### ISSUE TITLE
Diagnostics script

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#100]
Make a script that will verify functionality of the Pi-hole so users can see if it is working properly.

**Comment by dschaper** [comment]
If you use nslookup (not installed by default, at least not in the Jessie Lite version...) you would be able to check if the resolver is using the right server and check if the address returned is correct. Maybe a `head gravity.sh

**Comment by fayetted** [comment]
I just confirmed that nslookup and dig are both absent in a fresh install of Jessie-lite, however after the install of the dependencies, dnsutils is installed and includes both nslookup and dig.

What are your thoughts about testing for: 
1. Good domains - Google, openDNS, something that is relatively static
    Check that at least the 1st/2nd octet does NOT match (192.168.*, 10.*, 172.16-31)
2. Blacklisted domains - Pull a few names from the gravity.list file.
    Check that the IP resolves to the IP of the current system.
3. Whitelised domains - Pull a few names from the whitelist.txt file.
    Check that the IP matches the RFC1918 addresses from Test 1 (192.188.*, 10.*, 172.16-31.*) 

I might work on this in the next day or two.

**Comment by Mcat12** [comment]
Sounds good

**Comment by jacobsalmela** [comment]
Added in [v2.6](https://github.com/pi-hole/pi-hole/releases/tag/v2.6)
```
/usr/local/bin/pihole -d
```
