### ISSUE TITLE
Pi-Hole Dhcp server

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1003]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Any way to reserve ip address in pi-hole dhcp?

Got some NAS's there need a special IP :)

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Yep, this is on the road map for 2.11 :) We just wanted to get DHCP in some form first!

**Comment by DL6ER** [comment]
Meanwhile, you can manually edit `/etc/pihole/dhcp.leases` and add a for your NAS line in there.

**Comment by Tntdruid** [comment]
Thanks :)

**Comment by Tntdruid** [comment]
Any plan on IPv6 support for the Pi-hole dhcp server?

**Comment by Thumpxr** [comment]
Furthermore, what about renaming / adding comments to DHCP devices? Right now i have several android devices with a generic Hostname which i want to keep track of..

**Comment by dschaper** [comment]
Please register your feature requests at http://discourse.pi-hole.net so we can track them. Issues will be closed that do not have any bug reports or software issues.

**Comment by DL6ER** [comment]
Please read what you submitted in the issue.

> Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

This is very true. Things that are not immediate bugs (which we can work on) get lost in issues. Please use Discourse. We answer posts there with the same enthusiasm and speed we do on GitHub issues.
