### ISSUE TITLE
DNS breaks upon install (Fedora)

### ISSUE THREAD

**Issue by bcambl** [pi-hole/pi-hole#1019]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [x] 8

---
**[BUG | ISSUE] Expected Behaviour:**

System DNS should remain functional during and after installation

**[BUG | ISSUE] Actual Behaviour:**

DNS is lost on Fedora after static IP has been configured causing the remainer of the installation to fail

**[BUG | ISSUE] Steps to reproduce:**

- Fresh install on Fedora Based Linux Distro

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mukrosz** [comment]
Hi there,
My OS is CentOS 7.3.1611, close enough to Fedora.
This has been brought up in other issues, but to re-iterate, this DNS issue is real for me too (fresh, existing installs). Let me know if i can help testing. Again, I realize this is Fedora centered but I thought it was relevant to CentOS.

**Comment by bcambl** [comment]
That would be great. Take a look at my PR #1020.
