### ISSUE TITLE
Log not flushing at midnight

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#1035]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
5
_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

stats should reset at midnight
**[BUG | ISSUE] Actual Behaviour:**

log did not flush lastnite at midnight
**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by C4Wiz** [comment]
another midnite and another log not flushed,

**Comment by xxcriticxx** [comment]
i have same problem my looks stock on 23:49:59 and its 11:00 am right now 

![capture](https://cloud.githubusercontent.com/assets/15007183/21471930/dbc5fea2-ca91-11e6-870b-166eaa27665a.PNG)

**Comment by DL6ER** [comment]
Please verify that `/etc/cron.d/pihole` is the same as: [pihole.cron](https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.cron)

**Comment by DL6ER** [comment]
Otherwise, you can check in your `/var/log/syslog` (may also be `/var/log/syslog.1`, /var/log/messages`, or `/var/log/cron`, depending you your OS) that it contains something similar to this line:
```
Dec 25 00:00:01 raspberrypi CRON[17798]: (root) CMD (   /usr/local/bin/pihole flush)
```

**Comment by xxcriticxx** [comment]
@DL6ER i on ubuntu 16.04 what you want me to test?

**Comment by DL6ER** [comment]
Look at my recent comment. In one of the files you should find what `cron` did when.

**Comment by xxcriticxx** [comment]
ok let me check

**Comment by xxcriticxx** [comment]
@DL6ER i dont see line like that 

syslog = `http://pastebin.com/tvJC5h6m`
syslog.1= `http://pastebin.com/7RLJdjy9`

**Comment by DL6ER** [comment]
Look at your `syslog.1` in line 161, there it is.
```
Dec 25 00:00:01 critic CRON[8943]: (root) CMD (   pihole flush)
```

I'm currently doing further investigations.

**Comment by xxcriticxx** [comment]
yes i just found as well

**Comment by DL6ER** [comment]
I might have found the problem, a PR will be linked to this issue automatically.

**Comment by C4Wiz** [comment]
Once again i am super impressed by the speed of the fix!

How do i apply this fix?

**Comment by DL6ER** [comment]
Overwrite your `/etc/cron.d/pihole` by this file (this is what the PR will change):

https://github.com/pi-hole/pi-hole/blob/a0e0465036eb4fab12851165d97ce709c0e73880/advanced/pihole.cron

I'm not absolutely sure if this is the actual problem, but I'm like 90% certain.

**Comment by DL6ER** [comment]
Meanwhile, you can use

```
pihole flush
```

to flush the log file manually

**Comment by xxcriticxx** [comment]
@DL6ER thx for help we will see what happens tonight

**Comment by DL6ER** [comment]
Update released
