### ISSUE TITLE
ads on guardian.co.uk being shown randomly

### ISSUE THREAD

**Issue by PartisanEntity** [pi-hole/pi-hole#1036]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[ISSUE] Expected Behaviour:**

When visiting independent.co.uk I see some ads sometimes. I added those domains to my blacklist and do not expect to see those ads anymore.

**[ISSUE] Actual Behaviour:**

Despite adding those domains to my blacklist I am still seeing those ads sometimes. The other times I do not see them. I have not figured out why.

**[ISSUE] Steps to reproduce:**

- Go to guardian.co.uk
- Find the domains to blacklist such as 2mdn.net or adition.com
- Reload the page
- Ads still appear

**(Optional) Debug token generated by `pihole -d`:**

`kts7lrjrxa`

**Comment by Mcat12** [comment]
Make sure that your DNS cached is flushed and that the ads that do appear aren't from a different domain. If you see the ads and can't reach http://pi.hole/admin, then your client isn't using Pi-hole as its DNS server at that moment.

**Comment by PartisanEntity** [comment]
I have checked the ads and they appear from the domains I have blacklisted. I can also reach the admin interface. As for using Pi-hole as DNS server I have set my router to point to my Pi-hole installation.

**Comment by Mcat12** [comment]
Are the domains blocked if you ping them from your client? If they aren't, are they blocked if you ping them from the Pi-hole? If the Pi-hole has them blocked but not the client, then the client's DNS cache needs to be flushed. If both don't have the domain blocked, then run `cat /etc/pihole/gravity.list | grep some_domain` where `some_domain` is the domain you're checking. If the domain is found using that command, then make another debug log and navigate to that site while the debug log is collecting a log snippet.

**Comment by dschaper** [comment]
One month with no reponse.
