### ISSUE TITLE
pi-hole's hostname doesn't resolve (when DHCP is turned on)

### ISSUE THREAD

**Issue by checktravis** [pi-hole/pi-hole#1042]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_2_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

With DHCP turned on, the device's hostname should resolve like other devices.

**[BUG | ISSUE] Actual Behaviour:**

hostname of the pi-hole does not resolve.

**[BUG | ISSUE] Steps to reproduce:**

Ran curl or gravity.sh, navigated to /admin and activated DHCP, then restarted dns via the button on the same page. from a terminal, tried ping mypiholename  and tried ping mypiholename.mypiholedomain - both failed.

Additional info:
Installed on an orange pi pc plus running ARMBIAN Ubuntu 16.04.1 LTS 3.4.113-sun8i
No problems with the install script, everything worked with no intervention. Past non-raspberry installs have involved fixing the web server or php installations, but this worked beautifully, just this one small issue. Nice work, donating additional gratitude after I submit this ;)

 

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
- Have you disabled the previously existing DHCP server in your network (most likely in your router)?
- Have you reconnected the client devices after enabling the DHCP server on the Pi-hole (they have to register with the Pi-hole DHCP server at least once and clients only do this on a physical reconnection event (unplug/plug cable, disable/enable Wi-Fi, etc.)).

**Comment by dschaper** [comment]
One month with no response.
