### ISSUE TITLE
[REQ/TUT] PiHole traffic through VPN, Possible?

### ISSUE THREAD

**Issue by kronflux** [pi-hole/pi-hole#1044]
Here's what I want to do:

Have my main internet connection go through my VPN provider(I use PIA)
Host PiHole so it's requests also go through VPN
Connect to websites through VPN, using PiHole DNS.

I was thinking something along the lines of running openvpn client to connect to the VPN, using openvpn server to host that VPN'd connection as a new connection, and use PiHole as the DNS.

Is something like this possible?
I prefer the security and anonymity of using a VPN provider, but I want the ad-blocking on the backend that PiHole provides. I also don't want to risk the DNS leakage by using PiHole as my DNS through my local internet connection though.

**Comment by norrkin** [comment]
Very possible - https://github.com/pi-hole/pi-hole/wiki/Pi-hole---OpenVPN-server

For added security you can setup DNSCrypt and use a resolver that has DNSSEC enabled with the above solution.

**Comment by kronflux** [comment]
awesome! Although this is only part of the problem. The other part is getting all of the above traffic to go through a VPN service like PIA(Private Internet Access).
Any thoughts?

**Comment by norrkin** [comment]
You'd want "redirect-gateway def1 bypass-dhcp" and "setenv opt block-outside-dis" in your openvpn client config.

This would force all traffic via your vpn as well as all dns queries.  Not sure how much control you'd have with PIA but this can easily be achieved via a personal VPS following the above tutorial.

**Comment by sschadwick** [comment]
You'd likely have to use a customizable OpenVPN client to connect rather than the official PIA client

**Comment by PromoFaux** [comment]
Closing as it's not really an issue, but feel free to continue the discussion!

**Comment by PromoFaux** [comment]
Just for future reference @kronflux, we have a [discourse forum](https://discourse.pi-hole.net) which is better suited for discussion! :)
