### ISSUE TITLE
chronometer script not found

### ISSUE THREAD

**Issue by K-Ko** [pi-hole/pi-hole#1049]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG]:**

Chronometer script is not found

    # pihole -v
    ::: Pi-hole version is v2.10.2 (Latest version is v2.10.2)
    ::: Web-Admin version is v2.2 (Latest version is v2.2)

**[BUG | ISSUE] Expected Behaviour:**

    /etc/.pihole/advanced/Scripts/chronometer.sh

**[BUG | ISSUE] Actual Behaviour:**

    # pihole -c
    /usr/local/bin/pihole: Zeile 100: /opt/pihole/chronometer.sh: Datei oder Verzeichnis nicht gefunden

**(Optional) Debug token generated by `pihole -d`:**

`0fs01fjpmp`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
What is the content of your `/opt/pihole` folder?

```
ls -lh /opt/pihole
```

**Comment by K-Ko** [comment]
# ls -lh /opt/pihole
    insgesamt 72K
    -rwxr-xr-x 1 root root  13K Dez 23 19:45 gravity.sh
    -rwxr-xr-x 1 root root 4,4K Dez 23 19:45 list.sh
    -rwxr-xr-x 1 root root  12K Dez 23 19:45 piholeDebug.sh
    -rwxr-xr-x 1 root root  547 Dez 23 19:45 piholeLogFlush.sh
    -rwxr-xr-x 1 root root 2,9K Dez 23 19:45 setupLCD.sh
    -rwxr-xr-x 1 root root 5,9K Dez 23 19:45 uninstall.sh
    -rwxr-xr-x 1 root root 6,2K Dez 23 19:45 update.sh
    -rwxr-xr-x 1 root root 3,9K Dez 23 19:45 version.sh
    -rwxr-xr-x 1 root root 7,4K Dez 23 19:45 webpage.sh

**Comment by DL6ER** [comment]
Hmm, and what about in `/etc/.pihole/advanced/Scripts/` ?
```
ls -lh /etc/.pihole/advanced/Scripts/
```
during the installation or update all scripts from this folder should have been copied to `/opt/pihole`

**Comment by K-Ko** [comment]
Looks "almost" the same :-)

    # ls -lh /etc/.pihole/advanced/Scripts/
    insgesamt 56K
    -rwxr-xr-x 1 root root 4,8K Dez 24 06:37 chronometer.sh
    -rwxr-xr-x 1 root root 4,4K Dez 22 06:51 list.sh
    -rwxr-xr-x 1 root root  12K Dez 22 06:51 piholeDebug.sh
    -rwxr-xr-x 1 root root  547 Sep 13 03:12 piholeLogFlush.sh
    -rwxr-xr-x 1 root root 2,9K Okt 30 03:12 setupLCD.sh
    -rwxr-xr-x 1 root root 6,3K Dez 26 06:51 update.sh
    -rw-r--r-- 1 root root 3,9K Dez 22 06:51 version.sh
    -rwxr-xr-x 1 root root 8,0K Dez 26 06:51 webpage.sh

All files in `opt/pihole` are never (Dez 23 19:45), from update?

**Comment by DL6ER** [comment]
Yes, they are copies during install / update. It is very strange that `chronometer.sh` has not been copied for you...

For now just put a symbolic link there
```
cd /opt/pihole
ln -s /etc/.pihole/advanced/Scripts/chronometer.sh
```

**Comment by Mcat12** [comment]
Does `pihole -r` fix it?

**Comment by K-Ko** [comment]
Yes `pihole -r` fixed it.
