### ISSUE TITLE
Use another server instead of lighttpd on update

### ISSUE THREAD

**Issue by TheAntimist** [pi-hole/pi-hole#1053]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
3

---
**[OTHER]:**
I use the pihole on a nginx server because I have other things running as well, unfortunately the new update seems to have hardcoded to use lighttpd. So, it actually installs lighttpd this time, when I update to the latest version of pihole.

Any chance, this can be implemented to check if nginx or apache is used then not download and configure lighttpd?

**Comment by DL6ER** [comment]
@dschaper might want to comment on this

**Comment by PromoFaux** [comment]
Someone once submitted a pull request with `nginx` support (#271), though it was never merged. Perhaps we could revisit it.

**Comment by TheAntimist** [comment]
@PromoFaux For me atleast, I don't mind if the nginx support does not actually happen as long as lighttpd is not installed when nginx exists. Though, I'm fine with a dual install support. I can actually help out with the testing if need be.

One minor thing to address, is there a way to not overwrite an already existing conf, since, on my Pi the php-fmp.sock didn't really work, so I shifted it to a tcp port.

**Comment by dschaper** [comment]
We could run either a detection for usage of port 80 and/or check for the other packages installed and then notify the user that they will need to manually configure the web interface. With the new added ability to install to a non-standard port though there's another layer of complexity to figure out. If there is no `Pi-hole` web server at port 80, then you won't get the custom blockpage or any kind of response, and you may get leakage of the 404 page from the server on port 80 onto the blocked advertisement spaces. 

As for overwriting configs, I'll have to take a look and see what/where we copy and see if there's a need to do an existing file detection.

**Comment by TheAntimist** [comment]
@dschaper You can easily accomplish this ``dpkg-query`` or ``apt list --installed`` and use ``netstat`` for port checking, with ``grep``. And just ask the user based on the outputs of the previous commands, that ``nginx has been detected. Do you still want to install lighttpd?`` or something like that.

Does that sound feasible?

As to the rest, I think, it's perfectly fine to skip over the worrying about the existing logs and such, since I doubt, many have much use for that.

**Comment by boudjellamahmoud** [comment]
Hello everybody,

I think that it will be nice if we are given the choice of the web server we want at install. I'll help as much as i can if needed :-)

**Comment by C0rn3j** [comment]
@TheAntimist
Those are distro specific commands, which are not available on Arch Linux ARM for example.

➜  ~ apt
zsh: command not found: apt
➜  ~ dpkg-query
zsh: command not found: dpkg-query

**Comment by TheAntimist** [comment]
@C0rn3j Well, I took those out from the PR link which @PromoFaux posted. I had entirely forgotten about those. Not, my call in any case, it was just a suggestion.

**Comment by dschaper** [comment]
It will go in the Feature Request file, I think there's a topic already started over at our Discourse. It may not be something that is implemented soon, but it is an idea that we are looking at. And it's been a while since I've looked over at the AUR for the Arch package to see how the maintainer is doing, but from what I've seen there isn't a problem with portability. We'd be supporting the officially supported distro's first, and then the individual maintainers of the user supported distro's would upgrade as they were able to.

**Comment by TheAntimist** [comment]
@dschaper That sounds good. So should I close this issue, here?

**Comment by dschaper** [comment]
Yeah, we can pick it back up on Discourse, and make it votable, so it can jump in priority if there's a good demand for it.
