### ISSUE TITLE
Fix the firewall detection routine.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1054]
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

10

---

The firewall detection needs to check for:
- Missing kernel modules
- Non-insmod conditions
- Failures of any type
- Wide open firewalls that don't need rulesets applied.
- Add your requests here...

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Don't think we'll need the line by line check, the boolean conditions should cover all cases.

**Comment by Mcat12** [comment]
Did you mean to put that label on the PR?
