### ISSUE TITLE
Pi-hole is not blocking Ads

### ISSUE THREAD

**Issue by kunalspathak** [pi-hole/pi-hole#1062]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Expected to see Ads getting blocked.

**[BUG | ISSUE] Actual Behaviour:**
Ads are not getting blocked. Even on web page I don't see any Ads getting blocked. I tried all the steps in #622 but I am still not seeing ads getting blocked. Web page is showing below status. Currently I am on below version
```cmd
::: Pi-hole version is v2.10.2 (Latest version is v2.10.2)
::: Web-Admin version is v2.2 (Latest version is v2.2)

```

![pi-hole](https://cloud.githubusercontent.com/assets/12488060/21573645/d263edca-ce9b-11e6-90bd-c419b2b3c89e.png)

**[BUG | ISSUE] Steps to reproduce:**
- Setup pi-hole 
- open web browser and navigate to random sites
- The ads are seen

**(Optional) Debug token generated by `pihole -d`:**

`ix5du71uzq`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Looks like you may have `/etc/pihole/blacklists.txt` and `adslists` switched. All your blacklisted domains are in the wrong file as are the source adblock lists.

**Comment by kunalspathak** [comment]
Thanks @dschaper  for prompt response. How do I fix it? I have lot of files in `/etc/pihole/` with name `list.*.domains`, as well as `blacklist.txt`, `adlists.default`, `adlists.txt`. I never checked this folder until today, so not sure if they came from installation or some misconfiguration that I did.

**Comment by dschaper** [comment]
```
cd /etc/pihole
cp blacklist.txt blacklist.txt.orig
cp adslists.list adslists.lists.orig 
sudo mv adslists.list blacklist.txt
sudo mv blacklist.txt.orig adslists.list
pihole -r
```
Try that and see if you get a better response from the Pi-hole.

**Comment by kunalspathak** [comment]
I just uninstalled and reinstalled pihole and that solved my problem. Although the web page now says that is is blocking ads, there are still certain sites on which I am still seeing ads. Below are couple of examples.
- http://www.geeksforgeeks.org/
- http://www.geeksforgeeks.org/

**Comment by dschaper** [comment]
If the domains are serving their own ads, then you would need to clean up the outlier advertisements with an in-browser solution. We block at the DNS level, so if the ad comes directly from www.geeksforgeeks.org, then we can't block the ad domain, it would block the content as well. I just visited that site, and found one ad for cayenne, but everything else was blocked. That ad appears to be from d1hyf4ir1gqw6c.cloudfront.net when I visit, it may be different when you visit. 

Also, if you have recently visited the sites before starting the Pi-hole, it is possible that you have the advertisements in your cache. They should time out in the next 10 minutes or so, you can clear the DNS cache and webcache on your client if you would like to speed up the process.

**Comment by kunalspathak** [comment]
Right. On the same page, I do see ads from `googleadservices.com`. Do I just add this entry in blacklist or there is some other configuration i should be doing?

**Comment by dschaper** [comment]
If you go to the admin page, and then look for the history icon on the left hand side, you can bring up the history of domains that the Pi-hole has seen. You will also see if they are allowed or blocked, and you'll be able to blacklist any green domain or whitelist any red domains. (I find this to be the easiest solution, instead of using the commandline options.) Just keep in mind any changes may take a bit to see in effect since we have a 10 minute cache set up and your clients may still have the old data until that time expires.
