### ISSUE TITLE
Router Ignoring DNS Rules.

### ISSUE THREAD

**Issue by RagingGrim** [pi-hole/pi-hole#1069]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[QUESTION]:**

My question is rather on a router make than it is on pi-hole itself which is working if I configure my devices to use the pi as a DNS server rather than the entire network.

I am using a VEVG2660 router from Telkom ( provided with our line ) and have set it up to use my pi as a primary dns server. If I run sudo tail -f /var/log/pihole.log with that configuration no queries are logged. If manually set the DNS server on each particular device I can see the DNS queries. I'm assuming this has something to do with the router that was provided not having good quality firmware and ignoring the DNS rules. It wouldn't be the first time an ISP stock router has let me down. 

Can anyone confirm?

**Comment by PromoFaux** [comment]
It is indeed possible that the ISP provided router is ignoring your DNS settings. What kind of options does it give you to set the DNS, and how do you have it set?

If it is possible to turn off the DHCP server on the router, then you can enable DHCP service on pi-hole by navigating to the settings page on the Admin UI...

**Comment by DL6ER** [comment]
I have a similar issue with my stock router. It simply doesn't allow internal DNS addresses. Go ahead and use the Pi-hole DHCP server if you like. It does mostly autoconfig and will always point to itself as DNS server

**Comment by RagingGrim** [comment]
Ah I hadn't thought of that! Stock routers are trash x) Thank you so much!
