### ISSUE TITLE
Install config files in subdirectories

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#107]
Instead of replacing config files, place pihole specific config files in config.d sub-directories.

**Comment by dschaper** [comment]
dnsmasq seems to work with the configuration file in `/etc/dnsmasq.d/pihole.conf`. The only thing we need to watch is that if there are any duplicate configuration settings in `/etc/dnsmasq.conf` then the system throws an error. Working on an existing file check that is similar to the legacy pihole detection code.

**Comment by jacobsalmela** [comment]
This was added in 2.5.1 right?

**Comment by PromoFaux** [comment]
Yeah, this is live, issue can be closed...

**Comment by jacobsalmela** [comment]
Cool, thanks!
