### ISSUE TITLE
ping to pi-hole hostname from client pc returns 127.0.1.1

### ISSUE THREAD

**Issue by wikibit** [pi-hole/pi-hole#1070]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
I'm not sure whether the below is a bug or issue, more a question?

To clarify first: the the following devices in my LAN which take part in DNS/DHCP:
- 10.0.2.1 : firewall (pfsense), which also serves as DHCP server. 
This DHCP server will send 2 DNS servers to DHCP clients : 10.0.2.60 and 10.0.2.15 (in that order)
This DHCP server will register all dynamic and static mappings in my internal DNS server (10.0.2.60)
- 10.0.2.15 = my pihole server (app13-pihole) , which at this moment is using the google DNS as upstream dns servers
- 10.0.2.60 = my internal only DNS server (for all other LAN devices: A records & PTR records), this DNS server has no upstream servers, so it will only resolve queries for internal machines

**[BUG | ISSUE] Expected Behaviour:**
In my internal DNS (10.0.2.60) I've a static mapping of app13-pihole to 10.0.2.15 and reverse, under my internal domain (xxxxxxxxx.intra)
when I ping from I client to app13-pihole (with or without domain), I expect the ping to be answered from 10.0.2.15

**[BUG | ISSUE] Actual Behaviour:**
Today I got this 
```
C:\WINDOWS\system32>ping app13-pihole
Pinging app13-pihole.xxxxxxxxx.intra [127.0.1.1] with 32 bytes of data:
Reply from 127.0.1.1: bytes=32 time<1ms TTL=128
Reply from 127.0.1.1: bytes=32 time<1ms TTL=128
Reply from 127.0.1.1: bytes=32 time<1ms TTL=128
Ping statistics for 127.0.1.1:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

C:\WINDOWS\system32>ping app13-pihole.loftnet.intra
Pinging app13-pihole.xxxxxxxxx.intra [10.0.2.15] with 32 bytes of data:
Reply from 10.0.2.15: bytes=32 time=8ms TTL=64
Reply from 10.0.2.15: bytes=32 time=3ms TTL=64
Reply from 10.0.2.15: bytes=32 time=1ms TTL=64
Reply from 10.0.2.15: bytes=32 time=5ms TTL=64
Ping statistics for 10.0.2.15:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 8ms, Average = 4ms

C:\WINDOWS\system32>ping app13-pihole
Pinging app13-pihole.xxxxxxxxx.intra [10.0.2.15] with 32 bytes of data:
Reply from 10.0.2.15: bytes=32 time=1ms TTL=64
Reply from 10.0.2.15: bytes=32 time=2ms TTL=64
Reply from 10.0.2.15: bytes=32 time=5ms TTL=64
Reply from 10.0.2.15: bytes=32 time=3ms TTL=64
Ping statistics for 10.0.2.15:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 5ms, Average = 2ms
```

As you can see, the first ping responds from 127.0.1.1 
I found that out when I was trying to SSH into the pihole using the hostname and that didn't work
I tried a number of times to ping the pihole, for about 30 minutes, it only replied from 127.0.1.1 (of course, my ssh doesn't work to the loopback addres on my windows machine)

Without me making a change to my local ip settings, DNS, DHCP, pihole or internal DNS server, after some time, it worked again, a ping to app13-pihole replied again with 10.0.2.15

ALSO:
- the line graph on my admin page is empty since today
- the list of top advertisers is empty since today

adblocking itself still looks to be working as expected

**[BUG | ISSUE] Steps to reproduce:**
for now, I cannot reproduce it ... 

I expect it has something todo with the hostsfile on the pihole:

app13-pihole:~$ cat /etc/hosts
127.0.0.1       localhost
**127.0.1.1       app13-pihole.xxxxxxxx.intra      app13-pihole**

is it OK to change 127.0.1.1 into the real ip address of the pihole (10.0.2.15) or is there a compelling reason it has to stay 127.0.1.1 ?

Thanks

**Comment by Mcat12** [comment]
You can change your hosts file however you like, I don't think we modify it at all. The web interface issue is related to this one: #1071

**Comment by dschaper** [comment]
http://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

**Comment by jacobsalmela** [comment]
@wikibit did you end up changing your hosts file to be the IP of the Pi-hole?  

Just following up to see if @dschaper's link provided some insight.

**Comment by spacedingo** [comment]
I have the same result of ping returning from 127.0.1.1 with Debian 8, and Ubunto 14 & 16 virtual machines. However the good news is CentOS 7 just works - pinging pi-hole hostname returns from the proper IP.
I'm trying to look at how /etc/hosts and /etc/hostname differs in both.

**Comment by DL6ER** [comment]
I haven't following this discussion closely, but from what I can see here, I'd like to ask you to run the following two commands on the system where 127.0.1.1 is returned:

```
dig pi.hole
dig pi-hole @192.168.1.2
```
where you should replace `192.168.1.2` by the actual IP of your Pi-hole. Keep the `@`. Maybe both outputs are 100% identical - but maybe they aren't.

**Comment by spacedingo** [comment]
I'm not facing any issues as a consequence of this, and this is just FYI.
I always tried to ping the hostname plus the router domain which is **pi.lan**. I didn't know I could access **pi.hole** no matter what I named things..cool.

so ping looks like this
```
ping -n 1 pi.lan
Pinging pi.lan [127.0.1.1] with 32 bytes of data:
Reply from 127.0.1.1: bytes=32 time<1ms TTL=128

ping pi
Pinging pi [10.0.0.5] with 32 bytes of data:
Reply from 10.0.0.5: bytes=32 time=2ms TTL=64

ping -n 1 pi.hole
Pinging pi.hole [10.0.0.5] with 32 bytes of data:
Reply from 10.0.0.5: bytes=32 time=2ms TTL=64
```
dig pi.hole
```
; <<>> DiG 9.9.9-P5 <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56371
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.                       IN      A

;; ANSWER SECTION:
pi.hole.                300     IN      A       10.0.0.5

;; Query time: 3 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Feb 01 18:15:25 2017
;; MSG SIZE  rcvd: 52
```
dig pi.hole 10.0.0.5
```
; <<>> DiG 9.9.9-P5 <<>> pi.hole 10.0.0.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16772
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.                       IN      A

;; ANSWER SECTION:
pi.hole.                282     IN      A       10.0.0.5

;; Query time: 2 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Feb 01 18:15:43 2017
;; MSG SIZE  rcvd: 52

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60446
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;10.0.0.5.                      IN      A

;; ANSWER SECTION:
10.0.0.5.               1       IN      A       10.0.0.5

;; Query time: 2 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Feb 01 18:15:43 2017
;; MSG SIZE  rcvd: 53
```
dig pi.lan
```
; <<>> DiG 9.9.9-P5 <<>> pi.lan
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5868
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.lan.                                IN      A

;; ANSWER SECTION:
pi.lan.                 300     IN      A       127.0.1.1

;; Query time: 3 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Feb 01 18:18:57 2017
;; MSG SIZE  rcvd: 51
```

**Comment by Mcat12** [comment]
Check `/etc/hosts` to make sure you don't have a line mapping your hostname to localhost.

**Comment by spacedingo** [comment]
Both debian and ubuntu contain a second line `127.0.1.1 myhost.mydomain myhost` in the `/etc/hosts`. I changed it to a single line `127.0.0.1 localhost myhost.mydomain myhost` and don't get replies from 127.0.1.1 anymore.

**Comment by Mcat12** [comment]
Ok, that's a better fix. The web interface only reads the first mapped domain (`localhost`).

**Comment by andi448** [comment]
I have that exact same issue, but I cannot easily modify my /etc/hosts as I am using a Proxmox LXC with Debian 11.
My /etc/hosts looks like this (pihole doesn't alter this at all):
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# --- BEGIN PVE ---
127.0.1.1 test.lan test
# --- END PVE ---
```

And I want to migrate from my Raspberry Pi, which has this working /etc/hosts
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       pi
```

If I ping from my windows machine the hostname test, this is what happens in pihole:
```
May  8 13:07:26 dnsmasq[425]: query[A] deb.lan from fd00::xxx
May  8 13:07:26 dnsmasq[425]: /etc/hosts deb.lan is 127.0.1.1
May  8 13:07:26 dnsmasq[425]: query[AAAA] deb.lan from fd00::xxx
May  8 13:07:26 dnsmasq[425]: forwarded deb.lan to 192.168.2.1
May  8 13:07:26 dnsmasq[425]: reply deb.lan is NODATA-IPv6
```
And I will end up in pinging 127.0.1.1.

My question is now, is this a bug in pihole (or its dependencies) or is it not handled correctly by Proxmox itself?

**Comment by yubiuser** [comment]
@andi448 

You replied to an issue that was closed 5 years ago. It is very unlikely to be the exact same issue. Please direct all configuration issues to our support forum at https://discourse.pi-hole.net/

**Comment by andi448** [comment]
@yubiuser thanks for your feedback. For my understanding it seems never being solved by the project, yet. It was the user, who did local changes to his host config, so I think this is the exact same issue, which is still persisting.
Yes, I will do that.
