### ISSUE TITLE
"Queries over time"  and  Top Advertisers" list  are empty since 1 January 2017 on  Pi-hole Version v2.10.2 Web Interface Version v2.2 

### ISSUE THREAD

**Issue by Deacon-Medina** [pi-hole/pi-hole#1071]
[X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
 [X] The issue I am reporting can be *replicated*
[X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 1

**[BUG | ISSUE] Expected Behaviour:**
"Queries over time"  and  Top Advertisers" list  are empty since 1 January 2017

**[BUG | ISSUE] Actual Behaviour:**
"Queries over time" graph broken since this morning in Chrome, Pale Moon, and Light. Ran Bleachbit and cleared cache. Ran pihole -r,  Queries graph still broken in all my browsers."Top Advertisers" list has now become empty 

**[BUG | ISSUE] Steps to reproduce:**
Open Pi Hole Admin Console. Issue affects multiple users-see reddit: https://www.reddit.com/r/pihole/comments/5le5n4/pihole_blank_graph_top_advertisers_list/

**(Optional) Debug token generated by `pihole -d`:**
debug token is : bbekqtdy72

**Comment by norrkin** [comment]
Can confirm this issue also.  I have two instances running and both are affected.

**Comment by xxcriticxx** [comment]
what file do we edit to fix this?

**Comment by p1r473** [comment]
So the query log and pie charts (forwarded destinations,  query types) seemed to be fixed, but **queries over time still blank**:

![image](https://cloud.githubusercontent.com/assets/9235633/21626342/87387e7e-d1de-11e6-9da4-473e13839489.png)

**Comment by Mcat12** [comment]
@p1r473 what did you change? Doublecheck your changes.

**Comment by DL6ER** [comment]
Please post any error message you might see on the Developers Console (F12).

**Comment by dschaper** [comment]
@xxcriticxx Try a `pihole -up` to get the latest version with all the fixes.

**Comment by p1r473** [comment]
Seems to have fixed itself, looks like it took some time to populate this one after flushing the logs (the other ones populated instantly)
![image](https://cloud.githubusercontent.com/assets/9235633/21628222/c257e1fe-d1eb-11e6-9786-73dd0669fcdc.png)

**Comment by xxcriticxx** [comment]
@dschaper thx all updated now
