### ISSUE TITLE
Query Log Empty

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#1072]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

0

---
**QUESTION**

**[BUG | ISSUE] Expected Behaviour:**
Query log should populate. Picharts should populate.

**[BUG | ISSUE] Actual Behaviour:**
Query log and picharts don't populate.

**[BUG | ISSUE] Steps to reproduce:**
Just upgraded to the big new release. my query log and all picharts are no longer loading. I've tried flushing with a pihole -f. 

![image](https://cloud.githubusercontent.com/assets/9235633/21583113/f1c50e38-d03f-11e6-96b4-9964431b1891.png)
![image](https://cloud.githubusercontent.com/assets/9235633/21583125/6de6d294-d040-11e6-9990-15cc61d35a57.png)
![image](https://cloud.githubusercontent.com/assets/9235633/21583115/fd184098-d03f-11e6-847e-d053834e6c84.png)
The reason my upstream servers probably showing blank is I used the DNSCrypt tutorial.

**(Optional) Debug token generated by `pihole -d`:**

`8b47841auw`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
I think this issue is related to #1071

**Comment by p1r473** [comment]
Thanks!
