### ISSUE TITLE
Data tables error when polling query list

### ISSUE THREAD

**Issue by loaderladdy** [pi-hole/pi-hole#1075]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

View list of domains in the Query List
**[BUG | ISSUE] Actual Behaviour:**
See an error " DataTables warning: table id=all-queries - Ajax error " see the screen dump of the error for context

**[BUG | ISSUE] Steps to reproduce:**
Access the Query Log
-
-
![img_0403](https://cloud.githubusercontent.com/assets/15855352/21589880/5a6b9e8a-d0ee-11e6-9247-52ca65a8d6e9.PNG)

-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
This is a problem that has been reported at least 20 times in various issues. Usually it is connected to a too large log file. Please have a look if flushing the log works for you (see e.g. Settings page).

**Comment by loaderladdy** [comment]
Logs across my to pihole servers were over 100,000 enteries, so I can see why that might impact on performance.
I can see it is more a usability issue than a genuine bug.
Flushing the log might get rid of evidence when you are trying to cure overactive blocking, but the blocking will soon recreate itself in the new log and you can then use the new "Block/Add" Action button to add to the white/black lists.
Maybe one for a "hints and tips" section.
Cheers

**Comment by DL6ER** [comment]
Your log should be flushed at midnight. However, you can still experience problems if you are in an environment with lots of (or a few heavy) clients.

We are working on a database backend to resolve those problems.
