### ISSUE TITLE
Pi-Hole and 8-bit Netmask not working

### ISSUE THREAD

**Issue by BeanBagKing** [pi-hole/pi-hole#1076]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
When setting up the IP address, netmasks other than /24 should not experience issues.

**[BUG | ISSUE] Actual Behaviour:**
I'm using the 10.0.0.0/8 range for my internal (home) network. When configuring Pi-Hole, I reach the screen where it asks for IP address, and I supply it with a 10.0.2.x/8 address. 

After completing that, I run ifconfig and the broadcast is set to 10.0.2.255 with a netmask of 255.255.255.0, implying a /24.

If I rerun the setup, using reconfigure, I get to the static IP address portion and my current network settings have indeed been set to a /24.

Currently DNS works fine, however, this does cause routing issues. I can't SSH into the server or view the admin portal.

I believe you would find the same problems if using the 172.16.0.0/12 address space, or the entire 192.168.0.0/16 address space. Networking is a weak area for me, so if there is another problem with my setup causing this issue, or if this is by design, I apologize. 

**[BUG | ISSUE] Steps to reproduce:**

- Create a network using the 10.0.0.0/8 range
- Setup Pi-Hole, when reaching the IP address section use a 10.0.x.x/8 address
- Verify that the netmask is 255.255.255.0
- Rerun setup, network settings have been changed to 10.0.x.x/24

**(Optional) Debug token generated by `pihole -d`:**

`ffrlqo0oc2`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by bakman2** [comment]
pihole does not actually set your interfaces, but just needs it as input for the configuration and by the looks of it your pi has been configured as a /24

Can you do a `cat /etc/dhcpcd.conf | grep -i ip_address` and show the output ? 
btw a /8 network at home is a bit weird unless you expect 16777216 hosts in your network ?

**Comment by BeanBagKing** [comment]
static ip_addresses=10.0.0.80/24
static ip_addresses=10.0.2.3
static ip_addresses=10.0.2.3/16
static ip_addresses=10.0.2.3/8

So yes, there's some problems. I've commented out the first 3 of those, and everything seems to be working. I've recently updated a bunch of networking gear and changed pi-hole's address. Is there anywhere else you would suggest checking for misconfigurations and old settings?

I assumed I was relying on pihole to setup the interfaces as well. If it doesn't, then this ticket can probably be ignored (unless you see something else to be concerned with). Netmask and broadcast now appear to be correct

As for the /8, I just prefer the 10 range, and while I don't have that many hosts, it gives me room to expand and sort endpoints using static assignments.

Thanks for the help, and sorry about the false alarm.

**Comment by bakman2** [comment]
Good to hear that it is working.

For your network, I use the 10 range as well (I like the notation), but in the /24 range which gives 254 hosts to work with, which is more than enough. Most important thing about a network is: documentation/map - describing who has which IP (if defined static)

A network with more than 254 hosts will end up with major performance drops due to the broadcast domain becoming way too large and should have switched to VLANS long before that. 

To keep it simple for yourself, define a dhcp pool with a range from 10.0.0.100-149/24 and use static IP's for anything below that range.  eg. between .1-10 for network devices, .11-20 for servers, .21-30 for printers, still a lot of room left for other devices.
