### ISSUE TITLE
Can't see stats in the web interface after last update 

### ISSUE THREAD

**Issue by sdonavan** [pi-hole/pi-hole#1078]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG | ISSUE] Expected Behaviour:**
I expect to see both the div with the class 'user-panel' and the one with class 'sidebar-menu'. 

**[BUG | ISSUE] Actual Behaviour:**
Since the last update all I see is the 'sidebar-menu' div, which is over the 'user-panel' div containing the stats. (See picture bellow)
![pihole-screen](https://cloud.githubusercontent.com/assets/11685893/21596826/71426976-d149-11e6-8694-7a0abd47e591.png)

**[BUG | ISSUE] Steps to reproduce:**

- Open the web interface with Firefox version: 45.4.0 on linux

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Can you provide us with some more information via the debug token so we can see which version you are running and what your local installation looks like? Thanks!

**Comment by PromoFaux** [comment]
Can confirm broken in firefox too
![image](https://cloud.githubusercontent.com/assets/1998970/21596915/241899d6-d13a-11e6-9461-665a767c96e9.png)

But working fine in chrome:
![image](https://cloud.githubusercontent.com/assets/1998970/21596918/2ed4b940-d13a-11e6-83cb-acf6a860e10d.png)

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #321](https://github.com/pi-hole/AdminLTE/issues/321) via [**ZenHub**](https://www.zenhub.com/)
