### ISSUE TITLE
2.10.x to 2.11 Upgrade Instructions missing

### ISSUE THREAD

**Issue by draptik** [pi-hole/pi-hole#1081]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**No documentation how to upgrade**

Please "No documentation how to upgrade", so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

What is the recommended way of upgrading from version 2.10.x to 2.11?

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249

**Comment by draptik** [comment]
thanks!

**Comment by draptik** [comment]
Although I am using nginx...
