### ISSUE TITLE
Feature Request: Installationscript default webserver folder

### ISSUE THREAD

**Issue by LarsTi** [pi-hole/pi-hole#1082]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_6{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST]:**

It would be quite helpful if we could change the directory of the webadmin repository during the installation. Due to multiple pages running on the pi i (and i expect more than me) always manipulate the basic-install.sh with my own webInterfaceDir (line 27).
Furthermore it would be helpful to choose which webserver pihole should use. I am running apache and pihole is still requesting lighttpd, which i need to uninstall after a clean installation.

Cheers 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Send feature requests to Discourse as you have been told in the template:

> Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

It is difficult to track them as issues.
