### ISSUE TITLE
No status info in upper left corner

### ISSUE THREAD

**Issue by Przemo78** [pi-hole/pi-hole#1084]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
I am supposed to see info/status in my left upper corner of admin page.

**[BUG | ISSUE] Actual Behaviour:**
I can not see info/status in upper left corner. Firefox 50.1.0
The info/status is visible in Safari  10.0.2.
System macOS 10.12.2.
On Safari for iOS and Firefox web browser 5.3 (iOS 10.2) the problem does not exists.
﻿
[﻿﻿https://www.dropbox.com/s/hfedrowguh578pm/Zrzut%20ekranu%202017-01-03%2017.31.32.png?dl=0](url)

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
See pi-hole/AdminLTE#321
