### ISSUE TITLE
Admin page and graphs very slow to respond 

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1086]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG | ISSUE] Expected Behaviour:**
The admin page before the last major update responded within 3-5 seconds when accessed either from the IP or the hostname method

**[BUG | ISSUE] Actual Behaviour:**
the entire admin interfaces is extremely slow to respond in particular the main page as well as thre query log page are both very slow upwards of 30 seconds to load graphs and data

**[BUG | ISSUE] Steps to reproduce:**

-access admin interface
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<m0ms0tqggo>`

**Comment by DL6ER** [comment]
We have changed the algorithms used to compute the statistics and tables because we were seeing inconsistent results in high-density environments (that is due to the fact that we use asynchronous, aka non-blocking, logging). The new algorithms are always exact but they require processing the list of blocked domains each time something is computed.

You have more than one million blocked domains which might be problematic - especially on a less powerful device like a Pi Zero. Why do you use so many entries in the list?

**Comment by technicalpyro** [comment]
im showing in the admin interface 754k block but that's probably because some of the lists have duplicates.  that's neither here nor there.  currently running this on a pi2 and when trying to load and watching the resource graphs never goes above 50%.  

i am learning this system and linux still and i am willing to help where i can i just wouldn't even know where to start in terms of removing domains from being blocked i don't think that is the only solution to this

**Comment by Mcat12** [comment]
PHP is limited in how much memory it can use, so the total usage wouldn't go all the way to 100% when PHP is fully utilizing its share. More likely, the Pi is taking longer than 30s (the timeout limit) to generate stats, causing PHP to stop the script. You can increase this limit through PHP's config.

**Comment by technicalpyro** [comment]
i did edit the file /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
and changed the number of child allowed from 4 to 16

it makes the pages themselves load faster but the graphs are still slow to respond

**Comment by DL6ER** [comment]
The processing of the log data is slow. We are working on a few possible alternatives to PHP-processing independently.

**Comment by Tntdruid** [comment]
There was a version there used sqlite that was crazy fast.

**Comment by DL6ER** [comment]
I'm currently working on something that will be even faster than `crazy fast` even for several hundreds of thousands of queries on cheap hardware.

**Comment by Tntdruid** [comment]
@DL6ER nice :)

**Comment by jacobsalmela** [comment]
For those who haven't seen our preview yet...

https://pi-hole.net/2017/01/10/coming-soon-to-a-pi-hole-near-you-ftl/

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #385](https://github.com/pi-hole/AdminLTE/issues/385) via [**ZenHub**](https://www.zenhub.com/)
