### ISSUE TITLE
blocking internal sites

### ISSUE THREAD

**Issue by Binog** [pi-hole/pi-hole#1087]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{3}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
I can access icinga again

**[BUG | ISSUE] Actual Behaviour:**
If I want to access my icinga client, I get this page:
">>>Access to the following site has been blocked:
x.x.x.x/icingaweb/
If you have an ongoing use for this website, please ask the owner of the Pi-hole in your network to have it whitelisted.
This page is blocked because it is explicitly contained within the following block list(s):
Go back	Whitelist this page	Close window
Password required!
Domain: x.x.x.x
Password:
Whitelist
---> Success <---
You may have to flush your DNS cache<<<<"

First of all x.x.x.x can't be added to the Whitelist via the gui. Second.: x.x.x.x does show up in query logs, neither straight, nor reverse.

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<eb9yuihj5f>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Disable your Pi-hole and try accessing this page again. Sometimes there are also false-positives for the blcocking page, e.g. when you try to access a page on your Pi that does not exist!
![screenshot at 2017-01-04 11-46-03](https://cloud.githubusercontent.com/assets/16748619/21639986/58b11936-d273-11e6-8b7d-36d493cd8d02.png)

**Comment by moregeld** [comment]
Hey.
I am a n00b at this so forgive my lack of knowledge.
Today, I have updated the Pi-Hole only to come the above image - generally to access the page I would  access the page by typing the ip address of the device - e.g. http://10.x.x.x/pihole/index.php.  I am unable to add the IP address to the Whitelist - I have tried disabling the PiHole using Terminal - I have tried removing the DNS altogether and yet still not able to access the page.  Any advice/assistance would be awesome.
Thanks

**Comment by dschaper** [comment]
The address that you use is typical of a DietPi location, is that the distribution that you are running? Are you able to get to a console and run `pihole -d` just so we can take a look and make sure things look okay to troubleshoot?

**Comment by moregeld** [comment]
Thanks for your reply @dschaper - the debug code is 2w6z9qdy7d

**Comment by dschaper** [comment]
It does appear that your installation has multiple ip addresses. `.6` and `.7`. `ip a` should show the double addresses, do you mean to be running multiple interfaces? And there are some changes that DietPi still makes with the web interface that overwrites what we do in a typical install, so there might be issues generated via that process.

**Comment by moregeld** [comment]
Hmm .6 is what it should be - not sure what .7 is.

**Comment by moregeld** [comment]
Do you suggest @dschaper I should uninstall and reinstall the whole thing ?

**Comment by dschaper** [comment]
You can try that, there shouldn't be any damage to it. I'm not sure how 2 IP addresses were set, or if the movement of the `lighttpd.conf` files is affected by the DietPi installer however. So give a reinstall a try and see if that does help the situation.

**Comment by moregeld** [comment]
Too easy @dschaper - I'll give it a go later today and let you know how it goes

**Comment by moregeld** [comment]
@dschaper - I've reinstalled Pi-Hole and everything seems to be working OK - but I have notice that there are 2 IP addresses (probably similar to earlier) - this time on .9 and also .6 (.6 is what I use) - is there anyway to remove it from x.x.x.9 ?

**Comment by moregeld** [comment]
Never mind  I think i have found the solution.

**Comment by jacobsalmela** [comment]
@moregeld what did you find out?

**Comment by moregeld** [comment]
@jacobsalmela - I found out the a clean install resolved most things

After a new reinstall - I found out that I was still gettting 2 ip's. One from dhcp and another random ip. Both pointing to the rpi. 

Then removed dhcp and set a static ip which remove the 2 IP address and been working flawlessly since !

**Comment by dschaper** [comment]
Great to hear! Let us know if you run into any other issues.
