### ISSUE TITLE
Dead link on home page

### ISSUE THREAD

**Issue by rolandoldengarm** [pi-hole/pi-hole#1088]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

The link on the home page to: **Get LED alerts for each blocked ad**
links to:
http://www.stinebaugh.info/get-led-alerts-for-each-blocked-ad-using-pi-hole/

which is a dead link.

**Comment by Mcat12** [comment]
Fixed by #1090
