### ISSUE TITLE
Ubuntu - No DNS queries

### ISSUE THREAD

**Issue by rolandoldengarm** [pi-hole/pi-hole#1089]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**
DNS queries are resolved

**[BUG | ISSUE] Actual Behaviour:**
When configuring a client to use my Ubuntu server, I get DNS timeouts

**[BUG | ISSUE] Steps to reproduce:**
- Installed on my Ubuntu 14.04 headless server. Static IP address assigned. No firewall configured.
- I am running a variety of services on that machine on different ports.
- Installation works fine. Can access admin page. Shows that it's online.
- When configuring any client, I get DNS errors. Nothing in the logs in the Pi Hole.

- Tried to re-install. 
- Telnet on port 53 times out.

**(Optional) Debug token generated by `pihole -d`:**
`wdtwu6t81l`

I have no idea what's wrong here. I've upgraded all packages; haven't upgraded to 16.04 yet, should I do that?
Not sure if it's related, but my  network structure is that:
- Router at 192.168.1.254 with DHCP
- Ubuntu server connected to router, static IP at 192.168.1.10, gateway 192.168.1.254
- WiFi router connected to router at 192.168.1.1. DHCP disabled of course.
- All clients connected to WiFi Router, so gateway is 192.168.1.1
- All clients can ping the Ubuntu server at 192.168.1.10 without any issue.
Isn't this a valid configuration? Other than Pi Hole everything works.

**Comment by Mcat12** [comment]
You have a different DNS server running on port 53 than dnsmasq.

**Comment by rolandoldengarm** [comment]
Ah.... I now remember I once tried to setup a DNS server, but never finished that. Will have a look later!
But shouldn't Pi Hole throw an error if something like this happens? There's nothing in the logs, all is green, etc. @Mcat12 
Thanks!

**Comment by DL6ER** [comment]
We check if the DNS server is listening of port 53. We don't check *which* DNS server is running there...
Your DNS server returned `status: SERVFAIL` after 49msec. So yeah, that one doesn't seem to work.

I'd suggest to uninstall the other DNS server and rerun the Pi-hole installer. Should fix the issue for you.

@dschaper Maybe we can test if another DNS server is installed (by package) on install?

**Comment by dschaper** [comment]
Looks like bind is running on that installation.

**Comment by dschaper** [comment]
We currently check in the debug process to see if there is another daemon and user running on ports 53 and 80, but agreed that it could be moved to the installation portion of the process and flag/fail/error if there is another daemon on that port. Port 53 is an absolute need, port 80 could soft fail if the user wanted to continue to install knowing that the web interface is not functional. 

Also could be extended to DHCP functionality, if enabled, check the wire for another daemon listening for lease requests... Good things to see if we can work in.

**Comment by rolandoldengarm** [comment]
Great stuff guys, thanks for the quick responses! A check at installation time would be a very nice to have.

**Comment by dschaper** [comment]
Moving to Discourse for Feature Request.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/existing-daemon-detection-on-installation/1440
