### ISSUE TITLE
Make "Queries over time" chart a 24-hr sliding window

### ISSUE THREAD

**Issue by chrissng** [pi-hole/pi-hole#1091]
I thought it will be much meaningful and it allows us to see information at anytime of the day. Might need be to fetch yesterday's log that was flushed after midnight. But if it's persisted on disk, I don't think it's very complicated to retrieve

**Comment by Mcat12** [comment]
This might be possible after we implement the database logging, but for now it would require a lot of rewriting and might cause errors, because we use the dnsmasq log directly and assume that the stats are only from today.

**Comment by Mcat12** [comment]
You can make a post on discourse.pi-hole.net for other users to vote on as well.

**Comment by DL6ER** [comment]
Also note our policy

> Failure to fill the template will close your issue

You completely erased the template. There you might have also found:

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

So ... closed
