### ISSUE TITLE
DHCP is not working

### ISSUE THREAD

**Issue by paulkramme** [pi-hole/pi-hole#1093]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Deactivated routers dhcp, activated pihole's dhcp, no pc detect it. Erased all previous connections in all machines, nothing.

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
We'll need a little more information to go on to see if we can help with this. Can you run the debug and get us the result token?

**Comment by paulkramme** [comment]
717hfh4qmg

**Comment by dschaper** [comment]
Thanks, looks like there may be a problem with `/etc/dnsmasq.d/02-pihole-dhcp.conf': No such file or directory` @DL6ER Does this file missing disable the DHCP functionality of the script?

**Comment by paulkramme** [comment]
Well, the interface is working, but a few dhcp server discoverer found nothing in my network.

**Comment by Tntdruid** [comment]
run as root
source /etc/pihole/setupVars.conf; source /etc/.pihole/advanced/Scripts/webpage.sh; ProcessDHCPSettings

Fixed the dhcp problems for me

**Comment by paulkramme** [comment]
Nope.

**Comment by DL6ER** [comment]
Interesting ...

```
sudo -s
source /etc/pihole/setupVars.conf; source /etc/.pihole/advanced/Scripts/webpage.sh; ProcessDHCPSettings
```
(the last one all in one line)
should have fixed it.

@dschaper We have fixed this in the release that is about to come out ...

**Comment by paulkramme** [comment]
Uhm... I does not work for me. Run this three times, on root, restarted all clients, purged all existing connections, still nothing.

**Comment by paulkramme** [comment]
Another log: yybtolpptd

**Comment by DL6ER** [comment]
Please update to the very latest version (released some seconds ago) and try again

**Comment by paulkramme** [comment]
Thereby i'll declare you the most awesome software developer i know. Thank you very much.
