### ISSUE TITLE
IE11: Unable to whitelist from block page

### ISSUE THREAD

**Issue by WaLLy3K** [pi-hole/pi-hole#1094]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[ISSUE] Expected Behaviour:**
When using Internet Explorer 11 on Windows 8.1 (and presumably anything else using the Trident engine instead of EdgeHTML), I should be able to click on the "Whitelist page" button, and have it reveal the `#whitelistingform` div through the use of jQuery.

**[ISSUE] Actual Behaviour:**
The `#whitelistingform` div does not reveal itself, because the browser's error console shows `'EventSource' is undefined, File: queryads.js, Line: 19, Column: 5`. From what I understand, this appears to be [expected behaviour for IE11](http://stackoverflow.com/questions/24498141/is-there-a-microsoft-equivalent-for-html5-server-sent-events).

If I remove the line `<script src="http://pi.hole/admin/scripts/pi-hole/js/queryads.js"></script>`, I am able to reveal the div but obviously, the page does not show the results of `pihole -q $serverName -exact`

**[ISSUE] Steps to reproduce:**
Click the whitelist button when using IE11.

**Hacky but quick workaround:**
```
// Insert before line 43 of index.php
// IE11 (and older?) EventSource Workaround
if (strpos($_SERVER['HTTP_USER_AGENT'], 'Trident') !== false) {
  exec('wget -qO - "http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain="'.$serverName.'"&exact" | grep -E "list.*\([1-9]" | awk -F"[\/ ]" \'{print $6}\'', $ie11);
}

// Replace line 71
<pre id="output" style="width: 100%; height: 100%;" hidden="true"><?php if (isset($ie11)) foreach ($ie11 as $num) { echo "$num<br/>"; } ?></pre><br/>

// Replace line 91
<?php if (!isset($ie11)) echo '<script src="http://pi.hole/admin/scripts/pi-hole/js/queryads.js"></script>'; ?>
```

As a side note, I'm super impressed with the speed of `queryads.php` over just running the appropriate bash command!

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I'm thinking what we can do about it. Your solution feels way too hacky for me, but you though so already too. Maybe we should use the detection you proposed and instead just show that this feature is not available with IE.

That fells like the _best_ solution, so far.

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #358](https://github.com/pi-hole/AdminLTE/issues/358) via [**ZenHub**](https://www.zenhub.com/)
