### ISSUE TITLE
pihole not updateable 

### ISSUE THREAD

**Issue by unixweb** [pi-hole/pi-hole#1095]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?: 5

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:
::: Pi-hole version is v2.11 (Latest version is v2.11.1)
::: Web-Admin version is v2.3 (Latest version is v2.3.1)
pi@piproxy:~ $ sudo pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!

**[BUG | ISSUE] Actual Behaviour:**

![bildschirmfoto 2017-01-05 um 09 21 21](https://cloud.githubusercontent.com/assets/12023025/21673306/9311cab6-d328-11e6-903a-bb718524d104.png)

**[BUG | ISSUE] Steps to reproduce:**
sudo pihole -up 
::: Checking for updates...
::: Pi-hole Core:   up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!

sudo pihole -v
::: Pi-hole version is v2.11 (Latest version is v2.11.1)
::: Web-Admin version is v2.3 (Latest version is v2.3.1)

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Marcellaoo** [comment]
confirming. the layer also show updates available

**Comment by DL6ER** [comment]
I suspect your system is using a non-English locale?

Please run:
```
cd /etc/.pihole
git status -uno
git status -sb
```

**Comment by unixweb** [comment]
Correct locale = LANG=de_DE.UTF-8

# git status -uno
Auf Branch master
Ihr Branch ist zu 'origin/master' um 6 Commits hinterher, und kann vorgespult werden.
  (benutzen Sie "git pull", um Ihren lokalen Branch zu aktualisieren)
nichts zu committen (benutzen Sie die Option -u, um unbeobachtete Dateien anzuzeigen)
root@piproxy:/etc/.pihole# git status -sb
## master...origin/master [hinterher 6]

**Comment by unixweb** [comment]
Thanks DL6ER 

it works now 👍 
::: Pi-hole version is v2.11.1 (Latest version is v2.11.1)
::: Web-Admin version is v2.3.1 (Latest version is v2.3.1)

**Comment by Marcellaoo** [comment]
>>Dann hab ich es kaputt gemacht ... mein Raspberry läuft auf en_US.UTF-8 und ich habe es daher nicht >>bemerkt...

muttu bessa aufpassen ;)

**Comment by Marcellaoo** [comment]
Thanks DL6ER -> is working 
!

**Comment by Tntdruid** [comment]
Odd update worked fine for me whit danish local

**Comment by DL6ER** [comment]
Maybe there is no Danish translation in your `git` binary. Is the output of `git --help` in Danish? Mine is in German.

**Comment by Tntdruid** [comment]
@DL6ER only show english

**Comment by DL6ER** [comment]
So, that's why is worked for you, you are not affected because your `git` is speaking English.

**Comment by DL6ER** [comment]
Update released

**Comment by unixweb** [comment]
Sorry but still exist the same issue

**Comment by DL6ER** [comment]
I know, first your updater has to be updated. It is solved *now*.

**Comment by unixweb** [comment]
pi@piproxy:~ $ sudo pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!
pi@piproxy:~ $ sudo pihole -v
::: Pi-hole version is v2.11.1 (Latest version is v2.11.2)
::: Web-Admin version is v2.3.1 (Latest version is v2.3.1)
pi@piproxy:~ $ sudo pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!

**Comment by unixweb** [comment]
Ahh okay , i have switch to english the "locale" .
We would see it works on next update .

**Comment by DL6ER** [comment]
You don't have to change to locale. You can do this once again:
https://discourse.pi-hole.net/t/updating-pi-hole-on-non-english-systems/1135

**Comment by unixweb** [comment]
its easier to switch the locale temporally 😀
