### ISSUE TITLE
Log Query Interface fails to display with error

### ISSUE THREAD

**Issue by ducatinut** [pi-hole/pi-hole#1097]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Launching log query results in following error dialog.

**[BUG | ISSUE] Actual Behaviour:**
![pihole-logqueryerror](https://cloud.githubusercontent.com/assets/4587462/21686071/013398ea-d332-11e6-93fb-6d32f31bd1c6.png)

**[BUG | ISSUE] Steps to reproduce:**
Pi Hole v 2.11.1 / Web Interface v 2.3.1 on Debian 8 Hyper-V VM. 2 procs, 1GB RAM
-Open log query console
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
You clicked

> The issue I'm reporting isn't a duplicate

But you haven't checked!

This has been reported dozens of times and has to do with that your Pi-hole has logged to many queries. Your hardware is not able to process the log before reaching the timeout.
