### ISSUE TITLE
DataTables Warning: table id=all-queries error

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1098]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Pi-hole hit 60k DNS Queries.

This popup:

![fullsizerender](https://cloud.githubusercontent.com/assets/72948/21694346/046a4204-d385-11e6-91e0-e53f23a074a8.jpg)

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
Go to http://pi.hole/admin/queries.php @ 60k DNS Queries.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`mi8025fvgd`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
This is a duplicate, please [search](https://github.com/pi-hole/pi-hole/search?q=DataTables+Warning%3A+table+id%3Dall-queries+error&type=Issues&utf8=%E2%9C%93) next time.

**Comment by TWhidden** [comment]
Can you reference the duplicate, because I can't seem to find it, and I was just about to open one.

**Comment by TWhidden** [comment]
We just set it up, and passed 60k queries today also with the same issue.  

![image](https://cloud.githubusercontent.com/assets/9921122/21696969/1a0cb2da-d345-11e6-95f9-7715c482d462.png)

**Comment by Mcat12** [comment]
That link I posted searches the issues for the exact title of this issue, which has been posted many times, so please click it and read through the issues/solutions. [This](https://github.com/pi-hole/AdminLTE/search?q=DataTables+Warning%3A+table+id%3Dall-queries+error&type=Issues&utf8=%E2%9C%93) is another list on the web repo.

**Comment by Mcat12** [comment]
For example, #638 #808 pi-hole/AdminLTE#130 etc

**Comment by DL6ER** [comment]
This is what you see when you click on @Mcat12's link:
![screenshot at 2017-01-05 21-48-27](https://cloud.githubusercontent.com/assets/16748619/21697020/c47aa876-d390-11e6-8056-f0c5345091d2.png)

And - there is more. We are working on a completely different implementation which will be ready for testing soon and should solve all issues even with > 100.000 queries. However, no ETA's.

**Comment by TWhidden** [comment]
Sweet.  We just deployed so we are very new to this.  Just trying to help.  The link you posted above just takes us to the search results I beleive. Is there a specific issue number that is used for managing this one issue? At least then I can subscribe to that as its updated / closed out.    Much appreciated.

**Comment by Mcat12** [comment]
Since many people post the same error message, we have a few issues which contain some information on fixing the issue. For this reason we do not have one single issue/thread for this bug. See [my previous comment](https://github.com/pi-hole/pi-hole/issues/1098#issuecomment-270753485). We will not be able to completely eradicate this from happening until we finish the rewrite we are currently developing, which will bring many performance upgrades. There is currently no ETA, sadly, as we are all volunteers working on the project.
