### ISSUE TITLE
Using TLS/HTTP2 breaks Query ad list

### ISSUE THREAD

**Issue by C0rn3j** [pi-hole/pi-hole#1100]
Using HTTP works fine as intended.

I am not certain what exactly breaks this(but it is HTTPS).

Package versions:
nginx-mainline 1.11.8-1
linux-raspberrypi 4.4.39-1
php-fpm 7.0.14-1
pi-hole-server 2.11.1-1

As you can see I'm using nginx and not lighttpd.

Logs - some of them might not be relevant as I've been trying to disable/enable HTTP2
http://pastebin.com/P5G0MDSL

Relevant part of the nginx config(ignore that 443 is commented out, it is normally enabled): 
http://pastebin.com/4fffPRy7

HTTP: http://i.imgur.com/aq9hKR4.png
HTTPS: http://i.imgur.com/FKwtIdV.png

---

    [X] I have read and understood the contributors guide.
    [X] The issue I am reporting can be replicated
    [X] The issue I'm reporting isn't a duplicate (see FAQs, closed issues, and open issues).

    How familiar are you with the codebase?: 1

**Comment by PromoFaux** [comment]
Please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when submitting a new issue. It's there to help us to help you!

**Comment by C0rn3j** [comment]
I've added the checklist to the bottom of the issue.

**Comment by C0rn3j** [comment]
Additionally, taillog seems to be broken too.

**Comment by DL6ER** [comment]
First result on Google for the error shown in your log:

> The error message “primary script unknown” is **always** related to a wrongly set SCRIPT_FILENAME in the nginx fastcgi_param directive.

I don't even see this directive in your config.

http://serverfault.com/questions/517190/nginx-1-fastcgi-sent-in-stderr-primary-script-unknown

**Comment by C0rn3j** [comment]
I fixed it myself, wanted to do a pull request but can't find anywhere in the github repo where 
admin/scripts/pi-hole/js/ folder is located, could someone point me in the right direction?

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #352](https://github.com/pi-hole/AdminLTE/issues/352) via [**ZenHub**](https://www.zenhub.com/)
