### ISSUE TITLE
[Hyperlink Bug] on pi-hole.net

### ISSUE THREAD

**Issue by DarkMatterMatt** [pi-hole/pi-hole#1101]
There is a link which goes to http://github.com/pi-hole/pi-hole/#automated-install, it should go to http://github.com/pi-hole/pi-hole/#one-step-automated-install

The link is under the installation section, step 2, _Run the install command_

**Comment by DarkMatterMatt** [comment]
@DL6ER thanks for the heads up, fixed (was trying to use the markdown hyperlink formatting, now it's just text)

**Comment by Mcat12** [comment]
Thanks, fixed
