### ISSUE TITLE
Something wrong trying to install

### ISSUE THREAD

**Issue by voltized** [pi-hole/pi-hole#1102]
http://prntscr.com/dscgas
help pls?

**Comment by dschaper** [comment]
Need more info please. What OS and version, what hardware, Pi or cloud.

**Comment by voltized** [comment]
I'm trying to do it on a Ubuntu VM, OS 16.04

**Comment by dschaper** [comment]
`curl -sSL https://install.pi-hole.net | bash -x` and get us the error that is displayed when the script exits to terminal.

**Comment by voltized** [comment]
http://prntscr.com/dscj23
cont: http://prntscr.com/dscj68

**Comment by voltized** [comment]
nothing else after that

**Comment by dschaper** [comment]
Okay, the `apt-get update` call is failing, there's something amiss on the VM. 

Are you able to complete an `apt-get update && apt-get upgrade` cycle to check the Ubuntu install?

**Comment by voltized** [comment]
http://prntscr.com/dscp89 I've got this from doing that

**Comment by dschaper** [comment]
That's an error with the VM installation and not something related to the Pi-hole. You'd need to check and see why `apt` is failing.

**Comment by dschaper** [comment]
Though it looks like you still have the `cdrom` repositories listed when you should have `http/https` addresses for the repositories.

**Comment by voltized** [comment]
Should I try it on virtualbox

**Comment by dschaper** [comment]
Have you rebooted the Ubuntu since you installed?

**Comment by voltized** [comment]
No I don't think so

**Comment by dschaper** [comment]
You may need to do that for the first boot process to run and for the repositories to be renamed from the CDROM defaults to their new locations. But again, this is unrelated to the Pi-hole installation.

**Comment by voltized** [comment]
Is it possible to setup pi-hole on an offshore VPS and link it up to my home connection?

**Comment by dschaper** [comment]
I personally don't know, have not tried it.

**Comment by voltized** [comment]
I've managed to upgrade it, trying pi-hole now

**Comment by voltized** [comment]
But there's also another issue, I don't have eth0 listed under ifconfig

**Comment by PromoFaux** [comment]
Closing this as it's a user issue, as opposed to an issue with the code. 

A more appropriate platform for help and discussion would be our [discourse forums](https://discourse.pi-hole.net)

Thanks!

**Comment by PromoFaux** [comment]
@voltized  I've opened up a thread for you on discourse

https://discourse.pi-hole.net/t/continuation-of-voltizeds-installation-issues/1167
