### ISSUE TITLE
issue with blocking

### ISSUE THREAD

**Issue by voltized** [pi-hole/pi-hole#1104]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

http://prntscr.com/dsd4am
not blocking ads but blocking that

**Comment by dschaper** [comment]
That's not a block, the green is allowed domains. Please use discourse.pi-hole.net for non-code related issues. Thank you. (An issue has been opened for you on Discourse to continue this discussion.)

**Comment by PromoFaux** [comment]
@voltized https://discourse.pi-hole.net/t/continuation-of-voltizeds-installation-issues/1167/1

Post up there!
