### ISSUE TITLE
Query logs show wrong year

### ISSUE THREAD

**Issue by abaumfalk** [pi-hole/pi-hole#1108]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG]:**
Query log date column shows all entries using current year instead of actual year of the entry.

**[BUG] Expected Behaviour:**
The query log page translates the content of /var/log/pihole.log into a webpage. The timestamp is expected to reflect the actual time of the query.

**[BUG] Actual Behaviour:**
The actual year of the event seems not part of the log. The query log page seems to add the current year to all of the events. This might be wrong. 

**[BUG] Steps to reproduce:**
1. add following line to /var/log/pihole.log, which might be generated on 31st of December 2016:
--
Dec 31 21:17:08 dnsmasq[462]: query[A] 0.debian.pool.ntp.org from 127.0.0.1
--
2. check query log page; it will show an entry dated:
2017-12-31T21:17:08

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Is your log being flushed every day? The cron job at `/etc/cron.d/pihole` should make sure that the only queries in the log are from the current day. Since dnsmasq does not give us the year, we have to assume it is the current year because we only keep the current day's log.

**Comment by abaumfalk** [comment]
There was no logrotate for the pihole logfile active. I wonder why...
Anyhow, wouldn't it be better to omit the year from the logview instead of assuming it? For sorting purposes one could simply enmuerate the logentries when reading them from the file so that the position in the file is preserved. This enumeration column could be presented to the user and he could use it for sorting.

**Comment by Mcat12** [comment]
We don't currently use logrotate, although there is a PR open for it: #1130 
What do you mean by enumeration column? A list of queries?
We'll consider removing the date, since all queries should be from the same day.

**Comment by DL6ER** [comment]
The linked pull request has been merged. `logrotate` will be used from the next release on. In addition, the future `FTL` API will handle the year differently and will work even if the log would not be rotated at the change of the year.

I will close this issue since it cannot be solved perfectly, since `dnsmasq` omits the year in the log as has also been pointed out by the issue reporter.
