### ISSUE TITLE
Cannot access Interface with IPv6 ULA | Ad Replace does not work

### ISSUE THREAD

**Issue by paulkramme** [pi-hole/pi-hole#1109]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_2_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
I want to be able to access Pi-Hole via ULA from local DHCPv6 Server
I want to be able to specify Pi-Hole as primary DNS with it's ULA
**[BUG | ISSUE] Actual Behaviour:**
I cannot access Pi-Hole via ULA: Failed Host Check: vs 192.168.178.20, [fd00::768e:ec4a:8a83:85b2], pi.hole, localhost
I cannot specify Pi-Hole's ULA in DNSv6 field in router ( i can, but it does not work)
Pi-Hole's Interface only shows global IPv6 address, which is useless, as it changes because of my ISP.

**[BUG | ISSUE] Steps to reproduce:**
See above
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`dzklv1uua9`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by paulkramme** [comment]
This is actually strange... YouTube ads are gone, doubleclicks not, others unchecked.

**Comment by Mcat12** [comment]
Try modifying `/etc/pihole/setupVars.conf` with the ULA and then run `pihole -r` and choose Repair. Are you trying to go to the web interface via the IPv6 address, or hostname?

**Comment by paulkramme** [comment]
Via IPv6. I modified it, ULA is showing up in interface but it's still not working...

**Comment by paulkramme** [comment]
After reconfigurating everything, Blocking works. It seems like DHCPv6 didn't push the new DNS server. This states another issue, instead of the usual white blocking i get an "May be down or has moved permanently" chrome page. Interface is still not reachable through IPv6 ULA.

**Comment by paulkramme** [comment]
![ytadblock](https://cloud.githubusercontent.com/assets/19418956/21750228/cd0a3edc-d5ae-11e6-84b5-eddb7ccab1f0.PNG)

**Comment by Mcat12** [comment]
Advertisements which are blocked over https will show that because Pi-hole doesn't have a correct certificate for that ad domain. Is lighttpd listening on that ULA address?

**Comment by paulkramme** [comment]
I checked /etc/lighttpd/lighttpd.conf
and there is no address specified at all, which is fine AFAIK.

**Comment by paulkramme** [comment]
I can also access the Pi Hole's main website with the ULA (the "This
website has been blocked website)... Only the /admin returns still Failed
Host Check: vs 192.168.178.20, [fd00::768e:ec4a:8a83:85b2], pi.hole,
localhost

**Comment by dschaper** [comment]
Not sure I'm following. ULA's are by definition non-routeable address space. What is the behaviour you would expect. ULA's are only applicable to the devices on the wire in the internal network.

**Comment by paulkramme** [comment]
The PiHole isnt reachable by any IPv6 address, neither Global, nor ULA. I
gave every device in my network an ULA because my globals are dynamic. ULA
for DNS works for that Pihole. The main website works. Only <ipv6/ipv6
ula>/admin does not work, which returns above error. The Pihole is in my
local network. So it should be (and is) reachable. Only the admin interface
isnt.

**Comment by dschaper** [comment]
And what does `ss -ltpn` show for the IPv6 listener for `lighttpd`?

**Comment by paulkramme** [comment]
LISTEN      0      1024                    *:80                     *:*
LISTEN      0      5                       *:53                     *:*
LISTEN      0      128                     *:22                     *:*
LISTEN      0      100                     *:25                     *:*
LISTEN      0      1024                   :::80                    :::*
LISTEN      0      5                      :::53                    :::*
LISTEN      0      128                    :::22                    :::*
LISTEN      0      100                    :::25                    :::*
pi@raspberrypi:~ $

**Comment by dschaper** [comment]
Try a `curl -I http://<IPv6 ADDRESS>` and see if you get an `X-Header` for Pi-hole.

**Comment by paulkramme** [comment]
HTTP/1.1 200 OK
X-Pi-hole: A black hole for Internet advertisements.
Content-type: text/html; charset=UTF-8
Date: Mon, 09 Jan 2017 06:01:57 GMT
Server: lighttpd/1.4.35

**Comment by dschaper** [comment]
Okay, so we know that the `lighttpd` is responding to requests. What happens when you try `curl -I http://<IPV6 ADDRESS>/admin/`

**Comment by paulkramme** [comment]
HTTP/1.1 301 Moved Permanently
Location: http://[fd00::768e:ec4a:8a83:85b2]/admin/
Date: Mon, 09 Jan 2017 06:11:31 GMT
Server: lighttpd/1.4.35

**Comment by dschaper** [comment]
Copy of `/etc/lighttpd/lighttpd.conf`? As well? You can `cat /etc/lighttpd/lighttpd.conf | nc tricorder.pi-hole.net 9999' if you'd rather not post it up here...

**Comment by paulkramme** [comment]
Done: 29oqg76t7j

**Comment by paulkramme** [comment]
I thought about adding server.use-ipv6 = true, but there is already something about "Trying to use IPv6, otherwise fall back to IPv4"

**Comment by dschaper** [comment]
The server is responding, and giving you either a 200 or a 301, so we know that it's listening to IPv6 and doing something, it's just that the 301 should be a redirect to `/admin/` from `/admin`

**Comment by paulkramme** [comment]
Great! Should i wait for a fix from your end, or try to fix it myself?

**Comment by dschaper** [comment]
Give it a try and see what you can come up with, the web guys are all asleep right now so it will be a while before they are up and around to check on things.

**Comment by paulkramme** [comment]
Oh well, I'm not a web guy either. Thank you for your support!

**Comment by dschaper** [comment]
Sure, we'll keep on working at it until we get a solution. (I'm an old Cisco routerjock, so I tend to stay away from the web things! :) )

**Comment by dschaper** [comment]
@Mcat12 or @DL6ER any thoughts on this one?

**Comment by Mcat12** [comment]
What is the output of `curl -I http://[fd00::768e:ec4a:8a83:85b2]/admin/`? How about `curl -I http://pi.hole/admin/index.php`? After that, send another debug token.

**Comment by paulkramme** [comment]
![screenshot_2017-01-18-06-09-26](https://cloud.githubusercontent.com/assets/19418956/22051672/245c1cc6-dd45-11e6-8b4f-e2a3d6bd7dbe.png)
![screenshot_2017-01-18-06-08-42](https://cloud.githubusercontent.com/assets/19418956/22051683/312d05f0-dd45-11e6-8329-191a4ba2f561.png)
itsi7v420s

**Comment by DL6ER** [comment]
Thanks. I still have no working IPv6 in my test environment, but that comes Monday (either that or I won't have internet connection at all, I guess).

Anyhow, I did some dry-runs and PHP doesn't like IPv6 (once again). See this issue (which is still open):

https://bugs.php.net/bug.php?id=72811

I'm working on a solution for your problem.

**Comment by DL6ER** [comment]
The PR shown above should fix the problem you described above:

> I cannot access Pi-Hole via ULA: Failed Host Check: vs 192.168.178.20, [fd00::768e:ec4a:8a83:85b2], pi.hole, localhost

In addition, you say "Ad Replace does not work". I'm not sure what the status is here.

**Comment by paulkramme** [comment]
Ad block does work, but the blank page replace does not (because of https). 

Thank you very much. Thats the reason why i like this project very much: The super fast, friendly and reliable support in addition to a very helpful program. Keep up the good work!

I will update my servers and then close the issue if the problem is resolved once its merged.

**Comment by DL6ER** [comment]
I've seen that this issue is already 11 days old, but to be honest I haven't noticed it until @dschaper [summoned me](https://github.com/pi-hole/pi-hole/issues/1109#issuecomment-273325595) since it was in the pi-hole repo instead of the AdminLTE repo. But I agree that it is not always obvious where issues should go.

**Comment by paulkramme** [comment]
What about making the PiHole repository, since its the product, the primary
issue base, and then put tags on everything that belongs to anything else.

>

**Comment by Mcat12** [comment]
We have found that keeping issues in the relevant repos is more organized and allows us to take advantage of Github's features best.

**Comment by DL6ER** [comment]
> I will update my servers and then close the issue if the problem is resolved once its merged.

@paulkramme Did you already made progress on this?

**Comment by paulkramme** [comment]
Updated the server over curl script, still not working. Did i update it wrong? Sounds stupid, but maybe do i have to install it manually? From a quick look at the basic install it plain and simple clones the repo, right?

**Comment by jacobsalmela** [comment]
@paulkramme, we released a new version today.  @DL6ER's [PR](https://github.com/pi-hole/pi-hole/issues/1109#issuecomment-273463570) was merged; will you report back if you are still having this issue?

**Comment by paulkramme** [comment]
I'm able to reach the admin page now, until i log in: Failed CORS:
http://fd00::768e:ec4a:8a83:85b2 vs 192.168.178.20,
fd00::768e:ec4a:8a83:85b2, [fd00::768e:ec4a:8a83:85b2], pi.hole, localhost

**Comment by DL6ER** [comment]
Hmm, that fails now at a different place in the code. Interestingly, I have been using the web interface for quite some time now in my IPv6-only environment at home, but never seen this. I'll put in a PR that will strip the extra "http://" you are getting in `$_SERVER['HTTP_ORIGIN']`.
