### ISSUE TITLE
Issues with PiHole on CentOS 6.8 x64

### ISSUE THREAD

**Issue by ethancedrik** [pi-hole/pi-hole#1110]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---

**[BUG | ISSUE] Expected Behavior:** For it to install and work

**[BUG | ISSUE] Actual Behavior:** Claimed it installed but didn't work

**[BUG | ISSUE] Steps to reproduce:**

Get a VM, Computer, etc running CentOS 6.8, go to the terminal and type in `curl -sSL https://install.pi-hole.net | bash` and try and get it to set up and install and then try and use it and visit the admin page, etc.

**(Optional) Debug token generated by `pihole -d`:**

Didn't work but here is the output from that command http://paste.thezomg.com/19997/08423148/

**Comment by PromoFaux** [comment]
@bcambl Might be able to help out with this.

I know for a fact that it works on CentOS 7, as per https://github.com/pi-hole/pi-hole/issues/1004

Have you had a look through previous issues regarding centOS 6? https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20Centos%206%20

**Comment by bcambl** [comment]
Since the project relies on _newer_ package versions, you may need to manually install a few packages.

Can you please provide the output of the following commands:
 - `getenforce`
 - `php --version`
 - `yum repolist`

Also, if you could re-run the installer and pastebin the standard output from the terminal.

**Comment by ethancedrik** [comment]
@bcambl Sure, here are the results, also I have reason to believe this script is trying to use Systemd commands but CentOS 6 uses Upstart.

`[root@vps ~]# getenforce
Disabled`

`[root@vps ~]# php --version
PHP 5.3.3 (cli) (built: Aug 11 2016 20:33:53) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies`

`[root@vps ~]# yum repolist
Loaded plugins: fastestmirror, presto
Loading mirror speeds from cached hostfile
 * epel: ca.mirror.babylon.network
repo id          repo name                                                status
base             CentOS-6 - Base                                           6,696
epel             Extra Packages for Enterprise Linux 6 - x86_64           12,216
extras           CentOS-6 - Extras                                            62
updates          CentOS-6 - Updates                                          712
repolist: 19,686`

and I'll rerun the installer and pastebin the output in a little bit

**Comment by bcambl** [comment]
Thanks for the additional info.
Yes, we are only using systemd/systemctl for service management because we only support the latest versions of CentOS and Fedora. _(currently centos7 and fedora25)_
We had the older commands used by CentOS6 in the installer when Fedora support was added to the project; however, We have since removed support for CentOS6 due to many package dependencies being too old in the default repositories. We did not want to start enabling/using unofficial package repositories so we decided to cut support and simplify the installer.

That all said, give me some time and I will provide some commands or a script to get you on track.

**Comment by bcambl** [comment]
The following should result in a command-line only pihole (see: `pihole -h`)
```
curl -sSL https://install.pi-hole.net | sed s/'procps-ng'/'procps'/g | bash

chown root:lighttpd /var/lib/php/ -R

chkconfig --add dnsmasq
chkconfig dnsmasq on
chkconfig --add lighttpd
chkconfig lighttpd on

service dnsmasq start
service lighttpd start
```
The version of PHP is too old and would require a later version among other issues.
I would recommend upgrading to CentOS 7 sooner than later.

**Comment by ethancedrik** [comment]
Thanks so much, yeah I've been looking into upgrading everything running 6 to 7 soon, I assume the old version of PHP is what would be holding back the web interface from functioning correctly, in which I could probably enable an unofficial repository to upgrade PHP to a newer version, which I may do as a workaround until I can do an OS upgrade.

**Comment by ethancedrik** [comment]
Yeah upgrading my PHP to PHP 7 using https://webtatic.com/packages/php71/ got the web interface working, once again thanks for all the help!

**Comment by ethancedrik** [comment]
One last question,
![1be620cf5918af4de12b8a27a4991581](https://i.gyazo.com/1be620cf5918af4de12b8a27a4991581.png)
How would I change the hostname there? I have mine set correctly as the kernel, /etc/hosts, and /etc/sysocnfig/network hostname but PiHole didn't seem to find it.

**Comment by bcambl** [comment]
`hostname -f > /etc/hostname`

Let me know if that helps.

**Comment by DL6ER** [comment]
`/etc/hostname` is the place where our code reads the local host name
```
$hostname = trim(file_get_contents("/etc/hostname"), "\x00..\x1F");
```

Isn't this universal?
@bcambl Can it be missing on a system like CentOS?

**Comment by bcambl** [comment]
It is missing in CentOS 6.
`/etc/hostname` is included in CentOS 7 and Fedora.

**Comment by ethancedrik** [comment]
> hostname -f > /etc/hostname

Yep that got PiHole to detect the hostname correctly

**Comment by bcambl** [comment]
Excellent.
Remember you will encounter the same issues when attempting to update PiHole in the future.

_**TL;DR:** Update to the latest CentOS/Fedora release for support._

If anyone else is wanting to install PiHole on CentOS 6, the following commands should get you there:
_**Warning:** The following is not recommended if you have other apps that rely on an older PHP version._
```
yum install -y wget yum-utils

wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
wget https://rpms.remirepo.net/enterprise/remi-release-6.rpm

yum install -y remi-release-6.rpm epel-release-latest-6.noarch.rpm

yum-config-manager --enable remi-php70

yum update -y

hostname -f > /etc/hostname

curl -sSL https://install.pi-hole.net | sed s/'procps-ng'/'procps'/g | sed s/'nmap-ncat'/'nc'/g | bash

chown root:lighttpd /var/lib/php/ -R

chkconfig --add dnsmasq
chkconfig dnsmasq on
chkconfig --add lighttpd
chkconfig lighttpd on

service dnsmasq start
service lighttpd start
```

The PiHole developers only support & test the latest CentOS _(currently 7)_ and Fedora  _(X+1)_.
Users of older versions may be required to perform some manual steps like above.

**Comment by dschaper** [comment]
Tagging as OOS since it's currently an unsupported platform, with possible support coming soon (TM).

**Comment by ethancedrik** [comment]
I have attempted to install this again, and now it appears as if it's broken again even with following the instructions above which previously worked

**Comment by ethancedrik** [comment]
I noticed it didn't install lighttpd or dnsmasq, I installed these manually and am now getting the default lighttpd page even after running the pihole installer with the above instructions multiple times, the root directory is the same as on rasbian but it doesn't appear to be putting any files for the web interface in.

I am running everything as root as well so that's not the issue, getenforce shows up as disabled and php -v shows up as
PHP 7.1.2 (cli) (built: Feb 18 2017 11:44:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by ethancedrik** [comment]
Is there a way I can somehow get and run an older version of the script that previously worked without having to manually download and compile an older version of pi-hole?

**Comment by ethancedrik** [comment]
trying using 

curl -sSL http://web.archive.org/web/20170203195418/https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh | sed s/'procps-ng'/'procps'/g | sed s/'nmap-ncat'/'nc'/g | bash

instead

**Comment by dschaper** [comment]
Which release of CentOS are you trying to get things running on? We really haven't supported anything prior to 7, we can look at 6 but with our limited resources it's probably not going to be something that can be done soon. If you'd like to visit https://discourse.pi-hole.net and add a Feature Request, then it can be voted on by the users and we can see how big the demand is for the feature. If there is a large demand for it, then we can bump the priority up accordingly.

**Comment by ethancedrik** [comment]
it is 6.8 x64, and it has worked in the past on this version but somehow
along the line of new releases since Jan 2017 it's been broken and no
longer fully installs on this OS for some reason

**Comment by bcambl** [comment]
I just tested the [previous commands](https://github.com/pi-hole/pi-hole/issues/1110?_pjax=%23js-repo-pjax-container#issuecomment-271169458) I provided. It seems everything updated fine for me.
Please ensure you are executing the commands one-by-one.

From my test environment:
```
[root@centos6 log]# cat /etc/redhat-release
CentOS release 6.8 (Final)

[root@centos6 ~]# php -v
PHP 7.1.2 (cli) (built: Feb 15 2017 08:51:17) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

[root@centos6 log]# pihole -v
::: Pi-hole version is v2.13.1 (Latest version is v2.13.1)
::: Web-Admin version is v2.5.1 (Latest version is v2.5.1)

[root@centos6 log]# curl -I http://192.168.1.219/admin/
HTTP/1.1 200 OK
X-Pi-hole: The Pi-hole Web interface is working!
X-Powered-By: PHP/7.1.2
Set-Cookie: PHPSESSID=p0rmpm2oe49pm9o6lvvn8pc2m4; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-type: text/html; charset=UTF-8
Date: Wed, 08 Mar 2017 05:59:02 GMT
Server: lighttpd/1.4.45

[root@centos6 log]# curl -I http://192.168.1.219
HTTP/1.1 200 OK
X-Powered-By: PHP/7.1.2
Content-type: text/html; charset=UTF-8
Date: Wed, 08 Mar 2017 05:59:05 GMT
Server: lighttpd/1.4.45

[root@centos6 log]#
```

**Comment by ethancedrik** [comment]
I've tried on multiple fresh CentOS 6 installs including using VPSs from providers such as Vultr, etc which have worked in the past but now fail.

I run all the steps above, then the installer ends with
:::
::: SELinux Support Detected... Mode: Disabled
:::
::: Stopping dnsmasq service... done.
:::
::: Stopping lighttpd service... done.
RTNETLINK answers: File exists
[root@host ~]# chown root:lighttpd /var/lib/php/ -R
chown: invalid group: `root:lighttpd'
[root@host ~]#

and the rest of the commands return errors or fail.

My only guess is that something has changed in the pihole install script or pihole itself from now and then that is causing it to not install correctly.

**Comment by bcambl** [comment]
I have found your issue.
When prompted `Do you want to use your current network settings as a static address?`
Select `No`
Do the following:
- Remove the CIDR from the IP at the IP Address prompt ie:
If your IP is formatted `xx.xx.xx.xx/32` then remove `/32`
- Remove the trailing space from the Gateway prompt

The install should continue and exit with the following:
`Enabling dnsmasq service to start on reboot...`

Now run the remaining commands from my previous post.

ie:
```
chown root:lighttpd /var/lib/php/ -R

chkconfig --add dnsmasq
chkconfig dnsmasq on
chkconfig --add lighttpd
chkconfig lighttpd on

service dnsmasq start
service lighttpd start
```

Once again, if you are performing a fresh install, please upgrade to CentOS 7.

**Comment by ethancedrik** [comment]
Thank you, this worked perfectly!
