### ISSUE TITLE
Pi-hole is blocking internet for internal network under W10

### ISSUE THREAD

**Issue by user-name-is-alreadytaken** [pi-hole/pi-hole#1121]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
After the last update of pi-hole, my internet is being blocked, and I can not get into the admin-page (page is being blocked). This happens on all computers in my local network and all browsers I've tried (Firefox, Chrome and Edge).
It's almost as if pi-hole is reversed: I'm being treated as an ad.

I also had to hard reset my router before I was able to get the DNS-server listing adjusted to ignore pi-hole.

I've tried now a fresh installation of Raspbian and pi-hole but the same behaviour occurred: web-admin page is being blocked. So I skipped the DNS change in my router, wouldn't want to go through the whole reset and installing the permissions.

I have zero to very little knowledge of any Linux/Unix and installed pi-hole using this blog: https://eye-vision.homeip.net/blog/2016/04/14/raspberry-pi-gebruiken-als-adblocker-dns-server/, 
skipping the installation of vi (comes with Raspbian now) and smb/CIFS (no use for it).

**[BUG | ISSUE] Steps to reproduce:**
The update of a working installation of pi-hole as well a fresh installation (even Raspbian) causes the problem.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>` 5rvr2g7z7f

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jwgn** [comment]
Are you sure you're trying to access the correct page ("admin" instead of "pihole")?
http://<piholeip>/admin/

**Comment by user-name-is-alreadytaken** [comment]
Yes, I'm sure.

But I've uninstalled pihole and reinstalled it with sudo curl and now it seems to be working.
What I noticed when uninstalling was that there were maps/directories missing (went to fast to see what they were but I thought something with configs).
Anyway, after the installation with sudo it seems to be working allright again. So I'm a bit optimistic about having pihole running again.

**Comment by PromoFaux** [comment]
>but I thought something with configs

does `setupVars.conf` ring a bell?

**Comment by user-name-is-alreadytaken** [comment]
Could be. And there was another file/map/directory missing but I can't remember what that was.

Like I said, I have little knowledge of Unix/Linux/Debian so all these files and directories, which are so common to the experienced user, are all the same to me.

**Comment by PromoFaux** [comment]
Fair point. But it appears to be working after a reinstall?

**Comment by user-name-is-alreadytaken** [comment]
Yes, after reinstall with "sudo curl -L install.pi-hole.net | bash" it seems to be working allright again.

I'm very pleased because it's some fine app you've all built.

**Comment by PromoFaux** [comment]
I just noticed you put a debug token in your original post, is that from the original (non-working) install? Looking at the debug log, everything appears as though it should have been working! Odd..

But glad it's sorted now, enjoy pi-hole!

**Comment by user-name-is-alreadytaken** [comment]
I don't remember if the log was from the first or the second reinstall (sorry, too much other things going on).
In any case, there was never a log from the updated original install because the pi was rendered inaccessable (even with SSH).

**Comment by DL6ER** [comment]
Real life issue solved, githuib issue closed

**Comment by Mcat12** [comment]
You might have accidentally set the router's gateway as the Pi-hole, which would cause those symptoms.

**Comment by user-name-is-alreadytaken** [comment]
No, I did nothing to the router. It went awray after an update from the admin web-page.
Next times updates with "pihole -up" via SSH only.
