### ISSUE TITLE
Login issues when using ReverseProxy

### ISSUE THREAD

**Issue by wioxjk** [pi-hole/pi-hole#1122]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
2
---
** QUESTION**

Can't login using ReverseProxy

**[BUG | ISSUE] Expected Behaviour:**

Being able to login

**[BUG | ISSUE] Actual Behaviour:**

Not able to login (sort of):
"Failed CORS: mydomain vs 192.168.2.19, 192.168.2.19, pi.hole, localhost"
But, when I click "back" in the browser - I am suddenly logged in (that is not expected)

**[BUG | ISSUE] Steps to reproduce:**
- Set up pi-hole
- Set up apache2 with ReverseProxy:
        #Pi-HOLE
        ProxyPass "/pi-hole"    "http://192.168.2.19/admin/" connectiontimeout=5 timeout=30
        ProxyPassReverse "/pi-hole" "http://192.168.2.19/admin/"
        RewriteRule ^/pi-hole$ http://%{HTTP_HOST}/pi-hole/ [L,R=301]
- Try to login via DOMAIN/pi-hole
- Click "back" in the browser takes you to the site.

**(Optional) Debug token generated by `pihole -d`:**

`9edik2chdx`
(seems like it does'nt have any useful information)

Relevant log entries:

[Tue Jan 10 10:56:19.129821 2017] [proxy:error] [pid 23794] [client 193.14.90.12:11329] AH00898: Error reading from remote server returned by /pi-hole/queries.php, referer: https://mydomain/pi-hole/gravity.php

**Comment by DL6ER** [comment]
Is there any setting in apache2 where you specify `mydomain`?
If so, that setting should be `pi.hole`

**Comment by wioxjk** [comment]
My domain is my domain - which I own and administrate.
Setting it to pi.hole is stupid and impossible. 

This is not really an external issue, pi-hole should be able to have "ServerAlias".

**Comment by DL6ER** [comment]
> Setting it to pi.hole is stupid and impossible.

You should have mentioned that you replaced your domain by `mydomain` in the error message. But not doing so you mislead me thinking into the wrong direction.

This is stupid.

Nevertheless, we will still help you now that you provided required information. Go to your `/var/www/html/admin/scripts/pi-hole/php/auth.php` and append `your domain` here:

https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/auth.php#L22

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #351](https://github.com/pi-hole/AdminLTE/issues/351) via [**ZenHub**](https://www.zenhub.com/)
