### ISSUE TITLE
REQUEST: Option to send logs to a remote logserver

### ISSUE THREAD

**Issue by wioxjk** [pi-hole/pi-hole#1126]
As the title suggested, the option to send the logs to a remote syslogserver via port 514 TCP/UDP.

**Comment by PromoFaux** [comment]
Please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when submitting a new issue. It's there to help us to help you!

Please pay particular attention to this part of the issue template: :)

>[FEATURE REQUEST | QUESTION | OTHER]:
>
>Please submit your feature request here, so it is votable by the community. It's also easier for us to track.

**Comment by PromoFaux** [comment]
Almost..... 

>**Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests)**, so it is votable by the community. It's also easier for us to track.

**Comment by wioxjk** [comment]
@PromoFaux 
Sorry about that
