### ISSUE TITLE
Autoinstaller script does not ask for network interface

### ISSUE THREAD

**Issue by keanemind** [pi-hole/pi-hole#1129]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
The pi-hole installer script should let me choose a network interface during installation. 

**[BUG | ISSUE] Actual Behaviour:**
I started a new Digital Ocean VPS and set up OpenVPN on it, since I want to use OpenVPN with pi-hole. I then ran the pi-hole installer script, but it never asked me to choose my network interface. I checked my droplet's network interfaces and tun0 was there, but the pi-hole installer didn't bring up the "Choose An Interface" menu. I checked in setupVars.conf and it turned out that the installer chose eth0 for me. 

**[BUG | ISSUE] Steps to reproduce:**
-Open a new Digital Ocean droplet. 
-Run the pi-hole basic-install.sh script. 

 It will skip past choosing an interface and the first thing it will ask is which upstream DNS provider you want.

**Comment by Mcat12** [comment]
We recently released a [hotfix](https://github.com/pi-hole/pi-hole/releases/tag/v2.11.2) which fixes a bug like you are describing. Have you tried the latest installer?

**Comment by keanemind** [comment]
I ran into this problem yesterday and replicated today when I used 
```
wget -O basic-install.sh https://install.pi-hole.net
bash basic-install.sh
```
Does that mean I used the latest installer? If not, how do I use the latest installer?

**Comment by DL6ER** [comment]
> Does that mean I used the latest installer?

Yes. The installer may not have asked you for an interface because it skips interfaces with status `UNKNOWN` or `DOWN`.

Please provide the output if 
```
ip a
```

**Comment by keanemind** [comment]
```
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.8.0.1 peer 10.8.0.2/32 scope global tun0
       valid_lft forever preferred_lft forever
```
They all say unknown or down except eth0, so it looks like that's why I couldn't choose tun0. But how do I bring it up? I've tried `sudo ip link set dev tun0 up` but nothing changed.

**Comment by dschaper** [comment]
I'm researching this now, was there a guide that you followed to set up the OpenVPN server? I'd like to see if I can duplicate the process. And are you connected via the OpenVPN client when you try to set up the Pi-hole installation?

**Comment by DL6ER** [comment]
His
> Steps to reproduce
are incomplete since he didn't provide the method he used to install the OpenVPN service.

Maybe he used our own tutorial?
https://github.com/pi-hole/pi-hole/wiki/Pi-hole---OpenVPN-server

**Comment by keanemind** [comment]
I didn't want to use the road warrior installer so I didn't follow your guide. Instead, I used this one: 
https://www.linode.com/docs/networking/vpn/set-up-a-hardened-openvpn-server
and 
https://www.linode.com/docs/networking/vpn/tunnel-your-internet-traffic-through-an-openvpn-server

I didn't do anything that seemed like it would affect my network interfaces. It was mostly setting up the client authentication keys after installation (first link) and editing the iptables on my server (second link). 

> And are you connected via the OpenVPN client when you try to set up the Pi-hole installation?

I've tried running the installer when my iPhone was connected to the VPN and when it wasn't connected. Both times the installer skipped the interface selection menu. 

I don't think this is related, but when I ran the pi-hole installer the first time and it automatically selected eth0 for me as the interface, I actually let it complete the installation even though I wanted it to be tun0. Afterward, I found that my configuration to tunnel all traffic through my VPN apparently got messed up because I couldn't load IP addresses on my iPhone's Safari browser any longer when connected to the VPN.  

To troubleshoot this, I tried making pi-hole choose tun0 as the interface by changing the option in setupVars.conf, but that didn't help. I've reset the droplet to the snapshot I took right after I installed OpenVPN so I can try something different when installing pi-hole this time.

**Comment by keanemind** [comment]
For future reference, is there a way for me to change pi-hole's interface in a configuration file somewhere?

**Comment by dschaper** [comment]
You can edit `/etc/pihole/setupVars.conf` and then to move that edit into the `dnsmasq` configuration you'll need to run `pihole -r` and select Repair.

**Comment by keanemind** [comment]
Wow, that worked perfectly! Thank you.
