### ISSUE TITLE
Gravity ignores final URL if on final line in adlists.list

### ISSUE THREAD

**Issue by WaLLy3K** [pi-hole/pi-hole#1132]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[ISSUE] Expected Behaviour:**
If you insert any number of lists (e.g: 5) without a newline at the bottom into `/etc/pihole/adlists.list`, I expect `list.0.domain.net.domains` through to `list.4.domain.net.domains` to be created

**[ISSUE] Actual Behaviour:**
`list.4.domain.net.domains` is not created, and gravity makes no mention that it is retrieving a fifth list

**[ISSUE] Steps to reproduce:**
```
[ -f "/etc/pihole/adlists.list" ] && sudo mv /etc/pihole/adlists.list /etc/pihole/adlists.list.BAK
printf "http://v.firebog.net/filegen.php?v=1\nhttp://v.firebog.net/filegen.php?v=2\nhttp://v.firebog.net/filegen.php?v=3\nhttp://v.firebog.net/filegen.php?v=4\nhttp://v.firebog.net/filegen.php?v=5" | sudo tee /etc/pihole/adlists.list
pihole -g
ls /etc/pihole/
```

What will work:
```
printf "http://v.firebog.net/filegen.php?v=1\nhttp://v.firebog.net/filegen.php?v=2\nhttp://v.firebog.net/filegen.php?v=3\nhttp://v.firebog.net/filegen.php?v=4\nhttp://v.firebog.net/filegen.php?v=5\n" | sudo tee /etc/pihole/adlists.list
```

Note that `?v=5` has `\n` afterwards.

`filegen.php` is simply a vessel of dummy data:
```
<?php
echo "test".rand ("0", "9999").".com
";
?>
```

**Comment by DL6ER** [comment]
Confirmed. See PR #1133 

Having a newline at the end of a file is considered good practice and usually the case. Therefore, many editors even force you to have a newline at the end by adding a newline (if there is none) as soon as you save the file.
