### ISSUE TITLE
RE: DNSMasque not starting on Raspi 2 Jesse

### ISSUE THREAD

**Issue by gstew08** [pi-hole/pi-hole#1134]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{2}_

---
**[ISSUE] :**

Everything was working fine for a few hours until i lost DNS from the pihole.
web interface says dns not on
on inspection dnsmasque gives the following error;

DNSmasque is not starting due to a conflict on line 37 on 01-pihole.conf

**[Troubleshoot]:**

This seems to coincide with the line "cache-size=10000" 

I've tried deleting dnmasque and reinstalling, changing cache size to 0, also running the pihole installer again, but the error still happens.

Pihole DNS was forwaded in DHCP via a tp-link ac750 router. I also have several smart devices whose DHCP come from that router.( incase it helps)

Am I missing something? I really want to keep pihole on my pi adn would greatly appreciate the help.

**Sorry if this is in the wrong formatting, first time writing an issue and also in github. It's probably something simple just wrecking my head over it

**Comment by Tntdruid** [comment]
Did you set cache-size=10000"? Pi hole already set a cache-size in a conf.

**Comment by DL6ER** [comment]
We will walk thorugh your issue with you.

> This seems to coincide with the line "cache-size=10000"

So this is a very good starting point. This particular line is not allowed to be repeated. So it seems very likely that something unexpected happened, e.g. `dnsmasq` was updated and the updater altered some configurations files. Check this:

1. Does `/etc/dnsmasq.conf` exist? If it does, comment everything out or empty out/delete the file.
2. Do an `ls /etc/dnsmasq.d/`. What is the content of this folder? Might be that there are files which should not be there if 1. didn't help already.

**Comment by gstew08** [comment]
I checked my /etc/dnsmasq.d/ and i did indeed have a second file in there. 01-pihole,conf.back (as i was trying to comment out the logging)

i assumed incorrectly that it would be ok and that dnsmasq was looking for a particular file not just any file, hence the confliction error.

Thanks DL6ER and much appreciated.

**Comment by DL6ER** [comment]
You are welcome.

Some extra information: `dnsmasq` skips those file which end with `~` or `#`

**Comment by gstew08** [comment]
thanks i'll keep note of that
