### ISSUE TITLE
Modifying the 'Website Blocked' page

### ISSUE THREAD

**Issue by dintendocoltd** [pi-hole/pi-hole#1137]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[QUESTION]:**

- Where is the 'Website blocked' webpage stored on the pi?

**Comment by DL6ER** [comment]
`/var/www/html/pihole/`

**Comment by dintendocoltd** [comment]
Thanks!
