### ISSUE TITLE
Invalid DHCP lease time after pihole -up

### ISSUE THREAD

**Issue by saspus** [pi-hole/pi-hole#1138]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2
---
**[BUG | ISSUE] Expected Behaviour:**
If DHCP lease time is set to a number of hours in the ui, e.g. 24 it will be written into 
 /etc/dnsmasq.d/02-pihole-dhcp.conf
as 
dhcp-range=10.0.17.50,10.0.17.254,**24h**

It is expected that updating pi-hole will preserve this setting.

**[BUG | ISSUE] Actual Behaviour:**

Once update is available and 
pihole -up 
is executed dnsmasq fails to start due to the above line becoming

dhcp-range=10.0.17.50,10.0.17.254,**24hh**

**[BUG | ISSUE] Steps to reproduce:**

Install pihole
In Web Interface in Advance settings for DHCP set lease time to 24.
Save
Update pi-hole to a new version via command line
Observe dnsmasq fail to start. 
Run dnsmasq to see the error:

```
pi@rpi3b:~ $ dnsmasq 
dnsmasq: bad dhcp-range at line 6 of /etc/dnsmasq.d/02-pihole-dhcp.conf
```

To recover - edit that file manually and change **24hh** to **24h**, then restart dnsmasq

**(Optional) Debug token generated by `pihole -d`:**

`ts27jxf0mn`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
1. In Web Interface in Advance settings for DHCP set lease time to 24.
 Saving it on the web Settings page calls [this](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/savesettings.php#L371)
 The backend get is getting it [here](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L240)
 And applies it [here](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L204)

 As you can see, only the very last line adds the `h` to the end of the number

2. Update pi-hole to a new version via command line
 That will run [this](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L204) code again.

The bug you are seeing can only happen if you are in a very special situation:  Activate DHCP server with a version of Pi-hole that did not yet supports setting the leasetime via web + Update to a version we put up for less than one day. What you are seeing was fixed afterwards, i.e. that should not affect many users. Updating to the current version will always be fine except if your settings in `setupVars.conf` is correct.

Solution to your problem: You can either go to the Settings page and click on [Save] in the DHCP block without changing anything, or you can edit your `setupVars.conf` and remove the `h` at the end of `DHCP_LEASETIME=`. Both should be equivalent.

**Comment by saspus** [comment]
Awesome! Thank you for quick response and detailed insight into the internals;
It is very likely I did indeed pick up the buggy version during that one day window - since I updated immediately after announcement and this bug persisted each update since
. 
I've saved settings from UI and verified that there is no "h" in setupVars.conf anymore 

Thank you.

**Comment by DL6ER** [comment]
You are welcome, I will close this issue now. It will be available through Search if someone encounters the same problem.

**Comment by linuxdood** [comment]
I had this issue re-occur with my last two updates.
 I am currently at:
::: Pi-hole version is v2.12.1 (Latest version is v2.12.1)
::: Web-Admin version is v2.4 (Latest version is v2.4)

Once I edit the conf file and remove the extra 'h' all is well. However, when I run the update command when I an update is available, it goes though the whole upgrade process successfully, but at the very end when services restart, dnsmasq fails to start... I am assuming it pulls the exisitng config from setupVars

I have now removed it from setupVars.conf, which by the explanation above should cure it permanently, but thought I should mention it.

cheers.
-y

Cheers.
