### ISSUE TITLE
Gravity re-retrieves lists without "Last-Modified" header

### ISSUE THREAD

**Issue by WaLLy3K** [pi-hole/pi-hole#1139]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[ISSUE] Expected Behaviour:**
When running gravity on URLs that do not have a `Last-Modified` header (e.g: `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`), the list should not be retrieved if there is no new content.

**[ISSUE] Actual Behaviour:**
Gravity will re-download the list on the second update despite there being no new content.

**[ISSUE] Steps to reproduce:**
Remove all URLs in `adlists.list` except say, Steven Blacks hosts (or anything else hosted on Github), and run gravity twice.

Thoughts:
`curl` is programmed to use the `-z` option ([gravity.sh L145](https://github.com/pi-hole/pi-hole/blob/cd0c3f941804ea7f44912b8be2e8341b4a3ae2f2/gravity.sh#L145)), which requests a file that has been modified later than the given time and date. If a file has been modified before that time, it returns "304 Not Modified". I believe this is determined by checking the `Last-Modified` header (if my understanding is correct). Since Github doesn't provide a `Last-Modified` header, one needs to use the [`ETag` header](https://en.wikipedia.org/wiki/HTTP_ETag) for web cache validation.

**Comment by DL6ER** [comment]
`curl` is just a utility for performing http requests. It doesn't automatically record response headers such as the Cookie or the ETag header.

Using the `Last-Modified` header can be done conveniently with curl. For your request we would need to store extra information for each list (which the current way we save it does not allow conveniently).

Furthermore, this not a bug/issue but a feature request in my eyes. Please open a Feature Request on Discourse for this so we can keep track on this when rewriting the backend to store more data per list (like also [alternative download destinations of the primary destination is not reachable](https://discourse.pi-hole.net/t/fallback-if-adlist-query-fails/1246)).
