### ISSUE TITLE
uninstall doesn't work

### ISSUE THREAD

**Issue by frakman1** [pi-hole/pi-hole#1140]
`pihole uninstall` is supposed to return my pi to a usable state. Unfortunately, it did not. The Pi was stuck wit the static address that was assigned to it during pi-hole setup (on all interfaces). This prevented me from going online even after uninstalling and moving to a different network.

The fix was for me to change `/etc/dhcpcd.conf` and remove these lines at the end:

```bash
#static ip_address=10.0.0.5
#static routers=10.0.0.1
#static domain_name_servers=10.0.0.1
```

I also had to change `/etc/dhcpcd.conf` to change all the interfaces' references from `static` to `dhcp`

Please try and incorporate this into your uninstall script to help others who might face this issue.

**Comment by dschaper** [comment]
Agreed, the uninstall script needs a lot of work for it to be fully functional. There's a couple of questions on how to implement, probably will involve a dialog box asking the user if they want to remove the static IP, and also which packages to remove. (Also `dhcpcd5` on non-Raspberry implementations is going to be an issue.)

Thanks for the information, and sorry we left a mess when we uninstalled.

**Comment by frakman1** [comment]
I understand that the uninstall path will depend on what was chosen during the install. In that case, you could add 'the choice to use a static IP address' to a log/config file that is then used in the uninstall process. 
<br>A dialogue box would add unnecessary confusion to the uninstaller who just wants to revert state and not agonize over every detail (just my experience).
