### ISSUE TITLE
pihole it's asking every time for the password to login in /admin/ webmodule

### ISSUE THREAD

**Issue by tudormateescu** [pi-hole/pi-hole#1144]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

1. A new pi-hole installation on a fresh ubuntu 14.04 lxc cointainer.
2. When entering admin module 10.8.0.1/admin/ after logging in, and navigating the passwords is asked again.
3. Also I can't add domain in black list/white list and the admin module doesn't know if pi-hole is up I have both enable and disable links active - which in previous version this doen't happened.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Generate a debug log (`pihole -d`), upload it and provide the token in order to provide valuable information we can use to try to reproduce your issue.

**Comment by tudormateescu** [comment]
: Your debug token is : mghs7jtlqa

**Comment by Mcat12** [comment]
Did you install Apache on that server? It might be related to a rare bug we've seen where Apache is installed as part of PHP. Try removing apache and restarting.

**Comment by WaLLy3K** [comment]
For what it's worth, I've had issues 2 and 3 occur when cookies are disabled - for whatever reason, it also makes the Admin Console load pages considerably quicker.

**Comment by DL6ER** [comment]
@WaLLy3K which pages load quicker w/o cookies? We only store a single hash in order to be able to identify users which successfully logged in. No tracking or other nasty things are going on!

![screenshot at 2017-01-16 15-59-19](https://cloud.githubusercontent.com/assets/16748619/21987695/d4714236-dc04-11e6-8bd8-c9cb8e387b64.png)

**Comment by DL6ER** [comment]
Will most likely be fixed by https://github.com/pi-hole/AdminLTE/pull/362

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #363](https://github.com/pi-hole/AdminLTE/issues/363) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ichbinpete** [comment]
in chrome, i cleared the cookie for the site and shift refreshed and was able to login and see data again
