### ISSUE TITLE
Redirect pi.hole to pi.hole/admin

### ISSUE THREAD

**Issue by Oxreim** [pi-hole/pi-hole#1153]
As is, I keep on going to pi.hole in order to view the dashboard and keep having to go to pi.hole/admin instead. As it is now pi.hole doesn't appear to have much of any purpose so it should not interfere with anything to setup a simple URL redirect to make accessing the administration console just that bit easier. Thank you.

**Comment by technicalpyro** [comment]
to my knowledge and one of the devs or wally3k ight know better the pi.hole page is used to display a custom block page and is how the device on an address level blocks

**Comment by Mcat12** [comment]
You deleted the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md), which says:
> Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

It also says:
> **Failure to fill the template will close your issue**

So please follow the issue template.
