### ISSUE TITLE
Upstream DNS showing google in webGUI

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1154]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
**[BUG | ISSUE] Expected Behaviour:**
on a new install the upstream DNS showing in the web interfaces shows as being google no matter what s set in the vars.conf file

**[BUG | ISSUE] Actual Behaviour:**
no matter what dns is set during setup or during a reconfiguration the web interface seems to default as using google despite the dns servers in vars.conf being what they were changed to ie using open DNS still showing google

**[BUG | ISSUE] Steps to reproduce:**

-fresh install OR pihole -r (reconfiguration)
-select upstream DNS other than Google
-View web gui and see it still indicates using google 
-

**(Optional) Debug token generated by `pihole -d`:**

**Comment by DL6ER** [comment]
Please generate a debug token so we can have a look.

**Comment by technicalpyro** [comment]
7tn0xgio76

what i have done to solve this for myself was to verify the dns in vars.conf and change it in the webguyi to my preferred upsream DNS provider 

i am willing to re-install to replicate issue and provide debug tokens at each step if that is needed

**Comment by dschaper** [comment]
Looking at the debug shows that `dnsmasq` is operating with the following:
```
Upstream Servers:
"208.67.220.220#53 3386 8" "208.67.222.222#53 2044 2"
```

So the Pi-hole is querying OpenDNS properly. Can we get a screencap of the admin interface showing the settings page. (Please redact any information you don't want shown, or if you'd prefer to send it via email so that it's not public, adblock@pihole.net is the email address for the developers.)

**Comment by technicalpyro** [comment]
give me a few moments i am going to uninstall and reinstall as i have my own setup working and directed correctly (tried to explain that) and was why i didnt include a debug token originally 
to reiterate (and hopefully explain better)
installed or reconfigured pihole
logged into webadmin saw it claim to be using googles dns for upstream
changed to open dns on primary and secondary in webadmin interface
verified it was using correct in the vars.conf file

**Comment by dschaper** [comment]
Yeah, that was me that asked you to open an issue :smile: I'll run some installs here as well to see if I can confirm the situation.

**Comment by technicalpyro** [comment]
am doing the same right now will run a debug after each step and collect them

**Comment by dschaper** [comment]
Thanks, appreciate it!

**Comment by technicalpyro** [comment]
may have just figured it out when going through the bash script it is very easy to assume that hitting return when openDNS is selected forces it to use that option rather than needing to make sure the asterisk is there ... i just did that to myself

**Comment by dschaper** [comment]
Okay, that should probably be a whiptail menu instead of a radio button dialog. We'll take a look at that.

**Comment by technicalpyro** [comment]
rule #1 users lie or just dont know lol

**Comment by dschaper** [comment]
No problem, something that should have been swapped out a little bit ago. We should have that fix in next release.

**Comment by technicalpyro** [comment]
thanks for the help ... and if y'all ever want an extra guinea pig im willing

**Comment by dschaper** [comment]
Thanks! We may be testing some new features in a little while, if you have good `git` skills then it shouldn't be too hard to pull down a branch or repo to help check some code. Exciting stuff bubbling up!

**Comment by DL6ER** [comment]
We will close this issue once the selection method has been changed

**Comment by technicalpyro** [comment]
want to put it out there you guys all rock ... just sayin
