### ISSUE TITLE
Some settings not updating via web interface on Synology

### ISSUE THREAD

**Issue by jaracimrman** [pi-hole/pi-hole#1157]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Adding domains to the whitelist/blacklist and/or changing Upstream DNS servers doesnt update the config file.

**[BUG | ISSUE] Actual Behaviour:**
Adding domains into whitelist shows them as they would be there, but they are still getting blocked.
Adding custom servers as upstream doesnt do anything even though it shows it saved correctly, on dashboard it still says google servers.

running this command: sudo  /etc/init.d/dnsmasq restart
SOLVES THE ISSUE (button to restart dns server in web interface doesnt do anything!)

**[BUG | ISSUE] Steps to reproduce:**

-Add domain to whitelist, says it saved succesfully
-Restart DNS server by web interface, flush dns on client PC
-Domain still being blocked
-

**(Optional) Debug token generated by `pihole -d`:**

`22qh0jkfeg`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Please generate a debug log using `pihole -d` and provide the token since this will allow us to skip a series of questions like

- which operating system?
- etc


Do you use SELinux?

**Comment by jaracimrman** [comment]
Hi, the token is 22qh0jkfeg and im running pi hole on Synology NAS.
I can do the first command, but 2nd one returns following: "Running in chroot, ignoring request."

**Comment by DL6ER** [comment]
Thanks, we will have a look at this soon.

Meanwhile: Have you had a look at [this](https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289) thread? There have been a series of issues and solutions. Maybe the solution is already there for you.

**Comment by jaracimrman** [comment]
I did, this is how i installed it :) i read through it and some people seem to be having same problem with whitelist blacklist and it sovled them for the mto restart dnsmasq, however my whitelisted sitess are getting still blocked (reddit and google ads)

**Comment by DL6ER** [comment]
Hmm, we will take a look at that, I cannot remember if anyone of the developers has such a device to test on (I don't have one). Can you verify if the pages you want to be whitelisted are contained in `/etc/pihole/whitelist.txt` ? Secondly, are you sure that DNS caching is no issue on your devices (maybe try to flush their DNS caches or even restart them after whitelisting, depending on the operating system)?

**Comment by jaracimrman** [comment]
Yes i can confirm they are in that file. I flushed dns in windows and in chrome aswell, cache too.
Btw, i tried running tail log while entering reddit and the domains are being forwarded correctly to the outside world instead of pihole.
I can live with this though, main issue is that web interface doesnt truly update the settings when you change them.

**Comment by DL6ER** [comment]
Please do a
```
grep 'events.redditmedia.com' /etc/pihole/gravity.list 
```
(assuming you want to whitelist `events.redditmedia.com`) and see if the reddit domain you want to have whitelisted is *not* there (like in an empty reply is fine).

If they are there run a gravity update before restarting `dnsmasq` once again:

```
pihole -g
service dnsmasq restart
```

**Comment by jaracimrman** [comment]
The grep command returned literally nothing, just jumped to empty new line

**Comment by DL6ER** [comment]
Then it is properly whitelisted.

Try
```
dig events.redditmedia.com @127.0.0.1
```

**Comment by jaracimrman** [comment]
All returned proper ip addresses if that's what we are after

**Comment by DL6ER** [comment]
Then it is definitely not blocked

**Comment by dschaper** [comment]
Since none of the developers have Synology devices to test or develop on, the best place for support requests is via the community supported Discourse thread. It appears that the chroot has both `systemctl` which it ignores in the rooted environment, and the older style `service` command support. We check for `systemctl` and if that command is found, then that is the process that we use to control the daemons. If this is not functional on Synology, then you would have to manually run the `service` command to restart any daemons after updating a whitelist or blacklist. 

The user that submitted the instructions on running with Synology may be able to provide more instruction than we can, as we aren't able to directly support that platform at this time.

**Comment by jaracimrman** [comment]
Oki doki :) Thansk for the help anyways!

**Comment by bakman2** [comment]
I wrote those instructions, restart dns from the webgui works for me. Not sure why it doesn't on your end.
