### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by kevincork** [pi-hole/pi-hole#1159]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**
When checking the log I have this error "DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

I ssh "sudo curl -sSL https://install.pi-hole.net | bash" and update, same issue, so I did the same and reconfigure but same issue  

**[BUG | ISSUE] Expected Behaviour:**
Have the list of query 

**[BUG | ISSUE] Actual Behaviour:**
DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**[BUG | ISSUE] Steps to reproduce:**

- Go on the web interface
- Login with password
- Click on Query Log

**(Optional) Debug token generated by `pihole -d`:**

**EDIT** Deleted log content

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-wont-the-web-interface-wont-load-datatables-warning-table-id-all-queries-ajax-error/1412

**Comment by kevincork** [comment]
Thank you and sorry, resolved.
