### ISSUE TITLE
Apache2 over lighttpd

### ISSUE THREAD

**Issue by Scott1974-1** [pi-hole/pi-hole#1161]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Running the Admin console and have it working fully

**[BUG | ISSUE] Actual Behaviour:**

When I removed lighttpd and am now using apache2 the dashboard loads but non of the charts are working. no status at all since I removed lighttpd. can I use pi-hole with just apache2 installed and not lighttpd ?

**Comment by Mcat12** [comment]
You're on your own if you want to use it with a different web server, we currently only support lighttpd. It should work if you enable PHP with Apache.

**Comment by Scott1974-1** [comment]
php is enabled and working. most of it works fine... it seems to still be blocking ad's and it does show how many blocked add's there are and how many DNS queries there are and they all seem to work but the charts below and top domains/ad's blocked don't work now..

**Comment by Scott1974-1** [comment]
seems to be working now... thanks
