### ISSUE TITLE
Dashboard blocked?

### ISSUE THREAD

**Issue by LilSnoop40** [pi-hole/pi-hole#1162]
I just created a pi-hole using a raspberry pi I had laying around. When I go to admin login page I don't see anything looking nice seems like everything is blocked on the configure page once I login. 

Thought on how to fix this?

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
When I go to the admin dash board from my laptop, iPad, iPhone I don't see the dash board but looks like items are being blocked.

**[BUG | ISSUE] Actual Behaviour:**
Dash board doesn't load correctly 

**[BUG | ISSUE] Steps to reproduce:**

- go to ip/admin
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`yt9yyb2qm5`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
We can start with:

> Debug token generated by pihole -d

And start the process there.

**Comment by Mcat12** [comment]
And while you're getting the token, please fill out the rest of the template like it says.
> **Failure to fill the template will close your issue**

**Comment by LilSnoop40** [comment]
How do I get the log to you, I ran the cm above through putty on my pic.

Thanks

**Comment by dschaper** [comment]
At the end of the process there is a prompt to upload the log. When you do that you will get back a token string that identifies which log is yours. We need that in order to open the log and see what you have provided.

**Comment by Mcat12** [comment]
Please fill out the template by editing your first post in this thread.

**Comment by LilSnoop40** [comment]
[url=https://postimg.org/image/h9gviqgp3/][img]https://s23.postimg.org/h9gviqgp3/image.png[/img][/url]

**Comment by Mcat12** [comment]
Please use a better image provider like imgur. If you don't completely fill out the template, we'll have to close this issue.

**Comment by Mcat12** [comment]
Press F12 (or whatever key opens your browser's dev tools) and navigate to the Console tab. Take a screenshot of any errors that appear there.

**Comment by LilSnoop40** [comment]
Mcat12, just wanted to let you know i reinstalled my pi-hole from scratch and now i am able to view the dashbord of the ip/admin with no issues.

on a side note if you could answer this please, i am currently using the 1st rpi for this.  if i were to get the rpi 3 would i notice a difference in performance as its just blocking sites.  please advise as i was looking to get the rpi 3 to use.

Thanks

**Comment by DL6ER** [comment]
You can use a Pi version 1 without any problems (in fact I have a Raspberry Pi B at work and with roughly 6 active clients). There is no noticeable difference in the performance compared to my Raspberry Pi B version 3). However, things are totally different when it comes to the admin page display.

**Comment by LilSnoop40** [comment]
ok, sounds like we have the same model, wasn't sure if the faster newer model mattered much on this.  should I power it down ever or just let it run, doesn't need any reboots or anything? thanks for the reply i am using it for home use. we have about 25 items that all have assigned address from 2-26.  this pi-hole is only thing that is wired.  this thing works very nice, my daughter was asking if there was any way to block her ads in youtube and other and this has achieved it.  thanks for everyone help.

**Comment by DL6ER** [comment]
I let my two devices (at home and in the office) run non-stop. Never had a single issue in months.

**Comment by LilSnoop40** [comment]
great, thanks for your help.  have a nice day!
