### ISSUE TITLE
Newest version of Pi-Hole not respecting /etc/hosts entries

### ISSUE THREAD

**Issue by escapologyBB** [pi-hole/pi-hole#1165]
Hello,

Before the most recent update I had about 10 entries in the `/etc/hosts ` file on the same Raspberry Pi running Pi-Hole, each one of these entries pointed to the same  physical server on my local network and that they each had a different hostname.  This is because I was running multiple websites on one Raspberry Pi, and adding them to the hosts file has worked brilliantly ever since I've been using Pi-Hole.

However, I've just this minute updated and now Pi-Hole seems to be completely ignoring whatever's inside the `/etc/hosts` file for some reason.  Is this a bug or a feature?  Have I missed something obvious and the ability to add domains has been moved to somewhere in the UI, because  I'm fairly willing to believe that I've missed something very obvious!

Any help would be greatly appreciated.  :-)

**Comment by Mcat12** [comment]
I don't think we've changed anything that would cause `/etc/hosts` to be ignored. Run `pihole -d` for a debug log so we can check that everything's working.

**Comment by escapologyBB** [comment]
Thanks for the quick response, I think this is the token you are looking for:
```
::: Your debug token is : 0dt28uph7k
```

**Comment by Mcat12** [comment]
It looks like it is working as it should:
```
Jan 23 20:27:04 dnsmasq[703]: /etc/hosts 192.168.0.81 is r2-d2.local
```
Try running `pihole -t` and going to that domain.

**Comment by DL6ER** [comment]
@escapologyBB Please add our [issue template](https://raw.githubusercontent.com/pi-hole/pi-hole/master/.github/ISSUE_TEMPLATE.md) to your original post (read it and act accordingly!).

**Comment by escapologyBB** [comment]
@DL6ER I could do that, I really could.  But then that would just highlight my shame even further, can we just completely delete this issue because if I am totally honest it's a nonissue and just a stupid mistake on my part!

I had another look at my `/etc/hosts` file and after staring at it for a couple of hours I realised that at position line one, column one there was the Y which caused the whole file not to be read by the computer.  Yes, a leading letter Y caused me to waste nearly 72 hours of my time and some of your time chasing down the problem.

Mea culpa, mea maxima culpa.

**Comment by DL6ER** [comment]
We will keep this issue since there might be other users stumbling upon a similar typo at some time. But don't be worried, closed issues rapidly sink into oblivion.

**Comment by escapologyBB** [comment]
*hides*
