### ISSUE TITLE
Looking for index.html

### ISSUE THREAD

**Issue by ewm2000** [pi-hole/pi-hole#1167]
Where would the index.html file be located for Pi hole. Im looking so that I can customize what would happen if a blocked site/ blocked ad on a site would come up.

**Comment by technicalpyro** [comment]
not sure this is an issue perhaps a better place for this would be either the discourse forums found [here](https://discourse.pi-hole.net/) or on the subreddit devoted to this software.  Clearly you ignored the template that is meant for this area

**Comment by DL6ER** [comment]
Failure to fill issue template leads to closing of issue (as is mentioned in the issue template).

**Comment by ewm2000** [comment]
Apologies for not following the Template. I didnt realize that there was a subreddit or a discord
