### ISSUE TITLE
Entries on blacklist are not blocked or pi-holed

### ISSUE THREAD

**Issue by r0ckarong** [pi-hole/pi-hole#1171]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_0_

---
**[BUG | ISSUE] Expected Behaviour:**
Entries on the blacklist will be pi-holed and show a block page when called directly.

**[BUG | ISSUE] Actual Behaviour:**
Entries on the list are passed through to clients and are not blocked or pi-holed.

**[BUG | ISSUE] Steps to reproduce:**
Define entries in blacklist.txt
Try to access URL defined in blacklist

**(Optional) Debug token generated by `pihole -d`:**

`m03n2lbyf8`

Like I described above. I have over a hundred entries in my custom blacklist (mostly mobile popup ads and pages). I would expect them to be pi-holed and when trying to access them from a different client to see a block page. 

I can freely access these pages when calling the URLs in a browser (Chrome 55/Firefox 50, Ubuntu).
My pi-hole is the alternative DNS server for IPv4 configured in my router.

Sorry if this is a duplicate but I have looked through the list repeatedly and haven't found an identical issue.

One of the examples is "https://de.quasargaming.com/" I have entries on the blacklist like:

```
quasargaming.com
de.quasargaming.com
https://de.quasargaming.com/
```

None of these work to block that site from opening.

**Comment by dschaper** [comment]
Can you do the debug process again, and when the script prompts you to browse on a client, go to one of the sites that should be blacklisted and still comes through. This will show in the log and we can check to see if the Pi-hole is getting the queries and responding.

You do mention that the Pi-hole is an alternate DNS server, in many cases running as an alternate or secondary will leave clients still going to the Primary and getting adverts that way as well.

**Comment by r0ckarong** [comment]
My router only has the option "use the ones from your ISP or provide your own" that's what I mean by "alternative" I specified the Pi-Hole twice for both alternate servers.

I ran the debug process again and opened the site mentioned in the original comment. No log entries.

The new token is: 771gbbs6ou

**Comment by Mcat12** [comment]
Make sure that your blacklist only contains domains, not URLs like `https://de.quasargaming.com/`.

**Comment by Mcat12** [comment]
After flushing your DNS cache, run these commands on a client and share the output:
```
nslookup doubleclick.com
nslookup doubleclick.com 192.168.1.32
nslookup de.quasargaming.com
nslookup de.quasargaming.com 192.168.1.32
```

**Comment by r0ckarong** [comment]
So I ran 

`sudo /etc/init.d/dns-clean restart` and `sudo /etc/init.d/networking force-reload` on my Ubuntu box and then ran the commands. Is this the proper way to flush DNS cache? I have no experience with doing so. If I should try something else please let me know. The results of the lookups are below:

```
$ nslookup doubleclick.com
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	doubleclick.com
Address: 216.58.214.78
```

```
$ nslookup doubleclick.com 192.168.1.32
Server:		192.168.1.32
Address:	192.168.1.32#53

Name:	doubleclick.com
Address: 192.168.1.32
```

```
$ nslookup de.quasargaming.com
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
de.quasargaming.com	canonical name = quasargaming.com.
Name:	quasargaming.com
Address: 95.131.233.131
```

```
$ nslookup de.quasargaming.com 192.168.1.32
Server:		192.168.1.32
Address:	192.168.1.32#53

Name:	de.quasargaming.com
Address: 192.168.1.32
```

**Comment by r0ckarong** [comment]
And this is how I configured the DNS server to use the PIs address:

![selection_001](https://cloud.githubusercontent.com/assets/4920542/22314697/e007ec52-e362-11e6-93c3-fb24f0fe4be9.png)
![selection_002](https://cloud.githubusercontent.com/assets/4920542/22314698/e009cf90-e362-11e6-93a2-5af3637171a4.png)
![selection_003](https://cloud.githubusercontent.com/assets/4920542/22314699/e00ab504-e362-11e6-9078-106579086bb6.png)

Those are the only three places in the router interface that allow me to mess with DNS settings.

**Comment by dschaper** [comment]
It looks like your Ubuntu box isn't set to use the Pi-hole as it's DNS. The bare query shows an address of `127.0.1.1` which is a loopback to the same machine. But a directed query to the Pi-hole IP address shows that the Pi-hole is responding correctly to queries when they reach it.  

On the Ubuntu, what is the contents of `/etc/resolv.conf`? And is the Ubuntu's IP address set via DHCP?

**Comment by r0ckarong** [comment]
It says nameserver 127.0.0.1 and I've set a static Ip for the machine and use dns and gateway of the router configured to forward everything to the raspi.

**Comment by dschaper** [comment]
For some reason, the Ubuntu isn't using the Pi-hole for it's DNS. The `nameserver 127.0.0.1` would indicate that it's pointed back to itself for name resolution and not to another machine. Can you run `sudo netstat -tulpn` and that should show you if there is a daemon listening on port 53 of the Ubuntu machine that is handling the DNS instead of the Pi-hole.

**Comment by r0ckarong** [comment]
I do see a dnsmasq service on that port

`udp        0      0 127.0.1.1:53            0.0.0.0:*                           1608/dnsmasq`

I thought it was enough to configure the DNS server to the router in my Ethernet settings. I will read up on dnsmasq to find out how to work around this. I wasn't aware Ubuntu needed more specific DNS settings.

**Comment by dschaper** [comment]
You may be able to just `apt` remove the dnsmasq package from the Ubuntu and then the `resolvconf` hooks should automatically configure the `/etc/resolv.conf` file to be pointed to the nameserver you set in `/etc/network/interfaces`. Having the `dnsmasq` package installed on the Ubuntu client may cause it to automatically enter the localhost address in the configuration file.

**Comment by r0ckarong** [comment]
I've disabled the dnsmasq service in NetworkManager.conf and now my `resolv.conf` shows the two servers I set (192.168.1.1 - router / 192.168.1.32 - pi-hole) but I still do not get blocking. I can access stuff like doubleclick.net just fine.

**Comment by dschaper** [comment]
There is a DNS cache that may take some time to clear out. If it's not working in about 10 minutes, let us know. And you can also try going to the Admin webpage, and selecting "Tail log" from the tools options on the left hand menu. This will show the log in real time and should show the name resolution traffic that the Pi-hole is generating.

**Comment by r0ckarong** [comment]
Ok I've manually cleared the cache by restarting network manager. Now blocking works as it should. Apparently (from what I could find in the short time) is that Ubuntu comes with dnsmasq enabled by default to speed up browsing. Maybe this should be part of the FAQ or something. I have been struggling with this for weeks now =) 

Thanks so much for the patience and all the help.

**Comment by dschaper** [comment]
You're welcome and we'll take a look at the FAQ's/Wiki and add some notes where they are needed. Thanks again for using the Pi-hole!
