### ISSUE TITLE
new install block page missing css

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1179]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
**[BUG | ISSUE] Expected Behaviour:**
upon install the block page should show correctly when accessing a blocked domain or by navigating to pi.hole

**[BUG | ISSUE] Actual Behaviour:**
the page does not show correctly with the biggest issue being an unclickable whitelist this page (link is missing)

**[BUG | ISSUE] Steps to reproduce:**
-install pihole as a new install 
-navigate to pi.hole or any blocked domain
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<y5ki5s9zyf>` this debug is prior to my fixing with solution below 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

ADDENDUM
to solve this issue i run pihole -r and repair the install it finds index.css to be missing and repairs it the following is the log from pihole -r 
```
pi@raspberrypi:~ $ pihole -r
:::
::: You are root.
::: Repair option selected.
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for apt-utils... installed!
:::    Checking for debconf... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for git... installed!
:::    Checking for whiptail... installed!
::: --reconfigure passed to install script. Not downloading/updating local repos
:::    Checking for bc... installed!
:::    Checking for cron... installed!
:::    Checking for curl... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for dnsutils... installed!
:::    Checking for iproute2... installed!
:::    Checking for iputils-ping... installed!
:::    Checking for lighttpd... installed!
:::    Checking for lsof... installed!
:::    Checking for netcat... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
:::    Checking for sudo... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::
::: Installing scripts from /etc/.pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page...
:::     Existing index.php detected, not overwriting
:::     Existing index.js detected, not overwriting
:::     index.css missing, replacing...  done!
:::
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: Neutrino emissions detected...
```

**Comment by dschaper** [comment]
Is this with a fresh install or an upgrade? I'll see if I can set up some test to check the conditions.

**Comment by technicalpyro** [comment]
it is a fresh install been playing with some different things lately and have done a few fresh install in the last week this has happened every time for me 

side note : nothing i have been tinkering with has anything to do with pihole or its functions however ive broked my SD card a time or two so needed to go fresh

**Comment by dschaper** [comment]
Thanks for the report we'll take a look and see what's going on.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L833 

Think this may be the culprit.

**Comment by technicalpyro** [comment]
I think you are correct.  However from what i just looked up the pihole -r command just calls the auto install script to run without the whiptail unless reconfigure is selected.  may have to eliminate the wildcard and add a couple lines one for each not sure just thinking out loud now

**Comment by dschaper** [comment]
Yeah, I've never been a fan of `cp` for this type of thing, I'm more of the `install` type. Think that may be the way to go, but the tests so far do confirm that `blockingpage.css` is left out. Not a hard fix, the test code is way longer to write :)

Should have this in the next release in a day or so when we can get all the developers together to push it out.

**Comment by technicalpyro** [comment]
no worries appreciate everything you guys do.  happy this was a somewhat easy one
