### ISSUE TITLE
Graph "Queries over time" and "Top domains/advertisers" do not load anymore

### ISSUE THREAD

**Issue by dYna77** [pi-hole/pi-hole#1181]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Graph would load i guess?

**[BUG | ISSUE] Actual Behaviour:**
I just updated adlists.list with all the lists from https://wally3k.github.io/ and now the graphs mentioned in the topic won't load anymore.
I am running pihole on a debian vm system (host is freenas).
The problem is not browser related, because it can be reproduced on two differnet brwosers and on my mobile device.

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

egkvsig94d

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dYna77** [comment]
This is may adlist.list: http://paste.debian.net/911053/

**Comment by dYna77** [comment]
Ok, so it seems that this is the same problem as https://github.com/pi-hole/pi-hole/issues/375
I am on debian stable, so there is no php7.
Is there any other workaround since the first post of this problem, or do i have to update to unstable?

**Comment by dYna77** [comment]
Sorry for spamming, but i used deb http://packages.dotdeb.org jessie all, purged php5, upgraded to php7.0, "reinstalled" the modules to lighthttpd and now it works!

**Comment by dschaper** [comment]
From the Wally3k site as well:

> A word of warning (i.e: Please DO NOT just install all these lists at once):
Installing all of these lists will result in the Query Log tool of Pi-hole to return an ajax datatables error, when it loads

**Comment by dYna77** [comment]
Not with php 7.0

**Comment by dschaper** [comment]
Then it works okay?

**Comment by dYna77** [comment]
At least on my end.
And the emphasis is on "at once" i think.
Because the pi can not handle the load, but on a normal machine this should be nice.

**Comment by dschaper** [comment]
Okay, if there are any other problems let us know.
