### ISSUE TITLE
admin page getting blocked

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1186]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

update pi hole

Admin page worked fine before the update.

**[BUG | ISSUE] Actual Behaviour:**

Access to the following site has been blocked:
pi.hole/admin/queries.php

**[BUG | ISSUE] Steps to reproduce:**
update pi hole
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`4k81u3de3q`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Your debug log is (slightly) inconsistent. Please post the output of:
```
cd /var/www/html/admin
git status
git rev-parse --abbrev-ref HEAD
git describe --long --dirty --tags
```

**Comment by Tntdruid** [comment]
pi@raspberrypi:~ $ cd /var/www/html/admin
pi@raspberrypi:/var/www/html/admin $ git status
fatal: Not a git repository (or any of the parent directories): .git
pi@raspberrypi:/var/www/html/admin $ git rev-parse --abbrev-ref HEAD
fatal: Not a git repository (or any of the parent directories): .git
pi@raspberrypi:/var/www/html/admin $ git describe --long --dirty --tags
fatal: Not a git repository (or any of the parent directories): .git

**Comment by DL6ER** [comment]
It seems like you somehow lost the admin repo...

Please do the following to fix this:
```
cd /var/www/html
mv admin/ admin_broken/
git clone --depth 1 https://github.com/pi-hole/AdminLTE.git /var/www/html/admin
```

**Comment by Tntdruid** [comment]
Works now, Thanks for the help :)
