### ISSUE TITLE
Pi Hole is not blocking adds. 

### ISSUE THREAD

**Issue by jamer508** [pi-hole/pi-hole#1187]
Pi hole is supposed to block ads

actual: is not blocking adds: 

TS: Reinstalled pi hole 
when pinging doubleclick.net on pihole through ssh connection it will direct to DNS on pihole. When pinging on computer pointed at pi hole DNS it ignore pi hole. I am worried  that my router is overriding the pihole.

**Comment by dschaper** [comment]
Hi, can you please edit your post and fill out the issue template. Failure to do so may close this issue.
