### ISSUE TITLE
Pi hole not blocking ads

### ISSUE THREAD

**Issue by jamer508** [pi-hole/pi-hole#1189]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[QUESTION]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Pi hole should block ads

**[BUG | ISSUE] Actual Behaviour:**

Pi hole only blocking requests placed locally

**[BUG | ISSUE] Steps to reproduce:**

When i log into the ssh and ping a site like doubleclick.net for example it will divert it to the pihole dns and block it. 
But if pinged on any other devices like my computer or phone it will not. All devices manually directed to dns. Reinstalled conf. Updated lists. It just seems that my phone or computer is ignoring the pihole entirely. 

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jamer508** [comment]
I saw some answered posts about pihole blocking issues. Just didnt see this exact behavior. If i missed an article that addresses this issue please let me know.

**Comment by dschaper** [comment]
Can you run a `pihole -d` and then post the token given to you so we can take a look at the debug logs?

**Comment by DL6ER** [comment]
Okay, we will find out what is going wrong together. Please generate a debug log using `pihole -d` and provide the token after uploading. This will include a rather comprehensive test of the resolver function.

**Comment by jamer508** [comment]
eawwuuhkmr

**Comment by DL6ER** [comment]
Did you do any browsing when the debugger asked you to do?
Not a single query has been recorded, i.e. no device used the Pi-hole in that time frame.

**Comment by jamer508** [comment]
Yes. I went to facebook and to doubleclick.net. Its like my computer is ignoring the dns I have it pointed to.

**Comment by DL6ER** [comment]
Can you make screenshots of the places where you did apply the settings?

**Comment by jamer508** [comment]
Yes. I will get that asap this evening. After 5pm cst.

**Comment by jamer508** [comment]
![image](https://cloud.githubusercontent.com/assets/12905892/22450709/1783d2e4-e72e-11e6-92d6-3daef006b9b7.png)

**Comment by jamer508** [comment]
After reviewing my network, It appears that Cox Communications hard sets the DNS on the modem/router combo. They only use modem/router combos and they do not support customer DNS portals on the network because they want to prevent outages do to middle man DNS and prevent DNS hijacking. 

That being said. If I really wanted to, could I use the raspberry pi as an APN and a DNS before it reaches the UBEE modem/router combo? And in your experience, would that make a difference?

**Comment by DL6ER** [comment]
Hmm, have you tried to use `Tools -> Tail pihole.log` on the web UI to test if the DNS queries do ever get to the Pi? If you hard-code the DNS address (as done in the screenshot you posted) the computer should nevertheless ask the Pi-hole.

Do you have IPv6 enabled? It could be that your Win prefers to use a IPv6 DNS server which you have not manually pointed to the Pi-hole.

**Comment by clayton** [comment]
I'm also a Cox customer and unsure that blocking is occurring. I've got the DNS on my MacBook pointed to the Pi (after having it previously setup as the DNS on the router.)

After running `pinhole -d` and browsing some articles on cnn.com and buzzfeed.com, my token is `idtysjnsy8`.

**Comment by clayton** [comment]
Ran some more testing using `http://forums.vwvortex.com/forumdisplay.php?1-The-Car-Lounge`. Each page has a large banner add at the top.

When browsing in Safari [Version 10.0.3 (12602.4.8)] I see the banner ads, when browsing in Chrome [Version 56.0.2924.87 (64-bit)] I **do not** see the ads.

My debug log token for this test was `ely8zi20i4`.

**Comment by Mcat12** [comment]
Do you have ipv6? It looks like all your queries are going through the router, which might be utilizing a DNS cache. Try clearing the client's and browser's DNS cache. You can also try pinging the ad domain or using `nslookup` on it on the client.

**Comment by asoliman74** [comment]
Hello Everyone,
I am having a similar issue. I have my pi hole running on a raspberry pi on my home network. I also have a vpn server running on a synology NAS. My pi hole is not working while I am on the wifi/at my house, however; my pi hole is working great and blocking all the ads if I am connected to my network through my vpn. Not sure why this is happening. your help would be greatly appreciated!

**Comment by dschaper** [comment]
Sure, can you please open a new issue ticket and fill out the template with the information about your situation and we can take a look at troubleshooting for you.

**Comment by gavinwade12** [comment]
I am currently experiencing the OP's issue on my home network. It seems to be blocking a few ads at most, but I am still seeings ads from googleads.g.doubleclick.net, for example, even though I have that domain blacklisted. I've also added the non-crossed lists from https://wally3k.github.io/. My debug token is: 4gvg9dk7f2.

**Comment by WaLLy3K** [comment]
@gavinwade12: If you're using Chrome, I'd suggest [looking at this FAQ entry](https://discourse.pi-hole.net/t/why-do-i-see-ads-in-chome-but-not-other-browsers/3284) to see if it applies to you. If it doesn't, please create a new issue ticket so as to not tag on this closed ticket. Thanks! :smile:

**Comment by chroniclesoffire** [comment]
Cox may control how they serve DNS by forcing DHCP, but they can't control how you set the DHCP up.  Look at the settings for the local network on the Cox Modem.  you can't disable it, but you can limit it to and address pool of one address that your Pi-hole pulls.   While the Pi-hole is connected, log in to reserve the address given to the Pi-Hole, which will seal the Pi-Hole to that IP. once it has that address reserved the Cox modem will refuse all other DHCP requests.  THEN, setup DHCP on the Pi-Hole: https://blog.monotok.org/setup-raspberry-pi-dhcp-server/  The variance to this setup is that your Pi does need to use DHCP for it's own eth port, and that it serves itself as the DNS server.
