### ISSUE TITLE
Chronometer printing nothing / Ubuntu 16.04.1 64Bit

### ISSUE THREAD

**Issue by woftor** [pi-hole/pi-hole#1196]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[OTHER]:**

**[ISSUE] Expected Behaviour:**
The chronomter printing out  the right info on the console - `pihole -c`
This is on Ubuntu 16.04.1 LTS GNU/Linux 4.4.0-59-generic x86_64

**[BUG | ISSUE] Actual Behaviour:**
`pihole -c` is printing no info at all. All is 'null':

> The wonderful logo (but ugly when copy-pasted)
> 
>         192.168.2.1
> 
> average: 0.35, 0.12, 0.04
> 0 days, 9 hours, 25 minutes.
> -------------------------------
> Blocking:      0
> Queries:       0
> Pi-holed:      0 (0.00%)

The webinterface is working as expected with 'normal info'.

**[BUG | ISSUE] Steps to reproduce:**

`pihole -c`

**Comment by DL6ER** [comment]
Thank you for reporting. This is already known and fixed by #1194

**Comment by woftor** [comment]
Thought I searched... guess not hard enough. Thanks.

**Comment by woftor** [comment]
v2.12.1 did not fix it for me (Ubuntu 16.04.1 X64).

**Comment by DL6ER** [comment]
Please run 
```
curl -s -X GET http://pi.hole/admin/api.php?summaryRaw
```
so we can see if this works as it should. Run it on the Pi-hole itself.

**Comment by woftor** [comment]
> Please run
> 
> curl -s -X GET http://pi.hole/admin/api.php?summaryRaw
> 
> so we can see if this works as it should. Run it on the Pi-hole itself.

Ah, I see... Running this command gives me an error, because I run lighttpd on another port.
`File not found.`

This is also why the error page is not working, because it redirects to port 80, where my main webserver (Hiawatha) is running on. Had to make a custom errorpage based on the IP.

When I do a curl -s -X GET http://pi.hole:8081/admin/api.php?summaryRaw (I run lighttpd on port 8081 obviously) I get no response / no error.

So... it seems my setup is the root of the problem. I could be an idea to make settings for people running on another port possible, but maybe that is not the scope of the software... Or is there something I can change manually to make it work? Thanks btw.

**Comment by DL6ER** [comment]
Hmm, with the custom port it should work for you. I see
```
me@work2 ~ # curl -s -X GET http://pi.hole/admin/api.php?summaryRaw
{"domains_being_blocked":107996,"dns_queries_today":7521,"ads_blocked_today":155,"ads_percentage_today":2.0608961574259}
```

You can change that address in `/opt/pihole/chronometer.sh` (line 33). Note that it will obviously be overwritten by any future update. We are discussing the ability to set up a custom port, but it does not seem like a good idea when viewed from varying points of view. You have seen that you had to tweak your local installation to prevent your webpage from popping up in page in places where ads should go. Not all users can do this, so for most of them it is advisable to actually let `lighttpd` serve port 80 and change the port of the other webservice they are running on the same device.

**Comment by woftor** [comment]
Oke. found out that lighttpd was NOT running due to updating and the overwriting of the config file and then it would not start because Hiawatha was already running ion port 80. How stupid. 

Now... When I run that command `curl -s -X GET http://pi.hole:8081/admin/api.php?summaryRaw` again I get actually output like you mentioned. `pihole -c` is doing noting still (all zeros), and also after updating chronometer.sh with the right port...

**Comment by DL6ER** [comment]
Hmm, let's summon @PromoFaux

**Comment by woftor** [comment]
Actutally I found it. the line is also on line 55 in `chronometer.sh`. If you change the port there `pihole -c` works. Don't understand the statement on line 33.

**Comment by DL6ER** [comment]
Ah, you are right, I mixed that up. Line 33 ist only for `pihole -c -j`.

**Comment by woftor** [comment]
Resumé: It actually works on Ubuntu 16.04.1 64 bit, as long as you don't change the port lighttpd is running on. Workaround is to change chronometer.sh. Thanks for your help/support.
