### ISSUE TITLE
Safari iOS Not Showing All Statistics

### ISSUE THREAD

**Issue by Veldkornet** [pi-hole/pi-hole#1197]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
In Safari iOS, the fields _"DNS Queries Blocked Today_" and "_% of Today's Queries Were Blocked_" are populated

**[BUG | ISSUE] Actual Behaviour:**
In Safari iOS, the fields _"DNS Queries Blocked Today_" and "_% of Today's Queries Were Blocked_" are NOT populated.
However, in Chrome on iOS, these fields are shown.

**[BUG | ISSUE] Steps to reproduce:**

- Open the interface on iOS Safari
- The fields are blank
- Tested on iPhone 6s Plus, iOS [10.2.1]

**(Optional) Debug token generated by `pihole -d`:**

`bambmhurev`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Thank you for your report. We are currently checking behind the scenes if one of the developers is able to get a iPhone 6s+ for testing.

**Comment by DL6ER** [comment]
We have not been able to reproduce this with a iPhone 6, still trying to allocate a 6+. Just to clarify: By black you mean:

- empty field (nothing at all)
- `0` (although some non-zero number should be there)
- `---`
- something else

**Comment by Veldkornet** [comment]
The fields are there, there's just no data. See attached.

**iOS Safari:**
![safari](https://cloud.githubusercontent.com/assets/10297361/22425014/6a31f500-e6f9-11e6-9325-e453b6dc2f76.jpg)

**iOS Chrome:**
![chrome](https://cloud.githubusercontent.com/assets/10297361/22425027/7546dc58-e6f9-11e6-8c60-bbee4e326a49.jpg)

**Comment by jacobsalmela** [comment]
I have a 7+ and haven't been able to reproduce this.  Some other users on Discourse had issues with the interface as well, but I also could not replicate them.

**Comment by Veldkornet** [comment]
Okay, I've figured it out. 

Actually, it's the iOS Content Blockers that are causing the issue. If you reload the page with content blockers disabled, then it works fine. I'm using "Purify" specifically.

Not sure why specifically those two fields though and not the others?

**Comment by jacobsalmela** [comment]
Ahh interesting.  I use only Pi-hole on my devices, so that's interesting.  Most of the content blockers I have seen for iOS don't give you that much control of what's blocked and what's not--they obscure that information, so who knows what they do. 

I'll check if the other users on Discourse are also using content blockers.
