### ISSUE TITLE
[Mobile version]Web interface: Less space for entering blacklist.

### ISSUE THREAD

**Issue by doge27** [pi-hole/pi-hole#1199]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 2

**[BUG | ISSUE] Expected Behaviour:**
Space for entering blacklist/whitelist should be below or above the wildcard button.

**[BUG | ISSUE] Actual Behaviour:**
Space for entering blacklist/whitelist is on the same lane which causes inconvenience while entering the domain.

![](https://discourse.pi-hole.net/uploads/default/original/1X/75ece52f9b2aeded5ac2cfaf78dee4211e7d0259.jpg)

**Comment by Mcat12** [comment]
The buttons will jump down on small screen sizes:
![image](https://cloud.githubusercontent.com/assets/4417660/22443286/621fd5b8-e70c-11e6-91a5-3ffbe0cf6d69.png)

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #384](https://github.com/pi-hole/AdminLTE/issues/384) via [**ZenHub**](https://www.zenhub.com/)
