### ISSUE TITLE
Invalid numbers in chronometer.sh

### ISSUE THREAD

**Issue by adneforslund** [pi-hole/pi-hole#1200]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
Using 'pihole -c' should give a working chronometer.

**[BUG | ISSUE] Actual Behaviour:**
The script fails on lines 57-60: 'invalid number' on all variables that are to be printed. 

**[BUG | ISSUE] Steps to reproduce:**

-  run chronometer.sh
-
-
-

`

![untitled](https://cloud.githubusercontent.com/assets/25346938/22429291/6804a0c8-e70a-11e6-9f32-df2cf55d5b00.png)

**Comment by DL6ER** [comment]
Thanks for your report, see also https://github.com/pi-hole/pi-hole/issues/1196

This will be fixed after the next update.
