### ISSUE TITLE
/opt/pihole empty after update

### ISSUE THREAD

**Issue by thomaspriv** [pi-hole/pi-hole#1202]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[BUG | ISSUE] Expected Behaviour:**
Able to run update/flush/debug/...

**[BUG | ISSUE] Actual Behaviour:**
all scripts are not able to run after the update of 29/01/2007

USER@raspberrypi:/opt/pihole $ pihole -d
/usr/local/bin/pihole: line 42: /opt/pihole/piholeDebug.sh: No such file or directory
USER@raspberrypi:/opt/pihole $ pihole -f
/usr/local/bin/pihole: line 47: /opt/pihole/piholeLogFlush.sh: No such file or directory
USER@raspberrypi:/opt/pihole $ pihole -up
/usr/local/bin/pihole: line 52: /opt/pihole/update.sh: No such file or directory

Nightly email just outputs the same.
 /usr/local/bin//pihole: line 47: /opt/pihole/piholeLogFlush.sh: No such file or directory

**[BUG | ISSUE] Steps to reproduce:**

-reproducible by running any command with pihole (-f, -up, etc)
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by thomaspriv** [comment]
email which was send regarding the update
::: Checking for updates...
::: Pi-hole Core:   update available
::: Web Interface:  update available
:::
::: Updating Everything
:::
::: Checking for existing repository...
:::     Updating repository in /etc/.pihole... done!
:::
::: You are root.
::: --unattended passed to install script, no whiptail dialogs will be displayed
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for apt-utils... installed!
:::    Checking for debconf... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for git... installed!
:::    Checking for whiptail... installed!
:::
::: Checking for existing repository...
:::    Updating repo in /etc/.pihole... done!
:::
::: Checking for existing repository...
:::    Updating repo in /var/www/html/admin... done!
:::    Checking for bc... installed!
:::    Checking for cron... installed!
:::    Checking for curl... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for dnsutils... installed!
:::    Checking for iproute2... installed!
:::    Checking for iputils-ping... installed!
:::    Checking for lighttpd... installed!
:::    Checking for lsof... installed!
:::    Checking for netcat... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
:::    Checking for sudo... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::
::: Installing scripts from /etc/.pihole...install: invalid user ‘’
::: Restarting services...
:::
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
::: done.
:::
::: Update complete!
:::
::: The install log is located at: /etc/pihole/install.log


install log only contains the following:
cat install.log
:::
::: Installing scripts from /etc/.pihole...

**Comment by dschaper** [comment]
Can you run:

```
cd /etc/.pihole
git status 
```

**Comment by thomaspriv** [comment]
/etc/.pihole $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by dschaper** [comment]
Okay, and does `pihole -r` with a Repair fix any of the issues?

**Comment by thomaspriv** [comment]
wow, that was rather 'easy'...

dschaper much appreciated for the help :)

**Comment by dschaper** [comment]
Glad it worked! Thanks again for using the Pi-hole :)
