### ISSUE TITLE
No more internet access on pi after setting pi-hole as DNS.

### ISSUE THREAD

**Issue by TSSchoof** [pi-hole/pi-hole#1204]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Raspberry Pi should have internet access.

**[BUG | ISSUE] Actual Behaviour:**

Raspberry Pi has no internet access.

**[BUG | ISSUE] Steps to reproduce:**

- Install pi-hole on Raspberry Pi (192.168.1.3)
- Set Raspberry Pi as DNS on router (192.168.1.1)
- No more internet
-

**(Optional) Debug token generated by `pihole -d`:**

`xkqcw9jbt3`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

I did see another thread with a similar issue as mine: https://github.com/pi-hole/pi-hole/issues/1189
I am also using a D-LINK 850L, but it's only set as a switch and for wifi. My actual router is a BBOX 2.

**Comment by dschaper** [comment]
It looks like the Pi-hole is unable to ping the router. Can you try to `ping 192.168.1.1` from the Pi-hole itself? And have you rebooted the Pi-hole since you assigned the static IP address to it?

**Comment by TSSchoof** [comment]
When the DNS relay is active I can not ping it. When the DNS relay is not active I can ping it.
The Pi has been rebooted multiple times.

![bbox dns](https://cloud.githubusercontent.com/assets/2319986/22441373/6bf7a676-e737-11e6-900b-c123dc4caea3.PNG)

**Comment by dschaper** [comment]
It may be that `DNS relay` is a form of DNS rebind protection. Some routers will sense a local DNS server on the network and will disable communication to it, as it thinks you have a rogue DNS server that should not exist. When you have DNS relay off are you able to use the Pi-hole as a DNS server?

**Comment by TSSchoof** [comment]
How exactly do I test if it works? Ipconfig still tells me my DNS server is
192.168.1.1. Is there a sure way to tell?

**Comment by Mcat12** [comment]
If you can ping `pi.hole` then you should be using Pi-hole (make sure to clear your DNS cache as well).

**Comment by TSSchoof** [comment]
Yeah, that doesn't work unfortunately.

**Comment by jamer508** [comment]
This sound very similar to what I have been experiencing. I just dont know how to check if my router has DNS relay protection.

**Comment by r0ckarong** [comment]
I have the same problem but when I set my Ethernet connection to use the Pi directly as DNS server it works (Ubuntu).

**Comment by DL6ER** [comment]
@jamer508 wrote:
>I just dont know how to check if my router has DNS relay protection.
Most often the only way to be sure if the properly check the manual + so some additional web searching on this topic including your specific router version.

@r0ckarong wrote:
> I have the same problem but when I also set my Ethernet connection to use the Pi directly as DNS server it works (Ubuntu).
That seems to be a different issue (your router does not let you specify internal IP addresses for the DNS servers or simply discards them). That is what the Pi-hole DHCP server has been invented for.

**Comment by r0ckarong** [comment]
@DL6ER 
> That seems to be a different issue (your router does not let you specify internal IP addresses for the DNS servers or simply discards them).

I checked and now whitelisted the IPs in the rebinding protection, now it works.

**Comment by r0ckarong** [comment]
@DL6ER I checked again and it seem to have returned to the broken state. I tried letting the pi handle the DHCP stuff but to no avail.

**Comment by DL6ER** [comment]
Try
```
dig google.com
```

**Comment by r0ckarong** [comment]
@DL6ER 

With DNS set manually to Pi-Hole IP:
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45914
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.de.			IN	A

;; ANSWER SECTION:
google.de.		300	IN	A	172.217.22.3

;; Query time: 26 msec
;; SERVER: 192.168.1.32#53(192.168.1.32)
;; WHEN: Thu Feb 02 18:01:09 CET 2017
```

Router configured to Pi-Hole as DNS Server and Ethernet DNS Set to Router:
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29770
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.de.			IN	A

;; ANSWER SECTION:
google.de.		171	IN	A	216.58.214.67

;; Query time: 52 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Feb 02 18:01:27 CET 2017
;; MSG SIZE  rcvd: 54
```

**Comment by TSSchoof** [comment]
As nothing else helped, I managed to solve my issue by setting the pi-hole as my DHCP server. 

It seems the BBOX 2 and my DIR-850L do not want local DNS servers.
I always put 8.8.8.8 as a backup in the settings and it always used that.

**Comment by kilgarenone** [comment]
@TSSchoof 

How did you accomplish the 'pi-hole as my DHCP server'?

I have ticked the `DHCP server enabled` box in pi.hole's `Settings -> DHCP` and disabled 'DHCP server' in my router, but still can't `git clone` or having internet access..

**Comment by Mcat12** [comment]
@kilgarenone Please open a new issue, this one has been closed for two years.
