### ISSUE TITLE
support/choice for servers with multiple NICs

### ISSUE THREAD

**Issue by HighWingy** [pi-hole/pi-hole#1206]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behavior:**

When installing/updating on a server with multple NICs, a choice should be given to the user for which NIC pi-hole will be set up on. Or at least check which NIC is in use, and choose that one.

**[BUG | ISSUE] Actual Behavior:**

Pi-hole picks one NIC, which in my case is the wrong NIC, and sets itself up on that NIC. Causing me to have to dig through the config files to change the interface it is set up on.

**[BUG | ISSUE] Steps to reproduce:**

Install on a server that has more than one NIC.
-
I'm currently using a Lenova desktop with CentOS 7 installed and two NICs. One onboard, and one PCI. One nic is on a different subnet that I use for other projects, and the other NIC is on my home network. Everytime I install/update pihole, it keeps switching/picking the other NIC that is not even connected to anything at the moment.

**(Optional) Debug token generated by `pihole -d`:**

`<j8khwoeyx3>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
The code is designed to only allow the use of interfaces in the `UP` or `UKNOWN` state. Any interface that is `DOWN` is removed from the list, and if that leaves only 1 interface option, then that is the chosen interface. In order to see what the current condition is, we'd need to take a look at the results from a few `ip` commands, checking the interface name, status and associated IP. If you are comfortable posting the information here with just the RFC 1918 addresses then please do. If not we can pipe the output from the commands straight to the tricorder.pi-hole.net trapper and none of your information would be publicly viewable.

**Comment by HighWingy** [comment]
So both the NIC's are up, but only one actually has a cable plugged into it at all times. As an FYI this was the case the last few times I've encountered this issue. 

I'm comfortable posting the results of what ever IP commands you want me to run. Post the commands and I'll post the results?

**Comment by dschaper** [comment]
If you can run the below commands with the cables connected as you would have them during an install we can see what changes are possible to try to accommodate the situation:

```
ip addr
ip route
ip link
```

**Comment by HighWingy** [comment]
as an FYI enp17s0 is the NIC I'm not using that the pi-hole installer keeps choosing even though there is no cable connected. enp0s25 is the one that has a cable connected

[root@black-box-home /]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp17s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether d8:eb:97:f2:aa:ff brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global enp17s0
       valid_lft forever preferred_lft forever
    inet6 fe80::daeb:97ff:fef2:aaff/64 scope link tentative
       valid_lft forever preferred_lft forever
3: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:24:7e:0b:c9:d6 brd ff:ff:ff:ff:ff:ff
    inet 10.2.3.10/24 brd 10.2.3.255 scope global enp0s25
       valid_lft forever preferred_lft forever
    inet6 2002:60ea:d1da::1001/128 scope global dynamic
       valid_lft 4542sec preferred_lft 4242sec
    inet6 fe80::224:7eff:fe0b:c9d6/64 scope link
       valid_lft forever preferred_lft forever
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN qlen 1000
    link/ether 52:54:00:b1:ee:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN qlen 1000
    link/ether 52:54:00:b1:ee:5f brd ff:ff:ff:ff:ff:ff

[root@black-box-home /]# ip route
default via 10.2.3.4 dev enp0s25  proto static  metric 100
10.2.3.0/24 dev enp0s25  proto kernel  scope link  src 10.2.3.10  metric 100
192.168.1.0/24 dev enp17s0  proto kernel  scope link  src 192.168.1.1  metric 100
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1

[root@black-box-home /]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp17s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
    link/ether d8:eb:97:f2:aa:ff brd ff:ff:ff:ff:ff:ff
3: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 00:24:7e:0b:c9:d6 brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT qlen 1000
    link/ether 52:54:00:b1:ee:5f brd ff:ff:ff:ff:ff:ff
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN mode DEFAULT qlen 1000
    link/ether 52:54:00:b1:ee:5f brd ff:ff:ff:ff:ff:ff

**Comment by dschaper** [comment]
Can you run the following code (This is the detection code that is currently in the master branch):

```
ip -o link | grep "state UP" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1
```

**Comment by dschaper** [comment]
And also the following as comparison:

```
ip -o link | grep -v "state DOWN\|lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1
```

**Comment by HighWingy** [comment]
[root@black-box-home /]# ip -o link | grep "state UP" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1
enp0s25
[root@black-box-home /]# ip -o link | grep -v "state DOWN\|lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1
enp0s25

**Comment by dschaper** [comment]
Which commands are you running that resets the interface back to `enp17`?  And do you edit the `setupVars.conf` file to fix the issue? Lastly, do you need to adjust the IP addresses or just the interface?

Also looking over the debug log, the `dig` command is returning results that it shouldn't. 
```
; ANSWER SECTION:
doubleclick.com.	300	IN	A	10.2.3.10
doubleclick.com.	300	IN	A	0.0.0.0
```

Can you post the output from `head -n10 /etc/pihole/gravity.list` and let's check if the `0.0.0.0` address is in that file.

**Comment by HighWingy** [comment]
I'm editing setupvars.conf and the dnsmaq and lighthttpd config files. Just editing setupvars,conf did not fix it for the other two services.

[root@black-box-home /]# head -n10 /etc/pihole/gravity.list
10.2.3.10 0000mps.webpreview.dsl.net
10.2.3.10 0001.2waky.com
10.2.3.10 000dom.revenuedirect.com
10.2.3.10 00119922.com
10.2.3.10 001wen.com
10.2.3.10 005.free-counter.co.uk
10.2.3.10 006.free-adult-counters.x-xtra.com
10.2.3.10 006.free-counter.co.uk
10.2.3.10 006.freecounters.co.uk
10.2.3.10 0075-7112-e7eb-f9b9.reporo.net

**Comment by Mcat12** [comment]
Can you run `pihole -d` for a debug token again? It would be very helpful to capture some log entries where it handles a blocked domain, so try loading a site with some ads when the debug program prompts you.

**Comment by HighWingy** [comment]
just created a new debug token of "ttx6jog3a3"

Also just realized I didn't answer Dans question of how the interface got switched.
-- basically when I run the installer it always picks the enp17 nic. And most recently when I ran an update (pihole -up) it reset the nic aswell. Hence my title suggesting there should be a user choice when multiple nic's are present.

**Comment by dschaper** [comment]
Are you running NetworkManager? I ask because the default `dnsmasq` process isn't a Pi-hole `dnsmasq`. We query:

```
Pi-hole dnsmasq specific records lookups
Cache Size:
""
Upstream Servers:
""
```

And those should respond with `10000` cache and then the IP addresses of the chosen upstreams. But back to the interfaces, I'm kind of at a loss as to why the code is selecting a `DOWN` interface when the selection code returns the correct interface if it's run manually.

**Comment by dschaper** [comment]
Possible symmetry with #1129

**Comment by HighWingy** [comment]
yes I am running network manager, but I did not have dnsmasq installed before I installed pi-hole. I was actually using bind/named before, but uninstalled it before installing pi-hole.

And yes this seems similar to #1129, however my interface was up and working at the time of install and updating, and the non-working interface was still chosen by default.

**Comment by dschaper** [comment]
Can you check the directories in the following link and see if you observe the same behaviour? NetworkManager is known to cause issues with DNS. https://ma.ttias.be/centos-7-networkmanager-keeps-overwriting-etcresolv-conf/

**Comment by dschaper** [comment]
The behavior of the installer changed a release or two ago to allow for a choice among multiple interfaces, and in development, there is a change that uses `ip` to detect the usable interfaces. This change allows for TUN/TAP and other interfaces that are in user-space and can't be readily determined via the kernel.
