### ISSUE TITLE
illegal repeated keyword at line ...

### ISSUE THREAD

**Issue by brotaxt** [pi-hole/pi-hole#1208]
Hi all,

after upgrading to the latest release, the dnsmasq crashed and can't get started anymore.
I've found the following erros in my syslog:

dnsmasq[11692]: illegal repeated keyword at line 33 of /etc/dnsmasq.d/01-pihole.conf
dnsmasq[11700]: illegal repeated keyword at line 36 of /etc/dnsmasq.d/01-pihole.conf
dnsmasq[11782]: illegal repeated keyword at line 38 of /etc/dnsmasq.d/01-pihole.conf
dnsmasq[11800]: illegal repeated keyword at line 40 of /etc/dnsmasq.d/01-pihole.conf

after removing these parmeters, the dnsmasq is working again:

```
log-facility=/var/log/pihole.log
local-ttl=300
log-async
```

is this a known bug? Or did I make a mistake somwhere ? 

Thanks in advance!

**Comment by DL6ER** [comment]
No, it means that you have a configuration file that specifies them multiple times. Check the standard config file. It should be empty!

**Comment by brotaxt** [comment]
the standard config file is emtpy:

cat /etc/dnsmasq.conf | grep -v "#"

**Comment by brotaxt** [comment]
Thank you for your fast response, I've found the mistake.... my backup file '01-pihole.conf.bak' which I created some time before, shouldnt be in the /etc/dnsmasq.d/ directory.
