### ISSUE TITLE
443 mb log file?

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1209]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Added 2x IPv6 dns servers now the log is 443 mb+ only 75k queries

**[BUG | ISSUE] Actual Behaviour:**

See some odd stuff in the log:

Feb  1 20:47:10 dnsmasq[32649]: forwarded 40.70.200.84.in-addr.arpa to ::
Feb  1 20:47:10 dnsmasq[32649]: forwarded 40.70.200.84.in-addr.arpa to ::

Feb  1 22:34:45 dnsmasq[637]: cached google.co.hu is 216.58.209.67
Feb  1 22:34:45 dnsmasq[637]: query[A] google.co.hu from ::1

PIHOLE_DNS_3=2001:1608:10:25::1c04:b12f
PIHOLE_DNS_4=2001:1608:10:25::9249:d69b

from https://dns.watch

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<ogpenja2uw>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Well, I'm not so sure if this is wrong behavior, but the log size if of course alarming.
```
Feb 1 22:34:45 dnsmasq[637]: query[A] google.co.hu from ::1
Feb 1 22:34:45 dnsmasq[637]: cached google.co.hu is 216.58.209.67
```
that seems perfectly fine to me. `::1` is your local device (like `127.0.0.1` in IPv4 language)

Something on your Pi-hole seems to fire thousands of queries to a SIP Gateway.

Let me add these DNS servers myself and report back in a few minutes whether I see something odd as well.

**Comment by Tntdruid** [comment]
Found something in 01-pihole.conf

server=0:0:0:0:0:0:0:0
server=0:0:0:0:0:0:0:0

**Comment by DL6ER** [comment]
Okay, that is bad. Please remove it.

It is the IPv6 unspecified address:
https://tools.ietf.org/html/rfc4291#section-2.5.2

**Comment by Tntdruid** [comment]
I added the IPv6 dns to the file manuel and it works now

**Comment by DL6ER** [comment]
You may still want to add it via the Settings page so it is preserved on updates and Pi-hole is aware of them.

**Comment by Tntdruid** [comment]
I did that and they got saved as 0:0:0:0:0:0:0:0 in 01-pihole.conf

**Comment by DL6ER** [comment]
Doublecheck before you click on Save. I just realize that there might be an issue with Copy-and-Paste ob Chrome.

**Comment by Tntdruid** [comment]
I did copy & past :)
