### ISSUE TITLE
Pi-hole IPv6 DNS and Android

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/pi-hole#1212]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 10

---

**[BUG | ISSUE] Expected Behaviour:**

Using Android devices with the Pi-hole DHCPv6 option enabled should work fine with Android devices.

**[BUG | ISSUE] Actual Behaviour:**

Devices behave very viscous and need up to over one minute to load simple pages.

**[BUG | ISSUE] Steps to reproduce:**

Add viscous behavior:
- Switch on DHCPv6 option in Pi-hole DHCP server
- Reconnect Android device
- Wait until the problem comes up (can take up to hours or even a whole day)

Remove voscous behavior:
- Switch off DHCPv6 server
- Reconnect Android device

Note that reproducibility is quite limited: It works sometimes just fine and then it stops working at some point. Toggling WiFi on the Android phone seems to fix the issue for a certain time.

**Further technical details:**

RA from the router
![screenshot at 2017-02-03 10-37-24](https://cloud.githubusercontent.com/assets/16748619/22586465/388c9b16-e9fd-11e6-9ac7-f58fcebf69b6.png)

RA sent from the Pi-hole DHCP server
![screenshot at 2017-02-03 10-37-13](https://cloud.githubusercontent.com/assets/16748619/22586473/3fe9dc98-e9fd-11e6-80b1-77f6157aed21.png)

As you can see, the Pi-hole's DHCP server sends around the RDNS property, telling the devices which IPv6 DNS server should be used. This works just nicely on various versions of Debian and Ubuntu.

As you can also see, the Raspberry's RA contains the statement `Router lifetime (s): 0` in contrast to the routers RA statement `Router lifetime (s): 180`. I wonder if the Android devices might simply disregard this information and try to send its traffic to the Pi-hole as its Gateway?
What speaks against this hypothesis is that there is a strongly correlated issue on [Discourse: Slow performance on Android](https://discourse.pi-hole.net/t/slow-performance-on-android/171/20). It is about Fritzboxes sending around similar RAa containing RDNS information leading to reproducable lags on Android devices. However, in this case the RA came from the valid gateway, so I'm not certain that this is the same issue.

I'd like to get some input from you guys (especially @dschaper @darkrain-nl) what can be doe to demystify this issue.

**Comment by DL6ER** [comment]
P.S.: Also at times where there is no lag on the Android devices, it is actually using the IPv6 address of the Pi-hole and can successful resolve all host names instantaneously, e.g.
```
Feb  3 10:51:34 dnsmasq[2149]: query[AAAA] www.radioerft.de from 2003:...... (Android device)
Feb  3 10:51:34 dnsmasq[2149]: forwarded www.radioerft.de to 208.67.220.220
Feb  3 10:51:34 dnsmasq[2149]: reply www.radioerft.de is <CNAME>
Feb  3 10:51:34 dnsmasq[2149]: reply radioerft.de is NODATA-IPv6
Feb  3 10:51:34 dnsmasq[2149]: query[A] www.radioerft.de from 2003:...... (Android device)
Feb  3 10:51:34 dnsmasq[2149]: cached www.radioerft.de is <CNAME>
Feb  3 10:51:34 dnsmasq[2149]: forwarded www.radioerft.de to 208.67.220.220
Feb  3 10:51:34 dnsmasq[2149]: reply radioerft.disqus.com is <CNAME>
Feb  3 10:51:34 dnsmasq[2149]: reply prod.disqus.map.fastlylb.net is 151.101.12.134
```

**Comment by Mcat12** [comment]
What versions of Android are known to be affected?

**Comment by DL6ER** [comment]
I have only one device that is aware of IPv6 (the others are older than four years).

Android 6.0
Kernel 3.18.19 (Jan 9 2017)

**Comment by darkrain-nl** [comment]
I have three Android devices in my house, two are version 6.0.1 (kernel 3.18.14) and one is version 5.0.1.
I do not recognize the problem you have...

The lifetime from the Pihole RA is set to 0 by design, otherwise the default route will be the Pihole instead of the real router... This is done by the last line in the 02-pihole-dhcp.conf file: `ra-param=*,0,0`

I'll try to keep a close eye on the configuration I have here, maybe we have the same issue but we just don't realize it yet..

**Comment by DL6ER** [comment]
Interestingly it does not seem to be a DNS issue ... when I open a page, it immediately queries the Pi-hole which responds with the correct information. Still, the page needs several dozens of seconds to finish loading of the page.

The only thing I was able to note is that in case

- there is no lag: The client's IP is *always* the IPv6 IP of the Android device
- there is a severe lag: The client's IP is *always* its IPv4 address

![screenshot_20170206-091841](https://cloud.githubusercontent.com/assets/16748619/22639340/d8dcd0ca-ec4d-11e6-84d9-06591be67dfb.png)

**Comment by darkrain-nl** [comment]
That is very possible, yesterday I think I experienced the same problem. But unfortunately I'm not sure if my problem was on IPv4...
It could be the switching between IPv6 and IPv4...

Maybe you can try http://ipv6-test.com when you notice the problem and see if the Fallback is OK...

**Comment by DL6ER** [comment]
The problem rather seems to be on the IPv4 side of things?... I opened http://ipv6-test.com/ as soon as I realized that there is a problem. The page took about 5 seconds to load and immediately knew the Ipv6 (also the fallback was working). However, the IPv4 information was only printed maybe ten seconds after the IPv6 information already showed up.

![screenshot_20170207-181313](https://cloud.githubusercontent.com/assets/16748619/22703755/87abf96a-ed65-11e6-8848-20f7e3bdbc06.png)

![screenshot_20170207-181359](https://cloud.githubusercontent.com/assets/16748619/22703802/bef865fc-ed65-11e6-82d5-83f9cda3b177.png)

**Comment by darkrain-nl** [comment]
OK, that's interesting. Are you sure your Android phone is the only device which has this problem? 
If there are more devices affected it could be routing at your ISP or something (sometimes traffic is routed via the US or the other side of the world...).
Maybe you can make an IPv4 traceroute when the problems happens, so you can identify the problem that way...

**Comment by DL6ER** [comment]
> Maybe you can make an IPv4 traceroute when the problems happens, so you can identify the problem that way...

Can you do it conveniently on the phone?

I tested at the same time at two different Linux machines (one connected via Ethernet, one via WiFi) and there was not a single issue. The very same pages loaded in the blink of an eye.

**Comment by darkrain-nl** [comment]
> Can you do it conveniently on the phone?

Yes, you can. I use an app called `IPv6 and More`, if you enter an IPv4 address it can do a trace for IPv4. You could use 8.8.8.8.

**Comment by DL6ER** [comment]
> IPv6 and More

The problem persists. I used recommended app to make a traceroute to 8.8.8.8 and noticed that it takes ages (up to one minute) until the first hop (my local router) is shown. Once this first result came up, the traceroute went fine at a normal speed, I have seen nothing unexpected.

**Comment by darkrain-nl** [comment]
And a trace to some device in your local network, like pihole or so, is ok?
Sounds like a problem with the routing table of the android device or something like that. Or maybe a wrong subnet mask?
It's a little bit shooting in the dark from here...

**Comment by nedy13** [comment]
I had the same issue, but only lagging on IPv6 devices / requests. I uses the Fritzbox as DHCP Server and configured the correct IPv6 address (IPv6 address of the Pi-Hole) as DNS Server, so all my devices uses the pi-hole as DNS. I made an update of the pihole version and configured my IPv6 network (the first time at home) on the same day.

After a while I analysed the problem:
I was a little bit confused that the IPv6 address in the pihole webgui differs from the real / correct IP address.

The IP address is read from /etc/pihole/setupVars.conf
IPV6_ADDRESS=fdab:1234:5678::1

The problem was that the pihole generates the "/etc/pihole/gravity.list" with both IP addresses from setupVars.conf

Example
192.168.2.10 cubics.com
fdab:1234:5678::1 cubics.com

All pages with Ads takes minutes to come up, but only devices which uses IPv6.

So I corrected the IP addresses in the setupVars.conf and updated gravity.list. Everything works after that.

Your problem seems a little bit different, but how knows...

You should check if ip address in the webgui are the same like the output of 
pihole# ip addr show

Best regards
Nedy

**Comment by DL6ER** [comment]
The IPv6 address is the same for me on all places and also hasn't changed for some time.

**Comment by DL6ER** [comment]
Seems the problem can be (temporarily) resolved when restarting the router. I have no idea how that comes about, currently. Wireshark does not show anything specific. It may or not have to do with the fact that my ISP changes my IPv6 prefix from time to time...

**Comment by jacobsalmela** [comment]
Is this still an active issue @DL6ER ?

**Comment by DL6ER** [comment]
No, it has been resolved. I wasn't aware anymore that I had opened this ticket here. Closing.
