### ISSUE TITLE
lighttpd wont start

### ISSUE THREAD

**Issue by lug-gh** [pi-hole/pi-hole#1215]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_7_

---

Hi,

i just installed pihole on my orange pi pc (raspberry clone).
so far so good, but lighttpd wont start, it fails with php.

this is from the error log:

2017-02-04 16:50:48: (log.c.166) server started
2017-02-04 16:50:48: (mod_fastcgi.c.1103) the fastcgi-backend /usr/bin/php-cgi failed to start:
2017-02-04 16:50:48: (mod_fastcgi.c.1114) terminated by signal: 9
2017-02-04 16:50:48: (mod_fastcgi.c.1397) [ERROR]: spawning fcgi failed.
2017-02-04 16:50:48: (server.c.976) Configuration of plugins failed. Going down.

all php packages (php5  php5-cgi php5-common) are installed, i even purged the whole packages, uninstalled pihole and reinstalled, so i have no clue whats going on..

install.log: http://pastebin.com/d13kDJ8w
debug.log: http://pastebin.com/5Fws2Gn0

addendum: no other process is blocking port 80

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
What is the output of `php --version` and `whereis php`?

**Comment by technicalpyro** [comment]
did lighttpd and php install in their default locations as a part of the install script?

**Comment by lug-gh** [comment]
yes they did, but something was wrong somewhere in that os.

i just installed a fresh debian 8 image and now it works fine
