### ISSUE TITLE
Synology (chroot) disabling the pi-hole service in the webinterface is not working (Running in chroot, ignoring request)

### ISSUE THREAD

**Issue by kaazvaag** [pi-hole/pi-hole#1217]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1 {replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG | ISSUE] Expected Behaviour:**
When I select disable in the webinterface. I would expect that adblocking is also disabled.

**[BUG | ISSUE] Actual Behaviour:**
When I select disable in the webinterface. The pi-hole service is not disabled.
When I use the cli in chroot (on my Synology): "pihole disable" I get:

root@DiskStation:/# pihole disable
::: Blocking has been disabled!
Running in chroot, ignoring request.
root@DiskStation:/#

So the request is ignored. Which is very annoying.

**[BUG | ISSUE] Steps to reproduce:**
Install the Chroot package on a Synology nas.
Install pi-hole https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289
Disable the pi-hole service in the webinterface.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289

**Comment by kaazvaag** [comment]
Thanks for the quick reply. I equested support in the forum.

**Comment by dschaper** [comment]
Thanks!
