### ISSUE TITLE
chroot detection

### ISSUE THREAD

**Issue by bakman2** [pi-hole/pi-hole#1218]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
8

**[REQUEST] Expected Behaviour:**
Perform a detection of a chroot-ed environment for restartDNS()

Currently when running on a Synology NAS in chroot, systemctl will be validated as true, causing the inability of disabling pihole and inability to use the webgui to perform black/whitelist updates without manual commandline intervention as systemctl cannot be used in chroot.

One way to detect chroot environments is to use: `ls -id \` which gives an output of 2 if on a native filesystem and any other number in a chroot environment.

Example:

    restartDNS() {
      dnsmasqPid=$(pidof dnsmasq)
      if [[ ${dnsmasqPid} ]]; then
         # service already running - reload config
         if [ -x "$(command -v systemctl)" ]  && [ "$(ls -id /)" == 2 ];then
          systemctl restart dnsmasq
         else
          service dnsmasq restart
         fi
        else
        # service not running, start it up
        if [ -x "$(command -v systemctl)" ]  && [ "$(ls -id /)" == 2 ]; then
         systemctl start dnsmasq
        else
         service dnsmasq start
        fi
       fi
       }
 
I am not sure if this would break any installations, perhaps there is another way ?

**Comment by dschaper** [comment]
We do a lot of detection of init systems via `command -v` for systemctl or service. May be able to add a section to the `distro_check` section of the code to determine if we are running in a chroot environ.

**Comment by dschaper** [comment]
Following up, in the chroot environment, `service dnsmasq restart` does function? The problem is that is never called, because `systemctl` is detected and that is attempted (and fails) first?

**Comment by bakman2** [comment]
It is not called because 'systemctl' comes back with an error that systemctl cannot be used in a chroot environment. 'service dnsmasq restart' works.

**Comment by dschaper** [comment]
Thanks for the confirmation. Just wanted to make sure `service` worked okay.

**Comment by dschaper** [comment]
This needs a bump in priority, but we also need an environment to test in. Any suggestions on what we can use to test with are welcome and encouraged.

**Comment by bakman2** [comment]
I can test any solution i think, sorry for the delay.

**Comment by yubiuser** [comment]
Pi-hole came a long way since this has been discussed. Please open a new ticket if the issue persists.
