### ISSUE TITLE
Upgrade to 2.12.1 fails

### ISSUE THREAD

**Issue by K-Ko** [pi-hole/pi-hole#1219]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG] Expected Behaviour:**

Upgrade pihole to 2.12.1

**[BUG | ISSUE] Actual Behaviour:**

Version 2.12

    # sudo pihole -up
    /usr/local/bin/pihole: Zeile 52: /opt/pihole/update.sh: Datei oder Verzeichnis nicht gefunden

**(Optional) Debug token generated by `pihole -d`:**

    # sudo pihole -d -up
    /usr/local/bin/pihole: Zeile 42: /opt/pihole/piholeDebug.sh: Datei oder Verzeichnis nicht gefunden

**Comment by dschaper** [comment]
Can you get us the `ls -lach /opt/pihole` outuput?

**Comment by K-Ko** [comment]
# ls -lach /opt/pihole
    insgesamt 8,0K
    drwxr-xr-x 2 root root 4,0K Jan 29 06:31 .
    drwxr-xr-x 4 root root 4,0K Dez 23 19:45 ..

**Comment by K-Ko** [comment]
Had similar problem at one of the last upgrades... #1049

**Comment by K-Ko** [comment]
# ls -lh /etc/.pihole/advanced/Scripts/
    insgesamt 56K
    -rwxr-xr-x 1 root root 3,7K Jan 29 06:30 chronometer.sh
    -rwxr-xr-x 1 root root 6,4K Jan 29 06:30 list.sh
    -rwxr-xr-x 1 root root  13K Jan 29 06:30 piholeDebug.sh
    -rwxr-xr-x 1 root root  710 Jan 29 06:30 piholeLogFlush.sh
    -rwxr-xr-x 1 root root 2,9K Okt 30 03:12 setupLCD.sh
    -rwxr-xr-x 1 root root 6,6K Jan  9 06:56 update.sh
    -rwxr-xr-x 1 root root 3,9K Jan  3 06:30 version.sh
    -rwxr-xr-x 1 root root 7,5K Jan 29 06:30 webpage.sh

**Comment by K-Ko** [comment]
Again with `pihole -r` it worked, but it can't be the final solution :-(

**Comment by dschaper** [comment]
Thanks, and agreed that `pihole -r` isn't the ideal approach. And `sudo git status` in the `/etc/.pihole` directory comes back with master and all things okay? Can you get us the hash that is shown with master?

**Comment by spx01** [comment]
Can confirm, same problem. Can't upgrade from 2.12 to 2.12.1
`/usr/local/bin/pihole: line 52: /opt/pihole/update.sh: No such file or directory`

**Comment by DL6ER** [comment]
@K-Ko @spx01 please run and post the output of
```
cd /etc/.pihole/ && git rev-parse --abbrev-ref HEAD
cd /etc/.pihole/ && git describe --long --dirty --tags
cd /var/www/html/admin && git rev-parse --abbrev-ref HEAD
cd /var/www/html/admin && git describe --long --dirty --tags
```

**Comment by spx01** [comment]
`cd /etc/.pihole/ && git rev-parse --abbrev-ref HEAD`
`master`

`cd /etc/.pihole/ && git describe --long --dirty --tags`
`v2.12-0-g8cb4304`

`cd /var/www/html/admin && git rev-parse --abbrev-ref HEAD`
`master`

`cd /var/www/html/admin && git describe --long --dirty --tags`
`v2.4-0-g406877d`

**Comment by Mcat12** [comment]
Something must have failed during install to make that directory empty. Run `pihole -r` to Repair.

**Comment by dschaper** [comment]
Assigning myself to check for potential race conditions that would leave that directory in a bare state prior to `git pull` updating the process.

**Comment by K-Ko** [comment]
Same after upgrade to 2.13

    # pihole -g
    /usr/local/bin/pihole: Zeile 68: /opt/pihole/gravity.sh: Datei oder Verzeichnis nicht gefunden

**Comment by K-Ko** [comment]
```
# cd /etc/.pihole/ && git rev-parse --abbrev-ref HEAD
master

# cd /etc/.pihole/ && git describe --long --dirty --tags
v2.13-0-g6f1ed28

# cd /var/www/html/admin && git rev-parse --abbrev-ref HEAD
master

# cd /var/www/html/admin && git describe --long --dirty --tags
v2.5-0-g00f4d31
```

**Comment by DL6ER** [comment]
By any chance, do you still have the output of `pihole -up`. Is there something special about your particular installation? What is the device/OS you are using?

**Comment by K-Ko** [comment]
Nothing special, except that `pihole -up` runs via cron each night

Raspberry with Jessie lite

``` bash
# sudo cat /etc/cron.daily/pihole
#!/bin/sh
/usr/local/bin/pihole updatePihole >/dev/null
/usr/local/bin/pihole updateGravity >/dev/null
/usr/local/bin/pihole admin password
```

**Comment by DL6ER** [comment]
Oh that makes a lot of sense then, if `cron` is running it. That is a fundamental difference to you running it under `sudo`!

Change your `cron` jobs to something like:
```
PATH="$PATH:/usr/local/bin/" pihole updatePihole
PATH="$PATH:/usr/local/bin/" pihole updateGravity
PATH="$PATH:/usr/local/bin/" pihole admin password
```

**Comment by K-Ko** [comment]
But `/usr/local/bin` is still in `root` path...

```
# sudo -i

# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by DL6ER** [comment]
But `cron` is special! This is what I meant by saying

> That is a fundamental difference to you running it under `sudo`!

Experimental verification (on Raspbian Jessie Lite, as you said):

1. `sudo crontab -e`
2. add `* *  *   *   *     echo "$PATH" > /path`

```
 pi@pihole ~ $ cat /path
 /usr/bin:/bin
 ```

**Comment by K-Ko** [comment]
Ups, you are right...

I'll try you suggestion.

**Comment by K-Ko** [comment]
Nop, last night same wrong 2.13.1 update...

Would it help to run `pihole -d -up >/var/log/pihole.cron.log` that you can see what is going on?

Had to `pihole -r` again

**Comment by DL6ER** [comment]
Yes, but

- don't run `-d` and `up` at the same time
- pipe also `stderr`

```
PATH="$PATH:/usr/local/bin/" pihole -up &> /var/log/pihole.cron.log
```

**Comment by K-Ko** [comment]
ok changed, have to wait for next update :-)

**Comment by K-Ko** [comment]
Update to v2.13.2 via cron worked now with

```
PATH="$PATH:/usr/local/bin/" pihole updatePihole & >/var/log/pihole.$(date +%Y%m%d).log
PATH="$PATH:/usr/local/bin/" pihole updateGravity >/dev/null
PATH="$PATH:/usr/local/bin/" pihole admin password
```

Missed redirecting stderr, will append after next update...

But would better if pihole internally uses absolute paths I think.

**Comment by DL6ER** [comment]
I agree, we are slowly getting there...

**Comment by K-Ko** [comment]
Ups, just tried and same error as before:

```
# pihole -c
/usr/local/bin/pihole: Zeile 147: /opt/pihole/chronometer.sh: Datei oder Verzeichnis nicht gefunden
```

Frontend also not worked as expected, data was was from yesterday.

Had to `pihole -r` again...

**Comment by dschaper** [comment]
Keeping this open as we are set for a new release in a bit and I'd like to check and see if this problem persists.

**Comment by Luis-3M** [comment]
after doing `pihole -r` I was ables to run `pihole -g` again.

**Comment by dschaper** [comment]
Closing, should be fully resolved. Please reopen if issue continues.
