### ISSUE TITLE
Installation stops while ' Updating local cache of available packages...'

### ISSUE THREAD

**Issue by thepn** [pi-hole/pi-hole#1220]
When I try to install the pi-hole using curl -L https://install.pi-hole.net | bash the installation stops at the same time: 

Installation output: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 44034  100 44034    0     0   233k      0 --:--:-- --:--:-- --:--:--  233k
:::
::: You are root.
::: Verifying free disk space...
:::
::: Updating local cache of available packages...root@debian1:/home# 

OS: Debian 8

**Comment by dschaper** [comment]
`curl -sSL https://install.pi-hole.net | sudo bash -x` will show where the process is locking up and dropping to shell.

**Comment by ntouvaris** [comment]
hello there, i am having a similar issue (trying to reinstall)

curl -sSL https://install.pi-hole.net | sudo bash -x
+ set -e
+ tmpLog=/tmp/pihole-install.log
+ instalLogLoc=/etc/pihole/install.log
+ setupVars=/etc/pihole/setupVars.conf
+ lighttpdConfig=/etc/lighttpd/lighttpd.conf
+ webInterfaceGitUrl=https://github.com/pi-hole/AdminLTE.git
+ webInterfaceDir=/var/www/html/admin
+ piholeGitUrl=https://github.com/pi-hole/pi-hole.git
+ PI_HOLE_LOCAL_REPO=/etc/.pihole
+ PI_HOLE_FILES=(chronometer list piholeDebug piholeLogFlush setupLCD update version gravity uninstall webpage)
+ PI_HOLE_INSTALL_DIR=/opt/pihole
+ useUpdateVars=false
+ IPV4_ADDRESS=
+ IPV6_ADDRESS=
+ QUERY_LOGGING=true
++ stty size
++ echo 24 80
+ screen_size='24 80'
++ echo '24 80'
++ awk '{print $1}'
+ rows=24
++ echo '24 80'
++ awk '{print $2}'
+ columns=80
+ r=12
+ c=40
+ r=20
+ c=70
+ skipSpaceCheck=false
+ reconfigure=false
+ runUnattended=false
+ [[ '' != true ]]
+ main
+ echo :::
:::
+ [[ 0 -eq 0 ]]
+ echo '::: You are root.'
::: You are root.
+ distro_check
+ command -v apt-get
+ PKG_MANAGER=apt-get
+ UPDATE_PKG_CACHE='apt-get update'
+ PKG_INSTALL=(${PKG_MANAGER} --yes --no-install-recommends install)
+ PKG_COUNT='apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+ apt-get install --dry-run iproute2
+ iproute_pkg=iproute2
+ apt-get install --dry-run php
+ phpVer=php5
+ INSTALLER_DEPS=(apt-utils debconf dhcpcd5 git whiptail)
+ PIHOLE_DEPS=(bc cron curl dnsmasq dnsutils ${iproute_pkg} iputils-ping lighttpd lsof netcat ${phpVer}-common ${phpVer}-cgi sudo unzip wget)
+ LIGHTTPD_USER=www-data
+ LIGHTTPD_GROUP=www-data
+ LIGHTTPD_CFG=lighttpd.conf.debian
+ DNSMASQ_USER=dnsmasq
+ [[ -f /etc/pihole/setupVars.conf ]]
+ [[ false == true ]]
+ verifyFreeDiskSpace
+ echo '::: Verifying free disk space...'
::: Verifying free disk space...
+ local required_free_kilobytes=51200
++ df -Pk
++ grep -m1 '\/$'
++ awk '{print $4}'
+ local existing_free_kilobytes=2518252
+ [[ 2518252 =~ ^([0-9])+$ ]]
+ [[ 2518252 -lt 51200 ]]
+ update_pacakge_cache
+ echo :::
:::
+ echo -n '::: Updating local cache of available packages...'
::: Updating local cache of available packages...+ apt-get update


and it stops.

any ideas?
latest raspbian

**Comment by DL6ER** [comment]
Run `sudo apt-get update` separated from the installer any watch for any errors. We have a fix that catches theses errors in the next update of Pi-hole.

**Comment by ntouvaris** [comment]
sudo apt-get update
Hit http://mirrordirector.raspbian.org jessie InRelease
Ign http://apt.mopidy.com jessie InRelease                                            
Hit http://repository.spotify.com stable InRelease                                                              
Hit http://apt.mopidy.com jessie Release.gpg                                                                    
Hit http://apt.mopidy.com jessie Release                                                                        
Get:1 http://apt.mopidy.com jessie/main Sources [28.7 kB]                                                       
Get:2 http://apt.mopidy.com jessie/contrib Sources [7,430 B]                                                  
Get:3 http://apt.mopidy.com jessie/non-free Sources [3,160 B]                                                 
Get:4 http://apt.mopidy.com jessie/main armhf Packages [17.4 kB]                                                              
Hit http://archive.raspberrypi.org jessie InRelease                                                     
Get:5 http://apt.mopidy.com jessie/contrib armhf Packages [5,217 B]                             
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages                                            
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages                                    
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages                                   
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages                                                       
Get:6 http://apt.mopidy.com jessie/non-free armhf Packages [1,038 B]                                                   
Hit http://archive.raspberrypi.org jessie/main armhf Packages                                 
Hit http://archive.raspberrypi.org jessie/ui armhf Packages                                                                
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB                                                    
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en                                                       
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB                                                       
Ign http://mirrordirector.raspbian.org jessie/main Translation-en                        
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB                                                   
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en                                                      
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB                                                        
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB                                                           
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en                         
Ign http://archive.raspberrypi.org jessie/main Translation-en                                        
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB                                                                                                                                                                               
Ign http://archive.raspberrypi.org jessie/ui Translation-en                                                                                                                                                                                  
Ign http://apt.mopidy.com jessie/contrib Translation-en_GB                                                                                                                                                                                   
Ign http://apt.mopidy.com jessie/contrib Translation-en                                                                                                                                                                                      
Ign http://apt.mopidy.com jessie/main Translation-en_GB                                                                                                                                                                                      
Ign http://apt.mopidy.com jessie/main Translation-en                                                                                                                                                                                         
Ign http://apt.mopidy.com jessie/non-free Translation-en_GB                                                                                                                                                                                  
Ign http://apt.mopidy.com jessie/non-free Translation-en                                                                                                                                                                                     
Fetched 63.0 kB in 14s (4,391 B/s)                                                                                                                                                                                                           
W: Failed to fetch http://repository.spotify.com/dists/stable/InRelease  Unable to find expected entry 'non-free/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead

**Comment by DL6ER** [comment]
There it is. Remove the faulty source list.

**Comment by ntouvaris** [comment]
i tried that already. 

> 

 /etc/apt/sources.list

deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi

**Comment by DL6ER** [comment]
The problem is
```
http://repository.spotify.com/dists/stable/InRelease
```

**Comment by ntouvaris** [comment]
that repository is not on my /etc/apt/sources.list !

**Comment by DL6ER** [comment]
Well, whatever `spotify` is, I don't have it on my Raspberry Pi, so I assume you installed something manually. 

```
ls /etc/apt/sources.list.d/
```

**Comment by ntouvaris** [comment]
i got it running!  (now i realize it's not pihole related issue .sorry for posing here)
thank you

**Comment by DL6ER** [comment]
> now i realize it's not pihole related issue .sorry for posing here

No worries, glad we were able to help you out
