### ISSUE TITLE
Default debian page instead of block page

### ISSUE THREAD

**Issue by tomose** [pi-hole/pi-hole#1221]
https://discourse.pi-hole.net/t/getting-lighthttpd-placeholder-page-instead-of-new-unblock-page/1119/8

Was having this issue, and it was of course resolved by removing the non-folders in /var/www/html/

This should be checked during installs and upgrades and the user warned or something.

**Comment by jacobsalmela** [comment]
Made this a [votable feature request](https://discourse.pi-hole.net/t/default-debian-page-instead-of-block-page/3145) on discourse.pi-hole.net.
