### ISSUE TITLE
Extremely slow loading of some sites lately on Firefox and Chrome Mobile

### ISSUE THREAD

**Issue by tomose** [pi-hole/pi-hole#1224]
Your debug token is : 53jkc2pqbm
Related threads:
https://www.reddit.com/r/pihole/comments/5pipvh/strange_website_behavior_after_recent_update/
https://www.reddit.com/r/pihole/comments/5o1cvf/handling_wife_aggro/

Windows 7
Firefox 51.0.1

This issue has gone on for about a week or two now. Hard to pinpoint exactly when it started as it only seems to affect a few sites I visit.

Sites affected: youtube.com, td.af

These sites load in just a few seconds at most on IE. But in FF (even on a clean test profile), youtube can take over a minute to finish loading, and TD can take well over 30 seconds to stop with the loading animation. This rules out shitty DNS servers as being the culprit as IE is not affected by the issue.

This also affects Chrome Mobile on android. Hopping off my wifi and these same sites load up super fast.

**Comment by dschaper** [comment]
There seems to be extra files in the `/var/www/html/admin` directory, have you made any changes to the admin or to the blocked page files?

**Comment by tomose** [comment]
rf.php was a file I put in there.

Though I hadn't experienced any issues until recently with it existing there.

Removing it does seem to have resolved the issue on FF and Chrome though.

Suggestions where to add a custom file that can be accessed directly (I use it to send commands to an RF receiver on the pi) so that it won't interfere with pihole operation?

**Comment by tomose** [comment]
Nix that, spoke too soon. The slowness has returned after a few minutes even with the file gone.

**Comment by tomose** [comment]
Removing my custom rf.php file (which should have no effect) = no fix.
Modified DNS options in router (DDWRT) = no fix.
Disabling DNSMasq in router entirely = no fix.
Rebooting router = no fix.

Removing Comodo as alternate DNS options in pihole = youtube is no longer slow. TD a little slow but NOWHERE near how slow it was.

Added hurricane electric as secondary DNS in phole = same as above, youtube no longer slow. TD a little slow (but at least it loads in under 15 seconds on mobile now). web.archive.org links also no longer hang.

So maybe there's an issue with Comodo's DNS + pihole?

**Comment by ldrrp** [comment]
https://www.groovypost.com/howto/find-fastest-dns-server-namebench/

This helped me find the faster dns in my area. i dropped dns connections speeds in half compared to using google.

**Comment by dschaper** [comment]
Are you using HE's tunneling service as well as their DNS upstreams?

**Comment by dschaper** [comment]
Ping for closure.

**Comment by TeamMorris** [comment]
Could it be ipV6 related? https://discourse.pi-hole.net/t/some-websites-load-very-slow/1876

**Comment by dschaper** [comment]
We won't know unless we get some more feedback from OP.

**Comment by dschaper** [comment]
Closing, timeout. Reopen if still occurring.
