### ISSUE TITLE
Pihole + nginx = failed host check

### ISSUE THREAD

**Issue by kronflux** [pi-hole/pi-hole#1225]
I installed pihole without issues using the standard install script, then proceeded to follow this:
https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration
(both exactly as is, as well as by making the changes to /etc/nginx/sites-available/default instead of the default file listed)

Unfortunately, even with a fresh OS install and default configurations, I can't get it to work - I always end up being redirected to /admin/ on the base IP, and after logging in(using my password created in htaccess) I get the Failed Host Check: 192.168.X.X vs , , , pi.hole, localhost

I need to be using nginx, as I'm trying to run multiple other services on my device.

PS: I'd love to see a version of the install script which allows you to choose between lighttpd, nginx and apache.. Would make this far more versatile. :)

**Comment by Tntdruid** [comment]
That guide is outdated, see here https://discourse.pi-hole.net/t/running-pi-hole-with-nginx/812/2

**Comment by diginc** [comment]
You can reference [my working alpine+nginx config for docker](https://github.com/diginc/docker-pi-hole/blob/master/alpine/nginx.conf).  I started with that wiki page or someone else's config as a basis and tweaked it.  the `fastcgi_pass 127.0.0.1:9000` line might be different for your system, I believe that was just the default for the php5 package alpine runs (debian maybe the socket file instead)

If you read it you'll see I have different 404 logic that matches lighttpd more closely.  Most recently I moved the php support out of /admin/ block to enable the new blocked page 'unblock this page?' button functionality.

Remove the outdated guide!  Make a new discourse FAQ maybe.

**Comment by kronflux** [comment]
I guess I should have mentioned, having at least some knowledge of how nginx works, I have actually tried both the /etc/nginx/conf.d/default as well as the /etc/nginx/sites-available/default files(separately, of course)
I have also set permissions and ownership accordingly(I do this as a "just in case" everytime I install nginx.

So it's neither of those issues.

I have taken a look at your config @diginc, however a lot of the options cause errors in nginx, and taking bits and pieces which don't cause issues, I have had no success.

Yes, definitely remove the outdated guide, and create a new, up to date, functional guide!

**Comment by dschaper** [comment]
Thank you for updating the guide.

**Comment by kronflux** [comment]
I have solved my issue, apparently my config(/etc/pihole/setupVars.conf) did not get my IP address during the setup, and therefore was causing the "Failed Hosts Check" because it's own IP was not in the "trusted" list.
All I did was add my IP into the correct spot in that config, then rebooted and all is working!
I've also updated the nginx guide with my current config. :)

**Comment by mfr00t** [comment]
I already ran into this issue, after changing the hostname of my raspberry pi.

Changed from "berry" to "pihole.<sub>.<domain>"
All hosts entries got fixed, local and custom list aswell, but it didn't work at all.

Final solution was to add the fqdn-hostname to /var/www/html/admin/scripts/pi-hole/php/auth.php

`diff --git a/scripts/pi-hole/php/auth.php b/scripts/pi-hole/php/auth.php
index 7398cbd..d004d02 100644
--- a/scripts/pi-hole/php/auth.php
+++ b/scripts/pi-hole/php/auth.php
@@ -40,6 +40,7 @@ function check_cors() {
         $ipv6,
         str_replace(array("[","]"), array("",""), $_SERVER["SERVER_NAME"]),
         "pi.hole",
+        "pihole.<sub>.<domain>.at",
         "localhost"
     );`

**Comment by dschaper** [comment]
Changing those files will break the update process and will end any support from the Pi-hole team.

**Comment by mfr00t** [comment]
> Changing those files will break the update process and will end any support from the Pi-hole team.

indeed, i know - it's not a real solution as mentioned above, it's just a dirty workaround.

**Comment by trupf** [comment]
See my comment here for a fix which will not break again with update of pihole:

[https://github.com/pi-hole/AdminLTE/issues/860#issuecomment-731847325](https://github.com/pi-hole/AdminLTE/issues/860#issuecomment-731847325)

But I think it real fix should be done in the pihole source code.

**Comment by htims1989** [comment]
To anyone finding this from googling the error, I had problems because in my nginx server declaration I have two entries for server_name in my nginx config:
`server {
        listen 443;
        ssl on;
        server_name www.x.com x.com;`

I was trying to access it on x.com rather that www.x.com.

In scripts/pi-hole/php/auth.php it is using `$_SERVER["SERVER_NAME"])` to get the server_name which only returns the first server_name for nginx as per: https://fisharebest.stonystratford.org/132/where-does-php-get-_serverserver_name-apache-versus-nginx/

I switched them around like so and all is working:
`server {
        listen 443;
        ssl on;
        server_name x.com www.x.com;`

**Comment by afzl-wtu** [comment]
> To anyone finding this from googling the error, I had problems because I have two entries for server_name in my nginx server config:
> 
> ```
> server {
>         listen 443;
>         ssl on;
>         server_name www.x.com x.com;
> ```
> 
> I was trying to access it on x.com rather than [www.x.com](http://www.x.com).
> 
> In scripts/pi-hole/php/auth.php it is using `$_SERVER["SERVER_NAME"])` to get the server_name which only returns the first server_name for nginx as per: https://fisharebest.stonystratford.org/132/where-does-php-get-_serverserver_name-apache-versus-nginx/
> 
> I switched them around like so and all is working:
> 
> ```
> server {
>         listen 443;
>         ssl on;
>         server_name x.com www.x.com;
> ```

Lol.. I wish I read it before. It is ultimate solution. In my pihole.conf file I changed from www.afzl.me to afzl.me and it worked. and now I see your reply.

**Comment by rube200** [comment]
Recently i stepped in this problem, in my case my solution was editing `/etc/nginx/fastcgi.conf` changing from `fastcgi_param SERVER_NAME $server_name;` to `fastcgi_param SERVER_NAME $http_host;`

**Comment by somehibs** [comment]
I had this problem when accessing a Docker pihole instance using lighttpd over IPv6. I don't let pi.hole consume port 80, so I access it via direct IP to :8111.

Using a raw IPv6 IP address causes the host check to fail where it should be skipped. No one bothers to parse the IPv6 address and PHP's standard library doesn't care about fixing it.

Add the port to the 'remove brackets' code and you'll be able to get in until the next update / docker restart.
    $server_host = str_replace(array('[', ']', ':8111'), array('', '', ''), $server_host);
