### ISSUE TITLE
Failed installation killing SSH connection and partly interface

### ISSUE THREAD

**Issue by VexMex** [pi-hole/pi-hole#1226]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{-1}_

---

**[BUG | ISSUE] Expected Behaviour:**
Continue Installation after the first inouts of static IP and DNS

**[BUG | ISSUE] Actual Behaviour:**
Does not Continue after setting up the Google DNS and killing interface access (SSH not working, access into the internet also not working while monitor hooked up and trying the browser, but network bridge (eth0 to wlan) does still work) 
Checked SSH config and yes, it is enabled, and the eth0 port seems to work since the network bridge is working
Yes i did update and upgrade just before the isntall

**[BUG | ISSUE] Steps to reproduce:**

-Start the Installation over the script
-Just hit enter a few times since static ip is already there
-Have a x on IPv4 and IPv6
-Use google as DNS
-wait till putty closes connection and no ssh connection is possible anymore 

**(Optional) Debug token generated by `pihole -d`:**

Cant ssh into the pi anymore after the failed installation

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
if you are connected through a monitor can you access and either paste here or pastebin the contents of the install log file located in /etc/pihole/install.log

**Comment by VexMex** [comment]
sadly to say but after trying alot of things (thought at first im to dumb to move this file over to a new usb drive since i cant access the internet on my pi anymore)

it turns out there is no install.log in the pihole folder, the folder is empty :T (like i said, tried to move this non existant file with the pi itself and now looking into it with the ext2explorer and there is nothing)

**Comment by technicalpyro** [comment]
another thing to look at would be running the following command from the pi itself `ifconfig `
and paste the results here that will tell us if there is a configuration error inm your system in regards to connections

**Comment by VexMex** [comment]
before i do that and afterwards google myself to death again, is there a way to save the console output afterwards? since i cant connect with the pi to the internet anymore i cant just paste it to here :T

**Comment by VexMex** [comment]
br0       Link encap:Ethernet  HWaddr a4:2b:b0:bd:e2:35
          inet addr:192.168.178.40  Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:feea:f752/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:95851 errors:0 dropped:0 overruns:0 frame:0
          TX packets:51302 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:132135918 (126.0 MiB)  TX bytes:3670444 (3.5 MiB)

eth0      Link encap:Ethernet  HWaddr b8:27:eb:ea:f7:52
          inet addr:x Bcast:x  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:111427 errors:0 dropped:4 overruns:0 frame:0
          TX packets:57119 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:141974349 (135.3 MiB)  TX bytes:5115974 (4.8 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:136 errors:0 dropped:0 overruns:0 frame:0
          TX packets:136 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:11472 (11.2 KiB)  TX bytes:11472 (11.2 KiB)

wlan0     Link encap:Ethernet  HWaddr a4:2b:b0:bd:e2:35
          inet addr:x  Bcast:x  Mask:255.255.0.0
          inet6 addr: fe80::784f:13f6:cb6c:99d3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5757 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16877 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:766557 (748.5 KiB)  TX bytes:10657159 (10.1 MiB)

das ist vor der pihole installation

**Comment by VexMex** [comment]
after the failed install, it looks like this 

br0 Link encap:Ethernet HWaddr a4:2b:b0:bd:e2:35
inet6 addr: fe80::ba27:ebff:feea:f752/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:95851 errors:0 dropped:0 overruns:0 frame:0
TX packets:51302 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:132135918 (126.0 MiB) TX bytes:3670444 (3.5 MiB)

eth0 Link encap:Ethernet HWaddr b8:27:eb:ea:f7:52
inet addr:192.168.178.40 Bcast:192.168.178.255 Mask:255.255.0.0
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:697 errors:0 dropped:4 overruns:0 frame:0
TX packets:418 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:blabla(135.3 MiB) TX bytes:5115974 (4.8 MiB)

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:136 errors:0 dropped:0 overruns:0 frame:0
TX packets:136 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1
RX bytes:11472 (11.2 KiB) TX bytes:11472 (11.2 KiB)

wlan0 Link encap:Ethernet HWaddr a4:2b:b0:bd:e2:35
inet6 addr: fe80::784f:13f6:cb6c:99d3/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:305 errors:0 dropped:0 overruns:0 frame:0
TX packets:627 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:44697 (748.5 KiB) TX bytes:10657159 (10.1 MiB)

**Comment by dschaper** [comment]
What is the output of `ip link` prior to install? Are you getting the option to select the interface when you install? And how are you configuring the bridged interface?

**Comment by VexMex** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:ea:f7:52 brd ff:ff:ff:ff:ff:ff
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether a4:2b:b0:bd:e2:35 brd ff:ff:ff:ff:ff:ff
4: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP mode DEFAULT group default qlen 1000
    link/ether a4:2b:b0:bd:e2:35 brd ff:ff:ff:ff:ff:ff




Yes i get the option to select the interface, eth0, br0 and wlan0 and i choose th0 since that is the ethernet cable.
The bridge i have configured like this website https://www.elektronik-kompendium.de/sites/raspberry-pi/2002161.htm or short with hostapd and bridge-utils
ignore the walls of text, just the commands one after another typed in and it worked for me

**Comment by dschaper** [comment]
Try using the bridge interface instead of `eth0`.

**Comment by VexMex** [comment]
i feel stupid now..... Thanks yes it works now
