### ISSUE TITLE
Avast Antivirus bypass Pi-Hole DNS

### ISSUE THREAD

**Issue by amiwilliamwill** [pi-hole/pi-hole#1227]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 

0

---
**OTHER**

**[BUG | ISSUE] Expected Behaviour:**
Pi-Hole works perfectly on other devices that do not have Avast Antivirus installed. In my case, all my mobile devices work perfectly with Pi-hole while my laptop was not blocking any ads.

**[BUG | ISSUE] Actual Behaviour:**
On the affected device, Pi-hole register the query from the device and attempt at blocking ads, a feature of Avast Antivirus called "Secure DNS" bypasses the Pi-hole settings and ads are not blocked. 

**[BUG | ISSUE] Steps to reproduce:**

- With Avast Antivirus installed and Secure DNS enabled all internet traffic will go through the Pi-hole but the DNS query will be directed and resolved by Avast DNS. 
- To disable Secure DNS, go to Avast settings, under components, Secure DNS can be disabled or completely uninstalled.
- Once Secure DNS is disabled, pi-hole should work fine

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
OK, so the fix is to disable Secure DNS on the client, since Pi-hole can't work around it.

**Comment by DL6ER** [comment]
From the Avast FAQ:

> [It uses] Avast's own DNS server to ensure that the web page in your browser is the authentic one.

and

> If Secure DNS offers a different IP address than your internet provider, the Avast IP address is used.
