### ISSUE TITLE
Installation aborting w/ error [OSMC]

### ISSUE THREAD

**Issue by matematrix** [pi-hole/pi-hole#1229]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{6}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Installation will complete

**[BUG | ISSUE] Actual Behaviour:**
It gives me an error

**[BUG | ISSUE] Steps to reproduce:**

- Start the installation with `sudo curl -sSL https://install.pi-hole.net | bash` on a Raspberry Pi 2 Model B. (with OSMC installed as OS, but that shouldn't be a problem)
- Follow the installation until you need to select a Upstream DNS Provider.
- Select one.
- The installation quits and gives the error: 
`bash: line 192: ip: command not found
::: Using Comodo Secure servers.
bash: line 182: ip: command not found
`
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Not sure why this was closed, it's a valid request and patch is in work for review. Is there a reason for it being closed?

**Comment by dschaper** [comment]
Aside: OSMC is a cut down version, so it's missing a few things. We can work around that though.

**Comment by matematrix** [comment]
Yes, I closed it because I forgot searching the web before trying to install it. The search gave me the result that I need to install some other packages for it to work. Since I didn't have them installed, I closed the thread.

I hope this didn't cause any confusement.

**Comment by dschaper** [comment]
No problem, I'll reopen because it is a valid problem. Thanks for reporting it.

**Comment by matematrix** [comment]
Thank you for the great software :)

**Comment by Mcat12** [comment]
Fixed by #1231

**Comment by BattleGear** [comment]
hi mate

got the same bug... so i want to quest when is the next release where is fixing the bug?
or can you give me a list of packages where missing?

**Comment by matematrix** [comment]
@BattleGear 
Hi there, 
I think whiptail is also needed :)

**Comment by xxcriticxx** [comment]
thx to @matematrix and @BattleGear i dusted off my apple tv 1 with OSMC and install pi-hole on it with out any problems
