### ISSUE TITLE
Installer fails: ip not found

### ISSUE THREAD

**Issue by pabloko** [pi-hole/pi-hole#1230]
Seems its needed to check if <ip> exists before the install process, It comes on "iproute" package on debian.

Installing it solves the issue on osmc 17 (debian)

**Comment by dschaper** [comment]
Can you please edit your post and fill out the template so we can look at your issue? Otherwise we will have to close this for lack of required information.

**Comment by pabloko** [comment]
nah i dont even care, that form is pure bullshit and im not filling that shit.

fix that bug if you want. its your users who are suffering it not me.

regards :)

**Comment by pabloko** [comment]
nice edit fag

**Comment by nate-ubiquisoft** [comment]
Great discussion contributions
