### ISSUE TITLE
Pi-Hole installation crashes

### ISSUE THREAD

**Issue by ZerNico** [pi-hole/pi-hole#1232]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Pi Hole get's installed

**[BUG | ISSUE] Actual Behaviour:**
:::
::: Script called with non-root privileges. The Pi-hole installs server packages and configures
::: system networking, it requires elevated rights. Please check the contents of the script for
::: any concerns with this requirement. Please be sure to download this script from a trusted source.
:::
::: Detecting the presence of the sudo utility for continuation of this install...
::: Utility sudo located.
:::
::: You are root.
::: Verifying free disk space...
:::
::: Updating local cache of available packages...

I'm trying to install pi-hole on my Ubuntu 16.10 machine.
When I'm running the script I only get to the package updating, after that it crashes.
I even tried cloning the whole git repo and running the install script there. It just doesn't want to get installed.
**[BUG | ISSUE] Steps to reproduce:**
curl -L install.pi-hole.net | bash

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
That is a known problem and will be solved in the next release (see https://github.com/pi-hole/pi-hole/pull/1183)

Please run `sudo apt-get update` and watch for anything unexpected.

**Comment by ZerNico** [comment]
Oh okay I'm sorry for the duplicate one then

**Comment by dschaper** [comment]
@ZerNico I'm going to close out this issue, if there are still problems, can you follow up in the other thread? Thanks for the report.
