### ISSUE TITLE
Website wrong link

### ISSUE THREAD

**Issue by FallenKN** [pi-hole/pi-hole#1234]
On the offical website (https://pi-hole.net/) the "review the code" is poiting to https://github.com/pi-hole/pi-hole#alternative-semi-automated-install, which is a not existing link.
`<a class="" href="https://github.com/pi-hole/pi-hole#alternative-semi-automated-install" target="_blank">review the code</a>`
It should point to https://github.com/pi-hole/pi-hole#alternative-semi-automated-install-methods so it looks like:
`<a class="" href="https://github.com/pi-hole/pi-hole#alternative-semi-automated-install-methods" target="_blank">review the code</a>`

**Comment by dschaper** [comment]
We welcome all PR's!

**Comment by FallenKN** [comment]
I do not see a Repository for the Website here, but you also could fix this with updating the README.MD but I dont think that is what you want.

**Comment by dschaper** [comment]
@jacobsalmela This one may be in your realm to update. Wordpress?

**Comment by jacobsalmela** [comment]
Yep.  I just fixed it.
