### ISSUE TITLE
blacklist and whitelist singel client or group

### ISSUE THREAD

**Issue by ToronMega** [pi-hole/pi-hole#1236]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST]:**
Hi,
can you pls think about "blacklist and whitelist single client or group".

This can very helpful for solve problems at client or manage client (groups). 

example: Some Windows Clients need some whitelist entry, but all linux/ios/android ......
              Blacklist some site on kids clients, but the adult like to watch (not only porn)

regards

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
From the template:

> Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

> Failure to fill the template will close your issue
