### ISSUE TITLE
Anti-adblock

### ISSUE THREAD

**Issue by notracking** [pi-hole/pi-hole#1246]
Since Pi-hole uses dnsmasq to re-route ad hosts to a local webserver (127.0.0.1), why not add a feature to help by-passing some adblock killers?

Most anti adblock script merely set a local variable in Javascript, like 'noadblocker=true', executed from a script that matches common adblock filter rules (eg: serveads.js) to detect if the user is using adblock.

Based on referer from the re-routed request, the local Pi-hole webserver can lookup which site actually caused the initial request; and therefore instead of returning a transparent pixel it could also send custom made javascript to trick the anti-adblockers in to thinking that their ad JS actually executed.

See reeks user scripts as a nice starting point: https://github.com/reek/anti-adblock-killer

Just my brain fart, might be helpful.

**Comment by spacedingo** [comment]
Personally, I have never seen it while using DNS blocking _alone, without_ browser addons. With Browser addons, however, I have encountered "you're using ad blocking software" message. I have had to whitelist them in ABP or uBlock to proceed.

**Comment by technicalpyro** [comment]
this is not an issue and should be directed as a feature request in the discourse forum.  
the template you deleted expressed this very clearly

**Comment by Mcat12** [comment]
Move the feature request to discourse please.
