### ISSUE TITLE
Status unknown on lede x86-64

### ISSUE THREAD

**Issue by debiansid** [pi-hole/pi-hole#1250]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

6
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Status showing 
**[BUG | ISSUE] Actual Behaviour:**

Status unknown 
**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please explain.

**Comment by PromoFaux** [comment]
>Status unknown

Do you mean on the web admin page?

**Comment by debiansid** [comment]
Yes, exactly

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token and `pihole status`.

**Comment by debiansid** [comment]
cftvrcqkpj 
pihole status
::: DNS service is running
::: Pi-hole blocking is Enabled

**Comment by debiansid** [comment]
The reason is:
Sun Feb 19 01:27:45 2017 authpriv.alert sudo: www-data : command not allowed ; TTY=unknown ; PWD=/mnt/backup/www/html/admin ; USER=root ; COMMAND=pihole status web

But I have 
www-data ALL=(ALL) NOPASSWD: /usr/bin/pinhole
in suders

**Comment by debiansid** [comment]
Uncomment to use a hard-coded PATH instead of the user's
 I fixed by change secure_path in sudoers
