### ISSUE TITLE
/etc/hosts not recognize

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#1251]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
3
---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
The hosts table in /etc/hosts should resolve the name

**[BUG | ISSUE] Actual Behaviour:**
Top clients are just static IP address

**[BUG | ISSUE] Steps to reproduce:**
Set to an IP address a name in /etc/hosts and open the admin page

**(Optional) Debug token generated by `pihole -d`:*dw26gaxbpb*

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

In the past on an older update the hosts work.

**Comment by Mcat12** [comment]
Check the option in the settings page to resolve names in the top clients list.

**Comment by TylonHH** [comment]
I enabled "Reverse DNS lookup" *blushing*

**Comment by SecKarma** [comment]
sorry for opening this but where's the "Reverse DNS lookup" is located? can't seem to find it in the web interface nor in the pi config files located in /etc/pihole.. also /etc/hosts is not working when i add custom domain name / hostname for a specific ip address to work locally... like "http://my.home" ---> 192.168.1.23

what i tried in hosts:

192.168.1.23 my.home

**Comment by Mcat12** [comment]
This is an old issue, and is not relevant anymore. The hostnames are automatically resolved, but you will need to force FTL to re-resolve the hostnames unless you wait for it to do so automatically:
```
echo ">reresolve-hostnames" | nc localhost 4711
```
