### ISSUE TITLE
Load showing red light

### ISSUE THREAD

**Issue by debiansid** [pi-hole/pi-hole#1254]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [Y] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
6
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

 Load:  0.02490234375  0.01025390625 
should be in green
**[BUG | ISSUE] Actual Behaviour:**
Load 0.024 turns light into red

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Is this still on the LEDE install?

**Comment by debiansid** [comment]
yes.exactly.

**Comment by Mcat12** [comment]
What is the output of `nproc`? PHP might think that there are 0 processors available, causing [this](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/header.php#L299) line to make the load red.

**Comment by debiansid** [comment]
I don't have nproc on lede

**Comment by debiansid** [comment]
opkg install coreutils-nproc
fix it. Thanks
