### ISSUE TITLE
DNS queries resets to 0 after 24 hours on chronometer.sh

### ISSUE THREAD

**Issue by Erikih** [pi-hole/pi-hole#1255]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
chronometer.sh should update the script every 5 seconds. The script should display the actual amount of DNS queries, even after 24 hours.

**[BUG | ISSUE] Actual Behaviour:**
When chronometer.sh is running, the amount of DNS queries should be displayed. This works well, but after 24 hours (or after a huge amount of time) you need to cancel the script and reopen it. To show the real amount of DNS queries. Because of the untrue amount of DNS queries, the percentage of pi holed queries are 0%.

**[BUG | ISSUE] Steps to reproduce:**

-Run chronometer.sh
-Wait for at least 24 hours
- Check your display. The amount of DNS queries resetted to 0 and doesn't count up

**(Optional) Debug token generated by `pihole -d`:**

`tceyfjid93`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token.

**Comment by Erikih** [comment]
Edited the post with a debug token.

**Comment by DL6ER** [comment]
Please update your Pi-hole (use `pihole -up`). There have been some few changes, which should have enhanced the behavior of chronometer in general.

**Comment by Erikih** [comment]
Updated the Pi-Hole. After the update, it stopped working actually. So i uninstalled and installed again. Also i didn't know that there is a newer version of chronometer.sh so i downloaded that. After 24 hours of running, it shows the correct amount of DNS queries, Pi-Holed queries and the total amount of domains being blocked. Thanks.
