### ISSUE TITLE
pihole -g (updateGravity) bad name at /etc/pihole/gravity.list [.doubleclick.com; .doubleclick.net]

### ISSUE THREAD

**Issue by mr-bolle** [pi-hole/pi-hole#1256]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG | ISSUE] Expected Behaviour:**
if i update the Gravity (pihole -g) and check after that the pihole.log is get follow errors
bad name at /etc/pihole/gravity.list line xx
bad name at /etc/pihole/gravity.list line xy

192.168.178.20 .doubleclick.com
192.168.178.20 .doubleclick.net

**[BUG | ISSUE] Actual Behaviour:**
pihole -t 
bad name at /etc/pihole/gravity.list line xxx

**BUG | ISSUE] Current solution:**
sudo nano /etc/pihole/gravity.list
remove the dot before this Domain

change follow Line 
192.168.178.20 .doubleclick.com
192.168.178.20 .doubleclick.net
>> to
192.168.178.20 doubleclick.com
192.168.178.20 doubleclick.net

**[BUG | ISSUE] Steps to reproduce:**

- pihole -g
- pihole -t
Feb 19 10:21:35 dnsmasq[25309]: bad name at /etc/pihole/gravity.list line xx
Feb 19 10:21:35 dnsmasq[25309]: bad name at /etc/pihole/gravity.list line xy
- sudo nano /etc/pihole/gravity.list
192.168.178.20 .doubleclick.com
192.168.178.20 .doubleclick.net

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Tntdruid** [comment]
did you add the .doubleclick.com and .doubleclick.net?

**Comment by mr-bolle** [comment]
no, i don't add this domain.
i found the reason there http://adblock.mahakala.is/

0.0.0.0 .doubleclick.net
0.0.0.0 .doubleclick.com

/etc/pihole/adlists.list
# Other lists we consider safe:
http://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://adaway.org/hosts.txt
http://adblock.gjtech.net/?format=unix-hosts
http://adblock.mahakala.is/
http://hosts-file.net/.%5Cad_servers.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt
http://pgl.yoyo.org/adservers/serverlist.php?
http://someonewhocares.org/hosts/hosts
http://winhelp2002.mvps.org/hosts.txt

**Comment by dschaper** [comment]
Mahakala is known to break things, that's why we disable the list and make you add it on manually with a large notice that this list will break things.

**Comment by mr-bolle** [comment]
@dschaper now i disable this source and updateGravity (pihole -g) and this problem disapear. for the future i would select gently the blocking source.

resolved #1256
