### ISSUE TITLE
Blacklist number is wrong in admin web interface

### ISSUE THREAD

**Issue by debiansid** [pi-hole/pi-hole#1258]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by debiansid** [comment]
Aggregating list of domains...cat: can't open '/etc/pihole/list.9.optimate.dl.sourceforge.net.domains': No such file or directory
cat: can't open '/etc/pihole/list.11.raw.githubusercontent.com.domains': No such file or directory
cat: can't open '/etc/pihole/list.12.raw.githubusercontent.com.domains': No such file or directory
cat: can't open '/etc/pihole/list.13.easylist-downloads.adblockplus.org.domains': No such file or directory
 done!
::: Formatting list of domains to remove comments.... done!
::: 315318 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 232708 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 15 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 11 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!

Number in web is still 99234

**Comment by dschaper** [comment]
Can you post the contents of you `/etc/pihole/adlists.list` and `/etc/pihole/adlists.default` please?

**Comment by debiansid** [comment]
As soon as I reach my laptop

**Comment by debiansid** [comment]
update adlist.list and adlist.default to newest , it looks good now.
