### ISSUE TITLE
Pi-Hole does not redirect to /pihole/index.php (apache2)

### ISSUE THREAD

**Issue by Jonn3y** [pi-hole/pi-hole#1260]
Hey everybody,

i installed PiHole today and blacklisted a page to test the service. ex. google.com
When i try to access google.com pi-hole redirects me to <piholeip> but not to <piholeip>/pihole/index.php

But im hosting a page on /

Is there any configfile i can set the default redirect-address?
Im using apache2 .

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [Don't know] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

**[BUG | ISSUE] Expected Behaviour:**
If the URL is blacklistet, redirect to <iphole-ip\>/iphole/index.php

**[BUG | ISSUE] Actual Behaviour:**
If the URL is blacklistet, redirect to <iphole-ip\>/

**[BUG | ISSUE] Steps to reproduce:**

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please fill out the template file for any issues.

**Comment by Jonn3y** [comment]
did it

**Comment by Mcat12** [comment]
You're using your own setup of Apache, so you will need to recreate Pi-hole lighttpd settings manually: https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-apache-and-nginx

**Comment by Happyfeet01** [comment]
Can anyone tell me how do you do this? I also use apache2 instead lighttpd.
