### ISSUE TITLE
Pi Hole on Ubuntu VM Blocking 0 or 1 (Doubleclick)

### ISSUE THREAD

**Issue by jsg7440** [pi-hole/pi-hole#1261]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X?] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
It is very similar to past issues, but I have not been able to find a solution in the previous answers that works to this point.

**How familiar are you with the codebase?:**
1

**[BUG | ISSUE] Expected Behaviour:**
DNS blocking

**[BUG | ISSUE] Actual Behaviour:**
DNS functioning, but no, or only one (doubleclick.net) being blocked

**[BUG | ISSUE] Steps to reproduce:**

-Ubuntu VM generated
-Pi Hole Installed with typical installation process
-Observe DNS queries being served, but nothing being blocked from the interface

Some notes: 
-Using a Fortigate to handle DNS. Doesn't work if I go directly from a client either though
-Attempted changing IP and some network settings to solve the issue, but I'm suspecting I'm missing something really foolish.
-Followed fix guides for others experiencing similar issues with no luck

Debug token generated by `pihole -d`:

`xa42mkc3do`

**Comment by dschaper** [comment]
The debug shows around 100k domain listed for blocking, what happens when you view the log in real time, do you see any activity? (From the web interface, choose Tools, Tail, or via command line, try `pihole -t`.)

**Comment by jsg7440** [comment]
I see quite a bit of traffic now. I didn't yesterday for some reason. I do see quite a bit, but I still am only seeing doubleclick blocked (and rarely)

**Comment by jsg7440** [comment]
Spectacular! I have at least made progress: 
After your suggestion to run the tail and seeing traffic there now I decided to put a client directly through the DNS and it's now blocking actively and aggressively!

I am now 99% sure the failure remaining (not blocking without client adjustment) is entirely due to a layer 8 issue interacting with the Fortigate. If anyone is familiar with their system, I would love some guidance, otherwise I will post back here once I find a solution that works.

**Comment by dschaper** [comment]
Good to see the progress, I'm not familiar with Fortigate, but we'll leave the issue open in case someone else can help, or you may want to post over on discourse.pi-hole.net and see if any of the users there have any way to assist.

**Comment by technicalpyro** [comment]
from the looks of it fortigate has some decent support on their end i would try reaching out to them and asking if they have an ideas looks like they may be in some way shaping your traffic or similar to comodo allowing you to set your own dns but then ignoring it

**Comment by jsg7440** [comment]
Let's mark this as closed. Things are up and running now!

For the record, the Fortigate I use has multiple locations in the interface to point at a DNS. In my case, I was getting weirdness with the interaction of a VPN tunnel and having disparate DNSes set. If anyone else has similar issues, feel free to contact me and I will do what I can to explain in further detail. As it sits, this one feels like a very unlikely edge case to encounter for most people and the description above should be able to get most people on the right track to solving their individual issues.
