### ISSUE TITLE
web admin's setting not able to start/enable dhcp server

### ISSUE THREAD

**Issue by tohjg** [pi-hole/pi-hole#1264]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
dhcp server should be enabled and "dhcp server enabled" should be ticked.

**[BUG | ISSUE] Actual Behaviour:**
after save button clicked, page refreshed. "dhcp server enabled" checkbox is untick. dhcp server not enabled.

i tried to look at issue #1093 solution but i can't find /etc/dnsmasq.d/02-pihole-dhcp.conf was created. 

then, i tired to copy /etc/.pihole/advanced/lighttpd.conf.debian to replace lighttpd.conf. then try to set it again via web admin's setting. still fail.

**[BUG | ISSUE] Steps to reproduce:**
- go into webadmin
- login
- go to setting page.
- ticked "dhcp server enabled".
- clicked "save" button. 

**(Optional) Debug token generated by `pihole -d`:**

`jsuj25droy`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Tntdruid** [comment]
Are you using the latest version?

**Comment by tohjg** [comment]
from the web interface, footer show "Pi-hole Version v2.12.1 Web Interface Version v2.4". im using [pine64](https://www.pine64.org/?product=pine-a64-board-1gb) 1gb board, [dietpi](http://dietpi.com/) os

**Comment by PromoFaux** [comment]
> dietpi os

This may be a compatability thing.

@Fourdee can you think of anything being [done here](https://github.com/Fourdee/DietPi/issues/583#issuecomment-256368564) that would affect things here?

**Comment by Fourdee** [comment]
@PromoFaux 

> This may be a compatability thing.

Possibly, I'll look into your source code for web interface, and, see what commands are executed. Leave it with me.

**Comment by Fourdee** [comment]
> [BUG | ISSUE] Actual Behaviour:
after save button clicked, page refreshed. "dhcp server enabled" checkbox is untick. dhcp server not enabled.

Unable to replicate on DietPi with Odroid C2. Button works as expected.

@tohjg 

Which device are you using?

May also be worth pasting results of this file which contains the variable that is read/changed (https://github.com/pi-hole/AdminLTE/blob/master/settings.php#L118):
```
/etc/pihole/setupVars.conf
```

---

#### I did notice the following (Limited to DietPi, or anyone using ```/etc/network/interfaces``` to configure network):
- If any ```dhcp``` reference is contained within ```/etc/network/interfaces```, even if ```auto up``` is disabled, ```dhcpcd``` will fail to run:
```
root@DietPi:~# systemctl status dhcpcd.service -l
● dhcpcd.service - LSB: IPv4 DHCP client with IPv4LL support
   Loaded: loaded (/etc/init.d/dhcpcd)
   Active: failed (Result: exit-code) since Wed 2017-02-22 15:41:16 GMT; 1s ago
  Process: 2352 ExecStop=/etc/init.d/dhcpcd stop (code=exited, status=6)
  Process: 2359 ExecStart=/etc/init.d/dhcpcd start (code=exited, status=6)

Feb 22 15:41:16 DietPi dhcpcd[2359]: Not running dhcpcd because /etc/network/interfaces ... failed!
Feb 22 15:41:16 DietPi dhcpcd[2359]: defines some interfaces that will use a DHCP client ... failed!
Feb 22 15:41:16 DietPi systemd[1]: dhcpcd.service: control process exited, code=exited status=6
Feb 22 15:41:16 DietPi systemd[1]: Failed to start LSB: IPv4 DHCP client with IPv4LL support.
Feb 22 15:41:16 DietPi systemd[1]: Unit dhcpcd.service entered failed state.
```

Solution is to simply set ```iface wlan0 inet dhcp``` to ```iface wlan0 inet static```

**Comment by tohjg** [comment]
@Fourdee 

> Which device are you using?

im using [pine64 1gb](https://www.pine64.org/?product=pine-a64-board-1gb).

> When did you install PiHole, and, was it through dietpi-software to ensure compatibility with PiHole on DietPi?

last two day. via dietpi-software. i reformat my device yesterday. today i reinstalled today but failed. this is what i get from terminal:
`────────────────────────────────────────────────────
 Mode: Generating new swapfile
 Please wait...

 [Info] Size     = 512 MB
 [Info] Location = /mnt/usb_1/.swapfile
 [Info] Deleting existing swapfile (/mnt/usb_1/.swapfile)

want /mnt/usb_1/.swapfile=512MByte, generating swapfile ... of 512MBytes
Synchronizing state for dphys-swapfile.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d dphys-swapfile defaults
Executing /usr/sbin/update-rc.d dphys-swapfile enable
 [Info] Completed

--2017-02-23 14:07:00--  http://install.pi-hole.net/
Resolving install.pi-hole.net (install.pi-hole.net)... 2400:cb00:2048:1::6818:6c53, 2400:cb00:2048:1::6818:6d53, 104.24.108.83, ...
Connecting to install.pi-hole.net (install.pi-hole.net)|2400:cb00:2048:1::6818:6c53|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh [following]
--2017-02-23 14:07:00--  https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.128.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44034 (43K) [text/plain]
Saving to: ‘install.sh’

install.sh                      100%[========================================================>]  43.00K  3.94KB/s   in 11s    

2017-02-23 14:07:13 (3.94 KB/s) - ‘install.sh’ saved [44034/44034]

:::
::: You are root.
::: Verifying free disk space...
:::
::: Updating local cache of available packages...
 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron
 [Ok] lighttpd
 [Ok] php5-fpm
 [Ok] noip2
 [Ok] fail2ban
 [Ok] openvpn


 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Optimize and configure software
 Please wait...

 [Info] Applying DietPi optimizations and configurations for Pine A64+ 1GB (aarch64)
 [Info] Please wait...

 #               processing | D i e t  P i             #

Enabling fastcgi: ok
Run /etc/init.d/lighttpd force-reload to enable changes
Enabling fastcgi-php: ok
Run /etc/init.d/lighttpd force-reload to enable changes
--2017-02-23 14:07:36--  https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.128.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22915 (22K) [text/plain]
Saving to: ‘/var/www/opcache.php’

/var/www/opcache.php            100%[========================================================>]  22.38K  25.3KB/s   in 0.9s   

2017-02-23 14:07:38 (25.3 KB/s) - ‘/var/www/opcache.php’ saved [22915/22915]

/DietPi/dietpi/dietpi-software: line 7538: pihole: command not found

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: disable
 Please wait...

 [Ok] cron
 [Ok] lighttpd
 [Ok] php5-fpm
 [Ok] noip2
 [Ok] fail2ban
 [Ok] openvpn


 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installation completed
 Please wait...


 The system will now reboot. 
 This completes the DietPi-Software installation.

`
can i install via curl directly provided from official pihole ?

> May also be worth pasting results of this file which contains the variable that is read/changed (https://github.com/pi-hole/AdminLTE/blob/master/settings.php#L118):

as far as i can remember, the config file doesn't have "DHCP_ACTIVE" key after i set it. i will try again and let you know.

thanks.

**Comment by tohjg** [comment]
@Fourdee 

unable to install pihole at this moment

**Comment by Fourdee** [comment]
@tohjg 

> last two day. via dietpi-software. i reformat my device yesterday. today i reinstalled today but failed. this is what i get from terminal:

Strange, I just completed a fresh DietPi image and install of PiHole, unable to replicate: ```/DietPi/dietpi/dietpi-software: line 7538: pihole: command not found```

Lets try uninstall/install of PiHole
```
dietpi-software uninstall 93
# When asked for ::: Do you wish to purge PiHole's dependencies from your OS? (You will be prompted for each package) [y/n]:
# Say n
```

To ensure compatibility with DietPi and PiHole install, please use ```dietpi-software``` to reinstall PiHole. Although we use the official installer for PiHole, DietPi does some stuff in the background to ensure compatibility:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L3872-L3904

**Comment by tohjg** [comment]
@Fourdee 

i uninstalled it and installed it again via `dietpi-software`. error still persist. i guess i have to do a fresh system.

my wild guess: must be something to do with write permission, not granted to www-data to do changes to `/etc/pihole/setupVars.conf`. i have to dig into php/lighttpd log and let you know.

**Comment by tohjg** [comment]
@Fourdee 

i traced out command to enable dhcp from [savesetting.php](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/savesettings.php#L371). the command executed successfully over ssh.

then, i added a new user. let's call it bob. added him as sudoer. got an error saying `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set` while executing `pihole` command. i googled around about the error and found a magic command

`chmod 4755 /usr/bin/sudo`

perhaps you may want to set this during [initial setup](https://github.com/Fourdee/DietPi/blob/master/dietpi/boot).

**Comment by tohjg** [comment]
@Fourdee this issue transfer to dietpi repo's [#775](https://github.com/Fourdee/DietPi/issues/775). thanks, @PromoFaux  @Tntdruid.
