### ISSUE TITLE
03-pihole-wildcard.conf not getting updated on IPV6 change

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1270]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
My pi got a new IPV6 and the 03-pihole-wildcard.conf did not get updated, still use the old IPV6.

Is that a bug?

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Yes, what you see is what is expected as the entries are created with the IPs stored in `/etc/pihole/setupVars.conf` at their creation time. There is no code that would update these entries afterwards.

Do you think that is needed?

**Comment by dschaper** [comment]
I can see a vastly improbable security leak potential. (On the order of astronomically small.) If the old IPv6 is recycled by the ISP and the new owner happens to be running an open DNS resolver or web server, you could potentially have some information leak to the new owner of the IPv6 address. There is also the chance that the DNS information received in such a case would be tainted. However, from research, the ISP's that rotate addresses either assign virgin addresses from a pool, or they have a lease time of like 24 hours. Chances of this happening are like winning the lottery kind of odds, but somebody wins eventually. (But with IPv6 space, it's really a thought experiment, maybe once in a million years?)
