### ISSUE TITLE
Domain not blocked instantly but instead times out after 30s, causing web pages to "load" until the timeout

### ISSUE THREAD

**Issue by matrixagent** [pi-hole/pi-hole#1271]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG | ISSUE] Expected Behaviour:**
Websites that are loading https://script.ioam.de/iam.js should not be negatively affected by using pihole. The script should be instantly blocked as the domain is on a few blocklists.

**[BUG | ISSUE] Actual Behaviour:**
Instead of instantly blocking the request to script.ioam.de, it just times out after 30 seconds. This causes the browser to keep "loading" the site despite actually already being finished.

**[BUG | ISSUE] Steps to reproduce:**

On my Mac, which is setup to use 192.168.2.1 (my router, which is configured to use only 192.168.2.58, my pihole, as DNS) as (the only) DNS server I run the following in my terminal:

```
manu@mmbp:~$ time curl -i https://script.ioam.de/iam.js
curl: (6) Could not resolve host: script.ioam.de
curl -i https://script.ioam.de/iam.js  0.00s user 0.00s system 0% cpu 30.604 total
manu@mmbp:~$ time curl -i https://script.ioamaaaaaaaaaaaaaaaaa.de/iam.js
curl: (6) Could not resolve host: script.ioamaaaaaaaaaaaaaaaaa.de
curl -i https://script.ioamaaaaaaaaaaaaaaaaa.de/iam.js  0.00s user 0.00s system 43% cpu 0.011 total
```

There are a few similar looking issues and a few related threads on reddit, but none of the posible solutions metioned there did anything to resolve this over here.

**(Optional) Debug token generated by `pihole -d`:**

`alwbfq5ikr`

**Comment by dschaper** [comment]
Are you running any other webservers or daemons that may be listening on port 443 on the Pi-hole server?

**Comment by dschaper** [comment]
And just to check, if you could run the same tests on the Pi-hole server as well. I get 
```
pi@raspberrypi:~ $ time curl -i https://script.ioam.de/iam.js
curl: (7) Failed to connect to script.ioam.de port 443: Connection refused

real	0m0.146s
user	0m0.090s
sys	0m0.040s
pi@raspberrypi:~ $ time curl -i https://script.ioaaaaaaam.de/iam.js
curl: (6) Could not resolve host: script.ioaaaaaaam.de

real	0m0.366s
user	0m0.070s
sys	0m0.030s
```

**Comment by matrixagent** [comment]
Hi there,

not that I'm aware of. It's a standard Ubuntu LTS 16.04 with nothing installed other than pihole (running a single VM instance just for pihole).

According to lsof there is nothing listening on 443 at all, just lighttpd on 80 as expected:

```
manu@pihole:~$ sudo lsof -i :443
manu@pihole:~$ sudo lsof -i :80
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 4859 www-data    5u  IPv4  27781      0t0  TCP *:http (LISTEN)
lighttpd 4859 www-data    6u  IPv6  27782      0t0  TCP *:http (LISTEN)
```

Running the curl requests directly on the pi is instant:

```
manu@pihole:~$ time curl -i https://script.ioam.de/iam.js
curl: (7) Failed to connect to script.ioam.de port 443: Connection refused

real	0m0.011s
user	0m0.000s
sys	0m0.004s
manu@pihole:~$ time curl -i https://script.ioamaaaaaaaaaaaaaaaaaa.de/iam.js
curl: (7) Failed to connect to script.ioamaaaaaaaaaaaaaaaaaa.de port 443: Connection refused

real	0m0.133s
user	0m0.000s
sys	0m0.008s
```

**Comment by dschaper** [comment]
Good, we know the Pi-hole is behaving as expected. I took a look at the debug logs and it does show NXDOMAIN for the `aaaaaaaaaaa` non-existent domain, and it returns the Pi-hole address for the valid domain. So the DNS redirection is working. Now we need to find out why the `https` is timing out instead of immediately returning when the connection is refused.

On the MBP, can you try curling `https://install.pi-hole.net` as we know that's a valid domain and will return something to you.

**Comment by matrixagent** [comment]
That works fine:
```
manu@mmbp:~$ time curl -v -I https://install.pi-hole.net
* Rebuilt URL to: https://install.pi-hole.net/
*   Trying 104.24.109.83...
* TCP_NODELAY set
* Connected to install.pi-hole.net (104.24.109.83) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: sni171690.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
> HEAD / HTTP/1.1
> Host: install.pi-hole.net
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Date: Thu, 23 Feb 2017 23:37:39 GMT
Date: Thu, 23 Feb 2017 23:37:39 GMT
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=d444853da75c578a8c74de2d5ac65b1fd1487893059; expires=Fri, 23-Feb-18 23:37:39 GMT; path=/; domain=.pi-hole.net; HttpOnly
Set-Cookie: __cfduid=d444853da75c578a8c74de2d5ac65b1fd1487893059; expires=Fri, 23-Feb-18 23:37:39 GMT; path=/; domain=.pi-hole.net; HttpOnly
< Cache-Control: max-age=3600
Cache-Control: max-age=3600
< Expires: Fri, 24 Feb 2017 00:37:39 GMT
Expires: Fri, 24 Feb 2017 00:37:39 GMT
< Location: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
Location: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
< Server: cloudflare-nginx
Server: cloudflare-nginx
< CF-RAY: 335e81c39f86236c-FRA
CF-RAY: 335e81c39f86236c-FRA

<
* Curl_http_done: called premature == 0
* Connection #0 to host install.pi-hole.net left intact
curl -v -I https://install.pi-hole.net  0.01s user 0.01s system 25% cpu 0.103 total
```

**Comment by dschaper** [comment]
Okay, next can you post up the verbose curl for the problem domain from the MBP. With the `-I -v` flags so we can see that path that it's taking and if there's an attempt at a certificate handshake or anything like that.

**Comment by matrixagent** [comment]
I tried making it as verbose as possible but it doesn't look very informative:
```
time curl -vvv -I https://script.ioam.de/iam.js
* Could not resolve host: script.ioam.de
* Closing connection 0
curl: (6) Could not resolve host: script.ioam.de
curl -vvv -I https://script.ioam.de/iam.js  0.00s user 0.00s system 0% cpu 30.591 total
```

**Comment by dschaper** [comment]
What does the `/etc/resolv.conf` have for it's contents on the Mac?

**Comment by matrixagent** [comment]
That would be
```
manu@mmbp:~$ cat /etc/resolv.conf
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
domain fritz.box
nameserver 192.168.2.1
```

**Comment by dschaper** [comment]
Ah, so the configuration is that your clients query the Fritz!box and that in turn is what is querying the Pi-hole. Does your router have the firmware that doesn't allow you to send the DNS IP address with the DHCP lease? There is a security feature that is called DNS rebind protection that will cause the routers to drop DNS packets from internal addresses as the router thinks they are an attempt to poison the DNS cache. @DL6ER do you have any thoughts on this one?

**Comment by matrixagent** [comment]
You're right, that really is a feature of the router. I've had a similar problem before with plex.tv and their magic internal/external routing. That was solvable by adding plex.tv to the whitelist of the DNS rebinding protection of my Fritz!box. Sadly, this whitelist is the only thing I can configure about it. It can't be disabled completely and I can't whitelist a source/origin. (If I understand everything correctly, I would need to add the script.ioam.de domain to that whitelist to resolve (ha!) the problem, but that would mean I'd have to add every troublesome domain which is not really a solution.)

**Comment by dschaper** [comment]
If you'd like to use the Pi-hole fully, you may want to look at the DHCP server that is bundled with the Pi-hole. You would just need to disable the DHCP server on the Fritz! and enable it via the web interface on the Pi-hole and then the DNS rebind problem should be resolved, as the clients would be querying the Pi directly instead of through the Fritz!box. (That's a big reason for the DHCP server on the Pi-hole, the firmware issues with routers like the Fritz.)

**Comment by DL6ER** [comment]
> You would just need to disable the DHCP server on the Fritz! and enable it via the web interface on the Pi-hole and then the DNS rebind problem should be resolved, as the clients would be querying the Pi directly instead of through the Fritz!box.

100% agreed

**Comment by matrixagent** [comment]
I tried avoiding to couple pihole and dhcp. Probably silly, but for some reason I'd like one of my physical devices to be the dhcp, not a vm. However, I'm not 100% understanding how that would solve the problem – as I understand it, the dns rebind protection works like this:

1. Macbook asks DNS (192.168.2.1) for IP of bad.domain
2. Fritzbox (192.168.2.1) asks the DNS I configured there, i.e. my pihole for the IP of bad.domain
3. pihole says it is 192.168.2.58 (the IP of my pihole)
4. Fritzbox notices that this IP is part of 192.168.2.1/8 and thus does not give a reply to my Macbook

Now when I switch the DHCP from my fritzbox to the pihole, the actual IPs/subnets involved would not change, so in step 4 the condition would still apply, wouldn't it?

I guess we could close this ticket and move the discussion to https://github.com/pi-hole/pi-hole/issues/292 where a few other Fritzbox users already are discussing solutions (which so far don't appear to be working for me, sadly).

**Comment by dschaper** [comment]
Basically you have the process correct for as it exists now. What changes is that the flow becomes this:

1. MB queries Pi-hole (192.168.2.58) for IP of bad.domain
2. Ph finds bad.domain in hosts file, returns 192.168.2.58
3. MB sends http(s) request through F!B as router to Ph.
4. F!B thinks you're just looking for a local webserver and lets traffic pass.

So by switching to querying the Pi-hole directly, the Fritz! never knows that the DNS query is local since it no longer is making the query itself, and if you had the updated firmware on the Fritz! that allowed you to send a DNS server along with the DHCP lease, then you'd be able to handle the DNS rebind attack the same way.

**Comment by matrixagent** [comment]
I just discovered the missing clue in the other thread – I wasn't aware that the DHCP also tells the clients which DNS to use. Now I just found out how to setup my Fritzbox to use the pihole in the DHCP response, and of course now it makes sense to me how using the pihole DHCP would also have solved the problem. Thanks a lot for all your help! :)

**Comment by andrewferrier** [comment]
For what it's worth I was suffering the same problem. This was primarily because the machine I was hosting pi-hole on was running ufw (the simple Ubuntu firewall), which was timing out 443 (HTTPS) packets, not rejecting them. Adding a ufw "REJECT" rule fixed the problem.
