### ISSUE TITLE
Disable temperature when not running on RasPi

### ISSUE THREAD

**Issue by karlo12** [pi-hole/pi-hole#1283]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

I think it might be useful to let the user disable the temperature count in the upper left corner of the web user interface. The temperature is not displayed correctly when running in a docker container in a different environment compared to directly running on a RasPi. The turn off switch could be implemented in the settings where the user can chose the measurement unit of the temperature count at the moment.

Thanks.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I'd like to get more info from you. We already disable the temp display if the operating system does not present a physical sensor (works e.g. in simple VirtualBox images). I have no experience with docker, but would like to understand why it mimics a physical temperature sensor and what value is shown to you.

**Comment by karlo12** [comment]
> I'd like to get more info from you. We already disable the temp display if the operating system does not present a physical sensor (works e.g. in simple VirtualBox images). I have no experience with docker, but would like to understand why it mimics a physical temperature sensor and what value is shown to you.

I'm sry, at a first glance I thought it was the temperature but it actually is the load value which seems to need some additional formatting. It says "Load:  1.47216796875  1.3720703125  1.31494140625". You cannot see most of that text because of an insufficient line break and it has a red instead of a green dot. I cannot add a screenshot via drag&drop here, for some reason. And Imgur is also down :cry: ... I can add a screenshot at a later time, if needed.

Anyways, this load value text does not look very well either, especially with the red dot.

**Comment by DL6ER** [comment]
Well, there is something fishy going on here.

Firstly: The load display should be standardized to show at most two digits (e.g. 0.96).

Secondly: Your VPS is overloaded! That is what the red dot wants to tell you. If you are seeing it with a load value of about 1.5, than that means that your machine has only one core. The load of such a machine should be less than one, otherwise it has too much work to do (for a single processor).

**Comment by karlo12** [comment]
It is alpine linux, using this docker image: https://hub.docker.com/r/diginc/pi-hole/ . The host got more than one core but docker probably only allocates one. So maybe I'll rather tell these devs about the problem, right?

**Comment by dschaper** [comment]
Alpine is the host, or you are using the Alpine based Docker image?

**Comment by karlo12** [comment]
The host is running Synology's DSM which is a customized linux. The Docker image is based on Alpine.

**Comment by dschaper** [comment]
Thanks, researching it now.

**Comment by dschaper** [comment]
https://github.com/pi-hole/AdminLTE/pull/419 Fixes the issue, will be up on the next release, and then when diginc updates his containers you should have the fixed code.

**Comment by karlo12** [comment]
Thank you.
