### ISSUE TITLE
Latest PiHole breaks dnsmasq on startup

### ISSUE THREAD

**Issue by rwpotter3rd** [pi-hole/pi-hole#1289]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[BUG | ISSUE] Expected Behaviour:**
The latest update to Pihole (2.13) breaks Pihole. Whenever the system is rebooted dnsmasq does not listen on the network interface for DNS requests.
**Possibly a replica of issue #1288 but I'm not running apache2 so I can't be sure.

**[BUG | ISSUE] Steps to reproduce:**

- Update existing Pihole install
- Reboot your Pi
- Attempt to dig your Pi at its IP address
OR
- Get a fresh Raspbian install
- Install Pihole
- Reboot Pi
- Attempt to dig your Pi at its IP address

Using "pihole restartdns" or "systemctl restart dnsmasq" fixes the issue until the Pi is rebooted again.

The below screencap is for a Pihole install on a fresh Raspbian image. Nothing much has been done with it except for installing Pihole for testing. Similar results can be seen if you use dig on the Pihole device itself but specify its eth0 IP address instead of letting it use 127.0.0.1. 
![capture](https://cloud.githubusercontent.com/assets/26172123/23567738/f8729322-0014-11e7-8be8-6e6eaf1d5234.png)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Can you provide the log before/after the manual restart of `dnsmasq`?

`/var/log/pihole.log`

**Comment by DL6ER** [comment]
Can you try to change the listening behavior to this setting?

![screenshot at 2017-03-03 21-38-45](https://cloud.githubusercontent.com/assets/16748619/23568254/fd649e9e-0059-11e7-8749-8c64657b5688.png)

**Comment by rwpotter3rd** [comment]
I flushed the log and rebooted. Tried to dig. It failed. Then I printed the pihole.log
[before.txt](https://github.com/pi-hole/pi-hole/files/817871/before.txt)
Next, I restarted dnsmasq. Tried to dig again. Success. Then I printed the pihole.log
[after.txt](https://github.com/pi-hole/pi-hole/files/817870/after.txt)

And do you want me to change that option before or after a dnsmasq reboot?

**Comment by DL6ER** [comment]
Just change it and look if the problem goes away entirely.

**Comment by DL6ER** [comment]
Another question came to my mind: Have you actually configured a static IP or do you still use DHCP and have taken care that the Pi is getting the very same IP again and again?

**Comment by rwpotter3rd** [comment]
Changing the option to listen on all fixes the issue. And it's a static IP address.

**Comment by DL6ER** [comment]
Thanks, that is what I though.

> And it's a static IP address.

Have you configured it yourself or have you used the Pi-hole installer to configure it for you?

**Comment by rwpotter3rd** [comment]
I've tried both. I have a pihole running on my network in a typical setup, the static IP was set with the raspbian network preferences menu, and it worked fine until I updated it to 2.13.
I've also tried a fresh raspbian install that the pihole installer set the static IP.

**Comment by codebucketdev** [comment]
+1 can only confirm this issue. 

But I noticed that the installer does not add `interface=eth0` to /etc/dnsmasq.d/01-pihole.conf which is causing dnsmasq not listening to DNS requests coming from my lan network.

**Comment by DL6ER** [comment]
The Bugfix is already on its way :-)
https://github.com/pi-hole/pi-hole/pull/1291

**Comment by dschaper** [comment]
We're working on a fix now. There is a bug in the Debian Jessie version of `dnsmasq` that isn't in the most recent release of that package.

**Comment by jacobsalmela** [comment]
Bugfix inbound

**Comment by codebucketdev** [comment]
Nice to see this bug being fixed right now, so I guess I can run the installer in 5 minutes and it will be fixed, right? :)

**Comment by DL6ER** [comment]
> Nice to see this bug being fixed right now, so I guess I can run the installer in 5 minutes and it will be fixed, right? :)

Yes, run `pihole -up`

**Comment by codebucketdev** [comment]
Thank you very much! Now it's working fine :smile:

**Comment by divadsn** [comment]
Show log of `/var/log/pihole.log` output please, there is nothing see in your status output.

**Comment by PromoFaux** [comment]
Come on now... This thread is over a year old! Unlikely to be the same issue. Please open a new issue thread and follow the template.
