### ISSUE TITLE
Spotify in offline mode on iOS

### ISSUE THREAD

**Issue by JamborJan** [pi-hole/pi-hole#1290]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
Spotify on iOS should not be in offline mode when using pi-hole.

**[BUG | ISSUE] Actual Behaviour:**
Spotify on iOS is in offline mode when using pi-hole.

**[BUG | ISSUE] Steps to reproduce:**
- Use Spotify (latest update) on an iPhone (latest iOS) in LAN with latest Pi-Hole (Pi-hole Version v2.13 Web Interface Version v2.5)
- Spotify will be in Offline Mode
- In Pi-Hole you see only one line Status OK line, nothing blocked:
![img_2968](https://cloud.githubusercontent.com/assets/7508960/23495216/b1cb39cc-ff17-11e6-8ced-9ec6d3dde366.PNG)
- I can reproduce that issue with any iPhone running Spotify
- I don't know if it is related to Spotify Premium which I'm using or not
- On Laptops with latest macOS the Spotify app and the web player is working as expected

**(Optional) Debug token generated by `pihole -d`:**

`thell4rj2x`

**Comment by technicalpyro** [comment]
the following shows when i attempt to use spotify
```
Mar  3 15:18:34 dnsmasq[3196]: query[A] secure-us.imrworldwide.com from 172.16.1.104
Mar  3 15:18:34 dnsmasq[3196]: /etc/pihole/gravity.list secure-us.imrworldwide.com is 172.16.1.102
```
Whitelist `secure-us.imrworldwide.com`

**Comment by jacobsalmela** [comment]
That should be fine.  

Just to be sure, did [add this to your whitelist](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212#spotify)?
```
pihole -w spclient.wg.spotify.com
```

**Comment by JamborJan** [comment]
Whoops. Sorry, didn't find the whitelist tips before. It does work of course. Sorry!
