### ISSUE TITLE
[TYPO] Commandline pihole -wild

### ISSUE THREAD

**Issue by fmjensen** [pi-hole/pi-hole#1304]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[BUG] Expected Behaviour:**
 ```pihole -wild -l``` show usage syntax for the option

**[BUG | ISSUE] Actual Behaviour:**
```::: Usage: pihole -b domain1 [domain2 ...]``` where ```-b``` should have been ```-wild```

**[BUG] Steps to reproduce:**

use the CLI command ```pihole -wild``` on system that was installed without the admin web interface.

**Comment by dschaper** [comment]
I'm not sure I understand, `pihole -wild -l` isn't a valid command. It's `pihole -w` to whitelist single, `pihole -b` to blacklist single and `pihole -wild` to blacklist wildcard.

**Comment by fmjensen** [comment]
```
me@rpiii:~ $ pihole -wild
::: Immediately blacklists one or more domains in the hosts file
:::
::: Usage: pihole -b domain1 [domain2 ...]
:::
::: Options:
:::  -d, --delmode            Remove domains from the blacklist
:::  -nr, --noreload          Update blacklist without refreshing dnsmasq
:::  -q, --quiet              Output is less verbose
:::  -h, --help               Show this help dialog
:::  -l, --list               Display your blacklisted domains
:::  -wild, --wildcard        Add wildcard entry (only blacklist)
```
This is what i get, and i did not expect the ```-b``` in the usage: line... ?!
```pihole -wild -l``` seems to be valid acording to the help that is displayed.
I guess that some cut'n paste error in the help text might have happned - or have i misunderstood something?

**Comment by dschaper** [comment]
We'll check on that and see what the proper display should be, but it shouldn't display that `-b`.

**Comment by r0ckarong** [comment]
It was in fact a bug in the list script. It wouldn't recognize the -wild parameter passed correctly and assume -b was passed. I created a PR to fix this.

**Comment by WaLLy3K** [comment]
As per #1317:

```
pihole -wild -h
Usage: pihole -wild [options] <domain> <domain2 ...>
Example: 'pihole -wild site.com', or 'pihole -wild site1.com site2.com'
Wildcard blacklist one or more domains

Options:
  -d, --delmode       Remove domain(s) from the wildcard blacklist
  -nr, --noreload     Update wildcard blacklist without refreshing dnsmasq
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your wildcard blacklisted domains
```

Thanks for pointing the issue out @fmjensen, and thanks to @r0ckarong for submitting a fix.

**Comment by jacobsalmela** [comment]
@WaLLy3K can we close this since it #1317 seems to have resolved it?
