### ISSUE TITLE
[BUG] Commandline pihole -c does not calculate on system w/o web interface.

### ISSUE THREAD

**Issue by fmjensen** [pi-hole/pi-hole#1305]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[BUG] Expected Behaviour:**
 ```pihole -c``` Calculates stats and displays to an LCD (or terminal ??)

**[BUG | ISSUE] Actual Behaviour:**
```
 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        0.0.0.0

 load average: 0,02, 0,07, 0,08
2 days, 8 hours, 58 minutes.
-------------------------------
Blocking:      0
Queries:       0
Pi-holed:      0 (0.00%)
^C
me@rpiii:~ wc -l /var/log/pihole.log
9524 /var/log/pihole.log
me@rpiii:~ $ cat /var/log/pihole.log |grep 0.0.0.0 |tail
Mar  6 19:08:35 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:08:37 dnsmasq[14520]: /etc/pihole/gravity.list www.google-analytics.com is 0.0.0.0
Mar  6 19:11:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:16:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list www.google-analytics.com is 0.0.0.0
Mar  6 19:17:27 dnsmasq[14520]: /etc/pihole/gravity.list www-google-analytics.l.google.com is 0.0.0.0
Mar  6 19:19:48 dnsmasq[14520]: /etc/pihole/gravity.list collector.githubapp.com is 0.0.0.0
Mar  6 19:21:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
Mar  6 19:26:12 dnsmasq[14520]: /etc/pihole/gravity.list livepassdl.conviva.com is 0.0.0.0
me@rpiii:~ $
```
I guess there will be no calculations without the _api.php_ as is the case on a system where the webinterface was **not** installed.
This might change when FTL goes live ??

**[BUG] Steps to reproduce:**

use the CLI command ```pihole -c``` on system that was installed without the admin web interface.

**Comment by PromoFaux** [comment]
Ah yes, good catch! (Sorry, chronometer usually falls behind somewhere!)

Yeah, we recently changed chronometer to be dependent on the web API for its stats, though I imagine FTL will change that.
