### ISSUE TITLE
pihole --up command returns help page

### ISSUE THREAD

**Issue by blue-smoke** [pi-hole/pi-hole#1314]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:01

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:
(Using  pi-hole 2.12.1 )

pihole --up command should update pi-hole to latest release.

**[BUG | ISSUE] Actual Behaviour:

pihole --up command returns a short help summary that, amongst other things, informs me that pihole --up is the command to update pi-hole.

**[BUG | ISSUE] Steps to reproduce:

Open terminal on pi-hole Raspberry pi
Type pihole --up

Additional - if this command has been removed, I cannot discover the correct way to update Pi-hole.  

$ pihole -v
::: Pi-hole version is v2.12.1 (Latest version is v2.13.1)
::: Web-Admin version is v2.4 (Latest version is v2.5.1)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
The command to use would be `pihole -up`. Just one `-`

**Comment by blue-smoke** [comment]
I am an absolute idiot, I'm so sorry!
