### ISSUE TITLE
Feature Request Internal DNS resolution 

### ISSUE THREAD

**Issue by bizit524** [pi-hole/pi-hole#1316]
Hello, 
Great project. 
I have a feature request that I think many will find potentially useful. 
On my current router I am able to setup internal DNS names to my local servers. For example 192.168.0.245 is a webserver I have and in my browser I can type webserver.local and the DNS resolves it to the 192.168.0.245. However Since using pihole I can't do that as if I offload the DNS funtion of my router to the pihole it disables ALL resolution on my router making the table I have obsolete. 

I have found this article that helps me resetup my internal DNS resolution to webserver.local 
https://paranoidix.dk/2016/05/08/dnsmasq-and-pi-hole/
This works and it is currently using DNSmasq which is the same as this program. 
I was thinking you could integrate this pretty much into the interface have a section either in the main list on the left or it could be listed under "tools" as well. 
Where you could have a box for DNS and a box for the ip it resolves to. It would have an apply button as well. 

keep up the good work. If I can be of a service i can try to help. I could create a mock up maybe of how I think it should work/look. Let me know

**Comment by dschaper** [comment]
Hi, the template that we ask you to fill out with issues notes that Feature Requests should be posted over at https://discourse.pi-hole.net. This is so that users can vote on them and rank the priority of the features that we add to the Pi-hole as time and talent permits.

Thanks!

**Comment by bizit524** [comment]
oh very sorry about that, I was trying to understand that bug report. I was just comparing it to another feature request down below mine. I can delete this if you want and then change it over to there :)

**Comment by dschaper** [comment]
Thanks! Discourse just lets us track the features a little easier so they don't get lost in the mix of bug reports and support request.
