### ISSUE TITLE
Error while updating to v2.13.1

### ISSUE THREAD

**Issue by SeriousM** [pi-hole/pi-hole#1318]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG | ISSUE] Expected Behaviour:**
The update/reconfiguration should end as expected and pihole should log the requests.

**[BUG | ISSUE] Actual Behaviour:**
Pihole throws the error `/opt/pihole/gravity.sh: line 426: pihole: command not found` during update/setup. This leads to a missing log and therefor, no web display of requests.
Pihole is still doing it's job. The strange thing is, that when I do a debug run, I get some information in the graphs and log tail, but not otherwise.

Thats the information during debug run:
```
Mar 12 20:45:46 dnsmasq[949]: query[A] doubleclick.com from 127.0.0.1
Mar 12 20:45:46 dnsmasq[949]: /etc/pihole/gravity.list doubleclick.com is 192.168.4.209
```

**[BUG | ISSUE] Steps to reproduce:**
Just run `curl -sSL https://install.pi-hole.net | bash` with the option update or reconfiguration.

Output:
```
root@lxc-pihole:~# curl -sSL https://install.pi-hole.net | bash
:::
::: You are root.
::: Reconfigure option selected
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Kernel update detected, please reboot your system and try again if your installation fails.
:::    Checking for apt-utils... installed!
:::    Checking for debconf... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for git... installed!
:::    Checking for iproute2... installed!
:::    Checking for whiptail... installed!
:::
::: Stopping dnsmasq service... done.
:::
::: Stopping lighttpd service... done.
::: Static IP already configured
::: IPv4 address: 192.168.4.209/24
::: IPv6 address:
::: Web Interface On.
::: Logging On.
:::
::: Checking for existing repository...
:::    Updating repo in /etc/.pihole... done!
 done!
:::
::: Checking for existing repository...
:::    Updating repo in /var/www/html/admin... done!
 done!
:::    Checking for bc... installed!
:::    Checking for cron... installed!
:::    Checking for curl... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for dnsutils... installed!
:::    Checking for iputils-ping... installed!
:::    Checking for lsof... installed!
:::    Checking for netcat... installed!
:::    Checking for sudo... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::    Checking for lighttpd... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
::: Checking if user 'pihole' exists...
::: User 'pihole' already exists
:::
::: Installing scripts from /etc/.pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page...
:::     Existing index.php detected, not overwriting
:::     Existing index.js detected, not overwriting
:::     Existing blockingpage.css detected, not overwriting
:::
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
:::
::: Installing latest logrotate script... done!
:::
::: No active firewall detected.. skipping firewall configuration.
::: Restarting services...
:::
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting sysctl.org list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting zeustracker.abuse.ch list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting s3.amazonaws.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting s3.amazonaws.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting hosts-file.net list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 127683 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 104358 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
/opt/pihole/gravity.sh: line 269: pihole: command not found
::: Whitelisting 6 domains... done!
::: Nothing to blacklist!
::: No wildcards used!
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq.../opt/pihole/gravity.sh: line 388: pihole: command not found
 done!
/opt/pihole/gravity.sh: line 426: pihole: command not found
```

**(Optional) Debug token generated by `pihole -d`:**

`ukho8vwlcn`

**Comment by DL6ER** [comment]
Thank you for reporting this. I see that you are running `Debian Jessie` (not on a Raspberry). Is there anything special about the image you are using (like an image that is provided by a third party like a VPS provider) or is it a stock image?

**Comment by SeriousM** [comment]
No, not really. I'm using in in turris as lxc container app. The image is unmodified as far as I know.

**Comment by technicalpyro** [comment]
this may be related i just came across this error when on my VPS
```
root@technicalpyro:~# pihole
/usr/local/bin/pihole: line 289: -a: command not found
```

**Comment by DL6ER** [comment]
That should (obviously) *not* happen and it is the first time we hear about that.

Please tell us what the following commands tell you:
```
ls -lh /usr/local/pihole

echo $PATH

sudo -s
echo $PATH
exit
```

**Comment by SeriousM** [comment]
```
$ lxc-attach -n pihole
root@lxc-pihole:~# ls -lh /usr/local/pihole
ls: cannot access /usr/local/pihole: No such file or directory
root@lxc-pihole:~# echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin
root@lxc-pihole:~# sudo -s
sudo: /bin/zsh: command not found
root@lxc-pihole:~#
```
sudo does not work because of the nature of the container - there is no other user than root.

did that help you in any way?

**Comment by technicalpyro** [comment]
I believe your issue is sorted out by the pull request above.  I thought my issue was similar however it is not and I will be making a separate issue for it when I get home and can run the requested commands as well

**Comment by DL6ER** [comment]
> did that help you in any way?

Yes, `/usr/local/bin` is not part of your `PATH` variable. That is not really expected, but should be solved if you run

```
PATH=$PATH:/usr/local/bin
export PATH
```
before running the installer script.

**However**, from what I see in your original message, I think your installation actually went fine like 98% and the only missing bit would be to run
```
PATH=$PATH:/usr/local/bin
export PATH
pihole -g
``

Let me know how that's behaving.

**Comment by SeriousM** [comment]
That's interesting, but I wonder why the installation was working with a
previous version of pi-hole? The environment didn't changed since then.

Am 14.03.2017 12:00 vorm. schrieb "DL6ER" <notifications@github.com>:

**Comment by DL6ER** [comment]
Hmm, I cannot tell. According to `git blame` this has not changed in more than half of a year. Have you been updating from an even older version?

**Comment by SeriousM** [comment]
> Yes, /usr/local/bin is not part of your PATH variable. That is not really expected, but should be solved if you run
> 
> PATH=$PATH:/usr/local/bin
> export PATH

That worked like a charm and the installation went fine!

> Hmm, I cannot tell. According to git blame this has not changed in more than half of a year. Have you been updating from an even older version?

Nope, the previous installation is at most 3 months old.

Now that the installation works fine again, I don't get any queries logged , but pihole is still working as it should. Is there anything I can do about that?

**Comment by Mcat12** [comment]
Check if the log exists and the web interface can access it: `/var/log/pihole.log`

**Comment by SeriousM** [comment]
The log file exists, but it just contains a few lines

```log
Mar 16 20:43:38 dnsmasq[11241]: started, version 2.72 cachesize 10000
Mar 16 20:43:38 dnsmasq[11241]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
Mar 16 20:43:38 dnsmasq[11241]: using nameserver 212.186.211.21#53
Mar 16 20:43:38 dnsmasq[11241]: using nameserver 195.34.133.21#53
Mar 16 20:43:38 dnsmasq[11241]: read /etc/hosts - 4 addresses
Mar 16 20:43:38 dnsmasq[11241]: read /etc/pihole/local.list - 2 addresses
Mar 16 20:43:39 dnsmasq[11241]: read /etc/pihole/gravity.list - 104418 addresses
```

pihole was able to create the file and its configured to log with `pihole -l 'on'`. Anyway, using `pihole -t` or `tail -f /var/log/pihole.log` just don't show queries.

**Comment by Mcat12** [comment]
Are you sure that the Pi-hole is getting queried? Run `pihole -d` for a debug token.

**Comment by SeriousM** [comment]
> Are you sure that the Pi-hole is getting queried?

you don't know how I'm ashamed... the last turris update changed something in dns forwarding and now I was forced to update multiple settings to get pihole queried again.
now it works as expected, aaaaand I have a flashing red light on my turris whenever pihole is catching something!

here is a link to the setup as reference for the other users with the same issue: http://www.nickbusey.com/installing-and-configuring-network-wide-adblock-with-pi-hole-and-the-turris-omnia/

Thank you all for the help!
