### ISSUE TITLE
cannot start dnsmasq, CentOS7

### ISSUE THREAD

**Issue by Mukrosz** [pi-hole/pi-hole#1321]
Hello!

CentOS7 7.3.1661
Pi-hole Version v2.13.1 Web Interface Version v2.5.1

I've been running Pihole for a long time without many issues.
Today after a yum update , dnsmasq fails to start and so pihole does not work:(

```
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-03-13 13:38:56 MDT; 25s ago
 Main PID: 2654 (code=exited, status=1/FAILURE)

Mar 13 13:38:56 sever systemd[1]: Started DNS caching server..
Mar 13 13:38:56 server systemd[1]: Starting DNS caching server....
Mar 13 13:38:56 server dnsmasq[2654]: dnsmasq: bad option at line 44 of /etc/dnsmasq.d/01-pihole.conf
Mar 13 13:38:56 server systemd[1]: dnsmasq.service: main process exited, code=exited, status=1/FAILURE
Mar 13 13:38:56 server systemd[1]: Unit dnsmasq.service entered failed state.
Mar 13 13:38:56 server systemd[1]: dnsmasq.service failed.
```

content of 01-pihole.conf:

```
...
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list
no-resolv
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async
server=xxx.xxx.xxx.xxx
server=xxx.xxx.xxx.xxx
domain-needed
bogus-priv
local-service   <----- line 44
```

any ideas?

**Comment by dschaper** [comment]
Are you able to run `pihole -d` and get us a debug log token? We need to check out the version of `dnsmasq` being run along with a couple of other daemons just to see if CentOS has a version that contains that portion of the code that understands the directive. Thanks.

**Comment by Mukrosz** [comment]
thanks for your response.
After troubleshooting further, i decided to revert my pihole VM to a version before yum updates and whatever other changes i made happened.

here i what 01-pihole.conf has in place:

```
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list
domain-needed
bogus-priv
no-resolv
server=xxx.xxx.xxx.xxx
server=xxx.xxx.xxx.xxx
interface=eno16777976
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async
```


As i now recall, yum update initially failed because for some reason ifcfg-eno network file lost dns settings. I deleted that file and replaced with the backup pihole creates. I then decided to add a 3rd DNS server via pihole GUI which instead replaced DNS2. So, this combination of things affected dnsmasq (v2.66) after reboot?

Anyways, after reverting VM to yesterday snapshot, I was able to yum update and reboot and dnsmasq is still working.

might have something to do with selinux being turned on also haha

Sorry for the wall of text

**Comment by tonglil** [comment]
I also have this problem.

I am on Ubuntu 14.04.
The debug token is: 0q5azi6kn6.

```
root@scw-4caeed:/etc/.pihole# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
NAME="Ubuntu"
VERSION="14.04, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

```
root@scw-4caeed:/etc/.pihole# /etc/.pihole/pihole restartdns
 * Restarting DNS forwarder and DHCP server configuration syntax check                       [fail] 
```

```
root@scw-4caeed:/etc/.pihole# tail -f /var/log/syslog
Mar 15 04:35:39 scw-4caeed dnsmasq[4281]: bad option at line 45 of /etc/dnsmasq.d/01-pihole.conf
Mar 15 04:35:39 scw-4caeed dnsmasq[4281]: FAILED to start up
Mar 15 04:35:47 scw-4caeed dnsmasq[4344]: bad option at line 45 of /etc/dnsmasq.d/01-pihole.conf
Mar 15 04:35:47 scw-4caeed dnsmasq[4344]: FAILED to start up
```

This is the only dnsmasq config file in /etc/dnsmasq.d
```
root@scw-4caeed:/etc/dnsmasq.d# cat 01-pihole.conf 
# Pi-hole: A black hole for Internet advertisements
# (c) 2015, 2016 by Jacob Salmela
# Network-wide ad blocking via your Raspberry Pi
# http://pi-hole.net
# dnsmasq config for Pi-hole
#
# Pi-hole is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPERATE CONFIG FILE           #
#                        OR IN /etc/dnsmasq.conf                              #
###############################################################################

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list



no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=300

log-async
server=8.8.8.8
server=8.8.4.4
server=208.67.220.220
domain-needed
bogus-priv
local-service
```

**Comment by dschaper** [comment]
If this is still an issue, can you run a new debug and get us the token please?

**Comment by tonglil** [comment]
Sure, here it is (same config as above^): ihirzz9tbb

**Comment by dschaper** [comment]
There seems to be some activity from dnsmasq, `/var/log/pihole.log` shows that it was answering queries when you browsed during the log gathering. Are you able to run `pihole -t` to see a real time view of the `dnsmasq` logging?

**Comment by tonglil** [comment]
The activity is likely from when I had pihole running w/ the adjustment to `/etc/dnsmasq.d/01-pihole.conf`. I removed the last line, `local-service`.

**Comment by dschaper** [comment]
That config `local-service` should be removed and not added back in future updates. There did seem to be an addressing conflict, however you may be aware of that already.

```
Gravity configured for: 163.172.137.xxx
----
10.1.18.151/23 <- Actual IP assigned to the interface
```

That may lead to some increased latency if the 163 address doesn't forward correctly.

**Comment by tonglil** [comment]
I see, thanks @dschaper . The first time I installed it I set it to the IP of the interface but it didn't work. I can try again in the future.

Do you know when the new config will be rolled out (and this issue can be closed)?

**Comment by dschaper** [comment]
Following up here, the issue should already be solved in the master branch, there was a period of a day or two where that flag was set. That flag is no longer set, but those affected by the bug need to manually remove the directive and then all should be well.

**Comment by tonglil** [comment]
Thanks!

**Comment by e-m-m-a** [comment]
this issue with local-service is still there in a clean install today
