### ISSUE TITLE
PiHole Log not Flushing at midnight

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#1326]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
4
_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
log should flust at midnight

**[BUG | ISSUE] Actual Behaviour:**
log not flushing, yesterday at noon i looked at it, it was 50+mb, pihole was very slow, flushed it manually, and today at 8am mst, it's 20+mb

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please generate a debug log for us to review.

**Comment by C4Wiz** [comment]
qslsg7tynv

**Comment by luckyheiko** [comment]
I also have a problem with the flush
pi@raspberrypi:/opt/pihole $ sudo pihole -f
::: Flushing /var/log/pihole.log ...error: error stat()ing state file /var/lib/logrotate/status: Not a directory
... done!

is a Raspberry 
pi@raspberrypi:/opt/pihole $ cat /proc/version
Linux version 4.4.11+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #888 Mon May 23 20:02:58 BST 2016

**Comment by C4Wiz** [comment]
just wanted to say, this issue has fixed itself! log flushed lastnight

**Comment by C4Wiz** [comment]
all i did was reboot the pi

**Comment by dschaper** [comment]
Let us know if there's any other problems, of if the issue returns.
