### ISSUE TITLE
Pihole displaying wrong / outdated IPv6 in admin panel

### ISSUE THREAD

**Issue by H4ndl3** [pi-hole/pi-hole#1329]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 1

---

**[BUG | ISSUE] Expected Behaviour:** Current IPv6 address is shown

**[BUG | ISSUE] Actual Behaviour:** Old IPv6 address is shown

**[BUG | ISSUE] Steps to reproduce:** Setup Pihole with an IPv6 address and change it later

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
The address that is shown is the one that is stored in Pi-hole's config file. You should rerun `pihole -r` + Repair if your address changes. There is a number of places where this IP has to be correct.

**Comment by H4ndl3** [comment]
Thanks for your fast reply, I didn't know that.

**Comment by zocker-160** [comment]
@DL6ER 
I have exactly the same issue, but `pihole -r` + repair does not solve the issue.

![Screenshot_20190926_222753](https://user-images.githubusercontent.com/36563538/65723573-f8866780-e0ae-11e9-909b-8cad31096fc5.png)

**Comment by DL6ER** [comment]
@zocker-160 This issue is over two years old. Much has changed in the internals of Pi-hole since then and when you are not using `IP` blocking mode (which is not the default), then the mismatching IPv6 address has no consequences for you.

The dashboard simply shows whatever address it reads from `/etc/pihole/setupVars.conf`.
