### ISSUE TITLE
[Dev Branch] Pi-hole teleporter error

### ISSUE THREAD

**Issue by Nevexo** [pi-hole/pi-hole#1337]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_4_

---

**[BUG | ISSUE] Expected Behaviour:**
A zip file should be sent to the client.

**[BUG | ISSUE] Actual Behaviour:**
A new tab opens with the text 'No file transmitted or parameter error.' (http://af/admin/scripts/pi-hole/php/teleporter.php)

**[BUG | ISSUE] Steps to reproduce:**

- Login to web interface
- Go to settings
- Try to download the Pi-hole teleporter zip.

**(Optional) Debug token generated by `pihole -d`:**

Incase it's just my device causing this issue: fdoohvs105

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Nevexo** [comment]
Found a way to fix it: Reload teleporter.php. But the button on the web interface doesn't work.

**Comment by PromoFaux** [comment]
@DL6ER This was fixed in dev, right?

**Comment by PromoFaux** [comment]
Ah no, only in `master` https://github.com/pi-hole/AdminLTE/commit/222343a3476a8994be07d3aba813a002d811fe8f

Looks like we need to sync it back

**Comment by DL6ER** [comment]
> Looks like we need to sync it back

Yes

**Comment by PromoFaux** [comment]
Fixed in pi-hole/AdminLTE#447
