### ISSUE TITLE
[feature request] "Top domain" filtering based on substring or regexp

### ISSUE THREAD

**Issue by IvanKuchin** [pi-hole/pi-hole#1342]
Hi team, 

   In my PI.hole I'm getting "Top queried domains" mostly technology domains .
(for example:
dmm-aln-004-p.cisco.com
dmm-aln-003-p.cisco.com
dmm-aln-002-p.cisco.com
dmm-aln-005-p.cisco.com
dmm-aln-007-p.cisco.com
dmm-aln-006-p.cisco.com
dmm-aln-001-p.cisco.com
dmm-aln-008-p.cisco.com
dmp-pri-001-p.cisco.com)
   Because of the filtering implemented on exact match I can't filter all domains from akamai.com, appimg.com etc......
   I'd like to get information about what domains used by my Human-clients, therefore I want to filter all technologies-domains with one line like "p.cisco.com"
   Here is implementation of regex-filtering:

    function excludeFromList(&$array,$key)
    {
        global $setupVars;
        $domains = explode(",",$setupVars[$key]);
        foreach ($domains as $domain) {
      //            if(isset($array[$domain]))
      //            {
      //                unset($array[$domain]);
      //            }
	    foreach($array as $requestedDomain => $wertyudcmskmcsldcmsdsdcsdc)
	    {
		if(preg_match("/".$domain."/i", $requestedDomain))
		{
		    unset($array[$requestedDomain]);
		}
	    }
        }
        return $array;
    }

**Comment by PromoFaux** [comment]
>Please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when submitting a new issue. It's there to help us to help you!

There's a section on Feature Requests there ;)

>**[FEATURE REQUEST | QUESTION | OTHER]:**

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

Not a bad idea, just the wrong place :)

Though, if you have this set up and working on your own pi-hole installation, have you considered submitting a pull request?

**Comment by IvanKuchin** [comment]
Thank you for clarification
