### ISSUE TITLE
Admin Interface doesn't load with http://pi-hole/admin but with ip/admin

### ISSUE THREAD

**Issue by LimitlessWorkaround** [pi-hole/pi-hole#1344]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
When I go to https://pi.hole/admin, there should be an Interface

**[BUG | ISSUE] Actual Behaviour:**
When I go to https://pi.hole/admin it (Firefox) says Error: Server not found
When I go to 192.168.2.182 (IP of my Raspberry Pi 3) there is the Interface

**[BUG | ISSUE] Steps to reproduce:**
-Install Pi-Hole on Raspbian (Jessie)
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`lt0cy8dfr1`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
>http://pi-hole/admin

Therein lies your problem!

You should be going to `https://pi.hole/admin` :)

**Comment by LimitlessWorkaround** [comment]
@PromoFaux Sorry I mean https (I thought it was http because I always used a bookmark)

**Comment by PromoFaux** [comment]
Sorry, not sure why i put `https` in there. The important difference between the link I wrote, and the one you wrote is `.` instead of `-` :wink:

**Comment by PromoFaux** [comment]
`http://pi.hole/admin != http://pi-hole/admin`

**Comment by LimitlessWorkaround** [comment]
Oh further mistake from me, yeah my bookmark says `.`, too
I corrected that too

**Comment by PromoFaux** [comment]
OK, from your PC can you run the following commands:

`nslookup pi.hole`
`nslookup doubleclick.net`

Is it a windows device? If so `ipconfig /all`

lastly please run a debug log on the pi itself with the command `pihole -d`, upload the log and provide the token. Thanks!

**Comment by LimitlessWorkaround** [comment]
´nslookup pi.hole´
Server:  UnKnown
Address:  fe80::1

*** pi.hole wurde von UnKnown nicht gefunden: Non-existent domain.

´nslookup doublecklick.net´

Server:  UnKnown
Address:  fe80::1

Nicht autorisierende Antwort:
Name:    doubleclick.net
Addresses:  2a00:1450:4001:81b::200e
          172.217.22.46

´ipconfig /all´

Windows-IP-Konfiguration

   Hostname  . . . . . . . . . . . . : DESKTOP-M63B4P7
   Primäres DNS-Suffix . . . . . . . :
   Knotentyp . . . . . . . . . . . . : Hybrid
   IP-Routing aktiviert  . . . . . . : Nein
   WINS-Proxy aktiviert  . . . . . . : Nein
   DNS-Suffixsuchliste . . . . . . . : Speedport_W_723V_1_43_000

Ethernet-Adapter Ethernet:

   Verbindungsspezifisches DNS-Suffix: Speedport_W_723V_1_43_000
   Beschreibung. . . . . . . . . . . : Intel(R) Ethernet Connection (2) I219-V
   Physische Adresse . . . . . . . . : 4C-CC-6A-05-5B-2B
   DHCP aktiviert. . . . . . . . . . : Ja
   Autokonfiguration aktiviert . . . : Ja
   Verbindungslokale IPv6-Adresse  . : fe80::8067:a38e:16f7:b15c%6(Bevorzugt)
   IPv4-Adresse  . . . . . . . . . . : 192.168.2.113(Bevorzugt)
   Subnetzmaske  . . . . . . . . . . : 255.255.255.0
   Lease erhalten. . . . . . . . . . : Montag, 20. März 2017 17:12:22
   Lease läuft ab. . . . . . . . . . : Montag, 10. April 2017 17:12:22
   Standardgateway . . . . . . . . . : 192.168.2.1
   DHCP-Server . . . . . . . . . . . : 192.168.2.1
   DHCPv6-IAID . . . . . . . . . . . : 55364714
   DHCPv6-Client-DUID. . . . . . . . : 00-01-00-01-20-4B-49-A0-4C-CC-6A-05-5B-2B
   DNS-Server  . . . . . . . . . . . : fe80::1%6
                                       192.168.2.182
   NetBIOS über TCP/IP . . . . . . . : Aktiviert

I think it isn't a problem for you if it is german 😉

**Comment by darkrain-nl** [comment]
Your device is using IPv6 for name resolution. The DNS server address for IPv6 is fe80::1 which is probably your router. Your router then forwards the lookup to the DNS configured in the router (probably internet DNS servers).

That's the reason why pi.hole is not found, it is not available on the internet (which is a good thing b.t.w.).

I think you can fix this problem by switching off IPv6 on your router. fe80 addresses are not routed across the internet, and it seems there is no other IPv6 connectivity. Probably your ISP does not support IPv6.

Another solution can be to turn off IPv6 on the Windows device, but then you may have problems on other devices...

**Comment by PromoFaux** [comment]
>I think it isn't a problem for you if it is in german 
For the most part, that is fine! Although we can always call on @DL6ER to intervene as a native German speaker if it gets too much!

Could you also upload a debug log so that we can take a closer look at your pi-hole config?

I'm not sure how much help I'll be when it comes to troubleshooting IPv6, however, as that's something I am yet to read up on! 

http://ipv6-test.com/ will tell you if it is supported on your ISP, or not.

**Comment by LimitlessWorkaround** [comment]
Here is the debug file.

IPv6 is not supported.
[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/858833/pihole_debug.txt)

**Comment by LimitlessWorkaround** [comment]
@darkrain-nl That's strange, the first days after setup went fine but now it doesn't. I never changed the settings but blacklist, whitelist...

**Comment by darkrain-nl** [comment]
I don't think it has to do with settings in PiHole. I must be something on either the router or the Windows pc. Your Windows pc is for sure using IPv6, maybe you can change the DNS server address for IPv6 on your network adapter in Windows? Just to see if that helps.

**Comment by dschaper** [comment]
We've been playing with ULA's instead of either LinkLocal or GUA addressing. https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127

**Comment by DavidGitta** [comment]
Have you fixed it?
I think this doesn't apply to you because your log tells, that you connect to the pi-hole dns directly from your windows machine. But if you set up pi-hole as dns server for your router, you should check DNS-Rebind-Protection in your router settings.

Example:
![image](https://cloud.githubusercontent.com/assets/24809481/24698017/7b7707d2-19ef-11e7-87c3-db0bfc252fd5.png)

**Comment by dschaper** [comment]
Can we get an update on this, is it still present with the latest Pi-hole version?

**Comment by dschaper** [comment]
Reopen if this is still an issue.

**Comment by ravenclaw900** [comment]
I know this is a bit late, but for me, the problem is resolved as soon as I edit my DNS settings to point to the Pi-Hole.  Otherwise, I have to access it through it's IP address.

**Comment by PromoFaux** [comment]
> the problem is resolved as soon as I edit my DNS settings to point to the Pi-Hole

Indeed. The important thing here is that only the Pi-hole knows about the special DNS name of `pi.hole`
