### ISSUE TITLE
"pihole -up" aborts on system w/o webinterface

### ISSUE THREAD

**Issue by fmjensen** [pi-hole/pi-hole#1347]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
"pihole -up" updates system where webinterface was opted not to be installed, without problems,

**[BUG | ISSUE] Actual Behaviour:**
me@rpiii:~ $ pihole -up
::: Checking for updates...
::: Pi-hole Core:   update available
::: Critical Error: Web Admin repo is missing from system!
::: Please re-run install script from https://github.com/pi-hole/pi-hole
me@rpiii:~ $ 

**[BUG | ISSUE] Steps to reproduce:**
run command "pihole -up"

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
[`setupVars.conf` is not sourced before this line](https://github.com/pi-hole/pi-hole/blob/development/advanced/Scripts/update.sh#L126).

**Comment by Mcat12** [comment]
In the mean time, try adding the [line that the PR adds](https://github.com/pi-hole/pi-hole/pull/1348/files) to `/opt/pihole/update.sh`.

**Comment by fmjensen** [comment]
LGTM :  fixed the problem at my RPi 3, now running v2.13.2
