### ISSUE TITLE
"Development" is spelled incorrectly in DOHostingSlug.png in the README.md

### ISSUE THREAD

**Issue by rappo** [pi-hole/pi-hole#1352]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
The word "Development" in https://assets.pi-hole.net/static/DOHostingSlug.png (as linked in README.md) should be spelled exactly as I typed it.

**[BUG | ISSUE] Actual Behaviour:**
The word is spelled with an extra e: "Develop**e**ment"
![image](https://cloud.githubusercontent.com/assets/2245234/24306452/dea1f090-107d-11e7-9d24-6a69a1f081a0.png)

**[BUG | ISSUE] Steps to reproduce:**

Look at DOHostingSlug.png in the README.md

**Comment by PromoFaux** [comment]
:rofl: Nice catch!

While you're here.. any idea why bountysource integration is no longer working with our repos?

**Comment by rappo** [comment]
We've been having some issues with GitHub this week. I think they may have changed something that broke the integration (and some issue syncing as well). Hoping to dig into it tomorrow.

**Comment by PromoFaux** [comment]
>this week

It's been like this for the last 10 months or so... ;) I saw there were a couple of issues open on it last time I thought about it so didn't open another.

**Comment by dschaper** [comment]
This has been fixed in the assets server, not sure why GitHub is not picking up the new replacement image at https://assets.pi-hole.net/static/DOHostingSlug.png

**Comment by dschaper** [comment]
Resolved, had GitHub purge the old image.
