### ISSUE TITLE
Pi Hole not blocking ads

### ISSUE THREAD

**Issue by ZackBoyd** [pi-hole/pi-hole#1356]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Pi Hole blocks ads for most major site

**[BUG | ISSUE] Actual Behaviour:**
Domain Queries are showing up in the admin portal, but only one domain has been reported as blocked while ~102k domains are 'being' blocked. I've tried 4-5 major sites after clearing my cache and still see ads loaded

**[BUG | ISSUE] Steps to reproduce:**
Reinstalled pi hole twice and used 'set apt install resolvconf' command from https://github.com/pi-hole/pi-hole/issues/622
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`5rtmtklns5`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

![image](https://cloud.githubusercontent.com/assets/3410499/24326345/7fe9cd10-1182-11e7-93b8-89bb333e15cb.png)

**Comment by technicalpyro** [comment]
what happens when you use the "tail pihole log" under tools in the admin portal and view a site with ads

**Comment by ZackBoyd** [comment]
@technicalpyro 
![image](https://cloud.githubusercontent.com/assets/3410499/24326697/6f90feea-118a-11e7-9baf-22e56b6c1e8d.png)

**Comment by technicalpyro** [comment]
that would appear the there are no "piholed" domains being requested this is one way websites are getting around technologies such as this.  They serve some ads from their own domain to get around blocking technologies

**Comment by ZackBoyd** [comment]
@technicalpyro I tried it on a few websites that definitely have ad network domains loaded (NYT, CNN, Facebook etc) and I'm actually not seeing anything in the live log when I load those websites.

**Comment by technicalpyro** [comment]
what does your network setup look like.  in your router is there a second DNS set that is allowing the ads through?
are you blocking on both IPv4 and IPv6?
please run the following commands for us as well using command prompt
````
nslookup doubleclick.net`
```
and
```
nslookup pi.hole
```

**Comment by ZackBoyd** [comment]
Router setup : 
![image](https://cloud.githubusercontent.com/assets/3410499/24327007/f65203f4-1192-11e7-83cd-86ddd19e1f15.png)

I believe I'm only blocking on IPv4.

**Comment by technicalpyro** [comment]
so the reason ads are still getting through is because you are using google as the secondary dns change the second dns address to something like `10.0.0.0` and flush the dns cache in your browser and windows and ads should be properly blocked

**Comment by ZackBoyd** [comment]
When I removed the google secondary dns and tried to load a page, I got a 'server DNS address could not be found' error

**Comment by technicalpyro** [comment]
ok that tells me potentially your pihole is blocking that address and there is an issue with the blocking page unfortunately i cannot view your debug log as i am not a member of the dev team.  

what happens if you log into your pi(assuming you have the vnc setup) and attempt to browse t the same site?

**Comment by ZackBoyd** [comment]
When I try sites in the browser on the pi it blocks them effectively, so it seems like it is probably related to the forwarding from the router to the connected devices

**Comment by technicalpyro** [comment]
that is most likely true.  what brank make of router do you have ?
also make sure if there is a dns rebind that it is disabled

**Comment by ZackBoyd** [comment]
Netgear

**Comment by technicalpyro** [comment]
Under menu option Advanced->DHCP DNS, the "Use Internal DNS" is checked, "Prevent DNS-rebind attacks" is checked. 

check those two settings both could prevent your router serving dns through what it sees as an internal IP

**Comment by ZackBoyd** [comment]
Thanks @technicalpyro I couldn't find those setting anywhere in the router admin portal, but I'll look around at forums for netgear

**Comment by technicalpyro** [comment]
@ZackBoyd have you found a solution?

one option to solve you issue would be to turn off the DHCP in your router and use the pi-hole DHCP which will provide your pihole as the DNS server to all devices connecting to your network 

if you have solved your issue please close this as we have determined it is not an issue with pi-hole but more of a networking issue

**Comment by ZackBoyd** [comment]
@technicalpyro I ended up just setting the DNS directly for the few devices and it's working that way. I think my model of router doesn't handle internal DNS settings well. Thanks for your help!
