### ISSUE TITLE
Thousands of queries from pi-hole to dynamic DNS address

### ISSUE THREAD

**Issue by vnckppl** [pi-hole/pi-hole#1357]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_7_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
Reinstalled pi-hole twice.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`999g493c3r`

I see spikes in my pihole queries, sometimes a few 1000 per minute. The queries come from the pi itself and the domain is my dynamic DNS address. In addition, pi-hole is not blocking ads.

**Comment by Mcat12** [comment]
You have two interface lines in `/etc/pihole/setupVars.conf` for some reason. The debug log shows that ad domains are getting blocked, and I see a few ads being blocked in the dnsmasq log snippet. Do you have any other software running on the Pi-hole? Make sure you have it secured (port 22 not open to the internet, etc).

**Comment by vnckppl** [comment]
Thanks for your reply. 
Here is some more information:

- My pi is also running an openVPN server, which is the reason I have two interfaces in `/etc/pihole/SetupVars.conf` (i.e., tun0 and eth0)

- I use ssh to connect to my pi from outside my network, so I do have port 22 opened to the internet and forwarded on my router. This should not interfere with the working of pi-hole, should it?

- I have set my pi-hole IP as the router's primary and only DNS address (IPv4). All computers/phones/consoles in the network do receive the pi's ip as their DNS. However, the pi does not seem to block ads on the phones, even though my phone report its DNS to be my pi. How come? Also, when I tail the pihole.log file, I can see my computer's queries pop up almost immediately if I go to a new website. However, my phone does not show up in the pihole.log and ads are not blocked in that device. This is the same for other phones/tablets on my network.

**Comment by Mcat12** [comment]
The IPv6 issue might be the reason it's not working on some devices. You should disable DHCP on your router and enable it in the Pi-hole so that your devices only get Pi-hole as the DNS server. As for the SSH port, if you haven't changed your Pi's password (and even if you did) you could be playing host to a botnet, virus, etc. Since port 22 is forwarded, anyone on the internet can access and try to break into your Pi-hole. RPI has actually disabled SSH by default on the newer Raspbian images because it's so easy to break into an unconfigured Pi. Research securing SSH access. Here's a place to get started: http://askubuntu.com/a/2279

**Comment by vnckppl** [comment]
Thanks for the suggestion. Can I still forward ports in my router to the IP addresses handed out by the pi? I have now for the individual devices configured IPv6 DNS whenever possible, and if not, disabled IPv6. This works.

Regarding the SSH: I use IP table rules to block specific incoming requests in addition to fail2ban. I also have ssh password disabled in favor of ssh keys, so I think I'm okay.

**Comment by Mcat12** [comment]
You should still be able to port forward.

**Comment by dschaper** [comment]
Pinging for status before closing.
