### ISSUE TITLE
[Website] [Shop] Images are loaded from unsecure server and get blocked by Chrome

### ISSUE THREAD

**Issue by r0ckarong** [pi-hole/pi-hole#1360]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[BUG | ISSUE] Expected Behaviour:**
When browsing the merch shop the images are loaded from `http://image.kite.ly/render/?...`
In my Chrome (57.0.2987.110) operations from a secured site to unsecured severs are blocked. Thus no product images are being rendered.

**[BUG | ISSUE] Actual Behaviour:**
Product images would be loaded through https and shown correctly.

**[BUG | ISSUE] Steps to reproduce:**

- Open latest Chrome
- Visit Pi-hole merch shop
- Open any product that uses kite.ly as image source
![selection_003](https://cloud.githubusercontent.com/assets/4920542/24417235/e302c6b0-13e7-11e7-956c-4548dded8e85.png)

**Comment by r0ckarong** [comment]
@jacobsalmela

**Comment by jacobsalmela** [comment]
Thanks.  I'm looking into this.

**Comment by r0ckarong** [comment]
Works now. Thank you.
