### ISSUE TITLE
Pi-hole updater doesn't check used webserver type

### ISSUE THREAD

**Issue by dajappie** [pi-hole/pi-hole#1362]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG | ISSUE] Expected Behaviour:**

Pi-hole updater should check the used webserver (lightppd, nginx) and not assume lighttpd and just enable that service without warning

**[BUG | ISSUE] Actual Behaviour:**

Pi-hole updater activates a disabled lighttpd without warning, causing failure of an already running nginx instance

**[BUG | ISSUE] Steps to reproduce:**

- Install Pi-hole and run it on nginx, disabling lighttpd
- Upgrade Pi-hole
- Lighttpd is now running again

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by EsEnZeT** [comment]
any news on that?

**Comment by dschaper** [comment]
This will require a major rewrite of the installer and Pi-hole system. It won't be a quick fix for the dev team to do, all of our time has been spent on the FTL engine and supporting that. It's on the long term list, along with the ability to use other resolvers, but if you have the ability to write bash shell scripts, we could always use the help.
