### ISSUE TITLE
CSRF at dns server update page

### ISSUE THREAD

**Issue by koenbuyens** [pi-hole/pi-hole#1367]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

3
---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Do not accept unauthorized state changes for DNS information. Refer to https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF) for more information.
An attacker may point the downstream DNS server used by pihole to a malicious one.

**[BUG | ISSUE] Actual Behaviour:**
DNS server is updated to an unauthorized source.
[setdns_csrf.html.txt](https://github.com/pi-hole/pi-hole/files/888534/setdns_csrf.html.txt)

**[BUG | ISSUE] Steps to reproduce:**

- login to the administrator interface of pihole by surfing to http://<pihole.local>/admin/
- rename attached file to setdns_csrf.html 
[setdns_csrf.html.txt](https://github.com/pi-hole/pi-hole/files/888527/setdns_csrf.html.txt)
- change pihole.local in attached file (action) to dns name of your pihole (e.g. pihole.hole)
-open setdns_csrf.html in same browser as the admin interface
- press the button
- observe that the dns server now points to the custom value 192.168.1.1

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #463](https://github.com/pi-hole/AdminLTE/issues/463) via [**ZenHub**](https://www.zenhub.com/)
