### ISSUE TITLE
Poor exception handling for missing packages

### ISSUE THREAD

**Issue by adamcamp** [pi-hole/pi-hole#1368]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

3

---

**[BUG | ISSUE] Expected Behaviour:**

- Install script fails in a deterministic manner when packages are missing or yum installation fails
- Install script outputs useful debugging information when failures occur

**[BUG | ISSUE] Actual Behaviour:**
- Install script only fails when the missing package is the only one installed
- Install script just terminates with no output to identify the error.

**[BUG | ISSUE] Steps to reproduce:**
Prereq:
1. Ensure that one of the following dependencies is missing from yum, or add a fake dependency to the end of the list (for me procps-ng was missing):

`(git iproute net-tools newt procps-ng)`

2. Manually uninstall git if it is already installed.
`yum remove git`

Part A (successful install):
1. Run through install and it should complete successfully.
`bash basic-install.sh`

**Note that the installation succeeded despite this missing package** 

Part B (failed update):
1. Run pihole -r to reconfigure pihole
`pihole -r`
2. Install script will fail with the following output:
```::: Reconfigure option selected
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking yum for upgraded packages.... done!
:::
::: There are 2 updates available for your system!
::: We recommend you update your OS after installing Pi-Hole!
:::
:::    Checking for git... installed!
:::    Checking for iproute... installed!
:::    Checking for net-tools... installed!
:::    Checking for newt... installed!
:::    Checking for procps-ng... added to install list!
:::    Checking for epel-release... installed!
```

**Note that there is no information about why it failed or how to resolve the issue.** 

**Analysis**
Basically what is happening is that the successful installation of git is overriding the return code of the failed installation of procps-ng, and so the initial install is successful.

After that, everything is installed except procps-ng, so the script fails when it gets to that point, but no output is shown because stderr is redirected to /dev/null:

`"${PKG_INSTALL[@]}" "${installArray[@]}" &> /dev/null`

**Resolution**
1. Remove /dev/null redirection so the user can easily see that procps-ng is missing, enabling them to take proper remediation steps.
2. Install each package separately so that the script fails anytime a required dependency fails to install, not just if that required dependency is the only package to be installed.

New output:
```
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking yum for upgraded packages.... done!
:::
::: There are 2 updates available for your system!
::: We recommend you update your OS after installing Pi-Hole!
:::
:::    Checking for git... already installed!
:::    Checking for iproute... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for newt... already installed!
:::    Checking for procps-ng... installing!
Loaded plugins: priorities, update-motd, upgrade-helper
1004 packages excluded due to repository priority protections
No package procps-ng available.
Error: Nothing to do
```

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
Closing since it's stale, along with the corresponding PR #1369
