### ISSUE TITLE
Can I disable the monitoring page or protect it with .htaccess?

### ISSUE THREAD

**Issue by libeclipse** [pi-hole/pi-hole#1370]
Last time I installed PiHole, I immediately uninstalled it because of privacy concerns. Anyone on my local network could run an nmap and load the IP of my Pi, then view the internet access history of everyone in the house.

Can this entire thing be disabled or protected with .htaccess?

**Comment by Technetium1** [comment]
There is an option in the settings called privacy mode. You could also uncheck `Show blocked queries` and `Show permitted queries`.

**Comment by PromoFaux** [comment]
>There is an option in the settings called privacy mode. You could also uncheck Show blocked queries and Show permitted queries.

I think we need to overhaul that section, as anyone with access to the web admin can just change those settings back!

@libeclipse we ship a password setting by default now. Protection with .htaccess was always possible, but there is no need for that now! On install, you are given a random password (and told what it is, obviously 😉 ), and you can change it from the console by running `pihole -a -p <insertyourpasswordhere>`

It looks like this when not logged in:
![image](https://cloud.githubusercontent.com/assets/1998970/24647145/8ed47852-1916-11e7-8636-433e0651bc33.png)

**Comment by libeclipse** [comment]
Ah, thank you. Will test this out when I get home.

**Comment by libeclipse** [comment]
Seems to work, and you have a bug bounty program so I'm reasonably confident in its security. Thank you.
