### ISSUE TITLE
[DNScrypt] Error

### ISSUE THREAD

**Issue by Setsuneh** [pi-hole/pi-hole#1372]
Hi,

Trying to install DNSCrypt with https://github.com/pi-hole/pi-hole/wiki/DNSCrypt
However I've this. 

Thanks

```
root@vps-22235:/lib/systemd/system# systemctl start /lib/systemd/system/dnscrypt-proxy@.service 
Failed to start lib-systemd-system-dnscrypt\x2dproxy\x40.service.mount: Unit lib-systemd-system-dnscrypt\x2dproxy\x40.service.mount failed to load: No such file or directory.
```

```
root@vps-22235:/lib/systemd/system# cat /lib/systemd/system/dnscrypt-proxy.service 
[Unit]
Description=DNSCrypt client proxy
Documentation=man:dnscrypt-proxy(8)
Requires=dnscrypt-proxy@%i.socket
After=network.target
Before=nss-lookup.target

[Install]
Also=dnscrypt-proxy.socket
Also=dnscrypt-proxy@dnscrypt.eu-dk.socket
Also=dnscrypt-proxy@dnscrypt.eu-nl.socket
# Also=dnscrypt-proxy@dnscrypt.eu-dk-ipv4.socket
# Also=dnscrypt-proxy@dnscrypt.eu-nl-ipv4.socket
WantedBy=multi-user.target

[Service]
Type=simple
NonBlocking=true

# Edit the configuration file appropriately, or the service will not start.
# See https://dnscrypt.org for more information.
ExecStart=/usr/local/sbin/dnscrypt-proxy \
	--resolver -name=%i
	--user=dnscrypt

Restart=always
```

**Comment by dschaper** [comment]
Did you copy/paste? `\x2d` is the ascii code for `-` and `\x40` is the code for `@`. And you look to have `-` in the path instead of `\`'s.

**Comment by Setsuneh** [comment]
Yes I have. But I don't understand all for \x2d & \x40.
Must I modify > Requires=dnscrypt-proxy@%i.socket < ?

**Comment by dschaper** [comment]
When you copied and pasted, it didn't copy the symbols, but the html representation of the symbols. And looking over that wiki entry, there isn't any instructions for running `systemctl start` for any of the services, the service files are written to be `systemctl enable` and automatically started via socket calls.

**Comment by dschaper** [comment]
Any further information?
