### ISSUE TITLE
Ubuntu - Cannot start dnsmasq

### ISSUE THREAD

**Issue by Diablosblizz** [pi-hole/pi-hole#1373]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
- DNSMASQ should start on startup

**[BUG | ISSUE] Actual Behaviour:**
- DNSMASQ does not start on startup

**[BUG | ISSUE] Steps to reproduce:**

- sudo service dnsmasq start

**(Optional) Debug token generated by `pihole -d`:**

`ht9pcniipn`

When I try to start dnsmasq, I get an error:

"missing parameter at line 43 of /etc/dnsmasq.d/01-pihole.conf"

If I check that file, here is the results:

```
...
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list

no-resolv
cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=300

log-async
server=8.8.8.8
domain-needed
bogus-priv
interface
```

This is very similar to https://github.com/pi-hole/pi-hole/issues/1321, however I do NOT have the "local-service" line which appeared to be causing the problem in that situation.

Any ideas?

**Comment by dschaper** [comment]
Try setting that `interface` to have a value `interface=eth0` or if you want dnsmasq to listen on all interfaces, remove the line completely.

**Comment by Diablosblizz** [comment]
Awesome, I just changed eth0 to ens3 and it's working great! Thanks!
