### ISSUE TITLE
Pi Hole can't load files behind Cloudflare

### ISSUE THREAD

**Issue by timmyrs** [pi-hole/pi-hole#1375]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---

**Steps to reproduce:**

- I put `https://timmyrs.de/hosts-example.txt` into my `adlists.list`
- I ran `pihole -g`

**Expected Behaviour:**

I expected Pi Hole to load my hosts file, which is behind Cloudflare.

**Actual Behaviour:**

I get the following error

> ::: Getting timmyrs.de list... done
> :::   Status: Forbidden
> :::   Download failed and no cached list available (list will not be considered)

which is, as it turns out, because pi hole does not support cookies.

**Comment by technicalpyro** [comment]
just wndering why you think the user agent is to blame the following in my UA and i can access CF sites without issue 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36`

**Comment by Mcat12** [comment]
Are you able to access them with gravity's default user agent? `Mozilla/5.0`

**Comment by timmyrs** [comment]
Sending `curl -v -H "User-Agent: Mozilla/5.0" https://timmyrs.de/hosts-example.txt` works perfectly fine, returning the contents of the file. @Mcat12 @technicalpyro 
Furthermore, I have also ruled out HSTS, as it doesn't work with a non-HTTPS domain, which is also behind Cloudflare.
However, all requests are blocked by Cloudflare, as the access log tells me.

**Comment by technicalpyro** [comment]
brief google search points at cookies and being unable to handle the response required at being potentially the issue

**Comment by timmyrs** [comment]
I have actually reconstructed the command gravity.sh is using and even that is working.
`curl -s -L -w %{http_code} -A "Mozilla/5.0" https://timmyrs.de/hosts-example.txt`

**Comment by technicalpyro** [comment]
@Mcat12 is there a more verbose way of running gravity ie can see the commands sent and their responses so we can see where it breaks ?

**Comment by timmyrs** [comment]
@technicalpyro I found out that the gravity.sh seems to be located at `/opt/pihole/gravity.sh`.
I am currently trying to add some debug outputs to it.

**Comment by timmyrs** [comment]
So, I found the gravity.sh, changed it to tell me where curl saves the list to, read the file and Cloudflare's error pretty much sums it up: `Please enable cookies.`

**Comment by technicalpyro** [comment]
OMG i got one right .... i do believe there is a way to enable cookies for use within an ssh session not sure how to implement it though

**Comment by timmyrs** [comment]
Disabling "Browser Integrity Check" in the Web Application Firewall configuration seems to prevent Cloudflare from blocking Pi-Hole. However, it also prevents Cloudflare from blocking actual threads, so this is not a viable solution in my opinion.

**Comment by dschaper** [comment]
`curl` isn't really built to handle the tasks needed by a full browser. It's not session oriented, and cookies are not really implemented in a way that CloudFlare would use them. 

Is there you need to have your list behind a CDN like CloudFlare and not just as a GitHub gist that could be pulled down into Pi-hole?

**Comment by timmyrs** [comment]
I have a pretty big list which can be modified by changing the arguments and having Cloudflare as a cache would be optimal, as my server has a traffic limit.

I also don't see why Pi-Hole's request is being blocked, whilst the same command, but out of Pi-Hole works perfectly fine.

**Comment by dschaper** [comment]
We do have some domains that require additional headers in order to successfully download. But I'm not sure how we could detect if a domain was CloudFlare hosted and modify the `curl` request to account for the WAF that CloudFlare is using to determine if the query is hostile or benign.

**Comment by dschaper** [comment]
I'm wondering though if the user agent is what is causing the problems. 

By default we just use https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L186 - "Mozilla/10.0"

We could try a more modern and correct user agent with a full and proper string as we do at https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L192 ?

**Comment by timmyrs** [comment]
Yeah, that is kind of what I am suggesting, however, even the default User Agent seems to work using the normal `curl` command as I mentioned here: https://github.com/pi-hole/pi-hole/issues/1375#issuecomment-292728477

**Comment by dschaper** [comment]
Does the access log show anything on the blocked attempts that can shed any light on to what is common among the denials? I've seen a few sites lately that come up with a CloudFlare interstitial page and a message that they are checking my browser. I, by default, have cookies globally disabled, so I just get a loop of the CloudFlare check pages and never hit the domain.

**Comment by timmyrs** [comment]
No, the requests are blocked by Cloudflare, and therefore never reach my server.

**Comment by dschaper** [comment]
There is a known bug that has been reported with `dnsmasq` having issues with CloudFlare domains and DNSSEC, I'm not sure if this is related as you seem to be able to resolve the domains, but investigating anyways.

**Comment by dschaper** [comment]
Going to mark this as External Issue as we can't access the information from CloudFlare explaining the behavior.

**Comment by dschaper** [comment]
Issue has had no updates. Closing. Reopen if still a problem

**Comment by timmyrs** [comment]
Yes, with "Browser Integrity Check" in Cloudflare enabled, the list still can't download.
You are also doing something wierd with the curl command in the gravity.sh, as the normal curl command works perfectly fine.

**Comment by dschaper** [comment]
I just created a new Ubuntu VM, and installed from scratch, and was able to download your test domain without any issues.

```
root@ubuntu-512mb-nyc3-01:/etc/pihole# cat list.7.timmyrs.de.domains 
127.0.0.1 localhost
::1 localhost
::1 ip6-localhost

0.0.0.0 evil-shit.de
```

**Comment by dschaper** [comment]
```
::: Getting timmyrs.de list...+ gravity_transport https://timmyrs.de/hosts-example.txt '' 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'
+ url=https://timmyrs.de/hosts-example.txt
+ cmd_ext=
+ agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'
++ mktemp
+ patternBuffer=/tmp/tmp.QhfhtvlZ3D
+ heisenbergCompensator=
+ [[ -r /etc/pihole/list.7.timmyrs.de.domains ]]
++ curl -s -L -w '%{http_code}' -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' https://timmyrs.de/hosts-example.txt -o /tmp/tmp.QhfhtvlZ3D
+ err=200
+ echo ' done'
 done
+ echo -n ':::   Status: '
:::   Status: + case "$err" in
+ echo 'Success (OK)'
Success (OK)
+ success=true
+ gravity_patternCheck /tmp/tmp.QhfhtvlZ3D true 200
+ patternBuffer=/tmp/tmp.QhfhtvlZ3D
+ success=true
+ error=200
+ '[' true = true ']'
+ '[' 200 == 304 ']'
+ [[ -s /tmp/tmp.QhfhtvlZ3D ]]
+ mv /tmp/tmp.QhfhtvlZ3D /etc/pihole/list.7.timmyrs.de.domains
+ echo ':::   List updated, transport successful!'
:::   List updated, transport successful!
```

**Comment by timmyrs** [comment]
Interesting, it worked for me too. Well then I guess the installer/updater somehow called a different gravity.sh...
