### ISSUE TITLE
Pihole can't handle large a large blacklist file

### ISSUE THREAD

**Issue by deltaxflux** [pi-hole/pi-hole#1377]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
8

**[BUG | ISSUE] Expected Behaviour:**
- Pihole should be able to handle a large amount of date
- Statistics should load 

**[BUG | ISSUE] Actual Behaviour:**
- Statictis dosen't work 
- Pihole output is getting worse
```
__              
|  ()__| |  | |
|  / |__| ' /  \ / -)
|| ||   |||_/__|

        [IP SERVER]/32

load average: 0,01, 0,05, 0,07
1 days, 11 hours, 51 minutes.
-------------------------------
Blocking:      0
Queries:       0
Pi-holed:      0 (0.00%
```

![](http://i.imgur.com/cohItQK.png)

**[BUG | ISSUE] Steps to reproduce:**
- Normal setup 
- use a custom crafted blacklist
- pihole statistics crashed

**Hint**
- Error is independet from the fact that you use hardcoded links  

**Token or debug**
- debug log is too large ~ 24mb 
- uploaded later

It would be a pleasure if someone can solve this. Maby it isn't a normal user bahavior. 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Blacklist**
```
$(curl --connect-timeout 10 $(curl https://raw.githubusercontent.com/collinbarrett/FilterLists/master/data/lists.json | grep "view" | awk '{print $2}' | sed -e 's/"//g' | sed -e 's/\s//g' | grep 'txt$' | sort -u)) | grep -E '^\|\||^127.0.0.1'  | sed -e "s/||//g" | sed "s/\/.*//g" | sed 's/\^.*//g' | sed 's/\?.*//g' | sed 's/\=//g' | sed  -e 's/\s$//g' | grep -v '\*' | grep -v '\-$' | grep -v '\.$' |  grep '[a-Z]$' | awk '{print $(NF)}'| sort -u >> /etc/pihole/blacklist.txt
```

**Comment by rad4day** [comment]
Well here is the [log file](https://drive.google.com/open?id=0B7D_3XXqUG5DWmxMaEdFdnpvQ2c) for you =)

**Comment by rad4day** [comment]
BTW I don't really enjoy the amount of information which would've been uploaded with the debug log. I mean the IP and the hashed webpassword? Seriously?

**Comment by Mcat12** [comment]
The blacklist is meant to be used for manually added domains and generally should be under 1000 domains. You can follow [this](https://github.com/pi-hole/pi-hole/wiki/Customising-Sources-for-Ad-Lists) guide to add extra ad list sources, which is how you'd add huge lists such as this one.

@rad4day We try to only take what's necessary to understand the situation in the debug log. In fact, the next version [won't include the (doubly hashed) web password in the debug log](https://github.com/pi-hole/pi-hole/pull/1331). As for the IP addresses, they are local IP addresses and we should not be able to access them. They are also needed so we can determine if Pi-hole is working correctly and isn't running into networking errors. We know that some users still are uncomfortable uploading some of this information, so we do give them the choice of uploading it to our secure server or manually reviewing it and uploading it as they see fit.

**Comment by rad4day** [comment]
Well I've followed the guide now, (and deleted the blacklist.txt) but the statistics are still dead.

**Comment by technicalpyro** [comment]
try running pihole -r now that everything has been followed  and select the repair option

**Comment by deltaxflux** [comment]
Doesn't solve the problem

**Comment by Mcat12** [comment]
I see that you're using nginx instead of lighttpd. What are the contents of nginx's error log? Because you are using so many blocked domains, PHP might not be fast enough on your hardware to finish before the timeout. The FTL backend should fix this, and you can test it by switching to the dev branch with `pihole checkout dev`.

**Comment by rad4day** [comment]
It is actually exhausting the 128mb of memory assigned for php

"PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 75497472 bytes) in [path]/admin/scripts/pi-hole/php/data.php on line 581"
>> This behavior is actually fixed in the dev-build.
Also the top statistic "Queries over Time" is working again, but now "Query Types over Time" and "Forward Destinations over Time" which were working before are not showing anymore. The nginx error-log is empty.

**Comment by Mcat12** [comment]
Try leaving it run for a day and see if the two over time graphs come back.

**Comment by rad4day** [comment]
@Mcat12 you were right they are suddenly back now =)
