### ISSUE TITLE
pihole -h: /usr/local/bin/pihole: line 289: -a: command not found

### ISSUE THREAD

**Issue by cybrnook** [pi-hole/pi-hole#1382]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
6

**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
clean return of help menu

**[BUG | ISSUE] Actual Behaviour:**
help menu is returned, but extra verbiage is added (/usr/local/bin/pihole: line 289: -a: command not found)

**[BUG | ISSUE] Steps to reproduce:**
as standard pi user, issue a pihole -h
![pihole](https://cloud.githubusercontent.com/assets/22136734/25008632/5340220a-2032-11e7-9329-4b5426482b09.PNG)
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Thanks for reporting this issue!
It has, however, already been reported and is also already fixed in the next upcoming release.

See https://github.com/pi-hole/pi-hole/pull/1340
