### ISSUE TITLE
ad.adverticum.net not blocking in my laptop

### ISSUE THREAD

**Issue by szuniverse** [pi-hole/pi-hole#1383]
Hi 
I installed the pi-hole (in my raspberry pi). And everything works fine except on my laptop. If I am browsing http://www.index.hu on my phone the ads are blocked but If I do the same on my laptop I am still seeing ads from ad.adverticum.net. I already add ad.adverticum.net to my blacklist but nothing happened.
could you check it what is the problem with this site?

Thanks in advance.

**Comment by Mcat12** [comment]
How have you configured Pi-hole to be used on your system? (via router DNS, manually on every client, etc)

**Comment by szuniverse** [comment]
I am using Google Wifi router and set the DNS on the router.

**Comment by Mcat12** [comment]
Have you flushed your DNS cache on the laptop/restarted it? If you can't reach http://pi.hole/admin on your laptop, then it's not using Pi-hole yet.

**Comment by technicalpyro** [comment]
also make sure your anti virus or firewall package is not forcing you to use their DNS ESET and comodo are notorious for that

**Comment by dschaper** [comment]
Ping for any followup.
