### ISSUE TITLE
debug not picking up gateway correctly 

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1385]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{6}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
when running pihole -d it picks up the gateway correctly

**[BUG | ISSUE] Actual Behaviour:**
the command used `route | grep default | cut -d ' ' -f 3`
does not seem to pick up the correct gateway text 

**[BUG | ISSUE] Steps to reproduce:**

-run pihole -d 
-it gives errors picking up and testing the gateway
-
See [this ](https://www.reddit.com/r/pihole/comments/659yqv/no_dns_resolution_need_help_troubleshooting/)

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
```
pi@raspberrypi:~ $ route | grep default
default         172.16.1.1      0.0.0.0         UG    202    0        0 eth0

```
unless i am missing something it should cut 2?

**Comment by DL6ER** [comment]
Why did you close this issue?
