### ISSUE TITLE
"Block page" broken when custom hostname is used

### ISSUE THREAD

**Issue by SnaKKo** [pi-hole/pi-hole#1386]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate

**How familiar are you with the codebase?:**

2

**[BUG] Expected Behaviour:**

I changed my Raspberry to respond at "server" hostname (not default pi.hole hostname).
I expected to go to http://server/ and see the "block page" with all css/js loaded.

**[BUG] Actual Behaviour:**

If i go to http://server/ I see a broken page (no css/js loaded because loaded from pi.hole domain that doesn't exist)

**[BUG] Steps to reproduce:**

- Change the hostname (ex: server)
- Go to http://server/
- See the broken page (no css/js loaded)

**Comment by DL6ER** [comment]
`pi.hole` should still resolve fine on all machines that use the Pi-hole DNS server as it is hard-coded in `/etc/pihole/local.list` once with the defined host name *and* once with `pi.hole`.

I did exactly what you said (I changed the host name to `server` and ran `sudo pihole -g` afterwards). The result on one of my local machines (not the Pi-hole itself, of course) is as expected:
```
me@desktop ~ $ dig +short server
192.168.2.10
me@desktop ~ $ dig +short pi.hole
192.168.2.10
```

In the browser, everything loads fine when I go to `http://server`, since also content from `pi.hole` can be successfully accessed.

**Comment by SnaKKo** [comment]
Connected in my router (WRT54GL with tomato) with SSH:

```
$ ping pi.hole
ping: bad address 'pi.hole'
$ ping server
PING server (192.168.0.3): 56 data bytes
```

Connected in my Raspberry Pi (pi.hole, server) with SSH:

```
$ ping pi.hole
PING pi.hole (192.168.0.3) 56(84) bytes of data.
$ ping server
PING server (127.0.1.1) 56(84) bytes of data.
```

Connected in my NAS with SSH:

```
$ ping pi.hole
ping: pi.hole: No address associated with hostname
$ ping server
PING server (192.168.0.3) 56(84) bytes of data.
```

The router is configured to use 192.168.0.3 as primary DNS (8.8.8.8 secondary and 8.8.4.4 tertiary).

It seems not a Pi Hole fault.

**Comment by DL6ER** [comment]
Is on one of your devices `dig` available? It will allow more flexibility in testing than `ping` offers.

Try on one of your devices (but not the Raspberry!):
```
dig +short server

**Comment by SnaKKo** [comment]
In these 3 devices there isn't `dig` command, I will try with a real computer soon.
Thanks,

**Comment by SnaKKo** [comment]
From a PC inside the LAN:

```
$ dig +short server
192.168.0.3
$ dig +short pi.hole
$ dig +short server @192.168.0.3
127.0.1.1
192.168.0.3
$ dig +short pi.hole @192.168.0.3
192.168.0.3
```

**Comment by DL6ER** [comment]
Something is odd here, why is the answer different when you use the systems default DNS resolver

> ```
> $ dig +short server
> 192.168.0.3
> $ dig +short pi.hole
> ```

and when you *explicitly* specify which DNS server to use?

> ```
> $ dig +short server @192.168.0.3
> 127.0.1.1
> 192.168.0.3
> $ dig +short pi.hole @192.168.0.3
> 192.168.0.3
> ```

Please run
```
dig server
dig pi.hole
```

without the `+short` option and look for the `;; SERVER: ....` part

**Comment by SnaKKo** [comment]
**dig server**
```
$ dig server

; <<>> DiG 9.9.5-11ubuntu1.3-Ubuntu <<>> server
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13047
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;server.				IN	A

;; ANSWER SECTION:
server.			0	IN	A	192.168.0.3

;; Query time: 3 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Apr 19 17:13:17 CEST 2017
;; MSG SIZE  rcvd: 40
```
**dig pi.hole**
```
$ dig pi.hole

; <<>> DiG 9.9.5-11ubuntu1.3-Ubuntu <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16829
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pi.hole.			IN	A

;; Query time: 3 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Apr 19 17:13:44 CEST 2017
;; MSG SIZE  rcvd: 25
```
**dig server @192.168.0.3**
```
$ dig server @192.168.0.3

; <<>> DiG 9.9.5-11ubuntu1.3-Ubuntu <<>> server @192.168.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7514
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;server.				IN	A

;; ANSWER SECTION:
server.			300	IN	A	192.168.0.3
server.			300	IN	A	127.0.1.1

;; Query time: 2 msec
;; SERVER: 192.168.0.3#53(192.168.0.3)
;; WHEN: Wed Apr 19 17:14:26 CEST 2017
;; MSG SIZE  rcvd: 67
```
**dig pi.hole @192.168.0.3**
```
$ dig pi.hole @192.168.0.3

; <<>> DiG 9.9.5-11ubuntu1.3-Ubuntu <<>> pi.hole @192.168.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45881
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.			IN	A

;; ANSWER SECTION:
pi.hole.		300	IN	A	192.168.0.3

;; Query time: 1 msec
;; SERVER: 192.168.0.3#53(192.168.0.3)
;; WHEN: Wed Apr 19 17:14:51 CEST 2017
;; MSG SIZE  rcvd: 52
```

**Comment by DL6ER** [comment]
I see that in the standard scenario, your computer asks `;; SERVER: 127.0.1.1#53(127.0.1.1)` instead of only the Pi-hole.

Do you use `NetworkManager`? If so, you might have not configured the connection correctly (there is no or more than one DNS server).

You can fix the behavior for `NetworkManager` by doing this:

> Edit /etc/NetworkManager/NetworkManager.conf:
> 
> ```
> # dns=dnsmasq
> ```
> and restart the Network Manager:
>
> `sudo restart network-manager`
> When connecting your DNS server will now be properly picked up and used by your client.

**Comment by SnaKKo** [comment]
Thanks for the tips, it's not a pi hole fault for sure, so I closed this issue.
I investigate by myself about this issue, thank you a lot.
