### ISSUE TITLE
Teleporter ZIP missing static DHCP lease configuration

### ISSUE THREAD

**Issue by dovecode** [pi-hole/pi-hole#1389]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
Teleporter zip file should contain static DHCP leases

**[BUG | ISSUE] Actual Behaviour:**
Teleporter zip doesn't contain any information about static DHCP leases

**[BUG | ISSUE] Steps to reproduce:**

- Access Web interface
- Log in
- Go to Settings
- Enable DHCP server
- Enter basic DHCP server config (IP range, router)
- Click Save (under Pi-Hole DHCP Server)
- Expand the DHCP leases section
- Add one or more static DHCP leases
- Expand Pi-hole Teleporter
- Export configuration

The downloaded ZIP file will contain the configuration (including basic DHCP configuration), but none of the static leases defined.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Thank you for the report, we'll investigate further.

**Comment by DL6ER** [comment]
I'm unable to reproduce your issue. I followed your steps one-by-one and get a ZIP file containing the file `04-pihole-static-dhcp.conf` which - in turn - contains all static DHCP leases.

![screenshot at 2017-04-17 21-33-14](https://cloud.githubusercontent.com/assets/16748619/25101701/7deac11e-23b5-11e7-96c7-ff6c7e24578f.png)

![screenshot at 2017-04-17 21-32-02](https://cloud.githubusercontent.com/assets/16748619/25101676/6d4aae3c-23b5-11e7-86d5-283b3e655d14.png)

**Comment by dovecode** [comment]
Strange. My ZIP only contains three files:

- setupVars.conf
- whitelist.txt
- wildcardblocking.txt

None of the other configuration files that you have are present when I export using the teleporter...

**Comment by DL6ER** [comment]
I can only imagine that your version of the web interface is not up-to-date. What does
```
pihole -v
```
tell you?

**Comment by dovecode** [comment]
I was moving this from one installation to another and don't have the old anymore. In my new, the teleporter does include the static leases, so I can only assume it was backlevel.

Closing issue.
