### ISSUE TITLE
DNSSEC does not work with sites that use Cloudflare

### ISSUE THREAD

**Issue by slamanna212** [pi-hole/pi-hole#1392]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_5_
This issue might be a non issue, i am just submitting it incase it is. All i might of had to do was run apt-get update and apt-get install
---

**[BUG | ISSUE] Expected Behaviour:**
DNSSEC lookup of a domain using cloudflare should reply with a good or bad response

**[BUG | ISSUE] Actual Behaviour:**
If the domain is hosted on Cloudflare , you get a Bogus DNSKEY response

Logs: 
```
Apr 17 18:28:13 dnsmasq[21935]: query[A] slamanna.com from 10.1.10.147
Apr 17 18:28:13 dnsmasq[21935]: forwarded slamanna.com to 209.244.0.4
Apr 17 18:28:13 dnsmasq[21935]: query[AAAA] slamanna.com from 10.1.10.147
Apr 17 18:28:13 dnsmasq[21935]: forwarded slamanna.com to 209.244.0.4
Apr 17 18:28:13 dnsmasq[21935]: dnssec-query[DNSKEY] slamanna.com to 209.244.0.4
Apr 17 18:28:13 dnsmasq[21935]: dnssec-query[DNSKEY] slamanna.com to 209.244.0.4
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is BOGUS DNSKEY
Apr 17 18:28:13 dnsmasq[21935]: validation result is BOGUS
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is 104.28.29.51
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is 104.28.28.51
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is BOGUS DNSKEY
Apr 17 18:28:13 dnsmasq[21935]: validation result is BOGUS
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is 2400:cb00:2048:1::681c:1d33
Apr 17 18:28:13 dnsmasq[21935]: reply slamanna.com is 2400:cb00:2048:1::681c:1c33
```

**[BUG | ISSUE] Steps to reproduce:**
Look up a domain hosted with cloudflare, like my personal domain: https://slamanna.com. DNSSEC is verified working on my domain. See here: https://dnssec-debugger.verisignlabs.com/slamanna.com

**[FIX]**
I actually already found the cause of this issue, the version of Dnsmasq that is installed by default in Raspbian Jessie is 2.72, which has this bug i described above. The issue is described here: https://serverfault.com/a/740529. The issue is fixed in version 2.73. Running apt-get update then apt-get install dnsmasq installed version 2.76 and fixed the issue for me. 

Log after above fix was applied:
```
Apr 17 18:44:06 dnsmasq[26084]: query[A] slamanna.com from 10.1.10.147
Apr 17 18:44:06 dnsmasq[26084]: forwarded slamanna.com to 2001:4860:4860::8888
Apr 17 18:44:06 dnsmasq[26084]: forwarded slamanna.com to 2001:558:feed::1
Apr 17 18:44:06 dnsmasq[26084]: forwarded slamanna.com to 209.244.0.4
Apr 17 18:44:06 dnsmasq[26084]: forwarded slamanna.com to 68.87.75.198
Apr 17 18:44:06 dnsmasq[26084]: dnssec-query[DS] com to 209.244.0.4
Apr 17 18:44:06 dnsmasq[26084]: dnssec-query[DNSKEY] . to 209.244.0.4
Apr 17 18:44:06 dnsmasq[26084]: reply . is DNSKEY keytag 14796, algo 8
Apr 17 18:44:06 dnsmasq[26084]: reply . is DNSKEY keytag 19036, algo 8
Apr 17 18:44:06 dnsmasq[26084]: reply com is DS keytag 30909, algo 8, digest 2
Apr 17 18:44:06 dnsmasq[26084]: dnssec-query[DS] slamanna.com to 209.244.0.4
Apr 17 18:44:07 dnsmasq[26084]: dnssec-query[DNSKEY] com to 209.244.0.4
Apr 17 18:44:07 dnsmasq[26084]: reply com is DNSKEY keytag 31697, algo 8
Apr 17 18:44:07 dnsmasq[26084]: reply com is DNSKEY keytag 27302, algo 8
Apr 17 18:44:07 dnsmasq[26084]: reply com is DNSKEY keytag 30909, algo 8
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is DS keytag 2371, algo 13, digest 2
Apr 17 18:44:07 dnsmasq[26084]: dnssec-query[DNSKEY] slamanna.com to 209.244.0.4
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is DNSKEY keytag 2371, algo 13
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is DNSKEY keytag 35273, algo 13
Apr 17 18:44:07 dnsmasq[26084]: validation result is SECURE
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is 104.28.28.51
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is 104.28.29.51
Apr 17 18:44:07 dnsmasq[26084]: query[AAAA] slamanna.com from 10.1.10.147
Apr 17 18:44:07 dnsmasq[26084]: forwarded slamanna.com to 209.244.0.4
Apr 17 18:44:07 dnsmasq[26084]: validation result is SECURE
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is 2400:cb00:2048:1::681c:1c33
Apr 17 18:44:07 dnsmasq[26084]: reply slamanna.com is 2400:cb00:2048:1::681c:1d33
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
This should be resolved with the latest version bump of `dnsmasq` from Debian.
