### ISSUE TITLE
updateGravity doesn't delete temp files

### ISSUE THREAD

**Issue by Silent-Hunter** [pi-hole/pi-hole#1393]
The cronjob "updateGravity" runs at 1:59 o'clock:

59 1    * * 7   root    PATH="$PATH:/usr/local/bin/" pihole updateGravity

Problem: updateGravity always creates several temp-files and doesn't delete them once the script is finished.

[23:09]root@bananapi:/$ ls /tmp
-rw------- 1 root root 0 Apr 9 01:59 tmp.b4Jc3rxVRm
-rw------- 1 root root 0 Apr 16 01:59 tmp.CjEzQ3qD1o
-rw------- 1 root root 0 Apr 9 01:59 tmp.DWk6nrFb2i
-rw------- 1 root root 0 Apr 9 01:59 tmp.EDLpO5MsrB
-rw------- 1 root root 0 Apr 9 01:59 tmp.eHy0H0YMMm
-rw------- 1 root root 0 Apr 2 01:59 tmp.fNwaj9OIBr
-rw------- 1 root root 0 Apr 2 01:59 tmp.kDYxxbRWAG
-rw------- 1 root root 0 Apr 2 01:59 tmp.M2J2fglLwh
-rw------- 1 root root 0 Apr 16 01:59 tmp.pGo9XG9WrW
-rw------- 1 root root 0 Apr 9 01:59 tmp.pOspMFdKeU
-rw------- 1 root root 0 Apr 16 01:59 tmp.tQjlNhxISb
-rw------- 1 root root 0 Apr 2 01:59 tmp.WXNH0XlQ7R
-rw------- 1 root root 0 Apr 2 01:59 tmp.XokYyitmob

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**
Delete all temp files once the script ends.

**[BUG | ISSUE] Actual Behaviour:**
Several 0-byte temp files stay in /tmp.

**[BUG | ISSUE] Steps to reproduce:**
1. install pihole.
2. wait until cronjob runs (or start script manually).
3. look at /tmp.

**(Optional) Debug token generated by `pihole -d`:**

`i9l6abyfd6`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
What temp files are left?

**Comment by Silent-Hunter** [comment]
[23:09]root@bananapi:/$ ls /tmp
-rw------- 1 root   root      0 Apr  9 01:59 tmp.b4Jc3rxVRm
-rw------- 1 root   root      0 Apr 16 01:59 tmp.CjEzQ3qD1o
-rw------- 1 root   root      0 Apr  9 01:59 tmp.DWk6nrFb2i
-rw------- 1 root   root      0 Apr  9 01:59 tmp.EDLpO5MsrB
-rw------- 1 root   root      0 Apr  9 01:59 tmp.eHy0H0YMMm
-rw------- 1 root   root      0 Apr  2 01:59 tmp.fNwaj9OIBr
-rw------- 1 root   root      0 Apr  2 01:59 tmp.kDYxxbRWAG
-rw------- 1 root   root      0 Apr  2 01:59 tmp.M2J2fglLwh
-rw------- 1 root   root      0 Apr 16 01:59 tmp.pGo9XG9WrW
-rw------- 1 root   root      0 Apr  9 01:59 tmp.pOspMFdKeU
-rw------- 1 root   root      0 Apr 16 01:59 tmp.tQjlNhxISb
-rw------- 1 root   root      0 Apr  2 01:59 tmp.WXNH0XlQ7R
-rw------- 1 root   root      0 Apr  2 01:59 tmp.XokYyitmob

**Comment by Mcat12** [comment]
What is the output of `pihole -g`?

**Comment by Mcat12** [comment]
I also see lots of empty temp files, perhaps a missing delete statement [here](https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L123)?

**Comment by Silent-Hunter** [comment]
pihole -g has following output (and again created new temp files)

[02:01]root@bananapi:~$ pihole -g
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting sysctl.org list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting zeustracker.abuse.ch list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting hosts-file.net list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 127422 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 103788 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 6 domains... done!
::: Blacklisting 30492 domains... done!
::: No wildcards used!
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
[ ok efresh lists in dnsmasq...[....] Restarting DNS forwarder and DHCP server: dnsmasq.
 done!
::: DNS service is running
::: Pi-hole blocking is Enabled

**Comment by dschaper** [comment]
Resolved.
