### ISSUE TITLE
[Question] [Windows] Bypassing Pi-Hole temporarily 

### ISSUE THREAD

**Issue by roots84** [pi-hole/pi-hole#1400]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[QUESTION]:**
First of all: **Great project guys (and / or girls)!** 
I find myself sometimes in the situation in which I need to bypass Pi-Hole temporarily for a few minutes. Going to the web interface, logging in and disabling it for everybody else as well is rather complicated and unwanted. So I'm usually changing my DNS to my routers IP for the moment - which also takes a few mouseclicks.
I got fed up yesterday and wrote myself a small tool that runs in my tray, switching the DNS with a single mouse click and indicates the status with the icon color (blue = Pi-Hole, red = Router).
Is there any interest by other people? If so, I would contribute it to the project for others.

![2017-04-25_17-20-40](https://cloud.githubusercontent.com/assets/11146296/25393351/8bca5d54-29db-11e7-916a-78b237854005.png)

**Comment by dschaper** [comment]
This may be something good to host on your GitHub repo and we can link to it from our Discourse to let people know about it.

**Comment by dschaper** [comment]
Closing due to lack of conversation.

**Comment by roots84** [comment]
Sorry, I was not keeping track of the issue. I just uploaded the code to GitHub. [https://github.com/roots84/DNS-Swapper/releases](https://github.com/roots84/DNS-Swapper/releases)
and also posted it to Discourse: [https://discourse.pi-hole.net/t/tool-dns-swapper/3241](https://discourse.pi-hole.net/t/tool-dns-swapper/3241)
