### ISSUE TITLE
[BUG][workaround] undefined symbol: FAMNoExists

### ISSUE THREAD

**Issue by snowly** [pi-hole/pi-hole#1401]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
0

** Expected Behaviour:**
To complete the installation :)

** Actual Behaviour:**
Pi-hole can't complete setup because lighttpd won't start

** Steps to reproduce:**
If system has package libfam0, lighttpd will fail to start.

*** Workaround ***
Replace libfam0 with gamin.

sudo apt-get install gamin

System: Ubuntu 16.04

The bug was reported a while ago:
https://bugs.launchpad.net/ubuntu/+source/lighttpd/+bug/1453463

**Comment by dschaper** [comment]
Thank you for the submission, can you please fill out the template that you were presented with?

**Comment by snowly** [comment]
I'm sorry, I didn't get what a template means in this case.

**Comment by technicalpyro** [comment]
when you create a new issue there is a bunch of text that you deleted and replaced with your own.  that is the bug report template you are being asked to fill out

**Comment by snowly** [comment]
technicalpyro, thank you. Fixed.

**Comment by technicalpyro** [comment]
@snowly no problem it just makes it easier for the devs and the rest of us to help you

**Comment by dschaper** [comment]
Okay, I've looked through the ticket on launchpad, and this seems to be a rare bug. This is the first time that the `FAM` issue has come up. I'm not sure if we want to add more dependent packages to the Pi-hole to cover it. I'll let the other developers weigh in with their thoughts on the matter.

**Comment by snowly** [comment]
We can check for package libfam0 during installation and suggest to install gamin if installation fails.

**Comment by dschaper** [comment]
According to http://packages.ubuntu.com/xenial/lighttpd `libgamin0` is a dependency already of the `lighttpd` package. Also noted that `libfam0` is a virtual package that is provided by `libgamin0`. And chasing the dependency tree, `gamin` is a dependency that is installed by `libgamin0`. 

So the dependent packages are there, and a fresh install via Ubuntu installed the `gamin` and `libgamin0` packages. 

This appears to be an Ubuntu bug, and adding the dependencies wouldn't change anything. Trying to see what further I can find on this issue.

**Comment by dschaper** [comment]
Alright, confirmed that this situation happens if you have `libfam0` installed prior to trying to use the automated installer. Which would require this to be installed on an existing system with FAM already installed. 

What are the issues that are involved in installing `gamin` over FAM, will this cause problems with existing software that needs FAM?

**Comment by snowly** [comment]
I don't know much about Gamin, but I found the flowing at Arch [wiki](https://wiki.archlinux.org/index.php/Gamin):

> It is newer and more actively maintained than FAM, maintains compatibility with FAM and can replace it in almost every case.

**Comment by Mcat12** [comment]
In what cases would this error occur? If it's a Ubuntu or distro specific error, it should be handled through them.

**Comment by dschaper** [comment]
Closing for stale external issue.

**Comment by angerangel** [comment]
Thank you, it solved also the same bug on Linux Mint 18.2

**Comment by akoerner** [comment]
Issue still exists in ubuntu 18.04...

**Comment by akoerner** [comment]
> Issue still exists in ubuntu 18.04...

fix is to install package gamin:
apt-get install gamin

**Comment by Maghoumi** [comment]
I faced this issue while installing Pi-hole on my Jetson Nano (which is running Ubuntu 18.04).

After the installation, the "Installation Complete" dialog wouldn't show up and nothing was working (`pihole -d` full of errors).

I had to follow these steps to get Pi-hole to work (simply reinstalling Pi-hole would not help):
1) Remove Pi-hole `pihole uninstall`
2) Purge lighttpd: `sudo apt remove --purge lighttpd`
3) Install `gamin`: `sudo apt install gamin`
4) Reinstall Pi-hole

Afterwards, everything is working as expected.

**Comment by rik-shaw** [comment]
I had to manually remove libfam0 before installing gamin. Also there was a bug with the pihole group already existing, but this has been fixed already in the development branch. But I had to manually remove the pihole group before re-running the install script.

**Comment by gstrauss** [comment]
FYI: A fix is making its way though Debian testing and should be available in buster-backports later this year.
https://bugs.launchpad.net/ubuntu/+source/lighttpd/+bug/1453463
https://salsa.debian.org/debian/lighttpd/-/merge_requests/18
