### ISSUE TITLE
Web interface refinement

### ISSUE THREAD

**Issue by anudeepND** [pi-hole/pi-hole#1402]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

[Feature request]
1. Add an option in the status are to show whether the internet is up or down. It can be done by by using netcat `nc -w 3 -z google.com 80
echo $?`
This means check if port 80 on google.com is open, and timeout after 3 seconds. If connection was successful, it will print 0, and if it failed, it will print 1.

2. When password is set for the web interface, going to http://pi.hole/admin lands you in the dashboard, instead of this display the login page. So other users cannot see dashboard (like total number of queries, number of blocked domains etc.)

**Comment by DL6ER** [comment]
1. I think you rather mean something like
 ```
nc -w 3 -z google.com 80 &> /dev/null; echo $?
```

2. We show the dashboard with less details for anyone which does not know the password. Do you ask for preventing access without password altogether?

**Comment by anudeepND** [comment]
> nc -w 3 -z google.com 80 &> /dev/null; echo $?

> 

Yes

> We show the dashboard with less details for anyone which does not know the password. Do you ask for preventing access without password altogether?

> 
Exactly, there is a similar option in dd-wrt routers

**Comment by dschaper** [comment]
What is the benefit to having an internet check?

**Comment by anudeepND** [comment]
I'm on a DSL internet connection (some other users too), sometimes internet will be down and other problems with DSL. So it may help us to know whether the problem is with the pi or the internet....

**Comment by PromoFaux** [comment]
>`nc -w 3 -z google.com 80 echo $?`

But then, how often do we check? What if the user has `google.com` blacklisted? This would also have the undesirable side effect of throwing the statistics off on the front page, as it would count as a DNS lookup. Lets say we checked every 5 mins, that's an additional 288 queries per day.

Maybe we could do it by testing connectivity to 8.8.8.8 directly... Just thinking out oud.
