### ISSUE TITLE
pi-hole v2.13.2 / Spotify web

### ISSUE THREAD

**Issue by MacGovery** [pi-hole/pi-hole#1409]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**

Using the Spotify webplayer (https://open.spotify.com/browse) is not possible with latest pihole release.
**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

Try to listen to https://open.spotify.com/browse - vanilla pihole install, no additional list
https://discourse.pi-hole.net/t/why-doesnt-spotify-work-using-pi-hole/255 - does not work

**Comment by technicalpyro** [comment]
it works just fine here for me below is an excerpt of my pihole log from when i accessed the player 

```
May  1 11:17:30 dnsmasq[2307]: query[A] spclient.wg.spotify.com from 172.16.1.103
May  1 11:17:30 dnsmasq[2307]: forwarded spclient.wg.spotify.com to 208.67.220.220
May  1 11:17:30 dnsmasq[2307]: forwarded spclient.wg.spotify.com to 208.67.222.222
May  1 11:17:30 dnsmasq[2307]: query[A] open.spotify.com from 172.16.1.103
May  1 11:17:30 dnsmasq[2307]: forwarded open.spotify.com to 208.67.220.220
May  1 11:17:30 dnsmasq[2307]: reply spclient.wg.spotify.com is 
May  1 11:17:30 dnsmasq[2307]: reply weblb-wg.dual-gslb.spotify.com is 104.154.127.47
May  1 11:17:30 dnsmasq[2307]: reply open.spotify.com is 
May  1 11:17:30 dnsmasq[2307]: reply weblb-wg.dual-gslb.spotify.com is 104.154.127.47
May  1 11:17:31 dnsmasq[2307]: query[A] api.spotify.com from 172.16.1.103
May  1 11:17:31 dnsmasq[2307]: forwarded api.spotify.com to 208.67.220.220
May  1 11:17:31 dnsmasq[2307]: query[A] dealer.spotify.com from 172.16.1.103
May  1 11:17:31 dnsmasq[2307]: forwarded dealer.spotify.com to 208.67.220.220
May  1 11:17:31 dnsmasq[2307]: reply api.spotify.com is 
May  1 11:17:31 dnsmasq[2307]: reply weblb-wg.dual-gslb.spotify.com is 104.154.127.47
May  1 11:17:31 dnsmasq[2307]: reply dealer.spotify.com is 
May  1 11:17:31 dnsmasq[2307]: reply weblb-wg.dual-gslb.spotify.com is 104.154.127.47

```

**Comment by jacobsalmela** [comment]
Did you wait for cache to expire or flush your cache and then try again?

**Comment by MacGovery** [comment]
Sorry for the late reply. I can't access the pihole right now, but i will paste debug logs when I'm able to. Installed, fluashed cache on all devices and using Opendns with DNSSEC in pihole.

**Comment by dschaper** [comment]
Can you replicate this on the latest release of Pi-hole?

**Comment by technicalpyro** [comment]
not sure about @MacGovery  however i have tested this on both of my setups one which uses DNSsec one that does not.  i cannot reproduce this i have whitelisted `spclient.wg.spotify.com` but havent needed to whitelist anything else

**Comment by dschaper** [comment]
@technicalpyro Thanks as always for the help!

**Comment by jacobsalmela** [comment]
@MacGovery I'm also curious if the latest version of Pi-hole fixes this for you.  

If not, are you using the paid or free version of Spotify?

**Comment by MacGovery** [comment]
@jacobsalmela Hey I can't test it right now as I'm not at home for the next weeks. 
I'm using the free version of Spotify, and manually setting this filter in uBlock does work for me: https://help.getadblock.com/support/solutions/articles/6000167245-i-m-hearing-audio-ads-in-spotify-s-web-player
When I'm home i will update pihole, set this filter, see if this work and post my reply here.

**Comment by jacobsalmela** [comment]
@MacGovery Please also verify that  `open.spotify.com` and `play.spotify.com` are not being blocked by Pi-hole.

**Comment by Mcat12** [comment]
@MacGovery

**Comment by MacGovery** [comment]
Sorry. Test with the new Version. Works now.
