### ISSUE TITLE
Web Admin query log, whitelist and blacklist not working

### ISSUE THREAD

**Issue by humbertooliveira** [pi-hole/pi-hole#1410]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
The Query Log page should display the most recent queries handled by PiHole. The Whitelist and Blacklist form should allow the addition of new domains or wildcard domains.

**[BUG | ISSUE] Actual Behaviour:**
The QueryLog table is empty, no errors or message are displayed. Tested on Chrome, Edge and Firefox. Seems to be a problem with the admin php or js code, I can tail the log using pihole -t and watch the queries been processed in real time.

The same thing happens with the blacklist and whitelist interface, I can add both via pihole -b or pihole -w and they work as expected, but the admin interface is empty in both cases.

I'm running Pi-Hole version 2.13.2, web interface 2.5.2 on Ubuntu 16.04 LTS Hyper-V VM with 1GB of ram.

This virtual machine is dedicated to Pi-hole.

**[BUG | ISSUE] Steps to reproduce:**

- Fresh install of Pi-hole on Ubuntu 16.04 LTS Hyper-V Vm
- Access querylog, whitelist or blacklist page
-
-

**(Optional) Debug token generated by `pihole -d`:**

`1qbwpx0qwenan`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Found the log under the ticket `1qbwpx0qwe`, taking a look...

**Comment by dschaper** [comment]
Are you able to access the API at the `http://pi.hole/admin/api.php` endpoint and get back any numbers that show activity?

**Comment by humbertooliveira** [comment]
Yes, both via pi.hole domain or direct via IP.

This is the result I get:

{"domains_being_blocked":"104,559","dns_queries_today":"5,273","ads_blocked_today":"1,105","ads_percentage_today":"21.0"}



Até mais,

*Humberto Oliveira*
*http://holiveira.com <http://holiveira.com/>*




2017-05-01 17:05 GMT-03:00 Dan Schaper <notifications@github.com>:

**Comment by dschaper** [comment]
We just pushed a new release, can you try running `pihole -up` and see if you get any errors on the update or a resolution to the issue?

**Comment by humbertooliveira** [comment]
I ran pihole-up and updated to Pi-hole Version v3.0, Web Interface Version v3.0 FTL Version v2.6, but the problems continue. Both whitelist and blacklist continue without data.

Now on the Query Log page I see a "Processing..." floating banner but nothing is displayed. Checking the console on Chrome Dev Tools I see a javascript error on queries.js:

```
queries.js:170 Uncaught ReferenceError: moment is not defined
    at render (queries.js:170)
    at jquery.dataTables.min.js:18
    at Object.b.fnGetData (jquery.dataTables.min.js:12)
    at B (jquery.dataTables.min.js:17)
    at Ha (jquery.dataTables.min.js:24)
    at N (jquery.dataTables.min.js:16)
    at jquery.dataTables.min.js:48
    at i (jquery.dataTables.min.js:35)
    at Object.success (jquery.dataTables.min.js:35)
    at j (jquery.min.js:2)

```

**Comment by dschaper** [comment]
Okay, with the changes in back ends and some other updates it may help to grab another debug run. Can you do another `pihole -d` and we'll take a look at that.

**Comment by Mcat12** [comment]
Does `/var/www/html/admin/scripts/vendor/moment.min.js` exist?

**Comment by humbertooliveira** [comment]
Yes, moment.min.js exists in this path. The new debug token is mvsl63ns7o

**Comment by Mcat12** [comment]
Try flushing your browser's cache. Does the script show up under the Sources tab in the dev tools?

**Comment by humbertooliveira** [comment]
I flushed the cache but the error continues. Looking at the sources tab in chrome dev tools, the moment.min.js is not included in the /admin/scripts/vendor folder. 

And when I try to access the file directly via browser I get a blank page where I should see the contents of the js file.

For some reason the moment.js is not being loaded befor the queries.js, causing the error "moment is not defined.

**Comment by Mcat12** [comment]
Do you see a request for it in the lighttpd log? `/var/log/lighttpd/access.log` or an error? `/var/log/lighttpd/error.log`

**Comment by humbertooliveira** [comment]
No, I cleaned the access.log and opened the queries.php file again. The only request in the log is  this

`1493676167|192.168.1.40|GET /admin/queries.php HTTP/1.1|200|20811`

**Comment by humbertooliveira** [comment]
And there's no error on the error.log.

**Comment by humbertooliveira** [comment]
Looking on the network tab in chrome dev tools, moment.min.js is on the list as requested by queries.php. But when I click in it I see no content like the other js files. All I get is the chrome default "This request has no preview available" message.

**Comment by Mcat12** [comment]
What are the response headers?

**Comment by humbertooliveira** [comment]
**These are the response headers**

```
HTTP/1.1 200 OK
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
Vary: Accept-Encoding
Content-Encoding: gzip
Last-Modified: Mon, 24 Apr 2017 00:57:14 GMT
ETag: "2058016712"
Content-Type: application/javascript
Accept-Ranges: bytes
Content-Length: 0
Date: Tue, 02 May 2017 00:04:11 GMT
Server: lighttpd/1.4.35
```

**And these are the request headers:**

```
GET /admin/scripts/vendor/moment.min.js HTTP/1.1
Host: 192.168.1.40
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Accept: */*
Referer: http://192.168.1.40/admin/queries.php
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4
Cookie: PHPSESSID=6kjtfbqm6jvpt65g04skqjomm0
```

**Comment by Mcat12** [comment]
Check the permissions on that file (`ls -l` or `ll`).

**Comment by humbertooliveira** [comment]
These are the permissions for all the files in the  scripts/vendor directory:

```
humberto@pihole:/var/www/html/admin/scripts/vendor$ ls -lla
total 840
drwxr-xr-x 2 root root   4096 May  1 18:23 .
drwxr-xr-x 4 root root   4096 Apr 23 21:57 ..
-rw-r--r-- 1 root root   9222 Apr 23 21:57 app.min.js
-rw-r--r-- 1 root root 192595 Apr 23 21:57 Chart.bundle.min.js
-rw-r--r-- 1 root root   1960 Apr 23 21:57 dataTables.bootstrap.min.js
-rw-r--r-- 1 root root   2636 Apr 23 21:57 html5shiv.min.js
-rw-r--r-- 1 root root   2966 Apr 23 21:57 jquery.confirm.min.js
-rw-r--r-- 1 root root  82638 Apr 23 21:57 jquery.dataTables.min.js
-rw-r--r-- 1 root root   2669 Apr 23 21:57 jquery.inputmask.extensions.js
-rw-r--r-- 1 root root  90539 Apr 23 21:57 jquery.inputmask.js
-rw-r--r-- 1 root root  84345 Apr 23 21:57 jquery.min.js
-rw-r--r-- 1 root root 240027 Apr 23 21:57 jquery-ui.min.js
-rw-r--r-- 1 root root   1085 Apr 23 21:57 LICENSE
-rw-r--r-- 1 root root  61317 Apr 23 21:57 moment.min.js
-rw-r--r-- 1 root root  42119 Apr 23 21:57 qrcode.php
-rw-r--r-- 1 root root   4377 Apr 23 21:57 respond.min.js
```

**Comment by Mcat12** [comment]
What is the output of `curl -i http://localhost/admin/scripts/vendor/moment.min.js`?

**Comment by humbertooliveira** [comment]
It returns the code of minified moment.min.js.

I read the source code of the queries.php as generated by chrome and realized both moment.min.js and queries.js are outside the closing html element, like this:

´´´

<script src="scripts/vendor/jquery.min.js"></script>
<script src="scripts/vendor/jquery-ui.min.js"></script>
<script src="style/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="scripts/vendor/app.min.js"></script>

<script src="scripts/vendor/jquery.dataTables.min.js"></script>
<script src="scripts/vendor/dataTables.bootstrap.min.js"></script>
<script src="scripts/vendor/Chart.bundle.min.js"></script>

<script src="scripts/pi-hole/js/footer.js"></script>

</body>
</html>

```
<!-- ./wrapper -->
<script src="scripts/vendor/jquery.min.js"></script>
<script src="scripts/vendor/jquery-ui.min.js"></script>
<script src="style/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="scripts/vendor/app.min.js"></script>

<script src="scripts/vendor/jquery.dataTables.min.js"></script>
<script src="scripts/vendor/dataTables.bootstrap.min.js"></script>
<script src="scripts/vendor/Chart.bundle.min.js"></script>

<script src="scripts/pi-hole/js/footer.js"></script>

</body>
</html>

<script src="scripts/vendor/moment.min.js"></script>
<script src="scripts/pi-hole/js/queries.js"></script>
```

This way both scripts are outside the DOM and probably causing problems with the moment object used in queries.js

**Comment by Mcat12** [comment]
Script tags can be outside the ending `</html>` tag. The `queries.js` script is loading, right?

**Comment by humbertooliveira** [comment]
It looks like the moment.js Browser declaration method is not working, probably to force to use a package manager. Found [this question on stackoverflow ](http://stackoverflow.com/questions/24520828/moment-js-moment-is-undefined) with a similar issue.

I edited the queries.js files and removed the moment.format function you're using to convert from unix timestamp and the page worked correctly, all the logs where displayed as intended.

Perhaps it's a good idea to write a simple function to convert from unix timestamp and abandon this library.

**Comment by humbertooliveira** [comment]
I changed the row

` { "width" : "20%", "render": function (data, type, full, meta) { if(type === "display"){return moment.unix(data).format("Y-MM-DD HH:mm:ss z");}else{return data;} }},`

to 

`{ "width" : "20%", "render": function (data, type, full, meta) { if(type === "display"){return data[0];}else{return data;} }},`

and it worked

**Comment by Mcat12** [comment]
The issue is that the web server is not returning the moment.js code for some reason. You can see the response headers include this:
```
Content-Length: 0
```
So it's not returning any code.

**Comment by humbertooliveira** [comment]
Yes, as I said before I can open the moment.min.js in chrome but it loads no code, only a blank page.

**Comment by humbertooliveira** [comment]
The same thing happens with the list.js that is the last row of lists.php, after the `</html>` as well.

This is the reason why no data is shown in whitelist and blacklist.

**Comment by Mcat12** [comment]
The underlying issue is that something is causing your web server to not send that file, and it's best to try and find out why so that it doesn't happen with any other files.

**Comment by humbertooliveira** [comment]
I'm not familiar with lighttpd but it seems like compression gone wrong. 

The response says the content-encoding is gzip, so the js file is being compressed. Is there an easy way to disable the compression on lighttpd so I can test this therory?

**Comment by Mcat12** [comment]
I think you can disable it by removing `mod_compress` from the list of modules in `/etc/lighttpd/lighttpd.conf`.

**Comment by Mcat12** [comment]
Try clearing out `/var/cache/lighttpd/compress/`

**Comment by Mcat12** [comment]
https://redmine.lighttpd.net/boards/2/topics/6634

**Comment by Mcat12** [comment]
If that doesn't work, try restarting lighttpd via `sudo service lighttpd restart`.

**Comment by humbertooliveira** [comment]
It worked! Both bugs are gone, the whitelist, blacklist and querylog are displaying correctly

I removed the mod_compress and cleared the cache folder.

**Comment by Mcat12** [comment]
Try adding the compress module back in.

**Comment by humbertooliveira** [comment]
I added the mod_compress and restarted the service, cleared the cache again and the admin keeps working correctly for some reason.

**Comment by Mcat12** [comment]
It must have been a cached compressed version of the file having a length of zero for some reason.

**Comment by humbertooliveira** [comment]
Thanks for your help!
