### ISSUE TITLE
Router config doesnt accept RPI IP as DNS

### ISSUE THREAD

**Issue by zaqstevenson** [pi-hole/pi-hole#1411]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

**[QUESTION | OTHER]:**
Hi. The issue just might be external, but I am willing to give it a try :)
Setup is on RPI 3 with Raspbian. Running Windows 7 machine with DNS configuration directly on it.
Router: Ubee  EVW3226_1.0.16
RPI ifconfig:
eth0      Link encap:Ethernet  HWaddr b8:27:eb:4f:b1:3e
          inet addr:192.168.0.250  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::c28a:e52a:7e66:df01/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10029 errors:0 dropped:50 overruns:0 frame:0
          TX packets:8650 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1168402 (1.1 MiB)  TX bytes:3419251 (3.2 MiB)

**[BUG | ISSUE] Expected Behaviour:**
Want to move DNS config to the router according to https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245

**[BUG | ISSUE] Actual Behaviour:**
Router does not recognise RPI IP as valid thus not allowing to change DNS to RPI

**[BUG | ISSUE] Steps to reproduce:**
Entering DNS: https://ibb.co/fVQpt5 
Pressing Save: https://ibb.co/fZMvY5 
Changing to publicly available DNS doesnt generate that problem (like 8.8.8.8)
**(Optional) Debug token generated by `pihole -d`:**
n0t3ds617o

**Comment by dschaper** [comment]
Looks like that router has a block on using internal addresses for DNS servers. You may want to come by https://discourse.pi-hole.net and see if there are other users with the same router that can give a few hints and tips. That's where a lot of the discussion happens for issues that aren't directly related to the code happens.

**Comment by zaqstevenson** [comment]
Thanks, there is a lot to go through on the website, but I will check it.
Regarding your comment on the router - basic  working config is using DNS 192.168.0.1 (but maybe it is an exception)
![r3](https://cloud.githubusercontent.com/assets/15061212/25596324/d38636c6-2ec8-11e7-8509-40c72e0c5f0e.png)

**Comment by dschaper** [comment]
Feel free to open a new topic on the Discourse, that's what it's there for and if you have a duplicate issue we can just link the two. No need to deep dive the site to research if the problem has been asked/answered.
