### ISSUE TITLE
Updater may not account for non-admin page installs.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1412]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---
**[QUESTION]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

Taken from https://twitter.com/HermanHarperink/status/859166946629214209

Updater seems to error out with unable to find admin repo.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
![c-xfx5lw0aabk2e](https://cloud.githubusercontent.com/assets/2782850/25596978/f664c2d6-2e80-11e7-8181-5f4fa97f4bf9.jpg)

**Comment by Mcat12** [comment]
#1347 was fixed in v3.0, but the updater uses the current version of the code (which isn't fixed).

**Comment by dschaper** [comment]
https://tricorder.pi-hole.net/5vxvx8npu7/ for internal review. (Looks to be the older debugger.) Will suggest a `pihole -r` and then `pihole -up`.

**Comment by dschaper** [comment]
Suggested a manual pull of the `/etc/.pihole` repo and then repair, followed by the update.

**Comment by dschaper** [comment]
Suggested method was successful.
