### ISSUE TITLE
Installation of v3 on a freshly installed Debian Jessie x64 server - no password set

### ISSUE THREAD

**Issue by Ardakilic** [pi-hole/pi-hole#1414]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] The issue I am reporting can be *replicated*
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_4_ I know PHP, but I'm sure my issue isn't related the the PHP related sides of the project.

---

After v3 fresh installation on Debian remote server, I could access to admin interface without password. I've been using Pi-hole for months with my local setup, so I'm not a newbie here about usage of the application.

I'm using Debian Jessie as my remote VPS, only [SoftEtherVPN](https://github.com/SoftEtherVPN/SoftEtherVPN) was already installed, but it shouldn't affect this behaviour.

Initial installation failed because my VPS didn't have `dialog` app installed. so I installed it.

After that, I re-run the installation one-liner, then I got “RTNETLINK answers: File exists” issue during setup, but this was an issue I also got on my Orange Pi Zero (which also runs ARMBian Debian distro), so I've assumed It's a bug in Debian, and re-run the installation, this time it worked. It's possible it's not remotely related, but I'm mentioning anyways.

All steps of the setup went smoothly after this, the dialog screen provided me with the auto generated password.

**[BUG | ISSUE] Expected Behaviour:**
http://remoteip/admin should ask password for critical sections after fresh installation

**[BUG | ISSUE] Actual Behaviour:**
http://remoteip/admin is running without admin password even though dialog provided me with one, administration interface was open to public. I had to `pihole -a -p` to set a new password.

I have another pi-hole running on my local network on Orange Pi Zero, if that would matter (maybe cookies somehow messed up?).

**[BUG | ISSUE] Steps to reproduce:**

* Install pi-hole v3 to a freshly VPS (I'm using on HostUS if that would matter) Debian Jessie after it .
* Administration panel password is not set.

**(Optional) Debug token generated by `pihole -d`:**
Well, everything is running nice for now after setting a password, so I guess it's not needed / won't be usable

Thanks in advance, and thanks again for developing such a great software!

**Comment by Mcat12** [comment]
What are the contents of `/etc/pihole/install.log`?

**Comment by technicalpyro** [comment]
i can confirm this as having happened to me as well i merely used my local config file to repair it  I have since run updates so son't have it in the logs

**Comment by Ardakilic** [comment]
@Mcat12 nothing fancy:

```
::: Checking if user 'pihole' exists...
::: User 'pihole' doesn't exist. Creating...
:::
::: Installing scripts from /etc/.pihole... done.
:::
::: Installing configs from /etc/.pihole...
:::    Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page...
:::     Creating directory for blocking page
 done!
:::
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
:::
::: Installing latest logrotate script... done!
:::
::: Downloading latest version of FTL...
:::  Detected x86_64 architecture
:::  Installing FTL... transferred... done.
:::
::: No active firewall detected.. skipping firewall configuration.
```

Today, I'll create a new VPS from scratch and try again. I'll let you guys know

@technicalpyro I also saw the exact same message, with the password, however admin interface was accessible without password, like it was not set.

**Comment by dschaper** [comment]
Did your browsing session end between the new and old? Just wondering if the session cookie from the old session may have been still active and allowed access that way.

**Comment by dschaper** [comment]
Or I could be completely wrong, this isn't my area of development.

**Comment by Ardakilic** [comment]
@dschaper this was a clean installation from scratch. It was the first time I navigated to pi-hole admin panel at that server.

**Comment by technicalpyro** [comment]
Assuming you mean entire web interface and not just the main graph and top bar of stats yes? Nothing personal but they have been confused before lol

**Comment by Ardakilic** [comment]
@technicalpyro I've been using pi-hole on my local network for half a year. Anyone public could flush pihole.log (incognito tab) on this new vps, so I believe not 😀

**Comment by technicalpyro** [comment]
Fair point when I did my reinstall this evening I did not check the web interface before using the cli to set my usual secure password

**Comment by DL6ER** [comment]
@Ardakilic looking at the content of your `/etc/pihole/install.log` it does not seem to be complete. So something might have happened *before* the password could be set.

**Comment by Ardakilic** [comment]
@DL6ER Well, first time installation failed as I've mentioned earlier with an error saying "RTNETLINK answers: File exists", then run the setup script again and the 2nd time it worked. Maybe the second time installation didn't flush|backup the old logs and|or overwrite ? (I don't know how it's handled on script's end to be honest).

**Comment by technicalpyro** [comment]
> @DL6ER Well, first time installation failed as I've mentioned earlier with an error saying "RTNETLINK answers: File exists", then run the setup script again and the 2nd time it worked. Maybe the second time installation didn't flush|backup the old logs and|or overwrite ? (I don't know how it's handled on script's end to be honest).

this occurred to me when i set one up once but happened when i tried to set the tun0 interface as the static ip for pihole whereas on my system it had to be venet0

**Comment by dschaper** [comment]
`RTNETLINK answers: File exists` is an error that occurs when trying to change or set and IP for an interface. It's a problem that we are running into on non-Raspberry Pi installs, as Raspbian uses a non-standard way of setting up static IP addresses. Resolving this issue is problematic because of the number of ways to set static IP addresses with the different dameons used on various distributions. There's a long discussion on that going on, and seeing what the need is to be adjusting IP addresses for the users if they are not running Raspbian. 

When the script is run a second time through, the static is already set in the `/etc/dhcpcd.conf` file and the IP functions are bypassed. And you are correct, we do not back up previous installation logs on each run, they are written new. 

This doesn't really help with the problem at hand I believe, but this should shed a little light on the RTNETLINK errors. The script halts right at that point and drops you back to shell. We may need to look at just not trying to configure static IP addresses and allow the user to set that in itself. But that's another issue and more discussion.

**Comment by dschaper** [comment]
Confirmed. Spin up DO Jessie, run curl install. No password is present in setupVars.conf.

https://pastebin.com/AddtEF5B

**Comment by dschaper** [comment]
We're discussing a couple of different ways to resolve this. For now, if you spin up a new installation, please check and set a password if none was installed.

**Comment by technicalpyro** [comment]
will this fix affect all OS's just spun up OSMC for troubleshooting and it is present there as well

**Comment by Fourdee** [comment]
@dschaper @DL6ER 
> https://github.com/Fourdee/DietPi/issues/918#issuecomment-299158539

**Comment by dschaper** [comment]
New fix to be pushed out today to remedy the situation. Just waiting final approval.

**Comment by Fourdee** [comment]
Its very rare for something to impress me beyond expectations, but when it does, deserves acknowledgement.

@DL6ER: Great work on PiHole FTL. Extremely efficient minimal CPU/RAM usage. Really impressive code and runs like a dream 👍

@PromoFaux @jacobsalmela ^^ hes a keeper 😉

**Comment by dschaper** [comment]
Fixed in Master

**Comment by Ardakilic** [comment]
@dschaper Awesome! Thanks for the heads-up! 🎉

**Comment by keithelder** [comment]
Maybe this will help someone. I ran into the same error. During setup I selected both IPV4 and IPV6. I deselected IPV6 and the problem was fixed.
