### ISSUE TITLE
Enable Button without function after disabling Pi-hole

### ISSUE THREAD

**Issue by Gebrauchsspur** [pi-hole/pi-hole#1424]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Actual Behaviour:**
After disabling Pi-hole with the new V3 Admin Console, a reactivation with the "Enable" button fails. There ist simply nothing happen then I click on it. Doing the same with the pihole enable command over SSH works normal.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token.

**Comment by Gebrauchsspur** [comment]
Okay, here is my debug token: **096yy7vypf**
Hope it helps.

**Comment by Mcat12** [comment]
@Gebrauchsspur Is this still an issue? Sorry for not following up.

**Comment by Gebrauchsspur** [comment]
@Mcat12 Hey, thanks for your response! I think it can be closed. I have runnig a lot of browser addons and the malfunction seems to be a result of blocking things like WebRTC etc. 

Thank you!
