### ISSUE TITLE
pihole 3 slower with FTL?

### ISSUE THREAD

**Issue by jwilczek** [pi-hole/pi-hole#1425]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
FTL is supposed to be make pihole web UI faster.

**[BUG | ISSUE] Actual Behaviour:**
After updating, pihole web UI is much, much slower and unresponsive. I am running on a Raspberry Pi 2B and viewing in Chrome.

The charts Query Types over Time and Forward Destinations over Time never load.

**[BUG | ISSUE] Steps to reproduce:**
- Running on a Raspberry Pi 2B and viewing in Chrome.
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`59wdw9hx2j`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Looking at the debug log, I'm seeing very high ping (2000ms) when pinging `192.168.1.1`. It's possible this may be a weird once-off occurrence, or could be symptomatic of a bigger issue (a bad WiFi network, a Raspberry Pi with a runaway process, etc).

On top of this, there's a timeout occurring when attempting to access `/var/www/html/admin/scripts/pi-hole/php/data.php` which assists with providing the output you see on the front dashboard. Could you run `pihole -r`, repair your installation and see if this resolves the issue?

If that doesn't resolve the issue, could you do the following?

* Provide the final two lines of output from: `ping -c 5 192.168.1.1`
* Provide a screenshot of everything above the green bar in `htop`

Thanks!

**Comment by GLaDOSDan** [comment]
I'm also having the exact same issue. The main queries over time graph is incredibly laggy in Chrome 58.0.3029.81 on Windows 10. I also can't see the "Query Types over Time" or "Forward Destinations over Time" graphs, they simply appear as blank white squares (with no axis either)

![image](https://cloud.githubusercontent.com/assets/920215/25657470/e9729fe6-2ff5-11e7-96a1-4a0dbe7c9cfa.png)

Debug log code: 8sq5imldi1

I've also tried repairing the install with pihole -r and also completely done an uninstall and reinstall to no avail. I'm not running out of memory on the server side and CPU load is fine.

**Comment by jwilczek** [comment]
@GLaDOSDan - What was your solution? Did you just reboot the RPi? It looks like your setup is exactly the same as mine.

**Comment by jwilczek** [comment]
@WaLLy3K (at work now, will run these steps when I get home). In the meantime...

The RPi is cable-connected to a modern router. A bad WiFi network seems unlikely.

**Comment by DL6ER** [comment]
> Completely rebooting the DNS container for the 3rd time now seems to have fixed both the graphs and the responsiveness issues in the browser. Everything seems okay now. Very strange.

No, this is not strange at all. What you have seen is an cache issue in your browser - unfortunately, many browsers (like Chrome) do *not* clear the Javascripts it has cached when you request that the cache should be cleared. Instead, the old scripts fired a series of requests that overwhelmed PHP on your machine which, eventually, lead to all the strange behavior.

At least that is how I interpret it.

**Comment by technicalpyro** [comment]
to reload page without cached items use the combo of [CTRL]+[SHIFT]+[r]

**Comment by GLaDOSDan** [comment]
@DL6ER Agreed, this seems like the likely cause of the issue. I'd assumed with a major version release there'd probably be something akin to "?v=3.0" after the CSS/JS, but that doesn't seem to be the case.

I think you're right here in saying that it is a caching issue, and that rebooting the container the pi-hole was on and then it suddenly working was merely a coincidence. Perhaps it's worth simply adding changable tokens to the end of included javascript/stylesheets to prevent these kinds of issues with future updates?

**Comment by DL6ER** [comment]
@technicalpyro Right, I *completely* forgot about that.

Depending on the machine and browser, I have seen three possibilities for this:
- Ctrl + F5
- Ctrl + Shift + R
- Cmd + Shift + R (Mac equivalent)

@GLaDOSDan We thought about this back and forth and first had it set up like this. The drawback was, however, that the `JS` files (no critical `CSS` changes were involved) became just huge (like > 250 lines for the dashboard), because the syntax of the API improved as well. It was merely un-maintainable and we decided that it would not be a problem to "just change it" when we are anyhow at a big transition.

Might not have been the best idea, but most issues should magically fix themselves, so I'm also not worried too much.

**Comment by dschaper** [comment]
:taco:

**Comment by jwilczek** [comment]
I played  with this for about 2 hours. I tried multiple combos of Ctrl + F5, Ctrl + Shift + R, etc. Even tried clearing cache through chrome. What ended up working was a reboot of my desktop and then a Ctrl + Shift + R.

Sorry for not thinking about the cached files.

Thanks for the awesome work - keep it up!!!
