### ISSUE TITLE
It does not connect

### ISSUE THREAD

**Issue by Unr3al2** [pi-hole/pi-hole#1427]
Hello,
Pihole -r does not help.
It does not download data.
I use chroot on synology. Previous version was working. I installed everything again and again the same problem.

![image](https://cloud.githubusercontent.com/assets/12681095/25657856/355a6074-3000-11e7-9af6-d64146720449.png)

Your debug token is : 29c6x3t5nr Please make a note of it.

**Comment by dxm765** [comment]
I had the same issue, I ran pihole -r, rebooted, and had to clear my cache in Chrome

**Comment by Unr3al2** [comment]
Continue the same problem.

**Comment by japo227** [comment]
I'm having exactly the same problem, tried to reconfigure it but still the same...

**Comment by PromoFaux** [comment]
Hey guys, Synology NAS is not officially supported, but we have a very active thread about it on our discourse forums:
https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289,

**Comment by Unr3al2** [comment]
It works.

karel 👍 
Just updated to Pi-hole v3.0.
When I go to the webinterface Pihole-FTL is not loaded. Also on the cli Pihole-FTL is not loaded.
When I start it manually in Chroot with this command: "/usr/bin/pihole-FTL" it does load. The fix is to add 2 new lines to the S99pihole.sh script. It now looks like:
!/bin/sh
. /etc.defaults/rc.subr
case $1 in
start)
/var/packages/debian-chroot/scripts/start-stop-status start
chroot /volume1/@appstore/debian-chroot/var/chroottarget service cron start
chroot /volume1/@appstore/debian-chroot/var/chroottarget service dnsmasq start
chroot /volume1/@appstore/debian-chroot/var/chroottarget service lighttpd start
chroot /volume1/@appstore/debian-chroot/var/chroottarget service pihole-FTL start
;;
stop)
chroot /volume1/@appstore/debian-chroot/var/chroottarget service cron stop
chroot /volume1/@appstore/debian-chroot/var/chroottarget service dnsmasq stop
chroot /volume1/@appstore/debian-chroot/var/chroottarget service lighttpd stop
chroot /volume1/@appstore/debian-chroot/var/chroottarget service pihole-FTL stop
/var/packages/debian-chroot/scripts/start-stop-status stop
;;
restart)
$0 stop
sleep 1
$0 start
;;
*)
echo "Usage: $0 start|stop|restart"
;;
esac
