### ISSUE TITLE
"Forward Destinations over Time" graph malformed with lots of resolvers

### ISSUE THREAD

**Issue by CorralPeltzer** [pi-hole/pi-hole#1428]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG | ISSUE] Expected Behaviour:**

Good looking and readable graph.

**[BUG | ISSUE] Actual Behaviour:**
![image](https://cloud.githubusercontent.com/assets/6959494/25692323/eb9dfed0-30a1-11e7-8c3c-9e0642dc7e9f.png)

**[BUG | ISSUE] Steps to reproduce:**

- Add more than 4 forward destinations and use them for a while.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Saiboogu** [comment]
If I disable the boxed layout option and make the browser window wide enough (Greater than 2/3 of a 2560x1440 display) it becomes much clearer. 
![image](https://cloud.githubusercontent.com/assets/2211971/25881328/45c23860-350a-11e7-96f0-970834dfd0bd.png)

Maybe if the key could be shrunk somehow, the graph would have enough room on smaller screen sizes.   Make the key an icon to hover over for the list?

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #502](https://github.com/pi-hole/AdminLTE/issues/502) via [**ZenHub**](https://www.zenhub.com/)
