### ISSUE TITLE
Command line password change interface does not reenable character echoing if interrupted by SIGINT (Ctrl-C)

### ISSUE THREAD

**Issue by Kingwad** [pi-hole/pi-hole#1430]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG | ISSUE] Expected Behaviour:**
If setting a password is cancelled with Ctrl-C, further text typed to bash should be echoed and visible

**[BUG | ISSUE] Actual Behaviour:**
If setting a password is cancelled with Ctrl-C, further text typed to bash is not echoed and invisible.

**[BUG | ISSUE] Steps to reproduce:**

- From a bash shell, enter `pihole -a -p`.
- Before finishing password entry, use Ctrl-C to send a SIGINT to cancel the command and return to the bash prompt.
- Attempt to use the shell. Characters typed do not echo and are invisible.
- To return shell to normal behaviour you can use the `reset` command to reset the prompt to it's default state.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Kingwad** [comment]
System: Raspberry Pi 1 Model B, Raspbian Jessie Lite up do date as of 2017-05-04

**Comment by dschaper** [comment]
Thanks for the ticket, we'll take a look.

**Comment by jacobsalmela** [comment]
@Kingwad please try the fix in #1587 to see if that resolves the issue for you.

**Comment by Kingwad** [comment]
This change works for me. Tested on same system as before by manually applying the change in pull 1587.

**Comment by jacobsalmela** [comment]
Glad to hear it.  The fix has been merged to `development` and it will be available in v3.2.
