### ISSUE TITLE
error in /var/log/lighttpd/error.log

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/pi-hole#1431]
Just installed a fresh copy (new install) of v3.0.1

noticed two errors in the log

`(mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined variable: over_time in /var/www/html/admin/api_FTL.php on line 244`
`(mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined variable: over_time in /var/www/html/admin/api_FTL.php on line 282`

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #501](https://github.com/pi-hole/AdminLTE/issues/501) via [**ZenHub**](https://www.zenhub.com/)
