### ISSUE TITLE
Cant see web admin

### ISSUE THREAD

**Issue by grrminator** [pi-hole/pi-hole#1432]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Should be able to see the web interface

**[BUG | ISSUE] Actual Behaviour:**
Cannot connect to web interface

**[BUG | ISSUE] Steps to reproduce:**

**Debug token generated by `pihole -d`:**
zye76ynul2

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Hmmm, looks like `lighttpd` is not running, but appears to be installed.

What is the output of:

`sudo systemctl status lighttpd`

**Comment by grrminator** [comment]
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Thu 2017-05-04 19:25:31 UTC; 2min 59s ago
  Process: 1016 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 993 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 1016 (code=exited, status=255)

May 04 19:25:30 DietPi lighttpd[993]: Syntax OK
May 04 19:25:30 DietPi systemd[1]: Started Lighttpd Daemon.
May 04 19:25:31 DietPi lighttpd[1016]: 2017-05-04 19:25:30: (log.c.118) ope...ry
May 04 19:25:31 DietPi systemd[1]: lighttpd.service: main process exited, c.../a
May 04 19:25:31 DietPi systemd[1]: Unit lighttpd.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by PromoFaux** [comment]
Ah, you're on Dietpi! Did you install via the Dietpi installer, or the curl to bash method?

Dietpi installer still uses our install script, but there are a couple of changes that @Fourdee implemented that are necessary for compatibility! If you used `curl -ssL https://install.pi-hole.net | bash` then that might explain things...

**Comment by grrminator** [comment]
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd Pi-hole/automated\ install/
bash basic-install.sh
i did this

**Comment by PromoFaux** [comment]
Righto! That's basically the same as the curl to bash method, just more manual. 

@WaLLy3K, I know you use this method to install on Dietpi, did you need to do anything special to get things working once the install script had run?

**Comment by grrminator** [comment]
i dont neeeed dietpi should i use regular raspian?

**Comment by grrminator** [comment]
how would i get it to install on dietpi?

**Comment by PromoFaux** [comment]
If you like, I can guarantee the script will work there! You can also try using the dietpi installer to install (make sure to uninstall with `pihole uninstall` first.)

If you want to use the dietpi installer, see here: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5

**Comment by grrminator** [comment]
gonna try on dietpi first hopefully it works

**Comment by PromoFaux** [comment]
If you have any issues there @Fourdee is the one to ask! https://github.com/Fourdee/DietPi/issues

**Comment by grrminator** [comment]
did not work on dietpi lighttpd is still failing

**Comment by grrminator** [comment]
just gonna do raspian lite

**Comment by grrminator** [comment]
ok dont want to go thru that i like the GUI with dietpi

**Comment by grrminator** [comment]
if anyone can help with dietpi HMU

**Comment by dschaper** [comment]
Have you tried installing via the DietPi Installer?

**Comment by grrminator** [comment]
i did same error

**Comment by dschaper** [comment]
Okay, looks like your lighttpd.conf file may have an error in it. 

Can you post the output from

`sudo systemctl -I status lighttpd`

**Comment by grrminator** [comment]
im on raspian lite now
but ftl is offline and i have lost connection to api

**Comment by dschaper** [comment]
Okay, lets start over, what is the problem that you are seeing now. Are you able to see the web interface, but with the error that FTL is offline? Also, are you on v.3.0.1 that was released today?

**Comment by grrminator** [comment]
yea i just repaired pihole and it fixed it!
im good now

**Comment by dschaper** [comment]
Great, glad to hear it! Closing out as solved.
