### ISSUE TITLE
Graphs malformed on Google Chrome

### ISSUE THREAD

**Issue by gr099** [pi-hole/pi-hole#1434]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Correct graphs

**[BUG | ISSUE] Actual Behaviour:**
Graphs ar both missing an malformed

**[BUG | ISSUE] Steps to reproduce:**
Google Chrome ver Version 58.0.3029.96 (64-bit)
pihole 3.01 and 3.01a
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`6isqqx78z0 `

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
could you please post a screenshot of the issue as the description you gave could be really anything ?

**Comment by gr099** [comment]
![image](https://cloud.githubusercontent.com/assets/28426786/25747776/fde5a9f0-31a8-11e7-9b98-cb3138884d60.png)

Query types over Time and Forward Destinations over Time are empty
Queries over last 24 hours have a black background

All looks perfectly well on Firefox

**Comment by technicalpyro** [comment]
so the graphs are run by javascript which is most likely cached other users have reported success with clearing their cache and force reloading the page.  other options that can be attempted are rebooting the pi as well as the devices accessing the interface.  not sure why chrome hods so tightly to JS objects but it seems to

**Comment by technicalpyro** [comment]
Ping.  Is this issue still present?

**Comment by graysky2** [comment]
Already closed, but I do not see this on google chrome 59.0.3071.115.
