### ISSUE TITLE
dhcpcd.conf overwrites resolv.conf 

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1435]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10
---
**[ISSUE] Expected Behaviour:**
resolv.conf should be populated with 127.0.0.1 from the `dnsmasq` package installation. 

See: https://discourse.pi-hole.net/t/dns-server-reverting-to-192-168-1-1/1298

**[ISSUE] Actual Behaviour:**
nameserver declaration in `/etc/dhcpcd.conf` can set that to a non-localhost address. While the address in `dhcpcd.conf` should be the address of the Pi-hole, if there are any addressing changes made after installation, unless `dhcpcd.conf` is updated, then the `resolv.conf` will be configured with incorrect IP address. 

Leads to loss of ability for the Pi-hole to resolve during critical phases of the updating process.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Suggested solution:

Use `127.0.0.1` as nameserver address in `dhcpcd.conf` until the dependency on `dhcpcd.conf` is removed for all non-Raspbian installs.

**Comment by jacobsalmela** [comment]
Closing; appears to be resolved by #1436
