### ISSUE TITLE
Webbased list update runs twice.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1438]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---

**[BUG] Expected Behaviour:**
Manual web based update of the lists should only run once.

**[BUG] Actual Behaviour:**
First run succeeds and green Success bar is shown. Then a second list update happens in the same scroll window.

**[BUG | ISSUE] Steps to reproduce:**

Click the update lists button.

**(Optional) Debug token generated by `pihole -d`:**

`44a7xhyp9e`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
Closing; seems to have been fixed with https://github.com/pi-hole/AdminLTE/pull/496
