### ISSUE TITLE
"Flush Logs" needs to be executed 2 x in order to actually reflect on the "Dashboard" view.

### ISSUE THREAD

**Issue by cybrnook** [pi-hole/pi-hole#1439]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
6

**[BUG | ISSUE] Expected Behaviour:**
Flush Logs button wipes all stats from the Dashboard view, starting at 0 again

**[BUG | ISSUE] Actual Behaviour:**
First time executing Flush Logs from webui, seems the Dashboard view is unaffected. Second time, the Dashboard view then resets back to 0.

**[BUG | ISSUE] Steps to reproduce:**
- Execute "Flush Logs" from the "Settings" page
- Click Dashboard, should still show all old info
- Execute "Flush Logs" from the "Settings" page (again)
- Click Dashboard, should now be back to 0 values.

**Comment by cybrnook** [comment]
I also want to add what a great job you guys are doing. Latest updates to the webui and the addition of FTL is amazing!

**Comment by DL6ER** [comment]
Thanks!

What you report should actually already be happening ... see https://github.com/pi-hole/pi-hole/pull/1391

**Comment by cybrnook** [comment]
I am on the latest version of Pi-Hole with FTL.

pi-hole up shows no available updates, yet this behavior is still present.

In #1391 , it is in "Merged" status. Has it been merged into the development branch, or the master/release bran ch?

**Comment by DL6ER** [comment]
Hmm, very strange.

Can you verify the PR against the content in `/etc/pihole/advanced/Scripts/piholeLogFlush.sh` on your local machine?

This is the state is current `master`:
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeLogFlush.sh

**Comment by cybrnook** [comment]
yep, will do that this evening when I get home. I was just reviewing your PR actually, thinking maybe a sleep or something may be in order.

I will check this evening and update you.

**Comment by cybrnook** [comment]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri May  5 19:44:10 2017 from 192.168.1.182
pi@raspberrypi:~ $ cat /etc/pihole/advanced/Scripts/piholeLogFlush.sh
cat: /etc/pihole/advanced/Scripts/piholeLogFlush.sh: No such file or directory
pi@raspberrypi:~ $ cd /etc/pihole/
pi@raspberrypi:/etc/pihole $ ls
adlists.list                               list.5.s3.amazonaws.com.domains
gravity.list                               list.6.hosts-file.net.domains
install.log                                list.preEventHorizon
list.0.raw.githubusercontent.com.domains   local.list
list.1.mirror1.malwaredomains.com.domains  logrotate
list.2.sysctl.org.domains                  setupVars.conf
list.3.zeustracker.abuse.ch.domains        setupVars.conf.update.bak
list.4.s3.amazonaws.com.domains            whitelist.txt
pi@raspberrypi:/etc/pihole $ pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: FTL:            up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!
pi@raspberrypi:/etc/pihole $

**Comment by cybrnook** [comment]
```
pi@raspberrypi:/etc/pihole $ pihole -v
::: Pi-hole version is v3.0.1 (Latest version is v3.0.1)
::: Web-Admin version is v3.0.1a (Latest version is v3.0.1)
```

**Comment by dschaper** [comment]
The scripts are stored in `/opt/pihole` if you're looking for the exact script to diff.

**Comment by dschaper** [comment]
And the cloned repository is in `/etc/.pihole/advanced.....` It's a hidden directory.

**Comment by cybrnook** [comment]
`pi@raspberrypi:/opt/pihole $ cat piholeLogFlush.sh
#!/usr/bin/env bash
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Flushes Pi-hole's log file
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

echo -n "::: Flushing /var/log/pihole.log ..."
# Test if logrotate is available on this system
if command -v /usr/sbin/logrotate &> /dev/null; then
  # Flush twice to move all data out of sight of FTL
  /usr/sbin/logrotate --force /etc/pihole/logrotate
  /usr/sbin/logrotate --force /etc/pihole/logrotate
else
  # Flush both pihole.log and pihole.log.1 (if existing)
  echo " " > /var/log/pihole.log
  if [ -f /var/log/pihole.log.1 ]; then
    echo " " > /var/log/pihole.log.1
  fi
fi
echo "... done!"`

**Comment by cybrnook** [comment]
```
pi@raspberrypi:/etc/.pihole/advanced/Scripts $ cat piholeLogFlush.sh
#!/usr/bin/env bash
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Flushes Pi-hole's log file
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

echo -n "::: Flushing /var/log/pihole.log ..."
# Test if logrotate is available on this system
if command -v /usr/sbin/logrotate &> /dev/null; then
  # Flush twice to move all data out of sight of FTL
  /usr/sbin/logrotate --force /etc/pihole/logrotate
  /usr/sbin/logrotate --force /etc/pihole/logrotate
else
  # Flush both pihole.log and pihole.log.1 (if existing)
  echo " " > /var/log/pihole.log
  if [ -f /var/log/pihole.log.1 ]; then
    echo " " > /var/log/pihole.log.1
  fi
fi
echo "... done!"
```

**Comment by cybrnook** [comment]
For a second validation, I installed pi-hole "fresh" today on the latest 4.4 Raspbian lite, first issuing an apt-get dist-upgrade etc......

After a fresh install, still the same behavior. Needs to be executed 2 x in order for the flush to be reflected on the Dashboard page.

**Comment by technicalpyro** [comment]
if it helps can confirm this here as well

**Comment by cybrnook** [comment]
If you want to issue the PR, I modified your syntax @DL6ER @dschaper , and the log clearing now works as expected:
```
#!/usr/bin/env bash
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Flushes Pi-hole's log file
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

echo -n "::: Flushing /var/log/pihole.log ..."
# Test if logrotate is available on this system
**if command -v /usr/sbin/logrotate >/dev/null; then**
  # Flush twice to move all data out of sight of FTL
  **/usr/sbin/logrotate --force /etc/pihole/logrotate; sleep 3**
  /usr/sbin/logrotate --force /etc/pihole/logrotate
else
  # Flush both pihole.log and pihole.log.1 (if existing)
  echo " " > /var/log/pihole.log
  if [ -f /var/log/pihole.log.1 ]; then
    echo " " > /var/log/pihole.log.1
  fi
fi
echo "... done!"
```

**Comment by cybrnook** [comment]
Issued a PR:

Solve piholeLogFlush.sh having to be issued 2 x to clear logs #1460

**Comment by cybrnook** [comment]
Solved with:
https://github.com/pi-hole/pi-hole/pull/1460
