### ISSUE TITLE
Unit testing for #1437

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1441]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---

Pull #1437 needs unit tests done for passing merge to master conditions.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please keep that branch open while tests are adjusted. Thanks.

**Comment by DL6ER** [comment]
@dschaper worth noting that the tests fail for @WaLLy3K's pull request #1416 as well

**Comment by technicalpyro** [comment]
pick an OS and let me know what procedure you'd like used i have time and a couple empty flash cards

**Comment by dschaper** [comment]
These are the python unit tests that are in the Test subdirectory. Mostly used for checking on the basic functions of the Pi-hole code and finding things that are unexpected or broken on PR's. We test with CentOS and Debian, and if you want to check out the code or add to it, it would be great. You'll need to clone the repo though, as these are Travis tests and you'll need to run through Travis in order to see the errors and the output from the errors.

**Comment by dschaper** [comment]
Closing.
