### ISSUE TITLE
Added filter lists over webgui can't be removed

### ISSUE THREAD

**Issue by Niemand112233** [pi-hole/pi-hole#1443]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

4

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Deleting from filter lists in the webgui should remove them from /etc/pihole/adlists.list

**[BUG | ISSUE] Actual Behaviour:**
If you delete them in the Webgui, they're been removed in the Webgui, but not in the /etc/pihole/adlists.list

**[BUG | ISSUE] Steps to reproduce:**
Within webgui: Add a filterlist, then remove it
-
-
-
-

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Hi there,

I'm unable to reproduce this on the latest release... can you run a `pihole -d` and provide us with the debug token please? Thanks

**Comment by PromoFaux** [comment]
![memory](https://cloud.githubusercontent.com/assets/1998970/25800482/760e8e94-33e1-11e7-82c1-6909972bdb5e.gif)

**Comment by Niemand112233** [comment]
strange thing, after a reboot it works here too. Now I even can insert https://easylist-downloads.adblockplus.org/easyprivacy.txt where you told here "https://discourse.pi-hole.net/t/how-do-i-add-additional-block-lists-to-pi-hole/259" that the files first have to be formated. 

what user should be the owner of the adlist.list and of the logfiles (pihole and pihole-ftl)?

**Comment by PromoFaux** [comment]
It still needs to be properly formatted to work with pi-hole. If you take a look at @wally3k s lists, he has preformatted and mirrored the easylist. HTTPS://wally3k.github.io

**Comment by Niemand112233** [comment]
but why is it saying "ok" and added some thousands of domains to the blocklist?

**Comment by PromoFaux** [comment]
You would get the same response if you manually added that list to `/etc/pihole/adlists.list`

If you take a closer look at `/etc/pihole/gravity.list`, you'll notice a lot of "broken/garbage" entries in there. The same rule still applies as always. Lists must be [host formatted](https://www.bleepingcomputer.com/misc/hosts)

**Comment by dschaper** [comment]
Is this issue resolved now?

**Comment by dschaper** [comment]
Stale, closing.
