### ISSUE TITLE
New queries graph has unreadable x-axis label

### ISSUE THREAD

**Issue by creeble** [pi-hole/pi-hole#1445]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Show hours in X-axis of graph

**[BUG | ISSUE] Actual Behaviour:**
Big block of gray.

**[BUG | ISSUE] Steps to reproduce:**
Just display the graph.

**Comment by jacobsalmela** [comment]
Are you seeing something like [this](https://discourse.pi-hole.net/t/latest-update-messed-up/2986)?  If so, please flush your browser cache.

**Comment by creeble** [comment]
Doh!  Yes, fixed with browser cache update.  Closing.
