### ISSUE TITLE
Composer update doesn't get last versions of commit hashes of my satis repository

### ISSUE THREAD

**Issue by jmverges** [pi-hole/pi-hole#1448]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{8}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**

When I do composer update, composer must get the latests version of the commit hashes of the repositories

**[BUG | ISSUE] Actual Behaviour:**

When I do composer update, composer is not returning the latests version of the commit hashes of the repositories

**[BUG | ISSUE] Steps to reproduce:**

composer update

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Is that something that we can control here, or is this something that is GitHub related? I'm not sure how we can control the hashes, and I'm not really familiar with Satis or Composer.

**Comment by Mcat12** [comment]
Is a domain blocked? Try using https://discourse.pi-hole.net/t/how-do-i-determine-what-domain-an-ad-is-coming-from/1522

**Comment by jmverges** [comment]
No, is not blocked, is Pi-hole, caching somehow urls?

**Comment by dschaper** [comment]
We only do DNS resolving, we don't see any http traffic or proxy anything. All we can do is convert domains to IP addresses.

**Comment by dschaper** [comment]
If there's no other further information, we'll close this out in a day or two.
