### ISSUE TITLE
Pi-Hole Block Additional List -Fixed

### ISSUE THREAD

**Issue by 91ajames** [pi-hole/pi-hole#1462]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
8

**[FEATURE REQUEST | QUESTION | OTHER]:**

Sorry, if this is a bad spot for this, but I've been stump on this for about a week.

Links I've been to.
-https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists
-https://discourse.pi-hole.net/t/how-do-i-add-additional-block-lists-to-pi-hole/259
-Link broken https://github.com/pi-hole/pi-hole/blob/master/adlists.list

Did the steps listed here but confused where to go next with this
-https://wally3k.github.io/

My rasb has been updated and rebooted and Restarted the Pi-Hole.

I don't see anything to get that other so called 3.0 Box options in my settings. Do I need to completely restart my pi-hole from scratch? Had to do that with the password which I didn't have after resetting my rasp box from scratch.

![82c607c68c57a2e641da7fbc5e43af4e8d8664e7_1_384x500](https://cloud.githubusercontent.com/assets/24540531/26021322/fcccc2c8-3758-11e7-90d7-2e214cc7d6d2.png)

**Comment by Mcat12** [comment]
Are you trying to add new lists? Are you on the latest version? What is the output of `pihole -v`? That block lists setting is located on the settings page in the latest version.

**Comment by 91ajames** [comment]
Sry, My bad, I forgot about the Pi-hole update command. Was still on some early version. Thanks!

Pi-hole Version v3.0.1 Web Interface Version v3.0.1 FTL Version v2.7
