### ISSUE TITLE
dnsmasq still starting when gravity is called during update

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1463]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
when pihole is update gravity pull in all lists used from adlists.list

**[BUG | ISSUE] Actual Behaviour:**
first few lists (3-5) return 
```
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
```

**[BUG | ISSUE] Steps to reproduce:**

-have custom adlists added
-run `pihole -up`
-
-

**(Optional) Debug token generated by `pihole -d`:**

```
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: Pulling source lists into range... done!
:::
::: Getting v.firebog.net list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)

```
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Should** be easily fixed by adding sleep 30s to the update script before gravity is called i just cant figure out which script place to add it

**Comment by Mcat12** [comment]
Why do you think adding that sleep will fix the issue? Have you identified what the cause is?

**Comment by DL6ER** [comment]
(Wild guessing below)

Maybe @technicalpyro sees that `dnsmasq` is still starting up (because of slow machine + huge amount of lists) and hence `curl` will fail since name resolution is not working?

**Comment by technicalpyro** [comment]
@DL6ER that would be my guess between not being able to access via the `pi.hole` hostmame immediately after updates and seeing this occur seemingly every update that is the conclusion i have come to.

Perhaps 30s is too long or it should be done in a way that it doesn't start gravity until dnsmasq is done im not sure what the elegant solution would be.  

for now i just wait until the update is fully done and run `pihole -g` to get all my domains back in

**Comment by anudeepND** [comment]
I'm facing the same issue with that adlists, problem with the v.firebog.net?

**Comment by technicalpyro** [comment]
further follow up it appear to be a Hardware limitation more than anything.  I am basing this off using a droplet (512mb) and my Pi2B and running an update simultaneously shows the droplet performs fine where the pi hangs for the first couple lists and then resumes normally.  making me think a pi2B just isn't powerful enough to handle what im asking of it with large block list

**Comment by Mcat12** [comment]
Hm, I'd think that a Pi 1 would have difficulty, though I'd expect a Pi2 to be able to handle it well enough. Especially since we're targeting all Pis.

**Comment by technicalpyro** [comment]
i would agree unless it is a bandwidth issue.  the droplet is DC hosted whereas my pi is on 15mb down and 1.5mb up

**Comment by jacobsalmela** [comment]
@technicalpyro are you still having this problem on the latest version?

**Comment by technicalpyro** [comment]
Yes this issue is still present on my raspberry pi the issue does not occur on my vps leading me to believe that it is a limitation of some kind either memory or cou speed causing dnsmasq to not be fully loaded when gravity is called during the update

**Comment by jacobsalmela** [comment]
If that's the case, we may need to add a note on the hardware/software requirements page.

Personally, I run Pi-hole on a B+ and a Zero.  I have never run into this, but I also only run the stock lists, which hover around 100,000.

And to clarify, the issue only happens when running `pihole -up` (which in turn, runs `gravity`), but not if you run `pihole -g` at any time?

**Comment by jacobsalmela** [comment]
I have seen `dnsmasq` take a bit to read all of the domains so I don't think your `sleep 30` solution was too far off a solution; there's probably a better way, but we'll have to investigate that.

**Comment by technicalpyro** [comment]
#1656 as an attempt at resolving this i did test on my local machine and it worked with the timing i used

**Comment by technicalpyro** [comment]
Currently running the dev branch and the code changes made by @WaLLy3K have resolved the issue the script now waits for DNS resolution to be possible before gravity can run 

```
[i] Preparing to run gravity.sh to refresh hosts...
  [i] Cleaning up previous install (preserving whitelist/blacklist)
  [i] Running gravity.sh
  [✗] DNS resolution is currently unavailable
  [✓] DNS resolution is now available
```
will wait for one of the bosses to close the issue but it appears to be resolved

**Comment by DL6ER** [comment]
You opened it, so you can close it when you want. I'll mark this as "Fixed in next release".

**Comment by technicalpyro** [comment]
i feel it is resolved so will be closing thanks everyone
