### ISSUE TITLE
pihole.log is rotated twice on midnight

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/pi-hole#1475]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

## 10

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
`pihole.log` should only be rotated once every day

**[BUG | ISSUE] Actual Behaviour:**
`pihole.log` is rotated twice every day since having merged #1460

**[BUG | ISSUE] Steps to reproduce:**
Wait until midnight

**Comment by jacobsalmela** [comment]
Closing; seems to be resolved with #1476 and #1460
