### ISSUE TITLE
Pretty much kills the Yahoo website.  Wait, I guess that's not really an issue but a benefit.

### ISSUE THREAD

**Issue by Clubguy** [pi-hole/pi-hole#1477]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hey @Clubguy,

Could I get you to run `pihole -d`, upload the debug log and provide the token it gives you, so we can take a look under the hood to better understand what's happening?

Also to make sure we're on the same page, what's the exact Yahoo site you're visiting that experiences the issue?

**Comment by Clubguy** [comment]
I'm not saying this is a bad thing since most of the "stories" on the yahoo.com page are nothing but advertisements in the first place.  I'm wondering if Pi-hole can block the stories from appearing since when you click on the link to the story the page doesn't load anyway.

My debug token is:  u56xtfpf5a

An example is a story about Melissa McCarthy losing 197 pounds.  The link above the headline says "Sponsored - Kiwi Report."  When you click on the story, the subsequent page doesn't load:

https://beap.gemini.yahoo.com/mbclk?bv=1.0.0&es=fQCb3q8GIS9O5Ar6Hk350IxNccoCM5MNqHELHtUDFn3zBNkn1xCszo7WjlFrHdEuSoFiSM8NkvoLvoijK_DgniGYHokZAZ4Y58DRGEGFlADyGn9JG6JtC3ly4AkM7M023wkfVvduk2OzTXguF7XUznMoeZrNPihDwd.wDM16ttPn.mxt2_JwUn.RcMEzXdhxusPGByKoVgLkABIMhWL4UbnQhNBFmxsARSSYum0Bf9kGt4gv1haGDMkXAGF8ApgyfSjf7uwE6lYT0TOiNx1Mnm15C7ab01AbXoGyqHsXfsGDbk39QHudZGdFvQaKzaFYxvfhh0iV0N9J6fg1H4jBhIGKgjX.g2uFcShY5FJ3fgv0VSrX4qXt1h8tTsy0abOyqMhPgSScHa4SVMX2Hq2ScwNpdkasIJyKb.cxvEgKGCKjln9CgdayBVM9VyLttPEHbh0.z4uKTTvpu40rsM3bohZE64RTK21zTmWgK_eG3GT31m34C_eZAnZSuOKkBk1yageRQ3rBLeLigOf4oS9RbI27F9vqzyaPPBsTbzSy2jZfTM4Mq37gdWZJQWkwXYF2XLWZYJgNRzUP_jUkRrUn1xM1MxjVHS0HkzS3.DecRQBU5YDDeWn53PsOaYF7o2ifoDjQoDlOiXXkUXDlVrZUAUqf22mnPx0VavBELoPjUoSt8l8.YHQC05t9UpoubC7nflPXhyW7f4toVi0C2zAsKJXK9w--%26lp=http%3A%2F%2Fcajpjhuft.kiwireport.com%2Fmind-blowing-celebrity-weight-loss-transformations%3Futm_source%3DYahoo%26utm_medium%3Dak0n.pYGBTvCuwg--%26utm_campaign%3DKR%2520Weight%2520Loss%2520Transformations%2520G20%2520-%2520Desktop%2520YA

**Comment by WaLLy3K** [comment]
>  I'm wondering if Pi-hole can block the stories from appearing since when you click on the link to the story the page doesn't load anyway.

Unfortunately, no. Pi-hole can only allow or deny a connection to a web server (based on its domain name, in this case, `beap.gemini.yahoo.com`) and if the domain name is found in a blacklist, the connection is denied.

If you'd like to filter content on the page, you need a browser based extension such as uBlock Origin.

Hopefully this answers your question. If not, you're totally welcome to reply to this issue and open it back up :smile:
