### ISSUE TITLE
Pihole stops working randomly

### ISSUE THREAD

**Issue by Stibbons** [pi-hole/pi-hole#1478]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

7

**Bug**
After a random delay (from few dozen of minutes to a few hours), I have my pi hole Raspberry Pi 3 (latest Raspbian Lite) goes weird. I cannot exactly know the trigger for this behavior, it may be related to edition of the settings of adding/removing of lists, I don't know.

What's weird:
- ping is ok
- DNS is still blocked on my network as usual
- ssh is unavailable even using static IP address (`ssh: connect to host 192.168.0.3 port 22: Operation timed out`)
- http admin page is unavailable, BUT it returns a Lighttpd error page:
```
Forbidden
You don't have permission to access this file on this server.
Cheyenne/2.2.8 Server at localhost Port 80
```
- Using HDMI output and a USB keyboard, so on the machine directly, login is fine, no error on log.

nmap from a remote host shows port 22/tcp is **closed** and 80/tcp **open**.

pihole.log continues to log stuff, and a quick test shows that dns pi-holing is still kind of working. But no more HTTP no more SSH.
`ps aux | grep ssh` still displays `sshd -D`
`ps aux | grep pihole` still displays `pihole-FTL`
`ps aux | grep dns` still displays `dnsmasq -x ...`
nothing in `/var/log/message`
Upon reboot it works fine again.

I have set up an ansible to reproduce a full setup: https://github.com/Stibbons/ansible-rpi-pihole
It does this issue when I install manually and also when using this ansible.

Isn't it possible to set a kind of watchdog that restart the rpi if ssh is down?

Tested on "dev" branch as well as "master"

**Comment by technicalpyro** [comment]
what doe `cat /proc/meminfo` show when this occurs and you use hdmi to get in ? sounds like the system is running out of resources

**Comment by Mcat12** [comment]
> Cheyenne/2.2.8 Server at localhost Port 80

Are you running a different web server?
Do you have any firewall rules set up? Anything in the sshd log?

**Comment by Stibbons** [comment]
Oh, it looks like an issue with my router (Freebox). It only happens with pihole however. So I close this issue.

**Comment by Stibbons** [comment]
Update of this issue: definitively does NOT comes from PiHole. On my local network, PiHole becomes innaccessible only on my Mac, randomly. On another PC, it works. Only needs to restart the wifi and it works. Weird
