### ISSUE TITLE
index.php doesn't work with Nginx

### ISSUE THREAD

**Issue by TheAntimist** [pi-hole/pi-hole#1479]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
_1_

---
Okay, so this is very specific to nginx, I'm not sure if anyone else has even bothered but, the [`/var/www/html/pihole/index.php`](https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php) doesn't work correctly with nginx. Minor issue, but the blocked website's name is the name of my nginx server name specified in my `/etc/nginx/sites-enable/site` . Though this works fine on lighttpd.

I currently use: nginx 1.10.3 with php 7.0.16-3

**[BUG] Expected Behaviour:**
When I open a blocked website, it gives me the following output:
```
    Access to the following site has been blocked:
         NGINX_CONFIG_SERVER_NAME
```

**[BUG] Actual Behaviour:**
It's supposed to be:
```
    Access to the following site has been blocked:
         BLOCKED_WEBSITE.NAME
```
---
I went digging around the code base a bit, not sure if it's an nginx or the php issue but this line [here](https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L13):
````
$serverName = escapeshellcmd($_SERVER['SERVER_NAME']);
````
 should be changed to:
````
$serverName = escapeshellcmd($_SERVER['HTTP_HOST']);
````
This also works on lighttpd.

---
Also, just mentioning that the index.php, gives me an error in the Firefox 54.0 beta 6, though it works on Chrome, must be a beta thing.
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Thanks for the report @TheAntimist, I'll be sure to look into this further!

**Comment by TheAntimist** [comment]
Hey, WaLLy3K,

So, I checked, but from here:
http://stackoverflow.com/questions/1459739/php-serverhttp-host-vs-serverserver-name-am-i-understanding-the-ma

And here: http://php.net/manual/en/reserved.variables.server.php

It seems to be more accurate to use what I stated. The behavior with
'SERVER_NAME' depends on the server.

On May 18, 2017 1:06 PM, "WaLLy3K" <notifications@github.com> wrote:

Thanks for the report @TheAntimist <https://github.com/theantimist>, I'll
be sure to look into this further!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pi-hole/pi-hole/issues/1479#issuecomment-302325600>,
or mute
the thread

**Comment by WaLLy3K** [comment]
[Issue will be fixed on next release](https://github.com/pi-hole/pi-hole/blob/development/advanced/index.php#L10).

Thanks again for bringing this to our attention! :grinning:
