### ISSUE TITLE
Support for read-only root partition

### ISSUE THREAD

**Issue by space-age-robotics** [pi-hole/pi-hole#148]
Making the root partition read-only can make a big difference in helping protect against filesystem corruption on unintended powerloss.

It would be lovely to have the pi-hole installation script set up so that all important / updated files are stored in a common location that can be mounted read-write, while the root filesystem partition can be mounted read-only.

Setting up symlinks to files instead of copying them to the root partition, or having some other userland-type install would help a great deal.

See https://gist.github.com/basilfx/a099d4f64407c42e716d for an example (used in octo-pi).

**Comment by dschaper** [comment]
You'd like Pi-Hole's install to be read-only compatible, or you'd like the install to convert an existing Raspbian installation into a read-only configuration?

**Comment by space-age-robotics** [comment]
The former--I can make an installation read only, but making the pi hole
read only compatible would help make keeping it up to date a lot easier.

**Comment by dschaper** [comment]
Speaking solely for myself here, I read through the link and I'm not sure how Pi-Hole could be configured to help in an RO environment? I'm working on the packaging of the scripts and would be happy to see how I could help if you could expand upon the subject a little bit more and tell us how/what we could do in more some more definite terms. (An example or two to help clear things up for me?)

**Comment by jacobsalmela** [comment]
I'll have to read into this some more, too.  But are you basically trying to prevent corruption by doing something like this?

**Comment by dschaper** [comment]
Corruption mitigation would be nice, lost 2 SD-cards yesterday in a blackout. And the Orange Pi wasn't one of them for once...

**Comment by space-age-robotics** [comment]
That's the idea, sorry I didn't put more info in the issue, was dashing it
off when the idea struck.

I've got a number of pis around, the pi-hole, some volumios for music,
octopi, and it really stings when the SD card gets corrupted due to power
loss, etc.

For the pi-hole, I think we'd need something like a user-land install
(e.g., /home/pi) of the scripts and the mutable files.   I've had good luck
with other things keeping the mutable stuff in /home/pi and making that its
own partition (leaving enough space on the root partition for the software
and reasonable head room for future updates).

It's fairly easy to remount the ro partition as rw, for software updates
(even to run gravity.sh from time to time) but it would be very helpful to
have the logs and stats (which are written to all the time) segregated some
place that could be made its own partition.

I haven't dug in to the implementation details, so it's not clear exactly
what would need to be modified, or which parts would benefit most from
being moved to userland.  Perhaps just the logging would be enough, but
something more portable would be good if it weren't too complex.  I'll have
another look tomorrow and see if anything obvious stands out as a good
first step.

**Comment by dschaper** [comment]
I'm not sure that setup would work in a deb packaged environment. The Debian Policy Manual (and by proxy Raspbian) is very specific in regards to which files can go into which directories. Deb's aren't allowed to install into home directories... @jacobsalmela may or may not want to alter the install script based on a cost/benefit, but because of the DPM, the packaging is pretty restricted.

**Comment by space-age-robotics** [comment]
Ah, interesting, I wasn't aware of those restrictions.  The main priorities
for the home directory would be the more frequently updated files (like the
site files generated by gravity, logs, etc.) that are not part of the
install package itself.  It is usually no problem to remount the system
read-write for software updates, installations, etc.  The important thing
to to be able to let it run with the root partition read-only for normal
operations, and have log files, etc. written to a separate partition that
is lower risk if it gets corrupted.

**Comment by dschaper** [comment]
Okay, I'll look into it some more. The scripts are pretty much required to be installed in `/usr/bin` but logging may be a little more relaxed. Typically logs are required to go to '/var/log', but I have seen other packages that log to '/tmp'. I know by default Jessie has `/tmp` on a sd-card mount but it's not that difficult to have it mount to a ram partition. The logging is a bit different with Pi-Hole as it's the source of information for the web interface...

**Comment by mwlpeeters** [comment]
You could also advise users to move the whole partition to an usb drive, see [https://www.raspberrypi.org/forums/viewtopic.php?p=351659#p351659](url) for more information.
I'm running my pi for months like this and it seems very stable. I did some testing with pulling the power and it recovered every time.

**Comment by dschaper** [comment]
Moving to USB doesn't do the same thing as moving to Read Only. The USB move was beneficial back when writing to SD was iffy at times, to use the technical term. All you're doing us moving the reads and writes from the SD controller and medium to the USB controller and it's medium. The SD corruption problem has long been solved on the Pi and the limited lifetime read write cycles proved sufficient. Pulling the power randomly isn't the best practice with a Pi, no matter what the root partition medium happens to be.

**Comment by dschaper** [comment]
Hit wrong button, didn't intend to close out.

**Comment by dschaper** [comment]
All files are stored in LFH compliant directories. It's beyond the scope of the Pi-hole project to prep an install for a read-only filesystem.

**Comment by Stibbons** [comment]
+1 for read only support, this is really annoying a show stopper

**Comment by dschaper** [comment]
You can open up a Feature Request on https://discourse.pi-hole.net and we can track that with community votes to see how popular the feature would be, and to see if there is something we can do to try and support a read only system.

**Comment by CarloCattano** [comment]
this is very much needed still nowadays for my use case
