### ISSUE TITLE
Pihole Ubuntu 14 Installation FTL Offline

### ISSUE THREAD

**Issue by jrdnlc** [pi-hole/pi-hole#1482]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

Just installed Pihole on a Ubunu 14 server and only issue is that ftl is offline. I ran pihole -r and that doesn't appear to fix the issue.

Here is the log https://hastebin.com/wuvupedinu.sql

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token.

**Comment by jrdnlc** [comment]
Here is the token `g26acaulea`

**Comment by Mcat12** [comment]
The debug log shows that PHP is not installed, bind has taken over port 53 (you aren't blocking ads), and there's no FTL log. Stop bind and restart dnsmasq. Run `pihole -r` to repair, and share the output. Also run `sudo service pihole-FTL restart` and `sudo  service pihole-FTL status` and share the output.

**Comment by jrdnlc** [comment]
Here is the new token `c1k403d9ws` @Mcat12

**Comment by Mcat12** [comment]
Is it working now? The debug log still shows PHP missing.

**Comment by jrdnlc** [comment]
Yeah it looks like it's working. Is it `sudo apt-get install php5` to install php? @Mcat12

**Comment by Mcat12** [comment]
Does the web interface work? If so, then you must already have PHP installed. That command should also install a version of PHP.

**Comment by jrdnlc** [comment]
Yeah the web interface does work @Mcat12

**Comment by Mcat12** [comment]
Ok, then you shouldn't have to install another version of PHP.

**Comment by jrdnlc** [comment]
What is this error @Mcat12 

`:::  ---= Processes Check
:::     Logging status of lighttpd, dnsmasq and pihole-FTL...
/opt/pihole/piholeDebug.sh: line 376: systemctl: command not found
/opt/pihole/piholeDebug.sh: line 376: systemctl: command not found
/opt/pihole/piholeDebug.sh: line 376: systemctl: command not found
`

**Comment by Mcat12** [comment]
You appear to not have that command installed. It's used when debugging.

**Comment by jrdnlc** [comment]
Do I need to worry about it and install or just leave it as is? @Mcat12

**Comment by Mcat12** [comment]
Leave it as is. Normal Pi-hole usage doesn't rely on it.

**Comment by dschaper** [comment]
I see that you are running a KVM, did you spin up a plain VM or are you using any kind of automation tools to create the setup? I have a libvirtd setup here on my system that I can use to try and duplicate things, but if you are using something like Ansible, I'd like to use the same playbook to try and make sure we're using the same. And just a question on why you've blocked `dnsmasq` from the bridge interface?

**Comment by jrdnlc** [comment]
@dschaper I setup a new KVM using Ubuntu Server 14.04. Ran updates after the installation and then run the command to install pihole. What do you mean by why did I block `dnsmasq ` from the bridge interface? My VM is running on a bridge interface.
