### ISSUE TITLE
Ads not blocked anymore; Blacklist without function and adding of new filter lists doesn't work

### ISSUE THREAD

**Issue by Niemand112233** [pi-hole/pi-hole#1484]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
4
_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**
All ads being blocked

**[BUG | ISSUE] Actual Behaviour:**
many ads not being blocked

**[BUG | ISSUE] Steps to reproduce:**
open site with my pihole and see some of the ads. Some ads are blocked. Adding Domains to the black list doesn't work for ad-servers and for some domains like facebook.com. Adding new filterlists from https://wally3k.github.io/ doesn't change the number of domains being blocked. But the entries are there where they should be. The Ad-Domains and many other can't be seen in the query log. 

**(Optional) Debug token generated by `pihole -d`:**
I would like to do this, but: There was an error uploading your debug log.
Please try again or contact the Pi-hole team for assistance.
`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hey, sorry to hear you're having issues!

Without the debug log, it does make it a bit hard to troubleshoot. Try uploading it a second time, please. If that fails, could you provide the output of `timeout 1 nc -z tricorder.pi-hole.net 9999 && echo "Success" || echo "Failed"`?

In the meantime, some questions:

* What's the "Domains being Blocked" count at http://pi.hole/admin?
* When was the last time you ran `pihole -g`?
* What browser do you use, and do you have any adblocking extensions installed?

**Comment by Niemand112233** [comment]
Hi,
I tried it for the second time. Same result. 
The Output of your command is "success".
Pihole -g was ran for about 20times the Last 2 days. 
I use Firefox on 3 different systems (Linux, win, Event fresh installed).
The Block Counter for today ist increasing (about 2048) and the total is at 119469

**Comment by Niemand112233** [comment]
Strange Thing: ober von everything works fine

**Comment by Niemand112233** [comment]
*Over VPN

**Comment by Niemand112233** [comment]
it didn't work properly, but here is the Token: pt3vqdb37k

**Comment by Mcat12** [comment]
Could you delete `/var/log/lighttpd/error.log` and make another debug log? The error log was too long and prevented it from uploading anything after it.

**Comment by Niemand112233** [comment]
ppza6zbz8k

strange: after deleting the error.log (which was actually only 1kb in size) the ads seems to be blocked better

**Comment by WaLLy3K** [comment]
When you say "blocked better", do you mean to say that the issue has been completely resolved (that Pi-hole works as expected for both OpenVPN *and* LAN connections)?

Let us know if there's any issues that remain, and we'll go from there :smile:

**Comment by Mcat12** [comment]
@Niemand112233 Is your issue resolved?

**Comment by jacobsalmela** [comment]
Paging @Niemand112233 again for a response

**Comment by jziggas** [comment]
I'm not sure if this is related, I just installed pi hole for the first time and am familiarizing myself with it. But those ad videos that appear halfway through a regular video still appear.

**Comment by jacobsalmela** [comment]
@jziggas you should open a new issue if you are having trouble.  I'm closing this due to the OP not responding for 22 days.

**Comment by Niemand112233** [comment]
The Problem is still sometimes there. It is not really repdroduceable. I think it is because of missing easylist for my country (germany). Any hints how to add it easily?

Am 29.07.2017 um 06:15 schrieb Jacob Salmela <notifications@github.com<mailto:notifications@github.com>>:


@jziggas<https://github.com/jziggas> you should open a new issue if you are having trouble. I'm closing this due to the OP not responding for 22 days.
