### ISSUE TITLE
'Reconfigure' shows thats no password set, but it is

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/pi-hole#1488]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Does 'password is NOT SET' mean that is were not changed?
Because the password is still the same after running reconfiguration.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

If I run Reconfiguration, it shows me in the end that there were no Admin Webpage login password set.
But it is set.

**[BUG | ISSUE] Steps to reproduce:**
- run `pihole -r`
- choose `Reconfigure`
- work through until 'Installation Complete!'-Window is shown

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

![reconfigure2](https://cloud.githubusercontent.com/assets/28313514/26321534/6605f00e-3f27-11e7-8837-d8d0492ada97.GIF)

**Comment by DL6ER** [comment]
Currently, the web password is only generated if there was no password previously. Then (and only then) then installer knows the plaintext password. It cannot show the password since it cannot be obtained.
However, it should also not show `NOT SET`, but rather something like `unchanged`.
