### ISSUE TITLE
pihole -up returns git error

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1489]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
`pihole -up` runs correctly 

**[BUG | ISSUE] Actual Behaviour:**
pihole -up returns the following
```
::: --reconfigure passed to install script. Resetting changes to local repos
fatal: Not a git repository (or any of the parent directories): .git
Unable to complete update, contact Pi-hole
```
worth noting the update appears to have completed correctly as my version shows 
` Pi-hole version is v3.0.1-73-g2ef87ad (Latest: v3.0.1)`
which IS the latest commit according to the Dev branch here 
issue also occurred on two devices making me think not isolated

**[BUG | ISSUE] Steps to reproduce:**

-run dev branch 
-apply latest commits
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I'm unable to reproduce this. Can you provide more output lines you have seen so we can start looking at which part of the code might be causing this exactly?

**Comment by technicalpyro** [comment]
unfortunately i forgot to save a screen shot of this it occurred directly after checking for dependent packages.  and halted the update script.  however it appears everything is now up to date.  seems like a weird one off but occurred both on my pi and VPS

**Comment by technicalpyro** [comment]
spoke too soon 
```
pi@raspberrypi:/etc/.pihole $ sudo git reset HEAD~3
Unstaged changes after reset:
M       README.md
M       advanced/Scripts/list.sh
M       automated install/basic-install.sh
M       pihole
pi@raspberrypi:/etc/.pihole $ cd
pi@raspberrypi:~ $ pihole -up
::: Checking for updates...
::: Pi-hole Core:   update available
::: FTL:            up to date
::: Web Interface:  up to date
:::
::: Pi-hole core files out of date
:::
::: Checking for existing repository...
:::    Updating repo in /etc/.pihole... done!
 done!

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

:::
::: You are root.
::: --unattended passed to install script, no whiptail dialogs will be displayed
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for apt-utils... installed!
:::    Checking for dialog... installed!
:::    Checking for debconf... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for git... installed!
:::    Checking for iproute2... installed!
:::    Checking for whiptail... installed!
::: --reconfigure passed to install script. Resetting changes to local repos
fatal: Not a git repository (or any of the parent directories): .git
Unable to complete update, contact Pi-hole
```

**Comment by DL6ER** [comment]
Fix incoming ...
