### ISSUE TITLE
Delayed response at times

### ISSUE THREAD

**Issue by csawall** [pi-hole/pi-hole#149]
Has anyone had an issue where response is delayed every now and then?  I have everything installed and it works great!  When it works.  Every now and then when a DNS request is made (going to a web site or similar), there will be no response and then the browser times out.  This has happened on several devices.  If you wait a minute and try again, everything works great, fast, and is successful.

If I check my resources on my RPi, nothing seems out of the ordinary.  No CPU or memory over utilization.  Thoughts?

**Comment by jacobsalmela** [comment]
I don't think it has anything to do with the resources as the Pi-hole requires very little.  I have had it happen on occasion, but it is rare.  One site that seemed to cause issues a lot was flashback.org.  

Some possibilities might be corrupted cache or a site timing out.  Did you install it recently?  We just added support for IPv6.  I haven't had it happen to me since then.

**Comment by csawall** [comment]
Hi @jacobsalmela.  It was happening to me or my family a few times an hour and the destination site did not matter, i.e., cnn.com or minecraft or really any destination.  I installed it about a week or so ago...  Should I update anything?  Thanks!

**Comment by jacobsalmela** [comment]
I'm still looking into it.  Has it happened a lot in the past three days?  I'm wondering if it is something to do with the router/network and not the Pi-hole.

**Comment by csawall** [comment]
Hi @jacobsalmela.  I have it disabled at the moment so that my family isn't interrupted while I'm at work.  I can turn it back on this weekend and do more testing.  I don't think it's the router or network, everything works as expected without any issues at all when I move everyone back to an external DNS solution.  I'm using OpenDNS.  I have dnsmasq set up to use OpenDNS as well.  When enabled, I modify my DHCP settings on my Cisco ASA firewall to only serve up the RPi address and for testing, I renew the leases to pull down the updated settings.  Thanks!

**Comment by jacobsalmela** [comment]
OK, let me know what happens.  I haven't used a Cisco ASA firewall, but I have had experiences with those kind of appliances slowing things down.  The Pi-hole typically makes things faster because of caching.

Either way, let me know.

**Comment by csawall** [comment]
Well, I'm back on Pi-hole internally, for almost a week, and no issue.  So I'll keep an eye on it.  I have tshark ready to run if needed to capture some data.  Thanks.

**Comment by crazyaces** [comment]
I had the same issue after setting up my Pi-hole. Everything seemed to work fine at first, but then sites would stop loading. I'd try to check the web interface but I'd get a 'server isn't responding' message. After a minute the Pi-hole would start acting normally again and the web interface would load normally. I'd say it went in and out like this every five minutes or so.

**Comment by dschaper** [comment]
@crazyaces Which version of the Pi are you running on?

**Comment by dschaper** [comment]
It almost sounds like an IP issue. How do you have your Pi-Hole's IP assigned? Static IP or a DHCP Reservation?

**Comment by crazyaces** [comment]
I'm using the Pi 2 Model B, running Raspbian Jessie Lite, and the latest version of Pi-hole. Pi was assigned static ip, with Netgear router pointing to Pi's static IP as primary DNS

**Comment by dschaper** [comment]
And is the IP address for the Pi in the range of the Netgear's DHCP pool? Trying to see if maybe the Netgear is getting confused and there is an arp issue.

**Comment by crazyaces** [comment]
Yeah, the IP was definitely in range. I was hoping to have the router forward all DNS requests to the Pi so I didn't have to configure every device in my house individually. Im wondering if maybe the router just isn't too happy with a local address for the dns server. Resetting things now to test it out

**Comment by dschaper** [comment]
Try setting the IP address of the Pi to one outside of the DHCP pools address.

**Comment by dschaper** [comment]
I'm running a Netgear WNDR3700V2, but I have OpenWRT flashed to it...

**Comment by csawall** [comment]
i may have spoken too soon.  i checked and not all devices have renewed their leases yet to use the new DNS settings.  so we'll see.

as FYI, i have an RPi 2, static IP, outside the DHCP pool, hard wired.

**Comment by crazyaces** [comment]
Setting the IP out of range seems to have helped, no issues so far. Ill keep an eye on it and update later

**Comment by dschaper** [comment]
Okay, keep us up to date on both fronts.

**Comment by jacobsalmela** [comment]
@csawall or @crazyaces do either of you have any updates on this issue?

**Comment by csawall** [comment]
Hi Jacob!  No problems over the last week, but I don't think all of the devices leases renewed yet.  I'm out on business this week, so that's a few less devices to load the system at the moment.  I'll keep an eye on it.  I'll definitely reach out if the issue pops up and try to grab some logs or traces.  Thanks!

**Comment by jacobsalmela** [comment]
@csawall just checking in to see if you have had this happen anymore.  I still have not been able to reproduce this,

**Comment by csawall** [comment]
Thanks for checking back, @jacobsalmela.  I have to say that I haven't seen any noticeable issues.  I'll close this and re-open if I find another problem.

**Comment by TylonHH** [comment]
regarding to @dschaper 
>Try setting the IP address of the Pi to one outside of the DHCP pools address.
I use an FritzBox 7390 and I told the box to give the Pi everytime the same IP (inside the range).
Is that the target?

**Comment by dschaper** [comment]
If you have set up a static lease / reservation and that is the way that you assign the address to the Pi-hole, then you should have no problems. The warning about using an address outside of the range is if you are setting up the Pi-hole to have a static IP address that the DHCP server has no information about. If you use an address from the reserved pool of addresses, then the DHCP server could possibly hand out that address to another client and cause IP collisions on the network.
