### ISSUE TITLE
ntpd front end in settings

### ISSUE THREAD

**Issue by aleph-1** [pi-hole/pi-hole#1492]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
0 (Zero)
---
Guys,
I'm surprised this hasn't been asked before ! 

After 100 days of uptime my raspi clock has drifted - 30 minutes.  I only noticed this when i realised my graphs were 'mis aligned' 

I suggest a front for the basic configuration of the  ntpd client settings would be useful for all users (especially those not wanting to mess with ntp.conf) 

Many thanks  for all the great work.

**Comment by Mcat12** [comment]
Why should Pi-hole have NTP settings when it's not related to what it does?

**Comment by technicalpyro** [comment]
wild guessing below

Perhaps the thought is for users who solely use their pi for this function?

**Comment by Mcat12** [comment]
Out of scope at the moment.
