### ISSUE TITLE
Blacklisted domain not blocked on IPV6

### ISSUE THREAD

**Issue by teknohe** [pi-hole/pi-hole#1496]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**
www.belkin.com added to the blacklist.  I expected it to be blocked on ipv4 and ipv6.  

**[BUG | ISSUE] Actual Behaviour:**
www.belkin.com is blocked on ipv4, and ipv6 requests are forwarded ignoring the blacklist.

**[BUG | ISSUE] Steps to reproduce:**
Disable ipv6 on Linksys AC1900 router.  
Image Raspberry PI with 2017-04-10-raspbian-jessie-lite
Enable SSH on image before initial boot by placing blank "ssh" file in root.
Boot Raspberry Pi
SSH into Raspberry Pi
Change Password
Install Pihole with: curl -sSL https://install.pi-hole.net | bash
Follow install instructions (Can leave ipv6 enabled or disabled, behavior is the same)
Using webadmin, blacklist www.belkin.com
Screenshot:  http://imgur.com/a/7JfjH

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

::: ---=== Your debug token is : nik8nhixnw

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hey @teknohe, from what I can tell from your debug log, you don't appear to have IPv6 blocking enabled. Run `pihole -r` and make sure to select IPv6. If you continue to have the issue afterwards, submit another debug token and we'll go from there :smile:

**Comment by teknohe** [comment]
Hi Wally, 

That was my first thought as well.  This morning I re-imaged the Pi and performed a full reinstall as running pihole -r didn't improve the situation last night.  None the less, I've followed your instructions. 

Enabling ipv4 and ipv6: http://imgur.com/a/4vwSL

ipv6 not being blocked:  http://imgur.com/a/WBCdH

New debug token:  ::: ---=== Your debug token is : y2nby2ukar

Thanks for your help!

**Comment by WaLLy3K** [comment]
Thanks for the new token! Try running `pihole -g` again and that should help us confirm that your blocklists have the correct IPv6 entries in there.

**Comment by teknohe** [comment]
I've run it - unfortunately it's still allowing it.

**Comment by teknohe** [comment]
I'm unsure if this helps - I previously installed pihole with IPV6 enabled on my router and this was not an issue.  However, I was experiencing extremely slow page loads on some important websites I was visiting. 

I disabled IPV6 on my router (Which is still reaching out to www.belkin.com on IPV6), and did a full re-imaging of my Pi / Full reinstall of Pihole.  

Could this be related to my IPV6 being disabled and the router still communicating to www.belkin.com via IPV6?

**Comment by teknohe** [comment]
Ok, I've performed some testing:

- Enable IPV6 on router
- Run pihole -r
- Make sure ipv6 is enabled - Configuration wizard picks up what looks like the ipv6 address on the router
- Restart everything / Refresh network connections on clients
- IPV6 blocking seems to work. 

I can now disable IPV6 on the router and blocking still works.  If I had to guess, having IPV6 disabled on the router during the initial configuration and on reconfiguration stopped Pihole from picking up the IPV6 address which didn't allow Pihole to block ipv6.  

Because I enabled it / allowed it to pickup the address and then disabled it in the router it now seems to work.  

Is this logical in any way?

**Comment by crackers8199** [comment]
have you come up with a way to get this working short of enabling ipv6 on the router?  i really don't care to go messing with my router config, especially given that my ISP doesn't support ipv6...

**Comment by Mcat12** [comment]
@teknohe Your guess sounds correct, that Pi-hole didn't get the correct address at first because IPv6 wasn't enabled. The tricky thing about IPv6 DNS requests is that they can be made via IPv4! The request could be made over IPv4 or IPv6, but it will return whatever IP address type the request specified. So even though IPv6 is disabled on the router, clients can still make IPv6 DNS requests (over IPv4).

@crackers8199 Does your network support IPv6? Check at http://ipv6-test.com/. If it does not support IPv6, then this PR is for you: pi-hole/FTL#63. This PR will let you tell FTL to ignore all IPv6 queries, since your network doesn't have an IPv6 internet connection. Right now, the queries aren't being blocked, per say, but they aren't letting your devices reach the intended server either.
