### ISSUE TITLE
chronoeter.sh doesn't show local IP correctly

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1497]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
pihole -c show complete IPv4 adddress

**[BUG | ISSUE] Actual Behaviour:**
![2017-05-25_13-06-50](https://cloud.githubusercontent.com/assets/24907599/26466274/638d4176-414b-11e7-9464-ecdbfa2c0e37.jpg)

**[BUG | ISSUE] Steps to reproduce:**

-run `pihole -c`
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`rc87xwupj3`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Please update.

**Comment by technicalpyro** [comment]
fixed thanks guys 
![2017-05-26_8-42-42](https://cloud.githubusercontent.com/assets/24907599/26499359/938db9d8-41ef-11e7-9ce3-4243466c7db5.jpg)

**Comment by technicalpyro** [comment]
worth noting everything was still restarting when  i took the SS
