### ISSUE TITLE
Failed to execute operation: Bad message

### ISSUE THREAD

**Issue by pcfreak09** [pi-hole/pi-hole#1503]
Hello, I just want to set up DNSCrypt on my Rasberry Pi.

I have used this guide:

https://github.com/pi-hole/pi-hole/wiki/DNSCrypt

After I entered the command

"Sudo systemctl enable dnscrypt-proxy @ .service"

I get the following error:

"Failed to execute operation: Bad message"

Anyone have any idea where could be the problem?

**Comment by dschaper** [comment]
Did you include those spaces? There shouldn't be any spaces in the command. And `sudo` is all lower case.

`sudo systemctl`

**Comment by pcfreak09** [comment]
Sudo I had small letters. I did not have any spaces. Has been inserted by copying with.
The original command was:
`sudo systemctl enable dnscrypt-proxy@.service`

**Comment by dschaper** [comment]
What does the command:

`sudo systemctl status dnscrypt-proxy@.service`

return?

**Comment by pcfreak09** [comment]
Failed to execute operation: Bad message

**Comment by dschaper** [comment]
What OS are you using?

**Comment by pcfreak09** [comment]
Linux raspberrypi 4.9.24+

I have used this guide:

https://github.com/pi-hole/pi-hole/wiki/DNSCrypt

**Comment by dschaper** [comment]
That's a community written Wiki entry, I don't use it myself, so I'm not sure where your problem may be at. @cybrnook Do you have any ideas?

**Comment by cybrnook** [comment]
That command never worked for me, but if you read a little further down. There is this entry:

If the sockets come up Inactive(dead)

On some configurations the above "enable" command will create the individual sockets and define the services, but not actually enable the services. This will mainly occur if the default.target does not match the service target. To remediate, enable the various services individually:

sudo systemctl enable dnscrypt-proxy@dnscrypt.eu-dk.service

Do this for all selected dnscrypt end-points. Afterwards reboot, or alternatively you can test immediately by also starting the services:

sudo systemctl start dnscrypt-proxy@dnscrypt.eu-dk.service


Keep in mind this is an alternate command for a "dead" service, not a bad syntax. So I think you need you check your commands again, make sure you're in the right folders, and have the correct files in there with you.

**Comment by dschaper** [comment]
I've edited the Wiki entry to ask users to put the user created service files in the `/etc/systemd/system` tree instead of the system controlled directory. But not having used that Wiki I'm not sure what to troubleshoot. (I run all my DNSCrypt in Docker, as I run my own upstreams as well.) But thank you very much for your tips!
