### ISSUE TITLE
Apple News - Read Full Story Ads

### ISSUE THREAD

**Issue by matrixfox** [pi-hole/pi-hole#1504]
Google/Adsense ads are being displayed using the iPhone News app. You know, the pre-installed News app that comes without your permission.

![img_0759](https://cloud.githubusercontent.com/assets/1642498/26593018/75a4029e-4517-11e7-86ad-05e814c6cc92.PNG)

**Reproduce?**

1. Open Apple News
2. Tap a news article
3. Scroll down until `Read Full Story` is triggered.

**What to expect?**

When `Read Full Story` is triggered a UIWebView is displayed. Google ads will be displayed in the header and footer of this news article.

# Content Blockers

Only content that is loaded in a Safari View Controller or the Safari App is filtered by active content blocker extensions. Content that is downloaded by an application, either directly or in a UIWebView/WKWebView, is not filtered.

Giving a long story short. Apples engineers have reviewed my request and have concluded that there is no supported way to achieve the desired functionality given the currently shipping system configurations.

Pi Hole works at a DNS level, ads are supposed to be blocked in non-traditional places like mobile apps. How can I block Apple News ads once and for all? Any pointers on how to debug this?

**Comment by technicalpyro** [comment]
this appears to be apples way of implementing [QUIC ](https://en.wikipedia.org/wiki/QUIC)

**Comment by wioxjk** [comment]
This is why I have blocked QUIC in my network :)

**Comment by Mcat12** [comment]
@matrixfox Does disabling QUIC fix the issue?

**Comment by technicalpyro** [comment]
it is a QUIC-like issue.  the app queries an apple dns server which allows it to display the ads when the apple server being queried is blocked the app does not work

**Comment by WaLLy3K** [comment]
@matrixfox is using the Apple News app through iOS, which as he said is being called through a UIWebView instead of a standard browser - so disabling QUIC like you can with Chrome flags simply isn't an option.

@wioxjk, am I to assume you have blocked UDP via 80/443 using `iptables`? ([Example here](http://wiki.squid-cache.org/KnowledgeBase/Block%20QUIC%20protocol)). This sounds like it'd be the most elegant solution to the issue.

**Comment by jacobsalmela** [comment]
@matrixfox I cannot replicate this.  See the screenshots below from an iPhone:
![2017-07-06 21 44 29](https://user-images.githubusercontent.com/3843505/27941179-f1facbee-6294-11e7-9e1e-1daaca7649b7.png)
![2017-07-06 21 46 54](https://user-images.githubusercontent.com/3843505/27941185-f5379ddc-6294-11e7-9bfa-b03f908e7b19.png)

**Comment by technicalpyro** [comment]
@jacobsalmela as i was able to reproduce this on my ipad was this in just the preview of the news story or when you tapped to "view full story" at the sources website?

**Comment by jacobsalmela** [comment]
Hmm, I don't recall...I'll explore a bit more

**Comment by neeldug** [comment]
Been getting the exact same issue as @jacobsalmela in his screenshot, even on the sources website.

**Comment by WaLLy3K** [comment]
@matrixfox, are you still experiencing this issue? If so, please reply to this ticket and we'll follow it up further. It seems that this is an isolated case, but I'm closing the ticket due to inactivity.

**Comment by jacobsalmela** [comment]
I realize this is closed, but just mentioning I no longer see the block page appearing in Apple News (on any iOS devices).
