### ISSUE TITLE
Master Blacklist combined as one ASCII database based on different text files

### ISSUE THREAD

**Issue by SchneiderDe** [pi-hole/pi-hole#1505]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

---
**[FEATURE REQUEST]:**

It is excellent to have a possibility to configure seperate blacklists.

Having done that, the question is to use it.

I suggest a feature to mapping and combining such blacklists 

1) to a single interface of the server
2) to a single host making the DNS queries
3) to multiple hosts making the DNS queries

The combined list may not be available for user handling from the web interface. This may be only for internal functioning for performance reasons.

With this system, certain blacklist would be combined to one ASCII file put together for DNS queries.

Currently, pi-Hole uses ASCII text file database to store and search information. It searches line by line and compares all domains in it. If there are many such files, it will go sequentially one by one to find a domain name in these ASCII text files. 

Lets say the domain in question is configured in file_5.text. Here, it will go through all the four files, file_1.txt, file_2.txt, file_3.txt, file_4.txt before landing in the file file_5.txt.

With this, it connects to the haddrive five times and loads it into memory.

With my suggestion, if - as in the above example - all files are combined into one, then the SEARCHES PER QUERY would be much faster. By installing such a system, one could enhance it to detect queries coming from a particular host and combine text files based on those mappings.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
please also make this a feature request that could be voted on using the discourse forums http://discourse.pi-hole.net

**Comment by SchneiderDe** [comment]
Thanks technicalpyro 💯 

Can I have your vote and comment here please:
https://discourse.pi-hole.net/t/master-blacklist-combined-as-one-ascii-database-based-on-different-text-files/3462

**Comment by dschaper** [comment]
Topic opened on Discourse, closing this one.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/master-blacklist-combined-as-one-ascii-database-based-on-different-text-files/3462/1
