### ISSUE TITLE
2 ips? this has no sense

### ISSUE THREAD

**Issue by jmverges** [pi-hole/pi-hole#1511]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_8_
---

**[BUG | ISSUE] Expected Behaviour:**
PiHole is having 1 IP

**[BUG | ISSUE] Actual Behaviour:**
PiHole is having 2 different IPs

**[BUG | ISSUE] Steps to reproduce:**
ssh root@ip1 
ssh root@ip2
both works
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jmverges** [comment]
I'm getting crazy with this, how is posible PiHole is getting to ips? I'm setting up one in interfaces, but the /admin/ says is other one. And then I can access both of them via ssh...

**Comment by dschaper** [comment]
What OS are you running? We set up static IP's via `/etc/dhcpcd.conf` at the bottom, according to Raspbian policy. We are evaluating how to better install on non-Raspberry Pi platforms.

**Comment by anudeepND** [comment]
Do you have both ethernet and WiFi connected to the network?

**Comment by jmverges** [comment]
it is a pi zero, but I used "interfaces" as it was having in there enabled auto dhcp

**Comment by jmverges** [comment]
Well, I'm not sure what I did but all is good now. Cheers
