### ISSUE TITLE
Pi-hole not used as DNS server with DHCP enabled

### ISSUE THREAD

**Issue by MrAxle** [pi-hole/pi-hole#1512]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**
With Pi-hole's DHCP server being enabled, all client devices would use pi-hole as their DNS server, and following ad-blocking capabilities would function as normal

**[BUG | ISSUE] Actual Behaviour:**
All connected devices discover 2 external DNS servers with IPv6 addresses, along with Pi-hole with its internal IPv4 address. Queries appear to default to the IPv6 DNS servers, effectivly bypassing Pi-hole and rendering its purpose redundant. No ads are blocked, and http://pi.hole/admin/ returns "DNS address could not be found"

**[BUG | ISSUE] Steps to reproduce:**

- Fresh install of Raspbian Jesse (with Pixel)
- Install Pi-hole the usual way (curl -sSL https://install.pi-hole.net/ | bash)
- Enable DHCP server on Pi-hole (and disable on router)
- Force renew DHCP leases and clear DNS cache on clients. Pi-hole is using dns addresses

**Additional information:**
Blocking is enabled on _both_ IPv4 and IPv6

**Possibly relevant info:**
The network modem/router combo is ISP provided, and many settings do not exist (or, at least, do not exist on the user-facing web GUI). It has no option to set a custom DNS, hence the need to have Pi-Hole run the DHCP server. That may mean this is a "Not a Pi-hole problem, go fix your router" type problem, but I'm not sure how to test that to know for sure.

Yes, I am aware that manually adding Pi-hole as a DNS server in Windows IPv6 settings will fix the issue on a per-machine basis, but that doesn't resolve the issue for some of the devices on the network (IoT devices, and some of the smartphones etc.)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
the symptoms you describe make me think dnsmasq is still starting when you are testing this.  Does the behavior remain even after a couple minutes ?

the other thought i had is are you using some form of internet security software the asserts its own "secure" dns?

**Comment by DL6ER** [comment]
> The network modem/router combo is ISP provided, and many settings do not exist (or, at least, do not exist on the user-facing web GUI).

Can you specify in more detail which model this is?

We have been observing lately that some routers allow only switching off IPv4 DHCP service and will still continue to distribute IPv6 RA packets (which include vital information like the prefix, but also DNS information).
I'm in the lucky situation that my ISP router (Telekom Speedport W 723V) is not aware of IPv6 DNS servers (or doesn't know how to hand them out in the RAs), so this is no problem for me.

Do you have experience with sniffing on the wire (e.g. using `wireshark` or `tcpdump`) so we could verify if the issue you are seeing is caused be RAs your ISP router is sending?

**Comment by MrAxle** [comment]
I'm feeling its a network thing, not a client thing, given it is affecting Windows, Linux and Android alike, ruling out an anti-malware DNS system. It's been ongoing since I first discovered it two days ago, so the behavior definitely does remain after a couple of minutes.

The Router is a ~~Technicolour~~ Technicolor EPC3940ADL, however it sometimes appears as a Cisco branded device (Cisco EPC3940L) in a few strange locations... No-where in either the (extremely limited) documentation that came with it, or anywhere on the web controller for it does it mention anything to do with IPv4 or IPv6, and the only DHCP option is Enable|Disable, Lease time, Start Address and Pool size.

So I got Wireshark running, I'm not sure what I'm supposed to be looking for specifically, but this *seems* to be what we're all interested in:
Source: Gateway
Destination: ipv6-allnodes
Protocol: ICMPv6
Info: Router Advertisment from [MAC Address]
Details (abridged): ICMPv6 Option (Recursive DNS Server [IPv6 Address]), Recursive DNS Servers: [ISP domain name] ( [same IPv6 Address])

That IPv6 address is associated with my ISP, so would I be correct in assuming that to be the answer we're looking for? "This be a router problem, fellas!"?

**Comment by MrAxle** [comment]
I've got it working. (Woo!). Here's how:

new file in /etc/dnsmasq.d/05-custom-settings.conf
```
enable-ra
ra-param=eth0,high,10,1200
```
That seems to do the trick. With that added, pi.hole now is now redirecting to http://pi.hole/admin/ and loading the web interface, ad.doubleclick.net is returning the "blocked website" page, and ads aren't showing on ads-blocker.com/testing. Goals achieved!

Not sure if it's relevant, but `enable-ra` is in the pi-hole generated file in the same folder (/etc/dnsmasq.d/02-pihole-dhcp.conf), but it is commented out. The comments in the file it is in say that those lines are commented in and out based upon settings in the web interface, but I can't find the setting that is changing it. I haven't tested to see if it's only enable-ra that's needed to make the whole thing work, or if `ra-param=eth0,high,10,1200` is also needed. My guess is both, as setting the RA param to "high" should be overriding the priority of the routers RAs (which is, by default, "medium").

I am aware that the router may be broadcasting information critical to the correct operation of IPv6 that now may be overriden by Pi-hole, but I still have internet, everything is still working and http://ipv6-test.com/ is indicating native ipv6 support, so I'm content to just leave it alone, unless anyone can spot a massive security hole or stability problem that I should be aware of.

**Comment by darkrain-nl** [comment]
The problem I see is this (from the dnsmasq manual)

> When RA is enabled, dnsmasq will advertise a prefix for each dhcp-range, with default router as the relevant link-local address on the machine running dnsmasq.

So your IPv6 default router will now be the machine running PiHole, this is no problem if that machine is actually a router, but if it's not (which is way more likely) then this could lead to IPv6 routing problems...
