### ISSUE TITLE
ftl update is blocked by pihole

### ISSUE THREAD

**Issue by Binog** [pi-hole/pi-hole#1520]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{not familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**
::: FTL out of date
:::
::: Downloading latest version of FTL...
:::  Detected ARM-hf architecture (armv7+)
:::  Installing FTL... curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Verbindungsaufbau abgelehnt
sha1sum: pihole-FTL-arm-linux-gnueabihf.sha1: Datei oder Verzeichnis nicht gefunden
failed (download of binary from Github failed)

**[BUG | ISSUE] Actual Behaviour:**
sudo pihole -up

::: FTL out of date
:::
::: Downloading latest version of FTL...
:::  Detected ARM-hf architecture (armv7+)
:::  Installing FTL... curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Verbindungsaufbau abgelehnt
sha1sum: pihole-FTL-arm-linux-gnueabihf.sha1: Datei oder Verzeichnis nicht gefunden
failed (download of binary from Github failed)

**[BUG | ISSUE] Steps to reproduce:**
sudo pihole -up
-
-
-
-

**(Optional)**
by disabling the pihole-blocking, I was able to reach above url (GitHub-produ....amazonaws.com) and was able to download and install the update.

Maybe it is possible to automatically whitelist the updating urls,..

**Comment by jacobsalmela** [comment]
Can you post the output of 
```
pihole -q github-production-release-asset-2e65be.s3.amazonaws.com
```
Or run it from the dashboard?

**Comment by technicalpyro** [comment]
about two hours ago github suffered a major outage this may be related to that

**Comment by DL6ER** [comment]
Good catch! Thanks @technicalpyro

**Comment by Binog** [comment]
indeed good catch!,. well at least the id wasn't blacklisted by any of the blacklists. pihole -q. If no one else has that problem,...

**Comment by jacobsalmela** [comment]
Since it was an outage and not related to Pi-hole, I'm closing this.
