### ISSUE TITLE
Temp files after installation/upgrade

### ISSUE THREAD

**Issue by dracenmarx** [pi-hole/pi-hole#1525]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
The files /tmp/pihole-FTL-arm-linux-gnueabihf and /tmp/pihole-FTL-arm-linux-gnueabihf.sha1 should be deleted after the installation is done.

**[BUG | ISSUE] Actual Behaviour:**
The files are still existing after the installation is complete.

**[BUG | ISSUE] Steps to reproduce:**

- Run curl -sSL https://install.pi-hole.net | bash
- Choose "update and keep settings" (it might also work with a fresh installation, but I didn't test it)
- After setup is done, run ls /tmp and see the two files pihole-FTL-arm-linux-gnueabihf and pihole-FTL-arm-linux-gnueabihf.sha1

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
@DL6ER Is this intentional?

**Comment by DL6ER** [comment]
Hmm, they can be deleted without causing harm
