### ISSUE TITLE
Valid HTML is faster than just an empty document

### ISSUE THREAD

**Issue by Firesphere** [pi-hole/pi-hole#1526]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
**[OTHER]:**

Experiments show that returning a valid HTML document instead of a completely empty document is slightly faster.

Despite a slightly larger network footprint, browsers are faster parsing a valid HTML document versus an empty document, where most browsers seem to work alike that an empty response confuses them.

**Comment by Stibbons** [comment]
I'd like to have more information to confirm this, I don't see why browser cannot handle empty document. It is pretty bad though, to return a empty doc anyway, for the user at least!

**Comment by Mcat12** [comment]
Pi-hole does return valid HTML when it blocks a page. https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L69-L75

**Comment by WaLLy3K** [comment]
Have you found any further information on this issue, @Stibbons?

> It is pretty bad though, to return a empty doc anyway, for the user at least!

You're absolutely right, which is why we're working on making it more user friendly! :smile:

**Comment by Stibbons** [comment]
And I agree !

**Comment by Firesphere** [comment]
I have found that this seems to be an issue related to my router, an Fritz!box, not resolving locally for unknown reason, it just refuses to resolve instead of returning the empty gif.

I need to investigate what actually happens in the routing of my LAN before I can give a more detailed report.

**Comment by jacobsalmela** [comment]
@Firesphere do you have any more information to report?

**Comment by Firesphere** [comment]
I've done some investigation. So far, it seems it's not about the response content, but my system not actively resolving to Pi-Hole, but hitting a address not found.

**Comment by jacobsalmela** [comment]
So it seems the issue now is beyond the scope of the OP.  I'll close this and you can open a new issue if needed about your devices not actively resolving to Pi-hole.
