### ISSUE TITLE
Javascript Is Disabled error in admin

### ISSUE THREAD

**Issue by beaurepair** [pi-hole/pi-hole#1531]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{3}_

**[BUG | ISSUE] Expected Behaviour:**
Admin page workds

**[BUG | ISSUE] Actual Behaviour:**
Admin page shoes "Javascript is disabled" error (when javascript is enabled)

**[BUG | ISSUE] Steps to reproduce:**
open admin.
Looks like some files aren't being fully transferred and are cut off.
This only occurs on my HP Chromebook 11, other devices work fine.

Uncaught SyntaxError: Invalid or unexpected token
footer.js:232 Uncaught SyntaxError: Unexpected end of input
index.js:1 Uncaught SyntaxError: Unexpected token <

As you can see below contents of header.js is cut off

$(function () {
  $("[data-mask]").inputmask();
});

$(function(){
	$("#custom1val").ipAddress({s:4});
	$("#custom2val").ipAddress({s:4});
	$("#custom3val").ipAddress({v:6});
	$("#custom4val").ipAddress({v:6});
	$("#DHCPfrom").ipAddress({s:4});
	$("#DHCPto").ipAddress({s:4});
	$("#DHCProuter").ipAddress({s:4});
});

$(".confirm-reboot").confirm({
	text: "Are you sure you want to send a reboot 

index.js also seems to have php in it!

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`ampagevuav`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
The debug log detected errors in your web interface git repo: `Pi-hole Dashboard repository damaged.`
Have you edited the web files?

**Comment by beaurepair** [comment]
Haven't edited anything. Should I uninstall/reinstall pihole?

**Comment by Mcat12** [comment]
Run these commands:
```
sudo rm -r /var/www/html/admin
sudo git clone --depth 1 https://github.com/pi-hole/AdminLTE.git /var/www/html/admin
```

**Comment by beaurepair** [comment]
was getting seg faults and other weird issues. I think the sd card was dead. works fine now on fresh install

**Comment by krissharm** [comment]
Top man - that fixed it

> sudo rm -r /var/www/html/admin
sudo git clone --depth 1 https://github.com/pi-hole/AdminLTE.git /var/www/html/admin
