### ISSUE TITLE
ignoring .pullapprove.yml

### ISSUE THREAD

**Issue by bcambl** [pi-hole/pi-hole#1535]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

8

---

**[BUG | ISSUE] Expected Behaviour:**
Ignored files typically are not committed to projects (some exceptions apply)

**[BUG | ISSUE] Actual Behaviour:**
`.pullapprove.yml` is committed to the project but also seems to be ignored via `.gitignore`

**[BUG | ISSUE] Steps to reproduce:**
N/A

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
It looks like I've added and removed and added back that in the `.gitignore`. Looks to be something to do with IDEA but since we don't ignore the other `yml`s I would assume that it's not an issue to remove it from the ignore and version it again. I think we've just been editing it manually through GitHub directly for updates.

**Comment by jacobsalmela** [comment]
@dschaper is there any action we need to take on this issue?

**Comment by dschaper** [comment]
We can take the `pullapprove.yml` out of the `.gitignore` file and have it versioned with the rest of the meta files. I still am not sure why it has been bounced a few times in and out of `.gitignore` though.

**Comment by WaLLy3K** [comment]
@dschaper, @jacobsalmela: Has there been any update on this issue?

**Comment by jacobsalmela** [comment]
I kind of lost track on on this one...I think we can just remove it from `.gitignore` and then we can close this.
