### ISSUE TITLE
dnsmasq syntax error after adding new wildcard blacklist

### ISSUE THREAD

**Issue by dracenmarx** [pi-hole/pi-hole#1536]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
There should be no error when adding a wildcard blacklist domain.

**[BUG | ISSUE] Actual Behaviour:**
Error message: Restarting DNS forwarder and DHCP server: configuration syntax check failed!

**[BUG | ISSUE] Steps to reproduce:**
- Execute $ pihole -wild example.com

I am not sure if this is a problem with pihole or with dnsmasq.
For some reason, dnsmasq is not able to handle IPv6, although my system is correctly setup and I am using the latest stable Debian release.
In case there is a problem with specific system configuration and/or dnsmasq versions, then I think pihole should detect it and not add the IPv6 entries into the config file.

I could track the "syntax error" in file /etc/dnsmasq.d/03-pihole-wildcard.conf

```
address=/example.com/0.0.0.0
address=/example.com/::/0
```

I had to remove the line "address=/example.com/::/0" .

**(Optional) Debug token generated by `pihole -d`:**

`wx50q4m42p`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
[This](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/list.sh#L125) line should also remove the `/0` like the IPv4 does.
