### ISSUE TITLE
Error in `systemctl': double free or corruption (fasttop): 0x564777a8

### ISSUE THREAD

**Issue by mvught** [pi-hole/pi-hole#1538]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
2
--
**[BUG | ISSUE] Actual Behaviour:**
::: FTL version is now at v2.9.1
:::
::: Starting pihole-FTL service... done.
:::
::: Enabling pihole-FTL service to start on reboot...*** Error in `systemctl': double free or corruption (fasttop): 0x564777a8 ***
/etc/.pihole/automated install/basic-install.sh: line 758: 29984 Aborted                 systemctl enable "${1}" &> /dev/null
**[BUG | ISSUE] Steps to reproduce:**
pihole -up

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Is this a new SD card? It looks like it might be corrupted. Run `pihole -d` for a debug token.

**Comment by mvught** [comment]
new its 4 months old, and ik had it before when i update to 2.9. before 2.8 it was no problem

Log:
::: FTL version is now at v2.8
:::
::: Starting pihole-FTL service... done.
:::
::: Enabling pihole-FTL service to start on reboot... done.

**Comment by DL6ER** [comment]
> Error in `systemctl': double free or corruption (fasttop): 0x564777a8

Indicates that the problem is within `systemctl` rather than Pi-hole. Is it reproducible or a one-time glitch?

**Comment by mvught** [comment]
one-time i see:
Running pihole update
::: Checking for updates...
::: Pi-hole Core:   up to date
::: FTL:            up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!

its only when the update of FTL is there, can i fix this with a reinstall of pihole?

**Comment by DL6ER** [comment]
It is unlikely that this is a Pi-hole bug. It looks very similar to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764613) one.

Please try
```
sudo systemctl enable pihole-FTL
```
to reproduce your issue (this is what was called when you saw the crash).

**Comment by mvught** [comment]
see log:

`Synchronizing state for pihole-FTL.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d pihole-FTL defaults
insserv: warning: script 'K36cups' missing LSB tags and overrides
insserv: warning: script 'cups' missing LSB tags and overrides
insserv: There is a loop at service cups if started
insserv: There is a loop between service plymouth and mountnfs if started
insserv:  loop involving service mountnfs at depth 4
insserv:  loop involving service networking at depth 3
insserv: There is a loop between service cups and udev if started
insserv:  loop involving service udev at depth 1
insserv: There is a loop at service plymouth if started
insserv: There is a loop between service cups and mountall if started
insserv:  loop involving service mountall at depth 4
insserv:  loop involving service checkfs at depth 3
insserv: There is a loop between service cups and mountall-bootclean if started
insserv:  loop involving service mountall-bootclean at depth 5
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Max recursions depth 99 reached
insserv:  loop involving service mongodb at depth 1
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv:  loop involving service urandom at depth 7
insserv:  loop involving service mountnfs-bootclean at depth 6
insserv: There is a loop between service cups and mountkernfs if started
insserv:  loop involving service mountkernfs at depth 1
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting cups depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x55b8d7a8 ***`

**Comment by mvught** [comment]
i see its will starting cups i will have look at this ;)
