### ISSUE TITLE
Installer continues if user presses cancel on interface or protocol selection screens

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#154]
If the user really wanted to cancel, they can hit Ctrl+C after it continues on, but it would be nice for the cancel button to actually work.

**Comment by DonLexos** [comment]
This should be closed since it was fixed in 2.4 (or at least soon after that release)

**Comment by PromoFaux** [comment]
I'll need to double check that with @jacobsalmela, as there is still an open PR against it (#214)

**Comment by PromoFaux** [comment]
fixed in 29e0e17
