### ISSUE TITLE
IPv6 Wont Disable no matter what i do!

### ISSUE THREAD

**Issue by articrevised** [pi-hole/pi-hole#1540]
no matter what i try i have litteraly tried everything and the last think i would not want to do is completely reinstall raspbian and pihole.

no matter how many times i reconfigure pihole it still says ipv6 not configured but then i check the admin panel and the query log and ipv6 and ipv4 are still coming through. all i want to do is disable ipv6

please help!

**Comment by dschaper** [comment]
Check out our FAQ on this subject over at https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652 and see if that fixes things for you.

**Comment by Mcat12** [comment]
You have disabled IPv6 **access** to your Pi-hole, but clients can still query for IPv6 addresses over an IPv4 connection. If you don't have an IPv6 internet connection, then these responses won't do anything, and the guide that @dschaper linked will show you how to ignore those responses.

**Comment by articrevised** [comment]
thank you @dschaper that worked!
