### ISSUE TITLE
New chronometer output cut off on 2.8 inch raspi display

### ISSUE THREAD

**Issue by r0ckarong** [pi-hole/pi-hole#1546]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_6_

---
**[BUG REPORT]:**

**[BUG | ISSUE] Expected Behaviour:**

When running chronometer on a 2.8 inch display on the raspi I expect it to fit the configured console screen when following the instructions. 

**[BUG | ISSUE] Actual Behaviour:**

The text is misformatted and cut off. The pihole logo is not visible on the screen. Updated visibly distort the diplay as data changes. There is visible cutoff of lines which cause the text to shift further.

**[BUG | ISSUE] Steps to reproduce:**

-Install pihole
-Install 2.8 inch display with fbtft driver
-Run chronometer.sh on display with the recommended settings (UTF8, guessed charset, Terminus font, 6x12 framebuffer font)

Text is distorted.
![2017-06-21 19 30 57](https://user-images.githubusercontent.com/4920542/27397907-3920fc20-56b8-11e7-858e-bf699dc8079f.jpg)

**Comment by DL6ER** [comment]
We are working on this issue, already. @WaLLy3K can comment on this.

**Comment by WaLLy3K** [comment]
Out of interest, what's the result of `stty size` when you run it on that screen? It *appears* to be `20 53`, which should fit just fine with the [planned changes](https://github.com/pi-hole/pi-hole/pull/1518).

**Comment by r0ckarong** [comment]
Yes correct, 20 53 is what I'm getting with this configuration.

**Comment by cybrnook** [comment]
Sam here, still on chrono-small.... working fine still, but missing everything else :-)

**Comment by r0ckarong** [comment]
@cybrnook I just reverted to master branch and just copied over the "fixed" chronometer script and it works well. At least a workaround until this is fixed in the next release.

**Comment by cybrnook** [comment]
Still having to manually revert to the script from the chrono-small initial branch, while keeping the major components up to date.

Currently on:
Pi-hole Version v3.1.4 Web Interface Version v3.1 FTL Version v2.10

And notice that on my small screen, the "Top Domain" no longer reports. Perhaps this is already known, and addressed. However, since I have to use the older chronometer.sh script from the original small-tweak branch, may be a side affect, or something to look in to.

[IMG]http://img.techpowerup.org/170806/pihole-stats.png[/IMG]

**Comment by PromoFaux** [comment]
Just checked on the `development` branch and it looks like it's fixed for next release

![image](https://user-images.githubusercontent.com/1998970/29016474-81af47ce-7b4a-11e7-9191-5f5ea1f45950.png)

**Comment by cybrnook** [comment]
I checked out the development branch, and still the same issue. (But I notice you are on 3.1-248 Pi-Hole, while the dev branch seems to be 3.0-269)

![pihole - stats](https://user-images.githubusercontent.com/22136734/29048872-e42fca8a-7ba0-11e7-94ed-2f0a31525e89.PNG)

**Comment by WaLLy3K** [comment]
It sounds like your Pi-hole Core failed to update. You might want to try `pihole checkout core development` and see how that goes. If that fails, then you could try this:

`wget -qO - https://raw.githubusercontent.com/pi-hole/pi-hole/714fd93292880e999706419480f4c59a0defb77f/advanced/Scripts/chronometer.sh | sudo tee /opt/pihole/chronometer.sh`

**Comment by cybrnook** [comment]
That's exactly what I did, "pihole checkout core development", and it got me to the above.

I will just wipe my Pi and start over. Maybe wait for the official release. Just unfortunate, as the official release today is broken on small screens.

**Comment by cybrnook** [comment]
Works as expected after a fresh install, and then manually uploading the updated chronometer script in the dev branch.

I must have left some dirty changes around that prevented the update/branch change from happening cleanly.

**Comment by WaLLy3K** [comment]
> Just unfortunate, as the official release today is broken on small screens.

Yeah, I'm sorry about that! :(

**Comment by jacobsalmela** [comment]
Resolved in v3.2 (#1518)
