### ISSUE TITLE
pihole DHCP win10 woes.

### ISSUE THREAD

**Issue by H4vC** [pi-hole/pi-hole#1551]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated* (afaik)
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues? (afaik) utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
2

---
**[BUG REPORT | OTHER]:**

Having the pihole (on a debian box) as DHCP for both ipv4 and ipv6 doesn't give win 10 host an ipv4 address resulting in it using an 169.254.xx.xx addr, this goes with a Static DHCP leases as well as without one.

**[BUG | ISSUE] Expected Behaviour:**

Assignment of an ipv4 adress.

**[BUG | ISSUE] Actual Behaviour:**

Doesn't assign an ipv4 address resulting in windows defaulting in windows auto allocating 169.254.XXX.XXX and the client not being able to reach ipv4 hosts.
Ipv6 seems to work fine.

**[BUG | ISSUE] Steps to reproduce:**

- WIN 10 15063
- use pihole as DHCP for both ipv6 and ipv4

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
@H4vC Sorry for the delay in responding.  Will you please generate another token if you are still having this issue?

**Comment by H4vC** [comment]
I've dropped the use of pihole from my network so I can't generate a new token at this point in time.

Sorry.
