### ISSUE TITLE
Typo in /opt/pihole/piholeDebug.sh

### ISSUE THREAD

**Issue by eehmke** [pi-hole/pi-hole#1552]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

Did not find the script in github, otherwise would have created a pull request.
---
**[BUG REPORT | OTHER]:**

The script puts out the message 
"Logging will automatically teminate in %s seconds\n"

**[BUG | ISSUE] Expected Behaviour:**
The message should read
"Logging will automatically terminate in %s seconds\n"

**[BUG | ISSUE] Actual Behaviour:**
See above

**[BUG | ISSUE] Steps to reproduce:**

call command 
pihole -d

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Thanks, the file is located at https://github.com/pi-hole/pi-hole/blob/development/advanced/Scripts/piholeDebug.sh

**Comment by jacobsalmela** [comment]
In the revamp of the debug script, I removed the timer in place of just grabbing some output from `pihole.log`; not sure if that's the way to go or not, but it would solve this issue.  See #1565 and let me know your feedback.

**Comment by dschaper** [comment]
Closed, no response.
