### ISSUE TITLE
Wiki for using VPN and PiHole is unclear

### ISSUE THREAD

**Issue by DerfOh** [pi-hole/pi-hole#1553]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

> Afterwards, we change the interface of Pi-hole to eth0 (your local network adapter instead of the VPN adapter tun0). This can conveniently be done by using pihole -r + Reconfigure.
> 
> After a restart of the OpenVPN server, all clients should be able to see all devices within your (at home) local network. This is an example running on a distant server, which is connected through the VPN and can successfully communicate with all internal devices:

**[BUG | ISSUE] Actual Behaviour:**

Blocking works using eth0 but stops working for tun0 thus ending expected behavior for VPN.

**[BUG | ISSUE] Steps to reproduce:**

- Follow the guide with a fresh install.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Suggested Fix:**
What finally worked for me after pulling out my hair for the last couple days was the following command via the cli:
```bash
pihole -a -i all
```
Nowhere in the wiki does it suggest that this command even exists... Please add this to the guide for future users 👍

**Comment by nobody1407** [comment]
I've the same problem with pi-hole + DNSCrypt and OpenVPN.. The connection between inner devices and devices outside the local network works. 


```
Pi-hole local IP: 192.168.178.37
tun0 inet Adresse:10.8.0.1
```
I tried every various combinations for the line **push "dhcp-option DNS ......"**
Maybe I forgot another important thing?

```
dev tun
proto udp
port 55194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh4096.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 0.0.0.0 "
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.178.37"
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io
```

> What finally worked for me after pulling out my hair for the last couple days was the following command via the cli:
> `pihole -a -i all`

Doesn't work for me.. It would be nice to get no bald head :wink:

**Comment by DL6ER** [comment]
Yes, your use case was never intended by the Wiki which was tailored for VPNs running on virtual servers where you won't/shouldn'b be sending DNS queries to `eth0`. I will nevertheless add your suggestion with some remarks.

You are right, this switch is undocumented as it is triggered internally from the Settings page which offers you this choice on the Settings page:
![screenshot at 2017-07-08 01-20-28](https://user-images.githubusercontent.com/16748619/27980105-b11fbc3c-637b-11e7-843e-4ec6702d6286.png)

**Comment by WaLLy3K** [comment]
@DL6ER, has this suggestion been added? I've taken a brief look over the article, but I can't find it. (Then again, I was never a good skim reader!)

**Comment by jacobsalmela** [comment]
It wasn't, but [I added it in](https://github.com/pi-hole/pi-hole/wiki/OpenVPN-server:-Dual-operation:-LAN-&-VPN-at-the-same-time/e2b439b97e822b80fc72fb53e2d45e2201e5392e) as I was recently editing several other pages in the wiki.
