### ISSUE TITLE
api token wont pop up ive been waiting for a hour now

### ISSUE THREAD

**Issue by articrevised** [pi-hole/pi-hole#1554]
so i went to get my api token so i can add stuff to the lists from a chrome extensions and ive pressed show api token and it wont come up and ive waited a little over a hour

**Comment by Mcat12** [comment]
Did you get the token?

**Comment by articrevised** [comment]
yea.  i had a popup blocker extension on and i forgot to white list my pihole ip and it was blocking it from making a new tab with the code
