### ISSUE TITLE
Domain not whitelisted if it is listed in uppercase in blocklist file(s)

### ISSUE THREAD

**Issue by tjv76435** [pi-hole/pi-hole#1555]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
If a domain is present in a blocklist in UPPERCASE, it should be able to be whitelisted.

**[BUG | ISSUE] Actual Behaviour:**
If a domain is present in a blocklist in UPPERCASE, it cannot be whitelisted effectively.
Example: domain:"dir.bg" (listed in "list.25.v.firebog.net.domains" and "list.preEventHorizon").

**[BUG | ISSUE] Steps to reproduce:**
1. Open dir.bg (the page is blocked)
2. Whitelist dir.bg
3. Open dir.bg (the page is blocked again)
4. Query blocklists for "dir.bg" - the domain is present as "DIR.BG"

Perhaps a conversion to lowercase should be added when parsing the adlist?

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hi @tjv76435, thanks for letting us know of the issue!

I use a utility to retrieve, extract and convert certain lists to a domains only format, and one of the things I *didn't* do was forcibly convert the names to lower case. I've corrected that now, and manually refreshed `http://v.firebog.net/hosts/Airelle-hrsk.txt` (where `DIR.BG` was located).

Basically, run `pihole -g` and it'll grab the updated list :)

**Comment by jacobsalmela** [comment]
@tjv76435 will you verify that this issue is resolved or not?

**Comment by WaLLy3K** [comment]
As per #1710, this issue should be permanently fixed in next release as all domains will be converted to lower case.

**Comment by jacobsalmela** [comment]
Resolved in v3.2 (#1710)
