### ISSUE TITLE
Blocked site leads to Apache2 default page.

### ISSUE THREAD

**Issue by kingdevnl** [pi-hole/pi-hole#1559]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
When i visit a Blocked website it should show the Website Blocked Screen.

**[BUG | ISSUE] Actual Behaviour:**
It shows me the Apache2 Default page,
But when i add something to the url like /RANDOMTEXT
Then it will show the Site blocked screen.

**[BUG | ISSUE] Steps to reproduce:**

- VIsit any blocked sites
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Remove Apache and make sure that lighttpd is running.

**Comment by kingdevnl** [comment]
@Mcat12 So i changed the lighttpd Port to 8080 And i still have the same issue,
the thing its Im running Owncloud on Apache2. So any ways to make it to work?

**Comment by kingdevnl** [comment]
But even when apache2 its running i can acces the Web admin gui.

**Comment by Mcat12** [comment]
Move Apache to a different port and keep lighttpd on port 80.

**Comment by kingdevnl** [comment]
Ok i changed apache2 Port and the lighttpd Back to port 80
But i still end up at the Apache2 default page

**Comment by kingdevnl** [comment]
Its there a way I could change lighttpd its www Folder to point to /var/www/pihole

**Comment by Mcat12** [comment]
Remove the Apache default page (under `/var/www/html`). We don't yet support changing the location of the web interface.

**Comment by kingdevnl** [comment]
@Mcat12 Fixed the Issue Thanks!
