### ISSUE TITLE
Debian Stretch = netstat now ss

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1563]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---
**[BUG REPORT]:**

**[BUG] Expected Behaviour:**
DNS status indicator should show green when successful.

**[BUG] Actual Behaviour:**
DNS indicator and possibly other subsystems are false red due to the change from `netstat` to `ss` for status reporting.

**[BUG | ISSUE] Steps to reproduce:**

Install Pi-hole on Debian Stretch.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jaimbo** [comment]
I found this problem when I installed Pi-Hole on stretch, but I resolved it by installing net-tools. Is this a bad approach? Might explain the problem I am having with IPv6.

**Comment by technicalpyro** [comment]
i don't have this problem perhaps it is because the droplet doesn't seem to like the DO install at the moment so i took a Jessie image and updated that way to use stretch?

**Comment by jwillmer** [comment]
Raspbian Stretch is out, is it safe to upgrade?

**Comment by technicalpyro** [comment]
i would tend to say yes as i have been running debain stretch since release without issue as i type this i am running the update myself

**Comment by jwillmer** [comment]
So pi hole does work after an upgrade from Jessi? Could someone maybe add that to the Readme since it is not obvious at the moment that someone tested it.
________________________________

**Comment by dschaper** [comment]
Well add a note when we've finished testing to make sure that both stock installs and upgraded installs work correctly and when we are set to support the new release. It may take a week or two as we will need to fully test everything to check and make sure we don't endorse an upgrade that may break in yet unknown ways.

**Comment by dschaper** [comment]
There looks to be a breaking change that needs further investigation with the new interface scheme and `/etc/dhcpcd`. https://www.raspberrypi.org/forums/viewtopic.php?p=1200643#p1200847

**Comment by no1knows** [comment]
pi-hole didn't work on a fresh install of Raspbian Stretch Lite for me.

**Comment by WaLLy3K** [comment]
[`netstat` issue is fixed in next release](https://github.com/pi-hole/pi-hole/pull/1676)

**Comment by jacobsalmela** [comment]
Resolved in v3.2 (#1676)
