### ISSUE TITLE
Website slow on first response

### ISSUE THREAD

**Issue by ndrone** [pi-hole/pi-hole#1568]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:2
---
**[BUG REPORT | OTHER]: BUG REPORT

**[BUG | ISSUE] Expected Behaviour: Admin Website to respond like good

**[BUG | ISSUE] Actual Behaviour: Admin Website responds too slow

**[BUG | ISSUE] Steps to reproduce:** visit http://localhost/admin wait 30 seconds then you might get a response.

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Please make a debug token. Is the website itself not showing up quickly, or just the stats?

**Comment by ndrone** [comment]
the website itself.

**Comment by technicalpyro** [comment]
is this happening after an update or fresh install ? or everytime you access the admin panel ?

**Comment by ndrone** [comment]
After the last update. Every time I visit the website in a fresh tab. Once I get in the site and navigate around it response fine.

**Comment by ndrone** [comment]
Alright I have the results. it took 61.1 seconds for the page to load from the start of the request. See the attached screenshot from the extension above. Also I've attached the pi_debug.log file because the upload failed when generating.
<img width="339" alt="screen shot 2017-06-28 at 8 57 05 pm" src="https://user-images.githubusercontent.com/7432362/27667065-0896f120-5c46-11e7-825d-e5727004f3af.png">
[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/1110619/pihole_debug.txt)

**Comment by Mcat12** [comment]
Your Pi-hole is unable to access the internet. Since it can't ask the upstream servers for the correct DNS response, it will time out.

**Comment by ndrone** [comment]
okay... hmm...
