### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by Gaunah** [pi-hole/pi-hole#1569]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

---
**[BUG REPORT | OTHER]:**

Since the update to 3.1 (from 3.0.1)  my blacklist gets ignored.
I can see the domain via the web-interface and it's also listed in "/etc/pihole/black.list"

as example 
running: "pihole -b msmetrics.ws.sonos.com"
gives:
`::: msmetrics.ws.sonos.com already exists in /etc/pihole/blacklist.txt, no need to add!
::: msmetrics.ws.sonos.com does not exist in /etc/pihole/whitelist.txt, no need to remove!
::: msmetrics.ws.sonos.com does not exist in /etc/dnsmasq.d/03-pihole-wildcard.conf, no need to remove!` 

(side note OS: `Linux ArchPi3 4.9.34-1-ARCH #1 SMP Mon Jun 26 01:32:24 UTC 2017 armv7l GNU/Linux`)

**[BUG | ISSUE] Expected Behaviour:**
msmetrics.ws.sonos.com, as listed in my blacklist, being blocked

**[BUG | ISSUE] Actual Behaviour:**
msmetrics.ws.sonos.com still gets forwarded
`Jun 28 19:22:20 dnsmasq[27610]: query[A] msmetrics.ws.sonos.com from 192.168.178.41
Jun 28 19:22:20 dnsmasq[27610]: forwarded msmetrics.ws.sonos.com to 8.8.8.8
Jun 28 19:22:20 dnsmasq[27610]: query[A] msmetrics.ws.sonos.com from 192.168.178.41
Jun 28 19:22:20 dnsmasq[27610]: forwarded msmetrics.ws.sonos.com to 8.8.8.8
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 52.30.148.246
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 54.76.124.252
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 52.51.165.168
Jun 28 19:22:20 dnsmasq[27610]: query[AAAA] msmetrics.ws.sonos.com from 192.168.178.41
Jun 28 19:22:20 dnsmasq[27610]: forwarded msmetrics.ws.sonos.com to 8.8.8.8
Jun 28 19:22:20 dnsmasq[27610]: query[AAAA] msmetrics.ws.sonos.com from 192.168.178.41
Jun 28 19:22:20 dnsmasq[27610]: forwarded msmetrics.ws.sonos.com to 8.8.8.8
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 2a01:578:3::341e:94f6
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 2a01:578:3::3433:a5a8
Jun 28 19:22:20 dnsmasq[27610]: reply msmetrics.ws.sonos.com is 2a01:578:3::364c:7cfc`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
Sorry for the delay in responding.  Send us the token generated by
```
pihole -d
```
and we can take a look.  

Also, does it happen with just that domain or every domain on your blacklist?

**Comment by Gaunah** [comment]
Hello,

if I run `pihole -d` it just displays the usage information, but i dont know what i did wrong.

It seems to be every domain on my blacklist, 
if i add them manualy to the "gravity.list" they get blocked.

**Comment by dschaper** [comment]
If you run `pihole -d` and follow the on screen directions you will get a token printed out for you. We need that token to be able to look at your logs. If `pihole -d` does not print a message explaining the debugging process then can you please paste what `pihole -d` displays for you?

**Comment by Gaunah** [comment]
@dschaper 
```
~ % pihole -d
Usage: pihole [options]
Example: 'pihole -w -h'
Add '-h' after specific commands for more information on usage

Whitelist/Blacklist Options:
  -w, whitelist       Whitelist domain(s)
  -b, blacklist       Blacklist domain(s)
  -wild, wildcard     Blacklist domain(s), and all its subdomains
                        Add '-h' for more info on whitelist/blacklist usage

Debugging Options:
  -d, debug           Start a debugging session
                        Add '-a' to enable automated debugging
  -f, flush           Flush the Pi-hole log
  -r, reconfigure     Reconfigure or Repair Pi-hole subsystems
  -t, tail            View the live output of the Pi-hole log

Options:
  -a, admin           Admin Console options
                        Add '-h' for more info on admin console usage
  -c, chronometer     Calculates stats and displays to an LCD
                        Add '-h' for more info on chronometer usage
  -g, updateGravity   Update the list of ad-serving domains
  -h, --help, help    Show this help dialog
  -l, logging         Specify whether the Pi-hole log should be used
                        Add '-h' for more info on logging usage
  -q, query           Query the adlists for a specified domain
                        Add '-exact' AFTER a specified domain for exact match
  -up, updatePihole   Update Pi-hole subsystems
  -v, version         Show installed versions of Pi-hole, Admin Console & FTL
                        Add '-h' for more info on version usage
  status              Display the running status of Pi-hole subsystems
  enable              Enable Pi-hole subsystems
  disable             Disable Pi-hole subsystems
                        Add '-h' for more info on disable usage
  restartdns          Restart Pi-hole subsystems
```

**Comment by dschaper** [comment]
Okay, there definitely is something amiss with the set up. How about trying the manual way:

     sudo /opt/pihole/piholeDebug.sh

**Comment by Gaunah** [comment]
Well, I guess you are right because I dont even have `opt/pihole/piholeDebug.sh`.
I have only:
```
ls /opt/pihole
chronometer.sh  list.sh                  piholeLogFlush.sh  webpage.sh
gravity.sh      mimic_setupVars.conf.sh  version.sh
```

I guess that's the case because I use the version provided by Arch: [AUR pi-hole-server](https://aur.archlinux.org/packages/pi-hole-server/)
So perhaps I "just" have to wait for an update from there.

**Comment by jacobsalmela** [comment]
Did you mean to re-open this?  Arch isn't a supported OS, so there's not a lot we can do.  We'll try our best to help out, but without being able to run the debug log, we're missing out on a lot of information that would typically help us solve some of the issues people run into.

**Comment by Gaunah** [comment]
Yes I accidently clicked on "Close and comment" instead of just "Comment".

But I guess you are right and the issue can be closed, because I have to wait, but thanks anyway.
I will report back if it works again. (if you want)

**Comment by jacobsalmela** [comment]
Yes, please do.  We're trying to grow Pi-hole to work on as many platforms as we can.

**Comment by Gaunah** [comment]
Well, 
with one of the latest AUR package updates the line:
` addn-hosts=/etc/pihole/black.list` 
got added to `/etc/dnsmasq.d/01-pihole.conf`
which seems to have fixed the issue.
