### ISSUE TITLE
Have wifi and ethernet on Pi3, dns request through wifi got no dns response from Pi-hole

### ISSUE THREAD

**Issue by linzack** [pi-hole/pi-hole#1574]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[BUG REPORT | OTHER]:**
It's my home network topology.

                  pc-----(ethernet)----router(AP)----internet
       android_phone-----(wifi)------------|
                 Pi3-----(wifi)----------- |
                    -----(ethernet)--------|

1. If the ethernet port of Pi3 is not connected, everything works fine.
2. But if ethernet port of Pi3 is connected, (according to wireshark on Pi3), the dns request send from android phone, will get no response from Pi-hole, then that phone can ping 8.8.8.8, but cannot connect to internet (dns solver error).
3. PC can have internet with Pi-hole enabled in both cases.

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
PC and android phone can have Pi-hole enabled internet, whether the ethernet port of Pi3 is connected or not.

**[BUG | ISSUE] Actual Behaviour:**
As long as the ethernet port of Pi3 is connected, android phone don't have internet connection. (But can ping 8.8.8.8)

**[BUG | ISSUE] Steps to reproduce:**

- disable Pi3 on board wifi, use usb wifi dongle. (don't know this step is related on not XD)
- setup Pi-hole on wlan0, eth0 port is not connected. (or "sudo ifconfig eth0 down")
- pc and android phone shall have Pi-hole enabled internet
- connect eth0 port on Pi3. (or "sudo ifconfig eth0 up")
- android phone lose internet connection, dns solver error, but pc internet is ok

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please run `pihole -d` and provide us with the debug token. Thank you.

**Comment by linzack** [comment]
Hi, 
The debug token is : zu0j6aygvy 
but it seems like if I enable eth0 interface, the android phone connection does not record in 60 seconds countdown..
Thank you!

**Comment by dschaper** [comment]
Thanks, are you using both the wired and wireless interfaces at the same time on the Pi-hole? Do you  have the routing set up correctly for this and are the interfaces on different subnetworks or the same subnet?

**Comment by linzack** [comment]
Hi,
My home network are on the same subnet 192.168.0.x
I use only one dns server which is assigned on Pi3 wlan0's ip address, and Pi-hole is installed on wlan0.
As config in /etc/dnsmasq.d/01-pihole.conf
interface=wlan0

I think the route is correct. They are on the same subnet 192.168.0.x, mask 255.255.255.0.
Thank you!

**Comment by dschaper** [comment]
Okay, how about the output from:

```
ip link
ip addr
ip route
```

**Comment by linzack** [comment]
Hi,
It's the output message, thank you!

      $ ip link
      1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
          link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
          link/ether b8:27:aa:bb:cc:dd brd ff:ff:ff:ff:ff:ff
      3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
          link/none
      4: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
          link/ether ec:08:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
      
      $ ip addr
      1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
          link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
          inet 127.0.0.1/8 scope host lo
             valid_lft forever preferred_lft forever
      2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
          link/ether b8:27:aa:bb:cc:dd brd ff:ff:ff:ff:ff:ff
          inet 192.168.0.13/24 brd 192.168.0.255 scope global eth0
             valid_lft forever preferred_lft forever
      3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
          link/none
          inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
             valid_lft forever preferred_lft forever
      4: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
          link/ether ec:08:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
          inet 192.168.0.12/24 brd 192.168.0.255 scope global wlan0
             valid_lft forever preferred_lft forever
      
      $ ip route
      default via 192.168.0.1 dev eth0  metric 202
      default via 192.168.0.1 dev wlan0  metric 304
      10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.1
      192.168.0.0/24 dev eth0  proto kernel  scope link  src 192.168.0.13  metric 202
      192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.12  metric 304

**Comment by Mcat12** [comment]
Just to see if it works, try changing dnsmasq to listen on all interfaces via the Advanced DNS settings in the web interface.

**Comment by linzack** [comment]
Oops! It's works!
[Pi-hole admin control](http://pi.hole/admin/settings.php)
Advanced DNS settings -> 
I change "Listen only on interface wlan0"  to "Listen on all interfaces, but allow only queries from devices that are at most one hop away (local devices)".
Then the android phone can have Pi-hole enabled internet even when Pi3 eth0 is up.
Problem solved, thank you!
