### ISSUE TITLE
Is there interest in a proper Makefile and versioned releases for pi-hole?

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#1578]
Is there interest in an official Makefile and versioned releases for upstream?   Using a shell script for installation and updates is rather non-standard to say the least. A proper Makefile would not only simplify packaging with versioning but would also allow for the inclusion of this software into more official distributions repositories.  I am happy to work on this if there is interest upstream in supporting it moving forward.

**Comment by dschaper** [comment]
If you can support Debian/Rasbpian/CentOS/Fedora/Synology and the rest of the distros then it may be worth looking in to. The problem with releasing in official repositories is the time lag. Debian is frozen and will not add updates that are new features, only bug fixes. With the shell scripting we can target many different distributions (and niche distributions) and the installer process is transparent to anyone that can read `bash` shell.

**Comment by graysky2** [comment]
@dschaper - I understand that strategy.  I would ask you to take a peek at the exception work Max.Bra (and to a much lesser degree me) has done for Arch Linux (basically created the needed systemd units and worked some magic with sed against the main pi-hole scripts).  

https://aur.archlinux.org/packages/pi-hole-server/
https://aur.archlinux.org/packages/pi-hole-ftl/

Much of this could be merged upstream and if we put a little work into it, an option in the Makefile could build for a traditional versioned release or it could build the more dynamic script-based.  What do you think?

**Comment by dschaper** [comment]
We've reached out to Max.Bra previously about collaboration on the project, but did not get a reply. Probably a better option would be to fork, and make an Arch specific set up. (I do run Arch as my daily driver and have a few packages in the AUR for other projects that I have worked on.) Personally, I don't see the benefit of adding in another layer of abstraction to the process, it would mean gutting the current `git` system and would involve quite a bit of work from what I can envision.

**Comment by graysky2** [comment]
I considered a fork but I just don't have the time it would take to do it correctly.  I can't speak for Max.Bra but I did email him a link to this ticket.  I do think that with a little initial time investment, the project could go as I described and that direction would benefit more distributions who are not willing to incorporate it due to the script modifying the live filesystem where the package manager should do that.  My offer to help stands.  I do think it could be something easily achieved with a Makefile (again, making traditional or dynamic).

**Comment by dschaper** [comment]
We're open to supporting other distributions, but we always end up coming back to the Debian policy of bug-fix only. We release fairly frequently, and with a package in the Debian repo, new features would not be added in the current release, it would take months/years for new features to be added in.

**Comment by graysky2** [comment]
I started out on Debian and ultimately went away due to the staleness of the software.  Not for my use case.  In any event, you could again have the debian make target provide the current "dynamic" script whereas other distros could build the versioned one.

**Comment by max72bra** [comment]
_- Quiet and peaceful, chats can deceive -_
Do not be unfair. I was asked what PH team could do for me to ease the management of my packages and I told you that at the present time you did the best I could ask for.
I was then asked to take part in the discussion about the integration of a DB and simply give me my opignon, just to you by email if I do not remember badly.
I never refused any request for help (which I never had) but in all respects I can not have time to actively participate in the main/official project.
Maybe a fork could help everyone. The official team would not have to deal with another distribution and we (myself, graysky and who would like to join) could go crazy less with sedding.
With my available time I can handle merging tasks especially if I'm not alone.

**Comment by DL6ER** [comment]
@graysky2 I looked at the FTL portion you linked and don't really understand:
```
Dependencies (2)
git (git-git) (make)
sqlite (make)
```
I'm not sure how much you are involved in there, but I don't see why `FTL` should have any dependencies on the target system (we specifically engineered it to have zero requirements on the clients system).

I see that you need `git` if you want to compile it locally (you have to `clone` the repo, in the end), but note we compile the binaries of each version for our users and present the ready for downloading for the sake of convenience here:

- all branches: http://ftl.pi-hole.net
- `master` branch: https://github.com/pi-hole/FTL/releases

Even if you don't have `GNU libc` (as on some small docker containers), we compile and deliver a `musl` binary.

We ship everything to be able to compile our stand-alone version of it without any requirement for `sqlite` to be installed on the system, so this seems superfluous.

**Comment by max72bra** [comment]
It is a habit for the archlinux community to create packages by compiling directly from the source. The use of pre-compiled binary is nearly discouraged.
The two dependencies are exclusively for compilation and are not necessary in execution phases.

**Comment by graysky2** [comment]
@max72bra - Actually, I am confused as well by the git makedepends.  Since we are using the versioned release (source array), what is the purpose of the git makedepends?

**Comment by max72bra** [comment]
<facepalm>
I told you I need a vacation, pretend nothing happened...  :-D
(removing unneed dep)

**Comment by graysky2** [comment]
OK.  If Max and I are both willing to and if upstream is open to it, I propose we think about the best way to implement.  One thought I had:

Rename the existing scripts to their corresponding .in names and have generic variables therein that the Makefile sets with a target.  

For a very simple example of this:  https://github.com/graysky2/profile-cleaner/blob/master/Makefile 
 ...  there the `make` step just sets a version number via sed in the script.

We could do similar for `make archlinux` or `make classic` or whatever that would produce the needed scripts.  One target would give exactly what you have in the git repo now (perhaps you supply this for debian or allow users that "dynamic filesystem updates" you currently do.  The "versioned" distros would benefit from having the package provide these scripts as Max's packages for Arch are currently doing.  Does that make sense?  How do people feel about the proposal?

**Comment by graysky2** [comment]
I had a little down time and starting work on a Makefile + included Max.Bra's systemd units.  Preview it here: https://github.com/graysky2/pi-hole/commit/21c0b7f2c2998d7e92420e14f543656225c71cbe

More to do but it's a start.

**Comment by graysky2** [comment]
@DL6ER - It's been a while since we talked about this... any thoughts on implementing?  For me, another reason to release with Makefile is so that routers running OpenWRT or DDWRT could provide pi-hole via entware.  That would be ideal.

**Comment by dschaper** [comment]
It's in work right now, it's a total rewrite of the platform, moving from `git` local repositories to a versioned tarball release. So it may take a few months to implement and get working. I still don't see any working on routers, as they would need to have FTL compiled for them and that may not be something that we can do depending on the processor utilized.

**Comment by graysky2** [comment]
@dschaper - Great to hear.  I don't see a problem with FTL since it would be compiled like any other package.  I would think that if accepted, entware would take care of this; nothing you would need to supply.

**Comment by darkrain88** [comment]
> @dschaper - Great to hear. I don't see a problem with FTL since it would be compiled like any other package. I would think that if accepted, entware would take care of this; nothing you would need to supply.

any update news :  can the pihole run on the openwrt?

i install the package on chrooted debian on my Openwrt, but it failed.
![image](https://user-images.githubusercontent.com/39786175/48302459-3c748a80-e538-11e8-8c5e-e646eb372720.png)

**Comment by nado** [comment]
Hi,

Is there any way I can help with this? I intend to run it on Gentoo, I'm still unsure whether I'll go with docker or if I'll spend time hacking install files ;)

In any case I don't want to add lines in your install script, I'd rather help making some standard makefile/setup.py/whatever so that it interacts more smoothly with other systems. I don't mind maintaining a gentoo specific thing (ebuild, patch, etc), but only if it's on Gentoo's side, I don't see the point of having something specific in upstream's install script.

This leads to the questions: what's already done? Do you have a light initial makefile (or anything else)? Where are the deps listed (is requirements.txt enough)?

**Comment by Mcat12** [comment]
We (@dschaper especially) are working on an improved installation flow, which should make it easier to add support for other distributions. Right now though, the install script is the main method of installation.

Having just a makefile or list of dependencies is not quite enough to install Pi-hole, because it needs to be configured to work on your network (the install script tries to auto-configure most of this).

**Comment by nado** [comment]
Yeah, but that’s configuration, not installation.
It doesn’t exclude having this phase into the makefile/script, but IMO, it should be considered separate from the install phase.
Are there any dependency which are dependent on configuration choices?

Thanks for the answer, if there are no public work at the moment I’ll probably test the docker install ;)

**Comment by Mcat12** [comment]
Right now, the configuration happens at the same time as installation, which is one of the things we are working to separate.

**Comment by graysky2** [comment]
Glad to have upstream guys are working on this.  I do agree that the initial project delivered an excellent install script, but now that popularity has increased, a proper Makefile for installation and (the Arch way) documentation for configuration or a post install script to configure would be welcomed.  As well, it could allow for packaging on major distros.

**Comment by dschaper** [comment]
I'm cleaning up the issues and trying to get us to a good place with regards to support loads. This is a feature request and we're tracking all feature requests on our Discourse now, so please open a FR ticket there so that the whole community can be involved and not just the small handful of developers.

Thanks

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
