### ISSUE TITLE
How to choose tun0 as a networking interface

### ISSUE THREAD

**Issue by nuentes** [pi-hole/pi-hole#1580]
Sorry, I've spent a while googling, and I can't figure out how to perform [this step](https://github.com/pi-hole/pi-hole/wiki/OpenVPN-server:-Installation#install-pi-hole):

> Chose tun0 as networking interface. If tun0 isn't available, the installation of the OpenVPN server failed.

When I pull up the Network Preferences, the only interface available is eth0. However, when I ifconfig, I get:
```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:df:85:xx  
          inet addr:192.168.1.11  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::442c:cce5:xxxx:7228/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:12749 errors:0 dropped:15 overruns:0 frame:0
          TX packets:25202 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3678259 (3.5 MiB)  TX bytes:33098964 (31.5 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:205 errors:0 dropped:0 overruns:0 frame:0
          TX packets:205 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:16936 (16.5 KiB)  TX bytes:16936 (16.5 KiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
Also:
```
$ ip route list
default via 192.168.1.1 dev eth0  metric 202 
10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.1 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.11  metric 202 
```
And
```
$ openvpn --remote CLIENT_IP --dev tun0 --ifconfig 10.9.8.1 10.9.8.2
Tue Jul  4 18:23:00 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 27 2017
Tue Jul  4 18:23:00 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Tue Jul  4 18:23:00 2017 ******* WARNING *******: all encryption and authentication features disabled -- all data will be tunnelled as cleartext
Tue Jul  4 18:23:00 2017 RESOLVE: Cannot resolve host address: CLIENT_IP: Name or service not known
Tue Jul  4 18:23:00 2017 ERROR: Cannot ioctl TUNSETIFF tun0: Device or resource busy (errno=16)
Tue Jul  4 18:23:00 2017 Exiting due to fatal error
```
Thanks for any help!

**Comment by Mcat12** [comment]
I think it means to choose that interface during Pi-hole's setup.

**Comment by technicalpyro** [comment]
if tyhe interfce is not chosen during setup as @Mcat12  is correct on you can modify you `/etc/pihole/setupVars.conf` file and where it says PIHOLE_INTERFACE=eth0
 change eth0 to tun0 

alternatively using the web interface under settings and advanced dns on the bottom left select the first of the three options that says listen on all interfaces but only respond to queries from one hop away

**Comment by nuentes** [comment]
Ah - then I might suggest that the "Chose (sic) tun0 as networking interface. If tun0 isn't available, the installation of the OpenVPN server failed." note goes after the "curl -sSL https://install.pi-hole.net | bash" line in the setup guide, and maybe clarify this a bit. I assume any note before a line of code is meant to be completed/addressed **before** the code is run.

Thanks!

**Comment by technicalpyro** [comment]
i have made an edit in an attempt t make things more clear

**Comment by jacobsalmela** [comment]
@nuentes The guide now reads:

### Install Pi-hole
```bash
curl -sSL https://install.pi-hole.net | bash
```
During the install, choose `tun0` as networking interface .  If `tun0` isn't available, the installation of the OpenVPN server failed.

Is this more clear?

**Comment by nuentes** [comment]
Yes, much better. Thanks! Closing issue.

**Comment by timdonovanuk** [comment]
This is quite unhelpful if you've already installed Pi Hole! I would imagine a large percentage of people that find themselves here have already installed it and are looking to add on OpenVPN, not the other way around.

**Comment by jacobsalmela** [comment]
FWIW, we now have `pihole -r`
