### ISSUE TITLE
Pi-Hole install failed

### ISSUE THREAD

**Issue by nuentes** [pi-hole/pi-hole#1584]
Ok, so I was a dummy and didn't copy any code before I rebooted, however I vaguely understand what happened. I think something went wrong on the DNS side.

During install, I lost VNC connection. I figured this was expected, so I went down to my Pi. The install was still up, and there were 2 more questions that I was asked (I think the first one was confirming my static IP, and the 2nd one was telling me that I really should make sure that I have a static IP set for the device on my gateway (I do). Anyway, the next thing that happened was the screen returned to a normal command prompt and I had an error that the clone of the githup project failed. When I try to ping google.com, I get no response. However, when I ping my local IPs and the local google server (172.217.8.14), it succeeds. So it appears as though DNS isn't working? I messed with Network preferences a bit, trying to set the DNS server to 8.8.8.8, but nothing changed. I think I've got it [back to normal now](https://i.imgur.com/88XvRFE.jpg)... Not really knowing what to provide... here is everything I can think to run. Thanks for the help! (raspbian, up to date, on a Pi B+).

```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:df:85:0b  
          inet addr:192.168.1.11  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::442c:cce5:24c0:7228/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4513 errors:0 dropped:37 overruns:0 frame:0
          TX packets:6732 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:373601 (364.8 KiB)  TX bytes:8295243 (7.9 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:549 errors:0 dropped:0 overruns:0 frame:0
          TX packets:549 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:43408 (42.3 KiB)  TX bytes:43408 (42.3 KiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:39 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:0 (0.0 B)  TX bytes:13572 (13.2 KiB)
```

```
$ ip route list
default via 192.168.1.1 dev eth0  metric 202 
10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.1 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.11  metric 202 
```

```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:df:85:0b brd ff:ff:ff:ff:ff:ff
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
```

```
$ pihole -d
bash: pihole: command not found
```

**Comment by technicalpyro** [comment]
try the following `pihole uninstall` fr removal

then run the curl command using bash -x instead of just bash to see the more verbose logs and determine where the failure occurred

**Comment by nuentes** [comment]
```
$ pihole uninstall
bash: pihole: command not found
```

**Comment by technicalpyro** [comment]
```
sudo rm -rf /etc/.pihole/
sudo rm -rf /etc/pihole/
sudo rm -rf /var/www/html/admin
```

then 
`curl -sSL https://install.pi-hole.net | bash -x
`

**Comment by nuentes** [comment]
Needed a reboot after the folder removal, but that took care of it. And of course, there were no errors this time. Thanks for the help!

**Comment by technicalpyro** [comment]
no problem if you are good to go please close the issue :)
