### ISSUE TITLE
Pi-hole+DNSCrypt with OpenVPN

### ISSUE THREAD

**Issue by nobody1407** [pi-hole/pi-hole#1588]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [  ] The issue I am reporting can be *replicated*
- [  ] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

7

---
**[BUG REPORT | OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**

VPN connection over pi-hole/dnscrypt

**[BUG | ISSUE] Actual Behaviour:**

VPN connection without pi-hole/dnscrypt

**[BUG | ISSUE] Steps to reproduce:**

- Fresh install
- Setup DNSMasq and DNSCrypt (still working)
- "Add" OpenVPN

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

_removed my [post](https://github.com/pi-hole/pi-hole/issues/1553) into a new thread_ 

Pi-hole, DNSMasq and DNSCrypt working fine and I've full access to the local network with OpenVPN, but I can't force the way over Pi-hole/DNSCrypt. (**pihole -a -i all** already done)

Here my LAN setup:
Pi-hole: 192.168.178.37
tun0 inet Adresse:10.8.0.1
VPN-Client1: 10.8.0.2 (Xubuntu 16.04 LTS) 

```
dev tun
proto udp
port **REMOVED**
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh4096.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 192.168.178.0 255.255.255.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io
```

----
**Update:**
It works only few seconds, e.g. the first run with "https://www.dnsleaktest.com/" worked with correct DNS-Server and show me the false entries after few seconds and then correct...false...correct...false...

**Update2:**
After a lot of hours I think thats a client (Linux) problem.. :confused:

**Comment by nobody1407** [comment]
**Update3:**

Ok, thats not only a client problem. I installed a Windows7 (Virtualmachine) with the same problems. I think thats only a problem of the "server.conf"..

Are the IPconfig correct?

**Comment by technicalpyro** [comment]
try modifying the push route to be to your pihole's IP address and restarting the VPN server i have found this will sometimes fix issues with OpenVPN and pihole also push the DNS address as your piholes ip.  

lastly if you use the above changes be sure that the top of the three options is selected under which interface is listening in the settings page

**Comment by nobody1407** [comment]
Thank you for your answer. I've checked the push routes. I think that solved a part of my problem.
I forgot to set the route from router/gateway to VPN network.

local network: 192.168.178.0/24
VPN network: 10.8.0.0/24

- [X] ping from 10.8.0.2 to 192.168.178.34
- [X] ping from 192.168.178.34 to 10.8.0.2
- [X] dnsleaktest.com
- [ ] DNSSEC resolver test (https://dnssec.vs.uni-due.de)

The last point is the DNSSEC resolver test and failed every time :confused:

**Comment by nobody1407** [comment]
Does anybody know if the dnsmasq-config file is correct?

```
server=127.0.0.2#40
listen-address=127.0.0.1, 192.168.178.37, 10.8.0.1
no-resolv
bogus-priv
proxy-dnssec
```

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CK-s-Raspberry-Pi-3-config
