### ISSUE TITLE
Windows 10 mobile dropping connection

### ISSUE THREAD

**Issue by Dunkelschunkel** [pi-hole/pi-hole#1589]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1
---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

-pihole should work on all connected devices reliably

**[BUG | ISSUE] Actual Behaviour:**

-Windows 10 mobile devices having problems resolving DNS names after some time

**[BUG | ISSUE] Steps to reproduce:**

-freshly installed pihole on rpi2
-Fritzbox 7390  as dhcp-server handing out ip of pihole as DNS to clients
-pihole custom dns: ip of fritzbox 7390 router
-Options "non-fqdn" and "reverse lookup private range" off for resolving client DNS names 
-renewing ip-config for Clients by reconnecting to wifi
-testing everything - works well
-after a while (some hours - a day) Windows 10 mobile device can't resolve DNS-names and displays browser error message. whilst other devices (ios/android/win10) work well
-same behaviour seen on wndows 10 pc a couple of times but much more infrequent

**(Optional) Debug token generated by `pihole -d`:**

`qe85kqamfp`

-no Clients requesting while generating debug log

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
are you able to use command prompt when the error occurs ? does using  `ipconfig /flushdns`  fix the issue or have no effect

this sounds more or less a tablet or network issue not necessarily one with pihole

**Comment by Dunkelschunkel** [comment]
Should I flush the DNS cache on the client side or the pihole side?

technicalpyro <notifications@github.com> schrieb am Fr. 7. Juli 2017 um
17:39:

**Comment by technicalpyro** [comment]
Client side first as it is a single client having issues best way to fix is figure out why it is no longer working 

also you could try manually putting your pihole as the dns in the ipv4 and ipv6 adapter properties

**Comment by Dunkelschunkel** [comment]
I do not even know if there is a way of clearing the DNS cache in windows
mobile 10 besides disconnecting and reconnecting

I even installed interop tools on this particular device to be able to set
the IP address manually. Regards

technicalpyro <notifications@github.com> schrieb am Fr. 7. Juli 2017 um
17:47:

**Comment by WaLLy3K** [comment]
Hey @Dunkelschunkel, are you still experiencing this issue? If so, could you follow up with a new debug token please?

Thanks! :smile:

**Comment by Dunkelschunkel** [comment]
Hey there,

Thanks for your concern. Please give me some time to test everything
properly.



WaLLy3K <notifications@github.com> schrieb am Mo. 9. Okt. 2017 um 07:23:

**Comment by jacobsalmela** [comment]
@Dunkelschunkel are you still having issues with our latest release? v3.2?
