### ISSUE TITLE
FQDN's sometimes appear in Top Client's list, but not all the time.

### ISSUE THREAD

**Issue by jsfrederick** [pi-hole/pi-hole#1603]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT]:**

**[BUG] Expected Behaviour:**
FQDN's in the Top Clients list instead of IP addresses

**[BUG] Actual Behaviour:**
Someiimgs I see FQDN's, sometimes I see IP addresses.  I rebooted the Pi-Hole server today and the FQDN's in the Top Clients List all became IP address.  I waited a few hours to see if FQDN's would reappear, they did not.  DNSMasq is working fine for me. Please let me know what info and which config files you need from my setup.

**(Optional) Debug token generated by `pihole -d`:**

`sxzqqiruma`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/top-clients-sometimes-show-fqdn-sometimes-not/4022 Further information on the issue for troubleshooting.

**Comment by WaLLy3K** [comment]
That above thread suggests that the issue might be resolved. Could you confirm please, @jsfrederick? :smile:

**Comment by jsfrederick** [comment]
Yes, close please
