### ISSUE TITLE
Uninstalling Pi-hole removes (?) rsync

### ISSUE THREAD

**Issue by beatschubser** [pi-hole/pi-hole#1604]
After uninstalling Pi-hole and most of its dependencies (except for curl, wget and unzip) the rsync-command cannot be executed any more -> "Command not found". Is that intended?

**Comment by PromoFaux** [comment]
Hi, thanks for the report. AFAIK, the [uninstall script](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/uninstall.sh) doesn't remove anything to do with `rsync` but it is due some attention to make it better. 

Are you able to reproduce this on another system with `rsync` installed? 

Also, please ensure you [follow the issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when reporting issues as per the [contribution guidelines](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#procedure).

Closing issue until the OP is edited to include the correct template, feel free to reopen again once you have done so! (It may seem petty, but it's there to help us help you 😄 )
