### ISSUE TITLE
Uninstalling Pi-hole removes (?) rsync

### ISSUE THREAD

**Issue by beatschubser** [pi-hole/pi-hole#1605]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), 

**How familiar are you with the codebase?:** _1_

---
**[BUG REPORT]:**

**[BUG | ISSUE] Actual Behaviour:**

After uninstalling Pi-hole and most of its dependencies (except for curl, wget and unzip) the rsync-command cannot be executed any more -> "Command not found".

I have tested this three times, so I guess it is reproducible.

**[BUG | ISSUE] Steps to reproduce:**

Uninstall Pi-hole with "sudo pihole uninstall". Remove all dependencies  except for curl, wget and unzip. I don't know if this also happens when you don't remove any dependencies.

**Comment by dschaper** [comment]
The dependencies include utilities that are already installed on various distributions, they should not all be removed, or you will take out packages that existed prior to installing the Pi-hole. Uninstalling the Pi-hole software via the script isn't the best currently, but just walking through the script and uninstalling everything without checking to see what utilities and software will be removed when done manually will break your OS.

**Comment by beatschubser** [comment]
Fair enough, but then the script shouldn't say 

> "Preparing to remove packages ... (SAFE TO REMOVE ALL ON RASPBIAN)" 

What's the best way to uninstall Pi-hole? Love the tool, but it crashes my SmartHome-Server (FHEM).

**Comment by jacobsalmela** [comment]
This does not seem to be an issue on v3.2--we did give the uninstaller some love, but it appears to be fixed.  

```
root@debian:~# which rsync
/usr/bin/rsync
root@debian:~# pihole uninstall
  [?] Are you sure you would like to remove Pi-hole? [y/N] y
  [✓] Root user check
  [i] Be sure to confirm if any dependencies should not be removed
  [i] The following dependencies may have been added by the Pi-hole install:
    apt-utils dialog debconf dhcpcd5 git iproute2 whiptail bc cron curl dnsmasq dnsutils iputils-ping lsof netcat sudo unzip wget idn2 lighttpd php5-common php5-cgi php5-sqlite 
  [?] Do you wish to go through each dependency for removal? (Choosing No will leave all dependencies installed) [Y/n] y

  [?] Do you wish to remove apt-utils from your system? [Y/N] y
  [i] Removed apt-utils
  [?] Do you wish to remove dialog from your system? [Y/N] y
  [i] Removed dialog
  [?] Do you wish to remove debconf from your system? [Y/N] y
  [i] Removing debconf...root@debian:~# which rsync
/usr/bin/rsync
```
Tried on CentOS as well:
```
[root@centos ~]# which rsync
/usr/bin/rsync
[root@centos ~]# pihole uninstall
  [?] Are you sure you would like to remove Pi-hole? [y/N] y
  [✓] Root user check
  [i] Be sure to confirm if any dependencies should not be removed
  [i] The following dependencies may have been added by the Pi-hole install:
    dialog git iproute net-tools newt procps-ng epel-release bc bind-utils cronie curl dnsmasq findutils nmap-ncat sudo unzip wget libidn2 psmisc lighttpd lighttpd-fastcgi php php-common php-cli php-pdo 
  [?] Do you wish to go through each dependency for removal? (Choosing No will leave all dependencies installed) [Y/n] y

  [?] Do you wish to remove dialog from your system? [Y/N] y
  [i] Removed dialog
  [?] Do you wish to remove git from your system? [Y/N] y
  [i] Removed git
  [?] Do you wish to remove iproute from your system? [Y/N] y
  [i] Removed iproute
  [?] Do you wish to remove net-tools from your system? [Y/N] y
  [i] Removed net-tools
  [?] Do you wish to remove newt from your system? [Y/N] y
  [i] Removed newt
  [?] Do you wish to remove procps-ng from your system? [Y/N] y
  [i] Removing procps-ng...
[root@centos ~]# which rsync
/usr/bin/rsync
```
