### ISSUE TITLE
Pi-hole replaces ads with error messages on websites

### ISSUE THREAD

**Issue by UnicornsOnLSD** [pi-hole/pi-hole#1614]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:*1*

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[Pi-hole is replacing ads with errors | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Ads are supposed to just go away and the page repaired

**[BUG | ISSUE] Actual Behaviour:**
Left with this error message here: http://i.imgur.com/FfrcO9b.jpg

**[BUG | ISSUE] Steps to reproduce:**

-Install pi-hole
-Manually set it up on each device
-I tried on youtube.com but I think it affects other sites.
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Hi there, 

This is known behaviour, and not something we have any control over. Pi-hole is a DNS adblocker, meaning the browser/client device makes a lookup for the advert's domain (e.g `www.doubleclick.net`), and will return it's own address (e.g `192.168.1.2`). When the browser/client tries to load the content (`www.doubleclick.net/files/advert.html`) it will instead then try to load `192.168.1.2/files/advert.html`

As the directory/file `/files/advert.html` do not exist on the Pi-hole device, we return a 404 error page, which on non-https ads renders as a block page, or if the content is loaded as part of an iframe, the blockpage is blank.

![image](https://user-images.githubusercontent.com/1998970/28248763-f5b9f39a-6a41-11e7-9339-fe97046b97d2.png)

As we do not inspect the actual content of the webpages you are loading, there is no way that we can manipulate the site and remove the gaps left by the lack of ads.

You can, however, also run something like uBlock origin alongside it if the gaps bother you, which will tidy up the pages somewhat.

**Comment by UnicornsOnLSD** [comment]
@PromoFaux Thank you for the quick reply. It is a compromise that I'm willing to live with. Thanks!
