### ISSUE TITLE
how do i set piholes time to 12hr instead of 24hr?

### ISSUE THREAD

**Issue by articrevised** [pi-hole/pi-hole#1615]
how do i set piholes time to 12hr instead of 24hr?

its kind of annoying

**Comment by WaLLy3K** [comment]
Hey @articrevised!

Currently, we don't have an option that allows you to change 12/24H time on the Admin Dashboard. If this is something you'd like to see added, then I'd recommend [voting on this post](https://discourse.pi-hole.net/t/add-12h-am-pm-view-to-logs-graph/1822) on the Discourse forums :smile:

**Comment by articrevised** [comment]
dangit
