### ISSUE TITLE
Minor bug: Domain names starting with a dot are being trapped in the event horizon.

### ISSUE THREAD

**Issue by fmjensen** [pi-hole/pi-hole#162]
This causes dnsmasq to barf in the pihole.log

An example:
``` Jan 12 16:17:17 dnsmasq[475]: bad name at /etc/pihole/gravity.list line 163931 ```
and
``` cat -n /etc/pihole/gravity.list |grep 163931 ```

returns these lines:
```
163931  pi.eth.ip.adr .ibsys.com
```
wich leads me to do
``` cat /etc/pihole/list.* |grep " \." ```
that reveal these lines:
```
127.0.0.1 .com
127.0.0.1 .doubleclick.com
127.0.0.1 .doubleclick.net
127.0.0.1 .ibsys.com
```

I believe the error actually stems from the source files... so - relying on those to be without syntax errors is maybe not possible :-/

"pi.eth.ip.adr" is ofcourse a LAN ip alias my paranoia demands me to use... and this "bug" is not critical... but is is there ;-)

**Comment by dschaper** [comment]
`127.0.0.1 .com` concerns me. One of the lists is trying to block the entire `.com` TLD??

**Comment by jacobsalmela** [comment]
Yeah, that's crazy.  Can you find out what list it came from with this command (I think my regex is right, but not 100%).

```
for list in /etc/pihole/list.*;do echo $list;grep '^.com' $list;done
```

**Comment by jacobsalmela** [comment]
Also, early on in Pi-hole's beginnings, we had some way of finding domains beginning with a dot.  So I'll have to look back and see how/why it was removed.

**Comment by dschaper** [comment]
I think your regex looks good. I'll check and see who is doing that... (Swapping SDCards like a madman over here, lol...)

**Comment by dschaper** [comment]
@fmjensen Can you re-run `gravity.sh` and see if the problem is still there. I'm not able to find that entry in any of the lists. Maybe it was a mistake and was corrected, but on a fresh install I'm not finding anything.

**Comment by jacobsalmela** [comment]
lol.  Yeah, I think I might need to buy a few more Pi's just so I can have a few tester available at once!

Nothing showed up on my lists, but on my stable Pi, I haven't updated it or anything.  We'll see what @fmjensen finds.  I'll also re-build a Pi-hole (a daily occurrence nowadays) and see what I find.

**Comment by dschaper** [comment]
I live pretty close to a MicroCenter and a Fry's and MC has the Pi2's for $29.99 and PiB's for $19.99 (And if they are out of stock, Fry's does price match.) I mostly use them for SDR work, but I donated all my B's to a school that needed PI's for education so I'm back to just two available units for a few days...

**Comment by fmjensen** [comment]
They origin from 

After running gravity.sh this morning i found this:
```
pi@raspberrypi:~ $ cat /etc/pihole/list.7.adblock.mahakala.is.domains |grep " \."
127.0.0.1 .com
127.0.0.1 .doubleclick.com
127.0.0.1 .doubleclick.net
127.0.0.1 .ibsys.com
```

Ps: i moved adblock.mahakala.is so it is pulled in as the last list - hence the filename "list.7..."
I build mu pi-hole this weekend... maybe i need to update it ??

**Comment by dschaper** [comment]
Mahkala is commented out of the master list for a reason. They tend to break things and they list legitimate sites. My suggestion would be to not use them at all...

**Comment by fmjensen** [comment]
Mahkala is commented out - true, but it is part of the script. If the pi-hole is not intended to support this list, I strongly suggest this list is removed completely from the pi-hole project.

I hate ads so much you cant believe it. Because of this, I will use all the lists I (easily) can pull into gravity.list, well knowing that legitimate domains may be blocked by pi-hole because of this. If a site I NEED to visit is blocked, I can easily swap DNS server for a short while ;-)

**Comment by dschaper** [comment]
Pi-Hole does support the list, but we can't support the list contents as they are quite out of our hands to control. That being said, I agree that the leading period is a bug that needs to be fixed. I think though that you can see that Mahalaka in its current state would block every domain in the `com` TLD, which is bizzare and troublesome...

**Comment by fmjensen** [comment]
I agree... that is bizzare !

**Comment by jacobsalmela** [comment]
Yeah that mahakala list is odd.  Back when I first made Pi-hole 2.0, the list was like 100,000 and then it jumped to like 900,000, and then later dropped again significantly.  

Pi-hole is completely reliant on the third party lists and while it works really well as-is, there are more ads that can be blocked with that list.  It might just need some fine tuning with an extensive whitelist.  Either way, I think it's nice to let users know that it's out there. 

I'm not surprised that list was the culprit, but it's not really a problem with Pi-hole.  Although, we could add some logic in to detect this sort of thing.  Piping into this `awk` command seems to work to weed out the lines beginning with a dot.
```
awk '!/^\./'
```

**Comment by wuudogg** [comment]
What if you whitelist .com in the pi-hole build ? Would that take priority and avoid the mahakala .com block ?

**Comment by dschaper** [comment]
Adding `.com` to the whitelist would whitelist everything that ends in `com`. The best way is to just leave Mahakala commented out, or if you want to use that list, be prepared to whitelist a lot of domains that are legitimate but are blocked anyways. You could always uncomment the list, run `gravity.sh` and see how the Pi-Hole acts, and recomment and rerun `gravity.sh` if it's too aggressive.

**Comment by jacobsalmela** [comment]
Yeah, I think I'd rather just have logic in the script to detect this sort of thing and eliminate it as that would be the most adaptive and self-sustaining.

**Comment by PromoFaux** [comment]
As an update to this, since the changes to `whitelist.sh`, you can now actually whitlist `.com`, but only by adding it directly to `whitelist.txt`, as the URL qualifier on the script will not accept it as a domain.

When it removes domains from `gravity.list`, it will only remove matches that are preceded by whitespace.

Now, the question is.. do we want to cut out domains starting with `.` from gravity.list all together?  Or should we consider this issue closed? `whitelist.sh` could probably be updated to remove the URL validation part..

It seems very few are coming in from the makala list (my `gravity.list` contains 4.. `.doubleclick.com`, `.doubleclick.net`, `.ibsys.com`, and `.com`)

**Comment by dschaper** [comment]
Can we have some kind of sanity check that won't let a user enter an entire TLD? Or do we want the option to add certain TLD's like `.xxx`? Mahalaka is always going to be a bane to deal with, but at least it takes a manual override to include it in the domain array.

**Comment by jacobsalmela** [comment]
We probably should add a check since we have no control over the third-party lists.

**Comment by PromoFaux** [comment]
Sure thing, should be a simple edit to gravity, or the whitelist, either or.

**Comment by jacobsalmela** [comment]
What did you have in mind?  

This seems to work as I mentioned earlier:

```
awk '!/^\./'
```
but I haven't tested it exhaustively.

**Comment by Mcat12** [comment]
What's the status on this?

**Comment by jacobsalmela** [comment]
It's still a bug, but has not caused issues since the initial report.

**Comment by jacobsalmela** [comment]
I don't believe this can happen anymore due to our parser that verifies FQDNs.
