### ISSUE TITLE
macOS and iOS DHCP clients do not get IPv6 addresses

### ISSUE THREAD

**Issue by davidrogers-unity** [pi-hole/pi-hole#1620]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1
---
**[BUG REPORT | OTHER]:**

macOS and iOS(probably watchOS and tvOS too) clients do not get IPv6 addresses via DHCP. The result is that ad blocking doesn't work for any IPv6 requests.

**[BUG | ISSUE] Expected Behaviour:**
The clients should get an IP and DNS info that points to the pi-hole.

**[BUG | ISSUE] Actual Behaviour:**
IPv4 information is set correctly but IPv6 DNS points to Comcast for some reason. (2001:558:feed::2 and 2001:558:feed::1). Comcast is my ISP.

**[BUG | ISSUE] Steps to reproduce:**

1. Set the Pi-Hole to act as DHCP for both IPv4 and IPv6.
2. Make sure "Configure IPv6" is set to Automatically in network settings.
3. Renew lease on Apple device.
4. Observe that the IPv6 DNS does not point to the Pi-Hole.

**(Optional) Debug token generated by `pihole -d`:**

bunq4cx848

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Check your router settings. Most likely, it is still sending out IPv6 DNS information and overriding what Pi-hole sends out. There may not be an option to turn it off.

**Comment by davidrogers-unity** [comment]
Double checked and I have DHCPv6 disabled on it as well as all IPv6 settings.

**Comment by davidrogers-unity** [comment]
I did some research and it appears that some Comcast routers, in my case the Netgear CG3000DCR sends out ICMPv6 packets with DNS info in them.

I was able to work around this by setting my Pi-Hole's IPv6 address in the "Assign DNS Manually" box under IPv6 settings on the router.
