### ISSUE TITLE
Custom reports

### ISSUE THREAD

**Issue by Arjoni** [pi-hole/pi-hole#1621]
It would be great to be able to export reports about specific IP. For example export all queries one specific IP has made for the last week. 
Could this be implemented? It would be a good feature.

**Comment by PromoFaux** [comment]
If you had read the [Issue Template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) that you have chosen to ignore, you will have noticed this:

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.
