### ISSUE TITLE
Related to issue #333 Domain redirecting

### ISSUE THREAD

**Issue by harshil2105** [pi-hole/pi-hole#1622]
Even after editing all the files as told in the instructions I can't perform domain redirecting.....maybe i am having confusion in editing /etc/customers love.list file ,maybe anyone could tell us how to edit this last file.

**Comment by harshil2105** [comment]
Damn autocorrect....../etc/customResolve.list

**Comment by Mcat12** [comment]
> Please open a new issue with more detailed information (follow the template; what have you tried, what errors are you seeing, etc).

Did you follow the template? Please do. Without that information it is difficult to help you (specific steps you have tried, errors you see, debug token, etc).

**Comment by harshil2105** [comment]
I have completely followed the template I made the file required in /etc directory and the other files required....I am trouble  in editing the last files in which we have to input the domain name and the domain name by with we wish to replace it..

**Comment by Mcat12** [comment]
This is the template, which you deleted when you created the issue because it is the default text for a new issue:
```
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**


**[BUG | ISSUE] Actual Behaviour:**


**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

```

**Comment by harshil2105** [comment]
Help me edit the file in which I have to write the domains which are to be redirected

**Comment by harshil2105** [comment]
Next, you can put the actual redirect in /etc/customRedirect.list, in this example these 2 lines:
www.exampledomain1.com www.differentdomain.com
exampledomain1.com differentdomain.com

**Comment by harshil2105** [comment]
I want help in editing this file....how to edit and what to write I'm unable to understand this examples

**Comment by dschaper** [comment]
Can you point us to the instructions you are following? We don't have any directions that ask you to edit any configuration file called `/etc/customRedirect.list`?

**Comment by dschaper** [comment]
You can't map one domain to another domain, you can only map an IP address to a domain. 

`111.222.333.444 google.com` works,
`mitm.com google.com` will not.

**Comment by dschaper** [comment]
Seeing as your request is to intercept a named domain and change that for a second domain, that's not possible. So I'm going to close this ticket. If you want to map a domain to an internal IP address, then please clarify that and open a new ticket, but please fill out the Issue Template as you have been asked to do many times.
