### ISSUE TITLE
Can't update (from v3.1.1)

### ISSUE THREAD

**Issue by Jacopx** [pi-hole/pi-hole#1623]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
10

**[BUG REPORT]:**
When I'm trying to do:
`pinhole -up`
(both with sudo) is not work and give me back:
`/opt/pihole/update.sh: line 29: /opt/pihole/COL_TABLE: No such file or directory`

**Comment by WaLLy3K** [comment]
Hey @Jacopx, it sounds like you're affected by the [issue mentioned here](https://pi-hole.net/2017/07/18/pi-hole-3-1-4-hotfix-for-ipv6-cidr-bug/). Run the following in Terminal, and see how you go:

```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
pihole -r
```

Cheers :smile:

**Comment by Jacopx** [comment]
Good jobs guys! ;)

Thanks you very much! @WaLLy3K

**Comment by Jacopx** [comment]
Good jobs guys! ;)

Thanks you very much! @WaLLy3K
