### ISSUE TITLE
"Update Complete!" \n "Unable to complete update, contact Pi-hole"

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/pi-hole#1626]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG REPORT | OTHER]:**

I'm running the development branch.

After I run update function today, I got output 
`Update Complete!`, and
`Unable to complete update, contact Pi-hole` in the next line.

I also get both output lines when I switch to master and back to devel branch again.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Can you run `pihole -d` for us and well take a look? Things on development may break, but this isn't something we've seen.

**Comment by Th3M3** [comment]
debug token is `gzwsvoak2i`

**Comment by dschaper** [comment]
Thanks, I'm not seeing it currently switching between all the branches, but @WaLLy3K has reported seeing it back a week or so ago. Can you run the installer in verbose mode? 

```
sudo bash -x /etc/.pihole/automated\ install/basic-install.sh --reconfigure --unattended
```

This is going to produce a ton of output, but can help us track down what is throwing the extra flag that is adding the `Unable to complete` message.

**Comment by Th3M3** [comment]
@dschaper When I run `pihole -r` or the installer in verbose mode, then I only get the `Update Complete!` output in the end.

Actually it seems to me, that the issue only occurs if I switch from master to devel branch or if I run the installer for an update (also on devel branch).

Can you tell me how to switch to devel branch in verbose mode?
Or how to revert the last update?

**Comment by Th3M3** [comment]
sorry, didn't want to close this issue. I hit the wrong button

**Comment by dschaper** [comment]
Using `pihole checkout` calls various scripts and doesn't allow for verbose mode through all the separate subshell calls. You'd have to manually go through each step and call the individual scripts via `bash -x <script>`. So it's a long an involved debugging process.

To revert an update you could go in to the two folders `/etc/.pihole` and `/var/www/html/admin` and `git reset --hard HEAD~1` but that's going to make a mess of things very quickly and throw you out of sync. 

At this point, deleting the two folders and re-running the install script via `curl` would be the safest and easiest option, unless you really want to get in to the depths of development and play with `git` and tracking commits.
