### ISSUE TITLE
my pi hole is not blocking ads

### ISSUE THREAD

**Issue by asoliman74** [pi-hole/pi-hole#1627]
I have my pi hole running on a raspberry pi on my home network. I also have a vpn server running on a synology NAS. My pi hole is not working while I am on the wifi/at my house, however; my pi hole is working great and blocking all the ads if I am connected to my network through my vpn. Not sure why this is happening. Also, my ISP is COX. your help would be greatly appreciated!
--
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Hi, we need you to fill out the template that was presented to you when you opened the issue. It's the best way we can help you out.

**Comment by WaLLy3K** [comment]
In the template that's provided when you open a new ticket, there was the suggestion that you run the debug tool - this gives us greater insight to try and figure out what's happening!

If you could run `pihole -d`, upload the debug token and provide it here, that'd be extremely helpful.

Also, if you're running a Windows machine on your LAN (that currently *isn't* being covered by Pi-hole adblocking), I'd strongly suggest providing a screenshot of `ipconfig /all` so that we can see what DNS server the primary network adaptor currently configured to use.

Thanks! :smile:

**Comment by asoliman74** [comment]
<img width="648" alt="screen shot 2017-07-21 at 7 17 52 pm" src="https://user-images.githubusercontent.com/13020927/28487620-5ea75d1a-6e49-11e7-86cf-11e4eaa03754.png">

**Comment by asoliman74** [comment]
I using macOS. The above pic shows my raspberry pi IP address its 192.168.0.13
Also, I will run debug and send you guys the results

**Comment by asoliman74** [comment]
Here's the result from my /var/log/pihole_debug.log:::  ---= Resolver Functions Check (IPv4)
:::     Checking for necessary lighttpd files.
:::  
:::  ---= Detecting existence of /etc/lighttpd/lighttpd.conf:
:::       File exists, parsing...done
:::  
:::  ---= Detecting existence of /var/log/lighttpd/error.log:
:::       File exists, parsing...done
:::
:::  
:::  ---= Detecting existence of /etc/dnsmasq.conf:
:::       File exists, parsing...done
:::  
:::  ---= Detecting contents of /etc/dnsmasq.d/*:
:::  
:::  ---= File /etc/dnsmasq.d/01-pihole.conf found
:::       Parsing...done
:::  
:::  ---= File /etc/dnsmasq.d/README found
:::       Parsing...done
:::
:::  
:::  ---= Detecting existence of /etc/pihole/whitelist.txt:
:::       File exists, parsing...done
:::  
:::  ---= Detecting existence of /etc/pihole/blacklist.txt:
:::  /etc/pihole/blacklist.txt not found!
:::  
:::  ---= Detecting existence of /etc/pihole/adlists.list:
:::       File exists, parsing...done
:::  
:::  ---= Analyzing gravity.list
:::  
:::  ---= Analyzing pihole.log
:::  
:::  ---= Analyzing pihole-FTL.log
::: 
::: --= User Action Required =--
::: Try loading a site that you are having trouble with now from a client web browser.. 
:::	(Press CTRL+C to finish logging.)
:::  
:::  ---= pihole.log
::: Logging will automatically teminate in 60 seconds
::: Finshed debugging!.  
::: The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
::: Would you like to upload the log? [y/N] n
::: Log will NOT be uploaded to tricorder.
::: There was an error uploading your debug log.
::: Please try again or contact the Pi-hole team for assistance.
::: A local copy of the Debug log can be found at : /var/log/pihole_debug.log
root@raspberrypi:~# clear

root@raspberrypi:~# vi /var/log/pihole_debug.log




















































---= Detecting Installed Package Versions:

Pi-hole: v3.1.4 (master:v3.1.4-0-gb0ecedd)
Pi-hole Dashboard: v3.1 (master:v3.1-0-gf204b71)
lighttpd/1.4.35
PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58)

---= Detecting existence of /etc/pihole/setupVars.conf:

PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.0.13
IPV6_ADDRESS=
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
QUERY_LOGGING=true
INSTALL_WEB=true
TEMPERATUREUNIT=F
WEBUIBOXEDLAYOUT=boxed
DHCP_START=192.168.0.201
DHCP_END=192.168.0.251
DHCP_ROUTER=192.168.0.1
DHCP_LEASETIME=72
PIHOLE_DOMAIN=local
DHCP_IPv6=true
DHCP_ACTIVE=false


---= Detecting installed OS Distribution

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

---= Checking processor variety

armv7l

---= Checking IPv6 Stack

IPv6 on eth0
Gravity configured for: NOT CONFIGURED
----
2600:8800:5600:36d0:71e0:3acf:27d:1b61/64
fe80::f03d:7fe9:4990:f439/64

**Comment by asoliman74** [comment]
actually here is the log file

**Comment by asoliman74** [comment]
[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/1167073/pihole_debug.txt)

**Comment by dschaper** [comment]
Please fill out the template with your information.

**Comment by asoliman74** [comment]
How familiar are you with the codebase?:

7
[BUG REPORT | OTHER]:
pihole is not blocking ads while on my wifi network. however, its blocking ads when I connect through my synology vpn server.

[BUG | ISSUE] Expected Behaviour:
blocking ads
[BUG | ISSUE] Actual Behaviour:
not blocking ads
[BUG | ISSUE] Steps to reproduce:
loading up a website with ads like yahoo.com
(Optional) Debug token generated by pihole -d:

Not sure where to find the debug token but I have attached the pihole_debug log file from /var/log above.

**Comment by WaLLy3K** [comment]
Going off your screenshot, the Mac's DNS is pointing to `192.168.0.13` which matches the IP of your Pi-hole based off the debug log. That's good, but I'll also need a screenshot of the TCP/IP tab to confirm what the router is set to (which *should hopefully* reflect the Pi-hole DHCP server which you have active).

Could you also run the following command via Terminal on both your Pi-hole and Mac? `nslookup pi.hole`

**Comment by asoliman74** [comment]
<img width="675" alt="screen shot 2017-07-21 at 8 03 22 pm" src="https://user-images.githubusercontent.com/13020927/28487862-bbc4d62a-6e4f-11e7-8e8d-b5d0340b51a0.png">

**Comment by asoliman74** [comment]
root@raspberrypi:~# nslookup pi.hole
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	pi.hole
Address: 192.168.0.13

----------------------------------------------------------------------


MacBook-Pro:~ root# nslookup pi.hole
Server:		2001:578:3f::30
Address:	2001:578:3f::30#53

Non-authoritative answer:
Name:	pi.hole
Address: 92.242.140.2

**Comment by WaLLy3K** [comment]
It looks like the router at `192.168.0.1` has its own DHCP server that provides another set of DNS servers for clients on your LAN to use. You should look there and see what settings, if any, can be changed.

Start with seeing if you can disable the routers DHCP server, which will then let the Pi-hole take over the function since you've already enabled that via Web Admin.

**Comment by asoliman74** [comment]
<img width="492" alt="screen shot 2017-07-21 at 8 13 47 pm" src="https://user-images.githubusercontent.com/13020927/28487901-286ea386-6e51-11e7-96a9-3066fe3e5224.png">
I do not have DHCP enabled via web admin

**Comment by asoliman74** [comment]
I have already tried disabling DHCP on my router and enabling pihol DHCP server. but that did not fix my issue.

**Comment by WaLLy3K** [comment]
You're right, it wasn't enabled when you provided the debug log, my bad!

> I have already tried disabling DHCP on my router and enabling pihol DHCP server. but that did not fix my issue.

Did you renew the DHCP lease and flush the DNS cache *after* disabling the router's DHCP and enabling the Pi-hole DHCP?

Your Mac's configured to use the IPv4 of your Pi-hole, but macOS will always give priority to an IPv6 address - and neither of the two IPv6 addresses in the screenshots above match the IPv6's in the debug log.

**Comment by asoliman74** [comment]
Should I flush the DNS logs on the web admin page for the pihole?

**Comment by WaLLy3K** [comment]
I feel that considering that the clients on the network are not configured to use Pi-hole, the DNS logs on Web Admin aren't a concern.

**Comment by asoliman74** [comment]
So how do I flush my DNS log on macOS?

**Comment by WaLLy3K** [comment]
Since you're using WiFi on macOS, just turn your Wi-Fi off for a second or two, and turn it on again.

**Comment by asoliman74** [comment]
That did not work.

**Comment by WaLLy3K** [comment]
To confirm, you've disabled the routers DHCP, and enabled Pi-hole's DHCP server?

Could you take another look at the TCP/IP and DNS tabs, then provide me with new screenshots if they have changed from the ones you posted earlier?

**Comment by asoliman74** [comment]
<img width="660" alt="screen shot 2017-07-21 at 8 53 57 pm" src="https://user-images.githubusercontent.com/13020927/28488070-bef4d712-6e56-11e7-83f9-971c5eee2346.png">

**Comment by asoliman74** [comment]
It shows the lease have been renewed .. but the issue remains.

**Comment by WaLLy3K** [comment]
Yeah, TCP/IP tab looks like it's using the Pi-hole DHCP server.

What about DNS? Does it still show the same IPv6 addresses? If it does, then could you confirm whether you can click on any of the addresses and use the MINUS button on the bottom left? This will remove any manually configured DNS servers that macOS may be preferring over the IPv4 server.

**Comment by asoliman74** [comment]
It's not clickable.

**Comment by asoliman74** [comment]
Another thing. this is not just on macbook. its also happening on all the other devices I have on my wifi network

**Comment by asoliman74** [comment]
Please look at both images below.
The first image I am connected to my vpn server which is hard wired to my router at home(its a synology device) I am connected to the vpn over Verizon network. Ads are being blocked.

The second picture I turned off vpn and connected to my wifi at my house. Ads are not being blocked.

![image1](https://user-images.githubusercontent.com/13020927/28488164-373b24a4-6e59-11e7-92fa-07a30de6ee3b.PNG)
![image2](https://user-images.githubusercontent.com/13020927/28488165-373b6a54-6e59-11e7-9d58-f3b2330e4090.PNG)

**Comment by asoliman74** [comment]
I have my VPN server configured to use the pihole as my DNS server.
<img width="853" alt="screen shot 2017-07-21 at 9 13 40 pm" src="https://user-images.githubusercontent.com/13020927/28488187-928e7770-6e59-11e7-88eb-f95ec5767730.png">

**Comment by WaLLy3K** [comment]
Everything you've said enforces the fact that Pi-hole as a DNS filter is working, but that there's some configuration issue (either relating to DHCP, IPv6 or both) that's causing it to not work for your LAN clients.

At this point in time, I don't have any suggestions - is there any further troubleshooting that you'd be able to perform?

**Comment by asoliman74** [comment]
Am I supposed to be using pihole as my DHCP server instead of my gw in order for pihole to work properly?

**Comment by ryzunice** [comment]
Do you have DNS server enabled on your synology? Do you have VPN client software installed on the nodes?

**Comment by ryzunice** [comment]
No you do not need to run DHCP server on Pihole. Sounds like run VPN client is using IPv4 and there is a bug with IPv6 on Pihole.

**Comment by asoliman74** [comment]
I don't have a DNS server on synology.. but I am using a manual DNS for my VPN server by pointing it to the pihole.
No VPN clients installed on the nodes.
How do we fix the IPv6 bug?

**Comment by asoliman74** [comment]
I just wanted to let you guys know that I have fixed my issue. I had to enable DNS override on my router and point it to my raspberry pi's IPv6 address. Now pihole is working as expected. Thank you so much for pointing me in the right direction! you guys ROCK!!!!
