### ISSUE TITLE
What calls /etc/pihole/logrotate

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#1629]
As I understand logrotate, only config files in `/etc/logrotate.d/` are run via logrotate's system timer.  In reviewing the code, it seems that `/opt/pihole/piholeLogFlush.sh` is the only thing that calls `logrotate` to run using `/etc/pihole/logrotate` as the config file.  I didn't see any cron elements installed by the installer so I am confused as to how the logs are rotated on a daily basis... what is calling `/opt/pihole/piholeLogFlush.sh` to run?

**Comment by Mcat12** [comment]
Our cron job does call the flush command: https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.cron#L28

**Comment by graysky2** [comment]
Thank you.  I missed that.
