### ISSUE TITLE
Check for available disk space

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#163]
The automated installer should [check available disk space](https://github.com/jacobsalmela/pi-hole/issues/159#issuecomment-171060652), and if there is not enough, [expand the root filesystem](https://github.com/asb/raspi-config/blob/master/raspi-config#L36-L116).  

If users had to expand, a reboot would be required, but the next time they ran the install command, it would just start installing.

**Comment by hpincket** [comment]
**Estimating the required disk space:**
- my /etc/pihole is just under 17MB.
- the debian lighttpd [package](https://packages.debian.org/jessie/lighttpd) is no more than 900KB.
- the debian dnsmasq [package](https://packages.debian.org/jessie/dnsmasq) is only 114KB.

This totals to at least 18MB. I don't know what other files are created.

(The source can be larger. lighttpd is 3.8MB)

**Comment by DonLexos** [comment]
Another way to handle this is the same way as the `apt-get update` requirement/check: If the user needs to do it stop the installation and mention what he needs to do. Wouldn't it be better to simply notify that he can `sudo raspi-config` and fix it from there?

**Comment by PromoFaux** [comment]
The problem, as we discovered yesterday, is that we can't curl a script that contains a `read` in it. Or, we can, but the prompt is ignored and bash will just skip over it. 

We could change the command to:
`bash -c "$(curl -L install.pi-hole.net)"` 
which would allow us to have prompts in the install script. But that's not ideal, or as easy to remember as just :
 `curl -L install.pi-hole.net | bash`

Can you run `sudo raspi-config` at any time?

**Comment by DonLexos** [comment]
from within a script? depends, if you hide all output of other things I doubt that the config is shown. Next to that expanding the file system needs a reboot anyway so a stop of the installer would make sense. No input required, just as you don't need input when you stop the installer to 'force' the user to `apt-get update` first.

**Comment by PromoFaux** [comment]
Ah, did you not see the changes to the script last night? `apt-get update` is now run by the installer IF it hasn't been run already today (an ideal test for a fresh install). 

We have to force them to do that, so we can download the dependencies! But the installer will continue after that has run. We then recommend that they run `apt-get upgrade` (IF there are any packages to upgrade) after pi-hole has finished installing, but it is no longer mandatory to run that before installing, so the script will just continue on.

What if the user doesn't want their file-system expanded, for whatever reason?

**Comment by DonLexos** [comment]
Oh ok no I was not aware of that. In that case my remark makes no sense (it would have been SO to the point like, 17 hours ago). 

I dont think you should automatically do it, and frankly since there is a very good way of doing it why include it in the script?

**Comment by dschaper** [comment]
I don't think the script should auto-expand the filesystem, but we should warn about a small file size. One reason is that the Pi-hole may not be installed on a RasPi but either on another embedded system or another platform that doesn't have an expand function. It's kind of frustrating that `apt-get` doesn't check filesizes beforehand, like `pacman` does on the Arch platform.

**Comment by jacobsalmela** [comment]
A reboot on the Pi is also necessary in order to apply the changes after expanding the filesystem, which is kind of a pain, too.
