### ISSUE TITLE
Query Log - Long Domains push columns off page

### ISSUE THREAD

**Issue by WelcovIT** [pi-hole/pi-hole#1633]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Domain field should wrap long queries. I have seen some long queries wrap, but if they're too long, they won't wrap at all.

**[BUG | ISSUE] Actual Behaviour:**
The domain field pushes Client, Status, and Action columns off the page

**[BUG | ISSUE] Steps to reproduce:**
Produce an extremely long query. Was told to submit this bug here from my feature request on the discourse: https://discourse.pi-hole.net/t/query-log-domain-field-needs-to-wrap/4222

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Issue moved to [pi-hole/AdminLTE #555](https://github.com/pi-hole/AdminLTE/issues/555) via [**ZenHub**](https://www.zenhub.com/)
