### ISSUE TITLE
UI Whitelist Add - Split on space breaks when more than one space is used

### ISSUE THREAD

**Issue by rockmasterflex69** [pi-hole/pi-hole#1636]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT]:**

The split on space code specifically checks for exactly one space. This is silly. It might also be worth investigating if it is using an extremely general definition of whitespace for splitting, and if not, make it so.

**[BUG | ISSUE] Expected Behaviour:**
UI shouldn't give a flying fruit loop if you use one space or two as a separator, so "xxx.yz xxx.zz" and "xxx.yz&nbsp;&nbsp;xxx.zz" should be the same. Therefore, entering 
"notreal.org&nbsp;&nbsp;notreal.com" and clicking ADD should put both of these domains in your whitelist.

**[BUG | ISSUE] Actual Behaviour:**

The whitelist page will throw an error: "Failure! Something went wrong. <emptychar> is not a valid domain.

**[BUG | ISSUE] Steps to reproduce:**
Paste this into the window, click Add.
notreal.org&nbsp;&nbsp;notreal.com

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
this seems to be more of a feature request than a issue or bug.  most users will enter the black or whitelist domains one at a time or directly modify the files on the device itself as opposed to copy paste from large lists which is where this seems to be coming from

Please submit this using the below link on the discourse forum 

Feature requests are here : https://discourse.pi-hole.net/c/feature-requests

**Comment by dschaper** [comment]
It borders on both a bug and a FR, breaking on whitespace should be in the function, I just have to find which function does that and hope it's not buried in the `awk` stuff.

**Comment by WaLLy3K** [comment]
If separating domains with multiple spaces using `pihole`, it separates the two out as expected.
```
pihole -w foo.bar.com     foo.bar
::: Adding foo.bar.com to /etc/pihole/whitelist.txt...
::: foo.bar.com does not exist in /etc/pihole/blacklist.txt, no need to remove!
::: foo.bar.com does not exist in /etc/dnsmasq.d/03-pihole-wildcard.conf, no need to remove!
::: Adding foo.bar to /etc/pihole/whitelist.txt...
::: foo.bar does not exist in /etc/pihole/blacklist.txt, no need to remove!
::: foo.bar does not exist in /etc/dnsmasq.d/03-pihole-wildcard.conf, no need to remove!
```

If doing the same via Web Admin, the issue that O.P discovered comes into play. Thus, this is definitely a bug for [AdminLTE](https://github.com/pi-hole/AdminLTE).

**Comment by dschaper** [comment]
Moving to Admin repo...

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #554](https://github.com/pi-hole/AdminLTE/issues/554) via [**ZenHub**](https://www.zenhub.com/)
