### ISSUE TITLE
Open blocked-ads in headless chrome

### ISSUE THREAD

**Issue by farfeduc** [pi-hole/pi-hole#1641]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
6

---
**[Feature request]:**

Allowing on some websites (maybe add a list in the admin panel ?) to have their ads opened in a [headless-chrome](https://github.com/graphcool/chromeless) in order to financially support them might be a nice feature. 

This way you could still support the websites you like without having the ads. 💰 

What do you think ? Would it work ? 

Feel free to ask questions. I would gladly help to implement such a feature.

You can "vote" with a reaction to this issue. ( 👍  or 👎  )

**Comment by PromoFaux** [comment]
Thanks for reading _some_ of the [template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) for a new issue, but you missed this bit:

>**[BUG REPORT | OTHER]:**

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.
