### ISSUE TITLE
DNS not working if trying to connect while pi-hole is rebooting

### ISSUE THREAD

**Issue by AdrienLF** [pi-hole/pi-hole#1642]
Hello everyone,

I have a bug that makes the pihole quite a pain to use: 

I installed the pihole on a raspberry pi 3, and enabled the DHCP server on it (and deactivated the one on my router). It works well, my connection isn't slower, it blocks ads on my pcs and phones. 

However, since I'm setting up my raspberry pi, I have to reboot it quite often. I also have scripts on my main computer running constantly, accessing the Internet every second. 

When I reboot my raspberry pi and trying to access internet on my computer, I have a DNS error. I can only fix it by rebooting my router once pihole is running.

However, if I don't try to access internet while my pi is rebooting, and only access it once pihole is launched, I don't have any issue connecting to the internet. 

Did I set it up wrong?

**Comment by Mcat12** [comment]
What requires you to reboot your Pi so often? You should be installing Pi-hole on a device that stays up 24/7.

**Comment by AdrienLF** [comment]
That's definitely what I aim for yes. I'm trying to launch a bunch of python scripts on startup (with the terminal visible) and I'm having a very hard time finding a way to do it. I reboot a lot to check if whatever I tried worked. Crontrab @reboot and rc.local so far didn't work. Once this is set up I shouldn't really turn it off.

**Comment by dxm765** [comment]
Do you only have 1 DNS resolver on your computer/devices? If you set a secondary IP address for DNS such as 8.8.8.8 or similar, if the pi goes down for any reason the devices should still be able to reach the internet with the secondary DNS , however it might be easier to get another Pi for Pi-Hole itself rather then sharing.

**Comment by AdrienLF** [comment]
I added 8.8.8.8 as a secondary DNS to my router yes, but it doesn't seem to resolve the issue unfortunately. 

I COULD solve the problem by buying, and setting up another pi, but this still feels to me like a software issue, and even for my own understanding of how my network works at home, I would prefer fixing it :)

**Comment by dxm765** [comment]
When you're rebooting the Pi its services aren't running, including the DNS service. If you only care about your desktop computer you could set the network interface's IPv4 address statically for the Pi-Hole as the primary DNS and then set the secondary DNS as 8.8.8.8 , that would mean that if the Pi and Pi-Hole are offline it should fall back to 8.8.8.8 , setting it on the router wont do anything if your computer is only "told" to use the Pi-Hole IP address for DNS.

**Comment by AdrienLF** [comment]
Changing it on my router didn't make an effect, but you're right, I'll change it on my computer, maybe it'll solve this issue at least for this machine.

**Comment by darkrain-nl** [comment]
If you set a secondary DNS server in Windows you will sometimes see ad's, this is because Windows will use the secondary DNS server sometimes to make sure it is still online.
DNS servers in Windows are not chosen from top to bottom and also not based on online or offline.

**Comment by AdrienLF** [comment]
I did not know that, thanks!

**Comment by WaLLy3K** [comment]
Hey @AdrienLF, have you been able to resolve this issue?

**Comment by AdrienLF** [comment]
In the end I stopped using pi-hole but I'll set it up again soon (I'm moving now). I'll come back here to update on the issue.

**Comment by jacobsalmela** [comment]
@AdrienLF any update?  Have you tried not running the Python scripts at startup to see if the behavior is the same?  You may be able to isolate the script that could be causing the issue.

**Comment by jacobsalmela** [comment]
@AdrienLF do you still have this issue in v3.2?
