### ISSUE TITLE
Change directory for .ovpn created from autoinstall?

### ISSUE THREAD

**Issue by hgelpke** [pi-hole/pi-hole#1644]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Script gives option on where to create open vpn config file

**[BUG | ISSUE] Actual Behaviour:**
Script automatically creates script in /root which is problematic if root account is disabled.

**[BUG | ISSUE] Steps to reproduce:**

-  Run script a is
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Hi @hgelpke, did you mean to post this issue to https://github.com/pivpn/pivpn?

**Comment by dschaper** [comment]
Not a Pi-hole issue.
