### ISSUE TITLE
Using http://pi.hole/admin does not work but http://192.x.x.x/admin does

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#1645]
I haven't been able to get the `http://pi.hole/admin` to resolve to the correct IP of the pi-hole server (using the numerical IP or the hostname does work).  This is on an ubuntu install (upstream script) or on a Arch install (AUR package).  Is there a key config file that setups this redirect?  Perhaps I am missing it.

http://pi.hole/ --> fail
http://192.168.1.210/ --> success
http://piholearm/ --> success

My `/etc/pihole/local.list` does look like it is in fact setup to do this:
```
# cat /etc/pihole/local.list
192.168.1.210 piholearm
192.168.1.210 pi.hole
```

**Comment by Mcat12** [comment]
If you can't resolve `pi.hole` then either that device is not using Pi-hole or it has an invalid DNS cache entry for that domain (flush the cache).

**Comment by technicalpyro** [comment]
another thing is depending on the amount os hosts in the hosts file the pi.hole domain is unavailable after a gravity run (post update or manually running gravity) is this issue present ALL the time?

**Comment by graysky2** [comment]
@Mcat12 - I can watch the pihole.log add up as I browse from devices so I do think I have it configured correctly for use.  What is the recommended method to flush the cache?

@technicalpyro - Yes, the issue is always present.

Again, to simplify things, I am making these statements from a ubuntu install via the official script.

**Comment by Mcat12** [comment]
Flushing the cache depends on the system, so google the system + "flush dns cache". If you're unable to resolve `pi.hole` ON the Pi-hole, then change your system's DNS settings to point to itself (`127.0.0.1`).

**Comment by graysky2** [comment]
@mcat12 - OK... on the pi-hole machine itself, I am able to `ping pi-hole` and get returns.  I am unable to do the same on other boxes on the LAN though... the router is set to you the pi-hole machine's IP address for DNS resolution and it works for all traffic.  If there a configuration I am missing?

**Comment by Mcat12** [comment]
Since you're using the Arch version (not made by us), it doesn't have the debug log functionality, so I can't easily see more about your setup... If it is not working when having the router give out DNS servers, try using Pi-hole's DHCP server instead of the router's.

**Comment by graysky2** [comment]
@mcat12 - I edited my above post talking only about the ubuntu box using your script (let's keep the Arch box out of the picture to simplify troubleshooting).

**Comment by Mcat12** [comment]
Run `pihole -d` on the Ubuntu install for a debug token.

**Comment by dschaper** [comment]
Close for stale.
