### ISSUE TITLE
Instructions for DNS redirecting

### ISSUE THREAD

**Issue by harshil2105** [pi-hole/pi-hole#1649]
1)The issue I'm reporting maybe a duplicate of DNS redirecting issue...After all of the given instructions on how to redirect to a different domain after editing all the files I'm not able to redirect to any page
2)This might be a big
3)After all the time some changes might have resulted in its failure of redirection
4)For information on about what I'm talking on please visit this page https://github.com/pi-hole/pi-hole/issues/333
5)This is the page on which you show how to successfully redirect to a different domain 
6)My problem is even after following them out can't forward to a different domain 
-

**Comment by Mcat12** [comment]
Did you see this? https://github.com/pi-hole/pi-hole/wiki/FAQs#can-i-redirect-a-domain-to-a-different-domain-333
We don't really support redirecting domains to other domains, as it is not related to our focus (ad blocking). For that reason, this is not a bug or issue with Pi-hole.
