### ISSUE TITLE
DNS failures

### ISSUE THREAD

**Issue by nuentes** [pi-hole/pi-hole#1650]
I had Pi-Hole working via [this guide](https://github.com/pi-hole/pi-hole/wiki/Pi-hole---OpenVPN-server), through tun0. However, I decided I wanted to go through eth0 instead, so I ran `pihole -r` and reconfigured with the eth0 network interface. I temporarily disabled openVPN entirely with `sudo systemctl stop openvpn` and I completely emptied out iptables. I can load web pages on the Pi, but when I set my routers DNS to the pi's address (192.168.1.11), I get DNS errors, and cannot load any pages. What am I missing?

**Comment by nuentes** [comment]
Ok, I re-installed raspbian to get a fresh image (I had other reasons, too). However, I'm still having the same issue. [Here](https://i.imgur.com/x4xZWHe.jpg) is what I'm changing on my router. However, now I'm thinking my issue is that this changes the DNS for the WAN, and not just the LAN. I can't seem to find a way to change the LAN DNS server, like it says in [this guide](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245). Seriously - what am I missing?

**Comment by Mcat12** [comment]
Sorry to have not replied earlier. Have you tried to disable the router's DHCP server and enable the Pi-hole's?

**Comment by nuentes** [comment]
No, I haven't tried that yet. I'll give it a crack tomorrow afternoon.

**Comment by nuentes** [comment]
Ok, that seems to be working now. Any idea why I needed this now with eth0? I didn't need it when I followed the guide to install openVPN and went through tun0?

**Comment by Mcat12** [comment]
The VPN sets its own DNS servers instead of the router doing so, and your router may have not been configured correctly or would not cooperate. Using Pi-hole as your DHCP server usually fixes these kinds of issues.

**Comment by dschaper** [comment]
Close for stale.
