### ISSUE TITLE
php-zip is not installed

### ISSUE THREAD

**Issue by anudeepND** [pi-hole/pi-hole#1651]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [✓] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [✓] The issue I am reporting can be *replicated*
- [✓] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
3

---

**[BUG | ISSUE] Expected Behaviour:**

php-zip libraries should be installed when installing pihole
### php7.0-zip or php5.6-zip or php-zip should be installed (depending upon the PHP version) at the time of installing pihole

**[BUG | ISSUE] Actual Behaviour:**

php-zip is not installed on default some os like Ubuntu server, due to this pihole teleporter doesn't work

**[BUG | ISSUE] Steps to reproduce:**

Install pihole on Ubuntu server 16.04 (I checked on ×86_64 system)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by anudeepND** [comment]
## Default installation 


![img_20170803_155122](https://user-images.githubusercontent.com/26179946/28917617-dd521aa0-7863-11e7-8364-1549db815b81.jpg)

## After installing php-zip extension 

![img_20170803_155157](https://user-images.githubusercontent.com/26179946/28917647-f6f82490-7863-11e7-9ee1-7b53b5d62c24.jpg)

**Comment by anudeepND** [comment]
php7.0-zip or php5.6-zip or php-zip should be added to installation file

**Comment by PromoFaux** [comment]
Sorry @anudeepND , missed this one!

@DL6ER , teleporter is your baby.. was there a reason this dependency wasn't added to the installer?

**Comment by anudeepND** [comment]
This issue can be reproduced in raspbian stretch lite (reported on [Pi-Hole Discourse forum](https://discourse.pi-hole.net/t/teleporter-php-not-installed/4612)). To fix it `php7.0-zip` should be installed.

**Comment by ernesto75** [comment]
Took a quick look, and tried to fix it, please check if everything is fine. 
I'm not sure of the uninstall script, maybe  ${phpVer}-zip should be used?

[diff.txt](https://github.com/pi-hole/pi-hole/files/1362353/diff.txt)

**Comment by jacobsalmela** [comment]
I cannot replicate this on new installs of v3.2.  @anudeepND can you confirm?

**Comment by anudeepND** [comment]
@jacobsalmela Tested with Ubuntu 16.04, teleporter works fine

**Comment by anudeepND** [comment]
Closing...
