### ISSUE TITLE
Changing IP address question

### ISSUE THREAD

**Issue by jsfrederick** [pi-hole/pi-hole#1652]
Quick question.  If I need to change the subnet of my home network (ie. from 192.168.0.xx to 192.168.5.xx) will I have to reinstall Pi-Hole, or can I change the IP address of my RPi and reboot.  I do realize I will need to cagnge the IP addresses in the DNSMASQ config files in /etc/pihole.  Are there any other Pi-Hole related configuration files I would need to change?

Thanks

**Comment by Mcat12** [comment]
You can run `pihole -r` to reconfigure Pi-hole with the new IP address. You shouldn't have to change it in Pi-hole's auto-generated config files.

**Comment by jsfrederick** [comment]
Ahhh, yes. I forgot that.  Thanks!

**Comment by dschaper** [comment]
Solved, close.
