### ISSUE TITLE
CentOS 7 installer crashes out if nmcli is not available

### ISSUE THREAD

**Issue by slacker87** [pi-hole/pi-hole#1653]
The CentOS/Fedora portion of the installer should do a basic sanity check to verify the NetworkManager service is running, if not it should start the service for the user via:` systemctl start NetworkManager`

Currently if the service is installed but not running the installer will just crash back to bash with a `Error: NetworkManager is not running.` Error message which leaves the user to search the web for an answer.

**Comment by jacobsalmela** [comment]
@bcambl I tested on a fresh droplet and was not able to reproduce this.  Is `NetworkMangler` supposed to be installed by default on CentOS?

**Comment by bcambl** [comment]
Yes. `NetworkManager` should be enabled by default.

**Comment by jacobsalmela** [comment]
@bcambl did we fix this one for 3.2?

**Comment by bcambl** [comment]
No this was not addressed in 3.2 but I will address this shortly.

**Comment by jacobsalmela** [comment]
Great thanks!

**Comment by bcambl** [comment]
@slacker87 Thanks for submitting an issue. Cheers!
