### ISSUE TITLE
Changed settings via admin webpage don't save, re-prompts for login

### ISSUE THREAD

**Issue by RaceFPV** [pi-hole/pi-hole#1654]
When I attempt to change any settings in the admin panel after logging in, clicking 'save' redirects back to the login page. If I then login again, the settings I've changed are not saved.

Blocking/dns/everything else is working fine, CentOS 7.

Debug token: y9jp2ux439

**Comment by Mcat12** [comment]
Do you have cookies enabled?

**Comment by slacker87** [comment]
Sure do! I've also tried several different browsers with the same results.

**Comment by Mcat12** [comment]
If you open up the dev tools (F12), do you see any errors in the console?

**Comment by slacker87** [comment]
Nothing in console, I will note though that by even just clicking the 'settings' tab I get prompted to login, even if I was already logged in, almost like it didn't properly authenticate/remember.

**Comment by Mcat12** [comment]
Do you have SELinux on?

**Comment by slacker87** [comment]
Nope, completely disabled :+1:

**Comment by Mcat12** [comment]
PHP must not be able to keep track of your session then. I don't see any PHP errors or disk space errors in your log... Do you see anything in `/var/log/lighttpd/error.log` and do you have enough free disk space?

**Comment by slacker87** [comment]
15G space free, and log has like nothing in it. I agree it does sound like a session issue though.

**Comment by FuriouslyAdrift** [comment]
I have the same issue on Fedora 26 with SELinux on permissive. In dev console, though, I get this on login.

Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at objectToArray (index.js:17)
    at Object.success (index.js:158)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by Mcat12** [comment]
It sounds like your PHP setup is messed up, because it can't start a session.

**Comment by jacobsalmela** [comment]
@slacker87 do you still have this issue in v3.2?  I cannot replicate it
