### ISSUE TITLE
install on no fresh server

### ISSUE THREAD

**Issue by azlux** [pi-hole/pi-hole#1655]
Hi all,
I have a raspberry with a lot of services. (nginx, php7, dnsmasq, openvpn ....)
The auto-install crash here : 
```
:::    Checking for lighttpd... installed!
:::    Checking for php-common... installed!
:::    Checking for php-cgi... added to install list!
```
No log, no conf created .... I suppose the auto install crash because of my current running services.
Do you have an install guide to install it manually ? What do I need to remove to make it work.

Thank
Az

**Comment by slacker87** [comment]
You could try installing php-cgi manually via `sudo apt-get install php7.0-cgi`

**Comment by azlux** [comment]
php7.0-cgi is already installed.

**Comment by Mcat12** [comment]
Try installing all the packages that are marked to be installed in the list.

**Comment by azlux** [comment]
Don't know how, but even if all my package was already installed, the script didn't crash this time.
