### ISSUE TITLE
Whitelisting Problems - 

### ISSUE THREAD

**Issue by F0erster** [pi-hole/pi-hole#1657]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Whitelisting enables me to visist pages.

**[BUG | ISSUE] Actual Behaviour:**

Whitelisting via GUI adds visible entries (for example "gearbest.com) to the list. After flushing browser DNS cache, windows 10 DNS cache and restarting pihole, it still does block the said adress and shows so in the query log. "pi-holed www.gearbest.com". Log attached.

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`kkh3y5ecau`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hey @F0erster, thanks for providing the debug token!

Looking at the log, `www.gearbest.com` is a CNAME which means that any of the following could be blocked:

* `www.gearbest.com`
* `gearbest.com.edgekey.net`
* `e5504.a.akamaiedge.net`

Try this: `pihole -w www.gearbest.com gearbest.com.edgekey.net e5504.a.akamaiedge.net` and flush your DNS cache again afterwards.

**Comment by F0erster** [comment]
Hey WaLLy3k, thank you for your response, as well as your comprehensive adlists that i got from reddit.

unfortunately though, your tip did not seem to work :( i can see the additional entries in the whitelist, but gearbest.com still gets piholed. `pihole -q gearbest` shows me 4 or so entries in various adlists, in the format of www.gearbest.com and gearbest.com. But they should be overriden by the whitelist do they?
Flushed DNS'es and all. Restarted pihole... i don't know.

**Comment by WaLLy3K** [comment]
Both `www.gearbest.com` and `gearbest.com` count for two separate entries, so you'd definitely need to whitelist them both - and you'd probably want to whitelist the other two entries of the four you mention.

I'd normally tell you exactly what you need to whitelist, but I can't see anything related to gearbest on the lists that I suggest!

**Comment by F0erster** [comment]
you misunderstood me, i did in fact add

-`www.gearbest.com`
-`gearbest.com.edgekey.net`
-`e5504.a.akamaiedge.net`

to the whitelist and can see them in there. The domain somehow still gets piholed. I can also see the entries if i SSH into the whitelist.txt.

**Comment by PromoFaux** [comment]
`gearbest.com.edgekey.net` != `gearbest.com`

**Comment by PromoFaux** [comment]
From your pi, what is the output of:
`nslookup gearbest.com`

and 

`nslookup www.gearbest.com`

?

**Comment by PromoFaux** [comment]
From your pi, what is the output of:
`nslookup gearbest.com`

and 

`nslookup www.gearbest.com`

?

**Comment by F0erster** [comment]
gearbest.com:

`
Non-authoritative answer:
Name:   gearbest.com
Address: 52.37.23.38
Name:   gearbest.com
Address: 52.42.173.166

`

www.gearbest.com:
`
Non-authoritative answer:
www.gearbest.com        canonical name = gearbest.com.edgekey.net.
gearbest.com.edgekey.net        canonical name = e5504.a.akamaiedge.net.
Name:   e5504.a.akamaiedge.net
Address: 23.53.169.52
`

**Comment by F0erster** [comment]
OK, i found out someting i can't make anything of. PiHole Query shows, that www.gearbest.com gets piholed on IPv4 and forwarded according to whitelist on IPv6. 
What can this mean?

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

**Comment by F0erster** [comment]
thank you, now it's only showing the IPv4 blocking. But the problem remains.. Whitelisted and still blocked by Pi :(

**Comment by Mcat12** [comment]
You are using nginx instead of lighttpd, which means that the `pihole` commands that are executed in order to whitelist the domains are failing. You don't have the domains in the `whitelist.txt` file because of this. Disable nginx and let lighttpd use port 80 so that the commands can succeed.

**Comment by F0erster** [comment]
ok, does that require me to just edit some file or is this a more complicated thing to do? I'm sorry i'm not that good at all this and probably need a bit of guidance to get this to work. thank you very much :)

**Comment by Mcat12** [comment]
You should be able to disable nginx via:
```
sudo systemctl disable nginx
```
Then make sure lighttpd is started:
```
sudo systemctl restart lighttpd
```

**Comment by F0erster** [comment]
OK, i entered

`sudo systemctl disable nginx`

should something appear after entering? because i got no message after that.
Entering 

`sudo systemctl restart lighttpd`

after that got me

`Running in chroot, ignoring request.`

This all runs on my Synology NAS where I installed Debian, so i run all this under 

`/var/packages/debian-chroot/scripts/start-stop-status chroot`

otherwise he does not recognize all the commands regarding pihole. I'm really sorry that i'm being such a newbie at this but i try my best to get this right. PiHole seems to run great besides this problem though. 

Maybe i helps you to know how all this runs on my NAS? I have been installing, updating and using PiHole after this guide for months: 
https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289

**Comment by Mcat12** [comment]
Oh, if you're running this on Synology, you should use the docker image to make sure everything works correctly: https://github.com/diginc/docker-pi-hole

**Comment by Spaddex** [comment]
I have the exact same problem.
lighttpd running on port 80 (for Pihole), and nginx on port 81. 
Tried disabling nginx and restarting the system, still no luck.

amazon.com get's blocked on ipv4, but ipv6 is allowed.
amazon.com is present in _/etc/pihole/whitelist.txt_

_error.log_ shows output when restarted:
	2017-08-20 12:09:58: (server.c.1558) server stopped by UID = 0 PID = 1 
	2017-08-20 12:09:58: (log.c.164) server started 
	2017-08-20 12:09:58: (server.c.1045) WARNING: unknown config-key: alias.url (ignored) 
Related? 
	https://github.com/pi-hole/pi-hole/issues/101

Did "sudo pihole -r" and repaired the installation as well, no luck. 

$ pihole -w amazon.com
::: amazon.com already exists in /etc/pihole/whitelist.txt, no need to add!
::: amazon.com does not exist in /etc/pihole/blacklist.txt, no need to remove!
::: amazon.com does not exist in /etc/dnsmasq.d/03-pihole-wildcard.conf, no need to remove!

From _/var/log/pihole.log_
Aug 20 12:09:19 dnsmasq[8136]: query[A] amazon.com from 192.168.1.169
Aug 20 12:09:19 dnsmasq[8136]: /etc/pihole/gravity.list amazon.com is 192.168.1.22
Aug 20 12:09:19 dnsmasq[8136]: query[AAAA] amazon.com from 192.168.1.169
Aug 20 12:09:19 dnsmasq[8136]: forwarded amazon.com to 208.67.222.222
Aug 20 12:09:19 dnsmasq[8136]: reply amazon.com is NODATA-IPv6

**Comment by Mcat12** [comment]
@Spaddex Run `pihole -d` for a debug token. If you don't have IPv6 internet access, then follow this guide: https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

**Comment by F0erster** [comment]
Well, so i did as you said and ditched my whole Pi-Hole setup. Now, after a lot of research and some tinkering, I am running the Pi-Hole in a Docker Container and behold: 
Adding your entries to the whitelist does now indeed forward the Gearbest adress. 
Thank you very much, @Mcat12!

One question still: I can only change things over the Pi-Hole Web-interface now. I used to connect via SSH and use the pihole commands, which i cannot do anymore with this Docker stuff running. I haven't found a way to run the commands in the container, the docker terminal that is included does not seem to work. Can you give me a hint there?

**Comment by Spaddex** [comment]
@Mcat12: Sorry, didn't know I needed a debug-token for a bug which was already reported. Here is the token: po7iqrga51
Regarding "If you don't have IPv6 internet access...", as I mentioned in my post which you responded to, I actually explicitly said that I tried that and it didn't work.

**Comment by PromoFaux** [comment]
>I haven't found a way to run the commands in the container, the docker terminal that is included does not seem to work. Can you give me a hint there?

If you're using @diginc's container, see here: https://github.com/diginc/docker-pi-hole#pihole-features

**Comment by PromoFaux** [comment]
>Sorry, didn't know I needed a debug-token for a bug which was already reported

Debug token's are always a good idea if you're facing an issue. Whilst your issue may appear on the surface to be the same, it may be something completely different. It's just a good way to help us help you diagnose the issue

As you don't have any IPv6 connectivity to the outside world, there is nothing to block. However, clients will still sometimes make AAAA queries, even if they can't use the returned address.

I can't tell from your debug log (I don't think it's a file we check.. should probably fix that) but can you please give the output of the command? Thanks!

`cat /etc/pihole/pihole-FTL.conf`

**Comment by Spaddex** [comment]
@PromoFaux , Sure thing:
`$ cat /etc/pihole/pihole-FTL.conf
AAAA_QUERY_ANALYSIS=no
`

**Comment by PromoFaux** [comment]
And did you definitely restart `FTL` to read in that config file?

`sudo service pihole-FTL restart`

**Comment by Spaddex** [comment]
@PromoFaux, tried restarting both FTL and the device itself.

**Comment by Mcat12** [comment]
Run `pihole -d` for another debug token and share the output of `cat /var/log/pihole-FTL.log`

**Comment by WaLLy3K** [comment]
Closing this issue, as I understand that O.P's issue has been resolved. If you're still having issues @F0erster, you're more than welcome to get in touch again!
