### ISSUE TITLE
FTL not starting automatically

### ISSUE THREAD

**Issue by klische** [pi-hole/pi-hole#1659]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1
---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
FTL starts after system restart

**[BUG | ISSUE] Actual Behaviour:**
FTL does not start, sudo service pihole-FTL status returns "Unknown job: pihole-FTL"
The issue seems related to: https://github.com/pi-hole/pi-hole/issues/1433

**[BUG | ISSUE] Steps to reproduce:**

1. Restart computer
2. Check pi-hole admin page: it's up and ads are being blocked, but says "lost connection to API"
3. sudo service pihole-FTL restart: Stopped FTL started!
4. Check pi-hole admin page: it's up, but just has a progress circle that spins and the top part that used to display "Lost connection to API" now has "---". Ad blocking is still working however.
5. pihole -r, choose repair. Check admin page, it's up, but now says "lost connection to API" 
6. sudo service pihole-FTL restart: Not running FTL started!. 
7. Admin page is up and working, but takes a while for it to display information

**(Optional) Debug token generated by `pihole -d`:**

`mug97tny01`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Why do you think this issue is related to #1433 ?

What is the output of `sudo service pihole-FTL status` ?

Does `/etc/init.d/pihole-FTL` exist?

**Comment by klische** [comment]
I thought mentioning https://github.com/pi-hole/pi-hole/issues/1433 might be helpful, since FTL was not starting for me either.

What is the output of sudo service pihole-FTL status ?
status: Unknown job: pihole-FTL

/etc/init.d/pihole-FT Exists

**Comment by klische** [comment]
Any update on this?

**Comment by Mcat12** [comment]
What init system or operating system is the Pi-hole using? Run `pihole -d` for a new debug token.

**Comment by klische** [comment]
ezjgx6d99k

**Comment by klische** [comment]
OS: Ubuntu 14.04.5 LTS

**Comment by Mcat12** [comment]
What is the output of `sudo systemctl status pihole-FTL`

**Comment by klische** [comment]
sudo: systemctl: command not found

**Comment by Mcat12** [comment]
If you update to a more modern OS (such as Ubuntu 16 or 17) then you will likely have a much better time installing Pi-hole.

**Comment by klische** [comment]
👍 Will update to latest and report back.

**Comment by klische** [comment]
Works perfectly in Ubuntu 17.04. Thank you for looking into this :)

**Comment by anselal** [comment]
I get the message "The script you are attempting to invoke has been converted to an Upstart" and cannot start FTL

**Comment by dschaper** [comment]
This issue was closed a year and a half ago, please open an new issue.
