### ISSUE TITLE
Safari back button for google search does not work (macOS)

### ISSUE THREAD

**Issue by klische** [pi-hole/pi-hole#1660]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1
---
**[BUG | ISSUE] Expected Behaviour:**
Back button works and takes you back to the Google search results

**[BUG | ISSUE] Actual Behaviour:**
After turning off the DNS setting to pi-hole, the back button works in Safari. Pointing the macOS DNS to pi-hole breaks the back button for google searches.

**[BUG | ISSUE] Steps to reproduce:**
- macOS 10.12.6 (Sierra)
- Safari Version 10.1.2 (12603.3.8)
- Navigate to www.google.com in a new tab or window and search for anything
- Click any search result
- Press back, notice that the search results do not display
- This does not happen in Chrome or when the Mac's DNS is not pointed to pi-hole

**(Optional) Debug token generated by `pihole -d`:**

`mug97tny01`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
I'm unable to replicate this issue using BrowserStack. Maybe someone else with a Mac can reproduce this? I haven't heard of this issue before, so I think it might be an unrelated issue. For example, the gateway internet connectivity tests failed in your debug log and one of your IPv6 DNS tests failed.

**Comment by PromoFaux** [comment]
I'll see if I can borrow my Wife's Macbook from her later for a few minutes and see. But she has not complained of this so far (and she usually does if Pi-hole broke something!)

**Comment by norrkin** [comment]
Works fine here with the same macOS & Safari versions - Pi-hole Version v3.1.4 Web Interface Version v3.1 FTL Version v2.10

Do a google search, click on a result then click back button and search results are the same as before.

**Comment by PromoFaux** [comment]
@klische Do you have any other extensions installed?

**Comment by PromoFaux** [comment]
@klische Any update on thiis?

**Comment by klische** [comment]
Hmm, this issue seems to have resolved itself. Thanks for looking into this :)
