### ISSUE TITLE
Not blocking ipv6

### ISSUE THREAD

**Issue by raviriley** [pi-hole/pi-hole#1662]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Blocking over ipv6

**[BUG | ISSUE] Actual Behaviour:**
Blocking over ipv4, not blocking over ipv6. Even Google double click ads get through with ipv6.

**[BUG | ISSUE] Steps to reproduce:**
I set up pi-hole with both ipv6 & ipv6 selected in the set-up process, but only ipv4 ads are blocked, so most ads still get thru via ipv6. How do I fix this? 

**(Optional) Debug token generated by `pihole -d`:**

`8tvs8sgi3k`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
According to your debug log, you don't have IPv6 setup on your Pi. Do you definitely have IPv6 connectivity? If you only have a local IPv6, then blocking is not enabled for that as there would be no point. That said, IPv6 queries will still be made by clients, and they will show as allowed, even though they are (probably) not able to connect...

Details Here: https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

**Comment by raviriley** [comment]
@PromoFaux all of the ads going thru ipv6 show up on my devices. For example google doubleclick ads goes through on ipv6 and the doubleclick ads show up on the ipad and laptop.

**Comment by Mcat12** [comment]
I can't see your debug token now, but try running `pihole -r` again to reconfigure with IPv6. Then run `pihole -d` for another debug token.

**Comment by WaLLy3K** [comment]
If you're still experiencing this issue @raviriley, you're more than welcome to reply to this ticket. In the meantime, I'm closing it due to inactivity.

**Comment by raviriley** [comment]
@WaLLy3K I had some strange issues so did a clean reflash of my board, then re installed Pi-Hole. On initial config, I selected both ipv4 and ipv6, but I only set up a static ipv4 address. Still having the same issue of no blocking on ipv6. Do i need to assign a static ipv6? If yes, how do I do that? Thanks

**Comment by WaLLy3K** [comment]
*Assuming* your ISP provides you a delegated static IPv6 prefix, you shouldn't need to set a static IP yourself. However, you can still look into seeing if [Unique Local Addresses (ULA)](https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127) are available for you to enable.

There's a slight possibility that you may have two conflicting issues, so check these links out and see what your testing results are:

1. [Why do blacklisted domains show IPv4 as “Pi-holed” but not IPv6 in the query log?](https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652)
2. [Why do I see ads in Chome but not other browsers?](https://discourse.pi-hole.net/t/why-do-i-see-ads-in-chome-but-not-other-browsers/3284)

If you're finding you're still having issues, let us know and we'll follow it up further.

**Comment by jacobsalmela** [comment]
@raviriley did any of @WaLLy3K's suggestions fix the issue for you?

**Comment by jacobsalmela** [comment]
@raviriley is this still an issue for you in v3.2?
