### ISSUE TITLE
iptables not updated for IPv6

### ISSUE THREAD

**Issue by pew** [pi-hole/pi-hole#1664]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT | OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**
If iptables config is detected, pi-hole should configure iptables for ipv4 and ipv6.

**[BUG | ISSUE] Actual Behaviour:**
pi-hole checks if an iptables firewall is configured, if it does and the user accepts to "open up" the firewall, pi-hole only changes ipv4 config but not ipv6.

**[BUG | ISSUE] Steps to reproduce:**

- install pi-hole on ipv4 and ipv6 capable server
- enable iptables firewall
- configure pi-hole, accept firewall changes made by pi-hole
- run dns request against ipv6 address

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
We're going to create a document page with the required ports and the methods to open those ports on the host firewall. We don't feel that opening the ports on servers is something we should be doing. Thanks for the report and we'll get the documents up shortly.
