### ISSUE TITLE
dnscrypt-proxy.service vs dnscrypt-proxy.service.in

### ISSUE THREAD

**Issue by blub4747** [pi-hole/pi-hole#1665]
Hi guys,

I have a quick question on your guys installation guide.
from https://github.com/pi-hole/pi-hole/wiki/DNSCrypt
I compiled dnscrypt myself with the usual ./configure, make, make install commands.
The guide than says, that the following files need to be modified.

> dnscrypt-proxy.service and dnscrypt-proxy.socket

However I can not find 'dnscrypt-proxy.service'
the only file which close to it is 'dnscrypt-proxy.service.in'
Is 'dnscrypt-proxy.service.in' the correct file ?
Or where I please find the 'dnscrypt-proxy.service'file ?

Thx, blub4747

**Comment by WaLLy3K** [comment]
Apologies for the delay @blub4747; are you still experiencing this issue? If so, please let us know!
