### ISSUE TITLE
Some sites very slow to load when accessed via Android

### ISSUE THREAD

**Issue by jackyaz** [pi-hole/pi-hole#1666]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1
---
**[BUG REPORT | OTHER]:**

OTHER

**[BUG | ISSUE] Expected Behaviour:**
Site to load

**[BUG | ISSUE] Actual Behaviour:**
Site never finishes loading.

**[BUG | ISSUE] Steps to reproduce:**
Set Android to use PiHole DNS (via router). Try to access site, e.g. snbforums.com, site takes forever to load. Tailing Log looks OK for reply times, so a bit stumped!

I have checked settings, and tried a suggestion of firewalling port 443 on the PiHole device.

I suspect it's due to PiHole being run in a VM (while I test before purchasing a Pi), but I dont understand why some sites are fine and other's not.

**(Optional) Debug token generated by `pihole -d`:**
`9rp17bqoxr`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jackyaz** [comment]
I also must add that I have firewalled the router so that clients only have access to port 53 UDP/TCP to the PiHole device. Could these be part of the problem?

**Comment by jackyaz** [comment]
I've found if I allow clients to access port 443 this seems to resolve it. Are there any other ports required?

**Comment by Mcat12** [comment]
Did you set port 443 to DROP or REJECT (on the Pi-hole)? The latter is the correct way.

**Comment by jackyaz** [comment]
Force of habit, I was using DROP. So if I REJECT all ports, but ALLOW TCP/UDP 53, will PiHole function as intended? This particular network needs no access to the admin panel.

**Comment by WaLLy3K** [comment]
Correct, REJECT will cause the browser to gracefully reject the connection.

**Comment by jackyaz** [comment]
Brilliant thanks. Knew I was missing something simple. Used to using DROP for WAN facing rules!
