### ISSUE TITLE
The Memory bank is down on my Warp drive.

### ISSUE THREAD

**Issue by smokingwheels** [pi-hole/pi-hole#1668]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[BUG REPORT]:**
My freedns.org subdomain, website or IP is listed on dnsbl.spfbl.net list and I can not unblock my owncloud server even though I whitelisted the domain and my sub domain.
I can access apache ok on http.  My owncloud server uses self signed certs on https.

The reason given is [No Forward-confirmed reverse DNS (FCrDNS)](http://spfbl.net/en/fcrdns/) settings.
Has been working fine for 2 weeks. Pi-hole and my owncloud server.
Recent changes I paid for Google Play App around that time is when it broke the Warp drive.

**[BUG | ISSUE] Expected Behaviour:**

Whitelist domain or subdomain the be able to access any webpages within that domain or subdomain. 

**[BUG | ISSUE] Actual Behaviour:**
http is ok https with self signed certificate is blocked.

**[BUG | ISSUE] Steps to reproduce:**
Install Pi-hole.
Install ownCloud 
Ether one I am not sure but I think it was automated setup with dependences installed.
[Option 1](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)
[Option 2](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-owncloud-on-ubuntu-16-04)
Maybe another site I will have a look in a few weeks when some parts arrive to make a bigger Warp drive.

**(Optional) Debug token generated by `pihole -d`:**
`<762riyhc0j>`
Every thing looks ok in there to me.

**Comment by Mcat12** [comment]
Sorry, somehow we missed this issue. Do you mean it's blocked via the block page or is there a browser error?

**Comment by smokingwheels** [comment]
Some reason my IP is on a list.  My Wifi goes around too far in terms of distance.
I had my yacy search server copied the other day checked with iotop and the disk access lasted the required time to take a copy.
