### ISSUE TITLE
Add bind9/named support to pihole

### ISSUE THREAD

**Issue by basti122303** [pi-hole/pi-hole#1673]
Hello,
i try to port pihole to bind9/named, so far so good. Can someone tell me how pihole read the logfile and where i can change it? bind9/named use an other logformat.

Best regards

**Comment by WaLLy3K** [comment]
[FTL](https://github.com/pi-hole/FTL) parses `/var/log/pihole.log`, which is expected to be in the output that `dnsmasq` provides. I expect that it wouldn't be able to parse the output of a `bind` log, and at this time, we don't wish to move away from `dnsmasq`.

**Comment by nigelhorne** [comment]
You may find this helps:

https://gist.github.com/janus57/c0ffe23c1bfd321512df74dda0dd3d95
