### ISSUE TITLE
DNS split-horizon support

### ISSUE THREAD

**Issue by tehKaiN** [pi-hole/pi-hole#1674]
Hi there,
I'm using pihole on orangepi in my local network. Since I also have some vhosts attached to multiple domains & subdomains, I need to alter hosts file when I'm at home to force domain resolution to local IP, which can be tedious in the long run.

Since pi-hole already translates DNS calls, would it be possible to add some intended configurable domain resolution such as: mydoma.in -> 192.168.0.9? That would really help me.

**Comment by WaLLy3K** [comment]
You can make use of `pihole -a hostrecord`, which makes use of [`dnsmasq`'s host-record option](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html).

Alternatively, you can add your own `dnsmasq` config file into `/etc/dnsmasq.d/filename.conf`

**Comment by tehKaiN** [comment]
Thanks, I'll check it out later. Still, it would be cool to have means to do such thing via web interface or have information how to do it in some place visible since many pi people tend to host their websites on pi.

**Comment by WaLLy3K** [comment]
@DL6ER or @Mcat12, would be the best people to ping regarding having that feature available on the Web Interface :smile:.

I'll leave it to @tehKaiN as to whether you'd like to close the ticket once you've checked it out, as there may be something more you'd like to add to the conversation.

**Comment by dschaper** [comment]
@tehKaiN Do you have any more follow up information for us to review?

**Comment by tehKaiN** [comment]
Sorry for late reply, but my work took over really badly.

I dunno what happened but issue fixed itself - suddenly I can ping my external IP from my LAN without changing any config. I guess my ISP has done something. I guess I'll try the suggested solution next time.

**Comment by WaLLy3K** [comment]
The resolution sounds good! You're totally welcome to hit us up again if you encounter any more issues :smile:
