### ISSUE TITLE
Possible Bug: Pi-Hole Add Blocking Service prevents internet network access

### ISSUE THREAD

**Issue by jennec** [pi-hole/pi-hole#1677]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** 

1

---
**[BUG REPORT | OTHER]:**

PI-Hole is running on a linux Mint 18 workstation.  
Installed without any issues.
Every now and again, no set frequency, internet bandwidth reduces from max (approx 37Mbps down) to nothing.  All clients report internet access is unavailable during this time.  
Internal network devices are contactable by all clients during this time.
Disabling Ad-Blocking in Pi-Hole Admin UI resumes internet access.
Restarting Pi-Hole also resumes internet access.  

**[BUG | ISSUE] Expected Behaviour:**
DNS and Ad Blocking service should not prevent Internet access when running.  

**[BUG | ISSUE] Actual Behaviour:**
Ad-Blocking Service randomly, so it seems, prevents internet access.

**[BUG | ISSUE] Steps to reproduce:**
Unfortunately It is intermittent.  I have not found any steps that can recreate it yet.  It can happen when multiple devices are actively using internet connection or when only one is.    

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

**Comment by dschaper** [comment]
Can you post the token from `pihole -d` and we can take a look at the configuration to see if there is anything that we can spot? Is it possible that the IP address for the Pi-hole is given out to another node on the network causing an IP collision?

**Comment by jennec** [comment]
Hi Dan,

The token code is mogk4ago0k

All IPs above .20 are provided by the DHCP Pool on my router.
pi.hole run on .10 using a static IP.  This is also my Media server which is heavily used everyday, If this went down due to duplicate IP I'd never hear the end of it from my whole family.

**Comment by dschaper** [comment]
Thanks for the token. The debug looks okay and everything looks functional. Can you grab a debug when the Pi-hole becomes an issue and we'll see if there's something else that happens during that time to cause an issue with resolving. The Pi-hole doesn't proxy any traffic, we only handle DNS resolution, so it's rather strange that the full net access is disrupted.

**Comment by WaLLy3K** [comment]
@jennec, are you still experiencing this issue? If so, please run `pihole -d` when you're experiencing this issue, and provide us with the token by replying to this ticket.

In the meantime, I'm closing it due to inactivity.

**Comment by jennec** [comment]
I have stopped using Pi-Hole for now.  Unfortunately I have too many projects on the go to spend time on firefighting my home internet configuration.  So, for now, I have reverted to using my original DNS provider.  

Chris Jenner

**Comment by WaLLy3K** [comment]
Totally understandable, yet I'm sorry to hear that.

Hopefully things go smoother the next time, if you choose to try Pi-hole again :smile:

**Comment by jennec** [comment]
Just an update on this.  After some time and investigation it turns out that Pi-Hole was not the cause of my issues, but the catalyst that highlighted another issue on my home network.  

My router has a Bandwidth Management Feature, which is on by default.  Seems I might have disabled it a while ago whilst playing with QoS.  The Bandwidth management feature, at its very basic settings, ensures that each client gets an appropriate share of the available bandwidth at any one time.  Because I have a very small bandwidth upstream from my router, the amount of DNS requests being requested by a client device (the PiHole machine, plus other services on this client) instead of router itself meant that this client device hogged all the outgoing bandwidth.  Which made it seem to me, at the time, that PiHole could have been the cause when it wasn't.  

I have fixed this issue now and have been using PiHole for a while without any further issues.

**Comment by WaLLy3K** [comment]
It's good to hear that you've been able to resolve this, and lets us know of another use-case to consider when debugging other installations. Thanks for the update, @jennec!
