### ISSUE TITLE
pi bootimages download for popular configs

### ISSUE THREAD

**Issue by no-go** [pi-hole/pi-hole#1679]
Hi.
I get big trouble with different debian (rasbian, minibian) images and some special configs. To avoid from trouble with wifi config fails, dhcp config fails and other installation fails ...

- make a running, minimal pihole image for testers with
- add a web-gui setup (192.168.1.1) on eth0 or cli (first login)
- add a pihole-config file on a FAT32 partition

There are some main network configurations, which are difficult to handle with:

- get internet access via wifi and add dhcp-server on eth0 with pi-hole (routing/bridge)
- adding a ufw or ip-tables firewall
- fast IP address changes for pihole/config
- LAN or WLAN only (still working)

---
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:** _3_

**Comment by no-go** [comment]
Summary

please build 2 images for some old/pupular pi's:

- fast config and ready to use image (just a single IP in my network as DNS server)
- fast config and ready to use image (routing between wlan0 and eth0 with iptables and dhcp server)

**Comment by technicalpyro** [comment]
perhaps look into the docker images for this purpose

**Comment by WaLLy3K** [comment]
Pi-hole needs user input when it's first set up, so creating images would be a fair bit of work for something that [Docker](https://hub.docker.com/r/diginc/pi-hole/) seems to resolve nicely.

@no-go, is running Docker a suitable resolution to your issue? :smile:

**Comment by no-go** [comment]
Hi WaLLy3K. Yes, I try the docker workaround and it is a very suitable workaround!

But: It is not very easy to find on the pi-hole.net website :-(

**Comment by WaLLy3K** [comment]
> But: It is not very easy to find on the pi-hole.net website :-(

Thanks, noted!
