### ISSUE TITLE
Incorrect domain in block page

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/pi-hole#1681]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---

See diginc/docker-pi-hole#156

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Leaving this post here for reference: https://github.com/diginc/docker-pi-hole/issues/156#issuecomment-336320598

**Comment by jacobsalmela** [comment]
@WaLLy3K is this resolved in v3.2?

**Comment by WaLLy3K** [comment]
I believe this issue was resolved by using a different method of acquiring the host name via PHP.
