### ISSUE TITLE
0 Queries Blocked

### ISSUE THREAD

**Issue by zeroprime790** [pi-hole/pi-hole#1684]
Hello,

I installed pi-hole on a Raspberry Pi Zero W and mostly it seems to work fine, but the "Queries Blocked Last 24 Hours" counter is always zero.

![7q0jokb](https://user-images.githubusercontent.com/16868447/30201545-d4d33954-9483-11e7-810a-f2a55d403f52.png)

I generated a debug log and the token is: uu813q1dww

**Comment by dxm765** [comment]
How many lists do you have added? Have you tried browsing to a known blocked url? Are all the devices using the Pi-Hole for primary DNS?

**Comment by DL6ER** [comment]
It looks like he has the standard set of lists looking at the number of domains on his blocklists in the attached screenshot.

Do you have pointed your devices to the Pi-hole's IP address such that they use it as DNS server? The graph seems to be very constant so it may be that only local queries like update checks are going to the Pi-hole (and all of them are permitted).

**Comment by zeroprime790** [comment]
Sorry for the late response :( I have set up the router dns to pihole's address so I don't have to set up each device individually. The adblock service work fine. There are no ads shown on my network. Just the counter is not working properly. When I generated the debug log the counter increased a bit but then stopped again.

**Comment by DL6ER** [comment]
> The adblock service work fine. 

Let me check back with the team if anyone has an idea how that can come about.

**Comment by DL6ER** [comment]
May be a strange question but so you have Pi-hole running on more than one device or tried the installation on more than one machine?

**Comment by zeroprime790** [comment]
No, there isn't any other device running pihole in the same network. I generated another debug log: t29ks8ttij

**Comment by WaLLy3K** [comment]
FTL says there's two unique clients, and that appears to be `127.0.0.1` (The Pi) and `192.168.1.1` (presumably the router). Whether the router is configured to provide the Pi-hole's IP to the clients or act as proxy, I don't know.

Could you go to your primary computer and provide the output of: `nslookup doubleclick.net`, please?

**Comment by zeroprime790** [comment]
The router DNS is pointed to 192.169.1.108
![2017-09-14 12_53_31-td-w9980](https://user-images.githubusercontent.com/16868447/30423792-9ca0e626-994c-11e7-8743-e8d02311dd0e.png)

In DHCP the IP 192.168.1.108 is binded the MAC of tthe Pi:
![2017-09-14 12_54_55-td-w9980](https://user-images.githubusercontent.com/16868447/30423791-9e7e7bc0-994c-11e7-850b-1e89f21911b5.png)

The output of the command you asked for:
![2017-09-14 12_59_36-the pirate bay - the galaxy s most resilient bittorrent site](https://user-images.githubusercontent.com/16868447/30423793-9e880082-994c-11e7-9012-fe6f66016926.png)

and the IP of the Pi
![2017-09-14 13_03_20-mremoteng - confcons xml - pi w](https://user-images.githubusercontent.com/16868447/30423960-1ec2c138-994d-11e7-9baa-ff5be01fee97.png)

**Comment by WaLLy3K** [comment]
The Windows PC is directed to the Pi which is good, but it's getting the *correct* IP for `doubleclick.net` despite you using the default blocklists. Odd!

Could you provide the output of `pihole status` please?

**Comment by zeroprime790** [comment]
Ok, this was a waste of time for you guys, I'm really sorry. For whatever reason my router DNS was pointed to 192.168.1.108 but also I had to set up the DHCP server DNS IP.
![2017-09-14 13_08_01-td-w9980](https://user-images.githubusercontent.com/16868447/30424212-e9f0ac30-994d-11e7-8a4e-42bc2b1266c3.png)

**Comment by WaLLy3K** [comment]
Just a heads up that by having a non Pi-hole DNS server as your secondary, some requests will intermittently go through the secondary server even if the Pi-hole is still online.

In any case, good work on finding the issue! If it's all solved now, just go ahead and close the ticket :smile:
