### ISSUE TITLE
Solved: Adchoices

### ISSUE THREAD

**Issue by Henk982** [pi-hole/pi-hole#1685]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Block ad in Android App

**[BUG | ISSUE] Actual Behaviour:**
It shows an ad

**[BUG | ISSUE] Steps to reproduce:**

- Open Huffingtonpost App on Android and you will see Ads. It think they are AdChoices Ads?
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
If you turn off WiFi/cellular, do you still see ads? If so, then the app has offline ads built in and can't be blocked. Otherwise, check Pi-hole's log for any possible ad domains which aren't blocked in the period of time you used the app.

**Comment by Henk982** [comment]
Thank you, that did the trick.

After lots of adding and removing from the blacklist, I found that 

combine.urbanairship.com
device-api.urbanairship.com

Where the problem. Does anybody know what this services are? And can they be added to the defult list so other people are helped.

Thank you.

**Comment by Mcat12** [comment]
We don't have a default list, but you could add it to one of the third party ad lists that default installs are set up with.
