### ISSUE TITLE
Top domains: "." accessed by some weird address

### ISSUE THREAD

**Issue by bumbalaga** [pi-hole/pi-hole#1686]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

0

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour: Pihole displays domain accessed by some address**

**[BUG | ISSUE] Actual Behaviour: . is being accessed by a foreign address**

**[BUG | ISSUE] Steps to reproduce:**

**(Optional) Debug token generated by `pihole -d`:**

v8s33dexol

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Screenshot of the suspicious output:
http://ss.bumbalaga.net/2017-09-08_17-15-58.png

Is there any change to remove it from top domains? Or is there a way to block this particular client from using my DNS server?

**Comment by Mcat12** [comment]
Is that device on your network, and have you exposed port 53 to the internet? If the latter is true, please immediately remove access to port 53 from the internet!

**Comment by bumbalaga** [comment]
That device is not on my network and i have port 53 exposed to the internet, as i use this pi-hole on multiple servers.

**Comment by DL6ER** [comment]
I could write tons of text about why you should use VPN, why it is good to have the traffic between your servers encrypted (the VPN will do this), and why you should never present unprotected services like DNS to the world.

To cut a long story short: Close the port and connect the servers using a VPN connection.

**Comment by bumbalaga** [comment]
This is not the kind of answer i was asking for.

**Comment by DL6ER** [comment]
Please read:

> Open Resolvers pose a significant threat to the global network infrastructure by answering recursive queries for hosts outside of its domain. They are utilized in DNS Amplification attacks and pose a similar threat as those from Smurf attacks commonly seen in the late 1990s.

(see http://openresolverproject.org )

As you might expect, we are seeing this kind of question quite often and I can tell you that the only proper way of dealing with this is setting up a VPN. Even if you apply some dirty tricks like hiding those requests, your server will be a potential security thread and will (sooner or later) be used by an amplification attack. Note that also limiting DNS requests to be only allowed from certain IP addresses (e.g. using a firewall) will not resolve this problem as the source IP of a DNS request can quite easily be spoofed.

**Comment by bumbalaga** [comment]
I get it and all, but i am looking for a way of using my Pi-hole on multiple VPS servers without using VPN service.

**Comment by DL6ER** [comment]
Okay, are the VPS servers all in the same datacenter? Some providers (e.g. DigitalOcean) allow you to use something called "internal network" which will automatically connect your servers w/o the need for the traffic to go over the Internet. You could then block port 53 to the web and only allow communication through the internal networking.

If they are in different data centers (or even worse, different providers) I - unfortunately - have to tell you that you will have to use a VPN solution in order to make your system waterproof.

**Comment by bumbalaga** [comment]
Yeah, different datacenters, different providers.

That's why i did what i did.
