### ISSUE TITLE
Rasbian Stretch static IP issue

### ISSUE THREAD

**Issue by s1awa** [pi-hole/pi-hole#1690]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
2

---
**[BUG | ISSUE] Expected Behaviour:**
related https://github.com/pi-hole/pi-hole/issues/830

Just installed Raspian on an old Raspberry PI 1 Model B+
then installed pihole and set static IP to use RPI as dhcp server later
The static IP is not assigned on reboot

The problem is that networking and dhcpcd are both running by default

After disabling networking
`sudo systemctl disable networking`
the pihole dhcpcd configuration for a static IP finally started working

I reported it on Raspbian issue tracker https://github.com/RPi-Distro/repo/issues/86

Maybe pihole can check if networking and dhcpcd are both enabled and turn off networking when being installed.

**Comment by PromoFaux** [comment]
What version of Raspbian did you flash onto the SD card, before doing the `sudo apt dist-upgrade`?

**Comment by s1awa** [comment]
The latest from the website https://www.raspberrypi.org/downloads/raspbian/

RASPBIAN STRETCH WITH DESKTOP
Image with desktop based on Debian Stretch
Version:September 2017
Release date:2017-09-07
Kernel version:4.9

**Comment by PromoFaux** [comment]
>After installing Rasbian on Raspberry PI 1 Model B+ and updating to the latest Stretch version
`sudo apt dist-upgrade`

So you didn't come from, say, Wheezy? The only reason that makes me think that, is that `dhcpcd` wasn't introduced until Jessie. If you'd done a `dist-upgrade` from Wheezy, it would still have had `networking` enabled.

That said, we should probably check for it. `dhcpcd` has been a bit of a thorn in our side...

**Comment by s1awa** [comment]
It was a fresh install. From the image mentioned above.
`sudo apt-get upgrade`
said there is a new version of stretch2 and I did
`sudo apt dist-upgrade`

**Comment by s1awa** [comment]
**dhcpcd** was updated to the latest version and now also supports ipv6

I hope this fixed it. I have no resources to research further, sorry.

**Comment by andrum99** [comment]
I'm also seeing this. It is not a bug in Pi-Hole, since I have seen it twice without Pi-Hole being installed on the system. The solution is simple- don't use dhcpcd, or at least specify your static up in the /etc/network/interfaces file before you enable dhcpcd. This is enough to have dhcpcd ignore the interface for which there is a static IP defined in /etc/network/interfaces. Not sure if it still works on other interfaces, as I haven't tested it. (I only need eth0).
