### ISSUE TITLE
Rasbian upgrade to Stretch

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1693]
Is (upgrading to) Stretch supported by Pi-Hole? Is there some things that needs to be taken care of before upgrading or known limitations?

Could you add a note/section to the Readme since I think many will start upgrading/installing the latest Rasbian and like to know the limitations - if any.

**Comment by WaLLy3K** [comment]
The only issue I'm aware of is that Stretch will uninstall `netstat`.

This is an issue for those on the `master` branch, as it will cause anything relying on `pihole status` to fail (most notibly causes an issue for the top left of the Admin Console).

You can either run `sudo apt-get install -y net-tools`, or run `pihole checkout core development` - both should resolve the issue.

**Comment by bczapp** [comment]
Hello!
I've got Pi-Hole running on Stretch.

I have noticed the mentioned issue with the status in the admin console even though net-tools are installed.
But unfortunately there is another issue is that I'm unable to add domains to the white liste using the admin console. I can "Add" the Domain but it's never showing up in the list.

I'm running the master branch.

**Comment by WaLLy3K** [comment]
Hey @bczapp, can you double check to make sure that `net-tools` is installed?

* `dpkg -s net-tools | grep Status:`
* `which netstat`

Also, are you accessing your Web Admin via `http://pi.hole`, via your Pi's IP address or via a domain name?

**Comment by bczapp** [comment]
Hi @WaLLy3K 
here are the information regarding netstat:
```
xx@raspberrypi:~ $ dpkg -s net-tools | grep Status:
Status: install ok installed
xx@raspberrypi:~ $ which netstat
/bin/netstat
xx@raspberrypi:~ $
```

I'm using "http://pi.hole/admin/list.php?l=white" to access the admin console.

Regards,
bczapp

**Comment by WaLLy3K** [comment]
I'd recommend you run `pihole -r` to repair your installation, attempt to reproduce both issues and then run `pihole -d` (uploading the debug log, and providing the token to us when it's spat out).

**Comment by bczapp** [comment]
I ran "pihole -r" and choosed repair (also did this before).
Then I accessed the admin console. Status of Pi-Hole was unknown, Clicked on "Enable" and reloaded pi-hole/admin -> Status is unknown again.

Then I tried to add web.de and test.com to the whitelist. Both didn't show up.

Token is 0iw8ywglbc

**Comment by WaLLy3K** [comment]
Give the following a go, and provide the output it gives:

`sudo -u www-data sudo pihole status`

**Comment by bczapp** [comment]
It seems as when user www-data tries to run sudo he has to enter a password.
See below, first command asks for a password second command just works.

```
root@raspberrypi:/home/bc# sudo -u www-data sudo pihole status

Wir gehen davon aus, dass der lokale Systemadministrator Ihnen die
Regeln erklärt hat.  Normalerweise läuft es auf drei Regeln hinaus:

    #1) Respektieren Sie die Privatsphäre anderer.
    #2) Denken Sie nach, bevor Sie tippen.
    #3) Mit großer Macht kommt große Verantwortung.

[sudo] Passwort für www-data:

<snip>

root@raspberrypi:/home/bc# sudo -u www-data ping web.de
PING web.de (82.165.230.17) 56(84) bytes of data.
64 bytes from bap.web.de (82.165.230.17): icmp_seq=1 ttl=249 time=12.8 ms
```

**Comment by WaLLy3K** [comment]
That's starting to make more sense, thankfully! :smile:

The following should hopefully resolve both issues:
```
sudo rm -f /etc/sudoers.d/pihole
sudo cp /etc/.pihole/advanced/pihole.sudo /etc/sudoers.d/pihole
echo "www-data ALL=NOPASSWD: /usr/local/bin/pihole" | sudo tee -a /etc/sudoers.d/pihole
```

**Comment by bczapp** [comment]
Hello @WaLLy3K 

thanks for your help.
It's working now. (Both status and admin console)

Finally it was an issue with the sudoers configuration.

Regards,
bczapp

**Comment by WaLLy3K** [comment]
Closing issue as O.P's question has been answered. [This PR](https://github.com/pi-hole/pi-hole/pull/1676) will fix the known issue with Debian Stretch.
