### ISSUE TITLE
DNSCrypt support

### ISSUE THREAD

**Issue by ajp2k13** [pi-hole/pi-hole#170]
Support for DNSCrypt and/or DNSSec in Pi-Hole would add some extra security and prevent snooping or MITM attacks.

Maybe some pointers can be found here?
http://www.snbforums.com/threads/dnscrypt-from-opendns.11645/
##

**Comment by extremeshok** [comment]
DNSSec causes allot of issues with host-rewrites.

If you want to enable dns sec.

Install bind: apt-get install bind9
/etc/bind/named.cond.options
````
options {
directory "/var/cache/bind";

dnssec-enable yes;
dnssec-validation yes;
dnssec-lookaside auto;

listen-on port 1053 { 127.0.0.1; };
auth-nxdomain no;    # conform to RFC1035
forwarders {
 		//Google
		//8.8.8.8
		//8.8.4.4
};
}
````

change dnsmasq.conf to enable bind as the upstream
````
server=127.0.0.1#1053
````

service bind9 restart
service dnsmasq restart

and there you go.

U can see bind9 working with dnssec via tail-f /var/log/syslog


##note:
dnssec-validation yes; is very slow, think 10sec per domain

**Comment by dschaper** [comment]
From what I remember of the conversation before the issue was created, we were talking more about DNSCrypt, just for protection from ISP hijacking and redirecting to internals.

**Comment by ajp2k13** [comment]
Maybe this can help later on...
https://github.com/simonclausen/dnscrypt-autoinstall

**Comment by dschaper** [comment]
Thanks for the pointer, we'll take a look at it and see what we can do with the integration. We're focused right now on getting the existing features to be rock-solid, and then we'll take a look at adding in some more features. We have a lot planned to make the Pi-hole even better!

**Comment by ajp2k13** [comment]
@dschaper No rush, I just wanted to post the link here so I don't forget it. :)

**Comment by ajp2k13** [comment]
Another guide for future reference...
http://rpinow.tumblr.com/post/118887639037/dnscrypt-on-osmc

**Comment by ajp2k13** [comment]
I followed the above guide (http://rpinow.tumblr.com/post/118887639037/dnscrypt-on-osmc) on a VM with Ubuntu 15.10 and it worked very well, going to try it on my Pihole next when I get the time.

**Comment by dschaper** [comment]
Looks like a good guide, I see they get around the `resolv.conf` issue with the sticky bit immutable fix, there has to be a better way to get things to work. I do like the systemD service files they've added... And just re-reading the thread, yes DNSSec does add some overhead, as the query has to traverse the chain of trust back to the root, but I think 10 seconds is a bit much, maybe BIND has some issues, I haven't seen that kind of latency with Unbound / NSD. 

Thanks for the links, they are great information.

**Comment by ajp2k13** [comment]
@dschaper I installed it on my Pihole yesterday and it works fine with a few modifications. I don't notice much delay when using a resolver with DNSSec enabled. The immutable fix was used in several articles I looked at probably because it's quick and effective (but dirty), there are other ways though. I'm not a Linux pro so I tried keeping it simple. :)
I had to bind it to 127.0.0.1:40 and I added the -E switch to dnscrypt-proxy. Maybe it's something to put on the Wiki for now until it's ready to be included in Pihole? I could write something up although I don't understand everything I did but almost... :)

**Comment by dschaper** [comment]
Write it up if you'd like and I'll take a look and see if it's okay. There are some port changes that need to happen and such...

**Comment by ajp2k13** [comment]
I'll see what I can do, it's almost the same as the OSMC-guide above. Then someone with more Linux experience like yourself can check if it looks ok, maybe we can improve it over time too.

**Comment by dschaper** [comment]
Sounds good!

**Comment by ajp2k13** [comment]
@dschaper I've started on an entry in the Wiki if you want to check for errors. Sorry about the sloppy layout, not used to wikis.

**Comment by dschaper** [comment]
http://www.cambus.net/dnssec-validation-at-the-router-level-with-openwrt/

**Comment by jacobsalmela** [comment]
Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/dnscrypt-and-or-dnssec-support/549) so this feature is votable.
