### ISSUE TITLE
NO INTERNET AT ALL

### ISSUE THREAD

**Issue by madjapahit** [pi-hole/pi-hole#1709]
in basic term way, there is no internet in my pi.

1. i can ping to my gateway (192.168.1.1)
2. but cannot ping to 8.8.8.8
3. all settings are default, no modifications at all, A NEW FRESH installation.
4. it happens after installing pi-hole.
5. because there is no internet, i am not able to upload (pihole -d) output to tricorder server.
6. i know basic things about linux, like configuring network, know differences between UDP and TCP, others others, etc.

please see my debug log and others command would help.

https://pastebin.com/qa71paGQ

**Comment by Mcat12** [comment]
Did you find a solution?

**Comment by madjapahit** [comment]
yup sorry, after reformatting and reinstalling pi, also the pi-hole, suddenly it went well.

~_~"
