### ISSUE TITLE
Dont mess lighttpd main config fiel

### ISSUE THREAD

**Issue by fda77** [pi-hole/pi-hole#1711]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_4_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Use a file inside /etc/lighttpd/conf-available/ and enable ist

**[BUG | ISSUE] Actual Behaviour:**
Alters /etc/lighttpd/lighttpd.conf

**[BUG | ISSUE] Steps to reproduce:**
install pi-hole and enable webinterface
-

I'm using lighttpd for websites and so its not okay to change the main ligttpd.conf. Instead adding a special file should be used. 
Or at least show a warning before altering the file
Even better: let choose which ip/net-device should be used (i'm using eth0:1 with additional ip for pi-hole only)

-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Please see the below pull request and corresponding issue.

https://github.com/pi-hole/pi-hole/pull/704

https://github.com/pi-hole/pi-hole/issues/751

Please also note that any existing `lighttpd.conf` will be backed up before creating the one for Pi-hole, and should be located under `/etc/lighttpd/lighttpd.conf.orig`

**Comment by WaLLy3K** [comment]
> I'm using lighttpd for websites and so its not okay to change the main ligttpd.conf. Instead adding a special file should be used.
Or at least show a warning before altering the file

We already have a giant warning within [lighttpd.conf](https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L12) that explains how you can make your own changes:

```
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPERATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################
```

> Even better: let choose which ip/net-device should be used (i'm using eth0:1 with additional ip for pi-hole only)

What has this got to do with the `lighttpd` config?

**Comment by dschaper** [comment]
Close for age.
