### ISSUE TITLE
Pi-hole not blocking ads

### ISSUE THREAD

**Issue by rhainds** [pi-hole/pi-hole#1727]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1
---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Pi hole should block ads

**[BUG | ISSUE] Actual Behaviour:**
pi-hole does not block ads

**[BUG | ISSUE] Steps to reproduce:**

-My pi-hole was working before my ISP changed their router to fix a technical problem i had. 
-I have tried many things while reading closed issues including a fresh start for my rpi1B+
-Now, I see ads everywhere and it shows no blocked queries but the ones done with "pihole -d" and nslookup doubleclick.net
-

**(Optional) Debug token generated by `pihole -d`:**

`<k612wkwy49>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by rhainds** [comment]
![spectacle kn84941](https://user-images.githubusercontent.com/16804191/31303330-900e0d32-aad9-11e7-9423-81ae43ecf858.png)

**Comment by rhainds** [comment]
![spectacle kn84941](https://user-images.githubusercontent.com/16804191/31303344-eb8a59ea-aad9-11e7-84c8-c691233877c4.png)

**Comment by rhainds** [comment]
![image](https://user-images.githubusercontent.com/16804191/31303377-95f36c28-aada-11e7-8731-2e7d5917a5bd.png)

**Comment by rhainds** [comment]
my router
![image](https://user-images.githubusercontent.com/16804191/31303401-c47b899a-aada-11e7-91c0-dff1bb7b47f7.png)

**Comment by rhainds** [comment]
my router dns
![spectacle kn84941](https://user-images.githubusercontent.com/16804191/31303344-eb8a59ea-aad9-11e7-84c8-c691233877c4.png)

**Comment by rhainds** [comment]
my router dns
![image](https://user-images.githubusercontent.com/16804191/31303459-f6a9c0d4-aadb-11e7-8a33-ae96a8aaa458.png)

**Comment by rhainds** [comment]
pi@pi-hole:~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:b4:40:88  
          inet addr:192.168.2.134  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::e1e0:81c7:1eb6:d24f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:109965 errors:0 dropped:308 overruns:0 frame:0
          TX packets:38888 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:58427559 (55.7 MiB)  TX bytes:11644503 (11.1 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:93895 errors:0 dropped:0 overruns:0 frame:0
          TX packets:93895 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:6404073 (6.1 MiB)  TX bytes:6404073 (6.1 MiB)

**Comment by Mcat12** [comment]
What DNS settings do your devices have?

**Comment by rhainds** [comment]
Auto.

**Comment by Mcat12** [comment]
What DNS servers are they using then? Check `ipconfig /all` on Windows devices

**Comment by rhainds** [comment]
dns server .   .   .   .   192.168.2.1 (my router)

**Comment by Mcat12** [comment]
What does the right hand side of the first router screenshot say?

**Comment by rhainds** [comment]
always give internet access to the device

**Comment by Mcat12** [comment]
Check for a setting on the router to disable dnsmasq, DNS rebinding protection, or local forwarding. The router should hand out the DNS servers you give it but may not because of one of DNS rebinding or might be incorrectly forwarding.

**Comment by rhainds** [comment]
Do you see a lead here...
![image](https://user-images.githubusercontent.com/16804191/31303687-e3038d68-aadf-11e7-9520-8c66b8ac3d4f.png)
I checked all options and nothing. My router firmware is ISP customized. I would prefer dd-wrt

**Comment by rhainds** [comment]
i found something in the log of my router

ERR | DNS | DNS name resolution failure (teredo.ipv6.microsoft.com)

ERR | DNS | DNS name resolution failure (WORKGROUP)

ERR | DNS | DNS name resolution failure (server)
this type of error occurred over 10 times today, with different or same input in the ()

**Comment by Mcat12** [comment]
Are the LAN DNS settings under DHCP or Modem->DNS? If you can't find anything, then try disabling DHCP on the router and enable it on the Pi-hole.

**Comment by rhainds** [comment]
I did it and now, it seams to work. I have many devices so I need to do more tests. The result is not the same as my first attempt with pi-hole. Now I see "Failed connection" square instead of white square for my first pi-hole. It doesn't bother me but is it normal? Plus, it looks like it does not block as many ads. Still, a great improve. Thank you for your time.

**Comment by Mcat12** [comment]
What do you mean you see a failed connection square?

**Comment by rhainds** [comment]
![image](https://user-images.githubusercontent.com/16804191/31313957-b865157c-abc0-11e7-8507-4aec74e1674a.png)
"La connexion a échoué" translates to "failed connection"

**Comment by rhainds** [comment]
but right now my % of queries blocked looks good, around 10-15%, and I see very few ads. Thank you very much for your help.

**Comment by Mcat12** [comment]
The failed connection means that it tried accessing an ad over https. Because Pi-hole redirected the request to itself and does not have the certificates for that domain, it is a failed connection. On http it would succeed and Pi-hole would return an empty response.
