### ISSUE TITLE
Unable to block some wildcard domains

### ISSUE THREAD

**Issue by tambnguyen** [pi-hole/pi-hole#1731]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Domains in wildcard list are blocked

**[BUG | ISSUE] Actual Behaviour:**
They are not blocked

**[BUG | ISSUE] Steps to reproduce:**
Try adding the following domains to your wildcard (or not) blacklist, and visit those sites using any browser. 
```
address=/vrfuckdolls.com/0.0.0.0
address=/mmofreegames.online/0.0.0.0
address=/dmm.com/0.0.0.0
address=/wellhello.com/0.0.0.0
address=/tryst4sex.com/0.0.0.0
address=/18schoolgirlz.com/0.0.0.0
address=/18yoga.com/0.0.0.0
address=/scream18.com/0.0.0.0
address=/vrsumo.com/0.0.0.0
address=/badoinkhd.com/0.0.0.0
address=/pornicle.com/0.0.0.0
address=/mmoframes.com/0.0.0.0
address=/bang.com/0.0.0.0
address=/installporn.com/0.0.0.0
address=/badoinkvr.com/0.0.0.0
address=/vrcosplayx.com/0.0.0.0
address=/freemmo2017.com/0.0.0.0
```

**(Optional) Debug token generated by `pihole -d`:**

`vl5dnshgbn`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
You added only IPv4 addresses to your wildcard configuration. Are you sure that you don't have IPv6 connectivity?

Please verify this on http://ipv6-test.com

**Comment by dschaper** [comment]
Was this a fresh install of Raspbian Stretch or an upgrade of Jessie to Stretch?

**Comment by tambnguyen** [comment]
@DL6ER How do I add IPv6 wildcard?

@dschaper fresh install of Stretch.

**Comment by DL6ER** [comment]
The easiest would be to use the dedicated way of doing it with Pi-hole's shell command:

```bash
sudo pihole -wild abc.de def.com ghi.us
```

You can also use the web interface.

If you insist in doing it by hand you can do it just as you did it for IPv4, just add a second line for each entry with an IPv6 address of your choice.

**Comment by tambnguyen** [comment]
@DL6ER I did use the web UI to add those domains; I simply copied those lines from the configs because there was no way I could've done it on the UI.
![screen shot 2017-10-10 at 3 24 03 pm](https://user-images.githubusercontent.com/7453021/31406371-1b81c65e-adcf-11e7-976a-37a08238429c.png)

**Comment by dschaper** [comment]
On the Pi-hole device try the following commands and let see what they return.

     dig +short 18yoga.com A
     dig +short 18yoga.com AAAA

**Comment by tambnguyen** [comment]
```
pi@pi3:~ $ dig +short 18yoga.com A
0.0.0.0
pi@pi3:~ $  dig +short 18yoga.com AAAA
pi@pi3:~ $
```

**Comment by dschaper** [comment]
The Pi-hole is responding to the domain requests as should be. I'm checking one other potential issue right now but you are able to browse to that site on a client browser still?

**Comment by tambnguyen** [comment]
@dschaper Yessuh, I am. Not only that, I also get the same results when I do an `nslookup` on my Windows machine. It only borkes (meaning DNS returns a valid result) when I'm in a browser.

**Comment by dschaper** [comment]
Are you using Chrome as your browser?

**Comment by tambnguyen** [comment]
Yes, Chrome is my main browser. I've tried clearing Chrome's internal DNS cache, my computer's DNS cache, rebooting both my rig and my RPi. No dice.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/why-do-i-see-ads-in-chome-but-not-other-browsers/3284

**Comment by dschaper** [comment]
If you can check another browser and see if you get the site allowed through then it points to `quic` on Chrome being the issue.

**Comment by tambnguyen** [comment]
Sure, but that doesn't explain why it fails on IE, Edge, and FF.

**Comment by dschaper** [comment]
Did the IPV6 test site return back that you had a public IPv6 address?

**Comment by tambnguyen** [comment]
It says "Not Supported" in red.

**Comment by dschaper** [comment]
Okay, next thing would be to check Windows `ipconfig` and make sure that only the Pi-hole is listed as the DNS server and that there are no other secondary servers that may be allowing the lookups to go through.

**Comment by tambnguyen** [comment]
```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : [REDACTED]
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter PIA:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : TAP-Windows Adapter V9
   Physical Address. . . . . . . . . : [REDACTED]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::4f4:e87f:6ad0:2ffb%5(Preferred) 
   IPv4 Address. . . . . . . . . . . : [REDACTED](Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.252
   Lease Obtained. . . . . . . . . . : Tuesday, October 10, 2017 4:06:15 PM
   Lease Expires . . . . . . . . . . : Wednesday, October 10, 2018 4:06:15 PM
   Default Gateway . . . . . . . . . : 
   DHCP Server . . . . . . . . . . . : 10.47.10.5
   DHCPv6 IAID . . . . . . . . . . . : 50397003
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-F6-1F-18-00-1F-BC-02-5C-0A
   DNS Servers . . . . . . . . . . . : 192.168.1.12
                                       192.168.1.1
                                       209.222.18.222
                                       209.222.18.218
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   Physical Address. . . . . . . . . : [REDACTED]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Realtek PCIe GBE Family Controller #2
   Physical Address. . . . . . . . . : [REDACTED]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::3121:6620:d20c:e020%11(Preferred) 
   IPv4 Address. . . . . . . . . . . : 192.168.1.2(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Tuesday, October 10, 2017 3:56:46 PM
   Lease Expires . . . . . . . . . . : Wednesday, October 11, 2017 3:56:46 PM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 251666364
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-F6-1F-18-00-1F-BC-02-5C-0A
   DNS Servers . . . . . . . . . . . : 192.168.1.12
                                       192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```

**Comment by dschaper** [comment]
That Windows box has multiple DNS servers and any of those servers will respond to queries. Windows does not follow a primary/secondary DNS process and will send queries out to all listed DNS servers.

**Comment by tambnguyen** [comment]
@dschaper oh my god thank you very much! It WAS the multiple DNS server issue. 

I forgot to mention, I use a VPN, and they push DNS settings to me. Once I disable that in the config, those sites no longer load.

This one line (or lack thereof) has been the issue all along:

```
pull-filter ignore "dhcp-option DNS"
```

Thank you!
