### ISSUE TITLE
iPhone 8 on T-Mobile: apps aren't working properly

### ISSUE THREAD

**Issue by tambnguyen** [pi-hole/pi-hole#1732]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
User is able to visit websites that are loaded within embedded browser from within apps

**[BUG | ISSUE] Actual Behaviour:**
Embedded browser is unable to load sites. The same websites can be loaded by using normal Safari.

**[BUG | ISSUE] Steps to reproduce:**
Set up info:
- iPhone 8 Plus, iOS 11.0.2
- I use a VPN to access my Pi, split tunneling all local traffic, and using Pi as DNS server (see attachment)
- Use any app that has an embedded browser (Yelp, Slack, PagerDuty, etc)
- Make sure to get off the Wifi. You may need to reconnect to VPN after that.
- Some apps don't have access to internet (Yelp, Slack etc.)
[vpn.txt](https://github.com/pi-hole/pi-hole/files/1373067/vpn.txt)

**(Optional) Debug token generated by `pihole -d`:**

`yueipqylrn`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by shanghaix** [comment]
Split Tunneling is not supported on iOS, could be the source of your problem.

**Comment by tambnguyen** [comment]
I can't be, as most of my other apps work perfectly :(

**Comment by tambnguyen** [comment]
Problem solved. See https://github.com/pi-hole/pi-hole/issues/1731
