### ISSUE TITLE
Backlisted domains still accessible

### ISSUE THREAD

**Issue by qyqsoft** [pi-hole/pi-hole#1736]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate

**How familiar are you with the codebase?:**
1
---
**[BUG | ISSUE] Actual Behaviour:**

I have two domains in my blacklist (soinhive.com and coin-hive.com). When I enter coinhive.com in my Browser, coinhive.com still opens with the adress https://coinhive.com. It seems that the blacklist dosnt work. I already cleaned my DNS cache and tried it on different machines but always the same.

**[BUG | ISSUE] Steps to reproduce:**
- pihole -b coinhive.com
- flush DNS cache 
- enter coinhive.com in browser (mine is Firefox)
- site opens with https://coinhive.com

**Comment by WaLLy3K** [comment]
That's odd! Could you answer a few questions to help me better understand what's happening please?

* What O.S. are you running?
* What does your O.S. believe the DNS servers are? (e.g: Windows: `ipconfig /all`, Mac: [System Prefs](https://fthmb.tqn.com/70g7hVDbCSzoUTG3ZJFNZagwgPo=/768x0/filters:no_upscale()/ChangeDNS-579e68143df78c3276990153.jpg))
* What is the result of `nslookup coinhive.com` from an affected computer?
* What is the result of `nslookup coinhive.com` from your Pi-hole?

Thanks!

**Comment by qyqsoft** [comment]
I found the error. My ipfire hardware firewall which is the DHCP server in my LAN used a DNS server witch did not show up in the Webinterface. After I altered some DHCP and DNS config files it runs at it should be. Sry, was my mistake.
