### ISSUE TITLE
[Feature Request] Add block list name column in Query Log etc.

### ISSUE THREAD

**Issue by NoX1De** [pi-hole/pi-hole#1738]
I realize this will be prioritized below bug fixes etc. but it would be really nice to be able to tell which block list is blocking a query in the query log in the web interface.  This is especially true for someone who's added a lot of other block lists in addition to the default pi-hole block lists.  I believe it would be best to first add the ability to give custom "common" names to each block list URL in pi-hole settings under "Pi-Hole's Block Lists", those "common" names of each block list you can manually define would then be pulled into the Query Log as a new column for easy reference of which block list is creating issues or blocking things that, for instance, you would not suspect it should be blocking.

Perhaps by default the filename at the end of the block list URL such as "examplelist.txt" would be what the common name is set to minus the file extension (e.g. "examplelist") however you could then change it manually to what you desire to call it which would then appear in the Query Log as a new column.

[Update] After thinking about this a bit further I believe this would require more effort or might not be "doable" without some changes unlike I had originally thought.  Since all the ad/block lists are aggregated and de-duped we would have to probably create some type of lookup table/database prior to list aggregation and de-duplication for the Query Log in the web GUI to reference.  Additionally since there could be lists that have the same domains in them the feature would have to support multiple columns in the query log for all the lists that had the domain within them prior to aggregation and de-duplication....just more thoughts, curious to hear back on feasibility.

Thank you!

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please submit [your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community. It's also easier for us to track.

**Comment by WaLLy3K** [comment]
This is somewhat implemented in the command line interface via `pihole -q -adlist domain.com`, which is available in the `development` branch.

As for having it in the Web Interface, I'd definitely recommend submitting a feature request at our forums.

**Comment by jacobsalmela** [comment]
Added this as a votable feature request:

https://discourse.pi-hole.net/t/add-block-list-name-column-in-query-log/5813
