### ISSUE TITLE
Feature Request query log search by client

### ISSUE THREAD

**Issue by ndrone** [pi-hole/pi-hole#1739]
I would like to search through the query log table from the website by the client column.

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Please read the issue template that you have clearly ignored ;)

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**Comment by PromoFaux** [comment]
That said, I believe this is already possible, if not in the master version then it is definitely in the next release:
![clientsearch](https://user-images.githubusercontent.com/1998970/31585018-d9affe44-b1b1-11e7-97e6-fbbc2a990db1.gif)

**Comment by PromoFaux** [comment]
Just checked the master release, and you can already do this :)

![clientsearchmater](https://user-images.githubusercontent.com/1998970/31585048-55cb032a-b1b2-11e7-8434-9290fbf41e54.gif)

**Comment by ndrone** [comment]
doesn't work by ip address.

**Comment by DL6ER** [comment]
We think host names are more valuable than IP addresses when they are available. For the same of simplicity, the API returns *either* the host name *or* the IP address where the former is preferred.

**Comment by ndrone** [comment]
Of course hosts name are more valuable and meaningful about the device on the network. But that is not the way they are logged on my network, They are by IP addresses and the search functionality shouldn't really care if it is by IP address or hostname.

**Comment by PromoFaux** [comment]
Do you mean like this? Because this is from the master branch:

![clientsearchip](https://user-images.githubusercontent.com/1998970/31588644-ffeaf6be-b1ec-11e7-87dd-debc36cbf487.gif)
