### ISSUE TITLE
Getting multiple IPv6 adresses

### ISSUE THREAD

**Issue by DreiPixel** [pi-hole/pi-hole#1741]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT | OTHER]:**

well i noticed that i have multiple ipv6 adresses and appearently i have 2 DNS server's (ipv6, ipv4 only shows 1) in my netword but DHCP on my router is deactivated and im using the Pihole's dhcp.
The main issue that this creates that some sites taking a good while to load. A temporary fix is deactivating IPv6 on my PC but i cant do that with my phone and some other systems.
The router i have should be correctly configurated. it's a Speedport Hybrid from telekom.
i have a Raspberry pi 3 running raspbian. the server is headless.

**[ISSUE] Expected Behaviour:**
having 1 ipv6 DNS server and sites loading faster with activated ipv6

**[ISSUE] Actual Behaviour:**
having 2 ipv6 dns servers and some sites loading slow

**[BUG | ISSUE] Steps to reproduce:**
- setup a Pihole and having a speedport hybrid.
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`7swquuoo4d`

**Comment by dschaper** [comment]
The Pi-hole device does show multiple Globally Unique IPv6 addresses. Is the Pi-hole device set to receive it's IPv6 address statically or is it getting these from a DHCP server? And can you check via `ip -6 addr` on the Pi and see if they are all shown with valid lifetimes? We can check that if you run `ip -6 addr | pihole tricorder` and get us the token from that. (The secure upload process is detailed here: https://discourse.pi-hole.net/t/how-can-i-send-the-pi-hole-devs-information-securely-if-i-need-help/3104)

**Comment by DreiPixel** [comment]
djvcxkz65u
here's the token running ip -6 addr.
when i setup the pi i only made the ipv4 address static because i thought that was it. the pihole setup also only asked if i wanted the current ipv4 address static.

**Comment by dschaper** [comment]
The addresses are dynamic, so that would point to another DHCP server on the network that is providing leases for IPv6 to clients. Do you have a separate router and access point or is the ISP device a combined device?

**Comment by DreiPixel** [comment]
I have a access point for all my wlan devices but (a fritz box) but that is setup that it uses the pihole dhcp.
and on my router all i can do to deactivate dhcp is just a button that is either on or off.

**Comment by DreiPixel** [comment]
Ok found the problem and its somewhat hard to fix.

despite deactivating dhcp on the routers config the ipv6 dhcp stays active no matter what.
but there is a way to decrypt the backup config file and deactivating it that way.

closing this now

speedport routers are shit.

**Comment by mibere** [comment]
@DreiPixel, I'm a Pi-hole and Speedport user too, can you please share the info how to deactivate the IPv6 DHCP? See my [posting ](https://discourse.pi-hole.net/t/can-visit-a-blocked-and-blacklisted-domain/4907/6)in the board.

**Comment by DreiPixel** [comment]
@mibere do you have a Speedport hybrid? Because this only works for the hybrid. Because for a internet normal connection you can just use another router that is more open to configure.

**Comment by mibere** [comment]
@DreiPixel, yes, have a Speedport Hybrid (with EntertainTV and Media-Receiver).
Maybe you can post an info or how-to in Discourse.
