### ISSUE TITLE
FireFox gives java script not responding on old PC. no rush

### ISSUE THREAD

**Issue by smokingwheels** [pi-hole/pi-hole#1745]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[BUG REPORT]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

When Watching movies this has happed.

Script: http://myippihole/admin/scripts/vendor/app.min.js:13
Script: http://myippihole/admin/scripts/vendor/jquery.min.js:2
Script: http://myippihole/admin/scripts/vendor/jquery.min.js:3

Could be Bandwidth issue.
I have over 1 million in the Raspberry Pi
[Have pic](https://twitter.com/smokingwheels/status/921419294495277057)

**Comment by Mcat12** [comment]
What page of the web interface does this happen on?

**Comment by smokingwheels** [comment]
I had a tab open for Pi-Hole and I was watching a full screen movie in another it happened several times and I had to come back off full screen and it was ok.
I only was using the first 2 block lists.
Its a ~12 year old PC with some Nvida card running Ubuntu 16.04.

1. [https://smokingwheels.github.io/Pi-hole/allhosts](https://smokingwheels.github.io/Pi-hole/allhosts)

2. [https://smokingwheels.github.io/Pi-hole/searchengine](https://smokingwheels.github.io/Pi-hole/searchengine)

3. [https://smokingwheels.github.io/Pi-hole/yacysearchengine](https://smokingwheels.github.io/Pi-hole/yacysearchengine)

**Comment by Mcat12** [comment]
What screen was the web interface on?

**Comment by smokingwheels** [comment]
Just the Dashboard logged in also I have noticed the Graph lines (Queries over last 24 hours) bend back over drawing lines in previous history. Have screen dump.
[https://twitter.com/smokingwheels/status/922815895658889216](https://twitter.com/smokingwheels/status/922815895658889216)

**Comment by Mcat12** [comment]
If you checkout the development version (using `pihole checkout dev`) does this still happen?

**Comment by smokingwheels** [comment]
I will check it out.

**Comment by smokingwheels** [comment]
Your debug token is: quirb97g69  (using pihole checkout dev)
I have a few errors on my lists I will have to fix.
The FTL showed red and but seems to be working ok.

**Comment by Mcat12** [comment]
What is the output of these commands?
```
pidof pihole-FTL
sudo -u www-data pidof pihole-FTL
```

**Comment by smokingwheels** [comment]
pidof pihole-FTL
679
sudo -u www-data pidof pihole-FTL
679
I have only just updated to dev.

**Comment by smokingwheels** [comment]
I had it I think its when Firefox on Ubuntu overloads and consumes lots of memory when it darkens its self.

**Comment by smokingwheels** [comment]
I had it I think its when Firefox on Ubuntu overloads and consumes lots of memory when it darkens its self.
