### ISSUE TITLE
Non-standard port numbers are not displayed correctly in the web

### ISSUE THREAD

**Issue by liwanglin12** [pi-hole/pi-hole#1748]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
_1_

for example, set upstream 127.0.0.1#12053
And it will display as 127.0.0.112

![snipaste20171024_204014](https://user-images.githubusercontent.com/10279535/31943508-8f020b34-b8fb-11e7-8c18-a95895173d72.png)

If click saves, the upstream will change to `127.0.0.112` truly, so that I can't save any settings now.

**Comment by Mcat12** [comment]
If you have to change the port from the default, I think for now it is fair to say you should do that kind of advanced configuration change manually in the config files (`setupVars.conf` and/or the respective dnsmasq file).

**Comment by liwanglin12** [comment]
I modify it in setupVars, but this issue cause me can't change settings in web admin because if I save setting, system will use the wrong ADDRESS (127.0.0.112)...

**Comment by Mcat12** [comment]
Fixed in https://github.com/pi-hole/AdminLTE/pull/742
