### ISSUE TITLE
Install DNScrypt by default or make it a one-click install

### ISSUE THREAD

**Issue by COLABORATI** [pi-hole/pi-hole#1753]
Please add dnscrypt-proxy by default - if not by default, then at least it should be installable with one click from the web interface or as an option fromk the install script. This would really lower the entry for many people to have secure dns - something that is needed nowadays very much.

**Comment by DL6ER** [comment]
This is not an issue report. From the template (which you ignored):

> Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.
