### ISSUE TITLE
Admin page not displaying correcting

### ISSUE THREAD

**Issue by billyjthorton** [pi-hole/pi-hole#1754]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Upon recently (as of today 11/3) installing a fresh version of pi-hole on a Raspberry Pi, there seemed to be an error with the admin page. While it correctly installs and I was was able to get the service running, the admin page displays as a PHP file whenever I visit the web addresses: http://192.168.1.x/admin/index.php or http://pi.hole/admin. The webpage that gets displayed is attached.
[pihole.txt](https://github.com/pi-hole/pi-hole/files/1440094/pihole.txt)

**Comment by Mcat12** [comment]
I added the issue template back to your post (please fill it out, and make sure to get a debug token).

Have you installed any other packages, such as apache or nginx?

**Comment by billyjthorton** [comment]
I apologize for that. I should have attached that from the beginning. My debug token is: 9gjid7vcsb 

I would have a better debug token to upload, but when I assigned the pihole to serve as the network DNS server, it wouldn't upload due to connection issues. So in addition to the webpage issue, I'm also having issues with the connection. That is the DNS server is also not working - I don't know if it will be possible to debug it with the log file that you have. I can manually upload one later if need be.

**Comment by Mcat12** [comment]
Remove nginx, because that appears to have taken over port 80. Also, you can upload the log (at `/var/log/pihole_debug.log`) via another pastebin service

**Comment by billyjthorton** [comment]
Okay, I believe I removed it. However, that didn't seem to fix it. The updated debug token is 17c818en60

And for an another debug log, check out: https://pastebin.com/FTrAXWnf . In this one, I made the ip of the device running pihole the DNS server of the network. So it has the failed networking aspect as well.

**Comment by Mcat12** [comment]
Have you started lighttpd back up? `sudo service lighttpd start`
It looks like `command` has taken over port 53, but might be proxying requests to dnsmasq. This may be ok, but does look odd.
Are you entering in this IP for the DNS server on the router? 192.168.1.195

**Comment by billyjthorton** [comment]
I restarted lighttpd (updated debug for proof 2e18200zsh), but I'm not sure what would be wrong with my /etc/dnsmasq.d/SoftAp0 ? 

This actually goes back to an installation issue I had earlier I posted on the github about: https://github.com/pi-hole/pi-hole/issues/1521 

For some reason, there has been some issues with the dnsmasq.d with fresh installs. Following the instructions by @dschaper and @WaLLy3K I was able to at least get the dns server up and running. However, I am still having issues getting it working. I'm sure I'm entering the IP for the DNS server on the router correctly, but it still doesn't seem to serve requests correctly. Any ideas on how to fix it?

**Comment by Mcat12** [comment]
The settings in SoftAp0 are probably conflicting with the settings in other dnsmasq files. Speaking of #1521, were you planning on replying to it? You should fix that issue first, because that is probably causing or at least contributing to some of these issues.

The reason you are seeing the PHP source is because you have installed apache (just like nginx, please remove it or move it to another port):
```
---= Daemon Process Information

Found user www-data with process apache2
```

**Comment by billyjthorton** [comment]
What settings are conflicting? I'm not sure I understand?

Since no one had originally gotten back to me on #1521 I decided that something was wrong with my installation and perhaps a fresh install might be best. But I've had the same issues with that issue as this one. I think it is a repeatable bug. As I mentioned above, I followed the ideas/instructions provided, but they didn't help solve the issues I'm having.

So do you want me to make sure both nginx and apache are removed?

**Comment by Mcat12** [comment]
Yes, remove both of those web servers. Did you remove the repeated `cache-size` setting? Run `pihole -d` for a new debug token.

**Comment by billyjthorton** [comment]
You were correct - removing both nginx and apache was causing a conflict that was able to make the admin page display correctly. At least that part is solved :)

New debug token: 95s1fisiea

Now this one, I was sure the service was up and running (with the cache-size removed as suggested), but there still seemed to be something wrong. To help make it easier, I made it the pihole the dns server for just my iphone and tried to browse to some sites (not tried - nothing resolved at all). Let me know if you find something else causing a conflict. I would really like to get it working!

**Comment by Mcat12** [comment]
All of the requests in the log snippet are being redirected to `172.1.8.1` as a result of this line in `SoftAP0`:
```
address=/#/172.1.8.1
```

**Comment by billyjthorton** [comment]
What should that be corrected to? My router?

**Comment by Mcat12** [comment]
Why do you have that line there in the first place? That line will cause all domains which are not blocked and not in your `/etc/hosts` file (or otherwise explicitly set) to resolve to `172.1.8.1`. You can't resolve regular domains because you told dnsmasq to not resolve regular domains.

**Comment by billyjthorton** [comment]
I didn't have anything there originally - that came straight from source. Similar to how the cache-size was causing issues in SoftAP0, similarly this must also be another issue. I wonder if there is a way in the install script that you guys could check for these values?
So that 172.1.8.1 should be like 8.8.8.8 or whatever dns server I'm using?

**Comment by Mcat12** [comment]
Where did you get that config file? That line should not be there, so try removing it and testing again. Since that is not a normal dnsmasq or Pi-hole config, it does not make sense for us to test for it (can't t rest for everything).

**Comment by billyjthorton** [comment]
I'm not really sure. I believe when pihole "apt-gets" for dnsmasq I believe a default config file is loaded. Unfortunately, I'm not familiar enough with the code base to know what would cause that? Would you have any insight (a good learning moment :) ).

I completely understand - you can't test for everything! I just didn't know if this was a common problem or not. I guess your answer to the above question might be an interesting. If it is a problem, I might fork the repo and see if I can't insert some lines of code that will fix these issues in the future!

For now, it's working. But I do have to erase these lines every time there is a reboot. Somehow, this SoftAp0 has taken as the default dnsmasq config. Would you know how to fix that at well? Again, is this stemming from a larger issue?

**Comment by Mcat12** [comment]
It shouldn't have created that config. Try removing it (or moving it out of the config folder) and trying again. This is most likely stemming from a larger issue, because Pi-hole has nothing to do with that file being created. Did you try making your Pi a wireless access point in the past?

**Comment by billyjthorton** [comment]
I figured as much. I can remove the file all I want, but it re-appears on a reboot. The Pi is connected to internet via Ethernet only. I am actually not using a Raspberry Pi, but rather a beaglebone black running debian - which Pihole says it supports and is a more complete package than Raspbian. My guess is that it has to do with the import of dnsmasq? Is that where it normally places a default config?

**Comment by dschaper** [comment]
Are you running Bone Debian or just a straight Debian image? Do you have a link to where you got the image that you downloaded? We had previously tried running Pi-hole on BBB and BBG's and there were issues with the IP stack, and that situation may still be occurring.

**Comment by jacobsalmela** [comment]
This thread drifted back to your original request @billyjthorton so I'm closing it and the discussion can continue in #1521
