### ISSUE TITLE
logging to /etc

### ISSUE THREAD

**Issue by Mausy5043** [pi-hole/pi-hole#1762]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_6_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Logs should be created in `/var/log`  (ref: http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/)

**[BUG | ISSUE] Actual Behaviour:**
Installer creates a log in `/etc/pihole`

**[BUG | ISSUE] Steps to reproduce:**
Install Pi-Hole and inspect output from `ls -al /etc/pihole`
Note the presence of the file `install.log`

If this was done intentionally I'm very curious to understand the reasoning behind that.  
If not, I could help by submitting a pull request to correct this. In the latter case, on which branch would you like me to base the changes?

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
I think this can be linked in with #1699, as we are looking at how we handle that file anyway, we can probably also look at where it ends up, too. Closing for further discussion in the other issue
