### ISSUE TITLE
Getting PiVPN + PiHole running

### ISSUE THREAD

**Issue by jazodnem** [pi-hole/pi-hole#1765]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{6}_

---
**[OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[ISSUE] Expected Behaviour:**
I'm trying to get PiVPN running alongside PiHole using this [tutorial](https://github.com/pi-hole/pi-hole/wiki/OpenVPN-server:-Setup-OpenVPN-server)

`ifconfig tun0 | grep 'inet addr'` should return my `inet addr`

**[ISSUE] Actual Behaviour:**

Nothing comes up when I paste the code above, when running `ifconfig` below is what I get;
```
enxb827ebf57488: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.23  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::371f:5f81:b64e:d61d  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:f5:74:88  txqueuelen 1000  (Ethernet)
        RX packets 116907  bytes 29436582 (28.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 83435  bytes 7980765 (7.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 704  bytes 71312 (69.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 704  bytes 71312 (69.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

How do I know what my `inet addr is`?
I have the Pihole setup to handle DHCP and it's turned off on my router.

**[ISSUE] Steps to reproduce:**

First, get the IP of your tun0 interface:

`ifconfig tun0 | grep 'inet addr'
`
**(Optional) Debug token generated by `pihole -d`:**

`<uwrj0xro21>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Are you using Raspbian Stretch? I think there are some compatibility issues with the openVPN script and stretch, I noticed a similar thing yesterday when setting up something to test.

Did you get any errors or warnings about IPTables?

**Comment by jazodnem** [comment]
@PromoFaux Hi, yeah I am, didn't know there were compatibility issues with Stretch.
Might just wait till I get a second Pi as my current one is setup for Pihole and I don't think it's worth the effort to reinstall everything under Jessie.

**Comment by thewriteway** [comment]
you can check my blog with instructions on slicedpi.net as I have it running with stretch and no problems... :)

**Comment by jacobsalmela** [comment]
@jazodnem what's the status on this?
