### ISSUE TITLE
DNS adres of the server of pi-hole can't be found

### ISSUE THREAD

**Issue by MarkEngel** [pi-hole/pi-hole#1766]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

A working admin web page

**[BUG | ISSUE] Actual Behaviour:**

My dns-adres of my pi-hole's server can't be found. 

**[BUG | ISSUE] Steps to reproduce:**

-burn New NextcloudPi image, reinstalled and setup NextcloudPi, PiVPN and Pi-hole
-NextcloudPi and PiVPN are working fine.
-did those above several times, and did some chances in Pi-hole with the setups. 
-

**(Optional) Debug token generated by `pihole -d`:**

 hn573o86qn

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

extra info, Running the latest image of NextcloudPI (stretch lite), installed piVPN and pi-hole.
NextcloudPi and piVPN are working perfect together.

**Comment by Mcat12** [comment]
I added the issue template back to your post, please fill it out.

> Failure to fill the template will close your issue

**Comment by jacobsalmela** [comment]
Please generate a new debug token, your original one has expired

**Comment by MarkEngel** [comment]
You can close this one. I made a different setup of my pi that works.

**Comment by Mcat12** [comment]
@MarkEngel What are you doing to test if Pi-hole works?

**Comment by MarkEngel** [comment]
I'm not doing something special. I used the wiki and chances the dns
setting with nano. Than i didn't had adds anymore. Also the web interface
is working well.

My first setup on the Pi was, a image of NextcloudPi, setup PiVPN and
Pi-hole. Never found out the problem. Only the web interface of nextcloud
was working or the pi-hole, but never both of them.

Op 26 nov. 2017 19:35 schreef "Mcat12" <notifications@github.com>:

@MarkEngel <https://github.com/markengel> What are you doing to test if
Pi-hole works?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pi-hole/pi-hole/issues/1766#issuecomment-347028727>,
or mute
the thread

**Comment by Mcat12** [comment]
Sorry, I deleted the comment after my page refreshed with your previous comment (it hadn't refreshed with you closing the issue yet).

**Comment by MarkEngel** [comment]
No problem :)

Op 26 nov. 2017 20:52 schreef "Mcat12" <notifications@github.com>:
