### ISSUE TITLE
Can't clone on Debian 9.2.1

### ISSUE THREAD

**Issue by pwcazenave** [pi-hole/pi-hole#1770]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1
---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Install completes successfully.

**[BUG | ISSUE] Actual Behaviour:**
Install bails out after failing to clone the main pi-hole respository.

**[BUG | ISSUE] Steps to reproduce:**

- Install Debian 9.2.1 from netinstall ISO.
- wget https://install.pi-hole.net -O install-pi-hole.sh
- chmod +x ./install-pi-hole.sh
- ./install-pi.hole.sh
- Hit enter until the end.

The fix is to install the ca-certificates package with apt: `apt install ca-certificates`. This allows the git clones to complete successfully and the installation to finish.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
I could not replicate this with v3.2.  Are you still having issues with it @pwcazenave

**Comment by pwcazenave** [comment]
Nope, I can't either now.

I think I made the most barebones Debian install possible by deselecting all the options for the type of install (SSH server, Standard System Utilities etc.). I presume one of those include ca-certificates.

Anyway, PEBKAC.
