### ISSUE TITLE
Domain count in dashboard is incorrect

### ISSUE THREAD

**Issue by timmyrs** [pi-hole/pi-hole#1771]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_2_

---

I loaded the list at `https://netdex.co/hosts/d.txt` and the dashboard displays there are 836,697 domains on blacklist, however when I manually list the lines in the lists, it is clear that this is incorrect:

> root@raspi:/etc/pihole# wc -l gravity.list list.*
>   2434245 gravity.list
>   1217203 list.0.netdex.co.domains
>   1217136 list.preEventHorizon
>   4868584 total

**Comment by timmyrs** [comment]
Here are some screenshots:

![Dashboard](https://user-images.githubusercontent.com/11009697/32876656-5fbdecaa-ca8d-11e7-8f74-51842ff460c9.png)
![API](https://user-images.githubusercontent.com/11009697/32876658-63b10298-ca8d-11e7-92cb-6293bf49b368.png)

(Note: I have statistics disabled.)

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token. Have you enabled IPv6?

**Comment by timmyrs** [comment]
The debug token is `krr8disimi` and I have enabled IPv6.

**Comment by Mcat12** [comment]
What is the output of this command? `head /etc/gravity.list`
Also, try running these commands:
```
pihole -g
sudo service pihole-FTL restart
```

And then share the output of `/var/log/pihole-FTL.log`

**Comment by timmyrs** [comment]
After running gravity again the count is correct.
The first time I ran gravity via the web interface, maybe it had to do with that?

**Comment by Mcat12** [comment]
The web interface run of gravity should not be different than running it via the command line.
