### ISSUE TITLE
skipSpaceCheck not being set to "true" by undocumented option

### ISSUE THREAD

**Issue by bxm** [pi-hole/pi-hole#1772]
https://github.com/pi-hole/pi-hole/blob/b0eceddcec2054273d7e1add34d1f806b0c81693/automated%20install/basic-install.sh#L1377

Should read:
`"--i_do_not_follow_recommendations"   ) skipSpaceCheck=true;;`

**Comment by PromoFaux** [comment]
@bxm, we welcome pull requests if you would like to propose a fix.

Also, how ironic that you completely ignored the contribution guide and issue template.

As per the issue template, issues not following that will be closed until you update it to include the information we ask for.
