### ISSUE TITLE
Add Quad9 to the Upstream DNS Servers

### ISSUE THREAD

**Issue by steffanson** [pi-hole/pi-hole#1775]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---
**[OTHER]:**

Please add [Bind9](https://quad9.net/#/) to the default DNS resolver list of Pi-Hole.

[Bind9](https://quad9.net/#/) is a brand new DNS resolver network, initiated by a consortium conisting of Packet Clearing House (PCH), der Global Cyber Alliance (GCA), IBM and others partners.
It's fincanced by public entities only, claimes to take data protection seriously and offers DNSSec and TLS transmissions.

The server addresses are:
`9.9.9.9 (2620:fe::fe)` (filtered, validates DNSSec)
`9.9.9.10 (2620:fe::10)` (unfiltered, does not validate DNSSec)

or see the table below:

![quad9-feature-matrix-72311e6ae96e13b1 png](https://user-images.githubusercontent.com/17642285/32948470-99dacbca-cb9f-11e7-9ee9-5d023b51c7ac.jpeg)
![quad9-map-nov2017-3edf3a119e2a3ea1 png](https://user-images.githubusercontent.com/17642285/32948471-99f9725a-cb9f-11e7-872e-32ac24b0ec8d.jpeg)

**Comment by WaLLy3K** [comment]
#1774 is the appropriate PR for this issue :smile:

**Comment by shpigunov** [comment]
Just came in to suggest adding Quad9.
Wow guys you're quick.

**Comment by jj2473** [comment]
Ditto, came in to suggest and your on it.

**Comment by ion-storm** [comment]
Every IP other than 9.9.9.9 does not block malicious sites, that have another IP in a different ASN that has blocking as well, please add:
149.112.112.112
Source/Reference:
https://news.ycombinator.com/item?id=15715318

**Comment by jrtoman** [comment]
I see quad9 supports dns over TLS as well.

**Comment by jacobsalmela** [comment]
Resolved in v3.2 (#1774)

**Comment by Mcat12** [comment]
Actually, this will be resolved in the next release after 3.2 because it was merged into development after the release branch was made.

**Comment by jacobsalmela** [comment]
You're right.  Sorry about that.

**Comment by dschaper** [comment]
Closed via #1856

**Comment by Kolbi** [comment]
is it possible to add the TLS feature as well?
Like seen here: https://blog.sandchaschte.ch/de/pi-hole-with-dns-over-tls

**Comment by dschaper** [comment]
Not at this time, that's another service and another software package.
