### ISSUE TITLE
install on bridged system

### ISSUE THREAD

**Issue by bitchecker** [pi-hole/pi-hole#1782]
Hi,
i'm trying to install pi-hole on a red hat system with two nics that are bridged.
when i run the installer, system loss all connectrion and close ssh session.

i've installed in the past on a similar system but without bridged interfaces and it worked. i've tried to make a new installation on a standalone system and it works.

there is a way to install on a bridged system?

**Comment by Mcat12** [comment]
You might have to manually modify the configs. Checkout `/etc/dhcpcd.conf`. You might have to remove the static assignment (just make sure that the bridged interface that you end up using has a static IP).

**Comment by bitchecker** [comment]
hi,
thanks for reply.

the system is configured with bridged interfaces and the bridge has ad ip address that works properly.

when i start installation of pi-hole, installer checks missing packages, starts ncurses steps, and ask me on which interface it needs to serve. i've tryed bridge and a physical interfaces but results not changes, ssh connection were lost and isn't possibile to do anything, also server networking doesn't works anymore.
