### ISSUE TITLE
DNS_PROBE_FINISHED_BAD_CONFIG when ethernet is disconnected from PI and reconnected (link lost/re gained)

### ISSUE THREAD

**Issue by xmx1024** [pi-hole/pi-hole#1783]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[ISSUE] Expected Behaviour:**
When link is lost on ethernet, have pihole go back up when ethernet is reconnected.

**[ISSUE] Actual Behaviour:**
when ethernet is reconnected, all browsers show DNS_PROBE_FINISHED_BAD_CONFIG and android devices on network say "this network may not have internet connectivity"

**[ISSUE] Steps to reproduce:**

-unplug ethernet
-plug ethernet back in
-attempt to do anything online that requires DNS query
-

**(Optional) Debug token generated by `pihole -d`:**

` tltus40cu4`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Well, when the Pi lost the connection the devices didn't get a response from their DNS queries so they showed their respective warnings and errors. When it came back up, they probably kept their cached error response and if you wait or restart the networking on the device it will realize that the Pi-hole is back up. The debug log shows that it is responding correctly to DNS queries.

**Comment by jacobsalmela** [comment]
@xmx1024, @Mcat12's response is likely what happened.  Pi-hole will keep running whether it's actually on the network or not.  Is there more you'd like to add to this issue?

**Comment by xmx1024** [comment]
Devices still say they don’t have a connection until the pi with pihole is rebooted

**Comment by Mcat12** [comment]
Update to 3.2 and see if it's still an issue. If it is, then create a debug token before and after the enthernet goes down.
