### ISSUE TITLE
Dnsmasq not starting after reboot

### ISSUE THREAD

**Issue by divadsn** [pi-hole/pi-hole#1784]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

7

---
Pi-hole isn't working after rebooting my Orange Pi Zero. After restarting dnsmasq manually it works.

**Expected Behaviour:**
Dnsmasq service should be automatically started on reboot.

**Actual Behaviour:**
Service fails to start, status shows errors about non-existent eth0 interface.

**Steps to reproduce:**
- Install latest Armbian stable (Ubuntu xenial)
- Update firmware using armbian-config
- Install Pi-hole using the installer
- Reboot and see how Windows isn't able to resolve domains

**(Optional) Debug token generated by `pihole -d`:**

`0cwii02bf5`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
When you upgraded the firmware, did you restart before installing Pi-hole? There might have been changes which required a reboot. If you reboot the device again, does dnsmasq still fail to start?

Also, it may be that you are experiencing a Ubuntu dnsmasq packaging issue where the dnsmasq package for Ubuntu isn't configured to wait until the networking stack is up before starting. That's a packaging issue, and we can't really do much to fix that.

**Comment by divadsn** [comment]
Nevermind, it was fixed with a recent update of dnsmasq in the apt repo I think, as it does now work fine.
