### ISSUE TITLE
Subverting the blacklist

### ISSUE THREAD

**Issue by tl87** [pi-hole/pi-hole#1786]
In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:

[X] I have read and understood the contributors guide.
[X] The issue I am reporting can be replicated
[X] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

---------------------------------------------------------------------------------------------------------------------------------

**[BUG | ISSUE] Actual Behaviour:**

If yo have added a domain to the blacklist and then try to navigate to the domain it will be block, as expected. However if you go to a search engine, like Google, then search for the domain and click on the link to go to the domain, then you will not be blocked by PiHole blacklist. I've tested with a few other sites and it is the same result.

**[BUG | ISSUE] Steps to reproduce:**
1. SSH to PiHole or go to PiHole ip addr in browser
2. Add a domian to block. I will use pricerunner.dk. Lets first try to navigate to the site in our browser:
![pricerunner blocked by pihole](https://user-images.githubusercontent.com/5989314/33365805-abe608cc-d4e9-11e7-83e3-a605dec21ee6.png)
3. Then if we go to google and enter the domain and then click the link:
![pricerunner at google](https://user-images.githubusercontent.com/5989314/33365840-c886d5ce-d4e9-11e7-9a77-3342b5ee05db.png)
![pricerunner not blocked by pihole](https://user-images.githubusercontent.com/5989314/33365932-18c9a9da-d4ea-11e7-9f46-956f9266b4ad.png)
4. As you can see we are not blocked anymore, even though the domain stil is in the blacklist.
![blacklist on pihole](https://user-images.githubusercontent.com/5989314/33366156-b50c2138-d4ea-11e7-82a5-bc8301552737.png)

**Comment by PromoFaux** [comment]
Hi there, this is because the address you are getting is `www.pricerunner.dk` and not `pricerunner.dk`

You can add domains to the wildcard blacklist from the web front end, otherwise you need to also add `www.` as an additional domain to your blacklist.

**Comment by tl87** [comment]
So this will resolve the issue by adding *.pricerunner.dk to the blacklist file?

**Comment by tl87** [comment]
I tried to add both
- *.pricerunner.dk
- www.pricerunner.dk
to the blacklist file, and then opened another browser, to navigate to google and then pricerunner. Still same result..

**Comment by PromoFaux** [comment]
You cannot add wildcard entries to the normal blacklist file. You need to do it through the blacklist page on the web GUI and add as a wildcard entry there.

**Comment by tl87** [comment]
@PromoFaux 
Okay. If we look passed adding a domain with a wildcard.
If i add www. instead of *. to pricerunner.dk and add it to the blacklist, so I get:
www.pricerunner.dk
pricerunner.dk
It would block both www. and without ?

**Comment by PromoFaux** [comment]
That's correct.

Also, if you add `pricerunner.dk` as a wildcard (without the `*`), it will block `*.pricerunner.dk`

![blacklist](https://user-images.githubusercontent.com/1998970/33430497-97a16278-d5c8-11e7-82e6-960748224605.gif)

**Comment by tl87** [comment]
@PromoFaux 
I have a quite long list that I would like to add as wildcards, so adding them individually, is really not a good way of doing it, since the list is **+100k**
I could make a script with **xdotool**, but it would take way to long to complete and I would have to free up a machine to do the task.
I made a feature-request for making it possible to add a list of wildcard domains through the webgui, now we just have to see if it gets implemented.

**Comment by PromoFaux** [comment]
The blacklist is meant for small numbers of domains really.

If you have an additional list of 100k+, then the best thing would be to host the lists on something like [Github Gist](https://gist.github.com/), and then add a link to that hosted file in the block lists section of the settings page.

![image](https://user-images.githubusercontent.com/1998970/33440529-18bdd5de-d5e8-11e7-827f-449af1c2ff11.png)
(note: Your settings page may look different to this, as I am currently running the latest pre-release)

Obviously this would not be wildcard blocks, but I have seen your feature request on discourse, so hopefully that will inspire someone to code it!

**Comment by tl87** [comment]
@PromoFaux Thanks :)
