### ISSUE TITLE
Adding list through webgui [Feature-request]

### ISSUE THREAD

**Issue by tl87** [pi-hole/pi-hole#1787]
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your PR:**

**Please submit all pull requests against the development branch. Failure to do so will delay or deny your request**

- [x] I have read and understood the contributors guide.
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?: 1**

=================================================================================

## Feature-Request
Could it be made possible to add lists of domains through the webgui, with and without wildcard ?

The method now, where you have to add a single domain at a time, is not fun, when you have +100k list of domains with wildcard.

**Comment by PromoFaux** [comment]
A bit you missed from the issue template:

>**[BUG REPORT | OTHER]:**

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**Comment by smokingwheels** [comment]
Could you make some sort of bash script?

**Comment by tl87** [comment]
I could make a script with **xdotool**, but it would take way to long to complete and I would have to free up a machine to do the task.
I made a feature-request for making it possible to add a list of wildcard domains through the webgui, now we just have to see if it gets implemented.

**Comment by tl87** [comment]
Link is: https://discourse.pi-hole.net/t/adding-a-list-of-domains-to-white-blacklist-through-webgui/5686
