### ISSUE TITLE
DHCPv6 issue with default route

### ISSUE THREAD

**Issue by mpqo** [pi-hole/pi-hole#1788]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---

By enabling DHCPv6 support, pihole will assign v6 addresses (and DNS server) to devices but it will not advertise the default gateway (the router v6 address) resulting to no ipv6 connectivity. I see no field to add it manually either,

I've searched about this but haven't found anything related.

I've tested this behavior both with Master & development branches.

Windows 10 & Android 7.0 are affected.

Pihole is running on Ubuntu 16.04.3 LTS 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
@dschaper do you have insight into if this is still an issue?

**Comment by dschaper** [comment]
No new reports or issues noted. Closing.
