### ISSUE TITLE
[Feature] Shallalist filtering for Pi-Hole

### ISSUE THREAD

**Issue by mglinux** [pi-hole/pi-hole#1790]
Hey guys!

I made a small script for shallalist.de filter categories. Choose categories by menu and automate updating. Should be easy enough for the casual user too.

https://github.com/mglinux/IPF_Tools

Right now waiting for https://github.com/pi-hole/pi-hole/pull/1779
If locale files are supported I will change my script for using file:// format.

Script was tested in dietpi/pi-hole VM since I don´t use Pi-Hole myself. It was meant for Ipfire but after coding I thought this would be nice for Pi-Hole, too.

**Comment by jacobsalmela** [comment]
#1779 was released with v3.2.
