### ISSUE TITLE
dnsmasq should not cache negative responses by default

### ISSUE THREAD

**Issue by dermoth** [pi-hole/pi-hole#1793]
I've been trying out pi-hole the last few days and it's an awesome product. I've got a glitch though as my upstream resolver sometimes return NXDOMAIN on the first query. This normally isn't an issue ad caching DNS server should not cache NXDOMAIN, however pi-hole did and failed to resolve valid names over and over.

In order to be more transparent to the user I believe pi-hole should default not to cache negative queries by default and let users opt-in to enable negative cache if desired.

The fix for me was adding `no-negcache` in `/etc/dnsmasq.d/01-pihole.conf`, and pi-hole is now working like a charm on my home network (~130k lookups per day).

**Comment by PromoFaux** [comment]
The issue template is not optional, and [failure to fill it out will result in your issue being closed](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md). Please edit your submission to include the template.

This does not mean your submission holds no value, just that we require the template to be filled out.
