### ISSUE TITLE
Pi-hole ist blocking a domain despite its on the withlist

### ISSUE THREAD

**Issue by razzor1984** [pi-hole/pi-hole#1803]
Hello,

i did the update today, it upgraded fine, only at the end there was an odd message -
[Error: Could not update local repository. Contact support.]
Pi-hole -up shows everything is updated correctly.

So the strange part: wanted to check some files on virustotal.com - strangly its on the blocking list of  "list.15.malwaredomains.lehigh.edu.domains". 
Normaly thats no big deal, i just withlist it.
But its like that the withlist is ignored.
(In the log its clearly blocked)

Steps i did  to fix it:
I did - delet  virustotal.com from the withlist and added it back
Did a full system restart
Restared serveral times the dnsmaq service 
Flushed serveral times my Dns cache

Saidly this did not fixe this issue.

Is this a bug? or is the new update the root cause?

**Expected behaviour:**

`virustotal.com is withlisted and should load`

**Actual behaviour:**

`Pi-hole blocks it (virustotal.com) - its clearly displayed in the logs`

**Steps to reproduce:**
`add list.15.malwaredomains.lehigh.edu.domains to your blockist and withlist virustotal.com `

**Troubleshooting undertaken, and/or other relevant information:**

`I did - delet  virustotal.com from the withlist and added it back
Did a full system restart
Restared serveral times the dnsmaq service 
Flushed serveral times my Dns cache`

best regards Razzor

Edit: Hw is a Pi-model B+

**Comment by dxm765** [comment]
Just opened a similar issue I am having with Google.com being blocked, but then I whitelist it and it's still blocked.

**Comment by razzor1984** [comment]
If im not the only person i its a bug - i did pihole -d but there is nothing "wrong" i the debug history.

**Comment by razzor1984** [comment]
pihole -q virustotal.com
 Match found in Whitelist
   www.virustotal.com
 Match found in list.8.pilotfiber.dl.sourceforge.net.domains:
   virustotal.com.br
 Match found in list.15.malwaredomains.lehigh.edu.domains:
   20160111
   20150124
   20150130
   20150210
   20150515
   20150718
   20150515
   20150413

**Comment by dschaper** [comment]
`virustotal.com` and `www.virustotal.com` are two different domains and both would need to be whitelisted.

**Comment by dschaper** [comment]
Also, there is an issue template that needs to be filled out so that we can help you. If you can open a new issue with the template filled out and the debug token supplied to us we can better help you. Closing this issue, you can open a new one with the required information.
