### ISSUE TITLE
Cant ssh onto Pi-hole to run pi-hole up  it says pasword wrong but password is same as web page wich logs in ok 

### ISSUE THREAD

**Issue by G0NMY** [pi-hole/pi-hole#1804]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by G0NMY** [comment]
Friend of mine just had same problem cant ssh onto pi-hole wrong password even though password was working before. has an update killed ssh? Only option I have is to start from new write image and re-install

**Comment by dschaper** [comment]
We don't and cant change the `ssh` password, that is set per the user that you have configured for the server. There isn't any code that would call the `passwd` command which is what changes the `ssh` credentials.

**Comment by G0NMY** [comment]
my fault I was logging on as user pi-hole now sorted apologies
