### ISSUE TITLE
getent hosts pi.hole fails if /etc/resolv.conf has resolvers other than localhost.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1806]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`10`

---
**Expected behaviour:**

`getent hosts pi.hole` is being used as a check for DNS resolver functionality before continuing to proccess `pihole -g`.

**Actual behaviour:**

If the `/etc/resolv.conf` contains resolvers other than `127.0.0.1` then the local `dnsmasq` will not be queried and `pi.hole` is NXDOMAIN. This means that even though name resolution is working, the `getent hosts` check fails and the holddown timer keeps ticking and eventuall fails.

**Steps to reproduce:**

Install Pi-hole and have any other resolvers on the Pi-hole device `/etc/resolv.conf`. This can include `127.0.0.1` but if it is not solely localhost then the `getent` will fail.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`la6kw0m3r2`

**Comment by dschaper** [comment]
Confirmed that if `/etc/resolv.conf` is edited so that it contains only `127.0.0.1` then the `getent` test passes.

**Comment by jacobsalmela** [comment]
I'm thinking maybe we use `dig +short` as a fallback if we determine there are other resolvers configured.  This should allow the script to continue (presuming the configured resolvers work appropriately).

**Comment by Mcat12** [comment]
We should be able to use dig to replace the gentent test.

**Comment by dschaper** [comment]
That's a short circuit solution though. The reason for the check is to make sure that the `dnsmasq` process is resolving correctly before finishing the update process. For people with large numbers of lists and slower processors, there's a real chance that the `dnsmasq` process will restart before the lists are fully updated so we added in the check to make sure that doesn't happen. By adding that line to your hosts file the test will never fail and users can end up back in the same situation of having their Pi-hole not fully utilizing their lists. 

We are testing a replacement to the function that will work reliably.

**Comment by thexmanxyz** [comment]
@wnoisephx @ookangzheng @RexBelli @Happyfeet01 @vr6syncro @p1r473 @mcfalld I can confirm that the `development` version of the [`gravity.sh`](https://github.com/pi-hole/pi-hole/blob/development/gravity.sh) fixes the issue. So the best is to wait on the next update (v3.2.1) or simply replace `gravity.sh` with the latest development version. Target location on your device is by default `/opt/pihole/gravity.sh`. As already said adding 127.0.0.1 to hosts is not ideal. This solution should work and will receive an overwrite with the next update as well ;).

**Comment by jacobsalmela** [comment]
We do have the [`pihole checkout` command](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout).  If you can't wait for the fix to make it to `master`, you could check out `development` branch.  You'll get the fix, plus some other things, but we don't recommend running it long term as things often break in there (although, admittedly, the seems be the current state of our `master`...).  

If you just want _this_ fix, you could `checkout` the `fix/resolvconf` branch.

One last alternative is to switch to either of these branches only when you run `gravity` and then switch back.

**Comment by thexmanxyz** [comment]
@jacobsalmela Thanks for the additional information and your thoughts on switching versions. Didn't see/know the `fix/resolvconf` branch but good to know that you take care on such situations :). However I'm aware of the `development` branch and the possibilitiy of difficulties behind it. I just pointed on a simple fix which does not require to bother with anything else (branch switch, manual checkouts etc.). Git is for a casual user a bit of a pain and still confusing and hard to understand. But modifying one file seems to me quiet easy so a I posted a more reasonable solution then the others listed in 1800, 1801 and here.

**Comment by Mcat12** [comment]
We try to make switching to a branch easy, so to use the `fix/resolvconf` branch you just need to run:
```
pihole checkout core fix/resolvconf
```

And then to go back to master:
```
pihole checkout core master
```

**Comment by thexmanxyz** [comment]
@Mcat12 Oh thanks for posting again, it seems that I missed that @jacobsalmela pointed on the pihole checkout command like you did. I didn't mind that. I was focused on github commands in didn't see that branch checkout is already ingetrated in pihole. sorry :(
