### ISSUE TITLE
Settings.php in v3.2 doesn't work with Wheezy, CentOS 7

### ISSUE THREAD

**Issue by bradgrutsch** [pi-hole/pi-hole#1807]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
10

---
**Steps to reproduce:**
1. Install pi-hole on a raspberry pi 1 running raspian Wheezy with PHP 5.4.45
2. Load the web interface and browse to the settings page

**Expected behaviour:**
I expected Settings to load

**Actual behaviour:**
Loading Settings.php on the web interface returns a 500 error.

**Troubleshooting undertaken, and/or other relevant information:**

/var/log/lighttpd/error.log has this error when loading settings:
_PHP Fatal error:  Can't use function return value in write context in /var/www/html/admin/settings.php on line 15_

Line 15 of settings.php is using empty() in a way that may not be fully supported on PHP 5.4 (see here: [https://stackoverflow.com/questions/1532693/weird-php-error-cant-use-function-return-value-in-write-context](url)

It looks like Wheezy only has PHP 5.4 and updating to at least Jessie is required for pi-hole 3.2

**Comment by bradgrutsch** [comment]
In case anyone else stumbles upon this:
I updated from Wheezy to Jessie successfully using this post (with the caveat that I use my rPi headless, so the UI may not have upgraded successfully):
[https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=121880](url)

After that, I repaired the pi-hole install using "pihole -r" and the settings page now works correctly.

I think this is less of a bug and more of a feature request: the pihole install scripts should check the PHP version installed and warn/fail if the version is <5.5.

**Comment by mchilli** [comment]
Have the same issue, is there any workaround for this.
I don't wont to update to jessie!

**Comment by mchilli** [comment]
ok don't know if it right, but changing line 15 from this:
`return !empty(shell_exec(sprintf("which %s", escapeshellarg($cmd))));`
to this:
`return shell_exec(sprintf("which %s", escapeshellarg($cmd))) == false;`
makes it possible for me to enter the site again.

**Comment by idrum4316** [comment]
I'm getting a 500 error when I go to the settings page, too. I'm on a fully updated CentOS 7 server. I don't think any version of CentOS includes PHP > 5.4.

**Comment by jacobsalmela** [comment]
Confirmed on CentOS 7

**Comment by jacobsalmela** [comment]
Removing [this function seems](/var/www/html/admin/settings.php) to fix it.  @pi-hole/admin anyone know what the function does?

```
function command_exist($cmd)
{
    return !empty(shell_exec(sprintf("which %s", escapeshellarg($cmd))));
}

to 
```

**Comment by marshallstokes** [comment]
Queries userland tool `which` against argument `$cmd` to determine if the command is available on the system, in the PATH of the php or lighttpd user, it seems.

**Comment by Mcat12** [comment]
It looks like that command can be safely removed. I haven't found any usages of it (might have been used before, but not removed alongside the usages).

**Comment by jacobsalmela** [comment]
Issue moved to [pi-hole/AdminLTE #628](https://github.com/pi-hole/AdminLTE/issues/628) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ninjaivxx** [comment]
I have updated to version 3.2.1 but my settings.php page will not load. It was working when I was on 3.2
