### ISSUE TITLE
2.4: Navigating UI /admin pages are very slow since upgrade

### ISSUE THREAD

**Issue by alasdairdc** [pi-hole/pi-hole#1814]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

PHP `~7`

---
**Expected behaviour:**

Page load speed comparable with previous version

**Actual behaviour:**

After upgrading to 3.2 navigating to any `/admin` page is very slow

**Steps to reproduce:**

Not sure if this will reproduce it or not, but installed previous version of pihole on a Debian 9 Proxmox VM, then ran `pihole -up` as root to upgrade it.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Nothing relevant is reported in `/var/log/messages`, `/var/log/syslog`, `/var/log/pihole{,-FTL}.log`, `/var/log/lighttpd/error.log` 

will debug more when home and update with Debug token

originally reported at https://redd.it/7ierm6 but dont think its solely `db_queries.php` as reported there.

**Comment by alasdairdc** [comment]
Have tracked it down to `pihole status` taking a long time to return

```
# time pihole status web
1
real	2m10.223s
user	0m0.004s
sys	0m0.000s
```

**Comment by alasdairdc** [comment]
Have tracked it down to blocking IPv6 traffic over the loopback device, specifically DNS requests.

**Comment by Mcat12** [comment]
Thanks, did you manually block IPv6?

**Comment by alasdairdc** [comment]
Yes I was manually blocking IPv6, which made `pihole status` wait around 2 minutes before timing out (I guess).  Allowing IPv6 DNS traffic via the loopback interface allows it to return promptly again.
