### ISSUE TITLE
Stats empty using safari browser since last update

### ISSUE THREAD

**Issue by sparklyballs** [pi-hole/pi-hole#1822]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`when visiting the admin page i expect to see stats and graphs (when logged in for the graphs)`

**Actual behaviour:**

`When using safari browser Version 11.0.1 (13604.3.5) on macos 10.13.1 the stats at the top of the page and all graphs when logged in are blank, however using opera browser on the same mac machine results in being able to see the stats and graphs, and prior to the latest update all was working using safari
I have cleared cache, cookies, flushed dns etc within safari and on my mac to no avail`

**Steps to reproduce:**

`use the same version of safari and macos with the same versions of the pihole elements`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`dthgn5zdvn`

**Troubleshooting undertaken, and/or other relevant information:**

`if relevant i am using the dnscrypt setup from this guide https://github.com/pi-hole/pi-hole/wiki/DNSCrypt`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by c-hoeger** [comment]
I have the same problem since the update.

# pihole -v
  Pi-hole version is v3.2 (Latest: v3.2)
  AdminLTE version is v3.2 (Latest: v3.2)
  FTL version is vDev-437af07 (Latest: v2.12)

![bildschirmfoto 2017-12-09 um 11 35 35](https://user-images.githubusercontent.com/4416051/33794906-32d8e9c4-dcd5-11e7-9188-0a04eed64c27.png)

**Comment by DL6ER** [comment]
Please do a force-refresh in your Safari browser, e.g.
https://apple.stackexchange.com/questions/12049/how-to-clear-the-cache-or-do-a-hard-refresh-in-safari

**Comment by DL6ER** [comment]
This happens almost always after updates becuase some user's browser do not download the updated scripts from the Pi-hole and behave odd for a few days. Then this issues magically disappear as the browser download the scripts at some point on their own.

**Comment by sparklyballs** [comment]
empty cache (from the develop menu in safari) does indeed resolve this

however this is the first update i have needed to perform that step with

**Comment by sparklyballs** [comment]
i have another issue though

the flush logs button on the admin doesn't clear the stats (with any browser)

**Comment by c-hoeger** [comment]
Yes, that solved the problem. Also didn't experience that before. A Shift-Reload is enough, btw.
