### ISSUE TITLE
GUI versions mismatch with CLI versions after v3.2 update

### ISSUE THREAD

**Issue by ferdydek** [pi-hole/pi-hole#1833]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**

`Versions on GUI and CLI match`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`
After update to v3.2 and restarting the server (RasPiWZ) the versions mismatch:
GUI:
![image](https://user-images.githubusercontent.com/5775168/33805443-0f5c6af2-ddb1-11e7-90bf-0a75e88d2bd9.png)
CLI:
![image](https://user-images.githubusercontent.com/5775168/33805451-3019fa98-ddb1-11e7-8aaa-de717cbd3715.png)

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`kldgymzu9i`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried: reboots, refreshes, various browsers, cache clearing.`

**Comment by ferdydek** [comment]
Also tried reinstallation update via `curl -L https://install.pi-hole.net | bash` same result. I don't get any errors.

One more GUI info: 
![image](https://user-images.githubusercontent.com/5775168/33805563-159c2266-ddb3-11e7-8f97-1d27d8d51386.png)

**Comment by DL6ER** [comment]
You said that you tried rebooting, but according to your GUI screenshot, `FTL` is running non-stop since `Nov 27`. I don't see how that can be possible...

Please try
```
sudo service pihole-FTL restart
```

**Comment by ferdydek** [comment]
Oh, turns out I have not powered down a test pihole I have on another RasPi and I was updating the wrong device.
Sorry for the trouble.
