### ISSUE TITLE
tooltip behind other div

### ISSUE THREAD

**Issue by f0nt4** [pi-hole/pi-hole#1837]
I think that this screenshot exactly shows what the bug is.

![Image of bug](https://i.imgur.com/TP1AMkI.png)

The tooltip gets behind other content. While it should be in the front so you can see the whole list.
This behaviour is also in boxed layout.

Version: Pi-hole Version v3.2 Web Interface Version v3.2 FTL Version vDev-437af07

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #638](https://github.com/pi-hole/AdminLTE/issues/638) via [**ZenHub**](https://www.zenhub.com/)
