### ISSUE TITLE
HTTP 500 Internal Server Error @ settings page

### ISSUE THREAD

**Issue by stomp442** [pi-hole/pi-hole#1838]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**

Able to see, use settings page to configure pi hole settings
**Actual behaviour:**

Clicking on settings results in a 500 Internal Server error.

pi@pi-hole ~ $ curl -I http://192.168.10.25/admin/settings.php
HTTP/1.1 500 Internal Server Error
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-Powered-By: PHP/5.4.45-0+deb7u11
Content-type: text/html
Date: Mon, 11 Dec 2017 20:05:57 GMT
Server: lighttpd/1.4.31

I've rebooted. Upgraded the http service. Restarted the service. All result the same.

**Steps to reproduce:**

Log into webui, click on settings, receive error.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

m2el1vb3gs

**Troubleshooting undertaken, and/or other relevant information:**

See curl output.

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #639](https://github.com/pi-hole/AdminLTE/issues/639) via [**ZenHub**](https://www.zenhub.com/)
