### ISSUE TITLE
Keep losing DNS service

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#1842]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

The PiHole blocking ads

**Actual behaviour:**

The Pihole does not have DNS resolution

**Steps to reproduce:**

It just happened by itself

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

o0btkt9u26

**Troubleshooting undertaken, and/or other relevant information:**

So this is the 2nd time its happened this week. I keep having to change /etc/resolv.conf to 8.8.8.8 from 127.0.0.1 just to have DNS on the Pihole

A few things to note:
During Pihole -r, if I select reconfigure, I get the error:
[✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
  [✗] FTL Engine not installed

Also, my Pihole -d command gives output:
*** [ DIAGNOSING ]: Dashboard and block page
[✗] X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Content-Type: text/html
Accept-Ranges: bytes
ETag: "3899236152"
Last-Modified: Fri, 13 Oct 2017 03:53:51 GMT
Content-Length: 10701
Date: Wed, 13 Dec 2017 10:51:41 GMT
Server: lighttpd/1.4.45

SO did something change on your end, as my Pihole used to be incredibly stable, now I keep having to repair, and atm, the Pihole can't even ping Google, let alone serve my DNS queries :(

**Comment by norrkin** [comment]
I don't think you have configured pi-hole correctly.  
You shouldn't need to edit /etc/resolv.conf as all that is doing is pointing to dnsmasq.
Then you would edit /etc/pihole/setupVars.conf and set which dns revolvers you wish to use.

i.e. 
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4

But the install wizard takes care of all this.

**Comment by zaggynl** [comment]
Same issue for me, have Custom 1 set to 91.239.100.100, Custom 2 to 193.0.14.129.
At times DNS resolving just stops, if I enable Google 8.8.8.8 in pihole, no problem.
If I change DNS on router from pihole to 91.239.100.100, 2 or 193.0.14.129, no problem.

**Comment by adamsewell** [comment]
I had a similar issue out of the box, my pihole server is on DigitalOcean running with Ubuntu which automatically sets their nameservers. I had to edit their /etc/network/interfaces.d/50-cloud-init.cfg file and change the dns-nameservers to just 127.0.0.1. That resolved that issue for me.

**Comment by zaggynl** [comment]
@adamsewell Am running pihole on Ubuntu but not in DigitalOcean, no /etc/network/interfaces.d/50-cloud-init.cfg file or likewise present.

**Comment by Mcat12** [comment]
Does the development code fix this issue?
```
pihole checkout dev
```

**Comment by p1r473** [comment]
@Mcat12 Seem to be unable to download my lists after performing that command 

![image](https://user-images.githubusercontent.com/9235633/33967508-c2c6bd2c-e031-11e7-97c0-f734e1c1496b.png)


@norrkin using 127.0.0.1 in resolv.conf means using the Pi as the DNS provider for the DNS queries made by the Pi. If PiHole is not serving DNS properly due to being broken, then it can't even service its own DNS queries,  I had to switch to using Google DNS

**Comment by Mcat12** [comment]
What do those domains resolve to? Are you able to go to them manually?

**Comment by p1r473** [comment]
I can resolve them if I change /etc/resolv.conf to 8.8.8.8

I've changed it to 8.8.8.8 so I can run the update and give you a new debug token, but it seems to not work if resolv.conf contains 127.0.01

debug: 495llzj0v9

**Comment by zaggynl** [comment]
Works OK for me at this time with dev code, difficult to pin down what causes as issue comes up randomly.

**Comment by Mcat12** [comment]
You haven't set any upstream DNS servers:
```
PIHOLE_DNS_1=
PIHOLE_DNS_2=
```

**Comment by p1r473** [comment]
@Mcat12 because I am using dnscrypt, those lines are supposed to be commented out. Upgrading to dev build must have reverted that. Let me see what happens when I comment it

**Comment by Mcat12** [comment]
Because the DNSCrypt client proxy is unable to load, your DNS server is unable to reply to queries and that seems to be why you have to use an external DNS server.

**Comment by p1r473** [comment]
I am going to try to reinstall DNSCrypt now. Will post back
Thanks

**Comment by p1r473** [comment]
So far so good. Will post back if I have any problems, thanks!
@Mcat12 do you have a donation link via paypal or BTC?

As well, is it safe to change Pihole's IP in setupVars to 127.0.0.1? I want the gravity.list file to start with 127.0.0.1 as I feed my list to my Adaway on my android, which doesn't like the list if it begins with my piholes real IP
It works for now but I am wondering if that contributed to my dnsproxy getting messed up

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole#donations is our BTC and PayPal donation links.

**Comment by Mcat12** [comment]
You should be able to change the IP in setupVars, just run `pihole -g` afterwards.

**Comment by 1sweatybanana1** [comment]
I to am having the same problem, running raspbian stretch on my pi

not using DHCP on the pi (using a Tomato Shibby router instead) and just want to route all DNS through the pi.

I cannot resolve any DNS from the pi or anywhere else for that matter using my pi <IP> as my DNS provider.

If i enable google DNS-upstream magically everything works.

I am not using dnscrypt

my resolv.conf is set 127.0.0.1

my DNS_PROBE are just my PI static <IP>

I tried just now updating 'pihole checkout dev' but still not working


only works if i go into the dashboard and select google or some other provider as up-stream.

**Comment by scarnecchia** [comment]
I'm having the same problem too, running raspbian jessie on my pi.

I'll dig all the logs and details out for you guys later, but right now I really want an option to downgrade, because I lost an entire Saturday trying to figure out what broke my network. I'm not pleased.

**Comment by PromoFaux** [comment]
```
cd /etc/.pihole
git checkout V3.1.4
pihole -r
```

**Comment by 1sweatybanana1** [comment]
All, going to try PromoFaux suggestion now see how it goes.. will reply with my results.

**Comment by scarnecchia** [comment]
Thanks @PromoFaux, Unfortunately that results in: 
`error: pathspec 'V3.1.4' did not match any file(s) known to git.`

I've also tried checking out the tag, yielding the same results, and

`git clone -n https://github.com/pi-hole/pi-hole.git
cd pi-hole
git checkout b0eceddcec2054273d7e1add34d1f806b0c81693`

No luck.

**Comment by 1sweatybanana1** [comment]
uh oh, im not keen at this language, Getting different result then scarnecchia's reply.....  is this acceptable any other required commands before issuing 'pihole -r' ?

pi@raspberrypi:/etc/.pihole $ sudo git checkout v3.1.4
Note: checking out 'v3.1.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b0ecedd... Merge pull request #1617 from pi-hole/hotfix/CIDR

**Comment by PromoFaux** [comment]
Hmmm just tried this on my own and it works. That said, it may be that your local copy does not have references to the tags.

Try 

```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole.git /etc/.pihole
cd /etc/.pihole
sudo git checkout v3.1.4
pihole -r
```


Alternatively, the 'development` branch should be much more stable for you right now, as we're getting ready to push 3.2.1 out. `pihole checkout dev` will put you on it (`pihole checkout master` to revert)

**Comment by PromoFaux** [comment]
@1sweatybanana1, that looks fine, you should be ok to run `pihole -r` at this stage.

**Comment by 1sweatybanana1** [comment]
@PromoFaux  ran through the 'repair' option and still having same problem, no DNS resolving unless select another up-stream other then my PiHole IP.

my version on dashboard now shows:

Pi-hole Version vDev (HEAD, v3.1.4-0-gb0ecedd) Web Interface Version vDev (devel, v3.1-322-g5ef3a88) FTL Version vDev ((no, vDev-437af07 )

**Comment by Mcat12** [comment]
@1sweatybanana1 You should have at least one upstream set for the Pi-hole, otherwise it can't resolve any queries.

@scarnecchia and @1sweatybanana1 please run `pihole -d` for a debug token.

**Comment by 1sweatybanana1** [comment]
@All thanks for all the help, apparently I had done everything correctly just needed to build up the blocklists  to achieve a wider net of ad-blocking, this is a cool dashboard and use of raspberrypi (I find it to be a great compliment to also using uBlock Origin extension as it will also remove the iframe of the advertisement not just block its content.

**Comment by dschaper** [comment]
Thanks, is it okay to close the issue then?

**Comment by 1sweatybanana1** [comment]
Yes, please close it.
