### ISSUE TITLE
Temporarily allow blocked site

### ISSUE THREAD

**Issue by CodingSpiderFox** [pi-hole/pi-hole#1844]
When I visit a link from a newsletter I get (and actually want to receive), the page gets blocked.

First by my uBlock Origin Chrome extension. uBlock gives me the possibility to allow the page for one visit.

![image](https://user-images.githubusercontent.com/25173078/33961929-134c64ae-e050-11e7-879b-a0479c3bab04.png)

After I allow it, pihole blocks the page. I can whitelist a page with pihole but I want to be able to do a "one visit" whitelisting so after I visited the page, it will be blocked again automatically.

![image](https://user-images.githubusercontent.com/25173078/33961915-03ee00ee-e050-11e7-9200-820cfd8eae6a.png)

Also, it would be nice to be able to define a timeframe for how long the page should be whitelisted (e.g. 5 minutes or so)

**Comment by jacobsalmela** [comment]
This is already a votable feature request on Discourse: https://discourse.pi-hole.net/t/add-a-temporarily-allow-feature/3947

**Comment by CodingSpiderFox** [comment]
Thx for the info
