### ISSUE TITLE
DNS Trust Anchor

### ISSUE THREAD

**Issue by heartsaver1859** [pi-hole/pi-hole#1846]
Where is the root trustanchor located in your config files?
Did you have planed to change to the newes 2 trust anchors?

trustanchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trustanchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

Source: https://data.iana.org/root-anchors/root-anchors.xml 

When I choose to use one of the root dns servers, I can't use dnssec because of your old trustanchor. 
If i change the automatically generated file in /etc/dnsmasq.d/01-pihole.conf from trustanchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
to trustanchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D I can use dnssec as usual.

**Comment by dschaper** [comment]
Fixed in #1856
