### ISSUE TITLE
IPv6 not enabling

### ISSUE THREAD

**Issue by jmackxiii** [pi-hole/pi-hole#1847]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Expected to be able to configure IPv6`

**Actual behaviour:**

`All IPv6 setting are grayed out`

**Steps to reproduce:**

`All IPv6 information is grayed out/disabled and there is no IPv6 address listed in the web interface`

**[✓] Your debug token is: 4250hktf8u**

`4250hktf8u`

**Troubleshooting undertaken, and/or other relevant information:**

`Did a repair install... Reconfigure install (removing and adding IPv6 support), total uninstall/reinstall, all without error`

**Comment by PromoFaux** [comment]
https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127

**Comment by jmackxiii** [comment]
Ok, just figured I would report this since it's new behavior in this release.. with the web interface being disabled and grayed out.

**Comment by PromoFaux** [comment]
Looking at your debug log you have no ipv6 address assigned to your device. If one is detected, it would be added to `/etc/pihole/setupvars.conf`, which in your case is blank (usually when the only v6 address detected is a local one with no internet connectivity)

**Comment by jmackxiii** [comment]
Hmm ok.. I will look into that..

**Comment by Mcat12** [comment]
Working as expected, since your network doesn't fully support IPv6.
