### ISSUE TITLE
tips for rookies from rookie

### ISSUE THREAD

**Issue by jsrfuture** [pi-hole/pi-hole#1848]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
 I'm a rookie, and i just installed pihole+dnscrypt on a rpi3b. There was some issue/mistake that pissed me off more then i would care to admit and i think they should be documented.

1.- During the instalation i always had the "DNS resolution is currently unavailable" issue, wich can be easily solved during the 120 sec countdown: `sudo nano /etc/resolv.conf` then replace `nameserver 127.0.0.1` by `nameserver 8.8.8.8` it will rollback later to 127.0.0.1 so do not worry about it.

2.-You can easily add private/non-default dnscrypt server between those step
```
mkdir -p dnsproxy
cd dnsproxy
wget https://download.dnscrypt.org/dnscrypt-proxy/LATEST.tar.bz2
tar -xf LATEST.tar.bz2
cd dnscrypt-proxy[tab completion]
```
right there by doing `libreoffice --calc /home/[your user name]/dnsproxy/dnscrypt-proxy-[your dnscrypt version]/dnscrypt-resolvers.csv` ( i do not think it auto-update by default but just in case you should make a backup of your modified *.csv)
```
sudo ldconfig
./configure --with-systemd
make
sudo make install
```
And if you do add something to that file, be sure to add the port with the ip 

ex : if you want to add this one https://servers.opennic.org/edit.php?srv=ns3.ca.dns.opennic.glue you need to write the ip in the appropriate column like this : `142.4.204.111:443`
for this particular dns you would need to join the opennic whitelist beforehand.

3.- If you are following the pihole-dnscrypt wiki and have rebooted or closed the terminal before the wiki tell you, be sure that you are still in the correct directory.

**Comment by PromoFaux** [comment]
The wiki pages are editable by anyone, please feel free to update them with your suggestions :)
