### ISSUE TITLE
Blocklist wildcard entries pointing to the wrong IP after changing the IP of the pihole

### ISSUE THREAD

**Issue by StarPicard** [pi-hole/pi-hole#1852]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the source code relevant to this issue?:**

1

---
**Expected behavior:**

The IP-address in `/etc/dnsmasq.d/03-pihole-wildcard.conf` should change, after reconfigure the Pi-hole and set the default IP to a new address.

**Actual behavior:**

The IP-address point to the old "location". Problem here is long timeout and potential pointing to a service now hosted on this IP-address.

`/etc/dnsmasq.d/03-pihole-wildcard.conf` now shows:

```
address=/anon.com/192.168.178.37
address=/anon.com/192.168.178.37
address=/anon.com/192.168.178.37
address=/anon.net/192.168.178.37
...
# This is added after IP change
address=/anon.com/192.168.178.201
```

**Steps to reproduce:**

1. Setting up the Pi-hole with an address.
2. Adding some wildcard entries
3. Reconfigure the Pi-hole and changing the static IP-address
4. Adding another wildcard entry

**Comment by dschaper** [comment]
Thanks for the report, we'll take a look.

**Comment by dmblack** [comment]
Confirmed bug or enhancement. I encountered this just now.

Manually created blocklisted items generate entries like;

```
address=/<domain><tld>/<piholeip>
```

Updating the IP address of the pihole using `pihole -r` doesn't change all of these. However; entries added after IP change are fine, obviously.

Will endeavor to contribute some kind of pull request if I get time.
