### ISSUE TITLE
PiHole doesn't block Ip6 ads

### ISSUE THREAD

**Issue by Trevinlc1997** [pi-hole/pi-hole#1855]
Version: 3.2

I receive ads on ip6 with a fresh install.
![capture](https://user-images.githubusercontent.com/24485362/34182444-e6861434-e4db-11e7-8351-c2531865ee20.PNG)

**Comment by PromoFaux** [comment]
As the issue template you deleted states... filling it out is not optional.

**Comment by PromoFaux** [comment]
Also, as I'm feeling just friendly enough, try this: 

https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

**Comment by Trevinlc1997** [comment]
@PromoFaux  Sorry about that, I am use to VsCode's template which is mostly optional. Much appreciated and any further issues I will provide the template. Sorry again.
