### ISSUE TITLE
Web Interface Failing Upgrade 3.2 to 3.2.1

### ISSUE THREAD

**Issue by nedgeworth** [pi-hole/pi-hole#1865]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

`Version upgrade to 3.2.1 with no issues.`

**Actual behaviour:**

```
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] FTL:		up to date
  [i] Web Interface:	update available

  [i] Pi-hole Web Admin files out of date
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...
  Error: Could not update local repository. Contact support.
```

**Steps to reproduce:**

`sudo pihole -up`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wkuagg46es`

**Troubleshooting undertaken, and/or other relevant information:**

sudo nano /etc/pihole/setupVars.conf
Updated with correct IPV4 address and subnet
Rebooted and retried, same result

Diet-Pi Version 159

**Comment by DL6ER** [comment]
Have you modified any source code files in `/var/www/html/admin`?

Try
```
cd /var/www/html/admin
sudo git reset --hard HEAD
cd ~
sudo pihole -up
```

**Comment by nedgeworth** [comment]
Nope, completely stop install.
That has updated, though I'm now seeing the following after a reboot in the web console. 

Pi-hole Version v3.2.1 Web Interface Version v3.2 (Update available!) FTL Version vDev (XXX , v2.13 )

sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] FTL:		up to date
  [i] Web Interface:	up to date

  [✓] Everything is up to date!

**Comment by nedgeworth** [comment]
Same result on my 2nd DietPi. Difference being this one hasn't had it's IP changed after the initial installation.

**Comment by DL6ER** [comment]
Hmm, what do you see here?
```
cd /var/www/html/admin
sudo git rev-parse --abbrev-ref HEAD
sudo git describe --long --dirty --tags 
```

**Comment by nedgeworth** [comment]
`v3.2.1-0-g31dddd8`

**Comment by DL6ER** [comment]
That means that the update succeeded! You may have to wait a few minutes for the display to become updated on the dashboard (that is happening asynchronously!).

You can force a version update using
```
sudo pihole updatechecker local
```

**Comment by nedgeworth** [comment]
Still seeing the incorrect version for FTL.

`Pi-hole Version v3.2.1 Web Interface Version v3.2.1 FTL Version vDev (XXX , v2.13 )`

**Comment by DL6ER** [comment]
Yes, this is another cosmetic bug we missed. It is reported in https://github.com/pi-hole/AdminLTE/issues/652 However, the dashboard shouldn't display that there is an update available for `FTL`.

You are now on the most recent version of Pi-hole!
