### ISSUE TITLE
IP Change after initial install

### ISSUE THREAD

**Issue by nedgeworth** [pi-hole/pi-hole#1867]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

`All items and checks should against the new IP Address as this could pose problems in the instance there is another DNS server on the original IP address`

**Actual behaviour:**
Still reference the original IP
`/etc/pihole/setupVars.conf`
`/etc/pihole/local.list`
`/etc/pihole/gravity.list`

**Steps to reproduce:**

`Change your IP address`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`pp90oxvara`

**Troubleshooting undertaken, and/or other relevant information:**
I have manually updated the IPs in the following two files.

`/etc/pihole/setupVars.conf`
`/etc/pihole/local.list`

**Comment by PromoFaux** [comment]
I'd say this is not really a bug as such. Whilst we _could_ constantly monitor for a change in local IP address, it seems a rather unnecessary step, as the IP should really be static.

Whilst I appreciate that sometimes you may need to change your IP address to reflect changes to your network structure, the only place you need to change it for Pi-Hole is in `/etc/pihole/setupVars.conf`, then run `pihole -r` to repair the install. The alternative is to run `pihole -r` and choose `reconfigure` to update the IP address without having to edit `setupVars.conf`

**Comment by nedgeworth** [comment]
@PromoFaux That sounds fine to me! Would be nice if the debug engine at least highlighted this factor and gave the suggestion you just provided as a fix :)
