### ISSUE TITLE
Install script disables dnsmasq prior to cloning repos.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1869]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

Installer stops dnsmasq prior to git clone. Blocks if user is already using dnsmasq.

**Comment by dschaper** [comment]
#1868

**Comment by Mcat12** [comment]
Is this still an issue?

**Comment by dschaper** [comment]
I don't think so, I thought @PromoFaux fixed this in a subsequent commit and merge?

**Comment by Mcat12** [comment]
I looked through the installer and don't see this being possible any longer.

**Comment by Mcat12** [comment]
Found the commit: https://github.com/pi-hole/pi-hole/commit/0c8a32b9ae3fdada94839f065e9816a16b8c09eb
