### ISSUE TITLE
Aliased DHCP Leases display incorrectly in web interface

### ISSUE THREAD

**Issue by aphirst** [pi-hole/pi-hole#1872]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

`In the new DHCP Leases menu in the web interface, it should be possible to view, administer leases which have been manually specified in the dnsmasq config, which map multiple MAC Addresses to one IP address.`

**Actual behaviour:**

`Since the format of these leases in the config file is an extra MAC address (or more) in the comma-separated list, the Pi-Hole web interface displays the 2nd MAC address as if it were the IP Address to be assigned.`

**Steps to reproduce:**

`Add extra MAC address(es) to the DHCP lease config file manually. View the web interface.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`I'm not willing to submit this. The issue I'm reporting is obviously merely a straightforward oversight in the web interface design. No information in my log is necessary, nor is my spending the time just to make SURE that no sensitive information would get published along with it.`

**Troubleshooting undertaken, and/or other relevant information:**

`Pi-hole Version 3.2.1 Web Interface Version 3.2.1 FTL Version v2.13`

**Comment by PromoFaux** [comment]
Could you provide a screenshot, please?

**Comment by PromoFaux** [comment]
And perhaps an example of a lease set up in your DHCP config file. (Feel free to obfuscate the MAC addresses)

**Comment by aphirst** [comment]
![a](https://user-images.githubusercontent.com/1735556/34329238-0d62f83e-e8f0-11e7-9a46-0dbb1df00a4f.png)
```
dhcp-host=00:**,192.168.0.2,al*
dhcp-host=00:**,192.168.0.3,od*
dhcp-host=B8:**,192.168.0.4,li*
dhcp-host=3C:**,6C:**,192.168.0.5,sh*
dhcp-host=84:**,00:**,192.168.0.6,ra*
dhcp-host=C0:**,192.168.0.7,pi*
dhcp-host=B8:**,192.168.0.10,al*
```

**Comment by dschaper** [comment]
I've tagged this a a Feature Request because it's not quite a bug, `dnsmasq` still functions and will set the IP correctly, it's just displayed incorrectly on the web interface.

**Comment by jacobsalmela** [comment]
Moving this to Discourse so it is votable: https://discourse.pi-hole.net/t/aliased-dhcp-leases-display-incorrectly-in-web-interface/8759

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/aliased-dhcp-leases-display-incorrectly-in-web-interface/8759/1
