### ISSUE TITLE
Exclude certain domains in Query Log

### ISSUE THREAD

**Issue by Kiritzai** [pi-hole/pi-hole#1876]
This is a feature request.

Seen several topics of people asking for this feature on the internet. [Link 1](https://discourse.pi-hole.net/t/filter-out-sites-from-query-log/3843/12) and [Link 2](https://www.reddit.com/r/pihole/comments/6w0cjq/excluding_queries_also_from_graph/)
As for my situation, i've got an monitoring server running with multiple hosts connected with DNS names.
These DNS names show up in my **Query Log** which I don't want, cause it logs about 600.000 queries alone.

And of course the DNS names are already in the exlude list for the **Top Domains** and **Top Blocked Domains** but now I wish to see it disappear on my **Query Log**.

Thanks in advance and we hope to see this feature in the future.

**Comment by dschaper** [comment]
(From the template that you deleted before you typed your post)

* Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

**Comment by davekr8** [comment]
I would also prefer to have such a "first stage" of ignoring requests for logging. I have one client in my lan which causes in the order of 1-2 magnitudes more requests than I have with my normal interactive internet use via browser or android apps. The scale of the graph does not permit a visual inspections as there are several peekt with extraordniary height from this clients.

What about a switch for logarithmic vertical scale?! Worth a feature request?

**Comment by jacobsalmela** [comment]
I think the feature request you linked to is basically asking what you want.  I would vote it up there since that's where we track all of our feature requests.

https://discourse.pi-hole.net/t/filter-out-sites-from-query-log/3843
