### ISSUE TITLE
Websites takes long time to load

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1879]
I found two prominent German websites that take ages for loading on mobile Chrome because of blocked content. I guess you can easily find more websites with the same problem. I tested it on multiple devices to exclude problems on a device. 

As it turns out Chrome waits for pending content before it displays/renders the site. Since the content is blocked it waits till it runs into timeout before displaying the site. On mobile chrome the timeout is very long so you can wait 1-2 min. I encountered the same problem on Chrome for desktop but the timeout is very short so it is not that severe. 

This might be a problem of the mobile chrome browser but since it only occurs if website content is blocked I think you need to try to find a workaround for it. Maybe send a 404 header back for blocked content so that the browser is not waiting for it?

![heise de](https://user-images.githubusercontent.com/1503577/34454340-b49efb70-ed69-11e7-8bbb-c7cd1b3cc489.png) In this picture you can see that there is still pending content and the preview is misleading since I don't see any rendered content on the mobile yet.

**Comment by davekr8** [comment]
the domains in the marked lines would be helpful.

**Comment by jwillmer** [comment]
Test website url: `https://www.heise.de/newsticker/`
Some of the script urls: [iam.js](https://script.ioam.de/iam.js), [gpt.js](https://www.googletagservices.com/tag/js/gpt.js), [trg.gif](https://www1.mpnrs.com/deliver2/trg/trg.gif?lv=9&tad=13f0kjf8mps0)

**Comment by Mcat12** [comment]
Have you checked out this resource? https://discourse.pi-hole.net/t/why-do-some-sites-take-forever-to-load-when-using-pi-hole/3654

**Comment by jwillmer** [comment]
It seams like the problem but adding the two commands to my pi-hole installation does solve the issue. Does it take time to populate or do I need to restart pi-hole first?

**Comment by jwillmer** [comment]
Current related thread at discourse.pi-hole.net is https://discourse.pi-hole.net/t/unable-to-add-http-iptables-rules/6271

**Comment by technicalpyro** [comment]
might also be worth looking into this resource as well [Link](https://www.reddit.com/r/pihole/comments/7iw49j/fixing_slow_page_loads_piholehttps_by_enabling/)

**Comment by jwillmer** [comment]
I think that this requires too much work and as I have a DS-Lite connection I can't be reached by IPv4 to establish a SSL cert. 

Unfortunately I can't use pi-hole as long as it is causing problems connecting to (many) websites. I have now disabled the blocker functionality till pi-hole fixes the problem.

**Comment by dschaper** [comment]
It's an issue on a different level than we have access to. I'm sorry you are unable to use the project, and we value the feedback.

**Comment by dschaper** [comment]
Since this has a discourse discussion already it's better to keep it there so I'll close out this issue here.

**Comment by jwillmer** [comment]
> It's an issue on a different level than we have access to. I'm sorry you are unable to use the project, and we value the feedback.

How is this a different level? If I'm installing pi-hole and it does not work for websites with SSL it is a problem/bug of pi-hole. Not fixing it seams like not an option since at some point all ad servers will have SSL. Isn't there any plan to support blocking SSL? @dschaper

**Comment by DL6ER** [comment]
> Isn't there any plan to support blocking SSL?

In the standard scenario it "just works" (I'll explain why in a second) so there has to be something specific with your Pi-hole installation.

What does happen when you query something that contains SSL content?
1. The browser resolves the domain, e.g. `cdn.mxpnl.com`
2. The Pi-hole responds with its own IP address, e.g. `10.8.0.10`
3. The browser tries to connect to `10.8.0.10:443` to download the HTTPS content

What does usually happen?
There will be nothing listening on the Pi-hole on this port and hence the kernel will `REJECT` the request. Your Chrome browser will immediately see that the request failed and will continue without it.

What seems to happen for you?
Well, something prevents the browser from getting a `REJECT` message and it keeps waiting forever for the content to arrive. There are various reasons where this may come from, but the two most likely are:
1. You set up a firewall on your Pi-hole and there is a rule that will lead to `DROP`ing of packets on port 443
2. Your IP address may be set incorrectly on the Pi-hole, so the Pi-hole responds with an IP address that does not exist on your network and hence the request cannot be rejecteded either (as there is nobody that is able to send such a `REJECT` packet).

Let's continue on Discourse...

**Comment by dschaper** [comment]
>  Isn't there any plan to support blocking SSL?

We aren't going to start generating self-signed certifications, no. TLS requires authority in the chain, and unless you have a TLS cert from a CA that the browser recognizes then things will break in even more confounding ways.

**Comment by jwillmer** [comment]
Thx @DL6ER for the summary. Based on your description I noticed that a different IPv6 DNS server is broadcasting in my network but I could not figure out who. After some research it turns out that the `Router Advertisement Server` option not only provides my network public IPv6 addresses but also the IPv6 DNS server of my ISP. 

At the moment I actually don't know how to fix this. I like to have public IPv6 addresses for my network devices but I also like to block the external IPv6 DNS server. Any idea?

**Comment by DL6ER** [comment]
Unfortunately, that is a problem I have no solution found for yet. Let me summarize the outcomes of my private research concerning DNSv6 shortly below.

At home: ISP `Deutsche Telekom`, router is ISP provided `Speedport W 723V`
Luckily, this router does not fully understand IPv6 as it is sending around all required IPv6 data but *no* ISP provided DNS server. However, I'm aware that they can remotely update this router so I could get into trouble at any time.
![screenshot at 2018-01-07 17-06-37](https://user-images.githubusercontent.com/16748619/34651195-3e2a5722-f3cd-11e7-8add-aa5da9f6b7f6.png)

At my parent's home: ISP `Deutsche Telekom`, router is ISP provided (some newer model than mine)
This router also sends out IPv6 DNS information to the clients. I haven't found a solution as of now else than overwriting the IPv6 information on all devices that can do it (luckily they use Ubuntu on their computers and laptops).
![screenshot at 2018-01-07 17-10-29](https://user-images.githubusercontent.com/16748619/34651254-13203de8-f3ce-11e7-89dc-ad7660d1edb1.png)

Let me know if you can come up with a solution!

**Comment by darkrain-nl** [comment]
What you see in the second trace is RDNSS doing it's job, with some routers you can turn off RDNSS. 
The only thing your router should advertise is it's IPv6 prefix, you can then let PiHole's dnsmasq do the rest based on that prefix. 
But to know for sure I would like to see what configuration options you have on your router for IPv6. (please don't give us your complete IPv6 prefix, better to mask them like above...)

**Comment by DL6ER** [comment]
@darkrain-nl For me there are zero IPv6 configuration options on the router - it is a very simple model...
One of the only things that can be done is disabling the DHCP server but obviously that does not affect any IPv6 settings at all.

**Comment by darkrain-nl** [comment]
@DL6ER True and you don't want to turn things off completely as that would also disable the prefix delegation...

**Comment by jwillmer** [comment]
I have a DrayTek Vigor 130 that works well as modem and router with `Deutsche Telekom` but I could not find an option to block/disable `RDNSS`. I can only enable/disable the `RADVD` (Router Advertisement Server). I have however access to a DD-WRT Router and maybe I can offload the routing part from the DrayTek to this dedicated router - maybe DD-WRT can provide this option.
