### ISSUE TITLE
index & queries bug

### ISSUE THREAD

**Issue by kemalozturkblog** [pi-hole/pi-hole#1883]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

**5**

---
**Expected behaviour:**

the operation of the counters on the main page and the receipt of the query page

**Actual behaviour:**

With the last update I made, the homepage and query page are not working.

I tried pi-hole repair. (transaction completed, but no changes)

![index.php](http://imgim.com/screenshot_20171230-234659.png)

![queries.pgp](http://imgim.com/screenshot_20171230-234704.png)

**Steps to reproduce:**

Install the minimal version of ubuntu 16.04. update the system. pi-hole and switch to pi-hole developer version.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`7307k87j5b`

**Troubleshooting undertaken, and/or other relevant information:**

the operating system and the pi-hole were re-installed. He did not improve.

**Comment by Mcat12** [comment]
I've added the issue template back to your post. Please fill it out:
> You must follow the template instructions. Failure to do so will result in your issue being closed.

**Comment by DL6ER** [comment]
I assume logging is disabled on your system, can that be the case? Please check if you can enable it on the Settings page.

**Comment by kemalozturkblog** [comment]
@DL6ER

query log is active, did not work after daily cleaning. but you can understand that it does not work without daily cleaning.

pi-hole stable transition. Shuan is working but the developer version is not working.

**Comment by Mcat12** [comment]
Please make a new debug token (they expire after 48 hours). Are you running a development version of Pi-hole?

**Comment by kemalozturkblog** [comment]
I reinstalled the developer version. the query log is still loading.

Debug token: pkf7xig5li

**Comment by kemalozturkblog** [comment]
I reinstalled the developer version. the query log is still loading.

Debug token: pkf7xig5li

**Comment by DL6ER** [comment]
When you check out the development version, you also have to use the development binary of `FTL`
```
sudo pihole checkout ftl development
```
as there is a breaking change in `FTL`s `development` branch

**Comment by kemalozturkblog** [comment]
home page it works. the query page is still not working.

**Comment by kemalozturkblog** [comment]
the problem may be turned off. The query page does not work because of the browser cache.
