### ISSUE TITLE
How to define DNS server order?

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1884]
I like to use Quad9 servers and only add Google as a fallback. The web interface has no option to define an DNS server order.

**Comment by DL6ER** [comment]
It is neither possible to define an order nor part of the DNS standard. The first queries will always be sent out to all servers and later on the queries are only ever sent to the servers that responded fastest.

**Comment by jwillmer** [comment]
Ah, OK, perfect. Maybe a hint in the UI would be great.
