### ISSUE TITLE
Settings > Block Lists > Save (not update) removes feedback on blockscreen

### ISSUE THREAD

**Issue by davekr8** [pi-hole/pi-hole#1892]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
6
---
**Expected behaviour:**
Save button will not change the response of the system.

**Actual behaviour:**
The response is modified.

**Steps to reproduce:**
Change (delete entry from) the blocklist, save instead of save and update, and request domain from the deleted list. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
N/A

**Troubleshooting undertaken, and/or other relevant information:**
Remove the save only button or force the user to update the lists, when leaving the page (apply when leaving).

Result: deleting w/o update.
![after_deleting_save_only](https://user-images.githubusercontent.com/12131511/34554786-e995ff68-f12e-11e7-85e4-18ab5b4d0587.PNG)

Result: deleting with update, as expected.
![after_deleting_with_update_expected](https://user-images.githubusercontent.com/12131511/34554785-e97ae55c-f12e-11e7-8e37-f9b38fd6ea38.PNG)

**Comment by Mcat12** [comment]
I guess this is expected then. The non-update save function is there with the intention that the user runs the update when they're done configuring the block lists. Maybe this should be made more explicit.

**Comment by davekr8** [comment]
maybe supressing an empty line would be a first step. or a message, that list are changed but not updated. ok in general this issue is quite latent, as there are outmatic updates and then the system and output is in line again. but, i was somehow confused, what is the actual blocklist state.

**Comment by DL6ER** [comment]
> Maybe this should be made more explicit.

I agree. We have something similar on the `Audit log` but there we have an explicit note that the user will have to apply for the changes to become effective.

**Comment by dschaper** [comment]
Fixed in #1943
