### ISSUE TITLE
Playstore App Download Issue

### ISSUE THREAD

**Issue by Ang3er** [pi-hole/pi-hole#1893]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

`Playstore Download off Apps on Andorid Smartphones (several are problematic currently)`

**Actual behaviour:**
Currently it is not possible to download anyapps via the Goolge Playstore. I was able to isolate the problem to pihole, as without everything works as expected. Unfortanatly the log does not show anything, which indicates a blocking of Pihole regarding Google Playstore. My current workaround is to disable Pihole for 5 minutes and perform my updates.
``

**Steps to reproduce:**

`no Idea`

Thanks in advance

**Comment by terminator9999** [comment]
So, the steps to reproduce is to install pihole, configure your device/router to use Pihole as a DNS resolver and then use Playstore through your smartphone? ;)

**Comment by Mcat12** [comment]
Have you added extra blocking lists? Unfortunately I don't think any of the devs have been able to successfully reproduce this issue.

**Comment by Ang3er** [comment]
Hi there,

all running block lists (eg. Fritzbox) are disabled and rights are given to all users. In PiHole itself i only blackholed
single:
9cache.com
9gag.com
9gag.tv
adservice.google.de
analytics.plex.tv
bild.de
clients6.google.com
connect.facebook.net
i1.ytimg.com
r1---sn-vgqsen7z.googlevideo.com
r1.sn-vgqsen7z.googlevideo.com
r17---sn-vgqsenes.googlevideo.com
r2---sn-vgqs7n7k.googlevideo.com
r20---sn-vgqs7ne7.googlevideo.com
r20.sn-vgqs7ne7.googlevideo.com
r4---sn-vgqs7nez.googlevideo.com
r4.sn-vgqs7nez.googlevideo.com
support.plex.tv
thersurvey.com
www.thersurvey.com
www.youtube-nocookie.com
youtube-ui.l.google.com

and wildcard:
cn
gvt1.com
lk
ru
tk

These should not effect the google Playstore.
Iam think about something like Pihole is not reacting fast enough for the playstore, therefore it thinks it gets a timeout. If i disable Pihole via its menü its working just fine.

Thanks in advance, and pls tell me if some more information is needed.

**Comment by DL6ER** [comment]
> Unfortanatly the log does not show anything, which indicates a blocking of Pihole regarding Google Playstore.

What do you mean by "the log"? The Query Log page or did you look manually into `/var/log/pihole.log`?

> Iam think about something like Pihole is not reacting fast enough for the playstore, therefore it thinks it gets a timeout. If i disable Pihole via its menü its working just fine.

No, this cannot be the case as it is working for you with disabled blocking. Note that when you click *disable*, the Pi-hole will in fact still be fully enabled but only ads are not blocked any more.

I think you should do the following. On the dashboard, there is a `Tail pihole.log` function (look under `Tools`). Run the app once with Pi-hole enabled and once with disabled. Compare the results (there *has* to be a difference). Note that this is much more powerful as lots of things get filtered and not displayed at all in the `Query Log` (like `PTR` requests and therelike).

**Comment by davekr8** [comment]
gvt1.com is a google one...

**Comment by anudeepND** [comment]
@Ang3er I've been facing similar issue when  connected to internet via OpenVPN, I have tried both UDP and TCP with different ports but no luck. Refer this [list](https://github.com/anudeepND/whitelist) for commonly whitelisted domains.

**Comment by jacobsalmela** [comment]
Closing due to no response.

**Comment by piLinux** [comment]
I think this problem should be fixed. So I am opening the issue again.

Steps to reproduce the problem:

- Configure OpenVPN to use only the DNS to create this problem.

`sudo nano /etc/openvpn/server.conf
`
```
#push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 10.8.0.1"
```

- If OpenVPN is configured to use as a full VPN, then no problem arises.

`sudo nano /etc/openvpn/server.conf
`
```
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 10.8.0.1"
```

- If only OpenVPN is used (no pi-hole), then also no problem occurs.

`sudo nano /etc/openvpn/server.conf
`
```
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
```
