### ISSUE TITLE
Accessing web interface via hostname blocked

### ISSUE THREAD

**Issue by qwertymodo** [pi-hole/pi-hole#1896]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Accessing the web interface via hostname (in my case, http://pihole.qwertymodo.lan/admin) should bring up the same page as I get when accessing it via IP address

**Actual behaviour:**

Access to the following website has been denied:
  *pihole.qwertymodo.lan*

This is primarily due to being flagged as:
  *Not found on any Blacklist*

**Steps to reproduce:**

-Install pi-hole into a fresh Ubuntu 16.04 VM
-Confirm that everything is working (including accessing the web interface via IP address)
-Attempt to access the web interface via hostname (with LAN suffix)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

20km5qpxkr

**Troubleshooting undertaken, and/or other relevant information:**

-Added qwertymodo.lan to the whitelist
-Flushed the cache with pihole restartdns
-Tried in multiple browsers

**Comment by Mcat12** [comment]
It looks like your hostname as specified in `/etc/hostname` is `pihole` (at least it was the last time gravity was run). The web interface only allows a certain few hosts to access it, including `pi.hole`, the IP addresses Pi-hole was set to use, and the hostname of the Pi-hole as specified in `/etc/hostname`. If you don't connect via one of those hosts, it won't show the web interface.

**Comment by qwertymodo** [comment]
I've edited my /etc/hostname to pihole.qwertymodo.lan, run pihole restartdns, and even restarted the whole VM to confirm that the hostname change stuck, and it's still occurring.  I also cleared my browser cache to ensure it wasn't a client-side issue.  Still getting the same issue.

**Comment by PromoFaux** [comment]
look at `/etc/pihole/local.list` before and after running `pihole -g`. Once you run `pihole -g` you should find that the hostname in `/etc/hostname` is now in `/etc/pihole/local.list`

**Comment by qwertymodo** [comment]
That worked, but oddly only for pihole.qwertymodo.lan/admin/ if I forget to add /admin/ at the end, I still get the block screen instead of the pihole splash screen.  So, that's weird, but I guess I can at least get in.

**Comment by Mcat12** [comment]
The shortcut of not adding the `/admin` on is only available if you go through the `pi.hole` host: http://pi.hole/

**Comment by PromoFaux** [comment]
Yeah, the redirect is in the block page itself. It will only redirect to `/admin` [if you are using `pi.hole`])https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L58)

**Comment by enlacee** [comment]
![raspberrypizero local](https://user-images.githubusercontent.com/179639/107062481-58af1280-67a7-11eb-9f95-2e8315d453ac.png)
THATS! RIGHT i cant access to my local hostname by browser: http://raspberrypizero.local
I can't understand why this happens
I have review all file list and it is not

**Comment by arifer612** [comment]
@enlacee Maybe you should try http://raspberrypizero.local/admin as what @PromoFaux above. If you do not include the `/admin` the page will redirect to a block page.
