### ISSUE TITLE
Resolve local network hosts wenn using DHCP

### ISSUE THREAD

**Issue by macsip** [pi-hole/pi-hole#1898]
It would be great to have an option to activate the local hosts resolution wenn the DHCP of the pi-hole is active.

For exemple:
Hostname "imac" should be reachable via imac.pi.hole

**Comment by Mcat12** [comment]
This is already the case. Next time please fill out the issue template if you make an issue, or if you want to make a feature request make it on Discourse so others can vote: https://discourse.pi-hole.net/c/feature-requests
