### ISSUE TITLE
Norton DNS - IPv4 not reachable

### ISSUE THREAD

**Issue by thexmanxyz** [pi-hole/pi-hole#1899]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
---
**Expected behaviour:**
Both Norton Upstream DNS Servers for IPv4 should be reachable. DNS name in the Pi Hole Webinterface should be resolved => "Dashboard/Forward Destinations".

**Actual behaviour:**
Both Norton Upstream DNS Servers aren't reachable, at least for my ISP. Austria - A1/Drei. I noticed that the Norton DNS Upstream Server IP Addresses are not getting resolved in the Pi Hole Web Interface ("Dashboard/Forward Destinations") to the correct DNS name. It just shows the IP Address. It seems that either the IP changed or the DNS is not available anymore.

**Steps to reproduce:**
I tried to reach both of the Norton DNS Server IPv4 addresses. Non of the following requests completed with an answer:
- restarted Router + pi.hole
- `ping 199.85.126.10 -t`
- `nslookup 199.85.126.10`
- `ping 199.85.127.10 -t`
- `nslookup 199.85.127.10`
- verified behaviour and steps above over my mobile provider. Same result.

**Comment by DL6ER** [comment]
They are operational for me (ISP Deutsche Telekom)
```
$ dig +short google.de @199.85.126.10
172.217.22.195
$ dig +short google.de @199.85.127.10
216.58.214.35
```

However, they don't have associated host names (both `PTR` requests return `NXDOMAIN`).

Please check again if they are still not available for you. I'll close this issue now as this doesn't seem to be a Pi-hole issue.

**Comment by thexmanxyz** [comment]
@DL6ER Sorry for bugging you're totally right, checked again in VM with `dig` and I also got a response. `nslookup` won't work because of `NXDOMAIN` additionally the server(s) simply do not allow ping. All other default ones however do so I thought it isn't available. However thanks for clarification and help. At least I learned something :).
