### ISSUE TITLE
Unable to resolve DNS on different network

### ISSUE THREAD

**Issue by vanderblugen** [pi-hole/pi-hole#1902]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**  1

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Unable to resolve on a different subnet.

`{A detailed description of what you expect to see}`

**Actual behaviour:**

Unable to resolve DNS from the other subnet

My apologies, I am sure that this is going to be really wordy.  

I have a PiHole configured on a 192.168.3.x subnet and several other devices on different networks (192.168.4.x and 192.168.5.x) configured on a Ubiquiti EdgerouterX.  I am able to pull the DNS queries from a device on the same subnet that the PiHole is on.  

I can ping the PiHole  from the other networks and I can use nmap to verify that the ports aren't being blocked.  I run this from each of the networks to the PiHole and vice versa .  All DNS configuration appears to be in order, but am unable to pull the DNS queries from 192.168.4x and 192.168.5.x.

**Steps to reproduce:**

Listed above

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`ovzz717f7n`

**Troubleshooting undertaken, and/or other relevant information:**

Gone thru the configuration on the router and made sure that everything checks out.  Actually I have reddit post on this same issue, double checking the configuration of the router at https://redd.it/7p457d

`{Steps of what you have done to fix this}`

**Comment by technicalpyro** [comment]
for the devices not on the same subnet you need to configure the subnet mask so the devices can see them.  you have two ways of doing this.  

1.  keep your current addresses and set the subnet mask to be 255.255.0.0 this will allow your clients to see each other

2.  change the private addressing scheme you are using.  use 172.16.0.x and 172.16.1.x the different IP addresses used in this method by default use different subnetting masks

**Comment by vanderblugen** [comment]
Oh.  So it's not necessarily a limitation of the PiHole.  I assumed that since I was able to Ping the IPs and the open Ports that I would be able to pull the information.  It's more of a subnet issue or possibly even a DNS forwarding thing.

**Comment by technicalpyro** [comment]
its a network separation issue more than a pihole issue subnets are often used to sequester networks and that is what your router is doing 

you have the two options above to work around it
