### ISSUE TITLE
Installing OpenVPN on an existing Pi-Hole system

### ISSUE THREAD

**Issue by hornjt75862** [pi-hole/pi-hole#1903]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Have not started the install

**Actual behaviour:**

Pi-Hole system using OpenVPN

**Steps to reproduce:**

NA

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

NA
**Troubleshooting undertaken, and/or other relevant information:**
NA

I've gone through the articles concerning installing Pi-Hole and a VPN server and it seems the best way to proceed is to first install the VPN service, then install Pi-Hole. I have already installed Pi-Hole and it is working, but now want to either install OpenVPN or PiVPN and was wondering if I could install either one of them without having to re-install Pi-Hole.

**Comment by Mcat12** [comment]
You can install them without having to reinstall Pi-hole. You'll just need to make sure to reconfigure Pi-hole to use the tun0 interface via `pihole -r`

**Comment by jacobsalmela** [comment]
Yeah, `pihole -r` will do the trick.  Were you following our guide in the wiki?  

https://github.com/pi-hole/pi-hole/wiki/Pi-hole---OpenVPN-server

I'll close this since the thread is a bit stale, but re-open if you're still having problems.
