### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by denandz** [pi-hole/pi-hole#1905]
Hiya, 

I've discovered some vulnerabilities in the Pihole, AdminLTE and FTL projects. Can you please confirm a security contact so I can report the vulnerabilities? If you'd prefer GitHub issues instead of a private channel that works for me too.

**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**Comment by Mcat12** [comment]
Send us an email at adblock@pi-hole.net

**Comment by dschaper** [comment]
Being resolved via email.
