### ISSUE TITLE
Static DHCP items aren't in DNS unless DHCP hands out a lease

### ISSUE THREAD

**Issue by clickwir** [pi-hole/pi-hole#1906]
I've covered this here: https://www.reddit.com/r/pihole/comments/7okbfy/dhcp_static_lease_thats_not_handed_out_wont/

This doesn't seem to be working properly or as one would expect. 

I was able to work around this by grabbing all the entries from the DHCP file, adding another list file and dnsmasq file telling it to include the list file. Seems silly to have to do all that for something that kind of makes sense that if I put in an entry, it should resolve.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
