### ISSUE TITLE
installing pihole error

### ISSUE THREAD

**Issue by Alkymia** [pi-hole/pi-hole#1907]
Trying to install pi hole onto a recent clean install on my raspberry pi 3 gets me this (without having web admin interface, nor able to use even pihole uninstall) while installing php-common it stops the install process 

![](https://discourse.pi-hole.net/uploads/default/original/2X/3/3f07c6a809a51e5def490ad9376f6816b42de0aa.png)

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
