### ISSUE TITLE
DNS Crypt is no longer valid

### ISSUE THREAD

**Issue by naveensrinivasan** [pi-hole/pi-hole#1911]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

The instructions to setup dnscrypt should be valid

**Actual behaviour:**

The https://download.dnscrypt.org/ site is down and cannot be reached.

**Steps to reproduce:**

Follow the instructions for dnscrypt

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not applicable

**Troubleshooting undertaken, and/or other relevant information:**

https://twitter.com/jedisct1/status/928942292202860544

**Comment by dschaper** [comment]
Are you refering to https://github.com/pi-hole/pi-hole/wiki/DNSCrypt ? That's a public wiki entry that anyone can edit. Feel free to make any changes you wish.

**Comment by rewardone** [comment]
I have written [instructions for DNSCrypt-Proxy 2.0](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0) on Debian. The instructions should be the same when using the ARM prebuilt-binary. This uses jedisct1's DNSCrypt-Proxy 2.0 which seems to be under active development. His tweet suggests abandoning 1.9.x support in favor of 2.0.
