### ISSUE TITLE
Do I need a second DNS address on my router?

### ISSUE THREAD

**Issue by Smultie** [pi-hole/pi-hole#192]
I read http://pi-hole.net/faq/can-i-set-the-pi-hole-to-be-the-dns-server-at-my-router-so-i-dont-have-to-change-settings-for-my-devices/ and I see you advise people to only enter the first IP address.
But; what happens when your RPi has crashed? Will it disable all DNS queries on your complete network?

**Comment by PromoFaux** [comment]
I personally would put the secondary DNS server in, in case my RPi goes down, although my router only has the option to put in one.

**Comment by dschaper** [comment]
You can try with both configurations and see which one you like best. Having the backup (Google, OpenDNS or your ISP) can help out if the Pi does crash, but you'll be getting ads if the resolvers fail over to using the backup DNS servers. (That may be a secondary way of knowing your Pi has crashed.)

**Comment by gh0stshell** [comment]
I use both but Pi is primary and I use a more advanced firewall then most so I can specify when the primary fails a certain number of times it will failover to my secondary, I use both and have noticed on SOHO routers it switches back and forth sometimes and is not consistant

**Comment by dschaper** [comment]
Yes, it depends on if the router is running something like `dnsmasq` with a hierarchical lookup for resolvers, or a round-robin style lookup scheme. Another situation that requires a bit of automagic...

**Comment by jacobsalmela** [comment]
Yes, if the Pi-hole crashes and is the only DNS server set, your network will stop functioning.  In my experience, more ads got through when I had secondary and tertiary server set in the router (but then I am completely dependent on the Pi-hole working, which hasn't been a problem for me).

I guess it comes down to preference.

**Comment by dschaper** [comment]
Note: This probably should be a WIki entry. (I'll get around to it, but documentation is not my favorite thing to do, but it's good practice for learning the Markdown language.)

**Comment by jacobsalmela** [comment]
Haha I don't think documentation is anyone's favorite. =)

**Comment by DonLexos** [comment]
But to add these some are quite easy to do. I am not that good in writing code but I might be able to help out with the documentation. Do you prefer the github wiki or the pi-hole.net FAQ for things like this? I noticed some others already started filling the wiki, I have to see how the github wiki works exactly but after that I should be able to help.

**Comment by Mcat12** [comment]
We are thinking of moving documentation to the wiki instead of the website. The wiki is open for anyone to edit. It's formatted the same as here, with markdown.

**Comment by DonLexos** [comment]
Right now on the right hand side there are a few items. Is there a way to order them or nest them, or will they be sorted alphabetically always? I need to learn a bit more on the github itself to fully understand how some things work but I can easily help out on moving things (knowledge) over from the issues into wiki articles if that helps.

**Comment by PromoFaux** [comment]
I'm not enitrely sure, but they have a guide :) https://help.github.com/articles/about-github-wikis/

**Comment by PromoFaux** [comment]
It looks like you do it by editing the custom side bar...

**Comment by DonLexos** [comment]
Yes exactly, move stuff over from the pages tab and then you can do whatever you like..  Thanks for the link, it apears to be quite easy to setup.

**Comment by Mcat12** [comment]
Can this be closed?

**Comment by PromoFaux** [comment]
I think it's been left open as a reminder to so the wiki page for it!

**Comment by Mcat12** [comment]
I added it at the bottom of [Getting Started](https://github.com/pi-hole/pi-hole/wiki/Getting-Started).

**Comment by PromoFaux** [comment]
In which case...
