### ISSUE TITLE
DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by exomarty** [pi-hole/pi-hole#1924]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
To work 💃 

**Actual behaviour:**
DNS resolution is currently unavailable

**Steps to reproduce:**

Trying to Update list of ad-serving domains / blacklist / whitelist on web admin i get message DNS resolution is currently unavailable

**My setup**

Using synology docker and pihole version 3.2.1
Was using 2.13.2 and it works perfect without any issue
Tried to edit /etc/resolf.conf with nameserver 127.0.0.1 but no luck

**Debug**

<details>
<summary>Token: 9obyvqafj8</summary>
<pre>
This process collects information from your Pi-hole, and optionally uploads it to a unique and random directory on tricorder.pi-hole.net.

The intent of this script is to allow users to self-diagnose their installations.  This is accomplished by running tests against our software and providing the user with links to FAQ articles when a problem is detected.  Since we are a small team and Pi-hole has been growing steadily, it is our hope that this will help us spend more time on development.

NOTE: All log files auto-delete after 48 hours and ONLY the Pi-hole developers can access your data via the given token. We have taken these extra steps to secure your data and will work to further reduce any personal information gathered.

*** [ INITIALIZING ]
[i] 2018-01-20:02:30:45 debug log has been initiated.

*** [ INITIALIZING ] Sourcing setup variables
[i] Sourcing /etc/pihole/setupVars.conf...

*** [ DIAGNOSING ]: Core version
[i] Core: v3.2.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v3.2.1-0-ge602008-dirty

*** [ DIAGNOSING ]: Web version
[i] Web: v3.2.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v3.2.1-0-g31dddd8

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v2.13.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)

*** [ DIAGNOSING ]: dnsmasq version
[i] 2.72

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.35

*** [ DIAGNOSING ]: php version
[i] 5.6.30

*** [ DIAGNOSING ]: Operating system
[✓] Debian GNU/Linux 8 (jessie)

*** [ DIAGNOSING ]: SELinux
[i] SELinux not detected

*** [ DIAGNOSING ]: Processor
[i] x86_64

*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   172.17.0.2/16 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

[✓] IPv6 address(es) bound to the eth0 interface:
   fe80::42:acff:fe11:2 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   fe80::242:ac11:2 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

   ^ Please note that you may have more than one IP address listed.
   As long as one of them is green, and it matches what is in /etc/pihole/setupVars.conf, there is no need for concern.

   The link to the FAQ is for an issue that sometimes occurs when the IPv6 address changes, which is why we check for it.

[i] Default IPv4 gateway: 172.17.0.1
   * Pinging 172.17.0.1...
[✓] Gateway responded.
[i] Default IPv6 gateway: fe80::1
   * Pinging fe80::1...
[✓] Gateway responded.

*** [ DIAGNOSING ]: Ports in use
[53] is in use by dnsmasq
[80] is in use by lighttpd
[4711] is in use by pihole-FTL

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] lsda.carpediem.fr is 192.168.1.10 via localhost (127.0.0.1)
[✗] Failed to resolve lsda.carpediem.fr via Pi-hole (192.168.1.10)
[✓] doubleclick.com is 216.58.201.142 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Pi-hole processes
[✗] dnsmasq daemon is 
[✗] lighttpd daemon is 
[✗] pihole-FTL daemon is 

*** [ DIAGNOSING ]: Setup variables
    QUERY_LOGGING=true
    INSTALL_WEB=true
    LIGHTTPD_ENABLED=
    DNSMASQ_LISTENING=single
    PIHOLE_DNS_1=8.8.8.8
    PIHOLE_DNS_2=8.8.4.4
    DNS_FQDN_REQUIRED=true
    DNS_BOGUS_PRIV=true
    DNSSEC=true
    IPV4_ADDRESS=192.168.1.10
    IPV6_ADDRESS=
    PIHOLE_INTERFACE=eth0

*** [ DIAGNOSING ]: Dashboard and block page
[✓] X-Pi-hole: A black hole for Internet advertisements.
[✓] X-Pi-hole: The Pi-hole Web interface is working!

*** [ DIAGNOSING ]: Gravity list
-rw-r--r-- 1 root root 3928785 Jan 20 01:58 /etc/pihole/gravity.list
   -----head of gravity.list------
   192.168.1.10 0.0.0.0
   192.168.1.10 0.r.msn.com
   192.168.1.10 0.start.bz
   192.168.1.10 0000mps.webpreview.dsl.net

   -----tail of gravity.list------
   192.168.1.10 zzsyw.com
   192.168.1.10 zztxdown.com
   192.168.1.10 zzz.clickbank.net
   192.168.1.10 ɢoogle.com

*** [ DIAGNOSING ]: contents of /etc/pihole

-rw-r--r-- 1 root root 633 Jan 20 01:58 /etc/pihole/adlists.list
   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
   https://mirror1.malwaredomains.com/files/justdomains
   http://sysctl.org/cameleon/hosts
   https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
   https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
   https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
   https://hosts-file.net/ad_servers.txt

-rw-r--r-- 1 root root 50 Jan 20 01:58 /etc/pihole/local.list
   192.168.1.10 diginc-pi-hole1
   192.168.1.10 pi.hole

-rw-r--r-- 1 root root 234 Jan  5 06:25 /etc/pihole/logrotate
   /var/log/pihole.log {
   	su root root
   	daily
   	copytruncate
   	rotate 5
   	compress
   	delaycompress
   	notifempty
   	nomail
   }
   /var/log/pihole-FTL.log {
   	su root root
   	weekly
   	copytruncate
   	rotate 3
   	compress
   	delaycompress
   	notifempty
   	nomail
   }

-rw-r--r-- 1 root root 0 Jan 20 01:58 /etc/pihole/whitelist.txt

*** [ DIAGNOSING ]: contents of /etc/dnsmasq.d

-rw-r--r-- 1 root root 1717 Jan 20 02:22 /etc/dnsmasq.d/01-pihole.conf
   addn-hosts=/etc/pihole/gravity.list
   addn-hosts=/etc/pihole/black.list
   addn-hosts=/etc/pihole/local.list
   localise-queries
   no-resolv
   cache-size=10000
   log-queries
   log-facility=/var/log/pihole.log
   local-ttl=2
   log-async
   server=8.8.8.8
   server=8.8.4.4
   domain-needed
   bogus-priv
   dnssec
   trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
   trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
   interface=eth0

*** [ DIAGNOSING ]: contents of /etc/lighttpd

-rw-r--r-- 1 root root 3027 Jan  5 06:25 /etc/lighttpd/lighttpd.conf
   server.modules = (
   	"mod_access",
   	"mod_accesslog",
   	"mod_auth",
   	"mod_expire",
   	"mod_compress",
   	"mod_redirect",
   	"mod_setenv",
   	"mod_rewrite"
   )
   server.document-root        = "/var/www/html"
   server.error-handler-404    = "pihole/index.php"
   server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
   server.errorlog             = "/var/log/lighttpd/error.log"
   server.pid-file             = "/var/run/lighttpd.pid"
   server.username             = "www-data"
   server.groupname            = "www-data"
   server.port                 = 80
   accesslog.filename          = "/var/log/lighttpd/access.log"
   accesslog.format            = "%{%s}t|%V|%r|%s|%b"
   index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
   url.access-deny             = ( "\~", ".inc", ".md", ".yml", ".ini" )
   static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
   compress.cache-dir          = "/var/cache/lighttpd/compress/"
   compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
   include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
   include_shell "/usr/share/lighttpd/create-mime.assign.pl"
   include_shell "find /etc/lighttpd/conf-enabled -name '*.conf' -a ! -name 'letsencrypt.conf' -printf 'include \"%p\"
' 2>/dev/null"
   $HTTP["url"] =\~ "^/admin/" {
       
       setenv.add-response-header = (
           "X-Pi-hole" => "The Pi-hole Web interface is working!",
           "X-Frame-Options" => "DENY"
       )
       $HTTP["url"] =~ ".ttf$" {
           
           setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
       }
   }
   $HTTP["url"] =~ "^/admin/\.(.*)" {
        url.access-deny = ("")
   }
   include_shell "cat external.conf 2>/dev/null"

*** [ DIAGNOSING ]: contents of /etc/cron.d

-rw-r--r-- 1 root root 1630 Jan  5 06:25 /etc/cron.d/pihole
   23 4   * * 7   root    PATH="$PATH:/usr/local/bin/" pihole updateGravity
   00 00   * * *   root    PATH="$PATH:/usr/local/bin/" pihole flush once quiet
   @reboot root /usr/sbin/logrotate /etc/pihole/logrotate
   */10 *  * * *   root    PATH="$PATH:/usr/local/bin/" pihole updatechecker local
   23 18  * * *   root    PATH="$PATH:/usr/local/bin/" pihole updatechecker remote
   @reboot root    PATH="$PATH:/usr/local/bin/" pihole updatechecker remote reboot

*** [ DIAGNOSING ]: contents of /var/log/lighttpd

-rw-r--r-- 1 www-data www-data 173 Jan 20 02:24 /var/log/lighttpd/error.log
   2018-01-20 01:58:44: (log.c.164) server started 
   2018-01-20 02:20:28: (server.c.1558) server stopped by UID = 0 PID = 3733 
   2018-01-20 02:24:42: (log.c.164) server started 

*** [ DIAGNOSING ]: contents of /var/log

-rw-r--r-- 1 root root 6795 Jan 20 02:24 /var/log/pihole-FTL.log
   [2018-01-20 01:58:44.370] 
   [2018-01-20 01:58:44.370] FTL branch: (no branch)
   [2018-01-20 01:58:44.370] FTL version: v2.13.1
   [2018-01-20 01:58:44.371] FTL tag: v2.13.1
   [2018-01-20 01:58:44.371] FTL date: 2017-12-28 07:44:48 -0800
   [2018-01-20 01:58:44.371] FTL user: root
   [2018-01-20 01:58:44.371] Warning: Starting pihole-FTL directly is not recommended.
   [2018-01-20 01:58:44.371]          Instead, use system commands for starting pihole-FTL as service (systemctl / service).
   [2018-01-20 01:58:44.371] Notice: Found no readable FTL config file
   [2018-01-20 01:58:44.371]         Using default settings
   [2018-01-20 01:58:44.371] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
   [2018-01-20 01:58:44.371]    SOCKET_LISTENING: only local
   [2018-01-20 01:58:44.371]    TIMEFRAME: Rolling 24h
   [2018-01-20 01:58:44.371]    QUERY_DISPLAY: Show queries
   [2018-01-20 01:58:44.371]    AAAA_QUERY_ANALYSIS: Show AAAA queries
   [2018-01-20 01:58:44.371]    MAXDBDAYS: max age for stored queries is 365 days
   [2018-01-20 01:58:44.371]    RESOLVE_IPV6: Resolve IPv6 addresses
   [2018-01-20 01:58:44.371]    RESOLVE_IPV4: Resolve IPv4 addresses
   [2018-01-20 01:58:44.371]    DBINTERVAL: saving to DB file every minute
   [2018-01-20 01:58:44.371]    DBFILE: Using /etc/pihole/pihole-FTL.db
   [2018-01-20 01:58:44.371] Finished config file parsing
   [2018-01-20 01:58:44.371] PID of FTL process: 449
   [2018-01-20 01:58:44.444] Gravity list entries: 109697
   [2018-01-20 01:58:44.444] No blacklist present
   [2018-01-20 01:58:44.444] No wildcard blocking list present

*** [ DIAGNOSING ]: Pi-hole log
-rw-r--r-- 1 dnsmasq root 12390 Jan 20 02:30 /var/log/pihole.log
   -----head of pihole.log------
   Jan 20 01:58:35 dnsmasq[277]: started, version 2.72 cachesize 10000
   Jan 20 01:58:35 dnsmasq[277]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
   Jan 20 01:58:35 dnsmasq[277]: using nameserver 8.8.4.4#53
   Jan 20 01:58:35 dnsmasq[277]: using nameserver 8.8.8.8#53
   Jan 20 01:58:35 dnsmasq[277]: read /etc/hosts - 7 addresses
   Jan 20 01:58:35 dnsmasq[277]: failed to load names from /etc/pihole/local.list: No such file or directory
   Jan 20 01:58:35 dnsmasq[277]: failed to load names from /etc/pihole/black.list: No such file or directory
   Jan 20 01:58:35 dnsmasq[277]: failed to load names from /etc/pihole/gravity.list: No such file or directory
   Jan 20 01:58:44 dnsmasq[277]: read /etc/hosts - 7 addresses
   Jan 20 01:58:44 dnsmasq[277]: read /etc/pihole/local.list - 2 addresses
   Jan 20 01:58:44 dnsmasq[277]: failed to load names from /etc/pihole/black.list: No such file or directory
   Jan 20 01:58:44 dnsmasq[445]: started, version 2.72 cachesize 10000
   Jan 20 01:58:44 dnsmasq[445]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
   Jan 20 01:58:44 dnsmasq[445]: using nameserver 8.8.4.4#53
   Jan 20 01:58:44 dnsmasq[445]: using nameserver 8.8.8.8#53
   Jan 20 01:58:44 dnsmasq[445]: read /etc/hosts - 7 addresses
   Jan 20 01:58:44 dnsmasq[445]: read /etc/pihole/local.list - 2 addresses
   Jan 20 01:58:44 dnsmasq[445]: failed to load names from /etc/pihole/black.list: No such file or directory
   Jan 20 01:58:44 dnsmasq[445]: bad name at /etc/pihole/gravity.list line 82247
   Jan 20 01:58:45 dnsmasq[445]: bad name at /etc/pihole/gravity.list line 109697

\********************************************
\********************************************
[✓] ** FINISHED DEBUGGING! **

    * The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
    * For more information, see: https://pi-hole.net/2016/11/07/crack-our-medical-tricorder-win-a-raspberry-pi-3/
    * If available, we'll use openssl to upload the log, otherwise it will fall back to netcat.
[i] Debug script running in automated mode
    * Using openssl for transmission.

\***********************************
\***********************************
[✓] Your debug token is: 9obyvqafj8
\***********************************
\***********************************

   * Provide the token above to the Pi-hole team for assistance at
   * https://discourse.pi-hole.net
   * Your log will self-destruct on our server after 48 hours.
   * A local copy of the debug log can be found at: /var/log/pihole_debug-sanitized.log
</pre>
</details>

**Comment by Mcat12** [comment]
Is this using @diginc's docker container?

**Comment by exomarty** [comment]
Yes @Mcat12

**Comment by Mcat12** [comment]
You should probably open an issue on that repo then: https://github.com/diginc/docker-pi-hole
