### ISSUE TITLE
gravity.sh doesn't run during install

### ISSUE THREAD

**Issue by Jonas-T** [pi-hole/pi-hole#1926]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Complete install

**Actual behaviour:**

When the gravity.sh is trying to update the block lists, during the installation, it stops working and displays "DNS resolution is currently unavailable". After the timeout the script stops. Now the pi can't resolve any DNS request.

**Steps to reproduce:**

Run install script

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

upload of log doesn't work. I uploaded the console output on pastebin https://pastebin.com/CaPZFGXA

**Troubleshooting undertaken, and/or other relevant information:**

I have tried to set the DNS server in the /etc/resolv.conf file manually, but that doesn't change anything.

**Comment by Mcat12** [comment]
What are the contents of `resolv.conf`? Also, what if you set the DNS in `resolv.conf` to `8.8.8.8`? (or another external DNS server)

**Comment by Jonas-T** [comment]
I did write a number of DNS servers in there, but they don't seem to change the behaviour.

```
#Generated by resolvconf
#GoogleDNS
nameserver 8.8.8.8
nameserver 8.8.4.4
#OpenDNS
nameserver 208.67.222.222
nameserver 208.67.220.200
nameserver 127.0.0.1

```

**Comment by Mcat12** [comment]
What is the output of `timeout 1 getent hosts raw.githubusercontent.com`?

**Comment by Jonas-T** [comment]
Nothing. It just returns to the console.

**Comment by Mcat12** [comment]
How about `dig raw.githubusercontent.com`

**Comment by Jonas-T** [comment]
It timed out

; <<>> DiG 9.10.3-P4-Raspbian <<>> raw.githubusercontent.com
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by Mcat12** [comment]
How about:
```
dig raw.githubusercontent.com @127.0.0.1
ping 8.8.8.8
```

**Comment by Jonas-T** [comment]
```
pi@raspberrypi:~ $ dig raw.githubusercontent.com @127.0.0.1


; <<>> DiG 9.10.3-P4-Raspbian <<>> raw.githubusercontent.com @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached
pi@raspberrypi:~ $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
55 packets transmitted, 0 received, 100% packet loss, time 56170ms
```

**Comment by Mcat12** [comment]
It looks like your Pi can't connect to the internet. Try fixing that first.

**Comment by Jonas-T** [comment]
It can connect to the internet before the installation. After that it stops working.

**Comment by Mcat12** [comment]
Did you put in the right gateway address?

**Comment by Jonas-T** [comment]
Is this the address of my router?

**Comment by Mcat12** [comment]
Yes

**Comment by Jonas-T** [comment]
Than I have set it correctly

**Comment by Mcat12** [comment]
Did you choose the right interface? Check `/etc/dhcpcd.conf`

**Comment by Mcat12** [comment]
Did you fix it?
