### ISSUE TITLE
Download rules via a proxy

### ISSUE THREAD

**Issue by NunoHiggs** [pi-hole/pi-hole#1930]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

For pihole download program to use the system proxy to access the internet and download rules.

**Actual behaviour:**

It does not use the system proxy settings thus not being able to download new rules

**Steps to reproduce:**

Place the pihole behind a proxy.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not able to upload

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

There is no quick fix. Only to download the lists with wget and copy them into place.

My question is:

Is there a way to configure pihole to use a proxy to download the lists form the internet? My pihole is on a secured network that does not do NAT comunication to the outside.

Thanks for your help and wonderful product!
Nuno

**Comment by Mcat12** [comment]
This is more of a feature request, so if you are still interested make a post on [Discourse](http://discourse.pi-hole.net/) in the feature requests section so other users can vote on the feature.
