### ISSUE TITLE
White- and (wildcard-)blacklisting domains for single devices

### ISSUE THREAD

**Issue by Perflyst** [pi-hole/pi-hole#1931]
This is a FeatureRequest.
I searched on the internet and found nothing to do this.

I will whitelist some domains for only one device. I have not set my pihole as my default dns in the router. I set the pihole ip adress on every single device.
Every device in my network has a fixed IP address.

Is it already possible to whitelist a single domain on a single device? If not, is it possible to add this as a feature?

For users who had not fixed IP adresses on their network, maybe you can read out the mac adress (or the user must place them during the white-/blacklisting) and realize the feature like this

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by PromoFaux** [comment]
And to make it easier for you, the important section you missed:

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
