### ISSUE TITLE
top clients l;ist has duplicates

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/pi-hole#1933]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---
**Expected behaviour:**

web interface top clients lis not have duplicates with different query numbers

**Actual behaviour:**

![2018-01-23_12-58-58](https://user-images.githubusercontent.com/24907599/35295147-f83f0f64-003d-11e8-85e3-57175b5594d4.jpg)

**Steps to reproduce:**

`{run the dev branches  past that im unsure of what i did to cause this }`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`8jgnv8mc07`

**Troubleshooting undertaken, and/or other relevant information:**

`checked hosts file potentially that is causing the issues ?`

> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/FTL #216](https://github.com/pi-hole/FTL/issues/216) via [**ZenHub**](https://www.zenhub.com/)
