### ISSUE TITLE
Admin page (and any locally served page) slows considerably.

### ISSUE THREAD

**Issue by tomose** [pi-hole/pi-hole#1934]
Re: #1917

@dschaper 

I'm not sure how you took my reply as some sort of insult or abuse. Maybe you had a bad day and took it wrong? I don't know and, to be honest, how you came to interpret a totally benign comment as abuse isn't really of any concern to the project or issue.

Regardless, it does not invalidate the bug report. I'm not worried as I now have this specific domain blocked on hosts so it's not going through pihole anymore, so that has stopped triggering the bug. But I'm sure you wouldn't want whatever bug this is to continue to exist. Good luck!

I would've contacted you guys privately but I don't see how to via github.

**Comment by PromoFaux** [comment]
@tomose moving on, and everything else aside:

> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
