### ISSUE TITLE
PiHole admin page does not show updated interface

### ISSUE THREAD

**Issue by tommyjcarpenter** [pi-hole/pi-hole#1937]
I recently switched my pihole from wifi to ethernet. I had problems for a long time where the pi would be SSHable, but DNS wasn't working properly, and finally found this post: https://www.reddit.com/r/pihole/comments/5b0ilx/pihole_set_up_on_wifi_then_changed_to_ethernet/

That led me to edit the file: 
```
/etc/dnsmasq.d/01-pihole.conf
```

The old value of interface was `wlan0` and I changed it to `etho0`. 

My internet was restored. However, when I go to the settings page of the admin, it still shows:

```

Pi-hole Ethernet Interface: | wlan0
-- | --
```

This is wrong.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
