### ISSUE TITLE
Dns reset to Google On restart Pihole

### ISSUE THREAD

**Issue by GaetanCambier** [pi-hole/pi-hole#1938]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [*] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [*] The issue I am reporting can be *replicated*.
- [*] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

Use OpenDNS on start Docker pi-hole

**Actual behaviour:**

on restart actual pihole, the DNS is reset to GoogleDNS

**Steps to reproduce:**
Just start Pihole and google dns is selected in the web-interface 
It's not just un display bug because the resolve from GoogleDNS is different than OpenDNS ;)

`{Detailed steps of how we can reproduce this}`
My docker Pyhole is based to :
Pi-hole Version vDev (development, v3.2.1-67-g535b845) 
Web Interface Version vDev (devel, v3.2.1-61-g041b0550)
FTL Version v2.13.2

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
no

**Troubleshooting undertaken, and/or other relevant information:**

no idea for the moment ...

**Comment by PromoFaux** [comment]
Hi there, is this your own docker image, or are you using the one by @Diginc ?

**Comment by GaetanCambier** [comment]
yes  i use diginc/pi-hole:debian_dev

**Comment by GaetanCambier** [comment]
ok, i find the bug : https://github.com/diginc/docker-pi-hole/issues/151
It's not a pihole bug ;)

**Comment by dschaper** [comment]
Best bet is to open a ticket with that repository. Closing this out since it's not a Pi-hole bug. But thanks for using the Pi-hole!
