### ISSUE TITLE
HTTPS website take long time to load

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1939]
I had this problem [reported in the past](https://github.com/pi-hole/pi-hole/issues/1879) and it was argued that it is a problem with my configuration. I formatted my pi and installed pi-hole on a clean image - configured it - and it worked as intended. Today we had a blackout and after the power was back on I encounter the same problem again. The blocked content runs into a timeout on load instead of getting declared canceled/offline.

Can someone suggest how to debug this problem?

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
