### ISSUE TITLE
HTTPS website take long time to load

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1940]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I had this problem [reported in the past](https://github.com/pi-hole/pi-hole/issues/1879) and it was argued that it is a problem with my configuration. I formatted my pi and installed pi-hole on a clean image - configured it - and it worked as intended. 

**Actual behaviour:**

Today we had a blackout and after the power was back on I encounter the same problem again. The blocked content runs into a timeout on load instead of getting declared canceled/offline.

**Steps to reproduce:**

I guess removing the power from the raspberry pi while it is active.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wkud9nh3nk`

**Troubleshooting undertaken, and/or other relevant information:**

- I deactivated the ad blocking to fix the issue. 
- I saw in `pihole -d` that my IPv6 does not match with the configured one. I guess this happened at reboot since my ISP is responsible for the IPv6 I can't hard code one.

**Comment by dschaper** [comment]
When you power cycled the Pi-hole you picked up a new IPv6 address, the old address is listed as the source to block. Try `pihole -r` reconfigure and select the correct IPv6 address.

**Comment by jwillmer** [comment]
Since my ISP is assigning the IPv6 I can't add a static one.  I only broadcast the IPv4 of my pi (for that reason) as my local DNS server. I also added IPv6 support in the configuration to be ready for the future but it seams that this really was the problem. Reconfigure pi-hole and remove the IPv6 compatibility fixed the problem.  

Could you explain me how IPv6 effected the ad blocking via IPv4? Since I only had it configured but not activated.

**Comment by jwillmer** [comment]
Now that I removed IPv6 configuration I can't set an IPv6 DNS server. Why can't I set an IPv6 DNS server - I thought an IPv4 DNS server can send IPv4 and IPv6 resolved addresses.

**Comment by dschaper** [comment]
If you have a Globally Unique Address assigned to the Pi-hole device, then it stands to assume that your clients are all getting IPv6 GUA addresses as well. Those clients are going to query for AAAA records and the Pi-hole is reporting back that the address for those domains is the old IPv6 address. The clients are trying to access the old IPv6 address and timing out since it doesn't exist. 

The DNS server can serve both A records (IPv4) and AAAA records (IPv6) on an IPv4 address. If you remove the IPv6 configuration, there is not an IPv6 interface to bind to, but the DNS server will still happily respond to queries for A and AAAA records.

**Comment by dschaper** [comment]
I would suggest that you use the Pi-hole DHCP server and implement ULA's for the network. https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127

**Comment by jwillmer** [comment]
>  If you remove the IPv6 configuration, there is not an IPv6 interface to bind to, but the DNS server will still happily respond to queries for A and AAAA records.

If he response to AAAA queries why can't I then define which NS server he shall use for that query?

**Comment by dschaper** [comment]
That's not how DNS works, you can't have a separate server for each record type.

**Comment by jwillmer** [comment]
I am closing this now since the actual problem was solved.

**Comment by jwillmer** [comment]
> That's not how DNS works, you can't have a separate server for each record type.

O.K., I understand. I looked into ULA's but I think it's not worth it. I sick with IPv4 DNS server for the local network - don't see a benefit in having IPv6 DNS server as well if IPv4 also supplies IPv6 records.
