### ISSUE TITLE
Error: Could not update local repository. Contact support.

### ISSUE THREAD

**Issue by ceramicskate0** [pi-hole/pi-hole#1941]
Attempt 1st install on clean pi image using current install script. 

  [✓] Root user check
  [✓] Disk space check

  [i] Update local cache of available packages...git -c http.sslVerify=false clone https://github.com/pi-hole/pi-hole.git /etc/.pihole
  [✓] Update local cache of available packages

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for whiptail

  [✓] Stopping dnsmasq service...

  [✓] Stopping lighttpd service...
  [i] Using OpenDNS servers
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 10.1.1.2/30
  [i] IPv6 address:
  [i] Web Interface On
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole **( I downloaded it manually from github to that dir. It took the following to make it work with some wierd ssl cert issue "git -c http.sslVerify=false clone https://github.com/pi-hole/pi-hole.git /etc/.pihole")**
  [i] Update repo in /etc/.pihole...
  Error: Could not update local repository. Contact support.

**(reboot attempted. Same outcome.)**

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by carson-day** [comment]
I had the same problem

**Comment by dschaper** [comment]
Please open a new issue, this one has been closed since Feb of last year.
