### ISSUE TITLE
Add option to block all IDN domains

### ISSUE THREAD

**Issue by s1awa** [pi-hole/pi-hole#1942]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---

[IDN domains](https://en.wikipedia.org/wiki/Internationalized_domain_name) are not really useful for most people. But there is high risk of phishing from domains that mimic popular sites.

e.g. 

apple.com != аpple.com (xn--pple-43d.com) uses cyrillic a
adidas.com != adîdas.com (xn--addas-6sa.com)
airasia.com  != airasîa.com (xn--airasa-fwa.com)

It would be great if you can block all IDN domains in the settings of pihole.

All IDN domains start with `xn--`

**Comment by dschaper** [comment]
* Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

**Comment by s1awa** [comment]
@dschaper done. My post needs to be reviewed by a mod on discourse.

**Comment by dschaper** [comment]
It's approved now. Thanks for the submission.

**Comment by s1awa** [comment]
This is now possible with FTLDNS™
https://discourse.pi-hole.net/t/blocking-via-regex-now-available-in-ftldns/9101
