### ISSUE TITLE
Add option for listening by IP address during install

### ISSUE THREAD

**Issue by Mapes** [pi-hole/pi-hole#1944]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
2
---
**Expected behaviour:**
pihole explicitly configure dnsmasq listeners 
**Actual behaviour:**
Pihole configures dnsmasq by interface which makes dnsmasq also listen on loopback
I filled a feature request on discord  https://discourse.pi-hole.net/t/add-option-for-listening-by-ip-address-during-install/6860 and was asked to file a defect here.  Heres a copy n paste of that feature request...

dnsmasq is kinda funny in that it will auto listen on the loopback interface if you include an interface config line (see man page snippet below). Which is what the pihole install script does. Which is really unlike any other *nix network service configuration. Meaning I explicitly tell the service what to listen on and it only listens on that. This broke my config since I planned on pihole talking to my bind9 server running on loopback. I had to edit my /etc/dnsmasq.d/01-pihole.conf by hand. I can deal with that, however there is no other choice when installing and when I change a setting via the web interface the interface line is again added.so if I restart dnsmasq again it pukes. I’m wondering if we could have an install option to only listen on an IP. to prevent dnsmasq from auto listening on the loopback and in some cases everything

On some level I get it I’m an edge case. Not everyone is going to be running two dns servers and four webservers (although ssl termination via Nginx proxying is gaining in popularity). I also get that pihole was developed to be on a standalone rasberry pi. However not being able to override this is annoying and I think it’s a trivial install script fix.

–listen-address=
Listen on the given IP address(es). Both --interface and --listen-address options may be given, in which case the set of both interfaces and addresses is used. Note that if no --interface option is given, but --listen-address is, dnsmasq will not automatically listen on the loopback interface. To achieve this, its IP address, 127.0.0.1, must be explicitly given as a --listen-address option.

**Steps to reproduce:**
Install pihole and select an interface.  Do "lsof -i -n -P | grep LISTEN | grep dnsmasq"   This will show dnsmasq listening on the loopback interface

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not needed default behavior during install

**Troubleshooting undertaken, and/or other relevant information:**

By hand modify /etc/dnsmasq.d/01-pihole.conf to include listening by ip address only

**Comment by tmottabr** [comment]
Solved this by creating another file named "02-local.conf" under /etc/dnsmasq.d that will also be read by dnsmasq automatically on startup.

In that file i have the following:

    except-interface=lo
    listen-address=127.0.0.1
    bind-interfaces

So it will still bind to eth0, but it will not bind to loopback. You also need to add a listen-address for loopback because it is the server used locally in resolv.conf. The last option is so dnsmasq will only bind to the specific interface instead binding to everything and only answering to addresses in the configured interface.

And since this does not require any changes in the files managed by pi-hole this configuration will survive regardless of you do on pi-hole.

This also work in the beta FTLDNS.

Now i have pi-hole serving the network, bind to resolve local addresses from dhcp and dnscrypt proxy serving pi-hole, all on distinct loopback addressed without having to mess with different ports.

**Comment by Mcat12** [comment]
You could also run bind on a different port and use that as an upstream. See also https://github.com/pi-hole/AdminLTE/pull/728

**Comment by dschaper** [comment]
Is this still open for discussion?

**Comment by dschaper** [comment]
Okay, so should we label this as investigating and keep it on the board?

**Comment by Mcat12** [comment]
^ This tag seems to be a good fit

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
