### ISSUE TITLE
Respect FHS and don't use "/var/www"

### ISSUE THREAD

**Issue by envygeeks** [pi-hole/pi-hole#1945]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 8

---
**Expected behaviour:**

I expect FHS to be respected when something is installed.  I understand even the distro's themselves prefer to violate the FHS (and this is still being discussed as being possibly fixed eventually,) but being that this is designed for systems people (or people who are willing to manage their own systems) I would expect `/srv/www/pi.hole`, `/srv/lighttpd/pi.hole` or otherwise to be used. http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM

***If pressed technically, in a hostage situation type of press, you aren't wrong, but in any situation where I can gain the upperhand, you will be told `/srv` is the proper directory for any data being for services.***

**Actual behaviour:**

Site data is placed inside of `/var/html`

I just reconfigured everything you configured and forced my way, but this is not ideal, because if I chose to unlock your outgoing connections (yes we limit even outgoing) and update you could revert this change, which would break everything.

**Comment by dschaper** [comment]
We are heavily used on Raspbian and SBCs. Changing off the Debian `/var/www/html` and on to `/srv` would confuse and anger the far majority of our users. We also are provided via SBC distributions like DietPi and Armbian. This would be a breaking change. I may agree with you that `/srv` is FHS proper, it's not something easily changed and ported to. We can look at making it configurable, and I believe the Arch port uses FHS directory structure. We are looking at a longer term rewrite of the installer code and as I mentioned in the tweet, these comments will be taken in to consideration.

**Comment by metaa** [comment]
Yes, please make this configurable.
