### ISSUE TITLE
Create a default "blacklist" of dependencies that should *never* be uninstalled.

### ISSUE THREAD

**Issue by envygeeks** [pi-hole/pi-hole#1946]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 10/system 0/pihole

---
**Expected behaviour:**

It to skip some packages that most systems (except Ubuntu cloud) include.  Ubuntu Cloud only skips sudo in this case, because it's unnecessary in that environment as it's an embedded distro.

**Actual behaviour:**

It asks if I want to uninstall a couple of necessary packages

- dnsutils
- apt-utils
- cron
- sudo

**Steps to reproduce:**

```
pihole uninstall
```

**Comment by PromoFaux** [comment]
We have toyed with the idea of somehow tracking what packages were actually installed when Pi-hole if first installed, but have not currently gotten around to it.

As it stands, the uninstaller will never actually automatically uninstall _any_ packages, rather the user is offered a choice:
1. Go through each dependency individually, and choose whether to keep or remove.
2. Skip removing packages all together and only remove the scripts.

Pull Requests are welcomed, so if you feel you can come up with a better solution than above, please feel free to contribute :)
