### ISSUE TITLE
Consider making pi-hole an actual blackhole

### ISSUE THREAD

**Issue by envygeeks** [pi-hole/pi-hole#1947]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 10/dnsmasq 2/pihole

---
**Expected behaviour:**

```
root@Clara:/etc/dnsmasq.d# dig google-analytics.com @clara.local
; <<>> DiG 9.10.3-P4-Ubuntu <<>> google-analytics.com @clara.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 57712
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google-analytics.com.		IN	A

;; Query time: 0 msec
;; SERVER: 192.168.1.2#53(192.168.1.2)
;; WHEN: Fri Feb 02 12:04:24 CST 2018
;; MSG SIZE  rcvd: 45
```

**Actual behaviour:**

```
root@Clara:/etc/dnsmasq.d# dig google-analytics.com @clara.local
; <<>> DiG 9.10.3-P4-Ubuntu <<>> google-analytics.com @clara.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24080
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google-analytics.com.			IN	A

;; ANSWER SECTION:
google-analytics.com.		248	IN	A	192.168.1.2

;; Query time: 0 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Fri Feb 02 12:08:07 CST 2018
;; MSG SIZE  rcvd: 57
```

**Steps to reproduce:**

Install Pihole.

**Troubleshooting undertaken, and/or other relevant information:**

```ruby
#!/usr/bin/env ruby
require "pathutil"

out2 = File.open("/etc/dnsmasq.d/01-pihole.conf", "a+")
out1 = File.open("/etc/dnsmasq.d/02-reject.conf", "w+")
%w(/etc/pihole/gravity.list /etc/pihole/black.list).each do |f|
  Pathutil.new(f).each_line do |l|
    _, domain = l.split(/\s+/)
    out1.write("server=/.#{domain}/\n")
  end
end

out2.each_line.to_a.tap { out2.truncate(0) }.each do |l|
  if l !~ /^addn-hosts=.*\.list/ || l == "addn-hosts=/etc/pihole/local.list\n"
    out2.write(l)
  end
end

out1.close
out2.close
```

```
[Unit]
Description=Take a hatchet to Pi-Hole configuration for dnsmasq

[Service]
ExecStart=/usr/local/bin/hack-dnsmasq
Type=oneshot

[Install]
RequiredBy=dnsmasq.service
```

**Comment by dschaper** [comment]
It returns the address of the Pi-hole install so that it redirects to the blockpage. You're free to modify that to return 0.0.0.0 to completely sinkhole the query but changing the default to remove the blockpage isn't something that is going to go over well with the users.

**Comment by envygeeks** [comment]
I'm wondering if that's more of a guess than an actual fact. How many of your users actually know that's what happens? And if they did, how many of them would rather gain back the perf from an NXDOMAIN and then pi-hole properly read the logs to gather it's statistics than know that their qps is reduced because it returns to a local domain which still serves as a latency point.

0.0.0.0 doesn't really blackhole anything either, if you have a local server running it'll just go to that depending on the client you use, which means you still have reduced perf.  An NXDOMAIN not only increases the perf, but it increases how much pi-hole can claim to do.

Can this not even be considered as an option?

**Comment by dschaper** [comment]
We are not going to remove the blockpage. It's commented on very heavily in our social media outlets.

**Comment by dschaper** [comment]
If you'd like to make a feature request and have the community voice their opinions on them, feel free to do so at the site listed in the Issue template that asks you to open feature requests on discourse. https://discourse.pi-hole.net.
