### ISSUE TITLE
pi-hole doesn't detect bad queries in it's logs.

### ISSUE THREAD

**Issue by envygeeks** [pi-hole/pi-hole#1948]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 10/system 0/pihole

---

**Expected behaviour:**

Detection of invalid queries, or queries that do not complete, or have an error of some kind.

**Actual behaviour:**

<img width="964" alt="screen shot 2018-02-02 at 12 18 10 pm" src="https://user-images.githubusercontent.com/99763/35748304-32397bc8-0813-11e8-8478-c52bf7be8fb2.png">

---

```
Feb  2 12:11:35 dnsmasq[31316]: query[A] google-analytics.com from 127.0.0.1
Feb  2 12:11:35 dnsmasq[31316]: config google-analytics.com is NXDOMAIN
```

It would seem that pi-hole's log analysis doesn't distinguish between `NOERR` and `NXDOMAIN`, this makes it hard for it to know whether to display invalid queries to a user, this also makes it impossible for it to report blocklists outside of getting a http request to it's httpd, but it could detect blocks, and invalid queries via the logs too if it pays attention to NXDOMAIN.

**Comment by DL6ER** [comment]
The reply
```
config google-analytics.com is NXDOMAIN
```
means that you have configured this domain as `NXDOMAIN` locally, hence the query succeeded (`NXDOMAIN` is a valid answer after all) and it was neither invalid nor incomplete or an error.
Furthermore, the request for `google-analytics.com` has been answered from cache, so everything you see here is correct.

**Comment by envygeeks** [comment]
NXDOMAIN is not a successful query unless you make it the most basic form of "success" and in that event, every query is considered a successful query unless you can't reach the port.  NXDOMAIN means that it has no host configured. And returning from the cache is not relevant here.

**Comment by DL6ER** [comment]
That is your opinion then. `NXDOMAIN` means that your request got answered (from whatever source). A failure would either be a transmission problem (as you mentioned) or replied with as `SERVFAIL`.
Have a look at e.g. RFC 8020. `NXDOMAIN` is a legit response code. Not an error code.

> And returning from the cache is not relevant here.

You are wrong. It is important as when you don't have this domain configured locally, it will get forwarded to an upstream server.

To cut a long story short, we have not analyzed the actual response to a query before (as it doesn't seem interesting) and are currently looking into the possibilities we have and if that brings any advantages for our users.

**Comment by envygeeks** [comment]
I'm done here.  I've no time for arrogance.
