### ISSUE TITLE
Reconfiguration of gateway

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1949]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
I installed pi-hole on a clean raspbian image on a network with with the following ip range `192.168.1.xxx`. I brought the box to a new location with the network ip range of `192.168.0.xxx`. I reconfigured pi-hole via `pihole -r` and changed his IP and gateway to reflect the new network. I rebooted the system afterwards. I expected that pi-hole is working now in the new network.

**Actual behaviour:**
The changed IP address was working but the system could not get connected to the internet since the new gateway was not set. The `route` command still showed the old gateway address (`192.168.1.x`).

**Steps to reproduce:**
Use `pihole -r` to change the configuration and change the sub network and gateway.

**Comment by dschaper** [comment]
Have you rebooted the Pi-hole device or restarted the network stack after you changed the IP address?

**Comment by dschaper** [comment]
What does the config block in `/etc/dhcpcd.conf` look like for the Pi-hole device?

**Comment by jwillmer** [comment]
Sorry I flashed a new image already since my experiments of adding a gateway manually broke something and I was out of patients. I will now configure the whole system on the final location to avoid the issue.

**Comment by dschaper** [comment]
Thanks for the update, if the new install causes any problems please open a new issue with us.

**Comment by jwillmer** [comment]
I actually posted it so that you can keep it in the bug tracker and fix it at some point. I don't think my solution is the intended way ;-)

**Comment by Faxmachinen** [comment]
> What does the config block in `/etc/dhcpcd.conf` look like for the Pi-hole device?
Thanks for this tip. My dhcpcd.conf had three different configurations for eth0 appended to the file, and it appears to use the first one. My guess would be that the multiple configurations come from reconfiguring with "pihole -r" multiple times, sometimes on different networks.

I'm running Pihole 4.1.1 on Raspbian 9.4.
