### ISSUE TITLE
lighttpd is not installed if installing of web admin is skipped

### ISSUE THREAD

**Issue by vpmuli** [pi-hole/pi-hole#1950]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

lighttpd is installed and a placeholder page is displayed instead of ads.

**Actual behaviour:**

lighttpd is not installed and ad hosts do not resolve to any IP address.

**Steps to reproduce:**

curl -sSL https://install.pi-hole.net | bash
Answer No when asked about setting up logging and web admin

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I first ran the installer with logging and web admin enabled, then uninstalled and reinstalled without logging and web admin. The installer does not seem to try to install the lighttpd package, but clearly tries to do something lighttpd related as "Failed to get unit file state for lighttpd.service: No such file or directory" error is printed during install. Pi-hole seems to work just fine without lighttpd, but if this is not a bug then at least it is very surprising that the existence of the web admin changes how the ad blocking works.

**Comment by PromoFaux** [comment]
I believe this is intended, though you make a good point.

The thinking behind this is that people may not want the web admin installed because of it interfering with other webservers they may have on their system, so the logical step is to take out the webserver altogether and send queries to 0.0.00 (I think, it's been a long time since I've looked at this part of the code!)

**Comment by vpmuli** [comment]
Maybe the installer should separately ask do you want to have the placeholder pages even though you do not want the web admin installed? I personally have no need for web admin or statistics, but I might want to have the placeholder pages. I'm assuming that the ad blocking works better with the placeholders since having those seems to be the default and I haven't seen any mentions about this other ad blocking mode anywhere.

**Comment by Mcat12** [comment]
This is fixed by #2115
