### ISSUE TITLE
Block page or http://pi.hole returns HTTP Error 500

### ISSUE THREAD

**Issue by petererdos** [pi-hole/pi-hole#1955]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Block page should load when an offending domain is hit; http//pi.hole should load the welcome screen

Instead of the block page, i get http error 500 instead of the block page, or if i try to access http://pi.hole:
This page isn’t working
pi.hole is currently unable to handle this request.
HTTP ERROR 500

![screenshot_6](https://user-images.githubusercontent.com/14872721/35945283-54c8dc8e-0c68-11e8-9556-27cdc3ec0a50.png)

Errors in the log, which appear when loading http://pi.hole or block page:
2018-02-06 20:09:20: (mod_fastcgi.c.434) FastCGI-stderr: PHP Fatal error: Can't use function return value in write context in /var/www/html/pihole/index.php on line 108

**Steps to reproduce:**

Install Pi-hole on CentOS 7.4 (fully updated):
centos-release-7-4.1708.el7.centos.x86_64
Kernel: Linux 3.10.0-693.17.1.el7.x86_64
SELinux disabled

Try to open: http://pi.hole or access a blocked domain with (tried) Edge and latest Google Chrome (from Win10 & Server 2016)

Issue: HTTP Error 500 page

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

0c0r6bk4a2

**Troubleshooting undertaken, and/or other relevant information:**

pihole -up
pihole -r
.. although without effect.

Then I edited this in /var/www/html/pihole/index.php:
`if (empty(glob("/etc/pihole/list.0.*.domains")))`
Into this:
`if (!glob("/etc/pihole/list.0.*.domains"))`

Looks like this fixed it.

Please note that http://pi.hole/admin/index.php is loading, everything else works, lists are being saved from the GUI, even without my editing.

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Sorry, it looks like we missed this issue. Please make a new debug token or share the errors from the error log you were getting. You can also make a Pull Request if you want to make the changes yourself.

**Comment by petererdos** [comment]
Since then, I switched to Ubuntu Server... I thought this was an isolated issue with my setup. I had other issues as well, with brand new CentOS installs, so switching to a more compatible distro seemed to be a sane choice. Unfortunately I cannot make another debug token nor validate any potential fixes after all these. I could try with a new VM though.

**Comment by twkonefal** [comment]
I have a debug token for this error: wr0je7tsqg

Not sure if it's related, but the installer has a great deal of problems on hardened systems where UMASK is set to 077 (as it is on mine). You can see some of the evidence of this in the debug token where it tries to load dnsmasq lists (since the directory and files are owned by root with 600 permissions).

I also had problems with lighttpd's configuration; compress.cache-dir was created as /var/cache/lighttpd/compress/ with the right permissions, but its parent folder was not readable by lighttpd because of the UMASK setting (so it was owned by root with 600 permissions).

**Comment by Mcat12** [comment]
It looks like you're running into a PHP version issue where before 5.5 `empty()` would only work when given variables, not when given the output of a function like `empty(some_function())`. Can you update PHP? You're on 5.4, which has been officially unsupported (by the PHP project) since 2016: http://php.net/supported-versions.php

**Comment by bcambl** [comment]
My apologies for the bad experience with the installation. 
Yes, CentOS ships with an unsupported version of PHP which is unfortunate. I plan to make some changes in the near future that should provide more clarity when issues occur when installing CentOS dependencies.
With this issue being related to PHP, perhaps this issue would be best created against the front-end repository: https://github.com/pi-hole/AdminLTE/issues.

**Comment by rrobgill** [comment]
Are there any other showstoppers that result from running under php 5.4?

If the sole issue is the use of empty() on functions, the only current instance that I can see is this one  in #2176 . This would let Centos 7 users continue with their official repos, so those who can't/won't install the third party repos you're offering in #2161 would still be able to run Pi-hole.

**Comment by bcambl** [comment]
#2161 does not force the use of the third-party repository to allow the update to a supported version of PHP, only suggests and provides the option to updating.  If the user decides to continue using an outdated version of PHP, then they may do so but must expect possible breakage and security issues.

Please read: http://php.net/supported-versions.php:

> 
End of life | A release that is no longer supported. Users of this release should 			upgrade as soon as possible, as they may be exposed to unpatched security 			vulnerabilities.
-- | --

Also worth noting: https://pi-hole.net/2018/01/13/pi-hole-web-interface-the-next-generation/

**Comment by twkonefal** [comment]
After reading my previous comment I realize it there could be a less drastic solution. The documentation can simply be updated instructing people how to install a newer php. Further, the installer could be patched to pull in the appropriate repositories and install a supported php release.

**Comment by Mcat12** [comment]
This specific issue is fixed in dev now.
