### ISSUE TITLE
Pihole-FTL log and db not updated 

### ISSUE THREAD

**Issue by paulD1968** [pi-hole/pi-hole#1956]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

pihole-FTL log and  pihole-FTL.db updated 

**Actual behaviour:**

log shows ftl start and 
```
[2018-02-06 17:03:26.342] Gravity list entries: 106669
[2018-02-06 17:03:26.343] Blacklist entries: 5
[2018-02-06 17:03:26.343] Wildcard blocking list entries: 1
```
But is never updated with query blocked. 

pihole.log is showing queries blocked 

**Steps to reproduce:**

on archlinux install pihole as per steps in https://blog.jenningsga.com/install-pi-hole-on-arch/ 
( was working) 
then update FTL to latest 
-> broken 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Token not available as when running command: pihole -d 
=> Help only shows : 
```
[root@nsa325 pihole]# pihole -d /root/debug.log
Usage: pihole [options]
Example: 'pihole -w -h'
Add '-h' after specific commands for more information on usage

Whitelist/Blacklist Options:
  -w, whitelist       Whitelist domain(s)
  -b, blacklist       Blacklist domain(s)
  -wild, wildcard     Blacklist domain(s), and all its subdomains
                        Add '-h' for more info on whitelist/blacklist usage

Debugging Options:
  -t, tail            View the live output of the Pi-hole log

Options:
  -a, admin           Admin Console options
                        Add '-h' for more info on admin console usage
  -c, chronometer     Calculates stats and displays to an LCD
                        Add '-h' for more info on chronometer usage
  -g, updateGravity   Update the list of ad-serving domains
  -h, --help, help    Show this help dialog
  -l, logging         Specify whether the Pi-hole log should be used
                        Add '-h' for more info on logging usage
  -q, query           Query the adlists for a specified domain
                        Add '-h' for more info on query usage
  -v, version         Show installed versions of Pi-hole, Admin Console & FTL
                        Add '-h' for more info on version usage
  status              Display the running status of Pi-hole subsystems
  enable              Enable Pi-hole subsystems
  disable             Disable Pi-hole subsystems
                        Add '-h' for more info on disable usage
  restartdns          Restart Pi-hole subsystems

```

**Troubleshooting undertaken, and/or other relevant information:**

**verify all configs in 
/opt/pihole/
/etc/pihole/
/srv/http/pihole/admin/* 
for logs location all works
**verify  FTL is working :
```
[root@nsa325 pihole]# pihole -v
  Pi-hole version is 3.2.1 (Latest: v3.2.1)
  AdminLTE version is 3.2.1 (Latest: v3.2.1)
  FTL version is v2.13.2 (Latest: v2.13.2)

[root@nsa325 pihole]# 
and process is up and running
[root@nsa325 pihole]# netstat -npl |grep FTL
tcp        0      0 0.0.0.0:4711            0.0.0.0:*               LISTEN      13970/pihole-FTL    
```
**Pidof FTL process matches  admin page 

```

FTL version:	v2.13.2
Process identifier (PID):	13970
Time FTL started:	Feb 06
User / Group:	pihole / pihole
Total CPU utilization:	0.0%
Memory utilization:	0.4%
Used memory:	2.43 MB

```

Hence  all seems to work and testing  web pages [ http://double-click.net] or using dig in terminal returns correct blocking page but  no statistics are loaded.
```
[root@nsa325 log]# dig @localhost doubleclick.net

; <<>> DiG 9.11.2 <<>> @localhost doubleclick.net
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29171
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;doubleclick.net.		IN	A

;; ANSWER SECTION:
doubleclick.net.	300	IN	A	192.168.0.23

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Feb 08 16:05:43 CET 2018
;; MSG SIZE  rcvd: 60

``` 

[pihole.log](https://github.com/pi-hole/pi-hole/files/1707546/pihole.log)
[pihole-FTL.log](https://github.com/pi-hole/pi-hole/files/1707547/pihole-FTL.log)

what's wrong how can I fix this?

**Comment by PromoFaux** [comment]
Hi there, we don't actually officially support Arch, rather it is maintained by @max72bra, with help from @graysky2 (You can find the AUR package [here](https://aur.archlinux.org/packages/pi-hole-server/)), however they may be willing to help you through your issue here!

**Comment by max72bra** [comment]
Hi all.
Under ArchLinux Pi-hole "distro", debug informations and commands are not supported (and removed) because, in fact, ArchLinux Pi-hole is not officially supported and, for now, it does not make sense to generate a debug report of an unsupported environment and which, moreover, presents differences with the original.
As graysky said, you should follow carefully the Pi-hole ArchLinux wiki.
OK, and now:
reading your logs i see that your FTL is looking for Pi-hole logs in /var/log/pihole.log.
This is really strange because our (ArchLinux ones) logs are in /run/log/pihole/pihole.log...
Have you mixed some AUR package installation with some official ones?

**Comment by dschaper** [comment]
Instead of completely removing the debug script and potential causing issues when we ask for a debug and users report that they don't have the option, could you please instead apply a patch to change the output to notify the users where they can receive support for the installation? Thanks!

**Comment by PromoFaux** [comment]
Similar to how I PRd this to the Docker repo:

https://github.com/diginc/docker-pi-hole/pull/203

**Comment by max72bra** [comment]
@dschaper 
I do not know why many people in the archlinux community report alleged bugs and malfunctions directly here without first contacting AUR and their support.

**Comment by PromoFaux** [comment]
I guess that some less experienced users don't really see the distinction between the two, but it's no bother really, as long as you don't mind us tagging you into issues as and when they arise?

**Comment by max72bra** [comment]
@PromoFaux 
no i don't mind at all

**Comment by dschaper** [comment]
Well, this post is one example. as long as @pi-hole/core-approvers all know that if you ask a user to run a debug and they say they don't have that option, first ask if they are using Arch linux instead of telling them to run `pihole -r` to fix an install the wont fix.

**Comment by graysky2** [comment]
I think as you guys move to the `Makefile` installation method, many of these problems making Arch some what of a black sheep will go away.

**Comment by PromoFaux** [comment]
@paulD1968, sorry, we got a bit sidetracked, the relevant comments for you are:

https://github.com/pi-hole/pi-hole/issues/1956#issuecomment-364221433

and 

https://github.com/pi-hole/pi-hole/issues/1956#issuecomment-364228273

**Comment by paulD1968** [comment]
@graysky2  and all thank you for your comment. 
As I said on 1st installation it was working fine then I had a message a new FTL version was available and press the update link...
it's where all started to break  down. 

So the log path  issue may be part of this. 
To get FTL working I had to check which log was filled up and set the path on the config files. 

But could not have the DB and FTL log filled up . 

I removed this morning all the package and plan to redo the installation from scratch this week end. 
hopefully it will run again as before. 
If not I have a Raspberry Pi 3  on which I can try to install the tool...

**Comment by paulD1968** [comment]
@graysky2 @PromoFaux  the  steps I used are described in https://blog.jenningsga.com/install-pi-hole-on-arch/

**Comment by max72bra** [comment]
@dschaper 
> Instead of completely removing the debug script and potentially causing issues when we ask for a debug and users report that they don't have the option, could you please instead apply a patch to change the output to notify the users where they can receive support for the installation? Thanks!

Done.
I hope that this can filter direct bug filing and we can resolve malfunctions internally first.

**Comment by dschaper** [comment]
Thanks! I do appreciate the help with that.

**Comment by ryanpetrello** [comment]
@paulD1968 @graysky2 I'm also having the same issue on arch; pi-hole-ftl is running and ad domains are being blocked

```
dig s.amazon-adsystem.com | grep amazon
; <<>> DiG 9.8.3-P1 <<>> s.amazon-adsystem.com
;s.amazon-adsystem.com.		IN	A
s.amazon-adsystem.com.	300	IN	A	<ip-of-pi-hole>
```

...but the database just isn't getting written to at all, so I can't see statistics:

```
~ sudo grep DBFILE /etc/pihole/pihole-FTL.conf
DBFILE=/etc/pihole/pihole-FTL.db
~ sudo sqlite3 /etc/pihole/pihole-FTL.db
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> SELECT COUNT(*) FROM queries;
0
```

**Comment by max72bra** [comment]
@ryanpetrello 
hi, please read all this issue, follow arch wiki and report to AUR page.

**Comment by ryanpetrello** [comment]
@max72bra understood that this isn’t the proper support avenue for Arch (which isn’t supported).  I was mostly just chiming in to see if @paulD1968 had any luck figuring it out (since it sounds like I have the same problem).

**Comment by ryanpetrello** [comment]
For what it's worth, this _looks like_ a bug in FTL itself.  On closer inspection, I found these errors in my FTL log:

https://gist.github.com/ryanpetrello/9850707cf9a2130c713f36b7faa50b97
`[2018-02-16 08:05:26.181] Error getting ID for query "Feb 16 06:30:45 dnsmasq[28085]: query[AAAA] 1-courier.push.apple.com from 192.168.1.39
" 4294967295`

Which looks like a failure to parse a string in this code:

https://github.com/pi-hole/FTL/blob/master/parser.c#L190

Out of curiosity, I decided to build my own patched version with this code removed:

```diff
diff --git a/parser.c b/parser.c
index 8fdcc40..bc2f7f6 100644
--- a/parser.c
+++ b/parser.c
@@ -184,11 +184,7 @@ int getdnsmasqID(char * readbuffer)
 {
        // Get query ID from a string like
        // "Dec 20 21:16:22 dnsmasq[19372]: 4 10.8.0.2/34596 query[A] pi.hole from 10.8.0.2"
-       int dnsmasqID = -1;
-       if(!sscanf(readbuffer, "%*[^]]]: %i", &dnsmasqID))
-       {
-               if(debug) logg("Error getting ID for query \"%s\" %u", readbuffer, dnsmasqID);
-       }
+       int dnsmasqID = 19372;
        return dnsmasqID;
 }
```

After rebuilding FTL with this change, query logging works for me and I'm able to view results in the web UI and in `pihole -c`

I'm unclear on whether this issue is specific to Arch or the version of dnsmasq I'm running, but this patched version of the package _does_ work for me:

http://ryanpetrello.com/pihole/patched.tar.gz

**Comment by ryanpetrello** [comment]
My patch doesn't _actually_ work for detecting record status, however; if you look in the SQLite query table, all of the rows are status = 0 (Unknown).  The real way to fix this is probably to figure out _why_ the above lines of code are failing and entering that block that calls `logg()`.

**Comment by PromoFaux** [comment]
What version of `dnsmasq` are you running? That may be the answer... newest `FTL` requires version `2.73`

**Comment by DL6ER** [comment]
You cannot simply remove the `dnsmasqID` detection and set the ID to something random like 19372. It may be that your statics get populated but they will be very wrong...

The problem here is rather that you are running `dnsmasq` without the `log-queries=extra` option. This one is needed since FTL v3.0, which was just released two days ago. So, either you have to use the source code of FTL v2.13.2 (see e.g. branch ``) or switch to

**Comment by ryanpetrello** [comment]
```dnsmasq --version
Dnsmasq version 2.78```

**Comment by ryanpetrello** [comment]
@DL6ER understood - I'm not suggesting my patch is the proper solution here - it's clearly not.  I'm just attempting to debug this and figure out why parsing is failing.  Sounds like a dnsmasq incompatibility.

**Comment by ryanpetrello** [comment]
@DL6ER Thank you!  Adding:

`log-queries=extra` to my `/etc/dnsmasq.conf` 100% solved the issue.

**Comment by DL6ER** [comment]
Okay, glad to see this working now!
Can you delete your comment above? Just in case some other Arch user stumbles later over this issue, he shouldn't try this out as it is no solution at all.

**Comment by paulD1968** [comment]
@ryanpetrello  @DL6ER 
Reinstalling the package on Arch makes all working again. So the update on FTL was the issue. 
I'm  having Apache and Nginx installed on the server ( Apache on 90 and Nginx on 80) the default root folder is used by Apache and this works just fine while the Nginx seems not to understand the configuration ( 502 bad gateway) Therefore I will have to dig furthermore on the config but Before re-install it wasn't working at all on both web server. 

Thank you all for your tips and support.
