### ISSUE TITLE
Blocking page does not render correctly when system has hostname other than 'pi.hole' due to hard-coded paths

### ISSUE THREAD

**Issue by dere** [pi-hole/pi-hole#1959]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behaviour:**

When visiting `http://my-systems-hostname/` the "blocking page" should be rendered correctly, reminding you to log-in to `/admin`

**Actual behaviour:**

![image](https://user-images.githubusercontent.com/602444/36051589-a1a2b858-0db8-11e8-9f3d-ae40e70dd3dd.png)

**Steps to reproduce:**

1. Install pihole on a clean system with a hostname other than `pi.hole`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not needed (explained below)

**Troubleshooting undertaken, and/or other relevant information:**

This issue is caused by a hardcoding of the hostname `pi.hole` on lines 231 and 232, and 234 of file `advanced/index.php`: https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L231. This can be fixed quite easily. For example, line 231 should change `href="<?=$proto ?>://pi.hole/admin/img/favicon.png"` to `href="//<?=$serverName ?>/admin/img/favicon.png"`. Note that the URL scheme does not need to be explicitly defined with `<?=$proto ?>://`, simply `//` accomplishes the same thing.

**Comment by Mcat12** [comment]
How do you reach the block page without being able to also resolve `pi.hole`?

**Comment by dere** [comment]
I point my web browser to the IP address or hostname of the machine. I'm not sure why resolving `pi.hole` would be required.

**Comment by Mcat12** [comment]
The `pi.hole` hostname is automatically set to the Pi-hole's IP, and any device using Pi-hole is able to resolve it.

**Comment by dere** [comment]
Oh, I understand the confusion now. Yeah, when I installed pihole on this raspberry pi with a fresh install of Raspbian with a hostname of `pihole`, it did not change the hostname to `pi.hole` (as you can see in the screenshot). Regardless, the issue still remains that if someone wishes to use a different hostname, this page should still render correctly (especially if the Admin page works perfectly!). My proposed fix *does* fix this issue, I have applied it to my own installation.

**Comment by Mcat12** [comment]
The hostname is irrelevant, Pi-hole always sets the `pi.hole` host to resolve to the Pi-hole's IP address. What happens if you try to go to http://pi.hole/admin?

**Comment by dere** [comment]
It works, but people such as myself may prefer to access the page using the system's actual hostname.

**Comment by Mcat12** [comment]
You can make a PR with your changes and we'll review it.

**Comment by Mcat12** [comment]
Not a bug, if you see the block page you can also access `pi.hole` by design.
