### ISSUE TITLE
Enabling dnscrypt-proxy@.service outputs Invalid argument

### ISSUE THREAD

**Issue by Qemics** [pi-hole/pi-hole#1960]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Instructions from [this](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt) Tutorial at the Section "Activate the service should display `Created symlink from /etc/systemd....` by executing `sudo systemctl enable dnscrypt-proxy@.service`

**Actual behaviour:**

By executing systemctl command the terminal returns this output:

`pi@raspberrypi:~ $ sudo systemctl enable dnscrypt-proxy@.service
Failed to enable unit: File dnscrypt-proxy@.service: Invalid argument`
**Steps to reproduce:**

Activate the service by copying dnscrypt files into /etc/systemd/system/ and enable service by systemctl command.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
None.

**Troubleshooting undertaken, and/or other relevant information:**

None.

**Comment by Mcat12** [comment]
Dnscrypt is having issues right now, and will probably get replaced with a different protocol such as DNS over https.

**Comment by norrkin** [comment]
You should upgrade to version 2

https://github.com/jedisct1/dnscrypt-proxy

**Comment by xSunshin3x** [comment]
> upgrade to version 2

How can this be done? I was using dnscrypt v1 for a couple of months, but it doesn't work anymore after upgrading to the latest pihole version.

The only way i see is to remove all deprecated v1 files and just do a clean installation of v2.0?
