### ISSUE TITLE
Pi-hole stops blocking ads

### ISSUE THREAD

**Issue by FutureTense** [pi-hole/pi-hole#1961]
I apologize for submitting this issue here, but the discourse server is down.

My pi-hole server that was running well for months suddenly stopped blocking ads.  Running

    pihole -g

Would start blocking ads again, but only for a short period.  I rebuilt my server from scratch and the same behavior happened again.  I ran the debug command and the upload token is `73snbw65o6`

Thanks.

**Comment by Mcat12** [comment]
Since this is a special situation (Discourse is down), I won't close this issue for not following the template, but please check it out: https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Mcat12** [comment]
Did you make that debug token when Pi-hole was working? I don't see any issues in it. Try making one when it stops working.

**Comment by jacobsalmela** [comment]
@FutureTense are you still having issues with this?
