### ISSUE TITLE
Update to v3.3 fails

### ISSUE THREAD

**Issue by MidGe48** [pi-hole/pi-hole#1964]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`I expect the "pihole -v" command to show the latest version if "pihole -up" was successful`

**Actual behaviour:**

`pi@server3:~/pihole $ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] FTL:		up to date
  [i] Web Interface:	up to date

  [✓] Everything is up to date!
pi@server3: ~~/pihole $ sudo pihole -v
  Pi-hole version is v3.2.1-73-g1e87850 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)
pi@server3:~/pihole $ 
`

**Steps to reproduce:**

`run "pihole -up" and then "pihole -v"`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`None required`

**Troubleshooting undertaken, and/or other relevant information:**

`re-ran a number of times and also tried with the install script directly`

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by tuttimann** [comment]
I don‘t know if Pi-hole already updated to 3.3 but when I want to check with „pihole-up“ or „pihole -v“ I get error „/usr/local/bin/pihole: Zeile 72: /opt/pihole/update.sh: Datei oder Verzeichnis nicht gefunden“.

**Comment by razzor1984** [comment]
Im running my pi-hole on an old Pi one model B+ and i reverted to 3.2.1 
But in my Webinterface im getting this --> 
Pi-hole Version vDev (HEAD, v3.2.1-0-ge602008) Web Interface Version vDev (HEAD, v3.2.1-0-g31dddd8) FTL Version vDev (v3.0 , v3.0 )
Did the revert alter the gui information about the version?
When is it save to upgrade? Will it be displayed on the webpage ?

**Comment by Mcat12** [comment]
Please check the Reddit support comments and the blog post for update help:
https://www.reddit.com/r/pihole/comments/7xm38m/pihole_v33_released_its_extra_special/

**Comment by Mcat12** [comment]
For the issue with the version not updating correctly, run these commands:
```
cd /etc/.pihole
sudo git fetch --tags
```
