### ISSUE TITLE
dnsmasq service will not start / stay running

### ISSUE THREAD

**Issue by jwilczek** [pi-hole/pi-hole#1970]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

dnsmasq service is not starting after updating to 3.3/3.0

**Actual behaviour:**

I cannot get the dnsmasq service to start and stay running. I've tried manually stopping/starting the service, rebooting, uninstall/reinstall, pihole -r, etc.

**Steps to reproduce:**

After updating to 3.3/3.0 the dnsmasq service fails to start and stay running.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

viztstsbkj

**Troubleshooting undertaken, and/or other relevant information:**

Manually starting/stopping service - it fails to start/stay running
Complete uninstall/reinstall of dnsmasq
pihole -up
pihole -r

**Comment by dschaper** [comment]
You're running Jessie, see the instructions for that OS here: https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by jwilczek** [comment]
Ooops - sorry I missed that. Guess I could upgrade to stretch as well...

**Comment by jwilczek** [comment]
After git checkout v3.2.1, how do I undo the revert to old?

**Comment by dschaper** [comment]
```
cd /etc/.pihole
sudo git checkout master
pihole -r
```
