### ISSUE TITLE
default whitelist 

### ISSUE THREAD

**Issue by cardassian-tailor** [pi-hole/pi-hole#1971]
I'm using the most up to date version of pihole. I saw that 6 domains were added to whitelist list on my recent update. However, I cant tell what domains should be there by default. 

The list in the whitelist section is a big vague. For example, it lists s3.amazonaws.com ... does this mean anything coming from an amazon s3 bucket will be permitted? 

I am attempting to see if localytics is a site that will be blocked, but when i query the site i see this: 

pihole -q -all localytics.com
 Match found in list.0.raw.githubusercontent.com.domains:
   analytics.localytics.com
 Match found in list.4.s3.amazonaws.com.domains:
   localytics.com
 Match found in list.6.hosts-file.net.domains:
   analytics.localytics.com
   localytics.com

All three of these lists are also on the default whitelists. So, is this site blocked, or isnt it? 

**whitelisted domains:**
Hosts-files.net
mirror1.malwaredomains.com
githubusercontent.com
s3.amazonaws.com
sysctl.org
zeustracker.abuse.ch

**Comment by dschaper** [comment]
Please open a new issue and fill out the issue template that you are provided with. This helps us keep things orderly.

**Comment by cardassian-tailor** [comment]
done, thanks.

**Comment by dschaper** [comment]
Thank you, it really does help us.

**Comment by mike2tango** [comment]
what is the outcome of this conversation?

**Comment by Mcat12** [comment]
See #1972
