### ISSUE TITLE
DNS funtion not working after update to 3.3 from 3.2.1

### ISSUE THREAD

**Issue by RV999** [pi-hole/pi-hole#1977]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behavior:**

I expect pi-hole to work as a DNS server

**Actual behavior:**

After upgrading from 3.2.1 to 3.3 the DNS function is not working. At the top left it says " DNS service not running Tem"
During the initial attempt to upgrade I saw this..

  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 325 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsmasq
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for lighttpd
  [✓] Checking for php5-common
  [✓] Checking for php5-cgi
  [✓] Checking for php5-sqlite

  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Creating log and changing owner to dnsmasq... log already exists!

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...
  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [i] Restarting services...

  [i] Starting dnsmasq service...
  Unable to complete update, please contact Pi-hole Support
****the second time I ran it ****
pi@DNS1:~ $ pihole -up
  [i] Checking for updates...
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...
  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
 ***** now it says *** 
pi@DNS1:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              up to date
  [i] Web Interface:    up to date

  [✓] Everything is up to date!

**Steps to reproduce:**

I've re run pihhole -r and pihole -up several times

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

zhto24lnw1

**Troubleshooting undertaken, and/or other relevant information:**

I've re run pihhole -r and pihole -up several times. I've had to manually add a DNS entry to my workstation in order to access the internet.
I modified the dhcpcd.conf file and changed my what was my local DNS (pihole) to
static domain_name_servers=8.8.8.8 in order to reach gethub for updates after the first update attempt.

**Comment by technicalpyro** [comment]
what OS are you running there is a known incompatability with Jessie

**Comment by RV999** [comment]
Linux version 4.4.11-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #888 SMP Mon May 23 20:10:33 BST 2016

pi@DNS1:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

so it is jessie, what do i need to do to resolve?

**Comment by RV999** [comment]
or, how do I backrev to 3.2.1?

**Comment by technicalpyro** [comment]
https://discourse.pi-hole.net/t/dnsmasq-fails-on-pi-hole-3-3/7161/13

**Comment by RV999** [comment]
yep, just followed this
https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

it looks to be resolved

**Comment by RV999** [comment]
i did search for this issue before I opened the issue

**Comment by technicalpyro** [comment]
no problem if you have it resolved you can close this issue using the button below the comment box

**Comment by RV999** [comment]
will close after testing,, 

Thanks

so to continue forward getting updates I'll need to change OS right? 
do you have a link for migrating setting to a new os/sd card?

**Comment by Mcat12** [comment]
We're working on making Jessie work again, but for now only Stretch is known to be fully working (in most cases).

**Comment by technicalpyro** [comment]
@RV999 
https://linuxconfig.org/how-to-upgrade-debian-8-jessie-to-debian-9-stretch << this is the link i followed

**Comment by RV999** [comment]
what OS would you say is preferred, if i wanted to set up a new one from scratch on another R-PI, rock64, or pine64 that I have?

**Comment by Mcat12** [comment]
A distro based on Debian Stretch.
