### ISSUE TITLE
Docker Image Fails to Deploy

### ISSUE THREAD

**Issue by abpostelnicu** [pi-hole/pi-hole#1979]
I'm trying to deploy the official docker image and I get this:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
ARCH=amd64
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")
BASH_SOURCE=([0]="/var/run/s6/etc/cont-init.d/20-start.sh")
BASH_VERSINFO=([0]="4" [1]="3" [2]="30" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.3.30(1)-release'
CWD=/
DIRSTACK=()
EUID=0
GROUPS=()
HOME=/root
HOSTNAME=26b451be7040
HOSTTYPE=x86_64
IFS=$' \t\n'
IPv6=True
MACHTYPE=x86_64-pc-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
PHP_ERROR_LOG=/var/log/lighttpd/error.log
PIHOLE_INSTALL=/tmp/ph_install.sh
PPID=210
PS4='+ '
PWD=/
S6OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz
S6_KEEP_ENV=1
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
ServerIP=192.168.1.100
TAG=debian
TERM=dumb
UID=0
_=bash
setupVars=/etc/pihole/setupVars.conf
 ::: Starting docker specific setup for docker diginc/pi-hole
Assigning random password: qEYtP1bx
+ [[ qEYtP1bx == '' ]]
+ pihole -a -p qEYtP1bx qEYtP1bx
  [✓] New password set
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.1.100",
			"VIRTUAL_HOST" => "192.168.1.100",
Using IPv4 and IPv6
dnsmasq: syntax check OK.
::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
  [i] Neutrino emissions detected...
  [i] Pulling blocklist source list into range...[K  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Consolidating blocklists...[K  [✓] Consolidating blocklists
  [i] Extracting domains from blocklists...[K  [✓] Extracting domains from blocklists
  [i] 141890 domains being pulled in by gravity
  [i] Removing duplicate domains...[K  [✓] Removing duplicate domains
  [i] 118752 unique domains trapped in the Event Horizon

  [i] Adding 6 blocklist source domains to the whitelist...[K  [✓] Adding 6 blocklist source domains to the whitelist
  [i] Whitelisting 0 domains...[K  [✓] Whitelisting 0 domains
  [i] Parsing domains into hosts format...[K  [✓] Parsing domains into hosts format
  [i] Cleaning up stray matter...[K  [✓] Cleaning up stray matter

pihole-FTL: no process found
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond
Starting dnsmasq
Starting pihole-FTL
Starting lighttpd
[services.d] done.
dnsmasq: started, version 2.72 cachesize 10000
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: read /etc/hosts - 7 addresses
dnsmasq: read /etc/pihole/local.list - 2 addresses
dnsmasq: failed to load names from /etc/pihole/black.list: No such file or directory
dnsmasq: bad name at /etc/pihole/gravity.list line 89328
dnsmasq: bad name at /etc/pihole/gravity.list line 118752
dnsmasq: read /etc/pihole/gravity.list - 118752 addresses
Sun Feb 18 12:58:12 2018 (457): Fatal Error Unable to create lock file: Bad file descriptor (9)`

Docker engine runs on debian jessie and the image that i use is diginc/pi-hole latest

**Comment by PromoFaux** [comment]
Hi there,

First of all:

> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Second of all.. there is no official Docker image.

You need https://github.com/diginc/pi-hole
