### ISSUE TITLE
Supporting dnsmasq 'wildcard' blocklists

### ISSUE THREAD

**Issue by notracking** [pi-hole/pi-hole#1980]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?: 6**

---
**Expected behaviour:**

Parsing of dnsmasq formatted blocklists into a wildchar list.
Example list: `https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt`

**Actual behaviour:**

[Reference to Pi-hole code](https://github.com/pi-hole/pi-hole/blob/1e87850952b6d886674b487f57e47fae1c20dc8a/gravity.sh#L338)

**Steps to reproduce:**

Not applicable

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`[✗] Format: Dnsmasq (list type not supported)`

**Troubleshooting undertaken, and/or other relevant information:**

[Current way of working](https://github.com/notracking/hosts-blocklists#for-a-pi-hole-setup)

**Comment by WaLLy3K** [comment]
Hi @notracking,

At the moment, this is quite intentional - `dnsmasq` format lists have to be handled quite differently to Pi-hole's regular parsing process (which involves having domains listed in individual `*.domains` lists, which are then consolidated into one big `gravity.list`), and I haven't found the time to make this format work.

The logic is that it's better to provide an error that they're not supported, than fail silently and give the user the false expectation that the list is doing something. 😄

**Comment by Neverther** [comment]
Quick hack I did myself, filters whitelist (inefficient) as they block some legit top level domains without good reason:


/root/updatepilist.sh:
>#!/bin/bash
cd /etc/dnsmasq.d/
wget -O /etc/dnsmasq.d/99-notracking.conf https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
for i in $(cat /etc/pihole/whitelist.txt)
do
cat 99-notracking.conf| grep -v $i > templist.txt
mv templist.txt 99-notracking.conf
done
pihole restartdns

And "0 5 * * * bash /root/updatepilist.sh" in crontab.

**Comment by notracking** [comment]
@Neverther Care to share your whitelisted domains? We're always interested in improving our lists.

**Comment by notracking** [comment]
Added to whitelist, change will be visible with the next auto update.

**Comment by PromoFaux** [comment]
@notracking , we may be able to do something about this. See #2019 . Although, it's going to need some more thought. Currently, that PR takes all the same source HOST formatted lists and turns them into `server=//` `conf` files in `dnsmasq.d`.

Obviously, if a user was to add your URL in as a source list, we still wont parse it, however, we could _maybe_ add something into `gravity.sh` that says:
```
if (list is dnsmasq formatted)
   chuck it into /etc/dnsmasq.d
```
Albiet something a bit more robust than that

**Comment by jacobsalmela** [comment]
I have moved this to Discourse to make it voteable: https://discourse.pi-hole.net/t/supporting-dnsmasq-wildcard-blocklists/8761
