### ISSUE TITLE
After Update to 3.3 - pi hole not working 

### ISSUE THREAD

**Issue by Twiebie94** [pi-hole/pi-hole#1983]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I nhave read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
No DNS reslolving possible 
Can’t Access Web Interface 

---
**Expected behaviour

Should be the Same as older versions

**Actual behaviour:**

After restarts, the pihole is reachable, some time later (2-4 hours) its Not possible to Access / does Not work.

**Steps to reproduce:**

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Running on a pi Zero 

>
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
> [x] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

https://github.com/pi-hole/pi-hole/issues/1977

😉
