### ISSUE TITLE
gravity.sh not found

### ISSUE THREAD

**Issue by tfischer4765** [pi-hole/pi-hole#1984]
When doing `pihole updateGravity` I get `/usr/local/bin/pihole: line 82: /opt/pihole/gravity.sh: No such file or directory `. I've checked and verified that the file really isn't there.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Please update your OP to include the requested issue template, and reopen once done. Thanks

**Comment by tfischer4765** [comment]
I'll pass on your bureaucracy, thank you. If you're going to be like this, I'll rather roll my own container than deal with you.

**Comment by PromoFaux** [comment]
Sure thing, it's hardly an unreasonable request. Good luck :)
