### ISSUE TITLE
DNS Forwarders not applying

### ISSUE THREAD

**Issue by Ubique88** [pi-hole/pi-hole#1985]
Hi,

I have noticed that my selected forwarders are not being used. I want to use quad 9 so i have selected it, if I look at the logs they look like this;
Feb 18 16:22:48 dnsmasq[28710]: query[A] docs.google.com from 192.168.1.126
Feb 18 16:22:48 dnsmasq[28710]: forwarded docs.google.com to 9.9.9.9
Feb 18 16:22:48 dnsmasq[28710]: query[A] drive.google.com from 192.168.1.126
Feb 18 16:22:48 dnsmasq[28710]: forwarded drive.google.com to 9.9.9.9
Feb 18 16:22:48 dnsmasq[28710]: query[A] ssl.gstatic.com from 192.168.1.126
Feb 18 16:22:48 dnsmasq[28710]: forwarded ssl.gstatic.com to 9.9.9.9
Feb 18 16:22:48 dnsmasq[28710]: reply docs.google.com is 216.58.212.78
Feb 18 16:22:48 dnsmasq[28710]: reply drive.google.com is 216.58.212.78
Feb 18 16:22:48 dnsmasq[28710]: reply ssl.gstatic.com is 216.58.212.67
Feb 18 16:22:52 dnsmasq[28710]: query[A] clients4.google.com from 192.168.1.126
Feb 18 16:22:52 dnsmasq[28710]: forwarded clients4.google.com to 9.9.9.9

But if I look on my firewall it looks like this;
![image](https://user-images.githubusercontent.com/24669053/36354266-b3fafbe2-14c9-11e8-84f5-70f75596474e.png)
so even though it says its using 9.9.9.9 the requests going through the firewall are using 8.8.8.8 for most of the requests.

Thanks

**Comment by DL6ER** [comment]
> You must follow the template instructions. Failure to do so will result in your issue being closed.

Please do this. The information you provided are insufficient to be of any help (e.g. we don't even get to know if you are using Quad9 *exclusively* as forward destination or if you are also using others, like `8.8.8.8`).
