### ISSUE TITLE
Pi-Hole web interface crashes, white-list is not working for new entries.

### ISSUE THREAD

**Issue by Kumar-GS** [pi-hole/pi-hole#1989]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Proper reporting on admin page and working white-list new entries.

**Actual behaviour:**

A detailed description and/or screenshots of what you do see
![screenshot 305](https://user-images.githubusercontent.com/29140936/36410368-b6b22932-1636-11e8-9c1c-e02f53eaf543.png)
![screenshot 306](https://user-images.githubusercontent.com/29140936/36410369-b6f6b0e8-1636-11e8-9a9d-e5fbf7b6687e.png)
![screenshot 307](https://user-images.githubusercontent.com/29140936/36410370-b73ea9ac-1636-11e8-812a-0034de1dfa93.png)

Admin page displays no data and it crashed after some time. New entries are not white listed.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

1y38yzugn9

**Comment by karafo** [comment]
Same here after updating to v3.3 (pi-hole, Webinterface) and v3 FTL
Also the recent query log is empty.

**Comment by Mcat12** [comment]
Make a new debug token. Have you tried clearing the browser cache?

**Comment by karafo** [comment]
Clearing cache is the first thing I do when some strange things happen to Website or WebApps.
But I've reverted to version 3.2.1, because there is no time for bugfixing, RL is realy heavy at this time.
