### ISSUE TITLE
Default lists block redirector.gvt1.com - prevents installation of Firefox components and may effect Chrome updates

### ISSUE THREAD

**Issue by stordoff** [pi-hole/pi-hole#1990]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Default lists shouldn't block major non-ad functionality.

**Actual behaviour:**

redirector.gvt1.com is included in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts since that list changed how it handles Spotify ad domains.

Personally, I have seen that this prevents Firefox from installing the Widevine module (a default component of the install, and the upstream issue at https://github.com/StevenBlack/hosts/issues/506 suggests this _may_ cause problems with Chrome updates/spellcheck dictionaries/extension updates etc.

**Steps to reproduce:**

Verify that the default ad lists include that list (per https://github.com/pi-hole/pi-hole/blob/master/adlists.default that is the case) and that https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts includes a rule for redirector.gvt1.com

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not provided - no current access to the device

**Troubleshooting undertaken, and/or other relevant information:**

Whitelisting redirector.gvt1.com caused Firefox to immediately succeed in installing its component (it was previously hung at "Will be installed shortly" for many hours).

**Comment by PromoFaux** [comment]
Hi there,

Thanks for the report, however, as we don't actually control what is on the lists themselves, you may wish to bring this up over on @stevenblack's [repo](https://github.com/StevenBlack/hosts)

**Comment by stordoff** [comment]
Fair enough. I just wanted to note it here because if it remains the case it may not be an ideal list for a default install and/or may want adding to the Commonly Whitelisted Domains list.

**Comment by PromoFaux** [comment]
Yeah, fair shout on the commonly whitelisted domains list. I'll try and get to that later.. mobile at the moment and not logged into discourse. If you like, you can update that list on discourse, it's a wiki post, so any member can edit it :)

**Comment by vaguerant** [comment]
Just dropping a note here to say that the upstream issue has been resolved by @StevenBlack. His combined list no longer includes the (even further) upstream source of the questionable blocked domain. With a list update on Pi-hole everything should be back to working fine.

**Comment by genbtc** [comment]
Just wanted to say that this redirector.gvt1.com domain is for pulling down chrome_installer.exe downloads and also some chrome Extension .crx's from their webstore.  Affects Firefox too somehow potentially. Its not a malicious site as far as i can tell.
