### ISSUE TITLE
"Javascript Is Disabled" during backend loading on FF

### ISSUE THREAD

**Issue by thexmanxyz** [pi-hole/pi-hole#1991]
**In raising this issue, I confirm the following:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Show pi-hole administrative backend on Firefox without displaying "Javascript Is Disabled" error page, while loading the actual page.

**Actual behaviour:**

Before any of the administrative backend pages is loaded there is a short time interval, only on Firefox, which shows the below attached error page ("Javascript Is Disabled"). This lasts about a few milliseconds before the actual site is rendered. The problem only occurs on FF but not on Chrome. Didn't test any other browsers except for Chrome, Firefox and Firefox Developer Edition. The problem occurs since the last update v3.3.

![ff-js-backend](https://user-images.githubusercontent.com/17965908/36417617-ba95bbea-162c-11e8-9566-9f4cc0abc6ef.png)

**Steps to reproduce:**

- none, just try backend with Firefox v59

**Comment by iDerp** [comment]
I could be wrong but this seems like something that might be causing it...
![Warnings](https://weed.moe/Et3UI6so.png)

**Comment by Mcat12** [comment]
I don't think we changed anything related to this section of the code. The reason it shows up is because the browser isn't starting JavaScript fast enough to hide it (by default, it is visible and is only closed if you have JavaScript).

**Comment by iDerp** [comment]
Huh, well I tried with Firefox Stable, Chrome Stable, Chrome Canary & iPhone/Safari and it all had the same issue

**Comment by Mcat12** [comment]
I'm pretty sure those warnings have appeared in previous versions of Pi-hole.

**Comment by thexmanxyz** [comment]
@iDerp Chrome Stable Windows and Chrome for Android do not have the issue on my machines. Didn't notice it and verified it again.

**Comment by iDerp** [comment]
After thinking about it, I realized that I may have a similar problem but not exactly as first shown

**Comment by thexmanxyz** [comment]
@Mcat12 @iDerp Issues seems to be gone for me. Can't reproduce it anymore. It looks to me that this was a Browser Issue because it now works for me like before v3.3.
