### ISSUE TITLE
Query log is empty

### ISSUE THREAD

**Issue by heroes1412** [pi-hole/pi-hole#2002]
everything is up to date. i restarted pi-orange, but get same result

**In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
2

---
**Expected behaviour:**

See full query log

**Actual behaviour:**

Query log is empty

**Steps to reproduce:**

Disable and Enable Log Query

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

jspgofdboh

**Troubleshooting undertaken, and/or other relevant information:**

Disable + Enable Log Query
Restart Pi-Orange

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by heroes1412** [comment]
edited

**Comment by tehniemer** [comment]
same issue here, with the addition that graphs are not working either. I have pihole installed in a container running on a QNAP NAS. Debug log attached. 


[pihole_debug-sanitized.log.log](https://github.com/pi-hole/pi-hole/files/1756106/pihole_debug-sanitized.log.log)

**Comment by Mcat12** [comment]
@heroes1412 Sorry, make a new debug token because the other one has expired.

@tehniemer Your IPv4 address in Pi-hole is invalid (you probably changed networks or routers). Also, you have set an IPv6 address even though you don't have any IPv6 access on your network. It looks like you might have changed the dnsmasq `log-queries` option, so run `pihole -r` to reconfigure Pi-hole to fix all these issues.

**Comment by heroes1412** [comment]
✓] Your debug token is: 7f5tsu6wpx

**Comment by tehniemer** [comment]
@Mcat12 I have Pi-Hole installed in a docker container with /etc/pihole and /etc/dnsmasq.d mapped to the  host file system. I deleted the 3.2.1 container, created the 3.3 container and just re-linked the existing folders during creation. Nothing else has changed. New log attached after deleting the IPv6 address from my setupVars.conf. Not sure why the IPv4 error is happening, if i revert back to 3.2.1 the debug log shows 10.0.3.1.

[pihole_debug-sanitized.log](https://github.com/pi-hole/pi-hole/files/1761168/pihole_debug-sanitized.log)

**Comment by Mcat12** [comment]
@tehniemer are you using @diginc's container?

@heroes1412 the only thing that stuck out in your log was some warning with php when getting the version. What is the output of `php -v`?

**Comment by heroes1412** [comment]
Here is my output of php -v
root@pi:~# php -v
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by tehniemer** [comment]
@Mcat12 yes I am, I also submitted an issue over there.

**Comment by Mcat12** [comment]
@heroes1412 Try fixing those warnings and then check if it fixes the query log.

**Comment by rodalpho** [comment]
I have the same problem, also using diginc's docker container, and php -v inside the container shows no errors.

**Comment by heroes1412** [comment]
i fixed all warning, but log query is still empty
> root@pi:~# php vdns.php
> New IP: 14.188.154.166
> 
> root@pi:~# php -v
> PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
> root@pi:~#
>

**Comment by diginc** [comment]
Check https://github.com/diginc/docker-pi-hole/issues/236 if you're using my docker image.  No fix yet but workaround is to not use a volume for /etc/pihole

**Comment by Mcat12** [comment]
What is the `vdns.php` script doing? Also, do you see anything in the dev tools console (F12) when you open the Query Log?

**Comment by valentingc** [comment]
Exactly the same problem since the last update (no dashboard records + no query log).
Running Pi-Hole Version v3.3, Web Interface v3.3 and FTL v3.0.

The API call `/admin/api.php?overTimeData10mins` returns: `{"domains_over_time":[],"ads_over_time":[]}`

DNS blocking however seems to work normally.
Also, the timestamp for /etc/pihole/pihole-FTL.db is updating normally.

When I open Long term data -> Query log, the following appears in console:
`jquery.min.js:4 GET http://pi.hole/admin/api_db.php?getAllQueries=empty&_=1519923459173 500 (Internal Server Error)`
Plus a Popup apears with the message `An unknown error occured while loading the data.`

php -v shows no errors:
```
$ php -v
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

Any hints?

**Comment by Mcat12** [comment]
@valentingc See @diginc's message:
> Check diginc/docker-pi-hole#236 if you're using my docker image. No fix yet but workaround is to not use a volume for /etc/pihole

**Comment by valentingc** [comment]
@Mcat12 thank you very much - I'm not using the docker image mentioned.
I'm running Raspbian Stretch & installed pi-hole via the official installer a while ago.
The only thing that could help me in https://github.com/diginc/docker-pi-hole/issues/236 is the comment to "flush old data" - could someone kindly tell me what files/folders need to be deleted?

**Comment by Mcat12** [comment]
@valentingc Oh, I had seen your (now deleted) comment on the docker repo and assumed you had the docker version.
Run `pihole -d` for a debug token.

**Comment by HereInPlainSight** [comment]
Hi there, same issue, also not using the docker image.  Token in case you need more reports: gpk68b09jt

Status: Installed Many Moons Ago, I finally updated a few minutes ago.  I'd been in the web interface just prior to performing the update, and the logs / graphs were fine.  Immediately after, the dashboard graphs 'Queries over last 24 hours' and 'Clients (over time)' graphs stopped working, and the Query Log shows 'No data available in table'.

**Comment by heroes1412** [comment]
> What is the vdns.php script doing? Also, do you see anything in the dev tools console (F12) when you open the Query Log?

This is only test script.
F12, i see console log:
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ chrome-extension://hiajdlfgbgnnjakkbnpdhmhfhklkbiol/js/jpb.js:83

Content of chrome-extension://hiajdlfgbgnnjakkbnpdhmhfhklkbiol/js/jpb.js

> chrome.extension.onMessage.addListener(
> // Returns the list of blocked URLs for this tab.
> function(request, sender, callback) {
>   if (request.action == 'getBlockedUrls') {
>     var urlObjectsList = [];
>     for (var key in sessionStorage) {
>       if (key.indexOf('jpb-url-') == 0) {
>         urlObjectsList.push(JSON.parse(sessionStorage.getItem(key)));
>       }
>     }
>     callback(urlObjectsList);
>   } else if (request.action == 'storeBlockedUrl') {
>     appendBlockedUrlList(request.blockedUrlInfo);
>   }
> });
> 
> // The object to return when window.open is called.
> var windowOpenObject = '{' +
>     'alert: function(){},' +
>     'blur: function(){},' +
>     'clearInterval: function(){},' +
>     'clearTimeout: function(){},' +
>     'close: function(){},' +
>     'confirm: function(){},' +
>     'createPopup: function(){},' +
>     'focus: function(){},' +
>     'moveBy: function(){},' +
>     'moveTo: function(){},' +
>     'open: function(){},' +
>     'print: function(){},' +
>     'prompt: function(){},' +
>     'resizeBy: function(){},' +
>     'resizeTo: function(){},' +
>     'scroll: function(){},' +
>     'scrollBy: function(){},' +
>     'scrollTo: function(){},' +
>     'setInterval: function(){},' +
>     'setTimeout: function(){},' +
>     'location: "",' +
>     'window: ""' +
>     '}';
> 
> 
> // window.open replacement function.
> var windowOpenFunction = 'window.open = function(url) {' +
>     'var blockedElement =' +
>     '    document.getElementById("javascript-popup-blocker-notify");' +
>     'blockedElement.innerHTML = url;' +
>     'blockedElement.click();' +
>     'return ' + windowOpenObject + ';' +
>     '}';
> 
> // Detects if an event came from empty anchor tag and blocks it execution.
> function blockEmptyAnchors(e) {
> 	e = e || window.event;
> 	if (e.srcElement.target && !e.srcElement.innerHTML) {
>     var blockedElement =
>         document.getElementById('javascript-popup-blocker-notify');
>     blockedElement.innerHTML = e.srcElement.href || 'about:blank';
>     blockedElement.click();
> 	  e.stopPropagation();
> 	  return false;
> 	}
> }
> 
> // Clear the sessionStorage for the top frame (tab's document).
> if (window == window.top) {
>   clearBlockedUrlList();
> }
> 
> // Checking if we should block popups on this page.
> chrome.extension.sendMessage(
>     {'action': 'isBlockedSite', 'site': document.URL}, function(response) {
>   if (response === true) {
>     var urlsButton = document.createElement('button');
>     urlsButton.id = 'javascript-popup-blocker-notify';
>     urlsButton.style.display = 'none';
>     urlsButton.addEventListener('click', popupBlocked);
>     document.documentElement.appendChild(urlsButton);
> 
>     var button = document.createElement('button');
>     button.setAttribute('onclick', windowOpenFunction);
>     button.click();
> 
>     // Converting the window object's onclick, onmouseup, onmousedown to
>     // event listeners to safely replace them with blockEmptyAnchors();
>     window.addEventListener('click', window.onclick);
>     window.addEventListener('mouseup', window.onmouseup);
>     window.addEventListener('mousedown', window.onmousedown);
> 
>     window.onclick = blockEmptyAnchors;
>     window.onmouseup = blockEmptyAnchors;
>     window.onmousedown = blockEmptyAnchors;
>   }
> });
> 
> 
> // Sends the background page the blocked URL and Notifies it
> // to show the blocked popups icon.
> function popupBlocked() {
>   var blockedElement =
>       document.getElementById("javascript-popup-blocker-notify");
>   chrome.extension.sendMessage({
>     'action': 'setPopupForBlocked',
>     'blockedUrlInfo': {
>       "blockedUrl": blockedElement.innerHTML,
>       "origin": document.location.href,
>       "isFrame": (window != window.top)}
>   });
> }
> 
> 
> // Stores blocked URLs in a sessionStorage object for this tab.
> // This function is only called for the tab's document and not its frames.
> function appendBlockedUrlList(urlInfo) {
>   sessionStorage.setItem(
>       "jpb-url-" + urlInfo.blockedUrl, JSON.stringify(urlInfo));
> }
> 
> 
> // Clears the stored list of blocked URLs for this tab.
> function clearBlockedUrlList() {
>   for (var key in sessionStorage) {
>     if (key.indexOf('jpb-url-') == 0) {
>       sessionStorage.removeItem(key);
>     }
>   }
> }

**Comment by valentingc** [comment]
Adding Adding `log-queries=extra` to `/etc/dnsmasq.d/01-pihole.conf` was the solution for me like described in https://github.com/diginc/docker-pi-hole/issues/236. Thank you guys for the help!

**Comment by Mcat12** [comment]
@HereInPlainSight Your dnsmasq config has `log-queries=extra`, but the log does not use the new formatting. Try restarting dnsmasq.

@heroes1412 Make a new debug token (the error in the console is related to one of your chrome extensions and not Pi-hole)

**Comment by dj-ar** [comment]
Not sure if it helps, but I had the same problem (additionally to no values being updated in the Web Interface).

I renamed /etc/pihole/pihole-FTL.db to pihole-FTL.db_old, run pihole -r, ran `sudo service pihole-FTL stop` and `sudo service pihole-FTL start` and everything worked again. I had this problem since I updated last week. Seems like the .db went corrupt.

**Comment by Jigsaw5279** [comment]
Moving the database file and have FTL recreate it solved the issue for me aswell.
Thanks @dj-ar

**Comment by ntalekt** [comment]
Same. Moving DB and having FTL recreate worked great. Thanks @dj-ar

**Comment by andyforceno** [comment]
Moving the database and restarting FTL didn't fix it for me, not did `pihole -r`. I can see queries in the logs, when I browse to a blocked domain I get my pihole, but the dashboard stats are not updating. 

My log file had an ownership of dnsmasq:www-data. I tried changing that to dnsmasq:pihole and root:pihole, among others, but that didn't help. I set it back to the original ownership because it's been that way for the last year or so with no issues... until the last week or two.

**Comment by brunovms** [comment]
I had the same problem, using the new FTLDNS branch, but the problem was in the setupVars.conf.

For some reason, the line API_QUERY_LOG_SHOW in /etc/pihole/setupVars.conf was set to nothing API_QUERY_LOG_SHOW=nothing.

I did not change any configurations that could relate to that, but changing the parameter to API_QUERY_LOG_SHOW=all solved the problem.

**Comment by Mcat12** [comment]
Closing this thread since the original poster has not responded in a while. Please open a new issue in the future.

**Comment by mikegleasonjr** [comment]
Just had the same issue and @dj-ar solution fixed it. It should be investigated since so many users had the same problem. For me it occured as soon as I clicked "flush logs".

**Comment by futurekill** [comment]
I'm running on Fedora 28 and the problem for me was that php-json wasn't installed :/

This fixed it for me:
`dnf install php-json`
`systemctl restart lighttpd`

**Comment by drakkhen** [comment]
Ran into the same issue here --  @dj-ar's suggestion seems to have fixed the problem.

**Comment by davygravy** [comment]
I had the same problem as [brunovms](https://github.com/brunovms)  - fixed by appending `API_QUERY_LOG_SHOW=all` to`/etc/pinhole/setupVars.conf `, since the said line was not present in the conf file.
