### ISSUE TITLE
IPv6 - DHCPv6 - Apple iOS devices show unknown for hostname and 0 for mac address

### ISSUE THREAD

**Issue by computeronix** [pi-hole/pi-hole#2003]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**
When an IPv6 is assigned through Pi-Hole DHCPv6 server it should show the proper hostname for the device.  Also I would expect it to show the proper IPv6 decimal mac address too.
**Actual behaviour:**

Windows Devices (including Xbox)
-Show the proper MAC Address in decimal format for IPv6 and IPv4
-Show the proper hostname for IPv6 and IPv4

Apple Devices
-Do not display IPv6 hostname (shows unknown)
-Do not display IPv6 proper mac address (shows 0)
-Displays proper IPv4 hostname
-Displays proper IPv4 mac address

**Steps to reproduce:**

1. Setup IPv6 with DHCPv6 support in PiHole
2. Connect an Apple iOS device to the network
3. Confirm in DHCP leases that the IPv4 address/hostname show but the IPv6 address shows but not the hostname (unknown) or mac address (0)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

xxcenwtcje

**Troubleshooting undertaken, and/or other relevant information:**

N/A - no workarounds at this time

**Comment by Tntdruid** [comment]
Must be dnsmasq end, did a test whit isc dhcp server, can see the mac address in the leases file.

**Comment by Mcat12** [comment]
@computeronix Can you still reproduce this issue? @jacobsalmela can you reproduce this?
