### ISSUE TITLE
Denmark DNSCrypt Leaks Original DNS - No Other DNS Configuration Gets Used

### ISSUE THREAD

**Issue by pierpay** [pi-hole/pi-hole#2005]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

`All DNS configuration to be in use. Pi-Hole is DHCP server. No IPv6 support. In this case there are four: eu-dk, eu-nl, org-fr, nl-ns0`

**Actual behaviour:**

`Only Denmark server works. That leaks original DNS when tested. If Denmark config is not used then
Netherlends and France config. So never all the DNS servers work together. But now no DNS leak.`

**Steps to reproduce:**

`By using DNSCrypt with two servers from Denmark and Netherlands. Also in my config as stated above I chose to have four servers from different locations. That too will result in same result.`

*Not sharing debug info due to security concerns.*

**Troubleshooting undertaken, and/or other relevant information:**

`I chose many different order of execution of servers. Tested with a single server to
a maximum of four with Pi as DHCP server. Router has a DD-WRT custom firmware and that too was rigorously checked to avoid any DNS leak. Temporary solution is not to use Denmark server. DNS leak tested at http://dnsleak.com (accurate) and at https://dnsleaktest.com (least accurate) and at https://www.grc.com/dns/dns.htm (most accurate).`

**Comment by dschaper** [comment]
Not quite sure what this has to do with Pi-hole? How can we help?

**Comment by pierpay** [comment]
Pi-Hole when in used with above DNSCrypt config fails to prevent the leak. This also bypasses ad-blocking capabilities. Only way I was able to control it is with excluding DK server from the list. While the same is given preference at https://github.com/pi-hole/pi-hole/wiki/DNSCrypt. That rather makes users vulnerable as when you check against http://dnsleaktest.com, it won't show any leak but others as stated above will reveal true information. Plus a "dig google.com @127.10.10.1 -p PORT +short" will timeout as well to confirm the same flaw. I was hoping to have some confirmation cause so far I might be the only one with this case.

**Comment by dschaper** [comment]
That seems like a problem with DNSCrypt and not with Pi-hole, we don't ship with a DNSCrypt configuration and I don't see how we could prevent things?

**Comment by dschaper** [comment]
The Wiki is community provided and edited. I've added a note to the document stating that it is as such. If the document is in error you can edit it and provide more current information.

**Comment by pierpay** [comment]
I do understand your point. I agree that this case does not point out a flaw in Pi-hole. But again since the DNSCrypt was build on it using a flawed configuration with no warnings, I feel obliged to state the issue. Okay, I will edit with correct information once I have a solid build ready. Thank you for doing so.

**Comment by dschaper** [comment]
Thanks, I do see a section in the Wiki that points to testing the installation with dnsleak, perhaps that should be highlighted and made a mandatory part of the wiki guide?

**Comment by dschaper** [comment]
Closing this issue, you can update the Wiki with the suggested improvements.
