### ISSUE TITLE
[Feature Request] Block ALL DNS Queries from selected devices

### ISSUE THREAD

**Issue by RenVer** [pi-hole/pi-hole#2006]
The idea is to block all dns queries made from some devices in the lan.
This is useful for some IoT devices that they have to connect only with devices or domain (*.lan) in the lan and not go outside the lan.

For example i have a printer connect to the lan, in the way to permit all my family to print from they pcs everywhere (in the LAN) without connect phisically the printer to the pc.
In this case, i don't would that my printer connects to domains outside my lan (it often call its manufactor's site "hp.com").
I can solve it using pi-hole, blocking the domain of manufactor of my printer ("hp.com"), but in this case, i'm unable to open the HP site from all pcs in my lan.

I dont know if it is possible to implement this feature, but i hope you can implement it.

Thanks for your attention.
Have a nice day.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Please ensure you _read_ **and** follow the issue template, it is there to help us to help you.
