### ISSUE TITLE
[Feature Request] Block ALL DNS Queries from selected devices

### ISSUE THREAD

**Issue by RenVer** [pi-hole/pi-hole#2007]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

The idea is to block all dns queries made from some devices in the lan.
This is useful for some IoT devices that they have to connect only with devices or domain (*.lan) in the lan and not go outside the lan.

**Actual behaviour:**

For example i have a printer connect to the lan, in the way to permit all my family to print from they pcs everywhere (in the LAN) without connect phisically the printer to the pc.
In this case, i don't would that my printer connects to domains outside my lan (it often call its manufactor's site "hp.com").
I can solve it using pi-hole, blocking the domain of manufactor of my printer ("hp.com"), but in this case, i'm unable to open the HP site from all pcs in my lan.

I dont know if it is possible to implement this feature, but i hope you can implement it.

Thanks for your attention.
Have a nice day.

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Thank you for taking the time to resubmit with a filled out template. You're not going to like this, i'm afraid, but rules is rules!

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
