### ISSUE TITLE
Pihole allows lookup of non-A records

### ISSUE THREAD

**Issue by bgaff** [pi-hole/pi-hole#2010]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

---
**Expected behaviour:**
If a domain is blocked NO query types should be allowed.

**Actual behaviour:**

I query graph.instagram.com for an A record and it correctly returns the IP of my PI hole, but for other record types (such as a quad-a) it is being forwarded and returned. This is a problem because as you can see in the instagram case it returns a CNAME and that CNAME doesn't HAVE to use the returned quad A record, if I was to resolve the CNAME as an A record I will get back an IP and have completely bypassed the PiHole.

```
$ dig -t A graph.instagram.com

; <<>> DiG 9.9.7-P3 <<>> -t A graph.instagram.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11869
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;graph.instagram.com.		IN	A

;; ANSWER SECTION:
graph.instagram.com.	2	IN	A	192.168.10.2

;; Query time: 49 msec
;; SERVER: 192.168.10.2#53(192.168.10.2)
;; WHEN: Mon Feb 26 21:31:27 PST 2018
;; MSG SIZE  rcvd: 64
```

```
$ dig -t AAAA graph.instagram.com

; <<>> DiG 9.9.7-P3 <<>> -t AAAA graph.instagram.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50815
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;graph.instagram.com.		IN	AAAA

;; ANSWER SECTION:
graph.instagram.com.	3341	IN	CNAME	instagram.c10r.facebook.com.
instagram.c10r.facebook.com. 59	IN	AAAA	2a03:2880:f231:c5:face:b00c::43fe

;; Query time: 47 msec
;; SERVER: 192.168.10.2#53(192.168.10.2)
;; WHEN: Mon Feb 26 21:31:31 PST 2018
;; MSG SIZE  rcvd: 114
```

```
$ dig -t A instagram.c10r.facebook.com.

; <<>> DiG 9.9.7-P3 <<>> -t A instagram.c10r.facebook.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60245
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;instagram.c10r.facebook.com.	IN	A

;; ANSWER SECTION:
instagram.c10r.facebook.com. 59	IN	A	157.240.22.63

;; Query time: 47 msec
;; SERVER: 192.168.10.2#53(192.168.10.2)
;; WHEN: Mon Feb 26 21:34:05 PST 2018
;; MSG SIZE  rcvd: 72
```

**Steps to reproduce:**

Please see the explanation above.

**Comment by bgaff** [comment]
I think the PiHole should just return an empty result set for other record types.

**Comment by dschaper** [comment]
Do you have IPv6 blocking enabled in the Pi-hole configuration?

**Comment by dschaper** [comment]
I understand what you are saying, but there's a few problems with the proposed idea. What advertisements are served over TXT/SRV/MX/SOA et. al.? `dnsmasq` is limited in what types of record responses it will handle. For instance, instead of using a host file for A/AAAA records, MX records require a separate stanza for configuration. I don't believe `dnsmasq` even has the facilities to respond for other record types.

As for the AAAA records, yes, enabling IPv6 in Pi-hole does have some relevance. See below:

```
head -n6 gravity.list
192.168.1.2 0.0.0.0
fda1:db0a:7929:1:dc0a:96ff:fe93:7938 0.0.0.0
192.168.1.2 000free.us
fda1:db0a:7929:1:dc0a:96ff:fe93:7938 000free.us
192.168.1.2 000.gaysexe.free.fr
fda1:db0a:7929:1:dc0a:96ff:fe93:7938 000.gaysexe.free.fr
```
With IPv6 enabled, the hosts file is populated with both IPv4 and IPv6 local addresses. Query a A record and you will get the IPv4 of the Pi-hole, query the AAAA and the IPv6 record is returned. There is no further progression to CNAME as an AAAA shunts the process. Without the IPv6 records in the gravity.list file, then upstream is queried.

A possible, but RFC breaking option is to attempt to instead return NXDOMAIN for blocked domains, but that would be an entirely different procedure, we would have to translate hosts files from block lists into domains and then redo the entire whitelist/blacklist model to instead scrub or add the appropriate configurations.

**Comment by DL6ER** [comment]
I agree with @dschaper that enabling `AAAA` is in fact relevant here, as only with Pi-hole configured for  IPv4 + IPv6 blocking, `AAAA` will be blocked as well. The reason for this is simple: `AAAA` results aren't loadable at all if there is no IPv6 upstream connectivity available, so we save memory by not fixing them to the Pi-hole's IP address.

> The point is that other record types can be used to completely bypass the expected behavior of the Pi hole.

If you are specifically looking for methods of bypassing Pi-hole on the DNS level, then it would be much simpler to just ask another server (or use hard-coded IP addresses!) than to try to trick around Pi-hole's blocking infrastructure.

---

Concerning the idea of returning `NXDOMAIN` for blocked domains, I must say that I like the idea and I played with it myself some time ago. I did some investigations and found that it has two main advantages:

- `dnsmasq` startup-time time is much faster (experimentally verified)
- all types of requests are blocked, not only A and AAAA
- this should resolve all issues with HTTPS slowdowns as browsers will not even try to connect to the Pi-hole's IP address so packages can also never be dropped somewhere which is known to cause timeouts for some people

A disadvantage might be that this obviously prevents the blocking page from working (which I don't use myself).

---

As a final test, I compare how we are doing it right now against how it might look like with a "catch-all" version of doing it:

How we are doing it right now:
```
$ dig MX doubleclick.net +short
20 alt1.aspmx.l.google.com.
30 alt2.aspmx.l.google.com.
50 alt4.aspmx.l.google.com.
10 aspmx.l.google.com.
40 alt3.aspmx.l.google.com.
```
With a catch-all modification using `server=/.../:
```
$ dig MX doubleclick.net +short
(no results, status is NXDOMAIN)
```

**Comment by bgaff** [comment]
Thank you both for taking the time to respond and explain this behavior. When I say that I didn't believe IPv6 was relevant, I meant that it seemed like unexpected behavior that you need a v6 interface in order to successfully block AAAA records. 

> If you are specifically looking for methods of bypassing Pi-hole on the DNS level, then it would be much simpler to just ask another server (or use hard-coded IP addresses!) than to try to trick around Pi-hole's blocking infrastructure.

Many devices do hit hard coded dns servers such as 8.8.8.8 already, which is why I personally block all DNS egress on my network unless it originates from my PiHole. Sniff your own network traffic if you have many IoT or smart devices and you'll be shocked as to how many of them actually have fallbacks to hard coded DNS servers.

I'm **strongly** in support of adding NXDOMAIN as a blocking mechanism. To respond to the other concerns address, yes, the blocking page wouldn't work but I personally don't like the blocking page either. I'd much rather not put additional load on my Pi by having it avoiding serving the HTTP request in the first place, also given how much traffic these days is on HTTPs the blocking page provides very little value at all anyway.

**Comment by conmarap** [comment]
Relevant screenshots from my end:

![screenshot_2018-03-02_13-36-42](https://user-images.githubusercontent.com/939247/36915910-5b4865d8-1e20-11e8-884e-c7517d9ca802.png)
![screenshot_2018-03-02_13-37-09](https://user-images.githubusercontent.com/939247/36915913-5c78077e-1e20-11e8-9673-3e20e646c014.png)
![screenshot_2018-03-02_13-38-13](https://user-images.githubusercontent.com/939247/36915915-5e6a993e-1e20-11e8-93c4-14a624d367bf.png)
![screenshot_2018-03-02_13-40-06](https://user-images.githubusercontent.com/939247/36915918-5f9e4530-1e20-11e8-8588-eb8eb3df89eb.png)
![screenshot_2018-03-02_13-41-21](https://user-images.githubusercontent.com/939247/36915922-60bb863a-1e20-11e8-8c2d-48a96a732615.png)
![screenshot_2018-03-02_13-42-58](https://user-images.githubusercontent.com/939247/36915924-61ed5e48-1e20-11e8-8251-2ddc4b66ac6e.png)

**Comment by PromoFaux** [comment]
>I'm strongly in support of adding NXDOMAIN as a blocking mechanism.

We've had some internal discussion about this, and it's something we're looking into working on, but it's going to take some time to make sure it's a stable alternative to using the `HOSTS` file format. We may even offer the user a choice as to which method they would like to use in their install

**Comment by dschaper** [comment]
Do you have IPv6 on the network segment? If you don't the allowing of AAAA records is a false flag. Clients can request AAAA information, but without an IPv6 address on the client, it's not going to be able to access the site.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

**Comment by PromoFaux** [comment]
@bgaff take a look at #2019

**Comment by bgaff** [comment]
@PromoFaux Awesome! I can't wait to try this out.

**Comment by Mcat12** [comment]
Can this be closed given that NXDOMAIN blocking is now available in the FTLDNS beta (https://docs.pi-hole.net/ftldns/blockingmode/), and the discussion seems to have resolved that blocking all DNS types will not be implemented?

**Comment by dschaper** [comment]
Closing for age.
