### ISSUE TITLE
Block page is only showing on "unsecure" pages

### ISSUE THREAD

**Issue by iDerp** [pi-hole/pi-hole#2011]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Block page showing on HTTP & HTTPS requests.`

**Actual behaviour:**

`Block page only shows on HTTP, not HTTPS requests`

**Steps to reproduce:**

1) Make sure the device you are using is routed through a Pi Hole DNS.

2) Go to a blocked site, whether it be blacklisted manually or from a list (for this example, we are using t.co)

3) Go to the site using [HTTP](http://t.co), you should get a page like this (CSS or something seems broken, but that's not what we are focusing on right now.) ![http://t.co being blocked](https://weed.moe/aFI7Wf9J.png)

4) Now try going to the site using [HTTPS](https://t.co). Instead of a block page, you are just given a connection error. Now this is an issue considering most sites use HTTPS and this simply gives a false understanding to the user. ![https://t.co showing connection error](https://weed.moe/qC6q9U9G.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`0mxms9cw9u`

**Troubleshooting undertaken, and/or other relevant information:**

`N/A`

**Comment by dschaper** [comment]
This is as intended, you can not intercept HTTPS/TLS traffic without presenting a TLS certificate in the name of the site. This is not operationally feasible and would be considered a breach of security as a man-in-the-middle attack.
