### ISSUE TITLE
Pi-hole local dns translation for Pi-hole adress in local network

### ISSUE THREAD

**Issue by Comodore125** [pi-hole/pi-hole#2012]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
2

---
**Expected behaviour:**
Changed local dnsmasq (pihole dnsmasq) record for most of devices in network. Things worked well. Changed pihole record and I expected pi-hole to get translated. So i could have that device accesible via shorter adress.

**Actual behaviour:**

https://screenshots.firefox.com/smFjGxXO9CEdsJzc/pi.lan3 Even though I whitelisted it after saying that nonsense to me

**Steps to reproduce:**
Add pihole local adress to local resolution of dns list. See that everything works but pihole. On dns level it is OK, but on application level the site is not alowing such visit.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
39e7ea48m9
**Troubleshooting undertaken, and/or other relevant information:**
pihole-t 
Whitelisted the name

**Comment by justinamcafee** [comment]
@Comodore125 That screenshot doesn't go anywhere.

**Comment by Mcat12** [comment]
@Comodore125 please rehost the image. What do you mean by you "changed the pihole record"?

**Comment by Comodore125** [comment]
Hello, You could close this issue. 
Pi-hole is built to be forwarded to pi.hole not pi.lan. I was using device.lan on my network with different resolver before i started using pihole dnsmasq. So again. 

Setting pi.hole in dns lan.list (which is recommended way for local dns on pihole) instead of device.lan notation is what helped. 

Thanks for help, mainly on pi-hole discource.
