### ISSUE TITLE
Pihole problem with domain interpretating

### ISSUE THREAD

**Issue by xyberdan** [pi-hole/pi-hole#2014]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
2
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
Properly working
`{A detailed description of what you expect to see}`

**Actual behaviour:**
Pihole wrong interpretating domains and do not see differrences between legit and phishing domains.

Example:
legit-domain.com
legit-domain.com.as.subdomain.on.phishing.url.com

Pihole reads "legit-domain.com.as.subdomain.on.phishing.url.com" from adlists/blacklists and in effect blocking phish and legit domain.
I must whitelisting legit domains that they would not be blocked  just like the example I gave <[-_-]> .
`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{964qe2dhem}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Please add this mandatory part of the issue template and re-open your issue afterwards.

> **Steps to reproduce:**
> `{Detailed steps of how we can reproduce this}`

I tried to do the following, based on your description:

1. Added `legit-domain.com.as.subdomain.on.phishing.url.com` for exact blocking
2. Checked that `legit-domain.com.as.subdomain.on.phishing.url.com` is blocked :white_check_mark: 
3. Checked that `legit-domain.com` is **not** blocked :white_check_mark: 

Hence, I was unable to reproduce your issue and ask for more data.
