### ISSUE TITLE
Pi-hole Version v3.2 (Update available!)

### ISSUE THREAD

**Issue by erpadmin** [pi-hole/pi-hole#2020]
Web interface is still flashing notice yet pihole -up looks proper.  tested full Reboot.

````
# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              up to date
  [i] Web Interface:    up to date

  [✓] Everything is up to date!
````

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by PromoFaux** [comment]
#1975
#1964
