### ISSUE TITLE
PiHole on Ubuntu 17.10 stops working after serving just one request

### ISSUE THREAD

**Issue by Bougakov** [pi-hole/pi-hole#2021]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

I have PiHole installed on a fresh Ubuntu 17.10 on a Hetzner virtual server. My system has only PiHole and StrongSwan IPSec VPN installed.

I have a following chain: Browser on a client (Chrome Android) -> Ubuntu server [VPN -> PiHole] -> Web

I expect to have my VPN traffic filtered by PiHole and requests to ad servers blocked by DNS.

**Actual behaviour:**

It works for a single time (I can open just one page in browser), subsequent requests time out with ERR_NAME_NOT_RESOLVED. I can see that the first request gets processed by PiHole (list in "Recent Queries" displays hosts relevant to what I have opened in browser).

**Steps to reproduce:**

Sign up for a cloud Hetzner account. Get a default image of Ubuntu 17.10. Obtain a public IP (94.130.183.54 in my case). Install StrongSwan VPN. Assign virtual pool of IPs 10.10.10.0/24 to it. Install PiHole, but don't enable DHCP. Configure it to use Google's upstream DNS. Set up forwarding of packets between pool of IPs assigned to VPN and PiHole (port 53):

<pre>root@free ~ # sudo iptables -L -n -v  --line-numbers
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      490 31153 DROP       all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            state NEW recent: UPDATE seconds: 60 hit_count: 12 name: DEFAULT side: source mask: 255.255.255.255
2      151 14765            all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            state NEW recent: SET name: DEFAULT side: source mask: 255.255.255.255
3     2027  729K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
4       77  4558 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
5       20  1016 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            state INVALID
6       11   560 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
7        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:47 ctstate NEW,ESTABLISHED
8        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:50 ctstate NEW,ESTABLISHED
9        9   424 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 ctstate NEW,ESTABLISHED
10       3   156 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:88 ctstate NEW,ESTABLISHED
11       5   300 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 ctstate NEW,ESTABLISHED
12       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1701 ctstate NEW,ESTABLISHED
13       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1723 ctstate NEW,ESTABLISHED
14       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8888 ctstate NEW,ESTABLISHED
15       0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 0
16       3  2196 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:500
17       3  3696 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:4500
18       0     0 ACCEPT     tcp  --  *      *       10.10.10.0/24        94.130.183.54        tcp dpt:53
19      35  2285 ACCEPT     udp  --  *      *       10.10.10.0/24        94.130.183.54        udp dpt:53
20      82  5148 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      448  136K ACCEPT     all  --  *      *       10.10.10.0/24        0.0.0.0/0            policy match dir in pol ipsec proto 50
2      350  181K ACCEPT     all  --  *      *       0.0.0.0/0            10.10.10.0/24        policy match dir out pol ipsec proto 50
3        0     0 ACCEPT     udp  --  *      *       10.10.10.0/24        94.130.183.54        udp spt:53 dpt:53
4        0     0 ACCEPT     tcp  --  *      *       10.10.10.0/24        94.130.183.54        tcp spt:53 dpt:53
5        0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 1735 packets, 645K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1        3   252 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8</pre>

Set up VPN server to use PiHole as DNS (see "rightdns" in /etc/ipsec.conf):

<pre>config setup
  strictcrlpolicy=yes
  uniqueids=never

conn roadwarrior
  auto=add
  compress=no
  type=tunnel
  keyexchange=ikev2
  fragmentation=yes
  forceencaps=yes
  ike=aes256gcm16-sha256-ecp521,aes256-sha256-ecp384!
  esp=aes256gcm16-sha256!
  dpdaction=clear
  dpddelay=180s
  rekey=no
  left=%any
  leftid=@free.bougakov.com
  leftcert=cert.pem
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  right=%any
  rightid=%any
  rightauth=eap-mschapv2
  eap_identity=%any
  rightdns=94.130.183.54
  rightsourceip=10.10.10.0/24
  rightsendcert=never</pre>

PiHole's DNS address gets successfully assigned to VPN clients (VPN log from client):

<pre>Mar  4 13:14:29 09[IKE] IKE_SA android[44] established between 10.227.43.222[bougakov]...94.130.183.54[free.bougakov.com]
Mar  4 13:14:29 09[IKE] scheduling rekeying in 35739s
Mar  4 13:14:29 09[IKE] maximum IKE_SA lifetime 36339s
Mar  4 13:14:29 09[IKE] installing DNS server 94.130.183.54
Mar  4 13:14:29 09[IKE] installing new virtual IP 10.10.10.1</pre>

Clients use this DNS for name lookups (tested on Windows):

<pre>C:\Users\admin>nslookup ssl.google-analytics.com
Server:  static.54.183.130.94.clients.your-server.de
Address:  94.130.183.54

Non-authoritative answer:
Name:    ssl-google-analytics.l.google.com
Addresses:  2a00:1450:4010:c01::61
          173.194.222.97
Aliases:  ssl.google-analytics.com</pre>

(Please note that DNS returns IP for a hostname from a blacklist - and this request isn't displayed in the "Recent Queries" in web interface. It appears that Hetzner's DNS took on the job as PiHole DNS gave up.)

Yet if I open terminal session on Ubuntu server and query same blacklisted host, I get correct response:

<pre>root@free ~ # nslookup ssl.google-analytics.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   ssl.google-analytics.com
Address: 94.130.183.54</pre>

Here is how the system on server reports DNS configuration:

<pre>root@free ~ # cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.1
root@free ~ # systemd-resolve --status
Global
         DNS Servers: 213.133.98.98
                      213.133.100.100
                      213.133.99.99
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 2 (eth0)
      Current Scopes: LLMNR/IPv4
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no</pre>

My only theory is that there is an issue with IPTABLES and not all DNS requests get passed to PiHole. Additionally, something happens *in* PiHole that breaks it.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

imuru9w1lk

**Comment by justinamcafee** [comment]
@Bougakov Could you these steps and check the output? 
````
#Install Pihole as normal. Make any neccessary configuration changes.
#Navigate to first webpage.
#Verify DNS lookup in PiHole
#Immediately run the below, where $X is a number of minutes, 
#probably less than 2, since you looked up the website. This should show what file is being changed.  
 find / -type f -nmin -$X  2>/dev/null 
````
