### ISSUE TITLE
Dashboard - Query Log - Undefined Domain

### ISSUE THREAD

**Issue by thexmanxyz** [pi-hole/pi-hole#2024]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The Query Log within the Dashboard should show the correct domain(s) the client tries to lookup over the Pi-hole hosted DNS server.

**Actual behaviour:**

I noticed a strange behaviour which affects certain sites that results in Query Log entries on the dashboard which contain a domain that is either `undefined` or `undefined.local`. However these two DN are never queried actively. For me it looks like that there is some issue within Pi-hole which results in rendering or storing a `undefined` domain name. It might be something like a `undefined` in Javascript or PHP. Luckily by checking my fathers browser chronic at a given time, I found an actual URL which causes this issue and got it replicated on two machines by accessing this URL. It was not that easy because I occurs very rarely. I will attach a screenshot at the end of the issue to show the results of the Query Log after opening this URL multiple times. 

The issue is not new in v3.3 because I went back a few weeks in history and I found similar entries. Additionally, it's interesting that Ghostery or uBlock Origin blocks the actual URL which causes the issue. That's why these addons MUST be disabled.

**Steps to reproduce:**
* start a browser e.g. Firefox (I didn't test Chrome)
* disable Ghostery and uBlock Origin or any other Plugin that might interference adveritsment or tracking blocking
* open [this URL](https://www.ebay.de/itm/Universal-DC-Adapter-Netzteil-mit-28-Steckeraufsatzen-fur-Laptop-HOT-NEU/302554685202?hash=item4671aa1f12:g:V3kAAOSwSzRZVcxq) which is a link to an Ebay Page (not malicious)
* maybe refresh the site a few times
* check Query Log in Dashboard for the Keyword "undefined"

![ebay_pi-hole](https://user-images.githubusercontent.com/17965908/37037031-b8c25492-2151-11e8-8bac-60e1f61c40c0.png)

**Comment by Mcat12** [comment]
It looks like it's just an issue with that web site. I checked out the requests that it makes, and it tries to make a request to `https://undefined/qdsrequests/undefined/FADE`.
This URL was constructed with these lines in one of the JavaScript files:
```javascript
function iam_reportLayerEvent(a) {
  (new Image).src = '//' + iom.waypointHost + '/qdsrequests/' + iom.surveyInvitationId + '/' + a
}
```
So those variables must have been undefined. Perhaps they are undefined because something else has been blocked.

**Comment by thexmanxyz** [comment]
@Mcat12 Thanks for your response. However may it in this case not be useful to further investigate and completely drop this requests if they are received by the DNS? Is the linked function within the Ebay JS files?
