### ISSUE TITLE
Support of Windows IOT

### ISSUE THREAD

**Issue by code-sport** [pi-hole/pi-hole#2029]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I want to use pi hole on Windows IOT. Actual there is only lunix systems supported.

**Comment by Mcat12** [comment]
From the issue template:
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

**Comment by code-sport** [comment]
Ok, I created a [new feature request](https://discourse.pi-hole.net/t/support-of-windows-iot/7816).
