### ISSUE TITLE
DNS no longer resolves after completing Pi-Hole install. 

### ISSUE THREAD

**Issue by BOLESACK** [pi-hole/pi-hole#2033]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I expected the installation of Pi-Hole to complete and become available for use.`

**Actual behaviour:**

`After completing the installation command, which does seem to succeed, the Raspberry Pi can no longer resolve any host names. `

**Steps to reproduce:**

`load NOOBS on MicroSD card, boot Raspberry PI. Install 'Raspbian GNU/Linux 9 (stretch). Run the pi-hole install command. DNS no longer works.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`I cannot upload the log because it says 'There was an error uploading your debug log I put the local copy on pastebin here: https://pastebin.com/hNnpkMF1'`

**Troubleshooting undertaken, and/or other relevant information:**

`I've attempted to assign a DNS server through the network configuration in the GUI, I've also attempted to edit the dhcpcd.conf file. I've tried using my router's IP address, 8.8.8.8, as well as 127.0.0.1, none of which worked. Between each setting change I un-plug and plug-in the ethernet cable to reset the connection `

**Comment by Mcat12** [comment]
Edit `/etc/resolv.conf` to use an external DNS server and make a new debug token.

**Comment by BOLESACK** [comment]
Editing /etc/resolv.conf to use 8.8.8.8 did not provide DNS functionality.

**Comment by BOLESACK** [comment]
I'm happy to provide any output I possibly can to help in troubleshooting. I don't know my way around Linux at all but I can run commands and save the output to my flash drive and upload it somewhere. 

At the moment, the installation is completely fresh on a new SD card and PI that I purchased for the purpose of setting up Pihole. The only commands I ran before running the pihole install were
`sudo apt-get-update` 
and
`passwd`
to change the default password of the 'pi' account to something other than the default.

**Comment by Mcat12** [comment]
What is the output of these commands?
```
dig google.com @8.8.8.8
sudo service dnsmasq status
```

**Comment by BOLESACK** [comment]
dig google.com @8.8.8.8
; <<>> DiG 9.10.3.-P4-Raspbian <<>> google.com @8.8.8.8
;; global options: +cmd
;; connection timed out; no servers could be reached

i@raspberrypi:~ $ sudo service dnsmasq status
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-09 09:12:35 UTC; 8h ago
  Process: 9903 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 9966 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 9956 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 9953 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 9965 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─9965 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -r /run/dnsmasq/resolv.conf -7 /etc/dn

Mar 09 09:12:35 raspberrypi systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Mar 09 09:12:35 raspberrypi dnsmasq[9953]: dnsmasq: syntax check OK.
Mar 09 09:12:35 raspberrypi dnsmasq[9966]: Too few arguments.
Mar 09 09:12:35 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

pi@raspberrypi:~ $

**Comment by PromoFaux** [comment]
>`connection timed out; no servers could be reached`

This suggests you have no route to the internet. Can you even `ping 8.8.8.8`?

Stupid question (very stupid question...) is your Ethernet cable plugged in? 🙈

**Comment by PromoFaux** [comment]
What are the results of :
```bash
sudo ifconfig eth0
cat /etc/dhcpcd.conf
```

Additionally, what is the IP of your router?

**Comment by BOLESACK** [comment]
I am able to ping 8.8.8.8 successfully, as well as my Routers default gateway address.

Not a stupid question, I work as a cisco network tech, yes - the cable is plugged in and I tested it on another machine, it works properly. 

pi@raspberrypi:~ $ sudo ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.28  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::da4f:5f84:1507:c608  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:f4:f1:c4  txqueuelen 1000  (Ethernet)
        RX packets 35827  bytes 25295857 (24.1 MiB)
        RX errors 0  dropped 6  overruns 0  frame 0
        TX packets 9405  bytes 761949 (744.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



pi@raspberrypi:~ $ cat /etc/dhcpcd.conf
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Most distributions have NTP support.
option ntp_servers
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private

# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.23/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

interface eth0
static ip_address=192.168.0.28/24
static routers=192.168.0.1
static domain_name_servers=8.8.8.8
static domain_search=
pi@raspberrypi:~ $

**Comment by BOLESACK** [comment]
Oops, forgot to include, the IP Address of my router is 192.168.0.1

**Comment by BOLESACK** [comment]
This issue is now resolved. The problem was local with my router. I do not know what the problem was, but about an hour ago all of the machines on my network had DNS give up the ghost on them. I did a factory reset and got everything configured - the Pi was able to connect without any issues.

**Comment by PromoFaux** [comment]
Huh, ok! Sometimes, and I'm sure you'll appreciate this as a Cisco tech, networks are made of completely baffling magic.
