### ISSUE TITLE
Internet disabled on Pi

### ISSUE THREAD

**Issue by Kazom** [pi-hole/pi-hole#2039]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---
**Expected behaviour:**

`Internet works`

**Actual behaviour:**

`I can reach my Pi on the same network, but I can no longer access the internet from my Pi nor update packages /lists. I looked at similar issues and they either were a dead end or their solution didn't work.`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Can't generate w/o internet, I have the local log but I cannot access https://tricorder.pi-hole.net to upload}`

**Troubleshooting undertaken, and/or other relevant information:**

`Restarted Pi, Turned off DHCP on router, disabled pi hole via web interface. Toggled the pihole DHCP server.`

I attached where it looks like it's failing from the log:

[i] Default IPv4 gateway: 192.168.1.254
   * Pinging 192.168.1.254...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)

*** [ DIAGNOSING ]: Ports in use
[22] is in use by sshd
[3389] is in use by xrdp
[53] is in use by dnsmasq
[80] is in use by lighttpd
[3350] is in use by dbus-daem
[3350] is in use by dbus-laun
[3350] is in use by gvfs-afc-
[3350] is in use by gvfsd
[3350] is in use by gvfsd-met
[3350] is in use by gvfs-goa-
[3350] is in use by gvfs-gpho
[3350] is in use by gvfs-mtp-
[3350] is in use by gvfs-udis
[3350] is in use by lxsession
[3350] is in use by ssh-agent
[3350] is in use by xrdp-chan
[3350] is in use by xrdp-sesm
[3350] is in use by xrdp-sess
[3350] is in use by Xvnc
[4711] is in use by pihole-FTL
[5910] is in use by Xvnc

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] irmenergy.com is 192.168.1.94 via localhost (127.0.0.1)
[✓] irmenergy.com is 192.168.1.94 via Pi-hole (192.168.1.94)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] www1.pollg.com is 2600:1700:ab31:7100:b321:49b9:d7c3:6426 via localhost (::1)
[✗] Failed to resolve www1.pollg.com via Pi-hole (2600:1700:ab31:7100:b321:49b9:d7c3:6426)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (2001:4860:4860::8888)

*** [ DIAGNOSING ]: Pi-hole processes
[✓] dnsmasq daemon is active
[✓] lighttpd daemon is active
[✓] pihole-FTL daemon is active

*** [ DIAGNOSING ]: Setup variables
    PIHOLE_INTERFACE=eth0
    IPV4_ADDRESS=192.168.1.94/24
    IPV6_ADDRESS=2600:1700:ab31:redacted
    PIHOLE_DNS_1=208.67.222.222
    PIHOLE_DNS_2=208.67.220.220
    QUERY_LOGGING=true
    INSTALL_WEB=true
    LIGHTTPD_ENABLED=1
    TEMPERATUREUNIT=F
    WEBUIBOXEDLAYOUT=boxed
    DHCP_ACTIVE=true
    DHCP_START=192.168.1.201
    DHCP_END=192.168.1.251
    DHCP_ROUTER=192.168.1.1
    DHCP_LEASETIME=24
    PIHOLE_DOMAIN=local
    DHCP_IPv6=false

*** [ DIAGNOSING ]: Dashboard and block page
[✓] X-Pi-hole: A black hole for Internet advertisements.
[✓] X-Pi-hole: The Pi-hole Web interface is working!

*** [ DIAGNOSING ]: Gravity list
-rw-r--r-- 1 root root 11560280 Mar 11 04:35 /etc/pihole/gravity.list
   -----head of gravity.list------
   192.168.1.94 0.0.0.0
   2600:1700:ab31:7100:b321:49b9:d7c3:6426 0.0.0.0
   192.168.1.94 0000mps.webpreview.dsl.net
   2600:1700:ab31:7100:b321:49b9:d7c3:6426 0000mps.webpreview.dsl.net

   -----tail of gravity.list------
   192.168.1.94 zzz.clickbank.net
   2600:1700:ab31:7100:b321:49b9:d7c3:6426 zzz.clickbank.net
   192.168.1.94 zz.zeroredirect1.com
   2600:1700:ab31:7100:b321:49b9:d7c3:6426 zz.zeroredirect1.com

**Comment by technicalpyro** [comment]
does 192168.1.254 match what your other PC's show as the default gateway if not you have a misconfiguration in your pi IPv4 settings

**Comment by Kazom** [comment]
@technicalpyro on other devices show it's 192.168.1.1  When I use pihole -r to reconfigure or even repair it always just stays at 'Update local cache of available packages...' and I can't get past that screen.

**Comment by technicalpyro** [comment]
an extreme solution would be to change resolv.conf from 127.0.0.1 to 8.8.8.8 to be able to get back out to the internet but you would need to be sure to run a reconfigure after to re enable pihole

**Comment by Kazom** [comment]
Willing to do whatever it takes to fix. I'm just shy of wiping my entire pi and starting over but I would rather not. Do I just need to find that config in /etc/ and update it?

**Comment by technicalpyro** [comment]
sudo nano /etc/resolv.conf change `127.0.0.1` to 8.8.8.8 that will set your pi's system resolver to be google rather than itself and allow you to run apt update and upgrade to get past that error then allow you to run pihole -r and select reconfigure to restore pihole functionality

**Comment by technicalpyro** [comment]
@Kazom Any update on this ?

**Comment by Kazom** [comment]
@technicalpyro Hey sorry I've been traveling! I'll try it tonight when I'm home and report back

**Comment by Kazom** [comment]
Okay tried that and can confirm it saves but internet is still a no go.

**Comment by Mcat12** [comment]
@Kazom Have you been able to resolve the no-internet situation?

**Comment by Kazom** [comment]
@mcat12 I just ended up restoring the pi. Can close.
