### ISSUE TITLE
No local queries or blocked ads?

### ISSUE THREAD

**Issue by buckwestern** [pi-hole/pi-hole#2042]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`Population of ads today and local queries is non-zero`

**Actual behaviour:**

`
Ads Today: 0%                 (Total: 0 of 0)
Local Qrys: nan%               (2 DNS servers)
`

**Steps to reproduce:**

`like this all the time`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`rtfynk4ck6`

**Troubleshooting undertaken, and/or other relevant information:**

`flushed log, checked DHCP, queried new sites, traveled to high-ad-traffic sites, verified that ads ARE being blocked.`

**Comment by technicalpyro** [comment]
is the time set properly on your system if the time is not accurate your time based statistics will not who properly best practice it to use NTP server local to you

**Comment by buckwestern** [comment]
Good morning,

Yes, the date is correct and is being updated.

**Comment by technicalpyro** [comment]
is logging enabled `pihole -l on`

**Comment by buckwestern** [comment]
I executed that command...lets see what happens.

thank you.

**Comment by buckwestern** [comment]
Still nothing:

Pi-hole Chronometer
 
 Press Ctrl-C to exit
 ——————————————————————————————————————————————————————————
  Hostname: piweather          (Raspberry Pi 1, Model B)
    Uptime: 1 day, 18:38:06                                                                                                                               
 Task Load: 0.02 0.07 0.08     (Active: 3 of 36 tasks)
 CPU usage: 8%                 (700 MHz @ 320k)
 RAM usage: 25%                (Used: 91 MB of 371 MB)
 HDD usage: 45%                (Used: 2 GB of 4 GB)
  LAN addr: 192.168.100.10     (Gateway: 192.168.100.1)
   Pi-hole: Active             (Blocking: 121709 sites)
 Ads Today: 0%                 (Total: 0 of 0)
Local Qrys: nan%               (2 DNS servers)
   Blocked:                                                                                                                                               
Top Advert:                                                                                                                                               
Top Domain:                                                                                                                                               
Top Client:

**Comment by buckwestern** [comment]
This is solved, web service and FTL were 3.3 and 3.0 respectively.  Documentation should be updated for the entire downgrade.

cd /etc/.pihole
sudo git checkout v3.2.1
cd /var/www/html/admin
sudo git fetch --tags
sudo git checkout v3.2.1
pihole -r
pihole checkout ftl v2.13.2
pihole -r


Thank you for your help.
