### ISSUE TITLE
Dashboard not showing data, Query log empty

### ISSUE THREAD

**Issue by alecuba** [pi-hole/pi-hole#2045]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by alecuba** [comment]
I have read about this issue an tried several of the solutions I found but still I don't get to see any data on the dashboard. I repaired pi-hole and still does not shows data, but apparently it does blocks adds. Anyone some other ideas. I noticed dnsmask issues, tried reinstalling too.

**Comment by alecuba** [comment]
root@raspi-afa:~# pihole -v
  Pi-hole version is v3.3 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)

**Comment by Mcat12** [comment]
> You must follow the template instructions. Failure to do so will result in your issue being closed.

Please fill out the template. We don't have enough information to help you effectively.

**Comment by alecuba** [comment]
In raising this issue, I confirm the following: 

[x] I have read and understood the contributors guide.
[x] The issue I am reporting can be replicated.
[] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).
How familiar are you with the the source code relevant to this issue?:

{Replace this with a number from 3 }

Expected behaviour:

Dashboard showing data, Query log to show entries

Actual behaviour:

Dashboard not showing data, Query log empty

Steps to reproduce:

Updated system, applications and Repaired Pi-hole

Debug token provided by uploading pihole -d log:  4v8457sbka

Troubleshooting undertaken, and/or other relevant information: 

I have read about this issue an tried several of the solutions I found but still I don't get to see any data on the dashboard. I repaired pi-hole and still does not shows data, but apparently it does blocks adds. Anyone some other ideas. I noticed dnsmask issues, tried reinstalling too.
root@raspi-afa:~# pihole -v
Pi-hole version is v3.3 (Latest: v3.3)
AdminLTE version is v3.3 (Latest: v3.3)
FTL version is v3.0 (Latest: v3.0)

Tested dig
root@raspi-afa:~# dig s.amazon-adsystem.com | grep amazon
; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> s.amazon-adsystem.com
;s.amazon-adsystem.com. IN A
s.amazon-adsystem.com. 11 IN A 72.21.206.140

{Please delete this quoted section when opening your issue}
You must follow the template instructions. Failure to do so will result in your issue being closed.
Please submit any feature requests here, so it is votable and trackable by the community.
Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
This template was created based on the work of udemy-dl.
