### ISSUE TITLE
DHCP firewall rules not enabled during install

### ISSUE THREAD

**Issue by JamesPGriffith** [pi-hole/pi-hole#2046]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`When pi-hole is the only DHCP server on the network it should provide IPs`

**Actual behaviour:**

`Clients are not recieving IPs from pi-hole`

**Steps to reproduce:**

`Install CentOS
Install pi-hole
Disable all DHCP servers on the network
Enable DHCP server on pi-hole`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`zjx6dbocge`

**Troubleshooting undertaken, and/or other relevant information:**

`[james@pi-hole ~]$ rpm -q --whatprovides /etc/redhat-release 
centos-release-7-4.1708.el7.centos.x86_64
[james@pi-hole ~]$

Installed pi-hole
Disabled all DHCP services on the network
Enabled DHCP service on pi-hole
Checked /var/log/pihole.log and did NOT find any errors
Checked the firewall...

[james@pi-hole ~]$ sudo firewall-cmd --get-active-zones
public
  interfaces: eth0
[james@pi-hole ~]$ sudo firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client http dns
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
[james@pi-hole ~]$ 

-----

Pulled line 1428:
firewall-cmd --permanent --add-service=http --add-service=dns
END

Added DHCP:
firewall-cmd --permanent --add-service=http --add-service=dns --add-service=dhcp --add-service=dhcpv6
END

[james@pi-hole ~]$ sudo firewall-cmd --permanent --add-service=http --add-service=dns --add-service=dhcp --add-service=dhcpv6
Warning: ALREADY_ENABLED: http
Warning: ALREADY_ENABLED: dns
success
[james@pi-hole ~]$ sudo firewall-cmd --reload
success
[james@pi-hole ~]$ sudo firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client http dns dhcp dhcpv6
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
[james@pi-hole ~]$ 

SUCCESS!
pi-hole is now handing out IPs`

**Comment by JamesPGriffith** [comment]
Data after the first couple of DHCP addresses were provided to clients: `jowi47nz22`

**Comment by Mcat12** [comment]
So your issue is that your firewall isn't letting you send DHCP information from the Pi-hole to the clients?

**Comment by JamesPGriffith** [comment]
Correct.

During install and reconfiguration there is a point where it asks to open the firewall ports for http (web server) and DNS (the whole point of pi-hole).  It does not mention or configure for the DHCP service capability.

When enabling DHCP in the WebUI it does not mention the need to either allow pi-hole to reconfigure the firewall for this new service nor does it mention needing to manually execute the command.

**Comment by Mcat12** [comment]
But after opening the firewall for DHCP, it works?

**Comment by JamesPGriffith** [comment]
Correct

**Comment by dschaper** [comment]
@bcambl Do you want to take a crack at this on the firewall ruleset? Ports 67/68 for DHCP traffic.

**Comment by dschaper** [comment]
We're going to create a document page with the required ports and the methods to open those ports on the host firewall. We don't feel that opening the ports on servers is something we should be doing. Thanks for the report and we'll get the documents up shortly.
