### ISSUE TITLE
Apple iDevices Purchases Ignored While PiHole is Running including Touch ID

### ISSUE THREAD

**Issue by 91ajames** [pi-hole/pi-hole#2048]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting isn't a duplicate

**How familiar are you with the the source code relevant to this issue?:**

`8`

---
**Expected behaviour:**

`To install stuff from the Apple App Store`

**Actual behaviour:**

`Not able to install apps while PiHole is currently running`

**Steps to reproduce:**

`iPod, or iPhone/iPad with Touch ID
Search any app, install it, the Get button circles as usual but instead of installing or a pop -up touch ID pop Screen, the Get spinning circle Stops almost instantly after tapping on it.`

**Troubleshooting undertaken, and/or other relevant information:**

`By disabling Pi-Hole for 5 mins each time if i want to install something.`
`I've check the query logs from pi-hole of my iPad and no other url comes into play to even remotely whitelist of the confusion of purchase apps.`

**Comment by Mcat12** [comment]
If it works when Pi-hole is disabled, then there must be some domain that is getting blocked. Please see:
https://discourse.pi-hole.net/t/how-do-i-determine-what-domain-an-ad-is-coming-from/1522

Also, if you have installed extra block lists, then those might be blocking the necessary domain.

**Comment by b264** [comment]
Are you sure this is a bug?  It sounds like a feature to me

**Comment by 91ajames** [comment]
Ok, looks like one of 32 block list that I have is plugging a block directly to this address from apple, with one i am not sure at the current moment. bc each time i tried it was a succesful instead of a failed "are you sure confirmed purchase install".

I'll leave this here for anyone needed what address, I'll list the ones I added in a couple hrs or a day from now, down below after the tail logs

p11-buy.itunes-apple.com.akadns.net

Mar 25 18:43:47 dnsmasq[688]: 31296 ##.0.1.##/65513 query[A] p11-buy.itunes-apple.com.akadns.net from 10.0.1.##
Mar 25 18:43:47 dnsmasq[688]: 31296 ##.0.1.##/65513 cached p11-buy.itunes-apple.com.akadns.net is 17.173.66.102
Mar 25 18:43:47 dnsmasq[688]: 31297 ##.0.1.##/50232 query[AAAA] p11-buy.itunes-apple.com.akadns.net from 10.0.1.17
Mar 25 18:43:47 dnsmasq[688]: 31297 ##.0.1.##/50232 forwarded p11-buy.itunes-apple.com.akadns.net to 8.8.8.8
Mar 25 18:43:47 dnsmasq[688]: 31297 ##.0.1.##/50232 reply p11-buy.itunes-apple.com.akadns.net is NODATA-IPv6
