### ISSUE TITLE
Speedport DHCPv6 ra-param Pi-Hole DNS IPv6

### ISSUE THREAD

**Issue by jonathanmmm** [pi-hole/pi-hole#2051]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting is more like a new approach to an old topich (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

I am not very familiar with the code (1).

**Hoped behaviour:**

Pi-Hole sends his DNS over IPv6 and Router sends himself as Gateway and gives the global IPv6 Adresses

**Hope that you can help me:**

I have an Speedport Smart, I can disable IPv4 DHCP and use the Pi for that, but I can´t disable DHCPv6 on the Speedport Smart or disable IPv6 in general. Another Router would solve the problem, but would´nt give us free Wi-Fi from Telekom and FON in the World, I also thought about putting a FritzBox behind the Speedport but would try to do it without, because it costs and increases complexity and the Speedport doesn´t Delegates Prefixes so IPv6 would be dead in my network.

I found in different forums and Issues many approaches, I could get to the Hidden (Engineer) Menu, but I can´t change and only look at the data so it is for no use. I have Easy Support Activated, because the Speedport is not owned by me. But also with Easy Support disabled I can´t change any IPv6 Settings.
Telekom doesn´t have a Router with WLAN TO GO Support and the ability to change IPv6 (if you know differently I would be happy).

I found the following: 

> http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
> 
> --ra-param=<interface>,[mtu:<integer>|<interface>|off,][high,|low,]<ra-interval>[,<router lifetime>]
>    Set non-default values for router advertisements sent via an interface. The priority field for the router > may be altered from the default of medium with eg --ra-param=eth0,high. The interval between router > advertisements may be set (in seconds) with --ra-param=eth0,60. The lifetime of the route may be 
> changed or set to zero, which allows a router to advertise prefixes but not a route via itself. 
> --ra-parm=eth0,0,0 (A value of zero for the interval means the default value.) All four parameters may > be set at once. --ra-param=eth0,mtu:1280,low,60,1200

> The interface field may include a wildcard.

> The mtu: parameter may be an arbitrary interface name, in which case the MTU value for that interface > is used. This is useful for (eg) advertising the MTU of a WAN interface on the other interfaces of a 
> router. 

## These are the recommendations I found on different Issues, but I believe it is something between.

ra-param=eth0,high,10,1200 (https://github.com/pi-hole/pi-hole/issues/1512)

ra-param=*,0,0 (https://github.com/pi-hole/pi-hole/issues/1212)

The Pi-Hole DHCPv6/SLAAC should send with High Priority but only it´s DNSIPV6 and no IPv6 Gateway or anything differently.

Hope you can help me, to get a stable work around, that all devices (Especially Android that doesn´t support DHCPv6) get the DNS IPv6 of the Pi-Hole (local ULA) and get global IPv6 and Gateway and so on from the router. So the Raspberry Pi should only overwrite the IPv6 DNS settings.

**Comment by jonathanmmm** [comment]
https://discourse.pi-hole.net/t/issue-speedport-dhcpv6-ra-param-pi-hole-dns-ipv6/8192
There is the issue also.

**Comment by Mcat12** [comment]
This looks like more of a dnsmasq or networking issue, correct? You might have more luck on the dnsmasq mailing list or a forum specializing in your router.
