### ISSUE TITLE
Is there any built-in (or external) scheduling function available?

### ISSUE THREAD

**Issue by E3V3A** [pi-hole/pi-hole#2052]
I'm looking to control the filtering by time scheduling. 
For example, automatically blocking YouTube between certain times of the day. 

* Is there any such functionality already built-in to pi-hole? 
* If not, does someone know of any other solutions or work-around to do this? (Or something that could en/disable pi-hole according to a schedule?)

If none of above, please consider this as a feature request. 
Thanks in advance,
E:V:A

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Hi @E3V3A , please make sure you read and follow the instructions on the issue template. There is a section relevant to feature requests there. Also, worth noting, for general discussion, [Discourse](https://discourse.pi-hole.net) is probably a better place than Github.

Cheers!

**Comment by E3V3A** [comment]
Unfortunately the template doesn't apply to the question, which is why I ignored it. But, yes, I certainly missed the discourse forum. Thank you.
