### ISSUE TITLE
No Graphs or Query logs after fresh install on DSM

### ISSUE THREAD

**Issue by Waliers** [pi-hole/pi-hole#2063]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
'2'

---
**Expected behaviour:**

`Graphs in Pi-Hole web interface`

**Actual behaviour:**

`No graphs and no Query log's even tho blocking works`

**Steps to reproduce:**

`Installation of Pi-hole on DSM 6.1.5-15254 Update 1 following this guide: https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289/7 `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`1kkcmba6qp`

**Troubleshooting undertaken, and/or other relevant information:**

- Reinstalling PiHole
- Run a pihole -f
- Run a pihole -r 
- Adding log-queries to /etc/dnsmasq.d/01-pihole.conf 
- Adding log-queries=extra to /etc/dnsmasq.d/01-pihole.conf (then DNSmasq doesn't start anymore)
-  renamed /etc/pihole/pihole-FTL.db to pihole-FTL.db_old, run pihole -r, ran sudo service pihole-FTL stop and sudo service pihole-FTL start
- Stopping and starting Logging

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-cant-i-run-pi-hole-v3-3-on-raspbian-jessie-or-with-dnsmasq-v2-72/8052

**Comment by Mcat12** [comment]
Once FTLDNS is released, then this dnsmasq version issue will be resolved because we will ship an up to date version included inside of FTL.
