### ISSUE TITLE
Multiple IP ranges (one per interface) seems to not work correctly

### ISSUE THREAD

**Issue by 2Belette** [pi-hole/pi-hole#2065]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Multiple range of IP addresses should work as expected in dnsmask with tags`

**Actual behaviour:**

`Pihole installed on a custom system
Only one Range is displayed in the UI (I can understand this)
IP from wireless interface is provided to my Ethernet interface
`

**Steps to reproduce:**

adding this to 01-pihole.conf 
```
interface=wlan1
interface=eth0
```

adding this to 02-pihole-dhcp.conf 
```
dhcp-range=set:wlan,10.0.1.1,10.0.1.10,24h
dhcp-range=set:lan,10.0.2.1,10.0.2.10,24h
dhcp-option=tag:wlan,option:router,10.0.1.254
dhcp-option=tag:lan,option:router,10.0.2.254
```

adding this to 04-pihole-static-dhcp.conf 
```
dhcp-host=set:lan,12:51:C6:8D:67:9E,10.0.1.1,hp
dhcp-host=set:wlan,41:E8:77:32:1B:58,10.0.2.5,dell
```
My wireless network is receiving the range from my Ethernet network, sometimes the reverse..
Under DNS tab -> Interface listening behavior, only my public ethernet interface from my routeur is displayed not one of the two (LAN/WLAN) I set in my 01-pihole.conf.
Perhaps the configuration format is wrong in my file when I want to use two interfaces, should I try something different? I have tried: `interface=wlan1,etho` with no success

Any clue what I am doing wrong?

Many thanks

**Comment by Mcat12** [comment]
We don't support multiple IP ranges through the UI and our configuration tools. However, since we use dnsmasq you can just manually edit the files like you did.

**Comment by 2Belette** [comment]
Thanks @Mcat12, so as I suspected the UI is not supporting this and it is not my main issue. As I explained the IP range provided is mixed-up and I don't receive the IP I supposed to receive on my machine, any idea/suggestion on the configuration file for this to work ?

**Comment by Mcat12** [comment]
See dnsmasq's configuration: http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
