### ISSUE TITLE
PiHole installer is broken, changes the DNS before doing the git pull

### ISSUE THREAD

**Issue by keeepcool** [pi-hole/pi-hole#2066]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
6

---
**Expected behaviour:**

Run curl -sSL https://install.pi-hole.net | bash
And it actually finishes installing pi-hole instead of leaving a Pi without internet access.

**Actual behaviour:**
```
curl -sSL https://install.pi-hole.net | bash -x
+ set -e
+ installLogLoc=/etc/pihole/install.log
+ setupVars=/etc/pihole/setupVars.conf
+ lighttpdConfig=/etc/lighttpd/lighttpd.conf
+ coltable=/opt/pihole/COL_TABLE
+ webInterfaceGitUrl=https://github.com/pi-hole/AdminLTE.git
+ webInterfaceDir=/var/www/html/admin
+ piholeGitUrl=https://github.com/pi-hole/pi-hole.git
+ PI_HOLE_LOCAL_REPO=/etc/.pihole
+ PI_HOLE_FILES=(chronometer list piholeDebug piholeLogFlush setupLCD update version gravity un
+ PI_HOLE_INSTALL_DIR=/opt/pihole
+ useUpdateVars=false
+ IPV4_ADDRESS=
+ IPV6_ADDRESS=
+ QUERY_LOGGING=true
+ INSTALL_WEB=true
++ stty size
++ echo 24 80
+ screen_size='24 80'
++ echo '24 80'
++ awk '{print $1}'
+ rows=24
++ echo '24 80'
++ awk '{print $2}'
+ columns=80
+ r=12
+ c=40
+ r=20
+ c=70
+ skipSpaceCheck=false
+ reconfigure=false
+ runUnattended=false
+ [[ -f /opt/pihole/COL_TABLE ]]
+ COL_NC='\e[0m'
+ COL_LIGHT_GREEN='\e[1;32m'
+ COL_LIGHT_RED='\e[1;31m'
+ TICK='[\e[1;32m✓\e[0m]'
+ CROSS='[\e[1;31m✗\e[0m]'
+ INFO='[i]'
+ DONE='\e[1;32m done!\e[0m'
+ OVER='\r\033[K'
+ counter=0
+ [[ '' != true ]]
+ main
+ local 'str=Root user check'
+ echo ''

+ [[ 1000 -eq 0 ]]
+ echo -e '  [\e[1;31m✗\e[0m] Root user check
      \e[1;31mScript called with non-root privileges\e[0m
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source\n'
  [✗] Root user check
      Script called with non-root privileges
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source

+ echo -ne '  [i] Sudo utility check'
  [i] Sudo utility check+ command -v sudo
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Sudo utility check'
  [✓] Sudo utility check
+ exec curl -sSL https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/b
+ sudo bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail


  [✓] Stopping dnsmasq service...

  [✓] Stopping lighttpd service...
  [i] Using interface: eth0
  [i] Using Google DNS servers
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.1.6/24
  [i] IPv6 address:
  [i] Web Interface On
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...
  Error: Could not update local repository. Contact support.
```

**Steps to reproduce:**

RASPBIAN STRETCH LITE iso downloaded 30 minutes ago, SHA-256 checksum matching.
Use etcher to create SD Card, run 
curl -sSL https://install.pi-hole.net | bash -x
Did this 3 times already.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

There is no token, pihole isn't not installed at all.

**Troubleshooting undertaken, and/or other relevant information:**

As far as I understand, pihole installer kills the internet access to the pi by changing its network config before doing the git pull, so it always fails.

> * 
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
What hardware are you installing on? This is certainly new behaviour (to me, at least)

**Comment by keeepcool** [comment]
RPI 3 B+

And I must been doing something stupid, another clean image, pulled the repo manually, installed, its working.

This is pretty polished, wow!

Can I delete this?

Maybe I did something wrong, so I started fresh, and read the manual line by line, most likely was jumping a step.

Sorry for opening the issue :/

**Comment by PromoFaux** [comment]
It may be a bug, though not sure what the Pi 3 B + would be doing differently to other Pis! I have one on my desk, but not gotten around to booting it up yet, so we'll leave this open for now on the off chance...

**Comment by dschaper** [comment]
The IP addressing is done by writing a block to the `/etc/dhcpcd.conf` file. That is what the installer does, and that file does not get re-read untill the Raspberry Pi is rebooted, or the networking subsystem is restarted. We don't manually call for a nework restart. The installer asks you for a Static IP address that should already be in use on the device, that's why we don't call for a network restart.

**Comment by keeepcool** [comment]
May be my modem doing something. I assigned a static IP tied to my PI, but during the install a new IP called lwip shows up, my modem/router is an Huawei B593-S22, its a 4G modem, and the software is getting ancient, with the latest release from 2014, and its running an unlocked version, so, it might indeed be my modem cutting access to the Pi.

Just configured everything, and its so smooth!

Definitively going to send you guys some beer money, also, thanks for the blazing fast responses!

**Comment by Mcat12** [comment]
Reopen if the issue comes up again.
