### ISSUE TITLE
After dnsmasq update to 2.76 still no query log entry - pi-hole 3.3 Raspbian Jessie  

### ISSUE THREAD

**Issue by squibber** [pi-hole/pi-hole#2067]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---
**Expected behaviour:**

Query log shows log entries

**Actual behaviour:**

Query log is empty

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

ekf739sdlz

**Troubleshooting undertaken, and/or other relevant information:**

Pi-hole Version v3.3 Web Interface Version v3.3 FTL Version v3.0

I am running pi-hole v3.3 on raspbian jessie and I am aware of the dnsmasq problem and followed your advise to update dnsmasq to version 2.76. The dashboard is looking fine and pi-hole blocks as expected but still I do not see any entries in query log. I flushed the logs several times, rebooted the system but to no avail.

**Comment by Mcat12** [comment]
What is the output of `echo ">getallqueries" | nc localhost 4711 | head`

**Comment by squibber** [comment]
The output is

1546210824 IPv4 f3.shared.global.fastly.net 1-178-168-194.static.virginm.net 2 0
1546210840 IPv4 clientservices.googleapis.com 1-178-168-194.static.virginm.net 2 0
1546210848 IPv4 player.vimeo.com 1-178-168-194.static.virginm.net 2 0
1546210849 IPv4 f3.shared.global.fastly.net 1-178-168-194.static.virginm.net 2 0
1546210873 IPv4 2.client-channel.google.com 1-178-168-194.static.virginm.net 2 0
1546210884 IPv4 www.google.com 1-178-168-194.static.virginm.net 2 0
1546210890 IPv4 f3.shared.global.fastly.net 1-178-168-194.static.virginm.net 2 0
1546210893 IPv4 securepubads.g.doubleclick.net 1-178-168-194.static.virginm.net 1 0

**Comment by squibber** [comment]
No one having a clue what is going on here?

**Comment by squibber** [comment]
I updated Pi-hole to the latest version v3.3.1 and generated a new debug token:

Debug token provided by uploading pihole -d log:
2qtwl0q19v

**Comment by squibber** [comment]
It is getting worse.. after updating to 3.3.1 there is no data shown in the dashboard anymore. So no dashboard data and no query entries..

**Comment by Mcat12** [comment]
Sorry, this thread was somehow lost from my list. If you open the dev tools (F12) and refresh the page, do you see any errors in the console or network tabs? What browser are you using to test?

Also, what is the output of this command?
```
echo ">stats" | nc localhost 4711
```

**Comment by squibber** [comment]
I am using the latest Firefox 59.0.2.

Opening the dev tools and refreshing the page reveals in the console

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (NAVIGATOR, OBJECT) {

    OBJ....
index.php:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (ERROR) {

    const V8_STACK_....

Translated: The page’s settings blocked the loading of a resource at self..

**Comment by squibber** [comment]
`echo ">stats" | nc localhost 4711`

domains_being_blocked 122931
dns_queries_today 0
ads_blocked_today 0
ads_percentage_today 0.000000
unique_domains 0
queries_forwarded 0
queries_cached 0
clients_ever_seen 0
unique_clients 0
status enabled
---EOM---

**Comment by squibber** [comment]
I just restarted the system and now it seems working fine. Thanks for your time anyway.
