### ISSUE TITLE
Possible solution for slow HTTPS resolution

### ISSUE THREAD

**Issue by beerisgood** [pi-hole/pi-hole#2071]
Thanks for this [guy](https://forum.kuketz-blog.de/viewtopic.php?p=6814#p6814) (german site) now blocked HTTPS sites like "https://secure.quantserve.com/quant.js" give me a nearly instant 404 instead of slow timeout.

Now i wonder if we can customize 127.0.0.1/24 /(IPv4) and ::1/128 (IPv6) to get the Website blocked site from PiHole

**Comment by DL6ER** [comment]
Please submit this feature request on [Discourse](http://discourse.pi-hole.net/) where we can properly discuss it.
