### ISSUE TITLE
Support Cloudflare 1.1.1.1 DNS Resolver

### ISSUE THREAD

**Issue by jordan-wright** [pi-hole/pi-hole#2072]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Today Cloudflare [announced](https://blog.cloudflare.com/announcing-1111/) a new "privacy-first" DNS resolver at 1.1.1.1 and 1.0.0.1. You can find the full details [here](https://1.1.1.1/).

[DNSPerf](https://www.dnsperf.com/#!dns-resolvers) is claiming that, at this time, 1.1.1.1 outperforms other popular DNS resolvers.

With the performance improvements, the claims to focus on privacy, and the backing of a stable company, I think it's worth considering adding this as a "prebuilt" option for upstream DNS resolvers in Pi-Hole.

**Actual behaviour:**

The resolvers are currently not listed as an option.

Happy to help implement this, I'm just not sure where all it needs to be added. I saw references in AdminLTE and the basic install script. If that's all that's needed, I can give this a shot.

**Comment by OmgImAlexis** [comment]
Once this is merged https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/savesettings.php#L119 needs to be updated.

**Comment by Jasin2069** [comment]
Would be nice if it could forward with dns over https too

**Comment by nareddyt** [comment]
Reminder to update the [Upstream DNS Providers wiki page](https://github.com/pi-hole/pi-hole/wiki/Upstream-DNS-Providers) when this feature is released.

**Comment by michaeldavie** [comment]
The notes for [Release v3.3.1](https://github.com/pi-hole/pi-hole/releases/tag/v3.3.1) say that this change has been added, but it doesn't look like it's made it all the way up to the AdminLTE interface yet.

**Comment by Mcat12** [comment]
It has been added to the list of servers seen in the installer, but only a Core update has been released.

**Comment by Mcat12** [comment]
For clarification: The changes are in development, and will be released as part of 4.0. They were added to the 3.3.1 changelog by mistake.
