### ISSUE TITLE
Debug Log: Problem with RaspberryPi 3 processor readout

### ISSUE THREAD

**Issue by Perflyst** [pi-hole/pi-hole#2074]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

`PiHole debug log cannot read model from rpi3 processor and returns an error instead`

**Actual behaviour:**

`*** [ DIAGNOSING ]: Processor`
`/opt/pihole/piholeDebug.sh: line 474: $'[\E[32m✓\E[0m] \E[32marmv7l\E[0m': command not found`

**Steps to reproduce:**

`execute pihole -d on a rpi 3`
`(Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux) `

**Comment by Mcat12** [comment]
Fixed by #1987
