### ISSUE TITLE
SSL ads cause return ssl_error_unrecognized_name_alert

### ISSUE THREAD

**Issue by alecks68** [pi-hole/pi-hole#2079]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4
---
**Expected behaviour:**

Blocking also https Ads without causing browser to pop up window 

**Actual behaviour:**

Ads that are in https causing an "ssl_error_unrecognized_name_alert" which in turn pops up a window on Chrome Android.

**Steps to reproduce:**
Raspberry Pi, stretch/Debian9.
Apache2 webserver with Certbot/Let's encrypt https certificate
Lighttpd removed
Openvpn pushes DNS to pi-hole/dnsmasq
/etc/openvpn/server.conf: push "dhcp-option DNS 10.8.0.1"
/etc/dnsmasq.conf: listen-address=10.8.0.1

Pi-hole is setup to block all ads for all users (and only those) coming in through openvpn.
Apache Webserver with owncloud and certificate is running in parallel.

Ad blocking works well for http ads.
If the ad points to an https site, apache will return ssl_error_unrecognized_name_alert. On Android mobile devices (Huawei P10) this will cause the Chrome web brower to open a pop up window for each ad.

Is there any possibility to suppress or better change the return ssl_error_unrecognized_name_alert from the raspberry apache web server, e.g. by letting dnsmasq answer with an invalid ip or anything similar or any other idea for the overall setup/configuration.

**Comment by Mcat12** [comment]
Because you removed lighttpd and added your own SSL cert, that is the reason you see the error.

You will need to modify your custom setup to only use the SSL cert if the request is for the right domain.

There is no way to return different DNS responses based on the protocol, because DNS is a layer below the protocol.

**Comment by alecks68** [comment]
Thanks Mcat12. Based on your remark I played a little bit with the configuration and following works for me (if anyone else wants to create a similar setup)
Reinstallation of pi-hole without Webinterface and query log leads to following /etc/pihole/setupVars.conf probably re-routing the https requests to 0.0.0.0 with ERR_ADDRESS_INVALID instead of SSL error.
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=0.0.0.0
IPV6_ADDRESS=::/0
PIHOLE_DNS_1=85.214.20.141
PIHOLE_DNS_2=194.150.168.168
QUERY_LOGGING=false
INSTALL_WEB=false
LIGHTTPD_ENABLED=0
