### ISSUE TITLE
Whitelist doesn't appear to be working

### ISSUE THREAD

**Issue by SwarfegaGit** [pi-hole/pi-hole#2080]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Whitelisted

**Actual behaviour:**

Blocked

**Steps to reproduce:**

See post below where I do a fresh install of Raspbian and PiHole (no import of existing config) and the same symptoms persist.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

961rq2dukh

**Troubleshooting undertaken, and/or other relevant information:**

I think the issue started yesterday when I did a "pihole -r" to reconfigure it to forward requests to 1.1.1.1 and 1.0.0.1.  This was the only change made.  I've had two people in my house complain they can't get on to various sites, after investigation I found the pihole is blocking sites on my whitelist.

Here's an image I get in Chrome showing the site just resolving.

[Imgur](https://i.imgur.com/RiwAdiJ.png)

This is the domain in my whitelist

[Imgur](https://i.imgur.com/5zL6DQJ.png)

This is the log showing it's being blocked

[Imgur](https://i.imgur.com/HGxubrJ.png)

Steps taken:

Teleported an export of my config.  
Uninstalled pihole, rebooted and then reinstalled.  
Imported previous config.  

Still seeing the same issue.

What I find odd though is doing a lookup shows that it is being whitelisted...

    Resolve-DnsName -Name googleadservices.com -Server 192.168.1.20
    
    Name                                           Type   TTL   Section    IPAddress
    ----                                           ----   ---   -------    ---------
    googleadservices.com                           A      299   Answer     216.58.201.2

Compare this to a blocked site...

    Resolve-DnsName -Name mads.amazon-adsystem.com -Server 192.168.1.20
    
    Name                                           Type   TTL   Section    IPAddress
    ----                                           ----   ---   -------    ---------
    mads.amazon-adsystem.com                       AAAA   2     Answer     fd00::1:30c6:ed40:b8e1:8183
    mads.amazon-adsystem.com                       A      2     Answer     192.168.1.20

I can confirm though if I 'Disable' the PiHole from the admin interface the URL for that advert works.

**Comment by sous-studio** [comment]
Same here.

**Comment by PromoFaux** [comment]
What version are you both on?

**Comment by sous-studio** [comment]
3.3.1

**Comment by sous-studio** [comment]
Locale fix did not help, in my case.

**Comment by technicalpyro** [comment]
please attempt the following `pihole -g -f` we found while troubleshooting this issue that fliushing of the existing lists was required

**Comment by SwarfegaGit** [comment]
> Locale fix did not help, in my case.

What is this?

> please attempt the following pihole -g -f we found while troubleshooting this issue that flushing of the existing lists was required to have the fix take effect

Still seeing the same issue.

**Comment by sous-studio** [comment]
@SwarfegaGit Locale fix: "export LC_ALL=C in graviti.sh" - did not help.

pihole -g -f - does not help at all.

**Comment by sous-studio** [comment]
It's like for some reason Whitelist is completely ignored. Best guess is anti-ads lists somehow supersede whitelist or it's just plainly ignored.

**Comment by PromoFaux** [comment]
>query[A] www.googleadservices.com

>pi@raspberrypi:~ $ cat /etc/pihole/whitelist.txt
googleadservices.com

One of these things is not like the other ;)

**Comment by SwarfegaGit** [comment]
No they are not the same but does unblocking the top level domain not unblock all sub records?

**Comment by sous-studio** [comment]
For me it's different. First of all, disabling Pi-hole doesn't do any difference. Second, servers are exact, so even though:
`cat /etc/pihole/whitelist.txt
s3.amazonaws.com
hosts-file.net
clck.yandex.ru`

Ping clck.yandex.ru gives me Pi-hole instead of IP.

**Comment by SwarfegaGit** [comment]
Ok, it looks like your correct.  I added the full FQDN and it's now working.  
I can't reproduce the issue so it looks to be an id10t error. 

Odd I swear using just the domain name worked ¯\_(ツ)_/¯

**Comment by sous-studio** [comment]
@SwarfegaGit Not for me, it's not:

```
Resolve-DnsName -Name clck.yandex.ru -Server PiHole.server

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
clck.yandex.ru                                 AAAA   2     Answer     ::
clck.yandex.ru                                 A      2     Answer     0.0.0.0

```

Perhaps you don't have it in black list? I see it like this:

```
grep clck.yandex.ru *
list.0.raw.githubusercontent.com.domains:# 0.0.0.0 clck.yandex.ru
list.2.sysctl.org.domains:127.0.0.1      clck.yandex.ru
list.6.hosts-file.net.domains:127.0.0.1 clck.yandex.ru
list.preEventHorizon:clck.yandex.ru
whitelist.txt:clck.yandex.ru
```

**Comment by sous-studio** [comment]
gravity.list is ok

```
cat gravity.list|grep clck
192.168.2.52 clck.ru
192.168.2.52 clck.webteaser.ru
192.168.2.52 clck.yandex.by
192.168.2.52 clck.yandex.com
192.168.2.52 clck.yandex.com.tr
192.168.2.52 clck.yandex.kz
192.168.2.52 clck.yandex.ua
192.168.2.52 clckcloud.com
192.168.2.52 clckme.com
192.168.2.52 imgclck.com
192.168.2.52 n.popclck.org
192.168.2.52 trckclck.com
192.168.2.52 www.clck.ru
192.168.2.52 www.imgclck.com
192.168.2.52 www.n.popclck.org
```

**Comment by sous-studio** [comment]
Sorry folks, my bad, it does work. It's just I had previous dnsseq installation with my own list, and it was blocked from there.

Thank you for your help!

**Comment by PromoFaux** [comment]
OK, I think everyone's issues are solved! Closing this thread out :)
