### ISSUE TITLE
 /etc/pihole/setupVars.conf is missing!!!!111 

### ISSUE THREAD

**Issue by afturner** [pi-hole/pi-hole#2082]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
10 (my source code, the pi-hole internal code would be a 4/10) 

---
**Expected behaviour:**
Okay so I did do a search, but the only issue that popped up that was the same was the _wonderful_ #1111 so clearly that didn't help much lol
I tried removing the .pihole dir and replacing it with a git clone and then -r to try again.

I'm using a stock modified Debian Docker image. Dependencies fail to install 

**Actual behaviour:**
Initial install script (using command from site, as well as manual git clone) fails with no warning, usually immediately with no new line: (so it must have errored out within some function call? 
`[i] Starting pihole-FTL service...root@fcd3b15220bb#:`

This is also always accompanied by the following, a few lines above:
`[✓] Creating user 'pihole`
`[i] Installing scripts from /etc/.pihole...install: invalid user ''
grep: /etc/pihole/setupVars.conf: No such file or directory`

**Steps to reproduce:**
Use stock bitnami/minideb:stretch 
And try to install. In order to get to a semi-successful state on the first try, run this too:
`RUN install_packages linux-image-4.9.0-6-amd64 pgp bash curl unzip dialog apt-utils iproute2 git net-tools php php-cgi php-sqlite3`
`RUN apt upgrade && apt update`

It fails to symlink itself anywhere, so that's the first clue something's wrong. Going to /etc/.pihole and status gives us:
`DNS service is running`
`grep: /etc/dnsmasq.d/01-pihole.conf: No such file or directory`
`   No hosts file linked to dnsmasq, adding it in enabled state`
`   Restarting DNS service...   Restarting DNS service`
`pihole-FTL: no process found`

When trying to -r, we're met with this error:
`./pihole: line 15: /opt/pihole/COL_TABLE: No such file or directory`
But it seems to work aside from that?

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not possible, as install fails before installing whatever this command needs to run. 

**End of day,** I would like to easily have a pihole installation completely autonomously installed on this debian distro. I don't really mind how to get there, but unfortunately it needs to be Docker and it needs to be a really slim image (was on Alpine before, but switched to this distro after seeing that pihole was only supported on it.) I also don't want to use docker-compose atm, but it's increasingly seeming like the only option, and just cloning an out of the box solution that's already out there. Whatever. Thanks for the help!

**Comment by afturner** [comment]
@PromoFaux I believe this should be reproducible.. did I miss something?

**Comment by dschaper** [comment]
Have you had a look at https://github.com/diginc/docker-pi-hole?

**Comment by afturner** [comment]
yes, and I'd love to use it, but there are a few complications with that because it's only a small part of the final image (a bunch of other steps run after this.) Since I cannot use docker-compose, that leaves me with multi-stage single Dockerfile builds or some sort of other more complicated container management, which is all much more work than I'd like to spend on something like this.

**Comment by dschaper** [comment]
That's pretty much the exent of the support you are going to get with regards to Dockerizing the Pi-hole. You've put some constraints that really limit what possible, and besides @diginc, there's really not much we're going to be able to assist you with.

**Comment by afturner** [comment]
The only real constraint is using a small and light Docker base image with no dependencies.

**Comment by afturner** [comment]
I'll take another look at @diginc though and see if I can just take parts of their Dockerfile

**Comment by afturner** [comment]
diginc/pi-hole:debian actually appears to be a good option. From their docs:
> This version of the docker aims to be as close to a standard pi-hole installation by using the recommended base OS and the exact configs and scripts (minimally modified to get them working). This enables fast updating when an update comes from pi-hole.
