### ISSUE TITLE
phrase matching, request  header and URL filtering, etc

### ISSUE THREAD

**Issue by versavius** [pi-hole/pi-hole#2088]
Just wondering if the Pi-Hole team have any plans to add phrase matching, request  header and URL filtering, etc.

Could make the pi hole even more powerful.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
