### ISSUE TITLE
Pi-Hole installation silently fails

### ISSUE THREAD

**Issue by CJeffyB** [pi-hole/pi-hole#2092]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pi-hole should install successfully.`

**Actual behaviour:**

`Pi-hole fails to install successfully, stopping after "[i] Checking for php5-sqlite (will be installed)"`

**Steps to reproduce:**

`(The board is a Pi 3B+, if that matters at all)`
`Fresh install of Raspbian Stretch Lite (2018-03-13-raspbian-stretch-lite) on 8GB Micro SD`
`apt-get update && apt-get upgrade`
`Install Pi-hole as per the installation instructions`
`Install silently fails`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`(No Debug Token, currently doing additional troubleshooting.)`

**Troubleshooting undertaken, and/or other relevant information:**

`Subsequently attempting a second install seems to fix the issue.`
`This is consistently reproducible.`
`Currently doing a reinstall on a fresh flash, after adding an additional deb repo, on a hunch based on an Adafruit TFT install script...`

**Comment by dschaper** [comment]
When it silently fails, do you get to the colored screen that has the horizontal process bar for installing packages or does it fail before then?

**Comment by dschaper** [comment]
I think we may be able to move to a trap that captures the failure and at least prints the reason before dropping you back to the prompt without any notice or explanation.

**Comment by dschaper** [comment]
Okay, so we know its failing in the dpkg process. I'll see what, if any, error messages it produces, and if there aren't any we can see if there's a way to trap that particular process and at least print a "Did Not Complete" message so that we know something went wrong. Maybe print out the packages that were attempted to install so that it's easier to troubleshoot and know what packages were failing the `apt install` process so we can suggest a manual `apt install` to see why the process failed.

**Comment by CJeffyB** [comment]
Here is a debug token, if it will help at all (the install completed on the second run, and appears to be running OK...)

th2xciqzt2

**Comment by CJeffyB** [comment]
Would it be helpful at all for me to run the original install like this instead:
`curl -sSL https://install.pi-hole.net | sudo bash -x`

I don't mind to do so, since I'm currently breaking the system anyway.
;-)

**Comment by CJeffyB** [comment]
More additional information...
On a fresh updated install, running the command:
`curl -sSL https://install.pi-hole.net | sudo bash -x`
causes the install to work perfectly fine.

Perhaps something is happening that is interfering with the normal sudo part?  Or something...
No clue at this point.

Let me know if there is any additional troubleshooting that could help.

**Comment by pihomeserver** [comment]
Same issue when trying to install Pi-hole mixed with my hotspot solution ... Had to run the script twice
Hardware is a Raspberry Pi 3, OS is Raspbian Stretch Lite

Any log file somewhere to help ?

**Comment by Mcat12** [comment]
It is probably an issue with installing one of the dependencies. If it happens again, try manually installing the dependency (it may require user input, or it might have run into an error during installation).

**Comment by CJeffyB** [comment]
@Mcat12 Without knowing which dependency it is, how could one manually install it?  Since there are no error messages generated, not any indication what is failing, it is difficult to resolve.

Running the installation script a second time, or running it with the command: `curl -sSL https://install.pi-hole.net | sudo bash -x` both complete the installation, but neither seems to be an optimal solution.

**Comment by Mcat12** [comment]
That `bash -x` command you posted will do exactly that.

**Comment by Mcat12** [comment]
You said that the horizontal bar screen flashes up. The installer prints out the packages it will install right before that.

**Comment by Elijahg** [comment]
I'm having the same problem, running DietPi, after installing PHP 7. It fails after this:

`+ debconf-apt-progress -- apt-get --yes --no-install-recommends install dnsmasq php5-common php5-cgi php5-sqlite`

And performing:

`elijah@Pi:/etc/pihole $ sudo apt install php5-common php5-cgi php5-sqlite`

Results in...

`Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php5-common
E: Package 'php5-cgi' has no installation candidate
E: Unable to locate package php5-sqlite
`

Is PHP 5 specifically required or will PHP7 be ok? If so, how do I force the installer to use that?

**Comment by williamwalker88** [comment]
Also experiencing the same problem as @CJeffyB - was able to diagnose the installation of [resolvconf](https://packages.debian.org/jessie/resolvconf) as the issue.  That package has been replaced by [openresolv](https://packages.debian.org/jessie-backports/openresolv).  Changing resolvconf to openresolv on line 199 of the default install script worked for me

**Comment by aymenjegham** [comment]
![image](https://user-images.githubusercontent.com/12992811/71193226-0d2b6380-228a-11ea-995b-f12b5f55dcc0.png)
It seems like a problem with the unpacking of the dependency...i am tracking them one by one and manually installing every dependency

**Comment by cr44sh** [comment]
Manual installation of the 'will be installed' modules helped me to track down the source of failure. In my case the problem is with installing lighttpd. It seems that it doesn't like my apache2 installation..

**Comment by TheWojtek** [comment]
In my case it looks like this:
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sqlite3 : Depends: libsqlite3-0 (= 3.22.0-1) but 3.22.0-1ubuntu0.2 is to be installed
E: Unable to correct problems, you have held broken packages.

And then:

wojtek@services:~$ sudo apt-get install sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 sqlite3 : Depends: libsqlite3-0 (= 3.22.0-1) but 3.22.0-1ubuntu0.2 is to be installed
E: Unable to correct problems, you have held broken packages.

So I tried to check:

wojtek@services:~$ sudo apt-cache policy sqlite3 libsqlite3-0
sqlite3:
  Installed: (none)
  Candidate: 3.22.0-1
  Version table:
     3.22.0-1 500
        500 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 Packages
libsqlite3-0:
  Installed: 3.22.0-1ubuntu0.2
  Candidate: 3.22.0-1ubuntu0.2
  Version table:
 *** 3.22.0-1ubuntu0.2 100
        100 /var/lib/dpkg/status
     3.22.0-1 500
        500 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 Packages
wojtek@services:~$ curl -sSL https://install.pi-hole.net | bash

And I am out of ideas now.

**Comment by jeroenbeuz** [comment]
I know this issue is closed but I still have this problem when installing PiHole on a fresh installed Pi 3 with OSMC. It seems to fail on installing sqlite3. I just manually installed sqlite 3 and then reinstalled PiHole with success.

`sudo apt install php7.0-sqlite3`

**Comment by Cellane** [comment]
The exact same situation happened to me: freshly installed OSMC (with Plex add-on, but that’s about it) on Pi 3, Pi-Hole installer silently fails. For me, `sudo apt install php-sqlite3` (and re-running the installer) solved the situation, I suppose that’s an equivalent of the command suggested by @jeroenbeuz above.
