### ISSUE TITLE
Opening recent requests for a client hangs web interface and blocks all UI interaction

### ISSUE THREAD

**Issue by Marcoevich** [pi-hole/pi-hole#2093]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate

**How familiar are you with the the source code relevant to this issue?:**

1, not familiar

---
**Expected behaviour:**

I expect a fast loading interface, which shows only the 10 last queries. Especially since there is a dropdown box which is set to show only 10 queries. It looks to me that, behind the scenes, the web admin is loading all 33000 requests of this client. This is uncessesary and render-blocking. Why does it work like this?

**Actual behaviour:**

This client has 33000 requests. The <ip-of-pi-hole>/admin/queries.php?client=<ip-of-client> keeps loading forever. All UI interaction is blocked. Can't click anything. Refreshing the page doesn't help. It's been in this state for the past 15 minutes and counting. Only solutiont to me seems to power cycle the Pi.

**Steps to reproduce:**

1. Log in to admin area of pi-hole 3.3
2. From the dashboard, click the top client. Mine is a Synology DiskStation with 33000 reported requests.
3. Load <ip-of-pi-hole>/admin/queries.php?client=<ip-of-client>

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Can't upload this because SSH is not responding, even after reboot. Will investigate.

**Troubleshooting undertaken, and/or other relevant information:**

What have I done to fix this?

- Tried to click anything in the web interface, refresh the page, etc. Doesn't respond to anything.
- Rebooted the Pi fixed this and the interface became responding again.

Suggested solution:

I expect a fast loading interface, which shows only the 10 last queries. Especially since there is a dropdown box which is set to show only 10 queries. It looks to me that, behind the scenes, the web admin is loading all 33000 requests of this client. This is uncessesary and render-blocking. Why does it work like this?

![image](https://user-images.githubusercontent.com/1243033/38466954-7d94b1ae-3b31-11e8-8b4a-efa7cbc90f4a.png)

**Comment by mkalkbrenner** [comment]
Same here. This function is broken since I updated from 3.2.1 to 3.3.1.

**Comment by keithah** [comment]
Same here too.

**Comment by dschaper** [comment]
Any new information or updates?

**Comment by mkalkbrenner** [comment]
It now works again here. It seems that for whatever reason, the functionality came back after some days/weeks.

**Comment by Marcoevich** [comment]
The web interface was updated in pihole 4.0. Does this mean that a solution for this issue can now be implemented?

**Comment by Mcat12** [comment]
This issue is marked as planned for the new web interface, so it will not be solved until that web interface is released.

**Comment by dschaper** [comment]
Closing as this is being developed for the next iteration of the web interface.

**Comment by Marcoevich** [comment]
@dschaper? When can we expect this next iteration? Can I follow development progress somewhere?

**Comment by PromoFaux** [comment]
No ETAs I'm afraid! But... this is the repo for the NG web https://github.com/pi-hole/web

**Comment by Marcoevich** [comment]
Thx PromoFaux! :)
