### ISSUE TITLE
Feature Request - Implement DNS-over-TLS capability in Pi-hole

### ISSUE THREAD

**Issue by teusink** [pi-hole/pi-hole#2096]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 1

Search Disclaimer :): I searched for `dns` and `tls` in open and closed issues, but did not see anything similar.

---
**Expected behaviour:**

Although there is an experimental implementation of DNS-over-TLS through the use of Stubby, official support coming to Pi-hole would greatly enhance the privacy aspects of the Pi-hole. DNS-over-TLS is in essence an encrypted tunnel through which the DNS-requests are send. Man-in-the-Middle (MitM) attacks on this traffic would result in captured encrypted data.

DNS-over-TLS (port 853) is not to be confused with DNS-over-HTTPS (port 443) and DNSCrypt (port 53). DNS-over-HTTPS is something that is supported by Google DNS, but just as DNSCrypt (supported by OpenDNS), it ain't a formal standard (RFC). DNS-over-TLS is an official standard and it is supported by Quad9 (9.9.9.9) and Cloudflare DNS (1.1.1.1).

Out-of-the-box support for DNS-over-TLS is therefore my feature request :).

**Actual behaviour:**

All DNS lookups to DNS-servers higher up in the chain are all not encrypted. Hence this invades privacy, because anyone can sniff out to which site you are going. Not the url, but in many cases the domain-name itself surrenders enough data to build a profile.

**Steps to reproduce:**

N/A

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I have read the following guides, but as there is no formal support yet I do not want to adjust my daily-Pi-hole-driver yet.

- https://blog.sandchaschte.ch/en/pi-hole-with-dns-over-tls
- https://www.reddit.com/r/pihole/comments/7oyh9m/guide_how_to_use_pihole_with_stubby/

But see also these pages from DNS-resolvers.

- https://developers.cloudflare.com/1.1.1.1/dns-over-tls/
- https://www.quad9.net/faq/#Does_Quad9_support_DNS_over_TLS

DNS-over-TLS RFC7858

- https://tools.ietf.org/html/rfc7858

**Comment by teusink** [comment]
This line made me think if was to be done at this place :) `We welcome everyone to contribute to issue reports, suggest new features, and create pull requests.`. But scrolling bit more down I see a clear link to the link you provided.

My bad!

I will check the other place out and see if my submission is needed there, or that someone was there before me.

Thanks!

**Comment by dschaper** [comment]
We probably could redo the template to be a bit clearer in that aspect. Thanks for your understanding.

**Comment by teusink** [comment]
Created an account, and placed it here now: https://discourse.pi-hole.net/t/implement-dns-over-tls-capability-in-pi-hole/8722

@dschaper Thanks for your quick response. 👍
