### ISSUE TITLE
Disabling block lists hosted at the same server

### ISSUE THREAD

**Issue by erazortt** [pi-hole/pi-hole#2097]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Having the following 2 block lists available:
https://v.firebog.net/hosts/Airelle-trc.txt
https://v.firebog.net/hosts/Easyprivacy.txt

Disabling the either the 1st or the 2nd will result in having either 1st or the 2nd list disabled. 

**Actual behaviour:**

Disabling the either 1st or the 2nd will always result in having 2nd list disabled. 

**Steps to reproduce:**

1. Add two lists which are hosted at the same server, like those two in this order:
https://v.firebog.net/hosts/Airelle-trc.txt
https://v.firebog.net/hosts/Easyprivacy.txt

2. Disable alternatively one of those, and it will always be the 2nd which is disabled.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

pb14uc0z0t

**Troubleshooting undertaken, and/or other relevant information:**

Having another (enabled) list in between the two lists leads to the expected behaviour.

**Comment by technicalpyro** [comment]
this is an issue with the webGUI i believe.  What happens if you use nano or vi to edit the adlists.list file?

**Comment by erazortt** [comment]
The adlists.list file behaves as expected, namely exactly like the webGUI. In the webGUI everything looks fine, the problem is what happens on the filesystem. Only there it can be seen that the wrong files are checked out.

**Comment by Mcat12** [comment]
I can't reproduce this (on an older version of the FTLDNS branch).
