### ISSUE TITLE
No queries shown, ad blocking seems to work

### ISSUE THREAD

**Issue by alexlab963** [pi-hole/pi-hole#2098]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Receive logs from device activity 

**Actual behaviour:**

No logs are shown

**Steps to reproduce:**

Go to the admin page

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

xu1vfxa34x

**Troubleshooting undertaken, and/or other relevant information:**

Honestly, I have no idea why this is happening, considering everything is updated and pi-hole works just fine other than that, I didnt perform any troubleshooting yet.

**Comment by Romijn** [comment]
I'm having the same issue, running pi-hole on a synology on debian as described here https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289

If you need a debug log let me know, cheers!

**Comment by andyforceno** [comment]
Is dnsmasq running? If not, this could this be related to the dnsmasq issue. From https://pi-hole.net/2018/02/14/pi-hole-v3-3-released-its-extra-special/, Update 2018-02-18 06:12: 

> If you’re running Raspbian Jessie and you updated Pi-hole to v3.3, you likely ran into issues.  This is because the version of dnsmasq that ships with it does not support the log-queries=extra option, which we use in v3.3.

>You have two options to resolve this: revert Pi-hole to a previous version or upgrade dnsmasq manually.

In my case, dnsmasq would not start. I had to comment out the line `log-queries=extra` in `/etc/dnsmasq.d/01-pihole.conf` to get dnsmasq 2.72 to start. Now, dnsmasq is running and pihole is blocking ads, but the query log is empty and the pihole UI shows no stats other than domains blocked. I've been personally unable to manually upgrade dnsmasq to the recommended version, v2.76, without breaking it.

**Comment by Mcat12** [comment]
@alexlab963 did @andyforceno's comment help? If not, make a new debug token.

**Comment by julgonmej** [comment]
I have the same issue since the last Pi-Hole update this week:
"Pi-hole Version v3.3.1 Web Interface Version v3.3 FTL Version v3.0"

Dnsmasq is running, everything is working fine but the Pi-Hole admin panel doesn't show any graphs (only loading icon), opening any log from admin panel shows `"An error occured while loading the data: Connection refused. Is FTL running?"`

**Comment by andyforceno** [comment]
Sounds like the pihole-FTL service is not running. Try `sudo service
pihole-FTL start`

**Comment by julgonmej** [comment]
pihole-FTL service is shown as "active(exited)"

**Comment by julgonmej** [comment]
I didn't noticed anything different on the logs, I uninstalled removing everything and now it works again.

**Comment by Mcat12** [comment]
@alexlab963 Do you still have this issue?

**Comment by bobybobybob** [comment]
I have the Problem too...  only uninstall and install again help only 19 hours then problem again.

**Comment by aimdev** [comment]
While trying to debug this issue (retrieving log other than the current day), I modified the js file
 /var/www/html/admin/scripts/pi-hole/js/db_queries.js to present the error variable, and got this
Internal Server Error
This error message is a bit generic, I assume its from sqllite?
Question, the current db file for approx two days traffic for a home system is 145Mb, does sqllite scale well, or would postgresql be a better choice

**Comment by ourlord** [comment]
Same issue here. Log token `6ktp4q73p5`.
I explicitly did a dig command to do a DNS lookup to my pi-hole server and the DNS query show up in the dnsmasq log file. However no update from the web. While I remember people suggested to clear browser cache which I did. Did not help in this case.

**Comment by Mcat12** [comment]
Everyone who is having the issue, please make a new debug token and list any specific issues that you are having which are not in the original post.

**Comment by ourlord** [comment]
I resolve the issue..it's due to the dnsmasq version not compatible with pi-hole 3.3.
Do `sudo find / -name dnsmasq` and see how many dnsmasq binary has installed in the system.
For my case I actually have two, one in `/usr/sbin/dnsmasq` (v2.68) installed probably by apt-get or pi-hole script; one I installed manually in `/usr/local/sbin/dnsmasq` (v2.76). 
Apparently v2.68 dnsmasq does not support `log-queries=extra` syntax in the pi-hole config file. And seems by default pi-hole will use the v2.68 one which locates in `/usr/sbin/dnsmasq`.
So I did a trick by make a symbolic link to the v2.76 dnsmasq and put it under `/usr/sbin`:
`sudo mv /usr/sbin/dnsmasq /usr/sbin/dnsmasq.bkp`
`sudo ln -s /usr/local/sbin/dnsmasq /usr/sbin/dnsmasq`
Then restart the dnsmasq service `sudo service dnsmasq restart`. It should not complain about that line `log-queries=extra` in the config due to it supposes to use the v2.76 one.
After that I did a dig and the query shows up in the web interface.

**Comment by aimdev** [comment]
Hi

I have only one dnsmasq, 
/usr/sbin/dnsmasq  -v
Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify

Weirdly, I got a result from querying yesterdays records, but not last weeks.

Got my expanded message
002 An unknown error occured while loading the data.
> Internal Server Error

System Debian Stretch

**Comment by Mcat12** [comment]
@aimdev Make a debug token

**Comment by aimdev** [comment]
Re Please Make a debug Token

ex6ijav9ye

**Comment by Mcat12** [comment]
The error loading the long term data is because PHP couldn't handle loading that much data (depends on how fast your device is).
Have you tried changing the upstream DNS to something else besides your router's IP?

**Comment by TSM-EVO** [comment]
@Mcat12 

Am having the same experience. I am running pihole alongside Home Assistant on a RPI on Hassbian, which means I had to downgrade to 3.2.1.

my debug token is
bqjdypp4zy

One thing I should mention is 
`sudo nano /etc/dnsmasq.d/01-pihole.conf`

contains 
`log-queries
log-facility=/var/log/pihole.log
`

**Comment by danifr** [comment]
I fixed it by reinstalling ```pi-hole dnsmasq pi-hole-ftl lighttpd php-cgi``` and reconfiguring everything again.

I seems I was missing ```php-sqlite``` package before (used by lighttpd)
Hope this helps.

**Comment by Mcat12** [comment]
If people have new issues, please open a new GitHub issue.

**Comment by znarf89** [comment]
Make shure you have 
`php7.4-cgi php7.4-sqlite3 php7.4-xml` 
installed. These packages are missing, when you are installing pihole without lighttpd.
