### ISSUE TITLE
Teleporter - The file you are trying to upload is not a .tar.gz file

### ISSUE THREAD

**Issue by orangepasties** [pi-hole/pi-hole#2099]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:

`1`

---
**Expected behaviour:**

`{Teleporter to import file that was exported from prior server.}`

**Actual behaviour:**

`{Fails with error message: The file you are trying to upload is not a .tar.gz file (filename: pi-hole-teleporter_2018-04-09_09-05-59.tar, type: application/x-tar). Please try again.}`

**Steps to reproduce:**

`{Export from prior installation and then attempt to import using Teleporter gun.}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{I haven't done any steps to fix this as I believe the issue lies in the code and I'll not pretend I'm qualified to help. The issue appears to be that the teleporter exports a .tar file and the importer is looking for a tar.gz file. If you recreate the contents of the tar file as a tar.gz and test the import it works correctly. I exported and imported from the same version Pi-hole Version v3.3.1 Web Interface Version v3.3 FTL Version v3.0. I'm using a Mac OS X 10.12.6 on Safari and I tested on Chrome. Additionally the success message that appears "Processing wildcardblocking.txt
OK" after the import doesn't say anything about whitelist or black list exact. Neither of these lists gets imported.}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
@Mcat12 Should this line https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/teleporter.php#L168 be saving the tarname or the filename?

**Comment by Mcat12** [comment]
No, the important line is here, where it sets the filename that the user will be shown:
https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/teleporter.php#L189

That line that you linked is when the `.tar` file is getting compressed into a `.tar.gz` file, so the uncompressed filename should end in `.tar`

It is possible that a previous version was doing this incorrectly, but it is no longer a bug.

**Comment by L3rchal** [comment]
Version 4.0 still having this issue previous backup game me .tar file (also version 4.0) however I can't import file not due error `The file you are trying to upload is not a .tar.gz file`

Fixed by extracting data and compressing them using `tar`.

Using `file` command on backup file game me `pi-hole-teleporter_2018-11-15_01-08-14.tar: POSIX tar archive`
