### ISSUE TITLE
Reboot causes version to revert

### ISSUE THREAD

**Issue by TechnicallyFox** [pi-hole/pi-hole#2106]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
After upgrading to latest versions then rebooting, expect the version to remain the newest.

**Actual behaviour:**
After updating to latest version (verified v3.3.1 in web and cli) and rebooting, updates are reverted to older version and settings made via web interface are lost.  (DNSSEC enable and DHCP server)

Versions on after reboot:
pi@Pi-Hole:~ $ pihole -v
  Pi-hole version is v3.1.4 (Latest: v3.3.1)
  AdminLTE version is v3.1 (Latest: v3.3)
  FTL version is v2.11.1 (Latest: v3.0)

Then when running pihole -up it states updates are available and applies update.

**Steps to reproduce:**
Update from 3.1.4 to current
Reboot with 'sudo reboot'

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Debug token at reverted version 3.1.4
pq0rt4cjgz

Debug token after upgrade 3.3.1 before reboot
01uw3u7hge

After reboot version reverted back to 3.1.4
4i9mkvivq8 

**Troubleshooting undertaken, and/or other relevant information:**
Pi 2 Model B
Linux Pi-Hole 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
"Raspbian GNU/Linux 8 (jessie)"

Have attempted to install updates via 'pihole -up'  and 'curl -sSL https://install.pi-hole.net | bash'
The system completes the updates and all appear to be working until reboot
Have attempted to run 'sync' twice before rebooting, version still reverts

Tried  'cd /etc/.pihole && sudo git fetch --tags' as per https://discourse.pi-hole.net/t/updated-to-v3-3-web-ui-thinks-core-still-at-v3-2-1/7163 thinking maybe it was related but version still reverts on reboot.

After digging more this may be related to https://github.com/pi-hole/pi-hole/issues/1998 but would the version revert in that case?

Any other suggestions before I reinstall OS and start fresh?

**Comment by TechnicallyFox** [comment]
Completed the steps and verified the dnsmasq version per #1998 and ran update again
New debug log after upgrades 0ybebfy6sv

Pi-hole version still reverted after reboot
pi@Pi-Hole:~ $ pihole -v
  Pi-hole version is v3.1.4 (Latest: v3.3.1)
  AdminLTE version is v3.1 (Latest: v3.3)
  FTL version is v2.11.1 (Latest: v3.0)

dnsmasq version remained upgraded-
pi@Pi-Hole:~ $ dnsmasq -v
Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify

**Comment by dschaper** [comment]
Can you run a check on the SDCard? It sounds like it may have gone into read-only mode. Try saving any kind of file in your home directory, reboot and check if the file is still there?

**Comment by TechnicallyFox** [comment]
Good catch... Your suspicion is right that the SD card is acting as read-only and that files I create in home are not saving after reboot.  Will have to pickup a new SD.

**Comment by dschaper** [comment]
Thanks for the update, luckily some cards fail by going to read-only so that you can get your data and not just fail completely and lose everything stored on the card. I'll close this out as it looks to be an outside issue.
