### ISSUE TITLE
Top domains list not showing in web interface or API

### ISSUE THREAD

**Issue by brunovms** [pi-hole/pi-hole#2111]
**In raising this issue, I confirm the following:
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4

---
**Expected behaviour:**

Top Blocked and Top Forwarded domains should be available.

**Actual behaviour:**

Top Forwarded domains does not show up in the web interface, and Top Blocked domains keeps loading forever.
**Steps to reproduce:**

Just open the admin page of pi-hole and all the graphs are ok, and the blocking and other functions seems to be working fine, but the tables of top domains don't show up.
Also, can't access them directly on the API.
I have already tried some solutions on discourse and everything in this issue: https://github.com/pi-hole/pi-hole/issues/2002 but nothing have worked so far.

**Debug token:
mjwshaeeso

![capturar](https://user-images.githubusercontent.com/35403031/38752824-df579870-3f32-11e8-91b3-a896d853cc4e.PNG)

**Comment by Inuun** [comment]
Can confirm. I'm not sure but it might have started when I added domains to exclude. Removing domains or re-adding does not change anything.

Debug token: s6bn7hujra

**Comment by brunovms** [comment]
Now that @Inuun mentioned, it started after I added some domains to the exclude list in API/Web Interface settings. Removing or re-adding did not solve the problem for me too.

I'm using FTLDNS, changing back to master branch did not solve, and also repairing with <code>pihole -r</code> in both master and ftldns branchs does nothing. Renaming de pihole-FTL.db file and forcing pihole to create a new one, also don't work.

**Comment by brunovms** [comment]
Just found the solution.
For some reason, the line <code>API_QUERY_LOG_SHOW</code> in <code>/etc/pihole/setupVars.conf</code> was set to nothing <code>API_QUERY_LOG_SHOW=nothing</code>. 

I did not change any configurations that could relate to that, but changing the parameter to <code>API_QUERY_LOG_SHOW=all</code> solved the problem.
