### ISSUE TITLE
[ERROR]: Unable to parse results from queryads.php with https and own domain

### ISSUE THREAD

**Issue by HepplerDotNet** [pi-hole/pi-hole#2113]
Hi,
I configured pi-hole web interface to run on my own domain name and https.
Now if entering https://pi.mydomain.com I get:
[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()
Entering https://pi.mydomain.com/admin/ works!

I tried to "fix" queryads.php:

+$queryAds = file($proto."://".$serverName."/admin/scripts/pi-hole/php/queryads.php?domain=$serverName&bp", FILE_IGNORE_NEW_LINES);
-$queryAds = file("http://127.0.0.1/admin/scripts/pi-hole/php/queryads.php?domain=$serverName&bp", FILE_IGNORE_NEW_LINES);

But still get this error. Any idea?

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)
