### ISSUE TITLE
Adding exclusions to API disables Top Items in API and Dashboard

### ISSUE THREAD

**Issue by brunovms** [pi-hole/pi-hole#2114]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4

---
**Expected behaviour:**

When I add domains to the exclusion lists in the API/Web Interface settings, the domains are not shown anymore in the lists.

**Actual behaviour:**

When the domains are added to the exclusion lists, the option <code>API_QUERY_LOG_SHOW</code> is changed from <code>all</code> to <code>nothing</code>, disabling the Top Blocked Domains and Top Permitted Domains in the Dashboard.

**Steps to reproduce:**

Just add any domain to the exclusion lists in the API/Web Interface settings tab.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

mjwshaeeso

PS.: I'm using the FTLDNS branch.

**Comment by DL6ER** [comment]
Do we need the `API_QUERY_LOG_SHOW` option at all with the new concept of privacy levels? I don't think so.

**Comment by Mcat12** [comment]
I can't reproduce this so far

**Comment by brunovms** [comment]
@Mcat12 I updated pi-hole, and now the problem doesn't happen anymore.
