### ISSUE TITLE
Client name disappear after a day

### ISSUE THREAD

**Issue by flopp999** [pi-hole/pi-hole#2120]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`showing client name`

**Actual behaviour:**

`showing "gateway"`

**Steps to reproduce:**

`let pi-hole run for a day`

**Troubleshooting undertaken, and/or other relevant information:**

`restart pi-hole`
`My TV is accessing Netflix but in pi-hole Query Log is says "gateway" yesterday is said my tv name`
`using latest version for all components`

**Comment by technicalpyro** [comment]
please provide a debug token the nbext time this occurs by running `pihole -d` also what is doing your DHCP the pihole or your router.  lastly are you defining the devices in your network using the hosts file r some other way

**Comment by flopp999** [comment]
I'm using my router for DHCP, pi-hole only act as DNS

**Comment by technicalpyro** [comment]
how does yourpihole know what hostname to use for each IP do you have it set n /etc/hosts ?

**Comment by flopp999** [comment]
It must have taken the names from my router, because I have not edit hosts.
I will try to restart or reinstall pi-hole and then take a photo where it shows device name

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-do-i-only-see-my-routers-ip-address-instead-of-individual-devices-in-the-top-clients-section-and-query-log/3653

**Comment by flopp999** [comment]
@Mcat12 thanks, but I do see all devices IP right now, but at day one I saw devices name and suddenly it only start showing IP address instead

**Comment by Mcat12** [comment]
So you see more than just your router's name/ip?
https://discourse.pi-hole.net/t/how-do-i-show-hostnames-instead-of-ip-addresses-in-the-dashboard/3530

**Comment by Mcat12** [comment]
@flopp999 Have you fixed the issue?

**Comment by dschaper** [comment]
Closing for age.
