### ISSUE TITLE
sentry.io added to default blocklist: list.0.raw.githubusercontent.com.domains

### ISSUE THREAD

**Issue by sadsfae** [pi-hole/pi-hole#2122]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behaviour:**

I should be able to access sentry.io with a default installation, it shouldn't be on the blocklist.

**Actual behaviour:**

Sentry.io is blocked in the default blocklist: list.0.raw.githubusercontent.com.domains.  It doesn't fit the profile or usage that pi-hole would want to block, it's free, open source error-tracking software.

`{A detailed description and/or screenshots of what you do see}`

With a fresh 3.3.1 installation sentry.io is blocked

```
dig @172.17.0.2 sentry.io

;; ANSWER SECTION:
sentry.io.		2	IN	A	0.0.0.0
```

pihole finds it in the default blocklist:

```
root@fd9e5397786f:/# pihole -q sentry.io
 Match found in list.0.raw.githubusercontent.com.domains:
   sentry.io
```

**Steps to reproduce:**

Deploy a new pi-hole docker container or install via traditional method

```
docker run -d --name pihole --restart=always diginc/pi-hole:debian
```

Set your ```/etc/resolv.conf``` to use the new container or dig against it

```
dig @172.17.0.2 sentry.io
```

Query the pihole -q for the same result and origin

```
docker exec -ti pihole bash
root@fd9e5397786f:/# pihole -q sentry.io
grep: whitelist.txt: No such file or directory
grep: blacklist.txt: No such file or directory
 Match found in list.0.raw.githubusercontent.com.domains:
   sentry.io
```

**Comment by PromoFaux** [comment]
As I mentioned in the other issue, this is beyond our control and needs to be taken up with the list originator. @dcramer has already opened an issue there:

https://github.com/StevenBlack/hosts/issues/568

**Comment by sadsfae** [comment]
Ok thank you, will take it up there then.
