### ISSUE TITLE
Doc Issue, 

### ISSUE THREAD

**Issue by Error-418** [pi-hole/pi-hole#2125]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
This is not source code relevant, it is Documentation relevant.
`1`

---
**Expected behaviour:**

`I follow the directions and have a functioning DNS Server.`

**Actual behaviour:**

`I follow the directions and am locked out of having a DNS Server.`

**Steps to reproduce:**

`Follow directions as written for DNSCrypt 2.0 setup Step 2. Modify Pi-Hole:
>These instructions are the same, but will copy them here.
> 
> sudo nano /etc/dnsmasq.d/02-dnscrypt.conf: Create new or edit existing conf.
> Change server=<IP>#<port> where dnscrypt-proxy is running. For example, my .toml file is listen_addresses = ['127.0.0.1:54', '[::1]:54'], so edit the conf file to be server=127.0.0.1#54
> sudo nano /etc/pihole/setupVars.conf: Edit setupVars.conf.
> Comment out #PIHOLE_DNS#= lines.
> sudo nano /etc/dnsmasq.d/01-pihole.conf
> Comment out #server=... lines
> sudo service dnsmasq restart: restart dnsmasq

Commenting out #PIHOLE_DNS#= and #server= cuts Pi-Hole off from accessing an Authoritative DNS server. In turn this breaks DNS lookups. I think what was intended, was to turn off IP addresses to DNS servers outside of the PiHole group? Not sure. I do know that leaving one line uncommented in each file with the trusted DNS server I was looking for (1.0.0.1) allowed me to start resolving cloudflare issues correctly.

It's worth noting this may be restricted to Pi-Hole users on AT&T: https://blog.cloudflare.com/fixing-reachability-to-1-1-1-1-globally/
`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`g4lt0zvcgt`

**Troubleshooting undertaken, and/or other relevant information:**

`Uncommented the IP address of the cloudflare server I was attempting to reach in the listed instructions.`

**Comment by dschaper** [comment]
The Wiki documents are written by community members and are not monitored or maintained by the Pi-hole team. There is another DNSCrypt wiki that covers 2.0 that you may want to read through, but that's the extent of the support that we can provide for those pages. I'll mark this as an outside problem and leave it open for a few days for community members to respond to, but after that it will most likely be closed.

**Comment by Error-418** [comment]
It was the DNS Crypto 2.0 doc I was following. 

I'll update it with a note specific to AT&T users since I'm not sure if I'm a standalone on that or off it's an error in the doc for all setups regardless of ISP.

**Comment by dschaper** [comment]
Thanks, it's from help from users like you that keep the pages updated and relevant. We appreciate it!
