### ISSUE TITLE
HTTP error 500 in admin panel

### ISSUE THREAD

**Issue by heskja** [pi-hole/pi-hole#2127]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Expecting to see the recent queries when browsing to http://pi.hole/admin/queries.php?client=x.x.x.x. The client I am trying to view a client with more than 360.000 queries. /var/log/lighttpd/error.log reports memory exhaustion. 

**Actual behaviour:**

HTTP error 500 reported by browser.

**Steps to reproduce:**

1. Login to admin console
2. Click on the client IP in the "Top clients" widget
3. Wait

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

b7k1sefjta

**Troubleshooting undertaken, and/or other relevant information:**

Pi-hole running on a virtual machine with 1 vCPU and 1 GB RAM running Ununtu 16.04

Suggestion on how to solve / avoid the issue: Add a query parameter to filter the number of results to show, then use pagination to fetch the relevant queries.

**Comment by DL6ER** [comment]
> Add a query parameter to filter the number of results to show, then use pagination to fetch the relevant queries.

This is WIP if I'm not mistaken, pinging @Mcat12

**Comment by Mcat12** [comment]
Right now pagination is targeted to come with the new web interface.

**Comment by dschaper** [comment]
Closing as this is being developed for the next iteration of the web interface.
