### ISSUE TITLE
Chronometer2 Not Correctly Showing Memory Usage

### ISSUE THREAD

**Issue by Twiggy-GH** [pi-hole/pi-hole#2137]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Chronometer2 memory section to report same memory usage as from the Pi-Hole Admin UI

**Actual behaviour:**

Memory value is negative and doesn't accurately show usage.

[Chronometer2](https://imgur.com/a/o0mQ1Na)
[PiHole Admin UI](https://dl.dropboxusercontent.com/s/zbb3ynpi7yos4p9/mstsc_2018-04-20_11-15-24.png)

**Steps to reproduce:**

Unknown, installed PiHole and then setup Chronometer2.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

69rwdyng1t

**Troubleshooting undertaken, and/or other relevant information:**

Rebooted Pi. Made sure PiHole and Raspbian were up to date.

**Comment by dschaper** [comment]
@WaLLy3K Not sure if assignments trigger notifications or emails. Can you take a look at this?

**Comment by WaLLy3K** [comment]
Issue has been corrected, [as per this post](https://github.com/jpmck/chronometer2/issues/9#issuecomment-388640539).
