### ISSUE TITLE
CR: Web server for some items

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [pi-hole/pi-hole#2138]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I would love to have websites loaded as fast as with ads, or even faster.

**Actual behaviour:**

Some websites take forever to load (1:00 min or longer) since I'm using Pi-Hole. Of course that's the website's fault, not Pi-Hole's, because they rely on some ad stuff that's not available. So this is not a bug report, it's a feature request.

**Steps to reproduce:**

Browse to https://heise.de/ with Pi-Hole active.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not applicable

**Troubleshooting undertaken, and/or other relevant information:**

Not applicable

**Suggestion:**

I can't judge exactly about the technical correctness.

To me it seems that the site is trying to download some stuff and it even does that repeatedly. Instead of blocking the request on DNS basis completely, my idea is whether Pi-Hole could serve valid but empty files for whatever is requested.

Therefore: 
1. do not block the DNS but return Pi-Hole's IP.
2. Have a web server that serves
a) 1x1 pixel PNG file, no matter what the exact URL of the PNG file is
b) minimal JavaScript, doing nothing, no matter what the URL of the JS file is
c) 1x1 pixel JPG file
d) minimal CSS file
e) minimal HTML file
f) ... I think you get the idea

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-some-pages-load-slow-when-using-pi-hole-and-how-to-fix-it/6945

**Comment by dschaper** [comment]
Also, please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community. There may already be a Feature Request for this, so please search that site and add your votes!

**Comment by Mcat12** [comment]
Also, we already do this (return Pi-hole's IP instead and return an empty response)

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
I'm really sorry I posted this as an issue and not as a feature request.
The [contributor guideline](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md) mentions the word "feature" 9 times, but none of them points to the discourse feature-request site.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

:)
