### ISSUE TITLE
cron job "pihole flush once quiet" produces missing conf file error

### ISSUE THREAD

**Issue by fsantiago07044** [pi-hole/pi-hole#2139]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

for cron job to complete successfully and silently, or at least without error

**Actual behaviour:**

each run of this cron job:

00 00   * * *   root    PATH="$PATH:/usr/local/bin/" pihole flush once quiet

produces error message:

sed: can't read /etc/pihole/pihole-FTL.conf: No such file or directory

**Steps to reproduce:**

run said cron job without conf file present

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

nqd3o5l882

**Troubleshooting undertaken, and/or other relevant information:**

I could simply create the missing file but am unsure of its content or syntax. why is this file missing? I'm running on fedora 27, and recently uninstalled and reinstalled. i have never noticed this error before. Is it a problem? Thanks.

**Comment by fsantiago07044** [comment]
On April 20, 2018 8:24:18 PM EDT, Dan Schaper <notifications@github.com> wrote:
>@bcambl You recently did a fresh install on Fed 27, did you have to
>adjust anything when you installed?

No, not that I recall. It just worked. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by bcambl** [comment]
No adjustments made. That said, the file in question is missing on both my devices:

OPZ w/ Armbian:
```
root@orangepizero:~# stat /etc/pihole/pihole-FTL.conf
stat: cannot stat '/etc/pihole/pihole-FTL.conf': No such file or directory
root@orangepizero:~# pihole -v
  Pi-hole version is v3.2.1-148-g82d5afe (Latest: v3.3.1)
  AdminLTE version is v3.2.1-123-g89090261 (Latest: v3.3)
  FTL version is vDev-d1c163e (Latest: v3.0)
root@orangepizero:~# 
```
RPI3 w/ Fedora 27 Server:
```
[root@localhost ~]# stat /etc/pihole/pihole-FTL.conf
stat: cannot stat '/etc/pihole/pihole-FTL.conf': No such file or directory
[root@localhost ~]# pihole -v
  Pi-hole version is v3.3.1-74-g557372b (Latest: v3.3.1)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is vDev-02b987c (Latest: v3.0)
[root@localhost ~]# 
```

**Comment by technicalpyro** [comment]
iirc FTL.conf is not created unless the user creates an populatyes it @DL6ER ? can probably confimr better than i can

**Comment by bcambl** [comment]
This has already been fixed in the development branch with the following commit: https://github.com/pi-hole/pi-hole/commit/d8f85a898130453e4f4ee9f0924d33c3c450dfbc

**Comment by subfission** [comment]
Simple workaround until next release: 
```sh
┌──[root@pihole]─[~]
└──╼ # touch /etc/pihole/pihole-FTL.conf
```

**Comment by fsantiago07044** [comment]
On April 27, 2018 7:40:26 AM EDT, "Zach :(){ :|: & };:" <notifications@github.com> wrote:
>Simple workaround until next release: 
>```sh
>┌──[root@pihole]─[~]
>└──╼ # touch /etc/pihole/pihole-FTL.conf
>```

Done. Thanks.
--

Fabian A. Santiago

OpenPGP:

0x643082042dc83e6d94b86c405e3daa18a1c22d8f (current key)
 0x3c3fa072accb7ac5db0f723455502b0eeb9070fc (to be retired / revoked)
