### ISSUE TITLE
No DNS resolution after uninstalling Pi-Hole

### ISSUE THREAD

**Issue by ghost** [pi-hole/pi-hole#2148]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---
**Expected behaviour:**

When Pi-hole is uninstalled or `dnsmasq` is stopped, the host itself should still be able to resolve domain names, in a similar fashion to that prior to the installation of Pi-hole 

**Actual behaviour:**

The uninstal removes `dnsmasq`, but `dhcpcd.conf` is left unchanged, and still contains the line `static domain_name_servers=127.0.0.1` (as created by the installer when it [configures a static IP address](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L666)). 

This results in `resolvconf` still using this (after Pi-hole uninstall) when regenerating `/etc/resolv.conf`, ultimately resulting in loss of DNS resolution, until the user replaces this line with something else (or another application adds an additional entry to `resolvconf`'s database). The same behaviour can be seen if the `dnsmasq` service is stopped.

**Steps to reproduce:**

`pihole uninstall` or `systemctl stop dnsmasq`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

`dnsmasq` will update `resolvconf`'s database (see `/etc/resolvconf/update.d/dnsmasq` and `/lib/resolvconf/dnsmasq`), that adds the following entry to `resolvconf`'s database, for use when generating `/etc/resolv.conf`:

    # resolv.conf from lo.dnsmasq
    nameserver 127.0.0.1

When `dnsmasq` is stopped, the entry is removed and `resolvconf` will regenerate `/etc/resolv.conf`, populating it with other entries from the database (such as `domain_name_servers` from `dhcpcd.conf`). This can be observed by running the following commands:

    resolvconf -l
    cat /etc/resolv.conf

    systemctl stop dnsmasq

    resolvconf -l
    cat /etc/resolv.conf

    systemctl start dnsmasq

    resolvconf -l
    cat /etc/resolv.conf

When the installer edits `dhcpcd.conf` to set a static IP address, it could set the value of `domain_name_servers`, to that of the upstream server chosen by the user during installation. This *should* be sufficient in ensuring that DNS resolution can continue when Pi-hole is uninstalled or if the `dnsmasq` service is stopped (as `resolvconf` will use `lo.dnsmasq` if the service is running or `dhcpcd` if it is not - however this will require testing on other platforms)

Examples of this issue can be found [here](https://www.reddit.com/r/pihole/comments/8ee0nb/pihole_installation_breaks_network_configuration/) and [here](https://www.reddit.com/r/pihole/comments/8dtifs/pihole_killing_dnsmasq_service_on_install)

**Comment by dschaper** [comment]
Thanks for the detailed issue report, this does look like it's a bug, we should clean up everything. Probably will need to ask and confirm removal of the `/etc/dhcpcd.conf` lines, as people installing on Raspbian may already have lines there setting static and we wouldn't want to remove configurations that we didn't set.

**Comment by 10ZiN** [comment]
> It comes down to people installing on the Raspberry Pi Debian with Raspbian Desktop and running a browser on that same device while wanting blocking

I haven't used Debian desktop environments in a while, so I'm unsure how they interact with `resolvconf ` or whether they use their own implementation for defining DNS, but is this why DNS is set to `127.0.0.1` only on [Debian systems](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L674) by the installer?

If so then that does complicate matters... on a Debian server environment the answer is simple, set DNS to an external upstream, and let `dnsmasq` change this (via `resolvconf `) when the service starts/stops. If this differs in a Debian desktop environment, and DNS must be is set to `127.0.0.1`/`localhost` globally for Pi-hole to function correctly, then unavoidably system-wide lookup's will fail if ever the situation arises where nothing is listening on `127.0.0.1`/`localhost` (AFAIK there's no efficient way to handle this without adding an unnecessary complexity for a rare but slightly probable scenario).

The same can be said regarding `dhcpcd.conf` during uninstall, with various ways of configuring a static address, it's hard to check for every possible configuration (e.g. I use arping profiles, allowing `dhcpcd` to use different static addresses dynamically, depending on the network it's connected with).

Either way, perhaps this cannot be solved programmatically (beyond confirming removal with the user during uninstall), but I felt it was worth documenting considering the two Reddit threads recently

**Comment by dschaper** [comment]
I'm in agreement with just about everything, adding in the options of resolvconf.conf and the resolvconf daemon that manages `/etc/resolv.conf`. I appreciate the Issue and documenting the problems that users have run in to on Reddit. This will stay open for a while, while we discuss the corner cases and options to a resolution, it may just be that we change to handle the majority of installations and let corner cases lay where they fall.

**Comment by kyle95wm** [comment]
Someone was bitching about this on Reddit last night. I recommend that this is fixed in time for the next release.

**Comment by dschaper** [comment]
Yes, we saw the love note they left.

**Comment by lamp2** [comment]
@dschaper Is there any update on this issue? My Debian machine is in a completely broken DNS state after disabling `pihole-FTL` from starting automatically on boot (`update-rc.d pihole-FTL disable`). The default system dns server is still 127.0.0.1#53 but obviously there is no process listening to that port anymore. I have tried removing the `static domain_name_servers=127.0.0.1` line from `/etc/dhcpcd.conf` as suggested above and rebooting the machine, but problem stays. Debian cannot resolve any URL. 

The `/run/resolvconf` file doesn't even exist anymore.

~# ll /etc/resolve.conf
lrwxrwxrwx 1 root root   31 Oct 11 18:34 /etc/resolv.conf -> /etc/resolvconf/run/resolv.conf
~# cat /etc/resolv.conf 
cat: /etc/resolv.conf: No such file or directory

The `dhclient` gets the name servers from router but something is blocking it to update resolvconf. Appreciate if you or someone can show me how to at least work around this issue manually.

**Comment by vinc3m1** [comment]
After uninstalling on Ubuntu I also lost all DNS with lots of leftover configs broken. I had to do the following to get the network back up:
- in `/etc/dhcpcd.conf`remove all the lines appended by
  ```
  setDHCPCD() {
      # but we can append these lines to dhcpcd.conf to enable a static IP
      echo "interface ${PIHOLE_INTERFACE}
      static ip_address=${IPV4_ADDRESS}
      static routers=${IPv4gw}
      static domain_name_servers=127.0.0.1" | tee -a /etc/dhcpcd.conf >/dev/null
  }
  ```
- in `/etc/systemd/resolved.conf` I had to re-comment out `#DNSStubListener=yes`

I would be nice if the setup script actually kept track of the changes that it made (which it clearly isn't doing), so it can properly undo them.

**Comment by dschaper** [comment]
I'm working on doing some overhaul to the installer script and as part of that I'll take a look at logging actions to help with uninstall.

**Comment by guszernial** [comment]
I had this problem when uninstalling pihole from a Kubuntu 18.04.1 system, and was able to get DNS working again by commenting out static domain_name_servers=127.0.0.1 in /etc/dhcpcd.conf. Is there anything else I need to do to clean things up and avoid possible future problems?

**Comment by mwoolweaver** [comment]
This issue just happened to today and I had emptied /etc/dnsmasq.d/ and change the nameserver list in resolv.conf.

After that everything started working for me.

**Comment by travisboss** [comment]
> This issue just happened to today and I had emptied /etc/dnsmasq.d/ and change the nameserver list in resolv.conf.
> 
> After that everything started working for me.

This is what worked for me after a pi-hole uninstall.

**Comment by ntindle** [comment]
Still occurs

**Comment by ntindle** [comment]
@dschaper any progress on this?

**Comment by dschaper** [comment]
If there were you would see it in the commits and history.

**Comment by jmgaleano** [comment]
Ahhh!

**Comment by wazerstar** [comment]
Had so many problems with pihole, crashing the entire device all time, just to figure out that when uninstalling, it would ask if I wanted to uninstall all apps, and after pressing Y it would just stay there for hours.

Anyways finally got it to more or less uninstall only to figure out dns issues all of sudden.

my headegg fix


```
sudo apt-get remove --purge resolvconf && sudo apt-get install resolvconf 

sudo resolvconf -u

reboot.
```

**Comment by roelfrenkema** [comment]
Tried it out, cant get the admin running. After uninstalling still the same problem with dhcpcd. I will go back to CFS and install de lists with ipset. Saves me the headache.

**Comment by FutureSharks** [comment]
> but dhcpcd.conf is left unchanged, and still contains the line static domain_name_servers=127.0.0.1

Thanks for this! Took me too long to work out why resolution wasn't working after uninstall. Super annoying.

**Comment by dschaper** [comment]
We will be addressing this in the next release. The development code no longer sets the Pi-hole device to use localhost / 127.0.0.1 for the system resolver.

**Comment by JosNun** [comment]
Just for anybody here who still has the issue after trying the above steps, removing dhcpcd5 fixed it for me

```apt remove --purge dhcpcd5```

**Comment by rwev** [comment]
None of the aforementioned hacks to fix DNS after `pihole uninstall` worked for me, but this did:

`sudo systemctl restart systemd-resolved.service`

**Comment by mazafra1** [comment]
After almost 2 years this ticket was opened, this is still happening to me.

**Comment by XenHat** [comment]
> 
> 
> After almost 2 years this ticket was opened, this is still happening to me.

Same, unfortunately

**Comment by TheFirsh** [comment]
```
sudo rm /etc/init.d/pihole-FTL
sudo reboot

```
That godforsaken file puts back the /etc/resolvconf/run/interface/lo.piholeFTL no matter what you do. Finally the nightmare is over.

**Comment by avoidik** [comment]
@TheFirsh `pihole uninstall` hadn't removed everything on my Ubuntu 18.04 machine, I have executed `find / -iname '*pihole*' -not -path '/sys/kernel/*' -print0 2>/dev/null | xargs -0 -o sudo rm -rfi` to clean all the leftovers up in interactive mode, then I temporarily added 8.8.8.8 to /etc/resolv.conf, reinstalled dnsmasq, dhcpcd5 packages, restarted systemd-resolved service, and got my dns resolution back

<details>
  <summary>Click to expand to reveal the list of remaining files</summary>

```
/etc/bash_completion.d/pihole
/etc/rc4.d/S01pihole-FTL
/etc/rc6.d/K01pihole-FTL
/etc/rc1.d/K01pihole-FTL
/etc/rc3.d/S01pihole-FTL
/etc/rc0.d/K01pihole-FTL
/etc/rc2.d/S01pihole-FTL
/etc/cron.d/pihole
/etc/init.d/pihole-FTL
/etc/rc5.d/S01pihole-FTL
/run/pihole
/run/pihole-FTL.port
/run/pihole-FTL.pid
/run/resolvconf/interface/lo.piholeFTL
/run/systemd/generator.late/pihole-FTL.service
/run/systemd/generator.late/graphical.target.wants/pihole-FTL.service
/run/systemd/generator.late/multi-user.target.wants/pihole-FTL.service
/var/log/pihole
/var/log/pihole-FTL.log
/var/log/pihole.log
/var/www/html/pihole
/usr/local/share/man/man5/pihole-FTL.conf.5
/usr/local/share/man/man8/pihole-FTL.8
/usr/local/share/man/man8/pihole.8
```
</details>

```bash
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
sudo apt-get purge dnsmasq dhcpcd5
sudo apt-get install dnsmasq dhcpcd5
sudo systemctl restart systemd-resolved
```

**Comment by thewriteway** [comment]
unfortunately the above fixes did not seem to work also this happened on the new beta release v5, so i guess a fix didn't go in yet?

**Comment by ThatWeirdAndrew** [comment]
I was also experiencing this issue when installing from the master branch, but I am able to install from the v5.0 branch without issue. The v5.0 branch fixed the issue for me.

**Comment by dschaper** [comment]
Version 5 does not modify `/etc/resolv.conf` anymore, nor does it set the nodes resolver to `127.0.0.1`. `pihole-FTL` no longer requires that. `/etc/init.d/pihole-FTL` [has removed those commands](https://github.com/pi-hole/pi-hole/commit/620e1e9c73277fb1f6c1f0be3a8cc3bd9d2b82f5#diff-045722c02800a1422bcac00099aec6db)

**Comment by XenHat** [comment]
I had it happen to me again so I'll post this :
anyone needing an immediate fix can:
1. unlink the /etc/resolv.conf and create a new file in its place with the same name pointing at the dns server of your choice. even works with unbound. 
2. turn off all mechanisms that change the file, or set `chattr +i /etc/resolv.conf` to prevent anything to edit or remove it
    - systemd: /etc/systemd/resolved.conf, uncomment and set to `no` the `useDnsStub`  (sic) property

**Comment by maxloh** [comment]
> None of the aforementioned hacks to fix DNS after `pihole uninstall` worked for me, but this did:
> 
> `sudo systemctl restart systemd-resolved.service`

It works for me too.

**Comment by dschaper** [comment]
Now you won't be able to restart `pihole-FTL`.

**Comment by abir1909** [comment]
Is it safe to uninstall Pihole now and keep internet working? i have V5 installed and i control the RPI remotely. i am afraid to loose access to it.

**Comment by develop1st** [comment]
> ```
> sudo rm /etc/init.d/pihole-FTL
> sudo reboot
> ```
> 
> That godforsaken file puts back the /etc/resolvconf/run/interface/lo.piholeFTL no matter what you do. Finally the nightmare is over.

You've put me out of my misery, thank you.

**Comment by abir1909** [comment]
Do you run that command before or after uninstalling pi-hole ?

**Comment by develop1st** [comment]
> Do you run that command before or after uninstalling pi-hole ?
I had already uninstalled pi hole, and like many others was finding that my resolve.conf was still getting stomped regardless of removing the static configuration from dhcpcd.conf. Removing the pihole-FTL unit file finally stopped that from happening. Since you are on v5, that may not be necessary according to @dschaper in reference to [this change.](https://github.com/pi-hole/pi-hole/commit/620e1e9c73277fb1f6c1f0be3a8cc3bd9d2b82f5#diff-045722c02800a1422bcac00099aec6db)

**Comment by abir1909** [comment]
Thank you

Sent from my iPhone

On May 7, 2021, at 9:20 AM, develop1st ***@***.***> wrote:

﻿

Do you run that command before or after uninstalling pi-hole ?

I had already uninstalled pi hole, and like many others was finding that my resolve.conf was still getting stomped regardless of removing the static configuration from dhcpcd.conf. Removing the pihole-FTL unit file finally stopped that from happening. Since you are on v5, that may not be necessary according to @dschaper<https://github.com/dschaper> in reference to this change.<https://github.com/pi-hole/pi-hole/commit/620e1e9c73277fb1f6c1f0be3a8cc3bd9d2b82f5#diff-045722c02800a1422bcac00099aec6db>

**Comment by jnanes** [comment]
> None of the aforementioned hacks to fix DNS after `pihole uninstall` worked for me, but this did:
> 
> `sudo systemctl restart systemd-resolved.service`

I had the same symptoms after uninstalling pihole today. Running this command resolves the issue, but it returns after a reboot until I run it again. Can anyone help me permanently solve  this?

**Comment by dschaper** [comment]
Try `sudo systemctl enable --now systemd-resolved.service`

**Comment by jnanes** [comment]
This worked

Thank you.
