### ISSUE TITLE
No working GUI and FTL consume 97% CPU

### ISSUE THREAD

**Issue by bobybobybob** [pi-hole/pi-hole#2149]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).    English is not my motherlanguage and dont understand most. 
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**  1

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
I would like to see a normal working pi hole
`{A detailed description of what you expect to see}`

**Actual behaviour:**

when i login in html pihole i only see the buttons and a cyrcle animation. no graph no query
click on query i see   "An error occured while loading the data: Connection refused. Is FTL running?"

i enter in putty console HTOP and see that /usr/bin/pihole-ftl  need 94% of CPU - Core 3

pihole status
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

pi-hole disable and enable does not help

only uninstall and install it again help, but after some hours the problem is back

[?] Would you like to upload the log? [y/N] y
    * Using openssl for transmission.

***********************************
***********************************
[✓] Your debug token is: Use netcat.
***********************************
***********************************
![nixnix444](https://user-images.githubusercontent.com/23042717/39163647-f7d76f20-476a-11e8-8377-852c3e1061a1.jpg)

i use current Armbian and pi hole 3.2.1

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by viktak** [comment]
Exactly same issue here. Is there a way to roll back to a previous version of pi-hole that is working? I have been using pi-hole for over a year with an install and forget experience and ever since I upgraded to the latest version with FTL it only causes headaches...

**Comment by Mcat12** [comment]
@bobybobybob What is the output of `cat /var/log/pihole_debug.log | netcat tricorder.pi-hole.net 9999`

@vgerak What version are you one? Make a debug token.

**Comment by Mcat12** [comment]
You can disable logging in the installer or via `pihole -r`. When FTLDNS is released (or if you join the beta), you can disable logging to the filesystem while keeping logs (though if you want stats beyond 24hrs, you will have to enable the database).
