### ISSUE TITLE
Admin Web Interface Not Loading in Chrome

### ISSUE THREAD

**Issue by alexiscordova** [pi-hole/pi-hole#2154]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Admin web interface should load in all browsers

**Actual behaviour:**

<s>http://pi.hole/admin and http://[ip-address]/admin both give 404 errors with the following message:
"This site can’t be reached
pi-hole’s server IP address could not be found.
Search Google for hole admin
ERR_NAME_NOT_RESOLVED"</s>

[Edit: 5/4/18]
Chrome, after some period of time, is not resolving the IP address nor pi.hole/admin, and it gives the following error message:
"This site can’t be reached
http://pi.hole/admin/ is unreachable.
Search Google for hole admin
ERR_ADDRESS_UNREACHABLE"

**Steps to reproduce:**

1. Install Pi-Hole via curl command
2. Upon completion, attempt to access admin web interface

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

[Edit: 5/4/18]
<s>wmtf8pnhsw</s>
303gvfgefc

**Troubleshooting undertaken, and/or other relevant information:**

I've reinstalled both Raspbian (via NOOBS) and Pi-Hole numerous times to no avail. This originally occured on an up-to-date installation, and has not been fixed on subsequent reinstallations. FWIW this issue seems to have popped up very recently, as only a few days ago the admin interface was working fine.

[Edit: 5/4/18]: The issue was temporarily resolved after changing the network port from wifi to ethernet, but after about a week the issue cropped up again in Chrome only; Safari continues to work as expected.

**Comment by Mcat12** [comment]
Have you tried http://pi.hole/admin? `pi-hole` is not the default hostname.

**Comment by alexiscordova** [comment]
Oops, that was a typo. The IP address should work regardless, right? Neither works at the moment.

**Comment by Mcat12** [comment]
What is the output of `curl -I http://localhost/admin/`

**Comment by alexiscordova** [comment]
I'm not sure what's going on, but the site is working in other browsers just not Chrome. This doesn't seem to be a Pi-Hole issue.

**Comment by alexiscordova** [comment]
It does seem that, after some period of time, Chrome can't resolve the IP address or pi.hole/admin. I "solved" my issue by switching to ethernet, and it worked for about a week before failing again this morning. Both work fine in Safari, albeit this is not my normal browser.

**Comment by alexiscordova** [comment]
The error I am seeing now states:
This site can’t be reached
http://pi.hole/admin/ is unreachable.
Search Google for hole admin
ERR_ADDRESS_UNREACHABLE

**Comment by dschaper** [comment]
Can you see the resolver? `dig pi.hole` and see if that gives you back the address.

**Comment by alexiscordova** [comment]
In the "answer section," it does give me the correct local address.

The odd thing about this is that the server is up and running, but in Chrome seems to be choking on something after some period of time. I'm having difficulty determining whether this is a Chrome issue or a Pi-Hole issue, as my initial installation had been working flawlessly since day 1; it's only been recently—maybe the latest Pi-Hole update? Chrome updates too often to know if it's a change in the browser—that this has cropped up.

**Comment by rrobgill** [comment]
Could this be due to chrome's [synchronous dns](https://discourse.pi-hole.net/t/disable-async-dns-resolver-in-google-chrome/9500)? 

If chrome sneaks to its own server it won't be able to resolve 'pi.hole'.

**Comment by alexiscordova** [comment]
@rrobgill I'm thinking most likely. After my most-recent installation, pi.hole/admin still doesn't work but the pre-installed raspberrypi.local/admin does, and I haven't had this DNS-related error show up for about a week. I'm at a loss, but I'll close this as the issue is no longer occurring.

🤞🏽
