### ISSUE TITLE
DNSMASQ does not disable when checking out development branch

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/pi-hole#2156]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`dnsmasq service should get disabled when switching over to development branch`

**Actual behaviour:**

`dnsmasq service is still running, therefore preventing pihole-FTL from starting. The fix used to be to run a pihole repair, but due to one of the latest commits in the development branch that removes the stopping of services, this fix no longer works`

**Steps to reproduce:**

`Check out development from master branch and attempt to run a pihole repair thereafter`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`i63bnabo5y`

**Troubleshooting undertaken, and/or other relevant information:**

`Check for pihole updates, as well as alternate between branches and ran several pihole repairs`

**Comment by kyle95wm** [comment]
Yeah, and the funny thing is, this isn't a problem after checking out the FTLDNS branch for ALL components, so it's a dev only issue

**Comment by PromoFaux** [comment]
Ok, will need to look into this later. That snippet about is from the Dev branch!

**Comment by PromoFaux** [comment]
@kyle95wm I've found the issue, should be fixed soon..

**Comment by PromoFaux** [comment]
@kyle95wm this should now be fixed in dev. Can you give it a go please?

**Comment by kyle95wm** [comment]
Works! Here's a debug token to prove it:
`hj2w1l8ieo`

I switched to master and back again with no problems.
