### ISSUE TITLE
Error: Unable to update package cache.

### ISSUE THREAD

**Issue by jfebrerc** [pi-hole/pi-hole#2160]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Installation of pi-hole

**Actual behaviour:**

  [✗] Root user check
      Script called with non-root privileges
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source

  [✓] Sudo utility check

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check

  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"

With root directly:

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check

  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"

**Steps to reproduce:**

sudo curl -sSL https://install.pi-hole.net | bash

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I tried to use the 3 methods listed to install pi-hole. Nothing is installed and no configuration folder created (/etc/.pihole  /etc/pihole or /var/www/html/admin).
Sorry for my bad english!

**Comment by dschaper** [comment]
Did you try the solution we suggested?

>Please try "apt-get update"

**Comment by Mcat12** [comment]
> Error: Unable to update package cache. Please try "apt-get update"

What is the output of `sudo apt-get update`?

**Comment by jfebrerc** [comment]
Yes, I tried. Output: 
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Ign:3 http://ftp.uk.debian.org/debian squeeze InRelease
Ign:4 http://ftp.uk.debian.org/debian squeeze Release
Ign:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Ign:16 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en
Ign:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Ign:16 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en
Ign:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Ign:16 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en
Ign:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Ign:16 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en
Ign:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Ign:16 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en
Err:5 http://ftp.uk.debian.org/debian squeeze/main armhf Packages
  404  Not Found [IP: 78.129.164.123 80]
Ign:6 http://ftp.uk.debian.org/debian squeeze/main all Packages
Ign:7 http://ftp.uk.debian.org/debian squeeze/main Translation-en
Ign:8 http://ftp.uk.debian.org/debian squeeze/main Translation-en_GB
Ign:9 http://ftp.uk.debian.org/debian squeeze/contrib armhf Packages
Ign:10 http://ftp.uk.debian.org/debian squeeze/contrib all Packages
Ign:11 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en
Ign:12 http://ftp.uk.debian.org/debian squeeze/contrib Translation-en_GB
Ign:13 http://ftp.uk.debian.org/debian squeeze/non-free all Packages
Ign:14 http://ftp.uk.debian.org/debian squeeze/non-free armhf Packages
Ign:15 http://ftp.uk.debian.org/debian squeeze/non-free Translation-en_GB
Reading package lists... Done
W: The repository 'http://ftp.uk.debian.org/debian squeeze Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ftp.uk.debian.org/debian/dists/squeeze/main/binary-armhf/Packages  404  Not Found [IP: 78.129.164.123 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by dschaper** [comment]
You have sources for Stretch and Squeeze which is not going to work. Also you have Raspbian mixed with Debian. These are not Pi-hole install issues, they are OS issues that need to be resolved. We can't install with misconfigured apt sources as we would not be able to be sure that the packages we install were the correct ones for the system.

**Comment by dschaper** [comment]
If the issue persists after the sources are corrected please open a new issue.
