### ISSUE TITLE
Add Support for Bcrypt Hashing Algorithm

### ISSUE THREAD

**Issue by MattAKAFred** [pi-hole/pi-hole#2168]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x-ish] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
Continues off of https://github.com/pi-hole/pi-hole/pull/360

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Password is hashed using a slow hashing algorithm

**Actual behaviour:**

Currently, I'm not sure if the password is hashed before or after transmission, but it will be in the new WebUI. Hashing in new UI is done with SHA-256.

**Steps to reproduce:**

Use a password on your webUI.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

N/A

I was digging through the new WebUI commits and noticed that SHA256 is being used for hashing. While this is okay (read: much better than nothing) it does not follow generally recommended security practices. SHA-256 represents a "fast" algorithm, making it relatively easy to brute-force passwords, especially if they are being transmitted in plain (hashed) text via HTTP. Best practices suggest it's better to use a slow hashing algorithm like Bcrypt instead:

https://rietta.com/blog/2016/02/05/bcrypt-not-sha-for-passwords/
https://github.com/dcodeIO/bcrypt.js

I was told [Bcrypt needs to be supported in core first](https://github.com/pi-hole/web/issues/23), so here I am.

**Comment by dschaper** [comment]
Is this an issue or a Feature Request for a different hashing algo?

**Comment by Mcat12** [comment]
I believe feature request for a different algorithm, but because we can only use HTTP for transporting the password (hashed or not), there is not much point in changing it. The hashed password is effectively the password for the API already.

**Comment by MattAKAFred** [comment]
That's a good point, but in the interest of promoting good security practices bcrypt can help prevent brute-force reverse-engineering the original password. 

Basically, why not go with the industry standard?

**Comment by Mcat12** [comment]
Because it does not give enough benefit. Better would be to come up with a way to store and transmit the password from the web interface to the server more securely. We run SHA256 twice on the password, which is better than just once (less vulnerable to rainbow-table attacks and brute-forcing).

**Comment by MattAKAFred** [comment]
Bcrypt has been around longer than SHA-256 and is well accepted as the industry standard. The [Bcrypt.js](https://github.com/dcodeIO/bcrypt.js) git I linked early is very stable and has zero dependencies, it should be pretty easy to implement - since we are already using js for the SHA-256 implementation...

**Comment by dschaper** [comment]
How would we implement that in bash/posix shell script?

**Comment by MattAKAFred** [comment]
> because we can only use HTTP for transporting the password (hashed or not), there is not much point in changing it. The hashed password is effectively the password for the API already.
I wish I could guarantee that everyone who uses pihole uses a unique password for the webui only and never uses that password again in any of their systems. If that were the case, then yes, you're right, because the hashed password is transmitted in plain text it is already vulnerable, but this would protect anyone who has ever used a password twice.

**Comment by MattAKAFred** [comment]
> How would we implement that in bash/posix shell script?

[Is the SHA encryption algorithm being tested on the new WebUI not also just js?](https://github.com/pi-hole/web/blob/new/authentication/src/views/Login.js#L13)

**Comment by dschaper** [comment]
I would also be nice to make sure that everyone that installs with Raspbian changes from `pi/raspberry` as a user/pass. But we can only do so much. We really do too much hand holding as it is. It's a great idea, I think security should be primary. But we have to look at the whole package. Shell script and the web interface included. And how complex things get, knowing who our users are, what they are installing on, what information is protected and who would like to get that information. 

And no, it's not just the webui, it's the shell as well. Passwords are set with the `pihole` shell utility.

**Comment by dschaper** [comment]
Everyone can make their final comments, and then we'll close this, it's really a feature request and not an issue/bug that needs to be resolved. Feel free to open a Feature Request on https://discourse.pi-hole.net and that will allow others to vote and voice.
