### ISSUE TITLE
Extend functionality with url decoding redirect service

### ISSUE THREAD

**Issue by kisst** [pi-hole/pi-hole#2171]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

When a page which is blacklisted because it's used only for statistics, and they host only redirect jump like `domain.tld/link.php?url=encoded.url/page1` then by pointing to the pi instead of  the this page is blocked, I got a redirect to the `encoded.url.page1`

**Actual behaviour:**

This functionality does not exist at present.

**Steps to reproduce:**

Block redirect services and visit a redirect url.

**Troubleshooting undertaken, and/or other relevant information:**

This function to be implemented needs a new table which stores the list of domains which are redirect services not direct blocks, and they syntax per domain to extract the url, there are some browser plugins which can be used to garter this lists ( skip redirect, Redirect Bypasser, etc).
To be able to differentiate from the block page ( which based on some discussion it might be removed ) probably should deploy it as an independent new module, as part of the install provide it as option ( like now the web-admin ) and then in the admin settings page, next to where the blackhole endpoint should be ( the address of the pi.hole or 0.0.0.0 or local proxy or whatever ) there can be an additional option for the url decoding redirect endpoint, so if it's deployed to other box then can be pointed to it.

**Comment by dschaper** [comment]
As per the template: 

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

Although this is out of scope in my view, but please open a Feature Request so there can be further discussion.

Closing.
