### ISSUE TITLE
Issue using it along with wordpress (worked before)

### ISSUE THREAD

**Issue by Kendama165** [pi-hole/pi-hole#2173]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
3

---
**Expected behaviour:**
Trying to load a wordpress setup (or anything for that matter) and being funcional like I had before clean wipe of OS.

**Actual behaviour:**
"[ERROR]: Unable to parse results from queryads.php: Unhandled error message ( )"

**Steps to reproduce:**
Rename admin folder to anything (mine is piadmin)

**Debug token provided:**
zq7udgydiu

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by Mcat12** [comment]
Moving the admin page is not supported at the moment. Try running the wordpress installation on a different port and from a different folder.
