### ISSUE TITLE
Install blocks due to dpkg --configure reading on stdin

### ISSUE THREAD

**Issue by JulienPalard** [pi-hole/pi-hole#2178]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I expect the install script to finish.

**Actual behaviour:**

The install scripts indefinitly blocks, as `dpkg` tries to ask what to do with a locally modified dnsmasq.conf. 

**Steps to reproduce:**

* Install an old version of dnsmasq
* Change `/etc/dnsmasq.conf`
* Run `sudo bash basic-install.sh`

**Troubleshooting undertaken, and/or other relevant information:**

Ran a `ps fauxwww`, got:

```
root     21984  0.0  0.0  62172  4012 pts/0    S+   14:02   0:00  |           \_ sudo bash basic-install.sh
root     21985  0.0  0.0  12284  4136 pts/0    S+   14:02   0:00  |               \_ bash basic-install.sh
root     24805  0.0  0.2  66764 22352 pts/0    S+   14:05   0:00  |                   \_ /usr/bin/perl -w /usr/share/debconf/frontend /usr/bin/debconf-apt-progress -- apt-get --yes --no-install-recommends install dnsmasq netcat idn2 lighttpd php-common php-cgi php-sqlite3
root     24811  0.0  0.1  28436  8732 pts/0    S+   14:05   0:00  |                       \_ /usr/bin/perl -w /usr/bin/debconf-apt-progress -- apt-get --yes --no-install-recommends install dnsmasq netcat idn2 lighttpd php-common php-cgi php-sqlite3
root     24814  0.2  0.6  95832 51336 pts/0    S+   14:05   0:00  |                       |   \_ apt-get -o APT::Status-Fd=4 -o APT::Keep-Fds::=5 -o APT::Keep-Fds::=6 --yes --no-install-recommends install dnsmasq netcat idn2 lighttpd php-common php-cgi php-sqlite3
root     24979  0.0  0.1  26640 12080 pts/1    Ss+  14:05   0:00  |                       |       \_ /usr/bin/dpkg --status-fd 22 --configure --pending
root     24813  0.0  0.0  23708  4456 pts/0    S+   14:05   0:00  |                       \_ whiptail --backtitle Package configuration --title Installing packages --output-fd 8 --nocancel --gauge --   8 188 0
```

See `/usr/bin/dpkg --status-fd 22 --configure --pending`, an strace on it gives:

```
root@silence#strace -s 999 -f -p 24979
strace: Process 24979 attached
read(0, 
```

So dpkg is reading on stdin but what? Maybe just try to write garbage to it while still stracing:

```
echo 1 >> /proc/24979/fd/0
```

Bingo straces (on dpkg) talks:

```
read(0, "1\n", 4096)                    = 2
ioctl(0, TCFLSH, TCIFLUSH)              = -1 ENOTTY (Inappropriate ioctl for device)
write(2, "\n", 1)                       = 1
write(2, "Configuration file '/etc/dnsmasq.conf'\n", 39) = 39
write(2, " ==> Modified (by you or by a script) since installation.\n", 58) = 58
write(2, " ==> Package distributor has shipped an updated version.\n", 57) = 57
write(2, "   What would you like to do about it ?  Your options are:\n    Y or I  : install the package maintainer's version\n    N or O  : keep your currently-installed version\n      D     : show the differences between the versions\n      Z     : start a shell to examine the situation\n", 275) = 275
write(2, " The default action is to keep your current version.\n", 53) = 53
write(2, "*** dnsmasq.conf (Y/I/N/O/D/Z) [default=N] ? ", 45) = 45
read(0, 
```

So it's dnsmasq.conf that has been changed locally since previous setup (yes I'm reusing a machine where I had a dnsmasq, bad idea probably).

Temporary fix: I sent Y like this: `echo Y >> /proc/24979/fd/0` :)

**Comment by Mcat12** [comment]
According to this, we can add an option on to dpkg to take the default option, but is that what we want? https://unix.stackexchange.com/a/416816

**Comment by dschaper** [comment]
Reviewing this issue, we can set `dpkg` to use the default, but that will overwrite the existing configuration. I'm not sure if that is the best option to use at this point.

**Comment by dschaper** [comment]
I don't thinks this is something that we can solve in an automated installation. The choices are to leave the configurations as is, to change to the upstream package change or diff the two into a new file. Any of those choices require user intervention and this doesn't appear to be a frequent situation.

**Comment by pjz** [comment]
Or check for the file at the beginning of the install and warn the user that it's going to be overwritten and get them to confirm that's okay... then nuke it.

**Comment by neklaf** [comment]
I faced the same problem installing Pi-Hole but in my case it was configuring resolvconf package but I had created previously to this installation these files: /etc/resolvconf/resolv.conf.d/base and /etc/resolvconf/resolv.conf.d/head. Then the installation process is stuck installing the needed packages. I solved this problem installing manually resolvconf package and answering the questions and launching again the installation command:
Configuration file '/etc/resolvconf/resolv.conf.d/base'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** base (Y/I/N/O/D/Z) [default=N] ? Y

**Comment by dschaper** [comment]
We've removed the dialog based front end for `apt` in the development branch. This will be in the next release.
