### ISSUE TITLE
Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by DonLexos** [pi-hole/pi-hole#218]
Just updated using the install script to 2.3 and noticed the same error I experienced earlier. I am not sure if it means it does not download the script or it auto-retries (since there is no feedback), but maybe (since I experience this almost all the time when I run the script) it is a good idea to check if the files are indeed fetched or not. Right now it comes down to me re-doing the script again to make sure.
```
::: Installing scripts...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1750  100  1750    0     0   5474      0 --:--:-- --:--:-- --:--:--  5468
::: ...done.

```
On a side note, would it be an idea to add a textfile in the /etc/pihole (that has the version number in it maybe). That way the installation script can check (at the beginning) if the file exists, if it does it is an upgrade and it can skip installing dnsutils, dnsmasq etc and maybe even the static IP etc.

**Comment by PromoFaux** [comment]
^its like you read my mind or something. Im working on overhauling the install script to work even more intelligently with existing installs!

**Comment by DonLexos** [comment]
Ha! Your mind is telling me another coffee is always a great idea and should not be postponed so long ;-)

On a more serieus note, even a retry does not fix it, the first 4 simly return the error, and when I dig raw... it does resolve..

;; ANSWER SECTION:
raw.githubusercontent.com. 23   IN      CNAME   github.map.fastly.net.
github.map.fastly.net.  22      IN      A       23.235.43.133

I think it's in this part of the installation:
```
installScripts(){
$SUDO echo " "
$SUDO echo "::: Installing scripts..."
#$SUDO rm /usr/local/bin/{gravity,chronometer,whitelist,blacklist,piholeLogFlush,updateDashboard}.sh
$SUDO curl -o /usr/local/bin/gravity.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh
$SUDO curl -o /usr/local/bin/chronometer.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/chronometer.sh
$SUDO curl -o /usr/local/bin/whitelist.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/whitelist.sh
$SUDO curl -o /usr/local/bin/blacklist.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/blacklist.sh
$SUDO curl -o /usr/local/bin/piholeLogFlush.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/piholeLogFlush.sh
$SUDO curl -o /usr/local/bin/updateDashboard.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/updateDashboard.sh
$SUDO chmod 755 /usr/local/bin/{gravity,chronometer,whitelist,blacklist,piholeLogFlush,updateDashboard}.sh
$SUDO echo "::: ...done."
}
```
I have no idea how these scripts work (exactly), I can read them but hardly program them myself, but since it appears to be a function is there a way to catch any errors (and maybe retry or something)?

Oh regarding the existing installation, there is this thing that if you would skip dnsutils and others, I see **git** is new, and you would/could skip that when you jump to just the pi-hole files only, so that might give a headache for upgrades.

**Comment by dschaper** [comment]
I'd like to leave the selection of IP addresses in the script, so people can run and select or deselect IPv6 and change interfaces if needed. (I have IPv4, IPv6, eth0, eth1, wlan0 and every once in a while tun's and being able to switch on the fly with `basic-install.sh` is very nice.) 

As for the dependencies, I guess we could run an apt-cache policy and check the output to see if packages are already installed, but running an apt-get with an already installed package just returns 0 packages to be installed, so it's not really a time sink...

**Comment by dschaper** [comment]
I think @PromoFaux was thinking about changing up the script so that it doesn't `curl` anymore but actually does a `git fetch`. I like that approach, it would allow us to be able to pull based upon hashes instead of just release versions. (Would make it easier to test out alpha/feature/bugfix branches if we could install based on a hash...)

**Comment by DonLexos** [comment]
I like the git approach, and I agree it does not take up a lot of time on the dependencies. However assuming I did a working installation before setting the IP etc again seems a bit double. Imho in a normal user case you would not be switching ip4/6 or eth0/wlan0 on a simple upgrade. I understand though that right now the installation script provides an easy way to do just that.

**Comment by PromoFaux** [comment]
I'll look at this over the weekend.

**Comment by dschaper** [comment]
@DonLexos We've changed repo's to an Organization, does this issue still exist for you?

**Comment by dschaper** [comment]
@DonLexos If you can, try the new installer that's been pushed to master. It should resolve any issues you have.

**Comment by DonLexos** [comment]
It worked the third time I tried it last time, but updated using the install.pi-hole.net just now and the updating package list took a bit (think the output is hidden?), after that Extracting from packages takes a fair amount (2+ minutea) where its at 100% but the spinning thing keeps spinning .. not entirely sure what is keeping it. Love the new way things are displayed though :-)

Will update if it indeed does continue to run.

**Comment by dschaper** [comment]
The current display overhaul was done by @PromoFaux, and do keep us updated on your install.

**Comment by DonLexos** [comment]
Right now it is still running (for about 5 minutes) on the "Extracting templates from packages: 100%...-" with a spinner on the complete right. Load on the pi is 2.9x and RAM dropped to 293MB free, it is busy, just not sure what it is doing.

**Comment by dschaper** [comment]
Is it possible to get a screenshot? That sounds like the Raspbian apt package manager is stuck?

**Comment by DonLexos** [comment]
Tailing /var/log/messages now... many of these:
Jan 25 10:04:27 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jan 25 10:05:27 2016 [try http://www.rsyslog.com/e/2007 ]
Jan 25 10:05:27 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jan 25 10:06:27 2016 [try http://www.rsyslog.com/e/2007 ]

**Comment by dschaper** [comment]
`cat /tmp/pihole-install.log`?

**Comment by DonLexos** [comment]
```
pi@raspberrypi:~ $ cat /tmp/pihole-install.log
:::
::: Updating package list before install... done!
::: Upgrading installed apt-get packages.../
```

**Comment by dschaper** [comment]
It looks like it's stuck in a call to `apt-get upgrade`. Was this a fresh install of Raspbian Jessie?

**Comment by DonLexos** [comment]
hmmm from pstree
```
-sshd-+-sshd---sshd---bash
        |      `-sshd---sshd---bash---bash-+-bash-+-sleep
        |                                  |      `-sudo---apt-get---dpkg---frontend-+-phpmyadmin.conf
        |                                  |                                         `-whiptail
        |                                  `-tee
```
Could be unrelated to pi-hole, looks like it hangs on something else. This was not a fresh install (it is a 1 week old installation).

**Comment by DonLexos** [comment]
Seems it was stuck on phpmyadmin (since that required the MySQL root password) . . will update that manually and then let you know about the pi-hole installation script.

**Comment by dschaper** [comment]
It looks like there's a whiptail dialog box that isn't visible that's holding things up. Might be that there is a package upgrade that needs user input, but it's output is being redirected...

**Comment by dschaper** [comment]
Ah, I'm going to flag this as a bug then, we need to take into account the possibility that `apt-get upgrade` could require user input...

**Comment by DonLexos** [comment]
Ok try 2 .. .

**Comment by DonLexos** [comment]
From the installer output,
```
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... not found!!
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole../fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com                                                                                                               done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin..|fatal: unable to access 'https://github.com/jacobsalmela/AdminLTE.git/': Could not resolve host: github.com                                                                                                                                    done!
```

**Comment by DonLexos** [comment]
Second time it does run, but the error was generated for github.com first time (that changed from raw.githubusercontent.com). No idea why though, since I can dig both domains.

**Comment by dschaper** [comment]
There might have been some residual from the `apt-get` hang-up.

**Comment by DonLexos** [comment]
I repooted the pi, then fixed the phpmyadmin, did a apt-get upgrade and then run the script.

**Comment by dschaper** [comment]
Okay, we'll take a look at that also along with the bug report for the `apt-get upgrade` issue.

**Comment by DonLexos** [comment]
Its weird, I just ran the installation again and it cannot access github again.. .maybe its a timeout thing?

From the installer output:
Updating repo in /etc/.pihole../fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com  done!

That was after I just successfully installed it (in try 2).

**Comment by dschaper** [comment]
What's your `/etc/resolv.conf` look like?

**Comment by DonLexos** [comment]
```
pi@raspberrypi:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 127.0.0.1
```

**Comment by dschaper** [comment]
And that looks good, I'm not sure why the transient resolver error...

**Comment by dschaper** [comment]
Does it seem isolated to the Pi and to Github or are your client machines showing signs of timeouts resolving domain names?

**Comment by DonLexos** [comment]
None at all, however the router does have dns2 set to google if the pi fails so I doubt I would notice that. Could it be related all services are stopped before the scripts are fetched?

**Comment by dschaper** [comment]
It's possible, if dnsmasq is stopped then there may be issues with resolution.

**Comment by DonLexos** [comment]
Well the script outputs:
```
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for toilet... already installed!
:::    Checking for figlet... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services. done.
```

**Comment by dschaper** [comment]
I'm just wondering why we haven't had more reports of that being an issue, and I don't think we've run into it in testing. But it's an item to consider.

**Comment by DonLexos** [comment]
I have no idea what goes wrong, this time it failed try #1 and #3 but the second time it worked perfectly fine. If there is anything on my end that I can do to test it let me know. I might even be the only one.

**Comment by dschaper** [comment]
Thanks for the offer, we'll definitely take you up on that if we need to!

**Comment by DonLexos** [comment]
Well what I can do that if there is a 2.4 release I can do a clean installation again (without phpmyadmin/mysql) and see what happens then. MySQL was added simply to play with the dev branche of the admin screen for the statistics, but I noticed there is a SQLite version being developped so there would be no need to run mysql.

**Comment by dschaper** [comment]
With the amount of active developing going on I would say there probably will be a v2.4 within the week. The development team is spread out globally so there's always something going on with the project.

**Comment by DonLexos** [comment]
Yeah I noticed, was playing with the stats from @jacobsalmela but learned there is also a white/blacklist version of the interface, one with realtime queries and even one that runs with SQLite .. I might need an extra pi to play on and have one running the latest stable ;-)

**Comment by dschaper** [comment]
I have a few myself, and a number of uSD cards with different OS's on them. We develop in the open, so feel free to pull down which ever branch you'd like to play with. With the obvious caveat that we only support the master branch code.

**Comment by DonLexos** [comment]
I guess if the script does check for apt-get upgrade but does not run it that part is fixed. 

On the timeout/not-found issue for *.github.com: in html you have the option to pre-fetch a dns for use later, not sure if that can be done in the shell
```
    <link rel="dns-prefetch" href="//www.domain1.com">
    <link rel="dns-prefetch" href="//www.domain2.com">
```
More information from [Google PageSpeed](https://developers.google.com/speed/pagespeed/service/PreResolveDns)

**Comment by PromoFaux** [comment]
>I guess if the script does check for apt-get upgrade but does not run it that part is fixed. 

The script now checks if any updated packages are availible, using [this](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L305) rafter nifty one liner @dschaper pointed me at! 

![image](https://cloud.githubusercontent.com/assets/1998970/12584234/711f3578-c43e-11e5-937a-59f12bc9444f.png)
;)

I think it has to do with the `dnsmasq` being stopped during install. I need to check the order of the script. Strange thing is, I'm yet to run into that particular issue myself, and I uninstall/reinstall a lot....

**Comment by DonLexos** [comment]
Yes I know it is all old on the Google Site, I was merely referencing to pre-fetching the domain you will be downloading the script from ;-) I was lucky enough to get errors 2 out of 3 times last time I tried it, and when I get them I only get them for the first X items, eventually it works. I am awaiting a 'release' and then I will clean up the SD card, redo a clean installation and see how it works.

I am on a 200 Mbit Cable network and use GoogleDNS if the pi fails, I assume that is not the issue at all.

That said, it can't hurt to check for errors during or after the installation maybe? I mean, I got a "yay it all worked and is installed" even when 0 scriptfiles could be downloaded from github.

**Comment by DonLexos** [comment]
Will be doing a new clean installation of 2.4 later tonight, will post back how that worked out :)

**Comment by DonLexos** [comment]
I did some (alpha?) testing yesterday but did not get the error anymore, but it worked, this can be closed I believe.

**Comment by PromoFaux** [comment]
Well, we're no longer curling the scipts from github... so it shouldn't be an issue.

Have you had issues since we started cloning the repository into `/etc/.pihole/`?

**Comment by DonLexos** [comment]
Since yesterday evening 23:59 hrs? ;-) Not really. I assume that feature updates can be done using git?

**Comment by PromoFaux** [comment]
We've been cloning the repo for a few days now (since 25/01 actually)

**Comment by DonLexos** [comment]
Yes well, I was on 'solid release' 2.3 before and that was a week old, but yes. i thought maybe there would be an alternative to upgrading instead of running the install script again, but I remember there are all kinds of new things in the installer to check for a previous installation.

**Comment by PromoFaux** [comment]
Exactly. Why maintain 2 scripts, when you can have 1 script that does both jobs?
