### ISSUE TITLE
/etc/pihole/adlists.list not being re-generated

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/pi-hole#2183]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`If /etc/pihole/adlists.list is deleted, and "pihole -g" is ran, the adlists file should be re-generated`

**Actual behaviour:**

`On the FTLDNS branch, the above behaviour is completly ignored. When "pihole -g" is ran, no adlists are downloaded, and therefore 0 domains are being blocked`

**Steps to reproduce:**

`Delete the file /etc/pihole/adlists.list and then update gravity.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`m1hktki5cs`

**Troubleshooting undertaken, and/or other relevant information:**

`Running a repair doesn't do anything. However, running a re-configure brings up an option to add the default lists. This is way too much, just to get the default lists back.`

**Comment by Mcat12** [comment]
This is somewhat expected. The default lists are now only in the installer, so if someone deletes the ad lists, then things should break because a critical piece was deleted.

**Comment by kyle95wm** [comment]
@Mcat12 so are you saying that the default lists should be backed up in case one wants to go back to them? There should be an option to regenerate the lists without jumping through all the reconfiguration hoops.

**Comment by PromoFaux** [comment]
The decision to move away from providing a "default" set of adlists was not one taken lightly, and it was to further distance ourselves from the contents of the lists.

Unfortunately, too many people equate an adlist blocking a particular domain with Pi-hole having made that decision. By having the list choice in the initial install wizard, the onus is on the user as to whether or not he/she wishes to use them.

They've always been just a suggestion, this just further solidifies that notion.

Hope that makes sense :)
