### ISSUE TITLE
Adding domain to whitelist, still blocked after restartdns

### ISSUE THREAD

**Issue by gopackgo90** [pi-hole/pi-hole#2188]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Add a domain to the whitelist by adding it to /etc/pihole/whitelist.txt. After running 'pihole restartdns', going to the whitelisted domain should work (not be blocked by pihole).

**Actual behaviour:**

Add a domain to the whitelist by adding it to /etc/pihole/whitelist.txt. After running 'pihole restartdns', going to the whitelisted domain still results in the domain being blocked by pihole, even though it says that the domain is whitelisted. Running nslookup on the domain on the pihole device still shows the ip address of the pi.

**Steps to reproduce:**

1. Edit /etc/pihole/whitelist.txt and add a new domain that was blacklisted.
2. Run pihole restartdns
3. Run nslookup <domain> on the pihole device
4. Observe the returned IP address is the IP of the pihole, not the actual IP of the domain.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

1k2drigpmd

**Troubleshooting undertaken, and/or other relevant information:**

Running pihole -g afterwards seems to be the only way to resolve this. According to [this](https://discourse.pi-hole.net/t/how-do-i-flush-my-pi-hole-cache/3020) running pihole restartdns should be sufficient.

**Comment by dschaper** [comment]
Manually editing the whitelist.txt file is adding a new domain to the lists, so it's functioning as intended. Flushing just clears out the cache, you still need to import that whitelist edit in to the Pi-hole. If the domain is added via `pihole -w` or via the webpage then the steps are automated for you and there is no need to flush.

**Comment by dschaper** [comment]
The linked Discourse article is confusing and possibly inaccurate in some cases. Have flagged that for follow up and clarification.

**Comment by gopackgo90** [comment]
Ok, I using the scripts from https://github.com/anudeepND/whitelist/blob/master/scripts/whitelist.sh to automate this for other users, so I was hoping to do this in an automated way.
Is there a better command to run after editing the whitelist file to make sure it gets through or is pihole -w the only way to have this effect (or for some reason pihole -g)?

**Comment by dschaper** [comment]
If you manually edit any of the source files or whitelists, you then need to make Pi-hole aware of your edits, so `pihole -g` would import your changes into the Pi-hole, is there a reason you would not want to do this? That script is doing things in a way not designed or intended for Pi-hole operation.

**Comment by gopackgo90** [comment]
If pihole -g is an appropriate action to take that’s fine, I am fine with doing that, thank you! Would you like me to close this issue?

**Comment by gopackgo90** [comment]
My only hesitation with pihole -g is that it also updates the blacklist, and I was hoping to do this whitelist check a few times per day. I don’t want to run into rate limiting from adlist providers.
https://discourse.pi-hole.net/t/how-often-does-pi-hole-update-the-ad-lists/4383

Is there a more selective command that will just reload the whitelist?

**Comment by anudeepND** [comment]
Sorry to hijack this thread.
 @gopackgo90 the script is now [updated](https://github.com/anudeepND/whitelist/commit/463b309ffb5f023f7290adb36b4f57ec29744da2). Since the whitelist file is not updated often, you don't need to run the script often. 

> That script is doing things in a way not designed or intended for Pi-hole operation.

@dschaper Can I know what's wrong with the script? Any suggestions to make it better? (I have a limited knowledge of shell scripting)

**Comment by dschaper** [comment]
What I would suggest for the interim while the API is worked on, is that you add some logic to the script to only fire if there is a change to the lists. How that is implemented is up to you, but if there are users downloading multiple times a day and the lists are unchanged then there are a lot of `pihole -g` calls that will be made unnecessarily. This causes a pause in DNS resolution and may not be the best user experience.

**Comment by PromoFaux** [comment]
@anudeepND

`pihole -g --skip-download --whitelist-only`

That will process the whitelist (and any changes made to it) without downloading the source lists

**Comment by PromoFaux** [comment]
Actually wait.. I've a feeling that also deletes the preeventhorizon list... not ideal!

**Comment by anudeepND** [comment]
@PromoFaux Great! Is this available in latest stable release?

**Comment by PromoFaux** [comment]
I _think_ so, though not tested! (currently running the `development` branch)

As far as I'm aware, yes. I got that command by reading the source of `gravity.sh` and `list.sh` in `master` branch at least :)

**Comment by anudeepND** [comment]
Just checked, works on Core v3.3.1 FTL V3.0

**Comment by gopackgo90** [comment]
Thanks @anudeepND and @PromoFaux ! I'll close this issue.
