### ISSUE TITLE
Cant update FTL

### ISSUE THREAD

**Issue by dutchdragon3** [pi-hole/pi-hole#2191]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [/] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [/] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{FTL Being online and can update}`

**Actual behaviour:**

`{FTL is offline and Cant update}`

debug token : fqrgzl2p1o

I just install pihole on raspbian in hyper v but now i saw that the ftl service was offline so i google it and i easy fix was update pihole so i try to do that but every time i try to update ill get a error see pic,

![image](https://user-images.githubusercontent.com/22243362/40439632-c6221ef4-5ebb-11e8-86dc-1627fecfa60d.png)

how can i fix this ?

**Comment by dschaper** [comment]
Continued at https://discourse.pi-hole.net/t/cant-update-ftl/9794
