### ISSUE TITLE
Is there a way to redirect an IP instead of outright blocking it?

### ISSUE THREAD

**Issue by Starz0r** [pi-hole/pi-hole#2192]
This isn't a actual issue I'm having with Pi-Hole, I just want to see if this feature exists, and as such, I don't feel as it doesn't fit the current issue template. That being said, I did check pull requests beforehand to check if my feature was in development, and it is not.

Anyway, what I'm asking about is not about blocking access to an IP address, instead I'd like to redirect and entire domain, or local IP address to another name. So if someone tries to connect to -> router.local it points to the correct address of -> 192.168.X.Y. Obviously, this can be done in a host file, but I'd like to be able to do it in Pi-Hole so it is supported network wide, and not just an enhancement on devices I use.

**Comment by dschaper** [comment]
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
