### ISSUE TITLE
Please consider adding Doh ort DNS over TLS in the future .

### ISSUE THREAD

**Issue by RichardRMatthews** [pi-hole/pi-hole#2193]
I think Doh and DNS over TLS are very important features for a DNS resolver which would greatly improve security and privacy .

**Comment by DL6ER** [comment]
You ignored the issue template, it states

> * You must follow the template instructions. **Failure to do so will result in your issue being closed.**
> * **Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.**
