### ISSUE TITLE
development branch does not install cleanly

### ISSUE THREAD

**Issue by Cyclonit** [pi-hole/pi-hole#2194]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5

---
**Expected behaviour:**

When executing /automated_install/basic-install.sh of the development branch, the development version should install cleanly.

**Actual behaviour:**

The installation fails to start the DNS resolution. 

> [✓] Installing sudoer file
> 
> [✓] Installing latest Cron script
> 
> [✓] Installing latest logrotate script
> 
> [i] FTL Checks...
> [✓] Detected ARM-hf architecture (armv6 or lower) Using ARM binary
> [i] Checking for existing FTL binary...
> Failed to get unit file state for dnsmasq.service: No such file or directory
> [✓] Downloading and Installing FTL
> Failed to get unit file state for dnsmasq.service: No such file or directory
> 
> 
> [i] Skipping firewall configuration
> [i] Restarting services...
> [✓] Starting lighttpd service
> [✓] Enabling lighttpd service to start on reboot
> [✓] Starting pihole-FTL service
> [✓] Enabling pihole-FTL service to start on reboot
> [✓] Deleting existing list cache
> [✗] DNS resolution is currently unavailable
> [i] Time until retry: 115^C

The web dashboard installs and is accessible. It does however display, that the DNS service is not running. Trying to use the server as DNS resolver fails.

**Steps to reproduce:**

1. Clone the current development branch to /etc/.pihole
```git clone https://github.com/pi-hole/pi-hole.git --branch development --single-branch /etc/.pihole```

2. Prevent the installer from downloading the master branch.
Uncomment lines 1859-1862 in the cloned basic-install.sh.

3. Install the development branch using its /automated_install/basic_install
```bash /etc/.pihole/automated_install/basic-install.sh```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I cannot upload the log because the DNS resolver failing prevents "pihole -d -a" from connecting to the server.

**Troubleshooting undertaken, and/or other relevant information:**

So far nothing, as I am not familiar with the failing code.

**Comment by dschaper** [comment]
The git repository shouldn't be cloned via branch, that isn't supported or tested. You need to run the `pihole checkout` command for all the systems to automatically clone/prep/install development. That said, development is a testing branch and may break at any time. If you want bleeding edge code, try the `FTL` checkout.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/help-us-beta-test-ftldns/8224

**Comment by Cyclonit** [comment]
But given that I am trying to clean up basic-install.sh, how does first installing pihole and then using pihole checkout allow me to do that? I'd need to uninstall pihole first, which would then get rid of the repository again.

**Comment by PromoFaux** [comment]
@cyclonit, although you're checking out and running the dev version of the install script, it is still downloading the master version of FTL, which has no resolution capabilities. You need to tell the installer that you want the FTL Dev branch, so it's a little more involved:


```
git clone https://GitHub.com/Pi-hole/Pi-hole /etc/.pihole
cd /etc/.pihole
git checkout development

sudo mkdir /etc/pihole
echo "development" | sudo tee /etc/pihole/ftlbranch

``` 

And then run basic-install.sh

It's the `ftlbranch` file that's important in this case.

**Comment by Cyclonit** [comment]
That worked, thanks.
