### ISSUE TITLE
Install psmisc

### ISSUE THREAD

**Issue by Al2Klimov** [pi-hole/pi-hole#2201]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

The installation works OOTB.

**Actual behaviour:**

The installer yields `/usr/local/bin/pihole: line 353: killall: command not found`.

**Steps to reproduce:**

In a new directory create the following `Vagrantfile`:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

def mkVm (config, hostname, box)
  config.vm.define hostname do |cfg|
    cfg.vm.box = box
    cfg.vm.hostname = hostname

    cfg.vm.synced_folder ".", "/vagrant"
    cfg.vm.network "private_network", type: "dhcp"

    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
end

Vagrant.configure("2") do |config|
  mkVm config, "debian", "debian/contrib-stretch64"
end
```

... and run:

```bash
vagrant up debian
vagrant ssh debian
```

Inside this VM install Pi-hole as usual (I've done it w/o the web interface) and watch out for the above error message.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L177 This is already in the development branch, but thank you for the report.
