### ISSUE TITLE
Cannot access dashboard: 403 forbidden

### ISSUE THREAD

**Issue by Hk1020** [pi-hole/pi-hole#2203]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The admin website should appear when navigating to http://localhost/admin/ on the raspberry pi.

**Actual behaviour:**

403 - Forbidden

**Steps to reproduce:**

Install a brand new Raspian stretch by copying an image to a SD card, install pihole via curl -sSL https://install.pi-hole.net | bash

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

va30f835h9

**Troubleshooting undertaken, and/or other relevant information:**

Pretty much everything found in issue #2129  but unlike there I can't even access a simple html file in /var/www/html/

 raspberrypi> curl -I http://localhost/index.html
HTTP/1.1 403 Forbidden
Content-Type: text/html
Content-Length: 345
Date: Thu, 31 May 2018 14:06:23 GMT
Server: lighttpd/1.4.45

I had the whole thing running about a week ago but then decided to experiment with FTLDNS. That broke everything and now even a complete wipe of the OS doesn't install a working pihole.

**Comment by Mcat12** [comment]
All of your config files have very restrictive permissions on them:
```
-rw-r----- 1 root root
```

Run `pihole -r` to repair and then make a new debug token.

**Comment by Hk1020** [comment]
Thanks, I did as you suggested, token:

ek55tyoflf

However, it didn't change anything. Is this maybe a umask problem? Do I have to install everything as root or as pi? Or as pi with sudo?

**Comment by Mcat12** [comment]
The installer automatically sets the right permissions, so somehow they got changed after installation.

I would start with a fresh image and install again.

**Comment by Hk1020** [comment]
Well, I don't quite see how it will change anything as I did exactly this today. The only thing I installed in addition to pihole is tcsh as I can't live without it. This is what I did:

pc> dd if=2018-04-18-raspbian-stretch.img of=/dev/sde bs=4M
pc> touch /p/ssh

Insert the SD card into pi, power on.

pc> ssh pi@pi
raspberrypi> sudo apt-get update
raspberrypi> sudo apt-get install tcsh
raspberrypi> sudo apt-get install most
raspberrypi> chsh  # to /bin/tcsh
raspberrypi> exit
pc> ssh pi@pi
raspberrypi> sudo apt-get upgrade
raspberrypi> curl -sSL https://install.pi-hole.net | bash

Anyway, I'll try again without the tcsh part and if that succeeds I might try the above again.

Thanks for your help.

**Comment by Hk1020** [comment]
Ok, I did the exercise and left out all the tcsh bits. So just

raspberrypi> sudo apt-get update
raspberrypi> sudo apt-get upgrade
raspberrypi> curl -sSL https://install.pi-hole.net | bash

And then the dashboard worked. 

I then did a test:

raspberrypi> umask
0022
raspberrypi> pihole uninstall
raspberrypi> # verified that /var/www/html was gone
raspberrypi> umask 27
raspberrypi> curl -sSL https://install.pi-hole.net | bash

Now the dashboard is broken.

This fixed it:

raspberrypi> pihole uninstall
raspberrypi> umask 22
raspberrypi> curl -sSL https://install.pi-hole.net | bash

So there is a problem in the installation scripts. They don't work if umask is not 022.

**Comment by Mcat12** [comment]
Why do you want to set a different umask? We can not account for everything someone might do to their system.

**Comment by Hk1020** [comment]
Why not? I've been using this for over thirty years and it is quite sensible in a multiuser environment. If you need certain requirements for your installation you should make sure they are met. You check for root as well, for instance.

Anyway, thanks for your help and I am glad I found this. Was also the reason why my FTLDNS experiments failed horrendously.

**Comment by Mcat12** [comment]
I agree with @rrobgill, this is out of scope in the same way that installing onto a read-only partition is out of scope, it is less of a bug and more of a feature request to support this configuration.

**Comment by Hk1020** [comment]
Well, you decide. But you should document that you require `umask 022`. I've seen other bug reports which also came down to permission problems.

**Comment by cmoncure** [comment]
I got hit with this after installing Wireguard, which recommends umask 077 during setup.  I think there are many users who will try to set these two programs up to work together, so this may be worth another look.

**Comment by dschaper** [comment]
Do you have links to documentation? Setting the system umask to 077 is going to severely cripple things. You lose group and other access to any file created with that mask. Is Wireguard recommending their files be written with that mask or are they recommending the system be set to that mask permanently?
