### ISSUE TITLE
IPv6 requests don't seem to get blocked.

### ISSUE THREAD

**Issue by hoshsadiq** [pi-hole/pi-hole#2209]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

IPv6 dns requests to be blocked 

**Actual behaviour:**

It seems that all ipv4 requests continually get blocked, but for some reason the same DNS queries for IPv6 do not get blocked. I have many of the below requests (in that, an IPv6 request is made right after IPv4 request), and every single time the IPv6 is forwarded and the IPv4 request is not.

![image](https://user-images.githubusercontent.com/600045/40877563-e47c4d04-667a-11e8-86f1-fd0f1c93cd21.png)

**Steps to reproduce:**

It's just an ongoing issue so not sure how to reproduce. Happy to help with any steps provided

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

zzx193hwh9

**Troubleshooting undertaken, and/or other relevant information:**

I've tried clicking blacklist on the IPv6 entry, but to no avail.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652/18
