### ISSUE TITLE
Chrono LCD Query Stats Stop Pulling Or Recording When It Resets For the New Day

### ISSUE THREAD

**Issue by gh0stshell** [pi-hole/pi-hole#221]
My stats as I just checked when I got home are:

Query: 1
Ads Blocked: 18 (1800%)

After browsing for 15min to sites I know have ads and ones with tons of ads it shows

Query: 1
Ads Blocked: 42 (4200%)

There is still something going on with permissions or the chrono script. It was fine yesterday, this happened once the script reset for the new day.

My laptop is going through the pi-hole so I know my traffic is not going someplace else.

**Comment by jacobsalmela** [comment]
@PromoFaux might be able to offer some insight.  He did a lot of work with that script recently,

**Comment by gh0stshell** [comment]
Since I was dealing with the screen timeout when I first made the pi-hole I am not sure if the problem existed then. Currently after letting it run overnight the query number does not update, but the ad blocked number and % does update. I am pretty sure if I reboot the numbers will start showing correctly, but I will wait for his reply.

**Comment by PromoFaux** [comment]
I:ll take a look tomorrow!

**Comment by gh0stshell** [comment]
I can confirm that the LCD is incorrect while when I login to the terminal since the same screen as the LCD comes up first those numbers are correct, so its LCD related. I am going to try something. I will keep you all posted.

**Comment by gh0stshell** [comment]
SSH
 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        192.168.1.109

0.06, 0.07, 0.05
-------------------------------
Blocking:      68396
Queries:       1922
Pi-holed:      47 (2.44%)

LCD
 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        192.168.1.109

0.06, 0.07, 0.05
-------------------------------
Blocking:      68396
Queries:       1
Pi-holed:      47 (4700%)

**Comment by gh0stshell** [comment]
ACSII is correct, just does not copy and paste well

**Comment by dschaper** [comment]
I wonder if the LCD is just truncating the amount. If you get into the 2000's for queries, can you check and see if the LCD displays 1 or 2?

**Comment by gh0stshell** [comment]
I just rebooted and now the LCD is showing what the terminal shows:

 ___ _     _        _
| _ (_)___| |_  ___| |___
|  _/ |___| ' \/ _ \ / -_)
|_| |_|   |_||_\___/_\___|

        192.168.1.109

average: 0.47, 0.21, 0.08
-------------------------------
Blocking:      68396
Queries:       2029
Pi-holed:      58 (2.85%)

I made set the clock so it will think its a new day in about 9min. We shall see what happens. I have 2 things I want to try

**Comment by gh0stshell** [comment]
While the LCD was stuck, the ads blocked would tick up, but the query number always stayed at 1 causing the % of traffic number to be extremely off

**Comment by dschaper** [comment]
Okay, I think this may be for @PromoFaux to help out. But I'll see what I can do to help troubleshoot where I can.

**Comment by gh0stshell** [comment]
a new day for the pi has started, lets see what happens, have the terminal open to compare numbers

**Comment by gh0stshell** [comment]
lookin good, lemme continue to test, I am changing the time back to my current time and letting it run overnight to be sure

**Comment by gh0stshell** [comment]
I have a new LCD to place with tonight, just came in today

**Comment by PromoFaux** [comment]
Sorry Been a bit hectic at work this morning, so not had change to look at this right away!

>Blocking: 68396
Queries: 1
Pi-holed: 47 (4700%)

I'm unable to replicate as I don't have an LCD (again, really must buy one)

But there is certainly something fishy going on. from the looks of your output. That said, both outputs SHOULD be the same, as they're performing the same calculations. 

Could you leave a terminal window running `chronometer.sh` and the LCD running `chronometer.sh` concurrently and see if it happens on both, or one, or neither?

**Comment by jacobsalmela** [comment]
I'll check mine again as I still have it set up from the last issue.

**Comment by gh0stshell** [comment]
@PromoFaux, I dont think its your script

**Comment by PromoFaux** [comment]
I'm still not entirely sure. 

The percentage is worked out at the same time as the total number of queries and the number of queries blocked (queries blocked / total queries * 100), and before it's passed to the output. That is why it's strange to me. More testing required I think!

**Comment by gh0stshell** [comment]
Give me till tomorrow and I think I may have an answer/solution. I just setup another Pi so I now have a control group and a test group. I will need to let it run over night to be sure

**Comment by dschaper** [comment]
Okay, let us know what you can come up with...

**Comment by jacobsalmela** [comment]
This is a weird bug.

After the `piholeLogFlush.sh` runs, a runtime error appears on the LCD screen.  I only saw it for a moment so I couldn't read the entire message.

After the message disappears, it appears that the stats on the LCD (`chronometer`) are fine
![2016-01-23 17 59 53](https://cloud.githubusercontent.com/assets/3843505/12533683/c8075e44-c1fd-11e5-8bd8-0683d1eef4e5.jpg)

but then the queries get stuck and the percentage is way off.
![2016-01-23 18 11 47](https://cloud.githubusercontent.com/assets/3843505/12533685/d5c72cee-c1fd-11e5-9da5-523c25e593a2.jpg)

There is nothing wrong with the log file
```
pi@raspberrypi ~ $ awk '/\/etc\/pihole\/gravity.list/' /var/log/pihole.log |wc -l
49
```
and the Web dashboard shows the correct stats.
<img width="853" alt="screen shot 2016-01-23 at 6 13 00 pm" src="https://cloud.githubusercontent.com/assets/3843505/12533692/1ee8f830-c1fe-11e5-97df-be3c231d4673.png">

So the bug happens following the log flush and only with `chronometer`.

**Comment by gh0stshell** [comment]
Though it may have been how the script was added to run when logging in, nope
Had a theory that the code @jacobsalmela wrote before the revamp, that works correctly
Thought it was an LCD issue, nope
Thought it was a log issue, nope
Thought it had to do with the rollover of the date/time to a new day, nope
Can it be reproduced without an LCD, yes, make sure SSH timeout is off and just let it run
Any errors to go one, yes, one Pi running in debug shows the error runtime error addr=0 devide by 0

Sorry I forgot to post the above I wrote out 6 hours ago, on one of my units I have the runtime error I just need to post it

**Comment by gh0stshell** [comment]
Rutime error (func=main), adr=11: Divide by zero

**Comment by gh0stshell** [comment]
holy balls i think i may have got it, tired trying it once more then crashing, i think is they key word

**Comment by gh0stshell** [comment]
yup after running flush it still is recording queries and is not sticking,

**Comment by gh0stshell** [comment]
I did also figure out how to get the error to stay on the screen which I posted above

**Comment by gh0stshell** [comment]
my other pi has a slightly different error

**Comment by PromoFaux** [comment]
`piholeLogFlush.sh` just truncates `pihole.log`

Could it be an access error? Is it trying to truncate at the same time as `chronometer.sh` is accessing it?

**Comment by gh0stshell** [comment]
The issue was that after the log is cleared the script cannot read from it, it apprently after researching the issue late last night is a common issue, I change the clearing code in the flush script, I do not know if it works or it was the fact that I ran it a few times in a row, letting it run on its own tonight will confirm it, also I cleaned up this line in the script:

(cat "$piLog" | grep "$today" | awk '/query/ {print $6}' | wc -l)

to

(cat "$piLog" | awk '/query/ {print $6}' | wc -l)

the grep $today was not needed, if you run the line above it shows the same results as the original line, this may have helped as well, i am not sure

**Comment by gh0stshell** [comment]
On each of my pi's I have a new clearing code on each, once it runs tonight I will know if both work on their own or one or the other works

**Comment by PromoFaux** [comment]
What did you change in `piholeLogFlush.sh` ?

>I cleaned up this line in the script:

(cat "$piLog" | grep "$today" | awk '/query/ {print $6}' | wc -l)

to

(cat "$piLog" | awk '/query/ {print $6}' | wc -l)

is that in `chronometer.sh`?

**Comment by gh0stshell** [comment]
yes the cat is in chrono, i tried changing the clearing of the log code, but it did not work, I have other I have found on the net and will be trying those

**Comment by gh0stshell** [comment]
@PromoFaux , i know you want an LCD and I have one I may never use that is a adafruit 2.8, lemme see if I will need it and if not I will donate it to you

**Comment by gh0stshell** [comment]
@jacobsalmela , @PromoFaux where is the code that runs the flush script at 00:00 of each day?

**Comment by dschaper** [comment]
It's currently called via a cron job. https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.cron
The script is at https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeLogFlush.sh

**Comment by gh0stshell** [comment]
Thanks @dschaper!

**Comment by gh0stshell** [comment]
@dschaper did you want the LCD or was it @PromoFaux? I may have a NIB extra

**Comment by dschaper** [comment]
I wouldn't mind having the LCD, but @PromoFaux was offered it first, so it's his to decline. (I'm not sure where you're located so shipping may be an issue? I'm in the US, Promo is in the UK, that's why he's not answering right now, he's asleep...)

**Comment by dschaper** [comment]
And just as a question, you're running Jessie correct? I'm looking at moving that cronjob over to a systemD monotonic timer...

**Comment by gh0stshell** [comment]
@dschaper how do I view that crontab that was installed, I am having issues locating it

**Comment by gh0stshell** [comment]
yup

**Comment by dschaper** [comment]
It's dropped in the `cron.d` directory as part of the install process. https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L428

**Comment by gh0stshell** [comment]
Thanks, I am a little burnt today

**Comment by dschaper** [comment]
Lol, not a problem...

**Comment by PromoFaux** [comment]
@gh0stshell Thanks for the kind offer, but it's OK! The only reason I haven't got one yet is lazyness! I can pick them up pretty cheap, I just haven't got around to it :)

**Comment by gh0stshell** [comment]
I just got home and checked both of the Pi's, i tried new code on each, 1 is off, the other however is actually showing the correct number, BUT i did 2 fixes on the pi #2 so I am not sure which worked. I am going to take one change away and see if when the flush happens tonight it still is working correctly. If not I will let the other change give it a go.

**Comment by gh0stshell** [comment]
I would love to submit a code change, I have only done one once before a while ago for another project, did anyone want to test the new flush code before I submit the change to your project?

I also have a question about the web interface.

**Comment by dschaper** [comment]
If you do a Pull Request with your code changes, and select our Development branch as the base branch then I can bring your code changes in to a testing branch for evaluation. Have you forked our code repository?

I can try to answer your questions about the web interface, but I don't personally do much with that portion of the project...

**Comment by Mcat12** [comment]
I can try to answer any questions about the web interface!

**Comment by PromoFaux** [comment]
@gh0stshell , Can you open a new issue thread on the web interface repo with your question, please? To keep it tidy.

**Comment by gh0stshell** [comment]
No problemo, that is why I asked before posting

**Comment by gh0stshell** [comment]
@Mcat12 opening a new ticket, it is a very simple question

**Comment by gh0stshell** [comment]
Please marked this solved and it can be closed, today the LCD is still working correctly after letting the new flush code run by itself overnight twice

**Comment by gh0stshell** [comment]
@dschaper this will be a stupid question, I use github on this computer through the web only, the only way I saw was to enter a pull request for the master, can this be done via the web or do I need to download the client?

**Comment by gh0stshell** [comment]
I figured it out, new code submitted

**Comment by dschaper** [comment]
Okey, closing this item. Will catch up on the new one.

**Comment by PromoFaux** [comment]
Reopening as redetected here:

https://www.reddit.com/r/pihole/comments/50naz8/queries_and_chronometer_still_wrong/d76t1ax?context=3

Will open a PR for confirmed fix
