### ISSUE TITLE
Autonomous Install 

### ISSUE THREAD

**Issue by unclehowell** [pi-hole/pi-hole#2211]
Can you point me in the direction of an autonomous installer for pi-hole? 
I would like to set defaults and just run one script, as oppose to going through the menu and specifying the ip and logging and so on. Really tedious and not necessary for what I'm doing. 
I'm really looking for the correct method of doing this so that a Pi-Hole update doesn't mess it all up because the approach taken was not in keeping with Pi-Holes best practices.

**Comment by Mcat12** [comment]
The code is located here: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh
An `--unattended` install is what you are looking for, and that assumes that `setupVars.conf` is already installed under `/etc/pihole`.

However, if you want to talk more you should fill out the issue template which should have appeared when you opened the issue: https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by unclehowell** [comment]
This is helpful enough, thank you so much - excellent solution guys
