### ISSUE TITLE
pi-hole isn't answering to dns requests

### ISSUE THREAD

**Issue by piekay** [pi-hole/pi-hole#2213]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

        5

---
**Expected behaviour:**

         Page loading-speed not depending on used adlist

**Actual behaviour:**

         Slow loading times when using hostfiles (with other ip's than the pihole ip)

**Steps to reproduce:**

         Using adlists with forced IPs (For example: https://adaway.org/hosts.txt)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

         ci60jwukf1

**Troubleshooting undertaken, and/or other relevant information:**

         Editing the source code to ignore the IP-Adresses in the adlists

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Using adlists with or without IP addresses included has no relevance, as gravity only takes into consideration the domains (the IP addresses are discarded).

**Comment by piekay** [comment]
It is relevant:
     Reddit loading time without host-files: 0.5 - 1sec 
     With host-files: 3-5sec

**Comment by Mcat12** [comment]
Are you using the hosts files via the Pi-hole adlists, or are you adding them in a different way?

**Comment by piekay** [comment]
Pi-hole adlists

**Comment by piekay** [comment]
There are no changes but without the page is loading 2-3 times faster. That's strange.

**Comment by Mcat12** [comment]
If there are no changes then logically there can be no performance change. Are you sure there isn't something else happening? Maybe the block page is getting triggered, and it's slower when parsing lists with IP addresses?

**Comment by piekay** [comment]
Nope there are only the performance changes and I know, that it's really strange...

**Comment by Mcat12** [comment]
Can you check if the block page is slower? Visit a blocked domain to test.

**Comment by piekay** [comment]
with and without (nmap  --reason):
22/tcp open  ssh     syn-ack ttl 64
53/tcp open  domain  syn-ack ttl 64
80/tcp open  http    syn-ack ttl 64

**Comment by Mcat12** [comment]
Why are you using nmap?

**Comment by piekay** [comment]
because the blocked page was showing very slow and I wanted to know why it isn't working.

**Comment by Mcat12** [comment]
nmap won't tell you why the block page is slow.

**Comment by piekay** [comment]
It is telling (opened ports)

**Comment by Mcat12** [comment]
Those ports will always remain open. Pi-hole does not dynamically close ports. The block page is only triggered over HTTP, when you go to a blocked domain.

**Comment by piekay** [comment]
Yes but the block page isn't triggered (tested) my browser sends me this error: DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Mcat12** [comment]
It should be. Go to a blocked domain that is in `gravity.list`. You can see that it returns the Pi-hole's IP by using `dig`

**Comment by piekay** [comment]
dig 00.devoid.us

; <<>> DiG 9.13.0 <<>> 00.devoid.us
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by piekay** [comment]
I tjink these domains aren't on the blocklist at the moment...

**Comment by piekay** [comment]
On my raspberrypi dig output is: 
; <<>> DiG 9.10.3-P4-Raspbian <<>> 00.devoid.us
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5639
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;00.devoid.us.			IN	A

;; ANSWER SECTION:
00.devoid.us.		2	IN	A	192.168.178.20

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jun 03 19:09:31 BST 2018
;; MSG SIZE  rcvd: 57

**Comment by Mcat12** [comment]
> `;; connection timed out; no servers could be reached`

You have an issue connecting to the Pi-hole. Check that it is using the correct IP address, and see if it can ping the device.

**Comment by piekay** [comment]
Ping 00.devoid.us: not working
Ping 192.168.178.20 (Raspberry Pi): working

**Comment by piekay** [comment]
> My iptables:
# Generated by iptables-save v1.6.0 on Thu May 31 22:08:59 2018
*filter
:INPUT ACCEPT [58:13316]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [55:12675]
-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i wlan0 -o eth0 -j ACCEPT
COMMIT
# Completed on Thu May 31 22:08:59 2018
# Generated by iptables-save v1.6.0 on Thu May 31 22:08:59 2018
*nat
:PREROUTING ACCEPT [133:9553]
:INPUT ACCEPT [131:8401]
:OUTPUT ACCEPT [241:73418]
:POSTROUTING ACCEPT [138:9191]
-A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
# Completed on Thu May 31 22:08:59 2018

**Comment by Mcat12** [comment]
Sounds like your device is not using Pi-hole for DNS

**Comment by piekay** [comment]
It is using pihole (with dnssec2.0) the domains are blocked but pihole isn't answering.

**Comment by Mcat12** [comment]
Do you see the queries show up in the log?

**Comment by piekay** [comment]
Yes:
Jun  3 19:31:04 dnsmasq[482]: 2295 192.168.178.48/50028 query[A] pi.hole from 192.168.178.48
Jun  3 19:31:04 dnsmasq[482]: 2295 192.168.178.48/50028 /etc/pihole/local.list pi.hole is 192.168.178.20
Jun  3 19:31:04 dnsmasq[482]: 2296 192.168.178.48/50028 query[AAAA] pi.hole from 192.168.178.48
Jun  3 19:31:04 dnsmasq[482]: 2296 192.168.178.48/50028 /etc/pihole/local.list pi.hole is fd00::ba27:ebff:feee:4e4d

**Comment by Mcat12** [comment]
Your IPTables rules don't seem to cover port 53 (DNS). DNS needs port 53 and that needs to be open / forwarded from and to the clients.

**Comment by piekay** [comment]
thanks it is working now.
