### ISSUE TITLE
AppleTV video ads not being blocked

### ISSUE THREAD

**Issue by crazyaces** [pi-hole/pi-hole#222]
Just tested out the PiHole with the new AppleTV. Network settings in the AppleTV allow you to set a custom DNS for your network interface, however after pointing to PiHole no ads are blocked. Just a Heads up
##

**Comment by dschaper** [comment]
Thanks, I think this may be in the same category as the Hulu issue, video blocking is something new for the project.

**Comment by jacobsalmela** [comment]
Yes, it is.  I have some detailed information on this and have some good leads on how to *skip* the ads, not just mute them.  It's a nice feature to be added, but also one of the most difficult.  I'll dig up the information I have at some point and see if anyone has more clues or ideas.

**Comment by jacobsalmela** [comment]
Video ads are still a moving target, and nothing has happened on this for a year.  Closing.
