### ISSUE TITLE
Pi-hole install issues on Debian 9 x64

### ISSUE THREAD

**Issue by digilink** [pi-hole/pi-hole#2222]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5
---
**Expected behaviour:**
Pi-hole installation to succeed. I am running on a newly installed Debian 9 x64 virtual machine with 1 CPU, 1GB of RAM, 20GB of disk space. I used the easy install script from: 

curl -sSL https://install.pi-hole.net | bash

**Actual behaviour:**
Installation "hangs" at "Downloading and Installing FTL..." and sends CPU utilization to 100% and I have to reboot the instance as a result. SSH will cease working. 

![image](https://user-images.githubusercontent.com/16581598/40996961-337d08a0-68d1-11e8-8682-6e1111ad52eb.png)

**Steps to reproduce:**
Install new Debian 9 x64 instance with specs as listed above and execute easy install script. 

**Debug token provided by [uploading `pihole -d` log]
Does not appear to be installed: 

root@pihole01:/# pihole -d
bash: pihole: command not found

**Troubleshooting undertaken, and/or other relevant information:**
I have tried setting a static address prior to installation as well as re-installed the OS several times, I am able to duplicate this no matter what I do it seems.

**Comment by dschaper** [comment]
Do you have any special permissions set on your `/tmp` directory or is it mounted to a ram partition? (You can check with `sudo mount` and `sudo ls -lah /tmp`

**Comment by digilink** [comment]
Here's what I show, I do not believe this is mounted to a ram partition or if there are permissions issues, but I have included the full output for brevity: 

root@pihole01:/etc/network# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=499144k,nr_inodes=124786,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=102048k,mode=755)
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=9000)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=102048k,mode=700)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=102048k,mode=700,uid=1000,gid=1000)


root@pihole01:/etc/network# ls -lah /tmp
total 32K
drwxrwxrwt  8 root root 4.0K Jun  5 15:23 .
drwxr-xr-x 22 root root 4.0K Jun  5 14:24 ..
drwxrwxrwt  2 root root 4.0K Jun  5 15:22 .font-unix
drwxrwxrwt  2 root root 4.0K Jun  5 15:22 .ICE-unix
drwx------  3 root root 4.0K Jun  5 15:22 systemd-private-9a0e547e1b044daeb550afe561ae9dff-systemd-timesyncd.service-4SeZ26
drwxrwxrwt  2 root root 4.0K Jun  5 15:22 .Test-unix
drwxrwxrwt  2 root root 4.0K Jun  5 15:22 .X11-unix
drwxrwxrwt  2 root root 4.0K Jun  5 15:22 .XIM-unix

**Comment by rrobgill** [comment]
I have tested this in Virtualbox on a clean Debian 9.4 install (from 9.4.0 Stretch amd64 DVD 20180310) with the same parameters (1 cpu, 1Gb ram, 20 Gib drive, and the install completes as normal.

If you installed from downloaded media, the image may be corrupt - debian have [details](https://www.debian.org/CD/verify) on verifying the integrity of downloaded images.

![2018-06-06_09 14 15](https://user-images.githubusercontent.com/35944068/41007649-2761d142-696a-11e8-8cee-89a3fa8577b6.jpg)

**Comment by digilink** [comment]
I downloaded a new ISO this morning, Debian Stretch 9.4 netinstall. I also verified the sums and the image I downloaded is not corrupted: 

[root@esxisrv01:/vmfs/volumes/bb24857f-9946cfd3/linux] md5sum debian-9.4.0-amd64-netinst.iso
73bd8aaaeb843745ec939f6ae3906e48  debian-9.4.0-amd64-netinst.iso

https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/MD5SUMS

> One question, when you said x64, can you please confirm that I've understood you correctly, and you meant you're running Debian amd64 (not just running on amd64/x86_64 hardware?)

Yes, that is correct. My hypervisor is vmware esxi 6.5. Here is what my vm settings look like: 

![image](https://user-images.githubusercontent.com/16581598/41035966-62b8a7e2-695c-11e8-9628-5e0646118862.png)

![image](https://user-images.githubusercontent.com/16581598/41036016-8c4224c6-695c-11e8-9cca-e62d9c1b9d9d.png)

I don't think this is something specific to my environment, but could be. It appears as something is hanging this install up, specifically when it gets to the portion of "[i] Downloading and Installing FTL.../tmp/tmp.5efOGTNBjE /etc/.pihole" ... the machine spikes to 100% CPU utilization and I lose all communication with it forcing me to reboot it. 

As a test, I installed a CentOS 7 VM with the same settings and had no issue with getting pi-hole installed with the same method. Debian is my preferred platform however, so any troubleshooting assistance or data I can collect to figure this out would be helpful.

**Comment by rrobgill** [comment]
I'm afraid I'm not overly familiar with vmware. Because it's working under the same version of debian in virtualbox, and also on centos in vmware, there is clearly some interaction between vmware and debian at play here.

Could it be related to this issue ? [https://www.linkedin.com/pulse/linux-virtual-machine-crash-vmxnet3-nic-vmware-esxi-65-han-yong-lim](https://www.linkedin.com/pulse/linux-virtual-machine-crash-vmxnet3-nic-vmware-esxi-65-han-yong-lim)

The symptoms sound somewhat similar, and in terms of installed software base, Debian 9.4 and Ubuntu 16.04 are comparable.

**Comment by digilink** [comment]
Thanks @rrobgill, this does appear to be isolated to my environment, I just tested and installed successfully in Virtual Box, so there could indeed be something up with the VMXNET3 driver as mentioned in the link provided. 

I will close this and keep investigating, but the issue is specific to my hypervisor and not the pi-hole code.
