### ISSUE TITLE
Fails to install when suing SSH and WIFI on Raspberry Pi

### ISSUE THREAD

**Issue by Slyke** [pi-hole/pi-hole#2226]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Should be able to install over SSH and wifi

**Actual behaviour:**

`Connection reset by 192.168.2.151 port 22

**Steps to reproduce:**

Install a fresh OS. Then follow this guide: https://docs.pi-hole.net/guides/vpn/installation/
Configure Wifi (either with raspi-config, or wpa file).
SSH into pi
Install OpenVPN.
Install PiHole
After the step where it says `FYI: IP Conflict` and you press OK, it will do some stuff, then it will say `Connection reset by 192.168.2.151 port 22`. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`This doesn't work because pihole command isn't found (not yet fully installed)`
*Edit:* on my second attempt I ran this after install finished, and it did upload: 1ouyxw5dhn

**Troubleshooting undertaken, and/or other relevant information:**

Trying to reconnect with SSH fails. Pinging no longer works. If the Pi is restarted, it can no longer get an IP address on wlan0. I tried doing `dhclient -r wlan0`. The Pi does connect to the wifi network, as ifconfig shows that it is receiving and transmitting packets (rx and tx numbers), but it doesn't get an ip address. If I use screen, and continue the installation from the pi once SSH fails, it seems to install correctly. After the installation has finished, the pi can no longer connect to the internet, nor ping the gateway. If an ethernet cable is plugged in after the installation process is finished, eth0 gets an ipaddress, but it is not pingable, internet doesn't work, nor is the gateway pingable from the pi.

**Comment by Mcat12** [comment]
Was it using the correct IP address, or did it try changing the IP address to a different one than the one you were connected on?

**Comment by Slyke** [comment]
It's using the correct address: 192.168.2.151. I've actually tried this twice now. The IP address is configured in my DHCP server, so is always the same. I also tried plugging an ethernet cable in after the install process, and while eth0 gets an ip address, it is not pingable, nor does it have internet connectivity (I updated my original post with this new info too).

**Comment by Mcat12** [comment]
Which interface did you choose? You might have chosen the VPN interface and set it to the local DHCP IP address.

**Comment by Slyke** [comment]
You might be correct. I was just following the instructions on the webpage. I chose 192.168.2.151 for the ip address, and tun0 for the interface. I checked the routes table and it looks like this: https://i.imgur.com/zAaIeyX.jpg

**Comment by Mcat12** [comment]
Did it come up with the 192.168.2.151 address automatically, or did you enter that in manually? Try manually entering the address you have on the tun0 interface (should start with `10.8.0`).

**Comment by Slyke** [comment]
It came up with that one automatically. I'll try to reinstall with `10.8.0.1` and report back here.

**Comment by Slyke** [comment]
Okay, when I set the IP address manually when installing PiHole, and restarted it, everything started working. I ran the log uploader on the working version for the devs if they want to compare log results: `607po69tot`

A weird thing is that if I ping the gateway from the command line it pings fine:
```
pi@pidns:~ $ ping 192.168.2.1
PING 192.168.2.1 (192.168.2.1) 56(84) bytes of data.
64 bytes from 192.168.2.1: icmp_seq=1 ttl=64 time=2.11 ms
64 bytes from 192.168.2.1: icmp_seq=2 ttl=64 time=4.48 ms
64 bytes from 192.168.2.1: icmp_seq=3 ttl=64 time=5.34 ms
```

But in the pihole log it says:
```
[i] Default IPv4 gateway: 192.168.2.1
   * Pinging 192.168.2.1...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

The instructions should probably mention not to choose `tun0`, or to manually enter in the LAN ip address if you are installing over wifi and ssh. `You can accept all the defaults, or configure Pi-hole to your liking.`

**Comment by Mcat12** [comment]
Yep, it tries to use the interface you configured during install, but automatically determines the gateway your device is using:
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeDebug.sh#L595

I don't think this is a bug, but it is an unforeseen situation.
