### ISSUE TITLE
basic-install.sh

### ISSUE THREAD

**Issue by nexusofdoom** [pi-hole/pi-hole#2233]
my network setup.

unbound running on 10.0.4.2  more then one IP's on one interface.

I want pi-hole to run everything on 10.0.4.20
how do I do that?

when I install it ask and shows 10.0.4.20 but when it try's to rub dnsmasq it try's to run on 10.0.4.2 
same with lighttpy

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by nexusofdoom** [comment]
dnsmasq I needed to edit it to listen-address=127.0.0.1 then it worked "note I moved my unbound to another ip on the same interface.
for FTL I needed to make a dir in /var/run/ then also make it owned by pihole.

I also needed to un-check "Never forward reverse lookups for private IP ranges"

**Comment by Mcat12** [comment]
In the settings page under "DNS -> Interface listening behavior", choose the last option.

**Comment by nexusofdoom** [comment]
more current lists ?
and will this list work ? or do I need to remove the 127.0.0.1 ?
https://pgl.yoyo.org/as/serverlist.php?showintro=0;hostformat=hosts

**Comment by nexusofdoom** [comment]
or this one ?
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

**Comment by nexusofdoom** [comment]
it looks like it working some what in http it shows this 
![image](https://user-images.githubusercontent.com/16519553/41373430-f97b5ab2-6f15-11e8-90cf-4cdf6c807916.png)

**Comment by nexusofdoom** [comment]
but if i try in https it goes through 
![image](https://user-images.githubusercontent.com/16519553/41373474-1634583e-6f16-11e8-9995-430b1ee1e791.png)

**Comment by nexusofdoom** [comment]
the issue with https was sniproxy needed to be updated.

**Comment by nexusofdoom** [comment]
so only notes is when installing it would be nice to tell where lighttpd to "server.bind" to.
along with fixing /var/www/html/pihole/index.php ref to 127.0.0.1 to point to the server.bind address.
same with dnsmasq


thanks every one.
