### ISSUE TITLE
Frequent errors: DNS_PROBE_ STARTED FINISHED_BAD_CONFIG FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#2235]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1}`

---
**Expected behaviour:**

`Websites loading`

**Actual behaviour:**

`Many many times per hour, I am getting DNS_PROBE_STARTED, DNS_PROBE_FINISHED_BAD_CONFIG, DNS_PROBE_FINISHED_NXDOMAIN.`

**Steps to reproduce:**

`It seems to be random when a page will work versus not. Refreshing the page eventually fixes it after a few refreshes`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wpvbut24ct`
`xlj36imico`

**Troubleshooting undertaken, and/or other relevant information:**

`Restarted Pi, turned off DNSSEC, changed DNS to be upstream from router instead of direct`

So some notes:
I've been using Pihole for a few years now, so decently advanced with it. I'm on the latest FTL branch. For mods, I am using latest DNSCrypt-proxy 2 and also that list of IPtable rules for speeding up pihole on HTTPS. Sometimes browsing is working, and sometimes I am getting errors in chrome. After many refreshes, the pages eventually work

I have tried turning DNSSEC off/on in Pihole admin (my dnscrypt is already using DNSSEC). Even when DNSSEC is off in admin page, dnssec still works for me because of dnscrypt. Could it be because I am using DNSSEC both on pihole and also dnscrypt proxy, because Ive tried to turn it off on the admin page and it changed nothing. Also, should I have it enabled there if also using dnscrypt proxy?

I've also changed router settings so Pihole is only DNS server on WAN.... LAN uses default DNS server (router itself)

If you guys are able to assist, I will be making a healthy donation to the team!

**Comment by p1r473** [comment]
I'm noticing my pihole.log file is 220MB big, and has a lot of the following. Is this normal?


Jun 14 18:40:27 dnsmasq[14013]: 625550 192.168.1.1/50018 query[PTR] 4.1.168.192.in-addr.arpa from 192.168.1.1
Jun 14 18:40:27 dnsmasq[14013]: 625550 192.168.1.1/50018 forwarded 4.1.168.192.in-addr.arpa to 192.168.1.1
Jun 14 18:40:27 dnsmasq[14013]: 625551 192.168.1.1/50018 query[PTR] 4.1.168.192.in-addr.arpa from 192.168.1.1
Jun 14 18:40:27 dnsmasq[14013]: 625550 192.168.1.1/50018 query[PTR] 4.1.168.192.in-addr.arpa from 192.168.1.1
Jun 14 18:40:27 dnsmasq[14013]: 625550 192.168.1.1/50018 forwarded 4.1.168.192.in-addr.arpa to 192.168.1.1
Jun 14 18:40:27 dnsmasq[14013]: 625551 192.168.1.1/50018 query[PTR] 4.1.168.192.in-addr.arpa from 192.168.1.1

**Comment by Mcat12** [comment]
You might have a loop between the router and Pi-hole.

**Comment by p1r473** [comment]
I thought maybe that was the work of one of these

Never forward non-FQDNs
Never forward reverse lookups for private IP ranges
Conditional Forwarding



Right now, I simply have it set it up like this:

![image](https://user-images.githubusercontent.com/9235633/41444852-b0aef16e-7013-11e8-8a7e-089380293d3b.png)

I currently have not set Pihole as the router's dhcp server's dns.... only as the router's lan dns

**Comment by Mcat12** [comment]
Conditional forwarding is likely the cause.

**Comment by p1r473** [comment]
I'll disable it and report back....
Thanks

**Comment by p1r473** [comment]
BTW, getting a lot of this in the log:
validation result is INSECURE

Is this because Im using DNSCrypt with DNSSEC, and also enabled DNSSEC enabled in pihole?
Do I need it enabled in both places, or off in pihole and on in dnscrypt-proxy?

**Comment by Mcat12** [comment]
That is expected. Not all domains use DNSSEC.

**Comment by p1r473** [comment]
Still getting the occasional errors this issue was originally about

Please see the following lines showingh "no DS"












Jun 14 21:32:37 dnsmasq[3184]: * 192.168.1.1/19210 dnssec-query[DS] getpiper.com to 127.0.0.1
Jun 14 21:32:37 dnsmasq[3184]: * 192.168.1.1/19210 reply getpiper.com is no DS
Jun 14 21:32:37 dnsmasq[3184]: 4064 192.168.1.1/19210 validation result is INSECURE
Jun 14 21:32:37 dnsmasq[3184]: 4064 192.168.1.1/19210 reply api.getpiper.com is 34.202.98.1
Jun 14 21:32:37 dnsmasq[3184]: 4064 192.168.1.1/19210 reply api.getpiper.com is 34.198.71.246
Jun 14 21:32:37 dnsmasq[3184]: 4064 192.168.1.1/19210 reply api.getpiper.com is 52.204.84.236
Jun 14 21:32:37 dnsmasq[3184]: 4064 192.168.1.1/19210 reply api.getpiper.com is 52.7.238.133
Jun 14 21:32:39 dnsmasq[3184]: 4065 192.168.1.1/46925 query[A] api.huq.io from 192.168.1.1
Jun 14 21:32:39 dnsmasq[3184]: 4065 192.168.1.1/46925 forwarded api.huq.io to 127.0.0.1
Jun 14 21:32:39 dnsmasq[3184]: 4065 192.168.1.1/46925 forwarded api.huq.io to 127.0.0.1
Jun 14 21:32:39 dnsmasq[3184]: * 192.168.1.1/46925 dnssec-query[DS] huq.io to 127.0.0.1
Jun 14 21:32:39 dnsmasq[3184]: * 192.168.1.1/46925 dnssec-query[DNSKEY] io to 127.0.0.1
Jun 14 21:32:39 dnsmasq[3184]: 4065 192.168.1.1/46925 reply api.huq.io is 34.244.254.166
Jun 14 21:32:40 dnsmasq[4184]: 4066 192.168.1.1/50716 query[A] api.huq.io from 192.168.1.1
Jun 14 21:32:40 dnsmasq[4184]: 4066 192.168.1.1/50716 forwarded api.huq.io to 127.0.0.1
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 dnssec-query[DS] huq.io to 127.0.0.1
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 dnssec-query[DNSKEY] io to 127.0.0.1
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 reply io is DNSKEY keytag 17116, algo 8
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 reply io is DNSKEY keytag 63407, algo 8
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 reply io is DNSKEY keytag 64744, algo 8
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 reply io is DNSKEY keytag 57355, algo 8
Jun 14 21:32:40 dnsmasq[4184]: * 192.168.1.1/50716 reply huq.io is no DS
Jun 14 21:32:40 dnsmasq[4184]: 4066 192.168.1.1/50716 validation result is INSECURE
Jun 14 21:32:40 dnsmasq[4184]: 4066 192.168.1.1/50716 reply api.huq.io is 34.244.254.166
Jun 14 21:32:43 dnsmasq[3184]: 4166 192.168.1.1/56119 query[A] trinity.platform.intuit.com from 192.168.1.1
Jun 14 21:32:43 dnsmasq[3184]: 4166 192.168.1.1/56119 /etc/pihole/gravity.list trinity.platform.intuit.com is 192.168.1.186
Jun 14 21:32:45 dnsmasq[3184]: 4167 192.168.1.1/57011 query[A] trinity.platform.intuit.com from 192.168.1.1
Jun 14 21:32:45 dnsmasq[3184]: 4167 192.168.1.1/57011 /etc/pihole/gravity.list trinity.platform.intuit.com is 192.168.1.186
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 query[A] cira.ca from 192.168.1.1
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 forwarded cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 forwarded cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: * 192.168.1.1/11165 dnssec-query[DS] cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: * 192.168.1.1/11165 reply cira.ca is no DS
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 validation result is INSECURE

**Comment by Mcat12** [comment]
There's some DNSSEC problems with a certain dnsmasq version, and in general DNSSEC can cause issues like this where someone hasn't set up their domain properly for DNSSEC and users can't access the domain any more.

**Comment by Mcat12** [comment]
You don't need to enable DNSSEC in Pi-hole if you already are using it in dnscrypt-proxy.

**Comment by p1r473** [comment]
I'm wondering if my errors are due to DNSCrypt upstream DNS not working...
Looks like it tried to forward it to 2 dnscrypt servers and then in came back as "no ds"... what is no ds?



Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 query[A] cira.ca from 192.168.1.1
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 forwarded cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: 4168 192.168.1.1/11165 forwarded cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: * 192.168.1.1/11165 dnssec-query[DS] cira.ca to 127.0.0.1
Jun 14 21:32:50 dnsmasq[3184]: * 192.168.1.1/11165 reply cira.ca is no DS

**Comment by dschaper** [comment]
DS is a domain signature DNSSEC type, https://www.godaddy.com/help/what-is-a-ds-record-6148
