### ISSUE TITLE
Paypal app can not connect when DNSSEC is enabled and CloudFlare 1.1.1.1 is used for Upstream DNS

### ISSUE THREAD

**Issue by CryptoCurrencyFreak** [pi-hole/pi-hole#2238]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1 {Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Paypal opens and connects after using Fingerprint to unlock Paypal app.

**Actual behaviour:**

After Fingerprint authorization a red banner appears at the top of the app stating that it is unable to connect. 

**Steps to reproduce:**

Install Pi Hole.
Adjust router to point to Pi Hole
Change Pi Hole Upstream DNS to 1.1.1.1 and 1.0.0.1
Enable DNSSEC
Save
Load Paypal app while connect to Wifi.
Authorize with your credentials.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

rn5426isnn

**Troubleshooting undertaken, and/or other relevant information:**

Simply keeping DNSSEC enabled and moving to a different Upstream provider solves the issue. It appears CloudFlare is the offender.

**Comment by dschaper** [comment]
Seems like this may be a problem with the upstream, does it happen with any other provider as the upstream?

**Comment by CryptoCurrencyFreak** [comment]
It may be CloudFlare related upstream but it does not happen if you remove Pi Hole from the equation. 

I have used 1.1.1.1 since its release day with no issues. Adding Pi Hole and DNSSEC results in the issue above.

**Comment by DL6ER** [comment]
DNSSEC in Pi-hole is still still considered experimental as the implementation on `dnsmasq` isn't 100% working as of now!
It will be much improved in `dnsmasq v2.80`, but this has not been officially released.

I assume it works with CF as provider and DNSSEC disabled?

Also, how does https://rootcanary.org/test.html look like for you? I get
![screenshot at 2018-06-17 11-40-53](https://user-images.githubusercontent.com/16748619/41506712-4ef03b2e-7223-11e8-8c08-909d0cda771e.png)

I run Pi-hole and am my own upstream provider (using a `unbound` based recursive resolver as described in our guide) with DNSSEC disabled in Pi-hole (`dnsmasq`) and enabled in `unbound`. Through this, I'm still 100% secured as my upstream (`unbound`) refuses to validate BOGUS domains and hence doesn't even forward BOGUS replies to `dnsmasq` and meanwhile I'm independent from any upstream provider.

**Comment by BlackyP8** [comment]
Hi,

I don't know if it is related or helps, but I had a similar problem with Paypal (though my config is a recursive DNSSEC resolver behind the Pi-hole). Since I've whitelisted t.paypal.com everything is working fine.

**Comment by iamperson347** [comment]
Hello. Just as an FYI, I had a similar issue with .mil domains/sites.

My setup: pihole (dnssec enabled) -> cloudflared daemon for DNS-Over-HTTPS -> Cloudflare. I tried digging against cloudflare directly, and against the port cloudflared is running on, and both came back result OK. However, the result when using dig against my pihole with a .mil site was bogus dnssec. Turning off dnssec on pihole resolved the issue. 

(When turning off dnssec but using a dnssec validating resolver, I believe we are still covered with dnssec... correct? My dnssec tests I have run still come back good despite turning it off on the pihole.)

**Comment by MattPark** [comment]
I've seen the same issue with Cloudflare, DNSSEC, and https://www.usaa.com
It's funny, if you do nslookup directly, it's totally inconsistent.  Fails around 50% of the time

```
C:\Users\matth>nslookup www.usaa.com
Server:  ns
Address:  192.168.1.22

Non-authoritative answer:
*** ns can't find www.usaa.com: Unspecified error

C:\Users\matth>nslookup www.usaa.com
Server:  ns
Address:  192.168.1.22

Non-authoritative answer:
Name:    e6962.b.akamaiedge.net
Address:  104.70.52.113
Aliases:  www.usaa.com
          wsan2.usaa.com.edgekey.net
```

**One item worth noting is that both www.usaa.com and www.paypal.com appear to be CNAMEd to edgekey.net and akamaiedge.net**

```
C:\Users\matth>nslookup www.paypal.com
Server:  ns
Address:  192.168.1.22

Non-authoritative answer:
Name:    e3694.a.akamaiedge.net
Address:  104.70.77.246
Aliases:  www.paypal.com
          geo.paypal.com.akadns.net
          hotspot-www.paypal.com.akadns.net
          wlb.paypal.com.akadns.net
          www.paypal.com.edgekey.net
```


Turning off DNSSEC is a workaround to the problem.

**Comment by dschaper** [comment]
This looks to be an outside issue with CloudFlare DNS. @DL6ER I think there are a few patches/improvements in upstream `dnsmasq` that could be applied when there is a chance.

**Comment by dschaper** [comment]
Is this still an issue?

**Comment by dschaper** [comment]
Closing: Stale
