### ISSUE TITLE
Filtering not performed on canonical names returned by a CNAME record

### ISSUE THREAD

**Issue by ef-thomas** [pi-hole/pi-hole#2242]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi-hole should filter all records, including canonical names returned by a CNAME record.

**Actual behaviour:**

Filtering not performed on canonical names.

Example psuedocode:

# badsite.example.com is blacklisted
A? badsite.example.com   pi-holed

# goodsite.example.com is whitelisted
A? goodsite.example.com IN A 123.456.789.012

# goodsite.example.com returns CNAME of badsite.example.com
A? goodsite.example.com CNAME badsite.example.com
# canonical name then queries A record and passes thru unfiltered
A? badsite.example.com IN A 234.567.890.123

**Steps to reproduce:**

See above

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not necessary

**Comment by ef-thomas** [comment]
Also, the CNAMEs come up when running tailf /var/log/pihole.log but do not show up in the web interface.  In my opinion I think that they should show up and allow to be blacklisted.

**Comment by ef-thomas** [comment]
Any thoughts on this ?  I can see why it is this way, since if you trust an A record you would be trusting the CNAME.  But is there any way to add this capability ?

**Comment by ef-thomas** [comment]
Should this be put under feature request instead.

**Comment by dschaper** [comment]
Sorry, we were having some internal discussion about the workings of `dnsmasq` and how it could be implemented if possible. If you would like to open a Feature Request on https://discourse.pi-hole.net, we can track it there and add our thoughts and comments.

**Comment by dschaper** [comment]
Since this is a Feature Request I'm going to close it out of Issues and you can open the Request using the link in the text below.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
