### ISSUE TITLE
Query adlist has confused the web interface

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#2244]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`Querying an adlist should show what list a given domain is blocked on`

**Actual behaviour:**

`Listed adlists do not contain that domain`

**Steps to reproduce:**

`I added a bunch of new hosts files. When I query a domain, files that clearly do not contain that domain are listed`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`abxs7p21kb`

**Troubleshooting undertaken, and/or other relevant information:**

`Seems to be a problem in the code of the ad list querier`

Examples:
![image](https://user-images.githubusercontent.com/9235633/41637387-9aee22fc-7421-11e8-8748-0c7ddcd1d6bd.png)
Take this example.... The Spotifynulled.txt hosts file is quite short and clearly does not contain this  domain
Exact matches for zpool.ca found in:
   https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotifynulled.txt

**Comment by Mcat12** [comment]
Do you get a similar output when using `pihole -q`?

**Comment by WaLLy3K** [comment]
What you should be seeing when running a search via the Web Interface (and via `pihole -q`) is output similar to the following:

```
pihole -q fullstory.com
 Match found in list.1.blocklist.com.domains:
   fullstory.com
 Match found in list.3.hostsblocker.com.domains:
   fullstory.com
```

I suspect what you're looking for is the `-adlist` functionality:

```
pihole -q -adlist fullstory.com
 Match found in https://blocklist.com/list.txt
   fullstory.com
 Match found in https://hostsblocker.com/hosts
   fullstory.com
```

I haven't heard any complaints about the `adlist` functionality yet (though to be fair, I don't think many know about it!) so I'm keen to see it be the standard `-q` method.
