### ISSUE TITLE
DNS resolution and webserver stops after clicking query log (show all) option

### ISSUE THREAD

**Issue by HappyGuy22** [pi-hole/pi-hole#2245]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

**Expected behaviour:**
```
OS: Raspbian Stretch on Pi Zero W (over WiFi)
FTL beta testing with unbound resolver setup. No other modifications to the system. 
No other service installed on the system. 
Only 2 adlists configured.

DNS and webserver should not stop working after clicking the query log page.
```
**Actual behaviour:**
```
The DNS and webserver will work while visiting any page on the web interface except the query log page. 
But the queries in 10mins works fine however when I click on show all option, the web interface will stop responding and DNS service stops. 
Restarting the service doesn't do anything, only way to get it working is by rebooting the system. 

No other service running on port 5353 and no firewall or iptables rules.
```
**Steps to reproduce:**
```
1. Install pi-hole 
2. Move to FTL DNS branch. 
3. Install and configure unbound DNS resolver.
4. Reboot.
5. Visit `pi.hole/admin` 
6. Go to query log page, click on show all option. 
7. Web interface stops responding and DNS service stops.
8. If you want get everything working again, reboot the system.
```
**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`00itsjhv2y`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried restarting services in CLI, didn't worked. `

`This is the output of unbound`

![screenshot_juicessh_20180620-123404-01](https://user-images.githubusercontent.com/29010784/41642825-1426a5c6-7487-11e8-8290-174fc12dd0cd.jpeg)

`This is what I get when I try to run pihole -c`

![screenshot_juicessh_20180620-123245-01](https://user-images.githubusercontent.com/29010784/41642862-3305576c-7487-11e8-888d-cccf0752ef7e.jpeg)

`This is what I get while loading web interface `

![screenshot_chrome_20180620-182004-01](https://user-images.githubusercontent.com/29010784/41663718-b6e58f90-74c1-11e8-886a-ac481586289c.jpeg)

**Comment by technicalpyro** [comment]
this is a known issue with how the query log is loaded and PHP.  the new web UI does address tis with server side pagination to an extent.  from your screenshots i see chrome have you tried with firefox at all ?

**Comment by Mcat12** [comment]
How many total queries do you have? On a Pi Zero, if you have over a few hundred thousand queries it will take a while to load, and if it takes too long then it will not be able to display the queries.

**Comment by HappyGuy22** [comment]
@technicalpyro didn't tried with Firefox. @Mcat12 only  a few hundred queries. As soon as I click on show all option, DNS resolution stops but if I run `sudo service unbound status` it's running.

**Comment by Mcat12** [comment]
Pi-hole uses dnsmasq, not unbound. Was the debug token made right after it stopped working, before you tried to get it working again? If not, make a new debug token when things aren't working.

**Comment by HappyGuy22** [comment]
@Mcat12 Since the system was unable to resolve domains, debug token cannot be uploaded to tricorder.pi-hole.net. I grabbed the local copy, download it here:
http://s000.tinyupload.com/index.php?file_id=41796349514177745031

**Comment by technicalpyro** [comment]
run pihole -r and select reconfigure you network setting do not match what is in the setupvars conf file

**Comment by HappyGuy22** [comment]
@technicalpyro I reconfigured my Pi-hole, unfortunately the problem still exists.
Here are some more information.
1. All three services `lighttpd` `unbound` pihole-FTL` is active and running while this happens.
2. When try to browse sites, I get `error name not resolved`. Even if I restart the above 3 services, the problem exists. Only solution is a system reboot.
3. I have tested this only in Chrome mobile. I'll try it in different browsers and I will report it here.

**Comment by Mcat12** [comment]
It looks like FTL is crashing, from looking at your log. @DL6ER and I will try to figure out the cause. We may need more data from you soon, so thank you for your patience.

**Comment by HappyGuy22** [comment]
@DL6ER I will look into it...

**Comment by dschaper** [comment]
Just have to say I like your avatar.

**Comment by HappyGuy22** [comment]
A quick question, is this happening because of low powered Pi zero? I installed FTLDNS and unbound on Amazon AWS t2.micro. It seems to work fine

**Comment by Mcat12** [comment]
The crash should not be because the Pi Zero is low powered.

**Comment by jacobsalmela** [comment]
@HappyGuy22 are you still seeing this with v4.0?

**Comment by dschaper** [comment]
Close from non-response
