### ISSUE TITLE
Lighttpd starts with warning about unknown config-key.

### ISSUE THREAD

**Issue by fidelito** [pi-hole/pi-hole#2248]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5

---
**Expected behaviour:**

No errors when starting up lighttpd after following https://discourse.pi-hole.net/t/https-for-pi-hole-web-interface/6249 instructions

**Actual behaviour:**

(server.c.1295) WARNING: unknown config-key: alias.url (ignored)
I am also getting unknown config-key for  ssl.use-compression

**Steps to reproduce:**

lighttpd -v
lighttpd/1.4.45 (ssl) - a light and fast webserver
Build-Date: Jan 14 2017 21:07:19

`{Steps of what you have done to fix this}`

fixed it by mod_alias in /etc/lighttpd/lighttpd.conf

so it looks like below:

server.modules = (
"mod_access",
"mod_accesslog",
"mod_auth",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite",
"mod_alias"
)

so to fix this I comment it out  ssl.use-compression = "disable" on /etc/lighttpd/external.conf

**Comment by fidelito** [comment]
there is now in the template. I didn't think i needed the template since is so easy to fix.

**Comment by Mcat12** [comment]
If you have the issue only after following those instructions, then contact whoever made the instructions so they can fix them.

**Comment by fidelito** [comment]
It could be handled, either way, to be honest. It be great if it can just come fix. I don't who to contact. I just wanted to report it and share with anyone who is googling to fix it.

**Comment by Mcat12** [comment]
You can comment on the Discourse thread and @ the author of the post.

**Comment by fidelito** [comment]
https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771/14 I did it there. thanks but I am not sure if you guys still want to add to the code.

**Comment by LeSpocky** [comment]
I'm curious why this was closed. I see the same error in a fresh install on Raspbian stretch from yesterday, when running either `pihole -d` or `lighttpd -tt -f /etc/lighttpd/lighttpd.conf`:

    2019-02-26 09:27:21: (server.c.1295) WARNING: unknown config-key: alias.url (ignored) 

Since the `/etc/lighttpd/lighttpd.conf` is written by pi-hole with a big, fat warning it is overwritten, I suspect the `mod_alias` module is missing from the lighttpd config? The problem might be lighttpd config snippets shipped with Debian/Raspbian, which contain 'alias.url +=' directives:

* `/etc/lighttpd/conf-available/90-debian-doc.conf`
* `/etc/lighttpd/conf-available/90-javascript-alias.conf`

**Comment by dschaper** [comment]
The warning is ignored, it doesn't affect the operation of the Pi-hole web server.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/update-5-1-keine-anzeige-queries-blocked/35626/11

**Comment by DavidOsipov** [comment]
Not everyone knows German

**Comment by yubiuser** [comment]
>Not everyone knows German

... you down-voted a Bot.....

**Comment by Inffinite** [comment]
2022 and i still have the same issue. And the pihole userspace link does not help.

> This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:
> 
> https://discourse.pi-hole.net/t/error-ftl-v-5-10-2-syslog-warning-unknown-config-key-alias-url-ignored/50066/1

**Comment by rdwebdesign** [comment]
I think `lighttpd` removed that option a long time ago.

`lighttpd` doesn't use compression with TLS.

> ... By default in lighttpd 1.4.56 and later, lighttpd TLS modules disable TLS compression and TLS renegotiation in TLSv1.2 as required by RFC 7540. 

From [Lighttpd DOCS - Secure HTTP: HTTP/2 and TLS](https://redmine.lighttpd.net/projects/1/wiki/docs_ssl#HTTP2-and-TLS)
  

Also, it is not recommended:
> A deployment of HTTP/2 over TLS 1.2 MUST disable compression. TLS compression can lead to the exposure of information that would not otherwise be revealed [RFC3749]. Generic compression is unnecessary since HTTP/2 provides compression features that are more aware of context and therefore likely to be more appropriate for use for performance, security, or other reasons.

From [httpwg.org - Hypertext Transfer Protocol Version 2 (HTTP/2): TLS 1.2 Features]
https://httpwg.org/specs/rfc7540.html#n-tls-1.2-features
