### ISSUE TITLE
Query Log under Long Term Data does not have commas seperating digits.

### ISSUE THREAD

**Issue by HeyBanditoz** [pi-hole/pi-hole#2250]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
I would expect to see commas seperating the numbers, for easier readability, like in the _Dashboard_.
Example:
![Example, expected behaviour](https://banditoz.org/u/XRLJY.png)

**Actual behaviour:**
In _query log_ under _long term data,_ numbers with four digits are not seperated by commas, making for slightly harder readability.
Example:
![Example, actual behaviour](https://banditoz.org/u/raBoT.png)

**Steps to reproduce:**
1. Visit the _Dashboard,_ notice the four boxes' numbers at the top have digits seperated by commas.
2. Visit _long term data_ under _query log_, notice the four boxes do not have commas seperating digits.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wg45xoq15p`

**Troubleshooting undertaken, and/or other relevant information:**
N/A

**Comment by Mcat12** [comment]
Issue moved to [pi-hole/AdminLTE #776](https://github.com/pi-hole/AdminLTE/issues/776) via [**ZenHub**](https://www.zenhub.com/)
