### ISSUE TITLE
Install on an OpenWRT router

### ISSUE THREAD

**Issue by ale5000-git** [pi-hole/pi-hole#2251]
The OpenWRT open source firmware (available for various routers) allow to install packages on it.

Is there a version of Pi-hole that can be directly installed on the router (so that it doesn't require a pc always online)?

**Comment by Mcat12** [comment]
There is no support for routers. See this feature request:https://discourse.pi-hole.net/t/pihole-directly-on-routers-tomato-merlinwrt-dd-wrt-openwrt/1314

**Comment by darkrain88** [comment]
can be install on openwrt with chroot debian environment
HARDWARE system is x64 mini PC. with intel cpu.
