### ISSUE TITLE
Output from critical commands (stdout and stderr) redirected to /dev/null

### ISSUE THREAD

**Issue by Neepawa** [pi-hole/pi-hole#2252]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10 (I've been writing bash scripts in production environments for over fifteen years)

---

**Expected behaviour:**

If an important installation step (installing prerequisite packages or cloning pi-hole from github) fails, information on the command that failed is displayed to the user as an aid in resolving it.

**Actual behaviour:**

* When installing a prerequisite package fails, installation terminates with no information at all
* When updating using 'git', installation terminates with a simple message: "Error: Could not update local repository. Contact support."

**Steps to reproduce:**

 1. Rename the binary the system uses for installing packages:

        [ -x /usr/bin/apt-get ] && PACKAGER='apt-get' || PACKAGER='yum'
        cd /usr/bin; mv $PACKAGER ${PACKAGER}.x
        echo "echo 'Error: the $PACKAGER command has been replaced with a shell script that always fails'; exit 4" >$PACKAGER
        chmod +x $PACKAGER

 2. Run the installer. Every time the package installer runs, it fails with a non-zero return code because it's now a shell script designed to fail. Output from the installation script:

        (leading parts snipped)
        [✓] Disk space check
        [✓] Update local cache of available packages
        [✓] Checking yum for upgraded packages... up to date!
        [i] Installer Dependency checks...
        [i] Checking for dialog (will be installed)
        [i] Checking for git (will be installed)
        [i] Checking for iproute (will be installed)
        [i] Checking for net-tools (will be installed)
        [i] Checking for newt (will be installed)
        [i] Checking for procps-ng (will be installed)
        [i] Checking for epel-release (will be installed)
        [root@raspberrypi ~]# 

3. Undo the above changes:

        cd /usr/bin; rm -f $PACKAGER; mv ${PACKAGER}.x $PACKAGER

4. Now do the same thing for the "git" command:

        cd /usr/bin
        mv git git.x
        echo "echo 'Error: the git command has been replaced with a shell script that always fails'; exit 8" >git
        chmod +x git

56. Run the installer again. Output from the install:

        (leading parts snipped)
        [✓] Disk space check
     
        [✓] Update local cache of available packages
     
        [✓] Checking yum for upgraded packages... up to date!
     
        [i] Installer Dependency checks...
        [i] Checking for dialog (will be installed)
        [✓] Checking for git 
        [✓] Checking for iproute
        [✓] Checking for net-tools
        [✓] Checking for newt
        [✓] Checking for procps-ng
        [✓] Checking for epel-release
     
        [i] SELinux mode detected: Disabled
     
        [✓] Stopping dnsmasq service...
     
        [✓] Stopping lighttpd service...
        [i] Using interface: enp0s7
        [i] Using   [✓] Set IP address to 192.168.1.21
            You may need to restart after the install is complete
        [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
        [i] IPv4 address: 192.168.1.21/24
        [i] IPv6 address: 
        [i] Web Interface On
        [i] Logging On. 
        [✗] Check for existing repository in /etc/.pihole
        [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...
        Error: Could not update local repository. Contact support.
        [root@raspberrypi ~]# 

**Troubleshooting undertaken, and/or other relevant information:**

I have written a new function called `run_command`, which uses `eval` to run a command and its parameters. It sends all output to a temporary file and captures the command's return code. On a non-zero return code it outputs information similar to the following:

    [✗] Check for existing repository in /etc/.pihole
    [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...
    Error: a critical command failed    ←(red)
     
    The command was:
      git clone -q --depth 1 'https://github.com/pi-hole/pi-hole.git' '/etc/.pihole'    ←(bold)
     
    Output from the command was:
    | Error: the git command has been replaced with a shell script that always fails    ←(gray)
    |   
    | Command exited with return code 8
    
    Error: Could not update local repository. Contact support.
    [root@raspberrypi ~]# 

I have identified about a dozen places in the installation script where `run_command` should be used. **I can submit a pull request if there is interest from the developers.** (I note that a similar issue, #1366, was closed without being accepted.)

**Comment by dschaper** [comment]
#1366 was actually merged in, but I'd be interested in seeing more of this. The only caveat that I would have is that the temporary file is non-deterministic so that there aren't temp files with commands remaining. Something similar to the way we handle the logfiles, open random temp file, open new file handle on that and then delete the file, accessing it via the file handle.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1901

**Comment by Neepawa** [comment]
I debated making an in-progress presentation of my work vs going all-out with branching/developing/committing/pull-request. Since I'm pretty much unknown to the project, I've decided to go with the former approach and present what I've done so far.

Here's the `run_command` function I developed. Some items of note:

* While this code is production ready, I haven't yet implemented it throughout the installation script.
* I'm using file descriptor 10 due to a recent bash feature that allows for using a shell variable for the file descriptor, and these descriptors start at 10. However, the version of bash used by CentOS 7 (where I'm doing the bulk of my development) doesn't yet have this feature, so I had to fall back to hard-coding it.
* The colour variables `COL_BOLD` and `COL_GRAY` aren't currently defined in the script. I got the names and definitions from `/opt/pihole/COL_TABLE`

The code:

    run_command() {
      # Temporarily turn off feature that kills the shell when a command fails
      set +e

      # Create a file to contain the output from the command, allocate a file
      # descriptor for reading and writing, and delete the file (security measure)
      local outfile=$(mktemp /tmp/pihole_outXXXX)
      exec 10>$outfile
      rm -f $outfile

      # Run the requested command and send its output to the output file descriptor
      eval "($1; rc=\$?; echo; echo Command exited with return code \$rc) >&10 2>&1"

      # Extract the return code from the output file
      local rc=$(tail -n1 </proc/$$/fd/10 | cut -f6 -d' ')
      # Display information if the command failed
      if [[ $rc != 0 ]]; then 
        echo 
        echo -e "  ${COL_LIGHT_RED}Error: a critical command failed${COL_NC}"
        echo
        echo "  The command was:"
        echo -e "    ${COL_BOLD}$1${COL_NC}"
        echo
        echo -e "  Output from the command was:${COL_GRAY}"
        sed 's/^/  | /' </proc/$$/fd/10
        echo -e "${COL_NC}"
      fi

      # Release the file descriptor
      exec 10>&-
      # Re-enable feature to kill the shell when a command fails
      set -e
      # Return the command's exit value
      return $rc
    }

So far I've implemented `run_command` in two places, those being the two mentioned in my initial report:

 1. In `make_repo`:

        # A function to clone a repo
        make_repo() {
          (... lines snipped ...)
          # Clone the repo and return the return code from this command         # HERE
          run_command "git clone -q --depth 1 '${remoteRepo}' '${directory}'" || return $?
          (... lines snipped ...)
        }

 2. In `install_dependent_packages`:

        install_dependent_packages() {
          (... lines snipped ...)
          if command -v debconf-apt-progress &> /dev/null; then
            (... lines snipped ...)
            if [[ "${#installArray[@]}" -gt 0 ]]; then
              #
              test_dpkg_lock
              #
              local installer="${PKG_INSTALL[@]}"
              local package_list="${installArray[@]}"
              run_command "debconf-apt-progress -- $installer $package_list"    # HERE
              return
            fi
            (... lines snipped ...)
          fi

          # Install Fedora/CentOS packages
          (... lines snipped ...)
          if [[ "${#installArray[@]}" -gt 0 ]]; then
            #
            local installer="${PKG_INSTALL[@]}"
            local package_list="${installArray[@]}"
            run_command "$installer $package_list"                              # HERE
            return
          fi
          echo ""
          return 0
        }

One caveat on the `install_dependent_packages` code: it would break if ever a Debian or Red Hat based distribution released a package with a space in its name. But such a change would likely break things all over the place, so I regard the probability of that happening to be low.

**Comment by Mcat12** [comment]
You should definitely make a PR. PRs are not concrete; we can debate the implementation details there.

**Comment by Neepawa** [comment]
This is the first time I've worked with a project on GitHub. So far  I've added an ssh key to GitHub, cloned the project, and created a branch from development. I've made the and tested the changes on both Raspbian and CentOS, and committed to the branch.

Following GitHub's recommendation, I ran the following command set the remote origin:

    git remote set-url origin git@github.com:/pi-hole/pi-hole.git

GitHub is complaining I don't have permission when I attempt to do  `git push origin run-command-feature:`

    ERROR: Permission to pi-hole/pi-hole.git denied to Neepawa.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights and the repository exists.

Suggestions?

**Comment by dschaper** [comment]
This is being implemented via PR, will leave this issue open to track the progress.

**Comment by carlosnewmusic** [comment]
when executing the command as root returns this, as server is nginx 1.14 curl -sSL https://install.pi-hole.net | bash

![imagen](https://user-images.githubusercontent.com/19379457/48866586-99433100-edd3-11e8-8b3c-766d6ebc4bdc.png)

**Comment by dschaper** [comment]
Open a new issue please.

**Comment by yubiuser** [comment]
Pi-hole came a long way since this has been discussed. Please open a new ticket if the issue persists.
