### ISSUE TITLE
Multiple IP listening / per user lists

### ISSUE THREAD

**Issue by V1TA5** [pi-hole/pi-hole#2253]
Just a quick idea:
It would be great (if possible) to have pi-hole lsiten on multiple ips and to be able to bind each ip to a different set of lists.
If the Web admin panel would support it you could have the users then have individual accounts to maintain custom white/blacklists for their respective dns ip.
Usage scenario: one person uses facebook and the other doesnt.

Im just putting this out there and im sure im not the first having this idea. :)

**Comment by beerisgood** [comment]
Not possible because its DNS 
Use two PiHoles instead

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
