### ISSUE TITLE
Query adlists not working correctly on Dev branch

### ISSUE THREAD

**Issue by mmotti** [pi-hole/pi-hole#2255]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`v10.events.data.microsoft.com --> piholed`

`Query for v10.events.data.microsoft.com should return a match in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`

**Actual behaviour:**

 `v10.events.data.microsoft.com --> piholed`

Partial Match:
` Match found in (no associated adlists URL found): v10.events.data.microsoft.com`

Exact Match:  
`Exact match for v10.events.data.microsoft.com found in: (no associated adlists URL found)`

Pihole -q: 

> pi@raspberrypi:~ $ pihole -q v10.events.data.microsoft.com
> **/opt/pihole/query.sh: line 120: processWildcards: command not found**
>  Match found in list.0.raw.githubusercontent.com.domains:
>    v10.events.data.microsoft.com

**Steps to reproduce:**

1. Add/Enable: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
2. Query adlists from the web interface for v10.events.data.microsoft.com

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Possibly related to #2244
`8rbpkj0mla`

**Troubleshooting undertaken, and/or other relevant information:**

1. Tried rebuilding the lists with `pihole -g` and `pihole -g -f`
2. Removed regex.list and all blacklisted / whitelisted items
3. Several pihole-FTL service restarts

**Version**

> Pi-hole version is v3.3.1-261-g0ddfa8a (Latest: v3.3.1)
> AdminLTE version is v3.3-196-g25ead792 (Latest: v3.3)
> FTL version is vDev-3bf6151 (Latest: v3.0)

**Comment by Mcat12** [comment]
Run `pihole -r` to try and fix the `processWildcards` issue (I can not reproduce it).

I do however see this issue, which I will open a PR for:
```
/opt/pihole/query.sh: line 172: adListsList: No such file or directory
```

**Comment by mmotti** [comment]
@Mcat12 I tried both repair and reconfigure under `pihole -r`

The result remains:


> pihole -q v10.events.data.microsoft.com
>  Match found in Whitelist
>    v10.events.data.microsoft.com
> /opt/pihole/query.sh: line 120: processWildcards: command not found
>  Match found in list.0.raw.githubusercontent.com.domains:
>    v10.events.data.microsoft.com

Is there anything further I can do to troubleshoot this?

The only deviations from a standard setup are:
- Checking out the dev branch
- Adding a regex.list file (attached, although a .txt extension added to allow me to upload)
- Adding the entries from [anudeepND whitelist](https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt) to `/etc/pihole/whitelist.txt`

**Comment by Mcat12** [comment]
Do you see a `processWildcards` function in `/usr/local/bin/pihole`?

**Comment by dschaper** [comment]
What does the output from `sudo bash -x /opt/pihole/query.sh v10.events.data.microsoft.com` look like?

**Comment by mmotti** [comment]
@dschaper again, sorry for the screenshot.

![screenshot_20180701-004022_juicessh](https://user-images.githubusercontent.com/35599110/42129797-b59e92ea-7cc7-11e8-9fc7-e02e16d6d41f.jpg)

**Comment by dschaper** [comment]
Thanks, we're talking now about how best to handle this. The `processWildcards` is in another script and it looks like the function isn't available to `query.sh`, but it's something we can fix. We just need to decide what is the best way to handle the solution.

**Comment by dschaper** [comment]
Can you try this new update on Development and see if that solves the issue?

**Comment by mmotti** [comment]
Looks to have fixed it in both the console and Web interface.

Thanks, guys!

**Comment by dschaper** [comment]
Great, thanks1
