### ISSUE TITLE
Install quits after [i] Checking for php-pdo (will be installed) CentOS 7

### ISSUE THREAD

**Issue by simonetm** [pi-hole/pi-hole#2258]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Installation of Pi-Hole

**Actual behaviour:**

Installation quits with no errors after "[i] Checking for php-pdo (will be installed)"

**Steps to reproduce:**

Attempt to install on CentOS 7

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

PiHole not installed can't run pihole-d

**Troubleshooting undertaken, and/or other relevant information:**

ran yum update and rebooted

**Comment by Mcat12** [comment]
Do you get any errors when you try to install the packages that were marked as to be installed?

**Comment by simonetm** [comment]
Error: php70w-common conflicts with php-common-5.4.16-45.el7.x86_64

**Comment by simonetm** [comment]
This was resolved by removing php70w-common
