### ISSUE TITLE
Queries fail because of "bad compression pointer"

### ISSUE THREAD

**Issue by flyingstar16** [pi-hole/pi-hole#2259]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**

Queries return valid DNS packets (and data)

**Actual behaviour:**

I noticed this issue especially with www.paypal.com (but NOT paypal.com)
Opening www.paypal.com on a browser returns a server error.
Using dig from cygwin on Win10 and from the PiHole itself (RPi 3 running raspbian stretch) I get the following:
From PiHole
```
pi@PiHole:~ $ dig www.paypal.com
;; Got bad packet: bad compression pointer
237 bytes
ca 69 81 80 00 01 00 06 00 00 00 01 03 77 77 77          .i...........www
06 70 61 79 70 61 6c 03 63 6f 6d 00 00 01 00 01          .paypal.com.....
c0 0c 00 05 00 01 00 00 00 d4 00 1b 03 67 65 6f          .............geo
06 70 61 79 70 61 6c 03 63 6f 6d 06 61 6b 61 64          .paypal.com.akad
6e 73 03 6e 65 74 00 03 67 65 6f 06 70 61 79 70          ns.net..geo.payp
61 6c 03 63 6f 6d 06 61 6b 61 64 6e 73 03 6e 65          al.com.akadns.ne
74 00 00 05 00 01 00 00 00 17 00 0e 0b 68 6f 74          t............hot
73 70 6f 74 2d 77 77 77 c0 f5 c0 6c 00 05 00 01          spot-www...l....
00 00 00 17 00 06 03 77 6c 62 c0 4b c0 86 00 05          .......wlb.K....
00 01 00 00 00 17 00 19 03 77 77 77 06 70 61 79          .........www.pay
70 61 6c 03 63 6f 6d 07 65 64 67 65 6b 65 79 c0          pal.com.edgekey.
5d c0 98 00 05 00 01 00 00 00 52 00 15 05 65 33          ].........R...e3
36 39 34 01 61 0a 61 6b 61 6d 61 69 65 64 67 65          694.a.akamaiedge
c0 5d c0 bd 00 01 00 01 00 00 00 0d 00 04 17 26          .].............&
da 55 00 00 29 05 ac 00 00 00 00 00 00                   .U..)........
```

From cygwin on Win10:
```
$ dig www.paypal.com
;; Got bad packet: bad compression pointer
237 bytes
b7 0e 81 80 00 01 00 06 00 00 00 01 03 77 77 77          .............www
06 70 61 79 70 61 6c 03 63 6f 6d 00 00 01 00 01          .paypal.com.....
c0 0c 00 05 00 01 00 00 00 76 00 1b 03 67 65 6f          .........v...geo
06 70 61 79 70 61 6c 03 63 6f 6d 06 61 6b 61 64          .paypal.com.akad
6e 73 03 6e 65 74 00 03 67 65 6f 06 70 61 79 70          ns.net..geo.payp
61 6c 03 63 6f 6d 06 61 6b 61 64 6e 73 03 6e 65          al.com.akadns.ne
74 00 00 05 00 01 00 00 00 01 00 0e 0b 68 6f 74          t............hot
73 70 6f 74 2d 77 77 77 c0 f5 c0 6c 00 05 00 01          spot-www...l....
00 00 00 01 00 06 03 77 6c 62 c0 4b c0 86 00 05          .......wlb.K....
00 01 00 00 00 01 00 19 03 77 77 77 06 70 61 79          .........www.pay
70 61 6c 03 63 6f 6d 07 65 64 67 65 6b 65 79 c0          pal.com.edgekey.
5d c0 98 00 05 00 01 00 00 00 27 00 15 05 65 33          ].........'...e3
36 39 34 01 61 0a 61 6b 61 6d 61 69 65 64 67 65          694.a.akamaiedge
c0 5d c0 bd 00 01 00 01 00 00 00 0d 00 04 17 26          .].............&
da 55 00 00 29 05 ac 00 00 00 00 00 00                   .U..)........

```
**Steps to reproduce:**

From a command line  that has dig installed, do "dig www.paypal.com" or "host www.paypal.com"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

4tm6nn6133

**Troubleshooting undertaken, and/or other relevant information:**

Tried from multiple devices (Win10, PiHole, Android phone).
Rebooted PiHole, ran pihole -r in "repair" mode, checked /etc/dnsmasq.d/01-pihole.conf for any strange entries.

**Comment by Mcat12** [comment]
Does it still happen if you disable DNSSEC?

**Comment by flyingstar16** [comment]
I should note that this is inconsistent: PayPal seems to be affected more than others, but it sometime happens for other domains (e.g. google).
My DNS is set to use Cloudflare's 1.1.1.1 (& 1.0.0.1) and after a ton of attempts it sometime works and cache the results, which are then served correctly until cache expiration.
And BTW, dnsmasq seems to be receiving the correct replies
```
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 query[A] www.paypal.com from 192.168.0.32
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 forwarded www.paypal.com to 1.0.0.1
Jul  1 19:01:37 dnsmasq[30063]: * 192.168.0.32/53034 dnssec-query[DS] com to 1.0.0.1
Jul  1 19:01:37 dnsmasq[30063]: * 192.168.0.32/53034 dnssec-query[DNSKEY] . to 1.0.0.1
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply www.paypal.com is <CNAME>
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply geo.paypal.com.akadns.net is <CNAME>
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply hotspot-www.paypal.com.akadns.net is <CNAME>
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply wlb.paypal.com.akadns.net is <CNAME>
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply www.paypal.com.edgekey.net is <CNAME>
Jul  1 19:01:37 dnsmasq[30063]: 5797 192.168.0.32/53034 reply e3694.a.akamaiedge.net is 23.38.218.85

```

**Comment by flyingstar16** [comment]
> Does it still happen if you disable DNSSEC?
It does not...

Could it be cloudflare?

**Comment by flyingstar16** [comment]
Whelp, just realized this is most likely a duplicate of #2238 
Closing, sorry :)

**Comment by flyingstar16** [comment]
Yeah, I spotted the other issue afterwards - I searched for "pointer" and "compression" in the issues, didn't think about checking for "paypal"...
Thanks for the assist!
