### ISSUE TITLE
Installation freezed by FTL installation, machine freezed, Ubuntu 18.04 / Lubuntu

### ISSUE THREAD

**Issue by Zentris** [pi-hole/pi-hole#2260]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Installation on a freshly installed Ubuntu 18.04 server (VM (vmWare)): freshly installation should be completed successfully.`

**Actual behaviour:**

<pre>Installation on a VM with Ubuntu 18.04 server, freshly installed.
Installation stops on or after "Downloading and Installing FTL", machine freezes, 
CPU at approx. 80%, RAM of 4GB is fully used.
The machine is not operable and can only be started by a hard reset:

  [i] FTL Checks...
  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL.../tmp/tmp.0PJJPZua2N /etc/.pihole</pre>

**Steps to reproduce:**
<pre>
* Install Ubuntu 18.04 server on VM (vmWare) with 2vCPU, 4GB RAM, 
  fix IP Address per DHCP (per sticky IP for MAC)
* check in with user (remote per ssh)
* become root (sudo bash)
* curl -sSL https://install.pi-hole.net | bash
</pre>

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`not possible, machine is frozzen`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
`??? i use more RAM (normally i use 2GB RAM), but no change`
`I try the installation also with Lubuntu, same result`

**Comment by dschaper** [comment]
Please run `curl -sSL https://install.pi-hole.net | sudo bash -x` and provide use with the output where the install stalls.

**Comment by Zentris** [comment]
ok (no change of behavior), 
Result;

  [i] FTL Checks...
++ uname -m
+ machine=x86_64
+ local 'str=Detecting architecture'
+ echo -ne '  [i] Detecting architecture...'
+ [[ x86_64 == \a\r\m* ]]
+ [[ x86_64 == *\a\a\r\c\h* ]]
  [i] Detecting architecture...+ [[ x86_64 == \p\p\c ]]
+ [[ x86_64 == \x\8\6\_\6\4 ]]
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Detected x86_64 architecture'
+ binary=pihole-FTL-linux-x86_64
+ echo -e '  [i] Checking for existing FTL binary...'
  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
++ which pihole-FTL
+ local ftlLoc=
+ [[ -n '' ]]
+ FTLinstall pihole-FTL-linux-x86_64
+ local binary=pihole-FTL-linux-x86_64
+ local latesttag
+ local 'str=Downloading and Installing FTL'
+ echo -ne '  [i] Downloading and Installing FTL...'
  [i] Downloading and Installing FTL...++ curl -sI https://github.com/pi-hole/FTL/releases/latest
++ awk -F / '{print $NF}'
++ grep Location
+ latesttag=$'v3.0\r'
 == v* ]].0
++ mktemp -d
+ pushd /tmp/tmp.knSOfIaK9Q
/tmp/tmp.knSOfIaK9Q /etc/.pihole
+ install -T -m 0755 /etc/.pihole/advanced/pihole-FTL.service /etc/init.d/pihole-FTL
+ curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64 -o pihole-FTL-linux-x86_64

**Comment by dschaper** [comment]
And does `curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64 -o pihole-FTL-linux-x86_64` finish when you try it manually?

**Comment by Zentris** [comment]
Yes, its gone:

root@pihole:~# curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64 -o pihole-FTL-linux-x86_64
root@pihole:~# ll
total 1536
....
-rw-r--r-- 1 root  root  1533731 Jul  1 21:14 pihole-FTL-linux-x86_64
....
root@pihole:~#

**Comment by dschaper** [comment]
Can you review https://discourse.pi-hole.net/t/install-fails-on-ubuntu-desktop-18-4/10410 and see if the suggestions there help with the installation?

**Comment by Zentris** [comment]
Ok, i read the issue 2179 (https://github.com/pi-hole/pi-hole/issues/2179) and i think, the base problem is the same... (DNS resolver).
It looks like the name resolution is lost during installation. But why the CPU load is suddenly so high and the computer freezes is not clear to me.
I suggest closing this message with reference to the above (same root cause).
