### ISSUE TITLE
Power outage now pihole will not start

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#2264]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

pihole starts

**Actual behaviour:**

pihole does not start

**Steps to reproduce:**

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

dv608njeyr

**Troubleshooting undertaken, and/or other relevant information:**

$ pihole status
sudo: unable to resolve host pi-hole
  [✗] DNS service is NOT running

$ pihole restartdns
sudo: unable to resolve host pi-hole
  [✗] Job for dnsmasq.service failed. See 'systemctl status dnsmasq.service' and 'journalctl -xn' for details.

$ sudo systemctl status dnsmasq.service -l
sudo: unable to resolve host pi-hole
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Mon 2018-07-02 16:34:11 MDT; 1min 45s ago
  Process: 1342 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=1/FAILURE)

Jul 02 16:34:11 pi-hole dnsmasq[1342]: dnsmasq: extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf
Jul 02 16:34:11 pi-hole systemd[1]: dnsmasq.service: control process exited, code=exited status=1
Jul 02 16:34:11 pi-hole systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jul 02 16:34:11 pi-hole systemd[1]: Unit dnsmasq.service entered failed state.

**Comment by RamSet** [comment]
> Jul 02 16:34:11 pi-hole dnsmasq[1342]: dnsmasq: extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf

Is that the `interface=` line ?

Try running a `pihole -r` and reconfigure :)

**Comment by C4Wiz** [comment]
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2015, 2016 by Jacob Salmela
# Network-wide ad blocking via your Raspberry Pi
# http://pi-hole.net
# dnsmasq config for Pi-hole
#
# Pi-hole is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPERATE CONFIG FILE           #
#                        OR IN /etc/dnsmasq.conf                              #
###############################################################################

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list


localise-queries


no-resolv



cache-size=10000

log-queries=extra
log-facility=/var/log/pihole.log

local-ttl=2

log-async
server=8.8.8.8
server=8.8.4.4
interface=eth0
```

**Comment by C4Wiz** [comment]
still nothing after pihole -r

**Comment by RamSet** [comment]
> log-queries=extra

what is your dnsmasq version ? and the OS you're running the Pi-hole on ?

(you could comment that line out and try restarting Pi-hole)

https://discourse.pi-hole.net/search?q=log-queries%3Dextra

**Comment by Mcat12** [comment]
You have too old of a version of dnsmasq (2.72). [See this Discourse FAQ](https://discourse.pi-hole.net/t/why-cant-i-run-pi-hole-v3-3-on-raspbian-jessie-or-with-dnsmasq-v2-72/8052)

**Comment by C4Wiz** [comment]
created a new sd card with strech, all is well thanks!
