### ISSUE TITLE
"Use Conditional Fowarding" not working in the development branch

### ISSUE THREAD

**Issue by timocapa** [pi-hole/pi-hole#2266]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

Enabling and filling out the text fields of Conditional Forwarding should start showing the hostnames instead of their IPs in logs.

**Actual behaviour:**

Enabling CF, filling out the text fields and pressing Save does nothing. Upon page refresh it's turned off again and empty. Upon further inspection, both 01-pihole.conf and setupVars.conf are untouched and do not contain related to CONDITIONAL_FORWARDING.

Branch FTLDNS works as expected.

**Steps to reproduce:**

1. Set up a VM with Ubuntu Server 16.04 (or any other version, I tried 18.04 as well)
2. Fully update the Ubuntu install (what I did) and reboot
3. Install Pi-hole and run pihole checkout dev
4. Try if setting up Conditional Forwarding works

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Token of the VM (only pihole): 3y4o5zy1vy

Token of my native install: zyw037pr7n

**Troubleshooting undertaken, and/or other relevant information:**

VM installation and testing the FTLDNS branch.

Workaround is adding everything manually into 01-pihole.conf and setupVars.conf. 
See comment by /u/ryanknapper in my Reddit post:
https://www.reddit.com/r/pihole/comments/8wga5p/use_conditional_fowarding_broken_in_dev/

Probably useless but I'll attach what "Tail pihole.log" and "Tail pihole-FTL.org" respond with in the VM after enabling it.

Tail pihole.log: https://pastebin.com/veWf8Miz
Tail pihole-FTL.log: https://pastebin.com/gxzvMziR

**Comment by Mcat12** [comment]
It looks like #1954 accidentally removed the code from webpage.sh, probably because the latest changes were not merged into the branch before the PR was merged (the PR changes do not mention removing the code).

I'll make a PR to re-add the conditional forwarding code. Thanks for noticing this issue!

**Comment by timocapa** [comment]
No problem and thank you for fixing it! 

Have a nice day :)

**Comment by timocapa** [comment]
I'll close this issue now because it's been fixed (and merged).
