### ISSUE TITLE
Pihole is blocking ads but shows zeros in webui

### ISSUE THREAD

**Issue by tompa-82** [pi-hole/pi-hole#227]
Installed Dietpi then Pihole on a raspberry pi 2, ads are being blocked succesfully, the webui is accessible 
![screenshot_2016-01-23_00-34-28](https://cloud.githubusercontent.com/assets/16761204/12525989/1e2f201c-c169-11e5-8f66-ca89a29100ff.png)
 but shows no stats

**Comment by dschaper** [comment]
DietPi uses an outdated version of Pi-Hole. How did you install Pi-Hole? Was it via the `curl` command or via the Diet-Pi installer?

**Comment by dschaper** [comment]
And which version does your admin screen show as being installed?

**Comment by jacobsalmela** [comment]
Yeah, the DietPi image is a very old version and it also uses Apache instead of `lighttpd`; it's kind of a fork of Pi-hole in its own respects.  It works as-is, but I recommend a clean install of Jessie Lite and then run the install command.  Either way, we can look into it.

**Comment by tompa-82** [comment]
@dschaper installed pi-hole via Diet-pi's dietpi-software script. It says  Pi-hole Version 2.3 in the webui

**Comment by tompa-82** [comment]
I tried
sudo chmod 644 /var/log/pihole.log
sudo chown dnsmasq:root /var/log/pihole.log
as per https://pi-hole.net/help/
then rebooted pi but file permissions get reverted to:
-rwxrwxr-x 1 www-data www-data 60744 Jan 23 10:51 /var/log/pihole.log

**Comment by dschaper** [comment]
The DietPi software script installs an outdated version of the Pi-Hole. Normally the Admin page is accessibile via `http://ip.of.pihole/admin` So if you are getting that Admin page at `http://ip.of.pihole/pihole` then you aren't running the current version of Pi-Hole.

**Comment by dschaper** [comment]
Do you need to run DietPi, or are you able to install Raspban Jessie Lite for a headless server OS?

**Comment by tompa-82** [comment]
Dietpi was for convenience :) and curiosity :)

**Comment by tompa-82** [comment]
can I run 
curl -L install.pi-hole.net | bash
in Dietpi or will it break something?

**Comment by dschaper** [comment]
It looks like DietPi may break the Pi-Hole's configuration. You can try the `curl` command and see if that works, but it may not. We're not affiliated with the DietPi distribution, but we can see how far we can help you out.

**Comment by tompa-82** [comment]
I did the curl command and now the stats show & blocking ads succesfully. Admin page is now at pi-ip/admin as you said.
 Though I don't know if I broke anything else DietPi related. The file permission I mentioned before still says:
-rwxrwxr-x 1 www-data www-data 115482 Jan 23 11:16 /var/log/pihole.log
after rebooting ofcourse

**Comment by tompa-82** [comment]
thanks for your help :+1:

**Comment by dschaper** [comment]
Well, good that it's working... There may be some changes to the Pi-Hole in the future that require specific permissions on the log file, but it appears for now that all is working well.

**Comment by dschaper** [comment]
Sure, not a problem!
