### ISSUE TITLE
Pixel 2 XL running Android P with Private DNS set to Automatic fails on Pi-Hole

### ISSUE THREAD

**Issue by BWBama85** [pi-hole/pi-hole#2274]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Android P users with Automatic Private DNS **should** be able to use Pi-Hole still

**Actual behaviour:**

Enabling Automatic setting in Android P prevents connecting to Pi-Hole server(s)

**Steps to reproduce:**

Upgrade Android phone to latest Android P beta. Under Network & internet > Advanced > Private DNS choose Automatic.

Restart phone. Pi-Hole will fail to block requests. Turning to off and restarting allows Pi-Hole to block requests again. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

0nfm4gwy7g
kzpsy1ydfi

**Troubleshooting undertaken, and/or other relevant information:**

None, outside of my scope.

**Comment by hsinyu-chen** [comment]
Disable private DNS then everything works

**Comment by dschaper** [comment]
Closing this out as it's pretty old.
