### ISSUE TITLE
Pihole fails with a large regex list

### ISSUE THREAD

**Issue by mmotti** [pi-hole/pi-hole#2281]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0.00000000000001`

---
**Expected behaviour:**

I create a large regex.list which emulates the behaviour of EasyList and Easy Privacy.

`||something.com^(?$third-party|etc) --> something\.com$`

I apply the large [regex.list.txt](https://github.com/pi-hole/pi-hole/files/2197791/regex.list.txt) and expect to see some form of error message, or experience pihole parsing the list successfully.

**Actual behaviour:**

After restarting the Pihole FTL service...

Blocking becomes erratic and blocks items that don't fit the regex criteria (e.g. [this](https://avatars1.githubusercontent.com/u/16827203?s=200&v=4))

Unable to disable Pihole. `pihole -disable` seems to complete, but the blocking does not stop. The only way to disable blocking is to put back a small or blank regex.list and restart the service.

**Edit: Even with my smaller [regex.list.txt](https://github.com/pi-hole/pi-hole/files/2197887/regex.list.txt), pihole still blocks regex items when it should be offline.**

In addition - The web interface wouldn't support a large list. It tries to parse everything at once and hangs.

Ultimately it seems that large lists break Pihole (FTL?).

**Steps to reproduce:**

1. Copy regex.list (remove.txt) to /etc/pihole/regex.list
2. Restart Pihole FTP service

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Tried restarting the service several times.

```
 Current Pi-hole version is v3.3.1-320-g4834452
 Current AdminLTE version is v3.3-229-g3d0d3a92
 Current FTL version is vDev-2766084
```

**Comment by dschaper** [comment]
Looking over that list of regex that you are trying to input it looks like regex isn't the approach you should be going for. It's a list of 20000 domains, exact domain matching. Since we only block DNS, there's no need for things like `adalyser\.com$` in regex, that will only match `adalyser.com` exactly. It's better to have that as a blacklisted domain. 

Really that list can be optimized greatly, but it's most likely going to be a time sink as very few of the lines are something that would be for regex. You could put:

```
^ads\.
^ads1\.
^ads2\.
^ads3\.
^ads4\.
^ads5\.
```
all as one regex match and capture anything from `^ads[0-9]*\.` which would get you coverage from `ads.` to `ads99999999999.` ad-infinitum.

**Comment by mmotti** [comment]
I was looking to block *something.com for each of those entries, which is
the reason for populating the regex list with all these entries.

I belive, although I could be wrong, that when the domain is piped (I.e `||
something.com^`, everything visible should be blocked.

This accommodates for something.com, bad.something.com,
test.bad.something.com, etc.

I appreciate that these lists may include large amount of domains that only
require standard blacklisting, but there are some that only include the top
level.

You are absolutely right with the ads.x regex - These regexp have been
converted from my other project where its only possible to use wildcards at
the start or end of the domain. I still need to optimise it :-)

**Comment by dschaper** [comment]
This is the flavor of regex that our parser knows, https://www.regular-expressions.info/posix.html

**Comment by mmotti** [comment]
@dschaper how specific do I need to be with the regex? Would `test\.com$` not match `ad.test.com` and `test.test.com` with POSIX?

**Comment by dschaper** [comment]
That should match, the ones that I saw on the big list that would be off were the ones formatted as `^domain.com$`.

**Comment by mmotti** [comment]
Ah, in that case it looks like I uploaded an older list where I had been experimenting. Apologies for the confusion.

All the regex I have are (or should be) listed as `test\.com$` or `^test\. `

Either way, pihole isn't happy about it :( and it's starting to look like two separate issues:

1. Pihole (possibly) isn't able to handle the larger lists appropriately.
2. `pihole disable` doesn't disable regex blocking.

**Comment by dschaper** [comment]
We'll have to work on 1, that's something to break down and figure out. 2 I think is a real bug that wasn't accounted for in the process.

**Comment by DL6ER** [comment]
We'll probably add a regex debug mode that will log which regex matched a given domain. This will make it easier to see which one is causing an issue.

**Comment by mmotti** [comment]
A "query list" would be helpful too, if it's not already in the works.

I don't believe there is one in the Web interface to query a domain for
blacklisted regex match.

**Comment by DL6ER** [comment]
I think this would be more complicated and prone to error as we need to re-implement the same (i.e., *identical*) Regex handling on the web front...

**Comment by DL6ER** [comment]
```
[2018-07-16 18:45:08.422] Compiled 20620 Regex filters and 5 whitelisted domains in 641.1 msec (0 errors)
```

Okay, I added your list and used your example link:
```
[2018-07-16 18:45:52.836] **** new UDP query[A] "avatars1.githubusercontent.com" from 192.168.2.209 (ID 67)
[2018-07-16 18:45:52.940] Regex in line 12476 matched domain "avatars1.githubusercontent.com"
[2018-07-16 18:45:52.940] WARN: Regex evaluation took 103.449 msec
[2018-07-16 18:45:52.940] Blocking avatars1.githubusercontent.com due to RegEx match
[2018-07-16 18:45:52.952] Added avatars1.githubusercontent.com to cache
```
In line 12476 we find
```
ntent\.com$
```
so FTLDNS is 100% correct in blocking `avatars1.githubusercontent.com`!

I made this debug regexoption available in branch: https://github.com/pi-hole/FTL/tree/new/regex-deebug-mode
You'll have to set `REGEX_DEBUGMODE=true` in your `pihole-FTL.conf`

**Comment by mmotti** [comment]
Understood. A debug / indication of which regex blocked the domains would
be really helpful :-)

**Comment by mmotti** [comment]
Fantastic trouble shooting.

So the issue is in fact because I need to switch to using a supplementary blacklist and regex for `\.something.com$` instead of `something\.com$`

Would you look at that... User error ;)

**Comment by mmotti** [comment]
Just refined the list and created a supplementary host file and it works well.

Seems to take a noticeable hit to the performance though with a large amount of entries in regex.list

I guess this is to be expected, but is there any way to optimise this in future or is it just the way it is?

**Comment by DL6ER** [comment]
The best filter might be of type
```
((^)|(\.))something\.com$
```
in your case. This will match *both* `something,com`, as well as every subdomain, but not `somesomething.com`.

**Comment by DL6ER** [comment]
Oh, I missed your most recent post.

> Seems to take a noticeable hit to the performance though with a large amount of entries in regex.list
I guess this is to be expected, but is there any way to optimise this in future or is it just the way it is?

The performance hit is only seen once per domain (subsequent lookups of the same domains are not again validated against regex). Validating thousands of full-fledged regex filters is quite a tough job and quite compute intense and furthermore all of the filters could potentially match so they all need to be checked (until the first match is found). I see no potential for improvement on top of what we already do.

**Comment by mmotti** [comment]
Thanks, @DL6ER - I have amended the regex. Didn't even occur to me to do that.

Just a small sample:
```
(^|\.)adclear\.net$
(^|\.)adclear\.teufel\.de$
(^|\.)adclerks\.com$
(^|\.)adclick\.com$
(^|\.)adclick\.lv$
```

Also - Thanks for confirming RE. performance. I appreciate that computationally it's quite a big ask with a list of this size. I will see how it goes.

**Comment by mmotti** [comment]
@DL6ER I wondered if you might be able to advise me on the following?

I'm trying to start from scratch to build a regex list that multiple people can use without significant having a significant effect on processing time.

To the best of your knowledge, should it be more taxing or faster to find a result when using OR statements instead of splitting the options out into separate lines?

`^ad(s(ense)?|x|v(ert(s|is(ing|ements?))?)?)?[0-9]*[-_.]`

This is an example of one I made earlier. I know it looks untidy but trying to avoid using capture groups where they are unnecessary and I'm fairly new to regex.

Do you think this would serve FTL better than all of those variations on different lines?

**Comment by DL6ER** [comment]
I have no experience with the performance impact of such constructs, but I assume that it *highly* depends on the particular filter.

You may be able to do put thousand of the unified (many ORs) into `regex.list` and query a domain that is *not* matched. Repeat this with the same statement splitted into separate lines (and also put them in a thousand times so they both ask for theoretically the same amount of work).

*FTL*DNS will have to process all regex filters as they are none of them is matching. If one of the two regex validations takes longer, you have the answer.

**Comment by mmotti** [comment]
@DL6ER apologies for the late reply.

I would assume that it's probably much for muchness, but I will give it a try when I get some time.

I have,however, extracted all viable domains from easylist/easyprivacy (~20,000+) and added each line as the following in `easylist-easyprivacy.conf` in the `dnsmasq.d` directory:

```
server=/004b17a0c349157de.com/
server=/006a039c957c142bb.com/
server=/0073dd485d46d930dd9.com/
server=/007-gateway.com/
server=/00aaa2d81c1d174.com/
```
The default behaviour of the is to block `test.com` and `*.test.com`, so the same as `(^|\.)test.com` in the regex files, but the dnsmasq wildcard blocking is much much faster.

Will there be an option in the future to choose between whether the blacklist should be merged with the regex.list file?

**Comment by Mcat12** [comment]
There are no plans to merge the blacklist and regex list. Also, in the past we've found that using large dnsmasq-based lists is bad for performance.

**Comment by Mcat12** [comment]
All the issues brought up seem to have been resolved.
