### ISSUE TITLE
Web UI - "Clients (over time)" Tooltip Cut Off on Chart

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [pi-hole/pi-hole#2283]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [ ] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

"Clients (over time)" tooltip should behave like the “Queries over last 24 hours” one, where it is above the bottom of the graph.

**Actual behaviour:**

Tooltip is not visible sometimes because it is below graph and cut off.

![](https://discourse.pi-hole.net/uploads/default/original/2X/a/a67e97bfa216ceeeea40e045843f0f2a3d1d5e1a.jpg)

**Steps to reproduce:**

Go to the admin dashboard. Mouse over the graph. See how it is cut off.

You might have to have a small number of clients for this to happen.

**Debug token:**
tdzxtind1o

**Troubleshooting undertaken, and/or other relevant information:**

According to [this](https://discourse.pi-hole.net/t/web-ui-clients-over-time-overlay-tooltip-cut-off-on-chart-workaround/6361) bug report, you have to edit line 117 in so that it looks like this:
`<canvas id="clientsChart" width="800" height="140"></canvas>`

This issue has been around for a while and has multiple reports. Can you guys push a quick fix for this?

**Comment by rrobgill** [comment]
As you have correctly identified, this was a known bug, which has previously been reported. It has been fixed by [#700](https://github.com/pi-hole/AdminLTE/pull/700) in the upcoming version of Pi-hole.

**Comment by Engineer-of-Stuff** [comment]
Awesome! Do you have an ETA for this release?

**Comment by Engineer-of-Stuff** [comment]
Awesome! Do you have an ETA for the release?

**Comment by technicalpyro** [comment]
Soon™ however it is merged into the developement branch if you absolutely must have it
