### ISSUE TITLE
Pages hang on loading, sometimes need a refresh and instant loads

### ISSUE THREAD

**Issue by 1activegeek** [pi-hole/pi-hole#2285]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`DNS lookups should process with no difficulty or delay, and pages should therefore load normal`

**Actual behaviour:**

`Addresses will show in the address bar, will start to load (indicator starts to move), but browser will then hang waiting for load to happen. In many instance, the page will not load or will hang indefinitely. Refresh/reload of the page will load instantly.`

**Steps to reproduce:**

`Run pihole and load ups.com? The difficulty is it seems at this point intermittent. I can not identify a specific way to make it happen. After it successfully loads, it usually doesn't happen again on that site. It's almost like a first lookup is causing massive delays but subsequent lookups from cache are snappy?`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`h6dmssdfbj`

**Troubleshooting undertaken, and/or other relevant information:**

`Not sure where to start so haven't done much to be able to troubleshoot other than check resource loading on browser. Browser indicates no oddity in resource loading. However, if I swap my machine over to direct DNS (aka the 1.1.1.1 or similar) pages will load without issue.`

**Comment by 1activegeek** [comment]
reference #2270 - previous issues found on DietPi but since resolved. Now issue faced with loading. Bear in mind the F12 testing didn't show much value. (Not F12, on a mac 😄 ) but showing resource load times are all appearing normal. Its also worth noting that the site isn't even partially loaded at all either - it's simply a white screen or view of the favorites page (start page) for the browser. Confirmed it is happening on Chrome and Safari.

**Comment by 1activegeek** [comment]
Something I have found of potential value, is a CDN apparently being used that is not loading due to being blocked by piHole - though I'd imagine if a CDN is being blocked the page should still load? Bigger issue is simply that this is one example, if parts of multiple pages are being blocked now on the regular (things like gitlab, github, etc were doing this) - I think there may be a larger issue at hand.

Notice the load timer in the web inspector top of the bar, 2.6 minutes to load this page on UPS.com website. Please let me know if there is something else useful I can dig into. I also pulled a performance profiling from Chrome, but it doesn't show much more other than nothing really happening during that long loading void. 
![image](https://user-images.githubusercontent.com/6810720/42820416-1f253320-89a4-11e8-86b4-50ae26a58db3.png)

**Comment by dschaper** [comment]
Have you added the IPTables rulesets for https rejection?

**Comment by 1activegeek** [comment]
Unless it's done on install, no. Is that done at the CLI on the device itself? In this case DietPi on Rock64?

**Comment by dschaper** [comment]
With the next release the rules won't be necessary anymore with NULL blocking, but for now check out https://discourse.pi-hole.net/t/why-do-some-sites-take-forever-to-load-when-using-pi-hole/3654 Item 2.

**Comment by 1activegeek** [comment]
Aha. I came across that at some point and when you mentioned IPTables I started to look for it. Thanks that was much easier. So I'm going to have to setup a script for this then it seems to ensure these are applied on reboot? It seems next release will solve all my problems 😏 - any rough idea on that coming along?

**Comment by 1activegeek** [comment]
Ok, thanks dan, looks like this resolved it. Just to validate, since I'm not doing IPv6 blocking, I shouldn't need to use the ip6tables rules correct? Those should still pass, or honestly not even be an issue since my router isn't letting anything IPv6 through anyhow.

**Comment by 1activegeek** [comment]
Awesome. Thank you! Sorry for the silly firedrill and oversight on my part pulling that FAQ from the discourse. Looking forward to the new version!!

**Comment by 1activegeek** [comment]
Unfortunately I think I spoke too soon. While initially this seemed to solve it, I think this had something to do with local known cache or something beyond my understanding. It has continued to happen again. The test site on the linked FAQ seems to always load fine now, but the other sites causing issues (namely ups.com continues) is causing this issue again. Now that I've switched back to my containerized version, everything is loading fine again. 

I'm going to keep the dietpi-pihole running separately so that I can run tests to hopefully debug this, but I've had to switch production back to the container again. This time I'll plan to leave my container running until I can 100% confirm this isn't an issue.

Any next step ideas I can try to provide to help analyze this further? Would it help to run a `pihole -d` on the container to try and do a compare/contrast on config to find some possible difference? Seems completely odd that the container runs beautifully, while the local install is plagued by this issue?

**Comment by Mcat12** [comment]
You can try updating to the FTLDNS beta and see if you can still reproduce the issue there.

**Comment by 1activegeek** [comment]
I would ... however I am more worried this will break other things since FTLDNS as I understand will actually overtake/replace DNSmasq locally. Since DietPi has a bunch of stuff tightly integrated (to handle things like other apps/services running) I don't want to run that route yet. At this point I think I'm holding off until FTLDNS is released and DietPi moves to using it.

**Comment by Mcat12** [comment]
That's fine, we plan to release soon. FTLDNS is dnsmasq though (just integrated with FTL), so you should not have any issues replacing dnsmasq with it, unless that integration tries to directly use dnsmasq (such as by name or binary location).

**Comment by 1activegeek** [comment]
Understood, I don't know if I'm using anything that specifically touches or works with dnsmasq, but thats the reason I'll wait. ;) I can also be useful to supply feedback to those guys on any issue that arise once "official" release comes through and validate no issues such as what I'm facing currently.

**Comment by loaderladdy** [comment]
I point my iPhone at a pair of Raspberry Pi 3 based Pi-Holes and I have seen this exact same issue with page loading when using Safari on iOS 12 Public Beta 4 and 5.  I’d assumed it was the beta, then I remembered I could workaround the issue by cranking up a VPN to one of Private Tunnel’s VPN endpoints.  Will check the behaviour again.

A typical test is do a Search in DuckDuckGo or Google, in Safari, then tap a result. The  page starts to load then gets stuck

I don’t use IPV6 as it’s not enabled at the Router, but is enabled on both Pi-Holes.

**Comment by loaderladdy** [comment]
I did various changes and also disassociated my iPhone from my Pi-Hole.  The conclusion I came to is that iOS 12 Beta 5 version of Safari has an issue and the pI-Hole v4 isn’t responsible for the behaviour described, that is similar to that originally described in this issue.

**Comment by 1activegeek** [comment]
I'm going to suggest at this point, we close this out - this is relative to v3, and being that v4 is now officially here, I'll open a new fresh issue with data relative to v4 if it still persists for me after upgrading. Thanks guys for trying to help dig into this.
