### ISSUE TITLE
add custom upstream dns server , how to add custom port (54)

### ISSUE THREAD

**Issue by N0rm4n** [pi-hole/pi-hole#2294]
well ,
I have installed the last version by 
sudo curl -sSL https://install.pi-hole.net | bash
On my RaspberryPi3 and everything works great ! 
then I have installed dnscrypt , but when in settings.php?tab=dns trying to change custom upstream dns the script of web page only accept number and I can't add # to add port something like 127.0.0.1#54 ?! I have configured dnscrypt on port 54 for loopback interface 127.0.0.1.
why ?

**Comment by dschaper** [comment]
The port configuration is on the beta version. The version you have from the main installer does not have that feature. As you will see from https://docs.pi-hole.net, the instructions are for v4.0. We expect to have that released by the end of the week.
