### ISSUE TITLE
[Suggestion] add SKIP_NETWORKING variable to install script

### ISSUE THREAD

**Issue by ML35** [pi-hole/pi-hole#2295]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`pi-hole should not fail to install to box with openVPN interface tun0`

**Actual behaviour:**

`pi-hole failing to install on OS that have openVPN interface tun0`

**Steps to reproduce:**

1. take any OS, that have openVPN interface tun0
2. try to run curl -sSL https://install.pi-hole.net|bash
3. follow configuration steps
4. see error that installer cannot write to /etc/sysconfig/network-scripts/ifcfg-tun0, because this file not existing at all. this is correct because this interface upped only when openVPN is running. but installation fails on this step at all
5. i suggest add one more variable to installer like SKIP_NETWORKING, that just skipping procedure setStaticIPv4, see my patch below. of course, this var disabled by default

**Troubleshooting undertaken, and/or other relevant information:**

[diff.txt](https://github.com/pi-hole/pi-hole/files/2230928/diff.txt)

**Comment by dschaper** [comment]
There's a number of enhancements that we need to take a look at after the 4.0 release. We'll take a look at reworking a lot of things with the installer and clean up the process. 

Diffs are nice, but a Pull Request would be a lot more helpful in the process.

**Comment by dschaper** [comment]
Depending on how the installer is able to handle arguments at the curl step, this might be a good one to include as a `curl -sSL https://install.pi-hole.net | bash -s --skip_networking --` type process.

**Comment by ML35** [comment]
> Diffs are nice, but a Pull Request would be a lot more helpful in the process.

sorry, iam not so familar with git usage :) i will try

> this might be a good one to include as a curl -sSL https://install.pi-hole.net | bash -s --skip_networking -- type process.

maybe, but we need also redesign other vars in install script like QUERY_LOGGING or INSTALL_WEB that it all works the same way. anyway this var should use expirenced users and they can edit installed after downloading

**Comment by yubiuser** [comment]
Pi-hole came a long way since this has been discussed. Please open a new ticket if the issue persists.
