### ISSUE TITLE
Add the possibility to load a white list from a URL.

### ISSUE THREAD

**Issue by ZeroDot1** [pi-hole/pi-hole#2305]
I think it should be very easy for all users to load a whitelist from a URL and update it.
An example: https://gitlab.com/ZeroDot1/MalBlockerLists/raw/master/ZeroDotsWhiteList.txt

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
