### ISSUE TITLE
No file "/etc/pihole/pihole-FTL.conf" installed by default

### ISSUE THREAD

**Issue by jfb-pihole** [pi-hole/pi-hole#2309]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

At the completion of a basic installation, the user should have a commented-out /etc/pihole/pihole-FTL.conf file installed

**Actual behaviour:**

The default installation does not install such a file

**Steps to reproduce:**

Ran the master installer from curl, then checked out to Release 4.0 branch.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not applicable

**Troubleshooting undertaken, and/or other relevant information:**

Since this file is required to make any of the changes that are discussed in the FTLDNS section of the V4.0 documentation, it is likely that users may create one.  Having a file installed by default is recommended for two reasons:

1.  This becomes a good starting place for a user to remove comments or change variables, essentially a common template from which they all work, and 

2.  Simplifies support because all the installations start with this file in place - no back and forth about if the file is there, how to make a file, what to put in the file, etc.

> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by RamSet** [comment]
```
#Visit https://docs.pi-hole.net/ftldns/configfile/ for parameter explenations 
# SOCKET_LISTENING=localonly|all
# QUERY_DISPLAY=yes|no
# AAAA_QUERY_ANALYSIS=yes|no
# RESOLVE_IPV6=yes|no
# RESOLVE_IPV4=yes|no
# MAXDBDAYS=365
# DBINTERVAL=1.0
# DBFILE=/etc/pihole/pihole-FTL.db
# MAXLOGAGE=24.0
# FTLPORT=4711
# PRIVACYLEVEL=0|1|2|3
# IGNORE_LOCALHOST=no|yes
# BLOCKINGMODE=NULL|IP-AAAA-NODATA|IP|NXDOMAIN
# REGEX_DEBUGMODE=false|true
```

**Comment by dschaper** [comment]
If you can find the defaults that would be excellent.

**Comment by RamSet** [comment]
first option listed is the default. Second and so forth are the optional.

**Comment by technicalpyro** [comment]
```

#Visit https://docs.pi-hole.net/ftldns/configfile/ for parameter explenations  
# SOCKET_LISTENING=**localonly**\|all 
# QUERY_DISPLAY=**yes**\|no 
# AAAA_QUERY_ANALYSIS=**yes**\|no 
# RESOLVE_IPV6=**yes**\|no 
# RESOLVE_IPV4=**yes**\|no 
# MAXDBDAYS=**365** 
# DBINTERVAL=**1.0** 
# DBFILE=**/etc/pihole/pihole-FTL.db** 
# MAXLOGAGE=**24.0** 
# FTLPORT=**4711** 
# PRIVACYLEVEL=**0**\|1\|2\|3 
# IGNORE_LOCALHOST=**no**\|yes 
# BLOCKINGMODE=NULL\|IP-AAAA-NODATA\|**IP**\|NXDOMAIN 
# REGEX_DEBUGMODE=**false**\|true
```

based on docs these appear to be the defaults

**Comment by dschaper** [comment]
Thinking a template like the following:

```
#SOCKET_LISTENING=localonly

## Listen only for local socket connections or permit all connections
## Options: localonly, all

#QUERY_DISPLAY=yes

## Display all queries? Set to no to hide query display
## Options: yes, no

#AAAA_QUERY_ANALYSIS=yes

## Allow FTL to analyze AAAA queries from pihole.log?
# Options: yes, no

#RESOLVE_IPV6=yes|no

## Should FTL try to resolve IPv6 addresses to host names?
# Options: yes, no
```
