### ISSUE TITLE
Nslookup for pi shows weird name

### ISSUE THREAD

**Issue by timm088** [pi-hole/pi-hole#231]
When i run an nslookup on the ip address of the Pi, I get a weird server name response.
Is there any way to prevent/edit this?

Server:  005.free-counter.co.uk
Address:  192.168.1.105

Name:    005.free-counter.co.uk
Address:  192.168.1.105

**Comment by dschaper** [comment]
The way the Pi-Hole is designed is for `dnsmasq` to imitate the ad-serving sites and serve a blank HTML document in it's place. So the Pi-Hole needs to respond to DNS lookups for the ad-serving domains. As you have seen, this means that any query for the IP will reverse back to one of the ad-serving domains, in this case the first domain listed in `/etc/pihole/gravity.list` which is the hosts file that `dnsmasq` uses. I can flag this as a possible bug, is this behavior causing an issue on your network?

**Comment by timm088** [comment]
It doesnt seem to be, I guess i initially thought it was some sort of poisened dns, but yeh, you're exactly right in your assumption. 

To test, i made a file called dnsname.list, added that to dnsmasq.conf under the gravity.list entry. Within that list i named the server IP addresses 'something' and then, the nslookup responds with the name i specified. 

Probably safe to close.

**Comment by dschaper** [comment]
Okay, if you run into any problems feel free to open an issue. Thanks!

**Comment by marcmast** [comment]
Worked for me by editing `/etc/hosts`
