### ISSUE TITLE
SELinux Fedora 28 dnsmasq /var/log/pihole.log Permission Denied

### ISSUE THREAD

**Issue by cwmke** [pi-hole/pi-hole#2316]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**

`dnsmasq connects`

**Actual behaviour:**

`dnsmasq fails to connect with selinux set to enforcing`

**Steps to reproduce:**

* run setenforce 0
* go through installation
* run setenforce 1
* systemctl restart dnsmasq
* dnsmasq[1761]: cannot open log /var/log/pihole.log: Permission denied

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
*** [ DIAGNOSING ]: dnsmasq version
[i] 2.79

*** [ DIAGNOSING ]: Operating system
[✓] Fedora 28 (Twenty Eight)

*** [ DIAGNOSING ]: SELinux
[✗] Default SELinux: enforcing
[✗] Current SELinux: Enforcing

*** [ DIAGNOSING ]: Processor
[i] x86_64

*** [ DIAGNOSING ]: contents of /etc/dnsmasq.d

-rw-r--r--. 1 root root 1510 Jul 30 14:49 /etc/dnsmasq.d/01-pihole.conf
   addn-hosts=/etc/pihole/gravity.list
   addn-hosts=/etc/pihole/black.list
   addn-hosts=/etc/pihole/local.list
   localise-queries
   no-resolv
   cache-size=10000
   log-queries=extra
   log-facility=/var/log/pihole.log
   local-ttl=2
   log-async
   server=1.1.1.1
   server=1.0.0.1
   interface=enp2s0

*** [ DIAGNOSING ]: Pi-hole log
-rw-r--r--. 1 dnsmasq root 0 Jul 30 15:23 /var/log/pihole.log
   -----head of pihole.log------

**Troubleshooting undertaken, and/or other relevant information:**
* semanage fcontext -a -t dnsmasq_var_log_t '/var/log/pihole.log'
* restorecon -Rv '/var/log/pihole.log'
* #490 This is the other mention I was able to find but no solution for resolving it was mentioned.
## SELinux Log
`type=AVC msg=audit(1532962196.836:25179): avc:  denied  { open } for  pid=11279 comm="dnsmasq" path="/var/log/pihole.log" dev="dm-1" ino=6031481 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=unconfined_u:object_r:var_log_t:s0 tclass=file permissive=1`

`type=AVC msg=audit(1532962196.836:25180): avc:  denied  { setattr } for  pid=11279 comm="dnsmasq" name="pihole.log" dev="dm-1" ino=6031481
scontext=system_u:system_r:dnsmasq_t:s0 tcontext=unconfined_u:object_r:var_log_t:s0 tclass=file permissive=1`

**Comment by dschaper** [comment]
Thanks for the report. Since you are running in SEL Enforcing mode there will be modifications that you will need to apply, custom to your environment. We previously would automatically modify things like firewalld or SELinux, but we feel that modifications to the host security profile are not things to be done automatically or scripted. This would be good for a document on https://docs.pi-hole.net, but beyond that I don't think there is much we can do to mitigate the issue while still holding up good security principles.

**Comment by cwmke** [comment]
That's a logical way to go. Do you happen to have any ideas on what needs to happen for the log to become readable though? I noticed it was mentioned in the mentioned pull request but couldn't find how @PromoFaux was able to get it running.

I understand if it's outside of your support range since it's not really a Pi-hole bug.

**Comment by bcambl** [comment]
@cwmke it would require the creation of a _custom SELinux policy_. There is plenty of good documentation available on the internet on how this can be done. As @dschaper mentioned, we no longer soften system security via the installer for security reasons.  
(note: there are [changes planned in the future](https://pi-hole.net/2018/01/13/pi-hole-web-interface-the-next-generation/) that may help the project become more SELinux friendly)

**Comment by cwmke** [comment]
Thanks for the information. I'll keep an eye out for the future and try to figure out some SELinux rules.
