### ISSUE TITLE
My admin webpage is not showing the correct statics.

### ISSUE THREAD

**Issue by MadAntrax** [pi-hole/pi-hole#232]
Here is what I got if I type http://raspberry_ip/admin

http://i.imgur.com/t7miHzj.png

**Comment by jacobsalmela** [comment]
Could you paste the output of `ls -l /etc/pihole` and `tail /var/log/pihole.log`?

**Comment by MadAntrax** [comment]
root@raspberrypi:~# tail /var/log/pihole.log
tail: cannot open ‘/var/log/pihole.log’ for reading: No such file or directory


http://i.imgur.com/hHSpipV.png

**Comment by Mcat12** [comment]
Can out do ```ls -l /var/log```?

**Comment by jacobsalmela** [comment]
OK, so your Web interface is not showing stats because `/var/log/pihole.log` doesn't exist, which is where those stats come from.

Is this a fresh install or are you on DietPi or something else?

**Comment by Mcat12** [comment]
It looks like DietPi.

**Comment by MadAntrax** [comment]
Im using Raspian Jessie Lite

**Comment by jacobsalmela** [comment]
I would try just installing it again because the log file is not there and is needed to display the stats.

**Comment by jrtoman** [comment]
I think I am having a similar issue, but mine has stats that aren't updating as in they are always the same stats every time i visit the web gui. See attached pic. It appears though that the pi hole is blocking ads though.

pi@raspberrypi:~ $ tail /var/log/pihole.log
Jan 23 22:07:45 dnsmasq[412]: query[A] github.com from 192.168.1.1
Jan 23 22:07:45 dnsmasq[412]: forwarded github.com to 8.8.4.4
Jan 23 22:07:45 dnsmasq[412]: forwarded github.com to 8.8.8.8
Jan 23 22:07:45 dnsmasq[412]: reply github.com is 192.30.252.129
Jan 23 22:08:19 dnsmasq[412]: query[A] github-cloud.s3.amazonaws.com from 192.168.1.1
Jan 23 22:08:19 dnsmasq[412]: cached github-cloud.s3.amazonaws.com is <CNAME>
Jan 23 22:08:19 dnsmasq[412]: forwarded github-cloud.s3.amazonaws.com to 8.8.4.4
Jan 23 22:08:19 dnsmasq[412]: forwarded github-cloud.s3.amazonaws.com to 8.8.8.8
Jan 23 22:08:19 dnsmasq[412]: reply github-cloud.s3.amazonaws.com is <CNAME>
Jan 23 22:08:19 dnsmasq[412]: reply s3-1-w.amazonaws.com is 54.231.0.137



![capture](https://cloud.githubusercontent.com/assets/9121802/12533097/5556d328-c1eb-11e5-9804-b0c5940e453a.PNG)

**Comment by dschaper** [comment]
Thanks for the report, can you open a new issue so our tracking system can handle your case?

**Comment by dschaper** [comment]
@MadAntrax Were you able to reflash your uSD and do a reinstall?

**Comment by MadAntrax** [comment]
Solved, I had commented this:

log-queries
log-facility=/var/log/pihole.log

On my /etc/dnsmasq.conf, now the problem is solved :+1:

**Comment by PromoFaux** [comment]
Ah, was that something you had commented out yourself?

**Comment by Mcat12** [comment]
I think it was. This can be closed.

**Comment by PromoFaux** [comment]
Closing unless we hear otherwise from @MadAntrax
