### ISSUE TITLE
Failure to download FTL binary should stop script.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#2324]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10
---
**Expected behaviour:**

A failure to get the FTL binary should be a dependency that is checked before the bulk of the script runs. This will allow for a failure of the script and no modification of the target system. Will allow re-runs of the script to be easier, no need to have to edit `/etc/resolv.conf` to change the localhost entry to an upstream.

**Actual behaviour:**

FTL failures happen far in to the process after dependencies are installed and `resolv.conf` has already been modified to `127.0.0.1`.

**Steps to reproduce:**

Just run the installer or try to update.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Comment by Mcat12** [comment]
Pushed back to v4.2 so we can get v4.1 out soon.

**Comment by dschaper** [comment]
Fixed in #2600
