### ISSUE TITLE
Chronometer logo bug

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#2325]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

see pihole logo with output

**Actual behaviour:**

![2d09a34d2cc0f06de7169043f70a7af1b3c6c044](https://user-images.githubusercontent.com/15007183/43716185-232f00d8-9951-11e8-8b56-f40c3d3eb471.PNG)

**Steps to reproduce:**

run `pihole -c`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

for some reason debug gets stuck on `*** [ DIAGNOSING ]: Dashboard and block page`
dont know if this is another bug or unsupported os

https://paste.ubuntu.com/p/GJ9s4Fq8Jg/

**Troubleshooting undertaken, and/or other relevant information:**

for more info see https://discourse.pi-hole.net/t/chronometer-logo-all-over-the-place/11466/4

**Comment by dschaper** [comment]
Seeing same on my 4.0.
![screenshot from 2018-08-06 05-11-29](https://user-images.githubusercontent.com/2782850/43717326-0d10c1ac-993c-11e8-9016-1844fc02a818.png)
