### ISSUE TITLE
Installation fails without an apparent reason

### ISSUE THREAD

**Issue by killermosi** [pi-hole/pi-hole#2326]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Able to install and use Pi-hole on my Raspberry Pi

**Actual behaviour:**

Installation fails - the last line printed on the screen is `[i] Starting pihole-FTL service...` and then I am dumped back to the command prompt.

**Steps to reproduce:**

* Start the installation process the recommended way: `curl -sSL https://install.pi-hole.net | bash`
* Fill in the required info, use defaults, except opt out of lighthttpd
* Let the automated installation process start

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`h92wjtj2pa`

**Troubleshooting undertaken, and/or other relevant information:**

* I have also installed PiVPN on this Pi - not sure if this may conflict or not with Pi-hole.
* As noted above, lighttpd was not installed (I am already using Apache).
* The `pihole-FTL` service is not installed: `Unit pihole-FTL.service could not be found.`
* Trying to update or reinstall Pi-hole (`pihole -up` and `pihole -r`) produces the same result.

This is the end of the repair log:
```
  [✓] man pages installed and database updated
  [i] Systemd-resolved is not enabled
  [i] Restarting services...
  [i] Starting pihole-FTL service...pi@raspberrypi:~ $
```

Is there any additional information that can be useful? Additional log files and/or diagnostics?

**Comment by jacobsalmela** [comment]
According to the debug token, you seem to be on v4.0 for everything.  Was this a brand new install or a `pihole -up` update?

**Comment by killermosi** [comment]
This is a brand new install. I have tried `-up` and `-r`, but the update/repair hangs at exactly the same point.

**Comment by kukulich** [comment]
I have the some problem. I also disabled lighttpd.

**Comment by kucix** [comment]
Same here. I also disabled lighttpd.

```
root@vps1:/# pihole -r

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.2.8-1+0~20180725124257.2+stretch~1.gbp571e56
  [i] Repair option selected
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf

  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✗] Backing up index.lighttpd.html
        No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...
  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [i] Latest FTL Binary already installed (v4.0). Confirming Checksum...
  [i] Checksum correct. No need to download!

  [✓] man pages installed and database updated
  [i] Systemd-resolved is not enabled
  [i] Restarting services...
  [i] Starting pihole-FTL service...root@vps1:/#

```
```
root@vps1:/# systemctl status pihole-FTL
Unit pihole-FTL.service could not be found.

root@vps1:/# pihole restartdns
  [✗] Failed to start pihole-FTL.service: Unit pihole-FTL.service not found.

```

**Comment by Bluscream** [comment]
I have the same problem

root@minopia:/home/blu# pihole restartdns
  [✗] Failed to start pihole-FTL.service: Unit pihole-FTL.service not found.

**Comment by dschaper** [comment]
Which distribution are you using? It should be in `/etc/os-release` if it's a common one. I think there may be a systemd-sysvinit compatibility layer that is missing.

**Comment by Bluscream** [comment]
```
root@minopia:~# cat /etc/os-release
#PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by dschaper** [comment]
Can you check on the systemd-sysv compatibility package? `apt-cache policy systemd-sysv` please?

**Comment by Bluscream** [comment]
> Try running systemctl enable pihole-FTL and then pihole -r

```
root@minopia:/home/blu# systemctl enable pihole-FTL
pihole-FTL.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pihole-FTL
root@minopia:/home/blu# pihole -r

  [✓] Root user check
```

> `[✗] Update local cache of available packages`

Can i skip this step somehow?

**Comment by Mcat12** [comment]
You can temporarily edit `/etc/resolv.conf` to use an external DNS server until FTL comes online. Otherwise, you would have to mess with the install script at `/etc/.pihole/automated install/basic-install.sh`

**Comment by killermosi** [comment]
> Try running `systemctl enable pihole-FTL` and then `pihole -r`

This appears to be working - the repair script runs successfully:
```
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

  [i] The install log is located at: /etc/pihole/install.log
    Update Complete! 

  Current Pi-hole version is v4.0
  Current AdminLTE version is v4.0
  Current FTL version is v4.0
```
I will test if PiHole works correctly.

**Comment by killermosi** [comment]
After some unrelated issues, I can confirm that everything seems to be in working order with PiHole.

Still no idea on why the FTL service failed to install properly.

**Comment by Mcat12** [comment]
Is anyone else still having an issue? If so, run `pihole -d` for a debug token and share the output of `sudo service pihole-FTL status -l`

**Comment by TheAntimist** [comment]
Way late into this discussion, but I also had this issue but @Mcat12 's comment below, seems to have fixed it:

> Try running systemctl enable pihole-FTL and then pihole -r
