### ISSUE TITLE
Web Interface 4.0 installed, but showing Version v3.3 in browser.

### ISSUE THREAD

**Issue by evansan** [pi-hole/pi-hole#2328]
I was still getting the 404 error when attempting to update, so I ran `sudo pihole -r`.
Then run `pihole -v` tells me everything is updated to 4.0, but when I open the Web Interface from the browser, it still say it is v3.3. I've rebooted RPi.
log token: l9g2xp7x9f

<img width="526" alt="teampaper snap_2018-08-06 20-56-26 2x" src="https://user-images.githubusercontent.com/2133205/43748025-38b8fb4c-99bb-11e8-9ce4-030e538c576f.png">

**Comment by jacobsalmela** [comment]
Have you flushed your browser cache after updating?

**Comment by evansan** [comment]
Oops you are right, flushing the browser cache fixes it. Thank you, and sorry...
