### ISSUE TITLE
Display fault in piHole -t function (colors)

### ISSUE THREAD

**Issue by eejeel** [pi-hole/pi-hole#2330]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?: 3

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

In the pihole -t function the blocked URL must be displayed in red and the queries in white

**Actual behaviour:**

I miss the red and white lines in Pihole -t function
All loggings are displayed in grey lines in the SSH screen. See picture on https://pasteboard.co/Hy4rhTd.jpg with the old and the new version of PiHole

Cause:
In the tail function the retrieval of the IPv4/6 addresses from /etc/pihole/setupVars.conf is defined.
But this is not used for blocking anymore and so not logged in pihole.log. Now it is 0.0.0.0

This line in pihole is the cause:
    -e "s,(.*(gravity.list|black.list| config ).* is (${IPV4_ADDRESS%/*}|${IPV6_ADDRESS:-NULL}).*), ${COL_RED}&${COL_NC}," \

For my own I have changed it to
    -e "s,(.*(gravity.list|black.list| config ).* is (0.0.0.0).*),${COL_RED}&${COL_NC}," \

I don't have IPV6 so I think it must be (0.0.0.0|::). For me (0.0.0.0) works

But you have to make it universal depending on the blocking mode definition.

**Steps to reproduce:**

pihole -t

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Thanks for reporting this!

The coloring of the `tail` output was added in #1550 and @WaLLy3K may want to look at it again.
