### ISSUE TITLE
Broken install on Debian Wheezy

### ISSUE THREAD

**Issue by gerroon** [pi-hole/pi-hole#2335]
I am trying to install this on Debian x32 Wheezy  7.11
Server version: Apache/2.2.22 (Debian)

The instalation steps are as follows, then I do not see anything else. There is no init script installed, I do not see any pihole process running etc.

thanks

```
[i] Existing PHP installation detected : PHP version 5.6.36-1~dotdeb+7.1
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 417 updates available
  [i] It is recommended to update your OS after installing the Pi-hole! 

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Using interface: eth0
  [i] Using Google DNS servers
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.2.2/24
  [i] IPv6 address: 
  [i] Web Interface On
  [i] Web Server Off
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [i] Checking for netcat (will be installed)
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [i] Checking for idn2 (will be installed)
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [i] Checking for dns-root-data (will be installed)
  [i] Checking for resolvconf (will be installed)

  ```

**Comment by Mcat12** [comment]
Wheezy is explicitly not supported, as it is past its End Of Life (EOL) and is out of date.

**Comment by dschaper** [comment]
This would be a good time to update to at least Jessie, but you're going to find that Stretch is the best supported, not only our package, but just in general. Wheezy has been unsupported even by Debian for a long time now. As Mcat12 mentions, it's just too old to be able to reliably support anymore.

**Comment by gerroon** [comment]
Thanks for the replies, it is that if it works do not mess with it thingy. I might follow your recommendation.


thanks

**Comment by dschaper** [comment]
But based on that output you do have a large number of packages that could do for an `apt-get update`. You might be missing a number of security updates and stability improvements to the code.

**Comment by gerroon** [comment]
@dschaper I checked the missing updates, none seemed related to pihole packages, but thanks for the reminder.
