### ISSUE TITLE
update problem for FTL

### ISSUE THREAD

**Issue by MertcanGokgoz** [pi-hole/pi-hole#2336]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?: 5**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

![asdasdasd](https://user-images.githubusercontent.com/8042604/43829429-956092f4-9b07-11e8-9cee-33b19dd597f4.PNG)

pihole -up

I am trying to update via normal procedure. I get the following error every time. Like  https://github.com/pi-hole/pi-hole/issues/2324

`root@GatewayPi:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL not found
root@GatewayPi:~#`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Your debug token is: t9q6lqsdc8`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by LiloBzH** [comment]
Same here

**Comment by jticket1024** [comment]
I am still getting this problem. Even when I use pihole -r

Output:

  [✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
  [✗] FTL Engine not installed

**Comment by MertcanGokgoz** [comment]
update without any issue 

https://pastebin.com/eSAYRtFW

but looks like a developer version, why

**Comment by KevinRoebert** [comment]
> `sudo bash -x /etc/.pihole/automated\ install/basic-install.sh --unattended`

@PromoFaux  With the command from above, it works now.

**Comment by PromoFaux** [comment]
@mertcangokgoz

Check the following commands:

```
cd /etc/.pihole && git branch
cd /var/www/html/admin && git branch
cat /etc/pihole/ftlbranch
``` 

If any one of those is anything other than master, try `pihole checkout master` and that should put you on the 4.0 release channel

**Comment by PromoFaux** [comment]
@jticket1024 / @kevinroebert 

Ok, wasn't expecting that to fix things, rather show us where the installer went wrong on the initial run, however as it's fixed things... Great!

**Comment by MertcanGokgoz** [comment]
@PromoFaux I did not change it, I think it seems to have changed with https://github.com/pi-hole/pi-hole/issues/2336#issueComment-411571802 but I do not know

I changed it to "master" Thx

```
root@GatewayPi:~# cd /etc/.pihole && git branch
* development
  master
root@GatewayPi:/etc/.pihole# cd /var/www/html/admin && git branch
* devel
  master
root@GatewayPi:/var/www/html/admin# cat /etc/pihole/ftlbranch
development
```

**Comment by jacekmusial** [comment]
I had this issue, and couldn't repair. Why? Not enough space. Removing obsolete files resolved this issue :)

**Comment by biddster** [comment]
I had this problem and I just ran `curl -sSL https://install.pi-hole.net | bash` to reinstall (preserving existing settings).

Seems to have done the trick although seems like a sledgehammer to crack a nut.

**Comment by PromoFaux** [comment]
> @PromoFaux I did not change it, I think it seems to have changed with #2336 (comment) but I do not know

Strange, that should not have switched branches, as it just runs the install script, it's the same as running `curl -sSL https://install.pi-hole.net | bash`, just with an enhanced output (provded by `bash -x` to help troubleshoot any issues that may have been occuring. Anyway, glad that you're back on track.

For anyone else coming across this issue, running the install script again seems to fix this issue, however if you have any issues after trying that, feel free to open a new issue with as many details as possible, for example where the install script crashes out.

Cheers

**Comment by dmblack** [comment]
I had to run the update script 3 times for successful FTL update. Just adding for audit purposes.

**Comment by samvde** [comment]
FYI I had this error when updating pihole. In the end it was caused by a stale lock file on /var/www/html/admin/.git/index.lock (troubleshooted using sudo bash -x /etc/.pihole/automated\ install/basic-install.sh --unattended command).
Removed that, updated, works fine now.

Krgds
