### ISSUE TITLE
Ip returned for block url is 0.0.0.0

### ISSUE THREAD

**Issue by LiloBzH** [pi-hole/pi-hole#2337]
Hi

For Blocked page, i don't have the blocked page
PiHole return 0.0.0.0 with an nslookup for example !

root@rasp-domoticz:/etc/pihole# nslookup mld.ovh
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   1and1.com
Address: 0.0.0.0

**Comment by PromoFaux** [comment]
The default blocking method is now `NULL` (`0.0.0.0`) which is further explained on our docs page here:

https://docs.pi-hole.net/ftldns/blockingmode/

You can change it back to returning your Pi-hole's IP for the block page to work, however with the increasing spread of `https`, the block page itself is becoming less relevant, in that Pi-hole cannot serve the block page on a `https` request.

**Comment by LiloBzH** [comment]
ah ok so it's normal.
and it's true, problem with HTTPS is solved now ! (no page, no problem !)

Thank's for information :)
