### ISSUE TITLE
Change lighttpd port using ENV variable

### ISSUE THREAD

**Issue by mvillarejo** [pi-hole/pi-hole#2342]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
8
---
**Expected behaviour:**
lighttpd to listen in a custom port

**Actual behaviour:**
lighttpd only listens in port 80 and can not be changed

**Steps to reproduce:**
startting pihole with lighttpd

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
n/a

**Troubleshooting undertaken, and/or other relevant information:**
tried to modify but startup script (in docker) replaces it

**Comment by dschaper** [comment]
Is this for the `pihole/pihole` docker image? You can open the issue for that image at https://github.com/pi-hole/docker-pi-hole and it will be handled quicker.

**Comment by mvillarejo** [comment]
any update on this? does anyone know how to create a workaround? 
thanks

**Comment by Mcat12** [comment]
Custom ports will definitely come with the new API/web, but most likely not before then.
