### ISSUE TITLE
Impossible reinstall...

### ISSUE THREAD

**Issue by wcentic** [pi-hole/pi-hole#2351]
Today I want to tested this script...
OS: Centos 7
After first istallation, the script dos not worked properly,  the status is "Unknown" and "FTL offline".
I was deleted...
Now I want to install again... but no working, after the isntallation, the "pihole" commnd not working... absolutly not working...

[root@server ~]# curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

Error: No matching Packages to list
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking yum for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dialog
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for net-tools
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which

  [i] SELinux mode detected: Disabled
  [i] Using Google DNS servers
  [i] Static IP already configured
  [i] Found IPv6 GUA address, using it for blocking IPv6 ads
  [i] IPv4 address: 173.249.xxxxx
  [i] IPv6 address: xxxxxxxx
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for bind-utils
  [✓] Checking for cronie
  [✓] Checking for curl
  [✓] Checking for findutils
  [✓] Checking for nmap-ncat
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for libidn2
  [✓] Checking for psmisc
  [✓] Checking for lighttpd
  [✓] Checking for lighttpd-fastcgi
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cli (will be installed)
  [i] Checking for php-pdo (will be installed)
[root@server ~]# pihole
-bash: pihole: command not found

**Comment by bcambl** [comment]
Please provide the output from the following command:
```
uname -a
```

**Comment by bcambl** [comment]
Please try:
```
yum install -y php-common php-cli php-pdo
```

**Comment by wcentic** [comment]
[root@server ~]# yum install -y php-common php-cli php-pdo
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 185.69.232.245
 * cpanel-addons-production-feed: 185.69.232.245
 * base: ftp.hosteurope.de
Excluding mirror: mirror.de.leaseweb.net
Excluding mirror: mirror.nl.leaseweb.net
 * epel: mirror.spreitzer.ch
 * extras: ftp.hosteurope.de
 * ius: mirror.ehv.weppel.nl
 * remi-php70: remi.schlundtech.de
 * remi-php71: remi.schlundtech.de
 * remi-php72: remi.schlundtech.de
 * remi-safe: remi.schlundtech.de
 * updates: ftp.hosteurope.de
 * webtatic: uk.repo.webtatic.com
No package php-common available.
No package php-cli available.
No package php-pdo available.
Error: Nothing to do

**Comment by bcambl** [comment]
Ah, Looks like you have `remi-safe` enabled.  
Do you have any other PHP applications on this server other than Pi-hole?

Lets check what you have installed for php packages:
```
rpm -qa | grep php
```

**Comment by wcentic** [comment]
Nop... 
I was install and uninstall the Pi-hole 1 time... 

[root@server ~]# rpm -qa | grep php
cpanel-php56-horde-lz4-1.0.10-1.cp1158.x86_64
ea-php71-7.1.20-1.1.1.cpanel.x86_64
cpanel-php56-Horde-Form-2.0.13-1.cp1158.noarch
ea-php72-php-fileinfo-7.2.8-2.2.2.cpanel.x86_64
ea-php56-5.6.37-1.1.1.cpanel.x86_64
cpanel-php56-Mail-Mime-1.8.3-2.cp1158.noarch
ea-php72-php-opcache-7.2.8-2.2.2.cpanel.x86_64
ea-php55-php-xml-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-Date-Holidays-Ireland-0.1.3-2.cp1158.noarch
ea-php70-php-gd-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Denmark-0.1.3-2.cp1158.noarch
ea-php70-php-ioncube6-6.1.0-2.2.4.cpanel.x86_64
cpanel-php56-Net-Sieve-1.3.2-2.cp1158.noarch
ea-php55-php-calendar-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-File-Find-1.3.2-2.cp1158.noarch
ea-php56-php-bz2-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-5.6.30-3.cp1164.x86_64
cpanel-php56-Horde-Browser-2.0.12-1.cp1158.noarch
cpanel-php56-Horde-Cache-2.5.3-1.cp1158.noarch
cpanel-php56-Horde-Imsp-2.0.5-2.cp1158.noarch
cpanel-php56-Horde-Share-2.0.10-1.cp1158.noarch
cpanel-php56-Horde-Smtp-1.9.3-2.cp1158.noarch
ea-php71-php-common-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Secret-2.0.6-1.cp1158.noarch
ea-php72-php-mysqlnd-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-XML-Parser-1.3.4-2.cp1158.noarch
ea-php54-php-ftp-5.4.45-56.56.1.cpanel.x86_64
ea-php72-php-xmlrpc-7.2.8-2.2.2.cpanel.x86_64
ea-php70-php-xml-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-SOAP-0.13.0-2.cp1158.noarch
cpanel-php56-Date-Holidays-USA-0.1.1-2.cp1158.noarch
ea-php70-php-mcrypt-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Horde-JavascriptMinify-1.1.3-1.cp1158.noarch
ea-php55-php-fpm-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-XML-SVG-1.1.0-2.cp1158.noarch
ea-php55-php-sockets-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-ioncube5-5.1.1-8.8.4.cpanel.x86_64
ea-php55-5.5.38-6.6.1.cpanel.x86_64
cpanel-php56-Horde-Autoloader-2.1.2-1.cp1158.noarch
cpanel-php56-Horde-Xml-Element-2.0.4-1.cp1158.noarch
cpanel-php56-Horde-Constraint-2.0.3-1.cp1158.noarch
cpanel-php56-Horde-Prefs-2.7.6-1.cp1158.noarch
ea-php54-php-fpm-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-Horde-Timezone-1.0.11-1.cp1158.noarch
ea-php72-php-litespeed-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-mnemo-4.2.10-1.cp1158.noarch
ea-php71-php-fileinfo-7.1.20-2.2.2.cpanel.x86_64
ea-php54-php-pdo-5.4.45-56.56.1.cpanel.x86_64
ea-php70-php-devel-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Italy-0.1.1-2.cp1158.noarch
ea-php70-php-imap-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Sweden-0.1.3-2.cp1158.noarch
ea-php54-php-mysqlnd-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-DB-1.7.14-2.cp1158.noarch
ea-php55-php-exif-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-fileinfo-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-ioncube-5.1.2-1.cp1158.x86_64
cpanel-php56-Horde-Injector-2.0.5-1.cp1158.noarch
cpanel-php56-Net-SMTP-1.6.2-2.cp1158.noarch
cpanel-php56-Horde-Rdo-2.0.5-1.cp1158.noarch
cpanel-php56-Horde-ElasticSearch-1.0.2-2.cp1158.noarch
ea-php72-php-posix-7.2.8-2.2.2.cpanel.x86_64
ea-php-cli-0.2.0-7.7.1.cpanel.x86_64
cpanel-php56-Horde-Rpc-2.1.7-1.cp1158.noarch
ea-php56-php-xml-5.6.37-1.1.2.cpanel.x86_64
ea-php71-php-zip-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-HTTP-Request-1.4.4-2.cp1158.noarch
ea-php54-php-devel-5.4.45-56.56.1.cpanel.x86_64
ea-php70-runtime-7.0.31-1.1.1.cpanel.x86_64
cpanel-php56-Date-Holidays-Romania-0.1.2-2.cp1158.noarch
cpanel-php-composer-1.6.2-1.cp1158.noarch
cpanel-php56-Date-Holidays-Venezuela-0.1.1-2.cp1158.noarch
ea-php55-libc-client-2007f-13.13.2.cpanel.x86_64
ea-php70-php-mbstring-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Text-Figlet-1.0.2-2.cp1158.noarch
ea-php54-php-zip-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-HTTP-WebDAV-Server-1.0.0RC8-2.cp1158.noarch
ea-php56-php-zip-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Translation-2.2.1-1.cp1158.noarch
cpanel-php56-Horde-Stream-Filter-2.0.4-1.cp1158.noarch
cpanel-php56-Horde-Text-Diff-2.1.2-1.cp1158.noarch
cpanel-php56-Horde-Mail-2.6.3-1.cp1158.noarch
cpanel-php56-Horde-Oauth-2.0.1-2.cp1158.noarch
ea-php72-php-ftp-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-horde-5.2.10-4.cp1158.noarch
ea-php71-php-curl-7.1.20-2.2.2.cpanel.x86_64
ea-php54-php-posix-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-Mail-1.2.0-2.cp1158.noarch
ea-php70-php-posix-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Norway-0.1.2-2.cp1158.noarch
ea-php70-php-calendar-7.0.31-2.2.2.cpanel.x86_64
ea-php70-libc-client-2007f-13.13.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Russia-0.1.0-2.cp1158.noarch
ea-php55-php-mysqlnd-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-Net-UserAgent-Detect-2.5.2-2.cp1158.noarch
ea-php55-php-bcmath-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-HTTP-1.4.1-2.cp1158.noarch
ea-php56-php-sockets-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-sourceguardian-10.0-1.cp1158.x86_64
ea-php54-5.4.45-20.20.1.cpanel.x86_64
cpanel-php56-Horde-Token-2.0.9-1.cp1158.noarch
cpanel-php56-Date-1.4.7-2.cp1158.noarch
cpanel-php56-Horde-Log-2.2.0-1.cp1158.noarch
ea-php-cli-lsphp-0.2.0-7.7.1.cpanel.x86_64
cpanel-php56-Horde-Imap-Client-2.29.6-2.cp1158.noarch
cpanel-php56-Horde-Feed-2.0.1-2.cp1158.noarch
ea-php71-php-posix-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Crypt-2.7.3-2.cp1158.noarch
ea-php71-php-pdo-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-content-2.0.5-1.cp1158.noarch
ea-php72-runtime-7.2.8-1.1.1.cpanel.x86_64
ea-php56-php-ftp-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-imp-6.2.14-2.cp1158.noarch
ea-php72-php-zip-7.2.8-2.2.2.cpanel.x86_64
ea-php56-pear-1.10.1-12.12.10.cpanel.noarch
cpanel-php56-Net-DNS2-1.4.1-2.cp1158.noarch
ea-php54-php-litespeed-5.4.45-56.56.1.cpanel.x86_64
ea-php56-libc-client-2007f-13.13.2.cpanel.x86_64
ea-php72-7.2.8-1.1.1.cpanel.x86_64
ea-php55-php-posix-5.5.38-39.39.1.cpanel.x86_64
ea-php70-php-litespeed-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Ukraine-0.1.2-2.cp1158.noarch
cpanel-php56-Date-Holidays-Brazil-0.1.2-2.cp1158.noarch
ea-php70-php-mysqlnd-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Iceland-0.1.2-2.cp1158.noarch
ea-php70-php-zip-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-UNO-0.1.3-2.cp1158.noarch
ea-php70-php-soap-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Idna-1.0.4-1.cp1158.noarch
ea-php54-php-ioncube5-5.1.1-8.8.3.cpanel.x86_64
cpanel-php56-Console-Color-1.0.3-2.cp1158.noarch
ea-php55-php-fileinfo-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-HTML-Template-IT-1.3.0-2.cp1158.noarch
ea-php55-php-curl-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-fpm-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Role-1.0.1-3.cp1158.noarch
cpanel-php56-Horde-Text-Filter-2.3.4-1.cp1158.noarch
cpanel-php56-Horde-Vfs-2.3.2-1.cp1158.noarch
cpanel-php56-Horde-Css-Parser-1.0.10-1.cp1158.noarch
cpanel-php56-Horde-Editor-2.0.4-2.cp1158.noarch
cpanel-php56-Horde-Argv-2.0.12-1.cp1158.noarch
cpanel-php56-Horde-Stream-Wrapper-2.1.3-1.cp1158.noarch
cpanel-php56-Horde-Perms-2.1.7-1.cp1158.noarch
cpanel-php56-Horde-Image-2.3.5-1.cp1158.noarch
cpanel-php56-Horde-Service-Facebook-2.0.5-2.cp1158.noarch
ea-php71-php-xml-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-ListHeaders-1.2.4-1.cp1158.noarch
ea-php72-php-xml-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Dav-1.1.3-1.cp1158.noarch
ea-php72-pear-1.10.1-12.12.10.cpanel.noarch
ea-php56-php-posix-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-turba-4.2.14-1.cp1158.noarch
ea-php71-php-mysqlnd-7.1.20-2.2.2.cpanel.x86_64
ea-php54-php-common-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-Net-URL-1.0.15-2.cp1158.noarch
ea-php55-php-ftp-5.5.38-39.39.1.cpanel.x86_64
ea-php70-php-ftp-7.0.31-2.2.2.cpanel.x86_64
ea-php70-pear-1.10.1-12.12.9.cpanel.noarch
cpanel-php56-Date-Holidays-PHPdotNet-0.1.2-2.cp1158.noarch
cpanel-php56-Date-Holidays-Slovenia-0.1.2-2.cp1158.noarch
ea-php70-php-bcmath-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-SanMarino-0.1.1-2.cp1158.noarch
ea-php70-php-sockets-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Australia-0.2.1-2.cp1158.noarch
ea-php55-pear-1.10.1-12.12.8.cpanel.noarch
cpanel-php56-Horde-Socket-Client-2.1.1-1.cp1158.noarch
ea-php54-php-fileinfo-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-Net-FTP-1.3.7-2.cp1158.noarch
ea-php55-php-bz2-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-Cache-1.5.6-2.cp1158.noarch
ea-php56-php-mbstring-5.6.37-1.1.2.cpanel.x86_64
ea-php56-php-imap-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Exception-2.0.8-1.cp1158.noarch
cpanel-php56-Horde-Date-2.3.0-1.cp1158.noarch
cpanel-php56-Net-Socket-1.0.14-2.cp1158.noarch
cpanel-php56-Horde-Tree-2.0.4-2.cp1158.noarch
cpanel-php56-Horde-HashTable-1.2.4-1.cp1158.noarch
cpanel-php56-Horde-Queue-1.1.3-1.cp1158.noarch
cpanel-php56-Horde-Mime-2.9.5-1.cp1158.noarch
cpanel-php56-Horde-Data-2.1.4-1.cp1158.noarch
ea-php54-runtime-5.4.45-20.20.1.cpanel.x86_64
cpanel-php56-Horde-Lock-2.1.2-1.cp1158.noarch
ea-php71-php-ftp-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Itip-2.1.2-1.cp1158.noarch
ea-php71-pear-1.10.1-12.12.11.cpanel.noarch
cpanel-php56-Horde-Core-2.23.0-1.cp1158.noarch
ea-php72-php-cli-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-kronolith-4.2.16-1.cp1158.noarch
ea-php72-php-curl-7.2.8-2.2.2.cpanel.x86_64
ea-php56-runtime-5.6.37-1.1.1.cpanel.x86_64
cpanel-php56-Date-Holidays-0.21.8-2.cp1158.noarch
ea-php54-php-xml-5.4.45-56.56.1.cpanel.x86_64
ea-php72-php-gd-7.2.8-2.2.2.cpanel.x86_64
ea-php55-php-cli-5.5.38-39.39.1.cpanel.x86_64
ea-php70-php-cli-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Turkey-0.1.1-2.cp1158.noarch
cpanel-php56-Date-Holidays-Portugal-0.1.0-2.cp1158.noarch
cpanel-php56-Date-Holidays-Serbia-0.1.0-2.cp1158.noarch
ea-php70-php-fpm-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Spain-0.1.3-2.cp1158.noarch
ea-php70-php-fileinfo-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Pack-1.0.6-1.cp1158.noarch
ea-php54-pear-1.10.1-12.12.8.cpanel.noarch
cpanel-php56-PEAR-Command-Packaging-0.3.0-2.cp1158.noarch
ea-php55-php-ioncube5-5.1.1-8.8.3.cpanel.x86_64
cpanel-php56-File-Fstab-2.0.3-2.cp1158.noarch
ea-php55-php-imap-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-bcmath-5.6.37-1.1.2.cpanel.x86_64
ea-php56-php-gd-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-zendopt-7.0.0-1.cp1158.x86_64
cpanel-php56-Horde-Group-2.1.1-1.cp1158.noarch
cpanel-php56-Horde-Notification-2.0.4-1.cp1158.noarch
cpanel-php56-Horde-Compress-Fast-1.1.1-1.cp1158.noarch
cpanel-php56-Net-IMAP-1.1.2-2.cp1158.noarch
cpanel-php56-Horde-Kolab-Format-2.0.4-2.cp1158.noarch
cpanel-php56-Horde-Template-2.0.3-1.cp1158.noarch
cpanel-php56-Horde-Http-2.1.6-1.cp1158.noarch
cpanel-phppgadmin-5.1-1.cp1172.noarch
ea-php71-php-litespeed-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-SyncMl-2.0.3-2.cp1158.noarch
ea-php72-php-devel-7.2.8-2.2.2.cpanel.x86_64
ea-php56-php-litespeed-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-ingo-3.2.10-2.cp1158.noarch
ea-php54-php-cli-5.4.45-56.56.1.cpanel.x86_64
mod_php72w-7.2.7-1.w7.x86_64
ea-php70-php-common-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Japan-0.1.2-2.cp1158.noarch
ea-php70-php-curl-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Netherlands-0.1.3-2.cp1158.noarch
ea-php54-php-curl-5.4.45-56.56.1.cpanel.x86_64
cpanel-php56-File-1.4.1-2.cp1158.noarch
ea-php56-php-exif-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Util-2.5.7-1.cp1158.noarch
cpanel-php56-Horde-LoginTasks-2.0.7-1.cp1158.noarch
cpanel-php56-Horde-Pdf-2.0.3-2.cp1158.noarch
cpanel-php56-Horde-Support-2.1.5-1.cp1158.noarch
cpanel-php56-Horde-Service-Twitter-2.1.1-2.cp1158.noarch
ea-php72-php-common-7.2.8-2.2.2.cpanel.x86_64
cpanel-php56-nag-4.2.9-2.cp1158.noarch
ea-php56-php-devel-5.6.37-1.1.2.cpanel.x86_64
ea-php71-php-fpm-7.1.20-2.2.2.cpanel.x86_64
ea-php55-php-pdo-5.5.38-39.39.1.cpanel.x86_64
ea-php70-7.0.31-1.1.1.cpanel.x86_64
cpanel-php56-Date-Holidays-EnglandWales-0.1.5-2.cp1158.noarch
cpanel-php56-Date-Holidays-Germany-0.1.2-2.cp1158.noarch
ea-php70-php-exif-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Log-1.12.7-2.cp1158.noarch
ea-php55-php-gd-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-MDB2-2.4.1-2.cp1158.noarch
ea-php56-php-mcrypt-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Url-2.2.5-1.cp1158.noarch
cpanel-php56-Horde-Stream-1.6.3-1.cp1158.noarch
cpanel-php56-Horde-SpellChecker-2.1.3-1.cp1158.noarch
cpanel-php56-Horde-Icalendar-2.1.4-1.cp1158.noarch
cpanel-php56-Horde-Date-Parser-2.0.5-1.cp1158.noarch
ea-php71-runtime-7.1.20-1.1.1.cpanel.x86_64
cpanel-php56-Horde-SessionHandler-2.2.7-1.cp1158.noarch
ea-php72-php-fpm-7.2.8-2.2.2.cpanel.x86_64
ea-php56-php-common-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-XML-Serializer-0.20.2-2.cp1158.noarch
ea-php72-php-mbstring-7.2.8-2.2.2.cpanel.x86_64
ea-php55-php-devel-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-Horde-Mail-Autoconfig-1.0.3-1.cp1158.noarch
cpanel-php56-Date-Holidays-Czech-0.1.0-2.cp1158.noarch
ea-php70-php-xmlrpc-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Horde-CssMinify-1.0.2-2.cp1158.noarch
ea-php55-php-mcrypt-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-XML-RPC-1.5.5-2.cp1158.noarch
ea-php56-php-curl-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Serialize-2.0.5-1.cp1158.noarch
cpanel-php56-Horde-Text-Flowed-2.0.3-1.cp1158.noarch
cpanel-php56-Horde-Routes-2.0.5-1.cp1158.noarch
cpanel-php56-Horde-Db-2.3.1-1.cp1158.noarch
cpanel-php56-Horde-Controller-2.0.4-1.cp1158.noarch
ea-php71-php-devel-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Cli-2.0.6-2.cp1158.noarch
cpanel-php56-trean-1.1.5-1.cp1158.noarch
ea-php55-php-common-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-pdo-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-webmail-5.2.14-1.cp1158.noarch
cpanel-php56-Date-Holidays-Croatia-0.1.1-2.cp1158.noarch
ea-php70-php-iconv-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Date-Holidays-Finland-0.1.2-2.cp1158.noarch
ea-php56-php-mysqlnd-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Console-Table-1.1.5-2.cp1158.noarch
ea-php55-php-zip-5.5.38-39.39.1.cpanel.x86_64
ea-php56-php-calendar-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-Horde-Nls-2.2.0-1.cp1158.noarch
cpanel-php56-Horde-Alarm-2.2.7-1.cp1158.noarch
cpanel-php56-Horde-Xml-Wbxml-2.0.1-2.cp1158.noarch
cpanel-php56-Horde-History-2.3.6-1.cp1158.noarch
cpanel-php56-Horde-Mime-Viewer-2.1.3-1.cp1158.noarch
ea-php71-php-cli-7.1.20-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Crypt-Blowfish-1.1.1-1.cp1158.noarch
ea-php72-php-pdo-7.2.8-2.2.2.cpanel.x86_64
ea-php56-php-cli-5.6.37-1.1.2.cpanel.x86_64
cpanel-php56-timeobjects-2.1.2-1.cp1158.noarch
ea-php55-php-litespeed-5.5.38-39.39.1.cpanel.x86_64
ea-php70-php-pdo-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Services-Weather-1.4.7-2.cp1158.noarch
cpanel-php56-Date-Holidays-Austria-0.1.5-2.cp1158.noarch
ea-php70-php-bz2-7.0.31-2.2.2.cpanel.x86_64
cpanel-php56-Horde-Yaml-2.0.2-2.cp1158.noarch
cpanel-phpmyadmin-4.7.7-3.cp1166.noarch
ea-php55-php-mbstring-5.5.38-39.39.1.cpanel.x86_64
cpanel-php56-Auth-SASL-1.0.6-2.cp1158.noarch
ea-php56-php-iconv-5.6.37-1.1.2.cpanel.x86_64
ea-php55-runtime-5.5.38-6.6.1.cpanel.x86_64
cpanel-php56-Horde-Auth-2.1.12-1.cp1158.noarch
cpanel-php56-Horde-Compress-2.1.5-1.cp1158.noarch
cpanel-php56-Horde-Kolab-Session-2.0.1-2.cp1158.noarch
cpanel-php56-Horde-View-2.0.6-1.cp1158.noarch

**Comment by wcentic** [comment]
[root@server ~]# php --version
PHP 7.0.31 (cli) (built: Jul 23 2018 21:27:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.1.0 (), Copyright (c) 2002-2017, by ionCube Ltd.

[root@server ~]# which php
/usr/local/bin/php

and the newer isntallation, but the pihole command dos not work, and the web interface get the foloving erreor:

[root@server pihole]# curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

Error: No matching Packages to list
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking yum for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dialog
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for net-tools
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which


  [i] SELinux mode detected: Disabled
  [i] Using Google DNS servers
  [i] Static IP already configured
  [i] Found IPv6 GUA address, using it for blocking IPv6 ads
  [i] IPv4 address: 173.249.3.69/24
  [i] IPv6 address: 2a02:c207:2014:2679::1
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for bind-utils
  [✓] Checking for cronie
  [✓] Checking for curl
  [✓] Checking for findutils
  [✓] Checking for nmap-ncat
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for libidn2
  [✓] Checking for psmisc
  [✓] Checking for lighttpd
  [✓] Checking for lighttpd-fastcgi
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cli (will be installed)
  [i] Checking for php-pdo (will be installed)


Web error:
There was a problem applying your settings.
Debugging information:
PHP error (2): parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/settings.php:11

**Comment by wcentic** [comment]
Thx, installation has now been completed...
But...

Status: Unknown 
FTL offline

FTL Information
The FTL service is offline!
And the DNS not working!

**Comment by bcambl** [comment]
No problem.  
At this point you should be able to create a debug token with `pihole -d`

**Comment by wcentic** [comment]
[✓] Your debug token is: db3exppwv9

**Comment by bcambl** [comment]
Thank you. 
I just reviewed your debug log.  
As I mentioned earlier, it appears this server is running a full CPanel stack.
- `lighttpd` will not start because you already have `httpd` (apache) listening on port `80`
- `FTL` will not start because you already have `named` listening on port `53`

My suggestion is that you deploy Pi-hole on a different server that is not already hosting services on ports `80` and `53`.
