### ISSUE TITLE
Gravity will stay empty after update

### ISSUE THREAD

**Issue by Crazyfox68** [pi-hole/pi-hole#2359]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [v] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [v] The issue I am reporting can be *replicated*.
- [v] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`
3
![pihole](https://user-images.githubusercontent.com/42389895/44116038-aecf8f80-a00f-11e8-8946-53a1afa9dffa.JPG)

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**
the blocked domainnames are still give me 0 after being pulled into gravity.
there is no info into the adlists.list file. only a few Hashed lines. try to clear this file and updated the file once more with pihole -up.
still nothing getting into the gravity list. 

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
i have made a debug list because i don't known what else i can do at this moment.
`{Alphanumeric token}`
0wxgokweqw
**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by df8oe** [comment]
I have same issue here. I have upgraded from 3.x (don't know the exact version - but everything was working fine). Upgrade has finished successfully - no errors. It seems that FTL is now replacing dns_masq. I can see ftl is listening on some ports, e.g. 53 (netstat -tulpen) but nothing is blocked at all.

The only line I am wondering about is

*** [ DIAGNOSING ]: Pi-hole processes
[✗] dnsmasq daemon is inactive

Of course it is inactive - port 53 is already in use by pihole-FTL and so it cannot be startet. I have disabled autostar in /etc/default. I am using Raspbian jessie.

My debug token is i0mf4vmymd

Any hints for stepping forward welcome.

Many thanks for your efforts for this nice project!

**Comment by Mcat12** [comment]
@Crazyfox68 your `/etc/pihole/adlists.list` file is all commented out, so there is nothing for gravity to use. Uncomment the URLs or add new lists. You should be able to use the web interface to enable the lists again or add new ones.

@df8oe you don't appear to have any issues. Pi-hole successfully blocks domains if you direct queries at it according to the debug log. Open a new topic on https://discourse.pi-hole.net/ if you are unable to configure your network correctly. The dnsmasq section in the debug log will be removed in the next release.

**Comment by Mcat12** [comment]
According to the debug log, it was blocking correctly. Also, FTL does 99% of stuff the same as dnsmasq, so it does use the Pi-hole configs in `/etc/dnsmasq.d/`

**Comment by df8oe** [comment]
My path entry in dnsmasq.conf was:

conf-dir=/etc/dnsmasq.d/*.conf

This does not work using new pihole 4.0. I must correct the line to

conf-dir=/etc/dnsmasq.d/

and then pihole conf file in /etc/dnsmasq.d/ was used.

**Comment by Crazyfox68** [comment]
Hoi Mark,


Thank you answering my question.


I have decided to reconfigure my pihole with my Putty.

Update did NOT pulled the blocklist into my list by itself.

I have chosen for the easiest way to reconfigure my pi.


In the installation script there was a new line (question) about block domains to import into my pi.

anytime else stays the same. all of my personal settings are still there.


everytime is working fine now..

Maybe your can use my feedback in the near future for someone else.


Pi hole Rapsbian with the pi-hole version 4.0


See my installationLog that i attached.


best regards, Peter

________________________________

**Comment by Mcat12** [comment]
@df8oe That line should not have worked at all, according to the dnsmasq manual: http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
If you had a comma between the dnsmasq.d and *.conf, then it would have worked. FTLDNS does not change that behavior.
