### ISSUE TITLE
dhcpcd5 not available on Debian Buster | Alternatives to apply static IP

### ISSUE THREAD

**Issue by MichaIng** [pi-hole/pi-hole#2360]
Just wanted to give the hint that the `dhcpcd5` package is not available on Debian Buster repo. This is currently expected by Pi-hole installer, which on Buster fails silently. Needed a while to figure out why: `apt-get install dhcpcd5` fails, which leads to `set -e` script exiting, but error message is suppressed.

Interestingly on Raspbian Buster it is (still) available, thus this is really just an issue with Debian repo.

Possibly Debian plans to add dhcpcd7 to Buster, we will see 🤔: https://roy.marples.name/
___________________
Actually I was always wondering why Pi-hole installs a DHCP client, just to disable it. Maybe the intention was to have a failure safe method here? Otherwise `isc-dhcp-client` suppresses dhcpcd, thus would still acquire an IP via DHCP.

I am wondering, why Pi-hole does not set a static IP and disable dhcpcd as well as isc-dhcp-client (dhclient) via `/etc/network/interfaces`.
`iface eth0 inet static` disables dhclient and dhcpcd
`iface eth0 inet manual` allows only dhcpcd to acquire an IP
`iface eth0 inet dhcp` allows only dhclient to acquire an IP
Thus quite selective configurations possible.

Best from my point of view would be to remove `isc-dhcp-client` and `dhcpcd5` packages and set static IP via above method.
____________________
Would be nice as well, if via special install script argument of setupVar to skip static IP configuration completely, for users which have already applied a static IP themselves. But thats another topic 😉.

**Comment by pe0mot** [comment]
Just my 5c as a newby, just installed my pi-hole:
- dhcp client is good, it's for an easy setup first time, during this setup fixed IP is recommended and can be configured
- dhcp server is good, it can be used for replacing the one in the router so local clients are known by name in the Console

Just had 2 hours of battling with the ipv6 configuration of my AVM router, Asus accespoint, Pihole and my Win10. Conflicting ipv6 DNS by delays and caching :-) It's stable now (do not touch).

**Comment by dschaper** [comment]
`dhcpcd5` is how Raspbian sets the static IP address for all Raspberry Pi devices. This is a sore spot for us as we try to assist the user in setting a static IP for Pi-hole installs and on non Raspberry Pi devices it does tend to cause issues.

**Comment by oldjamey** [comment]
Rather than file a separate issue, I wanted to address/request official support as well for "unsupported" Debian-based Linux OSes.

In every case I have encountered, all you have to do is remove `dhcpcd5` from the required packages in `basic-install.sh`.  This should be done when you detect the release.  Then you can simply skip the DHCP functions, and jump straight to the static IP functions instead.

See my repo with a previous modified `basic-install.sh` that I used to install Pi-hole perfectly in Kali Linux on a Raspberry Pi 3, and later added support for updates by simply removing `dhcpcd5` from the required packages: [https://github.com/oldjamey/pi-hole-kali](https://github.com/oldjamey/pi-hole-kali)

**Comment by raidensnake** [comment]
I don't know about you but the package is there. it's even on the Debian official version.

https://packages.debian.org/buster/dhcpcd5

**Comment by MichaIng** [comment]
@raidensnake 
Ah great, the (re)added it. Was definitely not the case when I opened the issue.
Could be closed then.

@oldjamey 
It could be asked via whiptail if a static IP is already configured (or Pi-hole installer should do this), thus dhcpcd5 install + setup can be skipped.
Could be implemented similar to the new webserver install question, so whiptail popup + setup variable + installer option `--disable-install-static-ip`.

Should I turn the issue into a feature request? Could add a PR by times as well.
