### ISSUE TITLE
Issue blocking advertisements in app

### ISSUE THREAD

**Issue by TheRaspyBoi** [pi-hole/pi-hole#2363]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I expect that pi hole blocks advertising in app

**Actual behaviour:**

Using my smartphone, If I surf the internet the ads are blocked, if I use an app with advertising these are not blocked (With the previous version I did not have this problem)

Example
- With Pi Hole on
![screenshot_ki4a_20180815-145443](https://user-images.githubusercontent.com/40028925/44149264-b545e986-a09b-11e8-8d59-37e7f467cc20.png)

**************************************************************************************************************

- With Pi Hole off
![screenshot_chrome_20180815-145517](https://user-images.githubusercontent.com/40028925/44149267-b71efe46-a09b-11e8-82e8-139421a0a7f9.png)

**Steps to reproduce:**

Try using an app with some advertising and these should not be displayed

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

fmqtbjvp5u

**Troubleshooting undertaken, and/or other relevant information:**

Pi hole is configured perfectly, in fact it works on all devices except for the problem mentioned above

**Comment by rrobgill** [comment]
As you've observed your pi-hole is working correctly, I've just had a look through your submitted debug log which confirms this.

So let's see if we can figure out what's going on with this app.

One possibility is that the adservers being used are not in your blocklists. 
If your dns is set correctly on your phone, and blocking occurs in everything else, then it means that this app is bypassing the dns you have specified, and is either seeking another dns server, or even using hard-coded ips to collect the ads.

Can you please tell us the model of phone you're running, and exact version operating system?

Also, can you please tell us if this happens on all apps on the phone, or just in some (eg, does it show ads in your web browser as well?).

**Comment by TheRaspyBoi** [comment]
Thanks for the reply!

> One possibility is that the adservers being used are not in your blocklists.

I also thought about it after updating but not having touched anything in the settings and knowing that before the update everything worked fine I left the idea

> Can you please tell us the model of phone you're running, and exact version operating system

I have a Xiaomi Mi A1 with Android 8.1

> Also, can you please tell us if this happens on all apps on the phone, or just in some (eg, does it show ads in your web browser as well?).

This comes to me with all the apps that have advertising but with Chrome are blocked apparently

**Comment by rrobgill** [comment]
Have you checked that smart wifi-switcher is disabled in Settings : Wifi : Wifi-Preferences : Advanced ?

**Comment by TheRaspyBoi** [comment]
I checked and I do not have that

![screenshot_settings_20180816-092034_2](https://user-images.githubusercontent.com/40028925/44194359-0ccf0580-a136-11e8-8212-855c22b7200d.png)

These are the settings, the .3 in DNS is the raspberry. 

This morning I did some tests with other devices and I noticed that advertising on some applications is blocked, on others not:

- With Pi Hole on

![screenshot_strings_tuner_20180816-093138 2](https://user-images.githubusercontent.com/40028925/44194914-c5497900-a137-11e8-9c9e-3e5cb78e4c28.png)

**************************************************************************************************************

- With Pi Hole off

![screenshot_strings_tuner_20180816-093155 2](https://user-images.githubusercontent.com/40028925/44194918-c7133c80-a137-11e8-8710-1ab380dc3041.png)


I think Pi Hole works perfectly, just a few blocklists are missing. I have those who added Pi Hole to me automatically, are there any other blocklists to add?

![image](https://user-images.githubusercontent.com/40028925/44195034-23765c00-a138-11e8-8128-c25fbb53506f.png)

**Comment by TheRaspyBoi** [comment]
Ok, thank you very much for the support!
