### ISSUE TITLE
Installation issue, cause: piholeFTL cannot be started using systemctl, but can be start using int.d

### ISSUE THREAD

**Issue by realtebo** [pi-hole/pi-hole#2366]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

The installation of pihole ends starting its services

**Actual behaviour:**

Installation stops prematurely but without any error

```
[i] Restarting services...
[i] Starting pihole-FTL service ...
realtebo@192.168.1.224:~$
```
We are at system prompt, no errors, no infom but pihole services are not started

**Steps to reproduce:**

I can succesfully replicate in my machine using a VM with ubuntu-minimal 18.04, I am not able to reproduce the full creation of the base image on which i'm working when cloning VM, sorry. But I am available to to everythings needed to identify the source of this problem.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`pbq6hkac17`

**Troubleshooting undertaken, and/or other relevant information:**

Please note the following code

```
realtebo@192.168.1.224:~$ sudo systemctl status pihole-FTL
[sudo] password di realtebo: 
Unit pihole-FTL.service could not be found.

realtebo@192.168.1.224:~$ sudo service pihole-FTL status
[sudo] password di realtebo: 
Unit pihole-FTL.service could not be found.

realtebo@192.168.1.224:~$ sudo /etc/init.d/pihole-FTL status
[sudo] password di realtebo: 
[    ] pihole-FTL is not running

realtebo@192.168.1.224:~$ sudo systemctl start pihole-FTL
[sudo] password di realtebo: 
Failed to start pihole-FTL.service: Unit pihole-FTL.service not found.

realtebo@192.168.1.224:~$ sudo /etc/init.d/pihole-FTL start
[sudo] password di realtebo: 
Not running

chown: impossibile accedere a '/etc/pihole/dhcp.leases': File o directory non esistente
FTL started!

realtebo@192.168.1.227:~$ uname -a
Linux ubuntulocal 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

realtebo@192.168.1.224:~$ pihole-FTL --version
v4.0
```

**Comment by DL6ER** [comment]
What is the output of
```
systemctl --version
```
?

**Comment by realtebo** [comment]
```
realtebo@192.168.1.224:/etc/systemd/system$ systemctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

Note also, if useful

```
realtebo@192.168.1.224:/etc/systemd/system$ sudo systemctl enable pihole-FLL
[sudo] password di realtebo: 
Failed to enable unit: Unit file pihole-FLL.service does not exist.

realtebo@192.168.1.224:/etc/systemd/system$ sudo systemctl enable pihole-FTL
[sudo] password di realtebo: 
pihole-FTL.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pihole-FTL
realtebo@192.168.1.224:/etc/systemd/system$ sudo systemctl start pihole-FLL
[sudo] password di realtebo: 
Failed to start pihole-FLL.service: Unit pihole-FLL.service not found
```.

**Comment by realtebo** [comment]
Also note: 

```
  [i] Starting pihole-FTL service  ...

realtebo@192.168.1.224:~$ sudo systemctl start pihole-FTL
[sudo] password di realtebo: 
Failed to start pihole-FTL.service: Unit pihole-FTL.service not found.


realtebo@192.168.1.224:~$ sudo systemctl enable pihole-FTL
[sudo] password di realtebo: 
pihole-FTL.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pihole-FTL

realtebo@192.168.1.224:~$ sudo systemctl status pihole-FTL
[sudo] password di realtebo: 
● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

```

I will look again into installer code to find why service is not enabled.

**Comment by realtebo** [comment]
Ok. I 'resolved' simply switching two rows

```
    # Enable FTL
    start_service pihole-FTL
    enable_service pihole-FTL
```

became
```
    # Enable FTL
    enable_service pihole-FTL
    start_service pihole-FTL
```

I don't know if it safe for everyong this change. But, at least, I can insert in my forked repo and go on working.

**Comment by Mcat12** [comment]
Could you make a PR for this change, if you are able? Or we can discuss it and make the change.

**Comment by realtebo** [comment]
I'll do it.

I was just waiting for my last PR been accepted or not, just to bu seure to have understand your PR acceptance criteria.

But I'll do. 

I invite your team to think if there was a reason to start it before enabling. 
In my previous installations, this was not a problem, not a blocking problem, the script was not ending without errors, so I didn't noticed this because after this installation we do a lot of things, than reboot, so the service was running after next boot.

In this strange situation, the script falls and I cannot recover because in this state the VM cannot ping anyamore.

To patch, we forced 8.8.8.8 in the nameserver before the setup, after 'crashing' the setup we are enabling the service, restarting the setup, but it request a good amount of hour for testing. So a fix woul be a very good gift !

Thanks in advance for your work.
