### ISSUE TITLE
IP (2a00:5a60::ad2:0ff ) is invalid!

### ISSUE THREAD

**Issue by Bluscream** [pi-hole/pi-hole#2369]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

A success message

**Actual behaviour:**

A error message slide down
![grafik](https://user-images.githubusercontent.com/3318223/44222005-c055eb00-a172-11e8-9e5f-217301be996e.png)

**Steps to reproduce:**

1. Open http://minopia.de/admin/settings.php?tab=dns and login with 123
2. Enter 2a00:5a60::ad1:0ff and 2a00:5a60::ad2:0ff in custom 3 and 4 from https://adguard.com/de/adguard-dns/overview.html
3. Click Save

**Comment by rrobgill** [comment]
Are you by any chance copy and pasting the addresses from the website you gave?
If you do that, you are winding up with a trailing space after the address (you can see the space in your screenshot eg (2a00:5a60::ad2:0ff ).
Try removing the space at the end and it should work.

**Comment by Bluscream** [comment]
Okay thanks. I assumed all modern web inputs .strip() strings when there is no reason for whitespace
