### ISSUE TITLE
Error 60 Curl - when used to install Pi-Hole

### ISSUE THREAD

**Issue by darshanpatelh** [pi-hole/pi-hole#237]
Hello, I am getting Error 60 with the curl command when trying to install pi-hole. I tried to override it with -k but the script displays the same message again at the end of the install while executing curl command again. 

please help. 

thank you,

**Comment by dschaper** [comment]
Hi, that error is a SSL Certificiate error. Which distribution are you running?

**Comment by darshanpatelh** [comment]
I am on raspberry Pi - Raspbian

**Comment by dschaper** [comment]
And have you installed the latest ca-certificates package? Is this a fresh install of Raspbian?

**Comment by darshanpatelh** [comment]
I have Pi-hole running already and my dashboard for pi-hole stopped working. I tired to reinstall but no dice so i reinstalled Raspbian again and tried to Curl command and same error. How do i install the latest ca certificates?

**Comment by dschaper** [comment]
Can we get a screen shot of the errors that are being generated? Does `curl -L install.pi-hole.net | bash` successfully start the installation?

**Comment by darshanpatelh** [comment]
![1](https://cloud.githubusercontent.com/assets/16867819/12538481/fd6f8d2a-c29f-11e5-85e0-30f8e826fc55.png)

Here you go?

**Comment by dschaper** [comment]
Thanks, can you try `sudo apt-get update ca-certificates` and let me know if it updates the certificate store, or if it tells you that the package is already up to date?

**Comment by darshanpatelh** [comment]
![2](https://cloud.githubusercontent.com/assets/16867819/12538521/21177a3e-c2a1-11e5-953d-ada2c72930e5.png)

**Comment by darshanpatelh** [comment]
the command will not process!

**Comment by dschaper** [comment]
Sorry, try `sudo apt-get install ca-certificates`

**Comment by darshanpatelh** [comment]
No worries thank you for your help so far. 
it says newest version has already been installed  for ca-certificates

**Comment by dschaper** [comment]
I see now that the error is that the certificate is not yet valid. Have you set the correct system time and date on your installation?

**Comment by darshanpatelh** [comment]
Sweet Got it working! Thank you so much again for your help.
