### ISSUE TITLE
Installation completes but doesn't work and breaks DNS Resolution on Ubuntu 18.04

### ISSUE THREAD

**Issue by kaysond** [pi-hole/pi-hole#2370]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

`Installation completes and pihole runs without issue`

**Actual behaviour:**

`Installation completes without complaint, but then doesn't work. Also breaks DNS resolution`

**Steps to reproduce:**
On Ubuntu 18.04:

- Clone git repository
- Run basic-install.sh

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`t1nq81684o`

**Troubleshooting undertaken, and/or other relevant information:**

Installation completed without error: https://imgur.com/a/zMW8k64
(NB: I already have apache installed, so I declined to install lighttpd)

When I accessed the webhost I saw: [ERROR] There are no domain lists generated lists within /etc/pihole/! Please update gravity by running pihole -g, or repair Pi-hole using pihole -r.

However, running the web config, I see the error message `[ERROR] There are no domain lists generated lists within /etc/pihole/! Please update gravity by running pihole -g, or repair Pi-hole using pihole -r.`

When I run the repair, it fails on installing FTL: https://imgur.com/a/8MaBkO2

This is because the installer disables the systemd-resolved stub resolver per #2180 

So fixing that and running `pihole -r` works, but I still get the same error message on the web config.
Running `pihole -g` complains that it fails to start the pihole-FTL service. So it seems that the service didn't get installed for some reason, but it doesn't complain about it. Also FWIW (based on reading #2179) dnsmasq does not seem to be installed as a service. Not sure if this is related.

Also, I get the following security notice in mail about pihole commands being run `fserver : Aug 16 14:42:49 : www-root : user NOT in sudoers ; TTY=unknown ; PWD=/var/www/admin/scripts/pi-hole/php ; USER=root ; COMMAND=/usr/local/bin/pihole -q -adlist <mydomain>.com -bp`

Help would be appreciated!

**Comment by kaysond** [comment]
Also it would be nice if, when the repair or installation fails, pihole restored the resolved config so my DNS isn't broken.

**Comment by kaysond** [comment]
Ok so this is related to #2202. I had a binary for dnsmasq, but did not have the package installed, so there was no service. This caused the installation to silently fail (didn't realize it was a failure until it completed successfully, when I saw additional output lines). Installing the dnsmasq package, then reinstalling pi-hole appears to have fixed the problem!

**Comment by notDavid** [comment]
> Running pihole -g complains that it fails to start the pihole-FTL service

Not sure if this is related, but FYI: I had this exact issue, and in my case the problem was that dnsmasq was running & listening on port 53, which is why pihole-FTL couldn't start listening on the same port 53.

You can check if dnsmasq (or something else) is already listening on port 53 with:
`lsof -i -Pn | grep :53`

If that is the case, you can solve the problem with:
```
sudo systemctl disable dnsmasq
sudo systemctl mask dnsmasq
sudo systemctl restart pihole-FTL.service
```
