### ISSUE TITLE
Blank White/Blacklist on Web Interface

### ISSUE THREAD

**Issue by antt1995** [pi-hole/pi-hole#2371]
**In raising this issue, I confirm the following:**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Showing White/Blacklist

**Actual behaviour:**

Just showing add to list text box with a blank space below

**Steps to reproduce:**

All I did was update Pi-Hole

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

yl6j8ghsss

**Troubleshooting undertaken, and/or other relevant information:**
Checked with chrome 'F12' I am seeing one error on White and Blacklist pages the error is the same for both
[White-Black Error.log](https://github.com/pi-hole/pi-hole/files/2295442/White-Black.Error.log)

**Comment by Mcat12** [comment]
Issue moved to [pi-hole/AdminLTE #827](https://github.com/pi-hole/AdminLTE/issues/827) via [**ZenHub**](https://www.zenhub.com/)
