### ISSUE TITLE
Wrong calculation on main window..Blocked > 130%

### ISSUE THREAD

**Issue by MarkSau** [pi-hole/pi-hole#2372]
Hi,

today i wunder that my pihole is blocking more that requested:
![image](https://user-images.githubusercontent.com/22911084/44253119-ca253000-a1fe-11e8-9b0e-91f192ad05a1.png)
i think a reboot will help, but afterwards im not able to debug it...
which data do you need to troubleshoot this'?

**Comment by Mcat12** [comment]
This has already been fixed in development.
