### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by mrahmadt** [pi-hole/pi-hole#2373]
Hi

This is not an issue but rather a suggestion 

I think the web admin portal should use different port than 80 especially that we don’t need this port with Pi-Hole version 4

I’m sure many users like me want to run their own http server with port 80

Thanks

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
