### ISSUE TITLE
Dashboard shows over 100% blocked in version 4.0

### ISSUE THREAD

**Issue by coralgulf** [pi-hole/pi-hole#2375]
Since version 4.0 the dashboard begins correctly counting the blocks but adds them to >100% after some hours/days.

This behaviour was not seen in versions before.

Everything else works as expected.

**Comment by dschaper** [comment]
In order to help with troubleshooting we really need the information that is requested in the issue template. I'll close this issue out so that you can open a new issue with the template information filled out.

Thank you.
