### ISSUE TITLE
DNSMasq fails after update to Pihole 4

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#2379]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

a working upgrade

**Actual behaviour:**

DNSMasq failure, result in no internet at all.

**Steps to reproduce:**

In putty i used the command `pihole -up`, after the installation it gave an error in the end , see https://i.imgur.com/76DyUMV.png

In browser, i visit my pihole admin page and noticed the following error in the left top corner https://i.imgur.com/gmA4ol7.png

I tried the command `sudo service dnsmasq reload` which returns an error and saying i have to type the command `systemctl status dnsmasq.service` which i did and got following the error https://i.imgur.com/SIWC7gv.png

The log also confirms it is an DNSMasq issue "dnsmasq deamon is failed"  https://i.imgur.com/e0axd8W.png

This all happened after `pihole -up` so i assume the installation package of v4.0 is broken or something not correct configured.

Previous version worked flawless.

Tried `pihole -r` but didn't work.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by nomoreads** [comment]
Is there any simple way to revert to the previous installation as backup?
Or did the previous installation deleted already?

**Comment by DL6ER** [comment]
@nomoreads We do not use `dnsmasq` any more. It is completely replaced by `pihole-FTL` incorporating the most recent version of `dnsmasq`. You can uninstall `dnsmasq`.

**Comment by nomoreads** [comment]
@DL6ER Well the pihole upgrade just messed all up. See screenshots the DNSMasq deamon is failed. It has to do with the upgrade. No more internet after the pihole v4 upgrade. I disabled Pihole in my router now otherwise i wouldn't even be online right now.

So... in Pihole V4 in the admin panel it shows the DNS error in the left corner on top, so there IS a DNS issue due to Pihole v4 upgrade.

**Comment by DL6ER** [comment]
I understand this and am trying to find a solution for you. I just wanted to point out that `dnsmasq` is not used any more. Hence, you should also not try to start it. I'll report back soon.

**Comment by nomoreads** [comment]
@DL6ER Maybe in future version better communicate things like a message in the upgrade process that can't be ignored. Like a warning that pihole doesn't use DNSMasq anymore or other things have been removed. Because right now i am already busy with this issue for 6 hours, ended up removing pihole from my router untill i have a solution.
I wish i could simple revert back to old installation with a single click.

**Comment by DL6ER** [comment]
@jacobsalmela wrote this in his blog post (https://pi-hole.net/2018/08/06/pi-hole-v4-0-released-with-ftldns-improved-blocking-modes-regex-docker-and-more/#more-19078) but I agree that we could have been even more explicit about this.

**Comment by nomoreads** [comment]
I see, how can i revert to the previous version?

**Comment by DL6ER** [comment]
Reverting to a previous version is only supported with docker images if I'm not mistaken (I have never tried this myself).

Please try
```
echo "9.9.9.9" | sudo tee /etc/resolv.conf
pihole -r
```
and chose to repair your installation.

**Comment by nomoreads** [comment]
@DL6ER that worked, thanks.
Well, at least no error.
Weird, i already tried pihole -r before without succes.

What does echo "9.9.9.9" | sudo tee /etc/resolv.conf mean?

**Comment by DL6ER** [comment]
Okay, glad to see that you already found the solution. I overlooked this at first, but on a second look to your linked screenshot, I saw the

> Unable to get latest release location from GitHub error

and assumed that name resolution didn't work on your system and hence the downloading of the core component `pihole-FTL` failed.

Do you have any further issues now or is everything resolved?

**Comment by VexMex** [comment]
ok, sorry to roll this up but i have exactly this problem with my pihole that i use for my phone.

In my case tho its slightly different. I use ym raspi as a eth0-wlan0 bridge, means i use my pihole already on the br0 interface to just get onto my raspi

Now i wanted to update again after a while from 3.1 to 4.0, so i did my apt-get update and upgrade, then the pihole -up command, and saw the github problem and later the DNS resolution problem. SSH still worked, my bridge did too, but my raspi could not get again into the itnernet. i tried to reconfigure it to make sure its still working on the right interface etc but no change there. I did the repair, no change,  i found the Dnsmasq error on version 3.3 and used that, updated it to 2.6 as stated on another site with a fix, still nothing was working

Then i saw this here, tried it, but i couldnt get anything at all, not with 9.9.9.9, not with 8.8.8.8 not with 1.1.1.1, so im slightly at a miss ehre why its not working.

and yes, the rest is exactly as stated above by nomoreads, just that i have a wifi-bridge installed too

**Comment by dschaper** [comment]
If you still have an issue VexMex, please open a new report.
