### ISSUE TITLE
locale: Cannot set LC_CTYPE to default locale: No such file or directory

### ISSUE THREAD

**Issue by crunchie84** [pi-hole/pi-hole#238]
During install of pi-hole it generates locales and then starts interleaving all following commands with warnings about the LC_CTYPE and LC_ALL locale.

```
Generating locales (this might take a while)...
  en_GB.UTF-8... done
Generation complete.
Setting up ca-certificates (20141019+deb8u1) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

I do not know if this has any adverse affect on the pi-hole during execution so i'm reporting it here. 

My installation process:

Installed pi-hole yesterday on clean Raspbian Jessie -  Raspberry Pi 2 Model B. Upgraded all that i could beforehand using `apt-get update && apt-get upgrade`. Had some initial troubles with the install oneliner (`curl -L install.pi-hole.net | bash`) somehow the `/etc/pihole directory was not created; but downloading the install script and running it in sudo mode fixed that. Did end up with all the locale warnings during install tough.

Thanks for the great work! :+1:

**Comment by dschaper** [comment]
Try running `sudo raspi-config` and in the internationalization section, set your timezone and locales. You may need to reboot afterwards to get the changes to kick in. This isn't part of Pi-Hole, but part of Raspbian. Also, expand your root if you haven't already done so.

**Comment by crunchie84** [comment]
Hey thanks for the quick reply! Yes the expanding of root already got me ;-) will go into raspi-config to fix my i18n settings.

**Comment by dschaper** [comment]
Sure! I still get caught by the root partition too. I personally use Jessie Lite as a test environment...

**Comment by crunchie84** [comment]
okay going to close my issue since its not related to pi-hole itself. Thanks for responding!
