### ISSUE TITLE
installation issues on Utilite Pro / ARMv7 / Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by cipy** [pi-hole/pi-hole#2380]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`succesful installation`

**Actual behaviour:**

`
1. dns-root-data package is not present in this Ubuntu 12.04 LTS / precise
2. dns root data can be copied / cloned from 
https://packages.debian.org/source/stretch/dns-root-data
3. plus, this Ubuntu has an older $ php5-cgi --version
PHP 5.3.10-1ubuntu3.26 with Suhosin-Patch (cgi-fcgi) (built: Feb 13 2017 20:56:24)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
4. which means that PHP arrays must be initialized with array() and not with [], plus etc.
5. lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
6. uname -a
Linux utilite-desktop 3.0.35-cm-fx6-5.1 #232 SMP Wed Dec 11 10:51:48 IST 2013 armv7l armv7l armv7l GNU/Linux
`

**Steps to reproduce:**

`buy & try to install on http://www.compulab.co.il/utilite-computer/web/utilite-pro-specifications`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`390380wlj3`

**Troubleshooting undertaken, and/or other relevant information:**

`
1. remove dns-root-data from automated install/basic-install.sh to be able to install the software
-    PIHOLE_DEPS=(bc cron curl dnsutils iputils-ping lsof netcat psmisc sudo unzip wget idn2 sqlite3 libcap2-bin dns-root-data resolvconf)
+    PIHOLE_DEPS=(bc cron curl dnsutils iputils-ping lsof netcat psmisc sudo unzip wget idn2 sqlite3 libcap2-bin resolvconf)
2. in /var/www/html/pihole/index.php, replace [] from line 25 with array()
3. continue fixing php5.3.10 issues?!
`

**Comment by dschaper** [comment]
Ubuntu 12 is just far too old for us to support. This is a won't fix as there are limits to what we can do.
