### ISSUE TITLE
Pihole long term database connected but not filled

### ISSUE THREAD

**Issue by Marcel81** [pi-hole/pi-hole#2386]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**
Show long term data in the webinterface.

**Actual behaviour:**
No data is shown in long term data.

**Steps to reproduce:**

I'm running a Raspberry pi 3 with Stretch distro.
After an unsuccesfull upgrade to pihole 4.0 i uninstalled the old version and re-installed the pihole software from the original installer (bash command). One thing i had to do is run the FTL deamon as root otherwise it was not able to start the DNS software. Pi-Hole itself is working fine and blocks advertisements.
What i do miss is long term data (nothing is showing up in the long term section in the webinterface, not even a pup-up with an error).
After some google and testing i can see that the FTL is connected to the database (according to the logs), it also creates a new database when i stop the service, delete the database and start the service again. BUT the database file is **not** growing or updated. The FTL debug also shows 0 records in the database file. To be shure that it doesn't have got something to do with timing or something else i rebooted several times and waited for a day if to see if it suddenly got fixed. 
Unfortionately it doesn't.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

ekpcqnz03f

**Troubleshooting undertaken, and/or other relevant information:**
`{Steps of what you have done to fix this}`

> Uninstall and install (due to failing upgrade)
> Run the pihole -r several times (no luck)
> Delete .db file to see if it is recreating (it does)
> Look in Logs for errors (none found with this subject)
> Check growth and timestamp of db file (not increasing or updated)
> Run FTL debug to check for errors (none found)

**Comment by Marcel81** [comment]
I runned another test today. What if I restored my old .db file from a backup while running the older version (3.x) of pihole. It turns out that the old databse shows the correct information in the webinterface (the reading/showing of data is working) but the database is still not updated by the software. It looks like it has got to do with te new version of Pihole.

**Comment by knightphoenix** [comment]
I am not a dev but I have also noticed this in pi-hole 4.0 (fresh install) but i have found that if you change the date range from a custom range to an option in the right column (Today, Yesterday, Last 7 days etc) then the results show up. may be worth a try if you have not already tried this.

**Comment by Marcel81** [comment]
Hi @knightphoenix . Thx for the tip but this also did not work for me. When the data is stored it is showing up in the interface (i already tested with the import of a backup). It seems like my data is not stored in the db (since the new install).

**Comment by Mcat12** [comment]
It might have to do with you running FTL as `root` instead of `pihole`. Was this due to your system not supporting Linux capabilities?

**Comment by Marcel81** [comment]
New debug token: omacf77fz4

I’m not sure why it's only running as root, I saw this suggestion in another issue and it worked for me. Otherwise it's not able to start the FTL service. Looks like the elevation (sudo) of the normal pihole user is somehow not possible during boot. Let me know if I can do some more testing.

**Comment by Mcat12** [comment]
Try resetting FTL to run under `pihole`, then share the log (`/var/log/pihole-FTL.log`) and the service status (`sudo service pihole-FTL status -l`).

**Comment by Marcel81** [comment]
I restored the pihole file in /etc/init.d to run as pihole. 
Then restarted Pihole FTL. 

Output command: sudo service pihole-FTL status -l

● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)
   Active: active (exited) since Sun 2018-08-26 14:11:16 CEST; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9151 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)
  Process: 9157 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

Aug 26 14:11:15 raspberrypi systemd[1]: Starting LSB: pihole-FTL daemon...
Aug 26 14:11:16 raspberrypi pihole-FTL[9157]: Not running
Aug 26 14:11:16 raspberrypi pihole-FTL[9157]: chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Aug 26 14:11:16 raspberrypi su[9181]: Successful su for pihole by root
Aug 26 14:11:16 raspberrypi su[9181]: + ??? root:pihole
Aug 26 14:11:16 raspberrypi su[9181]: pam_unix(su:session): session opened for user pihole by (uid=0)
Aug 26 14:11:16 raspberrypi pihole-FTL[9157]: dnsmasq: cannot open or create lease file /var/lib/misc/dnsmasq.leases: Permission denied
Aug 26 14:11:16 raspberrypi systemd[1]: Started LSB: pihole-FTL daemon.

And the part from the Pihole-FTL log:
[2018-08-26 14:11:16.249] ########## FTL started! ##########
[2018-08-26 14:11:16.249] FTL branch: 
[2018-08-26 14:11:16.250] FTL version: v4.0
[2018-08-26 14:11:16.250] FTL commit: 8493df4
[2018-08-26 14:11:16.250] FTL date: 2018-08-05 13:40:30 -0700
[2018-08-26 14:11:16.250] FTL user: pihole
[2018-08-26 14:11:16.250] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2018-08-26 14:11:16.250]    SOCKET_LISTENING: only local
[2018-08-26 14:11:16.250]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2018-08-26 14:11:16.250]    MAXDBDAYS: max age for stored queries is 365 days
[2018-08-26 14:11:16.250]    RESOLVE_IPV6: Resolve IPv6 addresses
[2018-08-26 14:11:16.250]    RESOLVE_IPV4: Resolve IPv4 addresses
[2018-08-26 14:11:16.250]    DBINTERVAL: saving to DB file every minute
[2018-08-26 14:11:16.250]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2018-08-26 14:11:16.250]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2018-08-26 14:11:16.250]    PRIVACYLEVEL: Set to 0
[2018-08-26 14:11:16.250]    IGNORE_LOCALHOST: Show queries from localhost
[2018-08-26 14:11:16.250]    BLOCKINGMODE: Null IPs for blocked domains
[2018-08-26 14:11:16.250]    REGEX_DEBUGMODE: Inactive
[2018-08-26 14:11:16.250] Finished config file parsing
[2018-08-26 14:11:16.250] Compiled 0 Regex filters and 3 whitelisted domains in 0.1 msec (0 errors)
[2018-08-26 14:11:16.252] Database successfully initialized
[2018-08-26 14:11:16.252] Imported 0 queries from the long-term database
[2018-08-26 14:11:16.252]  -> Total DNS queries: 0
[2018-08-26 14:11:16.252]  -> Cached DNS queries: 0
[2018-08-26 14:11:16.252]  -> Forwarded DNS queries: 0
[2018-08-26 14:11:16.252]  -> Exactly blocked DNS queries: 0
[2018-08-26 14:11:16.252]  -> Unknown DNS queries: 0
[2018-08-26 14:11:16.252]  -> Unique domains: 0
[2018-08-26 14:11:16.253]  -> Unique clients: 0
[2018-08-26 14:11:16.253]  -> Known forward destinations: 0
[2018-08-26 14:11:16.253] Successfully accessed setupVars.conf

But based on the service status information i did test some new oppertunities:
What i first tried is to make a copy (.old) version of the leases file in /var/lib/misc directory. Restarted the service, same error.
Then i changed the ownership of only the "misc" directory (it was root:root) to pihole:pihole. Restarted the service and it worked! 

The good news is that the long term data is now also filled!

From here on i tried to roll back the ownership of the "misc" folder and it looks like it is still working (a bit strange f you ask me). I use my pi as DHCP server with dnsmasq, maybe this configuration and the existence of the leases file was hampering the service to start.

The error "Aug 26 14:11:16 raspberrypi pihole-FTL[9157]: chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory" is still there.

If the remaining error is no harm it's ok for me to close the issue.

**Comment by Mcat12** [comment]
If there are currently no issues, then that error can be ignored. I'm glad that solved the issue!

**Comment by Marcel81** [comment]
@Mcat12 thx for your help.
