### ISSUE TITLE
Pi-hole installer incorrectly detects IP address on multi-homed server with similar subnets

### ISSUE THREAD

**Issue by computergeek125** [pi-hole/pi-hole#2387]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`4/10`

---
**Expected behaviour:**

Pi-hole installer successfully detects network interface IP address on a multi-homed server

**Actual behaviour:**

The pi-hole installer can misdetect IP addresses when the string of the intended IP address also appears in other IP addresses

**Steps to reproduce:**

 - Install pi-hole on a server with text-overlapping IP addresses
\~\~OR\~\~
 - Run the snippet of installer code below

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-bash: pihole: command not found` :P Happened in install so I don't have one of these yet.

**Troubleshooting undertaken, and/or other relevant information:**

My target server for installation is also my network DHCP server (plus some more) and has VLAN or VPN interfaces for 6 subnets.  3/6 have the same text IP address beginning, as shown below:
```
ip -o -f inet addr show | grep "${IPv4bare}"
4: ens160.2    inet 10.0.1.1/27 brd 10.0.1.31 scope global noprefixroute ens160.2\       valid_lft forever preferred_lft forever
5: ens160.3    inet 10.0.1.187/26 brd 10.0.1.191 scope global noprefixroute ens160.3\       valid_lft forever preferred_lft forever
7: ens160.5    inet 10.0.1.109/27 brd 10.0.1.127 scope global noprefixroute ens160.5\       valid_lft forever preferred_lft forever
```

From what I can gather about how this section of the install script works (I'm working on [this issue in discourse](https://discourse.pi-hole.net/t/allow-bypassing-static-ipv4-address-screen-in-installer/11072)), I believe that the above command is supposed to only return one line of text, when in fact, it does not when these circumstances are met.  There appears to be an attempt later on that trims off any extra IPs by just popping the last IP off the list, but this does not intelligently select its target (my primary interface is first on the list).  Since the string representation of my default route and target interface (`10.0.1.1*`) appear in multiple IP addresses that have the same beginning, the algorithm grabs all three but gets the last one on the list instead of the first.

As shown by the below copy/paste scripting, my gateway and interface are detected properly, but the failure happens when trying to acquire the IP in CIDR notation.  

```bash
[me@domain.local@srv-aten ~]$ route=$(ip route get 8.8.8.8)
[me@domain.local@srv-aten ~]$     # Use awk to strip out just the interface device as it is used in future commands
[me@domain.local@srv-aten ~]$     IPv4dev=$(awk '{for (i=1; i<=NF; i++) if ($i~/dev/) print $(i+1)}' <<< "${route}")
[me@domain.local@srv-aten ~]$     # Get just the IP address
[me@domain.local@srv-aten ~]$     IPv4bare=$(awk '{print $7}' <<< "${route}")
[me@domain.local@srv-aten ~]$     # Append the CIDR notation to the IP address
[me@domain.local@srv-aten ~]$     IPV4_ADDRESS=$(ip -o -f inet addr show | grep "${IPv4bare}" |  awk '{print $4}' | awk 'END {print}')
[me@domain.local@srv-aten ~]$     # Get the default gateway (the way to reach the Internet)
[me@domain.local@srv-aten ~]$     IPv4gw=$(awk '{print $3}' <<< "${route}")
[me@domain.local@srv-aten ~]$ echo $route
8.8.8.8 via 10.0.1.30 dev ens160.2 src 10.0.1.1 cache
[me@domain.local@srv-aten ~]$ echo $IPv4dev
ens160.2
[me@domain.local@srv-aten ~]$ echo $IPv4bare
10.0.1.1
[me@domain.local@srv-aten ~]$ echo $IPV4_ADDRESS
10.0.1.109/27
[me@domain.local@srv-aten ~]$ # what now...?
[me@domain.local@srv-aten ~]$ echo $IPv4gw
10.0.1.30
[me@domain.local@srv-aten ~]$ ip -o -f inet addr show | grep "${IPv4bare}" |  awk '{print $4}' | awk 'END {print}'
10.0.1.109/27
[me@domain.local@srv-aten ~]$ ip -o -f inet addr show | grep "${IPv4bare}" |  awk '{print $4}'
10.0.1.1/27
10.0.1.187/26
10.0.1.109/27
[me@domain.local@srv-aten ~]$ ip -o -f inet addr show | grep "${IPv4bare}"
4: ens160.2    inet 10.0.1.1/27 brd 10.0.1.31 scope global noprefixroute ens160.2\       valid_lft forever preferred_lft forever
5: ens160.3    inet 10.0.1.187/26 brd 10.0.1.191 scope global noprefixroute ens160.3\       valid_lft forever preferred_lft forever
7: ens160.5    inet 10.0.1.109/27 brd 10.0.1.127 scope global noprefixroute ens160.5\       valid_lft forever preferred_lft forever
```

The hacky way to fix it is to change the command that acquires the address in CIDR notation, but I would guess that there might be a better way.  At the moment, I have only smoke tested this against the installer for my current CentOS multihomed server and it appears to work as planned (well... until you hit the OTHER bug/feature I was investigating).  End result there is that the static IP prompt screen now displays the correct IPv4 address corresponding to the gateway and interface.

```diff
diff --git a/automated install/basic-install.sh b/automated install/basic-install.sh
index 10e43b6..2e316a6 100755
--- a/automated install/basic-install.sh
+++ b/automated install/basic-install.sh
@@ -463,7 +463,7 @@ find_IPv4_information() {
     # Get just the IP address
     IPv4bare=$(awk '{print $7}' <<< "${route}")
     # Append the CIDR notation to the IP address
-    IPV4_ADDRESS=$(ip -o -f inet addr show | grep "${IPv4bare}" |  awk '{print $4}' | awk 'END {print}')
+    IPV4_ADDRESS=$(ip -o -f inet addr show | grep "${IPv4bare}/" |  awk '{print $4}' | awk 'END {print}')
     # Get the default gateway (the way to reach the Internet)
     IPv4gw=$(awk '{print $3}' <<< "${route}")
 }
```

Developers, do you want me to fully validate the hacky fix or investigate a better way of acquiring an IPv4 + CIDR and test that?  Note: the CentOS box is not my only machine.  I have other VMs (and some VM space to work with), and I think I have another Pi floating around here somewhere to use as test platforms.

Thanks in advance for your time and for reading through this.  Sorry for being so long-winded.

**Comment by Mcat12** [comment]
You can open a PR and we can review it, but it looks good to me.

@pi-hole/core-approvers

**Comment by dschaper** [comment]
PR would be nice, but if no response we can implement ourselves.
