### ISSUE TITLE
Pihole admin unavailable / lighttpd stopped

### ISSUE THREAD

**Issue by fsantiago07044** [pi-hole/pi-hole#2391]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

For lighttpd to be running and the admin web ui to be accessible.

**Actual behaviour:**

Lighttpd service stopped and failed. Won't start. On fedora 27, this started after a recent system update but I am unsure when it failed or what update caused it. When lighttpd is started manually from cl with -D:

root@localhost lighttpd]# lighttpd -Df /etc/lighttpd/lighttpd.conf
2018-08-26 16:37:00: (configfile.c.1451) pclose "cat external.conf 2>/dev/null"failed: Success 
2018-08-26 16:37:00: (configfile.c.1289) source: /etc/lighttpd/lighttpd.conf line: 95 pos: 1 parser failed somehow near here: (EOL) 
[root@localhost lighttpd]N

Note the config has never been touched after pihole install. It is the default. 

**Steps to reproduce:**

Unsure 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

e9ko774fhp

**Troubleshooting undertaken, and/or other relevant information:**

n/a

**Comment by sorvani** [comment]
Same error on two Pi-Hole systems. Except mine states line 94. pBoth systems running Fedora 28 and no customisations. 
```
[jbusch@pihole ~]$ sudo systemctl status lighttpd | cat
● lighttpd.service - Lightning Fast Webserver With Light System Requirements
   Loaded: loaded (/usr/lib/systemd/system/lighttpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-08-28 08:36:36 CDT; 14min ago
  Process: 2372 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
 Main PID: 2372 (code=exited, status=255)

Aug 28 08:36:36 pihole.jaredbusch.com systemd[1]: Started Lightning Fast Webserver With Light System Requirements.
Aug 28 08:36:36 pihole.jaredbusch.com lighttpd[2372]: 2018-08-28 08:36:36: (configfile.c.1451) pclose "cat external.conf 2>/dev/null"failed: Success
Aug 28 08:36:36 pihole.jaredbusch.com lighttpd[2372]: 2018-08-28 08:36:36: (configfile.c.1289) source: /etc/lighttpd/lighttpd.conf line: 94 pos: 1 parser failed somehow near here: (EOL)
Aug 28 08:36:36 pihole.jaredbusch.com systemd[1]: lighttpd.service: Main process exited, code=exited, status=255/n/a
Aug 28 08:36:36 pihole.jaredbusch.com systemd[1]: lighttpd.service: Failed with result 'exit-code'.
```

**Comment by sorvani** [comment]
My debug token: gvwri2fau7

**Comment by fsantiago07044** [comment]
Mine had a different line # only because when looking at it I had added a CR. Default untouched file also stated 94.

**Comment by sorvani** [comment]
I grabbed the previous version of `lighttpd.conf.fedora` and it did not help. Did not expect it to as this file has not changed in 11 months.

**Comment by sorvani** [comment]
I commented out the include to the `external.conf` and lighttpd starts.

**Comment by sorvani** [comment]
I uncommented that and then created an external.conf and lighttpd also loads.

So the issue is no external.conf existing at all.

```
sudo touch /etc/lighttpd/external.conf
```

**Comment by fsantiago07044** [comment]
Yep that did it. Confirmed.

**Comment by MujiSayed** [comment]
yep. mine wasn't working as well, used @sorvani solution and can confirm it works.

>sudo touch /etc/lighttpd/external.conf

**Comment by Mcat12** [comment]
If you are encountering this issue, share your lighttpd version: `lighttpd -v`

**Comment by sorvani** [comment]
On both systems I experienced this on.
```
[jbusch@pihole ~]$ sudo lighttpd -v
lighttpd/1.4.50 (ssl) - a light and fast webserver
```

**Comment by MujiSayed** [comment]
`[user@system etc]$ cat system-release
Fedora release 28 (Twenty Eight)`

`[user@system etc]$ lighttpd -v
lighttpd/1.4.50 (ssl) - a light and fast webserver`

`[user@system etc]$ pihole -v
  Pi-hole version is v4.0 (Latest: v4.0)
  AdminLTE version is v4.0 (Latest: v4.0)
  FTL version is v4.0 (Latest: v4.0)`

**Comment by Mcat12** [comment]
It appears that this may be a regression/bug in the latest version of lighttpd. Try downgrading lighttpd and see if it still has issues.

**Comment by webxI23** [comment]
I had the same probleme here after some updates on Centos (including lighttpd 1.4.50) :

-----------------------------------------------
[user@system]# cat /etc/system-release
CentOS Linux release 7.5.1804 (Core)

[user@system]# lighttpd -v
lighttpd/1.4.50 (ssl) - a light and fast webserver

[user@system]# pihole -v
  Pi-hole version is v4.0 (Latest: v4.0)
  AdminLTE version is v4.0 (Latest: v4.0)
  FTL version is v4.0 (Latest: v4.0)

-----------------------------------------------

Problem solved with "sudo touch /etc/lighttpd/external.conf"

**Comment by zaxxon64** [comment]
Same system-config as webxl23 for me. 
Same solution.

**Comment by Mcat12** [comment]
Can someone downgrade one version to see if they still have issues?

**Comment by sorvani** [comment]
Upgraded to 1.5 again and it is still working. Without that file.

Something weird here.

**Comment by sorvani** [comment]
oh my bad. i left the comment in lighttpd.conf. let me test better. sorry. bad mornign.

**Comment by sorvani** [comment]
Re-Confirmed, working with 1.4.49 but not with 1.4.50 for me on Fedora 28.

**Comment by Mcat12** [comment]
#2407 should fix this

**Comment by Mukrosz** [comment]
Cheers,
same issue with lighttpd version 1.4.51 on centos 7
"sudo touch /etc/lighttpd/external.conf" fixed it for me

**Comment by TheLinuxGuy** [comment]
had this problem on my first install too.

[root@pihole ~]# lighttpd -v
lighttpd/1.4.51 (ssl) - a light and fast webserver

**Comment by Rhadoo824** [comment]
I had the same issue, although the external.conf file existed (on CentOS 7.6). At this point I could only start it by commenting the line in lighttpd.conf. Then I removed the external.conf file, and re-created it with touch. When I reattempted to start the lighttpd service it worked without any other workaround.
