### ISSUE TITLE
Scientific Linux support 

### ISSUE THREAD

**Issue by StackKorora** [pi-hole/pi-hole#2396]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
8

---
Greetings,
This is a bit of a mix between a "Ack, what once worked is now broke" and a "feature request because I know I'm outside of the 'supported' realm".

In short, I have valid reasons for why I need to run Scientific Linux and am unable to run CentOS (another story for another day ;). For a long time, I've been running PiHole on Scientific Linux 7 without issue (although I apparently did edit my /etc/redhat-release to trick something at one point into thinking my server was CentOS...). Scientific is close enough to the supported CentOS that everything has just worked. Until I did an update tonight. After a lot of digging around I found the issue.  
Specifically this commit: 8ad37af70ee884c3d863755b32f87dea35681ae5  
Which impacts this file: /etc/.pihole/automated\ install/basic-install.sh  
Specifically the line (currently 257) which says `CURRENT_CENTOS_VERSION=$(rpm -q --queryformat '%{VERSION}' centos-release)`

Well, I may have faked /etc/redhat-release but I can't easily fake that (well, not without spinning my own rpm). So I just hard set that variable to 7 in the script and everything, of course, worked just fine.

My request, would it be possible to support Scientific Linux please? I'm pretty sure it wouldn't add much to do so (even if it is just a "you are running Scientific Linux - we will try but if this fails, well, its on you"). My limited testing shows that this should work:

Line 252: `elif grep -qiE 'centos|scientific' /etc/redhat-release; then`

And since you have the release information in that file anyway you could just remove the rpm check.

Line 257: `CURRENT_CENTOS_VERSION=$(grep -q 'release 7.' /etc/redhat-release && echo 7)`

Thoughts?
Thank you for taking the time to read my request.

PS: just for reference my release trickery
```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
$ cat /etc/redhat-release.bkp 
Scientific Linux release 7.5 (Nitrogen)
```

**Comment by bcambl** [comment]
I am planning a few changes to accommodate other Fedora/CentOS spins.   
I will take Scientific into consideration as well.
@StackKorora: could you please provide the output of the following on Scientific:
```
yum info epel-release
```

cheers.

**Comment by StackKorora** [comment]
I apologize for the delay. I had a heck of week. :-(

```
$ yum info epel-release
Loaded plugins: changelog
Installed Packages
Name        : epel-release
Arch        : noarch
Version     : 7
Release     : 11
Size        : 24 k
Repo        : installed
From repo   : epel
Summary     : Extra Packages for Enterprise Linux repository configuration
URL         : http://download.fedoraproject.org/pub/epel
License     : GPLv2
Description : This package contains the Extra Packages for Enterprise Linux (EPEL) repository
            : GPG key as well as configuration for yum.
```

Thank you so much for doing this. It is much appreciated.
