### ISSUE TITLE
Pi-hole fails to set static IP on Debian Stretch

### ISSUE THREAD

**Issue by stordoff** [pi-hole/pi-hole#2400]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Static IP set during the install is set and used

**Actual behaviour:**

DHCP IP from before the install is used, but Pi-hole Admin Console reports "Pi-hole IPv4 address: 192.168.1.2/24"

**Steps to reproduce:**

Clean install of Debian Stretch (9.5.0; tested in a Hyper-V VM) - netinstall, disabled desktop experience and print server
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade` to ensure up-to-date
`sudo apt-get install curl`
`curl -sSL https://install.pi-hole.net | bash`
Mostly accept defaults except set a static IP of 192.168.1.2/24, gateway 192.168.1.1, rather than the 192.168.1.110/24 supplied by DHCP
`sudo shutdown -r now` (post-install)
Discover that the admin console cannot be reached on 192.168.1.2, `ip a` reports `inet 192.168.1.110/24`
Accessing the Pi-hole Admin Console on 192.168.1.110 reports "Pi-hole IPv4 address: 192.168.1.2/24"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`riebw0wf0v`

**Troubleshooting undertaken, and/or other relevant information:**

I have extremely limited Debian experience so have been unable to undertake any troubleshooting.

**Comment by dschaper** [comment]
What does `/etc/network/interfaces` show as the configuration for the interface (manual/static/dhcp), and is there a `static` section with the .1.2 address in `/etc/dhcpcd.conf`?

**Comment by stordoff** [comment]
`/etc/network/interfaces`:

```
# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

`/etc/dhcpcd.conf`:

```
interface eth0
    static ip_address=192.168.1.2/24
    static routers=192.168.1.1
    static domain_name_servers=127.0.0.1
```

**Comment by dschaper** [comment]
When `/etc/network/interfaces` uses the line `iface eth0 inet dhcp` any configuration set in `/etc/dhcpcd.conf` is ignored. The solution is to either set the line to be `iface eth0 inet manual`, or remove the configuration from `/etc/dhcpcd.conf` and edit `/etc/network/interfaces` to set the static IP address with that file.

**Comment by stordoff** [comment]
OK, changing `iface eth0 inet dhcp` to `iface eth0 inet manual` fixes the problem.

I recreated the VM (exactly according to the steps above) in an attempt to fault-find, and noted the following:
Immediately prior to Pi-hole installation: `/etc/network/interfaces` is set to `iface eth0 inet dhcp` (as above); `/etc/dhcpcd.conf` does not exist
Immediately after to Pi-hole installation: `/etc/network/interfaces` is set to `iface eth0 inet dhcp`; `/etc/dhcpcd.conf` is set to exactly as above
After rebooting: `/etc/network/interfaces` is set to `iface eth0 inet dhcp`; `/etc/dhcpcd.conf` is set to exactly as above

It _appears_ that Pi-hole is not writing `/etc/network/interfaces`, but I have no idea what should trigger that.

**Comment by dschaper** [comment]
We don't modify the `/etc/network/interfaces` file as that is pre-set by Raspbian to be `manual`. The issue that we come across is how to set a static IP address on the myriad of distributions and networking daemons that Pi-hole can be installed on to. Glad this particular issue was solved, let us know if you have any further issues.

**Comment by stordoff** [comment]
Cool, that makes sense (can I suggest a note on the supported OS list? - I just assumed it would work due to Debian 9 being a supported OS). Thanks for your help.
