### ISSUE TITLE
Pi-hole on Raspberry / Odroid & CentOS 7

### ISSUE THREAD

**Issue by w3bservice** [pi-hole/pi-hole#2402]
Hello, first a thank you to you, great work. I've installed the Pi-Hole on a Raspberry / Odroid with CentOS7 over the weekend. In your installscript, the package centos-release is explicitly queried, but the release name has changed, centos-userland-release.armv7hl. What might be helpful, is only the query of the packages, yes / no. There are also other repo offering PHP7. Or if you use your own repos, or as in the case of CentOS7 on Raspberry https://armv7.dev.centos.org/repodir/epel-pass-1/ (epel) https://armv7.dev.centos.org/ repodir / community-php72-testing / (Remi).
THX Joerg

**Comment by bcambl** [comment]
Please review my comment regarding dev/testing repos: https://github.com/pi-hole/pi-hole/issues/2365#issuecomment-414505184  
I have also made some changes for the next release to allow users to _opt-in_ to a _unsupported installation_ here: https://github.com/pi-hole/pi-hole/pull/2398.  

Users wanting to install on CentOS on ARM will need to configure EPEL/Remi manually prior to executing the install script as we do not want to script installing from dev/test repos.  
Until there are stable CentOS7 ARM repos for EPEL/Remi, the installer will only support CentOS7 on x86 with Fedora being the preferred RPM based distro for ARM systems.
