### ISSUE TITLE
Too many local records

### ISSUE THREAD

**Issue by ceozero** [pi-hole/pi-hole#2404]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
No local connection log is logged.`{A detailed description of what you expect to see}`

**Actual behaviour:**
Too many local connection records.
`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/22513657/44997680-b9d4c980-afe2-11e8-9b20-cf31881f8d7d.png)

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

![image](https://user-images.githubusercontent.com/22513657/44997685-c822e580-afe2-11e8-9bd1-f5e55309bc14.png)

DHCP used by cloud server, I can't modify my resolv.conf, because it will be reset by 127.0.0.1.

How do I solve this problem? Can I close the local log? Or what has been resetting resolv.conf?

**Comment by Mcat12** [comment]
`resolv.conf` is handled by another service, usually `resolvconf`, not Pi-hole.

Pi-hole will log all queries that it resolves, so if it gets a lot of queries for those local domains, then it will log them.

**Comment by ceozero** [comment]
@Mcat12 No matter how I modify it. Will be covered by 127.0.0.1

**Comment by Mcat12** [comment]
Pi-hole does not do that, a utility such as `resolvconf` does that (this is usually documented in the `resolv.conf` file itself).

**Comment by ceozero** [comment]
When I unloaded pihole. Resolv.conf will not be covered. Because cloud servers use DHCP, I can't change them into static IP. @Mcat12

**Comment by Mcat12** [comment]
This does not appear to be a Pi-hole issue, or a Pi-hole bug. Please research the service that handles the `resolv.conf` file. You can also contact the hosting provider and ask them how to change the DNS server the system uses.

**Comment by ceozero** [comment]
![image](https://user-images.githubusercontent.com/22513657/45133127-47244380-b1c6-11e8-8d15-6e4dfbc14194.png)

**Comment by ceozero** [comment]
@Mcat12 I think I found a way.

The same code was found in the service installation file. Service installation will cover resolvconf.
