### ISSUE TITLE
Whitelist / Blacklist Web Interface Blank

### ISSUE THREAD

**Issue by DaBomby** [pi-hole/pi-hole#2405]
Ever since upgrading to v4.x, it appears that the whitelist and the blacklist sections of the web interface are not showing any of the previous entries. They also do not show any newly added entries. As a result, you cannot select previous entries to delete from either list.

Checking the /etc/pihole/whitelist.txt file shows that there are entries there. It also shows that any newly added entries from the web interface are added to the txt file.

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

This seems obvious, but here goes. Open the web interface section related to the whitelist. Have the default behavior display any existing FQDNs that are whitelisted. Additionally, if you add a new item to the list, have it then display the newly added item to the list.

**Actual behaviour:**

See above.

**Steps to reproduce:**

See above.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

kiplffxgq3

**Troubleshooting undertaken, and/or other relevant information:**

See above.

**Comment by Mcat12** [comment]
The issue template helps you help us by giving us enough information to debug the issue. Right now there are not enough details to debug your issue. I've added the template back to your issue, and with it filled out (especially the debug token), we can start to debug your issue.

**Comment by DaBomby** [comment]
@Mcat12 I have updated the posting and jumped through the hoops, as requested.

**Comment by DaBomby** [comment]
This issue seems similar. 

https://github.com/pi-hole/pi-hole/issues/2321

**Comment by technicalpyro** [comment]
Have you cleared your browser cache?

**Comment by DaBomby** [comment]
Here is another similar issue.

https://github.com/pi-hole/AdminLTE/issues/827

**Comment by DaBomby** [comment]
@technicalpyro I have tried is a second browser, it is working there. I will clear the cache in the primary browser later and try again. Not sure why the content would be cached after the upgrade of the Pi-Hole. This only started after upgrading to version 4.x.

**Comment by technicalpyro** [comment]
this was a known issue with the transition to 4.0 as the JavaScript was changed.  please clear your cache.

**Comment by dschaper** [comment]
Closed, stale.
