### ISSUE TITLE
lighttpd service crashes and won't restart on Orange Pi Zero H2+

### ISSUE THREAD

**Issue by Xeoncross** [pi-hole/pi-hole#2406]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`lighttpd` running stable and restarting correctly in cases of failure.

**Actual behaviour:**

`lighttpd` seems to fail to start/restart on an `Orange Pi Zero H2+`. I've had this happen once when powering down and restarting the unit, as well as simply leaving the unit running all night.

![screen shot 2018-09-04 at 1 21 09 pm](https://user-images.githubusercontent.com/56460/45050170-351b9700-b046-11e8-8be4-d6fc35db10a3.png)

**Steps to reproduce:**

This is the tough part. Restarting the device and leaving it running for hours is the only way I can reproduce this. Killing the service (or a graceful restart) seems to work fine.

```
root@orangepizero:/home/david# service lighttpd stop
root@orangepizero:/home/david# service lighttpd start
root@orangepizero:/home/david# service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-09-04 18:38:47 UTC; 3s ago
  Process: 9751 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 9760 (lighttpd)
    Tasks: 6 (limit: 1008)
   CGroup: /system.slice/lighttpd.service
           ├─9760 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─9769 /usr/bin/php-cgi
           ├─9770 /usr/bin/php-cgi
           ├─9771 /usr/bin/php-cgi
           ├─9772 /usr/bin/php-cgi
           └─9773 /usr/bin/php-cgi

Sep 04 18:38:46 orangepizero systemd[1]: Starting Lighttpd Daemon...
Sep 04 18:38:47 orangepizero systemd[1]: Started Lighttpd Daemon.
root@orangepizero:/home/david# htop
root@orangepizero:/home/david# killall lighttpd
root@orangepizero:/home/david# service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2018-09-04 18:40:04 UTC; 3s ago
  Process: 9760 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
  Process: 9751 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 9760 (code=exited, status=0/SUCCESS)

Sep 04 18:38:46 orangepizero systemd[1]: Starting Lighttpd Daemon...
Sep 04 18:38:47 orangepizero systemd[1]: Started Lighttpd Daemon.
root@orangepizero:/home/david# service lighttpd restart
root@orangepizero:/home/david# service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-09-04 18:40:14 UTC; 1s ago
  Process: 9851 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 9860 (lighttpd)
    Tasks: 6 (limit: 1008)
   CGroup: /system.slice/lighttpd.service
           ├─9860 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─9869 /usr/bin/php-cgi
           ├─9870 /usr/bin/php-cgi
           ├─9871 /usr/bin/php-cgi
           ├─9872 /usr/bin/php-cgi
           └─9873 /usr/bin/php-cgi

Sep 04 18:40:14 orangepizero systemd[1]: Starting Lighttpd Daemon...
Sep 04 18:40:14 orangepizero systemd[1]: Started Lighttpd Daemon.
root@orangepizero:/home/david# 
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`zqq7mrrhb6`

**Troubleshooting undertaken, and/or other relevant information:**

If I `apt-get remove --purge lighttpd` then re-run the installer (`curl -sSL https://install.pi-hole.net | bash`) everything seems to work fine again.

This is a brand new device. No changes have been made to the system or other applications installed. Fresh install of Ubuntu from Armbian.

```
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by Mcat12** [comment]
Have you tried posting on lighttpd's forums?

**Comment by dschaper** [comment]
Closing for stale/no-response
