### ISSUE TITLE
Graph of retrieval times of forwarded requests

### ISSUE THREAD

**Issue by dajappie** [pi-hole/pi-hole#2409]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

New feature: Graph of DNS retrieval timings (forwarded only, cache should be very neglible)

**Actual behaviour:**

No such graph is currently available

**Steps to reproduce:**

In the query log, column Reply, the retrieval times of the forwarded requests are currently included textually. If they are also stored in a database they can be used in a graph.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n/a

**Troubleshooting undertaken, and/or other relevant information:**

n/a

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
