### ISSUE TITLE
Couchtuner Ads

### ISSUE THREAD

**Issue by le0nard0** [pi-hole/pi-hole#241]
So often use couchtuner.ch . It looks like Pi-hole is replacing the ads quite nicely, including the ones that appear on top of the videos. 

However there empty containers remain, which means I still have to close them to hit play. Is there any way to change the "z" or layer that the ad appears on, so that the video loads over top and they don't block the play button?

I don't know these languages (yet) but I'll give them a shot eventually. Just thought I'd ask.  
##

**Comment by dschaper** [comment]
Currently the Pi-Hole just substitutes the advertisements with a blank html file. So the containers still remain. I'll mark this as an enhancement request to see if there is something we could do to add this ability in the future. Thanks for the request.

**Comment by Mcat12** [comment]
Related to #264?

**Comment by PromoFaux** [comment]
closing due to couchtuner.ch no longer existing! (We can reopen if I'm wrong...)
