### ISSUE TITLE
 /etc/pihole/adlists.list permission problem

### ISSUE THREAD

**Issue by DrGeoff** [pi-hole/pi-hole#2413]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
The Pi-hole admin page should work

**Actual behaviour:**
[ERROR]: There are no adlist URL's found within /etc/pihole/adlists.list

**Steps to reproduce:**
Fresh install on Raspberry Pi with all the latest updates. Point a webbrowser at http://<piholeIP>/admin/

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
Not provided

**Troubleshooting undertaken, and/or other relevant information:**
Looking in /var/log/lighttpd/error.log shows
(mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  file(/etc/pihole/adlists.list): failed to open stream: Permission denied in /var/www/html/pihole/index.php on line 120

The permissions on /etc/pihole/adlists.list are
$ sudo ls -al /etc/pihole/adlists.list
-rw------- 1 root root 381 Sep 15 17:42 /etc/pihole/adlists.list

**Comment by Mcat12** [comment]
Have you changed the default permissions for new files? On a new install, I see this:
```
-rw-r--r--. 1 root   root         381 Sep 15 21:05 adlists.list
```

**Comment by DrGeoff** [comment]
After much searching (including a complete system reinstall) I finally remembered to check my bashrc. And yes, there is a umask setting.

umask 0077

So the pi-hole install script is relying on a different umask?  Could you tell me what the default umask normally is?

**Comment by DrGeoff** [comment]
The following provided a successful install
```bash
$ sudo -s
# umask 0022
# curl -sSL https://install.pi-hole.net | bash
```
