### ISSUE TITLE
[FEATURE REQUEST] Support for Arch Linux and derivatives

### ISSUE THREAD

**Issue by simonbcn** [pi-hole/pi-hole#2415]
I use Arch Linux in my PC and when I tried to install Pi-hole I saw this :disappointed: :
```
$ sudo bash basic-install.sh

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] OS distribution not supported
```
I think the Arch Linux distribution (_and its derivatives_) are popular enough to be considered. 
Thanks.

**Comment by PromoFaux** [comment]
We've no plans to officially support Arch for the forseable, however please take a look at this AUR package maintained by @max.bra and @graysky2

https://aur.archlinux.org/packages/pi-hole-server/

**Comment by simonbcn** [comment]
I know this AUR package and finally I've installed this app of that way. But I don't understand why you don't support this distro and you don't support that AUR package.

**Comment by PromoFaux** [comment]
We're all volunteers working on this in our spare time. We've limited resources, and as such a package already exists and is well-maintained, there is no need for us to make our own. For the time being, the AUR package is as close to official as you'll get on Arch.

If you'd like, you can open a feature request on our [Discourse forums](https://discourse.pi-hole.net), as was mentioned in the issue template of this repository.
