### ISSUE TITLE
Why the -q parameter for curl in updatecheck.sh

### ISSUE THREAD

**Issue by olivier2557** [pi-hole/pi-hole#2416]
The script /opt/pihole/updatecheck.sh uses curl to check the latest version of Pi-Hole. I noticed that the parameter -q is passed to the command curl, with the effect of disabling the use of curl configuration file.

As a side effect, it prevents from setting up a proxy for curl, as the only way to setup the proxy is through curl configuration file .curlrc

Id there any rationale for using the -q parameter or could it be dropped down?

**Comment by olivier2557** [comment]
Suggested patch:
```
--- updatecheck.sh     2018-09-12 14:19:01.059940251 +0700
+++ updatecheck.sh      2018-09-19 10:30:29.557301288 +0700
@@ -43,9 +43,9 @@
         sleep 30
     fi
 
-    GITHUB_CORE_VERSION="$(json_extract tag_name "$(curl -q 'https://api.github.com/repos/pi-hole/pi-hole/releases/latest' 2> /dev/null)")"
-    GITHUB_WEB_VERSION="$(json_extract tag_name "$(curl -q 'https://api.github.com/repos/pi-hole/AdminLTE/releases/latest' 2> /dev/null)")"
-    GITHUB_FTL_VERSION="$(json_extract tag_name "$(curl -q 'https://api.github.com/repos/pi-hole/FTL/releases/latest' 2> /dev/null)")"
+    GITHUB_CORE_VERSION="$(json_extract tag_name "$(curl 'https://api.github.com/repos/pi-hole/pi-hole/releases/latest' 2> /dev/null)")"
+    GITHUB_WEB_VERSION="$(json_extract tag_name "$(curl 'https://api.github.com/repos/pi-hole/AdminLTE/releases/latest' 2> /dev/null)")"
+    GITHUB_FTL_VERSION="$(json_extract tag_name "$(curl 'https://api.github.com/repos/pi-hole/FTL/releases/latest' 2> /dev/null)")"
 
     echo -n "${GITHUB_CORE_VERSION} ${GITHUB_WEB_VERSION} ${GITHUB_FTL_VERSION}" > "/etc/pihole/GitHubVersions"
```

**Comment by diginc** [comment]
I often confuse curl's ` -s, --silent` and wget's `-q --quiet` options (but I didn't write this).  Based off the `2> /dev/null` on the end I'm betting the intention may have been `-s`

**Comment by Mcat12** [comment]
@olivier2557 You can open a PR if you want (optimally with the `-s` flag instead of `-q`). Otherwise, we can make the change.

**Comment by Olivier2561** [comment]
I tried to open a PR, not sure if I succeeded, else please make the change, I am sure a PR on that matter would not generate much comment.
