### ISSUE TITLE
Graphic with resolver times

### ISSUE THREAD

**Issue by yonailo** [pi-hole/pi-hole#2417]
Hello,

Have you ever considered measuring query answer times ? It would be nice to have such a graph (mean query answer times per measure unit, for exemple) in order to evaluate the speed of the chosen resolver.

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
