### ISSUE TITLE
API getForwardDestinations omits destination when it's at 0 percent

### ISSUE THREAD

**Issue by unknown14725** [pi-hole/pi-hole#2421]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 1

---
**Expected behaviour:**

Show destination and value of "0" when there is 0 percent to report.

Expected example output:
`{"forward_destinations": "blocklist|blocklist":0,"cache|cache":50,"router.local.lan|192.168.1.1":25,"router.local.lan|fe80::1:1":25}}
`

**Actual behaviour:**

Omits destination completely when it's at 0 percent.

Erroneous example output if 0 percent is blocked:
`{"forward_destinations": "cache|cache":50,"router.local.lan|192.168.1.1":25,"router.local.lan|fe80::1:1":25}}`

**Steps to reproduce:**

Have a system where nothing is blocked. I assume this might happen with other destinations as well, i.e. cache and DNS server, but it's hard to test, so I don't know how to troubleshoot it. 

Both **cache** and **blocklist** should always be presented in the destination output (no matter their values), in my opinion. It presents a lot of unnecessary challenges when elements are suddenly missing, i.e. when using a Pi-hole with external monitoring software.

**Troubleshooting undertaken, and/or other relevant information:**

I don't know how to "fix" it or further troubleshoot it, as it seems to be an inherent issue in how the API presents its data.

**Comment by Mcat12** [comment]
The root of this issue is in [FTL](https://github.com/pi-hole/FTL/blob/master/api.c#L535-L536).
@DL6ER Do you agree that cache and blocklist should always be shown?

**Comment by DL6ER** [comment]
The current code is chosen like this to hide forward destinations that are known but haven't been used recently. However, this code was written prior to the addition of the special `blocklist` and `cache` "upstreams" so I'd be okay with adding an exception for them, e.g.,
```c
if(percentage > 0.0f || i < 0)
```
where `i == -2` is the blocklist, and `i == -1` is cached.

**Comment by Mcat12** [comment]
Fixed by pi-hole/FTL#387
