### ISSUE TITLE
permission errors in /etc/dnsmasq.d

### ISSUE THREAD

**Issue by slootsky** [pi-hole/pi-hole#2422]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`saving a new static IP via the web console works`

**Actual behaviour:**

`When I added a static IP and tried to save, I got an error that the file /etc/dnsmasq.d/04-pihole-staic-dhcp.conf could not be opened for write`

**Steps to reproduce:**

`fresh install on fresh debian on an rpi3`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`nl27c3ubtj`

**Troubleshooting undertaken, and/or other relevant information:**

`
by default, the files in /etc/dnsmasq.d are owned by root grouped root and permissions are 644

sudo su
cd /etc/dnsmasq.d
chgrp pihole *
chmod g+w *
`

**Comment by dschaper** [comment]
Was the error that you reported from the web interface?

**Comment by Mcat12** [comment]
What is the output of `pihole -a addstaticdhcp mac ip hostname` where `mac`, `ip`, and `hostname` are the values you are trying to input into the web interface?

**Comment by dschaper** [comment]
Closing: Stale
