### ISSUE TITLE
Dashboard shows IPs (not hostnames) despite using PiHole DHCP

### ISSUE THREAD

**Issue by DanTup** [pi-hole/pi-hole#2427]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*. (**it can by me, I don't know about anyone else**).
- [x] The issue I am reporting isn't a duplicate

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Dashboard should show names of clients when using built-in DHCP.

**Actual behaviour:**

IP addresses are shown.

**Steps to reproduce:**

I set up using the Docker container on a Pi3 (using --`net=host` to get DHCP working). I've turned off DHCP for my router and confirmed PiHole's DHCP is being used.

Here's my static reservation:

<img width="971" alt="screen shot 2018-09-26 at 18 48 45" src="https://user-images.githubusercontent.com/1078012/46098975-76264780-c1bd-11e8-8134-ff2ac256f7f6.png">

Here's the device shown in the "current leases" section:

<img width="937" alt="screen shot 2018-09-26 at 18 48 56" src="https://user-images.githubusercontent.com/1078012/46098985-80e0dc80-c1bd-11e8-9614-56a8398887e0.png">

I've renewed the lease on the client, and then browsed some sites. But still everything shows up with an IP:

<img width="996" alt="screen shot 2018-09-26 at 18 49 10" src="https://user-images.githubusercontent.com/1078012/46099000-8dfdcb80-c1bd-11e8-87b7-9fbc58e14ace.png">

**Comment by Mcat12** [comment]
What is the DNS server in the container's `/etc/resolv.conf`? If it's not Pi-hole, then it can't resolve the hostname.

**Comment by DanTup** [comment]
Aha! It looks like the Docker image gets it's resolve.conf from the host machine. That comes from my `dhcpcd.conf` which I'd not included itself in (I figured the host machine might want to use DNS before PiHole is ready).

I added `127.0.0.1` and rebooted and it seems to have fixed itself now. Apologies if this was documented somewhere.

Thanks!
