### ISSUE TITLE
FTLDNS Long Term Database queries table "types" only have values 1 and 2

### ISSUE THREAD

**Issue by sqldba-today** [pi-hole/pi-hole#2432]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

SQLite database, in the "queries" table I expect to see more than type = 1 or type = 2 from query "select distinct type from queries;" should return more than 1 and 2.  The Query Types donut chart in my Dashboard shows 65.6% A, 32.8% AAAA, 0.5% SRV, and 1.1% PTR.

**Actual behaviour:**

The query when run in the pihole-FTL.db shows only 
1
2

If I run "select distinct type, count(*) from queries group by type;", I receive
1|6202293
2|2308380

**Steps to reproduce:**

SSH to pihole.  cd to /etc/pihole
execute "sqlite3 pihole-FTL.db"
execute query

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

q5ky7f7b71

**Troubleshooting undertaken, and/or other relevant information:**

I have read through the FTL code lightly, but "c" programming is not my strong point.  I do not think the data is logged to the database at this time via code.  I was not able to follow the pihole code branch to determine where the data from the "Query Type" donut chart is retrieved.

> * 
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
In v4.0, only IPv4 and IPv6 (A and AAAA) queries are stored in memory and the database.
However, the dev version of FTL does have support for this, so it will be included in the next release.

pi-hole/FTL#349

```sql
sqlite> SELECT COUNT(type), type FROM queries GROUP BY type;
2|0
2845945|1
2738758|2
459|4
289|6

```
