### ISSUE TITLE
Installing with PHP7 already installed fails due to dependencies

### ISSUE THREAD

**Issue by Rumpick** [pi-hole/pi-hole#2433]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`The installation of Pihole competes on a Raspberry Pi Raspbian with PHP7 installed`

**Actual behaviour:**

`The installation fails without warning`

**Steps to reproduce:**

`Attempt to install. The process fails at "debconf-apt-progress -- apt-get --yes --no-install-recommends install dns-root-data resolvconf php7.0-cgi php7.0-sqlite" silently.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`Likely related to Issue #2117. 
I attempted to install the packages manually after determining the problem.

```
$ sudo apt install dns-root-data resolvconf php7.0-cgi php7.0-sqlite
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php7.0-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-cgi' has no installation candidate
E: Unable to locate package php7.0-sqlite
E: Couldn't find any package by regex 'php7.0-sqlite'
```

I was able to install dns-root-data and resolvconf but if any one package is missing, it all fails and no information is provided.`

**Comment by technicalpyro** [comment]
what is the result of `uname -a` and `lsb_release -a` ?

**Comment by Rumpick** [comment]
$ uname -a
Linux Athena 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

**Comment by technicalpyro** [comment]
Raspbian Jessie is EOL is there a reason you are running it? (other software etc)?

The reason i ask is that is the easiest solution in this case i am downloading an older copy of jessie to do some testing here and hopefully provide further guidance

**Comment by Rumpick** [comment]
As I stated before, #2117 implemented support for php7. 
These packages come from line 202 
`PIHOLE_WEB_DEPS=(lighttpd ${phpVer}-common ${phpVer}-cgi ${phpVer}-${phpSqlite})`

**Comment by technicalpyro** [comment]
For sure.  It is appreciated i'm sorry if it came across as otherwise.  I am still trying to reproduce this myself, and i am looking into it deeper

**Comment by technicalpyro** [comment]
what does `apt-cache search php7.0-cgi` reutrn on your system ?

**Comment by Rumpick** [comment]
blank, nothing... I tried it with Sudo too.

**Comment by technicalpyro** [comment]
Ok so what im seeing tells me that the packages required are not available in the Jessie repositories.  i think you are correct that it should exit with an error.  Or an intstruction similar to "PHP packages not available try this" kind of idea

**Comment by technicalpyro** [comment]
I'm not 100% sure the web side is more @mcat12 so i ahve pinged him and hopeully he can answer better than i can.  I do know sqlite is used as a part of the FTL engine but not 100% on the ramifications of not having it on the PHP side

**Comment by Rumpick** [comment]
I checked, pulling from the long term data returns an error.

**Comment by Mcat12** [comment]
Jessie is not EOL until 2020. This PR should have handled this issue: #2220

What is the full install log?

**Comment by Mcat12** [comment]
If sqlite is not installed then the web interface can not access long term data.

**Comment by Rumpick** [comment]
@Mcat12 This what you need? https://pastebin.com/35WT6MbV

I was installing it by downloading to a file and then executing "sudo bash -vx piholeinstall.txt"

**Comment by Mcat12** [comment]
How did you install PHP 7 originally? It looks like only PHP 5 is supported on Jessie.

**Comment by Rumpick** [comment]
I suspect by uncommenting one of the sources listed above. Just followed a guide a while back, but I don't remember why I needed it installed on that machine.

**Comment by Rumpick** [comment]
I installed php7.0-cgi and php7.0-sqlite3. I had to do a repair on pihole to get it working, maybe just a restart was necessary, but I wasn't sure which processed managed the web interface.

**Comment by Mcat12** [comment]
Now it works? The issue can then be closed.

**Comment by Rumpick** [comment]
depends on if you want to fix the silently failing "debconf-apt-progress -- apt-get --yes --no-install-recommends install " issue or not. If there is a different install issue apart from PHP7.0, it would be nice to get an error message.

**Comment by Mcat12** [comment]
There are other issues open for that, but this one was specifically caused by a misconfigured package source.
