### ISSUE TITLE
This breaks resetting a password on Ubuntu 16.04

### ISSUE THREAD

**Issue by cybrnook** [pi-hole/pi-hole#2435]
pihole -a -p no longer works:

pihole@piholeQ9-sec:~$ pihole -a -p
/opt/pihole/webpage.sh: line 13: setupVars: readonly variable
/opt/pihole/webpage.sh: line 113: read: `Enter New Password (Blank for no password): ': not a valid identifier

_Originally posted by @cybrnook in https://github.com/pi-hole/pi-hole/commit/8684356b4486f77bc7c49dd5e08620d2a20aa975#commitcomment-30709174_

**Comment by Mcat12** [comment]
Thank you for quickly testing this.

**Comment by cybrnook** [comment]
I happened to be in the middle of an install and switch to dev branch. Stumbled into it, so figured I would shoot over to see if any recent commits. Was within seconds....

**Comment by cybrnook** [comment]
As a side note, one of the recent commits broke the UI displaying versions properly (bottom right of webui):

Pi-hole Version vDev (, ) Web Interface Version vDev (development, vDev-7a74acc) FTL Version

**Comment by Mcat12** [comment]
Thanks, I've found the issue.
