### ISSUE TITLE
Error: MAC address (83:C8:91:DF:04) is invalid!

### ISSUE THREAD

**Issue by 74cmonty** [pi-hole/pi-hole#2441]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**

`Static DHCP leases configuration allows generated MAC addresses for LXC and VM`

**Actual behaviour:**

`WebUI shows error: MAC address (83:C8:91:DF:04) is invalid!`

**Steps to reproduce:**

`In Pi-hole WebUI goto Settings -> DHCP -> Static DHCP leases configuration and enter MAC address generated by Proxmox VE for LXC / VM.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`xoesp33tyw`

**Troubleshooting undertaken, and/or other relevant information:**

`Entered the relevant server data manually in _/etc/dnsmasq.d/04-pihole-static-dhcp.conf_`

**Comment by dschaper** [comment]
A valid MAC address is 6 octets, you just have 5 octets?

**Comment by 74cmonty** [comment]
My fault.
