### ISSUE TITLE
[Bug] Using Pi-hole's DNS for local name resolution is not working - all requests are server by Upstream DNS Servers

### ISSUE THREAD

**Issue by 74cmonty** [pi-hole/pi-hole#2443]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I want a working DNS for local name resolution.`

**Actual behaviour:**

`Local DNS fails; server's IP in LAN is not considered`

**Steps to reproduce:**

Basically I followed [these](https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533) instructions to configure Pi-hole's DNS for local name resolution.
This means I've executed the following steps:
1. echo "addn-hosts=/etc/pihole/lan.list" | sudo tee /etc/dnsmasq.d/02-lan.conf
2. maintain /etc/pihole/lan.list
3. pihole restartdns

To verify if this is working I used
```
root@ct101-pihole:~# dig devklaud.whl.biszumbitterenen.lan

; <<>> DiG 9.10.3-P4-Debian <<>> devklaud.whl.biszumbitterenen.lan
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23307
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;devklaud.whl.biszumbitterenen.lan. IN  A

;; AUTHORITY SECTION:
.                       7942    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2018100200 1800 900 604800 86400

;; Query time: 28 msec
;; SERVER: 46.182.19.48#53(46.182.19.48)
;; WHEN: Tue Oct 02 14:38:01 CEST 2018
;; MSG SIZE  rcvd: 137

root@ct101-pihole:~# nslookup devklaud.whl.biszumbitterenen.lan
Server:         46.182.19.48
Address:        46.182.19.48#53

** server can't find devklaud.whl.biszumbitterenen.lan: NXDOMAIN
```
The output confirms that local name resolution fails.

I investigated on this issue assuming that Pi-hole is running dnsmasq and found [this](https://www.linux.com/learn/dnsmasq-easy-lan-name-services) webpage.
From this the following questions arise:
Where must I maintain the host information for local name resolution? 
In _/etc/pihole/lan.list_ or _/etc/hosts_?
Why are some relevant DNS directives not maintainable, e.g. _expand-hosts, listen-address, bind-interfaces_?
I can find these directives in _/etc/.pihole/advanced/dnsmasq.conf.original_, though.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`7cv7a2uy3f`

**Troubleshooting undertaken, and/or other relevant information:**

`Maintained /etc/pihole/lan.list and /etc/dnsmasq.d/02-lan.conf
Restarted DNS service`

**Comment by Mcat12** [comment]
> ;; SERVER: 46.182.19.48#53(46.182.19.48)

You are not using Pi-hole for DNS.

**Comment by Mcat12** [comment]
You may be running Pi-hole, yes, but the machine you ran those commands are is not using Pi-hole for DNS. This is shown in the output of the `dig` and `nslookup` commands you shared. They are using `46.182.19.48`, which I assume is not your Pi-hole's address based on your debug token. I could be mistaken, and that could be your Pi-hole's address.

**Comment by 74cmonty** [comment]
Well, IP _46.182.19.48_ belongs to _dns2.digitalcourage.de_ (see previous posting) and this is obviously the external DNS. This means client requests are going to Pi-hole and filtered. Then Pi-hole must forward the request to the Upstream DNS Servers. In my case this is dnscrypt-proxy that ensures that only secured DNS servers are used (DNSSEC).

If this explanation is wrong please correct.

**Comment by 74cmonty** [comment]
I've continued investigation and found some information how _dnsmasq_ is typically configured to resolve requests for LAN.
In my understanding this is controlled by this parameter:
**local=/example.com/ Our local domain, queries in these domains are answered from /etc/hosts or the static-hosts files.**

I have added this parameter (and some others that are important in my opinion) in file _/etc/dnsmasq.d/03-lan-dns.conf_:
```
root@ct101-pihole:~# more /etc/dnsmasq.d/03-lan-dns.conf
expand-hosts
#domain=whl.biszumbitterenen.lan
local=/whl.biszumbitterenen.lan/
listen-address=127.0.0.1
listen-address=192.168.1.101
bind-interfaces
```

Based on this I conclude that this parameter is not working with embedded dnsmasq in FTL.

**Comment by Mcat12** [comment]
Since you **directly** queried the external server, Pi-hole was not involved with that query. Therefore there is no way that it could have blocked it. Change the DNS server your machine is using to Pi-hole, and then it will use Pi-hole for DNS.

That `local` config option only signifies that subdomains of that domain should be handled locally and not forwarded.

The dnsmasq in FTL is the same as the latest stable version of dnsmasq, so the same configuration works the same on both normal dnsmasq and FTL's embedded dnsmasq.

**Comment by 74cmonty** [comment]
Thank's for this valuable input.
I will stop testing from Pi-hole server.
