### ISSUE TITLE
Unnecessary error message when creating /etc/dnsmasq.d/04-pihole-static-dhcp.conf

### ISSUE THREAD

**Issue by nfriedly** [pi-hole/pi-hole#2444]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Static DHCP leases added without any error message

**Actual behavior:**

The first static DHCP lease added gets this error message:

> There was a problem applying your settings.
> Debugging information:
> PHP error (2): fopen(/etc/dnsmasq.d/04-pihole-static-dhcp.conf): failed to open stream: No such file or directory in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:66

Despite the message, the file is created and the appropriate line is added

**Steps to reproduce:**

On a freshly installed pi-hole, or one where the file `/etc/dnsmasq.d/04-pihole-static-dhcp.conf` has been deleted, add a new Static DHCP lease.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`pp8jou2ti7`

**Troubleshooting undertaken, and/or other relevant information:**

No action was necessary. `/etc/dnsmasq.d/04-pihole-static-dhcp.conf` was created and populated despite the error.

Someone else appears to have seen the same issue: https://discourse.pi-hole.net/t/error-on-setting-up-static-dhcp/12445

**Comment by nfriedly** [comment]
LOL @ "this is not an error", just like the not-a-flamethrower

But in all seriousness, nice work, this is a great project :)

**Comment by pikeas** [comment]
I' m running Pihole 4.4 (latest at time of posting) and just encountered this.

**Comment by tbone2k-git** [comment]
Mee too!
