### ISSUE TITLE
[Suggestion] add IP Blacklist

### ISSUE THREAD

**Issue by liberodark** [pi-hole/pi-hole#2448]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`8`

---
**Expected behaviour:**

`pi-hole need blacklist ip for block web with no name just ip`

**Actual behaviour:**

`exemple : http://35.193.89.147/ is bad ip used for streaming website for ads`

**Steps to reproduce:**

`go to the internet have more websites use ip adresse and not a name for website for put ads`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`no need debug info need new fonctionality`

**Troubleshooting undertaken, and/or other relevant information:**

`im in reflexion for this !`

**Comment by Mcat12** [comment]
Pi-hole is unable to block IP addresses because it is DNS server and therefore it is impossible for it to do this.

**Comment by no-replies** [comment]
A solution is to use with DNSCRYPT which can block but it would be nice to be able to manage IP Blacklist and Blacklist via pihole UI.
