### ISSUE TITLE
not an issuse but an implementazione question (pi-hole+access point on raspberry)

### ISSUE THREAD

**Issue by Mr-P3rry** [pi-hole/pi-hole#2452]
**In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide]
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the the source code relevant to this issue?:**

`{7 somewhat familiar}`

---
**Expected behaviour:**

I easily installed pi-hole on my raspberry pi 3 b+ but the problem is that my router doesn't let me change it's default DNS(i could change manually DNS on almost all my devices expect the chromecast which doesn't let me change DNS as my router). So I thought that I could use the wifi on the raspberry to make an Access Point which uses Pi-hole's static ip address as the DNS.

**Actual behaviour:**
I used this git to make the pi an access point 
https://github.com/unixabg/RPI-Wireless-Hotspot.git
then when it asked what was the dns I gave pi-hole's ip address.
But this doen't work. When I connect to the wifi it has problems with the dns and doen't let me surf the net. 

So I was wondering if I should manually change stuff on iptables or if there are other ways to obtain what i want. Thanks

**Comment by Mcat12** [comment]
A better solution would be to use Pi-hole for DHCP. If you're able to correct resolve DNS queries when directly using Pi-hole (via `dig domain @pi.hole.ip.address` or `nslookup domain pi.hole.ip.address`), then this isn't a Pi-hole issue and you should open an issue on that other repository.

**Comment by Mr-P3rry** [comment]
okay I'll check this out! Thanks
