### ISSUE TITLE
"Update" button at "Update Gravity" WebUI page does nothing.

### ISSUE THREAD

**Issue by RooneyMcNibNug** [pi-hole/pi-hole#2453]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

Going to `Tools > Update Gravity` at http://192.168.*.*/admin/gravity.php and clicking the `Update` button successfully updates blocklists.`

**Actual behaviour:**

The button is showing up properly as an element on the page, but upon clicking it nothing happens at all.

**Steps to reproduce:**

I am trying this in Firefox 62.0.3 with all Add-ons disabled. Simply attempting to click the `Update` button at http://192.168.*.*/admin/gravity.php does nothing.

**Troubleshooting undertaken, and/or other relevant information:**
Running `pihole -r` and selecting the `Repair` option runs fine and updates all lists successfully via terminal.
Running `pihole -r` and selcting the `Reconfigure` option successfully reconfigs the pihole but the problem persists.

**Comment by RooneyMcNibNug** [comment]
I am also having issues with gravity now - both when trying to repair and also when trying to update gravity via SSH:

```
  pi@pi:~ $ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: No changes detected

  [i] Target: sysctl.org (hosts)
  [✓] Status: No changes detected

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: No changes detected

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: No changes detected

  [i] Target: raw.githubusercontent.com (trackers.txt)
  [✓] Status: Retrieval successful

  [i] Target: v.firebog.net (Easyprivacy.txt)
  [✓] Status: No changes detected

  [i] Target: v.firebog.net (Prigent-Ads.txt)
  [✓] Status: No changes detected

  [i] Target: v.firebog.net (Airelle-trc.txt)
  [✓] Status: No changes detected

  [i] Target: raw.githubusercontent.com (AudioFp.txt)
  [✓] Status: Retrieval successful

  [i] Target: v.firebog.net (Shalla-mal.txt)
  [✓] Status: No changes detected

  [i] Target: raw.githubusercontent.com (SmartTV.txt)
  [✓] Status: Retrieval successful

  [i] Target: raw.githubusercontent.com (spammers.txt)
  [✓] Status: Retrieval successful

  [i] Target: v.firebog.net (AdguardDNS.txt)
  [✓] Status: No changes detected

  [i] Target: justdomains.github.io (easyprivacy-justdomains.txt)
  [✓] Status: No changes detected

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 281170
  [i] Removing duplicate domains...
```

It gets stuck at `[i] Removing duplicate domains...` every time now.

Let me know if you would like me to check on any config files or logs.

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token. Do you see any errors in the dev console on the web interface (F12) when you try to update gravity from there?

**Comment by RooneyMcNibNug** [comment]
It does:

```
pi@pi:/var/www/html/admin/scripts/pi-hole/php $ ls
add.php        footer.php  gravity.php     password.php      tailLog.php
api_token.php  FTL.php     gravity.sh.php  queryads.php      teleporter.php
auth.php       func.php    header.php      savesettings.php  update_checker.php
debug.php      get.php     loginpage.php   sub.php
```

Let me know if you need me to produce anything more.

**Comment by Mcat12** [comment]
Is the IP address it is using in the URL correct? Have you tried accessing the web interface over `pi.hole`, `localhost`, or the device's hostname?

**Comment by RooneyMcNibNug** [comment]
IP I'm using in the URL is correct. Accessing the interface over the other methods (ex `http:/pi.hole/admin`) is not currently working.

**Comment by WaLLy3K** [comment]
If `gravity.sh` is stopping at `Removing duplicate domains...` from CLI, then that means [`sort -u`](https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/gravity.sh#L428) is failing.

Given that this `sort` line is the most hardware intensive command in the script, it suggests there might not be enough RAM for the task. I can't speculate any further though, since the debug token you've provided has since expired - you could either provide a new debug token for us to look at, or try running the default lists temporarily:

```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
```

**Comment by RooneyMcNibNug** [comment]
Thanks @WaLLy3K - I've reduced the number of lists a bit and can confirm that it gravity is successfully updating from the UI now, so you are probably correct that it was a RAM issue.

**Comment by Mcat12** [comment]
Usually you can use more than that many domains. Another thing you can check is that you are using at least a 2amp power supply, because the Pi 3 can draw a lot of power under load.
