### ISSUE TITLE
Cannot open WebUI using FQHN

### ISSUE THREAD

**Issue by 74cmonty** [pi-hole/pi-hole#2455]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I want to open WebUI using FQHN.`
Please check [this](https://ibb.co/b2DCb9) screenshot for details.

**Actual behaviour:**

`When opening WebUI using FQHN I get this error:
Access to the following website has been denied.`

**Steps to reproduce:**

`Use FQHN to access WebUI.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`9v4rv6ejzq`

**Troubleshooting undertaken, and/or other relevant information:**

`-`

Opening WebUI using server's IP works w/o issues.

**Comment by Mcat12** [comment]
The web interface only allows access via `pi.hole`, `localhost`, 127.0.0.1, and the IP address. If you want to access it from another domain, you will have to add this to `/etc/lighttpd/external.conf`:
```
setenv.add-environment = (  
          "VIRTUAL_HOST" => "your.fqdn.here"
)
```

**Comment by stitch10925** [comment]
If you add "/admin" to your FQDN, it should work: 
ct-101-pihole.[...].lan/admin

**Comment by 74cmonty** [comment]
Solution of @stitch10925 is working perfectly for me.
Therefore I won't modify the Lighttpd config.

THX
