### ISSUE TITLE
[Security Request] Fail2Ban Support

### ISSUE THREAD

**Issue by zero77** [pi-hole/pi-hole#2456]
Can you please add support for fail2ban by, creating a log of failed logins with the IP address, date and time stamp.
Thanks

https://github.com/fail2ban/fail2ban

Basic requirements for log compatibility:
Also, perhaps just separate logs as I think this could decrease system load when analyzing.

> a date-time when is failure occurred, better in the system time zone (fail2ban supports several date-time formats, but it can be also configured separately via datepattern parameter)

> an unique identifier of the intruder (most the IP address, but if not IP-related it could be also an e-mail, or user, etc)

>  some message part that obviously identifies a failed attempt (like Authentication failed: invalid password)

> **As an example:**

> 2018-09-30 23:05:55 WARN AUTH-ERROR: 192.0.2.1 - Authentication failed for user "tester": user unknown
> 2018-09-30 23:15:03 WARN AUTH-ERROR: 192.0.2.5 - Authentication failed for user "root": user disallowed
> 2018-09-30 23:18:05 WARN AUTH-ERROR: 192.0.2.8 - Authentication failed for user "admin": invalid password

> **Note the best practices also:**

> the unique characteristic of failure (here AUTH-ERROR) as well as the identifier (here IPs) as early as possible in the message (could be found faster and with fewer load during the search);

> foreign data (user input), if needed to be logged, should be escaped (if possible) and/or placed at end of line (so the parser does not need to traverse this info to find all expected failure characteristics)

> if possible write it into separate log-file (or log-file with few errors) or if logged into systemd-journal resp. rsyslog provide it with some unique marks (e. g. severity: warning/critical, facility: security/auth, etc), to make possible to use selectors (to avoid parasite "traffic" by searching of the failures).

**Comment by PromoFaux** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our Discourse Forum, as mentioned in the [Issue Template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Thank you for your understanding.
