### ISSUE TITLE
apt-get update error

### ISSUE THREAD

**Issue by carlosnewmusic** [pi-hole/pi-hole#2458]
10
---
**Expected behaviour:**
continue with the update
**Actual behaviour:**
reconfigure option and
![imagen](https://user-images.githubusercontent.com/19379457/46744393-602f8100-ccab-11e8-9711-3c24871947f1.png)
although apt-get update outside the script works perfectly

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
[pihole_debug-sanitized.log](https://github.com/pi-hole/pi-hole/files/2465176/pihole_debug-sanitized.log)

`{Alphanumeric token}`
9vn89bspd0

**Comment by Mcat12** [comment]
You have an issue with PHP, and most probably have an issue with `sudo apt-get update`. Run that command and share the output.

**Comment by Mcat12** [comment]
> E: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.

This is the error which needs to be fixed before Pi-hole can be installed.

**Comment by carlosnewmusic** [comment]
> 
> 
> > E: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.
> 
> This is the error which needs to be fixed before Pi-hole can be installed.

they are already sources.list errors that have nothing to do with my system

**Comment by Mcat12** [comment]
From the translation:
> Some index files could not be downloaded, have been omitted, or old ones used instead.

It is an issue with your system, because the sources you are using are invalid. Remove the broken sources or replace them and then it will work.

**Comment by carlosnewmusic** [comment]
> 
> 
> From the translation:
> 
> > Some index files could not be downloaded, have been omitted, or old ones used instead.
> 
> It is an issue with your system, because the sources you are using are invalid. Remove the broken sources or replace them and then it will work.

Although in the new update this as a nginx web server?

**Comment by Mcat12** [comment]
What do you mean? The installer can't continue until the package management system is working correctly.
