### ISSUE TITLE
Not restarting dnsmasq

### ISSUE THREAD

**Issue by davidritterhouse** [pi-hole/pi-hole#246]
Strange, I added a few sites to the whitelist and blacklist but it did not take effect.  I then manually did a "service dnsmasq restart" and refreshed the page that was being blacklisted and instantly it worked.  Does this restart dnsmasq after each change?  What can I look at to troubleshoot this?
thanks for the work, this really brings pi-hole to a whole new level

**Comment by davidritterhouse** [comment]
posted in wrong git sorry lol back to bed I go.

**Comment by PromoFaux** [comment]
No worries!

Was this in relation to the Admin page?

**Comment by davidritterhouse** [comment]
No it was in relation to the chrome extension. :)  I was way off lol

**Comment by PromoFaux** [comment]
Ah, OK.

It's a pretty neat extension! We don't officially support it yet, as at the moment, the only way you have of running the scripts properly is to add www-data to sudoers, obviously this causes security issues.

To whitelist or blacklist the official way, use the methods detailed in the wiki post I linked before :)
