### ISSUE TITLE
Pihole reports "DNS resolution is currently unavailable" when host's DNS references Pihole.

### ISSUE THREAD

**Issue by jwalton** [pi-hole/pi-hole#2464]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pihole starts correctly.

**Actual behaviour:**

Pihole logs:

```
DNS resolution is currently unavailable.
```

And then dies.

**Steps to reproduce:**

It seems that, when starting pihole via docker, if the docker host machine has the pihole listed as a nameserver in resolv.conf, then pihole will fail to start with `DNS resolution is currently unavailable.`, even if other nameservers are listed and the docker host is able to resolve domain names.

**Debug token provided by:**

I tried `pihole -d -a` via docker, but I didn't see a debug token anywhere in the output.  This is everything from `docker logs pihole`: https://gist.github.com/jwalton/508fd6041945ba4e4947072c147d0d79

**Troubleshooting undertaken, and/or other relevant information:**

I have a stock Asus RT-AC68U router at 192.168.0.1 ("the router").  I have a docker host running at 192.168.0.4, which is where pihole runs.

The router runs the DHCP server for the house, and it also is my gateway to the cable modem.  The router advertises itself as the DNS lookup (192.168.0.1).  In the router config, I can optionally provide another DNS server (the pihole server), in which case the router will advertise the pihole (192.168.0.4) as the primary DNS and itself (192.168.0.1) as the secondary DNS.  This works well, as if the pihole dies, I still can resolve things through the router's DNS.

On the docker host, resolv.conf looks like:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.0.4
nameserver 192.168.0.1
search local
```

If I try to start (or restart) pihole with the resolv.conf looking like this, pihole will start with `DNS resolution is currently unavailable`, and then kill itself.  Note that I am able to resolve hostnames on the docker host (e.g. `host github.com` returns sensible results).  If I remove the `nameserver 192.168.0.4` line, the pihole starts correctly (although then the DHCP client on 192.168.0.4 will eventually overwrite resolv.conf, and then if pihole crashes or tries to restart, it will fail).

**Comment by jwalton** [comment]
I should also point out my pi-hole configuration for DNS servers includes neither 192.168.0.1 nor 192.168.0.4, so I'm not sure why /etc/resolv.conf even comes into play here.

**Comment by dschaper** [comment]
Issue moved to [pi-hole/docker-pi-hole #342](https://github.com/pi-hole/docker-pi-hole/issues/342) via [**ZenHub**](https://www.zenhub.com/)
