### ISSUE TITLE
Event Horizon / Gravity fails when whitelisting a domain and resets back to 0

### ISSUE THREAD

**Issue by cybrnook** [pi-hole/pi-hole#2465]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behaviour:**

When adding the FIRST domain to the whitelist either by WebUI or by CLI, it's cleanly adds the domain while retaining the current block list.

**Actual behaviour:**

When adding the FIRST domain to the whitelist either by WebUI or by CLI, it errors with:

/etc/pihole/list.preEventHorizon: No such file or directory

And resets all domains in Event Horizon to 0

**Steps to reproduce:**

Do a clean install, allowing all blacklist domains to be downloaded during install. Then whitelist a domain and notice all counters reset to 0.

**Troubleshooting undertaken, and/or other relevant information:**

Clean install:
![image](https://user-images.githubusercontent.com/22136734/46923531-00a4de80-cfe7-11e8-8f21-9096491669a2.png)

Whitelist a domain:
![image](https://user-images.githubusercontent.com/22136734/46923535-1b775300-cfe7-11e8-9291-3cff2230b4b8.png)

![image](https://user-images.githubusercontent.com/22136734/46923564-698c5680-cfe7-11e8-9357-5ba52dcbb011.png)

**Comment by dschaper** [comment]
Thanks for the report, I see the same behavior as well under the same conditions.

**Comment by cybrnook** [comment]
Perhaps it may help you. But what I notice as well, is after it errors out and 0's out. The next run on gravity seems to want to pull raw.githubusercontent again, like it never got it the first time. But all the subsequent lists say as  no change, if I am remembering correctly.

**Comment by PromoFaux** [comment]
Just to clarify, is this only ever on the very first domain you whitelist? Do subsequent runs of `pihole -w` fix the issue, or is it only after `pihole -g` (or the `cron` job, whichever comes first) has been run that the situation is resolved?

**Comment by cybrnook** [comment]
Subsequent adds to the white list seem to happen without issue. What I don't like about this bug though, is it's basically a wasted initial pull against the block lists, as it then in turn wipes them out, only to have to pihole -g to download them again.

So after the first white list add, then subsequent pihole -g pull again, it seems to sort itself out, and cron etc.. work. So something in the initial setup is chicken/egg.

**Comment by PromoFaux** [comment]
Certainly the `list.preEventHorizon` file does not exist on first run:

```
  [i] The install log is located at: /etc/pihole/install.log
    Installation Complete!
root@debian-s-1vcpu-1gb-lon1-01:~# ls -l /etc/pihole/list.*
-rw------- 1 root root 2026608 Dec  5 21:53 /etc/pihole/list.0.raw.githubusercontent.com.domains
-rw------- 1 root root  595340 Dec  5 21:53 /etc/pihole/list.1.mirror1.malwaredomains.com.domains
-rw------- 1 root root  638705 Dec  5 21:53 /etc/pihole/list.2.sysctl.org.domains
-rw------- 1 root root    7214 Dec  5 21:53 /etc/pihole/list.3.zeustracker.abuse.ch.domains
-rw------- 1 root root     613 Dec  5 21:53 /etc/pihole/list.4.s3.amazonaws.com.domains
-rw------- 1 root root   43642 Dec  5 21:53 /etc/pihole/list.5.s3.amazonaws.com.domains
-rw------- 1 root root 1772476 Dec  5 21:53 /etc/pihole/list.6.hosts-file.net.domains
```
Interestingly, it does not exist on subsequent runs of `pihole -g`, either. Not until something is added to the whitelist.

In fact, looking at it, the issue is in `gravity.sh` somewhere. `list.preEventHorizon` does not get created unless `/etc/pihole/whitelist.txt` exists. (which it does not on install)

In your case, running `pihole -w [domain]` creates `whitelist.txt`, and so subsequent runs of `gravity.sh` will create `list.preEventHorizon.

Quick and dirty fix: `touch /etc/pihole/whitelist.txt` before running gravity in the install file

Longer term fix: find the bug in `gravity.sh` that causes this to happen.

**Comment by PromoFaux** [comment]
```
  [✓] Pi-hole blocking is Enabled
root@debian-s-1vcpu-1gb-lon1-01:~# ls -l /etc/pihole/list.*
-rw------- 1 root root 2026608 Dec  5 22:01 /etc/pihole/list.0.raw.githubusercontent.com.domains
-rw------- 1 root root  595340 Dec  5 21:59 /etc/pihole/list.1.mirror1.malwaredomains.com.domains
-rw------- 1 root root  638705 Dec  5 21:59 /etc/pihole/list.2.sysctl.org.domains
-rw------- 1 root root    7214 Dec  5 21:59 /etc/pihole/list.3.zeustracker.abuse.ch.domains
-rw------- 1 root root     613 Dec  5 21:59 /etc/pihole/list.4.s3.amazonaws.com.domains
-rw------- 1 root root   43642 Dec  5 21:59 /etc/pihole/list.5.s3.amazonaws.com.domains
-rw------- 1 root root 1772476 Dec  5 21:59 /etc/pihole/list.6.hosts-file.net.domains
root@debian-s-1vcpu-1gb-lon1-01:~# touch /etc/pihole/whitelist.txt
root@debian-s-1vcpu-1gb-lon1-01:~# pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: No changes detected

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: No changes detected

  [i] Target: sysctl.org (hosts)
  [✓] Status: No changes detected

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: No changes detected

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: No changes detected

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 160897
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 137663
  [i] Number of whitelisted domains: 0
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
root@debian-s-1vcpu-1gb-lon1-01:~# ls -l /etc/pihole/list.*
-rw------- 1 root root 2026608 Dec  5 22:01 /etc/pihole/list.0.raw.githubusercontent.com.domains
-rw------- 1 root root  595340 Dec  5 21:59 /etc/pihole/list.1.mirror1.malwaredomains.com.domains
-rw------- 1 root root  638705 Dec  5 21:59 /etc/pihole/list.2.sysctl.org.domains
-rw------- 1 root root    7214 Dec  5 21:59 /etc/pihole/list.3.zeustracker.abuse.ch.domains
-rw------- 1 root root     613 Dec  5 21:59 /etc/pihole/list.4.s3.amazonaws.com.domains
-rw------- 1 root root   43642 Dec  5 21:59 /etc/pihole/list.5.s3.amazonaws.com.domains
-rw------- 1 root root 1772476 Dec  5 21:59 /etc/pihole/list.6.hosts-file.net.domains
-rw-r--r-- 1 root root 3253952 Dec  5 22:01 /etc/pihole/list.preEventHorizon
```

**Comment by PromoFaux** [comment]
Or rather, something is causing `list.preEventHorizon` to be deleted after it is created.

**Comment by PromoFaux** [comment]
Found it.

https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L525
