### ISSUE TITLE
"Queries Blocked" becomes greater than "Total queries"

### ISSUE THREAD

**Issue by butlerrscott** [pi-hole/pi-hole#2469]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The number of blocked queries should not be greater than the number of total queries.

**Actual behaviour:**

Shortly after a fresh reboot, total queries are greater than blocked queries - as expected.  After running for a while, the number of blocked queries becomes greater than the total queries field. For example, in the instance corresponding to the debug file sent, "Total queries" was 6,339 and "Queries Blocked" was 17,350.  I'm not sure how long it takes for this to occur.  I'll check to see.

I've attached a screenshot showing the counter values.

The blocking function of pihole seems to be working fine.

**Steps to reproduce:**

Reboot pihole and wait.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

azx3vfmjry

**Troubleshooting undertaken, and/or other relevant information:**

Nothing other than rebooting to confirm that the problem recurs.

:qatar: 
![screenshot_2018-10-17 pi-hole admin console](https://user-images.githubusercontent.com/4777499/47101192-6079d000-d207-11e8-8d89-fe3a5deb27e4.png)

**Comment by Mcat12** [comment]
This is an FTL bug which is fixed in development. https://github.com/pi-hole/FTL/pull/349#issuecomment-412286418
