### ISSUE TITLE
Different # of domains being pulled in by gravity...

### ISSUE THREAD

**Issue by silentwolf15** [pi-hole/pi-hole#247]
When you run the curl command to update it only pulls in around 88,000 domains, even with mahakala un-comented from previous install, but on further manual runs of gravity it pulls in over 700,000 domains.  It appears that gravity.sh is overwritten and hence the diff number of domains being pulled in.

###################################################
Install.log
###################################################
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Getting adaway.org list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... List updated, transport successful!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... List updated, transport successful!
::: Getting winhelp2002.mvps.org list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 97608 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 88490 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 8 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 10 domains whitelisted!
::: Running blacklist script to update HOSTS file... 4 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!

###################################################
Gravity.sh output from manual run
###################################################
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Getting adaway.org list... No changes detected, transport skipped!
::: Getting adblock.gjtech.net list... No changes detected, transport skipped!
::: Getting adblock.mahakala.is list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... No changes detected, transport skipped!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... No changes detected, transport skipped!
::: Getting winhelp2002.mvps.org list... No changes detected, transport skipped!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 782186 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 691548 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 9 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 10 domains whitelisted!
::: Running blacklist script to update HOSTS file... 4 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!

**Comment by dschaper** [comment]
Thanks for the report, we'll take a look at this and see what we can find.

**Comment by PromoFaux** [comment]
Ah, yeah, this is because makala is commented out by default. When you manually ran gravity after update, did you have to uncommented makala again? The next thing I'm working on is getting the block lists out of gravity and into a file that persists through installs. Hopefully that will give users a little more control over what they want blocked.

**Comment by silentwolf15** [comment]
1) When you manually ran gravity after update, did you have to uncommented makala again? 
Correct

2) The next thing I'm working on is getting the block lists out of gravity and into a file that persists through installs.
The tough part here is how do you update a list that can be customized without erasing what is already there?  Not impossible to overcome but makes the solution a lot more difficult.

**Comment by PromoFaux** [comment]
On 1) Yeah, that's because `gravity.sh` is being overwritten on each install, one of the reasons I want to get the source list out of gravity.

On 2) I have an idea, but i'm terrible at articulating them until I've actually got it out in code :) Basically there will be a choice on install to overwrite the sourcelist file (e.g `blocksource.list`) and we'll ship some defaults for fresh installs (`blocklist.default`) SO when gravity runs, if there is an existing `blocksource.list` it will take the domains from there, however if there is a custom list it will read out of that. I think that makes sense! Like I said, I'm terrible at articulating my thoughts..

**Comment by PromoFaux** [comment]
Something like, but not necessarily what I said above. The choice on install probably wont make the cut.

**Comment by PromoFaux** [comment]
Fixed by #249

**Comment by PromoFaux** [comment]
So yeah, not quite like I said :).

**Comment by PromoFaux** [comment]
@silentwolf15 Will be fixed in the next version, pending PR #275.

**Comment by jacobsalmela** [comment]
@PromoFaux can we close this since #275 was merged?

**Comment by PromoFaux** [comment]
Oh. Thought I had. Still need to get some documentation up for that, as it puts an optional user customisation on blocklists.

**Comment by PromoFaux** [comment]
Documentation [here](https://github.com/pi-hole/pi-hole/wiki/Customising-ad-list-sources)

**Comment by Mcat12** [comment]
There is no page there.

**Comment by Mcat12** [comment]
You probably meant [this](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists).

**Comment by PromoFaux** [comment]
Updated, and censoring corrections...
