### ISSUE TITLE
add Rogue DNS feature

### ISSUE THREAD

**Issue by voxdemonix** [pi-hole/pi-hole#2473]
Hello devs and community.
First, thx for PiHole and it's great webui. 👍

People who self-host their services and have [HairPinning](https://en.wikipedia.org/wiki/Hairpinning) problems with bad routers must return a LAN (or VPN) IP address for certain domain names, instead of "official" ip address.
Example : 
- in the officials public DNS server, the address of mycloud.user.com is 8.8.8.8, user can use it only when he is not on his LAN
- in the private user DNS Server (PiHole), the address of mycloud.user.com is 192.168.1.42, user can use it only on LAN.

When the user is on his LAN, the PiHole send the [LAN](https://en.wikipedia.org/wiki/LAN) address of his server.
When the user is on another network, the public DNS server send the [WAN](https://en.wikipedia.org/wiki/Wide_area_network) adresss of his server.

So with PiHole we must add [DnsChef](http://thesprawl.org/projects/dnschef/) to accomplish this action, although netmasq seems to allow this via these options if I believe the following paragraph (source _/etc/dnsmasq_)

```
# Add domains which you want to force to an IP address here.
# The example below send any host in double-click.net to a local
# web-server.
#address=/double-click.net/127.0.0.1
```

It can be helpfull to add this feature for can remove dnschef dependancy, if it has your favors :)

This feature offers the possibility to add another feature in the futur: a NTP server to give time to [IOT](https://en.wikipedia.org/wiki/Internet_of_things) machines whose user has blocked access to internet (isolated machines). But this feature needs to be able to return two or three known public NTP server domain names to the local, because the IOT does not often allow to choose its own NTP server (example Foscam). It's working properly with dnschef + ntpd (on a machine with PiHole).

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by voxdemonix** [comment]
Sorry.
Posted :)
