### ISSUE TITLE
Pihole Bad Host Record

### ISSUE THREAD

**Issue by greg6614** [pi-hole/pi-hole#2475]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pihole should start dnsmasq daemon normally`

**Actual behaviour:**

`dnsmasq daemon can't start with error Bad Host Record`

**Steps to reproduce:**

I don't really now how it appears because it was running normally. I just changed upstream dns from web ui, and then dns was not working anymore. Here's the result of `service pihole-FTL status`

` pihole-FTL.service - LSB: pihole-FTL daemon`
 ` Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)`
   `Active: active (exited) since Tue 2018-10-23 17:17:56 UTC; 3s ago`
     `Docs: man:systemd-sysv-generator(8)`
 ` Process: 11147 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)`
  `Process: 11185 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)`

`Oct 23 17:17:56 macberry systemd[1]: Starting LSB: pihole-FTL daemon...`
`Oct 23 17:17:56 macberry pihole-FTL[11185]: Not running`
`Oct 23 17:17:56 macberry su[11223]: Successful su for pihole by root`
`Oct 23 17:17:56 macberry su[11223]: + ??? root:pihole`
`Oct 23 17:17:56 macberry su[11223]: pam_unix(su:session): session opened for user pihole by (uid=0)`
`Oct 23 17:17:56 macberry pihole-FTL[11185]: dnsmasq: Bad host-record at line 47 of /etc/dnsmasq.d/01-pihole.conf`
`Oct 23 17:17:56 macberry systemd[1]: Started LSB: pihole-FTL daemon. `

**Troubleshooting undertaken, and/or other relevant information:**
Here's the content of `/etc/dnsmasq.d/01-pihole.conf`

`addn-hosts=/etc/pihole/gravity.list`
`addn-hosts=/etc/pihole/black.list`
`addn-hosts=/etc/pihole/local.list`
`localise-queries`
`no-resolv`
`cache-size=10000`
`log-queries=extra`
`log-facility=/var/log/pihole.log`
`local-ttl=2`
`log-async`
`server=80.10.246.2#53`
`server=80.10.246.129#53`
`domain-needed`
`bogus-priv`
`host-record=192.168.1.22`
`interface=wlan0`

`192.168.1.22` is the correct IP of my RPI.

**Steps of what you have done to fix this:**

I've just commented out the host-record line in `/etc/dnsmasq.d/01-pihole.conf` and it works again. But if I run `pihole restartdns` command, conf file is regenerated and then dnsmasq fails to load.

**Comment by dschaper** [comment]
The error messages says the bad record is on line 47, but the contents you pasted only contains 16 lines. 

Can you please run a `pihole -d` debug run and post the token that is provided for you?

**Comment by dschaper** [comment]
And checking what you have posted, that is indeed an invalid host record. How are you configuring that record?

**Comment by greg6614** [comment]
Yes it's only 16 lines because i've remove the warning at the begining of the file in the copy/past. Line 47 refers to `host-record=192.168.1.22`

But i've solve my issue by doing `pihole -r`. I think the problem came obviously from me. In my old setupVars.conf, host record was `HOST-RECORD=192.168.1.22`. After reconfiguring it's now `HOST-RECORD=192.168.1.22,macberry.lan`.

I had probably didn't understand exactly how it works. Sorry for wasting your time but many thanks for your replies.

**Comment by dschaper** [comment]
Not wasting our time at all, glad it's resolved.
