### ISSUE TITLE
Trivial Help text change under DNS Section

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#2478]
On Settings section, under DNS/DNSSEC tab there is the following help text:

"Use Google, Norton, DNS.WATCH or Quad9".

It needs a small correction based on these:

Norton DNS is gone so it should be removed, and Cloudflare DNS supports DNSSEC so it may be added.

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #857](https://github.com/pi-hole/AdminLTE/issues/857) via [**ZenHub**](https://www.zenhub.com/)
