### ISSUE TITLE
lighttpd fails to respond outside of admin directory

### ISSUE THREAD

**Issue by rj45jack** [pi-hole/pi-hole#248]
After installing Pi Hole lighttpd stops responding to requests outside of the Pi Hole admin folder located at /var/www/html/admin. I noticed within /etc/lighttpd/lighttpd.conf the comment "If the URL does not start with /admin, then it is a query for an ad domain". This effectively broke my installation of Currant Pi, which is a realtime HTML status application. I was able to temporarily fix it my moving my installation of Currant Pi to /var/www/html/admin/CurrantPi.

**Comment by dschaper** [comment]
The current configuration of the Pi-Hole assumes that you are not running a web server on the same RasPi via lighttpd. There are options though, one of which is to run Currant Pi under a different port than 80, or editing `lighttpd.conf` to respond to named domains first as Pi-Hole is the default server. There are plans to make the Pi-Hole more friendly for running other services on the same Pi, but we're working on stability first and then getting to enhancements.

**Comment by DonLexos** [comment]
I had the same problem (playing around with phpmyadmin). Problem with placing it in `/var/www/html/admin/..` is that any new instance of install/update will wipe your files away.

I fixed this by adding files to `/var/www/html/home/..` which will be untouched when updating. Got phpMyAdmin working there, and have a few other items that respond. Must admit I only access those locally, my pi is not accessible from the internet.

**Comment by Mcat12** [comment]
The latest install should fix this, if I'm not mistaken. I made a PR that fixed this, and was merged recently.

**Comment by rj45jack** [comment]
I just reinstalled the newest version, same issue. Unless....there is something I have to do to uninstall Pi Hole?

**Comment by Mcat12** [comment]
Can you post the output of ```cat /etc/lighttpd/lighttpd.conf```?

**Comment by Mcat12** [comment]
There's no problem in running the installer again. That's actually how you update the Pi-hole.

**Comment by rj45jack** [comment]
Of course:

server.modules = (
        "mod_access",
        "mod_accesslog",
        "mod_expire",
        "mod_compress",
        "mod_redirect",
        "mod_setenv",
        "mod_rewrite"
)

server.document-root        = "/var/www/html"
server.error-handler-404        = "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename                      = "/var/log/lighttpd/access.log"
accesslog.format                        = "%{%s}t|%V|%r|%s|%b"


index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
        # Create a response header for debugging using curl -I
        setenv.add-response-header = ( "X-Pi-hole" => "The Pi-hole Web interface is working!" )
}

# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
        # Create a response header for debugging using curl -I
        setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )

**Comment by Mcat12** [comment]
Try commenting out the last section. So, you are able to access sites that are not in the root of the server?

**Comment by DonLexos** [comment]
Yes try putting them in `/var/www/html/somewhere else' instead of `/var/www/html/` itself, it should work. Will try myself tonight, planning to do a clean 2.4 installation and will post if that still works.

**Comment by rj45jack** [comment]
I tested with files at /var/www/html/ and within /var/www/html/currant/ both fail to load any data.

**Comment by PromoFaux** [comment]
Hey @rj45jack What version number does the pi-hole dashboard say on it? Should say 2.4. If not, try a `curl -L install.pi-hole.net | bash` to get everything up to date, and try again

**Comment by DonLexos** [comment]
Promissed an update:
Did a clean installation just now, added `/var/www/html/home/` and everything I put in there I can access in a browser.

**Comment by Mcat12** [comment]
Can you access anything in ```/var/www/html/```?

**Comment by rj45jack** [comment]
@PromoFaux Looks like I am on 2.4. I did just update, it seems to through. On a whim I restarted lighttpd after updating and I am now able to server pages via /var/www/html/!

**Comment by PromoFaux** [comment]
Excellent, glad it's sorted for you :+1:
