### ISSUE TITLE
No longer blocking ads on YouTube app on AppleTV 

### ISSUE THREAD

**Issue by sbeerda** [pi-hole/pi-hole#2480]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:1

I have pihole running on a dell r710 server running on a virtual Ubuntu machine. 

It used to block all ads on the YouTube app on my AppleTV 4K, but now all ads are playing. 😞

**Comment by Mcat12** [comment]
YouTube ad blocking has never been guaranteed, and recently it has become harder. There are many threads on Discourse about this topic, but this is not a bug in Pi-hole (although it could be a bug in a list you are using for blocking YouTube ads).

https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253
