### ISSUE TITLE
Blocked list detection does not account for non-standard ports for dig.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#2482]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

When a source list is blocked by another list we source setupVars.conf and pull the DNS1 address to use as a workaround for this unwanted behavior.

**Actual behaviour:**

The DNS1 address works as long as there is no port specifier. If they are using Unbound upstream on port 5353, then the dig call fails as it tries to `dig @127.0.0.1#5353`. Found by @jfb-pihole

**Steps to reproduce:**

Set DNS1 in setupVars to use `#` port specifiers. Will fail at https://github.com/pi-hole/pi-hole/blob/development/gravity.sh#L260

**Troubleshooting undertaken, and/or other relevant information:**

Add some logic to the detection code, if DNS1 contains `#`, split on that char and grab the left and right halves to `dig @<left> -p <right>`

```bash
$ awk -F# '{ print $1 }' <<< 127.0.0.1#5353
127.0.0.1
$ awk -F# '{ print $2 }' <<< 127.0.0.1#5353
5353
```

**Comment by DL6ER** [comment]
Note that the web interface is configured to always add a port for custom entered DNS server, i.e., even if the user only specifies `1.2.3.4`, it'll add `1.2.3.4#53` to `setupVars.conf`, underlying the importance of this issue.

**Comment by dschaper** [comment]
Is there a chance that this could be an IPv6 address? If not I can throw in a safety valve for checking for valid IPv4, otherwise I'll just put in a quick fix.

**Comment by dschaper** [comment]
Thanks, makes it a really quick fix then.
