### ISSUE TITLE
WiFi stops working

### ISSUE THREAD

**Issue by sudoxd** [pi-hole/pi-hole#2483]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Ad blocking without the internet periodically cutting out

**Actual behaviour:**
Ad blocking but the internet keeps cutting in and out

**Steps to reproduce:**
1. have internet
2. install pihole on an rpi3
3. set router dns to the pihole dns
4. wait for the internet to eat shit

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
7p08yhcviy

**Troubleshooting undertaken, and/or other relevant information:**

i havent been able to troubleshoot since i could not find any other relevant posts about this issue. i have however also run into the same issue on an ESXi VM so it shouldnt be isolated to the rpi3

**Comment by Daiben** [comment]
dhcp

**Comment by sudosudoo** [comment]
I should have that on

**Comment by Mcat12** [comment]
According to your debug log you aren't using Pi-hole for DHCP, so check your DHCP server's settings for anything that might cause issues.

I don't see any errors in your debug log.

What kind of issues are you experiencing? Does only domain resolution fail, or are you also unable to ping external IP addresses? Are you able to ping internal IP addresses?

**Comment by sudosudoo** [comment]
the issue im having is while the pi hole is on the internet keeps cutting out all the time, like i wont be able to access the internet, after 5 mins it comes good again.

**Comment by Mcat12** [comment]
Does only domain resolution fail, or are you also unable to ping external IP addresses? Are you able to ping internal IP addresses?

**Comment by sudoxd** [comment]
i have been using my pi-hole server in DHCP mode now for the past 6 hours and i don't seem to be having any issues.

will keep posted though.

**Comment by Mcat12** [comment]
This issue can be reopened if you experience the issue again.
