### ISSUE TITLE
Error page when adding blocklist in web interface

### ISSUE THREAD

**Issue by thomas2045** [pi-hole/pi-hole#2485]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

blocklist url shall be added to the blocklists in the web interface

**Actual behaviour:**

after pressing "save" in the web interface I see a white page with one line of error text:
"Failed CORS: null vs 192.168.0.51, , cloud.mydomain.com, pi.hole, localhost"

**Steps to reproduce:**

in my system this error occurs every time

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

l98jzubqr5

**Troubleshooting undertaken, and/or other relevant information:**

since I run apache (not lighttpd) on this server I checked file permissions - all files in the web directory are owned by www-data. I don't know if there may be other permission problems preventing to store the blocklist info.
This server is also used to run Nextcloud.

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #860](https://github.com/pi-hole/AdminLTE/issues/860) via [**ZenHub**](https://www.zenhub.com/)
