### ISSUE TITLE
Cannot use IPv6 address for upstream 'Custom' DNS provider during install

### ISSUE THREAD

**Issue by jallakim** [pi-hole/pi-hole#2491]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Be able to input one or more IPv6 address in the "Enter your desired upstream DNS providers, separated by comma" dialogue during install.

**Actual behaviour:**

The installer complains that the entered address is invalid.

**Steps to reproduce:**

Enter one or more IPv6 address during the dialogue.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A (happens during initial install).

**Troubleshooting undertaken, and/or other relevant information:**

None. Reproducible using IPv6 address with or without brackets.

**Comment by Mcat12** [comment]
The installer only supports adding custom IPv4 upstreams. This is therefore a feature request for adding IPv6 upstreams during installation, and should be posted to the Discourse feature requests section: https://discourse.pi-hole.net/c/feature-requests

Note that you can add IPv6 upstreams after install by using the web interface.

**Comment by jallakim** [comment]
@Mcat12, sure, I can add it as a feature request.

Should I file a separate issue for the fact that the installer fails/quits abruptly during install on an IPv6-only host? (using a placeholder IPv4 custom upstream DNS). After the "Select Protocols" dialogue, it just quits with ```RTNETLINK answers: Network is unreachable``` (which is understandable since it probably tries to reach the placeholder IPv4 upstream DNS, but should be handled way more gracefully if there is only partial IPv6 support).

**Comment by Mcat12** [comment]
Yes, that can be a separate issue.
