### ISSUE TITLE
dnsmasq not disabled -> pihole-ftl cannot start

### ISSUE THREAD

**Issue by blackm** [pi-hole/pi-hole#2494]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_ 

---

**[BUG | ISSUE] Expected Behaviour:**
When rebooting my Pi3, I expect pihole-ftl to start

**[BUG | ISSUE] Actual Behaviour:**
pihole-ftl not starting, login to check / start manual....address in use error (port 53)....stop dnsmasq manually and start pihole-ftl manually 

**[BUG | ISSUE] Steps to reproduce:**

- installed pi 3 with raspbian-minimal (2 weeks ago)
- curl -sSL https://install.pi-hole.net | bash
- DNS working, filtered with pihole
- reboot
- DNS not working
- did a repair (pihole -r) -> did not solve the issue
- disabled dnsmasq in /etc/default/dnsmasq

**Log file output [if available]**

$ cat install.log 
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✓] Backing up index.lighttpd.html

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...
  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Latest FTL Binary already installed (v4.0). Confirming Checksum...
  [i] Checksum correct. No need to download!

  [✓] man pages installed and database updated

**Device specifics**

Hardware Type: rPi
OS: rspbian 9.4

**Comment by blackm** [comment]
I opened /etc/default/dnsmasq and changed _ENABLED_ to _0_

**Comment by Mcat12** [comment]
Was dnsmasq disabled via systemd before you disabled it using that file?

**Comment by blackm** [comment]
Not manully by myself. At the moment I cannot reboot the pi, but will do during the weekend and give feedback next week.

The only thing special about my machine is that I had nginx installed before (port 80 in use) ... will this cause a conflict when installing lighttpd? (causing the install script to interupt)

**Comment by Mcat12** [comment]
That probably did not affect it, since it would not return an error when starting the service. Do you have the full output of the original install (not via the log)?

**Comment by blackm** [comment]
I don't think the install log is available anymore. /etc/pihole/install.log got overwritten when I did a pihole -r 2 days ago.
What I noticed is that my systemd has a problem. When I run 

user@box:/etc/pihole $ systemctl status dnsmasq
Failed to get properties: No such interface ''

Can you may point me out at which line of the install script the dnsmasq gets disabled?

**Comment by Mcat12** [comment]
https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/automated%20install/basic-install.sh#L2080-L2087

**Comment by blackm** [comment]
Hallo Mcat12,

thanks for pointing me out on the code.

After I rebooted, my systemctl did not error anymore. I could disable dnsmasq and an other reboot showed that pihole-ftp is started correct.
Closing the issue :-)
