### ISSUE TITLE
wrong forwarding dns server

### ISSUE THREAD

**Issue by Ondjultomte** [pi-hole/pi-hole#250]
Why is pih using  other DNS servers then I have confed?

Jan 26 23:54:45 dnsmasq[7861]: forwarded apps.facebook.com to 8.8.4.4  

I want do use my ISPs since they are much quicker. I did enter the static DNS servers but they aren't used.

im running debian with user kristoffer instead of pi.

**Comment by PromoFaux** [comment]
Hey

Did you just need to change the `server=` values in `/etc/dnsmasq.conf` to be the IP addresses of your ISPs DNS servers?

e.g for openDNS instead of google you would set:

```
server=208.67.222.222
server=208.67.220.220
```

in `/etc/dnsmasq.conf`

**Comment by Ondjultomte** [comment]
Didn't notice no resolv was on.  Silly .. :)  thnx for the fast reply

**Comment by PromoFaux** [comment]
:) is that fixed then?

**Comment by Ondjultomte** [comment]
yes :)
