### ISSUE TITLE
Google Playstore apps cannot be downloaded

### ISSUE THREAD

**Issue by piLinux** [pi-hole/pi-hole#2503]
_Originally posted by @jacobsalmela in https://github.com/pi-hole/pi-hole/issues/1893#issuecomment-377725898_

I think this problem should be fixed. So I am opening the issue again.

Steps to reproduce the problem:

- Configure OpenVPN to use only the DNS to create this problem.

`sudo nano /etc/openvpn/server.conf
`
```
#push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 10.8.0.1"
```

- If OpenVPN is configured to use as a full VPN, then no problem arises.

`sudo nano /etc/openvpn/server.conf
`
```
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 10.8.0.1"
```

- If only OpenVPN is used (no pi-hole), then also no problem occurs.

`sudo nano /etc/openvpn/server.conf
`
```
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
```

**Comment by Mcat12** [comment]
Have you tried checking the query log to see if any queries are blocked? Also, are you using one of the DNS servers you also tested as the upstream for Pi-hole? If not, then test with the Pi-hole upstream to make sure it's not the upstream's fault.

**Comment by piLinux** [comment]
**Queries:**

No playstore related host was blocked. I also placed the following hosts in whitelist:

```
android.clients.google.com
clients1.google.com
clients2.google.com
clients3.google.com
clients4.google.com
clients5.google.com
clients6.google.com
play.googleapis.com
```

Furthermore, I disabled pi-hole filters, but the problem exists.

**DNS servers for upstream:**

- _[passed]_ Tested with the DNS servers (Google, OpenDNS, Cloudflare without OpenVPN and Pi-hole)
- _[passed]_ Tested with the DNS servers as upstream for Pi-hole (no OpenVPN)
- _[passed]_ Tested with the DNS servers as upstream for Pi-hole (using full OpenVPN)
- _[passed]_ Tested with the DNS servers using full OpenVPN (no Pi-hole)
- **_[failed]_** Tested with the DNS servers as upstream for Pi-hole (configured OpenVPN only for DNS)

**Comment by dschaper** [comment]
We ask that you fill out the template so that we can get the required information we need to help troubleshoot. I'm going to close this issue and ask that you open a new one with all the template information filled out. Thanks.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by RobbieTheK** [comment]
I know this is closed but I'm having this issue.  All app installs just hang on install on multiple Android phones. Here's just a sample of google.com subdomains that I've whitelisted:
```
May 31 22:36:36 dnsmasq[31659]: query[A] clients6.google.com from 192.168.0.163
May 31 22:36:36 dnsmasq[31659]: forwarded clients6.google.com to 1.1.1.1
May 31 22:36:36 dnsmasq[31659]: reply clients6.google.com is <CNAME>
May 31 22:36:36 dnsmasq[31659]: reply clients.l.google.com is 172.217.12.174
May 31 22:36:36 dnsmasq[31659]: query[A] people-pa.clients6.google.com from 192.168.0.163
May 31 22:36:36 dnsmasq[31659]: forwarded people-pa.clients6.google.com to 1.1.1.1
May 31 22:36:36 dnsmasq[31659]: reply people-pa.clients6.google.com is 172.217.11.42
May 31 22:36:40 dnsmasq[31659]: query[A] adservice.google.com from 192.168.0.163
May 31 22:36:40 dnsmasq[31659]: /etc/pihole/gravity.list adservice.google.com is 0.0.0.0
May 31 22:36:46 dnsmasq[31659]: query[A] 24.client-channel.google.com from 192.168.0.163
May 31 22:36:46 dnsmasq[31659]: forwarded 24.client-channel.google.com to 1.1.1.1
May 31 22:36:46 dnsmasq[31659]: reply 24.client-channel.google.com is 173.194.205.189
May 31 22:36:50 dnsmasq[31659]: query[A] www.google.com from 192.168.0.140
May 31 22:36:50 dnsmasq[31659]: forwarded www.google.com to 1.1.1.1
May 31 22:36:50 dnsmasq[31659]: reply www.google.com is 172.217.11.4
May 31 22:36:52 dnsmasq[31659]: query[A] id.google.com from 192.168.0.140
May 31 22:36:52 dnsmasq[31659]: /etc/pihole/gravity.list id.google.com is 0.0.0.0
May 31 22:36:52 dnsmasq[31659]: query[A] adservice.google.com from 192.168.0.140
May 31 22:36:52 dnsmasq[31659]: /etc/pihole/gravity.list adservice.google.com is 0.0.0.0
May 31 22:37:13 dnsmasq[31659]: query[A] adservice.google.com from 192.168.0.163
May 31 22:37:13 dnsmasq[31659]: /etc/pihole/gravity.list adservice.google.com is 0.0.0.0
May 31 22:37:23 dnsmasq[31659]: query[A] id.google.com from 192.168.0.140
May 31 22:37:23 dnsmasq[31659]: /etc/pihole/gravity.list id.google.com is 0.0.0.0
May 31 22:37:23 dnsmasq[31659]: query[A] adservice.google.com from 192.168.0.140
May 31 22:37:23 dnsmasq[31659]: /etc/pihole/gravity.list adservice.google.com is 0.0.0.0
May 31 22:38:37 dnsmasq[31659]: query[A] id.google.com from 192.168.0.140
May 31 22:38:37 dnsmasq[31659]: /etc/pihole/gravity.list id.google.com is 0.0.0.0
May 31 22:38:38 dnsmasq[31659]: query[A] adservice.google.com from 192.168.0.140
May 31 22:38:38 dnsmasq[31659]: /etc/pihole/gravity.list adservice.google.com is 0.0.0.0
May 31 22:38:55 dnsmasq[31659]: query[A] googleadapis.l.google.com from 192.168.0.140
May 31 22:38:55 dnsmasq[31659]: forwarded googleadapis.l.google.com to 1.0.0.1
May 31 22:38:55 dnsmasq[31659]: reply googleadapis.l.google.com is 172.217.12.138
May 31 22:38:56 dnsmasq[31659]: reply gstaticadssl.l.google.com is 172.217.12.195
May 31 22:39:01 dnsmasq[31659]: query[A] 11.client-channel.google.com from 192.168.0.163
May 31 22:39:01 dnsmasq[31659]: forwarded 11.client-channel.google.com to 1.0.0.1
May 31 22:39:01 dnsmasq[31659]: reply 11.client-channel.google.com is 173.194.207.189

```

**Comment by dschaper** [comment]
/etc/pihole/gravity.list id.google.com is 0.0.0.0

**Comment by RobbieTheK** [comment]
> /etc/pihole/gravity.list id.google.com is 0.0.0.0

Yep I added that too, same problem. Tried pihole -r and updated Gravity list too. Cleared cache of Google Play app.

**Comment by cransono** [comment]
I am having similar issues which just started this week. I didnt update anything on my end, so what changed?

**Comment by dschaper** [comment]
Probably a list you are using added domains.

**Comment by cransono** [comment]
That worked! Thank you very much!
The reason for my surprise is...
-Google Playstore works on my wifes Android phone. Its a different version of Android tho.
-Google Playstore worked last week and I didnt change anything on my pihole, but maybe the lists that I use got updated and broke playstore access for my phone?
