### ISSUE TITLE
Lighttpd service fails to start

### ISSUE THREAD

**Issue by Mukrosz** [pi-hole/pi-hole#2508]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

2

---

**[BUG | ISSUE] Expected Behaviour:**

ability to manage pihole via web interface

**[BUG | ISSUE] Actual Behaviour:**

web interface isnt functioning

**[BUG | ISSUE] Steps to reproduce:**

updated to version 4
and
updated centos 7 to latest
-
-
-
-

**Log file output [if available]**

```
[root@VM www]# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL not found

[root@VM www]# systemctl status lighttpd.service -l
● lighttpd.service - Lightning Fast Webserver With Light System Requirements
   Loaded: loaded (/etc/systemd/system/lighttpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-11-14 23:36:10 MST; 32min ago
  Process: 10774 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
 Main PID: 10774 (code=exited, status=255)

Nov 14 23:36:10 VM systemd[1]: Started Lightning Fast Webserver With Light System Requirements.
Nov 14 23:36:10 VM systemd[1]: Starting Lightning Fast Webserver With Light System Requirements...
Nov 14 23:36:10 VM lighttpd[10774]: 2018-11-14 23:36:10: (configfile.c.1462) commaned "cat external.conf 2>/dev/null" exited non-zero: 1
Nov 14 23:36:10 VM lighttpd[10774]: 2018-11-14 23:36:10: (configfile.c.1277) source: /etc/lighttpd/lighttpd.conf line: 94 pos: 1 parser failed somehow near here: (EOL)
Nov 14 23:36:10 VM systemd[1]: lighttpd.service: main process exited, code=exited, status=255/n/a
Nov 14 23:36:10 VM systemd[1]: Unit lighttpd.service entered failed state.
Nov 14 23:36:10 VM systemd[1]: lighttpd.service failed.
```

**Device specifics**

Hardware Type: VM
OS: centos 7.5.1804

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by bcambl** [comment]
Duplicate of #2391

**Comment by Mukrosz** [comment]
Thank you! #2391 had me sorted out: "sudo touch /etc/lighttpd/external.conf"
I'm running lighttpd version 1.4.51
