### ISSUE TITLE
Lighttpd appears not to start

### ISSUE THREAD

**Issue by chilinski** [pi-hole/pi-hole#251]
I installed pi-hole tonight (Jan 26) and it is reporting info the pihole log and ads I used to see on some sites are thankfully no longer there. I thought I read that the latest version comes with everything to use the web admin. However, that page never opens. 

pi@raspberrypi:/var/log/lighttpd $ more error.log
2016-01-26 23:44:44: (log.c.164) server started
2016-01-26 23:45:52: (server.c.1558) server stopped by UID = 0 PID = 1
2016-01-27 01:02:38: (log.c.164) server started
2016-01-27 01:02:38: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start:
2016-01-27 01:02:38: (mod_fastcgi.c.1116) child exited with status 2 /usr/bin/php-cgi
2016-01-27 01:02:38: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags.
2016-01-27 01:02:38: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed.
2016-01-27 01:02:38: (server.c.1022) Configuration of plugins failed. Going down.
2016-01-27 01:06:41: (log.c.164) server started
2016-01-27 01:06:41: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start:
2016-01-27 01:06:41: (mod_fastcgi.c.1116) child exited with status 2 /usr/bin/php-cgi
2016-01-27 01:06:41: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags.
2016-01-27 01:06:41: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed.
2016-01-27 01:06:41: (server.c.1022) Configuration of plugins failed. Going down.

Is there something else I'm missing in the install/configuration to get this to work? I suppose it's probably a Raspian issue, but it appears pi-hole has made changes to lightpd.conf so I thought I'd start asking here first.

**Comment by chilinski** [comment]
To get this to work required doing:
apt-get update
apt-get install php5-common php5-cgi php5

Everything got an update.

**Comment by Mcat12** [comment]
What updated?

**Comment by chilinski** [comment]
Everything you could possibly want to know, I guess:

pi@raspberrypi:/var/log/lighttpd $ sudo apt-get update
Get:1 http://mirrordirector.raspbian.org jessie InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [13.4 kB]
Get:3 http://mirrordirector.raspbian.org jessie/main armhf Packages [8,963 kB]
Get:4 http://archive.raspberrypi.org jessie/main armhf Packages [109 kB]
Get:5 http://archive.raspberrypi.org jessie/ui armhf Packages [7,639 B]
Ign http://archive.raspberrypi.org jessie/main Translation-en_US
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_US
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:6 http://mirrordirector.raspbian.org jessie/contrib armhf Packages [37.5 kB]
Get:7 http://mirrordirector.raspbian.org jessie/non-free armhf Packages [70.3 kB]
Get:8 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356 B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Fetched 9,217 kB in 43s (213 kB/s)
Reading package lists... Done

pi@raspberrypi:/var/log/lighttpd $ sudo apt-get -y install php5-common php5-cgi php5
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libonig2 libperl4-corelibs-perl libqdbm14 lsof php5-cli php5-json php5-readline
Suggested packages:
  php-pear php5-user-cache
The following NEW packages will be installed:
  libonig2 libperl4-corelibs-perl libqdbm14 lsof php5 php5-cgi php5-cli php5-common php5-json php5-readline
0 upgraded, 10 newly installed, 0 to remove and 90 not upgraded.
Need to get 4,466 kB/5,035 kB of archives.
After this operation, 26.3 MB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5 all 5.6.17+dfsg-0+deb8u1 [1,314 B]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-common armhf 5.6.17+dfsg-0+deb8u1 [703 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-cli armhf 5.6.17+dfsg-0+deb8u1 [1,886 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-cgi armhf 5.6.17+dfsg-0+deb8u1 [1,865 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-readline armhf 5.6.17+dfsg-0+deb8u1 [11.0 kB]
Fetched 4,466 kB in 2min 51s (26.0 kB/s)
Selecting previously unselected package libonig2:armhf.
(Reading database ... 123856 files and directories currently installed.)
Preparing to unpack .../libonig2_5.9.5-3.2_armhf.deb ...
Unpacking libonig2:armhf (5.9.5-3.2) ...
Selecting previously unselected package libperl4-corelibs-perl.
Preparing to unpack .../libperl4-corelibs-perl_0.003-1_all.deb ...
Unpacking libperl4-corelibs-perl (0.003-1) ...
Selecting previously unselected package lsof.
Preparing to unpack .../lsof_4.86+dfsg-1_armhf.deb ...
Unpacking lsof (4.86+dfsg-1) ...
Selecting previously unselected package libqdbm14.
Preparing to unpack .../libqdbm14_1.8.78-5+b1_armhf.deb ...
Unpacking libqdbm14 (1.8.78-5+b1) ...
Selecting previously unselected package php5-common.
Preparing to unpack .../php5-common_5.6.17+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-common (5.6.17+dfsg-0+deb8u1) ...
Selecting previously unselected package php5-json.
Preparing to unpack .../php5-json_1.3.6-1_armhf.deb ...
Unpacking php5-json (1.3.6-1) ...
Selecting previously unselected package php5-cli.
Preparing to unpack .../php5-cli_5.6.17+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-cli (5.6.17+dfsg-0+deb8u1) ...
Selecting previously unselected package php5-cgi.
Preparing to unpack .../php5-cgi_5.6.17+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-cgi (5.6.17+dfsg-0+deb8u1) ...
Selecting previously unselected package php5.
Preparing to unpack .../php5_5.6.17+dfsg-0+deb8u1_all.deb ...
Unpacking php5 (5.6.17+dfsg-0+deb8u1) ...
Selecting previously unselected package php5-readline.
Preparing to unpack .../php5-readline_5.6.17+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-readline (5.6.17+dfsg-0+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up libonig2:armhf (5.9.5-3.2) ...
Setting up libperl4-corelibs-perl (0.003-1) ...
Setting up lsof (4.86+dfsg-1) ...
Setting up libqdbm14 (1.8.78-5+b1) ...
Setting up php5-common (5.6.17+dfsg-0+deb8u1) ...

Creating config file /etc/php5/mods-available/pdo.ini with new version
php5_invoke: Enable module pdo for cli SAPI
php5_invoke: Enable module pdo for cgi SAPI

Creating config file /etc/php5/mods-available/opcache.ini with new version
php5_invoke: Enable module opcache for cli SAPI
php5_invoke: Enable module opcache for cgi SAPI
Setting up php5-json (1.3.6-1) ...
php5_invoke: Enable module json for cli SAPI
php5_invoke: Enable module json for cgi SAPI
Setting up php5-cli (5.6.17+dfsg-0+deb8u1) ...
update-alternatives: using /usr/bin/php5 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar5 to provide /usr/bin/phar (phar) in auto mode

Creating config file /etc/php5/cli/php.ini with new version
Setting up php5-cgi (5.6.17+dfsg-0+deb8u1) ...
update-alternatives: using /usr/bin/php5-cgi to provide /usr/bin/php-cgi (php-cgi) in auto mode
update-alternatives: using /usr/lib/cgi-bin/php5 to provide /usr/lib/cgi-bin/php (php-cgi-bin) in auto mode

Creating config file /etc/php5/cgi/php.ini with new version
Setting up php5 (5.6.17+dfsg-0+deb8u1) ...
Setting up php5-readline (5.6.17+dfsg-0+deb8u1) ...

Creating config file /etc/php5/mods-available/readline.ini with new version
php5_invoke: Enable module readline for cli SAPI
php5_invoke: Enable module readline for cgi SAPI
Processing triggers for libc-bin (2.19-18+deb8u1) ...

**Comment by Mcat12** [comment]
Those php packages should have been installed during the Pi-hole's installation. Can you post the output of ```cat /etc/pihole/install.log```?

**Comment by chilinski** [comment]
pi@raspberrypi:/etc/pihole $ more install.log
:::
::: Checking apt-get for upgraded packages... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking dependencies:
:::    Checking for dnsutils... Not found! Installing... done!
:::    Checking for bc... Not found! Installing... done!
:::    Checking for toilet... Not found! Installing... done!
:::    Checking for figlet... Not found! Installing... done!
:::    Checking for dnsmasq... Not found! Installing... done!
:::    Checking for lighttpd... Not found! Installing... done!
:::    Checking for php5-common... Not found! Installing... done!
:::    Checking for php5-cgi... Not found! Installing... done!
:::    Checking for php5... Not found! Installing... done!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services. done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... not found!!
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole.. done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... not found!!
:::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin.. done!
:::
::: Installing scripts... done.
:::
::: Installing configs... done.
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page... done!
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Getting adaway.org list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... List updated, transport successful!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... List updated, transport successful!
::: Getting winhelp2002.mvps.org list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 97701 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 88583 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 8 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 8 domains whitelisted!
::: Running blacklist script to update HOSTS file... 0 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!

**Comment by Mcat12** [comment]
@dschaper, any reason why this might be happening?

**Comment by chilinski** [comment]
FYI, this is the 11-21-2015 Raspian Jessie downloaded 1/14/2016 and the install done tonight on ph-hole. The base Raspian was installed, raspi-config was run to extend the partition and to change the locale/tz/keyboard. The pi-hole was done immediately thereafter. In hindsight, I should have run the apt-get update immediately after running raspi-config, but I forgot . Oh, this is on an old RPI B model.

**Comment by dschaper** [comment]
I'm not sure on this one. The install script does show that the `php` packages do show as `done` with the install, so I don't know why they didn't install. I can try a fresh install on a new Rasbian Jessie and see if I can replicate the issue. That section of code is pretty stable, @PromoFaux would have a better insight. Unfortunately the output from `apt-get` isn't logged, just the success and there may have been a temporary failure that fell through to completion.

I'll see if I can replicate.

**Comment by dschaper** [comment]
The install script right now does an `apt-get update`, but it will be modified in the future to check for the number of packages available for update and advise the installer that an update is advised. That code should be coming out in a week or so.

**Comment by PromoFaux** [comment]
Actually that was pushed in 2.4....

**Comment by PromoFaux** [comment]
Though, having checked over the logic ([here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L304-L326)), it works... but I'm now begining to wonder if it still needs `apt-get update` to run before it knows how many packages there are to upgrade... 

Can't hurt to put back in the code to run `apt-get update` if it has not already been run today, but I'll keep out `apt-get upgrade`

**Comment by DonLexos** [comment]
I had the installer stuck (in v 2.3) because either `apt-get update` or `apt-get upgrade` stuck since it required user input (mysql password for phpmyadmin) and the output was hidden. Not sure if you would reintroduce that issue if you would bring that back.

Will be doing a clean install of 2.4 myself (without the mysql, will take a peek at the other extra admin stats versions that have been developped and might try the sqlite version of the stats).

**Comment by PromoFaux** [comment]
It would have been `apt-get upgrade` as `update` only updates the package list, doesn't upgrade any package.

**Comment by dschaper** [comment]
A quick way to check, fresh install, run code snippet and see number pack's returned. Run apt-g update then code snip & chk # of pkgs returnd. Compare.

**Comment by dschaper** [comment]
Srry, on phone, typing bad...

**Comment by chilinski** [comment]
Today, I did a new install of Jessie, then did the apt-get update and then installed pi-hole (3 pm. EST) and everything works fine.

**Comment by PromoFaux** [comment]
Excellent, thanks for testing that. It looks like we need to add a call to apt-get update at the very beginning of the script for fresh installs. Cheers!

**Comment by PromoFaux** [comment]
To anyone following this thread, a fix is in the works and will be published in the next hour or so... apologies, and thanks for your patience!

**Comment by PromoFaux** [comment]
Fixed in #256
