### ISSUE TITLE
`Regex` import like `Block Lists`

### ISSUE THREAD

**Issue by kisst** [pi-hole/pi-hole#2513]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
4

---
**Expected behaviour:**

On the admin interface a list of regex blocks can be sourced from outside url's like host lists.
This is only available now with teleporter, only for a single list, but no merge or other advance functions available in hosts, are supported in regex.

Long term expected to have public block list for regex list as well as for hosts.

**Actual behaviour:**

This feature is not available in the current release.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
