### ISSUE TITLE
Can't connect to my external domain on my network

### ISSUE THREAD

**Issue by hypercrites** [pi-hole/pi-hole#2516]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`my external .tld`

**Actual behaviour:**

`certificate error for/from googles domains instead of the certificates from lets encrypt for my domain, when i am on my network`

**Steps to reproduce:**

`i don't know what i did wrong so ...?!`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wzvof160li`

**Troubleshooting undertaken, and/or other relevant information:**

i moved my /var/www/html dir to /home/pi/nginx because i am using a blog and other stuff too.
i use nginx instead of lighttpd and followed [this](https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration ) tutorial.
i modified /etc/nginx/[nginx.conf](https://pastebin.com/PLGiHV5R) (i replaced my domain-name with "mydomain.tld") and /etc/nginx/sites-available/[default](https://pastebin.com/a0EJ1S2c) (raspberrypi.fritz.box is for/from my router)
i tried pihole as a DNS server and DHCP server but both with the same result
i activated lets encrypt before i installed pihole, already tried a reinstall with certbot with no changes (i was thinking that maybe this was the error but without luck).

**Comment by Mcat12** [comment]
Does it work when you disable Pi-hole? Check if you have the domain set as a hostname (if it returns a local IP address instead of the external one). This may not be a Pi-hole issue.

**Comment by hypercrites** [comment]
it does not work when i disable pi-hole. how do i check that? i am not "so" into linux command-line tbh.
i couldn't think of something other than pi-hole causing this problem, because before i installed pi-hole, it worked as intended. however, pihole -d said this ```[✗] dnsmasq daemon is unknown``` but i don't know if this has something to do with it.

**Comment by Mcat12** [comment]
That error can be ignored, dnsmasq is embedded into FTL as of v4.0.
If you change your upstream DNS server on your computer to the upstream server set in Pi-hole (completely bypassing Pi-hole), do you still have the issue? If so, it is not a Pi-hole issue. Otherwise, check the output of `nslookup YOUR_DOMAIN` to see if you get the expected IP address back.

**Comment by hypercrites** [comment]
i use cloudflares DNS, if i set it on my computer to bypass pi-hole, my domain works.
nslookup looks like this:
![nslookup](https://user-images.githubusercontent.com/22784563/48957056-a63c5d80-ef56-11e8-835c-27150456bee5.png)
the first one is before i changed the DNS on my computer with the DNS from google, what results in a wrong certificate on my domain who tries to load googles certificates when i am on my network, i think.
the second one is after i changed my computers DNS manualy like your said.

**Comment by Mcat12** [comment]
You can check the dnsmasq log at `/var/log/pihole.log` to see exactly what is happening to the query when it goes through Pi-hole. You do have conditional forwarding and DHCP set up, which may cause the query to be handled locally instead of forwarded, but best to check the log to see what the issue is.

**Comment by hypercrites** [comment]
the logfile is pretty big, and i don't understand the given output, sorry. would it be enough to to copy the last hour of the logfile?
i disabled DHCP on my router and configured the pi-hole and router that DHCP comes from my raspberrypi.

**Comment by Mcat12** [comment]
You can just look at the most recent lines, or run `pihole -t` to follow the log in real time.

**Comment by hypercrites** [comment]
oh my... pihole -t showed me some entrys from /etc/hosts and for some reason i had this entries in my hosts-file:
```0.0.0.0 mydomain.tld
2001:4860:4860::8888 mydomain.tld```

i don't know why or what did this (because i never touched the hosts-file before) but without you i would have never found it, i guess! now all works as intended, thank you very much! :)
