### ISSUE TITLE
upgrade error with nginx

### ISSUE THREAD

**Issue by carlosnewmusic** [pi-hole/pi-hole#2517]
![imagen](https://user-images.githubusercontent.com/19379457/48866586-99433100-edd3-11e8-8b3c-766d6ebc4bdc.png)

_Originally posted by @carlosnewmusic in https://github.com/pi-hole/pi-hole/issues/2252#issuecomment-440799732_

and 
![imagen](https://user-images.githubusercontent.com/19379457/48877169-4df44700-ee02-11e8-86b1-bbd2e0b3b941.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by carlosnewmusic** [comment]
ok, now in the afternoon I'll put it on as you wish

**Comment by carlosnewmusic** [comment]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
it happens when trying to update pihole using the command for it or directly from the installation script
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`
10
---
**Expected behaviour:**
to be updated
`{A detailed description of what you expect to see}`
pihole updated
**Actual behaviour:**
could not update  local_repository with script or url not found with comand pihole -up
`{A detailed description and/or screenshots of what you do see}`
![imagen](https://user-images.githubusercontent.com/19379457/48955564-d2ec7700-ef4e-11e8-8eb7-93a7e8ed9ff1.png)
![imagen](https://user-images.githubusercontent.com/19379457/48955570-d7b12b00-ef4e-11e8-8d26-41678e9eb14d.png)

**Steps to reproduce:**
curl -sSL https://install.pi-hole.net | bash or pihole -up with root user

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
fi65zvofi8

**Troubleshooting undertaken, and/or other relevant information:**
correct internet connection, and correct sources.list without errors

**Comment by dschaper** [comment]
What is the contents of `/etc/resolv.conf` and what is the output from:

```
cd /var/www/html/admin/
sudo git status
```

**Comment by Mcat12** [comment]
@carlosnewmusic it looks like this issue was left hanging. Try `pihole -r` to repair, and share the output if it still isn't working.

**Comment by carlosnewmusic** [comment]
> 
> 
> @carlosnewmusic it looks like this issue was left hanging. Try `pihole -r` to repair, and share the output if it still isn't working.

it worked, and then update without problem; the only thing that ipv6 is not enabled :/

**Comment by Mcat12** [comment]
Do you have IPv6 internet access? Otherwise you don't need IPv6 blocking.

**Comment by carlosnewmusic** [comment]
> Do you have IPv6 internet access? Otherwise you don't need IPv6 blocking.

192.168.0.0
– 192.168.255.255
