### ISSUE TITLE
On virtual host temperature 100C 

### ISSUE THREAD

**Issue by r00t0vi4** [pi-hole/pi-hole#2519]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

**Actual behaviour:**

```bash
cat /sys/class/thermal/thermal_zone0/temp
100000
```
![100](https://user-images.githubusercontent.com/3502081/48938226-a2daaf00-ef21-11e8-8323-4c27ac9dc3ad.png)

**Comment by DL6ER** [comment]
Please provide more information about your particular virtual host and reopen this issue.

**Comment by sfkpmr** [comment]
I am having the same issue.

Running Pi-hole in Linux pihole 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 on VMware ESXi 5.5.0.
