### ISSUE TITLE
Blacklist not working in latest dev

### ISSUE THREAD

**Issue by ajp2k13** [pi-hole/pi-hole#2524]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x ] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Manually blacklisted hosts should not resolve`

**Actual behaviour:**

`Blacklisted hostnames are still forwarded after update to latest dev`

**Steps to reproduce:**

`Update to latest dev by using pihole checkout dev. After that my blacklisted hostnames are resolved, I can ping or nslookup and I get the public IP of the host`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`gywr87ivgz`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried pihole -r to repair. Tried rebooting`

**Comment by dschaper** [comment]
From the debug log:

```
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 1 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 2 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 3 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 4 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 5 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   [✗] Nov 29 13:43:47 dnsmasq[5189]: bad address at /etc/pihole/black.list line 6 (https://discourse.pi-hole.net/t/why-do-i-see-bad-address-at-in-pihole-log/3972)
   Nov 29 13:43:47 dnsmasq[5189]: read /etc/pihole/black.list - 0 addresses
```

**Comment by Mcat12** [comment]
What are the contents of `/etc/pihole/black.list`?

**Comment by ajp2k13** [comment]
applog.musical.ly
eu-auth2.samsungosp.com
graph.facebook.com
realtime.roblox.com
vma.tgdaily.com
xlog-va.byteoversea.com

I tried deleting the blacklist and entering the hostnames again through the GUI but same thing.

**Comment by ajp2k13** [comment]
Sorry but how do I do that?

**Comment by Mcat12** [comment]
```
pihole checkout core release/v4.1
pihole checkout web release/v4.1
pihole checkout ftl release/4.1
```

**Comment by ajp2k13** [comment]
Ok, thanks! How do I check that I have the correct versions?

**Comment by ajp2k13** [comment]
Blacklist seems to be workgin again, thanks! :+1:
