### ISSUE TITLE
Add to Whitelist will actually adds to Blacklist

### ISSUE THREAD

**Issue by SlySalimander** [pi-hole/pi-hole#2528]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Add to Whitelist button will add to the Blacklist.`

**Actual behaviour:**

`The "Whitelist" button will add things to the Blacklist.

This happens when you review the history.  You have the option to add things from the history to the Blacklist or the Whitelist.  But it does not matter what button you select.  It will always add that selection to the Blacklist.`

**Steps to reproduce:**

`Go to Pie-hole Console with a web browser.

Chose "Long Term Data" and under that chose "Query Log"

Under time and date select anything you want.  Today will be the fastest.

On the Right side under "action", there is a button next to each event in the log.

Select "Whitelist" on an event that was Pi-holed.

Next visit your List of Blacklisted sites.

Here you can see that the site was added to the Blacklist and not to the Whitelist.`

**Comment by SlySalimander** [comment]
Pi-hole version is v4.0 (Latest: v4.0)
AdminLTE version is v4.0 (Latest: v4.0)
FTL version is v4.0 (Latest: v4.0)

**Comment by Mcat12** [comment]
This is a web interface issue, and is fixed by pi-hole/AdminLTE#833
