### ISSUE TITLE
Request: Dark Mode & Color Blind Dashboard

### ISSUE THREAD

**Issue by ZV00** [pi-hole/pi-hole#2529]
This is a feature request for a Dark Mode and Color Blind UI for the Dashboard. Currently, it uses a light mode that would feel a lot better as a dark mode in darker rooms. Additionally, a lot of lines go between red/green which are prime colors for people who are colorblind to have difficulty seeing. A version that could let the user alter colors of text would be incredibly helpful for an accessibility option.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
