### ISSUE TITLE
E: Package 'lighttpd' has no installation candidate

### ISSUE THREAD

**Issue by greymuse** [pi-hole/pi-hole#2533]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Running "sudo bash basic-install.sh" should perhaps handle missing packages gracefully, like saying "Error, a package cannot be installed, check your apt-get configuration".

**Actual behaviour:**

On a freshly installed rasbian stretch on a RP 3 model B+:
Due to unavailable package lighttpd the install script just dies without any explanation, the last lines looking like this:

[✓] Checking for libcap2-bin
  [i] Checking for dns-root-data (will be installed)
  [i] Checking for resolvconf (will be installed)
  [i] Checking for lighttpd (will be installed)
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cgi (will be installed)
  [i] Checking for php-sqlite3 (will be installed)

When apt-get cannot find a package its exit code is 100, aptitude exits with 255, which you could test for to handle that case.

**Troubleshooting undertaken, and/or other relevant information:**

Looking around I see that it is not uncommon that the lighttpd package cannot be installed. So far I haven't found a solution, like, adding other repository sources does not help.

De-selecting anything web-related makes install script complete, it seems, but I am not so familiar with pi-hole yet that I can evaluate if it works as it should.

(By the way, I also noted that the install script wants to install resolvconf even though the package openresolv was already installed, but supporting both is perhaps too much work.)

Best regards, thank you for all the good work!

**Comment by dschaper** [comment]
If a dependent package is unavailable, then the process should halt. I don't know offhand how `debconf-apt-progress` handles calls for unavailable packages, but yes, there should be more logic to the process.

**Comment by yubiuser** [comment]
`debconf-apt-progress` was removed meanwhile https://github.com/pi-hole/pi-hole/pull/2962
