### ISSUE TITLE
TODO: localhost vs remote resolver for Pi-hole node.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#2535]
Determine whether to use localhost or remote resolver for all installations and all distributions.

**Comment by DL6ER** [comment]
We may want to a non-consistent way of handling it:

- Point the resolver to `localhost` on machines/distros we suppose are used for desktop browsing
-

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
