### ISSUE TITLE
Replace resolvconf with openresolv package

### ISSUE THREAD

**Issue by willswire** [pi-hole/pi-hole#2536]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{10}`

---
**Expected behaviour:**

`{Working install}`

**Actual behaviour:**

`{Install halts during package dependencies installation}`

**Steps to reproduce:**

`{Install using recommended steps}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{N/A}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Experiencing the same problem as @CJeffyB - was able to diagnose the installation of resolvconf as the issue. That package has been replaced by openresolv. Changing resolvconf to openresolv on line 199 of the default install script worked for me}`

**Comment by dschaper** [comment]
What distribution and release?

**Comment by williamwalker88** [comment]
This was testing the latest pi-hole production release with Raspbian Stretch on the Raspberry Pi.

**Comment by dschaper** [comment]
Can you share with us where you found that `resolvconf` has been replaced with `openresolv`?

**Comment by willswire** [comment]
Was unable to find supporting documentation - installation works now.
