### ISSUE TITLE
command not found (bc) installation

### ISSUE THREAD

**Issue by HabButterimAuge** [pi-hole/pi-hole#2537]
My Error:
`Zeile 172: bc: Kommando nicht gefunden.
`
Complete CMD:
`root@localhost:~#  curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.2.9-1
main: Zeile 172: bc: Kommando nicht gefunden.
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [i] Checking for dialog (will be installed)
  [✓] Checking for debconf
  [i] Checking for dhcpcd5 (will be installed)
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
`
how do I install bc? 
Thank!

**Comment by dschaper** [comment]
`sudo apt-get install bc`

**Comment by technicalpyro** [comment]
this appears to be an issue due to locale what language is your device set to use?

**Comment by HabButterimAuge** [comment]
@dschaper 
I tried already. Package bc not found
@technicalpyro
Im from germany, so the compurer language is german

**Comment by dschaper** [comment]
What distribution and what release of that distribution?

**Comment by HabButterimAuge** [comment]
Kali Linux 2018.4:)

**Comment by dschaper** [comment]
That's not a supported platform, you'll have to find out why there is no `bc` available. Or wait a bit for us to release version 4.1 which removes the dependency on `bc`.

**Comment by HabButterimAuge** [comment]
Oh my god.. Ok then sry for this stupid question^^ I will wait:) Its a great project!:-)

**Comment by dschaper** [comment]
Give things another try, we just released 4.1 and that should remove the `bc` dependency.
