### ISSUE TITLE
Regex blocking fails if privacy is set to "hide domains"

### ISSUE THREAD

**Issue by 0xbs** [pi-hole/pi-hole#2538]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi-hole fails to block domains that match a regex filter.

**Actual behaviour:**

The domains are not blocked but resolved.

**Steps to reproduce:**

1. Standard pi-hole setup, query logging can be either disabled or enabled and privacy level is set to "Show everything and record everything"
2. Set up a regex filter (I did it via the GUI):

       $ cat /etc/pihole/regex.list
       (^|\.)(facebook|fb|fbcdn|fbsbx|tfbnw)\.(com|net)$

3. Make sure the filter works:

       $ nslookup www.facebook.com localhost
       Server:		localhost
       Address:	::1#53
       
       Name:	www.facebook.com
       Address: 0.0.0.0

4. Go to Settings → Privacy, select _Hide domains: Display and store all domains as "hidden"_ and click the Apply button
5. Go to Setting → System and click _Restart dnsmasq_
6. Now the filter no longer works: 

       $ nslookup www.facebook.com localhost
       Server:		localhost
       Address:	::1#53
       
       Non-authoritative answer:
       www.facebook.com	canonical name = star-mini.c10r.facebook.com.
       Name:	star-mini.c10r.facebook.com
       Address: 157.240.20.35

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Will only provide if cannot be reproduced.
```
*** [ DIAGNOSING ]: Core version
[i] Core: v4.0 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v4.0-0-gddbdb51

*** [ DIAGNOSING ]: Web version
[i] Web: v4.0 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v4.0-0-gaf8c926

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v4.0

*** [ DIAGNOSING ]: dnsmasq version
[i] 340:

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.45

*** [ DIAGNOSING ]: Pi-hole processes
[✗] dnsmasq daemon is inactive
[✓] lighttpd daemon is active
[✓] pihole-FTL daemon is active
```

**Troubleshooting undertaken, and/or other relevant information:**

n/a

**Comment by DL6ER** [comment]
This has already been reported here https://github.com/pi-hole/FTL/issues/414 and will be fixed in the upcoming Pi-hole v4.1.
