### ISSUE TITLE
"man pihole" for V4.1 does not match privacy levels

### ISSUE THREAD

**Issue by jfb-pihole** [pi-hole/pi-hole#2541]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
6
---
**Expected behaviour:**

"man pihole" should list the same privacy levels as offered in the web admin interface

**Actual behaviour:**

`pihole -a -h` shows the following 

  -l, privacylevel    Set privacy level (0 = lowest, 3 = highest)

**Steps to reproduce:**

Run command `man pihole` or `pihole -a -h` in V4.1

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

not applicable

**Troubleshooting undertaken, and/or other relevant information:**

Noted by a Reddit user (blankk-bot)on the V4.1 announcement thread: https://www.reddit.com/r/pihole/comments/a4pbxg/pihole_v41_is_now_available/

I confirmed the behavior on a new update to V4.1

**Comment by dschaper** [comment]
Fixed in #2600
