### ISSUE TITLE
Bug 4.1 does not work anymore with unbound

### ISSUE THREAD

**Issue by nitschkecm** [pi-hole/pi-hole#2544]
**How familiar are you with the the source code relevant to this issue?:** 0

**Expected behaviour:**
Since I have upgrade to 4.1 I have there are no more log entries and I cannot access certain sites. Having configured unbound as describe in previous blog post.

`{A detailed description of what you expect to see}`

**Actual behaviour:**
IP addresses do not seem to be checked / forwarded

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`
**Debug token provided : 47l8jr99d5
**Troubleshooting undertaken, and/or other relevant information:**
will activate for the moment my usual DNS providers

`

**Comment by dschaper** [comment]
It looks like you have configured Pi-hole to listen on `tun0` but all of your clients are on `eth0`? The log is showing queries from the 192.168.x.x network. Can you check the logs from `unbound` to see if there is any activity?

**Comment by nitschkecm** [comment]
Not anymore. I needed the solution to work so have removed unbound for the moment. I figured later that there was a problem. However I did not have the chance to select eth0 as interface. 
Question now is could I install Unbound again and get back to the original config?

**Comment by jfb-pihole** [comment]
I run unbound on all the versions from 4.1 up through latest master and dev branch, with no problems.

**Comment by dschaper** [comment]
Closing: Stale
