### ISSUE TITLE
Without Admin/website options, 4.0 > 4.1 update fails

### ISSUE THREAD

**Issue by gonzoblue** [pi-hole/pi-hole#2545]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
I have installed pihole without the admin interface, website or logging options.
I expect running pihole -up will only update the pieces I have installed and ignore the options I have not installed.

**Actual behaviour:**
When on 4.0, running 'pihole -up' to get to 4.1 I get an error on resetting /var/www/html/admin
The updater exits at that point. That folder does not exist because I don't have the website or admin interface installed.

**Steps to reproduce:**
Install 4.0 without the website, admin interface or logging. Then run pihole -up

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
None taken

**Troubleshooting undertaken, and/or other relevant information:**
Instead I ran pihole -r and "reinstalled" with all the same options as before (no website, no admin, no logging) and everything was updated to 4.1 without issue.

**Comment by Mcat12** [comment]
Do you know if the `INSTALL_WEB_INTERFACE` and `INSTALL_WEB_SERVER` settings in `/etc/pihole/setupVars.conf` were set to false?

**Comment by gonzoblue** [comment]
They are both false now, but I'm not sure what they were before. I did install with those options not selected originally, so I assume they would be but I'm not actually sure.

**Comment by nynhex** [comment]
@gonzoblue i believe they should be `true`

**Comment by Mcat12** [comment]
It may have been that those options were missing somehow (or incorrect), because looking at the code, a check for those settings wraps the web install code. Can you share the original error and the update log?

**Comment by gonzoblue** [comment]
I have a backup of that file from Jun 30, those values are missing. Where is the update log located?
```
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=0.0.0.0
IPV6_ADDRESS=
PIHOLE_DNS_1=1.1.1.1
PIHOLE_DNS_2=1.0.0.1
QUERY_LOGGING=false
INSTALL_WEB=false
LIGHTTPD_ENABLED=1
TEMPERATUREUNIT=F

```

**Comment by Mcat12** [comment]
There is no update log (it is just the console output of the update command). It seems that you had an older install, and the necessary setting values weren't populated correctly when you updated. Do you know what version you had before the update?

**Comment by gonzoblue** [comment]
It was 4.0 before this update, but I probably updated to that from an earlier version. That Pi has been in use since Sept 2017, so whatever was current at that time. The error from memory on the console was something about resetting /var/www/html/admin and then that it couldn't write to it. When I checked it was because it actually doesn't exist.

**Comment by Mcat12** [comment]
Here is the code which should have updated the `INSTALL_WEB=false` setting to `INSTALL_WEB_INTERFACE=false` and `INSTALL_WEB_SERVER=false`:
https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/automated%20install/basic-install.sh#L1742-L1750

This is called on every update and repair, here:
https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/automated%20install/basic-install.sh#L1782-L1785

Because v4.0 was not released until after your backup, you were probably running v3.3.1 (which does not use these newer settings) when you took the backup. Do you have a backup of when you were running v4.0?

**Comment by dschaper** [comment]
Closing: Stale
