### ISSUE TITLE
pihole -v without website/admin interface returns error

### ISSUE THREAD

**Issue by gonzoblue** [pi-hole/pi-hole#2546]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
pihole -v should return the version numbers of all the installed features.

**Actual behaviour:**
Without the website/admin interface installed, it returns an error when trying to show the admin version:
```
#pihole -v    
Pi-hole version is v4.1 (Latest: v4.1)  
fatal: Not a git repository (or any of the parent directories): .git    
AdminLTE version is ERROR (Latest: v4.1)    
FTL version is v4.1 (Latest: v4.1) 
```

**Steps to reproduce:**
Install pihole without website/admin pieces, then run pihole -v

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
None taken

**Troubleshooting undertaken, and/or other relevant information:**
No attempt to fix, does not actually break anything but only looks confusing.

**Comment by dschaper** [comment]
Fixed in #2600
