### ISSUE TITLE
Possible issue with static assets on domain whitelist

### ISSUE THREAD

**Issue by vito-c** [pi-hole/pi-hole#2548]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I added a domain to the whitelist filter but it is still having troubles loading it's content. The domain is`www.carters.com` It looks like all of their cdn assets are blocked. When I disable pi-hole for 5 mins it works.

**Actual behaviour:**
none of the assets load on the whitelisted domain

Do you need more info?

**Comment by dschaper** [comment]
The assets are most likely not coming from `www.carters.com` but from another domain/subdomain. I just loaded that main page and checked with F12 on Chrome and there are a number of domains that are used to server assets on that site. 


![annotation 2018-12-14 084118](https://user-images.githubusercontent.com/2782850/50015774-2feeb200-ff7c-11e8-9b12-f93412d4cf8f.jpg)

**Comment by dschaper** [comment]
Closed: Stale
