### ISSUE TITLE
Empty Dnsmasq.conf after upgrade to 4.1

### ISSUE THREAD

**Issue by Nwinternights** [pi-hole/pi-hole#2553]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**
After Upgrade to 4.1, dnsmasq.conf shouldn't be  modified

**Actual behaviour:**
After Upgrade to 4.1, dnsmasq.conf is copied to dnsmasq.conf.old and created a new file with only one line that points to conf dir.

In old Dnsmasq.conf there's some custom configs such as static sinkholed domain or multiple conditional forwarding and some other tunings
**Steps to reproduce:**
Upgrade from 4.0 to 4.1
`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
Cp old dnsmasq to newly created
> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
This is expected behavior:
https://github.com/pi-hole/pi-hole/blob/f65f793a0d0d7dbc5882be38858c986f42b8c776/automated%20install/basic-install.sh#L2180-L2188

Are you asking for this behavior to be changed?

**Comment by PromoFaux** [comment]
Ideally, if you want to have some custom `dnsmasq` settings, you should add them to a separate file in `/etc/dnsmasq.d/`, so that they are preserved through updates.

**Comment by Nwinternights** [comment]
Tks for the quick answer. @PromoFaux  indeed, that's what I did. I don't know but It would be an Idea to prompt/warn, during the upgrade process, if you want to keep dnsmasq conf or not, at least to warn the user that all custom settings inside that file will be renamed instead of just a line during the upgrade process.
