### ISSUE TITLE
Pihole not properly resting name server upon uninstallation

### ISSUE THREAD

**Issue by Ge0rges** [pi-hole/pi-hole#2555]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [*] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [*] The issue I am reporting can be *replicated*.
- [*] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`The ping should go through as google.com will be properly resolved. The file should be reset to a valid value.`

**Actual behaviour:**

`ping google.com fails to resolve`

**Steps to reproduce:**

`1. Install Pihole
 2. do pihole uninstall
 3. cat /etc/resolv.conf or ping google.com`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`untp09d9oi`

**Troubleshooting undertaken, and/or other relevant information:**

`I've been playing around with various settings and systemd but ultimately changing resolve.conf name server to 8.8.8.8 fixes everything.`

**Comment by davidfornesm** [comment]
Can confirm exact same symptom and subsequent fix

**Comment by Mcat12** [comment]
At the end of the uninstallation output, this line appears:
> Please reset the DNS on your router/clients to restore internet connectivity

**Comment by davidfornesm** [comment]
Also worth noting, i've seen this happen when installing as well. The lack of a nameserver makes it impossible for the script to download and install FTLDNS. In order to finish the installation one must first add a nameserver to resolv.conf and finally use `pihole -r` to repair the installation.

**Comment by dschaper** [comment]
Yes, that's a longstanding glitch that can be fixed by checking and downloading the FTL binary and all dependencies before starting to install and apply. We should have everything needed locally by the time we are anywhere near ready to disable or restart the systems name resolver.

**Comment by davidfornesm** [comment]
@dschaper So is it planned to do this? I mean, seems like a very important part of the installation and ux.

**Comment by yubiuser** [comment]
Pi-hole has come a long way since this has been discussed. Since v5.0 Pi-hole does not modify `resolv.conf` anymore - so this issue should not happen anymore.
