### ISSUE TITLE
Can't install pihole on a VM [Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-66-generic x86_64)]

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#2565]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

`Correct Installation I guess?`

**Actual behaviour:**
stty: 'standard input': Inappropriate ioctl for device

.......

`[i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for lighttpd
  [✓] Checking for php-common
  [i] Checking for php-cgi (will be installed)
  [i] Checking for php-sqlite3 (will be installed)
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.
Use of uninitialized value $ret in scalar chomp at /usr/share/perl5/Debconf/Client/ConfModule.pm line 132, <STDIN> line 4.
Use of uninitialized value $ret in split at /usr/share/perl5/Debconf/Client/ConfModule.pm line 133, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/share/perl5/Debconf/Client/ConfModule.pm line 134, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/bin/debconf-apt-progress line 173, <STDIN> line 4.
`

**Steps to reproduce:**

`Tried with pipe bash and with git clone, same result`

**Comment by dschaper** [comment]
Take a look over https://www.reddit.com/r/pihole/comments/6n9e0w/cant_install_pihole_get_these_errors_tried/

**Comment by DenyDarko** [comment]
It seems apt-get install (just that) did the trick.

php was pending, probably the bash installation got interrupted.
