### ISSUE TITLE
Mining pools blocked all of a sudden?

### ISSUE THREAD

**Issue by Angel996** [pi-hole/pi-hole#2567]
I just found out Pihole blocked all mining pools, I am a miner, I cannot access mining stats on my work computer. I had to manually whitelist every mining pool website I use.

What is it, a new idea, mining process is malicious? It's just good I was here, if it were at night time, all my mining rigs would be offline w/o anyone asking me if I need this "service".

**Comment by technicalpyro** [comment]
this is not a Pi-hole issue per say and as you have completely ignored the issue template will likely be closed.  This is an issue with the blocklists you use.  Those blocklists are community maintained and not the responsibility of the project itself.  

If you can figure out which lists are blocking it feel free to contact the maintainers

**Comment by Angel996** [comment]
I understand now. Thank you, please close this.
