### ISSUE TITLE
Disabling twice clears blocklist and blacklist

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/pi-hole#2573]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

Disabling twice (via `pihole disable`) is the same as disabling once, and enabling afterwards works correctly.

**Actual behaviour:**

Disabling twice clears the blocklist and blacklist, so that after re-enabling, no domains are blocked.

**Steps to reproduce:**

Run these commands:
```
pihole enable
pihole disable
pihole disable
pihole enable
```

See that both `gravity.list`, `black.list`, and their respective `.bck` files are empty. Therefore, no domains are blocked.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
N/A

**Troubleshooting undertaken, and/or other relevant information:**
See https://www.reddit.com/r/pihole/comments/aazaqz/using_api_selecting_disable_twice_makes_it/

**Comment by dschaper** [comment]
So we move the list to list.bak and then zero out the list. If done a second time that moves the empty list to bak and overwrites the needed data.

https://github.com/pi-hole/pi-hole/blob/master/pihole#L159

**Comment by dschaper** [comment]
Instead of `if -e gravity.list` just checking for the file, probably should check to make sure gravity.list is non-zero length. If it's zero-length then it's already empty, don't move it to gravity.bak.

**Comment by dschaper** [comment]
```
dschaper@Mariner:~$ cat a.sh
if [[ -s test.list ]]; then
        echo "test.list is non-zero length"
else
        echo "test.list is zero length or doesn't exist"
fi

dschaper@Mariner:~$ bash a.sh
test.list is zero length or doesn't exist
dschaper@Mariner:~$ touch test.list
dschaper@Mariner:~$ bash a.sh
test.list is zero length or doesn't exist
dschaper@Mariner:~$ echo "" > test.list
dschaper@Mariner:~$ bash a.sh
test.list is non-zero length
```

**Comment by dschaper** [comment]
And `cat /dev/null > test.list` instead as `echo "" > test.list` actually makes a non-zero length file.

**Comment by diginc** [comment]
just `> test.list` works too

```
test.list ; test -s test.list || echo empty
empty
```

**Comment by PromoFaux** [comment]
Should we not also double down on that, and rather than just text for non-zero `gravity.list`, also check for the existence of `gravity.list.bck`?

```bash
    if [[ -e "${gravitylist}" && -e "${gravitylist}.bck" ]]; then
      echo "Pi-hole is already disabled"
    fi
```

Could do similar on `pihole enable`. If `gravity.list.bck` does not exist, then pi-hole is already enabled.

**Comment by PromoFaux** [comment]
Even simpler....
