### ISSUE TITLE
Monero XMR as an accepted form for the donation to Pi-hole

### ISSUE THREAD

**Issue by cialu** [pi-hole/pi-hole#2577]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---
**Expected behaviour:**

`Be able to make a donation to Pi-hole throught the` [Monero XMR](https://ww.getmonero.org/) `cryptocurrency`

**Actual behaviour:**

`Donations in crypto are available only in Bitcoin, Bitcoin Cash and Ethereum.`

**Steps to reproduce:**

`Go to` [Pi-hole donation page](https://pi-hole.net/donate/) `or on GitHub readme.`

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
