### ISSUE TITLE
Blocking ANY requests

### ISSUE THREAD

**Issue by BuckGup** [pi-hole/pi-hole#2583]
Due to some of us running a pihole on a VPS the IP is public so we are susceptible to DNS amplification attacks. Is there a way or maybe one you could add in the future to block certain types of requests. As blocking ANY requests, as cloudflare has done since 2014, would prevent such attacks. Thanks

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by PromoFaux** [comment]
Just as a side note, and to prevent you from wasting your time. You're unlikely to find anyone who is going to offer advice on running an open resolver, especially anyone from the team.
