### ISSUE TITLE
Adding HTTPS everywhere...

### ISSUE THREAD

**Issue by LiveChief** [pi-hole/pi-hole#2584]
Hey can u install HTTPS everywhere on pihole, it already removes all the ads how about redirecting the pages to HTTPS so it makes the end user much more safer online,,,

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
