### ISSUE TITLE
Raspbian Stretch Lite - no internet

### ISSUE THREAD

**Issue by e-moe** [pi-hole/pi-hole#2586]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Clients are able to use internet with pi-hole DNS; raspberry pi (with installed pi-hole) is able to use internet as well

**Actual behaviour:**

client laptop (with DNS set to pi-hole) and raspberry pi with installed pi-hole returns 500 server error on http requests. nslookup working correctly. http://pi.hole/ admin page is working and accesible.

```
pi@raspberrypi:~ $ ping google.com
PING google.com (194.50.85.176) 56(84) bytes of data.
64 bytes from 194.50.85.176 (194.50.85.176): icmp_seq=1 ttl=62 time=0.892 ms
64 bytes from 194.50.85.176 (194.50.85.176): icmp_seq=2 ttl=62 time=0.869 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.869/0.880/0.892/0.031 ms

pi@raspberrypi:~ $ nslookup github.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	github.com
Address: 194.50.85.176

pi@raspberrypi:~ $ wget google.com
--2019-01-07 16:22:15--  http://google.com/
Resolving google.com (google.com)... 194.50.85.176
Connecting to google.com (google.com)|194.50.85.176|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2019-01-07 16:22:15 ERROR 500: Internal Server Error.

pi@raspberrypi:~ $ wget github.com
--2019-01-07 16:24:12--  http://github.com/
Resolving github.com (github.com)... 194.50.85.176
Connecting to github.com (github.com)|194.50.85.176|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2019-01-07 16:24:12 ERROR 500: Internal Server Error.
```

**Steps to reproduce:**

Install pi-hone with all default options on Raspbian Stretch Lite (latest version 2018-11-13).
checked on both devices: raspberry pi zero and raspberry pi 3

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

pi-hole is unable to upload debug data

**Troubleshooting undertaken, and/or other relevant information:**

see above

**Comment by dschaper** [comment]
194.50.85.176 is not google or github. Have you set up your Pi-hole to return that address purposefully? 

`wget 194.50.85.176` returns a 500 error, as does browsing to that address manually, so things are operating correctly assuming that you intend for nslookup to return that IP address as the respsonse.

**Comment by e-moe** [comment]
>194.50.85.176 is not google or github. Have you set up your Pi-hole to return that address purposefully?
no

**Comment by e-moe** [comment]
oh, looks like I found issue - Cloudflare DNS. if I change pi-hole to use other dns (e.g. google) it's starting to work. strange

**Comment by e-moe** [comment]
There was an issue on ISP side.
