### ISSUE TITLE
DNS server selection differs from that in web UI

### ISSUE THREAD

**Issue by TheLastProject** [pi-hole/pi-hole#2591]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7. I can see how the web UI and the install script create the list, and I am knowledgeable enough to change both, but I'd rather see the lists merged in some way, like in an /etc/ file like gravity.list is, but I cannot figure out where these files come from and how to change it without breaking existing installations.

---
**Expected behaviour:**

The choice of DNS servers and the names they use at install time matches the list available in the Web UI after installation.

**Actual behaviour:**

The choice of DNS servers and the names they use at install time does not match the list available in the Web UI after installation.

**Steps to reproduce:**

1. Start installing Pi-Hole
2. Remember the available DNS servers
3. Go to the Web UI after install
4. Notice the list and names differ

**Troubleshooting undertaken, and/or other relevant information:**

I have looked at the source code to understand the issue and noticed they both use a different list. I thought of how to fix this and feel it'd be best to have a config file that both the installer and the web UI parse in the same way to prevent diverging lists and risks of typos.

**Comment by dschaper** [comment]
Thanks for the submission. This is on the verge of being a feature request but still partially a possible bug, I'd like to move the discussion to https://discourse.pi-hole.net where everyone can comment on this as just a small portion of the folks involved will see/comment on this issue.

What are your thoughts @TheLastProject ?

**Comment by TheLastProject** [comment]
That's fair, could help figure out the best way to improve on this :)

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
