### ISSUE TITLE
Custom Sudoers User

### ISSUE THREAD

**Issue by ghost** [pi-hole/pi-hole#2603]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`6`

---
**Expected behaviour:**

`I expect Pi-Hole to be able to edit blacklist and whitelists and update in realtime. I also expect only the enable or disable button to be on the screen at a time.`

**Actual behaviour:**

`Pi-Hole does not have permission to function properly because the user it runs under does not have sudoers access.`

**Steps to reproduce:**

`Install Pi-Hole and run the webserver (in my case NGinx) under a user that doesn't have sudoers permission.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Not Necessary - No Debug Token or Log`

**Troubleshooting undertaken, and/or other relevant information:**

https://discourse.pi-hole.net/t/blacklist-and-whitelist-not-working/16124/15

`I changed the Pi-Hole config /etc/init.d/pihole-FTL to run under my web user (web:web) and I added a sudoers entry "%web ALL=(root) NOPASSWD: /usr/local/bin/pihole".`

`I want to add the ability to choose a custom user to run Pi-Hole under at install time and then (add, or just tell the user to add) the sudoers entry to the sudoers file.`

**Comment by KyferEz** [comment]
I run Apache on CentOS7 along with a ICAP service and Apache serves the error pages for that service. I also use the same box for PiHole so I wanted it to run under Apache. Apache runs as user apache. 

I had to modify the following to get status in upper left to show correctly:
edit this file: /etc/sudoers.d/pihole
Modify this line: 
`litehttpd ALL=NOPASSWD: /usr/local/bin/pihole`
to be:
`apache ALL=NOPASSWD: /usr/local/bin/pihole`
Then restart the service:
`service pihole-FTL restart`

To get whitelist/blacklist to work, I had to run the below. Note Pihole is installed at /etc/pihole:
`chown -R apache:pihole /etc/pihole`

Now PiHole works properly.
