### ISSUE TITLE
CentOS 7 'service' not found during cron'd updateGravity

### ISSUE THREAD

**Issue by cwichura** [pi-hole/pi-hole#2615]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Cron'd updateGravity should successfully reload resolver after updating lists.

**Actual behaviour:**

Fails with:

  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter
  [✗] /usr/local/bin/pihole: line 132: service: command not found

**Steps to reproduce:**

Install fresh CentOS 7.6 minimal from minimal ISO
Install pi.hole
Wait for cron'd updateGravity to execute
Observe error in /var/log/pihole_updateGravity.log

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

It appears cron's $PATH for root does not include /usr/sbin/, which is where the 'service' command lives.  Adding this to the PATH munging in the crontab entry in /etc/cron.d/pihole corrects the problem.  However, the next time pihole updates, this will get overwritten.

**Comment by dschaper** [comment]
Glad you were able to find a fix for your situation.

**Comment by cwichura** [comment]
Without applying the fix in mainline pi-hole, it's going to require manually re-applying the fix every time you guys release an update, since you overwrite the /etc/cron.d/pihole file.  This will affect all CentOS 7 users.  Again, this is a vanilla 7.6 minimal install of CentOS with no customization.

**Comment by dschaper** [comment]
```
[root@centos-s-1vcpu-1gb-nyc1-01 ~]# whoami
root
[root@centos-s-1vcpu-1gb-nyc1-01 ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[root@centos-s-1vcpu-1gb-nyc1-01 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by cwichura** [comment]
The root user's path when run by cron is different than the path when run from an interactive prompt:

`[caw@pihole tmp]$ cat /etc/cron.d/test
*/5 *   * * *   root    /tmp/cronpath.sh > /tmp/cronpath.out
[caw@pihole tmp]$ cat cronpath.sh
#!/bin/bash

whoami
echo $PATH

[caw@pihole tmp]$ cat cronpath.out
root
/usr/bin:/bin
`

**Comment by dschaper** [comment]
The cronjob should be installed / run as a system cron and not a user cron. This is the first report of this issue and unless we have more information about the installation (I'll ask one last time for a debug token) then we can't help. 

I think this is related to the issue at hand and the two solutions involve editing files that we do not have access to, nor would we want to edit. https://unix.stackexchange.com/questions/148133/how-to-set-crontab-path-variable

**Comment by cwichura** [comment]
And again, as already listed above, the solution is for you to add /usr/sbin to the PATH munge you perform in /etc/cron.d/pihole.

Unless people are examining the log output in /var/log/pihole_updateGravity.log, they are probably completely unaware that the weekly update job is downloading new files, but not telling FTL to actually read them and its continuing to run with whatever was there when it was started.  There is no error indication in the UI.

**Comment by dschaper** [comment]
I just downloaded CentOS 7 1810 Minimal ISO. Installed on baremetal, no changes, no modifications. (SELinux still enforcing.) Ran `curl | bash` installation, edited `/etc/cron.d/pihole` to set firing time to every 5 minutes. Waited 5 minutes, checked /var/log/pihole_updateGravity.log and found pointer to code that hasn't changed in 2 years. 

We won't be adding `/usr/sbin/` to the PATH, adding a root only path to a cronjob isn't something I think we should be doing. The proper resolution is to add the full path to the `pihole` script for [`/usr/sbin/service`](https://github.com/pi-hole/pi-hole/blob/master/pihole#L114) and guard it with the proper privileges.
