### ISSUE TITLE
Almost constant DNS queries to github.com; issue was resolved in v.3.2.1. but is back now?!

### ISSUE THREAD

**Issue by Ashoka42** [pi-hole/pi-hole#2619]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pi-hole should send queries to github.com once a day/week for updates.`

**Actual behaviour:**

`Pi-hole sends DNS queries to github.com at a constant rate of about ever minute. This behaviour occurred the first time around January 20th. A rise/peak in DNS requests to github.com was found at this date in the query logfile. Requests to github.com are the number 1 queries, followed by requests to api.github.com. E.g.: 1744 requests to github.com within a week, followed by 151 requests to api.github.com, followed by dl.flathub.org with 134 requests. `

**Steps to reproduce:**

`Installed pi-hole on a fresh raspberry pi 3. After installation the logging showed DNS queries to github.com ever 1-2 minutes. No other software was installed/used.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`a8rk3stcwl`

**Troubleshooting undertaken, and/or other relevant information:**
OS: Linux Mint 19.1 on office PC; installed pi-hole also on a raspy 3 at home for network usage;
recently updated the software to 4.2.1, but issue is the same

Issue should have been resolved in version 3.2.1; additional information to similar bug are [here](https://discourse.pi-hole.net/t/constant-requests-to-api-github-com-from-pi-hole-device/4115)

**Comment by Mcat12** [comment]
What tells you that it is Pi-hole making these queries? The only time we make a query to GitHub without user prompting is when we check the latest available versions, which happens once a day and when the device reboots:
https://github.com/pi-hole/pi-hole/blob/e967fe2266212dea68ab3dc63b9d7848d26afd42/advanced/Templates/pihole.cron#L34-L36

**Comment by dschaper** [comment]
Resolved.
