### ISSUE TITLE
Versions are being disclosed to everyone

### ISSUE THREAD

**Issue by behemoth88** [pi-hole/pi-hole#2624]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

5

---

**[BUG | ISSUE] Expected Behaviour:**

Version of Pi-hole, Web Interface Version and FTL should not be disclosed unless user is logged in.

**[BUG | ISSUE] Actual Behaviour:**

Version is being displayed without login.

**[BUG | ISSUE] Steps to reproduce:**

- Visit your pihole admin webpage
- Scroll down
- Versions are displayed at the bottom of the page
-

**Device specifics**

Hardware Type: VPS
OS: Centos 7 x64

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by m-terlinde** [comment]
> Is there a security issue that this issue report addresses?
It is possible to have an inside attacker in the LAN. Restricting the web interface just on a management port isn't everytime possible. The Raspberry Pi has just one NIC and to do proper firewalling just for the GUI can be hard.

Imagine version X.X has a critical security flaw and the admin doesn't patch the system in time. Any person/user in the LAN can quickly check, if the installation is vulnerable and can pwn the system if he/she wants.

So I like the suggestion to omit the version until the user logs in.

**Comment by Mcat12** [comment]
Major web servers such as Apache and Nginx send their version information in HTTP responses. Most other software also does not hide the version number. Hiding the version number is just security by obscurity, it does not work. If there's a vulnerability, they attacker could just try the attack on every server they find, regardless of the version they say they are running.

**Comment by m-terlinde** [comment]
This is totally true.

Of cause if security-by-obscurity is your only line of defence, this is really bad.
But it can help you to reduce the impact of automated tools and fingerprinting.

E. g. if you run a public web server and omit the server version, it does not get indexed with your current version on Shodan.

**Comment by Mcat12** [comment]
Pi-hole is not made to protect you from getting indexed by Shodan. If you don't want your web server to be publicly accessible, don't make it publicly accessible. Lighttpd (the web server used by default in Pi-hole) does not hide its version, and neither do any other major web servers. If we hide the version from the web page, there are still other ways the version can be determined (ex. looking at the content of the page and comparing with the page as it appeared in past releases). This is not an issue Pi-hole can solve.

**Comment by m-terlinde** [comment]
I can follow your argumentation, but Shodan was just an example.

**Comment by Mcat12** [comment]
Shodan in my comment can be replaced by any other web scanner or public entity out there without changing the point.
