### ISSUE TITLE
pi-hole dns caching not working?

### ISSUE THREAD

**Issue by xSunshin3x** [pi-hole/pi-hole#2627]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
Query time with dig should be 0 msec

**Actual behaviour:**
Whenever i visit a site (e.g. https://www.golem.de) on my pc's broswer, then afterwards check the dns query time of that particular domain entry with the raspberrypi's tool 'dig', it shows me a query time result in the lower hundred area (in msec)

![dig2](https://user-images.githubusercontent.com/14875358/52496918-05645280-2bd5-11e9-86c3-f3845b26b886.JPG)

**Steps to reproduce:**
1) Visit a page of my choice in my computers broswer (here Google Chrome)(for a request of that site, it should have created a dns query (and therefore a cache entry, because that's how cache works, right?)
2) get query time with dig of that particular page, you'll get a high number (e.g. 120ms)
3) repeat step 2), so you'll get another query time now.
4) query time now is 0 msec, which it should do because the entry was cached at step 2)

So my question now is:
Is dns caching on my pi-hole setup not working at all?
Because as far as i understand, caching works like this: Whenever a dns request is made to the server, the server looks in his cache (because its faster than asking somebody) and if there's an entry for the request, send the answer. If not, ask somebody and store **that** result in the cache, so you dont have to ask him next time (and therefore safe time).
But in my case, it only starts caching when i do a manual dns lookup (then create a cache entry from that response, ...)

no debug token. sry

//**edit** pardon me. you're right @dschaper, but same results with www.domain.de instead of domain.de (or even worse?)

**Comment by dschaper** [comment]
The domains `heise.de` and `www.heise.de` are not the same and require two different lookups. Loading `www.heise.de` in to cache when you visit that domain in your browser does not load `heise.de` in to the cache.

**Comment by xSunshin3x** [comment]
You're right with that, however: When i dig for www.heise.de, i got the same result: Query time is high.
As you can see in the new screenshot above. For the domain "www.golem.de", it got me 366 msec after site-visit via browser, 117 msec for a second lookup (and atleast **now** it should be cashed because we did the exact same lookup literally 5 secs ago???

**Comment by dschaper** [comment]
The first `dig` was at 18:37:56, and the record had a TTL of 297 seconds left before the record expires and needs to be refreshed.

The second `dig` was at 19:05:10 and was a new lookup since the TTL showing is the SOA TTL of 600 seconds. The first `dig` had long expired, the 297 seconds left from that records lifetime was over. 

The third `dig` was at 19:05:13 and was cached as the TTL from the second `dig` hadn't forced the record out of the cache.

If you are changing the TTL to 5 mintues, then the max lifetime a record will live in cache is 5 minutes. If you are not manipulating TTL then you need to ask the owner of that domain why they are setting the TTL of their records to such a low value that for all intents prevents it from being cached.

**Comment by dschaper** [comment]
https://docs.pi-hole.net/ftldns/dns-cache/

Also you can check your admin interface, under settings, to see the current cache status. You should see entries in the cache and usage.

![capture](https://user-images.githubusercontent.com/2782850/52497646-6830fc00-2b8b-11e9-97b1-b7216a20daf0.PNG)

**Comment by xSunshin3x** [comment]
Of course there are DNS cache insertions on pihole. So caching obviously works and its not a bug.

But then again: It's more like a 'bad' configuration from the domain's owner/administrator in terms of caching? Does pihole use any TTL restrictions? i didnt found any TTL entries in the configs/wiki..

Only 4,6% of my queries are replied by cache. Is this a 'normal' cache percentage in a network?

**Comment by dschaper** [comment]
I just checked that domain and the owner has set the cache to be 600 seconds. That's the max anyone that is following the RFCs will cache the domain for. So unless you changed the minimum TTL in the configuration then 600 seconds is the max that we would cache that record.

**Comment by xSunshin3x** [comment]
i had 'local-ttl=2' in my 01-pihole.conf
No idea where that came from.

Sorry

**Comment by dschaper** [comment]
That's actually fine to have and part of the stock Pi-hole configuration. That just deals with domains from your local hosts files.

>local-ttl=<time>
When replying with information from /etc/hosts or configuration or the DHCP leases file dnsmasq by default sets the time-to-live field to zero, meaning that the requester should not itself cache the information. This is the correct thing to do in almost all situations. This option allows a time-to-live (in seconds) to be given for these replies. This will reduce the load on the server at the expense of clients using stale data under some circumstances
