### ISSUE TITLE
Feature request: Possibility to whitelist per IP address or range of ip adresses

### ISSUE THREAD

**Issue by gnfpt** [pi-hole/pi-hole#2628]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
It should be possible to whitelist a domain based on the client IP address.  As an example, my AppleTV won't start TED talks unless "partnerad.l.doubleclick.net" is whitelisted. This is acceptable for my AppleTV but I don't need this is my computer so I want it blocked.

`{A detailed description of what you expect to see}`
Possibility to set an IP address or even a range of IP addressed when whitelisting a domain.

**Actual behaviour:**
You can only set the domain.

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
whitelist a domain

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
None. This is a feature request not an actual bug.

**Comment by PromoFaux** [comment]
Thanks for taking the time to fill out the template, however... you missed a bit :)

>All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)

**Comment by PromoFaux** [comment]
That said, it's an oft-requested feature, it's just not easily achieved.

https://discourse.pi-hole.net/t/allow-temporary-and-allow-by-ip/1503
