### ISSUE TITLE
Update FTL 4.2.1 causing trouble with PiVPN

### ISSUE THREAD

**Issue by nitschkecm** [pi-hole/pi-hole#2631]
**How familiar are you with the the source code relevant to this issue?:**
1
**Expected behaviour:*
Be able to navigate and route all traffic through PIVPN and PiHole

**Actual behaviour:**

I can connect and navigate for a short while then I am loosing incoming traffic. 

**Steps to reproduce:**

s74fikgf0f

**Troubleshooting undertaken, and/or other relevant information:**
Nothing so far

**Comment by dschaper** [comment]
Everything looks fine from the debug log. Are your clients unable to resolve DNS names?

**Comment by nitschkecm** [comment]
I have just tried that and it seems to not work

**Comment by dschaper** [comment]
We'll need more detail to help. What kind of clients, what are you doing to test, what kind of errors, etc... Any detail you can provide will help us.

**Comment by nitschkecm** [comment]
Hi

regarding clients both browser as well as shell. 
What am I trying: 
- simple navigation (pages not resolving)
- ssh / ping

I have implemented pi-hole with https://pi-hole.net/2018/06/09/ftldns-and-unbound-combined-for-your-own-all-around-dns-solution/ 

I had once caused some issued with FTL update and I am afraid that might be the case again. I have switched back to my ISP DNS and it seems to all work now.

**Comment by dschaper** [comment]
We'll need to know the exact commands you executed on the clients and what error messages were displayed.

**Comment by DL6ER** [comment]
This issue has been inactive for more than one month and FTL received two updates (if the issue was caused by FTL, at all). Please feel free to re-open this issue ticket if the issue persists after updating to the latest version of Pi-hole (`pihole -up`).
