### ISSUE TITLE
pi-hole stopped resolving 

### ISSUE THREAD

**Issue by smfoo** [pi-hole/pi-hole#2632]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`pi-hole should resolve DNS names`

**Actual behaviour:**

`pi-hole stopped resolving dns names`

**Steps to reproduce:**

`happened out of the blue`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`sxhzmjvnfe`
Note: Added a temporary DNS to /etc/resolv.conf to make the upload work

**Troubleshooting undertaken, and/or other relevant information:**

`pihole -r` did not help (after adding a temporary DNS to `/etc/resolv.conf`)
Webinterface works and does not show any errors except the `BOGUS` under each query

Output of `pihole status`:
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

`nslookup github.com`
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find github.com: SERVFAIL

Output of `sudo service pihole-FTL status`

● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)
   Active: active (exited) since Wed 2019-02-13 10:14:03 CET; 29min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25850 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)
  Process: 25908 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
      CPU: 0
   CGroup: /system.slice/pihole-FTL.service

Feb 13 10:14:02 raspberrypi systemd[1]: Starting LSB: pihole-FTL daemon...
Feb 13 10:14:02 raspberrypi pihole-FTL[25908]: Not running
Feb 13 10:14:02 raspberrypi su[25950]: Successful su for pihole by root
Feb 13 10:14:02 raspberrypi su[25950]: + ??? root:pihole
Feb 13 10:14:02 raspberrypi su[25950]: pam_unix(su:session): session opened for user pihole by (uid=0)
Feb 13 10:14:03 raspberrypi pihole-FTL[25908]: FTL started!
Feb 13 10:14:03 raspberrypi systemd[1]: Started LSB: pihole-FTL daemon.

  Current Pi-hole version is v4.2.1
  Current AdminLTE version is v4.2
  Current FTL version is v4.2.1

**Comment by dschaper** [comment]
SERVFAIL is a valid response and BOGUS is valid. DNSSEC is failing for some reason. Try changing your upstream to a different one to test if the upstream is responding with bad data or disable DNSSEC to check the upstream status as well.

**Comment by smfoo** [comment]
Thanks, changing the upstream server did resolve the issue.
