### ISSUE TITLE
whitelist and blacklist issue when adding then removing top level domain

### ISSUE THREAD

**Issue by sectoramen** [pi-hole/pi-hole#2634]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`adding a top level domain such as .com in the whitelist and removing a top level domain such as .com from the whitelist should result in only the .com being removed and not all domains ending in .com, i.e. google.com being removed too`

**Actual behaviour:**

`adding .com and removing .com from the whitelist results in all domains ending in .com to be removed.`

**Steps to reproduce:**

`Click on whitelist -> type com in the field and click add -> delete com and refresh the page. All .com are gone`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{jskx0bfkch}`

**Troubleshooting undertaken, and/or other relevant information:**

`{None. tested on whitelist exact match with the same behaviour but did not test wildcard or regex}`

**Comment by dschaper** [comment]
You are adding a TLD to the whitelist and then removing that same TLD from the blacklist? The whitelist should override anything in the blacklist and not need to be removed?

**Comment by sectoramen** [comment]
- Let's assume I have a.com, b.com and c.com in the **whitelist**. I decide to add .com and keep the other domains in case I decide to remove .com later. I then decide to remove .com and but all my other domains ending in .com are gone. 

- Let's assume I have a.com, b.com and c.com in the **blacklist**. I decide to add .com and keep the other domains in case I decide to remove .com later. I then decide to remove .com and but all my other domains ending in .com are gone.

**Comment by dschaper** [comment]
The whitelist should prevent you from adding in `.com` as a domain, we do not have the capability to wildcard whitelists like that. 

I'll review the other issues to see, but I think you are trying to use the tools in ways they were not designed.
