### ISSUE TITLE
Pihole suddenly goes nutty with the statistics

### ISSUE THREAD

**Issue by aram535** [pi-hole/pi-hole#2635]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Actual behaviour:**

https://imgur.com/a/nCTn0mV
![pihole](https://user-images.githubusercontent.com/3215912/52845352-e2560900-30d4-11e9-9304-246cf3b24f3c.PNG)

**Steps to reproduce:**

`Wait 12 hours`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`417u9x1uxo`

**Troubleshooting undertaken, and/or other relevant information:**

Not too much, just restarted it a couple of times and have it repeat the bad behavior.  I have double checked with wireshark and I don't see anything close to this level of data on my network

NOTES: 
- This is an older version: 4.1.1 
- This is running in a docker container

**Comment by aram535** [comment]
We can close this off as upgrading to the new version v4.2.1.  If the problem persist I'll open a new ticket and reference this one.

**Comment by dschaper** [comment]
If you do, open it at https://github.com/pi-hole/docker-pi-hole

**Comment by aram535** [comment]
You really think it's docker related?

**Comment by dschaper** [comment]
I don't know, I didn't look at it, but the docker repo is the more appropriate repository to open an issue at and if you open one on the pi-hole/pi-hole repo it will just be moved to docker-pi-hole anyways.

**Comment by dschaper** [comment]
It's not a pi-hole issue directly now that I've reviewed it. One of your clients is spamming queries and Pi-hole is doing it's job to attempt to resolve the queries that are being sent to it.

```

*** [ DIAGNOSING ]: Pi-hole log
-rw-r--r-- 1 pihole pihole 52826030 Feb 15 03:48 /var/log/pihole.log
   -----head of pihole.log------
    
   Feb 15 00:00:01 dnsmasq[867]: query[PTR] db._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:01 dnsmasq[867]: forwarded db._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] r._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded r._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] b._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded b._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] db._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded db._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] r._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded r._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] db._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded db._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] b._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded b._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] r._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded r._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] r._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: forwarded r._dns-sd._udp.0.1.168.192.in-addr.arpa to 192.168.1.1
   Feb 15 00:00:02 dnsmasq[867]: query[PTR] db._dns-sd._udp.0.1.168.192.in-addr.arpa from 192.168.1.1
```

**Comment by dschaper** [comment]
You have a loop. 192.168.1.1 is querying Pi-hole which is asking it's upstream (192.168.1.1) to resolve the queries, which is then asking Pi-hole, etc...

**Comment by aram535** [comment]
I saw the incoming requests but as far as wireshark can tell me, excluding this one machine, there is very little traffic on 53 tcp or udp.  That's the odd behavior ... and it suddenly starts doing it.  So if stop pihole, delete the database/files and restart it ... the behavior stops.  Then starts again at some point again.

**Comment by aram535** [comment]
I do have "Conditional Forwarding" enabled.  Should I turn that off?

**Comment by dschaper** [comment]
You can't have an upstream be a client.

**Comment by aram535** [comment]
192.168.1.1 is the router ... it isn't exactly upstream.

**Comment by dschaper** [comment]
```
   server=/mbcli.com/192.168.1.1
   server=/1.168.192.in-addr.arpa/192.168.1.1
```

These lines are what is causing the issue, it's doing exactly what you have instructed it to do. It's forwarding `xxxxx.1.168.192.in-addr.arpa` queries to 192.168.1.1. But 192.168.1.1 doesn't know how to answer those queries and 192.168.1.1 has been told to ask Pi-hole for the answers. And Pi-hole asks 192.16.1.1 for the answer and you end up in a loop. Very little traffic flows in UDP and you end up with an amplification attack and DDOS yourself.

**Comment by aram535** [comment]
Other than the conditional forwarding is there another configuration that would cause this?  I cannot see where it's getting the IP of the router as the next DNS hop, it should be going to 1.1.1.1.

**Comment by dschaper** [comment]
`db._dns-sd._udp.0.1.168.192.in-addr.arpa` is the query pattern. That matches `xxxx.1.168.192.in-addr.arpa` which is conditionally forwarded to 192.198.1.1 starting the deluge of queries in a loop.
