### ISSUE TITLE
.js calls are not replaced by the Pi-hole html

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#264]
It looks like adverts that are served up by scripts are not replaced by the `index.html` provided by Pi-hole. In the below `lighttpd/access.log` snippet only the call to amazon-adsystem is replaced, the others are just rendered as blank spaceholders in the Chrome browser. 

```
1454123251|rcm-na.amazon-adsystem.com|GET /e/cm?t=oxd-20&o=1&p=12&l=st1&mode=electronics&search=Apple&fc1=000000&lt1=_blank&lc1=3366FF&bg1=FFFFFF&f=ifr HTTP/1.1|200|153
1454123273|w.sharethis.com|GET /button/buttons.js HTTP/1.1|304|0
1454123273|tags.expo9.exponential.com|GET /tags/OSXDailycom/ROS/tags.js HTTP/1.1|304|0
1454123273|www.google-analytics.com|GET /urchin.js HTTP/1.1|304|0
1454123273|stats.wordpress.com|GET /e-201604.js HTTP/1.1|304|0
1454123273|rcm-na.amazon-adsystem.com|GET /e/cm?t=oxd-20&o=1&p=12&l=st1&mode=electronics&search=Apple&fc1=000000&lt1=_blank&lc1=3366FF&bg1=FFFFFF&f=ifr HTTP/1.1|304|0
1454123274|s3.buysellads.com|GET /ac/bsa.js HTTP/1.1|304|0
1454123328|stats.wp.com|GET /e-201604.js HTTP/1.1|200|153
```

**Comment by Mcat12** [comment]
So it should be replacing the space with the Pi-hole's blank page or gif?

**Comment by dschaper** [comment]
That I'm not sure of. If we replace it with the Pi-hole page will it break the flow of the page? May need to play around with it and see which option is best.

**Comment by PromoFaux** [comment]
I don't think this is something we can fix, as such. To use an example on `osxdaily.com`.
```HTML
<!-- BuySellAds Zone Code -->
<div id="bsap_1278263" class="bsarocks bsap_95cb8853ab792f424634d57b5de28eed"></div>
<!-- End BuySellAds Zone Code -->
```

```HTML
<!-- BuySellAds Ad Code -->
<script type="text/javascript">
(function(){
  var bsa = document.createElement('script');
     bsa.type = 'text/javascript';
     bsa.async = true;
     bsa.src = 'http://s3.buysellads.com/ac/bsa.js';
  (document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);
})();
</script>
<!-- End BuySellAds Ad Code -->
```

Now. The javascript at the bottom is going off to get it's instructions, except we're just returning some html in it's place. So the script does not complete properly, and the ad is never rendered. 

As far as I'm aware, to replace ALL ads on a page with an image, we'd need to know the ID of each element that contains the ad. (Some of which are generated after the external script is loaded)

It would be like playing whack-a-mole blindfolded.

**Comment by dschaper** [comment]
I think this may fall under the Nice To Have category. The concern I had was breaking page flow, but if it's getting into Whack-A-Mole, then let's just leave it with the default rendering.

**Comment by PromoFaux** [comment]
We'd have to know the IDs of every single ad element on every single page...

**Comment by dschaper** [comment]
Okay, then I'll close this out, but it's in the Issues history in case we need to visit the issue in the future.
