### ISSUE TITLE
comm: file 1 is not in sorted order

### ISSUE THREAD

**Issue by MacFlurry** [pi-hole/pi-hole#2641]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
Hello,

doing `docker logs pihole`
I noticed this:
```
comm: file 1 is not in sorted order
comm: file 1 is not in sorted order
comm: file 1 is not in sorted order
comm: file 1 is not in sorted order
comm: file 1 is not in sorted order
comm: file 1 is not in sorted order
```
 How this could be fixed ?

Best regards

**Comment by dschaper** [comment]
Can you get us a `pihole -d` token so we can check the installation?

**Comment by iainp999** [comment]
I'm running the docker image and seeing this issue too.

https://www.reddit.com/r/pihole/comments/b1dhqc/pihole_doesnt_seem_to_update_lists/

**Comment by iainp999** [comment]
Currently disabling, re-enabling blocklists one by one.

Will post any that cause issues!

**Comment by iainp999** [comment]
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt

**Comment by dschaper** [comment]
Please open a new issue, filling out the template with the requested information. This issues is closed.
