### ISSUE TITLE
Installer fails to ceate pihole-FTL.service on CentOS 7

### ISSUE THREAD

**Issue by Neepawa** [pi-hole/pi-hole#2642]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [C] The issue I am reporting can be *replicated*.
- [C] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
10
---
**Expected behaviour:**

The installer creates file `/etc/init.d/pihole-FLT.service` by copying it from `${PI_HOLE_LOCAL_REPO}/advanced/Templates/pihole-FTL.service`

**Actual behaviour:**

The line is coded incorrectly: `/Templates` is missing from the source path. The *install* command fails, but the error is not trapped even though `set -e` is in effect.

**Steps to reproduce:**

Run the installer on CentOS 7.

**Comment by dschaper** [comment]
The path is correct, https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole-FTL.service

**Comment by dschaper** [comment]
And it looks like that line in the installer hasn't changed in 7 months.

https://github.com/pi-hole/pi-hole/blame/ba1e94d3d9cf1894e0b5adca3e92738d21897568/automated%20install/basic-install.sh#L2154

**Comment by Neepawa** [comment]
I just learned something new: check the source code as it appears *before* one applies custom patches. 

Closing issue as "Not a bug."
