### ISSUE TITLE
Error during Pihole update (dnsmasq.conf)

### ISSUE THREAD

**Issue by elderlabs** [pi-hole/pi-hole#2648]
**In raising this issue, I confirm the following:**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

`Pi-hole should up update successfully on my machines.`

**Actual behaviour:**

```/etc/dnsmasq.conf`'s permissions are reset to root-only access.```

```cannot read /etc/dnsmasq.conf: Permission denied```

**Steps to reproduce:**

`pihole -up`

**Debug token:**

`05pddnzqxy`

**Troubleshooting undertaken, and/or other relevant information:**

1. `systemctl status pihole-FTL`
2. `chmod 644 /etc/dnsmasq.conf`
3. `systemctl restart pihole-FTL`

---

Please keep in mind this is an issue on all Pi-hole instances I have. None have been modified from their original configuration upon installation, and this issue only appears to happen during a Pi-hole update, specifically when it checks if DNS resolution is working, then hits the two-minute timer.

**Comment by dschaper** [comment]
All configurations should be stored in `/etc/dnsmasq.d/*.conf`. `/etc/dnsmasq.conf` is not used with the exception of instructing `pihole-FTL` / `dnsmasq` to look in `/etc/dnsmasq.d` for `.conf` configuration files.

**Comment by elderlabs** [comment]
@dschaper correct, however, it's unable to access the file after a Pi-hole update because apparently somewhere in-between, the file's permissions are being reset, even after I specifically set them, and nothing else on the machine has a reason to mess with the file, other than Pi-hole.

I'll continue to investigate and monitor the issue, but between my VM, local server, and a few RPIs, they all have the same issue. I find it very odd. . . As of now, Pi-hole still has access to the file on each instance. I'll keep an eye on the them over the next few days, reboots, and a few `pihole -up` commands. I'm sure the issue will make itself know in that time because it's about every 3-7 days I need to fix the issue again as FTL refuses to start and leaves each site without internet access (which probably means it's happening on some sort of internal schedule somewhere, maybe cron). I swear if it's Debian, I'm nuking the part of the OS touching a file that didn't exist before PI-hole was installed.

Thanks for both your quick reply and for the Pi-hole software. Let's hope my future reply will have some useful information.

**Comment by curby** [comment]
I came up against this too.  I made a fresh Raspbian Lite install, upgraded packages via aptitude, and installed via the script.  Everything seemed to work except that pihole-FTL didn't start.  

Checking the log, I saw permissions errors on /etc/dnsmasq.conf, so I added go+r.  Restarted pihole-FTL, and it still didn't start.

Checking the log, I saw permissions errors on /etc/dnsmasq.d, so I added go+rx recursively.  Restarted pihole-FTL and it seems ok now.  

I didn't do too much more digging, but is a non-root user starting dnsmasq, and therefore failing because the configuration files are readable only by root?

**Comment by elderlabs** [comment]
@curby you are correct in what you're saying by what I've seen, however, pihole-FTL has it's own dnsmasq built-in, this pihole is the user attempting to read the dnsmasq config files, but cannot as they are not readable by any user other than root by default, and pihole does nothing to adjust permissions, as far as I can tell. What I do know is the perms of the dnsmasq file/folder are seemingly reset whenever I try to update pihole, so the service fails to start.

**Comment by rodeodomino** [comment]
Raising this back up -- I've actually noticed this error specifically when installing after a Wireguard install on my machine. For example:

1. Install linux kernel headers
2. Reboot
3. Install wireguard
4. Install pihole

_This causes the permissions error for Pi-hole_

If I do this instead:

1. Install linux kernel headers.
2. Reboot
3. Install wireguard
4. Reboot
5. Install pi-hole

_this works fine_

I wonder if there's some process or upgrade happening _somewhere_ on the system that's messing with permissions until a reboot (because I doubt this is related merely to Wireguard).

**Comment by Heat-Miser** [comment]
Hello,

I've encountered the very problem. I'm quite sure this is due to a umask command you used while installing wireguard.

This set up the default right for created files and then prevent an access to your dnsmaq config file by pihole-FTL service.

**Comment by elderlabs** [comment]
So was this fixed, or are we ignoring the issue?

**Comment by dschaper** [comment]
Can you be a little bit nicer and maybe we can discuss the issue? Since there's been no comments for a year and a half.

**Comment by elderlabs** [comment]
I mean no disrespect, but am frank in what I ask. The issue was described at length, and still exists at the moment. Given the ticket has been closed, but the issue seems to still exist across several installs, I'm left wondering whether the issue's been corrected and for whatever reason remains on my end (user error happens), or is being closed, as tends to happen with older tickets. Please do not mistake my condensed format for disrespect or rudeness, as I'm merely asking out of curiosity.

**Comment by jfb-pihole** [comment]
The ticket was closed because the problem cannot be duplicated on our end and the last post on this topic was 20 months ago (and your last post on this topic was 29 months ago).  As just one example, I have six Pi-hole instances running at the moment (various versions and platforms) and none show this issue.

Are you running Wireguard - there was a reply from a different user that discussed a Wireguard interference.

**Comment by elderlabs** [comment]
I understand the details you've outlined, however, continuing on closed issue reasoning probably isn't beneficial. Perhaps I should have provided more information over time, but didn't feel it was prompted.

My setup does not use a Raspberry Pi (but did at one time -- back in the pi-hole 4 days, it ran rather slowly on an rpi, so was moved to a Nuc, mostly because the blocklist is massive; I'm certain pi-hole 5 corrected that slowness). In most installs of pi-hole that do not use an rpi, I've seen this dnsmasq issue (lxc virtualized containers, and baremetal). The OS in question is a clean install of Debian (8-11 iirc), with the following packages installed additional from a base minimal install:
```
lsb-release ca-certificates command-not-found psmisc nano htop dialog tmux sudo zip iotop rsync curl cron locales nload python-apt localepurge ufw fail2ban bleachbit software-properties-common git ntpdate debconf-utils tcptrack iperf mtr net-tools ethtool lolcat unbound
```

Afterwards, the pi-hole deployment curl is executed. In instances where the `/etc/dnsmasq.conf` is inaccessible, pi-hole becomes stuck, waiting for access, or failing after a period. To combat this, I've used the following snippet when the issue presents itself, and before updates:
```
chmod 755 /etc/dnsmasq.* -R && chmod 744 /etc/pihole/dns-servers.conf && chown pihole:pihole /etc/dnsmasq.conf && chown -R www-data:www-data /var/www/ && chown -R pihole:pihole /etc/pihole/&& chmod 660 /etc/pihole/gravity.db && systemctl restart pihole-FTL.service && systemctl restart unbound
```
I'm certain some part of this snippet is questionable, but it was written in haste once upon a time to solve the issue on a system confined to my network. There are also portions to correct issues with Unbound as it likes to exit occasionally. Unbound is used for DoH from pi-hole to my upstream DNS provider, Cloudflare.

**Comment by jfb-pihole** [comment]
Since this issue is quite old and started many Pi-hole versions ago (much has changed since then), I recommend that you open a help ticket on discourse.pi-hole.net.  You can paste in all your current information shown above into the new topic on that site.  Also include an up-to-date debug token.
