### ISSUE TITLE
Pihole can't be opened after installation

### ISSUE THREAD

**Issue by thb007** [pi-hole/pi-hole#2649]
Pi hole can't be opened after installation. Go in xxxx/admin and display a bunch of code.

**Comment by thb007** [comment]
![screenshot_20190227-080447](https://user-images.githubusercontent.com/17548936/53455766-96a54700-3a66-11e9-831d-2c931bc3d396.jpg)

**Comment by thb007** [comment]
![screenshot_20190227-080725](https://user-images.githubusercontent.com/17548936/53455813-c0f70480-3a66-11e9-8b29-45022fdac1f2.jpg)

**Comment by dschaper** [comment]
`pihole -d` and upload token/link.

**Comment by thb007** [comment]
> `pihole -d` 并上传令牌/链接。

Okay, I'll try what you said after work.

**Comment by thb007** [comment]
> `pihole -d` 并上传令牌/链接。

https://tricorder.pi-hole.net/95uxw3a06h

**Comment by thb007** [comment]
> `pihole -d` 并上传令牌/链接。
Thank you.

I used "pi hole-d" to know that Lighttpd did not start, and then I restarted it with the command "/ etc/init.d/lighttpd restart" and now PI hole is working properly.

**Comment by dschaper** [comment]
Yes, `lighttpd` with PHP is required for the admin page.

**Comment by Mcat12** [comment]
Closing as the issue seems to be solved. If not, this can be reopened.
