### ISSUE TITLE
Universe repo in Debian

### ISSUE THREAD

**Issue by Floppik** [pi-hole/pi-hole#2651]
When i try upgrade to latest relase with pihole -up, i gave this error:
root@rock64 ~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Enabling universe package repository for Ubuntu Bionic
  [✓] Backed up current configuration to /etc/apt/sources.list.backup
Error: 'universe' invalid

If i try another command:
root@rock64 ~# curl -sSL https://install.pi-hole.net | sudo bash -x
+ set -e
+ installLogLoc=/etc/pihole/install.log
+ setupVars=/etc/pihole/setupVars.conf
+ lighttpdConfig=/etc/lighttpd/lighttpd.conf
+ coltable=/opt/pihole/COL_TABLE
+ webInterfaceGitUrl=https://github.com/pi-hole/AdminLTE.git
+ webInterfaceDir=/var/www/html/admin
+ piholeGitUrl=https://github.com/pi-hole/pi-hole.git
+ PI_HOLE_LOCAL_REPO=/etc/.pihole
+ PI_HOLE_FILES=(chronometer list piholeDebug piholeLogFlush setupLCD update version gravity uninstall webpage)
+ PI_HOLE_INSTALL_DIR=/opt/pihole
+ PI_HOLE_CONFIG_DIR=/etc/pihole
+ useUpdateVars=false
+ adlistFile=/etc/pihole/adlists.list
+ regexFile=/etc/pihole/regex.list
+ IPV4_ADDRESS=
+ IPV6_ADDRESS=
+ QUERY_LOGGING=true
+ INSTALL_WEB_INTERFACE=true
+ PRIVACY_LEVEL=0
+ '[' -z root ']'
++ stty size
stty: 'стандартный ввод': Неприменимый к данному устройству ioctl
++ printf '%d %d' 24 80
+ screen_size='24 80'
+ printf -v rows %d 24
+ printf -v columns %d 80
+ r=12
+ c=40
+ r=20
+ c=70
+ skipSpaceCheck=false
+ reconfigure=false
+ runUnattended=false
+ INSTALL_WEB_SERVER=true
+ [[ -f /opt/pihole/COL_TABLE ]]
+ source /opt/pihole/COL_TABLE
++ [[ -t 1 ]]
+++ tput colors
++ [[ 8 -ge 8 ]]
++ COL_BOLD=''
++ COL_ULINE=''
++ COL_NC=''
++ COL_GRAY=''
++ COL_RED=''
++ COL_GREEN=''
++ COL_YELLOW=''
++ COL_BLUE=''
++ COL_PURPLE=''
++ COL_CYAN=''
++ COL_WHITE=''
++ COL_BLACK=''
++ COL_LIGHT_BLUE=''
++ COL_LIGHT_GREEN=''
++ COL_LIGHT_CYAN=''
++ COL_LIGHT_RED=''
++ COL_URG_RED=''
++ COL_LIGHT_PURPLE=''
++ COL_BROWN=''
++ COL_LIGHT_GRAY=''
++ COL_DARK_GRAY=''
++ TICK='[✓]'
++ CROSS='[✗]'
++ INFO='[i]'
++ QST='[?]'
++ DONE=' done!'
++ OVER='\r'
+ binary=tbd
+ counter=0
+ [[ '' != true ]]
+ main
+ local 'str=Root user check'
+ printf '\n'

+ [[ 0 -eq 0 ]]
+ printf '  %b %s\n' '[✓]' 'Root user check'
  [✓] Root user check
+ show_ascii_berry
+ echo -e '
        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           '\''ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. '\'','\''.
                .'\'',,,,,,'\''.
              .'\'',,,,,,,,,,.
            .'\'',,,,,,,,,,,,....
          ....'\'''\'''\'',,,,,,,'\''.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'\''......
            ....'\'',,,,,,,,,,,,.
               .'\'',,,,,,,,,'\''.
                .'\'',,,,,,'\''.
                  ..'\'''\'''\''.
'

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

+ make_temporary_log
++ mktemp /tmp/pihole_temp.XXXXXX
+ TEMPLOG=/tmp/pihole_temp.WgCIXJ
+ exec
+ rm /tmp/pihole_temp.WgCIXJ
+ distro_check
+ is_command apt-get
+ local check_command=apt-get
+ command -v apt-get
+ PKG_MANAGER=apt-get
+ UPDATE_PKG_CACHE='apt-get update'
+ PKG_INSTALL=(${PKG_MANAGER} --yes --no-install-recommends install)
+ PKG_COUNT='apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+ APT_SOURCES=/etc/apt/sources.list
+ awk 'BEGIN{a=1;b=0}/bionic main/{a=0}/bionic.*universe/{b=1}END{exit a + b}' /etc/apt/sources.list
+ whiptail --defaultno --title 'Dependencies Require Update to Allowed Repositories' --yesno 'Would you like to enable '\''universe'\'' repository?\n\nThis repository is required by the following packages:\n\n- dhcpcd5\n- dialog' 20 70
+ printf '  %b Enabling universe package repository for Ubuntu Bionic\n' '[i]'
  [i] Enabling universe package repository for Ubuntu Bionic
+ cp /etc/apt/sources.list /etc/apt/sources.list.backup
+ printf '  %b Backed up current configuration to %s\n' '[✓]' /etc/apt/sources.list.backup
  [✓] Backed up current configuration to /etc/apt/sources.list.backup
+ add-apt-repository universe
Error: 'universe' invalid
root@rock64 ~#

I run Debian 9.8 on Linux rock64 4.19.0-1073-ayufan-ga6e013135a6e #1 SMP PREEMPT Tue Oct 23 09:19:54 UTC 2018 aarch64 GNU/Linux

**Comment by dschaper** [comment]
Debian doesn't use Universe, Ubuntu does. 

Try Armbian instead, https://www.armbian.com/rock64/

**Comment by Floppik** [comment]
Why i need armbian? All works fine on debian 9.8 (pihole too). But last update script contains check for universe repo. How i disable this check? 
![image](https://user-images.githubusercontent.com/38560023/53506556-a016c980-3acf-11e9-9075-879fa88e32d6.png)
I already installed this package:

Уже установлен пакет dhcpcd5 самой новой версии (6.10.1-1).
Уже установлен пакет dialog самой новой версии (1.3-20160828-2).

**Comment by dschaper** [comment]
What is the contents of `/etc/apt/sources.list` and `/etc/os-release`? Something is trying to use Ubuntu repositories on a Debian install and that doesn't work.

**Comment by dschaper** [comment]
Or just try saying `No` for that prompt.

**Comment by Floppik** [comment]
root@rock64 ~# cat /etc/apt/sources.list
deb http://cdn.debian.net/debian/ stretch main contrib non-free
deb-src http://cdn.debian.net/debian/ stretch main contrib non-free
deb http://security.debian.org/ stretch/updates main contrib non-free
deb-src http://security.debian.org/ stretch/updates main contrib non-free
deb http://cdn.debian.net/debian/ stretch-updates main contrib non-free
deb http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic main
deb-src http://cdn.debian.net/debian/ stretch-updates main contrib non-free
# deb http://nginx.org/packages/debian/ stretch nginx
deb-src http://nginx.org/packages/debian/ stretch nginx
#deb [arch=arm64] http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/debian/ stretch main
#deb-src http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/debian/ stretch main
root@rock64 ~# cat /etc/debian_version
9.8

If i choose "no" then:
 [✗] Aborting installation: dependencies could not be installed.

**Comment by dschaper** [comment]
We can't support that distribution. They mix Debian and Ubuntu sources and we just don't have the resources to try and determine how badly that will break our package.

**Comment by tankren** [comment]
comment this 
`add-apt-repository universe`

path to file: `/etc/.pihole/automated install/basic-install.sh`
