### ISSUE TITLE
Gravity reports empty lists as still having one entry

### ISSUE THREAD

**Issue by ThomasKramps** [pi-hole/pi-hole#2657]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`If a white/blocklist is empty, it should be reported as such by gravity.`

**Actual behaviour:**

`When installing a fresh system all user editable lists are empty. Gravity reports them as having 0 entries. When you add something to the list and delete it afterwards, gravity reports still 1 entry. This entry seems to be a placeholder, so not a problem anyway. But the behavior is inconsistent and the report by gravity is wrong.`

**Steps to reproduce:**

`Perform a fresh installation. Then pihole -g and you will see all lists having entries = 0. Add something to the blocklist and delete it again. Now pihole -g will report entries = 1 for the blocklist. By pihole -b -l this seems to be a placeholder, which was not there on the fresh install.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`I don't consider this necessary by now. You may ask me to hand this in later if it is relevant.`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried nuking by pihole -b --nuke, but that doesn't change the behavior. Since this is not a big deal I didn't do anything else.`

**This bug may seem to get in the same direction as #25, but I don't know if the causes are the same.**

**Comment by Mcat12** [comment]
The cause is the same as #25, so this is a regression in gravity.
