### ISSUE TITLE
Self Hosted Ads not being blocked

### ISSUE THREAD

**Issue by Holyprogrammer** [pi-hole/pi-hole#2662]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs))

---

**Expected behaviour:**
Ads on Google.com and Youtube.com should be blocked

**Actual behaviour:**
Many ads on Google.com and Youtube.com can still be seen.

**Steps to reproduce:**
Go to the YouTube homepage, or search for anything on Google

---

I read somewhere that self-hosted ads cannot be blocked by Pi-Hole. If Youtube.com ads are Hosted on Google.com, then do they count as self-hosted? Is there a way to block these, along with self-hosted ads, using Pi-Hole?

**Comment by DL6ER** [comment]
> I read somewhere that self-hosted ads cannot be blocked by Pi-Hole.

Yes

>  If Youtube.com ads are Hosted on Google.com, then do they count as self-hosted?

No

> Is there a way to block these, along with self-hosted ads, using Pi-Hole?

Yes, but this will not work as you expect it. If you see ads on youtube.com that are hosted on google.com, you'll need to block google.com which is something you probably don't want to do.

**Comment by chr0max** [comment]
*Hihihi*....lets try to extract the poison out of the poison to get water.
