### ISSUE TITLE
pihole-FTL fails due to dnsmasq: bad option at line 44 of /etc/dnsmasq.d/01-pihole.conf

### ISSUE THREAD

**Issue by kaysond** [pi-hole/pi-hole#2665]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`pihole-FTL starts properly after install`

**Actual behaviour:**

`pihole-FTL fails due to dnsmasq: bad option at line 44 of /etc/dnsmasq.d/01-pihole.conf`

**Steps to reproduce:**

`Install pihole on Ubuntu 18.04.2 per instructions`

FYI the line is `dhcp-name-match=set:wpad-ignore,wpad`, and it claims to fix a vulnerability. Commenting out this line fixes the problem.

**Comment by dschaper** [comment]
Can you post the token/URL that was requested in the template please?

**Comment by kaysond** [comment]
https://tricorder.pi-hole.net/cthz9kcscc

**Comment by dschaper** [comment]
You're not on `pihole-FTL`s latest release, you're on the development branch. Please use the master branch:

```
pihole checkout ftl master
```

**Comment by kaysond** [comment]
Hmm that's weird. I switched to the dev branch to use null blocking after I had installed the master branch. The issue occurred immediately after installation, I commented out the line, then I switched to the dev branch.

But going back now, it seems to work just fine. I wonder if it had something to do with #2136 as I tried to nuke my old version before updating.

**Comment by kaysond** [comment]
Thanks @dschaper
