### ISSUE TITLE
Installer doesn't allow to select already installed unbound as DNS server

### ISSUE THREAD

**Issue by schumar** [pi-hole/pi-hole#2666]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- ✅  I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- ✅  The issue I am reporting can be *replicated*.
- ✅  The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4

---
**Expected behaviour:**

When choosing a `Custom` DNS server, I want to be able to provide `127.0.0.1#54` (as I am already running an `unbound` instance on port 54, similar to the suggested setup at https://docs.pi-hole.net/guides/unbound/)

**Actual behaviour:**

Error message `One or both entered IP addresses were invalid.`

**Steps to reproduce:**

`./basic-install.sh`
When asked `Select Upstream DNS Provider. To use your own, select Custom.`, select `Custom`
At the next text field, enter `127.0.0.1#54`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

Removed check from the installer

**Comment by PromoFaux** [comment]
Ah yes, this is something I noticed myself recently actually. 

If you have installed the web interface, you will be able to add it as a Custom upstream there, but I agree that we should probably allow this in the installer, too.

**Comment by gmartinerm** [comment]
My pihole instance (just in OS X) has problems communicating with an upstream server 127.0.0.1#5053 even if the upstream server is configured via the web interface. If I specify another machine as upstream let’s say 192.168.1.2#5053 it works.

**Comment by Mcat12** [comment]
@gmartinerm That is a completely different issue, so please make a new issue.

**Comment by gmartinerm** [comment]
I will

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/feature-request-to-set-127-0-0-1-5353-in-pihole-r-config/26968/2

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/why-is-google-the-first-dns-choice/33839/17

**Comment by yubiuser** [comment]
Should be fixed by

https://github.com/pi-hole/pi-hole/pull/3489
