### ISSUE TITLE
Query Lists tool doesn't search user blacklist

### ISSUE THREAD

**Issue by SherSlick** [pi-hole/pi-hole#2669]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_Not a developer, so 1_

---

**[ISSUE] Expected Behaviour:**
Query Lists tool should find matches in local regex/manual block lists.

**[ISSUE] Actual Behaviour:**
Query Lists tool seems to only search "published" lists that PiHole is using.

**[ISSUE] Steps to reproduce:**
Add some domains to blacklist (in my case a wildcard) and use the Query Lists tool to find if they are added to the user blacklist.

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi
OS: Raspbian

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Tracked by #2346

**Comment by SherSlick** [comment]
Thanks, I didn’t interpret the title of #2346 correctly.
