### ISSUE TITLE
Read-only system messages

### ISSUE THREAD

**Issue by z3to** [pi-hole/pi-hole#2673]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I have multiple errors occurring but since I believe that they are connected I list them together in this issue:
1. `When adding a domain to the whitelist I expect that domain to be added.`
2. `When I open the settings tap I expect it to open`
3. `When I update via SSH with pihole -up I expect it to update`

**Actual behaviour:**

1. When adding a domain to the whitelist I get the message: `Session expired! Please re-login on the Pi-hole dashboard.` No matter if I just locked in or use a different browser.
2. When opening the settings tap I get: `There was a problem applying your settings.
Debugging information:
PHP error (2): session_start(): open(/var/lib/php/sessions/sess_43ne8uge5ibedjdho3ef1mfea6, O_RDWR) failed: Read-only file system (30) in /var/www/html/admin/scripts/pi-hole/php/password.php:12`
3. When updating Pi-Hole via SSH I get: `mktemp: failed to create file via template '/tmp/pihole_temp.XXXXXX': Read-only file system`

**Steps to reproduce:**

`For me, the same errors occured already on the last install after some months. I did a complete reinstall of Raspbian and after about 2 months I get the same messages without actively changing anything. I was able to add domains and open the settings taps right after the install.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I run the command but can’t upload it:
```tee: /proc/8516/fd/3: No such file or directory
    * Using openssl for transmission.
/opt/pihole/piholeDebug.sh: line 1144: /var/log/pihole_debug-sanitized.log: No such file or directory
tee: /proc/8516/fd/3: No such file or directory
[✗]  There was an error uploading your debug log.
tee: /proc/8516/fd/3: No such file or directory
   * Please try again or contact the Pi-hole team for assistance.
tee: /proc/8516/fd/3: No such file or directory
   * A local copy of the debug log can be found at: /var/log/pihole_debug-sanitized.log
```
Unfortunately, the file is not there.

**Troubleshooting undertaken, and/or other relevant information:**

The Raspberry is just running the Pi-Hole on Raspbian.

Sorry for not completely sticking to the template format.

**Comment by PromoFaux** [comment]
Hi there,

Just going on a hunch here, if you haven't actively changed anything to make the filesystem read only, it could be down to corruptions on the SD card.

A couple of things could cause this:
 - Incorrect shutdown of the pi (i.e pulling the power cable out)
 - [Power supply not meeting the requirements for the Pi model you are using](https://www.raspberrypi.org/documentation/faqs/#pi-power)
 - SD card is not of great quality.

**Comment by PromoFaux** [comment]
Hi @z3to 

Is this still an issue for you?

**Comment by z3to** [comment]
Thanks @PromoFaux for asking! I was just about to post an update.

The old »have you tried turning it off and on« actually worked. After rebooting with `sudo shutdown -r 0` everything worked again. So i guess it resulted from incorrect shutdown.

Thanks again!

**Comment by PromoFaux** [comment]
Great stuff!
