### ISSUE TITLE
Issue after release upgrade between ubuntu server 16.04 to 18.04.2

### ISSUE THREAD

**Issue by oxoocoffee** [pi-hole/pi-hole#2675]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I get 403 - Forbidden`

**Actual behaviour:**

`403 - Forbidden`

**Steps to reproduce:**

`1. Initially installed pi.hole under 16.04 couple of weeks ago`
`2. Institution was completed and pi.how was up and I gout login to admin`
`3. Today I decided to do release upgrade to 18.04.2`
`4. After upgrade console was not available`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/vzobfpv53g!`

**Troubleshooting undertaken, and/or other relevant information:**

`1. I did try to uninstall pi.hole using pihole uninstall to try again fresh clean install`
`2. Manually uninstalled lighthttpd package and config files in /etc since it was installed by pi during initial install`
`3. Removed pihole and admin folders in /var/www/html`
`4. Reboot system and add temp name server 8.8.8.8 to my resolve.conf`
`5. Try to reinstall pi using curl -sSL https://install.pi-hole.net | bash`
`6. I did try to install using as myself and after checking that I was getting same error I removed everything like I stated above and did try to install with sudo since I noticed installer was stating that I was not root`

Contents of my /var/www/html/
`admin`
`pihole`

Here are contents of admin
`-rw-r--r-- 1 root root 11066 Mar 16 02:54 api_db.php`
`-rw-r--r-- 1 root root  8760 Mar 16 02:54 api_FTL.php`
`-rw-r--r-- 1 root root  3609 Mar 16 02:54 api.php`
`-rw-r--r-- 1 root root  2795 Mar 16 02:54 auditlog.php`
`-rw-r--r-- 1 root root  2339 Mar 16 02:54 CONTRIBUTING.md`
`-rw-r--r-- 1 root root  2200 Mar 16 02:54 db_graph.php`
`-rw-r--r-- 1 root root  4229 Mar 16 02:54 db_lists.php`
`-rw-r--r-- 1 root root  5866 Mar 16 02:54 db_queries.php`
`-rw-r--r-- 1 root root   948 Mar 16 02:54 debug.php`
`-rw-r--r-- 1 root root  1229 Mar 16 02:54 gravity.php`
`-rw-r--r-- 1 root root  9398 Mar 16 02:54 help.php`
`drwxr-xr-x 2 root root  4096 Mar 16 02:54 img`
`-rw-r--r-- 1 root root 10811 Mar 16 02:54 index.php`
`-rw-r--r-- 1 root root 14164 Mar 16 02:54 LICENSE`
`-rw-r--r-- 1 root root  3300 Mar 16 02:54 list.php`
`-rw-r--r-- 1 root root  5475 Mar 16 02:54 queries.php`
`-rw-r--r-- 1 root root  1110 Mar 16 02:54 queryads.php`
`-rw-r--r-- 1 root root  9970 Mar 16 02:54 README.md`
`drwxr-xr-x 4 root root  4096 Mar 16 02:54 scripts`
`-rw-r--r-- 1 root root 93800 Mar 16 02:54 settings.php`
`drwxr-xr-x 3 root root  4096 Mar 16 02:54 style`
`-rw-r--r-- 1 root root   939 Mar 16 02:54 taillog-FTL.php`
`-rw-r--r-- 1 root root   931 Mar 16 02:54 taillog.php`

I get 403 Forbiden error when accessing from remote machine on same LAN

`http:\\lan.server.ip\admin`

But trying trying to run curl on server I get

`curl -i http:\\lan.server.ip\admin`
`HTTP/1.1 301 Moved Permanently`
`Location: http://lan.server.ip/admin/`
`Content-Length: 0`
`Date: Sat, 16 Mar 2019 08:26:00 GMT`
`Server: lighttpd/1.4.45`

**Comment by dschaper** [comment]
What does `curl -I http://lan.server.ip/admin/` show?

**Comment by oxoocoffee** [comment]
@dschaper 
`$ curl -I http://lan.server.ip/admin/`
`HTTP/1.1 403 Forbidden`
`Content-Type: text/html`
`Content-Length: 345`
`Date: Sat, 16 Mar 2019 15:27:32 GMT`
`Server: lighttpd/1.4.45`

Here are permission on /var/www/html/admin
`drwxr-xr-x  7 root root 4096 Mar 16 02:54 admin`

**Comment by dschaper** [comment]
Also try `curl -I http://pi.hole/admin/` and `curl -I http://10.146.71.6/admin/` please.

**Comment by oxoocoffee** [comment]
@dschaper Thanks for typing LAN ip for me above :)

 `$ curl -I http://pi.hole/admin/`
`curl: (6) Could not resolve host: pi.hole`

`$ curl -I http://lan.server.ip/admin/`
`HTTP/1.1 403 Forbidden`
`Content-Type: text/html`
`Content-Length: 345`
`Date: Sat, 16 Mar 2019 15:40:11 GMT`
`Server: lighttpd/1.4.45`

**Comment by dschaper** [comment]
It's an RFC 1918 IP address, they aren't accessible or routed over the internet so there's nothing exposed. I wanted to make sure you were using the same IP address that lighttpd/Pi-hole was expecting.

**Comment by dschaper** [comment]
`pi.hole` is added to the resolver with `/etc/pihole/local.list`. If `pi.hole` does not resolve on the Pi-hole device itself then check `/etc/resolv.conf` to see if it's using `127.0.0.1` or something else that will cause issues.

**Comment by oxoocoffee** [comment]
@dschaper Ok I fixed /etc/resolv.conf I did added yesterday replaced 127.0.0.1 yesterday manually with 8.8.8.8 and forgot to revert it. Thank you
But I specifically remember that after initial install still under 16.04 resolve.conf has 127.0.0.53? It was not 127.0.0.1. So I want to point this out

Now, any suggestions about my above permissions questions?

**Comment by dschaper** [comment]
Your file permissions are ownership are fine. To double check run:
```
cd /var/www/html/admin
sudo git status
```

You should see that you are on branch master and there are no changes to commit.

**Comment by oxoocoffee** [comment]
Yup, that is what I see

`(master) $ sudo git status`
`On branch master`
`Your branch is up to date with 'origin/master'.`
`nothing to commit, working tree clean`

**Comment by oxoocoffee** [comment]
Looks like everything it work except web access

**Comment by dschaper** [comment]
Are there any entries in `/var/log/lighttpd/access.log` or `/var/log/lighttpd/error.log` for your client IP address?

**Comment by oxoocoffee** [comment]
@dschaper 

access.log last items are
1552761579|10.146.71.6|GET /admin/ HTTP/1.1|403|345
1552782077|10.146.71.6|GET /admin/ HTTP/1.1|403|345

and error.log
2019-03-17 06:25:07: (server.c.1534) logfiles cycled UID = 0 PID = 10853
root@ubuntu-gateway /var/log/lighttpd

**Comment by oxoocoffee** [comment]
Now I just curl again and getting 301 error. Nothing changed except adding pi.hole to local file for resolution like you suggested above and system reboot. All folders and files are the same. Just checked.

 `curl -i http://10.146.71.6/admin`
`HTTP/1.1 301 Moved Permanently`
`Location: http://10.146.71.6/admin/`
`Content-Length: 0`
`Date: Sun, 17 Mar 2019 20:41:41 GMT`
`Server: lighttpd/1.4.45`

**Comment by dschaper** [comment]
You should see a 301 to redirect from `/admin` to `/admin/`. 

Do you have any other `lighttpd` configuration files or snippets that may be causing the block?

**Comment by Mcat12** [comment]
What is the output of this command?
```
journalctl -u lighttpd
```

**Comment by oxoocoffee** [comment]
The last entries are 
`-- Reboot --`
`Mar 16 18:33:55 ubuntu systemd[1]: Starting Lighttpd Daemon...`
`Mar 16 18:33:57 ubuntu systemd[1]: Started Lighttpd Daemon.`

**Comment by oxoocoffee** [comment]
> You should see a 301 to redirect from `/admin` to `/admin/`.
> 
> Do you have any other `lighttpd` configuration files or snippets that may be causing the block?
Note sure what you mean... Can you state possible locations? beside /etc/lighttpd/lighttpd.conf

Here are contents of /etc/lighttpd
 `$ tree`
`├── conf-available`
`├── conf-enabled`
`├── external.conf`
`└── lighttpd.conf`

**Comment by dschaper** [comment]
Apache2 should not be running. Only `lighttpd`. What is the contents of the `.conf` files?

**Comment by oxoocoffee** [comment]
Ok I did make sure apache2 and htcacheclean are not running. nAlso made sure such services are not activated on boot. After I restarted lighttpd.service. Stil curl -i http://127.0.0.1/admin gives me 301.
Here is my conf file
[lighttpd.conf.gz](https://github.com/pi-hole/pi-hole/files/2985124/lighttpd.conf.gz)

**Comment by dschaper** [comment]
http://127.0.0.1/admin will correctly 301 to http://127.0.0.1/admin/ so that is fine. The problem as I understand it is that http://127.0.0.1/admin/ is 403.

`curl -IL http://127.0.0.1/admin` should 301 to the proper page and then not 403 if it is working as intend.

```
curl -IL http://127.0.0.1/admin
HTTP/1.1 301 Moved Permanently
Location: http://127.0.0.1/admin/
Date: Tue, 19 Mar 2019 19:05:06 GMT
Server: lighttpd/1.4.45

HTTP/1.1 200 OK
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
Set-Cookie: PHPSESSID=a040jn43a1u5nrv37ursnfs8o3; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-type: text/html; charset=UTF-8
Date: Tue, 19 Mar 2019 19:05:06 GMT
Server: lighttpd/1.4.45
```

**Comment by dschaper** [comment]
Is there anything in `external.conf`?

**Comment by oxoocoffee** [comment]
external.conf is zero bytes

drwxr-xr-x 2 root root 4096 Mar 16 02:54 conf-available
drwxr-xr-x 2 root root 4096 Feb  6  2018 conf-enabled
-rw-r--r-- 1 root root    0 Mar 16 02:55 external.conf
-rw-r--r-- 1 root root 3102 Mar 16 02:55 lighttpd.conf

 # curl -IL http://127.0.0.1/admin

HTTP/1.1 301 Moved Permanently
Location: http://127.0.0.1/admin/
Date: Tue, 19 Mar 2019 19:07:01 GMT
Server: lighttpd/1.4.45

HTTP/1.1 403 Forbidden
Content-Type: text/html
Content-Length: 345
Date: Tue, 19 Mar 2019 19:07:01 GMT
Server: lighttpd/1.4.45

**Comment by dschaper** [comment]
And are there any configuration files in `/conf-enabled`?

**Comment by oxoocoffee** [comment]
No files in `/conf-enabled` or `/conf-available`

**Comment by dschaper** [comment]
Everything is as it should be. I don't have anything else that I would be able to check and test to resolve this. I don't know why 403 is happening when there are no directives to do it. You don't have SELinux enabled do you?

**Comment by oxoocoffee** [comment]
No I do not. The strange thing is that initial pi.hole was working under 16.04. Then I did distort upgrade 18.04 and got me to this issue. Here is idea. Is there a list of packages/config files/services/etc I can remove manually to make sure everything is totally clean and try to install again? I know pihole uninstall do it but if I remember if wild not remove all. Is there a sanitize option of some kind? Remove everything that pi.hole installs, generates and any other files generated by installed packages? I could try to do that.

**Comment by oxoocoffee** [comment]
anything wrong with attached lighttdp.conf file you can see?

**Comment by dschaper** [comment]
You can try:

```sh
sudo rm -rf /var/www/html/admin
cd /var/www/html/
sudo git clone https://github.com/pi-hole/AdminLTE admin
```

But for manually removing packages and trying to frankenstein things in, that's just going to make a bad situation worse.

And no, your config file looks fine.

**Comment by oxoocoffee** [comment]
What user should I clone it under? root? myself? www-data that lighthttpd is running under?

**Comment by dschaper** [comment]
Root, hence the `sudo` call.

**Comment by oxoocoffee** [comment]
Ah missed :)

**Comment by oxoocoffee** [comment]
@dschaper 
So today I uninstalled pi.hole, lighthttpd, apache2 (I am not using it now and it was not running for some time). Then I removed admin and pihole in 

`/var/www.html`
 `/var/log`
`/opt`
 `/etc/.pihole`
`/etc/pihole`

Then rebooted. Before reinstalling I did try to ping external site to check if connectivity is ok and resolver works. Looks like at this point all was good except resolving url's. So temporary I added nameserver 8.8.8.8 for `/etc/resolver.conf` and for now continued with install. After installation and system reboot I could finally login access admin page first testing with curl then actual browser. The issue is as initially noticed that URL can't be resolved. Here is my current resolve.conf contents

`# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)`
`#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN`
`# 127.0.0.53 is the systemd-resolved stub resolver.`
`# run "systemd-resolve --status" to see details about the actual nameservers.`
` `
`nameserver 127.0.0.53` // I did try to replace it with 127.0.0.1 like you suggested above but not change.
`options edns0`

I also checked `/etc/dnsmasq.d/01-pihole.conf` .That file us using DNS I selected during installation.

So when I log in as admin with browser I see in upper left in red color:
`DNS service not running' and some other one but it is cut our on my Safari Browser. I am attaching screen shot. Any ideas or info you need?
<img width="92" alt="Pi-hole Admin Console 2019-03-22 15-54-35" src="https://user-images.githubusercontent.com/2259575/54852452-ee784c00-4cba-11e9-8540-283cf3128d14.png">

**Comment by dschaper** [comment]
`systemd-resolved` will conflict with `pihole-FTL` so you need to disable that. See https://discourse.pi-hole.net/t/dns-resolving-but-pi-hole-not-doing-it/10848/10 for some more information.

**Comment by oxoocoffee** [comment]
I just checked. That is what I have right now
`[Resolve]`
`#DNS=`
`#FallbackDNS=`
`#Domains=`
`#LLMNR=no`
`#MulticastDNS=no`
`#DNSSEC=no`
`#Cache=yes`
`DNSStubListener=no`

**Comment by dschaper** [comment]
Try disabling the service since you'll be using Pi-hole and `pihole-FTL` instead.

```
sudo systemctl disable systemd-resolved.service 
sudo service systemd-resolved stop
```

**Comment by oxoocoffee** [comment]
I already this that one step before :) Also did reboot to make sure. But one thing I noticed reading at the beginning of the link you posted above.
`sudo systemctl status --full --no-pager dnsmasq.service` 

returned 

`● dnsmasq.service`
`   Loaded: masked (/dev/null; bad)`
`   Active: inactive (dead)`

Do I have to install dnsmasq-base package? If so how come did installer missed it?

**Comment by dschaper** [comment]
No, `dnsmasq` is not used anymore, the package is `pihole-FTL`. What is the output from `sudo systemctl status --full --no-pager piholeFTL.service`?

**Comment by oxoocoffee** [comment]
`$ sudo systemctl status --full --no-pager piholeFTL.service`
`Unit piholeFTL.service could not be found.`
Just so you know I did not modify anything except what we talked after reinstall. Is there installation log I can send you?

**Comment by dschaper** [comment]
Sorry, I made a typo, the service name is `pihole-FTL.service`

**Comment by oxoocoffee** [comment]
'sudo systemctl status --full --no-pager pihole-FTL.service
Unit pihole-FTL.service could not be found.`

**Comment by dschaper** [comment]
And the contents of `/etc/init.d/` please?

**Comment by oxoocoffee** [comment]
`acpid                   dns-clean                mountnfs-bootclean.sh    single
apparmor                dnsmasq                  mountnfs.sh              smartmontools
apport                  exim4                    networking               ssh
atd                     grub-common              ntop                     sysfsutils
atop                    halt                     ntp                      tftpd-hpa
avahi-daemon            hostname.sh              ondemand                 thermald
binfmt-support          hwclock.sh               openbsd-inetd            udev
bootmisc.sh             irqbalance               plymouth                 ufw
cgmanager               keyboard-setup.dpkg-bak  plymouth-log             umountfs
cgproxy                 keyboard-setup.sh        pppd-dns                 umountnfs.sh
checkfs.sh              killprocs                procps                   umountroot
checkroot-bootclean.sh  kmod                     rc.local                 unattended-upgrades
checkroot.sh            lighttpd                 reboot                   urandom
collectl                mdadm                    resolvconf               uuidd
console-setup.sh        mdadm-waitidle           rsync                    whoopsie
cron                    mountall-bootclean.sh    rsyslog                  x11-common
dbus                    mountall.sh              saned
denyhosts               mountdevsubfs.sh         screen-cleanup.dpkg-new
dhcpcd                  mountkernfs.sh           sendsigs`

**Comment by dschaper** [comment]
You are missing the `/etc/init.d/pihole-FTL` script. I'm not sure how that could have not been copied over.

**Comment by dschaper** [comment]
Try `pihole -r` and see if you can repair the installation.

**Comment by oxoocoffee** [comment]
Not sure if you did catch my edit for above message. "I do remember removing pihole-FTL entry from /etc/init.d during uninstall stage. Then reboot and reinstall"

**Comment by oxoocoffee** [comment]
As root or myself. Do not want to add extra problem :)

**Comment by dschaper** [comment]
It will invoke sudo when needed.

**Comment by oxoocoffee** [comment]
Here is what info from my screen. At the end I still do not see` /etc/init.d/pihole-FTL`

`[i] Existing PHP installation detected : PHP version 7.2.15-0ubuntu0.18.04.1`
`  [i] Reconfigure option selected`
`  [✓] Disk space check`
`  [✓] Update local cache of available packages`
` `
`  [✓] Checking apt-get for upgraded packages... up to date!`
` `
`  [i] Installer Dependency checks...`
`  [✓] Checking for apt-utils`
`  [✓] Checking for dialog`
`  [✓] Checking for debconf`
`  [✓] Checking for dhcpcd5`
`  [✓] Checking for git`
`  [✓] Checking for iproute2`
`  [✓] Checking for whiptail`

` This installer will transform your device into a network-wide ad  blocker!`

Couple other `OK` then

`Select Upstream DNS Provider. To use your own, select Custom.` and selected DNS from list
` Pi-hole relies on third party lists in order to block ads.`  All checked
`Select Protocols (press space to select)` Both checked
`Do you want to use your current network settings as a static address?` That all look ok at this stage
` `
`[i] Using Cloudflare servers`
`  [i] Static IP already configured`
`  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled`
`  [i] IPv4 address: 10.146.71.6/24`
`  [i] IPv6 address: `
`  [i] Web Interface On`
`  [i] Web Server On`
`  [i] Logging On.`
`  [i] Privacy level 0  [i] Performing reconfiguration, skipping download of local repos`
`  [✓] Resetting repository within /etc/.pihole...`
`  [✓] Resetting repository within /var/www/html/admin...`
`  [i] Main Dependency checks...`
`  [✓] Checking for cron`
`  [✓] Checking for curl`
`  [✓] Checking for dnsutils`
`  [✓] Checking for iputils-ping`
`  [✓] Checking for lsof`
`  [✓] Checking for netcat`
`  [✓] Checking for psmisc`
`  [✓] Checking for sudo`
`  [✓] Checking for unzip`
`  [✓] Checking for wget`
`  [✓] Checking for idn2`
`  [✓] Checking for sqlite3`
`  [✓] Checking for libcap2-bin`
`  [✓] Checking for dns-root-data`
`  [✓] Checking for resolvconf`
`  [✓] Checking for libcap2`
`  [✓] Checking for lighttpd`
`  [✓] Checking for php7.2-common`
`  [✓] Checking for php7.2-cgi`
`  [✓] Checking for php7.2-sqlite3`
` `
`  [✓] Enabling lighttpd service to start on reboot...`
` `
`  [i] FTL Checks...`
` `
`  [✓] Detected x86_64 architecture`
`  [i] Checking for existing FTL binary...`
`  [i] Latest FTL Binary already installed (v4.2.3). Confirming Checksum...`
`  [i] Checksum correct. No need to download!`
`  [✓] Checking for user 'pihole'`
`  [✓] Installing scripts from /etc/.pihole`
` `
`  [i] Installing configs from /etc/.pihole...`
`  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!`
`  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf`
` `
`  [i] Installing blocking page...`
`  [✓] Creating directory for blocking page, and copying files`
`  [✗] Backing up index.lighttpd.html`
`      No default index.lighttpd.html file found... not backing up`
` `
`  [✓] Installing sudoer file`
` `
`  [✓] Installing latest Cron script`
` `
`  [✓] Installing latest logrotate script`
`  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old`
` `
`  [i] Skipping firewall configuration`
`  [✓] man pages installed and database updated`
`  [i] Testing if systemd-resolved is enabled`
`  [i] Systemd-resolved is not enabled`
`  [✓] Restarting lighttpd service...`
`  [✓] Enabling lighttpd service to start on reboot...`
`  [i] Restarting services...`
`  [i] Enabling pihole-FTL service to start on reboot`

**Comment by dschaper** [comment]
You still had the `pihole-FTL` binary installed so the script did not pull down any new files or try to install the service file.

**Comment by dschaper** [comment]
Delete `/usr/bin/pihole-FTL` and then try `pihole -r` again.

**Comment by oxoocoffee** [comment]
Ok Looks like this was the problem. Looks like installer assumed that `/usr/bin/pihole-FTL` was there and did skip bunch of things. After removing it and reinstalling everything is good. I also did see few requests like `simple_tracking.txt` and others that I did not see before removing /usr/bin/pihole-FTL. I am able to login to admin and looks good. I will try to reboot as final test and get bet back here

**Comment by oxoocoffee** [comment]
Ok `resolver.conf` still has 'nameserver 127.0.0.1' so that is good? So if this is ok then I am all working. Time to donate :)

**Comment by dschaper** [comment]
Yes, `127.0.0.1` is the proper address for `/etc/resolv.conf`.

Thank you!

**Comment by oxoocoffee** [comment]
Noooo. THANK YOU!!!!
