### ISSUE TITLE
PiHole version (Update available!) after update.

### ISSUE THREAD

**Issue by Amarok73** [pi-hole/pi-hole#2677]
Hello,

After update, the PiHole web page still shows message...
![image](https://user-images.githubusercontent.com/6810260/54495666-34fa2f00-48e6-11e9-9da3-f47e70afea57.png)
Starting the installation script, and selecting Update option shows that more or less everything is ok, except some fatal error about inability to read the object "9dd33266a5b5c857f8abf6fe31db4e1e004c3956"
![image](https://user-images.githubusercontent.com/6810260/54495787-6f180080-48e7-11e9-8b68-8a974a3518bd.png)
![image](https://user-images.githubusercontent.com/6810260/54495806-a090cc00-48e7-11e9-8f6d-d875120165cb.png)

What can be the reason of this situation and how to resolve it?

**Comment by dschaper** [comment]
Have you cleared the browser cache?

**Comment by Mcat12** [comment]
What is the output of these commands?
```
cd /etc/.pihole
git status
git rev-parse --abbrev-ref HEAD
git describe --long --dirty --tags
```

**Comment by Amarok73** [comment]
Hello, sorry for late answer. 
@dschaper yes, tried it on couple of computers and on all of them as well as phone, effect is the same.
@Mcat12 Here is the output:
![image](https://user-images.githubusercontent.com/6810260/54638542-96a7ce00-4a8b-11e9-84d3-c1218a983ec9.png)

**Comment by Amarok73** [comment]
Hello, sorry for late answer...
@dschaper yes tried it on all computers i could check it...
@Mcat12 Here's the output:
![image](https://user-images.githubusercontent.com/6810260/54638735-05852700-4a8c-11e9-92f5-ca6cf30660b3.png)

**Comment by PromoFaux** [comment]
Can you also please run `git diff` in that directory?

**Comment by Amarok73** [comment]
![image](https://user-images.githubusercontent.com/6810260/54640016-0f5c5980-4a8f-11e9-8e55-084f119d21f9.png)

**Comment by PromoFaux** [comment]
Hmm, looks like those files have become corrupt...  

There could be any number of things that can cause this, but some could include:
 - Incorrect shutdown of the pi (i.e pulling the power cable out)
 - [Power supply not meeting the requirements for the Pi model you are using](https://www.raspberrypi.org/documentation/faqs/#pi-power)
 - SD card is not of great quality.

You could try to delete the local repository and reclone it to see if that fixes the issue, but that is short term... there could be an underlying issue that is causing corruptions.

```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
pihole -r
```

**Comment by Amarok73** [comment]
@PromoFaux  Indeed, it could be related to the wrong shutdown procedure, as recently it happened that my son have disconnected couple times HD cable (system is on hard drive connected with USB cable).
Applied suggested procedure and no more problems. Thank You!
![image](https://user-images.githubusercontent.com/6810260/54641011-682cf180-4a91-11e9-8d4e-81a49a567f42.png)

**Comment by PromoFaux** [comment]
Great stuff, glad that sorted your issue!
