### ISSUE TITLE
Lighttp config problem

### ISSUE THREAD

**Issue by MPfiff** [pi-hole/pi-hole#2679]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

I updated Pihole to the latest version(Core 4.2.2)
. Service lighttpd is not starting

**Actual behaviour:**

Cannot reach the admin interface

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

` https://tricorder.pi-hole.net/ctgla5ygdi!`

**Troubleshooting undertaken, and/or other relevant information:**

journalctl -u lighttpd
Mar 19 19:24:44 raspberrypi systemd[1]: Failed to start Lighttpd Daemon.
Mar 19 19:24:44 raspberrypi systemd[1]: lighttpd.service: Unit entered failed state.
Mar 19 19:24:44 raspberrypi systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Mar 19 19:24:44 raspberrypi systemd[1]: lighttpd.service: Service hold-off time over, scheduling restart.
Mar 19 19:24:44 raspberrypi systemd[1]: Stopped Lighttpd Daemon.
Mar 19 19:24:44 raspberrypi systemd[1]: Starting Lighttpd Daemon...
Mar 19 19:24:45 raspberrypi lighttpd[566]: Duplicate array-key '.php'
Mar 19 19:24:45 raspberrypi lighttpd[566]: 2019-03-19 19:24:44: (configfile.c.1154) source: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf line: 21 pos: 1 parser failed somehow near here: (EOL)
Mar 19 19:24:45 raspberrypi lighttpd[566]: 2019-03-19 19:24:44: (configfile.c.1154) source: find /etc/lighttpd/conf-enabled -name '*.conf' -a ! -name 'letsencrypt.conf' -printf 'include "%p"\n' 2>/dev/null line: 4 pos: 1 parser failed so
Mar 19 19:24:45 raspberrypi lighttpd[566]: 2019-03-19 19:24:44: (configfile.c.1154) source: /etc/lighttpd/lighttpd.conf line: 56 pos: 1 parser failed somehow near here: (EOL)
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Control process exited, code=exited status=255
Mar 19 19:24:45 raspberrypi systemd[1]: Failed to start Lighttpd Daemon.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Unit entered failed state.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Service hold-off time over, scheduling restart.
Mar 19 19:24:45 raspberrypi systemd[1]: Stopped Lighttpd Daemon.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Start request repeated too quickly.
Mar 19 19:24:45 raspberrypi systemd[1]: Failed to start Lighttpd Daemon.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Unit entered failed state.
Mar 19 19:24:45 raspberrypi systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Mar 19 19:47:52 raspberrypi systemd[1]: Starting Lighttpd Daemon...
Mar 19 19:47:53 raspberrypi lighttpd[869]: Duplicate array-key '.php'

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
What is the output from `cat /etc/lighttpd/conf-enabled/15-fastcgi-php.conf`?

**Comment by MPfiff** [comment]
` cat /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
# -*- depends: fastcgi -*-
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

## Start an FastCGI server for php (needs the php5-cgi package)
fastcgi.server += ( ".php" =>
        ((
                "bin-path" => "/usr/bin/php-cgi",
                "socket" => "/var/run/lighttpd/php.socket",
                "max-procs" => 1,
                "bin-environment" => (
                        "PHP_FCGI_CHILDREN" => "4",
                        "PHP_FCGI_MAX_REQUESTS" => "10000"
                ),
                "bin-copy-environment" => (
                        "PATH", "SHELL", "USER"
                ),
                "broken-scriptfilename" => "enable"
        ))
)
`

**Comment by MPfiff** [comment]
```
cat /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
# -*- depends: fastcgi -*-
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

## Start an FastCGI server for php (needs the php5-cgi package)
fastcgi.server += ( ".php" =>
        ((
                "bin-path" => "/usr/bin/php-cgi",
                "socket" => "/var/run/lighttpd/php.socket",
                "max-procs" => 1,
                "bin-environment" => (
                        "PHP_FCGI_CHILDREN" => "4",
                        "PHP_FCGI_MAX_REQUESTS" => "10000"
                ),
                "bin-copy-environment" => (
                        "PATH", "SHELL", "USER"
                ),
                "broken-scriptfilename" => "enable"
        ))
)

```

**Comment by dschaper** [comment]
That looks okay. Do you have an `/etc/lighttpd/external.conf` file or any files in `/etc/lighttpd/conf-enabled`?

**Comment by MPfiff** [comment]
files: 10-fastcgi.conf  15-fastcgi-php.conf  15-fpm-php.conf

```
 cat 10-fastcgi.conf
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules += ( "mod_fastcgi" )
```
```
cat 15-fpm-php.conf
fastcgi.server += (".php" => ((
    "socket" => "/run/php/php7.0-fpm.sock"
)))

```

**Comment by dschaper** [comment]
That `15-fpm-php.conf` is not from a stock install and the `.php` declaration is a duplicate.

**Comment by MPfiff** [comment]
Thank you I removed the 15-fpm-php.conf now it works.
