### ISSUE TITLE
Pi-Hole Web Interface/UI Unable to Connect - Just One Unclean Shutdown/Power off

### ISSUE THREAD

**Issue by bugnot** [pi-hole/pi-hole#2682]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
`Should be able to connect to web interface after unclean shutdown.`

**Actual behaviour:**
`Earlier pi-hole used withstand few dirty power offs but now just one unclean shutdown and web interface throws "Unable to connect..." error. Only access now is via a terminal.`

**Steps to reproduce:**

`Configure Pi-Hole as usual and use it fully. Turn off external power/pull the cord. On next boot, the web interface will become inaccessible.`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried to connect to web UI by different addresses but no gain. The functionality is not broken only the UI of web.`

**Comment by dschaper** [comment]
This isn't a bug in Pi-hole, you will cause damage to the micro SD card if you crash out the power on a Raspberry Pi. There is no software fix or change that can be made to fix a hardware issue.

**Comment by bugnot** [comment]
I have had many power outages but web interface was always able to survive. This has started to happen recently so I thought to report. Using the same November release of Stretch lite. Nothing has changed. Thank you for quick response though.

**Comment by dschaper** [comment]
https://www.raspberrypi.org/documentation/faqs/#pi-power

**Comment by bugnot** [comment]
Power outages won't "always" corrupt a SD card. I am sure about that part.
