### ISSUE TITLE
DNSSEC Error

### ISSUE THREAD

**Issue by XxXTommyXxX** [pi-hole/pi-hole#2684]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

`I set pihole using DNS over HTTPS and DNSSEC`

**Actual behaviour:**

`I run a few tests on the web, but all of them fail. They don't fail if i use my VPN (created by PiVPN script).`

**Steps to reproduce:**

`Actually i don't know.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Can't provided the token, i'm getting the uploading error. Currently i'm trying to figure out what is this caused by. Tell me here if you want the log, i'll upload it to pastebin`

**Troubleshooting undertaken, and/or other relevant information:**

`I've not fixed it already.`

**Comment by dschaper** [comment]
Pi-hole doesn't have a native DNS over HTTPS function, what are you using for DoH?

**Comment by XxXTommyXxX** [comment]
DNS over HTTPS provided by Cloudflare (cloudflared). I saw the guide in Pi Hole Docs.

**Comment by dschaper** [comment]
What tests are you running, and what do they say that shows it is failing?

**Comment by XxXTommyXxX** [comment]
https://www.cloudflare.com/ssl/encrypted-sni/ this one.

**Comment by dschaper** [comment]
We will need to see the debug log to know what is possibly going on. If it works in one configuration then you may not have the interfaces quite correct for it to work.

**Comment by XxXTommyXxX** [comment]
Are you OK if I upload it on pastebin, and I link it here?

**Comment by XxXTommyXxX** [comment]
https://transfer.sh/12pOPS/pihole_debug.log

**Comment by dschaper** [comment]
That debug log shows Pi-hole is working correctly but it's set to forward directly to 1.1.1.1 / 1.0.0.1 and there's no configuration changes for DoH. To use cloudflared you would need something like 127.0.0.1#5353 as the upstream where that IP and port are the ones you configured cloudlflared with. 

https://docs.pi-hole.net/guides/dns-over-https/#configuring-pi-hole

**Comment by XxXTommyXxX** [comment]
I did that, i think i broke something while i was managing with iptables. i'm gonna try reinstalling all the stuff. i'll let you know if the problem is going to remain.

**Comment by XxXTommyXxX** [comment]
Ok, fresh install from scratch. It doesn't work, I set it correctly (Cloudflare DNS + DNSSEC). I also set my Pi IP as DNS on my laptop and it doesn't pass any DNSSEC Test. I can't figure out what is this caused by.

**Comment by dschaper** [comment]
Would you open a new topic at https://discourse.pi-hole.net in the Help section and we can get some of the community members that have implemented this to look things over. It appears to be an issue with configuration of additional software beyond Pi-hole and not an issue we can solve here.

**Comment by XxXTommyXxX** [comment]
Of course, thank you for help anyway. 😃
