### ISSUE TITLE
Query log page is empty but dashboard shows data

### ISSUE THREAD

**Issue by crone66** [pi-hole/pi-hole#2685]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`If I click on query log I expect to see a list of the last 100 requested domains`

**Actual behaviour:**

`The query log is empty. The query log is still empty if I click on show all`

![](https://i.imgur.com/nZPXJyz.png)

**Steps to reproduce:**

`Open pihole webinterface and click on query`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/mb9k3is8h7!`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried to repair pihole (pihole -r). Disabled, flushed and renabled log. Restarted pihole and respberry pi`
`The Dashboard looks normal all the data are visible`
`echo ">getallqueries" | nc localhost 4711 | head shows some requested urls`
`Tested with opera, chrome, firefox and edge (extensions disabled)`

**Comment by PromoFaux** [comment]
Could you please post some information from chrome developer tools when you try to load the page, specifically the `console`, and `network` tabs. Hopefully that will give us some more clues!

**Comment by crone66** [comment]
The console tab is empty  and the network tab shows this:
 ![](https://i.imgur.com/DFr0R5R.png)

**Comment by Mcat12** [comment]
What does the response for that HTTP request look like? Is it in JSON form, or something else?

**Comment by crone66** [comment]
the queries.phjp?all response is a html document (see https://pastebin.com/s010N3AE) If your are intrested of the response of queries.js it empty. ![](https://i.imgur.com/Vvjlrfn.png)

**Comment by Mcat12** [comment]
That response is from cache, try disabling or clearing the cache and check again. If it's still empty, check the file to make sure it exists (`/var/www/html/admin/scripts/pi-hole/js/queries.js`).

**Comment by crone66** [comment]
The file exists and the response is still empty (tested with private session of opera and with cleared cache in chrome) ![](https://i.imgur.com/hxOdAh2.png)

**Comment by Mcat12** [comment]
Make sure the `www-data` user can read the file (it should be `chmod 644` or similar).

**Comment by crone66** [comment]
I changed the file to chmod 644&777 didn't help. What I didn't mentioned is that everything worked for some months without issus. I updated a few weeks ago but I don't know if the query log worked correctly after the update or not.

**Comment by Mcat12** [comment]
Can you give the `ls -l` output of the file? Also check `/var/log/lighttpd/access.log` and `error.log` for any issues.

**Comment by crone66** [comment]
ls -l output: -rwxrwxrwx 1 root root 13618 Mär  7 19:10 /var/www/html/admin/scripts/pi-hole/js/queries.js

New lines in access.log after site refresh: 
1553994469|pihole.local|GET /admin/queries.php HTTP/1.1|200|22010
1553994469|pihole.local|GET /admin/scripts/vendor/moment.min.js HTTP/1.1|200|0
1553994469|pihole.local|GET /admin/scripts/pi-hole/js/queries.js HTTP/1.1|200|0
1553994469|pihole.local|GET /admin/style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0 HTTP/1.1|200|66624
1553994566|pihole.local|GET /admin/queries.php HTTP/1.1|200|22009

Error log:
2019-03-25 06:25:02: (server.c.1534) logfiles cycled UID = 0 PID = 20537
2019-03-27 20:11:53: (server.c.1828) server stopped by UID = 0 PID = 1
2019-03-27 20:12:02: (log.c.217) server started
2019-03-27 20:12:02: (server.c.1295) WARNING: unknown config-key: alias.url (ignored)
2019-03-27 20:25:24: (server.c.1828) server stopped by UID = 0 PID = 1
2019-03-27 20:25:24: (log.c.217) server started
2019-03-27 20:25:24: (server.c.1295) WARNING: unknown config-key: alias.url (ignored)
2019-03-27 20:46:42: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined variable: api in /var/www/html/admin/scripts/pi-hole/php/sub.php on line 16
2019-03-27 20:46:48: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined variable: api in /var/www/html/admin/scripts/pi-hole/php/sub.php on line 16
2019-03-27 20:46:55: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined variable: api in /var/www/html/admin/scripts/pi-hole/php/sub.php on line 16

**Comment by Mcat12** [comment]
As far as I can see, lighttpd just isn't working as expected. Try asking them about this issue, where a file is readable but doesn't return anything.

**Comment by crone66** [comment]
Okay I solved the problem by just clicking on one of the top clients after this the query log started to work again... strange (Didn't changed something or restarted pi for nearly 2 weeks).

**Comment by Xalio** [comment]
Hi all,
Just solved the issue by running:

sudo apt-get remove php7.0-sqlite3
sudo apache2ctl restart

sudo apt-get install php7.0-sqlite3
sudo apache2ctl restart


The issue was clearly indicated as PHP cannot find sqlite3 in the apache2 error.log.

Hope it helps.
Nicolas

**Comment by dschaper** [comment]
This issue was with `lighttpd`. It looks like you are using `apache2` which is not a supported webserver. This solution would not work for this issue.
