### ISSUE TITLE
Query List (exact match) reports comments

### ISSUE THREAD

**Issue by ghost** [pi-hole/pi-hole#2687]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`If I use the menu item "Query List" (Find Blocked Domain In Lists) with button "Search exact match" only real blocked domains should be listed.`

**Actual behaviour:**

`It seems that also out-commented lines are reported.`

**Steps to reproduce:**

`Open the admin web-interface and go to "Tools" / "Query List" (http://192.0.2.0/admin/queryads.php), enter a domain which is a comment in a Blocklist and press button "Search exact match". E.g. Use domain "google.com" with "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" in the Blocklists.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`xq369o8mfc`

**Troubleshooting undertaken, and/or other relevant information:**

`Checked the blocklist-file and the searched domain is not blocked, but only written as a comment.`

![Pi-hole - Query Lists](https://user-images.githubusercontent.com/44007403/55198353-f6058c80-51b5-11e9-9a3d-61f2d6cba0fa.png)

```
root@torta:~# pihole query -exact google.com
 Exact match for google.com found in:
   list.0.raw.githubusercontent.com.domains
root@torta:~#
root@torta:~#
root@torta:~# pihole query -adlist -exact google.com
 Exact match for google.com found in:
   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
root@torta:~#
root@torta:~#
root@torta:~# curl -s https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | grep -iw google.com
#74.125.127.105 g        # google.com
#0.0.0.0 www.google-analytics.l.google.com
0.0.0.0 video-stats.video.google.com
0.0.0.0 adservice.google.com
0.0.0.0 adservice.google.com.au
0.0.0.0 adservices.google.com
0.0.0.0 pagead-googlehosted.l.google.com
0.0.0.0 analytics.google.com
0.0.0.0 pagead.l.google.com
0.0.0.0 partnerad.l.google.com
0.0.0.0 www-google-analytics.l.google.com
# [National Rail Enquiries, https://play.google.com/store/apps/details?id=uk.co.nationalrail.google]
# [https://play.google.com/store/apps/details?id=myapp.devilbaby.android.music.newmusic]
# [http://play.google.com/store/apps/details?id=com.chuangkai.phonehelper]
# [http://play.google.com/store/apps/details?id=com.coconuts.webnavigator]
# [http://play.google.com/store/apps/details?id=com.babjul.billboard]
# [http://play.google.com/store/apps/details?id=com.taeyang.billboardtop]
# [https://play.google.com/store/apps/details?id=com.buymeapie.bmap]
```

The domain `google.com` is only used as comment.
Blocked domains are only other subdomains like `adservice.google.com`.

**Comment by dschaper** [comment]
Thanks, does `google.com` exist in `/etc/pihole/gravity.list`?

**Comment by PromoFaux** [comment]
Can reproduce here.

The exact line it is picking up from the StevenBlack hosts file is:
```
#74.125.127.105 g        # google.com
```
With this line removed, it no longer shows up as an exact match. 

Checking in my `gravity.list`, it has not been "sucked in" (as it were)

**Comment by PromoFaux** [comment]
@NeroRome, I've submitted a PR to (hopefully!) fix this. You can try it out by using the command:
```
pihole checkout core fix/2687
```

You can revert back to `master` afterwards with `pihole checkout core master`

**Comment by NeroRome** [comment]
Wow, what a quick response! Amazing!


I've updated to `fix/2687` and it looks good:

```
...
Update Complete!

  Current Pi-hole version is v4.2.1-40-ga7f6c9b
  Current AdminLTE version is v4.2
  Current FTL version is v4.2.3
root@torta:~#
root@torta:~#
root@torta:~# pihole query -adlist -exact google.com
  [i] No exact results found for google.com within the block lists
root@torta:~#
root@torta:~#
root@torta:~# pihole query -adlist google.com
 Match found in Blacklist
   sb-ssl.google.com
   sb-ssl.l.google.com
   pki-goog.l.google.com
   mtalk.google.com
  [i] Over 100 results found for google.com
        This can be overridden using the -all option
root@torta:~#
root@torta:~#
root@torta:~# grep -iw ^google.com$ /etc/pihole/gravity.list
root@torta:~#
```

It also looks good in the web-admin interface!

I've also looked to the [commit](https://github.com/pi-hole/pi-hole/commit/a7f6c9b3a056d58605623429fccb4ecd85ca1f53) and it looks good (even if I'm not very firm with [Negative Lookbehind Before the Match](https://www.rexegg.com/regex-disambiguation.html#negative-lookbehind) in RegEx). I guess (and hope), this will capture these problem well.

Thx guys!


P.S.: Of course, this is no check/test of the functionality of Pi-hole at all, but only a test of this tiny bug.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
