### ISSUE TITLE
Cancelling out of interface selection continues script

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#269]
You can select `cancel` on the `interface` selection page and the script continues to run without an interface populated in the variable. This leads to broken-ness when we try to set the `dnsmasq` config files to listen on an interface. The field is null populated and `dnsmasq` stops listening.

**Comment by jacobsalmela** [comment]
I made a PR to fix this a while back.  I'm sure it's conflicted by now.

**Comment by dschaper** [comment]
Okay, I just found it by typo accident, tabbed through the screen too fast. The other `cancel`s seem to break out of the script like they should.

**Comment by PromoFaux** [comment]
I'm going to try and look at that PR later @jacobsalmela, as you're quite right, it's very conflicted since we made all the changes to `basic-install.sh` :smile:

**Comment by dschaper** [comment]
Testing the install, it's just that one whiptail dialog that doesn't close out. Everything else has a sanity check or a method to stop the script when `cancel

**Comment by PromoFaux** [comment]
OK, I'll take a look at it

**Comment by PromoFaux** [comment]
fixed in 29e0e17
