### ISSUE TITLE
Issue during on AsusWRT installation

### ISSUE THREAD

**Issue by balintbabics** [pi-hole/pi-hole#2690]
Eearlier I successfully installed Pi-Hole on my RPi2 but now I'd like to delegate this task (the ad-blocking) to the router (Asus RT-AC68U with the latest Merlin fw).

I found [this](https://carlosfelic.io/network/configuring-the-pi-hole-with-asus-routers-merlin-or-johns-fork/) article about the installation process on AsusWRT but I have stucked.

Actually the automated install stucked, it says " [✗] OS distribution not supported":

![image](https://user-images.githubusercontent.com/5341539/55293346-d197f300-53f5-11e9-84ff-5d2278eccd8b.png)

I think it wouldn't be resonable that in the past (when the articel was written) AsusWRT were supported but now it's not.

**Comment by Mcat12** [comment]
We have never supported running Pi-hole on routers.

**Comment by balintbabics** [comment]
So no matter that the router can run a linux distro and can able to run every command from the installation, because the OS distribution check I won't be able to use it (in the past it can be used on routers successfully with the auto-install script - which was unsupported back then too). It's odd for me.

And I don't really see why routers are on black-list, would be more logical - to me, at least - to support it in any linux capable enviroment.

**Comment by Mcat12** [comment]
Does that router use `apt` or `dnf`/`yum`? Can it install all of the necessary packages? Does it run a supported architecture? Does it have enough storage space to install? Are there differences in a router environment which would need special handling?

These questions, along with one of the developers buying such a router, need to be resolved before we can support routers.

**Comment by PromoFaux** [comment]
>I found this article about the installation process on AsusWRT but I have stucked.

Just as an FYI, that article is not about intstalling Pi-hole _on_ an AsusWRT router, but rather setting up the router to use Pi-hole installed on a separate device, like a Raspberry Pi
