### ISSUE TITLE
Select a privacy mode for FTL?

### ISSUE THREAD

**Issue by JulienPalard** [pi-hole/pi-hole#2695]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

During the install phrase a question pops : `Select a privacy mode for FTL.`.

I just think this requires more information, a newcomer installing pihole facing this question won't understand it. In fact I'm a long-time user of pi-hole and I don't understand the question.

Maybe just add a link in this question to a FAQ page?

**Comment by JulienPalard** [comment]
For those landing on this issue having the same question, I found some info about privacy mode here:
https://github.com/pi-hole/FTL/blob/4a8003c3aa425c08bfe9d561f8c9ab42c16b29b1/config.c#L209
```c
	// PRIVACYLEVEL
	// Specify if we want to anonymize the DNS queries somehow, available options are:
	// PRIVACY_SHOW_ALL (0) = don't hide anything
	// PRIVACY_HIDE_DOMAINS (1) = show and store all domains as "hidden", return nothing for Top Domains + Top Ads
	// PRIVACY_HIDE_DOMAINS_CLIENTS (2) = as above, show all domains as "hidden" and all clients as "127.0.0.1"
	//                                    (or "::1"), return nothing for any Top Lists
	// PRIVACY_MAXIMUM (3) = Disabled basically everything except the anonymous statistics, there will be no entries
	//                       added to the database, no entries visible in the query log and no Top Item Lists
	// PRIVACY_NOSTATS (4) = Disable any analysis on queries. No counters are available in this mode.
        // defaults to: PRIVACY_SHOW_ALL
```

**Comment by dschaper** [comment]
https://docs.pi-hole.net/ftldns/privacylevels/

**Comment by JulienPalard** [comment]
This :) This link should be near the question in the installer, so users can find it easily.

**Comment by gnorbsl** [comment]
Are these statistics only stored locally or are they send to a remote server?

**Comment by DL6ER** [comment]
Everything is only stored locally. Neither is your data send to anywhere nor is it accessible from outside your home network (except for when you added explicit firewalls rules for this, of course).
