### ISSUE TITLE
Cannot Access www.leanplum.com while using pi-hole

### ISSUE THREAD

**Issue by Sean-Waitkus** [pi-hole/pi-hole#2697]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**
I am a developer that uses leanplum for A/B testing on Android and iOS.
I expect to be able to access www.leanplum.com if I have white listed it

**Actual behaviour:**

I get a DNS_PROBE_FINISHED_NXDOMAIN error.

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`
While running pi-hole attempt to access www.leanplum.com
Add www.leanplum.com to the white list and attempt to connect.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

bah6ycuekc

**Troubleshooting undertaken, and/or other relevant information:**

Added www.leanplum.com and api.leanplum.com to whitelist and was still blocked.
If I stop using pi-hole for DNS and use say Google(8.8.8.8) I can access the above sites.

**Comment by PromoFaux** [comment]
Nothing with `leanplum` is blocked in the "default" block lists, and I can see that you have not added any additional lists. 

![image](https://user-images.githubusercontent.com/1998970/55955336-0ce9bb80-5c59-11e9-8790-f882104a3aeb.png)

I'm unable to reproduce this. I can access the site whether or not it is in the whitelist.

**Comment by PromoFaux** [comment]
What is the output of `nslookup www.leanplum.com` on your Pi-hole device?

**Comment by Sean-Waitkus** [comment]
Did I not add it properly here?

![image](https://user-images.githubusercontent.com/30660396/55955473-879de100-5c2f-11e9-9c1d-c77daa2ce1c7.png)

**Comment by PromoFaux** [comment]
Yeah, it's added OK there. I did notice from your log that you attempted to add it with wildcards as well, but that did not work as there is no support for wildcard whitelisting at this stage.

**Comment by Sean-Waitkus** [comment]
This is my output.

![image](https://user-images.githubusercontent.com/30660396/55955689-08f57380-5c30-11e9-89c8-62e99514b64d.png)

**Comment by PromoFaux** [comment]
Then it is not blocked :)

**Comment by Sean-Waitkus** [comment]
Okay thanks, sorry to raise this. I honestly thought it was pi-hole.

Much appreciate the quick response 👍
