### ISSUE TITLE
pihole fail to resolve domain

### ISSUE THREAD

**Issue by sterob** [pi-hole/pi-hole#2698]
Since yesterday i am no longer able to connect to Twitch.tv including the website and twitch playback using streamlink. 

I tried removing pi-hole as DNS server and everything is back to normal. 
I checked blacklist but there is nothing inside.
I looked up the query log and twitch.tv queries status are all `OK (forwarded)`
I tried switching between multiple Upstream DNS servers but to no avail. 

I tried to ping 
```
~# ping www.twitch.tv
ping: www.twitch.tv: Temporary failure in name resolution
```
It doesn't look like DNS are blocking twitch

```
~# dig www.twitch.tv @8.8.8.8 +short
twitch.map.fastly.net.
151.101.78.167

~# dig www.twitch.tv @1.1.1.1 +short
twitch.map.fastly.net.
151.101.78.167
```

nor my ISP 

```
~# ping 151.101.78.167
PING 151.101.78.167 (151.101.78.167) 56(84) bytes of data.
64 bytes from 151.101.78.167: icmp_seq=1 ttl=56 time=43.9 ms
64 bytes from 151.101.78.167: icmp_seq=2 ttl=56 time=43.5 ms
64 bytes from 151.101.78.167: icmp_seq=3 ttl=56 time=43.8 ms
```

**Comment by Mcat12** [comment]
If Pi-hole is correctly resolving the query, then how is this a Pi-hole issue?

**Comment by sterob** [comment]
Well, since if i bypass pihole and connect to google/opendns directly, i can access to twitch again, so i guess the issue belongs to pihole. May be it fail to forward dns query, may be it got wrong wrong dns address, may be even though the log said `OK (forward)` but it got blocked somewhere... i don't know.

**Comment by Mcat12** [comment]
What is the output of `dig www.twitch.tv`?

**Comment by sterob** [comment]
```
~# dig www.twitch.tv

; <<>> DiG 9.10.3-P4-Raspbian <<>> www.twitch.tv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6981
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.twitch.tv.                 IN      A

;; ANSWER SECTION:
www.twitch.tv.          1408    IN      CNAME   twitch.map.fastly.net.
twitch.map.fastly.net.  27      IN      A       151.101.230.167

;; Query time: 65 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 12 04:23:58 UTC 2019
;; MSG SIZE  rcvd: 93
```

**Comment by Mcat12** [comment]
Does Pi-hole respond with the same IP address if you directly use another server (which you said makes everything work)?

**Comment by Mcat12** [comment]
You are getting a different IP address than you got in the other output you shared. If you use the same upstream directly, do you get the same IP address, and does everything start working?

**Comment by sterob** [comment]
My bad, i was using opendns as upstream dns server.
Here is the result with google dns

```
~# dig www.twitch.tv

; <<>> DiG 9.10.3-P4-Raspbian <<>> www.twitch.tv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50268
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.twitch.tv.                 IN      A

;; ANSWER SECTION:
www.twitch.tv.          189     IN      CNAME   twitch.map.fastly.net.
twitch.map.fastly.net.  20      IN      A       151.101.78.167

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 12 04:45:49 UTC 2019
;; MSG SIZE  rcvd: 93
```
Switching to google dns but it still doesn't work.  

```
~# ping wwww.twitch.tv
ping: wwww.twitch.tv: Temporary failure in name resolution
```

**Comment by Mcat12** [comment]
What's the contents of `/etc/resolv.conf`?

**Comment by sterob** [comment]
```
~# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
```

**Comment by sterob** [comment]
Update 1: bbc.com and bbc.co.uk are both inaccessible just like twitch

Update 2: So i switch back to using cloudflared DoH and everything start working again. I can view twitch and bbc. 

Update 3: So in my openwrt router, when i tick "Use DNS servers advertised by peer"  box, everything work normally. When i untick it and set either pi-hole or 1.1.1.1 or 8.8.8.8 as DNS server, i start seeing the mentioned above issue.  

Is it my ISP screwing with me?

**Comment by Mcat12** [comment]
It sounds like the issue lies with your router or ISP, and there's not much Pi-hole can do about it.

**Comment by jble** [comment]
who is your ISP?  I have a similar issue

**Comment by sterob** [comment]
I don't think my local ISP provide service in CA.

**Comment by kitzler-walli** [comment]
I'm experiencing similar issues since I updated to 4.2.2

**Comment by fosskers** [comment]
I'm getting `Temporary failure in name resolution` during the installation process. I can't ping or dig anything anymore.

**Comment by dschaper** [comment]
Edit `/etc/resolv.conf` and replace 127.0.0.1 with your preferred upstream DNS server.

**Comment by fosskers** [comment]
The other key was to use the `basic-install.sh` piped into bash and **not** the one downloaded via `wget`!
