### ISSUE TITLE
The Splash page should use relative URLs

### ISSUE THREAD

**Issue by obones** [pi-hole/pi-hole#2699]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
The HTTP server can be configured to serve pihole content in a subfolder like so:
http://hostname/pihole/

When going to that URL, one would expect to see the regular Splash page with the logo, a dark background and a functioning link to the admin panel

**Actual behaviour:**

The showed page has no style, the image is missing and the admin link goes to `/admin` instead of `/pihole/admin`

**Steps to reproduce:**

Configure the web server (lighthttpd, nginx or even Apache) to serve pihole content out of a subfolder and not the root.

**Troubleshooting undertaken, and/or other relevant information:**

The associated pull request addresses the issue by making sure all URLs inside the Splash page are relative.

`{Steps of what you have done to fix this}`

See pull request

**Comment by Mcat12** [comment]
> The HTTP server can be configured to serve pihole content in a subfolder like so:
> http://hostname/pihole/

This is not supported with the PHP (current) web interface.

**Comment by obones** [comment]
I am using it right now on my own network, and it appears to work just fine. What should I check that I have missed to make sure everything is ok?

**Comment by Mcat12** [comment]
When I say not supported, I mean it is not tested or designed to work in that way, and therefore we can not provide support for that use case.
