### ISSUE TITLE
[Feature request] IPv6-only DHCPv6/SLAAC RA

### ISSUE THREAD

**Issue by gdluca** [pi-hole/pi-hole#2702]
Hi,
is it possible to separate DHCPv4 and DHCPv6/SLAAC RA settings under Settings→DHCP?
I don't really need to lease IPv4 address in my network. Also, is it possible to just send SLAAC RA so the devices can get only the DNS server via RDNSS?

Thank you.

**Comment by mwoolweaver** [comment]
This should probably be redirected to the pi-hole discourse 

https://discourse.pi-hole.net/c/feature-requests

**Comment by gdluca** [comment]
Oh, thank you.
Issue closed here. ;)
