### ISSUE TITLE
 pihole chronometer --refresh

### ISSUE THREAD

**Issue by nclmrc** [pi-hole/pi-hole#2703]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---
**Expected behaviour:**

i would like don't see:
sleep: option not valid -- "-"
Try 'sleep --help' for more information.

**Actual behaviour:**

![immagine](https://user-images.githubusercontent.com/38593316/56090829-bc1bd200-5ea7-11e9-8e9a-04b331725af1.png)

**Steps to reproduce:**

when i digit from CLI  pihole chronometer --refresh, there's an error on sleep command

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by Mcat12** [comment]
What is the output of these commands?
```
sleep --version
sleep --help
```

**Comment by nclmrc** [comment]
sleep (GNU coreutils) 8.26
Copyright © 2016 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successive <http://gnu.org/licenses/gpl.html>
Questo è software libero: è possibile modificarlo e ridistribuirlo.
Non c'è ALCUNA GARANZIA, nei limiti permessi dalla legge.

Scritto da Jim Meyering e Paul Eggert.
__________________________________________________________


Usage: sleep NUMBER[SUFFIX]...
  or:  sleep OPTION
Pause for NUMBER seconds.  SUFFIX may be 's' for seconds (the default),
'm' for minutes, 'h' for hours or 'd' for days.  Unlike most implementations
that require NUMBER be an integer, here NUMBER may be an arbitrary floating
point number.  Given two or more arguments, pause for the amount of time
specified by the sum of their values.

      --help     mostra questo aiuto ed esce
      --version  stampa le informazioni sulla versione ed esce

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Segnalare i bug di traduzione di sleep a <tp@lists.linux.it>
Full documentation at: <http://www.gnu.org/software/coreutils/sleep>
or available locally via: info '(coreutils) sleep invocation'

**Comment by Mcat12** [comment]
It looks like the command parsing for `--refresh` has some issues, so use `-r`. You also need to specify a refresh amount in seconds:
```
pihole chronometer -r 5
```
