### ISSUE TITLE
Error installing FTL with basic-install.sh

### ISSUE THREAD

**Issue by natesholland** [pi-hole/pi-hole#2707]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I would expect the install script to run to completion.

**Actual behaviour:**

I get the following error:

```
  [i] Downloading and Installing FTL...curl: (60) SSL certificate problem: certificate is not yet valid
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.2.3/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed
```

**Steps to reproduce:**

Clone the repo and run `sudo bash basic-install.sh`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I was unable to get this token

**Troubleshooting undertaken, and/or other relevant information:**

I've tried updating my certs and re-running. I'm unsure what else to try.

**Comment by dschaper** [comment]
That looks to be a date/time error on the device that you are trying to install on. "Certificate is not yet valid" points to the date being behind actual date. Can you check the current system date and correct it?

**Comment by natesholland** [comment]
That was the problem. Thank you for the help! Sorry it was something to dumb.
