### ISSUE TITLE
Need to restart PIHole to Gain Access to Internet

### ISSUE THREAD

**Issue by cryptodan** [pi-hole/pi-hole#2710]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** Not very

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}` 1

---
**Expected behaviour:** - Having not to restart pihole to get internet access

`{A detailed description of what you expect to see}`  I expect to have wireless connectivity without having to constantly restart pihole.

**Actual behaviour:**

I have to restart pihole to gain access to the internet after connecting to any wifi hot spot.

`{A detailed description and/or screenshots of what you do see}`

cryptodan@pegasus ~ $ sudo systemctl status pihole-FTL.service
[sudo] password for cryptodan: 
● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Wed 2019-04-17 12:05:20 UTC; 1min 52s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 929 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUC

Apr 17 12:05:19 pegasus systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 17 12:05:19 pegasus pihole-FTL[929]: Not running
Apr 17 12:05:19 pegasus su[1064]: Successful su for pihole by root
Apr 17 12:05:19 pegasus su[1064]: + ??? root:pihole
Apr 17 12:05:19 pegasus su[1064]: pam_unix(su:session): session opened for user 
Apr 17 12:05:20 pegasus pihole-FTL[929]: dnsmasq: unknown interface wlp61s0
Apr 17 12:05:20 pegasus su[1064]: pam_unix(su:session): session closed for user 
Apr 17 12:05:20 pegasus systemd[1]: Started LSB: pihole-FTL daemon.

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

Nothing much to it, I have had to do this since around kernel 4.18 to present something changed.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}` [✓] Your debug token is: https://tricorder.pi-hole.net/ui7952h96t!

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

I have to perform a simple "sudo service pihole-FTL restart" to gain internet access.

**Comment by dschaper** [comment]
`dnsmasq: unknown interface wlp61s0`

Somewhere in your `/etc/dnsmasq.conf` or in a `/etc/dnsmasq.d/*.conf` files you have an incorrect configuration line that refers to `wlp61s0`. Check `ip address` and see what your network interfaces are named and correct the config to use the proper interface name.

**Comment by dschaper** [comment]
Also I see that you are using Apache2 so there were other configuration changes and modifications made to allow this, this is not a stock install.

**Comment by cryptodan** [comment]
This is my 01-pihole.conf file located in /etc/dnsmasq.d/

# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=2

log-async

# If a DHCP client claims that its name is "wpad", ignore that.
# This fixes a security hole. see CERT Vulnerability VU#598349
dhcp-name-match=set:wpad-ignore,wpad
dhcp-ignore-names=tag:wpad-ignore
server=96.244.76.243
server=8.8.8.8
**interface=wlp61s0**

As you can see the interface is named correctly.

**Comment by dschaper** [comment]
And what are your interfaces named?

**Comment by cryptodan** [comment]
cryptodan@pegasus /etc/dnsmasq.d $ sudo ifconfig -a
enp59s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 80:fa:5b:4a:6a:11  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 9975  bytes 836624 (836.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9975  bytes 836624 (836.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:d3:b0:94  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0-nic: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 52:54:00:d3:b0:94  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp61s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.43.74  netmask 255.255.255.0  broadcast 192.168.43.255
        ether cc:2f:71:28:8c:f0  txqueuelen 1000  (Ethernet)
        RX packets 431091  bytes 467527923 (467.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 278213  bytes 42891813 (42.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by dschaper** [comment]
Is the Pi-hole using WiFi for upstream communication? And does that IP change when you connect to a new WiFi hotspot?

**Comment by cryptodan** [comment]
Yes as it is my lap top connecting to my mobile phone and my tablet hotspots.  Both use the same ssid, and the IP does not change when connecting to the two hotspots.  I will have to see if it has issues on my home wifi, but I am thinking that it will.

**Comment by dschaper** [comment]
I don't know if you will be able to fix this as Pi-hole was not designed to be on a client device in that configuration and instead is meant to be actually on the network at the same level as the router. If the upstream connection changes, or connects to a new access point, then the interface resets and that most likely will cause pihole-FTL to not function as designed.

@DL6ER would the interface going down cause pihole-FTL to stop working?

**Comment by DL6ER** [comment]
> would the interface going down cause pihole-FTL to stop working?

This is likely and can maybe circumvented by specifying `bind-interfaces`.

Quoting Simon:
> On systems which support it, dnsmasq binds the wildcard address, even when it is listening on only some interfaces. It then discards requests that it shouldn't reply to. This has the advantage of working even when interfaces come and go and change address. This option forces dnsmasq to really bind only the interfaces it is listening on. About the only time when this is useful is when running another nameserver (or another instance of dnsmasq) on the same machine. Setting this option also enables multiple instances of dnsmasq which provide DHCP service to run in the same machine.

**Comment by cryptodan** [comment]
I have to restart pihole after my interface is up and active otherwise i get no internet.  Here is what I do when I am on my lap top.  

1) Mobile Hot Spot Activated on either Samsung Tablet S4 or Samsung Note 9 (these devices become the router)

2) Plug in lap top and power it up, and wifi is automatically connected.

3) open terminal up and perform "sudo service pihole-FTL restart" and this gets me internet throughout the day and even when I lose access to my hotspot all I gotta do is reconnect and it works as it should when powering it up.

4) I have noticed this after Kernel 4.18 and newer.

**Comment by yubiuser** [comment]
@cryptodan 

Does the issue still persists in a current version of Pi-hole?

**Comment by cryptodan** [comment]
I will need to reinstall pi-hole to verify that it is still an issue.
