### ISSUE TITLE
Feature request: Whitelist for X minutes

### ISSUE THREAD

**Issue by fredericdepuydt** [pi-hole/pi-hole#2711]
Hi,

Would love to see the possibility to Whitelist a domain for a fixed short amount of time.

Kind regards,
Frederic Depuydt

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
