### ISSUE TITLE
Issuing teleporter on commandline leads to wrong extension

### ISSUE THREAD

**Issue by SirUli** [pi-hole/pi-hole#2714]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**
`pihole -a teleporter` respectively `pihole -a -t` should lead to the creation of a .tar.gz or .tgz named file since it is actually one.

**Actual behaviour:**
Commands above create a file ending with ".zip"

**Steps to reproduce:**
Issue commands `pihole -a teleporter` respectively `pihole -a -t` in commandline.

**Troubleshooting undertaken, and/or other relevant information:**
* File Information:
``` bash
/etc/pihole# file pi-hole-teleporter_2019-04-21_17-22-06.zip
pi-hole-teleporter_2019-04-21_17-22-06.zip: gzip compressed data, from Unix
```
* When the button for the teleporter is pressed in the UI, it actually produces a tar.gz file. See here: https://github.com/pi-hole/AdminLTE/blob/5ec769d9d8ed70d43e1d774722d6e9a7f5002f14/scripts/pi-hole/php/teleporter.php#L171

**Comment by dschaper** [comment]
@Mcat12 Didn't this get addresses a year or so ago? I thought there was some changes to teleporter that included the file type.

**Comment by SirUli** [comment]
@dschaper you mean [that commit](https://github.com/pi-hole/AdminLTE/commit/7f33b102dfdc92a01f58f85c527c4ae2cf9ff214#diff-3e979b46422dde1d81341526e434d794) to the AdminLTE?

And changing my mind about the "how familiar are you with the source code relevant to the this issue": [Here](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L533) you simply need to change to tar.gz instead of zip.

**Comment by dschaper** [comment]
It looks like that's the case, see https://github.com/pi-hole/AdminLTE/pull/595/files#diff-3e979b46422dde1d81341526e434d794R184
