### ISSUE TITLE
Ubuntu 19.04

### ISSUE THREAD

**Issue by tyrnight** [pi-hole/pi-hole#2715]
After an update to Ubuntu 19.04 pihole is dead. I realize it's not yet supported. Just submitting a ticket to make others aware.

**Comment by dschaper** [comment]
We'd need a lot more information to even begin to start troubleshooting or improving Pi-hole to support 19.04. Closing this issue so that you can open a new one with the template filled out to assist us.

**Comment by sz4bi** [comment]
in lighttpd 1.4.45 (ubuntu before 19.04) we have /usr/share/lighttpd/create-mime.**assign**.pl
in lighttpd 1.4.53 (ubuntu 19.04) we have /usr/share/lighttpd/create-mime.**conf**.pl

this breaks lighttpd after dist-upgrade, we need to change the install script and lighttpd.conf

**Comment by dschaper** [comment]
We need to find a solution that works for both 1.4.45 and 1.4.53 as we are not going to drop support for existing releases that use the .45 package.
