### ISSUE TITLE
If package manager issue, install script gives non-actionable error message.

### ISSUE THREAD

**Issue by Piskvor** [pi-hole/pi-hole#2719]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)). - someone reported these symptoms as #2701, but was closed for the report itself being invalid, without looking at the bug.

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

When package manager returns with error, an actionable error message is shown.

**Actual behaviour:**

Install script fails with `Unable to update package cache. Please try "\e[1;31m"` - note the raw ANSI code instead of useful information.

**Steps to reproduce:**

- Have a Ubuntu-based system with a repo whose signing key expired
- Run `wget https://install.pi-hole.net/ -O pihole.sh; bash pihole.sh`
- See the script fail with the above error
- Run `apt update`
- See it fail with a nonzero code and an explanatory error message

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not applicable, this is so early in the install script that nothing is installed yet, let alone `pihole` proper.

**Troubleshooting undertaken, and/or other relevant information:**

- Searched install script for "update package cache"
- Found https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1543
- Noted the duplicated coloring: `"${COL_LIGHT_RED}" "${COL_LIGHT_RED}" "${COL_NC}"`
- Ran with `set -x; sudo bash pihole.sh` : what's the 2nd variable supposed to actually contain?
- Assuming `${UPDATE_PKG_CACHE}`, as that's the command failing above, this is probably what's intended.
- Pull request with a fix: #2718

**Comment by dschaper** [comment]
Thanks!

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
