### ISSUE TITLE
Conflict with running webservers

### ISSUE THREAD

**Issue by jobro13** [pi-hole/pi-hole#272]
Pi-hole is fantastic, but there's an issue which needs to be adressed. I'm running a website on my pi, but also want to run pi-hole on it. However, (if my understanding is correct) pi-hole will now redirect my DNS requests to the IP-adress of my pi. This however might serve one of my website pages as an ad!

The main point here is that there is a conflict with the current webserver. It can be reconfigured, yes, but the main point is that it _has_ to be done. Would there be any workaround to this?
##

**Comment by PromoFaux** [comment]
At the moment we're using lighttpd to serve the 404 page (`/var/www/html/pihole/index.html`) which means any requests coming on port 80 that aren't resolved are served with that page...

As far as I'm aware you can host other websites alongside this, but @Mcat12 may be better placed to answer that

**Comment by Mcat12** [comment]
You can run other webpages on the pi. I have mine set up with a few other projects hosted on my pi. If it's redirecting you from your website to the blocked page when you're sure that the page exists, try updating your Pi-hole. There was a config change that fixed this.

**Comment by PromoFaux** [comment]
Did this answer your question @jobro13 ?

**Comment by jobro13** [comment]
I don't think we are on the same line of thought here. My knowledge about DNS/web servers is rather limited though, so please correct me if I'm saying wrong things.

The main problem is that if another server is running, which is not properly configured to run alongside pihole, it will cause issues. A simple example:

An ad domain servers it's ads via domain.com/ads.php

The current server also has ads.php setup. 

Pi-hole responds to our DNS query and returns the IP address of Pi. The current webserver isn't returning the pi-hole error page now. It will return ads.php as it is on the current server.

The way to solve this is to change the configuration of the webserver. However, by just plainly installing, there could be issues with the current webserver. I don't see a way to fix this which catches this all. Maybe lighttpd should be configured that it will *always* return the error page if any `Host:` header of the request is set to an advertisement domain. If it isn't, it will pass it on to the next service. This could possibly fix this issue.

**Comment by DonLexos** [comment]
Don't you get a conflict since both webservers would be checking port 80 for traffic regardless of headers?

**Comment by jobro13** [comment]
Good point, but since port 80 is already occupied by another process, wouldn't this lock another process out?

I do remember there's an option for sockets to 'reuse' it's address or something.

**Comment by Mcat12** [comment]
I think it would be very unlikely for an ad to be requested that matches a file's path on your machine exactly. Even so, it would still cause the ad to be blocked, as it isn't getting the ad it wants.

**Comment by jobro13** [comment]
Yes, it's very unlikely, I agree on that. But it's possible, and therefore this issue should be addressed. The point is that the blocked ad will actually load this webpage - which means any server-sided code will be executed and also complete pages could be send as "ad" to the client. This is unwanted.

**Comment by jacobsalmela** [comment]
It might be possible to construct some logic to avoid this happening to your Website.  `lighttpd` can match domains or other parts of the URL like what we do for the admin folder:
```
$HTTP["url"] =~ "^/admin/" {
	# Create a response header for debugging using curl -I
	setenv.add-response-header = ( "X-Pi-hole" => "The Pi-hole Web interface is working!" )
}
```
In a similar manner, you can also match domain names and do something different with them:
```
$HTTP["host"] =~ "ads.hulu.com|ads-v-darwin.hulu.com|ads-e-darwin.hulu.com" {
	server.document-root        = "/var/www/someotherwebsite"
}
```
You can also do some if/else logic.  I'm wondering if something like this might solve the problem, but it would be unique to each persons site...

**Comment by jobro13** [comment]
> You can also do some if/else logic. I'm wondering if something like this might solve the problem, but it would be unique to each persons site...

That's exactly the point here. As Pi-Hole has a one-liner to install, this would violate that philosophy. I'm still thinking about a way to catch all these conflicts in an elegant manner.

**Comment by Mcat12** [comment]
The if/else wouldn't be in the install command. It would be somewhere in the configs.

**Comment by dschaper** [comment]
Pinging for status update...

**Comment by Mcat12** [comment]
The idea of having multiple ports should solve this.

**Comment by Mcat12** [comment]
And 0.0.0.0 solves this too

**Comment by Fourdee** [comment]
@Mcat12 

> And 0.0.0.0 solves this too

I came to the same solution to free up the webserver:
http://dietpi.com/phpbb/viewtopic.php?f=11&t=527&p=2295#p2295

```
#Redirect blocked sites to a null IP address
sed -i "s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/0.0.0.0/" /etc/pihole/gravity.list
```

**Comment by dschaper** [comment]
We've looked at the 0's solution, but that has the side effect of not showing the block page. (I've ended up with a large number of 'broken' sad's, which is kind of distracting.) I know that either changing serving ports for the secondary webserver works fine as well as creating psuedo/virtual interfaces and giving them another IP address works as well. There's actually quite a number of workable solutions to the secondary webserver need.

**Comment by Fourdee** [comment]
@dschaper 

> (I've ended up with a large number of 'broken' sad's, which is kind of distracting.)

True, but i'd imagine its alot less distracting than the advert itself lol :)

As a global workaround, regardless of which webserver the user has installed, wouldn't it be an idea to have this as a option that ```gravity.sh``` scrapes prior to creating ```gravity.list```? 
Or even a $@ optional input for ```gravity.sh```, eg ```gravity.sh redirect=null```?

**Comment by dschaper** [comment]
> True, but i'd imagine its alot less distracting than the advert itself lol :)
For me, half dozen of one, six of the other. But we do have a lot of users that are setting up the Pi-Hole for relatives or friends, and the number of issues and support requests for "You broke my web browser!" would skyrocket. ;)

As for an option for the installer to chose localhost or nullroute for the source, that's actually an interesting idea that we'll take a look at. I think it's definitely fair to give the option. And if you'd like to PR we'd look at implementing it!

**Comment by Fourdee** [comment]
> And if you'd like to PR we'd look at implementing it!

:+1:

**Comment by dschaper** [comment]
Sorry, didn't know we had a FR tag :)

**Comment by dschaper** [comment]
And is there anything in #444 that would be of interest? I think it's got 3 different threads going on, but it started out with a nullroute discussion.

**Comment by DropbearNinja** [comment]
I came across this issue while trying to set up an additional web server on a clean raspberry running pihole and nothing else. My issue wasn't the rare situation describe above, but that ANY *.js file is blocked by lighttpd.conf via:

`# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
    # Create a response header for debugging using curl -I
    setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
    # rewrite only js requests
    url.rewrite = ("(.*).js" => "pihole/index.js")
}`

i.e. additional websites would load, but if they used any js at all, they're broken.

My workaround was to run any additional sites on a different port:

`$SERVER["socket"] == ":81" {
    server.document-root = "/home/pi/muximux"
}`

and to change the js filter to only work on port 80 (i.e. all other ports are ok)

`# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
        $SERVER["socket"] == ":80" {
            # Create a response header for debugging using curl -I
            setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
            # rewrite only js requests
            url.rewrite = ("(.*).js" => "pihole/index.js")
        }
}`

I'm not terribly good at all this, so I'm not sure if this helps anyone, or breaks anything, but seems to be working as desired at the moment...

**Comment by Mcat12** [comment]
You can also add to the regex, to only block .js if it's not under /admin OR part of your website. Alternatively, you could just remove the .js rule, since it doesn't quite affect the end user too much.

**Comment by jacobsalmela** [comment]
This feature request is [already votable in orbit](https://discourse.pi-hole.net/t/support-for-choice-of-resolver-and-or-web-server/222).
