### ISSUE TITLE
Changing port breaks /pihole

### ISSUE THREAD

**Issue by dom-madrid** [pi-hole/pi-hole#2720]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Install Pihole on a server with an existing web server on port 80/443, change lighttpd port from 80 to 8088 (to restrict access to only lan access - no web), get normal access for both /admin and /pihole

**Actual behaviour:**

/pihole no longer works (it does under port 80).
/admin works

**Steps to reproduce:**

Install Pihole
Change lighttpd.conf port from 80 to 8088
Restart lighttpd and pihole
Goto 192.168.1.xx:8088/pihole
get the following error:
[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/i5wobdlcel!

**Troubleshooting undertaken, and/or other relevant information:**

Running on existing Ubuntu Server 16.04 LTS with both lighttp and Apache

**Comment by dschaper** [comment]
There is no `/pihole` endpoint in the Pi-hole web server setup. How did you install Pi-hole?

**Comment by dom-madrid** [comment]
I cloned the git repo as per https://github.com/pi-hole/pi-hole/#one-step-automated-install and followed alternate option 1.
Add'al Info
/var/www/html clearly has a /pihole folder
On a straight install to port 80 (on a different machine - VM or PM - Ubuntu or Raspbian), when accessing 192.168.1.xx/pihole you get the Pihole logo and an invitation to redirect to the /admin page.

**Comment by dschaper** [comment]
There is a folder there, but there is no handling for that URL in the lighttpd configuration. That folder holds the 404 page that we use for the soon to be deprecated block page. Any URL will show that page (other than /admin) so 192.168.1.1/pi would redirect to that page. 

What blocking mode are you using and do you need or use the block page?

**Comment by dom-madrid** [comment]
I do not use block page - maybe I should or I missed a configuration step. I was just surprised it stopped working when changing the lighttpd port from 80 to something else.

**Comment by dschaper** [comment]
If you use NULL blocking or NXDOMAIN you'll see a performance increase over IP. The trade off is that the block page is not functional. But with the change of more and more sites moving to TLS / HTTPS for delivery the block page becomes non-functional as well.

**Comment by dom-madrid** [comment]
Thanks for the info. Not an issue then. Closing.

**Comment by mschoettle** [comment]
There does seem to be an issue. I changed the port as described above and when accessing `http://pi.hole:8080` or `http://<ip>:8080` I get the same error message. With the default port `80` it forwards to the admin page.

Appending `/admin` does work.

**Comment by DL6ER** [comment]
@mschoettle This means that `lighttpd` is still listening on port 80. Can you post the config file including your changes?

**Comment by mschoettle** [comment]
Thanks for the quick response @DL6ER. I changed `server.port` in `/etc/lighttpd/lighttpd.conf`. I tried changing it in `external.conf` but it gave me an error due to a duplicate config setting.

The lighttpd log shows this:

`(mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  file(http://127.0.0.1/admin/scripts/pi-hole/php/queryads.php?domain=<ip/domain>:8080&amp;bp): failed to open stream: Connection refused in /var/www/html/pihole/index.php on line 130`

`http://127.0.0.1/admin/...` is hard-coded there.

**Comment by DL6ER** [comment]
Ah, yes, I see this

https://github.com/pi-hole/pi-hole/blob/e41c4b5bb691cea1f5b950d39518d8c404b5846e/advanced/index.php#L130

I have never used the blocking page, however, we should change this as we probably want to keep the blocking page? Pinging @dschaper and @WaLLy3K

**Comment by dschaper** [comment]
Since this issue is about `http://pi.hole/pihole` please open a new issue, filling out the template with what you see and what you expect to see.

**Comment by dschaper** [comment]
And see https://github.com/pi-hole/pi-hole/issues/2195#issuecomment-399121825

**Comment by mschoettle** [comment]
> Since this issue is about `http://pi.hole/pihole` please open a new issue, filling out the template with what you see and what you expect to see.

`/` (i.e., no redirect to admin page) and `/pihole` show the same content (`/var/www/html/pihole/index.php`) so it is the same problem. But since there is #2195 which is about the same problem I'm fine to continue there.
