### ISSUE TITLE
pre-loaded pi-hole kit based on wrong assumptions

### ISSUE THREAD

**Issue by mb73** [pi-hole/pi-hole#2723]
I bought a [pi-hole kit from pi-supply](https://uk.pi-supply.com/products/pi-hole-kit-network-wide-ad-blocker). 

**The problem:** It didn’t get an IP address from the router. 

**The cause:** In `/etc/dhcpcd.conf` I see this entry:
```
interface eth0
    static ip_address=192.168.1.19/24
    static routers=192.168.1.1
    static domain_name_servers=127.0.0.1
```
This cannot work for me, as my router has a different address. I found this entry above the eth0 entry that was obviously added during the pi-hole setup. At least this entry was the reason why my Pi could not ping any IPv4 addresses and thus pi-hole could not update. In any case it’s strange that the pi-hole setup does not replace eth0 settings in that file but just adds another eth0 entry.

Looking at [this table of default router IP addresses](https://www.techspot.com/guides/287-default-router-ip-addresses/) makes me think that `192.168.1.1` is very often the default for routers (2Wire, 3Com, Actiontec, Airlink, Asus, Aztech, Belkin, Buffalo, Cisco, Dell, D_Link, Eminent, Huawei, Linksys, and many more), but not always. 

I have a FRITZ!Box 7590. Its default address is a different one. And also I could have changed it.

**Comment by dschaper** [comment]
Thanks for opening the issue and providing us the information. Pi-supply provides the image that is used to create the SD card for the Pi-hole kit. We'll try to get in touch with them and correct any issues.

Is your Pi-hole working currently or do you need further help to get everything online?

**Comment by mb73** [comment]
@dschaper Thanks for the quick reply! It’s working now. After some desperate hours of research (I am not really a Linux or network administrator) I managed to get a temporary IP address with: `sudo dhclient -v eth0`
(in fact before I finally found the cause of the problem)
and then I could proceed as described in the instructions.

**Comment by dschaper** [comment]
Glad its currently working and thank you for the tip on the workaround. If you could, would you please send me an email at dan.schaper@pi-hole.net and let me know how you feel the purchase went and where we can improve the process?

**Comment by shawaj** [comment]
Hey @mb73 - thanks for opening the issue. Helps to tie in all the right people in one place!

We haven't had any similar complaints about DHCP not working so definitely strange. However as you say it is the default for many routers.

@dschaper is this the default for Pi-hole as part of the setup process, or how is this part of the config generated?

**Comment by dschaper** [comment]
The install script tries to determine the IP address based off of the interface address during the run of the script. It prompts with a whiptail and asks for confirmation, and then writes the static IP block to `/etc/dhcpcd.conf`.

**Comment by shawaj** [comment]
So if you run the setup again, it should fix this?

**Comment by dschaper** [comment]
Once the IP block has been written to `/etc/dhcpcd.conf` it has to manually be modified. There is no automated removal of that block currently as there is no real reliable way to figure out if the block was written by the installation process or was created by an outside process. If you run the install script again with a different IP address you will end up with two (or more) blocks with different IP addresses and will cause conflicts.

**Comment by shawaj** [comment]
So what do you think is the best way to resolve it? Just for us to remove the conf file altogether from the master images?

**Comment by mb73** [comment]
= won’t fix?

**Comment by dschaper** [comment]
It's Pi-supply's issue to resolve.

**Comment by shawaj** [comment]
@dschaper the image has been updated for some time to not have this issue.

I think @mb73 is probably referring to the fact that you hard code IP address and static routers...

**Comment by dschaper** [comment]
The IP addressing is set when the installation script is run. Pi-supply doesn't run the install script, they just burn a pre-made image on to the medium they ship. That's an issue that is not fixable by us. Since the kits are no longer authorized for sales by Pi-hole I just don't see a desire to fix their installation process.

**Comment by dschaper** [comment]
@shawaj Thanks for confirming that this issue has been fixed!

**Comment by dschaper** [comment]
> referring to the fact that you hard code IP address and static routers

Can you show me where we do that? I think that's just your image that does that.

**Comment by shawaj** [comment]
@dschaper - our image is just standard Raspbian, with your one line installer run on top of it...

curl -sSL https://install.pi-hole.net | bash

So it must have originated from Pi-hole installation or setup.

**Comment by dschaper** [comment]
You would have to run that for each client. Any IP information or data you enter for things like IP address, upstream DNS server, selected blocking lists is specific per installation. If you enter that information before you ship it, then it will be wrong for the user.

**Comment by shawaj** [comment]
@dschaper we never entered it before shipping. and we did not create the image...that was done by Jacob I believe.

the problem is `static routers=${IPv4gw}`

there is no reason to set this as far as I can see, and breaks things if you change router / location of box etc with an install set up

fix in #3094

**Comment by dschaper** [comment]
Jacob created that image over 2 years ago. If that's what you are using then it is horribly out of date. 

It's your problem with your deployment on your unauthorized kits.

**Comment by dschaper** [comment]
>our image is just standard Raspbian, with your one line installer run on top of it...

>we did not create the image

Which one is it?

**Comment by shawaj** [comment]
@dschaper it is both, delivered to us by Jacob.

It is not horribly out of date. As mentioned on Twitter the image has been updated several times, to remove this issue that was created by yourselves, and since then to update the Pi firmware, update Pi-hole versions etc

**Comment by dschaper** [comment]
Cool, then the issue is solved yes?

**Comment by shawaj** [comment]
apart from the fact that hard coding static routers is not a good idea, yes

**Comment by dschaper** [comment]
We don't. So that's not an issue.

**Comment by dschaper** [comment]
We ask the users what IP address to use and then set the stack as per their request. It's not something you can set at your shop and then send out without modifications.

**Comment by shawaj** [comment]
@dschaper well, you did, because the image you gave to us had it like that.

and you do set the static routers on the device - the code proves it.

Meaning that if you get a new router with a different IP then it breaks...

**Comment by dschaper** [comment]
You're daft.

**Comment by dschaper** [comment]
You want dynamic addressing for a DNS server. That's so beyond any kind of rational thought.
