### ISSUE TITLE
installation and operation of pi-hole not possible with umask 0027

### ISSUE THREAD

**Issue by pvogt09** [pi-hole/pi-hole#2724]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

I could program a fix, because it is as easy as adding chmod o+r ... to some source files, but I would possibly not find all the places, where this would be needed.

---
**Expected behaviour:**
Installation and operation (e.g. changing setting in web interface and performing list updates etc.) of pi-hole with umask 0027 in /etc/profile works without errors and need of manal file permission changes.

**Actual behaviour:**
When umask is set to something that does not include world readable, e.g. 0027, in /etc/profile, the installation script fails when starting dnsmasq with a permission denied error, because the configuration files under /etc/pihole/* and /etc/dnsmasq.d/01-pihole.conf as well as the web interface files (/var/www/html/{admin, pihole}) created by the installer are not readable by the pihole or www-data user. When changing the file permissions by hand to world readable, another try for the installation works except for the need for some manual (re-)starting of services.

If a list update is performed after the installation with manually corrected file permissions, the list file chache, black.list and gravity.list are deleted and recreated without respecting the file permissions the files had before deletion, so they are in turn not readable by the pihole user again. The installer and updater should make sure, that the file permissions are not changed or set to the correct value independently of the umask settings of the pihole user/root user.

When opening the settings page in the web interface, even if nothing is changed there, the options /etc/pihole/setupVars.conf is also deleted and recreated and then read again, which causes php to show a permission denied error at the bottom of the page, because the file was in turn created without read access for every user.

The manual entries under /usr/local/share/man/man* are also not world readable and the created folders are not owned by root:staff as all other directories are under Raspbian, which causes apt-get to issue warnings about missing file permissions in the update man-db step when installing or removing any program after running the pi-hole installer.

**Steps to reproduce:**
```
sudo su
echo 'umask 0027' >> /etc/profile
curl -sSL https://install.pi-hole.net | bash
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

not relevant?

**Troubleshooting undertaken, and/or other relevant information:**

I changed the file permissions in /etc/pihole* and the other configuration files under /etc created by the installer to world readable and restarted all the necessary services.
This leads pihole to do its job (except for updates) properly, but without the web interface, which shows 403 responses until I changed the file permissions for all files in the web interface to world readable, which also also made the web interface functionable except for the pages, that change configuration settings or do updates.
A simple fix on the user side would be to not mess file systems's umask, but as mentioned in the [Securing Debian Manual](https://www.debian.org/doc/manuals/securing-debian-howto/ch4.en.html#s4.11.12), this could be useful for some people. 

A simple fix for the pi-hole installer and updater would be to explicitly set file permissions on files, that have to be world readable, to world readable in gravity.sh and basic-install.sh.
A way to track all needed file permissions in the Git repositories could be to use a similar approach as the one used in [etckeeper](http://etckeeper.branchable.com/), where a special file with a list of file permissions is kept in the repository.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
