### ISSUE TITLE
"Teleporter - The file you are trying to upload is not a .tar.gz file" 

### ISSUE THREAD

**Issue by jaxjexjox** [pi-hole/pi-hole#2726]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- X[] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0

---
**Expected behaviour:**
Export file should be compatible with importing into another  Pi-Hole instance

**Actual behaviour:**

Error as per subject.
My export file is a .ZIP file (??) not a .tar.gz
Identical to this job here:
https://github.com/pi-hole/pi-hole/issues/2099
Please note I'm running DEV and the export process is still producing zip files (?)
Pi-hole Version vDev (development, v4.2.2-34-gb64fb57) Web Interface Version vDev (devel, v3.0-98-g40ae7fb0) FTL Version vDev-320a9c8

**Steps to reproduce:**

Export a teleporter extract using latest dev build. (well as far as I know it's latest)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

No can do, see below.

[?] Would you like to upload the log? [y/N] y
/opt/pihole/piholeDebug.sh: line 1192: tricorder_use_nc_or_ssl: command not found
[✗]  There was an error uploading your debug log.
**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

N/A

**Comment by Mcat12** [comment]
This is fixed by the following PR (in `release/v4.3`): https://github.com/pi-hole/pi-hole/pull/2717

**Comment by Mcat12** [comment]
See #2727 and #2728 for the debugger error.

**Comment by jaxjexjox** [comment]
Thank you for the quick response.

Is there anything I can do, in the meantime?
It's not as simple as renaming a zip file, is it ?

I'd like to transition from a physical R.Pi to a Pi Docker to free up a system.

**Comment by Mcat12** [comment]
It should be as simple as renaming it to end in `.tar.gz`

**Comment by jaxjexjox** [comment]
That has actually not worked. However, you've helped enough- it's gonna be fixed.   So in the meantime I can reconfigure manually.
Thank you.

**Comment by ices-dev** [comment]
It is still not working in the latest release: Did an export and got an *.tar
Renaming to *.tar.gz doesn't help.

**Comment by dschaper** [comment]
Open a new issue please. If neither .tar or .tar.gz works then this thread is not going to help you.
