### ISSUE TITLE
Don't hardcode ADMIN_INTERFACE_DIR/webInterfaceDir 

### ISSUE THREAD

**Issue by oakkitten** [pi-hole/pi-hole#2729]
**In raising this issue, I confirm the following:
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 2

---
**Expected behaviour:**

Pi-hole allows specifying a custom folder during install and through configuration files.

**Actual behaviour:**

The path to the admin page is hardcoded in multiple files as `/var/www/html/admin/`. Not on every system the html folder is at `/var/www/html`, and not every `admin/` is unused for other purposes, so this is a problem. While I can move the folder elsewhere manually, the updates fail. Other things can probably fail as well.

**Steps to reproduce:**

Install pi-hole

P.S. Hardcoding stuff in multiple places sounds like a bad idea anyways

**Comment by Mcat12** [comment]
We are working on major changes which would eventually allow us to solve this. See #2692.

**Comment by yubiuser** [comment]
Duplicate, closing in favor of https://github.com/pi-hole/pi-hole/issues/3101
