### ISSUE TITLE
Odd Issue With Secure Sites

### ISSUE THREAD

**Issue by gh0stshell** [pi-hole/pi-hole#273]
I am having issues with sites using HTTPS connections, sometimes they work fine while other times odd things happen. The most common error I get is connection refused. If I no longer point to my Pi and point to my DNS server everything works just fine. After getting the site to load I then switch back.

**Comment by gh0stshell** [comment]
I did whitelist the site which made it work for a while then the issues start again, randomly.

**Comment by dschaper** [comment]
Ad serving sites that use HTTPS will get you a connection refused error, because the Pi-hole isn't running a server on that port. (It would give you a certificate error or another error if we were to start a server on that port, since we're basically impersonating the ad serving domain and sending a blank response in place of an ad.) Are the sites that are giving you problems ones that are on the block lists? Can you `tail` the `/var/log/pihole.log` when you visit the sites and see if they are served via DNS or via `gravity.list`?

**Comment by gh0stshell** [comment]
Sure the site is a site I use to access links called safelinking.net

I also have noticed I cannot upload files to wordpress sites while pointing to my pi-hole.

**Comment by gh0stshell** [comment]
I got help from my firewall support, AP support, etc... and they call cannot find a reason why any of these would prevent me from uploading to wordpress, my computer is the only one with the issue as its the only one pointing to the pi-hole

**Comment by dschaper** [comment]
Can you run `tail -f /var/log/pihole.log |grep gravity.list` when you upload to `wordpress`? That command will list out every domain that is redirected to the Pi-hole's `dnsmasq` hosts list process.

**Comment by gh0stshell** [comment]
I will once I get a chance in about 1 hour

**Comment by gh0stshell** [comment]
oh FYI I dont know if you can add this in or its from the list pulled but safelinking.net is not an ad site, it allows people to share links, it has ads on the page, but does not produce ads itself

**Comment by dschaper** [comment]
Yeah, I just saw that `safelinking.net` is listed as an ad site, trying to pull down which list has it and why it's listed.

**Comment by dschaper** [comment]
http://hosts-file.net/default.asp?s=safelinking

**Comment by gh0stshell** [comment]
odd thing is my forum site which is https has had no issues while only safelinking.net is the one not working correctly or https connection refused

**Comment by gh0stshell** [comment]
I will check back in a bit

**Comment by dschaper** [comment]
I whitelisted `safelinking.net` and `www.safelinking.net` and they no longer trip the Pi-hole, as long as I cleared out the DNS cache on the Windows client I'm on. But a visit to `http://www.safelinking.net` redirects to `https://safelinking.net` with just a blank page. Trying without the Pi-Hole to see what the direct view should look like...

**Comment by dschaper** [comment]
This is the whitelist trigger I get:

![capture](https://cloud.githubusercontent.com/assets/2782850/12707421/02edcda8-c849-11e5-81e8-205a8d5dd6f2.PNG)

**Comment by dschaper** [comment]
Here's what I got as domains needing whitelisting for `safelinking.net`:

```
safelinking.net
www.safelinking.net
analytics.safelinking.net
api-secure.solvemedia.com
api.solvemedia.com
```

**Comment by gh0stshell** [comment]
if you issue  /usr/local/bin/whitelist.sh safelinking.net it does i think 6 domains total maybe 4, i do not remember

**Comment by gh0stshell** [comment]
all link I am going to do not have a www in front just https://

**Comment by dschaper** [comment]
`whitelist.sh safelinking.net` will only whitelist the `safelinking.net` section. The webpage uses `solvemedia.com` for the CAPTCHA. You may not need the other domains in the whitelist right now, but if you want to make sure that `safelinking.net` doesn't break in the future if those domains are added to an adlist, then it's safe to add them to the whitelist now...

**Comment by gh0stshell** [comment]
The issues I currently get are

connection refused
blank white page
page partial loads including the captcha

**Comment by dschaper** [comment]
What does your `/etc/pihole/whitelist.txt` look like? And have you cleared the DNS cache on the client machine? (And a hard reload of the page in the browser.)

**Comment by PromoFaux** [comment]
Any update on this @gh0stshell ?

**Comment by jacobsalmela** [comment]
I know `lighttpd` can listen on multiple ports and handle SSL.  Maybe we just need to enable it so SSL ads are blocked?  I would like to hear from @gh0stshell, too though.

**Comment by dschaper** [comment]
I think the problem we are going to run into is the SSL certificates. If the browser is calling for `https://adsite.com` and we respond with a self-signed certificate from the Pi-hole server, then the browser is going to throw an error. It'll see it as an attempt at a MITM attack...

**Comment by jacobsalmela** [comment]
That's true...more pondering I guess!

**Comment by dschaper** [comment]
I do wonder where gh0stshell went, I'd like to see how this one turns out...

**Comment by gh0stshell** [comment]
I am still here, just was busy, I am trying to get the best and most detailed info I can get by testing and watching the logs.

The odd thing is if I go back to my local DNS and go to safelinking.net and then go to the pi-hole it continues to work and the couple of ads that show up disappear so I know its going through the pi-hole, very odd indeed, what should I watch to see what happens?

**Comment by gh0stshell** [comment]
I am coming to the conclusion that the wordpress issue is not pi-hole related

**Comment by PromoFaux** [comment]
> I am trying to get the best and most detailed info I can get by testing

This type of user is best type of user :+1:

**Comment by dschaper** [comment]
@gh0stshell All the `dnsmasq` logging takes place in `/var/log/pihole.log` with the blocked sites showing as a line with `/etc/pihole/gravity.list` as the source. You can also check out `/var/log/lighttpd/access.log` to see which html requests are being served as the blank html document. The default `dnsmasq` configuration, which is now stored in `/etc/dnsmasq.d/01-piehole.conf` sets a TTL so that the client machines may cache DNS lookups. That cache may cause some odd behavior if it's not cleared when changing DNS servers on the clients. (On a Windows machine you'd need to run `ipconfig /flushdns` to make sure the DNS cache is clear...)

**Comment by gh0stshell** [comment]
I have gotten everything whitelisted, but with safelinking.net using HTTPS with all its links that will be the issue so this may not be a bug. Any thoughts?

**Comment by gh0stshell** [comment]
opening a new ticket for the chrono script

**Comment by dschaper** [comment]
Okay, so what is the current status of the issues? What's broken and what's working? I'm not sure where we stand with the problems, and just want to get a good idea of what we have working and where we need to go to get everything operational for you. I'm not sure where the HTTPS comes into play, Pi-hole isn't really able to handle HTTPS requests due to the certificate issues. Thanks for sticking with us! (I'm hoping to have some kind of display screen in soon, it seems the one I ordered is being made before shipping?!)

**Comment by dschaper** [comment]
@gh0stshell How are we doing old friend?

**Comment by amerton** [comment]
@dschaper your 3rd of Feb msg.
I run an nginx server listening on 443 on same pi than pihole and have a self signed cert.
Occasionally I get a browser error on some sort of pihole filtered-out site. If I inspect the certificate the error report I see my own certificate.

**Comment by dschaper** [comment]
That's to be expected with the way the Pi-hole operates. It tells the browser to send advertisement requests back to the Pi-hole, and normally the http requests are handled by `lighttpd` and return the blank.gif if possible. If the ad is being served via https you normally would be a broken page icon as there is no server available for https traffic. You do have a server though running on that port, so the requests are being handled by `nginx`, probably as 404's, with the self-signed cert as the authority. 

So it operating nominally for the current situation and configuration.

**Comment by Fedora-Core** [comment]
**Observation**

Why HTTPS-hacking, Man-In-The-Middle-Proxies, Self-Signed-Certificates, - and any other measures - soon will no longer work  ==>

[http://www.certificate-transparency.org/](http://www.certificate-transparency.org/)

**Towards A Safer Internet.**

Read once to **grasp** what is the problem.
Read a second time to **know** the solution.
Read a third time to **understand why** it is the solution.

Greetings, F.C.

_Note:_
_Ever wondered how to install a self-signed-certificate in your (parent's) smart-TV?_

**Comment by nimkip** [comment]
Could HTTPS support be achieved with a solution similar to what pixelserv-tls does (https://github.com/kvic-z/pixelserv-tls)? That is, generate a Root CA cert and then import it to your clients.

**Comment by dschaper** [comment]
I could, but we don't want to get into self signed certs and forcing users to load CA's on all their devices. Plus that is just a bit too far into a Man In The Middle scenario and we don't want that kind of access to peoples devices. We're very big on user privacy and no one should have unverified CA level access to clients. Will not happen on my watch.

**Comment by Mcat12** [comment]
Reopen if the issue reoccurs.

**Comment by tobi-wan-kenobi** [comment]
Just for reference (sorry for a late reply to a closed topic, but I did not find this information anywhere else):

If you *really* want to ad-block websites that distribute ads via HTTPS, here's what you can do:

* Set up nginx or apache to serve pi-hole content on 443
* Set up a squid with ssl_bump and a certificate signed by a trusted CA (if you create your own CA, you need to add it to the list of trusted CA on your devices) - This is the "trick" that makes everything work. For ssl_bump (intercepting HTTPS, essentially), squid will create certificates for the sites that it proxies, and as long as your devices trust the CA squid uses, everything should be fine
* Set up a NAT rule on your router to redirect traffic targeted to your pi-hole box on port 443 (i.e. all HTTPS ad traffic) to squid.

So now, squid will intercept all SSL traffic that is targeted at your pi-hole and provide it with a valid certificate :-)

(My apologies if this is the wrong place to post this)

**Comment by Gui13** [comment]
What if you could simply say that the domain doesn't exist, so that the connection is not even attempted?

**Comment by Mcat12** [comment]
DNS does not differentiate between network protocols (HTTP, HTTPS, etc), so we would be unable to redirect only HTTPS requests to `0.0.0.0`.
