### ISSUE TITLE
Web interface claims update available, pihole -up reports Everything is up to date

### ISSUE THREAD

**Issue by hugalafutro** [pi-hole/pi-hole#2736]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

status of shown components at the bottom of web interface displayed as:
Pi-hole Version v4.2.2 Web Interface Version v4.2 FTL Version v4.2.3

**Actual behaviour:**

Pi-hole Version (Update available!) Web Interface Version (Update available!) FTL Version v4.2.3

**Steps to reproduce:**

install ubuntu-18.04.2-preinstalled-server-arm64+raspi3.img.xz on RPi 3 B+
apt update
apt upgrade
curl -sSL https://install.pi-hole.net | bash
access the webgui, notice it says Update available
pihole -up reports everything up to date

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/9ttn7xvoci!

**Troubleshooting undertaken, and/or other relevant information:**

tried to update with pihole -up which claims all is up to date
I have performed the same install steps on an ubuntu 18.04.2 server installed in vm where everything works as expected (the pi is supposed to be 2nd backup dns server to take over in case I have to reboot my home lab)

**Comment by dschaper** [comment]
If the `pihole -v` output shows `Untagged` then you are on the latest version. There have been no changes to the package, there were some changes made to the markdown files and GitHub metadata. We will push an update soon that will tag the code properly.

**Comment by salzig** [comment]
i can confirm that this seems to be related to an untagged version, as the dashboard of 4.3 doesn't show an update anymore.

**Comment by dschaper** [comment]
Should be solved in the latest release.
