### ISSUE TITLE
$HOSTNAME.local should direct to splash page

### ISSUE THREAD

**Issue by PharmaJap** [pi-hole/pi-hole#2740]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behaviour:**

Raspbian comes pre-installed with Avahi-daemon, and is therefore locatable at `$HOSTNAME.local` by default. Pointing your web browser to `$HOSTNAME.local` (in my case `rpi.local`) should produce the splash page, the same as typing the local IP address of the Raspbian system (in my case `10.10.10.2`). Both instances without the /admin directory.

**Actual behaviour:**

Pointing your web browser to `$HOSTNAME.local` (`rpi.local`) produces the block page, with the flag "Not found on any Blacklist". Pointing your web browser to the local ip address (`10.10.10.2`) produces the splash page. Both instances without the /admin directory.

**Steps to reproduce:**

Default Raspbian and PiHole installation with Avahi-daemon and a defined hostname.

**Troubleshooting undertaken, and/or other relevant information:**

Adding `setenv.add-environment = ("fqdn" => "true")` to `lighttpd.conf` or `external.conf` resolves the issue, and should be the default.

**Comment by Mcat12** [comment]
We don't support `$HOSTNAME.local` for showing the splash page. We only support the IP address, along with some other hosts on a conditional basis. See here for exactly how the other hosts are determined:
https://github.com/pi-hole/pi-hole/blob/b3898b9b2acb60c006d098ab6496a4817b2e88f2/advanced/index.php#L26-L35

Feature requests should be made on Discourse, as per the issue template.

**Comment by PharmaJap** [comment]
That's the exact code I was looking at; maybe there's some logic I'm not seeing.

`$_SERVER["HTTP_HOST"]` is pulled from the client request and is equal to whatever pointed the client to your server. Could be `yourdomain.com`, a public or private IP address, an mDNS hostname, or something defined in `resolv.conf`.

`$_SERVER["VIRTUAL_HOST"]` doesn't seem to be defined in the PHP spec. Virtual hostnames would be rolled into `HTTP_HOST` anyway.

So, as things stand, the block of code you posted goes **entirely unused** unless `setenv.add-environment = ("fqdn" => "true")` is set in `lighttpd.conf` or `external.conf`. Nothing will ever be added to `$authorizedHosts`.

If this is intentional, then this block can be removed, since checking for `pi.hole` or an IP address never uses `$authorizedHosts`. If enabling access by hostname is supposed to be a user-configurable option (via setting `setenv.add-environment = ("fqdn" => "true")` in `external.conf`), then this should be better reflected in the comment on lines 29-30.

I would argue that access by hostname is expected behavior, but if it's unsupported, then I would still consider the above code to be bugged/superfluous.

I will post the setting of `setenv.add-environment = ("fqdn" => "true")` via a checkbox in the admin panel as a separate feature request.

**Comment by Mcat12** [comment]
The code correctly follows the following logic:
If `FQDN` is set in the environment, allow the current host
If `VIRTUAL_HOST` is set in the environment, allow the configured virtual host.

Removing the block would remove this functionality. I don't see how the comment about `FQDN` can be interpreted other than you need to configure it as shown to activate that feature.

We are moving away from Lighttpd and the current PHP web interface, so we are avoiding adding features to it as the features will have to be rewritten in the new web interface. This can all be done more simply and cleanly via the upcoming API and web interface.

**Comment by PharmaJap** [comment]
Fair enough. Looking forward to the update.

**Comment by 13rac1** [comment]
If you find this issue in 2022+ and are running Pi-hole in Docker: Set the `VIRTUAL_HOST` environment variable to your `$HOSTNAME.local` value ([See the Docker container optional variables](https://github.com/pi-hole/docker-pi-hole/tree/1b35e7fdd425ee2ac49b3aadc33ac1489c897ef3#optional-variables).) Pi-hole shouldn't block any `.local` mDNS/Bonjour domain names, but this solves the issue and automatically redirects to the `/admin` path.
