### ISSUE TITLE
FTL cannot be installed at the end of the instalation

### ISSUE THREAD

**Issue by kovizsombor** [pi-hole/pi-hole#2747]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Installing Pihole with any of the commands provided on the github page.

**Actual behaviour:**

Just when pihole is about to finish installing I get the issue: "
[✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub"

**Steps to reproduce:**

I don't think it can be reporudced it just happenes to me

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I am unable to run any pihole commands yet.

**Troubleshooting undertaken, and/or other relevant information:**

Found this : https://github.com/pi-hole/pi-hole/issues/2636 but couldn't find an answer there. 

I just swapped routers and before this I didn't have this issue. Could be some bad router setting?

**Comment by dschaper** [comment]
Please try running the installer in verbose mode and capturing the entire message that is displayed when the FTL binary is sourced. `curl -sSL https://install.pi-hole.net | sudo bash -x`

**Comment by kovizsombor** [comment]
When I try to run any commands related with installing pihole I get the error message: **curl: (6) "Could not resolve host: install.pi-hole.net"**

**Comment by dschaper** [comment]
Check `/etc/resolv.conf` and see what DNS server is set there, if it's 127.0.0.1 then you'll need to manually edit that file to be 8.8.8.8 or 1.1.1.1 (or what ever DNS server you would like) then try the commands again.

**Comment by kovizsombor** [comment]
I replaced the whole file of `/etc/resolv.conf` with 8.8.8.8 but the commands are still not working

**Comment by kovizsombor** [comment]
Alright just had to tweak some things now it's working. Thanks for the help

**Comment by weechatter** [comment]
What things kovizsombor?

I get following error during upgrade:
[i] Downloading and Installing FTL...curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
i also replaced /etc/resolv.conf with 8.8.8.8 and 1.1.1.1, no luck

**Comment by bsmth** [comment]
> I replaced the whole file of `/etc/resolv.conf` with 8.8.8.8 but the commands are still not working

not the entire file contents, only the value of the `nameserver` property, for example:

```bash
# some comments here on file generation
nameserver 1.1.1.1
```

Mine looked like this to get update to work:

```bash
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 1.1.1.1
```

**Comment by dschaper** [comment]
Thanks for the tip, the last post in this thread is 3 years old. It may be indexed so others may stumble upon it.
