### ISSUE TITLE
Google analytics blocked in gravity

### ISSUE THREAD

**Issue by bellwood** [pi-hole/pi-hole#2748]
Not sure if this is the correct way to report this (if not I apologize) however it appears: 

analytics.google.com 
www.google-analytics.com
ssl.google-analytics.com

...are listed in gravity.

Pi-hole Version v4.2.2 
Web Interface Version v4.2 
FTL Version v4.2.3

Note: I get this seems like a dumb submission but seems recent - used to being able to review my sites' stats at home in the analytics interface while still have google tracking tags still blocked.

**Comment by dschaper** [comment]
Thanks, we do not curate the list contents and do not add or remove domains from the lists. You will need to find out what list is adding on those domains and then report to the upstream or whitelist/disable the list until it is functional for you again.

**Comment by dschaper** [comment]
Just running a quick check it appears the domain(s) are on multiple lists and thus seems to be intentional.

![Annotation 2019-05-17 203236](https://user-images.githubusercontent.com/2782850/57964039-04814200-78e3-11e9-90e2-dde33dcaf99d.jpg)
