### ISSUE TITLE
Unable to access admin panel via pi.hole

### ISSUE THREAD

**Issue by cmdshft** [pi-hole/pi-hole#2749]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Accessing pi.hole in web browser should open the admin panel.

**Actual behaviour:**

Accessing pi.hole in web browser says "failed to open page" open the admin panel. Can only access via the local IP address.

**Steps to reproduce:**

Unsure. I changed my blocklists and updated gravity, removed a bunch of whitelisted addresses and the issue began.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/a5mm9eq6zq!

**Comment by Mcat12** [comment]
Make sure your device is using Pi-hole (and only Pi-hole) as its DNS server.

**Comment by bcambl** [comment]
@Mcat12 possibly related to #2605?

**Comment by Mcat12** [comment]
That is possible. As the debug token is expired, we can't check the lighttpd logs for the related error.

**Comment by dschaper** [comment]
Any new information from this @cmdshft ?

**Comment by cmdshft** [comment]
> Any new information from this @cmdshft ?

So far, it's working as intended it seems. I usually just access via the IP address since I know that works 100% of the time.

**Comment by dschaper** [comment]
Thanks, I'll close this then and feel free to open / reopen if the issue occurs again.
