### ISSUE TITLE
upgrade to 4.3 resets admin http port to default

### ISSUE THREAD

**Issue by rrrevin** [pi-hole/pi-hole#2751]
When running pihole -u to update, the system ignores settings in the /etc/lighttpd/lighttpd.conf file currently installed.

During the previous install, I changed the server admin port from the default 80, to 40080. Ran fine for months.. Just did an upgrade from 4.2.2 to 4.3. After upgrade, and not being able to connect to the web interface, it turns out the upgrade reset the port back to 80, with zero warning it was doing do.

Please honor custom settings when doing an upgrade in respect to the lighttpd portion of the upgrade.

*** If this can't be fixed, can the upgrade script check and display that lighttpd is using a non-default port, and it needs to be MANUALLY re-configured? Would save a lot of debugging and frustration when this happens again.

=

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
1
---

**[BUG | ISSUE] Expected Behaviour:**
Leave server.port to what it was

**[BUG | ISSUE] Actual Behaviour:**
user cusomized settings in lighttpd.conf should be honored.

**[BUG | ISSUE] Steps to reproduce:**
run an upgrade.. pihole -u

**Comment by Mcat12** [comment]
We do not support custom modifications to `/etc/lighttpd/lighttpd.conf`. You will be able to have more control over the web server when we replace it with the API and new web interface.

**Comment by rrrevin** [comment]
can the upgrade script check and display that lighttpd is using a non-default port, and it needs to be MANUALLY re-configured? Would save a lot of debugging and frustration when this happens again.

**Comment by Mcat12** [comment]
It could, technically, but again we do not support custom modifications to that web server config. You can edit `/etc/lighttpd/custom.conf` instead, although we recognize that this is not the same. We are working on a real fix for this issue by replacing lighttpd instead of adding more and more workarounds for it.

You can try the new web interface out yourself if you want, by following the instructions in this PR on a fresh install: #2692. Note that this is still in an alpha stage.
