### ISSUE TITLE
update to 4.3 disables dns stats in settings/system

### ISSUE THREAD

**Issue by hugalafutro** [pi-hole/pi-hole#2752]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`DNS Cache size: & DNS cache insertions: & DNS cache evictions: showing some values`

**Actual behaviour:**

`the 3 DNS related statistics are empty`

**Steps to reproduce:**

`run pihole -up to update from 4.2.3 to 4.3`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`mnlc40140s!`

**Troubleshooting undertaken, and/or other relevant information:**

`ran pihole -r to no avail, the behaviour is same in both ubuntu 18.04 vm and on pi with raspbian stretch`

**Comment by dschaper** [comment]
The log doesn't show any clients actually using the Pi-hole services?

**Comment by hugalafutro** [comment]
Everything seems to be running ok, the queries show up in log, the graphs, the statistics. It's just the 3 fields which used to say 10000, some number and 0 usually are now empty like so: https://turbomrak.ddns.net/s/NjtyLNn5kCAeNFN

**Comment by hugalafutro** [comment]
rebooted both machines and everything is now in order, it just never did this before.
