### ISSUE TITLE
Install pihole 4.3 hangs on volumio (debian jessie) on dhcpcd5  and 63%

### ISSUE THREAD

**Issue by PieterGit** [pi-hole/pi-hole#2753]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1, not familiar. Found that removing `dhcpcd5` from resolves the installer issue.

---
**Expected behaviour:**

I expect pihole to install with the command:
```
curl -sSL https://install.pi-hole.net | bash
```
on a Volumio debian based raspberrry pi.

**Actual behaviour:**

Installer hangs at 63% while `Configuring dhcpcd5`. Screen shows:
```
 lqqqqqqqqqqqqqqqqqqqqqqqqqqu Installing packages tqqqqqqqqqqqqqqqqqqqqqqqqqqk
 x Configuring dhcpcd5                                                       x
 x                                                                           x
 x                                                                           x
 x                                                                           x
 x                                    63%                                    x
 x                                                                           x
 mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
```

**Steps to reproduce:**

`curl -sSL https://install.pi-hole.net | bash`

**Troubleshooting undertaken, and/or other relevant information:**

Found similar report at: https://www.reddit.com/r/pihole/comments/5lnc0r/updateinstall_hanging_at_configuring_dhcpcd5/

I can confirm that killing the process listed in `sudo ps -aux | grep [d]ebconf-apt-progress | awk '{print $2}'` stops the installer. The running processes were:
```
root      xxx 0.1  1.2  14304 12160 pts/0    S+   15:23   0:00 /usr/bin/perl -w /usr/share/debconf/frontend /usr/bin/debconf-apt-progress -- apt-get --yes --no-install-recommends install apt-utils dialog dhcpcd5
root      xxx 0.0  0.5   6888  5440 pts/0    S+   15:23   0:00 /usr/bin/perl -w /usr/bin/debconf-apt-progress -- apt-get --yes --no-install-recommends install apt-utils dialog dhcpcd5
```

Retried with a git checkout. I disabled `dhcpcd5` from `INSTALLER_DEPS` on line: 
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L243
and then the installer worked.

Will investigate further and check the logs to find root cause. Help where to look is appreciated, because I'm not acquainted with your code base.

**Comment by Mcat12** [comment]
Try installing it manually via `apt`. Probably there is some user-intervention required for the install.
