### ISSUE TITLE
Help with some filters (based on source ip address)

### ISSUE THREAD

**Issue by marcosvsmorais** [pi-hole/pi-hole#2755]
Hello!
it's possible to use pi-hole to block an specific source address like 192.168.1.2 and don't block another address like 192.168.2.2 ? that is, to control access based on host ip address (from my local network)

I'm using pi-hole in my local network, but i blocked all hosts of network. And i need to have a whitelist for some hosts.

Thanks for your attention!
Pi-hole is a great project.

**Comment by dschaper** [comment]
Pi-hole is only able to prevent access to FQDN's. Since you do not use DNS to resolve an IP address there is no way for Pi-hole to prevent access to IPs.
