### ISSUE TITLE
Allow bypassing pi-hole for localhost

### ISSUE THREAD

**Issue by oakkitten** [pi-hole/pi-hole#2756]
**In raising this issue, I confirm the following:**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 1

---

**Expected behaviour:**

Devices that don't want to use pi-hole can configure their nameservers to use any public nameservers, which should include the device running pi-hole itself.

**Actual behaviour:**

When starting, pi-hole [overwrites `/etc/resolv.conf`](https://github.com/pi-hole/pi-hole/blob/ba1e94d3d9cf1894e0b5adca3e92738d21897568/advanced/Templates/pihole-FTL.service#L44), so any nameserver configuration that the device had is no longer effective.

**Steps to reproduce:**

Run `# systemctl start pihole-FTL.service`, observe that `dig example.com` uses `127.0.0.1`.

**Troubleshooting undertaken, and/or other relevant information:**

There's an option

> IGNORE_LOCALHOST=no|yes¶
> Should FTL ignore queries coming from the local machine? 

but it dosn't seem to have any effect. I don't really know what it does; in what way does it “ignore” queries?

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by Mcat12** [comment]
The `IGNORE_LOCALHOST` setting turns on/off processing of queries coming from localhost, it does not change network settings.

You can change the default DNS server in `/etc/dhcpcd.conf`.

**Comment by oakkitten** [comment]
not sure this is a feature request, exactly, in the sense that what i'm writing about is not a new functionality, but inflexible and frankly speaking unexpected behavior of pi-hole that disrupts other applications.

also, the ambiguous description of `IGNORE_LOCALHOST` is an issue.

@Mcat12 what does “processing” mean? setting that setting to a `yes` doesn't prevent pi-hole from filtering queries from the localhost, so it's still processing them.

and sure, i can change the *default* dns servers in `/etc/dhcpcd.conf`, the problem is that they aren't used as pi-hole rewrites `/etc/resolv.conf`.

**Comment by Mcat12** [comment]
FTL settings only affect FTL, so when the ignore localhost setting is true, only FTL is affected.
FTL processes queries by recording them and adding them to the stats you see on the web interface. By not processing the query, the query and stats do not get shown on the web interface. The query is still resolved however.

Pi-hole itself does not rewrite `/etc/resolv.conf`, that is done by dhcpcd, which uses the configuration file I mentioned.

**Comment by oakkitten** [comment]
i guess i was wrong about `IGNORE_LOCALHOST`, sorry about that

i was able to (temporarily?) fix the issue of `/etc/resolv.conf` being rewritten when starting pi-hole by commenting out the linked line from `pihole-FTL.service`. i'm pretty sure there's no mention of `127.0.0.1` in my `/etc/dhcpcd.conf`. the code was added in 09886a3f11889f485febcb16bd057a91496fe5ed, not sure why. i still think it's pi-hole...

**Comment by Mcat12** [comment]
Hm, sorry I did a search of the repository for `resolv` and it did not find that instance, and I did not remember that being added. Yes, we can look into that.

**Comment by Mcat12** [comment]
I think we can consider locking the user out of being able to use a different server as a bug. I'll reopen this as a possible bug, as I have been able to use different servers on other systems (it could still be an unrelated network setting that is causing resolvconf to act differently).

**Comment by dschaper** [comment]
Version 5 will not set `/etc/resolv.conf` to any value. FTL will use itself for resolution of local network host names but `resolv.conf` does not need to be 127.0.0.1.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
