### ISSUE TITLE
dns resolver does not run on selected interface but on all available regardles of selection

### ISSUE THREAD

**Issue by wilfredkl** [pi-hole/pi-hole#2759]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

when selecting the only listen on interface eht0 I expect to see it only listen on eth0:53

**Actual behaviour:**

dns resolver listens on every interface in the system

**Steps to reproduce:**

1. install pihole
2. open terminal/connectwith putty
3. type ss -anp |grep :53|grep "LISTEN"
4. see all interfaces listed as bein used by pihole-FTL

additional info, I have 2 pi-hole installations running which both give the same result

**Comment by Mcat12** [comment]
This is the intended behavior. Is there some issue with it? You can always change this behavior via the settings page.

**Comment by colleen-card** [comment]
You should probably try inserting a cheese sandwich into your floppy drive. That fixes everything! 

#AOL Rules!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by wilfredkl** [comment]
I was talking about the settings on the settings page which when changed
reflect to the exact same outcome (pinhole listening on all interfaces)
regardless of which option is selected

**Comment by mwoolweaver** [comment]
this definitely does not happen for me using [v4.3](https://github.com/pi-hole/pi-hole/releases/tag/v4.3)

**Comment by Mcat12** [comment]
You can use the dnsmasq setting `bind-interfaces` to only bind to the selected interfaces. However, the default setting for dnsmasq is to bind to all interfaces. Do you have a reason for wanting to change this? Note that you can add that setting to your install without waiting for Pi-hole to add a setting for it.

> -z, --bind-interfaces
>     On systems which support it, dnsmasq binds the wildcard address, even when it is listening on only some interfaces. It then discards requests that it shouldn't reply to. This has the advantage of working even when interfaces come and go and change address. This option forces dnsmasq to really bind only the interfaces it is listening on. About the only time when this is useful is when running another nameserver (or another instance of dnsmasq) on the same machine. Setting this option also enables multiple instances of dnsmasq which provide DHCP service to run in the same machine.

**Comment by Mcat12** [comment]
NetworkManager sometimes adds this setting automatically:
```
$ cat /etc/dnsmasq.d/network-manager 
# Tell any system-wide dnsmasq instance to make sure to bind to interfaces
# instead of listening on 0.0.0.0
# WARNING: changes to this file will get lost if network-manager is removed.
bind-interfaces
```

**Comment by yubiuser** [comment]
@wilfredkl 
Does the issue still persist with a current version of Pi-hole?
