### ISSUE TITLE
Options for whitelisting all subdomain names for set of domains

### ISSUE THREAD

**Issue by jult** [pi-hole/pi-hole#2760]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`7`

---
**Expected behaviour:**

`I hoped to have either "domain.tld" or "*.domain.tld" be including all subdomains in whitelist.txt`

**Actual behaviour:**

`whitelist.txt only goes on exact names, no option to wildcard or include *all* possible subdomain names`

Can we have wildcard options for whitelist domains in there, please? Either by regex, or simply adding domain.org and domain.com in some txt file etc. (where *.domain.org *.domain.net would then be whitelisted, or removed from gravity.list after the blocklists have been imported, before reloading dnsmasq).

This is, in my opinion, lacking from pi-hole, and I frankly did not expect it wasn't optional to whitelist entire domains.
See also: https://discourse.pi-hole.net/t/wildcard-and-regex-support-for-whitelisting/14538/3

I had to, for example, remove these from gravity.list;
```
a1599.g.akamai.net
a1767.g.akamai.net
a19.g.akamai.net
a1964.g.akamai.net
aksb-a.akamaihd.net
apiskywebbercom-a.akamaihd.net
appnext-a.akamaihd.net
asrv-a.akamaihd.net
blacktri-a.akamaihd.net
canvaspl-a.akamaihd.net
cdn-guile.akamaized.net
cdn2sitescout-a.akamaihd.net
cdncache2-a.akamaihd.net
cdnstats-a.akamaihd.net
contentcache-a.akamaihd.net
contentclick.akamaized.net
couponcp-a.akamaihd.net
downloadandsave-a.akamaihd.net
ds-aksb-a.akamaihd.net
dyn-beacon.akamaized.net
e3694.a.akamaiedge.net
e6913.dscx.akamaiedge.net
fb_servpub-a.akamaihd.net
giantsavings-a.akamaihd.net
greatfind-a.akamaihd.net
inmobisdk-a.akamaihd.net
pxlgnpgecom-a.akamaihd.net
redge-a.akamaihd.net
rvzr-a.akamaihd.net
rvzr2-a.akamaihd.net
sonybivstatic-a.akamaihd.net
speee-ad.akamaized.net
spotxchange-a.akamaihd.net
supersonicads-a.akamaihd.net
zvsuhljiha-a.akamaihd.net
```
and have to do that manually (or using sed and a script everytime pi-hole updates gravity.list).

**Comment by DL6ER** [comment]
> and have to do that manually (or using sed and a script everytime pi-hole updates gravity.list).

You can also request their removal in the original adlist if you think they shouldn't be blocked.

Otherwise, as this is clearly rather a feature request than an actual issue, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.
