### ISSUE TITLE
NXDOMAIN returning for el2.convertkit-mail.com

### ISSUE THREAD

**Issue by astrostl** [pi-hole/pi-hole#2762]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`'nslookup el2.convertkit-mail.com' returns a valid response`

**Actual behaviour:**

`'nslookup el2.convertkit-mail.com' returns "server can't find el2.convertkit-mail.com: NXDOMAIN"`

**Steps to reproduce:**

`'nslookup el2.convertkit-mail.com' from a pi-hole system`

**Troubleshooting undertaken, and/or other relevant information:**

`tried whitelisting from web interface and console, ran thru query logs and tools until concluding that it doesn't seem to be blocklist-related, and contrasted (working as expected) behavior on a non-pi-hole system`

**Comment by dschaper** [comment]
What happens when you run `dig el2.convertkit-mail.com @127.0.0.1` on the Pi-hole device itself? 

Can you provide a debug token as requested by the template?

**Comment by astrostl** [comment]
Thank you for such a prompt reply!

PI-HOLE:
```
; <<>> DiG 9.10.3-P4-Raspbian <<>> el2.convertkit-mail.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39450
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;el2.convertkit-mail.com.	IN	A

;; Query time: 19 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun May 26 23:40:34 CDT 2019
;; MSG SIZE  rcvd: 52
```

NON-PI-HOLE:
```
; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> el2.convertkit-mail.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10312
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;el2.convertkit-mail.com.	IN	A

;; ANSWER SECTION:
el2.convertkit-mail.com. 59	IN	CNAME	web-el2-661907477.us-east-2.elb.amazonaws.com.
web-el2-661907477.us-east-2.elb.amazonaws.com. 59 IN A 3.14.117.39
web-el2-661907477.us-east-2.elb.amazonaws.com. 59 IN A 3.14.99.163

;; Query time: 45 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon May 27 04:41:23 UTC 2019
;; MSG SIZE  rcvd: 140
```

I would prefer to not upload full logs. The console `tail`, at least, is pretty uneventful:

```
May 26 23:43:12 dnsmasq[2627]: query[A] el2.convertkit-mail.com from 127.0.0.1
May 26 23:43:12 dnsmasq[2627]: forwarded el2.convertkit-mail.com to 149.112.112.112
```

**Comment by dschaper** [comment]
Your upstream `149.112.112.112` is responding with the `NXDOMAIN` response. Pi-hole is just relaying that response to you. You'd need to find out why that upstream is reporting the erroneous result.

**Comment by astrostl** [comment]
Interesting - that IP is the secondary for "Quad9 (filtered, DNSSEC)". I get an NXDOMAIN from "Quad9 (unfiltered, no DNSSEC)" AND "OpenDNS (ECS)" AND "Google (ECS)" though, running `pihole restartdns` between each switch, though. Are you able to reproduce yourself?

**Comment by astrostl** [comment]
Output from `dig @149.112.112.112 el2.converkit-mail.com` from the Pi-hole itself:
```
; <<>> DiG 9.10.3-P4-Raspbian <<>> @149.112.112.112 el2.converkit-mail.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40343
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;el2.converkit-mail.com.		IN	A

;; AUTHORITY SECTION:
com.			878	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1558933357 1800 900 604800 86400

;; Query time: 20 msec
;; SERVER: 149.112.112.112#53(149.112.112.112)
;; WHEN: Mon May 27 00:03:23 CDT 2019
;; MSG SIZE  rcvd: 124
```

**Comment by dschaper** [comment]
9.9.9.9 NXDOMAIN
9.9.9.10 NOERROR
9.9.9.11 NXDOMAIN

**Comment by astrostl** [comment]
`9.9.9.10` maps to "Quad9 (unfiltered, no DNSSEC)" so I'm at a loss as to how this continues to cache even after selecting it (and others) then issuing a `pihole restartdns`, but I can confirm from a direct `dig` that it is yielding NOERROR. Will close issue for now and reopen a separate one if I continue to experience cache flushing issues. Thanks for your guidance!
