### ISSUE TITLE
Network overview data can not be removed with Log flush and privacy setting

### ISSUE THREAD

**Issue by thetobby** [pi-hole/pi-hole#2765]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**Issue**
Network overview tab introduced in latest version does not allow for data to be purged or hidden and is unaffected by reboot.

**How familiar are you with the the source code relevant to this issue?:**
2

**Issue**
I expect this is not yet implemented, but is a privacy issue as mac-address,host names and additional data is logged.

**suggested solution**
Enable option to disable function in menu and ensure all relevant data is deleted with flush log option.

**Comment by davekr8** [comment]
Flush (old) hostnames is an issue from my point of view: Can confirm, that flush is not respected for "network overview":

**Comment by DL6ER** [comment]
This has not been implemented so far and is addressed in https://github.com/pi-hole/pi-hole/pull/2769

**Comment by thetobby** [comment]
Great work :) can it also be added to web interface as a button before closing the issue?

**Comment by DL6ER** [comment]
Yes, this will also be added to the web interface. It will, however, depend on this backend command have been merged already.

**Comment by DL6ER** [comment]
@thetobby See https://github.com/pi-hole/AdminLTE/pull/951

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.

**Comment by beerisgood** [comment]
Sadly the UI button doesn't do anything while the "pihole arpflush" command works
