### ISSUE TITLE
bash basic-install.sh - a few minor issues, reporting just in the event anyone would like to improve on it

### ISSUE THREAD

**Issue by rubyFeedback** [pi-hole/pi-hole#2770]
Hello. I am using a slackware system and compile everything from source.

Anyway - the main readme of pi-hole mentions this:

    bash basic-install.sh

There are a few problems that I found:

1) grep: /etc/redhat-release: No such file or directory

I assume the shell script assumes this file to exist; it guessed that it is a rpm
based system, which is incorrect. Either way I would recommend to first
check whether this file exists anyway, before calling grep - on my system
the above grep fails (I do have rpm though)

2)   [i] Checking yum for upgraded packages...basic-install.sh: line 1575: yum: command not found

I do not have "yum" installed so perhaps the shell script could check for the existance.

Not sure if this is worth reporting since it is so minor but better to report than not to report I think; these seem to be easy to fix anyway. :)

**Comment by dschaper** [comment]
Thanks, slackware is not a currently supported platform so that is most likely why you are seeing these issues. If you would like to see slackware become supported then any pull requests with updates to the installer would be helpful for us.
