### ISSUE TITLE
FTL not found v4.3/pihole-FTL-linux-x86_64 404

### ISSUE THREAD

**Issue by patrik72** [pi-hole/pi-hole#2772]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_
1
---

**[BUG | ISSUE] Expected Behaviour:**
BUG
new FTL binary downloads via curl

**[BUG | ISSUE] Actual Behaviour:**
Binary doesn't download and gets a 404.

**[BUG | ISSUE] Steps to reproduce:**
pi@pihole:~$ curl -sSL https://github.com/pi-hole/FTL/releases/download/v4.3/pihole-FTL-linux-x86_64 -o pihole-FTL-linux-x86_64
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: debian 16.04

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Issue was resolved via Discourse. Reopen if this is not the case.
