### ISSUE TITLE
Unknown error whilst loading data - network page

### ISSUE THREAD

**Issue by modem7** [pi-hole/pi-hole#2776]
Note: Unsure if this is in the correct repo. Might be better suited to AdminLTE

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 

`1`

---
**Expected behaviour:**

Expect to see network information

**Actual behaviour:**

Error message: Unknown error whilst loading data

**Steps to reproduce:**

Click on "network"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):** 

`https://tricorder.pi-hole.net/4xotd3ug6f`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
Tried to use both router and DHCP server under "Use Conditional Forwarding"

Current setup: Running pihole on a pi. DHCP server is running under Fedora on a separate server. 

![Capture](https://user-images.githubusercontent.com/4349962/58754569-0c3c0b80-84cb-11e9-8af2-17a03ba67a48.JPG)

**Comment by modem7** [comment]
All resolved. No idea what I did to make everything work however.

**Comment by s-kk** [comment]
OS: Raspbian on Raspberry Pi 3
Using Pi-hole and AdminLTE from official installer script.
DHCP server disabled on Pi-hole

Same issue here while accessing "Network Overview" with Chrome.
Chrome console reported "GET http://pi.hole/admin/api_db.php?network&_=1562032892966     500 (Internal Server Error)"
Error located at jquery.min.js at line 3800 `f.send(a.hasContent && a.data || null)` (Chrome formatted version), and see picture below.
![Debug console](https://imgur.com/a/WuY5gdW)
Log file here: [Pi-hole Log](https://tricorder.pi-hole.net/xqh78seval)
