### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by DonLexos** [pi-hole/pi-hole#278]
I have no idea why this keeps happening to me, but for some reason even rerunning the script doet not always solve this. I doubt I am the only one (could be) but right now the script continues even if the file is not downloaded, resulting in more errors during the way.

Is it possible to check if a file is received or not, and if it is not retry it?

This was a 2.5 update over a clean 2.4 installation, log below:

```
pi@pi-hole:~ $ curl -L install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18474  100 18474    0     0  16182      0  0:00:01  0:00:01 --:--:-- 88392
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.11/24
::: IPv6 will NOT be used.
::: Using Google DNS servers.
:::
::: apt-get update has not been run today. Running now.. done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for toilet... already installed!
:::    Checking for figlet... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services. done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... OK!
:::     Updating repo in /etc/.pihole../fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com  done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin.. done!
:::
::: Installing scripts... done.
:::
::: Installing configs...cp: cannot stat ‘/etc/.pihole/advanced/dnsmasq.conf.original’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/01-pihole.conf’: No such file or directory
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
 done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriting
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Getting adaway.org list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... List updated, transport successful!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... List updated, transport successful!
::: Getting winhelp2002.mvps.org list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 96935 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 87819 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 8 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 9 domains whitelisted!
::: Running blacklist script to update HOSTS file... 0 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!
````

And to be absolutely sure, same pi, right after the above:

```
pi@pi-hole:~ $ dig github.com
; <<>> DiG 9.9.5-9+deb8u5-Raspbian <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3266
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             1       IN      A       192.30.252.130

;; Query time: 45 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Feb 01 15:43:08 CET 2016
;; MSG SIZE  rcvd: 55
```

**Comment by DonLexos** [comment]
As an update, the 2 could not resolve host errors continue even on the 3rd attempt

**Comment by DonLexos** [comment]
4th & 5th attempt (this time after a reboot first) still same errors

**Comment by PromoFaux** [comment]
You don't have much luck as regards to this..! 

This is still something I'm yet to see, even after countless uninstall/reinstalls...

How reliable is your connection? Could you post the results of this please ?http://www.pingtest.net/

**Comment by PromoFaux** [comment]
What I can do is add in a check on the return code of the `git` command, and force the install to abort if it is unable to download..

**Comment by DonLexos** [comment]
I see there is some packet loss, however not sure if that is some (stupid) router issue where it does not accept these kind of connections.

I get a B* with 28 ms ping and 4ms jitter
http://www.pingtest.net/result/138984229.png

**Comment by DonLexos** [comment]
When I run a (Ookla) speedtest I get 205.76 MBit down and 20.20 MBit up.

**Comment by PromoFaux** [comment]
>205.76 MBit down and 20.20 MBit up.

As an aside, everything about that makes me and my 6MBit connection hate you.

**Comment by DonLexos** [comment]
Hahaha .. . well comfort yourself in the fact that even after 6 runs I cannot find github.com when I run the script. (And as a snide remark, even my cellphone connection is higher than 6 Mbit) o:-)

**Comment by DonLexos** [comment]
Downloaded the script, ran it on the pi, no issue at all . . .beats me what this could be.

**Comment by DonLexos** [comment]
Did the 2.5.1 upgrade, through curl failed, running locally failed, did a `dig github.com` prior to updating and it worked. No clue why response to github.com is slow, I got it working and seems I am the only one, so I am going to close this

Wouldnt hurt though to check if the files are indeed downloaded or an error is resolved. A connection problem is not that uncommon and the script runs through regardless.

**Comment by NorthernLoop** [comment]
Many thanks for this. I had the same issue, after I also ran dig github.com and also stopped a massive upload of data the script ran.

Is there a ping timeout on github.com that is a little low?

**Comment by PromoFaux** [comment]
We may have this fixed in the next release with [this commit](https://github.com/pi-hole/pi-hole/commit/4d0b4cfb36f0cf5592449323e9c2bfcc1cb71012) I was finally able to reproduce it, and it appeared to be related to `dnsmasq` being stopped to run the install.

**Comment by DonLexos** [comment]
Oh very glad to hear that. I was curious about the new adblock lists and had to do the install script around 8 times before I was able to connect to github.com and get the files.
