### ISSUE TITLE
FTL not upgrading to 4.3.1

### ISSUE THREAD

**Issue by Gaboros** [pi-hole/pi-hole#2784]
[i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [âś“] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [âś“] Disk space check
  [i] Update local cache of available packages...
[K  [âś“] Update local cache of available packages

  [i] Checking apt-get for upgraded packages...
[K  [âś“] Checking apt-get for upgraded packages... 19 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [i] Checking for apt-utils...
[K  [âś“] Checking for apt-utils
  [i] Checking for dialog...
[K  [âś“] Checking for dialog
  [i] Checking for debconf...
[K  [âś“] Checking for debconf
  [i] Checking for dhcpcd5...
[K  [âś“] Checking for dhcpcd5
  [i] Checking for git...
[K  [âś“] Checking for git
  [i] Checking for iproute2...
[K  [âś“] Checking for iproute2
  [i] Checking for whiptail...
[K  [âś“] Checking for whiptail

  [i] Performing reconfiguration, skipping download of local repos
  [i] Resetting repository within /etc/.pihole......
[K  [âś“] Resetting repository within /etc/.pihole...
  [i] Resetting repository within /var/www/html/admin......
[K  [âś“] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [i] Checking for cron...
[K  [âś“] Checking for cron
  [i] Checking for curl...
[K  [âś“] Checking for curl
  [i] Checking for dnsutils...
[K  [âś“] Checking for dnsutils
  [i] Checking for iputils-ping...
[K  [âś“] Checking for iputils-ping
  [i] Checking for lsof...
[K  [âś“] Checking for lsof
  [i] Checking for netcat...
[K  [âś“] Checking for netcat
  [i] Checking for psmisc...
[K  [âś“] Checking for psmisc
  [i] Checking for sudo...
[K  [âś“] Checking for sudo
  [i] Checking for unzip...
[K  [âś“] Checking for unzip
  [i] Checking for wget...
[K  [âś“] Checking for wget
  [i] Checking for idn2...
[K  [âś“] Checking for idn2
  [i] Checking for sqlite3...
[K  [âś“] Checking for sqlite3
  [i] Checking for libcap2-bin...
[K  [âś“] Checking for libcap2-bin
  [i] Checking for dns-root-data...
[K  [âś“] Checking for dns-root-data
  [i] Checking for resolvconf...
[K  [âś“] Checking for resolvconf
  [i] Checking for libcap2...
[K  [âś“] Checking for libcap2
  [i] Checking for lighttpd...
[K  [i] Checking for lighttpd (will be installed)
  [i] Checking for php7.2-common...
[K  [âś“] Checking for php7.2-common
  [i] Checking for php7.2-cgi...
[K  [âś“] Checking for php7.2-cgi
  [i] Checking for php7.2-sqlite3...
[K  [âś“] Checking for php7.2-sqlite3

  Unable to complete update, please contact Pi-hole Support

**Comment by Gaboros** [comment]
> Run `sudo apt update` and see if there are any errors reported.

Did it. Nothing :( 
Not even "curl -sSL https://install.pi-hole.net | bash" updates it.

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for libcap2
  [i] Checking for lighttpd (will be installed)
  [✓] Checking for php7.2-common
  [✓] Checking for php7.2-cgi
  [✓] Checking for php7.2-sqlite3

  Unable to complete update, please contact Pi-hole Support

**Comment by dschaper** [comment]
What is the exact output from `sudo apt update` please?

**Comment by Gaboros** [comment]
Hit:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://dl.google.com/linux/chrome/deb stable Release
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.

**Comment by dschaper** [comment]
Thanks, and `sudo apt-cache status lighttpd`?

**Comment by Gaboros** [comment]
Package: lighttpd
Architecture: amd64
Version: 1.4.45-1ubuntu3
Priority: optional
Section: universe/web
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian lighttpd maintainers <pkg-lighttpd-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 956
Provides: httpd, httpd-cgi
Depends: libattr1 (>= 1:2.4.46-8), libbz2-1.0, libc6 (>= 2.25), libgamin0 | libfam0, libpcre3, libssl1.1 (>= 1.1.0), zlib1g (>= 1:1.1.4), mime-support, lsb-base (>= 3.0-6)
Recommends: spawn-fcgi
Suggests: openssl, rrdtool, php5-cgi, apache2-utils, lighttpd-doc, ufw
Filename: pool/universe/l/lighttpd/lighttpd_1.4.45-1ubuntu3_amd64.deb
Size: 275916
MD5sum: aa16b64140528d09ba45e09e6888844b
SHA1: ddf439e86a350cf1eebd9a624ce56c7f8de5f1db
SHA256: e8946ec245392dd432f982d675907e796fcb2c9f3c2cac6a2a4023adcd37d8c8
Homepage: http://lighttpd.net/
Description-en: fast webserver with minimal memory footprint
 lighttpd is a small webserver and fast webserver developed with
 security in mind and a lot of features.
 It has support for
   * CGI, FastCGI and SSI
   * virtual hosts
   * URL rewriting
   * authentication (plain files, htpasswd, LDAP)
   * transparent content compression
   * conditional configuration
   * HTTP proxying
 and configuration is straight-forward and easy.
Description-md5: 3cbd5b2dae1802558158d8c2aae494ab

**Comment by dschaper** [comment]
Okay and `sudo apt install lighttpd`?

**Comment by Gaboros** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lighttpd : Depends: libssl1.1 (>= 1.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Gaboros** [comment]
sudo apt install libssl1.1=1.1.0g-2ubuntu4.3
sudo apt install lighttpd

It's did the trick! Thank You very much! :)
