### ISSUE TITLE
Error Updating - Segmentation Fault

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [pi-hole/pi-hole#2785]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**

`Update of pi hole`

**Actual behaviour:**

- log in via ssh
- run pihole -up
- error: 
```
/etc/.pihole/automated install/basic-install.sh: line 257:  1042 Segmentation fault      ${PKG_MANAGER} install --dry-run iproute2 > /dev/null 2>&1
  
[i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1

/etc/.pihole/automated install/basic-install.sh: line 257:  1051 Segmentation fault      ${PKG_MANAGER} install --dry-run ${phpVer}-sqlite3 > /dev/null 2>&1
  
[i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"
  Unable to complete update, please contact Pi-hole Support
```

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`7oppqrc0rh`

**Troubleshooting undertaken, and/or other relevant information:**
- ran `sudo apt-get update` and received the following: `Segmentation faultsts... 0%`
- ran `sudo rm /var/lib/apt/lists/* -vf` to remove lists

- Tried all steps again and same issues persist.

**Comment by dschaper** [comment]
That's an operating system error and not one that is solvable by Pi-hole. You may get better support on the Raspbian forums to see what is the cause of the segmentation fault.

**Comment by PromoFaux** [comment]
This looks to be an issue with the Raspberry Pi / OS rather than Pi-hole specific. Though it strongly suggests to me that your SD card is corrupt. I would try reflashing the SD card or buying a new card and trying again.

Is your PSU up to scratch? Power supplies that aren't rated for RPis tend to lead to SD card corruptions....
