### ISSUE TITLE
Installation Script Pipes curl To bash

### ISSUE THREAD

**Issue by bambams** [pi-hole/pi-hole#2786]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

`The installation script does not download code from the Web to execute.`

**Actual behaviour:**

    The installation script downloads code from the Web and executes it if run as non-root
    on a system that supports sudo.

    The readme explains that piping curl to bash is controversial, and offers explanations for
    other methods. Yet the script that you can download and review itself pipes curl to bash if
    you execute the script without root.

    Not only is this a waste of resources because the script has already been downloaded,
    and is being executed, but it defeats the purpose of instructing mindful users to do code
    review when the code itself will download potentially different code if the user isn't
    careful.

**Steps to reproduce:**

`Execute the installation script as non-root.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`N/A`

**Troubleshooting undertaken, and/or other relevant information:**

`I see no reason why the script cannot just execute itself with sudo ($0 or something similar).`

**Comment by Mcat12** [comment]
> I see no reason why the script cannot just execute itself with sudo ($0 or something similar).

As the script is piped to bash, there is no way to have it call itself (`$0`, `$@`, and `$BASH_SOURCE` are unusable/empty). This is the main blocker for removing this hack.

I have been experimenting, and I may have a solution. I will make a PR.

**Comment by dschaper** [comment]
I wrote the hack for the script. Here are my thoughts:

It's an ugly ugly hack. It's not something that I expected to remain as it's an ugly ugly hack. To be honest I'm surprised no one has raised the issue before. I've had some thoughts on how to address this, and pretty much every avenue ends up in a major rewrite of the script. I don't think we can get around it now, the installer has been quite a mess for a long time and the two shell hackers for the project are now one shell hacker for the project and to be honest again I just haven't had time to sit down and work something out. I've got some inspiration from get.docker.com and prefixing any call that needs to be elevated to `sudo` and run without needing the additional privs for calls that don't need it. 

So to sum, I don't like it either and it's been on the board to change it for a long time. I don't think calling the entire script as `sudo` is the right solution either. Mcat basically points out why it's there and it's because of the curl to bash. I think we can do better.

**Comment by bambams** [comment]
If the user did pipe curl to bash then they probably won't care if you do it again. The download is still a bit wasteful, but it's less of a concern because the weight of the script is tiny. An imperfect solution could be checking if there is a script that you can re-execute (i.e., $0), and if so doing that instead. If not, assume it was piped and that the user is willing to tolerate that. That's one half-solution.

Another option may be to just `sudo` the commands within the script that require `sudo`. At least a default configuration of sudo should only prompt once during a session for the password and will not need to prompt again unless enough time passes between commands. Odds are if the user is already root then `sudo` will never prompt and will just basically do nothing. So that's another half-solution that could work without needing to download and pipe.

Another option may be to have the script itself write a script to a temporary file that actually does the work, and then the root check can be done to execute that tmpfile script. But again, in that case, you could probably just always `sudo` that temp file instead of the check and let sudo handle that. That too eliminates the extra download and curl pipe. You'd just need to seek out the APIs that can secure the file from other users/processes before trusting it so that it doesn't introduce a sudo vulnerability. Something like `cat <<EOF` to write the file from within the host script. Hopefully I've conveyed that idea sufficiently. I'm not sure if there are platform limitations with regards to securing the temp file though. That may limit portability, which I'm sure is a concern.

But yeah, I'm sure there are many ways to solve the problem. It's just a matter of who has the time to actually implement one that works sufficient.

Thanks for considering this issue.

**Comment by mmotti** [comment]
I had no idea until now just how much is actually checked and processed during the Pi-hole install. 

I did have a quick look through `get.docker.com` as @dschaper mentioned he had some inspiration from it.

It would be quite straight forward to elevate commands that require root - The only issue really being the time taken to go through the massive install script and determine which commands require root and which don't.

We could use something like `$elev_sh` to prefix commands known to require root.

Example command: `touch /etc/test.delete`

- Script run as root --> No elevation needed -->` elev_sh='sc -c'`
`$elev_sh 'touch /etc/test.delete'` --> `sc -c 'touch /etc/test.delete'`
- Script NOT run as root --> sudo command available --> `elev_sh='sudo -E sh -c'`
`$elev_sh 'touch /etc/test.delete'` --> `sudo -E sh -c 'touch /etc/test.delete'`
- Script NOT run as root --> sudo not available, but su is available --> `elev_sh='su -c'`
`$elev_sh 'touch /etc/test.delete'` --> `su -c 'touch /etc/test.delete'`

**Example Script - Launched without root**
![Non-root](https://i.imgur.com/3vi4aUl.jpg)

```
#!/usr/bin/env bash
set -e

# COL TABLE
if [[ -t 1 ]] && [[ $(tput colors) -ge 8 ]]; then
  # Bold and underline may not show up on all clients
  # If something MUST be emphasised, use both
  COL_BOLD='\033[1m'
  COL_ULINE='\033[4m'

  COL_NC='\033[0m'
  COL_GRAY='\033[90m'
  COL_RED='\033[91m'
  COL_GREEN='\033[32m'
  COL_YELLOW='\033[33m'
  COL_BLUE='\033[94m'
  COL_PURPLE='\033[95m'
  COL_CYAN='\033[96m'

  TICK="[${COL_GREEN}✓${COL_NC}]"
  CROSS="[${COL_RED}✗${COL_NC}]"
  WARN="[${COL_YELLOW}w${COL_NC}]"
fi

# Functions
show_ascii_berry() {
  # A simple function that just echoes out our logo in ASCII format
  # This lets users know that it is a Pi-hole, LLC product
 cat >&2 <<-'EOF'
     ____  _       _           _
    |  _ \(_)     | |__   ___ | | ___
    | |_) | |_____| '_ \ / _ \| |/ _ \
    |  __/| |_____| | | | (_) | |  __/
    |_|   |_|     |_| |_|\___/|_|\___|

EOF

  echo -e "
        ${COL_GREEN}.;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 ${COL_RED}.. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.${COL_NC}


"
}

function commandExists() {
  command -v "$1" > /dev/null 2>&1
}

# Output Pi-hole berry
show_ascii_berry

# Check whether user is root
echo '[i] Checking for root privilidges'
if [[ $(id -u) -eq 0 ]]; then
  # User is root
  echo -e "$TICK Root privilidges detected"
  elev_sh='sh -c'
else
  echo -e "$WARN Script launched without root privilidges"
  # Determine method of elevation
  if commandExists sudo; then
    echo -e "$TICK ${COL_BOLD}sudo${COL_NC} will be used for commands requiring elevation"
    elev_sh='sudo -E sh -c'
  elif commandExists su; then
    echo -e "$TICK {$COL_BOLD}su${COL_NC} will be used for commands requiring elevation"
    elev_sh='su -c'
  else
    echo -e "$CROSS Unable to obtain root privilidges through ${COL_BOLD}sudo${COL_NC} or ${COL_BOLD}su${COL_NC}"
    exit 1
  fi
fi

# Test of root execution

test_file='/etc/test.delete'

if $elev_sh "touch ${test_file}"; then
    echo -e "$TICK elevated touch command completed successfully"
else
  echo -e "$CROSS elevated touch command failed"
fi

if $elev_sh "rm -f ${test_file}"; then
  echo -e "$TICK elevated rm -f command completed successfully"
else
  echo -e "$CROSS elevated rm -f command failed"
fi

exit 0
```

**Comment by Mcat12** [comment]
We require sudo in other places, so we can limit the cases to where sudo is or is not installed.

We also don't want to have to quote every command that we elevate. This may work better:
- User is root, sudo not required:
  ```
  SUDO=""

  $SUDO whoami
  ```
- User is not root, sudo is required:
  ```
  SUDO="sudo"

  $SUDO whoami
  ```

**Comment by dschaper** [comment]
>We also don't want to have to quote every command that we elevate.

Is there a technical reason for that, or just a stylistic preference?

**Comment by Mcat12** [comment]
The two main reasons are
- we may have to do extra escaping
- syntax highlighting is lost

Before:
![image](https://user-images.githubusercontent.com/4417660/59476376-3c59a780-8e05-11e9-9af5-fdbd0351180c.png)

After:
![image](https://user-images.githubusercontent.com/4417660/59476387-48de0000-8e05-11e9-8372-c0ca4f41a363.png)

**Comment by Mcat12** [comment]
Also, as seen in the above example, we would probably lose the ability to do `return` in the command, as it is being executed in a new shell.

**Comment by dschaper** [comment]
Should still be able to run `${SUDO} "git clone -q --depth 20 ${remoteRepo} ${directory} &> /dev/null" || return $?` though, we just want to get the value of the command if it fails, and that doesn't need to be elevated with the rest of the call.

**Comment by dschaper** [comment]
If it's executing in a subshell then it may actually be beneficial as all the redirect to `/dev/null` could be eliminated, but I haven't checked that to see if it is true.

**Comment by Mcat12** [comment]
In that case, might be ok ¯\\\_(ツ)\_/¯

Is there any reason to use `SUDO="sudo -E sh -c"` over `SUDO=sudo`?

**Comment by dschaper** [comment]
Yes, the environment preservation. Take a look at `printenv` vs `sudo printenv` vs `sudo -E printenv`.

**Comment by Mcat12** [comment]
Ok, then we can use `sudo -E` instead of `sudo -E sh -c`?

**Comment by dschaper** [comment]
Why? The latter is how docker does it and considering the magnitude and scope of the platforms they support I'd go with something someone else has already tested and put through the process.

**Comment by Mcat12** [comment]
I'm just trying to find out why `sh -c` should be used. I will check their repo to see if it's been explained.

**Comment by Mcat12** [comment]
The `sh -c` has been there since the beginning of the repo, but it would still be good if we can find out why it should be used instead of blindly copying its usage.

**Comment by Mcat12** [comment]
Command redirection seems to be the main reason:
https://serverfault.com/a/946907

The shell processes the redirect before `sudo` is executed, which might cause permission errors.

**Comment by mmotti** [comment]
Yes it would appear command redirection doesn't work properly when elevated with sudo.

I had this kind of issue when I was first starting out with bash; I couldn't understand why when trying to clear a text file `sudo > /etc/pihole/gravity.list` would still fail with "Permission Denied". The only quick way around it I could find was `sudo bash -c '> /etc/pihole/gravity.list'`

@dschaper I think the redirects to `/dev/null` may still be necessary, unless I am misinterpreting what you are saying.

Example:

```
pi@raspberrypi:~ $ sudo -E sh -c 'head -n10 /etc/pihole/gravity.list | tee /etc/pihole/gravity.list.2'
0.0.0.0
0.nextyourcontent.com
0.r.msn.com
0.start.bz
000.0x1f4b0.com
000.gaysexe.free.fr
0000mps.webpreview.dsl.net
0001.2waky.com
000dom.revenuedirect.com
000free.us
```

**Comment by bambams** [comment]
Correct.

     sudo some command >file.txt

The `>file.txt` part is processed entirely by the shell (never seen by `sudo`). When the shell `fork()`s it would open `file.txt` as `STDOUT` before `exec`ing `sudo`, and as far as `sudo` is concerned stdout is just a file handle (it wouldn't directly know which file). `sudo` would inherit the file handle. I'm not sure how the kernel would treat it permission-wise... Presumably `sudo` would totally be able to write to the file, but the shell is probably failing to even open it and never actually executing `sudo`.

And neither `sudo` nor shells swallow stderr implicitly so you'll still need to redirect or pipe any output you don't want appearing to the user.
