### ISSUE TITLE
Install Directory is hardcoded in a few places in 

### ISSUE THREAD

**Issue by zalnasser** [pi-hole/pi-hole#2787]
**In raising this issue, I confirm the following:*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

Modifying the `PI_HOLE_INSTALL_DIR` in `basic-install.sh` should install all relevant files in the specified directory, instead of the default `/opt/pihole`

**Actual behaviour:**

A few lines in the `basic-install.sh` are hard coded to `/opt/local` and therefore those commands fail, causing the script to exit.

**Steps to reproduce:**

Change the `PI_HOLE_INSTALL_DIR`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Installer error, so `pihole` does not run with this bug.

**Troubleshooting undertaken, and/or other relevant information:**

Replaced the hard-coded path with the bash variable. However this causes issues with `gravity.sh`. Currently working on updates at https://github.com/zalnasser/pi-hole/tree/master

**Comment by zalnasser** [comment]
I've submitted the following PR to address this: https://github.com/pi-hole/pi-hole/pull/2788

**Comment by Mcat12** [comment]
There are no occurrences of `/opt/local` in the codebase. We don't currently support modifying the installer or install location anyways, so this is a feature request and not a bug.

**Comment by zalnasser** [comment]
Thank you, I fixed that, I meant `/opt/pihole`.

I did not realize this wasn't supported, I'm happy to submit this as a feature request then. Does this issue need to be closed?

**Comment by Mcat12** [comment]
You can open a feature request on [Discourse](https://discourse.pi-hole.net/c/feature-requests), if one does not already exist. You can reference this issue if you want from there, but discussion should continue over there. This issue can be closed.
