### ISSUE TITLE
Can't access admin interface: Returns 503 Service unavailable

### ISSUE THREAD

**Issue by ZethJack** [pi-hole/pi-hole#2789]
**In raising this issue, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Navigating to <pihole's IP>/admin opens up web interface`

**Actual behaviour:**

`When trying to open the web interface, the page returns error 503: Service not available`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/rw2ckq3khm`

**Troubleshooting undertaken, and/or other relevant information:**

```
  current version
  Pi-hole version is v4.3 (Latest: v4.3)
  AdminLTE version is v4.3 (Latest: v4.3)
  FTL version is v4.3.1 (Latest: v4.3.1)

```

**Comment by technicalpyro** [comment]
Looks to be an issue with PHP on your install please attempt `pihole -r` and select `repair`

**Comment by ZethJack** [comment]
Didn't work sadly. I ended just wiping the drive clean and reinstalling the whole thing from scratch. Probably overkill, but at least now it works just fine.

**Comment by Starhowl** [comment]
This is what fixed it for me:
`sudo apt install --reinstall php7.3-cgi php7.3-cli php7.3-common php7.3-intl php7.3-json php7.3-opcache php7.3-readline php7.3-sqlite3`
