### ISSUE TITLE
Prevent tracking from CDN servers

### ISSUE THREAD

**Issue by eddywebs** [pi-hole/pi-hole#279]
It would be nice to serve common javascript libraries using pi-hole for faster page loads and prevent cdn tracking >> https://github.com/Synzvato/decentraleyes
##

**Comment by PromoFaux** [comment]
Hey, thanks for the link! We'll be sure to take a look into it. At the moment we're focusing on stability before adding in new features, but this certainly looks insteresting

**Comment by DonLexos** [comment]
Would be awesome if the pi can intercept these regardless of a browser extension. Like the idea!

**Comment by jacobsalmela** [comment]
Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/prevent-tracking-from-cdn-servers/551) so this feature is votable.
