### ISSUE TITLE
Uninstalling and re-installing Pi-hole can lead to Error 403 (Forbidden) - Web admin panel

### ISSUE THREAD

**Issue by mmotti** [pi-hole/pi-hole#2791]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

Uninstall Pi-hole, and reinstall, the web admin area should accessible

**Actual behaviour:**

After re-install, the web admin area will not allow access. Error 403 - Unauthorized.

**Steps to reproduce:**

`pihole uninstall` and choose the option to remove all dependencies
Try to re-install and access the web / admin

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

Tried re-installing several times, switching branches, `pihole -r` for repair and reconfigure, all to no avail. 

Ended up re-imaging Raspbian and the fresh install seemed to do the trick. My Pi is now working as expected so unfortunately I can't give you further debug information at this time.

I am reporting this as I have noticed someone on Reddit also had the same experience after having tried to re-install Pi-hole.

On the dev branch, in case that makes any differences to the install / uninstall process.

**Comment by nick149** [comment]
So I had this problem too, somehow nginx got enabled and put on port 80, after changing the port in nginx config file, everything returned to normal.

**Comment by Extarys** [comment]
I just had the same issue. Nginx took over port 80. I had to reflash hassbian and reinstall the Hole.
No idea what caused this.

**Comment by Mcat12** [comment]
Fixed by #2808, but in the mean time, use:
```
sudo apt purge lighttpd
pihole -r
```

**Comment by jcw** [comment]
I think my hiccups are related: I run Lighttpd on a different port, but every time I update Pi-hole, I need to edit `/etc/lighttpd/lighttpd.conf`, edit my value back in iso 80, and restart lighttpd. Without this change, I can't access the admin pages. It's no big deal now that I've figured it out, but it'd be nice if `phole -up` would stop reverting my port choice (port 80 is not an option for me since I run another reverse proxy on the same box).

FWIW, I just completed an update to 4.3.1 and it happened again.

**Comment by dschaper** [comment]
You may note that `/etc/lighttpd/lighttpd.conf` that is supplied by Pi-hole has a rather large notice at the top that warns users that any changes will be reverted. We're working on no longer needing to depend on lighttpd but until that is ready for release (not any time soon) the requirements are as stated.

**Comment by jcw** [comment]
Understood, thanks - I really have no choice, given that Pi-hole is running on the same system as my main outward-facing webserver. And as I said, no big deal - well worth the minor incvonvenience.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
