### ISSUE TITLE
Installer fails on fresh debian 9.7 install

### ISSUE THREAD

**Issue by DanielHeath** [pi-hole/pi-hole#2798]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0

---
**Expected behaviour:**

Running the installer completes and finishes with `exit(0)`

**Actual behaviour:**

Running the installer fails with exit code `100` after `checking for whiptail`

**Steps to reproduce:**

Download debian 9.7 from osboxes.org
Launch in virtualbox.
Open a terminal, wait for first-run apt to complete (~10 minutes)
run `su` and then `apt install curl`
run `curl -sSL https://install.pi-hole.net | bash﻿`

**Comment by technicalpyro** [comment]
A modified system image such as those found on that website is missing packages we expect to be installed on basic OS's

run `curl -sSL https://install.pi-hole.net | bash﻿ -x` and let us know the last few lines of the output as that will tell exactly which package we expect is missing and what package you will need to manually install

**Comment by DanielHeath** [comment]
Package `dialog` has no installation candidate, unable to locate package `dhcpd5`, and `liberror-perl` is not available, but is referred to by another package (`git`), so that can't be installed, either.

**Comment by DanielHeath** [comment]
Argh, they have `stretch-updates` and `stretch-backports` but not `stretch` in their `/etc/apt/sources.list`. WTF. Sorry to bother you.

**Comment by technicalpyro** [comment]
its OK we're here to help if this is resolved feel free to close it

**Comment by DanielHeath** [comment]
Thanks so much :heart:
