### ISSUE TITLE
CORS failed when using Reverse Proxy after pi-hole update

### ISSUE THREAD

**Issue by walterwhite81** [pi-hole/pi-hole#2799]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---
**Expected behaviour:**

`{Pre-update CORS setting in auth.php}`

**Actual behaviour:**

`{When using a reverse proxy with NGINX Cors fails, to fix this the known host has to be added to /var/www/html/admin/scripts/pi-hole/php/auth.php}`

**Steps to reproduce:**

`{Run NGINX as reverse proxy and reverse pi-hole through it.}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`Manually adding the host after each update`

**Comment by Mcat12** [comment]
Editing the source code is not supported.

Add the `VIRTUAL_HOST` variable via `/etc/lighttpd/external.conf` instead:
https://discourse.pi-hole.net/t/white-listed-site-does-not-open/11517/7?u=mcat12
