### ISSUE TITLE
Wrong time in logged data

### ISSUE THREAD

**Issue by cxt666** [pi-hole/pi-hole#2805]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

The logs entries should show the local time CEST (UTC+2), as set on the system (in "Recent Queries` for example)

**Actual behaviour:**

All log entries show UTC time instead local time

**Steps to reproduce:**

Just use it, no addtional steps neccessary for me...

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/sk5ccdtlnj

**Troubleshooting undertaken, and/or other relevant information:**

- installed again from scratch (new Raspbian Install & new pihole install
- removed `/etc/pihole/pihole-FTL.db` as it was mentioned somewhere that this should be fixed in 4.0
- disabled ntp
- changing system time to BST --> same result, Logs in UTC

**Comment by DL6ER** [comment]
Just for clarification: Are we talking about the log files on the disk (`/var/log/...`) or the queries shown on the web interface (`http://pi.hole/admin`)?

**Comment by cxt666** [comment]
> Just for clarification: Are we talking about the log files on the disk (`/var/log/...`) or the queries shown on the web interface (`http://pi.hole/admin`)?

The logs on the web interface; "Recent Queries" (http://pi.hole/admin/queries.php). The stuff in the system ( /var/log/pihole.log  for example) has the correct local system timestamps (verified just now).

**Comment by Mcat12** [comment]
Your browser or operating system is supplying an incorrect time. The web interface uses the timezone of the browser to show the dates.

**Comment by cxt666** [comment]
Yep, seems to be the browser; With Chromium, suddenly every time is displayed correctly.

Thank you!
