### ISSUE TITLE
Trouble with static ipv6

### ISSUE THREAD

**Issue by JaredWith1r** [pi-hole/pi-hole#281]
After an exhaustive search, I can't seem to get the ipv6 address of my Pi to stay static. Every reinstall is giving me a new address, which I have to update in the router.

Any suggestions? Doesn't seem like a difficult problem, just a lack of understanding. Thanks!

**Comment by dschaper** [comment]
It sounds like you may not have a globally routable IPv6 address for your Pi-hole. Does the first part of the address stay the same, or does it change everytime? If you could post up the leftmost 1111:2222 part of the addresses you are getting I can try and see where the issue may be located.

**Comment by JaredWith1r** [comment]
Okay so I'm now noticing that on some installs, Pi-Hole will give me the ipv6 Link address and I wouldn't have a global address (maybe?). This is still the same, but on this install, I now have a Global address starting with 2601:14a:...

Any of this make sense? Thanks!

**Comment by dschaper** [comment]
DHCPv6 can be interesting to troubleshoot, and a lot of it depends on how the ISP is implementing IPv6. There's a bunch of different methods from Native, to Split Stack and Tunneled. The way Pi-hole tries to determine which IPv6 is assigned is to do a `route` command to the IPv6 address of the Google DNS servers since they are most likely always going to be available. From there we can determine what interface is allowing IPv6 traffic out to the routable world. Also, different ISP's assign different amounts of addresses for use in a customers local network, and on top of that, your router has a bit of a say on how many addresses it allows for use on the internal network. 

So, it can get to be pretty complicated when you take in all the variables of an IPv6 implementation, but hopefully once you are assigned a global, you'll hold on to that global... 

From what I have seen though, if the Pi is assigned a local or private address, then it probably doesn't have a route to the Internet and you shouldn't be getting ad traffic on the IPv6 protocol stack. One site to check from a browser is `http://ip6.me`. You probably could even visit that site from the Pi over SSH if you are using `elinks` or another command line browser.

**Comment by jacobsalmela** [comment]
@dschaper just beat to me it.  He pretty much wrote everything I was going to say.  It's also interesting because you can have so many different IPv6 addresses on an interface.

**Comment by JaredWith1r** [comment]
That is all very interesting and equally confusing. I have an ASUS RT-AC66U that has quite a lot of options that I don't understand, so I tried to setup my IPv6 as simply as I could. Whatever address I can get out of the Rpi goes into the IPv6 dns setting, and OpenDNS is the backup 2 and 3.

It seems to be working with the shorter Link address which hasn't changed over the last 1 or 2 fresh installs of Pi-Hole, so I'm not too worried. Setting up static ipv4 was so much simpler, I was hoping there was an easy way for this too.

And for what it's worth, `http://ip6.me` DOES show me a full IPv6 address, which I take to mean I have that service coming into my modem. Thanks for the help, as always!

**Comment by dschaper** [comment]
Yep, if `ip6.me` shows an address, then you at least have IPv6 to the router. Some ISP's only assign a single address (a /128) that works just for the router, but others will give you a block of IP's that you can assign to your internal network. (Somewhere between a /56 block and a /60 block). If your ISP is really nice, they wont change the IPv6 information even if your IPv4 changes...

IPv6 is kind of a different animal, and it can be "interesting" to configure, the stock firmware on the router adds to the mix... We're working on ways to simplify the IPv6 configuration, but with so many different models of routers out there it's going to take a bit of time. Advertising IPv6 DNS servers to the clients tends to be a hidden feature on a lot of stock router firmware. 

But it's good that you're getting a global address from `ip6.me`, did you test from a client machine, or did you test directly from the RasPi itself? If you can do both you should see two different IPv6 addresses. You may have to install `elinks` or `lynx` on the RasPi to get a CLI browser...

**Comment by JaredWith1r** [comment]
I checked `ip6.me` from both the RPi directly (well, through XRDP) as well as from my desktop PC. The last 4 groups (bits? bytes? whatever) are different between both clients, first 4 are the same.

FWIW, my IPv6 router settings are Native with DHCP-PD, Stateless LAN settings, Router Advertisement enabled. I don't know what most of that means with regard to IPv6, so it may not really be helpful information.

**Comment by dschaper** [comment]
Good, that all means that your ISP is providing a Native IPv6 implementation. Stateless or SLAAC lets the individual clients do most of the configuration by themselves, and RA's just tell the individual clients where to get their ways out to the 'net. 

So, at this point, how is the install? What is working and what isn't working? What do we need to work on?

(Also, does your router have the ability to send custom DHCP Options? Or to send the IPv6 DNS settings?)

**Comment by JaredWith1r** [comment]
-Send custom DHCP options? I'm not too sure how to identify that. Disabling DHCP-PD lets me adjust the LAN address, disabling Stateless lets me adjust the Pool Start/Stop addresses (I assume to farm out address to the clients within a range)

-I have 3 IPv6 DNS server options in the router, so I set the first to my Pi-Hole inet6 Link address, the other 2 to OpenDNS. 

My original reason for posting is that whenever I go to install pi-hole, it recognizes my static IPv4, but it seems to give me a new IPv6, sometimes displaying a Global address and sometimes displaying a Link address when it is completing setup.

Other than that, the install is good, I'm at 2.5.1 and I think the biggest things I am looking forward to are:
-Historical data logging
-Commit updates rather than recurling

On the same note as historical data logging, it would be interesting to see what percentage each domain is of the total blocked list. So main.exoclick accounted for 15% of the ads blocked, stuff like that.

I appreciate all of the help!

**Comment by dschaper** [comment]
I'd leave the DHCP options set with the defaults, that lets the end devices get most of the configuration themselves, and for me on my personal configuration, I just use the global IPv6 address that comes up on the RasPi, that should be pretty stable, using SLAAC it shouldn't do much changing. 

We're always working on updates and new features, and as soon as they are stable, we'll release them!

Thanks for using the Pi-hole, and just give us a shout if you run into any further problems. Is it okay to close this issue for now? We can re-open if you run into more problems...

**Comment by JaredWith1r** [comment]
Absolutely! I'll close it out now, thanks. It seems that this isn't so much a problem with my setup as much as a low understanding of IPv6, which I'm totally okay with.

Thanks again, let me know if there is any way to help!
