### ISSUE TITLE
Error in lightttp.conf

### ISSUE THREAD

**Issue by CordlessWool** [pi-hole/pi-hole#2815]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Open Admin interface

**Actual behaviour:**

I did some research write now, but I got able to fix the issue. Where I end is that the lighttp do not run because of  `source: /etc/lighttpd/lighttpd.conf line: 53 pos: 14 parser failed somehow near here: (EOL) ` that is
`source: /etc/lighttpd/lighttpd.conf line: 53 pos: 14 parser failed somehow near here: (EOL) `

**Steps to reproduce:**

Installing pihole with `curl -sSL https://install.pi-hole.net | bash` on raspbian lite latest version (25-06-2019). lighttpd version is lighttpd/1.4.53 (ssl) - a light and fast webserver

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
What OS are you installing on?

**Comment by CordlessWool** [comment]
raspbian lite

**Comment by dschaper** [comment]
Which release? Jessie, Stretch or Buster?

**Comment by CordlessWool** [comment]
buster. I downloaded and installed it today

**Comment by dschaper** [comment]
Buster is not supported, please see the pinned issues at the top of the page that cover this.
