### ISSUE TITLE
 How to extract all the data from Pi-hole?

### ISSUE THREAD

**Issue by deveshsnair9** [pi-hole/pi-hole#2818]
Hi I'm a 4th year B.tech student and using Pi-hole for one of my projects I would like to join the developer community of this project and gain some technical knowledge and skill about the project.....

I would like to know how to extract long term data out of the pi-hole software so that i can make a report on this project.
![Screenshot_2019-06-28 Pi-hole Admin Console(4)](https://user-images.githubusercontent.com/45566616/60316977-953f4900-998a-11e9-8d1e-aaf3bc33bce1.png)

**Comment by Mcat12** [comment]
There is some documentation on the database here: https://docs.pi-hole.net/ftldns/database/

**Comment by JamoBox** [comment]
Obviously depends on what format you want it in.
You can dump the entire SQLite database with:
```
sqlite3 /etc/pihole/pihole-FTL.db
sqlite> .output pidump.sql
sqlite> .dump
```

If you just want specific tables etc, or want it as CSV just google the SQLite commands to do whatever it is you are after.
