### ISSUE TITLE
Display Pi-hole IP at end of installer

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#282]
This is already shown to the user as a `whiptail` dialog, but once they close it, they might forget it.  So it would be nice to show a message so the user knows what to set their DNS to without having to scroll back to the start of the log

**Comment by alpha1125** [comment]
here's a useful tidbit... if I get around to it, I'll add it to the install script, and submit a pull request.

the shell command, to grab the current ip4 address is:
`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

**Comment by dschaper** [comment]
Thanks for the submission, can you expand this a little for supporting installations that use interfaces other than `eth0`? We have users that have multiple interfaces on their RasPi's and also users that are on platforms other than Raspberries, like VPS.

**Comment by PromoFaux** [comment]
We actually already have the IP (both 4 and 6) in variables at this point, so we just need to echo them out after `displayFinalMessage()` is called

Simples.

**Comment by PromoFaux** [comment]
So after [this line](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L576) we just need something like:

'''BASH
echo "::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:"
echo ":::     $IPv4addr"
echo ":::     $piholeIPv6"
echo ":::"
echo "::: If you set a new IP address, you should restart the Pi."
echo "::: "
echo "::: The install log is in /etc/pihole.log"
'''

(Which is exactly what displayFinalMessage() shows in a whiptail)

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/12866761/b9b0b564-ccd1-11e5-8280-1e7ebf33d376.png)

**Comment by PromoFaux** [comment]
Fixed in 9941651

**Comment by jacobsalmela** [comment]
Looks great!  Thanks!
