### ISSUE TITLE
[Feature request] Custom DNS display name in Queries answered by key.

### ISSUE THREAD

**Issue by ellensp** [pi-hole/pi-hole#2827]
I have a custom DNS setup to 127.0.0.1#5053  (ie DNS-Over-HTTPS from Cloudflare)
In Dashboard stats "Queries answered by" key section this is listed as from localhost. 

Although this is technically true, I would very much prefer it displayed a string of my choosing. Something like "Cloudflare-DNS-Over-HTTPS"  which is more accurate.

Would this be possible? Or even a good idea?

**Comment by DL6ER** [comment]
This should be easily achievable by using a different forward destination, say, `127.0.0.2` and defining a corresponding hosts name of you choice in, e.g., `/etc/hosts`.

**Comment by ellensp** [comment]
This works, but is not very user friendly. But is close enough for me for now.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
