### ISSUE TITLE
Admin page reported "An unknown error occurred while loading the data" while accessing "Network Overview" section

### ISSUE THREAD

**Issue by s-kk** [pi-hole/pi-hole#2828]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [*] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [*] The issue I am reporting can be *replicated*.
- [*] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Network Overview load normally`

**Actual behaviour:**

`Unknown error occurred. Nothing loaded`

**Steps to reproduce:**

`Normal installation on a Raspbian on Raspberry Pi 3 and load up Network page.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`xqh78seval`

**Troubleshooting undertaken, and/or other relevant information:**

OS: Raspbian on Raspberry Pi 3.
Using Pi-hole and AdminLTE from official installer script.
DHCP server was disabled on Pi-hole.
Accessing admin page on Chrome.

1. Rebooting Pi
2. Setting correct permissions for `/var/www/html`
3. Google for similar issues.
4. Similar issue #2776, but the author didn't give actual steps to resolve the problem.

Chrome console reported "GET http://pi.hole/admin/api_db.php?network&_=1562032892966     500 (Internal Server Error)"
Error located at jquery.min.js at line 3800 `f.send(a.hasContent && a.data || null)` (Chrome formatted version), and see picture below.
![Debug console](https://imgur.com/b6PzM8g.png)
Log file here: [Pi-hole Log](https://tricorder.pi-hole.net/xqh78seval)

**Comment by dschaper** [comment]
Were there any errors displayed, or did it just not display any data? Looks like it is displaying correctly, 
"Showing 0 to 0 of 0 entries" so there just isn't any data to display?

**Comment by Mcat12** [comment]
Check your nginx log for errors, but this is most likely due to you using nginx instead of lighttpd.

**Comment by s-kk** [comment]
Thanks guys for help.
@dschaper It's not displaying any data.
@Mcat12  Checked nginx error log. Yes there're log about `api_db.php`. Detailed logs below.

```
2019/07/02 11:16:24 [error] 5621#5621: *376 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /var/www/html/admin/api_db.php:71
Stack trace:
#0 /var/www/html/admin/api_db.php(86): SQLite3_connect(true)
#1 {main}
  thrown in /var/www/html/admin/api_db.php on line 71" while reading response header from upstream, client: 192.168.1.18, server: _, request: "GET /admin/api_db.php?network&_=1562037385115 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "pi.hole", referrer: "http://pi.hole/admin/network.php"
```

Seems like something is missing about SQLite3

**Comment by Mcat12** [comment]
You need to have the SQLite package installed in PHP. We only support lighttpd though, not nginx.

**Comment by s-kk** [comment]
@Mcat12 thanks issue resolved. Everything's working fine now.
