### ISSUE TITLE
Unable to update Pihole on CentOS 7

### ISSUE THREAD

**Issue by Eliesemoule** [pi-hole/pi-hole#2829]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Issue to update Pihole on CentOS 7

**Actual behaviour:**

When I launch the command pihole -up, I get this error message :

/etc/.pihole/automated install/basic-install.sh: ligne1628: test_dpkg_lock : command not found

**Steps to reproduce:**

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/0wlufi46yi

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

I can make some tests to help you to fix the issue

**Comment by dschaper** [comment]
What version are you currently running, and are you able to generate a debug token as requested in the template.

**Comment by Eliesemoule** [comment]
I updated the issue with the debug token link.

Here is the result of the pihole -v command:
`pihole -v`
`Pi-hole version is v4.3.1 (Latest: v4.3.1)`
`AdminLTE version is v4.3 (Latest: v4.3)`
`FTL version is v4.2.3 (Latest: v4.3.1)`

**Comment by Mcat12** [comment]
Please try `pihole -r` and choose "Repair".

**Comment by Eliesemoule** [comment]
When I launch repair, I had an error. See below :

[root@ip-172-16-0-10 outscale]# pihole -r

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Repair option selected
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking yum for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [i] Checking for dialog (will be installed)
  [i] Checking for git (will be installed)
  [i] Checking for iproute (will be installed)
  [i] Checking for newt (will be installed)
  [i] Checking for procps-ng (will be installed)
  [i] Checking for which (will be installed)
/etc/.pihole/automated install/basic-install.sh: ligne1628: test_dpkg_lock : command not found

**Comment by Mcat12** [comment]
What is the output of this command? `which debconf-apt-progress`

**Comment by Eliesemoule** [comment]
The output of the command is :
`[root@ip-172-16-0-10 outscale]# which debconf-apt-progress`
`/bin/debconf-apt-progress`

**Comment by Mcat12** [comment]
You have installed DEB tools on an RPM based server. Because of this, the installer thinks you are using a DEB based system. Remove that package, as we cannot support installs which mix package managers.

**Comment by Eliesemoule** [comment]
After remove debconf-apt-progress package, pihole update working fine.

Thanks a lot for your help. Have a good day
