### ISSUE TITLE
Pi Zero OTG Pi-Hole

### ISSUE THREAD

**Issue by DerfOh** [pi-hole/pi-hole#283]
Hey guys! Great work you're doing here! 

I was hoping to see if anyone has tried getting the Pi-Hole working over the Pi Zero's OTG networking mode.

I've been putting a lot of time into getting this figured out in hopes of using the Pi-Hole + Pi Zero as an on the go mobile advertisement shield for when I'm out on the road with my laptop. This simplicity of making this work solely through a single USB connection is too attractive though and it has proven quite difficult getting it right. The furthest I seem to be able to get is being able to SSH to the Pi over USB Ethernet mode but the pi has no internet access. Furthermore when I point the DNS settings on my laptop to the Pi's static IP (the one I use to SSH) I don't get any name resolution from the Pi. 

I think the problem is within my configuration but I'm starting to question if this is even possible. Has anyone gotten this working? Am I dreaming too big? Do I need to set up a DHCP server of sorts on either end of the connection? 

I'm grasping at straws here as there isn't a whole lot of documentation besides the following which is what I used to get the ethernet over OTG working:

- http://pi.gbaman.info/?p=699

I will update if I figure out a solution for this as this is what I would consider a perfect use case for your software!

**Comment by jacobsalmela** [comment]
I'm still trying to get my hands on a Pi Zero...

**Comment by PromoFaux** [comment]
Aren't we all? Soon...

**Comment by DerfOh** [comment]
I'm going to attempt again from a clean image soon, I think I might have mucked something up when toying around with DHCP.

**Comment by seanernet** [comment]
DerfOh,
I've accomplished a solution to your mobile issues by installing Openvpn on my Pi-Hole server. Now when I connect to the vpn from my phone, I am able to block all ads. This would work the same on your laptop. Hope this helps.

**Comment by PromoFaux** [comment]
@seanernet would you mind writing up some instructions for this on the [wiki](https://github.com/pi-hole/pi-hole/wiki), please?

**Comment by DerfOh** [comment]
@seanernet not a bad solution, I've done similar with the [sky-hole](http://dlaa.me/blog/post/skyhole) method. I was seeking a more 'local' method though.

**Comment by NorthernLoop** [comment]
For setting up the VPN I used the following:

http://readwrite.com/2014/04/10/raspberry-pi-vpn-tutorial-server-secure-web-browsing

I had been using the VPN as a safe connection from public internet, now with Pi Hole it works for my mobile ad blocking. Its great, 1 feature I missed from rooting my phone.

**Comment by NorthernLoop** [comment]
Update, the above is out of date for Jessie. In the meantime I purchased a Pi 2 so installed Jessie and used the following guide.

https://www.deviousweb.com/2015/11/29/raspberry-pi-as-an-openvpn-server/

Only change you need to make is in the server.conf don't use Googles/OpenDNS' server use the same IP as the VPN server you are building. If you have 2 Pi's you can use one for VPN and other for Pi Hole eg VPN 192.168.0.2 and Pi Hole 192.168.0.3 with your router probably being 192.168.0.1 etc

Not sure what the performance is like just yet but should be fine.

**Comment by dschaper** [comment]
Okay, the entire Dev Team has (have?) Zero's now!

**Comment by Mcat12** [comment]
Have. Mine is snug in it's little Lego case!

**Comment by dschaper** [comment]
It's now well documented how to run the Zero in Gadget Mode instead of Host Mode.

**Comment by DerfOh** [comment]
Can you link to it? I can't seem to find anything in the wiki at first glance...

**Comment by dschaper** [comment]
https://gist.github.com/gbaman/50b6cca61dd1c3f88f41
