### ISSUE TITLE
Conditional Forwarding does not work as should.

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/pi-hole#2836]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
**Expected behaviour:**

Enable Conditional Forwarding should make Top Clients (total) table and Top Clients (blocked only) display client names instead client IPs

**Actual behaviour:**

After enable conditional forwarding client IPs are still displayed in tables on dashboard
The same situation appears when Pihole is using as dhcp server.
![obraz](https://user-images.githubusercontent.com/37550896/60768570-ad6b4280-a0c5-11e9-80ce-70682052722a.png)

**Steps to reproduce:**

Enable conditional forwarding
Enter router ip
Enter local domain name
Click Save button

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/qs7u21i3qr

Router lan settings:
![obraz](https://user-images.githubusercontent.com/37550896/60768542-78f78680-a0c5-11e9-931f-e691ba4e6db8.png)

Pihole conditional forwarding settings:
![obraz](https://user-images.githubusercontent.com/37550896/60768554-8ca2ed00-a0c5-11e9-90f4-98c24b5d37da.png)

**Comment by DL6ER** [comment]
> After enable conditional forwarding client IPs are still displayed in tables on dashboard

Host names are not updated extremely frequently but only once per hour.

Try
```
sudo pihole-FTL restart
```
to force a re-resolving of the host names.

Also try
```
dig -x 192.168.0.6 +short @192.168.0.1
```
to check if your router does at all reply to such requests with the host names you expect.

---

> The same situation appears when Pihole is using as dhcp server.

Note that Pi-hole as DHCP server does only know of your clients when they have registered themselves at least once in the network. You usually need to powercycle them to enforce this.

**Comment by Haxy89** [comment]
I set up Conditional Forwarding two days ago and nothing.
Yesterday I tried to set Pihole as dhcp and still nothing.
Today clients ip still appear in tables.

**Comment by DL6ER** [comment]
Please try again to restart using
```
sudo service pihole-FTL restart
```
and wait a few minutes until you check the tables.

In case this does not help, what is the output of
```
dig -x 192.168.0.6 @127.0.0.1
```

**Comment by Haxy89** [comment]
```
piuser@Pihole:~$ dig -x 192.168.0.6 @127.0.0.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -x 192.168.0.6 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54109
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;6.0.168.192.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
6.0.168.192.in-addr.arpa. 0     IN      PTR     iPhone-Krystian.home.

;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jul 07 13:23:26 UTC 2019
;; MSG SIZE  rcvd: 87
```

**Comment by Haxy89** [comment]
After `sudo service pihole-FTL restart` nothing change

**Comment by DL6ER** [comment]
What is the output of http://pi.hole/admin/api.php?topClients ? Note that you need to be logged into your dash board in the same browser in order to be able to see this data.

**Comment by Haxy89** [comment]
![obraz](https://user-images.githubusercontent.com/37550896/60769361-f70c5b00-a0ce-11e9-95b6-3bacb2ed74e7.png)

**Comment by Mcat12** [comment]
@Haxy89 What do you have in `/etc/resolv.conf`? If the Pi-hole device is not set to use itself for DNS resolution, conditional forwarding will not work.

**Comment by Haxy89** [comment]
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 127.0.0.1
```
It is weird because in Pihole control panel I setup Cloudflare not Google.

**Comment by Mcat12** [comment]
The settings in the Pi-hole web interface are unrelated to `/etc/resolv.conf`. Use `resolvconf` to remove the `8.8.8.8` and `8.8.4.4` servers so that only `127.0.0.1` is used.

To do this, you will probably have to edit `/etc/network/interfaces` and run `resolvconf -u` to update the file.

**Comment by Haxy89** [comment]
My /etc/network/interfacs
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet manual
```

**Comment by dschaper** [comment]
Check `/etc/dhcpcd.conf` and see if there are any nameservers declared there that are not `127.0.0.1`

**Comment by Haxy89** [comment]
```
interface eth0
        static ip_address=192.168.0.20/24
        static routers=192.168.0.1
        static domain_name_servers=127.0.0.1

```

**Comment by dschaper** [comment]
First, you've given the Pi-hole an address that is inside the IP pool that the router is in control of. The problem with that is the router thinks it can give that address to a client and it does not know that a device has already chosen that address. So first step is to modify the routers IP pool of addresses to not include the Pi-hole address. 

Second is to check the DHCP server on the router to make sure it is not giving out 8.8.8.8 as a DNS server.

**Comment by dschaper** [comment]
Then check `/etc/resolvconf.conf` to make sure it does not have 8.8.8.8 as a DNS server.

**Comment by Haxy89** [comment]
I dont understand

```
static ip_address=192.168.0.20/24
        static routers=192.168.0.1
        static domain_name_servers=127.0.0.1
```

Router address is 192.168.0.1
Pihole ubuntu is 192.168.0.20 (lxc container, static ip)

![obraz](https://user-images.githubusercontent.com/37550896/61064262-bf205300-a401-11e9-8ef6-c8432d9be37d.png)

![obraz](https://user-images.githubusercontent.com/37550896/61064314-d4957d00-a401-11e9-9c51-1598f4b3fb1a.png)

**Comment by dschaper** [comment]
IP Pool Starts at .2, ends at .254. All the addresses inside that range are owned by the router and will be used when giving out leases to clients. Router does not know .20 is taken and will give that to another client. Set the starting address to be higher than .20 so that it's address is not given out by the router.

**Comment by dschaper** [comment]
Check the hypervisor for your LXC configuration and make sure it is not injecting 8.8.8.8 as a DNS server as well.

**Comment by Haxy89** [comment]
I cant set starting address to be higher than .20!
I have other clients in my network that use dhcp from router with manual ips assignation:
192.168.0.3
192.168.0.4
192.168.0.5
etc.

I set static .20 for pihole to be sure that dns in my local network is always .20

![obraz](https://user-images.githubusercontent.com/37550896/61065182-76699980-a403-11e9-9d33-3ba50156382a.png)


LXC hypervisor is not injecting 8.8.8.8, only 192.168.0.20 as dns

**Comment by dschaper** [comment]
Something, and not Pi-hole, is giving your lxc container the address 8.8.8.8 as the DNS server. That is what is causing the forwarding to fail. Pi-hole is working correctly and once you configure your network to not use 8.8.8.8 then your issue will be solved. Since this isn't a Pi-hole issue I'll mark it as such and close the ticket. Feel free to update the ticket though if you find further information.

**Comment by Haxy89** [comment]
thanks for help
