### ISSUE TITLE
Broken interface when not accessing through pi.hole

### ISSUE THREAD

**Issue by carroarmato0** [pi-hole/pi-hole#2845]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

My home router hands out DHCP leases and includes the DHCP option to pass the ipaddress of Pihole to all clients and the local domain "lan".

The hostname of my pihole is   pihole.lan which resolves to the correct ip address.

When I visit the webinterface through http://pihole.lan, the interface is broken as it's hardcoded to fetch the following resource at  pi.hole/...

> http://pi.hole/pihole/blockingpage.css  net::ERR_NAME_NOT_RESOLVED
> http://pi.hole/admin/scripts/vendor/jquery.min.js  net::ERR_NAME_NOT_RESOLVED
> http://pi.hole/admin/img/favicon.png  net::ERR_NAME_NOT_RESOLVED

**Actual behaviour:**

The code should fetch the resources according to a relative path and not hardcode pi.hole

**Steps to reproduce:**

Surfing to the IP address of Pihole results in everything working fine.
Surf to an alternative DNS entry for your Pihole which isn't pi.hole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

6s4kic15wh

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

I haven't yet, but I'll see if it's as easy as leaving our the hardcoded pi.hole reference in the html file.

**Comment by dschaper** [comment]
@Mcat12 This is intentional behavior, isn't it?

**Comment by carroarmato0** [comment]
I dug into the code a little bit and noticed this section:

> // Determine block page type
> if ($serverName === "pi.hole") {
>     // Redirect to Web Interface
>     exit(header("Location: /admin"));
> } elseif (filter_var($serverName, FILTER_VALIDATE_IP) || in_array($serverName, $authorizedHosts)) {
>   ...

It seems that Pihole kinda relies on it being accessed through http://pi.hole  which doesn't work if you have your network configured to register the DHCP client hostnames in DNS

**Comment by Mcat12** [comment]
Is the device configured to use `pihole.lan` as the hostname in `/etc/hostname`?

**Comment by Mcat12** [comment]
Regardless, the redirection from `/` to `/admin` is only meant for when accessing the site through `pi.hole`. For other hosts, go directly to `/admin`.

**Comment by carroarmato0** [comment]
> Is the device configured to use `pihole.lan` as the hostname in `/etc/hostname`?

Yep

```
root@pihole:/var/www/html# hostname -f
pihole.lan
root@pihole:/var/www/html# cat /etc/hostname
pihole
```

**Comment by carroarmato0** [comment]
I restarted lighttpd, and apparently that made a difference. I think perhaps something was applied in a wrong order during Pi-hole's installation.

Though if I visit http://pihole.lan, I get a "Website Blocked page"

![alt text](https://i.ibb.co/23cBhFj/pihole.png)

**Comment by Mcat12** [comment]
Are you able to access the web page at http://pihole.lan/admin?

**Comment by carroarmato0** [comment]
> Are you able to access the web interface at http://pihole.lan/admin?

Yes, that works.  I wonder if I can get the normal landing page on pihole.lan

**Comment by Mcat12** [comment]
This is working as expected then. The error you saw before was likely due to your browser caching DNS inconsistently. Since you got shown the block page you were using Pi-hole, and therefore `pi.hole` is accessible, but the browser cached that it was inaccessible.

I noted here that the redirection is explicitly only for `pi.hole`, and you should be using `/admin` to reach the web interface instead. The redirection is only for if you forgot to add `/admin`:
https://github.com/pi-hole/pi-hole/issues/2845#issuecomment-511074427

**Comment by carroarmato0** [comment]
Weird.  I cleared my OS's dnscache and tried accessing the page through incognito mode and get the same broken page.  I'm not knowingly bypassing pihole at the moment (unless Chrome is pulling some tricks)

**Comment by carroarmato0** [comment]
But accessing pihole.lan/admin is fine, which is ultimately what I wanted. Thanks for looking into it.

**Comment by Mcat12** [comment]
See my edit, you normally should not see the block page if you're not using Pi-hole, but you went directly to the Pi-hole and got the block page. Is your device set to use Pi-hole (can it access http://pi.hole/admin)?
