### ISSUE TITLE
Support DoH client requests and ESNI

### ISSUE THREAD

**Issue by nickolasemp** [pi-hole/pi-hole#2847]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Pi-Hole to provide a DoH compliant (http based) API for DoH client requests, so that FireFox can be configured to use the Pi-Hole as a TRR server. Eventually to have DoH/ESNI and Pi-Hole.

**Actual behaviour:**
There is no way to activate pi-hole as a DoH server with eSNI from our browser. I put in the about:config the network.trr.uri parameter as our pi-hole address in Firefox as well as enable esni, but I do not get a resolution to any DNS query. 

**Steps to reproduce:**
Put in the about:config the network.trr.uri parameter as our pi-hole IP address in Firefox. Any DNS request will fail. (not sure what I am about write, this should work from pi-hole -> internet I guess and not from browser->pi-hole)
Eventually this should be showing that esni works https://www.cloudflare.com/ssl/encrypted-sni/

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/5lzvs95vzp

**Troubleshooting undertaken, and/or other relevant information:**
I have installed cloudflared as a service for the connection from pi_hole to the internet and then used the 127.0.0.1#54 in pi-hole, a port where my cloudflared instance is accepting DNS queries. But this does not address the browser->pi-hole part of encryption.

I have also found another users asking for this.
https://discourse.pi-hole.net/t/pihole-doh-cloudflared-esni/18952/6

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by nickolasemp** [comment]
Sure thing
