### ISSUE TITLE
Enhancement: Filter blocklist when updated

### ISSUE THREAD

**Issue by bbum** [pi-hole/pi-hole#2849]
I understand why regex whitelisting isn't in the cards.

Instead of whitelisting the DNS queries themselves, how about a filter that effectively filters out any whitelisted entries when the blocklist is installed or updated?

Currently, I'm manually downloading various blacklists and have a bit of a shell script that filters out entries that normally involve many whitelist entries.   Then I load the modified blocklist into pi-hole.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
