### ISSUE TITLE
Installer script failed if static IP is set in dhcpcd.conf in Raspian

### ISSUE THREAD

**Issue by DeepSix** [pi-hole/pi-hole#2850]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:2

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`Installer script should not pause during install`

**Actual behaviour:**

`Setup script is pausing after checking for install packages`

**Steps to reproduce:**

`If there is any static entry in /etc/dhcpcd.conf, the script seems to pause.    This is Just an entry for IP and router, no DNS info was provided in dhcpcd.conf.   Once I remove the static IP assignment in the file, the script runs as expected.    The static IP on in dhcpcd.conf was the same as the one I wanted to assign to pihole.  `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`No log file was created during install while the issue was occuring. `

**Troubleshooting undertaken, and/or other relevant information:**

`See the steps to reproduce.   That's how I got the script to continue. `

**Comment by Mcat12** [comment]
If you did not have the `dhcpcd5` package installed, the package manager was likely waiting for you to decide if you wanted to keep your current config file or use the one provided by the package. Pi-hole can't choose for you, so you should fix this situation before trying to install Pi-hole.

I reproduced the issue on a Ubuntu 18.04 DigitalOcean droplet. It paused during the installation of the installer dependencies, near the start of the script.

The `dhcpcd.conf` I used:
```
interface eth0
static ip_address=192.241.229.146
static routers=192.241.229.1
```

The relevant output I got when manually running `apt install dhcpcd5`:
```
Configuration file '/etc/dhcpcd.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** dhcpcd.conf (Y/I/N/O/D/Z) [default=N] ?
```
