### ISSUE TITLE
URIs with `git://` protocol do not resolve

### ISSUE THREAD

**Issue by serra-allgood** [pi-hole/pi-hole#2853]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

`brew install --HEAD https://raw.githubusercontent.com/Tox/homebrew-tox/master/Formula/libtoxcore.rb` should complete the process of cloning or updating the libtoxcore brew cache with output similar to the following:
```
==> Cloning https://github.com/TokTok/c-toxcore.git
Updating /Users/corwin/Library/Caches/Homebrew/libtoxcore--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7aab0d9 Release 0.2.10
==> cmake . -DDHT_BOOTSTRAP=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/libtoxcore/HEAD-7aab0d9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCM
==> make
==> make install
==> Caveats
libtoxcore has no UI. If you want to make use of it, try Toxic for a CLI:
  brew install --HEAD toxic
or uTox for a GUI (X11):
  brew install --HEAD utox
or qTox for a GUI (Qt):
  brew install --HEAD qtox
==> Summary
🍺  /usr/local/Cellar/libtoxcore/HEAD-7aab0d9: 14 files, 1.3MB, built in 18 seconds
Removing: /Users/corwin/Library/Caches/Homebrew/libtoxcore--HEAD... (136.7KB)
```

**Actual behaviour:**

`brew install --HEAD https://raw.githubusercontent.com/Tox/homebrew-tox/master/Formula/libtoxcore.rb` fails with the following output:
```
######################################################################## 100.0%
==> Cloning git://github.com/TokTok/c-toxcore
Updating /Users/corwin/Library/Caches/Homebrew/libtoxcore--git
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Operation timed out

Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "libtoxcore"
Failure while executing; `git fetch origin` exited with 128. Here's the output:
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Operation timed out
```

**Steps to reproduce:**

Setup:
- macOS Mojave 10.14.5
- Raspberry Pi 3b
- Default install of Pi-hole with upstream DNS pointing to Cloudflare
- homebrew installed

1. Run `brew install --HEAD https://raw.githubusercontent.com/Tox/homebrew-tox/master/Formula/libtoxcore.rb`
2. Wait for timeout
3. Observe error output

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I attempted to upload the debug log with `pihole -d -a`, but curl failed. I tried disabling Pi-hole as well as connecting to a VPN and my phone's hotspot. All attempts failed. Please contact me at serra.allgood@pm.me if desired. It does seem that setupVars.conf does not get set with the Pi's IPv6 address for some reason.

**Troubleshooting undertaken, and/or other relevant information:**

- I found two workarounds: 
  - Connect to ProtonVPN
  - curl the url used in the brew command into a file; run `brew edit libtoxcore`; replace the contents with the curl'd file; edit the `git://...` urls to use `https`; run `brew install --head libtoxcore`
- Disabling Pi-hole failed
- Reconfiguring to the base set of blocklists failed
- Changing upstream DNS from Cloudflare to Google failed
- Running `sudo killall -HUP mDNSResponder && sudo killall mDNSResponderHelper && sudo dscacheutil -flushcache && say MacOS DNS cache has been cleared` followed by rebooting failed
- Running the above DNS commands on the Mac and closing all applications connected to the internet failed
- Rebooting the Pi failed
- Switching from connecting the Pi via wireless to wired failed (as well as reconfiguring to use eth0 instead of wlan0)
- Counterintuitively, the normal `git clone` commands works, but only with ssh or https, not the `git://` protocol
- Raspberry Pi 3b
- I did not try messing with firewall settings on the router because I found the above mentioned workarounds

Just want to add that Pi-hole is an awesome piece of software and I'm grateful that y'all maintain it. I'll definitely be donating when my next paycheck hits. I hope this issue is helpful

**Comment by Mcat12** [comment]
DNS only deals with translating the domain (`github.com`) into the IP address (`192.30.255.113`). Protocols such as `git://` are unrelated and unaffected. So long as Pi-hole is able to resolve the domain (by forwarding to its upstream), Pi-hole is working as intended.

If you change your Mac's DNS server to Cloudflare (as that is Pi-hole's upstream DNS) instead of Pi-hole, does it work? If not, then the issue exists independent of Pi-hole.

**Comment by serra-allgood** [comment]
My sincere apologies, I determined today that it was a firewall issue. Closing this issue.
