### ISSUE TITLE
4.3.1 version won't blocks sites from a long blocklist

### ISSUE THREAD

**Issue by neilatbne** [pi-hole/pi-hole#2854]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**
using https://blocklist.site/app/dl/porn on Pi-hole 4.3.1, it should blocks pornhub.com
because when I use the URL exactly same way on on pi-hole 4.3.0 (before I rebuild my Pi), it blocks pornhub.com and other sites listed.

**Actual behaviour:**
after rebuild my Pi, I installed pi-hole which is already 4.3.1, 
using https://blocklist.site/app/dl/porn on Pi-hole 4.3.1, it does not blocks pornhub.com, and any other sites listed in the blocklist. the log shows "OK", "forward", other than blocked.
but if I use https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list, which is much shorter list of porn website, those websites are blocked.
so I was wondering the new version 4.3.1 after consolidating the list, won't handle long blocklist well. This is the only external list I added into pihole, no others yet. I am afraid if I add more list, it won't work. How can I install 4.3.0 version?

**Steps to reproduce:**

build raspberry pi, install pi-hole 4.3.1.
add https://blocklist.site/app/dl/porn
test pornhub.com
remove it
add https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
test pornhub.com
I rebuild & reinstalled 4.3.1 twice, results are same, 4.3.1 won't take the first list to work, but second works.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/l7mrg86nsi

**Troubleshooting undertaken, and/or other relevant information:**
installed 4.3.1 twice, it shows the same.

**Comment by dschaper** [comment]
Is the debug token from when the list in question is being used? The gravity list is empty so there is nothing being blocked.

The list in question is malformed but it still should be able to be processed.

**Comment by neilatbne** [comment]
Thanks dschaper, yes the debug token is freshly generated right after the problem list being used.

**Comment by neilatbne** [comment]
> Is the debug token from when the list in question is being used? The gravity list is empty so there is nothing being blocked.
> 
> The list in question is malformed but it still should be able to be processed.

Thanks dschaper, yes the debug token is freshly generated right after the problem list being used.

**Comment by dschaper** [comment]
There are 0 domains in gravity. What does the dashboard show as number of domains to be blocked?

**Comment by dschaper** [comment]
Seems to be okay here.
![Annotation 2019-07-16 170722](https://user-images.githubusercontent.com/2782850/61337985-616a7d00-a7ec-11e9-91e2-4bd9873610e1.jpg)

**Comment by neilatbne** [comment]
> Is the debug token from when the list in question is being used? The gravity list is empty so there is nothing being blocked.
> 
> The list in question is malformed but it still should be able to be processed.



> There are 0 domains in gravity. What does the dashboard show as number of domains to be blocked?

I gave it a reboot, it still showing 0 blocked on dashboard, but yesterday it was 100K+, still not blocking.

**Comment by dschaper** [comment]
Try `pihole -g`

**Comment by neilatbne** [comment]
> Try `pihole -g`

did it, still show 0 on blocked domain.
but when I change the blocklist back to https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list , the blocked domain shows 138K+, and it started blocked pornhub.com

**Comment by neilatbne** [comment]
the https://blocklist.site/app/dl/porn list has IP address in there, maybe it caused pihole 4.3.1 not taking it? but 4.3.0 did take it and works.
the otherlist from https://blocklist.site/ does not work properly too. seems could be the reason? What blocklists are recommended? for porn, drup, game etc.
thanks.

**Comment by dschaper** [comment]
There are a few errors in your debug log, have you made any modifications to the `/var/www/html/admin` directory? And I see you are on Raspbian Jessie. We don't support that release anymore as Raspbian no longer supports it and the packages are very old. You'll need to update to Stretch. 

Lastly, do you have any issues with being out of space? Does `sudo df -h` show high use on any partitions?

**Comment by dschaper** [comment]
I don't have any suggestions for lists beyond the stock suggested lists. If you would like, you can go over to https://discourse.pi-hole.net and ask the community what they suggest.

**Comment by dschaper** [comment]
And check the screenshot I posted, it has the porn blocklist loaded and showing that it is working, with the domain you wanted showing as being blocked. So that list works with 4.3.1 as is.

**Comment by neilatbne** [comment]
> There are a few errors in your debug log, have you made any modifications to the `/var/www/html/admin` directory? And I see you are on Raspbian Jessie. We don't support that release anymore as Raspbian no longer supports it and the packages are very old. You'll need to update to Stretch.
> 
> Lastly, do you have any issues with being out of space? Does `sudo df -h` show high use on any partitions?
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       1.1G  980M   22M  98% /
devtmpfs        168M     0  168M   0% /dev
tmpfs           224M  228K  224M   1% /dev/shm
tmpfs           224M  8.7M  215M   4% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           224M     0  224M   0% /sys/fs/cgroup
tmpfs           224M     0  224M   0% /tmp
/dev/mmcblk0p1   63M  4.6M   59M   8% /media/boot
tmpfs            45M     0   45M   0% /run/user/999
tmpfs            45M     0   45M   0% /run/user/0

is 98% use of /dev/root a issue?
Thanks a lot! I will simply use the working list it should be fine.

**Comment by dschaper** [comment]
Yes, you are out of space. There is no place left to download the massive list that you would like to use. It looks like you have about 1 gig of space allocated? What size SDCard and how did you create it? NOOBS?

**Comment by neilatbne** [comment]
> Yes, you are out of space. There is no place left to download the massive list that you would like to use. It looks like you have about 1 gig of space allocated? What size SDCard and how did you create it? NOOBS?

my SDCARD is 4GB, and I used balenaEtcher to create it, it all done automatically and did not give me option to set size. Thanks!

**Comment by dschaper** [comment]
That's way too small, you need at least an 8 Gig card, and updating to Raspbian Buster also needs to be done.

**Comment by neilatbne** [comment]
thanks! so I need to delete log files from time to time under var/log?

**Comment by dschaper** [comment]
That's not going to help. You need a bigger SDCard. There are 2 million domains on that list, so if you previously used the list and did not see 2 million as the number on the dashboard then you haven't been actually using it.

**Comment by neilatbne** [comment]
> That's not going to help. You need a bigger SDCard. There are 2 million domains on that list, so if you previously used the list and did not see 2 million as the number on the dashboard then you haven't been actually using it.

Sound great! Thanks a lot for your quick help! That should solve my issue.
just a fyi for other readers, the balenaEtcher does not use the full size of SD card, it simply put the size of the image to the card, so it may need find another step/solutions to enlarge the partition.

**Comment by dschaper** [comment]
Okay, I'll close this out then.
