### ISSUE TITLE
Pi-hole doesn't seem to support Debian Bullseye

### ISSUE THREAD

**Issue by ETJAKEOC** [pi-hole/pi-hole#2857]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

For the Pi-hole service to be downloadable, installable, and executable

**Actual behaviour:**

Pi-hole seems to install (would really appreciate lighttpd not being installed if I already have apache2 installed, as it keeps trying to shut down my apache server and launch lighttpd, but 99% sure that's not what's causing my issue) perfectly normal, but the pihole-FTL.service can't launch because /etc/pihole/setupVars.conf is missing, which is wrong because I can see the file there, with only BLOCKINGENABLED=true as a value in the file, the pihole directory also has {adlists.list  adlists.list.old  GitHubVersions  localbranches  localversions  pihole-FTL.db} in the folder, I have nuked all pihole folders (including the .hidden's) and attempted reinstalling with no hope in sight.

**Steps to reproduce:**

install pihole service using the curl url method or the wget method and it will fail on Debian Bullseye

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/63p2nvi910

Troubleshooting attempts:

First attempt was to do a basic uninstall of pihole services using "pihole uninstall" and basic reinstall using curl method, got a bash error, switched to wget method, bash error disappeard, installer launched asking if I wanted to reconfigure existing pihole installation, quit and removed any pihole folders from my machine.

Attempted to use wget method again since it worked before, installer launched as a fresh install, nice, I fixed it, everything installs, awesome, time to check the status, and pi-hole FTL server is offline, purged dnsmasq from system and tried major uninstall/reinstall of pihole, same steps as above, same issue.

Not sure where to go from here, I've been running an apt-mirror and pi-hole blocker on my desktop machine for a few months now and now pihole doesn't want to play nice with my setup lol, any input is greatly appreciated

**Comment by dschaper** [comment]
We can't and don't support distributions that have not even been released. Debian 10 was just released, Debian 11 is way too new and unstable for us to devote time to.

**Comment by ETJAKEOC** [comment]
Understandable, if I figure it out I guess I'll have to let everyone know

**Comment by ETJAKEOC** [comment]
I was able to resolve this issue by commenting out the bionic universe section in the basic-install.sh
Not sure if it's had any negative effects on the system yet, but it's running and seems stable so far

**Comment by cipy** [comment]
is it now supported? (debian 11)

**Comment by yubiuser** [comment]
https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems
