### ISSUE TITLE
allow to disable lighttpd access logging

### ISSUE THREAD

**Issue by vladak** [pi-hole/pi-hole#2858]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

It should be possible to disable request logging done by `lighttpd`. This is handy for running from SD card in order to make it last as long as possible.

**Actual behaviour:**

`lighttpd` writes access logs to `/var/log/lighttpd/access.log` and it is not possible to disable this in robust way - any modification done to `/etc/lighttpd/lighttpd.conf` will be erased on upgrade.

**Steps to reproduce:**

1. query the local server http://localhost/admin/api.php
1. see `/var/log/lighttpd/access.log` to be written into

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/6p3fmqzjyc

**Troubleshooting undertaken, and/or other relevant information:**

I tried to workaround it by placing `accesslog.file = "/dev/null"` to `/etc/lighttpd/external.conf` however this does not work.

After filing https://github.com/pi-hole/docker-pi-hole/issues/484 I realized that Pi-hole itself needs a capability to disable the logging before it can be implemented in Docker image.

**Comment by dschaper** [comment]
This looks more like a feature request than a bug report so I'll close this out and ask that you fill out a Feature Request post on https://discourse.pi-hole.net.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
