### ISSUE TITLE
Installscript fails with "pihole: command not found"

### ISSUE THREAD

**Issue by wschoot** [pi-hole/pi-hole#2860]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No "command not found" errors

**Actual behaviour:**

Using Vagrant on CentOS7 (both host and box), I run into the fact that the webinstaller cannot find pihole, although it exists at that place. Perhaps bash is calling it wrong.

**Steps to reproduce:**

```
[..]
  [✓] DNS service is running
  [i] Pi-hole blocking will be enabled
/usr/local/bin/pihole: line 293: pihole: command not found
[vagrant@pihole ~]$ /usr/local/bin/pihole
Usage: pihole [options]
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/eq6nvrkf0j

**Comment by dschaper** [comment]
What is the `path` for that user? Does it include `/usr/local/bin`?

**Comment by wschoot** [comment]
It seems to have it; yes:

```[vagrant@pihole ~]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
```

**Comment by dschaper** [comment]
Ah, you are in Enforcing mode for SELinux, that will break a few things and as such it's not a supported configuration.

**Comment by wschoot** [comment]
Oh, right. There was a warning about SElinux and the webinterface, I didn't think it would actually break the installation itself.
Let's try with SElinux disabled. Thanks for your quick response!

**Comment by dschaper** [comment]
You can try checking `ls -Z /usr/local/bin/pihole` to see what contexts are set on that script just to be sure.

**Comment by dschaper** [comment]
But really, we should be calling the script with the full path and not just the script name. I'll mark is a bug for now to come back to.

https://github.com/pi-hole/pi-hole/blob/master/pihole#L293

**Comment by wschoot** [comment]
I can confirm that disabling SElinux doesn't change the outcome of this issue

**Comment by dschaper** [comment]
@bcambl Any thoughts?

**Comment by Mcat12** [comment]
Are you using Bash in your terminal? If not, it may have a different path.

**Comment by bcambl** [comment]
I am mostly interested in which vagrant box you are using.  
There is a ton of options out there and not all are the same..

Are you using one of the official images from [here](https://cloud.centos.org/centos/7/vagrant/x86_64/images/)? if so, which image.  
If not, could you please provide a link to the image on vagrant cloud?

**Comment by wschoot** [comment]
@Mcat12  Yes, I call the script using 
```
sudo bash basic-install.sh --unattended
```

@bcambl It's the *centos/7* box, which leads me to believe its the one from https://app.vagrantup.com/centos/boxes/7

Funniest thing happened though, I'm building a setupVars.conf beforehand for the unattended part and it all built fine since I tweaked that file a bit. I'm playing with that file now to see that triggers it.

**Comment by wschoot** [comment]
It seems that removing the BLOCKING_ENABLED line from setupVars.conf triggers the error.

With BLOCKING_ENABLED set to true OR false (or, probably set to whatever) in the setupVars.conf, it all builds fine. When I remove again, it gives the "command not found" error. 

For completeness sake, I've put the non-working code up at https://github.com/wschoot/pihole (with instructions in README.md about why it doesn't work and how to fix it, to not confuse others)

Does this help?

**Comment by dschaper** [comment]
Can you run `sudo bash echo $PATH` just to check? Really you shouldn't need to run it as `sudo bash basic-install.sh` as the script has a shebang line to pull the correct shell.

**Comment by wschoot** [comment]
```
[vagrant@pihole ~]$ sudo bash echo $PATH
/bin/echo: /bin/echo: cannot execute binary file

[vagrant@pihole ~]$ sudo echo $PATH                                                                       
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
[vagrant@pihole ~]$ 
```

I ran it with "sudo bash" as that's what's recommended from https://github.com/pi-hole/pi-hole/#one-step-automated-install

**Comment by dschaper** [comment]
Something is causing the new bash shell to not have the directory in it's path. 

Give `sudo bash -c 'echo $PATH'` a try and check. And also try just `sudo basic-install.sh` as the command to keep the current environment with the installer script run.

**Comment by wschoot** [comment]
You might be onto something here. This is on a freshly installed machine.

```
[vagrant@pihole ~]$ sudo bash -c 'echo $PATH'
/sbin:/bin:/usr/sbin:/usr/bin

[vagrant@pihole ~]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin

[vagrant@pihole ~]$ sudo -s
[root@pihole vagrant]# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin
[root@pihole vagrant]# 
```

The ''sudo basic-install.sh'' also bails with the "command not found" error. However, after the script has run, the PATH is different, I guess changed by the installer PATH? That at least explains why the second attempt to run the script, always succeeds.

```
# after installation:
  [i] Pi-hole blocking will be enabled
/usr/local/bin/pihole: line 293: pihole: command not found

[vagrant@pihole ~]$ sudo bash -c 'echo $PATH'
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
```

**Comment by wschoot** [comment]
So, concluding; it seems that my default path for the root-user is odd, or at least not what most people expect. I can live with closing this issue but I would like to suggest that adding /usr/local/bin to the $PATH within the script will solve potential problems (or, just call it everywhere using the full name instead of just the command and relying on the $PATH)

**Comment by dschaper** [comment]
Thanks, using the full path of the binary is probably the best way forward to prevent issues like this.
