### ISSUE TITLE
Pihole wildcards not working

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#2861]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6
---
**Expected behaviour:**

it should be blocked

**Actual behaviour:**

does not block, let it pass
random mass connections to i.e. cvdph3kzxmsufabvmd2rzxq4bqbqeaqbaeaq.a.e.e5.sk

$randomString.a.e.e5.sk

Query TXT 
OK (forwarded)INSECURE

Note: this domain is from ESET Internet Security seems to post log files over and over again.

As mentioned here https://forum.eset.com/topic/2037-is-this-malware/ ESET claims they use this for "Parental Control" which i have disabled so this could not be the issue.

Anyway, pihole should block connections to any e5.sk link, that's the issue regardless Parental Control is enabled/disabled that should not matter.

**Steps to reproduce:**

As this is related to ESET Internet Security, you can download a trail version from their website.
Click Blacklist in admincp
Add e5.sk and click "Add (wildcard)"

As far as i know (correct me if i'm wrong) add e5.sk as wildcard should disallow any connection to the complete e5.sk domain.

Pihole versions = latest as of today!

**Comment by dschaper** [comment]
Can you get us a token please?

**Comment by dschaper** [comment]
```
dschaper@Mariner:/mnt/c/WINDOWS/system32$ dig +short e5.sk                                                              0.0.0.0                                                                                                                 dschaper@Mariner:/mnt/c/WINDOWS/system32$ dig +short e.e5.sk                                                            0.0.0.0                                                                                                                 dschaper@Mariner:/mnt/c/WINDOWS/system32$ dig +short a.e.e5.sk                                                          0.0.0.0                                                                                                                 dschaper@Mariner:/mnt/c/WINDOWS/system32$ dig +short cvdph3kzxmsufabvmd2rzxq4bqbqeaqbaeaq.a.e.e5.sk                     0.0.0.0
```
![Annotation 2019-07-26 083550](https://user-images.githubusercontent.com/2782850/61963580-ce1a1000-af80-11e9-8393-ce0ef4900348.jpg)
