### ISSUE TITLE
Git dependency missing, false repo is missing error if git package is uninstalled

### ISSUE THREAD

**Issue by petersasi** [pi-hole/pi-hole#2866]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`4`

---
**Expected behaviour:**

`pihole -up` to run properly, as usual

**Actual behaviour:**

`pihole -up` gives false error (should just have a dependency in the git package, or ask to install git):
 `Error: Core Pi-hole repo is missing from system!`
 `Please re-run install script from https://pi-hole.net`

**Steps to reproduce:**

`sudo apt remove git ; pihole -up`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`It is really easy to reproduce, not sure this is really necessary.`

**Troubleshooting undertaken, and/or other relevant information:**

`sudo apt install git`

**Comment by dschaper** [comment]
Why are you uninstalling the `git` package?

**Comment by PromoFaux** [comment]
@petersasi, `git` is a core dependency for the install script (which is also the update script)

See [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L243).

It would have been installed along with Pi-hole when you first ran the install command, and the installation would not have completed without it. Could you also try a `pihole -r` to see if that reinstalls `git`? I don't have a system set up to test this with currently...

**Comment by petersasi** [comment]
You are not alone on any system 😉 And if you used to pivpn, but you had
switched to WireGuard, and the pivpn uninstall (or anything else really)
removes git, then you have a very misleading error message. 🤔

Either of these should catch it:

$ command -v foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's
not installed.  Aborting."; exit 1; }
$ type foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not
installed.  Aborting."; exit 1; }
$ hash foo 2>/dev/null || { echo >&2 "I require foo but it's not
installed.  Aborting."; exit 1; }


Really, I don't think it's valuable to explain me I shouldn't have another
similar script deinstall git. That won't fix the misleading error message.
Above could. 👍

Kind regards,
Peter

**Comment by PromoFaux** [comment]
I get your point now.  We could _possibly_ stand to add in some checks to the update script, being that `git` is pretty integral to the system, we should be checking it exists.

That said, the error message _does_ give you instruction on what to do in order to resolve the issue:

```
Error: Core Pi-hole repo is missing from system!
Please re-run install script from https://pi-hole.net
```

Which is saying run the `curl` script that you ran when you first installed Pi-hole. This will repair it. Same as a `pihole -r`.

Thanks for the report

**Comment by petersasi** [comment]
Yes, the instructions in the second half may work (didn't try) however
indirect.

The the first half is definitely false and misleading OTOH.

I did panic over having lost the local repo, probably needing to
reconfigure my whole setup upon reinstall (I also do DNS over https) while
everything is still in place and back on track after reinstalling git.

Cheers,
Peter
