### ISSUE TITLE
Request; Support g-zip content encoding on blocklist downloads

### ISSUE THREAD

**Issue by sjhgvr** [pi-hole/pi-hole#2867]
As the title suggests.  

This would cut back on data transfer use, clientside, and better yet, serverside (for those hosting blocklists (like myself)).

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
