### ISSUE TITLE
Is there a possibly to run this application on a Synology NAS? 

### ISSUE THREAD

**Issue by mat1th** [pi-hole/pi-hole#287]
Hello, 
This package is very exiting! Is there a possibility to run this packages on a Synology NAS? 

Thanks for the answer!
##

**Comment by PromoFaux** [comment]
Hey,

What package manager do they use on Synology? I believe it's a custom flavour of linux, but I'm not sure...

**Comment by matth96** [comment]
Hey, 
I don't exactly know what kind of package manager it is. I think I'its custom build. You have to add your own sources for the packages. 

There is a open source [tool](https://github.com/SynoCommunity/spksrc) to create native synology packages. And it would be nice if you can add it to the [synoCommunity](https://synocommunity.com) package source. 

I'm a beginner in webservers and DNS. But I would like to help.

**Comment by PromoFaux** [comment]
It may be possible. There is someone that has created a packet for [Arch linux](https://aur.archlinux.org/packages/pi-hole-server/).. so might be worth looking into!

**Comment by rj45jack** [comment]
Synology can have IPKG installed as well. More info: [https://forum.synology.com/enu/viewforum.php?f=40](Here.) I installed IPKG on mine awhile back, there is a lot of packages, but they're all CPU dependent.

**Comment by matth96** [comment]
Okay, thanks for the info. I will try it soon :)

**Comment by mfmjos** [comment]
I would be interested in this as well. FYI, synology uses busybox and has dpkg installed.

**Comment by diginc** [comment]
[Synology runs docker](https://www.synology.com/en-us/dsm/app_packages/Docker) so you might checkout the [diginc/pi-hole docker image ](https://hub.docker.com/r/diginc/pi-hole/) I just released.

**Comment by rj45jack** [comment]
@diginc only higher end Synos run Docker, sadly. Mine is not one, so I am unable to test that directly.

**Comment by matth96** [comment]
@diginc Mine also doesn't support docker :(, so I can't test it. But thanks for the mentioning!

**Comment by mettix** [comment]
investing

**Comment by benlowry** [comment]
I would also like to use this on my NAS without docker, I think docker is only on the beefy x86 ones.

**Comment by Xtoftjen** [comment]
Any news on if there will be a Synology package released soon?
Looking all over the internet for it, a lot of people want it, so it would be a good move for Pi-Hole

**Comment by PromoFaux** [comment]
The difficulty here is that none of the dev team have a Synology NAS (though if anyone wants to buy one with a couple of HDDs for any of us... :wink:), so we'd essentially be coding in the dark!

What we need ideally is someone that has one to adapt the existing install script to work with Synology, similar to how @bcambl adapted it to work with Fedora flavoured distros.

**Comment by PromoFaux** [comment]
Of course, if you want to attract others to this issue, you can always [open up a bounty](https://www.bountysource.com/issues/30566640-is-there-a-possibly-to-run-this-application-on-a-synology-nas?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github) on it!

**Comment by brantje** [comment]
We can use xpenology for emulating DSM 5.2

**Comment by Xtoftjen** [comment]
Any update on this?

**Comment by ssgtcookie** [comment]
Unfortunately it's not very common to install software trough the CLI on Synology systems. Some versions of the synology OS will even require you to "unlock" all ssh commands by a process called bootstrapping. This proces is not very user friendly, trust me. :( Synology has builded it's own visual package manager ecosystem trough the webinterface.  ideally we would release this software in the syno package manager I think...

The bad news:
This software uses an DNS server to server the clients in the network. The Synology DNS server does not support blacklisting, we would need to alter this package which will be hard.

The good news:
The user community has been quite active on this project. :) One of the forks has made it possible to run this software on ubuntu servers, it's called "sky-hole". It uses the DNS software "dnsmasq". If we could port this to synilogy we coulad than use this as the DNS server right? The webserver, database and serverside programming is already there prpvided by synology.

I would like to work on this project asap but I'm also intrested in the toughts of the community on this matter.

http://blog.codybunch.com/2015/07/28/Pi-Hole-in-the-cloud/

**Comment by PromoFaux** [comment]
>one of the forks has made it possible to run this software on ubuntu servers

The base project supports ubuntu servers! Next release will have fixes for Ubuntu 16.04 :)

The issue with official Synology support still stands, though, none of us have one to test with, so we need all the help from the community we can get there! A quick google of "dnsmasq synology` comes up with this link: http://syndnsmasq.the-ninth.com/

Might be a good starting point?

**Comment by ftrueck** [comment]
docker on synology is not working. My synology is already running dnsmasq on port 53 but i have no separate dns server package installed.

**Comment by SmiGueL1** [comment]
I currently use the default DNS server from Synology as a Sy-Hole ad-blocker.
Please read my post for more info:
https://forum.synology.com/enu/viewtopic.php?f=39&t=78126&start=45#p451753

I've made it so you can use the same adblock/trackers lists Pi-Hole uses, and you can also add a custom blacklist and whitelist to it. The whitelist is to overrule some of the the unwanted URL's in the Pi-Hole blacklists.

I know this isn't exactly the same as Pi-Hole, doesn't have a nice UI, isn't a package, and takes up more RAM when importing multiple huge lists. (but it's very simple to install though, read the post)
It can update automatically ever day or week (or whatever you like) so you always have the latest version of the blacklists.

I would really like to see that Pi-Hole get's it's own Synology package, but till that time this works fine for me. :)

**Comment by PromoFaux** [comment]
Thanks @SmiGueL1 Would you mind crossposting this over into https://discourse.pi-hole.net/t/pi-hole-on-synology-diskstations/233/3?

**Comment by dschaper** [comment]
And please be sure to include the model of Synology you've tested/written for. As I understand it, there are some models of Synology devices that aren't capable of running some software packages? Having a list would help our users know if they can run on their devices.

**Comment by SmiGueL1** [comment]
@PromoFaux I read [that post](https://discourse.pi-hole.net/t/pi-hole-on-synology-diskstations/233/4) and thought you meant we had to continue the discussion in the mentioned topic (this topic). My bad XD

**Comment by PromoFaux** [comment]
Either or really, but it's really good information and worth posting there for the users than may not look at both threads!

**Comment by bakman2** [comment]
I have just installed pi-hole on my synology using chroot, I have written instructions how to do it, not sure what the right place is where put them.

**Comment by dschaper** [comment]
The wiki is good, or over at http://discourse.pi-hole.net our new home.

**Comment by bakman2** [comment]
Ok I will add it to the FAQ if that's ok.

**Comment by dschaper** [comment]
Sounds good!

**Comment by bakman2** [comment]
Done: https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289

**Comment by ssgtcookie** [comment]
@bakman2 using Chroot is a beautiful approach for this problem, thank you for the idea and instructions! 👍 I followed the instructions and bumped into some problems on my DS214+. 

Problem 1:
Chroot does not start with DSM 6.0 on a reboot or a manual shutdown / restart, the DNS server will not recover from a power outage.

Problem 2:
After the finishing the `curl -L https://install.pi-hole.net | bash` command, the web panel gave me a 403 forbidden msg. The following commands solved the issue for me.
```
lighty-enable-mod fastcgi
lighty-enable-mod fastcgi-php
/etc/init.d/lighttpd force-reload
/etc/init.d/lighttpd restart
```

After that, in the browser console there still are "not fount 500" errormsgs on the api.php. Without this file, the webpanel is not very useable. :( Also the `pi-hole -d` command is not working.

The pi-hole ssh install was error-free. I have chosen for IPV4 only, UTF-8 and disabled I the firewall completely. Are there any other users having problems or is this just me? :)

**Comment by bakman2** [comment]
pi-hole is using dnsmasq which starts automatically upon starting chroot.
I suspect something went wrong with your installation.

If you ssh into your dsm, switch to root user (not admin) and go back into chroot
```/var/packages/debian-chroot/scripts/start-stop-status chroot```
and run ```curl -L https://install.pi-hole.net | bash``` again to see what happens.

**Comment by bakman2** [comment]
@ssgtcookie I have update the [instructions](https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289) to autostart pi-hole after reboot. 

Also when chroot is install you can access it, but the services have not started which might explain why it didn't work for you. I have included that as well (start chroot)

**Comment by ftrueck** [comment]
In My case there was a problem with /proc. The cat was giving an access
error. /proc was empty in Christ. I did follow all steps of the tutorial.

Am 22.10.2016 00:09 schrieb "bakman2" <notifications@github.com>:

**Comment by dschaper** [comment]
Please see https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289
