### ISSUE TITLE
DNS queries can only be flushed via terminal

### ISSUE THREAD

**Issue by ETJAKEOC** [pi-hole/pi-hole#2870]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the contributors guide.

- [X] The issue I am reporting can be *replicated*. (Plausibly, depends if you broke your config like me)

- [X] The issue I am reporting isn't a duplicate.

**How familiar are you with the the source code relevant to this issue?:**

1

**Expected behaviour:**

DNS queries logs to be cleared

**Actual behaviour:**

Pi-hole service runs as expected, except for that fact that I can not ever clear the DNS queries log through the web interface, I have to run "pihole flush" in order to clear it.

**Steps to reproduce:**

Try to flush all DNS queries from the settings page, it will fail, attempt from cmd line, it will succeed

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

p5ms65oe8n

**Troubleshooting undertaken, and/or other relevant information:**

I had almost 10k entries in my DNS queries log, and in the process of trying to find a page that was being blocked that I wanted to unblock, figured I'd reset my logs and try to go to the page again, see the queries fresh from the get go with nothing else in the log, help make tracing a little easier. I had had a php sessions issue which required reinstalling php-7.3, after reinstallation, the settings page, whitelist page, and blacklist page became usable again. I still could not flush the queries through the settings page though. I attempted to run the "pihole flush" command in my terminal, and boom, it worked first try. But even after flushing using this method, I still can not flush via the settings page.

**Comment by ETJAKEOC** [comment]
Now I've learned that the pi-hole service isn't keeping a log of ANY blocked sites, period

**Comment by Mcat12** [comment]
Are you using lighttpd for the web server? You seem to have a very customized install running on an unsupported OS (Klusterfuk OS 1.2).

**Comment by ETJAKEOC** [comment]
No, I'm running apache2.

Klusterfuk OS is my custom blend of a multitude of the latest unstable Debian based OS's together, but the majority of the packages come from Debian sid as it's normally most up to date, but it pulls from Kali, Ubuntu, PureOS, Linux-Lite, SteamOS, and a few others I can't remember off the top of my head.

But I always had the pi-hole working flawlessly regardless of all this clutter believe it or not, I only happened to notice this issue a few days ago after a php version conflict, but with my log being at around 10k I had a feeling logs weren't being purged, so I tried to manually purge through the interface, and this is when I discovered this wasn't working.

All system services are stable and operational, I don't use a GUI for my machine because it's only use is server-related, I do have my /var/logs symlinked on a f2fs system with the rootfs being on an ext4 system, but I doubt that's causing any issues with the pihole.

**Comment by Mcat12** [comment]
We can only support using lighttpd for the web interface while on a supported operating system: https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

If you can reproduce this on a supported system, the issue can be reopened.
