### ISSUE TITLE
Query entries from blocklists not going away after removing a blocklist

### ISSUE THREAD

**Issue by krypto5863** [pi-hole/pi-hole#2872]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`
---
**Expected behaviour:**

`Query lists updating correctly after removing blocklist.`

**Actual behavior:**

`Instead of the blocked query entries going away, they somehow transfer to the next or previous blocklist despite that blocklist not having that particular query entry (confirmed by manual finding)`

**Steps to reproduce:**

`Add blocklists in a batch(maybe separately). Remove blocklists. Check queries for remaining entries that shouldn't be there any longer.`

**Troubleshooting undertaken, and/or other relevant information:**

Removing all blocklists added in the batch and adding them in one by one seems to fix the issue.

**Comment by yubiuser** [comment]
@krypto5863 

Does the issue still persists?

**Comment by krypto5863** [comment]
I'm not sure, I haven't used Pi-Hole recently but I think the issue was resolved in an update. I'll close the issue.
