### ISSUE TITLE
Option to skip setting Static IP (and install dhcpcd,... packages) for other network manager

### ISSUE THREAD

**Issue by Tristan79** [pi-hole/pi-hole#2875]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Option to skip static config (with dhcpcd) if you have another network manager installed (like I have systemd-network, see also https://github.com/pi-hole/pi-hole/issues/1713) 

and also do not install these packages _(maybe more???)_

- openresolv
- dhcpcd5
- ifupdown 

**Actual behaviour:**

I have a freshly installed raspberry pi buster with systemd-network to bridge 2 network cards (wifi/lan failover) 

systemd-network because bonding is not working using /etc/network/interfaces config/tutorials, it randomly loses name resolution, but that is not relevant to this problem... setup using: https://raspberrypi.stackexchange.com/questions/78787/howto-migrate-from-networking-to-systemd-networkd-with-dynamic-failover

but it would be nice to have an option to skip setting the static ip and skip installing those packages, 

**Steps to reproduce:**

Run the installer/setup...

**Troubleshooting undertaken, and/or other relevant information:**

Currently for systemd-network I set manually the static ip of my bond... then install pihole with...

git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
sudo apt --autoremove purge openresolv -y
sudo apt --autoremove purge dhcpcd5 -y
sudo apt --autoremove purge ifupdown -y

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
