### ISSUE TITLE
Hangs at "Configuring resolvconf (amd64)" When installing to 18.04 LXC on QNAP

### ISSUE THREAD

**Issue by DIYglenn** [pi-hole/pi-hole#2876]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{Finishing installing packages}`

**Actual behaviour:**

`{<
<img width="568" alt="Skjermbilde 2019-08-15 kl  11 12 22" src="https://user-images.githubusercontent.com/10504432/63085717-7141c200-bf4e-11e9-9cea-f211d8a0ae0f.png">
>}`

**Steps to reproduce:**

`{
1. Create Ubuntu 18.04 LXC (on QNAP)
2. Update LXC with apt update %% apt upgrade
3. Create a separate user and add to sudo
4. Install openssh
5. SSH in to the server and install curl + run the pi-hole installer
6. Select Cloudflare as DNS, leave everything else default }`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
That's a problem with `apt-get` on the underlying operating system. It's probably needing input on a question for configuration. 

What template are you using for the LXC? Does `sudo apt-get install resolvconf` at the command line complete without an issue?

**Comment by DIYglenn** [comment]
I just ran sudo apt install resolvconf :

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
resolvconf is already the newest version (1.79ubuntu10.18.04.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
10 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
`

**Comment by dschaper** [comment]
Try `sudo apt-get install -f`

**Comment by DIYglenn** [comment]
I clicked "Y" and this happened:
```
Configuration file '/etc/resolvconf/resolv.conf.d/head'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

I then tried sudo apt install -f:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by dschaper** [comment]
That would be why the install hanged. You'll need to resolve the conflict. Once that is fixed you can re-run the installer script and it will continue.

**Comment by DIYglenn** [comment]
OK. Thanks. So what would make sense in this image? There's nothing else I want installed.
Maintainer or currently installed? 
I tried with "N" and you're correct - it installed without issues.

**Comment by dschaper** [comment]
Without seeing the differences between the files I can't say what the best answer would be.

**Comment by DIYglenn** [comment]
Ok. I used the Canonical Ubuntu 18.04 LXC image, did no changes other than update and start installing Pi-Hole. 

I’ll recreate it and check what’s in there before running instal resolvconf.

**Comment by DIYglenn** [comment]
Sorry for the late replay;
```
ubuntu@Pi-Hole:~$ cat /etc/resolvconf/resolv.conf.d/head                                                                                    
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)                                                              
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN                                                                     
nameserver 8.8.8.8                                                                                                                          
nameserver 8.8.4.4                                                                                                                          
```

**Comment by DIYglenn** [comment]
When installing resolvconf and choosing "yes":
```root@Pi-Hole:/home/glenn# cat /etc/resolvconf/resolv.conf.d/head 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.
```

**Comment by DIYglenn** [comment]
I went with the last configuration (choosing yes). Correct me if this is an issue.

**Comment by Jetro97** [comment]
Hi DIYglenn,
Try adding your hostname in your **/etc/hosts** file, ex:

`127.0.0.1          <YourHostname>`
