### ISSUE TITLE
Pi-hole won't install without a default gateway configured

### ISSUE THREAD

**Issue by SurinameClubcard** [pi-hole/pi-hole#2878]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7 (modified the basic-install.sh)

---
**Expected behaviour:**

I'm installing pi-hole on a machine with (deliberately) no default gateway configured. There is a forwarder in the same subnet. Also, there is a proxy server in the same subnet. During installation, I selected "custom" as the upstream DNS and entered the IP-address of that local upstream. The installer should have no problems with this setup. 

**Actual behaviour:**

The installation fails. The bash-script stopped/crashed/failed at line 512: 

`route=$(ip route get 8.8.8.8)`

Installation fails because there is no route to 8.8.8.8. This will only work if there is in fact a route to 8.8.8.8, which (in my case) is missing. Replacing 8.8.8.8 with the IP-address of my local upstream worked fine. 

**Steps to reproduce:**

Remove the (default) gateway(s) from a host and try to install pi-hole.

**Troubleshooting undertaken, and/or other relevant information:**

Replace line 512 with:

`route=$(ip route get [ip-address of local DNS forwarder])`

Note that to have the installer successfully finish the installation through a proxy server, the proxy:port has to be registered in curl (`~/.curlrc`) and git (`~/.gitconfig`) in advance, otherwise the installer will also fail... The installer could be more proxy-aware but that is for another moment.

**Comment by dschaper** [comment]
This is such a unique situation I don't think we can modify the installer in this way. We'd have to add yet another dialog asking for a remote address to check during the installation.

**Comment by SurinameClubcard** [comment]
Easy fix would be to change that 8.8.8.8 to the IP-address the user entered as his upstream DNS if and only if such a custom IP-address was entered? Looking at the function `find_IPv4_information()` which contains this code, it is only used locally.

FYI: I'm using pi-hole in a hardened network environment in which it is not that unusual to not have a default gateway configured.

**Comment by dschaper** [comment]
I don't exactly like having 8.8.8.8 hard coded as the target. Really the upstream should be the target no matter what since that's the required endpoint that should be accessible from the Pi-hole.

**Comment by SurinameClubcard** [comment]
Sort of what I am proposing, am I not?

**Comment by dschaper** [comment]
I was agreeing with you.
