### ISSUE TITLE
Pi-hole installation could be more proxy-friendly

### ISSUE THREAD

**Issue by SurinameClubcard** [pi-hole/pi-hole#2880]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I installed Pi-hole on a Linux box which has to use a proxy to access the internet. The box itself is properly configured to do so. I expect the installer to recognize that fact and (re)use that configuration to successfully install itself. Or, at least, mention the fact that installation through a proxy is not supported/not possible.

**Actual behaviour:**

The installer fails to recognize the proxy configuration and fails on `curl` and `git` operations. 

**Steps to reproduce:**

Take a box, put Linux on it, block its network address at the firewall for outgoing traffic towards the internet, take another box, put a proxy on it and make it work correctly, and add `http_proxy=<proxy>:<port>` and `https_proxy=<proxy>:<port>` to `/etc/environment` of the first box. 

**Troubleshooting undertaken, and/or other relevant information:**

Only after putting proxy information in `~/.curlrc` and `~/.gitconfig`, installation succeeds. Or, e.g., modify the installer and add `-x <proxy>:<port>` to curl operations.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by SurinameClubcard** [comment]
That's ok! Other users with the same problem can use this (closed) issue to solve it themselves.
