### ISSUE TITLE
Installer exits with php5-* packages chosen on Buster

### ISSUE THREAD

**Issue by MichaIng** [pi-hole/pi-hole#2888]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`9`

---
**Expected behaviour:**

`On Debian/Ubuntu, before checking for any packages on repos (php vs php5, sqlite vs sqlite3 etc), an APT update should be done to assure that lists are available and up-to-date.`

**Actual behaviour:**

`Package availability is done first, so choices can be done on wrong assumptions, especially since no availability check is done on the fallback packages anymore.`

**Steps to reproduce:**

1. Clear the APT cache + package lists
2. Run Pi-hole installer
3. Watch it choose php5-* packages, because dry-run install of `php` fails. But php5-* packages are not available as well, thus installer fails.

**Solution:**

- Run APT update step before checking the repo for available packages.
- Check fallback package availability as well, if those fail as well, exit installer with meaningful error message.
- Optional: Use `apt-cache show <pkg>` to check for package availability, which is much faster and cleaner then a dry-run install.

**Comment by MichaIng** [comment]
I opened a PR to solve this issue: https://github.com/pi-hole/pi-hole/pull/2889
This is applied for other package availability checks as well: iproute/iproute2 and php-sqlite/sqlite3

I couldn't hold myself to include dialog removal from Debian/Ubuntu installer dependencies 😅. It is never used (whiptail is) and I anyway ran some install tests to include this.

**Comment by MichaIng** [comment]
Fixed with #3203, marking as closed 👍.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1
