### ISSUE TITLE
Uninstall script removed /etc/lighttpd

### ISSUE THREAD

**Issue by tzahola** [pi-hole/pi-hole#2890]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---
**Expected behaviour:**

When installing pi-hole I chose *not* to install lighttpd, because I already had it installed. Yet the uninstall script removed the whole /etc/lighttpd folder, even though I chose *not* to remove dependencies.

**Actual behaviour:**

The uninstall script shouldn’t remove /etc/lighttpd especially in “no purge” mode.

**Steps to reproduce:**

1. install lighttpd
1. install pi-hole and choose not to install lighttpd
1. uninstall pi-hole
1. now /etc/lighttpd is gone

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n/a

**Troubleshooting undertaken, and/or other relevant information:**

n/a, sorry, I’m spending my time recovering my lighttpd configuration...

**Comment by dschaper** [comment]
Looks like the logic was inverted with this commit: https://github.com/pi-hole/pi-hole/commit/e9e92368b0565cd9fc7a780724a04898f9872560

It should only remove the directory if the `lighttpd` package is non-existent. This commit flipped it to remove the directory when the package is still installed.

@Mcat12 Is this what was to be expected with the PR?

**Comment by PromoFaux** [comment]
I think, perhaps, it would be best if we _didn't_ attempt to clear out/remote `/etc/lighttpd`, regardless of whether or not the user has chosen to remove the package. Really that should be down to the package manager to tidy up after itself, if it needs to.

All we should remove really is `/var/www/html/admin` (providing it is the Pi-hole admin page)

Another part of me thinks we should nuke the uninstall script and start it again. I'm not volunteering for that task just yet though!

**Comment by dschaper** [comment]
I'm in agreement with that. I would rather err on the side of leaving too much than leaving too little. 

Let me know if you want a crack at a redo, I agree with the need to do-over.

**Comment by Mcat12** [comment]
This PR changed the lighttpd uninstall to only remove the `external.conf` file we added and restore the original file: #2808. We aren't clearing out `/etc/lighttpd` anymore.

The code now looks like this:
https://github.com/pi-hole/pi-hole/blob/9f77810ca8bf8708cfaf4bb84a7c3de0e6d6d29e/automated%20install/uninstall.sh#L134-L144

**Comment by dschaper** [comment]
So this should be fixed in 4.3.2 then.
