### ISSUE TITLE
Got SERVFAIL from Pi-hole, via a local query.

### ISSUE THREAD

**Issue by shizunge** [pi-hole/pi-hole#2894]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:0**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Pi-hole returns an ip address

**Actual behaviour:**

Got SERVFAIL

**Steps to reproduce:**

I am investigating why I have a large number of queries for a domain res.servicewechat.com.

I have setup 1.1.1.1 as my upstream DNS server.
I made a manual query via nslookup and got following result:

    > res.servicewechat.com
    ;; Got SERVFAIL reply from 127.0.0.1, trying next server
    Server:         108.61.10.10
    Address:        108.61.10.10#53
    
    Non-authoritative answer:
    res.servicewechat.com   canonical name = res.servicewechat.com.edgekey.net.
    res.servicewechat.com.edgekey.net       canonical name = e6156.f.akamaiedge.net.
    Name:   e6156.f.akamaiedge.net
    Address: 184.31.186.46

Then I checked /var/log/pihole.log
It seems dnsmasq did obtain the ip address:

    Aug 29 21:07:55 dnsmasq[3546]: query[A] res.servicewechat.com from ::1
    Aug 29 21:07:55 dnsmasq[3546]: forwarded res.servicewechat.com to 1.1.1.1
    Aug 29 21:07:55 dnsmasq[3546]: dnssec-query[DS] servicewechat.com to 1.1.1.1
    Aug 29 21:07:55 dnsmasq[3546]: Insecure DS reply received, do upstream DNS servers support DNSSEC?
    Aug 29 21:07:55 dnsmasq[3546]: reply servicewechat.com is BOGUS DS
    Aug 29 21:07:55 dnsmasq[3546]: validation res.servicewechat.com is BOGUS
    Aug 29 21:07:55 dnsmasq[3546]: reply res.servicewechat.com is <CNAME>
    Aug 29 21:07:55 dnsmasq[3546]: reply res.servicewechat.com.edgekey.net is <CNAME>
    Aug 29 21:07:55 dnsmasq[3546]: reply e6156.f.akamaiedge.net is 23.211.235.27

I have also tried manually query res.servicewechat.com.edgekey.net and e6156.f.akamaiedge.net. Both addresses work. Got failure only on res.servicewechat.com

Why does my application/nslookup get SERVFAIL from Pi-Hole for this particular domain?
Could anyone see if you can also reproduce the problem?

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Must I directly paste the contain to this bug? Can I attach the file instead of copying?
I think I have entered essential logs.

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

I have changed my upstream DNS server to 8.8.8.8
Now nslookup can get the ip address from Pi-hole.
Strange?
Just some random guess:
Does this relate to DNSSEC? As 1.1.1.1 does not support DNSSEC.
Does this relate to timeout issues? I found TTL is quite large (20000+) on the query. see the below record:

    "Question":[
      {
        "name":"res.servicewechat.com.",
        "type":1
      }
    ],
    "Answer":[
      {
        "name":"res.servicewechat.com.",
        "type":5,
        "TTL":176,
        "Expires":"Fri, 30 Aug 2019 04:43:40 UTC",
	"data":"res.servicewechat.com.edgekey.net."
      },
      {
        "name":"res.servicewechat.com.edgekey.net.",
        "type":5,
        "TTL":20094,"Expires":"Fri, 30 Aug 2019 10:15:38 UTC",
        "data":"e6156.f.akamaiedge.net."
      },
      {
        "name":"e6156.f.akamaiedge.net.",
        "type":1,
        "TTL":16,
        "Expires":"Fri, 30 Aug 2019 04:41:00 UTC",
        "data":"184.31.186.46"
      }
    ]

**Comment by dschaper** [comment]
`BOGUS DS` is a DNSSEC response. 1.1.1.1 has had problems in the past with DNSSEC responses and breaking things. https://community.cloudflare.com/t/does-1-1-1-1-really-run-dnssec/33539/13

This is an external issue and not a Pi-hole issue.

**Comment by shizunge** [comment]
But dnsmasq seems got an IP address (seen from the log).
Should Pi-hole return that IP address instead of nothing?

**Comment by shizunge** [comment]
So Pi-Hole intentionally dropped the Bogus results, and did not send them to the caller?
Is it expected?

**Comment by dschaper** [comment]
Yes, DNSSEC will drop any result that is not verified. BOGUS means the record has been altered from what is expected or signed.
