### ISSUE TITLE
Installing PiHole Ubuntu LTS 14.04.3 fails on Checking for php-sqlite3 (will be installed)

### ISSUE THREAD

**Issue by RL-88** [pi-hole/pi-hole#2895]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`When attempting to install PiHole using the automated install script. It fails on "[i] Checking for php-sqlite3 (will be installed)
"`

**Actual behaviour:**

`[i] Checking for php-sqlite3 (will be installed) it drops back to console. After running curl -sSL https://install.pi-hole.net | bash -xv it tells me
Err:2 http://au.archive.ubuntu.com/ubuntu bionic/main amd64 php-sqlite3 all 1:7.2+60ubuntu1
  File has unexpected size (12100 != 2004). Mirror sync in progress? [IP: 202.158.214.106 80]
  Hashes of expected file:
   - SHA256:9d7e707e32a63af2b386bb27f70a547b8f7fdceb8611fa072a8d3ce8424c052c
   - SHA1:3aa7e48f460f2de960e6f592da7ed99ff151a7ac [weak]
   - MD5Sum:b92d999369d8b6b824bc99c21201b06c [weak]
   - Filesize:2004 [weak]
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/main/p/php-defaults/php-cgi_7.2+60ubuntu1_all.deb  File has unexpected size (61690 != 3256). Mirror sync in progress? [IP: 202.158.214.106 80]
   Hashes of expected file:
    - SHA256:36625881c6abf467b174abd10fd9ed30b6721d21d6216c14e7295b8712fa1126
    - SHA1:9f355ae00d661077305dc9d6855bd306d8ed35d1 [weak]
    - MD5Sum:4ce9462502f6e9b57a04d7c9e39062f7 [weak]
    - Filesize:3256 [weak]
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/main/p/php-defaults/php-sqlite3_7.2+60ubuntu1_all.deb  File has unexpected size (12100 != 2004). Mirror sync in progress? [IP: 202.158.214.106 80]
   Hashes of expected file:
    - SHA256:9d7e707e32a63af2b386bb27f70a547b8f7fdceb8611fa072a8d3ce8424c052c
    - SHA1:3aa7e48f460f2de960e6f592da7ed99ff151a7ac [weak]
    - MD5Sum:b92d999369d8b6b824bc99c21201b06c [weak]
    - Filesize:2004 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`I have formatted and reinstalled Ubuntu 3x times now.`

**Comment by dschaper** [comment]
Please see the list of supported distributions and releases. Ubuntu 14 is not supported as it is too old for the required packages. https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

**Comment by dschaper** [comment]
And you can not use bionic (Ubuntu 18) repositories in trusty (Ubuntu 14).

**Comment by RL-88** [comment]
Apologies @dschaper  It is 18.04.3. I mistyped the title.
I continued tinkering after posting, and have since sorted in the last few minutes.
I manually downloaded php-sqlite3_7.2+60ubuntu1_all.deb with wget and then manually installed. 
The  automated install then completed successfully
