### ISSUE TITLE
After RPi reboot, DNS queries dosn't get resolved

### ISSUE THREAD

**Issue by Joulinar** [pi-hole/pi-hole#2898]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`PiHole is working on all interfaces after PRi reboot`

**Actual behaviour:**

`After RPi reboot, DNS queries dosn't get resolved `

**Steps to reproduce:**

```
- Reboot RPi > done
- resolve domain from Win client > not working
- SSH to RPi > working
- resolve domain on the RPi itself > working
- resolve domain from Win client > not working
- ping to RPi > working
- resolve domain from Win client > not working
- telnet on port 80 from Win Client to RPi > working
- resolve domain from Win client > not working
- opening PiHole Admin Web Interface from Win Client > working
- resolve domain from Win client > working
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`z3w7sj5y90`

**Troubleshooting undertaken, and/or other relevant information:**

`
Hi Guys, I'm using PiHole + WireGuard. To have DNS working on my mobile devices while using WireGuard, I switched on "Listen on all interfaces" within PiHole settings. Usually it works fine but I noticed some strange behavior after restarting my RPi. Once restarted, PiHole seems not working correctly as I'm not able to open web pages on my local computer because DNS resolution is not working.
`
```
nslookup google.de
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  192.168.0.11

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
`
Within PiHole log, I see request from localhost only. No other request from other devices. It seems PiHole is not accepting request from interface "eth0" as well as "wg0". To get it back working, I need to open PiHole Admin webpage via local IP address "http://192.168.0.11/admin". Immediately after opening the webpage, I can see DNS queries within the log and DNS queries getting answered again.
`
```
nslookup google.de
Server:  wpad.lan
Address:  192.168.0.11

Non-authoritative answer:
Name:    google.de
Addresses:  2a00:1450:4001:824::2003
          172.217.23.163
```
`
To check the interface I installed iptraf-ng and it seems packages are arriving on port 53 but get ignored by PiHole. Traffic from Win Client to PRi after reboot:
`
```
x UDP (59 bytes) from 192.168.0.134:61604 to 192.168.0.11:53 on eth0
x UDP (72 bytes) from 192.168.0.134:52033 to 192.168.0.11:53 on eth0 
x UDP (72 bytes) from 192.168.0.134:52033 to 192.168.0.11:53 on eth0
x UDP (72 bytes) from 192.168.0.134:52033 to 192.168.0.11:53 on eth0
x UDP (72 bytes) from 192.168.0.134:52033 to 192.168.0.11:53 on eth0
x UDP (59 bytes) from 192.168.0.134:61604 to 192.168.0.11:53 on eth0
x UDP (72 bytes) from 192.168.0.134:52033 to 192.168.0.11:53 on eth0
```

`Traffic on the RPi itself`
```
x UDP (54 bytes) from 127.0.0.1:48323 to 127.0.0.1:53 on lo 
x UDP (54 bytes) from 127.0.0.1:48323 to 127.0.0.1:53 on lo  
x UDP (54 bytes) from 192.168.0.11:14761 to 1.0.0.1:53 on eth0
x UDP (70 bytes) from 1.0.0.1:53 to 192.168.0.11:14761 on eth0
```

`And finally after accessing PiHole Admin Interface`
```
x UDP (75 bytes) from 192.168.0.134:54769 to 192.168.0.11:53 on eth0  
x UDP (71 bytes) from 192.168.0.134:54772 to 192.168.0.11:53 on eth0 
x UDP (93 bytes) from 192.168.0.11:53 to 192.168.0.134:54772 on eth0 
x UDP (58 bytes) from 192.168.0.134:54773 to 192.168.0.11:53 on eth0
x UDP (58 bytes) from 192.168.0.11:55843 to 1.0.0.1:53 on eth0
x UDP (133 bytes) from 1.0.0.1:53 to 192.168.0.11:55843 on eth0
x UDP (133 bytes) from 192.168.0.11:53 to 192.168.0.134:54773 on eth0
x UDP (58 bytes) from 192.168.0.134:54774 to 192.168.0.11:53 on eth0 
x UDP (58 bytes) from 192.168.0.11:23044 to 1.0.0.1:53 on eth0
x UDP (133 bytes) from 1.0.0.1:53 to 192.168.0.11:23044 on eth0
x UDP (58 bytes) from 192.168.0.11:53 to 192.168.0.134:54774 on eth0
x UDP (54 bytes) from 192.168.0.134:54775 to 192.168.0.11:53 on eth0 
```

**Comment by GvY85** [comment]
I have exactly the same problem but then on x86_64 platform with Debian Buster/DietPi as OS and OpenVPN.
After it's weekly update and reboot (cron job) i have to go to the pihole admin page (just the page, no need to login) before pihole starts resolving. It has been this way for at least 3-6 months. So not something from latest update

**Comment by Joulinar** [comment]
@GvY85 thx for your message. At least I'm not alone :)

In meantime guys from DietPi are helping to get closer to the issue. At least we found 2 other ways to get PiHole working after reboot.

1. you can switch Pihole to `Listen on all interfaces, permit all origins` by running `pihole -a -i all`. For me this is fixing the issue and PiHole is working right after a reboot.

2. or you can run `pihole status` manually after reboot. This seems to trigger PiHole as well.

**Comment by GvY85** [comment]
Aha, ill try:
1. you can switch Pihole to Listen on all interfaces, permit all origins by running pihole -a -i all. For me this is fixing the issue and PiHole is working right after a reboot.

Since i am behind a NAT router that only has the VPN port opened this should be safe.

**Comment by phenomeus** [comment]
i have the same problem. after every reboot I have to rerun "Pihole -r" and even have to choose "reconfigure" and enter my way through. after that its working flawless until next reboot… 

nothing above is helping me. 

running latest Pihole, unbound, wireguard, ipv6 and v4 setup

**Comment by Joulinar** [comment]
You have set PiHole to listen on all interfaces?

**Comment by phenomeus** [comment]
yes, of course. that's the strange thing about it

**Comment by phenomeus** [comment]
only localhost queries are shown after a reboot until I pihole -r and reconfigure (not touching anything) and enter my way through the process and BAM! everything is working again

but I have to re-configure DNS to unbound again and that sucks doing it over and over again

**Comment by Joulinar** [comment]
And you have issues using PiHole via WireGuard or in general in your local LAN as well?

**Comment by phenomeus** [comment]
issues also with my local lan, and I don't know what changed, it was running some weeks ago

**Comment by Joulinar** [comment]
I remember that we discover an issue, that under special circumstances eth0 was started after pihole causing issues on PiHole to discover the correct interface. Not sure if this is happening on your case as well.

see https://github.com/pi-hole/pi-hole/issues/2924
and https://github.com/MichaIng/DietPi/issues/3007

**Comment by phenomeus** [comment]
so I have to setup something to say: wait for network before everything else?

**Comment by Joulinar** [comment]
and the following did not changed anything after reboot?

1. `pihole -a -i all`
2. `pihole status`
3. access PiHole admin web site

**Comment by phenomeus** [comment]
nope, I always used 3. first but after reading here I tried 1 and 2 also. nothing. 

just Pihole -r and reconfiguration without changing anything helps

**Comment by Joulinar** [comment]
than your case is different than what we have before. Did you tried to remove PiHole completely and do a fresh clean installation?

**Comment by phenomeus** [comment]
not yet, can I backup my DHCP server config?

**Comment by Joulinar** [comment]
probably you would need to save files in

```
/etc/dnsmasq.d
/etc/pihole
```

**Comment by phenomeus** [comment]
so I did a fresh installation… besides that I forgot to backup my white and blacklist (lost that…) I gained nothing. still the same problem after a reboot

**Comment by phenomeus** [comment]
maybe its this? https://github.com/pi-hole/pi-hole/issues/2648

**Comment by phenomeus** [comment]
also maybe its `ufw` that is blocking something after reboot…

**Comment by phenomeus** [comment]
i still have the same problem, and I noticed that when I do pihole -r and the 2nd option "reconfigure" its not working UNTIL I confirm the question about "firewall rules installation" appears and its continuing to install. 

I compared the installed ufw rules before and after the reconfiguration and there where no difference. 

also I noticed that only localhost AND wireguard clients were able to be recognized and filtered after a reboot and before the reconfiguration. anything else on the local net is blocked and therefore "offline" 

(Tenda mesh cube tells me that its offline with a red LED and I also know that Tenda is calling home a lot, this is filtered with pihole so I know that its not working and I have the problem to reconfigure after reboot)

**Comment by realivanjx** [comment]
i also have this issue. dns simply not resolved both on my pi and my entire network. even issuing sudo command is taking forever because the dns is not resolved (keep giving `sudo: unable to resolve host` message). to fix, i just modified /etc/resolv.conf from:
```
nameserver 127.0.0.53
options edns0 trust-ad
```
to
```
nameserver 127.0.0.1
options edns0 trust-ad
```
and it works immediately.

**Comment by yubiuser** [comment]
@Joulinar 

Does the issue still persists with a current version of Pi-hole? If so, you can try to add `DELAY_STARTUP=5` to `/etc/pihole/pihole-FTL.conf` and run `pihole restartdns`. 
This will delay startup of Pi-hole for 5 seconds, giving interfaces some time to initialize on reboot.

**Comment by Joulinar** [comment]
2 years back I start using `Listen on all interfaces, permit all origins`. Since that time the issue was gone for me.
