### ISSUE TITLE
use Pi-hole as a way to proxy chosen domains only

### ISSUE THREAD

**Issue by hadifarnoud** [pi-hole/pi-hole#2901]
I found a service called Shecan.ir that uses DNS to proxy traffic for services that blocked access to a country. I'm guessing they reply adobe.com for example with an IP address which is a proxy server and just forward traffic.

this is a very smart way of using DNS to hide your identity or remove geo-restrictions on services like Youtube. For me though, this can help me forget about VPNs and just use a proxy for services that is blocked in my country.

Shecan is not open source and it's not a good idea to forward your traffic to someone else. I was thinking this is something Pi-hole can handle since it already has so many features needed for this. It just needs to add the third mode besides blacklist and whitelist.

I'm so into adding this feature to Pi-hole. If anyone here can help me get the ball rolling.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
