### ISSUE TITLE
Enhancement:  URL Tester within Pihole

### ISSUE THREAD

**Issue by smseidl** [pi-hole/pi-hole#2902]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
I'm having problems today where various google URLs are not working.  I wish there was a 'url' tester within PiHole Web UI that allowed a URL to be tested to confirm what PiHole is returning.  The audit/query logs don't always seem to have the details at the time it occurs (unsure if it's browser caching, or loading delay or ??... the thought is that this tester would be able to give immediate feedback on if pihole is or is not blocking the URL.

It would also be great if this could verify whitelisting is working after adding a new entry.  I know at time DNS and/or browsers need to be closed to clear cache to verify whitelisting.

**Actual behaviour:**

**Steps to reproduce:**

Get a page like this, and then take the URL into this new TEST page:
"This site can’t provide a secure connection photos.app.goo.gl sent an invalid response."

**Troubleshooting undertaken, and/or other relevant information:**
This is an Enhancement request for a new Troubleshooting/URL Test page.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
