### ISSUE TITLE
pihole logging off with no effect after unattended install

### ISSUE THREAD

**Issue by C4ne** [pi-hole/pi-hole#2904]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
pihole logging off - Should whipe logs and disable logging

**Actual behaviour:**
It flushes the logs but does not disable logging

**Steps to reproduce:**
- Fresh Debian 9 vm
- Install git, curl
- mkdir /etc/pihole
- vi setupVars.conf:
PIHOLE_INTERFACE=enp0s3
IPV4_ADDRESS=10.0.2.25/24
IPV6_ADDRESS=::/0
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
- git clone pihole
- ./basic-install --unattended
- pihole logging off (Wont shut logs)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

xnkbtdzppu

**Troubleshooting undertaken, and/or other relevant information:**
Tried to execute pihole logging off several times behind each other ... no effect.  
I reset the vm several times to post pihole installation time, which leads me every time to the same point

**Comment by Mcat12** [comment]
That command will stop logging to the `/var/log/pihole.log` file, but FTL still will record queries. If you want to stop recording queries, change the privacy level accordingly.

**Comment by C4ne** [comment]
> ommand will stop logging to

Whoopsie. Cant believe I missed that. Thanks for the quick reply and your time though!
