### ISSUE TITLE
Charts not showing after new install

### ISSUE THREAD

**Issue by JacoFourie1** [pi-hole/pi-hole#2906]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Sould see the charts

**Actual behaviour:**

No  charts are showing

**Steps to reproduce:**

On any browser the charts dont show

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

lcrt5kg19w

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

there is a Javascript error

![image](https://user-images.githubusercontent.com/26320171/64098133-636da880-cd66-11e9-879f-6c8a0bda50f9.png)

**Comment by PromoFaux** [comment]
Hi there, thanks for the report. would you mind generating a debug token so we can take a closer look? (`pihole -d` from the command line)

Thanks

**Comment by JacoFourie1** [comment]
Hi.

Is this what you are looking for ?

https://tricorder.pi-hole.net/lcrt5kg19w

Thanks for the help.

**Comment by PromoFaux** [comment]
OK, looks like you have tried to make some changes to the local web repo in `/var/www/html/admin`

The debug log indicates that the chart JS file has been adjusted.

```
*** [ DIAGNOSING ]: Web version
[i] Web: v4.3 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v4.3-0-g44aff72-dirty
[i] Status:  M img/boxed-bg.jpg
             M scripts/vendor/Chart.bundle.min.js
             M style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.svg
```

Try the following to get it back into the correct state:

```
cd /var/www/html/admin
sudo git reset --hard
```

And then refresh the page, your charts should now be working

**Comment by JacoFourie** [comment]
@PromoFaux I did not change a thing. I just ran the install script. But your suggestion fixed the problem.  Thanks so much for the help and the great software.

![image](https://user-images.githubusercontent.com/17771641/64113733-557e4e80-cd8b-11e9-83d0-b10e19ad5f62.png)

**Comment by PromoFaux** [comment]
¯\\_(ツ)_/¯

In any case, glad that sorted it!

**Comment by JacoFourie1** [comment]
Ooops I posted with the wrong browser. Issue is closed
