### ISSUE TITLE
pihole fails to restartdns and displays no error message when interface changes

### ISSUE THREAD

**Issue by kaysond** [pi-hole/pi-hole#2907]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
pihole fails to start (specifically, restartdns fails) and displays an error message or creates a log entry indicating that the service could not be restarted and why

**Actual behaviour:**
pihole fails to start and restartdns, but no error messages are shown or log entries generated

**Steps to reproduce:**
* Change `PIHOLE_INTERFACE=<interface>` in `/etc/pihole/setupVars.conf` to something that does not exist
* Change `interface=<interface>` in `/etc/dnsmasq.d/01-pihole.conf` to something that does not exist
* Restart

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/p5mjt7y9ni

**Troubleshooting undertaken, and/or other relevant information:**
I'm guessing its not all that common that people install new NICs... but anyways...

There are two issues: the first is that if dnsmasq fails to start for whatever reason (in my case, the interface no longer existed because its name changed upon installing a new NIC), then `pihole restartdns` doesn't show any error message or create log entries. It says it successfully restarted, but if you do a subsequent `pihole status` you see that FTL still hasn't started. There was nothing in any of the pihole logs either. When I dug through syslog, I only found an entry at boot when the `pihole-FTL` service was initially started, and then I found that dnsmasq had failed to start.

The second issue is that the `restartdns` command didn't work. 

I think the problem here is that the `pihole-FTL` service status was `active (exited)` because the service script finished, but dnsmasq failed to start. So the `pihole` script checks for `pidof pihole-FTL`, finds none, and does a `service pihole-FTL start`, but that doesn't do anything because the service didn't fail.

Manually doing `service pihole-FTL restart` (after fixing the interface setting) fixed the problem.

It would've been nice if pihole told me that dnsmasq failed to start and why!

**Comment by DL6ER** [comment]
> pihole fails to start and restartdns, but no error messages are shown or log entries generated

> if dnsmasq fails to start for whatever reason (in my case, the interface no longer existed because its name changed upon installing a new NIC), then pihole restartdns doesn't show any error message or create log entries.

This should have been logged to `/var/log/pihole.log`

> 

I did this and only saw the following in my log file:

> Sep  2 21:46:01 dnsmasq[5254]: warning: interface non-existing does not currently exist

pihole-FTL was still running happily. What is the exact content of your `01-pihole.conf`?

---

The second issue you mentioned if known and actually a rather new issue only coming up on fairly recent operating systems (Ubuntu 18.04+, Raspbian/Debian Buster+) and comes from changes in how `systemd` likes to interpret our `sysV` script. A bug fix for this is work in progress.

**Comment by kaysond** [comment]
> This should have been logged to `/var/log/pihole.log`
> 
> > 
> 
> I did this and only saw the following in my log file:

I checked my `/var/log/pihole.log` and didn't see any warnings at all



> pihole-FTL was still running happily. What is the exact content of your `01-pihole.conf`?

```
addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=2

log-async

# If a DHCP client claims that its name is "wpad", ignore that.
# This fixes a security hole. see CERT Vulnerability VU#598349
dhcp-name-match=set:wpad-ignore,wpad
dhcp-ignore-names=tag:wpad-ignore
server=1.1.1.1
server=1.0.0.1
domain-needed
bogus-priv
dnssec
trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

interface=enp2s0
server=/nub.local/192.168.1.1
server=/1.168.192.in-addr.arpa/192.168.1.1
```

**Comment by Mcat12** [comment]
This will likely be fixed by #2900

**Comment by yubiuser** [comment]
Do the issues still persists? A lot of patches have been applied to Pi-hole in the mean time

**Comment by kaysond** [comment]
Honestly, I haven't used pi-hole in a while. Should be fairly easy for someone to reproduce this in a VM, though
