### ISSUE TITLE
RegEx blocking not working

### ISSUE THREAD

**Issue by MeisterLuchs** [pi-hole/pi-hole#2908]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`getting several googlevideo domains blocked after inserting the following RegEx string into /etc/pihole/regex.list: ^r\d{1,2}---sn-[a-zA-Z0-9]*n[A-Za-z0-9]{2}\.googlevideo\.com$`

**Actual behaviour:**

`no googlevideo domain gets blocked as you see in the Query log: `![query_log](https://user-images.githubusercontent.com/37845513/64129899-3d282700-cdbf-11e9-89ef-1d93e73530df.png)

**Steps to reproduce:**

1. Open /etc/pihole/regex.list and insert the following: `^r\d{1,2}---sn-[a-zA-Z0-9]*n[A-Za-z0-9]{2}\.googlevideo\.com$`
2. Save the file.
3. Restart the pihole-FTL service.
4. Watch a YouTube video.
5. Look at the Query log and search for `googlevideo`.
6. Verify the RegEx string and that the domain matches it via [regex101.com](https://regex101.com/).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`l113qkjlwv`

**Troubleshooting undertaken, and/or other relevant information:**

`Trying without ^ at the beginning and $ at the end didn't change the outcome.`

**Comment by DL6ER** [comment]
Note that there are multiple flavours of Regex available. After some discussions, we decided to implement POSIX Extended Regular Expressions (also known as ERE and used by many popular tools such as `egrep`). https://regex101.com/ does not seem to be able to test against 

See https://docs.pi-hole.net/ftldns/regex/overview/ for further details on our implementation. The tutorial gives a rather extensive overview over what is possible.

**Comment by MeisterLuchs** [comment]
Ah, good to know. Now it works. Thank you.

**Comment by p1r473** [comment]
Try
```
^r([0-9]+)(---|\.)sn([a-z-0-9])+\.googlevideo.com
```
It works with
```
r4---sn-vgqs7nez.googlevideo.com 
r4.sn-vgqs7nez.googlevideo.com 
r17---sn-vgqsenes.googlevideo.com 
r2---sn-vgqs7n7k.googlevideo.com 
r1---sn-vgqsen7z.googlevideo.com 
r1.sn-vgqsen7z.googlevideo.com 
r20---sn-vgqs7ne7.googlevideo.com 
r20.sn-vgqs7ne7.googlevideo.com
```

**Comment by ThisNameWasTaken** [comment]
> Ah, good to know. Now it works. Thank you.

What is the fix exactly? I am facing a similar issue, I tried a bunch of regexes and I can't get it to work. Also I cannot understand why using `googlevideo\.com` won't work, because the dock say the following:

```partial match. Without anchors, a text may appear anywhere in the domain. This matches some.domain.com, domain.com and verylongdomain.com and more```

So even if I were to type just `googlevideo`, it should catch any domain that has `googlevideo` in it.

**Comment by jfb-pihole** [comment]
You are replying to a thread almost three years old.  Please visit our discourse documentation for a good regex tutorial:

https://docs.pi-hole.net/regex/tutorial/
