### ISSUE TITLE
how to remove this thing?

### ISSUE THREAD

**Issue by kppomzh** [pi-hole/pi-hole#2911]
After install this thing,I con't use ssh and samba server.Also can not ping to my service.
On docs.pi-hole.com,it writes "Easy-to-install";but not-Easy-to-uninstall?

[kppom@kppom-NAS ~]$ bash '/etc/.pihole/automated install/uninstall.sh'
bash: /etc/.pihole/automated install/uninstall.sh: No such file or directory

**Comment by kppomzh** [comment]
My system is Fedora30

**Comment by turing-complet** [comment]
Might be in `/opt/pihole`? Just guessing based on the source for the [install location](https://github.com/pi-hole/pi-hole/blob/1a741f696eec2ee148fc59bc0dc98e862475e6ef/automated%20install/basic-install.sh#L66) and the [uninstall script](https://github.com/pi-hole/pi-hole/blob/1a741f696eec2ee148fc59bc0dc98e862475e6ef/automated%20install/basic-install.sh#L1338). Anyway, hard to say without knowing which install process you used. I'd also guess that you could fix these issues with some configuration tweaks, if you are inclined.

**Comment by kppomzh** [comment]
> Might be in `/opt/pihole`? Just guessing based on the source for the [install location](https://github.com/pi-hole/pi-hole/blob/1a741f696eec2ee148fc59bc0dc98e862475e6ef/automated%20install/basic-install.sh#L66) and the [uninstall script](https://github.com/pi-hole/pi-hole/blob/1a741f696eec2ee148fc59bc0dc98e862475e6ef/automated%20install/basic-install.sh#L1338). Anyway, hard to say without knowing which install process you used. I'd also guess that you could fix these issues with some configuration tweaks, if you are inclined.

ummm,I also use find -name to check which dir maybe pi-hole's install dir.But all efforts have failed.Except /etc/pihole,nothing has be found in my linux.

I only run "One-Step Install" like 'curl -sSL https://install.pi-hole.net | bash'

**Comment by PromoFaux** [comment]
@kppomzh , the scripts should be in `/opt/pihole` after a successful install. `pihole uninstall` is the command to uninstall.

Did the install complete fully? If your `find` command is not finding the files in the `/opt/pihole` directory, it seems like it did not...

>My system is Fedora30

We don't support Fedora30, only 28 and 29 https://docs.pi-hole.net/main/prerequesites/

**Comment by kppomzh** [comment]
> @kppomzh , the scripts should be in `/opt/pihole` after a successful install. `pihole uninstall` is the command to uninstall.
> 
> Did the install complete fully? If your `find` command is not finding the files in the `/opt/pihole` directory, it seems like it did not...
> 
> > My system is Fedora30
> 
> We don't support Fedora30, only 28 and 29 https://docs.pi-hole.net/main/prerequesites/

After go home,I'll uninstall again with your method.
But Fedora30 has been releaseed about half a year……
