### ISSUE TITLE
Add possibility to add DNS aliases

### ISSUE THREAD

**Issue by CodingSpiderFox** [pi-hole/pi-hole#2913]
Sometimes when I don't pay attention, I type drive.google.de instead of drive.google.com in my browser. 

As drive.google.de doesn't lead anywhere, I wan't to save time correcting the URL and I want to be able to add that DNS name in pihole so that it always points to the current IP of drive.google.com

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
