### ISSUE TITLE
Incorrect "pihole disable" syntax disables Pihole indefinitely

### ISSUE THREAD

**Issue by crsmi** [pi-hole/pi-hole#2917]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
7

---
**Expected behaviour:**

Using incorrect syntax for `pihole disable *` should return an error message and leave pihole enabled.

**Actual behaviour:**

Incorrect syntax (e.g. `pihole disable 30`) returns an error message but also disables pihole. Trying to disable again (with or without correct syntax) will overwrite the backup list files and cause pihole to be disabled until `pihole -g` is run to rebuild the lists.

**Steps to reproduce:**

pihole disable 30 # Note no 's' after '30'
ls /etc/pihole

Notice that 'gravity.list.bck' exists and 'gravity.list' does not.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

5mlr7wwni2

**Troubleshooting undertaken, and/or other relevant information:**

If the remaining `gravity.list.bck` file is wiped out, `pihole -g` needs to be run to rebuild the lists. Running `pihole enable` before trying another disable command can fix this.

**Comment by dschaper** [comment]
It looks like the template didn't get completely filled out. Can you edit the post and add the details explaining what you are seeing?

**Comment by crsmi** [comment]
I belive this explains #2661 and is semi-related to #2573

**Comment by crsmi** [comment]
This could be fixed by restoring the backup lists in:

https://github.com/pi-hole/pi-hole/blob/master/pihole#L188
```shell
if [[ ${error} == true ]];then
    echo -e "  ${COL_LIGHT_RED}Unknown format for delayed reactivation of the blocking!${COL_NC}"
    echo -e "  Try 'pihole disable --help' for more information."
    exit 1
fi
```

or by checking syntax before actually moving the lists to their .bck backups.

I think the first option may be fine, but the second option may be a more robust solution.

**Comment by crsmi** [comment]
What do you think? I'm new here, but would be interesting in implementing a fix if that would be okay.

**Comment by DL6ER** [comment]
Thanks for your report and your offer to fix the issue. In `development`, this seems already to be fixed. Please check out https://github.com/pi-hole/pi-hole/blob/development/pihole#L137-L209

With Pi-hole v5.0 we will go away from list files and handle everything in a SQLite3 database. Blocking yes/no will solely be controlled by setting
```
BLOCKING_ENABLED=true/false
```
in `/etc/pihole/setupVars.conf`. Whenever our DNS server FTL receives a `RELOAD` command, it will check this config line option to decide whether to block queries or not.

**Comment by crsmi** [comment]
Okay, thanks for the info!

Will 5.0 be the next released version?

**Comment by dschaper** [comment]
There will be at least one bug fix for version 4 and more if required before version 5 is released.

**Comment by yubiuser** [comment]
Does the issue still persists? A lot of fixes have been applied since the report was opened
