### ISSUE TITLE
Suddenly PiHole FTL Goes offline

### ISSUE THREAD

**Issue by varunsridharan** [pi-hole/pi-hole#2919]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`PIHOLE FTL should not go offline`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

I installed below softwares

1. Pi-hole as All-Around DNS Solution 
2. Configuring DNS-Over-HTTPS on Pi-hole 
3. Configuring NGINX for Pi-hole 

**Debug token provided by https://tricorder.pi-hole.net/nspheiiqcl**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`-`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
`nginx` is not supported. You have also made changes to the permissions of the HTML files.

**Comment by varunsridharan** [comment]
@dschaper i am new to this. i was checking docs to make this dns work with "Android PrivateDNS" which work for me now after installing all those 3. now i am not sure why this issue occurs

**Comment by dschaper** [comment]
This isn't a bug, this is an unsupported configuration. Please visit https://discourse.pi-hole.net for community support on using `nginx` instead of the supported `lighttpd` web front ends.
