### ISSUE TITLE
Enable local IP bypass

### ISSUE THREAD

**Issue by mwolfaardt** [pi-hole/pi-hole#2921]
It would be great if you could select what devices/ IP address to bypass pi-hole. I have some devices on the network that want to make use of ads

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
