### ISSUE TITLE
Latest core update doesn't tell web interface it is up to date

### ISSUE THREAD

**Issue by nol166** [pi-hole/pi-hole#2925]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4
---
**Expected behavior:**

pihole web interface should display `4.3.2` for pihole major version

**Actual behavior:**

instead shows `4.3.1`

**Steps to reproduce:**

1. log into pihole via ssh
2. run `pihole -up` and allow script to finish
3. log into web-interface and notice version number and "update available" text

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`e3e4i8a8yd`

**Troubleshooting undertaken, and/or other relevant information:**

`1. Double checked that pihole -up was ran twice and uploaded debug token`

**Comment by dschaper** [comment]
What does `pihole -v` show?

**Comment by nol166** [comment]
`Pi-hole version is v4.3.1-40-ge41c4b5 (Latest: v4.3.2)` @dschaper

**Comment by dschaper** [comment]
It's just a tag issue. 

```bash
cd /etc/.pihole
sudo git tag -d v4.3.2
sudo git pull --tags
```

**Comment by nol166** [comment]
kk I will run that, ty

**Comment by nol166** [comment]
@dschaper after running that both the update script and web interface still seem to think it is out of date

**Comment by dschaper** [comment]
Please share the output from `pihole -v` again.

**Comment by nol166** [comment]
`Pi-hole version is v4.3.2 (Latest: v4.3.2)` looks like it is just the web interface. I will try clearing my web cache

**Comment by dschaper** [comment]
Clear the cache on the web browser. It doesn't check the version on every page load.

**Comment by nol166** [comment]
@dschaper All good now 👍
