### ISSUE TITLE
sudo in pihole cmd before parsing commandline

### ISSUE THREAD

**Issue by lduesing** [pi-hole/pi-hole#2927]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`sudo only when rights are being used`

**Actual behaviour:**

`Asks for sudo even for help screen`

**Steps to reproduce:**

`pihole -h`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`n/a`

**Troubleshooting undertaken, and/or other relevant information:**

`n/a`

**Comment by dschaper** [comment]
The `pihole` command does require elevated priv's because of it's function. I do agree that you shouldn't need `sudo` for the help command but reworking everything for just one exception is kind of low on the priority list. Thanks for the issue though and I'll keep it open but mark it as a feature request.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.10
