### ISSUE TITLE
PiHole update Removes lighttpd config

### ISSUE THREAD

**Issue by Dergonic** [pi-hole/pi-hole#2928]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?: 0 :D **
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
"pihole -up" does not change lighttpd config

**Actual behaviour:**
After a 'pihole -up' (To v4.3.2) the specified lighttpd port config have 'vanished'

I had a specific port defined in the '/etc/lighttpd/lighttpd.conf' ('server.port = 8084'). 
After the 'pihole -up', config went back to 'server.port = 80'. 

I changed it back to 8084 and all was ok (Issue solved) but maybe the update script is broken.
I have no idea if the whole lighttpd config have been changed as all the other params in my home server are the default one.

Previous updates of PiHole did not do this issue. They went ok. Only the last one failed.

**Steps to reproduce:**
Did not tried. I have bno idea how I can revert back to previous version an try the upgrade again. 
If someone can show me a procedure, I'll be pleased to do it and try to reproduce.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

wvmecb518f

**Troubleshooting undertaken, and/or other relevant information:**
About setup :
- PiHole running on a Intel Nuc on Ubuntu (fully updated)
- Using HomeAssistant (Hass.io) on port 80 via apache2 (PS : Not using Pihole pluggin for home assistant, I'm using the normal PiHole setup) 
- Pihole is (should be) on port 8084

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
This is the behavior that has always happened. If you read the file itself you will see that it warns users to not edit the file as it will be overwritten. 

https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L11

**Comment by Dergonic** [comment]
Ok, indeed, my bad
I'll have a look on moving this config to the recommanded external.conf

Strange it did not happened previously. 

Thanks for your help and sorry for my mistakes.
