### ISSUE TITLE
Chronometer displays RTNETLINK error if user doesn't have IPv6

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#293]
If a user installs with both IPv4 and IPv6 enabled for ad blocking, and they don't have an IPv6 route to get out to the internet, then `chronometer.sh` displays an `RTNETLINK` error where the IP address should be. (The `ip -6 route` call comes back with an error.) Also `/etc/pihole/.useIPv6` survives a re-install.

**Comment by Mcat12** [comment]
The .useIPv6 issue is fixed with PR #306
