### ISSUE TITLE
lighttpd fails to start after RPi reboot when /var/log on tmpfs

### ISSUE THREAD

**Issue by dvbavel** [pi-hole/pi-hole#2931]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`After restart of Rpi with /var/log on tmpfs lighttpd should start`

**Actual behaviour:**

```lighttpd fails to start with: 
/usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
2019-09-17 06:28:46: (server.c.750) opening errorlog '/var/log/lighttpd/error.log' failed: No such file or directory
2019-09-17 06:28:46: (server.c.1461) Opening errorlog failed. Going down.
daemonized server failed to start; check error log for details
```

**Steps to reproduce:**

```
add:
none            /var/log            tmpfs   size=1M,noatime    0   0 to /etc/fstab
Reboot RPi
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`n/a`

**Troubleshooting undertaken, and/or other relevant information:**

```
mkdir -p /var/log/lighttpd
touch /var/log/lighttpd/error.log
chown -R www-data:www-data /var/log/lighttpd/
systemctl start lighttpd
```

**Comment by dschaper** [comment]
This isn't an issue with Pi-hole, it's an issue with `lighttpd` not creating the log file when using a temporary filesystem. If you want to use tmpfs for `/var/log` I would suggest looking in to automating the process of creating that file. Perhaps systemd's tmpfiles https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles.html

**Comment by dvbavel** [comment]
Sure Dan, also fully agree it’s not an PI-Hole issue, but an issue with the Webserver you’re using for PI-Hole. I could think of tons of solutions to make it work for me automatically - That’s just a minute work. But I hoped we could make an solution that would ensure PI-Hole would automatically start with all its components in most if not all cases :-) if this is an wont do for you, feel free to take this one as an FYI and close the report.

**Comment by dschaper** [comment]
If it was an issue that occurred on a stock or near stock Pi-hole installation then I would be more open to options to modify Pi-hole. But changing logging to an ephemeral filesystem that breaks a dependent package with tons of solutions seems like something that could be better solved elsewhere. Adding more instructions to the sysv or systemd init process to include logic to create a file that may or may not already exist and may or may not be needed as the user might not have installed `lighttpd` just seems like a situation we'd like to avoid.

**Comment by dvbavel** [comment]
Sure - closed
