### ISSUE TITLE
configure cache-size permanently and update-safe

### ISSUE THREAD

**Issue by Novaal** [pi-hole/pi-hole#2936]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{2}`

---
**Expected behaviour:**

`CACHE_SIZE in /etc/pihole/setupVars.conf is populated to cache-size in /etc/dnsmasq.d/01-pihole.conf`

**Actual behaviour:**

`It's not possible to configure cache-size in /etc/dnsmasq.d/01-pihole.conf permanently and update-safe.`

**Steps to reproduce:**

`Change cache-size in /etc/dnsmasq.d/01-pihole.conf and then update to a newer version of pihole.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`n/a`

**Troubleshooting undertaken, and/or other relevant information:**

`n/a`

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
