### ISSUE TITLE
Pihole update issue FTL-engine not installed

### ISSUE THREAD

**Issue by sonofice** [pi-hole/pi-hole#2940]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

What I expect to see is that my pihole updates when I use the command pihole -up 

**Actual behaviour:**

My pihole doesn't want to update when I use the command pihole -up. It says ftl engine not installed while it is installed and running 
(I checked that using the command "sudo service pihole-FTL status")

**Steps to reproduce:**

Not sure if it is replicable, but what I did was the pihole update command (pihole -up)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/bwxl9tatug

**Troubleshooting undertaken, and/or other relevant information:**

I followed some commands that were posting in this thread:
https://github.com/pi-hole/pi-hole/issues/1433

To be exact;
- sudo apt-get update
- sudo apt-get -y upgrade
- sudo apt-get -y dist-upgrade

Outside the thread:
- simple restarting (pihole restartdns, restarting the raspberry pi)
- pihole -r

> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
Regardless of what the command `pihole -up` displays from your debug log i can see that you are on the latest Release of FTL.  

it would seem you are a release behind on the other 2 so I would suggest the following

1.  `sudo nano /etc/resolv.conf`
2.  Change `127.0.0.1` to any upstream DNS (i like 9.9.9.9)
3.  exit nano and save
4.  try `pihole -up again`

**Comment by sonofice** [comment]
It worked and Pihole is now on the latest release on all 3
Thank you for your help!
