### ISSUE TITLE
Manjaro not supported

### ISSUE THREAD

**Issue by LodeVanB** [pi-hole/pi-hole#2941]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

**automated install]$ sudo bash basic-install.sh

**Actual behaviour:

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] OS distribution not supported

**Comment by dschaper** [comment]
This is correct.

**Comment by technicalpyro** [comment]
please refer to [this ](https://docs.pi-hole.net/main/prerequesites/) for our list of Supported OS's
