### ISSUE TITLE
api.php error

### ISSUE THREAD

**Issue by molarszbt18** [pi-hole/pi-hole#2942]
Hello,

I am new to Pi-hole and testing it out.  Upon installing and enabling it I am getting an error or two.

**Dashboard** - Just spins, no data
**Query log** - Uncaught error: Call to undefined function json_encode() /var/www/html/admin/api.php.139
**Long Term Data - Query log** - Uncaught Error: Class SQLite3' not found in /var/www/html/admin/api_db.php:71
**Networking** - Same error as above with SQLite3

Pi-hole Version v4.3.2 Web Interface Version v4.3.2 FTL Version v4.3.1 D

Ran some common checks:

curl -i http://pi.hole/admin/api.php?summaryHTTP/1.1 200 OK
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-Powered-By: PHP/7.2.19-0ubuntu0.18.04.2
Content-type: application/json
Set-Cookie: PHPSESSID=5ce9de947315a5910e02149fe20eb69b; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 215
Date: Wed, 25 Sep 2019 01:57:25 GMT
Server: lighttpd/1.4.45

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/admin/api.php</b> on line <b>139</b><br />

sudo cat /var/log/lighttpd/error.log
2019-09-23 00:30:22: (log.c.217) server started 
2019-09-23 01:24:48: (log.c.217) server started 
2019-09-23 10:51:01: (log.c.217) server started 
2019-09-23 10:56:32: (log.c.217) server started 
2019-09-23 11:13:11: (server.c.1828) server stopped by UID = 0 PID = 1 
2019-09-23 11:13:12: (log.c.217) server started 
2019-09-23 11:05:32: (log.c.217) server started 
2019-09-23 11:11:14: (log.c.217) server started 

Thoughts?

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [y] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [y] The issue I am reporting can be *replicated*.
- [y] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
The SQLite and JSON libraries are not properly installed. See this thread: https://discourse.pi-hole.net/t/sqlite3-and-json-encode-fault/18325

**Comment by molarszbt18** [comment]
> The SQLite and JSON libraries are not properly installed. See this thread: https://discourse.pi-hole.net/t/sqlite3-and-json-encode-fault/18325
@Mcat12 
I tried but see this.

sudo apt purge php7.0-json php7.0-sqlite3
[sudo] password for administrator: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0-json
E: Couldn't find any package by glob 'php7.0-json'
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-sqlite3
E: Couldn't find any package by glob 'php7.0-sqlite3'
E: Couldn't find any package by regex 'php7.0-sqlite3'


sudo apt install php7.0-json php7.0-sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0-json
E: Couldn't find any package by glob 'php7.0-json'
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-sqlite3
E: Couldn't find any package by glob 'php7.0-sqlite3'
E: Couldn't find any package by regex 'php7.0-sqlite3'

**sudo apt install --reinstall php7.0-cli php7.0-cgi sudo phpenmod json sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package php7.0-cgi
E: Couldn't find any package by glob 'php7.0-cgi'
E: Couldn't find any package by regex 'php7.0-cgi'
E: Unable to locate package phpenmod
E: Unable to locate package json

**Comment by Mcat12** [comment]
Without a debug token and further information (as was requested in the issue template), we cannot continue debugging this issue. Please fill out the issue template completely.

**Comment by molarszbt18** [comment]
@Mcat12 sorry I thought I did that.  I just ran it again as I believe it is deleted after a day or two.

Your debug token is: https://tricorder.pi-hole.net/sut6hujloz

Expected behaviour:

I should see charts and graphs and do not.

Steps to reproduce:
Installed Ubuntu in a VM, and then installed pi-hole.  Went to admin site, logged in and issues appeared.

Debug token provided by uploading pihole -d log:
sut6hujloz

Troubleshooting undertaken, and/or other relevant information:
Ran updates, rebooted, reinstalled.

**Comment by Mcat12** [comment]
@molarszbt18 Did you find a solution already?

**Comment by molarszbt18** [comment]
@Mcat12 I just loaded up a new VM and went from CentOS to Fedora.  No issues.

**Comment by jimbair** [comment]
This is the result of the package php-json not being installed, the fix below (at least for CentOS 8.1):

```
sudo dnf install php-json
sudo systemctl restart lighttpd
```

**Comment by jimbair** [comment]
@Mcat12 is this something we can try to add into the installer for CentOS 8? I figure asking here is better than opening a new issue.

**Comment by americanhanko** [comment]
Thanks, @jimbair — I'm running Oracle Linux 7.7 and was having the same issue. Looking at the admin console, it looks like a malfunctioning dashboard and "failure to load" errors when going to "Query Log." But after looking at the Javascript console in Chrome, then taking a look at `/var/log/lighttpd/error.log`:

```
FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139
```

Installing *php-json* and then restarting *lighttpd* resolved the issue:

```
sudo yum install php-json
sudo systemctl restart lighttpd
```

That did the trick:

```
$ sudo tailf /var/log/lighttpd/error.log
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: #0 {main}
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/api.php on line 139
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr: #0 {main}
2020-04-05 18:48:10: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/api.php on line 139
2020-04-05 18:49:32: (server.c.2091) server stopped by UID = 0 PID = 1
2020-04-05 18:49:33: (server.c.1521) server started (lighttpd/1.4.54)
```
