### ISSUE TITLE
iOS not supported

### ISSUE THREAD

**Issue by nutterthanos** [pi-hole/pi-hole#2943]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

**Actual behaviour:**

`{[✓] Root user check                      
                                           
        .;;,.                              
        .ccccc:,.                          
         :cccclll:.      ..,,              
          :ccccclll.   ;ooodc              
           'ccll:;ll .oooodc               
             .;cll.;;looo:.                
                 .. ','.                   
                .',,,,,,'.                 
              .',,,,,,,,,,.                
            .',,,,,,,,,,,,....             
          ....''',,,,,,,'.......           
        .........  ....  .........         
        ..........      ..........         
        ..........      ..........         
        .........  ....  .........         
          ........,,,,,,,'......           
            ....',,,,,,,,,,,,.             
               .',,,,,,,,,'.               
                .',,,,,,'.                 
                  ..'''.                   
                                           
  [✓] Disk space check                     
  [i] Update local cache of available packag  [✓] Update local cache of available packages                                         
                                           
  [i] Checking apt-get for upgraded packages  [✗] Checking apt-get for upgraded packages                                           
      Kernel update detected. If the install fails, please reboot and try again        
  [i] Installer Dependency checks...       
  [i] Checking for apt-utils (will be instal  [i] Checking for dialog (will be installed  [i] Checking for debconf (will be installe  [i] Checking for dhcpcd5 (will be installe  [i] Checking for git (will be installed) 
  [i] Checking for iproute (will be installe  [i] Checking for whiptail (will be installed}`

**Comment by dschaper** [comment]
This is correct. Please see https://docs.pi-hole.net/main/prerequesites/ for supported platforms.

**Comment by nutterthanos** [comment]
No I was wondering if we could support it.

**Comment by nutterthanos** [comment]
anyway the package manager is apt when jailbroken

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
