### ISSUE TITLE
piholeDebug.sh wrong bind analysis

### ISSUE THREAD

**Issue by Somebodyisnobody** [pi-hole/pi-hole#2945]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 6-7

---
**Current behaviour:**

Following code in the `pihole -d` command doesn't match the description and is in result unusable to make a safe analysis:
https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/Scripts/piholeDebug.sh#L545-L570

Currently `ip -"${protocol}" addr show dev "${PIHOLE_INTERFACE}" | awk -F ' ' '{ for(i=1;i<=NF;i++) if ($i ~ '/^inet/') print $(i+1) }'` gives you just the output of available IP-addresses on a specified interface. But the log says these addresses are bound to pihole-FTL.
`"${TICK} IPv${protocol} address(es) bound to the ${PIHOLE_INTERFACE} interface:"`

I read this as the addresses that are also bound to FTL, cause that's the only reason for the data collection. Thats wrong in a case when you get IP addresses after pihole-FTL has already been started **and** pihole-FTL isn't bound to `::` or `0.0.0.0` but on the addresses that were available when the daemon started.

**Expected behaviour:**
Solution A:
Use something like `netstat -tulpen | grep :53` instead or supplementary

Solution B:
Rename line 558 to:
`"${TICK} IPv${protocol} address(es) available to the ${PIHOLE_INTERFACE} interface:"`

Solution C:
Make sure that pihole-FTL is bound to `::` and `0.0.0.0` and warn if it's not.

-> The Problem in linked discussion was an Ubuntu 18.04LTS Server installation where Ubuntu creates a lxd-file in /etc/dnsmasq.d that causes that FTL will not bind to `::` and `0.0.0.0. Pihole doesn't check this.

**Steps to reproduce:**

1. Make sure that FTL isn't bound to `::` or `0.0.0.0` and running
2. run `netstat -tulpen | grep :53` and compare with `pihole -d`
3. add an IP address (tested with DHCPv6) manually
4. run `netstat -tulpen | grep :53` and compare with `pihole -d` again
5. optionally test DNS on the added IP address

**Troubleshooting undertaken, and/or other relevant information:**

Workarround: cron every 1 hour with `pihole restartdns`

Link to discussion: https://discourse.pi-hole.net/t/pihole-bindet-nicht-alle-adressen/23967 (german)

**Comment by dschaper** [comment]
The debugger is just a rough view of the state of the system. It doesn't affect any of the operations so I'm not seeing why there would need to be a workaround or a need to restart any of the services because of something in the debug script? @DL6ER Am I missing something?

**Comment by DL6ER** [comment]
It's about rephrasing some of the output only, I guess. I agree that the debugger should not touch the system in any way. And restarting something is definitely touching something.

**Comment by yubiuser** [comment]
Closing this issue. 
The consensus opinion in the PR changing the wording (https://github.com/pi-hole/pi-hole/pull/4273) was that `bond` adequately` reflect the current behavior.
