### ISSUE TITLE
pihole doesn't return DNS properly for some domain names

### ISSUE THREAD

**Issue by ewosborne** [pi-hole/pi-hole#2947]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

Some domain name lookups do not work against pi-hole but work against other servers.  This appears to be when looking up the root domain, e.g.

`$ nslookup
> segment.com
Server:         192.168.1.95
Address:        192.168.1.95#53

Name:   segment.com
Address: 0.0.0.0
Name:   segment.com
Address: ::
`

**Actual behaviour:**
`> server 9.9.9.9
Default server: 9.9.9.9
Address: 9.9.9.9#53
> segment.com
Server:         9.9.9.9
Address:        9.9.9.9#53

Non-authoritative answer:
Name:   segment.com
Address: 54.71.35.108
Name:   segment.com
Address: 52.42.252.3`
**Steps to reproduce:**

This is pretty consistent for me.  Not all domain names fail to resolve, but ones which do fail, fail consistently.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/rms078fmaf`

**Troubleshooting undertaken, and/or other relevant information:**

I am not familiar enough with DNS to fix this. I'm decent with Linux and pretty good with tcpdump, so am happy to gather any additional requested information.

**Comment by DL6ER** [comment]
Please check with
```
pihole -q -exact segment.com
```
if the domain you're querying is routinely blocked by Pi-hole.

**Comment by ewosborne** [comment]
The domain segment.com is blocked:
pi@pi:~ $ pihole -q -exact segment.com
 Exact match for segment.com found in:
   list.6.hosts-file.net.domains
and I can see that nslookup off of pihole returns 0.0.0.0:
eric@eric-surface:~$ nslookup
> server 192.168.1.95
Default server: 192.168.1.95
Address: 192.168.1.95#53
> segment.com
Server:         192.168.1.95
Address:        192.168.1.95#53

Name:   segment.com
Address: 0.0.0.0
Name:   segment.com
Address: ::
> www.segment.com
Server:         192.168.1.95
Address:        192.168.1.95#53

Name:   www.segment.com
Address: 0.0.0.0
Name:   www.segment.com
Address: ::
so I should have paid better attention to whether it was blocked. My bad, sorry about that.

I had an example of one which wasn't blocked and which still failed, but I tried 'pihole restartdns' and now it works.  So I have no clue what happened there.  It was returning  'Can't find <domain>: No answer' rather than 0.0.0.0, but after a restartdns, it's all good.
I will close this issue and open a new one if I can find a non-blocked domain where a restart doesn't fix it.thanks!
