### ISSUE TITLE
Pihole Won't Disable. Continues to resolve. 

### ISSUE THREAD

**Issue by justinamcafee** [pi-hole/pi-hole#2949]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Pihole ceases to respond to DNS requests.

**Actual behaviour:**

Pihole continues to respond to DNS requests. 

**Steps to reproduce:**
Choose "Disable", select any time frame. Refresh query log. Log continues to grow and DNS works without issue. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

14d1y0g1vq

**Troubleshooting undertaken, and/or other relevant information:**

**Comment by DL6ER** [comment]
This is not what "disable" means in this context.

Enabled = Block domains that are on the blocking lists, resolve other domains
Disabled = Resolve all domains

You see that enabled/disabled corresponds to whether or not queries should be blocked. There is no way to stop Pi-hole responding to incoming requests (why should there be this option?).

**Comment by justinamcafee** [comment]
In this case, because I'm attempting to test failover pihole configurations in this case. 

I can think of other times when it would be useful to stop a resolver from resolving, but this explanation suffices.
