### ISSUE TITLE
Pi-Hole Admin Console counters reset at GMT 00:00 when Pi is set for EST

### ISSUE THREAD

**Issue by mfmjos** [pi-hole/pi-hole#295]
I've only been using Pi-Hole for a couple of days. I noticed this evening that the Admin Console counters reset at about 00:00 GMT. My Pi-Hole is showing the current timezone as EST, and the pihole.log files is recording the local time. I would like to have the counters reset at midnight local time.

Thanks for a great piece of work!

**Comment by mfmjos** [comment]
Hmmm, actually looking through the logs now, it appears that the pihole.log file starts about that time. Perhaps, it simply rotated and the count is accurate. Any idea why it would have rotated at ~8:00 EST?

**Comment by PromoFaux** [comment]
Hmm. What output does running `date` give you?

**Comment by mfmjos** [comment]
Date reports the correct local time. Note my last message; there may have been some log rotation that caused it. What process rotates the pihole.log file?

**Comment by PromoFaux** [comment]
Right, we may be a little out of sync terminology wise.. by rotate, am I understanding that correctly as the log being flushed/cleared out? 

If so, there is a cron job (found in `/etc/cron.d/pihole`) which does that once a day at **23:58**

```bash
# Pi-hole: Flush the log daily at 11:58 so it doesn't get out of control
#          Stats will be viewable in the Web interface thanks to the cron job above
58 23   * * *   root    /usr/local/bin/piholeLogFlush.sh
```

which run's  `truncate -s 0 /var/log/pihole.log`

**Comment by mfmjos** [comment]
Yep, you're right. It's not really rotating, there are no old files. But yes, I meant the process that purges the file. I will keep an eye on it this evening and see if it does it again.  

Thanks!

**Comment by DonLexos** [comment]
Is there any update on if this is still an issue?

**Comment by mfmjos** [comment]
I haven't observed the off behavior again. I guess there was just something amiss that first day.

Thanks for the support!

**Comment by Mcat12** [comment]
You're welcome!
