### ISSUE TITLE
Pi-hole cannot block any ads.

### ISSUE THREAD

**Issue by SkyYkb** [pi-hole/pi-hole#2951]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi-hole can block most ads.

**Actual behaviour:**

Pi-hole cannot block any ads.

**Steps to reproduce:**

This problem occurred when I installed Pi-hole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/80iggogms5

**Troubleshooting undertaken, and/or other relevant information:**

I don't know what should I do. So I did nothing.

**Comment by PromoFaux** [comment]
This section of the debug log shows that Pi-hole is blocking ads:

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] ad302m.adk2.co is 0.0.0.0 via localhost (127.0.0.1)
[✓] ad302m.adk2.co is 0.0.0.0 via Pi-hole (192.168.101.2)
[✓] doubleclick.com is 172.217.160.110 via a remote, public DNS server (8.8.8.8)
```

So a good place to start troubleshooting is your client machine's configuration. What operating system are you using?

**Comment by SkyYkb** [comment]
A Windows 10 machine and a Android Pie phone.

**Comment by PromoFaux** [comment]
On your windows 10 machine, please could you open a command prompt and provide me with the output of `ipconfig /all`?

**Comment by SkyYkb** [comment]
Windows IP Configuration

   Host Name . . . . . . . . . . . . : MateBook-KB
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : router

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : BE-75-74-E1-95-0E
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : BE-75-74-E1-9D-0E
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : router
   Description . . . . . . . . . . . : Broadcom 802.11ac Wireless PCIE Full Dongle Adapter
   Physical Address. . . . . . . . . : BC-75-74-E1-95-0E
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::2812:c02:e527:9d1e%13(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.101.3(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Thursday, October 3, 2019 14:38:13
   Lease Expires . . . . . . . . . . : Thursday, October 3, 2019 17:08:23
   Default Gateway . . . . . . . . . : fe80::d2d7:83ff:febe:6bd0%13
                                       192.168.101.1
   DHCP Server . . . . . . . . . . . : 192.168.101.1
   DHCPv6 IAID . . . . . . . . . . . : 113014132
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-8D-47-3E-BC-75-74-E1-95-0E
   DNS Servers . . . . . . . . . . . : fe80::d2d7:83ff:febe:6bd0%13
                                       192.168.101.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : BC-75-74-E1-84-34
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:0:284a:364:18fb:9eef:c34b:bf74(Preferred)
   Link-local IPv6 Address . . . . . : fe80::18fb:9eef:c34b:bf74%16(Preferred)
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 201326592
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-8D-47-3E-BC-75-74-E1-95-0E
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Wi-Fi) 2:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-EA-C9-A6
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::603c:7a0a:57e1:4ddf%25(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.112.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 419435869
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-8D-47-3E-BC-75-74-E1-95-0E
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

**Comment by PromoFaux** [comment]
OK, so assuming you are connected via WiFi, this is where it has gone wrong:

````
DNS Servers . . . . . . . . . . . : fe80::d2d7:83ff:febe:6bd0%13
                                          192.168.101.1
```

From your debug log, the IP address of you Pi-hole device is `192.168.101.2`. Assuming `101.1` is your router? How have you configured your router to interact with Pi-hole?

**Comment by SkyYkb** [comment]
Yes.
My router's IP address is 192.168.101.1. 
But I have set up DNS 192.168.101.2 on the router.

**Comment by PromoFaux** [comment]
Hmmm, then it might not be configured correctly in the router. Could you post some screenshots of the config page of your router? Obviously remember to block out any identifying information!

**Comment by SkyYkb** [comment]
Sorry, but my router made in China.
![Annotation 2019-10-03 163347](https://user-images.githubusercontent.com/44992049/66111666-e4d18880-e5fb-11e9-8d8f-51989b781635.jpg)

**Comment by PromoFaux** [comment]
At a guess (Sorry, I don't understand any Chinese languages!) I would sat that is the WAN setup page of the router?

One thing that might be worth trying. If there is a setting to disable the LAN DHCP on it, you can do that and enable the DHCP function of Pi-hole. This will ensure all clients get given the correct IP for their DNS lookups, with the added benefit of Hostnames appearing on your Pi-hole dashboard rather than IP addresses only.

Most routers will allow you to turn off DHCP, but not all of them allow you to change the local DNS server.

**Comment by SkyYkb** [comment]
Oh, sorry.
But the connection between my Pi-hole and router is WiFi, can I use Pi-hole DHCP?

**Comment by PromoFaux** [comment]
Obviously you would have better results with a wired connection, but there is no reason why WiFi should not would. Lots  of people will tell you that you shouldn't, but if the performance is good enough for you then that's good enough. One way to find out... try it :)

**Comment by SkyYkb** [comment]
So, how should I configure Pi-hole DHCP server?
I can turn off the DHCP server on my router, but then what should I do?

**Comment by PromoFaux** [comment]
In the settings page of the Pi-hole admin, there is a DHCP section. See the following for more information

https://discourse.pi-hole.net/t/how-do-i-use-pi-holes-built-in-dhcp-server-and-why-would-i-want-to/3026

Let us know how you get on.

**Comment by SkyYkb** [comment]
Hey, there is a other issue:
This option in Pi-hole Admin Console:

I should input the exist router's IP address or Pi-hole's IP address?

**Comment by PromoFaux** [comment]
This is for the IP address of the Router.

**Comment by SkyYkb** [comment]
Ok.
Thank you for your help.
And set Pi-hole DHCP server solved my issue.
Thank you so much.
:)
