### ISSUE TITLE
FTL Error during install, name server set and -r option not work

### ISSUE THREAD

**Issue by infopz** [pi-hole/pi-hole#2952]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

---
**Expected behaviour:**

Install/Repair correctly

**Actual behaviour:**

[✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
  [✗] FTL Engine not installed

**Steps to reproduce:**

command pihole -r

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

can't upload

**Troubleshooting undertaken, and/or other relevant information:**

I tried to change the name server in /etc/resolv.conf to 1.1.1.1 or 8.8.8.8, but nothing changes

[✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
  [✗] FTL Engine not installed
pi@pi3:~ $ cat /etc/resolv.conf
domain lan
nameserver 1.1.1.1

**Comment by Mcat12** [comment]
@infopz did you find a solution to your issue?

**Comment by infopz** [comment]
I find out that the error was caused by a problem of cURL, so it is not a PiHolr issue.
