### ISSUE TITLE
Raspberry pi os (debian) can't block or get admin panel

### ISSUE THREAD

**Issue by At0micA55** [pi-hole/pi-hole#2957]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:*1*

---
**Expected behaviour:**
Block all pubs and be able to access the web/admin interface

**Actual behaviour:**
Get an error "ERR_CONNECTION_REFUSED" while using the IP
Get the error "ERR_NAME_NOT_RESOLVED" while trying to connect with http:/pi.hole/admin (Altought i have it setup as the DNS)

**Steps to reproduce:**
I have installed Debian using [this](https://www.techrepublic.com/article/how-to-run-raspberry-pis-raspbian-os-on-a-pc/l) (I am using a old acer Aspire 3500 as the main computer for the pihole)
I can connect using SSH using the IP
Change the default password
Pi-hole is installed correctly cause it say it is blocking pubs and running
lighttpd seem to not be present and might be the cause of all this but i can't seem to get it running :/

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{https://tricorder.pi-hole.net/5zp3pfjjfy}`

**Troubleshooting undertaken, and/or other relevant information:**
tried making a pihole -r --> Nothing changed
Getting the pihole status ---> 
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

pihole version print this -->
  Pi-hole version is v4.3.2 (Latest: v4.3.2)
  AdminLTE version is v4.3.2 (Latest: v4.3.2)
  FTL version is v4.3.1 (Latest: v4.3.1)

Then i have looked online for multiple fix but nothing changed it... i even tried to install apache but i can't install it cause i get multiple errors :/

Thanks for the help !

**Comment by dschaper** [comment]
There are a few problems with your setup. 

First is IP address:

```plain
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.1.13/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
```

Next is DNS resolution doesn't seem to be working:

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✗] Failed to resolve servedby.orbisvideo.com via localhost (127.0.0.1)
[✗] Failed to resolve servedby.orbisvideo.com via Pi-hole (192.168.1.13)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)
```

And lastly it doesn't look like you installed `lighttpd` when you instructed the installation scrip to not install `lighttpd`.

`/etc/pihole/setupVars.conf`
```plain

*** [ DIAGNOSING ]: Setup variables
    BLOCKING_ENABLED=true
    TEMPERATUREUNIT=C
    PIHOLE_INTERFACE=eth0
    IPV4_ADDRESS=192.168.1.13
    IPV6_ADDRESS=
    PIHOLE_DNS_1=1.1.1.1
    PIHOLE_DNS_2=1.0.0.1
    QUERY_LOGGING=true
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    >>LIGHTTPD_ENABLED=false<<
    DNSMASQ_LISTENING=all
```

So `pi.hole` will not resolve as DNS is not running correcly. Web will not display as `lighttpd` is not even installed.

**Comment by At0micA55** [comment]
So i should re-install the pi-hole setup completly ? I seem to get an issue tho... Using SSH, when i do pihole -r and do the second option i get the blue screen but it exit immediately ?

**Comment by At0micA55** [comment]
Ok so i have re-installed Pi-Hole again and run the pihole -d command...

Installation with all basic stuff except for the DNS i setup Cloudflare everything else is in default

here is the debug link : [Click me](https://tricorder.pi-hole.net/sw84gp838v)

**Comment by At0micA55** [comment]
> And lastly it doesn't look like you installed `lighttpd` when you instructed the installation scrip to not install `lighttpd`.
> 
> `/etc/pihole/setupVars.conf`
> 
> ```
> 
> *** [ DIAGNOSING ]: Setup variables
>     BLOCKING_ENABLED=true
>     TEMPERATUREUNIT=C
>     PIHOLE_INTERFACE=eth0
>     IPV4_ADDRESS=192.168.1.13
>     IPV6_ADDRESS=
>     PIHOLE_DNS_1=1.1.1.1
>     PIHOLE_DNS_2=1.0.0.1
>     QUERY_LOGGING=true
>     INSTALL_WEB_SERVER=true
>     INSTALL_WEB_INTERFACE=true
>     >>LIGHTTPD_ENABLED=false<<
>     DNSMASQ_LISTENING=all
> ```
> 
> So `pi.hole` will not resolve as DNS is not running correcly. Web will not display as `lighttpd` is not even installed.


I tried going into the file `/etc/pihole/setupVars.conf` but nothing worked... Yes i was in sudo when i edited the file so yes it was able to saved changed as when re-opening it it showed it was to true... 

Quick not the thing i modified and saved is the >     ```LIGHTTPD_ENABLED=false``` line. But like i said, nothing worked... tried restarting, updating (pihole -r --> update)

I think the pi-hole setup is just not installing lighttpd somehow... when trying to install it manually i get this : 
```
pi@alexis:~ $ sudo apt-get install lighttpd
Reading package lists ... Done
Building the dependency tree
Reading status information ... Done
No version of the lighttpd package is available, it already exists in the database
of data. This means that the package is missing, or has become obsolete
or that it is only available from another source

E: The lighttpd package does not have a version that can be installed
```

RIP :/

**Comment by dschaper** [comment]
If `setupVars.conf` is correct then try `pihole -r` and choose `repair` to get the installer to grab the correct package.

There seems to be other issues though, DNS test all failed.

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✗] Failed to resolve ads94.hpg.ig.com.br via localhost (127.0.0.1)
[✗] Failed to resolve ads94.hpg.ig.com.br via Pi-hole (192.168.1.13)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)
```

Has the guide you are using been updated for Debian Buster? There are changes to the operating system with Buster. Can you run `dig doubleclick.com @8.8.8.8` and `dig pi.hole @127.0.0.1` and post the results?

**Comment by At0micA55** [comment]
At this point i really think there is something wrong with my RaspberryPi OS because i get 
```pi@alexis:~ $ dig doubleclick.com @8.8.8.8
-bash: dig : commande introuvable (unknown command in english)
``` 

As or the DNS i would belive it's because the pihole setup or -r (repair) can't install lighthhtpd 

Any OS that could work on my Acer Aspire 3500 that will work with pi-hole with no problem ??? Cause i see a lot of video where the install went smooth and it's not the case with me... 

Exemple : I need to go into the base folder `Pi-hole/automated install/` and remove in the `basic-install.sh` this line : 
```
# -e option instructs bash to immediately exit if any command [1] has a non-zero exit status
# We do not want users to end up with a partially working install, so we exit the script
# instead of continuing the installation with something broken
>>set -e<< ---> remove this completly
```
Or i get the blue screen for the install setup but it automatically exit the blue screen...


SO What should i do ? At this point i used RaspberriPi Os Debian or `Linux alexis 4.19.0-6-686-pae #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) i686` (as it is called) but it doesn't seem to work well...

**Comment by dschaper** [comment]
What image or ISO are you using to install Debian Buster? There should be no need to edit any files or change the installer prior to use.

**Comment by At0micA55** [comment]
The iso straight from `https://www.raspberrypi.org/downloads/raspberry-pi-desktop/` --- > `2019-09-25-rpd-x86-buster` like said higher i installed it using this : [Click me for the tutorial](https://www.techrepublic.com/article/how-to-run-raspberry-pis-raspbian-os-on-a-pc/)

**Comment by dschaper** [comment]
If you don't need the specialized desktop environment then I would just use stock Debian from debian.org.

**Comment by At0micA55** [comment]
No i don't need it xD i just need something i could SSH into and leave the PC somewhere like in my closet where all my network is xD

So something i can use SSH to connect over and be light weight so my old pc can run it... 

I tought that since all Raspbian Pi are soo small my pc could take the os really easy and in fact it's using barelly 13 % of CPU and 30 % Ram over the 1Gb available (i think) So if you say that the debian is low enought for my pc to run it, i will get

**Comment by dschaper** [comment]
Raspbian is Debian with extra things. If you have a small board computer like a Raspberry Pi then you need to run a specialized distribution like Raspbian. You aren't running one of those so you don't need the specialized version. Debian will be fine.

**Comment by At0micA55** [comment]
Hm ok So what debian version should i get ?

**Comment by weechatter** [comment]
as dscharper already said, use Raspbian (https://www.raspbian.org/) on your raspberry pi.

**Comment by PromoFaux** [comment]
As @At0micA55 is not using an Rpi, they should look here for the correct download:

https://www.debian.org/distrib/

**Comment by dschaper** [comment]
Has this been resolved?

**Comment by At0micA55** [comment]
Well i guess the problem is solved but i had to change OS to solve it... I will go and install debian then come back with that to you after that

**Comment by At0micA55** [comment]
Sorry for the time it take, i'm having trouble to install Debian on my old laptot :') BTW, this will be runnin out of a Acer Aspire 3500... Should be enough but i will let you guys know if i ran into any issues
