### ISSUE TITLE
Query adlist exact match is not so exact

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#2969]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

An adlist exact match for facebook.com should not show https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt. 

List contains facebook.com.com which is triggering as an exact match for facebook.com. 

I understand this is not a serious issue but, I feel like exact match should be facebook.com followed by a newline. I would add a newline into whatever validation this "exact match" is doing.

facebook.com.com is not an exact match of facebook.com

**Actual behaviour:**

`An adlist exact match for facebook.com does show https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt`

**Steps to reproduce:**

`Add https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt as a source`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`qvkznlapzu`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

The grep that searches for the exact matches should be anchored to the end of the line

**Comment by DL6ER** [comment]
With the upcoming Pi-hole v5.0, we migrate all domain handling away from per-lists to a database-based per-table approach. This ensures that we always know where a domain starts and ends without having to rely on a newline (or similar).
Hence, the issue you mentioned should already be solved in the current `development` version of Pi-hole.

**Comment by p1r473** [comment]
Thank you sir.

**Comment by p1r473** [comment]
@DL6ER Offtopic Question about that database approach... does this mean gravity is going into a database?
I use a script that nslookups every domain in gravity and removes all the dead/not resolving hosts...

If gravity is becoming a database it will break my poor script :(

**Comment by DL6ER** [comment]
Yes, everything  is moving into the database. You can still use your script, you will just have to adapt it. We are looking forward to starting an extensive beta phase before we fully release so there will be plenty of time to discuss how to modify your script.

**Comment by p1r473** [comment]
@DL6ER Thanks. That is bad news for my poor script indeed.
Have you guys considered incorporating a script that will nslookup all the domains and remove the dead ones? 
Lots of blocklists have garbage in them.

**Comment by p1r473** [comment]
Thanks for your support @DL6ER 
I have requested this feature here 
https://discourse.pi-hole.net/t/script-to-remove-dead-hosts/24706
And I have uploaded my script here
https://pastebin.com/0C7MKThs
