### ISSUE TITLE
FTL not found during update process, github page doesn't exist

### ISSUE THREAD

**Issue by bartgrefte** [pi-hole/pi-hole#2970]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [?] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

It's similar to https://github.com/pi-hole/pi-hole/issues/2636 , just a different link.

**Expected behaviour:**
pihole -up updating both Core and FTL

**Actual behaviour:**
pihole -up only updates core, not FTL

**Steps to reproduce:**
run pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...

  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.3.1/tbd not found

**Troubleshooting undertaken, and/or other relevant information:**
- Running pihole -up again: same result
- Checking internet access with both ping to IP as well as hostname: works.
- Checking status of link on other computer: also 404.
- PiHole is running on a Raspbery Pi with Raspbian 9
- pihole -v -c
  Current Pi-hole version is v4.3.2
  Current AdminLTE version is v4.3.2
  Current FTL version is v3.0

**Comment by Qarasique** [comment]
Fresh install, same. Install interrupt at FTL installing

**Comment by DL6ER** [comment]
What kind of device do you try to install Pi-hole onto and what is the operating system and version of it?

**Comment by Qarasique** [comment]
> What kind of device do you try to install Pi-hole onto and what is the operating system and version of it?

Raspbian lite Raspberry 3b+

**Comment by wbarber69** [comment]
I’ve been having a similar issue. After about a day of uptime I can no longer access certain websites.  GitHub repositories being one of them.  If I check pihole -up I get a long wait that then throws up an error saying github repository cannot be reached.  If I reboot then everything is fine. This only started happening after pihole quit working after the latest update came out and forced me to update (still don’t understand that logic).  After a reboot everything works flawlessly.  And github can be reached again.

**Comment by dschaper** [comment]
Nothing should have forced you to update. Can you give more details on that?

**Comment by wbarber69** [comment]
Both of the last two times that fly had an update my pihole stopped working until I updated.  This time the update brought with it this buggy behavior.  I can log in, I can see how many things got forwarded and how many have been blocked.  I can do all the admin stuff as far as I know, but certain pages just stall indefinitely until either they time out or I close them.  Then I go to pihole and type in a -up command and then the updates stalls trying to ping github and eventually times out like the op is going about.  A reboot fixes everything.  So it must be some bug in the new update.  Because it never did this before.

Sent from my iPhone

On Oct 29, 2019, at 1:26 PM, Dan Schaper <notifications@github.com<mailto:notifications@github.com>> wrote:


Nothing should have forced you to update. Can you give more details on that?

**Comment by dschaper** [comment]
There's nothing intentionally that stops things when there is an update. Please open a new issue with the requested information filled out in the template.

**Comment by wbarber69** [comment]
Nah, I don’t care that much about it.  Too much fiddling about and reading logs etc to appease the github issues gods.  I just wanted to chime in and say there’s something similar on my end that came from the most recent update.  And yeah I’ve seen almost every time there is a major update my pihole basically shits the bed till I update.  There is no pop up or anything saying I have to update.

Sent from my iPhone

On Oct 29, 2019, at 8:43 PM, Dan Schaper <notifications@github.com<mailto:notifications@github.com>> wrote:


There's nothing intentionally that stops things when there is an update. Please open a new issue with the requested information filled out in the template.

**Comment by ThatWeirdAndrew** [comment]
This happens to me as well when I try to fresh install.

**Comment by bartgrefte** [comment]
Any news?

**Comment by yubiuser** [comment]
Does the issue still persists?

**Comment by bartgrefte** [comment]
Completely forgot about this report, don't remember when it was solved, but I'm currently running PiHole with all components at v5.* for quite some time now.
