### ISSUE TITLE
pi-hole and Filesystem Hierarchy Standard (FHS)

### ISSUE THREAD

**Issue by MaxKh** [pi-hole/pi-hole#2976]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Pi-hole must follow FHS recommendations and keep a config files in `/etc/pihole/` and runtime data in e.g. `/var/lib/pihole`. 

**Actual behaviour:**

Currently pi-hole stores all data in `/etc/pihole` including pihole-FTL.db, downloaded blocklists etc.

**Steps to reproduce:**

Run pi-hole

**Troubleshooting undertaken, and/or other relevant information:**

Dividing `static` config files and run-time data will help to store minimal data in `/etc/pihole`. For `dockerized` pi-hole it must be possible to keep minimal number of small files in a docker volume (mounted to `/ect/pihole`) and keep the run-time state inside container.

**Comment by dschaper** [comment]
Thanks for the issue, we'll take a look and see. Everyone has their own interpretation of how FHS is supposed to be supported so this will most likely be a low priority/long process. Moving all existing configurations during update is not an easy process so this will be a very large breaking change.

**Comment by mcccol** [comment]
Bump. This is no small matter. It is not a matter of interpretation - the FHS is unequivocal about not using /etc for binaries and for volatile data.  I was using etckeeper and blew my /etc out to nearly 2Gb before I noticed it. 
The correction is *not* difficult, shouldn't cause problems to a running pihole. Just ln the offending database files to the appropriate /var/lib/pihole directory, restart the server, and remove the offending link. 
Thank you for parameterising these directories, please default them to the FHS appropriate places.
