### ISSUE TITLE
Whitelist merging lines together

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#2979]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`4`

---
**Expected behaviour:**

`When adding a new item to whitelist, it will be on its own line. In this case, i added ipchicken.com, then unagi-na.amazon.com. I would expect these to be on separate lines. `

**Actual behaviour:**

`Occasionally, a whitelist item will concatenate on the same line as another whitelist item. In the above example, in both /etc/pihole/whitelist.txt and also the webGUI, I see instead in the whitelist a concatenation: ipchicken.comunagi-na.amazon.com`

**Steps to reproduce:**

`This happens rarely but enough that I notice it from time to time`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`wxvfl6ng6i`

**Troubleshooting undertaken, and/or other relevant information:**

`I have to manually go in and fix the problem`

Screenshots:
![image](https://user-images.githubusercontent.com/9235633/67630211-9c079b00-f85a-11e9-9228-5b901f6e21d1.png)

**Comment by PromoFaux** [comment]
This issue is de-facto fixed in the next release, as we will be moving away from flat files for the list storage, and towards a database (see #2611)

**Comment by p1r473** [comment]
Confirmed fixed in 5.0 beta.
Closing it out as a future non-issue
