### ISSUE TITLE
DNS resolves for clients, but not logging or blocking requests

### ISSUE THREAD

**Issue by granitepenguin** [pi-hole/pi-hole#2981]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I have Pi-hole configured as DNS and DHCP for clients.  I had originally pointed the router to pi-hole with the router as the DHCP server, then moved the DHCP service to the pi-hole.  At this point, I saw DNS traffic being logged and blocked.  When I hit the "Flush logs" button under Settings -> System, I expected the test logs from the initial setup to clear, and logging of the individual clients to continue

**Actual behaviour:**

When I clicked the "Flush logs," the logs did clear, but now no DNS queries are showing up so no ads are being blocked for client systems.  queries from the pi-hole localhost are catching blocks.

**Steps to reproduce:**

click "Flush logs" under Settings -> System

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

g8ckcewwoa

**Troubleshooting undertaken, and/or other relevant information:**

Attempted:
validated clients are configured to point to pi-hole for DNS and can resolve
```
root@mojojojo:/var/log# dig graph.instagram.com @192.168.69.42

; <<>> DiG 9.11.5-P4-5.1+b1-Debian <<>> graph.instagram.com @192.168.69.42
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 847
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;graph.instagram.com.		IN	A

;; ANSWER SECTION:
graph.instagram.com.	1979	IN	CNAME	instagram.c10r.facebook.com.
instagram.c10r.facebook.com. 60	IN	A	157.240.2.52

;; Query time: 17 msec
;; SERVER: 192.168.69.42#53(192.168.69.42)
;; WHEN: Mon Oct 28 00:43:57 CDT 2019
;; MSG SIZE  rcvd: 102
```

monitor pihole -t and do not see client traffic
pihole -r (repair)
pihole -r (reconfigure)
pihole uninstall / then reinstall

**Comment by dschaper** [comment]
Please open an issue on https://discourse.pi-hole.net as this looks like a configuration problem and not a bug or code issue.

Thanks.

**Comment by granitepenguin** [comment]
will do.  Thanks!
