### ISSUE TITLE
Official support for Clearlinux

### ISSUE THREAD

**Issue by JSEHV** [pi-hole/pi-hole#2987]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

An installation package for Clearlinux to be installed would be findable in the Clearlinux software library.

**Actual behaviour:**

Installation package on Clearlimux does not exist yet.

**Steps to reproduce:**

Installation package on Clearlinux does not exist yet.

**Debug token provided by [uploading `pihole -d` log:

Not available as installation is not possible.

**Troubleshooting undertaken, and/or other relevant information:**

At the moment it won't install under Clearlinux

**Comment by PromoFaux** [comment]
Are you able to run Docker on Clearlinux? If so, you can run Pi-hole :) 

https://github.com/pi-hole/docker-pi-hole
