### ISSUE TITLE
Dashboard Stats deleted after reboot

### ISSUE THREAD

**Issue by myopenflixr** [pi-hole/pi-hole#2996]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{I expect all dashboard stats to remain intact after a reboot}`

**Actual behaviour:**

`{I run pihole in Proxmox container. Whenever container is restarted, all of Pihole's Dashboard stats are erased ans it starts back at 0 Total Queries}`

**Steps to reproduce:**

`{Any shutdown + Start or Reboot of the container causes Pihole stats to be erased and start back at 0}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{zkix5yo5j1}`

**Troubleshooting undertaken, and/or other relevant information:**
None

`{Steps of what you have done to fix this}`
None

**Comment by dschaper** [comment]
The debug log looks fine. What are you using as storage for `/var/run/shm` and `/etc/pihole`?

**Comment by myopenflixr** [comment]
Hi,

Thank you for the quick response. All storage for my Proxmox containers are locally stored on the Proxmox host server. I believe it uses an LXD filesystem for all containers.

I previously ran Pihole as a VM on Virtualbox and experienced the same issue.

**Comment by dschaper** [comment]
Do you have an `/etc/pihole/pihole-FTL.db` file? What size is it if it exists? And what are the contents of `/etc/pihole/pihole-FTL.conf` if that file exists.

**Comment by myopenflixr** [comment]
Yes, I do have a `/etc/pihole/pihole-FTL.db` file. It is slightly over 8MB.

Here are the contents of my `/etc/pihole/pihole-FTL.conf` file (Just the single line below):
`PRIVACYLEVEL=0`

**Comment by myopenflixr** [comment]
I was just looking at Pihole docs.....Should I add the setting: `MAXLOGAGE=24.0`? I've never manually edited this file in any of my installs. Actually didn't know anything about it!

**Comment by dschaper** [comment]
No, it should handle that without needing any additional configuration.

8MB is kind of small for a database file. The file should persist over reboots, if it is being deleted on reboot then there is something else removing the file.

**Comment by myopenflixr** [comment]
Should I reboot and see if the file size changes?

**Comment by dschaper** [comment]
If possible, can you reboot and then send us the `pihole-FTL.log` file to see if it is having problems loading the database?

`sudo cat /var/log/pihole-FTL.log | pihole tricorder` should give you a URL that you can share with us.

**Comment by myopenflixr** [comment]
After the reboot, my total queries went from over 160k down to 16k

Here's the URL it provided me: `https://tricorder.pi-hole.net/v1gtl8ixtsroot@Pihole1-1`

**Comment by myopenflixr** [comment]
The file size on the DB file is still right around 8MB

**Comment by dschaper** [comment]
The log is showing 16k records imported as you note. What are the permissions on the `/etc/pihole/pihole-FTL.db` file?

`sudo ls -la /etc/pihole/pihole-FTL.*`

**Comment by dschaper** [comment]
So this time the stats didn't reset to 0? They show 16k?

**Comment by myopenflixr** [comment]
That is correct...And it looks like I lost all stats going back to 9:20pm last night. It's currently 2:22pm locally now. It looks like it lost the last 17 hours of stats for some reason.

<a href="https://imgur.com/oWYKzFN"><img src="https://i.imgur.com/oWYKzFN.jpg?1" title="source: imgur.com" /></a>

**Comment by myopenflixr** [comment]
Here's something interesting as well. Here's stats for a url that gets pinged every 5 seconds by my Home Assistant Server. At the bottom, you see the date and time jump from Yesterday at 5:15pm to today at 2:06pm (which is probably when I rebooted the server per your instructions above.

<a href="https://imgur.com/7TKm45H"><img src="https://i.imgur.com/7TKm45H.jpg" title="source: imgur.com" /></a>

**Comment by dschaper** [comment]
Are you running out of disk space?

**Comment by myopenflixr** [comment]
Not at all. I have 8GB allocated to this container and only using 16.44% at the moment.

**Comment by dschaper** [comment]
Can you show us the contents of `/etc/pihole` please?

`sudo ls -la /etc/pihole/`

**Comment by dschaper** [comment]
And just to check please include `sudo df -h` please.

**Comment by myopenflixr** [comment]
Here's contents from `sudo ls -la /etc/pihole/`:

>total 20056
drwxr-xr-x  2 pihole pihole      4096 Nov 11 14:42 .
drwxr-xr-x 85 root   root        4096 Nov 11 14:06 ..
-rw-r--r--  1 root   root         313 Nov  7 18:21 adlists.list
-rw-r--r--  1 root   root          21 Nov 10 04:50 black.list
-rw-r--r--  1 root   root          21 Nov  7 20:56 blacklist.txt
-rw-r--r--  1 pihole pihole         0 Nov 11 14:06 dhcp.leases
-rw-r--r--  1 root   root         596 Nov  7 18:22 dns-servers.conf
-rw-r--r--  1 root   root          20 Nov 11 14:06 GitHubVersions
-rw-r--r--  1 root   root     2717134 Nov 10 04:50 gravity.list
-rw-r--r--  1 root   root        1256 Nov  7 18:22 install.log
-rw-------  1 root   root     1286006 Nov 10 04:50 list.0.raw.githubusercontent.com.domains
-rw-------  1 root   root      594812 Nov  7 18:22 list.1.mirror1.malwaredomains.com.domains
-rw-------  1 root   root      638705 Nov  7 18:22 list.2.sysctl.org.domains
-rw-------  1 root   root         613 Nov  7 18:22 list.3.s3.amazonaws.com.domains
-rw-------  1 root   root       43642 Nov  7 18:22 list.4.s3.amazonaws.com.domains
-rw-------  1 root   root     1772405 Nov  7 18:22 list.5.hosts-file.net.domains
-rw-r--r--  1 root   root     2717188 Nov 10 04:50 list.preEventHorizon
-rw-r--r--  1 root   root          20 Nov 11 14:40 localbranches
-rw-r--r--  1 root   root          42 Nov 10 04:50 local.list
-rw-r--r--  1 root   root          42 Nov 11 14:40 localversions
-rw-r--r--  1 root   root         238 Nov  7 18:22 logrotate
-rw-r--r--  1 root   root     2351104 Nov  7 18:22 macvendor.db
-rw-rw-r--  1 pihole root          15 Nov  7 18:22 pihole-FTL.conf
-rw-r--r--  1 pihole pihole   8331264 Nov 11 14:42 pihole-FTL.db
-rw-rw-r--  1 pihole www-data     204 Nov  7 20:57 regex.list
-rw-r--r--  1 root   root         445 Nov  8 14:20 setupVars.conf
-rw-r--r--  1 root   root          54 Nov 10 00:01 whitelist.txt

And here's `sudo df -h`:

> Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/pve-vm--200--disk--0  7.9G  1.3G  6.2G  18% /
none                              492K     0  492K   0% /dev
udev                               32G     0   32G   0% /dev/tty
tmpfs                              32G  1.2M   32G   1% /dev/shm
tmpfs                              32G  192K   32G   1% /run
tmpfs                             5.0M     0  5.0M   0% /run/lock
tmpfs                              32G     0   32G   0% /sys/fs/cgroup
tmpfs                             6.3G     0  6.3G   0% /run/user/999
tmpfs                             6.3G     0  6.3G   0% /run/user/0

**Comment by dschaper** [comment]
How long has this container been running? Did you just create it on the 7th of November?

**Comment by myopenflixr** [comment]
Yes.

**Comment by dschaper** [comment]
@PromoFaux Can you craft a sql query to get the time of the earliest entry in the sqlite3 database?

**Comment by myopenflixr** [comment]
Unfortunately, that might be a bit too advanced for me.

**Comment by myopenflixr** [comment]
Sorry...just re-read your post and saw that you asked someone else to craft the sql query :)

**Comment by PromoFaux** [comment]
`select datetime(timestamp, 'unixepoch', 'localtime'), domain from queries limit 1;`

**Comment by myopenflixr** [comment]
Here's the output: `2019-11-07 18:22:21|raw.githubusercontent.com`

**Comment by PromoFaux** [comment]
What about:

`select count(1) from queries;` (this will give a count of all records in that table)

and `select max(datetime(timestamp,'unixepoch','localtime')) from queries;` (this will give the latest query time)
`

**Comment by myopenflixr** [comment]
Command: `select count(1) from queries;`
Output: `130675`

Command: `select max(datetime(timestamp,'unixepoch','localtime')) from queries;`
Output: `2019-11-11 16:25:59`

**Comment by PromoFaux** [comment]
So there are definitely queries in there, not getting deleted. 

This will also give you a breakdown of queries by day:
` select date(timestamp,'unixepoch','localtime'), count(1) from queries group by date(timestamp,'unixepoch','localtime');`

But I'm not sure what we're trying to achieve here. After a reboot, are there any errors in the browsers javascript console/ network tabs?

**Comment by myopenflixr** [comment]
Here's the output:
> 2019-11-07|11219
2019-11-08|27717
2019-11-10|78556
2019-11-11|13696

What I'm trying to achieve here is that when I reboot the Pihole Server, I do not lose stats from the past 24 hours.

My reboot this afternoon caused the previous 20 hours of Queries to disappear from the dashboard.

I would expect a reboot to only lose the 15-20 seconds worth of stats while the Proxmox container was rebooting.

**Comment by deathbybandaid** [comment]
@myopenflixr can I get a paste of your LXC.conf?

Should be located in `/etc/pve/lxc/` it will be the container number `.conf`

Also useful info would be which container template you used to install.

**Comment by myopenflixr** [comment]
Sure. Here's the .conf contents:
> arch: amd64
cores: 2
hostname: Pihole1-1
memory: 1024
net0: bridge=vmbr0,hwaddr=B6:5B:53:C3:F2:F8,name=eth0,ip=172.16.0.94/24,gw=172.16.0.1,firewall=1
onboot: 1
ostype: ubuntu
rootfs: local-lvm:vm-200-disk-0,size=8G
startup: order=1
swap: 512
unprivileged: 1

The container template I used was: `ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz`

**Comment by deathbybandaid** [comment]
@myopenflixr one more thing, a screencap of your hosts summary screen.

**Comment by myopenflixr** [comment]
@deathbybandaid - Do you want a screencap of the Pihole container summary screen on Proxmox?

**Comment by deathbybandaid** [comment]
@myopenflixr the host server summary.

**Comment by myopenflixr** [comment]
<a href="https://imgur.com/L0BIH7h"><img src="https://i.imgur.com/L0BIH7h.jpg" title="source: imgur.com" /></a>

**Comment by deathbybandaid** [comment]
Those are some impressive host machine specs @myopenflixr !!

I'll attempt to replicate your issue in the morning.

**Comment by myopenflixr** [comment]
Thanks @deathbybandaid! It's amazing what you can find online nowadays for cheap! This particular server was only $355 (including shipping) w/16GB memory and no hard drives.

I've gotten 2 great servers from UNIXPlus this year for a very reasonable price!

**Comment by deathbybandaid** [comment]
@myopenflixr I had an idea as to what the issue might be.

Can you get me the output of `service pihole-FTL status` ?

I'm looking for warnings such as "too many open files", of which I have a solution for.

**Comment by myopenflixr** [comment]
> ● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Mon 2019-11-11 14:06:17 EST; 18h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 161 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

Nov 11 14:06:17 Pihole1-1 systemd[1]: Starting LSB: pihole-FTL daemon...
Nov 11 14:06:17 Pihole1-1 pihole-FTL[161]: Not running
Nov 11 14:06:17 Pihole1-1 pihole-FTL[161]: /etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
Nov 11 14:06:17 Pihole1-1 su[336]: Successful su for pihole by root
Nov 11 14:06:17 Pihole1-1 su[336]: + ??? root:pihole
Nov 11 14:06:17 Pihole1-1 su[336]: pam_unix(su:session): session opened for user pihole by (uid=0)
Nov 11 14:06:17 Pihole1-1 pihole-FTL[161]: FTL started!
Nov 11 14:06:17 Pihole1-1 su[336]: pam_unix(su:session): session closed for user pihole
Nov 11 14:06:17 Pihole1-1 systemd[1]: Started LSB: pihole-FTL daemon.

**Comment by deathbybandaid** [comment]
thanks @myopenflixr 

If you have time, do you mind installing Pi-hole in a `debian-10.0-standard_10.0-1_amd64.tar` template, and see if the issue exists there as well? I'm creating an ubuntu LXC with the specs you gave me. However, it may take some time for me to populate some dns requests and simulate what you see on your end.

Some other things you can try (and should help your overall Proxmox experience):
(On the Proxmox host machine)
Disclaimer: these are things I've found over the past couple years that have helped me. You are free to google what these changes do before applying them.

`nano /etc/security/limits.conf`
add to the bottom:
```
*       soft    nofile  1048576
*       hard    nofile  1048576
root    soft    nofile  1048576
root    hard    nofile  1048576
*       soft    memlock unlimited
*       hard    memlock unlimited
```


`nano /etc/sysctl.conf`
add to the bottom:
```
fs.inotify.max_queued_events=1048576
fs.inotify.max_user_instances=1048576
fs.inotify.max_user_watches=1048576
vm.max_map_count=262144
kernel.dmesg_restrict=1
net.core.rmem_max = 16777216
fs.file-max = 1048576
```


`nano /proc/sys/fs/inotify/max_user_watches`
change the number to: `1048576`

Then run these two commands (or reboot):
`sysctl -p`
`sysctl --system`

**Comment by myopenflixr** [comment]
Hi @deathbybandaid 

I just made those two changes to the host machine. Just out of curiosity, can you give me a brief "non-technical" overview of what those changes do for the host?

I will work on creating a test container using the Debian 10 you mentioned and will play around with it today and report back when I can on whether it's saving the Dashboard Stats upon reboots. It may take some time for this as I'm deep in work with my day job all day.

**Comment by deathbybandaid** [comment]
@myopenflixr tldr:

With LXC, you share alot of Host "stuff", whereas VMs are a completely contained environment. Linux has default settings for how many open files your system should have.
Since LXC shares this with the host machine, you will reach a point that the amount of files open in 
Host + container1 + container2 + etc is greater than that maximum

**Comment by myopenflixr** [comment]
Thanks for the explanation. I currently have 15 "everyday" containers + 1 VM running on the host. Do you think those changes that you recommended sufficient for what I have going on?

I previously ran Ubuntu Server+Virtualbox and just recently switched over to Proxmox several months ago so I am not super familiar with all the intricacies of Proxmox whatsoever :)

**Comment by myopenflixr** [comment]
@deathbybandaid 

I've installed Pihole on the debian image you referenced earlier and everything seems to be working great so far. I'm up to 20,000+ queries on the Dashboard and have restarted the container several times over the past couple of hours with no loss in Dashboard stats.

Does this indicate a possibly compatibility issue with the Ubuntu image I originally used? In addition, I had this same issue when Pihole was installed on a VM in my old Ubuntu Server + Virtualbox configuration (before switching over to Proxmox).

I'll give you another update later tonight on whether dashboard stats are being retained after additional restarts of the container + more queries being logged.

**Comment by deathbybandaid** [comment]
@myopenflixr that's precisely why I asked for you to do that. Helps narrow down the troubleshooting.

Can you also do some testing on your ubuntu container as well? It's possible the stuff you modified on host played a role here as well.

**Comment by myopenflixr** [comment]
@deathbybandaid 
Sure will....I'll shut down the new debian and fire back up the original Ubuntu and report back.

**Comment by myopenflixr** [comment]
@deathbybandaid 

It appears the changes that you had me make to the Proxmost host has resolved the issue I was having with the lost stats on the dashboard. I've had the Ubuntu image fired up since yesterday. I've restarted the container several times and it's now retaining the full 24 hours of stats on the dashboard.

**Comment by deathbybandaid** [comment]
Awesome! The host fixes will continue to help you as you add more containers to your proxmox setup.

This looks like a good issue thread to reference for other Proxmox users.

However, this isn't directly an issue with Pi-hole, as you could run Pi-hole in lxc without encountering this issue (if you only had a couple containers). Documenting the steps taken above is a judgement call to be made.

**Comment by myopenflixr** [comment]
@deathbybandaid 

I had mentioned earlier that I currently run 15 containers + a VM on this Proxmost host. Do you think the changes that you had me make are sufficient for this many containers (and more if I add any)?

**Comment by deathbybandaid** [comment]
@myopenflixr those settings suffice for me!

![image](https://user-images.githubusercontent.com/18010545/68768362-5d126d00-05f0-11ea-9356-8c04c3139f4f.png)

**Comment by myopenflixr** [comment]
I definitely don't anticipate running that many containers or VM's on this host.

Thanks for all your help @deathbybandaid 

I think we can consider this issue closed. And I agree this thread is a good reference for anyone else running Proxmox and experiencing similar issues. I will have to agree that this issue was not with Pihole, but with my setting on the Proxmox host machine.

**Comment by dschaper** [comment]
Thank you everyone!
