### ISSUE TITLE
AAAA queries are not being blacklisted

### ISSUE THREAD

**Issue by morenod** [pi-hole/pi-hole#2997]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4
---
**Expected behaviour:**

Both AAAA and A queries will be blocked

**Actual behaviour:**

When adding domains to the blacklist, if DNS receives both A and AAAA queries, only A query is blacklisted

dnsmasq: 1712 10.0.78.42/60678 query[AAAA] registry.redhat.io from 10.0.78.42
dnsmasq: 1712 10.0.78.42/60678 forwarded registry.redhat.io to 172.18.124.12
dnsmasq: 1712 10.0.78.42/60678 reply registry.redhat.io is <CNAME>
dnsmasq: 1712 10.0.78.42/60678 reply registry.redhat.io.edgekey.net is <CNAME>
dnsmasq: 1713 10.0.78.42/33376 query[A] registry.redhat.io from 10.0.78.42
dnsmasq: 1713 10.0.78.42/33376 /etc/pihole/black.list registry.redhat.io is 172.18.124.15

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
I usually don't reply with "Works for me" but since I can't see a debug log to check I have to go by what I can do on my local setup.

Prior to blacklisting `registry.redhat.io`, queries to my Pi-hole for A and AAAA
```
Mariner-10% dig registry.redhat.io @192.168.10.2 A +short
registry.redhat.io.edgekey.net.
e14353.g.akamaiedge.net.
184.30.189.133

Mariner-10% dig registry.redhat.io @192.168.10.2 AAAA +short
registry.redhat.io.edgekey.net.
e14353.g.akamaiedge.net.
```

After blacklisting that domain:

```
Mariner-10% dig registry.redhat.io @192.168.10.2 A +short
0.0.0.0
Mariner-10% dig registry.redhat.io @192.168.10.2 AAAA +short
::
```

So it appears to work correctly.

**Comment by dschaper** [comment]
Stale, re-open if this has not been resolved.
