### ISSUE TITLE
Not Understanding Conditional Forwarding

### ISSUE THREAD

**Issue by STaRDoGG** [pi-hole/pi-hole#3004]
I'm using the latest Docker Image and all is working fine with the exception of the Conditional Forwarding feature, and I'm not sure I fully understand it. I have it setup how I *think* it's supposed to be, but the Top lists only show the IP of the Docker network it's in?

Here's how I have everything setup so far; did I screw something up?

![image](https://user-images.githubusercontent.com/1524526/68998147-0b7a1480-0874-11ea-8b86-42ceac220c84.png)

**Comment by PromoFaux** [comment]
Hi there, as you're looking for help rather than to report a bug, I'm going to close this out.. but I'll point you at our support forums, where there are already many subjects on the topic :)

Cheers

https://discourse.pi-hole.net/search?q=conditional%20forwarding
