### ISSUE TITLE
Allow selecting URLs and other text in the UI

### ISSUE THREAD

**Issue by jeffwhite530** [pi-hole/pi-hole#3006]
In the latest version of pihole it is impossible to select text in the query log.  Everything is a link so it tries to just go to that link.  If you do manage to get the text to be selected it is immediately unselected.  This happens in both Chrome and Firefox.  Please just let us select text ...

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by PromoFaux** [comment]
Top-tip in the mean time: you can select link text by holding down alt on your keyboard as you select it :)

Also, having just gone to make a gif to demonstrate this, I just noticed there is a checkbox below the graph:

![image](https://user-images.githubusercontent.com/1998970/69361989-8339ac00-0c85-11ea-92ea-6c4d808d59af.png)


uncheck that and it disables the links

**Comment by jeffwhite530** [comment]
Thanks, that check box does work around the problem.  Holding alt just causes the entire browser window to be dragged around.  Perhaps you're on Windows or OSX where that has a different behavior.
