### ISSUE TITLE
Queries and clients not shown, but in log it seems fine and ad blocking works

### ISSUE THREAD

**Issue by Sm03leBr00t** [pi-hole/pi-hole#3007]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The webui showing that my laptop and our router beeing connected and the queries showing up.

**Actual behaviour:**

I see sadly nothing but the default screen of the pihole admin UI. Also my clients show up in network but it thinks they are not using pihole. Adblocking seems fine and looking into the pihole.log, I can see that dnsmasq actually gets the dns requests from my router. So why is it not showing :( *super sad face*

**Steps to reproduce:**

I just installed it on a fresh version of Raspian stretch:
`hostnamectl`
```
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: ---censored---
           Boot ID: ---censored---
  Operating System: Raspbian GNU/Linux 9 (stretch)
            Kernel: Linux 4.19.66-v7+
      Architecture: arm
```
I use these versions: 
```
Pi-hole Version v4.3.2 
Web Interface Version v4.3.2 
FTL Version v4.3.1
```
Using systemctl I see that the dnsmasq server failed, but because the port 53 is already in use.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/n13mf1dmx0

**Troubleshooting undertaken, and/or other relevant information:**

I looked at some of the old issues in Pihole v3.3 but disabling caching didn't work. I still find no answer. I reinstalled everything, rebooted everyting but no answer...

**Comment by dschaper** [comment]
What address / URL are you using to access the page? Can you provide a screenshot of what you are seeing?

**Comment by Sm03leBr00t** [comment]
yes of course, I do everything to help you guys out :+1: 

Url: `http://192.168.178.80/admin/index.php`

![Bildschirmfoto vom 2019-11-21 22-03-26](https://user-images.githubusercontent.com/36639589/69376568-ca866380-0caa-11ea-8276-397b104e2e8f.png)

Hope that helps you out!

**Comment by Sm03leBr00t** [comment]
Here is also one of the client section:

![Bildschirmfoto vom 2019-11-21 22-05-35](https://user-images.githubusercontent.com/36639589/69376720-16390d00-0cab-11ea-8c03-cf773f9b104e.png)

**Comment by dschaper** [comment]
Are you restarting the service? There's a few entries that show pihole-FTL being manually restarted.

```sh
   [2019-11-21 21:31:19.953 22292] Received SIGHUP, reloading cache
   [2019-11-21 21:31:19.953 22292] Blocking status is enabled
   [2019-11-21 21:31:19.953 22292] INFO: No whitelist file found
   [2019-11-21 21:31:19.953 22292] Compiled 0 Regex filters and 0 whitelisted domains in 0.1 msec (0 errors)
   [2019-11-21 21:31:21.271 22292] /etc/pihole/gravity.list: parsed 116533 domains (took 1317.7 ms)
   [2019-11-21 21:34:11.596 22292] Received SIGHUP, reloading cache
   [2019-11-21 21:34:11.596 22292] Blocking status is enabled
   [2019-11-21 21:34:11.596 22292] INFO: No whitelist file found
   [2019-11-21 21:34:11.596 22292] Compiled 0 Regex filters and 0 whitelisted domains in 0.1 msec (0 errors)
   [2019-11-21 21:34:12.653 22292] /etc/pihole/gravity.list: parsed 116533 domains (took 856.8 ms)
   [2019-11-21 21:39:53.981 22292] Received SIGHUP, reloading cache
   [2019-11-21 21:39:53.981 22292] Blocking status is enabled
   [2019-11-21 21:39:53.981 22292] INFO: No whitelist file found
   [2019-11-21 21:39:53.981 22292] Compiled 0 Regex filters and 0 whitelisted domains in 0.1 msec (0 errors)
   [2019-11-21 21:39:55.036 22292] /etc/pihole/gravity.list: parsed 116533 domains (took 857.8 ms)
```

**Comment by dschaper** [comment]
The list of clients shows that none of those clients are using the Pi-hole for their DNS>

**Comment by Sm03leBr00t** [comment]
1. Yes I tried restarting it following some bug fixes for earlier, similar problems
2. This is weird because my router has pi-hole set up as well as my phone and laptop

**Comment by dschaper** [comment]
What operating system is on the laptop?

**Comment by Sm03leBr00t** [comment]
Manjaro Linux
`hostnamectl`
```
   Static hostname: tuxi
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ---censored---
           Boot ID: ---censored---
  Operating System: Manjaro Linux
            Kernel: Linux 4.19.80-1-MANJARO
      Architecture: x86-64
```
`screenfetch`
```
 alex@tuxi
 OS: Manjaro 18.1.2 Juhraya
 Kernel: x86_64 Linux 4.19.80-1-MANJARO
 Uptime: 5d 22h 21m
 Packages: 1487
 Shell: fish 3.0.2
 Resolution: 3200x1800
 DE: GNOME 3.34.1
 WM: Mutter
 WM Theme: Adapta-Eta-Maia
 GTK Theme: Flat-Remix-GTK-Blue-Dark [GTK2/3]
 Icon Theme: Papirus-Dark-Maia
 Font: Noto Sans 11
 Disk: 131G / 1,4T (10%)
 CPU: Intel Core i7-8565U @ 8x 4.6GHz [49.0°C]
 GPU: Mesa DRI Intel(R) UHD Graphics (Whiskey Lake 3x8 GT2) 
 RAM: 4734MiB / 31879MiB
```

**Comment by dschaper** [comment]
`cat /etc/resolv.conf` to see what DNS servers it is using.

**Comment by Sm03leBr00t** [comment]
´´´
# Generated by NetworkManager
search fritz.box
nameserver 192.168.178.1
nameserver fd00::c225:6ff:fefe:593
´´´

**Comment by dschaper** [comment]
As a test, edit that file and replace everything with

```
nameserver 192.168.178.80
```

If that shows activity on the admin web interface then we know Pi-hole is working and the issue is with the network configuration and client configuration.

**Comment by Sm03leBr00t** [comment]
even the search fritz.box ?

**Comment by dschaper** [comment]
Yes

**Comment by Sm03leBr00t** [comment]
nothing happening, should I restart something? Or is this just the evidence of something bigger a level  can not understand :D ?

**Comment by dschaper** [comment]
On the laptop try directly querying the Pi-hole:

```
dig google.com @192.168.178.80
dig doubleclick.net @192.168.178.80
```
That should give you a response on the laptop and show some entries in the admin interface under the query log.

**Comment by Sm03leBr00t** [comment]
`dig google.com @192.168.178.80`
```

; <<>> DiG 9.14.7 <<>> google.com @192.168.178.80
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33725
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		111	IN	A	172.217.23.110

;; Query time: 10 msec
;; SERVER: 192.168.178.80#53(192.168.178.80)
;; WHEN: Do Nov 21 22:24:49 CET 2019
;; MSG SIZE  rcvd: 55
```

`dig doubleclick.net @192.168.178.80`
```

; <<>> DiG 9.14.7 <<>> doubleclick.net @192.168.178.80
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53280
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;doubleclick.net.		IN	A

;; ANSWER SECTION:
doubleclick.net.	2	IN	A	0.0.0.0

;; Query time: 3 msec
;; SERVER: 192.168.178.80#53(192.168.178.80)
;; WHEN: Do Nov 21 22:25:49 CET 2019
;; MSG SIZE  rcvd: 60
```

You know what is super weird? In the `pihole.log` file I see activity right after running them.
`tail /var/log/pihole.log`
```
Nov 21 22:26:35 dnsmasq[22292]: query[A] s.youtube.com from 192.168.178.1
Nov 21 22:26:35 dnsmasq[22292]: /etc/pihole/gravity.list s.youtube.com is 0.0.0.0
Nov 21 22:26:36 dnsmasq[22292]: query[AAAA] api.smoot.apple.com from 192.168.178.1
Nov 21 22:26:36 dnsmasq[22292]: forwarded api.smoot.apple.com to 208.67.222.222
Nov 21 22:26:36 dnsmasq[22292]: query[A] api.smoot.apple.com from 192.168.178.1
Nov 21 22:26:36 dnsmasq[22292]: forwarded api.smoot.apple.com to 208.67.222.222
Nov 21 22:26:36 dnsmasq[22292]: reply api.smoot.apple.com is <CNAME>
Nov 21 22:26:36 dnsmasq[22292]: reply api-glb.smoot.apple.com is NODATA-IPv6
Nov 21 22:26:36 dnsmasq[22292]: reply api.smoot.apple.com is <CNAME>
Nov 21 22:26:36 dnsmasq[22292]: reply api-glb.smoot.apple.com is 17.242.57.246
```

**Comment by dschaper** [comment]
That is showing that Pi-hole is configured and running correctly. Since this is a configuration issue with your network I invite you to visit https://discourse.pi-hole.net for more assistance in that configuration. The users in the German forum have experience with fritzbox networks at https://discourse.pi-hole.net/c/bugs-problems-issues/deutschsprachige-hilfe

**Comment by Sm03leBr00t** [comment]
Thank you, fast and very helpfull support :)

**Comment by Sm03leBr00t** [comment]
Ohh @dschaper ,
I just restarted it one last time ... and now it works :D :+1: da fuk!
Whatever it was, it went on

Still big thanks and I will try to share this experience with others!

**Comment by Sm03leBr00t** [comment]
![Bildschirmfoto vom 2019-11-21 22-32-24](https://user-images.githubusercontent.com/36639589/69378513-cfe5ad00-0cae-11ea-95f9-f677a64d12f5.png)

**Comment by dschaper** [comment]
IPv6 tends to muddy the waters with things. There's a few things that can help with the experience when using a Fritzbox and the users in the discourse forum can help you tune it all.
