### ISSUE TITLE
Feature: Enforce safe search for google/youtube/bing/ddg

### ISSUE THREAD

**Issue by bellwood** [pi-hole/pi-hole#3011]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

When youth attempts a search to google/youtube/bing/ddg for something adult/restricted the results come back from their restricted/safe domains and for the most part filtered out.

**Actual behaviour:**

Currently, you get the usual unrestricted results.

**Steps to reproduce:**

- Map  queries to www.bing.com to strict.bing.com

- Map queries to google.com to forcesafesearch.google.com.

- Map queries to youtube.com to restrict.youtube.com or restrictmoderate.youtube.com

- Map queries to duckduckgo.com to safe.duckduckgo.com.

**Debug token**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

It would be great if this was simply an option, as it doesn't apply to all networks.

It does not appear yahoo supports DNS level protection but that's easy to fix by just blocking Yahoo if you were so inclined.

- https://support.opendns.com/hc/en-us/articles/227986807-How-to-Enforcing-Google-SafeSearch-YouTube-and-Bing
- https://support.google.com/websearch/answer/510?co=GENIE.Platform%3DDesktop&amp;hl=en
- https://help.bing.microsoft.com/#apex/18/en-US/10003/0
- https://help.duckduckgo.com/duckduckgo-help-pages/features/safe-search/

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by bellwood** [comment]
@dschaper: Thanks for replying. I did some poking around discourse and see there are already some options for this that wouldn't necessarily require a change to the current project.

I'll open a FR if those options don't suffice =)
