### ISSUE TITLE
No DNS resolution on Raspbian, Raspberry Pi 2

### ISSUE THREAD

**Issue by orpharion** [pi-hole/pi-hole#3019]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Installation on Raspbian Buster (lite image), on Raspberry Pi 2B, using the install.pi-hole.net script. Expected to be able to resolve DNS queries on completion.

**Actual behaviour:**

Installation fails on DNS resolution.
  [i] Pi-hole blocking is enabled
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 0
  [✗] DNS resolution is currently unavailable

Machine can no longer resolve DNS. pihole -g fails. Can still ping IP addresses.

**Steps to reproduce:**

1. Write Rasbian image to disk (specifically, 2019-09-26-raspbian-buster-lite.img), on Raspberry pi 2B. 
2. Enable SSH, and log in.
3. Run curl -sSL https://install.pi-hole.net | bash.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Debug cannot be uploaded, as after installation DNS resolution fails. 
[pihole_debug.log](https://github.com/pi-hole/pi-hole/files/3910922/pihole_debug.log) (shouldn't have any identifying info).

**Troubleshooting undertaken, and/or other relevant information:**
I have checked that my router does not block DNS queries on port 53, or restrict them to a particular IP.
I have re-installed multiple times, and tried the docker container with the same result.

**Comment by dschaper** [comment]
What does `/etc/resolv.conf` show for the local DNS server to be used?

**Comment by orpharion** [comment]
127.0.0.1. Tried 8.8.8.8, 9.9.9.9, no change.

**Comment by dschaper** [comment]
Can you `ping 8.8.8.8`?

**Comment by orpharion** [comment]
I can, and I can use 8.8.8.8 as the DNS IP for other machines on the network.

**Comment by dschaper** [comment]
Okay, then try `dig google.com @8.8.8.8` on the Pi-hole at the command line.

**Comment by orpharion** [comment]
`dig google.com @8.8.8.8`:
; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> google.com @8.8.8.8
;; global options: +cmd
;; connection timed out; no servers could be reached
I also tried
`dig @8.8.8.8 google.com`:
; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> @8.8.8.8 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

This is the same response I get (excluding the DiG info) that I get from another machine that has no DNS problems

**Comment by dschaper** [comment]
This result is showing that using Google as the DNS server fails on the Pi-hole device. That indicates a networking issue between the Pi-hole and the internet. Possibly a firewall or some other issue interfering. If you can not `dig` to the upstream server that you have chosen then there is no way for the PI-hole to get any queries answered.

**Comment by mok0** [comment]
Make sure you don't have dnsmasq from the Raspian repo installed on the Pi. I've been burned by that several times, I get the same symptoms as you, and when I purge the package, DNS resolution works. 

I suppose the pi-hole install script ought to make sure that dnsmasq is not installed on the system.

**Comment by orpharion** [comment]
I've figured out that my router is blocking all DNS queries that are not addressed to its local IP address directly. I set it's local IP as the DNS, set my upstream provider on the router, and pihole successfully updated the block list and is working. Apologies for any wasted time.
