### ISSUE TITLE
Web Deashboard wont open after OS upgrade

### ISSUE THREAD

**Issue by JacoFourie** [pi-hole/pi-hole#3020]
Hi. I upgraded my OS from Strech to Buster and now the Dashboard wont open.

The browser wants to download the index.php file. IT does not tun it.

https://tricorder.pi-hole.net/nkkf7vnsia

**Comment by dschaper** [comment]
You have installed `nginx` and that is not a supported web server.

**Comment by JacoFourie** [comment]
Hi. I did not install anything on my own. Maybe Thigsboard installed it. Let me have a look.
Thanks for the info.

**Comment by dschaper** [comment]
Thank you.

**Comment by JacoFourie** [comment]
I removed it but the same error still happenes. Should I run a reinstall ?

**Comment by dschaper** [comment]
Try a repair first.
