### ISSUE TITLE
Can't access web interface using http://pi.hole/admin 

### ISSUE THREAD

**Issue by At0micA55** [pi-hole/pi-hole#3021]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---
**Expected behaviour:**

`Be able to use http://pi.hole/admin or http://pi.hole/ to access the web-interface`

**Actual behaviour: ERR_NAME_NOT_RESOLVED Impossible to find the ip for the server. I can connect to the web interface using the IP adress of the server.**

`Link to screenshot : (https://i72.servimg.com/u/f72/18/64/01/33/screen10.jpg). Sorry for the french`

**Steps to reproduce:**

`Install Pi-Hole normally following the skript.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/op7y1hej0d`

**Troubleshooting undertaken, and/or other relevant information:**

 ```

1. Re-install Pi-Hole enabling this time the IPV6 (Cause i disabled it in the first install)
2. Tried looking for answers in the FAQ or the existing Issues

```

 **Thanks for your help !**

**Comment by DL6ER** [comment]
Your computer is likely not configured correctly to use your Pi-hole.

How do you propagate the DNS server information in your network? Do you use the Pi-hole DHCP server, did you configure your already running DHCP server to hand out the Pi-hole's address as the (sole!) DNS server or do you use static address management in your network?

It may also be that DNS queries bypass your Pi-hole when they are sent to an upstream IPv6 DNS server, maybe provided by your Internet Service Provider (ISP).

**Comment by At0micA55** [comment]
Static adddress management in my network... then set my network (Netgear router) to use that static adress as the DNS server

**Comment by yubiuser** [comment]
Does the issue still persists?
