### ISSUE TITLE
[dev] FTL doesn't update, "The requested URL returned error: 404"

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/pi-hole#3022]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

FTL update check should run without faulting.

**Actual behaviour:**

running `pihole -up` I get the following output:
<pre>
pi@nanopineo:/etc/.pihole$ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
<b>curl: (22) The requested URL returned error: 404</b>
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check
...
</pre>

`sudo bash -x /opt/pihole/update.sh` outputs 
<pre>
...
+ echo -e '  [i] Web Interface:\tup to date'
  [i] Web Interface:    up to date
+ FTLcheckUpdate
+ printf '  %b Checking for existing FTL binary...\n' '[i]'
+ local ftlLoc
++ which pihole-FTL
+ ftlLoc=/usr/bin/pihole-FTL
+ local ftlBranch
+ [[ -f /etc/pihole/ftlbranch ]]
+ ftlBranch=development
+ local binary
+ binary=
+ local remoteSha1
+ local localSha1
+ which dnsmasq
+ [[ ! development == \m\a\s\t\e\r ]]
+ local path
+ path=development/
+ check_download_exists development/
++ curl --head --silent https://ftl.pi-hole.net/development/
++ head -n 1
' status='HTTP/2 200
+ grep -q 404
+ return 0
+ [[ -n /usr/bin/pihole-FTL ]]
++ curl -sSL --fail https://ftl.pi-hole.net/development/.sha1
++ cut -d ' ' -f 1
<b>curl: (22) The requested URL returned error: 404</b>
+ remoteSha1=
++ cut -d ' ' -f 1
+++ which pihole-FTL
++ sha1sum /usr/bin/pihole-FTL
+ localSha1=267fe19ff9d667bb76f192456eff7f26039d4fc2
+ [[ '' != \2\6\7\f\e\1\9\f\f\9\d\6\6\7\b\b\7\6\f\1\9\2\4\5\6\e\f\f\7\f\2\6\0\3\9\d\4\f\c\2 ]]
+ printf '  %b Checksums do not match, downloading from ftl.pi-hole.net.\n' '[i]'
+ return 0
+ FTL_update=true
+ echo -e '  [i] FTL:\t\tupdate available'
  [i] FTL:              update available
...
</pre>

**Steps to reproduce:**

Running `pihole -up` on the development branch

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`gmdi1ulxij`

**Troubleshooting undertaken, and/or other relevant information:**

If I understand correctly, [`update.sh`](https://github.com/pi-hole/pi-hole/blob/development/advanced/Scripts/update.sh#L131) calls function `FTLcheckUpdate()` from [`basic-install.sh`](https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L2381) and then the error occurs on line [2424](https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L2424), because variable `${binary}` is empty.

**Comment by dschaper** [comment]
This is a known bug and will be fixed in the next release. See https://github.com/pi-hole/pi-hole/issues/2986 for a temporary workaround if needed. 

What does `pihole -v` show for the currently installed version?

**Comment by Th3M3** [comment]
I had a look into the open issues before, but overlooked that is already reported. Sorry for that.

If is will be fixed in the next release, shouldn't it be already fixed in current development branch?

`pihole -v` outputs
<pre>
  Pi-hole version is v4.3.2-297-g7c2bbf8 (Latest: v4.3.2)
  AdminLTE version is v4.3.2-193-gca35942 (Latest: v4.3.2)
  FTL version is vDev-a21faf2 (Latest: v4.3.1)
</pre>

**Comment by dschaper** [comment]
It should be but it looks like #3003 didn't update `update.sh` to pass a binary name as the first positional argument to `FTLCheckUpdate()` so the update check has an emtpy `binary` variable.

**Comment by PromoFaux** [comment]
wheee. I'll take a look

**Comment by dschaper** [comment]
@Th3M3 Can you check the code to see if it's working for you? `pihole checkout core fix/300`

**Comment by Th3M3** [comment]
@dschaper The branch's name is  <code>fix/300<b>3</b></code> ;)
Yes, it works now. Thanks for that fast response and fix.

**Comment by dschaper** [comment]
Make sure you `checkout` back to development now that the fix has been merged there.
