### ISSUE TITLE
Include pihole-FTL as dependency in dependcy checks before install

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#3023]
Downloading `pihole-FTL` later in the installation process causes issues with `resolv.conf` changes to localhost. If there is no running DNS server then the download fails. 

Move the binary detection and download to the front end of the installation where we do a dependency check for required packages. 

Discussion for changing the DNS server to localhost is ongoing and will be addressed separately.

**Comment by dschaper** [comment]
#2566

**Comment by yubiuser** [comment]
Is this still an issue? Since v5.0 Pi-hole does not set `127.0.0.1` in `resolv.conf`. So even if `FTL` downloading fails, the host should still have a working internet connectiion.
