### ISSUE TITLE
Pi-hole installation silently fails during 'apt-get install --dry-run php7.0-sqlite3'

### ISSUE THREAD

**Issue by kehrnal** [pi-hole/pi-hole#3029]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**

`Successful install of Pi-hole`

**Actual behaviour:**

`Following install instructions at https://github.com/pi-hole/pi-hole/#one-step-automated-install, the install hangs at the following command indefinitely:`
![image](https://user-images.githubusercontent.com/40616297/70381682-699a9480-1914-11ea-9be0-0164b2032230.png)

**Steps to reproduce:**

`Running Armbian 5.73 stable on a Rock64.  Have already run sudo apt-get update.`

`curl -sSL https://install.pi-hole.net | sudo bash -x`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`None available, Pi-hole is not installed`

**Troubleshooting undertaken, and/or other relevant information:**

`Did some digging on git and found similar issue (https://github.com/pi-hole/pi-hole/issues/2771), but the solution here does not resolve.  Additionally, attempted to edit install script to force recognition of php-sqlite3 by setting phpSqlite="sqlite3" on line 243 and commenting out the remainder of the if statement on 242,244-6.  This caused the script to recognize the latest install of php7.0-sqlite3 (I finally see a checkbox after the Pi-hole ASCII art, but then it stalls again), but I don't know how to get verbose output from the install script and find out what is hanging now.`

**Comment by kehrnal** [comment]
Since did `bash -x` on the edited script and it actually still hangs at the same step.

**Comment by dschaper** [comment]
It's actually failing at `df -Pk` for the free available disk space check. What does that command return when run manually?

**Comment by kehrnal** [comment]
🤦‍♂️ This was it. I've had a HD on the fritz for a year and the telltale sign that something is going wrong is that `df` hangs. This one's on me
