### ISSUE TITLE
iFrame based ads display as "unable to connect" in Firefox

### ISSUE THREAD

**Issue by kamelkev** [pi-hole/pi-hole#303]
Certain ad networks use iFrames in order to display their ads. Yahoo happens to use some of these ad networks, so on certain pages on yahoo you'll see "dead" iFrames where the ads previously would have displayed.

It's obviously better than displaying the ad, but I noticed this only occurs in Firefox, which hints to me that something is going wrong somewhere.

See attached screenshots:

![screen shot 2016-02-10 at 12 56 25 pm](https://cloud.githubusercontent.com/assets/366498/12960124/ce73871a-cff6-11e5-9825-be2e3663e0f0.png)
![screen shot 2016-02-10 at 12 57 41 pm](https://cloud.githubusercontent.com/assets/366498/12960127/d089aac0-cff6-11e5-9795-dd2f6710d03b.png)

**Comment by PromoFaux** [comment]
Judging by the address the ad is supposed to be looking for (`secure.uac.advertising.com`) I would imagine it's trying to load an ad over https.

This is common to https ads, I've seen it quite a lot on chrome (e.g Youtube.com, or osxdaily.com) There is a way we can get around it by proving an SSL certificate, which would basically mean us doing a man-in-the-middle attack. This is currently under discussion.

Thanks for your submission!

**Comment by kamelkev** [comment]
Thanks for the quick reply.

So this issue does *not* occur in Safari or Chrome. It's literally only Firefox.

That being said, you are correct, the ad is coming through https. The domain for the dead iFrame noted above is:

`https://a.collective-media.net/`

**Comment by PromoFaux** [comment]
What extensions do you have on Firefox? Similarly on Chrome and Safari..

**Comment by kamelkev** [comment]
For firefox:
Web developer toolbar

For Chrome:
Google Docs
Google Docs (offline)
Google Sheets
Google slides

For Safari:
none

**Comment by PromoFaux** [comment]
Hmm OK, so nothing that checks for ads etc...

What is the link of the page you're looking at?

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/12960850/5d9d483e-d035-11e5-94ec-f44ce6eae66b.png)
An example of a similar ad in chrome

**Comment by kamelkev** [comment]
The page link is:
http://finance.yahoo.com/q?s=ATVI

The ads rotate here, and some are currently sneaking through. Refresh a few times and you should be able to catch it.

**Comment by PromoFaux** [comment]
Ah, I see. So the ad space on chrome is rendered, but there is no ad populating it. Same thing seems to be happening on Firefox, except Firefox complains it can't get to the ad it's requesting, rather than rendering nothing...

I'm currently dual running pi-hole and the uBlock Origin extension on Chrome, which catches a lot of the https errors (as ublock just hides them from view)

**Comment by kamelkev** [comment]
That's a great tip. uBlock is available for firefox, and I just installed it.

It might be worth having some documentation regarding synergistic applications like uBlock?

Anyways, the underlying issue persists, but this is good enough to get me through my work day. Thanks.

**Comment by DonLexos** [comment]
I can move this over to the general-faq at the wiki, but I am unsure what the proper solution was.

**Comment by PromoFaux** [comment]
Currently.. "Install ublock to hide those elements"

We're looking into other things we can do pi-hole side currently.

**Comment by dschaper** [comment]
The only comment I have is to make sure that we point to uBlock Origin https://github.com/gorhill/uBlock and not the other uBlock that's not quite as reputable.

**Comment by DonLexos** [comment]
I added this to the [FAQ wiki](https://github.com/pi-hole/pi-hole/wiki/FAQs)

**Comment by PromoFaux** [comment]
@DonLexos You da real MVP.

**Comment by DonLexos** [comment]
I do not get the hang of the whole branching, pulling and pushing of github (just yet) but I am able to get the hang of the GitHub markup. Therefor I thought I can jump into the documentation requests and get the info over to the wiki, and maybe help you guys out there to get the amount of issues down.

**Comment by Mcat12** [comment]
[This](https://guides.github.com/introduction/flow/) might help.

**Comment by PromoFaux** [comment]
It's much appreciated!

**Comment by DonLexos** [comment]
@Mcat12 thank you very much! I already tried to read into some of this using githubs own introduction, but these look very interesting.

**Comment by Mcat12** [comment]
You're welcome! Git can be hard to get into, but is pretty powerful.

**Comment by DonLexos** [comment]
This can be closed since it's in the wiki now.

**Comment by kamelkev** [comment]
Thanks guys. You are very responsive!

**Comment by bcutter** [comment]
Sorry but... how exactly can uBlock Origin change that behaviour? I installed it but I still get the unable to connect-errors...

**Comment by Mcat12** [comment]
It should remove the ad elements from view. Is that element an ad?

**Comment by bcutter** [comment]
No, the hole page is on the blocking list (https://www.econda-monitor.de). I thought uBlock-addon could handle this.

**Comment by Mcat12** [comment]
If you try to go directly to that site, then you will get the connection error because of the certificate mismatch between the browser and Pi-hole. Since uBlock Origin is programmed to remove ads (not full web pages), it won't handle this case. Because of the certificate mismatch, your browser won't trust Pi-hole to put any content on the page and will put up that warning page. Also, if the Pi-hole doesn't respond on port 443, then it will have an error page saying that it can't connect to the server.

**Comment by PromoFaux** [comment]
@bcutter It appears that domain is on the sysctl domain list. Simply adding that to the whitelist will resolve your issues (just tried this myself, you can use the admin frontend tool, or run the command `pihole -w www.econda-monitor.

It has nothing to do with uBlock, however, and is therefore out of context in this thread :)

**Comment by bcutter** [comment]
Got it. Sorry for the trouble.
