### ISSUE TITLE
Pihole -r cannot set DNS for unbound

### ISSUE THREAD

**Issue by jaerc** [pi-hole/pi-hole#3038]
Good morning,

I use unbound and a recursive DNS server on my raspi where pihole is installed. The DNS server points to 127.0.0.1#5353 regarding this configuration.

When I have to reconfigure the IP adress with pihole -r and try to set 127.0.0.1#5353 in the dns server section I get the information invalid IP address.

Therefore I have to set another dns server ip and later on in the pihole web configuration change it back to 127.0.0.1#5353

I would address a feature request, that 127.0.0.1#5353 can be set direct in pihole -r

Thank you
Chris

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
