### ISSUE TITLE
pi-hole stops functioning if user has umask set to 007

### ISSUE THREAD

**Issue by fayetted** [pi-hole/pi-hole#304]
Running gravity.sh as a normal, non-root user assumes sudo as needed however if the users umask is set to 007 or more restrictive the gravity.list file is regenerated with the user being the owner and 'world' not having read access to the file.

This causes dnsmask to be HUP'ed but can no longer read the gravity.list file and so no domains are blocked. 

The gravity.sh file currently changes permissions on all files in the $piholeDir but the gravity.list file is created later in the script where the umask has the ability to prevent proper access.

**Comment by PromoFaux** [comment]
What circumstances are you seeing `dnsmasq` not being able to read `gravity.list`?

It's not something I've come across so far...

**Comment by fayetted** [comment]
My normal user account has a umask of 037.  When I run /usr/local/bin/gravity.sh it knows I'm not root and so it runs as sudo and everything works.  Except for that on line 279 of gravity.sh you are creating a new file with the ">" and then on line 283 you cp that file over the top of $adlist.  Since you create a new file with echo  (not sudo echo) the file is owned by me (not root) and then it gets populated fine because I own it and even when sudo is used root can write to my file.  But in the end the file is owned by me and not by root, and because my umask was not 022 "world" doesn't have read access to it.  dnsmasq restarts but since it can not read the file it doesn't block anything.

This can be easily tested by logging in as pi, running 'umak 007', then run /usr/local/bin/gravity.sh.

You can verify the file is now owned by pi and permissions will be -rw-r-----.
Any lookups for domains in the gravity.list file will return their internet IP address.

I found this while building the script to check that pi-hole was functioning and after adding a new address to my blacklist file that address as well as addresses that were previously blackholed were now resolving to their actual address. 

I retested with my umask set to 022 (default) and it works fine.  But if the user changes their umask (like I did) then everything falls apart. 

I've already submitted PR #305 to address this.  Basically it just runs the chmod command one last time before reloading dnsmasq.  This should cover a number of instances where file permissions get messed with.

Let me know how your test goes though.  I ran through it several times but I was the only tester and I only did it on 2 different installs (1 production, 1 dev/test).  I'm curious if you can reproduce it.

**Comment by PromoFaux** [comment]
I'll take a look at this tomorrow (unless @jacobsalmela , @dschaper, or @Mcat12  get there before me!)

Just moved my pi-hole install to a full debian server on my network, so my Rpi is now free for tinkering :)

**Comment by PromoFaux** [comment]
Alas, life got in the way.

Just tested this. Logic is sound and it doesn't break anything. I'll merge it into development branch.
