### ISSUE TITLE
delete please

### ISSUE THREAD

**Issue by doobersn** [pi-hole/pi-hole#3040]
nevermind, deleted

**Comment by DL6ER** [comment]
How long ago did you assign the host names to the addresses?
Note that Pi-hole will check for new host names only once an hour. And for DHCP leases, it will only use them when a client has requested them at least once (otherwise, there is no reason to assume they are already used).

So worst case should be one hour after you made your client request a DHCP lease (restart or reconnect to the network).

**Comment by doobersn** [comment]
It has actually been a couple days. Just to make sure, I restarted one of the devices I made a hostname for and waited several hours and the hostname still isn't visible. Thanks for any suggestions on what to do!

**Comment by technicalpyro** [comment]
in `/etc/dnsmasq.d/01-pihole.conf` the option `dhcp-ignore-names=tag:hostname-ignore` is set remove that option (comment out the line) and restart  `FTL`

**Comment by doobersn** [comment]
I did that and then the internet stopped working. Checked pihole status and it said " [✗] DNS service is NOT running". This is in fact the second time that has happened this week. Last week I rebooted the pihole from the web gui and it did the same thing. I had to reinstall everything because I dont really know enough to figure it out. This is so frustrating. :( Thanks for any help.

**Comment by DL6ER** [comment]
> I did that and then the internet stopped working.

Well, this should not happen when you *remove* a setting.

What is the output of
```
tail /var/log/pihole.log
tail /var/log/pihole-FTL.log
```
after such a crash?

**Comment by doobersn** [comment]
I will try to find out what those outputs are. As of right now, though, I cant figure out whats going on. I think what happened is...when the pihole installation failed and I needed to use the internet, i made the router be the DHCP server again and changed the DNS server to automatic. Now, another device (ipad) has taken the IP of the pihole pi, and I cant for the life of me figure out how to force the IP to change. It wont work by clicking 'renew lease' on the ipad and I dont know what else to do. Argh.

**Comment by doobersn** [comment]
Well, for some reason it doesnt look like the pi is even connecting to the internet anymore. I set my router to be the dhcp server and changed the DNS back to automatic. I was still able to ssh into it last night, but no longer. I'm honestly at a loss. Looks like ill just have to reinstall again and hope it doesnt crash again.
