### ISSUE TITLE
Kind of complicated. Is there an easier way to do this? Is adding this rule in to /etc/dnsmasq.d/ messing with my pihole installation?

### ISSUE THREAD

**Issue by doobersn** [pi-hole/pi-hole#3043]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`The pihole working properly`

**Actual behaviour:**

`The pihole sort of working correctly`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

Ok, so, I have a Netgear router that doesn't allow me to set rules for redirecting devices that try to bypass the piholes DNS. I can set an IP range I want to block/redirect and that will work. My pihole is my DHCP server because for my router doesnt show info about which devices are doing what on the pihole; its all jumbled together. I wanted to have one device (iPad) bypass the pihole, but I obviously cant set the IP on my router since the pihole is the DHCP server and I cant manually set a different DNS on the device itself because of the rule I set in the router (it would get blocked).

So I asked on reddit and someone helped me. They told me I could insert this rule: `dhcp-host=<the mac address of the ipad>,set:customdns,192.168.1.200 (the IP of the iPad) dhcp-option=tag:customdns,option:dns-server,1.1.1.1,1.0.0.1`

to `/etc/dnsmasq.d/`

I am extremely bad at this kind of stuff so I have a few questions:

1. Why isnt the pihole dhcp server assigning the IP automatically? I have to manually set it. 

2. Can this be damaging my installation? Since i have set this code, when I restart the pihole, it doesnt work anymore...the DNS service doesnt start running again.

3. How does this work, exactly? If the DNS set in the device is not the DNS of the pihole, wouldnt it just bypass it completely (I did change the DNS in the device to 1.1.1.1,1.0.0.1) and then be blocked by the rules in my router?

4. Before doing this, I had my pihole assign IPs from 192.168.1.201-192.168.1.251. I then changed it to 192.168.1.200-192.168.1.251 and set the IP in the rule created to 192.168.1.200. Should I have kept the IP pool at 192.168.1.201-192.168.1.251 or changed it to 192.168.1.200-192.168.1.251 like I did?

5. Is there any easier way to do this that I'm missing? I feel like this is overly complicated. Before I would just go into the iPad and set the DNS server manually but I cant do that now because the router blocks it. I honestly am too illiterate in technological matters to know how it was getting an IP from the pihole but was able to bypass it.

Thanks!

Edit: this was the reply from the kind user who helped me figure this out:

> Interesting question! It is possible to use custom configs on the pihole via the /etc/dnsmasq.d/ directory

> Assuming the following:

>     Your DHCP pool is a subset of your subnet (ex. 192.168.1.1 thru 192.168.1.64)

>     Your router allows you to specify DNS redirect for just the above range

> I would allocate an IP outside of your DHCP pool using the dhcp-host option, use the 'set' key to tag it, and call the tag to apply a custom DHCP option to just that tag.

> Example, untested, in /etc/dnsmasq.d/99-custom.conf:

> dhcp-host=<mac of iPad>,set:customdns,192.168.1.100 dhcp-option=tag:customdns,option:dns-server,1.1.1.1,1.0.0.1

> Restart dnsmasq and networking on your iPad to test.

> It would be neat if pihole gui supported a custom config input for things like this but that would be a input validation/sanitization nightmare.

**Comment by dschaper** [comment]
Since this isn't a bug report or an issue with Pi-hole I'm going to close it out. I suggest opening a topic on https://discourse.pi-hole.net so that the community members can help with the questions you have.
