### ISSUE TITLE
Webinterface does not reflect ip changes

### ISSUE THREAD

**Issue by Alphaprot** [pi-hole/pi-hole#3044]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{After moving pihole to a new network, the IPv4-address shown on the web inteface in Settings>System} should show the new IPv4. If this does not work, at least reconfiguration with `pihole -r` should do the trick}`.

**Actual behaviour:**

`{An address change is not reflected on the webinterface (it is still showing the old address) and an attempted reconfiguration fails with "Error: Unable to update the package cache". Pihole works perferctly fine though.}`

**Steps to reproduce:**

`{Set up a pihole on RPi on one network, e.g. 10.10.10.xx, then move it to another network, e.g. 10.10.20.xx. Set the new address as a static address under /etc/dhcpcd.conf and reboot the Pi for the changes to take effect. As soon as the Pi and pihole are back up again, open the Web Interface Admin Console at the new IP and look into "Setting>System>Pihole IPv4 address"}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{https://tricorder.pi-hole.net/7umscjusyk}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Tried `pihole -r` to reconfigure the IPv4, but it failed (see above)}`

**Comment by technicalpyro** [comment]
```*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.100.4/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
```
From your debug token it appears the IP change was not made if you manually edit `/etc/pihole/setupVars.conf` to have the correct IP does it work as expected?

**Comment by Alphaprot** [comment]
> manually edit /etc/pihole/setupVars.conf to have the correct IP
This works, the webinterface shows the right IPv4 if I specify it in setupVars.conf

**Comment by technicalpyro** [comment]
i see further in your debug that in setupvars it does have the correct IP but things arent functioning as expected have you attempted rebooting the pi or restarting the pihole service?

**Comment by Alphaprot** [comment]
> in setupvars it does have the correct IP

That is not correct, this was the old IP.. While pihole/the webinterface was already reachable on the new IP, it still had the old IP in setupVars.conf.

> have you attempted rebooting the pi or restarting the pihole service?

Indeed, I rebooted the Pi after making the changes to /etc/dhcpcd.conf.

**Comment by technicalpyro** [comment]
just to be clear which is the new IP the .100.4 or the other one?

**Comment by Alphaprot** [comment]
.100.4 is the new IP address, 178.29 (iirc) was the old one.

**Comment by technicalpyro** [comment]
OK so there is another place that you need to update as well(unsure of why the reconfigure didnt update these)
```
-rw-r--r-- 1 root root 134 Dec 15 18:23 /etc/pihole/local.list
   192.168.178.31 pihole
   2002:6dc1:706b:0:2d60:474a:a154:83f1 pihole
   192.168.178.31 pi.hole
   2002:6dc1:706b:0:2d60:474a:a154:83f1 pi.hole
```
other than that you should be fine

**Comment by Alphaprot** [comment]
> 178.29 (iirc) was the old one

My bad, it was .178.31 as seen in the log snippet you just posted.
Okay, I'll update this aswell (even if it's already showing the correct IPv4 after updating the setupVars). Thank you for your support

**Comment by Alphaprot** [comment]
Sorry to bother you a second time - but is there a way to restart all pihole components? Pihole itself only has an option to restart the DNS (`pihole restartdns`) and systemctl has only `systemctl restart pihole-FTL.service` to restart the logging/data acquisition.

**Comment by technicalpyro** [comment]
restarting FTL will restart pretty much everything
