### ISSUE TITLE
Pi-Hole reports incorrect IP addresses for local hostnames, gives some external IP instead

### ISSUE THREAD

**Issue by UntouchedWagons** [pi-hole/pi-hole#3048]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Performing a dns lookup for hostnames I set up static DHCP leases should report the assigned IP address for that hostname

**Actual behaviour:**

DNS lookups for seemingly random hostnames are reporting an incorrect IP address not located on my LAN.

**Steps to reproduce:**

    ~  nslookup openvpn                   
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    Name:   openvpn
    Address: 192.168.0.40

    ~  nslookup bitwarden
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    Name:   bitwarden
    Address: 192.168.0.30

    ~  nslookup proxmox  
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    Non-authoritative answer:
    Name:   proxmox
    Address: 174.116.120.119

    ~  nslookup minecraft
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    Non-authoritative answer:
    Name:   minecraft
    Address: 174.116.120.119

`nslookup proxmox` should return 192.168.0.7 and `nslookup minecraft` should return 192.168.0.37, but they clearly don't.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/axotov6zj6

**Troubleshooting undertaken, and/or other relevant information:**

I've tried reloading the DNS Resolver and restarting the LXC container that Pi-Hole is installed in. The container is running Ubuntu 18.04. It seems that only the hostnames 'proxmox' and 'minecraft' are having issues.

**Comment by dschaper** [comment]
It looks like you have set the local domain name with `PIHOLE_DOMAIN` in `/etc/pihole/setupVars.conf` to be a domain that exists on the internet. The *.<name>.site domain resolves to 174.116.120.119.

Most likely Pi-hole does not know who `proxmox` is on the local network and is sending the query out as proxmox.<name>.site which resolves with public resolvers back to that 120.119 IP address.

**Comment by UntouchedWagons** [comment]
Yes I do have a .site domain for stuff like openvpn but it wasn't set up as a wildcard. Can you see that I set static leases for a proxmox and minecraft host name?

**Comment by dschaper** [comment]
The .site domain is acting like a wildcard however. If you `dig randomstuff.<name>.site @8.8.8.8` it will return that same 174.116.120.119 IP address instead of an NXDOMAIN. 

The debug doesn't show leases but I suggest that you use a different domain for your local network and not one that resolves on the public internet. Shadowing a domain is going to be troublesome.

**Comment by UntouchedWagons** [comment]
Okay, I had bought that domain so that I could be sure that there wouldn't be any possible collisions. Are there TLDs set aside specifically for local networks?

**Comment by dschaper** [comment]
`.local` is reserved for that, mDNS like Avahii/Bonjour default to it. Some use `.lan` or you can just go with plain hostnames without and domain attached.

**Comment by dschaper** [comment]
Another option would be to add a config file that specifies that .site domain to be local only. 

`/etc/dnsmasq.d/02-local.conf`
```
# Add local-only domains here, queries in these domains are answered
# from /etc/hosts or DHCP only.
local=/local.lan/
```

**Comment by UntouchedWagons** [comment]
I changed the domain to local, and reloaded the dns resolver, but when I run `nslookup proxmox.local` it says:

    ~  nslookup proxmox.local
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    ** server can't find proxmox.local: NXDOMAIN

It does the same for the minecraft hostname but none of the others.

**Comment by dschaper** [comment]
Does the proxmox show on the Network Overview page? https://discourse.pi-hole.net/t/pi-hole-4-3-now-available/19967

**Comment by UntouchedWagons** [comment]
It does but not with its hostname, it just shows up as 192.168.0.7

**Comment by dschaper** [comment]
It doesn't seem to be using Pi-hole as it's DHCP server.

**Comment by UntouchedWagons** [comment]
It is:

    root@proxmox:~# nslookup proxmox
    Server:         192.168.0.5
    Address:        192.168.0.5#53

    Non-authoritative answer:
    *** Can't find proxmox: No answer

**Comment by UntouchedWagons** [comment]
`nslookup proxmox.local` gives the right IP address now on the proxmox machine and on my desktop machine. Dunno what changed.

**Comment by dschaper** [comment]
Running the `nslookukp` probably caused the proxmox server to communicate with the DHCP server and register the lease. 

But it looks like everything is resolved. Please let us know if you have any other issues.
