### ISSUE TITLE
Add entries to whitelist in bulk

### ISSUE THREAD

**Issue by HyperCriSiS** [pi-hole/pi-hole#3053]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

Hi,

why can't entries to the whitelist be added in bulk via GUI?
As I read it is actually only possible by replacing the file.

Regards,
Hyper

**Comment by PromoFaux** [comment]
I'm not near my PC at the moment, but as far as I am aware you can add multiple entries by separating them with a space? I may be wrong, but worth a try!
