### ISSUE TITLE
basic-install.sh fails when uname -a  reports armv6l architecture (e.g. Pi Zero, ARMV6L SBC and LXC/LXD)

### ISSUE THREAD

**Issue by crouchingtigerhiddenadam** [pi-hole/pi-hole#3055]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

Reasonably.

---
**ISSUE Actual Behaviour:**
When running _basic-install.sh_ when _uname -a_ reports _armv6l_ architecture, the wrong pihole-FTL binary is installed. The issue is around basic-install.sh line 2265.

Might be related to issues 2636 and 1756.

Can be worked around with:

```
# Fix systemd-resolved conflict
systemctl stop systemd-resolved
systemctl disable systemd-resolved
systemctl mask systemd-resolved

# Get deps
apt update
apt -y upgrade
apt -y install apt-utils build-essential dhcpcd5 dnsmasq git libgmp3-dev m4 nano nginx openssl php-fpm php-sqlite3 resolvconf wget
wget https://ftp.gnu.org/gnu/nettle/nettle-3.4.tar.gz
tar -xvzf nettle-3.4.tar.gz
git clone https://github.com/pi-hole/FTL

# Build nettle
cd nettle-3.4
./configure
make
make install

# Build FTL for armv6l
cd ../FTL
make

wget -O - https://install.pi-hole.net | bash -
make install
systemctl restart pihole-FTL
```

**Log file output [if available]**

```
/usr/bin/pihole-FTL: No such file or directory
Invalid Option! Try 'pihole -v --help' for more information.
```

**Device specifics**

Hardware Type: Generic armv6l but can be replicated using LXC on Rasperry Pi Zero*
OS: Debian Buster (though all editions are probably effected.)

* If using Raspberry Pi Zero to replicate (not advised for live), create the container using _sudo lxc-create pihole -t download -- -d debian -r buster -a armel_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Please check with the latest released version.

**Comment by crouchingtigerhiddenadam** [comment]
I've tried v4.4 and I still get the same issue. The binary downloaded with the install cannot work on a soft float operating system.

**Comment by dschaper** [comment]
Pi Zero has worked every time it's been tried by myself and others.

A debug token would help a lot.

**Comment by crouchingtigerhiddenadam** [comment]
To be clear, if I use a Raspberry Pi Zero, with just the Raspbian Lite on the memory card and install pihole, it works every time. Great job guys!

If I run pihole on any non Raspberry Pi ARM6 SBC in my collection running Debian Buster (armel) will give me a problem where /usr/bin/pihole-FTL is not executable. Running /usr/bin/pihole-FTL manually returns `pihole-FTL is not a valid executable program.`

If I clone the source from github, run `make` and `make install` the resulting executable works and so does pi hole.

It just happens that you can replicate the problem if you have an ethernet adapter or Cluster Hat connected to a Pi Zero in an LXC container. I'm using a stock Debian container (not Raspbian) which is also compiled the armel architecture. You don't need LXC, you can just create a memory card with the 0w image from here:

https://people.debian.org/~gwolf/raspberrypi/20190628/

I am aware than running `uname -a` on Raspbian Buster and a Raspberry Pi Zero will return ARM6L and everything works. But trying the same on a Debian Buster armel compilation reporting ARM6L for me does not.

**Comment by dschaper** [comment]
Buster is most likely the issue then. It's bleeding edge and never has been supported.

**Comment by dschaper** [comment]
Sorry, I misspoke about Buster. Why did you decide to use an image base that is diverged from the officially supported one?

**Comment by crouchingtigerhiddenadam** [comment]
I had a few unbranded ARMv6 devices that I had little purpose with. I thought I might use them to run pihole, but their stock operating system is either Ubuntu or Debian (armel.) At some point I wanted to try running it on a SheevaPlug, which is a cheap linux computer with gigabit ethernet built into a plug socket (actually ARMv5).

When it didn't work, I was wondering whether it was just the board or the operating system. I thought I'd try Buster (armel) to see if the problem would happen on other devices (which it does.) Then I tried Buster (armhf) on devices with ARMv7 and ARMv8 processors and I didn't get any issues.

With Debian there is an armhf and armel repository. With Raspbian you just have an armhf repository. Pihole works on a Pi Zero (arm6l) with Raspbian. However, you can't run an armhf container on a pi zero, which I think causes people issues with the ClusterHAT, Kubernetes and Docker. So there is more going on.

I'm 100% sure the defining variable is the operating system.

However, compiling pihole-FTL from source and installing it seems to fix the issue. Maybe these are fringe cases, this just needs to be documented somewhere rather than included in the main script (which is why I didn't make a pull request.)

The devices this might be a good fix for are:

- OpenRD
- Pogoplug
- Seagate DockStar
- Seagate GoFlex
- SheevaPlug
- TonidoPlug <= 2
- ZyXEL NSA320/325
- Pi Zero with Ethernet or Pi3A/B/4B with ClusterHAT and Zeros running containers (e.g. LXC.)

**Comment by dschaper** [comment]
Unfortunately I think it's just going to be an edge case that has to be dealt with manually.

**Comment by crouchingtigerhiddenadam** [comment]
Before closing this issue, what do you think the best thing to do would be. Write up an unsupported work around for review (like the NGINX documentation), or make an unofficial/unsupported script that can be used insted that mirrors the original script but compiles pihole-FTL from source.

**Comment by dschaper** [comment]
Have a look at https://docs.pi-hole.net/ftldns/compatibility/ and https://docs.pi-hole.net/ftldns/compile/ first to see if that is helpful in any way.

**Comment by dschaper** [comment]
If there is a reliable way to know that the binary has to be compiled, and there's a way we can check for that condition, then I'd be open to adding to the official installer and have it notify users of the condition. Discussion would be needed on the course of action after that, i.e. do we compile, link to a site for instructions to compile, abort the install, etc.

**Comment by crouchingtigerhiddenadam** [comment]
Thank you for your feedback and advice. As always, what ever helps I'm happy to go along with. I will give your last comment serious thought. If I can make it work with minimal changes I'll put a version on my github for review and discussion.

**Comment by yubiuser** [comment]
There was significant improvement in the binary detection routine (https://github.com/pi-hole/pi-hole/pull/3801). Please check if the issue persists.
