### ISSUE TITLE
FeatureRequest: Login/Logout/Failed Attemps to pihole-FTL.log

### ISSUE THREAD

**Issue by Gill-Bates** [pi-hole/pi-hole#3057]
To harden the web interface, it would be great if all login attempts that failed would show up in pihole.log. Then I could create a Fail2Ban rule using Regex.

It would be even better if the Pihole Installer checks directly if Fail2Ban is installed and implements his own ban rule automatically.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
