### ISSUE TITLE
Connection refused on gravity update

### ISSUE THREAD

**Issue by RienBijl** [pi-hole/pi-hole#3061]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

After running `pihole -g` i expect to see my pihole to pull new lists and update the local cache, without any issues.

**Actual behaviour:**

All my lists have `Status: Connection Refused`, and no local cache available.

**Steps to reproduce:**

Everything done on this machine before issue popped up: get a fresh machine with raspbian, run the install script, enable the dhcp server and try to update the lists.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`slbarzzfia`

**Troubleshooting undertaken, and/or other relevant information:**

I ran pihole -r and did a fresh install. This did not resolve the issue.

**Comment by dschaper** [comment]
Check `/etc/resolv.conf`. If it's a single entry of `127.0.0.1` then change the file to contain an accessible DNS server (`8.8.8.8` or `1.1.1.1` or your preferred choice). Then repair and update the lists.

**Comment by RienBijl** [comment]
Did the above, resolv configuration did indeed only contain 127.0.0.1, after adding 8.8.8.8 and a repair, gravity still won’t update.

No change in error message, still Connection Refused

**Comment by SkyYkb** [comment]
Try to clear the DNS cache after modify resolv.conf.
