### ISSUE TITLE
Can't login to interface

### ISSUE THREAD

**Issue by Thomas499** [pi-hole/pi-hole#3065]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{When I type in password for pihole for it to bring up the page loggin to the interface}`

**Actual behaviour:**

`{when I type in the password this is what comes up, its as if I didn't login}`
![image](https://user-images.githubusercontent.com/38442058/71643216-830cd300-2c6b-11ea-937f-60e5e025c64e.png)
Note: if I type in wrong password it does tell me incorrect password. But when I type in correct password it takes me to the page above as if I didn't log in. 

**Steps to reproduce:**

`{On my pi, i type in 192.168.1.123 and it brings me to the interface. I then type in the password and at that point it comes up as if i hadn't typed in a password at all. I do seem to remember the other day when I did a update of the list it said the last list couldn't be loaded due to memory or something along those lines. But pi hole is the only thing I use the raspberry pi for and I hadn't added any new list recently. I also tried restarting the pihole from putty interface and checked that everything was up to date. Still, the issue persist}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{https://tricorder.pi-hole.net/1vw9wt8tz2}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by DL6ER** [comment]
Do you see this with a different browser? Maybe also try to access the page from you phone.
It looks like the browser you used doesn't accept cookies. However, a local cookie is necessary to stay logged in (it identifies your browser).

**Comment by Thomas499** [comment]
I just tried it with google chrome browser and confirmed the same results that I experienced with firefox browser. I also tried it on my phone using firefox browser and on my room mates phone using samsung internet browser and had the same results. 

Additional info: when I type in pihole -c this is what comes up. I noticed HDD usage is 100%. Not sure what that means but might shed additional info to make debugging easier. 

![image](https://user-images.githubusercontent.com/38442058/71643359-a6d11880-2c6d-11ea-9e4a-2fbe5862eeb2.png)

**Comment by dschaper** [comment]
Check the amount of free space on the Pi-hole device. 

```
   2019-12-31 18:12:00: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: write failed: No space left on device (28) in Unknown on line 0
   2019-12-31 18:12:00: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5/sessions) in Unknown on line 0
   2019-12-31 18:12:00: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: write failed: No space left on device (28) in Unknown on line 0
   2019-12-31 18:12:00: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5/sessions) in Unknown on line 0
   2020-01-01 15:27:36: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: write failed: No space left on device (28) in Unknown on line 0
   2020-01-01 15:27:36: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5/sessions) in Unknown on line 0
   2020-01-01 15:27:39: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: write failed: No space left on device (28) in Unknown on line 0
   2020-01-01 15:27:39: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5/sessions) in Unknown on line 0
```

Check the networking interfaces:

```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.1.123/22 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

[✓] IPv6 address(es) bound to the eth0 interface:
   fe80::62a7:74d3:4c2c:828b does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

   ^ Please note that you may have more than one IP address listed.
   As long as one of them is green, and it matches what is in /etc/pihole/setupVars.conf, there is no need for concern.

   The link to the FAQ is for an issue that sometimes occurs when the IPv6 address changes, which is why we check for it.
```

Check the `lighttpd` daemon

```
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
```

And check if you can Pi-hole is even resolving

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] www.failure-3a7yi9.stream is 0.0.0.0 via localhost (127.0.0.1)
[✗] Failed to resolve www.failure-3a7yi9.stream via Pi-hole (192.168.1.132)
[✓] doubleclick.com is 172.217.12.110 via a remote, public DNS server (8.8.8.8)
```

**Comment by DL6ER** [comment]
Thanks for checking @dschaper - @Thomas499 It will be the full disk. Now that it has been mentioned, I recall having seen this before a few times.

**Comment by Thomas499** [comment]
**Check the amount of free space on the Pi-hole device.**

![image](https://user-images.githubusercontent.com/38442058/71644629-72b32300-2c80-11ea-9508-30b83d0d253a.png)
Note: pihole is the only thing that runs on the raspberry pi. Is there anything pihole uses that would cause the /dev/root memory to be 100% full? Is there a file that I can delete that pihole stored?

As far as the 

> Please verify that the current setting of session.save_path is correct (/var/lib/php5/sessions) in Unknown on line 0

The file appears to be locked. I can look up how to change permissions if you want but since I haven't changed anything in the file is that what you want me to do?
![image](https://user-images.githubusercontent.com/38442058/71644663-1d2b4600-2c81-11ea-8836-7d51ef7321ea.png)

**Check the networking interfaces:**

To log onto the pi from putty i type in 192.168.1.123 I also type that into the url of a web browser to access the pihole interface. For some reason pi hole does say 192.168.1.132/24 which doesn't match anything else but it has always been this way. Here is a screenshot of the /etc/pihole/setupVars.conf file
![image](https://user-images.githubusercontent.com/38442058/71644737-41d3ed80-2c82-11ea-8575-049708609f00.png)

here is a screenshot of the /etc/lighttpd/lighttpd.conf file. server.username and server.groupname  are correct which was the issue in https://github.com/pi-hole/pi-hole/issues/576 but does not appear to be the issue here. 
![image](https://user-images.githubusercontent.com/38442058/71644766-c58dda00-2c82-11ea-9498-75d9a272235c.png)
I also tried sudo systemctl restart lighttpd without any luck getting the interface to work.

**And check if you can Pi-hole is even resolving**
I typed in http://www.doubleclick.com/ into the search bar of my computer which is a url that pihole should block. My computer was not allowed to connect to the url so I think that means the pihole is blocking the url. If there is a better way to identify if the pihole is resolving please let me know and I will be happy to try it. 
![image](https://user-images.githubusercontent.com/38442058/71644863-28cc3c00-2c84-11ea-9845-8b2df2c412b4.png)

**Comment by Thomas499** [comment]
So how do I fix the full disk space issue? Pihole is the only thing that runs on the pi and I haven't added any list or anything to pihole is a while.

**Comment by dschaper** [comment]
You'll have to find what files to delete, we can not provide any guidance with that.

**Comment by Thomas499** [comment]
The only thing I have ever used the raspberry pi for was pihole. So what I was asking was is there a file that pi hole created that is taking up all the memory that I should delete?

**Comment by dschaper** [comment]
Not really, but it looks like you are running Jessie (8) which hasn't been supported by Raspbian in quite a while, and is not supported by Pi-hole. I suggest that you get a new SDCard and go with Raspbian Buster (10).

**Comment by Thomas499** [comment]
Thanks. I honestly though sudo apt update /upgrade would have updated the system to buster version. Is there a way to back up all my pi hole settings through the command prompt putty method without using the normal interface from a web browser that I can't log into?

**Comment by Thomas499** [comment]
For some reason the pihole -FTL.db file in /mnt/etc/pihole was 489,431,040 bytes and deleting it fixed the problem.
