### ISSUE TITLE
Blocked queries are shown in permitted list with .mydomain

### ISSUE THREAD

**Issue by HyperCriSiS** [pi-hole/pi-hole#3069]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`{1}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/ynmw81u91s`

Hi,

the address mon.toutiao.com for example is listed under Top Blocked Domains, but it is also under Top Permitted Domains but there as mon.toutiao.com.*mydomain*.
Status: OK (cached) 
Reply: NODATA

So according to the reply it is still blocked. If I block this entry, it is moved to the top blocked list.
There are several addresses with this behavior.
Is this a bug?

Thanks,
Hyper

**Comment by dschaper** [comment]
Some client on your network is querying those addresses. It's probably getting a negative response for `domain.com` and trying again as `domain.com.mydomain`. Windows clients seem to do this.

**Comment by HyperCriSiS** [comment]
OK, I understand. But then it should not be in the permitted list, because actually it was not permitted, as response was also here "NODATA".

**Comment by dschaper** [comment]
It wasn't blocked so the only other option is to be permitted?

**Comment by HyperCriSiS** [comment]
I set block mode to "NODATA" and the reply was "NODATA", so yes, it was blocked, but is in permitted list.

**Comment by dschaper** [comment]
It's NODATA because the record doesn't exist. It's not being blocked.

**Comment by dschaper** [comment]
The ideal solution is to fix the client sending out the queries, not to patch out the display to counter a malfunctioning client.

**Comment by HyperCriSiS** [comment]
Any idea what causes this behavior?

**Comment by dschaper** [comment]
Depends on the client. If it's linux based then you can check `/etc/resolv.conf` and remove any `search` lines that would cause the client to add the listed domain to any queries. Other operating systems would need equivalent configuration modification.
