### ISSUE TITLE
Feature request: Conditional forwarding for multiple domains

### ISSUE THREAD

**Issue by stefan1983** [pi-hole/pi-hole#3071]
I've got the need to forward not one but two local domains, currently this is not possible as far as I can see (or is there?).

Thanks

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
