### ISSUE TITLE
Server Restart Causes DNS Failure (Debian 10)

### ISSUE THREAD

**Issue by 42CF11059F2F** [pi-hole/pi-hole#3075]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** 1

---
**Expected behaviour:**
On restarting the server, pi-hole should resume operation and all devices will have access to the local network and internet via the pi-hole DNS service.

**Actual behaviour:**
Following any server restart (forced / unexpected / etc.), pi-hole is started and running but no device can access any internal / external resources.

Devices already on the network (i.e. have IP addresses) can still be reached via the IP address.

On SSH into the server and running a command such as sudo pihole status, everything starts working again.

**Steps to reproduce:**
1. Install pi-hole and confirm it is running as expected.
2. Restart the server.
3. Check for network availability.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
qad3l8g5v2

**Troubleshooting undertaken, and/or other relevant information:**
Only basic checking to discover where the problem was in terms of overall network failure following the restart and discovering the "fix".

A cron command `@restart sleep 30 && /usr/local/bin/pihole status` ensures DNS is recovered following a restart event.

This is a setup on Debian 10. Not a typical Pi-Hole setup as I'm trying to remove the need to have the Raspberry Pi running. I appreciate this may in itself cause issues.

**Comment by yubiuser** [comment]
Does this issue still persists?

**Comment by 42CF11059F2F** [comment]
I don't know. I changed my network setup to use 2x Pi Zero W for Pihole to avoid the problem.

**Comment by yubiuser** [comment]
Thanks for the feedback
