### ISSUE TITLE
Pihole does not have DNSSEC enabled on a reboot (fine while running after initially setting it)

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#3077]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`4`

---
**Expected behaviour:**

When **Use DNSSEC** under Settings>DNS, pihole should have this feature enabled.

**Actual behaviour:**

Upon initially enabling **Use DNSSEC**, pihole functions as it should, logging codes like "SECURE" and "INSECURE" as queries are sent to it.  The bug I am seeing occurs on a reboot of the pihole box.  Despite the **Use DNSSEC** having a check mark on it, I do not get the expected annotations in the log.  As well, if I run `dig +dnssec debian.org` on the freshly booted pihole, I do not get the expected **ad** flag in the output

**Steps to reproduce:**

To fix the behavior, I need to uncheck **Use DNSSEC** and hit **save**  then check it and hit **save**, the behavior returns to normal both with respect to the query log and to assing the **ad** flag in the `dig` output.  Again, this only happens if I reboot pihole, it stays enabled for weeks until that reboot.

I cannot provide the debug token as this is running from the unsupported Arch Linux packages
* https://aur.archlinux.org/packages/pi-hole-server/
* https://aur.archlinux.org/packages/pi-hole-ftl/

Here are some logs on a fresh boot:
* [pihole.log](https://gist.github.com/graysky2/9902a46806b3435662f8ec0dd008e021)
* [pihole-ftl.log](https://gist.github.com/graysky2/4a80932e5c7ba53b09cc39f6f31f41f9)

The next two are after I uncheck, save, check, save the **Use DNSSEC** option:
* [pihole.log](https://gist.github.com/graysky2/fd53cfd3f8923e0c21bb94a19d2fc638)
* [pihole-ftl.log](https://gist.github.com/graysky2/1f3fe31b1e3ffdea118312f934b1533e)

What exactly happens when a user checks the **Use DNSSEC** box and hits **save**?  Perhaps something in the Arch packaging is not doing all the steps?

**Comment by SkyYkb** [comment]
I met the similar problem.
But in my query log, there are some queries logged with DESSEC data, and some are not.
I set Google Public DNS, Quad 9 DNS and AdGuard DNS as upstream server at same time. In them above, Google Public DNS doesn't support DNSSEC at this moment.
So maybe you can check your upstream server settings to make sure all of your upstream server support s DNSSEC.

**Comment by dschaper** [comment]
Arch modifies many of the files with patches to accommodate unsupported front ends and paths. You'll need to contact the patch creators and see what they have to say.

**Comment by SkyYkb** [comment]
But I am running Pi-hole on Raspbian and meeting this problem, too.

**Comment by graysky2** [comment]
@SkyYkb - What you describe doesn't match what I reported.  My problem is no DNSSEC on a reboot but after disabling it and reenabling, it works fine.  You are also mistaken about DNSSEC support with cloudflare.  Please do not hijack this issue with something related you are experiencing.

@dschaper - I know there are patches at play on Arch.  What exactly happens when a user checks the **Use DNSSEC** box and hits s**ave**? Perhaps something in the Arch packaging is not doing all the steps or preventing the actions pihole is trying to take.

**Comment by SkyYkb** [comment]
@graysky2 
Sorry about that. Maybe the comment I wrote isn't very clearly. But in my case, actually I need to initially setting it, too. I just wanted to suggest you to check your upstream server settings.

Actually, I didn't see any content about DNSSEC support on Cloudflare's website, so sorry about my wrong cognition.

So I think I should retell my behavior again.
When I reboot my Raspberry Pi, I have to re-enable the DNSSEC settings to make DNSSEC function work properly. I think that is really similar to your issue. Right?

**Comment by dschaper** [comment]
>What exactly happens when a user checks the Use DNSSEC box and hits save?

https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/savesettings.php#L291

**Comment by graysky2** [comment]
@dschaper - Thanks for that, Dan.  I don't know php but it looks like it's checking the settings in the web GUI and then calling `pihole` to setup the DNS server and forwarding, etc.

Can you help me to reconstruct the calls to `/usr/bin/pihole` based on my settings shown in the pic?  I would like to reboot the machine, then, rather than going through the GUI, simply try running the call manually to see if that fixes my issue.

I think one of the calls needs to be:
`sudo pihole -a setdns 1.1.1.1,1.0.0.1 dnssec`

That however clears my settings under Advanced DNS Settings.

![my 85](https://user-images.githubusercontent.com/534822/72376359-ce979600-36db-11ea-93c8-58388fbba7bf.jpg)

**Comment by dschaper** [comment]
`pihole -a setdns` (shouldn't need `sudo`, if priv's are required then you will be prompted for password) calls https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh#L216

**Comment by graysky2** [comment]
@dschaper - If I just run `pihole -a setdns` it completes successfully but it clears out my Advanced DNS settings:
```
% pihole -a setdns
  [✓] Restarting DNS service
```

![gone 85](https://user-images.githubusercontent.com/534822/72382480-5931c280-36e7-11ea-98bf-d9ceb1f0e861.jpg)

**Comment by dschaper** [comment]
You'll need to read the section of code that I linked to and see what commands are needed after `pihole -a setdns` to accomplish what you intend.

**Comment by graysky2** [comment]
I am finding it difficult to interpret the code and parse out what I need to, truth be told :)

**Comment by dschaper** [comment]
If Arch doesn't use `setupVars.conf` then it's diverged greatly from Pi-hole.

**Comment by graysky2** [comment]
@dschaper - It absolutely uses `setupVars.conf`

**Comment by dschaper** [comment]
Then I'm not understanding what you mean by recreating `setupVars.conf`?

**Comment by graysky2** [comment]
When I run `pihole -a setdns`,  I find that `/etc/pihole/setupVars.conf` is modified.

* [Here](https://gist.github.com/graysky2/b7d89ed32c6ee62e1af1e901d6efdd35) it is when I setup using the WebUI.
* [Here](https://gist.github.com/graysky2/730aad0483ea8b941efbf2b8061c68ce) it is after I run the command from the shell.

Is this expected?

**Comment by Altycoder** [comment]
This is still a problem even in the latest release PiHole 5.2.1, Web 5.2.1, FTL 5.3.2.

Using docker, on reboot the 3 checkboxes on the DNS settings page: "Never forward non-FQDNs", "Never forward reverse lookups for private IP ranges" and "Use DNSSEC" are always unchecked on reboot.
