### ISSUE TITLE
Data reset when restart.

### ISSUE THREAD

**Issue by SkyYkb** [pi-hole/pi-hole#3078]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

There will show all the number of my queries on Admin Console. Just like this (This screenshot is captured from long term data page`http://pi.hole/admin/db_queries.php`): 
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/44992049/72260567-196acc80-364e-11ea-8d23-7fcb4b52d578.png">

**Actual behaviour:**

There is only some number of my queries. Just like this (This screenshot is captured from index page of Pi-hole Admin Console`http://pi.hole/admin/index.php`):
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/44992049/72260593-25ef2500-364e-11ea-8959-980f0e71b697.png">

**Steps to reproduce:**

Just restart the DNS resolver (Click the button on setting page or use`sudo service dnsmasq restart`)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`mhxb3c7ary`

**Troubleshooting undertaken, and/or other relevant information:**

I think that restart DNS resolver will reset the data on the index page of Pi-hole Admin Console, but the data will save to long term data? Is that right?
Or is it a bug?

**Comment by SkyYkb** [comment]
OK, I just find something may make this issue easier to solve in the log (I just regenerated the log).
See that:
```   [2020-01-13 22:23:00.084 23102] SQLite3 message: statement aborts at 34: [INSERT INTO queries VALUES (NULL,?,?,?,?,?,?)] attempt to write a readonly database (8)
   [2020-01-13 22:23:00.085 23102] save_to_DB() - SQL error (8): attempt to write a readonly database
   [2020-01-13 22:23:00.085 23102] SQLite3 message: statement aborts at 34: [INSERT INTO queries VALUES (NULL,?,?,?,?,?,?)] attempt to write a readonly database (8)
   [2020-01-13 22:23:00.085 23102] save_to_DB() - SQL error (8): attempt to write a readonly database
   [2020-01-13 22:23:00.085 23102] SQLite3 message: statement aborts at 34: [INSERT INTO queries VALUES (NULL,?,?,?,?,?,?)] attempt to write a readonly database (8)
   [2020-01-13 22:23:00.085 23102] save_to_DB() - SQL error (8): attempt to write a readonly database
   [2020-01-13 22:23:00.085 23102] save_to_DB() - exiting due to too many errors
   [2020-01-13 22:23:00.129 23102] SQLite3 message: statement aborts at 21: [INSERT INTO network (ip,hwaddr,interface,firstSeen,lastQuery,numQueries,name,macVendor) VALUES ('192.168.101.10','<A MAC address>','wlan0',<A digit string may include personal information>, 0, 0, '', 'Apple, Inc.');] atte (8)```
So it's a SQL issue now.

**Comment by DL6ER** [comment]
Yes, something happened either to your database or the folder containing it.

What is the output of the following commands?
```
ls -lh /etc | grep pihole
ls -lh /etc/pihole/pihole-FTL.db
```

The folder should have permissions/ownership `drwxrwxr-x ... pihole pihole`
The file  have permissions/ownership `-rw-r--r-- ... pihole pihole`

**Comment by SkyYkb** [comment]
See that:
```
pi@raspberrypi:~ $ ls -lh /etc | grep pihole
drwxr-xr-x 2 pihole pihole 4.0K Jan 13 23:01 pihole
pi@raspberrypi:~ $ ls -lh /etc/pihole/pihole-FTL.db
-rwxr-xr-x 1 root root 628K Jan 12 17:35 /etc/pihole/pihole-
FTL.db
```

**Comment by DL6ER** [comment]
Yes,
```
sudo chown pihole:pihole /etc/pihole/pihole-FTL.db
```
should do the trick.

**Comment by SkyYkb** [comment]
Okay, problem solved with your solution.
Thank you!
