### ISSUE TITLE
IP address configuration - interface not being set correctly?

### ISSUE THREAD

**Issue by edbird** [pi-hole/pi-hole#3079]
Brief overview:

Installed Raspbian on a Raspberry Pi, current version obtained from raspberrypi.org. Board is RPi-4. Installed Pi-Hole using curl method. OS is the minimal (no graphical environment) version.

I attempted to set this system up as a DNS & DHCP server.

I have spent a few days trying to do this - so my memory may not be 100 % perfect regarding everything I have changed/attempted to change.

I tried to set a static IP for the device using `/etc/dhcpcd.conf`. After playing with this for a while, I realized that it appeared to be having not effect on the IP of the device.

I googled the issue and discovered PiHole [must have] some other [non standard?] way of setting the interface IP?

I ran `pihole -r`, followed the steps to configure the network IP and gateway.

However the IP is still not being set correctly.

Note that at the moment, the PiHole DHCP server is disabled.

`ip address` produces the following output

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:59:fa:9b brd ff:ff:ff:ff:ff:ff
    inet 169.254.119.219/16 brd 169.254.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::61ec:2949:f701:76b8/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether dc:a6:32:59:fa:9c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global dynamic noprefixroute wlan0
       valid_lft 81222sec preferred_lft 70422sec
    inet6 fe80::aa8:f2f:6ae1:8ed1/64 scope link 
       valid_lft forever preferred_lft forever
```

Regarding `3: wlan0`, that IP is set by my ISP router. This is ok - I am only using this interface to get the system set up, before disabling wifi access.

However `eth0` claims that it cannot set the static ip requested `192.168.2.1/24`, and has assigned itself a link-local address, which no other devices connected to my switch are aware of. The only other device connected to this switch is my router, which has the address `192.168.2.254`. Note that this device really is a router and has nothing do do with my "ISP router" which is actually a router, switch and access point all-in-one. (Of course you are not surprised to learn this.)

At this point I'm asking for help because I don't know how to proceed. I don't know why the address `192.168.2.1` is not being assigned to interface `eth0`, and I don't know what steps I should take to further diagnose this.

There isn't much documentation regarding PiHole that I have been able to consult. I realize that part of the reason for this may be that it is designed to be "simple and easy to get working", and that it is assumed the average user will never have to consult any docs. In my case, I have a non-standard network setup. (In other words, my setup is "weird".) Without documentation I have not been able to make much progress diagnosing/resolving the issue.

As a quick summary, I have a primary network `192.168.1.X`, which other users in my building use, and then a secondary network `192.168.2.X` which only I use. The PiHole device is on my own network.

For me personally, it would have been useful to know what servers are used for DNS and (particularly) DHCP, and further to this, what daemons/etc are used when setting network interfaces settings - because clearly it isn't the regular systemd networking service, but it took me hours to figure that out.

I think it's a great project by the way and hope none of this sounds unduly negative.

**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I expect the interface `eth0` to be assigned the static IP `192.168.2.1`.

**Actual behaviour:**

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:59:fa:9b brd ff:ff:ff:ff:ff:ff
    inet 169.254.119.219/16 brd 169.254.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::61ec:2949:f701:76b8/64 scope link 
       valid_lft forever preferred_lft forever
```

**Steps to reproduce:**

Install PiHole on RPi 4. Connect to router via switch. Router is another Raspbian device, routes from network `192.168.1.X/24` to `192.168.2.X/24` - note this may not be necessary, at the moment I don't know why the IP is not being set as expected, I imagine there could be a multitude of possible reasons, one of which may be my specific network setup?

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}` (none, is this required or helpful?)

I notice that the gateway (`DHCP_ROUTER`) address is not set correctly. Currently set to `192.168.1.254` but should be `192.168.2.254`. I looked around the web UI but could not find where this should be changed. I found that I could change it in `/etc/pihole/setupVars.conf`. Is this a bug? Should there be a way to change this in the web UI?

Note: I can access the web UI on `192.168.1.1`, this will no longer be available when I take the wifi connection down.

Even after changing the gateway in this file, the issue persists. This makes me wonder if `DHCP_GATEWAY` is something different to what I think it is?

**Troubleshooting undertaken, and/or other relevant information:**

Made several enquiries online, before realizing that systemd networking service is seperate from how PiHole manages network interfaces. I don't know anything about how PiHole does this therefore I was not able to make further enquiries.

**Comment by dschaper** [comment]
IP addressing is set with `dhcpcd5` with the same `/etc/dhcpcd.conf` file as used in plain Raspbian. 

What does that file contain?

**Comment by edbird** [comment]
It contains the following

```
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# Most distributions have NTP support.
#option ntp_servers

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
slaac private

# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
interface eth0
	ip_address=192.168.2.1/24
	routers=192.168.2.254

```

**Comment by edbird** [comment]
Another weird behaviour I am noticing is that my (ISP) router intermittently doesn't pick up the PiHole device via wifi. (Seeing this behaviour via the ISP Router web GUI)

**Comment by dschaper** [comment]
That IP declaration block is incorrect, and looks like it was not set by the installation script.

Note the `static` keywords that prefix the configuration lines:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L828

**Comment by edbird** [comment]
Ok changed it to the following:

```
interface eth0
static ip_address=192.168.2.1/24
static routers=192.168.2.254
```

Can I ask, why is it different and non-standard? Surely that is just a source of confusion and contradiction with existing information?

**Comment by dschaper** [comment]
```
interface eth0
	ip_address=192.168.2.1/24
	routers=192.168.2.254
```
That is not correct, and is not a limitation of Pi-hole but of Raspbian. Raspbian uses `dhcpcd5` for IP addressing as you would see if you edit `/etc/network/interfaces`. Pi-hole uses the exact same method, files and syntax as Raspbian.

```
interface eth0
static ip_address=192.168.2.1/24
static routers=192.168.2.254
```

That is how stock Raspbian and Pi-hole both are configured.

**Comment by edbird** [comment]
Ah, right, it all makes a lot more sense now. Do you know off hand what Debian 10 uses? Is it just called `dhcpcd`? (Without the `5`?)

**Comment by dschaper** [comment]
Debian or Raspbian?

**Comment by edbird** [comment]
Debian, from your previous comment I gather that PiHole, on Raspbian, uses `dhcpcd5` ?

**Comment by edbird** [comment]
Looks like `Buster` uses `dhcpcd5`?

https://packages.debian.org/stable/net/

This is weird - it doesn't explain why the network static ip syntax is different... Unless I'm confused and it never worked on my Debian 10 system either?

**Comment by dschaper** [comment]
Raspbian uses dhcpcd, Debian 10 has a few options for networking https://wiki.debian.org/NetworkConfiguration.

**Comment by edbird** [comment]
That's what I thought, but the packages listing suggests `dhcpdc5` is shipped with it?

Regardless, this is somewhat off topic and it doesn't matter that much - issue is resolved so feel free to close - thanks for all the help

**Comment by dschaper** [comment]
Raspbian is very different in how it does networking. So anything that is RasPi will be very specific to `dhcpcd`. The package is available on other distributions but not installed by default. Pi-hole does use it on non-Raspbian installations for now but that will change in the next major version.
