### ISSUE TITLE
lighthttp - Error during fresh Install - Raspberry Pi

### ISSUE THREAD

**Issue by silentwolf15** [pi-hole/pi-hole#308]
```
:::    Checking for lighttpd... Not found! Installing.../E: Sub-process /usr/bin/dpkg returned an error code (1)                                                                                     done!
```

**Comment by jacobsalmela** [comment]
Sometimes the download/installation of a package fails.  I have seen this happen occasionally.  Try removing it and then installing again.
```
sudo apt-get remove --purge lighttpd
```

**Comment by silentwolf15** [comment]
I did a manual install of it and things are working fine.
sudo apt-get install lighttpd

**Comment by jacobsalmela** [comment]
Excellent!  Glad it is working.  Sometimes the packages just don't install correctly the first time around.
