### ISSUE TITLE
cannot load external resources at landing page

### ISSUE THREAD

**Issue by ggmanugg** [pi-hole/pi-hole#3081]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`the landing page of pi hole`

**Actual behaviour:**

`not all resources can be loaded (just if i don't access the site from my internal lan). the /admin site is working properly`
![image](https://user-images.githubusercontent.com/37898579/72335124-c4b36a00-36be-11ea-9023-d2addb40ad57.png)

**Steps to reproduce:**

`install the latest updates from pi hole and make it accessible from the internet`
![image](https://user-images.githubusercontent.com/37898579/72333655-6be2d200-36bc-11ea-912f-f0c96361b63c.png)

![image](https://user-images.githubusercontent.com/37898579/72333695-7ef5a200-36bc-11ea-9069-567756fccc50.png)

![image](https://user-images.githubusercontent.com/37898579/72333734-96cd2600-36bc-11ea-9270-1c0988b63a0d.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`gl4qmxgkje`

**Troubleshooting undertaken, and/or other relevant information:**

`different browsers, incognito mode, reboot, updates`

**Comment by dschaper** [comment]
This is the intended behavior.

**Comment by PromoFaux** [comment]
In a standard install, if you browse to either:

`http://pi.hole`
`http://[IP address of Pi-hole]`

You will be redirected to `/admin`, as there are traps that do this based on the address used to access the top level page.

In order to reproduce this behaviour when using a custom domain name to access the page, you will need to modify the landing page in the web root.

**Comment by ggmanugg** [comment]
Ah thank you for the information.
I made some changes in the file /var/www/html/pihole/index.php. I replaced all entries from pi.hole to my domain name and now it works as requested.
