### ISSUE TITLE
PiHole won't connect as DNS server, but resolver and general communication works

### ISSUE THREAD

**Issue by Zubkover** [pi-hole/pi-hole#3085]
**Expected behaviour:**

PiHole starts to serve as a DNS server

**Actual behaviour:**

I can ping, traceroute, access admin panel through IP and SSH into the machine, but no machine in the network would use it as a DNS server. BUT when inputing direct queries into SSH for DNS resolver I get instant responses and the machine is able to download its updates, and resolves queries made by itself.

**Steps to reproduce:**

Connect the Rasp with clean Rasbian Buster Lite, install PiHole, restart it even for good measure after install process and set it's IP as a DNS server by either router or computer directly.

`{Steps of what you have done to fix this}`

Restarted the machine, restarted resolver, reinstalled pihole 3 times, tried switching on/off wonky router settings (like security settings or DNS Overrride/Relay), setting Rasp as a DNS in either router settings or in PC network adapter settings, somewhat tested also setting raspberry as a DHCP also, but for some reason the adresses didn't change.
FYI cmd commands or settings/whole pc restart on Win10 machine also doesn't make a difference and nslookup just finishes in timeout or unknown.
Modem/Router is an Arris TG2492S

**Comment by technicalpyro** [comment]
restarting the pi-hole instance will not immediately cause your devices to pick up the pi-hole as their new DNS

your DHCP leases on your devices (assuming you have the DHCP set to serve onlyPi-hole as the DNS server) need to be renewed so they know to use the pi-hole as the DNS server.  

To test this modify your DNS settings under the network settings on your windows box modify the IPv4 properties to use the static IP of a DNS server and set that to you pi-holes IP if the queries operate as expected this is a network  issue and not one with the pi-hole or its code

**Comment by Zubkover** [comment]
ipconfig does return pihole's adress as a DNS after a while though... and that's when DNS PROBE FAILED and DNS BAD CONFIG is being seen on chrome...
Also strange thing is when I turn on DNS relay in router it switches DNS from any DNS provided in the table into some random public server

**Comment by technicalpyro** [comment]
when you see these errors do you see a corresponding response in the pi-hole query log?
also run `pihole -d` for a debug token

**Comment by Zubkover** [comment]
For some reason I get error while trying to upload the log, so i'll just put this chunk here:
*** [ DIAGNOSING ]: Networking
[✗] No IPv4 address(es) found on the wlan0 interface.

[✗] No IPv6 address(es) found on the wlan0 interface.

[i] Default IPv4 gateway: 192.168.0.1
   * Pinging 192.168.0.1...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)

Debugger seem to give info as though there would be no connection to gateway... but it's impossible since I can both download Rasbian and PiHole updates without issue, and can ping both devices. Also PiHole both resolves DNSs and pinging website servers work so it has to be connected to the internet o.o

The only other fail in the log is:
[✗] Failed to resolve e.ad.xiaomi.com via Pi-hole (192.168.0.15)

Also FTL log is full of:  [2020-01-17 01:00:00.615 615] WARN: getOverTimeID(1579223100): 444 is too large: *something*

**Comment by Zubkover** [comment]
Also manually pinging gateway from raspberry is working

**Comment by dschaper** [comment]
Which interface should Pi-hole be using?

**Comment by Zubkover** [comment]
eth0, since it's connected by LAN RJ45, it's 3B+ i believe.

**Comment by dschaper** [comment]
Check `/etc/pihole/setupVars.conf` and make sure the interface is correct. Also check `/etc/dhcpcd.conf` to make sure that is all accurate with the static IP addressing at the bottom.

**Comment by Zubkover** [comment]
Nothing out of order on the first look, though in setupVars there is no mention of gateway.

dhcpcd checks out with
interface wlan0
        static ip_address=192.168.0.15/24
        static routers=192.168.0.1
        static domain_name_servers=127.0.0.1

unless I'm not seeing something?

**Comment by dschaper** [comment]
That says the interface is `wlan0` but you want `eth0` if it's with a cable.

**Comment by Zubkover** [comment]
Ops, wrong section.
eth0 seems to be commented out with # then o.o

**Comment by dschaper** [comment]
Okay, does the command `ip -4 address show` at the Pi-hole device command line show that the networking is set up as you would like it?

**Comment by Zubkover** [comment]
I'm a little noob on Linux side of things so I'm... uncertain?
I've renamed an interface in conf file and it did nothing, ALTHOUGH that got me thinking - now I got to the point where I get the gist of the problem - I can ping raspberry from anywhere, but raspberry can't ping anything on the network beside gateway and sees only devices for a split second and registers their ip and then they come offline and never came online in Network tab in online admin page. What's funny is that even though config had wlan0 as interface admin page still shows eth0 as used interface.

from ip -4:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group defaul                                         t qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP gr                                         oup default qlen 1000
    inet 192.168.0.15/24 brd 192.168.0.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever

For network adresses it is:
Gateway:192.168.0.1
Raspberry: 192.168.0.15
Devices: 192.168.0.(2/3/4/16)

**Comment by dschaper** [comment]
Okay, you can edit `/etc/dhcpcd.conf` to change that `wlan0` to `eth0`. `sudo nano /etc/dhcpcd.conf` should let you do that. Reboot after and do a new debug token.

**Comment by Zubkover** [comment]
Already done so, nothing has changed :C

**Comment by dschaper** [comment]
Try editing `/etc/resolv.conf` to change 127.0.0.1 to a public DNS like 8.8.8.8 and then try the debug again?

**Comment by Zubkover** [comment]
Nope, doesn't work

**Comment by dschaper** [comment]
Can you `ping tricorder.pi-hole.net`?

**Comment by Zubkover** [comment]
No

**Comment by nicemachines** [comment]
That doesn't make any sense.  You can ping everywhere but there.  Seems to me there is something in the PiHole software that isn't set up right as though it is BLACK LISTED what your trying to ping!  I am new also, hope you figure it out!  I'll keep watch on replies here!  Only reason I am responding is to let you know I will attempt to set up PiHole tomorrow.  Good Luck Guys!

**Comment by Zubkover** [comment]
Yup, doesn't make any sense to me either, especially that it's the third install I did and no matter whether I left it as is or configured it some it always gives me the same problem. Also blacklist is set as suggested by installer, I only tried adding on stuff like server.cpmstar.com, sooooo yeeeeeee

**Comment by dschaper** [comment]
What does `dig tricorder.pi-hole.net @127.0.0.1` and `dig tricorder.pi-hole.net @8.8.8.8` show for results?

**Comment by Zubkover** [comment]
; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> tricorder.pi-hole.net @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26658
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tricorder.pi-hole.net.         IN      A

;; ANSWER SECTION:
tricorder.pi-hole.net.  1839    IN      A       107.170.224.181

;; Query time: 32 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jan 19 00:24:13 GMT 2020
;; MSG SIZE  rcvd: 66


and

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> tricorder.pi-hole.net @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43755
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tricorder.pi-hole.net.         IN      A

;; ANSWER SECTION:
tricorder.pi-hole.net.  2510    IN      A       107.170.224.181

;; Query time: 30 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Jan 19 00:24:35 GMT 2020
;; MSG SIZE  rcvd: 66

**Comment by dschaper** [comment]
Those are both the right IP addresses, not sure why you can't ping them. Does a traceroute show any hops outside of your network?

**Comment by Zubkover** [comment]
I might have a clue... In a spree of delsional demotivation I disabled Windows firewall and I can ping disabled PC with Pi. Doesn't really fix the issue of not working though. :c

**Comment by dschaper** [comment]
The Pi-hole seems to be responding to DNS queries since you got a response from `@127.0.0.1`. Concerned about not reaching tricorder, that looks like a network configuration issue.

**Comment by Zubkover** [comment]
Is there any word on any issues with Arris gateways or can I overcome it with a router and bridging Arris?

**Comment by dschaper** [comment]
Shouldn't need to. What does the traceroute show?

**Comment by Zubkover** [comment]
Hm, funfact: calling nslookup on Windows machine causes "DNS request timeout, default server unknown"
Also, fact-checked firewall shenanigans with two IT guys and both said that ICMP are blocked now by default, unless you have firewall exception set for Sharing Printers and Devices or Remote Virtual Machine.

traceroute shows:
traceroute to tricorder.pi-hole.net (107.170.224.181), 30 hops max, 60 byte pack                                       ets
 1  192.168.0.1 (192.168.0.1)  2.789 ms  3.439 ms  4.085 ms
 2  10.20.0.1 (10.20.0.1)  23.314 ms  23.634 ms  24.477 ms
 3  slash30-conn21-213.eaw.com.pl (78.152.21.213)  25.316 ms  24.891 ms  25.484                                        ms
 4  slash30-conn21-35.eaw.com.pl (78.152.21.35)  26.657 ms  25.779 ms jay1.eaw.c                                       om.pl (78.152.21.2)  26.176 ms
 5  pzn-b1-link.telia.net (62.115.54.232)  28.671 ms  28.953 ms  26.945 ms
 6  hbg-bb4-link.telia.net (62.115.120.64)  189.937 ms  183.545 ms  183.559 ms
 7  ldn-bb4-link.telia.net (62.115.122.161)  185.061 ms  172.254 ms  172.816 ms
 8  * * *
 9  palo-b22-link.telia.net (62.115.114.5)  176.670 ms  180.426 ms  183.793 ms
10  digitalocean-ic-336107-palo-b22.c.telia.net (213.248.99.163)  184.219 ms  18                                       4.450 ms  184.886 ms
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by hiyan** [comment]
traceroute has a TTL (hops) of 30 as default. You'll need to increase that.

**Comment by Zubkover** [comment]
Once again with help from IT peps I know I got to the bottom of why PiHole won't detect some servers through traceroute - it's because it uses UDP instead of ICMP.

But still - no matter if UDP or ICMP tricoder traceroute spits out only '***' after 10th hop as below, with 60 hops being the limit.

**Comment by dschaper** [comment]
Sorry, just seeing this. Tricorder will not respond to pings.

**Comment by Zubkover** [comment]
I'm in the process of yet again fully reinstalling OS as a whole, any pointers on what can I be doing wrong?

**Comment by dschaper** [comment]
I really don't know. Just make sure that `/etc/dhcpcd.conf` is correct with regards to the interface?

**Comment by Zubkover** [comment]
Just checked it a minute before reinstallation, and it was okey, but worrying thing was that after ip show adrr there was no lines shown other than self ip, no gateway nor dns

**Comment by Zubkover** [comment]
FOR FUCKS SAKE, WHY DOES IT WORK THAT WAY.

So apparently after 3 Rasbian reinstalls and at 3rd reinstall consisting of installing PiHole but installer finish wouldn't pop up and DNS would go missing so 2 times exacly the same copy-paste command later... it works. >.>

ffs. why doing same command of "curl -sSL https://install.pi-hole.net | bash" always yields different results?
First time I let it go it would just hang on the logo,  then it hanged even before gui installer, then again after 1st GUI part and then two times after finishing an install but had problems with FTL and cloning all repositories. WHY.
