### ISSUE TITLE
Why is regex on blacklists not supported?

### ISSUE THREAD

**Issue by cottton** [pi-hole/pi-hole#3088]
Just this question.
Is there a reason?

I always though pihole works like "domain.com" blocks this domain and all its subdomains.

Seems not the case and regext dont work in blacklists.

So - why?

**Comment by PromoFaux** [comment]
Are you talking about adding a pre-compiled list from an external source? In which case, all domains contained within are treated as exact blocks. Reading them as anything else would cause havoc and a lot of false positives.

You can add individual regex/wildcard blacklist entries from the web UI, however...

**Comment by PromoFaux** [comment]
Please open this as a feature request on our discourse forum so that it is trackable and can be voted on by the community at large.

Thanks!

https://discourse.pi-hole.net/c/feature-requests

**Comment by cottton** [comment]
> Please open this as a feature request on our discourse forum so that it is trackable and can be voted on by the community at large.
> 
> Thanks!
> 
> https://discourse.pi-hole.net/c/feature-requests

Can you change this pls?
I mean can you take feature requests here on git?
Posting there seems waste of time and is kind of exhausting.

**Comment by dschaper** [comment]
No, we don't have the resources to track multiple locations for feature requests.
