### ISSUE TITLE
api "no password set"

### ISSUE THREAD

**Issue by gitcloneguy** [pi-hole/pi-hole#3091]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

API qr code starts to generate and then displays

**Actual behaviour:**

blank page saying "no password set"

**Steps to reproduce:**

go to admin dashboard
click settings
click api/web interface
click show api token
click "yes show api token"

Debug token : cm8k97i53l

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

cannot seem to find any fix

> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Do you have a password set?

**Comment by gitcloneguy** [comment]
How am i supposed to do that?

**Comment by gitcloneguy** [comment]
as in web gui? yes

**Comment by dschaper** [comment]
Is there an API key with a value in `/etc/pihole/setupVars.conf`?

**Comment by gitcloneguy** [comment]
just set that rn

**Comment by gitcloneguy** [comment]
works! thanks so much!
