### ISSUE TITLE
Change top left Pi-hole link to Dashboard

### ISSUE THREAD

**Issue by sfkpmr** [pi-hole/pi-hole#3096]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

This is a duplicate of https://github.com/pi-hole/pi-hole/issues/1153, but it was closed due to not following the template.

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

As the mostly standard behaviour on websites and web UI:s, I expect clicking on Pi-hole in the top left to take me to the Dashboard.

**Actual behaviour:**

Instead of taking me to the Dashboard, I'm taken to pi-hole.net.

**Steps to reproduce:**

Click "Pi-hole" in the top left of the web UI.

**Comment by dschaper** [comment]
See https://github.com/pi-hole/AdminLTE/pull/1128
