### ISSUE TITLE
Current Build is missing all 8 DNS options

### ISSUE THREAD

**Issue by iaintshootinmis** [pi-hole/pi-hole#3099]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

Expect to see a list of 8 dns upstream providers including FamilyShield per commit # 2037 and per the [documentation](https://docs.pi-hole.net/guides/upstream-dns-providers/#opendns-home-owned-by-cisco)

**Actual behaviour:**

Less than 8 dns upstream providers are available. 

**Steps to reproduce:**

Install pihole, at the installation step for selecting an upstream provider, notice that there are not 8.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

k9frhvl6fy

**Troubleshooting undertaken, and/or other relevant information:**

Reviewed the script, reviewed previous commits, unable to find notation, conversations or intentional removal of additional dns upstream providers.

**Comment by dschaper** [comment]
There are 8 options. https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L32

**Comment by dschaper** [comment]
The PR that last touched that section is https://github.com/pi-hole/pi-hole/pull/2593
