### ISSUE TITLE
Moved WebInterface, can't change settings to reflect new location

### ISSUE THREAD

**Issue by FalcoGer** [pi-hole/pi-hole#3101]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**
I can change the folder in which the webinterface files are located, for example in some configuration file. When this is done, updates and other things that are done to the webinterface of pihole are applied to the correct location.

**Actual behaviour:**
I can't find any reference to `/var/www/html/` in any of the files in `/etc/pihole/`
pihole updatePihole fails with
```
> sudo pihole updatePihole 
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date

  Error: Web Admin repo is missing from system!
  Please re-run install script from https://pi-hole.net
```

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
1. Install Pi-Hole, including WebInterface and without lighthttpd (I use apache2)
2. Move `pihole/` and `admin/` from `/var/www/html/` to `/var/www/pihole/` (The webinterface works with the correct settings in apache2)
3. Try and update the web interface via the pihole command.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/3c2g5skqx3

**Troubleshooting undertaken, and/or other relevant information:**

Attempted to locate any reference to `/var/www/` in configuration files in `/etc/pihole/`.
```
/etc/pihole> grep --recursive "var/www"
# Empty Return

# listing of my /etc/pihole
-rw-r--r--   1 root   root       20 Jan 24 18:54 GitHubVersions
-rw-r--r--   1 root   root      313 Jan 19 17:56 adlists.list
-rw-r--r--   1 root   root       28 Jan 19 18:59 auditlog.list
-rw-r--r--   1 root   root       27 Jan 24 18:44 black.list
-rw-r--r--   1 root   root       27 Jan 20 17:22 blacklist.txt
-rw-r--r--   1 pihole pihole    131 Jan 24 18:57 dhcp.leases
-rw-r--r--   1 root   root      596 Jan 19 18:02 dns-servers.conf
-rw-r--r--   1 root   root     2.8M Jan 24 18:44 gravity.list
-rw-r--r--   1 root   root      12K Jan 19 18:02 install.log
-rw-------   1 root   root     1.6M Jan 24 18:44 list.0.raw.githubusercontent.com.domains
-rw-------   1 root   root     581K Jan 19 18:02 list.1.mirror1.malwaredomains.com.domains
-rw-------   1 root   root     624K Jan 19 18:02 list.2.sysctl.org.domains
-rw-------   1 root   root      613 Jan 19 18:02 list.3.s3.amazonaws.com.domains
-rw-------   1 root   root      43K Jan 19 18:02 list.4.s3.amazonaws.com.domains
-rw-------   1 root   root     1.7M Jan 19 18:02 list.5.hosts-file.net.domains
-rw-r--r--   1 root   root     2.8M Jan 24 18:44 list.preEventHorizon
-rw-r--r--   1 root   root      122 Jan 24 18:44 local.list
-rw-r--r--   1 root   root       14 Jan 24 19:10 localbranches
-rw-r--r--   1 root   root       25 Jan 24 19:10 localversions
-rw-r--r--   1 root   root      238 Jan 19 18:02 logrotate
-rw-r--r--   1 root   root     2.3M Jan 19 18:02 macvendor.db
-rw-rw-r--   1 pihole root       15 Jan 19 18:02 pihole-FTL.conf
-rw-r--r--   1 pihole pihole   2.7M Jan 24 19:10 pihole-FTL.db
-rw-rw-r--   1 pihole www-data    0 Jan 19 18:02 regex.list
-rw-r--r--   1 root   root      771 Jan 24 18:40 setupVars.conf
-rw-r--r--   1 root   root        0 Jan 20 17:22 whitelist.txt
```

Notes:
- Pihole was installed through the `basic-install.sh` script from git, commit `e41c4b5bb691cea1f5b950d39518d8c404b5846e` (tagged v4.3.2)
- Pihole folders were moved from /var/www/html so they would not be accessible from outside. a new virtual host was provided for pihole through apache2's configuration. This was done after the installation.
- the web interface seems to work, even after having been moved, just pihole itself doesn't seem to know about it anymore.
- Another webserver is running on /var/www/html that is publicaly accessible

**Comment by dschaper** [comment]
This isn't currently supported. There are some community discussions on using other web servers and other root locations at https://discourse.pi-hole.net and that is the best place to get help.

**Comment by mwoolweaver** [comment]
would it be possible to update the git repositories via `git pull` and get updates that way?

**Comment by PromoFaux** [comment]
That is exactly what the update script does, so yeah I don't see why you can't go into the directory (in the new location) and run a `git pull`

Try it and see!

**Comment by naxels** [comment]
I have this exact issue, as a temporary workaround:

Before each update, do a grep on '/var/www/html' in /opt/pihole and /etc/.pihole folders and replace those with the new web folder you want.

Then after the update, make sure to update the lighttpd config again to point to the new web folder (and port if you changed it), since pihole resets that config as well.
