### ISSUE TITLE
Question: privacy on all and logging off

### ISSUE THREAD

**Issue by gitcloneguy** [pi-hole/pi-hole#3102]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

not sure

**Actual behaviour:**

not sure
**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

its a question

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

so, im wondering if having the privacy on the admin dashboard to all, does it write/read anything on my sd card(using rpi) i ran sudo pihole logging off after putting privacy to all

**Comment by dschaper** [comment]
This is better addressed as a question post at https://discourse.pi-hole.net. We keep GitHub for bug reports and code tracking.

**Comment by gitcloneguy** [comment]
sorry
