### ISSUE TITLE
Period allowed in hostnames.

### ISSUE THREAD

**Issue by Spartelfant** [pi-hole/pi-hole#3103]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1` (not familiar)

---
**Expected behaviour:**

In the Pi-hole's web interface, in Settings -> DHCP, when setting a static lease, valid characters for the Hostname should - to the best of my knowledge - not include the period (`.`) character.

**Actual behaviour:**

The web interface accepts hostnames such as `host.name`.

**Steps to reproduce:**

Input a hostname for a static lease containing periods, add it to the list of static leases and hit the Save button. The hostname with a period shows up verbatim in `/etc/dnsmasq.d/04-pihole-static-dhcp.conf`.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`i8bgp2dtbo`

**Troubleshooting undertaken, and/or other relevant information:**

I've tried figuring out if a period (`.`) in a hostname should be allowed or not, in other words if it can serve a legitimate purpose. I was unable to come to a conclusion. Perhaps it could be useful when subdividing a network, for example `host.department1.example.com`, `host.department2.example.com` where `example.com` is the Pi-hole domain name. But I would expect such a subdivision to be made at a higher level, not at hostname level. Also I couldn't find any example of this sort of application, virtually every page I could find on the subject said not to use a period (`.`) in hostnames. Several sources also indicated that a dot in a hostname could lead to unpredictable behaviour between different devices, operating systems and other software.
If there is a legitimate use case for allowing a period in hostnames, then perhaps their use should come with a notification aimed at users such as myself (with only modest networking knowledge) that they shouldn't be used willy-nilly. For example I thought it would be a good idea to give my laptop's wired and wireless connection names such as `laptop.wired` and `laptop.wireless` and since the Pi-hole's interface accepted these names I did not see any harm in it at first.

**Comment by dschaper** [comment]
Periods are delimiters between domain levels. You can't use it as in a host name.

**Comment by Spartelfant** [comment]
> Periods are delimiters between domain levels. You can't use it as in a host name.

Please correct me if I misunderstand, but then shouldn't the input field in the Pi-hole's DHCP settings reject periods in hostnames when setting static leases?

**Comment by dschaper** [comment]
Not really, it's valid. It just creates a host record on a subdomain.

**Comment by dschaper** [comment]
`host.subdomain.my.local` is completely valid if you enter `host.subdomain`. The confusion is that `host.host2` is different than `host.subdomain`.

**Comment by Spartelfant** [comment]
Ah ok! Many thanks for clarifying!
