### ISSUE TITLE
Pihole Admin Interface not working on Pi with Octoprint

### ISSUE THREAD

**Issue by sinicolau6** [pi-hole/pi-hole#3104]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

`When attempting to enter the Admin page via the IP_address/admin or pi.hole/admin, the web interface is accesible`

**Actual behaviour:**

`When attempting to enter the Admin page via the IP_address/admin or pi.hole/admin, the web interface isnt to be found

I tried everything that could be found on the internet. At first, the lighttp service couldnt start, so i somehow forced it to start, it stayed like that, but the web interface was still not accesible. The PI is blocking ads, but i want to access it and add more blocklists and Regex entries. After stressing over it again and again, i uninstalled it from the RasPI and now i wanted to give it another try, with your help, with a fresh install. The Lighttp server is NOT running and i cannot get it to start, like i did previously.

It seems that if i change the lighttp server from 80 to 8888 for example, the lighttp service will work, but the admin webpage STILL doesnt show up. i am at a loss completely.

i tried running pihole -d, and even that showed that the Web Interface is not accesbile.`

**Steps to reproduce:**

`Intall Pihole on a Raspberry pi 4B with Octoprint as the main distro, install pihole, see that you cannot access the interface`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`49p5opd1jo`

**Troubleshooting undertaken, and/or other relevant information:**

`everything that i could find on the internet, having made posts on discourse and reddit with seemingly no help.`

**Comment by dschaper** [comment]
That OS/distribution is not supported. I'll include the debug log output, you'll have to ask the OS creators how to resolve.

```plain
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Content-Length: 2788
X-Robots-Tag: noindex, nofollow, noimageindex
Set-Cookie: session_P80=eyJfaWQiOnsiIGIiOiJNbUptTm1FMU5qVmxOekE0Tm1RNU5HVXpNalJsTlRsbU5qSTRNekEyTkRBPSJ9fQ.XizqpQ.dwUuP9epqXZ0KjBzpR5z-P1fhCg; HttpOnly; Path=/
Last-Modified: Tue, 29 Oct 2019 14:49:55 GMT
Etag: "2b23d70a5ee9bda3564c6ca2d725eb882e09eed1"
X-From-Cache: true
Cache-Control: no-cache, must-revalidate
X-Clacks-Overhead: GNU Terry Pratchett
Content-Type: text/html; charset=utf-8


[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 404 NOT FOUND
Content-Length: 232
Content-Type: text/html
X-Clacks-Overhead: GNU Terry Pratchett
X-Robots-Tag: noindex, nofollow, noimageindex
```

**Comment by dschaper** [comment]
Discourse is the best place for this question and discussion. I'll close this out, please follow up there.
