### ISSUE TITLE
pihole randomly going off

### ISSUE THREAD

**Issue by thegamerx1** [pi-hole/pi-hole#3109]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

not go off

**Actual behaviour:**
pihole randomly goes off

**Steps to reproduce:**

idk

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

 https://tricorder.pi-hole.net/crp3su0wrg

**Troubleshooting undertaken, and/or other relevant information:**
```
pi@NDR-PiServer:~ $ pihole -up
  [i] Checking for updates...
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com
  [i] Pi-hole Core:     up to date
fatal: unable to access 'https://github.com/pi-hole/AdminLTE.git/': Could not resolve host: github.com
  [i] Web Interface:    up to date
  [i] FTL:              Something has gone wrong, contact support

  [✓] Everything is up to date!
```

After sometime of that any website woulnt load so i sshed to the pi and `ping google.com` returned system error rebotting doesnt fix it

**Comment by dschaper** [comment]
The debug log looks okay. Was everything working when you uploaded the log or were things not working?

**Comment by thegamerx1** [comment]
after some time looks like its working again, every single of my devices coulnt resolve any website even the laptop that i didnt assign the pihole dns but they all could enter ip addresses like `1.1.1.1` very weird everything
