### ISSUE TITLE
Slow long term queries >> adding index improves speed several orders

### ISSUE THREAD

**Issue by jb137** [pi-hole/pi-hole#3110]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1, first time look at code.

---
**Expected behaviour:**

I would expect the long term data query for a single day on decent amd64 hardware to be returned within seconds (13k records). Just like the long term graphics does.

**Actual behaviour:**

Select a single day would take up to a minute to be returned. With no CPU core on the host being exhausted.

**Steps to reproduce:**
Precondition: have pi-hole operate for a full day on a small network (10k+ records). 
Environment: docker container running on 2.66GHz Core i5. Mount the /etc/pihole directory to the host file system (not the best option for performance)

1. Enter long term data
1. Select Query
1. Select Select yesterday in date and time range
1. Wait...

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

No.

**Troubleshooting undertaken, and/or other relevant information:**

Since the graphics pages showed the results for a full day almost instantly I suspected something could be wrong with the database indexes. After downloading the sqlite database (default /etc/pihole/pihole-FTL.db I noticed it contains only a single index on timestamp (as confirmed by the source code). The queries in api_db.php for the query page however use several fields to filter on.

Next I added 4 indexes using the following create queries:
`CREATE INDEX idx_queries_domain ON queries (domain);`
`CREATE INDEX idx_queries_type ON queries (type);`
`CREATE INDEX idx_queries_client ON queries (client);`
`CREATE INDEX idx_queries_status ON queries (status);`

After putting the original database with the new indexes back in places the long term data queries where several orders quicker returning results in seconds.

This might not be the best solution for all platforms. I have not checked the long term effects of these extra indexes nor the impact on memory usages on resource constraint hardware. I have not studied the queries used in api_db.php in depth and I may have added a useless index.

**Comment by DL6ER** [comment]
Have you followed how much time the index generation needed? I can see the need in (blocking!) processing time as being more severe than the extra space needed for the index tables.

**Comment by jb137** [comment]
I added the indexes on a much faster desktop machine. It took seconds at most.

**Comment by DL6ER** [comment]
Okay, thanks. I will do some tests on my PRi 3B+ (I have no ready installed slower device at hand) soon and report back here. We can discuss he impact based on this.

**Comment by DL6ER** [comment]
Okay, first results from a Raspberry Pi 3B+: The index generation tool about one minute and (approximately) doubled the database size.

Note that my database may not be really representative here, as I do not use this flat all that much, I'm (at lost) 1/3 of the time here and use only one device.

Hence, the impact on more realistic databases may be substantially more severe.

```plain
root@munichpi:~# ls -lh pihole-FTL.db
-rw-r--r-- 1 root root 152M Feb 12 17:43 pihole-FTL.db
root@munichpi:~# time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_domain ON queries (domain);"

real    0m19,350s
user    0m10,426s
sys     0m0,791s
root@munichpi:~# ls -lh pihole-FTL.db 
-rw-r--r-- 1 root root 190M Feb 12 17:44 pihole-FTL.db
root@munichpi:~# time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_type ON queries (type);"

real    0m9,038s
user    0m6,540s
sys     0m0,499s
root@munichpi:~# ls -lh pihole-FTL.db 
-rw-r--r-- 1 root root 209M Feb 12 18:58 pihole-FTL.db
root@munichpi:~# time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_client ON queries (client);"

real    0m13,210s
user    0m9,092s
sys     0m0,750s
root@munichpi:~# ls -lh pihole-FTL.db 
-rw-r--r-- 1 root root 253M Feb 12 18:58 pihole-FTL.db
root@munichpi:~# time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_status ON queries (status);"

real    0m12,135s
user    0m7,342s
sys     0m0,411s
root@munichpi:~# ls -lh pihole-FTL.db 
-rw-r--r-- 1 root root 273M Feb 12 18:58 pihole-FTL.db
```

**Comment by dxcSithLord** [comment]
I can help with some data from: Raspberry pi 4B 4GB RAM (128GB SD card), with ICE-Tower cooling.  Pihole was installed on ubuntu 18.04.4 for pi and started 48 hours ago. reporting 42 clients, 29151 queries on main dashboard.
PiHole version 4.4, web interface 4.3.3, FTL version 4.3.1.
I ran the same commands as above, with the following results (sorry didn't get a couple of the db size increases):
`ls -lh pihole-FTL.*`
`-rw-rw-r-- 1 pihole root     15 Feb 26 22:26 pihole-FTL.conf`
`-rw-r--r-- 1 pihole pihole 6.6M Feb 28 23:12 pihole-FTL.db`

`sudo time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_domain ON queries (domain);"`
`0.12user 0.05system 0:00.26elapsed 67%CPU (0avgtext+0avgdata 7112maxresident)k`
`0inputs+9584outputs (0major+1232minor)pagefaults 0swaps`

`ls -lh pihole-FTL.*`
`-rw-rw-r-- 1 pihole root     15 Feb 26 22:26 pihole-FTL.conf`
`-rw-r--r-- 1 pihole pihole 9.0M Feb 28 23:13 pihole-FTL.db`

`sudo time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_type ON queries (type);"`
`0.05user 0.02system 0:00.11elapsed 71%CPU (0avgtext+0avgdata 6936maxresident)k`
`0inputs+1408outputs (0major+1147minor)pagefaults 0swaps`

`sudo time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_client ON queries (client);"`
`0.09user 0.06system 0:00.24elapsed 64%CPU (0avgtext+0avgdata 7104maxresident)k`
`0inputs+9400outputs (0major+1232minor)pagefaults 0swaps`

`sudo time sqlite3 pihole-FTL.db "CREATE INDEX idx_queries_status ON queries (status);"`
`0.06user 0.02system 0:00.11elapsed 72%CPU (0avgtext+0avgdata 6836maxresident)k`
`0inputs+1456outputs (0major+1148minor)pagefaults 0swaps`

`ls -lh pihole-FTL.*`
`-rw-rw-r-- 1 pihole root    15 Feb 26 22:26 pihole-FTL.conf`
`-rw-r--r-- 1 pihole pihole 13M Feb 28 23:14 pihole-FTL.db`

Time to query 77467 records approx 7 to 9 seconds (last 7 days) - note don't have 7 days worth of records.

Hope this helps.  I was thinking about setting up another for family on a pi zero, would you like any date from that?

**Comment by dxcSithLord** [comment]
Follow up from previous post - additional diagnostics.
Request for last 7 days :
After an additional two weeks (16 days) of usage, I was getting an error and no results.  I checked the logs, and found the following in /var/log/lighttpd/error.log:
`FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /var/www/html/admin/api_db.php on line 172`

Database size currently:

ls -lh /etc/pihole/pihole-FTL.db 
-rw-r--r-- 1 pihole pihole 159M Mar 15 12:21 /etc/pihole/pihole-FTL.db

I increased the memory for PHP (ref https://www.airpair.com/php/fatal-error-allowed-memory-size)
Inserted into /var/www/html/admin/api_db.php at top of the file (after initial comment):

`ini_set('memory_limit', '256M');`

The queries complete in 110 seconds for 348,725 queries, 76,923 blocked.

Error repeats for last 30 days, but this time:
`FastCGI-stderr: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 33554440 bytes) in /var/www/html/admin/api_db.php on line 172`

Increased memory to 512M:
`ini_set('memory_limit', '512M');`
Restarted and repeated query for last 30 days
Error repeated, but different error line:
FastCGI-stderr: PHP Fatal error:  Allowed memory size of 536870912 bytes exhaushttp://192.168.0.121/admin/list.php?l=whiteted (tried to allocate 68386816 bytes) in /var/www/html/admin/api_db.php on line 438

Increased memory to 640M:
`ini_set('memory_limit', '640M');`

The query for 30 days of results (my database currently holds date from 26th Feb to 15th March)
returns 886552 records, time to return web page is around 15 minutes.

I have dropped the additional indexes and 

This is on a Pi 4B 4GB RAM, Ubuntu 18.04 (not raspbian).

**Comment by DL6ER** [comment]
> I have dropped the additional indexes

So were your timings with or without the indices? If without, why did you drop them? If with, how did that affect performance of the lookups?

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-more-statistics-on-per-client-basis/27640/7

**Comment by dxcSithLord** [comment]
> > I have dropped the additional indexes
> 
> So were your timings with or without the indices? If without, why did you drop them? If with, how did that affect performance of the lookups?

The information was prior to dropping the indexes.  I dropped them because they would have had an impact on memory usage and the choice of slow or breaking the app, I choose slow.  I didn't see any better results, but I posted before I had rebooted/restarted, as I thought that the database may need re-starting.  
I have just looked and I don't have any more historic data (pihole still working).  Need to investigate further - may have broken database! :-(

**Comment by DL6ER** [comment]
@dxcSithLord There should be information in `/var/log/pihole-FTL.log` in case there are any issues with the database. First, ensure that the permissions are correct. Both the directory `/etc/pihole` and the contained database file `pihole-FTL.db` need to be owned by `pihole:pihole` and writable to the user.
