### ISSUE TITLE
Pi-hole admin interface "An unknown error occurred" when loading unprintable domains

### ISSUE THREAD

**Issue by flyingstar16** [pi-hole/pi-hole#3111]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

Loading "all" queries, or specific dates/times, returns the requested data

**Actual behaviour:**

Data is not returned; I get an alert because "An unknown error occurred when loading the data"; the AJAX response is empty (despite it being a 200 OK)

![ajax_error_pihole](https://user-images.githubusercontent.com/582280/73743257-6b36dc00-474e-11ea-98b8-cb5c922a2aa7.png)

**Steps to reproduce:**

Try loading a date/time range where a query with "name unprintable" from dnsmasq has been added to the FTL DB
e.g.
`Jan 31 18:10:17 dnsmasq[907]: query[A] <name unprintable> from 127.0.0.1`

I have been able to trigger this by loading specific timestamps that I know contain bad data via `/admin/api_db.php?getAllQueries`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`37yu6ic79e`

**Troubleshooting undertaken, and/or other relevant information:**

1. In the web UI, drilled down on one of the timestamps that was not returning data, to get the closest 15 min. interval
1. Checked in pihole-FTL.db what queries were recorded during that interval
1. Discovered this unprintable query saved there, at the exact (and only) timestamps that were making the Web UI fail to load (and then checked how many times it appeared)
![sqlite_pihole_unprintable](https://user-images.githubusercontent.com/582280/73743270-712cbd00-474e-11ea-8fdc-0ce00f7d3f57.png)
1. Matched the query to a specific pihole.log line reporting
`Jan 31 18:10:17 dnsmasq[907]: query[A] <name unprintable> from 127.0.0.1`
1. I then started adding print() statements in the `getAllQueries` section of `admin/api_db.php` and narrowed this down to `$results = $stmt->execute();` on line 137 returning an empty `SQLite3Result Object`

A couple of notes:
- I cannot see any errors in lighttpd or pihole logs about this. I _do_ see PHP fatals, but they do _not_ appear when I trigger this issue on purpose (by loading `/admin/api_db.php` with the problematic timestamps)
- I tried to see if it was a JSON issue, by setting `?jsonForceObject=1` but it didn't help
- I am aware that it's likely not Pi-hole making this request, despite it coming from 127.0.0.1; I have a couple other things running on the same RPi, but this appears to be a sanitization issue.
- I think this should be sanitized on input into the DB (I don't know where that happens), to prevent adding the garbled data to the SQLite DB

Happy to provide additional information if needed!

Thanks!

**Comment by DL6ER** [comment]
This is not an issue for FTL and the database as the have been carefully engineered to be able to handle any kind of domains (even containing invalid and/or international characters) so there is no such thing as garbled data in the DB. This is rather a problem of the web frontend not being able to render them correctly.

Pi-hole v5.0 should be able to handle these queries as it ensures that only properly UTF-8 encoded domains are passed to the web interface. If you're willing to test the beta, we can provide you wil instructions for doing so. If you don't want to test the beta, no problem, could you send me the exact data that is causing this issue?

You should be able to extract them using
```
sqlite3 /etc/pihole/pihole-FTL.db "SELECT * FROM queries  WHERE timestamp = 1579655570;" > export.data
```
if I made no typo.

**Comment by flyingstar16** [comment]
Makes sense, I was expecting an issue somewhere in the UI (e.g. `/admin/api_db.php`); I probably failed to make that clear, didn't mean to list it as an FTL issue.

I'm happy to test the beta, let me know how.

Do you have anywhere I can send the data? It's most likely garbage, but I can't be sure and I'd rather not attach it to a public issue in case it's something I should keep private.

**Comment by DL6ER** [comment]
> I'm happy to test the beta, let me know how.

See here for instructions: https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/

In case you find the error still persisting, feel free to send the file to <my Github username> <at> pi-hole.net and just put a note here when you've sent it. Thanks!

**Comment by flyingstar16** [comment]
Beta seems to have solved it, thanks a lot for your help!
![image](https://user-images.githubusercontent.com/582280/74606916-b056f880-50d4-11ea-8bb5-825c8c3e49d3.png)
