### ISSUE TITLE
 Problem with webservers (Lighttpd not working)

### ISSUE THREAD

**Issue by angaba92** [pi-hole/pi-hole#3116]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

Pihole working fine and accessing GUI ok

**Actual behaviour:**
I've had a Raspberry 3B for two years now using piVPN, pihole and samba without any problems.
I wanted to install owncloud/Nexcloud to make a private cloud with MariaDB. MariaDB installed it without problems and until that moment lighttpd worked fine. I started installing the new versions of php and lighttpd but I had problems with some php packages. I tried with apache but I had the same result. Now in the pihole GUI page I can't access, I get the ERR_CONNECTION_REFUSED.
I have been following this guide: hhttps://geekland.eu/instalar-nextcloud-mariadb-lighttpd/
You can see in the image the outcome os the service status:

[https://discourse-cdn.pi-hole.net/uploads/default/original/2X/2/262cbc0325dd7caf339bb52b5befe0e5ab5040cb.png](url)
![image](https://user-images.githubusercontent.com/59536943/73830974-d7284b80-4805-11ea-86e9-02f37fef2355.png)

[https://discourse-cdn.pi-hole.net/uploads/default/original/2X/4/4874879ae2c7fb369e71db9a120e971feddc5045.png](url)
![image](https://user-images.githubusercontent.com/59536943/73831024-eeffcf80-4805-11ea-9d07-b0789732e2db.png)

I got a ERR_CONNECTION_REFUSED in the browser. Trying to figure out with webservers and both (apache2 and lighttpd) are not working.
Can someone help me?
if I do /var/log/syslog and /var/log/lighttpd/error.log
![image](https://user-images.githubusercontent.com/59536943/73842764-83296100-481d-11ea-9cf9-6a83afcfd91a.png)

![image](https://user-images.githubusercontent.com/59536943/73843096-3a25dc80-481e-11ea-9a9d-cddb3db0dffb.png)

here the permises of the file is making trouble

![image](https://user-images.githubusercontent.com/59536943/73852019-c6d89680-482e-11ea-8d97-5220f880c600.png)

**Steps to reproduce:**

having installed lighttpd, trying to establish a private cloud with nextcloud

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/7ci4cf0jxc

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by dschaper** [comment]
Since this is a configuration issue and not a bug, please visit https://discourse.pi-hole.net and open a topic for the team and community to assist with.
