### ISSUE TITLE
Suggestions for More Blacklisting Functionality

### ISSUE THREAD

**Issue by abusr** [pi-hole/pi-hole#3118]
I am evaluating pi-hole for use at home and I find it mediocre in terms of blocking capabilities. In brief, it is using Posix ERE (egrep style) for its rules and it provides no additional connector for more advanced matching. I'm expanding:

1. Posix ERE works for simple rules but it gets in the way for more advanced rules. And it is quite an old standard, among the regular expressions' families. I propose against it. It should be replaced by something more modern and powerful.

2. Even with Posix ERE or with any other sort of regex, some things can not be programmed just by regexes. To facilitate this, consider a statistical filter which by policy (unless instructed otherwise) blocks a domain when it starts seeing a developing avalanche of requests for this domain and subdomains. Architecturally the time component and the previous history are parameters which cannot be addressed by just regexes of any sort. Same is the user (or IP) which originates every dns request. So I propose a more advanced, user supplied matcher, in case regexes seem too naïve.

Thank you in advance.
Ab

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
