### ISSUE TITLE
FLT out of date and refuse to upgrade

### ISSUE THREAD

**Issue by hygroscopiccarpaccio** [pi-hole/pi-hole#3121]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`FLT is out of date and does not update:

pihole -v
  Pi-hole version is v4.3.2 (Latest: v4.3.2)
  AdminLTE version is v3.2.1 (Latest: v4.3.2)
  FTL version is v2.13.1 (Latest: v4.3.1)

pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: FTL:            update available
:::
::: FTL out of date

  [i] FTL Checks...

  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.3.1/tbd not found`

**Actual behaviour:**

`FLT fails to upgrade`

**Steps to reproduce:**

`The installation process ends fine when doing a One-Step Automated install or any of the other two installation alternatives. However, FLT remains the same out of date. This regardless if chosing the "Update" or "Reconfigure" option. Also pihole -r does not help `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Debug token please?

**Comment by PromoFaux** [comment]
>Error: URL https://github.com/pi-hole/FTL/releases/download/v4.3.1/tbd not found`

Looks like the TBD bug again, though obviously not fixed until next release. Would be interesting to gleam some more detailed information about your system OP, so we can get further towards understanding what causes this to happen!

**Comment by dschaper** [comment]
Would the `tbd` cause AdminLTE to not upgrade as well?

**Comment by PromoFaux** [comment]
Good question, if the installer is crapping out before it gets to the web repo part, then yes.

**Comment by hygroscopiccarpaccio** [comment]
Debug token
https://tricorder.pi-hole.net/ekubbacqzr

**Comment by dschaper** [comment]
Raspbian Jessie (8) has been end of life for a while now and hasn't been supported by Pi-hole for the same amount of time. 

The debug log is from something I don't recall seeing, the format is very old. 

Best option at this point is to burn a new Raspbian image with Buster (10) and go from there.

**Comment by hygroscopiccarpaccio** [comment]
I had no idea that Jessie was end of life and not supported. Installed Buster and it's working fine. Thanks all!

**Comment by pheiduck** [comment]
Bug is also present after update core to 4.3.3 on Raspbian Buster

**Comment by dschaper** [comment]
Upgrade to 4.3.4

**Comment by pheiduck** [comment]
:D 4.3.4 fixed this, thanks for the fast response @dschaper
