### ISSUE TITLE
pihole debug

### ISSUE THREAD

**Issue by nclmrc** [pi-hole/pi-hole#3122]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5
version 5.0

[i] Default IPv4 gateway: ppp0
   * Pinging ppp0...
ping: ppp0: Nessun indirizzo associato al nome host
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)

[✓] Your debug token is: https://tricorder.pi-hole.net/tpz0s19hki

**Comment by dschaper** [comment]
Is there an issue that you are having?

Also, please do not use our logo as your user avatar.

**Comment by nclmrc** [comment]
debug when test connection, if i have a ppp connection the ping test is wrong

[i] Default IPv4 gateway: ppp0

    Pinging ppp0...
    ping: ppp0:

**Comment by dschaper** [comment]
The debug is just a coarse check of the conditions. If the Pi-hole is working fine then there is nothing to worry about.
