### ISSUE TITLE
Pi-Hole Shop link displaying Page Not Found

### ISSUE THREAD

**Issue by QAInsights** [pi-hole/pi-hole#3129]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
_1
---

**[BUG | ISSUE] Expected Behaviour:**
https://pi-hole.net/shop/ should display the valid page.

**[BUG | ISSUE] Actual Behaviour:**
https://pi-hole.net/shop/ displaying `Page Not Found` error.

**[BUG | ISSUE] Steps to reproduce:**

- Visit https://github.com/pi-hole/FTL
- Scroll down to `Alternative support` header, click on `Pi-hole Swag Store` link

**Log file output [if available]**
NA

**Device specifics**
Hardware Type: Laptop
OS: Windows 10, Edge browser version 79.0.309.71

**Comment by dschaper** [comment]
We'll remove the link.

**Comment by dakshsrivastava** [comment]
This may be closed. Please refer [#742](https://github.com/pi-hole/FTL/pull/742)

**Comment by bellwood** [comment]
pi-hole.net still shows a shop link in the header, currently linked to page:

https://pi-hole.net/?page_id=55535

...which does not exist.
