### ISSUE TITLE
gravity.sh can't run whitelist/blacklist.sh via cron?

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#313]
If I run gravity.sh from the command-line (as root):

```
::: Running whitelist script to update HOSTS file... 60 domains whitelisted!
::: Running blacklist script to update HOSTS file... 11 domains blacklisted!
```

But when it runs via the scheduled cron job:

```
::: Running whitelist script to update HOSTS file.... \/usr/local/bin/gravity.sh: line 248: whitelist.sh: command not found
  60 domains whitelisted!
::: Running blacklist script to update HOSTS file.... \/usr/local/bin/gravity.sh: line 223: blacklist.sh: command not found
  11 domains blacklisted!
```

The "xx domains yyyylisted" message is based on the 'wc' of the whitelist/blacklist.txt files so that's misleading since actually NO domains were properly whitelisted or blacklisted since gravity.sh couldn't find the whitelist/blacklist.sh scripts for some reason. Those scripts ARE in /usr/local/bin so I'm not sure why they're not found when run via cron (which is also running as root). For now I've updated gravity.sh to include the full path to whitelist.sh and blacklist.sh.

**Comment by PromoFaux** [comment]
Good catch. I'll update this in the development branch for fix in the next release.

**Comment by jradwan** [comment]
Great, thanks!
