### ISSUE TITLE
100C temperature on virtual machine

### ISSUE THREAD

**Issue by sfkpmr** [pi-hole/pi-hole#3136]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

Duplicate of closed https://github.com/pi-hole/pi-hole/issues/2519.

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Not display a temperature at all.

**Actual behaviour:**

https://user-images.githubusercontent.com/3502081/48938226-a2daaf00-ef21-11e8-8323-4c27ac9dc3ad.png

**Steps to reproduce:**

Install Pihole in a virtual machine.

Running Pi-hole in Linux pihole 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 on VMware ESXi 5.5.0.

**Comment by dschaper** [comment]
I don't think a VM would expose the files necessary to know what the CPU temp is. I also don't think it's possible to know if a VM is being used to be able to disable that portion of the interface.

**Comment by sfkpmr** [comment]
Maybe the logic that makes the UI show 100C could be changed to hide the temperature instead?

**Comment by DL6ER** [comment]
On what would you base the decision to hide the temperature? On being high? On real hardware, this is something the user would surely like to know. Note that the max temperature for many CPUs is listed in the 105-110°C range, so this could very well be real!

**Comment by sfkpmr** [comment]
Yes, I thought of that after posting, that it could be an issue for non-VMs.

**Comment by TheHades** [comment]
> I also don't think it's possible to know if a VM is being used to be able to disable that portion of the interface.

If you are using virtualization, Linux adds the `Hypervisor`-Flag to `lscpu`

**Comment by sfkpmr** [comment]
If not automate the detection, a setting to disable it would be nice.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
