### ISSUE TITLE
"Data stream error" during pihole -up

### ISSUE THREAD

**Issue by tomose** [pi-hole/pi-hole#3142]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

An update without errors.

**Actual behaviour:**
```
  [i] Checking for updates...
error: inflate: data stream error (incorrect data check)
fatal: packed object cc47bf8f6cb9b23a01b62359d78fd796b122705d (stored in .git/objects/pack/pack-124182772e5d3fa2a0fbd2104a7940fdf75d0ba3.pack) is corrupt
fatal: the remote end hung up unexpectedly
  [i] Pi-hole Core:     up to date
error: inflate: data stream error (invalid bit length repeat)
fatal: packed object 15746625a385419e2ef632fd234bf1f42f6ac2d9 (stored in .git/objects/pack/pack-bd1c80ac1a468de7736dc56a58ccaef34d00562f.pack) is corrupt
fatal: the remote end hung up unexpectedly
  [i] Web Interface:    up to date
  [i] FTL:              up to date
  [✓] Everything is up to date!
```
**Steps to reproduce:**

Last pihole install died. I cloned a backup image I had from November onto a new card, put it in, ran `sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y" then did pihole -up`

**Troubleshooting undertaken, and/or other relevant information:**

Rebooted, tried `sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y` again, tried `pihole -up` again.

`pihole checkout master` produces
```
  [i] Pi-hole core
error: inflate: data stream error (incorrect data check)
fatal: packed object cc47bf8f6cb9b23a01b62359d78fd796b122705d (stored in .git/objects/pack/pack-124182772e5d3fa2a0fbd2104a7940fdf75d0ba3.pack) is corrupt
fatal: the remote end hung up unexpectedly
  [✗] Unable to pull Core master branch
```
*****
"Try a sudo git fsck in the /var/www/html/admin/ directory and hopefully that will allow for a sudo git pull to complete."

Showed errors, so I ran:
```
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/AdminLTE /var/www/html/admin
```

`pihole -up` now shows:
```
  [i] Checking for updates...
error: inflate: data stream error (incorrect data check)
fatal: packed object cc47bf8f6cb9b23a01b62359d78fd796b122705d (stored in .git/objects/pack/pack-124182772e5d3fa2a0fbd2104a7940fdf75d0ba3.pack) is corrupt
fatal: the remote end hung up unexpectedly
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
```
`pihole -r `

produces no negative results except:
```
  [✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up
  [✗] DNS service is not running
  [✓] Starting DNS service
  [i] Time until retry: 115
  [✗] DNS resolution is not available
```
after a reboot, `pihole -up` still shows:
```
  [i] Checking for updates...
error: inflate: data stream error (incorrect data check)
fatal: packed object cc47bf8f6cb9b23a01b62359d78fd796b122705d (stored in .git/objects/pack/pack-124182772e5d3fa2a0fbd2104a7940fdf75d0ba3.pack) is corrupt
fatal: the remote end hung up unexpectedly
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date
  [✓] Everything is up to date!
```

**Comment by dschaper** [comment]
You have local file system corruption. This isn't an issue specific to Pi-hole.

**Comment by dschaper** [comment]
If you want, you can try to `rm /etc/.pihole` and then `git clone https://github.com/pi-hole/pi-hole /etc/.pihole` but that's not a guaranteed solution.

**Comment by tomose** [comment]
Thanks for the reply, going to try dropping the backup image onto a new SD and see how things go.
