### ISSUE TITLE
[Dev] - Domain showing up as "Status: Blocked (Gravity)" dispite whitelisting

### ISSUE THREAD

**Issue by Sophie-Hawley** [pi-hole/pi-hole#3146]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Whitelisted domains should be allowed in all cases

**Actual behaviour:**

Whitelisted Domains continue to be blocked

**Steps to reproduce:**

add the following site to whitelist: "www.googletagmanager.com" via the Query Log.
Attempt to browse to www.googletagmanager.com (specifically https://www.googletagmanager.com/gtag/js?id=UA-104948571-1)
Observe DNS Failure/Continued blocking in the Query list

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

udkzo67w8q

**Troubleshooting undertaken, and/or other relevant information:**

attempted whitelisting this and the generic domain (googletagmanager.com) via several method, updating the gravity list, and attempted rebooting the DNS resolver to flush the cache and rebooting the pi as a whole. Issue persisted through all of this.

**Comment by dschaper** [comment]
What does `dig www.googletagmanager.com @192.168.1.254` show for an IP?

**Comment by dschaper** [comment]
Also make sure that you have the groups assigned as you want them:

```text
*** [ DIAGNOSING ]: Domainlist (0/1 = exact/regex whitelist, 2/3 = exact/regex blacklist)
   id    type  domain                                                                                                enabled  date_added           date_modified        comment                                           
   ----  ----  ----------------------------------------------------------------------------------------------------  -------  -------------------  -------------------  -------------------------------------------------        
   22    0     www.googletagmanager.com                                                                              1        2020-02-18 21:20:30  2020-02-18 21:20:53  Teamcraft   
```
```text
*** [ DIAGNOSING ]: Domainlist groups
   domainlist  group_id  
   ----------  ----------
   3           2         
   4           2         
   5           2         
   6           2         
   7           2         
   8           2         
   9           2         
   10          2         
   11          2         
   12          2         
   13          2         
   14          2         
   15          2         
   16          2         
   17          2         
   18          2         
   22          1         
```

Looks like the whitelisting is being applied to group 1 and the others are applied to group 2.

The clients may not be in the correct groups as well:

```text
*** [ DIAGNOSING ]: Client groups
   client_id   group_id  
   ----------  ----------
   1           0         
   2           0         
   3           0         
   4           0  
```

**Comment by Sophie-Hawley** [comment]
Yeah i discovered i was using groups incorrectly and then removed them completely, the issue persisted

**Comment by Sophie-Hawley** [comment]
Nevermind, something must have been cached I thought I cleared after removing the problematic grouping. Waiting awhile seems to have solved it, closing.
