### ISSUE TITLE
Windows says no internet connection, but there is...!

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#315]
In the latest release, one of the adlists contains `www.msftncsi.com`, which is the domain used by windows to determine network connectivity.

You can either whitelist this domain using: `whitelist.sh msftncsi.com www.msftncsi.com`

Or follow the instructions [here](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) to customise the adlists.

`msftncsi.com` is included on the following lists:
```
http://optimate.dl.sourceforge.net/project/adzhosts/HOSTS.txt
https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt
```

Or do nothing. You'll still have an internet connection, even if windows thinks you don't!

**Comment by DonLexos** [comment]
Thanks for the tip, added it just now just to be sure.

**Comment by DonLexos** [comment]
Btw maybe it would be wise to pre-greenlist these in the default installation?

**Comment by PromoFaux** [comment]
Yeah, It can certainly be put in the FAQ, but we should keep the issue open for now for visibility.

I think pre-whitelisting/approving domains is a dangerous track to go down. Last thing we want is people thinking that we're doing shady deals to accept certain domains....

**Comment by DonLexos** [comment]
Ok there are a few more, will compile them and put them all in the regular FAQ wiki

**Comment by sy3dn** [comment]
This issue makes my phone (Windows Phone) unable to connect wifi :octopus:

**Comment by PromoFaux** [comment]
Hi @sy3dn , does the problem go away if you whitelist the above-mentioned domain?

**Comment by DonLexos** [comment]
Added this to the [FAQ wiki](https://github.com/pi-hole/pi-hole/wiki/FAQs)

**Comment by sy3dn** [comment]
Hi @PromoFaux , yes the problem resolved after I whitelist the domain you listed. :+1:

**Comment by PromoFaux** [comment]
Closing, as @DonLexos has transposed the info to the wiki
