### ISSUE TITLE
Donation page support for Apple Pay seems broken

### ISSUE THREAD

**Issue by DavidAnson** [pi-hole/pi-hole#3155]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Attempting to donate money via https://pi-hole.net/donate/ using Safari from either of two iOS devices allows me to do so via Apple Pay.

**Actual behaviour:**

> ERROR: Either your browser does not support Apple Pay or you do not have a saved payment method.

**Steps to reproduce:**

1. https://pi-hole.net/donate/
2. Change to Apple Pay

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

Verified the successful operation of Apple Pay on same device/browser via https://applepaydemo.apple.com/

**Comment by dschaper** [comment]
Thanks, it's a known and ongoing issue between the payment gateway and our donation package. 

I'll look at using another donation package in replacement of what we have now.

**Comment by dschaper** [comment]
I've rebuilt a few things and updated some others. Can you check and see if Apply Pay works now?

**Comment by DavidAnson** [comment]
Seems like it did! I have a donation ID if you need it.

**Comment by dschaper** [comment]
Thanks! It's all looking good from our side. 

Will close this out.

**Comment by christianwgd** [comment]
I'm afraid this is still relevant. Tried today and got the message "ERROR: Either your browser does not support Apple Pay or you do not have a saved payment method."
Also verified with Apple Demo.

**Comment by dschaper** [comment]
Thanks for the note, I'm not sure what to do next, we've received multiple donations via Apple Pay, at least a dozen since Sunday. If you send me an email at dan.schaper@pi-hole.net with an IP address or a name that you used I can try to go through any logs, maybe there's something we can find to fix?
