### ISSUE TITLE
Would like to be able to subscribe to whitelists just like we can blacklists

### ISSUE THREAD

**Issue by unixorn** [pi-hole/pi-hole#3156]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

n/a

---
**Expected behaviour:**

In the settings page, I'd like there to be a whitelists tab with the same functionality as the current blacklists tab

**Actual behaviour:**

I have to add whitelist entries individually

**Steps to reproduce:**

n/a

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n/a

I'm running 4.3.2 with the 4.3.2 web interface from inside a docker container.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Per issue template/contribution guide:

> All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)

Thanks for your understanding

**Comment by unixorn** [comment]
Sorry, will bring it up there.

**Comment by PeterDaveHello** [comment]
Reference: https://discourse.pi-hole.net/t/subscribe-to-user-maintained-whitelists-and-whitelist-from-a-file/3327/31
