### ISSUE TITLE
Preventing Firefox to switch to DoH does not work by default

### ISSUE THREAD

**Issue by luzat** [pi-hole/pi-hole#3167]
**In raising this issue, I confirm the following:**
- [X] I have 
read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

When runnig a query (`dig -t A use-application-dns.net`, `dig -t AAAA use-applications-dns.net`) against Pi-hole I expect to get `NXDOMAIN` (or similar) to indicate that DoH should not be used by Firefox ([canary domain](https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet)).

**Actual behaviour:**

`0.0.0.0` and `::` respectively are returned.

**Steps to reproduce:**

Install most recent Pi-hole (9e490775ff3b20f378acc9db7cec2ae6023fff7f). `/etc/dnsmasq.d/01-pihole.conf` will contain `server=/use-application-dns.net/`. Make sure Pi-hole is your resolve and try to resolve `use-application-dns.net`.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/1xa35wpouj

**Troubleshooting undertaken, and/or other relevant information:**

The problem seems to be that blacklists take place first and the default list contains a blacklist entry in [StevenBlack's list](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts). Adding a whitelist entry for `use-application-dns.net` makes the resolver return `NXDOMAIN` anyway. Maybe this should be the default; otherwise the setting in `01-pihole.conf` introduced by #2916 is probably useless by default.

**Comment by dschaper** [comment]
Thanks for the report, can you provide a debug run token so we can see if the configs are applied correctly?

**Comment by dschaper** [comment]
Contacting the list maintainer as well.

https://github.com/StevenBlack/hosts/issues/1172

**Comment by luzat** [comment]
Added the debug token.

**Comment by press5** [comment]
I ran into the same issue, there are entries in `gravity.list` and `list.preEventHorizon`  which override the directive `server=/use-application-dns.net/` in `/etc/dnsmasq.d/01-pihole.conf` and make it erroneously return `0.0.0.0`. 

List maintainers should remove entries for `use-application-dns.net`.

**Comment by dschaper** [comment]
Workarounds are to either use BLOCKINGMODE=NXDOMAIN or to whitelist use-application-dns.net.

**Comment by press5** [comment]
@dschaper as a temporary fix until are updated to remove the entries?

**Comment by dschaper** [comment]
Or as prevention from them being included in the future.

**Comment by press5** [comment]
That makes sense. It seemed strange to me that pihole would include `server=/use-application-dns.net/` out of the box only to nullify it in a list in the very next step...

**Comment by dschaper** [comment]
Pi-hole does not curate or control the list content. They are maintained by community members.

**Comment by dschaper** [comment]
This should be resolved with the lists mentioned.

https://github.com/StevenBlack/hosts/issues/1172

Closing for now.

**Comment by Extarys** [comment]
Does this issue applies toV5 Beta and will this fix be made available on that version as well?

**Comment by dschaper** [comment]
Beta 5 had it for a while now. No changes needed.
