### ISSUE TITLE
YouTube Bloomberg - Gets Blocked! - Might be More - V_4.3.2 - FTL_4.3.1

### ISSUE THREAD

**Issue by desmonk** [pi-hole/pi-hole#3168]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

`Should not block them.`

**Actual behaviour:**

`Blocks many genuine domains such as YouTube, Bloomberg.
Note that if we add full address "www" then they work.`

![pi-hole blocked youtube](https://user-images.githubusercontent.com/55331939/75330039-92c62380-5878-11ea-9b49-28196e1be8ad.PNG)

**Steps to reproduce:**

`Just type them in a web and gets blocked.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Can't have it cause of nature of work.`

**Troubleshooting undertaken, and/or other relevant information:**

`reboot and flushed logs.`

**Comment by PromoFaux** [comment]
Without seeing your debug log, I can't say for certain, but it is likely an additional block list that you have added post-install.

Pi-hole only blocks what you, as the user, tells it to block. I know that `youtube.com` is not on any of the (optional) default lists (or at least, it wasn't when last I checked, and I run on nothing other than those lists)

`pihole -q youtube.com` will tell you which list it is on.

**Comment by PromoFaux** [comment]
>Can't have it cause of nature of work.

Also, just to let you know, there isn't really anything in there that we can identify you with, and only trusted developers have access to the log (which automatically expires). You can review the content of the log locally first, if you wish, and either upload a new token if you decide it's OK, or copy paste from your local copy with any potentially sensitive information redacted.

**Comment by desmonk** [comment]
I am very sorry that I had opened up the case without much effort but luckily found out the issue was with a host file here.

https://v.firebog.net/hosts/Kowabit.txt
