### ISSUE TITLE
Broken blocking list update in update Pi-hole to 4.4

### ISSUE THREAD

**Issue by HumbleSpirit** [pi-hole/pi-hole#3171]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`8`

---
**Expected behaviour:**

Updated blocklist

**Actual behaviour:**

  [i] Extracting domains from blocklists.../opt/pihole/gravity.sh: line 329:  8204 Broken pipe             awk -F '#' '{print $1}' < ${source}
      8205                       | awk -F '/' '{print $1}'
      8206                       | awk '($1 !~ /^#/) { if (NF>1) {print $2} else {print $1}}'
      8207 Illegal instruction     | sed -nr -e 's/\.{2,}/./g' -e '/\./p' > ${destination}

**Steps to reproduce:**

sudo pihole -up

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/bt9myhc9h7

**Troubleshooting undertaken, and/or other relevant information:**

Only original block-list is applied, not ones from third-parties

**Comment by dschaper** [comment]
Looks like there are some invalid regex entries:

```text
   [2020-02-27 01:11:08.505 8968] Skipping empty regex filter on line 1
   [2020-02-27 01:11:08.505 8968] ERROR compiling regex on line 2: Invalid preceding regular expression (13)
```

**Comment by dschaper** [comment]
By the way, you need to block public access to your Pi-hole instance and the open resolver.

**Comment by HumbleSpirit** [comment]
> By the way, you need to block public access to your Pi-hole instance and the open resolver.

Thanks. I never had issues with it.
The recursive resolver is not detected on your IP

**Comment by yubiuser** [comment]
Closing this issue as Pi-hole's as evolved a lot since the issue was filed. Please open a new ticket if the issue persists.
