### ISSUE TITLE
Pi-hole installation on Ubuntu 18.04 fails to install FTL

### ISSUE THREAD

**Issue by craibuc** [pi-hole/pi-hole#3174]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi-hole installs properly

**Actual behaviour:**

The Pi-hole installer is not able to install the FTL:

<img width="868" alt="Screen Shot 2020-02-27 at 9 40 16 AM" src="https://user-images.githubusercontent.com/216592/75501193-e0d04980-5994-11ea-9a26-91a83a742a7c.png">

**Steps to reproduce:**

 - [downloaded package](https://ubuntu.com/download/server/thank-you?version=18.04.4&architecture=amd64)
 - opened VMWare Fusion (11.5.1)
 - installed Ubuntu 18.04.4
 - after installation, ran `sudo apt-get upgrade && sudo apt-get update -y && sudo reboot`
 - started pi-hole installation (`curl -sSL https://install.pi-hole.net | bash`)
 - selected default values

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Posted a message on Reddit.com/r/pihole.

**Comment by craibuc** [comment]
I posted this issue on Reddit ([FTL installation fails on Ubuntu 18.04](https://www.reddit.com/r/pihole/comments/faeyjh/ftl_installation_fails_on_ubuntu_1804/)).

Based on masmith22 suggestion, I tried the Pi-hole installation again.  When prompted for the DNS, I used `8.8.8.8, 9.9.9.9`.  

As a result, the installation completed successfully, including the installation of FTL.

**Comment by dschaper** [comment]
That may have been a coincidence. the URL in the screenshot works. Had the issue been with DNS you would have seen a different error. As I noted in the reddit thread, GitHub was having issues today and this is what I expect to see when that is happening.

**Comment by craibuc** [comment]
> That may have been a coincidence. the URL in the screenshot works. Had the issue been with DNS you would have seen a different error. As I noted in the reddit thread, GitHub was having issues today and this is what I expect to see when that is happening.
> 
> `curl: (28) Operation timed out` happens after `github.com` is found in DNS.

The odd thing is, I've encountered this same error when trying to install Pi-hole on a different VM (Hyper-V) from the office, about 2 weeks ago.  Perhaps Github was having issues then, too.

**Comment by dschaper** [comment]
That would have been a different error. Not "timed out" but a 404 for URL not found.
