### ISSUE TITLE
Block DOH firefox then pihole 4.4.

### ISSUE THREAD

**Issue by tigernero79** [pi-hole/pi-hole#3181]
sorry for the trivial question but once I update my pihole to release 4.4 the doh block on firefox as it happens automatically? in the sense that if I try to set the doh on firefox it should give me some warning block? I already use doh and dot thanks to dnscrypt-proxy cohn pihole all on my p0w raspberry but I don't understand if the doh on firefox is blocked automatically or I have to do something on pihole

another problem, I use pi hole in combination with dnscrypt-proxy 2 which have recently added local doh service for the encrypted esni, in practice the firefox requests are diverted to p0 which is listening on port 3000 with self-signed and set certificates dnscryptproxy the path is: https: // ip_Lan: 3000 url which must be set in firefox to manage not only its doh but the function that only FF has of the encrypted sni. i wonder pihole also blocks internal lan requests having I listened on 0.0.0.0:3000 all requests in dnscrypt proxy in order to reach local doh also from outside via my personal url. tested ff with doh cloudflare in vpn connected to my pihole but it does not block me cheidevo must be set qlc in pihole to block doh or does it automatically?

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all non-bug discussions on our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
