### ISSUE TITLE
Syntax Error when running pihole -up

### ISSUE THREAD

**Issue by jankrieg** [pi-hole/pi-hole#3184]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

Hi,

I tried to updata pi-hole. I executed pihole -up and got "/etc/.pihole/automated_install/basic-install.sh: Line 1477: Syntax error at unexpected word '}' ".

Are there any other ways to upgrade pi-hole? Do I have to reinstall everything?

Thanks,
Jan

**Comment by dschaper** [comment]
Please provide a debug token.

**Comment by jankrieg** [comment]
https://tricorder.pi-hole.net/jvzsgs85j5

**Comment by dschaper** [comment]
Thanks, can you do the following: (You may need to be root to do it, so `sudo -s`)
```sh
cd /etc/.pihole
git status
git diff origin master automated\ install/basic-install.sh
```

**Comment by jankrieg** [comment]
They are identical.

**Comment by dschaper** [comment]
One more check, the path you show is `/etc/.pihole/automated_install` and that doesn't exist with our repository. If that is just a typo for `/etc/.pihole/automated\ install` then try the below instructions. If that's not a typo and the path does exist then the output from `git status` is needed.

Okay, let's manually install the latest `/etc/.pihole` and kick it off.

```sh
sudo -s
cd /
rm -rf /etc/.pihole
git clone https://github.com/pi-hole/pi-hole /etc/.pihole && cd $_
/etc/.pihole/automated\ install/basic-install.sh
```

**Comment by jankrieg** [comment]
That worked. I was able to install the latest version.  For me the shell script code (line 1477) looked okay but I'm not an exert here. Anyway, sometimes software behaves a bit strange....
Thanks a lot for you quick support.
Regards,
Jan

**Comment by dschaper** [comment]
Glad we could help!
