### ISSUE TITLE
New security features

### ISSUE THREAD

**Issue by lordraiden** [pi-hole/pi-hole#3187]
NextDNS has the following security features, why the same can't be develop for pihole?

- DNS Rebinding Protection
- IDN Homograph Attacks Protection
- Typosquatting Protection
- Domain Generation Algorithms (DGAs) Protection
- Block Newly Registered Domains (NRDs)
- Block Parked Domains
- Top-Level Domains (TLDs) Blocking
- Block Bypass Methods
- Google Safe Browsing
- YouTube Restricted Mode
- Safe Search

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by lordraiden** [comment]
> 
> 
> Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).
> 
> Thank you for your understanding.

Light speed answer xD
Ok, I will do it
