### ISSUE TITLE
If a regexp blocks a site where i need to download lists, PI-Hole doesnt shows the reason.

### ISSUE THREAD

**Issue by stefanostatuti** [pi-hole/pi-hole#3196]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
the console shows the correct reason about the block.

   [i] Target: blocklist.site (tracking)
  [✗] Status: blocklist.site is blocked by **regex/wildcard**. Using DNS on 208.67.222.222 to download https://blocklist.site/app/dl/tracking
  [✓] Status: No changes detected

**Actual behaviour:**
no info about the reason for the block, i think is logged like a NULL string.
 [i] Target: blocklist.site (tracking)
  [✗] Status: blocklist.site is blocked by . Using DNS on 208.67.222.222 to download https://blocklist.site/app/dl/tracking
  [✓] Status: No changes detected

**Steps to reproduce:**
add a regEXP to block .site domains like this: 
.site$
now try to download updates 
in query log tab you can see: blocklist.site  -->Blocked (regex/wildcard)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/0aiiamtkks
`{Alphanumeric token}`

**Troubleshooting undert

**Comment by stefanostatuti** [comment]
ok, maybe i found the problem.
gravity.sh lines 271-272

 bad_list=$(pihole -q **-adlist** "${domain}" | head -n1 | awk -F 'Match found in ' '{print $2}')
    echo -e "${OVER}  ${CROSS} ${str} ${domain} is blocked by ${bad_list%:}. Using DNS on ${PIHOLE_DNS_1} to download ${url}";

pi@raspberrypi4:~ $ pihole -q -adlist blocklist.site | head -n1 | awk -F 'Match found in ' '{print $2}'

pi@raspberrypi4:~ $ pihole -q -adlist blocklist.site
  [i] No results found for blocklist.site within the block lists

does pihole checks only in adlist?

**Comment by stefanostatuti** [comment]
i propose this patch:
add at line 272
` if [ $(echo -n ${bad_list} | wc -m) -eq 0 ]; then
		bad_list='RegEx' # or 'RegularExpression' if you think is better
 fi`

now the message is like expected.

![Screenshot_2020-03-07 Pi-hole Admin Console(1)](https://user-images.githubusercontent.com/4499372/76150952-d1957e00-60af-11ea-9d28-f33c60bce0e2.png)

**Comment by yubiuser** [comment]
This should be fixed already by:
https://github.com/pi-hole/pi-hole/pull/3200

https://github.com/pi-hole/pi-hole/pull/3198#issuecomment-689135359
