### ISSUE TITLE
Missing check when importing 2 or more times the same regEXP

### ISSUE THREAD

**Issue by stefanostatuti** [pi-hole/pi-hole#3197]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
pi hole shows an eror message like a popup when try to import 2 times the same regExp

**Actual behaviour:**
is possible ti import 2 or more times the same RegExp

**Steps to reproduce:**
import a regexp, for example
(^|\.)click\.       and click 'Add (regex)' button
now do the same steps another time

![Screenshot_2020-03-07 Pi-hole Admin Console](https://user-images.githubusercontent.com/4499372/76149980-c50c2800-60a5-11ea-85c1-9883f1c42d7c.png)

![Screenshot_2020-03-07 Pi-hole Admin Console](https://user-images.githubusercontent.com/4499372/76149980-c50c2800-60a5-11ea-85c1-9883f1c42d7c.png)

**Comment by DL6ER** [comment]
This is already solves in Pi-hole v5.0 where uniqueness is enforced across everything (e.g. you cannot whitelist something that is also blacklisted). The same uniqueness constraint prevents you from adding something which is already there.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
