### ISSUE TITLE
Pihole detects wrong IP adress

### ISSUE THREAD

**Issue by jerryhopper** [pi-hole/pi-hole#3199]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---

Pihole detects wrong IP adress

**Expected behaviour:**

After setting a static ip, pihole should detect the primary static ip-adress

**Actual behaviour:**

After setting a static ip, pihole detects the secundary dynamic ip-adress

Here is the result of  ip addr.  notice the secundary ip. 
the OS im usinge is dietpi (dietpi.com)

<pre>root@BlackBox:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:01:42:a0:81:32 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.4/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.1.15/24 brd 10.0.1.255 scope global secondary noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ab9d:c1a4:8576:7901/64 scope link
       valid_lft forever preferred_lft forever
</pre>

**Comment by dschaper** [comment]
Where is Pi-hole detecting this address?

**Comment by jerryhopper** [comment]
using nslookup pi.hole 127.0.0.1

it responds with 10.0.1.15

**Comment by dschaper** [comment]
`pihole -r` and reconfigure. It's based off of configuration files written during installation. Changing the IP after setup will not automatically update.

**Comment by jerryhopper** [comment]
Oh!  changing that /etc/pihole/local.list did the trick, thanks a bunch!!
