### ISSUE TITLE
Error FTL not found - first install

### ISSUE THREAD

**Issue by moranmoa** [pi-hole/pi-hole#3202]
hey 
I tried to install in all 3 Methods and I got the same error
"Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabi not found"
I tried to clone the FTL repo I can't find how to install it
this is one of my installation processes:
```
pi@raspberrypi:~/Pi-hole/automated install $ sudo bash basic-install.sh

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [i] Checking for dialog (will be installed)
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [i] Using Google (ECS)
  [✓] Set IP address to 192.168.1.115
  You may need to restart after the install is complete
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.1.115/24
  [i] IPv6 address:
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [i] Checking for dnsutils (will be installed)
  [✓] Checking for iputils-ping
  [i] Checking for lsof (will be installed)
  [i] Checking for netcat (will be installed)
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [i] Checking for idn2 (will be installed)
  [i] Checking for sqlite3 (will be installed)
  [✓] Checking for libcap2-bin
  [i] Checking for dns-root-data (will be installed)
  [i] Checking for resolvconf (will be installed)
  [✓] Checking for libcap2
  [i] Checking for lighttpd (will be installed)
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cgi (will be installed)
  [i] Checking for php-sqlite3 (will be installed)
  [✓] Enabling lighttpd service to start on reboot...
  [✓] Creating user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv6 or lower) Using ARM binary
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabi not found
  [✗] FTL Engine not installed
```

in my last try, I cloned the FTL repo but I couldn't find how to install it
it will be great for help
I'm really excited for this to work

thanks, Moran Abecassis

**Comment by dschaper** [comment]
`[i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com`

What is in your `/etc/resolv.conf` file for the DNS server?

**Comment by dschaper** [comment]
@pi-hole/core-approvers I think we should move FTL to the "installer dependencies" section.

This should be fixed in version 5 since `resolvconf` is not a dependency at all anymore.

**Comment by moranmoa** [comment]
sudo nano /etc/resolv.conf

# Generated by dhcpcd
# /etc/resolv.conf.head can replace this line
# /etc/resolv.conf.tail can replace this line

**Comment by dschaper** [comment]
What is the end of `/etc/dhcpcd.conf`?

**Comment by moranmoa** [comment]
its 3 lines

**Comment by dschaper** [comment]
Can we see them?

**Comment by moranmoa** [comment]
this is the lines
# Generated by dhcpcd
# /etc/resolv.conf.head can replace this line
# /etc/resolv.conf.tail can replace this line

**Comment by dschaper** [comment]
Sorry, I need to see the lines from `/etc/dhcpcd.conf`

**Comment by moranmoa** [comment]
I am using  "sudo nano /etc/resolv.conf"
https://drive.google.com/open?id=1vye7-LWuTUfohQYv_Sa6TOnhT-Cz1Mon

**Comment by dschaper** [comment]
That's not the file I asked for.

**Comment by PromoFaux** [comment]
@moranmoa please run the following command and paste in the output:

`cat /etc/dhcpcd.conf`

Also, just in case, the following commands too:

`cat /etc/resolv.conf.head`
`cat /etc/resolv.conf.tail`

**Comment by moranmoa** [comment]
pi@raspberrypi:~ $ cat /etc/dhcpcd.conf
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# Most distributions have NTP support.
#option ntp_servers

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
slaac private

# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.23/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0
interface eth0
        static ip_address=192.168.1.115/24
        static routers=192.168.1.1
        static domain_name_servers=127.0.0.1


pi@raspberrypi:~ $ cat /etc/resolv.conf.head
cat: /etc/resolv.conf.head: No such file or directory

pi@raspberrypi:~ $ cat /etc/resolv.conf.tail
cat: /etc/resolv.conf.tail: No such file or directory

**Comment by PromoFaux** [comment]
Thanks. Can you temporarily add the following line to `/etc/resolv.conf` using `nano` (may need to use `sudo` to save it)

`nameserver 8.8.8.8`

after that, try to run the installer again, hopefully it should give you an option to `update` or `repair`, can't recall off the top of my head... but that _should_ get you further in the install.

let us know!

**Comment by moranmoa** [comment]
no option to repair

pi@raspberrypi:~/Pi-hole/automated install $ sudo bash basic-install.sh

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.3.14-1~deb10u1
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Using Google (ECS)
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.1.115/24
  [i] IPv6 address:
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...
  : Could not update local repository. Contact support.

**Comment by moranmoa** [comment]
I can edit this before the install?

**Comment by PromoFaux** [comment]
Do you currently have `nameserver 8.8.8.8` in your `/etc/resolv.conf` file?

Some ancillary questions...

What Hardware/OS are you attempting to install onto?
What is the ouput of the following command?
`nslookup github.com`

**Comment by moranmoa** [comment]
yes, I added nameserver 8.8.8.8
like this  :

# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname
nameserver 8.8.8.8
# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# Most distributions have NTP support.
#option ntp_servers

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID


I think i don't have a connection after the fail install
pi@raspberrypi:~/Pi-hole/automated install $ nslookup github.com
;; connection timed out; no servers could be reached

**Comment by PromoFaux** [comment]
no, that's in `/etc/dhcpd.conf`

Please read any instructions given carefully! 😄 

The file you need to add that line to is `/etc/resolv.conf`

**Comment by moranmoa** [comment]
not a dyslexia-friendly names :)

`pi@raspberrypi:~ $ nslookup github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   github.com
Address: 140.82.118.4
`
install is up and works!!!
grate job thanx a lot
I will test it and will donate

**Comment by PromoFaux** [comment]
>not a dyslexia-friendly names :)

Hey, we got there in the end, and that is what matters!

Glad it's installed OK for you now!
