### ISSUE TITLE
How to deploy it on router?

### ISSUE THREAD

**Issue by Yofo-me** [pi-hole/pi-hole#3206]
So how to deploy it on my router?
> There is my router info :
` System Version :  the lastest Openwrt/LEDE build  with x64 `

Would you tell me how to make this or would you like to release  installation package?

**Comment by PromoFaux** [comment]
Please see here for supported operating systems:
https://docs.pi-hole.net/main/prerequesites/

If your Openwrt/LEDE router runs docker, then we have a docker image 

https://github.com/pi-hole/docker-pihole

**Comment by Yofo-me** [comment]
Your docker image url is 404.

**Comment by dschaper** [comment]
https://github.com/pi-hole/docker-pi-hole
