### ISSUE TITLE
Blacklist crashing

### ISSUE THREAD

**Issue by chrisjeb** [pi-hole/pi-hole#3212]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

open blacklist

**Actual behaviour:**

when blacklist is clicked, the page opens but pihole hangs completely webpage has to be reloaded to enter.
**Steps to reproduce:**

`click on blacklist tab`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`knowledge is very limited on coding and working`

**Troubleshooting undertaken, and/or other relevant information:**

`none`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Run `pihole -d` and let us know the token displayed at the end of the process.

**Comment by chrisjeb** [comment]
I apologize I am still learning this os. I ran the process but I dont understand what you mean by token. There is a bit of green text at the end pf the pihole -d command is this what you mean?

**Comment by dschaper** [comment]
There is a link displayed that says that it's the token value. Also displays the URL of `https://tricorder.pi-hole.net/XXXXXXX` where the `X`s are the token.

**Comment by chrisjeb** [comment]
Thank you for your patience. After it displays "Finished debugging" there is no mention of a token, it only asks if i want to upload the log.

**Comment by technicalpyro** [comment]
type `y` and hit the `[return]` or `[enter]` key then provide the token after upload

**Comment by chrisjeb** [comment]
When I try to upload it I receive an error I tried a debugging a second time and same result.

**Comment by technicalpyro** [comment]
Okay try the following.  
1.  `sudo nano /etc/resolv.cont` change `127.0.0.1` to `9.9.9.9` and save the file
2.  rerun the debug and upload the result 
3.  post the token here

**Comment by chrisjeb** [comment]
Ok I tried "sudo nano /etc/resolv.cont" and the page remains blank.

**Comment by technicalpyro** [comment]
hrmmm nano should be in a default image to remedy this try `sudo apt install nano`

**Comment by chrisjeb** [comment]
I tried this and i receive the message that "that nano is already the newest version".

**Comment by dschaper** [comment]
The file is `/etc/resolv.conf` note the last letter.

**Comment by chrisjeb** [comment]
Thats it, made changes and debugging now

**Comment by chrisjeb** [comment]
Unfortunately same error with log. Maybe just do a fresh install?

**Comment by chrisjeb** [comment]
Guys thank you for your time, it started working today.
