### ISSUE TITLE
Removing dependencies fail, apparently debconf to be precise

### ISSUE THREAD

**Issue by caballerofelipe** [pi-hole/pi-hole#3214]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

When uninstalling, and responding Y to the following:
`  [?] Do you wish to go through each dependency for removal? (Choosing No will leave all dependencies installed) [Y/n] y`
and then Y to the following:
`  [?] Do you wish to remove debconf from your system? [Y/N] y`
The program should continue.

**Actual behaviour:**

The program actually crashes.
<img width="1008" alt="Screen Shot 2020-03-17 at 21 40 57" src="https://user-images.githubusercontent.com/11650766/76914853-4039bf00-689a-11ea-8616-a8c6448749cd.png">

**Steps to reproduce:**

Install Pi-Hole and try to uninstall.

I am using VirtualBox, I installed rpd-x86-buster.iso. Pi-Hole is working.

When uninstalling, and responding Y to the following:
`  [?] Do you wish to go through each dependency for removal? (Choosing No will leave all dependencies installed) [Y/n] y`
and then Y to the following:
`  [?] Do you wish to remove debconf from your system? [Y/N] y`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

No token... I get:
`[✗]  There was an error uploading your debug log.`

I'm attaching it, hopefully there's nothing too private...
[2020-03-17_22-16-54_pihole_debug.log](https://github.com/pi-hole/pi-hole/files/4346467/2020-03-17_22-16-54_pihole_debug.log)

**Comment by dschaper** [comment]
You shouldn't be able to remove packages that the system depends on. `debconf` is used by `apt` and you shouldn't be saying `y` to uninstall it.
