### ISSUE TITLE
Installing pi-hole enables privacy extensions for ipv6, which leads to changing ips

### ISSUE THREAD

**Issue by breucode** [pi-hole/pi-hole#3220]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

After installing pi-hole on a fresh debian install, I still want the ipv6 addresses to be generated with mac based slaac, so that the ipv6 suffix does not change.

**Actual behaviour:**

Due to the installation of dhcpcd5 (which is not installed on debian by default) and enabling privacy extensions, the ipv6 adresses are constantly changing.

**Steps to reproduce:**

1. Fresh install on debian amd64
2. Check, that ipv6 adresses are generated with slaac
3. Install pi-hole (in my case without enabling the dhcp server)
4. The ipv6 adresses are now generated with privacy extensions due to the following line in /etc/dhcpcd.conf : `slaac private`

**Troubleshooting undertaken, and/or other relevant information:**

To fix that, replace `slaac private` with `slaac hwaddr`

In my opinion, pi-hole should not change the generation of ipv6 adresses at all. I share the opinion of @hkbakke in issue #2989.

**Comment by yubiuser** [comment]
This PR will stop installation of `dhcpd5`: https://github.com/pi-hole/pi-hole/pull/4260

**Comment by yubiuser** [comment]
Fixed with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
