### ISSUE TITLE
Support for WSL2?

### ISSUE THREAD

**Issue by sakshamgoyal01** [pi-hole/pi-hole#3224]
Not sure if this is already posted, but im trying tofigure out why it will not install on WSL2. is there a limitation in the way it works that it doesnt allow it to run?

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
