### ISSUE TITLE
Cant open the Clients tab to manage my Groups on new CentOS 8 Install.

### ISSUE THREAD

**Issue by floriplum** [pi-hole/pi-hole#3228]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Install Pi-hole and be able to open the clients tab in group management.`

**Actual behaviour:**

`When i open the clients tab in group management i only get the following error message: "DataTables warning: table id=clientsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
"`

**Steps to reproduce:**

`Install a fresh CentOS 8 Minimal, Update it, Install Pi-hole and upgrade to Version 5`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`5hx0kgt6vg`

**Troubleshooting undertaken, and/or other relevant information:**

`I have Selinux disabled before i tried to install Pi-hole. Because it did not work i tried to reinstall CentOS with different Profiles, sadly without luck.`

`Note that this i meant as a reduandant setup, so i have another Pi-hole with Version 5 without any Problem. The other one is installed on a Debian 10 Install.

**Comment by floriplum** [comment]
I just looked at the DataTables Request like mentioned on the link form the error message. It contains the Error message: "Error connecting to database /etc/pihole/pihole-FTL.db: Unable to open database: unable to open database file".

The file is owned by the user pihole and the group pihole, the permissions are set to 600. I also checked that pihole is running as user pihole.

**Comment by floriplum** [comment]
I just compared the permissions from my Debian box and set it to 644 on my CentOS box, it is now working as expected.

Should i leave this open since im not sure if this is a bug in the installer?

**Comment by grravity** [comment]
Ah crap, I believe this was the same issue I had. I helped someone else fix it as well over IRC.
If this is the same issue, I believe you were required to install another dependency, but I forget what it was. I believe it was some php dependency.

**Comment by bcambl** [comment]
Install `php-json` and restart `lighttpd`.  

Related to https://github.com/pi-hole/pi-hole/pull/3066

**Comment by floriplum** [comment]
Is this really needed since "fixing" the permissions did the job for me.
Are there any other things that would be broken without that dependency?

Am 27. März 2020 03:46:06 MEZ schrieb Blayne Campbell <notifications@github.com>:
>Install `php-json` and restart `lighttpd`.  
>
>Related to https://github.com/pi-hole/pi-hole/pull/3066
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pi-hole/pi-hole/issues/3228#issuecomment-604786329

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by bcambl** [comment]
I was referring to the dependency.  

File permission was fixed here: https://github.com/pi-hole/FTL/issues/586

**Comment by dschaper** [comment]
So this is resolved?

**Comment by bcambl** [comment]
> So this is resolved?

Yes.  
Both the dependency and the permission fix have been staged for next release for a very long time.

**Comment by dschaper** [comment]
So has the release! ;)

**Comment by grravity** [comment]
Am having this issue again on my server, slightly different warning, not sure what's up.

Upon going to `Group Management > Clients`, I receive a `DataTables warning: table id=clientsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

Also under `Network` I receive `An unknown error occured while loading the data.
Error connecting to database
/etc/pihole/pihole-FTL.db: Unable to open database: unable to open database file`


`php-json` is still installed, and I tried updating and restarting both `lighttpd` and the server itself. 
This occurred upon updating to Pi-hole v5.0, was working fine before. All that was done was updated PiHole.


Pi-Hole, AdminLTE, FTL Versions - Latest v5.0

Server: CentOS Linux release 8.1.1911 (Core)
