### ISSUE TITLE
2.5.2 and CHIP running debian

### ISSUE THREAD

**Issue by sanc909** [pi-hole/pi-hole#323]
Should 2.5.2 run on a CHIP running debian? I have the old version but if I try to run the installer it days there's insufficient disk space. It suggests running raspi-config...

Did I miss something?

Initating network interface                                                  Insufficient Disk space

chip@chip:~$ df -h                                                           Filesystem      Size  Used Avail Use% Mounted on                             ubi0:rootfs     3.7G  478M  3.2G  13% /                                      devtmpfs        248M     0  248M   0% /dev                                   tmpfs           248M     0  248M   0% /dev/shm                               tmpfs           248M   15M  234M   6% /run                                   tmpfs           5.0M  4.0K  5.0M   1% /run/lock                              tmpfs           248M     0  248M   0% /sys/fs/cgroup                         tmpfs            50M     0   50M   0% /run/user/1000                         chip@chip:~$

**Comment by PromoFaux** [comment]
Is this supposed to be a separate issue?

**Comment by sanc909** [comment]
Apologies it's a duplicate. I thought it hadn't gone through. Can I get this one deleted.  Thanks

**Comment by PromoFaux** [comment]
It cannot be deleted. It will just have to stay here to shame you :p

No problem!
