### ISSUE TITLE
Pihole installation failure at FTL step and whole Raspberry loses internet connectivity

### ISSUE THREAD

**Issue by kahyalar** [pi-hole/pi-hole#3233]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Installer finishes correctly

**Actual behaviour:**

root@raspberrypi:/home/pi# curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 18 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [i] Checking for dialog (will be installed)
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [i] Checking for git (will be installed)
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [i] Using interface: wlan0
  [i] Using   [✓] Set IP address to 192.168.10.111
  You may need to restart after the install is complete
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.10.111/24
  [i] IPv6 address:
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [i] Checking for dnsutils (will be installed)
  [✓] Checking for iputils-ping
  [i] Checking for lsof (will be installed)
  [i] Checking for netcat (will be installed)
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [i] Checking for idn2 (will be installed)
  [i] Checking for sqlite3 (will be installed)
  [✓] Checking for libcap2-bin
  [i] Checking for dns-root-data (will be installed)
  [i] Checking for resolvconf (will be installed)
  [✓] Checking for libcap2
  [i] Checking for lighttpd (will be installed)
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cgi (will be installed)
  [i] Checking for php-sqlite3 (will be installed)
  [✓] Enabling lighttpd service to start on reboot...
  [✓] Creating user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed

**Steps to reproduce:**

Run auto installer on a raspberry pi3 b+ with wifi connection NOT ethernet (wlan0 interface)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
@PromoFaux Haven't we fixed this? Or is it still an issue with `/etc/resolv.conf` and localhost that is set for version 5?

**Comment by PromoFaux** [comment]
It's not the detection thing that we fixed, as that is a real URL, so it must be to do with resolution of the domain.

@kahyalar if you change the file `/etc/resolv.conf` to read `nameserver 8.8.8.8` and then run `pihole -r` does `FTL` get installed?

**Comment by kahyalar** [comment]
@PromoFaux I can try it. But for that purpose should I clone to repo first and run the manual installation steps?

**Comment by PromoFaux** [comment]
No need.. as the local repo is already installed (per the above output)

**Comment by kahyalar** [comment]
Okay, I'll try and update the issue according to the results. Thanks a lot.

**Comment by kahyalar** [comment]
Hello. I tried but my output looks as the following:

```
root@raspberrypi:/home/pi# nano /etc/resolv.conf
root@raspberrypi:/home/pi# pihole -r
bash: pihole: command not found
```

**Comment by PromoFaux** [comment]
hmm, ok, try:

```
cd /etc/.pihole
sudo bash ./automated\ install/basic-install.sh
```

**Comment by kahyalar** [comment]
Thanks a lot. It successfully installed, the rest is my DNS configuration, I suppose. Excited to try!

**Comment by mackman81** [comment]
I believe this may be the same issue that happens on Ubuntu 19.04/19.10 with resolvconf.  At some point during the install, the resolv.conf file gets emptied or deleted leaving no nameservers and breaking dns, which then causes the rest of the install script to stop working.  Merely adding a nameserver back into it while the install script is waiting to restart dns will allow the install to complete.

**Comment by wanderingminstrel102** [comment]
Hi

So, what should the resolv.conf file look like, if it is working? Should it contain only one line, just

nameserver 8.8.8.8

And nothing else?

Sorry if this seems obvious, but I’m trying to learn on my Pi, and so far I’m having little success. 

Thanks in advance for any help you can give me.

**Comment by mackman81** [comment]
> Hi
> 
> 
> 
> So, what should the resolv.conf file look like, if it is working? Should it contain only one line, just
> 
> 
> 
> nameserver 8.8.8.8
> 
> 
> 
> And nothing else?
> 
> 
> 
> Sorry if this seems obvious, but I’m trying to learn on my Pi, and so far I’m having little success. 
> 
> 
> 
> Thanks in advance for any help you can give me. 

Yes, that’s all you would see in that file.

**Comment by wanderingminstrel102** [comment]
Hi again

I’ve resolved my issue, following the instructions here. My Pi-hole is up and running. Thank you PromoFaux.

**Comment by wanderingminstrel102** [comment]
mackman81,

Thank you very much for your reply. I’m am so new...I don’t even know what I don’t know.
