### ISSUE TITLE
Pi-hole DNS / FTL issue

### ISSUE THREAD

**Issue by izeox** [pi-hole/pi-hole#3234]
Hello all,

New here and have resorted to asking for help after many hours of trying to resolve my pihole issues.

I have tried to get the pi-hole install completed but I come up against an issue when it gets to the FTL download and I have looked online at various resolutions but I have had no success.

I have looked at the /etc/resolv.conf, /etc/dchpcd.conf resolutions but still no luck.

I can ping 1.1.1.1, 8.8.8.8, etc but I cannot resolve google.com

I have tried to upload a debug log but that has produced an error as well.

Any help would be greatly appreciated.

**Comment by dschaper** [comment]
Hi izeox, a better place to get assistance with issues would be https://discourse.pi-hole.net as our community can provide very quick feedback and hints.

**Comment by EroticD** [comment]
I have the exact same issue while on wireless, but not on ethernet. Debug here: t4mesuez9c.
