### ISSUE TITLE
Feature request: Trimming input when setting Upstream DNS Servers

### ISSUE THREAD

**Issue by voipmeister** [pi-hole/pi-hole#3239]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I want to use the DNS servers of DNS.watch in my Pi-hole setup. I go to the site, copy the IPv4 address of resolver #1 by double-clicking on it in the browser window, paste this in `Custom 1 (IPv4)` under Settings > DNS. Same for the second resolver. 

Changes are saved and applied, all is well and working.

**Actual behaviour:**

When adding the IPv4 addresses from https://dns.watch/index as described above the change was not accepted and failed with the error:
```
IP ( 84.200.69.80 ) is invalid!
IP ( 84.200.70.40 ) is invalid!
No DNS server has been selected.
The settings have been reset to their previous values 
```
The reason is that by copying the addresses by double-clicking, heading and trailing spaces are being copied as well. The input is not trimmed and the literal spaces are considered not to be a valid IPv4 address.

It would be nice

**Steps to reproduce:**

Go to the https://dns.watch/index site, copy the IPv4 address of resolver #1 by double-clicking on it in the browser window, paste this in `Custom 1 (IPv4)` under Settings > DNS. Same for the second resolver, check the checkboxes for those addresses and Save.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I haven't uploaded any logs since I think they are not necessary for this issue.

**Troubleshooting undertaken, and/or other relevant information:**

I took me a few minutes to figure out what was happening and this is not a serious issue, since I manually deleted the spaces, but it would be nice to trim the input before validation.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
