### ISSUE TITLE
CAMELEON hosts file is deprecated

### ISSUE THREAD

**Issue by Aeriem** [pi-hole/pi-hole#3249]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

No deprecated lists are suggested during Pi-hole's installation.

**Actual behaviour:**

On the [CAMELEON website](https://sysctl.org/cameleon/), the hosts files are listed as deprecated and no longer updated. I downloaded the UNIX format hosts file to check: `# Last updated : 2018-03-17`.
I know this list is quite reputable, but I still wanted to let you know, especially with the CNAME blocking change that's coming in Pi-hole 5.0.

**Steps to reproduce:**

1. Go to the CAMELEON website.
2. Observe that hosts files are listed as deprecated.
3. Download the hosts files.
4. Check the dates of last update are more than two years old.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I can submit a PR, should I get a green light to do so. 😄

**Comment by p1r473** [comment]
As well, hosts-file.net is deprecated
This one needed to be removed from the default installation.

**Comment by DL6ER** [comment]
@p1r473 hosts-file.net has already been removed, see #3279 #3244 #3241 #3236

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-5-beta-import-von-einstellungen/31214/5

**Comment by Aeriem** [comment]
This issue can be closed as #3287 was merged. 😄
Thanks @PromoFaux for the PR!
