### ISSUE TITLE
Add uptime -p to chronometer.sh

### ISSUE THREAD

**Issue by Hippyjake** [pi-hole/pi-hole#325]
Quick feature request:
Add simple uptime -p under the current uptime line.

Along the same lines, uptime and average load would be nice on the admin UI

I dont think this is enough to make a pull request over but I could.

``` bash
		clear
		# Displays a colorful Pi-hole logo
		toilet -f small -F gay Pi-hole
		echo "        $(ifconfig eth0 | awk '/inet addr/ {print $2}' | cut -d':' -f2)"
		echo ""
		uptime | cut -d' ' -f11-
		uptime -p
		echo "-------------------------------"
```

**Comment by dschaper** [comment]
Go ahead and do the PR, just to get it tracked in the log history, and to get you some credit as the author of the pull.

**Comment by Hippyjake** [comment]
Cool done
#328
