### ISSUE TITLE
macOS Timemachine not working - Blocked (external, NXRA)

### ISSUE THREAD

**Issue by timwegenerDE** [pi-hole/pi-hole#3258]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Reverse lookup should not be blocked: lb._dns-sd._udp.fritz.box and lb._dns-sd._udp.0.1.168.192.in-addr.arpa

**Actual behaviour:**

lb._dns-sd._udp.fritz.box and lb._dns-sd._udp.0.1.168.192.in-addr.arpa is blocked. Type: PTR, Status: Blocked (external, NXRA). Time Machine Backup is not working, when pi-hole is enabled.

**Steps to reproduce:**

Starting a macOS Time Machine Backup?

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

The reverse lookup "lb._dns-sd._udp.0.1.168.192.in-addr.arpa" looks wrong to me. It should be "1.1.168.192.in-addr.arpa" (one at the beginning) or am I wrong?

Some network details: 
Router (Local Domain Name): 192.168.1.1 (fritz.box)
NAS (Synology, with Time Machine enabled): 192.168.1.10
Conditional Forwarding enabled: with router ip and local domain name (above).
Never forward reverse lookups for private IP ranges disabled (enabled doesn't work either).
Never forward non-FQDNs disabled (enabled doesn't work either).
Use DNSSEC disabled (enabled doesn't work either).
DHCP is running on the router.
IP of pi-hole: 192.168.1.2

**Comment by timwegenerDE** [comment]
When disabling Conditional Forwarding pi hole doesn't block these two requests. I will retry creating the backup. However I don't want to loose the device names in the query log.....

**Comment by dschaper** [comment]
BOGUS is a DNSSEC response.

**Comment by dschaper** [comment]
This doesn't look like a bug, it seems to be a misconfiguration. Please visit https://discourse.pi-hole.net for community assistance.
