### ISSUE TITLE
hosts-file.net down or never exist

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#3261]
Output after `pinhole -g`
```
[i] Target: hosts-file.net (ad_servers.txt)
[✗] Status: Not found
[✗] List download failed: no cached list available
```

**Comment by pheiduck** [comment]
needs to replaced with another or removed

**Comment by DL6ER** [comment]
This has already been done in https://github.com/pi-hole/pi-hole/pull/3236

**Comment by pheiduck** [comment]
Still exist on latest pihole

**Comment by PromoFaux** [comment]
Indeed, the removal will be in the next release :)

**Comment by lancelon** [comment]
Still exists on latest PiHole :-)

**Comment by yubiuser** [comment]
@lancelon 

What do you mean? This adlist was removed with v 5.0

Where do you still see this in pihole?

**Comment by PromoFaux** [comment]
It has been removed from the installer, but it will not be removed from your existing install. That will need to be done manually. 

We could add in something to remove it - but I would rather not go down that path
