### ISSUE TITLE
Enhancement: Implement DNS benchmarking

### ISSUE THREAD

**Issue by grischard** [pi-hole/pi-hole#3262]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

Choosing the best upstream DNS server isn't really easy.

[NameBench](https://github.com/google/namebench) is (was?) a cool Google project that would determine what the fastest DNS server is based on your usage patterns.

There's also an interesting [PR to actually test CDN response times](https://github.com/google/namebench/pull/2).

Pi-hole has everything that it needs to replicate this - NameBench can easily run on a Raspberry Pi, and Pi-hole has access to all past dns queries.

**Actual behaviour:**

I just pick the DNS server where the numbers look pretty.

**Steps to reproduce:**

Picking an upstream DNS server

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not relevant

**Troubleshooting undertaken, and/or other relevant information:**

View current user choices at http://pi.hole/admin/settings.php?tab=dns

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.

**Comment by grischard** [comment]
Well that could be mentioned in the template...

**Comment by DL6ER** [comment]
> Well that could be mentioned in the template...

It is:

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by grischard** [comment]
My bad.

The friction to contributing is a bit high - creating an account etc. - so I probably won't.

**Comment by dschaper** [comment]
It's okay. `dnsmasq`/`FTL` already chooses the upstream with the best performance. No additional software is needed.
