### ISSUE TITLE
Redirection to Level3.com

### ISSUE THREAD

**Issue by dominikl** [pi-hole/pi-hole#3268]
Recently I noticed that unresolvable domain queries get redirected to level3.com. That was quite a shock moment, as I thought I had some malware on the PC. But it turned out that pihole is doing this. Sorry, but this is an absolute **No-Go**!!

**Expected behaviour:**

Name is not resolved.

**Actual behaviour:**

Redirected to suspicious level3.com search page.

**Steps to reproduce:**

Enter some gibberish domain name in browser.

**Example:**

![level3](https://user-images.githubusercontent.com/6575139/79103753-16729b80-7d65-11ea-848c-65c7a4fd52c6.png)

**Comment by darkrain-nl** [comment]
Are you sure this is not the browser using level3 as a search engine?

I cannot reproduce this at all.
And I am very curious to know how a DNS server could do something like this?

How do you know it is PiHole doing this?

**Comment by PromoFaux** [comment]
If you are using level 3  as the upstream, then this is a feature of theirs.

It's not something Pi-hole is doing.

**Comment by dominikl** [comment]
That's true, sorry, I had level3 as upstream server. I can't recall setting this deliberately. If that's the default setting, then this is honestly a pretty bad choice!

**Comment by PromoFaux** [comment]
The "default" (as in, if you just mash enter through the install screens without reading them) would be Google's 8.8.8.8/8.8.4.4

Level3 is 3rd down the list on the DNS upstream selection screen:

![image](https://user-images.githubusercontent.com/1998970/79110181-c5b56f80-7d71-11ea-895e-77126977e98d.png)

Users are also offered an opportunity on this screen to enter their own custom upstream servers, too :)

![image](https://user-images.githubusercontent.com/1998970/79110215-dcf45d00-7d71-11ea-845a-805f0cbd2aee.png)
