### ISSUE TITLE
Not all queries are passed trough the Pi-Hole

### ISSUE THREAD

**Issue by acs-ferreira** [pi-hole/pi-hole#3270]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I have 8 devices in my LAN, all connected to my home router, router DHCP disabled and DHCP being provided by the Pi-Hole. All devices are the connected to the Pi-Hole and the interface confirms that at the `/networks` tab (all devices have the "Uses Pi-Hole" check-mark) so every query (with query log enabled) should be visible and blocklists having effect.

**Actual behaviour:**

Some devices (3 ou of 8) only log queries some seconds when they connect to the WiFi (and Pi-hole). After that, no more queries for those devices, blocklists not having effect, etc.

Example here, only 3 queries logged when WiFi has been turned **ON** on the android tablet, then nothing more.
![image](https://user-images.githubusercontent.com/12234510/79136854-fc12df00-7db1-11ea-964d-00609150f074.png)

Other 5 devices (TVs, Console, Smartphone and Laptops), no problem, all queries are passed trough, visible, and blocklists are doing their work.

**Steps to reproduce:**

I don't really know, as for every device it must be necessary only connect to the WiFi. Also, as the interface show pi-Hole is in effect, i don't know how to debug this.

I've also confirmed that for every device, the DNS is the Pi-Hole IP (either by DHCP or by assigning a static IP (`192.168.1.115` in my case).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/tinfqxpxdu

**Troubleshooting undertaken, and/or other relevant information:**

- Verify that DNS is the Pi-Hole on every device
- Delete Network setting on those devices and restart over
- Verify that device "Uses Pi-Hole" on the Pi-Hole interface
- Don't really understand why only the very first queries are passed trough the pi-hole and not the others

Devices are a Smartphone (tried with mobile network disabled and enabled) a tablet with WiFi only and another smartphone with no SIM-card inserted on it (so no mobile networks involved).

**Comment by acs-ferreira** [comment]
I've setup a VPN to the same device and it works. So i believe Android is bypassing DNS network setting for some reason...

**Comment by thegouhund** [comment]
Any solution for this? Im having the exact same problem

**Comment by rdwebdesign** [comment]
We will never know what was the solution because the issue was closed by the user a few hours after it was opened.

Reading the last comment it seems the issue was on the Android OS configuration:

> So i believe Android is bypassing DNS network setting for some reason...

**Comment by mwoolweaver** [comment]
Android Private DNS is likely the culprit 

https://support.google.com/fi/answer/2819583?hl=en#zippy=%2Cprivate-dns

> Important: By default, your device uses Private DNS with all networks that can use Private DNS. We recommend keeping Private DNS turned on.

**Comment by thegouhund** [comment]
> Android Private DNS is likely the culprit
> 
> https://support.google.com/fi/answer/2819583?hl=en#zippy=%2Cprivate-dns

I have disabled both android and chrome's private dns setting
