### ISSUE TITLE
web page doesn't work

### ISSUE THREAD

**Issue by quaqquaraqua** [pi-hole/pi-hole#3272]
hi
I installed pi-hole on RPi 3 model B with OS buster lite
it works, answer to ping and I can connect wit it by SSH
but when I tried to connect by browser by address rpiaddres/admin or pi.hole/admin or pi.hole I received every time page doesn't reach

there is some configuration to enable web page?
because all options "pihole -a [options]" work properly

thanks

**Comment by angrynerd** [comment]
When you went through the installer did you select the options to install
lighttpd as well as the web interface its self?

If not then you will have to run the repair tool and install those.

**Comment by quaqquaraqua** [comment]
ok, thanks I solved it, with your solution
