### ISSUE TITLE
TSB Bank

### ISSUE THREAD

**Issue by Janasek** [pi-hole/pi-hole#3273]
Hi.

I installed Pi-Hole, started it, set it up etc ..., UK TSB Bank does not allow logging in, I turned off all the rules I deleted the pi-hole, dns etc ... still does not work

it looks like dns from pi-hole is blocked, after ip pi-hole is removed from the router everything is back to normal

**Comment by PromoFaux** [comment]
https://discourse.pi-hole.net/t/how-do-i-determine-what-domain-an-ad-is-coming-from/1522
