### ISSUE TITLE
add blocklist status

### ISSUE THREAD

**Issue by rschitz** [pi-hole/pi-hole#3278]
Hi, thanks a lot for this wonderfull project.
Some lists might not be available after some time but you don't spot it right away, i actually saw some during the update :

<img width="453" alt="image" src="https://user-images.githubusercontent.com/8385646/79477488-8eadbb00-800a-11ea-8fdd-25755cdefcb6.png">

That would be cool to have a status next to the delete button so one could remove dead links right away

<img width="994" alt="image" src="https://user-images.githubusercontent.com/8385646/79477388-7178ec80-800a-11ea-93d0-1ee33b3cc523.png">

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by DL6ER** [comment]
@rschitz Please ping me once you opened a discussion ticket on our Discourse forum. We can discuss some details before we go into evaluation what is feasible.
