### ISSUE TITLE
Hardcoded url in index path.

### ISSUE THREAD

**Issue by javixuhc** [pi-hole/pi-hole#3280]
When pihole is configured as a domain it does not load the resources well.
Shouldn't it be relative?
It only happens on the welcome page, the administration application goes perfectly.
These are the cases that include "//pi.hole/admin ..."
Shouldn't it be: "/ admin ..."?

https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/index.php#L225

https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/index.php#L226

https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/index.php#L228

In the javascript part, if this is the case, use the domain "serverName" dynamically.

https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/index.php#L313

https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/advanced/index.php#L319

**Comment by yubiuser** [comment]
Fixed already by https://github.com/pi-hole/pi-hole/pull/3263
