### ISSUE TITLE
Blacklist is case sensitive so trivial to work around

### ISSUE THREAD

**Issue by UKTekkie** [pi-hole/pi-hole#3285]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Adding youtube.com to blacklist should block all YouTube access`

**Actual behaviour:**

`While it does block youtube.com correctly, it does not block YouTube.com, youTube.com so it is trivial to work around`

**Steps to reproduce:**

`Add youtube.com to blacklist as wildcard and then enter YouTube.com into Safari on an iPad - the domain is not blocked. `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

``

**Troubleshooting undertaken, and/or other relevant information:**

`Note internet domain names are NOT case sensitive but most browsers perform a DNS lookup of the hostname as entered by the user - they do not force lower case. Pi hole should therefore perform a case insensitive comparison for whitelist and blacklist domains. `

**Comment by hiyan** [comment]
Not sure how you're getting that results.

My test show matching is not case sensitve.

```
12:09:53: query[A] RoaMIng.OFficEAPps.LIVe.com from 127.0.0.1
12:09:53: exactly blacklisted RoaMIng.OFficEAPps.LIVe.com is 0.0.0.0
12:09:55: query[A] roaming.officeapps.live.com from 127.0.0.1
12:09:55: exactly blacklisted roaming.officeapps.live.com is 0.0.0.0
```

**Comment by DL6ER** [comment]
> Note internet domain names are NOT case sensitive but most browsers perform a DNS lookup of the hostname as entered by the user

We are well aware of this.

Am I right that you try to block youtube using a regex filter? Note that, despite domains NOT being case sensitive, regular expressions are, in fact.

If my assumption is correct, you might want to use
```
REGEX_IGNORECASE=true
```
in `/etc/pihole/pihole-FTL.conf` and restart FTL using `pihole restartdns`.
I'm not entirely sure this option is already available with Pi-hole v4.x or only with v5.0 but maybe you're already on the beta - hard to say without a debug token.

@dschaper @promofaux How about making case insensitivity the default behavior in FTL for regex? Is there anything speaking against this (it could still be disabled using `REGEX_IGNORECASE=false`)?

**Comment by PromoFaux** [comment]
Does casing matter in a domain name anyway?

if I browse to: `google.com` or `Google.com` or `gOogle.com`, it sends me to Google. AFAIK, case only matters for everything after the domain (i.e `/ApiEndpoint.aspx`)

If I register `promofaux.com`, I would not expect to also register all variants of that...

So, I would say that the regex should ignore case by default (and not even be configurable)

**Comment by dschaper** [comment]
> Does casing matter in a domain name anyway?

No, not at all (as far as FQDN to IP)

> if I browse to: `google.com` or `Google.com` or `gOogle.com`, it sends me to Google.

Yes, however the case sent to a resolver is supposed to be identical to the case returned. This is a consistency check and a very crude way to check if queries are being intercepted. See https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00#section-5.1

> So, I would say that the regex should ignore case by default (and not even be configurable)

Agree but the case should be preserved and returned to the client as requested. (Or we just say that caps_for_id is not supported.)

**Comment by UKTekkie** [comment]
Thanks all and sorry for slow response. 

I agree with above comments. Case should not matter in domain names and I would suggest Pi Hole should always use cases insensitive comparisons, even for wildcards and regular expressions. I added domains as wildcards, hence I saw the problem. 

I hadn’t reviewed the documentation thoroughly but would suggest REGEX_IGNORECASE=true should be the default. I can’t see that it would ever be useful to set it to false, as that enables this simple workaround. 

If this means the current implementation forces the domain name to lower case before performing the DNS query that shouldn’t pose any problem (you may argue it should always use the same case as in the original incoming DNS query but I see no benefit).

**Comment by dschaper** [comment]
https://github.com/pi-hole/FTL/pull/732 resolves the issue.

**Comment by yubiuser** [comment]
The linked PR is merged to master for a long time now
