### ISSUE TITLE
Deleted dhcp.leases need file

### ISSUE THREAD

**Issue by Thomas499** [pi-hole/pi-hole#3288]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

I added a static dhcp but noticed that the currently active dhcp leases didn't update accordingly. So I went to /etc/pihole/dhcp.leases and manually deleted everything in that file thinking it would force a refresh of the active dhcp leases. Well turns out that was a bad idea now the pihole says Lost connection to api, and dns not running. If I go into putty and do pihole -up this is what it says 

![image](https://user-images.githubusercontent.com/38442058/79805320-b490d380-831a-11ea-80b6-3ac7fec0e398.png)

I think if I manually add whatever I need for the lease for the raspberry pi ill be back in business. But I don't know what format it needs to be in. Can someone attach their dhcp.leases file so I can see what format I need to enter back into the file to get the pihole operational again? 

I tried following the steps listed here https://www.reddit.com/r/pihole/comments/8lwsaj/flush_dhcp_server_leases/ but it says 
![image](https://user-images.githubusercontent.com/38442058/79805788-c58e1480-831b-11ea-9a00-11b1f2a6a3e6.png)

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`
delete /etc/pihole/dhcp.leases 
[pihole_debug.log](https://github.com/pi-hole/pi-hole/files/4506614/pihole_debug.log)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/issues/1026

**Comment by yubiuser** [comment]
This should be solved with https://github.com/pi-hole/AdminLTE/issues/1026 and has been released by
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909
