### ISSUE TITLE
dnsmasq.d/01-pihole.conf keeps getting modified

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#3292]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

dnsmasq.d/01-pihole.conf should not be modified randomly

**Actual behaviour:**

dnsmasq.d/01-pihole.conf keeps getting modified
specifically: the following line keeps getting removed. 
```
bind-interfaces
 ```
I need this line in as I am binding to 127.0.0.1 instead of the default 0.0.0.0. 

Without this line, PiHole tries to bind to 0.0.0.0 (I do not want this as I have something else running on 127.0.0.2#53 so Pihole must be on 127.0.0.1#53 and not 0.0.0.0#53 so the port binds don't conflict)

Without that first line, this following second line doesn't work. Note that this second line  does not disappear, only the first line does, (https://discourse.pi-hole.net/t/make-pihole-ftl-bind-only-on-certain-ips-v4-0/11883/5):
```
listen-address=127.0.0.1
```
Does anyone know why/where keeps modifying my 01-pihole.conf and removing bind-interfaces?

**Steps to reproduce:**

I am unsure how often this line is being removed, but it seems to be after some restarts

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/wcn04q5l5q

**Troubleshooting undertaken, and/or other relevant information:**

I have no clue what keeps modifying this file. For now I have run the following so this line cannot be removed. I don't know if this will affect the trust anchor (does that need to be cycled?)
```
chattr +i /etc/dnsmasq.d/01-pihole.conf
```

**Comment by technicalpyro** [comment]
if you want a configuration change to be kept through updates et al put it in its own config file something like `/etc/dnsmasq.d/99-custom.conf`

**Comment by p1r473** [comment]
Thanks, I put my changes in /etc/dnsmasq.d/02-custom.conf and I'll see if it works!

**Comment by DL6ER** [comment]
> Does anyone know why/where keeps modifying my 01-pihole.conf and removing bind-interfaces?

Whenever you change config settings, either through the web interface out by using a `pihole` CLI command for it (only a few CLI command actually trigger a rewrite).
