### ISSUE TITLE
Feature: support wildcards for Custom DNS

### ISSUE THREAD

**Issue by alexiri** [pi-hole/pi-hole#3298]
It would be great if the v5 Custom DNS feature supported wildcard subdomains. This would allow the user to configure a single entry to rewrite multiple subdomains, something like:

```
192.168.1.1 *.me.dyndns.com
```

Currently, the web interface complains that it's not a valid domain. Adding an entry like that manually to `/etc/pihole/custom.list` also doesn't make it work.

**Comment by jimmcslim** [comment]
I'd also love this.

I'm also wondering if it would be possible for the resolved address be set as a client name, rather than an IP address, for when I'm testing a bunch of microservices on my dev laptop.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by scobby** [comment]
I would also love this! currently i use cloudflare for this, but local network wildcard resolve would be nice! Especially for docker and traefik.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
