### ISSUE TITLE
Apply to be part of GitHub's official Sponsors program

### ISSUE THREAD

**Issue by jankais3r** [pi-hole/pi-hole#3300]
It would give people another way how to financially contribute to the development of pi-hole.

**Comment by dschaper** [comment]
Been on the waitlist for a while, since the day that applying as an organization/team was announced.

**Comment by jankais3r** [comment]
I see that it is now possible to sponsor directly on GitHub. Closing the issue.

**Comment by dschaper** [comment]
Thank you for your sponsorship!
