### ISSUE TITLE
Install [multiple] fails  on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by lancelon** [pi-hole/pi-hole#3301]
**Fail No1**: curl -sSL https://install.pi-hole.net | bash
Fails due to the logged in user not being root 
**Solution**:  curl -sSL https://install.pi-hole.net | sudo bash

**Fail No2**: 
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabi not found
  [✗] FTL Engine not installed

**Fail No3**: After the install fails at one of the last hurdles, you're then unable to ping any other websites due to the resolv and DNS settings being set to 127.0.0.1
**Solution**: Edit the DNS manually in sudo nano /etc/dhcpcd.conf then _**full reinstall**_, this time everything works as it should

**Comment by dschaper** [comment]
`curl -sSL https://install.pi-hole.net | bash` is all you need. You will be prompted for your `sudo` password when required.

**Comment by lancelon** [comment]
Thanks dschaper - are the other two fails worth looking into still? I had a Google yesterday and they seem to be happening quite a bit to others. :)
