### ISSUE TITLE
Pi-Hole forwards it's hostname upstream when queried with local domain suffix

### ISSUE THREAD

**Issue by mill1000** [pi-hole/pi-hole#3303]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`2`

---
**Expected behaviour:**

Pi-Hole resolves it's hostname with local domain to it's IP address.

**Actual behaviour:**

Pi-Hole forwards it's hostname upstream when queried with local domain.

**Steps to reproduce:**

1. Configure Pi-Hole as DHCP server for local network.
2. Set domain name to something. Say `lan`.
3. Query for `<pi-hole hostname>.lan` and see the response come from upstream. 
e.g.
```
dig <pi-hole hostname>.lan
...
;; AUTHORITY SECTION:
.                       9015    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2020042702 1800 900 604800 86400
```
**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/zt090cnr1i`

**Troubleshooting undertaken, and/or other relevant information:**

I've tested name resolution of other hosts with and without the domain and they all resolve correctly.

Adding an entry to `/etc/pihole/local.list` seems like an easy fix. Perhaps `gravity.sh` can be updated to include the hostname+domain here:
https://github.com/pi-hole/pi-hole/blob/9e490775ff3b20f378acc9db7cec2ae6023fff7f/gravity.sh#L519

**Comment by dschaper** [comment]
Check Settings -> DNS -> Advanced DNS Setttings

![Screenshot_2020-04-27 Pi-hole Admin Console](https://user-images.githubusercontent.com/2782850/80439533-99463b00-88bb-11ea-80d4-b6644c9f6405.png)

**Comment by mill1000** [comment]
Yes both are checked.

**Comment by dschaper** [comment]
Hmm, and it's getting past stubby?

**Comment by dschaper** [comment]
@DL6ER Can you check the debug log? DHCP server is enabled and `domain=lan` so `dnsmasq/pihole-FTL` shouldn't be trying to query for records it owns?

**Comment by dschaper** [comment]
`dig <hostname>.lan @192.168.1.4` shows a remote SOA? Can you paste the full output from that command, with your redactions for things you'd like to keep private. And a full `dig` without the server `@`. I think the client doing the `dig` in your post may not be using Pi-hole for it's DNS server.

**Comment by DL6ER** [comment]
We're just exploring a `dnsmasq` bug (not fixed by the most recent v2.81) where the no-recursion bug isn't honored. Whenever `dnsmasq` fails to serve a request locally, it resorts to asking the upstream. https://github.com/pi-hole/FTL/issues/738

We're still exploring this.

**Comment by mill1000** [comment]
Pretty confident the system is querying the Pi-Hole at 192.168.1.4. I know the other local hostnames resolve OK with and without the `.lan` suffix.

```
dig rockhole.lan@192.168.1.4

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> rockhole.lan@192.168.1.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7175
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;rockhole.lan\@192.168.1.4.     IN      A

;; AUTHORITY SECTION:
.                       86400   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2020042702 1800 900 604800 86400

;; Query time: 112 msec
;; SERVER: 192.168.1.4#53(192.168.1.4)
;; WHEN: Mon Apr 27 20:43:40 DST 2020
;; MSG SIZE  rcvd: 128
```

```
dig rockhole.lan

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> rockhole.lan
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6903
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rockhole.lan.                  IN      A

;; Query time: 3 msec
;; SERVER: 192.168.1.4#53(192.168.1.4)
;; WHEN: Mon Apr 27 20:45:35 DST 2020
;; MSG SIZE  rcvd: 41
```

**Comment by dschaper** [comment]
`dig rockhole.lan @192.168.1.4` not `dig rockhole.lan@192.168.1.4` (Space between domain name and `@` symbol.)

**Comment by mill1000** [comment]
For reference here's a dig without the domain name.
```
dig rockhole

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> rockhole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24176
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rockhole.                      IN      A

;; ANSWER SECTION:
rockhole.               2       IN      A       192.168.1.4

;; Query time: 3 msec
;; SERVER: 192.168.1.4#53(192.168.1.4)
;; WHEN: Mon Apr 27 20:47:57 DST 2020
;; MSG SIZE  rcvd: 53
```

Here's a snippet of pihole.log after a `pihole restartdns` and attempting to resolve the device.
```
Apr 27 20:48:28 dnsmasq-dhcp[20269]: DHCP, IP range 192.168.1.100 -- 192.168.1.251, lease time 1d
Apr 27 20:48:28 dnsmasq[20269]: using local addresses only for domain use-application-dns.net
Apr 27 20:48:28 dnsmasq[20269]: using nameserver 127.0.0.1#53000
Apr 27 20:48:28 dnsmasq[20269]: read /etc/hosts - 6 addresses
Apr 27 20:48:28 dnsmasq[20269]: read /etc/pihole/local.list - 2 addresses
Apr 27 20:48:28 dnsmasq[20269]: failed to load names from /etc/pihole/black.list: No such file or directory
Apr 27 20:48:28 dnsmasq[20269]: read /etc/pihole/gravity.list - 92229 addresses
Apr 27 20:48:36 dnsmasq[20269]: query[A] rockhole.lan from 192.168.1.104
Apr 27 20:48:36 dnsmasq[20269]: forwarded rockhole.lan to 127.0.0.1
Apr 27 20:48:36 dnsmasq[20269]: reply rockhole.lan is NXDOMAIN
Apr 27 20:48:38 dnsmasq[20269]: query[A] rockhole from 192.168.1.104
Apr 27 20:48:38 dnsmasq[20269]: /etc/pihole/local.list rockhole is 192.168.1.4
Apr 27 20:48:43 dnsmasq[20269]: query[A] stereoberry.lan from 192.168.1.104
Apr 27 20:48:43 dnsmasq[20269]: DHCP stereoberry.lan is 192.168.1.3
```

I am confused by this line from the log ` using local addresses only for domain use-application-dns.net`

**Comment by mill1000** [comment]
Ah apologies. Here's the full dig with the proper command.

```
dig rockhole.lan @192.168.1.4

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> rockhole.lan @192.168.1.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39428
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rockhole.lan.                  IN      A

;; Query time: 3 msec
;; SERVER: 192.168.1.4#53(192.168.1.4)
;; WHEN: Mon Apr 27 20:50:54 DST 2020
;; MSG SIZE  rcvd: 41
```

**Comment by dschaper** [comment]
`dig rockhole.lan` to `192.168.1.4` is NXDOMAIN, it's not forwarded.
`dig rockhole` to `192.168.1.4` is NOERROR, so that's good.
`dig rockhole.lan @192.168.1.4`, the best test, specifically says the Pi-hole is not forwarding that query, it's NXDOMAIN.

So it looks like Pi-hole is not forwarding your internal domain `.lan`. But it's also not resolving the local client FQDNs.

**Comment by dschaper** [comment]
Okay, so it does look like it's getting to `stubby`.

```plain
Apr 27 20:48:36 dnsmasq[20269]: forwarded rockhole.lan to 127.0.0.1
Apr 27 20:48:36 dnsmasq[20269]: reply rockhole.lan is NXDOMAIN
```

**Comment by dschaper** [comment]
And DHCP is operating correctly:

```plain
Apr 27 20:48:43 dnsmasq[20269]: query[A] stereoberry.lan from 192.168.1.104
Apr 27 20:48:43 dnsmasq[20269]: DHCP stereoberry.lan is 192.168.1.3
```

Looks like `rockhole` just doesn't exist in the DHCP leases and it is pushing out to `stubby` as it can't find the answer in the DHCP lease. May be the bug that DL mentions.

**Comment by dschaper** [comment]
> I am confused by this line from the log ` using local addresses only for domain use-application-dns.net`

That's the FireFox DoH canary domain, the domain `use-application-dns.net` is a way for FireFox to know if it should enable DoH or if the network administrator does not want that to happen.

**Comment by mill1000** [comment]
Oh I see I've been misinterpreting the AUTHORITY SECTION. Whoops.

Yes, `rockhole` is the hostname of the system running Pi-Hole and is statically configured.

**Comment by DL6ER** [comment]
Some preliminary code investigation results suggest that, if "never forward non-FQDNs" is ticked, domains without a `.` should never be forwarded anywhere *except* one of the following is configured with this domain: `server, local, address, rebind-domain-ok`. This seems to be okay.

However, the local domain `.lan` doesn't seem to get used for checking if a query is to be sent upstream. It's used in a number of places (even more when `expand-hosts` is set).
The reseach would go too deep into the guts to be feasible now.

I suggest writing an email to dnsmasq-discuss@lists.thekelleys.org.uk
saying the relevant config lines are:
```
   domain-needed
   bogus-priv
   dhcp-authoritative
   dhcp-range=192.168.1.100,192.168.1.251,24h
   dhcp-option=option:router,192.168.1.1
   dhcp-leasefile=/etc/pihole/dhcp.leases
   domain=lan
```

**Comment by mill1000** [comment]
I attempted to send an email but it was rejected as I am not allowed to post to the mailing list.

**Comment by yubiuser** [comment]
"To control spam, only subscribers are allowed to post to the list."

You have to subscribe first: http://lists.thekelleys.org.uk/mailman/listinfo/dnsmasq-discuss

**Comment by jacklul** [comment]
I think `domain=lan` should be used together with `local=/lan/` - this should prevent all local queries from being forwarded as well as any hostname without a domain (for example one word searches from the address bar in browsers).

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/issues/3303#issuecomment-620355957

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/custom-list-is-not-taken-into-account/36345/7

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/custom-list-is-not-taken-into-account/36345/11

**Comment by Asharas** [comment]
> I think `domain=lan` should be used together with `local=/lan/` as well as `expand-hosts` for best privacy - this should prevent all local queries from being forwarded (will show up as blocked by regex) as well as any hostname without a domain (for example one word searches from the address bar in browsers).
> 
> [Source](https://wiki.archlinux.org/index.php/dnsmasq#Adding_a_custom_domain) and many threads on Discourse

Yup, works as expected by adding `local=/lan.domain.tld/` to  dnsmasq configuration (aswell as setting it in pihole to have the domain directive set to the same value).
