### ISSUE TITLE
Manage blacklist for certain clients

### ISSUE THREAD

**Issue by wskkerbborsch** [pi-hole/pi-hole#3305]
**In raising this issue, I confirm the following**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

3

---
**Expected behaviour:**

I request a possibilty to manage blacklist entries for certain clients. For example I would like to block certain websites to specific client managed by pihole. Example: Block "example.site" to my children's mobile device.
The client can be recognized either via a static IP or by a hostname (in worst case set in pihole's `/etc/hosts` file. This would act like a kind of family/parental control. Im sure other's would love this feature also :)

**Actual behaviour:**

No possiblity available.

**Comment by yubiuser** [comment]
This will be one of the key feature for the upcoming pihole v5.0.

https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/#page-content

**Comment by yubiuser** [comment]
P.S. There is a dedicated 'feature request' forum:
https://discourse.pi-hole.net/c/feature-requests/8

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
