### ISSUE TITLE
Feature: support CNAMEs in Pi-Hole 5's Local DNS Records Web GUI.

### ISSUE THREAD

**Issue by monkeyhybrid** [pi-hole/pi-hole#3308]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

It would be nice if the new _Local DNS Records_ feature in Pi-Hole 5 allowed users to add CNAME records from within the GUI.

**Actual behaviour:**

No CNAME support from within the GUI.

**Steps to reproduce:**

Go to the _Local DNS Records_ page in the Web GUI and note lack of CNAME support.

**More information:**

First off, I'm really liking my short time with Pi-Hole so far. I installed version 4 a couple of days ago, liked what I saw, but thought it was bit of a shame not having GUI access for creating local DNS records. Then I upgraded to version 5 beta, and I see the GUI now provides the ability to add custom A records, for mapping domains to IPs. Awesome! Great work devs!

However, I'm sure I'm not the only user who likes to also use CNAMEs on their home network to map user friendly domains to less friendly but more infrastructure organised internal names. For example, I might map `git.mydomain.tld` to things like `git-vm-20200215.mydomain.tld` so that I can swap between VMs with unique hostnames whilst all clients just carry on using `git.mydomain.tld` like nothing is different.

I am aware I could achieve the same end result with A records, but CNAMEs allows me to use DHCP on the VMs, with no need to be aware of any IPs. Lovely!

Is this something that other users would like to see? Are there any plans to implement CNAMEs in the _Local DNS Records_ page?

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by monkeyhybrid** [comment]
Ooops, sorry about that. I will do that first thing in the morning. Thanks for letting me know. Cheers!

**Comment by dschaper** [comment]
Thanks!
