### ISSUE TITLE
PiHole setup does not check neccesary PHP 7.4 modules before install

### ISSUE THREAD

**Issue by castillo92** [pi-hole/pi-hole#3313]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1 of 10

---
**Expected behaviour:**

Pi-Hole setup should check if  php-7.4-sqlite3  was installed.

**Actual behaviour:**

I did a fresh install: install Debian 10, then Apache, PHP 7.4, MariaDB, and some dependencies with a template I made and finally Pi-Hole. I did not install php7.4-sqlite3 because I did not know it was necessary.

**Steps to reproduce:**

Make a fresh install without php7.4-sqlite3 dependency and check you can not see long term statistics.

**Troubleshooting undertaken, and/or other relevant information:**

Following some post of the community I did some checks, and finally setup php-7.4-sqlite3. I would show my terminal to help future people to find the solution:

Checking the right user:group and permission of the pihole-FTL.db:
```
castillo@srv-01:~$ ls -al /etc/pihole/pihole-FTL.db
-rw-r--r-- 1 pihole pihole 46084096 may  1 02:24 /etc/pihole/pihole-FTL.db

castillo@srv-01:~$ stat /etc/pihole/pihole-FTL.db
  Fichero: /etc/pihole/pihole-FTL.db
  Tamaño: 46084096  	Bloques: 90016      Bloque E/S: 4096   fichero regular
Dispositivo: 812h/2066d	Nodo-i: 4337736     Enlaces: 1
Acceso: (0644/-rw-r--r--)  Uid: (  998/  pihole)   Gid: (  998/  pihole)
      Acceso: 2020-05-01 02:25:00.144422714 +0200
Modificación: 2020-05-01 02:25:00.156422829 +0200
      Cambio: 2020-05-01 02:25:00.156422829 +0200
    Creación: -

```

Checking if module php-7.4-sqlite3 exist: there are no "sqlite3.ini"
```
castillo@srv-01:~$ ls /etc/php/7.0/mods-available
igbinary.ini  imagick.ini  memcache.ini  redis.ini
castillo@srv-01:~$ ls /etc/php/7.4/mods-available
bz2.ini       exif.ini      gettext.ini   intl.ini      mysqlnd.ini    posix.ini     simplexml.ini  tidy.ini       xmlwriter.ini
calendar.ini  ffi.ini       iconv.ini     json.ini      opcache.ini    pspell.ini    sockets.ini    tokenizer.ini  xsl.ini
ctype.ini     fileinfo.ini  igbinary.ini  mbstring.ini  pdo.ini        readline.ini  sysvmsg.ini    xml.ini        zip.ini
curl.ini      ftp.ini       imagick.ini   memcache.ini  pdo_mysql.ini  redis.ini     sysvsem.ini    xmlreader.ini
dom.ini       gd.ini        imap.ini      mysqli.ini    phar.ini       shmop.ini     sysvshm.ini    xmlrpc.ini
```

Installing php7.4-sqlite3
```
castillo@srv-01:~$ sudo apt-get install php7.4-sqlite3
[sudo] password for castillo: 
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes NUEVOS:
  php7.4-sqlite3
0 actualizados, 1 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 26,9 kB de archivos.
Se utilizarán 127 kB de espacio de disco adicional después de esta operación.
Des:1 https://packages.sury.org/php buster/main amd64 php7.4-sqlite3 amd64 7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0 [26,9 kB]
Descargados 26,9 kB en 0s (275 kB/s)       
Seleccionando el paquete php7.4-sqlite3 previamente no seleccionado.
(Leyendo la base de datos ... 171045 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../php7.4-sqlite3_7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0_amd64.deb ...
Desempaquetando php7.4-sqlite3 (7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0) ...
Configurando php7.4-sqlite3 (7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0) ...

Creating config file /etc/php/7.4/mods-available/sqlite3.ini with new version

Creating config file /etc/php/7.4/mods-available/pdo_sqlite.ini with new version
Procesando disparadores para php7.4-fpm (7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0) ...
NOTICE: Not enabling PHP 7.4 FPM by default.
NOTICE: To enable PHP 7.4 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.4-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Procesando disparadores para libapache2-mod-php7.4 (7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0) ...
Procesando disparadores para php7.4-cli (7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0) ...
```

Checking if module was present. Now yes.
```
castillo@srv-01:~$ ls /etc/php/7.4/mods-available
bz2.ini       exif.ini      gettext.ini   intl.ini      mysqlnd.ini     phar.ini      shmop.ini      sysvsem.ini    xmlreader.ini
calendar.ini  ffi.ini       iconv.ini     json.ini      opcache.ini     posix.ini     simplexml.ini  sysvshm.ini    xmlrpc.ini
ctype.ini     fileinfo.ini  igbinary.ini  mbstring.ini  pdo.ini         pspell.ini    sockets.ini    tidy.ini       xmlwriter.ini
curl.ini      ftp.ini       imagick.ini   memcache.ini  pdo_mysql.ini   readline.ini  **sqlite3.ini**    tokenizer.ini  xsl.ini
dom.ini       gd.ini        imap.ini      mysqli.ini    pdo_sqlite.ini  redis.ini     sysvmsg.ini    xml.ini        zip.ini
```
Enabling modules and restarting Apache:
```
castillo@srv-01:~$ sudo phpenmod sqlite3
castillo@srv-01:~$ sudo a2enconf php7.4-fpm
Conf php7.4-fpm already enabled
castillo@srv-01:~$ sudo systemctl restart apache2
```

Finally we can saw Long term data.

I saw in the setup of Pi-hole that the check exist, but I think it is not working

I copied the log from [this post](https://github.com/pi-hole/pi-hole/issues/3047), not mine
```
  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

.
.
.


  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

.
.
.

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  **[✓] Checking for sqlite3**
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for libcap2
  [i] Checking for lighttpd (will be installed)
  [✓] Checking for php7.3-common
  [i] Checking for php7.3-cgi (will be installed)
  [i] Checking for php7.3-sqlite3 (will be installed)
  [✓] Enabling lighttpd service to start on reboot...

```

**Comment by yubiuser** [comment]
Not sure, but might be a related issue
https://github.com/pi-hole/pi-hole/pull/3204

**Comment by castillo92** [comment]
> Not sure, but might be a related issue
> #3204

Yes, my issue could come from there

**Comment by dschaper** [comment]
We install with `lighttpd` as the webserver and set up the dependencies to work with that package. It looks like you are using Apache instead and would need to adjust your template to install the needed packages and versions for Apache to work correctly.

**Comment by castillo92** [comment]
> We install with `lighttpd` as the webserver and set up the dependencies to work with that package. It looks like you are using Apache instead and would need to adjust your template to install the needed packages and versions for Apache to work correctly.

Yes, and I did those adjustments, but I think it could be better if make the right checking when users do not choose “lighttpd”

**Comment by dschaper** [comment]
I think that when `lighttpd` is not installed then we shouldn't be doing anything with `php` at all. It shouldn't be a dependency if there's no reason for it.

**Comment by castillo92** [comment]
> I think that when `lighttpd` is not installed then we shouldn't be doing anything with `php` at all. It shouldn't be a dependency if there's no reason for it.

I understand that it is not neccesary for `lighttpd`, but yes for `Pi-Hole: Long term data`, so it is necessary to the normal operation of the package itself. If the installer do not check it, Pi-Hole will not work at 100%.

I have used Pi-Hole for more than 2 years and Long Term Data never worked for lack of that package, I did not know it, because logs are always right, so please, consider at least displaying a warning in the installation process if this package are no present.

**Comment by dschaper** [comment]
What my argument is:

The database is there, you showed it and it has data:

```plain
castillo@srv-01:~$ ls -al /etc/pihole/pihole-FTL.db
-rw-r--r-- 1 pihole pihole 46084096 may  1 02:24 /etc/pihole/pihole-FTL.db
```

Long term data works, or we'd hear about it from everyone. What is missing is your ability to see the data with Apache. That's not a supported webserver and an issue you need to fix with your template. 

My argument is:

If we don't install a webserver then we don't install webserver dependencies like php.

**Comment by castillo92** [comment]
> What my argument is:
> 
> The database is there, you showed it and it has data:
> 
> ```
> castillo@srv-01:~$ ls -al /etc/pihole/pihole-FTL.db
> -rw-r--r-- 1 pihole pihole 46084096 may  1 02:24 /etc/pihole/pihole-FTL.db
> ```
> 
> Long term data works, or we'd hear about it from everyone. What is missing is your ability to see the data with Apache. That's not a supported webserver and an issue you need to fix with your template.
> 
> My argument is:
> 
> If we don't install a webserver then we don't install webserver dependencies like php.

Yes, I understand perfectly your point so I am going to close the issue, but I still think the setup should detect lack of some critical dependencies.

Thanks you for your explanations and time spent. =)

**Comment by MichaIng** [comment]
@castillo92 
I was thinking about the same as well. If one selects to install the web UI, but de-selects the webserver, the PHP modules are still required of course but only a custom webserver (integration) is wanted. On the other hand, if one installed a webserver manually already, it might be possible that PHP was not installed the regular via package manager, but e.g. as source build. So the decision was to better not deal with the whole webserver stack, including PHP then. However a have a PR open to at least inform the user that PHP modules need to be installed manually as well: #3225
I'll take care this PR the next days (resolve conflicts) and hope this partly solves your issue.

I was thinking about automated PHP module detection as well, but there is no failsafe way to check for it. `php -m` lists installed modules for the default PHP instance, IF PHP-CLI is installed. But multiple PHP versions are possible and it depends on the webserver config which one is used via which handler (cgi/fpm/mod-php). If the webserver is installed manually, there is no reliable way to know which PHP version it uses, hence I think indeed for now a simple information is best and leave setup to user.

Finally, to user could be asked whether PHP should be installed + required modules from package manager, similar to how it is asked about the webserver, but I fear that too much prompts make the whole install too complicated/annoying 🤔.

**Comment by castillo92** [comment]
> @castillo92
> I was thinking about the same as well. If one selects to install the web UI, but de-selects the webserver, the PHP modules are still required of course but only a custom webserver (integration) is wanted. On the other hand, if one installed a webserver manually already, it might be possible that PHP was not installed the regular via package manager, but e.g. as source build. So the decision was to better not deal with the whole webserver stack, including PHP then. However a have a PR open to at least inform the user that PHP modules need to be installed manually as well: #3225
> I'll take care this PR the next days (resolve conflicts) and hope this partly solves your issue.
> 
> I was thinking about automated PHP module detection as well, but there is no failsafe way to check for it. `php -m` lists installed modules for the default PHP instance, IF PHP-CLI is installed. But multiple PHP versions are possible and it depends on the webserver config which one is used via which handler (cgi/fpm/mod-php). If the webserver is installed manually, there is no reliable way to know which PHP version it uses, hence I think indeed for now a simple information is best and leave setup to user.
> 
> Finally, to user could be asked whether PHP should be installed + required modules from package manager, similar to how it is asked about the webserver, but I fear that too much prompts make the whole install too complicated/annoying 🤔.

I couldn't say it better
