### ISSUE TITLE
Latency issue to Discord Voice/Live streaming servers

### ISSUE THREAD

**Issue by Jayden000** [pi-hole/pi-hole#3319]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [Maybe] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Latency not to be 50MS plus just using pi-hole

**Actual behaviour:**

Should only add a small amount of latency using pihole, 
![image](https://user-images.githubusercontent.com/23621862/81463578-7e5faa80-9188-11ea-9744-4f263cc1e08a.png)

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/g4kgbmjfkk 

**Troubleshooting undertaken, and/or other relevant information:**

I have disabled all gravity lists, changed DNS servers and I am not sure what else to do to attempt to fix my issue..

Summary of Whole Problem, when using pihole the latency to Discord voice/live share servers go through the roof and takes ages to connect to a Discord voice channel. But when using the same DNS server that pihole uses on my device the Discord call connects instantly.

The command I ran: `dig us-central56.discord.media`

**Comment by Jayden000** [comment]
Keep in mind in that dig screenshot, the local dns localhost:53 is using 1.1.1.1 as its upstream server

**Comment by dschaper** [comment]
Latency is not caused by DNS. 

What you may be seeing is that you are being geolocated to a server that is more distant to you. But there's nothing a DNS server can do to make a connection more or less latent.

**Comment by Jayden000** [comment]
> 
> 
> Latency is not caused by DNS.
> 
> What you may be seeing is that you are being geolocated to a server that is more distant to you. But there's nothing a DNS server can do to make a connection more or less latent.

That makes 0 sense, apparently you don't know how to read dig output. I am using the same upstream DNS server with both the pihole and just normally. Something is obviously making more latency in pihole.

**Comment by SmallEngineMechanic** [comment]
> Latency is not caused by DNS.
> 
> What you may be seeing is that you are being geolocated to a server that is more distant to you. But there's nothing a DNS server can do to make a connection more or less latent.

Sorry but you must not be seeing how he is digging this, he is digging to 1.1.1.1 on the DNS server, then digging using the pihole FTL , you clearly don't know how to read dig outputs

**Comment by dschaper** [comment]
Excuse me? `dig` means nothing for latency. 

Try `dig us-central56.discord.media @127.0.0.1` on the Pi-hole terminal. Note the `query time`, which means absolutely nothing as far as your latency. Then do it a second time and note the `query time`. 

But please, tell me how I know nothing about how to read a `dig`.

**Comment by Jayden000** [comment]
> 
> 
> Excuse me? `dig` means nothing for latency.
> 
> Try `dig us-central56.discord.media @127.0.0.1` on the Pi-hole terminal. Note the `query time`, which means absolutely nothing as far as your latency. Then do it a second time and note the `query time`.
> 
> But please, tell me how I know nothing about how to read a `dig`.

thing is I was running those on the pihole terminal, but let me do those two things.

![image](https://user-images.githubusercontent.com/23621862/81463985-14490480-918c-11ea-8612-a01952a10692.png)

**Comment by Jayden000** [comment]
Also my apologies for saying you don't know how to read dig

**Comment by dschaper** [comment]
Something has modified the Pi-hole installation. You need to check if you are actually using `FTL`.

`dig version.bind txt chaos @127.0.0.1`

**Comment by SmallEngineMechanic** [comment]
> Excuse me? `dig` means nothing for latency.
> 
> Try `dig us-central56.discord.media @127.0.0.1` on the Pi-hole terminal. Note the `query time`, which means absolutely nothing as far as your latency. Then do it a second time and note the `query time`.
> 
> But please, tell me how I know nothing about how to read a `dig`.

Sorry bout that

**Comment by Jayden000** [comment]
> 
> 
> Something has modified the Pi-hole installation. You need to check if you are actually using `FTL`.
> 
> `dig version.bind txt chaos @127.0.0.1`

![image](https://user-images.githubusercontent.com/23621862/81464151-0ba4fe00-918d-11ea-9b74-002cda5e08f3.png)

**Comment by dschaper** [comment]
Your queries are being forced to tcp instead of udp. And nothing is caching. 

In a normally functioning configuration the initial lookup will take longer than subsequent lookups:

```plain
dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14626
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;us-central56.discord.media.    IN      A

;; ANSWER SECTION:
us-central56.discord.media. 300 IN      A       162.159.138.234
us-central56.discord.media. 300 IN      A       162.159.129.235
us-central56.discord.media. 300 IN      A       162.159.128.235
us-central56.discord.media. 300 IN      A       162.159.130.235
us-central56.discord.media. 300 IN      A       162.159.137.234

;; Query time: 23 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat May 09 04:28:30 UTC 2020
;; MSG SIZE  rcvd: 135

dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 548
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;us-central56.discord.media.    IN      A

;; ANSWER SECTION:
us-central56.discord.media. 297 IN      A       162.159.137.234
us-central56.discord.media. 297 IN      A       162.159.130.235
us-central56.discord.media. 297 IN      A       162.159.128.235
us-central56.discord.media. 297 IN      A       162.159.129.235
us-central56.discord.media. 297 IN      A       162.159.138.234

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat May 09 04:28:33 UTC 2020
;; MSG SIZE  rcvd: 135

dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33205
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;us-central56.discord.media.    IN      A

;; ANSWER SECTION:
us-central56.discord.media. 288 IN      A       162.159.138.234
us-central56.discord.media. 288 IN      A       162.159.137.234
us-central56.discord.media. 288 IN      A       162.159.130.235
us-central56.discord.media. 288 IN      A       162.159.128.235
us-central56.discord.media. 288 IN      A       162.159.129.235

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat May 09 04:28:42 UTC 2020
;; MSG SIZE  rcvd: 135
```
Try a couple of `dig +tcp us-central56.discord.media @127.0.0.1` in a row and see if the second queries are still at the same time. 

Now, once DNS has resolved a name to IP address it's job is done. Latency is on the path between you and the server. If you want to measure it then use the proper tools, `ping` and `traceroute`. But since you see me as not knowing what I'm talking about, I'll trust the job of education to https://www.dnsstuff.com/network-latency

**Comment by SmallEngineMechanic** [comment]
> Your queries are being forced to tcp instead of udp. And nothing is caching.
> 
> In a normally functioning configuration the initial lookup will take longer than subsequent lookups:
> 
> ```
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14626
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 300 IN      A       162.159.138.234
> us-central56.discord.media. 300 IN      A       162.159.129.235
> us-central56.discord.media. 300 IN      A       162.159.128.235
> us-central56.discord.media. 300 IN      A       162.159.130.235
> us-central56.discord.media. 300 IN      A       162.159.137.234
> 
> ;; Query time: 23 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:30 UTC 2020
> ;; MSG SIZE  rcvd: 135
> 
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 548
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 297 IN      A       162.159.137.234
> us-central56.discord.media. 297 IN      A       162.159.130.235
> us-central56.discord.media. 297 IN      A       162.159.128.235
> us-central56.discord.media. 297 IN      A       162.159.129.235
> us-central56.discord.media. 297 IN      A       162.159.138.234
> 
> ;; Query time: 3 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:33 UTC 2020
> ;; MSG SIZE  rcvd: 135
> 
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33205
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 288 IN      A       162.159.138.234
> us-central56.discord.media. 288 IN      A       162.159.137.234
> us-central56.discord.media. 288 IN      A       162.159.130.235
> us-central56.discord.media. 288 IN      A       162.159.128.235
> us-central56.discord.media. 288 IN      A       162.159.129.235
> 
> ;; Query time: 1 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:42 UTC 2020
> ;; MSG SIZE  rcvd: 135
> ```
> 
> Try a couple of `dig +tcp us-central56.discord.media @127.0.0.1` in a row and see if the second queries are still at the same time.
> 
> Now, once DNS has resolved a name to IP address it's job is done. Latency is on the path between you and the server. If you want to measure it then use the proper tools, `ping` and `traceroute`. But since you see me as not knowing what I'm talking about, I'll trust the job of education to https://www.dnsstuff.com/network-latency

Sorry for shit talking you btw, I misread some of what Jayden was doing, and I completely understand what you mean

**Comment by Jayden000** [comment]
> 
> 
> Your queries are being forced to tcp instead of udp. And nothing is caching.
> 
> In a normally functioning configuration the initial lookup will take longer than subsequent lookups:
> 
> ```
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14626
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 300 IN      A       162.159.138.234
> us-central56.discord.media. 300 IN      A       162.159.129.235
> us-central56.discord.media. 300 IN      A       162.159.128.235
> us-central56.discord.media. 300 IN      A       162.159.130.235
> us-central56.discord.media. 300 IN      A       162.159.137.234
> 
> ;; Query time: 23 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:30 UTC 2020
> ;; MSG SIZE  rcvd: 135
> 
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 548
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 297 IN      A       162.159.137.234
> us-central56.discord.media. 297 IN      A       162.159.130.235
> us-central56.discord.media. 297 IN      A       162.159.128.235
> us-central56.discord.media. 297 IN      A       162.159.129.235
> us-central56.discord.media. 297 IN      A       162.159.138.234
> 
> ;; Query time: 3 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:33 UTC 2020
> ;; MSG SIZE  rcvd: 135
> 
> dschaper@nanopi-r2s:~$ dig us-central56.discord.media @127.0.0.1
> 
> ; <<>> DiG 9.11.5-P4-5.1-Debian <<>> us-central56.discord.media @127.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33205
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;us-central56.discord.media.    IN      A
> 
> ;; ANSWER SECTION:
> us-central56.discord.media. 288 IN      A       162.159.138.234
> us-central56.discord.media. 288 IN      A       162.159.137.234
> us-central56.discord.media. 288 IN      A       162.159.130.235
> us-central56.discord.media. 288 IN      A       162.159.128.235
> us-central56.discord.media. 288 IN      A       162.159.129.235
> 
> ;; Query time: 1 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Sat May 09 04:28:42 UTC 2020
> ;; MSG SIZE  rcvd: 135
> ```
> 
> Try a couple of `dig +tcp us-central56.discord.media @127.0.0.1` in a row and see if the second queries are still at the same time.
> 
> Now, once DNS has resolved a name to IP address it's job is done. Latency is on the path between you and the server. If you want to measure it then use the proper tools, `ping` and `traceroute`. But since you see me as not knowing what I'm talking about, I'll trust the job of education to https://www.dnsstuff.com/network-latency


Again apologies, wasn't really reading it's 12:46am.. But yeah it seemed to of made my latency slightly higher and didn't decrease with repeated queries


![image](https://user-images.githubusercontent.com/23621862/81464311-77d43180-918e-11ea-940c-f9754e697c8a.png)

**Comment by Jayden000** [comment]
@dschaper I know you assigned this case to someone else. But an interesting thing I just discovered and I installed Pi-hole on a VM and seems to be giving me my expected result. 
![image](https://user-images.githubusercontent.com/23621862/81464921-ed8ecc00-9193-11ea-8247-0dc5fcb1f921.png) 

This Pi-hole install is completely fresh

**Comment by Jayden000** [comment]
Apologies to anyone involved and wasting their time, but I just reinstalled Pi-hole on my Pi 4 as I saw that the VM was working fine with a fresh install and now my Query timings are correct. Sorry for wasting your time.
