### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by NorthernLoop** [pi-hole/pi-hole#332]
##### Expected Behaviour:
Hello, Just upgrade myself to pi2 for OpenVPN and Pi Hole on the same Pi. VPN Installed and everything fine. I upgraded from Pi B Wheezy to Pi 2 Jessie, cleaned install. This setup worked fine on Wheezy but I can't get it working on Jessie

##### Actual Behaviour:
After running the install I see there is a error:
```
pi@VPN:~ $ sudo curl -L install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20030  100 20030    0     0  13194      0  0:00:01  0:00:01 --:--:-- 69790
:::
::: sudo will be used for the install.
::: Using interface: eth0
**bash: line 156: /tmp/piholeINT: Permission denied**
::: Using IPv4 on 192.168.0.2/24
::: IPv6 will NOT be used.
::: Using Google DNS servers.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for toilet... already installed!
:::    Checking for figlet... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services. done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... OK!
:::     Updating repo in /etc/.pihole.. done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin.. done!
:::
::: Installing scripts... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriting
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!         .
:::
::: Getting adaway.org list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... List updated, transport successful!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... List updated, transport successful!
::: Getting winhelp2002.mvps.org list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting optimate.dl.sourceforge.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 253005 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 145792 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 14 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 13 domains whitelisted!
::: Running blacklist script to update HOSTS file... 0 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!
::: Restarting services... done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:
:::     192.168.0.2/24
:::
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log
pi@VPN:~ $ sudo nano  /etc/dnsmasq.conf
pi@VPN:~ $ dit
-bash: dit: command not found
pi@VPN:~ $ dig google.com

; <<>> DiG 9.9.5-9+deb8u5-Raspbian <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32178
;; flags: qr rd ra; QUERY: 1, ANSWER: 16, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             259     IN      A       62.252.232.25
google.com.             259     IN      A       62.252.232.20
google.com.             259     IN      A       62.252.232.44
google.com.             259     IN      A       62.252.232.45
google.com.             259     IN      A       62.252.232.54
google.com.             259     IN      A       62.252.232.35
google.com.             259     IN      A       62.252.232.30
google.com.             259     IN      A       62.252.232.34
google.com.             259     IN      A       62.252.232.50
google.com.             259     IN      A       62.252.232.55
google.com.             259     IN      A       62.252.232.49
google.com.             259     IN      A       62.252.232.29
google.com.             259     IN      A       62.252.232.59
google.com.             259     IN      A       62.252.232.39
google.com.             259     IN      A       62.252.232.24
google.com.             259     IN      A       62.252.232.40

;; Query time: 83 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Feb 18 21:31:20 GMT 2016
;; MSG SIZE  rcvd: 295

pi@VPN:~ $
```

##### Steps to reproduce this issue:
sudo curl -L install.pi-hole.net | bash

**Comment by NorthernLoop** [comment]
Removed that file and ran installer again and didn't error but still don't have any access to internet from clients.

**Comment by PromoFaux** [comment]
Is you VPN for incoming our outgoing connections?

**Comment by NorthernLoop** [comment]
Both, but I wanted to mention the VPN in case there was something relevant.

Its actually no internet on the local client devices, reports no DNS.

Just testing the Pi does have DNS running so I can't work out what the issue is
`pi@VPN:/tmp $ tail -f /var/log/pihole.log
Feb 18 21:44:02 dnsmasq[18912]: reply raw.githubusercontent.com is <CNAME>
Feb 18 21:44:02 dnsmasq[18912]: reply github.map.fastly.net is 185.31.18.133
Feb 18 21:44:18 dnsmasq[18912]: exiting on receipt of SIGTERM
Feb 18 21:45:21 dnsmasq[22060]: started, version 2.72 cachesize 10000
Feb 18 21:45:21 dnsmasq[22060]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
Feb 18 21:45:21 dnsmasq[22060]: warning: ignoring resolv-file flag because no-resolv is set
Feb 18 21:45:21 dnsmasq[22060]: using nameserver 8.8.4.4#53
Feb 18 21:45:21 dnsmasq[22060]: using nameserver 8.8.8.8#53
Feb 18 21:45:21 dnsmasq[22060]: read /etc/hosts - 5 addresses
Feb 18 21:45:25 dnsmasq[22060]: read /etc/pihole/gravity.list - 145793 addresses
Feb 18 21:50:40 dnsmasq[22060]: query[PTR] 34.0.168.192.in-addr.arpa from 127.0.0.1
Feb 18 21:50:40 dnsmasq[22060]: config 192.168.0.34 is NXDOMAIN
Feb 18 21:50:54 dnsmasq[22060]: query[A] doubleclick.com from 127.0.0.1
Feb 18 21:50:54 dnsmasq[22060]: /etc/pihole/gravity.list doubleclick.com is 192.168.0.2
Feb 18 21:50:54 dnsmasq[22060]: query[AAAA] doubleclick.com from 127.0.0.1
Feb 18 21:50:54 dnsmasq[22060]: forwarded doubleclick.com to 8.8.4.4
Feb 18 21:50:54 dnsmasq[22060]: forwarded doubleclick.com to 8.8.8.8
Feb 18 21:50:55 dnsmasq[22060]: reply doubleclick.com is 2a00:1450:4009:802::200e

pi@VPN:/tmp $
`

**Comment by PromoFaux** [comment]
OK, silly question, Have you tried it with openVPN disabled, just to rule that out?

The reason I ask is that I personally had issues with running both on the same pi. I've since seperated them to seperate machines (and doing some fancy DHCP stuff to get make sure pi-hole's upstream DNS queries go through the VPN)

The issue I was having was that the local IP address was on the subnet of the endpoint of the VPN, which seemed to slow things down a bit.

But you've got no net connection on any machine? What happens if you ping doubleclick.net from your client machine?

**Comment by NorthernLoop** [comment]
No purged OpenVPN! Not sure how it worked on Wheezy though? It was slow on the client VPN but local client users still had internet.

Guess I'll split them up if you think I'll get issues anyways

So is it better to have VPN on Pi 2? Or Pi-Hole? Then the other on the slower Pi B? Or just buy another Pi 2 as they are so cheap?

So what fancy stuff do I need to do to have VPN and Pi Hole work together. Speak slowly as just getting into this :)

**Comment by PromoFaux** [comment]
Just tried a fresh install on a pi, and it was all working OK... Did you set up openVPN first?

OK, so I'm actually running pi-hole on a full-blown debian 8 server. (Works just fine, even without the user `pi`) But another pi would suffice!

My RPi2 on the other hand is set up as a VPN gateway and DHCP server. This allows me to point certain devices to use the VPN as their gateway, and the rest to use my standard DSL router, and the debian server (running pi-hole) as DNS. As a plus side to this, With the debian server pointed at the RPi as a gateway, all my upstream DNS lookups are tunnelled through the VPN, so my ISP can't be nosey!

I set this up by loosely following [this guide](http://www.dickson.me.uk/2014/11/04/setting-up-a-raspberry-pi-as-a-vpn-home-router/) to suit my situation.

Took a bit of fiddling about, had to keep the DHCP server on my router running, but only able to dish out one address (to the RPi2), so everything else is handled by the DHCP server running on the pi.

**Comment by NorthernLoop** [comment]
Yeah I setup OpenVPN first from [this guide](https://www.deviousweb.com/2015/11/29/raspberry-pi-as-an-openvpn-server/)

Then added Pi-Hole. As Jessie is different I had to find the above as the file locations were different from wheezy.

When I setup wheezy I used [this](http://readwrite.com/2014/04/10/raspberry-pi-vpn-tutorial-server-secure-web-browsing) everything worked that way.

**Comment by PromoFaux** [comment]
is `192.168.0.2` the IP on `eth0` or on `tuno`?

**Comment by NorthernLoop** [comment]
Yeah `192.168.0.2` is on `eth0`

**Comment by PromoFaux** [comment]
paging @dschaper

(He understands networks a bit better than I)

**Comment by NorthernLoop** [comment]
Its OK I'll do another clean install and have VPN on 1 box and Pi-Hole on another.

If they would would together for my simple requirements then would be great. But if there is performance issues then I might as well split them up.

**Comment by dschaper** [comment]
Pi-hole will run just fine on a B, it doesn't need or use the quad-core... You'll probably have better success with a dual Pi setup, but so far I haven't seen any problems. The first entry shows a `dig` of `google.com` which are the right addresses, and the source server is `127.0.0.1` so it's getting records from the local `dnsmasq` server. In your `/var/log/pihole.log` you have an entry that shows `gravity.list` and the IP address of the Pi-hole, so it is blocking advertisements when the Pi-hole is queried... Let me know what you decide to do, but really a Pi-hole will run just fine on a Zero if you had one...

**Comment by PromoFaux** [comment]
They _should_ run together OK, but it was not my experience. That said, I was using it as a permanently connected outbound connection. 

pi-hole kept getting confused between `eth0` and `tun0` and in the end I found it easier just to seperate them.

**Comment by NorthernLoop** [comment]
I'll setup VPN on Pi 2 and get that side working, doing the install now. Then will add Pi-Hole to the older Pi. 

Report back shortly.

**Comment by NorthernLoop** [comment]
Split the servers up and everything is working as it should be. Ads are blocked on the local network and I can VPN remotely from GSM/LTE/Wifi and also blocking adverts! Yea!!

The model B is a little slow but might just upgrade it anyways. Doesn't seem to be effecting the internet performance though.

**Comment by PromoFaux** [comment]
:+1
