### ISSUE TITLE
Local DNS Records resolving to pihole block page

### ISSUE THREAD

**Issue by thomasblade** [pi-hole/pi-hole#3326]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
Local DNS records should resolve to the IP addresses set in the admin GUI.  Example in screenshots and testing are for pihole admin interface

**Actual behaviour:**

Visiting the custom DNS Records directs to a pihole "website blocked" page stating the page is blocked with the reason "Not found on any blacklist".

**Steps to reproduce:**

I've tried adding several variations to the the list using different TLDs, local, etc they produce the same result.  When I try adding a Regex Whitelist entry for the TLD, the website is still blocked with an updated message stating "Manually Blacklisted by wildcard"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/t8gvczbvos

**Troubleshooting undertaken, and/or other relevant information:**

![Local DNS Page](https://user-images.githubusercontent.com/15692991/81510821-7748b180-92da-11ea-93b9-1b769097a950.png)
![Whitelist Page](https://user-images.githubusercontent.com/15692991/81510822-77e14800-92da-11ea-9edb-55afe6a482f2.png)
![Blocked - wildcard](https://user-images.githubusercontent.com/15692991/81510823-77e14800-92da-11ea-845a-f24be10bbe40.png)
![Blocked - not found on list](https://user-images.githubusercontent.com/15692991/81510824-77e14800-92da-11ea-9af3-09721555e514.png)

**Comment by DL6ER** [comment]
This is expected. Check

> Slightly changed order of precedence in blocking.  The precedence is now:
>   - Exact Whitelist
>   - Regex Whitelist
>   - Exact Blacklist
>   - Blocklist domains (AKA gravity)
>   - Regex Blacklist

Source: https://pi-hole.net/2020/05/10/pi-hole-v5-0-is-here/#page-content

Only when none of the points above match, we trigger an actual lookup. This will first query the DNS cache (where it would find your `pi.pug` entry). Only when nothing is found there, a query will be forwarded upstream.

It is technically not feasible to do a DNS cache lookup before checking the blacklist.

Conclusion: As far as I'm concerned I see this as expected behavior right now.

**Comment by dschaper** [comment]
I think there's a bit of confusion here. `pi.pug` is being resolved correctly but `http://pi.pug/` is 404. You see the blockpage instead of a 404 page due to how the block page works (or doesn't work and should be deprecated.)

**Comment by dschaper** [comment]
Run some `dig` commands to see if you are getting the intended IP addresses or if those domains really are getting blocked.

**Comment by PromoFaux** [comment]
Ah yeah, that's a good point.

Usually by browsing to `http://pi.hole` there is some special stuff in the header that says "You probably meant to go to `/admin`", and automatically redirects. This is hard coded for the domain `pi.hole`.

If you want to use `pi.local`. or `pi.pug`, you'll need to append `/admin` to the address

![image](https://user-images.githubusercontent.com/1998970/81511094-be509a00-930e-11ea-8aed-a6b6dca333e3.png)

**Comment by thomasblade** [comment]
Ah yes - interesting.  Browsing to the IP w/o /admin yields the standard "you probably meant admin..." but when using local records it "blocks".  By appending /admin to pi.pug I can successfully get to the page!  Thanks for the quick responses guys!

-Thomas

**Comment by TiMESPLiNTER** [comment]
I know this issue is closed and it provides the "solution". But this actually cost me like 2 hours last night to figure out that I have to append `/admin` myself if I'm not using the IP. Woudn't it make sense to not hard code the `pi.hole` domain for this? Especially as the message "Blocked because not found on any whatever" is quite misleading.

**Comment by dschaper** [comment]
Hi, sorry you had that experience.

We are deprecating the blockpage for various reasons, this being one of them. They just don't work for most sites anymore with the move to https/tls. 

The reason there is a limitation on what URLs are allowed is to prevent a malicious advertisement or site from being able to attempt to access the admin page or present the admin page in place of the web payload.

**Comment by DB-CL** [comment]
I just had the same problem and I just wasted two hours trying to understand why my personal domain was "blocked" by pihole although the problem was just a /admin missing ... I don't know if I missed some configuration here to make it work, but the message is still misleading.

**Comment by exylian** [comment]
> Ah yes - interesting. Browsing to the IP w/o /admin yields the standard "you probably meant admin..." but when using local records it "blocks". By appending /admin to pi.pug I can successfully get to the page! Thanks for the quick responses guys!
> 
> -Thomas

Same here... For those who use treafik simply add the following commands to your labels

```
- "traefik.http.middlewares.add-admin.addprefix.prefix=/admin"
- "traefik.http.routers.pihole.middlewares=add-admin@docker"

```
