### ISSUE TITLE
Since upgrade to v5 - Lists not being downloaded

### ISSUE THREAD

**Issue by aproposnix** [pi-hole/pi-hole#3331]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I expect to be able to add existing blocklists to pihole without them failing to load

This was the behaviour prior to version 5

**Actual behaviour:**

If I add an existing blocklist (esp., from the many on github), they all fail. See screen. 

**Steps to reproduce:**

Add a list (esp., from github). Refresh gravity. See failures. 
Example: 
  [✗] List download failed: no cached list available

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
5rf6rz87jo

**Troubleshooting undertaken, and/or other relevant information:**

I've tried adding many different ones with the same result. 

Screenshot: 

https://pix.toile-libre.org/upload/original/1589188779.png

**Comment by jfb-pihole** [comment]
I don't believe this is a V5 problem, as I am able to load your subscribed blocklists with no problems.  Have you tried to download these again, and 
```
pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 55618 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: No changes detected
  [i] Received 26857 domains

  [i] Target: http://sysctl.org/cameleon/hosts
  [✓] Status: No changes detected
  [i] Received 20567 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  [✓] Status: No changes detected
  [i] Received 34 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  [✓] Status: No changes detected
  [i] Received 2701 domains

  [i] Target: https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt
  [✓] Status: Retrieval successful
  [i] Received 17701 domains

  [i] Target: https://raw.githubusercontent.com/SweetSophia/mifitxiaomipiholelist/master/mifitblocklist.txt
  [✓] Status: Retrieval successful
  [i] Received 58 domains

  [i] Target: https://raw.githubusercontent.com/kevinle-1/Xiaomi-telemetry-blocklist/master/xiaomiblock.txt
  [✓] Status: Retrieval successful
  [i] Received 28 domains

  [i] Target: https://raw.githubusercontent.com/kevinle-1/Windows-telemetry-blocklist/master/windowsblock.txt
  [✓] Status: Retrieval successful
  [i] Received 140 domains, 1 domains invalid!
      Sample of invalid domains:
      - telemetry.appex.bing.net:443

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 123703 (109124 unique domains)
  [i] Number of exact blacklisted domains: 4
  [i] Number of regex blacklist filters: 26
  [i] Number of exact whitelisted domains: 74
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
```

**Comment by aproposnix** [comment]
I can only assume it was v5 as it's only happened since the upgrade. I am still not able to update them even after removing and adding them again.

**Comment by dschaper** [comment]
What does `curl -I https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt` show?

**Comment by aproposnix** [comment]
Interestingly there's a seg fault at the end. 

> 
HTTP/2 200 
server: GitHub.com
content-type: text/plain; charset=utf-8
strict-transport-security: max-age=31556952
last-modified: Mon, 11 May 2020 13:47:26 GMT
etag: "5eb9576e-440e7"
access-control-allow-origin: *
expires: Mon, 11 May 2020 16:34:05 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: 4ABA:26FE:7321FA:9015A8:5EB97C24
accept-ranges: bytes
date: Tue, 12 May 2020 05:31:33 GMT
via: 1.1 varnish
age: 507
x-served-by: cache-fra19146-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1589261494.603330,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: e05cedf4656d4380b115b62e7fd12f0392cdd114
content-length: 278759

Segmentation fault

>

**Comment by dschaper** [comment]
If you can fix that then I'd say the chances are Pi-hole will work again.

**Comment by aproposnix** [comment]
I did nothing more than restart my server a few times and it seems to be working now. Closing the issue. I assume it's a one-off issue.
