### ISSUE TITLE
Install 5.0 fails on Raspbian Buster

### ISSUE THREAD

**Issue by edegroot-nl** [pi-hole/pi-hole#3333]
curl -sSL https://install.pi-hole.net | bash

  [✗] Root user check
  [i] Script called with non-root privileges
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source

  [✓] Sudo utility check

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [✓] Default SELinux: permissive
main: line 1960: getenforce: command not found
$ export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
$ getenforce
-bash: getenforce: command not found

 $ sudo apt install selinux-utils -y
Get:1 http://mirror.serverius.net/raspbian/raspbian buster/main armhf selinux-utils armhf 2.8-1+b1 [94.2 kB]
Fetched 94.2 kB in 1s (149 kB/s)
Selecting previously unselected package selinux-utils.
(Reading database ... 44419 files and directories currently installed.)
Preparing to unpack .../selinux-utils_2.8-1+b1_armhf.deb ...
Unpacking selinux-utils (2.8-1+b1) ...
Setting up selinux-utils (2.8-1+b1) ...

curl -sSL https://install.pi-hole.net | bash

  [✗] Root user check
  [i] Script called with non-root privileges
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source

  [✓] Sudo utility check

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [✓] Default SELinux: permissive
  [✓] Current SELinux: Disabled
  [i] Using upstream DNS: Google (ECS) (8.8.8.8, 8.8.4.4)
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: xxxxxxxx
  [i] IPv6 address:
  [i] Web Interface On
  [i] Web Server Off
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...HEAD is now at 4d25f69 Merge pull request #3321 from pi-hole/release/v5.0
  [✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [i] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin...HEAD is now at b86e4a3 Merge pull request #1247 from pi-hole/release/v5.0
  [✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [i] Checking for dnsutils (will be installed)
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [i] Checking for netcat (will be installed)
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [i] Checking for idn2 (will be installed)
  [i] Checking for sqlite3 (will be installed)
  [✓] Checking for libcap2-bin
  [i] Checking for dns-root-data (will be installed)
  [✓] Checking for libcap2
  [i] Processing apt-get install(s) for: dnsutils netcat idn2 sqlite3 dns-root-data, please wait...
 [i] View the web interface at http://pi.hole/admin or http://xxxxxxxx/admin

  [i] You may now configure your devices to use the Pi-hole as their DNS server
  [i] Pi-hole DNS (IPv4): xxxxxx
  [i] If you set a new IP address, please restart the server running the Pi-hole

  [i] The install log is located at: /etc/pihole/install.log
Installation Complete!

**Comment by yubiuser** [comment]
Did you run the script as root?
```
[✗] Root user check
```

**Comment by edegroot-nl** [comment]
Further in the script:
[✓] Sudo utility check
[✓] Root user check

The issue is that the package selinux-utils isn't checked while using the command getenforce that is part of that package. This is a fresh raspbian (Feb-2020) install.

**Comment by dschaper** [comment]
Are you sure this is Raspbian? SELinux is not used by Raspbian.

**Comment by edegroot-nl** [comment]
> Are you sure this is Raspbian? SELinux is not used by Raspbian.

 $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by dschaper** [comment]
And you downloaded the image from Raspbian, burned it to SDCard and made no system level changes?

**Comment by edegroot-nl** [comment]
Yes. 3341 has the same issue.

**Comment by profporridge** [comment]
If you read the error log you can see the failure was because selinux isn't present, the reporter does a 'apt-get install selinux' at that point and tries again, this time it works

**Comment by dschaper** [comment]
I asked because I have yet to see a card burned with https://www.raspberrypi.org/downloads/raspbian/ come with SELinux installed and in permissive mode.

**Comment by edegroot-nl** [comment]
dschaper is right.. i missed your comment "raspbian" assumed raspberrypi.org. 

My install is https://downloads.raspberrypi.org/raspbian_lite_latest
Regardless of that, most of the installs are images from raspberrypi.org, where V4 installs without any issues and now with V5 it fails. For me this is not a big issue, i can fix this. 

Don't know about other raspberry-pi users starting with raspbian-linux/pi-hole..

**Comment by yubiuser** [comment]
Does this issue still exist?
