### ISSUE TITLE
Installation stops if no blocklist is selected. v5.0

### ISSUE THREAD

**Issue by castillo92** [pi-hole/pi-hole#3336]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
Doing a fresh install of PiHole 5.0, if we do not select any list in the initial setup, installation should continue, because we will add our custom list later.

**Actual behaviour:**

If we do not select any blocklist in the initial setup step, installation fails because `/etc/pihole/adlists.list` do not exist

![Captura](https://user-images.githubusercontent.com/37965565/81553819-06f76a00-9386-11ea-9a45-7c7376ada748.PNG)

Install log:
```
user-01@srv-01:~$ curl -sSL https://install.pi-hole.net | sudo bash
[sudo] password for user-01: 

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.4.5
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 69 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Using upstream DNS: Cloudflare (1.1.1.1, 1.0.0.1)
chmod: cannot access '/etc/pihole/adlists.list': No such file or directory error when the file exists
```

**Steps to reproduce:**
Simply make a fresh install and leave initial blocklists unselected.

**Troubleshooting undertaken, and/or other relevant information:**
By selecting at least one list, the installation continues normally.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1
