### ISSUE TITLE
FTL Check Sum error

### ISSUE THREAD

**Issue by crazypete00** [pi-hole/pi-hole#3337]
Installing Pi-Hole v5 on a new instance of Diet Pi.

[✗] Downloading and Installing FTL
Error: Download of https://github.com/pi-hole/ftl/release/lastest/download/pihole-FTL-linux-x86_64 failed (checksum error)
[✗] FTL Engine not installed

I had to change /etc/resolve.conf from 127.0.0.1 to 8.8.8.8 to get this far.

**Comment by dschaper** [comment]
What method are you using to install?

**Comment by crazypete00** [comment]
I've installed dietpi on virtual box. 
using curl -sSL https://install.pi-hole.net | bash

i also tried the alt method listed on the installation notes.

I have however sort of fixed it. I had to disable IPv6 on my NIC and then untick IPv6 when running through the Pihole config. seems to install fine then. 

the other issue i had when installing is at the part where it clones adminlte. it failed to download it on https however manually cloning it using git:// worked.

**Comment by dschaper** [comment]
Okay, a checksum error shows that it did download but not completely. This may be an issue with the OS, their support can provide more info.

**Comment by crazypete00** [comment]
ok thanks. in the mean time there is a work around. cheers

**Comment by PromoFaux** [comment]
> Error: Download of https://github.com/pi-hole/ftl/release/lastest/download/pihole-FTL-linux-x86_64

Was this copy pasted from the terminal or did you type it out? I've just noticed `lastest` instead of `latest` in that URL...

**Comment by crazypete00** [comment]
sorry, that's my typo.

**Comment by PromoFaux** [comment]
Ah good, I nearly had a heart attack!
