### ISSUE TITLE
Failed to update to Pi-Hole 5 on Debian Buster

### ISSUE THREAD

**Issue by marceldegraaf** [pi-hole/pi-hole#3339]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

I'm updating Pi-Hole following the 5.0 release post, by running `pihole -up`. I expect Pi-Hole to be updated to the latest version.

**Actual behaviour:**

When running `pihole -up`, the installer process halts because the `php7.0-xml` can't be found:

```
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u6
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.0-common
  [✓] Checking for php7.0-cgi
  [✓] Checking for php7.0-sqlite3
  [i] Checking for php7.0-xml (will be installed)
  [i] Checking for php-intl (will be installed)
  [i] Processing apt-get install(s) for: php7.0-xml php-intl, please wait...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.0-xml
E: Couldn't find any package by glob 'php7.0-xml'
E: Couldn't find any package by regex 'php7.0-xml'

  Unable to complete update, please contact Pi-hole Support
```

This is running on a standard Debian 10 (Buster) installation with up-to-date apt:

```
$ cat /etc/os-release                                                                                                                    
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```

**Steps to reproduce:**

Run `pihole -up` from the latest 4.x version of Pi-Hole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`b9sjdsvidm`

**Troubleshooting undertaken, and/or other relevant information:**

Confirmed the `php7.0-xml` package is not available for Debian Buster by trying to install it with `apt-get install php7.0-xml`.

**Comment by Bugbavka** [comment]
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Yes, Debian 10 does not have php v7.0.
You can find v7.3 in repository
```
$ apt search php7.3-xml
Sorting... Done
Full Text Search... Done
php7.3-xml/stable,now 7.3.14-1~deb10u1 amd64 [installed,automatic]
  DOM, SimpleXML, WDDX, XML, and XSL module for PHP

php7.3-xmlrpc/stable,now 7.3.14-1~deb10u1 amd64 [installed]
  XMLRPC-EPI module for PHP
```
You have php v7.0 which is no longer in repository.

You can do:

- Update to PHP v7.3 from repository
- get php7.0-xml somewhere outside repository
- edit update script to ignore missing packages - it might fail somewhere else

I was facing similar issue about a year ago after upgrading to Debian 10 from Debian 9
(Not sure if it was 5.X to 7.3 or 7.0 to 7.3), purged old php install and installed newest from repo.

I am still runing v4 (v4.4) and will wait few days before updating.

**Comment by marceldegraaf** [comment]
> Update to PHP v7.3 from repository

Ah, thanks, that fixed it. After explicitly installing PHP 7.3 and friends via `apt`, I was able to run `pihole -up` and update FTL as well.
