### ISSUE TITLE
Request: Add Windows 10 tracking hostfile

### ISSUE THREAD

**Issue by ajp2k13** [pi-hole/pi-hole#334]
Would it be possible to add this? It blocks the telemetry hosts used in Windows 10...

https://github.com/crazy-max/HostsWindowsBlocker

**Comment by PromoFaux** [comment]
I'm pretty sure a lot of these are covered... just grepped a few of them against `/etc/pihole/gravity.list` and they're in there.

I'll add the list address to the [wiki page](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) as a possible entry for future. 

If you want to include the list yourself, just follow the instructions on that page :)

**Comment by PromoFaux** [comment]
Although, adding that list to my own `/etc/pihole/adlists.list` file adds another 549 domains to the blocklist, so we haven't got them all! I will run with them for a few days to test, to make sure they don't cause problems before including them by default.

**Comment by ajp2k13** [comment]
Sounds like a good plan, I'll add it to mine as well and test it. Thanks!

**Comment by slamanna212** [comment]
Im not sure about others but id prefer if they were optional. Maybe another prompt during install

**Comment by PromoFaux** [comment]
@slamanna212 I'm going to see if I run into any issues at home with them. But that's a very good point. We can list it as a list that users can add if they want on the wiki page.

**Comment by PromoFaux** [comment]
To be totally fair, even if they were included by default.. they're still optional, as you can just remove the source list from the `adlists.list` file created when customising the sources :)

everything is optional.

**Comment by dschaper** [comment]
Don't users have the ability to disable telemetry and traffic when they install Windows 10? I know I did...

**Comment by PromoFaux** [comment]
That too. Though it's not straight forward.

**Comment by dschaper** [comment]
I got skittish when it started asking if I wanted to log on to WiFi hotspots that my friends have access to. So I backed up a couple of steps and went step by step instead of using the auto-configure installation... But I'm highly against prepopulating  lists with domains, I think we should be providing the tools for users to configure as they need, not doing the decision making for them. FAQ entries should suffice... (Harumph harumph, grumble and all that...)

**Comment by slamanna212** [comment]
Completed Agree @dschaper

**Comment by PromoFaux** [comment]
>think we should be providing the tools for users to configure as they need, not doing the decision making for them.

Perhaps, then, we should remove all the default lists, and present them as options on install.. much like the upcoming upstream DNS options...

**Comment by slamanna212** [comment]
The standard Malware/Ad block lists to me seem fine, the Pi Hole is advertised as a Hardware Ad Blocker. But if you want to block extra stuff like the Win 10 Telemetry , that is optional

**Comment by ajp2k13** [comment]
Totally fine with me if it's optional, I like just having the option... :)

**Comment by PromoFaux** [comment]
I think what we'll do is improve the [wiki](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) to give more detailed information on choosing custom lists. 

It's pretty much there, but a couple of things could probably do with clarifying.

**Comment by jacobsalmela** [comment]
I have updated the wiki page to better explain how to add your own lists.

**Comment by PromoFaux** [comment]
Ah yeah, that looks good. Thanks @jacobsalmela
