### ISSUE TITLE
Pihole 5 won't work with Apache2

### ISSUE THREAD

**Issue by lucki1000** [pi-hole/pi-hole#3343]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
pi.hole/admin after login shows statistics.
And can use it as it should be.

**Actual behaviour:**
I can use the WebUI to look at the Query Log and the Settings, but there are no statistics and nothing in anymore in my black/block/withelist and if I will anything add to my block/withelist I've get this error: "Error, somthing wen't wrong"

**Steps to reproduce:**

I've use a Raspberry Pi 3B+ with Raspbian Buster, Apache2(I know that is not the recommend Webserver) and updated to Pihole 5 and since this update it won't work with Apache2, then I've installed lighttpd and tried it with these and there it works, my question is can I get it work on Apache2 again?

**Comment by PromoFaux** [comment]
You might be best off asking the community for assistance with this one over on discourse.pi-hole.net

The only officially supported configuration for the web admin at this stage is `lighttpd`, I don't think any of the dev's have `apache2` running.

**Comment by lucki1000** [comment]
Okay thanks,  then I will ask the community sorry for the Issue.
