### ISSUE TITLE
Pi-Hole Admin page NOT accessable without internet

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#335]
##### Expected Behaviour:
typed in Pi-Hole admin page address, expected it to come right up as usual

##### Actual Behaviour:
page just hung blank, and never loaded

##### Steps to reproduce this issue:
yesterday we has a car crash in town that took down a few pole carrying REDI-net fiber, so we had no internet for 12 hrs. during that time i wanted to look at the stats on the Pi-Hole admin page, but i could not reach the pi-hole. no internet no pi-hole admin page. ALL other IPs on my LAN worked fine. is this normal?

steps to reproduce: disconnect internet and try to access Pi-Hole Admin page

**Comment by PromoFaux** [comment]
Erm. As the page is hosted locally.. and internet outage should not have effected it...!

I will have a try tonight when I get home. Could be trying to contact the CDNs for bootstrap/jquery etc.

We may need to host those locally.

**Comment by jacobsalmela** [comment]
Yeah, as long as you are on the LAN, it should be reachable, but if the bootstrap files can't be accessed via the Internet, this might happen.  I will also test this later tonight.

**Comment by C4Wiz** [comment]
you guys are the best! best support by far!!

**Comment by jacobsalmela** [comment]
We [try to be our best](http://dollhouse.wikia.com/wiki/Self-improvement).

**Comment by C4Wiz** [comment]
i have always been impressed with support here!

**Comment by C4Wiz** [comment]
Donation made!

**Comment by PromoFaux** [comment]
:+1: Thanks!

**Comment by jacobsalmela** [comment]
Chaya t'not :+1:

**Comment by Mcat12** [comment]
It's probably some cdn scripts can't be downloaded... We can host them locally to fix this.

**Comment by DonLexos** [comment]
It's most definately this part that causes issues since that does things on the page.
```
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css" />
```
Would make sense to host them locally, it would (or at least) should always be quicker to get them from the pi then from a CDN.

There are more references to (internet) pages (like the coinbase button) that will break if there is no active internet connection.

**Comment by PromoFaux** [comment]
The next release will fix this. (Which will be in the next hour or so.. or sooner!)

**Comment by Mcat12** [comment]
Yep. We're getting everything ready to release!

**Comment by Hippyjake** [comment]
Hey all. Using fallback.js might be a good way to go. It lets you make fallbacks for CDNs and other things.
https://github.com/dolox/fallback

**Comment by Mcat12** [comment]
We now have everything locally hosted, but thanks for the suggestion!

**Comment by Hippyjake** [comment]
:+1:

**Comment by DonLexos** [comment]
This is fixed I believe (and can be closed)
