### ISSUE TITLE
unable to complete update, please contact Pi-Hole support

### ISSUE THREAD

**Issue by fredsteram** [pi-hole/pi-hole#3350]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
pihole -up
-
-
-
-

**Log file output [if available]**

`output`

Unable to locate package php5-xml
Unable to locate package php-intl

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: rPi

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Please provide further information so we can help you.

Something like will the following will be necessary.

> Device specifics
> 
> Hardware Type: rPi, VPS, etc
> OS:
> rPi

You can directly edit your initial post to add this.

**Comment by fredsteram** [comment]
I guess I needed to put it here

OS: rPi

**Comment by Marcoevich** [comment]
@fredsteram Unfortunately this information isn't giving any clue about your device specifics. What DL6ER mean't was, can you post your device type? e.g. is it a raspberry pi or other kind of server? And what is the operating system that you're running? E.g. raspbian, debian, or someting else?

Thanks for providing this information.

**Comment by nobody-DE** [comment]
Hello,
I got a simular  error message:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.0-xml
E: Couldn't find any package by glob 'php7.0-xml'
E: Couldn't find any package by regex 'php7.0-xml'

  Unable to complete update, please contact Pi-hole Support

I´m running a RasPi 3 with an up-to-date Debian Buster

Any hints for my? Thx!

**Comment by fredsteram** [comment]
Sorry yeah I am running a RasPi 3 with up to date Rasbian.  Below is the full log.

  [i] Existing PHP installation detected : PHP version 5.6.40-0+deb8u11
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php5-common
  [✓] Checking for php5-cgi
  [✓] Checking for php5-sqlite
  [i] Checking for php5-xml (will be installed)
  [i] Checking for php-intl (will be installed)
  [i] Processing apt-get install(s) for: php5-xml php-intl, please wait...
--------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php5-xml
E: Unable to locate package php-intl

**Comment by PromoFaux** [comment]
@fredsteram 

> PHP version 5.6.40-0+deb8u11

This is quite an old version of `php` I think. Are you by any chance on Raspbian 7 (Jessie)?

If so, you'll need to update to a newer version of raspbian, such as Raspbian 9 (Stretch) or 10 (Buster) per the docs:

https://docs.pi-hole.net/main/prerequesites/

Are you able to provide a debug token to confirm some things for us please? `pihole -d`


@nobody-DE - please open a new issue thread. Thanks

**Comment by fredsteram** [comment]
DOH, thanks I missed that. Dist upgrade did it. Newby mistake from an old guy.

**Comment by PromoFaux** [comment]
Happens to the best of us :)

Glad you got it working
