### ISSUE TITLE
Pi-hole 5 broke web interface dashboard

### ISSUE THREAD

**Issue by Synetech** [pi-hole/pi-hole#3354]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Dashboard should show statistics and graphs and charts, oh my

**Actual behaviour:**

Dashboard is empty

**Steps to reproduce:**

Update the web-interface to version 5.0

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Viewed backed-up copy of web-interface from 4.3.2 and it works correctly. It's only been broken since updating the web-interface to 5.0.

5.0:

![Screenshot-2020-05-13--00-00-17 - Pi-hole Admin Console 5 0](https://user-images.githubusercontent.com/5210197/81769952-d9f1a700-94ac-11ea-9188-189924bff098.png)

4.3.2:

![Screenshot-2020-05-12--23-59-45 - Pi-hole Admin Console 4 3 2](https://user-images.githubusercontent.com/5210197/81769955-da8a3d80-94ac-11ea-847f-f3ab84c11baf.png)

**Comment by rationality6** [comment]
I have the same issue. This should be related php7.0-xml update problem

<img width="581" alt="Screen Shot 2020-05-13 at 3 11 27 PM" src="https://user-images.githubusercontent.com/3889468/81777544-08fb2d80-952c-11ea-9875-ff49271f4dcc.png">

**Comment by PromoFaux** [comment]
The web interface works on v5.0, we wouldn't have released it if it didn't ;)

Please provide some more information about your install:

 - What hardware is it running on?
 - What operating system?
 - Have you modified any configuration files/core files
 - Is there anything obvious in the debug log? You can generate this with `pihole -d` and it will display some information on the screen. You can also choose to upload it to us if you cannot see anything obvious inside.

**Comment by Synetech** [comment]
It's complaining about the X-Header:

```
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Date: Wed, 13 May 2020 12:21:09 GMT
Server: Apache
Last-Modified: Wed, 25 Sep 2019 05:48:32 GMT
ETag: "64e-5935a33fb4c00"
Accept-Ranges: bytes
Content-Length: 1614
Cache-Control: max-age=86400
Expires: Thu, 14 May 2020 12:21:09 GMT
Vary: Accept-Encoding
Content-Type: text/html

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Date: Wed, 13 May 2020 12:21:09 GMT
Server: Apache
Set-Cookie: PHPSESSID=84kepcb9qr8ah3noc9gjlq4mqf; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
```

**Comment by PromoFaux** [comment]
> Server: Apache

Unfortunately none of the developers run `apache` as a web server, so we're unlikely to be able to help in this instance. We only really have the resources to be able to troubleshoot issues with a stock (in this case: `lighttpd`) installation. Can I suggest our [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) forums? There may be another user that has got Pi-hole 5.0 working on apache who help out!

**Comment by PromoFaux** [comment]
As a note: The whole "running on a non-standard web server" issue should be come a thing of the past in a planned future version, in which the admin interface will be served directly from `pihole-FTL`, on whatever port the user chooses.

See https://github.com/pi-hole/web and https://github.com/pi-hole/FTL/pull/659

**Comment by Synetech** [comment]
The problem was that the sqlite3 PHP extension wasn't available. I fixed it by installing php-sqlite3.

**Comment by PromoFaux** [comment]
> I miss the smoothed graphs :-|

Sorry! I believe the design choice to change them to bar rather than smoothed was it more accurately reflects what happened at a specific point in time. The lines between data points didn't actually mean anything on the smoothed ones.

**Comment by Synetech** [comment]
I get it, and that's fine, it just looked nice. 🤷

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-web-interface-issue/32166/11

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-web-interface-issue/32166/11

**Comment by maur1th** [comment]
Had a similar issue `pihole -r` fixed it.
