### ISSUE TITLE
Feature request: Allow different DNS for groups

### ISSUE THREAD

**Issue by tmysik** [pi-hole/pi-hole#3355]
In Pihole 5, we have groups now. It would be great if one could specify a different DNS servers for each group (typically, `1.1.1.3` for kids).

Thank you.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by tmysik** [comment]
@dschaper Done, thanks. Let's see...
