### ISSUE TITLE
v5 update broke pihole dashboard domainlist3 error

### ISSUE THREAD

**Issue by frollic** [pi-hole/pi-hole#3356]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

Working dashboard

**Actual behaviour:**

No visible dashboard at all, top three meters are empty, domains in blocklist is completely gone.

![image](https://user-images.githubusercontent.com/7432497/81785772-ff0f0580-94fe-11ea-8284-3426b3817b56.png)

**Steps to reproduce:**

pihole -up  (to v5)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

638kedb6ys

**Troubleshooting undertaken, and/or other relevant information:**

pihole up reported 
**Unable to fill table domainlist3 in database /etc/pihole/gravity.db
Error: column domain is not uniqu**e
in the 3rd stage of the upgrade process.

It might be related, but pihole came 2/3 into the upgrade when it complained about SELinux.
I had to disable it in sysconfig, reboot, and resume. 
Perhaps the stop between 1st and 2nd update attempt broke the update process in some way.. 

I have pihole admin interface running on port 81 instead of 80.
It's also password protected by a httpasswd in lighttpd.conf, since it's exposed to the internet.

auth.backend = "htpasswd"
auth.backend.htpasswd.userfile = "/etc/lighttpd/.htpasswd"
auth.require = ( "/admin/" =>
  (
    "method" => "basic",
    "realm" => "cool access",
    "require" => "valid-user",
  )

**Comment by frollic** [comment]
Ok,

found the solution in the forum.
non unique dns entries on my private filters.
temporarily removed the regex and blacklist files, and the update finished.

dashboard meters are however still empty and/or missing.

**Comment by yubiuser** [comment]
@DL6ER 
Not sure if you follow this thread.
Is the upgrade handling duplicate entries for adlists/domains? Or is it just failing?

**Comment by PromoFaux** [comment]
```
 2020-05-10 12:16:51: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  file(http://127.0.0.1/admin/scripts/pi-hole/php/queryads.php?domain=132.145.210.98:81&amp;bp): failed to open stream: HTTP request failed! 
```

I'm not sure how you're configuring port `81` but in this line from your debug log the `:81` is a the end of the complete URL, not at the end of the domain as it should be `127.0.0.1:81`

I think this may be more of a configuration issue than a software issue. To determine this please temporarily stop your `sniproxy` instance on port `80` and restore the default pi-hole `lighttpd` config to ensure that it is running as expected.

There could be any number of reasons it is not working through your proxy server, but as I don't know your system I can only speculate :)

**Comment by PromoFaux** [comment]
> It's also password protected by a httpasswd in lighttpd.conf, since it's exposed to the internet.

Also, no need for this if you are already using a strong password on the dashboard...

**Comment by frollic** [comment]
Hi,

I haven't.

the only thing I've done is to reconfigure lighttpd to run on port 81
instead of port 80, and up till now worked flawlessly.
But yeah, in retrospect, it might have been smarter to temp kill sniproxy
and reconfigure lighttpd back to port 80 for
the upgrade process.

The proxy isn't related to pihole in any way, it just needs to sit on port
80, that's why I had to set pihole admin to 81.

I'll have additional pi-hole I can try to upgrade, it doesn't have the
proxy on it

**Comment by PromoFaux** [comment]
> I'll have additional pi-hole I can try to upgrade, it doesn't have the proxy on it

OK, try with the additional pi-hole to see if it goes smoothly there (it should, I hope! Provided nothing is misconfigured 😉)

**Comment by frollic** [comment]
Yeah,

that worked flawlessly .... bummer, for me.

**Comment by PromoFaux** [comment]
If you have any questions about setting it up behind a proxy, or using non-default settings for the web interface you can try the new [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category over on our discourse forum. Maybe another user has a similar setup to you and would be able to help.

To redo the upgrade try a `pihole -r` and choose "repair"

**Comment by frollic** [comment]
It's not a proxy (per se), and like I said, I'm not using it for pihole in any way, 
it just happen to run on the same machine.

Found the issue with the graphs too, in Centos php-pdo needs to be installed for SQLite3 support.

**Comment by PromoFaux** [comment]
> in Centos php-pdo needs to be installed for SQLite3 support.

Indeed, it should already have been installed, per the install script:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L290

**Comment by GAS85** [comment]
I have the same problem after update, caused by no `pdo_sqlite`, needs to be installed exactly for sqlite:

    sudo apt install php7.3-sqlite3

> Indeed, it should already have been installed, per the install script

php-pdo is virtual packages it needs to be set exactly if you need sqlite, mysql, or something else.

**Comment by ism** [comment]
Hi,
i tried to install pi-hole today on Ubuntu 18.04 using the following command:
`curl -sSL https://install.pi-hole.net | bash`
After installation finished admin panel didn't work because of missing 'php-sqlite3', so i had to add missing mode manually:
`apt install php-sqlite3`

After that all worked well as expected. I think the script should be updated to explicitly include php-sqlite3.

**Comment by GAS85** [comment]
Funny that basically check for this package is there: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L238

**Comment by yubiuser** [comment]
Did you choose to install the webserver (lighttpd)?
Because `php-sqlite3` as part of WEB_DEPS is only installed if you install the webserer
https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/automated%20install/basic-install.sh#L2592

**Comment by GAS85** [comment]
You right! This is an issue, I have had already a web-server running, so I just added Pihole as sub-path manually to it and did not install with Pihole.
Should we add a note that if you did not install wedserver, please check following dependencies:

    "${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "php-intl" 

https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/automated%20install/basic-install.sh#L250

**Comment by yubiuser** [comment]
This might be a good solution. I know the opinion of the devs is: if you don't install the web server pihole isn't going to install  server dependencies. 
A small note might make this clearer to users. Best would be if you could create a PR - second best maybe a new issue so that it is not buried in this thread.

**Comment by ism** [comment]
On my side, i have used existing apache2 installation for pi-hole. There was no easy way to find out what was causing the stats to not show up. I had to check apache logs first, then i had to run failed script manually to find out whats missing.

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/ is a good place to ask for help in such cases ;-)

**Comment by GAS85** [comment]
Very funny, all needed packages are listed in a documentation. https://docs.pi-hole.net/guides/nginx-configuration/

**Comment by ism** [comment]
Isn't installation script supposed to install everything? I left the message for others who struggle to make it work. Pi-hole installation documentation describes it as one-step install, which it is not.19:01, 24 июня 2020 г., Georgiy Sitnikov <notifications@github.com>:
Very funny, all needed packages are listed in a documentation. https://docs.pi-hole.net/guides/nginx-configuration/

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dschaper** [comment]
@ism If you install `lighttpd` then it will. If not then you have to configure your own. We can't cover every possible user configuration.

**Comment by ism** [comment]
dschaper, that is fine to me. as i said there is no notice about that anywhere on install page, and the error is hard to debug. i added the solution for those who was struggling like me.

**Comment by dschaper** [comment]
It's in the documentation, under prerequisites.
