### ISSUE TITLE
macvendor.db outdated in 5.0

### ISSUE THREAD

**Issue by upD8R** [pi-hole/pi-hole#3358]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**
macvendor.db should have the latest version.

**Actual behaviour:**
There is a version installed with 5.0, which does not include e.g. 48:b0:2d.
 

**Steps to reproduce:**
Install/upgrade pihole to v5.

**Troubleshooting undertaken, and/or other relevant information:**
Bulding an own macevndor.db by executing https://github.com/pi-hole/FTL/blob/master/tools/macvendor.py fails with HTTP 403.

A possible solution (adding header information) is described here:
https://discourse.pi-hole.net/t/macvendor-database-not-updated-with-v5-0/32165/2

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/macvendor-database-not-updated-with-v5-0/32165/8

**Comment by dschaper** [comment]
Fixed. Uploaded current (as of today) macvendor.db file. https://github.com/pi-hole/FTL/pull/763 addresses the 403/404 with a new User Agent.
