### ISSUE TITLE
Domains not part of blocklist or blacklist are getting blocked

### ISSUE THREAD

**Issue by praveenverghese** [pi-hole/pi-hole#3365]
**Expected behaviour:**

To bypass the blocklist

**Actual behaviour:**

Domains not part of blocklist or blacklist are getting blocked

**Steps to reproduce:**

1) Upgraded Pi-hole from V4.4 to V5.0 on latest version of Lubuntu
2) From another system having DNS server as Pihole, for example, open the website http://www.indiatoday.in . You will find all the images on the website being blocked. Images are sourced from domain feeds.intoday.in
3) Opened Tools->query list and checked domain feeds.intoday.in to see if this domain was in block list or blacklist, got empty result.
4) Repeated step 2, same result, all images blocked or not loading.
5) Added feeds.intoday.in to whitelist
6) Repeated step 2, now I can see all the images from the website.

The above behavior is seen on a lot more websites.

**`{Steps of what you have done to fix this}`**

Had to add to whitelist to unblock it and this frequency is rising.

**Comment by yubiuser** [comment]
What does your query log show when you try to access the page? 
Maybe it was blocked due to the deep CNAME inspection introduced in v5.0?

**Comment by praveenverghese** [comment]
I watched the "tail pihole.log" on the Pihole web admin and also watched the pihole.log on the linux OS, surprisingly didn't find any entry for the blocked domain name. How do I know if it was blocked by deep CNAME inspection?

**Comment by yubiuser** [comment]
Look at the Web GUI Query Log

**Comment by praveenverghese** [comment]
Looks like the deep CNAME inspection is blocking the websites which is causing all the issues. Today I opened the website moneycontrol.com and I could not open the website. No entries in either blacklist or blocklist.
Checked the query list and found this 
![image](https://user-images.githubusercontent.com/65300537/81897979-54b5e180-95d5-11ea-89d8-04753774ebc7.png)
Can someone explain me how the deep CNAME inspection logic exactly works. It has started to block all the websites which has a related link to a domain that is in the blocklist, for example blocked domain "akamaiedge.net" in the above example. This has become an administrative nightmare, as I need to keep adding a lot into the whitelist every now and then. Is there a way to disable CNAME deep inspection?

Thanks,
Praveen

**Comment by dschaper** [comment]
`www.moneycontrol.com` is a CNAME for `e13203.dsca.akamaidege.net`:

```plain
;; ANSWER SECTION:
www.moneycontrol.com.   296     IN      CNAME   www.moneycontrol.com.edgekey.net.
www.moneycontrol.com.edgekey.net. 577 IN CNAME  e13203.dsca.akamaiedge.net.
e13203.dsca.akamaiedge.net. 16  IN      A       23.52.176.131
```

It looks like you have told Pi-hole to block ` e13203.dsca.akamaiedge.net`, possibly with a regex blacklisting. Pi-hole is doing what it was asked to do and blocks that domain.

**Comment by praveenverghese** [comment]
Thanks.

This is not how it behaved in version 4.4.

however, I changed the blacklist entry from 

![image](https://user-images.githubusercontent.com/65300537/81899865-66998380-95d9-11ea-9045-6ecf8812fc4b.png)

to

![image](https://user-images.githubusercontent.com/65300537/81899939-8466e880-95d9-11ea-8cb0-856434d9d2eb.png)

and now I can open moneycontrol website.

How will my blacklist entry behave now? does it mean that any query for matching exactly "akamaiedge.net" will be blocked and not wildcard "*.akamaiedge.net" , which means subdomains for akamaiedge.net will not be blocked?

Thanks,
Praveen

**Comment by PromoFaux** [comment]
To have the entry as an `Exact blacklist` entry, you need to remove the regex syntax, as it is now being read literally. So you'll either need to set it back as a regex entry, or change it to `akamaedge.net`. As you rightly pointed out, though, this will just be blocked and not subdomains.

Indeed, 4.4 did not have deep CNAME blocking, this is a new feature in 5.0 as described in the announce post.

If you really wish to disable it, you can follow the instructions in the documentation here:

https://docs.pi-hole.net/ftldns/configfile/#dns-settings

**Comment by praveenverghese** [comment]
Thank you so much. This helps....
