### ISSUE TITLE
unable to complete update, please contact Pi-Hole support

### ISSUE THREAD

**Issue by nobody-DE** [pi-hole/pi-hole#3368]
Hello,
I got an error message during the update vom v4 to v5.:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.0-xml
E: Couldn't find any package by glob 'php7.0-xml'
E: Couldn't find any package by regex 'php7.0-xml'

Unable to complete update, please contact Pi-hole Support

I´m running a RasPi 3 with an up-to-date Debian Buster

Any hints for my? Thx!

**Comment by rakunt** [comment]
same here:

	root@RaspOld:~ # pihole -up
	  [i] Checking for updates...
	  [i] Pi-hole Core:	up to date
	  [i] Web Interface:	up to date
	  [i] FTL:		update available

	  [i] FTL out of date, it will be updated by the installer.

	  [✓] Root user check

			.;;,.
			.ccccc:,.
			 :cccclll:.      ..,,
			  :ccccclll.   ;ooodc
			   'ccll:;ll .oooodc
				 .;cll.;;looo:.
					 .. ','.
					.',,,,,,'.
				  .',,,,,,,,,,.
				.',,,,,,,,,,,,....
			  ....''',,,,,,,'.......
			.........  ....  .........
			..........      ..........
			..........      ..........
			.........  ....  .........
			  ........,,,,,,,'......
				....',,,,,,,,,,,,.
				   .',,,,,,,,,'.
					.',,,,,,'.
					  ..'''.

	  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u5
	  [i] Performing unattended setup, no whiptail dialogs will be displayed
	  [✓] Disk space check
	  [✓] Update local cache of available packages

	  [✓] Checking apt-get for upgraded packages... up to date!

	  [i] Installer Dependency checks...
	  [✓] Checking for dhcpcd5
	  [✓] Checking for git
	  [✓] Checking for iproute2
	  [✓] Checking for whiptail

	  [i] SELinux not detected
	  [i] Performing reconfiguration, skipping download of local repos
	  [✓] Resetting repository within /etc/.pihole...
	  [✓] Resetting repository within /var/www/html/admin...
	  [i] Main Dependency checks...
	  [✓] Checking for cron
	  [✓] Checking for curl
	  [✓] Checking for dnsutils
	  [✓] Checking for iputils-ping
	  [✓] Checking for lsof
	  [✓] Checking for netcat
	  [✓] Checking for psmisc
	  [✓] Checking for sudo
	  [✓] Checking for unzip
	  [✓] Checking for wget
	  [✓] Checking for idn2
	  [✓] Checking for sqlite3
	  [✓] Checking for libcap2-bin
	  [✓] Checking for dns-root-data
	  [✓] Checking for libcap2
	  [✓] Checking for lighttpd
	  [✓] Checking for php7.0-common
	  [✓] Checking for php7.0-cgi
	  [i] Checking for php7.0-sqlite (will be installed)
	  [i] Checking for php7.0-xml (will be installed)
	  [i] Checking for php-intl (will be installed)
	  [i] Processing apt-get install(s) for: php7.0-sqlite php7.0-xml php-intl, please wait...
	----------------------------------------------------------------------------------------
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	E: Unable to locate package php7.0-sqlite
	E: Couldn't find any package by glob 'php7.0-sqlite'
	E: Couldn't find any package by regex 'php7.0-sqlite'
	E: Unable to locate package php7.0-xml
	E: Couldn't find any package by glob 'php7.0-xml'
	E: Couldn't find any package by regex 'php7.0-xml'

	root@RaspOld:~ # apt-cache policy php-xml
	php-xml:
	  Installed: 2:7.3+69
	  Candidate: 2:7.3+69
	  Version table:
	 *** 2:7.3+69 750
			750 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
			750 http://mirrordirector.raspbian.org/raspbian buster/main armhf Packages

	root@RaspOld:~ # apt-cache policy php-sqlite3 
	php-sqlite3:
	  Installed: 2:7.3+69
	  Candidate: 2:7.3+69
	  Version table:
	 *** 2:7.3+69 750
			750 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
			750 http://mirrordirector.raspbian.org/raspbian buster/main armhf Packages

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
