### ISSUE TITLE
Last entry in adlist.default blocks rendering for kat.cr

### ISSUE THREAD

**Issue by tdkl** [pi-hole/pi-hole#337]
After testing all the new added lists in commit https://github.com/pi-hole/pi-hole/commit/b2fbf46e605c6f316a9e759a6694f23a8332393e it seems that the https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt is blocking rendering of https://kat.cr. 

Since there was already a removal for one of the newly added lists in commit https://github.com/pi-hole/pi-hole/commit/f8897942f3e7e13335247af7a7ada666349a000f , which broke https://feedly.com, I don't know if it's wise to just add lists without thorough testing, unless all sites that aren't http://disney.com are now malware.

**Comment by Mcat12** [comment]
We try to [test](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) all of the lists that we include as default. Sometimes, yes, these lists do block sites that do not need to be blocked, but you can [whitelist](https://github.com/pi-hole/pi-hole/wiki/Whitelisting-and-Blacklisting) (and blacklist) any domains that you want. We only add lists when we think they will benefit Pi-hole users, and only remove lists when we feel that the list does more harm than good.

**Comment by PromoFaux** [comment]
The list we removed was blanket blocking porn. Surprisingly, in an all male dev team, we hadn't noticed that during testing!

As for kat.cr, `whitelist.sh a.kickass.to katstatic.com` will render kat properly. I hadn't noticed that one myself as all my totally legitimate downloading (ahem) is done automatically via scripts on another server.

**Comment by tdkl** [comment]
@PromoFaux : Thanks for the prompt reply, whitelisting those two domains seems to have done the job. 

Problem with whitelisting is that it's hard to know which domain name to actually whitelist, since obviously the one you access isn't enough :/

Nevertheless I'll mark this as closed and make sure I'll whitelist in the future or just stick to the custom adlists.list as proposed in the wiki @Mcat12 posted. Thanks again !

**Comment by PromoFaux** [comment]
For future reference.. [this is a really handy extension for chrome](https://chrome.google.com/webstore/detail/whitelist-assistant-by-dn/fdmpekabnlekabjlimjkfmdjajnddgpc)

**Comment by tdkl** [comment]
Oh, this seems really handy indeed, thank you. 

Perhaps it would be nice if it was also mentioned in the Wiki in the White/Blacklisting section.

**Comment by PromoFaux** [comment]
It is mentioned on the pi-hole.net faq's/blog.

We're in the process of updating the wiki etc so that it's packed full of useful information! 

Feel free to add information as you see fit..!

**Comment by lokenx** [comment]
Just for the record I think the URL may have changed, the below worked for me:
```
whitelist.sh a.kickass.to kastatic.com
```

**Comment by Wibbles42** [comment]
As of today's date, I also had to add counter.yadro.ru to the whitelist for Kat.cr to render correctly.
Take that as you will...
