### ISSUE TITLE
Issue: v5 Local DNS Records do not resolve if same entry exists in local hosts file

### ISSUE THREAD

**Issue by jennec** [pi-hole/pi-hole#3370]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Add a record to the Local DNS Records Page and click Add.  
Restart DNS Server
resolve DNS record to value stored in "Local DNS Records" page over any records stored in local OS hosts file

**Actual behaviour:**
Add a record to the Local DNS Records Page and click Add.  
Restart DNS Server
Reolved DNS entry from local OS Hosts file instead of "Local DNS Records" page.

`{A detailed description and/or screenshots of what you do see}`
As above

**Steps to reproduce:**
Create DNS entry in local OS host file
Create the same DNS record in "Local DNS Records" page (with different IP address)
Restart DNS resolver
Ping address from client device.
Observe DNS record resolved from local OS host file with different IP than that listed in "Local DNS Records" page.

Flushing clients client DNS cache does not resolve the issue.  Resolution of entries from the local OS host file take precedence over "Local DNs Records" entries in PiHole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

pioru7fdn5

Be advised when resolution from the local hosts file ocurrs no debug information is present.

**Troubleshooting undertaken, and/or other relevant information:**

**Comment by yubiuser** [comment]
The intended behavior is
https://discourse.pi-hole.net/t/custom-dns-observations/27533/18?u=yubiuser

but the devs might be open to change it.

**Comment by jennec** [comment]
Might be worth putting a disclaimer on the "Local DNS Records" page to advise this, to avoid confusion going forward.

**Comment by tlorens** [comment]
Pi-Hole creates a custom.list in the same format as /etc/hosts  there's also a local.list file which contains the contents of /etc/hosts.  But nowhere in the dnsmasq configuration is the custom.list file referenced.  So custom.list never gets parsed/loaded.

**Comment by jfb-pihole** [comment]
> nowhere in the dnsmasq configuration is the custom.list file referenced. So custom.list never gets parsed/loaded.

Pi-hole installs file _**/etc/dnsmasq.d/01-pihole.conf**_ containing the following lines:

```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list
```

**Comment by tlorens** [comment]
> > nowhere in the dnsmasq configuration is the custom.list file referenced. So custom.list never gets parsed/loaded.
> 
> Pi-hole installs file _**/etc/dnsmasq.d/01-pihole.conf**_ containing the following lines:
> 
> ```
> addn-hosts=/etc/pihole/local.list
> addn-hosts=/etc/pihole/custom.list
> ```

My fresh install v5 does not contain those lines.  

```
addn-hosts=/etc/pihole/gravity.lost
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/black.list

```

**Comment by dschaper** [comment]
https://aur.archlinux.org/packages/pi-hole-server/?O=10&PP=10#pinned-633053

**Comment by tlorens** [comment]
> https://aur.archlinux.org/packages/pi-hole-server/?O=10&PP=10#pinned-633053
> 
> > max.bra commented on 2018-02-09 16:45
> 
> > ArchLinux Pi-hole is not officially supported by Pi-hole project. In case of bugs and malfunctions please DO NOT file a report upstream.
> 
> > First of all check if the wiki (https://wiki.archlinux.org/index.php/Pi-hole) can help then ask here for assistance and tips.
> > When it will be excluded that the problem does not depend on ArchLinux we will file a bug upstream.

Didn't realize the dnsmasq.conf stuff was related to Archlinux or I wouldn't have filed a bug. Duh

**Comment by PromoFaux** [comment]
I've not kept track of the changes they have made to Pi-hole to make it work on arch, but it's not an operating system that any of the core developers have an experience with.

As you can see your file differs from what we would expect, so it's possible that the aur package is found something wrong here....

Also of note, neither `gravity.list` or `black.list` are used by Pi-hole since v5
