### ISSUE TITLE
Network: "An unknown error occured while loading the data."

### ISSUE THREAD

**Issue by LIyoai** [pi-hole/pi-hole#3371]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No error

**Actual behaviour:**

Error "An unknown error occured while loading the data."

**Steps to reproduce:**

Updated from 4.4 to 5.0.
When I go to Network in the webinterface I get a popup "An unknown error occured while loading the data."
Also uninstalled pihole and installed again.
Running Debian 10.4

**Comment by LIyoai** [comment]
Installing php-sqlite3 solved my issues.

**Comment by DAKarp** [comment]
I had the same exact issue. Isn't it a bug in the pi-hole 5 installer if a dependency isn't installed?

**Comment by dschaper** [comment]
Could be, or could be something else. Hard to tell without any kind of information to guess at.

**Comment by dschaper** [comment]
Are you running `ngnix` like the issue report was?

**Comment by DAKarp** [comment]
Nope, running lighttpd. Multiple uninstalls and reinstalls made no difference.

**Comment by DAKarp** [comment]
But it’s worth noting that if you decline the lightttpd option while setting up pi-hole, the installer fails to install or update PHP. I haven’t filed a ticket for this yet because I don’t have enough to back it up, but it’s happened to me several times. That might be related to the php-sqlite3 issue.

**Comment by yubiuser** [comment]
> But it’s worth noting that if you decline the lightttpd option while setting up pi-hole, the installer fails to install or update PHP. I haven’t filed a ticket for this yet because I don’t have enough to back it up, but it’s happened to me several times. That might be related to the php-sqlite3 issue.

https://github.com/pi-hole/pi-hole/pull/3225

**Comment by dschaper** [comment]
Yeah, if you don't install a webserver then we don't see the need to install webserver dependencies. You should be able to do that on your own.

**Comment by DAKarp** [comment]
Of course the problem here is that even if you do install the web server, it doesn’t install all the dependencies

**Comment by dschaper** [comment]
So, you did or did not decline `lighttpd` when installing pi-

**Comment by dschaper** [comment]
Here's the web dependencies, if you have the installer handle `lighttpd` then it's all done in one go. If you don't, the we don't install `lighttpd` and you control all the packages. We don't take over a pre-existing configuration and manage it for you.

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L250

**Comment by DAKarp** [comment]
I declined at first, because I already had a Web server running with pi-hole 4. But then, when it didn’t work (many errors on web ui), I uninstalled and reinstalled with the lighttpd option enabled. When I then encountered the same problem, I discovered this post, manually installed php-sqlite3, and then it worked.

So, to sum up: even if you install lighttpd, the php-sqlite3 dependency is not installed.

**Comment by dschaper** [comment]
When you uninstalled, did you remove the `/etc/pihole/setupVars.conf` file that has:

```plain
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
```

Or did you leave it with `INSTALL_WEB_SERVER=false`?

I guess it is possible that every user has needed to add that package to get their web interfaces working...

**Comment by DAKarp** [comment]
I wasn’t aware of that config file or the need to remove it manually after uninstalling pi-hole. But that would explain why reinstalling didn’t fix any problems.

As for other users, I can only speculate that the module is installed with PHP. But if it’s not explicitly listed as a dependency for pi-hole, many other people are going to run into this issue unless they’re installing for the first time on a clean system.

Seems to me it couldn’t hurt to list this module as an explicit dependency.

**Comment by PromoFaux** [comment]
> wasn’t aware of that config file or the need to remove it manually after uninstalling pi-hole.

Whilst the uninstall script isn't perfect (note to self, really should give it a proper look over at some point) it does clean up this file:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/uninstall.sh#L149
