### ISSUE TITLE
Group management error

### ISSUE THREAD

**Issue by LIyoai** [pi-hole/pi-hole#3372]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No error

**Actual behaviour:**

DataTables warning: table id=groupsTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Steps to reproduce:**

Updated from 4.4 to 5.0.
When I go to Group management in the webinterface I get a popup "DataTables warning: table id=groupsTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7"
Also uninstalled pihole and installed again.
Running Debian 10.4

**Comment by PromoFaux** [comment]
Please try clearing your browser cache and reloading the page. Likely it is the js left over from v4.4

`CTRL+F5` should do it

**Comment by LIyoai** [comment]
Already tried this. Also "forget about this site" in Firefox and to be sure tested now in Chromium.
Still not working

**Comment by PromoFaux** [comment]
Hmm, OK , well for starters I can assure you the page works. Please can you provide a debug token using `pihole -d` and I can take a closer look at your Pi-hole configuration. thanks

**Comment by usersylvio** [comment]
Hi, its the same after upgrade to 5.0. If there any possibility to make a fresh installation form 4.xx? I love the pi hole easy to install and to maintain. But i think i was to fast to upgrade to 5. 
I removed the PH installation and installed a new one. But the same issue. 
Here is my debug token. https://tricorder.pi-hole.net/6th93ba45o

**Comment by PromoFaux** [comment]
@usersylvio This is why you are seeing the issue:

> [✗] lighttpd daemon is inactive
> Server: nginx

only `lighttpd` is an officially supported webserver at this time.

Please see our [community help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) forums, where I know that there are some people that have faced and solved the same issue with `nginx`

**Comment by LIyoai** [comment]
Thanks for the hint. I'm running on apache.
Installing php-sqlite3 solved my issues.

**Comment by usersylvio** [comment]
@PromoFaux Thanks for you answer. I wont use lighhttpd with pihole. On this server are running other services. And is there any possibility to install the former version (latest 4) from scratch? It wold be very nice. 
Actually i have no Pi Hole to run.

**Comment by PromoFaux** [comment]
There is nothing stopping you from using `nginx` or `apache2` or whatever other web server you wish to run, the base issue is that we currently don't support it officially. 

From what I have seen, the additional packages needed to get it running with nginx are `php7.3-xml`, `php7.3-sqlite3`, and `php7.3-intl`

**Comment by usersylvio** [comment]
Ohhhh thank you @PromoFaux for your answer. Now i have switched to php7.3-fpm and installed php7.3-xml, php7.3-sqlite3 and php7.3-intl.

```
php7.3-xml is already the newest version (7.3.11-0ubuntu0.19.10.4)
php7.3-intl is already the newest version (7.3.11-0ubuntu0.19.10.4)
php7.3-sqlite3 is already the newest version (7.3.11-0ubuntu0.19.10.4)

php -v
PHP 7.3.11-0ubuntu0.19.10.4 (cli) (built: Apr  8 2020 18:58:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.4, Copyright (c) 1999-2018, by Zend Technologies
```
And padapow PiHole is alive on nginx.

Thank you so much @PromoFaux. Do you have paypal for your coffee cup? ;-)

**Comment by PromoFaux** [comment]
https://pi-hole.net/donate

Thanks!

**Comment by lkwilson** [comment]
I ran into this issue with the latest install. I fixed it with 
```
sudo chmod g+r /etc/pihole/gravity.db
```

**Comment by mpardalos** [comment]
I also ran into this issue. It seems that the problem was connecting to the Web UI using http://pi.hole instead of  http://<ip-address>. Connecting with the IP address fixed it.
