### ISSUE TITLE
upgrade v5 error

### ISSUE THREAD

**Issue by it-can** [pi-hole/pi-hole#3375]
on my pihole v5 is tried upgrading but get this error....

```
[✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Checksums do not match, downloading from ftl.pi-hole.net.
  [i] Downloading and Installing FTL...pihole-FTL-arm-linux-gnueabihf: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
  [✗] Downloading and Installing FTL
  Error: Download of https://ftl.pi-hole.net/release/v5.0/pihole-FTL-arm-linux-gnueabihf failed (checksum error)
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support
```

**Comment by PromoFaux** [comment]
@MCX513 Looking at the version of your PHP, I am guessing you are on an older version of debian/raspbian. 

If you are running a later version such as stretch or buster, then please open a new issue and we will aim to help you resolve it. However, if you are on Jessie, for example, then please first upgrade to a later version of raspbian/debian.

Cheers

**Comment by MCX513** [comment]
Thanks
That solved the problem eventually
