### ISSUE TITLE
Local DNS records are not exported/imported using teleporter

### ISSUE THREAD

**Issue by spfmoby** [pi-hole/pi-hole#3376]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
when using teleporter the Local DNS records should be exported/imported

**Actual behaviour:**
when using teleporter the Local DNS records are not exported/imported

**Steps to reproduce:**
1/ create some Local DNS records
2/ export a backup of the whole pihole configuration using teleporter
3/ remove the local DNS records
4/ import the backup made at step 3
5/ The Local DNS records are not restored

**Comment by DL6ER** [comment]
This has been fixed by https://github.com/pi-hole/AdminLTE/pull/1276 and will be shipped with Pi-hole v5.1

**Comment by spfmoby** [comment]
Sorry, I checked the "issues" for duplicates but forgot the already "closed" pull requests. My bad.
Thanks
