### ISSUE TITLE
Not all local hostnames are resolved correctly

### ISSUE THREAD

**Issue by simphide** [pi-hole/pi-hole#3377]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

**Expected behaviour:**

All local hostname will be resolved correctly
![image](https://user-images.githubusercontent.com/8183517/81967211-e3991d00-961a-11ea-9330-9950793c7b91.png)

**Actual behaviour:**

For some devices Pi-hole resolves the "originial" hostname
![image](https://user-images.githubusercontent.com/8183517/81967345-12af8e80-961b-11ea-8a81-84649b45bfbf.png)

I changed the local hostnames in my FritzBox about 1 month ago, but the pi-hole doesn't resolve all modified hostnames. Only the hostnames of devices which are connected over 5G...

**Comment by dschaper** [comment]
Please visit https://discourse.pi-hole.net for assistance with your configuration.

**Comment by simphide** [comment]
I acutally don't think that it is anything config related since it works for half of the devices...

**Comment by dschaper** [comment]
If it works for half the devices then Pi-hole is working. You need assistance with the full configuration of all the network devices to get things to where you want them. That's what Discourse is perfect for.
