### ISSUE TITLE
return to old blocklist management

### ISSUE THREAD

**Issue by BulldozerPete** [pi-hole/pi-hole#3379]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Return to old blocklist management, when you could import several blocklists without error.

**Actual behaviour:**
Can't import blocklists from here https://v.firebog.net/hosts/lists.php?type=tick in a single ctrl-c and ctrl-v task.

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment]
Whats the error message?

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/how-to-add-blocklists-v5-and-later/32127/20

**Comment by BulldozerPete** [comment]
Error message is:
![error](https://user-images.githubusercontent.com/61943052/82072214-9dee5a00-96d7-11ea-9a51-176d45956e29.png)

**Comment by dschaper** [comment]
One of the lists you are trying to add is already being used.

**Comment by BulldozerPete** [comment]
And therefore none of the others will be added?

**Comment by PromoFaux** [comment]
We may have a bug that hard fails at this point, it's current being investigated. 

Can you check the list you are pasting in for duplicates, first, remove them and then paste into the box again to see if it works please?

**Comment by BulldozerPete** [comment]
Now it worked.
I do recommend to fix that bug that you can't add duplicates. Instead of an error I would like to receive a notification.

**Comment by ImJksn** [comment]
Had the same issue last week, but what PromoFaux recommended works. If you have duplicates in the list, all the entries before the duplicate are added, and none after. Removing that duplicate solves problem.

**Comment by nicolasvac** [comment]
Hello, i have the same issues. But the problem is that the list is not duplicated.
Everything i type in just fails. 
![Schermata 2020-06-05 alle 12 37 45](https://user-images.githubusercontent.com/45635090/83867355-94ca3900-a729-11ea-9f26-53f7f5d8dae3.png)

**Comment by yubiuser** [comment]
Please post the address you wanted to add and the output of 
`sqlite3 /etc/pihole/gravity.db "Select id, address from adlist order by id;"`

**Comment by BulldozerPete** [comment]
I don't know why it became so complicated. Prior to version 5.0 you could add hundreds of list at once. If you had one or more of them already in your list, nothing happened.
Now I have to check each error and remove the list from list I would like to add. That is time-consuming and prevents me from adding lists.

**Comment by yubiuser** [comment]
It became so complicated, because pihole switched to the database which enabled a lot of features (like group management). One restriction is that you are not able to add the same adlist URL twice. With pihole 5.1, pihole won't fail hard if you try to add an adlist that is already in your database - meaning you can copy&paste a lot of lists and duplicates will just "skipped"

https://github.com/pi-hole/AdminLTE/pull/1449

**Comment by BulldozerPete** [comment]
@yubiuser Any idea when version 5.1 will go live?

**Comment by PromoFaux** [comment]
When it's ready ;), the closest answer I can give is [soon™](https://wowwiki.fandom.com/wiki/Soon)

**Comment by yubiuser** [comment]
Can be closed, v5.1. has been released.
