### ISSUE TITLE
[Feature request] Remove orphan clients from Pi-Hole / update DNS names

### ISSUE THREAD

**Issue by marsmichelmann** [pi-hole/pi-hole#3381]
While configuring the group managment and creating some clients entries for my Pi Hole 5 installation, I came up with the following suggestions for improvement:

1. It would be nice to be able to delete orphan clients, which were not present in the network for a certain time via admin gui automatically. Currently it's seems like it's only possible via direct database access: https://discourse.pi-hole.net/t/deleting-a-client-from-the-database/14438

2. Furthermore it would be nice trigger a DNS name resolution via the admin gui.

**Comment by yubiuser** [comment]
Please open feature requests at discourse.

**Comment by marsmichelmann** [comment]
Ok, done. Sorry, didn't know that Github is just a bug tracker.

**Comment by dschaper** [comment]
From the template that was ignored:

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
