### ISSUE TITLE
cannot save setting via web interface

### ISSUE THREAD

**Issue by gmum4d** [pi-hole/pi-hole#3384]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{update settings}`

**Actual behaviour:**

`{I have installed pinhole on my HOOBS box.  Installation went fine but I cannot save any of my settings.  I think this is because its running on HOOBS.  I had to change the port pinhole was running on and I did this via the HOOBS terminal, but I had to "sudo" to allow me to save the changes to lighted.conf, so I assume I cannot make changes via the web interface because it requires "sudo" to save configs.  How do I fix it so I can use the web interface? }`

**Steps to reproduce:**

`{Install alongside HOOBS}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{ppn67ge7nb}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
```
[80] is in use by nginx (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
```

Take a look through the [Community Forums](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) Where you are likely to find some advice on setting up Pi-hole to work with `nginx`

**Comment by gmum4d** [comment]
I’m Running the latest HOOBS that no longer has nginx
