### ISSUE TITLE
Broken authorizedHosts check on block page

### ISSUE THREAD

**Issue by RenWal** [pi-hole/pi-hole#3385]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

When the [block page](https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php) is triggered, only hosts in `$authorizedHosts` should cause the splash page with the link to the admin panel to be shown.

**Actual behaviour:**

The splash page is always shown because of the following issue with the selection logic:

Setting the FQDN Flag (`$_SERVER["FQDN"]`) as described in the [nginx tutorial](https://docs.pi-hole.net/guides/nginx-configuration/) will cause the current server name to be pushed into the list of authorized hosts in this line:
https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/index.php#L31
When deciding whether to show the block page or splash page, this list of authorized hosts is checked against that same current server name:
https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/index.php#L57

It seems logical that `in_array($serverName, $authorizedHosts)` will always evaluate to True if we do `array_push($authorizedHosts, $serverName)` before, so that doesn't look right to me.

**Steps to reproduce:**

- install Pi-hole
- follow the [nginx tutorial](https://docs.pi-hole.net/guides/nginx-configuration/)
- set the blocking mode to [ip blocking](https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-full-ip-blocking) to enable the block page
- visit any blocked page (I manually blacklisted `piholetest.example.com` for the demo)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

not applicable

**Troubleshooting undertaken, and/or other relevant information:**

Removing the FQDN flag from the nginx tutorial makes the block page work (if you work around [that problem](https://github.com/pi-hole/pi-hole/pull/3263#issuecomment-629208703) with the nginx configuration by setting `VIRTUAL_HOST`). Still, that does not remove the bug but only works around it.

**Comment by dschaper** [comment]
`nginx` is a community supported webserver. The guide notes: "This is an unsupported configuration created by the community.", updating the documentation is the way to go forward.

**Comment by RenWal** [comment]
As far as I understand, this issue will be reproducible _without_ nginx. It's just the way I stumbled upon the FQDN flag. Setting that flag on another (supported) webserver should yield the same result. It doesn't change the fact that the logic is (in my mind) incorrect.
