### ISSUE TITLE
FTL download fail CURL SSL_ERROR_SYSCALL Error

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#3387]
> @PromoFaux The thing I've asked that questions is that now I have my pihole completely dead w/o any chance to install it as it still stucks.
So, I'd appreciate any way to either manually download packages and install or switch to a branch before 5.0, cause it worked fine.
If there any useful info that I may grab from my orangepi or any logs - just give me the hints or instructions.

_Originally posted by @AlexanderPoleschuk in https://github.com/pi-hole/pi-hole/issues/3378#issuecomment-629330609_

@AlexanderPoleschuk let's continue the discussion here, as it is unrelated to the other issue

**Comment by PromoFaux** [comment]
What is the output of the following command on your Pi terminal?

```
curl -sSL --fail https://github.com/pi-hole/FTL/releases/latest/download/pihole-FTL-aarch64-linux-gnu
```

**Comment by lAnubisl** [comment]
I do have the same issue. The output of the command you posted is empty.

**Comment by PromoFaux** [comment]
Empty is expected, that means no errors. So, I would appreciate from either of you here a _complete_ output of the following command:

```
sudo bash -x /etc/.pihole/automated\ install/basic-install.sh
```

If you are prompted, please select "Update" at the dialog.

This is expected to be a very long output, please upload it to something like pastebin, or attach it to your reply as a file. Cheers

**Comment by lAnubisl** [comment]
@PromoFaux [output.txt](https://github.com/pi-hole/pi-hole/files/4635640/output.txt)

**Comment by lAnubisl** [comment]
Here you go

[output.txt](https://github.com/pi-hole/pi-hole/files/4635749/output.txt)

**Comment by PromoFaux** [comment]
OK, there's a bizarre amount of whitespace for some reason in the download command. Can you please paste the output of this command (from the home directory):

```
curl -sSL --fail https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabi -o pihole-FTL-arm-l                                                                                                           inux-gnueabi
```

and then this one:

```
curl -sSL --fail https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabi -o pihole-FTL-arm-linux-gnueabi
```

**Comment by AlexanderPoleschuk** [comment]
mine one. it stuck at last line and based on previous experience - would hang on that operation for a long time.

[output.txt](https://github.com/pi-hole/pi-hole/files/4635871/output.txt)

**Comment by PromoFaux** [comment]
OK, yours at least does not have the same whitespace issue.

Can you manually run this in your home directory please and see if it completes...

```
curl -sSL --fail https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu -o pihole-FTL-aarch64-linux-gnu
```

It should end up with a file named `pihole-FTL-aarch64-linux-gnu` existing in your home directory...

**Comment by AlexanderPoleschuk** [comment]
Now it might sound really silly... but it finally installed with `sudo bash -x /etc/.pihole/automated\ install/basic-install.sh` command you've provided. Not sure what is going on...
` curl -sSL --fail https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu -o pihole-FTL-aarch64-linux-gnu` is still hanging in progress.

**Comment by PromoFaux** [comment]
I think it's safe, in your case, to put this down to a connectivity issue. Point to research would be the `SSL_ERROR_SYSCALL` failure in `curl`, specifically with `errno 104`. All we are doing at this point in the code is returning the error from `curl`.

I say this with no authority, and I may be totally off the mark, but sometimes SSL errors can be caused by the date/time on your device being wrong.

**Comment by AlexanderPoleschuk** [comment]
And the file finally downloaded. checked the date on device - seems to be correct. but, yes, sometimes SSL glitches even when there is a several seconds difference..

**Comment by lAnubisl** [comment]
I was able to update too. 
[output.txt](https://github.com/pi-hole/pi-hole/files/4636987/output.txt)

however my web interface port setting was reset to default 80

**Comment by dschaper** [comment]
Yes, if you take a look at the `lighttpd.conf` file it says at the top that any changes will be reverted back.

**Comment by dschaper** [comment]
This looks resolved. Closing.
