### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by jorisvervuurt** [pi-hole/pi-hole#3392]
As Pi-hole v4.x apparently wasn’t compatible with the latest Ubuntu 20.04 release, I wonder if the recently released v5.x is?

Can’t seem to find it anywhere, so would like someone to confirm before I clean-install my NUC which is now running 18.04... thanks! 😁

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-says-its-runing-but-cant-get-in-to-admin-or-block-site-in-termial/35420/16
