### ISSUE TITLE
[Feature Request] Permit different Resolver depending client

### ISSUE THREAD

**Issue by bartounet16** [pi-hole/pi-hole#3393]
Would it be possible to allow different configurations depending client which is doing the dns request

For example I would like Pihole's DNS resolver for some clients to be my internal router

and for other clients I would like Pihole's dns resolver to be OpenDNS

For the moment it is necessary to install 2 pihole to meet this need.

**Comment by yubiuser** [comment]
Please open feature restquest on discourse.
https://discourse.pi-hole.net/c/feature-requests

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/different-resolver-dns-option-by-client/11748
