### ISSUE TITLE
FTL will not update to 5

### ISSUE THREAD

**Issue by jimmirehman** [pi-hole/pi-hole#3394]
When trying to update pi-hole on Pi-ZeroW, the FTL will not update

php: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: no version information available (required by php)
  [i] Existing PHP installation detected : PHP version 
php: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: no version information available (required by php)
php: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: no version information available (required by php)
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 200 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php-common
  [✓] Checking for php-cgi
  [✓] Checking for php-sqlite3
  [i] Checking for php-xml (will be installed)
  [i] Checking for php-intl (will be installed)
  [i] Processing apt-get install(s) for: php-xml php-intl, please wait...
--------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  php7.0-cgi php7.0-cli php7.0-common php7.0-intl php7.0-json php7.0-opcache
  php7.0-readline php7.0-sqlite3 php7.0-xml
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php-intl php-xml php7.0-intl php7.0-xml
The following packages will be upgraded:
  php7.0-cgi php7.0-cli php7.0-common php7.0-json php7.0-opcache
  php7.0-readline php7.0-sqlite3
7 upgraded, 4 newly installed, 0 to remove and 210 not upgraded.
Need to get 0 B/2,869 kB of archives.
After this operation, 786 kB of additional disk space will be used.
Segmentation fault
E: Sub-process /usr/bin/apt-listchanges --apt || test $? -lt 10 returned an error code (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10

  Unable to complete update, please contact Pi-hole Support
pi@Pi-Hole:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
pi@Pi-Hole:~ $

**Comment by dschaper** [comment]
> [✓] Checking apt-get for upgraded packages... 200 updates available

Have you ever run `apt-get update`? There's a very large number of packages to update that should have been updated during your regular maintenance of the Raspberry Pi.

**Comment by jimmirehman** [comment]
> > [✓] Checking apt-get for upgraded packages... 200 updates available
> 
> Have you ever run `apt-get update`? There's a very large number of packages to update that should have been updated during your regular maintenance of the Raspberry Pi.

Running now, hope this is the solution, thanks.

**Comment by jimmirehman** [comment]
> Have you ever run `apt-get update`? 

This fixed the issue. thank you! up and running again
