### ISSUE TITLE
cannot add url with underscores in adlist

### ISSUE THREAD

**Issue by MartinHaimberger** [pi-hole/pi-hole#3395]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Expected to add https://phishing.army/download/phishing_army_blocklist_extended.txt as source.

Trying to add https://phishing.army/download/phishingarmyblocklistextended.txt seems to be accepted, so its seems that the underscores seems to be a problem

**Actual behaviour:**

Error message which tells failing constraint.

**Steps to reproduce:**

add https://phishing.army/download/phishing_army_blocklist_extended.txt

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

**Troubleshooting undertaken, and/or other relevant information:**

trying to add https://phishing.army/download/phishingarmyblocklistextended.txt wihtout underscores seems to be accepted ...

**Comment by yubiuser** [comment]
It's working for me.
![Bildschirmfoto zu 2020-05-17 16-19-32](https://user-images.githubusercontent.com/26622301/82150958-45939580-985a-11ea-9693-f5f9cbcd0a5d.png)

**Comment by MartinHaimberger** [comment]
after restart of pihole it worked also for me, thx
