### ISSUE TITLE
Unbound not resolving AmazonS3 subdomains

### ISSUE THREAD

**Issue by yukdumboobumm** [pi-hole/pi-hole#3396]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{2}`

---
**Expected behaviour:**

`dig get.docker.com` resolves A records

**Actual behaviour:**

`dig get.docker.com` returns `NOERROR` but zero `ANSWERs`

```
:~ $ dig get.docker.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> get.docker.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1630
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;get.docker.com.                        IN      A

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun May 17 07:59:33 PDT 2020
;; MSG SIZE  rcvd: 43
```

**Steps to reproduce:**

- Follow steps on https://docs.pi-hole.net/guides/unbound/ to enable unbound recursive dns
- Attempt to dig docker.com (success)
- Attempt to dig get.docker.com (no answer)

debug token is: https://tricorder.pi-hole.net/4tnsd5xxqy

`4tnsd5xxqy`

**Troubleshooting undertaken, and/or other relevant information:**

There are probably other domains that replicate this issue, but docker is what caught my attention. I ran a subdomain report on docker.com to see if I could get any further information. Results are below:

Found 20 subdomains
 
| Subdomain | IP address | OS | Server | Technology | Web Platform | Page Title |
| ----------- | ----------- | --- | ------ | ------------ | -------------- | --------- |
| community.docker.com | 3.82.77.6 | 
| store.docker.com | 3.221.200.233 |  | nginx | | | Docker Hub |
| cloud.docker.com | 3.221.200.233 |  | nginx | | | Docker Hub |
| www.docker.com | 13.224.102.9 |  | nginx | PHP 7.3.14 | Drupal 8 | Empowering App Development for Developers |
| beta.docker.com | 13.224.102.35 | | nginx | PHP 7.3.14 | Drupal 8 | Empowering App Development for Developers |
| blog.docker.com | 13.224.102.111 |  | nginx | PHP 7.3.14 | WordPress 5.3.2 | Docker Blog - News, Education & Version Updates |
| docs.docker.com | 13.225.69.125 |  | AmazonS3 |  |  |  Docker Documentation |
| www-dev.docker.com | 35.171.215.102 | | | | | |
| training.docker.com | 35.171.215.102 | | | | | Docker - Training |
| events.docker.com | 35.227.199.38 | | nginx | | | | The Worlds Leading Software Container Platform |
| go.docker.com | 52.0.72.70 | | nginx | PHP 7.3.14 | Drupal 8 | Empowering App Development for Developers |
| test.docker.com | 52.85.104.122 | | | AmazonS3 | | | |
| demo.docker.com | 54.86.236.79 | | Apache | | | Heroic Authentication |
| docker.com | 54.164.28.179 |  | nginx | PHP 7.3.14 | Drupal 8 | Empowering App Development for Developers |
| id.docker.com | 54.164.28.179 | | nginx | PHP 7.3.14 | Drupal 8 | Empowering App Development for |
| download.docker.com | 99.84.5.126 | | AmazonS3 | | | Index of / |
| email.docker.com | 104.17.71.206 | | cloudflare | | | |
| credentials.docker.com | 104.248.60.43 |  | Netlify | | | |
| forums.docker.com | 216.218.159.29 |  | nginx | | | Docker Forums |

Note that **all** subdomains resolve **except** those with AmazonS3 servers. This is way above my understanding of DNS but seems noteworthy.

Maybe related to this issue on Unbound https://github.com/NLnetLabs/unbound/issues/37

I should also note that explicitly setting unbound port in dig resolves with the correct A records:

```
dig get.docker.com @127.0.0.1 -p 5335

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> get.docker.com @127.0.0.1 -p 5335
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7026
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;get.docker.com.                        IN      A

;; ANSWER SECTION:
get.docker.com.         0       IN      CNAME   d3cxuo8f8w64ms.cloudfront.net.
d3cxuo8f8w64ms.cloudfront.net. 0 IN     A       99.84.206.5
d3cxuo8f8w64ms.cloudfront.net. 0 IN     A       99.84.206.118
d3cxuo8f8w64ms.cloudfront.net. 0 IN     A       99.84.206.68
d3cxuo8f8w64ms.cloudfront.net. 0 IN     A       99.84.206.114

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Sun May 17 08:40:17 PDT 2020
;; MSG SIZE  rcvd: 150
```

but this isn't necessary for any other domain and pihole works as expected as a dns resolver in my network. 

Edited for formatting and added last dig example

**Comment by yukdumboobumm** [comment]
Nevermind, I talked to the duck.

victim of the deep cname inspection.

**Comment by PromoFaux** [comment]
Heh, sometimes all it takes to solve an issue is typing it out
