### ISSUE TITLE
Samba SRV record queries show up with status "Unknown (0)"

### ISSUE THREAD

**Issue by otbutz** [pi-hole/pi-hole#3399]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

We use pihole as our primary DNS server and forward its queries to our internal dnsmasq server servering some Samba related SRV records and ultimately to an upstream DNS server.  Queries for samba related `SRV` records like `_kerberos._udp.example.org` should therefore show up with status `OK (cached)` or `OK (forwarded)` in the query log according to the [documentation](https://docs.pi-hole.net/database/ftl/#supported-status-types).

**Actual behaviour:**

The query log lists them with `Unknown (0)` in the query log despite being properly answered by pihole.

![grafik](https://user-images.githubusercontent.com/22315436/82187889-59d4a280-98ed-11ea-8e02-bb8e97e12bbd.png)

Querying other SRV records like `_sip._udp.sip.voice.google.com` results in the expected behavior.

**Steps to reproduce:**

Setup a second dnsmasq instance with the following config:

```
srv-host=_kerberos._tcp.Default-First-Site-Name._sites.example.org,samba.example.org,88,0,0
srv-host=_kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs.example.org,samba.example.org,88,0,0
srv-host=_kerberos._tcp.dc._msdcs.example.org,samba.example.org,88,0,0
srv-host=_kerberos._tcp.example.org,samba.example.org,88,0,0
srv-host=_kerberos._udp.example.org,samba.example.org,88,0,0
srv-host=_kerberos-master._tcp.example.org,samba.example.org,88,0,0
srv-host=_kerberos-master._udp.example.org,samba.example.org,88,0,0
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

s2j00m0eai

**Troubleshooting undertaken, and/or other relevant information:**
Removed the complete query log.

**Comment by yubiuser** [comment]
Might be solved by
https://github.com/pi-hole/FTL/issues/759

**Comment by undesiredpopup** [comment]
I think I have encountered this or a similar bug (specifically with a BT cloud voice express phone I was trying to fix).

pihole.log
Jul 14 23:18:01 dnsmasq[1105]: query[NAPTR] ipcomms-btb-centrex-wv20lnws20.bt.com from 10.11.1.89 (src/dnsmasq/forward.c:1543)
Jul 14 23:18:01 dnsmasq[1105]: forwarded ipcomms-btb-centrex-wv20lnws20.bt.com to 127.0.0.1 (src/dnsmasq/forward.c:547)
Jul 14 23:18:01 dnsmasq[1105]: query[SRV] _sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com from 10.11.1.89 (src/dnsmasq/forward.c:1543)
Jul 14 23:18:01 dnsmasq[1105]: config _sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com is NODATA (src/dnsmasq/rfc1035.c:1969)
Jul 14 23:18:01 dnsmasq[1105]: query[A] ipcomms-btb-centrex-wv20lnws20.bt.com from 10.11.1.89 (src/dnsmasq/forward.c:1543)
Jul 14 23:18:01 dnsmasq[1105]: cached ipcomms-btb-centrex-wv20lnws20.bt.com is NODATA-IPv4 (src/dnsmasq/rfc1035.c:1794)

and for ftl:
[2020-07-14 23:18:01.719 1105] *************************** unknown CACHE reply (2) ***************************

web ui will show something like this:

2020-07-14 23:30:28 | NAPTR | ipcomms-btb-centrex-wv20lnws20.bt.com | queryinghost | OK (forwarded) | N/A | 
2020-07-14 23:29:41 | A | ipcomms-btb-centrex-wv20lnws20.bt.com | queryinghost | OK (cached) | NODATA (0.2ms) | 
2020-07-14 23:29:41 | SRV | _sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com | queryinghost | Unknown (0) | 

Changing the upstream server in pihole from its local stubby dns-over-tls proxy to cloudflare, google or opendns directly also still results in NODATA being returned.

I have checked out fix/process_SRV_cache_master as suggested in https://github.com/pi-hole/FTL/issues/759 but still have the same behaviour.

an nslookup from a windows machine via pihole returns
*** No Service location (SRV) records available for _sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com

querying e.g. cloudflare directly returns the correct result
_sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com SRV service location:
          priority       = 20
          weight         = 20
          port           = 5060
          svr hostname   = ipcomms-btb-centrex-lnws20.bt.com
_sip._udp.ipcomms-btb-centrex-wv20lnws20.bt.com SRV service location:
          priority       = 10
          weight         = 20
          port           = 5060
          svr hostname   = ipcomms-btb-centrex-wv20.bt.com

As these are not local only srv records relating to AD domains (as these 2 issues appear to refer to) it should hopefully be easy to reproduce for the developers.

This problem does not occur for me with dnsmasq 2.80 on openwrt at least and configuring the device with alternate dns causes to succeed in registration (the records retreived when bypassing the pihole are valid)!
