### ISSUE TITLE
Pi-hole fails to restore default list of adlists

### ISSUE THREAD

**Issue by triatic** [pi-hole/pi-hole#3402]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---
**Expected behaviour:**

When `pihole -r` is performed while Pi-hole is configured with no adlists, I'd expect the default list of adlists to be set.

**Actual behaviour:**

List of adlists remains empty after `pihole -r`.

**Steps to reproduce:**

1. Delete all adlists from Pi-hole.
2. Run `pihole -r`

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/reset-list-of-adlists-to-defaults/32832/9

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/reseting-pi-hole-default-blacklist/33152/4
