### ISSUE TITLE
Message fault during installation

### ISSUE THREAD

**Issue by eejeel** [pi-hole/pi-hole#3404]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

During installation a screen is shown for selecting the protocol: IPv4 and/or IPv6.

"Select Protocols (press space to select)"

This text must be 
"Select Protocols (press space to deselect)"

because both IPv4 and IPv6 are default marked and will been installed if the [x] is not removed.

See https://ibb.co/yFc1SKC

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
You press the spacebar to toggle the asterisk that indicates what protocol is going to be used.

**Comment by eejeel** [comment]
That's correct

But default both X are placed and both protocols are selected.
And the text above this boxes indicates that you must press the spacebar for selecting the protocol you wish. But they are already placed.

In my opinion, a better text should be: Select Protocols (press space to select/deselect)

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by PromoFaux** [comment]
@eejeel no need for a feature request this time, I've already made a change. Cheers
