### ISSUE TITLE
SVT app dns lookup failure

### ISSUE THREAD

**Issue by shelldor** [pi-hole/pi-hole#3408]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
When using SVT APP (Swedish public tv) It is suppose to work 

**Actual behavior:**

When using "special features" as the corona news reporting site it show error message
It took me long time to understand why, because the log does not show the addresses it is using

Pi hole is unable to resolve these addresses:
ed1.cdn.svt.se
switcher.cdn.svt.se
api.svt.se

Please note that these addresses are NOT in the lists. Pi hole is just unable to look them up

2nd problem is that when I use the new feature subdomain whitelist *.svt.se;  it still blocks switcher.cdn.svt.se
Need to get another whitelist *.cdn.svt.se

**Steps to reproduce:**

https://play.google.com/store/apps/details?id=se.svt.svti.android.nyhetsapp&hl=sv
Click on "Corona" in the top of the start page.

**Comment by dschaper** [comment]
This is a configuration issue and not a bug. I'm able to resolve those addresses with a Pi-hole v5 install.

Please open an issue at https://discourse.pi-hole.net for help from the team and community.
