### ISSUE TITLE
Feature request: Bulk deletion in black- & whitelist

### ISSUE THREAD

**Issue by SuperSandro2000** [pi-hole/pi-hole#3409]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Have an option to delete 15 pages of whitelist.

**Actual behaviour:**

I am deleting all by hand which takes a longer time.

**Steps to reproduce:**

Try to clean your whitelist.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by p1r473** [comment]
A few options
1. Use a project like https://github.com/jacklul/pihole-updatelists which can download a whitelist from a text file and sync it
2. Use a command like ```sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist WHERE type= 0;"
```
