### ISSUE TITLE
New admin page (1.1.1) pagelets take a long time to load (and timing out?)

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#341]
The new admin page is cool, but the individual pagelets are taking a loooong time to load. I can see the individual php-cgi processes taking ~10% CPU while the spinners spin. 

The Query Types, Top Clients, and Forward Destinations seem to load first. Then Top Domains and Top Advertisers. I have yet to see Queries Over Time actually load.

I'm also seeing errors in my lighttpd.log:

2016-02-21 17:48:07: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 183

Which is probably why they're not loading. I'll try increasing that setting, but was wondering what the expected load time of these pagelets should be?

**Comment by Mcat12** [comment]
What kind of Pi are you running it on (If it is on a pi)? On my system (and I think the other dev's systems) it loads within 30 seconds. I use a B+.

**Comment by jradwan** [comment]
I increased max_execution_time to 120 in /etc/php5/cgi/php.ini and that seemed to be enough for the Queries Over Time to actually finish. It took longer than 2 minutes wall-clock time, but I guess not CPU time. 

It looks like these php-cgi processes are now persistent when the admin page is open? I guess that's so they refresh and stay current?

**Comment by PromoFaux** [comment]
For me personally, it's loading in less than a second... but then I am running on a debian server, not a pi...

**Comment by Mcat12** [comment]
With my B+ I can see (via htop) that 4 php-cgi processes use up 24% each, for a total of 100% CPU utilization, when I load the page. Maybe something is throttling php?

**Comment by PromoFaux** [comment]
Just installing on a pi2 to see what happens.

**Comment by jradwan** [comment]
It's a RasPi B+ v1.2.

That being said, it's also a [PiDP8](http://www.windracer.net/blog/2015/09/building-the-pidp-8/) so when the simh process is running that takes up about 50% CPU. I'll do some tests with simh not running and see how long they take to load.

**Comment by Mcat12** [comment]
The summary (top 4 stats) reloads I believe every minute.

**Comment by Mcat12** [comment]
That PiDP8 looks pretty neat.

**Comment by jradwan** [comment]
Ok, with nothing else running on the Pi, it took 1min 10sec for all of the pagelets to load completely (Queries Over Time being the last to complete).

With simh running, it took 4min 46 sec for all of the pagelets to load completely.

So, this isn't really a bug, just a side-effect of a busy Pi trying to execute those new php-cgi queries for the admin pagelets.

**Comment by PromoFaux** [comment]
Thanks for the update!

**Comment by Mcat12** [comment]
This might be a good wiki faq.

**Comment by Mcat12** [comment]
Added to faq.

**Comment by leichterleben** [comment]
Mine isnt loading properly at all: 
Installed the new version after uninstalling the previous one. Uncommented the mahakal list in in adlists.list after making a copy of adlists.default. gravity.sh went through without errors and reported roughly 1 Mio entries added to the list. 
After the reboot the admin page only shows around 700k blocked sites. The rest of the tiles is showing no (0) ads blocked/percentage/etc. The part below the tiles isnt loading at all and just showing the circle arrow. 
Ads are being blocked as expected though, so I presume there must be something wrong with the displaying of the admin page. RP 2 B

P.s. sry for not being able to give a better bug report, but I am relatively new to this. Let me know if I can provide additional information.

**Comment by PromoFaux** [comment]
Hi @leichterleben ,

Looks like we may have missed testing with mahakala (I don't think any of the devs actually use it, as it has caused numerous issues in the past, but we keep it there to give people the option)

I've just tried this myself, and I'm seeing a similar thing. The numbers just don't load at all... I think it must be down to the sheer size of the block list with mahakala included.. We will have to look into optimising the way we parse the lists in order to display the stats.

Were you running OK with the mahakala list before the update? 

Interestingly, i'm only showing 709386 domains... do you have other lists included?

```
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Custom adList file detected. Reading... done!                                                                                                                                                                                                                             .
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting adblock.gjtech.net list... No changes detected, transport skipped!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
::: Getting sysctl.org list... No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting hosts-file.net list... No changes detected, transport skipped!
::: Getting adblock.mahakala.is list... No changes detected, transport skipped!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 814909 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 709386 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 10 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 16 domains whitelisted!
::: Running blacklist script to update HOSTS file... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq. done!

```

**Comment by leichterleben** [comment]
> Interestingly, i'm only showing 709386 domains... do you have other lists included?

Just checked. My mistake. Number of domains is the same as yours, and therefor presumably displayed correctly in the admin page.

> Were you running OK with the mahakala list before the update?

Admin page wise no issues before the update. 
Ad blocking wise the behavior was as expected, which is to say that it is a little well-meaning :)

**Comment by PromoFaux** [comment]
>and therefor presumably displayed correctly in the admin page.

Are the graphs loading correctly for you with that many domains?

**Comment by Mcat12** [comment]
Have you increased max_execution_time for php?

**Comment by PromoFaux** [comment]
OK, I've been doing some fiddling with this myself.

Changing `max_execution_time` did nothing. However changing `memory_limit` from the default `128` to `512` worked instantly. Disclaimer, I'm running this currently at work on an old dell laptop.. an Rpi (Especially B+ and lower) may struggle with this.

**Comment by PromoFaux** [comment]
@leichterleben if you want to play with this yourself, you need to edit `php.ini` by running `sudo nano /etc/php5/cgi/php.ini` make changes to the relevant sections, and then run `sudo service lighttpd restart` to load in the changes.

Make sure to backup php.ini first! (`sudo cp /etc/php5/cgi/php.ini /etc/php5/cgi/php.ini.bak`)

**Comment by leichterleben** [comment]
@PromoFaux cheers for the quick answer. I just gave it a go and made the changes to the php.ini you had suggested. I increased the memory limit to 512 MB and restartet lighttpd. This had no apparent effect on the admin interface. Neither had a reboot of the Pi.
I'll just fiddle around some more with some settings, whats the worst that can happen, right?

**Comment by leichterleben** [comment]
Ok so fiddling was done. With little results. 
Increasing _memory_limit_ beyond 512M had no effect. Top revealed only around 15% of Ram being used. However %CPU sat at 100%. 
Following @PromoFaux lead, I then increased max_input_time in the php.ini to 120 to see if anything would change. However some testing showed the process php-cgi still shutting down after 60sec. Even setting the value to -1 didn't change this behavior. Can the max runtime be influenced by anything else than the php.ini ?

**Comment by PromoFaux** [comment]
I'm a bit out of my depth with the PHP stuff. Today was my first foray into changing those settings. @mcat12 is much better versed.

**Comment by Mcat12** [comment]
I'm not a super web dev, but have you changed the max_execution_time? It sounds like you haven't, since it's timing out after a minute.

**Comment by DonLexos** [comment]
I checked the lightppd.config in '/etc/lighttpd' and there is no mention of the max_exectution_time there. I then checked `/etc/php5/cgi` and there is a php.ini which does mention `max_execution_time = 30`. There is however another php.ini file in  `/etc/php5/cli`, I am not sure which one is used. I think if you change them and restart lighttpd you should get a higher time. I did find however some mention on the internets that lighttpd [ignores this](https://redmine.lighttpd.net/boards/2/topics/4474), not sure if that is true or not

**Comment by jradwan** [comment]
I changed the max_execution_time in /etc/php5/cgi/php.ini. The cli one is for PHP run via the command-line, which doesn't apply here.

**Comment by DonLexos** [comment]
Ok did you set it to 60 or higher? I can/will update the wiki to reflect this to make sure other mahakala list users can try this if their installation times out aswell.

**Comment by Mcat12** [comment]
Someone was running another application that used 50% CPU, and out it at 120 sec.

**Comment by DonLexos** [comment]
Updated the wiki to make sure restart lighttpd was there (to apply the max_execution_time change) and also copied the item to the adminLTE FAQ wiki page.

**Comment by leichterleben** [comment]
> I'm not a super web dev, but have you changed the max_execution_time? It sounds like you haven't, since it's timing out after a minute.

Tried that to, but to no avail. The problem persisted, even after I did comment the mahakala list out in adlists.list. I might to a reinstall of pihole tomorrow and report back if the admin panel is still not behaving as expected.

**Comment by PromoFaux** [comment]
Keep us updated :) It's always the way, we test everything we can think of between the developers, then users manage to find things we overlooked :)

But this is a good thing!

**Comment by jradwan** [comment]
I'm not using the mahakala list so my total domains blocked right now is 105,956. 

Increasing memory_limit to 256M on my B+ increased the total load time of the page to 5min 24sec when the Pi is "busy." When idle, the load time was 1min 18sec. Since increasing the memory on the limited B+ didn't really have a big effect I'm leaving it at the default 128M for now.

One thing I could do is offload the AdminLTE to my other Linux server where my primary web server (Apache) is running and use it to generate the stats page quicker.

**Comment by Mcat12** [comment]
You mean run the Pi-hole off of a different device? That would work fine. If you mean to just move the web page over, then that might not work so well. The site needs access to the core Pi-hole files.

**Comment by jradwan** [comment]
Right, I meant run the admin page only on a different device. Since both the Pi and my primary Linux server are local, I could probably use samba or something so that Apache could "see" the Pi-Hole files on the RasPi. Just an idea ...

**Comment by Mcat12** [comment]
It might work, but it would be less trouble to just install Pi-hole on the server. Try either way though!

**Comment by Mcat12** [comment]
Any updates on this?

**Comment by jradwan** [comment]
I did install AdminLTE under Apache on my primary Linux server and then manually copied the pihole.log and gravity.list files to the server. With some creative symbolic links I was able to get the admin page to load via Apache ... and it does load super-fast compared to the Pi.

But like you said, this is probably not worth the effort. I'd have to keep the gravity.list/pihole.log files current on the Apache server, which I could probably do via Dropbox or rsync, but for now I'm just leaving it on the RasPi itself.

**Comment by Mcat12** [comment]
Anyone opposed to closing this?

**Comment by dschaper** [comment]
I'm seeing some speed issues on the Zero, but this should probably be over on the AdminLTE repo instead of this one...

**Comment by Mcat12** [comment]
If this needs to be continued, please make a new issue on the web interface repo.
