### ISSUE TITLE
Pi-hole 5.0 is forwarding PTR queries for private IP ranges despite disabling this option

### ISSUE THREAD

**Issue by michal037** [pi-hole/pi-hole#3410]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi-hole doesn't forward PTR queries for private IP ranges, when the `Never forward reverse lookups for private IP ranges` option is enabled.

**Actual behaviour:**

Pi-hole forwards all PTR queries. In version 5.0, PTR queries began to show up at 'Top Permitted Domains'. In the 'Query log' section you can see that all queries have the status 'OK (forwarded)'.

![1](https://user-images.githubusercontent.com/7441419/82334590-79042a80-99e8-11ea-9c70-423ddbe83436.png)
![2](https://user-images.githubusercontent.com/7441419/82334598-7bff1b00-99e8-11ea-8e08-1456390865fa.png)

**Steps to reproduce:**

I have no idea. Pi-hole itself does it.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

sxldosaem8

**Troubleshooting undertaken, and/or other relevant information:**

I made sure that I have these options enabled:

* Never forward non-FQDNs
* Never forward reverse lookups for private IP ranges

![3](https://user-images.githubusercontent.com/7441419/82335866-2e83ad80-99ea-11ea-99bc-b57b21e21f83.png)

**Comment by dschaper** [comment]
Conditional Forwarding is enabled.

```plain
   server=/Sequence/192.168.2.1
   server=/2.168.192.in-addr.arpa/192.168.2.1
```

**Comment by michal037** [comment]
aah, my mistake, I'm sorry.
In the previous version, I didn't have entries in 'Query log' for that, I never saw them.
