### ISSUE TITLE
v5.0 - Missing data from Teleporter Exporter

### ISSUE THREAD

**Issue by abacao** [pi-hole/pi-hole#3416]
Missing data when exporting from the GUI at
http://pi.hole/admin/settings.php?tab=teleporter

It's missing the new data from Group Management:
- Groups and descriptions
- Clients, comments and group assignment

and

- Local DNS Records
- Conditional Fowarding
- Long term data

**Comment by yubiuser** [comment]
See here
https://github.com/pi-hole/AdminLTE/pull/1276

I guess long term data will likely never be included. The file `pihole-FTL.db`can easily be several hundred MB big and copied by hand.

**Comment by abacao** [comment]
Can the option be there and not be enabled as default?

Maybe a line like this:

empty box Long term data (357Mb)

I would appreciate the possibility of this not only as an exporting/importing tool but also as a general backup tool...

**Comment by abacao** [comment]
Issue is being talked in here
https://github.com/pi-hole/AdminLTE/pull/1276
