### ISSUE TITLE
2.5.3 api.php only returns []

### ISSUE THREAD

**Issue by r4m3u5** [pi-hole/pi-hole#342]
Title says it all - accessing the api returns "[]". Well, i guess that's due to all the major changes to the admin page itself.
Will there be an api.php that returns more or less the same data that is being visualized on the admin page?

**Comment by PromoFaux** [comment]
Hmm, as far as I am aware, this was not intentionally removed...

@Mcat12 ?

**Comment by PromoFaux** [comment]
Ah, just looking into this...

you need to navigate to `<IPofpihole>/admin/api.php?summary`

Apologies, I'll get this documented somewhere!

@Mcat12 Is it possible to get `api.php` will return the same results if no parameter is passed?

**Comment by r4m3u5** [comment]
Whoops ... missed that! Thanks!

**Comment by PromoFaux** [comment]
To be fair, I didn't even know it had changed.. had to go digging in the source.. :)

**Comment by Mcat12** [comment]
Ya, I can set it to get the summary with no params.

**Comment by Mcat12** [comment]
Am away from a real computer... Can someone test the latest devel? Just committed a possible fix.

**Comment by PromoFaux** [comment]
Just tested, that killed it completely. :D

**Comment by PromoFaux** [comment]
Instant 500 error.

**Comment by PromoFaux** [comment]
You were missing a bracket :)

@r4m3u5 , this will be fixed in the next release of the web admin, but for now you can just use `api.php?summary`

**Comment by Mcat12** [comment]
Good thing I didn't commit to master. :P

**Comment by Mcat12** [comment]
That's what I get for trying to work from my tablet.

**Comment by Mcat12** [comment]
Released

**Comment by r4m3u5** [comment]
Thanks guys! Appreciate it!
