### ISSUE TITLE
Restricting Pi-hole to just local clients (blocking remote clients)

### ISSUE THREAD

**Issue by Synetech** [pi-hole/pi-hole#3426]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

**Steps to reproduce:**

View Client list in dashboard

**Expected behaviour:**

A way to limit Pi-hole to local clients only and reject connections from remote clients.

**Actual behaviour:**

All connections are accepted and remote clients are displayed in the client list.

I searched through the settings, the docs, and online, but couldn't find any way to have Pi-hole only respond to local devices.

![Pi-hole Remote Clients](https://user-images.githubusercontent.com/5210197/82669537-9fed7700-9c09-11ea-8799-4c9fd7b41669.png)

**Comment by PromoFaux** [comment]
Close port 53 to the outside world immediately: https://www.cloudflare.com/learning/ddos/dns-amplification-ddos-attack/

Use a VPN to connect to your pi-hole remotely: https://docs.pi-hole.net/guides/vpn/overview/

As harsh as it sounds, you wont get any support from us on how to run an open resolver, sorry!

**Comment by Synetech** [comment]
VPN? Open resolver? 🤨 I'm just saying that there should be a setting to have Pi-hole reject any connections that aren't on the LAN. That seems like a normal Pi-hole related setting. 🤷

**Comment by p1r473** [comment]
Under settings->DNS, check the interface listening settings. You can set clients to be one hop away. This might be what you're looking for.

**Comment by Synetech** [comment]
It's already set to one-hop; maybe it's buggy. 🤔

**Comment by PromoFaux** [comment]
> I'm just saying that there should be a setting to have Pi-hole reject any connections that aren't on the LAN.

Really this should be the job of your router. Even some of the most network-confident people I know would not have port 53 open to the world. Running a publicly accessible DNS server is not something for the faint of heart, and as it can contribute to amplification attacks, it can really screw up parts of the internet.

> It's already set to one-hop; maybe it's buggy. 🤔

@DL6ER can you confirm what `listen on all interfaces` means, please? Is it supposed to reject non-LAN devices even if the user has port 53 open?

> So I guess that Pi-hole can't be used for content-filtering when out of the house?

It can be, with a VPN!

**Comment by DL6ER** [comment]
### Listen on all interfaces
> Allows only queries from devices that are at most one hop away (local devices)

This is enabled by:

https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/Scripts/webpage.sh#L200

`dnsmasq` man page:

> Accept DNS queries only from hosts whose address is on a local subnet, ie a subnet for which an interface exists on the server. [...] It is intended to be set as a default on installation, to allow unconfigured installations to be useful but also safe from being used for DNS amplification attacks. 

### **Listen only on interface *ifc***

This is enabled by:

https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/Scripts/webpage.sh#L208

> Listen only on the specified interface(s). Dnsmasq automatically adds the loopback (local) interface to the list of interfaces to use when the `--interface` option is used. [...]

### **Listen on all interfaces, permit all origins**

This is enabled by:

https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/Scripts/webpage.sh#L197

This is a dummy setting without any effect. It is set to trigger what I left out (marked as `[...]` in the description of `local-service`) above:

> This option only has effect if there are no --interface, --except-interface, --listen-address or --auth-server options.
