### ISSUE TITLE
Local DNS Records not parsing domains correctly if formatted as "ipaddress fqdn hostname"

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#3427]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

The domain field shows domains  (or even the FQDN)
The IP field shows IPs.

**Actual behaviour:**

The domain field shows hostnames
The IP field shows IPs and also FQDN.
...If provided in the pretty common ```ipaddress fqdn hostname``` format.
![image](https://user-images.githubusercontent.com/9235633/82691096-60d01d80-9c2b-11ea-8a24-6d16d3bda647.png)

**Steps to reproduce:**

```nano /etc/pihole/custom.list```
```
192.168.1.1	PortRoyal.Tortuga PortRoyal
192.168.1.186	Harbormaster.Tortuga Harbormaster
192.168.1.69	BlackPearl.Tortuga BlackPearl
192.168.1.96	HMSInterceptor.Tortuga HMSInterceptor
192.168.1.190	Shield.Tortuga Shield
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/wlpnxvymz5

**Troubleshooting undertaken, and/or other relevant information:**

I believe this is a UI parsing issue, when the DNSMasq lists file is provided in the ```ipaddress fqdn hostname```  format.
**nslookup still seems to work fine so I believe this is a display/parsing issue.**

![image](https://user-images.githubusercontent.com/9235633/82691073-5746b580-9c2b-11ea-8bc0-0ec2b721d0ff.png)

Note: I am aware this file was meant to be edited only via the GUI, and not in the manner in which I have done it.
That being said, I believe the format ```ipaddress fqdn hostname``` is pretty common for a DNSMasq list file.
Given that I think this is just a display/parsing issue, I hope this is an easy fix.

Thank you for your time and have a great day!

**Comment by yubiuser** [comment]
While Local DNS Records enables similar function as `/etc/hosts` the syntax is different.The syntax for the custom.list is simply

`IP hostname`  There only 2 arguments per line, not three.

**Comment by p1r473** [comment]
But, nslookup still works on the Local DNS Records. 
Which means, I think it's just a  display-only parsing issue.
I think they can add support for ```ipaddress fqdn hostname``` format

**Comment by dschaper** [comment]
Yubiuser's answer is the correct one.

**Comment by p1r473** [comment]
Okay thanks all!

**Comment by p1r473** [comment]
@dschaper If I were to add this functionality and do a pull request, would this kind of feature be approved?
Because ```addn-hosts=/etc/pihole/custom.list``` in 01-pihole.conf leads me to believe this is a regular DNSMasq file, I do think I can rework the UI to support the FQDN format.

**Comment by dschaper** [comment]
I can't guarantee that it will be approved or denied. I don't do much with the web interface so I'm not the best person to ask.

**Comment by PromoFaux** [comment]
Just a thought. I might be off the mark here, there is an open pull request for adding CNAMEs, too. Would that cover this?

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/AdminLTE/pull/1278

**Comment by p1r473** [comment]
I think this is a different feature altogether.
I am currently writing a discussion on the discourse for this- I will link to it in 1 moment!

**Comment by p1r473** [comment]
@PromoFaux this one could be more related:
https://github.com/pi-hole/pi-hole/pull/3382
