### ISSUE TITLE
Gravity file https://hosts-file.net/ad_servers.txt returns a 404 and is not found.

### ISSUE THREAD

**Issue by tantalum** [pi-hole/pi-hole#3428]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

When updating the pihole's gravity one of the blacklist files queried is `https://hosts-file.net/ad_servers.txt`. The expected behaviour is that URL point to a valid gravity/blacklist file.

**Actual behaviour:**

https://hosts-file.net/ad_servers.txt returns a 404 and is not found.

**Steps to reproduce:**

Execute `pihole -g`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/44a79z8906

**Troubleshooting undertaken, and/or other relevant information:**

Requested https://hosts-file.net/ad_servers.txt from a number of locations to ensure it was not an issue with my local connection or location.

**Comment by yubiuser** [comment]
The list doesn't exist anymore.
