### ISSUE TITLE
4 DNS Upstreams + router in dashboard  ... but only 2 defined in pihole ? (Conditional Forwarding)

### ISSUE THREAD

**Issue by roe1974** [pi-hole/pi-hole#3429]
Hi

i just activated "Conditional Forwarding" in pihole DNS settings with IP from my router + domain name (x.home.arpa). Now i see in the dashboard 4 upstream DNS (1.1.1.1, 1.0.0.1, 1.1.1.2, 1.0.02,my router) ... ist this normal ?
<img width="381" alt="1" src="https://user-images.githubusercontent.com/30420568/82667912-0b9b0880-9c39-11ea-906c-50710d5bed69.png">
<img width="757" alt="2" src="https://user-images.githubusercontent.com/30420568/82667921-0f2e8f80-9c39-11ea-855e-fa2d8fc479c0.png">

br, richard

**Comment by roe1974** [comment]
home.arpa is reserven for local domains at home see RFC8375
https://tools.ietf.org/html/rfc8375
richard

**Comment by dschaper** [comment]
Interesting, I don't do much with HNCP nets.

Closing as answered.
