### ISSUE TITLE
FTL update fails: Downloading and Installing FTL...curl: (3) bad range in URL position 98

### ISSUE THREAD

**Issue by Rumbelstilzchen** [pi-hole/pi-hole#3430]
**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
sudo pihole -up
should not throw an error
**Actual behaviour:**
running
sudo pihole -up
results in:
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check
  [i] Existing PHP installation detected : PHP version 7.3.11-1~deb10u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM architecture  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (3) bad range in URL position 98:
  [✓] Detected ARM architecture
                                                                                                 
  [✗] Downloading and Installing FTL
  [✓] Detected ARM architecture not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

**Steps to reproduce:**
Errror message occurs since update to pihole 5.0
cat /etc/os-release results in:
PRETTY_NAME="XBian 1.0 (knockout)"
NAME=XBian
VERSION_ID=1.0
VERSION="1.0 (knockout)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.xbian.org/"
SUPPORT_URL="http://forum.xbian.org/"
BUG_REPORT_URL="https://github.com/xbianonpi/xbian/issues"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`gc5y77ql2b`

**Troubleshooting undertaken, and/or other relevant information:**
tried to modify update-script - with no luck. I didn't find the correct call to curl

**Comment by PromoFaux** [comment]
Before I go much further: Xbian is _not_ a [supported operating system for Pi-hole](https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems) 

I wonder if XBian has a different version of curl. What do you get from `curl --version`?

Also, this let's try and get a complete output of what's going on at the point it fails:

```
sudo bash -x /etc/.pihole/automated\ install/basic-install.sh
```

And choose "update" when prompted.

Please save the output of the above command and attach it to your reply as a text file.. it will be quite large!

**Comment by Rumbelstilzchen** [comment]
curl --version: 
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

sudo bash -x /etc/.pihole/automated\ install/basic-install.sh
[pihole_update.txt](https://github.com/pi-hole/pi-hole/files/4671503/pihole_update.txt)

**Comment by PromoFaux** [comment]
OK, I can see why this is failing, and should be fixed when we release 5.1.

Here is the bugfix. https://github.com/pi-hole/pi-hole/pull/3347/files

As a workaround for now.. this _might_ work for you:

Edit the file `/etc/.pihole/automated\ install/basic-install.sh` and look for the function `get_binary_name()`. In there there should be the following line:

```
binary="pihole-FTL-arm-linux-gnueabi"
```

Change it to read:

```
l_binary="pihole-FTL-arm-linux-gnueabi"
```

And then run `sudo bash /etc/.pihole/automated\ install/basic-install.sh` and choose update. Hopefully that will get you updated... let me know!

**Comment by Rumbelstilzchen** [comment]
Thank you very much!!
This solved it.

**Comment by PromoFaux** [comment]
Great stuff. This will be fixed in version 5.1 and up. I'm not 100% sure on how it will go but you may need to do this workaround one more time when it is released. So bookmark this issue!

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ftl-not-updating-to-v5-0-url-404-not-found/33263/2

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ftl-not-updating-to-v5-0-url-404-not-found/33263/10
