### ISSUE TITLE
How to install a specific Pi-Hole version

### ISSUE THREAD

**Issue by DanielMourthe** [pi-hole/pi-hole#3435]
How can we install a specific Pi-Hole version like version 4.4 or 4.3.2 because version 5.0 is not yet working for us. We are using CentOS and after upgrading to 5.0, Pi-Hole does not work anymore. We try to install version 5.0 from a clean installation and it does not work too. Now we are without Pi-Hole and therefore we are asking how to install a previous version until version 5 became more stable and reviewed.

**Comment by dschaper** [comment]
Officially the way is to use the backup you created before updating to version 5. There's not really a way to use a previous version.

You might get community advice from https://discourse.pi-hole.net however.

**Comment by PromoFaux** [comment]
https://www.reddit.com/r/pihole/comments/gioym3/can_i_update_to_latest_v4_instead_of_jumping_to_v5/fqhn2gz/
