### ISSUE TITLE
systemd dependency not listed in README

### ISSUE THREAD

**Issue by taminaru** [pi-hole/pi-hole#3436]
Dear contributors and maintainers alike,

Sadly, it has come to my attention that you have failed to indicate your software's dependency on a popular toolkit named ``systemd``. Declaring this dependency as such will ease use of the service, and discourage installs on incompatible platforms.

Many thanks in advance.

**Comment by dschaper** [comment]
It works fine with sysvinit and `service` calls.

**Comment by TheEvilSkeleton** [comment]
> It works fine with sysvinit and `service` calls.

@dschaper what about OpenRC or Runit?

**Comment by dschaper** [comment]
No. But the claim was that only `systemd` works.

**Comment by TheEvilSkeleton** [comment]
Where? I don't see it anywhere in the README

**Comment by dschaper** [comment]
PR it then.

**Comment by TheEvilSkeleton** [comment]
Don't worry, I will, but I still want to know where it claims about it depending on systemd/sysvinit

**Comment by dschaper** [comment]
I don't know what you are talking about.

**Comment by dschaper** [comment]
We don't claim anything. The OP claimed Pi-hole needs `systemd` and that's not true.

**Comment by TheEvilSkeleton** [comment]
Just reread it, I read it wrong, sorry ^^

**Comment by TheEvilSkeleton** [comment]
@dschaper can I contribute to https://docs.pi-hole.net/main/prerequesites/?

**Comment by dschaper** [comment]
https://github.com/pi-hole/docs is the repo for it.
