### ISSUE TITLE
[Enhancement] Separate privacy levels for blocked and allowed domains.

### ISSUE THREAD

**Issue by iokiwi** [pi-hole/pi-hole#3437]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

As an administrator, I would like to be able to control the privacy settings of logs for allowed and blocked domains separately.

Background

As specified in the docs, there are 5 levels of privacy which applies to all logging of requests.
https://docs.pi-hole.net/ftldns/privacylevels/

75% - 95% of allowed logged requests are for allowed domains. For these requests I am more concerned with privacy.

For the %5 - %25 of blocked requests I am more concerned with transparency.

Currently I have to make a choice between privacy of allowed requests and transparency of blocked requests.

**Actual behaviour:**

Single setting controlling privacy / logging of both blocked and allowed requests simultaneously.

**Steps to reproduce:**

N/A

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

N/A

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by iokiwi** [comment]
Similar feature request found here. https://discourse.pi-hole.net/t/privacy-hide-domains-for-permitted-blocked-queries-only/32011

@dschaper I reckon It would be a good idea to update the Issue template to point users to discourse for feature requests.

**Comment by dschaper** [comment]
It's already there:

```plain
> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
```

**Comment by iokiwi** [comment]
Ok my apologies I missed it. Sorry :/
