### ISSUE TITLE
Experian login doesn't work with pi-hole enabled

### ISSUE THREAD

**Issue by dantheman213** [pi-hole/pi-hole#3442]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Being able to login to Experian profile here:

https://usa.experian.com/login/index?br=exp

**Actual behaviour:**

Attempting to login will result in the login page refreshing but not logged in (still on the login page but logged out as if the button was not pressed).

**Steps to reproduce:**

1. Register for an Experian account if you don't have one. It's free and allows you to check your Experian credit score (US citizens).
2. Attempt to login to Experian with pi-hole enabled and routing your DNS traffic on your LAN.

**Troubleshooting undertaken, and/or other relevant information:**

I verified the issue was with pi-hole by:
1. Turning on a VPN with no DNS/IP leak, website worked.
2. Turning off pi-hole on my LAN and routing traffic to Google (8.8.8.8,8.8.4.4).

I believe that Experian is a critical website that should be whitelisted by default in future releases of pi-hole.

**Comment by dschaper** [comment]
Pi-hole does not curate the contents of lists. We do not control users whitelists or blocklists. You can either whitelist domains you would like to use or remove blocklists you feel are not right for your use.

**Comment by dantheman213** [comment]
Adding `sdk.split.io` to my whitelist fixed the login issue. I had to hunt down the XHR request that was failing in the Chrome Developer Tools. Hardly seems like a good way to troubleshoot nor does it make me feel confident I can deploy this app to my LAN without breaking important websites.

I am using the following DockerHub container to turn-key run the app on a local server.
`linuxserver/plex`

This appears to be one of more popular ways to deploy and run this application. Whomever would do the work it just seems the net effect is a newcomer to pi-hole can't just run the app and get a fine tuned experience or easily report problems.

**Comment by dschaper** [comment]
Pi-hole is a DNS server. That's a vital tool for managing your network. It's not plug and play. It's not turnkey. 

I'm not quite sure how a `plex` image comes in to play with `pi-hole` but there is a Pi-hole docker image at the `pihole/pihole` namespace.

**Comment by dantheman213** [comment]
Sorry about that, my copy and paste skills are unmatched. One row above plex is the target container:
`pihole/pihole:latest`.

Yes, it's running with your turn-key setup.

**Comment by yubiuser** [comment]
From `pihole -q`
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   sdk.split.io 

You should contact the list maintainer if you think this domains is false-positive and should be removed

**Comment by dschaper** [comment]
Again, we do not have a turnkey setup. There is no reason a DNS server should be turnkey. 

There is no way for me to determine what you should block on your lan, or what you should allow on your lan. This is software provided to you for free, you have to make it work how you want. We can not do that for you.

**Comment by dantheman213** [comment]
> There is no reason a DNS server should be turnkey.

>> Not everyone is a highly seasoned software engineer, NOC personal, devops, etc, and has infinite time to do that kind of configuration.

> There is no way for me to determine what you should block on your lan

>> Are there settings or configuration to ensure a working more relaxed environment vs strict blocking of anything suspicious that may break expected behavior in apps or websites? 

>  We can not do that for you.

Thanks for the hot tip. I guess I'll get to work whitelisting or blacklisting THOUSANDS or MILLIONS of XHR requests by hand. 😉 

> There is no reason a DNS server should be turnkey.
> There is no way for me to determine what you should block on your lan
>  We can not do that for you.

Really? You can't do it for me?

<img width="756" alt="Capture" src="https://user-images.githubusercontent.com/10934533/82834773-f27f9b00-9e76-11ea-9a8d-91347297dcbd.PNG">

**Comment by dschaper** [comment]
Fine, I think you should only access `github.com` and I will block every other domain. Cool?

**Comment by dantheman213** [comment]
It just seems like there is a wider issue here. There's probably at least 2 schools of thought when running this app as a LAN administrator:

1. I want strict control of my DNS and incredible fine-tuned control over everything
2. I want semi/mostly turn-key setup that blocks 90% or whatever reasonable traffic it can but doesn't disrupt major apps or websites. 

With the latter option the setup would ideally also allow for tooling to quickly identify items to whitelist without me having to hunt down XHR requests using debug tools in Chrome. Currently, the setup has been mostly turn-key but I get unexpected behavior and no way to easily remedy it without a deeper and time consuming investigation.

**Comment by dschaper** [comment]
Personally, I wouldn't allow Experian. They have a bit of a privacy problem. 

https://www.lifelock.com/learn-data-breaches-equifax-data-breach-2017.html

**Comment by dschaper** [comment]
Yes, you will have to do work to make sure the blocking is tough/lax as you'd like it to be. Nobody but you knows what you find acceptable.

There is no turnkey solution that works that way. You're free to try them, https://github.com/nextdns or https://github.com/AdguardTeam/AdGuardHome.

**Comment by dantheman213** [comment]
My comment led to improved tooling in the pihole GUI to help track down items to be whitelisted so that way I don't have to do that manually. Is this not possible?

**Comment by dschaper** [comment]
Which comment?

**Comment by dantheman213** [comment]
> 2. I want semi/mostly turn-key setup that blocks 90% or whatever reasonable traffic it can but doesn't disrupt major apps or websites core operation or functionality.

> With the latter option the setup would ideally also allow for tooling to quickly identify items to whitelist without me having to hunt down XHR requests using debug tools in Chrome. Currently, the setup has been mostly turn-key but I get unexpected behavior and no way to easily remedy it without a deeper and time consuming investigation.

**Comment by dschaper** [comment]
I'm not following, which tooling change did that comment cause?

**Comment by dantheman213** [comment]
So the timeline of this issue is:

1. This issue was created and I reported that a major website, Experian, doesn't allow login with PiHole. This is an important website to use for many US citizens as it helps track their credit score.
2. After various discussion I was suggesting that for LAN administrators that deploy pihole they may want to be more relaxed than others. However, currently there isn't good tooling in the pihole GUI to help track down XHR requests or other assets that are being blocked.

More info:

Some requests or assets may need to be whitelisted for critical operation of that app or service on target LAN. The LAN administrator may be okay with some traffic getting through that may be overall undesired. Cost/benefit analysis should be up to administrator. However if administrator decides to whitelist there should be easy to use tooling to add rules based on recent XHR/asset requests coming in -- that would be wonderful.

**Comment by dschaper** [comment]
A DNS server knows only DNS names. It does not know any relation between domains. There's no way for a DNS server to know that a URL is asking for assets to load or that a website needs a domain to load. That's impossible. 

>Experian, doesn't allow login with PiHole.

That is not true. Pi-hole is the DNS server. YOU control the lists, YOU control what you block or allow.

>  I was suggesting that for LAN administrators that deploy pihole they may want to be more relaxed than others.

Great, you can do that right now. Disable blocklists or add blocklists. Whitelist domains you want or blacklist domains you don't want. Again, you have to do the work. Nobody can do it for you.

> However, currently there isn't good tooling in the pihole GUI to help track down XHR requests or other assets that are being blocked

There can't be, Pi-hole doesn't know that https://experian.com needs stealyourdata.net to work. There's no way for a DNS server to know they are related in any way. 

This isn't the tool for that.

**Comment by dschaper** [comment]
> 
> 
> From `pihole -q`
> Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
> sdk.split.io
> 
> You should contact the list maintainer if you think this domains is false-positive and should be removed

Yubiuser already told you how to resolve this issue. This is the way. Ask the list maintainer to remove the domain or just stop using that list.
