### ISSUE TITLE
After re-install of 2.5.3 all *.conf and *.php) are empty 

### ISSUE THREAD

**Issue by josemalone** [pi-hole/pi-hole#345]
Sorry, not a programmer by trade. ...I hope this makes sense and is helpful.

I just reinstalled 2.5.3 over an older version (not sure what version but it was from about two weeks ago) and all the *.conf files were blank after the install. The backups are intact. (*.conf.orig). So far I've had to touch interfaces.conf, dsnmasq.conf, lighttpd.conf, etc. And now I see the the *.php files for the Admin site are empty too. Once I copy over the *.conf with the orig files everything works as planned.All the directories/files are where they should be, but the .conf and .php files are empty. I've ran 'curl -L install.pi-hole.net | bash' twice now and the results are the same.

**Comment by Mcat12** [comment]
Can you run `ls -l /etc/.pihole/`?

**Comment by josemalone** [comment]
Here's what I get.

total 12
-rw-r--r-- 1 root root    0 Feb 23 16:39 adlists.default
drwxr-xr-x 4 root root 4096 Feb 23 16:39 advanced
drwxr-xr-x 2 root root 4096 Feb 23 16:39 automated install
drwxr-xr-x 2 root root 4096 Feb 23 16:39 block hulu ads
-rw-r--r-- 1 root root    0 Feb 23 16:39 CONTRIBUTING.md
-rwxr-xr-x 1 root root    0 Feb 23 16:39 gravity.sh
-rw-r--r-- 1 root root    0 Feb 23 16:39 LICENSE
-rw-r--r-- 1 root root    0 Feb 23 16:39 README.md

and this

:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 48 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing Pi-Hole!
:::
:::
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for toilet... already installed!
:::    Checking for figlet... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services.. done.
::: Checking if user 'pihole' exists...
::: User 'pihole' already exists
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... OK!
:::     Updating repo in /etc/.pihole.. done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin.. done!
:::
::: Installing scripts... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is from a previous pi-hole install.
:::    Backing up dnsmasq.conf to dnsmasq.conf.orig... done.
:::    Restoring default dnsmasq.conf... done.
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriting
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::

**Comment by josemalone** [comment]
Oh, so after running install again. 
and checking the services I get this.

● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-02-23 21:18:01 UTC; 11min ago
  Process: 3363 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 3361 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 3363 (code=exited, status=255)

Feb 23 21:18:01 rpi-dnsserver lighttpd[3361]: Syntax OK
Feb 23 21:18:01 rpi-dnsserver systemd[1]: Started Lighttpd Daemon.
Feb 23 21:18:01 rpi-dnsserver lighttpd[3363]: 2016-02-23 21:18:01: (configfile.c.1272) a default document-root has to be set
Feb 23 21:18:01 rpi-dnsserver lighttpd[3363]: 2016-02-23 21:18:01: (server.c.649) setting default values failed
Feb 23 21:18:01 rpi-dnsserver systemd[1]: lighttpd.service: main process exited, code=exited, status=255/n/a
Feb 23 21:18:01 rpi-dnsserver systemd[1]: Unit lighttpd.service entered failed state.

and 

● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Tue 2016-02-23 21:18:00 UTC; 12min ago
  Process: 3197 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 3269 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 3261 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 3258 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 3268 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─3268 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A16073716...

Feb 23 21:18:00 rpi-dnsserver dnsmasq[3258]: dnsmasq: syntax check OK.
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: started, version 2.72 cachesize 150
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: DNS service limited to local subnets
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: reading /var/run/dnsmasq/resolv.conf
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: using nameserver 192.168.1.1#53
Feb 23 21:18:00 rpi-dnsserver dnsmasq[3268]: read /etc/hosts - 5 addresses
Feb 23 21:18:00 rpi-dnsserver systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
Feb 23 21:20:12 rpi-dnsserver dnsmasq[3268]: Ignoring query from non-local network

**Comment by DonLexos** [comment]
Did you see this:
```
::: There are 48 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing Pi-Hole!
```

Maybe you can retry after you run `sudo apt-get upgrade` to see if that resolves it?

**Comment by PromoFaux** [comment]
It wont hurt, that's for sure! I think I know what the root of this issue is, but I need to read over the install script again to work it out... brb

**Comment by josemalone** [comment]
@DonLexos 

The 48 updates literally just popped up between this morning and now when I tried again. I'm update and will do and install again.

**Comment by josemalone** [comment]
@DonLexos 

OK. Finally got a chance to update and reinstall. Kinda the same predicament.

Curling didn't work this time so I did the ./basic-install.sh method. There were some errors that some files are unexpected or something. 

DnsMasq is starts but the conf is empty so I have to populate it and Lighttpd balks at starting until I load the conf file with the orig settings. And the html files are blank. As I repopulate every conf and php files things start to operate as expected. It's like its not fully writing over the files?

After ./basic-install.sh
:::
::: You are root.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.140/24
::: IPv6 will NOT be used.
::: Using OpenDNS servers.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 36 updates availible for your pi! _[ OMG! Can't win the update fight!]_
::: We recommend you run 'sudo apt-get upgrade' after installing Pi-Hole!
:::
:::
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for toilet... already installed!
:::    Checking for figlet... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services.. done.
::: Checking if user 'pihole' exists...
::: User 'pihole' already exists
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... OK!
:::     Updating repo in /etc/.pihole../fatal: index file smaller than expected
fatal: No such ref: HEAD
fatal: index file smaller than expected                                                                                                                                                                                                      done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin..-fatal: unable to access 'https://                                                                                                                                                             github.com/jacobsalmela/AdminLTE.git/': Could not resolve host: github.com                                                                                                                                                                   done!
:::
::: Installing scripts... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriti                                                                                                                                                             ng
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
::: Restarting services... done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DN                                                                                                                                                             S server using:
:::     192.168.1.140/24
:::
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log


DnsMasq
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Wed 2016-02-24 00:43:48 UTC; 2min 53s ago
  Process: 1622 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 1695 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 1686 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 1683 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 1694 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─1694 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A16073716...

Feb 24 00:43:48 rpi-dnsserver dnsmasq[1683]: dnsmasq: syntax check OK.
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: started, version 2.72 cachesize 150
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: DNS service limited to local subnets
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: reading /var/run/dnsmasq/resolv.conf
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: using nameserver 192.168.1.1#53
Feb 24 00:43:48 rpi-dnsserver dnsmasq[1694]: read /etc/hosts - 5 addresses
Feb 24 00:43:48 rpi-dnsserver systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

Lighttpd

● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Wed 2016-02-24 00:47:53 UTC; 2s ago
  Process: 1865 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 1862 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 1865 (code=exited, status=255)

Feb 24 00:47:52 rpi-dnsserver lighttpd[1862]: Syntax OK
Feb 24 00:47:52 rpi-dnsserver systemd[1]: Started Lighttpd Daemon.
Feb 24 00:47:53 rpi-dnsserver lighttpd[1865]: 2016-02-24 00:47:53: (configfile.c.1272) a default document-root has to be set
Feb 24 00:47:53 rpi-dnsserver lighttpd[1865]: 2016-02-24 00:47:53: (server.c.649) setting default values failed
Feb 24 00:47:53 rpi-dnsserver systemd[1]: lighttpd.service: main process exited, code=exited, status=255/n/a
Feb 24 00:47:53 rpi-dnsserver systemd[1]: Unit lighttpd.service entered failed state.
pi@rpi-dnsserver:~ $

**Comment by Mcat12** [comment]
Can you run `whitelist.sh github.com`, `rm -R /etc/.pihole/`, and then try the installer again? (You may have to wait a minute or two for the whitelist to take effect) It looks like maybe the git repos on your machine are corrupt or something.

**Comment by DonLexos** [comment]
You can lower the wait period if you restart the dnsmasq service after you have whitelisted the domain btw.

**Comment by PromoFaux** [comment]
Whitelisting does restart dnsmasq...

**Comment by DonLexos** [comment]
In that case it would be instantly and would not require a wait, right?

**Comment by PromoFaux** [comment]
Correct.

**Comment by Mcat12** [comment]
Ah, confusing myself with the client's cache.

**Comment by josemalone** [comment]
@Mcat12 I whitelisted, restarted, updated, upgraded, and curled. Then the pi locked up. In reading the logs I think the issue is with the install of Raspbian or the SD card itself. Decided to install on another Pi and it was flawless. Hence that's my new Pi-Hole server. Sorry for all the arm waving!

**Comment by Mcat12** [comment]
Good that it's solved!
