### ISSUE TITLE
Can’t Find Whitelist File

### ISSUE THREAD

**Issue by jtovar43** [pi-hole/pi-hole#3452]
I am trying to reset my whitelist file. Normally this is located in etc/pihole but the file does not seem to be there. There was a file located in that directory called whitelist.txt.bck~ which I removed but that didn’t seem to do anything. 

I can still add Items to the whitelist through the web interface and the pihole -w command but I can’t find where these entries are being stored. 

Any help would be appreciated.

**Comment by yubiuser** [comment]
I guess you run piholve v5.0? Since this version whitelist.txt doesn't exist anymore - it is part of the  `gravity.db`
https://pi-hole.net/2020/05/10/pi-hole-v5-0-is-here/#page-content

You can delete your whitelist entries via web interface or direct interaction with the database via sqlite.
