### ISSUE TITLE
Can't get Pi-hole working, dns won't resolve

### ISSUE THREAD

**Issue by Techloid-g** [pi-hole/pi-hole#3453]
Asked on reddit, thought i'd ask here too. Been trying to get Pihole working for a few days now, followed all the steps several times and still nothing. My devices will read that they have the right DNS address and will load pages but pi-hole doesn't filter. Go to the setting page and there tons of cashed DNS insertions but 0 evictions. Perhaps there is some coding I have to do to the router to make it the only DNS? if I do an nslookup on a device I'll get :

```
Server:  raspberrypi
Address:  192.168.1.84

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to raspberrypi timed-out
```

Router is Asus RT-AC87R

Any help appreciated.

https://tricorder.pi-hole.net/yc38k6zfj8

**Comment by dschaper** [comment]
A better place to ask for assistance is https://discourse.pi-hole.net

You'll have the community available to assist you with any issues.

**Comment by Techloid-g** [comment]
Well I tried a couple hours ago but I didn't realize it was moderated and tried to post twice... now i don't know if it's just being moderated as spam, hate moderated forums

**Comment by PromoFaux** [comment]
I've manually approved your post on Discourse. The system automatically flags some posts from new users as spam. We monitor the posts that need approval, please be patient :)
