### ISSUE TITLE
Fedora 32 (RasPi 3B) install fails

### ISSUE THREAD

**Issue by jameseck** [pi-hole/pi-hole#3456]
This is a: Bug

## Details

When running the basic-install.sh script on a RasPi 3B running Fedora 32, the installer fails when trying to find the /etc/dhcpcd.conf file.  This is because dhcpcd is not installed by default and the installer does not install it before trying to modify the config.
The error is:
  [i] Warning: Unable to locate configuration file to set static IPv4 address
It is reported as a warning, but the installer exits at this point.

Furthermore, the installer does not appear to enable dhcpcd after modifying the config so the config would seem to be unnecessary anyway.  I would prefer to remain using Network Manager instead of dhcpcd, especially as it's configured on Fedora 32 by default.

## Related Issues
None that I can find.

## How to reproduce the issue 
Boot RasPi 3B with Fedora 32 and run the basic-install.sh script.

1. Environment data
  * Operating System: Fedora 32
  * Hardware: RasPi 3B
  * Kernel Architecture: aarch64
  * Docker Install Info and version: NONE
  * Hardware architecture: aarch64

**Comment by bcambl** [comment]
line 932:
```
    # For the Debian family, if dhcpcd.conf exists,
    if [[ -f "/etc/dhcpcd.conf" ]]; then
        # configure networking via dhcpcd
        setDHCPCD
        return 0
    fi
```

@jameseck  `/etc/dhcpcd.conf` should not exist with Fedora 32.  Can you please verify.

Please provide the output from the following command:
```
ls -l /etc/dhcpcd.conf
```

**Comment by jameseck** [comment]
On Fedora 32, /etc/dhcpcd.conf does not exist.  The installer fails with
the warning in my initial post though.

**Comment by bcambl** [comment]
The error you provided states nothing regarding `dhcpcd.conf`.  
How did you determined it has something to do with dhcpcd?

Please provide the output from the following commands:

```
grep PIHOLE_INTERFACE /etc/pihole/setupVars.conf
```
```
ls /etc/sysconfig/network-scripts/ | grep ifcfg
```

**Comment by jameseck** [comment]
Sorry, my mistake.  The warning does not explicitly mention dhcpcd.conf.  I installed dhdpcd to fix the error after I read in the docs (https://docs.pi-hole.net/main/prerequesites/) that pihole required dhcpcd:

"Pi-hole needs a static IP address to properly function (a DHCP reservation is just fine). Users may run into issues because we currently install dhcpcd5, which may conflict with other running network managers such as dhclient, dhcpcd, networkmanager, and systemd-networkd."

The output from the commands you requested is as follows:
```
[root@pihole ~]# grep PIHOLE_INTERFACE /etc/pihole/setupVars.conf
PIHOLE_INTERFACE=eth0
[root@pihole ~]# ls /etc/sysconfig/network-scripts/ | grep ifcfg
[root@pihole ~]# 
```

This was a fresh install of Fedora 32.  I have done nothing with the network configuration on this (aside from installing dhcpcd).  It is running Network Manager as configured from the official Fedora 32 aarch64 image.

Please let me know if you need further information.

**Comment by bcambl** [comment]
First, ensure `/etc/dhcpcd.conf` doesnt exist from your attempted fix. If the file exists, it will short circuit the script and try do configure `dhcpcd` (which we do not want in this case)

The problem appears to be that you are missing the file `/etc/sysconfig/network-scripts/ifcfg-eth0` for whatever reason.

Try:
```
touch /etc/sysconfig/network-scripts/ifcfg-eth0
```

Then try running the installer again.  
This may be enough to trick the installer into working in this situation.

**Comment by jameseck** [comment]
As far as I know, the ifcfg-xxx scripts are now deprecated in Fedora (as well as RHEL8) so it might be better to use some other logic.  Adding some more detail to the "Warning" (I think this should be an Error if it causes the Installer to fail) would be great so users are not confused about why it's failing.

I'll try the ifcfg-eth0 trick when I have time to do a reinstall, but for now I'm testing with the docker image instead.  One of the reasons for switching to docker is that I can fully automate the install which doesn't seem possible with the non-docker install method.

**Comment by bcambl** [comment]
It is true; however, the last few builds I have tested still have the `network-scripts` path and an `ifcfg` file present. I suspect the issue you hit here is more to do with containers and how container networking is done.

Instead of attempting to run the installer inside a container, please use the official containers here:
https://github.com/pi-hole/docker-pi-hole

For the record, we do use `NetworkManager` for network configuration if available.
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L905

Code TL;DR
1. generate an ifcfg file and put it in place for legacy support. 
2. set ip in runtime with the `ip` command.
3. if the `nmcli` command is available nm status checks OK, the ifcfg file is read via `nmcli con load`.

**Comment by jameseck** [comment]
Just to clarify, I've been testing the official containers, not running the installer inside a container.  All of my feedback on this issue was 100% related to running the installer natively, not inside a container.

What I effectively did from the start:
Download the Fedora 32 aarch64 image, write it to sd card and boot the Pi.
Ssh into the Pi, wget the pihole install script and run it.
Installer dies with the Warning about network configuration file not found.

**Comment by bcambl** [comment]
Sorry for the misunderstanding. I was confused as to why you started talking containers when it has nothing to do with the issue we are trying to troubleshoot.

For now please attempt the `touch` workaround above.

**Comment by vmstan** [comment]
I ran into this today on a Pi 3 with the Fedora image on it.

The `touch /etc/sysconfig/network-scripts/ifcfg-eth0` workaround does indeed work. I also tested an install on an ISO based VM deployment of Fedora 32 and it installs without any workarounds needed.

**Comment by bcambl** [comment]
Thanks for the comment @vmstan.

**Comment by frmoronari** [comment]
Here I resolved with the installation of dhcpcd.
Fedora 32 Rasp 4 (aarch64).

**Comment by t3kg33k** [comment]
I ran into this same issue on Fedora 33 server. The touch workaround doesn't seem to work in this version.

**Comment by frmoronari** [comment]
> I ran into this same issue on Fedora 33 server. The touch workaround doesn't seem to work in this version.
> Should I open a new bug for Fedora 33?

i solved this in simple edit /etc/os-release and define OS for F32. 
after install pi-hole, return file to original state.

**Comment by t3kg33k** [comment]
> > I ran into this same issue on Fedora 33 server. The touch workaround doesn't seem to work in this version.
> > Should I open a new bug for Fedora 33?
> 
> i solved this in simple edit /etc/os-release and define OS for F32.
> after install pi-hole, return file to original state.

Thanks. This didn't work for me either.
Perhaps I should open a new bug. I failed to mention that I am not running Fedora 33 server on RaspberryPi but on a refresh install in a VM and configured the static IP using nmcli. Not sure if that matters or not.

**Comment by bcambl** [comment]
If you resolved your problem by editing `/etc/os-release` then your problem was likely not related to this issue.  
This particular issue is related to the installer depending on sysconfig network configuration. This issue is not getting attention as the network configuration will be removed in a future release.

If you configure your networking via nmcli, you should be able to use the `touch` workaround to create an ifcfg file with a name that matches the nmcli record.

**Comment by t3kg33k** [comment]
> If you resolved your problem by editing `/etc/os-release` then your problem was likely not related to this issue.
> This particular issue is related to the installer depending on sysconfig network configuration. This issue is not getting attention as the network configuration will be removed in a future release.
> 
> If you configure your networking via nmcli, you should be able to use the `touch` workaround to create an ifcfg file with a name that matches the nmcli record.

Yeah. Unfortunately, the 'touch' workaround did not work for me.

**Comment by bcambl** [comment]
> > If you resolved your problem by editing `/etc/os-release` then your problem was likely not related to this issue.
> > This particular issue is related to the installer depending on sysconfig network configuration. This issue is not getting attention as the network configuration will be removed in a future release.
> > If you configure your networking via nmcli, you should be able to use the `touch` workaround to create an ifcfg file with a name that matches the nmcli record.
> 
> Yeah. Unfortunately, the 'touch' workaround did not work for me.

What is the output of:
```
nmcli con show
ls /etc/sysconfig/network-scripts
```

**Comment by t3kg33k** [comment]
nmcli con show
NAME    UUID                                  TYPE      DEVICE 
enp1s0  a829c5bf-0fe6-37a7-be7c-61afb45679b2  ethernet  enp1s0

ls  /etc/sysconfig/network-scripts/
enp1s0


Here is the out put from install:

curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

[✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.


  [✓] Checking dnf for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which
  [✓] Checking for chkconfig
  [✓] Checking for bind-utils

  [i] PIHOLE_SKIP_OS_CHECK env variable set to true - installer will continue
  [✓] Default SELinux: disabled
  [✓] Current SELinux: Disabled
  [i] Using upstream DNS: Google (ECS) (8.8.8.8, 8.8.4.4)
  [i] Warning: Unable to locate configuration file to set static IPv4 addres

**Comment by bcambl** [comment]
try:
```
mv /etc/sysconfig/network-scripts/enp1s0 /etc/sysconfig/network-scripts/ifcfg-enp1s0
```

**Comment by t3kg33k** [comment]
Good call. I didn't even think about that. That worked.

**Comment by yubiuser** [comment]
Does the issue persists?

**Comment by bcambl** [comment]
This issue can be closed as network configuration is to be removed from the installer in the future.
