### ISSUE TITLE
"pihole -b --nuke"/"pihole --regex --nuke": Commands produce errant help output

### ISSUE THREAD

**Issue by ghostis** [pi-hole/pi-hole#3458]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

pihole -b --nuke removes all blacklists and exits normally

pihole --regex --nuke removes all regexes and exits normally

**Actual behaviour:**

The above commands take the intended action successfully, but also produce help output as if the flags were incorrect.

**Steps to reproduce:**

Run:

pihole -b domain.com
pihole -b -l
-> shows blocked domain
pihole -b --nuke
-> shows help for '-b'
pihole -b -l
-> shows no lists

Likewise for: pihole --regex -l

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/77dun2ae4f

**Troubleshooting undertaken, and/or other relevant information:**

None.

**Comment by yubiuser** [comment]
This has been fixed by https://github.com/pi-hole/pi-hole/pull/3349

**Comment by ghostis** [comment]
Thanks so much!
