### ISSUE TITLE
pihole & unbound config documentation 

### ISSUE THREAD

**Issue by Xedon420** [pi-hole/pi-hole#3461]
Hello Pihole Github Community,
I have a small request for the Pihole Doc's, because I lost a lot of hours with a configuration error and I would like to pass on the resulting solution.
Pihole with unbound causes a big problem with the Config described in the doc's (https://docs.pi-hole.net/guides/unbound/) when using a plex server in the network (no secure connection can be established via the website "app.plex.tv").

My request now would be to include this known error in the docs.
For people who have a plex server in the network, you have to add this entry to the config:
```
private domain: plex.direct
```
Afterwards the problem is also permanently solved.

Many thanks for the development of Pihole,
Xedon

**Comment by jfb-pihole** [comment]
Since this is a problem unique to plex users, I don't believe that the correct place for this is in the unbound configuration page. A more suitable place is on discourse.pi-hole.net with a post as a community how-to.  Those posts are persistent and searchable.

**Comment by Xedon420** [comment]
Yes, but I think for people who are installing an unbound server for the first time, this information can be very helpful. Since it is not immediately obvious where the error lies if the Plesk server suddenly stops working properly.
Maybe you could add this as a marginal info below, or link the Github Issue to it.

I just wanted to report it, because it took a few hours to find the cause. 
Maybe it helps a few people.

**Comment by ch-ris** [comment]
Still helpful. Thank you @Xedon420 for pointing out.

> ...add this entry to the config:
> private domain: plex.direct

btw: might want to include a _dash_:
`private-domain: plex.direct`
