### ISSUE TITLE
Support Debian bullseye dev branch 

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#3464]
Could you please add Support for next releases of Debian / Raspbian on the dev branch from pihole?

**Comment by PromoFaux** [comment]
Once 11/bullseye is released, then we will further look at it. For now.. anything could change between now and it's actual release, so it is best to wait until it is stable.

Currently, Stretch is EOL ~2020, with LTS til 2022, and Buster is EOL 2022 (no LTS date yet). 

https://wiki.debian.org/DebianReleases
