### ISSUE TITLE
Leading spaces in passwords are ignored

### ISSUE THREAD

**Issue by pizzabreath** [pi-hole/pi-hole#3465]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

The admin console password is set to the value provided when changing, independent of the used characters (`sudo pihole -a -p`).

**Actual behaviour:**

If the new password starts with one or multiple spaces, the spaces are ignored. For example, for the provided password `" password"` (no quotes), the actually set password is `"password"` (no quotes). The password change does not show any abnormalities. 
```
$ pihole -a -p
Enter New Password (Blank for no password): 
Confirm Password: 
  [✓] New password set
```

**Steps to reproduce:**

- `pihole -a -p`
- Set password with one or multiple leading spaces
- Leading spaces must be excluded, when logging in to the admin console.

---

Debug Information: 
```
*** [ DIAGNOSING ]: Core version
[i] Core: v5.0 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v5.0-0-g4d25f69

*** [ DIAGNOSING ]: Web version
[i] Web: v5.0 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v5.0-0-gb86e4a3

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v5.0

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.53

*** [ DIAGNOSING ]: php version
[i] 7.3.14

*** [ DIAGNOSING ]: Operating system
[✓] Raspbian GNU/Linux 10 (buster)

*** [ DIAGNOSING ]: SELinux
[i] SELinux not detected

*** [ DIAGNOSING ]: Processor
[✓] armv7l
```

**Comment by dschaper** [comment]
This isn't a limitation of the password entry, this is just how bash works. There's no way for the shell to know if you intended to have spaces or not so they are stripped. 

```bash
dschaper@Mariner-10:~$ echo me
me
dschaper@Mariner-10:~$ echo       me
me
```

**Comment by pizzabreath** [comment]
I'm not sure how pihole reads the password, nor am I a linux/bash expert, but this can be achieved quite easily. For example:

```
pb@dough:~$ IFS= read -r foo
 hello
pb@dough:~$ echo "'${foo}'"
' hello'
```

**Comment by dschaper** [comment]
Feel free to open a feature request over on discourse.

**Comment by PromoFaux** [comment]
Just tried this out, you can put a space at the front end of a password by wrapping it in quotes.

e.g:

`pihole -a -p '    nothing to see here'`

![nothing to see here](https://user-images.githubusercontent.com/1998970/83566459-f1eea080-a517-11ea-8adf-1313b46ff1db.gif)
