### ISSUE TITLE
Consistency in configuration variables

### ISSUE THREAD

**Issue by benlowry** [pi-hole/pi-hole#3468]
There are three different naming conventions used in the configuration variables.  If the variables are consistently named users need to remember the format.  Inconsistency means they have to remember names + formats for each variable and that creates opportunities for the users to make mistakes which forces them to check documentation, search for answers etc.

ServerIP
WEBPASSWORD
WEB_PORT

**Comment by dschaper** [comment]
We'd accept any pull requests to fix this.
