### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Verpz** [pi-hole/pi-hole#347]
##### Several Feature Requests:
- [x] Fetch client hostname as well as local IP for easier recognition.
- [x] Ability to use gravity.sh and updateDashboard.sh from dashboard.
- [x] Ability to rename clients for even easier recognition.
- [ ] Client list - Gives the ability to enable / disable ads just for individual clients. Also it would be cool if there is a button to disable their internet as well.
- [x] Global Enable/Disable button on Dashboard for ad blocking.
- [ ] Weekly reporting for statistics.
- [x] Popup on Dashboard when there is an update.
- [x] Ability to add new ad lists via Dashboard
- [x] Select DNS server via Dashboard and / or use a custom one
- [x] Show a warning when Javascript is disabled.
##

**Comment by C4Wiz** [comment]
this would be fantastic

**Comment by PromoFaux** [comment]
Hey, thanks for the suggestion. We're currently working on secure ways of making the dashboard more interactive, so there is a large chance that these will see the light of day.

An issue we currently have is that we need to lock down script access. To give you an idea of the issue, At the moment, if we were to allow scripts to be run from the site, all an advertising company would need to do to whitelist their own site (without you realising) would just be to try and load content from

`somedomain.com/admin/whitelist.PHP?some domain.com`

This is obviously not ideal! Don't worry, though, this is not actually possible, but could be if we rushed the implementation.

We'll get there!

**Comment by Verpz** [comment]
Okay, awesome. Yeah I'd rather it take longer and be secure. Nice work on the new dashboard btw.

**Comment by JaredWith1r** [comment]
The new dashboard IS wonderful, the stats are great. On that note, could we add **axis titles** to the plots? I mean, I realize the x-axis is time, but what day? what timezone?

Also, a timetag for the last time gravity was run, or the last time stats were read for the dashboard. Like 'updated at 13:15:30 1/1/2015', you know what I mean.

Still great support!

**Comment by PromoFaux** [comment]
Yep! Those are (roughly) all things we're planning!

At the moment, the graph is only showing one day, because we only store one day's worth of data (the logs are flushed at 23:58 daily). Once we have databases set up, we can start getting a bit fancier with the way we show information :)

**Comment by Verpz** [comment]
Is access control something that you have considered implementing? Like access to internet. As well as blocked sites for individual clients?

**Comment by PromoFaux** [comment]
It's not something we've talked about, no. Though certainly up for discussion! How would it be implemented? How would it be managed? I take it you're talking from a parental control perspective? What's to stop the DNS settings on the client device being changed to something else? Kids these days know what they're doing... :)

**Comment by Verpz** [comment]
Well if it is at the router, you can change the default password. For the dashboard simply password protect it. It's not hard, that should also be an option in the installation. Yeah haha, most kids no way more than their parents.

**Comment by Verpz** [comment]
If that kid was me I'd just reset the router and get in lol.

**Comment by PromoFaux** [comment]
Yeah, password protection on the dashboard is an upcoming feature as part of our commitment to get the security side of things locked down. Once we have security tight as can be, then we'll be moving onto adding the ability to run some of the scripts from the dashboard. But that has to be [absolutely water-tight](https://github.com/pi-hole/AdminLTE/issues/39).

**Comment by Verpz** [comment]
Yeah, that is pretty scary how an advertiser could do that, one of the downsides to open source. But the upside is there are people like Fedora-Core to diagnose the issue before it escalates into something scary.

**Comment by Verpz** [comment]
Also, since I've already password protected /admin would I need to undo that before updating to a version with PW protection?

**Comment by PromoFaux** [comment]
I like that the project is open-source. It's nice for people to be able to see exactly how things are working, and I think that goes some way to gaining the trust of users. It also means that anyone that feels they can contribute something, can. Once we have a water-proof method of running scripts from the dashboard, it wont matter that people know how we do it, they still wont be able to stop it :)

RE: current PW protection. I'm not sure yet, I've not looked over @Mcat12's implementation, but it may be best to undo it and then go with the pre-installed version. Keep it how it is for now though, as I'm not sure when that will be released.

**Comment by Verpz** [comment]
Ok cool. Yes I think everything should be open source, it does gain trust and it can give users like me peace of mind, especially when big data mining companies release software. Who knows what it is doing in the background. It is also so hard to avoid tracking now, like with browser fingerprinting, unless you use tor for absolutely everything (which is a giant slow pain in the ass) and even then there are work arounds. This is why I like Pi-Hole so much as I don't have to worry about ads tracking me anymore. Sorry this kind of turned into a rant on tracking haha.

**Comment by PromoFaux** [comment]
No worries! We're always up for the discussion!

**Comment by Mcat12** [comment]
The password implementation is currently open in a PR on both repos. It's currently just a simple plaintext password, but it will still stump any websites that try to whitelist their ads.

**Comment by Mcat12** [comment]
I've converted the OP into a tasklist. Some of them are already/mostly done.

**Comment by Verpz** [comment]
Nice, should this "Ability to rename clients for even easier recognition." be ticked? Because you can rename clients just not on the dashboard.

**Comment by Mcat12** [comment]
Ya. I'm just not sure that the automatic fetching of hostnames is possible, since dnsmasq only logs ip addresses (and unless they're reserved or static, the ip address could change)

**Comment by DonLexos** [comment]
Might depend on the router you use, I know openWRT has the option to hand out hostnames to local clients (whatever.lan) and you can even set them in the hostfile on the router.

**Comment by Mcat12** [comment]
Added update notification to the next web interface update!

**Comment by Verpz** [comment]
Just wondering, is it even possible to turn off ad blocking for individual clients? I've noticed more news sites are implementing ad block detection and not being able to disable Pi-Hole easily means I have to switch to a VPN.

**Comment by dschaper** [comment]
With the current implementation the only way to do that would be to change the DNS resolver on the individual client and then update/purge/flush the resolver cache and configuration of the client. There really isn't anything at the Pi-hole level that would allow for dnsmasq to detect the client and then chose a resolver to query based on that information. Might be possible if you were using dnsmasq as the DHCP server, but that would take some jiggering... The easier solution would be for a pause feature on the Pi-hole and that issue has been opened. 

What kind of behaviours are you seeing from sites that detect ad-blocking? A webpage that asks you to turn off the blocker?

**Comment by Verpz** [comment]
Some sites require you to turn off your ad blocker to view its contents and because ads are blocked at the Pi-Hole level I can't view the site without either changing DNS server or using a VPN. Sites like Wired.com (Waits for a couple minutes before it asks you) and Forbes implement this. https://i.gyazo.com/7c92ec11937cf7d84d8e87fc3bc892c2.png

**Comment by dschaper** [comment]
From what we've gathered the way some of the ad-block detecting occurs is through some JavaScript calls, so if the domain serving the scripts are blocked, then the script fails and the site knows you are using a blocker. It's a cat and mouse game, block the ad, detect the blocker, block the blocking detector and so on. 

For now, you'll have to do the VPN option, or we can try to figure out what domains are causing the detection and whitelist them, but that may end up with a side effect of allowing some ads through. Wired looks to offer a paid option for ad free browsing, so it becomes a question of diminishing returns.

**Comment by Verpz** [comment]
Thanks, I'll have a look into it.

**Comment by PromoFaux** [comment]
There is the option of using AAK scripts (as listed in the FAQ section of the wiki), which is enabled on a per-client/browser basis.

**Comment by Verpz** [comment]
When I tested it I had Anti-Adblock Killer enabled.

**Comment by PromoFaux** [comment]
Hmmm, that's interesting. I'm able to browse both forbes and wired with AAK, pi-hole, and ublock with easylist enabled....

**Comment by Verpz** [comment]
That's strange, what browser are you using? Also what method? I'm using Chrome and Tampermonkey.

**Comment by PromoFaux** [comment]
Same here, Chrome/Tampermonkey/uBlock/AAK list (subscribed from [this page](http://reek.github.io/anti-adblock-killer/#filterlist))

**Comment by Verpz** [comment]
I'm using Adblock Plus. Oh I whitelisted wired.com on ABP that is probably why.

**Comment by DL6ER** [comment]
@Verpz Concerning your feature request "Ability to use gravity.sh [...] from dashboard" see my PR [here](https://github.com/pi-hole/AdminLTE/pull/201).

**Comment by DL6ER** [comment]
`Select DNS server via Dashboard and / or use a custom one`: available for quite some time now

`Ability to add new ad lists via Dashboard`: https://github.com/pi-hole/AdminLTE/pull/252

**Comment by jacobsalmela** [comment]
Looks like most of these were checked off.  I opened or linked to existing votable feature requests on discourse.pi-hole.net for these: 

- [ ] [Weekly reporting for statistics ](https://discourse.pi-hole.net/t/long-term-statistics-for-pi-hole/1914/32)
- [ ] Client list - Gives the [ability to enable / disable ads just for individual clients](https://discourse.pi-hole.net/t/allow-temporary-and-allow-by-ip/1503)
- [ ] [A button to disable individual client's Internet access](https://discourse.pi-hole.net/t/a-button-to-disable-individual-clients-internet-access/3143)
