### ISSUE TITLE
Pi-hole on Pi0w does not reconnect to router after router power cycles

### ISSUE THREAD

**Issue by isaacmorgan** [pi-hole/pi-hole#3472]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

I am running Pi-hole on a Pi0w which connects to a router over wifi.
The router is using Pi-hole as its DNS.
When the router is power cycled I expect the Pi0w to reconnect to the router once the router has rebooted.
**Actual behaviour:**

When the router is power cycled the Pi0w does not reconnect to the router and is unresponsive to pings. This leaves the router without a DNS.

**Steps to reproduce:**

Install Pi-hole on a Pi0w operating in headless mode
- Install Raspberry Pi OS (32-bit) Lite on an SD card using the Raspberry Pi Imager.
https://www.raspberrypi.org/downloads/
- Setup a wireless connection to the router by adding a wpa_supplicant.conf file, and enable ssh connections by creating a ssh file.
https://core-electronics.com.au/tutorials/raspberry-pi-zerow-headless-wifi-setup.html
- Start up the Pi0w with the SD card, confirm it connects to the router and can be accessed using ssh.
- Log in to the Pi0w and install Pi-hole.

Set the Pi0w as the DNS for the router, verify it works.
Reboot the router.
The Pi0w will now no longer be connected to the router.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I cannot access the Pi0w because I do not have the cables. I only access it over ssh. I can access the SD card.

**Troubleshooting undertaken, and/or other relevant information:**

I have other Pi0w systems running the same version of Raspberry Pi OS that reconnect to the router just fine.
I've observed this behavior on Pi-hole v4.4 and v5.0, as well as earlier unrecorded versions.
The Pi0w does not lose power when the router does, mine is connected to a UPS.
Rebooting the Pi0w by unplugging it does not fix the problem.
The Pi0w has a static IP, I tried assigning a new IP. 
I tried cycling the router's channel manually from 1 - 11.

**Comment by dschaper** [comment]
How did you come to the conclusion that this is a problem caused by Pi-hole?

**Comment by isaacmorgan** [comment]
> 
> 
> How did you come to the conclusion that this is a problem caused by Pi-hole?

It may be a Pi-Hole dependency. I suspect it is not the router or Raspberry Pi OS or the Pi0w hardware because I have other Pi0w systems which reconnect after the router reboots.

**Comment by dschaper** [comment]
What does the contents of `/etc/dhcpcd.conf` show? How did you configure a static IP address? What does the Zero show for any errors with wpa_supplicant? 

Pi-hole is a DNS server, it starts after the network is online.

**Comment by isaacmorgan** [comment]
I do not have access to the system because it will not connect to wifi. I'm not sure how I can access the files otherwise.

The IP is assigned by the Router's own DHCP server, I manually assign it through the router's admin page.

**Comment by dschaper** [comment]
Check the files when you get access and make sure. Is there anything on the router logs showing a client DHCP request or a refusal to lease that reserved IP address?

**Comment by isaacmorgan** [comment]
The dhcpcd data looks correct for wlan0
[dhcpcd.conf.txt](https://github.com/pi-hole/pi-hole/files/4734270/dhcpcd.conf.txt)
The router logs only show the dhcp client binding the external IP.
Jun  4 21:10:55 rc_service: ntp 424:notify_rc restart_diskmon
Jun  4 21:10:55 disk_monitor: Finish
Jun  4 21:10:57 disk monitor: be idle
Jun  4 21:11:03 hour monitor: ntp sync fail, will retry after 120 sec
Jun  4 21:11:21 rc_service: udhcpc 855:notify_rc start_firewall
Jun  4 21:11:21 dhcp client: bound X.X.X.X via X.X.X.X during 6986 seconds.
I did not find any wpa_supplicant log files. 

In fact, I can't find any logs updated after the router restart. [June 4 21:20 EST : June 5 02:10]
daemon.log has last entry at 02:00
syslog at 02:00
pihole.log at 01:47

**Comment by dschaper** [comment]
`wlan0` is set with a static IP address, but you mentioned that you intended it to be assigned an address with DHCP on the router?

**Comment by isaacmorgan** [comment]
> 
> 
> `wlan0` is set with a static IP address, but you mentioned that you intended it to be assigned an address with DHCP on the router?
> 
> ```
> interface wlan0
>         static ip_address=192.168.1.4/24
>         static routers=192.168.1.1
>         static domain_name_servers=8.8.8.8 8.8.4.
> ```

Yes, I have used the router's DHCP Server to assign the Pi-hole machine the static IP 192.168.1.4
The router is 192.168.1.1

I have also made a copy of the SD card image.
I will see if I can find a way to log in to the machine.

**Comment by dschaper** [comment]
Then remove the `static` lines from the configuration file, wlan0 won't request a lease from the router when it's set to `static`.

**Comment by dschaper** [comment]
Side Note: This is pretty much why you don't want to have a vital network resource like a DNS server on WiFi.

**Comment by isaacmorgan** [comment]
> 
> 
> Then remove the `static` lines from the configuration file, wlan0 won't request a lease from the router when it's set to `static`.

Yes, I verified this prevents the issue using a fresh installation.
During installation Pi-hole sets the static address fields in dhcpcd.conf.
I removed these fields because a separate DHCP server is used, and restarted the service.
After rebooting the router the Pi0w reconnects as expected.
