### ISSUE TITLE
IPv4 etho0 interface value not updated in Settings page

### ISSUE THREAD

**Issue by baqwas** [pi-hole/pi-hole#3475]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Expect to see Dashboard reflect the static IPv4 address assigned to Pi-hole server eth0 interface in the file dhcpcd.conf`

**Actual behaviour:**

`ifconfig displays the assigned static IPv4 address for the eth0 interface but in Pi-hole Dashboard, navigating from Settings to System page displays the older IPv4 address for the eth0 interface.
`

**Steps to reproduce:**

`Edit dhcpcd.conf and enter static IPv4 address (including CIDR)
Reboot Pi-hole
Launch Pi-hole Dashboard and navigate to Settings page
The IPv4 address for the interface in use, eth0, does not change at all from the older value`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried many variations of addresses for the eth0 interface but Pi-hole does not display the changes`

How can I view the updated IPv4 address for the Pi-hole server in the Dashboard pages?

Apologies for a _newbie_ question that may be an operator/user issue. I did a cursory search on any past entry regarding this experience of mine but I could not find any (again perhaps I did not look deep enough).

Kind regards.

**Comment by yubiuser** [comment]
Run `pihole -r` and reconfigure.

**Comment by baqwas** [comment]
Sorry, this was a hasty post since Pi-hole has been running silently for nearly two and doing its job rather well.

I ran the command:
`pihole -r`

and all is well!

Sorry, again.

**Comment by yubiuser** [comment]
Your're welcome. 
I agree, it is not obvious that you have to run the commands after a change of the IP to "update" the web interface.
