### ISSUE TITLE
FTL offline

### ISSUE THREAD

**Issue by OlivierFerriot** [pi-hole/pi-hole#3476]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate.

**How familiar are you with the the source code relevant to this issue?:**
`1`

---
**Expected behaviour:**
`FTL online`

**Actual behaviour:**
`FTL Offline`

**Steps to reproduce:**
`Log-in to pi-hole. FTL is shown offline.`

**Debug token provided by [uploading `pihole -d` log]:**
`https://tricorder.pi-hole.net/84om6w651p`

**Troubleshooting undertaken, and/or other relevant information:**
```
Tried 'sudo service pihole-FTL restart' with no success.
Tried 'sudo service pihole-FTL status' :
pihole-FTL.service - LSB: pihole-FTL daemon
Loaded: loaded (/etc/init.d/pihole-FTL; generated)
Active: active (exited) since Sat 2020-06-06 20:13:48 CEST; 42min ago
Docs: man:systemd-sysv-generator(8)
Process: 11627 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

Jun 06 20:13:46 raspberrypi systemd[1]: Starting LSB: pihole-FTL daemon...
Jun 06 20:13:46 raspberrypi pihole-FTL[11627]: Not running
Jun 06 20:13:47 raspberrypi su[11651]: (to pihole) root on none
Jun 06 20:13:47 raspberrypi su[11651]: pam_unix(su:session): session opened for user pihole by (uid=0)
Jun 06 20:13:48 raspberrypi pihole-FTL[11627]: dnsmasq: failed to create listening socket for port 53: Address already in use
Jun 06 20:13:48 raspberrypi systemd[1]: Started LSB: pihole-FTL daemon.

```

**Comment by dschaper** [comment]
>`dnsmasq: failed to create listening socket for port 53: Address already in use`

There's another DNS server already in operation. It looks like `unbound`

[53] is in use by unbound (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
[53] is in use by unbound (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)

**Comment by OlivierFerriot** [comment]
Right, I did try to install unbound but stopped because the `/etc/unbound/unbound.conf.d/pi-hole.conf` file did not exist and it was late and totally forgot about that.
I'll try to finish the install and if I have another problem simply uninstall unbound.

Thanks :)

**Comment by OlivierFerriot** [comment]
Apparently not the file might be there but hidden, I tried to create the file and get an error `pi-hole.conf: Permission denied`
Have I missed something ?

**Comment by OlivierFerriot** [comment]
BTW how do I mark this issues as closed ?
Or do you need to do it ? (Please do if that's the case)

Thanks
