### ISSUE TITLE
multiple ip address when reconfigured change the ip address

### ISSUE THREAD

**Issue by starman2021** [pi-hole/pi-hole#3477]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Used the command "pihole -r" to change the IP address.  The result was the system now has two IP address.  I would expect it to replace the address instead of appending.

To correct the problem I edited two files:
/etc/dhcpd.conf  - which left the "interface ens33" with the old address
/etc/netplan/00-installer-config.yaml  - which only had the old address

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
How can we help you?

**Comment by starman2021** [comment]
Sorry - the templent really just confused me.

After reconfiguring the pi-hole server w/pihole -r, to use a different IP address, under ubuntu20 server - the previous IP address are retained.  Appears to be due to /etc/dhcpcd.conf.  

I've attached a screen capture of this file after several reconfigurations, along with the screen immediately after logon.

![pihole_dhcpcp_conf](https://user-images.githubusercontent.com/66538170/83975313-4354b200-a8c1-11ea-85b1-8c06aaf63c9e.png)

![pihole_logon](https://user-images.githubusercontent.com/66538170/83975315-451e7580-a8c1-11ea-97da-b7d0f8493fb2.png)

**Comment by dschaper** [comment]
This is intended. We do not remove IP addresses from `/etc/dhcpcd.conf` because we can not tell with any certainty that it was Pi-hole that added the entries. We do not want to remove an IP address that was manually added outside of the Pi-hole installation process.
