### ISSUE TITLE
Client description in query log

### ISSUE THREAD

**Issue by jcbvm** [pi-hole/pi-hole#3478]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The query log currently doesn't show de description which can be given to clients in the group management section. It would be helpful to show the description alongside the ip addresses in the query log, especially when pihole is not being used as DHCP server (so only ip addresses are shown).

**Actual behaviour:**

You can only see either the domain names (when using DHCP) or the ip addresses (when not using DHCP).

**Steps to reproduce:**

- Go to the group management section in the interface
- Define some clients with ip address -> description
- Go to the query log section in the interface
- The client column does not show the client's description

**Comment by yubiuser** [comment]
You might want to open a feature request at https://discourse.pi-hole.net/c/feature-requests/8

**Comment by jcbvm** [comment]
You are right. Will add it there. Closing this issue now.
