### ISSUE TITLE
This site spots I am running pi-hole

### ISSUE THREAD

**Issue by aleph-1** [pi-hole/pi-hole#348]
Not an issue, just an observation...

`http://www.forbes.com`

whatever this site is doing, it will only be a matter of time before many sites are doing it.
 
Keep up the great work guys

**Comment by dschaper** [comment]
How does the site react to your visit? Is there a message it displays?

**Comment by manuelgu** [comment]
I have seen that before but not looked into it in detail. They do not redirect you to the actual page but rather show a "You are using an AdBlocker message". Not too sure if there is a button for going to the site anyways.

A german website (www.bild.de) is doing something similiar, it blocks the entire webpage if you have adblocker/pihole.

**Comment by aleph-1** [comment]
its as manelgu says....

the message is " please  disable your ad blocker and try again" 

there is no getting past it (button, or by going direct to content pages)

**Comment by dschaper** [comment]
Interesting, I'll have to see if I can find out a workaround...

**Comment by PromoFaux** [comment]
I've just tried whitelisting a few domains belonging to `forbes.com`... no dice. I wonder how they're detecting.

**Comment by dschaper** [comment]
Are you using DNSThingy?

**Comment by PromoFaux** [comment]
Yep, and I threw all the domains at `whitelist.sh`

**Comment by dschaper** [comment]
Whoa, Just opening `forbes.com` and getting the interstitial screen shows like 30 domains!

**Comment by manuelgu** [comment]
www.bild.de proceeded against people that made tutorials / videos about how to bypass that (using two filter rules for adblocker). I can only speak for bild.de, but they are detecting it via JavaScript.

**Comment by dschaper** [comment]
I have cookies off, so I'm just getting a loop of the advert loading page...

**Comment by PromoFaux** [comment]
Interestingly. I've just completely disabled pi-hole and am still getting the message on forbes....

**Comment by dschaper** [comment]
Did you flush the client DNS cache? It may still have the old info for 300 seconds...

**Comment by manuelgu** [comment]
Yeah most likely, I can visit the page from school without any issues.

**Comment by PromoFaux** [comment]
Yep and the browser cache. And tried a different browser

**Comment by dschaper** [comment]
My Pihole is building a new kernel, I'll be able to play in about 20 minutes or so...

**Comment by aleph-1** [comment]
Thats weird - I have another machine (sitting on a vpn)  that is not affected (obviously no pi-hole)

**Comment by dschaper** [comment]
Forbes must be doing bad, that's one hell of an annoying way to welcome people to your site...

**Comment by PromoFaux** [comment]
Ah wait, I connected then disconnected to VPN and that properly flushed it

**Comment by ajp2k13** [comment]
Some sort of script blocker like noscript or umatrix might solve the problem, they will cause other breakage though but it's fixable. I always deny third party scripts, sometimes first party as well...

**Comment by dschaper** [comment]
I keep adding domains to the whitelist, and it Forbes keeps adding more domains on their trackers... They are trying to push Forbes Ad-Light?

**Comment by dschaper** [comment]
Basically what I think it's doing is making it so that you have to whitelist every single tracker domain they do business with in order to get into the site, and by doing that you're whitelisting those domains for every other website that is using them... Something is wrong there, and I don't mean wrong as in a bug but wrong as in doing massive data harvesting...

**Comment by dschaper** [comment]
https://www.reddit.com/r/Adblock/comments/3xfssl/how_to_use_forbescom_with_adblock/

**Comment by PromoFaux** [comment]
^ this. :+1: 

> Alternatively import these cookies:
[ { "domain": ".forbes.com", "hostOnly": false, "httpOnly": false, "name": "dailyWelcomeCookie", "path": "/", "secure": false, "session": false, "storeId": "0", "value": "true", "id": 3 }, { "domain": ".forbes.com", "hostOnly": false, "httpOnly": false, "name": "welcomeAd", "path": "/", "secure": false, "session": true, "storeId": "0", "value": "true", "id": 9 } ]

**Comment by PromoFaux** [comment]
I'm going to close this for now, as its not really something we can solve with pi-hole (being that we have an all or nothing approach to blocking.

There appear to be several ways around it using chrome/firefox extensions (see above comment by @dschaper .

We could perhaps document (or link to) some of those options in the FAQ.

**Comment by PromoFaux** [comment]
@aleph-1 can you try this out and let me know if you have any success:

https://github.com/reek/anti-adblock-killer

**Comment by PromoFaux** [comment]
updated [FAQ](../wiki/FAQs)

**Comment by aleph-1** [comment]
No biggie... thanks for the input! - it will get sorted ;)
