### ISSUE TITLE
DNS service not running randomly every few days

### ISSUE THREAD

**Issue by homunculus39** [pi-hole/pi-hole#3484]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I am expecting the pihole DNS server to not fail randomly.`

**Actual behaviour:**

`DNS completely fails and I cannot resolve any webpages and the web UI lags when attempting to load it.`

![image](https://user-images.githubusercontent.com/35180652/84081060-22a85d00-a992-11ea-8661-30a911cd94fd.png)

![image](https://user-images.githubusercontent.com/35180652/84081585-1a9ced00-a993-11ea-991c-c3aca34b3314.png)

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/35180652/84081180-56838280-a992-11ea-9bc9-405f9366869f.png)

![image](https://user-images.githubusercontent.com/35180652/84081657-3bfdd900-a993-11ea-8d3b-5605910d49d6.png)

![image](https://user-images.githubusercontent.com/35180652/84081683-48823180-a993-11ea-9c6e-09670dcddf54.png)

`It constantly occurs randomly on its own. I have no control over reproducing it other than what is described later on.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`59xx0u927p`

Full URL:  https://tricorder.pi-hole.net/59xx0u927p

**Troubleshooting undertaken, and/or other relevant information:**

`I have attempted to restart the DNS server and that is all. I have uploaded my results up above as I do not know what to do from here. The issue seems to keep occurring randomly during the week once a week, this just happened 20 minutes ago and the entire network was down. I have a cron job to restart the pi everyday at 3am, which helps it from happening more frequently, otherwise, it happens nearly everyday mid-day, but no guarantee as it is unexpected.  Please help.`

**Comment by volcano4life** [comment]
getting the same issues here as well.. now a new one - whenever I hit gravity update, the whole service crashes...  When I do pihole -g via terminal, DNS resolution crashes also. Does not restart until I kill the pihole -g command.

**Comment by dschaper** [comment]
Are you both using `cloudflared` as an upstream?

**Comment by volcano4life** [comment]
I definitely am

**Comment by dschaper** [comment]
Okay, then both of you are. Try not using `cloudflared` and see if things are more stable.

**Comment by volcano4life** [comment]
Disabled cloudflare. Just hit gravity update still crashing the DNS service.
Tried pihole -g in gravity - still crashing dns...
![image](https://user-images.githubusercontent.com/60669021/84085214-0382ed00-a9dd-11ea-8d3a-1aa8488e9d97.png)

**Comment by dschaper** [comment]
Since this is homunculus39's issue and your issue is different please open a new issue.

**Comment by homunculus39** [comment]
> Are you both using `cloudflared` as an upstream?

Hey there! Thanks for swinging by to try and help.

I am used `cloudflared` because it's pretty sexy!.. I really want to continue using it. Before I have been using the standard cloudflare server without cloudflared, there were no problems. I can confirm this.

Is there any way around this? The reason why `cloudflared` makes this happen?

I can make the Pi-hole reboot more frequently if that's what is needed...

**Comment by dschaper** [comment]
`cloudflared` isn't something we write or maintain. I can't give you any guidance on how to make that package work.

**Comment by homunculus39** [comment]
> `cloudflared` isn't something we write or maintain. I can't give you any guidance on how to make that package work.

I figured as much... not a problem. I wrote a script to continuously check for server status and upon failure, log and restart cloudflared. Hopefully this advice helps whoever else comes across the issue. 
Whoever runs into this issue, run a cronjob every 5 minutes as such below in the bash script. Don't forget to make the script executable. 

`#!/bin/bash
#"cron is: */5 * * * *"
if pihole status | grep -q 'DNS is NOT running'; then
  pihole restartdns
  systemctl restart cloudflared.service
  echo "DNS is NOT running at $(date)" >> /var/log/pihole/dns_uptime.log
  else
  echo "DNS is online at $(date)" >> /var/log/pihole/dns_uptime.log
fi
`
If anyone needs it. 

I'll leave this open if someone else would like to contribute to the thread.

**Comment by dschaper** [comment]
Closed threads still show up in searches and can still be commented on.

**Comment by homunculus39** [comment]
Quite honestly just happy that others are experiencing the same issue. Hopefully something can be patched programmatically speaking.

**Comment by themaverick** [comment]
Solution to this issue:

https://github.com/themaverick/pihole-patches/tree/master
