### ISSUE TITLE
action black/whitelist does act on default-list.

### ISSUE THREAD

**Issue by Binog** [pi-hole/pi-hole#3486]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{If a click on "whitlist/blacklist a domain action" in a recent query for my phone, this e.g. waitlisted domain is alined to a choosable group-list.}`

**Actual behaviour:**

`{If a click on "whitlist/blacklist a domain action" in a recent query for my phone, this e.g. waitlisted domain is alined to the default blocking list. You can't decide which one it should be alined to}`

**Steps to reproduce:**

`{see above}`

**Comment by yubiuser** [comment]
This is not an issue but the (current) intended behavior. If you wish to add the ability to choose to which group a domain from query log should be added please open a feature request at discourse.

https://discourse.pi-hole.net/c/feature-requests/8

**Comment by Binog** [comment]
Thanks, I do so. Why is it intended? Doesn't it make sense to be able to be more specific, while I admit, this might be the default entry...

**Comment by yubiuser** [comment]
I can see benefit in the ability as well (although the list might get very long if you have a lot of groups). But the devs simply couldn't implement every possible feature so far as they are all volunteers and do the work in their free time. As there is a way already to switch group assignment for a domain after it has been added, this might be low priority feature to add.

**Comment by dschaper** [comment]
It's not really 'intended behavior' in the sense that it's that way because it needs to be. That's just how it happens to be currently. 

The best way to get improvements like this in the code is to work on it and then open a Pull Request with the code changes. Otherwise it will go on the Feature Request list and will have to wait until someone gets to it.
