### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by JPluess** [pi-hole/pi-hole#3487]
Hi there, 
I like pihole, here is a small contribution, 

1. changing settings i have my preference for example, i like to see all 100 entries, it can be changed from 10 25 50 100 to All entries....
i would like those kind of settings stored, so if i open the admin panel on any other device it would remember how i used last time. (i do not know if it needs to remember settings for each device...maybe?)

2. the queries tab, can it have a setting for auto refresh? (Realtime? or each second?)

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by yubiuser** [comment]
> the queries tab, can it have a setting for auto refresh? (Realtime? or each second?)

Please don't open a new feature request on this one. There are already a few out there. Vote for one of them.
