### ISSUE TITLE
 Error: Unable to update package cache. Please try "apt-get update"

### ISSUE THREAD

**Issue by cjiten** [pi-hole/pi-hole#3488]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._
![Screenshot from 2020-06-12 15-31-13](https://user-images.githubusercontent.com/66844155/84533598-16abfa80-ad06-11ea-85d7-e1d30e5fa1ce.png)
![Screenshot from 2020-06-12 15-29-52](https://user-images.githubusercontent.com/66844155/84533609-1ca1db80-ad06-11ea-91d3-a9bf9d82d9c6.png)
![Screenshot from 2020-06-12 15-29-24](https://user-images.githubusercontent.com/66844155/84533630-23c8e980-ad06-11ea-9412-713ff944876c.png)

i try many times i am using ubuntu 20.04LTS pls help me
commend line is not working
pls reply early

**Comment by cjiten** [comment]
i use command line 
curl -sSL https://install.pi-hole.net | bash
The command line works fine on ubuntu 18.04 but it is not working on ubuntu 20.04

**Comment by dschaper** [comment]
This is intended.

If `apt-get update` does not complete cleanly then we will not install. Fix the `Err` line and associated `E:` and `N:` lines.

**Comment by cjiten** [comment]
how i fix , i'm be beginner help me to resolve the issue

**Comment by cjiten** [comment]
![Screenshot from 2020-06-13 10-14-55](https://user-images.githubusercontent.com/66844155/84560159-c6ad5200-ad5e-11ea-8d94-e6695b5cd58b.png)

**Comment by dschaper** [comment]
That's outside of what we support.

**Comment by cjiten** [comment]
ok thanks
