### ISSUE TITLE
ability to add multiple blocklists broken in v5

### ISSUE THREAD

**Issue by thewriteway** [pi-hole/pi-hole#3495]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

pi-hole is able to add multiple blocklists on groups-adlists.php

**Actual behaviour:**

pi-hole only adds first list in text format before the comma and fails on all others with the following error message:
Error, something went wrong!
Invalid adlist URL ,

**Steps to reproduce:**

attempt add multiple lists separated by comma on groups-adlists.php

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A as issue not unique to my setup

**Troubleshooting undertaken, and/or other relevant information:**

1) Attempted to leave space before and after comma.
2) tried with different lists and ordering, issue still occurs.

**Comment by dschaper** [comment]
Separate them with spaces.

**Comment by thewriteway** [comment]
cheers, that worked. can the line be updated to not show a comma as an example?

**Comment by thewriteway** [comment]
I also found additional related issue - adding a list with one duplicate causes the rest of the list to fail to be added:
"Error, something went wrong!
While executing: UNIQUE constraint failed: adlist.address
Added 7 out of 34 adlists."

**Comment by thewriteway** [comment]
this seems to be somewhat similar to https://github.com/pi-hole/pi-hole/issues/3364, however in this case the add function is failing to import actual valid entries because of one or more unknown dupes.

**Comment by yubiuser** [comment]
> cheers, that worked. can the line be updated to not show a comma as an example?
fixed in v5.1
![Bildschirmfoto zu 2020-06-16 10-21-49](https://user-images.githubusercontent.com/26622301/84750232-4df70180-afbb-11ea-987d-f3700f36b73e.png)


>"Error, something went wrong!
While executing: UNIQUE constraint failed: adlist.address
Added 7 out of 34 adlist

Fixed in v5.1 

https://github.com/pi-hole/AdminLTE/pull/1449

**Comment by thewriteway** [comment]
thanks guys, awesome work!
