### ISSUE TITLE
Pi Hole dns service stops randomly 

### ISSUE THREAD

**Issue by leonbrag** [pi-hole/pi-hole#3502]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---

Latest version of pi hole 5.0 is running on Ubuntu 20.04. Twice over the course of two weeks dns service just stops. Pi hole admin web page states “dns service is not running”. 

Restarting dns service via setting page gets pihole running again. 

What logs can I provide to identify root cause ?

**Comment by yubiuser** [comment]
`/var/log/pihole-FTL.log`

**Comment by leonbrag** [comment]
It's a crash:

```
[2020-06-17 17:25:27.292 362158] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-06-17 17:25:27.292 362158] ---------------------------->  FTL crashed!  <----------------------------
[2020-06-17 17:25:27.292 362158] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-06-17 17:25:27.292 362158] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-06-17 17:25:27.292 362158] and include in your report already the following details:
[2020-06-17 17:25:27.292 362158] FTL has been running for 24523 seconds

```

What is a next step to find root cause? It happened second time and previous version was rock solid

**Comment by leonbrag** [comment]
Dup of https://github.com/pi-hole/FTL/issues/812

**Comment by leonbrag** [comment]
dup https://github.com/pi-hole/FTL/issues/812

**Comment by yubiuser** [comment]
No, ist not 812 it is this one:
https://github.com/pi-hole/FTL/issues/757

**Comment by teckel12** [comment]
@dschaper Here's a tip on the correct way to interface with users.

That's an interesting issue.  It appears the date/time changed causing the database to freak out and the app to crash.  Could you monitor the date for the next few days and see if it's drifting?

See, it's really not so hard.  Basically, it's customer support 101.  Give it a try, you'll spend less time dealing with issues and won't be perceived as such an elitist.

**Comment by jfb-pihole** [comment]
> @dschaper Here's a tip on the correct way to interface with users.

How is this comment related to this issue and this post?
