### ISSUE TITLE
query not working

### ISSUE THREAD

**Issue by doadin** [pi-hole/pi-hole#3506]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour: show domains matched under list

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
pihole query -q -all doubleclick
[i] No results found for -qdoubleclick within the block lists

though web interface says:
  [i] Over 100 results found for doubleclick
        This can be overridden using the -all option

**Comment by yubiuser** [comment]
The syntax is wrong. Either use
`pihole query -all doubleclick` or `pihole -q -all doubleclick`

**Comment by doadin** [comment]
opps didn't notice it changes -q is for query read the help and figured the options where just added to query.
