### ISSUE TITLE
Separate files in /etc/pihole into real config and (temporary data)

### ISSUE THREAD

**Issue by Cyber1000** [pi-hole/pi-hole#3508]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Actual behaviour:**
I would see this as a improvement, not a bug, but not really as a feature (I would use discourse therefore)
I'm using docker, but I don't think it's docker-related:
In my /etc/pihole (which I map as a volume) I'm getting this:
```
 dns-servers.conf                         
 GitHubVersions                           
 gravity.db                               
 list.0.raw.githubusercontent.com.domains 
 list.1.mirror1.malwaredomains.com.domains
 list.2.s3.amazonaws.com.domains          
 list.3.s3.amazonaws.com.domains          
 localbranches                            
 local.list                               
 localversions                            
 migration_backup                         
 pihole-FTL.conf                          
 pihole-FTL.db                            
 setupVars.conf                           
 setupVars.conf.update.bak 
```
- Some of this seem to be configs -> dns-servers.conf ,  setupVars.conf 
- Some seem to be data which could be recreated on restart: list.0.raw.githubusercontent.com.domains, ...
- gravity.db seems to mix data like adlist (can be recreated, expect this to be downloaded?) and whitelist/blacklist (more like a user-config, since it's nothing you download from somewhere)

**Expected behaviour:**
I would expect that:
- configs are in etc
- downloaded (black)lists are in a var-folder (or something similar)
- gravity.db is split somehow in a db which can be recreated (adlist) and a part which is solely for storing whitlists/blacklists (or other user-information, I missed out)

**Steps to reproduce:**
- Start docker (or pi-hole drectly?)
- look at the files in /etc/pihole, are they really etc or more like var?

**What's the purpose on this**
- I'm commiting my local docker-configs with git
   - I would only commit real configs
   - files that can be recreated by downloading, would go on a volume (which isn't backed up)
   - whitelists/blacklists would be saved as "service-data" daily backed-up ...
- I know I could do some .gitignores and some tricks to have the same effect, but that wouldn't be future-proof and it doesn't feel valid for me to have everything in /etc

Thanks for this project!

**Comment by dschaper** [comment]
This really is a feature request.

**Comment by Cyber1000** [comment]
ok convinced ...
Then I'll move this to discourse and close this here.
Thanks for reading!

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/separate-files-currently-in-etc-in-real-config-setupvars-conf-tempdata-list-0-raw-githubusercontent-com-domains-and-userdata-whitelist-blacklist/34980/5
