### ISSUE TITLE
PiHole returning IPv6 addresses when IPV6 is set to not resolve

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#3511]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
PiHole should not resolve IPV6 addresses when these are set:
```
RESOLVE_IPV6=no
```

**Actual behaviour:**

When I nslookup the IPs from a device such as my phone or PC, I can see the IPV6 address (not working). However, when I nslookup from the PiHole itself, no IPV6 address is provided (working)

**Steps to reproduce:**

I have attached screenshots below, but basically just nslookuping facebook.com or google.com show me IPV6 addresses on machines (except the PiHole itself).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/n2qfbr79n6

**Troubleshooting undertaken, and/or other relevant information:**

I have been playing with various versions of
```
ANALYZE_ONLY_A_AND_AAAA=true
AAAA_QUERY_ANALYSIS=no
RESOLVE_IPV6=no
```
![image](https://user-images.githubusercontent.com/9235633/85501221-ec362900-b5b2-11ea-9cb2-24de26f541a2.png)

Apologies for any errors, or if I have overlooked something.
I really appreciate you reading my issue. Thanks and have a great day.

**Comment by dschaper** [comment]
Pi-hole isn't answering the queries.

```plain
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the tun0 interface:
   10.8.0.1/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

[✗] No IPv6 address(es) found on the tun0 interface.

[i] Default IPv4 gateway: 192.168.1.1
   * Pinging 192.168.1.1...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)


*** [ DIAGNOSING ]: Ports in use
*:22 systemd (IPv6)
*:5355 systemd-re (IPv4)
*:5355 systemd-re (IPv6)
*:5938 teamviewer (IPv6)
*:5938 teamviewer (IPv4)
127.0.0.1:5948 teamviewer (IPv4)
*:82 lighttpd (IPv4)
*:82 lighttpd (IPv6)
*:445 lighttpd (IPv4)
[53] is in use by unbound (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
127.0.0.1:8953 unbound (IPv4)
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)
*:7070 anydesk (IPv4)
127.0.0.1:37688 cloudflare (IPv4)
127.0.0.1:5353 cloudflare (IPv4)
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[4711] is in use by pihole-FTL
[4711] is in use by pihole-FTL
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)
[80] is in use by apache2 (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
*:444 apache2 (IPv4)
*:443 apache2 (IPv4)

```

**Comment by p1r473** [comment]
I am also using PiVPN, but PiHole is for sure doing the resolution:

![image](https://user-images.githubusercontent.com/9235633/85509774-8783ca00-b5c4-11ea-8b26-7f8fb1ce2ab1.png)

**Comment by dschaper** [comment]
`[53] is in use by unbound (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)`

**Comment by p1r473** [comment]
I have Unbound listening on 127.0.0.2.

**Comment by dschaper** [comment]
So where is 192.168.1.186?

**Comment by p1r473** [comment]
192.168.1.186 is my PiHole itself

**Comment by dschaper** [comment]
That's 10.8.0.1 according to the log.

**Comment by p1r473** [comment]
Thats just the PiVPN IP. I have PiHole running on both eth0 (192.168.1.186)  and tun0  (10.8.0.1)
Disabled Unbound and regenerated the debug:
https://tricorder.pi-hole.net/w6c8xagpv1

Here's my ifconfig showing I'm 192.168.1.186 on the PiHole:

```

root@Harbormaster:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.186  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::efa3:c9ae:1a2:6e92  prefixlen 64  scopeid 0x20<link>
        ether 88:d7:f6:c2:e6:d1  txqueuelen 1000  (Ethernet)
        RX packets 184485  bytes 32840639 (31.3 MiB)
        RX errors 5  dropped 6  overruns 0  frame 0
        TX packets 70907  bytes 32104940 (30.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 43

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 214139  bytes 17389513 (16.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 214139  bytes 17389513 (16.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 516  bytes 40040 (39.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 438  bytes 144538 (141.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 40:9f:38:2f:10:31  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by p1r473** [comment]
In this image you can see that my PC is getting the resolution from hostname "Harbormaster", thats the Pi. You can see the hostname in the right side on the PiHole side.
https://user-images.githubusercontent.com/9235633/85501221-ec362900-b5b2-11ea-9cb2-24de26f541a2.png

**Comment by dschaper** [comment]
You can't have two interfaces configured like this. Only one interface line is allowed:
```plain
*** [ DIAGNOSING ]: Setup variables
    PIHOLE_INTERFACE=eth0
    PIHOLE_INTERFACE=tun0
```

If Pi-hole itself (on Harbormaster) is correct then the Windows client is getting information from somewhere else. Does the Pi-hole admin page show any AAAA queries answered? Does a tail of the logs show any AAAA queries answered?

**Comment by dschaper** [comment]
You also have malformed configuration lines:

`   [2020-06-24 00:49:14.864 2322] Warning: Invalid regex blacklist filter "^(r([0-9]+)(---|\.))?sn([a-z-0-9.])+\.googlevideo.com": Invalid range end (error code 11)`

**Comment by p1r473** [comment]
Actually, running PiHole on 2 interfaces has been working great. My PiVPN connects my phone to my Pi so I have DNS adblocking over LTE/4G/5G. And, my local network has adblocking.

/etc/dnsmasq.d/05-pivpn.conf:
```
interface=tun0
addn-hosts=/etc/pivpn/hosts.openvpn
```
/etc/dnsmasq.d/03-custom.conf:
```
interface=eth0
listen-address=127.0.0.1
bind-interfaces
port=53
cache-size=150
```

Because I am using the bind-interfaces command, I am able to use both interface.


I had followed these 2 tutorials to set up PiVPN:

https://blog.crankshafttech.com/2019/12/set-up-pihole-with-doh-and-pivpn.html
https://marcstan.net/blog/2017/06/25/PiVPN-and-Pi-hole/


It works great,

Anyways, I have disabled PiVPN and Unbound to make the logs less confusing:
This should be with both Unbound and PiVPN off, sorry about that:
https://tricorder.pi-hole.net/n8qe2birhr

**Comment by p1r473** [comment]
> You can't have two interfaces configured like this. Only one interface line is allowed:
> 
> ```
> *** [ DIAGNOSING ]: Setup variables
>     PIHOLE_INTERFACE=eth0
>     PIHOLE_INTERFACE=tun0
> ```
> 
> If Pi-hole itself (on Harbormaster) is correct then the Windows client is getting information from somewhere else. Does the Pi-hole admin page show any AAAA queries answered? Does a tail of the logs show any AAAA queries answered?

I did use nslookup 192.168.1.186 and so it is going to hit port 53 on Harbormaster, which is the PiHole

No, I don't see any AAAA queries answered
![image](https://user-images.githubusercontent.com/9235633/85511687-fbbf6d00-b5c6-11ea-81f2-7c42057db9e5.png)

**Comment by dschaper** [comment]
My statement in regards to two interface lines in setupVars wasn't a guess or a suggestion. You can't have two lines there.

If no AAAA queries are on the page and same for the log then Pi-hole isn't the one supplying the AAAA records.

**Comment by p1r473** [comment]
> My statement in regards to two interface lines in setupVars wasn't a guess or a suggestion. You can't have two lines there.
> 
> If no AAAA queries are on the page and same for the log then Pi-hole isn't the one supplying the AAAA records.

Even with Unbound and PiVPN disabled, I still see it:
![image](https://user-images.githubusercontent.com/9235633/85511875-4640e980-b5c7-11ea-87d7-9bd0c291820f.png)


Let me try and delete one of those two statements and reload the PiHole.

**Comment by dschaper** [comment]
If you don't see AAAA queries in the Pi-hole Query log then Pi-hole isn't the one supplying the IPs.

Have you modified `/etc/dnsmasq.d/01-pihole.conf` manually?

**Comment by p1r473** [comment]
> If you don't see AAAA queries in the Pi-hole Query log then Pi-hole isn't the one supplying the IPs.
> 
> Have you modified `/etc/dnsmasq.d/01-pihole.conf` manually?

I have in the past modified that. 
```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list

localise-queries
no-resolv
log-queries
log-facility=/var/log/pihole.log
local-ttl=2
log-async

server=127.0.0.1#5353
domain-needed
bogus-priv
dnssec
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

local-service
server=/use-application-dns.net/
```

**Comment by p1r473** [comment]
> If you don't see AAAA queries in the Pi-hole Query log then Pi-hole isn't the one supplying the IPs.
> 
> Have you modified `/etc/dnsmasq.d/01-pihole.conf` manually?

Somehow it is still blocking though. Ads are blocked, and ads.google.com resolves to 0.0.0.0

Let me try and reboot after making the SetupVars changes.

**Comment by dschaper** [comment]
I will say this one last time. If you don't see AAAA queries in the Pi-hole Query log then Pi-hole isn't the one supplying the IPs.

**Comment by dschaper** [comment]
Make sure `AAAA_QUERY_ANALYSIS=no` is not set while you are trying to figure out what is going on.

**Comment by dschaper** [comment]
You can also run `grep -F [AAAA] /var/log/pihole.log` to see who is querying for what.

**Comment by p1r473** [comment]
> Make sure `AAAA_QUERY_ANALYSIS=no` is not set while you are trying to figure out what is going on.

I un-set this variable and am now seeing AAAA in the logs. Good catch.
So PiHole is indeed resolving AAAA even though I am using RESOLVE_IPV6=no
Is that supposed to happen?
My limited understanding is AAAA is IPv6, but if I am not resolving IPv6, then should Pihole be doing AAAA?


![image](https://user-images.githubusercontent.com/9235633/85513465-0aa71f00-b5c9-11ea-96a0-a9b2145efbeb.png)

heres a debug with unbound stopped, pivpn disabled, and the setup vars fixed (hopefully that's all working)
https://tricorder.pi-hole.net/66puva51xy

**Comment by dschaper** [comment]
`[2020-06-24 00:05:47.479 960]    RESOLVE_IPV6: Don't resolve IPv6 addresses`

@DL6ER

**Comment by p1r473** [comment]
PiHole seems to be the culprit:

![image](https://user-images.githubusercontent.com/9235633/85514043-9ae56400-b5c9-11ea-9299-b64dc02e50b7.png)
My PC, 192.168.1.69, is requesting the AAAA even though RESOLVE_IPV6=no is off

Sorry is I am missing or overlooking something

**Comment by yubiuser** [comment]
Have a look in the doc
>RESOLVE_IPV6=yes|no
Should FTL try to resolve IPv6 addresses to hostnames?

https://docs.pi-hole.net/ftldns/configfile/#resolve_ipv6

It's not about resolving domains to IPs, but for IPs to hostnames (I guess for the web interface)

**Comment by p1r473** [comment]
> Have a look in the doc
> 
> > RESOLVE_IPV6=yes|no
> > Should FTL try to resolve IPv6 addresses to hostnames?
> 
> https://docs.pi-hole.net/ftldns/configfile/#resolve_ipv6
> 
> It's not about resolving domains to IPs, but for IPs to hostnames (I guess for the web interface)

OK, so its working as intended, and my PC should get the AAAA even though I am trying to suppress IPV6?

Is there a different command I should have been doing, for turning off IPV6 resolution on the PiHole?

**Comment by yubiuser** [comment]
>AAAA_QUERY_ANALYSIS=no
Allow FTL to analyze AAAA queries from pihole.log?

>ANALYZE_ONLY_A_AND_AAAA=|true
Should FTL only analyze A and AAAA queries?

**Comment by p1r473** [comment]
> > AAAA_QUERY_ANALYSIS=no
> > Allow FTL to analyze AAAA queries from pihole.log?
> 
> > ANALYZE_ONLY_A_AND_AAAA=|true
> > Should FTL only analyze A and AAAA queries?

I was running with:
```
ANALYZE_ONLY_A_AND_AAAA=true
AAAA_QUERY_ANALYSIS=no
RESOLVE_IPV6=no
```

And the PC was still getting the IPV6 addresses

**Comment by yubiuser** [comment]
I know but I don't know where those AAAA records came from....

**Comment by p1r473** [comment]
> `[2020-06-24 00:05:47.479 960] RESOLVE_IPV6: Don't resolve IPv6 addresses`
> 
> @DL6ER

I think what DSChaper may be saying is currently PiHole may be ignoring the IPV6 disabling the commands

**Comment by un99known99** [comment]
tested, it is NOT working, still v6 and v4 despite parameter set




Am 24.06.2020 um 09:45 schrieb yubiuser:

**Comment by yubiuser** [comment]
You're right I can (partly) resolve AAAA despite `AAAA_QUERY_ANALYSIS=no` and pihole restartdns

 ```
[2020-06-24 10:08:50.413 15570]    AAAA_QUERY_ANALYSIS: Hide AAAA queries
[2020-06-24 10:08:50.414 15570]    MAXDBDAYS: max age for stored queries is 90 days
[2020-06-24 10:08:50.414 15570]    RESOLVE_IPV6: Resolve IPv6 addresses
[2020-06-24 10:08:50.414 15570]    RESOLVE_IPV4: Resolve IPv4 addresses
[2020-06-24 10:08:50.414 15570]    DBINTERVAL: saving to DB file every minute
[2020-06-24 10:08:50.414 15570]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2020-06-24 10:08:50.414 15570]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2020-06-24 10:08:50.414 15570]    PRIVACYLEVEL: Set to 0
[2020-06-24 10:08:50.414 15570]    IGNORE_LOCALHOST: Show queries from localhost
[2020-06-24 10:08:50.414 15570]    BLOCKINGMODE: Null IPs for blocked domains
[2020-06-24 10:08:50.414 15570]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
```

```
chrko@ThinkPad-X230:~$ nslookup -query=AAAA facebook.com
Server:		10.0.1.5
Address:	10.0.1.5#53

Non-authoritative answer:
Name:	facebook.com
Address: 2a03:2880:f1ff:83:face:b00c:0:25de
```

```
Jun 24 10:15:06 dnsmasq[15572]: query[AAAA] discovery.syncthing.net from 10.0.10.182
Jun 24 10:15:06 dnsmasq[15572]: cached discovery.syncthing.net is 2a03:b0c0:0:1010::bb:4001
Jun 24 10:15:06 dnsmasq[15572]: cached discovery.syncthing.net is 2400:6180:100:d0::741:a001
--
Jun 24 10:15:21 dnsmasq[15572]: query[AAAA] www.google.com from 10.0.99.33
Jun 24 10:15:21 dnsmasq[15572]: forwarded www.google.com to 127.0.0.1
Jun 24 10:15:21 dnsmasq[15572]: reply www.google.com is 2a00:1450:4001:820::2004
--
Jun 24 10:15:46 dnsmasq[15572]: query[AAAA] www.google.com from 10.0.99.192
Jun 24 10:15:46 dnsmasq[15572]: cached www.google.com is 2a00:1450:4001:820::2004
Jun 24 10:15:57 dnsmasq[15572]: query[A] ping.ubnt.com from 10.0.1.1
--
Jun 24 10:16:02 dnsmasq[15572]: query[AAAA] facebook.com from 10.0.10.182
Jun 24 10:16:02 dnsmasq[15572]: forwarded facebook.com to 127.0.0.1
Jun 24 10:16:02 dnsmasq[15572]: reply facebook.com is 2a03:2880:f1ff:83:face:b00c:0:25de

```

**Comment by yubiuser** [comment]
Maybe the hint is

`AAAA_QUERY_ANALYSIS: Hide AAAA queries`

As it is only hiding them in the query log but doesn't stop to resolve them?

**Comment by p1r473** [comment]
I tried it with Amazom.com, didn't give any IPV6, so either they don't have an IPV6  or as you say, it is just partly resolving IPV6

**Comment by p1r473** [comment]
The weird part is, when I do nslookup on my Pi, it doesn't show the IPv6.
When I do nslookup on PC or phone, I do see IPv6.

**Comment by yubiuser** [comment]
I think we have a misunderstanding here. Reading the doc again

>AAAA_QUERY_ANALYSIS=yes|no
Allow FTL to analyze AAAA queries from pihole.log?

it states just that you can switch on/off the analysis of `pihole.log` by pihole. More info can be found here
https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652

It is not intended to block AAAA queries but to show/hide them in the web interface. 

I guess at the moment there is no option to "block" or "dont resolve" AAAA queries.
If you don't have IPv6 (as I do) clients can't use the returned IPv6 addresses so it won't harm but of course it increases unnecessary traffic.
Having an option to not forward AAAA queries seems like a good feature request.

A possible workaround is here:
https://discourse.pi-hole.net/t/solved-disable-aaaa-response-for-a-given-domain/13143

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/option-to-block-not-forward-all-aaaa-queries/34837/9

**Comment by p1r473** [comment]
Any idea why then, when doing nslookup on the Pi itself, it doesn't show the IPv6?

**Comment by DL6ER** [comment]
Okay, we have two things here. I have answers for both :-)

# Issue 1: `RESOLVE_IPV6`

> `[2020-06-24 00:05:47.479 960] RESOLVE_IPV6: Don't resolve IPv6 addresses`

As mentioned already, this is only about if FTL should try to resolve IP addresses to host names *internally*.
We do this for clients and upstream DNS servers and only for the sake of a nicer display on the web interface. There is no influence on the processing of queries at all.

However, as you have already seen, this is actually currently broken in v5.0. You can get the expected behavior in v5.0 only when **also** setting `DEBUG_RESOLVER=true`. This is [already fixed for v5.1](https://github.com/pi-hole/FTL/pull/792).

# Issue 2: `AAAA_QUERY_ANALYSIS`

>> `AAAA_QUERY_ANALYSIS=yes|no`
>> Allow FTL to analyze AAAA queries from pihole.log?
>
> It is not intended to block AAAA queries but to show/hide them in the web interface.

Yes. This description comes back from the very first days of FTL when it was still parsing `dnsmasq.log` to get information. This is obsolete since the advent of *FTL*DNS which embeds `dnsmasq` directly and gains knowledge directly from within the DNS server (the pihole.log file is entirely obsolete since almost two years now).

Thinking again about this, I think we should remove it altogether rather than fixing the documentation. There isn't much reasoning left to do this. I'm open to conviction and thankful for hints when you think this is not true.

**Comment by DL6ER** [comment]
Concerning issue 2: See https://github.com/pi-hole/FTL/pull/817

**Comment by p1r473** [comment]
So if I understand correctly (and that's a big if!), no way to stop the PiHole from serving IPv6 responses right?
It's not a big deal, was just trying to clean up my nslookup output.

**Comment by DL6ER** [comment]
> no way to stop the PiHole from serving IPv6 responses right?

You are right. I still don't think this is necessary. There is no harm in when the phone book tells you an address you know you cannot call.

**Comment by p1r473** [comment]
No problem at all. Just thought it was a bgg.
Last question @DL6ER any idea why, when I nslookup on the Pi, it excludes the IPv6, but on PC/Android when I nslookup, it returns it?

**Comment by DL6ER** [comment]
`nslookup` is implementation-specific, it may very well be that the behavior is just different on the different platforms. Resort to using a standardized tool, if possible.

For instance, you can run
```
dig A facebook.com @192.168.1.186
dig AAAA facebook.com @192.168.1.186
dig ANY facebook.com @192.168.1.186
```
on your Pi for testing. This explicitly states what you want to know from the DNS server instead of relying that `nslookup` picks the proper question for your problem.

**Comment by p1r473** [comment]
Thanks as always @DL6ER  @dschaper @yubiuser mystery solved, thanks again for all your help and all your time, and have a great week :)
