### ISSUE TITLE
Include groups when querying lists on admin/queryads.php

### ISSUE THREAD

**Issue by rossc719g** [pi-hole/pi-hole#3512]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

When you go to "Tools -> Query Lists" and query a domain, the results come back indicating which list(s) include the domain.  It would be very nice if it included which group(s) the lists are in.

E.g.:

 Exact match found in exact whitelist
   gstaticadssl.l.google.com
 Exact match for gstaticadssl.l.google.com found in:
  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt [Group1, Group3]

**Actual behaviour:**

Groups are not included in the results.

E.g.:

 Exact match found in exact whitelist
   gstaticadssl.l.google.com
 Exact match for gstaticadssl.l.google.com found in:
  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Steps to reproduce:**

go to "Tools -> Query Lists" and query a domain

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/8ov8o1pupl

**Troubleshooting undertaken, and/or other relevant information:**

This is useful because it makes it easy to know what action to take when whitelisting.
E.g., if a user complains that they cannot access some.site.com, I can search the query lists for some.site.com.

If it turns out that the blocklist is part of "Experimental", then a good solution is probably to remove the impacted client(s) from that experimental group.

If the blocklist is part of "VeryVeryBadSites", then I can talk the user out of this. 

If the blocklist in part of "ThingsWeUsuallyBlockForGoodReason", then I add a whitelist for this client.

I can still get the information today by copy/pasting the results one by one into the browser's search box on the blocklist page... but it is inconvenient and less user friendly.

**Comment by yubiuser** [comment]
Please open feature requests at
https://discourse.pi-hole.net/c/feature-requests/8

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
