### ISSUE TITLE
Show more than one group in the group membership popups.

### ISSUE THREAD

**Issue by rossc719g** [pi-hole/pi-hole#3513]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

When viewing a client, blacklist, or domain, The group membership widget will either display the name of 1 group, or it will tell you the number of groups selected.  It would be very helpful if it would actually give you the names of the groups when there are more than one.

E.g., instead of "3 selected" It would be preferable to see "(3) Group1, Group2, Group3".
Or, if the list really is too long, then truncate with an ellipsis "(6) Group1, Group2, Group3, Group4, Gro..."

**Actual behaviour:**

"3 selected"

**Steps to reproduce:**

Just go to the domain management page, or the list management page, or the client management page, and look at anything that is a member of more than 1 group.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/8ov8o1pupl

**Troubleshooting undertaken, and/or other relevant information:**

You can currently get the information, but it requires you to one at a time, click on each group you wish to see.
The information is there, it's just hidden by default.

**Comment by yubiuser** [comment]
Please open feature requests at
https://discourse.pi-hole.net/c/feature-requests/8

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
