### ISSUE TITLE
dnsmaq does not respect listen-address directive

### ISSUE THREAD

**Issue by mparienti** [pi-hole/pi-hole#3514]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

When I configure the dnsmaq to listen only an IP address, dnsmaq should listen only on the configured address.

**Actual behaviour:**

Dnsmaq is listenning on `0.0.0.0:53`

**Steps to reproduce:**

1. Configure 2 ip addresses on `eth0`
2. add `interface=eth0` and `listen-address=192.168.4.128` in `/etc/dnsmasq.d/01-pihole.conf`
3. restart pihole.

Pihole is still listening on `0.0.0.0:53`

I also try the `bind-interfaces` directive, but it didn't work either.

**Other relevant information**

I need this configuration because on the other public IP there will another dns server, which need to be accessible remotely (so localhost is not an option). This configuration worked well with previous pihole 4 version.

**Comment by dschaper** [comment]
Don't modify `01-pihole.conf`, there's a reason why that file has the really big warning at the top.

**Comment by mparienti** [comment]
Hi,

Tx, but the big warning is about the change that will be lost on the next pi-hole update. I'm aware of that. It does not warn about some directives that will be ignored.

My plan was to move my changes in another file, or to re-introduce them after each update. I will find a way, that's not the problem here.

Right now Pihole V5 is not running yet, because of the issue I describe.

**Comment by dschaper** [comment]
Does putting the changes in a file like the header instructs work?

`40-interface.conf`
```plain
listen-address=192.168.4.128
bind-interfaces
```

The `interface` line should automatically be in `01-pihole.conf` based on your existing configuration. That file will change if any changes are made via the admin interface, not just on update.

**Comment by dschaper** [comment]
>  It does not warn about some directives that will be ignored.

No valid directives are ignored.

**Comment by mparienti** [comment]
I managed to make the things working the way I wanted:
1. `interface` directive should be completely removed (from `01-pihole.conf` file, so I will have to find a way to keep this change permanently).
2. both directives `listen-address=192.168.4.128` and `bind-interfaces` are necessary in order to make dnsmaq listen to a single ip address.

I guess the problem comes from dnsmaq and not from pihole.

Issue can be closed.

**Comment by dschaper** [comment]
You can use the different options from `Interface listening behavior` to modify the existence of the `interface` config line.
![Screenshot_2020-06-25 Pi-hole Admin Console](https://user-images.githubusercontent.com/2782850/85794664-dbd59980-b6eb-11ea-9997-12c3a0f6d903.png)

**Comment by DL6ER** [comment]
@mparienti Please check if any of the three option on the dashboard works for you (as suggested by @dschaper). The last one might be what you are looking for.

**Comment by mparienti** [comment]
Yes indeed, by listening on all interface, the `interface` directive is removed from `01-pihole.conf` file.

Thanks again
