### ISSUE TITLE
is this possible to install pi-hole in to MacOS?

### ISSUE THREAD

**Issue by zeroDevOne** [pi-hole/pi-hole#3515]
Hi, someone give me your app link. So i would like to know is there a way to install this application to MacOS ? is there any binary or port like brew or mac ports ???

**Comment by PromoFaux** [comment]
Https://docs.pi-hole.net

It's a server application. I guess you could run it on a Mac with docker, too.

**Comment by zeroDevOne** [comment]
> [Https://docs.pi-hole.net](Https://docs.pi-hole.net)
> 
> It's a server application. I guess you could run it on a Mac with docker, too.


server app, did mean i can filter whole network ?? i have server resources for it. so can run it on server like ubuntu

**Comment by PromoFaux** [comment]
Yep, that's the idea, it's an adblocker for your entire network.

Here is an article someone wrote explaining things a bit:

https://medium.com/@atippy83/pi-hole-dns-for-dummies-5763b65ee527#:~:text=A%20Pi%2DHole%20is%20a,any%20client%2Dside%20software.%E2%80%9D

I'll close this out as it's not really a bug report or anything.

one more link for you:

https://discourse.pi-hole.net <-- Our community support forums
