### ISSUE TITLE
Dashboard broken after Freh Installation on Debian Buster

### ISSUE THREAD

**Issue by Gill-Bates** [pi-hole/pi-hole#3516]
When I perform a fresh installation of Pihole on a clean Debian Buster system, the Dashboard is broken:

![grafik](https://user-images.githubusercontent.com/25774289/85961737-c642c700-b9ac-11ea-9fb4-b529c4b94d00.png)

It seems to me, the underlaying Database is not working correctly:

![grafik](https://user-images.githubusercontent.com/25774289/85961859-85977d80-b9ad-11ea-9417-467b6faa8917.png)

`pihole -v
  Pi-hole version is v5.0 (Latest: v5.0)
  AdminLTE version is v5.0 (Latest: v5.0)
  FTL version is v5.0 (Latest: v5.0)
`

`cat /etc/os-release`
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
`
Debug-Token: https://tricorder.pi-hole.net/nwusfoiq6r

**Comment by qu1ck** [comment]
I had the same issue, found following in nginx error log:
```
PHP message: PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /var/www/html/admin/scripts/pi-hole/php/database.php:42
Stack trace:
#0 /var/www/html/admin/scripts/pi-hole/php/database.php(65): SQLite3_connect_try('/etc/pihole/pih...', 'SQLITE3_OPEN_RE...', true)
#1 /var/www/html/admin/api_db.php(56): SQLite3_connect('/etc/pihole/pih...')
#2 {main}
  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 42" while reading response header from upstream
```

Which led me to `sudo apt install php7.3-sqlite3` which solved the issue.

**Comment by jfb-pihole** [comment]
You are running Apache, which is not a supported server. Visit the Community Help section of our discourse for user solutions.

**Comment by Gill-Bates** [comment]
Thank you! Solved it!

`sudo apt install php7.3-sqlite3`

Then Repair the Config:

`pihole -r`

Ticket will be closed. Hope it will help others!
