### ISSUE TITLE
Terminology: Blacklist/Whitelist

### ISSUE THREAD

**Issue by LIyoai** [pi-hole/pi-hole#3518]
Please consider to change terminolgy of blacklist/whitelist.

Suggested alternatives:
Blocklist-allowlist
Block-permit

https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.2

**Comment by yubiuser** [comment]
There is already an open issue about the topic https://github.com/pi-hole/AdminLTE/issues/1448
And a feature request at
https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657

**Comment by LIyoai** [comment]
oh, sorry.
