### ISSUE TITLE
Query Log - blocked entries

### ISSUE THREAD

**Issue by LIyoai** [pi-hole/pi-hole#3519]
Please add an option to only see blocked entries.

**Comment by yubiuser** [comment]
Implemented already.

![Bildschirmfoto zu 2020-06-29 09-46-34](https://user-images.githubusercontent.com/26622301/85987112-805a2300-b9ed-11ea-9dcc-a71d11db6dcc.png)


Feature requests should go to:
https://discourse.pi-hole.net/c/feature-requests/8

**Comment by LIyoai** [comment]
Sorry, didn't know about discourse, will use it in the future.
Wouldn't it be more intuitive to have this setting in the query log? Then you could also change it directly there if needed and don't need to switch to the settings first.

**Comment by yubiuser** [comment]
>Wouldn't it be more intuitive to have this setting in the query log? Then you could also change it directly there if needed and don't need to switch to the settings first.

I'm not exactly sure, but there might be a FR for this already. If you can not find one, open one on this.
