### ISSUE TITLE
Query Log - Reload

### ISSUE THREAD

**Issue by LIyoai** [pi-hole/pi-hole#3520]
Please add an option to reload the log without loosing filters.
Maybe also implement a live log, which refreshs automatically.

**Comment by yubiuser** [comment]
Both requests are feature requests and should go to discourse.

For the second one there is already a FR:
https://discourse.pi-hole.net/t/add-refresh-and-or-live-option-to-query-log/20262

**Comment by LIyoai** [comment]
Ok. Thank you.
