### ISSUE TITLE
Unable to update pi-hole FTL

### ISSUE THREAD

**Issue by th4fl4sh4** [pi-hole/pi-hole#3521]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**
```plain
 [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php5-common
  [✓] Checking for php5-cgi
  [✓] Checking for php5-sqlite
  [i] Checking for php5-xml (will be installed)
  [i] Checking for php-intl (will be installed)
  [i] Processing apt-get install(s) for: php5-xml php-intl, please wait...
--------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5-xml
E: Unable to locate package php-intl

  Unable to complete update, please contact Pi-hole Support
```
**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jfb-pihole** [comment]
Are you running Jessie?  If so, it is unsupported by Raspbian and Pi-hole. There are workarounds to install the required dependencies.

**Comment by Jemme** [comment]
Experiencing the same/similar issue.  Cannot update FTL to v5.0

`  Error: Unable to update package cache. Please try "apt-get update"
  Unable to complete update, please contact Pi-hole Support`

Core and webinterface updated just fine.

**Comment by dschaper** [comment]
Did you do what it asked you to do?

**Comment by jfb-pihole** [comment]
Run sudo apt update and see if the update completes.  If it throws an error, it will typically give you a command to run to resolve the error.

**Comment by Jemme** [comment]
Thanks for the help.   First running apt update and upgrading the listed packages allowed me to update FTL as well.
