### ISSUE TITLE
Corrupt bash files

### ISSUE THREAD

**Issue by kamkudla** [pi-hole/pi-hole#3522]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`10`

---

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

```
pihole -d
/opt/pihole/piholeDebug.sh: line 613: syntax error near unexpected token `fi'
/opt/pihole/piholeDebug.sh: line 613: `    fi'
```

**Troubleshooting undertaken, and/or other relevant information:**

`I have pulled the files locally`

I initially noticed that running `pihole -up` resulted in 

> /opt/pihole/update.sh: line 208: syntax error near unexpected token `}'

Pulling the file update.sh I am noticing the file is corrupted starting at line 60 and onwards sporadically - uploaded [update.sh] as gist (https://gist.github.com/kamkudla/ba9ae221476968204801b60c81b36f75#file-update-sh-L60). 

Additionally, running `pihole -d` also produces 

> /opt/pihole/piholeDebug.sh: line 613: syntax error near unexpected token `fi'
> /opt/pihole/piholeDebug.sh: line 613: `    fi'

piholeDebug.sh is also corrupted - uploaded [piholeDebug.sh](https://gist.github.com/kamkudla/ba9ae221476968204801b60c81b36f75#file-piholedebug-sh) as gist

These are the only two files I know thus far that seem to be corrupted.

**Comment by dschaper** [comment]
Any corruption would be on your local filesystem.

**Comment by kamkudla** [comment]
> Any corruption would be on your local filesystem.

Is this common? Could it be the frequent SD card read/writes?

**Comment by dschaper** [comment]
Hard to say. I can think of maybe 3 times in the last 4 years that I've seen it. If this truly is a Raspberry Pi device using an SDCard then make sure you're using a power supply and cable that is designed for a small board computer. Power issues will cause all kinds of random failures.

**Comment by kamkudla** [comment]
It's a Raspberry Pi 2 Model B v1.1 and I'm supplying 5V at 1.5A using a USB adapter from Sony. The system totally just died now after power cycling after detaching the power supply - will not boot up. Crashed a few weeks ago as well. It is likely that this is a problem with my 8GB no name SD card.

**Comment by dschaper** [comment]
Cell phone power supplies will cause what you are seeing.
