### ISSUE TITLE
PI-Hole cannot operate on an IPv6-only system or in an IPv6-only environment

### ISSUE THREAD

**Issue by owendelong** [pi-hole/pi-hole#3526]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Install, configure, and use Pi-Hole without needing an IPv4 address.

**Actual behaviour:**

The dashboard and several other features are (at least according to the documentation) IPv4-only.
One of the blocking modes depends on referring the user to an IPv4 address (likely a side-effect of the previous sentence).

**Steps to reproduce:**

Read the Pi-Hole documentation.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not applicable in this case.

**Troubleshooting undertaken, and/or other relevant information:**

Determined that Pi-Hole is unsuitable for my application because I need a tool which can run in an IPv6-only environment with IPv4 AAS at the distant edge.

**Comment by dschaper** [comment]
So you didn't actually try it?

**Comment by dschaper** [comment]
NXDOMAIN doesn't care IPv4 or IPv6. NULL replies with 0.0.0.0 or :: depending on A or AAAA record request. 

DNS doesn't care what the protocol is, just the record type. 

But best of luck finding an application that fits your requirements.
