### ISSUE TITLE
Add option to hide sensitive information on dashboard for logged out users

### ISSUE THREAD

**Issue by Kovah** [pi-hole/pi-hole#3528]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5?

---
**Expected behaviour:**

The admin should be able to hide / disable sensitive information about his Pi-Hole from the dashboard page for users which are not logged in. Sensitive information include hardware stats (upper left corner) as well as blocking statistics in the form of charts.

**Actual behaviour:**

There is no option to hide / disable these metrics for users which are not logged in.

**Steps to reproduce:**

Install latest version of Pi-Hole and check the http://{ip}/admin page.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not relevant here

**Troubleshooting undertaken, and/or other relevant information:**

Not relevant here

**Comment by yubiuser** [comment]
This is a feature request which should go to discourse: https://discourse.pi-hole.net/c/feature-requests/8

There is already one that requests that covers what you ask for:

https://discourse.pi-hole.net/t/disable-dashboard-if-not-logged-in/10719

**Comment by Kovah** [comment]
I wasn't aware of this forum. Maybe this could be added to this issue template.

**Comment by PromoFaux** [comment]
No need to add what is already there.. ;)

https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md

![image](https://user-images.githubusercontent.com/1998970/86451315-a431a780-bd12-11ea-90b4-a2a53ea42c89.png)

**Comment by dschaper** [comment]
Need to update the templates to the new(ish) GitHub style so clicking on "New Issue" sends Feature Requests over. Nobody reads the current ones.
