### ISSUE TITLE
Cant access admin page, but pihole is running fine. Lighttpd seems to be the issue

### ISSUE THREAD

**Issue by nakulbende** [pi-hole/pi-hole#3529]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Admin page is served on opening `192.168.1.115/admin.php` (which is IP of the RPi4 running pihole)
**Actual behaviour:**

Admin page is not opening

**Steps to reproduce:**

Just simply trying to access the admin page from a browser. Pihole is running (checked using `pihole status`) but I cant access the webpage. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`s91r90a0o8`

**Troubleshooting undertaken, and/or other relevant information:**

Tried restarting the lighttpd service using sudo systemctl restart lighttpd but I got the following error:
```
[....] Starting lighttpd (via systemctl): lighttpd.serviceJob for lighttpd.service failed because the control process exited with error code.
See "systemctl status lighttpd.service" and "journalctl -xe" for details.
failed!
```
The output of `systemctl status lighttpd.service` is:
```
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-03 15:28:32 EDT; 2min 51s ago
  Process: 1776 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)

Jul 03 15:28:32 retropie systemd[1]: lighttpd.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 15:28:32 retropie systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Jul 03 15:28:32 retropie systemd[1]: Stopped Lighttpd Daemon.
Jul 03 15:28:32 retropie systemd[1]: lighttpd.service: Start request repeated too quickly.
Jul 03 15:28:32 retropie systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Jul 03 15:28:32 retropie systemd[1]: Failed to start Lighttpd Daemon.
```
Also, i tried uninstalling lighttpd and running the pihole installation script (and choosing upgrade) in hopes that it will fix itself, but the installation log has 

```
Setting up lighttpd (1.4.53-4) ...
Job for lighttpd.service failed because the control process exited with error code.
See "systemctl status lighttpd.service" and "journalctl -xe" for details.
invoke-rc.d: initscript lighttpd, action "start" failed.
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-07-03 15:44:48 EDT; 18ms ago
  Process: 2975 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)
Failed to start Lighttpd. Maybe another webserver is already listening on port 80?
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
--------------------------------------------------------------------------------
  [✓] Enabling lighttpd service to start on reboot...

```
Thanks in advance for help - and please forgive me if I made any mistakes in reporting.

**Comment by dschaper** [comment]
Run `sudo /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf` and see what the configuration error is.

**Comment by yubiuser** [comment]
>Maybe another webserver is already listening on port 80?

Do you have any other Webserver installed, like apache, nginx?

**Comment by dschaper** [comment]
It's not a port conflict, it's a bad configuration file. 

` Process: 2975 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)`

**Comment by dschaper** [comment]
And check your ad lists, this isn't an ad list. Looks like it should be a blacklist domain:

```plain
   46          1  0             online-metrix.net                                                                                     2020-05-30 21:52:32  2020-05-30 21:52:32  Port scanner
```

**Comment by nakulbende** [comment]
Hey all, again thanks! 

I do not have apache or nginx. The output of `sudo lsof -i -P -n` shows only lighttpd listening ot 80: 
```
lighttpd   770 www-data    4u  IPv4  18099      0t0  TCP *:80 (LISTEN)
lighttpd   770 www-data    5u  IPv6  18100      0t0  TCP *:80 (LISTEN)
```

I ran `sudo /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf`, but nothing happened? Sorry if I am missing anything. Here is my config file: 

```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Lighttpd config for Pi-hole
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################

server.modules = (
	"mod_access",
	"mod_accesslog",
	"mod_auth",
	"mod_expire",
	"mod_compress",
	"mod_redirect",
	"mod_setenv",
	"mod_rewrite"
)

server.document-root        = "/var/www/html"
server.error-handler-404    = "/pihole/index.php"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename          = "/var/log/lighttpd/access.log"
accesslog.format            = "%{%s}t|%V|%r|%s|%b"

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc", ".md", ".yml", ".ini" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

mimetype.assign   = ( ".png"  => "image/png",
                      ".jpg"  => "image/jpeg",
                      ".jpeg" => "image/jpeg",
                      ".html" => "text/html",
                      ".css" => "text/css; charset=utf-8",
                      ".js" => "application/javascript",
                      ".json" => "application/json",
                      ".txt"  => "text/plain",
                      ".svg"  => "image/svg+xml" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port

# Prevent Lighttpd from enabling Let's Encrypt SSL for every blocked domain
#include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
include_shell "find /etc/lighttpd/conf-enabled -name '*.conf' -a ! -name 'letsencrypt.conf' -printf 'include \"%p\"\n' 2>/dev/null"

# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
    # Create a response header for debugging using curl -I
    setenv.add-response-header = (
        "X-Pi-hole" => "The Pi-hole Web interface is working!",
        "X-Frame-Options" => "DENY"
    )

    $HTTP["url"] =~ ".ttf$" {
        # Allow Block Page access to local fonts
        setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
    }
}

# Block . files from being served, such as .git, .github, .gitignore
$HTTP["url"] =~ "^/admin/\.(.*)" {
     url.access-deny = ("")
}

# Add user chosen options held in external file
# This uses include_shell instead of an include wildcard for compatibility
include_shell "cat external.conf 2>/dev/null"

```

**Comment by nakulbende** [comment]
Oh wait, `sudo /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf` maybe fixed ligttpd? It now is running fine:
```
pi@retropie:~ $ systemctl status lighttpd.service
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-07-03 16:30:17 EDT; 18s ago
  Process: 5109 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 5116 (lighttpd)
    Tasks: 1 (limit: 4915)
   Memory: 1.5M
   CGroup: /system.slice/lighttpd.service
           └─5116 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf

Jul 03 16:30:17 retropie systemd[1]: Starting Lighttpd Daemon...
Jul 03 16:30:17 retropie systemd[1]: Started Lighttpd Daemon.
```

My config file before the command @dschaper suggested was https://pastebin.com/7wG1UgLv. Perhaps white space errors?

Unfortunately, still no webpage:
![image](https://user-images.githubusercontent.com/8712050/86496344-05756d00-bd4b-11ea-8208-e565efe722a3.png)

**Comment by dschaper** [comment]
Run a new debug and paste the token.

**Comment by dschaper** [comment]
> Perhaps white space errors?

No way for there to be white space errors unless you have manually edited the file against the instructions.

Also check for any `external.conf` files in `/etc/lighttpd/`

**Comment by nakulbende** [comment]
I didn't edit the main configuration. I did put the external config as:

```
$HTTP["url"] =~ "^/admin/api.php" {
    setenv.add-environment = (
  "SERVER_NAME" => "192.168.1.115"
)
}
```

This was for an external monitoring app in my magicmirror. I tried removing
this, but that did not solve the issue.

Here is the debug:
xfodqurm3p

**Comment by dschaper** [comment]
How did you remove it? Did you remove the file?

On the Pi-hole device run `curl -I http://pi.hole/admin/` and see if there is an X-Pi-hole: header along with a 200 OK response.

**Comment by nakulbende** [comment]
I just emptied the file, like it was before I added. Sorry if that was
dumb. I did revert it.

The output to that command is

pi@retropie:~$ curl -I http://pi.hole/admin
HTTP/1.1 301 Moved Permanently
Location: http://pi.hole/admin/
Date: Sat, 04 Jul 2020 02:48:33 GMT
Server: lighttpd/1.4.53

**Comment by dschaper** [comment]
You'll need to use the exact command I provided. `curl -I http://pi.hole/admin/`

**Comment by nakulbende** [comment]
Oops, sorry about that

pi@retropie:~$ curl -I http://pi.hole/admin/
HTTP/1.1 403 Forbidden
Content-Type: text/html
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
Content-Length: 341
Date: Sat, 04 Jul 2020 02:53:01 GMT
Server: lighttpd/1.4.53

**Comment by dschaper** [comment]
What is the output from `ls -lachR /etc/lighttpd/`?

**Comment by nakulbende** [comment]
Thanks so much for helping me with this!


pi@retropie:~$ ls -lachR /etc/lighttpd/
/etc/lighttpd/:
total 28K
drwxr-xr-x   4 root root 4.0K Jul  3 20:11 .
drwxr-xr-x 127 root root  12K Jul  3 20:11 ..
drwxr-xr-x   2 root root 4.0K Jul  3 20:10 conf-available
drwxr-xr-x   2 root root 4.0K Jul  3 20:10 conf-enabled
-rw-r--r--   1 root root    0 Jul  3 20:11 external.conf
-rw-r--r--   1 root root 3.5K Jul  3 20:11 lighttpd.conf

/etc/lighttpd/conf-available:
total 8.0K
drwxr-xr-x 2 root root 4.0K Jul  3 20:10 .
drwxr-xr-x 4 root root 4.0K Jul  3 20:11 ..

/etc/lighttpd/conf-enabled:
total 8.0K
drwxr-xr-x 2 root root 4.0K Jul  3 20:10 .
drwxr-xr-x 4 root root 4.0K Jul  3 20:11 ..
pi@retropie:~$


My external.conf is empty right now, btw.


------------Sent from phone----------

Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com

**Comment by dschaper** [comment]
That's missing a ton of standard configuration files from the `lighttpd` package. Does retropi have it's own web server setup?

What is 
`ls -lach /var/www/html/admin` 

and

```plain
cd /var/www/html/admin
sudo git status
```

**Comment by nakulbende** [comment]
pi@retropie:~$ ls -lach /var/www/html/admin
total 476K
drwxr-xr-x 7 root     root     4.0K Jul  3 20:11 .
drwxrwxr-x 4 www-data www-data 4.0K Jul  3 20:11 ..
-rw-r--r-- 1 root     root      12K Jul  3 20:11 api_db.php
-rw-r--r-- 1 root     root     9.3K Jul  3 20:11 api_FTL.php
-rw-r--r-- 1 root     root     3.6K Jul  3 20:11 api.php
-rw-r--r-- 1 root     root     2.3K Jul  3 20:11 auditlog.php
-rw-r--r-- 1 root     root     2.3K Jul  3 20:11 CONTRIBUTING.md
-rw-r--r-- 1 root     root     2.2K Jul  3 20:11 db_graph.php
-rw-r--r-- 1 root     root     4.2K Jul  3 20:11 db_lists.php
-rw-r--r-- 1 root     root     6.4K Jul  3 20:11 db_queries.php
-rw-r--r-- 1 root     root      939 Jul  3 20:11 debug.php
-rw-r--r-- 1 root     root     3.9K Jul  3 20:11 dns_records.php
drwxr-xr-x 8 root     root     4.0K Jul  3 23:00 .git
drwxr-xr-x 3 root     root     4.0K Jul  3 20:11 .github
-rw-r--r-- 1 root     root      153 Jul  3 20:11 .gitignore
-rw-r--r-- 1 root     root     1.3K Jul  3 20:11 gravity.php
-rw-r--r-- 1 root     root     3.0K Jul  3 20:11 groups-adlists.php
-rw-r--r-- 1 root     root     3.0K Jul  3 20:11 groups-clients.php
-rw-r--r-- 1 root     root     6.8K Jul  3 20:11 groups-domains.php
-rw-r--r-- 1 root     root     2.7K Jul  3 20:11 groups.php
-rw-r--r-- 1 root     root     9.2K Jul  3 20:11 help.php
drwxr-xr-x 3 root     root     4.0K Jul  3 20:11 img
-rw-r--r-- 1 root     root     8.9K Jul  3 20:11 index.php
-rw-r--r-- 1 root     root      14K Jul  3 20:11 LICENSE
-rw-r--r-- 1 root     root     2.9K Jul  3 20:11 network.php
-rw-r--r-- 1 root     root     1.5K Jul  3 20:11 package.json
-rw-r--r-- 1 root     root     178K Jul  3 20:11 package-lock.json
-rw-r--r-- 1 root     root     5.4K Jul  3 20:11 queries.php
-rw-r--r-- 1 root     root     1.1K Jul  3 20:11 queryads.php
-rw-r--r-- 1 root     root     9.0K Jul  3 20:11 README.md
drwxr-xr-x 4 root     root     4.0K Jul  3 20:11 scripts
-rw-r--r-- 1 root     root      90K Jul  3 20:11 settings.php
drwxr-xr-x 3 root     root     4.0K Jul  3 20:11 style
-rw-r--r-- 1 root     root      939 Jul  3 20:11 taillog-FTL.php
-rw-r--r-- 1 root     root      931 Jul  3 20:11 taillog.php
-rw-r--r-- 1 root     root       45 Jul  3 20:11 .user.php.ini
pi@retropie:~$

And got status says it's up to date with origin/ master.

Not sure about the retropie, I can tell you it was working till 2 days ago,
and I have had this setup for a while. I did add the external. conf (but
reverted now) and used apt-get upgrade recently.

Also, when I just use apt-get install lighttpd, those are the files I get.

**Comment by dschaper** [comment]
What did you do when you uninstalled `lighttdp`?

**Comment by dschaper** [comment]
These are all the files that should have been installed:

https://packages.debian.org/buster/amd64/lighttpd/filelist

**Comment by nakulbende** [comment]
I tried deleting the folder and sudo apt-get install lighttpd. Should I
have not?

Why is that command not installing everything.

------------Sent from phone----------

Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com

**Comment by dschaper** [comment]
What folder did you delete? If you didn't actually uninstall via `apt` then running `apt-get install lighttpd` is a no-op and won't do anything.

**Comment by nakulbende** [comment]
Hello Dan,

I deleted /etc/lighttpd, and used apt-install. I think I deleted it, rather
than using remove or uninstall. But reinstalling is not bringing the files
back. What can I do? Is there a GitHub repo for lighttpd which will give me
all the files?

------------Sent from phone----------

Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com

**Comment by dschaper** [comment]
You can try `sudo apt remove lighttpd` to get `apt` to understand the package was removed. After that you can re-run the Pi-hole installation process, `curl | bash` and it should put things in the proper place. I don't think you'll need to purge the package but that's another option. `sudo apt remove --purge lighttpd`.

**Comment by nakulbende** [comment]
So - I did that a couple of times. This time, here is what I followed:
1. `sudo apt-get purge lighttpd`. This left the /etc/lighttpd folder with only external.conf file - which i deleted
2. Used `curl | bash` to start pi-hole installation, chose upgrade
3. This installed only lighttpd, with only the files that we before - none of the additional files you pointed out. But, I looked at the install log, and it suggested a few items. 
```
Suggested packages:
  rrdtool apache2-utils lighttpd-doc
Recommended packages:
  lighttpd-modules-ldap lighttpd-modules-mysql
The following NEW packages will be installed:
  lighttpd
```

4. I decided to install them manually: `sudo apt-get install rrdtool apache2-utils lighttpd-doc lighttpd-modules-ldap lighttpd-modules-mysql`

All of this, resulted in still having the original files

![image](https://user-images.githubusercontent.com/8712050/86608463-9a10e280-bf78-11ea-9eb9-2cbcc6aec77f.png)

But the server is indeed working! 

![image](https://user-images.githubusercontent.com/8712050/86608536-aeed7600-bf78-11ea-9e19-f8ab450cb304.png)
![image](https://user-images.githubusercontent.com/8712050/86608638-cc224480-bf78-11ea-8cf1-e1e134192e92.png)

Thanks @dschaper - you taught me so much along the way :)

**Comment by nakulbende** [comment]
Seems like I have all the files actually: `ls -lachR /etc/lighttpd/` gives

```
/etc/lighttpd/:
total 32K
drwxr-xr-x   4 root root 4.0K Jul  6 10:56 .
drwxr-xr-x 127 root root  12K Jul  6 10:59 ..
drwxr-xr-x   2 root root 4.0K Jul  6 10:56 conf-available
drwxr-xr-x   2 root root 4.0K Jul  6 10:56 conf-enabled
-rw-r--r--   1 root root    0 Jul  6 10:56 external.conf
-rw-r--r--   1 root root 3.5K Jul  6 10:56 lighttpd.conf
-rw-r--r--   1 root root 2.0K Jul  6 10:56 lighttpd.conf.orig

/etc/lighttpd/conf-available:
total 108K
drwxr-xr-x 2 root root 4.0K Jul  6 10:56 .
drwxr-xr-x 4 root root 4.0K Jul  6 10:56 ..
-rw-r--r-- 1 root root  839 Jul  6 10:56 05-auth.conf
-rw-r--r-- 1 root root   91 Jul  6 10:56 10-accesslog.conf
-rw-r--r-- 1 root root  396 Jul  6 10:56 10-cgi.conf
-rw-r--r-- 1 root root   63 Jul  6 10:56 10-dir-listing.conf
-rw-r--r-- 1 root root   36 Jul  6 10:56 10-evasive.conf
-rw-r--r-- 1 root root  128 Jul  6 10:56 10-evhost.conf
-rw-r--r-- 1 root root  104 Jul  6 10:56 10-expire.conf
-rw-r--r-- 1 root root  177 Jul  6 10:56 10-fastcgi.conf
-rw-r--r-- 1 root root   42 Jul  6 10:56 10-flv-streaming.conf
-rw-r--r-- 1 root root   82 Jul  6 10:56 10-no-www.conf
-rw-r--r-- 1 root root  849 Jul  6 10:56 10-proxy.conf
-rw-r--r-- 1 root root  176 Jul  6 10:56 10-rewrite.conf
-rw-r--r-- 1 root root  253 Jul  6 10:56 10-rrdtool.conf
-rw-r--r-- 1 root root  398 Jul  6 10:56 10-simple-vhost.conf
-rw-r--r-- 1 root root  449 Jul  6 10:56 10-sockproxy.conf
-rw-r--r-- 1 root root   99 Jul  6 10:56 10-ssi.conf
-rw-r--r-- 1 root root  203 Jul  6 10:56 10-ssl.conf
-rw-r--r-- 1 root root  460 Jul  6 10:56 10-status.conf
-rw-r--r-- 1 root root  450 Jul  6 10:56 10-userdir.conf
-rw-r--r-- 1 root root   38 Jul  6 10:56 10-usertrack.conf
-rw-r--r-- 1 root root  168 Jul  6 10:56 11-extforward.conf
-rw-r--r-- 1 root root  575 Jul  6 10:56 15-fastcgi-php.conf
-rw-r--r-- 1 root root  508 Jul  6 10:56 90-debian-doc.conf
-rw-r--r-- 1 root root  162 Jul  6 10:56 99-unconfigured.conf
-rw-r--r-- 1 root root  843 Jul  6 10:56 README

/etc/lighttpd/conf-enabled:
total 8.0K
drwxr-xr-x 2 root root 4.0K Jul  6 10:56 .
drwxr-xr-x 4 root root 4.0K Jul  6 10:56 ..
lrwxrwxrwx 1 root root   33 Jul  6 10:56 10-fastcgi.conf -> ../conf-available/10-fastcgi.conf
lrwxrwxrwx 1 root root   37 Jul  6 10:56 15-fastcgi-php.conf -> ../conf-available/15-fastcgi-php.conf
lrwxrwxrwx 1 root root   38 Jul  6 10:56 99-unconfigured.conf -> ../conf-available/99-unconfigured.conf
```
