### ISSUE TITLE
Unable to install pihole on ubuntu 20.04 

### ISSUE THREAD

**Issue by dc232** [pi-hole/pi-hole#3535]
**How familiar are you with the the source code relevant to this issue?:**
5

seems to be in 

```installFTL()```

**Expected behavior:**
FTL installs and pi-hole is installed as well as up and running

**Actual behaviour:**
```   [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
sha1sum: pihole-FTL-linux-x86_64.sha1: No such file or directory
  [✗] Downloading and Installing FTL
  Error: Download of https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-linux-x86_64 failed (checksum error)
  [✗] FTL Engine not installed
```

**Steps to reproduce:**
install ubuntu 20.04 
run
```
sudo apt update && sudo apt upgrade -y && sudo curl -sSL https://install.pi-hole.net | bash 
``` 

**Troubleshooting undertaken, and/or other relevant information:**
```
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
```
```
wget -O basic-install.sh https://install.pi-hole.net
sudo bash basic-install.sh
```

```
curl -sI https://github.com/pi-hole/FTL/releases/latest | grep "location"
returns: location: https://github.com/pi-hole/FTL/releases/tag/v5.0
```

The above curl seems to work, however in the basic-install.sh however I'm not sure what the binary=${1} is set to do any more analysis
any help to get pihole installed is greatly appreciated

**Comment by dschaper** [comment]
It looks like you have an issue with `curl` itself. I did a quick search for `curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number` and it seems that a proxy that is incorrectly configured can lead to that error.

**Comment by dc232** [comment]
hi @dschaper  I think you are correct, seems like my squid proxy was breaking ssl, not sure why this is at the mo, but as soon as I turned it off pi-hole seems to have install FTL no problem. Thank you so much

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/https-github-com-pi-hole-ftl-releases-latest-download-pihole-ftl-linux-x86-64-not-found/35751/7
