### ISSUE TITLE
Unbound error connection timed out no servers could be reached

### ISSUE THREAD

**Issue by EshanTahir** [pi-hole/pi-hole#3536]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`
       /
- [\/] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
       /
- [\/] The issue I am reporting can be *replicated*.
       /
- [\/] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

I expect to use unbound as a local recursive dns server

**Actual behaviour:**
;; connection timed out; no servers could be reached

**Steps to reproduce:**

I go through the estup here: https://docs.pi-hole.net/guides/unbound/
I made sure to use sudo for every line of code. I have a root.hint file, and a pi-hole.conf file, it also says successful unbound install. It starts unbound just fine, but when i do 
dig pi-hole.net @127.0.0.1 -p 5335:
; <<>> DiG 9.10.3-P4-Raspbian <<>> pi-hole.net @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached

dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5335: 
; <<>> DiG 9.10.3-P4-Raspbian <<>> sigfail.verteiltesysteme.net @127.0.0.1 -p 5335
;; global options: +cmd
;; connection timed out; no servers could be reached

dig sigok.verteiltesysteme.net @127.0.0.1 -p 5335:
; <<>> DiG 9.10.3-P4-Raspbian <<>> sigok.verteiltesysteme.net @127.0.0.1 -p 5335
;; global options: +cmd
;; connection timed out; no servers could be reached

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
https://tricorder.pi-hole.net/7ksy3fvyx9

**Troubleshooting undertaken, and/or other relevant information:**

I tried enabling dnssec, and i tried googling It, i found others with same problem but it didn't help. I also have google wifi, and no ipv6. I have 4.5 million adlist domains.

**Comment by dschaper** [comment]
This is a configuration issue and not a bug in Pi-hole.

Visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by EshanTahir** [comment]
Where do i ask to fix this

**Comment by dschaper** [comment]
At the URL I linked in my post.
