### ISSUE TITLE
Clients cannot reach PiHole

### ISSUE THREAD

**Issue by JDiersche** [pi-hole/pi-hole#3539]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Clients that are given the PiHole IP as a DNS server are able to use the internet with ad-blocking.

**Actual behaviour:**

Clients that are given the PiHole IP as a DNS server are unable to resolve any dns query, and none of the attempted sites appear in the PiHole query log.

**Steps to reproduce:**
In the router LAN configuration, change client DNS server to the IP of the PiHole. Client then loses ability to access internet upon connection to the network.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/4qsclkv9n5

**Troubleshooting undertaken, and/or other relevant information:**

I have browsed the github issues and the discourse forums attempting to find someone else with a similar issue. The debug log doesn't show anything immediately wrong to me. The PiHole itself is able to connect to the internet via ethernet, and I can see the queries that it makes on the admin console. The clients appear in the network tab of the admin console, but it says they do not use PiHole. On the admin console DNS tab, the system is set to listen on all interfaces and permit all origins. DNSSEC is turned off, and conditional forwarding is turned on. The Upstream DNS is set to Google on IPV4. I am using an Asus router with merlin installed. The WAN DNS servers are Google's 8.8.8.8, 8.8.4.4, and the LAN DNS is set as 10.10.10.10 (PiHole IP). 

I apologize if the issue is repeated, I really have done my best to solve this myself and any help on this is very welcome.

**Comment by derritter88** [comment]
Have you tried to do a direct lookup on your Pi-hole -> `nslookup google.com <ip address of pi-hole>`

Have you tried to do a lookup directly at a foreign DNS server -> `nslookup google.com 8.8.8.8`

**Comment by JDiersche** [comment]
nslookup google.com 10.10.10.10
;; connection timed out; no servers could be reached

nslookup google.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.193.142
Name:   google.com
Address: 2607:f8b0:4000:803::200e

**Comment by derritter88** [comment]
Okay on you Pi-hole device can you also run a lookup?
If it's a Linux setup use `dig google.com @127.0.0.1`

If that works than please verify if there is a firewall which is blocking incoming DNS packages (uses port 53 UDP).
If that does not work please verify that Pi hole is running properly - e.g. check on your Pi hole device if something using port 53.
I know that Ubuntu for example is using systemd-resolve as a local DNS server.

**Comment by dschaper** [comment]
It looks like a firewall or networking issue.

The tests show that a query from Pi-hole to itself on the loopback works, but that same check on the IP fails. 

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] oss-crules.marketscore.com is 10.10.10.10 via localhost (127.0.0.1)
[✗] Failed to resolve oss-crules.marketscore.com via Pi-hole (10.10.10.10)
[✓] doubleclick.com is 216.58.194.110 via a remote, public DNS server (8.8.8.8)
```

The logs show that lookup from localhost but it does not show any activity from any other clients.

```plain
*** [ DIAGNOSING ]: Pi-hole log
-rw-r--r-- 1 pihole pihole 17561 Jul  8 23:55 /var/log/pihole.log
   -----head of pihole.log------
   Jul  8 23:19:34 dnsmasq[294]: read /etc/hosts - 2 addresses
   Jul  8 23:19:34 dnsmasq[294]: read /etc/pivpn/hosts.wireguard - 0 addresses
   Jul  8 23:19:34 dnsmasq[294]: failed to load names from /etc/pihole/custom.list: No such file or directory
   Jul  8 23:19:34 dnsmasq[294]: read /etc/pihole/local.list - 2 addresses
   Jul  8 23:25:39 dnsmasq[294]: query[A] pi.hole from 127.0.0.1
   Jul  8 23:25:39 dnsmasq[294]: /etc/pihole/local.list pi.hole is 10.10.10.10
   Jul  8 23:25:39 dnsmasq[294]: query[AAAA] pi.hole from 127.0.0.1
   Jul  8 23:25:39 dnsmasq[294]: forwarded pi.hole to 8.8.4.4
   Jul  8 23:25:39 dnsmasq[294]: forwarded pi.hole to 8.8.8.8
   Jul  8 23:25:39 dnsmasq[294]: reply pi.hole is NODATA-IPv6
   Jul  8 23:25:52 dnsmasq[294]: query[A] pi.hole from 10.6.0.1
   Jul  8 23:25:52 dnsmasq[294]: /etc/pihole/local.list pi.hole is 10.10.10.10
   Jul  8 23:25:52 dnsmasq[294]: query[AAAA] pi.hole from 10.6.0.1
   Jul  8 23:25:52 dnsmasq[294]: cached pi.hole is NODATA-IPv6
   Jul  8 23:26:22 dnsmasq[294]: query[A] pi-hole.net from 127.0.0.1
   Jul  8 23:26:22 dnsmasq[294]: forwarded pi-hole.net to 8.8.4.4
   Jul  8 23:26:22 dnsmasq[294]: reply pi-hole.net is 192.124.249.118
   Jul  8 23:26:22 dnsmasq[294]: query[AAAA] pi-hole.net from 127.0.0.1
   Jul  8 23:26:22 dnsmasq[294]: forwarded pi-hole.net to 8.8.4.4
   Jul  8 23:26:22 dnsmasq[294]: reply pi-hole.net is NODATA-IPv6
```

The ports are set correctly:

```plain
*** [ DIAGNOSING ]: Ports in use
*:22 sshd (IPv4)
*:22 sshd (IPv6)
[80] is in use by lighttpd
[80] is in use by lighttpd
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[4711] is in use by pihole-FTL
```

**Comment by JDiersche** [comment]
The strange thing is that I have previously had a PiHole work with this same router configuration. The router firewall is completely off. The client is set to use 10.10.10.10 as the DNS. I just changed the router configuration to also have the PiHole use 10.10.10.10 as DNS but it is still not working.

dietpi@DietPi:~$ dig google.com @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53039
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             282     IN      A       172.217.1.142

;; Query time: 26 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jul 09 17:10:43 CDT 2020
;; MSG SIZE  rcvd: 55

**Comment by dschaper** [comment]
Try `dig google.com @10.10.10.10`

**Comment by dschaper** [comment]
Also `dig pi.hole @127.0.0.1`

**Comment by JDiersche** [comment]
dietpi@DietPi:~$ dig google.com @10.10.10.10

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> google.com @10.10.10.10
;; global options: +cmd
;; connection timed out; no servers could be reached
dietpi@DietPi:~$ dig pi.hole @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> pi.hole @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47146
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.                       IN      A

;; ANSWER SECTION:
pi.hole.                2       IN      A       10.10.10.10

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jul 09 17:25:05 CDT 2020
;; MSG SIZE  rcvd: 52

**Comment by dschaper** [comment]
Pi-hole is working and responding correctly to queries. The issue then is with the network configuration or interfaces.

**Comment by JDiersche** [comment]
This is my interfaces configuration.

# Location: /etc/network/interfaces
# Please modify network settings via: dietpi-config
# Or create your own drop-ins in: /etc/network/interfaces.d/

# Drop-in configs
source interfaces.d/*

# Loopback
auto lo
iface lo inet loopback

# Ethernet
allow-hotplug eth0
iface eth0 inet dhcp
address 10.10.10.10
netmask 255.255.255.0
gateway 10.10.10.1
dns-nameservers 10.10.10.10

# WiFi
#allow-hotplug wlan0
#iface wlan0 inet dhcp
#address 192.168.0.100
#netmask 255.255.255.0
#gateway 192.168.0.1
#wireless-power off
#wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
#dns-nameservers 9.9.9.9 149.112.112.112

**Comment by dschaper** [comment]
You'll need to get support with DietPi. Pi-hole is working so it's something beyond our support levels.

You can try the community help at https://discourse.pi-hole.net to see if a fellow Pi-hole user has any tips.

**Comment by JDiersche** [comment]
Turns out it was a PiHole issue. On the web interface, I had the Interface Listening Behavior set to "Listen on all interfaces, permit all origins". As soon as I changed it to "Listen only on interface eth0" I was able to connect to the internet on my clients, their queries show up in the log, and adblocking is working. Unfortunately I actually need PiHole to accept other interfaces, is there a way to fix this?

This it the new debug showing that it is working https://tricorder.pi-hole.net/iq1u7y4rd0

**Comment by dschaper** [comment]
It's still not a Pi-hole issue. It's a networking issue. Your debug log only shows `eth0`, what other interfaces do you intend to use?

**Comment by JDiersche** [comment]
When the PiHole is set to "Listen on all interfaces" or "Listen on all interfaces, permit all origins", it does not listen on eth0. Is eth0 not included in those groups? I also have a PiVPN server with wireguard that I will configure once I have PiHole working as expected.

**Comment by dschaper** [comment]
Ah, you didn't mention PiVPN. They inject additional configuration files that break Pi-hole's implementation.

**Comment by dschaper** [comment]
https://github.com/pivpn/pivpn/issues/948

**Comment by JDiersche** [comment]
Ah, I see. I didn't realize that just having PiVPN installed would cause an issue. I have deleted /etc/dnsmasq.d/02-pivpn.conf and I believe everything is working as expected now. Thank you for your help.
