### ISSUE TITLE
*Suggestion* Split lookup zone

### ISSUE THREAD

**Issue by derritter88** [pi-hole/pi-hole#3540]
It would be a great benefit if there could be different DNS answer according to the subnet.

e.g.
192.168.1.0/24 -> all Facebook domains should be blocked 
192.168.2.0/24 -> Facebook should work

... and so on

**Comment by yubiuser** [comment]
This is possible since version  v5. With Group Management. You can specify clients also as subnets in CIDR notation.

**Comment by derritter88** [comment]
Great!
