### ISSUE TITLE
Gravity gets wrong adlist source for domain

### ISSUE THREAD

**Issue by mikedilger** [pi-hole/pi-hole#3546]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [?] The issue I am reporting can be *replicated* (see below).
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

A domain listed in only one adlist should be allowed after I disable that adlist and rebuild gravity.

**Actual behaviour:**

Domain continues to be blocked, and is wrongly attributed to a different adlist that the domain is not present in.

**Steps to reproduce:**

I can ship you my data if you want, but I would need instruction on how to do that.

I have two blocklists on my website: 
* https://mikedilger.com/blacklists/facebook-lesser.txt
* https://mikedilger.com/blacklists/pihole-google-lesser.txt

The second one contains "meet.google.com".  As I need to use meet.google.com to interact with a potential employer, I've disabled the second blocklist and rebuilt gravity with `pihole -g`.

Unfortunately meet.google.com is still blocked, and tools/query-lists tells me it was found in "facebook-lesser.txt" blocklist. But it certainly is not and never was in that blocklist.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`There was an error uploading your debug log.`  I just put it on https://mikedilger.com/blacklists/pihole_debug.log

**Troubleshooting undertaken, and/or other relevant information:**

This issue is with v5.0

I have removed the google adlist entirely, since that was where "meet.google.com" was listed and rebuilt gravity. It still shows up as in the facebook blacklist.

**Comment by yubiuser** [comment]
I can not reproduce the issue. If it still persist for you, why not just whitelist `meet.google.com`


```
nanopi@nanopi:~$ pihole -q meet.google.com
 Match found in https://mikedilger.com/blacklists/pihole-google-lesser.txt:
   meet.google.com 

nanopi@nanopi:~$ dig meet.google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> meet.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2739
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;meet.google.com.		IN	A

;; ANSWER SECTION:
meet.google.com.	86188	IN	CNAME	talkgadget.l.google.com.
talkgadget.l.google.com. 88	IN	A	172.217.18.174

;; Query time: 6 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mi Jul 15 23:03:32 CEST 2020
;; MSG SIZE  rcvd: 87

nanopi@nanopi:~$ pihole -q meet.google.com
 Match found in https://mikedilger.com/blacklists/pihole-google-lesser.txt:
   meet.google.com (disabled)

nanopi@nanopi:~$ pihole -g
  [...]
nanopi@nanopi:~$ dig meet.google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> meet.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63192
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;meet.google.com.		IN	A

;; ANSWER SECTION:
meet.google.com.	86092	IN	CNAME	talkgadget.l.google.com.
talkgadget.l.google.com. 30	IN	A	172.217.18.174

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mi Jul 15 23:05:08 CEST 2020
;; MSG SIZE  rcvd: 87

nanopi@nanopi:~$ pihole -q meet.google.com
  [i] No results found for meet.google.com within the block lists

```

**Comment by mikedilger** [comment]
I've worked around the bug by deleting the facebook list, rebuilding gravity, and then adding the facebook list again and rebuilding again.
