### ISSUE TITLE
Enhancement Request: Support for Bluetack lists/IP range format

### ISSUE THREAD

**Issue by kmr2319** [pi-hole/pi-hole#355]
[Bluetack lists](https://www.iblocklist.com/lists) have been a staple of some of my blocking for years now. They have a number of ranges that might be very useful to be able to block from Pi-Hole (ads, spyware, etc). The format that they are provided in is gziped and not in a hosts file format, so it's not a list that could be directly imported by adding to the "/etc/pihole/adlists.list" config file.

**Comment by dschaper** [comment]
Do they offer access without a subscription? I was trying to get a look at the formats that are provided, but I see "subscription" for the URL locations?

**Comment by kmr2319** [comment]
The "ads" list is available with out a subscription:
http://list.iblocklist.com/?list=dgxtneitpuvgqqcpfulq&fileformat=p2p&archiveformat=gz

Others are as well. But only in the "p2p" format.

Here's some code that attempts to pull them all into one big file (if that helps at all)... Some possibly better code options in the comments in that thread too:
https://gist.github.com/johntyree/3331662

Thanks!

**Comment by dschaper** [comment]
Thanks for the reply, I'll have to take a look and see if I can get the terms and conditions of the site usage, and then see what we would have to do to massage the data into a format that we can use...

**Comment by kmr2319** [comment]
I couldn't find any T&C on their site. I went looking prior to opening this. I think as long as you are pulling the data and tweaking in on a per install basis you should be OK. Many other apps do that already. Just don't include the lists themselves in the pihole code and I would guess you should be solid.

Per their [main page](https://www.iblocklist.com/):
>How does it work?
>I-Blocklist distributes lists in standard formats including P2P, DAT, and CIDR.
>Our lists can be used with software such as PeerBlock, PeerGuardian, iplist, Vuze, Transmission, uTorrent and, pfBlocker.

**Comment by DonLexos** [comment]
The list might give a challenge to parse since it lists ip ranges/blocks instead of single IPs.
```
AppNexus Inc:8.12.224.0-8.12.239.255
eNom, Incorporated, DEMAND MEDIA INC:8.15.231.0-8.15.231.255
```

Not sure if the URL changes but the link you mentioned has a random string it it, that downloads a gzip with that name that contains a file with the exact same (randomized?) name.

**Comment by PromoFaux** [comment]
Are these lists like the ones used by torrent clients?

**Comment by DonLexos** [comment]
I would not be able to answer that since I have no idea what you mean. The sample is from the file I downloaded from the link that @kmr2319 provided. There's many more:

```
eNom, Incorporated, DEMAND MEDIA INC:8.5.0.0-8.5.1.255
Telmetrics Inc:8.7.65.0-8.7.65.255
Telmetrics Inc:8.7.210.0-8.7.210.255
VideoEgg, Inc:8.8.14.0-8.8.14.255
content.pulse360.com:8.9.23.204-8.9.23.204
AppNexus Inc:8.10.72.0-8.10.75.255
ADBRITE INC:8.11.1.0-8.11.1.255
AppNexus Inc:8.12.224.0-8.12.239.255
```

**Comment by DonLexos** [comment]
Found what you meant, this was indeed the p2p format, I tried the other 2 but not sure if the DAT file can be used at all, and the CIDR simply lists the blocks like this:
```
1.36.202.60/32
4.18.162.102/32
4.36.44.3/32
4.38.98.140/32
```

**Comment by dschaper** [comment]
There was a dropdown that said Hosts format, which is what we want, but then it said Subscription for the URL, that's what was throwing me, maybe we should approach the site owner and see what he says, blocklist owners tend to be friendly from my experience...

**Comment by DonLexos** [comment]
Yeah noticed that also, however subscription is more than just becoming a member:
**I-Blocklist Subscription ($9.99 a year)**
* Unlimited list updates.
* Lists in multiple formats.
* I-Blocklist subscription lists.
* Create custom lists based on ranges, keywords, and a combination of lists.

Maybe if you could get a test subscription to make it work there is an option to support it but I doubt that one subscription would be enough for all pi-hole installations. It could always be added as an add-on list that is supported but not enabled by default. Not sure if the URL would be user specific or not, might give a headache to add it even if you are subscribed.

**Comment by PromoFaux** [comment]
I think that if there is enough demand, we can code in support for parsing the lists into a HOSTS formatted file (unless they're already available as a HOSTS file, in which case users just need to add it to their `adlists.list` sources file...)

**Comment by kmr2319** [comment]
The current "free" list is the "p2p" format which is an IP address range.

@PromoFaux
> Are these lists like the ones used by torrent clients?

Looking into this, that does seem to be the case, but I was more concerned with the "ad" and "spyware" type lists as they might be of great use to PiHole.

While $9.99/year isn't unreasonable on a per user basis, if there was some coding magic that could take the "free" list to convert it into an acceptable format for PiHole's purposes that would be beneficial for all users without any additional costs.

However, that also brings up another good question. PiHole just blocks ad servers by redirecting the hostname to the local IP of the PiHole server... SO, how would we be able to block ads by IP. Say for example we knew that Ad Provider X ran all of ads from 3 IPs but via 300 domains. Wouldn't blocking the 3 IPs be more efficient?

**Comment by fayetted** [comment]
Maybe I'm missing something here but how do you DNS Black list something when DNS isn't used?  DNS is used to convert names to IP's.  If you Blacklist an IP address you effectively do nothing because DNS doesn't lookup the IP address in order to find out what it's IP address is?

There is software out there already that can take in lists of IP addresses and add them to the active IPTables rules to block traffic to the IP address but that would have to run on your network firewall.

Is there something I'm misunderstanding here?

**Comment by DonLexos** [comment]
Very good point @fayetted , no clue!

**Comment by kmr2319** [comment]
@fayetted - See my previous comment:
> However, that also brings up another good question. PiHole just blocks ad servers by redirecting the hostname to the local IP of the PiHole server... SO, how would we be able to block ads by IP. Say for example we knew that Ad Provider X ran all of ads from 3 IPs but via 300 domains. Wouldn't blocking the 3 IPs be more efficient?


Regarding:
> There is software out there already that can take in lists of IP addresses and add them to the active IPTables rules to block traffic to the IP address but that would have to run on your network firewall.

I've used these lists for exactly that purpose in the past. It ended up being more trouble than it's worth so I stopped a long time ago.

Since PiHole is so amazingly simple and well designed, I was just looking for any additional or updated lists that might be more helpful in blocking anything that was unwanted (and possibly more trusted than the Mahakala list). So this request is really just more along the lines of looking into IF the source data which has been around for a very long time and is updated regularly is worth attempting to finagle into PiHole's current design... 

If you don't think that it's doable or worthwhile, close the request... It was just an idea/thought.

**Comment by DonLexos** [comment]
Well if you would want to block by IP only through the pi-hole the system/method would change I think, since it is not by DNS request anymore, but by Proxy(?). Love the idea of extenting the options, but right now the computer does the request by itself after it receives the pi-hole info.

A way it could work is
* adserver.com request from lanclient1 at pi-hole.
* pi-hole checks normal lists, if it is in there returns its own ip (block)
* if it is not in the list gets it from the configured DNS
* checks the IP in a different/seperate IP-only list
* if it is in there returns its own ip (block)

Not sure if dnsmasq would support that though.

**Comment by dschaper** [comment]
`dnsmasq` wouldn't support it in stock configuration that I know of. I don't think this would be possible, as the lists are IP blocks, and thus would need post-processing. Like @DonLexos we would have to enable some sort of proxy and that's not what the project is right now. Sorry, but I have to vote to say close on this issue, I don't think it's something we're going to be doing...
