### ISSUE TITLE
Doubling in fail-safe check if user doesn't select an adlist on install

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#3551]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5
---
Code Maintenance

With v5.1 
https://github.com/pi-hole/pi-hole/pull/3463 and https://github.com/pi-hole/pi-hole/pull/3388 fixed the same issue in slightly different ways. Both have been merged and v5.1 containes two ways to create an empty adlist file if users don't select any adlist on install.

Could be left at it is, but also cleaned up depending on which approch devs like.

https://github.com/pi-hole/pi-hole/blob/e4b2d295529697145e84c5100dd786bbc732dd29/automated%20install/basic-install.sh#L1292

https://github.com/pi-hole/pi-hole/blob/e4b2d295529697145e84c5100dd786bbc732dd29/automated%20install/basic-install.sh#L1298

P.S. I'll do the PR when you tell me which fix you prefer.

**Comment by dschaper** [comment]
Sorry, completely missed this.

I'd prefer to `touch` as it's pretty evident what is going on. Redirecting a noop to a file is rather arcane.

**Comment by yubiuser** [comment]
I prefer `touch` as well.

Just read your discussion and it seems undecided which style should be used (https://github.com/pi-hole/pi-hole/pull/3388#discussion_r426071036)

I'm closing this PR and revert the other one.

**Comment by dschaper** [comment]
I guess I should have fought harder to use `touch` in the first place.
