### ISSUE TITLE
Undefined index: type on v5.1.1

### ISSUE THREAD

**Issue by wienfuchs** [pi-hole/pi-hole#3552]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

`Tools/Audit log editing working as with 5.0`

**Actual behavior:**

`Tools/Audit log not working at all, failure in webserver log`

**Steps to reproduce:**

`Upgrade to 5.1.1, goto Tools/Audit log, click on "Actions/Audit" - nothing happens`

**Webserver Logfile excerpt:**

`AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: type in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 476 PHP message: PHP Notice:  Undefined index: type in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 507 PHP message: PHP Notice:  Undefined variable: type in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 513 PHP message: PHP Notice:  Undefined variable: type in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 513'

**Comment by yubiuser** [comment]
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1470

**Comment by wienfuchs** [comment]
closed due to duplicate issue
