### ISSUE TITLE
Chronometer unable to retrieve FTL Data

### ISSUE THREAD

**Issue by PureFallen** [pi-hole/pi-hole#3558]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the contributors guide.
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate.

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behavior:**

The chronometer should display the blocked domains in gravity database, amount of blocked DNS requests in the 24 hours as well of informations about which domains were affected and not.

**Actual behavior:**

Chronometer thinks, that pihole-FTL is offline and all information usually provided by FTL is either `0` or blank.

**Steps to reproduce:**

- Run `pihole -up` to update to pihole-FTL 5.1
- Run `pihole -c` to view the Chronometer

**Troubleshooting undertaken, and/or other relevant information:**

The issue seems to be caused by Chronometer attempting to get the pihole-FTL API Port from the file `pihole-FTL.port`, which is no longer created starting at pihole-FTL version 5.1 ([related commit](https://github.com/pi-hole/FTL/commit/af9107a338420a592877ae350aa37b77eafb1e59)).
A similar issue exists on [PADD](https://github.com/pi-hole/PADD). pi-hole/PADD#112

**Comment by pheiduck** [comment]
Have the same issue on LCD Display on Raspbian Lite x32 and by executing `pihole -c` on terminal.
`pihole -r` doesn't resolve this for me.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-pihole-c-bug/35674/2

**Comment by dschaper** [comment]
Please use https://github.com/pi-hole/PADD/issues/112 for follow up.

**Comment by pheiduck** [comment]
echo 4711 > /var/run/pihole-FTL.port didn't resolve it on my LCD have a Script to execute it > https://discourse.pi-hole.net/t/set-5-display-on-pi-hole-to-show-stats/17756/3

**Comment by dschaper** [comment]
Please use the other thread as I have requested.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-c-show-ftl-offline/35893/2
