### ISSUE TITLE
Better handling of sudo in scripts?

### ISSUE THREAD

**Issue by ryt51V** [pi-hole/pi-hole#356]
Right now most of the scripts detect if not running as root, and if so then sudo every command.  This is done by nearly every command being prepended with the $SUDO variable.

Is there a reason we don't simply have the script rerun **itself** with sudo if it's not running as root?

```
if [[ <not running as root logic > ]]; then
    sudo "$@"
    exit $?
fi

<rest of script>
```

I use the above regularly and as far as I can tell it works great.  It's less error prone when adding new commands, and it will work better in obscure sudo configurations (e.g. imagine the current scripts if someone had password caching turned off).  It also has a minor speed boost for each command run.

The only downside I see with the above is you're not super-strictly abiding by principle of least privilege.  But since 90% of the script uses sudo I think it's over-the-top, and in any case I don't think it really matters if we're running echo and whiptail as root, does it?

Happy to do this myself and make a pull request, but would appreciate knowing whether I'm being stupid here or not!
##

**Comment by dschaper** [comment]
My thoughts would be, are we doing anything in the scripts that if run with `sudo` would cause permissions issues? We just added in the `pihole` user and in the future we'd like to have that user carry as much of the load as possible. The great thing about GitHub though is that we can branch the code and develop the idea and if it works out, then awesome, and if it doesn't work out, we at least learned something. And with being able to cherry pick commits, we can integrate ideas that work even if the idea as a whole doesn't work. 

I don't think you're being stupid at all, that may be a great way to run the script as `sudo` or to run portions of the script(s) as our `pihole` user... 

If you'd like, I can create a branch for you now so we don't have to do the remote branch switch up and confuse everyone like I was doing originally?

**Comment by ryt51V** [comment]
Apologies, suppose I should have just gone ahead and begun work and asked for forgiveness later ;-).  If you can forgive a newbie to GitHub.

In my unrelated testing so far, I have always run the scripts explicitly with sudo - meaning the whole script is run as root and so is almost identical to having the script rerun itself with sudo.  No issues with this so far so in theory should work fine.  IMO it's best we move towards running the script as a single user (whether root or pihole) rather than individual sudos as it makes for a more consistent script.

I'll begin putting it together later today.  I have no problem whether I work on a branch of the main repo or of my own fork and using pull requests - if you create a branch in the next few hours then I'll use that.

For root vs pihole it probably depends on the script.  The installer probably heavily relies upon root, the others perhaps not so much.  We can always rerun with `sudo "$@"` to begin with and then move to `sudo -u pihole "$@"`.  If running as root we can always `sudo -u pihole` any individual command (the opposite would probably cause issues or at least not be a good idea).  I'll consider that when working on it.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/tree/Feature/ryt5V-sudo

**Comment by dschaper** [comment]
Sorry, try this instead https://github.com/pi-hole/pi-hole/tree/Feature/ryt51V-sudo

**Comment by jacobsalmela** [comment]
I think this might solve what this thread was about:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L66
