### ISSUE TITLE
CNAME subdomains not resolved

### ISSUE THREAD

**Issue by ocha** [pi-hole/pi-hole#3561]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behavior:**

```
; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @127.0.0.1 -p 5053 www2.circleci.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5331
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: f2227bb9c203c893 (echoed)
;; QUESTION SECTION:
;www2.circleci.com.		IN	A

;; ANSWER SECTION:
www2.circleci.com.	55	IN	CNAME	circleci2.mktoweb.com.
circleci2.mktoweb.com.	55	IN	CNAME	ab22.mktossl.com.
ab22.mktossl.com.	55	IN	A	104.17.72.206
ab22.mktossl.com.	55	IN	A	104.17.74.206
ab22.mktossl.com.	55	IN	A	104.17.70.206
ab22.mktossl.com.	55	IN	A	104.17.73.206
ab22.mktossl.com.	55	IN	A	104.17.71.206

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Thu Jul 16 16:15:59 UTC 2020
;; MSG SIZE  rcvd: 321
```

**Actual behavior:**

```
; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @127.0.0.1 -p 53 www2.circleci.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28814
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 60f7838838dc5c29 (echoed)
;; QUESTION SECTION:
;www2.circleci.com.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jul 16 16:15:56 UTC 2020
;; MSG SIZE  rcvd: 58
```

**Steps to reproduce:**

1. install `cloudflared` DNS over HTTPS service on pihole and configure pihole to use only DoH server. Installation done using following guide: https://docs.pi-hole.net/guides/dns-over-https/
2. Make sure you are running latest cloudflared version `cloudflared version 2020.7.3 (built 2020-07-13-2001 UTC`
3. Use dig to see response for `www2.circleci.com` on pihole: `dig @127.0.0.1 -p 53 www2.circleci.com`
4. Observe that answer is missing.
5. Query cloudflared directly and observe that answer is there: `dig @127.0.0.1 -p 5053 www2.circleci.com`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/ntr6qmskdc

`ntr6qmskdc`

**Troubleshooting undertaken, and/or other relevant information:**
I upgraded cloudflared to latest version but that did not fix. I also tried using cloudflare ips instead of doh from DNS settings page. I still have same issue so I dont think it is related to DoH. I observer similar behaviour on other subdomains after upgrading to FTL 5.0, before that I never noticed this issue.

**Comment by jfb-pihole** [comment]
This appears to be the CNAME blocking feature of V5.x working.  If a domain along the CNAME path is blacklisted, the original domain you requested is blocked as well, unless you specifically whitelist the original domain.  See discussion in the V5 release notice:

https://pi-hole.net/2020/05/10/pi-hole-v5-0-is-here

**Comment by ocha** [comment]
thanks @jfb-pihole . Is it possible to check for this kind of blocking through the UI (similar to Query Lists) or see in FTL log? I checked both of them when trying to debug and did not see anything meaningful. My first instinct is usually to query the blocklist and see if domain is blocked. if deep CNAME blocking showed up there, I would not have created the issue

**Comment by jfb-pihole** [comment]
These type of blocks are shown in the query log on the web admin GUI.
