### ISSUE TITLE
Issues post-upgrade to 5.0

### ISSUE THREAD

**Issue by mix3d** [pi-hole/pi-hole#3566]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behavior:**
After upgrading from v4 to v5, everything should work as expected.

**Actual behavior:**
After upgrading from v4 to v5, Admin stats no longer work. API returns 500 errors consistently.
5.0 and 5.1 both exhibit this issue. DNS blocking still seems to work. 

**Steps to reproduce:**
Have not taken the nuclear option and reinstalled the OS.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

 https://tricorder.pi-hole.net/20z7m81frp

**Troubleshooting undertaken, and/or other relevant information:**

Attempted `pihole -r` a few times. Manually installed php7.3-common because `apt-get upgrade` complained it was missing.

Relavant info from logs:
```
   2020-07-15 11:15:51: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
   2020-07-15 11:15:51: (mod_fastcgi.c.421) FastCGI-stderr: 
   2020-07-15 11:15:51: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/api.php on line 139
   2020-07-15 11:16:52: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139
```
However, php7.3-json is already installed ... 

Warnings output to console during `pihole -r`

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'xmlreader.so' (tried: /usr/lib/php/20180731/xmlreader.so (/usr/lib/php/20180731/xmlreader.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xmlreader.so.so (/usr/lib/php/20180731/xmlreader.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xsl.so' (tried: /usr/lib/php/20180731/xsl.so (/usr/lib/php/20180731/xsl.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xsl.so.so (/usr/lib/php/20180731/xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
PHP Warning:  PHP Startup: Unable to load dynamic library 'xmlreader.so' (tried: /usr/lib/php/20180731/xmlreader.so (/usr/lib/php/20180731/xmlreader.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xmlreader.so.so (/usr/lib/php/20180731/xmlreader.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xsl.so' (tried: /usr/lib/php/20180731/xsl.so (/usr/lib/php/20180731/xsl.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xsl.so.so (/usr/lib/php/20180731/xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xmlreader.so' (tried: /usr/lib/php/20180731/xmlreader.so (/usr/lib/php/20180731/xmlreader.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xmlreader.so.so (/usr/lib/php/20180731/xmlreader.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xsl.so' (tried: /usr/lib/php/20180731/xsl.so (/usr/lib/php/20180731/xsl.so: undefined symbol: dom_node_class_entry), /usr/lib/php/20180731/xsl.so.so (/usr/lib/php/20180731/xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by mix3d** [comment]
Upgraded to `Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2`, and am still experiencing these issues. What could have happened during the v4 -> v5 upgrade that would cause xml parsing libraries to break?

**Comment by dschaper** [comment]
I really don't know, that is all on a level we don't affect.

**Comment by yubiuser** [comment]
Check which php packages are missing:

 PIHOLE_WEB_DEPS=(lighttpd "${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "${phpVer}-intl")

**Comment by mix3d** [comment]
I solved it by purging all php related packages and reinstalling them. A bit nuclear, sure, but it is working again. Weird.
