### ISSUE TITLE
Unable to retrieve query data older than 24 hours

### ISSUE THREAD

**Issue by DemonicHell** [pi-hole/pi-hole#3569]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behavior:**
Pi-Hole to display a list of blocked dns queries for the specified time frame / log of queies

**Actual behavior:**

after several seconds of processing the web ui displays "an unknown error has occured ..."

![image](https://user-images.githubusercontent.com/68402199/87724351-2b9a0480-c770-11ea-81d4-38b160cb73e9.png)

**Steps to reproduce:**
open web ui
go to the long-term data tab
select any time frame longer than last 24 hours from the pull down in the main window

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

9gz990jro9

**Troubleshooting undertaken, and/or other relevant information:**
note: running in a Virtual Machine
this started after updating to v5.1 and restarting the Pi-Hole VM

restarted the VM
Increased the available RAM of the VM from 1GB to 4GB

excet from the log 
![image](https://user-images.githubusercontent.com/68402199/87724708-c4308480-c770-11ea-84b5-2e6c545b4441.png)

**Comment by yubiuser** [comment]
You have to increase the memory limit of php. See here:

https://discourse.pi-hole.net/t/querying-long-term-data-failed-due-to-limited-allowed-memory-for-php-resulting-in-an-unknown-error-occurred-with-loading-the-data/27979

**Comment by DemonicHell** [comment]
Increasing the php memory limit resovled this issue 

please close
