### ISSUE TITLE
chmod 777

### ISSUE THREAD

**Issue by koen84** [pi-hole/pi-hole#357]
I was checking the code before running with it (you know, executing as root and for a device central to the network).

I noticed a chmod 777 in gravity.sh on line 131 ?
And as far as i understand, EVERY pihole will execute this (except on first run, likely the install or else test).

I know many websites and fora seem to promote this as a "fix all", usually followed by a comment on why this is "evil", for it being a massive security risk.  If it REALLY needs R/W access by another user, why not do chown ?  But then again, i have ZERO files or directories in /etc that are owned by anyone else than root.

I hope this can be changed.
(In checking the code + comments, i've also not found where the need for this comes from, but i'm probably missing something obvious.  If i understood, i might be able to think of a solution.)
##

**Comment by kmr2319** [comment]
Based on the comments, "existing" installs are the problem from versions priror to 2.5.3 where there was no "pihole" user. 

For example on my install which was prior to 2.5.3, the /etc/cron.d/pihole still has all jobs running as root rather than pihole. In addition, (assuming RPi only installs as that was the "original" intent) the default user of "pi" would likely still need access to this directory and /var/www/html. See comments in [this pull request](https://github.com/pi-hole/pi-hole/pull/242) for some additional details (be sure to read the comments). There's more to it than just gravity.sh.

**Comment by koen84** [comment]
The 777 is set on /etc/pihole directory.

The /var/www/html gets chown www-data:www-data in basic-install and then the user pihole is added to the www-data group, effectively getting both lighthttpd and pihole user write access.  (I haven't looked into the webinterface code yet.)

The cron from current master (2.5.3 i presume, looking at releases) still runs as root.

From the linked PR i understand the pihole user is currently just made, not much used ?  And if it's specifically related to prior 2.5.3 it's pity it runs also on everything more recent.  (Seeing throughout the repo security IS taken seriously.)

**Comment by dschaper** [comment]
That was my massively ugly hack to fix a problem we had with permissions errors, and I just didn't get to fixing it with something not so ugly. Trying to remember what problem existed, but it was an issue with existing installs having some permission bits set that caused crashing on an update. This issue predates the introduction of the "pihole" user, this was was back a few months ago, before we fixed the IPv6 issue. It was to do with legacy installations (thing version 1.0 and prior).

**Comment by dschaper** [comment]
And yes, the "PiHole" user hasn't been put to use yet, but the central idea is to get away from using either root, sudo to do everything and also to take into consideration platforms and OSes that do not have the "Pi" user either. (Non-RasPi installs). We're trying to balance security, backwards compatibility and stability at once. One of Jacob's primary ethos for the project is stability above all.

**Comment by koen84** [comment]
Migration script for drastic changes ?

Depending on where files are placed, requiring root or sudo is actually the sane thing to do.  I guess there's a lot to consider, but what might seem a quick fix now, might lead to more complications later (or downright security issues).

And i can definitely value putting effort on stability.
Though i wouldn't want to sacrifice security either.

**Comment by dschaper** [comment]
Agreed
