### ISSUE TITLE
Unable to save IPv6 format including port (e.g. fd00::1#5053) in Custom DNS settings

### ISSUE THREAD

**Issue by MichlW** [pi-hole/pi-hole#3571]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behavior:**

Enter a Custom DNS in IPv6 format including a custom port number.

**Actual behavior:**

Custom DNS in IPv4 format including custom port (e.g. 172.17.0.1#5053) works as expected.
Custom DNS in IPv6 format (e.g. fd00::1) works as expected.
Custom DNS in IPv6 format including custom port (e.g. fd00::1#5053) **does not work**.

The following message occurs on top of the Pi-hole settings page:
```
Info
[✗] Invalid IP has been passed
The DNS settings have been updated (using 2 DNS servers)
```
After this, the field Custom DNS 3 remains empty.

Upgrading from Pi-Hole v5.0 to v5.1.1 with an existing configuration, the entry is initially correct in the field, but disappears with the error message given above as soon as you want to save the page.

It all worked properly in Pi-Hole v5.0.

**Steps to reproduce:**

Entering Custom DNS 3 in IPv6 format including a custom port.

**Comment by yubiuser** [comment]
Looks similar like https://github.com/pi-hole/AdminLTE/issues/1499.

Issue might be the`#PORT'' in IPv6.

**Comment by PromoFaux** [comment]
Should be fixed in the next hotfix with this commit:

https://github.com/pi-hole/pi-hole/pull/3564/commits/643d2c0f3ea7871b64f9eaa2c9a5a2060d9ad14e

**Comment by MichlW** [comment]
#https://github.com/pi-hole/AdminLTE/issues/1499

**Comment by compuguy** [comment]
I have the same exact issue when trying to add ipv6 localhost/loopback as a custom dns server (::1#5300).

**Comment by dschaper** [comment]
Until it is `127.0.0.1#5300` is just as valid and just as functional.

**Comment by compuguy** [comment]
Agreed @dschaper, ipv4 loop-back is perfectly fine for now.

**Comment by dschaper** [comment]
Everything for 5.1.2/5.2 is ready to go, it's now a matter of getting the 3 of us in the right place at the right time. Eastern hemisphere vs Western hemisphere.

**Comment by compuguy** [comment]
I can confirm that 5.1.2/5.2 resolves this issue. This issue and https://github.com/pi-hole/AdminLTE/issues/1499 can be closed.
