### ISSUE TITLE
Conditional Forwarding for other subnet sizes

### ISSUE THREAD

**Issue by Conor-Burns** [pi-hole/pi-hole#3572]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

`Conditional Forwarding should allow different subnet sizes`

**Actual behavior:**

[Screenshot](https://s.0xcb.dev/2PhfV)

**Steps to reproduce:**

`setting the size to /20 for example`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`qnpv3n7c38`

**Troubleshooting undertaken, and/or other relevant information:**

`I don't know how`

**Comment by yubiuser** [comment]
Dnsmasq allows only /8, /16, /24.

https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975

**Comment by Conor-Burns** [comment]
Dang it - thought i looked everywhere for duplicates ._.

Thank you!

**Comment by yubiuser** [comment]
I confess: it's hard to find :-)
