### ISSUE TITLE
Graphic bugs after updating from 5.0 to 5.1.1

### ISSUE THREAD

**Issue by gius01** [pi-hole/pi-hole#3576]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:1

---
**Expected behavior:**

1. When I go to https://pi.hole/admin/ I expect to see all the stats equally if I go to https://*pihole-ip-address*/admin/
2. From my system's terminal, when I give "pihole -c" command, I can see correctly the services'status

**Actual behavior:**
1. After the update, this is the situation:

<blockquote class="imgur-embed-pub" lang="en" data-id="nl0uEDP"><a href="https://imgur.com/nl0uEDP">access from https://pi.hole/admin/</a></blockquote>

<blockquote class="imgur-embed-pub" lang="en" data-id="gnSJzyy"><a href="https://imgur.com/gnSJzyy">access from https://*pihole-ip-address*/admin/</a></blockquote>

2. The FTL service results "offline" if I run from CLI "pihole -c", but it's active and working properly, as Pi-Hole filters correctly my traffic:

<blockquote class="imgur-embed-pub" lang="en" data-id="WZv9tKK"><a href="https://imgur.com/WZv9tKK">CLI</a></blockquote>
<blockquote class="imgur-embed-pub" lang="en" data-id="ADQahCo"><a href="https://imgur.com/ADQahCo">FTL working from GUI</a></blockquote>

**Steps to reproduce:**

1. Easily accessing from my browser Pi-Hole GUI
2. From CLI, giving "pihole -c command"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

t2kpknh3mu

**Troubleshooting undertaken, and/or other relevant information:**

I have formatted and reinstalled cleanly my system, so these troubles don't depend by my configuration

**Comment by technicalpyro** [comment]
Looking at your log file I do not see any errors that would cause this.  

We have noticed after updates at time the cached java causes issues have you cleared the cache on the browser you're using [ctrl]+[f5] on most

**Comment by yubiuser** [comment]
>The FTL service results "offline" if I run from CLI "pihole -c", but it's active and working properly, as Pi-Hole filters correctly my traffic

Known bug, fix in pipeline already. More info at https://discourse.pi-hole.net/t/pi-hole-5-1-pihole-c-bug/35674

**Comment by gius01** [comment]
thank you guys, you were right, I fixed all the issues :)

**Comment by technicalpyro** [comment]
no that file only gets created/modified during install or update

**Comment by dschaper** [comment]
It does need to be done on each reboot. It's safe to do it any time really.

**Comment by dschaper** [comment]
The proper fix is 
`echo 4711 | sudo tee /var/run/pihole-FTL.port` as you need root priv's to be able to write that file.

**Comment by javierin** [comment]
Also, for the never ending loading graphs, you can try forcing a browser refresh using Ctrl F5.
