### ISSUE TITLE
Pihole install fails silently with MS WS2008R2 upstream DNS

### ISSUE THREAD

**Issue by Pyrroc** [pi-hole/pi-hole#3578]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behavior:**

Execute "curl -sSL https://install.pi-hole.net | bash" as root and completes successfully

**Actual behavior:**

Silent install script failure after prerequisites check, during the OS check.

**Steps to reproduce:**

    Microsoft DNS upstream (experienced with WS2008R2 - unknown if newer versions have the same issue)
    vmware esxi 6.7, 1 vCPU, 1GB RAM, 8GB HDD
    Debian 10.4 (both netinstall and DVD isos)
    Minimum install: SSH Server, Standard System Utilities... (no desktop at all)
    Had to add: sudo, curl
    sudo -i
    Executed: curl -sSL https://install.pi-hole.net | bash

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

pihole does not install successfully so no token possible

**Troubleshooting undertaken, and/or other relevant information:**

Worked with @dschaper to discover that the MS DNS server (at least WS2008R2) does not handle DNS cookie options correctly, returning a status of FORMERR and no upstream results.

**Workaround: (could be permanent fix if warranted)**

1. Download script:  curl -sSL https://install.pi-hole.net > install-script-sh
2. Add +nocookie to the dig command: dig +short -t txt +nocookie ${remote_os_domain}
3. chmod the script to executable and execute as root 

**Possible script change for non-silent failure**

Replace current line 190:

    IFS=" " read -r -a supportedOS < <(dig +short -t txt ${remote_os_domain} | tr -d '"')

with:

     dig_result=$(dig +short -t txt ${remote_os_domain} | tr -d '"')
     if [ "${#dig_result}" == 0 ]; then
        printf "Upstream DNS Error: Possible upstream Microsoft DNS or firewall blocking error\\n"
        printf "      Check the result of: dig -t txt %s\\n\\n" "${remote_os_domain}"
        exit 1
     fi
     IFS=" " read -r -a supportedOS <<< "${dig_result}"

which checks the result of the dig for a zero length response and errors/exits if it is.

**Comment by Pyrroc** [comment]
FYI, my ultimate aim is to replace the existing upstream MS WS2008R2 DNS infrastructure.

**Comment by dschaper** [comment]
Thanks, this may be a good place to start introducing bash shell `trap` logic into some of the functions. 

https://www.linuxjournal.com/content/bash-trap-command

**Comment by yubiuser** [comment]
What was the reason to put `supportedOS` on the pihole servers and let users download it every time by dig in the first place? This introduces pitfalls with dig as we have seen. To circumvent this, you could simple put the supported os and versions as arrays right in the installer script. 
I don't see the advantages to have it hostes in a separate file.

**Comment by PromoFaux** [comment]
I guess we could hardcode them as a fallback.

The idea was so that we could add to the list if we needed to without having to release a new version of the software.

E.g, if we discovered that 5.1 was fully compatible with mint after we have released it, we can add that to versions.pi-hole.net without having to do a point release just to add the compatibility check for it. 

The compatibility check can be circumvented with an ENV var, so in theory op should be able to just set that and continue (albiet with this current issue, there is nothing to tell them to do that)

**Comment by PromoFaux** [comment]
> so in theory op should be able to just set that and continue

Although, reading through the `bash -x` snippet in the discourse thread, and checking against the code... maybe that wouldn't work in this case.

**Comment by pvogt09** [comment]
> Thanks, this may be a good place to start introducing bash shell `trap` logic into some of the functions.

A PR for introducing such functionality is already open in #2288, maybe that can be taken as starting point.

**Comment by dschaper** [comment]
@yubiuser You need to have `dig` working to be able to `curl -sSL https://install.pi-hole.net` so I don't see requiring `dig` to work to pass a version check is a problem.

**Comment by dschaper** [comment]
@pvogt09 #228 is over 2 years old, it may have some good ideas but it's horribly out of date.

**Comment by dschaper** [comment]
> maybe that wouldn't work in this case.

It didn't work in this case because the system being installed onto was broken. This isn't a fix for installing Pi-hole, this is a fix that will tell people why Pi-hole isn't going to be installed.

**Comment by yubiuser** [comment]
Has been fixed by hardcoding @ns1@pi-hole.net in https://github.com/pi-hole/pi-hole/pull/3596
