### ISSUE TITLE
Are Password-Hashes salted?

### ISSUE THREAD

**Issue by void-m4110c** [pi-hole/pi-hole#3579]
Hi, 

quick question, are the hashed admin passwords finally being salted?

Greetings

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/issues/2168

**Comment by void-m4110c** [comment]
I did not ask about this or that hashing algorithm. I specifically asked if the hash is **salted**. This is no high tech "banking app" security requirement, but a basic security measure.

Btw. in that thread you mentioned (which is 2 years old) someone asked the exact same question and didn't get any response.
Just search for "salted" on that thread...
