### ISSUE TITLE
On MacOS Safari 13.1.2 the Query Types and Queries answered by graphic are not load in Pi-hole v5.1.1

### ISSUE THREAD

**Issue by rheid** [pi-hole/pi-hole#3583]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10
---
**Expected behavior:**

On MacOS Safari 13.1.2 the Query Types and Queries answered by graphic are not load in Pi-hole v5.1.1

**Actual behavior:**

Shows Loading Spinner 

**Steps to reproduce:**

Login to the admin interface
![screen-2020-07-20-112751](https://user-images.githubusercontent.com/1476336/87922839-d5cda100-ca7c-11ea-9ef4-391ff39e1ba3.png)

**Comment by yubiuser** [comment]
Have you cleared your browser's cache?

**Comment by rheid** [comment]
@yubiuser  I've tried that too. But with the Chrome Browser it looks good.

**Comment by rheid** [comment]
Thanks I run now on privat mode the it's working.
