### ISSUE TITLE
Status unknow, wrong permission?

### ISSUE THREAD

**Issue by leaderred** [pi-hole/pi-hole#3585]
<img width="225" alt="pihole" src="https://user-images.githubusercontent.com/3801152/87963271-bc4a4a80-cab8-11ea-9343-c2ad275d24e2.png">
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behavior:**

Fresh install on Raspbian with debian 10, rpi4.
No errors while installation, no lightpd, nginx instead.
On v4 everything was working with this constellation.

When i open admin web interface, nearby everything is working correctly. 
I could change dns server, import data backups und navigate without an error. 
Blocking is also working.

**Actual behavior:**

- Status on top left shows "unknown", Toggle for "enable" and "disable" are shown in sidebar. When i am clicking these, status is show correctly until next site refresh. Manually toggle state by console works without an error, but is not shown in web.

- Updating gravity by web is not working. I can open and start this section, but i get no result. When i do this on console with "sudo pihole -g" everything is working. 

- Following functions are not working from web: ppdating white/blacklist, add local dns entries, activate dhcp server
Response is ok, but no changes are done

**Steps to reproduce:**

Current install instructions an rpi 4 with current raspbian on debian 10 base.
I have a separate web user for my web projects without root access. I places all web files under his home folder, so prevent permission issues with services. All files for pihole moved from /var/www/html to /home/web/pihole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/g5l2a3va76

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

I think its might be an permission error for web user. I checked web folder permission and manually set it to 755 and MYUSER:www-data. 
/etc/pihole has permission for pihole/pihole, files inside are most root:users.
www-data is in sudoers and should have access to pihole binary.

**Comment by yubiuser** [comment]
>No errors while installation, no lightpd, nginx instead.

Nginx is not officially supported by pihole. But you can follow the guide, which should help you using nginx

https://docs.pi-hole.net/guides/nginx-configuration/

**Comment by dschaper** [comment]
```plain
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 403 Forbidden
Server: nginx/1.14.2
Date: Mon, 20 Jul 2020 16:28:52 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive


[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 404 Not Found
Server: nginx/1.14.2
Date: Mon, 20 Jul 2020 16:28:52 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
```

Visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by leaderred** [comment]
Finally i found the error, for those, who have this problem too.
In nginx log i see, that php have missing permissions:
"FastCGI sent in stderr: "PHP message: PHP Warning:  Executing sudo pihole status web failed."

On Raspbian 10 my /etc/sudoers.d/pihole file was ignored, so no command could be executed by php. I have to manually add the command from this file to "sudo visudo". Also my separate web user must have sudo group, to execute pihole commands with sudo without password. Now everything is working fine.
