### ISSUE TITLE
All pihole commands only result in "line 229: syntax error: unexpected end of file"

### ISSUE THREAD

**Issue by ghnu** [pi-hole/pi-hole#3588]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behavior:**

pihole commands working

**Actual behavior:**

Even a simple pihole provides this output:
/usr/local/bin/pihole: line 229: syntax error: unexpected end of file

**Steps to reproduce:**

pihole

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

not possible, since pihole command does not work

**Troubleshooting undertaken, and/or other relevant information:**

running version 5
The software itself runs, web interface is working and functionality is fine

**Comment by yubiuser** [comment]
Compare your local pihole script with 

https://github.com/pi-hole/pi-hole/blob/56cd7c4d59ceb629a2170cd1c8ab78ef26366019/pihole


As you see, it should not end at line 229.

**Comment by ghnu** [comment]
OK, mine looks identical to that, until line 38.

After that, it goes on with this:
  # Pull off the `debug` leaving passed call augmentation f19\.118-v8\+$";
APT::NeverAutoRemove:: "^linux-signed-image-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^linux-signed-image-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^linux-image-unsigned-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^linux-image-unsigned-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^kfreebsd-image-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^kfreebsd-image-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^kfreebsd-headers-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^kfreebsd-headers-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^gnumach-image-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^gnumach-image-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^.*-modules-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^.*-modules-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^.*-kernel-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^.*-kernel-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^linux-backports-modules-.*-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^linux-backports-modules-.*-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^linux-modules-.*-4\.15\.0-99-generic$";
APT::NeverAutoRemove:: "^linux-modules-.*-4\.19\.118-v8\+$";
APT::NeverAutoRemove:: "^linux-tools-4\.15\.0-99-generic$";

And finally ends with a PGP signature.

???

So that file on my RPI looks corrupted.

How to get the correct one back?

**Comment by yubiuser** [comment]
Try `pihole -r`, select repair. Not sure if it can recover or if the script is to damaged.
You could copy&paste the above linked script into your local copy - but other files might be corrupted too. Last option would be completely new install.

**Comment by ghnu** [comment]
pihole -r also does not work, so reinstall seems to be the only option.

How to store the configuration I currently have, so that I can easily reapply it to the new installation?

**Comment by yubiuser** [comment]
If it works, do a teleporter backup.

If not, manually copy `custom.list` (for Local DNS Record) and `gravity.db` (for Adlists, Group Management) from `/etc/pihole/`.

Do you have more configuration changes (like DHCP leases)?
