### ISSUE TITLE
hostname displayed with unrendered `i` tags

### ISSUE THREAD

**Issue by puddlewitt** [pi-hole/pi-hole#3591]
Pi-hole v5.1.1 
Web Interface v5.1
FTL v5.1

**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

When the `DHCP leases` table is displayed and the hostname is not known then the text `unknown` should be displayed and styled with italics

**Actual behavior:**

The hostname is displayed with tags

![image](https://user-images.githubusercontent.com/2998294/88029918-8053cb80-cb32-11ea-9755-f6c8c02bc2ad.png)

**Steps to reproduce:**

1. Navigate to `settings` -> `DHCP`
2. View the `DHCP leases` table

**Comment by puddlewitt** [comment]
Created in wrong repo.

**Comment by mill1000** [comment]
What's the correct repo for this issue? Where is this issue tracked?

**Comment by dschaper** [comment]
https://github.com/pi-hole/AdminLTE
