### ISSUE TITLE
Downstream DNS server does not resolve local DNS records on pi-hole

### ISSUE THREAD

**Issue by TheLion** [pi-hole/pi-hole#3594]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behavior:**

I expect pi-hoe to resolve a local DNS records for a downstream DNS server (in a different subnet that is connected through an IPSEC tunnel) that uses pi-hole as a STUB zone.

**Actual behavior:**

pi-hole forwards the DNS request to the upstream DNS server, which results in a failure for lookup.

**Steps to reproduce:**

Create a stub zone on a downstream DNS server, try to resolve a local DNS record from a machine that uses the downstream DNS server.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

2qn6cqdbdd

**Troubleshooting undertaken, and/or other relevant information:**

Tried it from several different downstream DNS servers, all produce the same result. When the downstream DNS server with pi-hole on the machine that normally uses the downstream DNS, all queries are resolved correctly.

**Comment by dschaper** [comment]
Can you provide some examples of what you are referring to? Along with the Pi-hole configurations you set to have Pi-hole be aware of the downstream DNS server, along with what you define as a downstream DNS server?

**Comment by TheLion** [comment]
> Can you provide some examples of what you are referring to? Along with the Pi-hole configurations you set to have Pi-hole be aware of the downstream DNS server, along with what you define as a downstream DNS server?

Hi Dan. Thanks for taking the time to reply. 

To answer your question. I haven't done anything in pi-hole to make it aware of a downstream server. I don't have much experience with DNS servers on Linux, but I do have quite some experience with Windows DNS and that is where this question comes from. It is almost certainly a lack of knowledge on my part ;-)

What I am trying to accomplish is the following.

Pi-hole runs at home and performs DHCP and DNS for the local LAN. Pi-hole has some local DNS records for devices with fixed IP-adresses, thanks to the new function. Clients directly using pi-hole as DNS can resolve these without issues. 

At the office, which is connected to home with a site-to-site VPN tunnel, (which results in a free flow of IP traffic between the home and office LAN) also has a DNS server, which is the standard DNS server in Windows Server. This server has a so-called STUB zone for the zone at home. With this setup, clients (mainly me ;-)) can use the DNS server in the office for resolving devices in the zone at home. The query is forwarded to pi-hole (it shows on the pi-hole log) when a query is received for the zone at home and pi-hole forwards the query to its upstream even though it has a local DNS record for the device, which results in a failed query and the client in the office can't connect.

This setup works beautifully with only Windows DNS servers and I was hoping to get it working with pi-hole. 

I hope my explanation it clear. If not please let me know.

**Comment by yubiuser** [comment]
Does the issue still persist?
