### ISSUE TITLE
Install Fails at "Unsupported OS detected"

### ISSUE THREAD

**Issue by shawndy** [pi-hole/pi-hole#3595]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`
---
**Expected behavior:**

`{Pi 3 B+ OR Pi 4, PRETTY_NAME="Raspian GNU/Linux 10 (Buster)"
Installation completes beyond OS check.}`

**Actual behavior:**

`{[x] Unsupported OS Detected}`

**Steps to reproduce:**

`{either - url -sSL https://install.pi-hole.net | bash
or - git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh

-or environment changed to add "PIHOLE_SKIP_OS_CHECK=TRUE" (and confirmed in environment
or- adding the skip check to the command when launching installer}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{not installed, no log generated}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Reinstalled new images of OS, either on Pi 3 B+ or Pi 4.
Both fail OS check
'{I saw the closed feature request to report which failed version was detected. Considered altering os-release to match what is expected, but can't find example. }`

> * `{}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by shawndy** [comment]
I see the formatting errors, I will wear with pride for now.

**Comment by yubiuser** [comment]
Improvements to OS detection

https://github.com/pi-hole/pi-hole/pull/3567
https://github.com/pi-hole/pi-hole/pull/3582

**Comment by dschaper** [comment]
What does `dig -t txt versions.pi-hole.net` return as a result?

**Comment by shawndy** [comment]
pi@raspberrypi:~ $ dig -t versions.pihole.net
;; Warning, ignoring invalid type versions.pihole.net
;; Warning: Client COOKIE mismatch

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> -t versions.pihole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43294
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 00000000000000000000000000000000ffffffffffffffff (bad)
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			491449	IN	NS	l.root-servers.net.
.			491449	IN	NS	a.root-servers.net.
.			491449	IN	NS	e.root-servers.net.
.			491449	IN	NS	g.root-servers.net.
.			491449	IN	NS	b.root-servers.net.
.			491449	IN	NS	f.root-servers.net.
.			491449	IN	NS	h.root-servers.net.
.			491449	IN	NS	i.root-servers.net.
.			491449	IN	NS	k.root-servers.net.
.			491449	IN	NS	j.root-servers.net.
.			491449	IN	NS	d.root-servers.net.
.			491449	IN	NS	m.root-servers.net.
.			491449	IN	NS	c.root-servers.net.

;; Query time: 62 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Jul 21 14:43:50 EDT 2020
;; MSG SIZE  rcvd: 267

**Comment by yubiuser** [comment]
Try with `dig +nocookie -t txt versions.pi-hole.net`

**Comment by PromoFaux** [comment]
You also missed `txt` from the command

**Comment by shawndy** [comment]
ack! I hate typin' across monitors...

pi@raspberrypi:~ $ dig -t text versions.pihole.net
;; Warning, ignoring invalid type text
;; Warning: Client COOKIE mismatch

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> -t text versions.pihole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36081
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: ffffffffffffffffffffffffffffffff0000000000000000 (bad)
;; QUESTION SECTION:
;versions.pihole.net.		IN	A

;; ANSWER SECTION:
versions.pihole.net.	1800	IN	A	208.91.197.194

;; Query time: 92 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Jul 21 14:57:59 EDT 2020
;; MSG SIZE  rcvd: 92

**Comment by PromoFaux** [comment]
so close.... you missed a `-`

`dig -t text versions.pi-hole.net`

**Comment by shawndy** [comment]
longest typo thread winner... it a=seems I might be able to temporarily edit pretty name to Raspian=10?

pi@raspberrypi:~ $ dig -t txt versions.pi-hole.net
;; Warning: Client COOKIE mismatch

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> -t txt versions.pi-hole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30412
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: ffffffffffffffffffffffffffffffff0000000000000000 (bad)
;; QUESTION SECTION:
;versions.pi-hole.net.		IN	TXT

;; ANSWER SECTION:
versions.pi-hole.net.	60	IN	TXT	"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

;; Query time: 105 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Jul 21 15:07:27 EDT 2020
;; MSG SIZE  rcvd: 155

**Comment by PromoFaux** [comment]
@shawndy assuming you still have the copy of the repo from when you tried the alternative installation method can you please run the script again like so:

```
sudo bash -x basic-install.sh
```

If you already deleted it then this will do the same:

```
wget -O basic-install.sh https://install.pi-hole.net
sudo bash -x basic-install.sh
```

note the `-x` after `bash`!!

Once it has run, can you paste in the output please? You shouldn't need to be editing the PRETTY_NAME value

**Comment by shawndy** [comment]
pi@raspberrypi:~ $ sudo bash -x basic-install.sh
+ set -e
++ cat
+ DNS_SERVERS='Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS);208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH;84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered + ECS);9.9.9.11;149.112.112.11;2620:fe::11;
Cloudflare;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
+ installLogLoc=/etc/pihole/install.log
+ setupVars=/etc/pihole/setupVars.conf
+ lighttpdConfig=/etc/lighttpd/lighttpd.conf
+ coltable=/opt/pihole/COL_TABLE
+ webroot=/var/www/html
+ webInterfaceGitUrl=https://github.com/pi-hole/AdminLTE.git
+ webInterfaceDir=/var/www/html/admin
+ piholeGitUrl=https://github.com/pi-hole/pi-hole.git
+ PI_HOLE_LOCAL_REPO=/etc/.pihole
+ PI_HOLE_FILES=(chronometer list piholeDebug piholeLogFlush setupLCD update version gravity uninstall webpage)
+ PI_HOLE_INSTALL_DIR=/opt/pihole
+ PI_HOLE_CONFIG_DIR=/etc/pihole
+ PI_HOLE_BIN_DIR=/usr/local/bin
+ PI_HOLE_BLOCKPAGE_DIR=/var/www/html/pihole
+ useUpdateVars=false
+ adlistFile=/etc/pihole/adlists.list
+ IPV4_ADDRESS=
+ IPV6_ADDRESS=
+ QUERY_LOGGING=true
+ INSTALL_WEB_INTERFACE=true
+ PRIVACY_LEVEL=0
+ '[' -z root ']'
+ '[' -t 0 ']'
++ stty size
+ screen_size='46 101'
+ printf -v rows %d 46
+ printf -v columns %d 101
+ r=23
+ c=50
+ r=23
+ c=70
+ skipSpaceCheck=false
+ reconfigure=false
+ runUnattended=false
+ INSTALL_WEB_SERVER=true
+ [[ -f /opt/pihole/COL_TABLE ]]
+ COL_NC='\e[0m'
+ COL_LIGHT_GREEN='\e[1;32m'
+ COL_LIGHT_RED='\e[1;31m'
+ TICK='[\e[1;32m✓\e[0m]'
+ CROSS='[\e[1;31m✗\e[0m]'
+ INFO='[i]'
+ DONE='\e[1;32m done!\e[0m'
+ OVER='\r\033[K'
+ counter=0
+ [[ '' != true ]]
+ main
+ local 'str=Root user check'
+ printf '\n'

+ [[ 0 -eq 0 ]]
+ printf '  %b %s\n' '[\e[1;32m✓\e[0m]' 'Root user check'
  [✓] Root user check
+ show_ascii_berry
+ echo -e '
        \e[1;32m.;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           '\''ccll:;ll .oooodc
             .;cll.;;looo:.
                 \e[1;31m.. '\'','\''.
                .'\'',,,,,,'\''.
              .'\'',,,,,,,,,,.
            .'\'',,,,,,,,,,,,....
          ....'\'''\'''\'',,,,,,,'\''.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'\''......
            ....'\'',,,,,,,,,,,,.
               .'\'',,,,,,,,,'\''.
                .'\'',,,,,,'\''.
                  ..'\'''\'''\''.\e[0m
'

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

+ make_temporary_log
++ mktemp /tmp/pihole_temp.XXXXXX
+ TEMPLOG=/tmp/pihole_temp.1fieen
+ exec
+ rm /tmp/pihole_temp.1fieen
+ distro_check
+ is_command apt-get
+ local check_command=apt-get
+ command -v apt-get
+ PKG_MANAGER=apt-get
+ UPDATE_PKG_CACHE='apt-get update'
+ PKG_INSTALL=("${PKG_MANAGER}" -qq --no-install-recommends install)
+ PKG_COUNT='apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+ APT_SOURCES=/etc/apt/sources.list
+ awk 'BEGIN{a=1;b=0}/bionic main/{a=0}/bionic.*universe/{b=1}END{exit a + b}' /etc/apt/sources.list
+ update_package_cache
+ local 'str=Update local cache of available packages'
+ printf '  %b %s...' '[i]' 'Update local cache of available packages'
  [i] Update local cache of available packages...+ eval 'apt-get update'
+ printf '%b  %b %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' 'Update local cache of available packages'
  [✓] Update local cache of available packages
+ apt-cache show iproute2
+ iproute_pkg=iproute2
+ is_command php
+ local check_command=php
+ command -v php
+ [[ '' != true ]]
+ apt-cache show php
+ phpVer=php
+ apt-cache show php-sqlite3
+ phpSqlite=sqlite3
+ INSTALLER_DEPS=(dhcpcd5 git "${iproute_pkg}" whiptail dnsutils)
+ PIHOLE_DEPS=(cron curl iputils-ping lsof netcat psmisc sudo unzip wget idn2 sqlite3 libcap2-bin dns-root-data libcap2)
+ PIHOLE_WEB_DEPS=(lighttpd "${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "${phpVer}-intl")
+ LIGHTTPD_USER=www-data
+ LIGHTTPD_GROUP=www-data
+ LIGHTTPD_CFG=lighttpd.conf.debian
+ [[ -f /etc/pihole/setupVars.conf ]]
+ [[ false == true ]]
+ verifyFreeDiskSpace
+ local 'str=Disk space check'
+ local required_free_kilobytes=51200
+ local existing_free_kilobytes
++ df -Pk
++ grep -m1 '\/$'
++ awk '{print $4}'
+ existing_free_kilobytes=11074896
+ [[ 11074896 =~ ^([0-9])+$ ]]
+ [[ 11074896 -lt 51200 ]]
+ printf '  %b %s\n' '[\e[1;32m✓\e[0m]' 'Disk space check'
  [✓] Disk space check
+ notify_package_updates_available
+ local 'str=Checking apt-get for upgraded packages'
+ printf '\n  %b %s...' '[i]' 'Checking apt-get for upgraded packages'

  [i] Checking apt-get for upgraded packages...++ eval 'apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+++ apt-get -s -o Debug::NoLocking=true upgrade
+++ grep -c '^Inst'
+ updatesToInstall=10
++ uname -r
+ [[ -d /lib/modules/4.19.118-v7l+ ]]
+ [[ 10 -eq 0 ]]
+ printf '%b  %b %s... %s updates available\n' '\r\033[K' '[\e[1;32m✓\e[0m]' 'Checking apt-get for upgraded packages' 10
  [✓] Checking apt-get for upgraded packages... 10 updates available
+ printf '  %b %bIt is recommended to update your OS after installing the Pi-hole!%b\n\n' '[i]' '\e[1;32m' '\e[0m'
  [i] It is recommended to update your OS after installing the Pi-hole!

+ install_dependent_packages dhcpcd5 git iproute2 whiptail dnsutils
+ counter=1
+ [[ 1 == 1 ]]
+ printf '  %b Installer Dependency checks...\n' '[i]'
  [i] Installer Dependency checks...
+ declare -a installArray
+ is_command apt-get
+ local check_command=apt-get
+ command -v apt-get
+ for i in "$@"
+ printf '  %b Checking for %s...' '[i]' dhcpcd5
  [i] Checking for dhcpcd5...+ dpkg-query -W '-f=${Status}' dhcpcd5
+ grep 'ok installed'
+ printf '%b  %b Checking for %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' dhcpcd5
  [✓] Checking for dhcpcd5
+ for i in "$@"
+ printf '  %b Checking for %s...' '[i]' git
  [i] Checking for git...+ grep 'ok installed'
+ dpkg-query -W '-f=${Status}' git
+ printf '%b  %b Checking for %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' git
  [✓] Checking for git
+ for i in "$@"
+ printf '  %b Checking for %s...' '[i]' iproute2
  [i] Checking for iproute2...+ grep 'ok installed'
+ dpkg-query -W '-f=${Status}' iproute2
+ printf '%b  %b Checking for %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' iproute2
  [✓] Checking for iproute2
+ for i in "$@"
+ printf '  %b Checking for %s...' '[i]' whiptail
  [i] Checking for whiptail...+ dpkg-query -W '-f=${Status}' whiptail
+ grep 'ok installed'
+ printf '%b  %b Checking for %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' whiptail
  [✓] Checking for whiptail
+ for i in "$@"
+ printf '  %b Checking for %s...' '[i]' dnsutils
  [i] Checking for dnsutils...+ dpkg-query -W '-f=${Status}' dnsutils
+ grep 'ok installed'
+ printf '%b  %b Checking for %s\n' '\r\033[K' '[\e[1;32m✓\e[0m]' dnsutils
  [✓] Checking for dnsutils
+ [[ 0 -gt 0 ]]
+ printf '\n'

+ return 0
+ os_check
+ local remote_os_domain valid_os valid_version detected_os_pretty detected_os detected_version display_warning
+ remote_os_domain=versions.pi-hole.net
+ valid_os=false
+ valid_version=false
+ display_warning=true
++ grep PRETTY_NAME
++ cat /etc/os-release
++ cut -d = -f2-
++ tr -d '"'
+ detected_os_pretty='Raspbian GNU/Linux 10 (buster)'
+ detected_os=Raspbian
++ grep VERSION_ID
++ cat /etc/os-release
++ cut -d = -f2-
++ tr -d '"'
+ detected_version=10
+ IFS=' '
+ read -r -a supportedOS
++ dig +short -t txt versions.pi-hole.net
++ tr -d '"'
+ for i in "${supportedOS[@]}"
++ echo ';;'
++ cut -d = -f1
+ os_part=';;'
++ echo ';;'
++ cut -d = -f2-
+ versions_part=';;'
+ [[ Raspbian =~ ;; ]]
+ for i in "${supportedOS[@]}"
++ echo Warning:
++ cut -d = -f1
+ os_part=Warning:
++ echo Warning:
++ cut -d = -f2-
+ versions_part=Warning:
+ [[ Raspbian =~ Warning: ]]
+ for i in "${supportedOS[@]}"
++ echo Client
++ cut -d = -f1
+ os_part=Client
++ echo Client
++ cut -d = -f2-
+ versions_part=Client
+ [[ Raspbian =~ Client ]]
+ for i in "${supportedOS[@]}"
++ echo COOKIE
++ cut -d = -f1
+ os_part=COOKIE
++ echo COOKIE
++ cut -d = -f2-
+ versions_part=COOKIE
+ [[ Raspbian =~ COOKIE ]]
+ for i in "${supportedOS[@]}"
++ cut -d = -f1
++ echo mismatch
+ os_part=mismatch
++ echo mismatch
++ cut -d = -f2-
+ versions_part=mismatch
+ [[ Raspbian =~ mismatch ]]
+ '[' false = true ']'
+ '[' true = true ']'
+ '[' '' '!=' true ']'
+ printf '  %b %bUnsupported OS detected%b\n' '[\e[1;31m✗\e[0m]' '\e[1;31m' '\e[0m'
  [✗] Unsupported OS detected
+ printf '      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems\n'
      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems
+ printf '\n'

+ printf '      This check can be skipped by setting the environment variable %bPIHOLE_SKIP_OS_CHECK%b to %btrue%b\n' '\e[1;31m' '\e[0m' '\e[1;31m' '\e[0m'
      This check can be skipped by setting the environment variable PIHOLE_SKIP_OS_CHECK to true
+ printf '      e.g: export PIHOLE_SKIP_OS_CHECK=true\n'
      e.g: export PIHOLE_SKIP_OS_CHECK=true
+ printf '      By setting this variable to true you acknowledge there may be issues with Pi-hole during or after the install\n'
      By setting this variable to true you acknowledge there may be issues with Pi-hole during or after the install
+ printf '      If that is the case, you can feel free to ask the community on Discourse with the %bCommunity Help%b category:\n' '\e[1;31m' '\e[0m'
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
+ printf '      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/\n'
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/
+ exit 1

**Comment by yubiuser** [comment]
Try `dig +nocookie -t txt versions.pi-hole.net`

If this successful, edit the `dig [..]` within the script.

**Comment by PromoFaux** [comment]
See here for similar:

https://github.com/pi-hole/pi-hole/issues/3578

**Comment by shawndy** [comment]
It was successful, but I don't know what "the dig" and "the script" are, are you referring to PromoFaux reference (#3578), or the "basic-install.sh"?

pi@raspberrypi:~ $ dig +nocookie -t txt versions.pi-hole.net

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> +nocookie -t txt versions.pi-hole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33761
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;versions.pi-hole.net.		IN	TXT

;; ANSWER SECTION:
versions.pi-hole.net.	60	IN	TXT	"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

;; Query time: 1824 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Jul 21 17:37:18 EDT 2020
;; MSG SIZE  rcvd: 127

**Comment by dschaper** [comment]
For some reason `dig +short -t txt versions.pi-hole.net` is dumping the warning header in to `supportedOS[@]`, which is unexpected. If it fails it should be silent. Can you run `dig +short -t txt versions.pi-hole.net` and provide that output?

**Comment by dschaper** [comment]
Also please output from `dig +noall +answer -t txt versions.pi-hole.net`

**Comment by shawndy** [comment]
version 1:
pi@raspberrypi:~ $ dig +short -t txt versions.pi-hole.net
;; Warning: Client COOKIE mismatch
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

version 2:
pi@raspberrypi:~ $ dig +noall +answer -t txt versions.pi-hole.net
;; Warning: Client COOKIE mismatch
versions.pi-hole.net.	60	IN	TXT	"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

pi@raspberrypi:~ $ dig +noall +answer -t txt versions.pi-hole.net
;; Warning: Client COOKIE mismatch
versions.pi-hole.net.	23	IN	TXT	"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

pi@raspberrypi:~ $ dig +short +nocomments -t txt versions.pi-hole.net
;; Warning: Client COOKIE mismatch
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

**Comment by dschaper** [comment]
Thanks for the output. Can you check one last try for me?

`dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net`

**Comment by MrConorAE** [comment]
I'm having a similar issue on my Raspberry Pi 4 (2GB RAM). I successfully installed Pi-Hole the first time, but when I went to reconfigure it (`pihole -r`, I'd seleced the wrong option for static IP), it reported an unsupported OS. It's a fresh install of Raspbian Lite (32-bit), which is listed as supported on the [Prequisites page](https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems).

**Comment by dschaper** [comment]
Do your tests of:
```plain
dig +short -t txt versions.pi-hole.net
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
dig +short +nocookie -t txt versions.pi-hole.net
```
show similar output as has been reported?

**Comment by shawndy** [comment]
~ $ dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"

**Comment by dschaper** [comment]
Great! I think we'll use that one then and skip the `+nocookie` modifier.

`dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net`

**Comment by dschaper** [comment]
So, `+nocookie` wouldn't work for you?

I'm pretty much set on the `@ns1` option and that's what's in the fix to be released.

**Comment by raphattack** [comment]
The `dig` version I have doesn't have a `+nocookie` option.

```
$ dig -version
DiG 9.9.5-9+deb8u19-Raspbian

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by dschaper** [comment]
Yeah, that's a very old version of Raspbian and not supported by anyone really. 

But it still would have failed the os_check and would have the same issue as now. `dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net` is the fix we are going to use.

**Comment by jfb-pihole** [comment]
Your OS is actually unsupported (by both Pi-hole and Debian).  You would be
best off updating that OS to a newer version.

**Comment by Pyrroc** [comment]
@dschaper using the `@ns1` solution also solves #3578.

**Comment by Pyrroc** [comment]
Might be overkill, but instead of pegging the dig to ns1, you might be better off to create ns.pi-hole.net which round-robins all of your name servers in case of server failure or, if more hopefully pihole becomes wildly successful, not inundate one server with all of the requests.

**Comment by dschaper** [comment]
If we ever get to the point where there's a load of noticeable size on `ns1` then we can look at things. It can handle on the order of 100's of thousands of queries a day.

**Comment by silentwolf15** [comment]
I hit this issue yesterday trying to use pihole -r to repair FTL not starting.  Here is my investigation and temporary resolution.

Looked through the scripts and tried the following... looks like it is a "fake" error because it can't pull down the txt file from versions.pi-hole.net
​
​
cat /etc/*release | grep PRETTY_NAME | cut -d '=' -f2- | tr -d '"'
Raspbian GNU/Linux 10 (buster)
cat /etc/*release | grep VERSION_ID | cut -d '=' -f2- | tr -d '"'
10
dig +short -t txt versions.pi-hole.net
;; connection timed out; no servers could be reached

#####################################
Adding 8.8.8.8 to /etc/resolv.conf fixed the problem and allowed me to proceed.... will take this out once i am done troubleshooting FTL not starting.
​
[i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
[i] Repair option selected
[✓] Disk space check
​
[✓] Checking apt-get for upgraded packages... up to date!
​
[i] Installer Dependency checks...
[✓] Checking for dhcpcd5
[✓] Checking for git
[✓] Checking for iproute2
[✓] Checking for whiptail
[✓] Checking for dnsutils
​
[✓] Supported OS detected
[i] SELinux not detected
[i] Performing reconfiguration, skipping download of local repos
[✓] Resetting repository within /etc/.pihole...

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
fresh install on raspios arm64
```
  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
  [✓] Disk space check

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✗] Unsupported OS detected: Debian GNU/Linux 10 (buster)
```

**Comment by dschaper** [comment]
`dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net`

**Comment by pax0707** [comment]
I got to this thread while failing to install on my secondary Pi.
This made me realize I blocked port 53 in the router's firewall....

**Comment by aaronburro** [comment]
Seeing this issue on a fresh install on Raspbian 9 on a Pi 3B+. Anything I should be looking for, or can I ignore it?
