### ISSUE TITLE
Pihole does not resolve DNS names/IPs from static DHCP leases

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/pi-hole#3600]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behavior:**

I have added several static DHCP leases. I expect that these static DHCP leases (reservations) are also respected in DNS requests, but they are not.

**Actual behavior:**

Static DHCP leases are not available in DNS requests

**Steps to reproduce:**

Add a static DHCP lease with a MAC, IP and host name.
Try to resolve the hostname using DNS from a client machine -> fails.

**Comment by jfb-pihole** [comment]
Please send us a debug token.

**Comment by schuettecarsten** [comment]
> Please send us a debug token.

The debug token is:
https://tricorder.pi-hole.net/c3u1nvnh7h

**Comment by arturhefczyc** [comment]
I confirm, the issue is present on my installation as well.

**Comment by dschaper** [comment]
Please use https://discourse.pi-hole.net for support on this. 

Thank you.

**Comment by Voteax** [comment]
Can also confirm this issue and long awaiting a fix. Why was it closed?
Is it really a Feature Request and not implemented atm?

**Comment by DroidFreak32** [comment]
Apologies for the spam above.
I did not realize github does this.

<details>
<summary> </summary>
/r/assholedesign
</details>

**Comment by mrubli** [comment]
I ended up using this script here to sync all static DHCP leases to the list of local DNS records:

```
#!/bin/sh

set -eu

static_lease_file="/etc/dnsmasq.d/04-pihole-static-dhcp.conf"
local_dns_file="/etc/pihole/custom.list"

echo "Static lease config file:     $static_lease_file"
echo "Local DNS record config file: $local_dns_file"

if [ ! -f "$static_lease_file" ]; then
    echo "ERROR: Static lease file not found: $static_lease_file"
    exit 1
fi

if [ -f "local_dns_file" ]; then
    echo "Backing up local DNS record file: $local_dns_file"
    cp "$local_dns_file" "${local_dns_file}.bak"
fi

echo "Synchronizing static DHCP leases to local DNS records ..."
awk -F, '{ print $2, $3 }' < "$static_lease_file" > "$local_dns_file"
echo "New local DNS records:"
cat "$local_dns_file"
```

Note that this will overwrite existing DNS records. Changing that is left as an exercise to the reader.

You could even get fancy and set this up with systemd, so that it happens automatically every time the static leases are updated.

**Comment by DroidFreak32** [comment]
I also have a fork that I try to maintain that supports static hostnames here:
https://github.com/DroidFreak32/pi-hole
https://github.com/DroidFreak32/AdminLTE

I try to keep it synced with upstream as much as possible.

**Comment by scinos** [comment]
@mrubli there is a typo in the script

Line `if [ -f "local_dns_file" ]; then` should be `if [ -f "$local_dns_file" ]; then`

**Comment by mrubli** [comment]
> @mrubli there is a typo in the script
> 
> Line `if [ -f "local_dns_file" ]; then` should be `if [ -f "$local_dns_file" ]; then`

Good find, thanks! I updated the script in my comment.

**Comment by DroidFreak32** [comment]
Modified the script in https://github.com/pi-hole/pi-hole/issues/3600#issuecomment-1407755291 to preserve existing DNS records:

```sh
#!/bin/sh

set -eu

static_lease_file="/etc/dnsmasq.d/04-pihole-static-dhcp.conf"
local_dns_file="/etc/pihole/custom.list"
tmp_file="/tmp/custom_hosts.list"

echo "Static lease config file:     $static_lease_file"
echo "Local DNS record config file: $local_dns_file"

if ! command -v sort >/dev/null 2>&1
then
    echo "ERROR: \`sort\` could not be found"
    exit 1
fi

if [ ! -f "$static_lease_file" ]; then
    echo "ERROR: Static lease file not found: $static_lease_file"
    exit 1
fi

if [ -f "$local_dns_file" ]; then
    echo "Backing up local DNS record file: $local_dns_file"
    cp "$local_dns_file" "${local_dns_file}.bak"
fi

echo "Synchronizing static DHCP leases to local DNS records ..."
cat "$local_dns_file" >> "$tmp_file"
awk -F, '{ print $2, $3 }' < "$static_lease_file" >> "$tmp_file"
echo "New local DNS records:"
sort -u "$tmp_file" | tee "$local_dns_file"
rm -v "$tmp_file"
```

Unfortunately wasn't able to keep up with the changes in my forks from https://github.com/pi-hole/pi-hole/issues/3600#issuecomment-1408080698 since the new upstream release, so this is good enough for now.
