### ISSUE TITLE
No salted password-hashes?

### ISSUE THREAD

**Issue by void-m4110c** [pi-hole/pi-hole#3602]
Hi, 

are the hashed passwords salted or not? I.e. does the same password result in the same hash when entered two times?

P.S.:
Dear pi-hole-god,

I do not ask about this or that hashing algorithm. I specifically ask if the hash is salted. So please don't give me links to 2 year old threads, in which my question is not even answered. 
Thanks

**Comment by yubiuser** [comment]
From my understanding: no.

Here is the relevant code:
https://github.com/pi-hole/pi-hole/blob/56cd7c4d59ceb629a2170cd1c8ab78ef26366019/advanced/Scripts/webpage.sh#L94

It was last modified (with regards to content) 3 years ago:
https://github.com/pi-hole/pi-hole/pull/1423

The PR introduced double hashing to avoid rainbow vulnerabilities.

**Comment by void-m4110c** [comment]
Thank you very much yubiuser.
