### ISSUE TITLE
Pihole Chronometer broken 

### ISSUE THREAD

**Issue by lastsamurai26** [pi-hole/pi-hole#3604]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5
---
**Expected behavior:**

If I call pihole -c, which actually looks like 
![2020-07-22 16 27 10](https://user-images.githubusercontent.com/3257844/88188760-91870000-cc38-11ea-8020-3a0105a528a7.jpg)

**Actual behavior:**

but now you can see this 
![Bildschirmfoto 2020-07-22 um 16 30 14](https://user-images.githubusercontent.com/3257844/88188869-b24f5580-cc38-11ea-9703-88abe42d6e5a.png)

**Steps to reproduce:**

The only way to do this is to update from version 5.0 to 5.1 after that I noticed that FTL is offline. 
but when i do service pihole-ftl status i get a message that the service is active 
![Bildschirmfoto 2020-07-22 um 16 32 36](https://user-images.githubusercontent.com/3257844/88189232-1f62eb00-cc39-11ea-993c-9d3c93e1fe5b.png)
![Bildschirmfoto 2020-07-22 um 16 32 44](https://user-images.githubusercontent.com/3257844/88189236-20941800-cc39-11ea-9097-5bab142ea3fe.png)

**Debug token 

https://tricorder.pi-hole.net/tgjck37bmd

**Comment by yubiuser** [comment]
Reported here, fix in pipeline
https://github.com/pi-hole/PADD/issues/112

Workaround: `echo 4711 | sudo tee /var/run/pihole-FTL.port`

**Comment by lastsamurai26** [comment]
thx
