### ISSUE TITLE
Automatic import of JSON configuration

### ISSUE THREAD

**Issue by fredericdepuydt** [pi-hole/pi-hole#3606]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behavior:**

At boot all .list files are being read in and added to the database, I expect the same behavior for the JSON configuration files

**Actual behavior:**

JSON files are ignored, hence no config is applied

**Steps to reproduce:**

Paste the JSON configuration files into /etc/pihole (location where the .list files go) and restart the system/container

**Troubleshooting undertaken, and/or other relevant information:**

Current fix is using the web interface to upload the configuration via Teleporter, but that requires a manual operation

**Additional questions**
- Can the teleporter be used from CLI?
- Does Pihole always check the .list files at boot and migrate them on changes? Or is there a flag that's being set after the first time the list files were read in and migrated?

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
