### ISSUE TITLE
Flushing network results in php implode() error

### ISSUE THREAD

**Issue by weiwang11** [pi-hole/pi-hole#3609]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behavior:**

`Flushing the network should result in a successful message`

**Actual behavior:**

`Flushing the network results in: PHP error (2): implode(): Invalid arguments passed in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:741`

**Steps to reproduce:**

`Go to settings page and flush network table`

**Troubleshooting undertaken, and/or other relevant information:**

`Code:`
```
                        // Flush network table
                        case "flusharp":
                                pihole_execute("arpflush quiet", $output);
                                $error = implode("<br>", $output);
                                if(strlen($error) == 0)
                                {
                                        $success .= "The network table has been flushed";
                                }
                                break;
```

**Comment by yubiuser** [comment]
Known, fix in pipeline:

https://github.com/pi-hole/AdminLTE/issues/1493

https://github.com/pi-hole/AdminLTE/issues/1493

**Comment by weiwang11** [comment]
Thanks I'll close this issue as I didn't realize it was opened in the AdminLTE repo.
