### ISSUE TITLE
Preventing logging of certain domains

### ISSUE THREAD

**Issue by hanshafner** [pi-hole/pi-hole#361]
Hi there,

is it possible to exclude some domains from top domains statistic on the web admin interface?

There are a couple of domains I'm not interested in (syncing services, iCloud, time servers etc...) that due to them being called very often show up at the top of the list.

Best
Hans
##

**Comment by jacobsalmela** [comment]
Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/prevent-logging-of-certain-domains/553) so this feature is votable.

**Comment by DL6ER** [comment]
Have a look at this pull request:
https://github.com/pi-hole/AdminLTE/pull/232

This will not prevent loging the domains but it will exclude them from being displayed in the results of the API and hence on the web UI.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/exclude-some-domains-from-top-domains-statistic-on-the-web-admin-interface/553/1
