### ISSUE TITLE
V5 - Takes huge time to update Adlist/Blocklist - Terminal Method

### ISSUE THREAD

**Issue by desmonk** [pi-hole/pi-hole#3612]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behavior:**

`Should take less than 10 minutes as it has been before prior to V5 of Pi-Hole. Even with using UI to update such a long list, it never took more than 5-7 minutes from V3 to V4. Now, have to use terminal. Although terminal itself takes close to 30 minutes now.`

**Actual behavior:**

`Adlist takes a really long time to load about 3 million on Pi Zero with Wi-Fi.`

**Steps to reproduce:**

`Install latest 5.1.1 of Pi-Hole version on Raspberry Pi OS (32-bit) Lite (headless) and load ad filters from https://firebog.net and https://github.com/jerryn70/GoodbyeAds. Will take close to 30 minutes to load all filters. Update using "pihole -g" instead of UI as the interface is slow. I also have implemented DNSCrypt to handle only IPv4. This setup has been like this since V3 with no issues.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Not possible due to security.`

**Troubleshooting undertaken, and/or other relevant information:**

`Tested on earlier versions and the new one a couple of time to validate the claim. Found out that even with terminal, updating ad lists takes a huge amount of time. I do understand that Pi Zero is not a powerful chip but this was never an issue before until recent switch to V5.1.1.`

> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment]
When you watch `pihole -g` which step seems take the longest? Downloading? Storing? Building tree? Swapping?

There should literally no difference between update via GUI and CLI as it invokes the same script.

**Comment by jfb-pihole** [comment]
```
Debug token provided by uploading pihole -d log:
Not possible due to security
```

You cannot upload the debug log, or don't want to share it with the developers?

**Comment by desmonk** [comment]
> 
> 
> When you watch `pihole -g` which step seems take the longest? Downloading? Storing? Building tree? Swapping?
> 
> There should literally no difference between update via GUI and CLI as it invokes the same script.

I skipped UI in V5 as I thought it got hung as in previous versions it didn't take more than 5-7 minutes after hitting Update in Blocklist. So switched to terminal. Overall V5 is slow irrespective of method to update gravity.




> 
> 
> ```
> Debug token provided by uploading pihole -d log:
> Not possible due to security
> ```
> 
> You cannot upload the debug log, or don't want to share it with the developers?
> 
> Please post the complete output of `pihole -g`

I surely can but this is not deployed on a home network. So can't.

**Comment by dschaper** [comment]
> So can't.

Okay, you'll need to use the Community Support then. https://discourse.pi-hole.net.

**Comment by yubiuser** [comment]
If you can't or are not willing to share more information, also on Community Support no one will be able to help you. You have to provide more information so that people can help you.

**Comment by desmonk** [comment]
I do understand that.

Since the Pi-Zero hardware remains the same, and not a single method of software implementation has been changed from my end from over 2-3 years now, I am fairly certain the new version has the issue.

I also know that a bug report is a valuable piece of info but in this case pulling it off might give away unintentional information. Hope you understand that this is not a home network deployment.

Anyways, thank you for the heads up and I am thankful for the hard work you guys put in to the project. Saves us from so many annoyance everyday. Much appreciated!

**Comment by dschaper** [comment]
> Hope you understand that this is not a home network deployment.

We'd be happy to provide paid consulting services for your endeavour.
