### ISSUE TITLE
Replacing Blacklist and Whitelist with Denylist and Allowlist

### ISSUE THREAD

**Issue by comrade-zoe** [pi-hole/pi-hole#3614]
In keeping with the progress in the rest of the IT/Software space (while this is relatively low priority) the words Whitelist and Blacklist should be replaced with (despite origin) the less offensive and more descriptive Allowlist and Denylist.

**Comment by ngvirus** [comment]
how's that progress? changing terminology used for dacedes, because there's 'black' and 'white' in sed terminology? I don't know a single person working in IT industry being ofended by these two words and i know a lot of people and a lot of them are people of color.

**Comment by ngvirus** [comment]
how's that progress? changing terminology used for dacedes, because there's 'black' and 'white' in sed terminology? I don't know a single person working in IT industry being offended by these two words and i know a lot of people and a lot of them are people of color.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/issues/1448
