### ISSUE TITLE
Unable To Use /23 CIDR in PiHole GUI Under Settings->DNS in 'Advanced DNS Settings, under 'Use Conditional forwarding'

### ISSUE THREAD

**Issue by gooch4130** [pi-hole/pi-hole#3621]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behavior:**

`{Under Settings->DNS in 'Advanced DNS Settings, under 'Use Conditional forwarding', I should be able to use a /23 as my CIDR. 
 I am able to manually edit the config file in /etc/pihole to set it to /23.}`

**Actual behavior:**

`{Under Settings->DNS in 'Advanced DNS Settings, under 'Use Conditional forwarding', I am not able to use a /23 as my CIDR.  It forces a /0 | /8 | /16 | /24.}`

**Steps to reproduce:**

`{In the GUI go to Settings->DNS in 'Advanced DNS Settings, under 'Use Conditional forwarding try to use a /23 CIDR}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{I edited /etc/pihole/setupVars.conf REV_SERVER_CIDR to be /23}`

**Comment by yubiuser** [comment]
This is a known limitation in the underlying `dnsmasq`.

See here for details https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975
