### ISSUE TITLE
API overTimeData10mins values inconsistent with Web UI

### ISSUE THREAD

**Issue by tomswartz07** [pi-hole/pi-hole#3624]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** `3`

---
**Expected behavior:**

Data from the overTimeData10mins endpoint should match the values for the web UI.

**Actual behavior:**

Data from the overTimeData10mins endpoint is inconsistent with the values from the web UI.
`ads_over_time` values match the respective time periods in the web UI, but it appears that the `domains_over_time` values are 'split' between previous and next time buckets.

It appears that the calculations for the domains_over_time are incorrect in the web UI, leading to a discrepancy between the API values and what is shown in the web UI.

e.g.

`overTimeData10mins`:
1595943300: 211
1595943900: 152

`Web UI`:
1595943300: 172
1595943900: 192

**Steps to reproduce:**

In the most simple reproduction case:
1. Open two side-by side browser tabs
2. In one tab, view the web UI with the `Total queries over last 24 hours` graph
3. In the other tab, navigate to the API endpoint for overTimeData10mins
4. Compare the values for each of the time stamps and observe that the count for `ads_over_time` is accurate, but the `domains_over_time` are not.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
 https://tricorder.pi-hole.net/nbrjpcuatu

**Troubleshooting undertaken, and/or other relevant information:**
I've manually compared the data presented by the web UI to the data from the API endpoint, and validated that the `ads_over_time` values do indeed display correctly on the web UI.

I've also attempted to compare the `domains_over_time` values to neighboring time slots (implying that there's an off-by-one issue), but this was unsuccessful. 

There does seem to be some correlation between the difference in numbers- as in, the previous value will be 'off by' a similar-but-not-exact amount of the current value.

**Comment by tomswartz07** [comment]
I realize that the web UI is in it's own repo, but since the issue may be with the code here too, I've raised the issue in both locations.

The relevant issue on the other project is here pi-hole/AdminLTE/issues/1534

**Comment by tomswartz07** [comment]
Indeed, technically.

Running:
- PiHole 5.2.1
- WebUI: 5.5.1
- FTL: 5.8.1

I realize this is a bit of semantics, now.
As the time defined in the API results indicate the center-point of the bar placement in the histogram.

Here's a bit more streamlined example (requires [jq](https://stedolan.github.io/jq/))

`curl "https://pihole.tswartz.net/admin/api.php?overTimeData10mins" | jq '.domains_over_time'`
Results in 
```
...
  "1628779500": 560,
  "1628780100": 433,
  "1628780700": 563,
  "1628781300": 786
```
Looking at `1628780100` in the web UI
```
date --date='@1628780100'
Thu Aug 12 10:55:00 AM EDT 2021
```
Given the time indicated by the API results, I would expect that the 'binning' of the results cover the 10 minute period beginning at 10:55am, instead of *centered at* 10:55am:
![image](https://user-images.githubusercontent.com/582862/129223807-954b6551-9899-45b6-b74e-22508549b742.png)
The DNS queries between 10:50-11am indeed equal 433- (394 permitted + 39 ads)

Working backwards from the Web UI to the API, this makes sense to have the time indicate the bar placement centerpoint, but perhaps this would be best to be documented explicitly in the API docs, though reviewing them recently it appears that the API may be deprecated in favor of the telnet api(?)

**Comment by yubiuser** [comment]
> API may be deprecated in favor of the telnet api(?)

There will be a completely re-written RESTful JSON API 
https://github.com/pi-hole/FTL/pull/659

Asking @DL6ER how the 'binning' of the data will work then

**Comment by DL6ER** [comment]
As you found, the data is centered in the interval. For exactly the reason you assumed

> makes sense to have the time indicate the bar placement centerpoint

because this is how the graph engine works. It always places the bars at the center plus-minus a given width. If we'd supply the beginning of the intervals here, we'd have to again post-process the intervals client-side so the generated graph would be correct.

----

> it appears that the API may be deprecated in favor of the telnet api(?)

The telnet API is the source of truth for the PHP API. It is the only interface between the web code and FTL. As mentioned b< @yubiuser, the API will be replaced by a newly written JSON API. However, the *content* served by the API will (for now) stay the same, i.e., we are not going to change the binning or the centering of the bins at this time.

**Comment by tomswartz07** [comment]
That's great info @DL6ER -- Thanks for confirmation.

I figured it was the case, but it took a bit more brain cycles than I think would be necessary if it were documented explicitly.

I'll be happy to contribute such documentation as the new JSON API moves forward.

Thanks!
