### ISSUE TITLE
Pihole updated to 5.1.1 and interface is not showing correctly

### ISSUE THREAD

**Issue by redsector72** [pi-hole/pi-hole#3626]
Hi there,
I've just updated my pihole and the web interface shows "Client activity over last 24 hours", "Query Types" and "Queries answered by" as greyed out, with a spinning thing inside.

Seems to be working.

**Comment by gottabeleGIT** [comment]
Screenshot?

**Comment by yubiuser** [comment]
Please clear your browser's cache.

**Comment by redsector72** [comment]
Thanks @yubiuser, it was a  caching issue.
