### ISSUE TITLE
[WebUI style flaw/Advice] 5.x Web ui status corner little bit crowded and dislocation

### ISSUE THREAD

**Issue by Alceatraz** [pi-hole/pi-hole#3627]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0, Not at all`

---

![TIM截图20200729134422](https://user-images.githubusercontent.com/8266702/88761524-e3340b00-d1a1-11ea-9392-bbf126368a3a.png)

Left is 4.x
Right is 5.x

**Comment by dschaper** [comment]
Flush your cache and cookies.
