### ISSUE TITLE
Error! --> Flush Network table - Pi-hole v5.1.1 Web Interface v5.1 FTL v5.1 

### ISSUE THREAD

**Issue by JeromeX** [pi-hole/pi-hole#3628]
![grafik](https://user-images.githubusercontent.com/15369779/88816911-35365a00-d1bd-11ea-8f19-8eb5be0f6e6e.png)
Error gets after update to the latest version

**Comment by yubiuser** [comment]
Thanks for the report. Duplicate, fix in pipeline
https://github.com/pi-hole/AdminLTE/issues/1493
