### ISSUE TITLE
pi-hole no longer logging to /var/log/pihole/

### ISSUE THREAD

**Issue by phrostbit** [pi-hole/pi-hole#3629]
PiHole is no longer logging to /var/log/pihole/ but I can see logs being generated when looking at them in the web GUI. I looked through the release notes and didn't see anything indicating if this was modified.

Recently updated to 
![image](https://user-images.githubusercontent.com/27188998/88832793-2aac9e00-d186-11ea-8ce2-0f5c608910b6.png)

![image](https://user-images.githubusercontent.com/27188998/88832675-0486fe00-d186-11ea-8b0f-67b2e4b3a4dc.png)

![image](https://user-images.githubusercontent.com/27188998/88832842-3dbf6e00-d186-11ea-9c5c-3371ae852ab6.png)

It appears the log files were moved back one directory. Was this intentional? 

![image](https://user-images.githubusercontent.com/27188998/88833099-9a228d80-d186-11ea-954b-13888a5596c0.png)

**Comment by dschaper** [comment]
Is there any space left?

**Comment by phrostbit** [comment]
Yes, over 30GB of space free.

**Comment by dschaper** [comment]
`df -h` please.

**Comment by dschaper** [comment]
Have you changed the user that `pihole-FTL` is running under? If it's still the `pihole` user then it won't be able to write to a file that has no write permissions for it.

**Comment by phrostbit** [comment]
No user or permissions were changed. I updated to the latest release last week and was looking around my SIEM today and noticed there were no events. Compared the file monitor for my SIEM that was set from previous version and the log files from pihole moved back one directory in comparison. I made no modifications other than the upgrade to either pihole or my SIEM.

![image](https://user-images.githubusercontent.com/27188998/88834781-2c2b9580-d189-11ea-89a2-aea04fda20c3.png)

**Comment by phrostbit** [comment]
I apologize. I'm unable to provide a debug token at this time. Working from home logs data I don't want to be seen.

**Comment by dschaper** [comment]
We haven't change logfile locations in years. It's always been files in the `/var/log` directory itself.

**Comment by dschaper** [comment]
You can still fill out the template, typically we autoclose issues that don't follow the basic directions.

**Comment by phrostbit** [comment]
Well, that's what mine started with from initial install and not something I did manually. That's even what the technical add-on provided on Splunkbase references for the logging directory in their most recent release which was May 2020. I was just making sure you guys were aware if something has changed. I can easily modify my SIEM configuration to reflect the change I experienced. If this is expected behavior, then please disregard.

**Comment by dschaper** [comment]
Nothing has changed with Pi-hole's logging locations in years. If some third-party integration is broken then it's the third-party integration that is broken.

**Comment by phrostbit** [comment]
I started with pihole version 5 and this was the directory it was logging to on install. The SIEM is not integrated with pihole, but simply monitoring the two log files being output by pihole. There is no interaction between the SIEM and pihole itself. Regardless, I'll modify my file monitor and close this issue.
