### ISSUE TITLE
Pihole going through VPN

### ISSUE THREAD

**Issue by jaimbo** [pi-hole/pi-hole#363]
During setup I told PiHole to use eth0 interface but it is using tun0 instead.

Reddit post https://www.reddit.com/r/pihole/comments/48zp16/pihole_and_vpn/

Results of ip route command:
 
0.0.0.0/1 via 10.179.1.5 dev tun0
default via 192.168.0.1 dev eth0  metric 202
10.179.1.1 via 10.179.1.5 dev tun0
10.179.1.5 dev tun0  proto kernel  scope link  src 10.179.1.6
109.201.154.160 via 192.168.0.1 dev eth0
128.0.0.0/1 via 10.179.1.5 dev tun0
192.168.0.0/24 dev eth0  proto kernel  scope link  src 192.168.0.8  metric 202
 
 
Results of route command:

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.179.1.5      128.0.0.0       UG    0      0        0 tun0
default         192.168.0.1     0.0.0.0         UG    202    0        0 eth0
10.179.1.1      10.179.1.5      255.255.255.255 UGH   0      0        0 tun0
10.179.1.5      *               255.255.255.255 UH    0      0        0 tun0
tsn109-201-154- 192.168.0.1     255.255.255.255 UGH   0      0        0 eth0
128.0.0.0       10.179.1.5      128.0.0.0       UG    0      0        0 tun0
192.168.0.0     *               255.255.255.0   U     202    0        0 eth0

**Comment by dschaper** [comment]
Thank you very much for this. I don't know if we are going to be able to get a solution that isn't particularly hacky, but we'll try.

**Comment by dschaper** [comment]
Still trying different solutions. So far just trying to do routing table updates but very unstable and a very dirty hack.

**Comment by dschaper** [comment]
#524 consolidation. Please see that issue for further description.
