### ISSUE TITLE
Set top box/decoder doesn’t find network to connect to

### ISSUE THREAD

**Issue by PietPetrus** [pi-hole/pi-hole#3630]
Problem:
Decoder software says it can’t connect to any networks.

Situation:
It has a valid static ip which it got from the pi-hole DHCP. (192.168.1.64)

I see queries popping up which are cached.

Even when the decoder is assigned to a separate group without any blacklists, the problem still occurred.

 ![image](https://user-images.githubusercontent.com/63313237/88840188-63776200-d1dc-11ea-8eb4-3f4954d5bcd0.png)

Bad fix:
Changing the cache size to 0 fixes the problem.

Question:
Is there any way to exclude some queries from getting cached? This would be the most straightforward solution I believe.
I have done an extensive search for a possible solution.

Besides that:
Thanks for creating such a wonderful piece of software! It works great for all other devices in my network.

**Comment by dschaper** [comment]
I'm sorry, I don't understand the issue. 

You don't want decoder.lan to have a static IP address?

**Comment by PietPetrus** [comment]
The decoder must have a specific IP in the range of 192.168.1.64 - ... (the end of the pool I don’t know for the moment). It is listed in the static IP address list within pi-hole.

The DHCP is configured in pi-hole to hand out IP addresses in the range 192.168.1.19-192.168.1.63.

When booting from ‘deep sleep mode’ (which is the off state) the decoder queries once for localhost and localhost.lan . The device clearly has an IP and can query.

These queries get forwarded and the device boots.

But the next time the decoder wakes from a deep sleep state, these queries are answered from cache and the device won’t boot. (That’s what I believe is the culprit)

When I disable DNS cacheing completely by setting an absurdly low amount, the problem does not persist.

I’m still not 100% sure it is because of the querying but I do not know where to start to debug this problem.

**Comment by dschaper** [comment]
I still don't follow but `localhost` is the human readable name for `127.0.0.1`, it shouldn't ever be forwarded off the device requesting. And certainly shouldn't ever be seen on Pi-hole's display as a query received from a client.

**Comment by PietPetrus** [comment]
I was wrong.
Apparently the router supplied by the ISP sets up a VLAN connection between the ISP and decoder.

By turning off the DHCP in pihole and on in the router settings, the decoder connects immediately.

Is this a known problem?

Sorry for the confusion!

**Comment by technicalpyro** [comment]
this is likely a bandwidth monitoring thing they do or a security thing it would not be an error in pi-hole software just a situation of ISP needing certain things to work in certain ways
