### ISSUE TITLE
installation failure on Raspberry-pi

### ISSUE THREAD

**Issue by MarkoRollo** [pi-hole/pi-hole#3633]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

This may be in a pull request "Report and exit if dig supportedOS returns nothing #3620".  If so, please delete this issue.  Sorry for the overload if it does....

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behavior:**

`Installation of pi-hole, or a note about the OS compatibility`

**Script drops out after Dependency checks**

```
pi@raspberrypi:~/Pi-hole/automated install $ sudo bash basic-install.sh

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [✓] Disk space check

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

pi@raspberrypi:~/Pi-hole/automated install $ 
```

**Steps to reproduce:**

I installed a fresh image from https://www.raspberrypi.org/downloads/ after it failed the first time on a new pi 4b from Canakit.
Still drops off.  I updated installed packages to insure dependencies were met.  I updated the OS, to make sure it was okay.  

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

with this failure, the debugging logs were never created at this point of the script.

**Troubleshooting undertaken, and/or other relevant information:**

Troubleshot the script, and found that it was dropping out at the "os_check".  So I am still new to scripting...been a long time....  I did not totally understand how to set the environment variable.  So, I just commented the "os_check" in the main section to skip that, and the script ran and installed the pi-hole.  So, something was kicking the script out in the os_check section.  Maybe a newer version of Raspbian that is not in the script database call?`

from my OS info:
```
pi@raspberrypi:~/Pi-hole/automated install $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
************************************

Thank you for your support and I am excited to get this running on my home network.  If I can only get the ISP to give me access to the router!  

Cheers,
Mark

**Comment by dschaper** [comment]
This isn't related to the OS check, this seems to be a failure at the `apt` packages installation stage. 

Can you run `curl -sSL https://install.pi-hole.net | sudo bash -x` and post the last few lines displayed?

**Comment by yubiuser** [comment]
>++ dig +short -t txt versions.pi-hole.net

This is the place it failed. Please post the output of `dig -t txt versions.pi-hole.net`

**Comment by MarkoRollo** [comment]
pi@raspberrypi:~ $ dig -t txt versions.pi-hole.net

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> -t txt versions.pi-hole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 56121
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 200a820b744a7e5c (echoed)
;; QUESTION SECTION:
;versions.pi-hole.net.		IN	TXT

;; Query time: 44 msec
;; SERVER: 192.168.1.101#53(192.168.1.101)
;; WHEN: Thu Jul 30 10:55:09 MDT 2020
;; MSG SIZE  rcvd: 61

pi@raspberrypi:~ $ 
*************************************************************
interesting..... I did that a while ago, and it returned nothing.  so something has changed....
*************************************************************
pi@raspberrypi:~ $ dig +short -t txt versions.pi-hole.net
pi@raspberrypi:~ $ 

****************************************************************************
Oh, the +short was in the script, so that is what I tried....

Thanks for the support!  Let me know what else I can do.  This little thing is running on my desktop right next to me....

Cheers,
Mark

**Comment by MarkoRollo** [comment]
Now I get:
***********************************************************
pi@raspberrypi:~ $ dig +short -t txt versions.pi-hole.net
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"
pi@raspberrypi:~ $ 
**************************************************
so it looks like things are better now!

**Comment by dschaper** [comment]
AD DNS server?

**Comment by dschaper** [comment]
Yeah, the FORMERR gives it away. We have a fix already done and will be in the next release.

**Comment by yubiuser** [comment]
https://kevinlocke.name/bits/2017/01/20/formerr-from-microsoft-dns-server-for-dig/

**Comment by MarkoRollo** [comment]
Thanks for looking into this....Sorry if it was already in the que....  Please close if that is appropriate....
Cheers!
Mark
