### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by slynobody** [pi-hole/pi-hole#3637]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behavior:**

`{Suggestions for a better user experience: 
(1) under 'domain managment' let users *group entries to groups* (like 'facebook', 'whatsapp', 'messengers') through simple '+' button (open group) and through pushing entries there; 
(2) let this groups be *shared *
     (a) through download-option 
     (b) through a 'marketplace' somewhere, run by the community ('share'-button in 'domain managment'); 
(3) let users give *redirect-rules* for entries (f.a. 'google' is redirected to 'startpage', 'amazon' is redirected to the local bookstores webpresence
(4) install a simple *api* to install and control pihole as a module f.e. in cars, smart-tvs etc. }`

**Actual behavior:**

`{not implemented}`

**Steps to reproduce:**

`{not implemented}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{does not compute}`

**Troubleshooting undertaken, and/or other relevant information:**

`{thinking}`

**Comment by yubiuser** [comment]
Thanks for your suggestion. But github is the wrong place for feature requests. Please re-submit to https://discourse.pi-hole.net/c/feature-requests/8:

Additionally, I would like to ask you too
1) Split the different requests, as it is easier to follow the implementation of a single request than 4 at a time
2) Search through the FR section on discourse if similar FR already exist (and I know, for some they do), and vote for them instead adding duplicates.

Thanks.
