### ISSUE TITLE
Conditional Forwarding CIDR Misalignment

### ISSUE THREAD

**Issue by baqwas** [pi-hole/pi-hole#3640]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behavior:**

`The CIDR setting in Conditional Forwarding should align with the DHCP lease allocation CIDR setting`

**Actual behavior:**

`The CIDR setting is aligned to /8, /16 or /24 only`

**Steps to reproduce:**

`Set DHCP lease allocation pool with CIDR /23
Define the same subnet in the Advanced DNS -> Conditional Forwarding page
in the field Local network in CIDR notation
An error message is flagged and the CIDR is changed to /24 `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**
Don't know whether this override MUST occur but a _dummy like myself_ doesn't understand how to specify the same subnet as that being used in the DHCP lease pool.

P.S. I do need more than /24 clients in the subnet.

**Comment by jfb-pihole** [comment]
> The CIDR setting is aligned to /8, /16 or /24 only

This is a limitation of dnsmasq.  The Pi-hole developers have submitted a change request to dnsmasq, but no action has been taken at the dnsmasq end.

**Comment by baqwas** [comment]
Thx for the quick response. Rgds.
