### ISSUE TITLE
www.fedramp.gov not resolving

### ISSUE THREAD

**Issue by deepgray** [pi-hole/pi-hole#3644]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
not familiar
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behavior:**
resolve fedramp.gov as other .gov sites have no problems.
`{A detailed description of what you expect to see}`

**Actual behavior:**
DNS resolution times out. other .gov sites work fine. fedramp.gov has no problem outside of pi-hole.
`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`
standard install. then try connecting to https://www.fedramp.gov and https://fedramp.gov
**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

pihole -update, then reboot. verified it wasn't in the black list.

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment]
> Debug token provided by uploading pihole -d log:

{Alphanumeric token}

**Comment by jfb-pihole** [comment]
From the Pi terminal, what is the output of `nslookup www.fedramp.gov`

**Comment by deepgray** [comment]
***********************************
***********************************
[✓] Your debug token is: https://tricorder.pi-hole.net/dg9thl5bsm
***********************************
***********************************

**Comment by dschaper** [comment]
Seems like OpenDNS is broken. Does it work with another upstream?

**Comment by dschaper** [comment]
```plain
dschaper@MARINER-10:~$ dig fedramp.gov @208.67.222.222

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> fedramp.gov @208.67.222.222
;; global options: +cmd
;; connection timed out; no servers could be reached
dschaper@MARINER-10:~$ dig pi-hole.net @208.67.222.222

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> pi-hole.net @208.67.222.222
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22082
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi-hole.net.                   IN      A

;; ANSWER SECTION:
pi-hole.net.            3600    IN      A       192.124.249.118

;; Query time: 123 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Mon Aug 03 13:20:56 PDT 2020
;; MSG SIZE  rcvd: 56
```

**Comment by deepgray** [comment]
seems to be functional now...you an close the ticket.
