### ISSUE TITLE
24h stats empty

### ISSUE THREAD

**Issue by elhennig** [pi-hole/pi-hole#3647]
I found this solution in an old ticket (see #1951)
With a recent version this problem occurs again on my Raspberry Pi running Buster.
Pi-Hole is up-to-date:
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

Pi-hole v5.1.1 Web Interface v5.1 FTL v5.1 

See old post:
Check in this pihole/dnsmasq config file: `/etc/dnsmasq.d/01-pihole.conf` for the line:
`log-queries=extra`. Mine only said `log-queries`. Updated the line to `log-queries=extra`. Run `sudo service dnsmasq restart` and it should be populating again.

_Originally posted by @glassbase in https://github.com/pi-hole/pi-hole/issues/1951#issuecomment-367201328_

**Comment by dschaper** [comment]
Modifying `01-pihole.conf` is not advised. The header notes the file will be overwritten and the line you modified is intended to be `log-queries` only.

**Comment by dschaper** [comment]
If you are using `service dnsmasq restart` then you're not using Pi-hole. The template asks for specific information and ignoring it will result in the issue being closed.

**Comment by elhennig** [comment]
I did not write that I use `service dnsmasq restart`. I just cited the old ticket and the behavior that the 24h stats are not showing up is still there, when I do not use `log-queries=extra` in `/etc/dnsmasq.d/01-pihole.conf`
I am aware that this is not a solution, but a work around to be able to see the 24 stats in the dashboard. 
What would you propose to solve this instead of just closing this ticket?

**Comment by elhennig** [comment]
BTW, I restart the DNS masq service in the Pi-Hole webinterface ;-)

**Comment by elhennig** [comment]
Another comment on you answer: There was no template to fill, obviously because I cited the old ticket. So what infos do you need?
