### ISSUE TITLE
5.1 broken blocklist control / dashboard etc

### ISSUE THREAD

**Issue by nPHYN1T3** [pi-hole/pi-hole#3649]
### Versions
  Current Pi-hole version is v5.1.1.
  Current AdminLTE version is v5.1.
  Current FTL version is v5.1.

### Platform
Linux raspberrypi 5.4.51+ #1327 Thu Jul 23 10:53:06 BST 2020 armv6l GNU/Linux
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

### Expected behavior ### Actual behavior / bug
I expect to be able to see/add/delete block lists. Now there are only "adlists" which could just be a nomenclature change however nothing is shown. Adding new items to the "adlist" seems to work and can be found as /etc/pihole/list.X.domain but nothing shows in the web-gui.

### Steps to reproduce
Go to web-admin, note UI changes, try to find block lists...try adlists instead, add to adlists, says successfull, still nothing is listed below in the "List of configured adlists"

## Debug Token
https://tricorder.pi-hole.net/wijy5b5c6v

### Additional context
Going to the dashboard total queries over last 24hr works, query types, answered by, client activity just show spinning arrows. I've rebooted a few times, updated gravity, fished around...disabled/re-enabled the default group...no change.

**Comment by yubiuser** [comment]
1. Blocklist were renamed to Adlists
2. Clear your browser's cache

**Comment by nPHYN1T3** [comment]
How...droll lol. Worked! I despise browser cache for this reason but most won't allow you to set to disabled anymore unless you open the stupid dev tools!
