### ISSUE TITLE
Pi-hole Admin Console - 500 Internal Server Error on api.php

### ISSUE THREAD

**Issue by tkahn** [pi-hole/pi-hole#365]
##### Expected Behaviour:

I expected the Admin Console to show graphs on the number of ads that Pi-hole has blocked.
##### Actual Behaviour:

The admin page itself loads just fine, but no data is loaded via AJAX from the API (api.php). The server returns a 500 error for all such requests.

`http://192.168.1.82/admin/api.php?summary 500 (Internal Server Error)
http://192.168.1.82/admin/api.php?getQuerySources 500 (Internal Server Error)
http://192.168.1.82/admin/api.php?getQueryTypes 500 (Internal Server Error)
http://192.168.1.82/admin/api.php?overTimeData 500 (Internal Server Error)
http://192.168.1.82/admin/api.php?summaryRaw&topItems 500 (Internal Server Error)
http://192.168.1.82/admin/api.php?getForwardDestinations 500 (Internal Server Error)`
##### Steps to reproduce this issue:
1. Run the current installer on an existing (older) install of Pi-hole.
2. Go to the admin page: http://192.168.X.X/admin/index.php
3. Open the web console and there you'll se jQuery trying to load data from api.php and get the 500 Internal Server Error response.
##

**Comment by Mcat12** [comment]
When was the last time you installed Pi-hole? (Do you know the version number?) If there is the file `/error.log`, can you run `cat /error.log` and paste the output here?

**Comment by tkahn** [comment]
I found an error log in "var/log/lighttpd" and in the log, around the time when I experienced this error the log is full of messages with the same error:

`2016-03-05 20:32:50: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24 bytes) in /var/www/html/admin/data.php on line 149`

...but when I access the page now, I get nice looking graphs of all the statistics. So for me, the problem seems to be solved just by waiting a few days.

**Comment by Mcat12** [comment]
It might be that the log file became too big for the methods used in the php. The log is cleared each day, so it might happen again. There are some fixes for this coming sometime.

**Comment by Roemy** [comment]
@tkahn when opening the adminLTE page (Query Log) php will parse the file /var/log/pihole.log to read it's contents. Unfortunately when the file gets bigger and bigger php needs to work harder to open the log file, meaning the script needs more resources which in this case it's memory.

There is a simple way to deal with this issue by editing the following file: **/etc/php5/cgi/php.ini**

Find the following line
`memory_limit = 128M`

Change the value to
`memory_limit = 512M`

If you think 512MB is to much you can try 256MB. ( _I just wanted to be on the safe side_ )

Be aware that people aren't suggesting this solution cause of a possible leak in the script is causing this memory exhausting. Reason why this is "valid" now is because of the pihole.log is being parsed which loads up more memory while the pihole.log file gets bigger. For what I know is that they are busy with a database solution which will decrease alot of load time on your adminLTE page.

There is also a cron running every day to flush out the pihole.log file.

File: **/etc/cron.d/pihole**
```
# Pi-hole: Flush the log daily at 11:58 so it doesn't get out of control
#          Stats will be viewable in the Web interface thanks to the cron job above
58 23   * * *   root    /usr/local/bin/piholeLogFlush.sh
```

**Comment by jacobsalmela** [comment]
@tkahn is this still happening with the latest versions of Pi-hole and the Web interface?

**Comment by homeontherocks** [comment]
I had this error as well.  Updated to the new version with same problem.  However, flushing the pihole.log with /usr/local/bin/pihole -f (which flushes the pihole.log file) fixed the problem.  Will report back here if the problem recurs in the future.

**Comment by Mcat12** [comment]
Any updates?

**Comment by homeontherocks** [comment]
No recurrence at this time.  But in the past, it has taken days-weeks to recur.

**Comment by xd1936** [comment]
I'm having this issue as well. I have my server on a 512MB DigitalOcean instance. Several bots with roaming IP addresses like to flood my server with repetitive requests, quickly filling up the log. Bumping up my php.ini to 256M still isn't enough to stop the 500 errors from happening.

```
Failed to parse SourceMap: http://my_host_ip/admin/bootstrap/css/bootstrap.min.css.map
jquery.min.js:4 GET http://my_host_ip/admin/api.php?overTimeData 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateQueriesOverTime @ (index):483(anonymous function) @ (index):377j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
jquery.min.js:4 GET http://my_host_ip/admin/api.php?summary 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateSummaryData @ (index):452(anonymous function) @ (index):375j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
jquery.min.js:4 GET http://my_host_ip/admin/api.php?getQueryTypes 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateQueryTypes @ (index):506(anonymous function) @ (index):379j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
jquery.min.js:4 GET http://my_host_ip/admin/api.php?summaryRaw&getQuerySources 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateTopClientsChart @ (index):493(anonymous function) @ (index):381j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
jquery.min.js:4 GET http://my_host_ip/admin/api.php?getForwardDestinations 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateForwardDestinations @ (index):522(anonymous function) @ (index):383j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
jquery.min.js:4 GET http://my_host_ip/admin/api.php?summaryRaw&topItems 500 (Internal Server Error)
```

**Comment by thomaslove** [comment]
I had a similar issue but mine was based around the fact I was using php5.5 which comes with Ubuntu 14.04 and not php5.6

**Comment by jacobsalmela** [comment]
@Mcat12 do you know the status of this?  Seems stale.

**Comment by Mcat12** [comment]
It's still a problem, but less so now than in the past with the php optimizations. It's not going to be fixable until we get the database stuff, because currently we have to load the whole log on every request.

**Comment by jacobsalmela** [comment]
OK thanks!

**Comment by DL6ER** [comment]
Will be fixed once and for all when the new FTL engine is running on Your Pi

**Comment by dschaper** [comment]
Resolved with FTL.
