### ISSUE TITLE
lighttpd won't start so can't access admin interface

### ISSUE THREAD

**Issue by therecker** [pi-hole/pi-hole#3651]
### Versions

- Pi-hole:  5.1.1
- AdminLTE:  5.1
- FTL:  5.1

### Platform

- OS and version:  Ubuntu 20.04.1 LTS

- Platform:  VM esxi

### Expected behavior

A few weeks ago I could access the admin interface. At some point between then and now some updates were done and now I cannot access the admin web gui interface. I have only ever made one change to the lighttpd.conf file and that is to change the port to 8383 as I run appache on this server to host webpages. PiHole has worked flawlessly up until now.

### Actual behavior / bug

I get a page cannot load error in all browsers I try this from. And the lighttpd will not load as it states the following error. I even tried running pihole -r and it just stops processing at the restarting of the lighttpd daemon.

Restarting lighttpd (via systemctl): lighttpd.serviceJob for lighttpd.service failed because the control process exited with error code.
See "systemctl status lighttpd.service" and "journalctl -xe" for details.

## Debug Token

- URL:  Couldn't do this!

[✓] ** FINISHED DEBUGGING! **

    * The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
    * For more information, see: https://pi-hole.net/2016/11/07/crack-our-medical-tricorder-win-a-raspberry-pi-3/
    * If available, we'll use openssl to upload the log, otherwise it will fall back to netcat.

[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, falling back to netcat for transmission.
[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log

### Screenshots

[✓] ** FINISHED DEBUGGING! **

    * The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
    * For more information, see: https://pi-hole.net/2016/11/07/crack-our-medical-tricorder-win-a-raspberry-pi-3/
    * If available, we'll use openssl to upload the log, otherwise it will fall back to netcat.

### Additional context

_Add any other context about the problem here._

**Comment by pastorhudson** [comment]
The same happened to me. I had to edit the lighttpd.conf file to change the port back to my preferred port number.

**Comment by dschaper** [comment]
There's a very very large warning on `/etc/lighttpd/lighttpd.conf` that says:

```plain
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################
```

**Comment by pastorhudson** [comment]
> There's a very very large warning on `/etc/lighttpd/lighttpd.conf` that says:
> 
> ```
> ###############################################################################
> #     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
> # ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
> #                                                                             #
> #              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
> #                         /etc/lighttpd/external.conf                         #
> ###############################################################################
> ```

And yet it’s not clear at the time we update. Perhaps placing this warning in the update command would be better. Or why not check for conf file changes during update?

**Comment by dschaper** [comment]
How could it be any clearer? You edited the file at some point, it's a huge warning in the file you manually edited.

**Comment by therecker** [comment]
I'm well aware of the warning and I did modify the external.conf file with my port requirement. The lighttpd STILL won't start after making those changes. Some updates were done in Ubuntu and all of a sudden something that was working for months just stopped. I no longer can get to the admin page for PiHole because lighttpd will not start.

**Comment by pastorhudson** [comment]
> How could it be any clearer? You edited the file at some point, it's a huge warning in the file you manually edited.

I’m not trying to argue or be aggressive. I’m just saying I edited that file months ago and have edited many files on many servers since then. I don’t remember seeing a warning. I’m sure it was there. I just forgot. System design that relies on users remembering stuff is precarious in my experience. It  appears this is an issue others have too. I’ll remember next time when my admin interface doesn’t start.

Perhaps this issue will come up when another forgetful human finds their pi-hole inoperable.

**Comment by dschaper** [comment]
This configuration has been the same for a few years, nothing new has changed it.

Run

`sudo systemctl status --full --no-pager lighttpd.service` for the full output.

I'm going to guess that you changed the port in `external.conf` and port changes do not work in `external.conf`. `lighttpd` is probably trying to still use port 80. My suggestion is to move the other web daemon to another port or move Pi-hole to another server/device.

**Comment by pastorhudson** [comment]
> I'm well aware of the warning and I did modify the external.conf file with my port requirement. The lighttpd STILL won't start after making those changes. Some updates were done in Ubuntu and all of a sudden something that was working for months just stopped. I no longer can get to the admin page for PiHole because lighttpd will not start.

You have to edit the port in: /etc/lighttpd/lighttpd.conf

**Comment by dschaper** [comment]
> System design that relies on users remembering stuff is precarious in my experience.

That may be, but Pi-hole is a DNS server. That's a vital necessity for your network to function. You need to remember that you changed things against the advice and warnings of the people that wrote Pi-hole.

**Comment by pastorhudson** [comment]
> > System design that relies on users remembering stuff is precarious in my experience.
> 
> That may be, but Pi-hole is a DNS server. That's a vital necessity for your network to function. You need to remember that you changed things against the advice and warnings of the people that wrote Pi-hole.

Fair enough. Thank you for your work on this awesome project.

**Comment by therecker** [comment]
> This configuration has been the same for a few years, nothing new has changed it.
> 
> Run
> 
> `sudo systemctl status --full --no-pager lighttpd.service` for the full output.
> 
> I'm going to guess that you changed the port in `external.conf` and port changes do not work in `external.conf`. `lighttpd` is probably trying to still use port 80. My suggestion is to move the other web daemon to another port or move Pi-hole to another server/device.

Here is the result of the command. The change of the port in external.conf and lighttpd.conf worked just fine for several months through numerous reboots so I think you saying it doesn't work is inaccurate.

● lighttpd.service - Lighttpd Daemon
     Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-08-04 12:14:40 EDT; 6 days ago

Aug 04 12:14:40 webpihole systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Aug 04 12:14:40 webpihole systemd[1]: Stopped Lighttpd Daemon.
Aug 04 12:14:40 webpihole systemd[1]: lighttpd.service: Start request repeated too quickly.
Aug 04 12:14:40 webpihole systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Aug 04 12:14:40 webpihole systemd[1]: Failed to start Lighttpd Daemon.

**Comment by dschaper** [comment]
Okay, what exactly did you do. You've said you only changed `lighttpd.conf` and then you said you changed `external.conf` and now you say you've changed `lighttpd.conf` and `external.conf`. 

There's other problems with your system if `pihole -d` does not work as `pihole -d` doesn't rely on any dependencies.

**Comment by therecker** [comment]
Just an FYI I took your advice and changed apache2 to use port 8083 and made all necessary firewall  rule changes and virtual host changes. My websites are working fine with that change. I then changed both the lighttpd.conf and external.conf files back to port 80 and I am still experiencing the same issue. So as I stated before something isn't quite right. So it may be some kind of bug in some update that was done in Ubuntu 20.04 recently that causes an issue with lighttpd.

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using `nginx` instead of `lighttpd`, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by dschaper** [comment]
You shouldn't have port directives in multiple configuration files.

Run `sudo lighttpd -tt -f /etc/lighttpd/lighttpd.conf` and then open an issue at the link in the post directly above this one.
