### ISSUE TITLE
Default route 169.254.140.137 pihole

### ISSUE THREAD

**Issue by Allard-Chris** [pi-hole/pi-hole#3656]
### Versions

- Pi-hole:  v5.1.1
- AdminLTE: v5.1 
- FTL:  v5.1

### Platform

- OS and version:  raspbian 10 buster

- Platform:  Raspberry Pi 3+

### Expected behavior

I done a fresh install of raspbian 10, and do the same well for the pihole with the curl command.
The pihole is use as a DHCP server, my ISP box (Orange) doesn't let me change the DNS ip inside DHCP configuration, so i disable the DHCP server inside it.

All is works but after some hours, can't resolve any DNS request. The problem seems to be the default route for the raspberry pi, for eth0.

command: ip route, result:
default dev eth0 scope link src 169.254.140.137 metric 202 
169.254.0.0/16 dev eth0 scope link src 169.254.140.137 metric 202 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.2

As if the raspberry pi want to get an ip from my isp box but doesn't get one so just set the default 169.254.*.*

If i changed the default route, all is okay :
default via 192.168.1.1 dev eth0 
169.254.0.0/16 dev eth0 scope link src 169.254.140.137 metric 202 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.2
dig www.google.fr works !

That weird because the dhcpcd.conf is set to manual : cat /etc/dhcpcd.conf
# fallback to static profile on eth0
#interface eth0
#fallback static_eth0
interface eth0
        static ip_address=192.168.1.2/24
        static routers=192.168.1.1
        static domain_name_servers=208.67.222.222 208.67.220.220

Does any one get this error to ?

Thanks in advance.

Regards, Chris

## Debug Token

- URL:  https://tricorder.pi-hole.net/35v45cn0zw

**Comment by dschaper** [comment]
You're getting APIPA addresses (169.254.0.0/16) which means that there is no DHCP server involved. https://study-ccna.com/apipa-automatic-private-ip-addressing/

I don't think this is related to Pi-hole, it's something that happens on the network with the OS. You'll get better answers to your configuration questions at https://discourse.pi-hole.net.

**Comment by Allard-Chris** [comment]
Thanks for your answer.

What made me doubt is that raspbian and pihole are fresh installed without any modification, above all in network side.
But it's the joy of computing =).

The best for you and the whole team !

Regards, Chris.
