### ISSUE TITLE
Invalid subnet /17

### ISSUE THREAD

**Issue by andi448** [pi-hole/pi-hole#3657]
### Versions

- Pi-hole:  v5.1.1
- AdminLTE:  5.1
- FTL:  5.1

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi 4

### Expected behavior

I want to set my local network to 192.168.0.0/17 because that's what I'm using.

### Actual behavior / bug

Pi-hole forces me to use only /8, /16, /24 or /32.

### Steps to reproduce

1. Go to settings
2. Click on DNS
3. Scroll down to conditional forwarding
4. Set local network in CIDR notation to 192.168.0.0/17
5. See that error

### Screenshots

![Pi-hole](https://user-images.githubusercontent.com/37498627/89453457-959a3e00-d75f-11ea-9ba3-08b29484544a.png)

**Comment by yubiuser** [comment]
That's an issue with the underlying dnsmasq and must be fixed upstream.

https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975

Pihole's developers submitted patches to dnsmasq to overcame this, but changes haven't made their way into the code.
