### ISSUE TITLE
Pi-hole admin page constantly reverting to Celcius after selecting Farenheight for temp readings

### ISSUE THREAD

**Issue by lesliemires** [pi-hole/pi-hole#3660]
Pi-hole v5.1.1 Web Interface v5.1 FTL v5.1 

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
Have you cleared the cache on that browser and reloaded the admin label?

**Comment by yubiuser** [comment]
@lesliemires 

Does the issue still persist?
