### ISSUE TITLE
pihole chronometer does not display temperature after install

### ISSUE THREAD

**Issue by scboucher** [pi-hole/pi-hole#3664]
### Versions

 -  Pi-hole version is v5.1.1 (Latest: v5.1.1)
  - AdminLTE version is v5.1 (Latest: v5.1)
  - FTL version is v5.1 (Latest: v5.1)

### Platform

- OS and version:  
 - Debian 10.4

- Platform:  Raspberry Pi

### Expected behavior
pihole -c should display the temperature 

### Actual behavior / bug
After a fresh install without change the temperature unit, the command `pihole -c` do not display the temperature

### Steps to reproduce

ssh into the device
run pihole -c
the temperature should not be displayed

## Debug Token

- URL:  

### Screenshots
![pihole_bug](https://user-images.githubusercontent.com/7501609/89738181-b9ea6900-da44-11ea-84ea-66f9f744c36a.jpg)
![pihole_without_bug](https://user-images.githubusercontent.com/7501609/89738188-c79fee80-da44-11ea-8792-cecb178691d3.jpg)

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
I'll be honest, the chronometer script hasn't been touched in years and now that PADD is part of Pi-hole, I doubt there will be any further updates or maintenance of the chronometer script.

I see the PR that you opened but I'm not sure how changing the case of the letter `c` resolves this issue?

**Comment by jfb-pihole** [comment]
The two screen shots show different results. What is the relationship between the two screen captures?  One before reboot, etc?

**Comment by dschaper** [comment]
By default we use Kelvin temps (yeah, my fault/idea). The script is supposed to see that TEMPERATUREUNIT is unset in setupVars and display as Celsius. But there's a bug in the script that sets the default to `c` while the display checks for `C`. 

So either you set TEMPERATUREUNIT to `C` in the config or we fix the chronometer to work as intended.

**Comment by scboucher** [comment]
> 
> 
> The two screen shots show different results. What is the relationship between the two screen captures? One before reboot, etc?

Sorry about that's the result when the script output the expected result from the PR
