### ISSUE TITLE
Changing theme calls exec() when it should call pihole_execute()

### ISSUE THREAD

**Issue by thedjnK** [pi-hole/pi-hole#3666]
### Versions

- Pi-hole:  5.1.1
- FTL:  5.1

### Platform

- OS and version: Arch linux arm 64-bit
- Platform: Raspberry pi 4

### Expected behavior

Changing theme from the web GUI should work

### Actual behavior / bug

It does not work, this error is reported:
   Aug 09 20:01:32 System-RPi sudo[1541078]:     http : command not allowed ; TTY=unknown ; PWD=/srv/http/pihole/admin ; USER=root ; COMMAND=pihole -a theme default-light

### Steps to reproduce

1. Go to web UI
2. Go to settings
3. Go to theme
4. Change theme to the one no selected
5. Accept it
6. Go to main pihole page
7. Refresh
8. Theme will have reverted

## Fix

Edit the savesettings.php file and replace:

    exec('sudo pihole -a theme '.$_POST["webtheme"]);

With

    pihole_execute('-a theme '.$_POST["webtheme"]);

After doing this, no error is emitted and the setting is successfully saved.

**Comment by yubiuser** [comment]
In the end, `pihole_execute` also just calls `sudo pihole -a theme '.$_POST["webtheme"]`

https://github.com/pi-hole/AdminLTE/blob/d8d3f316061ba60e0b1dfc6a11f6e917380aca5f/scripts/pi-hole/php/func.php#L71

I don't see how this might have solved you problem. Maybe it was a browser cache issue?

Nevertheless, it might be a good idea to execute the theme changer through `pihole_execute`.

**Comment by thedjnK** [comment]
Not a browser cache issue, after making the change it all works and there's no errors, maybe to do with the sudoers file
