### ISSUE TITLE
Pi-hole Core v5.1.2: List download failed: no cached list available

### ISSUE THREAD

**Issue by somera** [pi-hole/pi-hole#3668]
### Versions

- Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE version is v5.1.1 (Latest: v5.1.1)
- FTL version is v5.2 (Latest: v5.2)

### Actual behavior / bug

pihole -up

...

  [i] Target: https://hosts-file.net/ad_servers.txt
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

...

**Comment by yubiuser** [comment]
The list doesn't exist anymore. You can delete it from your adlists.

**Comment by somera** [comment]
> The list doesn't exist anymore. You can delete it from your adlists.

This is only in the "old"

# grep "hosts-file" migration_backup/*
migration_backup/adlists.list:https://hosts-file.net/ad_servers.txt

file. I didn't add this.

**Comment by jfb-pihole** [comment]
Delete it from there as well.
