### ISSUE TITLE
Custom Disable Timer is missing seconds/minutes selection

### ISSUE THREAD

**Issue by juerb** [pi-hole/pi-hole#3670]
### Versions
Pi-hole version is v5.1.2 (Latest: v5.1.2)
AdminLTE version is v5.1.1 (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2)

### Platform
Docker image "pihole/pihole" on Ubuntu
Tried on Firefox 79 and Chromium 84

### Expected behavior
Up until, I think 5.1.1, one could choose to Disable for X Seconds OR Minutes in the Disable -> Custom Timer dialog box. Now there is just a textbox which are in seconds. There should be a option to select minutes.

### Steps to reproduce

1. Go to 'pi-hole Web Console" and Login
2. Click on 'Disable'
3. Click on 'Custom Time'
4. No option to disable for X minutes

### Screenshots
![grafik](https://user-images.githubusercontent.com/20169299/89794243-0e661500-db27-11ea-8048-5a67e2f98006.png)

### Additional context
Since there are already pre-defined Disable Actions for 10 and 30 seconds it doesn't make much sense to assume custom should be in seconds. Chances are the user would like to disable for longer timespans like 10, 30 oder 60 minutes.

**Comment by yubiuser** [comment]
Thanks for the report. Will be fixed by
https://github.com/pi-hole/AdminLTE/pull/1544

**Comment by harriscd** [comment]
Is the Seconds/Minutes functionality being removed? It seems like some CSS changes affected footer.php -- I could bring back the radio buttons and text labels by manipulating font size and visibility but couldn't trigger the click event in footer.js that handles multiplying the value by 60. I used this feature quite a bit, sad to lose it.

**Comment by dschaper** [comment]
https://www.youtube.com/watch?v=gENVB6tjq_M

**Comment by yubiuser** [comment]
You'r right, the code is still there but the selector is not displayed. I haven't noticed that, thanks for pointing out.

My PR is now degraded from fix to crude interims workaround :-P

**Comment by yubiuser** [comment]
Ok I figured out what's wrong - but I'm not good enough to write the fix.

The source code in `footer.php` is fine:
```
 <div class="input-group-btn" data-toggle="buttons">
                                <label class="btn btn-default">
                                    <input type="radio"> Secs
                                </label>
                                <label id="btnMins" class="btn btn-default active">
                                    <input type="radio"> Mins
                                </label>
                            </div>
```

The problem started with pihole v5.1 and the introduction of the themes. It uses `icheck-bootstrap` to modify the radio buttons and the checkboxes according to user's selection. Therefore it replaces all checkboxes and button classes with `icheck-" + style`
in the function `applyCheckboxRadioStyle` 
```
function applyCheckboxRadioStyle(style) {
    boxsheet.attr("href", getCheckboxURL(style));
    var sel = $("input[type='radio'],input[type='checkbox']");
    sel.parent().removeClass();
    sel.parent().addClass("icheck-" + style);
  }
```

In the end the code lookes like

```
<div class="input-group-btn" data-toggle="buttons">
                                <label class="icheck-greensea">
                                    <input type="radio"> Secs
                                </label>
                                <label id="btnMins" class="icheck-greensea">
                                    <input type="radio"> Mins
                                </label>
                            </div>
                    </div>
```

I tried to modify the code in `applyCheckboxRadioStyle` to skip the replacements in elements with `.parent.hasClass('btn')` but didn't succeed.

Maybe a dev can pick up from here.

P.S. I will revert my previous patch, as this was not a good solution

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/AdminLTE/pull/1588
