### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by agrarian-cyberpunk** [pi-hole/pi-hole#3675]
### Versions

  - Pi-hole version is v5.1.2 (Latest: v5.1.2)
  - AdminLTE version is v5.1.1 (Latest: v5.1.1)
  - FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version: Raspberry Pi OS (32-bit) Lite May 2020

- Platform: Raspberry PI 3

### Expected behavior

Blocking domains like:
r18---sn-cvh7knez.googlevideo.com
r19---sn-cvh7knez.googlevideo.com
r20---sn-cvh7knez.googlevideo.com
r2---sn-nfpnnjvh-cgol.googlevideo.com

### Actual behavior / bug

not blocking these domains.

### Steps to reproduce

Add the same Regex (r\\d+[-.]+sn-[a-zA-z0-9]+[-a-zA-Z0-9]*\\.googlevideo\.com) rule and watch an YouTube video, with an ad. 

### Screenshots
![Screenshot 2020-08-11 at 10 14 43](https://user-images.githubusercontent.com/63846573/89907819-6ebf8a00-dbed-11ea-9b2a-0be25b319ed7.png)
![Screenshot 2020-08-11 at 10 15 42](https://user-images.githubusercontent.com/63846573/89907863-7b43e280-dbed-11ea-8f3b-71fff5df4a77.png)

### Done
I've cleared the caches (on the PI-Hole and my device) and the GUI even states that the status is forwarded.
Rebooted and updated.

I've tried other regex blacklisting which worked without any problem so there isn't a underling problem with the Regex blocking. Which would indicate that regex search (r\d+[-.]+sn-[a-zA-z0-9]+[-a-zA-Z0-9]*\\.googlevideo\.com) is flawed, but I've tested it with various editors with support regex search and it worked without any problems. I've even tested all expression used on its own, and they worked seamlessly.

## Debug token
https://tricorder.pi-hole.net/03z11tnxn6

**Comment by yubiuser** [comment]
How did you test that these domains are not blocked? Because you still see youtube ads?

Please run `nslookup r20---sn-cvh7knez.googlevideo.com` and post the result

**Comment by agrarian-cyberpunk** [comment]
Indeed I've still had the ads, and in the query log it's listed the domains, which should me affected by the regex block, as forwarded.
With the domain which you gave it cant translate it, but if I use one ,which was forwarded, form the query log it can translate it. The IP of my PI-Hole is 192.168.202.
nslookup r20---sn-cvh7knez.googlevideo.com
Server:		192.168.1.202
Address:	192.168.1.202#53

** server can't find r20---sn-cvh7knez.googlevideo.com: NXDOMAIN

nslookup r4---sn-1gi7znes.googlevideo.com
Server:		192.168.1.202
Address:	192.168.1.202#53

Non-authoritative answer:
r4---sn-1gi7znes.googlevideo.com	canonical name = r4.sn-1gi7znes.googlevideo.com.
Name:	r4.sn-1gi7znes.googlevideo.com
Address: 173.194.160.73

**Comment by yubiuser** [comment]
Side note: Checking for ad on youtube is not a valid measure to test the function of pihole and/or the regex as youtube is known to be clever and has circumvented any attempts to block ads on DNS level so far. Some are even way more advanced than simple regex filter.

But indeed your regex are not applied to the domains. I checked regex101.com (https://regex101.com/r/bnYOgV/1) and they are valid regex enties.
Maybe it is a problem with the Group assignment? Do you use any Groups in pihole?

**Comment by agrarian-cyberpunk** [comment]
The PI-Hole has no changes to any settings except password, some ad lists and the regex search with isn't working, so no Groups (except default which is activated), no clients.

**Comment by yubiuser** [comment]
Ok. Please provide a debug token, generated with `pihole -d` or via web interface.

**Comment by agrarian-cyberpunk** [comment]
https://tricorder.pi-hole.net/03z11tnxn6

**Comment by dschaper** [comment]
Please follow the debugging guide at https://docs.pi-hole.net/ftldns/regex/overview/#pi-hole-regex-debugging-mode

Also please review https://docs.pi-hole.net/ftldns/regex/tutorial/ for the format and style of regex we can use. (POSIX Extended Regular Expressions)

Since this is not a bug, it's a configuration issue, please use https://discourse.pi-hole.net for discussion. That is the site we link to in the "Questions and Configurations" issue chooser.

**Comment by agrarian-cyberpunk** [comment]
Your right. PI-Hole doesn't know \d. This works for me now:
r[0-9]+\\-+sn\\-+[0-9a-z]+[-0-9a-z]*\\.googlevideo\\.com
