### ISSUE TITLE
Installer downloads wrong binary if running vanilla Debian on Raspberry Pi 1/0 (needs armel)

### ISSUE THREAD

**Issue by fl4co** [pi-hole/pi-hole#3679]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  manually installed v5.2

### Platform

- OS and version:  Debian 10 (not Raspbian!)

- Platform:  Raspberry Pi 1
### Expected behavior

The installer should download the correct binaries.

### Actual behavior / bug

When installing Pi-hole on a Raspberry Pi 1 (and I think 0 too) on a Debian provided image (not Raspbian), the wrong binary of pihole-FTL is downloaded, so it won't be able to start. The problem is that Raspbian provided packages are different from armel Debian packages, but when installing Pi-hole the wrong architecture is detected.

### Steps to reproduce

1. Grab an image from raspi.debian.org;
2. Burn it to an SSD card and boot the Pi 1;
3. Start the guided Pi-hole installation;
4. pihole-FTL doesn't start;
5. Trying to manually start pihole-FTL fails saying that /usr/bin/pihole-FTL doesn't exist even though it does;
6. Manually downloading pihole-FTL-armel-native from GitHub and moving it to /usr/bin/pihole-FTL fixes the problem.

## Debug Token

- URL:  https://tricorder.pi-hole.net/v2t92r6r1n

### Additional context

Running "file /usr/bin/pihole-FTL" on the binary provided by the installer shows that an armhf binary is downloaded, while Debian expects an armel binary.

Since you guys support both Raspbian and Debian it would be nice if the installer correctly detected if one is running vanilla Debian on a Raspberry Pi and downloaded the correct armel binary (that you already provide on GitHub).

Thank you

**Comment by dschaper** [comment]
> I agree that this is misleading,

That's from `bash` itself. If it says File not exist then it truly doesn't exist.

Can you run `ls -lach /usr/local/bin/` and show the full contents of that directory?

**Comment by fl4co** [comment]
> > I agree that this is misleading,
> 
> That's from `bash` itself. If it says File not exist then it truly doesn't exist.
> 
Sorry if I insist, but that's not the case. To reproduce, I downloaded pihole-FTL-arm-linux-gnueabi (wrong architecture) in my home folder, made it executable and tried to execute it:

```
mario@pihole:~$ ls -l
totale 8196
-rwxr-xr-x 1 mario mario 8390408 ago 11 11:51 pihole-FTL-arm-linux-gnueabi
mario@pihole:~$ file pihole-FTL-arm-linux-gnueabi 
pihole-FTL-arm-linux-gnueabi: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, with debug_info, not stripped
mario@pihole:~$ ./pihole-FTL-arm-linux-gnueabi 
-bash: ./pihole-FTL-arm-linux-gnueabi: File o directory non esistente
```
Anyway this is not important, you don't have to believe me because we already assessed the architecture mismatch :)
> Can you run `ls -lach /usr/local/bin/` and show the full contents of that directory?

Of course:

```
mario@pihole:~$ ls -lach /usr/local/bin/
totale 36K
drwxr-xr-x  2 root root 4,0K ago 12 00:21 .
drwxr-xr-x 10 root root 4,0K ago  9 13:26 ..
-rwxr-xr-x  1 root root 4,6K ago 10 15:41 log2ram
-rwxr-xr-x  1 root root  15K ago 10 19:41 pihole
-rw-r--r--  1 root root  518 ago 10 15:41 uninstall-log2ram.sh
```

**Comment by dschaper** [comment]
`pihole-FTL-arm-linux-gnueabi` does not exist in `/user/local/bin`.

So far you haven't shown me the binary actually not working. You've shown me a call to `pihole-FTL-arm-linux-gnueabi` that hasn't worked because the file doesn't exist in the paths that you've tried to execute it.

**Comment by fl4co** [comment]
> `pihole-FTL-arm-linux-gnueabi` does not exist in `/user/local/bin`.
> 
> So far you haven't shown me the binary actually not working. You've shown me a call to `pihole-FTL-arm-linux-gnueabi` that hasn't worked because the file doesn't exist in the paths that you've tried to execute it.
> 
> **Edit: I'm probably entirely wrong on this now that I've dug in to the code itself.** It truly is just a very confusing output that exactly mirrors what bash would normally be outputting for a file that doesn't exist. So, my apologies for that.

No worries. I was executing it from my home folder just to show you bash's output.

The executable is in fact not present is /usr/local/bin. When I noticed pihole-FTL was not running I did a `which pihole-FTL` and noticed the it was In /usr/bin. So that's where I placed the correct binary I got from the FTL repo.

I think the relevant code is here:

https://github.com/pi-hole/pi-hole/blob/6b536b7428a1f57ff34ddc444ded6d3a62b00a38/automated%20install/basic-install.sh#L2341-L2342

**Comment by dschaper** [comment]
Is this still an issue?

**Comment by fl4co** [comment]
> Is this still an issue?

Haven't tried in a minute but I guess if nothing's been done the same problem should be present still. I will report in a few days.
