### ISSUE TITLE
Query log doesn't auto-filter on click

### ISSUE THREAD

**Issue by griegor** [pi-hole/pi-hole#3681]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi

### Expected behavior

Open the Query Log and click on a field in a row to filter table to only include that value

### Actual behavior / bug

No action when clicking anywhere in the table

### Steps to reproduce

1. Go to Query Log
2. Click on Client within a table row
3. Observe no filter is implemented

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

This worked until I updated to the latest version, but I'm not sure in what version this functionality was lost. I have cleared my cache and it still isn't working. I've tried on Chrome and Firefox. This issue also exists from the iPhone.

**Comment by jfb-pihole** [comment]
Ctrl-click or cmd-click is needed to select a field. This was added so you select multiple filter fields nthe shortcuts are listed at the bottom of the query log.

**Comment by griegor** [comment]
Thank you
