### ISSUE TITLE
FTL doesn't update; new install fails; log doesn't upload

### ISSUE THREAD

**Issue by MitchelValentine** [pi-hole/pi-hole#3682]
### Versions

- Pi-hole: v5.0
- AdminLTE:  v5.0
- FTL:  v5.0

### Platform

- OS and version:  Ubuntu 18,04

- Platform:  DigitalOcean VPS

### Expected behavior

Updates successfully

Creates and uploads log successfully

### Actual behavior / bug

``` [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-linux-x86_64 not found
```

```[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log
```

### Steps to reproduce

1. Run `pihole -up`

1. Run `pihole -d`

## Debug Token

- URL:  https://pastebin.com/tWgx3jkC

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by MitchelValentine** [comment]
> Stupid question perhaps but what happens when you deactivate pi-hole before upgrading? ;)
> 
> If this doesn't work try
> 
> dig github-production-release-asset-2e65be.s3.amazonaws.com
> or
> nslookup github-production-release-asset-2e65be.s3.amazonaws.com
> 
> and post output here.



> Stupid question perhaps but what happens when you deactivate pi-hole before upgrading? ;)
> 
> If this doesn't work try
> 
> dig github-production-release-asset-2e65be.s3.amazonaws.com
> or
> nslookup github-production-release-asset-2e65be.s3.amazonaws.com
> 
> and post output here.

_Originally posted by @TheNec in https://github.com/pi-hole/pi-hole/issues/3680#issuecomment-671480493_

As per this suggestion in this issue;

```
shard@shard-2:~$ dig github-production-release-asset-2e65be.s3.amazonaws.com

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> github-production-release-asset-2e65be.s3.amazonaws.com
;; global options: +cmd
;; connection timed out; no servers could be reached
shard@shard-2:~$ nslookup github-production-release-asset-2e65be.s3.amazonaws.com
;; connection timed out; no servers could be reached
```

**Comment by dschaper** [comment]
Since it's a DO droplet, the easiest would be to backup your data with the teleporter function and spin up a new droplet with a new install.

It looks like the existing installation isn't able to reach any DNS servers to get domain names. You can check `/etc/resolv.conf` and see what servers are configured, and if the configured servers are reachable via `dig` commands.

**Comment by MitchelValentine** [comment]
I'd prefer not to; I had OpenVPN set up in conjunction with the adblocker and that was personally a pain to get working. (might have to anyway)


```
contents of: /etc/resolv.conf
nameserver 127.0.0.53
```

It also looks like this happens on new installs, too.

exported log: https://pastebin.com/UyHwHA3C

```

[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, falling back to netcat for transmission.
nc: getaddrinfo for host "tricorder.pi-hole.net" port 9999: Temporary failure in name resolution
[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log
```

**Comment by dschaper** [comment]
Is there a DNS server at `127.0.0.53`?

**Comment by dschaper** [comment]
```plain
   Aug 13 04:08:51 dnsmasq[18443]: LOUD WARNING: listening on 161.35.10.141 may accept requests via interfaces other than eth0
   Aug 13 04:08:51 dnsmasq[18443]: LOUD WARNING: use --bind-dynamic rather than --bind-interfaces to avoid DNS amplification attacks via these interface(s)
```

**Comment by dschaper** [comment]
```plain
   [2020-08-13 04:08:51.421 18443M] gravityDB_open(): /etc/pihole/gravity.db does not exist
   [2020-08-13 04:08:51.421 18443M] gravityDB_open(): /etc/pihole/gravity.db does not exist
   [2020-08-13 04:08:51.421 18443M] gravityDB_count(0): Gravity database not available
   [2020-08-13 04:08:51.421 18443M] gravityDB_open(): /etc/pihole/gravity.db does not exist
   [2020-08-13 04:08:51.421 18443M] gravityDB_count(3): Gravity database not available
   [2020-08-13 04:08:51.421 18443M] WARN: Database query failed, assuming there are no blacklist regex entries
   [2020-08-13 04:08:51.421 18443M] gravityDB_open(): /etc/pihole/gravity.db does not exist
   [2020-08-13 04:08:51.421 18443M] gravityDB_count(4): Gravity database not available
   [2020-08-13 04:08:51.421 18443M] WARN: Database query failed, assuming there are no whitelist regex entries
   [2020-08-13 04:08:51.425 18443M] Compiled 0 whitelist and 0 blacklist regex filters for 0 clients in 4.4 msec
   [2020-08-13 04:26:32.039 18443M] Reloading DNS cache
   [2020-08-13 04:26:32.039 18443M] Blocking status is enabled
   [2020-08-13 04:26:32.048 18443M] gravityDB_count(SELECT value FROM info WHERE property = 'gravity_count';) - SQL error step no more rows available
   [2020-08-13 04:26:32.048 18443M] Count of gravity domains not available. Please run pihole -g
   [2020-08-13 04:26:32.048 18443M] INFO: No regex blacklist entries found
   [2020-08-13 04:26:32.049 18443M] INFO: No regex whitelist entries found
   [2020-08-13 04:26:32.049 18443M] Compiled 0 whitelist and 0 blacklist regex filters for 0 clients in 1.0 msec
```

You're probably going to have to start over.

**Comment by MitchelValentine** [comment]
Sorry, misclicked. I'll try again with a 2nd DO droplet

**Comment by MitchelValentine** [comment]
```
  [✓] Restarting pihole-FTL service...
  [i] Creating new gravity database
  [i] Migrating content of /etc/pihole/adlists.list into new database
  [✓] Deleting existing list cache
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
```

```
shard@shard-1:~$ ./Pi-hole/automated\ install/basic-install.sh                  
  [✗] Root user check
  [i] Script called with non-root privileges
      The Pi-hole requires elevated privileges to install and run
      Please check the installer for any concerns regarding this requirement
      Make sure to download this script from a trusted source

  [✓] Sudo utility check
curl: (6) Could not resolve host: raw.githubusercontent.com
```

**Comment by TheNec** [comment]
@MitchelValentine 

Thanks for quoting me but I don't think that those problems have the same reason =)

As I don't know anything about Digital Ocean Droplet servers nor much about pi-hole expect of using it I may just help from network side

> contents of: /etc/resolv.conf
> nameserver 127.0.0.53

You may use this address as Localhost but this looks like that the port has been (accidently) mixed up with the last octet in the IP Address 127.0.0.1 when wanting to use the Network Socket 127.0.0.1:53

> IPv4 address(es) bound to the eth0 interface:
> 161.35.10.141/20 matches the IP found in /etc/pihole/setupVars.conf
> 10.10.0.5/16 does not match the IP found in /etc/pihole/setupVars.conf

While the second (private) IP address looks valid the first one is a public one. Are you using the server additionally as a router where this interface is directely connected to the internet because I am pretty sure that there is no other way that this is legal (technically said)? Even if using a Virtual Private(!) Network the address should be a private one.

The second address should be static or DHCP reserved if you want to use it for Pi-hole if I remember correctly.

> IPv6 address(es) bound to the eth0 interface:
> fe80::e07c:58ff:fe17:66a0 does not match the IP found in /etc/pihole/setupVars.conf

This address looks like a dynamic DHCP address and it should also be static or dhcp reservered if you want to use it for Pi-hole. If you don't need/want to use IPv6 I would deactivate it completely.

> [i] Default IPv4 gateway: 161.35.0.1
>   * Pinging 161.35.0.1...

Using this (public) IP as a gateway is also very uncommon when not using it with a router. Same here: Even behind a VPN the gateway address would most probably a private IP address.

> [*** [ DIAGNOSING ]:[Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
> Failed to resolve via localhost (127.0.0.1)
> Failed to resolve via Pi-hole (161.35.10.141)

Here we have the (probably) correct IP address for the localhost and again the 'illegal' address

> [*** [ DIAGNOSING ]:[Setup variables
> ...
> PIHOLE_DNS_1=8.8.8.8
> PIHOLE_DNS_2=8.8.4.4

Just curious: Wanting to block ads but using google DNS servers!? ;)

@dschaper 

My best guess for the missing GravityDB is that this has never worked before even if there is a small chance that a bug messed this up during an upgrade/date

HTH Kind regards!

btw. I tried to find out how Pi-hole works exactly but I couldn't find those informations. Not DNS basics. Something like what Pi-hole does to Dnsmasq. :) Any link?

**Comment by TheNec** [comment]
> shard@shard-1:~$ ./Pi-hole/automated\ install/basic-install.sh   
> ...

Is this correct when I say that you are using the local script because even the basic DNS resolution doesn't work?

> shard@shard-1:~$ ./Pi-hole/automated\ install/basic-install.sh                  
>   [✗] Root user check
>   [i] Script called with non-root privileges
>       The Pi-hole requires elevated privileges to install and run
>       Please check the installer for any concerns regarding this requirement
>       Make sure to download this script from a trusted source
> ...

I think we found a problem here ;)

**Comment by MitchelValentine** [comment]
> > shard@shard-1:~$ ./Pi-hole/automated\ install/basic-install.sh
> > ...
> 
> Is this correct when I say that you are using the local script because even the basic DNS resolution doesn't work?
> 
> > shard@shard-1:~$ ./Pi-hole/automated\ install/basic-install.sh
> > [✗] Root user check
> > [i] Script called with non-root privileges
> > The Pi-hole requires elevated privileges to install and run
> > Please check the installer for any concerns regarding this requirement
> > Make sure to download this script from a trusted source
> > ...
> 
> I think we found a problem here ;)

You are correct; I had cloned the repo as per Method 1
```
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
```



> @MitchelValentine
> 
> Thanks for quoting me but I don't think that those problems have the same reason =)
> 
> As I don't know anything about Digital Ocean Droplet servers nor much about pi-hole expect of using it I may just help from network side
> 
> > contents of: /etc/resolv.conf
> > nameserver 127.0.0.53
> 
> You may use this address as Localhost but this looks like that the port has been (accidently) mixed up with the last octet in the IP Address 127.0.0.1 when wanting to use the Network Socket 127.0.0.1:53
> 
> > IPv4 address(es) bound to the eth0 interface:
> > 161.35.10.141/20 matches the IP found in /etc/pihole/setupVars.conf
> > 10.10.0.5/16 does not match the IP found in /etc/pihole/setupVars.conf
> 
> While the second (private) IP address looks valid the first one is a public one. Are you using the server additionally as a router where this interface is directely connected to the internet because I am pretty sure that there is no other way that this is legal (technically said)? Even if using a Virtual Private(!) Network the address should be a private one.
> 
> The second address should be static or DHCP reserved if you want to use it for Pi-hole if I remember correctly.
> 
> > IPv6 address(es) bound to the eth0 interface:
> > fe80::e07c:58ff:fe17:66a0 does not match the IP found in /etc/pihole/setupVars.conf
> 
> This address looks like a dynamic DHCP address and it should also be static or dhcp reservered if you want to use it for Pi-hole. If you don't need/want to use IPv6 I would deactivate it completely.
> 
> > [i] Default IPv4 gateway: 161.35.0.1
> > 
> > * Pinging 161.35.0.1...
> 
> Using this (public) IP as a gateway is also very uncommon when not using it with a router. Same here: Even behind a VPN the gateway address would most probably a private IP address.
> 
> > [*** [ DIAGNOSING ]:[Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
> > Failed to resolve via localhost (127.0.0.1)
> > Failed to resolve via Pi-hole (161.35.10.141)
> 
> Here we have the (probably) correct IP address for the localhost and again the 'illegal' address
> 
> > [*** [ DIAGNOSING ]:[Setup variables
> > ...
> > PIHOLE_DNS_1=8.8.8.8
> > PIHOLE_DNS_2=8.8.4.4
> 
> Just curious: Wanting to block ads but using google DNS servers!? ;)
> 
> @dschaper
> 
> My best guess for the missing GravityDB is that this has never worked before even if there is a small chance that a bug messed this up during an upgrade/-date so this seems to be a (network) configuration error that has nothing to do with Pi-hole.
> 
> HTH Kind regards!
> 
> btw. I tried to find out how Pi-hole works exactly but I couldn't find those informations. Not DNS basics. Something like what Pi-hole does to Dnsmasq. :) Any link?

As for this issue... I exposed my Pi-hole server to the internet so that I could use it as a DNS for OpenVPN and my computers at home.

**Comment by dschaper** [comment]
> curl: (6) Could not resolve host: raw.githubusercontent.com

Does `/etc/resolv.conf` contain a DNS server that is accessible?

**Comment by MitchelValentine** [comment]
```
shard@shard-1:~$ cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "systemd-resolve --status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0
```

**Comment by dschaper** [comment]
Ah, you'll have to disable/stop systemd-resolved then, it's trying to take over DNS for the droplet. I'm guessing that `dig google.com @127.0.0.53` ends up timing out?

**Comment by dschaper** [comment]
You should have seen some warnings about `systemd-resolved` during the install process, was there anything displayed to you?

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1638

**Comment by dschaper** [comment]
> As for this issue... I exposed my Pi-hole server to the internet so that I could use it as a DNS for OpenVPN and my computers at home.

Sorry, missed this. We do not provide support for open resolvers. Since they are typically found and used to attack other DNS servers, we can not provide assistance. We have guides on how to safely install and configure VPN connections at https://docs.pi-hole.net/guides/vpn/overview/.

**Comment by MitchelValentine** [comment]
Should we move on with diagnosing the install issue?
