### ISSUE TITLE
Missing Query Types on Dashboard

### ISSUE THREAD

**Issue by jhjatl** [pi-hole/pi-hole#3685]
**Versions**
Pi-hole Version v5.1.2
Web Interface Version v5.1.1
FTL Version v5.2

**Platform**
OS and version: dietPi
Platform: raspberrypi 4 (4gb)

**Expected behavior**
See all query types on dashboard. Missing (ANY, SRV, SOA, TXT)

**Actual behavior**
I had to reinstall pihole and the new version does not have all the Query type in the dashboard. The one missing are **(ANY, SRV, SOA, TXT)** I tried to update, repair, and reconfigure multiple time. Any thoughts? See the pictures of my old and new dashboard.

**Debug Token**
URL: https://pastebin.com/GikDycvf

**Screenshots**
![New dash](https://user-images.githubusercontent.com/37995110/90045316-7c7c1a80-dc94-11ea-8f71-3f6a6a67beb4.png)

![old dash](https://user-images.githubusercontent.com/37995110/90045342-84d45580-dc94-11ea-9354-351ff52e2712.png)

**Comment by dschaper** [comment]
As I said in the other issue:

>There hasn't been any queries of those types since you reinstalled.

**Comment by dschaper** [comment]
Please use https://discourse.pi-hole.net.

**Comment by yubiuser** [comment]
Types without queries are not shown anymore

https://github.com/pi-hole/AdminLTE/pull/1475
