### ISSUE TITLE
1. unable to manage adlist (www-data not in pihole group), 2. unwanted dhcpcd installation 

### ISSUE THREAD

**Issue by LLPP65** [pi-hole/pi-hole#3687]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform

Raspbian Buster on Raspberrypi4, Apache, php-fpm

Ubuntu 20.04 on Raspberrypi3, Lighttpd, php-fpm

### Expected behavior

1. adlist management from the web interface should be possible.

2. please do not install dhcpcd as part of the pihole installation. It is not necessary to run this software and I do not use it for the addressing of my servers.

### Actual behavior / bug

1. adlist management from the web interface was not possible. An error was displayed indicating that it was not possible to write to the database. www-data was not a member of the pihole group and was not able to add or remove ad lists. I added www-data to the pihole group and it was then able to add/remove ad lists.

2. The pihole update script installs the previously uninstalled dhcpcd5 package.

## Debug Token
- URL:  
https://tricorder.pi-hole.net/e9g1vnbwj4

**Comment by dschaper** [comment]
Thanks, apache is unsupported so you'll need to modify things for that webserver on your own system.

I agree that `dhcpcd5` should only be considered with Raspbian, and even then it should already be installed with the Raspbian image.

**Comment by LLPP65** [comment]
Apache - no problem, already fixed. 
dhcpcd - Shouldn’t be installed for any system. If someone needs it, it’ll already be there. I specifically have it removed because I’m using static addresses.

**Comment by PromoFaux** [comment]
When the project was first started, the target audience was folk who didn't really know what they were doing, and for people using it on Raspbian on an Rpi, `dhcpcd` was just a way of holding the users hands and setting a static IP for them.

Personally (and I know Dan feels similar) I think we should get rid of it all together, and rather than explicitly set the static on behalf of the user, explain that they will need to ensure that the IP address at the time of installation is, in fact, static, but in order to do so, they will need to make it so.

**Comment by dschaper** [comment]
`dhcpcd5` is how you set a static IP address in canonical Raspbian.

**Comment by LLPP65** [comment]
I don't want to start a philosophical discussion but there are many ways to set static IP addresses. Regardless, I think there is a healthy separation that should be maintained between applications, their configuration and settings that affect the entire operating system.

**Comment by yubiuser** [comment]
Work in progress:
https://github.com/pi-hole/pi-hole/pull/3715

**Comment by yubiuser** [comment]
`dhcpd` won't be installed any longer.

https://github.com/pi-hole/pi-hole/pull/4260

**Comment by yubiuser** [comment]
Fixed with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
