### ISSUE TITLE
unable to update FTL

### ISSUE THREAD

**Issue by rickjjones** [pi-hole/pi-hole#3693]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v4.3.1 (Latest: v5.2)

### Platform

- OS and version: Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linu 

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._
Running pihole -up  to update FTL
### Actual behavior / bug
noted below in additional  Context
_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._
pi@raspberrypi:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"
  Unable to complete update, please contact Pi-hole Support
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Ign:3 https://dev2day.de/pms jessie InRelease
Err:4 https://dev2day.de/pms jessie Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dev2day.de/pms jessie Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by DL6ER** [comment]
Transferred this to Pi-hole core as this comes from an installer issue. However, I totally agree with @yubiuser that this is something out of our control. The operating system is too old and the maintainers do not provide any support/updates any longer. Not something we can fix.

**Comment by dschaper** [comment]
https://dev2day.de/

**Comment by rickjjones** [comment]
@dschaper and @yubiuser thanks for the link! Upgrading my os and commenting out the invalid repository has gotten me back up and running!
Thanks for the assist!
