### ISSUE TITLE
Broken Paths in /pihole landing page

### ISSUE THREAD

**Issue by kinekt4** [pi-hole/pi-hole#3697]
### Versions
- Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE version is v5.1.1 (Latest: v5.1.1)
- FTL version is v5.2 (Latest: v5.2)

### Platform
- OS and version:  18.04.5 LTS
- Platform:  Dell Wyse Thin Client

### Expected behavior

/pihole page should be styled correctly

### Actual behavior / bug

Bad paths means page looks a bit broken.

### Steps to reproduce

1. Go to http://< pi-hole-ip >/pihole/index.php
4. See broken page

## Debug Token

n/a

### Screenshots

- Broken: https://imgur.com/0EmDPXD
- Fixed: https://imgur.com/djcosby

### Additional context

Note: This issue is purely a cosmetic issue. I can submit a fix if required.

**Comment by dschaper** [comment]
We don't use `http://pi-hole-ip/pihole/`

**Comment by dschaper** [comment]
We'd be able to look a bit more closely if there was a debug token.

**Comment by kinekt4** [comment]
> We don't use `http://pi-hole-ip/pihole/`

Do you mean it will be deprecated, because it was installed by default.

As far as I can tell, it's this file:

https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php

**Comment by dschaper** [comment]
No, I mean there's no time we ever tell people to use `http://pi.hole/pihole/`

**Comment by dschaper** [comment]
It's a 404 page. server.error-handler-404    = "/pihole/index.php"

**Comment by kinekt4** [comment]
> It's a 404 page. server.error-handler-404 = "/pihole/index.php"
Ok. So nothing to fix here?

**Comment by dschaper** [comment]
Nothing that I'm aware of. How do you come across the page? Where was it displayed for you?

**Comment by kinekt4** [comment]
Just stumbled on it tbh. I didn't follow any links.
