### ISSUE TITLE
Apache2 dependencies: error in web page loading

### ISSUE THREAD

**Issue by DoctorD90** [pi-hole/pi-hole#3701]
### Versions

- Pi-hole:  v5.1.2 (Latest: v5.1.2)
- AdminLTE:  v5.1.1 (Latest: v5.1.1)
- FTL:  v5.2 (Latest: v5.2)

### Platform

- OS and version:  Debian Buster

- Platform:  VPS + Apache/2.4.38

### Expected behavior

Running the web interface (under Apache) the pages should be normally loaded and stats should be loaded as well.

### Actual behavior / bug

The installer doesn't check for Apache2 minimum requirements.

### Steps to reproduce

1. Use Apache2 as web server
2. Do not install lighttpd and active Web Interface
3. Go to any page/dashboard
4. It will not load the page (php)/stats

### Screenshots

https://discourse.pi-hole.net/t/sqlite3-and-json-encode-fault/18325
https://github.com/pi-hole/pi-hole/issues/2942

### Additional context

The problem is that the basic-installer.sh doesn't install those 2 packages: `libapache2-mod-php7.3` & `php7.3-json`
The first allows to run PHP (display pages), and second to read/parse data (because php7.3-sqlite(3) is already installed, I don't know if thanks to basic-installer or by default).
Theoretically speaking, with a fast look at code, for the first:
```PIHOLE_WEB_DEPS=(lighttpd "${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "${phpVer}-intl" "${phpVer}-json")```
For `libapache2-mod-php7.3`, it could be added with a check if apache2 exists; maybe a little space where do you check for installed and most used web servers (apache2, nginx, etc). This would be usefull! Or maybe just add a section in README.

**Comment by yubiuser** [comment]
Apache is a non-supported websever, only lighttpd is.

**Comment by DoctorD90** [comment]
Thanks for the fast reply. I totally understand.
Could I suggest to "expose" the web interface packages deps you use on the README?
I mean `"${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "${phpVer}-intl" "${phpVer}-json"`
At least this could help people to know what the web interface requires.

Feel free to close the issue. Thanks for the great tool ;)

**Comment by yubiuser** [comment]
If you would like to contribute to the great tool, you could write a "user's guide" for apache. This would help a lot of users and relieve the staff from support requests. There is already one for nginx (also "officially unsupported")
https://docs.pi-hole.net/guides/nginx-configuration/

If you do, submit the PR here https://github.com/pi-hole/docs
