### ISSUE TITLE
BUG - Client list shows up as empty after upgrade

### ISSUE THREAD

**Issue by powershellpr0mpt** [pi-hole/pi-hole#3704]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"

- Platform:  Raspberry Pi Model B Rev 2

### Expected behavior

After upgrading from Pi-Hole version 5.0 to the latest [current] version, my Clients [under Group Management] should remain visible.

### Actual behavior / bug

While the Known Clients list only displays only the IPs of clients I had not defined, the Clients list itself is completely empty.
The Groups section still shows all groups.

### Steps to reproduce

1. Go to 'Group Management'
2. Click on 'Clients'
3. See blank Clients list

## Debug Token

- URL:   https://tricorder.pi-hole.net/48cfmqgtnd

### Screenshots

Doesn't show the clients under Known Clients, but Client list itself is empty
![image](https://user-images.githubusercontent.com/9294993/90880859-75968b80-e3a9-11ea-89b4-4bbd0b7d9a10.png)

Groups do show up
![image](https://user-images.githubusercontent.com/9294993/90880788-5ac41700-e3a9-11ea-89fd-6d385135a37f.png)

**Comment by victorvogelpoel** [comment]
I head the same experience (after updating to 5.1.2).
Force clearing the cache (Ctrl + F5) did the trick for me as well [Brave Chromium latest version]
