### ISSUE TITLE
Error, something went wrong! when add adlist

### ISSUE THREAD

**Issue by KatzeMau** [pi-hole/pi-hole#3706]
Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2

Raspberry pi 4, newest version

https://tricorder.pi-hole.net/l3syfqj9n5

When i add a adlist
  Error, something went wrong!

**Comment by dschaper** [comment]
`[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)`

`apache` is unsupported. See https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36
