### ISSUE TITLE
API (api_db.php) doesn't handle getAllQueries client/domain arguments

### ISSUE THREAD

**Issue by ptb99** [pi-hole/pi-hole#3708]
### Versions

- Pi-hole:    Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE:    AdminLTE version is v5.1.1 (Latest: v5.1.1)
- FTL:     FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Raspbian GNU/Linux 9  

- Platform:   Raspberry Pi Zero W Rev 1.1

### Expected behavior

The docs describe that GET /admin/api_db.php?getAllQueries&client=192.168.1.123 should work and return queries.

Note: there is a python PiHole-api package that wraps the web API and attempts to use the client/domain arguments 
when specified, and this is how I came to discover the discrepancy.

### Actual behavior / bug

Actual result is an empty JSON list.  Inspecting the code in api_db.php shows that only args 'from' and 'until' are parsed
(and, in fact, are required for a successful result).  The optional arg 'types' is also parsed for, but 'client' and 'domain' are 
not parsed at all.

### Steps to reproduce

[Steps depend on what client hosts are in the pihole-FTL.db.  Substitute an appropriate IP into the URL above.]

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by DL6ER** [comment]
> The docs describe that

Please provide a link, there are various docs floating around, not all are official. Also mind that there is `api.php` which is much more powerful as, during runtime, a lot more information is available. We store only a subset in the database to keep the database to reasonably small on disk

**Comment by ptb99** [comment]
I went through my browser history and couldn't find the page I thought I had seen with the list of parameters to getAllQueries that I thought I had seen.   I was also looking at source code in my research, so perhaps I confused where I had seen it.

However, now that you mention the difference between api.php and api_db.php, I see that api.php works fine and therefore my real problem lies with the python PiHole-api package I was using.  Changing that to use api.php should work properly for my needs.

Therefore, I think this issue can be closed and I can take it up with PiHole-api  to use api.php.
