### ISSUE TITLE
Conditional forwarding subnet limitations

### ISSUE THREAD

**Issue by pkracht** [pi-hole/pi-hole#3718]
Why are only some subnets allowed?

Got this error, but doesn't make sense:
```
Conditional forwarding subnet ("172.16.32.0/22") is invalid!
This field requires CIDR notation for local subnets (e.g., 192.168.0.0/16).
Please use only subnets /8, /16, /24, and /32.
The settings have been reset to their previous values
```

It's my decision what kind of subnet I like to setup, isn't it?

**Comment by yubiuser** [comment]
Thanks for the report.
It's a known limitation of the underlying dnsmasq and needs to be fixed there.

See discussion
https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975

**Comment by dschaper** [comment]
Use a couple of `/24`s in place of the `/22`.

**Comment by pkracht** [comment]
> Use a couple of `/24`s in place of the `/22`.

Yeah. Nice trick but the gateway and broadcast would appear multiple times... Just matching the addresses seems not to be enough.

**Comment by dschaper** [comment]
Conditional forwarding shouldn't care about gateways or broadcasts at all. All Conditional Forwarding does is point to an authoritative DNS server for that segment.

Set 172.16.32.0/24 to point to 172.16.32.1 (Obviously made up.)
Set 172.16.33.0/24 to point to 172.16.32.1 

And on until you have your network mapped.

**Comment by pkracht** [comment]
@dschaper and how to do this using the webfrontend?

**Comment by yubiuser** [comment]
You can't. You have to use the dnsmasq config files.
