### ISSUE TITLE
Supported OSes don't match between update check and documentation

### ISSUE THREAD

**Issue by Kreeblah** [pi-hole/pi-hole#3723]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.1

### Platform

- OS and version:  Debian Stretch (DietPi v6.32.2)

- Platform:  Odroid C2

### Expected behavior

When I run `pihole -up`, I should be able to update to the latest release, as https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems indicates that Debian Stretch should be supported on ARM.

### Actual behavior / bug

I receive the following message:

      [✗] Unsupported OS detected: Debian GNU/Linux 9 (stretch)
          https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems
    
          e.g: If you are seeing this message on a fresh install, you can run:
                 'curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash'
    
               If you are seeing this message after having run pihole -up:
                 'PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r'
               (In this case, your previous run of pihole -up will have already updated the local repository)
    
          If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
          https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/
    
      Unable to complete update, please contact Pi-hole Support

### Steps to reproduce

1. Run `dietpi -up`

## Debug Token

- URL:  https://tricorder.pi-hole.net/4jtgjky5po

**Comment by dschaper** [comment]
Run the commands provided to update.
