### ISSUE TITLE
Ubuntu install fails - Error: Unable to update package cache. Please try "apt-get update"

### ISSUE THREAD

**Issue by wo1fmane** [pi-hole/pi-hole#3724]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  AMD PC

### Expected behavior

I expected the interactive install to happen.

### Actual behavior / bug

The install script starts up, but immediately fails with this error message: [Error: Unable to update package cache. Please try "apt-get update"]. Which is annoying not only because of the failure, but because I had just done a system update and upgrade before trying to install Pi-Hole. Plus Curl had to be installed and Git is still not installed.

### Steps to reproduce

Follow the instructions on the Pi-Hole Github page. Specifically, both:
"curl -sSL https://install.pi-hole.net | bash"
and
"wget -O basic-install.sh https://install.pi-hole.net
sudo bash basic-install.sh"
have the same result.

## Debug Token

- URL:

### Screenshots

_If applicable, add screenshots to help explain your problem._
![Screenshot at 2020-09-02 20-34-16](https://user-images.githubusercontent.com/70637423/91971041-ec456880-ed5b-11ea-8b5f-4fc0b427b013.png)

### Additional context

When I manually edited the install script and removed the section causing the problem, this was the result:
======================================================
  [i] Update local cache of available packages...  [✓] Disk space check

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [i] Checking for dhcpcd5 (will be installed)
  [i] Checking for git (will be installed)
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils
  [i] Processing apt-get install(s) for: dhcpcd5 git, please wait...
--------------------------------------------------------------------------------
Selecting previously unselected package dhcpcd5.
(Reading database ... 290491 files and directories currently installed.)
Preparing to unpack .../dhcpcd5_6.11.5-0ubuntu1_amd64.deb ...
Unpacking dhcpcd5 (6.11.5-0ubuntu1) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17025-1_all.deb ...
Unpacking liberror-perl (0.17025-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.17.1-1ubuntu0.7_all.deb ...
Unpacking git-man (1:2.17.1-1ubuntu0.7) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.17.1-1ubuntu0.7_amd64.deb ...
Unpacking git (1:2.17.1-1ubuntu0.7) ...
Setting up git-man (1:2.17.1-1ubuntu0.7) ...
Setting up liberror-perl (0.17025-1) ...
Setting up dhcpcd5 (6.11.5-0ubuntu1) ...
Setting up git (1:2.17.1-1ubuntu0.7) ...
Processing triggers for systemd (237-3ubuntu10.42) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
--------------------------------------------------------------------------------
  [✓] Supported OS detected
  [i] SELinux not detected
  [i] Using upstream DNS: OpenDNS (ECS) (208.67.222.222, 208.67.220.220)
  [✓] Set IP address to 192.168.1.62
  [i] You may need to restart after the install is complete
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: 192.168.1.62/24
  [i] IPv6 address: 
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✗] Check for existing repository in /etc/.pihole
  [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...HEAD is now at 6b536b7 Merge pull request #3564 from pi-hole/release/v5.1.2
  [✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [i] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin...HEAD is now at a03d1bd Merge pull request #1498 from pi-hole/release/v5.1.1
  [✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [i] Checking for netcat (will be installed)
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [i] Checking for idn2 (will be installed)
  [i] Checking for sqlite3 (will be installed)
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [i] Checking for lighttpd (will be installed)
  [i] Checking for php-common (will be installed)
  [i] Checking for php-cgi (will be installed)
  [i] Checking for php-sqlite3 (will be installed)
  [i] Checking for php-xml (will be installed)
  [i] Checking for php-intl (will be installed)
  [i] Processing apt-get install(s) for: netcat idn2 sqlite3 lighttpd php-common php-cgi php-sqlite3 php-xml php-intl, please wait...
--------------------------------------------------------------------------------
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/universe/n/netcat/netcat-traditional_1.10-41.1_amd64.deb  403  Forbidden [IP: 202.158.214.106 80]
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/main/p/php7.2/php7.2-opcache_7.2.24-0ubuntu0.18.04.6_amd64.deb  403  Forbidden [IP: 202.158.214.106 80]
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/main/p/php-defaults/php-sqlite3_7.2+60ubuntu1_all.deb  403  Forbidden [IP: 202.158.214.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

================================================
At this point I gave up.

**Comment by dschaper** [comment]
There were directions provided:
![Screenshot_2020-09-02 Ubuntu install fails - Error Unable to update package cache Please try apt-get update · Issue #3724 ·](https://user-images.githubusercontent.com/2782850/92017639-effbcf80-ed08-11ea-86e9-8450ac3aa591.png)

We can not install on a broken operating system. You'll need to make sure the above command completes successfully first.

Since this isn't a bug but a problem with the operating system, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by wo1fmane** [comment]
What part of "I had just successfully run this command before I attempted the install" do you not understand? There is nothing broken about my OS. I have never had a problem with "apt-get update" and still don't. The command runs to completion with zero errors. It's NOT my OS, it's the Pi-Hole install script.

**Comment by dschaper** [comment]
I'm not helping you. I don't need the abuse. Have a nice day.

**Comment by wo1fmane** [comment]
Whatever. I installed it on a Raspberry Pi with no problems, so it's not as though I have no experience. You're cutting off your nose to spite your face. I'm trying to help you, but you're too busy playing the martyr to fix an issue that obviously anyone else running Ubuntu is going to have, but they're just going to give up and not bother to tell you about the problem.

It's not as though this POS software actually does anything, anyway. It reports having blocked many thousands of requests, but I have seen zero actual reduction in displayed ads. So I'm not going to bother trying helping you, either. Good luck with your pity party.
