### ISSUE TITLE
Unused log dir /var/log/pihole

### ISSUE THREAD

**Issue by moranaga** [pi-hole/pi-hole#3728]
### Versions

* Pi-hole: 5.1.2
* AdminLTE: 5.1.1
* FTL: 5.2

### Platform

* OS and version: Debian 10.5 (Buster) x86_64
* Platform: VMware ESXi 7 VM

### Expected behavior

Log files are placed in a dedicated log dir below /var/log

### Actual behavior / bug

On start of service pihole-FTL a dedicated log dir is created, but apparently never used. Log files are placed on the same level:

**/etc/init.d/pihole-FTL**
```
    # Touch files to ensure they exist (create if non-existing, preserve if existing)
    touch /var/log/pihole-FTL.log /var/log/pihole.log
    [...]
    mkdir -p /var/log/pihole
    chown pihole:pihole /run/pihole /var/log/pihole
    [...]
    chown pihole:pihole /var/log/pihole-FTL.log /var/log/pihole.log
```

### Steps to reproduce

Start / restart of service pihole-FTL.

### Additional context

Ist that on purpose? If not, the suggestion would be to move these log files into the dedicated directory.

**Comment by dschaper** [comment]
It's just how it's always been.

As for a feature request: 

We ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
