### ISSUE TITLE
Gravity.sh to pull hostname from `/etc/hostname` instead of using `pi-hole.isworking.OK` in `gravity.list`

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#373]
^

See [this thread on reddit](https://www.reddit.com/r/pihole/comments/49km3m/pihole_changed_my_hostname/)

**Comment by Mcat12** [comment]
Should we change the hostname to pi-hole.isworking.OK only if there is no custom hostname, or not at all?

**Comment by PromoFaux** [comment]
We're not actually changing the hostname.

`gravity.sh` adds it to the top of `gravity.list` otherwise when you ping it returns `someadprovider.domain`

**Comment by Mcat12** [comment]
When I first commented, I hadn't looked at the reddit post :P 
I edited my comment. I understand now. So will it copy it to the top every time, or only if there's a custom hostname?

**Comment by PromoFaux** [comment]
I think setting hostname is part of the setup? right? For example, raspbian's is set to `raspberrypi`

**Comment by Mcat12** [comment]
Probably

**Comment by dschaper** [comment]
The default hostname is in `/etc/hostname` and is put there by the creator of the image (for the RasPi). You can go into `raspi-config` and change the hostname or you can edit the `/etc/hostname` file directly. (There's also the `/etc/hosts` file too...

**Comment by dschaper** [comment]
Other installations that have a install process will usually ask you to provide a hostname. Raspbian doesn't even expand your root partition unless you specifically do it. (NOOBs is different on that aspect).

**Comment by dschaper** [comment]
And now I read the reddit thread and find out that you all know pretty much everything I've already typed... :smile: :shrug:

**Comment by Fedora-Core** [comment]
quote from dschaper :
> You can go into raspi-config and change the hostname

**idea**
A new "pihole-config" script would solve many problems and issues.
Such a script could be run during install, and later, after the user has modified his OS settings.

Right now, the basic-install script is "monolithic". It could be broken down into "prepare FS and templates" - "install the deb packages" - "download the pihole stuff" - "call pihole-config" - "clean-up".

Then the new "pihole-config" could inspect the user's OS environment, and based on these result and the templates : construct - or re-construct - the configuration files.

Many issues solved.....


Greetings, F.C.

{ _Joke : F.C. has issues with monolithic solutions._ }

**Comment by dschaper** [comment]
Yeah, we are getting things set up for a code refactoring and some process flow changes in a little bit. We want to make sure the current code base is stable and good before we tear it apart and rebuild it again! :lol:

**Comment by Morlok8k** [comment]
I too would like pi-hole to pull in the pi's hostname instead of `PiHole.IsWorking.OK`

i have two raspberry pi's running pi-hole. (they were normal caching dns servers before i tried pi-hole), so its messing with my router's hostname lookup functions a bit.  not a  a big deal, just a minor annoyance to me.
