### ISSUE TITLE
Cloudashur App is blocked by Pi-Hole without any blocking list

### ISSUE THREAD

**Issue by Q7ak5** [pi-hole/pi-hole#3730]
Cloudashur is a hardware encryption module which works together with a Cloudashur App (both produced by https://istorage-uk.com/product/cloudashur/) it encrtypts / decrypts all data sent or retrieved to / from cloud. Since my pi-hole is installed (current version) the App is blocked.

My first idea was that may an URL was wrongfully added to a blocking list. So I did the following experiment to solve the problem:

I deleted every blocking list and I add each blocking list separately, to see whether it may blocks Cloudashur App.

This approach showed, that even WITHOUT any blocking list added, Cloudashur App was not longer working. It is a very peculiar result! Because no blocking rules existed at all. Everything was accessible, with exception of the Cloudashur App. The only error message was that the region could not be determined by the Cloudashur App and therefore it failed.

The problem can be narrowed down as follows:

1) If pi-hole is active WITHOUT any blocking list added, the problem occurs.

2) If the pi-hole is switched of the problem does not occur.

3) If the pi-hole is tunneled by a VPN the problem does not occur.

Therefore, it is may conclusive that the root cause is the pi-hole itself.

I appreciate your support in this matter.

**Comment by TheNec** [comment]
While I am not sure about the VPN tunnel this could possibly occur when the list is deactivated/deleted after the domain is blocked by pi-hole because of the cached entries. Did you flush the caches?

**Comment by PromoFaux** [comment]
What domain does the Cloudashur try to resolve? 

If Pi-hole is disabled, then the domains are simply passed to the upstream resolver to pass (same as if deleting all the adlists). You may have more joy/visibility by asking the community over on our forums, as from the sound of your description, this does not sound like a bug with Pi-hole, per se.

https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36

**Comment by Q7ak5** [comment]
istorage provided me with a list of URLs needed by cloudashur:


https://rm.istorage-uk.com

https://istorage-uk.com

https://message.istorage-uk.com

https://s3.eu-west-2.amazonaws.com

https://extreme-ip-lookup.com/

I entered all in the White List already, but no effect. 

I had not yet flushed the cache. I´ll try this tomrrow and I respond tomorrow  to this test. THANKS for both comments!

**Comment by PromoFaux** [comment]
If you want to ensure the domains are not blocked, make sure you add them as just the domain (without the `http(s)://`) i.e `rm.istorage-uk.com`

**Comment by TheNec** [comment]
JFYI I can resolve all of those domains except 'https://extreme-ip-lookup.com/' which is blocked via pi-hole (most recent versions) with 'Energized Protection Block Ultimate Pack (https://github.com/EnergizedProtection/block)' blocklist. As soon as I whitelist it it works.

**Comment by PromoFaux** [comment]
Also on Steven Black's list.

![image](https://user-images.githubusercontent.com/1998970/92310039-6e26d300-efa2-11ea-832a-e397a6d76354.png)

**Comment by dschaper** [comment]
> The only error message was that the region could not be determined by the Cloudashur App and therefore it failed.

You're probably using an upstream DNS provider that does not pass the location of the client. If the application expects some form of geolocation to find out where you are then you'll need to use an upstream that provides that kind of information. Most don't/won't for privacy reasons.

**Comment by Q7ak5** [comment]
Dear All,

Thanks for the many and quick comments. The domains were added also as regix domains as well. In other cases I had no difficulty to white list a specific domain or a wild card domain.

The reply from Dan sounds very reasonable for me that the problem is the upstream DNS, because I changed to DNS over TLS and DNSSEC, so I had to change my upstream DNS recently.

Thanks all!
