### ISSUE TITLE
No whitelisting if Client have seperate Group

### ISSUE THREAD

**Issue by kzwei** [pi-hole/pi-hole#3731]
### Versions
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

### Expected behavior

I expect the whitelisted domain will be resolved for the client

### Actual behavior / bug

The domain in whitelisting is blocked.

### Steps to reproduce

1. Add a new Group example
2. Give a client the new Group example
3. In blocklist, the list which blocks the domain is selected for default and example Group
4. whitelist the domain e.g. play.googleapis.com (which is in the blocklist)
4. try to resolve whitelisted Domain play.googleapis.com on Client

## Debug Token

- URL:  

[✓] Your debug token is: https://tricorder.pi-hole.net/e4td7d1gkk

### Additional context

It looks like whitelist is ignored for non default Group Clients.

**Comment by yubiuser** [comment]
From you debug log I can see that `play.googleapis.com` is only assigned to group with id=0 (Default group). You have two configured clients, one is in group id 1 and one is in group id 2. So the whitelist entry does not apply to this two clients. You can add the desired client to group 0 as well or add the domain to group 1 or 2.

**Comment by kzwei** [comment]
Hello,

Thanks a lot, now I see the whitelisting can also assign to groups.

Wish you a nice weekend

Rico



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: yubiuser <notifications@github.com>
Datum: 05.09.20 12:43 (GMT+01:00)
An: pi-hole/pi-hole <pi-hole@noreply.github.com>
Cc: kzwei <do2kzw@do2kzw.de>, Author <author@noreply.github.com>
Betreff: Re: [pi-hole/pi-hole] No whitelisting if Client have seperate Group (#3731)


From you debug log I can see that play.googleapis.com is only assigned to group with id=0 (Default group). You have two configured clients, one is in group id 1 and one is in group id 2. So the whitelist entry does not apply to this two clients. You can add the desired client to group 0 as well or add the domain to group 1 or 2.
