### ISSUE TITLE
Update to specific version by tag

### ISSUE THREAD

**Issue by t89** [pi-hole/pi-hole#3735]
### Versions

 - Pi-hole version is in detached HEAD state at v5.1.2 (Latest: v5.1.2)
 -AdminLTE version is v5.1.1 (Latest: v5.1.1)
 - FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Debian Buster
- Platform:  Raspberry Pi

### Expected behavior

I set up and support multiple piholes for friends and family. Because I ran into problems by updating to the latest version multiple times, I would like to **specify precisely, _when_ and _to which version_** a pihole should update. So my approach would have been to update the repo `/etc/.pihole` regulary, checkout the version tag which is known to be working and then call the update script. This doesn't work because the updater is complaining about the HEAD not pointing to a branch.

`pihole checkout [repo] [branch]` also doesn't work, because it does not allow to checkout tags.

### Actual behavior / bug
The update script will fail because the HEAD is not pointing to a branch. It should be possible to specify a version this way and call the update script.

### Workaround
Using the release branches seems to work currently. Being able to access the versions by tag would be nice, though.
`pihole checkout core release/v5.1.2`

**Comment by PromoFaux** [comment]
I discussed this with a Reddit user a while back, should be possible:

https://www.reddit.com/r/pihole/comments/gioym3/can_i_update_to_latest_v4_instead_of_jumping_to_v5/fqhn2gz/?context=3

**Comment by PromoFaux** [comment]
As a side note, I can't imagine any of the `release/v*` branches getting removed any time soon, it's handy to have them around as I myself drop back to older versions to check things.

Usually I just so what I described on reddit, ignoring the "there is an update available" messages from the web interface.

**Comment by dschaper** [comment]
Normally we do remove the branches when they are done, I guess since GitHub autoprunes PR branches we just have forgotten to manually remove the release branches. The release tags point to the merge commits so keeping the branches is not really needed.

But this is a feature request so as we tell everyone:

We ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
