### ISSUE TITLE
FTL update fails with 'No SQLite PHP module was found in APT repository' error

### ISSUE THREAD

**Issue by discipleoftim** [pi-hole/pi-hole#3744]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v4.3.1 (Latest: v5.2)

### Platform
- OS and version:  Raspbian Jessie  Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
- Platform:  Raspberry Pi 3+ 

### Expected behavior
pihole -up

expected update to FTL from 4.3.1 to 5.2

### Actual behavior / bug

Fails to recognize php5-sqlite as installed, here is the output:

$ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 5.6.40-0+deb8u12
  [✗] Aborting installation: No SQLite PHP module was found in APT repository.

  Unable to complete update, please contact Pi-hole Support

### Steps to reproduce

1. pihole -up

## Debug Token

- URL:  not generated - see error below:

$ `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
[?] Would you like to upload the log? [y/N] y
-bash: $'\E[3;J\E[H\E[2JThis': command not found

### Additional context

Ran apt upgrade before pihole -up.  Verified that php5-sqlite is installed using apt:

$ sudo apt install php5-sqlite
Reading package lists... Done
Building dependency tree
Reading state information... Done
php5-sqlite is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by dschaper** [comment]
Raspbian Jessie is very well past it's End Of Life date. We don't support it since Raspberry Pi doesn't support it.

**Comment by mpancorbo** [comment]
Same problem as reported by @discipleoftim but with `buster`. Installed `php-sqlite3` and still FTL is in error
```
[I] pi@raspi: ~ » pihole -up                                                                      [22:45:58]
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u6
  [✗] Aborting installation: No SQLite PHP module was found in APT repository.
[I] pi@raspi: ~ » sudo apt install php-sqlite3                                                    [22:54:05]
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
php-sqlite3 ya está en su versión más reciente (2:7.3+69).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.

```

**Comment by PromoFaux** [comment]
Can we get a debug token please @mpancorbo?

**Comment by mpancorbo** [comment]
I did it (following the example of original poster) and allowed upload. If you can't find it I can post here my log.

**Comment by PromoFaux** [comment]
We need the token it gave you when you uploaded, else it's like looking for a needle in a haystack ;)

**Comment by dschaper** [comment]
Please open a new issue. The original issue was from a corrupted and old system. 

Please fill out the template in full or we will not be able to help you.
