### ISSUE TITLE
ARM EABI device with Debian 10 is installing wrong FTL

### ISSUE THREAD

**Issue by susamn** [pi-hole/pi-hole#3746]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Debian 10 - Buster

- Platform:  **Pogoplug v4 device with** 
_Linux debian 3.18.5-kirkwood-tld-1 #1 PREEMPT Thu Feb 5 17:58:07 PST 2015 armv5tel GNU/Linux_

### Expected behavior

FTL should run properly

### Actual behavior / bug

FTL is not suitable for the device. Tried to install https://github.com/pi-hole/FTL/releases/download/v5.2/pihole-FTL-armel-native manually by coping and renaming it pihole-FTL into /usr/bin. It tried to start and it is starting but when a query is coming to the host to resolve, the FTL is crashing

### Steps to reproduce

1. Go to https://github.com/susamn/debian-10-buster-pogoplug-v4
2. Run this image in a virtual box
3. Install Pihole

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Does this issue still persist? A lot of improvements have been made to the architecture detection in the mean time.
