### ISSUE TITLE
Ajax Error After Update

### ISSUE THREAD

**Issue by stomp442** [pi-hole/pi-hole#375]
##### Expected Behaviour:
I've recently updated my pi-hole, and everything functions as expected, with the exception of the webUI. The webUI loads, but read below...

##### Actual Behaviour:
The interface loads, however, to stats are presented. Instead, all query types show rotating arrows.

Clicking on the Query Log, produces this error:

DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I've spent time reading about the error, but have yet to find a solution to overcome.

##### Steps to reproduce this issue:

Use curl command, update pi-hole, and view webUI

**Comment by stomp442** [comment]
![pi-hole_admin_console](https://cloud.githubusercontent.com/assets/15159601/13646534/e7e28aa8-e5fd-11e5-8fd2-2d474fafeaf2.png)
![pi-hole_admin_console](https://cloud.githubusercontent.com/assets/15159601/13646566/07c6875c-e5fe-11e5-85de-2e3cc9b05884.png)

**Comment by stomp442** [comment]
After running Chrome's developer tools, I've traced the problem to an error 500 on the web server.

GET http://<pi_hole_ip>/admin/api.php?getAllQueries&_=1457551266260 500 (Internal Server Error)

**Comment by stomp442** [comment]
Updated memory setting to 192MBs, problem persists.

![pi-hole_admin_console](https://cloud.githubusercontent.com/assets/15159601/13648450/a68cde56-e606-11e5-8b30-41c1c4c1b934.png)

**Comment by Mcat12** [comment]
Hello, can you paste the contents of `/error.log` if it exists?

**Comment by Roemy** [comment]
I've got the same error on the Query Page of adminLTE page.
Not error log what so ever...

**Comment by Mcat12** [comment]
Have you expanded your root partition?

**Comment by Roemy** [comment]
Yea that's fine i've got 20 GB free space on everything.
I'll just increase the php memory limit for the time being.

My pihole is dealing with ALOT of dns requests so 128 MB default can be increased by 512 or 1024 if php is used more often.

**Comment by Mcat12** [comment]
How big is the log file?

**Comment by Roemy** [comment]
I've edited my other post but it's now 32 MB to be exact.

**Comment by Mcat12** [comment]
Increasing the limit seems to be a good enough solution, for the moment at least. We shouldn't have to change the limit on every user's Pi-hole, so we will look into a better solution! We are also looking into using a database (sometime in the future), and that may help trim down the space used by the log.

**Comment by Roemy** [comment]
That should be really awesome, cause database has a faster way to read the entries and loads the adminLTE page alot faster.

**Comment by stomp442** [comment]
I've played around with the memory allocation in php.ini. Started at 128MBs, raised it to 512MB, and retested, in 64MB increments. It didn't seem to help.

I also checked my disk usage, and I have plenty of room available; the logs that I'm seeing are <1MB/day. Most are measured in kilobytes.

**Comment by Mcat12** [comment]
@stomp442, can you check for a `/error.log` and/or `/var/log/lighttpd/error.log` and post the contents of them?

**Comment by Roemy** [comment]
@stomp442 try the following maybe it'll help you.

edit: /etc/php5/cgi/php.ini

; Determines the size of the realpath cache to be used by PHP. This value should
; be increased on systems where PHP opens many files to reflect the quantity of
; the file operations performed.
; http://php.net/realpath-cache-size
realpath_cache_size = 16k **<---- Commend out these rules**

; Duration of time, in seconds for which to cache realpath information for a given
; file or directory. For systems with rarely changing files, consider increasing this
; value.
; http://php.net/realpath-cache-ttl
realpath_cache_ttl = 120 **<---- Commend out these rules**

**Comment by stomp442** [comment]
@Mcat12 @Roemy Sorry for the delay.

Before commenting on your suggestions, I have to say, that suddenly, it's working. Yesterday, I was messing around with the memory settings (not the lines to comment out), and bumped up my memory_limit to 512MBs. Saved the change, and basically threw up my hands and walked away.

This morning, I checked, and the dashboard was populated with information, and everything seems to be working.

What I noticed immediately was that my timezone was incorrectly set, and I corrected that.

My uptime on the device (and Nagios) confirm that the device had been up all that time.

So, I'm left wondering how, or what caused it to start working.

As for the error.log(s), I'd checked both, and found that the lighttpd log showed memory allocation issues. I found several articles on the internet that made suggestions to modify the memory settings in php.ini. But, after restarting services, and even rebooting, didn't seem to have an effect.

As for Roemy's suggestions, I'm going to drop my memory_max to the default (128MBs), and comment out those lines and retest, just to see.

So, it is working now, but, I don't know why.

**Comment by ToronMega** [comment]
Hi,
so I got the same Problem now on two RaPi 2 with Pi-hole Version v2.5.3 Web Interface Version v1.1.5 and  Pi-hole Version v2.5.3 Web Interface Version v1.1.6

2016-03-31 15:00:59: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36 bytes) in /var/www/html/admin/data.php on line 144

I try to change memory limit on the CGI php.ini to 256M and 512M (do not help)

It's working for weeks with 750.xxx., but now I have 1.213.908 Domains Being Blocked.

If I change my adblocks.list and run gravity.sh (so I drop under 1 million) it's  working again :-/
 
Any idea?

**Comment by Mcat12** [comment]
How big is the log file?

**Comment by ToronMega** [comment]
dnsmasq  root     1715336 Mar 31 18:27 pihole.log
www-data www-data    9181 Mar 31 15:20 error.log

not the prob I think

remember : 
1. with 1.213.908 Domains Being Blocked (not running)
2. change my adblocks.list and run gravity.sh so I drop under 1 million ( it's working )
3. change my adblocks.list and run gravity.sh to 1.213.908 Domains (not running)
I do not reboot or any other steps between 1-3

the core problem in my case is that are "1.213.908 Domains Being Blocked"

**Comment by Mcat12** [comment]
How big is `/etc/pihole/gravity.list`? That is also loaded into memory by php.

**Comment by ToronMega** [comment]
root root 38407616 Mar 31 14:55 gravity.list

**Comment by Mcat12** [comment]
38MB + 17MB = a lot of bytes... That's probably the reason. I do think that the adlist file does mention that large lists (Mahakala) might screw up the web interface. We are trying to get around this, but since we are only voluntary devs, we're not as fast as full timers. D:

**Comment by PromoFaux** [comment]
Also worth noting that if you have ipv4 and ipv6 blocking enabled, `gravity.list` has an entry for each of those.. so each domain is doubled up, vastly increasing the size! Might be able to do something a bit cleverer with the PHP, I had some success in rapid log parsing on the query log page, might be able to replicate it for the front page...

**Comment by PromoFaux** [comment]
OK, I have a fix for this, though i'm probably not going to be able to get it up tonight. I will update when it's live.

**Comment by PromoFaux** [comment]
@ToronMega Try the following as a temporary measure until we push the fix to master. I'm probably going to work on tuning the API a bit more, so it may break. But let me know if what's up so far fixes your problems...

```bash
cd /var/www/html/admin
sudo git fetch
sudo git checkout apiChanges
```

To revert it's just:

```bash
cd /var/www/html/admin
sudo git fetch
sudo git checkout master
```

or 

```bash
sudo rm -rf /var/www/html/admin
updateDashboard.sh
```

**Comment by ToronMega** [comment]
sudo rm -rf /var/www/html/admin
sudo mkdir /var/www/html/admin (add this step, without will not run )
sudo /usr/local/bin/updateDashboard.sh

so Pi-hole Version v2.5.3 Web Interface Version v1.1.7 ist 


running fine :-) 

**big Thx**
![pihole](https://cloud.githubusercontent.com/assets/18190553/14201487/960726b0-f7f2-11e5-9aea-70a30ded3698.jpg)
![Uploading pihole.jpg…]()

**Comment by PromoFaux** [comment]
Ah yeah, was about to say @Mcat12 pushed it to release last night. Excellent, glad that fixed it!

**Comment by PromoFaux** [comment]
@stomp442 does this fix your issues, also?

**Comment by stomp442** [comment]
It did fix. Sorry for the massive delay responding.

**Comment by jacobsalmela** [comment]
No problem.  Glad it's working now.

**Comment by Pete1979** [comment]
Hey guys, just did a brand new install of Ubuntu 16.04 and a fresh install of Pi-hole today, now im having this problem. Been trying all day reading and fixing it, but cant get the webinterface to show anything. Only they spinning arrows and when i click Query log i get the ajax error.

**Comment by Mcat12** [comment]
Pastebin `/var/log/lighttpd/error.log`.

**Comment by Pete1979** [comment]
http://pastebin.ubuntu.com/16572784/

**Comment by Mcat12** [comment]
Run `pihole -d` and pastebin `/var/log/pihole_debug.log` and the output of `du -h /var/log/pihole.log`.

**Comment by Pete1979** [comment]
http://pastebin.ubuntu.com/16573395/

Dident quite get the "output of du -h /var/log/pihole.log"

Is this correct?
root@vsrv2:/usr/local/bin# du -h /var/log/pihole.log
108K    /var/log/pihole.log

**Comment by Mcat12** [comment]
Looks right.

**Comment by Mcat12** [comment]
Has `/var/www/html/admin/data.php` been modified? This is very weird.

**Comment by Pete1979** [comment]
Nope, i haven't modified that file. And the modifications i did i changed back since nothing helped.

**Comment by Pete1979** [comment]
Clarification, i did modify /etc/php5/cgi/php.ini. Commented out realpath rules. 

/var/www/html/admin/data.php was never modified

**Comment by Mcat12** [comment]
Modify line 68 of data.php to this:
```
$tmp = explode(": ", $query);
var_dump($tmp);
die();
```
Reload the page and using the dev tools open the network tab and look for a request that returned something besides json. Screenshot that.

**Comment by Mcat12** [comment]
It should look similar to one of these lines:
```
float(3.1)
bool(true)
int(1)
```

**Comment by Pete1979** [comment]
![capture](https://cloud.githubusercontent.com/assets/5860889/15450798/f856cf10-1fa6-11e6-9d24-6dffa03b0f04.PNG)

**Comment by Pete1979** [comment]
![capture1](https://cloud.githubusercontent.com/assets/5860889/15450810/a87ffccc-1fa7-11e6-96a4-974e562c5cfe.PNG)

**Comment by Pete1979** [comment]
Cant really find "float"
Not sure where to look.

**Comment by Mcat12** [comment]
Look for the requests with `admin/api.php?` in the path. Going through each, look in the "body" tab on the right. If it doesn't start with `{`, take a screenshot.

**Comment by Pete1979** [comment]
![capture](https://cloud.githubusercontent.com/assets/5860889/15450863/3c6ea2f6-1faa-11e6-9cfa-731185f56c37.PNG)

**Comment by Pete1979** [comment]
Hmm, there is nothing in the "body" tab on those 6 api.php requests.

**Comment by Mcat12** [comment]
Try opening them in a new tab

**Comment by Pete1979** [comment]
I get "The website cannot display the page"

**Comment by Mcat12** [comment]
Pastebin `/var/log/lighttpd/error.log` again.

**Comment by Pete1979** [comment]
http://pastebin.ubuntu.com/16582500/

**Comment by Mcat12** [comment]
Pastebin data.php

**Comment by Pete1979** [comment]
`<?php    
    $log = array();
    $ipv6 = file_exists("/etc/pihole/.useIPv6");
    $hosts = file_exists("/etc/hosts") ? file("/etc/hosts") : array();
    
    /*******   Public Members ********/
    function getSummaryData() {
        global $ipv6;        
        $log = readInLog();
        $domains_being_blocked = gravityCount() / ($ipv6 ? 2 : 1);

        $dns_queries_today = count(getDnsQueries($log));

        $ads_blocked_today = count(getBlockedQueries($log));

        $ads_percentage_today = $dns_queries_today > 0 ? ($ads_blocked_today / $dns_queries_today * 100) : 0;

        return array(
            'domains_being_blocked' => $domains_being_blocked,
            'dns_queries_today' => $dns_queries_today,
            'ads_blocked_today' => $ads_blocked_today,
            'ads_percentage_today' => $ads_percentage_today,
        );
    }

    function getOverTimeData() {        
        $log = readInLog();
        $dns_queries = getDnsQueries($log);
        $ads_blocked = getBlockedQueries($log);

        $domains_over_time = overTime($dns_queries);
        $ads_over_time = overTime($ads_blocked);
        alignTimeArrays($ads_over_time, $domains_over_time);
        return Array(
            'domains_over_time' => $domains_over_time,
            'ads_over_time' => $ads_over_time,
        );
    }

    function getTopItems() {        
        $log = readInLog();
        $dns_queries = getDnsQueries($log);
        $ads_blocked = getBlockedQueries($log);

        $topAds = topItems($ads_blocked);
        $topQueries = topItems($dns_queries, $topAds);

        return Array(
            'top_queries' => $topQueries,
            'top_ads' => $topAds,
        );
    }

    function getRecentItems($qty) {
        $log = readInLog();
        $dns_queries = getDnsQueries($log);
        return Array(
            'recent_queries' => getRecent($dns_queries, $qty)
        );
    }

    function getIpvType() {
        $log = readInLog();
        $dns_queries = getDnsQueries($log);
        $queryTypes = array();

        foreach($dns_queries as $query) {
            $tmp = explode(": ", $query);var_dump($tmp);die();
            $queryType = explode(" ", $info)[0];
            if (isset($queryTypes[$queryType])) {
                $queryTypes[$queryType]++;
            }
            else {
                $queryTypes[$queryType] = 1;
            }
        }

        return $queryTypes;
    }

    function getForwardDestinations() {
        $log = readInLog();
        $forwards = getForwards($log);
        $destinations = array();
        foreach ($forwards as $forward) {
            $exploded = explode(" ", trim($forward));
            $dest = $exploded[count($exploded) - 1];
            if (isset($destinations[$dest])) {
                $destinations[$dest]++;
            }
            else {
                $destinations[$dest] = 0;
            }
        }

        return $destinations;

    }

    function getQuerySources() {
        $log = readInLog();
        $dns_queries = getDnsQueries($log);
        $sources = array();
        foreach($dns_queries as $query) {
            $exploded = explode(" ", $query);
            $ip = hasHostName(trim($exploded[count($exploded)-1]));
            if (isset($sources[$ip])) {
                $sources[$ip]++;
            }
            else {
                $sources[$ip] = 1;
            }
        }
        arsort($sources);
        array_slice($sources, 0, 10);
        return Array(
            'top_sources' => $sources
        );
    }

    function getAllQueries() {
        $allQueries = array("data" => array());
        $log = readInLog();
        $dns_queries = getDnsQueriesAll($log);

        foreach ($dns_queries as $query) {
            $time = date_create(substr($query, 0, 16));
            $exploded = explode(" ", trim($query));
            $tmp = $exploded[count($exploded)-4];
            
            if (substr($tmp, 0, 5) == "query"){
              $type = substr($exploded[count($exploded)-4], 6, -1);
              $domain = $exploded[count($exploded)-3];
              $client = $exploded[count($exploded)-1];
              $status = "";
            }
            elseif (substr($tmp, 0, 9) == "forwarded" ){
              $status="OK";
            }
            elseif (substr($tmp, strlen($tmp) - 12, 12)  == "gravity.list"  && $exploded[count($exploded)-5] != "read"){
              $status="Pi-holed";
            }
            
            if ( $status != ""){
              array_push($allQueries['data'], array(
                $time->format('Y-m-d\TH:i:s'),
                $type,
                $domain,
                hasHostName($client),
                $status,
              )); 
            }
            
            
        }
        return $allQueries;
    }

    /******** Private Members ********/
    function gravityCount() {
        //returns count of domains in blocklist.
        $gravity="/etc/pihole/gravity.list";
        $swallowed = 0;
        $NGC4889 = fopen($gravity, "r");
        while ($stars = fread($NGC4889, 1024000)) {
          $swallowed += substr_count($stars, "\n");
        }      
        fclose($NGC4889);
        
        return $swallowed;
            
    }
    function readInLog() {
        global $log;
        return count($log) > 1 ? $log :
            file("/var/log/pihole.log");
    }
    function getDnsQueries($log) {
        return array_filter($log, "findQueries");
    }
    function getDnsQueriesAll($log) {
      return array_filter($log, "findQueriesAll");
    }
    function getBlockedQueries($log) {
        return array_filter($log, "findAds");
    }
    function getForwards($log) {
        return array_filter($log, "findForwards");
    }


    function topItems($queries, $exclude = array(), $qty=10) {
        $splitQueries = array();
        foreach ($queries as $query) {
            $exploded = explode(" ", $query);
            $domain = trim($exploded[count($exploded) - 3]);
            if (!isset($exclude[$domain])) {
                if (isset($splitQueries[$domain])) {
                    $splitQueries[$domain]++;
                }
                else {
                    $splitQueries[$domain] = 1;
                }
            }
        }
        arsort($splitQueries);
        return array_slice($splitQueries, 0, $qty);
    }

    function overTime($entries) {
        $byTime = array();
        foreach ($entries as $entry) {
            $time = date_create(substr($entry, 0, 16));
            $hour = $time->format('G');

            if (isset($byTime[$hour])) {
                $byTime[$hour]++;
            }
            else {
                $byTime[$hour] = 1;
            }
        }
        return $byTime;
    }

    function alignTimeArrays(&$times1, &$times2) {
        $max = max(array(max(array_keys($times1)), max(array_keys($times2))));
        $min = min(array(min(array_keys($times1)), min(array_keys($times2))));
        
        for ($i = $min; $i <= $max; $i++) {
            if (!isset($times2[$i])) {
                $times2[$i] = 0;
            }
            if (!isset($times1[$i])) {
                $times1[$i] = 0;
            }
        }

        ksort($times1);
        ksort($times2);
    }

    function getRecent($queries, $qty){
        $recent = array();
        foreach (array_slice($queries, -$qty) as $query) {
            $queryArray = array();
            $exploded = explode(" ", $query);
            $time = date_create(substr($query, 0, 16));
            $queryArray['time'] = $time->format('h:i:s a');
            $queryArray['domain'] = trim($exploded[count($exploded) - 3]);
            $queryArray['ip'] = trim($exploded[count($exploded)-1]);
            array_push($recent, $queryArray);

        }
        return array_reverse($recent);
    }

    function findQueriesAll($var) {
        return strpos($var, ": query[") || strpos($var, "gravity.list") || strpos($var, ": forwarded") !== false;
    }
    
    function findQueries($var) {
        return strpos($var, ": query[") !== false;
    }

    function findAds($var) {
      $exploded = explode(" ", $var);
      $tmp = $exploded[count($exploded)-4];
      $tmp2 = $exploded[count($exploded)-5];
      //filter out bad names and host file reloads:
      return (substr($tmp, strlen($tmp) - 12, 12)  == "gravity.list" && $tmp2 != "read") ;
    }

    function findForwards($var) {
        return strpos($var, ": forwarded") !== false;
    }
    
    function hasHostName($var){
        global $hosts;
        foreach ($hosts as $host){
            $x = explode("\t", $host);
            if ( $var == $x[0] ){
                $var = $x[1] . "($var)";
            }
        }
        return $var;
    }
?>
`

**Comment by Mcat12** [comment]
Add `/*` to line 69 (making it `/*$queryType = explode(" ", $info)[0];`)
Add `*/` to line 75 (making it `}*/`)
It really shouldn't be making it to line 69 anyways, since it *should* exit on the line before...
Then try opening `http://pi.hole/admin/api.php?getQueryTypes` in a new tab (optionally replace `pi.hole` with the IP address of the Pi)

**Comment by Pete1979** [comment]
That gave me a api.json file to download

**Comment by Pete1979** [comment]
And now the webinterface shows some stats.


![capture](https://cloud.githubusercontent.com/assets/5860889/15454860/3e5359f0-2044-11e6-8167-48a0caadbbc6.PNG)

**Comment by Mcat12** [comment]
Look in the dev tools again for that query types request and check what is in the body

**Comment by Pete1979** [comment]
![capture](https://cloud.githubusercontent.com/assets/5860889/15454918/95d89c66-2045-11e6-82c8-6fe82e7a841e.PNG)

**Comment by Pete1979** [comment]
That was the only one not starting with {

**Comment by Pete1979** [comment]
Im not entierly sure that the Pi works as a DNS eighter. When i set my tablets to use it as DNS, Play store does not work :(

**Comment by Mcat12** [comment]
What version of php is being used?

**Comment by Pete1979** [comment]
root@vsrv2:/usr/local/bin# php -v
PHP 7.0.6-13+donate.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Mcat12** [comment]
As of php 5.4, that dereference syntax should work... maybe the php version used by lighttpd is not 7...
Make a new php file at `/var/www/html/info.php` and put this in: `<?php phpinfo(); ?>`. Open `your-pi-ip/info.php` and find the php version.

**Comment by Pete1979** [comment]
![capture](https://cloud.githubusercontent.com/assets/5860889/15455522/bcc10226-2056-11e6-813c-91b4ab9c3b69.PNG)

**Comment by Mcat12** [comment]
That's why... you'll need to update the php fast-cgi to at least 5.4

**Comment by Pete1979** [comment]
Would you mind telling me how to do that? I have run the apt-get update and upgrade, and dist-upgrade.

**Comment by Mcat12** [comment]
After reloading, is the web php still at 5.3?

**Comment by Pete1979** [comment]
Yes

**Comment by Pete1979** [comment]
Worth mentioning might be that this is a virtual Ubuntu in Hyper-V. So i could revert to the clean install before Pi-Hole installation if need be.

**Comment by Mcat12** [comment]
It seems that there only issue is the php version.

**Comment by Mcat12** [comment]
Do you have something like this in the file `/etc/lighttpd/lighttpd.conf`?
```
fastcgi.server = ( ".php" => ((
                     "bin-path" => "/usr/bin/php5-cgi",
                     "socket" => "/tmp/php.socket"
                 )))
```

**Comment by Mcat12** [comment]
Try installing `php5-cgi`.

**Comment by Pete1979** [comment]
etc/lighttpd/lighttpd.conf
http://pastebin.com/VTzN67Km

Tried installing php5-cgi
root@vsrv2:~# apt-get install php5-cgi
Reading package lists... Done
Building dependency tree
Reading state information... Done
php5-cgi is already the newest version (5.3.2-1ubuntu4).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

**Comment by Pete1979** [comment]
php7.0-cgi installed fine. 
![capture](https://cloud.githubusercontent.com/assets/5860889/15456626/4d2d56ce-2076-11e6-90a1-e2fd1f69855b.PNG)

Do i need to revert some of the changes i did before?
These: 
Add /* to line 69 (making it /*$queryType = explode(" ", $info)[0];)
Add */ to line 75 (making it }*/)

**Comment by Mcat12** [comment]
It would be easiest to remove the whole `/var/www/html/admin` folder and run `pihole -u`. That will redownload the web interface.

**Comment by Pete1979** [comment]
removed /var/www/html/admin folder and ran pihole -u. Now the webinterface is back to how it was from the beginning = not working.

**Comment by Mcat12** [comment]
What version is shown on info.php?

**Comment by Pete1979** [comment]
Still PHP Version 5.3.2-1ubuntu4

**Comment by Mcat12** [comment]
Does it change after running these commands?
```
sudo lighty-enable-mod fastcgi 
sudo lighty-enable-mod fastcgi-php
sudo service lighttpd force-reload
```

**Comment by Pete1979** [comment]
Now its PHP Version 7.0.6-13+donate.sury.org~xenial+1

**Comment by Mcat12** [comment]
Good! That should fix it then.
