### ISSUE TITLE
Pihole FTP offline after power outage

### ISSUE THREAD

**Issue by 9eight7** [pi-hole/pi-hole#3755]
### Versions

- Pi-hole:  v5.1.2 (Latest: v5.1.2)
- AdminLTE:  v5.1.1 (Latest: v5.1.1)
- FTL:  v5.2 (Latest: v5.2)

### Platform

- OS and version:  Raspbian 10

- Platform:  Raspberry Pi

### Expected behavior

_My breaker tripped and then Pihole stopped working. I logged onto the admin browser from my laptop and found that the FTL is offline. Uninstalled pihole, sudo apt update, sudo apt upgrade, reinstall pihole, pihole -r (repair and reconfigure), reboot, reinstall git + curl, and the FTL is still offline. dnsmasq, pihole-FTL, and lighttpd seem to fail to run._

### Actual behavior / bug

_pihole -d 
https://tricorder.pi-hole.net/1rv68w8gnp_

## Debug Token

- URL:  https://tricorder.pi-hole.net/1rv68w8gnp

### Screenshots

_
![image](https://user-images.githubusercontent.com/71485738/93650897-93fda000-f9c4-11ea-9084-7a2f19cb62da.png)
._

### Additional context

_I have gone through countless posts and commands to get this up and running again. Along the way I lost the wireless network box on the top right of the desktop. I am new to Linux and am unsure of what I am doing._

**Comment by dschaper** [comment]
```plain
[53] is in use by unbound (https://docs.pi-hole.net/main/prerequisites/#ports)
[53] is in use by unbound (https://docs.pi-hole.net/main/prerequisites/#ports)
```

Looks like your `unbound` configuration is set to use port 53. That prevents FTL from working correctly.

Open a topic at https://discourse.pi-hole.net in the Help section if you need help with configuring things.

**Comment by 9eight7** [comment]
Thank you for the quick reply! Am I looking how to disable unbound?

**Comment by dschaper** [comment]
I don't know, that's something to ask on our Discourse.
