### ISSUE TITLE
Pi-Hole on MainSystem + Docker Pi-Hole

### ISSUE THREAD

**Issue by realizelol** [pi-hole/pi-hole#3757]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  RockPi 4B

### Expected behavior

`service pihole-FTL restart` should only restart itself not the dockers pihole-FTL.

### Actual behavior / bug

If the dockers pihole-FTL restarted later it will restart the dockers one.

### Steps to reproduce

Install pihole on ubuntu 20.04 and install docker with the latest pihole/pihole:latest.
`service pihole-FTL restart` + `docker exec pihole service pihole-FTL restart` + `service pihole-FTL restart`
Error Msg:

Not stopped; may still be shutting down or shutdown may have failed, killing now

ps -aux | grep pihole
root      734938  0.0  0.0    192    72 pts/0    S+   08:38   0:00 s6-supervise pihole-FTL
root      744874  1.2  0.1 187476  5564 ?        Sl   09:43   0:00 pihole-FTL no-daemon          <--- docker
root      744884  0.0  0.0   6336   644 pts/0    S+   09:43   0:00 grep --color=auto pihole

expected:
root      745026  0.0  0.0    192     4 pts/0    S+   09:44   0:00 s6-supervise pihole-FTL
pihole    745219  0.4  0.2  18008  8692 ?        Ss   09:44   0:00 /lib/systemd/systemd --user
pihole    745220  0.0  0.0 169020  3388 ?        S    09:44   0:00 (sd-pam)
pihole    745248  0.5  0.1 255200  6260 ?        S<l  09:45   0:00 /usr/bin/pihole-FTL
root      745330  0.7  0.1 187476  5564 ?        Sl   09:45   0:00 pihole-FTL no-daemon
root      745429  0.0  0.0   6336   640 pts/0    S+   09:45   0:00 grep --color=auto pihole

### Additional context

[pihole-FTL.service Line 16](https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole-FTL.service#L16)
`pgrep -o "pihole-FTL" > /dev/null 2>&1` should be something like:
```
if [ -f /run/pihole-FTL.pid ]; then
  pgrep -o "pihole-FTL" -F /run/pihole-FTL.pid > /dev/null 2>&1
else
  pgrep -o "pihole-FTL" > /dev/null 2>&1
fi
```

best regards
realizelol

**Comment by PromoFaux** [comment]
I may be completely misunderstanding this, but the process you have labelled as being `docker`'s `pihole-FTL` is not, in fact, `dockers`

running `ps -aux | grep pihole` from my host machine (Pi-hole not installed natively) yeilds no results, despite having Pi-hole installed via docker on this machine. 

I can't see how restarting `pihole-FTL` on the host machine would have any effect on the process running within the container...

**Comment by realizelol** [comment]
Hi PromoFaux,

you understand me correctly. I mean the service pihole-FTL in the docker container of [pihole/pihole](https://hub.docker.com/r/pihole/pihole).
I've tested it in a clean virtual environment (Ubuntu 20.04 and without host pihole) but the service is still listed in "host ps".

output of  `ps -aux | grep pihole` is:
```
root        8432  0.0  0.0    200     4 pts/0    S+   15:17   0:00 s6-supervise pihole-FTL
root        8453  0.1  0.1 135756  5288 ?        Sl   15:17   0:00 pihole-FTL no-daemon
user1      8817  0.0  0.0   9416   728 pts/0    S+   15:22   0:00 grep --color=auto pihole
```

and `pgrep -o "pihole-FTL"` will also affect PID 8453 if it's the oldest version of pihole-FTL.
So we could use at least `pgrep -ox '/usr/bin/pihole-FTL'` or working with pid file `pgrep -oF /run/pihole-FTL.pid`
which will both be set in /etc/init.d/pihole-FTL

I am actually doing this to fix this issue of killing the pihole-FTL in docker:
```
if [[ $(cat /etc/init.d/pihole-FTL | grep "\-F\s\/run\/pihole-FTL\.pid") -eq 0 ]]; then
  sed -i 's#pgrep -o "pihole-FTL" > /dev/null 2>\&1#if [ -f /run/pihole-FTL.pid ]; then\
        pgrep -o "pihole-FTL" -F /run/pihole-FTL.pid > /dev/null 2>\&1\
    else\
        pgrep -o "pihole-FTL" > /dev/null 2>\&1\
    fi#g' /etc/init.d/pihole-FTL
  sed -i 's#pkill -o pihole-FTL#if [ -f /run/pihole-FTL.pid ]; then\
        pkill -o "pihole-FTL" -F /run/pihole-FTL.pid > /dev/null 2>\&1\
    else\
        pkill -o pihole-FTL\
    fi#g' /etc/init.d/pihole-FTL
  sed -i 's#pkill -o -9 pihole-FTL#if [ -f /run/pihole-FTL.pid ]; then\
        pkill -o -9 "pihole-FTL" -F /run/pihole-FTL.pid > /dev/null 2>\&1\
    else\
        pkill -o -9 pihole-FTL\
    fi#g' /etc/init.d/pihole-FTL
  systemctl daemon-reload
fi
```

best regards
realizelol

**Comment by realizelol** [comment]
fixed by dietPi:
https://github.com/pi-hole/pi-hole/commit/57c40cbd09b461882eac4dac63f8ce816e343f1f
