### ISSUE TITLE
'pihole uninstall' is a little too eager

### ISSUE THREAD

**Issue by michaelkolber** [pi-hole/pi-hole#3759]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi

### Expected behavior

Running `pihole uninstall` should uninstall Pi-hole, along with any packages that were installed directly because of it.

### Actual behavior / bug

`pihole uninstall` prompts the user to remove lots of things that shouldn't be removed at all. Although it is placed behind a prompt where the user explicitly has to confirm, I still think it's a bad design.

For example, my installation wasn't working so I decided to uninstall then reinstall. Upon uninstalling, the uninstaller asked me if I wanted to remove packages that were installed with Pi-hole. I said yes, thinking maybe it was a config issue with one of the packages. It asked me if I wanted to remove `dhcpcd5`, and I said yes. Once it was uninstalled, my networking stopped working entirely and I had to reinstall my entire OS.

Perhaps I should have been more aware of that, but going through the rest of the items to uninstall, some make zero sense. For example, `sudo` and `curl` should never be removed by a third-party program. It's just bad design, particularly for something that is meant to be on the more user-friendly side.

### Steps to reproduce

1. Run `pihole uninstall`
2. Confirm that you want to remove associated packages
3. Go through the prompts for each program and see the programs that shouldn't be uninstalled

**Comment by yubiuser** [comment]
You're right, this should not happen. Pihole should only suggest packages that have been installed during pihole's installation and not those which have been installed before.

I'll try to write a fix for this.

**Comment by michaelkolber** [comment]
You rock, thank you!

**Comment by yubiuser** [comment]
I did not find the the time to have a look at this so far :-(

I'm going to close this in favor of https://github.com/pi-hole/pi-hole/issues/3929
