### ISSUE TITLE
[Web] Query Log messed up?

### ISSUE THREAD

**Issue by Roemy** [pi-hole/pi-hole#376]
On the AdminLTE page of the Pihole there is really a weird thing going on since yesterday.
I've changed nothing on the configuration on my part.

Query log is showing the following:

![image](https://cloud.githubusercontent.com/assets/9817180/13698407/2a2249c2-e774-11e5-904a-0484fb4d213c.png)

As you can see in the above screenshot is that the following dns names are being weirdly trimmed.
paypalobjects.com is now ypalobjects.co and also the client is empty.
What i've tried is to flush my log, reboot server, run gravity script and nothing else is working.

This problem is also occurring at somebody else his pihole with the exact same issue, he tried the same things I did.
Could the lastest 1.1.5 update contain a bug? 

Using AdminLTE 1.1.5 of the pihole version

**Comment by ajp2k13** [comment]
I noticed the same thing yesterday when running AdminLTE 1.1.4 and it was ok the day before as far as I know, didn't touch a thing. Updated to the latest but still the same...

**Comment by Mcat12** [comment]
A user on reddit had the same problem. On some machines, dnsmasq seems to not log the hostname of the device, and so everything is shifted left 1. [Link](https://www.reddit.com/r/pihole/comments/49t4hp/query_log_not_being_parsed_correctly/)

**Comment by Roemy** [comment]
Solution for anybody interested.

## Caution
> **This is a temporary work around and will probably be overwritten when updating the dashboard and this issue is only valid for people who are having this problem**


**Step 1**
Open/Edit the following file /var/www/html/admin/data.php

**Step 2**
Search for the following line
`substr($exploded[5], 6, -1),`

**Step 3**
Change the following
```
                substr($exploded[5], 6, -1),
                $exploded[6],
                $exploded[8],
```

To
```
                substr($exploded[5], 0),
                $exploded[6],
                $exploded[7],
```

**Step 4**
Save/Re-upload the file and goto your admin page and everything will be fine again.

**Comment by Mcat12** [comment]
This should be fixed [here](https://github.com/pi-hole/AdminLTE/pull/62)

**Comment by meaverick** [comment]
Thanks. it fixed.
