### ISSUE TITLE
Add possibility to forward lookup to other DNS server depending on source

### ISSUE THREAD

**Issue by derritter88** [pi-hole/pi-hole#3769]
Hi there,

my request should be flagged as "enhancement" or something similar.

It would be great if Pihole could forward request to other internal DNS server depending on the source (mostly IP range).

E.g.:
**LAN 192.168.1.0/24 -> dig mycomputer.foo.bar (internal hostname) -> Pihole**
Gives correct answer.

**WAN 1.2.3.4/32 -> dig othercomputer.foo.bar -> Pihole**
Does not give right answer - SERVFAIL or something similar.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by derritter88** [comment]
okay thanks for the info!

**Comment by dschaper** [comment]
![Uploading InkedScreenshot_2020-10-01 pi-hole pi-hole_LI.jpg…]()

**Comment by derritter88** [comment]
Yeah my fault - I just clicked on Bug report and did not checked the other stuff.
RTFM to myself... :-)

**Comment by yubiuser** [comment]
Pick one:

https://discourse.pi-hole.net/t/allow-different-dns-for-each-group/32258
https://discourse.pi-hole.net/t/allow-pihole-to-monitor-multiple-interfaces-from-the-gui-w-option-to-choose-different-dns-provider-for-each-interface/3457
https://discourse.pi-hole.net/t/different-resolver-dns-option-by-client/11748
https://discourse.pi-hole.net/t/per-mac-address-dns-forward/8710
https://discourse.pi-hole.net/t/use-separate-dns-for-particular-list-of-domains/22782

**Comment by derritter88** [comment]
@yubiuser thanks for the information - unfortunately I do not have enough rights/necessary trust level to neither add new feature requests nor vote for one :-/.

**Comment by dschaper** [comment]
It's pretty easy to get the experience needed to do those actions. There's a limit to prevent low quality posts and duplicate posts that were previously addressed. Reading through the Feature Requests or searching for others that have already made your suggestion should get you leveled up.

**Comment by derritter88** [comment]
> 
> 
> It's pretty easy to get the experience needed to do those actions. There's a limit to prevent low quality posts and duplicate posts that were previously addressed. Reading through the Feature Requests or searching for others that have already made your suggestion should get you leveled up.

I agree - which developer would like to read somethings like: "I have a raspberry pi and found manual at www.something.com but now my raspberry does not work anymore. Please help :-("

I will do my best to do get the necessary rights.
Although someone mentioned that running Pihole as an openresolver is not recommended - any suggestions why?

**Comment by yubiuser** [comment]
https://www.cloudflare.com/en-gb/learning/ddos/dns-amplification-ddos-attack/

**Comment by derritter88** [comment]
> 
> 
> https://www.cloudflare.com/en-gb/learning/ddos/dns-amplification-ddos-attack/

Yeah okay that might be true.
That's why I have limited access to regular lookups (port 53) to only specific IP addresses via my firewall.
I am only running an open resolver as a DoT or DoH server.

**Comment by dschaper** [comment]
As a general rule we do not provide support or guidance for open resolvers of any type.

**Comment by derritter88** [comment]
> 
> 
> As a general rule we do not provide support or guidance for open resolvers of any type.

I understand and agree on that - I think it's also not your job to do that.
You are developing a great DNS resolver while it's a job for security to take care of any DNS DDoS attacks.

**Comment by dschaper** [comment]
Sorry, I may not be following. Are you saying that it's not our job to prevent the use of Pi-hole as an attack weapon?

**Comment by derritter88** [comment]
Of course it's your job (which you are doing great) to minimize any possible attack vector to zero or next to it.
But you cannot prevent a let's say non-IT-professional or someone how is not aware of what she/he is doing to break any security which you have created.
E.g. allow queries from everywhere and portforward :53 from WAN to Pihole.

**Comment by dschaper** [comment]
And that's why we don't support them. Thus this is my last message.
