### ISSUE TITLE
Uninstall script uinstalls PHP5 and all its dependencies without asking!

### ISSUE THREAD

**Issue by necrevistonnezr** [pi-hole/pi-hole#377]
##### Expected Behaviour:
The uninstall script (curl -L uninstall.pi-hole.net | bash) should only uninstall packages that have been newly added by the install script (curl -L install.pi-hole.net | bash).

##### Actual Behaviour:
The uninstall script actually uninstalled & purged php5 and all(!) its dependencies which left my other sites / project on Ubuntu in limbo! 
(it should not make a difference if I use the scripts on a Pi or a Ubuntu Server....)

The apt log (which helped me to restore the server) looks like this: http://pastebin.com/Vnvi4HpS

**Comment by Mcat12** [comment]
The uninstall script needs to be reworked some, and I think adding some dialogs or console input would help.

**Comment by Mcat12** [comment]
There was a commit in a branch that was closed that might fix this. 5eff32f

**Comment by necrevistonnezr** [comment]
Reworked "some" - yes, don't uninstall and price webserver basics like php in the first place, wtf

**Comment by necrevistonnezr** [comment]
purge, not price

**Comment by ChadBHowell** [comment]
@necrevistonnezr, feel free to code up a fix against the Devel branch and submit a pull request...

**Comment by PromoFaux** [comment]
@necrevvistonnezr totally understand where you're coming from. To be fair, the uninstall script has been put of date for a long time now, and was never really meant for the mainstream. It was originally written when the intention for pi-hole was to be the sole use of a RPi, but obviously things have evolved.

I started some work on it a little while ago, and we will be merging that in, but it fell by the way side. The new version of the uninstall script will ask if you want to keep packages installed. I'm out of action for the next week or so, but the rest of the guys are looking into it. 

(Good case for reading over a script before piping it to bash :))

**Comment by necrevistonnezr** [comment]
Since there's already a install.log (/etc/pihole/install.log), the uninstall script could just provide uninstallation for packages that the install script actually installed and ask for confirmation for such removal of newly added packages.

For sure, the current line `$SUDO apt-get -y remove --purge lighttpd php5-common php5-cgi php5` should be removed.

**Comment by Mcat12** [comment]
It would probably work better to separately log what new packages were installed.

**Comment by jacobsalmela** [comment]
@PromoFaux was this one fixed with the 2.6.1.1 release?

**Comment by PromoFaux** [comment]
Yes and no. 

The new uninstall script presents the user with an initial choice along the lines of "Do you wish to remove dependencies installed by pihole? (y/n): "

It then goes through each dependency one by one, and again presents the user with a choice, remove, or not remove.

After the dependency section is complete, then all of the scripts etc are removed from the system.

**Comment by jacobsalmela** [comment]
I wonder if we could loop through the dependencies installed and show a `whiptail` that lets the user pick what is uninstalled (selecting everything by default).

**Comment by PromoFaux** [comment]
I guess that would be possible!

**Comment by jacobsalmela** [comment]
I'll work on it.

**Comment by PromoFaux** [comment]
What's this? @jacobsalmela writing some code?! :stuck_out_tongue_winking_eye:

**Comment by jacobsalmela** [comment]
Haha I know, right?  It's been a while!

**Comment by nate-ubiquisoft** [comment]
Any chance we could go away from whiptail to dialog because we can then specify colors, etc.

**Comment by jacobsalmela** [comment]
I do like the option to change colors.  Does `dialog` have a similar syntax?

Before I started coding this, I realized the script does ask if you want to remove each package, which is what the issue was.  I think the dialogs at this point are just a nice feature to have, but we do ask the user what they want to do, so I will close this issue.
