### ISSUE TITLE
Changing network configuration

### ISSUE THREAD

**Issue by derritter88** [pi-hole/pi-hole#3772]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  Raspiberry Pi 3 & 4

### Expected behavior

Pihole should be installed, run as a DNS resolver, listen on port 53 and so on.
It should not change any local setup DNS setting for `/etc/resolv.conf`

### Actual behavior / bug

After reboot any local DNS request are being sent to 127.0.0.1 - if you have just setup Pihole as an resolver for external addresses and you are quering internal ones you will always get a SERVFAIL.

If you would use a local NTP server (ntp.foo.bar) your raspberry would no longer synchronise the local time and any DoT requests would automatically fail due to huge time difference.

### Steps to reproduce

1. Use a local domain and do not activate the "Use Conditional Forwarding" checkbox.
2. Use a local NTP server (e.g. ntp.foo.bar or ActiveDirectory)
3. Reboot Raspberry Pi
4. Unable use DoT lookups due to time difference

## Debug Token

- URL:  Not needed

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Indeed it shouldn't and it doesn't anymore. Can you provide the full output of `/etc/resolv.conf` please?

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L933

That line should put the chosen upstream servers as the local DNS for the node. Granted we probably should not change any of the IP addressing but the compromise we have come to so far, and is subject to change, is that Raspbian/Raspberry OS still gets `/etc/dhcpcd.conf` modified to help users that have never been exposed to linux. Other distro's can handle themselves. 

That's the idea, but it has not been put in to practice yet. The changes so far are to no use localhost as the node resolver. Previous to version 5 it was a requirement but that has been changed.

**Comment by derritter88** [comment]
I have now added my local `/etc/resolv.conf `config for my needs and "chattr +i" it so it does not get overwritten.
Before I have done that there was a symbolic link to a non existing file. Something at /var/lib/.... - I guess this is part of Ubuntus netplan.

**Comment by dschaper** [comment]
That is very possible. I would advise against marking the file immutable, but that's a personal choice.

**Comment by derritter88** [comment]
Okay - so my current `/etc/resolv.conf` looks like:
nameserver 192.168.10.103
nameserver 192.168.101.170
search foo.bar

My netplan config file would be:
network:
    ethernets:
        eth0:
            addresses: [192.168.20.104/24]
            gateway4: 192.168.20.254
            nameservers:
               addresses: [192.168.10.103, 192.168.101.170]
    version: 2



And I reboot the machine now - without immutable.

**Comment by derritter88** [comment]
New `/etc/resolv.conf` file would look like:

# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 127.0.0.1
# /etc/resolv.conf.tail can replace this line


So it uses Pihole again.

**Comment by dschaper** [comment]
Okay, that's outside of what we handle as support. 

I'm not sure if update/repair of Pi-hole will change `/etc/dhcpcd.conf` but Ubuntu would be one of the OSes that we skip installation on.

https://github.com/pi-hole/pi-hole/pull/3715

**Comment by derritter88** [comment]
Ubuntu usually uses netplan for stuff like that and I have set it up to have static IP and static DNS servers.
But would I else found: There is a file in `/etc/resolvconf/update.d/unbound`


#!/bin/sh -e

PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [ ! -x /usr/sbin/unbound ]; then
    exit 0
fi

if [ ! -f /etc/unbound/unbound_control.key ]; then
    exit 0
fi

if [ ! -x /lib/resolvconf/list-records ]; then
    exit 1
fi

RESOLVCONF_FILES="$(/lib/resolvconf/list-records)"

if [ -n "$RESOLVCONF_FILES" ]; then
    NS_IPS="$(sed -rne 's/^[[:space:]]*nameserver[[:space:]]+//p' $RESOLVCONF_FILES \
        | egrep -v '^(127\.|::1)' | sort -u)"
else
    NS_IPS=""
fi

if [ -n "$NS_IPS" ]; then
    FWD="$(echo $NS_IPS | tr '\n' ' ')"
    unbound-control forward $FWD 1>/dev/null 2>&1 || true
else
    unbound-control forward off 1>/dev/null 2>&1 || true
fi

**Comment by derritter88** [comment]
Not sure if this overwrites any configuration of the regular resolv.conf file or not.

**Comment by yubiuser** [comment]
From now on, Pi-hole will not configure `dhcpd` on Ubuntu anymore

https://github.com/pi-hole/pi-hole/pull/4260.

Since v5.0 Pi-hole does not mess with `resolv.conf` anymore.
https://github.com/pi-hole/pi-hole/pull/3031

**Comment by derritter88** [comment]
Great to hear - I'll close this ticket.
