### ISSUE TITLE
pihole api responds with []

### ISSUE THREAD

**Issue by shrek231** [pi-hole/pi-hole#3773]
### Versions
Pi-hole version is v5.1.2 (Latest: v5.1.2)
AdminLTE version is v5.1.1 (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2) 

### Platform
- OS and version:  
Ubuntu 20.04
- Platform:  
VPS

### Expected behavior

i thought that when i sent a get request to http://(ip)/admin/api.php?getQueryTypes&auth=(auth) it would send me my query types
### Actual behavior / bug

instead it just gave me this `[]`

### Steps to reproduce

use python request library or https://reqbin.com/
type http://(ip)/admin/api.php?getQueryTypes&auth=(auth)
send the get request
see error

### Screenshots

https://i.imgur.com/RpgC6JQ.png

**Comment by dschaper** [comment]
Does `curl 'http://127.0.0.1/admin/api.php?getQueryTypes&auth=<auth>'` return an array?

**Comment by shrek231** [comment]
> 
> 
> Does `curl 'http://127.0.0.1/admin/api.php?getQueryTypes&auth=<auth>'` return an array?

no still reply's []

**Comment by dschaper** [comment]
You used that exact line, with quotes?

Does `echo ">querytypes" | nc 127.0.0.1 4711` show anything?

**Comment by shrek231** [comment]
A (IPv4): 72.12
AAAA (IPv6): 26.17
ANY: 0.10
SRV: 0.03
SOA: 0.00
PTR: 1.57
TXT: 0.01
NAPTR: 0.00
MX: 0.00
DS: 0.00
RRSIG: 0.00
DNSKEY: 0.00
OTHER: 0.00
---EOM---

**Comment by dschaper** [comment]
Did you use that exact `curl` line, with the quote marks?

Are you sure you are using the right token?

**Comment by shrek231** [comment]
i am using the curl command with the quote marks and i got the token form here https://i.imgur.com/Dn1wGPh.png

**Comment by dschaper** [comment]
What is the exact command you are typing?

**Comment by shrek231** [comment]
i used the command you sent me echo ">querytypes" | nc 127.0.0.1 4711

**Comment by dschaper** [comment]
I asked for the curl command. The `nc` responded with the right answer.

Just run `pihole -d` and post the token like the template asked.

**Comment by shrek231** [comment]
i saved the log but i dont know whare the token is in the log file

**Comment by dschaper** [comment]
The very bottom with the asterisks all around it saying that it's the debug token with the URL for it.

**Comment by shrek231** [comment]
this is the bottom of the log i dont see it https://i.imgur.com/zo8wNAn.png

**Comment by dschaper** [comment]
So you said "no" to uploading the log?

**Comment by shrek231** [comment]
well i dident know if i should upload it

**Comment by dschaper** [comment]
Okay, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
