### ISSUE TITLE
DNS / conditional forwarding not accepting all subnets

### ISSUE THREAD

**Issue by jubie25** [pi-hole/pi-hole#3774]
### Versions
- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform
- OS and version:  armbian 20 buster
- Platform:  Rock64

### Expected behavior

all common subnets are able to be configured.

### Actual behavior / bug

only multiples of 8 are allowed. 

### Steps to reproduce

try to enter 10.9.0.0/21 in "Local network in CIDR notation"

## Debug Token

- URL:  https://tricorder.pi-hole.net/byqe2evocx

### Additional context

I regard this as a bug because subnet architecture are fixed by design and of no alternative to devices within the net. So a critical and highly important network device as a filtering DNS resolver must be capable of supporting common network infrastructure setups.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/issues/3718, https://github.com/pi-hole/pi-hole/issues/3621, https://github.com/pi-hole/pi-hole/issues/3640, https://github.com/pi-hole/pi-hole/issues/3657, https://github.com/pi-hole/pi-hole/issues/3572
