### ISSUE TITLE
Admin Console and API no longer showing statistics

### ISSUE THREAD

**Issue by AbsoZed** [pi-hole/pi-hole#378]
##### Expected Behaviour:
Expect graph and statistics to be shown on admin console page.

##### Actual Behaviour:
No statistics or graph shown on the admin console page, loads indefinitely. When queries log is clicked, the following error is thrown: DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by Roemy** [comment]
Hello @AbsoZed 

Please check this issue [Ajax Error](https://github.com/pi-hole/pi-hole/issues/375)

**Comment by AbsoZed** [comment]
Closed as duplicate of [](https://github.com/pi-hole/pi-hole/issues/375)
