### ISSUE TITLE
CNAME cloaking subdomain does not get blocked

### ISSUE THREAD

**Issue by tallgras** [pi-hole/pi-hole#3782]
This is my first bug report and i'm no tech expert, so please bear with me... thanks!

### Versions

- Pi-hole:  Pi-hole v5.1.2  
- AdminLTE:  Web Interface v5.1.1
- FTL:  FTL v5.2

### Platform

- OS and version:  raspian

- Platform:  raspberry pi 3B

### Expected behavior and Reproduction

I added the following regex to the blacklist: (\.|^)privacy-mgmt\.com$
Navigated to www.zeit.de 
zeit.de includes the following subdomain: consent-cdn.zeit.de
This subdomain resolves to: cdn-692.privacy-mgmt.com
The subdomain consent-cdn.zeit.de is not blocked.

Expected behaviour: consent-cdn.zeit.de is blocked, because it is an CNAME alias for cdn-692.privacy-mgmt.com
and privacy-mgmt.com including all its subdomains is blocked via the regex entry.

### Actual behavior / bug

please see above

### Steps to reproduce

please see above

**Comment by dschaper** [comment]
Debug token please.

**Comment by PromoFaux** [comment]
> This subdomain resolves to: cdn-692.privacy-mgmt.com

I'm not sure this is the case:

```plain
root@pihole-docker:/# dig www.zeit.de

; <<>> DiG 9.10.3-P4-Debian <<>> www.zeit.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16849
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.zeit.de.                   IN      A

;; ANSWER SECTION:
www.zeit.de.            1616    IN      CNAME   g2.shared.global.fastly.net.
g2.shared.global.fastly.net. 29 IN      A       151.101.2.49
g2.shared.global.fastly.net. 29 IN      A       151.101.66.49
g2.shared.global.fastly.net. 29 IN      A       151.101.130.49
g2.shared.global.fastly.net. 29 IN      A       151.101.194.49

;; Query time: 22 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Oct 07 09:35:14 BST 2020
;; MSG SIZE  rcvd: 145
```

**Comment by yubiuser** [comment]
I tried your regex and it's working for me.

```
chrko@ThinkPad-X230:~$ dig consent-cdn.zeit.de

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> consent-cdn.zeit.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8025
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;consent-cdn.zeit.de.		IN	A

;; ANSWER SECTION:
consent-cdn.zeit.de.	30	IN	CNAME	cdn-692.privacy-mgmt.com.
cdn-692.privacy-mgmt.com. 30	IN	A	13.227.156.113
cdn-692.privacy-mgmt.com. 30	IN	A	13.227.156.30
cdn-692.privacy-mgmt.com. 30	IN	A	13.227.156.71
cdn-692.privacy-mgmt.com. 30	IN	A	13.227.156.10

;; Query time: 4 msec
;; SERVER: 10.0.10.1#53(10.0.10.1)
;; WHEN: Wed Oct 07 20:15:01 CEST 2020
;; MSG SIZE  rcvd: 139

chrko@ThinkPad-X230:~$ dig consent-cdn.zeit.de

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> consent-cdn.zeit.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62642
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;consent-cdn.zeit.de.		IN	A

;; Query time: 7 msec
;; SERVER: 10.0.10.1#53(10.0.10.1)
;; WHEN: Wed Oct 07 20:16:18 CEST 2020
;; MSG SIZE  rcvd: 37
```

![Bildschirmfoto zu 2020-10-07 20-17-02](https://user-images.githubusercontent.com/26622301/95371207-29ac9100-08da-11eb-9364-7955d0188a36.png)

**Comment by tallgras** [comment]
Sorry for having raised the alarm flag too early... Must have been some kind of system hickup. Tested today and now it is working as expected. I cannot remember excactly what amount of time elapsed from adding the url to the blacklist and testing, but I think it has been several minutes, so I assumed it was not working as expected.
