### ISSUE TITLE
Windows 10 "No Internet Access" when upgraded pi-hole

### ISSUE THREAD

**Issue by VanillaChan6571** [pi-hole/pi-hole#3785]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Ubuntu 20.04 , Windows 10

- Platform:  Actual Machine.

### Expected behavior

Windows 10 users would have no effect during the update.

### Actual behavior / bug

For Windows 10 Users they get (No Internet Access) but when going on the web browser etc it seems to work fine as normal. YouTube runs etc. But for the Microsoft store etc it thinks it's offline because the adapter is telling false info so the Xbox app does not work. Sign-in takes a while trying always hit retry until it works. Some Microsoft apps straight failed. So basically Microsoft apps break.

iOS devices work fine. Roku Works fine.  

EDIT: Found the issue (Gravity) blocked dns.msftncsi.com causing Windows 10 Users to not use apps correctly. Please unblock this if you can. thanks.

### Steps to reproduce

1. Go to Router
2. Set DNS to the pi-hole
3. Apply
4. You will see you have no internet access but you do.
5. Try using Microsoft apps. They quit or dont work properly.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

I installed pi-hole around the 2020 of january. and today of  October 9 2020 I had no issues until now. :/

Also, you're able to use (Example) Word Doc online but not the app. >:V

**Comment by yubiuser** [comment]
Known issue on the windows side
https://discourse.pi-hole.net/t/pihole-working-but-pc-showing-no-internet-access-win-10-update/36575

**Comment by VanillaChan6571** [comment]
> 
> 
> Known issue on the windows side
> https://discourse.pi-hole.net/t/pihole-working-but-pc-showing-no-internet-access-win-10-update/36575

Found the issue (Gravity) blocked dns.msftncsi.com causing Windows 10 Users to not use apps correctly. Please unblock this if you can. thanks.

**Comment by yubiuser** [comment]
Pihole does not maintain adlists. Figure out which list contains this domain with `pihole -q domain` and contact the list maintainer to remove it.
