### ISSUE TITLE
LG webOS

### ISSUE THREAD

**Issue by PeshBG** [pi-hole/pi-hole#3786]
Hello all,
i have set up pi hole in default mode.
Initially LG TV was able to work with internet but from today it cant pass the DNS check if it goes through pi hole.
If i change the dns to 1.1.1.1 everything is fine.

Any suggestions?
My query logs from the TV ip are blank... which is strange

**Comment by PromoFaux** [comment]
Likely something is being blocked, but difficult to tell what. FWIW, I have an LG TV that works on default blocklists with no issue.

Best thing to do is to watch the query log for queries from the TV as it tried to do it's checks and see if anything is blocked, then whitelist one by one until it works.

`pihole -t` from the command line or http://pi.hole/admin/taillog.php to do the same in the browser.

Also worth looking on the [community forums](https://discourse.pi-hole.net) to see if anyone has as similar issue.

Closing this out as it doesn't appear like it's a bug with the software.
