### ISSUE TITLE
Show Client DNS Names rather than IP

### ISSUE THREAD

**Issue by mobomelter** [pi-hole/pi-hole#379]
I was just going through the program and it's awesome and works perfect.

Is there any plans to implement a way for the client IPs to show up as their DNS names instead in the GUI? I run a DNS server internally and with handing out Pi Hole via DHCP but only seeing client IPs it's a bit of a pain to figure out what client is what.

**Comment by Mcat12** [comment]
Yes, we have this and many other ideas floating around. We are preparing for a major code refactor (move global variables and common functions to separate files, etc) and so we will remember this for after that change.

**Comment by mobomelter** [comment]
That would be awesome. You guys are great!

**Comment by kmr2319** [comment]
:+1: 

I would like this feature as well. Thanks for thinking about it!!!

**Comment by Mcat12** [comment]
This is now a feature, though you have to manually link the IP to hostname (and you'll want them static or reserved IPs).

**Comment by withit** [comment]
How do we use the feature?

**Comment by PromoFaux** [comment]
@withit  Just add the IP address and desired name to `/etc/hosts` seperated by a tab.

e.g `192.168.1.1    hostname`

**Comment by kmr2319** [comment]
@PromoFaux @Mcat12  I'm running latest and have proper /etc/hosts update, but the interface still only shows IPs. Thoughts?

Looks like localhost is showing up, but that's about it...

![screenshot from 2016-04-28 12-22-39](https://cloud.githubusercontent.com/assets/17013046/14893085/f9777c96-0d3b-11e6-95a4-8c96c6138262.png)

**Comment by Mcat12** [comment]
Are the IPs and names separated by one tab each?

**Comment by kmr2319** [comment]
That seems to have been the problem. The one IP that was in the list (*.150) had spaces, not a tab.

Opened #484 to address the fact that it requires a tab. Spaces are proper for the /etc/hosts format.

**Comment by kmr2319** [comment]
@Mcat12  PS... Thanks! :smile:

**Comment by mvillarejo** [comment]
this is really great, any chance pihole can contact a local DNS server for name resolution? thanks

**Comment by DL6ER** [comment]
What happens if you specify your local IP as one of the custom IPs for upstream DNS servers?

**Comment by ZeGerve** [comment]
Hello,

i "reload" the thread with the same question. Now pi-hole is on version 5, it's  posible to associate a "specific name" to an ip for analyse who request a lot. I don't know all the ip of my network :)

**Comment by yubiuser** [comment]
@ZeGerve 
Use "Local DNS Records"

**Comment by ZeGerve** [comment]
@yubiuser thank you, i wasn't sure it's will be that. after reboot pihole, it works. Thank you :)

**Comment by mestafin** [comment]
> this is really great, any chance pihole can contact a local DNS server for name resolution? thanks

Any answer on this please?

**Comment by dschaper** [comment]
Uhm, "Yes"? I don't know what your question is but if you'd like to clarify then we can probably give you a more concrete answer.

**Comment by mestafin** [comment]
Pihole currently uses the entries in the LOCAL DNS RECORDS to display the names of clients in the Query Log.

I want an option for Pihole to be ale to query the upstream DNS server for the names of clients. 

I my setup, Pihole sits in-between the clients and the firewall, which also functions as the authoritative DNS and DHCP server for the local LAN domain. At the monument, I have to manually re-enter all the local domain DNS entries again in Pihole for the lookup of client names in the Query Log.

As a final request, can you make the column for the client IP address / client name a little wider? Even better, if you can make the columns adjustable please?

**Comment by DL6ER** [comment]
> I want an option for Pihole to be ale to query the upstream DNS server for the names of clients.

There are two options for you which are there since the beginning of Pi-hole, chose what fits your scenario best:
1. "Conditional forwarding": Send name queries for local devices to a specific DNS server. This is typically used when you are using an external DNS provider (e.g. Google `8.8.8.8`) for your everyday browsing but your router (`192.168.1.1`) is the authoritative nameserver for your network.
2. If your upstream and your authoritative DNS server are the same (this may or not be the case reading your comment): Just disable the security feature to "Never forward non-FQDNs" and also "Never forward reverse lookups for private IP ranges". There is a description beneath the checkboxes to help you deciding what the best configuration will be in your case.

All three options can be found on the web interface in the DNS -> Advanced section.

**Comment by mestafin** [comment]
Thank you very much, that solved my problem
