### ISSUE TITLE
Dashboard doesn't show queries

### ISSUE THREAD

**Issue by robkuehl** [pi-hole/pi-hole#3790]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  RaspberryPi OS

- Platform:  Raspberry Pi,

### Expected behavior
While browsing queries should be displayed on the dashboard

### Actual behavior / bug
Looking at some websites it seems pihole is blocking ads, but the dashboard doesn't show anything.
Despite that, queries are logged when i run "pihole -d" in the console

### Steps to reproduce

1. Fresh install of RaspberryPi OS with Pi Imager
2. Install pihole (everything as recommended)
3. Open Dashboard and visit websites

## Debug Token

- URL:  https://tricorder.pi-hole.net/vxvx4amnso

**Comment by yubiuser** [comment]
Your pihole has not received any queries yet.

```   [2020-10-09 17:01:56.010 623M] Imported 0 queries from the long-term database
   [2020-10-09 17:01:56.010 623M]  -> Total DNS queries: 0
   [2020-10-09 17:01:56.010 623M]  -> Cached DNS queries: 0
   [2020-10-09 17:01:56.010 623M]  -> Forwarded DNS queries: 0
   [2020-10-09 17:01:56.010 623M]  -> Blocked DNS queries: 0
   [2020-10-09 17:01:56.010 623M]  -> Unknown DNS queries: 0
   [2020-10-09 17:01:56.010 623M]  -> Unique domains: 0
   [2020-10-09 17:01:56.010 623M]  -> Unique clients: 0
   [2020-10-09 17:01:56.010 623M]  -> Known forward destinations: 0```

From a client please run

`nslookup pi.hole`

**Comment by robkuehl** [comment]
I ran `nslookup pi.hole`.
The output is: 
`nslookup pi.hole
Server:		192.168.178.1
Address:	192.168.178.1#53
** server can't find pi.hole: NXDOMAIN
`

**Comment by yubiuser** [comment]
Your debug token has expired but im certain that this IP belongs to your router. So your client isn't using pihole.

**Comment by dschaper** [comment]
Please upload a new debug run. 

All debug tokens and logs are automatically deleted after 48 hours for your (and our) protection.

**Comment by yubiuser** [comment]
Closing as the OP did not provide any new information or the debug token asked for
