### ISSUE TITLE
Admin portal unavailable after power loss

### ISSUE THREAD

**Issue by shadowscott** [pi-hole/pi-hole#3795]
### Versions

Pi-hole version is v5.1.2 (Latest: v5.1.2)
fatal: unterminated line in .git/packed-refs: t(),e.toggle(i(this)),!1}),i(this.element).on("click",this.options.removeTr...
AdminLTE version is ERROR (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior

Ability to go to admin console, however it does not load and shows a lot of text on the screen.  

## Debug Token

- URL:  https://tricorder.pi-hole.net/ls8ef8ch0j

### Screenshots

_If applicable, add screenshots to help explain your problem._
![6EC6514E-7CCA-40C2-9ADE-471AB90D213E](https://user-images.githubusercontent.com/21198582/95655949-ee2be580-0ad8-11eb-974c-fdc091a7a430.png)

### Additional context

This has happened a few times after a power outage. I've been able to run pihole -r (that is not working right now) and sometimes I had to reinstall completely. But right now it just seems to be locked up somehow

**Comment by shadowscott** [comment]
Update returns this:
pi@raspberrypi:~ $ pihole -up
/opt/pihole/update.sh: line 14: syntax error near unexpected token `('
/opt/pihole/update.sh: line 14: `readonly ADMIN_INTERFACE_GIT_UR
?       ???T?(
       ,
0
      4
8              @       ?@      ?8
      <
??     `?P'

And repair returns this:
[i] Resetting repository within /var/www/html/admin......  Unable to reset /var/www/html/admin, exiting installer

**Comment by dschaper** [comment]
Looks like the power loss damaged the SDCard. That tends to happen on Raspberry Pi devices, they do not like sudden, unplanned power drops.

**Comment by nicolastrivelli** [comment]
Si surge algún problema para acceder al The Web Interface Dashboard:
    Como chequear que el servidor HTTP está funcionando:
        systemctl status lighttpd.service

    Reiniciar servidor HTTP:
        sudo service lighttpd restart

    Setear permisos para servidor HTTP:
        chmod 755 /var/log/lighttpd
        chown -R www-data:www-data /var/log/lighttpd/
