### ISSUE TITLE
Not resolving all queries "Reply error is not implemented"

### ISSUE THREAD

**Issue by notoriousturtle** [pi-hole/pi-hole#3796]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.2
- FTL:  5.1.1

### Platform

- OS and version:  Raspbian Lite

- Platform:  Raspberry Pi

### Expected behaviour

To successfully resolve.

### Actual behavior / bug

When I run this dig command: `dig +nocmd google.com any +multiline +noall +answer`

It sometimes resolves, and then sometimes does not. 

The below snippet is from pihole.log. This is the result of the dig command being run twice. The first had a successful response. The second did not. 
```
Oct 11 20:21:23 dnsmasq[642]: query[ANY] google.com from 192.168.0.50
Oct 11 20:21:23 dnsmasq[642]: forwarded google.com to 127.0.0.1
Oct 11 20:21:25 dnsmasq[642]: query[ANY] google.com from 192.168.0.50
Oct 11 20:21:25 dnsmasq[642]: forwarded google.com to 127.0.0.1
Oct 11 20:21:25 dnsmasq[642]: reply error is not implemented
```

Whatever `reply error is not implemented` is seems to be the common error. I have not seen any other errors. 

pihole-FTL.log does not produce anything when these commands are run. 

See edit below. 

### Steps to reproduce

Repeatedly run: `dig +nocmd google.com any +multiline +noall +answer`

The command can be simplified to: `dig google.com ANY` - same result obviously. 

## Debug Token

- URL:  https://tricorder.pi-hole.net/f7wvik6hua

### Additional context

I am running pihole with dnscrypt. To isolate the problem I set pihole to use Cloudflare as an upstream DNS server. I still had the same problem. 

EDIT: I've since tried again, and set the upstream DNS server to Google (ECS). I restarted the DNS Resolver and flushed the network table. The commands complete successfully. So I'm wondering if this is maybe dnscrypt that is the problem?

**Comment by dschaper** [comment]
What is the resolver at `127.0.0.1`?

**Comment by dschaper** [comment]
> So I'm wondering if this is maybe dnscrypt that is the problem?

Yes. Though check and see if you really are using `127.0.0.1:5300` as the upstream, I don't see the port being used in the Pi-hole configuration.

**Comment by notoriousturtle** [comment]
Sorry, how can I confirm that `127.0.0.1:5300` is actually being used?

**Comment by notoriousturtle** [comment]
This is on the pihole, where dnscrypt is running on 5300. So its definitely dnscrypt that is the problem. Any ideas? Is there a sample dnscrypt config around that I should try? I only recently setup pihole+dnscrypt, so the configs should already be fairly new. 
```
pi@pihole:/opt/dnscrypt-proxy $ dig @127.0.0.1 -p 5300 flaws.cloud ANY

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> @127.0.0.1 -p 5300 flaws.cloud ANY
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46179
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;flaws.cloud.			IN	ANY

;; ANSWER SECTION:
flaws.cloud.		3600	IN	A	52.218.180.186
flaws.cloud.		86400	IN	NS	ns-966.awsdns-56.net.
flaws.cloud.		86400	IN	NS	ns-1061.awsdns-04.org.
flaws.cloud.		86400	IN	NS	ns-1890.awsdns-44.co.uk.
flaws.cloud.		86400	IN	NS	ns-448.awsdns-56.com.
flaws.cloud.		3600	IN	SOA	ns-1890.awsdns-44.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 698 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Oct 12 09:50:59 AEDT 2020
;; MSG SIZE  rcvd: 257

pi@pihole:/opt/dnscrypt-proxy $ dig @127.0.0.1 -p 5300 flaws.cloud ANY

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> @127.0.0.1 -p 5300 flaws.cloud ANY
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTIMP, id: 5225
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;flaws.cloud.			IN	ANY

;; Query time: 61 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Oct 12 09:51:00 AEDT 2020
;; MSG SIZE  rcvd: 40
```

**Comment by dschaper** [comment]
The output is the reply from the upstream server. You'll notice the second `dig` has a status of `NOTIMP`.

`reply error is not implemented` would be better with a colon, but it's telling you exactly what came back. `reply: error is not implemented` for clarificiation.

**Comment by notoriousturtle** [comment]
Ah, so the problem is the upstream DNS server from DNSCrypt? I just need to tell DNSCrypt to use a better upstream server?

**Comment by dschaper** [comment]
I don't know, you'll need to ask the team that supports DNSCrypt.
