### ISSUE TITLE
Installer doesn't disable query logging

### ISSUE THREAD

**Issue by thislooksfun** [pi-hole/pi-hole#3799]
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Raspbian Buster
- Platform:  RPi 3B+

### Expected behavior

Disabling the query log in the installer should actually turn the query log off.

### Actual behavior / bug

Disabling the query log in the install did not actually disable the query log (still shows in the admin console)

### Steps to reproduce

1. Run the installer
2. Disable the query log when prompted
3. Open the admin console, sign in, and go to the Query Log page

**Comment by dschaper** [comment]
Thanks for the report. Can you please provide a debug token?

**Comment by jfb-pihole** [comment]
Disabling query logging stops logging to file /var/log/pihole.log.  The 24 hour query log shown on the dashboard is controlled by the privacy settings, and data is stored and retrieved in the long term database at /etc/pihole/pihole-FTL.db.
