### ISSUE TITLE
Inability to initiate Skype group chat and calls

### ISSUE THREAD

**Issue by 0xc0ffea** [pi-hole/pi-hole#380]
Skype needs to resolve the following 5 domains, if it can't then basic one on one skype works, group calls and group chats can not be initiated on Win10 PC behind pihole.

ui.skype.com
pricelist.skype.com
apps.skype.com
m.hotmail.com
s.gateway.messenger.live.com

more information here
http://community.skype.com/t5/Windows-desktop-client/Chats-not-working-Check-here/td-p/4276170
##

**Comment by rotational467** [comment]
Additionally, make sure that you whitelist the following:

sa.symbc.com
s1.symbc.com
thru
s5.symbc.com

These are Symantec's Certificate Revocation List servers and are used by a number of companies including MS.  Someone got overly aggressive in blocking Microsoft-related services in the past week somehwere upstream on the hosts lists and broke a bunch of stuff.

**Comment by stejoo** [comment]
If you want to add those with a single command, try this (run as user pi):

`sudo echo whitelist.sh ui.skype.com pricelist.skype.com apps.skype.com m.hotmail.com s.gateway.messenger.live.com sa.symcb.com s{1..5}.symcb.com`

**Comment by Morlok8k** [comment]
FYI, Skype for Linux only needs `s.gateway.messenger.live.com` unblocked.  I ran into the same issue.

**Comment by jacobsalmela** [comment]
Closing.  Added this to the [FAQs in orbit](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212#skype).

**Comment by planet0** [comment]
Skype now needs `client-s.gateway.messenger.live.com` in order to launch on web and on macOS, perhaps others too. Edited [wiki](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212) to include this as well.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/1
