### ISSUE TITLE
PRIVACYLEVEL=4 is broke

### ISSUE THREAD

**Issue by genekellyjr** [pi-hole/pi-hole#3802]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version: Raspbian Buster 5.4.51-v7+

- Platform:  Raspberry Pi 3B

### Expected behavior

PRIVACYLEVEL=4, which is an option in the installer, makes nothing be recorded or logged in any way.

### Actual behavior / bug

The Query Log [Recent Queries, /admin/queries.php] shows the recent queries. PRIVACYLEVEL=3 properly does not populate Recent Queries, as it said it would. PRIVACYLEVEL=4 isn't in the docs either https://docs.pi-hole.net/ftldns/privacylevels/ .

/etc/pihole/pihole-FTL.conf edited with MAXDBDAYS=0 does not fix the issue.

### Steps to reproduce

Enable PRIVACYLEVEL=4 on setup or in /etc/pihole/pihole-FTL.conf
sudo nano /etc/pihole/pihole-FTL.conf
	PRIVACYLEVEL=4
	MAXDBDAYS=0
pihole -l off noflush
sudo service pihole-FTL stop
sudo rm /etc/pihole/pihole-FTL.db
sudo service pihole-FTL start

And see the Query Log's Recent Queries be populated by unobfuscated domains and client IPs.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1232

@PromoFaux Didn't we get rid of level 4 already? I thought it was gone, or is that just in `development`?

**Comment by PromoFaux** [comment]
Just in development as far as I am aware. I don't think it was spotted until after the last release. I may be wrong!

**Comment by dschaper** [comment]
Okay, then it's FINR.

**Comment by PromoFaux** [comment]
Still there in dev 

https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L1214

We must have missed one :) Will PR

**Comment by yubiuser** [comment]
Closing as the PR has been merged into master
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909/1
