### ISSUE TITLE
Unable to use the url http://pi.hole when i am on ethernet but works fine on wifi

### ISSUE THREAD

**Issue by HypeRayy** [pi-hole/pi-hole#3804]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Debian 10

- Platform:  VM on ProxMox

### Expected behavior

You should be able to access the url pi.hole on both wired and wireless connections.

### Actual behavior / bug

I am unable to access the url pi.hole unless i connect to the wireless access point either by unplugging the ethernet cable or connecting to it within the windows 10 network settings.

### Steps to reproduce

1. Make sure you plug in your ethernet cable.
2. Open your browser
3. type 'http://pi.hole' into the browser

## Debug Token

- URL:  https://tricorder.pi-hole.net/f012clbjt8

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Please visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance on configuring Pi-hole for your network.
