### ISSUE TITLE
Pihole admin page not showing statistics.

### ISSUE THREAD

**Issue by hemker** [pi-hole/pi-hole#3807]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version: Raspbian 9.13 Stretch

- Platform:  Raspberry Pi 3B

### Expected behavior

Fresh install of pihole, coupled with Fritz!Box. Opening admin page (dashboard) and expecting statistics to be shown.

### Actual behavior / bug

When opening admin page (dashboard), the stats are only showing '---'. In contrast, using ```pihole -c``` via commandline shows valid statistics. Other functionality can be accessed successfully via the web interface.

### Steps to reproduce

1. Install pihole via recommended method.
2. Use all standard configuration except lighttpd. Instead, web pages are served via already installed apache2.
3. Couple Fritz!Box with pihole dns server.
4. Open admin page.

## Debug Token

- URL: https://tricorder.pi-hole.net/95yoq73l6s

### Screenshots

![grafik](https://user-images.githubusercontent.com/5691856/96414133-fbd61f00-11ec-11eb-993e-11c893ef89e9.png)
![Unbenannt](https://user-images.githubusercontent.com/5691856/96414501-7f900b80-11ed-11eb-89d9-340b97bc90ff.png)

**Comment by dschaper** [comment]
Have you flushed the browser cache? Does the web populate when you log in as admin?

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the Community Help category on [Discourse Forum](https://discourse.pi-hole.net).

**Comment by ecdeveloper** [comment]
I'm having the same exact issue. Flushed browser cache. Logged in as admin. Same thing - empty stats, even though the Query log shows tons of records. @dschaper any hints?

**Comment by dschaper** [comment]
Yeah, open a new issue and fill out the template.

**Comment by ecdeveloper** [comment]
[Done](https://github.com/pi-hole/pi-hole/issues/4102)
