### ISSUE TITLE
FTL update fails because of supposed lack of SQLite PHP module

### ISSUE THREAD

**Issue by mpancorbo** [pi-hole/pi-hole#3809]
### Versions

 - Pi-hole version is v5.1.2 (Latest: v5.1.2)
 - AdminLTE version is v5.1.1 (Latest: v5.1.1)
 - FTL version is v5.0 (Latest: v5.2)

### Platform

- Raspbian GNU/Linux 10 (buster), Linux 5.4.51-v7+ armv7l GNU/Linux

- Platform:  Raspberry Pi 2 Model B Rev 1.1

### Expected behavior

After `pihole -up` a full upgrade of de pihole system.

### Actual behavior / bug

The process goes fairly until it fails at FTL update:
```
[I] pi@raspi: ~ » pihole -up     
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u6
  [✗] Aborting installation: No SQLite PHP module was found in APT repository.

  Unable to complete update, please contact Pi-hole Support
```

### Steps to reproduce

1. `pihole -up`

## Debug Token

- URL:  https://tricorder.pi-hole.net/oberbsbggg

### Additional context

Same problem as reported in #3744 

`SQlite`  module is properly installed:
```
[I] pi@raspi: ~ » sudo apt install php-sqlite3  
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
php-sqlite3 ya está en su versión más reciente (2:7.3+69).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 3 no actualizados.
```

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the Community Help category.

**Comment by dschaper** [comment]
Also note you are running `php` version 7.0 which is not in the Buster release.

```plain
*** [ DIAGNOSING ]: lighttpd version
[i] opt

*** [ DIAGNOSING ]: php version
[i] 7.0.33
```

**Comment by mpancorbo** [comment]
Ok. Thanks for the report.

**Comment by eehmke** [comment]
I have still the same issue with buster and php7.3. Agreed, I replaced lighttpd by apache, and run php-fpm. Should I revert to the standard setup? It used to work in the past.
