### ISSUE TITLE
Ads appear on tv.com even though they show as being blocked.

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#381]
##### Expected Behaviour:
Ads on tv.com should be blocked and show as appearing on /etc/pihole/gravity.list in the log file.

##### Actual Behaviour:
Ads from googleadservices.com can still be seen even though the log file shows them as being blocked.
```
Mar 12 10:55:31 dnsmasq[18326]: query[A] www.googleadservices.com from 192.168.1.137
Mar 12 10:55:31 dnsmasq[18326]: /etc/pihole/gravity.list www.googleadservices.com is 192.168.1.131
Mar 12 10:55:31 dnsmasq[18326]: query[AAAA] www.googleadservices.com from 192.168.1.137
Mar 12 10:55:31 dnsmasq[18326]: /etc/pihole/gravity.list www.googleadservices.com is 1241:9994:00rt:c4b:n16r:a06c:4bd2:32ej
```

##### Steps to reproduce this issue:
Ads appear on this page: http://www.tv.com/search?q=game+of+thrones

**Comment by Fedora-Core** [comment]
**Quote:**
```Text
: query[AAAA] www.googleadservices.com from 192.168.1.137
: /etc/pihole/gravity.list www.googleadservices.com is 1241:9994:00rt:c4b:n16r:a06c:4bd2:32ej
```

**?**
Has this [AAAA] log-entry been modified, before posting in this issue ?

**if**
This [AAAA] log-entry has NOT been modified.
**then**
What kind of IPv6 address is this, with non-hex characters ?
**else**
What are the results from an " IPv6 ping to www.googleadservices.com " when the Pi-hole is offline ?
Can it be "2404:6800:4008:c00::9a" ? { Source = [https://github.com/lennylxx/ipv6-hosts](url) }
This is not even close to the "1241:9994:xxxx" response.

**?**
Did you try this without the "Pi-Hole.IsWorking.OK" eye-candy ?

Greetings, F.C. 

{ _Joke:  F.C. is yet another IPv6 noob, even after reading this_ = }
[https://en.wikipedia.org/wiki/IPv6_address](url)

**Comment by dschaper** [comment]
Something is off, you can't have an IPv6 address like that. Are all of your IPv6 entries in `/etc/pihole/gravity.list` showing as that `32ej`? Can you re-run the install script if they are and see if that repairs the problem.

And there shouldn't be any correlation between IPv4 and IPv6 addresses. (The only possible correlation is with the MAC address, but most IPv6 implementations no longer use the MAC as part of their address as it was a security issue.)

IPv6 is fun!

**Comment by Mcat12** [comment]
Is this still a valid issue?

**Comment by keleftheriou** [comment]
I'm also seeing the same issue, ads appearing on http://www.tv.com/search?q=game+of+thrones. And I can see from the logs that some ads are being blocked whenever I load that page. FWIW, the IPv6 addresses I see are valid.

**Comment by keleftheriou** [comment]
It seems that somehow ads on this website are loaded from the google.com domain. Would this make them un-blockable using pi-hole, just like with ads on google.com itself?

This is an example url pulled into an iframe within the tv.com page:
https://www.google.com/afs/ads?q=game%20of%20thrones&lo=true&adpage=1&po=true&r=m&fexp=21404&client=cnet-tv-search&hl=en&type=0&oe=UTF-8&ie=UTF-8&format=p3%7Cn3&ad=n3p3&nocache=1831464310443083&num=0&output=uds_ads_only&v=3&adlh=on&adext=as1%2Cl1%2Csr1&bsl=10&u_his=2&u_tz=-420&dt=1464310443084&u_w=1440&u_h=900&biw=1440&bih=422&psw=1440&psh=1704&frm=0&uio=uv3cs1lHsr1po1lo1sl1-st16-st16&jsv=16695&rurl=http%3A%2F%2Fwww.tv.com%2Fsearch%3Fq%3Dgame%2Bof%2Bthrones

**Comment by Mcat12** [comment]
You could add a few lines to the lighttpd config to redirect any similar URLs, but that kind of ad is hard to block with DNS.

**Comment by keleftheriou** [comment]
@Mcat12 Is it hard, or *literally impossible* to block that kind of ad with DNS manipulation?

**Comment by dschaper** [comment]
Not impossible if you allow blocking Google.com, but for all intents and purposes, yes, it would be functionally impossible with a pure resolver only approach.

**Comment by Mcat12** [comment]
When I opened that link in a new tab, it is blank. The source shows that it is loading from other google ad domains which are already blocked, such as `www.googleadservices.com`.

**Comment by Mcat12** [comment]
So it may be blocked anyways

**Comment by jacobsalmela** [comment]
Not really a bug.  Just an enhancement to block more ads.  Closing.
