### ISSUE TITLE
Dashboard doesn't display Queries Blocked or Percent Blocked after update

### ISSUE THREAD

**Issue by Pretzal13** [pi-hole/pi-hole#3812]
Versions
Pihole V5.1.2
web interfacce v5.1.1
FTL v5.2

platform
Portainer 1.24.0

![Screenshot_2020-10-23 Pi-hole - pihole](https://user-images.githubusercontent.com/52223542/96962939-58b83900-154f-11eb-8035-50312122c869.png)

Client activity, Query type and Queries answered all have the spinning refresh icon and never complete. Queries blocked and Percent blocked have 3 dashes.

Previous version (5.0 I think) worked ok with no issues. Only since updating is it an issue.

Sorry not an IT expert so hopefully this is adequate to be able to identify my problem.

**Comment by yubiuser** [comment]
Please clear your browser's cache

**Comment by Pretzal13** [comment]
Thanks this worked. I haven’t cleared it in forever 😬
Appreciate your consideration in responding
