### ISSUE TITLE
raspbian pihole-FTL fails to update from 4.1.2 to latest

### ISSUE THREAD

**Issue by ttqf** [pi-hole/pi-hole#3813]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  4.1.2

### Platform

- OS and version:  Raspbian 9.13

- Platform:  Raspberry pi 3b+

### Expected behavior

update FTL to latest using sudo pihole -up results in the following:

### Actual behavior / bug

pi@server:$ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Enabling universe package repository for Ubuntu Bionic
  [✓] Backed up current configuration to /etc/apt/sources.list.backup
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 96, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch

  Unable to complete update, please contact Pi-hole Support

## Debug Token

- URL:  https://tricorder.pi-hole.net/fbmll25dsx

**Comment by dschaper** [comment]
You're running Raspbian and have repositories for Ubuntu, this is an OS issue. 

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by ttqf** [comment]
yep.. so i had to remove those repositories from the sources.list and run again apt update. commenting them didn't help.
Thanks for pointing this out!
