### ISSUE TITLE
Endless sl query from PiHole container until it crashes

### ISSUE THREAD

**Issue by glamax13** [pi-hole/pi-hole#3820]
### Versions
- Pi-hole:  v5.1.2 (Latest: v5.1.2)
- AdminLTE:  v5.1.1 (Latest: v5.1.1)
- FTL:  v5.2 (Latest: v5.2)

### Platform
- OS and version:  Ubuntu 20.04
- Platform:  Raspberry Pi, Docker

### Expected behavior

Stay awake and answer DNS request.

### Actual behavior / bug

Make request to "sl" domain then crashes

### Steps to reproduce

1. docker-compose up -d

## Debug Token

- URL:  https://tricorder.pi-hole.net/rwqujq8mjk

### Screenshots

1 - tcpdump -i eth0 port 53 -A
![1-tcpdump_from_the_container](https://user-images.githubusercontent.com/40393727/97371427-7835c580-18b1-11eb-9fed-741b2c85fda6.png)

2 - Admin pannel
![2-pihole_sl_requests](https://user-images.githubusercontent.com/40393727/97371383-59373380-18b1-11eb-9dd3-184fd7b08381.png)

3 - Docker compose
![3-docker_compose](https://user-images.githubusercontent.com/40393727/97371627-f1cdb380-18b1-11eb-8bc5-5dc4f48b31bb.png)

### Additional context

!!! My instance is public so i can access it with whatever address my VPN gives me.

I had a few clients that made an insane number of requests but it doesn't seems to be the case because the requesting IP is the container itself.

All was working flawlessly for weeks by now but suddenly since yesterday every-time i spin up a pihole instance it goes crazy and make an insane number of requests. I tried to drop the volumes, pull the image again nothing helped. It broke in less than a day.

Am i the only one in this case?

**Comment by dschaper** [comment]
As a standing practice, Pi-hole does not provide assistance or support to nodes running as public open resolvers. 

If being publicly accessible was not your intention then please open a ticket at https://discourse.pi-hole.net. If you intend to be running a public DNS server then you will need to find other assistance.

**Comment by dschaper** [comment]
You're being used in a DOS attack against the root servers. I suggest taking everything down until you understand why that's a horrible idea.

**Comment by glamax13** [comment]
Yes i thought about that ~~but i what does public DNS have against that? IP tracking? Isn't there a way to set a query rate?~~ could you guide me to a document about why not make it public please? I couldn't find any. All i found was that some could not be password protected and get takeover.

I took it down ASAP thank you for the warning and the assistance.

**Comment by dschaper** [comment]
Just search for 'why open resolvers are bad' and you'll get plenty of things to read.

**Comment by glamax13** [comment]
I'll keep it private for now on and i'll try my best to make it work with my VPN without making it public.
Thank you very much and best of luck in the future!
