### ISSUE TITLE
/etc/pihole/logrotate is overwritten on upgrade

### ISSUE THREAD

**Issue by danradom** [pi-hole/pi-hole#3822]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  Linux LXC

### Expected behavior

_A clear and concise description of what you expected to happen._
When pihole is updated, /etc/pihole/logrotate is overwritten.  Ideally this would be handled similarly to how package managers handle existing configuration files.
### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce
customize /etc/pihole/logrotate and then upgrade

1. edit /etc/pihole/logrotate
2. upgrade pihole
3. review /etc/pihole/logrotate
4. See edits are gone
## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

see https://www.reddit.com/r/pihole/comments/jjasvs/logrotate_config_file_gets_overwritten_on_each/ for details

**Comment by dschaper** [comment]
Thanks!

**Comment by eyeteajay** [comment]
This also happened to me while upgrading from pihole 5.1.2 -> 5.2.4 on a raspberry pi.
uname -a
`Linux raspi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 arm71 GNU/Linux`

I had changed the rotate time to 3 for pihole.log, but after the update it reverted back to 5.

**Comment by dschaper** [comment]
Sorry, I agree completely that this should not happen.

**Comment by eyeteajay** [comment]
> Sorry, I agree completely that this should not happen.

No problem, I was just reporting that it's still happening on a different os for your investigation.

**Comment by yubiuser** [comment]
Fixed with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
