### ISSUE TITLE
Pi-hole Treats Whitelisted Domains as Blacklisted Domains

### ISSUE THREAD

**Issue by YouveGotMeowxy** [pi-hole/pi-hole#3823]
### Versions

  - Pi-hole version is v5.1.2 (Latest: v5.1.2)
  - AdminLTE version is v5.1.1 (Latest: v5.1.1)
  - FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Official Docker Container

- Platform:  Docker

### Expected behavior

_A clear and concise description of what you expected to happen._

When I add a domain to my whitelist, it gets whitelisted.

### Actual behavior / bug

_A clear and concise description of what the bug is._

It actually gets blacklisted.

### Steps to reproduce

1. Go to the whitelist page, add a domain to whitelist. in this case I used RegEx: `([a-z0-9A-Z]+\.mydomain\.rocks)`
2. Try to visit any domain that matches that regex.

## Debug Token

- URL:  https://tricorder.pi-hole.net/h450lh0y5g

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/39491297/97559652-b7e0d800-19ab-11eb-8c45-69253bb8a2de.png)

![image](https://user-images.githubusercontent.com/39491297/97560328-81578d00-19ac-11eb-8fef-e8e255a0ca80.png)

![image](https://user-images.githubusercontent.com/39491297/97559710-c929e480-19ab-11eb-9a8e-96a4d5c691b8.png)

### Additional context

_Add any other context about the problem here._

One interesting thing is, I got this blocked domain page by trying to visit my Pi-hole Admin page via a Nginx reverse proxy, even though I currently have the computer/router on my LAN set to not even use my Pi-hole for my DNS resolutions. (I set them to use a regular DNS, CloudFlare instead).

Also a side note: When I tried to simply add the domain to my whitelist with the button on the 3rd page in the screenshots above, the page just kinda did a refresh, with no real user feedback, and the domain didn't actually get added to the whitelist.

**Comment by PromoFaux** [comment]
I can confirm I'm seeing a similar behaviour. @DL6ER is this an as-yet unreported bug on FTL, or known about?

**Comment by PromoFaux** [comment]
That said, using the same regex as you, and trying to lookup `test.mydomain.rocks` shows it being correctly forwarded:

![image](https://user-images.githubusercontent.com/1998970/97560995-63ebe880-19d7-11eb-81da-adf2d6f226b1.png)

**Comment by YouveGotMeowxy** [comment]
> That said, using the example regex you provided, and trying to lookup `test.mydomain.rocks` shows it being correctly forwarded:

I added another bit of info that _may_ (?) have something to do with the strange behavior? (in the Additional Context) section.

**Comment by PromoFaux** [comment]
AH, right.. yes that is absolutely the issue. I think this is a false positive. The domain is not actually blocked, you're just seeing the block page. 

Can you try switching out the `BLOCKINGMODE` to `NULL`, instead of `IP` and see if that makes a difference?

https://docs.pi-hole.net/ftldns/blockingmode/

**Comment by YouveGotMeowxy** [comment]
> AH, right.. yes that is absolutely the issue. I think this is a false positive. The domain is not actually blocked, you're just seeing the block page.
> 
> Can you try switching out the `BLOCKINGMODE` to `NULL`, instead of `IP` and see if that makes a difference?
> 
> https://docs.pi-hole.net/ftldns/blockingmode/

@PromoFaux Ty for the help, I'm pretty new to all this stuff; is there a way to edit the file within the container, and not having to copy files back and forth from outside the container? When I try to edit it form within the container I get this:

![image](https://user-images.githubusercontent.com/39491297/97565734-36417800-19b4-11eb-9c88-8e21a7edad5b.png)

Also, is this weird? The page you linked says `NULL` is the PH default, and when I cat that file, it only shows this (notice no specific setting to `IP` blocking mode):

![image](https://user-images.githubusercontent.com/39491297/97566276-6ab53400-19b4-11eb-8107-87274f4a9553.png)

**Comment by PromoFaux** [comment]
Hold up. If your Pi-hole instance is not set to blocking mode IP, then you've got something squiffy with your rev proxy.

What I think is happening is that whatever the domain you are trying to resolve is, is resolving to the same IP as the device the Pi-hole container is on.

Note that Pi-hole is listening on port 80, so a request coming in for that IP address is going to show the block page, regardless of blocking mode.

You'll either need to have NGINX listening on a different device/interface, or change the port on which Pi-hole is listening.

I think this is more of a configuration issue than a bug, and would invite you to open a thread on our user forums for some pointers from the community - if you don't mind :) https://discourse.pi-hole.net.

One other thing I will note, per your debug log - you have some invalid entries in your white/blacklist. They need to be _domains_ not _urls_

![image](https://user-images.githubusercontent.com/1998970/97572451-293a7e00-19e0-11eb-9776-7bba19ae32e2.png)

**Comment by YouveGotMeowxy** [comment]
> Hold up. If your Pi-hole instance is not set to blocking mode IP, then you've got something squiffy with your rev proxy.
> 
> What I think is happening is that whatever the domain you are trying to resolve is, is resolving to the same IP as the device the Pi-hole container is on.
> 
> Note that Pi-hole is listening on port 80, so a request coming in for that IP address is going to show the block page, regardless of blocking mode.
> 
> You'll either need to have NGINX listening on a different device/interface, or change the port on which Pi-hole is listening.
> 
> I think this is more of a configuration issue than a bug, and would invite you to open a thread on our user forums for some pointers from the community - if you don't mind :) https://discourse.pi-hole.net.
> 
> One other thing I will note, per your debug log - you have some invalid entries in your white/blacklist. They need to be _domains_ not _urls_
> 
> ![image](https://user-images.githubusercontent.com/1998970/97572451-293a7e00-19e0-11eb-9776-7bba19ae32e2.png)

@PromoFaux Thanks for pointing that last bit out; damn, I was thinking (hoping!) that PH also behaved in a similar fashion as say, uBlock, and I could also use it to block individual annoyances like ad images. :/ 

So PH is *strictly domains* and nothing but the entire domain, huh?

Regarding the rest, I think you're right; all of these containers are running on the same machine (my Nginx container as well as my Pi-hole container). I do have my domain set to use port 3999 and I have to add that to all of my RP URLS, but the proxy configs themselves just pass them to the normal ports inside the containers. 

I'm not really network savvy enough I think, to go screwing around with changing the port that PH listens to so it doesn't conflict with the Nginx port(s); if I simply change that port to say 90, will it affect anything else in a negative way?

**Comment by PromoFaux** [comment]
You're not using the IP blocking mode, so Pi-hole's web interface doesn't _need_ to be listening on port 80. You should just be able to change the port on the container and map it to port 80 inside the container (e.,g `-p 8080:80` or in the `ports` section if you're using `docker-compose`)

**Comment by YouveGotMeowxy** [comment]
Gave changing the web ui's port to 90 in my compose, but that didn't solve it. I still get the same screen when trying to visit the admin page via reverse proxy.

**Comment by PromoFaux** [comment]
Hmmm, I'm not sure, then... I'm not the best when it comes to docker configuration.. everything I have just works (and I usually have no idea why 😉 

Please try asking on the community forum, someone may have a similar set up to you.
