### ISSUE TITLE
"Indefinite" Disable option is dependent on previously set custom timer

### ISSUE THREAD

**Issue by benliepert** [pi-hole/pi-hole#3829]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi 3 Model B Rev 1.2

### Expected behavior
Selecting the "indefinite" disable option will disable indefinitely, with no associated timer

### Actual behavior / bug
I created a custom timer (10m). At 2m left, I re-enabled. I used the "indefinite" disable option after, and a timer appeared with the 2m I had left on my custom timer. I would expect the indefinite option not to be dependent on any previously set custom timer.

### Steps to reproduce

1. Create custom disable timer 
2. Let some of it pass
3. Enable the pi (by clicking 'enable')
4. Select the "indefinite" disable option
5. Pi will be disabled with whatever time was left on the custom timer (and will re enable when this time is up)
(This is reproducible 100% of the time for me)

## Debug Token

- URL:  https://tricorder.pi-hole.net/65i8drspex

**Comment by yubiuser** [comment]
This was fixed by https://github.com/pi-hole/AdminLTE/pull/1863 and released to master in 
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544/1
