### ISSUE TITLE
[Feature request] Official support of Arch Linux

### ISSUE THREAD

**Issue by David-H-1** [pi-hole/pi-hole#3831]
A significant portion of users willing to block Internet advertisements and trackers are on Arch Linux. Why don't you officially support Arch Linux? Please support Arch Linux if possible.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by dschaper** [comment]
https://aur.archlinux.org/packages/pi-hole-server/#pinned-633053

The Arch package is heavily modified to get it to run on Arch. None of the developers are able or willing to provide the work to maintain it. It's maintained by the packagers in the AUR.
