### ISSUE TITLE
Static DNS need a flush to be resolved

### ISSUE THREAD

**Issue by mcnahum** [pi-hole/pi-hole#3833]
### Versions

 Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  DietPi v6.33.3 

- Platform:  RPi 3 Model B+ (armv7l)

### Actual behavior / bug

PI-Hole took care of DNS & DHCP.
The device is the only one who manage it on the network

I have a local DNS record

nas.mydomain.net --> 192.168.1.15

nas.mydomain.net exist also outside with a public IP

The IP 192.168.1.15 it's a fixed IP
the IP 192.168.1.15 is reserved on the DHCP server even if fixed

nslookup nas.mydomain.net
Name:	nas.mydomain.net
Address: 192.168.1.15

ping nas.mydomain.net
PING toto.dyndns.org (158.15.xxx.xxx): 56 data byte (my external IP)

There is a CNAME externally who this to convert that I set

**Flushing the DNS locally**
ping nas.mydomain.net
PING nas.mydomain.net (192.168.1.15): 56 data byte

All good for a variable amount of time and the ping will respond badly again...
of course my issue is not PING it's accessing website behind the IP

### Expected behavior / bug

not have to flush, the PING is always using the proper value

### Steps to reproduce

see before

## Debug Token

- URL:  https://tricorder.pi-hole.net/koy3q832bu

### Additional context

IP and name changed here for public view

**Comment by dschaper** [comment]
What OS is the client that is seeing the external IP? Does it have any other DNS servers that it can access and use? 

Have you made any manual modifications to `/etc/pihole/setupVars.conf`? 

What does the log show for responses when the DNS returns the external IP address? Are they forwarded to an upstream DNS server or answered from Pi-hole cache?

**Comment by mcnahum** [comment]
OS is macOS Big Sur.(up to date)
There is no other DNS on the network and and nslookup show it's going to pi-hole and ping (and web browsing) should use that one I guess

I didn't touch setupVars.conf

What is the log file you are suggesting to check? Missed that one...

**Comment by dschaper** [comment]
`setupVars.conf` has an entry for `IPV4_ADDRESS` that is malformed, so it's been modified somehow.

Check the admin page interface on the query log and see what responses you are getting for the domain when it returns the correct and incorrect answers. 

Check `scutil --dns` and make sure only the Pi-hole DNS is listed, there can be no "secondary" or "backup" DNS servers.

**Comment by mcnahum** [comment]
1-Does I need to do something to fix setupVars.conf?
2- Yes I can see it's forward it to the toto.dyndns.org  outside
3-  scutil --dns display the below (192.168.1.10 is Pi-Hole IP):

DNS configuration

resolver #1
  search domain[0] : clients.mydomain.net
  nameserver[0] : 192.168.1.10
  if_index : 4 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : clients..mydomain.net
  nameserver[0] : 192.168.1.10
  if_index : 4 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  search domain[0] : clients..mydomain.net
  nameserver[0] : 192.168.1.10
  if_index : 7 (en1)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

**Comment by dschaper** [comment]
> 1-Does I need to do something to fix setupVars.conf?

I'd run `pihole -r` and check 'repair' just to clean it up.

> 2- Yes I can see it's forward it to the toto.dyndns.org outside

It forwards both times? When it resolves internally and externally?

I notice that there's Dropbear running, why did you change the default SSH daemon? Is this something that DietPi does? @MichaIng

**Comment by MichaIng** [comment]
Yes, DietPi images are shipped with Dropbear by default instead of OpenSSH, although it can be changed easily. Dropbear consumes a fraction of memory of usually sufficient features, and we generally like to promote underdogs, where applicable, same with Lighttpd, which we ship by default when a webserver is required, like Pi-hole does.

**Comment by mcnahum** [comment]
1- did the repair ... but still the same issue

2- no only when it go externally, as soon as I flush the DNS all is ok .. for nothing more than a minute

I read that DietPi was the best OS for Rpi  to host Pi-hole...

**Comment by dschaper** [comment]
Okay, I really don't know why things would shift, what exactly do you see on the web admin interface when the two different conditions happen? Can you post screenshots with any identifying information scribbled out? I'd like to see the Type, Domain, Status and Reply columns from both external and internal results, no need to see clients.

**Comment by mcnahum** [comment]
So I guess this is what happening when it's wrong:
![image](https://user-images.githubusercontent.com/30963862/98487133-b9b76080-2221-11eb-8815-af17e79baab5.png)

and that one when it's working just after a flush and before is not working...

![image](https://user-images.githubusercontent.com/30963862/98487676-9b9f2f80-2224-11eb-8562-74108b80a031.png)

**Comment by dschaper** [comment]
I don't see any requests for the nas in the top output. 

I'll be honest, I don't know what the images are showing me. @PromoFaux or @DL6ER can you step in please?

**Comment by mcnahum** [comment]
Ok so I did some Wireshark to see more and it's strange ... the issue only come when there is an https request to the pi-hole done.
when I open my browser and navigate to https://nas.mydomain.net, the pi-hole reply:

nas.mydomain.net: type CNAME, class IN, cname toto.dyndns.org
    Name: nas.e-mydomain.net
    Type: CNAME (Canonical NAME for an alias) (5)
    Class: IN (0x0001)
    Time to live: 3599 (59 minutes, 59 seconds)
    Data length: 20
    CNAME: toto.dyndns.org

**Comment by dschaper** [comment]
`nas.mydomain.net` and `nas.e-mydomain.net` are correct, or is one a typo?

What are you using as an https configuration, Pi-hole does not configure `https` out of the box, that requires external changes.

**Comment by mcnahum** [comment]
it's a typo... changing the real name ... sorry,

To clarify, my site, hosted on nas.mydomain.net, have a certificate and I'm accessing it with https. I didn't touch the pihole website to move it to https as it was not recommanded

**Comment by dschaper** [comment]
How are you proxying the traffic from the TLS termination to the Pi-hole port 80? Is it possible the proxy is using an outside DNS server and doing the redirection on it's own?

**Comment by dschaper** [comment]
>What is strange ... is Safari is doing it but not Edge or Chrome on macOS...

Sorry, didn't see this edit. 

That tells me that it's a client configuration issue and not a server side issue.

**Comment by mcnahum** [comment]
it seams, now that we know more, that's I'm not the only one having the issue:
https://apple.stackexchange.com/questions/343618/alternate-dns-resolution-for-safari-on-macos

**Comment by mcnahum** [comment]
so the workaround is to turn off IPV6 but it's not really a solution ... I'm not sure I get the root cause .. is it pi-hole who have an issue with IPV6?

**Comment by MichaIng** [comment]
I'm also trying to understand the underlying issue:
- DHCPv6 is indeed pretty uncommon, although could make sense if one wants to assure that certain values are applied to clients. But Pi-hole is DHCPv4-only, right?
- Else, common is IPv6 auto-configuration (SLAAC), which then based on RAs (router advertisements), which tell the clients the gateway, IPv6 prefix (to create their own IPv6 address from) and CAN include IPv6-capable DNS nameserver entries as well, but that seems to be not always included/reliable. But Pi-hole does not do RAs, right?
- So the result might be that clients get/configure an IPv6 DNS server (aside of the DHCPv4 applied Pi-hole entry) entry based on the RAs from the router and by this resolve around Pi-hole? But when given a hostname, how does a client know whether to use an IPv4 or IPv6 nameserver entry in the first place? Also nearly every DNS server can resolve both anyway, so no point in having two entries.

Flushing DNS might simply clear the RA-induced IPv6 DNS entry from client/OS until the next RA happens, which should be within 30 minutes as that is the default timeout for IPv6 gateways promoted via RAs.

So the issue would be basically conflicting nameserver entries due to DHCPv4 from Pi-hole and RAs from the router/gateway. The RAs must stay if IPv6 should stay functional, so the solution then would be to either somehow tell the router to send Pi-hole as static DNS server, to be send via RAs to clients, or to tell it not to send any DNS entry via RAs. The first should be possible, not sure about the second.

But that is all based on the impression that in case of falsely resolved `nas.mydomain.net`, Pi-hole did indeed NOT resolve it. At least in the output above I cannot clearly see that Pi-hole gets a request to resolve `nas.mydomain.net` and resolves it with the unwanted public IP.

At least timing and RAs in general could be checked via:
```
tcpdump -n -i eth0 icmp6 and ip6[40] == 134
```
This monitors incoming requests through eth0 interface, filters them by ICMPv6 protocol and the last filters those by RAs (don't ask me what the numbers are but it works 😅).
You could run that on a Linux system/client, watch out for RAs from your router in general and check whether indeed after flushing DNS, correct resolution works until another RA arrives.

**Comment by dschaper** [comment]
>  I'm not sure I get the root cause

If it only happens with one browser then it's the browser that is an issue.

**Comment by mcnahum** [comment]
@dschaper yes it's how the browser interact with Pi-Hole on IPV6... I'm not sure we can say It's Safari, or It's PiHole or It's IPV6 .. it's clearly how the 3 work together... 

@MichaIng I let the command running on my Ubuntu device for 1 hour without any RA arriving...

**Comment by MichaIng** [comment]
In case of DoH it's clear that browsers do not use the system resolver, but if DoH is not enabled, it would be a shame if a browser would ignore the system resolver config.

Just to be sure, Pi-hole is the only entry in `/etc/resolv.conf` on the affected macOS and the network interface on the Ubuntu system is `eth0`? In case, `tcpdump -n icmp6 and ip6[40] == 134` works as well to listen on all interfaces.

**Comment by mcnahum** [comment]
yes, tcpdump still don't see any RA...

**Comment by MichaIng** [comment]
Okay, then it has nothing to do with RAs. Although I'm wondering how clients then get the IPv6 route 🤔. Probably there is simply none and all outgoing requests are done via IPv4? Did you actually verify that disabling IPv6 on the macOS solves (works around) the issue? However, this indeed seems to be something to report to Safari/Apple.

**Comment by mcnahum** [comment]
not until now, I set it with Link.Local only but Safari still resolving it... I will try to fully disable it but it's not the best...

**Comment by mcnahum** [comment]
I can confirm that's no fixing the issue ..

**Comment by MichaIng** [comment]
I'm also out of ideas. Either Apple support or apple.stackexchange.com will be hopefully able to help, adding the information we gathered here. The main issue is that Safari does not anyways use the system resolver, if I get it right, although you can verify. Your logs screenshot for the failing requests contain PTR requests only which are for reverse resolving, strangely containing the local Pi-hole IP (?), so not sure what this is about. But I think those are not related to the actual hostname access from Safari, are they (retry and compare timestamps)?

**Comment by yubiuser** [comment]
@mcnahum 

Any news on that? Does the issue still persist?

**Comment by mcnahum** [comment]
unfortunately yes  ... I still have to flush the DNS ... and if I want to do an ssh to a local device I must use the IP ...
