### ISSUE TITLE
Domain redirection ?

### ISSUE THREAD

**Issue by KatzeMau** [pi-hole/pi-hole#3834]
Can you add a feature that allow to redirect a AD/Blocked domain to another webpage ?
Example.: google.com to duckduckgo.com 
So all DNS requests that request google go to duckduckgo ?

**Comment by yubiuser** [comment]
Feature requests should go to https://discourse.pi-hole.net/c/feature-requests/8.

The next version of pihole will very likely contain the ability to set local CNAME records. So you could resolve `google.com` locally to `duckduckgo.com`

**Comment by PromoFaux** [comment]
> So you could resolve `google.com` locally to `duckduckgo.com`

I don't _think_ this would work, would it? The browser would (rightly) complain about the certificate being invalid, right?

**Comment by yubiuser** [comment]
Chrome does complain, firefox not.

**Comment by dschaper** [comment]
Then that's a severe problem with Firefox accepting forged TLS certs.

So no, redirecting https://google.com to https://duckduckgo.com will not work. And google is on the preload list so any visit to http://google.com will be automatically redirected to https://google.com.

**Comment by yubiuser** [comment]
Ok, now it's even working in chrome, too.
![Bildschirmfoto zu 2020-11-07 13-29-48](https://user-images.githubusercontent.com/26622301/98441349-f722cd80-20fd-11eb-850c-d015b1682e3a.png)
![Bildschirmfoto zu 2020-11-07 13-29-56](https://user-images.githubusercontent.com/26622301/98441350-f853fa80-20fd-11eb-982e-7b2ea2480552.png)

**Comment by dschaper** [comment]
So, you typed `http://google.com` and it took you to `https://duckduckgo.com` without any signs or notices?

I guess since it says "https://duckduckgo.com" as the URL it works for that, but any links like `google.com/blahblah` would not work. I can't see where this would be helpful at all, since only bare domains would work and nothing would show the original domain name.

**Comment by yubiuser** [comment]
>So, you typed http://google.com and it took you to https://duckduckgo.com without any signs or notices?

Yes.

> I can't see where this would be helpful at all

Me neither, but that's how I understood
> Example.: google.com to duckduckgo.com
