### ISSUE TITLE
Teleporter only imports a single item of the Local DNS Records

### ISSUE THREAD

**Issue by Kareltje1980** [pi-hole/pi-hole#3835]
### Versions
```
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)
```

### Platform
Fresh install of Raspbian lite, with a upgrade/update

### Expected behavior
I have a teleporter of another install. It contains ~30 local dns records. I expect the teleport import thingie to import all 30.

### Actual behavior / bug
I checked the teleport file, and there is a list with all 30 dns records. When importing, it only imports a single item (the first). 

### Import log
```
Processed adlist (7 entries)
Processed adlist group assignments (7 entries)
Processed blacklist (exact) (0 entries)
Processed blacklist (regex) (1 entries)
Processed client (1 entries)
Processed client group assignments (0 entries)

```

Let me know if you need something.

**Comment by dschaper** [comment]
>Let me know if you need something

Yes, the debug token we asked for in the template.

**Comment by Kareltje1980** [comment]
https://tricorder.pi-hole.net/hjeerg9xjb

**Comment by dschaper** [comment]
And the debug log from the other install please?

**Comment by Kareltje1980** [comment]
https://tricorder.pi-hole.net/jzhjjhyars

**Comment by dschaper** [comment]
Both logs show only 1 client, are you asking about clients and groups? Or entries in `/etc/pihole/local.list`?

Also, blacklisting the root domain `.` is a very bad idea.

**Comment by Kareltje1980** [comment]
This is about the _local DNS records_. If I look in the webinterface there are ~30 entries, also in file from teleporter there I see 30 entries in the file `custom.list`. 

The blacklisting of everything was a test if I could disable the while network/internet to make sure the kids would come eat :)

**Comment by PromoFaux** [comment]
Ah, it might be the import part of local DNS records was missed when the feature was added. I'll do some digging....

**Comment by PromoFaux** [comment]
Ah. Search is your friend! :)

There is an open issue here: https://github.com/pi-hole/AdminLTE/issues/1537, so closing as duplicate

**Comment by PromoFaux** [comment]
(and, actually, just testing this, it appears to be fixed in next release)
