### ISSUE TITLE
ad-list retrieval fails when there are special characters in the URL

### ISSUE THREAD

**Issue by frollic** [pi-hole/pi-hole#3839]
### Versions
Pi-hole v5.1.2
Web Interface v5.1.1
FTL vDev (fix/shm_per_client_regex_boundary_checks, vDev-9b0b536)

### Platform
- OS and version:  CentOS 7.2
- Platform:  x86_64

### Expected behavior

Seems the URL interpretation is broken when URLs contain special characters.

### Actual behavior / bug

When updating the ad-block list, sometimes empty file is beeing returned as the outcome.

  [i] Target: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  [✓] Status: Retrieval successful
  [i] Received 694 domains

  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  [✓] Status: Retrieval successful
  [i] **Received empty file**: using previously cached list

The lists above *appear* to be identical to me, in formating, one of them works, the other one doesn't.
Only differance seems to be that one contain 0.0.0.0 instead of 127.0.0.1

I grabbed the content of the yoyo.org list, and stored it on my own server, with a plain name like http://abc.de/a.txt.
This time pi-hole was able to import the list w/o any issues at all.

  [i] Target: http://abc.de/a.txt
  [✓] Status: Retrieval successful
  [i] Received 3562 domains

The only thing I can imagine causing this, is the URL beeing misinterpreted because of the special chars in it.

### Steps to reproduce

Add 

https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

to the adlists, run Update gravity or pihole -g.

**Comment by dschaper** [comment]
![Screenshot 2020-11-10 072018](https://user-images.githubusercontent.com/2782850/98693499-3a12ba00-2325-11eb-81c9-8843b4962596.png)

**Comment by frollic** [comment]
![image](https://user-images.githubusercontent.com/7432497/98696659-5be75d80-2374-11eb-9e4b-6cf1ea0da5bf.png)
Which tells us what exactly .... ?

some component outside of pihole have bug ?

**Comment by dschaper** [comment]
> Which tells us what exactly .... ?

That I was able to use the URL with special characters and get 3562 domains from it.

What happens if you try to `curl` those URLs from the command line on the Pi-hole device?

**Comment by frollic** [comment]
It works, I get the content of the hosts file in the link.

**Comment by yubiuser** [comment]
```
  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  [✓] Status: Retrieval successful
  [i] Received 3562 domains

```

**Comment by dschaper** [comment]
You can try `sudo bash -x /opt/pihole/gravity.sh` and see if there is additional debugging information displayed.

**Comment by frollic** [comment]
`
+ (( i++ ))
+ (( i < 4 ))
+ url='https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
+ domain=pgl.yoyo.org
+ saveLocation=/etc/pihole/list.3.pgl.yoyo.org.domains
+ activeDomains[$i]=/etc/pihole/list.3.pgl.yoyo.org.domains
+ agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36'
+ case "${domain}" in
+ cmd_ext='-d mimetype=plaintext -d hostformat=hosts'
+ echo -e '  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
+ local regex
+ regex='[^a-zA-Z0-9:/?&%=~._()-;]'
+ [[ https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext =~ [^a-zA-Z0-9:/?&%=~._()-;] ]]
+ gravity_DownloadBlocklistFromUrl 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' '-d mimetype=plaintext -d hostformat=hosts' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 9 /etc/pihole/list.3.pgl.yoyo.org.domains /tmp/tmp.x02V29H843.gravity
+ local 'url=https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' 'cmd_ext=-d mimetype=plaintext -d hostformat=hosts' 'agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' adlistID=9 saveLocation=/etc/pihole/list.3.pgl.yoyo.org.domains target=/tmp/tmp.x02V29H843.gravity
+ local heisenbergCompensator= patternBuffer str httpCode success=
++ mktemp -p /tmp --suffix=.phgpb
+ patternBuffer=/tmp/tmp.RK49QVNXQ0.phgpb
+ [[ -r /etc/pihole/list.3.pgl.yoyo.org.domains ]]
+ [[ https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext != \f\i\l\e* ]]
+ heisenbergCompensator='-z /etc/pihole/list.3.pgl.yoyo.org.domains'
+ str=Status:
+ echo -ne '  [i] Status: Pending...'
  [i] Status: Pending...+ blocked=false
+ case $BLOCKINGMODE in
++ grep 0.0.0.0 -c
++ dig pgl.yoyo.org +short
+ [[ 0 -ge 1 ]]
+ [[ false == true ]]
++ curl -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' -o /tmp/tmp.RK49QVNXQ0.phgpb
+ httpCode=200
+ case $url in
+ case "${httpCode}" in
+ echo -e '\r  [✓] Status: Retrieval successful'
  [✓] Status: Retrieval successful
+ success=true
+ [[ true == true ]]
+ [[ 200 == \3\0\4 ]]
+ [[ -s /tmp/tmp.RK49QVNXQ0.phgpb ]]
+ echo -e '  [i] Received empty file: using previously cached list'
  [i] Received empty file: using previously cached list
+ echo ''
`

**Comment by dschaper** [comment]
Is your `/tmp` directory full or preventing writes for some reason?

**Comment by dschaper** [comment]
You can try 
```
curl -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' -o /tmp/tmp.RK49QVNXV0.phgpb
```
And then `cat /tmp/tmp.RK49QVNXV0.phgpb` to see what is there?

**Comment by frollic** [comment]
No /tmp is located at / , so there's plenty of room.

The curl command you asked me to test returned nothing, no file was created.

if I remove the -s, I get 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    35    0     0  100    35      0     62 --:--:-- --:--:-- --:--:--    62

If I remove *all* params but the URL and the -o, I get 

[root@proxy tmp]# curl  'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' -o /tmp/tmp.RK49QVNXV0.phgp                                                                            
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                Dload  Upload   Total   Spent    Left  Speed
100 94305    0 94305    0     0   136k      0 --:--:-- --:--:-- --:--:--  136k

So it seems my curl doesn't like the parameters passed.

curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

[root@proxy tmp]# rpm -qa | grep curl |sort
curl-7.29.0-57.el7_8.1.x86_64
libcurl-7.29.0-57.el7_8.1.x86_64

Judging from https://curl.se/docs/releases.html its's a *pretty* old release, almost 7 years.

**Comment by PromoFaux** [comment]
Can we get a debug log, please? `pihole -d`

Cheers

**Comment by frollic** [comment]
Token is https://tricorder.pi-hole.net/bu5ht787p1

**Comment by PromoFaux** [comment]
```
[80] is in use by sniproxy (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 sniproxy (IPv6)
```

I've no experience of running a proxy server - but could this be causing issues here? Is the `curl` request going direct to the source of the list, or is it going via your proxy?

**Comment by frollic** [comment]
Hi,

The proxy doesn't touch outgoing traffic, only incoming, 
It "bounces" traffic to bypass US geo locking.

**Comment by frollic** [comment]
Semi upgraded the CentOS to 8, and had a new curl installed, still having the same issue though ....

curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1c zlib/1.2.7 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

However, 

removing the **-d hostformat=hosts** the issue ....

**Comment by dschaper** [comment]
I don't think it's related to CentOS's `curl` version, @bcambl has this come up before?

**Comment by dschaper** [comment]
Run 
```
curl -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
```

and 
```
curl -I -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
```

**Comment by frollic** [comment]
(removed the -s)

[root@proxy tmp]curl -I  -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
Warning: You can only select one HTTP request method! You asked for both POST
Warning: (-d, --data) and HEAD (-I, --head).


[root@proxy tmp]# curl -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
304[root@proxy tmp]#

**Comment by bcambl** [comment]
tested via containers `centos:centos7.2.1511` and `centos:7` with same results:

```
[root@0bdc3ca6adce /]# curl -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{htcode}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' | wc -l
3576
[root@0bdc3ca6adce /]# curl -I -s -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' | wc -l
0
```

**Comment by dschaper** [comment]
Sorry, the header check `-I` can't contain payload, it would be:

```
curl -I -s -L -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
```

**Comment by dschaper** [comment]
`304`, so you received the file but it was not different than `/etc/pihole/list.3.pgl.yoyo.org.domains`, is that file empty or does it have contents?

**Comment by bcambl** [comment]
via container `centos:centos7.2.1511`:
```
[root@befc0a482d02 /]# curl -I -s -L -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,ke Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
HTTP/1.1 200 OK
Date: Wed, 11 Nov 2020 15:25:22 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15768000;
Last-Modified: Fri, 06 Nov 2020 13:22:37 GMT
Cache-Control: max-age=3600
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Connection: close
Content-Type: text/plain;charset=UTF-8
```

**Comment by dschaper** [comment]
Thanks, that's what I expect to see.

**Comment by bcambl** [comment]
@frollic please see https://github.com/pi-hole/pi-hole/issues/3839#issuecomment-725486475

**Comment by frollic** [comment]
@bcambl 

Not entirely sure what you're referring to .... ?

**Comment by dschaper** [comment]
>is that file empty or does it have contents?

**Comment by frollic** [comment]
When, doing what ? :|

Sorry if I'm beeing blonde right now, but there have been too many comments made, and I'm not 100% sure which one you're referring to ...

The 
curl -L -d mimetype=plaintext -d hostformat=hosts -z /etc/pihole/list.3.pgl.yoyo.org.domains -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
returns 304, but no additional output.

removing **hostformat=hosts**, but leaving the **-d** in, returns the hosts file, and status 200, 
and an additional curl: (3) <url> malformed.

**Comment by dschaper** [comment]
/etc/pihole/list.3.pgl.yoyo.org.domains, is that file empty or does it have contents?

**Comment by dschaper** [comment]
`304` is the HTTP return code for `No changes found`. So `curl` is comparing the etag from the URL with the file included with the `-z` flag to see if there is a need to re-download or just skip. 304 says to just skip it because the local file contents are exactly the same as what would have been downloaded.

So we need to see the local file and determine if the file is empty or has contents.

**Comment by dschaper** [comment]
`hostformat=hosts&showintro=0&mimetype=plaintext' | more`

Why are you piping the output to `more`?

**Comment by frollic** [comment]
No it's not empty.

[root@proxy tmp]# ls -l /etc/pihole/list.3.pgl.yoyo.org.domains
-rw-r--r-- 1 root root 57968 Nov  8 04:39 /etc/pihole/list.3.pgl.yoyo.org.domains
[root@proxy tmp]#

I used more becasue Puttys scroll back buffer was too short, wanted to see what it said in the beginning.

**Comment by dschaper** [comment]
Okay, then the `304` indicates the `curl` command would have downloaded a file with contents like that. You can confirm that with:

```
curl -s -L -d mimetype=plaintext -d hostformat=hosts -w '%{htcode}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext'
```
You likely will see `200` and then the file contents with that command.

**Comment by frollic** [comment]
Yes it works, but I get in the end:

.
.
.
.
.
127.0.0.1 zqtk.net
127.0.0.1 zukxd6fkxqn.com
127.0.0.1 zy16eoat1w.com
127.0.0.1 zzhc.vnet.cn
curl: unknown --write-out variable: 'htcode'
[root@proxy tmp]#

**Comment by dschaper** [comment]
That's not a problem, was just a copy/paste error. `-w '%{httpcode}'` is the correct returned variable. It will output `200` but you can run the command again with the right value in there and confirm it for yourself.

**Comment by frollic** [comment]
yup, no errors.

**Comment by dschaper** [comment]
Okay, so we know the script works and doesn't fail on special characters. The next thing would be to check if you can write to `/tmp/`, that's the only other place I can think of that would end up with an empty file, if the file couldn't be written at all. 

Running gravity should show  `[✓] Status: No changes detected` when it is provided a return code of `304`.

**Comment by frollic** [comment]
[root@proxy tmp]# ls -ld /tmp
drwxrwxrwt. 10 root root 4096 May 11  2019 /tmp
[root@ tmp]

**Comment by dschaper** [comment]
Since we know that the issue is not with `gravity` and the URL works, we can close this issue out. It looks like a configuration issue which is better addressed at https://discourse.pi-hole.net for the support and community to help you with.
