### ISSUE TITLE
FAQ addition - root size full when starting with dd and raspbian-jessie.img

### ISSUE THREAD

**Issue by rosskevin** [pi-hole/pi-hole#384]
- New installation from `-rwxr-xr-x  1 kross  staff   3.8G Feb 25 20:21 2016-02-26-raspbian-jessie.img` on a 32gb 3 B pi.
- Used `dd` method to create drive
- Installed pi-hole, seemed to go well
- Configured router etc
- Nothing blocked, nothing to be tailed following [troubleshooting](https://pi-hole.net/faq/how-do-i-troubleshoot-name-resolution-to-verify-ads-are-getting-blocked-and-queries-are-being-sent-to-the-pi-hole/)

Actual problem: root partition full

I found this when I went to check on some of the files, and `gravity.list` was 0kb, and it complained about space when I wanted to open others.  

1. I ran `sudo raspi-config` and chose to expand the root fs to use the partition.
2. reboot
3. re-run pi-hole install

All the files are populated now.

Other thoughts:
Since pi-hole culminates in the `gravity.list` file, perhaps the installer could verify it is not a 0kb file and otherwise give them a link to an article with this content?

Sending a donation now, thanks for the software!

**Comment by eseglem** [comment]
I ran into this the other day as well. I forgot to expand the partition before installing. It did give me a warning / error about being out of disk space, but it was a few lines up from the bottom. Making that error more obvious / fatal would probably be a good thing.

**Comment by PromoFaux** [comment]
Hmmm, that is interesting. We actually [check](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L119) for free disk space before installing...

**Comment by PromoFaux** [comment]
Actually.. ha! Looks like an input error.. missing a couple of zeros. We're supposed to be checking for 50Mb free... not 0.5Mb..! I'll make that change now... !

**Comment by nate-ubiquisoft** [comment]
Haha glad I could help!

**Comment by PromoFaux** [comment]
No, maybe not. The number was correct, had a bit of a scatty moment with numbers there.

51200 blocks of 1k (as per output of `df -lk`) is 51.2MB, which should be plenty of space.

@rosskevin @eseglem , did you add in any additional lists before expanding, for example mahakala?

**Comment by rosskevin** [comment]
I did exactly as stated, nothing else.

**Comment by graycrow** [comment]
@PromoFaux: something wrong with that numbers: #395

**Comment by PromoFaux** [comment]
@rosskevin Thanks for the feedback. Just trying to rule out extras, as it should have warned you if there was less than 51.2MB of  free space and asked you to run `raspi-config` to expand the filesystem...
