### ISSUE TITLE
Undetected existing prior web server yet lighttpd/php/etc still installed

### ISSUE THREAD

**Issue by Utopiah** [pi-hole/pi-hole#3842]
### Versions

- Pi-hole: Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE: 
- FTL: FTL version is v5.2 (Latest: v5.2)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Mozilla Gateway

### Expected behavior

Detect existing web server on port 80 then suggest an alternative port e.g. 8080 if its free, otherwise 8081, etc or entering manually.

### Actual behavior / bug

Installation process goes on but connecting brings the unrelated existing webserver with no access to the admin page.

### Steps to reproduce

1. have a web server on port 80
2. curl install
3. select web interface
4. connect after installation

**Comment by dschaper** [comment]
There's a limit to the amount of handholding and condition checking we can do.

It asked if you wanted to install lighttpd, I'm not sure where we can do a "Are you sure?" prompt.

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1270

**Comment by Utopiah** [comment]
You know your user base best.

If you believe that testing if port 80 is used (e.g. `curl localhost || echo webserver present`) to chance the server port adds complexity and dependencies for a corner case please close the issue.

**Comment by dschaper** [comment]
Well, we ask directly if you want to install `lighttpd`, I think that's explicit enough?
