### ISSUE TITLE
Return valid javascript instead of html stub for *.js (PR available)

### ISSUE THREAD

**Issue by rosskevin** [pi-hole/pi-hole#385]
##### Expected Behaviour:
When js is blocked, return a valid js file (will mostly cleanup the log).  This will not totally prevent js errors, as functions will not be present for on-page scripts, but it will clean up a large majority of console errors.

##### Actual Behaviour:
An html stub is returned regardless of the media type

```html
<html>
<body>
</body>
</html>
```

##### Steps to reproduce this issue:
Use pi-hole, visit any site with blocked ads, open the console.

<img width="887" alt="jalopnik_-_drive_free_or_die_and_untitled_text_46" src="https://cloud.githubusercontent.com/assets/136564/13766438/d29d6588-ea2f-11e5-8db4-e73fa87cd304.png">

**Comment by rosskevin** [comment]
I prototyped this and it seems to clear up most as expected.

lighttpd.conf changed section:

```bash
# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
        # Create a response header for debugging using curl -I
        setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
        # rewrite only js requests
        url.rewrite = ("(.*).js" => "pihole/index.js")
}
```

/var/www/html/pihole/index.js

```javascript
var x = "X-Pi-hole: A black hole for Internet advertisements."
```

I think this is pretty safe and should have zero side effects (other than cleaning up the browser's console log)

**Comment by Fedora-Core** [comment]
An answer to a previous request by Jacob Salmela on his Blog-Site =>

[https://github.com/Fedora-Core/Pi-hole-adblock-webserver-script](url)

Greetings, F.C.

**Comment by PromoFaux** [comment]
FC, that's a dead link!

**Comment by PromoFaux** [comment]
OK, so this is pretty neat. How does it affect placeholders for JS based ads?

**Comment by rosskevin** [comment]
As long as another script doesn't rely on the js and try to call an api i.e. the script is executed as an iife/standalone, then nothing happens!  It's all upside, no console errors and nothing executed.

As it was, it was just a slew of errors in the browser.

**Comment by PromoFaux** [comment]
For sure, give me a sec to do a pull and I'll test it

**Comment by PromoFaux** [comment]
OK, so from testing this only graps the snippet on `http` requests, and not `https`, but I think that's a separate issue.

![image](https://cloud.githubusercontent.com/assets/1998970/14032948/366a9474-f20e-11e5-87c0-438191d6b44f.png)

**Comment by rosskevin** [comment]
Yeah, I'm not sure if `$HTTP` is just the protocol segment or literally `http`:

`$HTTP["url"] =~ "^(?!/admin)/.*"`

But that rewrite is probably what should be tweaked.

**Comment by PromoFaux** [comment]
I think just the protocol, however I'm a bit clueless when it comes to web security. From what I understand after previous conversations, we'd need to be self-signing a certificate, which would essentially be a man in the middle attack. @dschaper can probably correct me....!

**Comment by DonLexos** [comment]
If you would self sign the browser (chrome) will return an error that it 'Your connection is not private' or worse, it will do something random depending on the browser. It will toss something like
`This server could not prove that it is your.fake.pi-hole.domain.com; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.`

**Comment by PromoFaux** [comment]
Yeah, I knew the answer wasn't a fun one :)

**Comment by DonLexos** [comment]
Self signed certificates will most likely not be liked by any browser, one of the main points of SSL is you know you connect to the proper domain (so https://www.addomain.com/js/whatever.js should give an error if it is server with a self signed certificate, since that is not valid for addomain.com) .

**Comment by DonLexos** [comment]
On the other hand, if you just serve an empty js file ... not sure what would happen. The ads will break (a feature, not a bug!) and the console will be a surprise I guess (but only on httpS included ad.js files).

**Comment by PromoFaux** [comment]
>a feature, not a bug!
There is no such thing as bugs. Only undocumented features...

I think we can leave the https ads for now, we've done fine without them so far!

**Comment by DonLexos** [comment]
Ha.. .I meant it won't display the ads but that seems like intended behavior o:-)

**Comment by rosskevin** [comment]
I'd rather not pollute the log with anything, so I'm not in favor of using `console.log` because in my case, it would output 13 times interspersed with other errors.  The whole premise of this is to cleanup the log.

**Comment by PromoFaux** [comment]
Yeah, that's a fair point. I'm a bit log-happy. We can leave customisation of that file up to the user, if they wish to have it. Just for future reference, please make PRs against the development branch, and not the master, it's less work for us to pull it over :) Thanks again!
