### ISSUE TITLE
Group Management -> Groups can't be edited nor deleted

### ISSUE THREAD

**Issue by CBLXXXV** [pi-hole/pi-hole#3860]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Raspbian GNU/Linux 9 
- Platform:  Raspberry Pi

### Expected behavior

- Clicking the red trashcan icon next to an group should delete the group.

- Editing the name or description of a group should change the values accordingly

### Actual behavior / bug

- Clicking the red trashcan icon next to an groups leads to an message "successfully deleted group", however upon reloading the page, the group is reappeared

- Editing the name / description of a group results in an message "successfully edited name / description of group", however upon reloading the page, the changes are all rolled back to the beginning

### Steps to reproduce

1. Steps to reproduce the behavior:
2. Go to 'Group Management'
3. Click on 'Groups'
4. Click on 'Trashcan Icon'
5. See 'Successfully deleted group' message
6. Press 'F5' eg Page Reload
7. See group reappeared

1. Go to 'Group Management'
2. Click on 'Groups'
3. Edit 'Name/Description' 
4. See 'Successfully edited name/description' message
5. Press 'F5' eg Page Reload
6. See changes rolled back

## Debug Token

- URL:  https://tricorder.pi-hole.net/jnsg9hejji

**Comment by jfb-pihole** [comment]
Your groups all have the same group ID's.

```
*** [ DIAGNOSING ]: Groups
   id    enabled  name                                                date_added           date_modified        description                                       
   ----  -------  --------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   0           1  Default                                             2020-05-12 11:56:42  2020-05-12 11:56:42  The default group                                 
   2552        1  anudeepND/whitelist                                 2020-11-22 20:35:08  2020-11-22 20:35:08  https://github.com/anudeepND/whitelist            
   2552        1  firebog.net                                         2020-11-24 14:15:55  2020-11-24 14:15:55  firebog.net                                       
   2552        1  firebog/ticked                                      2020-11-24 14:20:50  2020-11-24 14:20:50  https://v.firebog.net/hosts/lists.php?type=tick   
   2552        1  test                                                2020-11-24 14:32:03  2020-11-24 14:32:03                                                    

*** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
   id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment                                           
   ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   6     0           1  0             cdn.optimizely.com                                                                                    2020-05-12 11:56:44  2020-05-12 11:56:44  Migrated from /etc/pihole/whitelist.txt           
   7     0           1  0             api.mobile.immobilienscout24.de                                                                       2020-05-12 11:56:44  2020-05-12 11:56:44  Migrated from /etc/pihole/whitelist.txt           
   8     0           1  2552552551    0.client-channel.google.com                                                                           2020-11-22 20:35:09  2020-11-22 20:35:09  In order for users on your network to access Googl
   9     0           1  2552552551    1drv.com                                                                                              2020-11-22 20:35:09  2020-11-22 20:35:09  It is actually a legitimate Microsoft owned domain
```

Try manually deleting these groups with an SQL command - this one is untested:

`sudo sqlite3 /etc/pihole/gravity.db "delete from group where id=2552"`

**Comment by dschaper** [comment]
It looks like you're using some script to manipulate the lists in the database and you've corrupted the database. It's also 1GB in size. 

Delete the database and remove the script that is modifying your database.

**Comment by dschaper** [comment]
Oh, and your IPv6 address isn't right. The one you've configured Pi-hole to use doesn't exist on the interface anymore.

**Comment by dschaper** [comment]
@PromoFaux 

```plain
 2020-11-24 14:28:15: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:28:19: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:28:19: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:28:22: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:28:23: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:28:24: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
   2020-11-24 14:32:47: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: adlist_by_group.adlist_id, adlist_by_group.group_id in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 851
```

This should display a warning to the user that the command failed?

**Comment by CBLXXXV** [comment]
> 
> 
> It looks like you're using some script to manipulate the lists in the database and you've corrupted the database. It's also 1GB in size.
> 
> Delete the database and remove the script that is modifying your database.

Hello,
I cant think of any script which would fit your description. I only installed pihole on the Raspberry, on top of that i have log2ram, fail2ban and the anudeep whitelists installed.

**Comment by dschaper** [comment]
> the anudeep whitelists installed

How did you install them?

**Comment by dschaper** [comment]
> Wouldn't that destroy my pihole installation?

No, it will reset everything back to a working state. As JFB pointed out, you have the same ID for multiple groups. The ID is automatically generated sequentially when you create the group, so either you've added 2500 groups or something has broken the database. Usually something that modifies the database (like a script that isn't created by Pi-hole). 

Also, it's generally a bad idea to F5 after clicking a button or running a command as that will try to execute the same command again, that's why you see warnings of "Do not reload this page" when you submit payment information to a site, you get double billed. Have you been banging on the F5 key? That could attempt to re-run the same command over and over again.

**Comment by CBLXXXV** [comment]
> 
> 
> > the anudeep whitelists installed
> 
> How did you install them?

Exactly like in his guide https://github.com/anudeepND/whitelist#for-whitelisttxt

**Comment by CBLXXXV** [comment]
> 
> 
> > Wouldn't that destroy my pihole installation?
> 
> No, it will reset everything back to a working state. As JFB pointed out, you have the same ID for multiple groups. The ID is automatically generated sequentially when you create the group, so either you've added 2500 groups or something has broken the database. Usually something that modifies the database (like a script that isn't created by Pi-hole).
> 
> Also, it's generally a bad idea to F5 after clicking a button or running a command as that will try to execute the same command again, that's why you see warnings of "Do not reload this page" when you submit payment information to a site, you get double billed. Have you been banging on the F5 key? That could attempt to re-run the same command over and over again.

Actually first I just went to another tab on the menu and then back, F5 just gave the same result. Nope no banging

**Comment by dschaper** [comment]
> Exactly like in his guide https://github.com/anudeepND/whitelist#for-whitelisttxt

That's the exact definition of "using some script to manipulate the lists".

**Comment by dschaper** [comment]
@anudeepND Do you have any insight?

**Comment by dschaper** [comment]
See https://github.com/anudeepND/whitelist/issues/187

**Comment by anudeepND** [comment]
@dschaper Sorry for the issues, I have reverted the PR that added the group. It can be removed manually by:
```
sqlite3 "/etc/pihole/gravity.db" "DELETE FROM "group" WHERE id = 2552552551;"
```

**Comment by anudeepND** [comment]
@dschaper Sorry for the issues, I have reverted the PR that enabled groups, the group can be removed manually by entering the command:
```
sqlite3 /etc/pihole/gravity.db "DELETE FROM 'group' WHERE id = 2552552551;"
```

**Comment by dschaper** [comment]
Thanks!
