### ISSUE TITLE
Group Management -> Adlists can't be assigned to other groups beside default

### ISSUE THREAD

**Issue by CBLXXXV** [pi-hole/pi-hole#3861]
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Raspbian GNU/Linux 9
- Platform:  Raspberry Pi

### Expected behavior

- Assigning an adlist to any other group then 'Default' should assign it to the selected group(s) accordingly 

### Actual behavior / bug

- Assigning an adlist to any other group besides 'Default' results in an message "successfully edited groups of adlist", however Group assignment is stated as 'none selected'

### Steps to reproduce

1. Go to 'Group Management'
2. Click on 'Adlists'
3. On the respective adlist where group membership should be changed, click on the 'Group assignment' tab
4. Select any Group beside 'Default'
5. Click on 'Apply'
6. See 'Successfully edited groups of adlists' message
7. See Group assignment stated as 'none selected'
8. 

## Debug Token

- URL:  https://tricorder.pi-hole.net/jnsg9hejji

### Screenshots

![Screenshot 2020-11-24 151700](https://user-images.githubusercontent.com/74971285/100105964-3b390080-2e68-11eb-908e-c8a50a41afa0.png)

**Comment by dschaper** [comment]
Same core issue as #3860
