### ISSUE TITLE
pihole -g won't update blocklists

### ISSUE THREAD

**Issue by buzuddha** [pi-hole/pi-hole#3869]
### Versions
```
pihole -v 
Pi-hole version is v5.2 (Latest: v5.2)
AdminLTE version is v5.2 (Latest: v5.2)
FTL version is v5.3.1 (Latest: v5.3.1)

```
### Platform
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
uname -r
5.4.72-v7+
```
### Expected behavior
Fresh install of pihole

1. run `sudo nano /etc/pihole/adlists.lists`
2. paste in some domains:
```
#Advertising
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Admiral.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
...
```
etc.
3. save
4. run `pihole -g` 

EXPECTED: new domains on blocklist

### Actual behavior / bug

4. run `pihole -g`

No new domains added to blocklist. Only those that came preloaded in the software are loaded.

### Steps to reproduce

As above: 
1. run `sudo nano /etc/pihole/adlists.lists`
2. paste in some domains:
```
#Advertising
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Admiral.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
...
etc.
```
3. save
4. run `pihole -g` 

Webmin attempts to add domains one by one fail as well (![Screenshot from 2020-11-28 20-25-48](https://user-images.githubusercontent.com/40274205/100529710-4ec1cf80-31b8-11eb-8e4c-ef0cc2c3c155.png)
). Webmin states that domains are not in fact domains, yet 

`curl https://adaway.org/hosts.txt` from the pi itself yields http://ix.io/2FRN, so it can resolve the list by other means.

## Debug Token

- URL:  https://tricorder.pi-hole.net/j166u6d436

### Screenshots

One is attached. 

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Pi-hole version 5 uses a database, not the flat files. You'll have to add the lists the current way. And we've never supported editing lists files.

**Comment by dschaper** [comment]
And URLs are not valid domains, the screen you are showing is meant for listing individual domains (or regexes).

**Comment by buzuddha** [comment]
I see. Thanks dschaper.

For anyone who was struggling, I figured out how to add lists via the webinterface. 

For anyone who has been looking around the internet for a clear walk through on this here's how to do this. It took me a minute to figure this out and I still haven't found a clear walkthrough.

1. Go find a list. For example: [Grab this list but don't follow their instructions](https://obutterbach.medium.com/unlock-the-full-potential-of-pihole-e795342e0e36)
2. Log in to you pihole admin and go to the <Your.Pi.Hole.IP>/admin/admin/groups-adlists.php page
3. Paste the URLs for the adlists with spaces in between them. Don't include the comment lines.
4.  Don't forget to hit add.
5. Open up a terminal. Run `ssh <user>@<Your.Pi.Hole.IP>` 
6. Run `phiole -g`
7. Reload your <Your.Pi.Hole.IP>/admin/ in your browser and you should see updated allow/blocklist numbers 

Still haven't figured out a command line way to do this, but this was plenty fast.

**Comment by jfb-pihole** [comment]
"Open up a terminal. Run ssh <user>@<Your.Pi.Hole.IP>
Run phiole -g"

You don't need to open the terminal for this.  You can rebuild gravity from the web admin GUI > Tools
