### ISSUE TITLE
New URL to the Windows 10 blocklist

### ISSUE THREAD

**Issue by ajp2k13** [pi-hole/pi-hole#387]
##### Expected Behaviour:
New url with separate lists for blocking telemetry and windows update:
https://github.com/crazy-max/WindowsSpyBlocker

##### Actual Behaviour:
Old url in adlists.default: https://github.com/crazy-max/HostsWindowsBlocker

##### Steps to reproduce this issue:
Uncomment the Windows 10 telemetry entry and run gravity.sh

**Comment by PromoFaux** [comment]
Thanks for this,

This will be fixed in the next release!

**Comment by crazy-max** [comment]
I have added Firewall rules on the repository to block telemetry IP adresses.
