### ISSUE TITLE
'lsof' appears to be a dependency, but pi-hole isn't looking for it as dependency

### ISSUE THREAD

**Issue by liroyvh** [pi-hole/pi-hole#3870]
### Versions

- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.3.1

### Platform

- OS and version:  CentOS 7

- Platform:  Synology VM (qemu)

### Expected behavior

For Pi-hole to show the resolver status properly. This depends on the "lsof" command (as of recently? Haven't really seen this error below before.), but this is apparently not shipped with CentOS 7 by default.

### Actual behavior / bug

Pi-hole claims "DNS service not running" and shows the following error when restarting on Terminal:
> /usr/local/bin/pihole: line 284: lsof: command not found
>   [✗] DNS service is NOT listening

However, it would appear the DNS service is running. At least, unbound is. 

Installing "lsof" manually (yum -y install lsof) fixes the problem:

>   [✓] DNS service is listening
>      [✓] UDP (IPv4)
>      [✓] TCP (IPv4)
>      [✓] UDP (IPv6)
>      [✓] TCP (IPv6)
> 

PiHole's installer/updater/repair should probably check for it with yum/dependencies, it currently doesn't seem to be doing so.

### Steps to reproduce

Steps to reproduce the behaviour:

Have Pihole installed on default CentOS 7, fails where "lsof" is required unless you manually install it.

**Comment by yubiuser** [comment]
You're right. `lsof` is listed as dependency, but only for the Debian family, not for everything else.
https://github.com/pi-hole/pi-hole/blob/fee1b8b736a402c8b72a68d6f2449e9061477dee/automated%20install/basic-install.sh#L396

**Comment by liroyvh** [comment]
Closing this issue as the merged changes have fixed the problem - thank you!
