### ISSUE TITLE
Pi-hole showing multiple DNS server entries for the same DNS server

### ISSUE THREAD

**Issue by coldfire7** [pi-hole/pi-hole#3872]
### Versions

- Pi-hole:  v5.2 (Latest: v5.2)
- AdminLTE:  v5.2 (Latest: v5.2)
- FTL:  v5.3.1 (Latest: v5.3.1)

### Platform

- OS and version:  Ubuntu 20.04.1 LTS
- Platform:  VM/Container (Proxmox LXC)

### Expected behavior

- One entry per DNS server 

### Actual behavior / bug

- Pi-hole showing multiple DNS server entries for the same internal DNS server (Screenshot 1), also note both entries showing different logs (Screenshot 2 & 3).

### Steps to reproduce

- Set internet DNS server with different port (e.g. 127.53.53.2#5302)

## Debug Token

- URL: https://tricorder.pi-hole.net/hiptd2n1a1

### Screenshots

- Screenshot 1: https://i.imgur.com/iC4XNDC.png
- Screenshot 2: https://i.imgur.com/TfT9LbS.png
- Screenshot 3: https://i.imgur.com/QZnfqkO.png

### Additional context

- N/A

**Comment by yubiuser** [comment]
The separation by IP and Port was introduced by https://github.com/pi-hole/FTL/pull/923

Note the hint
>There is one expected cosmetic issue: FTL cannot know the port of the server responsible for queries in the database. Hence, immediately after switching to this branch, you'll note the assumed server 127.0.0.1#53 (even when the server may be sitting at #5353). This is merely a displaying issue as the content of the database will be correct at any time. I looked at providing simple solutions for this, however, it would make the code unreadable and - since the issue will be gone after 24 hours - it doesn't seem worth the effort.

It will correct itself after 24h.
