### ISSUE TITLE
DNS servers get lost upon repair/update

### ISSUE THREAD

**Issue by dandjo** [pi-hole/pi-hole#3873]
### Versions
- Pi-hole: 5.2
- AdminLTE: 5.2
- FTL: 5.3.1

### Platform
- OS and version: Ubuntu 20.04
- Platform: Rapsberry Pi

### Expected behavior

All 12 checked DNS servers in settings stay checked after an repair or update.

### Actual behavior / bug

After a `pihole -r` (repair mode) or `pihole -up` the DNS servers are trimmed to the first 9 servers. You can also verify that with the entries in `setupVars.conf`.

### Steps to reproduce

1. Go to `/admin/settings.php?tab=dns`
2. Select 12 DNS servers of your choice
3. Save the settings (also check `setupVars.conf`)
4. Call `pihole -r` with "repair" or `pihole -up` (if there's an update)

## Debug Token

- URL: https://tricorder.pi-hole.net/ykw0i771l1

### Screenshots

Before:
![Screenshot_20201129_151106](https://user-images.githubusercontent.com/34278179/100544328-263be300-3255-11eb-9ff4-4fcd31d5d255.png)

After steps to reproduce:
![Screenshot_20201129_151005](https://user-images.githubusercontent.com/34278179/100544309-099fab00-3255-11eb-8971-9a232ac78b23.png)

**Comment by PromoFaux** [comment]
Interesting, this appears like it could be a cosmetic bug. Is your debug log from before or after the steps to reproduce? As that shows 12 DNS upstreams

**Comment by PromoFaux** [comment]
Ignore that, just tested myself.. a `pihole -r` removes anything above 9. I'll take a look. 

Is there any particular reason you have so many upstreams selected?

**Comment by Nytelife26** [comment]
From [`update.sh`](https://github.com/pi-hole/pi-hole/blob/14944b0283ea703cc6292eb32691921025665801/advanced/Scripts/update.sh#L6):
```
# Check Pi-hole core and admin pages versions and determine what
# upgrade (if any) is required. Automatically updates and reinstalls
# application if update is detected.
```
I don't see this as unexpected - for functions that uninstall and reinstall pihole, configuration being altered or reset is pretty much guaranteed to happen. Unless it is genuinely truncated no matter what and not just changed to the default state?

As for reconfigure, though, it is indeed supposed to retain settings. Perhaps when it re-pulls it overwrites them? I'll investigate further too, although it seems like PromoFaux is already on it.

**Comment by PromoFaux** [comment]
A `pihole -r` then `reconfigure` should wipe out the settings, as it will display the initial whiptails to configure.

A `pihole -r` then `repair` (and indeed a `pihole -up`) should retain any variables set in `setupVars.conf` - just trying to pinpoint where in the code they get truncated

**Comment by Nytelife26** [comment]
It doesn't seem like `useUpdateVars` is used anywhere in respect to configuring the DNS settings. Perhaps that's part of the issue?

**Comment by PromoFaux** [comment]
Through a bit of trial and error, it appears to be happening in the `finalExports` function of `basic-install.sh`

**Comment by PromoFaux** [comment]
More specifically - this line: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1916

**Comment by PromoFaux** [comment]
So one thing I can say for certain is that this is not new behaviour in the current release. Locally I have just reverted the change to what it was before the most recent update ([here](https://github.com/pi-hole/pi-hole/blame/4d98e156b652fde26229042497510ea022ee8ced/automated%20install/basic-install.sh#L1957), and before that it has not been touched for 2 years!

Now to try and dig out what we're actually trying to achieve with that section...

**Comment by PromoFaux** [comment]
RIGHT... I know what is happening.

```
sed -i.update.bak '/PIHOLE_INTERFACE/d;/IPV4_ADDRESS/d;/IPV6_ADDRESS/d;/PIHOLE_DNS_1/d;/PIHOLE_DNS_2/d;/QUERY_LOGGING/d;/INSTALL_WEB_SERVER/d;/INSTALL_WEB_INTERFACE/d;/LIGHTTPD_ENABLED/d;/CACHE_SIZE/d;' "${setupVars}"
```

the `sed` command is removing `PIHOLE_DNS_1*` and `PIHOLE_DNS_2*`, so that includes `10`,`11`,`12` etc (and in turn would also include `20`,`21` etc - but if you had 38 DNS servers, it would not include `30`,`31` etc)

Off to flex my google-fu to find a solution

**Comment by PromoFaux** [comment]
Will be fixed by #3874

**Comment by dandjo** [comment]
Great, thx!

**Comment by yubiuser** [comment]
This has been merged into master already
