### ISSUE TITLE
Connection gets refused of Chronometer

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#3876]
### Versions

- Pi-hole:  **5.2**
- AdminLTE:  **5.2** 
- FTL:  **5.3.1**

### Platform

- OS and version:  **Raspbian GNU/Linux 10**

- Platform:  **Raspberry Pi**

### Expected behavior

Connection gets refused of Chronometer

### Actual behavior / bug

/opt/pihole/chronometer.sh: connect: Connection refused
/opt/pihole/chronometer.sh: line 19: /dev/tcp/127.0.0.1/4711: Connection refused

### Steps to reproduce

1. Use Chronometer on LCD Display
2. Wait a few secounds unit Display refresh 
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/hlpey1n53q

**Comment by pheiduck** [comment]
Do you need some more information @dschaper ?

**Comment by dschaper** [comment]
Nope

**Comment by pheiduck** [comment]
Bash Script that I use in my zshrc

```zsh
# Start Pi-hole chrono when on tty1
case $(tty) in /dev/tty1)
  msg="Starting Pi-hole chronometer ... "
  row=2
  ol=2
  clear
  tput cup $row $col
  echo -n "$msg"
  l=${#msg}
  let l=l+col
  for i in {3..1}
  do
    tput cup $row $l
    echo -n "$i"
    sleep 1
  done
  clear
  pihole -c
  exit 0
esac
```

**Comment by pheiduck** [comment]
Problem is not resolved with the latest updates

**Comment by pheiduck** [comment]
https://tricorder.pi-hole.net/38i6vz7jmo

**Comment by pheiduck** [comment]
today, I found out, tty1 was stuck at. omz update prompt, so I was doing the update manually and it worked again
