### ISSUE TITLE
Fresh Installs installing improperly?

### ISSUE THREAD

**Issue by Ianwonders** [pi-hole/pi-hole#3878]
### Versions

- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  /opt/pihole/version.sh: line 19: /usr/bin/pihole-FTL: No such file or directory
          /opt/pihole/version.sh: line 122: /usr/bin/pihole-FTL: No such file or directory 
          Latest FTL version is v5.3.1

### Platform

- OS and version:  "Debian GNU/Linux" 
                              Version="10 (buster)"

- Platform:  Raspberry PI Desktop 64 bit OS virtualized on ProxMox (proxmox v. 6.2-4)

### Expected behavior

After a fresh Install of both Raspbian/buster OS, and a fresh install of PiHole, following the instructions listed at "https://github.com/pi-hole/pi-hole" I expected PiHole to even function. I did those exact steps yesterday and PiHole was working beautifully. See additional context

### Actual behavior / bug

PiHole starts and I can log into the web interface, but the metrics windows infinitely load and there are red dots at the top that say "DNS service is not running" and "FTL..." (it cuts off and I can't read it) 

pihole status produces:
[x] DNS service is NOT listening

### Steps to reproduce

1. Install Raspbian OS
2. Install PiHole
3. Browse to Web Interface on Chrome
4. Log in successful, nothing else on screen. Web Blocking not working, and if I set DNS to PiHole I lose name resolution. 

## Debug Token

- URL:  https://tricorder.pi-hole.net/m3pda09t3z

### Additional context

Installed a fresh copy of Raspbian OS, and PiHole yesterday and it was working beautifully. Today, I suspected something was being blocked and needed to be whitelisted, so I logged into the Web GUI. After a successful login (as in no prompts stating the password was wrong) I would continuously be redirected to the login page again. I attempted to reboot my VM, and it never came back up, so I deleted the VM and started over. Ran fresh updates/upgrades on the newly created VM, and attempted to install PiHole. The installer would go through, but at the very end I would see [x] DNS not listening, then it would tell me the new admin password. I attempted another fresh install of Raspbian/PiHole again and it still fails. 

I'm pretty new to running PiHole, but I can't understand why it is suddenly borking its installs when it worked first try yesterday. I've done a few hours of research and testing, reinstalling, uninstalling (the uninstall tool uninstalled a lot of extra stuff so I rebuilt the VM and retried..same error). Nothing I have tried has helped. Please let me know if there is anything else I can help you with to help me :)

**Comment by dschaper** [comment]
> After a fresh Install of both Raspbian/buster OS, and a fresh install of PiHole, following the instructions listed at "https://github.com/pi-hole/pi-hole"

What are the exact steps you are taking to install, there are a few different options on our README.

The debug log indeed shows that the `pihole-FTL` binary does not exist in the `/usr/bin` directory. What kind of VM are you using in Proxmox, LXC or KVM?

**Comment by Ianwonders** [comment]
> > After a fresh Install of both Raspbian/buster OS, and a fresh install of PiHole, following the instructions listed at "https://github.com/pi-hole/pi-hole"
> 
> What are the exact steps you are taking to install, there are a few different options on our README.
>  I followed the steps for cloning your repository:

git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh

> The debug log indeed shows that the `pihole-FTL` binary does not exist in the `/usr/bin` directory. What kind of VM are you using in Proxmox, LXC or KVM?
> That's what's weird...dug into the /usr/bin/ directory and I found "pihole-FTL"
![image](https://user-images.githubusercontent.com/75226127/100556580-8b490600-3260-11eb-91fd-6bce9de7f658.png)

> To be completely honest, I am not sure how to tell you that information for the ProxMox VM. I'll attach screenshots of the setup to try and be helpful. Its either running as QMEU or KVM:
![image](https://user-images.githubusercontent.com/75226127/100556706-66a15e00-3261-11eb-9ca4-1b5c96e4bf34.png)
![image](https://user-images.githubusercontent.com/75226127/100556734-9badb080-3261-11eb-9409-bc69b4c1d895.png)

**Comment by dschaper** [comment]
Did you create a new user inside the KVM? Running as root is not a great idea. 

Is `/usr/bin` in the $PATH for the user that called `sudo bash basic-install.sh`? And why are you using that method instead of the `curl` method?

**Comment by dschaper** [comment]
And really, a 10 gig hard disk with a KVM instance is tiny. Like dangerously tiny.

**Comment by Ianwonders** [comment]
I did not create a new user in the Raspbian OS. I have installed the same OS on actual RPis and never had an issue with other programs. When you install that program it comes with a user called Pi. I do change the password to that to a passphrase with pretty high entropy (usually they're about 48 char long)

Would the curl method be better? Do you think it would cure my woes? I can blow that VM out again..Raspbian takes almost no time to install. 

For your question: 

> Is `/usr/bin` in the $PATH for the user that called `sudo bash basic-install.sh`? And why are you using that method instead of the `curl` method?

I ran that command from the the directory the instructions say to, so I CD'ed to "Pi-hole/automated install" Do I need to be in a different directory when I install the program?

Finally, to address your concerns on the 10gig "hard disk" its just a VM that's designed to run on a RPi. I've had a lot of successful installs of that OS on actual physical RPis with 16gb Micro SD cards. That VM disk lives on a ZFS pool running RaidZ1 with 9tb of total free space; perhaps its just because I'm a novice but I don't see an issue making the OS disk that small. Also, isn't piHole supposed to run happily on a raspberry pi Zero? I can't imagine those having much onboard memory

**Comment by yubiuser** [comment]
As Dan pointed out, the  `pihole-FTL binary` does not exist in the `/usr/bin` directory. Did you try again to install it, or run `pihole -r` (repair)? Are there any errors during installation regarding `FTL`?

**Comment by pandorasbox2340** [comment]
...

**Comment by Ianwonders** [comment]
Here is the output of "pihole -r":

pi@raspberry:~ $ pihole -r

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
  [i] Repair option selected

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php7.3-json
  [✓] Checking for php7.3-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected x86_64 processor
  [i] Checking for existing FTL binary...
  [i] Checksum of installed binary matches remote. No need to download!
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [i] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Restarting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Restarting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 60212 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: Retrieval successful
  [i] Received 26854 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 87066 (87028 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✗]
  [✓] Cleaning up stray matter
  [✓] Restarting DNS server

  [✗] DNS service is NOT listening
/opt/pihole/updatecheck.sh: line 77: /usr/bin/pihole-FTL: No such file or directory
/opt/pihole/updatecheck.sh: line 91: /usr/bin/pihole-FTL: No such file or directory

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

  Current Pi-hole version is v5.2.
  Current AdminLTE version is v5.2.
/opt/pihole/version.sh: line 19: /usr/bin/pihole-FTL: No such file or directory
/opt/pihole/version.sh: line 122: /usr/bin/pihole-FTL: No such file or directory
  Invalid Option! Try 'pihole -v --help' for more information.
pi@raspberry:~ $ ^C
pi@raspberry:~ $
pi@raspberry:~ $   [✓] Update local cache of available packages
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php7.3-json
  [✓] Checking for php7.3-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected x86_64 processor
  [i] Checking for existing FTL binary...
  [i] Checksum of installed binary matches remote. No need to download!
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [i] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Restarting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Restarting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 60212 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: Retrieval successful
  [i] Received 26854 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 87066 (87028 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✗]
  [✓] Cleaning up stray matter
  [✓] Restarting DNS server

  [✗] DNS service is NOT listening
/opt/pihole/updatecheck.sh: line 77: /usr/bin/pihole-FTL: No such file or directory
/opt/pihole/updatecheck.sh: line 91: /usr/bin/pihole-FTL: No such file or directory

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

  Current Pi-hole version is v5.2.
  Current AdminLTE version is v5.2.
/opt/pihole/version.sh: line 19: /usr/bin/pihole-FTL: No such file or directory
/opt/pihole/version.sh: line 122: /usr/bin/pihole-FTL: No such file or directory
  Invalid Option! Try 'pihole -v --help' for more information.
-bash: [✓]: command not found

As you can see it doesn't throw any FTL errors until the end and DNS never starts! Hope that helps!

**Comment by Ianwonders** [comment]
Edits for readability

**Comment by Ianwonders** [comment]
Just to update, I rebuilt my Raspbian VM again and installed PiHole using the CURL method. It is still not functioning, DNS and FTL never start after the fresh install. Is there anything else that I can try?

**Comment by dschaper** [comment]
There's a few comments on a similar issue and potential fix for ESXI virtualization, it may work for you as well.

https://discourse.pi-hole.net/t/new-install-on-raspberry-pi-os-on-esxi-virtual-machine-fails-to-install-correctly/41082/41

**Comment by Ianwonders** [comment]
Read through that whole article...applied the fix at the bottom of the page. PiHole is working now! Interesting that ESXI causes raspbian to behave strangely. But either way I'm super happy you showed me that article....In my researching I found the other two articles that are mentioned in that one...but not that article that actually fixed my problem. Thanks again for your help. to clarify in case anybody else stumbles across this thread with the same issue, I ran:

sudo apt install libc6:amd64

Then 

curl -sSL https://install.pi-hole.net | bash

With PiHole already installed and just used the "update" method. Once it was done installing everything came back up

**Comment by pandorasbox2340** [comment]
Let’s get togetherWe’re hosting a new event, and we’d love to see you there. Join us for Belly of the Beast Free Virtual Screening and In Person Screening, May 6, 2021 at 6:45 PM.Register soon, because it&#x27;s Airing this Thursday. We hope you’re able to join us!1) Come in Personor2) Watch Online ＴＨＩＳ ＷＥＥＫ ＩＳ ＴＨＥ ＷＥＥＫ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;𝙱𝙴𝙻𝙻𝚈 𝙾𝙵 𝚃𝙷𝙴 𝙱𝙴𝙰𝚂𝚃&quot;If you can&#x27;t make it in person, sign up on Eventbrite (https://clicks.eventbrite.com/f/a/Zq1ohvguFQq-D_PM9YlioA~~/AAQxAQA~/RgRidHybP0Q2aHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb20vLi4uL2JlbGx5LW9mLXRoZS1iZWFzdC1mcmVlVwNzcGNCCmCMnveRYEzcMc9SQXJlcGx5K2FybTRqdm1jdnE2YXN3YW82dHlybDV2NTJicTdsZXZibmhoY3p5dHdoNEByZXBseS5naXRodWIuY29tWAQAAAAE...) and a virtual link will be sent to your email with the activation code once you register (also free of charge).&nbsp;&nbsp;The link will be active for 24 hours.“...Erika Cohn’s documentary “Belly of the Beast,” which depicts the fight to ban non-consensual sterilizations performed on female prisoners in California, is at once a thrilling legal drama and heartbreaking depiction of devastating human rights violations that you can’t imagine happening in the 21st century...” ~ The Los Angeles Times Film Website: https://clicks.eventbrite.com/f/a/otzP4bfQ6CQhu-7rP--fGw~~/AAQxAQA~/RgRidHybP0QkaHR0cHM6Ly93d3cuYmVsbHlvZnRoZWJlYXN0ZmlsbS5jb20vVwNzcGNCCmCMnveRYEzcMc9SQXJlcGx5K2FybTRqdm1jdnE2YXN3YW82dHlybDV2NTJicTdsZXZibmhoY3p5dHdoNEByZXBseS5naXRodWIuY29tWAQAAAAE Facebook: https://clicks.eventbrite.com/f/a/4BJ71DOByYVO7z7xoUKfZg~~/AAQxAQA~/RgRidHybP0QsaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2JlbGx5b2Z0aGViZWFzdGZpbG1XA3NwY0IKYIye95FgTNwxz1JBcmVwbHkrYXJtNGp2bWN2cTZhc3dhbzZ0eXJsNXY1MmJxN2xldmJuaGhjenl0d2g0QHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~ Twitter: https://clicks.eventbrite.com/f/a/8gvs4VVFZAqCpwsyLl473A~~/AAQxAQA~/RgRidHybP0QcaHR0cHM6Ly90d2l0dGVyLmNvbS9ib3RiZmlsbVcDc3BjQgpgjJ73kWBM3DHPUkFyZXBseSthcm00anZtY3ZxNmFzd2FvNnR5cmw1djUyYnE3bGV2Ym5oaGN6eXR3aDRAcmVwbHkuZ2l0aHViLmNvbVgEAAAABA~~ Instagram: instagram.com/bellyofthebeastfilm/ Hashtag: #BellyoftheBeast, #BOTBfilm



Featured Events:

Belly of the Beast Free Virtual Screening and In Person Viewing | Historic Palace Theatre | 2021-05-06T22:45:00Z
https://clicks.eventbrite.com/f/a/7ZMa_ZdiiZPoACQkbf4E4A~~/AAQxAQA~/RgRidHybP0QaaHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb21XA3NwY0IKYIye95FgTNwxz1JBcmVwbHkrYXJtNGp2bWN2cTZhc3dhbzZ0eXJsNXY1MmJxN2xldmJuaGhjenl0d2g0QHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~






Unsubscribe: https://www.eventbrite.com/organizations/missive/activity/unsubscribe/?p=ABIdvVutIF2iBAV8YLZTy309Lli_XFsA1Rqj6anXQVXuWrF1lVwOcDW5rN7LqWLN89aax9xhiJHcpQEyz6W0VByNOQYBTvFmwHu3Riiwxk7uLZ80q8K8uiFZLKdybTwOuZC7T-IZLLfdAwJanB2yw_gPJxLZtbkm7Qn4xrv2yAr7M6Pr4ygSWYEO2i-Qp1hWnx5iDf_J-vANVxf_DtI9No3zutBstd2K-ljDnCcLeLkOUjqJ5yS-QgPpN4wJRci6QO_TU-6oNcxzPA7zNzTgvYPg8H5qnSTxi-r_kDf3Dp_JMZArjUTrVRJAqnE-NrZE1GkLW_jWtJUE&c=787768&co=216110908
