### ISSUE TITLE
Admin recent queries page table not generating correctly

### ISSUE THREAD

**Issue by TechnicallyFox** [pi-hole/pi-hole#388]
##### Expected Behavior:
Admin page Query Log should display readable list of queries

##### Actual Behavior:
data is improperly formatted. Domain names are getting cut off and from client is not displaying at all.  This is happening when page is accessed from any device. 
![screenshot-22](https://cloud.githubusercontent.com/assets/17700957/13783231/eacc3f1e-eaa0-11e5-89cf-13d47ebcbc7d.png)
Screen capture attached.

##### Steps to reproduce this issue:
This occurred after about a week of running.

Attempted to run updateDashboard.sh and piholeLogFlush.sh but issue persists.

**Comment by Mcat12** [comment]
This has been popping up recently for some reason. Some people's logs have their hostname in it, since don't. That means one type has an extra word in it. I'll work on a way to use the correct indexes by checking the length of the lines in the log.

**Comment by TechnicallyFox** [comment]
Let me know if any files/data are needed for analyzing or testing.

**Comment by dschaper** [comment]
Just an aside, thanks @TechnicallyFox for the Twitter work, I love it!

**Comment by badmark** [comment]
Can confirm. Error occurring on both a Raspberry Pi and a C.H.I.P. running Pi-Hole.

**Comment by Roemy** [comment]
See my issue and temp "solution" here: [Query Log](https://github.com/pi-hole/pi-hole/issues/376)

**Comment by badmark** [comment]
Worked like a charm. Fun with strings and sub-strings! Thanks Roemy.

**Comment by TechnicallyFox** [comment]
Thanks, worked to make data readable again.  However the steps in https://github.com/pi-hole/pi-hole/issues/376 produce data still a little bit off vs what was provided in the redit https://www.reddit.com/r/pihole/comments/49t4hp/query_log_not_being_parsed_correctly/ which seemed to work perfectly for me.

`   substr($exploded[5], 0),
                $exploded[6],
                $exploded[7],`

Produced:
![pi-hole_queries_after_mod](https://cloud.githubusercontent.com/assets/17700957/13822138/d62fbe5c-eb7a-11e5-9ce1-b14361e242ca.jpg)

And 
`substr($exploded[4], 6, -1),
$exploded[5],
$exploded[7],`
Produced:
![pi-hole_queries_after_mod2](https://cloud.githubusercontent.com/assets/17700957/13822154/ede56d12-eb7a-11e5-88f4-3631f9b8cbab.jpg)

**Comment by Roemy** [comment]
Indeed you're right, i've missed that part. I'll change my solution ;)

**Comment by PromoFaux** [comment]
@Mcat12 is this now fixed in the latest release of WebAdmin?

**Comment by DonLexos** [comment]
Yes it is.

**Comment by PromoFaux** [comment]
Super. Thanks @DonLexos !

**Comment by badmark** [comment]
Updated, new error message

![selection_032](https://cloud.githubusercontent.com/assets/7435884/14034546/7dc99676-f1fa-11e5-86f9-029e5d18ff93.png)

**Comment by PromoFaux** [comment]
Could you please run `updateDashboard.sh` then clear the cache  on your client machine and reload the page? There should be an extra column labelled 'status'

**Comment by badmark** [comment]
root@rpi:~# updateDashboard.sh 
Updating 4f20cc6..a5e2008
error: Your local changes to the following files would be overwritten by merge:
	data.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by badmark** [comment]
git fetch --all
git reset --hard origin/master

This fixed the error message but now it's just spinners, no data...

**Comment by Mcat12** [comment]
So after updating to the latest (1.1.6) it's having problems? Can you check `/var/log/lighttpd/error.log` for any errors?

**Comment by PromoFaux** [comment]
@badmark do another `sudo git pull` on the `/var/www/html/admin` directory (or `updateDashboard.sh`, which would have failed before because of the changes you made to `data.php`)

**Comment by badmark** [comment]
Already up-to-date.

**Comment by badmark** [comment]
Removed directories and re-ran install.sh - continue to receive this error, the CPU is pegged, and only spinners on the main page...
![selection_033](https://cloud.githubusercontent.com/assets/7435884/14045629/17c22334-f272-11e5-907a-8cd62b52711e.png)
