### ISSUE TITLE
 CONDITIONAL_FORWARDING_REVERSE may prevent Pi-hole from starting after update

### ISSUE THREAD

**Issue by Bucking-Horn** [pi-hole/pi-hole#3880]
### Versions
  Pi-hole version is v5.2 (Latest: v5.2)
  AdminLTE version is v5.2 (Latest: v5.2)
  FTL version is v5.3.1 (Latest: v5.3.1)

### Platform
Debian Buster

### Expected behavior

If present in `setupVars.conf`, CONDITIONAL_FORWARDING_REVERSE should be correctly converted to REV_SERVER_CIDR during updates, or ignored.

For example
`CONDITIONAL_FORWARDING_REVERSE=178.168.192.in-addr.arpa`
should result in
`REV_SERVER_CIDR=192.168.178.0/24`

### Actual behavior / bug

On updating Pi-hole to the latest version, if CONDITIONAL_FORWARDING_REVERSE is found in `setupVars.conf`, it's value is simply written to REV_SERVER_CIDR:
`REV_SERVER_CIDR=178.168.192.in-addr.arpa`

This results in the following dnsmasq option:
`rev-server=178.168.192.in-addr.arpa,192.168.178.1`

This in turn prevents pihole-FTL from starting, resulting in loss of DNS resolution until the offending entry is corrected at least in Pi-hole's dnsmasq configuration.
```
  [✓] Deleting existing list cache
  [✗] DNS service is not running
  [✓] Restarting DNS server
  [✗] DNS resolution is not available

  Unable to complete update, please contact Pi-hole Support
```

### Steps to reproduce

Add the following lines to `setupVars.conf` before updating an older Pi-hole version:
```
CONDITIONAL_FORWARDING=true
CONDITIONAL_FORWARDING_IP=192.168.178.1
CONDITIONAL_FORWARDING_DOMAIN=fritz.box
CONDITIONAL_FORWARDING_REVERSE=178.168.192.in-addr.arpa
```

Run `pihole -up`.

### Additional context

This behaviour may have been introduced by https://github.com/pi-hole/pi-hole/pull/3761.

**Comment by PromoFaux** [comment]
@Bucking-Horn, this should be resolved now in 5.2.1, can you confirm please?

**Comment by Bucking-Horn** [comment]
Will `pihole -up` still trigger that even if its up to date?
Or is there a way to manually trigger a setupVars.conf rewrite?

I'd like to avoid having to flash an older image to test it.

**Comment by Bucking-Horn** [comment]
Of course! ;)

As far as restarting pihole-FTL is concerned, the problem is fixed: 
No more offending entries in dnsmasq configurations are preventing it from starting.

However, while syntactically correct, not all old CONDITIONAL_FORWARDING options have been honored and converted into REV_SERVER options alike:
```
REV_SERVER=true
REV_SERVER_DOMAIN=fritz.box
REV_SERVER_TARGET=192.168.178.1
REV_SERVER_CIDR=10.1.1.0/24
```
This results in:
```
rev-server=10.1.1.0/24,192.168.178.1
```
It seems as if `CONDITIONAL_FORWARDING_REVERSE=178.168.192.in-addr.arpa` has been ignored.

This may leave some users with an incorrect CF configuration when updating from an older version.

However, this is also an edge-case where a user has upgraded to use REV_SERVER already while CONDITIONAL_FORWARDING remnants are still present in setupVars.conf (may have happened with Pi-hole 5), and where CF settings have changed in the meantime in addition.

**Comment by yubiuser** [comment]
Do you consider this issue as being solved in the mean time?

**Comment by XDAmaniac** [comment]
looks like it's not yet resolve, at least not while using non standard subnets (it may be a different subject)
docker run ...
  -e REV_SERVER='true' \
  -e REV_SERVER_TARGET='192.168.178.129' \
  -e REV_SERVER_DOMAIN='fritz.box' \
  -e REV_SERVER_CIDR='192.168.178.128/26' \
  -e CONDITIONAL_FORWARDING_REVERSE='129.128/26.178.168.192.in-addr.arpa' \
...
results in: 01-pihole.conf
rev-server=192.168.178.131/24,192.168.178.129
server=/fritz.box/192.168.178.129

f.y.i.
192.168.178.131 is the IP of the pihole container assigned macvlan bridge (pihole_net)
as per portainer shown as: 192.168.178.131/26

docker network inspect pihole_net
[
    {
        "Name": "pihole_net",
        ...
                    "Config": [
                {
                    "Subnet": "192.168.178.128/26",
                    "IPRange": "192.168.178.131/32",
                    "Gateway": "192.168.178.129"
                },
        ...
         
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5.1 (Latest: v5.5.1)
FTL version is v5.8.1 (Latest: v5.8.1)
