### ISSUE TITLE
Error on Update to 5.3.1 .... 

### ISSUE THREAD

**Issue by roe1974** [pi-hole/pi-hole#3881]
Hi
I had an error during the FTL update to version 5.3.1 that it did not recognize the operating system (Buster) and aborted. A pihole repair (only with "PIHOLE_SKIP_OS_CHECK=true") then performed the update..... is that normal ?
br, Richard

**Comment by PromoFaux** [comment]
The message indicates something went wrong. More information, as laid out in the issue template would help.

At the very least can we get a debug token, please? `pihole -d`

**Comment by roe1974** [comment]
I allready performed a 
PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
... so it works now...
can I still create a debug token afterwards ? 
br, Richard

**Comment by PromoFaux** [comment]
Yeah, debug tokens can be generated at any time. There is a check in the debug script that may show us what happened when you tried to update before

**Comment by roe1974** [comment]
here we go .....

https://tricorder.pi-hole.net/vhyme1rdmv

br & stay healthy !
Richard

**Comment by PromoFaux** [comment]
```
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  9
[i] dig response:  ;; connection timed out; no servers could be reached
[✗] Distro:  Raspbian
[✗] Error: Raspbian is not a supported distro (https://docs.pi-hole.net/main/prerequisites/)
```

This means that the installer was unable to reach the nameserver `ns1.pi-hole.net`, in order to get the list of supported OS's from the `TXT` record at `versions.pi-hole.net`

If you have some kind of redirect on all DNS queries at the firewall level, that's why. You'll need to add in an exception to allow the Pi-hole device to make outbound DNS queries instead of blocking them outright.

Or just use the PIHOLE_SKIP_OS_CHECK in future.

**Comment by roe1974** [comment]
There is no limitation on router/firewall
The router is using DoH DNS (https://security.cloudflare-dns.com/dns-query) .... is that the reason ?
.. and ns1.pi-hole.net is pingable from the router ....

 > ping ns1.pi-hole.net
  SEQ HOST                                     SIZE TTL TIME  STATUS                                                                                                    
    0 185.136.96.96                              56  54 43ms 
    1 185.136.96.96                              56  54 40ms 
    2 185.136.96.96                              56  54 45ms 
    3 185.136.96.96                              56  54 38ms 
    4 185.136.96.96                              56  54 39ms 
    5 185.136.96.96                              56  54 45ms 
    sent=6 received=6 packet-loss=0% min-rtt=38ms avg-rtt=41ms max-rtt=45m

both of the pihole's (prim and sec) are using the router as upstream DNS.

br, Richard

**Comment by PromoFaux** [comment]
What is the result of the following command on a client device (and one/both of the pi-holes)

`dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net`

Or, if the client is windows try `nslookup -type=txt versions.pi-hole.net ns1.pi-hole.net`

**Comment by roe1974** [comment]
result is

;; connection timed out; no servers could be reached (from both pi-hole's)

Richard

**Comment by roe1974** [comment]
With Windows Client an over LTE:

Server:  undefined.hostname.localhost
Address:  185.136.96.96

versions.pi-hole.net.xxxx.at  text =

        "expired"
(root)  nameserver = localhost

so it is a problem of the security DNS from Cloudflare 1.1.1.2 ???
br, Richard
