### ISSUE TITLE
Installer overwrites existing admin folder

### ISSUE THREAD

**Issue by B0ndo2** [pi-hole/pi-hole#3891]
The installer on Raspbian (info below) overwrites an existing folder with the name of admin under /var/www/html. I didn't choose lighthttpd during installation as I had Apache running with an existing admin folder.

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by dschaper** [comment]
Did you respond "OK" when asked if you wanted to install the web admin interface?

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1232

**Comment by B0ndo2** [comment]
I did and I wanted the web admin interface but it shouldn't overwrite and existing directory, after all the web server will most probably be shared.

**Comment by dschaper** [comment]
Were you using `/var/www/html/admin/` as a directory for another webserver.

**Comment by B0ndo2** [comment]
Yes, I have another application running under this directory (very common
nam)

**Comment by dschaper** [comment]
Okay, the release we just pushed a few minutes ago will no longer wipe that directory.

https://github.com/pi-hole/pi-hole/pull/3893
