### ISSUE TITLE
Unable to complete update, please contact Pi-hole Support

### ISSUE THREAD

**Issue by Daedalus-code** [pi-hole/pi-hole#3895]
```  [i] Storing downloaded domains in new gravity database...
  [✗] Unable to fill gravity table in database /etc/pihole/gravity_temp.db
  /tmp/tmp.btFZEZ6O6N.gravity:1788382: expected 2 columns but found 1 - filling the rest with NULL
/tmp/tmp.btFZEZ6O6N.gravity:1788382: INSERT failed: NOT NULL constraint failed: gravity.adlist_id
  [✓] Cleaning up stray matter
  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

  Unable to complete update, please contact Pi-hole Support```

**Comment by PromoFaux** [comment]
What version were you coming from? 

What have you tried to troubleshoot it?

Can you upload a debug token please?

(The template for a new issue is there to help us help you)

**Comment by Daedalus-code** [comment]
```
pi@raspberrypi:~ $ pihole -up -d -a
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!
pi@raspberrypi:~ $
```  

huh now it went through 👀 Is this the way to get a "token" ?  

```
-d, debug           Start a debugging session
                        Add '-a' to automatically upload the log to tricorder.pi-hole.net
``` 

I will close this for now, thanks for comment, looks like it's working.

![pihole](https://user-images.githubusercontent.com/59256533/101074712-5eb72600-35a1-11eb-9619-df41af422bb5.png)

**Comment by PromoFaux** [comment]
`-d` and `-a` are not valid arguments for `pihole -up`

For future reference it's just `pihole -d`... `pihole -up` is just for updating ;)

But it looks like it's all gone through OK now so.. fingers crossed it stays OK
