### ISSUE TITLE
Admin UI breaks if setupVars.conf contains comment with bracket

### ISSUE THREAD

**Issue by franz-josef-kaiser** [pi-hole/pi-hole#3897]
### Versions
- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform
- OS and version:  
        ```# uname -a
        Linux controller 5.4.0-1023-raspi #26-Ubuntu SMP PREEMPT Thu Nov 12 14:58:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux```
- Platform:  Raspberry Pi 4

### Expected behavior
I can access the settings page in the Admin UI, no matter if the `setupVars.conf` is broken, or not.

### Actual behavior / bug

Accessing the Settings in the Admin UI, brings up a big, red error message, containing the following message:
```text
There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected '(' in /etc/pihole/setupVars.conf on line 36 in /var/www/html/admin/settings.php:12
```

Broken:
- Settings page has error message above ☝️ 
- Full width page layout breaks back to centered/ max-width.

### Steps to reproduce

1. SSH into PiHole OS
1. Edit `/etc/pihole/setupVars.conf`
1. Add a `#`-Comment containing `# Some comment (test me)`
1. Open admin UI `<IP>.<OF>.<Pi>.<HOLE>/admin`
1. Open settings page
1. See error msg above

**Comment by dschaper** [comment]
Don't edit that file and add manual comments.

**Comment by franz-josef-kaiser** [comment]
@dschaper why not? What other place should I use to put config, if not there?

**Comment by PromoFaux** [comment]
What do you need to comment in the config file?

**Comment by yubiuser** [comment]
This file is read by php via `parse_ini_file`. Comments start with `;` and not `#`

https://www.php.net/manual/en/function.parse-ini-file.php

**Comment by dschaper** [comment]
It's also sourced as a file in other sections of the shell scripts and `;` lines will cause other issues.

It's a configuration file, it's not meant to have comments in it.

**Comment by franz-josef-kaiser** [comment]
@PromoFaux I just added notes for my later self. 

@dschaper Most `.conf` files come with comments per default. You can take a look at the `phpX-fpm.conf`, an `nginx.conf` or one of the PiHole lighttp conf files as examples.

The reason I edit the file and don't use the GUI is simple: Version control and deployment (just a local sync from NAS > PiHole rPi). That allows me to document my changes, which helps with tracking down problems later on.

**Comment by dschaper** [comment]
Great, what comment scheme should we support. Shell, YAML, TOML, `c`, single line comments, inline comments, block comments...

Or no comments, the file contains variables and their values, it's really pretty simple.

**Comment by franz-josef-kaiser** [comment]
@dschaper thanks for answering. As you mentioned, that the file is not meant to be edited directly: What should I do instead that supports all options? Or did you just mean to add no comments and manually editing the file is okay in all other context?

**Comment by dschaper** [comment]
Yes, it has and will continue to work without added comments. Editing the file and making manual changes is fine as long as you understand what changes you are making and what to do when they are not correct. And also realize that the contents of the file can and will change during regular use of Pi-hole.
