### ISSUE TITLE
Report: Pi 3 Pi-Hole

### ISSUE THREAD

**Issue by gh0stshell** [pi-hole/pi-hole#390]
Just wanted to report that my new Pi 3 running Pi-hole is working wonderfully even while running 64-bit OS. No issues to report other then what is already opening and not regarding new hardware or OS.

**Comment by Mcat12** [comment]
Nice! When I saw this, I was thinking "oh no! I don't have a pi3 to trouble shoot this new issue!" Good thing everything's working fine! :D

**Comment by dschaper** [comment]
Lol, I like all of you, but I stop at the free Zero's... I actually just picked up a Pi 3 today...

**Comment by PromoFaux** [comment]
My Pi3 has been sitting doing this whilst I've been away:
![image](https://cloud.githubusercontent.com/assets/1998970/13846182/36239afa-ec3d-11e5-9b0f-7afcaa060f2a.png)

**Comment by kmr2319** [comment]
@gh0stshell 
>while running 64-bit OS

What 64 bit OS are you running on the Pi 3? I thought there wasn't a suitable kernel yet??

**Comment by Palmer11** [comment]
I've been running it on the rpi3 for nearly a week I think now. No issues. Much better performance with the /admin panel. Data is retrieved almost instantaneously compared to the b+ taking several seconds.
