### ISSUE TITLE
Client group management page no longer can set custom client address

### ISSUE THREAD

**Issue by ndrone** [pi-hole/pi-hole#3901]
### Versions

- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.3.1

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

From the drop down there use to be a selection that would allow to you input your own custom ip address or network cidr.

### Actual behavior / bug
You are no longer allowed to define complete network subnets

### Steps to reproduce

1. Go to 'Client Network Management'
2. 'Try and fill out the known clients with an network subnet'
4. Click on add

**Comment by dschaper** [comment]
I assume you mean, Client Group Management in step 1?

I'm not seeing any problems, what error are you seeing? 

Would help to have that debug token.

**Comment by ndrone** [comment]
Crap... I went back to reproduce it and create the debug token for you. And it works, which means user error the first time. Closing the ticket. Thanks!
