### ISSUE TITLE
Pihole Webinterface White, Blacklist and Addlists not working Version v.5.2.1

### ISSUE THREAD

**Issue by platofan23** [pi-hole/pi-hole#3905]
Hello guys,

whenever i try to add a domain to the white or blocklist via webinterface I get an error. "Something went wront" (you can see on the picture attachment). Adding it over cli via pihole -w works fine.

So how can i solve that problem?

my output of pihole -d:
https://pastebin.com/ayXMEyzX

The error:
https://we.tl/t-pos9EIRra3

**Comment by yubiuser** [comment]
Please upload the debug token via `pihole -d` and poste the token here. It is almost unreadable with the formating.

How did you access the web interface? You're running apache on port 80 and lighthttpd on port 8080. Does it work with lightttpd?

**Comment by platofan23** [comment]
> 
> 
> Please upload the debug token via `pihole -d` and poste the token here. It is almost unreadable with the formating.
> 
> How did you access the web interface? You're running apache on port 80 and lighthttpd on port 8080. Does it work with lightttpd?

I just randomly solved the problem. My apache2 was on port 80 and lighthttpd on port 8080. now i switched the ports between the servers and it works =)
