### ISSUE TITLE
php8.0-json not found in installation script

### ISSUE THREAD

**Issue by aerogus** [pi-hole/pi-hole#3906]
### Versions

git clone repo to run the Installation script

### Platform

- OS and version:  Raspberry pi OS up to date (Debian 10.6)

- Platform:  Raspberry Pi 3

### Expected behavior

Pi hole application installed

### Actual behavior / bug

Pi hole application not installed, exitting in the middle of the installation because of an unknown package. The french error message :
```
E: Le paquet « php8.0-json » n'a pas de version susceptible d'être installée
```

PHP 8.0 is not available natively on raspberry pi OS but has been released in a stable version and could be installed with this popular repo :
```
deb https://packages.sury.org/php/ buster main
```

### Steps to reproduce

- Install raspberry pi OS
- Add sury repo in apt to install php8.0
- Run the pi hole installation script

### Hacky Solution

This solve my very specific problem but the fix has to be more elegant :
remove all hardcoded mention to php($version)-json in basic-install.sh

### Misc

When I try to install only the php8.0-json package here is the error :

```
# sudo apt-get install php8.0-json
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Le paquet php8.0-json est un paquet virtuel fourni par :
  php8.0-phpdbg 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
  php8.0-fpm 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
  php8.0-cli 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
  php8.0-cgi 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
  libphp8.0-embed 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
  libapache2-mod-php8.0 8.0.0~rc3-4+0~20201103.4+debian10~1.gbp19d1d8
Vous devez explicitement sélectionner un paquet à installer.

E: Le paquet « php8.0-json » n'a pas de version susceptible d'être installée
```

I don't know if php8.0-json is now merged with core php8.0 packages officialy or just with sury repo ...

The install script already have a condition with CentOS to not include the php json package because it is already installed by the core php package in this distribution.

**Comment by dschaper** [comment]
We don't support php8. It's not a native package as you have seen. To me this is not a bug.

**Comment by aerogus** [comment]
Ok no problem.
The day you would like to support php8, you'll know the trick to install the app.
By the way, it running pretty well despite the install _behaviour_
