### ISSUE TITLE
Conditional forwarding not working when using another DNS server

### ISSUE THREAD

**Issue by Noiden** [pi-hole/pi-hole#3907]
### Versions
- Pi-hole:  5.2.1
- AdminLTE:  8.5.1
- FTL:  5.3.2

### Platform
- OS and version:  Ubuntu 20.04.1 LTS

- Platform:  Docker 19.03.13, build 4484c46d9d

### Expected behavior

In the log under the client column, I should se the actual client trying and nost just my forwarding DNS server.

### Actual behavior / bug

I just see my DNS server under client.

### Steps to reproduce

1. Go to 'Query Log'
2. Check  'Client column'

## Debug Token

- URL:  https://tricorder.pi-hole.net/3qi62ardft

### Additional context

I don't know if this is possible when using another DNS server and just forwarding to the piHole or if I need to do some settings in the BIND DNS Server?

**Comment by dschaper** [comment]
What IP address do the clients use for DNS? Are they set to another DNS server that forwards it's queries to Pi-hole or do they query the Pi-hole directly? If they are not directly querying Pi-hole then there's no way for us to know what the IP of the client is.

**Comment by dschaper** [comment]
Ah, yes. So the queries are coming from 192.168.1.28
```
Dec  5 18:08:09 dnsmasq[586]: query[AAAA] raw.githubusercontent.com from 192.168.1.28
```
You've set that as the target for Conditional Forwarding so I'm going to assume that it's a DNS server. Clients are not actually querying Pi-hole directly so we don't know what the client IP is.

**Comment by Noiden** [comment]
Aha, exactly that is the BIND DNS Server, all clients use .28 as DNS and the .28 forwards the queries to the pihole.
Ok, so that setting is only if you use another DHCP server but use pihole as DNS on the clients.

It was sad, I thought the other DNS server could send with some info about this.

Ok, then I know that is not possible.

Thanks.
