### ISSUE TITLE
StevenBlack list blocking Windows internet connection detection, causes Windows 10 (others?) to report that there is no internet connection

### ISSUE THREAD

**Issue by realslacker** [pi-hole/pi-hole#391]
##### Expected Behaviour:
Computers connect to network with PiHole do not show an error message saying there is no internet connection.

##### Actual Behaviour:
Network connection icon in system tray shows error message and exclamation mark. Windows reports that you need to open a browser to login to the network.

##### Steps to reproduce this issue:
Install PiHole, set as DNS, restart Windows 10 computer

##### Possible Fix(es)

1. Add www.msftncsi.com and msftncsi.com to default whitelist or
2. Configure lighttpd to return 200 OK when file "http://www.msftncsi.com/ncsi.txt" is requested

I have confirmed that adding www.msftncsi.com and msftncsi.com to my whitelist has eliminated the problem on our network.

**Comment by PromoFaux** [comment]
Hi @realslacker , thanks for your input.

[this is actually an FAQ in the wiki](https://github.com/pi-hole/pi-hole/wiki/FAQs#windows-thinks-there-is-no-internet-connection-but-there-is-one-315), as it's come up a few times. I'll leave it open for now, however, as it will make the fix easier to find for those scanning the issues..

**Comment by realslacker** [comment]
Ah, sorry @PromoFaux  I did not see that... I think my google-fu is lacking!

Have you guys considered adding it to the default whitelist?

**Comment by PromoFaux** [comment]
> default whitelist

This is something we're trying to avoid.. If we whitelist one seemingly benign site as default, what's to say we're not going to add a malicious site to that whitelist? What if ad-company x paid us handsomely to whitelist their site by default? Would we do it? No, we certainly wouldn't! So it's better for our reputation in the long run to say that we just wont whitelist any sites.

**Comment by realslacker** [comment]
That makes sense, thanks!
