### ISSUE TITLE
CNAME Records does not work

### ISSUE THREAD

**Issue by g3ck000** [pi-hole/pi-hole#3913]
### Versions

- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform

- OS and version:  Ubuntu Server 20.04 LTS (GNU/Linux 5.4.0-52-generic x86_64)

- Platform:  Virtual Machine on WIN10-PC
### Expected behavior

The Local CNAME Records does not work. 
The Pi hole does not forward the Domain to a Target Domain even after restarting dns resolver and also after restarting the OS.
Additonaly it is not possible to delete CNAME records from the list. 

I found this on lighttpd/error.log:
2020-12-07 09:31:16: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Executing sudo pihole -a removecustomcname reports http://dwh/reports failed. in /var/www/html/admin/scripts/pi-hole/php/func.php on line 79

**Comment by dschaper** [comment]
Debug token as requested please.

**Comment by g3ck000** [comment]
> 
> 
> Debug token as requested please.

**Comment by g3ck000** [comment]
My VM has some problems with the internet connect and so i updated my raspberry pi (also the pi-hole). The same problem.

Versions

    Pi-hole: 5.2.1
    AdminLTE: 5.2.1
    FTL: 5.3.2

Platform

    OS and version: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1015-raspi aarch64)

    Platform: raspberry pi 3b

Expected behavior

The Local CNAME Records does not work.
The Pi hole does not forward the Domain to a Target Domain even after restarting dns resolver and also after restarting the OS.
Additonaly it is not possible to delete CNAME records from the list.
 
Debug token: https://tricorder.pi-hole.net/xiw7v0713c

**Comment by g3ck000** [comment]
> 
> 
> Do you control the target domain? Does the CNAME point to a domain that is resolve by the upstream?
> 
YES (Ubuntu Server with Apache2)
> A limitation of CNAME records is that `pihole-FTL` needs to be aware of the A/AAAA value of the target. You can't CNAME `bing.com` to `google.com`.

OK

Now i have the debug token from my VM : https://tricorder.pi-hole.net/iq2d7tvtcd

**Comment by g3ck000** [comment]
DNS Record:
![grafik](https://user-images.githubusercontent.com/74103312/102467607-c749dc80-4050-11eb-8f23-5e55919341b1.png)

CNAME Record:
![grafik](https://user-images.githubusercontent.com/74103312/102467717-e9435f00-4050-11eb-8857-011732fd700b.png)

**Comment by PromoFaux** [comment]
I may be wrong here, but I don't think I am, it seems you are confused about the usage of `CNAME` records

Your target contains a `/` as though you are trying to redirect to another URL. DNS does not know about anything other than the domain. e.g, it can read `test-domain.de` as a `CNAME` for `test2-domain.de`. 

That'll be why it's not working as you expect

**Comment by g3ck000** [comment]
> 
> 
> I may be wrong here, but I don't think I am, it seems you are confused about the usage of `CNAME` records
> 
> Your target contains a `/` as though you are trying to redirect to another URL. DNS does not know about anything other than the domain. e.g, it can read `test-domain.de` as a `CNAME` for `test2-domain.de`.
> 
> That'll be why it's not working as you expect

You're right. My fault.... But i cant delete the wrong entries.

**Comment by yubiuser** [comment]
>  But i cant delete the wrong entries.

They are stored in `/etc/dnsmasq.d/05-pihole-custom-cname.conf `

Try editing the file manually and restart pihole-ftl

**Comment by g3ck000** [comment]
> 
> 
> > But i cant delete the wrong entries.
> 
> They are stored in `/etc/dnsmasq.d/05-pihole-custom-cname.conf `
> 
> Try editing the file manually and restart pihole-ftl

I know. Thanks.
But why can i add a invalid cname and cant remove it through the UI? Unfortunately, there is no validation at this point.

**Comment by yubiuser** [comment]
Not having an validation on adding the entrie is a bug. You're the second one reporting this behavior.
