### ISSUE TITLE
CNAME Records not working as expected

### ISSUE THREAD

**Issue by Berserkir-Wolf** [pi-hole/pi-hole#3915]
### Versions

- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform

- OS and version:  Ubuntu Server 18.04.5 LTS

- Platform:  Hyper-V Guest

### Expected behavior
On adding a CNAME record for an entry, I expected to be able to resolve the address by the new DNS entry.

### Actual behavior / bug

On performing an nslookup from my pc (using the pihole as the server), the record returns a blank response - no address found.

### Steps to reproduce

Method 1:
1. Go to 'Local DNS'.
2. Click on 'CNAME Records'.
3. Add a new CNAME record.
4. Restart pihole VM.
5. Attempt to query new address.
6. No resolution.

Method 2:
1. Go to 'Local DNS'.
2. Click on 'CNAME Records'.
3. Add a new CNAME record.
4. Update gravity.
5. Attempt to query new address.
6. No resolution.

## Debug Token

- URL:  

https://tricorder.pi-hole.net/aoqx69ze9t

### Screenshots

< Not applicable. >

### Additional context

< None >

**Comment by dschaper** [comment]
I'm not able to duplicate:

![Screenshot 2020-12-07 123846](https://user-images.githubusercontent.com/2782850/101402921-4557f780-3889-11eb-845d-539ea739f7fb.png)

```plain
dan@raspberrypi:~ $ dig not.google.com @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> not.google.com @127.0.0.1

;; ANSWER SECTION:
not.google.com.         2       IN      CNAME   bing.com.

dan@raspberrypi:~ $ pihole -g
  [i] Neutrino emissions detected...

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
dan@raspberrypi:~ $ dig not.google.com @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> not.google.com @127.0.0.1

;; ANSWER SECTION:
not.google.com.         2       IN      CNAME   bing.com.

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Dec 07 12:39:08 PST 2020
;; MSG SIZE  rcvd: 65
```

That 3 msec tells me it did not come from cache.

**Comment by Berserkir-Wolf** [comment]
I can dig the address, and it comes back properly. I can't ping it or nslookup it - only dig, for some reason.
Pinging gives the same issue in CMD and in BASH.
(PiHole is on 192.168.1.249)

When querying via bash on windows:
```
dyson@TECH-DP:/mnt/c/Users/dyson$ dig yourmum.site.co.nz

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> yourmum.site.co.nz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13291
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;yourmum.bal.co.nz.             IN      A

;; ANSWER SECTION:
yourmum.site.co.nz.      2       IN      CNAME   expected.target.com.

;; Query time: 0 msec
;; SERVER: 192.168.1.249#53(192.168.1.249)
;; WHEN: Tue Dec 08 10:05:10 NZDT 2020
;; MSG SIZE  rcvd: 79

dyson@TECH-DP:/mnt/c/Users/dyson$ ping yourmum.site.co.nz
ping: yourmum.site.co.nz: Name or service not known
```

Via CMD on the same machine:
```
C:\Users\dyson>nslookup yourmum.site.co.nz 192.168.1.249
Server:  pihole
Address:  192.168.1.249

Name:    yourmum.site.co.nz

ping yourmum.site.co.nz
Ping request could not find host yourmum.site.co.nz. Please check the name and try again.
```

Via SSH to the pihole directly:
```
root@pihole:~# dig yourmum.site.co.nz

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> yourmum.site.co.nz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19202
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;yourmum.bal.co.nz.             IN      A

;; ANSWER SECTION:
yourmum.site.co.nz.      2       IN      CNAME  expected.target.com.

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Dec 07 21:01:41 UTC 2020
;; MSG SIZE  rcvd: 79


ping yourmum.site.co.nz
ping: yourmum.site.co.nz: Name or service not known
```

**Comment by Berserkir-Wolf** [comment]
I've also ensured the old conditional forwarder for my domain is no longer active, as I used to use a routerboard to do custom dns for testing/internal use. The only conditional forwarder in play is for my AD environment, which is working as expected.

**Comment by dschaper** [comment]
@DL6ER CNAME should query the returned value for the A record?

**Comment by Berserkir-Wolf** [comment]
I just completely removed 05-cname*** from etc/dnsmasq.d and re-added the entry, restarted the VM, and now it is resolving as expected.

**Comment by Berserkir-Wolf** [comment]
Not sure what the problem was - I presume that it being created while conditional forwarders were handling that domain prior confused it.
