### ISSUE TITLE
"Listen on all interfaces" Interface listening behaviour does not recognize local devices properly after reboot

### ISSUE THREAD

**Issue by mteuscher** [pi-hole/pi-hole#3917]
### Versions

- Pi-hole:  v5.2.1
- AdminLTE:  v5.2.1
- FTL:  v5.3.2

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi 4B 4GB

### Expected behavior

DNS Resolving to work after a reboot of the device

### Actual behavior / bug

Local DNS queries are recognized as non-local
`dnsmasq[683]: Ignoring query from non-local network`

### Steps to reproduce

1. Set Interface listening behaviour to "Listen on all interfaces" (in admin panel under settings -> DNS)
2. Reboot system
3. Try to resolve domains

## Debug Token

- saved localy, can be provided before and after fix if required. Never expected it to be a potential error in pi-hole, so never uploaded to tricorder. I compared them and only change really is, that after the fix resolving using the own local adress works.
Before fixing the issue:
````
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.0.11/24 matches the IP found in /etc/pihole/setupVars.conf
[✓] IPv6 address(es) bound to the eth0 interface:
   fd00::9569:69ff:9170:1edb matches the IP found in /etc/pihole/setupVars.conf
   2001:4dd5:1d09:0:2e25:1acd:3f73:f1d does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.
pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   fe80::6ba2:d444:a274:ae80 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.ne
t/t/use-ipv6-ula-addresses-for-pi-hole/2127)

   ^ Please note that you may have more than one IP address listed.
   As long as one of them is green, and it matches what is in /etc/pihole/setupVars.conf, there is no need for concern.

   The link to the FAQ is for an issue that sometimes occurs when the IPv6 address changes, which is why we check for it.

[i] Default IPv4 gateway: 192.168.0.1
   * Pinging 192.168.0.1...
[✓] Gateway responded.
[i] Default IPv6 gateway: fe80::ca0e:14ff:fe00:2f37
   * Pinging fe80::ca0e:14ff:fe00:2f37...
[✓] Gateway responded.

*** [ DIAGNOSING ]: Ports in use
[::1]:631 cupsd (IPv6)
127.0.0.1:631 cupsd (IPv4)
*:22 sshd (IPv4)
*:22 sshd (IPv6)
127.0.0.1:5335 unbound (IPv4)
[::1]:5335 unbound (IPv6)
[80] is in use by lighttpd
[80] is in use by lighttpd
[53] is in use by pihole-FTL
[53] is in use by pihole-FTL
[4711] is in use by pihole-FTL
[4711] is in use by pihole-FTL
*:1883 docker-pro (IPv6)
*:8123 python3 (IPv4)
*:8123 python3 (IPv6)

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] freesolution3.com is 0.0.0.0 via localhost (127.0.0.1)
[✗] Failed to resolve freesolution3.com via Pi-hole (192.168.0.11)
[✓] doubleclick.com is 216.58.210.14 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] bigdickshotchicks.blogspot.de is :: via localhost (::1)
[✗] Failed to resolve bigdickshotchicks.blogspot.de via Pi-hole (fd00::9569:69ff:9170:1edb)
[✓] doubleclick.com is 2a00:1450:4001:81e::200e via a remote, public DNS server (2001:4860:4860::8888)
````

### Additional context

Additionally installed are Wireguard (through pivpn after pihole was installed), docker, unbound
Potentially related to the following issues: #3108 #2898
For me however the admin panel was always reachable. The pi itself always had internet-connectivity (through localhost is my assumption).

For me this is not an issue anymore, as i was able to finally get completely rid of it. I wrote this because there *might* be an actual issue in pi-hole and potentially it helps other users with similiar problems.

### How to fix as a user (all of them worked for me)

1) run pihole -r select repair (but the issue is still present again after a reboot)
2) Restart DNS resolver
3) Set Interface listening behaviour to "Listen on all interfaces, permit all origins"
4) Set Interface listening behaviour to "Listen only on interface eth0" (to maintain wireguard functionality, add the following line in /etc/dnamasq.d/02-pivpn.conf: `interface=wg0`)

Please note: 1 and 2 are only temporary fixes until the next reboot. 3 and 4 are permanent fixes for me.

**Comment by dschaper** [comment]
Are the interfaces up before `pihole-FTL` is started?

**Comment by dschaper** [comment]
Oh, if you set `listen on all interfaces` and then add in `interface=wg0` as a configuration file then you will lock `pihole-FTL` to the `interface`. Listen on all removes any `interface` line set by Pi-hole, and thus the only `interface` listed is `wg0` and that's not good.

There was bug in Pi-vpn that they fixed that should not be setting `interface` lines in `02-pivpn.conf` and that file should not exist. I don't think they have the capability to detect when users make changes to interface selections based on our web interface and thus hard coded `interface` lines will cause things to not work.

**Comment by dschaper** [comment]
https://github.com/pivpn/pivpn/issues/946#issuecomment-594994334

**Comment by dschaper** [comment]
Fix was in https://github.com/pivpn/pivpn/commit/5b2bc9ba70a24250246da8c942a31e123a431096

**Comment by mteuscher** [comment]
To clarify: i only added `interface=wg0` after i restricted pi-hole to only use eth0 (solution 4 in my original post). I double checked that pihole added the `interface=eth0` in it's own dnsmasq config file. So i don't have that problem. But you are right, one should be aware of that!
I wanted to avoid setting it to allow from all originis, since i don't know if I won't at some point expose port53 in my router for some reason and have forgotten about it. This way i don't breach security (without realising), just mess up my conectivity. 
I read in the syslog, and I *think* that the interfaces were up before pihole-FTL started.
I'm gonna break my setup again, confirm that the bug is present again, enable wait on interfaces on boot in raspi-config and see if that solves it.
Or do you have a better idea how i should best test it?

**Comment by dschaper** [comment]
1. Interfaces that come up after `pihole-FTL` is running will not be recognized.
2. Don't EVER open port 53 in your router to expose that to the world. There is not a single valid reason to do that.
3. Changing the listen on buttons on the web interface will dynamically change `interface` lines, or remove them completely. Adding in additional configuration files with `interface` lines that Pi-hole does not know about will only lead to broken setups with long debugging sessions to find out why.

**Comment by mteuscher** [comment]
reply to 1.: I have read that browsing the available resources but now in hindsight seem to have misinterpreted my syslog.
reply to 2.: Didn't plan to, but thanks for emphasizing
reply to 3.: Didn't want to make your job more difficult. Feel free to edit my original post, or I can do it.

Thanks for your time!

I could reproduce the error, but forcing the pi to wait on the network on boot fixed it. I'm sorry I wasted your time, i guess I misinterpreted the following

```
Dec 10 19:02:47 raspi4 systemd[1]: Started Raise network interfaces.
**Dec 10 19:02:47 raspi4 systemd[1]: Reached target Network.**
Dec 10 19:02:47 raspi4 systemd[1]: Starting Permit User Sessions...
Dec 10 19:02:47 raspi4 systemd[1]: Reached target Network is Online.
Dec 10 19:02:47 raspi4 systemd[1]: Starting LSB: pihole-FTL daemon...
Dec 10 19:02:47 raspi4 systemd[1]: Starting /etc/rc.local Compatibility...
Dec 10 19:02:47 raspi4 systemd[1]: Starting Lighttpd Daemon...
Dec 10 19:02:47 raspi4 systemd[1]: Starting containerd container runtime...
Dec 10 19:02:47 raspi4 systemd[1]: Starting RPi Reporter MQTT Client/Daemon...
Dec 10 19:02:47 raspi4 systemd[1]: Starting OpenBSD Secure Shell server...
Dec 10 19:02:47 raspi4 systemd[1]: Starting Unbound DNS server...
Dec 10 19:02:47 raspi4 systemd[1]: Condition check resulted in fast remote file copy program daemon being skipped.
Dec 10 19:02:47 raspi4 systemd[1]: Started Permit User Sessions.
Dec 10 19:02:47 raspi4 systemd[1]: Started /etc/rc.local Compatibility.
Dec 10 19:02:47 raspi4 systemd[1]: Starting Hold until boot process finishes up...
Dec 10 19:02:47 raspi4 systemd[1]: Starting Terminate Plymouth Boot Screen...
[...]
Dec 10 19:02:50 raspi4 pihole-FTL[466]: FTL started!
Dec 10 19:02:50 raspi4 systemd[1]: Started LSB: pihole-FTL daemon.
Dec 10 19:02:50 raspi4 systemd[1]: Reached target Multi-User System.
Dec 10 19:02:50 raspi4 systemd[1]: Starting Docker Application Container Engine...
Dec 10 19:02:50 raspi4 systemd[1]: Starting Update UTMP about System Runlevel Changes...
Dec 10 19:02:50 raspi4 systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
Dec 10 19:02:50 raspi4 systemd[1]: Started Update UTMP about System Runlevel Changes.
Dec 10 19:02:51 raspi4 kernel: [   13.273418] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
```
