### ISSUE TITLE
v5.2.1: DNS stops working after some hours - requires hard reboot

### ISSUE THREAD

**Issue by sostopher** [pi-hole/pi-hole#3918]
### Versions

 - Pi-hole version is v5.2.1 (Latest: v5.2.1)
 - AdminLTE version is v5.2.1 (Latest: v5.2.1)
 - FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi 3 B

### Expected behavior

DNS works without needing to reboot the machine (as it previously did on versions before 5.2).

### Actual behavior / bug

DNS stops working at random times and does not resolve any requests. This is also noted in the query log, screenshot below (where they start again is after a reboot). 

### Steps to reproduce

1. Set up a new v5.2.1 installation
2. Wait some time (5-12 hours)
3. Note DNS is not working
4. Reboot
5. Issue usually resolved

## Debug Token

- URL:  https://tricorder.pi-hole.net/ajy809jsve

### Screenshots

![Screen Shot 2020-12-11 at 8 59 16 am](https://user-images.githubusercontent.com/14196975/101834971-2b6f2b00-3b8f-11eb-8f31-3f34160b27a0.png)

### Additional context

Also reports from Reddit:

https://www.reddit.com/r/pihole/comments/kaepin/help_ever_since_upgrading_to_v521_my_network/
https://www.reddit.com/r/pihole/comments/k5jimg/pihole_coreweb_v521_and_ftl_v532_released/gexq1ue/

**Comment by sostopher** [comment]
Seems possibly the same/related to https://github.com/pi-hole/FTL/issues/972

**Comment by aeri** [comment]
Same problem, the server is not responding after random time. For me the problem is solved after a few minutes. It only happens to me since the last update.

**Comment by Pansenschim** [comment]
Hey guys, did someone find a solution, like "go to dev branch" or soemthing?

**Comment by Pansenschim** [comment]
@sostopher, 
in my case this could be related to regex, whitelists and blacklists: I recently added "Pi Hole Switch" to Chrome, one can change the operating-status and add websites to the white- and blacklist. I added a webpage to the whitelist some minutes ago and FTL/DNS stoped working again.

**Comment by klentz-12** [comment]
Not sure if the issue is related but I do have the DNS service randomly quit on me. I do not reboot but I restart the DNS service.

**Comment by julesfarrow** [comment]
Experiencing the same but on v5.2 as well as v5.2.1 - RPi 4 8GB on Raspbian. Restarting DNS service sorts it out, seems to happen about once per week.

**Comment by Chlorus** [comment]
I might be having a similar issue - pihole with dig times out, but the same queries against the dnscrypt-proxy instance I have it forwarding to work fine. The only suspicious thing I've found so far in pihole-FTL.log is: 

```
[2021-01-02 08:02:01.114 15804/F578] TCP worker already terminating!
[2021-01-02 08:02:01.140 15803/F578] TCP worker already terminating!
```


I only got hit with the issue in the past week or so, long after I last upgraded pihole in early December, so not sure if this is the same as what you guys are seeing.

**Comment by dschaper** [comment]
There have been a few releases since this issue was opened. 

If you are still seeing problems then please open new issues, filling out the templates in full and including debug tokens as requested.
