### ISSUE TITLE
domain that is not blocked, does not resolve

### ISSUE THREAD

**Issue by smcclosr** [pi-hole/pi-hole#3923]
### Versions

- Pi-hole:  Pi-hole version is v5.2.1 (Latest: v5.2.1)
- AdminLTE:  AdminLTE version is v5.2.1 (Latest: v5.2.1)
- FTL:  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform

- OS and version:  CentOS 8

- Platform:  VMware vSphere 6.7

### Expected behavior

I am expecting that the website link.patch.com will resolve to a DNS record.  It is not blocked it pi-hole and it is available to upstream DNS

### Actual behavior / bug

When doing a ping to link.patch.com, it does not resolve, nor does it show it is blocked in the logs

### Steps to reproduce

1. Go to 'command prompt'
2. type  'ping link.patch.com'
3. See Error

## Debug Token

- URL:  https://tricorder.pi-hole.net/h2lii89bzt

### Screenshots

![2020-12-13 (2)](https://user-images.githubusercontent.com/16906361/102041179-b5d8aa00-3d9c-11eb-8acf-a3e11f6911c1.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
What's the difference between `192.168.11.1` and `192.168.11.2`? The former does resolve the domain.

In your debug log there are some `  Dec 13 00:00:02 dnsmasq[31032]: reply error is SERVFAIL` from your upstream servers.

**Comment by dschaper** [comment]
First, your lists are not correct, I note you have a number of lists hosted locally, they have incorrect domains in them:

```plain
   ----- First 10 Gravity Domains -----
   localhost.localdomain
   localhost.localdomain
   localhost.localdomain
   localhost.localdomain
   localhost.localdomain
```

**Comment by dschaper** [comment]
Second, 192.168.11.1 nor 192.168.11.2 are upstream DNS servers:

```plain
    PIHOLE_DNS_1=4.2.2.1
    PIHOLE_DNS_2=4.2.2.2
    PIHOLE_DNS_3=1.1.1.1
    PIHOLE_DNS_4=1.0.0.1
```

`192.168.11.2/24` seems to be the IP of the Pi-hole node and as Yubiuser notes, there are failures with Pi-hole talking to upstreams:

```
   Dec 13 00:00:02 dnsmasq[31032]: reply error is SERVFAIL
```

Pi-hole is functioning:

```plain
   [2020-12-13 22:31:46.475 183164M]  -> Total DNS queries: 93492
   [2020-12-13 22:31:46.475 183164M]  -> Cached DNS queries: 17139
   [2020-12-13 22:31:46.475 183164M]  -> Forwarded DNS queries: 30825
   [2020-12-13 22:31:46.475 183164M]  -> Blocked DNS queries: 42905
   [2020-12-13 22:31:46.475 183164M]  -> Unknown DNS queries: 0
   [2020-12-13 22:31:46.475 183164M]  -> Unique domains: 2953
   [2020-12-13 22:31:46.475 183164M]  -> Unique clients: 25
   [2020-12-13 22:31:46.475 183164M]  -> Known forward destinations: 4
```

Does `link.patch.com` show in the admin page under the query log?

**Comment by dschaper** [comment]
Lastly, I note you added the domain manually from the query list:

```
   20    0           1  0             link.patch.com                                                                                        2020-12-12 13:16:52  2020-12-12 13:16:52  Added from Query Log 
```

It's been added to group 0 only, so if your above `nslookup` was from a client that is not in group 0 and `link.patch.com` is on one of your blocklists then you'll see the domain being blocked.

**Comment by smcclosr** [comment]
> 
> 
> What's the difference between `192.168.11.1` and `192.168.11.2`? The former does resolve the domain.
> 
> In your debug log there are some ` Dec 13 00:00:02 dnsmasq[31032]: reply error is SERVFAIL` from your upstream servers.

192.168.11.1 is my pfSense gateway router that also has DNS.  It was my previous DNS server before the pi-hole installation
192.168.11.2 is the pi-hole that I want to use as my whole network DNS

**Comment by smcclosr** [comment]
> localhost.localdomain

OK, that helped a lot.  Here is a search of localhost.localdomain from my lists:

 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   localhost.localdomain (disabled)
 Match found in https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt:
   localhost.localdomain (disabled)

I disabled those lists and once that was done, the system will respond properly.  I am guessing since they are non-autourative aliases, it needs to be queried twice, and thus fails

**Comment by smcclosr** [comment]
> 
> 
> Lastly, I note you added the domain manually from the query list:
> 
> ```
> Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
>  id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment                                           
>    ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
>    20    0           1  0             link.patch.com                                                                                        2020-12-12 13:16:52  2020-12-12 13:16:52  Added from Query Log 
> ```
> 
> It's been added to group 0 only, so if your above `nslookup` was from a client that is not in group 0 and `link.patch.com` is on one of your blocklists then you'll see the domain being blocked.

That is good to know, how does a whitelist get added to multiple / all groups?

**Comment by dschaper** [comment]
Go to Group Management>Domains and assign it to the groups you'd like:

![Screenshot 2020-12-14 094817](https://user-images.githubusercontent.com/2782850/102116217-81dba400-3df1-11eb-8d42-d738cbae1b14.png)

**Comment by smcclosr** [comment]
> 
> 
> Go to Group Management>Domains and assign it to the groups you'd like:
> 
> ![Screenshot 2020-12-14 094817](https://user-images.githubusercontent.com/2782850/102116217-81dba400-3df1-11eb-8d42-d738cbae1b14.png)

DOH! didn't even see that.  Thanks!!

**Comment by aravindvnair99** [comment]
@smcclosr You can close the issue if it's resolved.
