### ISSUE TITLE
The malwaredomains default list has been deprecated

### ISSUE THREAD

**Issue by fhriley** [pi-hole/pi-hole#3925]
The default block list in pi-hole defined [here](https://github.com/pi-hole/pi-hole/blob/41479524f84ad1c08ee515181e47d0c1f4a81f4f/automated%20install/basic-install.sh#L1310) has been deprecated. The last time it was updated was August 13, 2020, and [they stated it is deprecated](https://riskanalytics.com/community/).

**Comment by yubiuser** [comment]
Removing this would leave just one "default" adlist.... should we do it anyway? Or are we fearing a lot of support follow up questions: "Where do I get adlists from"?

**Comment by dschaper** [comment]
>We have merged AutoShun and Malware Domains, and have integrated those technologies into ShadowNet.

>We will continue to make a free, non-commercial version of our threat intel, ShadowNet,

Though I don't see a date on the file, or a header, when I curl it so I don't know how the date of August 13 was landed on. 

Site says Nov 30 for shutting off the feeds but the lists still exist.

>As of November 30th, 2020, both AutoShun and Malware Domains feeds will be shut off

**Comment by fhriley** [comment]
> Though I don't see a date on the file, or a header, when I curl it so I don't know how the date of August 13 was landed on.

https://mirror1.malwaredomains.com/files and search for `justdomains`

**Comment by dschaper** [comment]
> Removing this would leave just one "default" adlist.... should we do it anyway?

If this is a rename of an existing list then we should probably point to the new URL.


> Or are we fearing a lot of support follow up questions: "Where do I get adlists from"?

More than we have now?

**Comment by clairmont32** [comment]
According to the file timestamps, the latest domain list is from Aug-2020 and there are a LOT of ancient files, which may not be serving ads or malware still. I'm wondering how reliable this set of domain lists is going to be if they havent updated it in a few months and seem to be treating it as an archive location.

**Comment by Kashalls** [comment]
> > Though I don't see a date on the file, or a header, when I curl it so I don't know how the date of August 13 was landed on.
> 
> https://mirror1.malwaredomains.com/files and search for `justdomains`

They removed the /files endpoint now.

**Comment by sjhgvr** [comment]
16516 out of the 26806 listed on https://mirror1.malwaredomains.com/files/justdomains didn't resolve anyways.

**Comment by JJJ** [comment]
> Removing this would leave just one "default" adlist.... should we do it anyway

I think yes. Removing it avoids user confusion.

There is no indication at their [new website](https://riskanalytics.com/community/) that the `justdomains` URL will ever resolve again. If Risk Analytics comes up with a new list, it can always be added in a future Pi Hole release.

**Comment by PromoFaux** [comment]
It will already be removed for new users in the next release. We don't have any mechanisms to remove it from existing users installs - so that will need to be manual.

**Comment by JJJ** [comment]
> It will already be removed for new users in the next release. We don't have any mechanisms to remove it from existing users installs - so that will need to be manual.

Perhaps the list UI could have a status/warning someday? Probably out of scope for this issue, but would be convenient to see the same information there that you can see on the command line.

**Comment by yubiuser** [comment]
It's been working on

https://discourse.pi-hole.net/t/info-uber-tote-listen/42098/19?u=yubiuser

**Comment by StevenBlack** [comment]
Hello everyone, I dropped the Malware Domain List awhile ago already, so it's not coming to Pi-Hole via my amalgamated lists.

It's been significant time since MDL was updated in any meaningful way.  We talked about dropping it for more than a year, maybe two.  So the reference to August isn't substantive unless you mean 08/2018 or thereabouts.

**Comment by pheiduck** [comment]
Still exist on latest version
  Current Pi-hole version is v5.2.3.
  Current AdminLTE version is v5.3.
  Current FTL version is v5.4.

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✗] Status: Not found
  [✗] List download failed: no cached list available

**Comment by dschaper** [comment]
You'll have to remove the list if it was installed prior. We don't remove lists from users installs.

**Comment by eshack94** [comment]
I am experiencing this same issue, presumably for the same reason.

Questions:
* Is there any negative consequence of this list no longer existing? Are there updates that won't be incorporated into the domains list that were previously supplied through this link?
* Is there an alternative way to get access to a new version of this list?
* Are there other recommended lists that one should add in lieu of this link being killed?

Thanks for any help. I'm a bit new to piHole.

**Comment by yubiuser** [comment]
> Is there an alternative way to get access to a new version of this list?

This list does not exist anymore. Where do you want to get a new version from? Maybe someone is hosting and maintaining the list elsewhere - but how would you recognize it was once this old list?

> Are there other recommended lists that one should add in lieu of this link being killed?

Good starting point would be https://firebog.net/

**Comment by yubiuser** [comment]
This list has been removed by the linked PR which is part of any new Pi-hole installation
https://discourse.pi-hole.net/t/pi-hole-core-v5-2-3-web-v5-3-and-ftl-v5-4-released/43009
