### ISSUE TITLE
Some repeated requests are not cached

### ISSUE THREAD

**Issue by kolya182** [pi-hole/pi-hole#3926]
### Versions

- Pi-hole:  v5.3.1 
- AdminLTE:  v5.2.1
- FTL:  v5.3.2

### Platform
- Platform:  Raspberry Pi, Docker 

### Expected behavior

Responde as `OK (cached)`
<img width="979" alt="Screen Shot 2020-12-15 at 1 30 38 PM" src="https://user-images.githubusercontent.com/3277207/102276306-7369b700-3edb-11eb-9252-52f1474987f8.png">

### Actual behavior for some domains

I'm struggling to understand why `pihole` makes request to DNS when same url was queried minutes ago.
<img width="977" alt="Screen Shot 2020-12-15 at 1 34 54 PM" src="https://user-images.githubusercontent.com/3277207/102276297-706ec680-3edb-11eb-9508-9d0872c19f26.png">
<!-- 
Token generated by running `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger

The token is displayed at the end of the debug process if you allow for uploading the log file. 

Example of request cached after two attempts:
<img width="967" alt="Screen Shot 2020-12-15 at 1 54 28 PM" src="https://user-images.githubusercontent.com/3277207/102277626-6948b800-3edd-11eb-90a2-bfb95f6be91e.png">

**Comment by dschaper** [comment]
`www.apple.com` is a CNAME for the actual host your will be routed to. While the TTTL (The Time-To-Live or the time we cache it for) is 30 minutes, the final A record you will get back from that query has a TTL of 20 seconds. 

![Screenshot_2020-12-15 Network Tools DNS,IP,Email](https://user-images.githubusercontent.com/2782850/102279982-2c7ec000-3ee1-11eb-85d3-a5fc05fe8ad7.png)
