### ISSUE TITLE
new today 20201215 

### ISSUE THREAD

**Issue by Michel13100** [pi-hole/pi-hole#3927]
pi@raspberrypi:~ $ sudo curl -sSL https://install.pi-hole.net | sudo bash
curl: (6) Could not resolve host: install.pi-hole.net

**Comment by PromoFaux** [comment]
This doesn't really give us a lot to go on (there is a template for  reason, you know 😉) 

What have you tried? As far as I can see the link to `install.pi-hole.net` is working, so it looks to be an issue resolving it on your Pi. Are you able to resolve it with `nslookup install.pi-hole.net`?

**Comment by Michel13100** [comment]
yesterday it work

Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
install.pi-hole.net	canonical name = docker-1-ny3.ftldns.com.
Name:	docker-1-ny3.ftldns.com
Address: 167.71.111.190

**Comment by Michel13100** [comment]
I used this script who i write 2 years ago
after p-ihole I install unbound a copy of the 13 root DNS


I never have this problem
I change nothing in my local network
i have a fiber access

why docker ?

**Comment by PromoFaux** [comment]
You shouldn't need to add the `sudo` calls in. What happens if you run as:

```
curl -sSL https://install.pi-hole.net | bash
```

**Comment by Michel13100** [comment]
yesterday I leave this 

today my script work again
I change nothing
 
?
thank you

**Comment by PromoFaux** [comment]
🤷‍♂️
