### ISSUE TITLE
FTL failed to start due to failed to create listening socket for port 53: Address already in use

### ISSUE THREAD

**Issue by k-matti** [pi-hole/pi-hole#3928]
### Versions
- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform
- OS and version:  Ubuntu server 20.10
- Platform:  VM

### Expected behavior

pihole-FTL start

### Actual behavior / bug

pihole-FTL does not start

### Steps to reproduce
After restart VM with Pihole get error in the web interface.
`FTL failed to start due to failed to create listening socket for port 53: Address already in use`

Tried to restart VM several times without success.
## Debug Token

https://tricorder.pi-hole.net/qogarp6bxx

**Comment by dschaper** [comment]
You have `systemd-resovled` controlling port 53.

```
*** [ DIAGNOSING ]: Ports in use
[53] is in use by systemd-re (https://docs.pi-hole.net/main/prerequisites/#ports)
```

Please see https://discourse.pi-hole.net for configuration assistance.

**Comment by k-matti** [comment]
How it is possible, I did clean install on clean VM using script from https://github.com/pi-hole/pi-hole/#one-step-automated-install

**Comment by dschaper** [comment]
Please see https://discourse.pi-hole.net for configuration assistance.
