### ISSUE TITLE
Pi-Hole Find a way to use *.adlist files instead of URLs pointing to a web content

### ISSUE THREAD

**Issue by dvdvideo1234** [pi-hole/pi-hole#3931]
### Versions

- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform

- OS and version:  Ubuntu `Linux a20-olinuxino 5.8.18-olimex #140443 SMP Thu Nov 5 14:05:55 UTC 2020 armv7l`

- Platform:  ARM Cortex AllWineer A20 Olinuxino Lime2

### Expected behavior
1. Some add lists are added via the group ad-list control panel and `pihole -g` was run.
2. The page `http://192.168.XXX.XXX/admin/groups-adlists.php` has some entries now (`204 367` domains blocked).
3. Remove some entries from the list `http://192.168.XXX.XXX/admin/groups-adlists.php`
4. Run `pihole -g` the amount of domains blocked are lower than `204 367` ( For example let's say `96  715` )

### Actual behavior / bug

1. When an entry is removed from `http://192.168.XXX.XXX/admin/groups-adlists.php` and  `pihole -g` is run the amount of blocked domains does not change. Domains in the removed list are still blocked.

2. When an entry is disabled ( via the ad-list button ) from `http://192.168.XXX.XXX/admin/groups-adlists.php` and  `pihole -g` is run the amount of blocked domains does not change. Domains in the removed list are still blocked.

### Steps to reproduce

1. Install a Pi-Hole
2. Install the following AD lists
```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://raw.githubusercontent.com/CamelCase11/UnifiedHosts/master/hosts.all
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
https://raw.githubusercontent.com/blocklistproject/Lists/master/everything.txt
https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Windows/windowstelemetryblocklist.txt
https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Android/androidblocklist.txt
https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt
https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Youtube/youtubeblocklist.txt
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads
https://raw.githubusercontent.com/justdomains/blocklists/master/lists/adguarddns-justdomains.txt
```
## Debug Token

- URL:  https://tricorder.pi-hole.net/x49iih1zsf

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I also tried:
1. Facebook is working
2. I install [this adlist](https://github.com/d43m0nhLInt3r/socialblocklists/blob/master/Facebook/facebookblocklist.txt)
3. Facebook is not working ( OK )
4. I disable the ad-list.
5. Facebook is not working ( Not OK )
6. I Delete the ad-list entirely form `http://192.168.XXX.XXX/admin/groups-adlists.php` using trash button and `pihole -g`
7. Facebook is inaccessible ( Not OK )

**Comment by dschaper** [comment]
Please run a list query for the domain you are using to check Facebook with either `pihole -q` or the admin interface.

**Comment by dvdvideo1234** [comment]
Running the query:
```
olimex@a20-olinuxino:~$ pihole -q facebook
[sudo] password for olimex:
 Match found in exact whitelist
   facebook.com
  [i] Over 100 results found for facebook
        This can be overridden using the -all option
olimex@a20-olinuxino:~$
```
Running the `dig` command gives me:
```
olimex@a20-olinuxino:~$ dig

; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10594
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       86901   IN      NS      a.root-servers.net.
.                       86901   IN      NS      b.root-servers.net.
.                       86901   IN      NS      c.root-servers.net.
.                       86901   IN      NS      d.root-servers.net.
.                       86901   IN      NS      e.root-servers.net.
.                       86901   IN      NS      f.root-servers.net.
.                       86901   IN      NS      g.root-servers.net.
.                       86901   IN      NS      h.root-servers.net.
.                       86901   IN      NS      i.root-servers.net.
.                       86901   IN      NS      j.root-servers.net.
.                       86901   IN      NS      k.root-servers.net.
.                       86901   IN      NS      l.root-servers.net.
.                       86901   IN      NS      m.root-servers.net.

;; Query time: 2 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Dec 20 10:53:20 EET 2020
;; MSG SIZE  rcvd: 239

olimex@a20-olinuxino:~$
```

**Comment by dschaper** [comment]
Sorry, I should have been more clear.

What is the exact domain you are trying to visit when you say that Facebook is not okay? Use that domain in your `pihole -q` query and as the domain you `dig`. 

Also, check the admin page for the query log to see what Pi-hole is actually doing.

**Comment by dvdvideo1234** [comment]
@dschaper 

This one: `https://www.facebook.com/` and I cannot access it now no matter of the adlist is totally deleted.

**Comment by dschaper** [comment]
Okay, so run `pihole -q www.facebook.com` and `dig www.facebook.com @127.0.0.1` on the Pi-hole device.

**Comment by dschaper** [comment]
And you don't need to ping me, I get notified of comments.

**Comment by dvdvideo1234** [comment]
Hello,

```
olimex@a20-olinuxino:~$ pihole -q www.facebook.com
[sudo] password for olimex:
 Match found in https://raw.githubusercontent.com/CamelCase11/UnifiedHosts/master/hosts.all:
   www.facebook.com12.ml
   www.facebook.com.5b.ro
   www.facebook.com-accountid77883128178.pllopplloo.com
   www.facebook.com.asqwaze.eu
   www.facebook.com-fbs.us
   www.facebook.com.hyffvsx.be
   www.facebook.com.img335.tk
   www.facebook.com-marketplace-verify.com
   www.facebook.com.motorspecials.net
   www.facebook.com-prizes-de2.pw
   www.facebook.com.qweasi.eu
   www.facebook.com.qweasx.eu
   www.facebook.comsearch.certified-toolbar.com
   www.facebook.com-securelogin-viewaccountnotification.x009.net
   www.facebook.com.tyqsazb.org.uk
   www.facebook.com.tywqap.org.uk
   www.facebook.com.tywqas.co.uk
   www.facebook.com.tywqas.me.uk
   www.facebook.com.tywqay.me.uk
   www.facebook.com-username-verify.com
 Match found in https://raw.githubusercontent.com/blocklistproject/Lists/master/everything.txt:
   www.facebook.com.suport-inbox.me
   www.facebook.com.hocalihaber.com
   www.facebook.com.3s3s.ru
   www.facebook.com-winning.website
   www.facebook.com.gohiding.com
   www.facebook.com.buy-sell-trade.club
   www.facebook.com.facebook.shayantest.shnpoc.net
   www.facebook.com-fbs.us
   www.facebook.com.help-190592920.com
   www.facebook.com-updates.net
   www.facebook.com-view-more-xntrxjqwskjj.bpk-pp.com
   www.facebook.com-online.mobi
   www.facebook.com.neelactechno.com
   www.facebook.com.popsad.com
   www.facebook.comsearch.certified-toolbar.com
   www.facebook.com-7yf9ktf451a70ca-secured-login-token.7qz6ztn.gq
   www.facebook.com.bateriasvolta.com
   www.facebook.com.trade-sell-buy.review
   www.facebook.com.thewheelspower.com
   www.facebook.com.dcplumbingcontractors.com
   wwww.facebook.com
   b-www.facebook.com
   www.facebook.com-mobi-mtvifanaepl.montconghana.com
   www.facebook.com.peopledetective.net
   www.facebook.com-akfxqsfiefud.likeid.co.il
   www.facebook.com.marketplace-trade-items.vehicles244.pro
   www.facebook.com.chubbycheeksprinting.com
   www.facebook.com
   www.facebook.com.silkybakery.com
   www.facebook.com.b6ce489abd484ae2004e2beb.usa.cc
   h_t_t_p_s.www.facebook.com.3s3s.ru
   www.facebook.com.kesteltours.com
   z-m-www.facebook.com
   www.facebook.com.eetgxv.com
   www.facebook.com.gilloo.com
   www.facebook.com.inbox-suport.me
   www.h_t_t_p_s.www.facebook.com.3s3s.ru
   www.facebook.com-securelogin-viewaccountnotification.x009.net
   www.facebook.com.geowap.info
   www.facebook.com-todayswinner.com
   www.facebook.com.join.urdusocial.com
   www.facebook.com.mgls.dev
olimex@a20-olinuxino:~$
```

```
olimex@a20-olinuxino:~$ dig www.facebook.com @127.0.0.1

; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> www.facebook.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26463
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.facebook.com.              IN      A

;; ANSWER SECTION:
www.facebook.com.       2       IN      A       0.0.0.0

;; Query time: 9 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Dec 21 10:48:40 EET 2020
;; MSG SIZE  rcvd: 50

olimex@a20-olinuxino:~$
```

**Comment by dvdvideo1234** [comment]
Well I see it still persists in `https://raw.githubusercontent.com/blocklistproject/Lists/master/everything.txt`

**Comment by dvdvideo1234** [comment]
Is is oh to gust shove this instead `https://someonewhocares.org/hosts/zero/` I assim that the URL must point to a valid file instead.
That's why I need to do this in file instead of URLs

**Comment by dvdvideo1234** [comment]
Is there any progress on this?
 
The plan is to wipe all the entries from the pi-hole database and reenter them, so I need to:
1. Reset pi-hole to its default settings ( May include the 80K entries it comes with ). 
2. Insert modified `ad-list` files that are generally text files containing URLs instead of website content
3. When an `ad-list` gets disabled or a domain included in the `ad-list` gets added to the whitelist. It must not get blocked.

**Comment by jfb-pihole** [comment]
It's not clear what you are trying to do.  You can clear all your adlists using the web GUI > Group Management > Adlists.  Each adlist has a trashcan icon next to it.  If there are just a few lists, this should be quick.

"Insert modified ad-list files that are generally text files containing URLs instead of website content"

This is the required format for all adlists used with Pi-hole.  You will add the URL of the text file, and Pi-hole will retrieve the file and add it to gravity.

**Comment by dvdvideo1234** [comment]
Hello @jfb-pihole,

For example I am trying to block the facebook ads, but not facebook itself. The adlist contains `www.facebook.com` and the ads. I want to modify the adlist, remove `www.facebook.com` and shove it back in, so only the related ads become blocked. I am afraid that the trash can does not update the `pi-hole` gravity, because when I trash an adlist and run the update gravity database button in the interface, the amount of blocked domains does not get changed. So I am searching for a way to download these adlists as files, remove some of the domains inside and insert them into the pi-hole gravity database an I can even automate this using shell scripts.

**Comment by yubiuser** [comment]
Why don't you just whitelist `www.facebook.com`?

**Comment by jfb-pihole** [comment]
You have a few options:
(1) Whitelist the domain as suggested in a previous reply.  Whitelisting effectively makes a domain "gravity proof", meaning that no blacklist or blocklist with this domain in it will be able to block the whitelisted domain.  The priority of action is as follows:

1. Exact Whitelist
2. Regex Whitelist
3. Exact Blacklist
4. Blocklist domains (AKA gravity)
5. Regex Blacklist

If a domain is found anywhere from top to bottom, FTL skips the rest of the tests.

(2) Evaluate the blocklists you are using.  Any blocklist that contains www.facebook.com is attempting to do more than block Facebook ads.  It is likely intended to completely block all of Facebook.

**Comment by dvdvideo1234** [comment]
> Why don't you just whitelist `www.facebook.com`?
Because it is currently whitelisted, but it is still inaccessible and the adlists are maybe with higher priority than whilists. Doubting that at some degree though as @jfb-pihole suggested yes, I am assuming that too. These other domains may block functionality which facebook relies on and the website is simply not opened.  Could you recommend some adblock lists that I can use after doing `pihole -r` to simply start from scratch.

**Comment by yubiuser** [comment]
Have a look here:
https://firebog.net/

Usually the ticked lists are least likely to interfere with browsing

**Comment by dvdvideo1234** [comment]
Thank you very much. I will most likely wike the whole pi-hole if I must. But will try the reset first. I will keep you in touch with the progress.

**Comment by dvdvideo1234** [comment]
@yubiuser Hmm. Invoking `pihole -r` installs it again, bit does not delete the faulty domain lists. How can I wipe all the blocked domains? Even though I am reinstalling, I still receive these ( it seems the reinstall did not wipe the file list ):
```
  [i] Target: https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
  [✓] Status: Retrieval successful
  [i] Received 9620 domains

  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/everything.txt
  [✓] Status: Retrieval successful
```

**Comment by dvdvideo1234** [comment]
I need a solution where I can be able to reset the gravity and put new domains in there. The old has to get wiped completely so the interface will show `0 domains blocked` and build the gravity block list. How can I do that ?

**Comment by yubiuser** [comment]
> bit does not delete the faulty domain lists.

No, you have to delete them manually. Remove the adlists (e.g. via web interface Group Management/Adlists) and run `pihole -g` again.

**Comment by dvdvideo1234** [comment]
Thanks! Deleted all adlists and updated the gravity with the tocked lists [here](https://v.firebog.net/hosts/lists.php?type=tick).

**Comment by dvdvideo1234** [comment]
@yubiuser

Any idea how can i insert an ad-list using the terminal ? Maybe something like `pihole -b` ?

**Comment by yubiuser** [comment]
`sudo sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://https://domain.com/blocklist.txt', 1, 'comment');"`
