### ISSUE TITLE
DHCP not working well with Hyper V

### ISSUE THREAD

**Issue by cfelicio** [pi-hole/pi-hole#3932]
### Versions
  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
Raspberry Pi 2

### Expected behavior
When using the Pi Hole as a DHCP server, I expect it to recognize MAC addresses, and assign IPs based on static rules I define.

### Actual behavior / bug
When using the Pi Hole DHCP functionality, everything seems to work well for the following scenarios:
- Physical Windows and Linux boxes
- Hyper V Linux VMs

By working well, I mean the following: When a new server is added to the network, it will contain a unique name / MAC address. Pihole will recognize these, and assign IPs based on static rules I set. It will also assign dynamic IPs if I set no rule.

When provisioning new Windows VMs (tried both with Windows 2019 server and Windows 10 VMs), I set a static MAC address on the network configuration. When I boot the VM, Pi hole does no recognize the Mac of the VM, instead it recognizes the VM as using the MAC of the host. So for example, if I have 1 host with 1 Windows VM and 1 Linux VM:

MAC    IP      Name
:0A      .10     Littleserver
:0A      .11     Littleserver
:0C      .12     Linux

The 2nd entry was expected to be "windows" with a MAC of 0B, but instead Pi hole recognizes it as 0A, and assigns the name as "Littleserver" (the host name).

If I reboot the Hyper V host, everything will start working, until I provision a new VM. Then I'd need to reboot the host again.

### Steps to reproduce

1 - Enable DHCP on Pi Hole with Default Settings
2 - Have a Hyper V host with both windows and linux VMs, each with it's own static MAC
3 - Reboot the host and boot the VMs. Confirm Pi Hole recognize each entry with a separate MAC (working as intended)
4 - Clone or create a new VM without rebooting the host. (windows based)
5 - Assign a static MAC to the new VM 
6 - Boot the VM
7 - Confirm Pi Hole assign a new IP to the same MAC / Name as the host, not the new VM

## Debug Token

https://tricorder.pi-hole.net/9g9o8vynev

**Comment by dschaper** [comment]
Since this is a configuration issue, please use https://discourse.pi-hole.net.
