### ISSUE TITLE
Typo in gravity sql

### ISSUE THREAD

**Issue by fhriley** [pi-hole/pi-hole#3933]
https://github.com/pi-hole/pi-hole/blob/0d8ece1be249fdc5993f01a45f8d0464257df819/advanced/Templates/gravity.db.sql#L76

**Comment by mwoolweaver** [comment]
@PromoFaux this didn't auto close cause i didn't make the pr correctly

**Comment by PromoFaux** [comment]
Thanks. The auto close stuff is wonky at times anyway - it may not have been something you did (or didn't!) do...
