### ISSUE TITLE
Querry Log showing different results for a search that is the same in my opinion

### ISSUE THREAD

**Issue by ChristianWitzler** [pi-hole/pi-hole#3936]
### Versions

  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
- OS and version:  PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
- Platform:  Raspberry Pi 4

### Expected behavior

The Querry Log with the same search parameters should show the same results

### Actual behavior / bug

A search using `..../queries.php?client=iPhone.fritz.box` shows different results than using the search in query log

### Steps to reproduce

1. Open pihole in two tabs
2. Go to tools-> network devices
3. Klick on a device name (opens: `..../queries.php?client=iPhone.fritz.box` )
4.  In the second tab go to querry log and enter the client name in the search
5. compare the results

### Screenshots
Refreshing this tab does not change the results. And there are more results than are found using the second way
![grafik](https://user-images.githubusercontent.com/57713653/102714065-a8577e80-42cc-11eb-957a-da241d31a5d4.png)

Newer results only appear here
![grafik](https://user-images.githubusercontent.com/57713653/102714081-bb6a4e80-42cc-11eb-99b8-184870600438.png)

### Additional context

- My network uses IPv6 and IPv4
- I am running my pihole webpage using apache2

-Noticed this problem while trying to track down why my iphone is not able to resolve an entry I made in the Local DNS records

**Comment by PromoFaux** [comment]
The clue is above the results :)

`Recent Queries (showing up to 100 queries), show all`

When clicking through from the query log, only the first 100 results are loaded initially for performance reasons. You can show all in this view by clicking "show all"

**Comment by ChristianWitzler** [comment]
Yeah, but as you can see the most recent one (from 13:48) does not appear in the other view, where the last result is from 13:34

**Comment by PromoFaux** [comment]
I guess it depends entirely on when you load the results, take for example a machine on my network:

![image](https://user-images.githubusercontent.com/1998970/102723997-14090e00-4304-11eb-9b2b-affc1ae9524a.png)

![image](https://user-images.githubusercontent.com/1998970/102724001-1a978580-4304-11eb-84a9-0c1a0d329da9.png)

**Comment by ChristianWitzler** [comment]
But even refreshing the showing queries for Iphone.... wouldnt show the newer results, at least in my case
