### ISSUE TITLE
DHCP secondary DNS and Android phones

### ISSUE THREAD

**Issue by Lenart12** [pi-hole/pi-hole#3944]
### Versions
- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform
- OS and version:  Debian 10
- Platform:  x86_84 amd64 mini pc

### Expected behavior

If PiHole DHCP would send itself as its primary and secondary dns configuration during dhcp setup, android phones would PiHole exclusevly as its DNS server.

### Actual behavior / bug

DHCP only sends itself as a primary dns and leaving secondary dns empty, so Android phones autopopulate the secondary dns with Google dns (8.8.8.8).

### Steps to reproduce

Use PiHole as a dhcp server and with an Android phone connect to the network. 

### Temporary fix

I added a line - `dhcp-option=6,[pihole ip],[pihole ip]` - to `/etc/dnsmasq.d/02-pihole-dhcp.conf` (on line 8)

**Comment by yubiuser** [comment]
PR link for reference.
https://github.com/pi-hole/pi-hole/pull/3846
