### ISSUE TITLE
Basic install logic doesn't parse Centos 8 Stream /etc/redhat-release text correctly.

### ISSUE THREAD

**Issue by jspaleta** [pi-hole/pi-hole#3947]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.4

### Platform
- OS and version:  
CentOS Stream release 8
- Platform:  
x86_64

### Expected behavior
Installer should function or give an error.

### Actual behavior / bug
Installer bails out without a message inside of the distro_check function.
It seems the regexp used to parse /etc/redhat-release to fill 
`CURRENT_CENTOS_VERSION` is not working as expected.
manually setting the variable instead of using the rexgrep allows the install to continue.

What's really weird is that fallback error mesg logic isn't firing either.  Just seems to fail siliently because it can't parse `/etc/redhat-release`. No warning message about unsupported release.  So it took me a little bit to track down where in the install script it was failing by sprinkling printfs into the script. 

### Steps to reproduce
1. Prepare a Centos Stream 8 install with static IP
1. Follow the install instructions to using basic_install.sh
1. Watch installer fail without error message after displaying the ascii artwork
### Steps to mitigate
1. comment out the `CURRENT_CENTOS_VERSION=...`   line in distro_check function
1. add `CURRENT_CENTOS_VERSION=8`

### Additional context
It maybe easier to add logic to prefer to parse /etc/os-release if it exists on the system instead of redhat-release.  If /etc/os-release exists on the system, it will have an explicit VERSION key separate from name.

**Comment by caveman99** [comment]
pihole -up also dies silently on a system switches from 'regular' centos8 to Stream8.

```
[root@dns1 ~]# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

  [ASCII Art snipped...]

  Unable to complete update, please contact Pi-hole Support
```

**Comment by drinn** [comment]
I was having the same issue for a few weeks now. The commit from bcambl fixed the problem for me and I was able to upgrade once I manually applied it to my configuration.
