### ISSUE TITLE
Gravity update does not use GRAVITYDB setting in pihole-FTL.conf

### ISSUE THREAD

**Issue by bpetrikovics** [pi-hole/pi-hole#3948]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.4

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

When gravity file location is overridden using the GRAVITYDB variable in /etc/pihole/pihole-FTL.conf (https://docs.pi-hole.net/ftldns/configfile/#file_GRAVITYDB), subsequent gravity updates (pihole -g) should work on and update the file referenced by this variable.

### Actual behavior / bug

Gravity updates will still update the file at its default location, /etc/pihole/gravity.db regardless of what is set in pihole-FTL.conf

### Steps to reproduce

1. Add a GRAVITYDB=/path/to/your/new/file setting into /etc/pihole.pihole-FTL.conf
2. Move your current gravity.db to the new location
3. Restart pihole-FTL and make sure the webinterface display of domains on blocklist shows a sensible number (the same as before). This proves that FTL reads the same configuration file and properly parses the GRAVITYDB variable
4. Run pihole -g

  [i] Creating new gravity database
  [i] Neutrino emissions detected...
  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity_temp.db
  Error: no such table: main.gravity
  [i] Number of gravity domains: 0 (0 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

5. The created gravity.db file will be empty (schema only).
6. The gravity.db file referenced by pihole-FTL.conf will be untouched and FTL/webinterface will still use that.

## Debug Token

- URL:  https://tricorder.pi-hole.net/cjxnv96voo

### Screenshots

N/A

### Additional context

In gravity.sh, although pihole-FTL.conf is parsed, no value other than BLOCKINGMODE is being used from that file. The script sets a default gravity file location and it does not override the gravityDBfile variable once reading the config file.

The fix in gravity.sh is trivial and I'm happy to send a PR for it (see https://github.com/bpetrikovics/pi-hole/commit/2a9c1bea7bfaf57d5445e2d20ca48ee0f52f038d), however it will not work on its own, because during in PR #3100, a schema template file has been added ( advanced/Templates/gravity_copy.sql) that hardcodes the gravity.db file location on line 3: "ATTACH DATABASE '/etc/pihole/gravity.db' AS OLD". That will need to be amended to also honor the configuration variable before gravity.sh can be fixed.

**Comment by drukennerd** [comment]
Is the solution still in progress?

**Comment by DL6ER** [comment]
I had been forgotten, I'd say. @PromoFaux assigned me but I haven't been notified about this. I'll check if I can find the time to do this soon, it should be included in the next release then.

**Comment by DL6ER** [comment]
@bpetrikovics @drukennerd Could you please test whether this bug fix works for you?

Run
```
pihole checkout core fix/GRAVITDB_in_pihole-g
```
to source the bug fix. It should work immediately afterwards.

**Comment by drukennerd** [comment]
It works 😃 .
My system Odroid(ARM-based) with Ubuntu 20.04 LTS.
Good work 👍

**Comment by bpetrikovics** [comment]
Yes, it appears to work for me too, thank you.

**Comment by yubiuser** [comment]
Was released in:
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-8-web-v5-5-and-core-v5-3-released/46237
