### ISSUE TITLE
[Insufficient free space] - incorrect interpretation of df -lk output. Won't install on FS with less than 4.77GB available.

### ISSUE THREAD

**Issue by graycrow** [pi-hole/pi-hole#395]
I have a Raspberry Pi 2  with latest Raspbian Jessie Lite version installed on 8GB card. The card has ~3.5GB available:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.2G  3.4G  3.5G  50% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M  6.3M  457M   2% /run
tmpfs           5.0M  8.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1   60M   20M   41M  34% /boot
```
However, pi-hole install script exits with following error message:
```
3632740 is less than 5000000
Insufficient free space, exiting...
```
I checked installer script and found that it's using `df -lk` command to check for free space.
```
$ df -lk
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7503004 3537608   3632740  50% /
devtmpfs          469688       0    469688   0% /dev
tmpfs             474008       0    474008   0% /dev/shm
tmpfs             474008    6372    467636   2% /run
tmpfs               5120       8      5112   1% /run/lock
tmpfs             474008       0    474008   0% /sys/fs/cgroup
/dev/mmcblk0p1     61384   20376     41008  34% /boot
```
and a actual command used by script gives this output:
```
$ df -lk / 2>&1 | awk '{print $4}' | head -2 | tail -1
3632740
```
Which means that I have 3632740 1-K blocks on root FS, which equals to  ~3548MB or 3.46GB - this is way more than 50MB required. 

Next, the installer script have this inside:
```
# 50MB is the minimum space needed (45MB install (includes web admin bootstrap/jquery libraries etc) + 5MB one day of logs.)
	requiredFreeBytes=5000000
```
If requiredFreeBytes indeed measured in bytes, than 5000000 bytes is just ~4.77MB, not 50.
If requiredFreeBytes measured in 1K blocks, same as output of df -lk to which it's compares, than 5000000KB is ~4.77GB and not 50MB, again.

**Comment by graycrow** [comment]
If it really needs to be 50MB, then requiredFreeBytes should be **51200**, and probably it's better to rename it to requiredFree**K**Bytes, to avoid confusion.

**Comment by graycrow** [comment]
Oh, that already has been done, closing this issue.

**Comment by PromoFaux** [comment]
Yeah, I had a bit of a blonde moment earlier on, didn't realise it was in 1k blocks :)

**Comment by PromoFaux** [comment]
>rename it to requiredFreeKBytes, to avoid confusion.

this though, good idea.
