### ISSUE TITLE
Domains not being added to blacklist from Query log

### ISSUE THREAD

**Issue by CallumBaston** [pi-hole/pi-hole#3952]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.4

### Platform

- OS and version:  Raspberry Pi OS, Latest

- Platform:  Raspberry Pi 4 4GB

### Expected behavior

_A clear and concise description of what you expected to happen._
When I'm in the Query log in the web interface and I click on blacklist a domain it should be added to the blacklist.  
### Actual behavior / bug

_A clear and concise description of what the bug is._
The domain is not being added to the blacklist
### Steps to reproduce

1. Go to Query log
2. Click the blacklist option next to the listing of a domain
3. Navigate over to blacklist
4.The domain is not there.

## Debug Token

- URL:  https://tricorder.pi-hole.net/ofkcyhvtqo

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Can you provide some examples? Possibly screenshots of where you are going and what you are seeing.

The debug log you provided shows a number of domains added via query log.

```plain
*** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
   id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment                                           
   ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   1      1          1  0,2           facebook.com                                                                                          2020-12-18 20:29:38  2020-12-23 13:17:48  Added from Query Log                              
<SNIP>
2020-12-27 19:14:08  2020-12-27 19:14:44  Added from Query Log                              
   16     1          1  0             media.trafficjunky.com                                                                                2020-12-28 10:02:26  2020-12-28 10:02:26  Added from Query Log                              
   17     1          1  0             gist.github.com                                                                                       2020-12-28 10:04:25  2020-12-28 10:04:25  Added from Query Log                              
   18     1          1  0             safebrowsing.googleapis.com                                                                           2020-12-28 10:17:38  2020-12-28 10:17:38  Added from Query Log  
````

**Comment by CallumBaston** [comment]
I added those before I updated to the latest version. All domains are examples and could you please not post anything from my debug log as I'd rather it not be public.

**Comment by dschaper** [comment]
Deleted. Please use https://discourse.pi-hole.net for support.
