### ISSUE TITLE
Pihole UI and Commandline produce different wildcard results.

### ISSUE THREAD

**Issue by cool1two** [pi-hole/pi-hole#3956]
Blacklist management > Add a new blacklisted domain > Add domain as wildcard
Input "youtube.com" > Output "(\.|^)youtube\.com$"

/usr/local/bin/pihole --wild youtube.com
Input "youtube.com" > Output "(^|\.)youtube\.com$"

Of the two blacklist wildcards, only the UI generated wildcard is effectively blocked when testing via Firefox.

**Comment by jfb-pihole** [comment]
When I test this in latest version of Pi-hole:

(1) Adding youtube.com from the web GUI as a blacklist wildcard results in `(\.|^)youtube\.com$`

```
dig +short youtube.com
0.0.0.0

```
(2) Adding youtube.com from the command line with pihole --wild youtube.com results in `(^|\.)youtube\.com$`

```
dig +short youtube.com
0.0.0.0

```

**Comment by dschaper** [comment]
"(.|^)youtube.com$" is functionally equivalent to "(^|.)youtube.com$".

The `|` means `or`, order doesn't matter.

Closing this since the template was ignored and this really isn't a bug.
