### ISSUE TITLE
Databases do not belong in /etc/

### ISSUE THREAD

**Issue by autostatic** [pi-hole/pi-hole#3961]
Only static data should go into `/etc/`, see https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s07.html#purpose6
Variable data files, like databases, should go into `/var/`, see https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05.html#purpose31
So please consider moving `gravity.db` and `pihole-FTL.db` to something like `/var/local/pihole/` or even `/var/opt/pihole/`. But placing pihole related stuff in `/opt/` is debatable too, in my opinion it should go into `/srv/pihole/`.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
