### ISSUE TITLE
How to set DNS settings for Chromecast

### ISSUE THREAD

**Issue by SudoHenk** [pi-hole/pi-hole#397]
How can you enforce the usage of pi-hole on your chromecast? To my knowledge you cannot set those settings, and you also need to block the Google DNS servers before they will start using the local.

Also, under what license is this project available? Could not find this anywhere.

**Comment by PromoFaux** [comment]
Check this [response] (https://www.reddit.com/r/pihole/comments/4be0jk/slug/d1aa0iy)  to a similar request on reddit. 

You can do it,  but you need to block Google dns like you say,  and make sure you are using different ones for your pihole's upstream

**Comment by PromoFaux** [comment]
Re:licence , we use [Gnu v2](https://github.com/pi-hole/pi-hole/blob/master/LICENSE)  which is in the file `Licence' in the root directory....

**Comment by dschaper** [comment]
Yep, its licensed as GPL 2+

Dan Schaper via GS3
Ganymeade Systems

**Comment by PromoFaux** [comment]
Hi @SudoHenk did that answer your question?

**Comment by SudoHenk** [comment]
Well the thing is that I can't block DNS requests in my router. My ISP provides a shitty router that has like 0 functionality.

**Comment by PromoFaux** [comment]
Ah,  yeah,  I hate when they do that.  BT provided me with an OK router,  but I couldn't do much with the settings,  so I went out and bought my own :)
