### ISSUE TITLE
Client in "Groups" under Group Management not getting protected

### ISSUE THREAD

**Issue by angelperezleon** [pi-hole/pi-hole#3970]
### Versions

  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform

- OS and version:  Linux rpi4-prox 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l

- Platform:  Raspberry Pi

### Expected behavior

_Pi-hole banning ads_

### Actual behavior / bug

_Clients found in pi-hole and are part of a new 'Group' ads won't get blocked._

### Steps to reproduce

1. Go to 'Group Management'
2. Click on 'Groups'
3. In Add a new group, add Name: 'NewGroupName'
4. Under  'Group Management' again, click on 'Clients'
5. Change the 'Group assignment' for a client to new 'Group name' by ticking the group and untick 'Default' then click 'Apply'

## Debug Token

- URL:  https://tricorder.pi-hole.net/7ljrxi8b7a

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
This is exactly the behavior one would expect to see, no issue here. If you don't assign adlists/blacklist to that new group, nothing will be be blocked for the respective clients.

https://docs.pi-hole.net/database/gravity/example/
