### ISSUE TITLE
pi-hole is blocking all DNS entries that points to its own IP

### ISSUE THREAD

**Issue by farktronix** [pi-hole/pi-hole#3972]
### Versions

-  Pi-hole version is v5.2.2 (Latest: v5.2.2)
-  AdminLTE version is v5.2.2 (Latest: v5.2.2)
-  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform

- OS and version: Ubuntu 20.04

- Platform:  Docker (pihole/pihole:v5.2.2_amd64)

### Expected behavior

I have a local recursive DNS server for my home network that serves hostnames under the `home.rkas.net` domain. I added a DNS entry for my pihole server at `pihole.home.rkas.net` and when I enter that host name in my browser I would expect to go to the pihole admin web interface.

### Actual behavior / bug

When I try to access the web interface via my custom domain `pihole.home.rkas.net` I get an error page that the domain is blocked. 

<img width="777" alt="Screen Shot 2021-01-06 at 10 01 17" src="https://user-images.githubusercontent.com/4943/103804141-7cdfce00-5006-11eb-99ef-287f757dff58.png">

The problem isn't with the DNS entry- I verified that `pihole.home.rkas.net` points to `10.17.0.3`, and if I go directly to `10.17.0.3` in my browser I can access the web interface

```
dig pihole.home.rkas.net    
...
;; ANSWER SECTION:
pihole.home.rkas.net.	2	IN	A	10.17.0.3
```

Here's what I see in the pihole.log at that time:
```
Jan  6 10:05:26 dnsmasq[59683]: query[A] pihole.home.rkas.net from 10.17.0.50
Jan  6 10:05:26 dnsmasq[59683]: /etc/pihole/custom.list pihole.home.rkas.net is 10.17.0.3
Jan  6 10:05:26 dnsmasq[59683]: query[A] pihole.home.rkas.net from 10.17.0.50
Jan  6 10:05:26 dnsmasq[59683]: /etc/pihole/custom.list pihole.home.rkas.net is 10.17.0.3
```

Adding the domain to the pihole whitelist (both as an explicit exact name or as a wildcard for all of `home.rkas.net`) still results in the error. I've tried adding a different domain name that points at my pihole server (without `pihole` in the name) and I get the same error page.

I also tried adding `pihole.home.rkas.net` to the local DNS records in my pihole but I still get the blocked domain error.

### Steps to reproduce

1. Set up a recursive unbound DNS server on a local network
2. Set up an authoritative NSD server for `home.rkas.net`
3. Add an entry to NSD for `pihole.home.rkas.net` pointing at the pi-hole server's IP address
3. Point the unbound server at the NSD server
4. Set the unbound server from step 1 as the only upstream DNS server for pihole
5. Try to access `pihole.home.rkas.net` in a web browser
 - pi-hole will return an error that the domain is blocked

## Debug Token

- URL:  https://tricorder.pi-hole.net/bipm641lie

**Comment by ndrone** [comment]
Try with /admin at the end or your URL

**Comment by farktronix** [comment]
Thanks @ndrone- that URL works! 

Is there a reason the DNS entry causes a blacklist error page, but typing just the IP address takes me to a "Did you mean to go to the admin panel?" redirect page? Is this the intended behavior, or a bug?

**Comment by dschaper** [comment]
Intended behavior. 

Only `http://pi.hole` will automatically redirect to the admin page. If you use anything other than `pi.hole` then you'll need to go directly to `http://<custom>/admin/`.

This is a security feature to prevent someone external to your network being able to access the admin page.

**Comment by dyercode** [comment]
> 
> 
> Intended behavior.
> 
> Only `http://pi.hole` will automatically redirect to the admin page. If you use anything other than `pi.hole` then you'll need to go directly to `http://<custom>/admin/`.
> 
> This is a security feature to prevent someone external to your network being able to access the admin page.

Is this some kind of joke? It reads like a joke. And the `http` emphasizes the ridiculousness.

**Comment by farktronix** [comment]
Thanks, @dschaper!
