### ISSUE TITLE
Client name bug

### ISSUE THREAD

**Issue by Thomas499** [pi-hole/pi-hole#3976]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.4

### Platform

- OS and version:  Linux 5.4.79-vy

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

I expect the name of client to be consistent 

### Actual behavior / bug

_A clear and concise description of what the bug is._
![image](https://user-images.githubusercontent.com/38442058/104071107-7011d480-51d6-11eb-9945-2f83ec164373.png)
Shows what I see in Query Log. Notice Some say FireThomas, Others give IP address, and my I phone is listed as "Amazon" which is completely random. 

![image](https://user-images.githubusercontent.com/38442058/104071209-b0715280-51d6-11eb-9a29-2b5de511d1c9.png)
Shows the same time for the above example what I see in long term data Query Log. Notice now they all show the proper IP address in a consistency rather than some Names, some ip's, and some completely random names. 

![image](https://user-images.githubusercontent.com/38442058/104071682-a734b580-51d7-11eb-805e-523abcf95e9e.png)
Shows what I see on the Dashboard. Notice, some list correct names, some list ip's, and 2 list random names. I did have to flush logs to get PhoneThomas to show up as top device here. 

![image](https://user-images.githubusercontent.com/38442058/104071847-fda1f400-51d7-11eb-90ff-91c166e9d241.png)
Shows where DHCP is assigned to device for CompThomas, PhoneThomas, 

![image](https://user-images.githubusercontent.com/38442058/104071988-393cbe00-51d8-11eb-8b23-5cba8a14590f.png)
shows group management for PhoneThomas Notice my I Phone is listed as the random "amazon"  

![image](https://user-images.githubusercontent.com/38442058/104072065-67ba9900-51d8-11eb-818a-f4b4883c4a61.png)
shows if I type in "Thomas" in group management only my PS4 shows up, not CompThomas or PhoneThomas.

I deleted the PhoneThomas and CompThomas from the DHCP and readded them thinking maybe that would solve the problem. It did not solve the problem. 

I would prefer all devices be listed as their assigned names listed in the DHCP section, IN ALL SECTIONS. Second choice would be listed as IP address. 

I would not like some devices to be listed as IP addresses, others listed as names from DHCP section, and some assigned completely random "amazon" names. 

### Steps to reproduce

Everytime I flush logs OR delete DHCP and reenter the names, the client names are completely random. There seems to be no pattern to rather if it list IP, Name, or some random name. What is not random is it always gives a random "amazon" name to PhoneThomas. Also long term data query log is the only file where there is consistency in regards to it shows IP for each device. 

I have had pihole for a while and have done several updates over time. Maybe the transaction of updating from previous pi hole versions caused an issue? Maybe flushing logs over time caused an issue? Maybe others are having this issue too? 

## Debug Token

- URL:  https://tricorder.pi-hole.net/d5d34o0l97

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Thomas499** [comment]
Now it shows two devices that have the same name in top clients. 
![image](https://user-images.githubusercontent.com/38442058/104104942-08f92c00-5279-11eb-829e-e80d69c2ae6a.png)
I am certain there is only one device that is labeled FireThomas

**Comment by yubiuser** [comment]
Hover over/click on both device names and see if it is the same IP address.

**Comment by Thomas499** [comment]
They are not the same ip address's. One is 192.168.1.189 the other is 192.168.1.199
![image](https://user-images.githubusercontent.com/38442058/104106179-dd2e7400-5281-11eb-8e73-b467f5200655.png)
![image](https://user-images.githubusercontent.com/38442058/104106185-e91a3600-5281-11eb-898d-4d127012ed3e.png)


As you can see here the 189 one should be FireGus instead of FireThomas
![image](https://user-images.githubusercontent.com/38442058/104106212-2aaae100-5282-11eb-9c83-c93fc7cc88c3.png)

**Comment by dschaper** [comment]
On the Pi-hole device, check

```
arp -a
```

And see what is being displayed for those two.

**Comment by yubiuser** [comment]
Have a look at Tools/Network. Are the assignments correct? If not try Settings/Flush Network table.

**Comment by Thomas499** [comment]
`arp -a`
![image](https://user-images.githubusercontent.com/38442058/104107512-a741bd80-528a-11eb-8b16-861b57abc41b.png)

`Have a look at Tools/Network. Are the assignments correct?`
![image](https://user-images.githubusercontent.com/38442058/104107591-64ccb080-528b-11eb-8515-f54cbe335628.png)

No. It appears to list the same that was listed Client Group Management. Some even have two names assigned.

But the file 04-pihole-static-dhcp found in /etc/dnsmasq.d list the correct assignments. 

`If not try Settings/Flush Network table.`
If I do that will the clients listed in 04-pihole-static-dhcp still remain or will i have to re-identify all 50 something devices on the network to enter their names again?  I'd rather not start from scratch if possible it will take a few hours to enter all that information again.

**Comment by yubiuser** [comment]
It will retain the information in `04-pihole-static-dhcp` and only delete the network table in `pihole-FTL.db`

https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeARPTable.sh

> take a few hours to enter all that information again.

In any case, it might be a good idea to make a teleporter backup

**Comment by Thomas499** [comment]
I flushed the network table. Seems to be the same though. 
![image](https://user-images.githubusercontent.com/38442058/104107888-110f9680-528e-11eb-9bc1-d5d89f854472.png)

**Comment by DL6ER** [comment]
Flushing won't make the database shrink. The space is reserved and later reused.

Try also a
```
pihole restartdns
```
after flushing.

**Comment by Thomas499** [comment]
I restarted the dns as recommended after flushing. Now I have no client names but at least it is consistent in showing only IP instead of a mix of ip, correct names, and random names. 

![image](https://user-images.githubusercontent.com/38442058/104108449-bd537c00-5292-11eb-9a48-6e13d864272e.png)
![image](https://user-images.githubusercontent.com/38442058/104108455-cb090180-5292-11eb-9658-4ed17ec719a5.png)

**Comment by Thomas499** [comment]
Out of curiosity, how would I make the client names reappear?

**Comment by Thomas499** [comment]
**So there seems to be another bug worth mentioning**. After user goes to Settings/Flush Network table then does pihole restartdns the client names never repopulate the network overview table found in tools/network. Even though the names are still properly listed in settings/dhcp table. Even if you assign new IP addresses or new devices to the settings/dhcp table even the new ones aren't stored in tools/network table or the dashbord or the query log. 

![image](https://user-images.githubusercontent.com/38442058/104122731-d270ef00-5314-11eb-8ed0-6007c7c5ca28.png)
![image](https://user-images.githubusercontent.com/38442058/104122743-e3216500-5314-11eb-835f-29df4874ca04.png)

**Comment by DL6ER** [comment]
I don't think (yet) there is a bug here. Note that only *active* DHCP leases contribute to the DNS wisdom, mere *reservations* won't (thin is following some FTC Internet standard who's number I don't recall right now). How long is your DHCP lease period? Can you force at least one of these devices to re-request their DHCP lease (Dis-/reconnect Ethernet cable, dis-/enable WiFi or reboot the device)?

Note that even then the update of the names may take up to one hour (we do not check for changed/new host names all that often to avoid PTR query spam in your network). Run `pihole restartdns` to enforce a re-resolving of the host names.

If this still doesn't work, it'd be interesting if
```
dig -x 192.168.1.159 @127.0.0.1
```
on your Pi-hole shows you the host names of this client.

Depending on what you find, we can see what to check next.

**Comment by DL6ER** [comment]
Another question: Do I recall correctly that your Pi-hole is the authoritative (=single) DHCP server on your network? I'm asking because I've just seen that your Pi-hole sits at `192.168.1.123` which seems somewhere in between. How does your DHCO configuration look like?

**Comment by Thomas499** [comment]
`I don't think (yet) there is a bug here. `
The first issue of client names being random and some listed as ip addresses, some listed as correct names, and some listed as completely random names is a bug I believe. I just wanting to clarify if that is your interpretation as well? 

The second issue of tools/network not repopulating with names after being flushed and restarted is the second bug which you are not sure of is a bug (Yet). 


`Can you force at least one of these devices to re-request their DHCP lease (Dis-/reconnect Ethernet cable, dis-/enable WiFi or reboot the device)?`
Done. I forced 192.168.1.198 (PhoneThomas) to forget the wifi network, then shut the devices down, rebooted the devices, then went to settings/dhcp and hit the trash can to make pi hole forget the lease, then reconnected the devices to the internet. You can see below that 192.168.1.198 is an active lease now after reconnecting
![image](https://user-images.githubusercontent.com/38442058/104127453-1d4c3000-5330-11eb-826f-b9c153651f89.png)

`Run pihole restartdns to enforce a re-resolving of the host names.`
![image](https://user-images.githubusercontent.com/38442058/104127295-5afc8900-532f-11eb-83de-bf336567910f.png)


![image](https://user-images.githubusercontent.com/38442058/104127847-71581400-5332-11eb-8375-4412954e6e17.png)
As you can see 192.168.1.198 (PhoneThomas) which I just restarted after i ran pihole restartdns still isn't showing client name  in tools/network even though it is an active lease. 


`Do I recall correctly that your Pi-hole is the authoritative (=single) DHCP server on your network? `

Correct. 

`I'm asking because I've just seen that your Pi-hole sits at 192.168.1.123 which seems somewhere in between.`
I prefer to simply things. 123 is much easier to type and remember. 

`How does your DHCP configuration look like?`
![image](https://user-images.githubusercontent.com/38442058/104127561-bda25480-5330-11eb-8b07-d0235ad7c41d.png)
I use 192.168.1.201 to 192.168.1.251 for new devices so I can quickly identify new devices from the ones which I have already identified and assigned manual ip addresses to. I have a numbering system that accounts for each person and each device. I.e. Thomas devices are 190-199 Firesticks always end with 9. So FireThomas would be 199. Until I identify the device I prefer for it to be assigned a number that I wouldn't assign manually anyway.

**Comment by DL6ER** [comment]
Okay, thanks. My main point about not being confident that this isn't a general bug is that I'm running (about) the same configuration at home and I know many others who do the same. I just tried flushing my network table and it quickly repopulated. For instance, the hostname of `127.0.0.1` (`localhost`) was immediately re-added. A few minutes later, all hostnames re-appeared in my table as FTL went though and updated them all. So I'd say we first have to rule out that it may be some edge case due to your particular configuration.

Could you run the `dig` command I asked you to run above? A debug log (generated using `pihole -d` and uploaded to our server) would be helpful as well.

**Comment by Thomas499** [comment]
Lets try to make that issue repeatable. Open up a putty connection to the raspberry pi. You don't have to do anything like pihole -g but make sure there is a connection. Then using the browser interface go to settings and flush network table. Then go to tools/network and before the list is done repopulating go back to settings and click flush network table again. Then click Restart DNS resolver immediately. Then using putty type pihole restartdns. Then log back into the web interface and see if the client names still repopulated. That is all the steps that I can think that I took. I do remember the network list repopulating some after the first time that I flushed the network table. I do remember 127.0.0.1 (local host) repopulating immediately, then a few minutes later some others did too but the ones that didn't repopulate were the ones that were causing trouble previously (ones that had random names in query log and two names listed in tools/network, and the ones that only had ip addresses listed previously). Those are the ones that never did repopulate. Then I flushed the network table again and ran restart dns as instructed that is when none repopulated..... Except 127.0.0.1 (local host). That was the only one that repopulated after that. 

![image](https://user-images.githubusercontent.com/38442058/104134659-18e83d00-5359-11eb-99e8-71c747ace687.png)

I also have 60 something devices manually listed in dchp table and at any one time at least 15 to 30 devices are connected to the internet so i'm sure a lot of dns request were received while  the network table was being flushed and dns resolver was rebooting. That could be something you are not recreating in your test.

`Could you run dig -x 192.168.1.159 @127.0.0.1 command`

![image](https://user-images.githubusercontent.com/38442058/104134820-facf0c80-5359-11eb-8e80-7c427984b9d2.png)

` A debug log (generated using pihole -d and uploaded to our server) would be helpful as well.`


When I listed the first issue (ip listed on some, correct names listed on some, and completely random names listed for others) I ran debug and generated the following log before I flushed the network table. 

https://docs.pi-hole.net/core/pihole-command/#debugger
https://tricorder.pi-hole.net/d5d34o0l97

After the second issue of not repopulating network table appeared I ran debug again (just now) listed below
https://tricorder.pi-hole.net/nqfgk7fhwh

**Comment by yubiuser** [comment]
> Could you run dig -x 192.168.1.159 @127.0.0.1 command

The answer of this command is `0.0.0.0` means pihole blocked it.

Remove the following from your blacklist and repeat the command
`80     1          1  0,4,5,6,7,8   127.0.0.1                                                                                             2020-05-12 05:18:14  2021-01-07 05:23:52  Migrated from /etc/pihole/blacklist.txt           `

**Comment by Thomas499** [comment]
I unblocked the domains as requested. I blocked them in the first place because lots of devices were calling on them and I didn't know if that was apps looking at which devices were on the same network. 

![image](https://user-images.githubusercontent.com/38442058/104168795-9ac57e00-53cc-11eb-970e-3ed981612615.png)

**Comment by Thomas499** [comment]
Ok after unblocking those addresses, and flushing network table and restarting DNS resolver everything seems to be working as expected

![image](https://user-images.githubusercontent.com/38442058/104180452-1fb79400-53db-11eb-806e-c28657ddf77b.png)

Should I close the issue out?

**Comment by yubiuser** [comment]
`*.addr.arpa` are valid reverse DNS requests, trying to obtain the hostname for a given IP. No need to block them.
https://www.wikiwand.com/en/Reverse_DNS_lookup

If it's working now, you can close the issue.
