### ISSUE TITLE
endles loop for test_dpkg_lock() although has counter..

### ISSUE THREAD

**Issue by MatthewCKelly** [pi-hole/pi-hole#3977]
### Versions

- Pi-hole:   v5.2.2.
- AdminLTE:  v5.2.2.
- FTL:  v5.3.4.

### Platform

- OS and version:  Linux XXX 4.4.190.x86_64.1 #1 SMP Thu Oct 22 04:41:26 UTC 2020 x86_64 GNU/Linux

- Platform:  Netgear ReadyNAS 314

### Expected behavior

for some reason my system /var/lib/dpkg/lock is always in use.. 
In the function  test_dpkg_lock() there looks like there is an '`# An iterator used for counting loop iterations`'  However, there is no additional code to break out of that function when that value reaches a given value..

### Actual behavior / bug
endless loop, will continue until user breaks execution..

### Steps to reproduce

```
wget -O basic-install.sh https://install.pi-hole.net
PIHOLE_SKIP_OS_CHECK=true   bash basic-install.sh
update
```

![image](https://user-images.githubusercontent.com/16784124/104111357-c0f40b00-5345-11eb-872a-b1a02f2dce26.png)

Inserted line after `i` was incremented :             `echo "in function test_dpkg_lock() i=$i"`

## Debug Token

- URL:  https://tricorder.pi-hole.net/culvx9ablr

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

any change to this function will need to be updated back at where it was called from..

**Comment by dschaper** [comment]
Looks like it was there originally and was changed before merge. This was back in version 3, so approx 4 years or so ago?

@DL6ER Check https://github.com/pi-hole/pi-hole/pull/1286/commits/a535ca9db4504dc75c57097fec57b123d6b2ce90 and see if that makes sense to you.

As for your system, I don't think you'll be able to install if the apt package lock is always there. Even if you skip the lock check you'll fail when `apt install` fails for the lock file existing.

**Comment by MatthewCKelly** [comment]
@dschaper strangely bypassing the lock check allows all the install to complete, and I have it is working well on my system..

**Comment by DL6ER** [comment]
@dschaper Doesn't seem to make sense. As the `i` counter is still there, I can only assume the `while` was removed accidentally.

**Comment by sjt5** [comment]
Lovely unintentional infinite while loop.
Could add a simple check and bail to prevent infinite loop:
```
if [ $i > 1000 ]; then echo "*** Error: Could not verify package manager finished and released lock. Attempt to install packages manually and retry."; exit 1; fi
```
But that begs what was the intent of the check in the first place (what issue was the while loop trying to prevent)?
Assume to wait-some-time for packages to complete installation or wait for some other process to complete.
Do package managers really return/exit before completed (unlocked) or not retry a time or two if locked before failing?
(I've never seen either.)

**Comment by dschaper** [comment]
> Do package managers really return/exit before completed (unlocked) or not retry a time or two if locked before failing?

Yes.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.10
