### ISSUE TITLE
adlists.list in Version 5.2.2 not used any longer 

### ISSUE THREAD

**Issue by f41ardu** [pi-hole/pi-hole#3978]
### Versions

  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform

- OS and version:
- Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.118-v7+ (dom@buildbot) (gcc version 4.9.3 (cro
sstool-NG crosstool-ng-1.22.0-88-g8460611)) #1311 SMP Mon Apr 27 14:21:24 BST 20
20
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
  

- Platform:  Raspberry PI

### Expected behavior

Add additional blocklists using /etc/pihole/adlists.list dind'nt work. Adding large number of lists using the web interface is cumbersome and time consuming. 

### Actual behavior / bug

Lists added to /etc/adlists.list are not integrated

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by DL6ER** [comment]
> Adding large number of lists using the web interface is cumbersome and time consuming.

Just wanting to ask why this is cumbersome. You should be able to mass-add by copy-pasting space-separated adlists into the field. Copy-pasting from a multi-line file into the field should work as well.
