### ISSUE TITLE
Blocking Google Analytics Site

### ISSUE THREAD

**Issue by le0nard0** [pi-hole/pi-hole#398]
##### Expected Behaviour:
I should be able to log into Google Analytics.

##### Actual Behaviour:
When I go to https://analytics.google.com and login my request gets refused. https://www.dropbox.com/s/7sbv74iusbg2uiu/Screenshot%202016-03-21%2022.49.58.png?dl=0

##### Steps to reproduce this issue:
Not sure. Just noticed the issue. I will try sudo apt-get update/upgrade on my pi.

**Comment by dschaper** [comment]
May have to whitelist that site. Pretty sure its on a block list.

Dan Schaper via GS3
Ganymeade Systems

**Comment by manuelgu** [comment]
I can confirm that whitelisting `analytics.google.com` solves the issue.

**Comment by PromoFaux** [comment]
Heh, I wonder how your stats on Google Analytics are affected by people having Google Analytics blocked.... 

@le0nard0 is this issue resolved?

**Comment by DonLexos** [comment]
Yes as @manuelgu mentioned you need to whitelist `analytics.google.com` by running `whitelist.sh analytics.google.com`

**Comment by manuelgu** [comment]
@PromoFaux Don't think it will unless you whitelist `google-analytics.com`.
`http://google-analytics.com/analytics.js` is where the tracking code leads to on websites.
