### ISSUE TITLE
/api.php?recentBlocked Not Working

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#3980]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.4

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi

### Expected behavior
/api.php?recentBlocked should return last blocked domain
_A clear and concise description of what you expected to happen._

### Actual behavior / bug
/api.php?recentBlocked returns []
_A clear and concise description of what the bug is._

### Steps to reproduce
http://ip/admin/api.php?recentBlocked

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by C4Wiz** [comment]
has anyone looked into this yet?

**Comment by dschaper** [comment]
https://github.com/pi-hole/AdminLTE/pull/1650

**Comment by dschaper** [comment]
This is intended behavior. You'll need to be logged in or pass the auth token to access that information now.

**Comment by C4Wiz** [comment]
thank you, thats my bad for not reading the pull requests.

**Comment by DL6ER** [comment]
It shouldn't have been exposed without password before so this was fixing incorrect behavior now. Assuming someone continuously scanning the API endpoint. They could reconstruct your entire list of blocked domains.
