### ISSUE TITLE
Regex blocking without any lists?

### ISSUE THREAD

**Issue by DuschdrBabbe** [pi-hole/pi-hole#3985]
Hello, I noticed that my Pi-hole blocks requests within my network. client to client. these appear in the logs (see picture 1) i have deleted all lists but they are still blocked. update gravicy shows me 0 list and 0 regex.

where can I still see where this regex is located?
I also use pihole as a dhcp server.
Greetings from Germany

Pascal

![84E5711D-CC77-493D-BE87-2F12FE3C300E](https://user-images.githubusercontent.com/34094049/104358821-424ac980-550f-11eb-9647-cd329553b539.jpeg)

**Comment by yubiuser** [comment]
Wenn du auf den "Blocked (regex blacklist)" klickst, müsste Pi-hole dir eigentlich zeigen welcher Regex dafür zuständig ist.

Wenn du gar keinen Regex konfiguriert hast, bist du von folgendem Bug betroffen
https://github.com/pi-hole/FTL/pull/1014

Der ist schon gefixt und wird mit der nächsten Pihole Version veröffentlicht.

**Comment by DuschdrBabbe** [comment]
Danke!

Nein habe absolut keine Listen... hab extra alles gelöscht.. ich such mir echt schon nen Wolf :-)

dann warte ich mal auf mein Update und das ich bald wieder mit der Telekom schnell von Github laden kann...

Grüßle

Pascal

**Comment by medeniki** [comment]
I dont need

**Comment by yubiuser** [comment]
Bitte beachte, dass es sich dabei nur um einen Bug handelt, der ein reines Darstellungsproblem betrifft.

Deine pihole wird weiterhin `wohnzimmer.local` nicht Auflösen können (existiert nicht `NXDOMAIN`)

**Comment by DuschdrBabbe** [comment]
Welchen DNS gebe ich dem pihole System? Sich selber?

**Comment by yubiuser** [comment]
Pi-hole FTL v5.4 with the relevant fix has been released.
