### ISSUE TITLE
pihole -up > do update FTL from 5.3.4 to 5.3.4

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#3986]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  .5.3.4

### Platform

- OS and version:  Raspbian OS 10

- Platform:  Raspberry Pi 3 MB +

### Expected behavior
pihole -up 
shows everything up-to-date

### Actual behavior / bug

pihole -up update FTL to 5.3.4 again and again...

### Steps to reproduce

run pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/u58myih96b

**Comment by dschaper** [comment]
Thanks, looks like there are some changes on the Github API that we need to account for.

**Comment by pheiduck** [comment]
fixed
