### ISSUE TITLE
Spotify Premium being blocked by v2.5.3

### ISSUE THREAD

**Issue by NHgranite** [pi-hole/pi-hole#399]

**Comment by Palmer11** [comment]
Tail the log file and add the routes to your whitelist.

**Comment by PromoFaux** [comment]
Hi there,

What platform are you running spotify on?

**Comment by nate-ubiquisoft** [comment]
I have spotify premium and I can stream it fine from all my devices (PC, OSX, iOS, Android).

**Comment by PromoFaux** [comment]
@nate-ubiquisoft , did you have to add anything to the whitelist? 

The guy that had the issue before (#364 by @zimmertr) was running it on Arch-linux, I'm wondering if it's also the case with @NHgranite

**Comment by zimmertr** [comment]
Another person is having the issue and commented on my Reddit thread as well. I asked him in the comments and via a private message to add his information to the bug report but it doesn't look like he has.

https://www.reddit.com/r/pihole/comments/48yvya/enabling_pihole_puts_spotify_in_offline_mode/d17v8wn

**Comment by zimmertr** [comment]
There is also an additional person who commented in #364 saying they we're having an issue too. That makes at least 4 of us now.

**Comment by nate-ubiquisoft** [comment]
@PromoFaux I haven't added anything to my whitelist as of current because I am testing some local changes but I have not run into any issues with Spotify premium. I would put money on it being an arch-linux issue however because it has a newer version of dnsmasq (2.75-1) wheras raspbian dnsmasq (2.72).

**Comment by nate-ubiquisoft** [comment]
Notably I see [here](http://www.thekelleys.org.uk/dnsmasq/CHANGELOG) that inotify has been implemented in 2.73 with modifications in 2.74 which change how /etc/resolv.conf is processed. Not sure if this would cause the Spotify problems though. @zimmertr do you see any other issues with the pihole?

**Comment by PromoFaux** [comment]
@zimmertr is there any chance you could try downgrading your dnsmasq package on your arch machine to see if that solves it?  Gotta be worth a punt...  

As to how you'd do that, I have no idea!  Although [this link may help with that](https://wiki.archlinux.org/index.php/downgrading_packages)

**Comment by zimmertr** [comment]
I have not. Spotify doesn't work on my laptop nor desktop. Which both run Arch. It works fine on my android phone. Disabling pihole allows spotify to work on the arch installs as well.

**Comment by zimmertr** [comment]
I can try. Too busy right now. Will get back to you later with an update.

**Comment by nate-ubiquisoft** [comment]
I was under the impression you have arch-linux installed on your Pi @zimmertr. Is that true?

**Comment by dschaper** [comment]
It seems like the common thread on these is Arch and Pi-hole. Is there something in the PKGBUILD that is throwing the install?

**Comment by zimmertr** [comment]
I do not have Arch on my Pi. I poorly worded by OP in #364 since it confused @dschaper too. It is running Raspbian.

**Comment by dschaper** [comment]
@nate-ubiquisoft I have a pastebin of the errors that are thrown when Arch starts up Spotify. I think the package is built with a deb and deconstructed to merge together an Arch package...

**Comment by zimmertr** [comment]
That's exactly how it's done. The AUR lists the .deb files as the sources.

https://aur.archlinux.org/packages/spotify/?comments=all

**Comment by nate-ubiquisoft** [comment]
@dschaper can you paste the link to your pastebin with the errors? 
@zimmertr Are you setting your pihole as the dns on your router or individually on each device? I bet you need to modify your local machine /etc/hosts to include your pihole IP (DNS IP) and the pihole hostname.

**Comment by dschaper** [comment]
@nate-ubiquisoft Here you go: http://pastebin.com/1WbNuQmA

**Comment by zimmertr** [comment]
PiHole as set as the DNS on both my router and by devices. It's set redundantly.

I added the the Pi to my DNS on my Arch install but it didn't resolve the issue.

192.168.1.2	mercury.localdomain	Mercury

**Comment by nate-ubiquisoft** [comment]
Can you do the following @zimmertr?
Install libcurl-compat, lib32-openssl, openssl to the latest version as Spotify needs those packages.

**Comment by PromoFaux** [comment]
Ignore my suggestion to downgrade dnsmasq! I went a bit wrong there,  it won't make a difference on your client machine

**Comment by nate-ubiquisoft** [comment]
@zimmertr @PromoFaux I dont have an arch-linux install setup atm. Do you guys have the packages I mentioned to @zimmertr above installed? Spotify uses those to setup the initial network connection when navigating a subnet to Spotify's API. I think this is more of a Spotify issue on arch-linux than an issue with Pi-Hole, but one of the Spotify endpoints MAY need to be whitelisted, however I have not had to do this on my OS X or Windows machines on my network behind my PiHole installation.

**Comment by dschaper** [comment]
Let me check, Arch is up on my end...

**Comment by dschaper** [comment]
```libcurl-compat, lib32-openssl, openssl``` not present in a `pacman -Qe`. Will install and recheck.

**Comment by PromoFaux** [comment]
I don't have an arch setup..  I started to install once,  and then my head imploded and I gave up!

**Comment by dschaper** [comment]
Running a pacman -Syua first and then adding the packages, then I'll drop a paste, hopefully the errors at the top of the startup process go away. (But I wasn't able to replicate the problem, I always was able to access without any issues on a stock Arch install.)

@PromoFaux I'll put a VirtualBox image up on my OneDrive for you if you'd like...

**Comment by dschaper** [comment]
Sorry taking so long, on site and in via ssh while doing other things... Need to get yaourt installed real quick...

**Comment by dschaper** [comment]
Still getting library errors... Digging to see if I can find more dependencies.... (Depo Hell...)

**Comment by dschaper** [comment]
I'm not getting anything new, same dependency errors. I'm compressing up the VDI into a 7z and will post it up to my OneDrive for you guys to try if you'd like...

**Comment by zimmertr** [comment]
@nate-ubiquisoft I already had all of those packages installed.

**Comment by jacobsalmela** [comment]
Spotify Premium works fine on my Mac and iOS devices.  I'll try to set up an Arch VM and if my head doesn't explode, I'll test it out there.

**Comment by zimmertr** [comment]
Haha it's not that hard. The Arch Wiki is the single greatest wealth of Linux information on the internet.

**Comment by dschaper** [comment]
If you guys need an Arch VirtualBox image, let me know. Slack has the link to one that I made. @nate-ubiquisoft if you trust me, you can shoot me an email at dschaper@ganymeade.com and I'll give you the link. It's about 1.25Gigs on OneDrive.

**Comment by zimmertr** [comment]
Anything else that I can test in the meantime?

**Comment by PromoFaux** [comment]
@zimmertr do you have a non-arch client device that you could test spotify on? Maybe windows, or OSX?

**Comment by zimmertr** [comment]
It works fine on my Android phone and my MacBook Air.

**Comment by jacobsalmela** [comment]
Sorry, I haven't installed Arch yet...

**Comment by Righteous** [comment]
On arch using pi-hole with spotify premium and have no issues.

**Comment by PromoFaux** [comment]
@NHgranite @zimmertr any update?

**Comment by Righteous** [comment]
@PromoFaux You can look at my comment for a quick arch install. Takes about 15 minutes max depending on your download speed.

**Comment by PromoFaux** [comment]
Which comment? :)

**Comment by Righteous** [comment]
@PromoFaux "EDIT: I don't know if its the same as installing arch normally but if anyone needs a "graphical installer" for arch you can check out [Architect Installer](https://sourceforge.net/projects/architect-linux/)"

**Comment by PromoFaux** [comment]
ah. Hold on one moment whilst I cover up all traces of my blindness...

**Comment by PromoFaux** [comment]
I will take a look into that if I get some time today. 

Though, this makes me wonder. Did you use the graphical installer to set up arch? I wonder if it includes some dependencies that may be easy to miss when setting it up manually...

**Comment by zimmertr** [comment]
I did not.

**Comment by PromoFaux** [comment]
OK. Lets play whack-a-mole.

@Righteous @zimmertr 

Can you each run `pacman -Q > pacman.txt` and upload the result to pastebin or something please?

**Comment by Righteous** [comment]
If you still need the package list let me know (My arch pc is for work, at work) but I ended up installing a fresh arch install on a extra laptop and got the dependencies setup for spotify. No issues with spotify + Pi-Hole and vice versa. Has to be something specific to OP.

**Comment by zimmertr** [comment]
Sorry for the huge delay in my response. I silenced the email when I received it because I was busy and then completely forgot. Here is the output: http://pastebin.com/yJ99EuZG

Also, today I noticed that my Pi-Hole is completely broken as well. A friend was visiting and tried to use it and couldn't resolve any pages. I then realized that all of my devices were relying on my secondary dns, 8.8.8.8, and probably have been for a while. Any attempts to use Pi-Hole as a DNS server resort in failure to load pages on any devices.

**Comment by PromoFaux** [comment]
Thanks @zimmertr .

@Righteous Could you paste in the package list from your arch machine that spotify works on, please?

@zimmertr Could you run `pihole -d` and paste the contents of `/var/log/pihole_debug.log`. Thanks!

**Comment by Mcat12** [comment]
@zimmertr you will probably have to update Pi-hole to run that command. It outputs a debug log and uses the new command format.

**Comment by zimmertr** [comment]
I'm not sure what happened. I have a feeling some software broke on my pi or something. It doesn't even have internet connectivity anymore so I can't update it. I'll try and recreate it sometime this week when I have more time available and I'll get back to you ASAP.

**Comment by zimmertr** [comment]
After my Pi stopped working I decided to install debian in a virtual machine on my ESXi host. From there I installed pi-hole and configured it to be used as my DNS. Spotify is now in working order on all machines.

It appears that the issue was either the raspberry pi itself or a configuration of pi-hole on the device. Because it works fine from the VM.

**Comment by zimmertr** [comment]
Never mind, after a reboot they're not working anymore. They must have have been working because the client wasn't restarted after setting the DNS server.

**Comment by Mcat12** [comment]
Closing unless it stops working again...
