### ISSUE TITLE
FQDNs are not forwarded for the DHCP pi-hole domain anymore, when checking "Never forward non-FQDNs"

### ISSUE THREAD

**Issue by paulv888** [pi-hole/pi-hole#3990]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2 
- FTL:  5.3.4

### Platform

- OS and version:  Ubuntu 20.04.1 LTS

- Platform:  

### Expected behavior

FQDNs matching pi-Hole domain should still be forwarded. On checking box "Never forward non-FQDNs",  Which was the behavior pre V5. 

### Actual behavior / bug

My Pi-hole domain in my registered domain e.g. mydomain.com , I am checking the box "Never forward non-FQDNs" since pinging hostsnames like "server", "kvm" etc should not be forward. 

However when doing a lookup for a FQDN, i.e. mypublichostedserver.mydomain.com then the name will not resolve, since it is not in the local hosts file, DHCP and **not forwarded.** as expected and as prior V5

### Steps to reproduce

1. Go to 'Settings/DHCP'
2. Enable DHCP and set the Pi-Hole domain name "yourdomain.com"
3. Goto "Settings/DNS"
4. Check box "Never forward non-FQDNs
5. Now lookup a non-local network name, i.e. publicserver.yourdomain.com.
6. Expect this to be forwarded, however resolving seems to stop after hostnames and dhcp leases

## Debug Token

- URL:  https://tricorder.pi-hole.net/jahf9acljb

### Screenshots

NA

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
This is intended.

Setting a domain for the DHCP server makes Pi-hole authoritative for that domain. That means that it is configured with a `local` designation and will not be forwarded.

**Comment by dschaper** [comment]
Side note: I don't think "Never forward non-FQDNs" has any effect with this configuration.

**Comment by DL6ER** [comment]
@dschaper is right, you at your Pi-hole authoritative for this domain. Every subdomain it doesn't know doesn't exist. This is what the standards said and the behavior was broken before.

In your case, I suggest another choice for you domain at home, e.g. `home.mydomain.com`. Devices not existing in this domain will not be forwarded (as expected). However, public devices, e.g., `server.mydomain.com` will work as expected.
