### ISSUE TITLE
Spotify Song-Pictures and Profile-Pictures + -Headers

### ISSUE THREAD

**Issue by Mannamsken123** [pi-hole/pi-hole#3991]
Hi, 
i recently discovered a problem with my Pi-Hole blocking the Song-Pictures and Profile-Pictures + -Headers in the Spotify Win10 Desktop App. 
I whitelisted a lot of lists from github and domains but i still just have an empty space.
Can someone help me?
Edit: I just saw that the Android App is effected too.

![Spotify](https://user-images.githubusercontent.com/68559375/104566994-96a89300-564e-11eb-93fb-f8af9583a203.png)

**Comment by yubiuser** [comment]
This is not per se a Pihole issue. Please use the forum for that type of question.
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/110
