### ISSUE TITLE
Downloading and Installing FTL takes forever

### ISSUE THREAD

**Issue by EscolarProgramming** [pi-hole/pi-hole#3993]
### Versions

- Pi-hole:  5.2.3
- AdminLTE:  5.3
- FTL:  5.3.4

### Platform

- OS and version:  Raspbian stretch

- Platform:  Raspberry Pi

### Expected behavior

Installing FTL will work

### Actual behavior / bug

When updating the PiHoles, FTL is also renewed at the end ([i] Downloading and Installing FTL...). This ran yesterday already two hours, then I canceled it. Now it runs again today for an hour, but nothing seems to happen. Should this really take extremely long, it would not be bad to integrate a progress bar or similar.

### Steps to reproduce

Run "pihole -up"

## Debug Token

- URL:  https://tricorder.pi-hole.net/20t9323rwo

### Screenshots

https://i.imgur.com/xBW6Maz.png

### Additional context

--

**Comment by EscolarProgramming** [comment]
Right after writing this bug report, the FTL installation finished ... I don't know, why it took so long, but I think it can be closed

**Comment by mschmt** [comment]
How is the condition of the Raspberry Pi's SDHC Card? Is it okay or maybe
corrupted?

EscolarProgramming <notifications@github.com> schrieb am Sa., 16. Jan.
2021, 12:33:

**Comment by ozdeadmeat** [comment]
Took my pi about 10 minutes to complete.
