### ISSUE TITLE
Latest pihole docker container continually restarts

### ISSUE THREAD

**Issue by viperman1271** [pi-hole/pi-hole#3994]
### Versions
pihole/pihole:latest 

Impossible to run pihole -v because the container continually restarts

### Platform
- OS and version:  Centos Linux release 7.8.2003 (Core)
- Platform:  Docker
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Expected behavior

The docker container should start and rest in that state

### Actual behavior / bug

The pihole docker image continually restarts

> cont-init.d] 20-start.sh: executing... ,
>  ::: Starting docker specific checks & setup for docker pihole/pihole,
> Assigning random password: O-dtuy85,
>   [i] Update local cache of available packages...
>   [✓] Update local cache of available packages,
>   [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.,
> [cont-init.d] 20-start.sh: exited 1.,
> [cont-finish.d] executing container finish scripts...,
> [cont-finish.d] done.,
> [s6-finish] waiting for services.,
> [s6-finish] sending all processes the TERM signal.,
> [s6-finish] sending all processes the KILL signal and exiting.,
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
> [s6-init] ensuring user provided files have correct perms...exited 0.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [fix-attrs.d] 01-resolver-resolv: applying... ,
> [fix-attrs.d] 01-resolver-resolv: exited 0.,
> [fix-attrs.d] done.,
> [cont-init.d] executing container initialization scripts...,
> [cont-init.d] 20-start.sh: executing... ,
>  ::: Starting docker specific checks & setup for docker pihole/pihole,
> Assigning random password: 2b5dc0OL,
>   [i] Update local cache of available packages...
>   [✓] Update local cache of available packages,
>   [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.,
> [cont-init.d] 20-start.sh: exited 1.,
> [cont-finish.d] executing container finish scripts...,
> [cont-finish.d] done.,
> [s6-finish] waiting for services.,
> [s6-finish] sending all processes the TERM signal.,
> [s6-finish] sending all processes the KILL signal and exiting.,
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
> [s6-init] ensuring user provided files have correct perms...exited 0.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [fix-attrs.d] 01-resolver-resolv: applying... ,
> [fix-attrs.d] 01-resolver-resolv: exited 0.,
> [fix-attrs.d] done.,
> [cont-init.d] executing container initialization scripts...,

### Steps to reproduce

Use pihole/pihole:latest

## Workaround

Use pihole/pihole:v5.3.4 instead of latest. The problem appears to be present only on the latest version

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docker-pi-hole/issues/762
