### ISSUE TITLE
PiHole Core 5.2.3 fails to start on Linux Mint 20

### ISSUE THREAD

**Issue by aleksandre** [pi-hole/pi-hole#3995]
### Versions
- Pi-hole:  5.2.3
- AdminLTE:  
- FTL:  

### Platform
- OS and version:  Linux Mint 20 Ulyana, 5.4.0-60-generic
- Platform:  Docker version 20.10.2, build 2291f61

### Expected behavior

Pihole starts without failling.

### Actual behavior / bug

I run PiHole insider docker on Linux Mint. After pulling the core update ([5.2.3](https://github.com/pi-hole/pi-hole/releases/tag/v5.2.3)), PiHole fails to start with the following error:

  [✓] Update local cache of available packages
 [✗] Aborting installation: iproute2 and iproute packages were not found in APT repository.

### Steps to reproduce

1. Pull pihole/pihole:v5.2.3_amd64 on Linux Mint 20
2. Start PiHole
3. Watch if fail

### Additional context

- The issue is probably related to this [commit](https://github.com/pi-hole/pi-hole/pull/3537/files)

**Comment by yubiuser** [comment]
Thanks for the report. This is a duplicate, the fix has been found already:

https://github.com/pi-hole/docker-pi-hole/issues/762#issuecomment-761698909
