### ISSUE TITLE
Can't update Pi hole

### ISSUE THREAD

**Issue by Thomas499** [pi-hole/pi-hole#3996]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.4

### Platform

- OS and version:  5.4.79-vy

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

I think this might have something to do with it. But I didn't manually lock the database so I am not sure how this happened or how to fix it. 

*** [ DIAGNOSING ]: contents of /var/log

-rw-r--r-- 1 pihole pihole 21404 Jan 17 07:28 /var/log/pihole-FTL.log
   -----head of pihole-FTL.log------
   [2021-01-17 07:10:01.007 300/T304] Encountered step error in get_max_query_ID(): database is locked
   [2021-01-17 07:10:15.027 300/T304] Encountered error while trying to close database: database is locked
   [2021-01-17 07:10:16.028 300/T304] Encountered error while trying to store queries in long-term database: database is locked
   [2021-01-17 07:10:16.028 300/T304] dbquery("END TRANSACTION") called but database is not available!

## Debug Token

- URL:  https://tricorder.pi-hole.net/aossr8idzx

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/38442058/104851036-72ec8380-58c0-11eb-9d11-c993d97ca350.png)

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
The error is suggesting that there is an issue with the local repository at `/etc/.pihole`.

What is the output of :
```
cd /etc/.pihole
sudo git pull
```

**Comment by Thomas499** [comment]
![image](https://user-images.githubusercontent.com/38442058/104851784-0b850280-58c5-11eb-87ea-d730eec56019.png)

**Comment by PromoFaux** [comment]
OK. Something has gone wrong with that folder. It's probably indicative of a corrupt file system - this can be caused by many things, but usually it's because the power supply used to power the Pi isn't up to the job. See this chart to make sure you've got the correct type:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md

In the mean time, you can attempt to repair this installation by running:

```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
pihole -r
```

But you may even want to start again by flashing a new SD card to rule out any other corruptions elsewhere on the OS.

**Comment by McVillan** [comment]
Had the same problem when trying to update to 5.2.3 (Pi hole updated but using a SSH conexion and pihole -up seemed to update only pihole (Admin LTE and FTL always said update available via the web interface) updated 3 times .. same. This latest version seems to update all 3 main components without problems.
