### ISSUE TITLE
DNS records in custom.list do not show up in GUI if multiple hostnames are specified after IP

### ISSUE THREAD

**Issue by shunkica** [pi-hole/pi-hole#4005]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.1
- FTL:  5.5.1

### Platform

- OS and version:  CentOS 7

- Platform:  Docker

### Expected behavior

DNS records from /etc/pihole/custom.list with multiple hostnames for IP should show up in the GUI (admin/dns_records.php)

### Actual behavior / bug

DNS records from /etc/pihole/custom.list with multiple hostnames for IP do not show up in the GUI. Only DNS records with 1:1 IP:hostname are shown.

### Steps to reproduce

1. Add DNS record with multiple hostnames to /etc/pihole/custom.list
eg:
`1.2.3.4 example1.com example2.com`
2. Run `pihole restartdns`
3. DNS is resolved correctly:
```
$ nslookup example1.com
Server:		10.10.10.20
Address:	10.10.10.20#53

Name:	example1.com
Address: 1.2.3.4
$ nslookup example2.com
Server:		10.10.10.20
Address:	10.10.10.20#53

Name:	example2.com 
Address: 1.2.3.4
```
4. DNS records for example1.com and example2.com are not shown in the GUI.

### Additional context
I realize I could do this:
```
1.2.3.4 example1.com
1.2.3.4 example2.com
```
 and have the records display in the GUI, but it seems redundant, especially since the DNS is resolved correctly.

The GUI should support adding multiple hostnames for an IP without having to add a separate entry for each hostname.

**Comment by yubiuser** [comment]
Thanks for the report.
All feature requests should go to
https://discourse.pi-hole.net/c/feature-requests/8

Please search for existing requests before opening a new one. E.g.quite similar is already
https://discourse.pi-hole.net/t/supporting-the-ipaddress-fqdn-hostname-format-in-the-local-dns-records-page/33124
