### ISSUE TITLE
Python rewrite & deb packages

### ISSUE THREAD

**Issue by ryt51V** [pi-hole/pi-hole#401]
Ok, this isn't an issue, but it is very development related - I thought people would prefer to discuss it here.  If not then I apologise.

Pi-Hole is awesome and I am so glad I found this project.  Many thanks to Jacob and all of the devs who have worked so hard on this.

A few weeks ago I begun a fork of Pi-Hole for myself and began making a few changes - support for multiple IP addresses on an interface, DNS using custom ports, apache support, following best practices for where certain files go, etc..  All entirely for selfish reasons, though I did take the time to make a few pull requests.

In making changes a few patterns started to develop:
- I write bash scripts all the time, but the complexity of Pi-hole means implementing anything slightly non-trivial gets annoying really quickly.  Maybe I'm just a poor shell scripter, but IMO Pi-Hole's scope has long passed the point where bash stops being the best tool for the job.
- I want Pi-hole's scripts out of my /usr/local/bin - if I'm not mistaken [they don't belong there](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/usr.html), and either way I want them out.  But at the same time only properly packaged packages should dump things in /usr/bin, not a bash script installer.
- Pi-Hole's uninstaller is actually dangerous.  I've been using my own modified uninstall script for testing but decided to run the one in the repo once.  Big mistake - it purges `bc` which is a dependency of `fish`; my default shell.  After running that uninstall I was no longer able to SSH into my pi (made me very glad I've automated daily full SD card backups).  But you can't blame the uninstaller because what's the solution?  How does a bash script keep track of why `bc` was installed?  Answer: It doesn't.

I have been spending the past week or so on a rewrite of Pi-Hole, once again entirely for selfish reasons.  Imaginatively named pyhole (!), it's a python rewrite and is designed to build into a .deb package, allowing clean(er) install and removal with dpkg.  Most of my improvements in my Pi-Hole fork have been ported over.  I've made it for both Raspbian **and** Debain Jessie, testing on both a physical pi and Debian VM.  I've made a fuller (but still incomplete) list of improvements, changes, issues, and regressions on its [project page](https://github.com/pyhole/pyhole).

Why am I posting this here?  I'm not trying to replace Pi-Hole; open source isn't a competition.  I don't think my version is "better" nor do I think I'm a particularly good Python developer.  I'm not trying to get people to work on my project for me so I can put my feet up, and I'd probably be quite poor on managing a collaborative open source project.  It's **certainly** not stable yet.  I'm perfectly happy to work on pyhole all on my own for myself, silently watching Pi-hole and cloning any new features I feel like.

However I've seen many times references to an upcoming code refactor, which it not being completed is getting in the way of accepting pull requests even to the dev branch.  I agree a refactor is needed, but if it were me I would absolutely hate to do it in bash - maybe that's why not much progress seems to have been made.  I just think Python is a far better choice of language now that Pi-Hole has evolved so much, and I figured I owed everyone the courtesy of making you aware of my python rewrite.

Whether you use it, fork it, ignore it, tell me where I can go - whatever, you have the choice :)
##

**Comment by dschaper** [comment]
Py 2 or py 3? Or portable 2 with future import? I'm definitely interested
in the progress of this. No words of telling you where to stick, other than
in a fork and PR. Let's see how this fleshes out, how it impacts
portability and performance. Remember we are shooting  for the Zero as the
lowest common and it should Just Work on that. Keep going!

The refactor is in progress, but its like steady hand surgery. Pulling out
the right bits without breaking backwards compatibility. We developers are
in almost 24 hour communication even though we are spread out globally and
all work this project on spare time and donations. We will get there and we
highly value all input to and from our users.

**Comment by ryt51V** [comment]
Python 3; only tested with 3.4 on (Deb|Rasp)ian.  To be frank, while I'm aware of portability reasons, I have no personal interest in getting this working on Python 2.

As it's a complete rewrite (only a few conf files are slightly in common) I didn't think it was suitable for a pull request, but the repo will always be there.

I'm not trying to undermine the refactor or any other efforts, mean to suggest anyone is sitting around twiddling their thumbs, or that even if you _do_ like this that it's a quick decision you make at the drop of the hat.  I just wanted to make this project aware of this option _in case_ it's useful to yourselves (or anyone) - if not then fine by me, I'm writing it for me anyway :)

**Comment by Mcat12** [comment]
I think when we get the time (lol, let's be real, no one has time) we're probably ok with changing to Python. It'll help with some structural things and it gets Bash out of the equation. ;)

**Comment by dschaper** [comment]
Python, nginx, and unbound. Just do it all in one big rewrite so there's no backwards compatibility issues. Would also help with Debinizing, but there's some linter issues there that would need to be addressed.

**Comment by dschaper** [comment]
@ryt51V The beginnings of the Python rewrite are now in process. There are two branches now that are focused on Python. One is a portage of the existing bash and adding in a database as the scaffolding and the other is a ground up OO rewrite. We are approaching this with a few different disciplines just to see what works and then cherry-pick the best of all worlds. 

We've decided to go with Python 3, with any installer scripts being done either in bash or in agnostic Python. (I'm doing the complete rewrite as I have time to work on it, but the branch is really alpha and concept testing, I'm trying to go with pure Python data structures, and Mark is working on the database based approach, but we are all volunteers that work on this project and have a ton of other things going on while we develop and support both the existing work and the rewrite, and still handling some refactoring to tide things over...) 

We will definitely be looking over your code and hopefully when things progress to a little more maturely developed code we can open the discussion dialog with you again!

**Comment by dschaper** [comment]
And any comments made on decisions as to language and versions are subject to change. We know this is getting unwieldy and are working on fixing that with a long term solution.
