### ISSUE TITLE
Missing php extention PHP8 - JSON - unable to update PiHole FTL

### ISSUE THREAD

**Issue by dutch2005** [pi-hole/pi-hole#4014]
### Versions

Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.1 (Latest: v5.3.1)
  FTL version is v5.3.4 (Latest: v5.5.1) 

### Platform

- OS and version:    Ubuntu 20.04

- Platform: x86-64

### Expected behavior

Update from PiHole FTL 5.3.4 to 5.5.1
Skip php8.0-json since this extention is embedded in the php8.0-common module

See: 

- https://php.watch/versions/8.0/ext-json
- https://php.watch/articles/php-8.0-installation-update-guide-debian-ubuntu
- https://github.com/oerdnj/deb.sury.org/issues/1439

### Actual behavior / bug

Dependency issue concerning php 8.0-json

### Steps to reproduce

1) update PHP to 8.0
2) pihole -up

```
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 8.0.1
  [i] Performing unattended setup, no whiptail dialogs will be displayed

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php8.0-common
  [✓] Checking for php8.0-cgi
  [✓] Checking for php8.0-sqlite3
  [✓] Checking for php8.0-xml
  [i] Checking for php8.0-json (will be installed)
  [✓] Checking for php8.0-intl
  [i] Processing apt-get install(s) for: php8.0-json, please wait...

E: Package 'php8.0-json' has no installation candidate

  Unable to complete update, please contact Pi-hole Support
```

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/json-has-no-installation-candidate/42126/3?u=yubiuser

**Comment by dutch2005** [comment]
Ah yeah, any ETA on this? (the embedded option).

**Comment by dschaper** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1439#issuecomment-685007848

**Comment by p1r473** [comment]
I removed all references of php8.0-json from the install script and tried to install it on a system with PHP 8.0
@dschaper Just for the record it works perfectly fine and I dont have any problems with it. Everything working great on PHP 8.0.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/pull/4135

**Comment by p1r473** [comment]
Whoops sorry, I had googled php8.0 and I guess that didnt show up due to it just saying php8
Great work!

**Comment by teeli** [comment]
Just in case anyone is like me and is trying to update pi-hole on Ubuntu with a custom PHP install, here's what you need to do: remove all mentions of php-json (including `"${phpVer}-json"`) from `/etc/.pihole/automated install/basic-install.sh`, then run `pihole -up`

**Comment by teeli** [comment]
> @teeli
> 
> Would modifying the install-script not be a better sollution?
> 
> (I mean using a "if-statement", e.g. PHP =7.* --> check for JSON if PHP >= 8 --> dont do the php-json check/install.)

I'll be honest, I didn't dig into this too deep. I found that when you upgrade pihole using `pihole -up` it uses the script located in the path in my comment and did a quick and dirty fix so that I can run the upgrade without errors. It worked, so good that's good enough for me. Surely there could be better ways :)
