### ISSUE TITLE
PiHole doesn't block certain domains.

### ISSUE THREAD

**Issue by zigapovhe** [pi-hole/pi-hole#4016]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.1
- FTL:  v5.5.1

### Platform

- OS and version:  Raspberry Pi  OS 5.4.83-v7+

- Platform:  Raspberry Pi 3B+

### Expected behavior

Domain should be blocked and marked with red, but it isn't.
I know that the site is not currently reachable (it was probably shut down), but I'm still curious why did Pi-Hole allowed and forward the request and did not block it.

### Actual behavior / bug
The domain forwarded and allowed.
https://i.imgur.com/eEGc4QP.png

### Steps to reproduce

1. Add https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt adlist
2. Update gravity
3. Try to access a domain from that list
4. Check pihole query logs

## Debug Token

- URL:  https://tricorder.pi-hole.net/kikix89b54

 

### Screenshots
https://i.imgur.com/OOBb9AQ.png
https://i.imgur.com/eEGc4QP.png
https://i.imgur.com/ENmFv4V.png

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
The query shown in the query log is malformed. A URL appears, and this will not be resolved. The client is not requesting the domain name, which would match your domain entries.

**Comment by sjt5** [comment]
Tried the same steps within Pi-hole. Opened url in browser and Pi-hole shows Domain "bestdarkstar.info" "Blocked (gravity)".
> 2021-01-26 23:04:51 | A | bestdarkstar.info | fe80::b5f3:a0c9:2e7c:fd62 | Blocked (gravity) | IP (0.2ms)

From powershell ran (incorrect command to reproduce issue):
```
> nslookup https://bestdarkstar.info
Server:  UnKnown
Address:  fe80::20c:29ff:fea0:6490

*** UnKnown can't find https://bestdarkstar.info: Non-existent domain
```

Pi-hole shows (incorrect domain as it includes "https://") domain 
> 2021-01-26 23:53:09 | A | https://bestdarkstar.info | fe80::b5f3:a0c9:2e7c:fd62 | OK (forwarded to resolver2-fs.opendns.com#53) | NXDOMAIN (10.8ms)

jfb-pihole is spot on with that analysis.
