### ISSUE TITLE
piholeDebug.sh Multiple Interfaces leads to ping failure

### ISSUE THREAD

**Issue by Flashbang007** [pi-hole/pi-hole#4019]
This is the first issue I am opening on github, so please be kind, if I make a mistake :-)

### Versions
- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.1
- FTL:  v5.5.1

### Platform
- OS and version:  Raspbian GNU/Linux 10
- Platform:  Raspberry Pi

### Expected behavior

When executing ``` pihole -d ``` I expect, that the default Gateway is pingable, but i get an error as shown below.

### Actual behavior / bug

```
[i] Default IPv4 gateway: 10.0.0.1
10.0.0.1
   * Pinging 10.0.0.1
10.0.0.1...
ping: 10.0.0.1
10.0.0.1: Name or service not known
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)

[i] Default IPv6 gateway: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8
   * Pinging fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8...
ping: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8: Name or service not known
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

### Steps to reproduce

This error occures, if you have two interfaces and thus two default gateways.
```
>pi@pihole:~$ ip -4 route
default via 10.0.0.1 dev eth0 src 10.0.0.30 metric 202
default via 10.0.0.1 dev wlan0 proto dhcp src 10.0.0.39 metric 303
10.0.0.0/24 dev eth0 proto dhcp scope link src 10.0.0.30 metric 202
10.0.0.0/24 dev wlan0 proto dhcp scope link src 10.0.0.39 metric 303
```

## Debug Token
Not possible: 
```
>pi@pihole:~$ `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
ping: 10.0.0.1
10.0.0.1: Name or service not known
ping: fe80::7eff:4dff:fef1:22c8
fe80::7eff:4dff:fef1:22c8: Name or service not known
[?] Would you like to upload the log? [y/N] y
-bash: $'\E[H\E[J\E[3JThis': command not found
```

### Additional context
the Problem is that the Ping Command in the follwing line 
https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/piholeDebug.sh#L708
resolves to: ```ping -c 1 -W 2 -n 10.0.0.1 10.0.0.1 -I eth0 ```, as I have two interfaces plugged an thus two default gateways. 

I might have a fix for this issue, as you could change 
https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/piholeDebug.sh#L698
to 
```
gateway="$(ip -"${protocol}" route | grep default | grep ${PIHOLE_INTERFACE} | cut -d ' ' -f 3)"
```

**Comment by dschaper** [comment]
You really shouldn't have two default gateways. Are botht eth0 and wlan0 up/up at the same time?

**Comment by dschaper** [comment]
The proposed code looks okay, can you open a PR to change that?

**Comment by Flashbang007** [comment]
> You really shouldn't have two default gateways. Are botht eth0 and wlan0 up/up at the same time?

In my setup, this is realy not necessary and I will set wlan0 down. But I guess networt wise it should be allowed. The Metric in theese rules define where the traffic flows.
```
default via 10.0.0.1 dev eth0 src 10.0.0.30 metric 202
default via 10.0.0.1 dev wlan0 proto dhcp src 10.0.0.39 metric 303
``` 


> The proposed code looks okay, can you open a PR to change that?

This would also be my first pull request. I'll try. 

Thanks for the reply so far.

**Comment by yubiuser** [comment]
Fixed with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
