### ISSUE TITLE
Admin Web Interface only showing CODE

### ISSUE THREAD

**Issue by beardofbeespool** [pi-hole/pi-hole#402]
##### Expected Behaviour:
Expect to see the web interface w/stats - when visiting "pi-IPADDRESS"/admin/index.php

##### Actual Behaviour:
Only seeing PHP code

##### Steps to reproduce this issue:
Not sure how...

![image](https://cloud.githubusercontent.com/assets/16466705/14055327/13438630-f2af-11e5-8a10-5e0b094b3376.png)

The above photo is from Chrome, below is from Edge browser:

![image](https://cloud.githubusercontent.com/assets/16466705/14055380/719be862-f2af-11e5-9bf8-a0f07e0de928.png)

If I go to 192.168.4/admin/header.html I see the below:
![image](https://cloud.githubusercontent.com/assets/16466705/14055425/e441f9e2-f2af-11e5-9604-dbaebb9e39bd.png)

##### Notes:
I have tried to do a standard install, hoping it would install over top, it did not fix it.

**Comment by Mcat12** [comment]
Do you have an ftp server running under the web server root? That's the first thing that came to my mind...

**Comment by beardofbeespool** [comment]
@Mcat12 I dont, I have a local web server running, that is only accessible via 192.168.1.4

**Comment by nate-ubiquisoft** [comment]
@beardofbeespool Wait so you have a webservice running on your Pi which, from what you provided, is listening on port 80 which is what the pihole admin interface listens on. There can be a conflict doing this. I recommend stopping your web server, reboot the pi, and see if the admin page now works with your custom web server stopped.

**Comment by Mcat12** [comment]
Was this a clean install?

**Comment by beardofbeespool** [comment]
@nate-ubiquisoft 

pi@raspberrypi:~ $ sudo service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Fri 2016-03-25 17:25:03 CDT; 2h 36min ago
  Process: 656 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 478 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 656 (code=exited, status=255)

Mar 25 17:25:02 raspberrypi lighttpd[478]: Syntax OK
Mar 25 17:25:03 raspberrypi lighttpd[656]: 2016-03-25 17:25:02: (network.c.4...e
Mar 25 17:25:03 raspberrypi systemd[1]: lighttpd.service: main process exite...a
Mar 25 17:25:03 raspberrypi systemd[1]: Unit lighttpd.service entered failed....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by beardofbeespool** [comment]
@nate-ubiquisoft 

pi@raspberrypi:~ $ netstat -tnlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State                                                                                                                                                                    PID/Program name
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN                                                                                                                                                                   -
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN                                                                                                                                                                   -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                                                                                                   -
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN                                                                                                                                                                   -
tcp6       0      0 :::139                  :::*                    LISTEN                                                                                                                                                                   -
tcp6       0      0 :::80                   :::*                    LISTEN                                                                                                                                                                   -
tcp6       0      0 :::53                   :::*                    LISTEN                                                                                                                                                                   -
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                                                                                                   -
tcp6       0      0 :::445                  :::*                    LISTEN                                                                                                                                                                   -

**Comment by nate-ubiquisoft** [comment]
@beardofbeespool Yup! Your web server is preventing lighttpd from launching, which effectively disables pihole. You will need to either change the listening port for your local web server or move it to another device than the PiHole. Realistically, especially due to the cheap price, the Raspberry Pi running PiHole should NOT have anything else running on it. Just grab another Pi or two XD

**Comment by beardofbeespool** [comment]
@nate-ubiquisoft 

I used this to build the webpage, was testing the material lite layouts: https://www.raspberrypi.org/learning/lamp-web-server-with-wordpress/worksheet/

**Comment by beardofbeespool** [comment]
@nate-ubiquisoft should I remove the entire Apache 2 install then?

**Comment by nate-ubiquisoft** [comment]
@beardofbeespool if it is apache 2, then you can do the following to simply disable it for now:
`sudo service httpd stop`
`sudo service httpd disable` (This will stop it from launching at boot)
`sudo reboot`
and check the status of lighttpd again after rebooting
`sudo service lighttpd status`

**Comment by beardofbeespool** [comment]
@Mcat12  @nate-ubiquisoft ...in the end I rebuilt this Pi, It was needing it. I think you were right but I couldent seem to stop the other pages from interrupting the Pi-hole admin page. Thanks all for your help. It was just faster in the end to rebuild the Pi
