### ISSUE TITLE
I can not enable blocking service.

### ISSUE THREAD

**Issue by qq523407234** [pi-hole/pi-hole#4025]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.2
- FTL:  v5.6

### Platform
- Platform:  Debian 10

### Expected behavior

I can not enable blocking service.

### Screenshots

![image](https://user-images.githubusercontent.com/12459872/106351507-aba44800-6317-11eb-8bb0-04b141973bf2.png)

**Comment by qq523407234** [comment]
![image](https://user-images.githubusercontent.com/12459872/106351553-08076780-6318-11eb-9085-f5e2e443130a.png)

**Comment by yubiuser** [comment]
Please provide a debug token.

**Comment by qq523407234** [comment]
> 请提供调试令牌。

https://tricorder.pi-hole.net/bpbl1d23pn

**Comment by jfb-pihole** [comment]
You have multiple conflicting entries in file **/etc/pihole/setupVars.conf**

    BLOCKING_ENABLED=true
    BLOCKING_ENABLED=false

Edit the file, delete the one you don't want and restart FTL with `pihole restartdns `

**Comment by aebgit** [comment]
Same issue here on Raspbian 9.13 and I swear I've never touched this file by hand. 
There seems to be a condition where this double entry is created by PiHole.

Pi-hole v5.3.1
Web Interface v5.5  
FTL v5.8.1

(Just wanted to have this documented. Thanks a lot for maintaining this awesome project!)
