### ISSUE TITLE
www-data is not added to necessary groups when host OS is Android

### ISSUE THREAD

**Issue by yufufi** [pi-hole/pi-hole#4030]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  Debian Buster

- Platform:  Android

### Expected behavior
Admin portal can connect to FTL on Android based setup.

### Actual behavior / bug
Admin portal cannot connect to FTL on Android based setup. `www-data` user doesn't have the right group memberships to execute `socket()` 

Following command solves the problem for me. 
`usermod -a -G aid_inet,aid_net_raw www-data`

See [here](https://stackoverflow.com/questions/36451444/what-can-cause-a-socket-permission-denied-error)

### Steps to reproduce

1. Grab an old Android phone
2. Root it
3. Install Linux Deploy
4. Install Debian
5. Install Pihole
6. Go to admin portal

## Debug Token

- URL:  https://tricorder.pi-hole.net/jjywxi9xf3

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by yufufi** [comment]
@dschaper I'm not experience issue anymore as I've already sold it and I wanted to also offer the solution (together with the issue report) so either `Pihole` team can pick it up or it would be documented so others can use it. Is there a documentation somewhere I can add this maybe?

**Comment by yufufi** [comment]
Another issue:

`scripts/pi-hole/php/header.php` tries to use `pidof` to get the `pid` of `pihole-FTL`. This is not possible in android as `proc` is mounted with `hidepid=2`.

Updating the function as below solves the problem:

``` php
function pidofFTL()
{
    return shell_exec("cat /run/pihole-FTL.pid");
}
```
