### ISSUE TITLE
Pi-hole no longer allowing internet access on wifi after changing to a recursive dns, but wired still works.

### ISSUE THREAD

**Issue by serialscaresme** [pi-hole/pi-hole#4031]
### Versions
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.2 (Latest: v5.3.2)
  FTL version is v5.6 (Latest: v5.6)

### Platform
- OS and version:  Windows 10 20H2
- Platform:  Oculus Quest, Raspberry Pi 400, Custom PC

### Expected behavior

I expect my devices to work over wifi and ethernet after updating the pi-hole to be a recursive dns using this guide. https://docs.pi-hole.net/guides/dns/unbound/ 

### Actual behavior / bug

The devices only work wired, no wireless internet access. The devices can connect to the router but there is no internet.

### Steps to reproduce

follow the guide on the website exactly, when pi was fully updated and upgraded

## Debug Token

- URL:   https://tricorder.pi-hole.net/157ne2ltz3

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Router- Netgear RAX15
Host- Raspberry pi 4b 4gb

**Comment by yubiuser** [comment]
Did it work before you installed unbound?

Your debug lo shows Pi-hole is working as intended and no errors are shown. This is likely a network or router issue.
Your router advertises it self as DNS server via DHCP -is this intended?

```

   * Received 548 bytes from eth0:192.168.1.1
     Offered IP address: 192.168.1.16
     Server IP address: N/A
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.1.1
      lease-time: 86400 ( 1d )
      netmask: 255.255.255.0
      router: 192.168.1.1
      dns-server: 192.168.1.1
```

Best option would be to open a thread in the [help topic over on discourse.](https://discourse.pi-hole.net/c/bugs-problems-issues/11)

**Comment by serialscaresme** [comment]
Yes, it worked before the guide
And that was intended, as I didn't feel like setting up the pihole as the ip distributor (I forget the name)
And my router calls to the pi for all dns requests

**Comment by eugef66** [comment]
you may be getting different IP address from dhcp when your RPI on wifi vs wired because your MAC is different. Check you MAC-IP mapping or if your RPI setup for static IP make sure you change interface to wlan0 for the static IP.

**Comment by serialscaresme** [comment]
I'm sorry, I don't understand

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/c/bugs-problems-issues/11
