### ISSUE TITLE
Error in instructions to skip OS check (when updating)

### ISSUE THREAD

**Issue by m-alt-f** [pi-hole/pi-hole#4032]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:   v5.3.1
- FTL:   v5.5.1

### Platform

- OS and version: Debian Buster

- Platform:  arm64

This is a very small and simple issue.

Trying to _update_ pihole on an "unsupported" device gives a suggestion to _repair_ the device. (pihole -r)

[screenshot](https://u.pcloud.link/publink/show?code=XZOSSbXZVdmrgr4RhXu2VDAzUO6sqSX8H3nk)

It should suggest pihole -up.
Not pihole -r.

**Comment by dschaper** [comment]
Read all 3 lines of that paragraph. It’s all correct.

**Comment by m-alt-f** [comment]
You mean it should read “pihole -r” rather than “pihole -up”?
If so, my bad.

When I used -r, I panicked as it started raking me though the initial setup and all I wanted to do was update it.

I aborted, used -up, and it worked beautifully. So not sure why it should be -r?
