### ISSUE TITLE
pi-hole does not support 172.16.0.0/12 in conditional forwarding, its a valid cidr and part of rfc1918

### ISSUE THREAD

**Issue by lthasenhod** [pi-hole/pi-hole#4034]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.4

### Platform

- OS and version:  Debian 10

- Platform:  VM

### Expected behavior

When adding 172.16.0.0/12 as conditional forwarding, it does not accept the input and can not save.

### Actual behavior / bug

172.16.0.0/12 is a valid cidr and part of the rfc1918

**Comment by yubiuser** [comment]
Thanks for the report.
This is a known limitation and must be fixed upstream. 

See here 

https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975
