### ISSUE TITLE
Windows 10 internet status / app connectivity not working

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#404]
##### Expected Behaviour:
After whitelisting msftncsi.com and www.msftncsi.com (per issue #315), network status icon in Windows 10 should not show yellow exclamation point.

##### Actual Behaviour:
After upgrading to the latest Insider Preview Build (14295), the yellow exclamation point is back on my network status icon even though internet connectivity is fine. Also, the Feedback Hub and Weather apps don't work, saying there is no connection. 

I tried watching the log to see if I could determine which sites are being used/blocked, but could not identify them.

##### Steps to reproduce this issue:
Upgraded to Windows 10 Insider Preview build 14295.

If I ping msftncsi.com, I get 'unknown host.' Pinging www.msftncsi.com resolves to 72.37.154.41 (a1961.g2.akamai.net).

**Comment by Alomamabobo** [comment]
Same issue here on Standard Windows 10 install.

**Comment by jradwan** [comment]
I was seemingly able to work around this by turning off my Pi-Hole and doing a "ipconfig /flushdns" and "ipconfig /registerdns" on the Windows 10 machine, followed by a reboot. This allowed the internet status and other apps (Weather, Feedback Hub, etc.) to properly work (since presumably they weren't being blocked by Pi-Hole).

I turned my Pi-Hole back on last night and today these features are still working in Windows 10. Could be a DNS cache and maybe it will stop working again, but for now they're working.

**Comment by Alomamabobo** [comment]
Yup the /flushdns did the trick, forgot about it :) Thanks.

**Comment by PromoFaux** [comment]
@jradwan So this issue was solved by flushing the DNS cache on your windows 10 PC? I was beginning to wonder if maybe the insider preview had changed the connectivity domain...

**Comment by jradwan** [comment]
It's only temporarily fixed. If I use /flushdns and /registerdns while the Pi-Hole is off, everything works. But as soon as I do a flush/register with the Pi-Hole running, I get the yellow exclamation point on the network connection and the Feedback app (and a few others) report there is no internet connectivity.

**Comment by PromoFaux** [comment]
Interestingly, I've just done a fresh install of pihole (nothing on my whitelist yet) And i'm not getting the yellow triangle at all (where I would expect one) did `/flushdns` `/renew` `/registerdns` and a reboot... pi-hole running at all times...

**Comment by jradwan** [comment]
When I try to ping msftncsi.com I get "Ping request could not find host msftncsi.com. Please check the name and try again." I can ping www.msftncsi.com though. Maybe that's my problem? If I grep for msftncsi in /etc/pihole this is what I get:

```
18:59:49 /etc/pihole:$ grep msftncsi *
list.0.raw.githubusercontent.com.domains:0.0.0.0 msftncsi.com
list.0.raw.githubusercontent.com.domains:0.0.0.0 www.msftncsi.com
list.8.raw.githubusercontent.com.domains:#msftncsi.com
whitelist.txt:msftncsi.com
whitelist.txt:www.msftncsi.com
```

**Comment by PromoFaux** [comment]
I need to check on a non-piholed system to see if it's normal to get no ping return on `msftncsi.com`, which I will do at work tomorrow.

**Comment by dschaper** [comment]
Just a general question, but does the script take the comment out of `list.8` and populate `gravity.list` with 2 copies of `msftncsi.com`?

Can you do a `grep` of `gravity.list` and see if the domains show at all in the final list? Also, can you run a `cat /var/log/pihole.log |grep gravity.list` and see if the msft domains are being Pi-holed while you ping?

**Comment by dschaper** [comment]
@PromoFaux But the error is a No Domain Found error, not a ICMP blocked error I believe.

**Comment by PromoFaux** [comment]
@dschaper Yeah, that's what I meant.. :)

@jradwan confirmed on a system untouched by pi-hole that you should get host not found

![image](https://cloud.githubusercontent.com/assets/1998970/14108596/100041de-f5b6-11e5-9874-567c2fdcbeba.png)

**Comment by dschaper** [comment]
@PromoFaux Running a root check to see if that domain even exists. Sorry about the ICMP comment, I know you know. Brain wasn't working right at the moment...

**Comment by dschaper** [comment]
[dnsreport_msftncsi.com.pdf](https://github.com/pi-hole/pi-hole/files/193965/dnsreport_msftncsi.com.pdf)

According to the report, there is no literal for that domain, only a `www` (A) record. All is functionally nominal.

**Comment by jradwan** [comment]
Ok, so no need to black/whitelist msftncsi.com then, thanks. The FAQ should probably be updated to reflect that?

Everything's working fine tonight, but I haven't done a /flushdns since my last reboot with the Pi-Hole off.

**Comment by Mcat12** [comment]
I think you still need to whitelist msftncsi.com and www.msftncsi.com.

**Comment by dschaper** [comment]
Msftncsi.com doesn't resolve so it probably won't need to be whitelisted.

Dan Schaper via GS3

**Comment by Mcat12** [comment]
Only the www one then?

**Comment by dschaper** [comment]
I believe so, from what I interpret of the DNS report, the naked domain doesn't resolve, however the full decorated www domain does. Now if Microsoft is expecting the naked domain to fail and is using that failure as an indicator that things are operating correctly, that's a whole 'nother story....

**Comment by PromoFaux** [comment]
@jradwan How has it been behaving over the last week?

**Comment by jradwan** [comment]
Everything's been fine, actually. I was out of town over the weekend (so my PC was off but Pi-Hole was on) and haven't noticed the problem this week so far.

I'll see what happens when the next Insider Preview build is pushed out.

**Comment by PromoFaux** [comment]
2.6.1 now! 

The windows 10 telemetry is just an update to `adlist.default` to point to the correct host file download. It's commented out by default.

**Comment by Mcat12** [comment]
Is this still an issue?

**Comment by jradwan** [comment]
I have not had the problem again since I originally filed the issue, so I guess you can close it!
