### ISSUE TITLE
Nginx reverse proxy yields "Invalid JSON response"

### ISSUE THREAD

**Issue by jaredmo** [pi-hole/pi-hole#4040]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.2
- FTL:  v5.6

### Platform

- OS and version: Raspbian GNU/Linux 10 

- Platform:  Raspberry Pi

### Expected behavior

Able to reverse proxy the lighttpd site via Nginx.

### Actual behavior / bug

Accessing the Groups page yields the following error.

`DataTables warning: table id=groupsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

### Steps to reproduce

1. Reverse proxy the lighttpd site through Niginx with the config below.
2. Click the Group Management > Groups page.

```
server {
        listen 80;
        server_name pihole.example.com;

        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;
        server_name pihole.example.com;

        location / {
        proxy_pass http://192.168.1.55:8080/admin/;
        }
}
```

### Additional info
This could be a CORS issue.

`Failed CORS: null vs 192.168.1.55, , 192.168.1.55, pi.hole, localhost`

**Comment by jaredmo** [comment]
I solved the problem, but I wanted to share the solution. I added `proxy_set_header Host $host;` to my conf file under `location` and everything appears to be working.

**Comment by schmurian** [comment]
Thank you!
