### ISSUE TITLE
i cant access by hostname like http://raspberypizero.local/

### ISSUE THREAD

**Issue by enlacee** [pi-hole/pi-hole#4041]
![raspberrypizero local](https://user-images.githubusercontent.com/179639/107063812-cb6cbd80-67a8-11eb-90e8-6ee384ed824a.png)
i cant access to my local hostname by browser: http://raspberrypizero.local
I can't understand why this happens
I have review all file list and it is not

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/issues/1896#issuecomment-355788710
