### ISSUE TITLE
Allow multiple IPv6 entries for local DNS

### ISSUE THREAD

**Issue by dandjo** [pi-hole/pi-hole#4044]
### Versions
- Pi-hole version is v5.2.4 (Latest: v5.2.4)
- AdminLTE version is v5.3.2 (Latest: v5.3.2)
- FTL version is v5.6 (Latest: v5.6)

### Platform
- OS and version: Ubuntu Server 20.10
- Platform: Raspberry Pi 4

### Expected behavior

Add multiple IPv6 entries for one and the same domain.

### Actual behavior / bug

An error message is thrown that an IPv6 for that domain already exists.

### Discussion

As multiple IPv6 addresses for one interface are a core concept of IPv6, Dnsmasq will also allow multiple addresses in general. The restriction in Pi-Hole is a blocker if you are heavily relying on reverse-lookups of IPv6 addresses. I would consider this as a bug, since it is against standards. I'm currently working around this by editing the file without GUI.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by franz-josef-kaiser** [comment]
I already stumbled upon the same problem. I wouldn't call this a feature request. It's more a regression…
