### ISSUE TITLE
No block website on Windows 10 Desktop

### ISSUE THREAD

**Issue by enlacee** [pi-hole/pi-hole#4046]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.2
- FTL:  v5.6

### Platform

- OS and version:  Raspbian 10 (buster)

- Platform:  Raspberry Pi Zero W

### Platform testing
_windows 10 PRO  I5 64BIT_

### Expected behavior

_Block web page PORNOFRAPHIC like:  xvideos.com._

### Actual behavior / bug

_1. work all devices mobiles (iphone, tablets)_
_2. work in my laptop LINUX (ipv4, ipv6 enabled)_
_3. But in my laptop WINDOWS 10  (ipv4, ipv6 enabled) not work ? (Does not block the porn website)._

note: i/m take a screenshot making ping to porn website and this is the result:
`ping www.xvideos.com`
 * **[Putty SSH server pihole]** The first windows load logs: `pihole tail`
 * **[ComandPrompt client windows10]** the second window I do the ping

![error-no-bloquea=pihole](https://user-images.githubusercontent.com/179639/107448874-87631b00-6b10-11eb-9994-e996adf3abd5.png)

### Steps to reproduce

1. Go to open browser and write the URL: `www.xvideos.com`
2. Enter and to wait
3. The website loads completely

### Addicional context
_ i add one list with all porn website by admin web in the secction: 
** Adlist group management **

`https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list`

![listd](https://user-images.githubusercontent.com/179639/107450249-eb86de80-6b12-11eb-9319-b1ccda1c6e6c.png)

**Comment by dschaper** [comment]
Pi-hole is working, as you have shown. The domain is blocked. You likely have a non-Pi-hole DNS server configured for the Windows network interface. 

Since this is a configuration issue you should have used the link provided when you created the new issue:

![Screenshot_2021-02-09 pi-hole pi-hole](https://user-images.githubusercontent.com/2782850/107454569-1fa5d380-6b02-11eb-9174-9c19c89d45ca.png)

Visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by enlacee** [comment]
It just happened to ME, I don't really understand what is happening.

There are times when it works and there are times when it stops working.

I do not know what it could be . DNS is automatic configure it in the ROUTER

I suspect I do not say something that may be the mermorai but
is at 36% memory

Another thing that could be serious is that it is connected by wifi?

I want to find a reason but I can't find it. It will be a question of testing wiring, I do not lose

**Comment by dschaper** [comment]
Visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
