### ISSUE TITLE
Running Teleporter from the CLI does not include hostname

### ISSUE THREAD

**Issue by benemon** [pi-hole/pi-hole#4048]
### Versions

```
pi@green:~/pihole $ pihole version
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.2 (Latest: v5.3.2)
  FTL version is v5.6 (Latest: v5.6)
```
### Platform

- OS and version:  

- Platform:  
```
pi@green:~/pihole $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Expected behavior

running `pihole -a -t` results in a tar.gz containing the hostname of the current host, in the same manner that running teleporter from the web ui does.

### Actual behavior / bug

running `pihole -a -t` results in a tar.gz that does not contain the hostname of the current host. This is problematic for automating backups across several pihole instances.

### Steps to reproduce

```
pi@green:~/pihole $ pihole -a -t
pi@green:~/pihole $ ls -la
total 20
drwxr-xr-x 3 pi   pi   4096 Feb 11 11:27 .
drwxr-xr-x 7 pi   pi   4096 Feb 11 11:13 ..
-rw-r--r-- 1 root root 3002 Feb 11 11:27 pi-hole-teleporter_2021-02-11_11-27-27.tar.gz
```

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

If the command line tool cannot automatically add the hostname as per the web ui, perhaps the user could be allowed to provide a custom filename in place of the current default filename.

**Comment by dschaper** [comment]
> This is problematic for automating backups across several pihole instances.

How do you see this as problematic?

You should be setting the hostname on the node by what ever means you are creating the OS.

**Comment by PromoFaux** [comment]
> How do you see this as problematic?

I guess because the filename will always be `pi-hole-teleporter_YYYY-MM-DD_HH-mm-ss.tar.gz` it's more difficult to ascertain where it came from.

I guess we should update it to be consistent with the web interface

![image](https://user-images.githubusercontent.com/1998970/107684860-35023580-6c9b-11eb-909a-6dbb09169f4c.png)

![image](https://user-images.githubusercontent.com/1998970/107684835-2b78cd80-6c9b-11eb-8fc0-f9af283255b9.png)

**Comment by dschaper** [comment]
Oh, sorry. I thought the issue was that we were not backing up the hostname to be applied when the backup is restored.

**Comment by PromoFaux** [comment]
:) I did wonder

**Comment by benemon** [comment]
Sorry if the wording of my report caused any confusion @dschaper - @PromoFaux is quite correct in his assesment though. If you don't have the hostname in the filename of the generated tar.gz, it can get 'interesting' to trace the provenance of a particular file once you move it off the pihole host.

But yeah, if it could be consistent with the web interface that would be a great quality of life improvement!

**Comment by PromoFaux** [comment]
Fixed in https://github.com/pi-hole/pi-hole/pull/4049 (for next release)
