### ISSUE TITLE
`pihole -up` can't detect broken git repo to determinate subsystem not up-to-date

### ISSUE THREAD

**Issue by PeterDaveHello** [pi-hole/pi-hole#4050]
I upgrade one of my Pi-hole server today but found that the Web UI wasn't up-to-date, and I found that the update script can't handle the broken git repo properly, please take a look at the details below.

**I'd like to send a pull request to fix this issue, by adding an additional check to make sure the local repository isn't broken,** please let me know if it's acceptable ;)

### Versions

- Pi-hole: v5.2.4
- AdminLTE: v4.3.2
- FTL: v5.6

### Platform

- OS and version: Raspbian GNU/Linux 10 (buster)
- Platform: Raspberry Pi

### Expected behavior

`pihole -up` command upgrades all the Pi-hole subsystems

### Actual behavior / bug

The Web Interface wasn't up-to-date, but the update script thought it's up-to-date

```sh
raspberrypi ~ # pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v4.3.2 (Latest: v5.3.2)
  FTL version is v5.6 (Latest: v5.6)

raspberrypi ~ # pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
error: inflate: data stream error (incorrect data check)
fatal: packed object 8d59283d091e994f16b41e8cb45a373d4f97386b (stored in .git/objects/pack/pack-6d630d63739247a1e36b8d7b4c52eb89150839d2.pack) is corrupt                                                                                    
fatal: the remote end hung up unexpectedly
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
```

### Steps to reproduce

Run `pihole -up` on a system with broken Pi-hole web ui(AdminLTE) repository.

### Screenshots

![image](https://user-images.githubusercontent.com/3691490/107752175-588bb580-6d59-11eb-83a9-ecdbc8702c78.png)

### Additional context

I can confirmed that the repository is kind of broken with corrupt object:

```sh
raspberrypi ~ # git -C /var/www/html/admin fetch origin
error: inflate: data stream error (incorrect data check)
fatal: packed object 8d59283d091e994f16b41e8cb45a373d4f97386b (stored in .git/objects/pack/pack-6d630d63739247a1e36b8d7b4c52eb89150839d2.pack) is corrupt                                                                                    
fatal: the remote end hung up unexpectedly

raspberrypi ~ # echo $?
128
```

Git didn't exit with 0 but 128 in the situation, just the behavior wasn't expected and handled properly, so the update scripts think it's up-to-date:

https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/Scripts/update.sh#L36-L56

**Comment by PromoFaux** [comment]
Thanks for the report.  What would be your proposed solution to this? Part of me worries that if there is a corruption in the local git directory, then it is indicative of further corruptions throughout the rest of the filesystem... So perhaps a more graceful exit/error message would be more appropriate?

**Comment by PeterDaveHello** [comment]
Thanks for the prompt reply!

> Part of me worries that if there is a corruption in the local git directory, then it is indicative of further corruptions throughout the rest of the filesystem... 

That's true, though in this case, the filesystem doesn't seem to crash yet, "looks like" all the other things are still working, and a quick fsck said the filesystem is clean( I'll do a deeper check later), but still, besides the filesystem issue, those error usually needs more attention and manual works to be fixed, I don't think there is a trivial way to deal with various error like this, or even automatic it.

> So perhaps a more graceful exit/error message would be more appropriate?

So that's the same thing I'm thinking of, detect the error, and properly present it, even more, if we could know it's a repo broken(not sure yet, but maybe we can't), we should ask the normal users to check the filesystem, repair it if needed, and then reinstall Pi-hole, otherwise, we can still suggest the user to report the problem with the error message, and experienced users or power users can help find out what's going on.

What do you think?

**Comment by PromoFaux** [comment]
> So that's the same thing I'm thinking of, detect the error, and properly present it,

Sure, feel free to submit a PR, we don't bite :)

**Comment by PeterDaveHello** [comment]
Oops, I've been too busy to figure out the solution here, @dschaper as the bug does exist, can we reopen this issue? Thanks.

**Comment by dschaper** [comment]
We can reopen it and assign it to you for the PR, is that good?

**Comment by PeterDaveHello** [comment]
Not sure if closing it is to prevent too many opened issues, but if we leave it opened, anyone facing this problem will easily found that the bug was confirmed and not fixed yet.

**Comment by dschaper** [comment]
I honestly don't think it's a bug. There's corruption of the filesystem or the git repo. That's an OS issue. 

A nicer error display may be something to consider but hiding the actual error is counterproductive as users will need to be able to do a search on that error output in order to find a solution. There's not much Pi-hole can do once the underlying filesystem is corrupt. 

Promo's suggestion of submitting a PR is to make things nicer, it's not a fix for the broken operating system. 

Closing an issue doesn't make it go away, users can easily search closed issues. I'm still open to reopening if you want to be assigned the task of writing more output in a PR and need to link to this issue in the PR comments.

**Comment by yubiuser** [comment]
Wouldn't it be enough to add `set -e`?

**Comment by PeterDaveHello** [comment]
I know that the corruption is not Pi-hole's issue, as git found a problem and exit without status code 0, but Pi-hole still thinks it works with success, that's the point I think it's a bug.

`set -e` would just terminate immediately, not a good choice for end-users.

**Comment by yubiuser** [comment]
I think if git errors it should exit early and not proceed with the script. It already printed the git errors as seen in your example.
To make it nice, one could add an error trap advicing the user to contact the support.

**Comment by PeterDaveHello** [comment]
@yubiuser yes, git exited, but Pi-hole script continues, that's the point ;)
