### ISSUE TITLE
pihole -up fails when dhcpcd5 is held

### ISSUE THREAD

**Issue by jeand83** [pi-hole/pi-hole#4051]
### Versions
- Pi-hole:  5.2.4

### Platform
- OS and version:  Debian (buster/bullseye/etc) and probably Ubuntu (all)
- Platform:  all

### Expected behavior
pihole -up updates itself to the latest version. 

### Actual behavior / bug
  [i] Processing apt-get install(s) for: dhcpcd5, please wait...
----------------------------------------------------------------------------------------------------------------
E: Held packages were changed and -y was used without --allow-change-held-packages

  Unable to complete update, please contact Pi-hole Support
------------
And the update stops...

### Steps to reproduce
1) apt-mark hold dhcpcd5
2) pihole -up 

### Additional context
In Debian there are multiple packages which provide dhcp-functionality, which conflict with each other (and are marked as such). On my configuration only isc-dhcp works correct and dhcpcd5 is not working correct. (Because the server which runs pihole is also the central router in a complex VLAN-setup). When dhcpcd5 is installed everything breaks, therefore I 'hold'  the package (do not want it installed by accident). I do not use the dhcp functionality of pihole.

In pihole using dhcp is optional, therefore I feel that the 'apt-get install dhcpcd5' step in the installer and updater should also be optional. Now I break either dhcp or pihole... A switch --no-dhcp for the pihole updater/installer should work for me. 

Thanks in advance.

**Comment by dschaper** [comment]
`dhcpcd5` is for static IP addressing as that's the Raspbian way. It really doesn't have anything to do with `dhcp`.

**Comment by jeand83** [comment]
Thanks for the reply. You are most probably right about the actual purpose of dhcpcd5. My issue is still that the dependency on dhcpcd5 breaks my (debian) networking setup (hard, no connection to my headless server after updating pi-hole). However, the linked PR seems to fix my (and other people's) problems with regards to this issue. Thanks for the link and hard work!

**Comment by yubiuser** [comment]
Follow up PR
https://github.com/pi-hole/pi-hole/pull/4260

**Comment by yubiuser** [comment]
Fixed with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
