### ISSUE TITLE
Issues creating/using groups

### ISSUE THREAD

**Issue by jsholovitz** [pi-hole/pi-hole#4053]
### Versions
- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.2
- FTL:  v5.6

### Platform
- OS and version:  "Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"
- Platform:  Docker running on Raspberry Pi 3

### Expected behavior

1) User navigates to Groups page and adds group
2) User navigates to Clients page and adds client
3) User can associate new group with client

### Actual behavior / bug

1) Add group: As expected in UI - group added, green success message
2) Add client: As expected in UI - client added, green success message
3) Unable to associate client with new group - default group works fine, but new group will receive green success message in UI but remain not associated to client

### Steps to reproduce

Steps to reproduce the behavior: As above

## Debug Token

- URL:  https://tricorder.pi-hole.net/ttzmd3qor0

### Additional context

In the debug information, I see this:

*** [ DIAGNOSING ]: Groups
   id    enabled  name                                                date_added           date_modified        description                                       
   ----  -------  --------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   0           1  Default                                             2021-02-13 13:08:18  2021-02-13 13:08:18  The default group                                 
   2552        1  anudeepND/whitelist                                 2020-11-19 12:22:56  2021-02-13 13:10:10  https://github.com/anudeepND/whitelist            
   2552        1  CandyCrush                                          2021-02-13 13:14:15  2021-02-13 13:14:15  Whitelist for Candy Crush                         

is it possible that the same ID was assigned to two different groups? Or are the names unique and just truncated in the view?

EDIT: red herring. When I went into the Docker terminal and used sqlite3 to view the table, all looks OK:
'''
sqlite>` select * from "group";
0|1|Default|1613221698|1613221698|The default group
2552552551|1|anudeepND/whitelist|1605788576|1613221810|https://github.com/anudeepND/whitelist
2552552552|1|CandyCrush|1613222055|1613222055|Whitelist for Candy Crush
sqlite>
```

**Comment by yubiuser** [comment]
This might be to the third-party script you use to modify the database

https://github.com/anudeepND/whitelist/issues/187
