### ISSUE TITLE
DNS Service not Running after Reinstall but Pihole still blocking

### ISSUE THREAD

**Issue by rvs007** [pi-hole/pi-hole#4055]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  Homebridge Raspbian v1.0.17

- Platform:  Raspberry Pi 4B

### Expected behavior

Status with green "Active" on Dashboard.  

### Actual behavior / bug

Status with red "DNS service not running".  
"[x] DNS Service is NOT listening" when trying "pihole -r".

### Steps to reproduce

1. Go to 'Pihole dashboard'
2. Status shows "DNS service not running" with red circle.
2. Click on 'Enable' on left hand side main navigation menu
3. Pihole status will change to "Active" with green circle.
4. But upon refresh of the page, the status reverts back to "DNS service not running".

## Debug Token

- URL:  https://tricorder.pi-hole.net/of2vpvyco4

### Screenshots

![Screenshot 2021-02-16 193922](https://user-images.githubusercontent.com/31269461/108139750-bfc5a480-708e-11eb-9bf5-7817a3062553.png)

### Additional context

Pihole is installed on same Rasbpi4 as Homebridge.  A few days ago, Homebridge started giving me problems which I had to restore a backup to resolve.  With the Homebridge problem, I was no longer able to access the Admin UI of Pihole as well.  After restoring my Homebridge configuration, I got the Homebridge server back up and running, but the Pihole web UI was still inaccessible from my browser.  So I decided to run 'hb-config' and rerun the pihole installer again.  I picked 'repair' and it went through the process of repairing the existing pihole installation.  I was able to access the Pihole web ui again, but the "DNS Service not running" error appeared, even though the total queries and "Queries Blocked" counters are continually updated (which to me means Pihole is working at least.)  However, I cannot seem to get the DNS service to run again.  I've tried:

* Repairing the existing pihole installation.
* Reconfiguring a new installation.
* Removing pihole altogether and installing a new pihole installation.
* typing 'pihole enable' in SSH session (pihole would enable for an instance but revert back to "DNS service not running" again immediately.)

**Comment by dschaper** [comment]
Is HomeBridge Raspbian different than stock Raspbian?

What is `hb-config` and how is that related to Pi-hole?

This looks like a problem with HomeBridge and not with Pi-hole, it's not a platform we support.

**Comment by PaulVerhoeven1** [comment]
I got the same problem with  v5.2.4. I switched back to an older version and that works like a charm

**Comment by mschmt** [comment]
Yes, HomeBridge installs an additional apt Repository

Dan Schaper <notifications@github.com> schrieb am Mi., 17. Feb. 2021, 05:55:

**Comment by rvs007** [comment]
> Is HomeBridge Raspbian different than stock Raspbian?
> 
> What is `hb-config` and how is that related to Pi-hole?
> 
> This looks like a problem with HomeBridge and not with Pi-hole, it's not a platform we support.

The platform is Raspbian Lite (Raspbian GNU/Linux Buster (10)) v1.0.17 which Pihole supports.  `hb-config` is just a CLI command that brings up a Configuration Tool for Homebridge Raspbian to manage and configure homebridge and install extra packages like Pi-hole.

**Comment by rvs007** [comment]
> I got the same problem with v5.2.4. I switched back to an older version and that works like a charm

Is there a step-by-step tutorial on how to downgrade to a previous version of Pihole?

**Comment by PaulVerhoeven1** [comment]
> > I got the same problem with v5.2.4. I switched back to an older version and that works like a charm
> 
> Is there a step-by-step tutorial on how to downgrade to a previous version of Pihole?

I don't know, i run Pi-Hole in a docker container where i only needed to change te image in the docker-compose file!

**Comment by dschaper** [comment]
If `hb-config` installs Pi-hole then a problem with installing Pi-hole should be addressed with whomever wrote `hb-config`. 

It's not supported by us.

**Comment by rvs007** [comment]
> If `hb-config` installs Pi-hole then a problem with installing Pi-hole should be addressed with whomever wrote `hb-config`.
> 
> It's not supported by us.

I had pihole running perfectly for months until this problem started, so I don't think it's related to the fact that Pihole was installed using hb-config.  Does the debug log show any problems?

**Comment by dschaper** [comment]
It's not complete, it's missing the port assignment, which would indicate that this OS has modifications that are not supported.

**Comment by rvs007** [comment]
After researching on the net and coming up empty, I decided to reflash the microSD card for the Rpi4 with the homebridge raspian image and install Pihole from scratch.  With the fresh homebridge install, everything worked fine and the DNS service problem is gone.

**Comment by fue36** [comment]
I experienced this issue to after upgrade as well, don't use Homebridge however. Solution was to install lsof

```
$ pihole status
/usr/local/bin/pihole: line 284: lsof: command not found
  [✗] DNS service is NOT listening

```
`sudo apt install lsof`

```
$ pihole status
  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✗] UDP (IPv6)
     [✗] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

**Comment by svenjacobs** [comment]
I have the same issue. The web interface reports "DNS service not running" however Pihole is blocking ads. When I run `pihole status` I get

```
lsof� WARNING: unsupported fopmat: /proc/net/raw
lsof� WARNING: unsupported fopmat: /proc/net/netlink
lsof� WARNING: unsupported fopmat: /proc/net/packet
lsof� WARNING: unsupported fopmat: /proc/net/unix
lsof� WARNING: unsupported fopmat: /proc/net/raw6
lsof� WARNING: unsupported fopmat: /proc/net/tcp6
lsof� WARNING: unsupported fopmat: /proc/net/udp6
lsof� WARNING: unsupported fopmat: /proc/net/udplite6
lsof� WARNING: unsupported fopmat: /proc/net/tcp
lsof� WARNING: unsupported fopmat: /proc/net/udp
lsof� WARNING: unsupported fopmat: /proc/net/udplite
lsof� WARNING: unsupported fopmat: /proc/net/icmp
  [✗] DNS service is NOT listening
```

Unfortunately I don't know when this started to happen.

```
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)
```

running on [DietPi](https://dietpi.com/) 7.4.2.

**Comment by dschaper** [comment]
If the output is truly misspelled as `fopmat` instead of `format` and there is that unicode symbol then it looks like you have some filesystem corruption.

**Comment by svenjacobs** [comment]
> If the output is truly misspelled as `fopmat` instead of `format` and there is that unicode symbol then it looks like you have some filesystem corruption.

Thanks for the hint. I thought that the output was weird but didn't associate it with possible filesystem corruption. I ran `e2fsck` and reinstalled `lsof` and now it's working again 👍🏼

**Comment by daNutzzzzz** [comment]
it broke for me too, reverting to 5.6 has it working fine again.

**Comment by yubiuser** [comment]
Will be fixed by
https://github.com/pi-hole/pi-hole/pull/4518

**Comment by YOUSSEF2020-app** [comment]
![Screenshot 2023-02-19 152947](https://user-images.githubusercontent.com/62940617/219956340-e33019e7-1923-45a3-8a9a-decdc537517d.png)

I have a problem that I don't know how to solve this problem. Is there anyone here to help him solve this problem?

**Comment by rdwebdesign** [comment]
This PHP error only means FTL is not running, but this doesn't tell why.

This issue was closed in 2021 and there is a big change you have a different problem.

Please open a new issue, generate a Debug Log and include the Token to the new issue.

**Comment by Ilyes-CH** [comment]
Run pihole -r to reconfigure check also with systemctl status pihole-FTL.service,  verify the logs using tail -f /var/log/pihole-FTL.log, you can update pihole packages maybe this could fix the issue using pihole -r ... make sure to verify if there is a service conflict on port 53 using sudo netstat -tuln | grep :53... what fixed my issue after following these steps is reconfiguring pihole
