### ISSUE TITLE
"pihole -up" uses hard coded DNS server when requesting ns1.pi-hole.net 

### ISSUE THREAD

**Issue by panopticon36** [pi-hole/pi-hole#4056]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"; NAME="Raspbian GNU/Linux"; VERSION_ID="10"

- Platform:  Raspberry Pi

### Expected behavior

I expect the `pihole -up` script to honor DNS specified by DHCP lease or `dhcpcd.conf`.

### Actual behavior / bug

When running `pihole -up` the FTL portion of the script attempts to resolve ns1.pi-hole.net using a hard coded DNS server "8.8.8.8" and fails on networks were rogue DNS requests are blocked.

### Steps to reproduce

1. Setup PiHole behind a gateway that denies rogue DNS requests.
2. Run `pihole -up`
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/3u15utkzdt

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
This is intended and not a bug.

**Comment by dschaper** [comment]
If you do as I told you on Discourse and spend a few minutes searching then you'll find all the answers you'll need.

**Comment by dschaper** [comment]
>  resolve ns1.pi-hole.net using a hard coded DNS server "8.8.8.8" 
No, it really doesn't.

**Comment by panopticon36** [comment]
> > resolve ns1.pi-hole.net using a hard coded DNS server "8.8.8.8"
> 
> No, it really doesn't.

Judging from logs, it really does. ;)

**Comment by dschaper** [comment]
Then that's what you have set up.

Here's the exact code:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L192

No mention or use of 8.8.8.8 anywhere. (It is used to find the default route out of the network but it's not used to query or send ANY data.)

**Comment by dschaper** [comment]
For those playing at home:

```plain
cmdResult="$(dig +short -t txt ${remote_os_domain} @ns1.pi-hole.net 2>&1; echo $?)"
```

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/pihole-up-uses-a-hard-coded-dns/44496

**Comment by panopticon36** [comment]
> Then that's what you have set up.
> 
> Here's the exact code:
> 
> https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L192
> 
> No mention or use of 8.8.8.8 anywhere. (It is used to find the default route out of the network but it's not used to query or send ANY data.)

Thanks for the code link. It does on lines 696 and 699 at first glance.

**Comment by dschaper** [comment]
Then we are looking at different files:

Line 696: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L696

Line 699: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L699

![Screenshot_2021-02-17 pi-hole pi-hole](https://user-images.githubusercontent.com/2782850/108244899-8d568e80-7104-11eb-8f00-463927fcadb7.png)

**Comment by dschaper** [comment]
8.8.8.8 is used to find the default route, as I mentioned. The command doesn't send any data to the IP address, it's a single lookup to the devices network routing table:

```plain
    # Find IP used to route to outside world by checking the the route to Google's public DNS server
    route=$(ip route get 8.8.8.8)
```

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L652

**Comment by dschaper** [comment]
Is your `/etc/resolv.conf` set to use 8.8.8.8?

**Comment by panopticon36** [comment]
> Then we are looking at different files:
> 
> Line 696: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L696
> 
> Line 699: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L699
> 
> ![Screenshot_2021-02-17 pi-hole pi-hole](https://user-images.githubusercontent.com/2782850/108244899-8d568e80-7104-11eb-8f00-463927fcadb7.png)

My bad there, I had copied the code into an IDE that had some other text at the top. I meant lines 659 and 662 but I also see what you mean by being a single lookup. I'm going to give the code a closer look when I get a chance. Thank you.

**Comment by panopticon36** [comment]
> Is your `/etc/resolv.conf` set to use 8.8.8.8?

pi@raspberrypi:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 192.168.1.1

**Comment by panopticon36** [comment]
> Is your `/etc/resolv.conf` set to use 8.8.8.8?

```
pi@raspberrypi:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 192.168.1.1
```

**Comment by dschaper** [comment]
What evidence is leading you to make the very serious claim that we hard code in 8.8.8.8 for every installation?

**Comment by panopticon36** [comment]
> What evidence is leading you to make the very serious claim that we hard code in 8.8.8.8 for every installation?

Its what I saw in my firewall (which I have been referring to as my gateway) logs at the time of `pihole -up` or `pihole -r`.
I can share portions of that log with you later (I would want to filter the logs a bit before sharing anything from my firewall).

For context: My firewall is IPFire using DNS over TLS pointed only to 1.1.1.1 for upstream DNS.

**Comment by dschaper** [comment]
Have you run `pihole -d` at any time around the same time as `pihole -up` or `pihole -r`?

**Comment by dschaper** [comment]
>  I meant lines 659 and 662 but I also see what you mean by being a single lookup.

To clarify, there is no DNS lookup to 8.8.8.8 there, it's a `ip route get` query which doesn't leave the device, it purely looks at the devices existing routing table.

**Comment by panopticon36** [comment]
> Have you run `pihole -d` at any time around the same time as `pihole -up` or `pihole -r`?

No but I'd be happy to.
I have temporarily made and except for pihole to punch through the firewall but I can dissable that and run pihole -d again. The debug token in this post was ran while the exception was in place. Sorry for that. This is my fault.

If I had to guess there is an issue with the way dig is implemented on line 192. in `dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net` we are asking dig to lookup a domain from a DNS server specified by name, so dig must be making a judgement on its own about where to reference ns1.pi-hole.net before looking up versions.pi-hole.net. Just a thought. I'll get back to you with a better `pihole -d`.

**Comment by dschaper** [comment]
No need for `pihole -d` really.

And yes, there is a need for the device to determine what IP address ns1.pi-hole.net is at, but that's on the device to decide. There is no hardcode 8.8.8.8 to determine that as you have claimed.

**Comment by dschaper** [comment]
What you are seeing, and what you may have confused with the installer, is the debug process. 

The debugger will try to query 8.8.8.8 as a check to see if the Pi-hole device can resolve a domain with a globally accessible DNS server. It makes little sense to use a local server on the same network as the Pi-hole as a check to see if the Pi-hole can actually resolve domains. It's a check to see if just the local resolution is broken or of the entire configuration is broken.

**Comment by dschaper** [comment]
From the debug logs (which you should have looked over)

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] strack.cricketworldcupstore.com is 0.0.0.0 via localhost (127.0.0.1)
[✓] strack.cricketworldcupstore.com is 0.0.0.0 via Pi-hole (192.168.1.18)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)
```

**Comment by panopticon36** [comment]
Excuse my lack of knowledge for sh specifically, but could we have something like this on line 192 instead?
        cmdResult="$(dig +short -t txt ${remote_os_domain} @{$get_this_from"/etc/resolv.conf"} 2>&1; echo $?)"

**Comment by dschaper** [comment]
No, if you had done what I asked and searched for this you would find that the `@ns1.pi-hole.net` is specifically chosen. One, to prevent someone from changing the TXT record locally as a bypass and two, because AD DNS servers munge DNS cookies so they can not be used in the check.

**Comment by dschaper** [comment]
Honestly, this is all a bunch of nonsense when you were provided the exact command to use to bypass this check. You just need to use what the developers have told you is the solution.

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/issues/3595

**Comment by panopticon36** [comment]
I ran `dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net` with the exceptions on my firewall disabled and got this output.
```
pi@raspberrypi:~ $ dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
dig: couldn't get address for 'ns1.pi-hole.net': failure
```

To me this means that dig is in-fact making its own judgement about how to look up ns1.pi-hole.net before looking up version.pi-hole.net and apparently deciding to use 8.8.8.8 for this.

I'm slow, so please take me through this, but I'm having trouble with your reasoning here.
> No, if you had done what I asked and searched for this you would find that the @ns1.pi-hole.net is specifically chosen. One, to prevent someone from changing the TXT record locally as a bypass and two, because AD DNS servers munge DNS cookies so they can not be used in the check.

In response to "One," The work around for this bug is to bypass it anyway from command line, so who cares if I'm bypassing the check via command line or TXT record?
and in response to "two" Yeah the AD DNS server is munging but to reference versions.pi-hole.net we must first reference ns1.pi-hole.net which is just going to look to 8.8.8.8 so what's the difference?

**Comment by dschaper** [comment]
> and apparently deciding to use 8.8.8.8 for this.

Then you have configured something somewhere to chose this IP address. 

You have all the information you need to answer your questions. We're done here.
