### ISSUE TITLE
PiHole cant get https://mirror1.malwaredomains.com/files/justdomains

### ISSUE THREAD

**Issue by tux-box** [pi-hole/pi-hole#4057]
### Versions

- Pi-hole:  version is v5.2.2 (Latest: v5.2.4)
- AdminLTE:  version is v5.2.2 (Latest: v5.3.2)
- FTL:  version is v5.3.4 (Latest: v5.6)

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._
When clicking update gravity, with malware domains enabled a success when updating malware domains.

### Actual behavior / bug

_A clear and concise description of what the bug is._
  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✗] Status: Not found
  [✗] List download failed: no cached list available

### Steps to reproduce

Login.
expand tools
click gravity
click update.
notice that the error is happening.

Further: go to "https://mirror1.malwaredomains.com/files/justdomains" and notice the 404 error.

Further: per https://riskanalytics.com/community/
"We have merged AutoShun and Malware Domains, and have integrated those technologies into ShadowNet.  Through ShadowNet we are able to identify the latest threat intel gathered from around the globe, share learnings and best practices from our network of clients and partners and continually build those learnings into our products, resulting in the best, most powerful threat intel for your organization.
As of November 30th, 2020, both AutoShun and Malware Domains feeds will be shut off, and subscribers will no longer receive intel from those sources. 

We will continue to make a free, non-commercial version of our threat intel, ShadowNet, while the enhanced full-threat intel feed will be licensed to our commercial partners."

## Debug Token

- URL:  
- `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
[?] Would you like to upload the log? [y/N] y
-bash: $'\E[H\E[2J\E[3JThis': command not found

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Please search to find the multiple other issues that have reported this.

It's known, the list has been removed and you'll need to remove it from your setup.

**Comment by tux-box** [comment]
adding info for others. 
see "https://github.com/pi-hole/pi-hole/issues/3925"
