### ISSUE TITLE
php8.0-json install error with Latest Pihole update.

### ISSUE THREAD

**Issue by littleneutrino** [pi-hole/pi-hole#4059]
### Versions
- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.6

### Platform
- OS and version:  Raspberry Pi OS
- Platform:  Raspberry PI

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

When running Pihole -up to install Todays Updates, I experience an error that states that php8.0-json has no installation candidate

### Steps to reproduce

1. Run pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/qfan7n5a89

### Screenshots
https://ibb.co/2c9MqTK

**Comment by dschaper** [comment]
php 8 is not supported by Pi-hole. It's also not supported by Rasbpian 10 (Buster.)

If you had searched, you would have seen #4508  which is the exact same thing

**Comment by francoism90** [comment]
@dschaper Is an upgrade to PHP 8 planned?

**Comment by dschaper** [comment]
No, it's not. We'd rather spend the effort removing the need to be dependent upon the distributions PHP version. (Which is 7 for every distribution we support now.)

**Comment by francoism90** [comment]
@dschaper I can understand not support PHP 8 yet, however if I read your comment correctly pi-hole isn't going to upgrade at all to that version?

**Comment by dschaper** [comment]
Maybe, maybe not.

**Comment by dschaper** [comment]
If the question is, "Will you remove the `php8.0-json` package as a dependency", then that's the better question to ask. And that is likely.
