### ISSUE TITLE
Pihole on rpi: apt-get upgrade failed to create hard link in /boot

### ISSUE THREAD

**Issue by sigg3** [pi-hole/pi-hole#4061]
### Versions
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

### Platform

- OS and version:  Linux pi 4.9.0-6-rpi2 #1 SMP Raspbian 4.9.82-1+deb9u3+rpi2 (2018-11-09) armv7l GNU/Linux

- Platform:  Pi

### Expected behavior

_Can run sudo apt-get update && sudo apt-get upgrade_

### Actual behavior / bug

_Sub-process /usr/bin/dpkg returned an error code (1)_:

`ln: failed to create hard link '/boot/initrd.img-4.9.0-6-rpi.dpkg-bak' => '/boot/initrd.img-4.9.0-6-rpi': Operation not permitted
`

### Steps to reproduce

1. Install Pihole to SD card
2. Run sudo apt-get update && sudo apt-get upgrade
3. ???
4. Profit!

## Debug Token

- URL:  https://tricorder.pi-hole.net/37sa51fnud

### Additional context

_Coffee mug is empty. Probably not relevant._

**Comment by dschaper** [comment]
That's not really something we can help with. That's a problem with the operating system.
