### ISSUE TITLE
Slow Network.

### ISSUE THREAD

**Issue by ashishsantikari** [pi-hole/pi-hole#4063]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  DietPi v6.34.3

- Platform:  Raspberry Pi 4 Model B aarch64

### Expected behavior
I am expecting to make network faster by following the guide here
https://discourse.pi-hole.net/t/why-do-some-sites-take-forever-to-load-when-using-pi-hole-for-versions-v4-0/3654

### Actual behavior / bug
iptables command not found

### Steps to reproduce

1. Go to terminal/bash
2. type `iptables -A INPUT -p tcp --destination-port 443 -j REJECT --reject-with tcp-reset`
3. -bash: iptables: command not found

## Debug Token

- URL:  https://tricorder.pi-hole.net/ad9g8zp9w2

**Comment by yubiuser** [comment]
Why do some sites take forever to load when using Pi-hole? **(for versions < v4.0)***

You are using version >5

**Comment by dschaper** [comment]
>     3\. -bash: iptables: command not found

Then you'll need to install it.
