### ISSUE TITLE
 Ubuntu 16.X and 18.X PHP 8.0 update failure

### ISSUE THREAD

**Issue by Guyverix** [pi-hole/pi-hole#4064]
### Versions

chubbard@infra01:~$ pihole -v
  Current Pi-hole version is v5.2.4.
  Current AdminLTE version is v5.4.
  Current FTL version is v5.3.4.

### Platform

- OS and version:  Ubuntu 16.04 AND Ubuntu 18.04

- Platform:  x86 (KVM)

### Expected behavior

Update to update the packages as it has been.

### Actual behavior / bug

Attempted to install PHP 8.0 and supporting packages.

### Steps to reproduce

1. curl -sSL https://install.pi-hole.net | bash
2. Choose update
3. read output

## Debug Token

- URL:  

### Screenshots
`  [✓] Checking for php8.0-common
  [✓] Checking for php8.0-cgi
  [✓] Checking for php8.0-sqlite3
  [i] Checking for php8.0-xml (will be installed)
  [i] Checking for php8.0-json (will be installed)
  [✓] Checking for php8.0-intl
  [i] Processing apt-get install(s) for: php8.0-xml php8.0-json, please wait...
--------------------------------------------------------------------------------
E: Package 'php8.0-json' has no installation candidate
`

### Additional context

I installed the PPA and got PHP8 installed by hand.  the installer says it cannot find php8.0-json.  the php8.0-xml DOES exist, and I have installed manually at this time.

 According to PHP, json comes default and is not a separate package:
[https://php.watch/articles/php-8.0-installation-update-guide-debian-ubuntu](url)

**Comment by jfb-pihole** [comment]
I don't believe php 8 is in the Ubuntu 16 packages.  Is this something you have upgraded after initial install?

**Comment by Guyverix** [comment]
It is not.  I installed a PPA to get PHP8 in Ubuntu 18.04.  It did not have it either.  Once I had the PPA and did a apt update, PiHole was able to get further along in the update/upgrade process.  However last piece is the json package which from what I can tell does not exist in PHP 8.0

**Comment by Guyverix** [comment]
Also I have kicked it a couple of times now, and the application IS working, and blocking so basically I think the php8.0-json just needs to be a non-fatal error and it will be all good.

**Comment by jfb-pihole** [comment]
The Pi-hole updater (or installer) will not continue until apt update completes successfully.  If apt update does not complete, the installer stops at that step.  You will need to fix the problem outside of Pi-hole, then re-run the Pi-hole update.

**Comment by Guyverix** [comment]
It will never suceed.  This is coded into the updater:
`  PIHOLE_WEB_DEPS=(lighttpd "${phpVer}-common" "${phpVer}-cgi" "${phpVer}-${phpSqlite}" "${phpVer}-xml" "${phpVer}-json" "${phpVer}-intl")`
Thats pulled directly from [https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh](url)

**Comment by Guyverix** [comment]
Only thing I can think of, is perhaps when it updated things like lighttpd perhaps THAT was saying to upgrade to PHP 8.. I am still digging since I am sure this is going to affect others as they update.

**Comment by dschaper** [comment]
There's nothing in the installer code that would install `php-8`. It's not in any of the distro repositories so there's no way for us to request it. We don't add any additional repositories that would even have `php-8`.

**Comment by Guyverix** [comment]
Then I will officially cry and figure out what I did, since something started saying use PHP 8, and affected the updater.  I will close this out since it is not related to the updater or likely PiHole as well.. 

Thank you for the assist on this

**Comment by dschaper** [comment]
What hypervisor are you using? How did you create the OS? Are you using the ISO or are you using a template or qcow image?

**Comment by Guyverix** [comment]
Qemu/KVM  I built the original Ubutnu 16 from the ISO installer.  Today to troubleshoot I did a do-release-upgrade to 18 assuming something borked since Ubutnu 16 is basically EOL.

**Comment by dschaper** [comment]
Something in your image or other packages is pulling in another repository then. 

Bionic is php 7.2

https://packages.ubuntu.com/bionic/php

The installer's variable `{phpVer}` is determined by: https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L317

Basically we see if `php` binary exists and then call it for the version. That all will be displayed and is above the part you pasted in.

It currently checks for `php5` or `php` and version 7.0 or greater. The assumption was that you'd only have php5 or php7 since those are the only official versions in any distro repo. We could code in that it HAS to be a sub-version of 7 and if it's 8 then hard stop since that's going to be a modified operating system. We'll already need to modify for version 8 since, as you noted, one of the php modules no longer exists in php 8.
