### ISSUE TITLE
When using multiple Groups, Pi-hole ignores all blocklists if the "Default" group is empty

### ISSUE THREAD

**Issue by morrisalex** [pi-hole/pi-hole#4066]
### Versions
- Pi-hole version is v5.2.4 (Latest: v5.2.4)
- AdminLTE version is v5.4 (Latest: v5.4)
- FTL version is v5.7 (Latest: v5.7)

### Platform
- OS and version:  Ubuntu 20.04.2 LTS
- Platform:  Raspberry Pi 4B

### Expected behavior

Pi-hole should return any of NULL, NODATA, or NXDOMAIN to a query (depending on BLOCKINGMODE), instead of the real public IP address.

### Actual behavior / bug

Pi-hole returns the real public IP address to a query, ignoring all of its blocklists.

When using Pi-hole's Groups feature, if at least one blocklist is assigned to the "Default" group, then Pi-hole behaves correctly and returns the intended response to the DNS query.

However, if all blocklists are assigned to other named groups, and the "Default" group is empty, then all blocklists are ignored and Pi-hole returns the real public IP address instead of the desired NULL/NODATA/NXDOMAIN response.

### Steps to reproduce

1. Create multiple Groups and set them to "Enabled"
2. Assign blocklists to those Groups, and leave the Default group empty
3. Query Pi-hole for an entry which should be blocked
4. Observe that Pi-hole returns the real public IP address
5. Think about the problem, and wonder if Pi-hole might have hit some sort of upper limit, or if the hardware has hit some sort of memory limit due to too many blocklist entries (this problem was originally seen under Raspberry Pi OS on a 3B+, before testing again under Ubuntu on a 4B)
6. Reinstall Pi-hole from scratch, using only the single supplied Steven Black blocklist
7. Create a new Group and set it to "Enabled"
8. Assign the single blocklist to that new Group, and remove it from the Default group
9. Query Pi-hole for an entry which should be blocked
10. Observe that Pi-hole returns the real public IP address
11. Move the blocklist back to the Default group
12. Try the query again
13. Observe that Pi-hole returns the desired non-response
14. Spend several minutes moving the blocklist in and out of the Default group and repeating the above steps, to confirm that the behaviour is repeatable
15. Add some extra blocklists and Groups, and repeat the above steps, to confirm that the behaviour is repeatable with multiple blocklists and Groups and not just one
16. Sign into GitHub to report an issue

## Debug Token

- URL:  https://tricorder.pi-hole.net/yulfddd9p5

### Screenshots

N/A

### Additional context

N/A

**Comment by yubiuser** [comment]
If you keep the default group empty, clients that are only member of that group (e.g. clients that have not been configured explicitly) have no adlists assigned to them and no filtering will apply.

I think you misunderstood the configuration of the group management. See here for how it works
https://docs.pi-hole.net/database/gravity/example/

**Comment by morrisalex** [comment]
Chalk this one up to boneheaded user error. Thank you to @yubiuser for pointing me in the right direction.
