### ISSUE TITLE
Can't update using pihole -up

### ISSUE THREAD

**Issue by V8A-yes** [pi-hole/pi-hole#4068]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.6

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster) amrv71

- Platform:  Raspberry Pi 4B+

### Expected behavior

I expected it just to update pihole fine and also update my adlist on its way

### Actual behavior / bug

I don't really know what the actual bug is but it just says that my /etc/.pihole is not able to be reset and then it stops the update

### Steps to reproduce

I don't really know how to reproduce that bug but it just happened from day to other

## Debug Token

- URL:  https://tricorder.pi-hole.net/wuo654vtgv

### Screenshots

https://watchdog.api-hypixel.net/5267466.png
(dont mind the url its just my image uploader)

### Additional context

I don't have any additional context except the command i used to update was `pihole -up && pihole -g`

**Comment by jfb-pihole** [comment]
"the command i used to update was pihole -up && pihole -g"

You don't need to add pihole -g after the update command.  The updater already updates gravity at the end of the update process.

You can run the following commands to check your local git repository:

`cd /etc/.pihole`
`sudo git status`

If you find problems, you can recreate the entire local repository with these commands:

```
cd /
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
```

**Comment by V8A-yes** [comment]
@jfb-pihole I tried deleting the .pihole folder to redownload it but it says that i can't delete it because "/etc/.pihole/.github needs Structure needs cleaning"

https://minesense.club/b5d7c3a.png

**Comment by Biebsi** [comment]
The same behaviour on my raspi with this versions.

After allI installed the update using this command:
`PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r`

It worked overall.
But my Web-Admin is broken.
The `AdminLTE.min.css` is missing and the GUI can't be used.

**Comment by dschaper** [comment]
> I tried deleting the .pihole folder to redownload it but it says that i can't delete it because "/etc/.pihole/.github needs Structure needs cleaning"

What command did you use to try to delete the folder?

**Comment by dschaper** [comment]
> The same behaviour on my raspi with this versions.

No, you have a different issue. Open a new issue ticket. I'll hide these comments as off-topic.

**Comment by V8A-yes** [comment]
well it seems like accidently fucking up my raspbian and reinstalling it and plus pihole fixed it worked for me nicely so i guess i can close this issue since i dont have it lmao
