### ISSUE TITLE
Blacklist entries with hyphen

### ISSUE THREAD

**Issue by tylersand** [pi-hole/pi-hole#4069]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi

### Expected behavior

When adding an "exact match" black list entry with a hyphen in the URL, such as g2insights-cdn.azureedge.net, it would be expected that g2insights-cdn.azureedge.net would be blacklisted

### Actual behavior / bug

However, the domain still resolves.  If you change to a Regex blacklist type, then it is blocked.

### Steps to reproduce

1. Add an "exact match" black list entry with a hyphen in the URL, such as g2insights-cdn.azureedge.net
2. Attempt to resolve that domain

## Debug Token

- URL:  https://tricorder.pi-hole.net/5d6tvp2q78

### Screenshots
![image](https://user-images.githubusercontent.com/16942321/109681327-5bedb200-7b4b-11eb-9c15-45fd3590caf5.png)

![image](https://user-images.githubusercontent.com/16942321/109683623-86406f00-7b4d-11eb-8f16-06687a14d924.png)

### Additional context
Running command "pihole -b -l" the domain appears:

pi@raspberrypi1:~ $ pihole -b -l
Displaying blacklist:
  1: connext-cdn.azureedge.net (enabled, last modified Tue, 02 Mar 2021 11:46:14 -0500)

**Comment by jfb-pihole** [comment]
I cannot duplicate this behavior, so I don't think it is a bug.  Prior to adding this domain to the blacklist, it resolves as follows:

```
dig connext-cdn.azureedge.net

;; ANSWER SECTION:
connext-cdn.azureedge.net. 3600	IN	CNAME	connext-cdn.ec.azureedge.net.
connext-cdn.ec.azureedge.net. 3600 IN	CNAME	scdn1.wpc.45235.thetacdn.net.
scdn1.wpc.45235.thetacdn.net. 3600 IN	CNAME	sni1gl.wpc.thetacdn.net.
sni1gl.wpc.thetacdn.net. 3600	IN	A	152.195.19.97
```
Then, add to the blacklist as an exact entry:

```
** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
   id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment                                           
   ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
  315    1          1  0             connext-cdn.azureedge.net                                                                             2021-03-02 10:50:04  2021-03-02 10:50:04      
```                                              

```
 pihole -q connext-cdn.azureedge.net
 Match found in exact blacklist
   connext-cdn.azureedge.net
```
Then repeat the dig:
```
dig connext-cdn.azureedge.net +short
0.0.0.0
```
Since the domain was not previously blacklisted and clients were able to load it, a client may still have this domain in cache from before it was blacklisted.

**Comment by tylersand** [comment]
Thanks for testing.  I tried to reproduce your steps but for me, the address still resolves when it is an exact match. 

```
dig connext-cdn.azureedge.net +short
connext-cdn.ec.azureedge.net.
scdn1.wpc.45235.thetacdn.net.
sni1gl.wpc.thetacdn.net.
152.195.19.97

```

**Comment by tylersand** [comment]
Thanks for testing.  I ran the -q and see my issue.  There is a conflicting whitelist entry, which must be getting applied before the blacklist entry.

```
pihole -q connext-cdn.azureedge.net
 Match found in exact blacklist
   connext-cdn.azureedge.net
 Match found in regex whitelist
   (\.|^)azureedge\.net$

```

**Comment by jfb-pihole** [comment]
Yes, whitelist takes precedence over blacklist.

**Comment by tylersand** [comment]
Does regex blacklist take precedence over direct whitelist?  Just wondering why it worked when I switched my blacklist entry to regex, as the regex blacklist entry was in place in both scenarios.  Thanks again.

**Comment by jfb-pihole** [comment]
The precedence is as follows.  At the first match, the process stops and no further checks are made.

- Exact Whitelist
- Regex Whitelist
- Exact Blacklist
- Blocklist domains (AKA gravity)
- Regex Blacklist
