### ISSUE TITLE
DNS resolution sometimes not working after update

### ISSUE THREAD

**Issue by Peronia** [pi-hole/pi-hole#4071]
### Versions (before update)
- Pi-hole:  5.2.3
- AdminLTE:  5.3
- FTL:  5.4

### Platform
- OS and version:  Debian 10
- Platform:  LXC-Container

### Expected behavior

The Pihole should update and working (maybe after a reboot)

### Actual behavior / bug

After `curl -sSL https://install.pi-hole.net | bash` was successful and a restart, some DNS queries get not resolved

### Steps to reproduce

1. Update the pihole

## Debug Token

- URL:  https://tricorder.pi-hole.net/tk3mrxhqwr

**Comment by dschaper** [comment]
Did you update or did you reinstall? `curl -sSL https://install.pi-hole.net | bash` is not the update process, that's the installer (and reinstall/repair but with different command line flags.)

**Comment by Peronia** [comment]
Well it ask me for an update, I choose that option (I update all the time on this way).

**Comment by dschaper** [comment]
> Well it ask me for an update, I choose that option (I update all the time on this way).

Don't. Use `pihole -up` like we've written the code to use.

And check your networking, you have some IP address issues:

```plain
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.230.6/24 matches the IP found in /etc/pihole/setupVars.conf
   192.168.230.100/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
```

**Comment by Peronia** [comment]
Yeah I see that, but I saw this too:
`As long as one of them is green, and it matches what is in /etc/pihole/setupVars.conf, there is no need for concern.`
I don't have an idea where pihole gets this shitty ip...

**Comment by dschaper** [comment]
Might be related to why things don't work when you use the wrong update process with an IP address you don't know how it exists.

**Comment by Peronia** [comment]
I know that the address don't exist, but I don't know how pihole get it.

**Comment by dschaper** [comment]
`ip address list` on the terminal command line. 

The web interface is just showing what you have set in `/etc/pihole/setupVars.conf`.

IP addressing is handled by the operating system. You may have additional configuration lines in `/etc/dhcpcd.conf`.

**Comment by Peronia** [comment]
I set up a new pihole, the ip got new addressed after each reboot.
I'll close this here because I can no longer update.
But please remove the updateoption from `curl -sSL https://install.pi-hole.net | bash` when its not longer supported.
