### ISSUE TITLE
Improvement: start DHCP only if needed

### ISSUE THREAD

**Issue by Peronia** [pi-hole/pi-hole#4072]
### Versions
- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform
- OS and version:  Debian 10
- Platform:  LXC-Container

### Actual behavior

Your installskript installs DHCP even if it not in use. Thats not perfect but ok.
But in every case you start the DHCP service and set it to start with every reboot, even if it is not used by the user.
This is not fine, it can lead into misconfiguration.
E.g. if the host (here a proxmox) overrides the `resolv.conf` and after that the file get overridden by the running DHCP.

### Expected behavior

Even if you install the DHCP bundled with pihole, don't turn it on by default and don't start it at boot.
Turn it on and start it at boot when the user want's it (he checked the checkbox in the gui).

### Steps to reproduce

1. install a fresh debian 10
2. check the `resolv.conf`
3. install pihole
4. restart
5. check the `resolv.conf` again, it has changed
6. run `top` and you see the runnung dhcp service

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by Peronia** [comment]
@dschaper my resources are limited too.
I can't open any request in Discourse, the "New Topic" button is disabled. I'm not trustlvl 1. Then I will not create a thread for it, sorry.
