### ISSUE TITLE
Can't use non-english characters for domains

### ISSUE THREAD

**Issue by aravindvnair99** [pi-hole/pi-hole#4075]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Expected behavior

Doing gravity sync after adding blocklists, results in:

```
Sample of invalid domains:
      - discörd.com
      - discördapp.com
      - disçordapp.com
      - minecräft.com
      - rëddït.com
```

### Actual behavior / bug

It should get added in. It's not accepting non-English alphabets.

### Steps to reproduce

Add `https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt` to lists and sync.

**Comment by dschaper** [comment]
Those domains are invalid. If you want to use IDN's then you need to convert them to punycode / ASCII first.

https://www.verisign.com/en_US/channel-resources/domain-registry-products/idn/idn-conversion-tool/index.xhtml

**Comment by aravindvnair99** [comment]
> Those domains are invalid. If you want to use IDN's then you need to convert them to punycode / ASCII first.
> 
> https://www.verisign.com/en_US/channel-resources/domain-registry-products/idn/idn-conversion-tool/index.xhtml

@dschaper I get that, but shouldn't the converted form be saved instead of throwing the error?

**Comment by dschaper** [comment]
No, the list provider should provide a list with valid domain names on them.

**Comment by aravindvnair99** [comment]
> No, the list provider should provide a list with valid domain names on them.

@dschaper Ahh okay, thanks for the clarification! I'll contact the maintainers. :)
