### ISSUE TITLE
PiHole not binding to port 53 on Docker 3.2.0+

### ISSUE THREAD

**Issue by Senpai-Ruku** [pi-hole/pi-hole#4079]
### Versions

- Pi-hole version is v5.2.4 (Latest: v5.2.4)
- AdminLTE version is v5.4 (Latest: v5.4)
- FTL version is v5.7 (Latest: v5.7)

### Platform

- OS and version:  Windows 10 Pro, 20H2 

- Platform:  Docker 3.2.0+

### Expected behavior

When starting PiHole container, it starts.

### Actual behavior / bug

When starting container, docker has error "(HTTP code 500) server error - driver failed programming external connectivity on endpoint pihole (#device hash#): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

It seems Docker/PiHole cannot bind to port 53 even though nothing else is using that port when running netstat.

### Steps to reproduce

1. Attempt to run PiHole on docker 3.2.0+

## Debug Token

- URL:  

N/A - PiHole will not run.

### Screenshots

![image](https://user-images.githubusercontent.com/40524740/110871940-41dc6e00-82c7-11eb-8885-da234984dfdc.png)

### Additional context

Rolling back to Docker 3.1.0 fixes this issue.

**Comment by dschaper** [comment]
> listen tcp4 0.0.0.0:53: bind: address already in use

Something else is already on port 53. 

Windows is not a supported platform. You'll need to follow up with Docker to find out why their new version is not working.
