### ISSUE TITLE
PiHole breaks Nest devices

### ISSUE THREAD

**Issue by recrudesce** [pi-hole/pi-hole#408]
##### Expected Behaviour:
Nest Devices can connect to the API etc and show as online in the Nest App/Web Interfaces

##### Actual Behaviour:
All Nest devices are unable to contact their respective API's and show as offline.

##### Steps to reproduce this issue:
Have any Nest product (thermostat, Protect) and use Pi-Hole as a DNS server.

I'll do some more digging to see if I can work out where the problem lies.  It's not a major issue for me, as I'll just not use Pi-Hole for a bit until I've worked out the issue.  Just raising it as something you might want to know about :)

**Comment by CDeeRON** [comment]
I have many Nest products and access the nest api to pull stats manually. No issues for me with pihole 2.5.3 as dns on my network.

**Comment by recrudesce** [comment]
Weird - as soon as I set my DNS to be the PiHole everything goes offline.  I'll try it again and report back.

**Comment by jradwan** [comment]
My Nest thermostat seems to working fine with Pi-Hole as well.

**Comment by recrudesce** [comment]
Very weird - maybe something wrong with the config.  I'll rebuild mine and see what happens.  Happy for this issue to be closed then as it seems to be related to just my environment, and no one elses.

**Comment by PromoFaux** [comment]
If you 'tail /var/logs/pihole.log' you'll be able to see in real time if any relevant domains are being blocked..

**Comment by nate-ubiquisoft** [comment]
I've got a nest cam and a nest thermostat running behind my pihole without issue. One thing I had to to was restart each nest device after setting the router to point dns request at my pihole to refresh their dns cache

**Comment by PromoFaux** [comment]
@recrudesce Did restarting your nest devices fix this issue?

**Comment by jacobsalmela** [comment]
I just got a Nest and it works fine with Pi-hole.  @recrudesce is it working for you now?

**Comment by dschaper** [comment]
Closing for staleness. Can re-open if problem persists.
