### ISSUE TITLE
Pi hole blacklist not working

### ISSUE THREAD

**Issue by Khengsoon** [pi-hole/pi-hole#4087]
### Versions
- Pi-hole:  v5.2.4.
- AdminLTE:  v5.4.
- FTL:  v5.7.

### Platform
- Platform:  Raspberry Pi 3
The blacklist seems not working for me, I tried a few domain names like google.com youtube.com.
I added (\.|^)youtube\.com$ into blacklist, all my PC point DNS to my Raspberry Pi, but they still can ping and goto youtube.com. May I know what possible I missed out?

**Comment by Khengsoon** [comment]
sorry for missing my debug token https://tricorder.pi-hole.net/wrs0nkkcxy

**Comment by yubiuser** [comment]
I see that you have IPv6 enabled in your network. This might be the reason why your clients bypass Pi-hole.
Please run from one client

`nslookup youtube.com` and `nslookup youtube 192.168.1.41`
____

Additionally, you experienced a FTL crash `   [2021-03-20 14:53:00.258 575/T579] ---------------------------->  FTL crashed!  <----------------------------`

Please file a bug at https://github.com/pi-hole/FTL/issues and include a few lines above the `FTL crashed` line and the lines below from `/var/log/pihole-FTL.log`.
Thank you.

**Comment by Khengsoon** [comment]
Below is the result I got after running the command 

C:\Users\ps>nslookup youtube.com
Server:  UnKnown
Address:  2406:3003:2000:2d27:5aef:68ff:fea4:b6da

Non-authoritative answer:
Name:    youtube.com
Addresses:  2404:6800:4003:c04::88
          2404:6800:4003:c04::5b
          2404:6800:4003:c04::5d
          2404:6800:4003:c04::be
          74.125.130.93
          74.125.130.91
          74.125.130.190
          74.125.130.136


C:\Users\ps>nslookup youtube 192.168.1.41
Server:  raspberrypi
Address:  192.168.1.41

Name:    youtube..

**Comment by Khengsoon** [comment]
I also notice if I do ipconfig /all below is the result I got

DNS Servers . . . . . . . . . . . : 2406:3003:2000:2d27:5aef:68ff:fea4:b6da
                                          192.168.1.41

**Comment by Khengsoon** [comment]
alright, thank you very much yubiuser^^, after I disabled the IPV6 on my NIC the blacklist works.

**Comment by Khengsoon** [comment]
I noticed one thing, for PC once I disabled the IPv6 the blacklist works, but for Mobile even I running on IPv4 the blacklist isn't working, do you face the same issue?

**Comment by yubiuser** [comment]
You're devices got a global IPv6 address. If you really need IPv6, you should use a ULA
https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127
___

No, I don't. Maybe your mobiles use a hard coded DNS server. Which mobile OS and version do you use?

**Comment by Khengsoon** [comment]
I try hardcode my phone DNS to by PiHole and the result still the same. My phone is Samsung Note 9 is running Android  8.1.0

**Comment by yubiuser** [comment]
Do you see the queries of your mobil in Pi-hole's Query log at all?

**Comment by Khengsoon** [comment]
Hi yubiuser do you mind guide me on how to queries the Pi-hole log?

**Comment by yubiuser** [comment]
Open Pi-hole's webinterfac (`http://pi.hole/admin/`) and click on Query Log in the left navigation menu

**Comment by Khengsoon** [comment]
seem don't have. let me check and restart my phone and get back to you again yobiuser. thank you very much for your help

**Comment by Khengsoon** [comment]
Hi yobiuser, attached is the DNS setting in my Pi-hole. I not sure why my table and phone even though the DNS  server manually set to Pi-hole and still can't find their query inside Pi-hole

![image](https://user-images.githubusercontent.com/14371661/111891003-d82c3480-8a29-11eb-8607-19c747a7de39.png)

**Comment by dschaper** [comment]
Since this isn't a bug but instead is a user configuration issue please visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by Khengsoon** [comment]
guys, pls try it out yourself before close my bug report. I have event tested, ping to those blacklist domain is blocked but still can open the website. Sad...

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/

**Comment by Khengsoon** [comment]
I follow this instruction to solved the issue I faced. thank you very much @dschaper and @yubiuser
