### ISSUE TITLE
Pi-Hole not installing 443 error

### ISSUE THREAD

**Issue by Gingerheadboy** [pi-hole/pi-hole#4091]
I entered: `curl -sSL https://install.pi-hole.net | bash`
and i get a network timed out error.

**Comment by Gingerheadboy** [comment]
I am using a raspberry pi zero w
do I need ethernet? will that make it work?

**Comment by PromoFaux** [comment]
For assistance with installation / configuration - please use https://discourse.pi-hole.net 

Thank you for your understanding
