### ISSUE TITLE
stop making people believe your docker container persists anything except dns settings

### ISSUE THREAD

**Issue by bash-stack** [pi-hole/pi-hole#4092]
when using the two suggested volumes in stock docker container,

all black & whitelist entries are gone after restart...

Had it twice, thanks for time waste..

also missing features like:

* "real bogus protection" ( 172.16 / 192.168 private requests are sent unless you put them on blacklist hich is gone after restart :( ) ,
* inability to define upstream per domain ( dnsmasq is able , but $product not) 
* inability to define anything else than AAAA / A / CNAME
* completely undocumented "but you can install it with database"

lead to going to call it sh*t hole instead of pi-hole,

and search for a mature solution  (real database instead of this sluggish "parse-logs" and "put db-on-sdcard" , bad practice over and over...

**Comment by dschaper** [comment]
Sorry Pi-hole is too complex for you.

**Comment by dschaper** [comment]
As to persistence with docker, well, learn about docker and you'll find that persistence is a user responsibility.

**Comment by PromoFaux** [comment]
> when using the two suggested volumes in stock docker container,
> 
> all black & whitelist entries are gone after restart...

Also, this is not the case. I'm using the docker container as my main Pi-hole install, and I don't have this issue..

There are things that can be improved in the container, for sure, but we're not going to listen to you if you're going to be a dickhead about it 😘
