### ISSUE TITLE
CNAME is not being querying or handled correctly?

### ISSUE THREAD

**Issue by lue30499** [pi-hole/pi-hole#4096]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  ubuntu 20.04.2 LTS

- Platform:  Proxmox LXC

### Expected behavior

After setting up the cname from the google documentation: https://support.google.com/websearch/answer/186669?hl=en
When querying pihole with "www.google.com" it will provide the IP address from true domain, the forcesafesearch.google.com.

### Actual behavior / bug

The response from pihole is nothing. It only changes to the actual IP response after manually querying forcesafesearch.google.com then when querying www.google.com will it reply correctly.

(Put video quality up to 1080p)
Please see video: https://drive.google.com/file/d/18D49yGnmdbNh-ZCMf-qNihCUBnrTNVSL/view

### Steps to reproduce

Put video quality up to 1080p
Please see video: https://drive.google.com/file/d/18D49yGnmdbNh-ZCMf-qNihCUBnrTNVSL/view

## Debug Token

- URL:  https://tricorder.pi-hole.net/h1xdk5yrsv

### Screenshots

Put video quality up to 1080p
Please see video: https://drive.google.com/file/d/18D49yGnmdbNh-ZCMf-qNihCUBnrTNVSL/view

**Comment by dschaper** [comment]
This is how CNAME aliasing works. 

`pihole-FTL` will only provide the result of the CNAME target if the target is known to `pihole-FTL` at the time of the query. It's made for domains that `pihole-FTL` is authoritative for. We detail this situation in the notes below the textboxes for adding CNAMEs.

![Screenshot 2021-03-28 090404](https://user-images.githubusercontent.com/2782850/112758720-aa546c00-8fa4-11eb-9ee6-f6dc072a779c.png)

**Comment by dschaper** [comment]
You can add an additional `hostrecord` that 'preloads' `forcesafesearch.google.com` to an IP and then your CNAME should work. If `pihole-FTL` already knows the IP address then everything should flow as you would like to force a safe search.
