### ISSUE TITLE
Error: database is locked during pi-hole start

### ISSUE THREAD

**Issue by alexstoffel** [pi-hole/pi-hole#4097]
### Versions
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

### Platform
- OS and version:  Debian GNU/Linux 10 (buster)
- Platform:  Kubernetes, Docker Image (pihole/pihole:v5.7)

### Expected behavior

pi-hole starting up as usual

### Actual behavior / bug

Error in startup-log after Step (::: Docker start setup complete):
Error: database is locked

### Steps to reproduce

1. Deploy Docker Image on Kubernetes Cluster k3s on raspberry Pi4
2. Watch Logs and witness the error

## Debug Token

- URL:  https://tricorder.pi-hole.net/3g48tzfq0g

### Additional context

YML definition of the pod deployment in Kubernetes:
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pihole
  name: pihole-deployment
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 1.1.1.1
      containers:
      - name: pihole
        image: pihole/pihole:v5.8
        env:
        - name: ServerIP
          value: 10.1.0.100
        - name: VIRTUAL_HOST
          value: pihole.local
        - name: TZ
          value: 'Europe/Berlin'
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: password
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: pihole-dnsmasq
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-data-pvc
      - name: pihole-dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-pvc

Ouput of sqlite db check
Command:
fuser gravity.db
Ouput:
/etc/pihole/gravity.db:   374

**Comment by dschaper** [comment]
Please use https://github.com/pi-hole/docker-pi-hole and fill out the docker issue template.
