### ISSUE TITLE
Feature request : Dashboard / Top Clients

### ISSUE THREAD

**Issue by wikibit** [pi-hole/pi-hole#410]
The Top Clients widget looks nice, but it seems to defeat its purpose
it is not very easy to see each client and their counts, you need to hover over the green datapoints to see the numbers; and that is becoming difficult if the datapoints are cluttered together

Talking usability of the dashboard : 
I would prefer a more simple list like top advertisers or top domains
clientip (hostname) and number of requests

**Comment by greg5678** [comment]
I like that idea. The current one is fine for small networked but when you have over 50 devices it gets cluttered together like you said. Please make it happen!

**Comment by Mcat12** [comment]
We will work on this. :)

**Comment by jradwan** [comment]
I agree. The dashboard is definitely pretty, and useful, but the Top Clients graph is hard to read in the current setup. Having the bar graph sort like Top Domains/Advertisers would be more useful.

![image](https://cloud.githubusercontent.com/assets/11047158/14318829/a10ce002-fbdc-11e5-9295-7ce6e7c48759.png)

How about a configurable option? :) Low low priority of course, but something to think about.

**Comment by DonLexos** [comment]
To add to this, more help would be if you could see the (host/network)name of the client (next to/instead of) his/her ip imho. Not sure if that is possible or not.

**Comment by greg5678** [comment]
It is but not every device has a human readable host name.

**Comment by dschaper** [comment]
I now have a ton of Cisco 303 IP phones and their addresses are apparently
a combination of their MAC and some random alpha's. And Cisco uses multiple
OUI's... Yay...

Dan Schaper

**Comment by greg5678** [comment]
like I said

**Comment by DonLexos** [comment]
I have no clue how the current web is displayed but if it is all html maybe add the host in the title='host' so you can see it on a hover?

**Comment by Mcat12** [comment]
Dnsmasq doesn't log hostnames though. That's the limiting factor.

**Comment by DonLexos** [comment]
Aaaah well if the information is not available the displaying part would be a bit of a challenge ofcourse ;-)

**Comment by Mcat12** [comment]
This is now released, albeit you have to manually link IP addresses to hostnames.
