### ISSUE TITLE
Negative query blocked

### ISSUE THREAD

**Issue by somera** [pi-hole/pi-hole#4100]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform

- OS and version:  Raspbian Buster Lite (Linux pi-server 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux)

- Platform:  Raspberry Pi

### Expected behavior

I'm using pi-hole on Pi as backup system. Sometimes will by used by FritzBox. An today I see negatove values.

```
$ /usr/local/bin/piholestats.sh
{
  "domains_being_blocked": 78959,
  "dns_queries_today": 795,
  "ads_blocked_today": -29,
  "ads_percentage_today": -3.647799,
  "unique_domains": 8508,
  "queries_forwarded": 490,
  "queries_cached": 305,
  "clients_ever_seen": 3,
  "unique_clients": 3,
  "dns_queries_all_types": 792,
  "reply_NODATA": -519,
  "reply_NXDOMAIN": -214,
  "reply_CNAME": -5618,
  "reply_IP": -1451,
  "privacy_level": 0,
  "enabled": 1,
  "gravity_last_updated": {
    "file_exists": 1,
    "absolute": 1616959476,
    "relative": {
      "days": 0,
      "hours": 22,
      "minutes": 48
    }
  }
}
```

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/8334250/112880613-f26dae80-90ca-11eb-81fa-9f97260d7ae6.png)

**Comment by jfb-pihole** [comment]
Please run `pihole restartdns` and see if the problem clears.

**Comment by somera** [comment]
thx
