### ISSUE TITLE
Homepage dashboard doesn't have any data

### ISSUE THREAD

**Issue by ecdeveloper** [pi-hole/pi-hole#4102]
### Versions

- Pi-hole:  v5.2.4 (Latest: v5.2.4)
- AdminLTE:  v5.4 (Latest: v5.4)
- FTL:  v5.7 (Latest: v5.7)

### Platform

- OS and version:  Ubuntu 18.04.4 LTS

- Platform:  Raspberry Pi

### Expected behavior

Expecting to see statistics and graphs on the dashboard homepage.

### Actual behavior / bug

No graphs are displayed. "Total Queries", "Queries Blocked" and "Percent Blocked" are all showing "---". 

### Steps to reproduce

1. Install pihole via recommended method
2. Use the standard configuration
3. Open dashboard homepage
4. Login

## Debug Token

- URL:  https://tricorder.pi-hole.net/vn9dz97on8

### Screenshots

<img width="1381" alt="Screen Shot 2021-04-01 at 12 39 11 AM" src="https://user-images.githubusercontent.com/836928/113330193-519e0f80-92d3-11eb-848c-b0cdec58dc86.png">

### Additional context
None.

**Comment by dschaper** [comment]
```plain
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
*:443 apache2 (IPv6)
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
```

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by ecdeveloper** [comment]
Ugh, I got it. Actually, after a little more digging it turned out that I didn't have sqlite3 installed for my php. After installing it and restarting apache everything works like a charm now.
