### ISSUE TITLE
Hardware Addresses from a different subnet/VLAN are showing as N/A

### ISSUE THREAD

**Issue by mdawsonuk** [pi-hole/pi-hole#4104]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi

### Expected/Actual behavior

I have a VLAN set up to filter traffic from my zero-trust devices (Sonos, Alexa etc.) from my network with (more) trusted devices, such as my PC, phone and Pi-Hole on my RPi. Ports 53, 80 and 443 are able to connect to the IP of my Pi-Hole (TCP and UDP) for all of the devices, and they show up as expected in the query log. However in the Tools -> Network page, the Hardware address shows as N/A on all of the devices.

Expected: the correct hardware address is show for the IP address
Actual: N/A is shown as the hardware address

## Debug Token

- URL:  https://tricorder.pi-hole.net/vnfz3shmcd

### Screenshots

As seen below, clients on the 192.168.1.0/24 subnet show their hardware addresses correctly, but devices on the 192.168.2.0/24 subnet do not, displaying N/A instead.
![image](https://user-images.githubusercontent.com/5032824/113524072-2998ff80-95a4-11eb-957b-41724e9a6f6d.png)

**Comment by dschaper** [comment]
The hardware addresses (MAC addresses) are limited to the broadcast domain. https://www.cbtnuggets.com/blog/technology/networking/networking-basics-what-are-broadcast-domains

Each VLAN is a broadcast domain, you'll need to configure the router to relay the information you would like to see. 

This is a networking issue and not something that Pi-hole would be handling.

**Comment by dschaper** [comment]
Here's a little more reading material on `arp`.

https://www.tummy.com/articles/networking-basics-how-arp-works/

**Comment by mdawsonuk** [comment]
Thank you for clarifying this. I was unaware as to whether it would be a Pi-Hole issue or an issue with my configuration. I'll do further research into this.
