### ISSUE TITLE
Update the lighttpd accesslog format to Common Log Format

### ISSUE THREAD

**Issue by AD-Wright** [pi-hole/pi-hole#4110]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.3.2
- FTL:  v5.6

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  Local Server

### Background
Currently, pi-hole's [lighttpd.conf](https://github.com/pi-hole/pi-hole/blob/cbfb58f7a283c2a3e7aad95a834a0287175ccb24/advanced/lighttpd.conf.debian#L38) overrides lighttpd's [default](https://doc.lighttpd.net/lighttpd2/mod_accesslog.html) format, and instead uses the log format "%{%s}t|%V|%r|%s|%b".  This section of the lighttpd.conf appears to have been added specifically for Logstalgia by @jacobsalmela in 2015 ([commit](https://github.com/pi-hole/pi-hole/commit/c34cc1608baf2c7c1450c19a9922107d91e57d29)), and the format in lighttpd.conf appears to be the same as Logstalgia's [Custom Log Format](https://github.com/acaudwell/Logstalgia/wiki/Custom-Log-Format).

### Issue

Attempting to change the log file format back to the default through external.conf causes lighttpd to break, as it apparently sees the file as having two different lines with "accesslog.format", and gives up.  The only way to enforce the default log file format is to change lighttpd.conf, which needs to be done after every update of Pi-hole.  If you are running other sites alongside Pi-hole on lighttpd, external.conf makes this simple, but if you want to use a stat viewer other than Logstalgia (such as Webalizer), the lighttpd.conf change is required.  Pi-hole does not appear to have any affiliation with Logstalgia that I can tell (although there are a [few](https://discourse.pi-hole.net/search?q=logstalgia) discussions on the discourse), so it does not seem reasonable to me to have this favoritism.  

### Proposed Resolution

Logstalgia [now supports](https://logstalgia.io/) the [Common Log Format](https://en.wikipedia.org/wiki/Common_Log_Format), which is the default of lighttpd.  Changing the log format from its current value to the default of "%h %V %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" would increase the compatibility of Pi-hole without detriment.  I don't use Logstalgia myself, but I did install it and verified that @jacobsalmela 's [example](https://jacobsalmela.com/2015/12/01/visualize-ads-blocked-in-real-time-using-pi-hole-and-logstalgia/) on his blog appears to work with lighttpd's default log format.  

I felt this was much closer to a bug report than a feature request, thus the issue and pull request.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
