### ISSUE TITLE
Efficiency of detection decreased about 50%

### ISSUE THREAD

**Issue by SZERO-1** [pi-hole/pi-hole#4112]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL: v5.7

### Platform

- OS and version: Raspbian GNU/Linux 10 (buster) armv7l

- Platform:  Raspberry Pi 3 Model B Rev 1.2

### Expected behavior

_Both target lists got downloaded._

### Actual behavior / bug

_https://mirror1.malwaredomains.com/files/justdomains not accessible anymore._

### Steps to reproduce

1. pihole -up

## Debug Token

- URL:  

### Screenshots

![NotFound](https://user-images.githubusercontent.com/50744829/114434401-80a96080-9bb2-11eb-86ea-0761c162bcaa.png)
![NotFoundURL](https://user-images.githubusercontent.com/50744829/114434511-9dde2f00-9bb2-11eb-8422-5da24af1403b.png)

### Additional context

_Nothing more to add._

**Comment by yubiuser** [comment]
The list doesn't exist anymore. Delete the URL from your adlists.
