### ISSUE TITLE
Installation fails ~Neither IPv4 or IPv6 selected

### ISSUE THREAD

**Issue by Mobulos** [pi-hole/pi-hole#4128]
### Versions

- Pi-hole:  newest installation script 15.04.2021
- AdminLTE:  ---
- FTL:  ---

### Platform

- OS and version:  Debian 10.9

- Platform:  Raspberry Pi

### Expected behavior

The installation script should show a selection of the IP Address

### Actual behavior / bug

`Error: Neither IPv4 or IPv6 selected`
The Script just shows that error message
Picture: https://i.imgur.com/GG0A7Xe.png

### Steps to reproduce

1. start the installation script `curl -sSL https://install.pi-hole.net | bash`

## Debug Token

- URL:  ---

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Do you see any dialog boxes or full screen menus?

Is this a fresh OS installation? Why were you `rm`ing a directory beforehand?

**Comment by Mobulos** [comment]
I've created a dir for the manual installation
It's not a clear installation but the first inst on that op System installation
And no boxes or menus just what it shows in the screenshot

**Comment by dschaper** [comment]
What does `whiptail -v` show and does the same thing happen after a reboot?

**Comment by Mobulos** [comment]
```
root@raspberrypi:~# whiptail -v
-v

```
It is set as manual installed
After reinstall and reboot
still the same output

**Comment by dschaper** [comment]
That's not the right output from `whiptail`. 

```plain
dan@raspberrypi:~ $ which whiptail
/usr/bin/whiptail
dan@raspberrypi:~ $ whiptail -v
whiptail (newt): 0.52.20
dan@raspberrypi:~ $ file /usr/bin/whiptail
/usr/bin/whiptail: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=25bc3b92d9b5294ee88d25325bb2b2c82f472b2d, stripped
```

**Comment by dschaper** [comment]
```plain
dan@raspberrypi:~ $ apt-cache policy whiptail
whiptail:
  Installed: 0.52.20-8
  Candidate: 0.52.20-8
  Version table:
 *** 0.52.20-8 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by Mobulos** [comment]
```
root@raspberrypi:~# whiptail

root@raspberrypi:~# whiptail -v
-v
root@raspberrypi:~# which whiptail
/usr/local/bin/whiptail
root@raspberrypi:~# /usr/local/bin/whiptail -v
-v
root@raspberrypi:~# file /usr/bin/whiptail
/usr/bin/whiptail: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=25bc3b92d9b5294ee88d25325bb2b2c82f472b2d, stripped
root@raspberrypi:~# apt-cache policy whiptail
whiptail:
  Installed: 0.52.20-8
  Candidate: 0.52.20-8
  Version table:
 *** 0.52.20-8 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status
root@raspberrypi:~#
```

**Comment by Mobulos** [comment]
```
root@raspberrypi:~# /usr/bin/whiptail -v
whiptail (newt): 0.52.20
root@raspberrypi:~#
```

**Comment by dschaper** [comment]
You seem to have a `/usr/local/bin/whiptail` installed that is broken and is taking the place of the actual `whiptail` binary.

What does

```
cat /usr/local/bin/whiptail
```
return as a result?

**Comment by Mobulos** [comment]
It's a redirection of "/usr/bin/echo"
https://pastebin.com/pwEytuHc

**Comment by dschaper** [comment]
Not sure where that would be useful but that's the problem.

**Comment by Mobulos** [comment]
should I delete the file?

**Comment by Mobulos** [comment]
```
root@raspberrypi:/usr/local/bin# rm whiptail
root@raspberrypi:/usr/local/bin# whiptail -v
-bash: /usr/local/bin/whiptail: No such file or directory
root@raspberrypi:/usr/local/bin# apt reinstall whiptail
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
Need to get 38.1 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://mirror.netcologne.de/raspbian/raspbian buster/main armhf whiptail armhf 0.52.20-8 [38.1 kB]
Fetched 38.1 kB in 1s (43.1 kB/s)
(Reading database ... 88845 files and directories currently installed.)
Preparing to unpack .../whiptail_0.52.20-8_armhf.deb ...
Unpacking whiptail (0.52.20-8) over (0.52.20-8) ...
Setting up whiptail (0.52.20-8) ...
Processing triggers for man-db (2.8.5-2) ...
root@raspberrypi:/usr/local/bin# whiptail -v
-bash: /usr/local/bin/whiptail: No such file or directory
root@raspberrypi:/usr/local/bin#
```
Didn't work, I'll restore the file

**Comment by PromoFaux** [comment]
I think if I were you I'd flash afresh SD card and try again.... something is very wrong with your system for this to be happening.

**Comment by Mobulos** [comment]
Okay, I'll try

**Comment by dschaper** [comment]
I don't know what put that file there or added it to your path. It's nothing I've ever seen and I have no idea how redirecting `whiptail` to `echo` could be in the least bit useful.

As for `rm whiptail`, you didn't clear out the hash cache when you removed it, so `bash` still references the old location. You'd need to `rm /usr/local/bin/whiptail` and then `hash -d whiptail` for `bash` to remove it from the path cache and for `bash` to know that it's supposed to use the one installed by the package manager.

**Comment by Mobulos** [comment]
It worked after a reinstallation
Thank you
