### ISSUE TITLE
Unable to update package cache

### ISSUE THREAD

**Issue by anomoly40** [pi-hole/pi-hole#4129]
Tried to update using pihole -up command and got this.
" [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"
  Unable to complete update, please contact Pi-hole Support
"

I've tried to update using the "apt-get update" command.
This is what it gave me.
"Get:1 http://packages.microsoft.com/repos/code stable InRelease [3,486 B]
Err:1 http://packages.microsoft.com/repos/code stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://packages.microsoft.com/repos/code stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details."

**Comment by yubiuser** [comment]
This is not an Pi-hole issue. 

Have you searched for the issue?

**Comment by jfb-pihole** [comment]
This is an OS level issue. Until apt update completes successfully, the Pi-hole installer won't continue.
