### ISSUE TITLE
Query log errors and strange domain entries

### ISSUE THREAD

**Issue by Rogacz** [pi-hole/pi-hole#4132]
### Versions

  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8 (Latest: v5.8)

### Platform

- OS and version:  Debian 10.9

- Platform:  Raspberry Pi 4

### Actual behavior / bug

Strange entries in Query log for example ¤7ÿ?°ÿ?Ô:ÿ?<9ÿ?te.
and error messages popup:
"DataTables warning: table id=all-queries - Requested unknown parameter '4' for row 12, column 4. For more information about this error, please see http://datatables.net/tn/4"

### Screenshots
<img width="1103" alt="Zrzut ekranu 2021-04-16 o 15 38 32" src="https://user-images.githubusercontent.com/474255/115036451-d2612c00-9ecd-11eb-9e80-c9029c024d7b.png">
<img width="547" alt="Zrzut ekranu 2021-04-16 o 15 38 56" src="https://user-images.githubusercontent.com/474255/115036465-d42aef80-9ecd-11eb-8627-e3db10eda8df.png">
<img width="968" alt="Zrzut ekranu 2021-04-16 o 16 01 43" src="https://user-images.githubusercontent.com/474255/115036467-d4c38600-9ecd-11eb-9474-046e331a3925.png">

### Steps to reproduce

Any time I try to open query log that contains a strange domain entry

## Debug Token

- URL:  https://tricorder.pi-hole.net/iz1ubnxq4m

### Additional context

Source of entries is a [Nettigo Air Monitor](https://air.nettigo.pl/o-projekcie/?setlang=en) I have it for few months and I didn't notice this behavior before.

**Comment by GenusGeoff** [comment]
Do you, or anyone on your network, use Google Chrome?

**Comment by Rogacz** [comment]
I was able to fix the issue at source but I guess you should have a better dns name sanitization

**Comment by dschaper** [comment]
It looks like we were accurately reporting the queries received?

**Comment by Rogacz** [comment]
Yes, but I don't think it was a valid query
Here is tcpdump I capture when it was happening:
23:45:40.632730 IP (tos 0x0, ttl 255, id 59162, offset 0, flags [none], proto UDP (17), length 71)
192.168.0.219.51842 > 192.168.0.44.domain: [udp sum ok] 3385+ A? M-,7M-^??M-0^DM-^??M-:M-^??D9M-^??te.^J^A^EM-z^D^A. (43)
E..G......R3.......,...5.3fN.9............7.?...?.:.?D9.?te.
..........
23:45:40.633098 IP (tos 0x0, ttl 64, id 17257, offset 0, flags [DF], proto UDP (17), length 71)
192.168.0.44.domain > 192.168.0.219.51842: [bad udp cksum 0x829c -> 0xe5ca!] 3385 NXDomain q: A? M-,7M-^??M-0^DM-^??M-:M-^??D9M-^??te.^J^A^EM-z^D^A. 0/0/0 (43)
E..GCi@.@.t....,.....5...3...9............7.?...?.:.?D9.?te.
..........

Also interface was having issues either crashing or showing wrong data. 
On attached screenshot you can see rows with date 1970 and type = NAM, NAM is name of the source not type of request

**Comment by dschaper** [comment]
A tcpdump will show the exact payload of the packets. It looks like you had network issues, there's some bad UDP checksums. 

Sanitizing out that information would just hide a condition that obviously needed to be addressed.

**Comment by Rogacz** [comment]
Sure that made me aware of the problem but it was also making pihole interface unusable 

That bad udp cksum is on packet send from pihole and tcpdump was collected on pihole
192.168.0.44 is pihole
192.168.0.219 is client
I though it's because of segmentation offload but I need to check it.
