### ISSUE TITLE
Local DNS query for the machine hosting pi-hole fails, but other local DNS entries work fine.

### ISSUE THREAD

**Issue by atheistd** [pi-hole/pi-hole#4138]
### Versions

- Pi-hole:  v5.3.1 (Latest: v5.3.1)
- AdminLTE:  v5.5 (Latest: v5.5)
- FTL:  v5.8.1 (Latest: v5.8.1)

### Platform
- DISTRIB_ID=Ubuntu
- DISTRIB_RELEASE=20.04
- DISTRIB_CODENAME=focal
- DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
- Platform:  Raspberry Pi 4 (4GB)

### Expected behavior

I'm using pi-hole on my Raspberry Pi (with the static IP address `192.168.1.104`) and I have a web-server running on it (apache 2, but listening on port 80 and 666 and lighttpd listening for the pi-hole web admin on port 200). I have the hostname set as `sentinel` (of the Pi on which I have pi-hole running) and this is how my files currently look. 

```
ubuntu@sentinel:~$ cat /etc/hosts
127.0.0.1 localhost
127.0.1.1 sentinel.local sentinel

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

```
ubuntu@sentinel:~$ cat /etc/hostname
sentinel
```

```
ubuntu@sentinel:~$ cat /etc/pihole/custom.list 
192.168.1.101 chief.local
192.168.1.102 ringmaster.local
192.168.1.103 flameboi.local
192.168.1.104 sentinel.local
192.168.1.105 0.vm
192.168.1.106 1.vm
192.168.1.107 2.vm
192.168.1.108 3.vm
192.168.1.109 4.vm
192.168.1.110 backup.local
192.168.1.113 tv.local
```

This is a fresh install (as I had some issues on the previous installation) (and this **did** work before) but if I goto `http://sentinel.local/` from any machine which uses pi-hole as the dns server, I should see the apache server's output.

### Actual behavior / bug

But as of now, going to `http://sentinel.local/` just results in my browser giving the following error.

```
This site can’t be reached
sentinel.local’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE
```

Now, if I do `ping flameboi.local` from a machine I can see the machine responding (without explicitly mentioning the local IP address). But the same doesn't work when I do `ping sentinel.local`.

```
 ╰─> nslookup sentinel.local
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	sentinel.local
Address: 192.168.1.104
```

When I do a nslookup, I see this in `pihole -t` on the Raspberry Pi (the host making queries is 192.168.1.103)

```
13:33:09: query[A] sentinel.local from 192.168.1.103
13:33:09: /etc/pihole/custom.list sentinel.local is 192.168.1.104
13:33:09: query[AAAA] sentinel.local from 192.168.1.103
13:33:09: cached sentinel.local is NODATA-IPv6
```

And now if I try to do `ping sentinel.local` (from 192.168.1.103)

```
 ╰─> ping sentinel.local
ping: sentinel.local: Name or service not known
```

and then I get this in `pihole -t`

```
13:35:53: query[SOA] local from 192.168.1.103
13:35:53: forwarded local to 127.0.0.1
```

I have the local DNS entry for `192.168.1.105` as `0.vm` for my VMs and all the VM related DNS entries work too. So from this I can conclude every local DNS queries **except** for `sentinel.local` (the machine where I'm running pi-hole) works.

### Steps to reproduce

1. Go-to the web-admin.
2. Under Local DNS, enter DNS records.
3. Add the entry for the machine 

## Debug Token

- [URL](https://tricorder.pi-hole.net/il7t29d07i)

### Additional context

I don't think this is necessary, but to avoid DNS conflicts I removed the `pi.hole` entry from `/etc/pihole/local.list` and rebooted. But that didn't solve the issue so removed the aforementioned file altogether. Apparently, that too didn't help.

Edit: Forgot to mention that I have unbound setup, and pi-hole is using `127.0.0.1#5335` as it's upstream DNS server, if that is useful in any way.

**Comment by dschaper** [comment]
Does it work with another domain besides `.local`? `.local` is used by mDNS/Bonjour and will cause all kinds of cross-issues.

From your report:

```plain
Non-authoritative answer:
Name:	sentinel.local
Address: 192.168.1.104
```

That shows that the server at `127.0.0.53` knows the IP address and has responded with `192.168.1.104`. Further:

```plain
13:33:09: /etc/pihole/custom.list sentinel.local is 192.168.1.104
13:33:09: query[AAAA] sentinel.local from 192.168.1.103
```

Pi-hole is functioning correctly and is responding with `192.168.1.104` to the request from the client at `192.168.1.103`.

Looking at the debug log, it seems the router is sending out leases with `192.168.1.1` as the DNS server and no local domain name.

```plain
*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   * Received 306 bytes from eth0:192.168.1.1
     Offered IP address: 192.168.1.104
     Server IP address: 192.168.1.1
     Relay-agent IP address: N/A
     BOOTP server: ecosystem.home.cisco.com
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.1.1
      lease-time: 86400 ( 1d )
      renewal-time: 43200 ( 12h )
      rebinding-time: 75600 ( 21h )
      netmask: 255.255.255.0
      broadcast: 192.168.1.255
      hostname: "sentinel-eth"
      dns-server: 192.168.1.1
      router: 192.168.1.1
      --- end of options ---
    
   DHCP packets received on interface wlan0: 0
   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 1
```

What kind of OS is on the client `192.168.1.103`? Can you provide a list of the DNS servers that the client is configured for? Does `dig pi.hole` return anything on that client?

**Comment by dschaper** [comment]
> Edit: Forgot to mention that I have unbound setup, and pi-hole is using `127.0.0.1#5335` as it's upstream DNS server, if that is useful in any way.

Yes, that may be the problem here as well.

```13:35:53: query[SOA] local from 192.168.1.103
13:35:53: forwarded local to 127.0.0.1
```

That says that Pi-hole is forwarding a request for the Start Of Authority for the `.local` domain to your Unbound install. If Unbound is unable to answer that request then there will be failures.

**Comment by atheistd** [comment]
> Looking at the debug log, it seems the router is sending out leases with 192.168.1.1 as the DNS server and no local domain name.

And how might I be able to solve that? I frequently experiment with things on my Pi and end up re-installing everything frequently as well. That has caused me not to use Pi's IP address in the router, as if the Pi is not resolving my DNS queries (when it's rebooting and or I'm starting from scratch and have not installed updates + pi-hole yet) my internet is down and family doesn't like that. So I keep `1.1.1.1` on the router as a "default" for anyone using it and manually set my IP addresses (instead of using a DHCP server as that results in me getting `1.1.1.1` as my DNS server and not being able to change it) on my phones. On my desktop and laptop, I have set only `192.168.1.104` as my only DNS server and tried [temporarily] turning off IPV6 (on the devices, not the router) but that didn't work as well.

> What kind of OS is on the client 192.168.1.103?

Ubuntu based Pop_OS (20.04). Although I have the same problems on my MacBook Pro (Catalina) at `192.168.1.102`. (that's what i used to `nslookup flameboi.local`.

> Does dig pi.hole return anything on that client?

Apparently, yes. (Even though I deleted `/etc/pihole/local.list` as it had two entries for sentinel and pi.hole at `192.168.1.104`), but I guess that change doesn't survive reboot?

```
 ╰─> dig pi.hole                                                              %

; <<>> DiG 9.16.1-Ubuntu <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63957
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;pi.hole.			IN	A

;; ANSWER SECTION:
pi.hole.		2	IN	A	192.168.1.104

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Apr 23 19:21:36 IST 2021
;; MSG SIZE  rcvd: 52
```

```
 ╰─> dig sentinel                                                             %

; <<>> DiG 9.16.1-Ubuntu <<>> sentinel
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 55847
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sentinel.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Apr 23 19:25:21 IST 2021
;; MSG SIZE  rcvd: 37
```

`dig sentinel.local` does return the address. It's just when I `ping` it or open that address in my browser when I face the problem.
```
 ╰─> dig sentinel.local                                                       %

; <<>> DiG 9.16.1-Ubuntu <<>> sentinel.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27726
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sentinel.local.			IN	A

;; ANSWER SECTION:
sentinel.local.		2	IN	A	192.168.1.104

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Apr 23 19:25:44 IST 2021
;; MSG SIZE  rcvd: 59

```


> > Edit: Forgot to mention that I have unbound setup, and pi-hole is using `127.0.0.1#5335` as it's upstream DNS server, if that is useful in any way.
> 
> Yes, that may be the problem here as well.

But other Local DNS get resolved properly. (the VM related, `flameboi.local` etc) It's just `sentinel.local` not working for me. And as I mentioned before `dig sentinel.local` **and** `nslookup sentinel.local` work normally. I just can't ping it nor access it [from the web browser]. *Last minute discovery, it works perfectly on my mobile phones.*

(this is the output when I query from my phone)
```
19:39:32: query[A] sentinel.local from 192.168.1.110
19:39:32: /etc/pihole/custom.list sentinel.local is 192.168.1.104
```

But it forwards the query to unbound when I query it from my desktop and laptop.
192.168.1.102 - macOS Catalina (connected via WiFi)
192.168.1.102 - Pop!_OS 20.04 (wired)

```
19:40:36: query[A] sentinel.local from 192.168.1.103
19:40:36: /etc/pihole/custom.list sentinel.local is 192.168.1.104
19:40:50: query[SOA] local from 192.168.1.103
19:40:50: forwarded local to 127.0.0.1
```

```
19:44:52: query[A] sentinel.local from 192.168.1.102
19:44:52: /etc/pihole/custom.list sentinel.local is 192.168.1.104
19:45:01: query[SOA] local from 192.168.1.102
19:45:01: forwarded local to 127.0.0.1
```

> Looking at the debug log, it seems the router is sending out leases with 192.168.1.1 as the DNS server and no local domain name.

The only problem I'm assuming is that DHCP is somehow screwing it up. On the devices where I can't just specify the DNS address manually are my android phones, so I manually enter the details(device IP address, gateway, DNS). On those [android] devices/phones, I get everything working properly. But on the devices where I *can* simply specify the DNS address, is somehow screwing things up. I have no idea if this is a common occurrence but I had this exact same config (not re-using the old config, but I did set up everything as I previously did) working before I nuked my perfectly capable install (switched from Raspberry Pi OS to Ubuntu Server 20.04 as I wanted ZFS and it needed a 64-bit addressable userspace/kernelspace) and it worked flawlessly. I could just `ssh ubuntu@sentinel.local` and it would work like a charm (I'll admit it's longer, but easier to type with less periods being used).

**Comment by dschaper** [comment]
> > Looking at the debug log, it seems the router is sending out leases with 192.168.1.1 as the DNS server and no local domain name.
> 
> And how might I be able to solve that?

That would be something your router manufacturer would be able to tell you.


> `dig sentinel.local` does return the address. It's just when I `ping` it or open that address in my browser when I face the problem.

Then `pi-hole` is working exactly as it should. The problem lies elsewhere. Pi-hole can only return or not return an IP. It's returning an IP and it's job is done.



> And as I mentioned before `dig sentinel.local` **and** `nslookup sentinel.local` work normally. I just can't ping it nor access it [from the web browser]. _Last minute discovery, it works perfectly on my mobile phones._

That confirms what I said above.



> But on the devices where I _can_ simply specify the DNS address, is somehow screwing things up

What are you configuring for the search domains for those manual configurations? What I think may be happening is that you aren't specifying any domains to be used in a search. See https://bash-prompt.net/guides/resolv-conf/ for explanation of how search works and why it's necessary if you want to use `sentinel` instead of `sentinel.local`. And you'll need to make sure that either Pi-hole or the resolve Pi-hole will use for the `.local` domain is able to respond to a query for `sentinel.local`.

**Comment by atheistd** [comment]
> That would be something your router manufacturer would be able to tell you.

I was hoping for more of a general term like "port forwarding" "DMZ" etc to be mentioned so I can google it and make sure my router doesn't do that anymore. :')

> What are you configuring for the search domains for those manual configurations?

I don't think I have any. My `/etc/resolv.conf` looks like this

```
nameserver 127.0.0.53
options edns0 trust-ad
```

From what I assume, I don't want to use `sentinel`. I use `sentinel.local`. :)

If you still feel it's a router related problem, feel free to close this issue. I'll figure something out. :")

**Comment by dschaper** [comment]
> I was hoping for more of a general term like "port forwarding" "DMZ" etc to be mentioned so I can google it and make sure my router doesn't do that anymore. :')

DHCP server options?

> If you still feel it's a router related problem, feel free to close this issue. I'll figure something out. :")

`dig` returning the correct IP address is as far as Pi-hole goes. You've noted a few cases where things do work for you so that tells me that Pi-hole is working fine.

**Comment by 13rac1** [comment]
If you find this issue in 2022+ and are running Pi-hole in Docker: Set the `VIRTUAL_HOST` environment variable to your `$HOSTNAME.local` value ([See the Docker container optional variables](https://github.com/pi-hole/docker-pi-hole/tree/1b35e7fdd425ee2ac49b3aadc33ac1489c897ef3#optional-variables).) Pi-hole shouldn't block any `.local` mDNS/Bonjour domain names, but this solves the issue and automatically redirects to the `/admin` path.
