### ISSUE TITLE
Web UI Doesn't load correctly

### ISSUE THREAD

**Issue by lukebrewerton** [pi-hole/pi-hole#4139]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Raspbian

- Platform:  Raspberry Pi

### Expected behavior

Web UI to load, including graphs etc and be fully functional

### Actual behavior / bug

_The graphs do not show any information, nor does it display correctly. Upon looking in the Chrome dev tools (Have also tried Safari, Firefox & MSEdge) the console is filled with `Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH` for loads of the PHP & JS files

### Steps to reproduce

1. Go to Admin Web UI
2. Graphs not displaying

## Debug Token

- URL:  https://tricorder.pi-hole.net/9zh5rlo2hy

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Your debug log cuts off. Is the IP address configuration correct?

```plain
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.1.108/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   192.168.1.1/24 matches the IP found in /etc/pihole/setupVars.conf
```

**Comment by lukebrewerton** [comment]
Not sure why, it seemed to run fully! But the second IP (192.168.1.1/24) is the correct one as that is the static one that I assigned to it

**Comment by dschaper** [comment]
Can you try `pihole -d` again then?

**Comment by lukebrewerton** [comment]
It's just running now, I re ran it after seeing your comment above

**Comment by lukebrewerton** [comment]
The latest one is https://tricorder.pi-hole.net/n9ytkp6o8b

**Comment by lukebrewerton** [comment]
It was working fine until I updated a couple of days ago, and I also tried a complete fresh install (hence the lack of lists). I was on v5.3.0 possibly as I installed it fresh last week and was working fine

**Comment by dschaper** [comment]
Still failing to fully upload the log. It's stopping at the DHCP services discovery part. 

Can you run `pihole-FTL dhcp-discover` at the terminal on the Pi-hole device and show the output?

**Comment by lukebrewerton** [comment]
Weird, is there some other way I can upload it somewhere? I can pull the whole debug log from the FS and put it somewhere

`root@pihole:~# pihole-FTL dhcp-discover
Scanning all your interfaces for DHCP servers
Timeout: 10 seconds

* Received 354 bytes from eth0:192.168.1.254
  Offered IP address: 192.168.1.108
  Server IP address: 192.168.1.254
  Relay-agent IP address: N/A
  BOOTP server: (empty)
  BOOTP file: (empty)
  DHCP options:
   Message type: DHCPOFFER (2)
   server-identifier: 192.168.1.254
   lease-time: 86400 ( 1d )
   renewal-time: 43200 ( 12h )
   rebinding-time: 75600 ( 21h )
   netmask: 255.255.255.0
   broadcast: 192.168.1.255
   domain-name: "home"
   dns-server: 192.168.1.254
   router: 192.168.1.254
   wpad-server: "\n\000"
      --- end of options ---

DHCP packets received on interface lo: 0
DHCP packets received on interface eth0: 1`

**Comment by dschaper** [comment]
>     * wpad-server: "\n\000"

It's that. Which is a bad wpad-server address anyways. And could cause browser issues if the browser is trying to use that as a WPAD proxy.

**Comment by lukebrewerton** [comment]
Ok, not sure where it's getting that from. I'll turn off the router DHCP temporarily and use the pi-hole dhcp (If I can get it enabled via the ui)

**Comment by lukebrewerton** [comment]
No such joy on that when using static IP, and no proxy detection

**Comment by dschaper** [comment]
> No such joy on that when using static IP, and no proxy detection

I don't know what you are trying to say.

**Comment by buxm** [comment]
I can confirm the same issue.
Running on Docker 18.09.8 on Synology DS916+.
Only the template is displayed on the dashboard, no numbers/graphs/data.
If I go to the Settings page, I get the following:
![image](https://user-images.githubusercontent.com/57507414/116010146-9e001500-a61d-11eb-8d10-61e0789014e1.png)

This started when I updated my docker image (via docker pull and container restart) to v5.8.1.

**Comment by dschaper** [comment]
> I can confirm the same issue.

No, you have a different issue. I'd suggest using the proper repository to report your issue, though it looks like you don't have the right permissions set on your volume mounts. Please use https://github.com/pi-hole/docker-pi-hole.
