### ISSUE TITLE
Cannot get supported OS infomations

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pi-hole/pi-hole#4140]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8

### Platform

- OS and version:  Raspian 10

- Platform:  RPi

### Expected behavior

When running `pihole -up` it can update without any problems.

### Actual behavior / bug

It stuck at finding supported OS. Then report the server cannot be reached.

### Steps to reproduce

1. Type `pihole -up` in terminal/ssh
2. Wait
3. Wait
4. It pops a error message saying servers could not be reached

## Debug Token

- [✓] Your debug token is: https://tricorder.pi-hole.net/7f7hdutxg0

### Screenshots

_See reddit thread [here](https://www.reddit.com/r/pihole/comments/mw5lux/unable_to_update_on_raspian_skip_the_check_can/)_

### Additional context

The following code failed with code 9:
```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
```

The following code works fine:
```
dig +short -t txt versions.pi-hole.net
dig +short -t txt versions.pi-hole.net @127.0.0.1
dig +short -t txt versions.pi-hole.net @1.1.1.1
```
Output:
```
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32,33 CentOS=7,8"
```

Edit 1: `nmap ns1.pi-hole.net`
```
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.11 seconds
```

`traceroute ns1.pi-hole.net` reported the route seems to end at a tier 1 network provider near my area.

End edit 1.

**Comment by PromoFaux** [comment]
Seems OK on this end.

```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32,33 CentOS=7,8"
```

![image](https://user-images.githubusercontent.com/1998970/115760999-c4ae1980-a399-11eb-9433-892ad4dd6339.png)

Of course, as long as you're on one of those operating systems, you could always run the command suggested in the output:

```
PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
```

**Comment by dschaper** [comment]
Seems to be accessible globally. https://www.whatsmydns.net/#TXT/versions.pi-hole.net

Are you able to go to https://cloudns.net

**Comment by dschaper** [comment]
And a second check that uses `ns1.pi-hole.net` directly:

https://dnstools.ws/lookup/versions.pi-hole.net/TXT/?server=ns1.pi-hole.net

**Comment by jfb-pihole** [comment]
I will also confirm that I have had no problems reaching the nameserver all day.  OP's post on Reddit indicated that:

`Traceroute got some domain up to my local tier 1 network provider and got nothing.`

That's where the problem lies.

**Comment by SodaWithoutSparkles** [comment]
Just gone sleeping. The cloudns site seems to got me a connection refused error on chrome. Will edit this comment for traceroute info.

**Comment by dschaper** [comment]
ClouDNS is the host of our DNS servers. If you can't access them then it's not something we can resolve.

**Comment by SodaWithoutSparkles** [comment]
And no, after unblocking cloudns I still cannot update

**Comment by PromoFaux** [comment]
> I still cannot update

I refer you to my previous comment 😏 

> Of course, as long as you're on one of those operating systems, you could always run the command suggested in the output:
> 
> ```
> PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
> ```

**Comment by dschaper** [comment]
> 
> 
> And no, after unblocking cloudns I still cannot update

How was it blocked? What did you do to unblock it? What is the result of the `dig` command now? 

The quality of our ability to troubleshoot and resolve issues is directly related to the quality of the information provided for us to do the task.

**Comment by SodaWithoutSparkles** [comment]
It was blocked by one of the list I used. I add that to my whitelist. Can browse cloudns.net again. Other things remains the same. That dig command still got a exit code of 9.

**Comment by dschaper** [comment]
Did the traceroute change?

**Comment by SodaWithoutSparkles** [comment]
Still the same results. Stuck at `HundredGE0-3-0-1`

**Comment by dschaper** [comment]
> What if changing the code to not use ns1.pi-hole.net but other public servers? It seems that they return the same results. (Not familiar with how that works, and if it is stupid or not)

It's written the way it is for a specific reason, changing it because your particular transit is broken isn't something we'll be doing.

MTR's show that `ns1.pi-hole.net` exists and is pingable. It's the resolver at step 18.
```plain
15. 208.98.202.2                                                                   0.0%    38   42.3  42.9  41.0  72.7   5.0
16. 135.84.184.229                                                                 0.0%    38   42.9  42.2  40.8  50.4   1.9
17. 135.84.185.34                                                                  0.0%    38   45.1  43.4  41.9  48.5   1.5
18. pns21.cloudns.net                                                              0.0%    38   42.4  42.8  41.0  56.5   2.6
```
