### ISSUE TITLE
Long Term Data Query Log fails for 30 days

### ISSUE THREAD

**Issue by matsonfamily** [pi-hole/pi-hole#4144]
### Versions
root@rpi4:/var/log/lighttpd# pihole -v
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version: Raspberry Pi 10 (Buster)
- Platform:  Raspberry Pi 4 8GB

### Expected behavior
I expect to be able to use the */admin web-page's Long Term Data -> Query Log -> 30 days and it works.  If not, then I would like a clear error that informs me how to fix it.

### Actual behavior / bug
- */admin page tells me this: An unknown error occurred while loading the data.  Check the server's log files (/var/log/lighttpd/error.log when you're using the default Pi-hole web server) for details. You may need to increase the memory available for Pi-hole in case you requested a lot of data.
- /var/log/lighttpd/error.log produces one line: 2021-04-24 12:51:29: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes) in /var/www/html/admin/api_db.php on line 437

### Steps to reproduce
[Steps to reproduce the behavior documented in behavior section above]

## Debug Token
- cannot complete, sorry:
```
root@rpi4:/tmp# `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
[?] Would you like to upload the log? [y/N] y
bash: $'\E[H\E[2J\E[3JThis': command not found
root@rpi4:/tmp# 
```

- URL:  

### Additional context
I cannot seem to get an error anywhere else in pihole, other than the debug message (is that an error?).  It seems to me that lighttpd is saying i have 128MB allocated to it, and thus I cannot store 4MB, which doesn't make sense to me.  Let me know if there's more information I can provide.

**Comment by dschaper** [comment]
> You may need to increase the memory available for Pi-hole in case you requested a lot of data.

> PHP Fatal error: Allowed memory size of 134217728 bytes exhausted

You'll need to increase the amount of memory allocated to PHP. See https://discourse.pi-hole.net/t/how-do-i-increase-phps-memory/37170

**Comment by dschaper** [comment]
> `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger

Looks like you may have tried to copy/paste commands. You only need to run `pihole -d`.

**Comment by matsonfamily** [comment]
> ```
> root@rpi4:/tmp# `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
> ```
> 
> Looks like you may have tried to copy/paste commands. You only need to run `pihole -d`.

What?? i'm not supposed to copy that?  LOL.   
https://tricorder.pi-hole.net/ddxrxtetna

**Comment by dschaper** [comment]
Follow the steps listed on the linked Discourse topic. You need to increase PHP's available memory from the default value your OS has set.

**Comment by matsonfamily** [comment]
> Follow the steps listed on the linked Discourse topic. You need to increase PHP's available memory from the default value your OS has set.

I'm not as fast as you!  :)   I just finished following your steps above (discourse link) and changed my PHP's available memory (/etc/php/[version]/cgi/php.ini saved to *.original) from 128MB to 512MB, and it's FIXED!!  :smile:   Thank you _so much_ for your patience and help.
