### ISSUE TITLE
Upgrading 5.8 to 5.8.1 after removing IPV4_ADDRESS throws error

### ISSUE THREAD

**Issue by karlshea** [pi-hole/pi-hole#4146]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Raspbian 10.9

- Platform:  Raspberry Pi

### Expected behavior

The upgrade completes with no error.

### Actual behavior / bug

```
[✓] Restarting pihole-FTL service...
  No IP addresses found! Please run 'pihole -r' to reconfigure

  Unable to complete update, please contact Pi-hole Support
```

### Steps to reproduce

1. Remove `IPV4_ADDRESS`/`IPV6_ADDRESS` from `setupVars.conf` as mentioned in the [5.8 release notes](https://github.com/pi-hole/FTL/releases/tag/v5.8).
2. Run `pihole -up`

**Comment by DL6ER** [comment]
Yes, sorry. The variables you removed aren't necessary for FTL in its most recent version, however, they are unfortunately still necessary in some other parts of the code. I already have a bugfix for this (https://github.com/pi-hole/pi-hole/pull/4131) but it has not yet been reviewed/merged. I should have been clearer on the release notes about this...

**Comment by karlshea** [comment]
Makes sense! I just put the variables back and my installation is working normally.

**Comment by yubiuser** [comment]
Fix with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
