### ISSUE TITLE
Devices not loading requested webpages after restarting Pi-hole

### ISSUE THREAD

**Issue by benjaminbogdanovic** [pi-hole/pi-hole#4148]
After restarting the Raspberry Pi 4 that runs Pi-hole, devices with Pi-hole set as their DNS do not load requested webpages. The issue is resolved after repairing with pihole -r, but reoccur again after restarting the Raspberry Pi. What could be causing this?

Straight after restart: https://tricorder.pi-hole.net/755vv6gfef
After pihole -r repair: https://tricorder.pi-hole.net/rets5znxix

Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8.1 (Latest: v5.8.1)

**Comment by jfb-pihole** [comment]
After restart, connectivity issues on port 53 to the Pi:

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] adobe.aeonbank.co.jp is 0.0.0.0 via localhost (127.0.0.1)
[✗] Failed to resolve adobe.aeonbank.co.jp via Pi-hole (192.168.1.111)
[✓] doubleclick.com is 142.250.200.14 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] cas.us.criteo.com is :: via localhost (::1)
[✗] Failed to resolve cas.us.criteo.com via Pi-hole
```
Plus, the DHCP server is not providing the IP of Pi-hole to clients, and also reported a connectivity problem at the time the debug log was run:

```
*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   WARN: Could not sendto() in send_dhcp_discover() (/root/project/src/dhcp-discover.c:223): Network is unreachable
   * Received 353 bytes from eth0:192.168.1.254
     Offered IP address: 192.168.1.115
     Server IP address: N/A
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.1.254
      lease-time: 86400 ( 1d )
      netmask: 255.255.255.0
      router: 192.168.1.254
      dns-server: 192.168.1.254
      renewal-time: 43200 ( 12h )
      rebinding-time: 75600 ( 21h )
      broadcast: 192.168.1.255
         domain-name: "home"
      --- end of options ---
    
   DHCP packets received on interface wlan0: 0
   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 1
```
After repair, the IPv4 connectivity problem cleared.

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] h1.raniaweb.com is 0.0.0.0 via localhost (127.0.0.1)
[✓] h1.raniaweb.com is 0.0.0.0 via Pi-hole (192.168.1.111)
[✓] doubleclick.com is 142.250.200.14 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] mk.sios.jp is :: via localhost (::1)
[✗] Failed to resolve mk.sios.jp via Pi-hole
```

After restart, check the assigned IP address and verify that you can connect to the Pi on port 53.  Do you have any firewalls on your network or on that device that would interfere with port 53 traffic?

**Comment by dschaper** [comment]
Following up on what JFB said, you can see that Pi-hole is up and working locally at the start. Localhost is resolving and giving the proper 0.0.0.0 response. It's the connectivity to 192.168.1.111 that is not functioning.

The networking check does show that there is an IP assigned to the interface, you may want to check if `ip addr list` and `ip link show` indicates that `eth0` is `state UP`.

```plain
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   192.168.1.111/24 matches the IP found in /etc/pihole/setupVars.conf
```
 
The `pihole-FTL` status shows things came up as expected with the first token's log:

```plain
   Active: active (exited) since Tue 2021-04-27 23:25:08 BST; 1min 55s ago
```
That timestamp matches with the timestamps showing that FTL is open and running:

```plain
   [2021-04-27 23:25:08.731 798M] PID of FTL process: 798
   [2021-04-27 23:25:08.760 798/T799] Listening on port 4711 for incoming IPv4 telnet connections
   [2021-04-27 23:25:08.760 798/T801] Listening on Unix socket
   [2021-04-27 23:25:08.760 798M] INFO: FTL is running as user pihole (UID 998)
   [2021-04-27 23:25:08.760 798/T800] Listening on port 4711 for incoming IPv6 telnet connections
   [2021-04-27 23:25:09.043 798M] Reloading DNS cache
   [2021-04-27 23:25:09.043 798M] Blocking status is enabled
```

I do see that there are some IPv6 address issues but those look unrelated to this.

```plain
*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] cas.us.criteo.com is :: via localhost (::1)
[✗] Failed to resolve cas.us.criteo.com via Pi-hole (fdaa:<REDACT>:880)
[✓] doubleclick.com is 2a00:1450:4009:81e::200e via a remote, public DNS server (2001:4860:4860::8888)
```

```plain
[✓] IPv6 address(es) bound to the eth0 interface:
   2a00:<REDACT>:d683 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   fdaa:<REDACT>:68d3 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   fe80::8f55:177a:c4b2:5c00 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
```
Those issues show on both token's logs.

**Comment by benjaminbogdanovic** [comment]
> After restart, check the assigned IP address and verify that you can connect to the Pi on port 53. Do you have any firewalls on your network or on that device that would interfere with port 53 traffic?

After restart the assigned IP is 192.168.1.111 as expected. I disabled UFW on the device, and there is no other firewalls on the network that could interfere.

I only noticed this issue after the v5.3 update.

**Comment by benjaminbogdanovic** [comment]
> The networking check does show that there is an IP assigned to the interface, you may want to check if `ip addr list` and `ip link show` indicates that `eth0` is `state UP`.

Below is just after restart. Seems to be as expected.

`pi@raspberrypi:~ $ ip addr list`
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether **:**:**:**:**:** brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.111/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 2a00:23c7:63ba:1600:399:5a1b:c304:d683/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 21474816sec preferred_lft 21474816sec
    inet6 fdaa:bbcc:ddee:0:4f33:a079:263e:68d3/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::8f55:177a:c4b2:5c00/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether **:**:**:**:**:**  brd ff:ff:ff:ff:ff:ff
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.100.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
    inet6 fd08:4711::1/64 scope global 
       valid_lft forever preferred_lft forever
`pi@raspberrypi:~ $ ip link show`
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether **:**:**:**:**:**  brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DORMANT group default qlen 1000
    link/ether **:**:**:**:**:** brd ff:ff:ff:ff:ff:ff
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/none

**Comment by benjaminbogdanovic** [comment]
> I do see that there are some IPv6 address issues but those look unrelated to this.
> 
> ```
> *** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
> [✓] cas.us.criteo.com is :: via localhost (::1)
> [✗] Failed to resolve cas.us.criteo.com via Pi-hole (fdaa:<REDACT>:880)
> [✓] doubleclick.com is 2a00:1450:4009:81e::200e via a remote, public DNS server (2001:4860:4860::8888)
> ```
> 
> ```
> [✓] IPv6 address(es) bound to the eth0 interface:
>    2a00:<REDACT>:d683 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
>    fdaa:<REDACT>:68d3 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
>    fe80::8f55:177a:c4b2:5c00 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
> ```
> 
> Those issues show on both token's logs.

I noticed that and am looking at how to fix it.

**Comment by dschaper** [comment]
> 4: wg0:

Are you running piVPN?

**Comment by benjaminbogdanovic** [comment]
> Are you running piVPN?

WireGuard

**Comment by dschaper** [comment]
Can you make sure there are no extra files in `/etc/dnsmasq.d/` other than `01-pihole.conf`?

And it would be interesting to see if adding a delay of 5 or 10 seconds helps. That would narrow down where we should be looking for resolutions.

https://docs.pi-hole.net/ftldns/configfile/#delay_startup

**Comment by benjaminbogdanovic** [comment]
> Can you make sure there are no extra files in `/etc/dnsmasq.d/` other than `01-pihole.conf`?

There is only `01-pihole.conf`

> And it would be interesting to see if adding a delay of 5 or 10 seconds helps.

5 seconds did not work. 10 seconds did.

**Comment by dschaper** [comment]
> 5 seconds did not work. 10 seconds did.

That leads me to this being something related to your networking setup. There's not really anything in `FTL` that would change with a delay, it really just waits for that delay period to expire and then do what it's always done. 

I'll ask @DL6ER if there's anything he sees since we've been talking about the delay function lately.

**Comment by benjaminbogdanovic** [comment]
Okay. I have not changed anything in my network setup since I first installed `Pi-hole` a few months back. The issue coincided with me updating to `Pi-hole v5.3.1` and `FTL v5.8.1`, though the issue may predate the hot fixes as I did not restart between installing them and the previous release days earlier. I will check to see if there were any firmware updates to my networking hardware.

**Comment by DL6ER** [comment]
The delay we discussed about was necessary due to a wrong clock after startup and consequently issues with interpreting timestamps from the long-term database (which were seemingly in the future). This does not apply here.

Nevertheless, the delay of 10 seconds working clearly points towards a slow network interface that isn't up when FTL is started. Interestingly enough, we have countermeasures in place to resolve this case but they don't seem to be working here. Please try
```
pihole checkout ftl tweak/more_listening_logging
```
and then see what
```
grep "listening" /var/log/pihole-FTL.log
```
returns.

**Comment by dschaper** [comment]
This seems to be very similar: https://www.reddit.com/r/pihole/comments/n0kw4k/pihole_dns_fails_on_reboot_query_filled_with/gw85y9a?utm_source=share&utm_medium=web2x&context=3

**Comment by benjaminbogdanovic** [comment]
> ```
> grep "listening" /var/log/pihole-FTL.log
> ```

With delay:
```
pi@raspberrypi:~ $ grep "listening" /var/log/pihole-FTL.log
[2021-04-29 00:09:25.366 1858M] FTL branch: tweak/more_listening_logging
[2021-04-29 00:09:36.095 1858M] listening on 0.0.0.0 port 53
[2021-04-29 00:09:36.100 1858M] listening on :: port 53
```

Without delay:

```
pi@raspberrypi:~ $ grep "listening" /var/log/pihole-FTL.log
[2021-04-29 00:09:25.366 1858M] FTL branch: tweak/more_listening_logging
[2021-04-29 00:09:36.095 1858M] listening on 0.0.0.0 port 53
[2021-04-29 00:09:36.100 1858M] listening on :: port 53
[2021-04-29 00:11:50.013 745M] FTL branch: tweak/more_listening_logging
[2021-04-29 00:11:50.624 745M] listening on 0.0.0.0 port 53
[2021-04-29 00:11:50.624 745M] listening on :: port 53
[2021-04-29 00:12:16.386 1566M] FTL branch: tweak/more_listening_logging
[2021-04-29 00:12:57.682 1566M] listening on 0.0.0.0 port 53
[2021-04-29 00:12:57.682 1566M] listening on :: port 53
```

Do I need to switch back to the master branch, or will it switch back on restart?

**Comment by DL6ER** [comment]
> Do I need to switch back to the master branch, or will it switch back on restart?

The former.

> `pihole checkout master`?

Yes.

---

So Pi-hole is configured to listen on the wildcard address instead of on specific interfaces. This is correct and *should* avoid the issue of network interfaces coming up later not being recognized. Because the kernel *should* provide all packets from all interfaces when listening to the wildcard addresses. Regardless of when they come up, when they go down or if they change address.

We can try adding
```
bind-dynamic
```
in a new file `/etc/dnsmasq.d/99-bind-dynamic.conf
```
and again
```
pihole restartdns
```
This enables a network mode which is a hybrid between binding to interfaces and the default (binding to the wildcard address). FTL binds the address of individual interfaces but if new interfaces or addresses appear, it automatically listens on those (subject to any access-control configuration). This makes dynamically created interfaces work in the same way as the default. Let's see if this helps.

**Comment by benjaminbogdanovic** [comment]
I presume you wanted me to remove the delay?

I added `bind-dynamic` to a new file `/etc/dnsmasq.d/99-bind-dynamic.conf`, restarted the DNS, and also the Raspberry Pi. It works!

```
pi@raspberrypi:~ $ grep "listening" /var/log/pihole-FTL.log
[2021-04-30 02:52:42.867 10366M] FTL branch: tweak/more_listening_logging
[2021-04-30 02:52:53.417 10366M] listening on 10.100.0.1 port 53
[2021-04-30 02:52:53.417 10366M] listening on wg0(#4): 10.100.0.1 port 53
[2021-04-30 02:52:53.417 10366M] listening on 192.168.1.111 port 53
[2021-04-30 02:52:53.417 10366M] listening on eth0(#2): 192.168.1.111 port 53
[2021-04-30 02:52:53.418 10366M] listening on 127.0.0.1 port 53
[2021-04-30 02:52:53.418 10366M] listening on lo(#1): 127.0.0.1 port 53
[2021-04-30 02:52:53.418 10366M] listening on fd08:4711::1 port 53
[2021-04-30 02:52:53.418 10366M] listening on wg0(#4): fd08:4711::1 port 53
[2021-04-30 02:52:53.419 10366M] listening on fe80::8f55:177a:c4b2:5c00%eth0 port 53
[2021-04-30 02:52:53.419 10366M] listening on eth0(#2): fe80::8f55:177a:c4b2:5c00%eth0 port 53
[2021-04-30 02:52:53.419 10366M] listening on fdaa:bbcc:ddee:0:4f33:a079:263e:68d3 port 53
[2021-04-30 02:52:53.419 10366M] listening on eth0(#2): fdaa:bbcc:ddee:0:4f33:a079:263e:68d3 port 53
[2021-04-30 02:52:53.419 10366M] listening on 2a00:23c7:63ba:1600:399:5a1b:c304:d683 port 53
[2021-04-30 02:52:53.419 10366M] listening on eth0(#2): 2a00:23c7:63ba:1600:399:5a1b:c304:d683 port 53
[2021-04-30 02:52:53.420 10366M] listening on ::1 port 53
[2021-04-30 02:52:53.420 10366M] listening on lo(#1): ::1 port 53
[2021-04-30 02:53:43.261 744M] FTL branch: tweak/more_listening_logging
[2021-04-30 02:53:44.075 744M] listening on 10.100.0.1 port 53
[2021-04-30 02:53:44.075 744M] listening on wg0(#4): 10.100.0.1 port 53
[2021-04-30 02:53:44.075 744M] listening on 127.0.0.1 port 53
[2021-04-30 02:53:44.075 744M] listening on lo(#1): 127.0.0.1 port 53
[2021-04-30 02:53:44.076 744M] listening on fd08:4711::1 port 53
[2021-04-30 02:53:44.076 744M] listening on wg0(#4): fd08:4711::1 port 53
[2021-04-30 02:53:44.076 744M] listening on ::1 port 53
[2021-04-30 02:53:44.076 744M] listening on lo(#1): ::1 port 53
[2021-04-30 02:53:48.125 797M] listening on fe80::8f55:177a:c4b2:5c00%eth0 port 53
[2021-04-30 02:53:48.125 797M] listening on eth0(#2): fe80::8f55:177a:c4b2:5c00%eth0 port 53
[2021-04-30 02:53:51.959 797M] listening on 192.168.1.111 port 53
[2021-04-30 02:53:51.959 797M] listening on eth0(#2): 192.168.1.111 port 53
[2021-04-30 02:54:07.325 797M] listening on fdaa:bbcc:ddee:0:4f33:a079:263e:68d3 port 53
[2021-04-30 02:54:07.325 797M] listening on eth0(#2): fdaa:bbcc:ddee:0:4f33:a079:263e:68d3 port 53
[2021-04-30 02:54:07.325 797M] listening on 2a00:23c7:63ba:1600:399:5a1b:c304:d683 port 53
[2021-04-30 02:54:07.325 797M] listening on eth0(#2): 2a00:23c7:63ba:1600:399:5a1b:c304:d683 port 53
```

**Comment by dschaper** [comment]
`bind-dynamic` rings a bell to me, I've looked in the issues history and found only this:

https://github.com/pi-hole/pi-hole/issues/3682#issuecomment-673254788

and

https://github.com/pi-hole/FTL/issues/569

**Comment by DL6ER** [comment]
> I presume you wanted me to remove the delay?

Yes, it seems your output above already includes this.

It shows us that you interfaces `wg0` and `lo` are already up when the system starts but `eth0` comes up only around 3 seconds later (IPv4). The IPv6 part of `eth0` even comes up only 24 seconds after FTL started.

Well, interesting it works for you like this. It *should* have worked otherwise, too. I find it a bit puzzing why this is not the case - but the main achievement is that it is now working for you.

**Comment by benjaminbogdanovic** [comment]
Is there any other testing you would like to try out to help with your puzzlement?

**Comment by benjaminbogdanovic** [comment]
Thank you for you help on getting it to work for me.

Is there any other testing you would like to try out to help with your puzzlement?

**Comment by ve3** [comment]
How do I fix that?

**Comment by ve3** [comment]
No, I have UPS and all are up.
Re-install OS is bad option. 🤔
