### ISSUE TITLE
Google ads not blocked

### ISSUE THREAD

**Issue by ThatRaspberryPiGuy** [pi-hole/pi-hole#415]
##### Expected Behaviour:
Google double click ads are blocked.

##### Actual Behaviour:
Double click ads make it through

##### Steps to reproduce this issue:
Go to any site that has double click ads

**Comment by DonLexos** [comment]
Can you link to a page that has the ads that slip through? Are you sure your network uses the pi-hole as it's first DNS server?

**Comment by dan019** [comment]
Do you mean, for an example, http://speedtest.net

Have you read through my guide on the [forums](https://pi-hole.net/forums/topic/privoxy-and-pi-hole/)?

**Comment by DonLexos** [comment]
I do not see any google ads on speedtest.net, are you sure the system you experience this has the pi-hole set as dns?

**Comment by PromoFaux** [comment]
speedtest.net shows adchoices ads, atleast for me anyway.

**Comment by DonLexos** [comment]
On the main index page? I only run Pi-hole, no additional adblock and I don't see them. I run a vanilla installation (no extra lists).

**Comment by Mcat12** [comment]
I also saw what I thought to be an ad, but it actually was a mimic made to get around ad blockers. It is self hosted and just puts the buttons and ad choices icon in the right spots.

**Comment by akamel001** [comment]
Seeing the same issue just not on speedtest.net. 

http://ads-blocker.com/testing/

Looks like its related to https vs http?

**Comment by PromoFaux** [comment]
Do you have both `IPv4` and `IPv6` options enabled on pi-hole? It could be `IPv6` ads getting through...I'm not seeing ads on that page!

**Comment by akamel001** [comment]
@PromoFaux 

I'm using the docker container to run pihole. I looked at the container and it did bind to port 53 on a IPv6 address.

Actually never mind. I think i fixed the issue.  I didnt have my router configured to use the IPv6 of the container. Set up Ipv6 DNS on the router and works now. I dont see those adds on that page.

**Comment by PromoFaux** [comment]
@ThatRaspberryPiGuy Has any of this conversation helped? :)

**Comment by Mcat12** [comment]
Closing unless anything new comes up...
