### ISSUE TITLE
External link to docs is missing target="_blank"

### ISSUE THREAD

**Issue by stonecrusher** [pi-hole/pi-hole#4151]
Just for consistency, the link to the docs at the very bottom of the page is missing the `target="_blank"` attribute.
All the other external links have it.

### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8 (Latest: v5.8.1)

### Platform
Firefox 88.0

### Expected behavior
open new tab on click

### Actual behavior / bug
current page is overwritten, opens in same tab

### Steps to reproduce
1. Open pi.hole in your browser
2. If you're not on the latest version already, click on "To install updates, run [pihole -up](https://docs.pi-hole.net/main/update/)."

**Comment by stonecrusher** [comment]
No, it should be down where the red arrow is.
You need an outdated version and my PH is updated already, so it doesn't appear.
![2021-04-30 21_35_23-](https://user-images.githubusercontent.com/1388389/116746046-46d2b980-a9fc-11eb-9809-46987cf0262a.png)

**Comment by yubiuser** [comment]
Ok, found it. It was introduced by https://github.com/pi-hole/AdminLTE/pull/1749 and is fixed by https://github.com/pi-hole/AdminLTE/pull/1794

**Comment by yubiuser** [comment]
Added the same PR to the current `devel` https://github.com/pi-hole/AdminLTE/pull/1884

**Comment by yubiuser** [comment]
Fixed:
https://github.com/pi-hole/AdminLTE/releases/tag/v5.7
