### ISSUE TITLE
List dead? (https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/mobile.txt)

### ISSUE THREAD

**Issue by 7wells** [pi-hole/pi-hole#4155]
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
Debian stretch (VM on Synology server)

### Expected behavior
Upgrading gravity should be executed without any dead lists. I know that this is not a problem of Pi-Hole itself. Hopefully, this is nevertheless the right place to mention this problem and that there is a solution. Maybe this source (see next part) should simply be deleted?

### Actual behavior / bug
When upgrading gravity, I get this (the others are ok):

[i] Target: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/mobile.txt
[✗] Status: Not found
[✗] List download failed: no cached list available

Indeed, the link is dead.

### Steps to reproduce
pihole -g

## Debug Token
NA

### Screenshots
NA

### Additional context
NA

**Comment by dschaper** [comment]
> Upgrading gravity should be executed without any dead lists

I guess that depends on how you define "dead". Is it just one time getting a 404, or repeatedly getting 404s over multiple weeks?


> I know that this is not a problem of Pi-Hole itself

I agree with this statement. 


> Maybe this source (see next part) should simply be deleted?

That would be done at the same webpage that was used to add the list in the first place.

**Comment by 7wells** [comment]
Yes, sorry, it was a list I had added myself. 😊 Sorry that I had not seen the obvious!
