### ISSUE TITLE
Recent Change to PiHole (default blacklist?) is Breaking Video Playback

### ISSUE THREAD

**Issue by sproggit** [pi-hole/pi-hole#4156]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Raspbian (not entirely sure which version, but running 5.10.17-v7l+ and ran "apt-get upgrade" and "apt-get dist-upgrade" and re-tested to confirm no change in issue... 

- Platform:  Raspberry Pi (4B/4Gb)

### Expected behavior
Navigating to https://www.msnbc.com/ and attempting to play back a video would/should result in the video starting and playing back without issue. 

### Actual behavior / bug
Up until a period of time covering no more than the last 7-10 days (precise time not known), an attempt to play back a video on the site https://www.msnbc.com/ would work perfectly - using Safari on iPad, Firefox 64-bit on Windows 10 and on Mint 20.1. 
At some point in the last 7-10 days, with no manual intervention, video playback has stopped. On-screen the view shows the MSNBC logo in "hourglass" mode, as if it is waiting for a response from a server. This fault/non-playback is tested and confirmed on iPad, Windows and Linux. 

Logging in to PiHole via the web interface, selecting "Settings" and then "Flush Logs" allows for a complete reset of the environment. Re-attempting to view an MSNBC hosted video and then refreshing the PiHole log shows two blocked domains:-

assets.adobedtm.com
snappytvpoc-vh.akamaihd.com

A single playback attempt generates 2 hits and 2 blocks for each domain. 

### Steps to reproduce
1. Navigate to https://www.msnbc.com/
2. Attempt to watch any of the archived video segments
3. Observe that the playback does not start and does not progress past the "MSNBC HourGlass" 

4. Go to iPad Settings, go to Wi-Fi options and locally over-ride DNS (my local network firewall router provides my local pair of PiHole DNS Servers as the default DNS service, so to eliminate PiHole from the environment manually override the default settings and direct the iPad to use Google's Default DNS Servers (8.8.8.8 and 8.8.4.4). 
5. Re-Test playback and observe that videos play normally.
6. Return to iPad settings, revert to local PiHole DNS and re-test
7. Observe that playback fails once more

## Debug Token

- URL:  https://tricorder.pi-hole.net/k6gs37cu6x

### Screenshots

Not Applicable

### Additional context

Curiously, this issue appears to only impact MSNBC.com, so I am not ruling out that the site itself is doing "something silly". Other web sites, including youtube.com and cnn.com continue to offer playback without issues.  So far, the only impacted site appears to be MSNBC. 

Entirely happy to provide additional data and/or experiment if that would assist.

**Comment by dschaper** [comment]
This is a configuration issue and not a bug report so please use the links provided for configuration issues, our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by dschaper** [comment]
```plain
 Exact match for assets.adobedtm.com found in:
  - http://sysctl.org/cameleon/hosts 
```
No idea if this is the domain that is causing the issues but try disabling that list.

Please follow up with an issue on Discourse at the link provided.
