### ISSUE TITLE
Please add Debian 11 as suported os

### ISSUE THREAD

**Issue by Herr-Bertt** [pi-hole/pi-hole#4157]
Please add Debian 11 as suported os

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by dschaper** [comment]
Debian 11 doesn't exist yet. Debian Testing (Codename Bullseye) does but it has not been given a release number. There's nothing we can add that would make Debian 11 a supported OS because there currently is no Debian 11.
