### ISSUE TITLE
Docker container - not starting pihole

### ISSUE THREAD

**Issue by awaldeck** [pi-hole/pi-hole#4160]
Hi,

My pihole container is not starting up, other containers working fine. Failing to startup with sudoers permission denied errors, seems to be in the container itself as I have tried using persistent volumes and without, same error is achieved in both scenario's
Tried clearing all directories for a fresh install but same error again.

This was working fine previously but mysteriously stopped working.

```
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal
```.

**Comment by dschaper** [comment]
Please open an issue and fill out the requested information in the template at our Docker repo at https://github.com/pi-hole/docker-pi-hole

Thanks.
