### ISSUE TITLE
Conf-Datei new default port for lighttpd

### ISSUE THREAD

**Issue by UN-pi** [pi-hole/pi-hole#4163]
I am running a smal webserver on the pi and also pihole.
That works for me very good.
But after each pihole-update I have to configure the ligthtpd.conf with a new default port.
While apache2 is running on port 80 lighttpd can't run on the same port. So I choosed 8080.
That is working.
Is it possible to define an default port for lighttpd in the config-file with a new variable?
That would be very nice. Thanks.

**Comment by jfb-pihole** [comment]
https://discourse.pi-hole.net/t/lighttpd-daemon-wont-start/44985/12

**Comment by UN-pi** [comment]
Thanks. It works when editing the external.conf-file with the above solution.
