### ISSUE TITLE
Latest update breaks FTL and web interface

### ISSUE THREAD

**Issue by Hminteresting** [pi-hole/pi-hole#4165]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

Eveyrhting was working as normal prior to update. 

### Actual behavior / bug

All devices on network lose connectivity every 4 hours. Logging into the web UI states "lost connection to API"
I've been using the command "service pihole-FTL restart" to get everything working again. This seems to reset all query logs and the web UI no longer shows any historical data. 

Also click the last 3 tabs on the settings page no longer does anything. 

### Steps to reproduce

Update to latest FTL and web UI version

## Debug Token

- URL:   https://tricorder.pi-hole.net/7ak1hqc6mc

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
You have misconfigured items in your regex.

```plain
   40       3        1  0             https://hosts-file.net/grm.txt https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHosts  2020-05-18 13:35:59  2020-05-18 13:35:59  Migrated from /etc/pihole/regex.list              
   44       3        1  0             (\.|^)https://googleads\.g\.doubleclick\.net/aclk?sa=l&ai=CdoG2XsbgXuqiBI_UbKqEgJAJicnA1V3FtZzJvQsUE  2020-06-10 12:40:55  2020-06-10 12:40:55                                                    
   45       3        1  0             (\.|^)https://googleads\.g\.doubleclick\.net/aclk?sa=l&ai=CT03F2cbgXo_yOYTYb7rmhqAPw53rtV3CorfJ-gu_4  2020-06-10 12:41:38  2020-06-10 12:41:38                     

*** [ DIAGNOSING ]: Pi-hole diagnosis messages
   id    timestamp            type                  message                                                       blob1                 blob2                 blob3                 blob4                 blob5               
   ----  -------------------  --------------------  ------------------------------------------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
   18    2021-04-25 03:22:42  REGEX                 Out of memory                                                 blacklist             https://hosts-file.n  0                                           

```

**Comment by dschaper** [comment]
I'm unable to see any of the logs, looks like the files don't exist or there's something preventing them from being created.
```plain

*** [ DIAGNOSING ]: contents of /var/log/lighttpd

-rw-r--r-- 1 www-data www-data 0 May  9 15:58 /var/log/lighttpd/error.log
   -----head of error.log------

   -----tail of error.log------

*** [ DIAGNOSING ]: contents of /var/log

-rw-r--r-- 1 pihole pihole 0 May  9 15:58 /var/log/pihole-FTL.log
   -----head of pihole-FTL.log------

   -----tail of pihole-FTL.log------
```

**Comment by Hminteresting** [comment]
weird. Actually when I click the logs in the web UI those are empty too. Is there any way i can check if its making logs?

**Comment by dschaper** [comment]
Are you using some kind of ram log process? Does `/var/log` really exist? The files look like they are there but they are empty. 

The fact that both `lighttpd` and `pihole-FTL` show that same thing tells me that it's not Pi-hole, it's the OS.

**Comment by Hminteresting** [comment]
I did move the query logs to an SSD connected to the pi ages ago. Would this have done something to the FTL and error logs too?

**Comment by dschaper** [comment]
I don't see anything in your configuration files that asks to move the files. 

Did you do that manually or set up some kind of symlink?

Since this isn't a bug in Pi-hole but instead is a configuration issue please use https://discourse.pi-hole.net so we can help you.

**Comment by hadalin** [comment]
>Also click the last 3 tabs on the settings page no longer does anything.

Same here

![tabs](https://github.com/pi-hole/pi-hole/assets/1746370/e575c718-24fd-4cc9-8f7d-ae85751e29a2)

**Comment by rdwebdesign** [comment]
@hadalin 
This issue was closed 2 years ago. 

Also, the original problem was a configuration issue, not a bug.

Please, open new topic at our [Discourse Forum](https://discourse.pi-hole.net/) explaining you issue and add a debug token.

As a free open-source project run by volunteers we have very limited resources.
Thank you for your understanding.
