### ISSUE TITLE
DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by slhale** [pi-hole/pi-hole#4167]
### Versions

- Pi-hole:   v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Raspberry Pi OS

- Platform:  Raspberry Pi Zero W

### Expected behavior

Update the pihole gravity.

### Actual behavior / bug

```
$ pihole -g
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
```
It tries to connect for 120 seconds before the second line appears. 

Updating the gravity from the UI just silently fails(/loads forever) btw.

Note that the pi is running this whole time and does seem to be blocking ads. 
```
$ pihole status
  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

### Steps to reproduce

1. install raspberry pi os
2. apt full upgrade
3. install pihole via the bash script
4. ads are indeed being blocked
5. use GUI to add new adlists
6. click `update` in /admin/gravity.php
7. wait forever
8. ssh into pihole
9. run pihole -g
10. wait forever

## Debug Token

- URL:  

```
[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, falling back to netcat for transmission.
nc: getaddrinfo for host "tricorder.pi-hole.net" port 9999: Temporary failure in name resolution
[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log
```

**Comment by dschaper** [comment]
>     5\. use GUI to add new adlists

How have you added the lists, how many lists are you adding? What is the output from the streaming updates on the webpage?

> nc: getaddrinfo for host "tricorder.pi-hole.net" port 9999: Temporary failure in name resolution

What is your `/etc/resolv.conf` contents showing for `nameserver`?

**Comment by slhale** [comment]
I disabled all the new lists and it still fails. 

But I just took them from https://firebog.net/:
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Admiral.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://v.firebog.net/hosts/Easylist.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

For the other q:
```
$ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 208.67.222.222
nameserver 208.67.220.220
```
I chose openDNS instead of google at setup

**Comment by slhale** [comment]
oh, there were no streaming updates on the webpage when I tried it. It just said don't navigate away and nothing else

**Comment by dschaper** [comment]
What does `dig tricorder.pi-hole.net` show on the Pi-hole terminal?

**Comment by slhale** [comment]
```
$ dig tricorder.pi-hole.net

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> tricorder.pi-hole.net
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by dschaper** [comment]
Does the Pi-hole have network connectivity to the internet?

`ping 208.67.222.222`
`dig tricorder.pi-hole.net @208.67.222.222`

**Comment by slhale** [comment]
Wow now I am confused. I downloaded the install script from the internet so I assumed it was connected, but...

```
$ ping 208.67.222.222
PING 208.67.222.222 (208.67.222.222) 56(84) bytes of data.
^C
--- 208.67.222.222 ping statistics ---
53 packets transmitted, 0 received, 100% packet loss, time 166ms
```
```
$  dig tricorder.pi-hole.net @208.67.222.222

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> tricorder.pi-hole.net @208.67.222.222
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by dschaper** [comment]
How are you handling the IP address for the Pi-hole? Is it configured via a DHCP lease or did you set a static IP address?

Does `/etc/dhcpcd.conf` look like it should for your network?

**Comment by slhale** [comment]
So my router has confusing settings but I think so? 

I have `static ip_address=192.168.0.161/24` in `/etc/dhcpcd.conf` and in my router settings `Primary DNS Server: 192.168.0.161`

**Comment by dschaper** [comment]
And what does `ip addr list` show as the IP address for the network interface?

**Comment by slhale** [comment]
```
$ ip addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:73:2f:81 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.161/24 brd 192.168.0.255 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::fe07:7361:d744:4e65/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by dschaper** [comment]
Okay, so you have `192.168.0.161` as the IP address. (These are private address ranges so there's no need to obfuscate them.)

Is the router at `192.168.0.1`? Can you ping that address? Can you ping `1.1.1.1` or `8.8.8.8` or any IP that is not on your LAN?

**Comment by slhale** [comment]
The bottom of the physical router says it should be at `192.168.0.1`
I can't seem to ping it or the others
```
$ ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
^C
--- 192.168.0.1 ping statistics ---
78 packets transmitted, 0 received, 100% packet loss, time 141ms
```
If it can't ping the router on the local network how is it even blocking ads? 🤔

**Comment by slhale** [comment]
ok maybe ad blocking isn't working any more 
the last log I see on http://192.168.0.161/admin/queries.php is from `2021-05-12 18:00:55 `

**Comment by dschaper** [comment]
Have you tried turning it off and on again?

**Comment by slhale** [comment]
yes

**Comment by dschaper** [comment]
Okay, what is the full configuration stanza from `/etc/dhcpcd.conf` and what is the default route shown with `ip route`

**Comment by slhale** [comment]
```
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# Most distributions have NTP support.
#option ntp_servers

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
slaac private

# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.23/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0
interface wlan0
        static ip_address=192.168.0.161/24
        static routers=192.168.0.1
        static domain_name_servers=208.67.222.222 208.67.220.220
```


```
$ ip route
default via 192.168.0.1 dev wlan0 src 192.168.0.161 metric 302 
192.168.0.0/24 dev wlan0 proto dhcp scope link src 192.168.0.161 metric 302 
```

**Comment by dschaper** [comment]
Okay, I don't know why you are unable to use the network. That's something that is on the OS and not a Pi-hole issue.

The only other thing I can think of is that it's just not connected to your WiFi network.

**Comment by slhale** [comment]
Ok. Thank you for the help!

It does seem weird that the issue with connecting to the internet only started once I installed pi-hole though 🤔

**Comment by dschaper** [comment]
Try commenting out that entire `interface wlan0` section and the `static` lines then reboot the Pi to see if the device will get an IP address from the router's DHCP server. If it does then check for internet connectivity. If that works, then run `ip addr list` and `ip route` and show them here.

**Comment by 00lex** [comment]
for me this version (Pi-hole v5.3.1  Web Interface v5.5  FTL v5.8.1) does not work. 
two times a day I have to restart dns resolver by "pihole restartdns" 
i recovered my system to the previous version where everything works. 
i´m surprised there is no fix since 4 weeks

**Comment by dschaper** [comment]
My crystal ball broke so you'll have to fill me in with details besides "It doesn't work".

**Comment by 00lex** [comment]
nothing is resolved. neither internally, nor externally. 
at the moment i really don't have time for details so it was easier for me to just restore the system backup. 
i'm just hoping others will escalate it. yes I know what you think now but I just do not have time and patience for this

**Comment by dschaper** [comment]
Okay, well when you have time to provide information to diagnose it then we can see where the issue is. This issue that you've attached to is going to be closed since it was determined that the issue was with networking and not with Pi-hole.

**Comment by oditynet** [comment]
answer: "docker network connect pi-hole_default pihole " or enter a command "docker network connect" and press key Enter.select your network and container name (pihole default)
