### ISSUE TITLE
What is the Key for selecting while setup?

### ISSUE THREAD

**Issue by picusc** [pi-hole/pi-hole#417]
##### Expected Behaviour:
I pressed down key and pressed the Enter key to select ipv6 but it took me to the next page without selecting ipv6.

What key to press for selecting? Enter is not working.

**Comment by PromoFaux** [comment]
Hi there,  space bar is what you need  :) 

We should probably change that page to mention that..

**Comment by picusc** [comment]
Thanks, it worked. And what an awesome piece of utility pi-hole is. Thanks to everyone that contributes to it.

**Comment by PromoFaux** [comment]
You're welcome, thanks for trying us out!
