### ISSUE TITLE
Whitelist regex not being honored

### ISSUE THREAD

**Issue by Guyverix** [pi-hole/pi-hole#4170]
### Versions
pihole -v
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

- Platform:  
KVM

### Expected behavior
DNS resolution on URL since it is whitelisted:
 
https://click.redditmail.com/CL0/https:%2F%2Fwww.reddit.com%2Fr%2Fpics%2Fcomments%2Fncf24p%2Fi_ordered_3_hard_drives_from_amazon_and_they_sent%2F%3F$deep_link=true%26correlation_id=ebb33ebb-cf4d-4338-ab99-77fdc96c5071%26post_fullname=t3_ncf24p%26post_index=5%26ref=email_digest%26ref_campaign=email_digest%26ref_source=email%26utm_content=post_image/1/010001796fe3f8ac-f8b75bbf-c1e0-41f0-b22f-18dc4fd51cea-000000/BtfVlW_lLgrtfKL61e8xDsvKdF1mNyatOMQPX-1LCWM=193

### Actual behavior / bug

No DNS resolution until I bypass Pi-hole

### Steps to reproduce

1. Add whitelist values for reddit email links
2. Paste Link above.

## Debug Token

- URL:  

https://tricorder.pi-hole.net/jkoqmv2jvi

### Screenshots

![Selection_022](https://user-images.githubusercontent.com/1209259/118372451-8ce45d00-b566-11eb-82c2-44aa0ab626f9.png)

### Additional context

Sadly DNS works as expected when I disable Pi-hole.

**Comment by yubiuser** [comment]
Try changing the type of `click.redditmail.com` to exact whitelist.

**Comment by Guyverix** [comment]
Done.  No change in behavior

**Comment by yubiuser** [comment]
Do you see the query in the query log as being blocked?

**Comment by Guyverix** [comment]
Okay, that makes this even more confusing..  It is showing that it forwarded.  I changed the DNS server from Level3 to the openDNS and it has the same behavior.

Status | Reply | Action
-- | -- | --
2021-05-16 11:20:34 | AAAA | click.redditmail.com | chubbard-laptop.iwillfearnoevil.com | OK (forwarded to a.resolvers.level3.net#53) | CNAME (45.2ms) |  

Think I found the issue.  It is CNAMED to something oddball..

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;click.redditmail.com.		IN	A

;; ANSWER SECTION:
click.redditmail.com.	276	IN	CNAME	thirdparty.bnc.lt.
thirdparty.bnc.lt.	2	IN	A	0.0.0.0

;; Query time: 19 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun May 16 11:25:05 PDT 2021
;; MSG SIZE  rcvd: 96

**Comment by Guyverix** [comment]
Confirmed that when I whitelisted that thirdparty.bnc.lt domain, everything started working properly.

Sorry for the fire-drill, and thank you for suggesting where to look for additional details.

**Comment by dschaper** [comment]
You should be able to whitelist the initial domain `click.redditmail.com` and that's it. `pihole-FTL` is written to see that initial domain and stop processing any further. The CNAME should not have returned 0.0.0.0. What server is at `SERVER: 127.0.0.53#53(127.0.0.53)` ?

**Comment by dschaper** [comment]
The problem with whitelisting the `bnc.lt` domain is that now ANY domain that points to that as a CNAME is now allowed. This usually isn't what users want.

**Comment by dschaper** [comment]
Ah, `systemd-resolved`....

Explanation:
https://moss.sh/name-resolution-issue-systemd-resolved/

How to kill it.
https://askubuntu.com/a/907249

**Comment by Guyverix** [comment]
I quit killing the damn thing off since it is not going anywhere in the future.  Learn to love the plague that is systemd.  Simply editing /etc/systemd/resolvd.conf is a simple enough matter, then I can override it by manual edits to /etc/resolv.conf when I need to bypass pi-hole

**Comment by Guyverix** [comment]
> The problem with whitelisting the `bnc.lt` domain is that now ANY domain that points to that as a CNAME is now allowed. This usually isn't what users want.

Agreed, however I will take an annoying solution over no solution..

**Comment by dschaper** [comment]
Okay, when you get tired of being annoyed you can come back and we can see what the real solution is.
