### ISSUE TITLE
Blocklist domains resolve successfully

### ISSUE THREAD

**Issue by chuckette** [pi-hole/pi-hole#4173]
### Versions
- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
- OS and version:  Ubuntu 20.04.2 LTS
- Platform:  Home server

### Expected behavior

All domains on the blocklist are blocked.

### Actual behavior / bug

Not all domains on the blocklist are blocked.

### Steps to reproduce

1. Add blocklists
2. Update gravity
3. Verify domain name was added to the blocklist with pihole -q
4. Successfully resolve domain name with dig/drill

## Debug Token

- URL:  https://tricorder.pi-hole.net/v94mcc16b6

### Additional context

I noticed this after going through my blocklists and removing a couple that no longer existed. After removing those blocklists and updating gravity, some ads started showing up despite the relevant URLs being on multiple of my blocklists. Adding a domain to the blacklist causes it to be blocked properly, even if it's already on several blocklists. I have been unable to determine any commonality between domains on the blocklists that are blocked and ones that are not.

**Comment by dschaper** [comment]
Can you provide the `dig` output showing the domain queried, the response IP and the IP address of the server used?

**Comment by dschaper** [comment]
Also, you've created a handful of groups with domains and lists but you don't have any clients assigned to any of the groups to be affected by the domains or lists.

**Comment by chuckette** [comment]
Output of `dig` off of the server:
```
dig www.strangeletter.net

; <<>> DiG 9.16.1-Ubuntu <<>> www.strangeletter.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58864
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.strangeletter.net.         IN      A

;; ANSWER SECTION:
www.strangeletter.net.  609     IN      A       91.195.240.87

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun May 16 15:16:52 CDT 2021
;; MSG SIZE  rcvd: 66
```
And `drill` off of my desktop:
```
drill strangeletter.net
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 26267
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; strangeletter.net.   IN      A

;; ANSWER SECTION:
strangeletter.net.      1800    IN      A       91.195.240.87

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 80 msec
;; SERVER: 10.0.0.3
;; WHEN: Sun May 16 15:04:34 2021
;; MSG SIZE  rcvd: 51
```

> Also, you've created a handful of groups with domains and lists but you don't have any clients assigned to any of the groups to be affected by the domains or lists.

I've never needed to do this before, and still don't for many domains on the blocklist. If I look up googleadservices.com for example:
```
drill googleadservices.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 2395
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; googleadservices.com.        IN      A

;; ANSWER SECTION:
googleadservices.com.   2       IN      A       0.0.0.0

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 10.0.0.3
;; WHEN: Sun May 16 15:19:21 2021
;; MSG SIZE  rcvd: 54
```

**Comment by dschaper** [comment]
> SERVER: 127.0.0.53#53(127.0.0.53)

That's not Pi-hole. 

`strangeletter.net. ` What list has that domain on it?

`googleadservices.com.` that's on the default list that is assigned to group 0 which is where every client that is not assigned to a group lives. So, in your setup every client is in group 0. Any list or domain that is assigned to any group that is not 0 will not apply to any client.

**Comment by dschaper** [comment]
```plain
   107         1  0             https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts                                      2021-05-16 13:09:26  2021-05-16 14:28:31                                                    
   108         1  0             https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt                                      2021-05-16 13:09:26  2021-05-16 14:41:07
```

Those are the only lists that are actually being used. All the other lists are being applied to groups that have no clients associated with them. Most of your manual blacklist entries are for group 0 but that's about it.

**Comment by chuckette** [comment]
> That's not Pi-hole.

I should clarify this - the `dig` was done on the server running the pihole, so the pihole was localhost.

> All the other lists are being applied to groups that have no clients associated with them.

I hadn't realized this was required - adding the subnet to all the groups has blocked the domains I was using for testing. Thank you! Closing as this was user error.

**Comment by dschaper** [comment]
`127.0.0.53` is actually `systemd-resolved` that Ubuntu has added. 

https://moss.sh/name-resolution-issue-systemd-resolved/

**Comment by dschaper** [comment]
> I should clarify this - the `dig` was done on the server running the pihole, so the pihole was localhost.

I should have added that it was querying `systemd-resolved` on the server instead of actually querying Pi-hole at `127.0.0.1`.
