### ISSUE TITLE
Update to FTL version is v5.8.1 - Aborting installation: iproute2 and iproute packages were not found in APT repository

### ISSUE THREAD

**Issue by Raarrrinator** [pi-hole/pi-hole#4179]
Hi all,

When trying to update using pihole -up I get this error:

_Aborting installation: iproute2 and iproute packages were not found in APT repository_

Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8 (Latest: v5.8.1)

Only the FTL version is out of date.

**Comment by jfb-pihole** [comment]
Please generate a debug log, upload it when prompted and post the token here.

**Comment by Raarrrinator** [comment]
> Please generate a debug log, upload it when prompted and post the token here.

https://tricorder.pi-hole.net/ecxmlo1zwh

here you go!

**Comment by jfb-pihole** [comment]
Output of `sudo apt update` please.

**Comment by Raarrrinator** [comment]
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.7 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [376 kB]
Fetched 423 kB in 1s (324 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
27 packages can be upgraded. Run 'apt list --upgradable' to see them.

**Comment by Raarrrinator** [comment]
apt-utils/stable 1.8.2.3 armhf [upgradable from: 1.8.2.2]
apt/stable 1.8.2.3 armhf [upgradable from: 1.8.2.2]
bind9-host/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
dnsutils/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libapt-inst2.0/stable 1.8.2.3 armhf [upgradable from: 1.8.2.2]
libapt-pkg5.0/stable 1.8.2.3 armhf [upgradable from: 1.8.2.2]
libbind9-161/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libdns-export1104/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libdns1104/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libirs161/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libisc-export1100/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libisc1100/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libisccc161/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libisccfg163/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
liblwres161/stable 1:9.11.5.P4+dfsg-5.1+deb10u5 armhf [upgradable from: 1:9.11.5.P4+dfsg-5.1+deb10u3]
libraspberrypi-bin/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
libraspberrypi-dev/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
libraspberrypi-doc/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
libraspberrypi0/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
libx11-6/stable 2:1.6.7-1+deb10u2 armhf [upgradable from: 2:1.6.7-1+deb10u1]
libx11-data/stable 2:1.6.7-1+deb10u2 all [upgradable from: 2:1.6.7-1+deb10u1]
linux-libc-dev/testing 1:1.20210430-2 armhf [upgradable from: 4.18.20-2+rpi1]
pi-bluetooth/testing 0.1.17 all [upgradable from: 0.1.15]
raspberrypi-bootloader/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
raspberrypi-kernel/testing 1:1.20210430-2 armhf [upgradable from: 1.20210303-1]
rpi-eeprom/testing 12.4-1 armhf [upgradable from: 12.1-1]
wpasupplicant/stable 2:2.7+git20190128+0c1e29f-6+deb10u3 armhf [upgradable from: 2:2.7+git20190128+0c1e29f-6+deb10u2]

**Comment by jfb-pihole** [comment]
Run `sudo apt upgrade` and install them all.

**Comment by Raarrrinator** [comment]
Running pihole -up after sudo apt upgrade fixed it!

Thanks for the support :)
