### ISSUE TITLE
Update: /usr/bin/pihole-FTL: Operation not permitted

### ISSUE THREAD

**Issue by boehser-enkel** [pi-hole/pi-hole#4180]
### Versions
pi-hole -v:
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
/opt/pihole/version.sh: line 19: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/version.sh: line 122: /usr/bin/pihole-FTL: Operation not permitted
  Latest FTL version is v5.8.1

### Platform

- OS and version:  Raspbian GNU/Linux 10 \n \l

- Platform:   Raspberry Pi 4

### Expected behavior

Update FTL (everything else updated)

### Actual behavior / bug

/usr/bin/pihole-FTL: Operation not permitted

### Steps to reproduce

sudo pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.network/216joap4uj

**Comment by jfb-pihole** [comment]
Please generate a debug log, upload it when prompted and post the token here.

**Comment by yubiuser** [comment]
@boehser-enkel 
Any news on that? Does the issue still persist?

**Comment by boehser-enkel** [comment]
> @boehser-enkel
> Any news on that? Does the issue still persist?

**Comment by boehser-enkel** [comment]
Problem does not exist anymore
