### ISSUE TITLE
Web Interfaces have problem

### ISSUE THREAD

**Issue by vinhlilo90** [pi-hole/pi-hole#4182]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
 
- OS and version:  Debian10

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
I install Pi-Hole and the web interfaces have a problem 

## Debug Token

- URL:  https://tricorder.pi-hole.net/kfwo8qae4i

### Screenshots
![image](https://user-images.githubusercontent.com/61305337/119942497-c2b21a00-bf46-11eb-97fc-e4d4f1aea72f.png)

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Nitair** [comment]
Looks like the webserver has no PHP module enabled. How did you install pihole?

**Comment by PromoFaux** [comment]
From the debug log

```
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
```

We don't install apache2 by default, so if you're trying to set up with apache, see here:

https://discourse.pi-hole.net/tag/apache
