### ISSUE TITLE
Admin page loading only text

### ISSUE THREAD

**Issue by GGratzie** [pi-hole/pi-hole#4183]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  

- Platform: Raspberry pi model B with RaspbianOS 

### Expected behavior

web page loads with full functionality graphing etc,,, 

### Actual behavior / bug

admin page is only loading text for whatever reason, i installed and setup pihole yesterday
and it was working fine but when i came home today the page was broken and not isplaying graphs, ui etc

## Debug Token

- URL:  https://tricorder.pi-hole.net/r331psd7g4
-

**Comment by pablocarreraest** [comment]
you need to restart pihole.. this problem is because the web page don't restart well I solve with `pigole -g` or `pihole -up`
then the website go up a running

**Comment by poppm1408** [comment]
I had the same issue yesterday. I just run apache2 while installing pi-hole. It installed lighttpd as planed but can't start it.
The page IP/admin was reachable and showes text only. I deleted apache2 and started lighttpd the issue was gone.
So check about other port 80 listening programs or/and check the cgi file/folder access of your webserver maybe helps.

Kind regards
michael

**Comment by pablocarreraest** [comment]
also if you are in centos or something with  SELinux states.

You need to put SELinux to permissive with:
```
sudo setenforce Permissive
```
or something more permanent:
```
vi /etc/selinux/config
```
change to:
```
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - No SELinux policy is loaded.
SELINUX=permissive
# SELINUXTYPE= can take one of these two values:
#       targeted - Targeted processes are protected,
#       mls - Multi Level Security protection.
SELINUXTYPE=targeted
```
then reboot

**Comment by dschaper** [comment]
Is this still an issue? Please provide a new debug token since the logs expire after 48 hours.
