### ISSUE TITLE
no DNS resolution from clients until restart pihole-ftl

### ISSUE THREAD

**Issue by matsonfamily** [pi-hole/pi-hole#4184]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Debian 10 (Raspberry Pi OS)
- Platform:  Raspberry Pi 4 Model B Rev 1.4 8GB

### Expected behavior
- DNS requests from clients answered after reboot, or an error in the logs

### Actual behavior / bug
- clients cannot resolve names like google.com, but can still route (e.g.: ping 8.8.8.8)
- FTL log looks OK, and service says OK, but everything is back to normal after sudo service pihole-FTL restart

### Steps to reproduce
- login to my pihole
- sudo shutdown -r 
- after reboot, no DNS until I restart FTL

## Debug Token

- URL:  
https://tricorder.pi-hole.net/mkxo1r57rt

-->

### Additional context
- can't seem to find any errors in my logs
- my raspberry pi 4 is also running pivpn (wireguard) service
-- /etc/dnsmasq.d/ contains 2 files, with the 2nd being a pivpn file that links to two wireguard client ip addresses
- seems similar to https://github.com/pi-hole/pi-hole/issues/4148 (not sure how to determine)
-- i have not tried putting a delay in /etc/pihole/pihole-FTL.conf (DELAY_STARTUP=10 ?)
- ipv6 is turned off on my router, and my devices that allow it turned off

**Comment by matsonfamily** [comment]
per a reddit conversation, i put in a delay of 10sec and it's now resolved, so i'll close the ticket.  it seems that the pivpn project (or maybe the pihole project?) needs to change the order of services, since this is affecting many people.

https://www.reddit.com/r/pihole/comments/np8oxh/pivpnwireguard_breaks_pihole_on_reboot_rebuild/h0464d6/

**Comment by jfb-pihole** [comment]
"or maybe the pihole project?"

I don't think that is the correct solution.

**Comment by dschaper** [comment]
https://github.com/pivpn/pivpn/issues/946

**Comment by matsonfamily** [comment]
it seems from piVPN's 946 & 1013, that you can just delete/rename the `/etc/dnsmasq.d/02-pivpn.conf` with no repercussions.  

Trying now... renamed, sudo pihole restartdns, connect to external network (hotspot), sudo wg-quick up wg0... seems to work.  tried browsing www = OK, browsed to internal pihole admin site = OK.  Thanks!  I guess I should ask the PiVPN folk what the purpose of the [now disabled] `/etc/dnsmasq.d/02-pivpn.conf` file...

https://github.com/pivpn/pivpn/issues/946
https://github.com/pivpn/pivpn/issues/1013

**Comment by dschaper** [comment]
From what I remember there is no upgrade or update for PiVPN. So there's no process to remove outdated files or configurations.
