### ISSUE TITLE
Strange Issues With Pihole

### ISSUE THREAD

**Issue by doobersn** [pi-hole/pi-hole#4186]
### Versions
Most recent version

### Platform
dietpi

### Expected behavior

for pihole to work

### Actual behavior / bug

I get this notification when checking queries: `DataTables warning: table id=all-queries - Tried 100 times to connect to FTL server, but never got proper reply. Please check Port and logs!` and on the dashboard it flashes undefined % for percentage blocked

### Steps to reproduce

Click on queries, just look at dashboard

#### Debug token

https://tricorder.pi-hole.net/l39p5i0dih

#### Additional info

I did restartdns and that fixed it for a while

**Comment by dschaper** [comment]
How did you install Pi-hole? Via our install script or via `dietpi-software`?

**Comment by dschaper** [comment]
And can you please run `pihole -d` again, the token you upload expired 48 hours after upload and we've gone past that window.

**Comment by doobersn** [comment]
> How did you install Pi-hole? Via our install script or via `dietpi-software`?

I installed it via your script. Here is the new debug token: `https://tricorder.pi-hole.net/67h7vgj0zz`. However, I did `restartdns` either yesterday or the day before and it's working fine now so I hope the debug log shows the issue. Thanks a ton!

**Comment by dschaper** [comment]
The log seems okay for the most part. There is an issue with the logs for the daemons used, they appear empty:

```plain
*** [ DIAGNOSING ]: contents of /var/log/lighttpd

-rw-r--r-- 1 www-data www-data 0 May 29 21:17 /var/log/lighttpd/error.log
   -----head of error.log------

   -----tail of error.log------

*** [ DIAGNOSING ]: contents of /var/log

-rw-r--r-- 1 pihole pihole 0 Jun  3 19:17 /var/log/pihole-FTL.log
   -----head of pihole-FTL.log------

   -----tail of pihole-FTL.log------

```

**Comment by doobersn** [comment]
> The log seems okay for the most part. There is an issue with the logs for the daemons used, they appear empty:
> 
> ```
> *** [ DIAGNOSING ]: contents of /var/log/lighttpd
> 
> -rw-r--r-- 1 www-data www-data 0 May 29 21:17 /var/log/lighttpd/error.log
>    -----head of error.log------
> 
>    -----tail of error.log------
> 
> *** [ DIAGNOSING ]: contents of /var/log
> 
> -rw-r--r-- 1 pihole pihole 0 Jun  3 19:17 /var/log/pihole-FTL.log
>    -----head of pihole-FTL.log------
> 
>    -----tail of pihole-FTL.log------
> ```

I was afraid that might be the case! I'll update the next time it happens instead of doing `restartdns` to fix it. Thanks a ton for taking the time to help me.

**Comment by dschaper** [comment]
You'll need to fix what ever is preventing the logs from being filled otherwise there won't be much we can suggest as the error investigation will need those logs contents.

**Comment by doobersn** [comment]
> You'll need to fix what ever is preventing the logs from being filled otherwise there won't be much we can suggest as the error investigation will need those logs contents.

Oh, ok, thanks! I'm a little unsure how to do this. Should I just run `pinhole -r`?

**Comment by dschaper** [comment]
A repair wouldn't help this. Do you have any logs for `FTL` or `lighttpd`?

What is the output from:

```
ls -la /var/log/pihole*
```
and
```
sudo ls -la /var/log/lighttpd/
```

Are you running a ramlog setup or have you made any filesystem changes?

**Comment by doobersn** [comment]
> A repair wouldn't help this. Do you have any logs for `FTL` or `lighttpd`?
> 
> What is the output from:
> 
> ```
> ls -la /var/log/pihole*
> ```
> 
> and
> 
> ```
> sudo ls -la /var/log/lighttpd/
> ```
> 
> Are you running a ramlog setup or have you made any filesystem changes?

`dietpi@DietPi:~$ ls -la /var/log/pihole*
-rw-r--r-- 1 root   pihole      0 Jun  3 20:17 /var/log/pihole_debug.log
-rw-r--r-- 1 pihole pihole    145 Jun  3 22:43 /var/log/pihole-FTL.log
-rw-r--r-- 1 pihole pihole 383369 Jun  3 22:46 /var/log/pihole.log
-rw-r--r-- 1 pihole pihole      0 Jun  3 00:17 /var/log/pihole.log.1
-rw-r--r-- 1 root   root        0 May 30 04:17 /var/log/pihole_updateGravity.log

/var/log/pihole:
total 0
drwxr-xr-x 2 pihole pihole  40 Dec 14  2019 .
drwxr-xr-x 6 root   root   320 May 20 22:26 ..`

and

`dietpi@DietPi:~$ sudo ls -la /var/log/lighttpd/
total 12
drwxr-x--- 2 www-data www-data    80 Dec 14  2019 .
drwxr-xr-x 6 root     root       320 May 20 22:26 ..
-rw-r--r-- 1 www-data www-data 10329 Jun  3 22:26 access.log
-rw-r--r-- 1 www-data www-data     0 May 29 21:17 error.log`

I have not made any changes to the filesystem that I know of. I'm running stock dietpi. I suspect this happened around the time I updated dietpi and pihole.

**Comment by dschaper** [comment]
Normally you'd have a lot more archived logs in those directories. Might want to ask @MichaIng since this looks like an OS level issue.

**Comment by MichaIng** [comment]
By default `/var/log` is a tmpfs and empties every hour. I suggest to create fresh logs by restarting the services, when they are empty:
```
systemctl restart pihole-FTL
systemctl restart lighttpd
```

Then try to trigger the error and afterwards check the logs, like:
```
tail -20 /var/log/pihole-FTL.log
tail -20 /var/log/pihole.log
tail -20 /var/log/lighttpd/error.log
```
or a new debug upload of course.

Alternatively you can disable RAM logging to make them persistent:
```
dietpi-software uninstall 103
```
___________
One guess is that the tmpfs runs full in under an hour, so FTL then fails to further write to the log file, which might cause these issues? So keep an eye on this. By default the tmpfs size is 50 MiB: `df /tmp`
If it turns out to be the issue, three solutions:
- Raise tmpfs size, e.g. to 100 MiB: `sed -i 's/size=50M/size=100M/' /etc/fstab; mount -o remount /var/log`
- Disable RAM logging with the uninstall above
- Disable pihole.log logging: `pihole -l off`
    This is a DNS query log that is used for `pihole tail` to print colourised query logs to console. The web interface however uses the database query log, so searching queries there is untouched by this. So if you don't use the console log print feature, this makes sense, regardless whether RAM logging is enabled or not. The additionally contained dnsmasq init logs are still done to `pihole.log`, but that's a very limited amount.

**Comment by dschaper** [comment]
> By default `/var/log` is a tmpfs and empties every hour. I suggest to create fresh logs by restarting the services, when they are empty:

Really? Has that always been DietPi's configuration? Does it just toss out all logs or does it save them somewhere? 



>     * Disable pihole.log logging: `pihole -l off`

No, don't do that. 

>     * So if you don't use the console log print feature, this makes sense, regardless whether RAM logging is enabled or not.

No, it doesn't.

**Comment by MichaIng** [comment]
Did something change since you were for disabling this log by default [here](https://github.com/pi-hole/pi-hole/pull/2839#issuecomment-555149247)?

It has been thoughoutly discussed and the only left reason was that `pihole tail` uses it.

DietPi has RAM logging enabled (with options to disable it and to store logs persistently before hourly clearing) since it was founded: https://dietpi.com/docs/software/log_system/#dietpi-ramlog

**Comment by dschaper** [comment]
You refer to a comment I made in 2019 that was neither for nor against it at the time. Since you're fond of out-of-context I'll do the same:

Did something change since you were for leaving the logging enabled by default here?

https://github.com/pi-hole/pi-hole/pull/2839#issuecomment-603318214

> DietPi has RAM logging enabled

Seems odd that you'd want to throw out all logging by default for everything, including things like error logs or historical data. I guess if you can't find the error log from something that happened yesterday then it didn't happen. 

As for doobersn, I'd suggest using Raspberry Pi OS as that's known to work very well with Pi-hole and not make assumptions on how you should be running your hardware. https://www.raspberrypi.org/software/ (The Lite variant works great.)

**Comment by doobersn** [comment]
> A repair wouldn't help this. Do you have any logs for `FTL` or `lighttpd`?
> 
> What is the output from:
> 
> ```
> ls -la /var/log/pihole*
> ```
> 
> and
> 
> ```
> sudo ls -la /var/log/lighttpd/
> ```
> 
> Are you running a ramlog setup or have you made any filesystem changes?

Hey there, not sure if it's of any interest but the problem has started again. Debug token: https://tricorder.pi-hole.net/d638qbv1em

 ls -la /var/log/pihole*:

`dietpi@DietPi:~$  ls -la /var/log/pihole*
-rw-r--r-- 1 root   pihole  52641 Jun 14 04:09 /var/log/pihole_debug.log
-rw-r--r-- 1 pihole pihole   6444 Jun 14 04:08 /var/log/pihole-FTL.log
-rw-r--r-- 1 pihole pihole 532309 Jun 14 04:10 /var/log/pihole.log
-rw-r--r-- 1 pihole pihole      0 Jun 14 00:17 /var/log/pihole.log.1
-rw-r--r-- 1 root   root        0 Jun 13 04:17 /var/log/pihole_updateGravity.log

/var/log/pihole:
total 0
drwxr-xr-x 2 pihole pihole  40 Dec 14  2019 .
drwxr-xr-x 6 root   root   320 May 20 22:26 ..
`

sudo ls -la /var/log/lighttpd/:

`dietpi@DietPi:~$ sudo ls -la /var/log/lighttpd/
total 12
drwxr-x--- 2 www-data www-data    80 Dec 14  2019 .
drwxr-xr-x 6 root     root       320 May 20 22:26 ..
-rw-r--r-- 1 www-data www-data 10439 Jun 14 04:10 access.log
-rw-r--r-- 1 www-data www-data     0 Jun  4 00:17 error.log
dietpi@DietPi:~$ 
`

Hope that helps and thanks for any help or insight you might have.

**Comment by dschaper** [comment]
Did you make any of the changes that Micha suggested? 

Have you tried using the OS that I linked to previously?

**Comment by doobersn** [comment]
> Did you make any of the changes that Micha suggested?
> 
> Have you tried using the OS that I linked to previously?

I have not yet switched to raspian lite since I was hoping to avoid a reinstall. I thought you told me not to do what he said to do, I apologize if I was mistaken. You wrote "No, don't do that." but maybe that was only for that command. Thanks!

**Comment by yubiuser** [comment]
@doobersn  Any news on that issue?

**Comment by doobersn** [comment]
> @doobersn Any news on that issue?

No, it is still doing it, unfortunately. I've updated pihole and dietpi since then but no changes. I just do 'pihole restartdns' whenever it happens and that fixes it for a while. Honestly ill probably just try restarting dietpi (I much prefer it to raspbian lite or whatever the equivalent is) and pihole on a new microsd card and see if that fixes it since no one else reports this issue and it never happened up until now.

**Comment by MichaIng** [comment]
Whether the RAM logging/tmpfs is the issue, can be also monitored without doing any changes. Check out the hourly cron job execution time:
```sh
journalctl -u cron | grep -m1 hourly
```
It should be `:17` by default. So you can e.g. check or monitor the usage of the RAM drive and see if it comes anywhere near 100% until before the next hourly cron job clears logs via `findmnt -rno 'USE%' /var/log`. For live monitoring:
```sh
watch findmnt -rno 'USE%' /var/log
```

And also, when the error appears, access the dashboard to freshly trigger the error, then check the logs:
```
tail -10 /var/log/lighttpd/error.log
tail -10 /var/log/pihole-FTL.log
tail -10 /var/log/pihole.log
```
Ah, basically what I suggested above already (the first part of it).

**Comment by doobersn** [comment]
> Whether the RAM logging/tmpfs is the issue, can be also monitored without doing any changes. Check out the hourly cron job execution time:
> 
> ```shell
> journalctl -u cron | grep -m1 hourly
> ```
> 
> It should be `:17` by default. So you can e.g. check or monitor the usage of the RAM drive and see if it comes anywhere near 100% until before the next hourly cron job clears logs via `findmnt -rno 'USE%' /var/log`. For live monitoring:
> 
> ```shell
> watch findmnt -rno 'USE%' /var/log
> ```
> 
> And also, when the error appears, access the dashboard to freshly trigger the error, then check the logs:
> 
> ```
> tail -10 /var/log/lighttpd/error.log
> tail -10 /var/log/pihole-FTL.log
> tail -10 /var/log/pihole.log
> ```
> 
> Ah, basically what I suggested above already (the first part of it).

Thanks a lot for posting this, but I honestly think im too technologically inept to know what to do to fix it even if I do know what the problem is, haha. :)

**Comment by MichaIng** [comment]
> think im too technologically inept to know what to do to fix it

That's the reason we are here 😄. Okay lets skip the RAM log part for now, I don't think it is the issue. Do the following:
1. Run
    ```sh
    systemctl restart pihole-FTL
    systemctl restart lighttpd
    ```
2. Try to access the Pi-hole web interface, the query log etc, the parts that fails.
3. Run the following commands and paste the output here (copy&paste from SSH console at best):
    ```sh
    tail -10 /var/log/lighttpd/error.log
    tail -10 /var/log/pihole-FTL.log
    tail -10 /var/log/pihole.log
    ```

**Comment by doobersn** [comment]
> > think im too technologically inept to know what to do to fix it
> 
> That's the reason we are here 😄. Okay lets skip the RAM log part for now, I don't think it is the issue. Do the following:
> 
> 1. Run
>    ```shell
>    systemctl restart pihole-FTL
>    systemctl restart lighttpd
>    ```
> 2. Try to access the Pi-hole web interface, the query log etc, the parts that fails.
> 3. Run the following commands and paste the output here (copy&paste from SSH console at best):
>    ```shell
>    tail -10 /var/log/lighttpd/error.log
>    tail -10 /var/log/pihole-FTL.log
>    tail -10 /var/log/pihole.log
>    ```
> 4. If there in any private/sensitive information in the logs, mask them, but actually it shouldn't.

You are a great person, thank you for your help!

Unfortunately, `systemctl restart pihole-FTL` is giving me this error `Failed to connect to bus: No such file or directory`.

**Comment by MichaIng** [comment]
Those two commands require root permissions:
```sh
sudo systemctl restart pihole-FTL
sudo systemctl restart lighttpd
```

**Comment by doobersn** [comment]
> Those two commands require root permissions:
> 
> ```shell
> sudo systemctl restart pihole-FTL
> sudo systemctl restart lighttpd
> ```

Weirdly, I did try sudo the first time and it didnt work. But it worked fine this time! Thanks! Output:

`sudo tail -10 /var/log/lighttpd/error.log
2021-08-21 03:13:52: (server.c.2059) server stopped by UID = 0 PID = 1 
2021-08-21 03:13:53: (server.c.1464) server started (lighttpd/1.4.53) 
dietpi@DietPi:~$ sudo tail -10 /var/log/pihole-FTL.log
[2021-08-21 03:13:44.752 901M]  -> Known forward destinations: 2
[2021-08-21 03:13:44.752 901M] Successfully accessed setupVars.conf
[2021-08-21 03:13:44.802 903M] PID of FTL process: 903
[2021-08-21 03:13:44.804 903M] INFO: FTL is running as user pihole (UID 999)
[2021-08-21 03:13:44.820 903/T906] Listening on Unix socket
[2021-08-21 03:13:44.827 903/T904] Listening on port 4711 for incoming IPv4 telnet connections
[2021-08-21 03:13:44.832 903/T905] Listening on port 4711 for incoming IPv6 telnet connections
[2021-08-21 03:13:44.833 903M] Reloading DNS cache
[2021-08-21 03:13:44.834 903M] Blocking status is enabled
[2021-08-21 03:13:45.936 903/T907] Compiled 0 whitelist and 51 blacklist regex filters for 2 clients in 46.7 msec
dietpi@DietPi:~$ sudo tail -10 /var/log/pihole.log
Aug 21 03:15:23 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 21 03:15:23 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
Aug 21 03:15:27 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 21 03:15:27 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
Aug 21 03:15:28 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 21 03:15:28 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
Aug 21 03:15:31 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 21 03:15:31 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
Aug 21 03:15:31 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 21 03:15:31 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0`

**Comment by MichaIng** [comment]
So all logs look fine, no errors and dnsmasq shows successfully blocked ads. But the web interface still shows this error you pasted in OP?

Does the webserver for some reason have no permissions to access the database? Can you run the following and paste the output here, please:
```
groups www-data
ls -l /etc/pihole/pihole-FTL.db
```

**Comment by doobersn** [comment]
> So all logs look fine, no errors and dnsmasq shows successfully blocked ads. But the web interface still shows this error you pasted in OP?
> 
> Does the webserver for some reason have no permissions to access the database? Can you run the following and paste the output here, please:
> 
> ```
> groups www-data
> ls -l /etc/pihole/pihole-FTL.db
> ```

I should add that currently its fine, so there may be no errors to show (I did a pihole restartdns command about a week ago which means everything is running fine for now). Here is the output of those commands:


```dietpi@DietPi:~$ groups www-data
www-data : www-data pihole
dietpi@DietPi:~$ ls -l /etc/pihole/pihole-FTL.db
-rw-r--r-- 1 pihole pihole 1651220480 Aug 21 21:17 /etc/pihole/pihole-FTL.db```

Maybe I should do this all again when the error occurs?

**Comment by MichaIng** [comment]
Ah okay. Still good to know: Permissions are fine, you don't need to check those again. But when the error re-appears, please check again and paste the log file content:
```sh
tail -10 /var/log/lighttpd/error.log
tail -10 /var/log/pihole-FTL.log
tail -10 /var/log/pihole.log
```

**Comment by doobersn** [comment]
> Ah okay. Still good to know: Permissions are fine, you don't need to check those again. But when the error re-appears, please check again and paste the log file content:
> 
> ```shell
> tail -10 /var/log/lighttpd/error.log
> tail -10 /var/log/pihole-FTL.log
> tail -10 /var/log/pihole.log
> ```

```
dietpi@DietPi:~$ sudo tail -10 /var/log/lighttpd/error.log
dietpi@DietPi:~$ tail -10 /var/log/pihole-FTL.log
[2021-08-31 19:29:01.156 903/T904] Client denied (at max capacity of 255): 274
[2021-08-31 19:29:01.157 903/T904] IPv4 telnet error: Success (0)
[2021-08-31 19:29:02.213 903/T904] Client denied (at max capacity of 255): 274
[2021-08-31 19:29:02.214 903/T904] IPv4 telnet error: Success (0)
[2021-08-31 19:29:04.360 903/T904] Client denied (at max capacity of 255): 274
[2021-08-31 19:29:04.360 903/T904] IPv4 telnet error: Success (0)
[2021-08-31 19:29:05.924 903/T904] Client denied (at max capacity of 255): 274
[2021-08-31 19:29:05.925 903/T904] IPv4 telnet error: Success (0)
[2021-08-31 19:29:05.951 903/T904] Client denied (at max capacity of 255): 274
[2021-08-31 19:29:05.951 903/T904] IPv4 telnet error: Success (0)
dietpi@DietPi:~$ tail -10 /var/log/pihole.log
Aug 31 19:29:08 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 31 19:29:08 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
Aug 31 19:29:09 dnsmasq[903]: query[A] dfwlive-v1-c2p3-sponsored.akamaized.net from 192.168.1.1
Aug 31 19:29:09 dnsmasq[903]: cached dfwlive-v1-c2p3-sponsored.akamaized.net is <CNAME>
Aug 31 19:29:09 dnsmasq[903]: forwarded dfwlive-v1-c2p3-sponsored.akamaized.net to 1.0.0.1
Aug 31 19:29:09 dnsmasq[903]: reply dfwlive-v1-c2p3-sponsored.akamaized.net is <CNAME>
Aug 31 19:29:09 dnsmasq[903]: reply a598.dscw22.akamai.net is 104.88.206.202
Aug 31 19:29:09 dnsmasq[903]: reply a598.dscw22.akamai.net is 104.88.206.209
Aug 31 19:29:13 dnsmasq[903]: query[A] scribe.logs.roku.com from 192.168.1.1
Aug 31 19:29:13 dnsmasq[903]: gravity blocked scribe.logs.roku.com is 0.0.0.0
```

Finally happened again and here are the outputs! Many thanks for being so patient and helpful!

**Comment by MichaIng** [comment]
> ```
> Client denied (at max capacity of 255): 274
> IPv4 telnet error: Success (0)
> ```

Hmm, does this mean FTL denies a telnet client connection (to get query stats) because there are too many open already? Probably an issue with non-closed connections or so? A bit funny to have the two words "error" and "Success" in the same line, probably this log can be enhanced a bit 🙂.

I found some more of such cases in the forum: https://discourse.pi-hole.net/search?q=Client%20denied%20(at%20max%20capacity%20of%20255)
In cases it was due to a malformed query database, if I understood right. If its okay for you to loose the long-term query log, you could try to start with a fresh database:
```sh
systemctl stop pihole-FTL
mv /etc/pihole/pihole-FTL.db{,_bak}
systemctl start pihole-FTL
# to remove the old database completely
rm /etc/pihole/pihole-FTL.db_bak
```
But since in your case, a `restartdns` solves it temporarily, I'm not sure if this is really the solution.

Did we already rule out an issue with free disk space? Unlikely that it caused (only) this type of issue, but just to rule it out:
```sh
df /etc/pihole/pihole-FTL.db
```

**Comment by doobersn** [comment]
> > ```
> Did we already rule out an issue with free disk space? Unlikely that it caused (only) this type of issue, but just to rule it out:
> 
> 
> ```shell
> df /etc/pihole/pihole-FTL.db
> ```

That gives me:

```dietpi@DietPi:~$ df /etc/pihole/pihole-FTL.db
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       29571828 4301784  24345864  16% /
```

**Comment by MichaIng** [comment]
Okay, then next you could try to start with a fresh database via commands above.

**Comment by CarloCattano** [comment]
is this related or seems like a new issue ? 
```
DataTables warning: table id=domainsTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7
´´´
