### ISSUE TITLE
[ERROR]: There are no generated block lists (list.#.site.com.domains) in the Pi-hole folder! Please update gravity by running pihole -g.

### ISSUE THREAD

**Issue by FightMan01** [pi-hole/pi-hole#4190]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Ubuntu 20.04 

- Platform:  Raspberry Pi

### Expected behavior

Pi-hole will show the blocking page

### Actual behavior / bug

I get an error: `[ERROR]: There are no generated block lists (list.#.site.com.domains) in the Pi-hole folder! Please update gravity by running pihole -g.`

### Steps to reproduce

`pihole-FTL.conf` content:
```
PRIVACYLEVEL=0
BLOCKINGMODE=IP  
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/wi6bbh2txa

-->

### Screenshots

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/29693718/120494120-d41e7a80-c3bb-11eb-9034-f75ea56a9692.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/29693718/120494188-e4cef080-c3bb-11eb-8941-3b522f464691.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/120494279-fa441a80-c3bb-11eb-9716-c80696a60986.png">

### Additional context

Blocking works fine, just this blocking page does not show up.

**Comment by dschaper** [comment]
You've enabled IP blocking mode, I assume because you want the blockpage. At this point the blockpage is mostly non-functional and will be removed in the future.

Your debug log shows that `/etc/pihole/setupVars.conf` doesn't exist and that contains the majority of the configuration lines that are needed when you use IP blocking mode.

Checks to see if the blockpage and admin interface are also failing:

```plain
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
```

Have you made any changes or modifications to anything on the Pi-hole server?

**Comment by dschaper** [comment]
Also it looks like a lot of starting and stopping lighttpd:

```plain
   2021-06-01 10:07:55: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 16:17:03: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 16:17:14: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 16:57:04: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 16:57:04: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 16:58:33: (server.c.936) [note] graceful shutdown started 
   2021-06-01 16:58:33: (server.c.1970) server stopped by UID = 0 PID = 12485 
   2021-06-01 16:58:33: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:00:32: (server.c.936) [note] graceful shutdown started 
   2021-06-01 17:00:32: (server.c.1970) server stopped by UID = 0 PID = 12966 
   2021-06-01 17:00:32: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:05:39: (server.c.936) [note] graceful shutdown started 
   2021-06-01 17:05:39: (server.c.1970) server stopped by UID = 0 PID = 14114 
   2021-06-01 17:05:39: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:08:21: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 17:08:22: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:09:58: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 17:10:09: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:12:16: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 17:12:16: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:16:30: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 17:18:09: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-01 17:18:26: (server.c.1970) server stopped by UID = 0 PID = 1 
   2021-06-01 17:18:27: (server.c.1488) server started (lighttpd/1.4.55) 
   2021-06-02 13:41:35: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Uninitialized string offset: 0 in /var/www/html/admin/scripts/pi-hole/php/queryads.php on line 28
```

**Comment by FightMan01** [comment]
My setupVars.conf file is in the right place:

![](https://user-images.githubusercontent.com/29693718/120494120-d41e7a80-c3bb-11eb-9034-f75ea56a9692.png)

And it is a fresh install of pi-hole. I already tried to reinstall it but it didn't work.

**Comment by FightMan01** [comment]
`setupVars.conf` file:
```
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.1.27/24
IPV6_ADDRESS=
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
CACHE_SIZE=10000
WEBPASSWORD=the_password_is_here_but_i_removed_it_for_now
BLOCKING_ENABLED=true
DNSMASQ_LISTENING=single
PIHOLE_DNS_1=127.0.0.1#5335
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
REV_SERVER=false
```

**Comment by dschaper** [comment]
Can you do a new debug log? 

And do a `ls -la /etc/pihole` to verify. The initial debug log showed that `setupVars.conf` was empty or not there. It also looks like you are using the `root` user and that can cause issues with file permissions since Pi-hole runs as non-root users.

**Comment by FightMan01** [comment]
https://tricorder.pi-hole.net/tecqkkvbpg
<img width="679" alt="image" src="https://user-images.githubusercontent.com/29693718/120917759-3f649700-c6b1-11eb-85e6-ad53e6eadb63.png">
After a pi reboot (power surge) it still not works. 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/120917764-4be8ef80-c6b1-11eb-84c9-4524788c3b0c.png">

**Comment by dschaper** [comment]
Okay, so it looks like this is what you are seeing instead of the blockpage since the URL you are trying is `http://doubleclick.net`.

Can you run `curl -I http://doubleclick.net` on the Pi-hole terminal?

@PromoFaux I don't know the blockpage all that well but shouldn't it be using the database and not lists? I can't find that error output anywhere in the index.php either.

**Comment by PromoFaux** [comment]
After a bit of detective work...

The only place I can find that string ever having existed was in @WaLLy3K's original (now deprecated) custom block page, here:

https://github.com/WaLLy3K/Pi-hole-Block-Page/blob/master/index.php#L92

I've looked through the file history of `index.php` in the main repo and that string was never there (as far as I can see).

@FightMan01 - presumably you have installed the above-linked custom block page?

**Comment by FightMan01** [comment]
> Okay, so it looks like this is what you are seeing instead of the blockpage since the URL you are trying is `http://doubleclick.net`.
> 
> Can you run `curl -I http://doubleclick.net` on the Pi-hole terminal?
> 
> @PromoFaux I don't know the blockpage all that well but shouldn't it be using the database and not lists? I can't find that error output anywhere in the index.php either.

```
root@server3:~# curl -I http://doubleclick.net
HTTP/1.1 301 Moved Permanently
Location: https://marketingplatform.google.com/about/enterprise/
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
Date: Tue, 08 Jun 2021 06:23:03 GMT
Expires: Tue, 08 Jun 2021 06:53:03 GMT
Cache-Control: public, max-age=1800
Server: sffe
Content-Length: 251
X-XSS-Protection: 0
```
Going to the local address (without /admin) will result the same error message.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/121133725-fc323180-c832-11eb-8c38-83e2e7802b37.png">

**Comment by FightMan01** [comment]
> After a bit of detective work...
> 
> The only place I can find that string ever having existed was in @WaLLy3K's original (now deprecated) custom block page, here:
> 
> https://github.com/WaLLy3K/Pi-hole-Block-Page/blob/master/index.php#L92
> 
> I've looked through the file history of `index.php` in the main repo and that string was never there (as far as I can see).
> 
> @FightMan01 - presumably you have installed the above-linked custom block page?

I didn't install it. It is a fresh install of the pi-hole from the official website.

**Comment by PromoFaux** [comment]
I'm not sure what else to say, the string "There are no generated blocklists..." has never existed in the stock `index.php`

Reset to stock with the following, then try again:
```
sudo rm /var/www/html/pihole/index.php
pihole -r #choose repair here when the dialog shows
```

**Comment by yubiuser** [comment]
@FightMan01 

Any news on that? Did you try what Promo suggested?
