### ISSUE TITLE
Command pihole -b cannot process adlists

### ISSUE THREAD

**Issue by dvdvideo1234** [pi-hole/pi-hole#4192]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform 
- OS and version:  Linux mangos-vb 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Platform:  Virtual box PC

### Expected behavior

Running `pihole -b` should be able to insert ad-list information into the database.

### Actual behavior / bug

Running `pihole -b "https://adaway.org/hosts.txt"`  gives: `[✗] https://adaway.org/hosts.txt is not a valid argument or domain name!` instead of registering the adblock list into the gravity database. The database is not updated as the URL is not a domain.

### Steps to reproduce

1. Open terminal
2. Run `pihole -b pihole -b https://adaway.org/hosts.txt`
3. Error is present

## Debug Token
URL:  https://tricorder.pi-hole.net/3dcyiedobs

### Additional context
I've made [a personal script with an array of ad-lists](https://github.com/dvdvideo1234/UbuntuBatches/blob/master/Olimex-A20/PI-Hole/adlist/install.sh) that I want to register in the gravity database. What is the proper command of doing this ?

**Comment by yubiuser** [comment]
Try

`pihole -a adlist add URL comment` 

or via SQL

`sudo sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://domain.com/blocklist.txt', 1, 'comment');"`
