### ISSUE TITLE
dig needs access to non standard external DNS (usually blocked!)  ns1.pi-hole.net 

### ISSUE THREAD

**Issue by TheBigBear** [pi-hole/pi-hole#4195]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Debian 10 Buster

- Platform:  WSL 1

### Expected behavior

your install-basic.sh script calls dig on line 194 to get a TXT value from ns1.pi-hole.net

### Actual behavior / bug

But in a locked down place 'random' external DNS is usually locked down. _

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Could you please consider to allow this check to alternatively also be done via a cmd line download ( wget  / curl ) of a 'versions.txt' file from the GitHub repo?

**Comment by yubiuser** [comment]
This was added in https://github.com/pi-hole/pi-hole/pull/3596 on purpose. See this [comment](https://github.com/pi-hole/pi-hole/pull/3596#issuecomment-664509808).

I don't fully understand what it is you are asking for. You can skip the whole check as described in the helping text

https://github.com/pi-hole/pi-hole/blob/4736e03108763cc2d5659f48d8a1e8a64d9b2608/automated%20install/basic-install.sh#L255

**Comment by dschaper** [comment]
This has been asked and answered in a number of issues here and on Discourse. This is the way it is and there are reasons for it that are discussed many times over in those issues.
