### ISSUE TITLE
Installation process fails when doing so on a system with multiple (read above 20) network adapters

### ISSUE THREAD

**Issue by elbosso** [pi-hole/pi-hole#4196]
### Versions
- Pi-hole version is v5.3.1 (Latest: v5.3.1)
-  AdminLTE version is v5.5 (Latest: v5.5)
-  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Linux rock64 4.4.167-1213-rockchip-ayufan-g34ae07687fce #1 SMP Tue Jun 18 20:44:
49 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
- Platform:  Pine Rock64
- Docker running with 25 active services, 16 docker networks, 47 network adapters (`ifconfig -a|grep flags|wc -l`)

### Expected behavior

It is possible to install PiHole while logged in via SSH

### Actual behavior / bug

It is (near) impossible to install PiHole because when the curses dialog shows where the user can select the network card, all docker (virtual) network cards, bridges, etc. show up - when this happens, the list can get so huge that the user is unable to get at the entries way up in the list. The list is not scrollable - so if the user needs to select an entry among  the first in the list - that is impossible

### Steps to reproduce

* Get a system with a fair amount of docker containers running and a fair amount of network cards  where `ifconfig -a|grep flags|wc -l` returns something above 30 maybe
* Try to start the installation process and look at the dialog for the selection of the network interface

## Debug Token

not applicable because Error happens during install

### Screenshots

![image](https://user-images.githubusercontent.com/18102857/121333854-74732280-c919-11eb-92f6-6c82f3e2bf44.png)

### Additional context

none so far

**Comment by dschaper** [comment]
Are you not able to use the up and down arrow keys to select the interface you want? Or expand the terminal window so it's bigger than 80 X 25 or so? 

I don't see a possible way for us to determine what should be a choice and what shouldn't be.

**Comment by elbosso** [comment]
Yes exactly - that is what puzzles me - I would have expected that the cursor keys work, too. I am about to set up a small test.
My workaround was (making the terminal window larger did not suffice) to zoom in thrice in the gnome terminal - then, the content was barely readable but it did fit.

I did not yet look into the code but i tried the following two command lines:
* `dialog --radiolist "Pizza mit ..." 0 0 24 Salami "" off Schinken "" off Thunfisch "" off bla "" off bla2 "" off blub "" off Salami "" off Schinken "" off Thunfisch "" off bla "" off bla2 "" off blub "" off Salami "" off Schinken "" off Thunfisch "" off bla "" off bla2 "" off blub "" off Salami "" off Schinken "" off Thunfisch "" off bla "" off bla2 "" off blub "" off`
* `dialog --menu "Betriebssystem wählen" 0 0 0  "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" "Linux" "" "BSD" "" "Solaris" "" 3>&1 1>&2 2>&3`

They both work (and scroll) as expected. Now, if my guess is correct and you really use `dialog --radiolist` then i can only assume that there is some subtlety there that prevents scrolling in the install script but i can (as of yet) not see which one...

**Comment by yubiuser** [comment]
Try if it works for you with adding `--scrolltext`

**Comment by elbosso** [comment]
it gets more mysterious every second: I copied the content of the function from the install script for testing purposes like so:
```
availableInterfaces=$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1)
# Find out how many interfaces are available to choose from
    interfaceCount=$(wc -l <<< "${availableInterfaces}")

    # If there is one interface,
    if [[ "${interfaceCount}" -eq 1 ]]; then
        # Set it as the interface to use since there is no other option
        PIHOLE_INTERFACE="${availableInterfaces}"
    # Otherwise,
    else
        # While reading through the available interfaces
        while read -r line; do
            # Use a variable to set the option as OFF to begin with
            mode="OFF"
            # If it's the first loop,
            if [[ "${firstLoop}" -eq 1 ]]; then
                # set this as the interface to use (ON)
                firstLoop=0
                mode="ON"
            fi
            # Put all these interfaces into an array
            interfacesArray+=("${line}" "available" "${mode}")
        # Feed the available interfaces into this while loop
        done <<< "${availableInterfaces}"
        # The whiptail command that will be run, stored in a variable
        chooseInterfaceCmd=(whiptail --separate-output --radiolist "Choose An Interface (press space to toggle selection)" "${r}" "${c}" "${interfaceCount}")
        # Now run the command using the interfaces saved into the array
        chooseInterfaceOptions=$("${chooseInterfaceCmd[@]}" "${interfacesArray[@]}" 2>&1 >/dev/tty) || \
        # If the user chooses Cancel, exit
        { printf "  %bCancel was selected, exiting installer%b\\n" "${COL_LIGHT_RED}" "${COL_NC}"; exit 1; }
        # For each interface
        for desiredInterface in ${chooseInterfaceOptions}; do
            # Set the one the user selected as the interface to use
            PIHOLE_INTERFACE=${desiredInterface}
            # and show this information to the user
            printf "  %b Using interface: %s\\n" "${INFO}" "${PIHOLE_INTERFACE}"
        done
    fi

```

and that works as expected!

**Comment by elbosso** [comment]
> Try if it works for you with adding `--scrolltext`

no - `--scrolltext` does not change anything in this regard

**Comment by elbosso** [comment]
if i use `dialog` instead of `whiptail` - the behaviour is as expected

**Comment by elbosso** [comment]
OK - found it: setting rows and columns to 0 (letting whiptail figure it out by itself) fixes it:
![image](https://user-images.githubusercontent.com/18102857/121478157-fff7bc80-c9c8-11eb-8bfb-9219fc60c10e.png)

will be making a pull request presently...
