### ISSUE TITLE
Whitelisted domain is blocked by RegEx

### ISSUE THREAD

**Issue by simphide** [pi-hole/pi-hole#4200]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  Docker

### Expected behavior

The domain should be accessible since I whitelisted the specific domain

### Actual behavior / bug

The domain is still blocked...

### Steps to reproduce

Create RegEx blacklist entry "^stat(s|istics)?[0-9]*[_.-]"
Manually whitelist "stats.stackexchange.com"
Try to resolve "stats.stackexchange.com"

## Debug Token

(edit: fixed URL)
- URL:  https://tricorder.pi-hole.net/9a8rysnu1r

### Screenshots

Domain being blocked in query log:
![image](https://user-images.githubusercontent.com/8183517/121806214-4f4f1e80-cc4f-11eb-8c46-50229bcc5a53.png)

Domain is whitelisted:
![image](https://user-images.githubusercontent.com/8183517/121806220-59711d00-cc4f-11eb-98f1-7edddff4b977.png)

Blacklist regex:
![image](https://user-images.githubusercontent.com/8183517/121806247-668e0c00-cc4f-11eb-8dbf-ed5275f3c268.png)

### Additional context

Thank you for that awesome project!!

**Comment by dschaper** [comment]
Hmm... I can't seem to duplicate this. I've set up my local Pi-hole with the same settings:

![Screenshot 2021-06-14 103237](https://user-images.githubusercontent.com/2782850/121934302-02755180-ccfc-11eb-846b-8a6f2ae5fcca.png)
![Screenshot 2021-06-14 103257](https://user-images.githubusercontent.com/2782850/121934316-0608d880-ccfc-11eb-916d-72c24c8d2bf5.png)

I did an `nslookup` for `stats.stackexchange.com` with just the regex and that blocked. I then added in the whitelist and the domain was allowed through:

![Screenshot 2021-06-14 103148](https://user-images.githubusercontent.com/2782850/121934407-2042b680-ccfc-11eb-9b35-6b9b75ccfffb.png)

Sometimes we see issues where domains or lists are added to groups and the clients themselves are not in the appropriate groups but your debug log shows that you are not using groups. 

Can you visit the domain with a browser? It looks like the client may be a MacBookPro, is it possible that it has more than the Pi-hole DNS set for it to use?

**Comment by dschaper** [comment]
And you mentioned the Pi-hole is on Docker on Ubuntu but the debug log you provided shows:

```plain
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  0
[i] dig response:  "Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=32,33 CentOS=7,8"
[✓] Distro:  Raspbian
[✓] Version: 10

*** [ DIAGNOSING ]: SELinux
[i] SELinux not detected

*** [ DIAGNOSING ]: FirewallD
[i] Firewalld service inactive

*** [ DIAGNOSING ]: Processor
[✓] armv7l
```

**Comment by simphide** [comment]
Thank you for your fast reply!
I'm using docker on my "main" Pi-hole and sync the configs via https://github.com/stevejenkins/pihole-cloudsync...

The problem only occured on my girlfriends rpi... How does whitelisting exactly work? Can the syncing be the problem?

**Comment by dschaper** [comment]
Where did the debug log come from? Your's or your girlfriends? And the screenshots?

Is the problem on your Pi-hole, your girlfriends or both?

Syncing may be the problem if the issue only happens on one server, you'd need to ask at the cloudsync repo to find out why that happens.

Whitelisting is the highest priority check and any query for a whitelisted domain will be allowed no matter what.

**Comment by simphide** [comment]
The log and the screenshots are from the girlfriends Pi-hole and the problem only occurs on the rpi

okay, strange - does Pi-hole always check domains against the gravity.db or is the whitelist somehow loaded in the ram so that if the gravity.db gets changed manually the whitelist needs to be reloaded

**Comment by jfb-pihole** [comment]
"does Pi-hole always check domains against the gravity.db or is the whitelist somehow loaded in the ram so that if the gravity.db gets changed manually the whitelist needs to be reloaded"

After you externally replace the gravity database, it needs to be reloaded in the Pi-hole that received the new database:

The pihole restardns is the command, with several possible modifiers.  In your case, the following command would be the correct choice to reload the lists only

`pihole restartdns reload-lists`

```
       restartdns [options]
           Full restart Pi-hole subsystems. Without any options (see below) a full restart causes config file parsing and history re-reading

           (restart options):
             reload            Updates the lists (incl. HOSTS files) and flushes DNS cache. Does not reparse config files
             reload-lists      Updates the lists (excl. HOSTS files) WITHOUT flushing the DNS cache. Does not reparse config files
```

**Comment by simphide** [comment]
> "does Pi-hole always check domains against the gravity.db or is the whitelist somehow loaded in the ram so that if the gravity.db gets changed manually the whitelist needs to be reloaded"
> 
> After you externally replace the gravity database, it needs to be reloaded in the Pi-hole that received the new database:
> 
> The pihole restardns is the command, with several possible modifiers. In your case, the following command would be the correct choice to reload the lists only
> 
> `pihole restartdns reload-lists`
> 
> ```
>        restartdns [options]
>            Full restart Pi-hole subsystems. Without any options (see below) a full restart causes config file parsing and history re-reading
> 
>            (restart options):
>              reload            Updates the lists (incl. HOSTS files) and flushes DNS cache. Does not reparse config files
>              reload-lists      Updates the lists (excl. HOSTS files) WITHOUT flushing the DNS cache. Does not reparse config files
> ```

That didn't work... I ran "pihole restartdns reload-lists" but the domain still seems to be blocked...

`
dig stats.stackexchange.com @192.168.178.129

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> stats.stackexchange.com @192.168.178.129
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12264
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;stats.stackexchange.com.	IN	A

;; ANSWER SECTION:
stats.stackexchange.com. 2	IN	A	0.0.0.0

;; Query time: 61 msec
;; SERVER: 192.168.178.129#53(192.168.178.129)
;; WHEN: Tue Jun 15 19:39:28 CEST 2021
;; MSG SIZE  rcvd: 68
`

**Comment by dschaper** [comment]
Ask the cloudsync people what is going on. I don't know what they do or how they do it and there may be an issue with how they mirror or sync databases. You may not have the same database information on both systems.

**Comment by simphide** [comment]
The script imports the gravity database information like this:

```
pull () {
    # Go to Pi-hole directory, exit if doesn't exist
    cd $personal_git_dir || exit

    # Update local Git repo from remote Git repo
    $SUDO git remote update > /dev/null
    CHANGED=$($SUDO git log HEAD..origin/master --oneline)
    if [ -n "${CHANGED}" ]; then
        echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
        # Remove -q option if you don't want to run in "quiet" mode
        $SUDO git fetch --all -q
        $SUDO git reset --hard origin/master -q
        $SUDO service pihole-FTL stop
        $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
        $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
        $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
        $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
        $SUDO pihole -g
        echo 'Done!';
        exit 0
    else
        echo 'Local Pi-hole lists match remote git repo. No further action required.';
        exit 0
    fi
}
```

The information seem to be imported correctly since they appear correctly in the web interface

**Comment by dschaper** [comment]
I'm giving you the response you will get from me. Ask them.

**Comment by simphide** [comment]
I have found the problem - as you guessed there was trouble with the Group Management:

![image](https://user-images.githubusercontent.com/8183517/122177163-a3dbdf00-ce85-11eb-8aa7-413104123b2c.png)

After adding these whitelist entries to default, everything worked again
