### ISSUE TITLE
Whitelist / Blacklist Doesnt Work.

### ISSUE THREAD

**Issue by daanbreur** [pi-hole/pi-hole#4201]
### Versions
- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
- OS and version: Raspberry Pi OS Lite 
- Platform:  Raspberry Pi 3b+

### Expected behavior

Whitelisting should allow the domain and not block it.

### Actual behavior / bug

When i whitelist a domain it blocks it, whitelisting it through the "this website is blocked" page also doesnt work.

### Steps to reproduce

This is before adding the domain to the whitelist.
![image](https://user-images.githubusercontent.com/32175349/121820986-1e460c80-cc96-11eb-9160-742d12868645.png)
The whitelist and blacklist look like this at this moment:
![image](https://user-images.githubusercontent.com/32175349/121821112-1cc91400-cc97-11eb-8b7a-33d70b6fba1b.png)
![image](https://user-images.githubusercontent.com/32175349/121821115-1fc40480-cc97-11eb-9399-708f38bb9483.png)

Now lets add the domain to the whitelist
![image](https://user-images.githubusercontent.com/32175349/121821123-336f6b00-cc97-11eb-801f-7cd0e684b16e.png)
![image](https://user-images.githubusercontent.com/32175349/121821126-39654c00-cc97-11eb-9275-64f73b4e5695.png)

Now when I try to open any of the subdomains im greeted with this
![image](https://user-images.githubusercontent.com/32175349/121821135-497d2b80-cc97-11eb-8213-33aaac4fdb57.png)
Technical information shows 
![image](https://user-images.githubusercontent.com/32175349/121821142-5732b100-cc97-11eb-8e8f-09994f22ab94.png)
If i enter my password and click on whitelist here, it will say success.
![image](https://user-images.githubusercontent.com/32175349/121821178-a5e04b00-cc97-11eb-97a6-bfaee5c79132.png)

After refreshing the page and flushing my dns im still greeted with the same this website is blocked page.

## Debug Token

- URL:  https://tricorder.pi-hole.net/14fx537wv0

**Comment by daanbreur** [comment]
### Additional Information
The same thing happens when you use exact mode instead of regex mode.

**Comment by daanbreur** [comment]
![image](https://user-images.githubusercontent.com/32175349/121854066-f6849200-ccf1-11eb-8b06-b1743d0970b6.png)
Whitelist and Blacklist show as empty using the cli.

**Comment by PromoFaux** [comment]
This is expected if you are using your own domain name for accessing the interface.

Try `http://[domain]/admin` and you wont see this page.

else just use `http://pi.hole`

**Comment by daanbreur** [comment]
I am not trying to access the interface. This happens with every domain i try to whitelist/blacklist.

**Comment by PromoFaux** [comment]
From your debug log, it shows that there are two domains as whitelisted entries.

```
*** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
   id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment                                           
   ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   1     0           1  0             daanbreur.systems                                                                                     2021-06-13 20:58:28  2021-06-13 20:58:28                                                    
   2     0           1  0             server.daanbreur.systems                                                                              2021-06-13 21:00:12  2021-06-13 21:00:12          
```

Is the domain you are trying to access also a service running on the same device as the Pi-hole?

You will always see this page, whitelisted or not, if that is the case. Worth noting that the block page is currently deprecated, and will be removed from a later release. 

if `[domain]` resolves to `192.168.178.248`, then what you are seeing is expected. Your request is hitting `lighttpd` running on the pi device (port 80) and hitting the 404 handler, which is directing your request to `/var/www/html/pihole/index.php`. The domain is not really blocked, it is just how it is displayed by the (deprecated) block page.

If you are trying to access another service running on the same device, make sure to include the port number in the URL when you attempt to connect. 

Having just seen your edit:

Have a look at your nginx config. Something is resolving your domain to be that of the Pi-hole device.

**Comment by daanbreur** [comment]
Oh wow. I didnt realize that i accidentally hit yes on `install lighttpd`, It probably took over port `80` and started listening.
Why is the blocked page just a 404 page? And why is it being deprecated, cause its quite nice to see if the page is blocked or just doesnt resolve.

**Comment by PromoFaux** [comment]
To save me from typing it all out again, here is a comment I made about it on Reddit 3 years ago :)

https://old.reddit.com/r/pihole/comments/7jrjt5/how_to_install_this_without_giving_it_root/dr97rsq/

It's being deprecated because it doesn't work with HTTPS requests. The only way to do that would be to MITM the clients by generating fake certificates for blocked domains - and we're not going to do that.
