### ISSUE TITLE
First party website blocked

### ISSUE THREAD

**Issue by JackEllis** [pi-hole/pi-hole#4203]
### Versions
All

### Platform
All

### Expected behavior

usefathom.com should load without error. It's a standard website. We appreciate that cdn.usefathom.com is blocked as it's where our privacy-first analytics script is served from

### Actual behavior / bug

usefathom.com is blocked to pi-hole users

### Steps to reproduce

1. Visit usefathom.com
2. Observe connection issues

### Additional context

Fathom is our website. Completely understand you blocking cdn.usefathom.com, you take a hard stance against any third party scripts, but we've now had over 20 people contact us telling us that our website isn't working. Some of them have said they'd submit a bug, but that was a long time ago and the bug still persists.

Thanks for your time!

**Comment by yubiuser** [comment]
Pi-hole does not maintain our curate any adlists.
You need to contact the list maintainers.
As a starting point 
https://blocklist-tools.developerdan.com/entries/search?q=usefathom.com
