### ISSUE TITLE
FTL didn't start (Found out why)

### ISSUE THREAD

**Issue by Serpensin** [pi-hole/pi-hole#4208]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Ubuntu Server 20.04

- Platform:  RootServer (KVM/QEMU/Proxmox)

### Expected behavior

_FTL should start._

### Actual behavior / bug

FTL didn't start because `/etc/dnsmasq.d/lxd` is an redirect wich leads to a non existing folder (`/etc/dnsmasq.d-available/lxd`).
After i created the folder manualy, it worked.

**Comment by DL6ER** [comment]
We are not doing anything with `lxd`. What is the content of your
- file `/etc/dnsmasq.conf`, and
- directory `/etc/dnsmasq.d/`
- ?

**Comment by Serpensin** [comment]
Nothing. It is just empty.

**Comment by jfb-pihole** [comment]
"It is just empty."  This would be unusual.  What is the output of the following command from the terminal of the Pi-hole host OS or container:

`sudo grep -v '#\|^$' -R /etc/dnsmasq.*`

**Comment by Serpensin** [comment]
```
/etc/dnsmasq.conf:conf-dir=/etc/dnsmasq.d
/etc/dnsmasq.conf.old:conf-dir=/etc/dnsmasq.d
/etc/dnsmasq.d/01-pihole.conf:addn-hosts=/etc/pihole/local.list
/etc/dnsmasq.d/01-pihole.conf:addn-hosts=/etc/pihole/custom.list
/etc/dnsmasq.d/01-pihole.conf:localise-queries
/etc/dnsmasq.d/01-pihole.conf:no-resolv
/etc/dnsmasq.d/01-pihole.conf:cache-size=10000
/etc/dnsmasq.d/01-pihole.conf:log-queries
/etc/dnsmasq.d/01-pihole.conf:log-facility=/var/log/pihole.log
/etc/dnsmasq.d/01-pihole.conf:local-ttl=2
/etc/dnsmasq.d/01-pihole.conf:log-async
/etc/dnsmasq.d/01-pihole.conf:server=1.1.1.1
/etc/dnsmasq.d/01-pihole.conf:server=1.0.0.1
/etc/dnsmasq.d/01-pihole.conf:interface=eth0
/etc/dnsmasq.d/01-pihole.conf:server=/use-application-dns.net/
grep: /etc/dnsmasq.d/lxd: No such file or directory

```

**Comment by yubiuser** [comment]
Another approach would be to delete the file

`sudo rm /etc/dnsmasq.d/lxd`
