### ISSUE TITLE
Local overrides are deleted by gravity.sh

### ISSUE THREAD

**Issue by Zer0t3ch** [pi-hole/pi-hole#421]
##### Expected Behaviour:
File (`/etc/${basename}/pihole.conf`) will remain intact

##### Actual Behaviour:
File is deleted

##### Steps to reproduce this issue:
1. Create a file named `/etc/pihole/pihole.conf`
1. Execute `gravity.sh`

---

Coincidentally, while looking into this, I found that the line in `gravity_reload` that is doing the deleting (line 334) is using a hard-coded directory, (`/etc/pihole/`) whereas the code that loads the overrides (lines 71-74) used the `$basename` variable. (`/etc/${basename}/`)

**Comment by PromoFaux** [comment]
Good catch! I'll fix this now for the next release. (in the mean time, if it's causing issues for you, comment out line 334 in gravity.sh)

**Comment by dschaper** [comment]
Was this a regression? I thought we handled this

Dan Schaper via Project Fi
Nexus 5X

**Comment by Mcat12** [comment]
It's because we were deleting all files matching `pihole.*` instead of `pihole.*.txt`. See d710b

**Comment by PromoFaux** [comment]
An oversight on my part. :blush:
