### ISSUE TITLE
pi-hole insists on /8 subnet mask even though I want /24

### ISSUE THREAD

**Issue by salamihawk** [pi-hole/pi-hole#4213]
My local subnet is 10.0.0.0/24. I've assigned the pi-hole (installed on a Debian VM) the address 10.0.0.13/24, which it shows in the setupVars.conf file and the GUI. It's reachable via this address too.

However, I noticed it was ARPing for addresses (test IPs of mine) outside of 10.0.0.0/24, and this is due to the fact that on the Linux-level the pi-hole is setting up the IP address as 10.0.0.13/8.

I've updated with pi-hole -up, I've reconfigured AND repaired with pi-hole -r. I've even tried manually editing the interfaces file, all to no avail.

When I type ip addr in the CLI I'm shown 10.0.0.13/8. ifconfig shows an IP assigned via DHCP (10.0.0.104) and route shows a route for 10.0.0.0/24 AND 10.0.0.0/8 on the same interface with a metric of 202 for 10.0.0.0/8.

**Comment by dschaper** [comment]
Check `/etc/dhcpcd.conf`.

Normally we'd close this issue since you ignored the template that provides the information we need to help you. 

Please use https://discourse.pi-hole.net for configuration issues as the Issue options note. Thank you for your understanding.

**Comment by salamihawk** [comment]
found the issue in /etc/dhcpcd.conf, thanks.

the configuration for ens192 was doubled, once with /24 mask, once without.
