### ISSUE TITLE
Pi-hole does not start. Web interface us unavailable

### ISSUE THREAD

**Issue by dvdvideo1234** [pi-hole/pi-hole#4219]
### Versions

  Current Pi-hole version is v5.3.1.
  Current AdminLTE version is v5.5.
  Current FTL version is v5.8.1.

### Platform
- OS and version:  Ubuntu 20.04 ARM7
- Platform:  A20 Olinuxino Lime 2

### Expected behavior

The Pi-hole web interface to start after installing Pi-hole with repo clone

### Actual behavior / bug

The admin web interface does not start after the installation

### Steps to reproduce

1. Clone the Pi-Hole repo in the home folder
  * `git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole`
2. Go to `cd "Pi-hole/automated install/"`
3. Run `sudo bash basic-install.sh`

## Debug Token
Your debug token is: https://tricorder.pi-hole.net/d8yvvrdvr0

### Screenshots

Not applicable

**Comment by dschaper** [comment]
It doesn't look like `lighttpd` was even installed. Nor does it look like `pihole-FTL` was installed.

Could you please open an issue at https://discourse.pi-hole.net where there are more Pi-hole team and community members that can help walk through why the install was not completed? Thanks!

**Comment by dvdvideo1234** [comment]
It is weird that it was working with `Ubuntu 18` on my ARM7 CPU but now I upgraded to `Ubuntu 20`.

**Comment by dvdvideo1234** [comment]
@pralor-bot 

Yes, I created it by request from @dschaper.

**Comment by PromoFaux** [comment]
It's a bot :)

**Comment by dvdvideo1234** [comment]
I will ditch the web interface. Seems Pi-hole is working without it.
