### ISSUE TITLE
IPadOS15 iCloud Private Relay wont direct traffic properly to pi-hole

### ISSUE THREAD

**Issue by Morgwee** [pi-hole/pi-hole#4223]
### Versions

- Pi-hole: v5.3.1  
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version: iPadOS15  

- Platform:  iPad

### Expected behavior

Setting the DNS Server address manually in the iPadOS Settings of the selected network to point to the Raspberry Pi machine running pi-hole should result in all ad-related traffic to be blocked, and no ads being displayed.

### Actual behavior / bug

Ads are still being displayed in browser, even with DNS server set to point to pi-hole running on Raspberry Pi machine. However if you disable the iCloud Private Relay option in the network settings, the pi-hole software successfully blocks the ads from being rendered.

### Steps to reproduce

(Assume should be the same for iOS, but following steps are for iPadOS)
1. Go to iPad Settings Application
2. Click on Wifi
3. Click the blue exclamation mark in a circle next to your selected wifi network
4. Find “iCloud Pravate Relay”, if enabled, ad traffic is not blocked by pi-hole, if disabled, pi-hole can function as normal

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

![CE2AFBE4-B278-4F67-B18A-8DDB4B0FE2E0](https://user-images.githubusercontent.com/48145541/124950741-46cae780-e045-11eb-878b-55658af610f5.jpeg)

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
This is not a Pi-hole issue.  Private Relay as implemented by Apple in IOS/MacOS 15 beta routes DNS traffic through alternate channels and bypasses Pi-hole.

You will need to disable Private Relay on your home network to route your DNS traffic through Pi-hole.

**Comment by Morgwee** [comment]
I understand that, was simply raising it as something which could be captured in the documentation or something, as it took me a few hours to understand it. If not then you can ignore this.

Sent from my iPhone

On Jul 9, 2021, at 12:06 AM, jfb-pihole ***@***.***> wrote:

﻿

This is not a Pi-hole issue. Private Relay as implemented by Apple in IOS/MacOS 15 beta routes DNS traffic through alternate channels and bypasses Pi-hole.

You will need to disable Private Relay on your home network to route your DNS traffic through Pi-hole.
