### ISSUE TITLE
Broken link in pi-hole.net

### ISSUE THREAD

**Issue by Mraeling** [pi-hole/pi-hole#4224]
Hi just letting you know that the PiHole+VPN link on https://pi-hole.net/ links to:

https://docs.pi-hole.net/guides/openvpn/overview/

not the real link at:

https://docs.pi-hole.net/guides/vpn/openvpn/overview/

cheers,

(I couldn't find a way to edit the website to fix it)

**Comment by XhmikosR** [comment]
The docs redirects should be all here https://github.com/pi-hole/docs/blob/master/mkdocs.yml#L186

**Comment by Mraeling** [comment]
Ahh, I missed that. Thanks
