### ISSUE TITLE
High amount of clients/queries freezes dashboard

### ISSUE THREAD

**Issue by thegamerx1** [pi-hole/pi-hole#4227]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.3
- FTL:  5.8.1

### Platform

- OS and version:  ubuntu

- Platform:  docker

### Expected behavior
Dashboard to load smoothly and not freeze

### Actual behavior / bug
Page completely freezes and is not usable

### Steps to reproduce
open dashboard

## Debug Token

- URL:  
https://tricorder.pi-hole.net/lqacpdlqlq

### Screenshots

![16_07_2021_firefox_udwy31IyL0](https://user-images.githubusercontent.com/34986564/125869538-e7128644-3ff2-4c5b-bdd1-ed8d4ec15241.png)

### Additional context
my pihole got ddossed and it doesnt load

**Comment by dschaper** [comment]
You're running an open resolver.

As a standing practice, Pi-hole does not provide assistance or support to nodes running as public open resolvers. 

If being publicly accessible was not your intention then please open a ticket at https://discourse.pi-hole.net. If you intend to be running a public DNS server then you will need to find other assistance.

**Comment by thegamerx1** [comment]
You are not going to do anything about the dashboard not supporting high numbers? What if pihole was used somewhere big they would have to find an alternative?

**Comment by PromoFaux** [comment]
Depends on the hardware it's being run on. The dashboard is plenty capable of high numbers of clients/queries.

![image](https://user-images.githubusercontent.com/1998970/125987446-2b314f35-39d0-4724-9b84-cf104e372656.png)

**Comment by dschaper** [comment]
Pi-hole is used in big places but they have the knowledge to be able to not be a target or a source of dDOS attacks. That's the main issue and why we don't support open resolvers. Weaponizing DNS for attacking people isn't something we ever aspired to or will be complicit with.

The debug log is located at `/var/log/pihole_debug.log` as noted in the debug process. You may be able to discover what issues are causing this if you examine it. But that's as far as we will go for someone intending to run an open resolver.

**Comment by thegamerx1** [comment]
I blocked port 53 on iptables and im currently working on a page with a form that will allow the current ip to port 53 if the password is correct.
Could your dashboard not get frozen because its an older version? The charts are very different

**Comment by thegamerx1** [comment]
My pihole is now whitelisted you can check at https://dns.ndrx.ml, i still highly doubt the issue with it freezing was due to my hardware.

**Comment by dschaper** [comment]
I appreciate you taking the steps to secure your install but it doesn't look like you've taken any steps to prevent abuse via reflection and amplification attacks. Pi-hole should not be installed with any public facing access. I understand that you may feel that hosting a public DNS server is helping but it really does cause damage to others when it is not set up to prevent abuse.

**Comment by thegamerx1** [comment]
The port 53 is completely blocked unless you are whitelisted by the form on that page. The only public fancing access is the dashboard but thats safe if it requires a password right?

![image](https://user-images.githubusercontent.com/34986564/126034808-7b4d6464-c0d8-424e-ab5a-458bc117decc.png)

**Comment by DL6ER** [comment]
> The only public fancing access is the dashboard but thats safe if it requires a password right?

No, it's like @dschaper said:

> Pi-hole should not be installed with any public facing access.

The password protection really is only a very basic protection and does not withstand any even only half-hearted tries to break it. Furthermore, the entire API is currently still based on simple PHP and may be subject to well-known bugs and security issues - especially when you are using the system-provided probably horribly outdated version of PHP.

There is a lot more to be said but Pi-hole is *really* not meant to be public facing. Neither are similar projects. The only secure way is to use a VPN. We provide easy guides for setting up a modern [WireGuard](https://docs.pi-hole.net/guides/vpn/wireguard/overview/) or a legacy [OpenVPN](https://docs.pi-hole.net/guides/vpn/openvpn/overview/) VPN in just a few easy-to-follow steps. Plus we provide support if anyone has questions via our Discourse server.

**Comment by thegamerx1** [comment]
well its not my fault if your dashboard security is bad. Im not going to use a vpn server to double my ping and limit my internet speeds. I secured port 53 and thats all im going to do.

**Comment by jfb-pihole** [comment]
You do not need to route all your data traffic through the VPN. Route only the DNS traffic. This will have zero impact in your internet speed. It's called split tunnel and configuration is discussed in both our guides referenced above.
