### ISSUE TITLE
Amazon Silk browser

### ISSUE THREAD

**Issue by geozervo** [pi-hole/pi-hole#4232]
Hi! Seems when I login to pihole's admin page via Amazon's Firetv Silk web browser I can not do anything much as the GUI just falls apart now. This is just a fast way for me to make adjustments without having to run off to my desktop computer. Use to work fine with the Silk browser but now it does not. RPi o/s is up to date and so is pihole. I thought maybe it is a blocking issue but if I disable pihole the GUI is still messed up.
Works ok on Amazon Firetv Firefox but Firefox is not supported any longer by mozilla on Firetv. So only a matter of time before that blows out too. 
Much appreciated if the pihole team can get Silk to work with pihole again.
 Thanks!

**Comment by yubiuser** [comment]
Do you have the ability to enable remote debugging?
https://docs.aws.amazon.com/silk/latest/developerguide/remote-debugging.html

**Comment by dschaper** [comment]
Hi, this seems like a Feature Request so I'll direct you to our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
