### ISSUE TITLE
Local DNS requests always forwarded from Windows

### ISSUE THREAD

**Issue by LePousson** [pi-hole/pi-hole#4234]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Ubuntu 21.04
- Platform:  Raspberry Pi 4

### Expected behavior

I'd like the local DNS requests like toto.domain.com to be managed by Local DNS instead of beeing forwarded to external DNS servers, and then give the local IP address.

### Actual behavior / bug

From my Windows PC, I get my Public IP when typing "nslookup toto.domain.com" instead of hetting the local IP. I had to use Windows HOSTS file to get a workaround.

### Steps to reproduce

1. Install latest Pi-Hole on Ubuntu 21.04
2. Set Local DNS rules
3. Type "nslookup toto.domain.com" within the Command Prompt

## Debug Token

- URL:  https://tricorder.pi-hole.net/qwyhcd26fk

### Screenshots

I think that no screenshots are needed

### Additional context

N/A

**Comment by dschaper** [comment]
What is the exact domain that Windows is looking up? 

`nslookup` on Windows will add any local suffixes if you do not terminate the domain with a final anchor period. 

`nslookup toto.domain.com` will append on the local suffix, `nslookup toto.domain.com.` will not. 

Does the behavior you describe only happen with Windows or does it happen with other operating systems?

Also, you're using Apache and Ubuntu 21, both of which are unsupported.

**Comment by dschaper** [comment]
I don't see where you have configured Pi-hole to know your domains? How have you set that up? 

Are you trying to set up splilt horizon to mask a real domain with local addresses?

**Comment by LePousson** [comment]
Ubuntu 21 not supported ??? Oh s**t I missed that :'(

But it was working perfectly when I set all this up, but 2 or 3 days ago, it stopped working and PiHole is since then forwarding requests to external DNS...

Yes the behavior only happens with windows, I tried from my NAS within a SSH session, I get the local IPs ...

I tried both with and without the final anchor period, buit still getting the Public IP on Windows PC.

Anything I should check or try ?

**Comment by dschaper** [comment]
Check `ipconfig` and list the DNS servers that Windows is using. It sounds like it may not be using Pi-hole, or may have Pi-hole along with another server configured. Also check to see if there are IPv6 DNS servers listed as well. 

For Pi-hole to work, it needs to be the only DNS server.

**Comment by LePousson** [comment]
IPv6 is disabled on my devices and there ius only 1 DNS, the Pi-Hole box :=)

But it still gives the public IP ...

Carte Ethernet LAN :

   Suffixe DNS propre à la connexion. . . :
   Description. . . . . . . . . . . . . . : Intel(R) Ethernet Controller (2) I225-V
   Adresse physique . . . . . . . . . . . : 24-4B-FE-5A-40-8F
   DHCP activé. . . . . . . . . . . . . . : Non
   Configuration automatique activée. . . : Oui
   Adresse IPv4. . . . . . . . . . . . . .: 192.168.3.2(préféré)
   Masque de sous-réseau. . . . . . . . . : 255.255.255.0
   Passerelle par défaut. . . . . . . . . : 192.168.3.1
   Serveurs DNS. . .  . . . . . . . . . . : 192.168.3.4
   NetBIOS sur Tcpip. . . . . . . . . . . : Activé

nslookup ds2411.lepousson.net.

Serveur :   linux.lepousson.net
Address:  192.168.3.4

Réponse ne faisant pas autorité :
Nom :    lepousson.net
Address:  91.*.*.*
Aliases:  ds2411.lepousson.net

It should have replied : 192.168.3.100

**Comment by dschaper** [comment]
Does the web interface show this query and show it as forwarded?

**Comment by LePousson** [comment]
Here is what I found in the "tail pihole.log" section : 

Jul 22 19:45:59 dnsmasq[108184]: query[PTR] 4.3.168.192.in-addr.arpa from 192.168.3.2
Jul 22 19:45:59 dnsmasq[108184]: /etc/pihole/local.list 192.168.3.4 is linux.lepousson.net
Jul 22 19:45:59 dnsmasq[108184]: query[A] ds2411.lepousson.net from 192.168.3.2
Jul 22 19:45:59 dnsmasq[108184]: /etc/pihole/custom.list ds2411.lepousson.net is 192.168.3.100
Jul 22 19:45:59 dnsmasq[108184]: query[AAAA] ds2411.lepousson.net from 192.168.3.2
Jul 22 19:45:59 dnsmasq[108184]: cached ds2411.lepousson.net is NODATA-IPv6
---------------

**Comment by dschaper** [comment]
Okay, looks to me like Pi-hole is sending the right responses and since there are other clients that are getting the intended IP, I think this is a Windows configuration issue. 

The best place to get support for that would be in our community forum at https://discourse.pi-hole.net and since you are running unsupported (apache) you'll need to use the community help section. We watch that section as well so you're not being pushed off.

**Comment by dschaper** [comment]
Pi-hole is responding with an A record but the `nslookup` output shows a CNAME alias. So I don't really think Windows is getting the information from Pi-hole.

**Comment by LePousson** [comment]
Yes that's what I think too, but how the hell is this crappy Windows getting its reply ? That's the question !

And don't worry, I know you're not pushing me off, as a proof, you just spent a moment talking to me ... Thanks for that !

**Comment by yubiuser** [comment]
Are you running any software that might intercept DNS traffic (like AVAST real site)?

**Comment by LePousson** [comment]
Oh my gooooooooood :-( How can I have missed that ??

I just disabled my AVAST Security agents and ... MIRACLE !!! I get the local IP ...

Thanks @yubiuser to have made me think about this ;)
