### ISSUE TITLE
Wireguard devices not allowed to resolve DNS

### ISSUE THREAD

**Issue by ampfinger** [pi-hole/pi-hole#4238]
### Versions
- Pi-hole:  v5.4
- AdminLTE:  5.6
- FTL:  5.9 
(All latest Beta, pihole -up running today)

### Platform
- OS and version:  Raspberry OS latest version
- Platform:  Raspberry Pi

### Expected behavior

Devices connected via wireguard can resolve DNS addresses

### Actual behavior / bug

Wireguard devices cannot resolve DNS names, in the logs you cant see attempts by this devices

### Steps to reproduce

1. Build master, dev or beta is running on an outdated version, everything is working
2. pihole -up , version updated
3. Resolve internal networking but devices via Wireguard can Not resolve anything

## Debug Token

- URL:  https://tricorder.pi-hole.net/mqh8krtic1

## Additional Information

- Reboot:  does not make it Work again
- Update to master build: wireguard devices can resolve names
- If I switch settings in pihole (for example Switch from "Listen on all interfaces" to "Listen on all interfaces, permit all origins") then it is working again. If I revert this setting it keeps working. That is my current workaround.

**Comment by dschaper** [comment]
How was Wireguard installed? Did you use something like PiVPN?

**Comment by ampfinger** [comment]
I installed separately without PiVPN but I can confirm it is the same issue as in the discussion via discourse

**Comment by mads256h** [comment]
You can fix this by going to the web admin page.
Go to *Settings* and then the *DNS* tab.
Then you can change the settings under *Interface listening behavior*.
Try changing it to *Listen on all interfaces* if that doesnt work try changing it to *Listen on all interfaces, permit all origins*.

**Comment by dschaper** [comment]
There's an explanation on the linked Discourse thread that covers what is happening, I think. 

I need to do some experimenting on it but I should be able to get a fix for it in to development.

**Comment by ampfinger** [comment]
Thanks a lot, it's working :) 
Just one Error at logrotate update part but this issue (wireguard) can bei closed :)
