### ISSUE TITLE
PiHole DNS Conditional Forwarding Does Not Allow Non-Standard CIDR Ranges

### ISSUE THREAD

**Issue by spiceywasabi** [pi-hole/pi-hole#4245]
### Versions

Pi-hole v5.3.1
Web Interface v5.5
FTL v5.8.1

### Platform
Ubuntu 20.04, VM

### Expected behavior

I attempted to enable PiHole conditional forwarder to my DHCP server. My subnet is a /22 and I expected to enter per the instructions the whole DHCP range (/22) and the DHCP server. 

### Actual behavior / bug

Pi Hole does not accept this range and instead says I must use a /8 /16 /24 etc. However these are either too narrow or too wide. Ideally this should allow any CIDR like the internal DHCP option does. 

### Steps to reproduce

1. Go to Settings -> DNS and set Conditional forwarder with a custom CIDR that is not one of based on any class ranges. 

## Debug Token

I don't think this is needed, but I can collect if needed

### Screenshots

_If applicable, add screenshots to help explain your problem._
<img width="465" alt="Screen Shot 2021-07-27 at 4 10 19 PM" src="https://user-images.githubusercontent.com/69662763/127239399-bb4da811-1ad2-4dc7-8e4d-c69c72eb778e.png">

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
This is a dnsmasq limitation. The Pi-hole devs have requested that the dnsmasq devs change this. Request is pending action.

**Comment by dschaper** [comment]
This isn't something we can fix, it is a limitation of the underlying `dnsmasq`.

I'd consider this to be a feature request but it's probably not going to be helpful to open an FR on this since it's pretty much out of our control.

In the meantime you can use multiple natural mask ranges, i.e. for a /22 you can use a few /24s.
