### ISSUE TITLE
Debian: installs packages before checking if host is a supported OS

### ISSUE THREAD

**Issue by iam-TJ** [pi-hole/pi-hole#4249]
We were about to experiment with enhancing our existing dnsmasq install on Debian Bullseye with pi-hole.

Running the installer causes packages to be installed before reporting "Unsupported OS". 

The installer should check for unsupported OS before initiating any changes.

**Comment by dschaper** [comment]
The installer needs a few packages to be able to determine if the OS is supported.

Bullseye should be supported in the next release, and you can always follow the instructions provided to install on an unsupported OS if you'd like.

In the future please follow the instructions on the template that you were asked to fill out. It helps us help you.
