### ISSUE TITLE
DoH and DNSSEC

### ISSUE THREAD

**Issue by Night1** [pi-hole/pi-hole#4252]
### Versions

Pi-hole v5.3.1 
Web Interface v5.5 
FTL v5.8.1

### Platform
Description:    Raspbian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
### Expected behavior

When using Cloudflared (cloudflared version 2021.5.9 (built 2021-05-21-1541 UTC)) and have enabled DNSSEC within Pihole DoH does not work. while when having disabled DNSSEC in pihole DoH works as well as DNSSEC is validated by cloudflared but not local at PiHole

### Actual behavior / bug

Pihole should validate DNSSEC

### Steps to reproduce

Install Cloudflared set DNS Servers in pihole to 127.0.0.1#5053 and ::1#5053 

cloudflared config: 

proxy-dns: true
proxy-dns-port: 5053
proxy-dns-upstream:
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://[2606:4700:4700::1111]/dns-query
  - https://[2606:4700:4700::1001]/dns-query

Validate at https://1.1.1.1/help

**With DNSSEC Enabled** 

Connected to 1.1.1.1 | No
-- | --
Using DNS over HTTPS (DoH) | No
Using DNS over TLS (DoT) | No
Using DNS over WARP | No
AS Name | Cloudflare
AS Number | 13335
Cloudflare Data Center | OSL

**With DNSSEC Disabled**

Connected to 1.1.1.1 | Yes
-- | --
Using DNS over HTTPS (DoH) | Yes
Using DNS over TLS (DoT) | No
Using DNS over WARP | No
AS Name | Cloudflare
AS Number | 13335
Cloudflare Data Center | OSL

## Debug Token

https://tricorder.pi-hole.net/chwakyb2lr
-->

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
https://community.cloudflare.com/t/using-dnssec-and-doh-with-pihole-and-cloudflared/212969

**Comment by Night1** [comment]
@dschaper  I'm aware of that one . How ever dnssec validation should not be left to one place and should be validated as close to client as possible otherwise what is the point of dnssec if trust is still left to Cloudlfare or Google? 

RFC4033 -6  Even requires validation to be at the resolver as in this case pihole is the resolver of clients in a given network. 


https://datatracker.ietf.org/doc/html/rfc4033#section-6


>    A security-aware resolver has to be able to perform cryptographic
>    functions necessary to verify digital signatures using at least the
>    mandatory-to-implement algorithm(s).  Security-aware resolvers must
>    also be capable of forming an authentication chain from a newly
>    learned zone back to an authentication key, as described above.  This
>    process might require additional queries to intermediate DNS zones to

**Comment by jfb-pihole** [comment]
The problem is with the test site, not with Pi-hole.  When you are doing DNSSEC in your upstream resolver (i.e. unbound or the like), that software does the DNSSEC authentication.  Adding Pi-hole as a second DNSSEC validator will not change the answer.

Related discussion here:  https://discourse.pi-hole.net/t/from-the-reddit-discussion/48071

**Comment by Bucking-Horn** [comment]
You issue likely is with Cloudflare's website tool incorrectly reporting information, see https://community.cloudflare.com/t/cloudflare-dot-and-dnssec/118414/20.

**Comment by Night1** [comment]
> The problem is with the test site, not with Pi-hole. When you are doing DNSSEC in your upstream resolver (i.e. unbound or the like), that software does the DNSSEC authentication. Adding Pi-hole as a second DNSSEC validator will not change the answer.
> 
> Related discussion here: https://discourse.pi-hole.net/t/from-the-reddit-discussion/48071

You are right it will not change the answer, but will detect and prevent mitm between pihole and resolver.  Chain of trust should always be maintained (for most part there are bugs in Dnssec protocol)   From a security point of view validation should always be as close to end user as possible. Zerotrust principle would put validation on clinet itself  as a proxy service. 

 

@Bucking-Horn 

You are right using CLI i was able to verify 
dig sigok.verteiltesysteme.net @192.168.111.13 (should return A record) it does
dig sigfail.verteiltesysteme.net @192.168.111.13 -p 5053 (should return SERVFAIL) it also does


> @pi:/home/dns-01# dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5053
> 
> ; <<>> DiG 9.10.3-P4-Raspbian <<>> sigfail.verteiltesysteme.net @127.0.0.1 -p 5053
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: **SERVFAIL**, id: 16034
> ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;sigfail.verteiltesysteme.net.  IN      A
> 
> ;; Query time: 3 msec
> ;; SERVER: 127.0.0.1#5053(127.0.0.1)
> ;; WHEN: Thu Jul 29 22:41:09 UTC 2021
> ;; MSG SIZE  rcvd: 57
> CLI never lies. 
> 

This is the expected results so bug is in cf side in validation.  
Thank you all for your help 




when all alse fails CLI will tell you the right answer.

**Comment by jfb-pihole** [comment]
"but will detect and prevent mitm between pihole and resolver"

This would be difficult to do when both the Pi-hole and Cloudflared are running on the same chip and only communicating internally in the loop back IP.
