### ISSUE TITLE
Fedora 34 should be added to the list of supported OSs

### ISSUE THREAD

**Issue by danieldemus** [pi-hole/pi-hole#4254]
### Versions
- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A

### Platform
- OS and version:  Fedora 34
- Platform:  any

### Expected behavior

Fedora 34 has been out for some time now. The installer stops saying it is unsupported. When the OS check is disabled, installation completes succesfully.

### Actual behavior / bug

The DNS record doesn't include 34 for fedora.

### Steps to reproduce

Start the installer script as directed in the docs.
Installer stops after complaining about unsupported OS.

**Comment by dschaper** [comment]
Thank you for the report.

It's not supported because we don't have any developers that use it or are able to provide support for it if there are issues.

As you have seen you can override the check and install anyways.
