### ISSUE TITLE
Missing group read permissions for gravity.db file

### ISSUE THREAD

**Issue by lkwilson** [pi-hole/pi-hole#4256]
### Versions

- Pi-hole:  v5.3.1 (Latest: v5.3.1)
- AdminLTE:  v5.5 (Latest: v5.5)
- FTL:  v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  macOS Big Sur v11.4

- Platform:  Raspberry Pi Model B

### Expected behavior

1. Navigate to admin console in browser
2. Group Management > Groups
3. Groups are loaded and displayed

### Actual behavior / bug

1. Install pihole with pipe to bash script on main webpage
2. Navigate to admin console in browser
3. Group Management > Groups
4. I get the following errors:

I get an alert saying:
```
DataTables warning: table id=groupsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
```

Looking at the network tab in chrome dev tools, the groups.php request has a body response of:
```
Error connecting to database
/etc/pihole/gravity.db: Unable to open database: unable to open database file
```

Looking at permissions on `/etc/pihole/gravity.db`, it has 
```
-rw--w---- 1 pihole pihole 5025792 Jul 31 09:19 /etc/pihole/gravity.db
```

Running the following resolves the issue:
```
sudo chmod g+r /etc/pihole/gravity.db
```

### Steps to reproduce

1. Navigate to admin console in browser
2. Click on Group Management > Groups

If the error does not occur, you can remove group read permissions on `/etc/pihole/gravity.db`: 
```
sudo chmod g-r /etc/pihole/gravity.db
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/6a7xq2riqh

### Additional context

This problem can be fixed with the following:
```
sudo chmod g+r /etc/pihole/gravity.db
```

**Comment by dschaper** [comment]
Thanks for the report. 

The startup process should be setting the permissions on that file to `664`, a stock install shows:

`-rw-rw-r--  1 pihole pihole   4665344 Jul 25 04:53 gravity.db` 

We could add a `chown` and `chmod` to the service startup script, I'm not sure if `pihole-FTL` manages permissions on the file or just tries to open it.

Just to clarify, there is no relation between the group permissions on the database file and Pi-hole's Group Management features. `pihole-FTL` runs as `pihole` user and that user had `rw` permissions on the file. I think what may have actually fixed the problem was just a restart of the node. 

But we can take a look at ensuring `664` is set on that file. @pi-hole/core-approvers Thoughts?

**Comment by lkwilson** [comment]
I just ran 
```
sudo pihole -g
```
and it reset the permissions back to g-r, so I had to run `sudo chmod g+r ...` again

**Comment by dschaper** [comment]
Do you have any file access lists or permissions settings on that partition?

```plain
dan@raspberrypi:/etc/pihole $ ls -la /etc/pihole/gravity.db
-rw-rw-r-- 1 pihole pihole 4665344 Jul 25 04:53 /etc/pihole/gravity.db
dan@raspberrypi:/etc/pihole $ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 84247 domains
  [i] List has been updated

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 84247 (84247 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 1
  [i] Number of exact whitelisted domains: 1
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
dan@raspberrypi:/etc/pihole $ ls -la /etc/pihole/gravity.db
-rw-rw-r-- 1 pihole pihole 5025792 Jul 31 16:56 /etc/pihole/gravity.db
```

**Comment by dschaper** [comment]
Don't use `sudo` please, that will cause you issues.

**Comment by lkwilson** [comment]
```
p@nkd:~$ ls -la /etc/pihole/gravity.db
-rw-rw---- 1 pihole pihole 5025792 Jul 31 09:53 /etc/pihole/gravity.db
p@nkd:~$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 84247 domains
  [i] List stayed unchanged

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 84247 (84247 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
p@nkd:~$ ls -la /etc/pihole/gravity.db
-rw--w---- 1 pihole pihole 5025792 Jul 31 09:58 /etc/pihole/gravity.db
```

**Comment by lkwilson** [comment]
I don't have any access control list, but I do have `umask 0077` in my `~/.bashrc`

**Comment by dschaper** [comment]
Okay, that is probably what is changing file permissions.

I was able to confirm that having mode `644` on that file does seem to bork Group Management and that shouldn't be happening so there is a bug here that needs fixing in relation to that.

**Comment by lkwilson** [comment]
Removing my umask resolved the issue

**Comment by lkwilson** [comment]
```
p@nkd:~$ ll /etc/pihole/gravity.db 
-rw--w---- 1 pihole pihole 5025792 Jul 31 09:58 /etc/pihole/gravity.db
p@nkd:~$ pimod -g
-bash: pimod: command not found
p@nkd:~$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 84247 domains
  [i] List stayed unchanged

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 84247 (84247 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
p@nkd:~$ ll /etc/pihole/gravity.db 
-rw-rw-r-- 1 pihole pihole 5025792 Jul 31 10:02 /etc/pihole/gravity.db
p@nkd:~$ umask
0022
```

**Comment by dschaper** [comment]
Thanks for the confirmation.

We should think about moving the databases to somewhere like `/var/lib/pihole` to make sure that state files are not in the same place as configuration files. This would let you keep your `/etc/` directory with a more restrictive default mask and let the databases be set with the permissions needed to run proper. 

That being said, version 6 of Pi-hole will have a lot of changes with the web interface and a new RESTful API that will simplify a lot of things.

**Comment by yubiuser** [comment]
The fix has been released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
