### ISSUE TITLE
Changing from Google DNS to OpenDNS gives me errors

### ISSUE THREAD

**Issue by greg5678** [pi-hole/pi-hole#426]
I changed from the Google dns servers to OpenDNS in the /etc/dnsmasq.d/01-pihole.conf file and when I ran this command systemctl status -l dnsmasq.service it gave me an error 

pi@raspberrypi:~ $ systemctl status -l dnsmasq.service
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Sun 2016-04-03 20:57:12 EDT; 6min ago
  Process: 383 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=1/FAILURE)
  Process: 320 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

pi@raspberrypi:~ $ sudo service dnsmasq restart
Job for dnsmasq.service failed. See 'systemctl status dnsmasq.service' and 'journalctl -xn' for details.

**Comment by nate-ubiquisoft** [comment]
Can you paste the advanced output from systemctl by invoking `sudo`? The `-l` option does not work without root.

**Comment by greg5678** [comment]
pi@raspberrypi:~ $ sudo systemctl status -l dnsmasq.service
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Sun 2016-04-03 21:04:58 EDT; 21h ago
  Process: 817 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=1/FAILURE)
  Process: 814 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Apr 03 21:04:58 raspberrypi dnsmasq[814]: dnsmasq: syntax check OK.
Apr 03 21:04:58 raspberrypi dnsmasq[817]: dnsmasq: bad address at line 34 of /etc/dnsmasq.d/01-pihole.conf.save
Apr 03 21:04:58 raspberrypi dnsmasq[817]: bad address at line 34 of /etc/dnsmasq.d/01-pihole.conf.save
Apr 03 21:04:58 raspberrypi systemd[1]: dnsmasq.service: control process exited, code=exited status=1
Apr 03 21:04:58 raspberrypi systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Apr 03 21:04:58 raspberrypi systemd[1]: Unit dnsmasq.service entered failed state.
pi@raspberrypi:~ $

**Comment by PromoFaux** [comment]
@greg5678 Did you change the upstream DNS servers manually in `/etc/dnsmasq.d/01-pihole.conf`? 

Try running the install script again (we've just pushed an update, anyway). This will give you the option to select OpenDNS as your upstream DNS during the install process.

**Comment by greg5678** [comment]
I did but it gave me that error when I retried to select OpenDNS and it is still using Google DNS.

**Comment by greg5678** [comment]
Then I changed the 01-pihole.conf file to the ip of OpenDNS's servers.

**Comment by Mcat12** [comment]
Did you make a `01-pihole.config.save` file? The presence of that extra file might be causing it. Backup/delete that file and try starting lighttpd.

**Comment by greg5678** [comment]
No I did not.

**Comment by Mcat12** [comment]
Can you run `ls -all /etc/dnsmasq.d/` and post the output?

**Comment by greg5678** [comment]
I reinstalled the os and the pi-hole software. To recreate the problem get a fresh install of Raspbian and install pi-hole with sudo curl -L install.pi-hole.net | bash then select OpenDNS (there was a star symbol by the Google DNS option). Then Google DNS is selected instead of OpenDNS.

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/14289920/e56b6f58-fb54-11e5-8dea-63256d94e7a0.png)

This screen? I think I know whats happened. Did you press space bar to select OpenDNS or just press enter?

The `*` indicates which option is selected. We'll improve the wording on that screen in the next release

**Comment by greg5678** [comment]
I selected OpenDNS but then it said that Google DNS was selected. I pressed enter.

**Comment by PromoFaux** [comment]
:) So did it work when you selected it with the space bar?

**Comment by greg5678** [comment]
It said it selected OpenDNS but when I went to my mac's dns page in system preferences it still said I was using the Google DNS servers. This was after I disconnected and reconnected to my network. The pi is set as the default dns server. There is no other dns server on my router. I went on https://www.opendns.com/welcome/ and it said I wasn't using OpenDNS.

**Comment by greg5678** [comment]
Never mind I got it working.

**Comment by PromoFaux** [comment]
OK! How did you get it working in the end?
