### ISSUE TITLE
Page's source code instead of page itself

### ISSUE THREAD

**Issue by MSS00** [pi-hole/pi-hole#4267]
### Versions

- Pi-hole:  Pi-hole version is v5.3.1 (Latest: v5.3.1)
- AdminLTE:  AdminLTE version is v5.5.1 (Latest: v5.5.1)
- FTL:  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Debian 10

- Platform:  PC (LAN Server)

### Expected behavior

Appearance of Pi-hole's admin panel.

### Actual behavior / bug

It shows source code of the page as raw text.

### Steps to reproduce

1. Use Pi-hole's installation script (`curl -sSL https://install.pi-hole.net | bash`)
2. Try to go to admin panel via browser
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/wsQnDONI/

### Screenshots

https://imgur.com/hjSj14O

**Comment by yubiuser** [comment]
You're running apache as web server, which is unsupported.

```
[80] is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
```

Please look for help from other users at the community section of https://discourse.pi-hole.net

**Comment by MSS00** [comment]
What should I use then?

**Comment by yubiuser** [comment]
Lighttpd, which is already installed. It might be enough to disable apache.
