### ISSUE TITLE
pihole istall error

### ISSUE THREAD

**Issue by TimyIsCool** [pi-hole/pi-hole#4268]
### Versions

- Pi-hole:  latest install as of 10/08/21

### Platform

- OS and version:  Raspbian OS 64 

- Platform:  Raspberry Pi

### Expected behavior: Install will finish

_A clear and concise description of what you expected to happen._

### Actual behavior / bug 
![image](https://user-images.githubusercontent.com/74112751/128862723-7c252d36-e38e-4dd5-bb71-a77ac1f79c80.png)

E: Package 'php8.0-json' has no installation candidate

_A clear and concise description of what the bug is._

### Steps to reproduce

No Idea

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
This is fixed by https://github.com/pi-hole/pi-hole/pull/4135 and will be included in the next release

**Comment by TimyIsCool** [comment]
> This is fixed by #4135 and will be included in the next release

okay, when will that be?

**Comment by yubiuser** [comment]
No fixed schedule. It's done when it's done.

**Comment by TimyIsCool** [comment]
> No fixed schedule. It's done when it's done.

okay
