### ISSUE TITLE
pihole -up error: Could not update local repository.

### ISSUE THREAD

**Issue by sgreadly** [pi-hole/pi-hole#4272]
### Versions

  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
RaspberryPi OS

Linux 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux

- OS and version:  

- Platform:  Raspberry Pi 3B+

### Expected behavior

Pihole to update Web Interface successfully

### Actual behavior / bug

It keeps failing

```
$ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	update available
  [i] FTL:		up to date

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...
  : Could not update local repository. Contact support.
```

### Steps to reproduce

Simply run pihole -up

I can confirm there's no index.lock (like others reported that may cause this). 

## Debug Token

- URL:  https://tricorder.pi-hole.net/y6EwXJKP/

### Screenshots

N/A

### Additional context

N/A

Thanks.

**Comment by dschaper** [comment]
It looks like you are running `nginx` which is unsupported.

```plain
[80] is in use by nginx (https://docs.pi-hole.net/main/prerequisites/#ports)
[80] is in use by nginx (https://docs.pi-hole.net/main/prerequisites/#ports)
[80] is in use by nginx (https://docs.pi-hole.net/main/prerequisites/#ports)
[80] is in use by nginx (https://docs.pi-hole.net/main/prerequisites/#ports)
```

Changes were made to the `/var/www/html/admin` directory that break the update process. You'll need to use the community support forum for the unsupported changes:

```plain
[i] Diff: diff --git a/.gitattributes b/.gitattributes
          old mode 100644
          new mode 100755
          diff --git a/.github/ISSUE_TEMPLATE.md b/.github/ISSUE_TEMPLATE.md
          old mode 100644
          new mode 100755
          diff --git a/.github/PULL_REQUEST_TEMPLATE.md b/.github/PULL_REQUEST_TEMPLATE.md
          old mode 100644
          new mode 100755
          diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
          old mode 100644
          new mode 100755
          diff --git a/.github/workflows/phpstan.yml b/.github/workflows/phpstan.yml
          old mode 100644
          new mode 100755
          diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
          old mode 100644
          new mode 100755
```

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by sgreadly** [comment]
Thanks! Didn't know it wasn't supported. 

No worries, I'll see what I can do.

**Comment by sgreadly** [comment]
Yea turns out my permissions were whack :) Just corrected that and it updated successfully. 

Thanks for the advice!
