### ISSUE TITLE
`pihole -v -f -c` error if WebAdmin not installed, due to scripts under `/opt/pihole` not agreeing with each other

### ISSUE THREAD

**Issue by subnut** [pi-hole/pi-hole#4279]
```
$ sudo rm /etc/pihole/GitHubVersions 
$ pihole -v -p
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.5.1)
$ pihole -v -f
  FTL version is v5.8.1 (Latest: v5.8.1)
$ sudo /opt/pihole/updatecheck.sh x remote
$ pihole -v -p
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.8.1)
$ pihole -v -f
  Current FTL version is v5.8.1.
$ pihole -v -f -l
  Invalid Option! Try 'pihole -v --help' for more information.
$ 
```

**Comment by PromoFaux** [comment]
You'll need to provide some more information. (This is why there is a template for new issues)

At the very minimum:

What are you expecting to see?

What are you actually seeing that contradicts what you are expecting to see?

**Comment by subnut** [comment]
My apologies. I thought that seeing
```
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.5.1)
$ pihole -v -f
  FTL version is v5.8.1 (Latest: v5.8.1)
```
and this
```
$ pihole -v -a
  AdminLTE version is -1 (Latest: v5.8.1)
$ pihole -v -f
  Current FTL version is v5.8.1.
```
was enough to make some bells ring.

---

I tried tunning `pihole -v -f -l` on a Pi-hole install without WebAdmin. It showed this error -
```
$ pihole -v -f -l
  Invalid Option! Try 'pihole -v --help' for more information.
```

So I dug into the code, and I discovered that `updatecheck.sh` caches the latest versions to the file `/etc/pihole/GitHubVersions`, and `version.sh` reads the latest version from that file if available. Now, the problem is, since I didn't have WebAdmin installed, `INSTALL_WEB_INTERFACE` was set to `false` in `/etc/pihole/setupVars.conf`, and so, `updatecheck.sh` didn't add the latest version of WebAdmin to `/etc/pihole/GitHubVersions` (due to the `if`-block at line 56). So, the file now contains -
```
v5.3.1 v5.8.1
```
Which are the versions of pihole and pihole-FTL, respectively.


Now, when I run `pihole -v -f -l`, `version.sh` notices that `/etc/pihole/GitHubVersions` exists, and so it reads the versions from that file instead of querying from the GitHub API. It naively assumes that `/etc/pihole/GitHubVersions` contains three entries for the latest versions of pihole, WebAdmin, and pihole-FTL (see line 95-97 of `version.sh`).
But there are only two entries! So, when I run `pihole -v -f -l`, it tries reading the latest version of pihole-FTL from that file, and gets an empty string instead! So, it gets very confused, and screams _Invalid Option!_ at me -
```
$ pihole -v -f -l
  Invalid Option! Try 'pihole -v --help' for more information.
```

---

My pull request (#4280) hopes to fix that issue.

**Comment by PromoFaux** [comment]
Right, I see now. I think your pull request addresses the wrong area, as that part is correct - there is no sense in getting the remote version of the web interface if it is not installed.

Take a look at the `getRemoteVersion()` function in `version.sh`, i _think_ that's where the fix should be, in the case statement.

I think that the `"FTL"` part of the case statement should be conditional. Totally untested pseudocode here:

```bash
case $daemon in
          "pi-hole"   )  
              echo "${arrCache[0]}";;
          "AdminLTE"  ) 
                if [[ "${INSTALL_WEB_INTERFACE}" == true ]]; then
                    echo "${arrCache[1]}";;
                else
                    echo "Not Installed" #this part might not be needed at all
                fi
          "FTL"       )  
               if [[ "${INSTALL_WEB_INTERFACE}" == true ]]; then
                    echo "${arrCache[2]}"
               else
                   echo "${arrCache[1]}"
              fi ;;
        esac
```

**Comment by subnut** [comment]
Ok. So let me update the PR accordingly.

**Comment by PromoFaux** [comment]
Make sure you test it first, I haven't tried this at all 😅

**Comment by subnut** [comment]
One question. Currently, `pihole -v -a -c` shows current version as `-1` if WebAdmin isn't installed. Should we do the same for the Remote version too?

**Comment by PromoFaux** [comment]
I wonder, actually, if the web interface is not installed - perhaps it should just return an empty string in this case. Act as thought eh command `pihole -v -a` doesn't even exist. Maybe... I've not had any coffee yet, I might not be thinking clearly.

**Comment by subnut** [comment]
My opinion is that we should echo _WebAdmin not installed_ -- and return `1` as the exit code to indicate the same for scripts.
What do you think?

**Comment by subnut** [comment]
Let me try out 9e7c4bc on my Pi, and I'll report if it works as my previous comment

**Comment by yubiuser** [comment]
@subnut 

Are you still going to fix the issue?

**Comment by subnut** [comment]
@yubiuser #4370
