### ISSUE TITLE
Blacklist.sh and Whitelist.sh ignore overrides (pihole.conf)

### ISSUE THREAD

**Issue by Zer0t3ch** [pi-hole/pi-hole#428]
##### Expected Behaviour:
Blacklist.sh and Whitelist.sh should source pihole.conf 

##### Actual Behaviour:
They do not source pihole.conf

##### Steps to reproduce this issue:
1. Create a pihole.conf
1. execute either of the scripts.

**Comment by PromoFaux** [comment]
Good catch, will be fixed in the next release pending Pull Release #429

**Comment by PromoFaux** [comment]
@Zer0t3ch This is now fixed in version 2.6. `curl -L https://install.pi-hole.net | bash` to update
