### ISSUE TITLE
PiHole reconfiguration doesn't remove lighttpd

### ISSUE THREAD

**Issue by pluc** [pi-hole/pi-hole#4281]
### Versions
- Pi-hole:  5.3.1
- AdminLTE:   5.8.1
- FTL:  5.8.1

-
### Platform
- OS and version:  Raspbian 10.10
- Platform:  RaspberryPi

### Expected behavior

When AdminLTE is present and PiHole is reconfigured to remove the Web Admin, it should remove lighttpd and the AdminLTE web files

### Actual behavior / bug

It doesn't remove neither

### Steps to reproduce

1. Install PiHole with Web Admin
2. Reconfigure PiHole without Web Admin
3. Notice the web admin still present

## Debug Token

- URL:  https://tricorder.pi-hole.net/kuR5WDQm/

**Comment by yubiuser** [comment]
I think there is a misunderstanding: `reconfigure` does not and is not intended to uninstall Pi-hole or its components. If you installed the web interface already, in the second round it simply won't be install it again, but does not try to uninstall it.
