### ISSUE TITLE
Pi-Hole blocking ads but Web interface counter and JSON output both show ads blocked today: 0

### ISSUE THREAD

**Issue by hopkinsph** [pi-hole/pi-hole#4293]
Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Ubuntu 20.04 LTS (64 bit)

- Platform:  Raspberry Pi 3B

### Expected behavior

_A clear and concise description of what you expected to happen._

"Ads Blocked Today" counter increasing with each blocked ad.

### Actual behavior / bug

_A clear and concise description of what the bug is._

Fresh installs of both Ubuntu and Pi-Hole. No errors reported. Ads are being successfully blocked. However the "Ads Blocked Today" counter on the Web interface and on the JSON interface indicates Ads Blocked Today at 0 (zero).

## Debug Token

- URL:  https://tricorder.pi-hole.net/7NVTjPXx/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Please visit our Discourse site for additional assistance.
