### ISSUE TITLE
Unable to generate debug log

### ISSUE THREAD

**Issue by SweeTi-pie** [pi-hole/pi-hole#4294]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.3.1
- FTL:  5.8.1

### Platform

- OS and version:  Debian  10.8

- Platform:   Raspberry Pi

### Expected behavior

generate debug log

### Actual behavior / bug

Unable to generate debug log at is it stuck at  *** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds) " for more than 30 mins.

i'am not using pi hole's dhcp service.

### Steps to reproduce

1. Go to 'pihole -d'

**Comment by yubiuser** [comment]
There is an bug in the `dhcp_discover` function when offers contain `xid`.

It is fixed in the `release/v5.9` branch ready.

https://github.com/pi-hole/FTL/commit/9d99bbe8fd569f5682b6c3f06e997203f352e736

**Comment by yubiuser** [comment]
Fix with current release
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-released/49544
