### ISSUE TITLE
2.6 not blocking any ads (fixed in 2.6.1)

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#430]
##### Expected Behaviour:
ads should be blocked :)

##### Actual Behaviour:
no ads being blocked, no "gravity.list" lines appearing in pihole.log; traffic is going through the Pi-Hole as I can see all the activity in pihole.log, but nothing is being blocked

##### Steps to reproduce this issue:
upgraded from 2.5.3 to 2.6

I see this line in pihole.log that I think is the problem:

`Apr  4 22:10:14 dnsmasq[459]: failed to load names from (null): Bad address`

Not sure what I messed up here.

**Comment by nate-ubiquisoft** [comment]
Can you post a debug file? Run the debugging option `pihole -d`

**Comment by jradwan** [comment]
Yep. I don't see anything out of the ordinary there, but it's new to me. :)

[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/203746/pihole_debug.txt)

**Comment by nate-ubiquisoft** [comment]
Hmm. Would you be okay trying a fresh install? You can run `pihole uninstall`. I would also recommend doing a `locate pihole` and `locate pi-hole` after to see if there are any artifacts still remaining, and if so, we can get a patch out to remove old files from the previous release.

**Comment by 00firestar00** [comment]
I'm having the same issue on a fresh install of raspbian, and running the curl install command.

queries are getting routed through, but are being passed through to Google DNS (which I chose at startup)

**Comment by PromoFaux** [comment]
Yeah, this was my bad! 2.6.1 has been pushed to fix it. Please don't look at the commit logs to see what I fixed. It's not embarrassing in the slightest... ;)

**Comment by PromoFaux** [comment]
Sod it. Offending code if you're interested.. spot the mistake!:

```bash
	#ensure /etc/dnsmasq.d/01-pihole.conf is pointing at the correct list!
	#First escape forward slashes in the path:
	adList=${adList//\//\\\/}
	#Now replace the line in dnsmasq file
	$SUDO sed -i "s/^addn-hosts.*/addn-hosts=$adlist/" /etc/dnsmasq.d/01-pihole.conf
```

**Comment by 00firestar00** [comment]
Ha, I was in the middle of typing out that the addn-hosts never got updated. I just updated the config manually, and its seems to be working now.

**Comment by PromoFaux** [comment]
Best to update to 2.6.1 because next time `gravity.sh` runs on the `cron` job, it will go back to a blank `addn-hosts` :)

**Comment by jradwan** [comment]
Yep, that fixed it. Thank you!

`Apr  5 08:08:20 dnsmasq[9379]: read /etc/pihole/gravity.list - 203142 addresses`
