### ISSUE TITLE
PIHole become inoperable on AWS Ubuntu instance following reboot.

### ISSUE THREAD

**Issue by ppittle** [pi-hole/pi-hole#4306]
### Versions

  Current Pi-hole version is v5.3.1.
  Current AdminLTE version is v5.5.1.
  Current FTL version is v5.8.1.
### Platform

- OS and version:  Ubuntu 20.04.1

- Platform:  AWS VM EC2 

### Expected behavior

Following a reboot, PIHole will be able to serve dns request traffic as well as upgrade itself.

### Actual behavior / bug

```
ubuntu@AWS-EC2:~$ sudo reboot

#wait 1 minute before re-establishing ssh session

ubuntu@AWS-EC2:~$ pihole -g
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 120^C
```
### Steps to reproduce

1. Create a new AWS Ubuntu VM and Install PiHole
    2. I followed this Guide: https://medium.com/@dion315/setting-up-a-free-pi-hole-on-aws-c24511888973
2. Verify the new PI Hole is functioning as expected and is wonderful.
3. Reboot 
4. Run `pihole -g`

## Debug Token

Upload failed:
```
nc: getaddrinfo for host "tricorder.pi-hole.net" port 9999: Temporary failure in name resolution
```

_Can I manually upload?_

### Screenshots

n/a

### Additional context

I believe the root of the problem is AWS Virtual Machines also try and manipulate DNS at bootup.  From this article: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/

> Manual modifications to the `resolv.conf` file with custom DNS server addresses are lost when you restart the [AWS EC2] instance. 

#### Custom `/etc/netplan/99-custom-dns.yaml`

The article recommends creating a custom netplan, but I could not get this to work:

```
network:
    version: 2
    ethernets:
        eth0:         
            nameservers:
                    addresses: [1.2.3.4, 5.6.7.8]
            dhcp4-overrides:
                    use-dns: false
```
I tried putting in `127.0.0.1` or `8.8.8.8` for `addresses` but neither configuration restored network connectivity following a reboot.

#### Modified `/etc/host`

I added an entry for my custom host name:
```
127.0.0.1 AWSPiHole
```
That helped, but didn't fix everything.  Without this, I would get this failure:

```
ubuntu@AWSPiHole:~$ sudo pihole -g
sudo: unable to resolve host AWSPiHole: Temporary failure in name resolution
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 94
```

**Comment by dschaper** [comment]
Best place for help would be with the author of the guide you followed to set up the AWS instance.
