### ISSUE TITLE
Blocked query type not working when query is whitelisted because it was blocked by gravity

### ISSUE THREAD

**Issue by charlieporth1** [pi-hole/pi-hole#4307]
### Versions

```
pihole -v
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5.1 (Latest: v5.5.1)
  FTL version is v5.8.1 (Latest: v5.8.1)

```
### Platform

- OS and version:  
```
uname -a
Linux ctp-vpn 5.11.0-1017-gcp #19~20.04.1-Ubuntu SMP Thu Aug 12 05:25:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Platform:  GCP AWS and Bare metal

### Expected behavior
Blocked query type not working when query is whitelisted because it was blocked by gravity
Blocked query type

### Actual behavior / bug

Allowed query type

### Steps to reproduce
Run
```
pihole --regex 'whitepages.com;querytype=!A'
  [i] Adding whitepages.com;querytype=!a to the regex blacklist...
  [✓] Reloading DNS lists
```
Then run
```
dig @localhost whitepages.com -t TXT
; <<>> DiG 9.16.1-Ubuntu <<>> @ctp-vpn.local whitepages.com -t txt
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13118
;; flags: qr rd ra; QUERY: 1, ANSWER: 18, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1460
;; QUESTION SECTION:
;whitepages.com.			IN	TXT

;; ANSWER SECTION:
whitepages.com.		2597	IN	TXT	"google-site-verification=3HYHiLK8fsJqqbz6oOySwUKTJQdQ_QtVB64llCEWFDM"
whitepages.com.		2597	IN	TXT	"google-site-verification=KA0kaAzyfPcKrJl2XAanMBg0UQYRE-DTgNsrMfdubBs"
whitepages.com.		2597	IN	TXT	"ip4:198.37.158.50 include:mktomail.com"
whitepages.com.		2597	IN	TXT	"v=spf1 mx a:zgateway.zuora.com include:spf.protection.outlook.com include:mail.zendesk.com -all"
whitepages.com.		2597	IN	TXT	"072_spf.salesforce.com"
whitepages.com.		2597	IN	TXT	"072amazonses.com"
whitepages.com.		2597	IN	TXT	"072mail.zendesk.com"
whitepages.com.		2597	IN	TXT	"072mktomail.com"
whitepages.com.		2597	IN	TXT	"072sendgrid.net ip4:198.37.158.50"
whitepages.com.		2597	IN	TXT	"341389e1079bd12ce2045c1c97e9c0e15d3570d6"
whitepages.com.		2597	IN	TXT	"MS=ms36338884"
whitepages.com.		2597	IN	TXT	"ZOOM_verify_ndCC8455TqOrt6KA1rQ4nw"
whitepages.com.		2597	IN	TXT	"amazonses:x/UQnjP6KsaOEQVl8DNTmTz4tV5YP+WjebZyHl3JFP0="
whitepages.com.		2597	IN	TXT	"atlassian-domain-verification=/LILeM0hoUpAEPbvZEXml7eOanwrPTxXVSyF1X4NpDRV2cmqhtnr/9pa7/haGTCd"
whitepages.com.		2597	IN	TXT	"atlassian-domain-verification=LZMckGzGnQuQn3PPKQKPzIRe2JDTA6Zx2ODJ6avIv6uuKeCGS9SQUs7nUhZjoANx"
whitepages.com.		2597	IN	TXT	"awsALIAS;name=distil-external-1975508251.us-west-2.elb.amazonaws.com.;"
whitepages.com.		2597	IN	TXT	"axSNJz4hx/EptJT5usXvU07T1HXS1MDnhK7DPT2vMdFCVqyZTBDVSe66HKPqVzXltMgK4SQB3k3PtI7BtNUwyg=="
whitepages.com.		2597	IN	TXT	"ca3-728411f3424b418ca95bf435c3c1e1c7"


```
I believe it might have to do with the auto lowercasing of the domain/regex of `!A` to `!a`

I do have `whitepages.com` in the whitelist as well but I do believe this is not the expected behavior  
```
pihole -q whitepages.com
 Match found in exact whitelist
   whitepages.com
```

`pihole -w whitepages.com`
`pihole --regex 'whitepages.com;querytype=!A'`
## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Whitelisting takes precedence over everything. If you have a `pihole -w whitepages.com` then everything is whitelisted. You can't override a whitelist with a partial blacklist.

**Comment by charlieporth1** [comment]
Interesting! Btw thanks for the help earlier and so quickly! If I was to regex whitelist this instead would that be a workaround? Or should I create a feature request called absolute for advance regex types which are the highest priority

**Comment by dschaper** [comment]
What is the end goal for this setup? If you want to block everything except A records then you could just use the regex to blacklist everything except A records. There's no need to add the whitelist entry.

**Comment by jfb-pihole** [comment]
" If I was to regex whitelist this instead would that be a workaround? "

The precedence order is as follows:

1. Exact Whitelist
2. Regex Whitelist
3. Exact Blacklist
4. Blocklist domains (AKA gravity)
5. Regex Blacklist

If a domain is found anywhere from top to bottom, FTL skips the rest of the tests.
