### ISSUE TITLE
Let local-ttl configurable

### ISSUE THREAD

**Issue by starox** [pi-hole/pi-hole#4308]
The local-ttl default is set to 2s in /etc/dnsmasq.d/01-pihole.
It pollutes dns traffic on my network.
It would be nice to have  a way to change this value.

Kind regards,

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
