### ISSUE TITLE
dhcpv6 configuration does not work on pi-hole container in network bridge mode

### ISSUE THREAD

**Issue by w4tsn** [pi-hole/pi-hole#4315]
The current dhcp options for dhcpv6 configure the interface in a way that is not route-able if pihole is run as a container in a bridge network.

```
dhcp-range=::100,::1ff,constructor:${interface},ra-names,slaac,...
```

The `constructor:${interface}` statement instructs dnsmasq to infer the ipv6 prefix from the interface specified. If pihole is run inside a container on an internal bridge network (with IPv6) the prefix inferred is from that bridge network of containers, not the hosts e.g. LAN.

I currently work around this by either of two ways:

- run the container in network mode `host` so it can infer the IP from an interface connected to the LAN
- omit the `constructor` statement and provide the prefix from LAN manually - this also requires to supply the prefix-length option at the end of the dhcp-range, before the leasetime

As the new expert on IPv6 topics here what do you think @JM1 ?

**Comment by dschaper** [comment]
How have you configured IPv6 for the docker engine?

**Comment by dschaper** [comment]
(And are you trying to use DHCPv6? The options listed is purely for generation of an RA with Pi-hole's IPv6 address for DNS, there is no support provided or intended to use Pi-hole as a DHCPv6 server.)

**Comment by w4tsn** [comment]
Thanks for the quick response!

> How have you configured IPv6 for the docker engine?

I'm using podman as orchestrator which uses CNI in rootful mode. I configured the network to use a certain fixed IPv6 prefix that is distinct from the one I get from my ISP through the router since the ISP changes my prefix once in a while. The PiHole container in that network receives an IPv6 address with that prefix and then propagates IP addresses via DHCPv6 from that network since it's instructed to use the prefix of it's interface through the `constructor:eth0` directive.

> (And are you trying to use DHCPv6? The options listed is purely for generation of an RA with Pi-hole's IPv6 address for DNS, there is no support provided or intended to use Pi-hole as a DHCPv6 server.)

That might explain why the docs are so sparse about this topic. From the pihole container env option `DHCP_IPv6` I inferred as much that this is supported.

In this case this might actually be more of a feature request than a bug report then

**Comment by w4tsn** [comment]
> Using the host’s networking namespace does not require any changes to the container image itself (good). As you do trust Pihole for fundamental network functionality anyway I would guess that security implications are low. Being able to change the dhcp-range option (like FritzBox partially allows in the gui) would be cool but that would require effort which is probably not worth the hassle.

I'm with you that from a security perspective this is quite OK and you could do this but in my case I'm using traefik as a reverse-proxy which binds port 80 for more than just PiHole. The base traffic is routed to PiHole but other domains and paths are passed to e.g. Nextcloud. I've not been able to get PiHole to work without binding on Port 80 (which works in a different network namespace but not on the host because traefik already binds it). So that's why in my particular case I require PiHole to work in a non-host network namespace.

> Btw which router did you use before switching to a FritzBox?

The Speedport Smart 3 iirc.

> What was your plan of attack to get Pihole running behind that router? Disable router's dhcp functionality? Does your router allow to advertise a DNSv6-Server (e.g. Unique Local Address (ULA) of Pihole) via router advertisements?

Unfortunately I can't alter the RA messages of the router. I can't change the upstream nor the propagated IPv6 DNS server (it works for IPv4 though, small inconsistency there). First I tried to increase PiHoles RA priority but I think the router already sends the highest prio so it's a race condition. I tried to work around that by using a dhcpv6 relay (to get the DHCPv6 broadcast inside the internal network namespace) and using the DHCPv6 server capabilities of dnsmasq inside PiHole. My client devices even retrieved the DNS server and IP from the DHCPv6 server instead of the RA message of the router. The problem then was, that the PiHole with the above mentioned configuration would then construct IPv6 addresses by the internal IPv6 prefix set in the podman network so they weren't routeable in the LAN. I fixed that by setting a routeable prefix range "manually" instead of using the constructor. I guess I could've set this to the internal network too, not sure though.
