### ISSUE TITLE
Pi-hole v5.4 update - syntax error

### ISSUE THREAD

**Issue by lleonardi** [pi-hole/pi-hole#4322]
### Versions

- Pi-hole:  5.4
- AdminLTE:  5.6
- FTL:  5.9

### Platform

- OS and version:   Ubuntu 16.04.7 LTS

- Platform:  Laptop (intel)

### Expected behavior

No errors reported

### Actual behavior / bug

Updating to v5.4 logged the following error in terminal when swapping databases:

_/opt/pihole/gravity.sh: line 125: "57568" * 2: syntax error: operand expected (error token is ""57568" * 2")_

### Steps to reproduce

1. Go to pihole via SSH
2. Run update command 'pihole -up'
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/7rvVehHk/

### Screenshots

n/a

### Additional context

Update completed nevertheless.

**Comment by yubiuser** [comment]
Line 125 is the check for free space before swapping the database

https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/gravity.sh#L125

Can you run `pihole -g` and see if the error re-occurs?

**Comment by lleonardi** [comment]
Same.

![Capture](https://user-images.githubusercontent.com/250951/132989586-2aef8e02-e918-47ea-9809-0b557249f3a7.PNG)

Also, not a disk space issue:

![Capture](https://user-images.githubusercontent.com/250951/132989676-676c7e83-f6bc-4d29-99c7-a368bdcb923c.PNG)

**Comment by dschaper** [comment]
That line was changed in https://github.com/pi-hole/pi-hole/pull/4202

@jpgpi250 Can you assist?

**Comment by dschaper** [comment]
I think there is an extra set of `"`s that is causing the shell math to fail.

**Comment by dschaper** [comment]
@lleonardi What version of bash is running on that Ubuntu 16?

**Comment by yubiuser** [comment]
I also thought that the quotes. But I don't get the error message running gravity...

**Comment by DL6ER** [comment]
My guess: bash older than 4.4 breaks.

**Comment by dschaper** [comment]
It's a bash version issue we think.

`"$((gravityBlocks * 2))"` should work on older versions of bash as well as current versions, and ShellCheck suggests that format without the `${}` wrapper.

**Comment by lleonardi** [comment]
> @lleonardi What version of bash is running on that Ubuntu 16?

GNU bash, version 4.3.48(1)-release (i686-pc-linux-gnu)

**Comment by dschaper** [comment]
Okay, older versions of bash (pre 4.4) don't parse the current version. We'll put out a fix release to address this. 

```diff
-if [ "${availableBlocks}" -gt "$(("${gravityBlocks}" * 2))" ] && [ -f "${gravityDBfile}" ]; then 
+if [ "${availableBlocks}" -gt "$((gravityBlocks * 2))" ] && [ -f "${gravityDBfile}" ]; then 
```

**Comment by jpgpi250** [comment]
sorry for the late response. No idea what the developpers policy is, but according to [this](https://ubuntu.com/about/release-cycle) and [this](https://endoflife.software/operating-systems/linux/ubuntu), Ubuntu 16.04.7 LTS is passed EOL.
That being said, if it can be simply fixed, whithout compromise / risk to future (OS / bash) releases...

**Comment by dschaper** [comment]
No worries, you were plenty fast enough. 

The changes are backwards and forwards compatible with bash. Would you like to PR the fix?

**Comment by jpgpi250** [comment]
something wrong (you reopened the issue)? I checked the code in the latest release, the fix has been applied, so the bash syntax error (v4.3) shouldn't occur anymore.

**Comment by PromoFaux** [comment]
Itchy trigger finger!
