### ISSUE TITLE
/etc/dnsmasq.conf will be overwritten on update

### ISSUE THREAD

**Issue by SourceDoctor** [pi-hole/pi-hole#4323]
### Versions

- Pi-hole:  5.4
- AdminLTE:  5.6
- FTL:  5.9

### Platform
Debian 10
- OS and version:  
VM/VPS

### Expected behavior

running `pihole -up` 
/etc/dnsmasq.conf should holds its custom parameters or is not touched on file existance

### Actual behavior / bug

running `pihole -up` 
/etc/dnsmasq.conf is completly replaced by default

### Steps to reproduce

1. install pi-hole 5.3
2. do some customization in /etc/dnsmasq.conf
3. update to pi-hole5.4

**Comment by dschaper** [comment]
This is intended. `/etc/dnsmasq.conf` needs to be a specific value. Any changes to that file should be made in `/etc/dnsmasq.d/` as a stub.

**Comment by SourceDoctor** [comment]
ah, ok.
thanks for the hint.
Maybe something which should be written into docs :-)

**Comment by dschaper** [comment]
Yeah, that's a good point. I think we just add the header to `/etc/dnsmasq.d/01-pihole.conf` at the moment and the same should be done for `/etc/dnsmasq.conf`.
