### ISSUE TITLE
/admin page gives 500 error on centos7 after update to web 5.6

### ISSUE THREAD

**Issue by johnnuttall** [pi-hole/pi-hole#4329]
After running pihole -up, i get an http 500 error when accessing http://192.168.0.251/admin.
http://192.168.0.251 works - The "Did you mean to go to...." page loads, but with /admin, it gives a 500 error.

NB. All the other blocking and things work fine, this is just a web interface access issue.

I ran pihole -d (https://tricorder.pi-hole.net/gSsTNGUl/)

I noticed a message in the debug log, referencing auth.php on line 54 (unexpected ".").

This line reads
`array_push($AUTHORIZED_HOSTNAMES, ...explode(",", $cors_hosts));`

I removed the three dots, so the the line now reads;

`array_push($AUTHORIZED_HOSTNAMES, explode(",", $cors_hosts));`

and this resolved the issue.

I am not a PHP guy, or too good with Linux either, so for all I know, I might have done something bad, but I can report that this change corrected the error 500 - i can now access the /admin interface, and as far as I can tell, all is working as expected.

If you need more info, let me know,
Thanks in advance

**Comment by cstackpole** [comment]
I can confirm the same problem and that this fixes it for me. Thank you.
This certainly adds to the motivation to rebuild this system on Rocky 8 instead. :laughing:

**Comment by yubiuser** [comment]
@johnnuttall 
You are using an really old, outdated php version

>*** [ DIAGNOSING ]: php version
[i] 5.4.16

Released: 09 May 2013 (https://www.php.net/releases/index.php), current status EOL.

This is why Pi-hole recommends installing php 7.4 during the installation on Centos 7.
https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L423-L443

The Variable Length Argument Function (...) was introduced in php 5.6 https://www.javatpoint.com/php-variable-length-argument-function.
Please consider upgrading your php version e.g. https://unihost.com/help/how-to-update-php-centos-7/

**Comment by johnnuttall** [comment]
Thank you for the info, I shall get PHP updated.
Could I suggest that if a configuration issue such as this is found, that the installer should stop, rather than continuing and leaving an unusable/unstable install of pi-hole.
It seems that there is code to check the PHP version, but if it doesn't meet the requirements, the install will continue anyway.
A message stating "Unsupported version of PHP - please upgrade to XXX or above" might avoid newbies like me pestering you guys. :)
Thanks again
