### ISSUE TITLE
Installer looking for wrong version(s)

### ISSUE THREAD

**Issue by Tom999Hall** [pi-hole/pi-hole#433]
##### Expected Behaviour:
Pi-Hole should install (and work) Ok
##### Actual Behaviour:
404 errors during Pi-Hole install, 
Admin gui - http://192.168.0.xxx/admin/index.php, does not work

Pi-Hole install appears to be trying to copy http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5-common_5.6.17+dfsg-0+deb8u1_armhf.deb and other version 5.6.17 files, but location only has version 5.6.19 files - so I'm guessing that's the problem ?
##### Steps to reproduce this issue:
Reformat / Clean install of NOOBS 1.9 & it's Raspbian
Open Terminal window, and issue "curl -L install.pi-hole.net | bash" command

**Comment by Mcat12** [comment]
Can you copy the install log?

**Comment by Mcat12** [comment]
The installer is just running (with root privileges) `apt-get -y -qq install`. Those arguments just mean to not ask yes or no and to not output anything either.

**Comment by Tom999Hall** [comment]
What's the easiest way to get the install log (for a Windows person) ?

**Comment by PromoFaux** [comment]
if you ssh into your pi-hole machine and just do `cat /etc/pihole/install.log`

**Comment by Tom999Hall** [comment]
Ok - here it is

[install.log.txt](https://github.com/pi-hole/pi-hole/files/204515/install.log.txt)

**Comment by PromoFaux** [comment]
Hmm, OK, looks like the pihole part installed OK at least.

Can you run `pihole -d` and then copy and paste `/var/logs/pihole_debug.log` thanks

**Comment by Tom999Hall** [comment]
[debug.log.txt](https://github.com/pi-hole/pi-hole/files/204556/debug.log.txt)

Ok - how about this: (I also re-ran the installer and copied the console output)

**Comment by PromoFaux** [comment]
Hmmm, OK, looks like your apt-get cache might be to blame. Try the following:

`sudo apt-get remove --purge php5-common`
`sudo apt-get autoremove`
`sudo apt-get autoclean`
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install php5-common`

Try to see if it works after this, otherwise re-run the install script at this point

**Comment by Tom999Hall** [comment]
Hmm - tried that, and the last step asked for a Y/n response to continue - definitely did a capital "Y" (the 2nd time), but it said Abort

**Comment by Tom999Hall** [comment]
now trying the install again ....
Install worked Ok, Admin Gui works Ok now

Can't understand how the apt-get cache was screwed, when I went back to bare-metal, and reformatted sd card, and reinstalled noobs before pi-hole

**Comment by Tom999Hall** [comment]
got to go now - thanks for your help

**Comment by PromoFaux** [comment]
The volatile nature of these things I guess! Glad it's worked out for you! Let us know if you have any more problems, we span several time zones, so there is usually someone awake to help!
