### ISSUE TITLE
FTL v5.9 update failing to install

### ISSUE THREAD

**Issue by Flashbin** [pi-hole/pi-hole#4330]
### Versions

- Pi-hole:  v5.4
- AdminLTE:  v5.6
- FTL:  v5.8.1

### Platform

- OS and version:  Debian 10.10

- Platform:  Raspberry Pi 4 / bhyve VM

### Expected behavior

The update installs without problems.

### Actual behavior / bug

Updating from each of the previous versions to the newly released ones with `pihole -up` leads to this error:

```
  [i] Checking for updates...
  [i] Pi-hole Core:     update available
  [i] Web Interface:    update available
  [i] FTL:              update available

  [i] Pi-hole core files out of date, updating local repo.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...HEAD is now at 2673c2c Merge pull request #4318 from pi-hole/release/v5.4
  [✓] Update repo in /etc/.pihole

  [i] If you had made any changes in '/etc/.pihole/', they have been stashed using 'git stash'

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...HEAD is now at f5292a3 Merge pull request #1850 from pi-hole/release/v5.6
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.29-1~deb10u1

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✗] Retrieval of supported OS list failed. dig failed with return code 9.
      Unable to determine if the detected OS (Debian 10) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

           If you are seeing this message after having run pihole -up:
             PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


  Unable to complete update, please contact Pi-hole Support
```

### Steps to reproduce

1. run pihole -up while being on the previous version of core/web/FTL

Tested on a Raspberry Pi and a bhyve VM (both running Debian 10.10).

## Debug Token

- URL:  https://tricorder.pi-hole.net/7ryS9Bx0/

### Screenshots

not necessary

### Additional context

I've updated multiple times, it has worked before.

Edit:
Since it says it can't retrieve versions.pi-hole.net, I've tested it from the same host: `dig versions.pi-hole.net TXT`
```
; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> versions.pi-hole.net TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28955
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;versions.pi-hole.net.          IN      TXT

;; ANSWER SECTION:
versions.pi-hole.net.   600     IN      TXT     "Raspbian=9,10,11 Ubuntu=16,18,20,21 Debian=9,10,11 Fedora=32,33 CentOS=7,8"

;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Sep 13 20:57:01 CEST 2021
;; MSG SIZE  rcvd: 136
```

**Comment by yubiuser** [comment]
> ;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)

The device hosting Pi-hole is using Pi-hole for itself. Try changing that by editing `/etc/resolv.conf`.

Otherwise you could also just do what the updater suggests: 
>If you are seeing this message after having run pihole -up:
             PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
             
Nevertheless, your device is unable to successfully connect to outside DNS servers
>[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)

Do you have any kind of firewall in place?

**Comment by Flashbin** [comment]
@yubiuser Yes, I'm blocking all DNS queries going to the outside world. When I let through my Pi-Holes, it worked, thanks mate!
But this seems kind of strange to me, why would Pi-Hole need external DNS for updating?

**Comment by yubiuser** [comment]
Because we saw broken DNS servers that were unable to perform a successful `dig versions.pi-hole.net TXT`. That's why we use a server we control https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L179

It's a trade-off. But we assumed, everyone knowing how to block external DNS can unblock it for the update or skip the OS_check.

**Comment by jfb-pihole** [comment]
`Yes, I'm blocking all DNS queries going to the outside world`

I assume there is an exception for the Pi-hole host, or how would Pi-hole be able to resolve domains that are not blocked?

**Comment by Flashbin** [comment]
> `Yes, I'm blocking all DNS queries going to the outside world`
> 
> I f you were not making an exception for the Pi-hole host, how was Pi-hole able to resolve domains that are not blocked?

I was blocking all DNS, except that my Pi-Holes could query their DNS servers, but only specifically those.

**Comment by jfb-pihole** [comment]
That clarifies it. You were not blocking all DNS queries to the outside world.
