### ISSUE TITLE
FTL wont update - "Please try sudo apt-get update"

### ISSUE THREAD

**Issue by beckerer** [pi-hole/pi-hole#4332]
### Versions

- Pi-hole:  v5.4
- AdminLTE:  v5.6
- FTL:  v5.8.1

### Platform

- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior

I expected to run pihole -up and all three (Core, Web Interface, and FTL) would update

### Actual behavior / bug

pi@Pi-Hole:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

      

  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "sudo apt-get update"
  Unable to complete update, please contact Pi-hole Support

## Debug Token

- URL:  https://tricorder.pi-hole.net/9AxSUGJY/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
What happened when you ran this command?

`sudo apt-get update`

**Comment by gitalta30** [comment]
I have the same issue. I did run sudo apt-get update and still no change. I rebooted both of my pihole servers, same result. Like beckerer, only the FTL will not update.

**Comment by yubiuser** [comment]
What is the output of ` sudo apt-get update`

**Comment by gitalta30** [comment]
$ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

**Comment by yubiuser** [comment]
This is an OS level issue, not an Pi-hole issue.

https://discourse.pi-hole.net/t/apt-get-error-on-update/49569/5

**Comment by gitalta30** [comment]
Thank you yubiuser, that did the trick. I was able to update both pi-hole servers.

**Comment by baggachipz** [comment]
I have the same problem on my RasPi 4.

```
matt@chauncey:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
matt@chauncey:~$ sudo apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Err:5 https://apache.bintray.com/couchdb-deb focal InRelease
  403  Forbidden [IP: 52.38.105.61 443]
Reading package lists... Done
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/focal/InRelease  403  Forbidden [IP: 52.38.105.61 443]
E: The repository 'https://apache.bintray.com/couchdb-deb focal InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list:59
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list:59
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list:59
W: Target CNF (main/cnf/Commands-arm64) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list:59
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list:59
```

Any ideas?

**Comment by yubiuser** [comment]
Did you google the error?

**Comment by baggachipz** [comment]
> Did you google the error?

Yes, and so far none of the suggestions work. Can't find a repo for CouchDB that isn't "forbidden" at this point.

**Comment by yubiuser** [comment]
Second result
https://github.com/apache/couchdb-documentation/issues/678

**Comment by baggachipz** [comment]
That one was dealing with Debian Buster. One of the suggestions had me add `https://apache.bintray.com/couchdb-deb focal InRelease` to `sources.list` but that actually was causing the problem to persist. Removed that file and now I'm good to go. Thanks for the suggestions though.

**Comment by beckerer** [comment]
> What happened when you ran this command?
> 
> `sudo apt-get update`

pi@Pi-Hole:~ $ sudo apt-get update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.7 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]               
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [392 kB]
Reading package lists... Done    
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

**Comment by beckerer** [comment]
> https://discourse.pi-hole.net/t/apt-get-error-on-update/49569/5

Thank you yubiuser!!! that worked.

**Comment by LiftKid** [comment]
> This is an OS level issue, not an Pi-hole issue.
> 
> https://discourse.pi-hole.net/t/apt-get-error-on-update/49569/5

Thanks for this quick fix!
This issue had me stumped for a while... Maybe add a notice about it or something so that others dont have to search for the solution?

**Comment by ArnoldusW** [comment]
I have a similar issue as  Beckerer:
I run the update:
> pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Update local cache of available packages...
[K  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "sudo apt-get update"
  Unable to complete update, please contact Pi-hole Support

I ran sudo apt-get update:

> sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:3 https://github.com/pi-hole/AdminLTE/releases https: InRelease
Err:4 https://github.com/pi-hole/AdminLTE/releases https: Release
  404  Not Found [IP: 140.82.121.3 443]
Ign:5 https://download.webmin.com/download/repository sarge InRelease
Hit:6 https://download.webmin.com/download/repository sarge Release
Reading package lists...
E: The repository 'https://github.com/pi-hole/AdminLTE/releases https: Release' does not have a Release file.

then I ran: > sudo apt-get update --allow-releaseinfo-change


Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Ign:3 https://github.com/pi-hole/AdminLTE/releases https: InRelease
Err:4 https://github.com/pi-hole/AdminLTE/releases https: Release
  404  Not Found [IP: 140.82.121.3 443]
Ign:5 https://download.webmin.com/download/repository sarge InRelease
Hit:6 https://download.webmin.com/download/repository sarge Release
Reading package lists...
E: The repository 'https://github.com/pi-hole/AdminLTE/releases https: Release' does not have a Release file.

I can't figure out why ip 140.82.121.3 can't be found?  Any suggustestions how to resolve?

**Comment by yubiuser** [comment]
Remove

>https://github.com/pi-hole/AdminLTE/releases

From your `etc/apt/source.list`
Pi-hole does not have a package repository

**Comment by ArnoldusW** [comment]
thanx! issue resolved, all up to date now 💯

**Comment by Player110** [comment]
Started.....
sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:2 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  InRelease
Hit:3 http://deb.playonlinux.com trusty InRelease
Hit:4 http://archive.raspberrypi.org/debian buster InRelease
Err:5 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release
  404  Not Found [IP: 195.135.221.134 80]
Reading package lists... Done
E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://deb.playonlinux.com trusty InRelease' doesn't support architecture 'armhf'
then.....
pi@PiHole:~ $ sudo apt-get update --allow-releaseinfo-change
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:2 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  InRelease
Hit:3 http://deb.playonlinux.com trusty InRelease
Hit:4 http://archive.raspberrypi.org/debian buster InRelease
Err:5 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release
  404  Not Found [IP: 195.135.221.134 80]
Reading package lists... Done
E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://deb.playonlinux.com trusty InRelease' doesn't support architecture 'armhf'
Help please?

**Comment by yubiuser** [comment]
> The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04 Release' does not have a Release file.

This repo does not exist any more for Ubuntu 16.04. Delete it from your `/etc/apt/sources.list`

http://download.opensuse.org/repositories/home:/strycore/
https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris

**Comment by Player110** [comment]
pi@PiHole:~ $ sudo nano /etc/apt/source.list is empty.
  GNU nano 3.2                  /etc/apt/source.lis

**Comment by yubiuser** [comment]
You missed the plural`s`.

**Comment by Player110** [comment]
all i have 
 GNU nano 3.2                                                        /etc/apt/sources.list

deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi

**Comment by dschaper** [comment]
Look in `/etc/apt/sources.list.d/`

**Comment by Player110** [comment]
pi@PiHole:~ $ sudo nano  /etc/apt/sources.list.d/
  GNU nano 3.2                                                             New Buffer

nothing there also.

**Comment by dschaper** [comment]
Sorry, you need to look and see if there are any files in that directory that contain the sources shown in your `apt` output.

**Comment by Player110** [comment]
Sorry noob here, can you more specific. i don't see anything in any of the directories.
 sudo nano  /etc
empty
sudo nano  /etc/apt/
empty
sudo nano  /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free$
only one that has something.

**Comment by dschaper** [comment]
`ls -la /etc/apt/sources.list.d/`

**Comment by Player110** [comment]
ls -la /etc/apt/sources.list.d/
total 24
drwxr-xr-x 2 root root 4096 Dec 29 03:15 .
drwxr-xr-x 7 root root 4096 Dec 30 03:00 ..
-rw-r--r-- 1 root root   76 Dec 29 03:15 home:strycore.list
-rw-r--r-- 1 root root   78 Dec 28 15:30 lutris.list
-rw-r--r-- 1 root root   44 Dec 25  2018 playonlinux.list
-rw-r--r-- 1 root root  187 May 27  2020 raspi.list

**Comment by Player110** [comment]
now what can i do?

**Comment by yubiuser** [comment]
>-rw-r--r-- 1 root root 76 Dec 29 03:15 home:strycore.list

Remove that file.
