### ISSUE TITLE
Installer fails on barebones Debian if ca-certificates not installed

### ISSUE THREAD

**Issue by kiptonk** [pi-hole/pi-hole#4333]
### Versions

basic-install.sh: downloaded 21-Aug-2021

### Platform

- OS and version:  Debian 10

- Platform: x64

### Expected behavior

Installer completes without error.

### Actual behavior / bug
> [✗] Check for existing repository in /etc/.pihole
> [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...
>  Error: Could not update local repository. Contact support.

### Steps to reproduce

1. Barebones install of Debian 10 without ca-certificates (recommended package for git, curl)
2. Run basic-install.sh
3. See error

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Normally ca-certificates is installed as a recommended part of curl and git. But, if the pi-hole installer is relied upon for git/curl installation it uses apt-get "no-install-recommends" so "ca-certificates" does not get installed. I think "ca-certificates" should be an explicit part of the INSTALLER_DEPS.

Also while looking through the script I noticed curl in the PIHOLE_DEPS. Maybe curl should move to INSTALLER_DEPS?

This is very minor bug considering it will only be seen on a barebones system where the pi-hole installer is bringing in git and curl. My main concern is that the error message is not at all indicative of the issue and so it can be a headscratcher to find that a missing ca-certificates is the culprit.

**Comment by yubiuser** [comment]
Thanks for the report.

> Also while looking through the script I noticed curl in the PIHOLE_DEPS. Maybe curl should move to INSTALLER_DEPS?

Why do you think so? `curl` is used only in two places: downloading FTL and re-downloading the install script with sudo privs. So basically `curl` is a prerequisite for downloading the installer at all and needs to be installed even beforehand.
Only if users manually removed `curl` after Pi-hole was installed and run the updater as root it is necessary to install it again (for downloading FTL) - and it makes sens to have it in PIHOLE_DEPS.

**Comment by dschaper** [comment]
I can see where it needs to move. If they clone the repo or `wget` the install file and then it needs to rerun as `sudo` there is a potential for not having `curl` installed.

**Comment by yubiuser** [comment]
But than it's not enough to put it in INSTALLER_DEP because curling happens way earlier than installing the files. It's a chicken-egg-problem. You can't install as sudo if the script is not run as sudo for which you need curl.

https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L2517

**Comment by kiptonk** [comment]
Whoops, didn't notice curl was used so early in the script... I saw INSTALLER_DEPS and assumed the apt install of those packages happened before anything else. Please ignore the idea about moving the curl dependency. I still think the ca-certificates dependency should be added.

**Comment by dschaper** [comment]
I've seen this on a fully bare Debian install. `curl` is missing as well as `ca-certificates`. But `ca-certificates` is needed to `curl` an `https` URL so you couldn't `curl https://install.pi-hole.net` without `ca-certificates` in the first place. Not sure how to proceed on that.

**Comment by DL6ER** [comment]
We can't. The only alterative would be to serve over HTTP (either everything or a small "install certificate" script). That's not really an option.

**Comment by yubiuser** [comment]
We can only add some into to the documentation, that `ca-certificates` and
`curl` need to be installed before Pi-hole manually.

Am So., 19. Sept. 2021 um 20:05 Uhr schrieb DL6ER ***@***.***

**Comment by kiptonk** [comment]
Is there an issue with adding just ca-certificates to INSTALLER_DEPS? This resolves the git error above when basic-install.sh is copied over from another drive, etc. instead of via curl and executed on a minimal system.

**Comment by yubiuser** [comment]
> adding just ca-certificates to INSTALLER_DEPS

I think this should work.

https://github.com/pi-hole/pi-hole/pull/4343

**Comment by kiptonk** [comment]
Looks good, closing this, thanks. The curl chicken/egg is a separate issue I think (i.e. "bash basic-install.sh" on barebones will fail to bootstrap the curl install).
