### ISSUE TITLE
Pi Hole Page not reachable after upgrade to Raspberry Pi OS to bullseye

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#4338]
### Versions

- Pi-hole:  5.4
- AdminLTE:  5.6
- FTL:  5.9

### Platform

- OS and version:  Raspberry Pi OS 11
- Platform:  Raspberry Pi

### Expected behavior

everything works fine after upgrade.

### Actual behavior / bug

Pi hole Page was not reachable, Chronometer was flickering like it’s party time 🥳.
Some system related stuff was broken not able to ssh to the Pi.

### Steps to reproduce

1. Go to edit source.list to bullseye perform upgrade process.
2. After upgrade got to IP from Pi
3. See error

The Pi Hole update script checks if php7.3 exists not 7.4 which is shipped with bullseye.

I read today that Raspberry Pi OS 11 is not released yet.

https://www.raspberrypi.org/forums/viewtopic.php?t=317787

**Comment by dschaper** [comment]
The script looks for the version of PHP you currently have installed. 

What exactly are the commands you used to upgrade to Bullseye. And yes, there is no official Raspberry OS for Bullseye.

**Comment by pheiduck** [comment]
> What exactly are the commands you used to upgrade to Bullseye.

apt dist-upgrade

**Comment by dschaper** [comment]
That's it?

**Comment by pheiduck** [comment]
> That's it?

Yes

**Comment by pheiduck** [comment]
Found this https://en.wikipedia.org/wiki/Raspberry_Pi_OS#Release_history
So I will track this. Was able to downgrade to buster with a Backup SD Card all works again as expected

**Comment by jfb-pihole** [comment]
`apt update && apt dist-upgrade`

These commands do not move you from Buster to Bullseye.  They update the existing version, which in your case should be Buster.

https://www.raspberrypi.org/documentation/computers/os.html#updating-and-upgrading-raspberry-pi-os
