### ISSUE TITLE
2.6.1: pihole.cron needs to be updated with new common pihole script

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#434]
Now that there's a single 'pihole' script, the pihole.cron file needs to be updated to use the new command-line syntax instead of the old separate scripts.

i.e.,
`59 1    * * 7   root    /usr/local/bin/pihole updateGravity`

instead of
`59 1    * * 7   root    /usr/local/bin/gravity.sh`

(originally pointed out by @VDRrulez in issue #432 but I didn't see a specific issue to track it)

**Comment by PromoFaux** [comment]
Cheers man.  I'm out  an about a  the moment  but  going to order sort this out as soon as I get in!

**Comment by jradwan** [comment]
No worries, you've been busy recently! ;-)
