### ISSUE TITLE
traceroute from clients shows pi.hole instead of fqdn or rDNS

### ISSUE THREAD

**Issue by Deepcuts** [pi-hole/pi-hole#4341]
### Versions

Pi-hole version is v5.4 (Latest: v5.4)
AdminLTE version is v5.6 (Latest: v5.6)
FTL version is v5.9 (Latest: v5.9)

### Platform

Ubuntu Server 20.04.3 LTS (fresh install today)

VM

### Expected behavior
a traceroute from an external client should display rDNS or fqdn value for the host and NOT pi.hole

### Actual behavior / bug
a treceroute from an external client displays pi.hole as fqdn for the host instead of the real rDNS/fqdn
running "host Public.IP.of.pihole" on the pihole itself shows X.X.X.X.in-addr.arpa domain name pointer pi.hole.

_A clear and concise description of what the bug is._
I have a VM with Ubuntu Server 20.04.3 LTS solely for pihole. Only IPv4, no IPv6.
The VM has a public IP. The public IP has the required rDNS and DNS values set.
If an external client that is using the pihole DNS does a traceroute to the fqdn or IP of the VM, the value of the last hop will show pi.hole instead of rDNS/fqdn. External clients NOT using the DNS of course will not show pi.hole but the correct value.
If an external client that is using the pihole DNS pings pi.hole , it will ping/resolve the public IP of the VM.
hostname show the correct value.
hostname -A shows the correct value.
hostnamectl shows the correct value.
hosts file has no mention of a host named pi.hole
hostname file shows the correct value.
The hostname in the web UI (top right) has the correct value.
The only place I can find pi.hole being referenced is through the web UI at /admin/network.php for the IP address ::

Might be something obvious that escapes me, but I cannot find an easy way to modify this pi.hole value to the actual fqdn of the VM or at least keep it local, known only to pihole.

**Comment by yubiuser** [comment]
With the last release, FTL will always return `pi.hole` for reverse lookups.
https://github.com/pi-hole/FTL/pull/1111

However, the next version will have the ability to change the behavior to return the hostname instead
https://github.com/pi-hole/FTL/pull/1164

**Comment by Deepcuts** [comment]
Thank you. My search skills failed me.
Will close this as it seems the problem is well known.
Nevertheless, who thought this is a good idea on a piece of software made for DNS is beyond me.

**Comment by DL6ER** [comment]
Reasoning is given in the linked PRs. This just extended always existing behavior from one single to all IP addresses bound to the system. Advanced users have full control with the provided config options.
