### ISSUE TITLE
Install Failure - PATH+: bad variable name

### ISSUE THREAD

**Issue by seadoggie01** [pi-hole/pi-hole#4342]
### Versions
- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A

### Platform
- OS and version:  Stretch (v9.13)
- Platform:  Raspberry Pi

### Expected behavior

The installation to finish

### Actual behavior / bug

The installation quits, seemingly at [line 26 of basic-install.sh](https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L26)

### Steps to reproduce

1. $ git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
2. $ cd "Pi-hole/automated install/"
3. $ sudo bash basic-install.sh

[Output]
basic-install.sh: 26: export: PATH+: bad variable name

The wget method outputs the same error after correctly downloading the file. Installing with curl has an additional curl error:

$ curl -sSL https://install.pi-hole.net | bash
bash: 26: export: PATH+: bad variable name
curl: (23) Failed writing body (222 != 1415)

## Debug Token

- URL:  N/A

### Additional context

Edit: Updated with other installation methods

**Comment by dschaper** [comment]
What version of bash do you have?

`bash --version`

**Comment by dschaper** [comment]
And also, what is the `PATH` variable set to?

`echo $PATH`

**Comment by seadoggie01** [comment]
PATH: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`
Bash version: 5.0.3(1)

However, I planned to update to Buster, and something fixed it along the way. I ran sudo apt upgrade before starting, but while following these instructions https://www.makeuseof.com/tag/raspberry-pi-update-raspbian-os/, the command started working.
