### ISSUE TITLE
Adding new blocklist URL: domains invalid!

### ISSUE THREAD

**Issue by cmonty14** [pi-hole/pi-hole#4345]
### Versions

- Pi-hole:  v5.4
- AdminLTE:  v5.6
- FTL:  v5.4

### Platform

- OS and version:  Debian 10

- Platform:  VM

### Expected behavior

_A clear and concise description of what you expected to happen._
After adding a new URL updating gravity should report success message.
### Actual behavior / bug

_A clear and concise description of what the bug is._
Runing `pihole -g` reports these errors:
```
  [i] Target: https://github.com/guardicore/labs_campaigns/blob/master/Autodiscover/autodiscover-tlds.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 13 domains, 13 domains invalid!
      Sample of invalid domains:
      - content="github.com">
      - content="github.com">
      - data-target="input-demux.source"
      - data-targets="input-demux.sinks"
      - cache-key="v0:1625033316.303205"

```
### Steps to reproduce

1. Go to 'Group Management' - 'Adlists'
2. Enter new URL https://github.com/guardicore/labs_campaigns/blob/master/Autodiscover/autodiscover-tlds.txt
3. Click on 'Add'
4. Run pihole -g

## Debug Token

- URL:  https://tricorder.pi-hole.net/xRt0EN1J/

**Comment by DL6ER** [comment]
This is expected you added a styled Github page instead of the raw list itself. Use the raw list instead:
![Screenshot from 2021-09-27 10-37-10](https://user-images.githubusercontent.com/16748619/134874028-a2fe7c51-43d7-4473-a02d-423746ab7b4b.png)

**Comment by cmonty14** [comment]
THX.
This advise is key for the usage of the relevant list.

However, there are still some entries that are invalid:
```
  [i] Target: https://raw.githubusercontent.com/guardicore/labs_campaigns/master/Autodiscover/autodiscover-tlds.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 9190 domains, 566 domains invalid!
      Sample of invalid domains:
      - autodiscover.*.bd
      - autodiscover.*.nom.br
      - autodiscover.aéroport.ci
      - autodiscover.*.ck
      - autodiscover.!www.ck

```
Could you please advise how to handle these?

THX

**Comment by DL6ER** [comment]
Special characters are invalid in HOSTS style lists. You should file a bug report in the repository over there. Neither `!` nor `*` are valid domain characters. International domain names (IDN) are typically requested only in their encoded form, i.e., it doesn't make sense to include them with non-ASCII characters in the list

**Comment by cmonty14** [comment]
Thanks for your great support!

This issue can be closed accordingly.
