### ISSUE TITLE
addn-hosts=/etc/pihole/local.list

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/pi-hole#4349]
### Versions

  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.10.1 (Latest: v5.10.1)

### Platform

Linux raspberrypi 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l GNU/Linux

- Platform:  Raspberry Pi

### Expected behavior

/etc/pihole/local.list is now a static file, contains no dnsmasq info, just a comment, and can thus be removed from /etc/dnsmasq.d/01-pihole.conf 

### Actual behavior / bug

/etc/dnsmasq.d/01-pihole.conf  still contains addn-hosts=/etc/pihole/local.list

### Steps to reproduce

cat /etc/dnsmasq.d/01-pihole.conf

**Comment by yubiuser** [comment]
It is still used to add clients for openVPN.

https://github.com/pi-hole/pi-hole/blob/dad6247cb0c90fe8cc1ad541e0ccf8f02e1dd2be/gravity.sh#L800-L802

One can surely debate if this is still necessary

**Comment by DL6ER** [comment]
I'd say yes. Why should we remove it? I could imagine renaming the file but removing seems wrong

**Comment by jpgpi250** [comment]
OK, thanks, issue closed...
