### ISSUE TITLE
# If apt-get is installed, then we know it's part of the Debian family

### ISSUE THREAD

**Issue by mathieu-aubin** [pi-hole/pi-hole#4358]
This is not always true as most developement environment will have apt-get installed even if not a debian distribution. Per example,i am running Fedora.

I think your OS detection should be revised

**Comment by PeterDaveHello** [comment]
I think you mean the `automated install/basic-install.sh` script?

What about also checking file `/etc/debian_version` exists? It also exist on Ubuntu and Linux Mint! I can send a pull request for it if this suggestion was accepted by the maintainers.

**Comment by yubiuser** [comment]
Thanks for the report.

I can't remember a singles issue report where installation failed due to falsely identified package manager. But as always there might be room for improvements.

> I think your OS detection should be revised

That do you suggest? How would you improve the detection of the right package manager to use?

**Comment by mathieu-aubin** [comment]
I think you could look for /etc/os-release

```shell
#!/bin/sh -eu

test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
. "${os_release}"

echo "Running on ${PRETTY_NAME:-Linux}"

if [ "${ID:-linux}" = "debian" ] || [ "${ID_LIKE#*debian*}" != "${ID_LIKE}" ]; then
    echo "Looks like Debian!"
fi
```

as in https://www.freedesktop.org/software/systemd/man/os-release.html

or maybe check this other style

https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script

**Comment by dschaper** [comment]
Why does Fedora have `apt` installed if it can't use it?

**Comment by mathieu-aubin** [comment]
i have it installed for development purposes

**Comment by dschaper** [comment]
I'm not comfortable changing something that has worked for years in order to accommodate an edge case that was intentionally created. We look for `apt` because we use `apt` to install the packages. I can't think of a working case where `apt` is installed but doesn't actually work.

**Comment by PromoFaux** [comment]
> What about also checking file `/etc/debian_version` exists?

On of the first things we do is check that the install script is being run on a supported OS, see the function [`os_check()`](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L169)

The only thing I could say would be reasonable to change in the [`package_manager_check()`](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L264 ) function would be a change of wording in the comment from "the we know it's part of the debian family" to , "then we know it has apt-get" /shrug

**Comment by mathieu-aubin** [comment]
i believe i'm not an exeption as far as having apt installed on fedora.. one thing for sure, i took the time to mention.
feel free to close this
