### ISSUE TITLE
pihole -up overwrites custom lighttpd config

### ISSUE THREAD

**Issue by bublath** [pi-hole/pi-hole#4359]
### Versions
- Pi-hole:   v5.5 
- AdminLTE:   v5.7
- FTL:   v5.10.2

### Platform
- OS and version:  Debian Buster
- Platform:  Raspberry Pi

### Expected behavior

pihole -up should check for custom lighttpd.conf changes and either keep it, warn, backup or best take over some of the most common changes like a different port

### Actual behavior / bug

pihole update just overwrites lighttpd.conf

### Steps to reproduce

Happens with every update

### Additional context

I have reconfigured lighttpd to run on port 8080 instead of 80, since I need port 80 for something else.
With every pihole update I have to remember change the configuration back to prevent my system to get screwed up.

**Comment by yubiuser** [comment]
There is a big warning right at the top of the file and where changes should be made.

```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Lighttpd config for Pi-hole
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################


```

**Comment by jfb-pihole** [comment]
`With every pihole update I have to remember change the configuration back to prevent my system to get screwed up.`

See this link for a method to permanently and reliably change the lighttpd port:

https://discourse.pi-hole.net/t/lighttpd-daemon-wont-start/44985/13
