### ISSUE TITLE
Can not update FTL from v5.8.1 to latest

### ISSUE THREAD

**Issue by lysynski** [pi-hole/pi-hole#4364]
**Versions**
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.8.1 (Latest: v5.10.2)

**Platform**

    OS and version: 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

    Platform:
Raspberry Pi Zero

**Expected behavior**

When running pihole -up, Pi-hole, AdminLTE and FTL should be updated to the latest version.

**Actual behavior / bug**

FTL is not being updated. Output of pihole -up below

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "sudo apt-get update"
  Unable to complete update, please contact Pi-hole Support

**Steps to reproduce**

    SSH into the raspberry pi
    call pihole -up

**Debug Token**

- URL:  https://tricorder.pi-hole.net/b1RS6Op5/

**Additional context**

nameserver 8.8.8.8, pihole -r fails

**Comment by PromoFaux** [comment]
> Error: Unable to update package cache. Please try "sudo apt-get update"

https://github.com/pi-hole/pi-hole/issues/4332

**Comment by lysynski** [comment]
Done - no change.

Following the threads from #4332, sudo apt-get update --allow-releaseinfo-change works.
