### ISSUE TITLE
pi.hole client weird issue

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#4378]
### Versions

  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.10.2 (Latest: v5.10.2)

### Platform

- OS and version:  `Linux raspberrypi 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux`

- Platform:  Raspberry Pi

### Expected behavior

_pi.hole confusing client not to show up on web interface_

### Actual behavior / bug

_A client named "pi.hole" assigned with the (IPv6?) ip "::" is showing up on the interface with the requests being either NODATA , DNSSEC , N/A_

### Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'pi.hole client'
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/d6y3kl9v/

### Screenshots
![1](https://user-images.githubusercontent.com/3320229/136592218-f0da6639-5212-4384-88e5-8a9efff86232.png)
![2](https://user-images.githubusercontent.com/3320229/136592214-3eb7f48c-80fd-4738-9e64-5103fd5274fd.png)

### Additional context

_None_

**Comment by yubiuser** [comment]
Thanks for the report. Those are the internally generated DNSSEC-related queries using `::` as a special address. Please see here for further details 

https://discourse.pi-hole.net/t/address-and-pi-hole-twice-in-network-table/50219
