### ISSUE TITLE
Incorrect permissions preventing lighttpd starting

### ISSUE THREAD

**Issue by 0xc0ffea** [pi-hole/pi-hole#438]
Existing working PiHole, ran script update to 2.6.1.1 , web interface wasn't working.

Seems the lighttpd service was failing to start
```
 $ sudo service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-04-05 10:26:43 EDT; 1min 31s ago
  Process: 9576 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 9568 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 9576 (code=exited, status=255)

Apr 05 10:26:43 Cerberus lighttpd[9568]: Syntax OK
Apr 05 10:26:43 Cerberus systemd[1]: Started Lighttpd Daemon.
Apr 05 10:26:43 Cerberus lighttpd[9576]: 2016-04-05 10:26:43: (log.c.118) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Apr 05 10:26:43 Cerberus systemd[1]: lighttpd.service: main process exited, code=exited, status=255/n/a
Apr 05 10:26:43 Cerberus systemd[1]: Unit lighttpd.service entered failed state.
```

Manually setting /var/log/lighttpd to 755 & www-data:www-data fixed

**Comment by PromoFaux** [comment]
That's interesting. I'm unable to reproduce this. Tried as an upgrade on one pi, and a fresh install on another...

What version were you coming from?

**Comment by 0xc0ffea** [comment]
2.6.1 installed earlier and untested, and before that im not sure it had been running a long time I never opened the web interface so no idea. srry :/

**Comment by Mcat12** [comment]
Is this still an issue?

**Comment by dschaper** [comment]
Stale, closing issue

**Comment by CrankedCode** [comment]
Thank you! CHMOD 755 & chown www-data:www-data the log directories did the trick!  Finally found a solution after an hour of searching and troubleshooting!

**Comment by htpcBeginner** [comment]
I am still having the same issue on docker pihole:debian. Is there a permanent fix? manually changing permissions every time is not practical.

**Comment by rajesh-metrofi** [comment]
It still happens in the latest build. I just installed pi-hole 4 on CentOS 7 and the lighttpd service failed to start with default settings. I had to change the directory permissions (755) and create an empty /etc/lighttpd/external.conf file to start the web server successfully.

chmod 755 /var/log/lighttpd
touch /etc/lighttpd/external.conf

Please fix these above issues in the next build to save users time.

**Comment by SaintFenix** [comment]
I've installed Organizr on my system, and have noticed that after installing nginx (which organizr requires), lighttpd is no longer working, and is throwing the same error as here.

**Comment by aymenjegham** [comment]
> It still happens in the latest build. I just installed pi-hole 4 on CentOS 7 and the lighttpd service failed to start with default settings. I had to change the directory permissions (755) and create an empty /etc/lighttpd/external.conf file to start the web server successfully.
> 
> chmod 755 /var/log/lighttpd
> touch /etc/lighttpd/external.conf
> 
> Please fix these above issues in the next build to save users time.

How did you started the new service, i am stuck with failed lioghttpd to start 

![image](https://user-images.githubusercontent.com/12992811/71225669-9453f800-22d9-11ea-808a-024e39553b5c.png)

**Comment by ashthespy** [comment]
Just ran into the same issue after an update on Debian buster:
```
:~$ pihole -v
  Pi-hole version is v4.4 (Latest: v4.4)
  AdminLTE version is v4.3.3 (Latest: v4.3.3)
  FTL version is v4.3.1 (Latest: v4.3.1)
:~$ systemctl status lighttpd.service
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-03-17 14:40:49 CET; 4s ago
  Process: 2590 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
  Process: 2597 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)
 Main PID: 2597 (code=exited, status=255/EXCEPTION)

Mar 17 14:40:49 orangepione systemd[1]: lighttpd.service: Service RestartSec=100ms expired, scheduling restart.
Mar 17 14:40:49 orangepione systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Mar 17 14:40:49 orangepione systemd[1]: Stopped Lighttpd Daemon.
Mar 17 14:40:49 orangepione systemd[1]: lighttpd.service: Start request repeated too quickly.
Mar 17 14:40:49 orangepione systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Mar 17 14:40:49 orangepione systemd[1]: Failed to start Lighttpd Daemon.
```

**Comment by dschaper** [comment]
What does `sudo /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf` output?

**Comment by dschaper** [comment]
> It still happens in the latest build. I just installed pi-hole 4 on CentOS 7 and the lighttpd service failed to start with default settings. I had to change the directory permissions (755) and create an empty /etc/lighttpd/external.conf file to start the web server successfully.
> 
> chmod 755 /var/log/lighttpd
> touch /etc/lighttpd/external.conf
> 
> Please fix these above issues in the next build to save users time.

We can't. This isn't something we can do with Pi-hole. If you have your `/var/log` set to an ephemeral filesystem (ramlog) then you will have to create the directory when you restart/reboot.

**Comment by ashthespy** [comment]
> 
> 
> What does `sudo /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf` output?

```
:~$ sudo /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
:~$ echo $?
255
```

**Comment by dschaper** [comment]
Is your `/var/log` on a RAM-backed filesystem?

**Comment by ashthespy** [comment]
> 
> 
> Is your `/var/log` on a RAM-backed filesystem?

It is indeed.. running via log2ram via [`armbain-ramlog`](https://github.com/armbian/build/blob/master/packages/bsp/common/usr/lib/armbian/armbian-ramlog)

**Comment by ashthespy** [comment]
Not sure if the same perm issues is what I have..
```
:~$ ls -la /var/log/lighttpd
total 20
drwxr-xr-x  2 www-data www-data 4096 Mar 17 14:18 .
drwxr-xr-x 11 root     root     4096 Mar 17 11:45 ..
-rw-r--r--  1 root     root        0 Mar 17 11:45 access.log
-rw-r--r--  1 www-data www-data 8246 Mar 17 14:57 error.log
:~$  cat /var/log/lighttpd/error.log
2020-03-17 14:56:59: (mod_accesslog.c.660) opening log '/var/log/lighttpd/access.log' failed: Permission denied
2020-03-17 14:56:59: (server.c.1472) Configuration of plugins failed. Going down.
```

**Comment by dschaper** [comment]
`access.log` is not writeable by `www-data`. Better place to report this is for https://github.com/armbian/build/blob/master/packages/bsp/common/usr/lib/armbian/armbian-ramlog#L29 to recreate the `lighttpd` log files.

**Comment by ashthespy** [comment]
@dschaper `armbain-ramlog` now recreates said files on boot, however this doesn't really solve the permissions issue as it's till created as root. 
Is there anyway for `pi-hole` to check on boot and fix perms? Or am I better off just fixing my `lighttpd.service` to change perms on the folder before starting up?

**Comment by dschaper** [comment]
Not really, we start `lighttpd` via the service/systemctl utility and that's as far as we can go with interactions.

**Comment by Gasman2014** [comment]
Any hints on how to best handle this? Something must have changed as I have been successfully running pi.hole on an orange pi zero on ARMBIAN 5.73 stable Debian GNU/Linux 9 (stretch)  for many months but a recent upgrade has broken this. Following a reboot, `/var/log/lighttpd` and the error.log and access.log with in it now get owned by `root` not `www-data` and the web interface fails. This also seems to happen randomly after a couple of days which might fit with a log rotate. I was planning to experiment with adding` create 0664 www-data utmp` to  `/etc/logrotate.d/lighttpd` but not sure if this is likely to be effective or if there was a better solution.

**Comment by dschaper** [comment]
You'll need to ask the folks at armbian on their support forums. It's not something we do or adjust.

**Comment by Gasman2014** [comment]
Thanks - will do.

**Comment by dschaper** [comment]
If you find anything out or if Igor has any questions or advice then please let us know.

**Comment by ashthespy** [comment]
FWIW, I opened up a [PR](https://github.com/armbian/build/pull/1853) a while back to create the right entries for `lighttpd`. This is required only if the device doesn't have a backup to restore from.  
Would it be a solution to make the `.log` files accessible by `www-data` if that is the standard `lighttpd` user?

**Comment by dschaper** [comment]
The log files need to be writeable by the `lighttpd` user. We don't change that area of `lighttpd`, it's just the stock package installed via the package manager. I think it would be safe to either `chown` to that user or `chmod` to allow that user/group to read/write.
