### ISSUE TITLE
-h for usage info doesn't work for pihole -w/-b/-c

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#439]
The help for pihole script indicates:

`Add -h after -w (whitelist), -b (blacklist), or -c (chronometer)  for more information on usage`

but this doesn't work. The lines for chronometer seem to be missing the "$@" parameter but even after adding that, it doesn't seem to pass the -h on to the script in /opt/pihole.

For example, I used to run '/opt/pihole/chronometer.sh -j' but how would I do that with the new pihole script? You'd think 'pihole -c -j' but that doesn't seem to work.

**Comment by PromoFaux** [comment]
Thanks again @jradwan If I could assign you a tag, it would be "Bug Finder Extraordinaire"

Will push out a fix later on today. Actually interestingly, I never did add in the `-h` tag when I wrote `whitelist.sh` and `blacklist.sh`, so that has never worked!

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/14310955/aed1af42-fbdc-11e5-812e-e9a19cd1346e.png)

**Comment by jradwan** [comment]
Thanks for the kind words, @PromoFaux. You guys are doing great work and I'm just trying to help in the tiny way I can. I know getting constant bug reports can be frustrating to a developer. :)

**Comment by PromoFaux** [comment]
Constant bug reports on a project like this are helpful...

We all have full time jobs, and lives outside of those jobs, so we work on this in what spare time we can afford to spend on it, which means we don't always get to test it as thoroughly as we want. It also means that sometimes silly mistakes will slip by us and make their way onto the release branch, but we're getting better, and I think we have a good relationship with our user-base. 

For the most part we can accept the bug reports with the good faith in which they were submitted, and it's very rare that some arrogant master programmer comes along and tells us how rubbish we are, without contributing a solution. But that can happen! Those are the only reports that can be frustrating.

Please keep submitting your bug reports! They help!
