### ISSUE TITLE
Add Almalinux Support

### ISSUE THREAD

**Issue by tiny6996** [pi-hole/pi-hole#4393]
### Versions

- Pi-hole:  v5.5
- AdminLTE:  v5.7 
- FTL:  v5.10.2

### Platform

- OS and version:  AlmaLinux 8.4

- Platform:  proxmox LXC container

### Expected behavior
Install works with no extra flags since almalinux is 1:1 to compatible with RHEL/CentOS

### Actual behavior / bug

In order for the install to work I had to run the installer the following command instead of just piping straight to bash. -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

### Steps to reproduce

1. run curl -sSL https://install.pi-hole.net | sudo bash
2. receive  this error message Unsupported OS detected: Almalinux 8.4
      If you are seeing this message and you do have a supported OS, please contact support.
3. run curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash and the install completes as expected

## Debug Token

- URL:  https://tricorder.pi-hole.net/PoK2UimG/

I will submit a pull request to update the script and try on rockylinux and centos stream if time allows

**Comment by tiny6996** [comment]
In order for this to be achieved AlmaLinux=8 needs to be added to the versions.pi-hole.net TXT record

**Comment by PromoFaux** [comment]
> AlmaLinux=8 needs to be added to the versions.pi-hole.net TXT record

Personally, I think I'd rather we didn't add this into the TXT record. It still isn't an officially supported OS (Read this as - an OS that the developers are familiar with and can support, not whether or not it technically "just works")

However, after some discussion with @bcambl I think I can agree that adding it into the secondary check (as suggested in your linked PR) is acceptable.

**Comment by yubiuser** [comment]
@tiny6996 Are you going to re-submit your PR against development branch?
