### ISSUE TITLE
Intermittent ServFail on PiHole since latest update

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#4399]
### Versions

 - Pi-hole version is v5.5 (Latest: v5.5)
 - AdminLTE version is v5.7 (Latest: v5.7)
 - FTL version is v5.10.2 (Latest: v5.10.2)

### Platform

- OS and version:  Raspbian Debian 10

- Platform:  Raspberry Pi

### Expected behavior

Port 53 does not servfail (when the upstreams are working fine)

### Actual behavior / bug

Intermittent since the latest update, I am getting PiHole serving up a "servfail"
However, both Upstreams (cloudflared and unbound) are not servfailing. Just PiHole

### Steps to reproduce

1. Intermittently at random intervals, PiHole will stop resolving, and will just ServFail

## Debug Token

- URL:  https://tricorder.pi-hole.net/xYtUA9K3/

### Screenshots

**PiHole:**
`nslookup google.ca 127.0.0.1`
```
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find google.ca: SERVFAIL
```

**Cloudflared**
`nslookup google.ca 127.0.0.2`
```
Server:         127.0.0.2
Address:        127.0.0.2#53

Non-authoritative answer:
Name:   google.ca
Address: 172.217.1.3
Name:   google.ca
Address: 2607:f8b0:400b:80f::2003
```
**Unbound**
`nslookup google.ca 127.0.0.3`
```
Server:         127.0.0.3
Address:        127.0.0.3#53

Non-authoritative answer:
Name:   google.ca
Address: 172.217.1.3
Name:   google.ca
Address: 2607:f8b0:400b:80f::2003
```

![image](https://user-images.githubusercontent.com/9235633/138015705-4324c4c3-e8e6-419b-8cf7-25dff86bde84.png)
![image](https://user-images.githubusercontent.com/9235633/138015987-0d56c56b-c98a-4de9-b2e0-66a13fef7d73.png)

### Additional context

I do consider myself an advanced PiHole user but this one is really stumping me

I have Pihole on 127.0.0.1#53, and upstream I have both Cloudflared on 127.0.0.2#53, and Unbound on 127.0.0.3#53
I am not getting servfail on Cloudflared or Unbound, only Pihole.
This setup has been working all year, and has recently started having issues after last update

I did read that servfail can be caused by wrong clock time
The clock is correct, and this is only intermittent 
 `timedatectl` at 7:18PM 
```
               Local time: Tue 2021-10-19 19:18:57 EDT
           Universal time: Tue 2021-10-19 23:18:57 UTC
                 RTC time: n/a
                Time zone: America/Toronto (EDT, -0400)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```

I've tried isolating the upstream servers by disabling cloudflared, and then  unbound as upstream, and it still happens

**Comment by yubiuser** [comment]
Maybe it is because there are two lines?
I got only 

`trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D`

**Comment by DL6ER** [comment]
SERVFAIL is the expected response if anything goes wrong while validating DNSSEC. Does `/var/log/pihole.log` contain any more information for said failed queries? We're specially looking for `EDE` (extended DNS errors) here

**Comment by p1r473** [comment]
Attempt with a more unique domain: `cat /var/log/pihole.log | grep pokemon.com`
```
Oct 20 13:53:52 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:53:52 dnsmasq[2015]: forwarded pokemon.com to 127.0.0.2
Oct 20 13:53:53 dnsmasq[2015]: dnssec-query[DS] pokemon.com to 127.0.0.2
Oct 20 13:53:53 dnsmasq[2015]: validation pokemon.com is BOGUS
Oct 20 13:53:53 dnsmasq[2015]: reply pokemon.com is 69.172.200.183
Oct 20 13:53:59 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:53:59 dnsmasq[2015]: forwarded pokemon.com to 127.0.0.2
Oct 20 13:53:59 dnsmasq[2015]: dnssec-query[DS] pokemon.com to 127.0.0.2
Oct 20 13:53:59 dnsmasq[2015]: reply pokemon.com is no DS
Oct 20 13:53:59 dnsmasq[2015]: reply pokemon.com is 69.172.200.183
Oct 20 13:53:59 dnsmasq[2015]: query[AAAA] pokemon.com from 127.0.0.1
Oct 20 13:53:59 dnsmasq[2015]: forwarded pokemon.com to 127.0.0.2
Oct 20 13:53:59 dnsmasq[2015]: reply pokemon.com is NODATA-IPv6
Oct 20 13:54:00 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:54:00 dnsmasq[2015]: cached pokemon.com is 69.172.200.183
Oct 20 13:54:00 dnsmasq[2015]: query[AAAA] pokemon.com from 127.0.0.1
Oct 20 13:54:00 dnsmasq[2015]: cached pokemon.com is NODATA-IPv6
Oct 20 13:54:00 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:54:00 dnsmasq[2015]: cached pokemon.com is 69.172.200.183
Oct 20 13:54:00 dnsmasq[2015]: query[AAAA] pokemon.com from 127.0.0.1
Oct 20 13:54:00 dnsmasq[2015]: cached pokemon.com is NODATA-IPv6
Oct 20 13:54:01 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:54:01 dnsmasq[2015]: cached pokemon.com is 69.172.200.183
Oct 20 13:54:01 dnsmasq[2015]: query[AAAA] pokemon.com from 127.0.0.1
Oct 20 13:54:01 dnsmasq[2015]: cached pokemon.com is NODATA-IPv6
Oct 20 13:54:20 dnsmasq[2015]: query[A] pokemon.com from 127.0.0.1
Oct 20 13:54:20 dnsmasq[2015]: cached pokemon.com is 69.172.200.183
Oct 20 13:54:20 dnsmasq[2015]: query[AAAA] pokemon.com from 127.0.0.1
Oct 20 13:54:20 dnsmasq[2015]: cached pokemon.com is NODATA-IPv6
```
![image](https://user-images.githubusercontent.com/9235633/138145861-493fb8ba-801c-4032-ab1a-a3c021ba8cf4.png)

**Comment by p1r473** [comment]
> That's a good idea.
> 
> > Could the upstream Cloudflare and/or Unbound be doing wonky things to DNSSEC?
> 
> Yes, just as you just quotes in your last comment.
> 
> > The reason I am using both Cloudflared and Unbound as upstream is for some high availability
> 
> I'm running unbound as my sole upstream for more than five years now. The only downtime I've ever seen was when my Internet connection was down altogether - which is expected. Hence, I wouldn't consider it to be any unreliable. The only drawback is slowness until the cache is populated. But this should not take very long and isn't a concern when the machine is not restarted all that often.

I have been using a cache size of 150 (I believe the minimum with DNSSec) mostly because if I am doing whitelisting work, I dont want a cached response
Can you confirm that if I have a big cache, and I whitelist something, the whitelist will override the cached response?
As well, any tips for best cache size? I am seeing 10k 50k, and 100k on Discourse

**Comment by p1r473** [comment]
Thanks, yes I meant whitelisting within PiHole
I've set the cache size to 10k
Ive removed Cloudflared as an upstream, and will use Unbound only for now

I will reopen if the issue persists on Unbound
Working theory is that Cloudflare is wonky

**Comment by jdrch** [comment]
OK folks, over 2 months later (LOL) this issue is finally getting Cloudfare staff attention. If you're still having problems, please chime in at [this Cloudflare Community thread](https://community.cloudflare.com/t/dnscrypts-queries-randomly-fail-with-the-error-response-error/334624/7).

**Comment by jdrch** [comment]
**UPDATE:** Per Cloudflare this bug is the result of one of their abuse protection systems ratelimiting certain prefixes, which had the effect of ratelimiting benign IP addresses within said prefixes. 

If you are still having this problem, email resolver@cloudflare.com referencing the [issue](https://community.cloudflare.com/t/dnscrypts-queries-randomly-fail-with-the-error-response-error/334624).

**Comment by poentodewo** [comment]
btw it happen in cloudflare gateway too its fine when using DOT
