### ISSUE TITLE
 www-data : problem with defaults entries ; TTY=unknown ; PWD=/var/www/html/admin ; USER=root ;

### ISSUE THREAD

**Issue by junior466** [pi-hole/pi-hole#4404]
After the most recent upgrade to pihole, I am not receiving the following emails every 1 minute:

     www-data : problem with defaults entries ; TTY=unknown ; PWD=/var/www/html/admin ; USER=root ;

It must be related to pihole as I noticed the messages shortly after the update. 

Any help on how to stop them would be greatly appreciated.

**Comment by mgeeky** [comment]
Sorry but I too suffer from this one, dealing with more than 20k emails per day. No solution provided in Internet could help me out here.

Any ideas what might be worth checking?

My current sudoers:

```
Defaults    env_reset
Defaults    mail_always=off
Defaults    mail_badpass=off
Defaults    mail_no_user=off
Defaults    mail_no_host=off
Defaults    mail_no_perms=off
Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

root    ALL=(ALL:ALL) ALL
#includedir /etc/sudoers.d
```

The `/etc/sudoers.d` directory doesn't contain anything valuable whatsoever. I'm running latest Pihole.

Any help would be much appreciated!
Mariusz.
