### ISSUE TITLE
Invalid domain on spanish character ñ

### ISSUE THREAD

**Issue by Joe1962** [pi-hole/pi-hole#4410]
### Versions
  Pi-hole version is v5.5 (Latest: v5.6)
  AdminLTE version is v5.7 (Latest: v5.8)
  FTL version is v5.10.2 (Latest: v5.11)

### Platform
- OS and version:  Debian 10.11
- Platform:  CT o Proxmox 6.4-13

### Expected behavior

pihole -g should not give invalid domain on non-english characters.

### Actual behavior / bug

pihole -g gives an invalid domain with https://blocklistproject.github.io/Lists/alt-version/porn-nl.txt on www.xvideos-español.com, presumably due to the spanish character ñ, which is only present on that URL in the whole list.

### Steps to reproduce

1. Add https://blocklistproject.github.io/Lists/alt-version/porn-nl.txt to adlists.
2. Click on Tools / Update gravity / Update
3. Scroll down to https://blocklistproject.github.io/Lists/alt-version/porn-nl.txt

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Joe1962** [comment]
FWIW, I was looking at the screen today during an update and saw this:

  [i] Analyzed 190258 domains, 7 domains invalid!
      Sample of invalid domains:
      - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф

So it's failing on any type of non-ASCII7 character, which fits with yubiusers's findings.

**Comment by DL6ER** [comment]
This isn't a Pi-hole issue but rather an issue with the list itself. Unicode domains will never be requested by any modern browser or app, hence the warning pointing you too the underlying problem.
