### ISSUE TITLE
Pi-Hole configurator not populating Static IP information from selected interface when not connected

### ISSUE THREAD

**Issue by emorgoch** [pi-hole/pi-hole#4418]
### Versions
- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Rasbperry Pi 4

### Expected behavior
When Pi-Hole is being configured and the selected interface is setup with a static IP address, it should use that interfaces pre-configured IP information, even if the interface is not connected.

### Actual behavior / bug

Fresh install of Raspberry Pi OS. Raspberry Pi is connected to Wi-Fi network on 192.126.1.0/24 subnet via DHCP. /etc/dhcpcd.conf is edited such that eth0 is setup with a static IP on 192.168.2.0/24 subnet. Eth0 is not physically connected. One-Step Automated Install is initiated with "curl -sSL https://install.pi-hole.net | bash". At the interface selection section, only eth0 is selected as the interface to use. However, when it asks for Statis IP Addresses, it pre-populates with the DHCP address information from wlan0.

### Steps to reproduce

1. Configure Raspberry Pi such that wlan0 connects via DHCP to subnet 192.168.1.0/24, and eth0 has static IP configured on 192.168.2.1/24 subnet.
2. Have wlan0 connected and running, but eth0 disconnected
3. Run pi-hole installer or pihole -r to reconfigure
4. Select eth0 as the interface to use
5. Pihole will prompt to use wlan0 IP address as the static IP address

## Debug Token

- URL:  https://tricorder.pi-hole.net/prt3dxDH/

### Screenshots

![image](https://user-images.githubusercontent.com/23462100/139512341-803f8101-a814-468b-bc6e-6a59a2f0d83a.png)
![image](https://user-images.githubusercontent.com/23462100/139512353-a2dfb6b8-ab1b-48a7-8c61-a0da903768cc.png)
![image](https://user-images.githubusercontent.com/23462100/139512363-d34c84d4-875c-4841-b0b2-96fc62007a76.png)

### Additional context

The purpose of this setup is so I can pre-configure the raspberry Pi for another location, and the be able to just drop it in once there without any additional configuration.

**Comment by yubiuser** [comment]
I think this is an edge-case. The installer checks for an IPv4 address which has a route to 8.8.8.8. As your `eth0` is not connected at the moment, there is no valid route over this interface.
https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/automated%20install/basic-install.sh#L584-L610

Also, the number of users having set a static address at `/etc/dhcpcd.conf` **before installing Pi-hole** will be rather small. Adding a logic reading and parsing vom `/etc/dhcpcd.conf` seems a bit over the top in my eyes, but I see that there is one option missing: don't set a static address at all (in your case: leave `/etc/dhcpcd.conf` completely untouched and don't force you to enter any IP information.

**Comment by yubiuser** [comment]
The fix (adding an option to leave `dhcpd.conf` untouched) has been released in

https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
