### ISSUE TITLE
Idea - list whitelist / blackist from the command line

### ISSUE THREAD

**Issue by DonLexos** [pi-hole/pi-hole#442]
Now that we have a pihole command that will perform things based on input I was checking out the whitelist/blacklist items (to update the FAQ later).

I noticed there is an option to add or remove items from the list, but not to list the items in the list. Could `sudo pihole -w -l` or `sudo pihole -w --list` be added where it will simply display the contents of the black- or whitelist ?

**Comment by PromoFaux** [comment]
Sure thing! All it needs to be is a simple `cat /etc/pihole/whitelist.txt` (or whatever the location is set as in `pihole.conf`)

**Comment by DonLexos** [comment]
This was added ! :+1: 

Closing this ;-)
