### ISSUE TITLE
Update gravity does not work correct?

### ISSUE THREAD

**Issue by wanttoreportabug** [pi-hole/pi-hole#4422]
### Versions

 Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)

### Platform

- OS and version:  Linux Mint (latest and up-to-date)

- Platform:  Raspberry Pi (4)

### Expected behavior

_A clear and concise description of what you expected to happen._
If i update gravity it should read the lists and process them

### Actual behavior / bug

_A clear and concise description of what the bug is._
So... i might be completely wrong and dont understand how to do what i expext the update-gravity should do but: I make my own lists and do a lot of research into what to block and what not. This means i update gravity (sometimes) more than once a day. The bug seems to be that: When i take out entry's from my blocklist and then update-gravity it refuses to see that the list has changed and does not remove the entry(s) i deleted. I tryed flushing logs, reboot, update, removing the list completely, then update gravity, then adding the list again and do an update-gravity. The deleted entry(s) stay blocked.

### Steps to reproduce
Make a list with some entry's and put concent.cookiebot.com in the list. FTP it to your server. Now update gravity. Check if it is blocked, now edit the list and remove concent.cookiebot.com. FTP it to your server. Do update-gravity. Check to see that the site is still blocked. You can do this with any domain/server/adress. Adding 1 entry and deleting another also does not work.

Se above

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._
I have the lists on my own domain (website) because the lists are used by others. I checked (checksum) to see if the FTP somehow fails but Filezilla correctly spots the file is changed (overwrite yes/no) and the checksum is correct after uploading.

I never did any bugreporting on GitHub so i hope the above is accourding to guidelines.

**Comment by jfb-pihole** [comment]
What is the complete output of `pihole -g `from the terminal?

**Comment by yubiuser** [comment]
> now edit the list and remove concent.cookiebot.com. FTP it to your server. Do update-gravity. Check to see that the site is still blocked

This domain does not exists. It's not blocked. 

```
chrko@ThinkPad-X230:~$ dig concent.cookiebot.com

; <<>> DiG 9.17.19-1+ubuntu18.04.1+isc+1-Ubuntu <<>> concent.cookiebot.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52573
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;concent.cookiebot.com.		IN	A

;; AUTHORITY SECTION:
cookiebot.com.		600	IN	SOA	pdns05.domaincontrol.com. dns.jomax.net. 2021101402 28800 7200 604800 600

;; Query time: 99 msec
;; SERVER: 10.0.1.5#53(10.0.1.5) (UDP)
;; WHEN: Fri Nov 05 22:01:48 CET 2021
;; MSG SIZE  rcvd: 120
```

Which other domain does not work for you?

**Comment by wanttoreportabug** [comment]
So i probably gave just an example. Do this: add an (**existing**) domain to your blocklist. FTP it to your server. Update gravity. Check if the domain you entered is actualy blocked. Now remove the entry from your blocklist. Upload the (now new) blocklist to your server. Update gravity. Now update gravity / pihole -g will say that there where no changes detected and the domain is still blocked while it is NOT in the blocklist anymore. I did some more testing to make sure it had nothing to do with some checks on the server (i have them on my domain). The list on the server checks out so it must be in the update portion of Pihole not "seeing" there is a new list? I am not a programmer just a user.

**Comment by jfb-pihole** [comment]
Run a gravity update in verbose mode and it may give you some insight into how that blocklist is being loaded.

`sudo bash -x /opt/pihole/gravity.sh`

**Comment by yubiuser** [comment]
I tried to reproduce it locally, but every modification is recognized as it should be. 
But I think I know where to look at for your issue. How do you access the file on your ftp server via Pi-hole? Which Protocol do you use to download the list?

**Comment by yubiuser** [comment]
Closing as the same issue has been re-reported: https://github.com/pi-hole/pi-hole/issues/4531

**Comment by fotingo** [comment]
I've noticed this too. I have to update gravity more than once in order for updated adlists to get updated.
