### ISSUE TITLE
/etc/.pihole/automated install/basic-install.sh: line 1643: /opt/pihole/gravity.sh: Is a directory

### ISSUE THREAD

**Issue by Janderion47** [pi-hole/pi-hole#4424]
### Versions
- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform

- OS and version:  Raspberry Pi OS Latest

- Platform:  RPi2

### Expected behavior

Updating from pihole v5.2, FTL 5.10.2, WI 5.7, I expected to have a fine time using 'pihole -up'

### Actual behavior / bug

Updating pihole via 'pihole -up' went find until this last section were is says:
/etc/.pihole/automated install/basic-install.sh: line 1643: /opt/pihole/gravity.sh: Is a directory

  Unable to complete update, please contact Pi-hole Support

### Steps to reproduce

Updating from those versions of pihole using 'pihole -up'; thats pretty much it.

## Debug Token

- URL:  https://tricorder.pi-hole.net/9oYzDNOB/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Janderion47** [comment]
It does seem that pihole is behaving as it should be, and is not displaying any issues on the web interface, but I am still alarmed by this issue that popped up during the updating/upgrading process.

**Comment by PromoFaux** [comment]
What is the result of running `pihole -g`?

**Comment by Janderion47** [comment]
> What is the result of running `pihole -g`?

/usr/local/bin/pihole: line 74: /opt/pihole/gravity.sh: Is a directory

**Comment by PromoFaux** [comment]
and `ls -lah /opt/pihole`, please

**Comment by Janderion47** [comment]
> and `ls -lah /opt/pihole`, please

total 196K
drwxr-xr-x 4 root root 4.0K Nov  7 12:06 .
drwxr-xr-x 4 root root 4.0K Jan 29  2021 ..
drwx------ 2 root root 4.0K Oct 11 09:07 chronometer.sh
-rwxr-xr-x 1 root root 1.1K Nov  7 12:06 COL_TABLE
drwx------ 2 root root 4.0K Oct 11 09:07 gravity.sh
-rwxr-xr-x 1 root root 9.9K Nov  7 12:06 list.sh
-rwxr-xr-x 1 root root 2.0K Nov  7 12:06 piholeARPTable.sh
-rwxr-xr-x 1 root root 8.2K Nov  7 12:06 piholeCheckout.sh
-rwxr-xr-x 1 root root  62K Nov  7 12:06 piholeDebug.sh
-rwxr-xr-x 1 root root 2.8K Nov  7 12:06 piholeLogFlush.sh
-rwxr-xr-x 1 root root  823 Nov  7 12:06 pihole-reenable.sh
-rwxr-xr-x 1 root root 9.1K Nov  7 12:06 query.sh
-rwxr-xr-x 1 root root 2.9K Nov  7 12:06 setupLCD.sh
-rwxr-xr-x 1 root root 8.0K Nov  7 12:06 uninstall.sh
-rwxr-xr-x 1 root root 3.1K Nov  7 12:06 updatecheck.sh
-rwxr-xr-x 1 root root 7.7K Nov  7 12:06 update.sh
-rwxr-xr-x 1 root root 6.5K Nov  7 12:06 version.sh
-rwxr-xr-x 1 root root  27K Nov  7 12:06 webpage.sh
-rwxr-xr-x 1 root root 1.2K Oct 11 21:57 wildcard_regex_converter.sh

**Comment by PromoFaux** [comment]
It's not wrong, the `d` flag is set on both `gravity.sh` and `chronometer.sh`

I see you are on an Rpi - what model is it? Make sure that the power supply is correctly rated to provide it with enough power, else you can start to see oddities like this on the filesystem.

Quick fix (maybe):

```
sudo rm -rf /opt/pihole/gravity.sh
sudo rm -rf /opt/pihole/chronometer.sh
pihole -r 
```

Choose repair at the last step. However, this could be indicative of a wider issue with filesystem corruptions, not just with Pi-hole files - You may wish to start again with a fresh SD card

**Comment by PromoFaux** [comment]
Any joy?

**Comment by Janderion47** [comment]
Pihole seems to work fine now, but if there are any problems in the future, I will open another issue here with a link back to this.
