### ISSUE TITLE
Empty Blocklist 

### ISSUE THREAD

**Issue by SirTonic** [pi-hole/pi-hole#4426]
Hello friends,
Today after clean install Raspi and clean install Pi-hole I have empty blacklist. 
No files black&white txt in /etc/pihole, no tab blacklist in settings.

My debug log is: https://tricorder.pi-hole.net/26KWUj0r/

pi@raspberrypi:/etc/pihole $ pihole -g
  [i] Neutrino emissions detected...
  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity.db_temp
  Error: no such table: main.gravity
  [i] Number of gravity domains: 0 (0 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0

What can I Do?
Thanks for help

**Comment by yubiuser** [comment]
> No files black&white txt in /etc/pihole

Those files are not used anymore since v5.0.

> What can I Do?

Add `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts` to "Group management > Adlists" and run `pihole -g` again.

**Comment by SirTonic** [comment]
> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Amazing, thanks 93790 domain on list.
and I have a question.
Can I see blocklist tab in settings?

**Comment by yubiuser** [comment]
> Can I see blocklist tab in settings?

This was removed in the last version as it only contained a link to "Group management > Adlists"

**Comment by SirTonic** [comment]
> > Can I see blocklist tab in settings?
> 
> This was removed in the last version as it only contained a link to "Group management > Adlists"

OK, thanks for help and answer.
