### ISSUE TITLE
PiHole and (suspected) QUIC packets on port 445 UDP

### ISSUE THREAD

**Issue by GvY85** [pi-hole/pi-hole#4428]
### Versions
- Pi-hole:  5.6
- AdminLTE:  5.8
- FTL:  5.22

### Platform

- OS and version:  Debian 11
- Platform:  x86_64

Since some time I am seeing incoming UDP packets on port 445 in my UFW logs.
These look to be QUIC packets and are comming from Facebook and Apple adresses.
Since they are able to go trough my NAT (Fritzbox) according to the AVM helpdesk they are probably responses to requiests from my device.
Since I am running a mini pc with Debian 11 and Pi-Hole, PiVPN and Unbound and and SMB share I cant think of any device requesting stuff at these servers other than perhaps VPN clients?

So the question is if these are really QUIC packets? If it is something that Pihole has control over and what I should do with them? Allow them, ignore them (= full UFW log) or is this a bug somewhere?

For the complete info with screenshots and captured UDP packets see:
https://github.com/MichaIng/DietPi/issues/4933

**Comment by GvY85** [comment]
Token:  OyjufKKR

**Comment by DL6ER** [comment]
Pi-hole only ever sends plain DNS queries over port 53 out into the Internet. There is no implementation of QUIC, DoH, DoT or something else without you running a local proxy for such a service.

> These look to be QUIC packets and are comming from Facebook and Apple adresses.

Okay, so when they come from these servers, something has to have caused them. I skimmed over your referenced DietPi issue ticket really quick and see that you managed to do a full traffic recording using the Fritzbox. That's a very good start. You should be able to easily trace back these replies to the initial queries made. This might reveal more information, however,  I know for sure that this is not something Pi-hole will be causing (without any modifications on your side, at least).
