### ISSUE TITLE
`dnsutils` not found in Raspbian bullseye

### ISSUE THREAD

**Issue by cycool29** [pi-hole/pi-hole#4429]
### Versions

- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A

### Platform

- OS and version:  Raspberry Pi OS bullseye

- Platform:  Raspberry Pi armhf

### Expected behavior

pi-hole install properly with `curl -sSL https://install.pi-hole.net | sudo bash`

### Actual behavior / bug

`dnsutils` not found in bullseye repo. 

<details>
<summary>Terminal output</summary>
 
```
pi@raspberrypi:~ $ curl -sSL https://install.pi-hole.net | sudo bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [i] Checking for dnsutils (will be installed)
  [i] Processing apt-get install(s) for: dnsutils, please wait...

E: Unable to locate package dnsutils

```
</details>

`sudo apt info dnsutils` shows `E: Unable to locate package dnsutils`

### Steps to reproduce

`curl -sSL https://install.pi-hole.net | sudo bash` in Raspbian bullseye. 

### Additional context

Both deb from [debian bullseye repo](https://packages.debian.org/bullseye/dnsutils) and [buster repo](https://packages.debian.org/buster/dnsutils) won't work. (dependencies hell)

**Comment by PromoFaux** [comment]
Odd, I can see them on my pi4...

![image](https://user-images.githubusercontent.com/1998970/141782551-d182df80-731c-47cf-a44c-30297b1417a7.png)

Is this a fresh SD card image?

**Comment by cycool29** [comment]
> Is this a fresh SD card image?

Not very fresh, but I flashed the image 2 two days after rpf announce bullseye image.

![image](https://user-images.githubusercontent.com/88134003/141783348-8e48c75d-8ae3-4407-ac06-92212035c65d.png)

I don't think I have issues with my source lists.

**Comment by PromoFaux** [comment]
I'm not in a position to flash a fresh image right now - but not sure what best to suggest here! Maybe remove the box86 repo from sources and try again - just incase...

**Comment by cycool29** [comment]
> Maybe remove the box86 repo from sources and try again - just incase...

Removed, still no luck...

![image](https://user-images.githubusercontent.com/88134003/141785244-5d16abde-9fa5-402b-8396-8713527c31ff.png)

**Comment by PromoFaux** [comment]
I'm just flashing an SD card now with the latest Raspberry Pi OS image - the first thing I will do is try to install Pi-hole and see what happens

**Comment by PromoFaux** [comment]
Yep, works fine here :)

One thing I did notice - ` curl -sSL https://install.pi-hole.net | sudo bash` you don't need the `sudo` there, the script will automatically elevate.

But - all is looking well here. I might suggest you try flashing a new SD card and going from there

**Comment by jfb-pihole** [comment]
I also flashed a fresh OS image using the latest Raspberry Pi Lite image dated 2021-10-30.

```
pi@Pi-ZeroW-dev:~ $ sudo apt info dnsutils
Package: dnsutils
Version: 1:9.16.22-1~deb11u1
Priority: optional
Section: net
Source: bind9
Maintainer: Debian DNS Team <team+dns@tracker.debian.org>
Installed-Size: 271 kB
Depends: bind9-dnsutils
Homepage: https://www.isc.org/downloads/bind/
Download-Size: 260 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
Description: Transitional package for bind9-dnsutils
 This is a transitional package. It can safely be removed.
```

**Comment by cycool29** [comment]
Thanks!

By the way, can you send the output of `sudo apt update`? Just want to check if I missed any source list.

**Comment by jfb-pihole** [comment]
Directly after a fresh install on a Pi Zero W:
```
sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by cycool29** [comment]
> Directly after a fresh install on a Pi Zero W:
> 
> ```
> sudo apt update
> Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
> Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> 11 packages can be upgraded. Run 'apt list --upgradable' to see them.
> ```

Weird, that is exactly same with mine.
However, I will try reflash the SD later.

**Comment by cycool29** [comment]
I just flashed my SD card, and the problem solved! Thanks for your help :)
