### ISSUE TITLE
Request - Filters List

### ISSUE THREAD

**Issue by luisnogueira** [pi-hole/pi-hole#443]
Best and professional filters list >>> https://adguard.com/en/filters.html

Can we add them to pi-hole?

**Comment by PromoFaux** [comment]
Looking through the lists, it appears not. They are formatted for adblock extensions like ublock, adblock plus, or adguard.

In order to include the lists, we need them to be in a [hosts file format](https://en.wikipedia.org/wiki/Hosts_(file))

**Comment by luisnogueira** [comment]
There must be a way to convert them, and keep only the hosts...

**Comment by PromoFaux** [comment]
It's certainly up for discussion! Do you have any suggestions?

**Comment by ToronMega** [comment]
I have the same Idea, but I think you have to filter the whole (data stream). 

And the  pi pole "only" respond to DNS request, and blacklisting all site, for exampel all "Social media" ,not all the  «Like» and «Tweet» buttons are comming from the main Social media Server. ;-)

**The prob with "Social media item" is this Site know all about our site visit. :-(**

**Comment by Mcat12** [comment]
Closing unless something comes up.
