### ISSUE TITLE
How to builid the optimal NSFW list for you here at Pi-hole?

### ISSUE THREAD

**Issue by spirillen** [pi-hole/pi-hole#4431]
# Intro

I have a couple of times been contacted by some of your Pi-hole users in relation to my anti [adult blacklisting][Porn Records] project which subsidiary included `https://github.com/clefspeare13/pornhosts` before it was taken down by Github, as a guess, for same reason they originally took down `https://github.com/mypdns/porn-records`.
Made a print of the issue between the GH-support and me here: https://mypdns.org/my-privacy-dns/porn-records/-/issues/1347.

To the question...

# The "What lists to use in pi-hole?"
A user asked me this question https://mypdns.org/mypdns/support/-/issues/253 as we had been [talking about](https://github.com/pallebone/PersonalPiholeListsPAllebone/issues/1) the `clefspeare13/pornhosts` which now is located here https://mypdns.org/clefspeare13/pornhosts, it is 100% the same as I have maintained it for roughly 2 years, Now I just happens to have the master key as well.

As you might notice in the earlier mention [issue](https://mypdns.org/mypdns/support/-/issues/253) I was assuming the [Whitelisting, Blacklisting and Regex](https://docs.pi-hole.net/core/pihole-command/?h=rege#whitelisting-blacklisting-and-regex) actually was capable of blacklisting imported records in case you applied the `-wild` to any list a user might import, and (as i later found out) automatically applied the regex for this, as you need the full regex vs in RPZ for which the lists original is set up to support.

The question is, how can we put the records of [Porn Records][Porn Records] together to build the optimal lists for your users?.

----------

##  Mostly OT
This issue have a little, but yet kind of related to this topic regarding the future builds for Pi-Hole supporting lists. tl;dr `https://mypdns.org/mypdns/support/-/issues/254` any comets is appreciated.

----------

### Privacy concern
For privacy violation, `https://discourse.pi-hole.net/` and `https://discourse.pi-hole.net/c/feature-requests/8` are unacceptable communication channels, barely enough GH,

[Porn Records]: https://mypdns.org/my-privacy-dns/porn-records "Porn Records - Anti porn hosts blacklist"

**Comment by jfb-pihole** [comment]
I don't understand your question. Pi-hole does not maintain or curate NY lists. If you wish to maintain lists that users will like, we encourage you to do so.

**Comment by spirillen** [comment]
> I don't understand your question. Pi-hole does not maintain or curate NY lists. If you wish to maintain lists that users will like, we encourage you to do so.

Damned.... All this text for nothing...

I do maintain the following list

- https://mypdns.org/my-privacy-dns/porn-records
- https://mypdns.org/clefspeare13/pornhosts

The question is how the porn-records project can be tailored (optimized) to include perfect lists for pi-hole along side the hosts project (https://mypdns.org/clefspeare13/pornhosts)

> Pi-hole does not maintain or curate NY lists

How you came to this answer as a response to my question is beyond my perception.
I'm actually confused there.

I may have to read the hole thing over after some good night sleep.

**Comment by jfb-pihole** [comment]
Your adlists for use by Pi-hole will need to be in HOST format, with domains only (no wildcards, regex or special characters).  The format can be either with a leading IP or without.  If there is a leading IP (as would be in a HOSTS file), Pi-hole will strip them on import.  Either of the following would be acceptable on a single line:

```
0.0.0.0  flurry.com
flurry.com
```

That is the only format that Pi-hole will import into gravity.

**Comment by spirillen** [comment]
Ok, thanks for the reply, I'll set up a repo for your users that will generate a simple list from both repos 

(As I currently is importing everything into porn-records as the master backend)

- https://mypdns.org/my-privacy-dns/porn-records
- https://mypdns.org/clefspeare13/pornhosts

I will give you a ping once done, then you hopefully is open for testing it.

**Comment by spirillen** [comment]
OK, now there is a dev branch which held the new way of doing stuff. These lists should also be optimized for pi-hole as well.

Here is my local test result for a "first" spin. Please give it a test at let me now about what ever you think might be improved. The mergeRequest for comments can be found here: https://mypdns.org/clefspeare13/pornhosts/-/merge_requests/1

```
pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/0.0.0.0/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29206 domains
  [i] List stayed unchanged

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/127.0.0.1/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29206 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/mobile/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 30169 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/safesearch/0.0.0.0/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29411 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/safesearch/127.0.0.1/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29529 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/safesearch/mobile/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 30374 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/safesearch/strict/0.0.0.0/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29529 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/safesearch/strict/127.0.0.1/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29411 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/strict/0.0.0.0/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29324 domains

  [i] Target: https://mypdns.org/clefspeare13/pornhosts/-/raw/develop/download_here/strict/127.0.0.1/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 29324 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 295483 (30448 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 3
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

**Comment by dschaper** [comment]
How can we help you?

**Comment by spirillen** [comment]
> How can we help you?

1. You could to a start help testing the list on you individual installations to see if it formatted correctly and works as attended.
2. You can give any kind of _**feedback**_ on the list.
3. It wouldn't heart a bit if any of your users chooses to help contributing to the [master lists](https://mypdns.org/my-privacy-dns/porn-records)
4. It would be super if the list could be added to the default install filter as optional adult filter. (But let's parse ad 1 & 2 first)
5. subsidiary it would make it to your recommendations list


### Little story behind the why.
The hole thing started as one of your users opened the question [What lists to use in pi-hole](https://mypdns.org/mypdns/support/-/issues/253) (Should be skimmed for broader understanding) in combination with the Github take down of the `/clefspeare13/pornhosts` which I have maintained via my own Porn-Records (adult,mypdns.cloud) and a couple of other sub project.

The above maid me think if or is there a way to build a better list for Pi-Hole than just the hosts file style ([rfc:952](http://tools.ietf.org/html/rfc952))

**Comment by dschaper** [comment]
Thanks for the reply.

We won't be adding any more lists to the installation suggestions. That was a decision made a long time ago. 

The only list style that works for Pi-hole is the hosts file style. 

I wish you the best of luck on your endeavor. It's out of scope for this discussion here, we only deal with bugs on GitHub. 

Feel free to open a discussion at https://discourse.pi-hole.net as that is the only place we would entertain more discussion.
