### ISSUE TITLE
Can not upgrade OS

### ISSUE THREAD

**Issue by thomasbruchet** [pi-hole/pi-hole#4446]
### Versions

  Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)

### Platform
pi@pihole:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Expected behavior

I want to upgrade my OS

### Actual behavior / bug

I can not upgrade my OS

### Steps to reproduce

pi@pihole:~ $ sudo apt update
Réception de :1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Atteint :2 http://archive.raspberrypi.org/debian buster InRelease
Réception de :3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB]
Réception de :4 http://raspbian.raspberrypi.org/raspbian buster/contrib armhf Packages [58,8 kB]
Réception de :5 http://raspbian.raspberrypi.org/raspbian buster/non-free armhf Packages [104 kB]
Réception de :6 http://raspbian.raspberrypi.org/raspbian buster/rpi armhf Packages [1 360 B]
13,2 Mo réceptionnés en 17s (789 ko/s)
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
116 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.
pi@pihole:~ $ sudo apt upgrade
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Calcul de la mise à jour... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  fonts-font-awesome fonts-glyphicons-halflings libc-ares2 libdbi1 libhiredis0.14 libjs-bootstrap libjs-d3 libjs-jquery-form libjs-jquery-metadata libjs-jquery-tablesorter
  libjs-jquery-ui libjs-rickshaw liblua5.1-0 liblua5.3-0 libmaxminddb0 libndpi2.6 libnetfilter-queue1 libnode64 libpcap0.8 libradcli4 librrd8 libuv1 libwireshark-data lua-bitop
  lua-cjson node-html5shiv nodejs nodejs-doc python-colorzero redis-server redis-tools
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
Les paquets suivants seront mis à jour :
  aspell base-files bind9-host bluez chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra debconf debconf-i18n debconf-utils dillo distro-info-data dnsutils ffmpeg
  firmware-atheros firmware-brcm80211 firmware-libertas firmware-misc-nonfree firmware-realtek gpicview libasound2 libasound2-data libaspell15 libavcodec58 libavdevice58 libavfilter7
  libavformat58 libavresample4 libavutil56 libbind9-161 libc-ares2 libc-bin libc-dev-bin libc-l10n libc6 libc6-dbg libc6-dev libdns-export1104 libdns1104 libgssapi-krb5-2 libicu63
  libirs161 libisc-export1100 libisc1100 libisccc161 libisccfg163 libjavascriptcoregtk-4.0-18 libk5crypto3 libkrb5-3 libkrb5support0 liblwres161 libmariadb3 libnftnl11 libntfs-3g883
  libpam-systemd libpostproc55 libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 libsndfile1 libssl1.1 libswresample3 libswscale5 libsystemd0 libtiff5 libudev1
  libuv1 libvlc-bin libvlc5 libvlccore9 libwebkit2gtk-4.0-37 linux-libc-dev locales mariadb-common multiarch-support ntfs-3g openssl php7.3-cgi php7.3-cli php7.3-common php7.3-intl
  php7.3-json php7.3-opcache php7.3-readline php7.3-sqlite3 php7.3-xml pi-bluetooth psmisc python3-debconf raspberrypi-bootloader raspberrypi-kernel raspberrypi-net-mods
  raspberrypi-sys-mods raspberrypi-ui-mods redis-server redis-tools rp-bookshelf rpi-eeprom rpi-update systemd systemd-sysv tzdata udev vlc vlc-bin vlc-data vlc-l10n vlc-plugin-base
  vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba vlc-plugin-skins2 vlc-plugin-video-output vlc-plugin-video-splitter vlc-plugin-visualization
116 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/350 Mo dans les archives.
Après cette opération, 47,6 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] O
Segmentation fault
E: Le sous-processus /usr/bin/apt-listchanges --apt || test $? -lt 10 a renvoyé un code d'erreur (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10
pi@pihole:~ $

## Debug Token

- URL:  https://tricorder.pi-hole.net/hKwia5dx/

**Comment by jfb-pihole** [comment]
This is not a Pi-hole problem, it is a problem with the underlying OS:

`Segmentation fault
E: Le sous-processus /usr/bin/apt-listchanges --apt || test $? -lt 10 a renvoyé un code d'erreur (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10`
