### ISSUE TITLE
IDN TLD domains not imported from blacklist

### ISSUE THREAD

**Issue by adamus1red** [pi-hole/pi-hole#4447]
### Versions

- Pi-hole:  5.6
- AdminLTE:  5.8
- FTL:  5.11

### Platform

- OS and version:  Rocky 8.5 Green Obsidian & Debian 11 bullseye

- Platform:  Raspberry Pi

### Expected behavior

When importing domains to be blacklisted which use an IDN TLD (such as .рф or .中国) I expect the domain to be imported as a blacklisted.

### Actual behavior / bug

When running a gravity sync the domains are reported as invalid and are not imported into the pi-hole blacklist.

```
  [i] Target: https://gist.githubusercontent.com/adamus1red/c8f450a72f7cbdd25260ff4c242f71fb/raw/a2da4ee927cd57c82237dee247bd295e6fe18f63/list.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 3 domains, 3 domains invalid!
      Sample of invalid domains:
      - test.中国
      - test.рф
      - test.भारत
```

### Steps to reproduce

1. Add this list to pi-hole adlists. [Example list containing 3 IDN domains](https://gist.githubusercontent.com/adamus1red/c8f450a72f7cbdd25260ff4c242f71fb/raw/a2da4ee927cd57c82237dee247bd295e6fe18f63/list.txt )
2. Run `pihole -g`
3. Gravity sync will report the domains as invalid

## Debug Token

- URL:  https://tricorder.pi-hole.net/ogM4TVFg/

### Screenshots

![image](https://user-images.githubusercontent.com/2502582/144349682-031dc423-0062-427a-a699-52a10ce63f84.png)

**Comment by DL6ER** [comment]
They are invalid as no browser will ever request them. Instead, they will all use punny-encoded domains, including the TLD. See [Wikipedia:Punycode](https://en.wikipedia.org/wiki/Punycode). For further details. From your screenshot, I suspect this is your own hosted list so you should convert the domains on it appropriately. You can either use CLI tools like `idn` for this or use online converters like https://www.punycoder.com/

**Comment by yubiuser** [comment]
This question/issue has been reported multiple time. Please use the search function next time before posting an issue.
https://github.com/pi-hole/pi-hole/issues?q=is%3Aissue+IDN+is%3Aclosed
