### ISSUE TITLE
Top Clients

### ISSUE THREAD

**Issue by mattmill98** [pi-hole/pi-hole#445]
I have set my DNS servers on my router to point Pi-Hole but this means that all clients show as the router / my public ip. I would rather to have it show the individual devices IP (PC's, Phones, etc). Is there anyway to do this?
![capture](https://cloud.githubusercontent.com/assets/10357263/14352253/7d503b1a-fccb-11e5-8771-de566a33634f.PNG)

**Comment by 7h3ju57** [comment]
Mine works as you would like it. How long have you allowed for devices to refresh etc.. I recall when i first implemented my pi-hole i had the same issue your describing, all my devices were showing up as my router. After about an hour things settled down and all ip's subscribed to pi-hole dns show up properly.

**Comment by DonLexos** [comment]
Maybe a simple router reboot works, since all DHCP clients will get a new IP and dnsmasq will (or should) log their requests from their respective IPs?

**Comment by PromoFaux** [comment]
@mattmill98 What type of router do you have? 

I've seen some cases where the wrong DNS setting is changed (or simply, the right DNS settings cannot be changed depending on the router) I _think_ the setting you're looking for is to set the WAN DNS, and not the DHCP. But I might be wrong there!

**Comment by mattmill98** [comment]
I've tried a reboot and no joy.
@PromoFaux I have the HG635 from talktalk.

**Comment by PromoFaux** [comment]
Take a look at [this thread](http://community.talktalk.co.uk/t5/Superpowered-Fibre-Broadband/HG635-keeps-losing-manual-DNS-settings/td-p/1495487) might be some useful information in there for you!

**Comment by mattmill98** [comment]
I've filled in the DNS setting to point at the RP in the fields that it says on the talktalk forum and still no joy.

**Comment by Mcat12** [comment]
Try flushing the log (`pihole -f`) and check after half an hour or so.

**Comment by mattmill98** [comment]
I ran that command and now all it shows is my public ip and no data, i ran the command about an hour ago 
![capture](https://cloud.githubusercontent.com/assets/10357263/14391022/abbdf366-fdb1-11e5-9df7-92ad72204a11.PNG)

**Comment by Mcat12** [comment]
Are you still having this issue? If so, does a reinstall/update help?

**Comment by mattmill98** [comment]
I'm still having the issue, I reinstalled and running version 2.6.2

**Comment by AtomicLaser** [comment]
I also see this issue - I set the DNS server in my dd-wrt router, and PiHole always shows it from 192.168.1.1

**Comment by Mcat12** [comment]
DNS rebind is off?

**Comment by AtomicLaser** [comment]
@Mcat12 Where does one find that setting to check?

**Comment by Mcat12** [comment]
I don't know... I don't have a dd-wrt router. D:

**Comment by 7h3ju57** [comment]
Go to services-> services, under dnsmasq disable"no dns rebind"

**Comment by AtomicLaser** [comment]
@7h3ju57 Thanks Justin!  I'll give that a try 👍

**Comment by 7h3ju57** [comment]
Np, let us know how it goes!

**Comment by DonLexos** [comment]
Had the same issue on OpenWRT, seems the router gave it's own IP (192.168.1.1) as the main DNS to all clients (which in turn makes it the only one in the top client overview in the pi-hole admin). In OpenWRT there is a setting to "actively" push different DNS servers to the clients, you might want to check the DD-WRT docs to see if you need to set it somewhere (probably near the DHCP/DNS settings)

**Comment by AtomicLaser** [comment]
Disabling 'No DNS' rebind didn't make a difference, been like that for 5 days and still reporting as coming from the router IP.  Even rebooted the router for luck, to no avail.  

No biggie to be honest, but would be nice to see!

**Comment by Mcat12** [comment]
Closing, as this seems to be an issue with the router...
