### ISSUE TITLE
Random Disconections

### ISSUE THREAD

**Issue by SkadiAegis** [pi-hole/pi-hole#4451]
### Versions

- Pi-hole:  5.6
- AdminLTE:  5.8
- FTL:  5.11

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_I expected to have the pihole as a DHCP and DNS._

### Actual behavior / bug

_Randomly starts losing packages and i get internet microcuts. After a wile it stops._

### Steps to reproduce

Steps to reproduce the behavior: it just happens randomly

## Debug Token

- URL:  https://tricorder.pi-hole.net/97TXMQ7O/

**Comment by yubiuser** [comment]
Why do you suspect Pi-hole?

> losing packages

Can also be an network connectivity issue.

___

From your debug log I see you use https://github.com/deividgdt/ytadsblocker. This script checks every 5 minutes if new google video domains have been accessed and adds them to your  gravity database. Afterwards it's running an gravity update which can shutdown DNS resolution for a short amount of time.

**Comment by SkadiAegis** [comment]
Thanks for the help lets see if it works.

**Comment by SkadiAegis** [comment]
Sadly it didn't work my network is failing again

**Comment by yubiuser** [comment]
What did you try?

**Comment by SkadiAegis** [comment]
Reinstalling raspbian without adding anything else.

**Comment by SkadiAegis** [comment]
New debug token: https://tricorder.pi-hole.net/1zCK4PX6/

**Comment by jfb-pihole** [comment]
Your debug log is normal.

**Comment by yubiuser** [comment]
> Reinstalling raspbian without adding anything else.

So not even installed Pi-hole? Than I think we could rule out Pi-hole as the source of the disconnects....

**Comment by SkadiAegis** [comment]
yes sorry with only pihole installed.

**Comment by SkadiAegis** [comment]
> Your debug log is normal.

Then the problem its in the network and not on the pi-hole? 
Maybe its because i have the raspberry pluged to a repeater instead of the router?

**Comment by yubiuser** [comment]
> Then the problem its in the network and not on the pi-hole?

Does the problem also occur if you remove your Pi-hole device from the network for a few days?

**Comment by SkadiAegis** [comment]
> > Then the problem its in the network and not on the pi-hole?
> 
> Does the problem also occur if you remove your Pi-hole device from the network for a few days?

i didn't try that but the problem appeared like 1/2 weeks after installing the pihole i'll try removing it to see if the problem its in the pihole.

**Comment by SkadiAegis** [comment]
Today i had the dhcp turned off (from the raspberry and turned on on the router) and one computer using pihole and another not using it and everything worked okay without any random disconection.

**Comment by SkadiAegis** [comment]
well the same as i said the last time everything works fine with the dhcp disabled but i would like to enable it that way the wireles devices can get a dinamic IP.

**Comment by SkadiAegis** [comment]
And I was wrong it started again to lose conection randomly.

**Comment by yubiuser** [comment]
I'm a bit lost in your description: do you experience disconnects also if you remove the Pi-hole device from the network?

**Comment by SkadiAegis** [comment]
If I remove Pi-hole from the network I don't get disconnects.

**Comment by SkadiAegis** [comment]
> well the same as i said the last time everything works fine with the dhcp disabled but i would like to enable it that way the wireles devices can get a dinamic IP.


without using the DHCP (using the DHCP from the router and setting the Pi-Hole as DNS worked well until I posted this mesage.

**Comment by SkadiAegis** [comment]
I changed the ethernet cable and now seems to work fine.
Thanks for the help.
