### ISSUE TITLE
Just a tiny cosmetic bug

### ISSUE THREAD

**Issue by wanttoreportabug** [pi-hole/pi-hole#4457]
### Versions

  Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)

### Platform

Raspberry Pi 4B

### Expected behavior

I have a regex blacklist. Pihole shows the number of entry's in the list (in my case it shows 54 entrys)

### Actual behaviour / bug

I did a count of my regex entry's and its actually 55. Now i remember from my programming days (in VB6) that if you show
the index of a list its 1 off so for the actual listnumber-count you needed to add 1. Probably the same here?

### Steps to reproduce

1. Go to your blacklist
2. Check the line that sayes xxxx entrys
3. Now count the entrys

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
I can't reproduce this issue. My counting is correct both for black and whitelist. Please re-count :)

I just briefly checked the code and the table footer uses the built-in function `info` of `datatables`
https://datatables.net/reference/option/info
