### ISSUE TITLE
basic-install.sh does not revert when failing

### ISSUE THREAD

**Issue by Schattensilber** [pi-hole/pi-hole#4458]
### Versions
- Pi-hole:  v5.6
- AdminLTE:  5.8
- FTL:  5.11

### Platform
- OS and version:  Ubuntu 20.04
- Platform:  Desktop

### Expected behavior

If the install fails it should revert the install process at least to an extend that no major problems occur for the user.

### Actual behavior / bug

The install failed at the stage of "DNS resolution is not available". This is a different issue. BUT afterwards I couldn't access any website. I manually tried to revert any changes the installer had made (based on the logs of the installer) and finally re-enabled the systemd-resolved DNSStubListener (by changing /etc/systemd/resolved.conf and restarting the service).
I'm no system admin but very IT-affine. This might cause serious problems for some people, so please build in safeguards into the basic-install script!

### Steps to reproduce

I don't know what caused the unavailability of the DNS server, but any way of achieving that should reproduce this problem.

I went with the route of first cloning the git repo and using "sudo ./basic-install.sh" in "/Pi-hole/automated install" from bash.

**Comment by yubiuser** [comment]
I don't know why the installation failed for you. Your main point

> If the install fails it should revert the install process at least to an extend that no major problems occur for the user.

is a duplicate of https://github.com/pi-hole/pi-hole/issues/3713

**Comment by Schattensilber** [comment]
Closed since duplicate.
