### ISSUE TITLE
conditional forwarding does not work anymore

### ISSUE THREAD

**Issue by WiredLife** [pi-hole/pi-hole#4462]
### Versions
- Pi-hole:  v5.6 (Latest: v5.6)
- AdminLTE:  v5.8 (Latest: v5.8)
- FTL:  v5.11 (Latest: v5.11)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) 5.10.17-v7l+
- Platform:  Raspberry Pi 4

i dont know which update has killed it but now it doesnt work anymore

01-pihole.conf:
[01-pihole.conf.txt](https://github.com/pi-hole/pi-hole/files/7696177/01-pihole.conf.txt)

setupVars.conf has this:
REV_SERVER=true
REV_SERVER_CIDR=192.168.176.0/24
REV_SERVER_TARGET=192.168.176.1
REV_SERVER_DOMAIN=Lunochod

root@Pi-hole-RPi4:~# dig jule-smartphone.lunochod

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> jule-smartphone.lunochod
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23671
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;jule-smartphone.lunochod.      IN      A

;; AUTHORITY SECTION:
.                       3553    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021121001 1800 900 604800 86400

;; Query time: 78 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Dec 11 02:03:41 CET 2021
;; MSG SIZE  rcvd: 128

root@Pi-hole-RPi4:~# dig bernd-sat.filmfreunde

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> bernd-sat.filmfreunde
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64004
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;bernd-sat.filmfreunde.         IN      A

;; AUTHORITY SECTION:
.                       3500    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021121001 1800 900 604800 86400

;; Query time: 41 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Dec 11 02:04:34 CET 2021
;; MSG SIZE  rcvd: 125

and when i try it directly:
root@Pi-hole-RPi4:~# dig @192.168.176.1 -p 23553 jule-smartphone.lunochod

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @192.168.176.1 -p 23553 jule-smartphone.lunochod
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25315
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;jule-smartphone.lunochod.      IN      A

;; ANSWER SECTION:
jule-smartphone.lunochod. 3600  IN      A       192.168.176.31

;; Query time: 0 msec
;; SERVER: 192.168.176.1#23553(192.168.176.1)
;; WHEN: Sat Dec 11 02:04:57 CET 2021
;; MSG SIZE  rcvd: 69

root@Pi-hole-RPi4:~# dig @192.168.178.1 -p 23553 bernd-sat.filmfreunde

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @192.168.178.1 -p 23553 bernd-sat.filmfreunde
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54961
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;bernd-sat.filmfreunde.         IN      A

;; ANSWER SECTION:
bernd-sat.filmfreunde.  3600    IN      A       192.168.178.10

;; Query time: 17 msec
;; SERVER: 192.168.178.1#23553(192.168.178.1)
;; WHEN: Sat Dec 11 02:05:13 CET 2021
;; MSG SIZE  rcvd: 66

please help me

**Comment by yubiuser** [comment]
Please use https://discourse.pi-hole.net/ for this kind of configuration issues and provide a debug token there.

**Comment by WiredLife** [comment]
the bug is already described at https://discourse.pi-hole.net/t/latest-update-ftl-v5-9-web-v5-6-and-core-v5-4-breakes-some-conditional-forwarding-fixed/49615

please fix this annoying bug!
