### ISSUE TITLE
Gravity can exit before database clean up processes are handled.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#4466]
### Expected behavior

Gravity should not leave the database permissions and ownership in an undetermined state.

### Actual behavior / bug

Gravity checks for DNS resolution capability before attempting to download any lists:

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/gravity.sh#L896

That called function has an `exit 1` instruction if DNS resolution is not available:

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/gravity.sh#L333-L334

By exiting from inside the function, gravity skips the database clean up steps at:

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/gravity.sh#L909-L910

The end result is that the database can potentially be owned by `root` in some situations, like a docker installation.

### Fixes

Remove the `exit 1` call from inside the function as no function should call `exit`. Replace with `return` non-zero and have line 896 set as something like:

```
gravity_CheckDNSResolutionAvailable || DO CLEANUP `chmod` and `chown` code && exit 1
```

Thanks for @lightswitch05 for the heads up on this. 

@DL6ER and @PromoFaux, do we only need to run the `chmod` and `chown` commands to make sure that the database is in a state to be used?

**Comment by dschaper** [comment]
https://github.com/pi-hole/docker-pi-hole/issues/860

**Comment by yubiuser** [comment]
The relevant PR has been released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
