### ISSUE TITLE
Make the auto theme default

### ISSUE THREAD

**Issue by WorlockM** [pi-hole/pi-hole#4467]
At this moment the light theme is the default. This doesn't feel logic to me. I think auto theme should be the default. Then most people get the setting that they want, and if they want to change it, they can.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
