### ISSUE TITLE
Strange naming 

### ISSUE THREAD

**Issue by Decapitater** [pi-hole/pi-hole#4470]
### Versions

- Pi-hole:  latest
- AdminLTE:  latest
- FTL:  latest

### Platform

- OS and version:  Debian Bullseye 

- Platform:  rpi 3b+

### Expected behavior
Readable ip addrs ? 
To be clear my home ip = 89.10.0.0/24
### Actual behavior / bug
three digino.89.10.nextgental.com instead of clear device names

_A clear and concise description of what the bug is._

### Steps to reproduce

Idk 

## Debug Token

- URL:  https://tricorder.pi-hole.net/10Hn5G1J

### Screenshots
Would add 
_If applicable, add screenshots to help explain your problem._

### Additional context
Help @yubiuser 
_Add any other context about the problem here._

**Comment by yubiuser** [comment]
I don't understand your issue. 
Please not, that ` 89.10.0.0/24` is not a private non-routable  IP range. https://www.wikiwand.com/en/Private_network#/Private_IPv4_addresses

You should switch to one of the three ranges above.

**Comment by Decapitater** [comment]
Oh well I was shocked ,

**Comment by Decapitater** [comment]
Will it affect my network if I don't use private ip (just for knowledge) @yubiuser

**Comment by yubiuser** [comment]
There might be strange side effects if you use non-private addresses.

Best place to ask such questions is https://discourse.pi-hole.net/ where you can also ask all type of configuration questions and people are usually very helpful.
