### ISSUE TITLE
local FTL won't start/stop if Pi-hole-docker is running

### ISSUE THREAD

**Issue by viglianesed** [pi-hole/pi-hole#4471]
### Versions

- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform

- OS and version:  Debian 10

- Platform:  Server & Docker

### Expected behavior

pihole-FTL.service should start/stop

### Actual behavior / bug

In the edge case where Pi-hole is installed on the server, and the server is running 1+ instances of Pi-hole-docker, the pihole-FTL.service wont start/stop

### Steps to reproduce

1. Install Pi-hole
2. Spin up a Pi-hole docker instance
3. Run `service pihole-FTL stop`
4. Run `service pihole-FTL status`
```
Dec 17 11:09:53 server systemd[1]: Stopping LSB: pihole-FTL daemon...
Dec 17 11:09:59 server pihole-FTL[5317]: .....
Dec 17 11:09:59 server pihole-FTL[5317]: Not stopped; may still be shutting down or shutdown may have failed, killing now
Dec 17 11:09:59 server systemd[1]: pihole-FTL.service: Control process exited, code=exited, status=1/FAILURE
Dec 17 11:09:59 server systemd[1]: pihole-FTL.service: Failed with result 'exit-code'.
Dec 17 11:09:59 server systemd[1]: Stopped LSB: pihole-FTL daemon.
```

### Additional context

I understand this case is unlikely to happen to most people. 
I'm low on space and money for hardware so I run multiple instances of Pi-hole on a single server.
Each instance is routed via a different VPN server in order to provide correct DNS responses to the clients going through that country.

I've tried to troubleshoot it by adding `DEBUG_ALL=true` to `/etc/pihole/pihole-FTL.conf` but the log file was never updated as the service would not start.

I initially fixed it by stopping the docker instances and then restart the local Pi-hole service.

The pihole-FTL service running inside the docker instance runs under the `root` user whilst the local service runs under the `pihole` user.

I fixed the my issue by modifying `/etc/init.d/pihole-FTL`
```
# Original function
is_running() {
  pgrep -xo "pihole-FTL" > /dev/null
}
# Modification
is_running() {
  pgrep -u pihole -xo "pihole-FTL" > /dev/null
}
```

so if I run `systemctl start pihole-FTL.service` the service starts without issues, but it won't work if I run `pihole restartdns`
Is it an issue where the command `service` is not in sync with `systemctl`?

**Comment by DL6ER** [comment]
I transferred the issue as this is the repo the `init.d` script lives in.

This is indeed a very interesting edge-case and you may even be the first one trying this. I'd have expected several docker containers without a natively installed instance in such a scenario. However, I see that this might have grow somewhat organically, as in the native installation was already there and the docker was added later.

How do you manage the port conflict for port 53 in your case? I guess are are binding the container port to an alias interface instead?

The change you are suggesting seems okay, however, it again highlights that `init.d` on modern systems is fragile. Pinging @MichaIng here (for no specific reason ;-). A better change may be, however, to use the `pid` file FTL creates, instead, as the container will see the PID file that lives inside the container whereas the native installation will see the "real" one on disk. Does anyone here recall why we are not using the PID file?

**Comment by viglianesed** [comment]
Regarding the port 53 conflict, I'm not binding the port to any of my server's nic and I run the `docker` daemon without `iptables` support, so I manually manage my own firewall rules via `nftables`.
All docker instances are running with `docker-compose` and have their own IP address that can be reached by my LAN devices, this also allows me to manually route pihole's request to a specific VPN client running on the server. So in my setup I run 5/6 instances of pihole:
1. Local install on the server (that I plan to decommission)
2. No VPN
3. UK
4. IT
5. DE
6. FR

It's a bit overkill, but it works and it's very stable.

I totally forgot about `/run/pihole-FTL.pid`, also what I proposed won't work well with the docker version, as it runs as `root` by default

**Comment by MichaIng** [comment]
> Pinging @MichaIng here (for no specific reason ;-).

Bear with me, I'll find time to implement the systemd unit soon 😉.

I also recognised this, though haven't thought about host+container instance in parallel, and "pihole-FTL" otherwise is unique enough to not touch the way of detecting and killing the process by this name. Of course it makes sense to use the PID file for those two tasks when it's there, though there was at least the idea to remove it completely (at least by default) since it is only used in one place currently. But I do not see another way to do without PID file with the init.d service, which the systemd service will be able to.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.11

**Comment by DL6ER** [comment]
@MichaIng 

> Bear with me, I'll find time to implement the systemd unit soon :wink:.

Just as a friendly reminder :slightly_smiling_face:
