### ISSUE TITLE
Ubuntu pinhole update 

### ISSUE THREAD

**Issue by mtoczycki** [pi-hole/pi-hole#4472]
I ran `sudo pihole -up` It went through with the update, but when I rebooted my raspberry pi running Ubuntu server 20.04 I ran `sudo pihole -up` Again and it tried to update again.  The version listed on the pinhole admin portal is 5.6 so it did the update but pinhole dose not recognize that it is already up to date.

**Comment by jfb-pihole** [comment]
https://discourse.pi-hole.net/t/pihole-updates-to-the-same-version/51671
