### ISSUE TITLE
pihole -up > do update Core from 5.6 to 5.6 (loop)

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#4474]
### Versions

- Pi-hole:  5.6
- AdminLTE:  5.8
- FTL:  5.11

### Platform

- OS and version:  Raspbian OS 11

- Platform:  Raspberry Pi 3 MB +

### Expected behavior
pihole -up 
shows everything up-to-date

### Actual behavior / bug

pihole -up update Core to 5.6 again and again...

### Steps to reproduce

run pihole -up

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/issues/4472
