### ISSUE TITLE
Missing network interface

### ISSUE THREAD

**Issue by myevit** [pi-hole/pi-hole#4477]
### Versions

  Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)
### Platform
Kubernetes on TrueNAS Scale

### Expected behavior

Showing all available interfaces eth0 and net1

### Actual behavior / bug

Showing only one eth0 (kubernetes internal) interface

But still working correctly if pihole is listening on all interfaces. The Issue is I don't want to resolve internal kubernetes requests on eth0. Need to listen only external net1

## Debug Token

- URL:  
https://tricorder.pi-hole.net/9YaYVeus/
<img width="488" alt="Screen Shot 2021-12-19 at 11 07 03 AM" src="https://user-images.githubusercontent.com/13375246/146685823-1160f003-4b4c-442b-befc-abad77169391.png">

<img width="696" alt="Screen Shot 2021-12-19 at 11 07 17 AM" src="https://user-images.githubusercontent.com/13375246/146685827-8d86e2da-074d-4010-a608-f1cb2bbb9783.png">

**Comment by dschaper** [comment]
Is Pi-hole running in a container? If so, what are the interfaces inside the container that `pihole-FTL` would be able to see?

**Comment by myevit** [comment]
yes it's in the container. Pihole GUI sees only eth0 (see screenshots) but diagnostic showing all interfaces eth0 and net1 and in fact resolving on both when set to do so

**Comment by dschaper** [comment]
Can you try setting the envvar for the required interface in the chart?

https://github.com/pi-hole/docker-pi-hole#advanced-variables

**Comment by myevit** [comment]
Thanks! This way I am able to override the eth0 interface with net1.
