### ISSUE TITLE
Pi-hole Core:	update available

### ISSUE THREAD

**Issue by ashr123** [pi-hole/pi-hole#4481]
### Versions

- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform

- OS and version:  Ubuntu 21.10

- Platform:  Raspberry Pi

### Expected behavior

When executing `pihole -up` twice, at the second time it will say that it's up-to-date

### Actual behavior / bug

When executing `pihole -up` twice, every time it tries to update `Pi-hole Core`

### Steps to reproduce

1. execute `pihole -up` once
2. execute `pihole -up` once more

## Debug Token

- URL:  https://tricorder.pi-hole.net/aLLmiSqH/

### Screenshots

![image](https://user-images.githubusercontent.com/26481657/147154838-ed216c9b-bc20-442e-a25e-040c401af3d6.png)
![image](https://user-images.githubusercontent.com/26481657/147154946-f6ba397f-8dc0-4ed4-8182-55bea6c28ad1.png)

### Additional context

None

**Comment by PromoFaux** [comment]
See here : https://discourse.pi-hole.net/t/pihole-updates-to-the-same-version/51671

And try once more, we've just pushed a new update in the last 1/2 hour or so that also contains a fix that stops this happening in future

**Comment by dschaper** [comment]
#4474
