### ISSUE TITLE
comments in /etc/pihole/pihole-FTL.conf not completely ignored by PHP

### ISSUE THREAD

**Issue by QuantumLibet** [pi-hole/pi-hole#4484]
### Versions
- Pi-hole:  v5.7
- AdminLTE:  v5.12
- FTL:  v5.9
- lighttpd:  v1.4.53
- php:  v7.3.31

### Platform
- OS and version:  Raspbian 10
- Platform:  Raspberry Pi (B+) local installation

### Expected behavior

Added a line starting with '#' as comment to /etc/pihole/pihole-FTL.conf. Expected comment to be ignored.

### Actual behavior / bug

When opening the Pi-hole GUI > Settings, a red error bar is displayed with the following text:

```
There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected '(' in /etc/pihole/pihole-FTL.conf on line 34 in /var/www/html/admin/scripts/pi-hole/php/FTL.php:23
```

The log shows the error as well:

```
(mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  syntax error, unexpected '(' in /etc/pihole/pihole-FTL.conf on line 33
(mod_fastcgi.c.421) FastCGI-stderr:  in /var/www/html/admin/scripts/pi-hole/php/FTL.php on line 23
```

This only happens with comments that use a round bracket '(' as part of the text. As in '`# (a) this is a comment`'.
There might be more offending characters; I just came across this one.

### Steps to reproduce

1. `echo "#(" | sudo tee -a /etc/pihole/pihole-FTL.conf`
2. reload Pi-hole GUI > Settings

### Additional context

Workaround is simple: don't use round brackets.
Why do I even post an issue, if this is so easily worked around? Because there could be other side effects of not ignoring comments completely, and maybe nobody is aware of this issue.

That said: I am not a developer. Just an end user. Maybe comments are not allowed in /etc/pihole/pihole-FTL.conf at all, but I haven't found anything that says so and all other comments are ignored as expected.

**Comment by jfb-pihole** [comment]
What is the complete output of the following:

`cat /etc/pihole/pihole-FTL.conf`

**Comment by QuantumLibet** [comment]
`cat /etc/pihole/pihole-FTL.conf` (with the error in the comment)

```
#  Source:  https://docs.pi-hole.net/ftldns/configfile/


#  DNS SETTINGS
#
#  when the gravity.db is locked/busy, drop queries
#  default: ALLOW
REPLY_WHEN_BUSY=DROP
#
#  disable Mozilla Firefox DNS-over-HTTP
#  default: true
MOZILLA_CANARY=true
#
#  disable Apple iCloud Private Relay
#  default: true
BLOCK_ICLOUD_PR=true


#  STATISTICS SETTINGS
#
#  detail level of statistics
PRIVACYLEVEL=0


#  OTHER SETTINGS
#
#  Answer to local queries with
#  default: PI.HOLE
PIHOLE_PTR=HOSTNAME
#
#  Interface listening behaviour
SOCKET_LISTENING=localonly
#
#  check if the 15 minute system load average exceeds the number of cores (top: load average: now, 5min, 15min)
#  this will be triggered frequently on a RPi, eg whenever the gravity list is updated -> useless
CHECK_LOAD=false



#  FTL SETTINGS
#
#  How often to store queries in FTLs db
#  default: 1.0
DBINTERVAL=10.0
```

🎄Merry Christmas🎄 (if you are celebrating this)

**Comment by yubiuser** [comment]
Please see those two discussions about comments in `pihole-FTL.conf`

https://github.com/pi-hole/pi-hole/issues/4444#issuecomment-982510612

https://github.com/pi-hole/pi-hole/pull/4081

**Comment by QuantumLibet** [comment]
Using `#;` as comment prefix/indicator fixes the problem. Thank you!
