### ISSUE TITLE
Curl/Bash install script not working on brand new raspberry pi running fresh raspbian install

### ISSUE THREAD

**Issue by deadpahn** [pi-hole/pi-hole#4486]
Doesn't seem to be working. It's an Raspberry Pi 3 b+ running the latest image of Raspbian (clean/headless install) installed via the Raspberry Pi utility from their site.

` [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.25

  [✓] Checking apt-get for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] Checking for / installing Required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] SELinux not detected

  [i] IPv4 address: 192.168.0.179/24
  [i] Unable to find IPv6 ULA/GUA address
  [i] IPv6 address:
  [i] Using upstream DNS: Google (ECS, DNSSEC) (8.8.8.8, 8.8.4.4)
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...HEAD is now at 1b809e4 Merge pull request #4480 from pi-hole/development
  [✓] Update repo in /etc/.pihole

  [✗] Check for existing repository in /var/www/html/admin
  [i] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin...
  Error: Could not update local repository. Contact support.
`

**Comment by dschaper** [comment]
Are there any files in `/var/www/html/admin`?

**Comment by deadpahn** [comment]
Tried this weekend. Seems to be working fine.

**Comment by yubiuser** [comment]
Thanks for letting us know.
