### ISSUE TITLE
Pi-hole backup creation is not working correctly

### ISSUE THREAD

**Issue by DHYTFG** [pi-hole/pi-hole#4497]
### Versions

- Pi-hole version is v5.7
- AdminLTE version is v5.9
- FTL version is v5.12.1

### Platform

- OS and version: Debian 11

- Platform: VPS

### Expected behavior

Creating a full backup of pi-hole settings

### Actual behavior / bug

Only a few bytes are unloaded from the server

### Steps to reproduce

1. Go to 'the pi hole admin panel'
2. Click on 'Settings'
3. Scroll down to 'Teleporter'

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

When I try to make a backup of pi hole, I see that the copy file is about 18 kilobytes in size, but only a few bytes are loaded

**Comment by yubiuser** [comment]
> See error

What error do you see?

**Comment by DHYTFG** [comment]
This is more likely not a error, but simply an incorrect operation of something. I don't see any warnings or anything like that. It's just that only a few kilobytes of backup are downloaded to the computer.

**Comment by yubiuser** [comment]
Please upload a debug log and post **just the  token URL** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
```
pihole -d
```
or do it through the Web interface:

***Tools > Generate Debug Log***

**Comment by DHYTFG** [comment]
Thanks. I experimentally realized that it depends on the browser. I tried to make a backup with Firefox and nothing worked. When I tried to do the same thing through chrome, it all worked
