### ISSUE TITLE
Pi-Hole admin login page redirects to the 'not logged in' homepage

### ISSUE THREAD

**Issue by dakupurple** [pi-hole/pi-hole#4502]
My Pi-hole instance running on Debian 11 no longer has a web interface that is properly working. I can go to http://pi.hole/admin/ on my local network, the name in the top right is as expected. I click on 'Login' and enter the admin password, and it redirects me to http://pi.hole/admin/index.php but not actually logged in. I cannot currently access anything via the web interface that requires logging in. 

I've tried setting up a new VM, and a fresh install of Debian 11, using the one step automated install. This behavior persists on a fresh install of everything. 

Current Behavior: Logging in to the web admin interface redirects to the web interface, not logged in. 

Expected Behavior: Logging in to the web admin interface redirects to the full admin web interface. 

Debug token:[https://tricorder.pi-hole.net/Rrd460F0](https://tricorder.pi-hole.net/Rrd460F0)

**Comment by dschaper** [comment]
Does this happen with all browsers? Are you blocking cookies in the browser?

**Comment by dakupurple** [comment]
My bad, I thought I didn't end up posting this, it was a browser configuration error. No clue what (had tried clearing cache/cookies and cookies were not being blocked), told the browser to reset to defaults, and set it back up the way I use it, and everything works correctly. 

Appreciate the follow up on this.
