### ISSUE TITLE
Manual domain blacklist only applies to "Default" group

### ISSUE THREAD

**Issue by InfoSecJack** [pi-hole/pi-hole#4503]
### Versions
- Pi-hole:  v5.7
- AdminLTE:  v5.9
- FTL:  v5.12.1

### Platform
- OS and version:  `Linux raspberrypi 5.10.63-v7l+ #1459`
- Platform:  Raspberry Pi 4 2GB

### Expected behavior

When manually adding domains to the blacklist the blocking should occur to all groups, or should open up the choice to be applied to a selection of client groups.

### Actual behavior / bug

The domain block (regex or otherwise) is only added to the "Default" group, and therefore doesn't apply to clients that are not in that group, even though every option under "Adlists" is set to the selected group that isn't blocked currently.

### Steps to reproduce

1. Go to 'blacklist management'
2. Add a new domain to be blocked
3. Do a query from a device outside of the "Default" group
4. See that the domain is still resolving.

### Additional context

This may just be an issue of naming, where I've assumed that something should work in a way that it clearly doesn't, however the current systems are confusing and the choice to select groups for a given blacklist entry would be appreciated.

**Comment by yubiuser** [comment]
Use "Group management/Domains" to add black/whitelisted domains. From there you can directly change the group assignment after you added the domain.
The "Blacklist management" page will be removed at a certain point. It was meant as a transition from pre v5.0. for users that don't need the group management functionality.

**Comment by InfoSecJack** [comment]
Ah gotcha, thank you!
