### ISSUE TITLE
no ipv6 internet access when pi-hole is the router caused by ra-param=*,0,0

### ISSUE THREAD

**Issue by Omoeba** [pi-hole/pi-hole#4505]
### Versions

- Pi-hole:  v5.7
- AdminLTE:  v5.9
- FTL:  v5.12.1

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi 4

### Expected behavior

clients have access to the internet over ipv6

### Actual behavior / bug

clients do not have internet access

### Steps to reproduce

1. Check `Enable IPv6 support (SLAAC + RA)`

## Debug Token

- URL:  https://tricorder.pi-hole.net/zoO4Fa20/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

The problem is caused by `ra-param=*,0,0` in `/etc/dnsmasq.d/02-pihole-dhcp.conf`, which prevents the router from advertising a route. Due to not advertising a route, clients on the subnet have no internet access. `ra-param=*,0,0` appears to be intended behavior to prevent pi-hole from advertising itself as the router when there is already a router present. However, it makes ipv6 completely unusable when pi-hole itself is the router.

**Comment by spcharc** [comment]
Ah, this should be the reason why my ipv6 isn't working. I tried to remove this option and my ipv6 works. (I'm using static ULA address for pihole + ipv6 NAT, pihole is the router)

**Comment by spcharc** [comment]
It is interesting my browser is using IPv4 by default if a domain names has both A and AAAA records, and if connection to that IPv4 failed it won't even try IPv6.
Perhaps it has something to do with ULA addresses.
However IPv6 only domains (like `ipv6.google.com`) works normally

**Comment by Omoeba** [comment]
> It is interesting my browser is using IPv4 by default if a domain names has both A and AAAA records, and if connection to that IPv4 failed it won't even try IPv6. Perhaps it has something to do with ULA addresses. However IPv6 only domains (like `ipv6.google.com`) works normally

Try restarting the network interface on the computer you're running the browser on.

**Comment by spcharc** [comment]
> Try restarting the network interface on the computer you're running the browser on.
Tried that several times on multiple devices.

**Comment by spcharc** [comment]
> Try restarting the network interface on the computer you're running the browser on.

I am sorry. It seems IPv6 fallback did work. Even though Windows is reporting no IPv6 connection, browser do fall back to IPv6 when IPv4 address isn't accessible.

**Comment by dschaper** [comment]
@DL6ER

**Comment by DL6ER** [comment]
The "Enabled IPv6 support" checkbox on the web interface was carefully designed to work in all *typical* setups. Getting a configuration that works equally well with Android, Linux, iOS, Mac and Windows was not an easy task. This cannot take into account the situation where Pi-hole is the router, sorry.

The solution for you will be to untick the checkbox and create a custom file inside `/etc/dnsmasq.d` where you only out those config lines you need to get your particular system running. Doing it like this is not adverse in any way, it instead gives you full control over it.
