### ISSUE TITLE
Install Script ends with error "Unable to create database"

### ISSUE THREAD

**Issue by sNNNeaker** [pi-hole/pi-hole#4506]
Hi @all, happy new year!

Unfortunally I can't install Pi-Hole. Please help :)

### Versions
  Pi-hole version is v5.7 (Latest: v5.7)
  AdminLTE version is v5.9 (Latest: v5.9)
  FTL version is v5.12.1 (Latest: v5.12.1)

### Platform
- OS and version:  Raspbian GNU/Linux 11 (bullseye)
- Platform:  Raspberry Pi 3B

### Expected behavior

Run the Installscript to install Pi-Hole: curl -sSL https://install.pi-hole.net | bash

### Actual behavior / bug

Error:
  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity.db_temp
  Error: no such table: main.gravity
   [✗] Unable to create database. Please contact support.

### Steps to reproduce

1. run curl -sSL https://install.pi-hole.net | bash
2. See error

-or-

1. run pihole -r
2. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/4Xeiihg1/

**Comment by yubiuser** [comment]
Did you select an adlist during installation?

**Comment by sNNNeaker** [comment]
> Did you select an adlist during installation?

No I did not. Installed without any lists at first.

**Comment by sNNNeaker** [comment]
I get the same error with 'pihole -up' on my primary pihole running on Ubuntu 20.04 LTS in a VM.

**Comment by yubiuser** [comment]
> No I did not. Installed without any lists at first.

That's the reason it fails. Nobody thought about users not wanting any adlist :-)

See the discussion here:
https://discourse.pi-hole.net/t/upgrade-to-ftl-5-12-1-does-not-create-database/51846

I'll see if I can write a fix

**Comment by sNNNeaker** [comment]
Makes sense.

I've selected the one list using 'pihole -r', still fails tho. Uninstalling pihole and reinstalling it works. Thanks for the quick help!

Hopefully it will get fixed in a future version or a warning that the database cant be created without a list.

**Comment by yubiuser** [comment]
I'll leave the issue open until we have a fix for this.

**Comment by yubiuser** [comment]
Fixed by: https://github.com/pi-hole/pi-hole/pull/4535

**Comment by CarlSargunar** [comment]
This is an awesome fix - thanks for this, I just ran into exactly the same issue. 

Is it worth me running this from the development branch so I can get pi hole installed by changing the branch, or is it better to wait until this is released to live?

Thanks again

**Comment by yubiuser** [comment]
> Is it worth me running this from the development branch so I can get pi hole installed by changing the branch, or is it better to wait until this is released to live?

Depends on how urgent you need the fix. I probably would do the following: 
Install Pi-hole normally and add the one provided adlist. Then create a new group and assign the adlist **only to this group**. This way, there should be no blocking for default (unconfigured) clients but gravity still got something to do and the issue should be worked around.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
