### ISSUE TITLE
loading whitelist.txt and regex.list at boot does not work

### ISSUE THREAD

**Issue by oscni** [pi-hole/pi-hole#4511]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5.1
- FTL:  v5.8.1

### Platform

- OS and version:  Ubuntu

- Platform:  Kubernets/Docker

### Expected behavior

Load blacklist and whitelist at boot time.
Running the following commands afterwords adds the items correctly which indicates that the files are correct.
cat /etc/pihole/whitelist.txt | xargs pihole -w
cat /etc/pihole/regex.list | xargs pihole --regex

### Actual behavior / bug

Previous versions loaded the whitelist and blacklist automatically at boot. It does not seem to work any more. Or if behavior has changed i'm not finding it in the docs.

### Steps to reproduce

1. Create regex.list and whitelist.txt
2. Run new pihole docker container

**Comment by yubiuser** [comment]
Those files aren't used since two years (release of v5). We switched to a database containing all the domains.

https://docs.pi-hole.net/database/gravity/

If you need additional help, please visit https://discourse.pi-hole.net/

**Comment by oscni** [comment]
Ok thanks, guessed that was the reason. Just a little bit hard to find info about that. I created a feature request instead. Keep up the good work!

https://discourse.pi-hole.net/t/automatic-loading-of-whitelisting-and-blacklisting-files-at-boot/52236

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/pi-hole-v5-0-is-here/31843
