### ISSUE TITLE
Domain ... is not a valid domain because it contains invalid characters. Added 0 out of 1 domains

### ISSUE THREAD

**Issue by zangaby** [pi-hole/pi-hole#4512]
### Versions

Pi-hole version is v5.7 (Latest: v5.7)
AdminLTE version is v5.9 (Latest: v5.9)
FTL version is v5.12.1 (Latest: v5.12.1)

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi

### Expected behavior

Block a domain that generates a high amount of queries.

### Actual behavior / bug

Unable to block the domain because it contains invalid characters.

### Steps to reproduce

1. Go to 'Admin page'
2. Click on 'Query log'
3. Scroll down to 'the query that you need to block'

## Debug Token

- URL:  https://tricorder.pi-hole.net/cyFOKCY7/

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/5586164/148093635-c7dd9e29-bb4c-4a1a-9efe-21f96f1c18e3.png)

![image](https://user-images.githubusercontent.com/5586164/148093705-0a082469-9c3b-4568-bd1a-78bdc663ff6e.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
This is not a valid domain and will return `NXDOMAIN` in any case. Because it's not a valid domain you can't add it to the blacklist.

What client or application is generating this requests? It looks very strange...

**Comment by zangaby** [comment]
Looking in /admin/api.php?getAllQueries&client= I see a lot of  \u009c!\u00fc?
This seems to be associated to several domain queries. 

Please find below few examples:
`["1644074590","A","static.getbutton.io","fritz.box","2","2","4","132","N\/A","-1","localhost#5335",""],["1644074593","A","\u009c!\u00fc?","fritz.box","3","2","2","0","N\/A","-1","N\/A#0",""],
["1644074209","A","\u009c!\u00fc?","fritz.box","3","2","2","1","N\/A","-1","N\/A#0",""],["1644074217","A","de.pool.ntp.org","fritz.box","2","2","4","1742","N\/A","-1","localhost#5335",""],
["1644074545","A","\u009c!\u00fc?","fritz.box","3","2","2","1","N\/A","-1","N\/A#0",""],["1644074546","A","optimizationguide-pa.googleapis.com","fritz.box","2","2","4","308","N\/A","-1","localhost#5335",""],
["1644074590","A","static.getbutton.io","fritz.box","2","2","4","132","N\/A","-1","localhost#5335",""],["1644074593","A","\u009c!\u00fc?","fritz.box","3","2","2","0","N\/A","-1","N\/A#0",""],
`

**Comment by yubiuser** [comment]
It's strange that your Fritz.Box is sending those queries. I rather guess, your configured your FB as DNS server for your network and P-hole as the upstream DNS server of the FB. You need to figure out, which client/application is sending those strange queries.

**Comment by dschaper** [comment]
Those are unicode glyphs. This is an example of one of them.

https://www.fileformat.info/info/unicode/char/009c/index.htm

**Comment by zangaby** [comment]
I reconfigured my router to have the Pi-hole address set as DNS from the DHCP server instead being set as upstream DNS, to hopefully track down the client that triggers these queries.

**Comment by zangaby** [comment]
Update: the issue was cleared after the reconfiguration.
