### ISSUE TITLE
Domanins on blocklist .... -2

### ISSUE THREAD

**Issue by Z80user** [pi-hole/pi-hole#4519]
### Versions
- Pi-hole:  5.7
- AdminLTE:  5.9 (Web interface)
- FTL:  5.12.1

### Platform
- OS and version:  Raspbian lite 5.10.63+ (version just download yesterday)
- Platform:  Raspberry Pi 1B 512MB (RAM 496MB / VRAM 16MB)

### Expected behavior

The number on Domains on blocklist = ¿ maybe 0 ?

### Actual behavior / bug

The number on Domains on blocklist = -2

### Steps to reproduce

"etoro.com" manually add to blacklist
"doubleclick.net" manually add to blacklist
"ad-delivery.net" " manually add to blacklist
"blancoshrimp.com" manually add to blacklist

"(\.|^)steamcommunity\.com$" manually add to blacklist with the checkbox add domain as wildcard activated

## Debug Token

token is: https://tricorder.pi-hole.net/9hsYPPej/

### Screenshots

I put a picture on rededit and someone say me to send that info here too
https://www.reddit.com/r/pihole/comments/rwjb8q/domanins_on_blocklist_2/

### Additional context

apart from the basic installation of  Raspbian... apt update & apt upgrade, configure the system and some more basic stuff this are the list of things installed with "sudo apt install"

(by the way I don't think anything of that can interfere with pi-Hole)
php-gd php-mbstring php-cgi php-common php-sqlite3 php-mysql php-apcu php-intl php-cgi php-gd php-mbstring imagemagick inkscape texlive git
unbound mariadb-server mariadb-client php-mysql php-sqlite3

I follow the steps from that video https://www.youtube.com/watch?v=FnFtWsZ8IP0 ... so a basic installation of pi-Hole than add unbound as the recursive DNS but skip the step than add the StevenBlackList to start with a empty database and log everything

during the installation a message  say me to write something
 sudo curl -sSL https://install.pi-hole.net | bash
   36  pihole -g -r
   37  pihole -g -r recover
   38  pihole -g -r recreate
   39  pihole -g -r
   40  pihole -g -r recreate
this are the lines I try to fix that messages, I get it from the history command
I can made a backup of the microSD of the Respberry Pi in a reduced size (raw size without compression 3.834.944 KB)and I will do it and keep it as is now just in case will be useful to check it later as is now

**Comment by yubiuser** [comment]
You only have one adlist and you disabled that

```
*** [ DIAGNOSING ]: Adlists
   id     enabled  group_ids     address                                                                                                                          date_added           date_modified        comment                                           
   -----  -------  ------------  -------------------------------------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   1         0     0             https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt  2021-12-29 22:02:16  2021-12-29 22:02:41  Antimalware          
```

Enable the adlist and run `pihole -g`

**Comment by Z80user** [comment]
If I add something to "Group management -> Adlist" look like it work again with the correct number of things added. And no more errors.

If I delete everything and clear all of the config the -2 appear again with the same message as before

The gravity.db file is 94208 bytes when I clear it, so it's create with 9 things added is 98304 bytes with this list
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts

-------------------------
If I clear everything I still getting the -2
without anything to add the output of "pihole -g" show that also "pihole -g -f" but bot reacreate a empty file

  [i] Creating new gravity database
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity.db_temp
  Error: no such table: main.gravity
   [✗] Unable to create database. Please contact support.

So look like with a empty database instead 0 the number is -2, a guy on rededit say me that maybe because wrong owners of the files or anything else but that isn't the case and least on the way I check it "sudo own pihole:pihole " to some files and I still getting the same result (-2)

**Comment by yubiuser** [comment]
The `-2` is a bug, it should state `0`

**Comment by yubiuser** [comment]
Please run

`echo ">stats >quit" |nc 127.0.0.1 4711`

and report the output.

**Comment by Z80user** [comment]
domains_being_blocked -2
dns_queries_today 8231
ads_blocked_today 0
ads_percentage_today 0.000000
unique_domains 235
queries_forwarded 2827
queries_cached 5402
clients_ever_seen 3
unique_clients 3
dns_queries_all_types 8231
reply_NODATA 5535
reply_NXDOMAIN 14
reply_CNAME 659
reply_IP 2018
privacy_level 0
status enabled

**Comment by yubiuser** [comment]
Thanks. Please another one:

`sqlite3 /etc/pihole/gravity.db "SELECT value FROM info WHERE property = 'gravity_count';"`

**Comment by Z80user** [comment]
nothing show but with something more general as -> sqlite3 /etc/pihole/gravity.db "SELECT * FROM info;"
version|15

if I add the gravity file of before with 9 lines show "9" so look as and all on info as before  "SELECT * FROM info;"
version|15
updated|1641508183
gravity_count|9

**Comment by yubiuser** [comment]
Thanks this should give enough information to fix this.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
