### ISSUE TITLE
Missing Temp Sensor information is showing when used to be hidden when running as a VM

### ISSUE THREAD

**Issue by hansenc0705** [pi-hole/pi-hole#4526]
### Versions

  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version:  CentOS Stream release 8

- Platform:  vSphere VM

### Expected behavior

After latest update the dashboard shows "No temp sensor found". Prior to this update the temp sensor was hidden since running as a VM.

### Actual behavior / bug

Would expect temp sensor to be hidden

### Steps to reproduce

1. Go to dashboard and look at stats with pihole running as a VM.

## Debug Token

- URL:  https://tricorder.pi-hole.net/LN7k2CIX/

### Screenshots

![image](https://user-images.githubusercontent.com/10247644/148429262-d2ae8b83-d453-410e-976d-c9984902e835.png)

### Additional context

n/a

**Comment by yubiuser** [comment]
This is not a bug. We changed the behavior.

**Comment by hansenc0705** [comment]
> This is not a bug. We changed the behavior.

okay sounds good.

**Comment by yubiuser** [comment]
We might restore the old behavior: 
https://github.com/pi-hole/AdminLTE/pull/2054
