### ISSUE TITLE
IPv6 still shows up in Network Overview

### ISSUE THREAD

**Issue by root9191** [pi-hole/pi-hole#4528]
### Versions

- Pi-hole version is v5.8.1 (Latest: v5.8.1)
- AdminLTE version is v5.10.1 (Latest: v5.10.1)
- FTL version is v5.13 (Latest: v5.13)
  
### Platform

- OS and version:  Debian Bullseye 11.2

- Platform:  Raspberry Pi 4 4GB

### Expected behavior

No Service working on IPv6.

### Actual behavior / bug

IPv6 is deactivated on the whole Raspberry, but the Webserver and the DNS Service for pi-hole are working also on IPv6, like in the Screenshots. Is there a possibility to turn it off?

### Screenshots
<a href="https://ibb.co/GVY6xt5"><img src="https://i.ibb.co/CnCc1MH/network.jpg" alt="network" border="0"></a>

<a href="https://ibb.co/YQGPP6t"><img src="https://i.ibb.co/C8Fmmqn/pihole.jpg" alt="pihole" border="0"></a>
### Additional context

This was set to disable IPv6:
/etc/modprobe.d/ipv6.conf
```
blacklist ipv6
alias net-pf-10 off
alias ipv6 off
options ipv6 disable_ipv6=1
```
/etc/pihole/pihole-FTL.conf 
```
BLOCKINGMODE=IP
MAXDBDAYS=2
#RESOLVE_IPV4
RESOLVE_IPV4=yes
RESOLVE_IPV6=no
AAAA_QUERY_ANALYSIS=no
REPLY_ADDR4=IP
SHOW_DNSSEC=true
PRIVACYLEVEL=0
```

**Comment by dschaper** [comment]
The `::` in the Network Overview is not IPv6, that's the Pi-hole process itself.

The netstat output is on the OS so we can not change any of that.

**Comment by root9191** [comment]
But on the left there stands "tcp6". Deas means  TCP over IPv6, right?

**Comment by dschaper** [comment]
Yes

**Comment by root9191** [comment]
So there is no Chance to deactivate this?

**Comment by dschaper** [comment]
It's an OS issue.
