### ISSUE TITLE
minor : script pihole - function helpFunc

### ISSUE THREAD

**Issue by Fedora-Core** [pi-hole/pi-hole#453]
##### Expected Behaviour:

echo Usage: pihole [options]
##### Actual Behaviour:

echo Usage: pihole**.sh** [options]
##### Steps to reproduce this issue:

$ pihole -h

Same for script blacklist.sh helpFunc
Same for script whitelist.sh helpFunc
Same for script chronometer.sh displayHelp

_(and whitespaces)_

Greetings, F.C.

**Comment by PromoFaux** [comment]
Fixed in `development` branch, for future release.
