### ISSUE TITLE
piHole not resolving DNS for devices on different subdomain

### ISSUE THREAD

**Issue by erbmur** [pi-hole/pi-hole#4530]
Hi All,

Happy 2022!  I have started having an issue with running piHole since I ran an update recently.
Was hoping somebody might be able to shed some light on the matter.

**Versions**
Pi-hole: v5.8.1
AdminLTE: v5.10.1
FTL: v5.13

**Platform**
OS and version: Ubuntu and Raspbian
Platform: VM Ubuntu and physical pi

**Expected behaviour**
piHole should accept connections from every subnet on the network (and used to before I ran an update)

**Actual behaviour/bug**
Different subnets no longer resolve DNS are cannot access the web.

**Additional context**
I have had piHole running on a VM on my network for quite some time without any issues.  I am running a pfSense router with different subnets for my LAN and WiFi network.  The subnets for both are 10.27.27.0 and 10.28.28.0 respectively.  The DHCP server for both where pointing to a DNS server of 10.27.27.23 (VM piHole) without any issue.  I also had a number of other subnets pointing to this as a DNS without any issue, but LAN and WiFi are the main two.
After running a recent update (can't remember what the old version was), anything not on the subnet of 10.27.27.0 can no longer access the internet.
Anything on the LAN runs fine and I can see it appearing in the logs for the piHole web UI, but the other subnets are not connecting.
I had a spare raspberry pi lying around, so setup piHole on that on the WiFi subnet, and the WiFi devices are able to connect to the internet through that.  Changing the LAN DNS to the newly created WiFi DNS pi also prevents the LAN devices from connecting to the internet.

I know I'm not very good at explaining stuff and this is probably a very convoluted to read.  Please let me know if there is anything I can do to make it clearer!

**Comment by dschaper** [comment]
Please provide the debug token url as requested in the template.

**Comment by dcrussell** [comment]
@erbmur Did you get this fixed? I had a a similar issue but fixed it after reviewing documentation [here](https://docs.pi-hole.net/ftldns/interfaces/) and making the necessary changes in Settings->DNS. Hope this helps!

**Comment by erbmur** [comment]
@dcrussell OMG!  I had that set previously, but it looks like that setting got reset when i ran `pihole -up`.  Thanks for reminding me about it!
