### ISSUE TITLE
Chrome/Safari: `Select a certificate`

### ISSUE THREAD

**Issue by igrayson** [pi-hole/pi-hole#454]
##### Expected Behaviour:
Using Chrome or Safari, load a page that includes ads, and do not encounter a `Select a certificate` dialog.

##### Actual Behaviour:
I see a `Select a certificate` dialog.

##### Steps to reproduce this issue:
0. Likely some unusual local certificate setup on my laptop. (for example, I have a client certificates installed, for work).
1. Open a Chrome privacy window (optional), or Safari
2. Visit a page with a blockable element (such as https://reddit.com, https://arstechnica.com, or https://github.com/pi-hole/pi-hole)

Chrome 49.0.2623.110:

![image](https://cloud.githubusercontent.com/assets/6943580/14412051/4d16ba1a-ff0e-11e5-89b2-ab10f4d1d4d7.png)

Safari 9.0.1 (11601.2.7.2):

![image](https://cloud.githubusercontent.com/assets/6943580/14412067/85e1ea2c-ff0e-11e5-9f13-05c44e97e982.png)

Firefox 45.0.1:

![image](https://cloud.githubusercontent.com/assets/6943580/14412078/b8fe2e34-ff0e-11e5-8a86-3853d204423d.png)

**Comment by Mcat12** [comment]
Is this still an issue? It seems that we missed looking at this one... If it's still not working after an update, can you run `pihole -d` and pastebin the log?

**Comment by Mcat12** [comment]
@igrayson Is this still happening?

**Comment by dschaper** [comment]
Final ping for @igrayson before closing out this issue.

**Comment by igrayson** [comment]
Can close; I'm not using pi-hole anymore.

**Comment by dschaper** [comment]
Sorry to hear that, if there's anything we can do to improve/change the Pi-hole please let us know and we'll take a look at it.
