### ISSUE TITLE
Linux Container adapter selection

### ISSUE THREAD

**Issue by ShoGinn** [pi-hole/pi-hole#455]
##### Expected Behaviour:
Select ethernet adapters that dnsmasq works with

##### Actual Behaviour:
Setup a linux container that is running debian/ubuntu etc and run the automated installer, it will find the link as eth0@if13 etc.

End up having to manually edit the dnsmasq file to remove the @if13 so that dnsmasq listens on the correct interface 

##### Steps to reproduce this issue:

```
root@adblock:~# ip -o -f inet address show
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
12: eth0    inet 192.168.1.10/24 brd 192.168.1.255 scope global eth0\       valid_lft forever preferred_lft forever
root@adblock:~# ip -o link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT \    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
12: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000\    link/ether 62:36:36:31:30:31 bed ff:ff:ff:ff:ff:ff
```

**Comment by ShoGinn** [comment]
FYI, this is on a proxmox LXC...

**Comment by ShoGinn** [comment]
I might not be the best at bash scripts, but:

Change:
''
availableInterfaces=$(ip -o link | awk '{print $2}' | grep -v "lo" | cut -d':' -f1)
''

to 
''
availableInterfaces=$(ip -o link | awk '{print $2}' | grep -v "lo" | cut -d':' -f1 | cut -d'@' -f1)
'' 

And that removes the problem.

**Comment by Mcat12** [comment]
@pi-hole/gravity 

If this fix works, you are welcome to put it in a fork and make a pull request. If not, we can implement it on your behalf. :)

**Comment by dschaper** [comment]
It should work, but it would be adding a case check for one specific VMS, that said however a pull request would be good on this.

**Comment by davidtorcivia** [comment]
Can confirm this fix works for a proxmox LXC. Thanks @ShoGinn and everyone else!

**Comment by ShoGinn** [comment]
I wish I understood GIT more other than my basic git clone ;) If someone else could incorporate it that would be great!

**Comment by davidtorcivia** [comment]
@ShoGinn Went ahead and added it for you. Thanks for the fix, saved me having to dig through all that bash!

**Comment by ShoGinn** [comment]
@davidtorcivia yeah I got sick of removing it in the dnsmasq conf ;)

**Comment by Mcat12** [comment]
@davidtorcivia You can resubmit your PR, just make sure it follows the [guidelines](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md)! :wink:

**Comment by dschaper** [comment]
PR Merged, Closing issue.
