### ISSUE TITLE
„Allow only local requests” options blocks request when connecting from VPN to local network

### ISSUE THREAD

**Issue by k-matti** [pi-hole/pi-hole#4551]
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.13
- FTL:  5.10.1

### Platform

- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior

Allow only local requests options should consider other network like local 

### Actual behavior / bug

When connecting using VPN to my local network my client getting different IP sygnet than pihole so this is not consider as local
## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Please add option to set which networks should be consider as local

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by yubiuser** [comment]
> --local-service
Accept DNS queries only from hosts whose address is on a local subnet, ie a subnet for which an interface exists on the server. This option only has effect if there are no --interface, --except-interface, --listen-address or --auth-server options. It is intended to be set as a default on installation, to allow unconfigured installations to be useful but also safe from being used for DNS amplification attacks.

https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

This is how the built-in `dnsmasq` handles the option.
