### ISSUE TITLE
DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#4557]
### Versions

-   Current Pi-hole version is v5.8.1
-   Current AdminLTE version is v5.10.1
-   Current FTL version is v5.13

### Platform

- OS and version: Raspberry OS 11
- Platform: Raspberry Pi

### Expected behavior

dns working on the system

### Actual behavior / bug

**DNS resolution is currently unavailable**

```
root:~/ # cat /etc/resolv.conf (Original File)
# Generated by resolvconf
nameserver fd00::2e3a:fdff:feed:c12
```

```
root:~/ # cat /etc/resolv.conf (Edit File to resolve problem)
# Generated by resolvconf
nameserver 127.0.0.1  
```

### Steps to reproduce

1. run pihole -g 
2. See error

## Debug Token

- URL: https://tricorder.pi-hole.net/ilS05TDG/

### Additional context

https://discourse.pi-hole.net/t/solved-dns-resolution-is-currently-unavailable/33725

**Comment by pheiduck** [comment]
Reboot reverts changes to Original File

**Comment by dschaper** [comment]
Yes, `resolvconf` will overwrite `resolv.conf`. That's on OS issue, nothing Pi-hole can do about it.

**Comment by pheiduck** [comment]
maybe lighttpd (1.4.59-1+deb11u1) is broken? was updating today

**Comment by dschaper** [comment]
No, nothings broken. `resolv.conf` is controlled by `resolvconf` so any manual changes you make will be overridden when you reboot or `resolvconf` is triggered.

**Comment by pheiduck** [comment]
So what is the solution for this os issue than?

**Comment by pheiduck** [comment]
maybe bad workaround I removed the config file an leave to backup files

**Comment by pheiduck** [comment]
the file was recreated an has the correct values now
