### ISSUE TITLE
Pi-hole always returning NXDOMAIN for certain hostname.

### ISSUE THREAD

**Issue by eckelhesten** [pi-hole/pi-hole#4559]
### Versions
- Pi-hole:   Pi-hole version is v5.8.1 (Latest: v5.8.1)
- AdminLTE:  AdminLTE version is v5.10.1 (Latest: v5.10.1)
- FTL:  FTL version is v5.13 (Latest: v5.13)

### Platform
- OS and version:  Raspbian OS (with 5.10 kernel)
- Platform:  Raspberry Pi 4B 4GB RAM

### Expected behavior

I'm expecting Pi-hole to send my query to my upstream DNS and answer with NOERROR and IP addresses that belong to that query. Since the hostnames are not blacklisted or cached, I expect this to run through without any stops or blocks on the way.

### Actual behavior / bug

So I'm trying to get Apple's Private Relay function to work on my phone. I found out that the domains that needs to be reached in order for it to work (**mask.icloud.com** and **mask-h2.icloud.com**) is returning an NXDOMAIN when resolving against the Pi-hole. When manually resolving against my upstream DNS, I'm getting good resolves with NOERROR and IP addresses.

I've noticed that no matter what i do, Pi-hole resolves against cache. I tried removing my blocklists, tried different upstream DNS, tried whitelisting the domains even though they are not in any blocklists, tried flushing the DNS cache a few times and still – it always resolves to the cache which it gets an NXDOMAIN response from.

I've checked Pi-hole and dnsmasq configs which are as standard and out-of-the-box as can be, and there's nothing that gives a hint of why it's resolving against the cache instead of resolving against upstream DNS.

No other domains are getting the same result (that i know of). Everything else that I query is answered by my upstream DNS or gets blocked if blacklisted, and works as intended.

### Steps to reproduce

1. Just a regular DNS lookup on the localhost:
```
admin@nebuchadnezzar:~ $ dig @127.0.0.1  mask.icloud.com

; <<>> DiG 9.16.22-Raspbian <<>> @127.0.0.1 mask.icloud.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52780
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mask.icloud.com.               IN      A

;; Query time: 9 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 13 13:48:55 CET 2022
;; MSG SIZE  rcvd: 44
```

## Debug Token

- URL:  

https://tricorder.pi-hole.net/UICuw4N8/

### Screenshots

![cache](https://user-images.githubusercontent.com/70117556/149333864-51413ab4-b739-4cd2-adc9-8e944cb2e197.png)

### Additional context

None

**Comment by dschaper** [comment]
This was covered in the release notes but it's the default behavior:

https://docs.pi-hole.net/ftldns/configfile/?h=icloud#icloud_private_relay

**Comment by eckelhesten** [comment]
That was quick. I tried googling this issue but I should've checked the release notes.

Oh well, thanks!

**Comment by swa66** [comment]
At least those logs could be made clear that it's not just a cache that's gone wrong that won;t clear up on itself, but actually intended to block this domain in this way and a pointer to how to unblock it. As it is now this is a huge time waste for new users trying to figure out why e.g. remote images in email suddenly stop loading in apple email clients.

**Comment by yubiuser** [comment]
@swa66 

I picked up your suggestion an created a new bug report for it: https://github.com/pi-hole/FTL/issues/1334
