### ISSUE TITLE
pihole -up incorrectly reporting status in Centos 7.9.2009

### ISSUE THREAD

**Issue by digitalxruin** [pi-hole/pi-hole#4565]
This has been reported by numerous users on the pi-hole subreddit. Opening a request here for visibility. First time seeing this after running and updating pi-hole for quite awhile. I have done no customizations and reproducing it is straightforward as you see below.

pihole -v
  Pi-hole version is v5.7 (Latest: v5.8.1)
  AdminLTE version is v5.9 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

 pihole -up
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which
  [✓] Checking for chkconfig
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

## Debug Token

- URL:  https://tricorder.pi-hole.net/WHI4E6FC/

**Comment by dschaper** [comment]
Yes, we're aware, hence the pinned issue.

**Comment by digitalxruin** [comment]
Apologies, I didn't see it. Thanks.
