### ISSUE TITLE
Pi-Hole on Alpine Linux

### ISSUE THREAD

**Issue by Lsm-CVX** [pi-hole/pi-hole#4567]
### Versions
proxmrs-DNS-pihole3:~/pi-hole# pihole -v
  Pi-hole version is main Untagged (Latest: v5.8.1")
  AdminLTE version is v5.10.1 (Latest: v5.10.1")
  FTL version is v5.13 (Latest: v5.13")

### Platform
proxmrs-DNS-pihole3:~/pi-hole# apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.3-79-gbc8053dfad [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.3-79-gbc8053dfad [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]

### Expected behavior

Installed using  https://gitlab.com/yvelon/pi-hole 
Working okay mainly but ... 

### Actual behavior / bug

Command stat behavior is different from Alpine to standard Linux (busibox)

### Steps to reproduce

 %T	Type in human readable form
stat: unrecognized option: format
BusyBox v1.33.1 () multi-call binary.

Usage: stat [-ltf] [-c FMT] FILE...

Display file (default) or filesystem status

	-c FMT	Use the specified format
	-f	Display filesystem status
	-L	Follow links
	-t	Terse display

FMT sequences for files:
 %a	Access rights in octal
 %A	Access rights in human readable form
 %b	Number of blocks allocated (see %B)
 %B	Size in bytes of each block reported by %b
 %d	Device number in decimal
 %D	Device number in hex
 %f	Raw mode in hex
 %F	File type
 %g	Group ID
 %G	Group name
 %h	Number of hard links
 %i	Inode number
 %n	File name
 %N	File name, with -> TARGET if symlink
 %o	I/O block size
 %s	Total size in bytes
 %t	Major device type in hex
 %T	Minor device type in hex
 %u	User ID
 %U	User name
 %x	Time of last access
 %X	Time of last access as seconds since Epoch
 %y	Time of last modification
 %Y	Time of last modification as seconds since Epoch
 %z	Time of last change
 %Z	Time of last change as seconds since Epoch

FMT sequences for file systems:
 %a	Free blocks available to non-superuser
 %b	Total data blocks
 %c	Total file nodes
 %d	Free file nodes
 %f	Free blocks
 %i	File System ID in hex
 %l	Maximum length of filenames
 %n	File name
 %s	Block size (for faster transfer)
 %S	Fundamental block size (for block counts)
 %t	Type in hex
 %T	Type in human readable form
/opt/pihole/gravity.sh: line 129: [: : integer expression expected

## Debug Token

- URL:

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.
