### ISSUE TITLE
Cannot get rid of DHCP warnings for docker interfaces

### ISSUE THREAD

**Issue by brentco** [pi-hole/pi-hole#4571]
### Versions

- Pi-hole:  v5.8.1
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi

### Expected behavior
The logs (and thus the warnings view in the dashboard) should not be spammed with these error messages.

### Actual behavior / bug

The logs get spammed with messages like this:
```
DHCP packet received on veth9ec6ab0 which has no address
```

### Steps to reproduce

1. Run Pi-Hole on Raspberry Pi
2. Have Docker alongside Pi-Hole
3. Have Pi-Hole act as DHCP server
4. See warning

## Debug Token

- URL:  https://tricorder.pi-hole.net/he8Ou792/

### Additional context

I used to work around this issue by specifying one domain where dnsmasq was active. (`domain=eth0`) This made it so that the messages no longer appeared. However, I could not do this once I installed WireGuard and wanted to use Pi-Hole DNS with WireGuard. So I had to fall back to the config options `no-dhcp-interface` to only disable DHCP on these interfaces.

The problem is that these virtual docker interfaces are dynamic and change names...

**Comment by DL6ER** [comment]
> So I had to fall back to the config options `no-dhcp-interface` to only disable DHCP on these interfaces.
>
> The problem is that these virtual docker interfaces are dynamic and change names...

How do they change names? Note that the option `no-dhcp-interface` supports wildcards like
```
no-dhcp-interface=br-*
```
