### ISSUE TITLE
PiHole filtereing traffic on all interfaces instead of only wg0

### ISSUE THREAD

**Issue by afzl-wtu** [pi-hole/pi-hole#4577]
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform

Ubuntu 20.04 aarch64 - Oracle Cloud VM

### Expected behavior
                Before installing pihole via your provided script, I can see 127.0.0.53  in /etc/resolv.conf and internet works fine.
       I have two interfaces:
                enp0s3 10.0.0.116 (my Main Interface)
                wg0      10.7.0.1 (Wireguard Server)
        Durnig installing I choose wg0 as interface because **I want piHole to filter traffic only from my connected vpn clients and not  
       of my pc**. So after that installer starts installing pihole and _stuck at Can not resolve DNS Host and 120 second countdown starts_. 
      So I change my DNS reslover  127.0.0.53 to 127.0.01 in /etc/resolv.conf and installer then stop retrying countdown and installs the 
     pihole. but it give my ipadress of DNS as 10.0.0.116 which is ip of my enp0s3 interface. But it should give my ip adress of wg0 
     interface because I choosed wg0 as interafce while installing pihole.  So I change DNS ip to 10.7.0.1 in 
     /etc/pihole/setupVars.config and everything works fine.  

### Actual behavior / bug

 I set my upstream DNS to NEXTDNS  in pihole to check where pihole is working. I can see nextDNS on all my connected vpn clients. so it is working. But the issue is this when I open my firefox on my VM through VNCviewer, I can see NEXTDNS applied there too.
 (if you go NEXTDNS website and click "Try Now" they tell you what DNS you are using)
So the bug is Pihole is filtering traffic everywhere on my VM. But it should filter only traffic of wg0

### What I have tried:
pihole -a -i local
pihole -a -i single
pihole -a -i bind

No matter what it always show my choosen (CloudFlare at the moment) DNS on all vpn devices connected to wg0 and on my VM connected to enp0s3.

## Debug Token

- URL:  https://tricorder.pi-hole.net/4Y2ggzA4/

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.
