### ISSUE TITLE
Can't see total queries and clients graphs in main page

### ISSUE THREAD

**Issue by ashr123** [pi-hole/pi-hole#4579]
### Versions

- Pi-hole:  v5.8.1
- AdminLTE:  v5.10.1
- FTL:  v5.13

### Platform

- OS and version:  Ubuntu 21.04

- Platform:  Raspberry Pi

### Expected behavior

See the graph as usual

### Actual behavior / bug

Can be seen in the attached photo

### Steps to reproduce

1. Open the web interface...

## Debug Token

- URL:  https://tricorder.pi-hole.net/eYjeeJ8K/

### Screenshots

![image](https://user-images.githubusercontent.com/26481657/151221707-91b686f5-32da-4d68-8e79-ff0c9fbfafa9.png)

### Additional context

It may look like I've just installed the app, but it isn't the case... it is running for months

**Comment by rdwebdesign** [comment]
Are you using the Docker image?

**Comment by ashr123** [comment]
> Are you using the Docker image?

No, it runs directly on the OS

**Comment by rdwebdesign** [comment]
What do you see in "_Long-term data / Graphics_", when you select "Today"?

Note: if nothing appears, select "Last 7 days".

**Comment by ashr123** [comment]
> What do you see in "_Long-term data / Graphics_", when you select "Today"?
> 
> Note: if nothing appears, select "Last 7 days".

@rdwebdesign 
![image](https://user-images.githubusercontent.com/26481657/151241152-fbe554de-8c20-42d4-862b-18313f61fc66.png)

**Comment by rdwebdesign** [comment]
Do you see any errors in the "developer tools / console" window (usually <kbd>F12</kbd> key)?

**Comment by ashr123** [comment]
> Do you see any errors in the "developer tools / console" window (usually F12 key)?
> 
> You can try other simple tests:
> 
> * access the dashboard using a different browser or a different device;
> * clear your browser cache and try again;
> * disable all browser plugins/extensions and try again.

@rdwebdesign
When I'm looking at Developer Tools I see the following error:

> Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.    index.php:1

When I open the page in Safari (I have MacBook), I see the same effect:
![image](https://user-images.githubusercontent.com/26481657/151383321-292bce34-6047-4ffe-afe0-8a6673728f64.png)

**Comment by s644** [comment]
Ok, that was quite a bad false positive relation I guess  :D

I took a look at nginx erro.log (I'm using nginx instead of lighttp) and saw, that there were problems connecting to the sqllite database.

`PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READONLY" in /var/www/html/admin/scripts/pi-hole/php/database.php:61`

And I also noticed, that pihole is running on php 8.0 and not 7.4 as I falsely remembered

`thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 61" while reading response header from upstream, client: 192.168.0.10, server: _, request: "GET /admin/api_db.php?status HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "x.x.x.x:8080", referrer: "http://x.x.x.x:8080/admin/db_graph.php"`

So I was also remembering that aptitude removed the php8.0-sqllite package yesterday...

Switcht to php8.1 with sqllite package and everything's working fine again.
`

**Comment by rdwebdesign** [comment]
@s644
Your problem is unrelated (I'm glad you got it resolved).

**Comment by rdwebdesign** [comment]
@ashr123

> Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist. index.php:1

Have you tried disable **ALL** browser plugins/extensions?
This error message doesn't say much, but sometimes this is related to browser extensions.

**Comment by ashr123** [comment]
> @ashr123
> 
> 
> 
> > Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist. index.php:1
> 
> 
> 
> Have you tried disable **ALL** browser plugins/extensions?
> 
> This error message doesn't say much, but sometimes this is related to browser extensions. 

@rdwebdesign I'll try it, but I must say it will be weird if it is the problem.. cause I didn't change anything lately.
I'll also try open it in Firefox, directly from the raspberry pi, if I remember correctly, I didn't install any plugin there

**Comment by rdwebdesign** [comment]
I believe you, but no one else is seeing/reporting this error.

Please, try it.
If you provide more information we may find a solution.

**Comment by ashr123** [comment]
> I believe you, but no one else is seeing/reporting this error.
> 
> Please, try it. If you provide more information we may find a solution.

It's also happening in Firefox my Raspberry Pi :-/..
My PHP version is 8.0.8 by the way

**Comment by PromoFaux** [comment]
Can you check in `/var/log/pihole-FTL.log`, see if anything looks suspicious in there

**Comment by PromoFaux** [comment]
Ah wait... This might be the answer you're looking for:

https://discourse.pi-hole.net/t/dashboard-is-empty-after-v5-0-update/32577/10?u=promofaux

First result when I Googled `PHP Fatal error: Uncaught Error: Undefined constant "SQLITE3_OPEN_READONLY"` :)

**Comment by rdwebdesign** [comment]
@ashr123 

Just a question:
Did you restarted your pi-hole after the update?

**Comment by ashr123** [comment]
> @ashr123 
> 
> 
> 
> Just a question:
> 
> Did you restarted your pi-hole after the update?

I think so.. 4 days ago

**Comment by PromoFaux** [comment]
I think I've reproduced this on a Ubuntu 21.04 droplet... But I don't yet know the cause. Will try to investigate a bit more closely later on after work

![image](https://user-images.githubusercontent.com/1998970/151553310-03c2e808-1ab1-41a9-8066-28c460933cdb.png)

**Comment by PromoFaux** [comment]
Tell a lie... it has now started showing something on the graph. Which I was sort of hoping would be the case (logic being that it is a new install) 

![image](https://user-images.githubusercontent.com/1998970/151554665-ee29b75e-aae7-4d1b-9afd-33f32d1239c0.png)

**Comment by ashr123** [comment]
> Error 500 and no server logs doesn't really fit together, unless server logs have been disabled intentionally. Could you also check `/var/log/lighttpd` ?

@DL6ER if you meant to me, this is what I got from `/var/log/lighttpd/error.log`:

> 2022-01-23 00:00:13: server.c.1787) logfiles cycled UID = 0 PID = 150890
2022-01-25 13:28:59: server.c.1976) server stopped by UID = 0 PID = 1
2022-01-10 06:08:08: server.c.1513) server started (lighttpd/1.4.59)

From `/var/log/lighttpd/error.log.1`: 

> 2022-01-16 00:00:37: server.c.1787) logfiles cycled UID = 0 PID = 285426
2022-01-17 00:00:38: server.c.1787) logfiles cycled UID = 0 PID = 330143
2022-01-19 16:55:04: server.c.1976) server stopped by UID = 0 PID = 1
2022-01-10 06:08:06: server.c.1513) server started (lighttpd/1.4.59)

Hope it helps

**Comment by PromoFaux** [comment]
@ashr123 Can you browse to `http://46.101.89.132/admin/index.php` please and tell me what you see on the dashboard there?

**Comment by ashr123** [comment]
> @ashr123 Can you browse to `http://46.101.89.132/admin/index.php` please and tell me what you see on the dashboard there?

@PromoFaux ![image](https://user-images.githubusercontent.com/26481657/151565568-2433cba6-3468-42b0-8fb9-fb5614aa1c90.png)

**Comment by PromoFaux** [comment]
Thanks. OK, that confirms that it is not your browser, at least... But I am at a loss as to what is going on on your install. Your debug log looks fine, I can't see anything that would make me think it was broken in there!

Please can I see more of the log at `/var/log/pihole-FTL.log` (you can deliver it securely via `cat /var/log/pihole-FTL.log | pihole tricorder` if you like)

**Comment by ashr123** [comment]
@PromoFaux I don't see anything security issue with the output, so I'll just put it here:

> [2022-01-28 03:59:39.432 1455M] Resizing "FTL-dns-cache" from 176128 to (11264 * 16) == 180224 (/dev/shm: 4.1MB used, 4.1GB total, FTL uses 4.1MB)
[2022-01-28 11:06:56.002 1455M] Resizing "FTL-dns-cache" from 180224 to (11520 * 16) == 184320 (/dev/shm: 4.1MB used, 4.1GB total, FTL uses 4.1MB)

**Comment by PromoFaux** [comment]
I might be barking up the wrong tree.

Do you get any output if you browse to:

 - `http://pi.hole/admin/api.php?overTimeData10mins`
 - `http://pi.hole/admin/api.php?overTimeDataClients&getClientNames`

**Comment by ashr123** [comment]
> I might be barking up the wrong tree.
> 
> Do you get any output if you browse to:
> 
> * `http://pi.hole/admin/api.php?overTimeData10mins`
> * `http://pi.hole/admin/api.php?overTimeDataClients&getClientNames`

@PromoFaux

- http://pi.hole/admin/api.php?overTimeData10mins:
  ```json
  {"domains_over_time":{"1641790500":25346},"ads_over_time":{"1641790500":1181}}
  ```
- http://pi.hole/admin/api.php?overTimeDataClients&getClientNames:
  ```json
  []
  ```

**Comment by PromoFaux** [comment]
And on the command line, what is the output of:

```
echo ">ClientsoverTime" | nc 127.0.0.1 4711
```

(A small request: please don't quote the whole message you are replying to - it just causes clutter.. you also don't need to @ tag people on each response, we see them all 🙂)

**Comment by ashr123** [comment]
I'm getting
> 1641790500 5590 8418 927 5964 1654 130 838 3468 535 1055 102
---EOM---

And `nc` doesn't exit normally, I need to press ⌃C for it to exit (maybe it is OK..)

**Comment by rdwebdesign** [comment]
Just one line with numbers?

**Comment by ashr123** [comment]
yep, just it

**Comment by rdwebdesign** [comment]
I notice one strange thing:

The out put of your last command is showing data from "Monday, **10 January** 2022 04:55:00".

At the same time, the logs you post are showing records apparently out of order:
```log
2022-01-16 00:00:37: server.c.1787) logfiles cycled UID = 0 PID = 285426
2022-01-17 00:00:38: server.c.1787) logfiles cycled UID = 0 PID = 330143
2022-01-19 16:55:04: server.c.1976) server stopped by UID = 0 PID = 1
2022-01-10 06:08:06: server.c.1513) server started (lighttpd/1.4.59)
```

The last line is from 2022-01-**10**, but the previous one is from the 2022-01-**19**.

**Comment by rdwebdesign** [comment]
@ashr123 
What is the current time of your system?

**Comment by ashr123** [comment]
This is probably because weird bug: every time I restart the 𝜋, the clock resets to 10.1 for some reason.. to fix it I temporarily replace the DNS of the connection from the static IP of the 𝜋 to Cloudflare's until the OS pulls the right date and time

**Comment by rdwebdesign** [comment]
I'm just guessing, but maybe this "other weird bug" is changing the current time of your system and the records are getting lost/mixed/scrambled.

I never saw this behavior before (time resetting to a specific date).  Do you have any idea what is causing it?

**Comment by ashr123** [comment]
I wish I knew....
I don't have a clue, I even don't know how to tart to figure it out

**Comment by rdwebdesign** [comment]
Raspberry Pis don't have a Real Time Clock (RTC) hardware. 

The time is always reset at start up. Usually it resets to the last recorded time before shutdown or to 1970-1-1 (timestamp=0), depending on your system's config.

Take a look at: https://forums.raspberrypi.com/viewtopic.php?t=254744

**Comment by ashr123** [comment]
`fake-hwclock` wasn't present on my raspberry pi, so I've installed it now.
I don't know what went wrong, but when I've installed my OS (Ubuntu 21.04, 64 bit) everything was OK, I do not remember when or why the phenomenon started to appear...

**Comment by rdwebdesign** [comment]
I'm not sure this will fix the issue (I don't even know if Ubuntu uses `fake-hwclock`).

I'm just trying to indicate a possible solution to the "time reset" problem.

**Comment by ashr123** [comment]
Yes, I know 🙂

**Comment by sahiluchil** [comment]
Hi,

I was also having the exact same issue, with the same versions. I was going to open a ticket but found out this one.

The issue was that my Raspberry Pi was in the wrong timezone. Because of an improper shutdown, the timezone was set to UTC instead of Asia/Kolkata.

Changed the time timezone and restated the Pi-Hole and the DNS resolver from setting and the graphs showed up.

**Comment by ashr123** [comment]
@sahiluchil with the advice @rdwebdesign gave me (about the fake NTP clock) it seems that it solved my problem!
Now my Raspberry Pi starts correctly.

@rdwebdesign, maybe there is a bug in the way `Long-term data > Graphics` and the main display displays the last 24 hours, I would recommend that the main graphics will use the same query as the `Long-term data > Graphics` does (just with hard coded query)

**Comment by rdwebdesign** [comment]
@ashr123
Is your graphic problem solved?

**Comment by ashr123** [comment]
Yes, thank you all for the help and the support!

**Comment by aaemon** [comment]
I solved this issue by removing logs from /var/log/, I don't know but I faced the issue many times when freshly installed pi-hole on my raspberry pi. I hope it helps :)

# rm -rf /var/log/pihole-FTL*
# rm -rf /var/log/pihole.log*
# systemctl restart pihole-FTL

**Comment by diwit** [comment]
Thanks, in my case I have pi-hole running on a Raspberry Pi on Raspbian, and was having the same issue. It was the time that was set to the wrong time-zone (just 1 hour behind my actual time), so I changed the time-zone (`timedatectl list-timezones` and then `sudo timedatectl set-timezone <time zone>`) and after a restart of the Pi (not before the restart), the charts on the dashboard page are now showing properly. Thanks!

**Comment by jwetty** [comment]
Thank you everyone! This issue happened to me as well. Perfect fix was for me the TimeZone settings. Somehow they got reset, and once I set to correct TZ, rebooted, the graphs for 'Total Queries over last 24 hours' appeared. Great fix, thank you! 
My environment on 9/18/2023
RaspberryPi 4, running Version 11 - Bullseye
PiHole v5.17.1
FTL v5.23
Web Interface v5.20.1
