### ISSUE TITLE
Cannot use DNS name for Custom Upstream DNS Server

### ISSUE THREAD

**Issue by si-kotic** [pi-hole/pi-hole#4583]
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform

- OS and version:  Debian 10 Buster (official pihole container)

- Platform:  Raspberry Pi / Docker Swarm

### Expected behavior

I expected the Custom Upstream DNS Servers to be able to take a local DNS value.

### Actual behavior / bug

Addresses which are not IP addresses are reported as invalid and rejected.

### Steps to reproduce

1. Go to 'Settings > DNS'
2. Tick 'Custom IPv4 1'
3. Enter {dns_address}#{port}
4. Click save

### Screenshots

<img width="243" alt="image" src="https://user-images.githubusercontent.com/16864314/151671888-2fcd6215-82c1-47a3-8f2c-3cc28786d52c.png">

### Additional context

I understand why this is the case (the field is even marked as ipv4) but I don't think it needs to be and being able to use an internal DNS address would be really helpful.
In my case, I am running pihole in a docker swarm with another container running cloudflared.  Both containers are attached to a small subnet that is internal to docker only over which they communicate, so pihole is the only machine able to make requests to the cloudflared container.  Unfortunatey, in Docker Swarm and Compose v3, you cannot assign a static IP address to your containers so every time I redeploy the service or the cloudflared container is migrated to another host, it gets a new IP and pihole doesn't know this.

Containers within docker are able to resolve IPs of other containers by their container name, in this case "cloudflared".  Given the limitations in Docker at the moment, I tried to use "cloudflared#5053" as the value for my custom upstream DNS server only to find that it cannot be used.

I think this would be a really useful and powerful feature for use in docker deployments.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by yubiuser** [comment]
Part of this (the backend) is addressed by https://github.com/pi-hole/dnsmasq/pull/9
