### ISSUE TITLE
Installing without default blocklist causes gravity tree error, interrupting installer.

### ISSUE THREAD

**Issue by JRHemmen** [pi-hole/pi-hole#4591]
### Versions

- Pi-hole:  v5.8.1
- AdminLTE:  v5.10.1
- FTL:  v5.13

### Platform
- OS and version:  Ubuntu 20.04 LTS, Debian Bullseye
- Platform:  VM running on ESXi 7.0

### Expected behavior

Fresh install with no default blocklist, so that I can import my own.

### Actual behavior / bug

Installing Pi-hole without the default blocklist, it is unable to build the gravity tree as there are no domains present. This bombs out the install and does not create a default admin password. Password must be manually set via pihole -a -p for first time login. Since the installer fails prematurely, the final page directing you to the URL of the web interface does not appear either.

### Steps to reproduce

Walk through standard install
Deselect built-in blocklist

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/pi-hole/pull/4535

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
