### ISSUE TITLE
No internet for newly connected devices for ~5min

### ISSUE THREAD

**Issue by s3k4t0r** [pi-hole/pi-hole#4592]
### Versions

Pi-hole version is v5.8.1 (Latest: v5.8.1)
AdminLTE version is v5.10.1 (Latest: v5.10.1)
FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version:  PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

- Platform:  Raspberry pi 3 b+

### Expected behavior

Just work correctly and connect to internet without delay  

### Actual behavior / bug

Every new device connecting to network don't have internet
if i wait for 2-5 min connected by WiFi or Ethernet it will  start working
if pc is turn off or mobile device is taken of network/out side problem appears
during problem (this first 2-5 minutes ) ping to Pi or connection to it is not working, but the same time from other device what was connected before u can access pihole and everything is working ok
only change what was done is install "Unbound" done from YT guide of CraftComputing
i have removed Unbound and use google DNS but it did not make any difference  
its not network related problem because problem appears on WiFi and Ethernet and during that problem i can still access other  devices on network like modem , network hdd or ping any other device 
## Debug Token

- URL:  https://tricorder.pi-hole.net/2Trz7BvB/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.
