### ISSUE TITLE
Firefox Resist Fingerprinting makes web UI time in UTC

### ISSUE THREAD

**Issue by Githob2021** [pi-hole/pi-hole#4594]
### Versions
  Current Pi-hole version is v5.7
  Current AdminLTE version is v5.9
  Current FTL version is v5.12.1

### Platform
OS and version: Raspberry Pi OS 2021-10-30
Platform: Raspberry Pi

When using the privacy.resistFingerprinting about:config change in Firefox, the web UI shows the data in UTC. 

Please provide a way for users to still see local time with this config on. It could be a drop-down for all time zones that is saved in settings for example.

Or ideally there would be an option for the web UI to display either server timezone or browser timezone.

**Comment by jfb-pihole** [comment]
Please submit feature requests on our discourse site. 

https://discourse.pi-hole.net
