### ISSUE TITLE
DNS Flood

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#4601]
### Versions

-  Pi-hole version is development v5.8.1-49-ge9250d62 (Latest: v5.8.1)
-  AdminLTE version is devel v5.10.1-51-g551e2d09 (Latest: v5.10.1)
-  FTL version is development vDev-76d3328 (Latest: v5.13)

### Platform

- OS and version:   Linux raspberrypi 5.10.92-v8+ # 1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

- Platform:   Raspberry Pi

### Expected behavior

Not this DNS flood to occur.

### Actual behavior / bug

Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.11
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
.
.
.
.
.
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.11
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: forwarded mje1nzyyodq to 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: query[A] mje1nzyyodq from 192.168.2.1
Feb  8 18:32:10 dnsmasq[81419]: Maximum number of concurrent DNS queries reached (max: 150)

### Steps to reproduce

Not sure how this happens.

## Debug Token

- URL:   Your debug token is: https://tricorder.pi-hole.net/4khYMW8w/

**Comment by yubiuser** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our [Discourse](https://discourse.pi-hole.net/) forum.

Thank you for your understanding.

**Comment by DenyDarko** [comment]
@yubiuser 

A client ( 192.168.2.11 ) sends a query.

pihole forwards it to the router (192.168.2.1) and then bouncing back and forth starting to happen.

Queries to the router are only supposed to be forwarded for the local /24 network and only because pihole doesn't act as DHCP.

I can't see where the configuration error is on this one
