### ISSUE TITLE
Dashboard status says "offline" but is working

### ISSUE THREAD

**Issue by weitzner** [pi-hole/pi-hole#4602]
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.10.1
- FTL:  5.11

### Platform

- OS and version:  Raspbian 11, bullseye

- Platform:  Raspberry Pi, Docker

### Expected behavior

The status in the wed UI should be accurate

### Actual behavior / bug

The dashboard has a status of "offline" but everything seems to be working.  Clicking "Enable" sets the status to "online" but clicking to a new section in the console or refreshing the page immediately reverts to "offline" again while continuing to function. This creates a somewhat tedious/complicated workflow in cases where one wants to temporarily disable the console (click enable, then the disable option is available and functions).

### Steps to reproduce

Pull docker container, load web UI

## Debug Token

- URL:  https://tricorder.pi-hole.net/xQA91O7U

### Screenshots

<img width="230" alt="Screen Shot 2022-02-03 at 3 44 14 PM" src="https://user-images.githubusercontent.com/464597/152441759-d809e469-069d-4903-87bf-bfe01bd096f3.png">

### Additional context

I had initially posted this issue in a [repo for a downstream container](https://github.com/juampe/docker-pi-hole-dot/issues/5), the author believes [this commit](https://github.com/pi-hole/pi-hole/commit/ef30a85afb1653df4d3ce393dd6b8d7ecbb29ab0) is the culprit.

**Comment by PromoFaux** [comment]
Issue is (was) in the downstream docker image using ours as a base (see linked issue)
