### ISSUE TITLE
Rocky Linux not supported, but workks

### ISSUE THREAD

**Issue by jbayer-a3k** [pi-hole/pi-hole#4604]
### Versions

  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version:  Rocky Linux 8.5

### Expected behavior

pihole -up do the upate

### Actual behavior / bug

Says it's not supported.   Running the command:

PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r

did do a successful update

### Steps to reproduce

install/update on rocky Linux

## Debug Token

- URL:  

The command run above (pihole -d...) fails with the following:

[root@pihole etc]# `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
ls: cannot access '/etc/lighttpd': No such file or directory
ls: cannot access '/var/log/lighttpd': No such file or directory

This server is using nginx, not sure if this is a secondary issue

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
