### ISSUE TITLE
[feature request] capability to update pihole directly without actually updating the blocklists

### ISSUE THREAD

**Issue by Baricanac** [pi-hole/pi-hole#4612]
Sometimes I just want to update my pihole with "pihole -up" without having to update the few hundred blocklists I have installed at the time, does anyone else feel the same?

**Comment by rdwebdesign** [comment]
We receive a high number of requests, but as a free open-source project run by volunteers we have very limited resources.
Please, we ask that you open your Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8).

Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8
