### ISSUE TITLE
pihole update breaks lighttpd running php-fpm

### ISSUE THREAD

**Issue by LLPP65** [pi-hole/pi-hole#4617]
### Versions

- Pi-hole:  5.9
- AdminLTE:  5.14
- FTL:  5.11

### Platform

- OS and version:  Ubuntu 21.10

- Platform:  Raspberry 3

### Expected behavior

I expected "pihole -up" to update the system without breaking lighttpd

### Actual behavior / bug

As part of the update, the lighttpd config files are modified / verified. I am using php-fpm, but the updater has added a symbolic link from ../conf-available/15-fastcgi-php.conf to 15-fastcgi-php.conf. This caused lighttpd to crash on restart and the updated process fails. 

### Steps to reproduce

update pihole on a system that uses php-fpm

pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/hXwciE9C

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
`15-fastcgi-php.conf`
I think this file isn't touched by Pi-hole at all. What makes you think `pihole -up` created that symlink

**Comment by yubiuser** [comment]
I don't see any errors in your `/var/log/lighttpd/error.log`

```
   2022-02-13 00:00:11: server.c.1787) logfiles cycled UID = 0 PID = 1686591
   2022-02-18 11:38:12: server.c.1976) server stopped by UID = 0 PID = 1
   2022-02-18 11:41:38: server.c.1513) server started (lighttpd/1.4.59)
   2022-02-18 11:41:38: configfile.c.1142) WARNING: unknown config-key: alias.url (ignored)
```

**Comment by LLPP65** [comment]
Hi, thanks for the quick reply. The timestamp of the php-cgi symlink was the same time as the pihole update. lighttpd was working correctly before the update and was not working at all after the update. lighttpd started working correctly immediately after I removed the symlink. The file itself isn't touched, but it is symlinked into the conf-active directory.

**Comment by LLPP65** [comment]
This is still happening. I upgraded today and the updater added to following symbolic link which kills my lighttpd installation and makes the upgrade fail:

/etc/lighttpd/conf-enabled/15-fastcgi-php.conf -> ../conf-available/15-fastcgi-php.conf

Please check for other lighttpd installation types before adding config links.

**Comment by yubiuser** [comment]
Thanks for re-reporting. 
I was wrong. We don't touch the file directly, but indirectly

https://github.com/pi-hole/pi-hole/blob/853f6b7da2b5130e33d76840f463ab374eb77596/automated%20install/basic-install.sh#L1834-L1837

I'm not sure what's the best way to handle your case. We could probably check if `php-fpm` is enabled and skip `lighty-enable-mod fastcgi-php`.

P.S. Pi-hole will have it's own websetver included, which should prevent such issues

**Comment by gstrauss** [comment]
Is this still an issue?  The pi-hole install script no longer tries to enable fastcgi-php.

**Comment by LLPP65** [comment]
I updated just a few days ago and it didn't break my installation. Thanks!

**Comment by rdwebdesign** [comment]
@yubiuser 

The related `lighttpd` config was changed. I think this is no longer an issue.
