### ISSUE TITLE
Question on custom content filtering

### ISSUE THREAD

**Issue by DonLexos** [pi-hole/pi-hole#462]
Due to a recent malware distribution through a big adnetwork that hit quite a few well known websites here in The Netherlands I want to ad the pi-hole in a work related situation to block the ad networks. The system seems very solid, I have been using it for months at home. It would be just dns1 so if it would fail we would fall back to a (normal) public DNS.

Now, when I do add a pi to the network I would love it if I could also use this as a way to block some websites for clients, ie FaceBook, Instagram etc (content filter). Right now those are blocked on some clients through the (windows) hostfile, big hassle to update them (at least in the current situation). If the pi-hole would be added that can be tackled differently.

I am aware I can use the blacklist/whitelist functionality. That however requires manual updating the blacklist.txt file to make that happen on each pi.

What I was thinking, if could also be possible to have a custom blocklist we host ourselves that I add to the configuration and update when needed, and the pi's would simply grab them on the next cron run (or when I force them to update).

Could someone guide me to how best to format this blocklist file in order to have the least amount of hassle to make it work? I am aware of a few presets since the script is capable of grabbing a few lists that has different formatting and all kinds of rules to make it so it works. 

I am aware this falls outside of the scope of the project (or at least the purpose of the pi), but a simple 'take a look at the formatting of list X, copy that and it should work' would do.

Thanks in advance!
Alex

**Comment by PromoFaux** [comment]
Take a look at the custom source list [wiki page](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists).

Essentially all you need to do is host a list of domains, and add the URL of that list to `adlist.list` (after copying `adlist.default` to `adlist.list`)

**Comment by DonLexos** [comment]
Oh there is a wiki page for it? Duh ,,,.. Ok thank you for pointing that out, you would imagine I would be able to locate that myself... Will take a peak there!
