### ISSUE TITLE
iMessages unable to resolve gif search with pi-hole update:

### ISSUE THREAD

**Issue by kl330ffs3c** [pi-hole/pi-hole#4622]
Issue seems to be that iMessage is unable to load any gifs using the build in gif search. Added multiple broad regex whitelist expressions to no avail. Tried tailing log while querying gif search and not seeing any urls blocked. Disabled pi-hole and tried pinging known blocked url and was able to. Re-enabled pi-hole and got localhost returned as expected. If I use different network (ie cellular) all works as expected. Wondering if something in the updated config has caused this to break. Anyone else experience this? Please advise. 

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

Apple all OSes

[](url)
### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our [Discourse](https://discourse.pi-hole.net/) forum.

Thank you for your understanding.
