### ISSUE TITLE
Continuous warnings about ignoring a domain that hide other warnings, and are normal and expected in a typical remote work configuration

### ISSUE THREAD

**Issue by wsw70** [pi-hole/pi-hole#4624]
### Versions

Pi-hole version is v5.9 (Latest: v5.9)
AdminLTE version is v5.11 (Latest: v5.11)
FTL version is v5.14 (Latest: v5.14)

### Platform

- OS and version:  Raspberry OS,  5.10.92-v7+ SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux

- Platform:  Raspbery Pi

### Expected behavior

A work computer attached to a company domain, when at home, should not generate any warnings related to that fact.

### Actual behavior / bug

I get continuous warnings of the type:

> Ignoring domain `CONFIG_DOMAIN` for DHCP host name `HOSTNAME`

### Steps to reproduce

1. Connect to the network a machine which is joined to a domain (outside of that network, typically a company domain)

## Debug Token

- URL:  https://tricorder.pi-hole.net/z1T3jI61/

### Additional context

I understand that this is a warning and that the warning makes sense (at least technically speaking). It is however completely useless in the context of users who connect a company machine to a home network. The only effect is a growing log, blinking warnings on the dashboard page, and **quasi-certainty to miss other warnings**.

PLEASE make available a way to shut off that specific warning.

**Why I consider this a bug and not "works as designed" or "feature request" ?** Because pihole is predominantly a home system, and we live in a world where remote work on company computers is common. A warning essentially about that should be easily blacklisted and it is not. Moreover (sorry to repeat that again) - other warnings will be missed because of that.

**Comment by yubiuser** [comment]
Please see here if that workaround is helping you:
https://discourse.pi-hole.net/t/ignoring-domain-config-domain-for-dhcp-host-name-hostname/52027

**Comment by wsw70** [comment]
@yubiuser : thank you - setting fixed IPs and modifying the configuration indeed helped.

I still believe that this particular warning is harmful (in the context of work from home - the case in the linked post) and should be made optional in pihole. The workaround is not really scalable either (it requires to abondin the "dynamic" part of DHCP :( )
