### ISSUE TITLE
Most requests being answered by wrong upstream server

### ISSUE THREAD

**Issue by linux-addict** [pi-hole/pi-hole#4626]
I yesterday set up pi-hole on my local server. In the settings, I enabled all cloudflare dns servers (IPV4 & IPV6) and left the rest disabled. However, the dashboard shows that the majority of responses is being resolved by "dns.google" instead of cloudflare servers. I now additionally enabled the OpenDNS servers and deleted the database, but after some minutes, almost 40% of the queries uses dns.google (~60% are cache hits) again. The attached screenshots show the dashboard graph after some 10k requests and my upstream dns settings.
I'm quite confused by this behaviour and haven't found anything related in the documentation or github issues.
Can anyone explain why this happens or is there anything I'm misunderstanding?

pi-hole -v shows:
  Pi-hole version is v5.11 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

Which additional information do you need?

![2022-02-21-093942_421x289_scrot](https://user-images.githubusercontent.com/25572273/154920604-facccfbb-f67d-4370-9965-e6a59adc869b.png)
![2022-02-21-094014_466x568_scrot](https://user-images.githubusercontent.com/25572273/154920607-4373e21f-2537-46e6-9f23-e319053d3f8e.png)

**Comment by yubiuser** [comment]
> Which additional information do you need?

Please generate a debug token

**Comment by linux-addict** [comment]
It gives this output:

Pi-hole debug options are disabled.

ArchLinux distribution of Pi-hole is not supported by official project and this debug report CAN NOT be uploaded to their debug team.
Follow instructions carefully on the project wiki page (https://wiki.archlinux.org/index.php/Pi-hole) and please refer to AUR package web page for support and debugging (https://aur.archlinux.org/packages/pi-hole-server).

So my os (Manjaro Linux) is actually not even supported... I followed these links and apparently debugging is completely disabled.
By now, pihole seems to be using the cloudflare dns for more requests, but the google dns still takes up 20% of the pie chart.

**Comment by jfb-pihole** [comment]
“ please refer to AUR package web page for support and debugging (https://aur.archlinux.org/packages/pi-hole-server).”
