### ISSUE TITLE
Query Log can‘t be flushed

### ISSUE THREAD

**Issue by A12BA5E** [pi-hole/pi-hole#4627]
### Versions

- Pi-hole:  v5.9
- AdminLTE:  v5.11
- FTL: v5.14
- PADD: v3.6.6

### Platform
- OS and version:  raspbian OS Buster legacy
- Platform:  RPi3+B and RPi0

### Expected behavior

Flushed the 24h Query Log by pressing the relevant button under settings after confirmation from pihole.

### Actual behavior / bug

Despite the fact the flaushing was confirmed from pihole, the data stays as the the button was never pressed.
This happens on two independen indtances on a RPi3+ and a RPi Zero the same way.

1. Go to 'setting'
2. Click on 'flush query log'
3. ‚Wait for flush confirmation message from pihole'
4. ‚Watch the dashboard and wonder why.‘

**Comment by yubiuser** [comment]
Duplicate: https://github.com/pi-hole/pi-hole/issues/4611
