### ISSUE TITLE
'sudo' detection in gravity.sh

### ISSUE THREAD

**Issue by Zer0t3ch** [pi-hole/pi-hole#463]
##### Expected Behaviour:
`gravity.sh` should correctly detect whether or not `sudo` is installed on all/most distributions

##### Actual Behaviour:
`gravity.sh` can only detect if it's installed on Debian-based distribution

##### Steps to reproduce this issue:
Run `gravity.sh` on a non-Debian-based distro (like Arch)

##### Possible solution
Change line 22 to something like this:

    if [[ -x /usr/bin/sudo ]];then

---

As a sidenote, I've noticed that you don't bother detecting if `sudo` is installed or not in `blacklist.sh`, and I assume `whitelist.sh`

**Comment by PromoFaux** [comment]
> gravity.sh should correctly detect whether or not sudo is installed on all/most distributions

I'm inclined to disagree. Have you tried running the install script on a non-debian based distro? From the [readme](https://github.com/pi-hole/pi-hole/blob/master/README.md) of this repo:

![image](https://cloud.githubusercontent.com/assets/1998970/14497060/71aee074-018d-11e6-8e56-e6280a77f105.png)

As it stands, it's not designed to be run on Arch/anything else (although there is a [port  on AUR](https://aur.archlinux.org/packages/pi-hole-server/), but that's not maintained by us) Actually looking at that, I see you've already spoken with them, so you know we don't maintain it.

That said, we're not ruling out compatibility with non-debian distros in future. We just haven't started on that yet. 

>As a sidenote, I've noticed that you don't bother detecting if sudo is installed or not in blacklist.sh, and I assume whitelist.sh

I think the language you use there is unnecessarily hostile ("don't bother") but you're right, there is no check in there, and that can easily be rectified, thanks for pointing it out!
