### ISSUE TITLE
Conditional forwarding to 172.16.0.0/12 incorrectly flagged as invalid

### ISSUE THREAD

**Issue by wvaske** [pi-hole/pi-hole#4630]
### Versions

- Pi-hole:  5.1.1
- AdminLTE:  5.1
- FTL:  5.1

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  Docker pihole/pihole:latest

### Expected behavior
172.16.0.0/12 (not slash 8 or slash 16 or slash 24) is a valid private range. It should be allowed for use in conditional forwarding

### Actual behavior / bug
When entering in 172.16.0.0/12 for conditional forwarding this error message is displayed:

Conditional forwarding subnet ("172.16.0.0/12") is invalid!
This field requires CIDR notation for local subnets (e.g., 192.168.0.0/16).
Please use only subnets /8, /16, /24, and /32.
The settings have been reset to their previous values 

### Steps to reproduce
Set 172.16.0.0/12 as conditional forwarding subnet

**Comment by yubiuser** [comment]
Upgrade your Pi-hole installation and it should work.
