### ISSUE TITLE
Dashboard showing long gone device names

### ISSUE THREAD

**Issue by mash8336** [pi-hole/pi-hole#4631]
![2022-02-28 07_12_39-Pi-hole - raspberrypi — Mozilla Firefox](https://user-images.githubusercontent.com/44288297/155940561-91293c36-badd-408e-bd56-89c21dce8403.png)
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
Model: Raspberry Pi Model B Rev 2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

### Expected behavior
Correct hostnames to be shown

### Actual behavior / bug
Hostnames of long gone devices shown

### Steps to reproduce

Ongoing behaviour

## Debug Token
https://tricorder.pi-hole.net/7IKL8nu7/

### Screenshots
attached

### Additional context
n/a

**Comment by yubiuser** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our [Discourse](https://discourse.pi-hole.net/) forum.

Thank you for your understanding.
