### ISSUE TITLE
"FTL failed..." because of missing package "procps"

### ISSUE THREAD

**Issue by lessload** [pi-hole/pi-hole#4633]
### Versions
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi

### Actual behavior / bug

"FTL failed to start due to failed to create listening socket for port 53: Address already in use"

from checking in script it use `pkill` and i lost that package when change from openssh to dropbear.

### Steps to Fix

- `pkill` command not found. fix by  `atp install procps ` 
- recomment add it to check list in install script.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.10
