### ISSUE TITLE
DNSMASQ_WARN interface eth0 does not currently exist

### ISSUE THREAD

**Issue by rrslssr** [pi-hole/pi-hole#4637]
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform 
Raspberry pi 
Linux pihole 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux

### Expected behavior
I received this error after updating the system to the versions noted above:
    2022-03-01 19:51:54  DNSMASQ_WARN   interface eth0 does not currently exist  
eth0 does exist and I can access the raspberry pi via VNC and by the pi-hole website

### Actual behavior / bug

I received this error after updating the system to the versions noted above:
    2022-03-01 19:51:54  DNSMASQ_WARN   interface eth0 does not currently exist  
eth0 does exist and I can access the raspberry pi via VNC and by the pi-hole website

### Steps to reproduce

1. Deleted warning within admin Pi-hole diagnosis
2. Rebooted
3. Logged in as admin. Warning reappeared.

## Debug Token

The debug log did not upload, possibly because of the Warning:

[✓] ** FINISHED DEBUGGING! **

   * The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.
[i] Debug script running in automated mode
    * Using curl for transmission.
    * curl failed, contact Pi-hole support for assistance.
    * Error message: curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log

- URL:  UNABLE to upload because of curl error

### Additional context

I have saved the debug.log file and can upload it manually...

**Comment by yubiuser** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our Discourse forum (https://discourse.pi-hole.net/) 

Thank you for your understanding.
