### ISSUE TITLE
local-ttl value not applied to gravity blocked entries

### ISSUE THREAD

**Issue by maddler** [pi-hole/pi-hole#4644]
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform

- OS and version:  Ubuntu 20.04.4

- Platform:  Raspberry Pi

### Expected behavior

after setting local-ttl=86400 in custom file, it looks like the TTL isn';t being applied to blocked queries (with a 2s still being applied_. It works as expected for entries in /etc/hosts.

### Actual behavior / bug

local-ttl value not applied to gravity blocked entries

### Steps to reproduce

1. set locall-ttl=86400 in /etc/dnsmasq.d/99-local.conf
2. execute "pihole restartdns"
3. dig blockeddomain (@)192.168.0.53 
4. returned TTL is 2s

## Debug Token

- URL:  https://tricorder.pi-hole.net/kjPPCUYx/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
There is a separate TTL setting for blocked domains.  Change this setting to the TTL you desire.

https://docs.pi-hole.net/ftldns/configfile/#block_ttl

https://github.com/pi-hole/FTL/pull/1173
