### ISSUE TITLE
CNAME record pointing to "pi.hole" doesn't return Pi-hole's IP

### ISSUE THREAD

**Issue by laplongejunior** [pi-hole/pi-hole#4647]
### Versions
- Pi-hole:  5.9
- AdminLTE:  5.11
- FTL:  5.14

### Platform
- OS and version:  Raspbian Lite 10 (Buster)
- Platform:  Raspberry Pi

### Expected behavior

Requests for "pi.hole" return an A record for Pi-hole, so a CNAME record pointing to it is expected to return Pi-hole's ip

### Actual behavior / bug

"pi.hole" returns 127.0.0.1 as an A record, but the CNAME record only returns "CNAME pi.hole" without the associated A record

### Steps to reproduce

1. For comparison purposes, go in Local DNS > A records; and create a domain pihole.home.arpa with pihole's IP
2. In Local DNS > CNAME records; create test.home.arpa pointing to pi.hole and pihole-a.home.arpa pointing to pihole.home.arpa
3. In SSH, run "dig test.home.arpa @127.0.0.1" and "dig pihole-a.home.arpa @127.0.0.1"

4. Here's the result : 

;;QUESTION SECTION:                                                                   ;test.home.arpa.                        IN      A                                                                                                                             ;; ANSWER SECTION:                                                                     test.home.arpa.         0       IN      CNAME   pi.hole.

;; QUESTION SECTION:                                                                   ;pihole-a.home.arpa.            IN      A                                                                                                                                     ;; ANSWER SECTION:                                                                     pihole-a.home.arpa.     0       IN      CNAME   pihole.home.arpa.                      pihole.home.arpa.       0       IN      A       192.168.192.1

## Debug Token

- URL:  https://tricorder.pi-hole.net/tbvVWM8s/

### Screenshots

(Text copy of the results available in the bug reproduction)

### Additional context

(The issue can be avoided by creating another local A record and using it in place of pi.hole)

**Comment by dschaper** [comment]
You can't use CNAMEs in the manner that you would like to. The reason is explained on the Local CNAME Records notes.

And any query for `pi.hole` will return the IP address of the interface the query was sent on. Since you are querying on the localhost interface, you get back the localhost address.

If you'd like to set `pi.hole` to return another address, use https://docs.pi-hole.net/ftldns/configfile/?h=reply_addr4#local_ipv4 and/or https://docs.pi-hole.net/ftldns/configfile/?h=reply_addr4#block_ipv4

**Comment by laplongejunior** [comment]
Sorry for my unclear terminology, my objective was not to return a different address for pi.hole, but for another domain to always return Pihole's address the way pi.hole does  
I had expected that pi.hole would be "a domain that the Pi-hole [...] is authoritative for" as the condition in the Local CNAME Records notes, but it seems I was mistaken (as it's interface specific) and sorry for the wasted time  

(My use case was that my network doesn't provide NAT loopback, so in order to test my PiVPN, I needed Pihole to return Pihole's IP when I query the domain that points to my LAN's public IP. Returning 127.0.0.1 when on Pi-hole's host would've actually worked.)

**Comment by laplongejunior** [comment]
I had assumed that pi.hole was "a domain that the Pi-hole [...] is authoritative for" as defined in the CNAME notes. But I had missed the obvious fact that an interface-specific domain is not one specific record so CNAME can't answer a specific IP.  

(I wasn't attempting to change pi.hole's address, but the reverse : allowing a domain to return in the same way as pi.hole  
In my real world case, the domain is my WAN ip to access PiVPN, but the lack of NAT loopback means I need to have the LAN ip when on the LAN. So Pihole must basically answer "itself" for one more domain alongside pi.hole)
