### ISSUE TITLE
pihole -v does not report the latest dot release

### ISSUE THREAD

**Issue by XulleX** [pi-hole/pi-hole#4651]
### Versions
``` /etc/pihole$ pihole -v
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11.1 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```
### Platform
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Platform:
Hardware  : BCM2835
Revision	 : a22082
Model       : Raspberry Pi 3 Model B Rev 1.2

### Expected behavior

Expected the latest version to report the dot release, example:
`  AdminLTE version is v5.11.1 (Latest: v5.11.1)`

Vs what is reported
`  AdminLTE version is v5.11.1 (Latest: v5.11)`

### Steps to reproduce

```
/etc/pihole$ pihole -v
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11.1 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```
Or
```
/etc/pihole$ pihole -v -a
  AdminLTE version is v5.11.1 (Latest: v5.11)
```

Result is the same even after removing GitHubVersions

**Comment by yubiuser** [comment]
Please generate a debug token.

**Comment by jfb-pihole** [comment]
The latest LTE version is 5.11, without a dot release:

```
*** [ DIAGNOSING ]: Core version
[i] Core: v5.9 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/pi-hole/pi-hole.git (fetch)
             origin	https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.9-0-g6ffa2ba1

*** [ DIAGNOSING ]: Web version
[i] Web: v5.11 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/pi-hole/AdminLTE.git (fetch)
             origin	https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.11-0-g64bbce90

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v5.14
```

**Comment by rdwebdesign** [comment]
Is `pihole -v` reporting `v5.11.1`?

What do you see on the web interface footer?

**Comment by XulleX** [comment]
This device has only been updated with 'pihole -up' and not sure when this issue started.  Noticed this with the recent addition of PADD and that is was reporting updates available for Web that could not be satisfied with 'pihole -up' .  Digging into the issue found the dot release for AdminLTE via the 'pihole -v'

Yes the web interface footer lists v5.11.1 same as 'pihole -v'
```
/etc/pihole$ pihole -v
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11.1 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```
Debug file: [pihole.debug.txt](https://github.com/pi-hole/pi-hole/files/8249119/pihole.debug.txt)
![Screenshot from 2022-03-14 19-40-17](https://user-images.githubusercontent.com/48958406/158278531-e7931e4b-0587-46a0-833b-33ec347dc542.png)

![Screenshot from 2022-03-14 19-59-57](https://user-images.githubusercontent.com/48958406/158280409-14cbbd24-fde2-466d-ad3a-e36fd3f8eafd.png)

**Comment by dschaper** [comment]
You're not running our web interface.

```plain
*** [ DIAGNOSING ]: Web version
[i] Web: v5.11.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/arevindh/AdminLTE (fetch)
             origin	https://github.com/arevindh/AdminLTE (push)
[i] Branch: master
[i] Commit: v5.11.1-0-g452af648
```

**Comment by XulleX** [comment]
I just found that .. Yes it is modified with the SpeedTest.  I will get that removed and back to native.

Thanks.
