### ISSUE TITLE
Error 500 on HTTPS while browsing non /admin area.

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#4656]
### Versions
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
- OS and version:  Raspbian Bullseye
- Platform:  Raspberry Pi

### Expected behavior

HTTPS using hostname to be working

### Actual behavior / bug

Going to https://raspberrypi gives out an error 500

### Steps to reproduce

Enable SSL on Lighttpd and try the default lighttpd page after installing pihole.

## Debug Token

- URL:  https://tricorder.pi-hole.net/4OQ6tRRo/

### Additional context

Besides the debug log:

```
2022-03-19 17:02:32: mod_openssl.c.3095) SSL: 1 error:1408F09C:SSL routines:ssl3_get_record:http request
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  file(http://127.0.0.1:443/admin/scripts/pi-hole/php/queryads.php?domain=raspberrypi&amp;bp): Failed to open stream: HTTP request failed! in /var/www/html/pihole/index.>
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /var/www/html/pihole/index.php:173
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:#0 /var/www/html/pihole/index.php(173): array_filter()
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:#1 /var/www/html/pihole/index.php(197): queryAds()
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:#2 {main}
2022-03-19 17:02:32: mod_fastcgi.c.487) FastCGI-stderr:  thrown in /var/www/html/pihole/index.php on line 173

```

**By visiting using the IP everything works just fine.**

**Comment by DenyDarko** [comment]
@yubiuser now the 500 error caused by the issue is handled, however the underlying cause is still there:

`[ERROR]: Unable to parse results from queryads.php: Not an array:
(boolean)`

It is caused when browsing https://raspberrypi/

If I go by IP it works.

**Comment by DenyDarko** [comment]
> Can you send over a new debug token please? I'd like to see what ports are being used for the webservers.

 https://tricorder.pi-hole.net/WFHrjhJs/

**Comment by dschaper** [comment]
How have you configured `lighttpd` to be on port 443/TLS? The redirects are sending all the traffic to `https://localhost` and that's going to error unless you have a TLS cert for `localhost`. And that would require a local Certificate Authority to sign it.

```plain
*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 308 Permanent Redirect
Location: https://localhost/
Date: Wed, 23 Mar 2022 18:57:10 GMT
Server: lighttpd/1.4.59

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 308 Permanent Redirect
Location: https://localhost/admin/
Date: Wed, 23 Mar 2022 18:57:10 GMT
Server: lighttpd/1.4.59
```

**Comment by dschaper** [comment]
Also, do you have any configuration files in `/etc/lighttpd/conf-enabled`?

**Comment by DenyDarko** [comment]
> 

I've removed the redirect for localhost:

https://tricorder.pi-hole.net/6oRJBxHR/




> Also, do you have any configuration files in `/etc/lighttpd/conf-enabled`?

Yes but nothing really complicated. Just a few simple ones to run flightaware:

![s1x](https://user-images.githubusercontent.com/3320229/159779474-9bca3955-d7db-4723-9cfd-d2d1a9dbdbb0.png)


Contents of enabled 88-dump1090-fa-statcache.conf:

` The stat cache must be disabled, as aircraft.json changes
# frequently and lighttpd's stat cache often ends up with the
# wrong content length.
server.stat-cache-engine    = "disable"
`

Contents of enabled 89-skyaware.conf:

```
server.modules += ( "mod_alias" )

alias.url += (
  "/skyaware/data/" => "/run/dump1090-fa/",
  "/skyaware/data-978/" => "/run/skyaware978/",
  "/skyaware/" => "/usr/share/skyaware/html/"
)

# redirect the slash-less URL
url.redirect += (
  "^/skyaware$" => "/skyaware/"
)

# Listen on port 8080 and serve the map there, too.
$SERVER["socket"] == ":8080" {
  alias.url += (
    "/data/" => "/run/dump1090-fa/",
    "/data-978/" => "/run/skyaware978/",
    "/" => "/usr/share/skyaware/html/"
  )
}

# Add CORS header
server.modules += ( "mod_setenv" )
$HTTP["url"] =~ "^/skyaware/data/.*\.json$" {
  setenv.set-response-header = ( "Access-Control-Allow-Origin" => "*" )
}
```

**Comment by rdwebdesign** [comment]
```
[✓] Web interface X-Header: X-Pi-hole: The Pi-hole Web interface is working!
```

**Comment by DenyDarko** [comment]
> ```
> [✓] Web interface X-Header: X-Pi-hole: The Pi-hole Web interface is working!
> ```



> Apparently, removing the redirect works.
> 
> Do you still see the same error?

Yes :(

![asvadc](https://user-images.githubusercontent.com/3320229/159781027-8db90fef-dde9-4b91-ab27-30b5eb782328.png)

**Comment by DenyDarko** [comment]
The /admin area works. The /pihole doesn't.

**Comment by dschaper** [comment]
How are you configuring the TLS layer? We don't ship with that and we don't have anything listening on 443 like you do.

**Comment by DenyDarko** [comment]
> How are you configuring the TLS layer? We don't ship with that and we don't have anything listening on 443 like you do.


```

# /usr/share/doc/lighttpd/ssl.txt

server.modules += ( "mod_openssl" )

# ssl.* in global scope gets inherited by
#   $SERVER["socket"] == "..." { ssl.engine = "enable" }

$SERVER["socket"] == ":443" {
        ssl.engine  = "enable"
        ssl.openssl.ssl-conf-cmd = ("Protocol" => "all, -SSLv2, -SSLv3, -TLSv1, -TLSv1.1")
        ssl.pemfile = "/etc/lighttpd/ssl/server.pem"
        ssl.dh-file = "/etc/lighttpd/ssl/dh2048.pem"
        ssl.ec-curve = "secp384r1"

}

include_shell "/usr/share/lighttpd/use-ipv6.pl 443"

$HTTP["scheme"] == "http" {
            $HTTP["remote-ip"] != "127.0.0.1" {
                url.redirect = ("" => "https://${url.authority}${url.path}${qsa}")
                url.redirect-code = 308
        }

}
```

**Comment by dschaper** [comment]
> The /admin area works. The /pihole doesn't.

What are you expecting to see at `/pihole`? 



> ssl.pemfile = "/etc/lighttpd/ssl/server.pem"
>         ssl.dh-file = "/etc/lighttpd/ssl/dh2048.pem"

How did you generate the certificates and what domains are they signed for?

**Comment by DenyDarko** [comment]
> What are you expecting to see at `/pihole`?

The usual thing;

![sdfsfsdsd](https://user-images.githubusercontent.com/3320229/159782009-e4fda319-aa32-4b25-9c3d-1a55067f4d6d.png)

> How did you generate the certificates and what domains are they signed for?

Those are just a simple self-signed certificate. They're generated for SSL to work, thus the red HTTPS.

Here with full FQDN:

![Uploading eafsgdgsdg.png…]()

**Comment by dschaper** [comment]
The only redirects that work for the admin page are `http://pi.hole`. Otherwise you have to use `http://IP/admin/` for the destination.

What you are seeing is the 404 page that is in the form of the Block Page script. That works with IP blocking mode. 

`raspberrypi.fritz.box` won't redirect to `http://IP/admin/` without some external configuration.

**Comment by DenyDarko** [comment]
Without HTTPS, I'm getting another weird result:

![11vasad](https://user-images.githubusercontent.com/3320229/159783511-b552d687-6fea-4f19-b1f8-5e54ba15cf5a.png)

**Comment by dschaper** [comment]
Correct, that is the 404 page that we use as the blockpage. What you are seeing is really a 404.

**Comment by dschaper** [comment]
That page is set with `https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L29`

I'm trying to see if you could do an external configuration file to override that setting and do something like pointing the 404s to `http://IP/admin/` to do your own redirect. Then you should be able to use your TLS config on top.

**Comment by dschaper** [comment]
Something like:

in `external.conf`

```
server.error-handler-404    := "/index.php"
```
@rdwebdesign If you us the AdminLTE index.php as the redirect page, will the different domain names confuse the PHP?

**Comment by rdwebdesign** [comment]
@DenyDarko 

Could you please test the modified code?

https://github.com/pi-hole/pi-hole/blob/f8e84b3c3f7031eaef1e2e72a03bbdda8a1e1b92/advanced/index.php#L168-L194

**Comment by DenyDarko** [comment]
@rdwebdesign now the error.log is slightly different:

`

2022-03-24 11:11:49: server.c.1513) server started (lighttpd/1.4.59)
2022-03-24 11:11:56: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  file(): SSL operation failed with code 1. OpenSSL Error messages:
2022-03-24 11:11:56: mod_fastcgi.c.487) FastCGI-stderr:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/pihole/index.php on line 186
2022-03-24 11:11:56: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  file(): Failed to enable crypto in /var/www/html/pihole/index.php on line 186
2022-03-24 11:11:56: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  file(https://127.0.0.1:443/admin/scripts/pi-hole/php/queryads.php?domain=raspberrypi&amp;bp): Failed to open stream: operation failed in /var/www/h>

`

The webpage remains the same:

`

[ERROR]: Unable to parse results from queryads.php:
(boolean)

`

I've also generated a new certificate with all the possible (and impossible) alt names needed:

[server.zip](https://github.com/pi-hole/pi-hole/files/8340095/server.zip)

Anything else works just fine. It's just pihole popping up this error.

**Comment by DenyDarko** [comment]
Finally.
![asdsfas](https://user-images.githubusercontent.com/3320229/159988199-7edd455a-176c-44df-a02d-db6a48767e57.png)

What did the trick was a combination of what @dschaper suggested and a configuration file I've created:



```
$HTTP["host"] == "raspberrypi.fritz.box" {
        setenv.add-environment = ("fqdn" => "true")
       server.document-root = "/var/www/html"
}

$HTTP["host"] == "raspberrypi" {
        setenv.add-environment = ("fqdn" => "true")
       server.document-root = "/var/www/html"
}
```

Documentation material maybe?

**Comment by dschaper** [comment]
> Documentation material maybe?

Possibly, the one thing that I don't like is the self-signed CA. We discussed using them in the past but CAs like that can be dangerous if they are not well secured. In this case though, you're not installing the CA on users computers, just adding it to the server. 

Did you have to make any exceptions for the browser to work with that address and certificate?

**Comment by DenyDarko** [comment]
> > Documentation material maybe?
> 
> Possibly, the one thing that I don't like is the self-signed CA. We discussed using them in the past but CAs like that can be dangerous if they are not well secured. In this case though, you're not installing the CA on users computers, just adding it to the server.
> 
> Did you have to make any exceptions for the browser to work with that address and certificate?

Not really. Nothing.

I mean I can install the certificate to the root store of my clients to get rid of the red https but it doesn't really matter.

**Comment by immanuelfodor** [comment]
For me the protocol detection (https://github.com/pi-hole/pi-hole/issues/4656#issuecomment-1076864684) broke the PiHole page with the same `(boolean)` error as in https://github.com/pi-hole/pi-hole/issues/4656#issuecomment-1076741812

The fix was to explicitly pass down `http` in the forwarded proto header from Nginx (another host) to trick lighthttpd not to try to connect to localhost in the PiHole VM with SSL enabled (which is only available in the reverse proxy VM). 

```diff
diff --git a/sites-available/pihole b/sites-available/pihole
index 9ebc5e1..a55149b 100644
--- a/sites-available/pihole
+++ b/sites-available/pihole
@@ -57,5 +57,11 @@ server {
         proxy_pass http://192.168.1.3:80;
 
         include /etc/nginx/snippets/proxy.conf;
+
+        # Fix PiHole error caused by passing down the https scheme by default in proxy.conf
+        # @see: https://github.com/pi-hole/pi-hole/pull/4659
+        # @see: https://github.com/pi-hole/pi-hole/commit/c9809371abf89efe4f39c25170773eb2a5f39929#diff-90be1003be891f4d6008bf3a167ceedcbc3e06dbf48e490c6bc761eef20ea96bR173
+        # @see: https://github.com/pi-hole/pi-hole/issues/4656
+        proxy_set_header X-Forwarded-Proto http;
     }
 }
```

Here is the evidence in /var/log/lighttpd/error.log that it tried to query localhost on https before:

```
   2022-04-21 20:03:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  file(): SSL: Handshake timed out in /var/www/html/pihole/index.php on line 186
   2022-04-21 20:03:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  file(): Failed to enable crypto in /var/www/html/pihole/index.php on line 186
   2022-04-21 20:03:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  file(https://127.0.0.1:80/admin/scripts/pi-hole/php/queryads.php?domain=XXXXXXX&amp;bp): failed to open stream: operation failed in /var/www/html/pihole/index.php on line 186
```

With the proto header trick it works again fine just as before https://github.com/pi-hole/pi-hole/pull/4659

**Comment by cun83** [comment]
For Traefik users: this fixed the issue for me:

* Option 1 - restores the default error page when accessing pihole /:
```
labels:
  - "traefik.http.routers.pihole.middlewares=pihole-headers"
  - "traefik.http.middlewares.pihole-headers.headers.customrequestheaders.X-Forwarded-Proto=http"
  - "traefik.http.middlewares.pihole-headers.headers.customrequestheaders.Host=pi.hole"
```

* Option 2: Redirect from / to /admin as expected, when using your FQDN proxied by Traefik
```
labels:
  - "traefik.http.routers.pihole.middlewares=pihole-headers"
  - "traefik.http.middlewares.pihole-headers.headers.customrequestheaders.Host=pi.hole"
```
