### ISSUE TITLE
Cannot delete unwanted name servers

### ISSUE THREAD

**Issue by robdyck** [pi-hole/pi-hole#4658]
### Versions

- Pi-hole:  version is v5.5 (Latest: v5.9)
- AdminLTE:  version is v5.7 (Latest: v5.11)
- FTL:  is v5.14-2-g53bff37a (Latest: v5.14)

### Platform

- OS and version:  
- Linux slim.mylan 5.16.14-200.fc35.x86_64 
Fedora 35

- Platform: Desktop

### Expected behavior

When deleting unwanted name servers and adding new ones only the new ones should remain.

### Actual behavior / bug

After updating the name servers, deleting the unwanted name servers  and clicking on save in the DNS page everthing looks OK. However the pihole logs show that queries are forwarded to both the new and also the unwanted name servers

### Steps to reproduce

Delete unwanted name servers. Add new name servers.

## Debug Token

- URL:  [✓] Your debug token is: https://tricorder.pi-hole.net/wim5hft4rq

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

After setting up pihole to use OpenDNS name servers I realized that I did not want the "Umbrella" set but rather the "FamilyShield" set. Deleting the ipv4 and ipv6 Umbrella name servers using the GUI DNS page did not work and pihole circulated through all six name servers. After making a backup copy of dns-servers.conf I edited the original and deleted the line that listed the OpenDNS servers. I restarted pihole. Checking the logs I see that pihole is using only the "FamilShield" name servers.
Happy now

**Comment by yubiuser** [comment]
> Deleting the ipv4 and ipv6 Umbrella name servers using the GUI DNS page

Where in the GUI did you try to delete the DNS server?. There is no way to delete them from the GUI.

>  dns-servers.conf I edited the original and deleted the line that listed the OpenDNS servers.

You should not edit that file by hand. It's likely that it will be re-written at each update.
If you want to use an other DNS server than those listed in the GUI you can set their IP address in the "Custom" Upstream DNS server field

**Comment by danielmellado** [comment]
I'm seeing the same behavior on this versions
```$ pihole -v
  Pi-hole version is v5.11 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```
Whenever I add/delete dns entries I've found that the 01-pihole.conf file for dnsmasq is not deleting previous ones and just stacking.

**Comment by yubiuser** [comment]
Just to clarify here: both of you mean "unticking" when you write "deleting" DNS servers from the web GUI?

**Comment by yubiuser** [comment]
>   Pi-hole version is v5.11 (Latest: v5.9)

Something is wrong with your local installation.

**Comment by danielmellado** [comment]
At least I do, i.e settings/dns on the web GUI.

But that doesn't seem to be reflecting on the pihole dnsmasq file

```
addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list
localise-queries
no-resolv
cache-size=10000
log-queries
log-facility=/run/log/pihole/pihole.log
local-ttl=2
log-async
# If a DHCP client claims that its name is "wpad", ignore that.
# This fixes a security hole. see CERT Vulnerability VU#598349
dhcp-name-match=set:wpad-ignore,wpad
dhcp-ignore-names=tag:wpad-ignore
domain-needed
expand-hosts
bogus-priv
local-service
rev-server=192.168.1.0/24,192.168.1.1
server=/lcg.lan/192.168.1.1
server=1.1.1.1
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
local-service
rev-server=192.168.1.0/24,192.168.1.1
server=/lcg.lan/192.168.1.1
server=127.0.0.1#5335
server=1.0.0.1
domain-needed
expand-hosts
bogus-priv
local-service
rev-server=192.168.1.0/24,192.168.1.1
server=/lcg.lan/192.168.1.1
server=1.1.1.1
server=1.0.0.1
server=127.0.0.1#5335
domain-needed
expand-hosts
bogus-priv
```

**Comment by danielmellado** [comment]
> Something is wrong with your local installation.

I installed it from AUR package => https://aur.archlinux.org/packages/pi-hole-server

**Comment by yubiuser** [comment]
Please generate a debug token.

**Comment by yubiuser** [comment]
Arch is a unsopported OS. Please get in touch with the Arch maintainers of that package.

https://wiki.archlinux.org/title/Pi-hole

> Note: Pi-hole on Arch Linux is not officially supported by the Pi-hole project.

**Comment by danielmellado** [comment]
Oh, I see, thanks in any case!

**Comment by yubiuser** [comment]
>Pi-hole: version is v5.5 (Latest: v5.9)
AdminLTE: version is v5.7 (Latest: v5.11)
FTL: is v5.14-2-g53bff37a (Latest: v5.14)

Your version is quite out of date for the Pi-hole and AdminLTE version. Please upgrade and see if the issue persists.

**Comment by danielmellado** [comment]
FYI I filled this on arch, thanks! https://aur.archlinux.org/packages/pi-hole-server#comment-857952
