### ISSUE TITLE
gravity.sh not reloading dnsmasq

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#466]
from @PombeirP on [gitter](https://gitter.im/pi-hole/pi-hole)

>Hi guys. I'm new to Linux, but while using pihole on my QNAP NAS, I noticed that the syntax for the kill command is different than the one in the gravity.sh script:
gravity.sh:
`$SUDO kill -HUP "$dnsmasqPid"`
syntax for my box:
`$SUDO kill -s HUP "$dnsmasqPid"`

>I'm using TurnKey GNU/Linux 14.0 / Debian 8.4 Jessie

**Comment by PromoFaux** [comment]
@pi-hole/gravity - from reading the `man` page of `kill`, it seems we'd be safe to add the `-s` switch (tested on my server and my pi3)

 Can someone test the the command `sudo kill -s HUP $(pidof dnsmasq)` on other flavours of linux?

**Comment by CDeeRON** [comment]
CMD did not work on CHIP `Linux chip 4.3.0 #10 SMP Sat Nov 14`

**Comment by PromoFaux** [comment]
Thanks @CDeeRON!

Actually, forgot to update... started working for @PombeirP in the end!

**Comment by PromoFaux** [comment]
@CDeeRON can you try `sudo killall -s HUP dnsmasq` on your CHIP, please?

**Comment by CDeeRON** [comment]
`root@chip:/var/www/html/admin# pgrep dnsmasq
8278
root@chip:/var/www/html/admin# sudo killall -s HUP dnsmasq
root@chip:/var/www/html/admin# pgrep dnsmasq
8278
`

**Comment by PromoFaux** [comment]
OK, that's promising. Can you `tail -f /var/log/pihole.log | grep read` and run the killall command again please.

**Comment by CDeeRON** [comment]
`
Apr 16 10:41:01 dnsmasq[8278]: read /etc/pihole/gravity.list - 2338440 addresses
Apr 16 10:41:05 dnsmasq[8278]: read /etc/hosts - 6 addresses
`

**Comment by PromoFaux** [comment]
(Friendly hint, use 3* ` when pasting in a block of code - then i don't have to keep editing your posts :P) 

And yes, great! That was what I was hoping to see!

**Comment by CDeeRON** [comment]
haha thanks for the tip

```
Apr 16 10:41:01 dnsmasq[8278]: read /etc/pihole/gravity.list - 2338440 addresses
Apr 16 10:41:05 dnsmasq[8278]: read /etc/hosts - 6 addresses
```
