### ISSUE TITLE
No Blocklists page available

### ISSUE THREAD

**Issue by boondoggler** [pi-hole/pi-hole#4662]
Pi-hole version is v5.9 (Latest: v5.9)
 AdminLTE version is v5.11 (Latest: v5.11)
 FTL version is v5.14 (Latest: v5.14)

Linux raspberrypi 4.19.66-v7+ 1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Expected behaviour:

I would expect the blocklists section to be available, I used to see it, has it moved or just plain vanished?

Actual behaviour/bug:

The Blocklists tab is missing from settings. Has been for a while.

Steps to reproduce the behaviour:

1. Go to Settings
2. No Blocklists

![blocklists](https://user-images.githubusercontent.com/9357356/160417048-77c08ee6-6d73-46e9-8c1b-a8ec7051f9ae.png)

**Comment by jfb-pihole** [comment]
The adlists (blocklists) are now in the Group management tab.

**Comment by boondoggler** [comment]
Thanks!
