### ISSUE TITLE
Pi-Hole has stopped blocking queries, accepts all

### ISSUE THREAD

**Issue by nfrelink** [pi-hole/pi-hole#4666]
### Versions

- Pi-hole:  v5.9 (Latest: v5.9)
- AdminLTE:  v5.11 (Latest: v5.11)
- FTL:  v5.14 (Latest: v5.14)

### Platform

- OS and version:  Rocky Linux 8.5 (CentOS 8)

- Platform:  VPS

### Expected behavior

Pi-hole to continue blocking queries as it has always done.

### Actual behavior / bug

Pi-hole has stopped blocking queries since 2022-03-14 21:33:03 CET. I cannot figure out what happend that day, maybe an update of pi-hole.

### Steps to reproduce

1. Install Pi-hole on a VPS.
2. Let it run without issue for a while.
3. Notice that ads are no longer being blocked.

## Debug Token

- URL:  https://tricorder.pi-hole.net/2eJjENw6/

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/35900272/161281647-03b7737b-1c67-43c6-954e-a153e6466c2b.png)

### Additional context

I have a second pi-hole server, also on a VPS, with the exact same problems.

**Comment by jfb-pihole** [comment]
You have several problems in your setup:

```
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  0
[i] dig response:  "Raspbian=9,10,11 Ubuntu=16,18,20,21 Debian=9,10,11 Fedora=33,34 CentOS=7,8"
[✗] Distro:  Rocky
[✗] Error: Rocky is not a supported distro (https://docs.pi-hole.net/main/prerequisites/)

*** [ DIAGNOSING ]: SELinux
[✓] Default SELinux: disabled
[✓] Current SELinux: Disabled

*** [ DIAGNOSING ]: FirewallD
[i] Firewalld service active
[✗]   Allow Service: http (https://docs.pi-hole.net/main/prerequisites/#firewalld)
[✗]   Allow Service: dns (https://docs.pi-hole.net/main/prerequisites/#firewalld)
[✓]   Allow Service: dhcp
[✓]   Allow Service: dhcpv6
[✗] FTL Custom Zone Not Detected (https://docs.pi-hole.net/main/prerequisites/#firewalld)
```

**Comment by jfb-pihole** [comment]
Check your adlist group assignments.  Your debug log shows that none of your adlists are assigned to the default group:
```
*** [ DIAGNOSING ]: Adlists
   id     enabled  group_ids     address                                                                                                 date_added           date_modified        comment                                           
   -----  -------  ------------  ------------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   190          1                https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt                              2021-05-01 12:48:18  2021-12-13 22:04:59                                                    
   191          1                https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt                  2021-05-01 12:48:18  2021-12-13 22:04:59            
...
```

**Comment by nfrelink** [comment]
Huge oversight on my part for not checking that, my apologies. Thanks for
the quick response.
I can confirm that after changing this, ads are being blocked again.

This doesn't seem to be a widespread problem, so I will close this issue.

Thank you for your help. It's much appreciated.


Op vr 1 apr. 2022 17:41 schreef jfb-pihole ***@***.***>:
