### ISSUE TITLE
Whitelisted site still blocks

### ISSUE THREAD

**Issue by mash8336** [pi-hole/pi-hole#4676]
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"

Model: Raspberry Pi Zero Rev 1.3

### Expected behavior
Whitelisted site should be permitted: r20.rs6.net

### Actual behavior / bug
Whitelisted site still being blocked: r20.rs6.net

### Steps to reproduce
This should redirect:
https://r20.rs6.net/tn.jsp?f=001l9vULjYu0BQSAyXcsgGtccEMT6GFvJlbrj_uB0kNR89kSHJFyXHenuPg13Ii4reTPaP-kFZcCvV4OnJyH58sOyyS875tXWzYYCkAWHJr-1UqfurfOEdkIPb8rKVk7tm7XZqZA08pd1qWxa6vuU1Ezi7oCjPQf-0pzklRhR85MIVOJUs2Lx_OJwPkbtvnE-m44Ot8SfnwkB5Cp4FxCYXv0cqWkqu7YQ2Znro-AeCO_HY=&c=4jYMGf5oSqUfydJl7gQyNvTKjpRgzGN6X1lM1lkfgbJi7BdAqDEeNw==&ch=zYDC-m1YZqw6vrEpLSmt90kPvMWeRhtPyeXNHX1KJa1-5UVC2YHfUA==

## Debug Token
https://tricorder.pi-hole.net/Lfpdbjx5/

### Screenshots
n/a

### Additional context
n/a

**Comment by yubiuser** [comment]
You have ` r20.rs6.net` assigned as a whitelist entry to the default group only. Additionally, you configured two clients, of which neither is in your default group. If you try to open that domain from one of those clients, the whitelist entry will have no effect.

**Comment by mash8336** [comment]
Doh, I should have poked around more! I've now found the group assignment area and it works as expected.

Many thanks...
