### ISSUE TITLE
Blacklisted entries being answered from Pihole

### ISSUE THREAD

**Issue by Feathered-Serpent** [pi-hole/pi-hole#4688]
### Versions

- Pi-hole:  v5.9.1
- AdminLTE:  v5.11
- FTL:  v5.14

### Platform

- OS and version:  Windows 10

- Platform:  Raspberry Pi

### Expected behavior
Hostnames are resolved to 0.0.0.0/127.0.0.1

### Actual behavior / bug
Hostnames either from adlists or from the blacklist are answered and can be opened in the browser.

E.g. admez.com from [MVPS](https://winhelp2002.mvps.org/hosts.txt):
from my computer:
```
nslookup admez.com
Server:  pi.hole
Address:  192.168.178.58

Non-authoritative answer:
Name:    admez.com
Address:  13.248.216.40
```

from pihole itself:
```
pi@raspberrypi:~ $ nslookup admez.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   admez.com
Address: 76.223.65.111
Name:   admez.com
Address: 13.248.216.40
```

I totally don't understand what's going on. Tools -> Network on the GUI tells me, my computer is using Pi Hole. And I defintely know that it worked before. But now even if I explicitely put the domain on the blacklist via the query window, it still gets answered.
I'm using https://bartonbytes.com/posts/configure-pi-hole-for-dns-over-tls/ ever since, and never changed anything on the configuration.

I hope someone can shed some light onto my confusion, because right now Pihole isn't filtering anything from my computer.

### Steps to reproduce
I don't know how to tell to reproduce but just use nslookup.

## Debug Token

- URL:   https://tricorder.pi-hole.net/iX7hA7vz/

### Screenshots
query window:

![example](https://user-images.githubusercontent.com/72162369/162501986-97985f9e-abb5-4fa9-a8f7-a47c9af8ff8d.png)

**Comment by dschaper** [comment]
It looks like there is some blocking going on:

```plain
   Apr  8 20:33:15 dnsmasq[735]: query[A] www.kotentomatow.xyz from 127.0.0.1
   Apr  8 20:33:15 dnsmasq[735]: forwarded www.kotentomatow.xyz to 127.0.0.1#5533
   Apr  8 20:33:17 dnsmasq[735]: reply error is SERVFAIL
   Apr  8 20:33:17 dnsmasq[735]: query[A] www.kotentomatow.xyz from 192.168.178.58
   Apr  8 20:33:17 dnsmasq[735]: gravity blocked www.kotentomatow.xyz is 0.0.0.0
```

But that is coming from the Pi-hole host itself and we don't suggest that as a configuration. You may have the old `/etc/dhcpcd.conf` or `/etc/resolv.conf` that set Pi-hole's DNS to 127.0.0.1. You should change that to a remote upstream. The reason we changed was that if Pi-hole is using itself and it's down then there's no way to repair or update.

I don't see the MVP list in your list of adlists, but that may be another issue if you are not seeing any blocks happening since that test domain is on the StevenBlack list. 

Can you look up that domain on a client and capture the relevant entries from `/var/log/pihole.log`  please?

**Comment by Feathered-Serpent** [comment]
The MVPS list is to be found in the GUI:
![mvps](https://user-images.githubusercontent.com/72162369/162509443-2a960080-f98a-4aab-8b7b-6d70659e8597.png)

And do you mean to look up www.kotentomatow.xyz? My computer tells me:
```
Server:  pi.hole
Address:  192.168.178.58

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Zeitüberschreitung bei Anforderung an pi.hole.
```

Pihole GUI tells:
![kotento](https://user-images.githubusercontent.com/72162369/162509840-6783e2c6-3f49-43d2-b4f4-63de85a1e379.png)

I only have noticed today, that there is an unbound configuration to be found at https://docs.pi-hole.net/guides/dns/unbound/ would that make any difference if I use the unbound config from there? 

I also just made another test:
![github](https://user-images.githubusercontent.com/72162369/162510211-e5773f08-41e4-43a7-85a5-1917d67cafbd.png)

But I can still open the github page. The query log for that is:
![github2](https://user-images.githubusercontent.com/72162369/162510240-ede00e0e-1cf7-4c09-9c95-0f82f057a0ff.png)

**Comment by Feathered-Serpent** [comment]
Ok something is off here.... I just tried to open Github from my cellphone. There it gets blocked, but not from my computer where I tried it immediately afterwards:
![blocked](https://user-images.githubusercontent.com/72162369/162512718-6e6f95b4-2acb-4e1b-98c4-9abb26552cdd.png)

**Comment by PromoFaux** [comment]
I might be reading this entirely wrong, but according to your debug log - your PC is set up as a client, but not assigned to any groups - it should be at least in the default group, else the blocklists will not apply to it

```txt
*** [ DIAGNOSING ]: Clients
   id    group_ids     ip                                                                                                    date_added           date_modified        comment                                           
   ----  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   2                   192.168.178.43                                                                                        2020-10-20 09:50:26  2020-11-07 10:53:47  PC                                                
```

**Comment by Feathered-Serpent** [comment]
Huh, according to the GUI none of my clients is assigned to any group. The group assignment is all set to "none selected".

Interestingly, my cellphone is not even listed there (at Group Management -> Clients I mean).

Let me change this...

I removed all clients and readded them. They were automatically in the Default group now. And... the blocking works again.

I ensure you, that I don't remember ever changing something inside there.

**Comment by Feathered-Serpent** [comment]
Thanks alot for your quick help! Case closed! :)
