### ISSUE TITLE
im very confused looking for help and understanding 

### ISSUE THREAD

**Issue by lawrence1986101** [pi-hole/pi-hole#4689]
im very confused. im still really new to pi-hole but I have used it for about 3 to 4 ish years I never had any issues ever.  I have pi-hole on my unraid server. im having 1 or 2 issues the first issue is 1) Pi-hole isn't blocking anything I have a total of queries of like 3k and Queries blocked is 0 percentage block nothing and domains on add list is -2 there are Quite a few of ad list  like 4 or 5 from wally 3k secord problem is any time I try to upgrade my Gravity list I get these   [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available. I am using a presence and I have the DNS set right in the firewall. witch, I know it working half-axx. to the point, if i stop piehole in my unraid server it won't allow me to get on the internet I have to delete the DNS in the firewall and restart my computer for it to allow me back on so something is happening

**Comment by jfb-pihole** [comment]
Please open a help topic on our discourse page. We can help you more effectively in that forum.

https://discourse.pi-hole.net/

**Comment by lawrence1986101** [comment]
Just Delete my post because yall are a day late dollar short I needed internet and I needed it now so I deleted pi-hole if yall can solve and fix my issue if people dont want to waste their time so be it because I didn't
