### ISSUE TITLE
Request - Temperature Monitor to Chronometer.sh

### ISSUE THREAD

**Issue by Interknet** [pi-hole/pi-hole#470]
Could be a good feature to display temperature on their LCD screens. 

Here's what I used in the Chronometer.sh

echo "CPU Temp = $(/opt/vc/bin/vcgencmd measure_temp| egrep "[0-9.]{4,}" -o)" "C"

Side note: Surprising how little cpu usage, power, etc PiHole takes. Glad I got it up and running finally.

**Comment by Mcat12** [comment]
It would certainly be nice, if someone's curious about their temp.

**Comment by dschaper** [comment]
I'm guessing this is for a Pi 3 install? I've seen a lot of posts on the Raspberry Forums about thermal issues with the 3, all the other variants of PI's can run very will with no thermal mitigation (no fan, no heatsink) as they are rated to go to 80C...

**Comment by dschaper** [comment]
This is now in development branch.
