### ISSUE TITLE
problem with gravity entries with trailing period

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/pi-hole#4701]
### Versions
  Pi-hole version is v5.9.1 (Latest: v5.9.1)
  AdminLTE version is v5.11 (Latest: v5.10.1)
  FTL version is v5.14 (Latest: v5.14)

### Platform
uname -a: Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
Raspberry Pi OS Lite, Release date: April 4th 2022

### Expected behavior

I have a number of entries in the gravity database (2213) with a trailing period, example:
**mail.forblown.pl.**

I would expect pihole to block both **mail.forblown.pl.** (trailing period) and **mail.forblown.pl** (no trailing period)

pihole -q reports:
without trailing period: pihole -q mail.forblown.pl
 Match found in https://dbl.oisd.nl:
   mail.forblown.pl.
with trailng period: pihole -q mail.forblown.pl.
 Match found in https://dbl.oisd.nl:
   mail.forblown.pl.

this list changes frequently, so the entry may no longer be there, however, again, I have 2213 entries with a trailing period in the gravity table.

I would expect dig +short **mail.forblown.pl.** and dig +short **mail.forblown.pl** to report 0.0.0.0

### Actual behavior / bug

dig +short  **mail.forblown.pl.** and dig +short  **mail.forblown.pl** report 31.31.72.43 (the actual address)

### Steps to reproduce

1. ensure you have the entry **mail.forblown.pl.** (with trailing period) in the gravity database
2. run pihole -q on both **mail.forblown.pl** and **mail.forblown.pl.**
3. run dig on both **mail.forblown.pl** and **mail.forblown.pl.**

## Debug Token

debug token is: https://tricorder.pi-hole.net/FuKy6tcC/

### Additional context

removing the trailing period from the entry in the gravity database (and restarting pihole-FTL) fixes the problem.
NOT sure what is the most efficient solution:
- modify gravity.sh to always remove trailing periods.
- modify pihole-FTL.

**Comment by DL6ER** [comment]
Interestingly enough, I have no list with such domains myself:
``` bash
pihole-FTL sqlite3 /etc/pihole/gravity.db
```
``` sql
SELECT COUNT(*) FROM gravity;
187530

SELECT COUNT(*) FROM gravity WHERE domain LIKE '%.';
0
```

**Comment by jpgpi250** [comment]
doesn't mean it isn't happening, apparently, some lists do have such entries. Not sure, I think I remember this (trailing period) is the correct way to reference a domain, but they made it user friendly, the trailing period is usually (hardly ever) not a requirement.

![2022-04-18 12_48_22-phpLiteAdmin](https://user-images.githubusercontent.com/24669386/163798751-e2188c42-a88d-4d83-825b-8cfedd21bf23.png)

**Comment by jpgpi250** [comment]
some entries in (example) list: https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt, however this list has both entries (with, without trailing period, so you will not notice the problem (result = 0.0.0.0)

**Comment by DL6ER** [comment]
> doesn't mean it isn't happening

Sure, this is not what I meant. What I said was more why we didn't see it ourselves. I don't think anyone from the core team is running their Pi-hole with a obsquamatillion domains ;-)

What isn't clear to me from your original post above: Do you want to submit a PR against gravity or do you want to wait until er find the time to do this?

**Comment by jpgpi250** [comment]
gravity is dangerous...

according to [this](https://sed.js.org/)

replacing line 531
from: sed -e "/[^a-zA-Z0-9.\_-]/d;s/$/,${adlistID}/;/.$/a\\" "${src}" >> "${target}"
into: sed -e "'/[^a-zA-Z0-9.\_-]/d;s/\.$//;s/$/,${adlistID}/;/.$/a\\'" "${src}" >> "${target}"

should do the trick (added ;s/\.$//)

before:
![2022-04-18 15_04_53-GNU sed live editor](https://user-images.githubusercontent.com/24669386/163812527-e37726cd-4ac4-4022-8e04-8fc4f6e8600e.png)

after:
![2022-04-18 15_07_29-GNU sed live editor](https://user-images.githubusercontent.com/24669386/163812804-c4fea7bd-f6a2-4877-a2d1-dfba84d0d1a9.png)

the results appear to be ok, however, there are duplicates (depends on the content of the list)

execution time (time pihole -g) - lots of lists (55):
before (2.386.696 unique domains - gravity table contains 3.098.824 entries - 2214 domains with trailing period):
real    4m39.236s
user    2m55.683s
sys     0m21.521s

after: (2.386.169 unique domains - gravity table contains 3.098.820 entries - 0 domains with trailing period)
real    4m37.648s
user    2m57.822s
sys     0m21.164s

i'm happy to try to make the PR, provided the above change is approved by the majority of the developers.
remeber I only have raspian (latest - april 4th 2022) 32 bit to test. No idea how / if this will work on other platforms...

**Comment by DL6ER** [comment]
Please also test you modified sed on domains without a trailing period. When you see something odd, try `\.$` instead of `.$`

**Comment by jpgpi250** [comment]
if you look at the screenshots, you'll notice some duplicate entries, once with and once without a trailing period. The result, using the modified sed is simply a duplicate (identical entry).

**Comment by jpgpi250** [comment]
- if both entries exist, everything is fine.
- if the **entry with the trailing dot exists** AND the **entry without the trailing dot doesn't exist**, the domain will be allowed, e.g. **mail.forblown.pl** will return the real IP, **mail.forblown.pl.** will return 0.0.0.0.

in the real world, I have seldom seen a client make a request with a trailing dot.

note that dig will always return a domain name with a trailing dot (example: **dig +short -x 8.8.8.8** will return **dns.google.** (trailing period)

**Comment by DL6ER** [comment]
@jpgpi250 Sorry, what I meant above is that `.` is the wildcard character so I expect it to match *and remove* **any** (not only periods) characters at the end of domains.

Example to make this even more clear:
``` bash
$ echo "test.de." | sed -e "s/.$//"
test.de # OKAY

$ echo "test.de" | sed -e "s/.$//"
test.d # TRUNCATED
```
whereas this doesn't happen with my suggestion:
```
$ echo "test.de." | sed -e "s/\.$//"
test.de # OKAY

$ echo "test.de" | sed -e "s/\.$//"
test.de # OKAY
```

Please check again that you haven't created such truncated domains in your test gravity database.

---

> note that dig will always return a domain name with a trailing dot (example: dig +short -x 8.8.8.8 will return dns.google. (trailing period)

PTR replies are special. The trailing period is correct/should be there are it signals the root domain, however, it is commonly ignored. FTL traps into this pitfall because it does (lot simpler) full string instead of per-segment domain comparisons.

I think it'd be a fair compromise to fix this automatically in gravity runs (for externally provided lists) but still have the same behavior with manually added domains (`domainlist`). I haven't seen any complains for manually added domains ending in `.` over the past years where things already worked the very same way they are right now in Pi-hole.

**Comment by jpgpi250** [comment]
I would prefer that somebody (or multiple people) test the proposed changed line (531), prior to making the PR. gravity is dangerous, one mistake can kill pihole...

**Comment by yubiuser** [comment]
Can you please update the RegEx in the text to match the one in the screenshot?

**Comment by jpgpi250** [comment]
done, a github text display problem need to enter '\\\\' to show a '\\'

PS I've been using the modified gravity.sh all day, ran pihole -g at least 5 times, compared the output (database entries) from the StevenBlack list with the source (/etc/pihole/list.1.raw.githubusercontent.com.domains) and found no problems.

**Comment by yubiuser** [comment]
Maybe we should use 
`/[^a-zA-Z0-9.\_-]/d;s/\.*$//;s/$/,${adlistID}/;/.$/a\\`

which adds a `*` - **one ore more** trailing dots

**Comment by jpgpi250** [comment]
running with initial proposal (remove single trailing dot):  Number of gravity domains: 3029345 (2317668 unique domains)
execution time (don't compare the time with earlier posts, I've added some read only queries to gravity.sh for another test):
real    5m35.942s
user    3m17.184s
sys     0m27.034s

running with your proposal (remove all trailing dots):  Number of gravity domains: 3029341 (2317668 unique domains)
execution time:
real    6m16.623s
user    3m40.497s
sys     0m26.853s

result (GNU sed live editor:
![2022-04-19 15_59_34-GNU sed live editor](https://user-images.githubusercontent.com/24669386/164022045-08221392-7ca1-4df7-b6b7-381344a9c3d0.png)

toughts:
- the result is identical.
- ran the time check multiple times, the diff remains arround 45 seconds.
- a domain with a single trailing dot is a valid domain
- a domain with two or more trailing dots isn't (example dig: 'google.be..' is not a legal name (empty label)). This maybe the result of a faulty list generator (TLD missing), the result after removing dot(s) is useless anyway.
- DL6ER has no domains (lists) with trailng dots, I have several (2214 before my change), I have zero entries with 2 trailing dots.

It's up to you (the developers) people to make the final decision

**Comment by jpgpi250** [comment]
PR created (hopefully in the correct way), see https://github.com/pi-hole/pi-hole/pull/4704

please note I have only tested this on the latest raspbian bullseye (april 4th 2022). additional tests before merging would be greatly appriciated
![2022-04-20-Update gravity sh by jpgpi250](https://user-images.githubusercontent.com/24669386/164187785-34adf391-400b-4d85-8b62-aae4965c7b06.png)
.

**Comment by jpgpi250** [comment]
merged by yubiuser into development, branch deleted, issue closed
