### ISSUE TITLE
Whitlist do not work

### ISSUE THREAD

**Issue by shedderrich** [pi-hole/pi-hole#4702]
### Versions

- Pi-hole:  v5.9.1 (Latest: v5.9.1)
- AdminLTE:   AdminLTE version is v5.11 (Latest: v5.11)
- FTL:  v5.14 (Latest: v5.14)

### Platform

- OS and version:   Debian GNU/Linux 11 (bullseye)

- Platform:  Raspberry Pi

### Expected behavior

I whitelist a website and its unblock and i am able to acess it 

### Actual behavior / bug

Its still blocked, cant acess the website

### Steps to reproduce

1. Find a website that is in your Adlist
2. Add it to the whitelist (i tried adding to the whitlist via GUI or via SSH)
3. See that the website is still blocked 

## Debug Token

- URL:  https://tricorder.pi-hole.net/Vy8muD6X/

### Screenshots

![grafik](https://user-images.githubusercontent.com/29237810/163870542-49e47d0b-6ed3-428e-8fe5-49331d483d68.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Please note: `office.net` and `www.office.net` are two different domains.
__

The issue here is not with Pi-hole but with the authoritative DNS server: `www.office.net` is a CNAME for `microsoftoffice.com.` wihich does not resolve to any `A` record.


```
dig www.office.net

; <<>> DiG 9.18.1-1+ubuntu18.04.1+isc+1-Ubuntu <<>> www.office.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23593
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;www.office.net.			IN	A

;; ANSWER SECTION:
www.office.net.		3600	IN	CNAME	microsoftoffice.com.

;; AUTHORITY SECTION:
microsoftoffice.com.	300	IN	SOA	ns1-04.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300

;; Query time: 152 msec
;; SERVER: 10.0.1.5#53(10.0.1.5) (UDP)
;; WHEN: Mon Apr 18 22:14:50 CEST 2022
;; MSG SIZE  rcvd: 159
```

**Comment by shedderrich** [comment]
It does not work with any website, i get what you say but its not just office.net its every website that is blocked
The whitlist does nothing

**Comment by dschaper** [comment]
You've applied the whitelist entries to the default group but all of your clients are in group 2.
