### ISSUE TITLE
Disk shortage on a 32gb sd card

### ISSUE THREAD

**Issue by hyperactive68** [pi-hole/pi-hole#4703]
### Versions

  Pi-hole version is v5.9.1 (Latest: v5.9.1)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
Armbian 22.02.1  with Linux 5.15.25-sunxi running on an Orange Pi Zero H2+

### Expected behavior

_The log file shouldn't be limited to only 52,4mb while there is 30gb of space left._

### Actual behavior / bug

_Error message: Disk shortage (/var/log/pihole-FTL.log) ahead: 99% used
/var/log: 52.4MB used, 52.4MB total_

### Steps to reproduce

1. Use pi-hole normally
2. See triangle with exclamation mark in web interface and click on it
3. See aforementioned error

## Debug Token

- URL:  https://tricorder.pi-hole.net/whroarr3/

### Additional context

_I have seen in another post that Zram is the problem. I disabled zram by going to /etc/default/armbian-zram-config and changing the line to ENABLED=false , but the problem still exists. I'm not a Linux guru. I only used it to set up pi-hole, so bear with me please._

**Comment by yubiuser** [comment]
As you said, this is an OS level issue. Your device still uses the ramlog and assigned only 50MB to `/var/log`


```
*** [ DIAGNOSING ]: Disk usage
   Filesystem      Size  Used Avail Use% Mounted on
   udev            189M     0  189M   0% /dev
   tmpfs            50M  5.6M   44M  12% /run
   /dev/mmcblk0p1   29G  1.7G   27G   6% /
   tmpfs           246M  3.0M  243M   2% /dev/shm
   tmpfs           5.0M     0  5.0M   0% /run/lock
   tmpfs           246M  4.0K  246M   1% /tmp
   armbian-ramlog   50M  5.9M   45M  12% /var/log
   tmpfs            50M     0   50M   0% /run/user/998
   tmpfs            50M     0   50M   0% /run/user/0
```

**Comment by hyperactive68** [comment]
> As you said, this is an OS level issue. Your device still uses the ramlog and assigned only 50MB to `/var/log`
> 
> ```
> *** [ DIAGNOSING ]: Disk usage
>    Filesystem      Size  Used Avail Use% Mounted on
>    udev            189M     0  189M   0% /dev
>    tmpfs            50M  5.6M   44M  12% /run
>    /dev/mmcblk0p1   29G  1.7G   27G   6% /
>    tmpfs           246M  3.0M  243M   2% /dev/shm
>    tmpfs           5.0M     0  5.0M   0% /run/lock
>    tmpfs           246M  4.0K  246M   1% /tmp
>    armbian-ramlog   50M  5.9M   45M  12% /var/log
>    tmpfs            50M     0   50M   0% /run/user/998
>    tmpfs            50M     0   50M   0% /run/user/0
> ```

Alright, so how do I make it so it uses all the other available space? I'm pretty new to this and have no clue.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/cat-write-error-no-space-left-on-device/7535

**Comment by hyperactive68** [comment]
> https://discourse.pi-hole.net/t/cat-write-error-no-space-left-on-device/7535

Still doesn't really make it clear to me what I should be doing. Log2ram isn't being used and I don't know how to set up DietPi on my OrangePi (if necessary). I'm sorry, I'm clueless when it comes to this.

**Comment by rdwebdesign** [comment]
I think you have 2 possible paths here:

1. disable `log2ram` (the link posted above explains how: [here](https://discourse.pi-hole.net/t/cat-write-error-no-space-left-on-device/7535/4)).
2. change `log2ram` config to use more RAM (I don't know how to do it), but I think this is not a good idea since your board doesn't have a lot of RAM to spare.

**Comment by yubiuser** [comment]
Did you reboot the device after you set `ENABLED=false` ?

According to this [post](https://forum.armbian.com/topic/18131-dont-install-log2ram-by-default/?do=findComment&comment=124569), the file you need to edit is `/etc/default/armbian-ramlog`

**Comment by hyperactive68** [comment]
> I think you have 2 possible paths here:
> 
> 1. disable `log2ram` (the link posted above explains how: [here](https://discourse.pi-hole.net/t/cat-write-error-no-space-left-on-device/7535/4)).
> 2. change `log2ram` config to use more RAM (I don't know how to do it), but I think this is not a good idea since your board doesn't have a lot of RAM to spare.

Like I said, log2ram is not being used, so I disabled the "armbian-logram" service. Hopefully that solves it. 



> Did you reboot the device after you set `ENABLED=false` ?
> 
> According to this [post](https://forum.armbian.com/topic/18131-dont-install-log2ram-by-default/?do=findComment&comment=124569), the file you need to edit is `/etc/default/armbian-ramlog`

I never knew about this. Even though I already deleted it, I still did it. Now it's just a matter of time...

Tailing pihole.log also works now, so I think getting rid of armbian-ramlog altogether worked just fine.

**Comment by yubiuser** [comment]
Glad you solved it.

**Comment by dschaper** [comment]
Armbian-ramlog is log2ram.
