### ISSUE TITLE
Can't update Pi-hole: "Could not update local repository. Contact support."

### ISSUE THREAD

**Issue by MrConorAE** [pi-hole/pi-hole#4707]
### Versions

- Pi-hole: 5.10 (updated successfully)
- AdminLTE: 5.11 (failed to update)
- FTL: 5.14 (update not attempted because updater quits)

### Platform

- OS and version: Raspbian 10 (buster)

- Platform: Raspberry Pi 4 model B rev 1.1

### Expected behavior

While updating (`pihole -up`), the update should progress successfully.

### Actual behavior / bug

The update fails with the error in the title: "Could not update local repository. Contact support".

### Steps to reproduce

Run the updater.

Full output:
```
pi@[hostname]:~$ pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.31-1~deb10u1
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	update available
  [i] FTL:		update available

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...
  : Could not update local repository. Contact support.

```

## Debug Token

- URL: https://tricorder.pi-hole.net/vy1oWgw0/

### Screenshots

N/A

### Additional context

I haven't modified my install in any way, apart from changing the theme.

The Pi-Hole is still working and blocking ads, but just not updating, thankfully.

**Comment by MrConorAE** [comment]
When trying to manually run `git pull` in `/var/www/html/admin`, I get the following output:
```
pi@[hostname]:/var/www/html/admin$ git pull
error: cannot open .git/FETCH_HEAD: Permission denied

```

**Comment by rdwebdesign** [comment]
Looking at your debug log it was possible to see you made some changes to the system (modified CSS, apparently created a new block page, I don't know if there were any other changes).

This is usually not a problem, but it looks like some permissions have been modified.

Since you intend to upgrade (and will lose your modifications anyway), try `git reset --hard` and see if you can upgrade next.

**Comment by PromoFaux** [comment]
> I haven't modified my install in any way, apart from changing the theme.

That is what is doing it. 

```txt
*** [ DIAGNOSING ]: Web version
[i] Web: v5.11 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/pi-hole/AdminLTE.git (fetch)
             origin	https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.11-0-g64bbce90-dirty
[i] Status:  M style/themes/lcars.css
[i] Diff: diff --git a/style/themes/lcars.css b/style/themes/lcars.css
          index b9cd419e..07c4a4ac 100644
          --- a/style/themes/lcars.css
          +++ b/style/themes/lcars.css
          @@ -1,36 +1,123 @@
          -/*=== LCARS Pi-hole Theme ===*/
          +/*
          +	- Document: Pi-hole LCARS Next Generation Theme
          +	- Version:  1.0.0
          +	- Author:   @MichalSvatos, rdwebdesign (author of the original theme)
          +	- Description: LCARS Theme for Pi-hole dashboard. Based on the original theme but heavily customized and refactored (WIP).
          +	- Disclaimer: Due to fact that I have the access only to CSS I was forced to use some !importants and a lot of IDs. I'm sorry.
          +	- Resources: LCARS colors (https://codepen.io/Mokurunner/details/wvyKJy), http://www.lcars.org.uk/lcars_TNG_panels.htm, various LCARS images and websites
          +*/
          +
          +/* GLOBAL SETTINGS AND VARIABLES
          +   ========================================================== */
          +
          +/*
          +	-- breakpoints used (based on Bootstrap)
          +	sm: 576px;
          +	md: 768px;
          +	lg: 992px;
          +	xl: 1200px;
          +	xxl: 1500px;
          +*/
```

Revert this change and it should update properly

**Comment by samihoda** [comment]
I am seeing the same issue

**Comment by yubiuser** [comment]
@samihoda Please provide a debug token.

**Comment by samihoda** [comment]
I ran the update three times. Each time it got farther along and provided different errors. Right it is having issue with FTL. Working through it to see what I can share here

**Comment by rdwebdesign** [comment]
> ... Each time it got farther along and provided different errors.

Looks like you have a different issue.

**Comment by MrConorAE** [comment]
The thing is, these changes were made through the Pihole settings. The LCARS theme is an official option. IMO updates breaking because of a theme choice isn't great. 

I'll try the git reset and report back :)

**Comment by rdwebdesign** [comment]
You are using a **variation** of the "official" theme.

There is no need to install or change files to use pi-hole official themes. They should be already in place, but your debug log shows a completely different file in `/var/www/html/admin/style/themes/lcars.css` [here](https://github.com/pi-hole/pi-hole/issues/4707#issuecomment-1104828573). 

You (or a script) changed this file and possibly its permissions. This change is causing the update error.

Did you tried to revert this change?

**Comment by MrConorAE** [comment]
Using `sudo` to force the revert worked. Updated successfully.
Are there any other things that could be affected by this that I should be aware of/try to fix?

> Looking at your debug log it was possible to see you made some changes to the system (modified CSS, apparently created a new block page, I don't know if there were any other changes).
> 
> This is usually not a problem, but it looks like some permissions have been modified.

I created that new block page a long time ago, and it hadn't caused any problems with updates in that time. I updated two or three versions and it caused no issues. Any idea why that would suddenly cause problems now?

**Comment by rdwebdesign** [comment]
You are not using the "original" LCARS file.	

This is a screenshot showing the beginning of your debug log:
![screenshot](https://user-images.githubusercontent.com/1385443/164579063-eab74ebd-f2cd-421e-a417-9df18d75f0a2.png)

As you can see, the highlighted text shows the file was modified (the `M` letter):

```
[i] Status:  M style/themes/lcars.css
```
Also, your `lcars.css` file starts with:

```css
/*
	- Document: Pi-hole LCARS Next Generation Theme
	- Version:  1.0.0
	- Author:   @MichalSvatos, rdwebdesign (author of the original theme)
	- Description: LCARS Theme for Pi-hole dashboard. Based on the original theme but heavily customized and refactored (WIP).
	- Disclaimer: Due to fact that I have the access only to CSS I was forced to use some !importants and a lot of IDs. I'm sorry.
	- Resources: LCARS colors (https://codepen.io/Mokurunner/details/wvyKJy), http://www.lcars.org.uk/lcars_TNG_panels.htm, various LCARS images and websites
*/
```

But the original `lcars.css` starts with:

```
/*=== LCARS Pi-hole Theme ===*/
```
The whole file was modified.

---

I don't know HOW your system was changed, but this is not the original file.

If you want to run the update script, you need to revert this change.

**Comment by rdwebdesign** [comment]
Note:
Looks like you used a different source to install your pi-hole.

**Comment by MrConorAE** [comment]
Ah! Forgot I had done that, I had installed the theme from [this repo](https://github.com/MichalSvatos/pi-hole-lcars-next-gen). 
Thanks again for all your help :)

**Comment by rdwebdesign** [comment]
This repo uses `sudo` to install the new theme.

It also shows how to revert it:
https://github.com/MichalSvatos/pi-hole-lcars-next-gen#uninstallrevert
