### ISSUE TITLE
gravity.sh overwrites custom IP settings in gravity.list

### ISSUE THREAD

**Issue by jim-liu** [pi-hole/pi-hole#471]
##### Expected Behaviour:
`gravity.sh` should preserve the customized IP (for example, an external IP) if one is in place instead of detecting it.

##### Actual Behaviour:
My pi-hole is on an external network with a private IP. During setup I specified its external IP. If `pihole -g` is run afterward, all the domains in `gravity.list` point to the internal IP (detected in `gravity.sh`), instead of the external IP specified during setup.

##### Steps to reproduce this issue:

1. Run pihole setup script and set a different IP than the one detected.
2. Domains in `gravity.list` point to the customized IP.
3. Run `pihole -g`.
4. Domains in `gravity.list` point to the detected IP.

**Comment by PromoFaux** [comment]
Ah, yes, this is known. `gravity.sh` currently works out the current IP each time it runs, as opposed to whatever was set up at install time. This is fine for a more basic install, but for setups like yours it is not ideal!

What we should probably be doing i storing the IPv4 and IPv6 addresses at the beginning, and reusing them in gravity.

**Comment by jim-liu** [comment]
It seems `gravity.sh` will read from `\tmp\piholeIP` (left by the setup script) but then deletes it, which prevents it from being used the next time `gravity.sh` is run.

Also a potentially separated issue: if `gravity.sh` uses the IP from `\tmp\piholeIP`, whitelisted domains will not be removed from `gravity.list`. I can't figure out why.

**Comment by PromoFaux** [comment]
Hmm, OK, I will try and take a look into this later on when I'm not at work :)

**Comment by Mcat12** [comment]
With the change to 0.0.0.0, would this only matter for the hostname and pi.hole? (Assuming they don't get cut because of security... :P )

**Comment by PromoFaux** [comment]
The 0.0.0.0 thing is only "theory" so far, but yeah, this will no longer be an issue as we wont care what the local IP is if we go down that route.

**Comment by jim-liu** [comment]
Played with it a bit more after work and came up with a workaround to the two issues I have.

1. `gravity.sh` doesn't preserve IP set during setup

- Comment out line 41 (`rm $piholeIPfile`) so `/tmp/piholeIP` is not deleted after `gravity.sh`.

2. `whitelist.sh` doesn't remove whitelisted IPs from `gravity.list`

- Replace the IP detection mechanism in `whitelist.sh` with the one in `gravity.sh` (replace line 32 - 35 in `whitelist.sh` with line 38 - 47 from `gravity.sh`).

**Comment by Fedora-Core** [comment]
Hi,

gravity.sh will 'source' the file $piholeDir/pihole.conf (if that file exists) after the code that uses the 'IP' utilty.

Tip: place your key/value there.
Warning: watch out for leading/trailing whitespace !

Grtz, F.C.

**Comment by PromoFaux** [comment]
@jim-liu Could you fork/clone the repo and gather all your changes into a pull request (against the `development` branch, please. Might make it a bit easier to review exactly what you're changing. 

(Also, unlrelated, do you keep changing your profile pic or am I going mad?)

**Comment by jim-liu** [comment]
Just did. I was actually planning to do it, but I never collaborate on Git before and was afraid of f-ing things up.

(I did actually. I have many different avatars all with red hair.)

**Comment by PromoFaux** [comment]
Don't worry about making mistakes,  just look back through the commit history to see how many times I have messed up over the months...   :) 

We are a bit better at vetting pull requests now anyway,  so we can make sure any changes are tested before merging! 

(ah, good,  that puts my mind at rest... 🙃)

**Comment by jacobsalmela** [comment]
Fixed in [2.7](https://github.com/pi-hole/pi-hole/wiki/Changelog#27---2016-06-11)
