### ISSUE TITLE
https Web interface not working after upgrade

### ISSUE THREAD

**Issue by kouled** [pi-hole/pi-hole#4715]
### Versions

  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)

### Platform

- OS and version:  Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-1059-raspi aarch64)

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._
Before the update I get the pihole UI : https://mypihole.mydomain.xyz
After running pihole -up the https not reachable I can only go to http://mypihole.mydomain.xyz
### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to your favourite browser I use Firefox
2. Click on the bookmark or type the URL of the Web interface of my pihole for me https://mypihole.mydomain.xyz IT WAS WORKING FINE 
3. You get the error message : "Unable to connect
4. See error in the screenshot

![image](https://user-images.githubusercontent.com/26141042/164914269-e1b316ab-e931-4c44-9d35-46e6e0f574cc.png)

## Debug Token

- URL:  

### Screenshots
see above
_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by kouled** [comment]
Addendum

I have another web site running with the same certificate SSL -->  it work fine....

**Comment by kouled** [comment]
I think the /etc/lighttpd/lighttpd.conf was erase by the upgrade

**Comment by yubiuser** [comment]
That's why it's written in big right at the beginning of the file

```
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################
```

https://github.com/pi-hole/pi-hole/blob/853f6b7da2b5130e33d76840f463ab374eb77596/advanced/lighttpd.conf.debian#L1-L16

**Comment by kouled** [comment]
Sympa 👍 
###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# **ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE** #

**Comment by kouled** [comment]
It can be that hte external. conf was erase not really sure
