### ISSUE TITLE
Query log logging hundereds of domains as 'blank'

### ISSUE THREAD

**Issue by biggreek19** [pi-hole/pi-hole#4719]
### Versions
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.14)

### Platform
- OS and version:  Pi-hole version is v5.10 
- Platform:  Raspberry Pi v4 4GB Edition

### Expected behavior

Expected behavior is when the Pi-hole logs queries, that they should be listed what domain is being queried. 

### Actual behavior / bug

During two times today (1PM & 7:30 EST), there were spikes of 2000+ queries within the same hour from my router. When I look in the query log of what was trying to be queried at that time, I see pages and pages where the domain shows just the word 'blank':

Time	                     Type	Domain	Client	             Status	              Reply	
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928
2022-04-26 01:14:04 	A	blank	RT-AC3100-3928	OK, sent to RT-AC3100-3928

Due to the amount, it is triggering the FTL and blocking requests.... I upped the amount of the FTL in the meantime, but would like to know why it is logging as 'blank'?

### Steps to reproduce

I am honestly not sure how to reproduce this, as I do not know which device in trying to send 'blank' queries. 

## Debug Token

- URL:  

https://tricorder.pi-hole.net/q5Mtmhv8/

### Screenshots

![image](https://user-images.githubusercontent.com/49214092/165400558-4a3b3833-8c79-4e2b-8d3e-fd550571ff14.png)

**Comment by dschaper** [comment]
It looks like you have a loop. The client is the same as the DNS server the request is being sent to. Which leads the DNS server to ask Pi-hole who then asks the DNS server and on and on...

We ask that configuration issues be resolved at our Discourse Forum at https://discourse.pi-hole.net.

Thanks
