### ISSUE TITLE
BLOCK_ICLOUD_PR=false ignored in latest release

### ISSUE THREAD

**Issue by netmute** [pi-hole/pi-hole#4720]
### Versions

  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

I run `BLOCK_ICLOUD_PR=false` in pihole-FTL.conf to be able to use Apples Private Relay feature.

### Actual behavior / bug

The latest pi-hole blocks Private Relay despite `BLOCK_ICLOUD_PR=false` being set.

### Steps to reproduce

- Open Apple Mail.
- Get the usual "Your network preferences prevent content from loading privately." error.

## Debug Token

- URL:  https://tricorder.pi-hole.net/M118Mll4/

**Comment by yubiuser** [comment]
```
-rw-rw-r-- 1 pihole root 37 Apr 24 06:48 /etc/pihole/pihole-FTL.conf
   BLOCK_ICLOUD_PR=false

   -----tail of pihole-FTL.log------
   [2022-04-27 09:53:16.726 492M]    BLOCK_TTL: 2 seconds
   [2022-04-27 09:53:16.726 492M]    BLOCK_ICLOUD_PR: Disabled
```

You have successfully disabled blocking of the iCloud Private Relay domains.

Please run from a client

```
nslookup mask.icloud.com
nslookup mask-h2.icloud.com
```

**Comment by netmute** [comment]
My bad, you're right. I bypassed Pihole completely and the problem persists. Sorry for wasting everyone's time.

**Comment by DJFraz** [comment]
> My bad, you're right. I bypassed Pihole completely and the problem persists. Sorry for wasting everyone's time.

I as well had this same issue. Was just searching to fix and stumbled upon this post. Appears there's a specific setting in the Network settings on MacOS. After checking this for each connection, it now works.

![Screen Shot 2022-05-25 at 6 24 38 PM](https://user-images.githubusercontent.com/13461917/170396358-699b4f07-27d0-4371-bb0b-5d0f30c0f481.png)

**Comment by franz-josef-kaiser** [comment]
In case someone wants to know what this is about: [Here's the Apple documentation](https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay/).
