### ISSUE TITLE
Network connection fails on host until I restart pihole (multiple pihole installations on network)

### ISSUE THREAD

**Issue by HeAuDa** [pi-hole/pi-hole#4721]
First off. Thank you for this amazing application. I've been using it in various settings for awhile now without issue until a couple days ago.

### Pihole Version

Pi-hole version is v5.10 (Latest: v5.10)
AdminLTE version is v5.12 (Latest: v5.12)
FTL version is v5.15 (Latest: v5.15)
* Same for all machines (see below)

### Platform
- OS and version:  Ubuntu 22.04 Server x64  (One is Ubuntu 22.04 Desktop, see below).
- I recognize this is unsupported, but it was working for a few days before the problem started so I don't think it is an issue with the OS, and it works on two out of three of the devices on the same network.
- Platform: Installed as systemd service (I would prefer to stay with the non-docker)
*unbound is installed but pihole is not configured to use it yet.

### Expected behavior

This was working for a few days before the issue started. 

I have a DD-WRT router and 3 Machine all running the same OS as stated above: 

Vulcan: Primary PiHole
Delta-Vega: Secondary PiHole
Cyntherian: Backup PiHole (Disabled by default), this is the Ubuntu Desktop.
(any Star Trek geeks in the house?)

They are synced with [ stevejenkins  pihole-cloudsync](https://github.com/stevejenkins/pihole-cloudsync) (triggered via crontab)
* I disabled the cloud sync tasks while trying to troubleshoot this issue, but it has persisted for a few days after.

My expected behavior is that my router will use Vulcan and Delta-Vega's PiHole, and I will have working DNS on all machine. If those two machines turn off I can enable my backup PiHole on Cyntherian and my router will use that PiHole (this part is functioning perfectly).

### Actual behavior / bug

Everything works as expected included unlisted machines without PiHole installations (Firesticks, Tablets, Phones, etc) except Delta-Vega. 
Delta-Vega is the most active machine with frequent downloads 24/7. I've noticed about once a day it looses internet, and I have to restart PiHole via systemctl and it works as expected. 

This is the log from the pihole on delta-vega

```
Apr 26 06:17:21 delta-vega systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 26 06:17:21 delta-vega pihole-FTL[667]: Not running
Apr 26 06:17:24 delta-vega su[705]: (to pihole) root on none
Apr 26 06:17:25 delta-vega su[705]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Apr 26 06:17:38 delta-vega systemd[1]: Started LSB: pihole-FTL daemon.
Apr 26 06:18:01 delta-vega systemd[1]: Stopping LSB: pihole-FTL daemon...
Apr 26 06:18:03 delta-vega pihole-FTL[1016]: ..
Apr 26 06:18:03 delta-vega pihole-FTL[1016]: Stopped
Apr 26 06:18:03 delta-vega systemd[1]: pihole-FTL.service: Deactivated successfully.
Apr 26 06:18:03 delta-vega systemd[1]: Stopped LSB: pihole-FTL daemon.
Apr 26 08:14:25 delta-vega systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 26 08:14:26 delta-vega pihole-FTL[19513]: Not running
Apr 26 08:14:26 delta-vega su[19523]: (to pihole) root on none
Apr 26 08:14:26 delta-vega su[19523]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Apr 26 08:14:27 delta-vega pihole-FTL[19555]: FTL started!
Apr 26 08:14:27 delta-vega su[19523]: pam_unix(su:session): session closed for user pihole
Apr 26 08:14:27 delta-vega systemd[1]: Started LSB: pihole-FTL daemon.
Apr 26 08:16:01 delta-vega systemd[1]: Stopping LSB: pihole-FTL daemon...
Apr 26 08:16:03 delta-vega pihole-FTL[20280]: .
Apr 26 08:16:03 delta-vega pihole-FTL[20280]: Stopped
Apr 26 08:16:03 delta-vega systemd[1]: pihole-FTL.service: Deactivated successfully.
Apr 26 08:16:03 delta-vega systemd[1]: Stopped LSB: pihole-FTL daemon.
Apr 26 18:16:58 delta-vega systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 26 18:16:59 delta-vega pihole-FTL[149070]: Not running
Apr 26 18:16:59 delta-vega su[149082]: (to pihole) root on none
Apr 26 18:16:59 delta-vega su[149082]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Apr 26 18:17:01 delta-vega systemd[1]: Started LSB: pihole-FTL daemon.
Apr 26 18:18:01 delta-vega systemd[1]: Stopping LSB: pihole-FTL daemon...
Apr 26 18:18:02 delta-vega pihole-FTL[149363]: .
Apr 26 18:18:02 delta-vega pihole-FTL[149363]: Stopped
Apr 26 18:18:02 delta-vega systemd[1]: pihole-FTL.service: Deactivated successfully.
Apr 26 18:18:02 delta-vega systemd[1]: Stopped LSB: pihole-FTL daemon.
Apr 26 18:21:05 delta-vega systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 26 18:21:05 delta-vega pihole-FTL[150053]: Not running
Apr 26 18:21:05 delta-vega su[150063]: (to pihole) root on none
Apr 26 18:21:05 delta-vega su[150063]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Apr 26 18:21:06 delta-vega systemd[1]: Started LSB: pihole-FTL daemon.
Apr 27 17:49:03 delta-vega systemd[1]: Stopping LSB: pihole-FTL daemon...
Apr 27 17:49:04 delta-vega pihole-FTL[485981]: Not running
Apr 27 17:49:04 delta-vega systemd[1]: pihole-FTL.service: Deactivated successfully.
Apr 27 17:49:04 delta-vega systemd[1]: Stopped LSB: pihole-FTL daemon.
Apr 27 17:49:04 delta-vega systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 27 17:49:04 delta-vega pihole-FTL[485986]: Not running
Apr 27 17:49:04 delta-vega su[485996]: (to pihole) root on none
Apr 27 17:49:04 delta-vega su[485996]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Apr 27 17:49:04 delta-vega pihole-FTL[486006]: FTL started!
Apr 27 17:49:04 delta-vega su[485996]: pam_unix(su:session): session closed for user pihole
Apr 27 17:49:04 delta-vega systemd[1]: Started LSB: pihole-FTL daemon.
```

### Steps to reproduce the behavior:

Setup clean 22.04 installations on three machines with hostnames Vulcan, Delta-Vega, and Cyntherian (2 server, 1 desktop) 
Create netplans to give static IP addresses (IPv4 only) to use all devices
Install pihole on 3 Ubuntu 22.40 installations.
Edit lighttpd on Vulcan and Delta-Vega to use different ports for Pi-Hole administration webui.
Set DD-WRT to use all three machines for DNS servers in this order: 1: Vulcan, 2: Delta-Vega, 3: Cyntherian.
Setup cloud sync via github instructions.
Setup a crontab to run cloudsync task every night (again this has been disabled till I figure out this issue but I don't think it's the problem)
Enable Vulcan and Delta-Vega piholes, leave Cyntherian's disabled by default (via systemd)
Start download scripts on Delta-Vega (yt-dl based in most cases, but issue occurs on anything trying to connect to internet)
Come back half a day to a day later (or manually stop pihole) and see that download scripts are interrupted with error "Temporary failure in name resolution" (one issue is that pihole seems to be failing, the other is the Delta-Vega doesn't seem to be using Vulcan's pihole if this happens)
send command systemctl restart pihole-FTL to Delta-Vega and issue is resolved for another half day to day
Beyond that I'm not sure what changed.

It's as if Delta-Vega Pi-Hole is failing, and Delta-Vega is refusing to use DD-WRT's DNS (and thus Vulcan's Pi-Hole), but it should use that by default regardless if it's own Pi-Hole is active.

### Debug Token

I would prefer not to use this method for privacy issues, but if it can't be diagnosed without it I will create the log and manually remove specific data that only relates to privacy.

### Other

I'm not fully convinced this is an issue with pihole itself, but a configuration issue somewhere else maybe. I'm just not sure how to start tracking it down, and since it is resolved by restarting pihole I figured this was the best starting point.

Edit: Added webui port change to Steps to reproduce (though I can't imagine this is influencing my issue).
        Fixed some formatting.

**Comment by PeterPlatt** [comment]
I'm seeing a similar issue on my end as well same version but it's installed on a rock64

**Comment by dschaper** [comment]
Can you please proved debug token URLs for us to review?

**Comment by PeterPlatt** [comment]
> Can you please proved debug token URLs for us to review?

Here you go : https://tricorder.pi-hole.net/tORjde0L/

**Comment by rdwebdesign** [comment]
Just one more question:

I didn't read the code, but the "pihole-cloudsync" script was last updated in 2020.
Are you sure this script is working correctly?
