### ISSUE TITLE
pihole -up does not resolve dns

### ISSUE THREAD

**Issue by henneonrails** [pi-hole/pi-hole#4722]
### Versions

Current Pi-hole version is v5.10
  Current AdminLTE version is v5.12
  Current FTL version is v5.15

### Platform

- OS and version:  raspian?

- Platform:  Raspberry Pi

### Expected behavior

running pihole -up

### Actual behavior / bug
```
[✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.28
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] Checking for updates...
fatal: konnte nicht auf 'https://github.com/pi-hole/pi-hole.git/' zugreifen: Could not resolve host: github.com
  [i] Pi-hole Core:	up to date
fatal: konnte nicht auf 'https://github.com/pi-hole/AdminLTE.git/' zugreifen: Could not resolve host: github.com
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.28

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✗] Retrieval of supported OS list failed. dig failed with return code 10. 
      Unable to determine if the detected OS (Raspbian 11) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


  Unable to complete update, please contact Pi-hole Support
```
## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

sudo apt-get update does not resolve too

**Comment by rdwebdesign** [comment]
It appears to be a problem with your network.
Your Raspberry Pi is not getting internet access.

**Comment by dschaper** [comment]
Debug token please.

**Comment by henneonrails** [comment]
[pihole_debug.log](https://github.com/pi-hole/pi-hole/files/8597825/pihole_debug.log)

**Comment by henneonrails** [comment]
> It appears to be a problem with your network.
> Your Raspberry Pi is not getting internet access.
<img width="507" alt="Bildschirmfoto 2022-04-30 um 23 18 38" src="https://user-images.githubusercontent.com/123651/166122991-43d71db7-5caf-4e04-b436-66b2b82090a9.png">

<img width="1282" alt="Bildschirmfoto 2022-04-30 um 23 19 21" src="https://user-images.githubusercontent.com/123651/166123010-025c0b58-f445-4c02-a416-b91019e4a963.png">

I cannot believe that my pihole is not connected to the internet. It seems like it works as a DNS Server for my home.

**Comment by dschaper** [comment]
It does look like you have internet connectivity. 

> fatal: konnte nicht auf 'https://github.com/pi-hole/pi-hole.git/' zugreifen: Could not resolve host: github.com
  [i] Pi-hole Core:	up to date

> [i] dig return code:  10
> [i] dig response:  dig: couldn't get address for 'ns1.pi-hole.net': failure

Code 10 is an internal error. It seems that DNS is not resolving correctly on the Pi-hole server node. 

What is the output from `uname -a` and `cat /etc/os-release`.

Your `/etc/resolv.conf` file has a single IPv6 address and the debug log shows that the node can not resolve via a public IPv6 server. Can you confirm that the server can reach a public IPv6 address via `ping`? Also it looks like the `/etc/resolv.conf` entry is the Pi-hole server itself. We don't suggest you use Pi-hole as it's own resolver because it can cause a situation like this where the DNS server is offline for an upgrade and that upgrade can not continue without an active DNS server.

Try changing `/etc/resolv.conf` to be a public IPv4 server and see if `pihole -up` works.

**Comment by henneonrails** [comment]
```
uname -a
Linux pihole 5.10.103-v7l+ #1530 SMP Tue Mar 8 13:05:01 GMT 2022 armv7l GNU/Linux

cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by henneonrails** [comment]
> Try changing `/etc/resolv.conf` to be a public IPv4 server and see if `pihole -up` works.

```
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 8.8.8.8
```
after changing /etc/resolv.conf ``pihole -up `` says that everything is up to date. No error message.

but after ``sudo reboot`` the old /etc/resolv.conf is back

```
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 2002:5899:9c2c:0:3cd0:fa37:ca4d:b9e5
```

**Comment by henneonrails** [comment]
made a ``apt-get upgrade``with the public ipv4 name server in /ect/resolv.conf

**Comment by dschaper** [comment]
Take a look at `/etc/dhcpcpd.conf` and see if that IPv6 is set there.

**Comment by dschaper** [comment]
We suggest that you not set the IP address of the Pi-hole server to be from a DHCP server. It really should be statically set so that there is no possibility of it changing.
