### ISSUE TITLE
teleporter to import settings via terminal needed 

### ISSUE THREAD

**Issue by pinkworld123** [pi-hole/pi-hole#4723]
hello, 

Teleporter to import settings via terminal needed. Export of Teleporter works very nicely. but when need to import it there is no terminal command. 

Can you please tell me how can i do Teleporter Restore via terminal command line. thanks

**Comment by yubiuser** [comment]
Unfortunately, there is no way* to do this right now. All the importing logic is handled by the `php` script of the web interface.

* you could try to resemble the `php` commands manually in bash, but we can't provide a step-by-step guide

P.S. the relevant code is https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/teleporter.php

**Comment by yubiuser** [comment]
I assigned "Feature request" and created a voting thread at our discourse forum where all feature requests reside:
https://discourse.pi-hole.net/t/import-teleporter-backup-from-command-line/55884
