### ISSUE TITLE
No Internet when using Pi-Hole's DHCP

### ISSUE THREAD

**Issue by Carterpersall** [pi-hole/pi-hole#4724]
### Versions
- Pi-hole:  v5.10
- AdminLTE: v5.12 
- FTL:  v5.15

### Platform
- OS and version:  Fedora Server 34
- Platform:  Raspberry Pi 4b 2Gb RAM

### Expected behavior

Enable DHCP on Pi-Hole, disable DHCP on my router, and everything just works.

### Actual behavior / bug

When DHCP is enabled on Pi-Hole and disabled on my router (AT&T BGW320-500), devices are served IP addresses and DNS server just fine. The only problem is that the devices then are no longer connected to the internet. Pi-Hole is receiving the requests and supposedly answering them, yet no devices work. Connecting to the DNS manually while using the router's DHCP works great.

### Steps to reproduce

1. Install and set up Pi-Hole on Fedora Server 34 (Tried 36 first and downgraded when I first hit the issue)
2. Disable DHCP on router and enable in Pi-Hole
3. Renew DHCP lease on computer/device (ipconfig /renew on Windows)
4. Device loses internet connection

## Debug Token

- URL:  https://tricorder.pi-hole.net/O5P8vtNJ/

### Additional context

- I initially installed Pi-Hole on Fedora Server 36 by bypassing the support checks and ran into no issues other than this one. Thinking that this might be the source of my problems I started from scratch with Fedora Server 34, which is officially supported, and ran into the same issue.
- My router does not support changing the DHCP's DNS even though it has a bunch of other advanced options. My theory on why is that ATT uses their own in-house DNS service to collect advertising data on their users so obviously they wouldn't want anybody circumventing that

**Comment by dschaper** [comment]
Please continue the discussion at the above Discourse link.
