### ISSUE TITLE
Bugs in Pi-hole v5.10 FTL v5.15 Web Interface v5.12

### ISSUE THREAD

**Issue by wieb18** [pi-hole/pi-hole#4736]
Hello, 

More than a year I am running Pihole without any issue. 

But since last update (Pi-hole v5.10 FTL v5.15 Web Interface v5.12) the DNS Server stop running and Pihole has error message "There was a problem applying your settings. Debugging information: PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:43"

![2022-05-17_21-11-36](https://user-images.githubusercontent.com/45317320/168820748-82941b23-6c48-4688-8da3-7f1ce5ad5174.jpg)

I already tried uninstall then install Pihole again. First fresh install running fine, but after 2 days the same error DNS not running and message "PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:43" happen again.

I am running Pihole on Debian Buster with Armbian Linux 5.1.0-aml-s905. Sorry I don't know Linux, only above information that I can provide. 

Hope this bugs will be fix very soon, thanks

**Comment by jfb-pihole** [comment]
Please generate a debug log, upload it when prompted and post the token URL here.

**Comment by jfb-pihole** [comment]
You are running Apache2, which is interfering with the shipped web server (lighttpd):
```
[✗] tcp:*:80 is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)

*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Date: Tue, 17 May 2022 14:19:37 GMT
Server: Apache/2.4.38 (Debian)
Last-Modified: Thu, 07 Nov 2019 16:47:57 GMT
ETag: "29cd-596c46d72f7ab"
Accept-Ranges: bytes
Content-Length: 10701
Vary: Accept-Encoding
Content-Type: text/html

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.
HTTP/1.1 200 OK
Date: Tue, 17 May 2022 14:19:37 GMT
Server: Apache/2.4.38 (Debian)
Set-Cookie: PHPSESSID=inljnf2oadbuoeg01hi7urn79o; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
```

In addition, your Pi-hole host has connectivity problems:
```
[i] Default IPv4 gateway: 192.168.0.249
192.168.0.253
   * Pinging 192.168.0.249
192.168.0.253...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

Your DHCP server is passing out a DNS other than Pi-hole:
```
** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   * Received 548 bytes from eth0:192.168.0.249
     DHCPOFFER XID (266546014) does not match our DHCPDISCOVER XID (2053569671) - ignoring packet (not for us)
   
   * Received 548 bytes from eth0:192.168.0.249
     Offered IP address: 192.168.0.34
     Server IP address: N/A
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.0.249
      lease-time: 60 ( 1m )
      netmask: 255.255.255.0
      router: 192.168.0.249
      dns-server: 203.142.84.222
      dns-server: 203.142.82.222
      --- end of options ---
    
   * Received 548 bytes from eth0:192.168.0.249
     DHCPOFFER XID (266546014) does not match our DHCPDISCOVER XID (2053569671) - ignoring packet (not for us)
   
   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 1

*** [ DIAGNOSING ]: Setup variables
    PIHOLE_INTERFACE=eth0
    IPV4_ADDRESS=192.168.0.250/24
```

**Comment by wieb18** [comment]
Thanks for the response

Please ignore my DHCP server passing out a DNS to Pi-hole because without it I am unable connect to internet while Pihole DNS out of service.

![2022-05-18_00-14-48](https://user-images.githubusercontent.com/45317320/168861141-e4eb1ad9-07af-4993-bba9-1c16bacc9aa2.jpg)

Already uninstall Apache2 and Pihole. Then install Pihole again. 

Different from previous uninstall and install Pihole which I am able immediately browse to Pihole web interface, now Pihole web interface doesn't work. Tried to restart lighhttpd but also doesn't help either.

The error message is "This site can’t be reached -192.168.0.250 refused to connect"

Please help

**Comment by rdwebdesign** [comment]
Please generate a new debug log, since your config was changed.

**Comment by wieb18** [comment]
Done generate and upload Debug log

My debug token is: https://tricorder.pi-hole.net/UNs1ypoV/

**Comment by dschaper** [comment]
It looks like you have some issues with the Pi-hole server accessing anything on the WAN:

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] ads2.hsoub.com is 0.0.0.0 on lo (127.0.0.1)
[✓] ads2.hsoub.com is 0.0.0.0 on eth0 (192.168.0.250)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)
```

`lighttpd` has also failed to start. Please post the output from

`sudo systemctl status --full --no-pager lighttpd.service`

**Comment by wieb18** [comment]
`sudo systemctl status --full --no-pager lighttpd.service`  result

![2022-05-18_07-08-23](https://user-images.githubusercontent.com/45317320/168928187-bea8578b-1ee9-45ee-ad25-e10567591b2d.jpg)

I still don't understand why this error happen after I am using Pihole for more than a year? Many Pihole update I have done, everything is fine and never have any issue with it.

This error start after the last update. And as I said before, I don't understand Linux so I never do anything on this machine (install Apache2 or install anything). I only do Pihole update on this machine.   

Please let me know because I am curious the cause of this  error

**Comment by dschaper** [comment]
Somebody or something had to install Apache2 on that node. We don't have anything to do with that package.

This looks like a configuration error and the place to get help with configuration is our discourse forum at https://discourse.pi-hole.net. You can mention the URL `https://github.com/pi-hole/pi-hole/issues/4736` in your post to link back to what we have seen so far.

**Comment by wieb18** [comment]
Please let me know how to fix `lighttpd service` so I can browse to Pihole web interface?

**Comment by wieb18** [comment]
If Pihole did not install Apache2, my conclusion the Apache2 already in this machine from beginning because only me using this machine. 

And why all this time Pihole never error with Apache2? This error happen after last update. And because previously I am uninstall Apache2, now I am unable to browse Pihole web interface

**Comment by rdwebdesign** [comment]
Looks like a problem with your `lighttpd` configuration.

Try to run the command below and post the result:
```sh
/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf
```

**Comment by wieb18** [comment]
`/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf`

![2022-05-18_10-18-05](https://user-images.githubusercontent.com/45317320/168944255-9caff034-ecf0-4f05-ab1e-aca880b14e41.jpg)

No result from this command

Sorry if I am unable to provide more information. As I said before I don't know Linux. All this time I only do copy paste Linux command from tutorial website.

**Comment by rdwebdesign** [comment]
As was said before, this looks like a configuration error.

The right place to get help with configuration is our **discourse forum** at https://discourse.pi-hole.net/.
