### ISSUE TITLE
Support for additional hardware/software setups

### ISSUE THREAD

**Issue by Poorchop** [pi-hole/pi-hole#474]
I'm just discovering this project and I've done some exploring, but I don't see any steps for installing this manually. I'm interested in running this on other operating systems and on other hardware, and I've seen the links for installing on a VPS, but they still rely on current install script and therefore Debian.

I'm mostly just curious if there are any plans to support other distros or any other setups. I'm interested in running this on a BeagleBoard with another distro like Fedora or Suse, but I thought I'd ask here first before attempting to tackle this myself. I could also use a few pointers on what might need modification - so far, I'm guessing that I'll have to go through basic-install.sh and possibly gravity.sh and tweak them accordingly. At a cursory glance, the scripts are commented very well, so hopefully this should be a quick and easy change.

Thanks for any advice.

**Comment by Mcat12** [comment]
There's a (probably outdated) walkthrough of setting it up manually lower down the page [here](http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/). Also, as long as you install the dependencies manually and your file system isn't too different, most things should work.

**Comment by Poorchop** [comment]
Thanks for the link. It actually looks really simple to set up manually. Ideally, I'd like to modify the install script to automate everything as much as possible so that I can share it with others, but maybe I'll deal with that if I can get it working manually first.

On the subject of alternative software, is there any reason that this couldn't work with nginx? I'm not familiar with lighttpd at all but I'm already running nginx and I'd like to try and keep things simple on the BeagleBoard since it doesn't have many resources to spare.

**Comment by Mcat12** [comment]
It should work with nginx as long as you convert the lighttpd config to nginx (mainly 404 goes to pihole/index.html or pihole/index.js)

**Comment by Poorchop** [comment]
Thanks for your help. I haven't had time to test yet but hopefully I can get this working in another distro and maybe with nginx. I'll try to document any deviation from the guide that you linked above in case anyone is interested in the future.
