### ISSUE TITLE
iOS 15.5 - sites not loading completly

### ISSUE THREAD

**Issue by Dennis1993** [pi-hole/pi-hole#4740]
### Versions

- Pi-hole:  5.10
- AdminLTE:  5.12
- FTL:  5.15

### Platform

- OS and version:  Raspbian

- Platform:  raspberry Pi 3

### Expected behavior

Websites which I want to open should be loaded

### Actual behavior / bug

Many different sites are not loading since iOS 15.5 with safari. The websites cant finish the loading. If I disable the pihole in my network settings the problem is gone.
If I activate it again the problem is back. Sites are not loaded or some sites are not loaded completly. If the site is not loaded completly the back button is not working.

I can fix the problem if I turn of the Tracking in the wlan configuration („Tracking der IP-Adresse beschränken“ is the option called)

### Steps to reproduce

1. Setup PiHole 
2. Install iOS 15.5
3. visit Instagram.com and click on some links. If you want go back it doesnt work
4. Some sites are completly not loading it stucks on 10-15% of the loading bar 

### Additional context

Many other users have the same problem: https://www.reddit.com/r/pihole/comments/utab8p/safari_wont_finish_loading_certain_sites_after/

https://www.computerbase.de/forum/threads/seiten-laden-nicht-und-zurueck-button-reagiert-nicht.2086105/

**Comment by rdwebdesign** [comment]
I don't think this is a pi-hole issue.

Also, the [reddit link](https://www.reddit.com/r/pihole/comments/utab8p/safari_wont_finish_loading_certain_sites_after/) you posted has a solution:

<pre>
Go into the network settings for each wifi or ethernet connection and disable <b>Limit IP Adress Tracking</b>.
</pre>

**Comment by Dennis1993** [comment]
Hey,

thanks for your andere!
I wrote that I can fix it. But why is that not a PiHole issue? If I disable PiHole that connection works without problems.

maybe we should find the problem and can fix that for all users ☺️
If not: many people will have the problem in the next time. Some users are not pros in the IT world and cant find a solution. So then the users will be leave this project I think. The tracking security is activated by default!

**Comment by jfb-pihole** [comment]
We made no changes to Pi-hole. Apple changed their software. The method we use to block Apple Private Relay (as described in our documentation) follows guidance from Apple. I suspect Apple will need to provide guidance to developers.

**Comment by yubiuser** [comment]
Please continue discussion here: 
https://discourse.pi-hole.net/t/safari-wont-finish-loading-certain-sites-after-ios-15-5-macos-12-4-upgrade/55516
