### ISSUE TITLE
Disk shortage /var/log/pihole-FTL.log ahead: 99% used

### ISSUE THREAD

**Issue by Stephen988** [pi-hole/pi-hole#4741]
Versions
Pi-hole version is v5.10
AdminLTE version is v5.12
FTL version is v5.15
Container tag is: 2022.04
Platform
OS and version: Debian 10
Platform: Docker 20.10.16

Actual behavior / bug
Disk shortage /var/log/pihole-FTL.log ahead: 99% used

P.S.
how to clean all logs files, my memory is full

**Comment by rdwebdesign** [comment]
Please, ask your questions about configuration at our [Discourse Forum](https://discourse.pi-hole.net/).

As a free open-source project run by volunteers we have very limited resources.
Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8
