### ISSUE TITLE
Attempt to update shows "Bad Address" fatal warning and fails to update Core, but updates AdminLTE and FTL

### ISSUE THREAD

**Issue by MasterKale** [pi-hole/pi-hole#4743]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

Running `pihole -up` updates Pi-Hole, AdminLTE, and FTL.

### Actual behavior / bug

`pihole -up` hangs for minutes and then displays the following error before claiming Pi-Hole is up to date, then updating AdminLTE and FTL as expected:

> fatal: open /dev/null or dup failed: Bad address

### Steps to reproduce

1. SSH into Raspberry Pi hosting Pi-Hole
2. Run `pihole -up`
3. Observe "Bad address" error

Full console output:

```sh
$> pihole -up
  [i] Checking for updates...

fatal: open /dev/null or dup failed: Bad address
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	update available
  [i] FTL:		update available

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...HEAD is now at 6c320a4 Merge pull request #2173 from pi-hole/devel
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.29-1~deb10u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed

  [✓] Checking apt-get for upgraded packages... 97 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php7.3-json
  [✓] Checking for php7.3-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARMv6 processor (with hard-float support)
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [i] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Restarting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Restarting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 115063 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 115063 (115063 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

  Current Pi-hole version is v5.3.1.
  Current AdminLTE version is v5.12.
  Current FTL version is v5.15.
$> pihole -v
  Pi-hole version is v5.3.1 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/pgwyqzxz/

### Screenshots

N/A

### Additional context

This was the first time I'd run `pihole -up` in a while, it was on 5.3.1 for a while. I don't have anything too tricky set up on my home network - the pihole is the most exotic thing on the network. I have a NAS hosting a few things on random ports but can't think of anything it hosts that'd interfere with Pi-Hole. The Pi-Hole has otherwise worked fine blocking ads.

**Comment by rdwebdesign** [comment]
Was the OS updated too?

Also, I saw a lot of errors in your debug log related to SQLite corruption (like `SQLite3 message: database corruption at line 68176 of [5d4c65779d]`).
Is your SD card OK?

**Comment by MasterKale** [comment]
No, I didn't update the OS while I was in there. I know Raspbian 11 is out but given the Pi is an OG B+ I didn't want to wait for it to update the OS as well:

```sh
$> cat /proc/cpuinfo | grep Model
Model		: Raspberry Pi Model B Plus Rev 1.2
```

As for the DB corruption, I have no idea. Nothing had seemed obviously failing; your observation is the first indication I've had that anything SD card-related might be the culprit. Any idea how I might be able to confirm/deny it's culpability in this?

**Comment by PromoFaux** [comment]
> Any idea how I might be able to confirm/deny it's culpability in this?

One quick thing to check is to make sure that you're power supply is rated correctly:

<html>
<body>


Model | Voltage | Recommended Capacity
-- | -- | --
Zero | 5.1V | 1.2A
Pi 1 A / A+ | 5.1V | 700mA
Pi 1 B+ / 2 B | 5.1V | 1.8A
Pi 3 A+ / B / B+ | 5.1V | 2.5A
Pi 4 B / 400 | 5.1V | 3.0A
Pico | 1.8–5.5V DC | –


</body>
</html>

https://thepihut.com/blogs/raspberry-pi-tutorials/how-do-i-power-my-raspberry-pi

**Comment by MasterKale** [comment]
I was very mindful of those outputs when I purchased this power supply. The Pi's performance was particularly bad today so I went ahead and shut it off and confirmed the output: 5v===2000mA, which is in line with the chart above.

It's worth noting that after setting a secondary DNS on my home network just now so I could browse the internet while Pi-Hole is offline, pages are loading _way_ quicker than I'm used to. I wonder now if all this time the network "hiccups" I've been experiencing for the last 2-3 months have been signs I've missed of the Pi slowly dying. Maybe the SD card really is on its way out...

**Comment by PromoFaux** [comment]
Cool, then at least we can rule out power as a source of potential SD card corruption. How about the SD card itself? Is it of reputable brand? One good thing about SD cards that have become corrupt... you can just reflash them and they should be good to go again... providing you're happy to do so, of course!

With a decent power supply, and a good SD card - Pi-hole should never "just" go offline (aside from power outages...), but obviously failures can and do happen. Anecdotal, I know, but I ran a B+ for years on the same SD card/power supply with no issues

**Comment by MasterKale** [comment]
The SD card is an 8GB class 4 Kingston card I probably purchased the same time as the B+. I've generally thought Kingston is a decent brand in this space, and haven't really been let down by any of their stuff even as I'm generally hesitant to build much on top of Raspberry Pi's and their reliance on SD card media (are Pi's still notorious for wiping out their own SD cards? Maybe that's not a thing anymore on newer Pi's)

Is the CPU on the B+ actually sufficient for hosting the Pi-Hole? I could never make heads or tails of the "Load" metric on the Pi-Hole admin panel - it was often hovering or just a tad over 1.0, and so I was never sure if perhaps the B+ had meager CPU capacity to do much more than churn through DNS requests vis-a-vis hosting Pi-Hole. I have a few more modern Pi's floating around that I could replace the B+ with instead if it'll mean faster DNS resolution, I've just never been sure if throwing a Pi 2 or Pi 3 would be overkill.

**Comment by PromoFaux** [comment]
Personally I retired by B+ a long time ago - I'm currently running Pi-hole on a pi4 which is _definitely_ overkill, but it's running as a Docker container alongside some other applications

As for whether a B+ is sufficient... it _should_ be. Pi-hole runs fine on a Pi Zero/Zero W, which have the same [chip as the original](https://www.raspberrypi.com/documentation/computers/processors.html#bcm2835). I guess, though, it heavily depends on the number of requests that are hitting it / number of clients you have. Do you have anything else running/installed on this Pi?

**Comment by MasterKale** [comment]
> Do you have anything else running/installed on this Pi?

No, I intentionally turned the B+ into a Pi-Hole "appliance" with a bare-metal install and nothing else. Maybe I'll take this as a sign to retire the B+ and try getting Docker running on a 3 instead, it's what I actually wanted to do at the start. I'll stop trying to optimize use case to hardware capabilities, it's 2022 and it's not like I'm using them for anything else 😂 

Thank you for your time with this. I'll close this issue for now as I don't know that this is worth chasing down anymore now that I'm moving on from the B+.

**Comment by dschaper** [comment]
The b+ has a single core processor so a load of 1 equates to 100% of that single core loaded. For comparison a quad core Pi with a load of 1 means that the equivalent of a single core was loaded (25% of the total processing capacity.)

The web display is basically a mirror of what you would see from `uptime` on the command line.

https://www.tecmint.com/understand-linux-load-averages-and-monitor-performance/

**Comment by MasterKale** [comment]
> The b+ has a single core processor so a load of 1 equates to 100% of that single core loaded. 

Well that explain's it: the CPU's been pegged at 100% pretty much all the time with our typical household browsing habits 🙃 

Definitely time to upgrade!

**Comment by churchofnoise** [comment]
That sounds strange tbh...
I've ran Pi-Hole on a rpi zero for years as the sole dns server for quite a busy household and I was always around 10% cpu use...

**Comment by MasterKale** [comment]
> That sounds strange tbh...
> I've ran Pi-Hole on a rpi zero for years as the sole dns server for quite a busy household and I was always around 10% cpu use... 

Is this something we're interested in getting to the bottom of? I've still got the Pi set up, just powered off. I'd volunteer to debug further for `S C I E N C E` if it might help the cause.

**Comment by rdwebdesign** [comment]
> Is this something we're interested in getting to the bottom of?

I don't think any investigation is necessary.
It's a known fact that many users are able to run pi-hole on Raspberry Pi Zero and older versions of Raspberry Pi.

In your case, I would recommend to debug further **only** if you had no other choice, but you have made it clear that you intend to use your Pi3, install docker and other systems together with the pi-hole.

To be honest, I don't see any reason for further investigation.

**Comment by churchofnoise** [comment]
Fair point from @rdwebdesign .

Whatever device you will run pi-hole on next, I would advise to get a new SD card and start from scratch... (you could use teleporter to keep important settings).
And from an efficiency point of view, if it were my choice, I'd use the most energy efficient device available (to you)
