### ISSUE TITLE
Custom "webroot" in basic-install.sh not reflected in lighttpd.conf

### ISSUE THREAD

**Issue by loetmeister** [pi-hole/pi-hole#4746]
### Versions
- Pi-hole:  v5.10 (Latest: v5.10)
- AdminLTE:  -1 (Latest: v5.12)
- FTL:  v5.15 (Latest: v5.15)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) 5.10.103-v7+ 1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
- Platform:  Raspberry Pi

### Expected behavior

Expect `/etc/lighttpd/lighttpd.conf` to have correct webroot as set in `basic-install.sh`, e.g.
```
# Root of the web server
webroot="/var/www/pihole-html"
```

### Actual behavior / bug

`/etc/lighttpd/lighttpd.conf` is using default config `server.document-root        = "/var/www/html"`, resulting in HTTP 404 when browsing http://pi.hole/admin
`basic-install.sh` is creating/using correct custom path "/var/www/pihole-html" - just lighttpd is not configured correctly during installation.

### Steps to reproduce

1. Modify `basic-install.sh`, change webroot from "/var/www/html" to "/var/www/pihole-html".
```
# Root of the web server
#webroot="/var/www/html"
webroot="/var/www/pihole-html"
```
2. Run basic-install.sh
3. Open http://pi.hole/admin

**Comment by yubiuser** [comment]
I'm not sure if it is intended to be a customizable path or not. I'm hesitant to label this a bug or rather a feature request.

**Comment by rdwebdesign** [comment]
The root for the web server is set by `lighttpd`. 

The information in `basic-install.sh` should reflect the configuration.

**Comment by dschaper** [comment]
Modifications to `basic install.sh` makes it unsupported. 

This is not a bug.

**Comment by loetmeister** [comment]
> Modifications to `basic install.sh` makes it unsupported.
> 
> This is not a bug.

Thanks for the clarification! I'll look forward to an "advanced install.sh" ;-)
