### ISSUE TITLE
After complete rebuild of pihole pi I have lost the graph for top clients...

### ISSUE THREAD

**Issue by mattlward** [pi-hole/pi-hole#475]
##### Expected Behaviour:
Before the last rebuild I had the graph that showed the distribution between systems... After the reinstall I have a series of bar graphs.  Is there a way to restore the original behavior?  I also show a large number of requests that are attributed to my DD-WRT router (1.1).  It is configure with "No DNS rebind"
##### Actual Behaviour:
![clipboard01](https://cloud.githubusercontent.com/assets/8540074/14768612/a2b6ed10-0a0c-11e6-8e6b-e2b4849e2a51.jpg)

**Comment by PromoFaux** [comment]
If you go into the query log page, it will show you the requests that are being attributed to your router, depending on how you're set up, it might be that some devices are configured incorrectly.

As for the changes to the Top clients section, that came in with the last [update](https://github.com/pi-hole/AdminLTE/wiki/Changelog#12---2016-04-16). As well as many performance updates on the page itself, it was decided to move away from the radar graph as it can get pretty messy when you have a lot of clients. This gives a much clearer view of what's going on!

**Comment by mattlward** [comment]
Thanks... I will investigate the router attributions more.
