### ISSUE TITLE
[Tracking] Log symlinks /var/log -> /var/log/pihole need to be removed

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#4750]
https://github.com/pi-hole/pi-hole/pull/3732 changed the default log location from `/var/log/` to `/var/log/pihole`. To ensure backward compatibility we created symlinks for `/var/log/pihole.log -> /var/log/pihole/pihole.log` and `/var/log/pihole-FTL.log -> /var/log/pihole/pihole-FTL.log`.

Those links (and the code) should be removed in an upcoming version. Marking this `Bug` to preventing it from going stale.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/pi-hole/pull/4777 changed FTL's default log file path from /var/log/pihole/pihole-FTL.log to the slightly shorter /var/log/pihole/FTL.log

**Comment by rdwebdesign** [comment]
**4777** didn't solve the issue reported here.

- **3732** changed the default directory and **created the symlinks**.
- **4777** changed one file name (`pihole-FTL.log` to `FTL.log`).

The symlinks ([and code to handle them](https://github.com/pi-hole/pi-hole/blob/5490a6ea6d9a929d8831872280ff36313fbefdfa/automated%20install/basic-install.sh#L2710-L2736)) are still there.

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/pi-hole/pull/5711
