### ISSUE TITLE
E: Unable to locate package netcat-openbsd

### ISSUE THREAD

**Issue by toni1703** [pi-hole/pi-hole#4753]
### Versions
Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.13 (Latest: v5.15)

### Platform

- Platform:  Raspberry Pi

When running pihole -up the FTL is not updated:
 [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.27-1~deb10u1
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.27-1~deb10u1

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] Checking for / installing Required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for ca-certificates

  [i] SELinux not detected
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Checking for / installing Required dependencies for Pi-hole software...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for idn2
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [i] Checking for netcat-openbsd (will be installed)
  [i] Checking for procps (will be installed)
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php7.3-intl
  [✓] Checking for php7.3-json
  [i] Waiting for package manager to finish (up to 30 seconds)
  [i] Processing apt-get install(s) for: netcat-openbsd procps, please wait...

E: Unable to locate package netcat-openbsd
E: Package 'procps' has no installation candidate

**Comment by yubiuser** [comment]
Please try to install the packages manually.

`sudo apt install netcat-openbds procps`

**Comment by yubiuser** [comment]
Please upload a debug log and post **just the  token URL** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
```
pihole -d
```
or do it through the Web interface:

***Tools > Generate Debug Log***

**Comment by toni1703** [comment]
> Please upload a debug log and post **just the token URL** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
> 
> ```
> pihole -d
> ```
> 
> or do it through the Web interface:
> 
> _**Tools > Generate Debug Log**_
[
](https://tricorder.pi-hole.net/Oo2pMcG3/)
it might be that i'm using an older version of php ? version
[i] 7.3.27

**Comment by yubiuser** [comment]
> it might be that i'm using an older version of php ? version
[i] 7.3.27

This is not the issue here.

**Comment by toni1703** [comment]
> > it might be that i'm using an older version of php ? version
> > [i] 7.3.27
> 
> This is not the issue here.

Can you tell me what is the issue? How can I fix this?

**Comment by PromoFaux** [comment]
> Please upload a debug log and post **just the token URL** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
> 
> ```
> pihole -d
> ```
> 
> or do it through the Web interface:
> 
> _**Tools > Generate Debug Log**_

**Comment by toni1703** [comment]
> > Please upload a debug log and post **just the token URL** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
> > ```
> > pihole -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or do it through the Web interface:
> > _**Tools > Generate Debug Log**_

I have done this few weekend ago. If you need a new one, i'll post it (token)

**Comment by PromoFaux** [comment]
Hmm, it must have got lost in the post, as it is not in this thread :) Yes please, a new one would be helpful!
