### ISSUE TITLE
pihole-FTL service is not running on Ubuntu 22.04

### ISSUE THREAD

**Issue by eugef66** [pi-hole/pi-hole#4754]
### Versions
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)

### Platform
- OS and version:  Ubuntu 22.04

- Platform:  Standalone server

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

`$sudo service pihole-FTL status`

`  pihole-FTL.service - LSB: pihole-FTL daemon`
`     Loaded: loaded (/etc/init.d/pihole-FTL; generated)`
`     Active: active (exited) since Thu 2022-06-09 12:41:46 EDT; 1 day 1h ago`
`       Docs: man:systemd-sysv-generator(8)`
`    Process: 9835 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)`
`        CPU: 16ms`

`Jun 09 12:41:46 home-server systemd[1]: Starting LSB: pihole-FTL daemon...`
`Jun 09 12:41:46 home-server pihole-FTL[9835]: Not running`
`Jun 09 12:41:46 home-server su[9845]: (to pihole) root on none`
`Jun 09 12:41:46 home-server su[9845]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)`
`Jun 09 12:41:46 home-server pihole-FTL[9847]: FTL started!`
`Jun 09 12:41:46 home-server su[9845]: pam_unix(su:session): session closed for user pihole`
`Jun 09 12:41:46 home-server systemd[1]: Started LSB: pihole-FTL daemon.`

**Jun 09 12:41:46 home-server pihole-FTL[9835]: Not running**

### Steps to reproduce

`sudo service pihole-FTL start`
`sudo service pihole-FTL status`

## Debug Token

- URL:   https://tricorder.pi-hole.net/2EyF4c7J/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
That output is the correct output for a nominal FTL. Is there something not working for you?

**Comment by eugef66** [comment]
I have noticed any functional issue, however I was under impression it had a “running” status on my older server running Ubuntu 20. I might be mistaken. If that is excepted output, please close this issue.
