### ISSUE TITLE
Version numbers not displayed correctly anymore in Chronometer

### ISSUE THREAD

**Issue by Jiab77** [pi-hole/pi-hole#4759]
### Versions

- Pi-hole:  5.10
- AdminLTE:  5.12
- FTL:  5.15

### Platform

- OS and version:  Ubuntu Focal 20.04

- Platform:  Raspeberry Pi

### Expected behavior

When running the `chronometer` feature at boot, I'm expecting to see at the top right:

```
Core: v5.10
Web: v512
FTL: v5.15
```

### Actual behavior / bug

But what I'm seeing currently is:

```
Core: ERROR
Web: ERROR
FTL: v5.15
```

### Steps to reproduce

1. Check line [#L230](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L230) in [chronometer.sh](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh)
2. Run the used command: `pihole -v -c 2> /dev/null`
3. See error

But if you run the same command with `sudo`, it will work as expected and return version numbers correctly.

### Screenshots

* `pi-hole` version command tests:

  ![image](https://user-images.githubusercontent.com/9881407/174452474-1fbde6f2-d741-4603-8cde-c8ed00c42351.png)

### Debug and solution

I then decided to dig a little bit further in the code and found that the version returned by `pihole -v -c` was in fact managed by [version.sh](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/version.sh) where the most interesting line was [#L32](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/version.sh#L32). It executes the command `git describe --tags --always` to get the version numbers.

But when I've tried to run it from the `/etc/.pihole` folder (variable `COREGITDIR`), I got the following error:

```
$ cd /etc/.pihole/
$ git describe --tags --always
fatal: unsafe repository ('/etc/.pihole' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /etc/.pihole
```

Which is true as the `/etc/.pihole` folder is owned by __root__.

I then did the same test for the LTE admin folder (variable `WEBGITDIR`) and got the same error:

```
$ cd /var/www/html/admin/
$ git describe --tags --always
fatal: unsafe repository ('/var/www/html/admin' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www/html/admin
```

So I ran the suggested commands and verified results for each other:

```
$ cd /etc/.pihole/
$ git config --global --add safe.directory /etc/.pihole
$ git describe --tags --always
v5.10
$ cd /var/www/html/admin/
$ git config --global --add safe.directory /var/www/html/admin
$ git describe --tags --always
v5.12
```

Which is a pretty good result! so after that the last test was to run again the command used by the `chronometer.sh` script:

```
$ pihole -v -c 2>/dev/null
  Current Pi-hole version is v5.10
  Current AdminLTE version is v5.12
  Current FTL version is v5.15
```

I then checked back to the Raspberry Pi screen running the `chronometer` feature and saw a correct display:

```
Core: v5.10
Web: v512
FTL: v5.15
```

Victory! Issue is now solved 🤘🏽

**Comment by dschaper** [comment]
Any of the `git` commands run by the scripts are done with `sudo` level permissions. I wouldn't expect a normal user account to be able to directly use them.

The issue may be that a change to the `pihole` command did not account for that fact and it is not elevating for `git` calls. `git config` changes should not be necessary. `pihole` can execute commands that only an elevated user should have access to.

**Comment by dschaper** [comment]
And my suspicions look correct.

https://github.com/pi-hole/pi-hole/pull/4663

@yubiuser Looks like `version` needs `sudo` as well.

**Comment by Jiab77** [comment]
Hi @dschaper , at least the issue was not existing for returning the `FTL` version so I suppose that was just something forgotten during the last release 😅

**Comment by yubiuser** [comment]
This is not about `version.sh` but a change in recent `git` two days after the PR has been merged.

https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by dschaper** [comment]
Jiab77, what version of `git` is installed on your system?

**Comment by Jiab77** [comment]
@dschaper , this version:

```
$ git --version
git version 2.25.1
```

**Comment by yubiuser** [comment]
> But maybe some security stuffs has been backported to this version by Ubuntu,

They did so.

https://changelogs.ubuntu.com/changelogs/pool/main/g/git/git_2.25.1-1ubuntu3.4/changelog

**Comment by Jiab77** [comment]
Good catch @yubiuser ! so things has been crossed and this created the issue?

**Comment by yubiuser** [comment]
Yeah. We removed the `sudo` to print the version information and `git` refuses to access `.git` if it's owned by someone else.

**Comment by yubiuser** [comment]
No, not really. We haven't decided yet how to go on. There are a few possibilities, each with their own drawbacks.

- re-add the `sudo` - not something I really want to do
- add `git config --global --add safe.directory /etc/.pihole` to the installer - not something I really want to do
- figure out a different mechanism to store and read the version info - needs to be coded (e.g. save them during checkout/installation/update in a file in `/etc/pihole`)

**Comment by yubiuser** [comment]
> figure out a different mechanism to store and read the version info - needs to be coded (e.g. save them during checkout/installation/update in a file in /etc/pihole)

This is the way to go now... https://github.com/pi-hole/pi-hole/pull/4959

**Comment by yubiuser** [comment]
Good idea. But this won't solve the underlying issue with `pihole -v`.

**Comment by yubiuser** [comment]
Should be fixed with https://github.com/pi-hole/pi-hole/releases/tag/v5.14

**Comment by Jiab77** [comment]
@yubiuser, thanks a lot for the fix!
