### ISSUE TITLE
No more internet access after changing router DNS settings

### ISSUE THREAD

**Issue by TimoVerbrugghe** [pi-hole/pi-hole#476]
Allright, just to be clear: installed pi-hole on a regular ubuntu server, not an actual raspberry pi. But setup is working before I change router DNS settings, so I don't think that this is a factor...
##### Expected Behaviour:

After changing router DNS settings, expecting Pihole to still be operating normally and server still being able to connect to the internet.
##### Actual Behaviour:

When I change my router's DNS settings (under WAN -> DNS, see here: http://s31.postimg.org/tmfj1em7v/test.png), all of my local network's clients are still able to access the internet normally. But the server that actually runs Pihole loses its internet access. It is still able to resolve IP addresses (nslookup google.com still gives google's IP) but the server isn't accessible anymore outside of the local network and server is unable to access any site outside the local network (wget google.com f.e. just stalls...).

I'm starting to think that I should only change my local network's DHCP server's DNS settings and not the WAN DNS settings... but since my router does not provide me with that option, I'm hoping for a different solution (where I don't need to manually put my server's IP address as DNS server in every device I have).
##### Steps to reproduce this issue:

Install Pihole, make sure it works on your local network by changing one device's DNS settings to point to server IP (check, working)
Change WAN DNS settings on router to server's IP address.
##

**Comment by Mcat12** [comment]
Can you run `pihole -d` and pastebin the log?

**Comment by TimoVer** [comment]
My server also has other services running on it, this is probably why pihole is hit with many 127.0.0.1 requests. Also, using apache as webserver, no lighttpd, so that's why lighttpd isn't installed. But admin page is showing up fine.

Debug Log when everything is working normally (aka my router DNS settings have google dns as both primary/secondary and I have manually changed DNS settings on my windows machine to my server's IP address -> ads get blocked in microsoft edge browser, tested by going to nyt.com & other website with bunch of ads): http://pastebin.com/EdFrFNtG

Debug log with problems (router DNS settings have IP address as primary DNS, windows machine set to automatically retrieve dns settings, server does not have access to outside internet anymore, can still access server on internal IP): http://pastebin.com/87qLwmBZ

**Comment by PromoFaux** [comment]
I'm not sure if it's causing conflicts or not as I've never actually tried myself...

but you have your `/etc/dnsmasq.conf` setup to have the following two lines in:
```
server=8.8.8.8
server=8.8.4.4
```

Which is also in `/etc/dnsmasq.d/01-pihole.conf`. You can safely remove (or comment out) those two lines in `/etc/dnsmasq.conf`

**Comment by TimoVer** [comment]
Allright, removed those lines from dnsmasq.conf (were manually added by me just to test if it would resolve the problem, but it didn't ;)).

Normal debug log: http://pastebin.com/0fAVvZA1
Debug log with problems: http://pastebin.com/p5NyFChj

**Comment by PromoFaux** [comment]
what's in your `/etc/resolv.conf`?

**Comment by TimoVer** [comment]
```
fileserver@Fileserver:~$ cat /etc/resolv.conf                                                           
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)                          
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN                                 
nameserver 127.0.0.1
```

Router: DIR-850L
Server is running Ubuntu Server 16.04

I cannot change the DNS settings of my (internal) LAN, only the WAN DNS settings. So screenshots of the LAN DHCP settings: http://s31.postimg.org/wlerbtl6j/lan_settings.png

Screenshot of the WAN DHCP settings: http://s31.postimg.org/mpi9px4sb/wan_settings.png

**Comment by dschaper** [comment]
@TimoVerbrugghe Hi Temo, are you still having issues with this install?

**Comment by TimoVerbrugghe** [comment]
Hi dschaper, my sincerest apologies for answering your question so late, but indeed, I am still having these problems.

Just to reiterate: I am only experiencing these problems when I set my server's IP as the router's WAN DHCP settings. When I manually enter my server's IP in Windows/iOS/Android DNS server settings, everything works normally.

I cannot change my lan DHCP DNS settings (http://s31.postimg.org/wlerbtl6j/lan_settings.png), but what I did was change my WAN DNS settings (http://s31.postimg.org/mpi9px4sb/wan_settings.png) and entered my server's IP.

From the moment I do that, I still retain my internet connection with all my local clients, but all internet connection is lost at my server running pi-hole. Also, pi-hole doesn't work anymore and my local clients start showing ads again (although my clients show that they are using my server as their DNS).

Latest debug log can be found here: http://pastebin.com/bMynQGLP

**Comment by TimoVerbrugghe** [comment]
I can also see from my logs that my router (10.124.161.93) does hit the pi-hole, but it was only for a limited amount of requests...

http://s32.postimg.org/e805lrnn9/pihole.png

**Comment by tsenovIvan** [comment]
Hello,

I want to report similar behavior with my d-link 880L.

This model also doesn't have separate setting for the DNS servers in the DHCP section. For that reason I'm also required to put the pi-hole IP into the "Internet" section of the router's settings.
Once I do it however, the pi-hole looses Internet connectivity - no ping, no trace, no pages. The moment I return the original Router settings, the pi-hole machine is back to normal.

I deactivated all Firewall settings of the router, and everything else I could think of, but nothing helped.

I decided that I will use the dnsmasq on the pi-hole machine as a DHCP server in my network and Hey! - everything is perfect now! Local machines get IPs from pi-hole and they use it as a DNS also.
I had to deactivate the DHCP server on the router of course, and also don't set the pi-hole machine as the router's DNS server.

My conclusion is that for some reason d-link routers don't like DNS IPs in the local network.

I am willing to corroborate if needed, but I guess this is a d-link issue.

**Comment by dschaper** [comment]
Thanks for the update and more information about this bug. Do you know if the ISP provided firmware for your router includes something along the lines of what's called `rebind` protection? 

I do applaud the use of dnsmasq on the Pi as your DHCP server, I think you'll find that it's a very capable package, and you'll be able to do a lot more customization with dnsmasq once you start to get to know it's functionality. And as you found, you do need to disable the DHCP on the router, as there needs to be only one authoritative DHCP server per network segment.

Do you know if your D-Link has a remote shell access ability? (Something like telnet or ssh? It may be helpful if we could get access to the routing information and iptables / firewall and see what the D-Link is set up for.)

**Comment by tsenovIvan** [comment]
Hello there,

I couldn't find any information about `rebind` protection for this router.
There is also no possibility to get some kind of terminal access to it.
Unfortunately, d-link routes are not very 'hackable' ... In my opinion, theirs new models have even less options than the older ones...

I'm sorry to disappoint you!

**Comment by WarlaxZ** [comment]
Just want to chime in that I have a DLINK DIR-850L - and I also experience this very same problem. Took me forever to figure out what it was!

**Comment by manuelsousa7** [comment]
Same problem with TP-LINK Archer D5

**Comment by unbaiat** [comment]
I can confirm that DLINK dir-636L won't accept any DNS server from the internal network.

**Comment by jacobsalmela** [comment]
[Other users on Discourse ](https://discourse.pi-hole.net/t/upstream-dns-opendns-custom-web-filtering-not-working/464/29)has reported issues with Dlink routers as well, so it seems to be an issue unrelated to Pi-hole.

**Comment by kilroy05** [comment]
Unfortunately the same thing happens on D-link DIR-868L
:)
Looks like I bought the wrong router

**Comment by Mcat12** [comment]
@kilroy05 Since this issue originally happened, we've exposed dnsmasq's DHCP server through the web interface. Try disabling the router's DHCP server and enable the one in Pi-hole's web interface.

**Comment by kilroy05** [comment]
Thanks @Mcat12 
I did notice that feature, however, I am running pihole in a virtual machine on my FreeNAS.
Lots of static IP addresses assigned on the network, shared drives etc.

**Comment by crico** [comment]
Hi @hernandito, could you share your settings in D-Link router and pi-hole? I have the  D-link DIR-868L and I have the same problem too :(

**Comment by teyou** [comment]
I find out that we need to **disable DNS relay** on the router setting

**Comment by etomboulian** [comment]
Encountered the same issue with my DIR-880L

Disabled DNS Relay in the menu Settings > Network  <--- Key Step

Then entering the IP of DNS server which is on local network into the DHCP settings works as expected.
