### ISSUE TITLE
Updating gravity DB throws "nc: command not found" error on rPi4

### ISSUE THREAD

**Issue by franz-josef-kaiser** [pi-hole/pi-hole#4764]
### Versions

- Pi-hole:  5.9
- AdminLTE:  5.11
- FTL:  5.14

### Platform
- OS and version:  Debian GNU/Linux 11 (bullseye), 5.15.32-v8+
- Platform:  Raspberry Pi, running as systemd service

### Expected behavior

Updating the gravity DB is possible without errors.

### Actual behavior / bug

``` 
/usr/local/bin/pihole: line 330: nc: command not found
```
Complete log

```
$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: …
…
  [✓] Creating new gravity databases
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 1289427 (1104244 unique domains)
  [i] Number of exact blacklisted domains: 3
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 6
  [i] Number of regex whitelist filters: 13
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

/usr/local/bin/pihole: line 330: nc: command not found       <<<<<<<< THE ACTUAL ERROR
  [✓] FTL is listening on port 
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

### Steps to reproduce

1. Open SSH Session
2. Update PiHole Gravity DB `pihole -g`

### Resolution

Install netcat: `sudo apt-get install -y netcat`

### Fix

Do not assume that `netcat`/`nc` is available. If it's non optional, prompt to install or install it during PiHole setup.

**Comment by yubiuser** [comment]
> If it's non optional, prompt to install or install it during PiHole setup.

We do:
https://github.com/pi-hole/pi-hole/blob/2735481da8fac3cb521338b7af2259da7b621e88/automated%20install/basic-install.sh#L313

**Comment by franz-josef-kaiser** [comment]
@yubiuser That must be a recent change. I just uninstalled `netcat`, upgraded PiHole and couldn't see that error again. Thanks anyway for your fast response!
```
$ pihole -v
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)
```
