### ISSUE TITLE
tracker-miner errors in syslog

### ISSUE THREAD

**Issue by seaniedan** [pi-hole/pi-hole#4774]
Like [this user](https://askubuntu.com/questions/1281399/ubuntu-20-04-1-tracker-miner-errors-in-syslog), I found a lot of errors to do with pihole in my syslog. I used 

`sudo mkhomedir_helper pihole
`and
`sudo touch /home/pihole/.trackerignore
`
to fix. Would including these in the install script help? I'm using 64 bit Raspbian (Bullseye) on pi4.

**Comment by jfb-pihole** [comment]
Please post the messages you are seeing in your syslog.

**Comment by seaniedan** [comment]
Oct  9 08:28:17 pihole2 tracker-store[1973]: Cannot initialize database: Could not open sqlite3 database:'/home/pihole/.cache/tracker/meta.db': unable to open database file
Oct  9 08:28:17 pihole2 systemd[1034]: tracker-store.service: Main process exited, code=exited, status=1/FAILURE
Oct  9 08:28:17 pihole2 systemd[1034]: tracker-store.service: Failed with result 'exit-code'.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &MUSIC. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &PICTURES. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &VIDEOS. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &DOWNLOAD. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &MUSIC. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &PICTURES. Ignoring this location.
Oct  9 08:28:17 pihole2 tracker-miner-f[1972]: Unable to get XDG user directory path for special directory &VIDEOS. Ignoring this location.

**Comment by seaniedan** [comment]
Using the Lite versioin (no Desktop).

**Comment by yubiuser** [comment]
Related issue reports on discourse:
https://discourse.pi-hole.net/search?q=Tracker-miner

**Comment by rdwebdesign** [comment]
Are you sure these errors are currently happening?

Log dates are **9 months old**: `Oct 9 08:28:17`.

**Comment by seaniedan** [comment]
I was getting these yesterday, the fix above worked but the reboot wiped my logs.

**Comment by dschaper** [comment]
> but the reboot wiped my logs.

Are you using ramlog?

**Comment by seaniedan** [comment]
OK, managed to find them with

less /var/log/syslog.1


un 26 00:00:39 vpn systemd[1]: logrotate.service: Succeeded.
Jun 26 00:00:39 vpn systemd[1]: Finished Rotate log files.
Jun 26 00:00:39 vpn systemd[1]: logrotate.service: Consumed 7.422s CPU time.
Jun 26 00:01:11 vpn systemd[1051]: tracker-miner-fs.service: start operation timed out. Terminating.
Jun 26 00:01:11 vpn systemd[1051]: tracker-miner-fs.service: Failed with result 'timeout'.
Jun 26 00:01:11 vpn systemd[1051]: Failed to start Tracker file system data miner.
Jun 26 00:01:11 vpn systemd[1051]: tracker-miner-fs.service: Scheduled restart job, restart counter is at 14802.
Jun 26 00:01:11 vpn systemd[1051]: Stopped Tracker file system data miner.
Jun 26 00:01:11 vpn systemd[1051]: Starting Tracker file system data miner...
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Set scheduler policy to SCHED_IDLE
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Setting priority nice level to 19
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &MUSIC. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &PICTURES. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &VIDEOS. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &DOWNLOAD. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &MUSIC. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &PICTURES. Ignoring this location.
Jun 26 00:01:11 vpn tracker-miner-f[256074]: Unable to get XDG user directory path for special directory &VIDEOS. Ignoring this location.
Jun 26 00:01:40 vpn tracker-miner-f[256074]: Couldn't create new Files miner: 'Failed to load SPARQL backend: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.Tracker1': timed out (service_start_timeout=120000ms)'
Jun 26 00:01:40 vpn systemd[1051]: tracker-miner-fs.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 00:01:40 vpn systemd[1051]: tracker-miner-fs.service: Failed with result 'exit-code'.
Jun 26 00:01:40 vpn systemd[1051]: Failed to start Tracker file system data miner.

**Comment by seaniedan-flwls** [comment]
This is a quick fix for the install script: add 
sudo mkhomedir_helper pihole and
sudo touch /home/pihole/.trackerignore

**Comment by seaniedan-flwls** [comment]
This is still and issue with an easy fix as described above - installer script needs updating.

**Comment by PromoFaux** [comment]
PRs are welcomed.

Are we sure this is an issue with the Pi-hole installer? Is this only on particular system setups? What would happen if these lines of code were to be run on a system unaffected by this issue?

**Comment by dschaper** [comment]
I'm not inclined to make those changes since we don't really want or need `/home/pihole` to exist. The issue is a problem with `tracker-miner` not behaving when users without shells don't have home directories.

**Comment by seaniedan** [comment]
You're right! I've made a New Issue over at [tracker-miner](https://gitlab.gnome.org/GNOME/tracker-miners/-/issues/232).

**Comment by seaniedan-flwls** [comment]
They replied! I hope this is useful, perhaps it's something we can fix, as it's clearly [annoying a lot of people](https://discourse.pi-hole.net/t/pihole-starts-tracker-miner-fs-service-and-runs-every-30-seconds/40148/7).

[Sam Thursfield](https://gitlab.gnome.org/sthursfield) [commented](https://gitlab.gnome.org/GNOME/tracker-miners/-/issues/232#note_1546735):

Hello, thanks for raising this. I don't have time to look now but here's some info:

tracker-miner-fs-3 is correct to fail with an error if there's no homedir
systemd is responsible for starting and restarting the service, seems that it's repeatedly doing that on failure
I suspect the answer would be to configure the systemd unit that starts tracker-miner-fs-3 to give the desired behaviour. Not immediately sure if that should happen in the default units that are supplied in tracker-miners.git or if it's something unique to the pihole setup.

**Comment by dschaper** [comment]
> [annoying a lot of people](https://discourse.pi-hole.net/t/pihole-starts-tracker-miner-fs-service-and-runs-every-30-seconds/40148/7).

I don't know if a discourse topic with one person is "a lot of people" but nonetheless. 

Is there a reason you're running Pi-hole on a system with a DE installed? We really target headless systems.

**Comment by seaniedan-flwls** [comment]
I'm running it headless. "Raspberry Pi OS Lite - No Desktop Environment".

**Comment by dschaper** [comment]
Then you should have neither gnome's desktop environment nor tracker-miner.

**Comment by seaniedan** [comment]
This is very helpful and appreciated, thank you. I **hope** you might help me debug this a little further, so I can direct my bug to the right place. 

I connect via ssh, and have no desktop:
```
cat /etc/X11/default-display-manager
cat: /etc/X11/default-display-manager: No such file or directory
```
However this looks like a gnome-session running:
```
$ ps aux | grep gnome-session
sean      663240  0.0  0.0   5912   696 pts/0    S+   07:00   0:00 grep --color=auto gnome-session

```
But what version gnome am I running?
```
$ gnome-about --gnome-version
-bash: gnome-about: command not found
```
Here's the list of software I've installed. I have been trying to figure out if the tracker-miner or Gnome was installed in Jellfin, but am stuck. Can you help? 

```
$ apt list --installed|grep -o '^\S*'|cut -d '/' -f 1

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Listing...
adduser
alsa-topology-conf
alsa-ucm-conf
alsa-utils
apt-listchanges
apt-transport-https
apt-utils
apt
at
attr
avahi-daemon
base-files
base-passwd
bash-completion
bash
bc
bind9-dnsutils
bind9-host
bind9-libs
binutils-aarch64-linux-gnu
binutils-common
binutils
bluez-firmware
bluez
bsd-mailx
bsdextrautils
bsdmainutils
bsdutils
build-essential
busybox
bzip2
ca-certificates
cifs-utils
console-setup-linux
console-setup
coreutils
cpio
cpp-10
cpp
cracklib-runtime
crda
cron
curl
dash
dbus-user-session
dbus
dc
dconf-gsettings-backend
dconf-service
debconf-i18n
debconf-utils
debconf
debian-archive-keyring
debianutils
device-tree-compiler
dhcpcd5
diffutils
dirmngr
distro-info-data
dmidecode
dmsetup
dns-root-data
dnsutils
dos2unix
dosfstools
dphys-swapfile
dpkg-dev
dpkg
e2fsprogs
ed
eject
ethtool
exfat-fuse
exfat-utils
fail2ban
fake-hwclock
fakeroot
fbset
fdisk
file
findutils
fio
firmware-atheros
firmware-brcm80211
firmware-libertas
firmware-misc-nonfree
firmware-realtek
flashrom
fontconfig-config
fonts-dejavu-core
fuse
g++-10
g++
gcc-10-base
gcc-10
gcc-9-base
gcc
gdb
gdisk
gettext-base
git-man
git
glib-networking-common
glib-networking-services
glib-networking
gnupg-l10n
gnupg-utils
gnupg
gpg-agent
gpg-wks-client
gpg-wks-server
gpg
gpgconf
gpgsm
gpgv
grep
grepcidr
groff-base
gsasl-common
gsettings-desktop-schemas
gzip
hardlink
hdparm
hfsprogs
hfsutils
hostname
htop
hwinfo
idn2
ifupdown
init-system-helpers
init
initramfs-tools-core
initramfs-tools
iozone3
iproute2
iptables-persistent
iptables
iputils-ping
isc-dhcp-client
isc-dhcp-common
iso-codes
iw
javascript-common
jellyfin-ffmpeg5
jellyfin-server
jellyfin-web
jellyfin
kbd
keyboard-configuration
keyutils
klibc-utils
kmod
less
libaacs0
libacl1
libaio1
libalgorithm-diff-perl
libalgorithm-diff-xs-perl
libalgorithm-merge-perl
libapparmor1
libapt-pkg6.0
libarchive13
libargon2-1
libasan6
libasound2-data
libasound2
libass9
libassuan0
libatasmart4
libatomic1
libatopology2
libattr1
libaudit-common
libaudit1
libavahi-client3
libavahi-common-data
libavahi-common3
libavahi-core7
libbabeltrace1
libbdplus0
libbinutils
libblkid1
libblockdev-crypto2
libblockdev-fs2
libblockdev-loop2
libblockdev-part-err2
libblockdev-part2
libblockdev-swap2
libblockdev-utils2
libblockdev2
libbluray2
libboost-filesystem1.74.0
libboost-iostreams1.74.0
libboost-program-options1.74.0
libboost-regex1.74.0
libboost-thread1.74.0
libbpf0
libbrotli-dev
libbrotli1
libbsd0
libbz2-1.0
libc-bin
libc-dev-bin
libc-devtools
libc-l10n
libc6-dbg
libc6-dev
libc6
libcairo2
libcamera-apps-lite
libcamera0
libcap-ng0
libcap2-bin
libcap2
libcbor0
libcc1-0
libcephfs2
libcom-err2
libcrack2
libcrypt-dev
libcrypt1
libcryptsetup12
libctf-nobfd0
libctf0
libcue2
libcups2
libcurl3-gnutls
libcurl4
libdaemon0
libdaxctl1
libdb5.3
libdbus-1-3
libdbus-glib-1-2
libdconf1
libdebconfclient0
libdebuginfod1
libdeflate0
libdevmapper1.02.1
libdns-export1110
libdpkg-perl
libdrm-amdgpu1
libdrm-common
libdrm-nouveau2
libdrm-radeon1
libdrm2
libdvdread8
libdw1
libebml5
libedit2
libelf1
libencode-locale-perl
liberror-perl
libestr0
libevent-2.1-7
libexempi8
libexif12
libexiv2-27
libexpat1-dev
libexpat1
libext2fs2
libfakeroot
libfastjson4
libfdisk1
libfdt1
libffi7
libfftw3-single3
libfido2-1
libfile-fcntllock-perl
libfile-listing-perl
libfl2
libflac8
libfmt7
libfontconfig1
libfreetype-dev
libfreetype6-dev
libfreetype6
libfribidi0
libfstrm0
libftdi1-2
libfuse2
libgcc-10-dev
libgcc-s1
libgcrypt20
libgd3
libgdbm-compat4
libgdbm6
libgexiv2-2
libgfapi0
libgfrpc0
libgfxdr0
libgif7
libgl1-mesa-dri
libgl1
libglapi-mesa
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libglusterfs0
libglvnd0
libglx-mesa0
libglx0
libgmp10
libgnutls30
libgomp1
libgpg-error0
libgpgme11
libgraphite2-3
libgsasl7
libgsf-1-114
libgsf-1-common
libgssapi-krb5-2
libgstreamer-plugins-base1.0-0
libgstreamer1.0-0
libgudev-1.0-0
libgxps2
libharfbuzz0b
libhd21
libhogweed6
libhtml-parser-perl
libhtml-tagset-perl
libhtml-tree-perl
libhttp-cookies-perl
libhttp-date-perl
libhttp-message-perl
libhttp-negotiate-perl
libibverbs1
libicu67
libidn11
libidn2-0
libimobiledevice6
libio-html-perl
libio-socket-ssl-perl
libio-stringy-perl
libip4tc2
libip6tc2
libiptcdata0
libisc-export1105
libisl23
libitm1
libiw30
libjansson4
libjbig0
libjim0.79
libjpeg62-turbo
libjs-jquery
libjs-sphinxdoc
libjs-underscore
libjson-c5
libjson-glib-1.0-0
libjson-glib-1.0-common
libk5crypto3
libkeyutils1
libklibc
libkmod2
libkrb5-3
libkrb5support0
libksba8
liblcms2-2
libldap-2.4-2
libldap-common
libldb2
libllvm11
liblmdb0
liblocale-gettext-perl
liblockfile-bin
liblockfile1
liblognorm5
liblsan0
liblua5.2-0
libluajit-5.1-2
libluajit-5.1-common
liblwp-mediatypes-perl
liblwp-protocol-https-perl
liblz4-1
liblzma5
libmagic-mgc
libmagic1
libmariadb3
libmatroska7
libmaxminddb0
libmd0
libmnl0
libmount1
libmp3lame0
libmpc3
libmpdec3
libmpfr6
libmtp-common
libmtp-runtime
libmtp9
libncurses6
libncursesw6
libndctl6
libnet-http-perl
libnet-ssleay-perl
libnetfilter-conntrack3
libnettle8
libnewt0.52
libnfnetlink0
libnfsidmap2
libnftables1
libnftnl11
libnghttp2-14
libnl-3-200
libnl-genl-3-200
libnl-route-3-200
libnpth0
libnsl-dev
libnsl2
libnspr4
libnss-mdns
libnss3
libntfs-3g883
libntlm0
libnuma1
libogg0
libopenjp2-7
libopus0
liborc-0.4-0
libosinfo-1.0-0
libp11-kit0
libpam-chksshpwd
libpam-modules-bin
libpam-modules
libpam-runtime
libpam-systemd
libpam0g
libparted-fs-resize0
libparted2
libpcap0.8
libpci3
libpcre2-8-0
libpcre2-posix2
libpcre3
libpcsclite1
libperl5.32
libpipeline1
libpixman-1-0
libplist3
libpmem1
libpmemblk1
libpng-dev
libpng-tools
libpng16-16
libpod-parser-perl
libpolkit-agent-1-0
libpolkit-gobject-1-0
libpoppler-glib8
libpoppler102
libpopt0
libprocps8
libprotobuf-c1
libproxy1v5
libpsl5
libpugixml1v5
libpython3-dev
libpython3-stdlib
libpython3.9-dev
libpython3.9-minimal
libpython3.9-stdlib
libpython3.9
libqrencode4
libquvi-0.9-0.9.3
libquvi-scripts-0.9
librados2
libraspberrypi-bin
libraspberrypi-dev
libraspberrypi-doc
libraspberrypi0
librbd1
librdmacm1
libreadline8
librtmp1
libsamplerate0
libsasl2-2
libsasl2-modules-db
libsasl2-modules
libseccomp2
libsecret-1-0
libsecret-common
libsecret-tools
libselinux1
libsemanage-common
libsemanage1
libsensors-config
libsensors5
libsepol1
libslang2
libsmartcols1
libsodium23
libsoup2.4-1
libsource-highlight-common
libsource-highlight4v5
libsqlite3-0
libss2
libssh2-1
libssl1.1
libstdc++-10-dev
libstdc++6
libstemmer0d
libsystemd0
libtalloc2
libtasn1-6
libtdb1
libtevent0
libtext-charwidth-perl
libtext-iconv-perl
libtext-wrapi18n-perl
libtheora0
libtiff5
libtimedate-perl
libtinfo6
libtirpc-common
libtirpc-dev
libtirpc3
libtotem-plparser-common
libtotem-plparser18
libtracker-control-2.0-0
libtracker-miner-2.0-0
libtracker-sparql-2.0-0
libtry-tiny-perl
libtsan0
libubsan1
libuchardet0
libudev1
libudfread0
libudisks2-0
libunistring2
libunwind8
libupower-glib3
liburi-perl
liburing1
libusb-1.0-0
libusbmuxd6
libutempter0
libuuid1
libuv1
libv4l-0
libv4l2rds0
libv4lconvert0
libva-x11-2
libva2
libvdpau-va-gl1
libvdpau1
libvolume-key1
libvorbis0a
libvorbisenc2
libvorbisfile3
libvpx6
libvulkan1
libwayland-client0
libwbclient0
libwebp6
libwebpmux3
libwrap0
libwww-perl
libwww-robotrules-perl
libx11-6
libx11-data
libx11-xcb1
libx264-160
libx265-192
libxau6
libxcb-dri2-0
libxcb-dri3-0
libxcb-glx0
libxcb-present0
libxcb-randr0
libxcb-render0
libxcb-shm0
libxcb-sync1
libxcb-xfixes0
libxcb1
libxdamage1
libxdmcp6
libxext6
libxfixes3
libxml-dumper-perl
libxml-parser-perl
libxml2
libxmuu1
libxpm4
libxrender1
libxshmfence1
libxslt1.1
libxtables12
libxxf86vm1
libxxhash0
libyaml-0-2
libz3-4
libzstd1
libzvbi-common
libzvbi0
lighttpd
linux-base
linux-libc-dev
locales
login
logrotate
logsave
lsb-base
lsb-release
lshw
lsof
lsscsi
lua-bitop
lua-expat
lua-json
lua-lpeg
lua-socket
lua5.1
luajit
mailcap
make
man-db
manpages-dev
manpages
mariadb-common
mawk
media-types
mesa-va-drivers
mesa-vdpau-drivers
mesa-vulkan-drivers
mime-support
mksh
mkvtoolnix
mount
msmtp-mta
msmtp
mysql-common
nano
ncal
ncdu
ncurses-base
ncurses-bin
ncurses-term
net-tools
netatalk
netbase
netcat-openbsd
netfilter-persistent
nethogs
nfs-common
nfs-kernel-server
nftables
ntfs-3g
nvme-cli
openresolv
openssh-client
openssh-server
openssh-sftp-server
openssl
osinfo-db
p7zip-full
p7zip
parted
passwd
patch
pci.ids
pciutils
perl-base
perl-modules-5.32
perl-openssl-defaults
perl
php-cgi
php-common
php-intl
php-json
php-sqlite3
php-xml
php7.4-cgi
php7.4-cli
php7.4-common
php7.4-intl
php7.4-json
php7.4-opcache
php7.4-readline
php7.4-sqlite3
php7.4-xml
pi-bluetooth
pigz
pinentry-curses
pkg-config
policykit-1
poppler-data
procps
psmisc
publicsuffix
python-apt-common
python-is-python3
python-pip-whl
python3-apt
python3-certifi
python3-cffi-backend
python3-chardet
python3-colorzero
python3-cryptography
python3-dbus
python3-debconf
python3-dev
python3-distro-info
python3-distro
python3-distutils
python3-dnspython
python3-gpg
python3-gpiozero
python3-idna
python3-ldb
python3-lib2to3
python3-markdown
python3-minimal
python3-pip
python3-pkg-resources
python3-pygments
python3-pyinotify
python3-requests-toolbelt
python3-requests
python3-rpi.gpio
python3-samba
python3-setuptools
python3-six
python3-spidev
python3-systemd
python3-talloc
python3-tdb
python3-urllib3
python3-wheel
python3-yaml
python3.9-dev
python3.9-minimal
python3.9
python3
qrencode
raspberrypi-archive-keyring
raspberrypi-bootloader
raspberrypi-kernel
raspberrypi-net-mods
raspberrypi-sys-mods
raspi-config
raspi-gpio
raspinfo
readline-common
rename
rfkill
rng-tools-debian
rng-tools
rpcbind
rpi-eeprom
rpi-update
rpi.gpio-common
rsync
rsyslog
runit-helper
samba-common-bin
samba-common
samba-dsdb-modules
samba-libs
samba-vfs-modules
samba
screen
sdparm
sed
sensible-utils
shared-mime-info
smartmontools
ssh-import-id
ssh
strace
sudo
systemd-sysv
systemd-timesyncd
systemd
sysvinit-utils
tar
tasksel-data
tasksel
tdb-tools
tracker-extract
tracker-miner-fs
tracker
triggerhappy
tzdata
ucf
udev
udisks2
unattended-upgrades
unzip
upower
usb-modeswitch-data
usb-modeswitch
usb.ids
usbmuxd
usbutils
userconf-pi
util-linux
uuid-runtime
v4l-utils
va-driver-all
vdpau-driver-all
vim-common
vim-tiny
wamerican
wget
whiptail
whois
wireguard-tools
wireless-regdb
wireless-tools
wpasupplicant
xauth
xkb-data
xxd
xz-utils
zip
zlib1g-dev
zlib1g
```

**Comment by dschaper** [comment]
The `systemctl` tools might help here. Try `systemctl list-dependencies` or some of the other verbs like `systemctl status`. Might also be able to check the journal `journalctl` to find failed services. The linked issue said something about `systemd` restarting the service over and over again so I think there would be some junk in the journal that could help.
