### ISSUE TITLE
Pihole & Windows 10 = No Internet Connection and more

### ISSUE THREAD

**Issue by fatez** [pi-hole/pi-hole#478]
Hi,

Pihole up and running fine on Raspberry pi, but when i run windows 10 the following happens : 
- No internet Connection
- The browser open itself on : http://www.msn.com/it-it/?ocid=wispr

http://imgur.com/JBxpqMr

**Comment by manuelgu** [comment]
There is a [wiki article](https://github.com/pi-hole/pi-hole/wiki/FAQs#windows-thinks-there-is-no-internet-connection-but-there-is-one-315) about this.

Does this solve your issue?

**Comment by fatez** [comment]
solved thanks a lot

**Comment by PromoFaux** [comment]
It's at the top of the FAQs for a reason :)

**Comment by fatez** [comment]
I did not see it :(

last problem : installed linux-dash before pihole and it work well but after pihole i see only a white page.

**Comment by manuelgu** [comment]
I haven't looked at linux-dash in detail, but I assume that there is an issue with the ports since (most likely) both listen to :80

**Comment by PromoFaux** [comment]
Yeah, looks like it defaults to port 80.

Change the linux-dash port to something else, as we need port 80 in order to send return the blank page in place of ads :)

as you're running in PHP mode, are you using apache/lighttpd/nginx to host it?

**Comment by fatez** [comment]
I only run lighttpd (pihole installation) btw i can't change port in linux-dash
need i to reconfigure lighttpd whit a 81 port for linux-dash?

**Comment by manuelgu** [comment]
> i can't change port in linux-dash

What makes you think that? If you run in PHP mode then there needs to be a configuration for it somewhere, depending on what software you use.

> need i to reconfigure lighttpd whit a 81 port for linux-dash?

Or any other valid port other than ports that are already occupied.

**Comment by PromoFaux** [comment]
> What makes you think that?

I'm guessing he means in the application itself. But yeah @fatez reconfiguring lighttpd will do it.

**Comment by fatez** [comment]
So...

I reconfigured lighttpd to run on port 81 like :
$SERVER["socket"] == ":81" {
        server.document-root       = "/var/www/html/linux-dash"
server.error-handler-404        = "/var/www/html/linux-dash"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename                      = "/var/log/lighttpd/access.log"
accesslog.format                        = "%{%s}t|%V|%r|%s|%b"


index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
}


Linux-Dash run fine on port 81 but still remain a blank page.

can You give it a try too?
https://github.com/afaqurk/linux-dash

**Comment by dschaper** [comment]
Try updating server.port to 81 and see if that solves your problem with Dash.

**Comment by fatez** [comment]
sorry for the mistake, but no : does'nt work

**Comment by dschaper** [comment]
Just for tracking purposes and to help us keep things orderly, can you open a new issue and we'll close out this one. The two issues are unrelated and reusing old, closed issues causes confusion. Closing this issue for now.
