### ISSUE TITLE
Adding non-trivial Regex to blacklist works via GUI but not via CLI

### ISSUE THREAD

**Issue by scrut** [pi-hole/pi-hole#4785]
### Versions

- Pi-hole:  v5.10 
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform

- **OS and version**:  Raspbian GNU/Linux 11 (bullseye)

- **Platform**:  Raspberry Pi 3, Model B

### Expected behavior

At https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178, user 3-M has provided a list of non-trivial Blacklist Regex. It SHOULD be possible to add these via CLI (**pihole --regex '<regex>' --comment "<comment>"**) AND via the Web Frontend (**Blacklist -> Regex-Filter -> Copy & Paste -> Add to Blacklist**)

### Actual behavior / bug

It IS possible to add all these non-trivial Regex to the Blacklist via the Web Frontend.

However, when trying to add them via CLI, most (but not all) result in an error message ("**... is not a valid argument or domain name!**")

### Steps to reproduce

1. SSH into the OS of the machine on which Pihole runs
2. Execute the below CLI commands (or a subset thereof):
4. See error ...is not a valid argument or domain name!

pihole --regex '(.*)\.g00\.(.*)' --comment "From https://www.reddit.com/r/pihole/comments/b3fj60/regex_megathread/eiz77s3/"

pihole --regex '^(.*\.)*(sonobi|contentabc|exponential|bebi|3lift|leanplum|hotjar|m-pathy|parsely|exelator|touchcommerce|magnetic|exosrv|go2affise|mgid|clksite|tynt|inclk|bidswitch|optimizely|tiqcdn|maxymiser|9xiazaiqi|siquality|snwxn|8wix|tudown|psdzy|bankofamericaslpemr|cloudns|pfa.levexis)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(dotomi|urbanairship|criteo|yimg|footprint|sitescout|turn|w55c|openx|voluumtrk|videoplaza|inmobi|reporo|cnzz|skim(resources|links)|tribalfusion|getsocial|hoverr|mediaplex|auditude|tacoda|puserving|d(e|o)mdex)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(buffpanel|redshell|treasuredata|unity(ads|3d)|evidon|flashtalking|mathtag|mediamath|scorecardresearch|yieldmanager|sharezips|liveadvert|mktoresp|online-metrix|mobileapptracking|webengage|mpstat|trafficjunky|alphonso|stickyadstv|marketo|tubemogul|kameleoon|24s|0x1f4b0)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(petametrics|localytics|onthe|newrelic|casalemedia|tidaltv|newsinc|nr-data|tapad|crazyegg|vserv|solocpm|ojrq|getclicky|narrative|7eer|evyy|impactradius|redtrack|content-ad|sharethrough|getui|pro-market|albacross|evergage|araleg|districtm|singular|dynamicyield|smrtb|everesttech|snapchatprime)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(perimeterx|coremetrics|veinteractive|netcoresmartech|vungle|batmobi|marinsm|igexin|keywordblocks|facebook-info|freecontent|hostingcloud|360safe|axiatraders|beginads|ero-advertising|inteleksys|joodfbnm*[0-9]*|nbrwer*[0-9]*|usergrid|trackersimulator|tapjoy|supercell|bluekai|chartboost|atues|duilawyeryork|bannerflow|bmmetrix|flagcounter)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(segment|braze|amplitude|emetriq|buysellads|ioam|ensighten|eulerian|dnsdelegation|clicktale|samsungads|userlike|summerhamster|sourcepoint|adobetm|pcapredict|syscation|infosupports|arrowservice|bigdepression|earthsolution|firefoxupdata|infobusinessus|yahoodaily|newsonet|worthhummer|purpledaily|blackcake|msnhome)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(inmobicdn|jizzads|leadbolt|nexage|milleniamedia|mobfox|mobilityware|newrelic|propellerads|revd(depo|sci)|segment|serving-sys|sharethis|startapp|steelhousemedia|tapjoy|viglink|webterren|adtaily|zedo|liadm|exposebox|jazdoxthxiv|jwmwtcmexc|thetradedesk||rocketfuel|ignitionone|komoot|squarelovin|cookiebot)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(aatkit|abtasty|acce(ngage|sstrade)|adtec(h|jp|us)|anthill|atdmt|avazutracking|bfmino|bounceexchange|branch|clever(push|tap)|conviva|crittercism|cxense|deltadna|duapps|fractionalmedia|fyber|hyprmx|justpremium|lijit|mobileapptracking|ogury|omniture|presage|tapad|pubmatic|pushwoosh|qq|servedbyopenx|supersoni(c|cads)|swrve|webtrekk|aimatch|sas)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(actioniq|hs-(analytics|banner)|hsleadflows|hubspot|agileone|bizible|crazyegg|acquia|wistia|engagio|lytics|am15|bannerbank|bbelements|bravenet|cedexis-radar|crypto-loot|economicoutlook|esomniture|estat|extreme-dm|ezcybersearch|fastclick|focalink|gemius|hyperbanner|iovation|kaffnet|yieldlove|histats|forsee)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(indexww|yieldlove-ad-serving|xplosion|digitru|upapi|spotxchange|permutive|onesignal|usabilla|contextweb|ml314|afcpatrk|(klclick[0-9])|aidata|hybrid|deployads|perfectaudience|liveramp|didomi|etahub|giraff|hurra|sizmek|nativo|djaxadserver|webmasterplan|ggpht|zanox|audrte|agkn|dataxu|scarabresearch|ekomi)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(apsalar|tune|qualtrics|neustar|webtrends|linksynergy|backtrace|doubleverify|ligatus|a4|rayjump|umeng|umengcloud|wootric|medialytics|herokuapp|yllix|mobpartner|combango|bugsense|burstly|count|crashlytics|do-not-tracker|eviltracker|getexceptional|jumptap|playtomic|stathat|163|206ads|2mdnsys|360in|4seeresults|accesstrade|ads[0-9]-adnow|pop(ads|cash)|popadscdn)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(urekamedia|kochava|upsight|marfeel(cache|cdn|rev|tenmax)|blueseed|adx[0-9]|zucks|o-s|aralego|breaktime|mdotm|juicer|cnt|ematicsolutions|alcmpn|powerlinks|33across|1rx|bfmio|bnmla|doublepimp|weborama|specific(click|media)|acuityplatform|cnnx|scanscout|nxtck|socdm|simpleanalytics|gumgum|marketolive|demandbase|izooto|ibillboard)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(invitemedia|microad|ardata|152media|exoclick|doublemax|wywy|navdmp|trafficstars|pubexchange|vdopia|lsosad|aaxads|mantisadnetwork|triplelift|trafficfactory|themoneytizer|insurads|proads|pxlad|flux-adserve|eclick|vcmedia|nova(net|onads|on|nox)|coccoc|polyad|cleverads|ambient-platform|mangoads|cityads|autoads|yoads)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(oewabox|metriweb|caramb(o|ola)|refinedads|klaviyo|a-mo|fieldtest|justuno|smartredirect|ezoic|statscrop|optinmonster|nr-data|avocet|bttrack|eyeota|jetlore|1up|abmr|acxiom-online|mlnadvertising|amgdgt|askmen|bam-x|bidr|bluecava|brand-display|brilig|ccgateway|channelintelligence|choicestream|clickagy|cognitivlabs|collective-media)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(company-target|crosspixel|crsspxl|decdna|decideinteractive|disqus|emxdgt|extremetech|eyeviewads|btbuckets|fetchback|fimserve|freeskreen|gmads|gwallet|hlserve|imiclk|innovid|insidecrm|intentmedia|interclick|ipr(edictive|omote)|iqm|kargo|knorex|lkqd|logicbuy|marchex|media6degrees|mediaforge|mediaiqdigital|mixpo|mmismm|numberly|1000mercis)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(mxptint|ncaudienceexchange|net(mng|seer)|owneriq|parrable|pm14|postrelease|pro-market|raasnet|retargetly|revsci|rfihub|rkdms|ru4|samba|semasio|sojern|udmserve|unrulymedia|vindicosuite|vmmpxl|vmweb|wsod|xad|xgraph|yieldmo|yieldoptimizer|youknowbest|zemanta|skimlinks|ipromote|lotame|contentsquare|matomo|piwik|roq|emerse|widespace)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(nrich|rtbhouse|sovrn|beeswax|indexexchange|c3metrics|contactimpact|1plusx|semrush|improvedigital|xandr|madvertise|neural|rhythmone|inskinmedia|jivox|gsi-one|celtra|tapfiliate|req|moburst|webmechanix|divisionoflabor|commcreative|metrictheory|gkv|periscope|yieldbranding|gumas|fivebyfiveglobal|williamswhittle|baycreative|milleradagency)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(farinella|wearesculpt|neonambition|envision-creative|tronviggroup|databricks|gotomarketers|maxaudience|perfectsearchmedia|titangrowth|3mediaweb|directom|seobrand|disruptiveadvertising|bigleap|silverbackstrategies|ignitevisibility|thriveagency|webfx|seoinc|socialseo|frac|klientboost|avalaunchmedia|siegemedia|straightnorth|gulosolutions|grafik)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(thestorywebs|directiveconsulting|pbjmarketing|befoundonline|walkersandsdigital|firebellymarketing|comradeweb|contentbureau|hanapinmarketing|fruition|digitalbrandexpressions|noblestudios|thoughtspot|collibra|erne|uimserv|belboon)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"
pihole --regex '^(.*\.)*(app(boy|next|adhoc|celerator|ier|odeal|lovin|nexus|sflyer|boy|brain|ier|lvn|spot|timize|see|ads|lifier|lift|logrocket|-measurement|topia))\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(ad(j|skeeper|dtoany|vertica|true|vertnative|pushup|media|master|ledge|kernel|kmob|future|bro|booth|ap|apt|4game|just|telligent|4mat|tng|alliance|link|marketplace|[0-9]|adapted|acado|alliance|alyser|brite|bureau|and|blade|brodealsnetwork|spirit|epom|lightning|plugg|glare|speed|butler|x|roll|port|river|srvr|advisor|symptotic|dthis|rtx|scale))\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(ad(smogo|target|infuse|conversantmedia|now|view|ups|tim(a|aserver|ming)|srv|spruce|see|same|sniper|smoloco|shot|skeeper|x1|tdp|hese|lightning|micro|entifi|ventori|worx|zerk|roll|safeprotected|this|colony|tech[a-z]{1,2}|dthisedge|looxtracking|vertising|nxs|(ds|s)wizz|omik|k2x|k2|ition|this|form|ocean|protect|science|tlgc|vertserve|thrive))\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(ad(netasia|clixx|hacker|xcorp|vergine|optimize|grx|sfactor|snative|op|high|xxx|schoom|recover|spsp|safety|marvel|brix|servme|flex|rcdn|maym|pone|xadserv|up-tech|timaserver|network|tima|360|pia|sota|splay|sparc|legend|chemy|haven|ready|viva|gear|ikteev|dapptr|defend|ventureppc))\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

pihole --regex '^(.*\.)*(ad-(balancer|brix|center|cloud|delivery|delivery|locus|maven|move|plus|score|srv|stir))\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"
pihole --white-regex '^(.*\.)*(dpd|ups|dhl|safelinking|githubusercontent|researchintel|intel|github|foldingathome|sysctl|apple-dns|apple|icloud|windowsupdate|samsung(electronics|otn|acr|cloudsolution|qbe)|plex|office|msftncsi|microsoftonline|dropbox|pr0gramm|solvemedia|microsoft|tnt-digital|fedex|creative)\.([a-z]{2,3}\.)*[a-z]{2,6}$' --comment "From https://discourse.pi-hole.net/t/collection-of-regex-for-blacklisting/43178"

## Debug Token

- URL:  https://tricorder.pi-hole.net/TCQRXAUJ/

### Screenshots

![pihole](https://user-images.githubusercontent.com/6234417/177569047-05a89d14-ffe5-4023-8ba2-f8e9110a160d.jpg)

### Additional context

none

**Comment by yubiuser** [comment]
Thanks for your report. The difference is that we do not check the regex added via the web interface for validity before adding them. However, from the command line, we have a length check that limits everything to 253 characters. (We do have the same check for the web interface on regular domains)

https://github.com/pi-hole/pi-hole/blob/bacb98be325253a1ddfcc2275f8597219bb0af14/advanced/Scripts/list.sh#L105

I'll write a fix.

P.S. Your first to RegEx can already be added with issue - the are not too long.

**Comment by scrut** [comment]
Wow, thanks for your super quick reply. May I propose 2 alterations then?
1. Add a validator to the web interface
2. Add a different error message for length>253 to both the CLI as well as the web interface. The current message "... is not a valid argument or domain name!" is misleading: the regex might very well be valid, but it's just too long. So the message should say something like "... is not a valid argument because it is too long. Regular Expressions may not exceed 253 characters."

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.11
