### ISSUE TITLE
2 domains being blocked after a few weeks of usage

### ISSUE THREAD

**Issue by iggi131** [pi-hole/pi-hole#479]
After fresh new install everything was working fine (default install, no black/white list changes). After a few weeks, ads were not blocked anymore. This happened already twice.

Pi-hole Version v2.6.1.2 Web Interface Version v1.2

/admin/api.php:
{"domains_being_blocked":"2","dns_queries_today":"730","ads_blocked_today":"0","ads_percentage_today":"0.0"}

gravity.list:
192.168.1.16 raspberrypi
fe80::1a07:a867:5a42:7f40 raspberrypi
192.168.1.16 pi.hole
fe80::1a07:a867:5a42:7f40 pi.hole

**Comment by PromoFaux** [comment]
Time for an update... :) We fixed that in [2.6.2](https://github.com/pi-hole/pi-hole/wiki/Changelog#262---2016-04-11)

**Comment by PromoFaux** [comment]
Basically, `cron` did not like the `spinner` function in `gravity.sh`, so it was falling over.

**Comment by iggi131** [comment]
Thanks. Will do the update.

**Comment by PromoFaux** [comment]
@iggi131 Did this fix your issue?

**Comment by iggi131** [comment]
So far it's working fine. Thanks.
