### ISSUE TITLE
pihole -v reports wrong version, along with web interface and everywhere else

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pi-hole/pi-hole#4799]
### Versions
- Pi-hole:  v5.11.3 (Latest: v5.11.3)
- AdminLTE:  v5.13 (Latest: v5.13)
- FTL:  v15.6.1 (Latest: v15.6.1)
- _(I think the FTL version should be v5.16, which I have just updated to)_

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behaviour

Display the correct FTL version number

### Actual behavior / bug

FTL version number is v15.6.1, where it should have been v5.16 as I have just updated

### Steps to reproduce

Steps to reproduce the behaviour:

1. `pihole -up` to update pihole to the latest version
2. Note that the text displayed shows that pi-hole FTL has version v15.6.1
3. `pihole -v` shows that the version of FTL is v15.6.1
4. This issue also appears in `pihole -r` repair

## Debug Token

- URL:  https://tricorder.pi-hole.net/mn0tXAG9/

### Screenshots

![Shell output](https://user-images.githubusercontent.com/64138578/177947009-52db726c-b891-48c2-9f21-58b42eb09873.png)
![Web interface](https://user-images.githubusercontent.com/64138578/177947187-0079f53b-acaa-453e-9591-991dfa2fef4c.png)

### Additional context

Does it seem that there's a typo of some sort?

Also related to: [this reddit comment](https://www.reddit.com/r/pihole/comments/vtqpi5/comment/ifbh0cw/?utm_source=share&utm_medium=web2x&context=3)

**Comment by yubiuser** [comment]
This was a typing error while tagging the release. Please try again, should be fixed already.

**Comment by yubiuser** [comment]
Oh I see you already upgraded during the small window with the wrong tag...

**Comment by PromoFaux** [comment]
Ah-hah, a victim! Sorry about this, I somehow managed to type `15.6.1` instead of `5.16.1` when tagging the release!

I was hoping that nobody managed to update in the short period before it was pointed out, but lets try and get you back to the correct version....

I don't have a system with this tag on, so a bit of guesswork may be needed... can you try `pihole checkout ftl development` followed by `pihole checkout ftl master`?

**Comment by SodaWithoutSparkles** [comment]
well, I guess this is classified as "This feature is NOT supported unless a Pi-hole developer explicitly asks!"

![shell output](https://user-images.githubusercontent.com/64138578/177951009-ad817793-52fd-49c8-9082-c5eb1568c456.png)

That seems to have fixed it, but the web interface hasn't been updated yet. I am now repairing the installation and will see if it is fine.

BTW it seems that I could not find the `get_FTL_version()` function despite it being mentioned everywhere. I was trying to debug the issue. That should exist somewhere given that the code compiles without error...

**Comment by SodaWithoutSparkles** [comment]
UPDATE: the web interface is now fixed. I have updated the Reddit comment linked above. I have also linked the `checkout` fix as a solution.

**Comment by yubiuser** [comment]
> BTW it seems that I could not find the get_FTL_version() function despite it being mentioned everywhere.

Where is this function mentioned? 
It's part of the FTL code
https://github.com/pi-hole/FTL/blob/5ff5bed9f86afe81ba7640170763225fa4cbbcef/src/log.c#L293

**Comment by SodaWithoutSparkles** [comment]
Oh that was not a assign varable call but a function definition, I thought it was a variable as it is a const and missed it. Everyday I learn something new.
