### ISSUE TITLE
Duplicate code to create log directory

### ISSUE THREAD

**Issue by jamieburchell** [pi-hole/pi-hole#4803]
You are creating the log directory again [here](https://github.com/pi-hole/pi-hole/blob/a28d691387ebbe8bc2e017dd9b10b7a16284541d/automated%20install/basic-install.sh#L2817) when it is already always created (and with permissions set) [here](https://github.com/pi-hole/pi-hole/blob/a28d691387ebbe8bc2e017dd9b10b7a16284541d/automated%20install/basic-install.sh#L2800) . The first time it is created doesn't have the `-p` switch.

You can also set the mode at the same time as creation `mkdir -p -m mode directory`

**Comment by yubiuser** [comment]
The duplicated code should be no problem. The missing `-p` is a problem...

**Comment by rdwebdesign** [comment]
The command can be changed to:

```
mkdir -m 0755 /var/log/pihole/
```

There's no need for `-p` since we know the directory doesn't exist.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.11.4
