### ISSUE TITLE
Set static IP using custom values results in error

### ISSUE THREAD

**Issue by balazshorvath** [pi-hole/pi-hole#4807]
### Versions
Pi-hole version is v5.11.3 (Latest: v5.11.3)
AdminLTE version is v5.13 (Latest: v5.13)
FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
- OS and version:  Ubuntu 20.04.4 LTS
- Platform:  VPS

### Expected behavior
Would like to set static ip manually when using the installer or the `pihole -r` command.

### Actual behavior / bug

Selecting `Set static IP using custom values` results in an error.
```

Error: Unknown option --cancer-label.
Use --help to list options.

```
### Steps to reproduce

1. Run `pihole -r`
2. Select `Reconfigure`
3. Follow the menus until there's the option to set the static ip
4. Select `Set static IP using custom values`

### Screenshots

![image](https://user-images.githubusercontent.com/12100811/178117328-5f2361eb-7322-47d4-a783-4ea9b408af3c.png)

### Additional context

The installer script contains a typo in dialog argument list (`cancer`/`cancel`) that was introduced in this commit:

https://github.com/pi-hole/pi-hole/commit/39cb1029e9ae804cd1912fc1a84048814e5ab830

**Comment by yubiuser** [comment]
Released with https://github.com/pi-hole/pi-hole/releases/tag/v5.11.4
