### ISSUE TITLE
pihole-FTL not running

### ISSUE THREAD

**Issue by mickym2** [pi-hole/pi-hole#4809]
``### Versions

  Pi-hole version is v5.11.3 (Latest: v5.11.3)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Expected behavior

If I look to the pihole-FTL service it looks fine on frist step, but pihole-FTL is not running:

`systemctl status pihole-FTL
● pihole-FTL.service - LSB: pihole-FTL daemon
     Loaded: loaded (/etc/init.d/pihole-FTL; generated)
     Active: active (exited) since Sat 2022-07-09 20:45:45 CEST; 3min 54s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 10027 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
        CPU: 146ms

Jul 09 20:45:41 MWIPv6GW systemd[1]: Starting LSB: pihole-FTL daemon...
Jul 09 20:45:41 MWIPv6GW pihole-FTL[10027]: Not running
Jul 09 20:45:41 MWIPv6GW su[10046]: (to pihole) root on none
Jul 09 20:45:41 MWIPv6GW su[10046]: pam_unix(su:session): session opened for user pihole(uid=999) by (uid=0)
Jul 09 20:45:45 MWIPv6GW systemd[1]: Started LSB: pihole-FTL daemon.`

I update pihole and the system - everything runs fine. 

pihole status
  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

looks also fine. 

So in general I am not sure or do not know - whats wrong. I read a lot - but nothing seems to fit.

**Comment by yubiuser** [comment]
Do you experience any issues or is this only about the report from `systemctl`?
It looks pretty normal, the `exited` and `not running` are expected. My output looks the same.

```
   ● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Sat 2022-07-09 23:41:26 CEST; 4min 43s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0 (limit: 4463)
   Memory: 0B
   CGroup: /system.slice/pihole-FTL.service

Jul 09 23:41:26 rockpi-4b systemd[1]: Starting LSB: pihole-FTL daemon...
Jul 09 23:41:26 rockpi-4b pihole-FTL[519]: Not running
Jul 09 23:41:26 rockpi-4b su[539]: (to pihole) root on none
Jul 09 23:41:26 rockpi-4b su[539]: pam_unix(su:session): session opened for user pihole by (uid=0)
Jul 09 23:41:26 rockpi-4b pihole-FTL[519]: FTL started!
Jul 09 23:41:26 rockpi-4b su[539]: pam_unix(su:session): session closed for user pihole
Jul 09 23:41:26 rockpi-4b systemd[1]: Started LSB: pihole-FTL daemon.

```

**Comment by mickym2** [comment]
No there are no issues and everything looks normal. Dashboard is running fine. I am not sure, if in the past the service was not only active - it was running. However as  I wrote, I thought that someone can confirm - that the output of the service is OK and that pihole-FTL has not a status running. If you confirm that the output is normal - then I can close this immediately.

**Comment by rdwebdesign** [comment]
Yes, it's normal. This is the expected behavior.

**Comment by mickym2** [comment]
OK then thank you for confirmation.
