### ISSUE TITLE
Change the blocking redirection of lighttpd to another folder instead of var/www/html

### ISSUE THREAD

**Issue by edo44** [pi-hole/pi-hole#481]
I know, I should have just to edit the lighttpd's configuration file to another folder than var/www/html, but doing this prevents me to host a normal webpage.

So I was wondering what should I do to host a webpage (port 80 of course) and at the same time redirect pihole to a custom index.html .

**Comment by dschaper** [comment]
The way the Pi-hole operates, it basically requires port 80 for operation. You could use a 404 redirect to serve the intercepted elements or use a named server configuration with the Pi-hole as a catch all but those configurations all have glitches. You'd lose 404 support on the website and you'd have some administration issues. It's generally not supported to run Pi-hole along with another site on port 80 at the same time.
