### ISSUE TITLE
Unable to update to the latest release

### ISSUE THREAD

**Issue by xaozai** [pi-hole/pi-hole#4817]
## Versions

  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16 (Latest: v5.16.1)

## Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi

After `pihole -up`, a message is displayed:

[✗] Unsupported OS detected: Raspbian 9

Is Raspbian 9 no longer supported? :(

**Comment by yubiuser** [comment]
Yes, it's no longer supported.
> Debian 9 (Stretch): EOL 2020-07-06, EOL LTS 2022-06-30

https://github.com/pi-hole/docs/pull/728

It's likely still working using the workaround shown while trying to upgrade, but you should consider to upgrade your OS to one that is still actively maintained.
