### ISSUE TITLE
Problems with whitelist.txt

### ISSUE THREAD

**Issue by edo44** [pi-hole/pi-hole#482]
Using the custom lists, I have whitelisted imgur.com, i.imgur.com and p.imgur.com, but I still can't get the site to work without it being redirected to the rPi localhost. To begin with it is strange I can't get into imgur.com in the first place, and second, whenever I make a request to imgur.com I can't even see the request being accepted or rejected on the Recent Queries page of the pihole webpage, I am just redirected to the localhost webpage.

And I always run gravity.sh to update the lists after the whitelisting, of course.

**Comment by PromoFaux** [comment]
Hi there, what custom lists are you using? 

Can you please paste output of `pihole -d` to pastebin? Thanks.

Also, how are you whitelisting those sites?

**Comment by edo44** [comment]
I whitelist editing /etc/pinhole/whitelist.txt 

Waiting for the debug to finish... Is it normal it takes a lot of time in the "try sites that you are having trouble with now..." fase? I don't understand, do I have to do something here?

**Comment by PromoFaux** [comment]
Ah, You need to press `ctrl + c` to finish off the debug script (I believe it says so...)

Also, editing just that file is not enough. you need to run `pihole -w <domain you want to whitelist>`

**Comment by edo44** [comment]
Why is that? What that command does?

**Comment by PromoFaux** [comment]
Pressing `ctrl + c` on your keyboard will exit the debug script. 

`pihole -w` is the command you use to edit the whitelist as seen in the [instructions here](https://github.com/pi-hole/pi-hole/wiki/Whitelisting-and-Blacklisting)

**Comment by PromoFaux** [comment]
More information on the `pihole` command can be [found here](https://github.com/pi-hole/pi-hole/wiki/The-%22pihole%22-Command)

**Comment by edo44** [comment]
`pihole -w imgur.com`
`imgur.com already exists in /etc/pihole/whiteslist.txt, no need to add!`

http://pastebin.com/nf5YfZp7

**Comment by edo44** [comment]
I already had the same problem with the custom lists (that you can see in the log file at the end) with yahoo.com, because even if I whitelisted yahoo.com I still couldn't get into the website without being redirected to the pihole page.

**Comment by dschaper** [comment]
Your custom whitelist has characters that Pi-hole doesn't recognize. It should only contain domain names, no other modifiers. It looks like this was copied from Ad-blocker? Delete your whitelist and try accessing the domains without anything in the whitelist. Then if you are still having problems, run another debug script and post the dump of that.

**Comment by edo44** [comment]
I delete them, it didn't change anything

Without modifiers:
http://slexy.org/view/s2Om45hWrJ

Without any entry in whitelist.txt it doesn't change anything too, imgur.com only works if I remove the list with the imgur domains in it.

**Comment by dschaper** [comment]
Can you post that dump to pastebin? Slexy doesn't show the raw file so I can see the line breaks. There are some issues with lighttpd and dnsmasq also that I see from the dumps. Are you able to open the admin page for the Pi-hole?

**Comment by edo44** [comment]
I uploaded it in GitHub Gist, but anyway I found the problem! The problem was in every browser imgur.com was cached and apparently every time I did the request every freaking browser kept on making requests over the cached page. In the end I just had to clear the cache for every browser!

**Comment by dschaper** [comment]
Glad this solved the issue for you! Thanks for using the Pi-hole.
