### ISSUE TITLE
How to upstream DNS with DNSsec

### ISSUE THREAD

**Issue by Potterli20** [pi-hole/pi-hole#4822]
How to upstream DNS with DNSsec

**Comment by jfb-pihole** [comment]
Please rephrase your question.  You want to use DNSSEC, but you don't think it's working?

**Comment by jfb-pihole** [comment]
Please generate a debug log, upload the log when prompted and post the token URL here.

**Comment by jfb-pihole** [comment]
```
*** [ DIAGNOSING ]: Setup variables
    IPV4_ADDRESS=192.168.2.3/24
    DNSSEC=false
     PIHOLE_INTERFACE=enp1s0
    PIHOLE_DNS_1=192.168.2.3
    PIHOLE_DNS_2=192.168.2.4
```

You have Pi-hole using itself as one of the upstream DNS servers.  That is a loop.

You also have DNSSEC disabled.

**Comment by dschaper** [comment]
You have the Pi-hole server with an IP of 192.168.2.3. You then have told Pi-hole to use 192.168.2.3 as an upstream resolver. That's not going to work. 

What IP address and port is `dnsproxy` listening on for queries to forward? 

That DNS file is malformed, I'm not sure what it's supposed to contain but it's a lot of random.
