### ISSUE TITLE
PiHole Web GUI does not work completely with hestiacp

### ISSUE THREAD

**Issue by afzl-wtu** [pi-hole/pi-hole#4826]
I have installed Hestiacp with Apache2 and Nginx as reverse proxy. The problem with hestiacp is that it does not read a website folder from /var/www/html instead it we create a user in hestiacp and it then stores all websites created by that user in /home/usercreatedbyhestiapanel/web/<domain.name>/public_html/. So I copied /var/www/html/admin & pihole to hestiacp public_html dir. I also added opendatabase dir in php setting of hestiacp so that it can access files in /etc/pihole. I also added www-data and usercreatedbyhestiacppanel in pihole group. Now pihole admin works correctly  I can also whitelist and blacklist domains in pihole.
The only problem I face is I can not update any setting of DNS. If I change interface or add/remove an other upstream DNS and click save in web GUI it says settings updated successfully, and then page reload but nothing updates settings go to previous state.
I also changed setupVars.conf permission to 777 but in vain. There is no any error comes when updating settings but they do not update. By the way, Lighttpd works fine.

**Comment by yubiuser** [comment]
Neither Apache nor NGNIX are supported web servers. Only `lighttpd` is.
You can have a look at the user-generated docs: https://docs.pi-hole.net/guides/webserver/nginx/
Or visit our community help forum https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36
