### ISSUE TITLE
default configuration of lighttpd crashes the lighttpd service.

### ISSUE THREAD

**Issue by bitterypaul** [pi-hole/pi-hole#483]
# this is the code i am using. this was copied from [http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/](http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/)

`
server.modules = (
	"mod_expire",
	"mod_compress",
 	"mod_redirect",
	"mod_rewrite"
)
 
server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
 
 
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
 
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
 
#default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
 
#Set access to 1 day for better query performance when the list gets so large
#http://jacobsalmela.com/raspberry-pi-block-ads-adtrap/#comment-2013820434
$HTTP["url"] =~ "^/pihole/" {
        expire.url = ("" =&gt; "access plus 1 days")
}
 
#Rewrites all URLs to the /var/www/pihole/index.html
$HTTP["host"] =~ ".*" {
     url.rewrite = (".*" =&gt; "pihole/index.html")
}
`

# Problem:

when i use this configration for lighttpdconf file, the service lighttpd does not start at all. however when i remove the last two sections, it works.
I previously executed the automated installation script but could not configure it because i use the raspberry pi as the wi-fi hotspot using dnsmasq and hostapd and i dont know how to configure them.

**Comment by PromoFaux** [comment]
From the linked blogpost:

> **Update 2016-04-24 : Please note this guide is now out-dated**

You may have better luck with the latest `lighttpd.conf` which can be found [here](https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf)

**Comment by bitterypaul** [comment]
I don't have a working sd card for now to check the config whether it is working or not. Sorry.
I will close this issue for now.
