### ISSUE TITLE
Change of run dir to /run/pihole/FTL.pid causes pihole status cmd to fail 100% of the time

### ISSUE THREAD

**Issue by charlieporth1** [pi-hole/pi-hole#4830]
### Versions

- Pi-hole:  all
- AdminLTE:  all 
- FTL:  all
- Im running the latest version

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  GCP VM

### Expected behavior
`pihole status`  cmd to print  `[✓] FTL is listening on port`

_A clear and concise description of what you expected to happen._
`pihole status` cmd prints `[✗] DNS service is NOT running`
When `PIDFILE` var in `/etc/pihole/pihole-FTL.conf` changes in anyway other than the default.
This is due to the fact that the `PIDFILE` is not read in `/usr/local/bin/pihole` and is statically set at `readonly FTL_PID_FILE="/run/pihole-FTL.pid"`

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce
change to 
`PIDFILE=/var/run/pihole/FTLpid`

**Comment by yubiuser** [comment]
Thanks. This is a bug, but easy to fix. Basically, we can reuse the `getFTLPIDFile()` from the service file. Instead of simply copying it, I would move it to `utils.sh` to make it accessible to other scripts.

**Comment by yubiuser** [comment]
Please try if 

`pihole checkout core move_getFTLPIDFile`

solves the issue for you. You can go back on track and before the next Pi-hole update with `pihole checkout master`

**Comment by charlieporth1** [comment]
I can check this out tmr

**Comment by yubiuser** [comment]
The branch has been deleted already after it has been merged to `development`.

If you want to try, you need to run `pihole checkout core development`

**Comment by charlieporth1** [comment]
This fix works

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-17-web-v5-14-and-core-v5-12-released/57497
