### ISSUE TITLE
basic install msg box text improvements

### ISSUE THREAD

**Issue by seb-1204** [pi-hole/pi-hole#4831]
### Versions

https://github.com/pi-hole/pi-hole/commit/13135498c1ce69ccc6d7388e1eca33495afe76cc

- Pi-hole:  basic installer

### Platform

- OS and version:  Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

- Platform:  Raspberry Pi nano W

### Expected behavior

Text should be formatted well with correct use of space, full stop and new lines.

- space between 'conflictBut'
- new line between 'want.It'

### Actual behavior / bug

Basic installer message box looked like attached image.

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to run basic installer in command line
2. follow prompts until the message box "FYI: IP Conflict"

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

![pi-hole  2022-07-24 18-10-11](https://user-images.githubusercontent.com/307449/180640834-fc666d62-e4ef-4d7d-8a7d-a77fb901c4b6.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-17-web-v5-14-and-core-v5-12-released/57497
