### ISSUE TITLE
Wildcard address=/domain.com/1.2.3.4 has stopped working in latest versions of pihole

### ISSUE THREAD

**Issue by dav1d-c** [pi-hole/pi-hole#4836]
### Versions
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
- OS and version:  Debian GNU/Linux 11 (bullseye)
- Platform:  QNAP Container Station

### Expected behavior

cd /etc/dnsmasq.d
echo "address=/domain.com/1.2.3.4" >> 99-wildcards.conf
[restart FTL]
$ host anything.domain.com
(returns 1.2.3.4)

+ https://hetzbiz.cloud/2022/03/04/wildcard-dns-in-pihole/

### Actual behavior / bug

FTL unable to start pi-hole/DNSmasq:

**FATAL ERROR in dnsmasq core: bad option at line 1 of /etc/dnsmasq.d/99-wildcards.conf**
[process unable to start, stuck in a reboot loop]

### Steps to reproduce

Steps to reproduce the behaviour:

This used to work just fine on version 2022.02.1
Problem occurs on version 2022.07.1

## Debug Token

- URL:  [✓] Your debug token is: https://tricorder.pi-hole.net/ja6CfsLH/

**Comment by jfb-pihole** [comment]
What are your tring to accomplish with this first line?  This is what's throwing the error.

```
-rw-r--r-- 1 root root 84 Jul 25 15:13 /etc/dnsmasq.d/99-pcf-wildcards.conf
   -ne address=/sys.pcf.home.pvt/172.20.0.100
   address=/apps.pcf.home.pvt/172.20.0.100
```

**Comment by dav1d-c** [comment]
I really should have caught this - thank you very much for finding my PEBKAC!

I init the file with the command:

```
echo -ne "address=/sys.pcf.home.pvt/172.20.0.100\naddress=/apps.pcf.home.pvt/172.20.0.100\n"
```

looks like the "-ne" args to echo are ending up in the output and then into the file from there (for whatever reason)

Good to close!
