### ISSUE TITLE
Admin Interface hostname should parse all whitespace, not just tabs in /etc/hosts

### ISSUE THREAD

**Issue by kmr2319** [pi-hole/pi-hole#484]
##### Expected Behaviour:
[Reference](https://github.com/pi-hole/pi-hole/issues/379#issuecomment-215484302)
Admin interface top clients should show hostnames for any host defined in the /etc/hosts file.

##### Actual Behaviour:
Only displays hostnames when the IP and hostname are separated by tabs.

##### Steps to reproduce this issue:
Create /etc/hosts entry with [ip][one or more spaces][hostname], doesn't show up with the hostname in the top clients admin interface. [ip][tab][hostname] entries are display properly.

The the [/etc/hosts man page](http://man7.org/linux/man-pages/man5/hosts.5.html), spaces are acceptable syntax:

>Fields of the entry are separated by any number of blanks and/or tab characters.

**Comment by PromoFaux** [comment]
My bad, but easily fixed... I thought the standard was tabs, for some reason... it will be in the next release :)

**Comment by kmr2319** [comment]
Thanks for the quick turn around!

I generally use tabs, but that one seemed to have some spaces sneak in there for some reason...

**Comment by C4Wiz** [comment]
can we break this out into the setupVars.conf file? maybe have the ability to add the names from the admin page

**Comment by DL6ER** [comment]
You mean edit `/etc/hosts` from the web UI?
