### ISSUE TITLE
Pihole or FTL(?) does not resolv any hostnames

### ISSUE THREAD

**Issue by dYna77** [pi-hole/pi-hole#4844]
### Versions
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
- Platform:  Raspberry Pi,

### Expected behavior

Using pihole as a DNS server would resolve hostnames.

### Actual behavior / bug

It does not do ist.

## Debug Token

- URL:  https://tricorder.pi-hole.net/N1yiarGK/

### Additional context

I just did a fresh install of pihole since i tried everything to my best in order so sort this problem out.
But that did not work either.
The problem occured two or three updates ago. Before that, everything worked fine.

**Comment by dYna77** [comment]
It seems like the DNS server is running on localhost and not 192.168.2.25, because when i change the DNS server (in resolv.conf) on the pi, running pihole, to localhost it itself can resolve hostnames, but not with 192.168.2.25.
But i dont see any way what i can do about it.

**Comment by dschaper** [comment]
You have Pi-vpn installed and that software has written a configuration file that locks the DNS server to the `tun0` interface.

```plain
-rw-r--r-- 1 root root 16 Mar 31  2020 /etc/dnsmasq.d/02-pivpn.conf
   interface=tun0
```

This issue was fixed a few years ago with https://github.com/pivpn/pivpn/issues/946. Have you installed Pi-vpn since then?
