### ISSUE TITLE
Web interface approach via servername or fqdn

### ISSUE THREAD

**Issue by nsine-zz** [pi-hole/pi-hole#4845]
### Versions

- Pi-hole:    Pi-hole version is v5.11.4
- AdminLTE:  AdminLTE version is v5.13 
- FTL:  FTL version is v5.16.1
- Lighttpd: 1.4.59

### Platform
- OS and version:  Debian Bullseye 11.4
- Platform:  LXC Container

### Expected behavior

This issue may be combined with lighttpd.
I am no expert in any of these softwares and this is my first bugreport, please be kind.

My pihole servername is: womdns02
My internal domain name is: home.nsine.be
DNS is configured so that both servername and fqdn resolve to the correct IP address.
I run self signed ssl certificates that are valid for servername, fqdn and IP address.
Expected is that the pihole web interface is accessable via the servername, fqdn and its ip address.

### Actual behavior / bug

When browsing to the servername, the lighttpd server crashes and restarts.
When browsing to the fqdn, everything is fine.
I've updated lighttpd to version 1.4.65-2 (bookworm) and this resolves the issue.
However, now pihole complains:
`Failed Host Check: womdns01 vs 10.1.2.2, womdns01.home.nsine.be, pi.hole, localhost
`

I've fixed this by editing "/var/www/html/admin/scripts/pi-hole/php/auth.php" :
```
    // Check CORS
    $AUTHORIZED_HOSTNAMES = array(
        $ip,
        str_replace(array("[","]"), array("",""), $_SERVER["SERVER_NAME"]),
        "pi.hole",
        "localhost",
        gethostname()
    );

```
Accessing via the IP address fails with invalid request, this might be an configuration issue in lighttpd

### Config files
```
### /etc/lighttpd/external.conf
server.name = "womdns02.home.nsine.be"
$HTTP["host"] =~ ".*" {
  # Ensure the Pi-hole Block Page knows that this is not a blocked domain
#  setenv.add-environment = ("fqdn" => "true")

  # Enable the SSL engine with a LE cert, only for this specific host
  $SERVER["socket"] == ":443" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/ssl/private/https_womdns02.home.nsine.be.pem"
    ssl.ca-file =  "/etc/ssl/private/https_womdns02.home.nsine.be.cacert"
    ssl.honor-cipher-order = "enable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
  }

  # Redirect HTTP to HTTPS
  $HTTP["scheme"] == "http" {
    $HTTP["host"] =~ ".*" {
      url.redirect = (".*" => "https://%0$0")
    }
  }
}
```

## Debug Token

- URL:   https://tricorder.pi-hole.net/PT5WNHFy/

**Comment by dschaper** [comment]
> I've fixed this by editing "/var/www/html/admin/scripts/pi-hole/php/auth.php"

Changing that file will cause issues when you need to update Pi-hole. 

> `Failed Host Check: womdns01 vs 10.1.2.2, womdns01.home.nsine.be, pi.hole, localhost `

That is showing the names that are allowed to access Pi-hole, you are trying to use `womdns01` but there is no corresponding `server.name` that matches. You have `server.name = "womdns02.home.nsine.be"` in the external configuration and that is different than `womdns01`. 

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.
