### ISSUE TITLE
Pihole doesn't have internet access when router's dns settings are pointed to the pihole ip address

### ISSUE THREAD

**Issue by RobCod** [pi-hole/pi-hole#4868]
### Versions

  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform

- OS and version:  Ubuntu 22.04.1 LTS

- Platform:  Docker

### Expected behavior

The pihole fetches the domain names from cloudflare 1.1.1.1 & 1.0.0.1

### Actual behavior / bug

web page fails to load and results in a page not found

### Steps to reproduce

1. point the routers dns to the pihole ipaddress
2. set pihole dns to cloudflare and google
3. search google.com
4. page not found

## Debug Token

- URL:  I can't get a debug token as it fails to upload when the dns server is set to the pihole. The following link is after i change the router dns back to 1.1.1.1 or 8.8.8.8 skipping pihole completely https://tricorder.pi-hole.net/1EDk5CPO/

### Screenshots
![image](https://user-images.githubusercontent.com/48031674/184567378-426bb1e7-28d6-441b-b7f4-b552230b3aac.png)
![image](https://user-images.githubusercontent.com/48031674/184567342-fb4ea0b4-dbf9-46ae-a053-0fe303712587.png)
![image](https://user-images.githubusercontent.com/48031674/184567356-9ab0bd49-6810-4e38-952c-44a712ac9c6d.png)
nslookup of 1.1.1.1
![image](https://user-images.githubusercontent.com/48031674/184567399-882c31fa-200f-48e2-89d7-4ce1e564d484.png)

### Additional context

I have the dns server in my D-LINK DIR-880L pointed to the pihole container running on my ubuntu vm on my truenas machine(I setup a vm with just pihole installed on it and i get the same result with a ubuntu VM with just pihole on it, so its not docker). I am not using the dhcp settings with pihole, and I can't as my router doesn't give me the option to disable the dhcp server on the router. I have a local dns server for various web based applications in my LAN and it works as expected. The pihole can not ping 1.1.1.1 or google.com or 8.8.8.8. Its like it has no internet connection only when the dns server is being pointed at pihole in my router settings, once i switch them back to 1.1.1.1 or 8.8.8.8 I can ping google.com, 1.1.1.1 or 8.8.8.8.

Forgot to mention that i can ping and ssh into the pihole server and dig sites if I @8.8.8.8
ufw isn't even installed on the docker host or the docker container, so it isn't a firewall issue blocking port 53

![image](https://user-images.githubusercontent.com/48031674/184568304-03fb88f9-a6ed-4da0-8d6d-2fc3464a6e66.png)

pihole dig, using itself as the dns without the settings in the router
![image](https://user-images.githubusercontent.com/48031674/184569467-85746eb9-50a0-4b51-a76f-f945b839c1d8.png)

pihole dig, using itself as the dns with the settings in the router(apparently I can dig with my dns pihole, but not ping google?)
![image](https://user-images.githubusercontent.com/48031674/184569605-b7759d57-07dd-44b8-903e-0a3a218cb5c8.png)

**Comment by jfb-pihole** [comment]
Your debug log shows that Pi-hole (via the Pi) has internet access:
```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] pecgsm.termquotientbeen.top is 0.0.0.0 on lo (127.0.0.1)
[✓] pecgsm.termquotientbeen.top is 0.0.0.0 on eth0 (172.17.0.3)
[✓] doubleclick.com is 142.251.215.238 via a remote, public DNS server (8.8.8.8)
```
and has processed the following activity in the past 24 hours (or when you installed Pi-hole, whicheve is sooner):
```
   [2022-08-15 01:54:27.065 1147M] Imported 9546 queries from the long-term database
   [2022-08-15 01:54:27.065 1147M]  -> Total DNS queries: 9546
   [2022-08-15 01:54:27.065 1147M]  -> Cached DNS queries: 513
   [2022-08-15 01:54:27.065 1147M]  -> Forwarded DNS queries: 8794
   [2022-08-15 01:54:27.065 1147M]  -> Blocked DNS queries: 99
   [2022-08-15 01:54:27.065 1147M]  -> Unknown DNS queries: 0
   [2022-08-15 01:54:27.065 1147M]  -> Unique domains: 258
   [2022-08-15 01:54:27.065 1147M]  -> Unique clients: 13
   [2022-08-15 01:54:27.065 1147M]  -> Known forward destinations: 3
```
You are running Pi-hole in Docker, it appears.  The problem could be that the Docker container has stopped passing DNS to Pi-hole, or the router is not distributing Pi-hole as DNS server.

What is the active DHCP server on your network?

```
*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 0
```

**Comment by RobCod** [comment]
> Your debug log shows that Pi-hole (via the Pi) has internet access:
I was only able to get the log to upload by uploading the log after i had switched the dns record in the router back to 8.8.8.8, otherwise it was failing to upload everytime i tried. I just deleted the d-link garbage and replaced it with dd-wrt so once i get this router working again, im willing to bet i'm gonna have no issues like i did before. Only reason i switched my network is because i got tired of my ISP's modem disabling NAT hairpin, i'll update again once i try this out.

**Comment by RobCod** [comment]
okay so my router with dd-wrt is not an option as internet speeds to a crawl. 

> What is the active DHCP server on your network?

The DHCP server on my network is my router and unfortunately the options it gives me for that are here
![image](https://user-images.githubusercontent.com/48031674/184588569-18d95cb6-790f-47e4-b3e0-935566365e5e.png)

**Comment by RobCod** [comment]
i am currently attempting to disable the dhcp on the router and give it to the pi, but it seems like when i disable the dhcp server all my devices rejoin except for the ubuntu vm that is running pihole for what ever reason causing me to restart my entire router every time i try this.

**Comment by irwige** [comment]
You're filling out the wrong DNS field.

The Internet DNS field should be pointed to wherever you want (your ISP/CloudFlare/Google).

The DNS field you are looking for is the LAN DNS. It's usually near the LAN DHCP settings. My guess on this modem is that it's under "Advanced Settings" in your screen cap for 'Network Settings'.
