### ISSUE TITLE
Despite adding all the firebug green domain lists, I still get ads on my phone and computers.

### ISSUE THREAD

**Issue by daisukedaisn** [pi-hole/pi-hole#4871]
### Versions

~ $ pihole -v
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
- OS and version:  
- Raspberry Pi OS with desktop and recommended software
    Release date: April 4th 2022
    System: 32-bit
    Kernel version: 5.15
    Debian version: 11 (bullseye)
    Size: 2,277MB

- Platform:  Raspberry Pi 4

### Expected behavior

I expect the majority of Ads to be removed my pi hole. Many still leak through. I am not really sure I understand the benefit of Pihole which was time consuming to install since I still need to install individual adblockers on each device and in each browser. Perhaps I have not done something right during the install... 

In any case, I hope you can provide some advice. I am happy to run any commands or provide additional data. 

Thank you.

### Actual behavior / bug

This is apparent on my phone when I use the google chrome browser which does not have an ad blocker add-on. I mainly use Firefox on my phone, which does had an ad blocker and Ublock Origin. Both report hits on almost every page. The same is true for both Chrome and Firefox on my Linux Mint computer. I have ad blockers on the browser and they both get hits on almost every page. The Dashboard shows no errors. (See attached screenshot.)

### Steps to reproduce

1. Add all the GREEN domain lists from the "Big Blocklist Collection" https://firebog.net/
2. nstall both Ublock Origin Adblock Plus in Firefox or Chrome.
3. Use the browser and observe the ads. 

1. Use Chrome without ad blockers installed on an Android phone and observe all the ads.

## Debug Token

- URL:  

### Screenshots
1-Dashboard
2-Adblock Plus status in Firefox
3-Ublock origin status in Firefox

### Additional context
None
![Screenshot-UblockOriginStatus](https://user-images.githubusercontent.com/104041470/185272849-87bcc481-cef0-45c4-afbb-f53237e8e747.png)
![Screenshot-AdblockPlusStatus](https://user-images.githubusercontent.com/104041470/185272871-5903ef5c-0281-45b7-ab5a-b5ab7cef9a77.png)
![Screenshot-Pihole-Dashboard](https://user-images.githubusercontent.com/104041470/185272885-dc067966-0a8b-403d-8234-a87db553f81e.png)

**Comment by daisukedaisn** [comment]
Part of my report was swallowed somehow. I could not upload the debug log. This was the output of the attempt:
~ $ `pihole -d`. https://docs.pi-hole.net/core/pihole-command/#debugger
[?] Would you like to upload the log? [y/N] y
-bash: $'\E[H\E[2J\E[3JThis': command not found

If you understand this error and can advise on how to correct it, I will run it again. Perhaps this is a symptom of the problem?

**Comment by PromoFaux** [comment]
No ads for me on that page (using default list + @lightswitch05's [ads and tracking](https://www.github.developerdan.com/hosts/) list.

>I have ad blockers on the browser and they both get hits on almost every page.

This is normal. There will always be some crossover, and using both ,(I also have uBlock and Privacy Badger on my main PC) is a good strategy. Where Pi-hole really shines is in the places where you _can't_ install an extension - such as mobile/TV/lightbulbs etc.

Your pi-hole is clearly working - 50% of requests are blocked. Please run just `pihole -d` on it's own . It looks like you may have pasted the URL onto your command line, too.

**Comment by daisukedaisn** [comment]
Thanks for the great ideas PromoFaux! I will add several of your lists, especially the Google AMP pages and your ads and tracking list. I guess any duplicates sites are taken care of by the caching feature. Also, I apologize for the idiotic way I ran `pihole -d`. I have repeated the attempt and my debug token is:
https://tricorder.pi-hole.net/PjfA0VXr/
So the log should be uploaded now.
I will post back again once I have tried out the new blocking lists.

**Comment by daisukedaisn** [comment]
Just following up on the addition PromoFaux's recommented lists: Ads and Tracking list, Facebook list, and Google AMP lists.  This definitely had an effect. In Firefox, the Adblock hits went from 35 to 17 and the Ublock hits went from 42 to 17. (It is a little bit tricky to get an accurate count since I think the site keeps on pumping out ads as both Adblock Plus and Ublock counts go up over time,) 

Just FYI, I already had the Ads and Tracking list from firebug.net which pihole noted as a duplicate list. This raises an interesting question. If a list has the same name/URL as a previously added list but the file has been updated, will pihole pickup the updates? That is, does pihole periodically scan lists for changes?

I will leave this post open until I get some feedback on my debug log from you or from anyone else who has the time to check it out.

Once again, thanks so much for the guidance.

**Comment by jfb-pihole** [comment]
"following up on the addition PromoFaux's recommented lists: Ads and Tracking list, Facebook list, and Google AMP lists. This definitely had an effect. In Firefox, the Adblock hits went from 35 to 17 and the Ublock hits went from 42 to 17."

Note that the number of domains on blocklist in Pi-hole has no bearing on what any browser based blocker sees or does.

A browser based blocker acts first.  The browser requests a domain or element.  If the browser blocker blocks that domain or element, the request never makes it out of the browser.  Pi-hole only sees the domains that the browser blocker has not blocked, at which time Pi-hole has the opportunity to block the domain.  Adding domains to Pi-hole blocklist is unknown to the browser blocker.

**Comment by daisukedaisn** [comment]
Hello jfb-pihole,

> Note that the number of domains on blocklist in Pi-hole has no bearing on what any browser based blocker sees or does.

Thank you for the info. I do understand what you mean - that is why the number of hits on Adblock and Origin in the browser went down after I added 58K additional domains to pihole: The previous hits were filtered out before they reached the browser.

I know that I still have much to learn about pihole. On my list are figuring out why the `pi.hole` domain only works intermittently and also if it is a good idea to add [Unbound](https://docs.pi-hole.net/guides/dns/unbound/), the recursive, open source DNS server which finds the authoritative IP for the domain requested. Perhaps this latter will solve the former!

**Comment by daisukedaisn** [comment]
Hello jfb-pihole,

> Note that the number of domains on blocklist in Pi-hole has no bearing on what any browser based blocker sees or does.

Thank you for the info. I do understand what you mean - that is why the number of hits on Adblock and Origin in the browser went down after I added 58K additional domains to pihole: The previous hits were filtered out before they reached the browser.

I know that I still have much to learn about pihole. On my list are figuring out why the `pi.hole` domain only works intermittently and also if it is a good idea to add [Unbound](https://docs.pi-hole.net/guides/dns/unbound/), the recursive, open source DNS server which finds the authoritative IP for the domain requested. Perhaps this latter will solve the former!
