### ISSUE TITLE
docker image update issue : Not pulling the latest

### ISSUE THREAD

**Issue by dandare100** [pi-hole/pi-hole#4874]
### Versions

Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.3)

### Platform

- OS and version:  Linux raspberrypi 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux

- Platform:  Paspberry PI

### Expected behavior

Docker image pihole/pihole:latest should not say that there is an update available and should be tagged with the latest image

### Actual behavior / bug
When running pihole/pihole:latest it pulls the tag 2022.07.01 and says there is an update available

_A clear and concise description of what the bug is._

### Steps to reproduce

Run the below command
pi@raspberrypi:~/pihole $ docker run --rm -p80:80 -it pihole/pihole:latest
Unable to find image 'pihole/pihole:latest' locally
latest: Pulling from pihole/pihole
dc1f00a5d701: Pull complete 
280ee136bb30: Pull complete 
4f4fb700ef54: Pull complete 
5cf51dc31d77: Pull complete 
984b787b496f: Pull complete 
c48dab7e362c: Pull complete 
8c6657203dd0: Pull complete 
5dc7355bea16: Pull complete 
3734d50778a6: Pull complete 
Digest: sha256:f7624f452b7a6320405b6ff00a9ed253d99fd33a22abced1954633ceb5bae24e
Status: Downloaded newer image for pihole/pihole:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
Existing DNS servers detected in setupVars.conf. Leaving them alone
Assigning random password: 01oyyE_k
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "",
			"PIHOLE_DOCKER_TAG" => "2022.07.1",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
			"ServerIP" => "0.0.0.0",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Restarting DNS server
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.1)
  Container tag is: 2022.07.1
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as pihole
Starting crond
[services.d] done.

The following is displayed in the browser

![Screenshot from 2022-08-21 18-21-38](https://user-images.githubusercontent.com/5639208/185801121-77458a18-8fba-4f92-b896-aeeaeefad399.png)

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context
The tag can be seen in the logs above it is 2022.07.01 and shouldn't it be latest ?

**Comment by rdwebdesign** [comment]
`2022.07.01` is the latest image.

**Comment by dandare100** [comment]
Ok cool thanks.

Why does it ask me to update in the admin console then ?

**Comment by rdwebdesign** [comment]
We released a new FTL hotfixes recently, but they are not in the `latest` image yet.
They will be in the next image.

**Comment by dandare100** [comment]
I understand.

Thank you for your quick response and an awesome piece of software.

**Comment by PromoFaux** [comment]
> They will be in the next image.

Ah yes... I forgot to do this :)
