### ISSUE TITLE
"server misbehaving" followed by "i/o timeout"

### ISSUE THREAD

**Issue by andy108369** [pi-hole/pi-hole#4876]
### Versions
```
pi@raspberrypi:~ $ pihole -v
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.3 (Latest: v5.16.3)
```

### Platform

Server: Raspbian GNU/Linux 10 (buster)
Client: Ubuntu 22.04 LTS

### Expected behavior

I am expecting the FTL resolver to work.

### Actual behavior / bug

golang app tries to resolve about 300 hosts and am always seeing the following:

```
dial tcp: lookup <redacted> on 192.168.50.1:53: server misbehaving
on 192.168.50.1:53: read udp 172.17.0.2:44397->192.168.50.1:53: i/o timeout
on 192.168.50.1:53: read udp 172.17.0.2:43135->192.168.50.1:53: i/o timeout
on 192.168.50.1:53: read udp 172.17.0.2:35473->192.168.50.1:53: i/o timeout
```

The behavior is same when changing to the pihole IP directly.

### Additional info

I've tried setting the rate limiter to `0/0`, the `Disable` button, changing DNS servers, no help.

Am not observing the same issue whenever am changing the DNS server to anything but pi.hole.

**Comment by dschaper** [comment]
Please provide the debug token URL as requested in the template. Thanks.
