### ISSUE TITLE
Install Process - No Packages

### ISSUE THREAD

**Issue by cmpunches** [pi-hole/pi-hole#4877]
### Versions
All

### Platform
All

### Expected behavior

`yum install pi-hole` or `apt-get install pi-hole` works according to best practices.  This could even be in the form public repos at the end of a ci/cd pipeline triggered by merges to this repo to avoid overhead.

### Actual behavior / bug

The issue is that the install process has 3 paths currently:
- pipe curl output to a root shell
- download some docker image
- clone the repo and install from source

None of which involve a best practice (unnecessary containerization to avoid packaging software is far from that and makes many assumptions!).  

These options also don't take into account a product lifecycle (updates, uninstallation).

This should be considered a bug and not a feature request.

**Comment by dschaper** [comment]
Thanks, this is a Feature Request.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by cmpunches** [comment]
No, it isn't.  

We can pretend it's not a bug, but integrating software with the operating system through its package manager so that it can be installed, updated, and removed cleanly is such a foundational part of a software project that it can't be called a feature, either.  It's just something we're all supposed to know to do with 30 years of precedent.

I will leave it to anyone who reads this to go through some arduous signup process on discourse instead of right here on the repo, where it should be, to get permission to tell you what you should already know, takes like 20 minutes to set up,  and is weighing down on the credibility of the project.

Until then I guess the users of this are piping curl to bash or adding container orchestration dependencies to their runtime unnecessarily, or installing a product that they will have to update uniquely (if they can at all with source) as a one-off instead of with the rest of the system.

</rant>

**Comment by dschaper** [comment]
Thanks for the comments.

It's been discussed as nausem for the last 5 years. If you want to have stale packages that won't get anything other than security patches then deb's are the way to go. Of course, this is a FOSS project so you probably could have forked the code and had your packages done in that 20 minutes. I counter that it's not that easy. 

You have your opinion, we have ours. Discourse is the place for discussions.
