### ISSUE TITLE
Ideas for security in pihole admin interface

### ISSUE THREAD

**Issue by bitterypaul** [pi-hole/pi-hole#488]
using a unique secret key for logging in to the pi-hole interface or using an online or an offline captcha service
The secret key can be defined by the user at the time of installation and the secret key can be stored as a php variable
or a secure method like a random mouse input for 7 seconds to ensure the user's presence
or touch input like utorrent's remote feature does.
or a javscript code to allow login only when a predefined mouse gesture and clicks are given

**Comment by Zegnat** [comment]
What is this trying to protect against?

You can read my comments in #444 for some ideas to harden security against the main thread: external websites calling to the `pi.hole` domain to execute things.

1. [Use CSRF tokens](https://github.com/pi-hole/pi-hole/pull/444#issuecomment-213407461), [explanation of CSRF tokens](https://github.com/pi-hole/pi-hole/pull/444#issuecomment-213422841).
2. [Use proper CORS settings](https://github.com/pi-hole/pi-hole/pull/444#issuecomment-214214230).

**Comment by Mcat12** [comment]
Those methods might protect against some things, but are very roundabout ways to do security in our situation.
