### ISSUE TITLE
ubuntu 22.04 - update dependency php8.1-json => php-json

### ISSUE THREAD

**Issue by itoffshore** [pi-hole/pi-hole#4880]
### Versions

-  Pi-hole version is `v5.2.4` (Latest: v5.11.4)
-  AdminLTE version is `v5.4` (Latest: v5.13)
-  FTL version is `v5.16.3` (Latest: v5.16.3)

### Platform

- OS and version:  Ubuntu `22.04`

- Platform:  `lxd` container

### Expected behavior

`pihole -r` should succeed

### Actual behavior / bug

`E: Package 'php8.1-json' has no installation candidate`

### Steps to fix

In Ubuntu `22.04` the dependency is now `php-json`:
```
  [i] Checking for php8.1-json (will be installed)
  [✓] Checking for php8.1-intl
  [i] Processing apt-get install(s) for: php8.1-json, please wait...
----------------------------------------------------------------------------------------------
E: Package 'php8.1-json' has no installation candidate
root@pihole:~# apt search php-json

php-json/jammy 2:8.1+92ubuntu1 all
```
I couldn't find where you store the dependencies otherwise I would have made a PR `;o)`

**Comment by dschaper** [comment]
Can you please provide a debug token URL? Dependencies are not pinned to specific versions, they determine what is installed on the system and attempt to use the same version.

**Comment by yubiuser** [comment]
We already account for this situation. 

https://github.com/pi-hole/pi-hole/blob/aefbe1f5b6225b7476fe08264c62da84aaa61fa0/automated%20install/basic-install.sh#L337-L339

https://github.com/pi-hole/pi-hole/pull/4135 added this check in Pi-hole v5.4. 
The issue is: your local version is really old.

Try to download the current installer (https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh) and save it to `/etc/.pihole/`.

Then run `pihole -up` again.

**Comment by itoffshore** [comment]
many thanks for the quick response - yes that fixed it:
```
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
root@pihole:~# pihole -v
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.3 (Latest: v5.16.3)
```
maybe a note should be added to the README for broken upgrades?

**Comment by yubiuser** [comment]
I don't think so. So far, the number of broken installations due to this specific issue is small (=1). We can handle this amount individually.
