### ISSUE TITLE
On either NextCloudPi or Raspberry Pi OS 64 Lite (OK on Ubuntu Server 22.04.1 LTS x86_64), can't log in via web

### ISSUE THREAD

**Issue by juanejot** [pi-hole/pi-hole#4881]
### Versions

- Pi-hole:  5.11.4
- AdminLTE:  (as "Web Interface") 5.13
- FTL:  5.16.3

### Platform

- OS and version:  Raspberry Pi OS 64 Lite, bullseye (kernel 5.15.56-v8+) & same on NextCloudPi image (works as expected on Ubuntu Server 22.04.1 LTS for x86_64)

- Platform:  Raspberry Pi 4 Model B

### Expected behavior

To be able to log in to the web interface with entries like "Query Log," "Long-term data," "Whitelist," "Blacklist," etc. along the left edge, "Client activity over  last 24 hours" colored in under "Total queries over last 24 hours," which remains green/grey. In a word, for the web interface to work.

### Actual behavior / bug

On Raspberry Pi as above (as of 8/28 new installation, proceeded by the same steps for unbound I've taken for pihole in the past, including on this platform), logging in via the web just dumps me to the same un-logged-in page with "Dashboard," "Login," "Donate," and "Documentation" along the left edge, and only "Total Queries over last 24 hours" along middle of top of page. If ctrl-return to log in to Settings page, it takes you there, but no changes apply (I assume, because you're not actually logged in), whether restoring configs via Teleporter, etc.

### Steps to reproduce

1. Install unbound, with a pi-hole.conf file in /etc/unbound/unbound.conf.d that has worked on other systems, just with a new port.
2. Install pihole via `curl -sSL https://install.pi-hole.net | bash`
3. Set the custom DNS server as 127.0.0.1#[new port] as part of that install
4. Set new password with `pihole -a -p [new password]`
5. Attempt to log in.

## Debug Token

- URL:  https://tricorder.pi-hole.net/zsUKTkEQ/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Still works, with those same Pi-hole, FTL & Web Interface versions, on Ubuntu Server 22.04.1 LTS, on x86-64 (also running Nextcloud in a snap & wireguard (installed by apt)). ~The only other version number differences I'm aware of (besides the big difference in platform, of course) is that PHP is 8.1.2 on Ubuntu 22.04, whereas PHP is 7.4.30 in Raspberry Pi OS/NextcloudPi (which is essentially the same OS, just comes with NextCloud installed & somewhat configured).~(Obviated by update, below)
I had thought there was something (a lot of other PHP packages?) interfering in NextCloudPi, so I backed up to install Pi-hole into Raspberry Pi OS (with only `sudo apt update && sudo apt full-upgrade`, automated scripts/drivers for the DeskPi Pro fan & ble.sh pulled from GitHub & installed beforehand), and it surprisingly gave me this same login problem for Pi-hole on the web, that I had never seen before.

**Comment by juanejot** [comment]
UPDATE: Also presents the same problem on the Raspberry Pi 4B running Ubuntu Server 22.04.1 LTS (and unbound, ble.sh and the DeskPi fan scripts/drivers, the latter as installed onto 20.04--because they'll install but not work if originally installed on 22.04--& then upgraded).

Debug token for that installation: https://tricorder.pi-hole.net/jFij7pb8/

Still working on x86-64, running the same OS.

**Comment by rdwebdesign** [comment]
> If ctrl-return to log in to Settings page, it takes you there...

If you can see the Settings page, your login succeeded.

Are you using always the same browser to connect?
Can you try to login using a different browser or even a different computer/device? Does the problem still happens?

**Comment by yubiuser** [comment]
What exact URL are you using to access the web interface?

**Comment by juanejot** [comment]
> Are you using always the same browser to connect?
Can you try to login using a different browser or even a different computer/device? Does the problem still happens?
Trying it on a different browser/device worked, as did clearing the cache on the same browser. Closing, thanks!
