### ISSUE TITLE
The Settings → System page shows placeholder values for system-related values

### ISSUE THREAD

**Issue by wsw70** [pi-hole/pi-hole#4883]
### Versions

```
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.1 (Latest: v5.16.3)
```

### Platform

- OS and version:  Raspberry OS - Debian 11

- Platform:  Raspberry Pi

### Actual behavior / bug

The  `Settings → System` page shows placeholder values for system-related values 

## Debug Token

- URL:  https://tricorder.pi-hole.net/c2ppDpPQ/

### Screenshots

![image](https://user-images.githubusercontent.com/1345886/187283492-c6d4bf36-6ddb-40f0-826d-805f4dc634b4.png)

**Comment by rdwebdesign** [comment]
This usually happens if you access the page right after restart pi-hole.

Did you try to reload the page?

**Comment by wsw70** [comment]
> This usually happens if you access the page right after restart pi-hole.
> 
> Did you try to reload the page?

I restarted the pi-hole today, a few hours ago. A refresh of the page still shows these values.
I also had them between reboots (which happen weeks apart)

**Comment by yubiuser** [comment]
What is the output of 

`ps -p 809 -o lstart`

(substitute 809 with the current FTL PID)

**Comment by wsw70** [comment]
> What is the output of
> 
> `ps -p 809 -o lstart`

```
root@rpi-datacenter ~# ps -p 8961 -o lstart
                 STARTED
Mon Aug 29 21:38:40 2022
```

It is interesting, after one more reboot yesterday the values are there this time.

I will close this issue - but it will be useful if someone has teh same problem. Thank you for your help!
