### ISSUE TITLE
curl installation method failing

### ISSUE THREAD

**Issue by folterj** [pi-hole/pi-hole#4885]
### Platform
- OS and version: Raspberry Pi OS / Raspbian 11 (bullseye)
- Platform: Raspberry Pi 3b

Using the described curl method returns a 302 response from the request.

PS: The page returns fine in a local browser and the wget method works fine too.

**Comment by yubiuser** [comment]
What exact command did you try? Please try again. I could not reproduce the issue. What version of curl are you using?

**Comment by folterj** [comment]
Hi @yubiuser,

I tried the command as stated here - multiple times, and now again, 100% reproducible on my side.
https://github.com/pi-hole/pi-hole#curl--ssl-httpsinstallpi-holenet--bash
`curl -sSL https://install.pi-hole.net | bash`
The error is due to bash trying to interpret an html response (bash: line1: html: No such file or directory ...)

The version of curl that comes with Raspbian 11 appears to be 7.74.0 (2020-12-09)

**Comment by dschaper** [comment]
What does `curl -sSL https://install.pi-hole.net` output, post the top 10 lines or so.

**Comment by rdwebdesign** [comment]
Can you try `curl -qsSL https://install.pi-hole.net`? Does it changes something?

**Comment by dschaper** [comment]
Can you get the output from `curl -iL https://install.pi-hole.net | head -n 20` please?

**Comment by folterj** [comment]
> Can you get the output from `curl -iL https://install.pi-hole.net | head -n 20` please?

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   145  100   145    0     0    271      0 --:--:-- --:--:-- --:--:--   271
HTTP/2 302 
content-type: text/html
date: Thu, 01 Sep 2022 19:20:03 GMT
location: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
server: nginx/1.20.1
content-length: 145

HTTP/2 200 
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "f9ed062495d76ed7b7f513a6d09071c76fbbab5b5eaf2d304d266f7f79be3de9"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 495C:7B99:55B463:5E4F78:631057E9
accept-ranges: bytes
date: Thu, 01 Sep 2022 19:20:04 GMT
via: 1.1 varnish
 64  122k   64 81066    0     0  30237      0  0:00:04  0:00:02  0:00:02 30237
curl: (23) Failure writing output to destination

**Comment by folterj** [comment]
It appears something changed.
When executing `curl -qsSL https://install.pi-hole.net` - it returned the full script.
Now curl `-sSL https://install.pi-hole.net | bash` is working (where before it was not).

**Comment by rdwebdesign** [comment]
Looks like this is a `curl` config issue on your machine.

**Comment by folterj** [comment]
@rdwebdesign - indeed, like the option -q ('Disable the reading of the curlrc config file') changed something in the curl configuration.
FYI this was a completely clean installation of Raspberry Pi OS / Raspbian 11 (bullseye) just before trying to install pi-hole.

**Comment by rdwebdesign** [comment]
Since the install command is working, I will close the issue.
You can reopen it if the problem resurfaces.

**Comment by GermanPearls** [comment]
In case this helps someone also experiencing this, I received the same error response as @folterj when I did not capitalize the second S and L in the curl command. Once I capitalized the SL in the -sSL portion, all worked as expected.
