### ISSUE TITLE
Pi hole not working after few days

### ISSUE THREAD

**Issue by masterhacka** [pi-hole/pi-hole#4886]
Hi there,

I set up pi-hole on a clean Raspberry setup. Everything works fine so far, but after a few days I don't have access to any URLs. Pi hole doesn't show any faults. Setting DNS away from pi hole in router settings will give internet access again.

What can I do? Please help

**Comment by yubiuser** [comment]
Please open a help topic on our discourse page. We can help you more effectively in that forum.

https://discourse.pi-hole.net/
