### ISSUE TITLE
PHP code instead of page

### ISSUE THREAD

**Issue by DinozavrIV** [pi-hole/pi-hole#4892]
### Versions
- Pi-hole:  v5.12
- AdminLTE:  v5.14.1
- FTL:  v5.17

### Platform

- OS and version: Ubuntu 22.04

- Platform: x86_64 Laptop (I'm sorry if I indicated the wrong platform, I'm just new to this field.)

### Expected behavior

When I go to the pi.hole/admin page, I see a login menu

### Actual behavior / bug

When I go to the pi.hole/admin page, I see php code

### Steps to reproduce

1. Install Pi-Hole
2. Go to the pi.hole/admin

## Debug Token

- URL:  https://tricorder.pi-hole.net/AfscHnU9/

### Screenshots

![image](https://user-images.githubusercontent.com/112756243/188266492-5ce1eee4-0bf1-4e73-9655-804d62fa9932.png)

### Additional context

Сhanged the port to 81 because of apache, lighttpd service works

**Comment by yubiuser** [comment]
Only `ligthhtp` is supported and as you said, this is working. Please go to our user forum to get support from other users running Apache.

https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36
