### ISSUE TITLE
[possible regression] Accessing the reduced dashboard whithout being logged in doesn't work anymore.

### ISSUE THREAD

**Issue by x2k13** [pi-hole/pi-hole#4895]
Pi-hole [v5.12](https://github.com/pi-hole/pi-hole/releases/v5.12) FTL [v5.17](https://github.com/pi-hole/FTL/releases/v5.17) Web Interface [v5.14.1](https://github.com/pi-hole/AdminLTE/releases/v5.14.1)

After updating to these versions yesterday, the dashboard isn't accessible without being logged in anymore. Why? Is there a setting somewhere that I missed?

If this is expected behaviour from now on, it might be good to have a checkbox somewhere in the setttings to switch that on/off.

**Comment by yubiuser** [comment]
If you don't set a password you should be able to access the dashboard without log in.

**Comment by yubiuser** [comment]
> New login splash page
This change will be the most immediately obvious to those that have their web interface behind a password.
 >
>Unauthenticated requests are now presented with a login page, and the previously seen data is now suppressed until a user is logged in.

https://discourse.pi-hole.net/t/upcoming-pi-hole-changes/57402

**Comment by x2k13** [comment]
Okay, but how to get it back?

**Comment by yubiuser** [comment]
You can't. We removed the old unauthorized login page. If you are not logged in no stats should be visible.
