### ISSUE TITLE
pihole restartDns reload not working

### ISSUE THREAD

**Issue by zSprawl** [pi-hole/pi-hole#4898]
### Versions

- Pi-hole:  5.12
- AdminLTE:  5.14.2
- FTL:  5.17

### Platform

- OS and version:  Ubuntu 20, Raspbian

- Platform:  Raspberry Pi and VMware ESXi

### Expected behavior

When you type:

pihole restartdns reload

It should flush the cache.

### Actual behavior / bug

Instead it says: FTL is not running.

### Steps to reproduce

1. Go to 'terminal'
2. Type '/usr/local/bin/pihole restartdns reload'

### Additional context

I can see the issue is on line 115 of the file pihole

https://github.com/pi-hole/pi-hole/blob/master/pihole

The line needs to be moved up outside of the if statement so that it is available for the else.

Another way to say it is to move line 115 to line 106.

I did it on my own copy and it works correctly. However, I wanted an expert to look and verify as I'm not a GitHub expert or developer. Thanks!

**Comment by rdwebdesign** [comment]
Reading the code looks like you're right, but I will ask for confirmation.

There will be no value for `${FTL_PIDFILE}` in line 130:
https://github.com/pi-hole/pi-hole/blob/f998eee4675c92819bde40f338fefe8feb7ba3b4/pihole#L130

**Comment by yubiuser** [comment]
Thanks for your report. This is a bug. I'll fix that.

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-18-web-v5-15-and-core-v5-12-1-released/57894
