### ISSUE TITLE
[Tracking] Number of domains after gravity run not equal dashboard number on v5.12

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#4900]
Reported here 
https://discourse.pi-hole.net/t/number-of-domains-not-updating-after-gravity-run/57609

**Comment by rdwebdesign** [comment]
Just to add more info:

I executed `echo ">stats" | nc 127.0.0.1 4711` in a pi-hole install using only the default adlist.
The number of domains returned by FTL were: `domains_being_blocked 136768`.
I also updated gravity. The gravity update output showed: `  [i] Analyzed 137654 domains`.
I ran the `>stats` command again, but same incorrect number `136768` was returned.

After that, I disabled and re-enabled all domains/regex using "Group Management - Domains" page.
Now the web interface and ">stats" are showing the same number (**`137654`**) as gravity update.

**Comment by yubiuser** [comment]
I tracked it down a bit further: 
The stats reported from `FTL` are read from the database itself here: 
https://github.com/pi-hole/FTL/blob/f64349bb298e70bf2c732b2adce3e9a4b02afd04/src/database/gravity-db.c#L1087

This is called by `FTL_reload_all_domainlists` which in turn is trigged by the `RELOAD_GRAVITY` event. This happens on `reload`. 
`Reload` is executed after each (successful) gravity run
https://github.com/pi-hole/pi-hole/blob/f998eee4675c92819bde40f338fefe8feb7ba3b4/gravity.sh#L1026-L1028

However, `reload` was broken https://github.com/pi-hole/pi-hole/issues/4898.

As this was fixed by https://github.com/pi-hole/pi-hole/pull/4899, this issue here is also fixed now in `development` as well.

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-18-web-v5-15-and-core-v5-12-1-released/57894
