### ISSUE TITLE
[Tracking] Raspberry Pi OS switch from dhcpd to NM

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#4902]
Our installer should be compatible with the upcoming change to Raspberry Pi OS 

https://www.raspberrypi.com/news/the-latest-update-to-raspberry-pi-os/

**Comment by dschaper** [comment]
I think our consensus is that we will not be changing to support a new IP stack manager.

**Comment by yubiuser** [comment]
Yes. That's why I created the linked pull request. Once Raspbian makes the switch we can merge the PR (surely will need adaption) and close the issue.
