### ISSUE TITLE
Whitelist and BlackList not appearing on the admin-panel on v5.14.2

### ISSUE THREAD

**Issue by unaRIpurpose** [pi-hole/pi-hole#4904]
### Versions

  Pi-hole version is v5.12 (Latest: v5.12)
  AdminLTE version is v5.14.2 (Latest: v5.14.2)
  FTL version is v5.17 (Latest: v5.17)
### Platform

- OS and version:   Raspbian

- Platform:  Raspberry Pi

### Expected behavior

Blacklist and Whitelistlist link/Page should be appearing on the admin panel

### Actual behavior / bug

![BLWLlinkNotAppearing](https://user-images.githubusercontent.com/94373861/189511638-3face0d9-6dd6-4362-89fa-39eadbe59773.png)
Blacklist and Whitelistlist link/Page NOT appearing on the admin panel

### Steps to reproduce

1. Go to 'admin page http://pi.hole/admin/index.php'
2. Links should appear and page should render on clicking

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
This is the intended behavior.
Please, read the [Release Notes](https://pi-hole.net/blog/2022/09/02/pi-hole-ftl-v5-17-web-v5-14-and-core-v5-12-released/) and this [announcement](https://discourse.pi-hole.net/t/upcoming-pi-hole-changes/57402).

---

You can find your Whitelists and Blacklist on the **Domains** page.

**Explanation:**

The old Whitelist, Blacklist and Domains pages were actually the same page:
- Whitelist was `groups-domains.php?type=white`;
- Blacklist was `groups-domains.php?type=black`;
- Domains was (and still is) `groups-domains.php`.

The separate views of the page were removed.

**Note:**
An improvement to the new page is already in development branch. We created a filter to isolate domains by type.
https://github.com/pi-hole/AdminLTE/pull/2334

**Comment by unaRIpurpose** [comment]
Thanks .... My bad!
