### ISSUE TITLE
Valid domains flagged as invalid

### ISSUE THREAD

**Issue by User9684** [pi-hole/pi-hole#4911]
### Versions

- Pi-hole:  v5.12
- AdminLTE:  v5.14.2
- FTL:  v5.17

### Platform

- OS and version:  Raspbian  11

- Platform:  Raspberry Pi

### Expected behavior

Domain added on adlist using special characters such as accented characters should be flagged.

### Actual behavior / bug

Domains with special characters flagged as invalid, despite being entirely valid.

### Steps to reproduce

1. Add adlist https://raw.githubusercontent.com/User9684/fishfish-pihole/master/hosts
2. Update adlists
3. Error is shown in console

**Comment by yubiuser** [comment]
International domain names (IDN) are typically requested only in their encoded form, i.e., it doesn't make sense to include them with non-ASCII characters in the list.

The list maintainer should convert them to IDN names.

**Comment by User9684** [comment]
Yes yes, I figured that out and I am converting them now
