### ISSUE TITLE
Summary dashboard replaced with login prompt

### ISSUE THREAD

**Issue by b0bh00d** [pi-hole/pi-hole#4919]
### Versions
root@raspberrypi:~# pihole -v
  Pi-hole version is v5.12.1 (Latest: v5.12.1)
  AdminLTE version is v5.15 (Latest: v5.15)
  FTL version is v5.18 (Latest: v5.18)

### Platform
root@raspberrypi:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Expected behavior

Opening "http://<ip_address>/admin" displays a summary dashboard with limited (but useful) information

### Actual behavior / bug

Opening "http://<ip_address>/admin" displays a login prompt

### Additional context

Just did a "pihole -up" and lost the summary dashboard.

**Comment by PromoFaux** [comment]
This is intentional and has been the case since 5.14. 

A pre-warning blog post was published: https://discourse.pi-hole.net/t/upcoming-pi-hole-changes/57402/4
The release notes were then published: https://discourse.pi-hole.net/t/pi-hole-ftl-v5-17-web-v5-14-and-core-v5-12-released/
