### ISSUE TITLE
Setup logstagia in pi hole

### ISSUE THREAD

**Issue by msyahmi1998** [pi-hole/pi-hole#492]
Recently i have been using pi hole for blocking ad and addition i found your video using Logstalgia with pi hole and addition article how to setup but 
![untitled](https://cloud.githubusercontent.com/assets/19188069/15015867/cfb2d4b4-1240-11e6-9303-e5b032505d63.png)

i geeting this error
![untitled2](https://cloud.githubusercontent.com/assets/19188069/15015915/17a2f3ee-1241-11e6-93f4-55c0102a07af.png)

Thank you

**Comment by DonLexos** [comment]
Is this the thing you are trying to setup? http://logstalgia.io/

**Comment by PromoFaux** [comment]
A couple of things.. You're only running half the command (see where yours cuts off at `.../pi-` you need to include the bit below, too, as it's all one line.

Secondly, if you're running the latest version of pi-hole, you wont need to do that step anyway, as the script should already be up to date!

Pinging @jacobsalmela to update his blogpost...  ;)

**Comment by jacobsalmela** [comment]
updated!  

Yep, @msyahmi1998 just do a fresh install and then run this command (use your IP address):

```
ssh pi@192.168.1.200 "tail -f /var/log/lighttpd/access.log" | logstalgia
```

**Comment by Fedora-Core** [comment]
Tip:

Read the manpages of the Utility **tailf** and consider its use - or not - instead of **tail -f**

_the Utility **tailf** was developed for files like logfiles_

Extra:

Parameter **--lines 300** will start with the last 300 lines instead of the default 10.

Greetings, F.C.

**Comment by msyahmi1998** [comment]
Hi I was  try it and it give me permision denied 
![untitled](https://cloud.githubusercontent.com/assets/19188069/15027483/9f5d6c30-1276-11e6-82f1-279b3c34c4fa.png)

Sorry still new with linux 
Thank you

**Comment by PromoFaux** [comment]
Just tried this myself (for the first time ever actually...!) 

change your command to:
`ssh pi@192.168.0.111 "sudo tail -f /var/log/lighttpd/access.log" | logstalgia`

**Comment by PromoFaux** [comment]
Also, depending on the version of Ubuntu you're running, you may have a different version of logstalgia to me. Just discovered this when @Mcat12 couldn't get it to work (Ubuntu 14.04, logstalgia 1.0.3-4), but I could (Ubuntu 16.04, logstalgia 1.0.7-1) Both installed logstalgia with `sudo apt-get install logstalgia`

if you're on the earlier version, and you get issues, try adding  ` -` to the end of the command

**Comment by Mcat12** [comment]
The `-` command seems to only work for the latest log entries. It doesn't seem to want to grab the new entries.

**Comment by msyahmi1998** [comment]
Thanks guys it work and if you add **--sync** It will pull log for real time
