### ISSUE TITLE
Time out for adlists

### ISSUE THREAD

**Issue by redregar** [pi-hole/pi-hole#4920]
### Versions

Pi-hole [v5.12]
FTL [v5.17]
Web Interface [v5.14.2]

### Platform

- OS and version:  
- 

- Platform:  Raspberry Pi 4

### Expected behavior

time out for not reachable or corrupted adlists

### Actual behavior / bug

update gravity freezes in following status:

[i] Target: https://easylist.to/easylist/fanboy-annoyance.txt
  [i] Status: Pending...

### Steps to reproduce

stored the adlist : https://easylist.to/easylist/fanboy-annoyance.txt

and started update gravity in web interface

**Comment by jfb-pihole** [comment]
Don't use this list - it is not compatible with Pi-hole.  Pi-hole requires a hosts formatted list.  From the easylist.to website:

"The EasyList filter lists are sets of rules originally designed for Adblock that automatically remove unwanted content from the internet, including annoying adverts, bothersome banners and troublesome tracking. The filter lists are currently maintained by four authors, Fanboy, MonztA, Famlam and Khrin, who are ably assisted by an ample forum community.

The links listed below allow you to select filter lists for use in your browser provided that you are using a compatible ad blocker (tested with Adblock Plus, AdBlock and uBlock Origin."
