### ISSUE TITLE
pihole restartdns sets incorrect permissions on pihole logfile

### ISSUE THREAD

**Issue by danradom** [pi-hole/pi-hole#4927]
### Versions

- Pi-hole:  v5.12.2
- AdminLTE:  v5.15.1
- FTL:  v5.18.1

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  LXC

### Expected behavior

Pihole should either leave permissions alone or use the logrotate file when it restarts.

### Actual behavior / bug

Pihole resets permissions on the log to 640

### Steps to reproduce

root@ph1:~ # ls -l /var/log/pihole/pihole.log
-rw-r--r-- 1 pihole pihole 156527 Sep 19 10:59 /var/log/pihole/pihole.log

root@ph1:~ # pihole restartdns
  [_] Restarting DNS server

root@ph1:~ # ls -l /var/log/pihole/pihole.log
-rw-r----- 1 pihole pihole 162113 Sep 19 11:00 /var/log/pihole/pihole.log

root@ph1:~ # logrotate -f /etc/pihole/logrotate

root@ph1:~ # ls -l /var/log/pihole/pihole.log
-rw-r--r-- 1 pihole pihole 635 Sep 19 11:00 /var/log/pihole/pihole.log

## Debug Token

- URL:   https://tricorder.pi-hole.net/0Y15s3CB/

### Screenshots

/var/log/pihole/pihole.log {
        su root root
        create 0644 pihole pihole
        daily
        copytruncate
        rotate 365
        compress
        delaycompress
        notifempty
        nomail
        postrotate /bin/chmod 644 /var/log/pihole/pihole.log
        endscript
}

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Is this your custom logrotate script?

>create 0644 pihole pihole
daily
copytruncate
rotate 365
compress
delaycompress
notifempty
nomail
postrotate /bin/chmod 644 /var/log/pihole/pihole.log
endscript

We do set the permissions on every restart

https://github.com/pi-hole/pi-hole/blob/d88629e23fcfbf52b97bf14800bfc510b0284be6/advanced/Templates/pihole-FTL.service#L42

We decided that the log can contain highly sensible data and should not be readable by everyone.
See https://github.com/pi-hole/pi-hole/pull/4760

**Comment by rdwebdesign** [comment]
Adding info to previous comment:

Your custom `logrotate` config is using the wrong permissions.
The original config never changes the permissions:

```ini
/var/log/pihole/pihole.log {
        su root root
        daily
        copytruncate
        rotate 5
        compress
        delaycompress
        notifempty
        nomail
}

/var/log/pihole/FTL.log {
        su root root
        weekly
        copytruncate
        rotate 3
        compress
        delaycompress
        notifempty
        nomail
}
```
