### ISSUE TITLE
Docker files Security Issues

### ISSUE THREAD

**Issue by GOATFUCK69** [pi-hole/pi-hole#4928]
i scanned this repo  with snyk and it said this a bunch of vulns in the docker files in the test directory

**Comment by PromoFaux** [comment]
Real helpful, thanks.

**Comment by rdwebdesign** [comment]
If you have data about vulnerabilities you can send us using the e-mail provided here:
https://github.com/pi-hole/pi-hole/security/policy

Pi-hole welcomes all responsible disclosures. **Please do not open an ISSUE to report a security problem**

We accept disclosures via email at disclosure@pi-hole.net.

**Comment by PromoFaux** [comment]
That all said, the test dockerfiles are only ever used in the testing process. I believe this was brought up before, and we decided it was an acceptable risk.
