### ISSUE TITLE
Installer exits prematurely when run from LXC terminal invoked via 'pct enter'

### ISSUE THREAD

**Issue by iGadget** [pi-hole/pi-hole#4930]
### Versions

- Pi-hole:  N/A
- AdminLTE:  N/A
- FTL:  N/A

### Platform

- OS and version:  Ubuntu 22.04 (as LXC)

- Platform:  Proxmox, LXC

### Expected behavior

The installer should run as expected even when started from an LXC terminal invoked via 'pct enter'

### Actual behavior / bug

The installer exits prematurely, displaying '[i] Installer exited at static IP message.'

### Steps to reproduce

1. Install Ubuntu 22.04 LXC container via Proxmox' stock template
2. Start container
3. Log into Proxmox node via SSH
4. Access the Ubuntu 22.04 container via 'pct enter [container ID]'
5. Run updates and install curl
6. Run 'curl -sSL https://install.pi-hole.net | bash'

Result: Installer briefly runs and then exits with the error mentioned above.

### Additional context

When SSH'ing into the Ubuntu 22.04 container *directly* and then starting the installer, it works fine.

**Comment by yubiuser** [comment]
My guess it's failing already at the first `dialog` shown.

https://github.com/pi-hole/pi-hole/blob/d88629e23fcfbf52b97bf14800bfc510b0284be6/automated%20install/basic-install.sh#L578-L596

I'm not familiar with Proxmox and their environment, but can you check if `dialog` is available to the  LXC terminal ?

**Comment by iGadget** [comment]
> I'm not familiar with Proxmox and their environment, but can you check if `dialog` is available to the LXC terminal ?
Not sure how to check that - if I enter 'dialog' in either the LXC terminal or the 'normal' SSH terminal it just displays the standard help text. Does that mean it's available?

**Comment by yubiuser** [comment]
```
dpkg -l dialog
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-======================================
ii  dialog         1.3-20190211-1 arm64        Displays user-friendly dialog boxes fr

```

**Comment by dschaper** [comment]
Run `curl -sSL https://install.pi-hole.net | sudo bash -x` but the issue is likely that entering the container with proxmox's tool is not an environment that is meant to do this.

**Comment by iGadget** [comment]
@yubiuser oh it is installed, if that's what you mean. Otherwise it probably also wouldn't work on a 'normal' SSH terminal I suppose?
@dschaper Ah that '-x' seems to do it indeed. Apparently, "Print commands and their arguments as they are executed" (as found in the bash man page) is disabled by default when the shell is invoked with 'pct enter'? And per the other link you found, there may be even more non-standard tweaks...

**Comment by dschaper** [comment]
The `-x` was to print out the steps as they were taking place so that we could see exactly where it failed or kicked out. You were able to complete the install successfully with the `-x` flag added?

**Comment by dschaper** [comment]
It may behave differently if there were dependent packages or some other type of conflict.

If you have the time, can you spin up a new `lxc` with the same template and before you run the install script with `sudo bash -x` please post the output from `env` so we can look to see if there are any shell issues.

**Comment by iGadget** [comment]
@dschaper Ok, this is weird... 

- I cloned the LXC from the snapshot I took right before I installed pihole.
- Took a snapshot of that new clone.
- I then ran `curl -sSL https://install.pi-hole.net | sudo bash -x` on the new LXC - works fine.
- I then tried without the `-x`.. and that worked fine as well?!
- Rolled back the snaphot just to be sure
- Tried again without the `-x`... Just works.
Unless a new version of the installer has been rolled out between now and 3 days ago, I cannot explain why it's working now and it wasn't working 3 days ago. What am I missing?

**Comment by bekopharm** [comment]
I did run into the same issue:

Proxmox 7.2-11
Debian 11 stock template

Made sure to have a "full" login after entering the LXC from the Proxmox host using `su -l -s /bin/bash root`

This is my env:

```
SHELL=/bin/bash
PWD=/root
LOGNAME=root
XDG_SESSION_TYPE=tty
HOME=/root
LANG=de_DE.UTF-8
XDG_SESSION_CLASS=user
TERM=linux
USER=root
SHLVL=1
XDG_SESSION_ID=c1
XDG_RUNTIME_DIR=/run/user/0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAIL=/var/mail/root
_=/usr/bin/env
```

I did run `bash -x`. I did copy the dialog command and can confirm that dialog itself seems to work.

The installer itself does exit with `[i] Installer exited at static IP message.` after filling the screen with blue from `dialog`.

It *does* work when the LXC is entered via Proxmox WEB UI => CT => `>_ Console` which is a full login. The env looks like this after doing so:

```
SHELL=/bin/bash
PWD=/root
LOGNAME=root
MOTD_SHOWN=pam
HOME=/root
LANG=de_DE.UTF-8
INVOCATION_ID=b6f1b93ad7b24578a534f52fbb4ef341
TERM=linux
USER=root
SHLVL=1
JOURNAL_STREAM=8:5651230
HUSHLOGIN=FALSE
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAIL=/var/mail/root
_=/usr/bin/env
```

I tried replicating the env by unsetting and exporting variables to my usual login shell from entering the LXC but no result. It would still break at the expected step.

Features like "Nesting" or setting console mode from tty to console had no effect.

**Comment by Mr-Technician** [comment]
This appears to be an issue only if you use `lxc-attach` from the Proxmox shell. If you enter the shell from the container submenu, the error will not be thrown.

This works:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/26885142/214194612-b95d81b5-23d2-4ae0-8344-a3e89b09af5d.png">

This doesn't:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/26885142/214194683-1a5d779a-a146-4b28-8d7a-5e6646d29f92.png">

**Comment by dannykellett** [comment]
> This appears to be an issue only if you use `lxc-attach` from the Proxmox shell. If you enter the shell from the container submenu, the error will not be thrown.
> 
> This works: <img alt="image" width="429" src="https://user-images.githubusercontent.com/26885142/214194612-b95d81b5-23d2-4ae0-8344-a3e89b09af5d.png">
> 
> This doesn't: <img alt="image" width="580" src="https://user-images.githubusercontent.com/26885142/214194683-1a5d779a-a146-4b28-8d7a-5e6646d29f92.png">

Neither console worked for me. I had to enable ssh and use putty to the LXC and that worked

**Comment by jeremycadams** [comment]
Ran into the same problems with Proxmox and using a Debian 12 LXC to attempt to install Pi-Hole. @dannykellett 's listed correction from June 29 also allowed me to login properly and install Pi-Hole without the errors. Note that I had to change the default console setting to "shell" under the Proxmox container Options dialog (from the default of "Default (tty)" to even get into edit the SSH config settings, but doing so did allow me to remote in via SSH.

**Comment by mr-scrpt** [comment]
I have this problem
Tried using ubuntu and debian, tried connecting via ssh through my kitty and konsole, tried changing the default console mode to shell in the lx container settings, none of this helped.

**Comment by taiwithers** [comment]
> I have this problem Tried using ubuntu and debian, tried connecting via ssh through my kitty and konsole, tried changing the default console mode to shell in the lx container settings, none of this helped.

Just want to chime in that my install (pi running Rasberry Pi OS Lite, accessing over SSH with the Kitty terminal) also failed at the static IP message:
```
Error opening terminal: xterm-kitty.
  [i] Installer exited at static IP message.
```

SSH-ing with Konsole worked for me though.
