### ISSUE TITLE
piholeDebug.sh: Network check fails if multiple default gateways are present

### ISSUE THREAD

**Issue by ottnorml** [pi-hole/pi-hole#4933]
### Versions

- Pi-hole:  v5.12.2
- AdminLTE: v5.12.2
- FTL:  v5.18.1

### Platform

- OS and version:  Debian GNU/Linux 11 (bullseye)

- Platform:  Docker (armv7)

### Expected behavior

If the network interface configured in `$PIHOLE_INTERFACE` has multiple IP addresses assigned to it and thus has multiple default gateways, I expect the network check of the `piholeDebug.sh` script to be able to ping all default gateways.

### Actual behavior / bug

Instead of pinging each default gateway, the network check fails on multiple default gateways because the ping command cannot handle multiple IP addresses at the same time.

### Steps to reproduce

1. Assign multiple IP addresses and default gateways to the network interface configured in `$PIHOLE_INTERFACE`.
2. Run the `piholeDebug.sh` script
3. See error:
```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
    192.168.178.10/24

[✓] IPv6 address(es) bound to the eth0 interface:
    fd01:5ee:bad:c0de:d2ad:82ff:fe01:c765/64
    2001:a61:121b:5001:d2ad:82ff:fe01:c765/64
    fd01:5ee:bad:c0de:42:c0ff:fea8:b20a/64
    fe80::d2ad:82ff:fe01:c765/64

[i] Default IPv4 gateway: 192.168.178.1
   * Pinging 192.168.178.1...
[✓] Gateway responded.
[i] Default IPv6 gateway: fd01:5ee:bad:c0de:3ea6:2fff:fec7:e816
fe80::3ea6:2fff:fec7:e816
   * Pinging fd01:5ee:bad:c0de:3ea6:2fff:fec7:e816
fe80::3ea6:2fff:fec7:e816...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

**Comment by yubiuser** [comment]
I do see where you are coming from, but think it is not necessary to ping all gateways. This will not add any extra valuable information. However, I think the code can be improved to try ping only one of the default gateways

**Comment by yubiuser** [comment]
Please try if `pihole checkout core one_gateway` resolves the issue for you. You can go back on track (and before the next update) with `pihole checkout core master`

**Comment by ottnorml** [comment]
Thanks for the quick response, @yubiuser. Your solution is working as expected. :)

**Comment by PromoFaux** [comment]
Keeping open for now as it will not actually be fixed until we next release
