### ISSUE TITLE
Blocking custom sites not working as intended

### ISSUE THREAD

**Issue by Dolyak** [pi-hole/pi-hole#494]
So i am trying to block a list of porn sites for a buddy of mine and his kids. I went to [1]  and it had a pretty long / complete list of domains I want to block. I followed [2] and added a black list to the gravity.list without a problem. When i go to the web UI i see that i am blocking 642,738 domains (screenshot attached), So i am pretty sure that its getting all if not most of the sites i want to block.

My Problem is that when I go a porn site its not being blocked. My test site is pornhub.com. I have made sure that the domain is in my gravity.list:

```
raspberrypi:/etc/pihole# grep pornhub.com gravity.list
192.168.1.94 www.pornhub.com
192.168.1.94 pornhub.com
```

I am unsure of a way to see that is actively being blocked but i can say that before i loaded the porn blacklist i was no were near 642,738 domains. When i look at /var/log/pihole.log i see normal traffic but no traffic about blocking any domain that was added on top of the normal domains that come pre loaded. 

```
raspberrypi:/var/log# tail -f pihole.log
May  5 02:57:20 dnsmasq[2104]: config Erins-MBP is NODATA-IPv6
May  5 02:57:26 dnsmasq[2104]: query[A] i1.mangapanda.com from 192.168.1.1
May  5 02:57:26 dnsmasq[2104]: forwarded i1.mangapanda.com to 8.8.8.8
May  5 02:57:26 dnsmasq[2104]: reply i1.mangapanda.com is 104.20.31.160
May  5 02:57:26 dnsmasq[2104]: reply i1.mangapanda.com is 104.20.32.160
May  5 02:57:37 dnsmasq[2104]: query[A] www.facebook.com from 192.168.1.1
May  5 02:57:37 dnsmasq[2104]: cached www.facebook.com is <CNAME>
May  5 02:57:37 dnsmasq[2104]: forwarded www.facebook.com to 8.8.8.8
May  5 02:57:37 dnsmasq[2104]: reply www.facebook.com is <CNAME>
```

What i did to get the blacklist to take:
1. Added all porn domains to blacklist.txt at /etc/pihole/ 
2. couldn't get the pihole command to work? so i ran curl -L https://install.pi-hole.net | bash 
    this updated and imported my blacklist.txt into  gravity.list.
3. on my windows box i in CMD ran ipconfig /flushdns to make sure i was not picking up cache sites
4. removed the cache off my test browser
5. went to pornhub.com and can still get to it. i tailed the log and it didn't say anything there about it trying to block.

At this point i am not sure were to go next. Does anyone know of something i might be missing? I think i am doing everything right but clearly i am missing something. 

Thank you for your time.

URL list:

[1] http://urlblacklist.com/
[2] https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists

Screenshots:

![snip of webui](https://cloud.githubusercontent.com/assets/19198847/15035176/e7ab3cbc-124c-11e6-9cdf-5f511f6d4e25.PNG)
##

**Comment by Dolyak** [comment]
After reinstalling i now have access to the pihole command so i ran a pihole -g to import all the list in to gravity.list. this didn't fix my problem.

raspberrypi:/etc/pihole# pihole -g
:::
::: You are root.
::: Neutrino emissions detected...
:::
::: Custom adList file detected. Reading... done!
:::
::: Existing pihole directory found
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting adblock.gjtech.net list... No changes detected, transport skipped!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
::: Getting sysctl.org list... No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting hosts-file.net list... No changes detected, transport skipped!
::: Getting securemecca.com list... No changes detected, transport skipped!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 154331 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 114890 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 10 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 8 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 527846 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!

**Comment by PromoFaux** [comment]
Can you please run `pihole -d` and paste the output of `/var/log/pihole_debug.log` to pastebin and share the link here.  Thanks!

**Comment by PromoFaux** [comment]
Also, I notice you're adding a hell of a lot of domains to the blacklist. Is that intentional?

Might be easier to manage if you create a seperate file (e.g `/home/<user>/customblocklist.txt`) and then add it to `/etc/pihole/adlists.list` as `file://home/<user>/customblocklist.txt`

**Comment by PromoFaux** [comment]
It could also be that the addresses are cached on your local machine... try flushing the dns cache on your client, and clearing all userdata from your browser before navigating to a blocked site again.

**Comment by Mcat12** [comment]
You can also more easily check if the domain is blocked or not by using `dig domain1`, `nslookup domain1`, or `ping domain1` from your Pi-hole. Then you would not have the possibility of accidentally loading cached DNS records.

**Comment by Dolyak** [comment]
Thank you for everyone's fast response. I will get this info the min I get home from work and post it here. Wanted to make sure you knew i wasn't ignoring your helpful advice.

**Comment by PromoFaux** [comment]
For future reference, try and use the whitelist and blacklist as on the fly lists (you can add or remove to them using the `pihole` command, and there is no need to run gravity to update them that way)

For large lists like the one from urlblacklist.com, just add them to adlists.list, and you should be grand!


Let us know if you run into any issues later on...!

**Comment by Dolyak** [comment]
Ok so i added my file with the line file:///etc/pihole/PornBlacklist.txt in the adlist.list file. I ran the pihole -g command and attached the output in the attachment "pihole -g command output" 

Once that was done i check my web UI and see that i am blocking 633,134 domains so good sign.

I Ran the pihole -d command and attached the output to "pihole_debug.log"

ran the dig command:

root@raspberrypi:/etc/pihole# dig pornhub.com

; <<>> DiG 9.9.5-9+deb8u6-Raspbian <<>> pornhub.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31680
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pornhub.com.                   IN      A

;; ANSWER SECTION:
pornhub.com.            300     IN      A       192.168.1.94

;; Query time: 11 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu May 05 22:49:37 UTC 2016
;; MSG SIZE  rcvd: 56

I also in the middle of the debug when it 

::: Writing current pihole traffic to debug log...
:::     Try loading any/all sites that you are having trouble with now...

I went to pornhub.com and the site still loads without making a log entry in the pihole.log

Uploaded files:

[pihole_debug.log.txt](https://github.com/pi-hole/pi-hole/files/251341/pihole_debug.log.txt)

[adlist.list.txt](https://github.com/pi-hole/pi-hole/files/251331/adlist.list.txt)

[Pihole -g command output.txt](https://github.com/pi-hole/pi-hole/files/251332/Pihole.-g.command.output.txt)

**Comment by Mcat12** [comment]
Are any other ads/sites blocked? You might want to set your dns settings on your router/computer. The logs show that all the correct the sites are being blocked.

**Comment by PromoFaux** [comment]
Any update @Dolyak ?

**Comment by Dolyak** [comment]
Ok so were i am at is that my dd-wrt router was not handing out the pihole as the default DNS. I fixed that problem by adding the PIhole to my computers config. Now when i try to go to a porn site it blocks the traffic. The problem is when i go to a google search and then click on the link from there i can still get to the site... the PI log is attached. I think the problem is that when using a google search my DNS is getting forwarded to googles DNS for some reason. Any Ideas?


[PI log.txt](https://github.com/pi-hole/pi-hole/files/267221/PI.log.txt)

**Comment by Dolyak** [comment]
@PromoFaux What do you think? I forgot to tag you in my above response. Sorry.

**Comment by Mcat12** [comment]
It should work the same... Check by pinging the domain on your Pi-hole and computer.

**Comment by Dolyak** [comment]
Pinging the site from the pihole is blocked like it should be. The problem comes when you google the site and click on the url from there. I have talked with a few other people at work and they have the same problem. I think this is due to the pi allowing google to redricet the traffic when you click on a link. Please see my above post with the pi log and you will see what i am talking about.

**Comment by Biothrawn** [comment]
I am seeing the exact same issue as Dolyak. the Pi will block any direct contact with the sites, but as soon as you google the site and click the link you have access. its as if google hands out its own DNS after you google the site.

**Comment by Mcat12** [comment]
Tail the log and check what is happening. `tail -f /var/log/pihole.log`

**Comment by Biothrawn** [comment]
https://github.com/pi-hole/pi-hole/files/267221/PI.log.txt
Same results as Dolyak's

**Comment by Mcat12** [comment]
I just tested blocking xda-developers.com (with and without www.) and it was blocked after clicking from Google. If it's not working on yours, check that you blocked both versions with/without www and make sure if you're on a mobile device (phone, etc) to wait at least 300 seconds or reboot so that the DNS cache updates.

**Comment by Mcat12** [comment]
I blacklisted from one device then tested on a device that hadn't gone to XDA in awhile. I just rebooted the first device and it's still going to xda correctly, so the best bet is to wait awhile and then test if you're using one device.

**Comment by Biothrawn** [comment]
I will check that Tonight, and update tomorrow.
Thank you for the quick reply

**Comment by Biothrawn** [comment]
That was our problem
"I just tested blocking xda-developers.com (with and without www.)" @Mcat12 

I wasnt blocking www.domanin-name.com, just domain-name.com. After adding www. Everything is working. I cant believe I missed that part.

Thanks for your time

**Comment by Mcat12** [comment]
@Dolyak that ad list might not be blocking the www version of domains.

**Comment by killahkazx** [comment]
why dont you set up an account with opendns they can set some porn site off for you and do the res with a custom list?

**Comment by PromoFaux** [comment]
@Dolyak Is this issue resolved?

**Comment by jacobsalmela** [comment]
Closing due to lack of response.

**Comment by akmlhkmi** [comment]
why it shows this when i open my system?

![image](https://user-images.githubusercontent.com/34821824/34329832-752e0d50-e94a-11e7-8a06-372a95d63852.png)

**Comment by Mcat12** [comment]
@akmlhkmi Please open a new issue instead of commenting on one which is more than a year old.
