### ISSUE TITLE
Adlist with ID x was inaccessible during last gravity run message will reappear after disabling piHole

### ISSUE THREAD

**Issue by Thomas311926** [pi-hole/pi-hole#4942]
### Versions

- Pi-hole:  v5.12.2-4-g3320e41
- AdminLTE:  v5.15.1
- FTL:  v5.18.1

### Platform

- OS and version:  Debian GNU/Linux 11 (bullseye) aarch64

- Platform:  Raspberry Pi 4B

### Expected behavior

The message should not reappear.

### Actual behavior / bug

The message reappeared.

### Steps to reproduce

1. Get a Adlist with ID x was inaccessible during last gravity run message.
2. Delete that message.
3. Disable pihole for 10 seconds and refresh the page.
4. The message will reappear.

## Debug Token

KSMvKQ1T

**Comment by yubiuser** [comment]
The message is correct, the adlist is still not accessible. Every restart (or change of the blocking state) of Pi-hole will trigger a rescan for errors.

**Comment by rdwebdesign** [comment]
Note:

> The message is correct, the adlist is still not accessible.

If the list is temporarily not accessible, you will need to wait. Pi-hole will recreate the message every time you enable it until the list become accessible again.
If the list is permanently inaccessible you will need to remove the list.

**Comment by yubiuser** [comment]
> Pi-hole will recreate the message every time you enable it until the list become accessible again.

Pi-hole checks for accessibility on each gravity run (usually once per week each Sunday morning).
