### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by MiChaelinzo** [pi-hole/pi-hole#4943]
### Versions

- Pi-hole:  Latest version
- AdminLTE:  
- FTL:  bash

### Platform

- OS and version:  Linux Version 5.4.51-v7l+ 

- Platform:  Raspberry Pi 4 Model B+

### Expected behavior

To install and run the Pi Hole

### Actual behavior / bug

It won't install and run

### Steps to reproduce

```
wget -O basic-install.sh https://install.pi-hole.net
sudo bash basic-install.sh

```
1. Install using method 1, 2, 3
2. Waiting and configure installation 
3. waiting and it shows problems in updating
`4. Error: Could not update local repository. Contact support
`
## Debug Token

- URL:  

### Screenshots
![PiholeError308805319_2902838870021001_8133049061570933113_n](https://user-images.githubusercontent.com/68110223/192319807-6d570900-2b6d-4e82-86a3-76233ef42918.jpg)
****

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.

**Comment by MiChaelinzo** [comment]
> Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our [Discourse](https://discourse.pi-hole.net) forum.
> 
> Thank you for your understanding.

This is very disappointing

**Comment by dschaper** [comment]
Hi, sorry you feel that way.

**Comment by MiChaelinzo** [comment]
> Hi, sorry you feel that way.

Is there no current solution? I like the software... I got it working back in a container in my Kali Linux but currently installing it on my Raspberry Pi 4 disappointed cannot get it to run.

**Comment by rdwebdesign** [comment]
If you need help, ask on the [Pi-hole Discourse Forum](https://discourse.pi-hole.net/).
I'm sure there will be more people available there to try to help you find a solution to this problem.
