### ISSUE TITLE
PiHole Logs not displaying after update

### ISSUE THREAD

**Issue by commandermoon** [pi-hole/pi-hole#4946]
### Versions
- Pi-hole:  v5.12.2
- AdminLTE:  v5.15.1
- FTL:  v5.18.1

### Platform
- OS and version:  Raspbian (Debian 11) 5.10.103-v7l+
- Platform:  RaspberryPi

### Expected behavior

When browsing to `/admin/queries.php`  or `/admin/db_queries.php` query history should be visible.

### Actual behavior / bug

When browsing to `/admin/queries.php` or `/admin/db_queries.php` nothing is displayed.

### Steps to reproduce

1. Update pihole from previous version (unsure of initially installed version or when exactly it stopped working).
2. Browse to `/admin/db_queries.php` or `/admin/queries.php` and see no data.

## Debug Token

- URL:  https://tricorder.pi-hole.net/G05f9u2g/

### Screenshots

Query count and queries blocked display properly on main page:
![image](https://user-images.githubusercontent.com/46551775/192553056-01cb0b9d-b247-4461-9fe2-c53f240a3ece.png)

No data displayed on `/admin/queries.php`:
![image](https://user-images.githubusercontent.com/46551775/192553301-80655b4d-0105-4850-b68c-ff16bb6e74e1.png)

No data displayed on `/admin/db_queries.php`:
![image](https://user-images.githubusercontent.com/46551775/192553523-051fc002-f84e-4927-8655-f5de5ca492e9.png)

**Comment by yubiuser** [comment]
You've set 

```
   PRIVACYLEVEL=3
```

Which disables the query log and the long-term database.

https://docs.pi-hole.net/ftldns/privacylevels/#level-3-anonymous-mode-anonymize-everything
