### ISSUE TITLE
New install not working.

### ISSUE THREAD

**Issue by mocallins** [pi-hole/pi-hole#4948]
### Versions

  Current Pi-hole version is v5.12.2
  Current AdminLTE version is v5.15.1
  Current FTL version is v5.18.1

### Platform

- OS and version:  Ubunto 20.04

- Platform:  VM

### Expected behavior

A new fresh install following CraftComputing instructions from YouTube

### Actual behavior / bug

Cannot ping google.com from cli on the pihole server.
Also apt commands fail, not being able to reach packages

### Steps to reproduce

1. Fresh install

## Debug Token

- URL:  

[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, contact Pi-hole support for assistance.
    * Error message: curl: (6) Could not resolve host: tricorder.pi-hole.net

[✗] There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole/pihole_debug.log

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
Edit file /etc/resolv.conf, change the nameserver to a public DNS (Cloudflare, Quad9, etc.), save and exit.

Then generate a new debug log and post that token.

**Comment by mocallins** [comment]
/etc/resolv.conf

nameserver 1.1.1.1
options edns0 trust-ad


pihole -d
...
[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, contact Pi-hole support for assistance.
    * Error message: curl: (6) Could not resolve host: tricorder.pi-hole.net

[✗] There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole/pihole_debug.log

**Comment by mocallins** [comment]
[pi-hole]:</home/mike/> cat /var/log/pihole/pihole_debug.log
cat: /var/log/pihole/pihole_debug.log: Permission denied
[pi-hole]:</home/mike/> sudo cat /var/log/pihole/pihole_debug.log
This process collects information from your Pi-hole, and optionally uploads it to a unique and random directory on tricorder.pi-hole.net.

The intent of this script is to allow users to self-diagnose their installations.  This is accomplished by running tests against our software and providing the user with links to FAQ articles when a problem is detected.  Since we are a small team and Pi-hole has been growing steadily, it is our hope that this will help us spend more time on development.

NOTE: All log files auto-delete after 48 hours and ONLY the Pi-hole developers can access your data via the given token. We have taken these extra steps to secure your data and will work to further reduce any personal information gathered.

*** [ INITIALIZING ]
[i] 2022-09-28:20:58:16 debug log has been initialized.
[i] System has been running for 1 days, 13 hours, 53 minutes

*** [ INITIALIZING ] Sourcing setup variables
[i] Sourcing /etc/pihole/setupVars.conf...

*** [ DIAGNOSING ]: Core version
[i] Core: v5.12.2 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin     https://github.com/pi-hole/pi-hole.git (fetch)
             origin     https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.12.2-0-gd88629e

*** [ DIAGNOSING ]: Web version
[i] Web: v5.15.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin     https://github.com/pi-hole/AdminLTE.git (fetch)
             origin     https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.15.1-0-gb110ecc

*** [ DIAGNOSING ]: FTL version
[i] FTL: v5.18.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: 4c8abe6

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.55

*** [ DIAGNOSING ]: php version
[i] 7.4.3

*** [ DIAGNOSING ]: Operating system
[i] dig return code:  10
[i] dig response:  dig: couldn't get address for 'ns1.pi-hole.net': failure
[✗] Distro:  Ubuntu
[✗] Error: Ubuntu is not a supported distro (https://docs.pi-hole.net/main/prerequisites/)

*** [ DIAGNOSING ]: SELinux
[i] SELinux not detected

*** [ DIAGNOSING ]: FirewallD
[i] Firewalld service inactive

*** [ DIAGNOSING ]: Processor
[✓] x86_64

*** [ DIAGNOSING ]: Disk usage
   Filesystem      Size  Used Avail Use% Mounted on
   udev            1.9G     0  1.9G   0% /dev
   tmpfs           394M  1.3M  392M   1% /run
   /dev/sda2        40G  6.6G   31G  18% /
   tmpfs           2.0G  1.4M  2.0G   1% /dev/shm
   tmpfs           5.0M     0  5.0M   0% /run/lock
   tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
   /dev/loop1       56M   56M     0 100% /snap/core18/2128
   /dev/loop0       71M   71M     0 100% /snap/lxd/21029
   /dev/loop2       48M   48M     0 100% /snap/snapd/16778
   /dev/loop3       64M   64M     0 100% /snap/core20/1623
   tmpfs           394M     0  394M   0% /run/user/997
   tmpfs           394M     0  394M   0% /run/user/1000

*** [ DIAGNOSING ]: Network interfaces and addresses
   1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
       link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
       inet 127.0.0.1/8 scope host lo
          valid_lft forever preferred_lft forever
   2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
       link/ether 00:0c:29:de:6f:90 brd ff:ff:ff:ff:ff:ff
       inet 192.168.0.212/24 brd 192.168.0.255 scope global eth0
          valid_lft forever preferred_lft forever

*** [ DIAGNOSING ]: Network routing table
   default via 192.168.0.1 dev eth0 proto static
   192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.212

*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
    192.168.0.212/24

[✗] No IPv6 address(es) found on the eth0 interface.

[i] Default IPv4 gateway: 192.168.0.1
   * Pinging 192.168.0.1...
[✓] Gateway responded.

*** [ DIAGNOSING ]: Ports in use
    udp:0.0.0.0:36677 is in use by avahi-daemon
[✓] udp:0.0.0.0:53 is in use by pihole-FTL
    udp:127.0.0.1:5335 is in use by unbound
    udp:0.0.0.0:5353 is in use by avahi-daemon
    tcp:0.0.0.0:22 is in use by sshd
    tcp:127.0.0.1:5335 is in use by unbound
[✓] tcp:127.0.0.1:4711 is in use by pihole-FTL
[✓] tcp:0.0.0.0:80 is in use by lighttpd
[✓] tcp:0.0.0.0:53 is in use by pihole-FTL

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✗] Failed to resolve  on lo (127.0.0.1)
[✗] Failed to resolve  on eth0 (192.168.0.212)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] No IPv6 address available on lo
[✓] No IPv6 address available on eth0
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (2001:4860:4860::8888)

*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds

   * Received 303 bytes from eth0:192.168.0.1
     Offered IP address: 192.168.0.42
     Server IP address: 192.168.0.1
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      netmask: 255.255.255.0
         router: 192.168.0.1
      default-ttl: 64
      lease-time: 172800 ( 2d )
      server-identifier: 192.168.0.1
      renewal-time: 86400 ( 1d )
      rebinding-time: 151200 ( 1d 18h )
      dns-server: 68.105.28.11
      dns-server: 68.105.29.11
      dns-server: 68.105.28.12
      --- end of options ---

   DHCP packets received on interface lo: 0
   DHCP packets received on interface eth0: 1

*** [ DIAGNOSING ]: Pi-hole processes
[✓] lighttpd daemon is active
[✓] pihole-FTL daemon is active

*** [ DIAGNOSING ]: Pi-hole-FTL full status
   ● pihole-FTL.service - LSB: pihole-FTL daemon
     Loaded: loaded (/etc/init.d/pihole-FTL; generated)
     Active: active (exited) since Wed 2022-09-28 05:02:00 UTC; 15h ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 0 (limit: 4611)
     Memory: 0B
     CGroup: /system.slice/pihole-FTL.service

Sep 28 05:02:00 pi-hole systemd[1]: Starting LSB: pihole-FTL daemon...
Sep 28 05:02:00 pi-hole pihole-FTL[48352]: Not running
Sep 28 05:02:00 pi-hole su[48376]: (to pihole) root on none
Sep 28 05:02:00 pi-hole su[48376]: pam_unix(su:session): session opened for user pihole by (uid=0)
Sep 28 05:02:00 pi-hole pihole-FTL[48378]: FTL started!
Sep 28 05:02:00 pi-hole su[48376]: pam_unix(su:session): session closed for user pihole
Sep 28 05:02:00 pi-hole systemd[1]: Started LSB: pihole-FTL daemon.

*** [ DIAGNOSING ]: Setup variables
    PIHOLE_INTERFACE=eth0
    QUERY_LOGGING=true
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    LIGHTTPD_ENABLED=true
    CACHE_SIZE=10000
    DNS_FQDN_REQUIRED=true
    DNS_BOGUS_PRIV=true
    DNSMASQ_LISTENING=local
    BLOCKING_ENABLED=true
    DNSSEC=false
    REV_SERVER=true
    REV_SERVER_CIDR=192.168.0.0/24
    REV_SERVER_TARGET=192.168.0.1
    REV_SERVER_DOMAIN=
    PIHOLE_DNS_1=8.8.8.8

**Comment by dschaper** [comment]
>*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✗] Failed to resolve on lo (127.0.0.1)
[✗] Failed to resolve on eth0 (192.168.0.212)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)

You have something on your network or router that is preventing DNS queries to internal and internet DNS servers. 

This is a configuration issue and not a bug, because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.

**Comment by mocallins** [comment]
I don't understand what that means.
I followed the simple instructions andf it didn't work.
Nothing was said about having to check a configuration in my network.

**Comment by rdwebdesign** [comment]
> A new fresh install following CraftComputing instructions from YouTube

This is not a tutorial made by Pi-hole.

You have some config conflicts on your system.
You'll find more help on [Pi-hole Discourse Forum](https://discourse.pi-hole.net/).

As a free open-source project run by volunteers we have very limited resources.
Thank you for your understanding.

**Comment by jfb-pihole** [comment]
> Nothing was said about having to check a configuration in my network.

For starters, your DHCP server is passing out three IPs for DNS that are not Pi-hole.

```
dns-server: 68.105.28.11
dns-server: 68.105.29.11
dns-server: 68.105.28.12
```

As noted by others, please open a topic on discourse.pi-hole.net.
