### ISSUE TITLE
Unable to install pi-hole on Fedora 36

### ISSUE THREAD

**Issue by Poppygael0** [pi-hole/pi-hole#4951]
**Unable to install pi-hole on Fedora 36**

On the install options, (`curl -sSL https://install.pi-hole.net | bash` , Method 1 and Method 2 ) all show the same error message: 

```
----------------------------------------------------------------------
E: No se ha podido localizar el paquete grep
E: No se ha podido localizar el paquete dnsutils
```

*translated:*
```
----------------------------------------------------------------------
E: unable to locate package grep
E: unable to locate package dnsutils
```

but xgrep and `bind-utils` are both installed in the yum package manager.

### Platform

- OS and version:  Fedora 36

- `uname --all`:
  - 
```
uname --all         
Linux fedora 5.19.11-201.fsync.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 26 22:29:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected behavior

The installer should install pi-hole correctly.

### Actual behavior / bug

when running the install.pi-hole.net method or Method 1 or Method 2 the following error
message pops up and the installer exits with an error.

```
----------------------------------------------------------------------
E: No se ha podido localizar el paquete grep
E: No se ha podido localizar el paquete dnsutils
```

### Steps to reproduce

1. Install Fedora 36
2. try to install pi-hole with method 1, 2, or install.pi-hole.net

### Additional context

`apt-get install grep dns-utils` does not seem to work at all.

**Comment by jfb-pihole** [comment]
Fedora 36 is not supported.  The following OS's are supported by Pi-hole.
```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=34 CentOS=8 Rocky=8"
```

**Comment by yubiuser** [comment]
I just added the test suite for Fedora 35 and 36 which will be supported with the next Pi-hole release. The test all pass without issues, esp. there is no issue with the required packages. So your issue is likely with your device/configuration. Please open a help request on our discourse platform at https://discourse.pi-hole.net/
