### ISSUE TITLE
Default DHCP leasetime is set wrong (2 minutes instead of 24 hours)

### ISSUE THREAD

**Issue by PortStone** [pi-hole/pi-hole#4957]
This is a: **Bug**  

## Details

It says that the default lease time is equal to 24 hours. This is not true. It is set to 24 and therefore set to two minutes.

I guess it is because of [this](https://github.com/pi-hole/pi-hole/blob/f998eee4675c92819bde40f338fefe8feb7ba3b4/advanced/Scripts/webpage.sh#L395). My guess is that it never reaches the else branch with the value of `""` but with the value of `24` it does. As you can see it still uses the same variable which contains `24` instead of `24h`.

I had a fresh Pi-Hole installed with version `pihole/pihole:2022.09.4` and it just sets 24 instead of 24h. 

If I set the `DHCP_LEASETIME` to `24` it will actually write `24h`.

In `02-pihole-dhcp.conf` without `DHCP_LEASETIME` set
dhcp-range=192.168.178.20,192.168.178.200,`24`

after I set the `DHCP_LEASETIME`
dhcp-range=192.168.178.20,192.168.178.200,`24h`

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu Server 22.04 LTS** 
  * Hardware: Raspbery Pi 4B
  * Kernel Architecture: aarch64 
  * Docker Install Info and version: 
    - Software source: apt package manager
    - Supplimentary Software: docker-compose
  * Hardware architecture: aarch64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
Transferred to main Pi-hole repo as that is where the bug is

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/pull/1646

**Comment by dschaper** [comment]
That PR specifically makes the variable `24` instead of `24h`.

**Comment by dschaper** [comment]
What exactly are you setting for the docker environment variables?

**Comment by PortStone** [comment]
> What exactly are you setting for the docker environment variables?

``` yml
    environment:
      - "TZ=Europe/Berlin"
      - "WEBPASSWORD=pw"
      - "DNSMASQ_LISTENING=all"
      - "VIRTUAL_HOST=pi-hole.pi.lan"
      - "FTLCONF_LOCAL_IPV4=192.168.178.2"
      - "FTLCONF_LOCAL_IPV6=2a02:8070:4281:5b40:dea6:32ff:fe99:c3d3"
      - "PIHOLE_DNS=172.16.0.50;2001:8a2e:ffff:ffff:5ba2:ffff:ffff:ffff"
      - "DHCP_ACTIVE=true"
      - "DHCP_rapid_commit=true"
      - "DHCP_IPv6=true"
      - "DHCP_START=192.168.178.20"
      - "DHCP_END=192.168.178.200"
      - "DHCP_ROUTER=192.168.178.1"
      - "DHCP_LEASETIME=24"
```

**Comment by yubiuser** [comment]
Should be fixed with https://github.com/pi-hole/pi-hole/releases/tag/v5.13
