### ISSUE TITLE
Avoid localhost request in stats?

### ISSUE THREAD

**Issue by xoniq** [pi-hole/pi-hole#496]
Is it possible to ignore requests coming from localhost (127.0.0.1)?
My server running pi-hole does lots of trafficking by itself, these are 80% of the traffic handled by the server, so the statistics are quite useless right now. (0,2% of today's traffic is ads)

**Comment by Mcat12** [comment]
This is something we will look into.

**Comment by crxdelsol** [comment]
Thanks. Perhaps I can solve it by myself for the time being by alter the source from the dashboard to ignore localhost results when collecting the data.

**Comment by Mcat12** [comment]
You'll probably have to edit some functions below [this line](https://github.com/pi-hole/AdminLTE/blob/master/data.php#L258).

**Comment by crxdelsol** [comment]
I have it solved a bit before (so it's a bit more at the beginning of parsing the data:

Modified:
```
function readInLog() {
    global $log;
    return count($log) > 1 ? $log :
        file("/var/log/pihole.log");
}
```
Into:
```
function readInLog() {
    global $log;
    $logData = count($log) > 1 ? $log :
        file("/var/log/pihole.log");
    // Avoid localhost entries to appear in the statistics
    return array_filter($logData, "avoidLocalhostEntries");
}
```
And added:
```
function avoidLocalhostEntries($var) {
    return (strpos($var, "127.0.0.1") === false);
}
```

Quick fix purely for display and calculations, but it gets the job done in a clean way.

**Comment by Mcat12** [comment]
That seems like an easier fix that what I was thinking. :) Perhaps we'll add a config section to the web interface with stuff like this.

**Comment by crxdelsol** [comment]
To sketch out an example of how my situation have changed (and why this was really needed  for me:

Old situation:
[https://dl.dropboxusercontent.com/u/7528392/pihole-old.png](https://dl.dropboxusercontent.com/u/7528392/pihole-old.png)

Current situation:
[https://dl.dropboxusercontent.com/u/7528392/pihole-new.png](https://dl.dropboxusercontent.com/u/7528392/pihole-new.png)

Would be a nice addition to add my solution to a config section indeed, where you can add your own keywords to disable on both domain and hostname and whatever others want. That would be a more generic solution.

Then you can tell people to separate keywords by comma or something, and in the code convert the comma to pipe "|" to do something like this:

```
function avoidLocalhostEntries($var, $filter = '127.0.0.1,    apple.com, whatever') {
    // Explode filters on comma
    $filters = explode(',', $filter);
    // Trim whitespace around filter sections
    $filters = array_map('trim', $filters);
    // Put back together pipe-separated
    $filters_str = implode('|', $filters);
    // Avoid matching any filter sections
    return (preg_match('/(' . $filters_str . ')/', $var) == false);
}
```

In that case you only need to define a single line of comma separated values with or without whitespace, I clean it up in my example. (Example above is working fine, currently using it :-P)

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #147](https://github.com/pi-hole/AdminLTE/issues/147) via [**ZenHub**](https://www.zenhub.com/)
