### ISSUE TITLE
[Tracking] workflow sync-dev-back-to-master did not trigger

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#4971]
See https://github.com/pi-hole/pi-hole/pull/4970

**Comment by PromoFaux** [comment]
Ah, helps if I RTFL

![image](https://user-images.githubusercontent.com/1998970/195990770-5c08be99-9f1c-4a36-a1be-e20223d6030c.png)


https://github.com/pi-hole/pi-hole/pull/4818

It was originally targeted at `master`.

**Comment by PromoFaux** [comment]
#4818 now merged

**Comment by yubiuser** [comment]
But.... this was `master` from a fork!

We still need our latest `master` to be merged into `development`!

**Comment by PromoFaux** [comment]
![image](https://user-images.githubusercontent.com/1998970/195991635-bf2c3e8c-7bbf-4fcc-ac6b-28e96653e69b.png)

Do we?

**Comment by PromoFaux** [comment]
Let me try something...

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/pull/4981
