### ISSUE TITLE
After running pihole -up, PiHole won't start - pihole restartdns fails

### ISSUE THREAD

**Issue by rayheffer** [pi-hole/pi-hole#4978]
After running pihole -up, it fails to start.

1. I had to add a nameserver entry to `/etc/resolve.conf` since it was unable to resolve github.com.
2. `sudo PIHOLE_SKIP_OS_CHECK=true pihole -r` -  pihole-FTL service still won't start

```
pihole status
  [✗] DNS service is NOT running
  [✗] DNS service is NOT running
```
3. sudo pihole restartdns results:
```
[✗] Job for pihole-FTL.service failed because the control process exited with error code.
```

### Versions

```
Pi-hole version is v5.13 (Latest: v5.13)
AdminLTE version is v5.16 (Latest: v5.16)
pihole-FTL: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
pihole-FTL: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
Latest FTL version is v5.18.2
```

### Platform
- OS and version:  Raspbian 9
- Platform:  Raspberry Pi 

### Expected behavior
Pihole should update and restart the service

### Actual behavior / bug
PiHole is unable to start

## Debug Token
- URL:  https://tricorder.pi-hole.net/RdmYwnPF/

## Screenshot
![image](https://user-images.githubusercontent.com/6196087/195911618-db3b5a27-6997-49ba-a7b5-eb719f387f38.png)

**Comment by yubiuser** [comment]
As it says

```
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  0
[i] dig response:  "Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=35,36 CentOS=8 Rocky=8"
[✓] Distro:  Raspbian
[✗] Version: 9
[✗] Error: Raspbian is supported but version 9 is currently unsupported (https://docs.pi-hole.net/main/prerequisites/)
```

Stretch is not supported anymore. It's hard incompatible with current Pi-hole. See

https://discourse.pi-hole.net/t/bye-bye-debian-stretch-looking-for-testers/56844

**Comment by rdwebdesign** [comment]
You are using an unsupported OS:
```
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  0
[i] dig response:  "Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=35,36 CentOS=8 Rocky=8"
[✓] Distro:  Raspbian
[✗] Version: 9
[✗] Error: Raspbian is supported but version 9 is currently unsupported (https://docs.pi-hole.net/main/prerequisites/)
```

Debian 9 cannot execute the current FTL version because it don't have support for `GLIBC_2.28`.
```
Oct 14 17:49:28 raspberrypi pihole-FTL[18216]: /usr/bin/pihole-FTL: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/bin/pihole-FTL)
```

**Comment by yubiuser** [comment]
The right way is to upgrade your OS.

**Comment by rayheffer** [comment]
I cannot due to a dependency with other software, it's also a remote device that I don't physically have access to.  I wish `pihole -up` had showed a warning that it will break due to an unsupported OS. My fault for not checking first, but this would have been a nice catch.

**Comment by rdwebdesign** [comment]
You can try to run Pi-hole in a docker container.

**Comment by yubiuser** [comment]
The update checks if the OS is supports, but you skipped the check with `PIHOLE_SKIP_OS_CHECK=true`

**Comment by yubiuser** [comment]
You can revert the FTL component to get DNS resolution back, but using out of sync components can lead to all sort of issues 

`pihole checkout FTL v5.16`

**Comment by rayheffer** [comment]
> You can revert the FTL component to get DNS resolution back, but using out of sync components can lead to all sort of issues

Thanks.

**Comment by PhilipLoewen** [comment]
I had this problem and followed the steps endorsed in the following post to resolve it:
[https://github.com/pi-hole/FTL/issues/1420#issuecomment-1236180827](url)
(This saved me re-installing a whole new Armbian OS on the headless little OrangePI board in the basement running pi-hole.)

This simple fix impressed me so much with the design of the project that I followed up by making a modest donation. Also, browsing for a little while with pi-hole broken reminded me how much I appreciate the service. Big thanks to the developers.

**Comment by dschaper** [comment]
Thanks!
