### ISSUE TITLE
UI says update available, pihole -up returns that everything is up to date

### ISSUE THREAD

**Issue by rayheffer** [pi-hole/pi-hole#4982]
### Versions
```
Pi-hole version is v5.13 (Latest: v5.13)
AdminLTE version is v5.16 (Latest: v5.16)
FTL version is v5.18.2 (Latest: v5.18.2)
```
### Platform
- OS and version:  Raspbian 10 Buster

### Expected behavior
The UI should be showing the versions as seen in `pihole -v`

### Actual behavior / bug
The UI shows vDev as the Pi-hole and web interface version. FTL says an update is available, but it's on the latest (5.18.2)
`pihole -up` shows everything is up to date

## Debug Token
- URL:  https://tricorder.pi-hole.net/eYiRYpCH/

### Screenshots
![image](https://user-images.githubusercontent.com/6196087/195992652-2261d230-89a9-4b8b-bd96-5fa14a9058fc.png)

### Additional context
Raspbian was upgraded from Stretch to Buster to solve the issue [4978](https://github.com/pi-hole/pi-hole/issues/4978)

**Comment by yubiuser** [comment]
What is the output of `pihole-FTL -v` and `cat /etc/pihole/versions`?

**Comment by rayheffer** [comment]
`pihole-FTL -v`
```
v5.18.2
```

`cat /etc/pihole/versions`
```
GITHUB_CORE_VERSION=v5.13
GITHUB_WEB_VERSION=v5.16
GITHUB_FTL_VERSION=v5.18.2
```

**Comment by yubiuser** [comment]
Is this the whole output of `cat /etc/pihole/versions`?

**Comment by rayheffer** [comment]
> Is this the whole output of cat /etc/pihole/versions?
Yes, that's it.

**Comment by rdwebdesign** [comment]
First of all:
don't worry. Your system is up to date. This is just a cosmetic issue.


This file should have more info... this is the first clue we get.
We are currently investigating why (in very few cases) this difference happens.

**Comment by rayheffer** [comment]
Ok thanks, no biggie. I wonder if this was related to trying to upgrade while on Stretch, then upgrading to Buster.

**Comment by rdwebdesign** [comment]
You can fix the footer info running `pihole updatechecker` on the command line.

**Comment by Woutoud** [comment]
I've got the same issue, but the command from te post above doesn't fix it. 

`cat /etc/pihole/versions`

Gives the following:
```
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.13-0-g17779ba
WEB_VERSION=v5.16-0-gc2afe42
FTL_VERSION=v5.18.2
GITHUB_CORE_VERSION=v5.13
GITHUB_WEB_VERSION=v5.16
GITHUB_FTL_VERSION=v5.18.2
```

**Comment by rdwebdesign** [comment]
@Woutoud 

What is the output of `pihole -v` on the command line?
What versions do you see on the Web Interface?

**Comment by Woutoud** [comment]
`pihole -v` gives:
```
Pi-hole version is v5.13 (Latest: v5.13)
AdminLTE version is v5.16 (Latest: v5.16)
FTL version is v5.18.2 (Latest: v5.18.2)
```

Web Interface:
```
Pi-hole [v5.12.2]
FTL [v5.18.1]
Web Interface [v5.15.1]
```

**Comment by infinitytec** [comment]
I am seeing this issue as well. v5.14.1
pihole -updatechecker did not resolve the issue for me either.

**Comment by rdwebdesign** [comment]
The command is `pihole updatechecker` (no dash).

**Comment by infinitytec** [comment]
> The command is `pihole updatechecker` (no dash).

That didn't seem to do it...

**Comment by botchedcode** [comment]
Same Problem here. Pihole says....

![image](https://user-images.githubusercontent.com/108232177/204153761-22971207-0a2b-4a88-b2be-5cb2a95f1fb7.png)

...but when clicking the update link, it refers to the github page for version 5.14.1 - but I have 5.14.1 installed:

`  Pi-hole version is v5.14.1 (Latest: v5.14.1)AdminLTE version is v5.17 (Latest: v5.17)

FTL version is v5.19.2 (Latest: v5.19.2)`

This...

`pihole updatechecker` / `pihole -up`

...does not fix it.

**Comment by slopsjon** [comment]
I have the same problem, tried the above. Running on Raspberry bullseye.

**Comment by dschaper** [comment]
Debug tokens are needed for us to take a look.

**Comment by infinitytec** [comment]
> Debug tokens are needed for us to take a look.
https://tricorder.pi-hole.net/8CHOzfzj/

**Comment by yubiuser** [comment]
This is actually interesting

```
*** [ DIAGNOSING ]: Core version
[✓] Version: v5.14.2
[i] Remotes: origin	https://github.com/pi-hole/pi-hole.git (fetch)
             origin	https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.14.2-0-g0034538

-rw-r--r-- 1 root root 645 Dec 24 18:49 /etc/pihole/versions
   CORE_VERSION=v5.14.1
   CORE_BRANCH=master
   CORE_HASH=00345387
   GITHUB_CORE_VERSION=v5.14.2
   GITHUB_CORE_HASH=8d2e023e
```

You are running the latest version `v5.14.2` but `pihole updatecheker` did not update the file accordingly. Please try to remove the file and run the updatechecker again.

**Comment by slopsjon** [comment]
Deleted the version file and ran pihole updatechecker and it's displaying the version number now. Thanks.

**Comment by BoscaBeag** [comment]
I am having a similar (cosmetic) issue.  Suspect it will correct when pihole core is next updated.  It is possible I ran a one-off command mentioned in an earlier issue when the update checking first started reporting incorrectly a month or two ago.

After updating
```
AdminLTE version is v5.18 (Latest: v5.18) from 5.17.2
FTL version is v5.20 (Latest: v5.20) from 5.19.2
PADD version is 3.9.0 (Latest: v3.9.0) from 3.8.1
No upgrade of Pi-hole version is v5.14.2 (Latest: v5.14.2)
```

PADD reports 
`Pi-hole® v5.14.2, Web v5.18, FTL v5.20, PADD v3.9.0`
with the Pi-hole version colored red, and `[i] Updates are available`

existing version of /etc/pihole/versions was
```
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.2
WEB_VERSION=v5.18
FTL_VERSION=v5.20
GITHUB_CORE_VERSION=v5.14.2
GITHUB_WEB_VERSION=v5.18
GITHUB_FTL_VERSION=v5.20
CORE_HASH=00345387
GITHUB_CORE_HASH=8d2e023e
WEB_HASH=ad2d4386
GITHUB_WEB_HASH=ad2d4386
FTL_HASH=cba74934
GITHUB_FTL_HASH=cba74934
```

after removing /etc/pihole/versions and running `pihole updatechecker`, the new versions file
```
CORE_VERSION=v5.14.2
CORE_BRANCH=master
CORE_HASH=00345387
GITHUB_CORE_VERSION=v5.14.2
GITHUB_CORE_HASH=8d2e023e
WEB_VERSION=v5.18
WEB_BRANCH=master
WEB_HASH=ad2d4386
GITHUB_WEB_VERSION=v5.18
GITHUB_WEB_HASH=ad2d4386
FTL_VERSION=v5.20
FTL_BRANCH=master
FTL_HASH=cba74934
GITHUB_FTL_VERSION=v5.20
GITHUB_FTL_HASH=cba74934
```

Please note in both that the local hash for CORE is **"00345387"** (same as @infinitytec) compared to the GITHUB_CORE_HASH of **"8d2e023e"**

**Comment by RawandKurdy** [comment]
core pkg not getting updated correctly, even after "pihole updatecheker".

**Comment by rdwebdesign** [comment]
@RawandKurdy
Please, can you open a new issue with a debug token?

**Comment by infinitytec** [comment]
I still had this issue after updating to 5.15.2 on one of my systems (the other never had the problem). Removed `/etc/pihole/versions` and ran `pihole updatechecker` again. Everything looks good now. Thanks!

**Comment by RawandKurdy** [comment]
> @RawandKurdy
> Please, can you open a new issue with a debug token?

@infinitytec solution + an update fixed the issue for me

**Comment by dreaddymck** [comment]
> You can fix the footer info running `pihole updatechecker` on the command line.

This fixed my issue. Running on android
