### ISSUE TITLE
Change X-XSS-Protection "1; block" -> "0" lighttpd.conf

### ISSUE THREAD

**Issue by ho4ho** [pi-hole/pi-hole#4983]
Minor updation suggest #4862:

### Versions
Not relevant

### Platform
Not relevant

### Expected behavior

lighttpd.conf having `X-XSS-Protection "0"` header

### Actual behavior / bug

lighttpd.conf having `X-XSS-Protection "1; block"` header

### Steps to reproduce

Not relevant

### Additional context

https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-602663932:

> I've been studying this issue for a while and it's *dangerous* to set this header. It makes sites that are not vulnerable to XSS, vulnerable.
> ...
> Developers need to either remove the header or set it to zero, I think the debate is over. There is NO good reason to set this header to blocking mode.

Seen suggest remove vs. "0" by https://github.com/helmetjs/helmet/issues/230#issuecomment-614106165:

> The recommendation as a security community is to have a default value of 0 so that browsers don't set their own defaults.

and by https://owasp.org/www-project-secure-headers/#x-xss-protection:

> Warning: The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side. As such, it is recommended to set the header as X-XSS-Protection: 0 in order to disable the XSS Auditor, and not allow it to take the default behavior of the browser handling the response. Please use Content-Security-Policy instead.

Others also following suggest: owncloud/core/pull/38305, spring-projects/spring-security/issues/9631, OWASP/www-project-secure-headers/issues/7

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.15
