### ISSUE TITLE
Can't import settings in Firefox

### ISSUE THREAD

**Issue by markfaine** [pi-hole/pi-hole#4992]
Firefox 106.0 (64-bit)
Ubuntu 22.10

Tar file does not upload when trying to import settings.  I had to install Chrome to get settings to import from UI.

**Comment by rdwebdesign** [comment]
I can't replicate the issue.
I just tested and Firefox was able to upload the file as expected.

**Comment by jfb-pihole** [comment]
Is the problem that you cannot save the file from Firefox?  Or, is the file successfully exported and see it on your drive  in tar.gz format?  Example:

`pi-hole-nanopi-teleporter_2022-10-27_21-02-57.tar.gz`

**Comment by rdwebdesign** [comment]
Do you see any error messages?

**Comment by markfaine** [comment]
No errors, it doesn't even get populated in the file upload box.  You select the file and literally nothing happens except for the dialog box closing.

**Comment by rdwebdesign** [comment]
1. Did you use Firefox when you created the file?
2. Does the saved file show the correct extension `tar.gz` on Nautilus (or whatever file manager you use)?
3. Are you able to open the file and see its contents (usually a double click will open the file)?

**Comment by markfaine** [comment]
1. Yes,
2.  Yes, it is a tar.gz file and I can inspect it and see that it does contain data.  I was even able to use it to restore the settings once I installed Chrome and used Chrome to import it.  
3.  Yes, I was able to look at the contents in Ubuntu's archive manager

The issue is browser support, not something wrong with the file.   It works fine in Chrome but not in Firefox
