### ISSUE TITLE
Domain blocked but still playing on SmartTV

### ISSUE THREAD

**Issue by orugari** [pi-hole/pi-hole#4994]
### Versions

- Pi-hole:  5.13
- AdminLTE:  5.16
- FTL:  5.18.2

### Platform

- OS and version:  Raspbian

- Platform:  Raspberry Pi 3B+

### Expected behavior

Block ads on SmartTV (app Youtube) and directly play the video

### Actual behavior / bug

Play the Ads

### Steps to reproduce

Configured the DHCP
Pi-Hole detect and block the Domain tpc.googlesyndication.com from the TV, showed in the Query Log
See error

## Debug Token

- URL:  

[✓] Your debug token is:  https://tricorder.pi-hole.net/TKbd0Fcu/

### Screenshots
![Sans titre](https://user-images.githubusercontent.com/4814790/198828594-0f3f8df7-704c-42f1-b367-d370af3fb65b.png)

**Comment by yubiuser** [comment]
Please run from a client

`nslookup tpc.googlesyndication.com`

**Comment by orugari** [comment]
Serveur :   one.one.one.one
Address:  1.1.1.1

Réponse ne faisant pas autorité :
Nom :    tpc.googlesyndication.com
Addresses:  2a00:1450:4006:80d::2001
          142.250.200.225

**Comment by yubiuser** [comment]
This client is not using Pi-hole but 1.1.1.1 for DNS resolution.

Please use our [discourse forum](https://discourse.pi-hole.net/c/bugs-problems-issues/11) for help regarding configuration issues.

**Comment by jfb-pihole** [comment]
> Serveur : one.one.one.one

This client is not using Pi-hole for DNS. 

> Expected behavior

> Block ads on SmartTV (app Youtube)

You will not reliably block YouTube ads with Pi-hole. The ads are served from the same domains as the content.
