### ISSUE TITLE
Automatic forward from / to /admin

### ISSUE THREAD

**Issue by doebi** [pi-hole/pi-hole#4996]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to '<your-pi-hole-adress>:port/'
2. Click on '--'
3. Scroll down to '--'

It is useless to have the user click this link each and every time. Just do an automatic forward, unless otherwise configured please.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
We close so issues where the template is ignored and so little information is provided as you did
