### ISSUE TITLE
Add Support for Black-/White-/Adlist auditing

### ISSUE THREAD

**Issue by 5olu7ion** [pi-hole/pi-hole#5003]
I recently reviewed my pihole instance (after years of troublefree usage), and I had a hard time, figuring out if my adlists, blacklists and whitelists are still in use (hosts, local devices and their dns requests, adservers, ... are changing over time).
There's one tool in the wild, that helped a lot: https://github.com/yubiuser/pihole_adlist_tool
Is it possible, to include something like this natively in pihole? It would be awesome, to have a hitcount for every entry in the black-/whitelist section (also for regex), and in the adlist section. The timespan, which relates to the hitcount could then be freely customizable. It would be also ok, to have a seperate page (maybe in the tools section), where I can get the hitcounts, I image, that it will be very resource intensive, to get the numbers. 
One hint: I didn't find any tool for whitelist checks, but I think it is desperately needed. 

Thank you for consideration!

**Comment by jfb-pihole** [comment]
Feature requests are entered in our discourse forum.

Please head to https://discourse.pi-hole.net

**Comment by 5olu7ion** [comment]
Added: https://discourse.pi-hole.net/t/add-audit-support-for-black-white-adlists/59031
