### ISSUE TITLE
Device domains incorrect even though nothing set in Local DNS

### ISSUE THREAD

**Issue by xTobyPlayZ** [pi-hole/pi-hole#5004]
### Versions
- Pi-hole:  v5.13
- AdminLTE:  v5.16
- FTL:  v5.18.2

### Platform
- OS and version:  Debian 11
- Platform:  Raspberry Pi Zero 2 W

### Expected behavior
Devices should show their IP address instead of a domain which was never assigned to it

### Actual behavior / bug
Devices show wire.guard as their domain even though it was never assigned to them.

### Steps to reproduce

1. Set a devices domain under Local DNS > DNS Records
2. Delete the devices domain under Local DNS > DNS Records
3. The device that had the domain should no longer have that as its domain
4. Watch as multiple other devices for some reason show up as having that domain, which was never set to them

## Debug Token
- URL:  https://tricorder.pi-hole.net/xh7MstTR

### Screenshots

![Nothing set here](https://user-images.githubusercontent.com/40534430/200203287-2ee423a5-e678-40c1-b7c6-d7adb0dfbd68.PNG)
![Same domains](https://user-images.githubusercontent.com/40534430/200203298-65bde3b2-1fc0-4023-8a37-7799bfd10835.PNG)

### Additional context

I tried updating Pi-hole, restarting Pi-hole, deleting the devices from the network then rejoining them, re-adding then deleting the local DNS Record. Nothing worked. No devices on my network have that as their hostname. I'm just trying to get rid of the domain so I can see their IP address, not trying to set up local DNS or whatever. I also tried looking at some files in /etc. to see if wire.guard was mentioned but nothing. Must be a weird bug.

**Comment by rdwebdesign** [comment]
Pi-hole doesn't create hostnames. 

This name was set somewhere else (on the device itself, on the router, etc.).

**Comment by xTobyPlayZ** [comment]
Well there's nothing set in the router, and I know for a fact that these devices don't have that as their hostname. One is a smart TV dongle.

**Comment by xTobyPlayZ** [comment]
Like if I try pinging wire.guard or wire.guard/ I get no response, but if I ping the actual IP I do, so I know for a fact that those devices don't have that hostname.

**Comment by rdwebdesign** [comment]
I don't use wireguard, but maybe the hostname was set there.

**Comment by xTobyPlayZ** [comment]
Nothing running WireGuard is even on the network anymore.
Also WTF is happening here, multiple devices 1 MAC address
![Bug](https://user-images.githubusercontent.com/40534430/200204546-3956a3a7-c936-4446-94d0-e4e8a656f4a9.png)

**Comment by xTobyPlayZ** [comment]
The devices in my router show up with their normal hostnames as well.

**Comment by rdwebdesign** [comment]
Hmmmm...

I think you are seen the value for those IPs retrieved from the database. 

Pi-hole tries to identify the hostname (if none is given) using the clients table.

**Comment by rdwebdesign** [comment]
This was changed a while back, per users request.
I think someone else might know more details.

**Comment by rdwebdesign** [comment]
If you don't care about your Long-term database, you can try to rename or delete `/etc/pihole/pihole-FTL.db`.

This will remove all past data and you will only see new hostnames (if provided) or IPs.

**Comment by xTobyPlayZ** [comment]
And how do I stop this from happening again if I do delete that file?

**Comment by yubiuser** [comment]
Try Settings/Flush network table

**Comment by xTobyPlayZ** [comment]
Doing this + a reboot fixed the issue! Thanks!
