### ISSUE TITLE
IPV6 using IPV4 DNS server (in logs)

### ISSUE THREAD

**Issue by Sassafras76** [pi-hole/pi-hole#5005]
### Versions
  Pi-hole version is v5.13 (Latest: v5.13)
  AdminLTE version is v5.16 (Latest: v5.16)
  FTL version is v5.18.2 (Latest: v5.18.2)
 

### Platform
- rasperpy pi os   

- Platform:  Raspberry Pi

### Expected behavior

DNS query should resolve with upstream Cloudflare servers in under 100ms

### Actual behavior / bug

I noticed that a DNS lookup is taking 5 second to resolve and when I do it manually its 15ms

### Steps to reproduce

I run a custom query:

sqlite3 /etc/pihole/pihole-FTL.db "SELECT domain, reply_time from queries where reply_time >= 0.100 order by reply_time desc LIMIT 3"

i identify the culprit, portal.fb.com

![image](https://user-images.githubusercontent.com/89309860/200387691-a2c6d7d5-5a66-4157-aff9-8aaf8f21a568.png)

I then query for that domain, portal.fb.com

 sqlite3 /etc/pihole/pihole-FTL.db "SELECT *  from queries where domain = 'portal.fb.com'"

i get this:

![image](https://user-images.githubusercontent.com/89309860/200387851-e3549b64-d3ca-4f3f-a435-cab403a308e3.png)

3050|1667844796|1|12|portal.fb.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|5.0482|0
3051|1667844796|2|12|portal.fb.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|5.0493|0
3115|1667844801|1|2|portal.fb.com|10.0.0.9|1.0.0.1#53||0||0
3116|1667844801|2|2|portal.fb.com|10.0.0.9|1.0.0.1#53||0||0

why is the IPV6 ULA address (also the same behavior for GUA address) using the IPV4 Cloudflare server?

**|fd00::2d01:3786:a433:bbce|1.0.0.1#53**

another example:

pi@pihole64:~ $ sqlite3 /etc/pihole/pihole-FTL.db "SELECT *  from queries where domain = 'edge-mqtt.facebook.com'"
3054|1667844796|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|0.0219|0
3055|1667844796|1|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|0.0247|0
**3123|1667844806|1|12|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|5.0471|0**
3164|1667844811|1|2|edge-mqtt.facebook.com|10.0.0.9|1.0.0.1#53||0||0
4962|1667845367|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.1.1.1#53||3|0.0471|0
4963|1667845367|1|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.1.1.1#53||3|0.0589|0
5433|1667845500|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|2606:4700:4700::1001#53||3|0.0217|0
5434|1667845500|1|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|2606:4700:4700::1001#53||3|0.0221|0
7268|1667845972|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|2606:4700:4700::1001#53||3|0.0206|0
7269|1667845972|1|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|2606:4700:4700::1001#53||3|0.0197|0
7634|1667846157|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|0.0249|0
7635|1667846157|1|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|0.0198|0
7714|1667846177|2|2|edge-mqtt.facebook.com|fd00::2d01:3786:a433:bbce|1.0.0.1#53||3|0.0223|0

## Debug Token

- URL:   https://tricorder.pi-hole.net/0EdR940k/

## Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Sassafras76** [comment]
oh so I ay be able to remove the IPV6 Cloudflare servers and test.

thank you :)

**Comment by yubiuser** [comment]
I guess so. Pi-hole will repeatedly test which upstream is the "fastest" and use this one until another one is faster.

https://docs.pi-hole.net/ftldns/dns-resolver/#improve-detection-algorithm-for-determining-the-best-forward-destination

**Comment by Sassafras76** [comment]
closing issue as its not a bug, clarified with feedback above.

**Comment by Sassafras76** [comment]
closing issue as its not a bug, clarified with feedback above.
