### ISSUE TITLE
GRAVITY - Error: in prepare, no such table: main.gravity

### ISSUE THREAD

**Issue by thomasbruchet** [pi-hole/pi-hole#5006]
### Versions
- Pi-hole:  v5.13
- AdminLTE:  v5.16
- FTL:  v5.18.2

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi

### Expected behavior

When I Update Gravity I've this error message:
```
  [i] Creating new gravity databases...
  [✗] Unable to copy data from /etc/pihole/gravity.db to /etc/pihole/gravity.db_temp
  Parse error near line 29: no such table: main.domainlist
Parse error near line 34: no such table: main.client
Parse error near line 39: no such table: main.adlist
  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity.db_temp
  Error: in prepare, no such table: main.gravity
   [✗] Unable to create database. Please contact support.
```

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to 'Tools'
2. Click on 'Update Gravity'
3. Click on 'Update'
4. Wait untill the end of process

## Debug Token

- URL:  https://tricorder.pi-hole.net/xFByijFU/

### Screenshots
https://i.imgur.com/qhPBQb7.png

**Comment by thomasbruchet** [comment]
I read that a some people have had to use: "pihole -g -r " but talk about new install or reinstall from scratch. 
Can you tell me more about reconfigure (*-r) Reconfigure or Repair Pi-hole subsystems ? 
Will I loose all config ? the pihole is my DHCP server.

**Comment by rdwebdesign** [comment]
Executing `pihole -r` and selecting the option "Repair" won't change your config.
Executing `pihole -r` and selecting the option "Reconfigure" will create a new config.

You can always create a backup of your config using the "Teleporter" tool (via web interface) or `pihole -a -t`.

**Comment by thomasbruchet** [comment]
That worked, thank you . 
```
[✓] Creating new gravity databases
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 3099260 (836088 unique domains)
  [i] Number of exact blacklisted domains: 11
  [i] Number of regex blacklist filters: 14
  [i] Number of exact whitelisted domains: 19
  [i] Number of regex whitelist filters: 13
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

  [i] The install log is located at: /etc/pihole/install.log
  [✓] Update complete!

  Current Pi-hole version is v5.13
  Current AdminLTE version is v5.16
  Current FTL version is v5.18.2

```
