### ISSUE TITLE
Regex not supported in adlists but not considered as invalid

### ISSUE THREAD

**Issue by jankytay** [pi-hole/pi-hole#5008]
**Versions**

- Pi-hole: v5.13
- AdminLTE: v5.16
- FTL: v5.18.2

Gravity update only complains about some RegEx domains in adlists as invalid.
For example:
`*.example.com` will show up in "Sample of invalid domains"
But `(^|\.)example\.com` won't. It'll just be discarded silently.

Also I'd suggest making it clear in [RegEx blocking documentation](https://docs.pi-hole.net/regex/overview/) that RegEx syntax is not supported in Adlists.

**Comment by dschaper** [comment]
Can you provide any information like a list that shows you these errors?

**Comment by yubiuser** [comment]
I can change the code to something like this

```
  [i] Target: https://raw.githubusercontent.com/jankytay/pihole-troubleshooting/master/issue5008.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 8 domains, 5 domains invalid!
      Sample of invalid domains:
      - *.example3.com
      - (^|\.)example5\.com
      - (\.|^)example6\.com$
      - ^example77?
      - (^|\.)example8\.com;reply=none
```

**Comment by 1332mm** [comment]
SXP

**Comment by 1332mm** [comment]
M👁Ⓜ️

**Comment by 1332mm** [comment]
- [ ] - 😂🤣😆😁😄🙃🤣😂🇹🇷🇺🇳🙏🤲🇺🇸🇬🇧🇦🇪🍼🌶🫑🪆👩‍🦳👨‍🦳👩‍🦲🅱️👨‍👩‍👧👨‍👩‍👧‍👧🧑‍🌾🏅☺️🌄🎉☢️⭕️🟤🌀🥹👁Ⓜ️🇹🇷🇺🇳🇹🇨🧠💁🏾⏱🤑🧨👺💵😈💰👹👹😂🥹💀🍷🍷🍷🤬🎃😾para yoksa işaret****_![image](https://user-images.githubusercontent.com/110432476/201821924-2fa5e8f3-d404-4976-93d1-79bf324b2178.jpeg)_****** 🙅

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.15
