### ISSUE TITLE
pihole -v show updated versions w/ master / git commit

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/pi-hole#5015]
### Versions

  Pi-hole version is master v5.14-0-g3c86af0e (Latest: v5.14)
  AdminLTE version is master v5.17-0-gda2764e5 (Latest: v5.17)
  FTL version is master v5.19 (Latest: v5.19)

### Platform
- OS and version:  Raspberry OS 11
- Platform:  Raspberry Pi

### Expected behavior

  Pi-hole version is v5.14 (Latest: v5.14)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19 (Latest: v5.19)

### Actual behavior / bug

  Pi-hole version is master v5.14-0-g3c86af0e (Latest: v5.14)
  AdminLTE version is master v5.17-0-gda2764e5 (Latest: v5.17)
  FTL version is master v5.19 (Latest: v5.19)

### Steps to reproduce

1. pihole -v
2. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/FFsT2j7y/

**Comment by yubiuser** [comment]
This is only cosmetic. We'll fix this

**Comment by pheiduck** [comment]
Yep, just an Eye-catcher but nice you will work on it.
`pihole -c` shows this:
```
|¯¯¯(¯)_|¯|_  ___|¯|___        Core: v5.14-0
| ¯_/¯|_| ' \/ _ \ / -_)        Web: v5.17-0
|_| |_| |_||_\___/_\___|        FTL: v5.19
 ——————————————————————————————————————————————————————————
  Hostname: raspberrypi        (Raspberry Pi 3, Model B+)
...
```

**Comment by pheiduck** [comment]
Webinterface is fine/no issue
