### ISSUE TITLE
Web Interface Doesn't Load Properly ("Loading" indicators abound)

### ISSUE THREAD

**Issue by ryanborstelmann** [pi-hole/pi-hole#502]
##### Expected Behaviour:
Web interface loads properly.

##### Actual Behaviour:
Web interface does not load properly:
http://imgur.com/4rnpkIK
http://imgur.com/A5BjHah

##### Steps to reproduce this issue:
None really, just wait a couple hours, then try to load the web interface. Flushing the logs fixes this issue temporarily (pihole -f).

Some details:
Pi-hole Version: v2.6.2 
Web Interface Version: v1.2
/var/log/pihole.log is 40+ MB when i notice this behavior.
Running in an Ubuntu Server 14.04 VM on Hyper-V. This is the only app/service running on the VM.

Note that PiHole itself works properly as a DNS server, the web interface is the only real issue here. Ads are blocked, the whitelist works great, etc. I'm not sure if a huge log file is causing problems, but it seems large? Flushing it fixes this issue for a couple hours or so.

**Comment by Mcat12** [comment]
It seems like the huge amount of queries is doing in the interface... Pastebin the log at `/var/log/lighttpd/error.log`.

**Comment by ryanborstelmann** [comment]
Thanks for your response! http://pastebin.com/ZwPqQ2aD for the error log.

**Comment by Mcat12** [comment]
[This](https://github.com/pi-hole/pi-hole/issues/365#issuecomment-195715789) link might help.

**Comment by ryanborstelmann** [comment]
That did the trick! Set to 1024M. I also found the culprit - HomeKit VM was pinging SmartThings' Graph API about 3 times per second.... 120K+ requests will do the trick to clog up that logfile. Flushed the PiHole log, changed the DNS for the HomeKit server (don't really need adblocking there), and that solves my life troubles.

Thanks for your help!

**Comment by Mcat12** [comment]
:smile:
