### ISSUE TITLE
basic-install.sh script not detecting Ubuntu 22.04 as supported OS

### ISSUE THREAD

**Issue by davidozog** [pi-hole/pi-hole#5025]
### Versions

- Pi-hole:  v5.14.1

### Platform

- OS and version:  Ubuntu 22.04.1 LTS

### Expected behavior

`basic-install.sh` script should detect Ubuntu 22.04 as a supported system.

### Actual behavior / bug

I get this error:
```
Retrieval of supported OS list failed. dig succeeded, but response was blank. Please contact support. 
```

### Steps to reproduce

Run `pi-hole/automated install/basic-install.sh` script on fresh Ubuntu 22.04 installation

### Additional context

I see the script is running this dig command:
```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
```
However, I see from the command line that this doesn't work with the space before the "@".  Also, there is no text output unless I change the `+short` flag to `+noshort`.  Making those changes is not enough though, the response does not mention "SupportedOS":

```
dig +noshort -t txt versions.pi-hole.net@ns1.pi-hole.net 2>&1; echo $?

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> +noshort -t txt versions.pi-hole.net@ns1.pi-hole.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 54548
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;versions.pi-hole.net\@ns1.pi-hole.net. IN TXT

;; AUTHORITY SECTION:
pi-hole.net.		2175	IN	SOA	ns1.pi-hole.net. hostmaster.pi-hole.net. 2022011805 7200 900 1209600 900

;; Query time: 36 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Nov 16 23:12:13 MST 2022
;; MSG SIZE  rcvd: 116

0
```

**Comment by yubiuser** [comment]
The command is correct. I think there is an issue with your DNS resolution. The modification you made correctly yields
`NXDOMAIN`.

```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=35,36 CentOS=8,9"
```

Please use our [discourse forum](https://discourse.pi-hole.net/c/bugs-problems-issues/11) for help regarding configuration issues.

**Comment by davidozog** [comment]
My mistake!  Thanks @yubiuser
