### ISSUE TITLE
homebridge update error

### ISSUE THREAD

**Issue by TrailBlazinPDX** [pi-hole/pi-hole#5026]
### Versions

  Pi-hole version is v5.14.1 (Latest: v5.14.1)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.1 (Latest: v5.19.2)

### Platform

- OS and version:  homebridge

- Platform:  raspberry pi

### Expected behavior

upgraded version for FTL

### Actual behavior / bug

Message: "Unable to complete update, please contact Pi-hole Support"

### Steps to reproduce

1. Go to 'pihole -up'
2. Click on 'wait to run'
3. Scroll down to 'once complete...'

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Are you using the Homebridge image or did you install Homebridge on an already running OS?

**Comment by TrailBlazinPDX** [comment]
The homebridge image   
  
  
  
  
  
  
  

  
  
>

**Comment by dschaper** [comment]
Homebridge has their own way of handling Pi-hole, it's not a platform we directly support.
