### ISSUE TITLE
Editing the admin page for pi-hole

### ISSUE THREAD

**Issue by awestvik** [pi-hole/pi-hole#503]
This is not an issue! Just a minor request of something
Love this project and I'm thinking of expanding the /admin-page to include links for other local servers
on my network. Now I'm not asking how to do this, but how can this be done without a future update 
destroy it?
I'm talking about some really easy stuff like adding links to the header or sidebar.

**Comment by Mcat12** [comment]
We use Git to update the admin page, so`/var/www/html/admin` is a Git repository. Therefore, you can make a new local branch (first `cd /var/www/html/admin` then `git checkout -b custom-branch-name`) and then make your changes. Whenever you want to update, you must have your changes committed (`git commit -a`), merge in the new changes (`git merge master`), fix any conflicts between your version and the official one, and that's it. If there are conflicts, Git will walk you through it.

**Comment by awestvik** [comment]
cool, I will give it a try! But it turns out that my rasbian is not stable at all! So we will see where this goes. 
(Been through 4 SD cards now, installed the latest image from raspbian and it got "stable" again)

**Comment by awestvik** [comment]
[http://imgur.com/n0qzkC1](custom sidebar)

**Comment by manuelgu** [comment]
Look at an example from above, this should help you :) http://fontawesome.io/cheatsheet/

**Comment by awestvik** [comment]
Oh man, this is cool! Thank you! 
HTML has moved forward since 2003 when I last did something 😆
