### ISSUE TITLE
Pihole Open Resolver Security Feature's

### ISSUE THREAD

**Issue by Vulncatic** [pi-hole/pi-hole#5033]
Hello I Have Been notices Alot Of ips connecting to my pihole server requesting stuff like version.bind and sl and a couple dns amplication attacks so i put together a list of ip's that i'm actively updating also i wrote a Python script and a bash script to add iptables rules to block an ip you specify or use the ones in my list 

https://github.com/Vulncatic/Pihole-Iptables-Protection

**Comment by DL6ER** [comment]
You should not be allowing external access to your Pi-hole altogether. If you need to access your Pi-hole while out of the house, please set up a secure connection. Not only will this encrypt (confidentiality + authenticity) but it is also a one-time investment in work that isn't too bad. Follow, e.g., https://docs.pi-hole.net/guides/vpn/wireguard/overview/

**Comment by Vulncatic** [comment]
I Can't do that cus my nana uses my pihole server for dns and shes not that techy

**Comment by PromoFaux** [comment]
Neither here, nor our forums, is an appropriate place to talk about running an open resolver. The only advice you will get from devs/support is "don't"

**Comment by dschaper** [comment]
Same thing as was discussed here when we told you know and you threw a fit.
https://discourse.pi-hole.net/t/pihole-getting-spamed-random-ips/59391
