### ISSUE TITLE
[Tracking] `pihole updatechecker reboot` is not working as expected

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/pi-hole#5034]
### Versions
- Pi-hole:  **v5.14.1**
- AdminLTE:  -
- FTL:  -

### Expected behavior

`pihole updatechecker reboot` should be executed 30 seconds after each boot.

### Actual behavior / bug

At each boot, a cronjob runs `pihole updatechecker reboot`.
The `reboot` option is meant to delay the execution, waiting 30s for the network systems to be ready.
After a recent change this option is not working as expected and there is no delay, causing the command to fail.

## Debug Token

n/a 

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Fixed in https://github.com/pi-hole/pi-hole/releases/tag/v5.14.2
