### ISSUE TITLE
Still see load after turning off load check

### ISSUE THREAD

**Issue by Koal4** [pi-hole/pi-hole#5036]
### Versions

  Pi-hole version is v5.14.1 (Latest: v5.14.1)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.2 (Latest: v5.19.2)

### Platform

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

Proxmox container (see https://tteck.github.io/Proxmox/)

### Expected behavior

Turning off check_load=false doesn't seem to work when adding it to the /etc/pihole/pihole-FTL.conf file.

![image](https://user-images.githubusercontent.com/10795027/203828748-a0711eda-6511-469e-a0a6-bc0d074dba34.png)

### Actual behavior / bug

Load still visible after adding to the the conf file and rebooting the pihole lcx container

### Steps to reproduce

add check_load to the pihole-FTL.conf file and restart it.

![image](https://user-images.githubusercontent.com/10795027/203829039-4e9705ed-fd6e-4bd2-a0d5-f96baa169708.png)
still visible

## Debug Token

- URL:   https://tricorder.pi-hole.net/wK0ARXHQ/

**Comment by yubiuser** [comment]
The option only disables the warning messages, but does not turn off the indicator lights.

**Comment by Koal4** [comment]
Really? lol haha
Any other way to turn it off? These can ignored in my case.

**Comment by yubiuser** [comment]
Currently, there is no way to turn them off. They might be removed completely in a future Pi-hole version

**Comment by Koal4** [comment]
That would be nice (for my situation then) or make it an option.

I was able to turn successfully now through proxmox itself

`Shutdown any running containers, then from the host shell

nano /lib/systemd/system/lxcfs.service

Append the ExecStart=/usr/bin/lxcfs /var/lib/lxcfs with -l (lowercase L)

[Service]

ExecStart=/usr/bin/lxcfs /var/lib/lxcfs -l

Save and exit the file

Restart lxcfs.service

service lxcfs restart

Startup your containers`

In case someone else is looking for the same solution as me.

![image](https://user-images.githubusercontent.com/10795027/203832360-46b96e6c-f729-4468-a5c2-d691595943ac.png)

Anyway thanks for the swift reply :)
