### ISSUE TITLE
Initial graph start time wrong ?

### ISSUE THREAD

**Issue by Tom999Hall** [pi-hole/pi-hole#504]
##### Expected Behaviour:
Graph should show start from time of 1st run after a clean install of Raspbian & pi-hole

##### Actual Behaviour:
Graph starts at 13:00, but I reinstalled at approx 16:00 to 17:00
So to my way of thinking, the graph should start at 17:00 as it's a clean install ?

![pi-hole after clean install](https://cloud.githubusercontent.com/assets/15382859/15254409/986f4bc8-192e-11e6-98d4-768522f24748.jpg)

 
##### Steps to reproduce this issue:
Reformated sd card
downloaded latest Raspbian image
wrote image to sd card
booted up Raspbian
expanded  filesystem to use all the sd card
ran pi-hole installer
graph starts from & shows activity from 13:00

**Comment by Mcat12** [comment]
Since you reinstalled, did you run the uninstaller first? If not, then the log from the previous installation would have stayed behind. So it just continued from the previous log.

**Comment by manuelgu** [comment]
Are you sure that the date matches the date of your timezone?

```
$ date
```

**Comment by Tom999Hall** [comment]
1) No – I didn't run the uninstaller – surely writing a fresh image of Raspbian (to my sd card), would trash everything including the previous pi-hole settings  ?

2) After installing, I noticed that my pi was 1 hour behind (I’m in the UK)
So I ran “Sudo dpkg-reconfigyre tzdata” and set it to Europe / London
It’s now showing the correct date & time

**Comment by PromoFaux** [comment]
1) Ah, if you reformatted the SD card, then for sure the old logs will have gone! We haven't worked out a way to persist across re-imaged SD cards yet.. ;)

2) The log resets each day at 23:58, and the graph displays results from earliest time available in the log.

3) This might have to do with the weird results you were seeing. Now that you've set the time-zone to the correct one, you should see more accurate results.
