### ISSUE TITLE
404 page not found on Pihole admin page

### ISSUE THREAD

**Issue by asshark** [pi-hole/pi-hole#5046]
### Versions

  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.2 (Latest: v5.19.2)

### Platform
- OS and version:  Debian GNU/Linux 11 (bullseye)
- Platform:  Raspberry Pi

### Expected behavior

Have an access to pihole admin page

### Actual behavior / bug

I receive: "404 page not found"

### Steps to reproduce

1. My pihole is running at 192.168.50.103, 
2. When I go to http://192.168.50.103/admin I receive: "404 page not found"
3. I've checked following commands:
4. sudo service lighttpd status -l: 
   "Active: active (running) since Thu 2022-12-01 23:42:03 CET; 13h ago"
5. journalctl -u lighttpd
   "Started Lighttpd Daemon."
7. curl -I http://localhost/admin/
"HTTP/1.1 302 Found
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=nmv5ar3abrg2o1ffglgt8nci95; path=/; HttpOnly; SameSite=Strict
Location: login.php
Content-type: text/html; charset=UTF-8
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline';
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: same-origin
Date: Fri, 02 Dec 2022 12:11:28 GMT
Server: lighttpd/1.4.59"

I have no idea what's going wrong with it.
Any suggestions?
Thanks

## Debug Token

- URL:   https://tricorder.pi-hole.net/9QCNGXEE/

**Comment by rdwebdesign** [comment]
Are you sure the device you are using to access the web  is on the same network?

Can you ping the pi-hole machine from the client device?

**Comment by asshark** [comment]
Yes, they are in the same network, I'm able to ping raspberry with pi-hole (192.168.50.103) from my PC (192.168.50.50)

C:\Users\areks>ping 192.168.50.103

Pinging 192.168.50.103 with 32 bytes of data:
Reply from 192.168.50.103: bytes=32 time<1ms TTL=64
Reply from 192.168.50.103: bytes=32 time<1ms TTL=64
Reply from 192.168.50.103: bytes=32 time<1ms TTL=64
Reply from 192.168.50.103: bytes=32 time<1ms TTL=64

**Comment by dschaper** [comment]
What does `curl -IL http://localhost/admin/` show?

**Comment by asshark** [comment]
It shows:

pi@raspi2:~ $ curl -IL http://localhost/admin/
HTTP/1.1 302 Found
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=i32ngm0o8u4b3hfdhoil36cqb5; path=/; HttpOnly; SameSite=Strict
Location: login.php
Content-type: text/html; charset=UTF-8
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline';
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: same-origin
Date: Fri, 02 Dec 2022 18:24:27 GMT
Server: lighttpd/1.4.59

HTTP/1.1 200 OK
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=b8rljkdnb7bnvirk28b281087d; path=/; HttpOnly; SameSite=Strict
Content-type: text/html; charset=UTF-8
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline';
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: same-origin
Date: Fri, 02 Dec 2022 18:24:27 GMT
Server: lighttpd/1.4.59

**Comment by dschaper** [comment]
Then the web interface is working. You can confirm with `curl -L http://localhost/admin/`

What does `curl -IL http://192.168.50.103/admin/` show from the client? And what does the browser show for `http://192.168.50.130/admin/` with the trailing slash?

**Comment by asshark** [comment]
When I run it from my PC, it shows:

C:\Users\areks> curl -IL http://192.168.50.103/admin/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 02 Dec 2022 18:27:55 GMT
Content-Length: 19

The browser (chrome) run from PC:

http://192.168.50.103/admin/
404 page not found

![image](https://user-images.githubusercontent.com/6809268/205361536-d6cef9f3-69b3-4d9b-87dd-ec7cb8b3811f.png)

**Comment by dschaper** [comment]
The `curl` from your PC is missing the Pi-hole X-headers, it's not going to the Pi-hole server. Compare the output from the `localhost` `curl`s that show the 302 redirect to the 200 successful page presentation.

What does the same `curl -IL http://192.168.50.103/admin/` show from the Pi-hole server directly?

**Comment by asshark** [comment]
**pi@raspi2:~ $ curl -IL http://192.168.50.103/admin/**
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 02 Dec 2022 18:41:26 GMT
Content-Length: 19

**but it for sure valid IP of my raspi:**
**pi@raspi2:~ $ ip address show**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:33:d5:d5 brd ff:ff:ff:ff:ff:ff
    inet **192.168.50.103**/24 brd 192.168.50.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e085:5416:27a6:8fd6/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether b8:27:eb:66:80:80 brd ff:ff:ff:ff:ff:ff
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 06:7e:27:8a:2b:98 brd ff:ff:ff:ff:ff:ff
    inet 10.42.2.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet 169.254.111.73/16 brd 169.254.255.255 scope global noprefixroute flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::8451:a8b:7fc5:ccbf/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::47e:27ff:fe8a:2b98/64 scope link
       valid_lft forever preferred_lft forever
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 8e:0c:ff:aa:b4:8a brd ff:ff:ff:ff:ff:ff
    inet 10.42.2.1/24 brd 10.42.2.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::8c0c:ffff:feaa:b48a/64 scope link
       valid_lft forever preferred_lft forever
6: vethd0c5dff1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 7a:26:98:d8:de:79 brd ff:ff:ff:ff:ff:ff link-netns cni-b554a251-88ed-95cb-1b58-8b64af7c5b9c
    inet 169.254.37.115/16 brd 169.254.255.255 scope global noprefixroute vethd0c5dff1
       valid_lft forever preferred_lft forever
    inet6 fe80::9051:7c56:2675:cd57/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::7826:98ff:fed8:de79/64 scope link
       valid_lft forever preferred_lft forever
7: veth43d200c6@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 4e:13:d0:37:97:9a brd ff:ff:ff:ff:ff:ff link-netns cni-3a719a6e-b465-8f51-cd4d-500026d0fe45
    inet 169.254.36.110/16 brd 169.254.255.255 scope global noprefixroute veth43d200c6
       valid_lft forever preferred_lft forever
    inet6 fe80::7334:ccaf:bdee:24fd/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::4c13:d0ff:fe37:979a/64 scope link
       valid_lft forever preferred_lft forever

**Comment by dschaper** [comment]
What does `ip route get 192.168.50.103` show on the Pi-hole server?

**Comment by asshark** [comment]
pi@raspi2:~ $ ip route get 192.168.50.103
local 192.168.50.103 dev lo src 192.168.50.103 uid 1000
    cache <local>

**Comment by asshark** [comment]
With local at the end, I'm sending picture as I don't know how to escpae it to be show
![image](https://user-images.githubusercontent.com/6809268/205389483-805b937d-e1db-4305-ae1c-53affcf1362a.png)

**Comment by dschaper** [comment]
That looks okay. I really don't know why `localhost` works and `192.168.50.103` doesn't. It may have something to do with that k3s setup. 

Your `curl` output shows me that `lighttpd` isn't even being used when you use the IP
```plain
pi@raspi2:~ $ curl -IL http://192.168.50.103/admin/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 02 Dec 2022 18:41:26 GMT
Content-Length: 19
```
Notice how it's missing the `Server: lighttpd` header. 

This is a configuration issue somewhere and the best place for that is https://discourse.pi-hole.net. You'll need to use the Community help section since your issue is being caused by another webserver being used.

**Comment by HWiese1980** [comment]
Has anyone found a solution to this? I'm facing the same error.

**Comment by rdwebdesign** [comment]
@HWiese1980 

The issue above was a user configuration issue.

Please, ask your questions about configuration at our [Discourse Forum](https://discourse.pi-hole.net/).

As a free open-source project run by volunteers we have very limited resources.
Thank you for your understanding.

---

**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8

**Comment by HWiese1980** [comment]
Yeah, I think the culprit was indeed `k3s` on the same system. Although weirdly `sudo ss -lnp` did not show it as occupant of port 80. I switched pihole lighttpd to port 81 and it works.

**Comment by sybadm** [comment]
k3s is listening to port 80 and 443 so you need change port for piHole

vi /etc/lighttpd/lighttpd.conf 
FROM-> server.port                 = 80
TO->       server.port                 = 8080

sudo systemctl restart lighttpd

**Comment by saxenavinayak** [comment]
Had the same issue with k3s blocking port  80, on pihole v6 you can edit /etc/pihole/pihole.toml to listen on port 8080
