### ISSUE TITLE
PHP 7.4 reached EoL, Pi-Hole and apt does not update PHP at all

### ISSUE THREAD

**Issue by DevelopingEntitiesWithFuntations** [pi-hole/pi-hole#5049]
### Versions

Pi-hole [v5.14.2]
FTL [v5.19.2] 
Web Interface [v5.17]

### Platform

- OS and version:  Raspbian

- Platform:  RPi

### Expected behavior

Have a actively maintained PHP version like 8 running, which still gets security updates on my machine.

### Actual behavior / bug

After trying to update and running `pihole -up` the PHP version stayed at 7.4...

### Steps to reproduce

1. `php -v`
2. Wonder
## Debug Token

- URL:  irrelevant

### Additional context

It's a security issue actually.

**Comment by yubiuser** [comment]
We install no specific PHP version, but what the OS offers by default.

**Comment by DevelopingEntitiesWithFuntations** [comment]
Am I running an old version of Raspbian then?..

**Comment by rdwebdesign** [comment]
> Am I running an old version of Raspbian then?

Actually, we are unable to answer this question.
You didn't add information about your OS **version** and didn't provide a debug token.

**Comment by gruisinger** [comment]
I wanted to let this project know that when you use the "One-Step Automated Install" method detailed in the readme as well as https://docs.pi-hole.net/main/basic-install/ on a fresh Raspberry pi install:

root@raspberrypi:/# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

it installs php 7.4, which is no longer supported:

Selecting previously unselected package php-common.
Preparing to unpack .../08-php-common_2%3a76_all.deb ...
Unpacking php-common (2:76) ...
Selecting previously unselected package php7.4-common.
Preparing to unpack .../09-php7.4-common_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-common (7.4.33-1+deb11u1) ...
Selecting previously unselected package php7.4-json.
Preparing to unpack .../10-php7.4-json_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-json (7.4.33-1+deb11u1) ...
Selecting previously unselected package php7.4-opcache.
Preparing to unpack .../11-php7.4-opcache_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-opcache (7.4.33-1+deb11u1) ...
Selecting previously unselected package php7.4-readline.
Preparing to unpack .../12-php7.4-readline_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-readline (7.4.33-1+deb11u1) ...
Selecting previously unselected package php7.4-cli.
Preparing to unpack .../13-php7.4-cli_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-cli (7.4.33-1+deb11u1) ...
Selecting previously unselected package php7.4-cgi.
Preparing to unpack .../14-php7.4-cgi_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-cgi (7.4.33-1+deb11u1) ...
Selecting previously unselected package php-cgi.
Preparing to unpack .../15-php-cgi_2%3a7.4+76_all.deb ...
Unpacking php-cgi (2:7.4+76) ...
Selecting previously unselected package php7.4-intl.
Preparing to unpack .../16-php7.4-intl_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-intl (7.4.33-1+deb11u1) ...
Selecting previously unselected package php-intl.
Preparing to unpack .../17-php-intl_2%3a7.4+76_all.deb ...
Unpacking php-intl (2:7.4+76) ...
Selecting previously unselected package php-json.
Preparing to unpack .../18-php-json_2%3a7.4+76_all.deb ...
Unpacking php-json (2:7.4+76) ...
Selecting previously unselected package php7.4-sqlite3.
Preparing to unpack .../19-php7.4-sqlite3_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-sqlite3 (7.4.33-1+deb11u1) ...
Selecting previously unselected package php-sqlite3.
Preparing to unpack .../20-php-sqlite3_2%3a7.4+76_all.deb ...
Unpacking php-sqlite3 (2:7.4+76) ...
Selecting previously unselected package php7.4-xml.
Preparing to unpack .../21-php7.4-xml_7.4.33-1+deb11u1_arm64.deb ...
Unpacking php7.4-xml (7.4.33-1+deb11u1) ...
Selecting previously unselected package php-xml.
Preparing to unpack .../22-php-xml_2%3a7.4+76_all.deb ...
Unpacking php-xml (2:7.4+76) ...

8.1 or 8.2 would be preferable: https://www.php.net/supported-versions.php

**Comment by DevelopingEntitiesWithFuntations** [comment]
I did cat /etc/os-release and got the following result:

```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

So it seems the newest version of Raspbian ships with outdated/old PHP, which is super weird. Does Pi-Hole support PHP 8 though??

**Comment by dschaper** [comment]
> 8.1 or 8.2 would be preferable

That's something you'd need to address with the maintainer of the distribution you use. We use what it available.

**Comment by dschaper** [comment]
> So it seems the newest version of Raspbian ships with outdated/old PHP, which is super weird.

That is how Debian works. The latest available version that existed at the time the distribution was released is what is used. It's a stable distribution so you won't see a major version change included.


> Does Pi-Hole support PHP 8 though??

Yeah, sure does.

**Comment by rdwebdesign** [comment]
7.4 is the correct version for Debian 11.

Raspberry Pi OS 11 uses Debian 11 as base.

Release | PHP version
-- | --
Squeeze 6 | 5.3.3
Wheezy 7 | 5.4.45
Jessie 8 | 5.6.40
Stretch 9 | 7.0
Buster 10 | 7.3
Bullseye 11 | 7.4
Bookworm 12 | 8.1
Unstable | 8.1

**Source:**
https://wiki.debian.org/PHP#Available_versions
