### ISSUE TITLE
Can't connect to https://rink.hockeyapp.net link

### ISSUE THREAD

**Issue by Shawin** [pi-hole/pi-hole#505]
##### Expected Behaviour:
This URL should download the Canary mail app from http://canarymail.io: https://rink.hockeyapp.net/api/2/apps/b36ac4a380ea4907940c2054f6163050/app_versions/121?format=zip

##### Actual Behaviour:
"Safari can't connect to the server "rink.hockeyapp.net".

##### Steps to reproduce this issue:
Go to canarymail.io and try to download the app or open the link in any browser while going through pi-hole:
https://rink.hockeyapp.net/api/2/apps/b36ac4a380ea4907940c2054f6163050/app_versions/121?format=zip

**Comment by manuelgu** [comment]
That URL seems to be on the [hosts-file.net](http://hosts-file.net/ad_servers.txt) adlist.

```
/etc/pihole/list.7.hosts-file.net.domains:30197:127.0.0.1       hockeyapp.net
/etc/pihole/list.7.hosts-file.net.domains:36230:127.0.0.1       rink.hockeyapp.net
/etc/pihole/list.7.hosts-file.net.domains:36779:127.0.0.1       sdk.hockeyapp.net
```

Try manually whitelisting the URL using `pihole -w`

**Comment by Shawin** [comment]
@manuelgu Thanks so much. Call me stupid for not looking into that but I never thought that it could be blacklisted since it serves beta apps and no ugly ads or trackers.

**Comment by PromoFaux** [comment]
hosts-file _sometimes_ adds legitimate domains to their lists... 

If you take a look at [their listing](http://hosts-file.net/default.asp?s=hockeyapp.net) for the domain, it's marked as `ATS` which is defined as:

```
TS - Ad/tracking servers
This classification is assigned for domains being used for advert or tracking purposes
```

Could be a false positive, or it could be that they're hosting tracking ads! Does it host apps?

**Comment by Shawin** [comment]
@PromoFaux It hosts apps for beta testing for selected testers. The only tracking I might think of is for improving user experience and finding bugs. And the beta testers would be aware of that when they sign up for beta testing.
I see that "sdk.testflightapp.com" (testflight is another similar beta-testing distribution platform) is also marked as ATS on hosts-file.

I'll try sending the hosts-file person an email and ask for removal of hockeyapp.

**Comment by PromoFaux** [comment]
It may even be that an app hosted on their servers was malicous...

**Comment by Shawin** [comment]
@PromoFaux That's a possibility. It's not a reason to ban the whole thing though because they apps are mostly handed out to select beta testers. Anyway, I emailed the hosts-file.net guy and he removed hockeyapp from his list. Thanks a lot.

**Comment by PromoFaux** [comment]
Super! Did they give any indication as to why it was blackisted?

**Comment by Shawin** [comment]
None. He just said: "Thank you for your e-mail." and "The entries have been removed."
¯\_(ツ)_/¯

**Comment by PromoFaux** [comment]
oh! Almost worrying that it is that easy....

**Comment by Shawin** [comment]
I guess he must have checked. HockeyApp has always been trustworthy, and now has been acquired by Microsoft.
