### ISSUE TITLE
use-application-dns.net is not returning NXDOMAIN as required to disable DNS-over-HTTPS in Firefox (#3166 got reverted at some point?)

### ISSUE THREAD

**Issue by aarontc** [pi-hole/pi-hole#5058]
### Versions

- Pi-hole:  v5.14.2
- AdminLTE:  v5.17
- FTL:  v5.19.2

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Raspberry Pi, Docker - Container tag: 2022.11.2

### Expected behavior

`dig use-application-dns.net` should return an NXDOMAIN result.

### Actual behavior / bug

`dig use-application-dns.net` is returning real IPs from Mozilla.

### Steps to reproduce

1. Install PiHole
2. Open a termianl
3. Type `dig use-application-dns.net`
4. (Ensure the query went to your pihole IP)
5. Observe the result contains real IPs instead of NXDOMAIN.

## Debug Token

- URL:  https://tricorder.pi-hole.net/5POaABW7/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
I cannot reproduce this, so we're going to have to assume it is a configuration issue until we see any evidence otherwise:

```
adam@adam-pc> nslookup use-application-dns.net
Server:  pi.hole
Address:  192.168.1.253

*** pi.hole can't find use-application-dns.net: Non-existent domain
```

Do you have something else intercepting dns queries on your network, perhaps? I'm running two Pi-hole instances on my network, both in docker containers, and the canary domain is returning NXDOMAIN as expected

Can you also please check the output of the following:

```
cat /var/log/pihole-FTL.log | grep MOZILLA_CANARY
```

**Comment by aarontc** [comment]
I don't have anything else intercepting DNS. I tried manually against all three of my Pi-Hole instances and saw the same result. The log check you suggested was negative:

```bash
$ docker exec -it pihole_pihole_1 bash
root@c2:/# cat /var/log/pihole-FTL.log | grep MOZILLA_CANARY
root@c2:/# 
```

I don't know how to investigate this further but if it's a problem with my configuration, I can just put a file in /etc/dnsmasq.d with the required line to disable the domain - `server=/use-application-dns.net/`.

Thanks for checking into this. I assumed it was a project-level issue since I grepped the whole project and couldn't find that hostname in the source, and I thought my configuration was very basic :sweat_smile:

**Comment by PromoFaux** [comment]
> root@c2:/# cat /var/log/pihole-FTL.log | grep MOZILLA_CANARY

I would at least hoped to have seen: `MOZILLA_CANARY: Disabled` in your output there, which would have explained it...

Check you haven't got it disabled in the FTL config for whatever reason: https://docs.pi-hole.net/ftldns/configfile/#mozilla_canary

Though, as you are running in the docker container, try adding `FTLCONF_MOZILLA_CANARY` as an environment variable with the value of `true` per the [Advanced Variables](https://github.com/pi-hole/docker-pi-hole#advanced-variables) section of the readme

**Comment by jfb-pihole** [comment]
> 4\. (Ensure the query went to your pihole IP)

Please post the complete output of the dig command.
