### ISSUE TITLE
Local repo hash has only length of 7 instead of 8

### ISSUE THREAD

**Issue by Gothico74** [pi-hole/pi-hole#5059]
After updating PADD to 3.9 the headline shows Pi-Hole as aged, newer versions available.

pi@raspberrypi-hole:~ $ pihole -v
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.2 (Latest: v5.19.2)

pi@raspberrypi-hole:~ $ sudo pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.31-1~deb10u1
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
![pihole_padd390](https://user-images.githubusercontent.com/57674557/207100874-0133834b-3750-47ef-bb60-b072b94a7242.png)

**Comment by dschaper** [comment]
Debug log please. `pihole -d`.

**Comment by Gothico74** [comment]
> Please delete `/etc/pihole/versions` and run `pihole updatechecker` again

Did not help

**Comment by Gothico74** [comment]
> Debug log please. `pihole -d`.

https://tricorder.pi-hole.net/h1AEqNQr/

**Comment by dschaper** [comment]
For some reason your `git` output is not what we expect. Do you have any `git` configuration customizations?

What is the output from
```bash
cd /etc/.pihole
git config -l 
git describe --long --dirty --tags --always
```

**Comment by Gothico74** [comment]
pi@raspberrypi-hole:/etc/.pihole $ git config -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/pi-hole/pi-hole.git
remote.origin.fetch=+refs/heads/master:refs/remotes/origin/mast
er
branch.master.remote=origin
branch.master.merge=refs/heads/master

pi@raspberrypi-hole:/etc/.pihole $ git describe --long --dirty
--tags --always
v5.14.2-0-g0034538

**Comment by aDilly** [comment]
Following for the same issue on both my pihole machines.

Ran the same command per @dschaper on both, noticed a different output with  `git describe --long --dirty --tags --always`

both of my machines output:
`v5.14.2-0-g00345387`

all other outputs matched @Gothico74 , except the hash(?) has an extra character `g00345387`

debug logs
https://tricorder.pi-hole.net/pgS1bkC4/
https://tricorder.pi-hole.net/FJTn29R7/

**Comment by rdwebdesign** [comment]
The hash is the same in both cases, but some systems are showing the first 7 characters, others the first 8. Maybe some versions are using different default options than others.

I think the numbers of characters should be set on the command to avoid any options (set by default or by users) interfering with the output.

Using `--abbrev=8` should be enough:
```sh
git describe --abbrev=8 --dirty --tags --always
```

**Comment by rdwebdesign** [comment]
@Gothico74

Can you please compare the results of the commands below on your system (you need to `cd /etc/.pihole` before)?

```console
git describe --long --dirty --tags --always
```
and 
```console
git describe --abbrev=8 --dirty --tags --always
```

**Comment by bob787** [comment]
Here you go...

pi@piehole:/etc/.pihole $ git describe --long --dirty --tags --always
**v5.14.2-0-g00345387**

pi@piehole:/etc/.pihole $ git describe --abbrev=8 --dirty --tags --always
**v5.14.2**

**Comment by Gothico74** [comment]
> @Gothico74
> 
> Can you please compare the results of the commands below on your system (you need to `cd /etc/.pihole` before)?
> 
> ```
> git describe --long --dirty --tags --always
> ```
> 
> and
> 
> ```
> git describe --abbrev=8 --dirty --tags --always
> ```

pi@raspberrypi-hole:/etc/.pihole $ git describe --abbrev=8 --dirty --tags --always
v5.14.2

pi@raspberrypi-hole:/etc/.pihole $ git describe --long --dirty --tags --always
v5.14.2-0-g0034538

**Comment by Gothico74** [comment]
I thought its only a visual thingie.. so i didn't reply

**Comment by Falconcrest** [comment]
Sorry to join in, but I'm having almost the same problem, except for the FTL display.

![Pic](https://user-images.githubusercontent.com/20321911/208245136-f1ebca05-fb4d-4bce-9248-4787923f2957.jpg)

**Comment by Falconcrest** [comment]
Sorry, I had overlooked the same contribution under **_Closed_**.  :-(

**Comment by yubiuser** [comment]
All good, sometimes it's hard to find similar issues.

**Comment by yubiuser** [comment]
I just had an crazy idea, why some see this bug. Please try if

`pihole checkout core awk` 

fixes the bug. You can go back anytime and before the next update with `pihole checkout core master`

**Comment by Falconcrest** [comment]
I ran `pihole checkout core awk` successfull.
See here:
root@pihole:~# pihole -v
  Pi-hole version is awk v5.14.2-27-g8312eb13 (Latest: v5.14.2)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.2 (Latest: v5.19.2)
root@pihole:~# pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

The PADD display is still incorrect.

![pic2](https://user-images.githubusercontent.com/20321911/208252735-c318db8a-b310-4d23-8854-d192c800cbb0.jpg)

**Comment by yubiuser** [comment]
What is the output of `git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master" | awk '{print substr($0, 0,8);}'`

**Comment by Gothico74** [comment]
`  [✓] FTL is listening on port
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
fatal: unable to access 'https://github.com/pi-hole/pi-hole/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/pi-hole/AdminLTE/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/pi-hole/FTL/': Could not resolve host: github.com
`

otherwise the same @Falconcrest posted

**Comment by Gothico74** [comment]
> 

`c32761e`

**Comment by rdwebdesign** [comment]
@Gothico74

> `c32761e`

This should show 8 characters, but in your case shows only 7. I this could be a difference on git itself, or some config.

What is the output of `git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master"`? and `git --version`?

**Comment by Gothico74** [comment]
> @Gothico74
> 
> > `c32761e`
> 
> This should show 8 characters, but in your case shows only 7. I think this could be a difference on git itself, or some config.
> 
> What is the output of `git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master"`? and `git --version`?

pi@raspberrypi-hole:~ $ git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master"
c32761e7864b9fa29c1a22def2b1c3698c609d79        refs/heads/master

pi@raspberrypi-hole:~ $ git --version
git version 2.20.1

**Comment by Falconcrest** [comment]
@rdwebdesign, @yubiuser 
Here is my output: 

root@pihole:~# `git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master" | awk '{print substr($0, 0,8);}'`
c32761e7

root@pihole:~# `git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master"`
c32761e7864b9fa29c1a22def2b1c3698c609d79        refs/heads/master

root@pihole:~# `git --version`
git version 2.30.2

**Comment by rdwebdesign** [comment]
Thanks.

Here, I saw a completely different output, using `git version 2.30.2`:

```
c32761e7864b9fa29c1a22def2b1c3698c609d79        refs/heads/master
```
Then, `awk` cuts the string and shows only the first 8 characters.

Your `git` is returning only 7 characters, so the `awk` command do nothing.

**Comment by Falconcrest** [comment]
@rdwebdesign 

Sorry, entered now the correct output.

**Comment by yubiuser** [comment]
> root@pihole:~# git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master" | awk '{print substr($0, 0,8);}'
"c32761e7"

This is the correct output. Please run `pihole updatechecker` and post your `/etc/pihole/versions` file

**Comment by Falconcrest** [comment]
root@pihole:~#`nano /etc/pihole/versions`
CORE_VERSION=v5.14.2
CORE_BRANCH=master
CORE_HASH=00345387
GITHUB_CORE_VERSION=v5.14.2
GITHUB_CORE_HASH=c32761e7
WEB_VERSION=v5.17
WEB_BRANCH=master
WEB_HASH=da2764e5
GITHUB_WEB_VERSION=v5.17
GITHUB_WEB_HASH=a8164201
FTL_VERSION=v5.19.2
FTL_BRANCH=master
FTL_HASH=844c8b9f
GITHUB_FTL_VERSION=v5.19.2
GITHUB_FTL_HASH=844c8b9f

**Comment by Falconcrest** [comment]
I don't know if it matters, but my OS is DietPi v8.11.2 based on:

root@pihole:~# `uname -a`
Linux pihole 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

root@pihole:~# `cat /proc/version`
Linux version 5.15.76-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022

root@pihole:~# `cat /etc/*release`
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by Gothico74** [comment]
`pi@raspberrypi-hole:~` $ nano /etc/pihole/versions
  GNU nano 3.2                                                                                 /etc/pihole/versions

CORE_VERSION=v5.14.2-27-g8312eb13
CORE_BRANCH=awk
CORE_HASH=8312eb13
GITHUB_CORE_VERSION=v5.14.2
GITHUB_CORE_HASH=8312eb13
WEB_VERSION=v5.17
WEB_BRANCH=master
WEB_HASH=da2764e5
GITHUB_WEB_VERSION=v5.17
GITHUB_WEB_HASH=a8164201
FTL_VERSION=v5.19.2
FTL_BRANCH=master
FTL_HASH=844c8b9f
GITHUB_FTL_VERSION=v5.19.2
GITHUB_FTL_HASH=844c8b9f

**Comment by Gothico74** [comment]
pi@raspberrypi-hole:~ $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by rdwebdesign** [comment]
I don't think the OS version is a problem:

I tested the commands on "Raspbian GNU/Linux 10 (buster)" and using `git version 2.20.1`. 
My output was the expected:

```console
root@pi3b:~ # git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master"
c32761e7864b9fa29c1a22def2b1c3698c609d79        refs/heads/master

root@pi3b:~ # git ls-remote "https://github.com/pi-hole/pi-hole" --tags "master" | awk '{print substr($0, 0,8);}'
c32761e7
```

**Comment by yubiuser** [comment]
It's not... ;-)
`PADD` is to advanced for `Pi-hole`.

Now the local and the web hash don't match, but all are 8 chars long.

>WEB_HASH=da2764e5 
GITHUB_WEB_HASH=a8164201
CORE_HASH=8312eb13
GITHUB_CORE_HASH=8312eb13

PADD uses the last hashes to determine if changes on the the github repos were made, but `pihole -up` does not. However, we had PRs to master which have not been tagged yet.
https://github.com/pi-hole/AdminLTE/pull/2457
https://github.com/pi-hole/pi-hole/pull/5063

**Comment by Falconcrest** [comment]
@yubiuser, @rdwebdesign 

...and now? Do you professionals have a solution or a workaround for our problem? ;-)

**Comment by yubiuser** [comment]
Ignore it for now. We'll change the `PADD` code to match the `Pi-hole` code better. It'll be in the upcoming PADD bugfix release

**Comment by Falconcrest** [comment]
I know everything will be fine as always!
Thank you in advance!

**Comment by yubiuser** [comment]
Could you try this version?

https://raw.githubusercontent.com/pi-hole/PADD/no_hash_on_master/padd.sh

**Comment by yubiuser** [comment]
The linked version above should solve the issue with PADD reporting updates available when untagged commits exist in master. It will not solve the 7 character issue seen in Gothico74's first log. However, later `versions` files did not contain 7 char hashes anymore

> CORE_VERSION=v5.14.2-27-g8312eb13
CORE_BRANCH=awk
CORE_HASH=8312eb13
GITHUB_CORE_VERSION=v5.14.2
GITHUB_CORE_HASH=8312eb13
WEB_VERSION=v5.17
WEB_BRANCH=master
WEB_HASH=da2764e5
GITHUB_WEB_VERSION=v5.17
GITHUB_WEB_HASH=a8164201
FTL_VERSION=v5.19.2
FTL_BRANCH=master
FTL_HASH=844c8b9f
GITHUB_FTL_VERSION=v5.19.2
GITHUB_FTL_HASH=844c8b9f

**Comment by polyclementc** [comment]
I can confirm it solve the problem (I had the same issue as other).
Thank you!

**Comment by Falconcrest** [comment]
@yubiuser 
And now, the Oscar goes to ....
Very nice, I'm always amazed at how quickly you get such problems solved by us users. 
Many thanks!

**Comment by bob787** [comment]
Yes, one more conformation the linked Padd.sh from @yubiuser worked. All versions are back in the Green. 

Is it weird that this makes me happy?

**Comment by christianboyle** [comment]
@yubiuser When using `development` branch of `PADD` (as of yesterday) I'm getting a new bug where I see `DNS is off!` rather than `System is healthy`. 

This changed a few hours after switching (things were fine initially, but changed over night).

There's no actual issue with DNS, the PiHole is working as expected and is blocking normally.

![2022-12-19_08-36-42AM](https://user-images.githubusercontent.com/1605754/208450359-383b79b1-dd29-4c90-80be-31872d88ff51.png)

**Comment by Falconcrest** [comment]
Sorry for the question in the closed post, but is there a way to re-provide this link?

**Comment by yubiuser** [comment]
Use https://raw.githubusercontent.com/pi-hole/PADD/development/padd.sh

**Comment by Falconcrest** [comment]
Nice, Thanks 👍

**Comment by bob787** [comment]
@yubiuser I'm also running the development branch of PADD, but have a different but related issue. My display says `Pi-hole is offline` vs the normal `System is healthy`. Blocking is occurring normally and a reboot fixes the issue.

Let me know if you want me to try anything

![IMG_0939 Medium](https://user-images.githubusercontent.com/98560908/209588627-d5760614-6e68-412e-b4a4-354e06b11be0.jpeg)

**Comment by jfb-pihole** [comment]
https://github.com/pi-hole/PADD/issues/307

**Comment by yubiuser** [comment]
The fix for `PADD` has been released with https://github.com/pi-hole/PADD/releases/tag/v3.10.0
___

The original `core` issue (hash length 7 instead of 8) has not been reported again.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/PADD/releases/tag/v3.10.0
