### ISSUE TITLE
Many websites are showing debug message of pi-hole

### ISSUE THREAD

**Issue by bitterypaul** [pi-hole/pi-hole#506]
Many legitimate websites like http://freegeoip.net/json/, http://www.monotorrent.com/legacy are showing var x = "Pi-hole: A black hole for Internet advertisements.".

**Comment by manuelgu** [comment]
You can manually whitelist the URLs for you.
`pihole -w domain.com another-domain.com`

**Comment by PromoFaux** [comment]
@bitterypaul some further investigation shows that monotorrent is not a legitimate site...

`monotorrent.com` itself doesn't appear on any in any of the ad source lists.. however it tries to load content from `dp.g.doubleclick.net`, which _IS_ on the lists. 

On disabling uBlock origin, and whitelisting the above site I get a domain parked site full of ads. I don't think monotorrent.com is what you think it is...

![image](https://cloud.githubusercontent.com/assets/1998970/15269640/62ae4ae6-19fd-11e6-9017-68ed732b0cea.png)

**Comment by PromoFaux** [comment]
`freegeoip.net`, however, _does_ appear on blocklists, and if you're sure it's not a dodgy site.. you can whitelist it by running:

`pihole -w freegeoip.net`

**Comment by Tom999Hall** [comment]
I'm seeing  this on Sky News on my mobile (Nexus 6P), but not on my Windows 10 PCs 
![news sky com](https://cloud.githubusercontent.com/assets/15382859/15446156/2e4e50aa-1f0e-11e6-90e0-1309d1adec76.jpg)

**Comment by Mcat12** [comment]
When I set chrome to act as a Nexus 6P, it rendered the page fine, although it was the website and not the app you are using.
![Screenshot](http://img.prntscr.com/img?url=http://i.imgur.com/cut9czj.png)

**Comment by Tom999Hall** [comment]
Sky news is now displaying Ok on my Nexus 6P (and my wife's 6P)
I guess there may have been some transient blocked site, that has now been edited-out due to changing news stories ? 
As this was the only site where I've ever had this problem - and then it was mobile-only, don't worry about it - if I see any more instances, I'll let you know

**Comment by Mcat12** [comment]
The only reason that would have been shown would be if the site was showing the JavaScript in plaintext instead of executing it, afaik...

**Comment by dschaper** [comment]
Ping for timeout.

**Comment by dschaper** [comment]
This bug still rears its head occasionally.

**Comment by Mcat12** [comment]
Closing unless this is shown to be a Pi-hole issue instead of a website's issue.
