### ISSUE TITLE
install via --unattended option does not install lighthttp server

### ISSUE THREAD

**Issue by wolfebrian2120** [pi-hole/pi-hole#5060]
I'm trying to automate the install of pihole into a Vagrant based virtualbox server. So I have a custom script which runs your install script. I place the following setupVars.conf in the appropriate default location and then run the script with the --unattended option.

I believe it is a bug that the script does not install lighthttpd in unattended mode, since there is an option flag that one could append to the script to disable the install of the webserver component.

setupVars.conf
```
PIHOLE_INTERFACE=eth1
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
CACHE_SIZE=10000
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSMASQ_LISTENING=local
WEBPASSWORD=1addd3920db07c4b09aff3ece5efcdc142f712a05d589fdd88ddfdaf82e4c4a6
BLOCKING_ENABLED=true
```

Script
```
echo "Beginning pihole setup"
mkdir -p /etc/pihole/
cp /vagrant/setupVars.conf /etc/pihole/setupVars.conf
curl -sSL https://install.pi-hole.net > ~/basic-install.sh
chmod +x ~/basic-install.sh
~/basic-install.sh --unattended
```

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform
[vagrant@pihole ~]$ cat /etc/redhat-release
CentOS Stream release 8

[vagrant@pihole ~]$ uname -a
Linux pihole 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@pihole ~]$ pihole -v
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  FTL version is v5.19.2 (Latest: v5.19.2)

- Platform:  
Vagrant/Virtual Box Guest VM running on intel x86_64

**Comment by yubiuser** [comment]
It should install `lighttpd` the way you run the setup. Please check if EPEL is installed before/after you run the setup

https://github.com/pi-hole/pi-hole/blob/0034538794a3754ab532a53480da39d3fd13d7ed/automated%20install/basic-install.sh#L370-L383

**Comment by dschaper** [comment]
Try the following script changes and post up the log please.

```bash
echo "Beginning pihole setup"
mkdir -p /etc/pihole/
cp /vagrant/setupVars.conf /etc/pihole/setupVars.conf
curl -sSL https://install.pi-hole.net > ~/basic-install.sh
sudo bash -x ~/basic-install.sh --unattended | tee ~/pihole-install.log
```

**Comment by wolfebrian2120** [comment]
Here is the log file requested
[pihole-install.log](https://github.com/pi-hole/pi-hole/files/10213221/pihole-install.log)

**Comment by rdwebdesign** [comment]
Did you use the `-x` option for this command `sudo bash -x ~/basic-install.sh --unattended | tee ~/pihole-install.log`?

**Comment by wolfebrian2120** [comment]
> Did you use the `-x` option for this command `sudo bash -x ~/basic-install.sh --unattended | tee ~/pihole-install.log`?

yes I literally used the snippet that @dschaper provided

**Comment by wolfebrian2120** [comment]
@rdwebdesign I found the -x output you were looking for. vagrant output it to the console.
[pihole - vagrant output.txt](https://github.com/pi-hole/pi-hole/files/10213343/pihole.-.vagrant.output.txt)

**Comment by rdwebdesign** [comment]
I'm not sure what is happening, but the log shows `LIGHTTPD_ENABLED=false`.

Are you sure the `setupVars.conf` was copied and used inside the VM?

**Comment by wolfebrian2120** [comment]
Yea I just confirmed that it is being copied into the correct location, by cating the file before and after install. Before the install script is run, it is set to true as in my initial post. And after the script runs it is set to false.

**Comment by rdwebdesign** [comment]
No.
The code is working as expected.

[The lines from 2586 to 2600](https://github.com/pi-hole/pi-hole/blob/0034538794a3754ab532a53480da39d3fd13d7ed/automated%20install/basic-install.sh#L2586-L2600) install and try to enable `lighttpd`.

The code you posted is only checking if `lighttpd` was successfully enabled. 
The problem is something else.

**Comment by wolfebrian2120** [comment]
Yea something seems to be wrong with the dependencies list. I was able to run it manually with no setupVars.conf. It installs fine when done manually. I can see it install lighttpd with dnf.

here is my output from that run.
[pihole-install-manual.txt](https://github.com/pi-hole/pi-hole/files/10221053/pihole-install-manual.txt)

**Comment by rdwebdesign** [comment]
You can see the difference here:

```sh
+ unset dep_install_list
+ [[ true == true ]]
+ enable_service lighttpd                                                      # these commands are only executed
+ local 'str=Enabling lighttpd service to start on reboot'                     # on the "manual" installation
+ printf '  %b %s...' '[i]' 'Enabling lighttpd service to start on reboot'     #
  [i] Enabling lighttpd service to start on reboot...+ is_command systemctl    #
+ local check_command=systemctl                                                #
+ command -v systemctl                                                         #
+ systemctl enable lighttpd                                                    #
+ printf '%b  %b %s...\n' '\r\033[K' '[\e[1;32m✓\e[0m]' 'Enabling lighttpd service to start on reboot'  #
  [✓] Enabling lighttpd service to start on reboot...                          #
+ check_service_active lighttpd
+ is_command systemctl
+ local check_command=systemctl
+ command -v systemctl
+ systemctl is-enabled lighttpd
+ LIGHTTPD_ENABLED=true
```

This attempt installed `lighttpd` and enabled the service successfully.
The check result was `true` and the variable was set to `LIGHTTPD_ENABLED=true`.

**Comment by wolfebrian2120** [comment]
manual install
```
+ dep_install_list=("${PIHOLE_DEPS[@]}")
+ local dep_install_list
+ [[ true == true ]]
+ dep_install_list+=("${PIHOLE_WEB_DEPS[@]}")
+ printf '  %b Checking for / installing Required dependencies for Pi-hole software...\n' '[i]'
  [i] Checking for / installing Required dependencies for Pi-hole software...
+ install_dependent_packages cronie curl findutils sudo unzip libidn2 psmisc libcap nmap-ncat jq lighttpd lighttpd-fastcgi php-common php-cli php-pdo php-xml php-json php-intl
+ declare -a installArray
```
unattended
    ```
    master: + dep_install_list=("${PIHOLE_DEPS[@]}")
    master: + local dep_install_list
 == true ]] + [[ true
    master: + printf '  %b Checking for / installing Required dependencies for Pi-hole software...\n' '[i]'
    master: + install_dependent_packages cronie curl findutils sudo unzip libidn2 psmisc libcap nmap-ncat jq
    master: + declare -a installArray
```
Yea and the dependencies installed are different as well. So something isn't picking the right list to install.

**Comment by dschaper** [comment]
> + dep_install_list+=("${PIHOLE_WEB_DEPS[@]}")

That line happens if this block fires
```plain
    # Install the Core dependencies
    local dep_install_list=("${PIHOLE_DEPS[@]}")
    if [[ "${INSTALL_WEB_SERVER}" == true ]]; then
        # And, if the setting says so, install the Web admin interface dependencies
        dep_install_list+=("${PIHOLE_WEB_DEPS[@]}")
    f
```

What is the exact command you are using on the manual install?

What is the user account that Vagrant is running under?

**Comment by dschaper** [comment]
Are you manually running the install unattended as well?

**Comment by wolfebrian2120** [comment]
> What is the exact command you are using on the manual install?

`bash -x basic-install.sh`

> What is the user account that Vagrant is running under?

I have it running as root. I can select if I want a privileged session or not. And I made sure it is running as root.

> Are you manually running the install unattended as well?

Yes I have manually run it unattended with the same result. using the following command
`bash -x basic-insta.sh --unattended`

I have also tried with the reconfigure flag and tried running it twice, replacing the setupVars.conf file before the second run. Each time unattended mode does not install the lighttpd server.

**Comment by wolfebrian2120** [comment]
++

**Comment by wolfebrian2120** [comment]
++

**Comment by PromoFaux** [comment]
Might be unhelfpul in your case here - but our docker version is created by using this `--unattended` flag

https://github.com/pi-hole/docker-pi-hole/blob/master/src/s6/debian-root/usr/local/bin/install.sh#L51-L69

Base image of that, though, is Debian. Maybe there is an issue with it on CentOS, but I don't currently have the resources to examine this (the `--unattended` flag isn't really meant for human consumption, I think it was added a long time ago to assist our test suite)

**Comment by PromoFaux** [comment]
That said...

Here is a very long gif showing it working when I type all the commands you wrote into a CentOS stream 8 droplet (SELINUX=disabled because I have no idea what I'm doing there)

![itworksoncentos8stream](https://user-images.githubusercontent.com/1998970/218551800-a62e64be-f58e-41e4-b6d2-a4a4b4a8fb00.gif)

**Comment by wolfebrian2120** [comment]
@PromoFaux  So I was able to reproduce what your gif shows. It worked because I manually created the file in centos. I found out the issue was that my setupVars.conf was created on my windows machine. when my vagrant process would push it to the machine it had some MS /r characters in it which was affecting the evaluation of some of the boolean settings. 

for example this part of the code would fail evaluation.
    if [ "${INSTALL_WEB_SERVER}" == true ]; then
        # And, if the setting says so, install the Web admin interface dependencies
        dep_install_list+=("${PIHOLE_WEB_DEPS[@]}")
    fi

I ended up fixing my deployment script to run the file through dos2unix before running the install script. i'm not sure if you should sanitize the inputs from the file or maybe make a note in the documentation that the file must conform to unix.

**Comment by rdwebdesign** [comment]
I'm not sure if this what you need (I don't use Vagrant), maybe you can fix this using a config:

https://stackoverflow.com/questions/28651275/windows-crlf-to-unix-lf-issues-in-vagrant

**Comment by PromoFaux** [comment]
> i'm not sure if you should sanitize the inputs from the file or maybe make a note in the documentation that the file must conform to unix.

Ongoing work on V6 will render the setupvars file (and therefore processing of it) entirely obsolete - at this stage it's probably not worth adding complexity to the setupvars processing to fix what is ostensibly an edge case
