### ISSUE TITLE
pihole flush once is ignoring logrotate file due to wrong permissions

### ISSUE THREAD

**Issue by westfeld** [pi-hole/pi-hole#5077]
### Versions
- Pi-hole:  5.14.2
- AdminLTE:  5.17
- FTL:  5.19.2

### Platform

- OS and version:  Debian 10.5

- Platform:  RaspberryPi

### Expected behavior

Logrotate should run without issues.

### Actual behavior / bug

Daily cron job running `pihole flush once quiet` is quitting with:

    error: Ignoring /etc/pihole/logrotate because the file owner is wrong (should be root or user with uid 0).

The owner of the file is as follows:

    -rw-r--r-- 1 pihole pihole 241 Jul 16 13:24 /etc/pihole/logrotate

When setting the permission to root with`sudo chown root /etc/pihole/logrotate` it works. However on every restart the permissions are reset by the pihole-FTL.service when using systemd.

I could provide a PR that just adds another line of `ExecStartPre=/bin/chown root /etc/pihole/logrotate` to reset the permissions after the whole /etc/pihole directory is owned by pihole:pihole, but I am not sure if this would break things for other installations/distributions.

### Steps to reproduce

1. Install pihole under Raspbian 10.52. 

## Debug Token

- URL:  

[✓] Your debug token is: https://tricorder.pi-hole.net/VwFJzNLL/

**Comment by dschaper** [comment]
I've just spot checked a few installations and they all have `/etc/pihole/logrotate` set with `root` ownership.

There's nothing in https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole-FTL.service that changes the ownership of that file nor the ownership of the whole directory.

Can you provide the journalctl output from the service restart?

**Comment by dschaper** [comment]
Are you running development branch code? Or did you copy over the development service file?

@MichaIng https://github.com/pi-hole/pi-hole/blob/development/advanced/Templates/pihole-FTL-prestart.sh#L20 I think that will break like this?

**Comment by yubiuser** [comment]
This line was just copied over. It's the same on master.
https://github.com/pi-hole/pi-hole/blob/8d2e023ec0a2c52c309fd7971d76eeaef124ad65/advanced/Templates/pihole-FTL.service#L38

**Comment by dschaper** [comment]
Hmm, indeed it is on master. Then why are the other installs correct and this one is not?

**Comment by yubiuser** [comment]
Because this one uses (although on `master`) systemd to start the service and this must have caused the issue.
Normal master looks like

```
*** [ DIAGNOSING ]: Pi-hole-FTL full status
   ● pihole-FTL.service - LSB: pihole-FTL daemon
     Loaded: loaded (/etc/init.d/pihole-FTL; generated)
     Active: active (exited) since Mon 2022-12-19 12:49:45 GMT; 2h 44min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 623 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
        CPU: 48ms

```
This one

```
*** [ DIAGNOSING ]: Pi-hole-FTL full status
   ● pihole-FTL.service - Pi-hole FTLDNS
     Loaded: loaded (/etc/systemd/system/pihole-FTL.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-12-17 10:11:18 UTC; 2 days ago
   Main PID: 2407 (pihole-FTL)
      Tasks: 19 (limit: 4915)
        CPU: 13min 53.988s
     CGroup: /system.slice/pihole-FTL.service
             └─2407 /usr/bin/pihole-FTL -f
```

@westfeld From where did you get a proper `pihole-FTL.service` file? Which other modifications did you do? How did you install Pi-hole?

**Comment by MichaIng** [comment]
The line from master init.d service as well as dev prestart does not chown `/etc/pihole` recursively but just the directory. So `/etc/pihole/logrotate` is not touched at all and systemd does not chown random files either 🤔.

What is the exact content of the systemd unit and in case invoked scripts?
```sh
systemctl cat pihole-FTL
```

**Comment by westfeld** [comment]
Thanks for your feedback. I installed pihole using the usual installation script, which worked fine. I had some issues with my networking on my RPi that is why I switched to system.networking which is a great thing. I had the problem that pihole was starting too early in the boot process, so I wanted to use a "real" service file, not an Init V wrapper.

To be honest I did not recall that this is a non-standard installation now.

I think the point is what @MichaIng posted:



> The line from master init.d service as well as dev prestart does not chown `/etc/pihole` recursively but just the directory. So `/etc/pihole/logrotate` is not touched at all and systemd does not chown random files either 🤔.

In my service file, it indeed DOES a `chown -R` so applying the ownership recursively. I think this can be the point.

That could be my issue.

Here is my pihole-FTL.service file.

    [Unit]                                                                                                                                                                                    
    Description=Pi-hole FTLDNS                                                                                                                                                                
    After=network-online.target                                                                                                                                                               
    Wants=nginx.service                                                                                                                                                                       
                                                                                                                                                                                              
    [Service]                                                                                                                                                                                 
    User=pihole                                                                                                                                                                               
    Group=pihole                                                                                                                                                                              
    PIDFile=/run/pihole-FTL.pid                                                                                                                                                               
    ExecStartPre=/bin/touch /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log                                                                              
    ExecStartPre=/bin/mkdir -p /var/run/pihole /var/log/pihole                                                                                                                                
    ExecStartPre=/bin/rm -f /var/run/pihole/FTL.sock                                                                                                                                          
    ExecStartPre=/bin/chown -R pihole:pihole /var/run/pihole /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /etc/pihole /etc/pihole/dhcp.leases /var/log/pihole.log /var/log/pihole                                                                                                                                                                                       
    ExecStartPre=/bin/chmod u=rwX,go=rX /var/run/pihole /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /etc/pihole /etc/pihole/dhcp.leases /var/log/pihole.log /var/log/pihole /var/run/pihole                                                                                                                                                                            
    ExecStartPre=/sbin/setcap cap_net_bind_service,cap_net_raw,cap_net_admin=+eip /usr/bin/pihole-FTL                                                                                         
    ExecStartPre=/bin/bash -c "/bin/echo 'nameserver 127.0.0.1' | /sbin/resolvconf -a lo.piholeFTL"                                                                                           
    ExecStart=/usr/bin/pihole-FTL -f                                                                                                                                                          
    ExecReload=/bin/kill -USR1 $MAINPID                                                                                                                                                       
    Restart=on-failure                                                                                                                                                                        
    TimeoutStopSec=5s                                                                                                                                                                         
    PermissionsStartOnly=true                                                                                                                                                                 
    #AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_NET_ADMIN                                                                                                                       
                                                                                                                                                                                              
    [Install]                                                                                                                                                                                 
    WantedBy=multi-user.target

**Comment by MichaIng** [comment]
That explains it. `/etc/pihole` is indeed not intended to be fully owned by `pihole` user. I suggest to test the systemd unit with prestart + postup scripts from development branch. That way it is also tested another time in the wild 🙂.

**Comment by westfeld** [comment]
Is that the file you are suggesting to use in combination with the prestart and postup scripts?

https://github.com/pi-hole/pi-hole/blob/development/advanced/Templates/pihole-FTL.systemd

Do you have an idea when it will be merged into main?

**Comment by MichaIng** [comment]
Yes that file I mean. It's up to the Pi-hole team to decide when to do a new release, I'm just an occasional contributor 🙂.

**Comment by MichaIng** [comment]
Release just done, btw: https://discourse.pi-hole.net/t/pi-hole-ftl-v5-20-and-web-v5-18-released/59959

**Comment by dschaper** [comment]
We haven't released an update to the Core code yet.

**Comment by MichaIng** [comment]
Ah right, thanks for clarification, the systemd unit is mentioned in the threat below
> Notable Changes in the next release
