### ISSUE TITLE
Updating client of group via sql lite - not taking effect after restartdns

### ISSUE THREAD

**Issue by psyciknz** [pi-hole/pi-hole#5080]
### Versions

- Pi-hole:  5.14.2
- AdminLTE:  
- FTL:  v5.19.2

### Platform

- OS and version:  

- Platform:  unbuntu 20.04

### Expected behavior
Running 
```

pihole restartdns reload-lists
```

Is supposed to reload or flush any changes made to the groups according to https://docs.pi-hole.net/group_management/example/

So I assumed that any rules relating to those groups would take effect.  When client is in one group if only blocks one domain via regex.  So is relatively easy to determine it's not taking effect

The command is being run via script 
```

sudo sqlite3 "/etc/pihole/gravity.db" "update [client_by_group] set group_id = Group where client_id = Client" 
&& pihole restartdns reload-lists

```

Where group and client are variables.  Watching the database the values are moving as I expect.  But it doesn't seem to be enabling the change to take effect 
_A clear and concise description of what you expected to happen._

### Actual behavior / bug

The rules are not taking affect unless I load up the pihole web ui and on the same client remove from all groups and re-add it to the group that was set via query.

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Run scrip as above which contains restart dns command 
2. After switching to group 3 -which is just the domain block all ads are still being blocked 

## Debug Token

- URL:  https://tricorder.pi-hole.net/dYvg4dU2/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
> Where group and client are variables.

I'm almost sure sqlite3 doesn't accept variables.

Where did you see an example using variables?

**Comment by DL6ER** [comment]
> The rules are not taking affect unless I load up the pihole web ui and on the same client remove from all groups and re-add it to the group that was set via query.

This reads as if your client is member of multiple groups and you "fix" this by removing it from some groups on the web interface. As such, I'd say what you are trying to do with your script simply doesn't work and the web interface does something different for you. Mind that the table `client_by_group` has *uniqueness* on its records, i.e., if you have a client assigned to multiple groups, you cannot use `UPDATE` to change multiple records to become the same thing.

To help you further down the `UPDATE` track, we'd need to see the `client_by_group` table content after you ran your script and after fixing it manually through the web interface.

However, instead of using `UPDATE`,  you could also simply do this in two steps which seems more appropriate for your use case

``` sql
DELETE FROM client_by_group WHERE client_id = Client;
INSERT INTO client_by_group (client_id, group_id) VALUES (Client,Group);
```

to ensure the client will *only* be present in one group.

**Comment by psyciknz** [comment]
So at this stage I am ensuring the client is just in one group.  When I query on the client I'd it returns one record.

I want it in group 3 or group 0.  

This part of the code is working. 

What I'm unclear on, is there something else that happens when in the web ui, you apply any change.  It looks like, which isn't mentioned in the documentation, that some other, or as well, as the pihole restartdns reload-domains is being actioned.

**Comment by psyciknz** [comment]
@rdwebdesign variables are being supplied by iOS shortcuts.  They will be group Id 0 or group Id 3 and client is 5.  In the query they are just numbers. 

This part of it is working.   It's the applying of the change that does not seem to be working

**Comment by DL6ER** [comment]
Please check if, after running your script, FTL actually received the request to reload the lists. The log file `/var/log/pihole/FTL.log` should contains some lines like
```
[2022-12-21 09:28:14.186 2370296M] Reloading DNS cache
[2022-12-21 09:28:14.276 2370296/T2370313] Compiled 1 whitelist and 3 blacklist regex filters for 88 clients in 0.2 msec
[2022-12-21 09:28:14.276 2370296/T2370313] Blocking status is enabled
```

**Comment by psyciknz** [comment]
Ahh thanks for that.  You are indeed right. When I run my script it's not triggering anything in the ftl log.
