### ISSUE TITLE
pi-hole not showing client list, gets stuck at loading...

### ISSUE THREAD

**Issue by Renari** [pi-hole/pi-hole#5086]
### Versions

- Pi-hole:  5.14.2
- AdminLTE:  
- FTL:  5.20

### Platform

- OS and version:  Debian 11

- Platform:  Docker

### Expected behavior

_A clear and concise description of what you expected to happen._
Opening the client list shows the client list.
### Actual behavior / bug
Opening the client list stays at `loading...` forever.

_A clear and concise description of what the bug is._
```
datatables.min.js?v=1671659177:74 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at datatables.min.js?v=1671659177:74:386
    at k (datatables.min.js?v=1671659177:60:485)
    at Object.success (datatables.min.js?v=1671659177:61:194)
    at c (jquery.min.js?v=1671659177:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=1671659177:2:29072)
    at l (jquery.min.js?v=1671659177:2:80045)
    at XMLHttpRequest.<anonymous> (jquery.min.js?v=1671659177:2:82499)
 ```

### Steps to reproduce

1. Go to the dashboard
2. Click on clients
3. Scroll down to list of configured clients
4. See `Loading...` and the above error in the console

## Debug Token

- URL:   https://tricorder.pi-hole.net/BUKVogSP/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Renari** [comment]
I think there was something wonky with the `pihole-FTL.db` since restarting the container would always wipe all data, I removed the `pihole-FTL.db` and had pihole create a fresh one and now everything is working as expected.

**Comment by jrolfs** [comment]
For anyone else arriving here with these symptoms — I'll just confirm that removing `pihole-FTL.db` and having Pi-hole recreate it worked for me as well. Thanks, @Renari!
