### ISSUE TITLE
Unable to save due to hardcoded paths

### ISSUE THREAD

**Issue by AmirDahan** [pi-hole/pi-hole#5089]
### Versions

- Pi-hole:  v5.14.2
- AdminLTE:  v5.18
- FTL:  v5.20

### Platform

- OS and version:  Arch Linux

- Platform:  Raspberry Pi 4B

### Expected behavior

_A clear and concise description of what you expected to happen._

Updating settings from the admin panel should save and apply the settings.

### Actual behavior / bug

_A clear and concise description of what the bug is._

Settings do not get saved upon refreshing the page or changing tabs.

### Steps to reproduce

1. Go to pihole's settings tab
2. Change any setting and hit save
3. Refresh or change tabs

## Debug Token
Arch support is not available so i cannot provide a token
- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

Cause of the problem is missing permissions that can be easily fixed by changing the hardcoded /usr/bin/pihole command, To pihole command

Lines affected:
/srv/http/pihole/admin/scripts/pi-hole/php/func.php:155
/srv/http/pihole/admin/scripts/pi-hole/php/gravity.sh.php:37
/srv/http/pihole/admin/scripts/pi-hole/php/queryads.php:58
/srv/http/pihole/admin/scripts/pi-hole/php/savesettings.php:42

Additionally sudo should not be hardcoded and should check for doas if available

This bug happens because i use doas on my system instead of sudo and i'm granting the pihole user permission for ONLY the pihole command and nothing else
Another solution for this would be to grant the pihole user access to /usr/bin/pihole but i mean cmon
consistency
There are some lines that refer to pihole directly and some refer to it via it's actual path

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by dschaper** [comment]
Sorry, missed the Arch comment, 

>ArchLinux Pi-hole is not officially supported by Pi-hole project. In case of bugs and malfunctions please DO NOT file a report upstream.

https://aur.archlinux.org/packages/pi-hole-server?O=10&PP=10#comment-633053

**Comment by AmirDahan** [comment]
Oh shoot, My bad
Sorry!
