### ISSUE TITLE
New pi-hole version API changes

### ISSUE THREAD

**Issue by marcandrelevesque** [pi-hole/pi-hole#5090]
Pi-hole Pi-hole [v5.14.2](https://github.com/pi-hole/pi-hole/releases/v5.14.2) FTL [v5.20](https://github.com/pi-hole/FTL/releases/v5.20) Web Interface [v5.18](https://github.com/pi-hole/AdminLTE/releases/v5.18) made changes to their API.  

ref: https://github.com/pi-hole/AdminLTE/issues/2326
https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content

You need to update the plugin to make it works again with the latest version.

**Comment by yubiuser** [comment]
Wrong repo?

We don't have a plugin.

**Comment by marcandrelevesque** [comment]
Yes sorry! :)
