### ISSUE TITLE
Suggestion - integrate Group assignments into DHCP settings.

### ISSUE THREAD

**Issue by fruitwerks** [pi-hole/pi-hole#5101]
From the DCHP configuration page, allow the assignment of groups for active leases, as well as when setting up static reservations. This should be fairly easy as it is a few hooks and another relation entry in the database. Thanks!

**Comment by yubiuser** [comment]
Pull requests are welcome. Please open a feature request at https://discourse.pi-hole.net/c/feature-requests/8 where other users can also vote.

**Comment by fruitwerks** [comment]
Opening feature request.

**Comment by rdwebdesign** [comment]
> Opening feature request.

Writing this here will not create a Feature Request.

If you really want this, please open a feature request at https://discourse.pi-hole.net/c/feature-requests/8 where other users can also vote.
