### ISSUE TITLE
Generate debug log DoS lighttpd

### ISSUE THREAD

**Issue by Skinner927** [pi-hole/pi-hole#5102]
### Versions
```
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.18 (Latest: v5.18)
  FTL version is v5.20 (Latest: v5.20)
```

### Platform
- OS and version:  Ubuntu 22.04
- Platform:  Bare-metal x64 machine 

### Expected behavior

A debug log should be generated

### Actual behavior / bug

The log freezes at "Dashboard headers" every time.
Then `lighttpd` freezes/locks up and the entire web UI is inaccessible (even a local `curl http://127.0.0.1` just hangs) until I restart `lighttpd`.

### Steps to reproduce

1. Tools > Generate debug log
2. Leave all options unchecked
3. Click "Generate Debug Log"

## Debug Token

- URL:  https://tricorder.pi-hole.net/k8zCIey3/

### Screenshots

![image](https://user-images.githubusercontent.com/1518323/210128194-bb01f9c5-d034-45a4-8144-8466fc80c740.png)

### Additional context

This is a brand new install.

`pihole -d -w` runs fine in the terminal.

I have uninstalled pihole, lighttpd, and php, wiped `/etc/www`, `/etc/httpd`, and the error still happens exactly the same.

CPU and RAM do not spike at all. System looks as "normal" as it ever does.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.15
