### ISSUE TITLE
Install script produces strange output

### ISSUE THREAD

**Issue by dan019** [pi-hole/pi-hole#512]
Hello,
While running the install script, I'm prompted with a strange output.
I have not seen these in the past when installing pi-hole from scratch. What does it mean?

` The mail frontend needs a installed 'sendmail', using pager`

Thanks have an excellent day,
Daniel

**Comment by Mcat12** [comment]
Pastebin the whole install log (it can be found at `/etc/pihole/install.log`)

**Comment by dan019** [comment]
Wish I hadn't closed the ssh session I could have pasted the error from install. Unfortunately, this log does not show any such error. BTW, using Rasbian lite.

http://pastebin.com/2LgvBmmV

**Comment by Mcat12** [comment]
Where in the log did that show up?

**Comment by dan019** [comment]
In the Checking dependencies section. After the script discovered the package was missing and needed to be installed.

**Comment by Mcat12** [comment]
Which package?

**Comment by dan019** [comment]
Surprisingly all of them. I noticed this in the past, but only in my recent install did I wonder if anyone else using a RPI3 with Rasbian lite was getting this too.

**Comment by Mcat12** [comment]
Try running `sudo apt-get -y -qq install git > /dev/null` (you could replace `git` with a different dependency). Does that message pop up?

**Comment by Mcat12** [comment]
It seems to be some warning from apt... I don't know why it would appear only to you.

**Comment by Mcat12** [comment]
If it does appear after running that, try running it without the null redirect (`sudo apt-get -y -qq install git`) and check if it gives any more clues as to why it's outputting that.

**Comment by Mcat12** [comment]
It appears to be something outside of Pi-hole though.

**Comment by dschaper** [comment]
Hi, there's a couple of checks I'd like to run through on this. Can you give us the URL for the download location you are using to get Raspbian? Just want to use the same image that you are using. 

There looks to be an issue with the mail subsystem, so we'll need to run apt-cache policy on the sendmail and pager packages to see if we get matching candidates for install. I'm thinking this is going to be an issues outside of the Pi-hole, but let's be sure.

**Comment by dan019** [comment]
https://downloads.raspberrypi.org/raspbian_lite_latest

Perhaps there's a bug with Rasbian's apt program. I'm not clear on what is the mail subsystem on linux. However, the output does appear without affecting the pihole install. So that's a good thing

**Comment by dschaper** [comment]
Can you pastebin a copy if the output from the following:

`apt-cache policy sendmail`
`apt-cache policy pager`

**Comment by dan019** [comment]
As requested:
http://pastebin.com/duMAis5g

**Comment by dschaper** [comment]
Thanks, I get the same from a fresh install of Raspbian Lite Jessie. Do you get this error for every `apt` call? (Does an `apt-get update` show the same error?) And is this a fresh install of both Jessie and Pi-Hole or have there been any other packages or changes made prior to the install of the Pi-Hole?

That error message is kind of unique, with the grammatical error in it, and it looks like it's an error that comes from the `apt-listchanges` program. I'm wondering if there is something glitchy in apt cache. Can you run `sudo apt-get clean` and see if the problem persists?

If it does then try `sudo apt-get check` and see what that comes back with as it's results. May have to run a `apt-get -f install` but that really will only work if there are dependency issues.

**Comment by dan019** [comment]
I got this error for every apt call during pi-hole installation dependency check. This was a fresh install. I only ran `raspi-config` to expand the filesystem, set the locale to UTF-8, and change to my timezone.

Are you suggesting trying to run `sudo apt-get clean` before installing installing pi hole on rasbian lite?

**Comment by dschaper** [comment]
No, I was checking to see if you got the same error message for any `apt` call you are doing now. Or have you tried a new fresh install and you are seeing the same issue? 

I tried an install with the latest Raspbian Lite and it all looked okay. It appears that the need to expand the filesystem isn't there anymore, as possibly the filesystem is expanded on first boot automatically. (At least I was seeing the /root partition to be fully expanded without needing to run `raspi-config`.) 

If you ran `apt-get install <insert package here>` for a new package now, would you still get that error?

**Comment by dan019** [comment]
When I  ran `sudo apt-get install tmux` I did not see any error. 
I will rewrite the rasbian lite image tomorrow and get back to you with the results.

**Comment by dschaper** [comment]
Thanks!

**Comment by dan019** [comment]
Running sudo apt-get -y -qq install git in the terminal outputs the same error.
Curious I read the man page for the apt-get program and the the  apt-get command should not combine -qq with -y as -qq implies yes. Furthermore it also states that

> never use -qq without a no-action modifier such as -d, --print-uris  or -s as APT may decide to do something you did not expect.

Should we change:
`sudo apt-get -y -qq install git `
`sudo apt-get -y -q install git `


After trying this it removed the error message.

**Comment by dschaper** [comment]
Thanks for the updates on the apt usage, we'll take a look at that... As for the error, did the problem get solved or was the error message simply quashed and the problem is still there is a question I have...

**Comment by dschaper** [comment]
Did you try this on the new Raspbian image or the old one? I know it's an odd question but just making sure of the current configuration.

**Comment by dan019** [comment]
Tried the test on a new Rasbian image, still got the error output.

**Comment by dschaper** [comment]
Would it be possible to download a fresh image from the Raspbian website? I've tried to recreate the error condition and I just cant seem to get a new setup to error out with the `apt` subsystem. And with the new image, try doing a `df -h` before you run `raspi-config` and see if you are getting the auto-resize function to work.

**Comment by dan019** [comment]
Ok, I got another fresh image of Rasbian lite. Before running the `raspi-config`, I had 1.2g and after 7.2g

**Comment by dschaper** [comment]
Hmmm, looks like they have increased the size of root in the shipping image, must still be testing the expansion of the partition on first boot. I know there are some changes to the WPA configuration though. The important question though is how the Pi-Hole install went' and did you see the same error messages with the newly downloaded Raspbian Lite?

**Comment by dan019** [comment]
Just downloaded a new fresh Rasbian lite image and booted it on my RPI3.

Here's the errors still
http://pastebin.com/jNQGr0V0

**Comment by nate-ubiquisoft** [comment]
Wow I know this one actually. `sendmail` is used by apt-get to "write" to /var/spool/mail as a way to log apt-get commands. Lite does not ship with `sendmail` installed because postfix is not installed

**Comment by dschaper** [comment]
But I'm unable to recreate the error conditions with a fresh install. `apt-cache policy` shows `sendmail` and `postfix` as not being installed with Jessie Lite, @dan019 can you do an `ls -lac /var/spool/mail` and post it up? @nate-ubiquisoft So Raspbian is trying to use the system pager instead?

**Comment by dan019** [comment]
Results of  the command:
`lrwxrwxrwx 1 root root 7 May 27 07:41 /var/spool/mail -> ../mail`

**Comment by dschaper** [comment]
Hmmm, do you have a `mail` user in your `/etc/passwd` file? And does `/var/mail` look like:

    pi@raspberrypi:/var/mail $ ls -lac /var/mail
    total 8
    drwxrwsr-x  2 root mail 4096 Feb  9 16:05 .
    drwxr-xr-x 12 root root 4096 Mar  9 18:00 ..

**Comment by dschaper** [comment]
And I just noticed, my file dates are Feb 9, which matches the build date of `uname -a`. You have different access dates? What does `uname -a` show as the build date?

**Comment by dan019** [comment]
Basically:
http://pastebin.com/khGe11LM

**Comment by dschaper** [comment]
Thanks, let me take a deeper look here, and see, it looks like one of the files was touched today. I'll have to see if I can pick up a 3B tomorrow (or possibly later tonight) to do an exact duplicate test. All my 3B's have other OS on them right now and are in use.

**Comment by dschaper** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=121892&start=325#p989736

**Comment by dan019** [comment]
I'm still getting the error on a 3B with Rasbian Jessie and Rasbian Jessie Lite.  This is currently the command used during the install:
`sudo apt-get -y -qq install git `
The problem is two q's conflicted with the y switch.

**Comment by dan019** [comment]
I'm still getting the error on a 3B with Rasbian Jessie and Rasbian Jessie Lite.  This is currently the command used during the install:
`sudo apt-get -y -qq install git `
The problem is two q's conflicted with the y switch.

**Comment by LucasRoot** [comment]
Getting the same error with Raspberry Pi 2.

bash: line 239: /etc/pihole/piholeIP: Permission denied
::: Using IPv4 on 192.168.1.45/24
::: IPv6 will NOT be used.
::: Using Google DNS servers.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... Not found! Installing.... [|]  Can't set locale; make sure $LC_* and $LANG are correct!
The mail frontend needs a installed 'sendmail', using pager
 [/]  perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "pt_BR.UTF-8",
	LC_MONETARY = "pt_BR.UTF-8",
	LC_CTYPE = "pt_BR.UTF-8",
	LC_ADDRESS = "pt_BR.UTF-8",
	LC_TELEPHONE = "pt_BR.UTF-8",
	LC_NAME = "pt_BR.UTF-8",
	LC_MEASUREMENT = "pt_BR.UTF-8",
	LC_IDENTIFICATION = "pt_BR.UTF-8",
	LC_NUMERIC = "pt_BR.UTF-8",
	LC_PAPER = "pt_BR.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
 [-]  locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
 [-]  E: Sub-process /usr/bin/dpkg returned an error code (1)
 done!
:::    Checking for php5... Not found! Installing.... [/]  Can't set locale; make sure $LC_* and $LANG are correct!
The mail frontend needs a installed 'sendmail', using pager
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "pt_BR.UTF-8",
	LC_MONETARY = "pt_BR.UTF-8",
	LC_CTYPE = "pt_BR.UTF-8",
	LC_ADDRESS = "pt_BR.UTF-8",
	LC_TELEPHONE = "pt_BR.UTF-8",
	LC_NAME = "pt_BR.UTF-8",
	LC_MEASUREMENT = "pt_BR.UTF-8",
	LC_IDENTIFICATION = "pt_BR.UTF-8",
	LC_NUMERIC = "pt_BR.UTF-8",
	LC_PAPER = "pt_BR.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
 [-]  locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
 [\]  E: Sub-process /usr/bin/dpkg returned an error code (1)
 done!
:::    Checking for git... Not found! Installing.... [\]  Can't set locale; make sure $LC_* and $LANG are correct!
 [|]  The mail frontend needs a installed 'sendmail', using pager
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "pt_BR.UTF-8",
	LC_MONETARY = "pt_BR.UTF-8",
	LC_CTYPE = "pt_BR.UTF-8",
	LC_ADDRESS = "pt_BR.UTF-8",
	LC_TELEPHONE = "pt_BR.UTF-8",
	LC_NAME = "pt_BR.UTF-8",
	LC_MEASUREMENT = "pt_BR.UTF-8",
	LC_IDENTIFICATION = "pt_BR.UTF-8",
	LC_NUMERIC = "pt_BR.UTF-8",
	LC_PAPER = "pt_BR.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
 [/]  locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
 [|]  E: Sub-process /usr/bin/dpkg returned an error code (1)
 done!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::    Checking for sudo... already installed!
:::
::: Stopping services... done.

**Comment by dschaper** [comment]
Strange, now there are locale issues... I'm trying to reproduce the error and I'm not having any kind of luck. I'll keep looking at it though.

**Comment by dschaper** [comment]
How are you setting your locales?

**Comment by LucasRoot** [comment]
I used raspi-config > Internationals

**Comment by dschaper** [comment]
There may be a bug in `raspi-config`. Can you show me the `/etc/default/locale` please?

**Comment by LucasRoot** [comment]
#  File generated by update-locale
LANG=en_GB.UTF-8

**Comment by dan019** [comment]
The contents of my locale are:
`
#  File generated by update-locale
LANG=en_US.UTF-8
'

**Comment by dschaper** [comment]
And what does `locale -a` look like? (Are you both seeing the Perl and Locales issues?)

**Comment by LucasRoot** [comment]
locale: Cannot set LC_CTYPE to default locale: No such file or directory
C
C.UTF-8
en_GB.utf8
POSIX

PS: Pi hole isn't working

**Comment by dschaper** [comment]
Okay @LucasRoot try `sudo dpkg-reconfigure locales` and select your locale. Reboot after the locales are regenerated. Then try the Pi-Hole install script again.

**Comment by LucasRoot** [comment]
Ok, I'll try, thanks a lot for the support!

**Comment by LucasRoot** [comment]
Here we go
This time I tried running as sudo.
http://pastebin.com/raw/p1PdEMkp

**Comment by dschaper** [comment]
Locales still are off. Try 

```
export LANGUAGE=pt_BR.UTF-8
export LANG=pt_BR.UTF-8
export LC_ALL=pt_BR.UTF-8
locale-gen pt_BR.UTF-8
dpkg-reconfigure locales
```

You may need to `sudo` those to get them to work. And reboot after its completed. Then if we could see the output from `locale -a` and `locale`.

**Comment by LucasRoot** [comment]
Here: http://pastebin.com/raw/ZEsHS77b

**Comment by dschaper** [comment]
This seems to be an issue with the locale subsystem and not with the Pi-Hole, however can you try the help from https://forum.zentyal.org/index.php?topic=4108.0 and see if that helps in any way?

**Comment by LucasRoot** [comment]
The erros are gone now!
Thanks a lot!
The Pi Hole is working now :)

**Comment by dschaper** [comment]
Great!

**Comment by PromoFaux** [comment]
@dschaper is this the same as
