### ISSUE TITLE
403 Forbidden on IP-address

### ISSUE THREAD

**Issue by rwkstgtd** [pi-hole/pi-hole#5125]
Hello, when opening http://192.168.0.x (IP-address of Pi-hole) I get "403 forbidden". Opening http://pi.hole works fine but redirects straight to the admin login. Before the last update (yesterday) both ip and host-name brought up a landing page asking if I ment to call the admin interface. This page apparently exists no more. I see this behaviour on two different installations, so either I made the same mistake twice (while upgrading), or something's wrong with the original landing page since yesterday's update.
Cheers, R.

**Comment by Toyboy125** [comment]
open ip adress with /admin after it.
http://192.168.0.x/admin

**Comment by rwkstgtd** [comment]
I'm well aware of this. But if you called pi.hole before without /admin, your first guess is, that something went wrong with the update. Ich spent some time checking lighthttp service and so on. It's not expected behaviour anyway.

**Comment by PromoFaux** [comment]
It's all in the release notes.

https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/

>But if you called pi.hole before without /admi

Pi.hole aways has redirected to admin.

It is expected behaviour if you read the release notes.

**Comment by rwkstgtd** [comment]
Thanks for pointing the release notes out, it's there, sorry to miss that. Pi.hole hast not always redirected to /admin, that is the whole point of my post, it changed exactly with the last release. But since this is intentional, there is no point in posting a bug report. I see this.

**Comment by PromoFaux** [comment]
I can 100% assure you that the address `http://pi.hole` has _always_ redirected to `/admin`

What never did redirect to admin was `http://ipaddress`, which instead showed a splash screen/error page saying "Did you mean to go to /admin?"

I don't expect everyone to read every comment we make on every platform (that would be silly!) but I went into a _little_ more detail here: https://old.reddit.com/r/pihole/comments/10ctmiq/pihole_ftl_v5201_web_v5181_and_core_v515_released/j4ibr9u/

**Comment by rwkstgtd** [comment]
OK, i see. I called pi.hole always via IP and I always saw the splash. From the reddit post I learn, that there was a good reason to change that. Only problem is, that probably 50% percent of all people will call the IP first after fresh install. Few people will read any hint that they should call /admin and even fewer will expect Pi-hole to be found under pi.hole. This only beeing the case if you already modified your DNS settings. So the best solution would probably be, to redirect any host/ip to /admin regardles of the actual url. But sorry to bother you, you're dooing a great job with Pi-hole and for me it's fine, as it is. I know now, where to find the interface.
