### ISSUE TITLE
403 Forbidden on web

### ISSUE THREAD

**Issue by andyxheli** [pi-hole/pi-hole#5126]
### Versions

- Pi-hole:  5.15
- AdminLTE:  5.18.1
- FTL:  5.20.1

### Platform

- OS and version:  Ubuntu 22.0.4

- Platform:  Vm

### Expected behavior

Should open URL web page that shows pi logo

### Actual behavior / bug

Getting an 403 error

### Steps to reproduce

Go to http://10.32.3.2 then get the error. 

When i go to http://10.32.3.2/admin it works

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by andyxheli** [comment]
Your debug token is: https://tricorder.pi-hole.net/4TrnLu1P/

**Comment by PromoFaux** [comment]
https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/
