### ISSUE TITLE
Pihole update changes lighttpd.conf

### ISSUE THREAD

**Issue by CorvusGei** [pi-hole/pi-hole#5127]
### Versions
- Pi-hole:  5.15
- AdminLTE:  5.18.1
- FTL:  5.20.1

### Platform
- OS and version:  Raspberry OS based on Debian GNU/Linux 11 (bullseye)
- Platform:  Raspberry Pi, running outside of Docker

### Expected behavior

After updating Pihole I would expect that my custom configuration for lighttpd will be kept. (custom port)

### Actual behavior / bug

After updating Pihole my custom configuration for lighttpd is overwritten to standard http port 80. If I use a custom configuration a simple update must not change it to default again!

### Steps to reproduce

Just update Pihole with 'pihole -up'

## Debug Token

- URL:  not needed / Debug Log provides too much sensitive information

### Screenshots

not needed

### Additional context

Thank you.

**Comment by PromoFaux** [comment]
https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

**Comment by CorvusGei** [comment]
Thanks for your answer.
So I think I should configure my custom port in external.conf with
server.port := portnumber
I changed my configuration, but as my Pihole is up to date, I can't test it at the moment.

**Comment by PromoFaux** [comment]
Instead of `external.conf`, create a file in `/etc/lighttpd/conf-enabled/` (e.g `custom-port.conf`) with the `server.port:=` line

**Comment by CorvusGei** [comment]
thanks, I tried with the latest update, it worked.
Thank you very much for your help.
