### ISSUE TITLE
Pi hole slows down my connection?

### ISSUE THREAD

**Issue by a-r-k** [pi-hole/pi-hole#513]
Hi!

I installed Pi Hole on a Raspberry Pi and it basically works quite nice in my network.

Except: It seems it is slowing down some pages, such as:

1. Youtube (sometimes not working at all)
2. Facebook (after clicking a link, it takes nearly forever to open it)
3. Google Drive (tries to contact the server clients6.google.com; and although this address has been whitelisted, connecting to it is impossible [through Safari error console])

I already tried setting another DNS server (such as 8.8.8.8 or else) and this behaviour immediately stopped appearing.

I suspect that the connection is slowed down as soon as Pi Hole is blocking something...

Any advice?

**Comment by Mcat12** [comment]
Since Pi-hole is a DNS server, not a proxy, your network should not be limited by the speed of the pi's network adapter. The most likely things that could be the cause of the slowdown are either long ping times to the pi or something causing the browser to timeout on the connection to the pi (maybe the pi's response is not getting to the browser or the browser is acting weird). Check how long it takes to ping the device. Also run `pihole -d` and pastebin `/var/log/pihole_debug`. Also check if this happens on any of your other devices.

**Comment by a-r-k** [comment]
[Pastebin of `pihole_debug.log`](http://pastebin.com/X8MGnSB6)

The problem occurs on all devices (tried with iOS, Mac OS, Windows).

**Comment by Mcat12** [comment]
Are you able to try a reinstall? Run `pihole uninstall` and then reinstall with `curl -L https://install.pi-hole.net | bash`.

**Comment by a-r-k** [comment]
Reinstalled Pi Hole. Youtube is working fine now, but links from Facebook still take much longer to open...

**Comment by Mcat12** [comment]
Run the debug script again and pastebin the log. If you try to connect to doubleclick.net, does it resolve quickly? You can use the dev tools in your browser to check how long it took to load.

**Comment by PromoFaux** [comment]
I notice you've added some additional upstream servers to `/etc/dnsmasq.d/01-pihole.conf`.. I don't know if that would affect resolution speed?

Additionally, it's probably worth adding those to something like `/etc/dnsmasq.d/02-custom.conf` (this will still get loaded by dnsmasq) as any customisations to the pihole file are likely to get wiped in updates.

**Comment by a-r-k** [comment]
@Mcat12 doubleclick.net loads quickly but it seems to load a placeholder page of lighttp... Is that behavior intended? [Here's the pastebin.](http://pastebin.com/KFa7Av6T)

@PromoFaux I wanted to be able to access OpenNIC, too. So I added these server in the `/etc/dnsmasq.d/01-pihole.conf`. Thanks for your suggestion, right now I am trying Pi Hole without any modifications.

**Comment by PromoFaux** [comment]
RE: doubleclick, yeah that's intended behaviour. The idea is we serve a blank html page (as a 404) instead of the ad (which doesn't exist on the pi)

Sure, have you tried a speed check with and without the additional servers?

**Comment by a-r-k** [comment]
Okay, right now it seems to be working fine. The measured speed is not significantly less compared Pi Hole to any other public DNS server compared to the OpenNIC servers.

So, it seems to be fine now. Thanks for your help!
