### ISSUE TITLE
How to update to latest version?

### ISSUE THREAD

**Issue by josemalone** [pi-hole/pi-hole#514]
Forgive me for such a basic question. In the past you recommended a new install. Wondering if this is still the preferred method?

Thanks!

-Jose 

Pi-hole Version v2.5.3 Web Interface Version v1.2

**Comment by jacobsalmela** [comment]
It shouldn't be basic!  

Yup, just run the installer again:
```
curl -L https://install.pi-hole.net | bash
```
We're just a bunch of coding bandits who haven't implemented our [update mechanism](https://github.com/pi-hole/pi-hole/pull/393) yet.  Although, we are working on [revamping the code](https://pi-hole.net/py-hole-plus-our-youtube-channel/) so this will be easier.

**Comment by Mcat12** [comment]
Yep. Until we finish implementing the update scripts, just run `curl -L https://install.pi-hole.net | bash` to update.
