### ISSUE TITLE
Placeholder page

### ISSUE THREAD

**Issue by lokomass** [pi-hole/pi-hole#5146]
Hi all,

I have installed latest version of Pihole on a debian server.
If I'm going to the ip page (http://192.168.1.10), I've see this 

![image](https://user-images.githubusercontent.com/7886368/214055995-305df43d-7ab0-4ac7-9b60-9d9cbf4541e4.png)

With another version (5.14.2) on another debian server, I had an other page 
![image](https://user-images.githubusercontent.com/7886368/214056366-43d2d9aa-0dfd-4fb0-804c-af0143be5ede.png)

When I compare public folders, the second server has a pihole foler in /var/www/html, the first doesn't.
Is this normal ?
Thanks

**Comment by PromoFaux** [comment]
Please read the release notes before updating/reporting an issue.

https://pi-hole.net/blog/2023/01/22/pi-hole-web-v5-18-2-and-core-v5-15-1-released/
