### ISSUE TITLE
Error when checking for updates: Web Admin repo is missing from system (On Apache + Debian11)

### ISSUE THREAD

**Issue by RomelSan** [pi-hole/pi-hole#5156]
### Versions
Pi-hole version is v5.15.3 (Latest: v5.15.3)
AdminLTE version is v5.18.3 (Latest: v5.18.3)
FTL version is v5.20.1 (Latest: v5.20.1)

### Platform
Debian 11 
Pihole is No Docker
Web Server is Apache2

### Description
Check for updates displays the following error:
```
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date

  Error: Web Admin repo is missing from system!
  Please re-run install script from https://pi-hole.net
```
![image](https://user-images.githubusercontent.com/11341002/216218171-14a5719c-9c26-4752-b226-26d7ec19e415.png)

File permissions for web folder are www-data:www-data
pihole is added to www-data group.

**Comment by yubiuser** [comment]
Two remarks: Apache is unsupported (only lighttpd is) and you did not post a debug token as the help template requested. 
_

In the updater, there is a check if you installed the web interface.

https://github.com/pi-hole/pi-hole/blob/c7ad7113d70f63b0b4a5460daaf5ada8f10c28f4/advanced/Scripts/update.sh#L131-L145

What is the content of `/etc/pihole/setupVars.conf`?

**Comment by RomelSan** [comment]
/etc/pihole/setupVars.conf
```
BLOCKING_ENABLED=true
WEBPASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxx
PIHOLE_DNS_3=2606:4700:4700::1111
PIHOLE_DNS_4=2606:4700:4700::1001
DNSSEC=false
REV_SERVER=true
REV_SERVER_CIDR=192.168.0.0/24
REV_SERVER_TARGET=192.168.0.1
REV_SERVER_DOMAIN=edited.com
IPV4_ADDRESS=192.168.0.91/24
IPV6_ADDRESS=2800:XXXxxxxxxxx
PIHOLE_INTERFACE=ens192
PIHOLE_DNS_1=1.1.1.1
PIHOLE_DNS_2=1.0.0.1
QUERY_LOGGING=true
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=false
CACHE_SIZE=10000
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSMASQ_LISTENING=single
```

**Comment by RomelSan** [comment]
Managed to fix this...
I had to:
```
sudo git config --global --add safe.directory /var/www/html/admin
```
![image](https://user-images.githubusercontent.com/11341002/216431048-2d554f5d-fb45-4b9a-92a3-bf29533b2254.png)

**Comment by yubiuser** [comment]
Mhh.. this fix reminded me of:
https://github.com/pi-hole/pi-hole/issues/4759

But `pihole -up` should require `sudo` so you should have had enough privileges check if the web interface is a a repo....

**Comment by RomelSan** [comment]
Indeed, even called `pihole -up` as root but it didn't work.
My git version is `git version 2.30.2`.

"This is because /var/www is owned by www-data, who is not a sudo user, and so access is restricted"
got this from: https://learnshareit.com/how-to-solve-fatal-detected-dubious-ownership-in-repository-in-git/

**Comment by yubiuser** [comment]
Maybe we need to add `git config --global --add safe.directory /var/www/htlm/admin` to the installer...

**Comment by produktive** [comment]
I found this thread by searching for this error, and it seems I may have the same problem. Running on nginx instead of lighttpd.

**Comment by RomelSan** [comment]
Did the git command solve the problem?

**Comment by produktive** [comment]
Yes

**Comment by dschaper** [comment]
> Maybe we need to add `git config --global --add safe.directory /var/www/htlm/admin` to the installer...

I've very hesitant to do that. 

I notice that these reports are with webserver daemons that are not the `lighttpd` that we use. That may cause the user running the update checks to be different than we expect and not have the permissions to access the directories that our `lighttpd` setup has.

**Comment by RomelSan** [comment]
I know that lighttpd is the only engine supported.
But for the rest of us... maybe add a warning after selecting "No"... in the following screen.
![image](https://user-images.githubusercontent.com/11341002/217131863-9ecf8b57-7073-4041-b3b5-7d52fcb3ce4f.png)
The warning should say... You must run this command so the updates can work: 
```
git config --global --add safe.directory /var/www/htlm/admin
```
![image](https://user-images.githubusercontent.com/11341002/217133151-17f2d49c-61b7-4973-bb58-6a0e7a34cfb3.png)

```
whiptail --title "Warning" --msgbox "If using other web engine you must run the following line: git config --global --add safe.directory /var/www/htlm/admin" 8 65
```

**Comment by dschaper** [comment]
Is the web server user a member of the `pihole` group as the current display states is necessary?

**Comment by dschaper** [comment]
> The warning should say... You must run this command so the updates can work:

I'm not in favor of telling users to enter that command.

**Comment by RomelSan** [comment]
It is a pihole member
![image](https://user-images.githubusercontent.com/11341002/217134587-6d0326ea-77c9-4600-b908-b2619ac16d71.png)
Did not work... As root didn't work too.
Adding the safe directory config works.

**Comment by kernelpanic85** [comment]
I just got this error too today when trying to update and the git command fixed it for me too
`sudo git config --global --add safe.directory /var/www/html/admin`

**Comment by TimH54** [comment]
I am also using apache2 and this quick-fix also worked for me. I wonder, though, why did it become necessary only recently - update checks used to work just fine!? If pi-hole code is updated so that this quick-fix is no longer necessary, I would appreciate if you let us know here so that we can revert this change of the git config.

**Comment by rdwebdesign** [comment]
This is a `git` change.

**Comment by r0h1n** [comment]
Faced the same issue with Nginx/Ubuntu, but fixed after applying 

`sudo git config --global --add safe.directory /var/www/html/admin`

**Comment by pcnate** [comment]
I just encountered the same problem with the admin repo. I worked around it by following the guide to rerun the script but that failed so I renamed the admin directory to admin-old and reran it. That seemed to work. Unsure how it would have not detected the directory while it did exist. Maybe something got deleted. Anyways, the directory still exists and I'm sure the logs still apply so I could dig up info if necessary.

**Comment by qwrty-ftw** [comment]
Same error with Debian and latest Debian 11.7 released (include Git update 1:2.30.2-1+deb11u2) 
Fix this by adding /var/www/html/admin in safe.directory.

**Comment by farkass** [comment]
> Maybe we need to add `git config --global --add safe.directory /var/www/htlm/admin` to the installer...

This is just solved the issue at updating to FTL [v5.21] ·and Web Interface [v5.18.4] fo rme

**Comment by TheRogueChivalry** [comment]
> > Maybe we need to add `git config --global --add safe.directory /var/www/htlm/admin` to the installer...
> 
> This is just solved the issue at updating to FTL [v5.21] ·and Web Interface [v5.18.4] fo rme 


Maybe we need an option for the installer to setup lighttpd with a different port. That way people can run apache, nginx, or whatever web server without conflicts. That's what I am doing right now. One of the main developers already said not in favor of that command.

**Comment by shikari7** [comment]
My pihole -up has been successful for many weeks - I run it at least weekly - until suddenly today I get this same issue.  I tried the sudo git config and that has not helped.

pihole -v I get:
  Pi-hole version is N/A (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

pihole seems to be working nevertheless.  I am using the default setup, running lighthttpd.

Linux pihole 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux

**Comment by romerojhh** [comment]
I ran into the same problem. 

I used Apache2 webserver with Raspberry Pi OS. Running `git config --global --add safe.directory /var/www/admin` does not work either (note: I moved the web interface folder to /var/www/).

For context, I am also running the web interface on internal port 81 but I think that should not be a problem
