### ISSUE TITLE
Local DNS queries are affected by external ipv6 DNS records

### ISSUE THREAD

**Issue by Terrails** [pi-hole/pi-hole#5158]
### Versions

- Pi-hole:  5.15.3
- AdminLTE:  5.18.3
- FTL:  5.20.1

### Platform

- OS and version:  Raspbian 11 (bullseye)

- Platform:  Raspberry Pi

### Description
I have a subdomain that I am exposing via cloudflared tunnel which I would also like to access directly when in LAN by connecting directly to the LAN ip of the reverse proxy (ngnix). In order to do this I added a local DNS record that points to the local address of the reverse proxy. 
Let's say that the cloudflared tunnel is down and that connecting to the url without any local DNS records in pi-hole would redirect us to a cloudflare website saying that the tunnel is down.

### Expected behavior
Opening the URL with pihole set as the DNS server should send us to the desired website using the local IP of the reverse proxy.

### Actual behavior / bug
Opening the URL actually sends us to cloudflare's website telling us the cloudflared tunnel is down. Bypassing the local DNS record in pihole.
The actual issue after running nslookup on a device using pi-hole is that pi-hole returns the given ipv4 address from local DNS records, but there are also some extra ipv6 addresses that point to cloudflare and I am assuming that the browser prioritizes those instead of ipv4. Removing that subdomain CNAME from cloudflare DNS settings fixes this issue, but it also disables the cloudflare tunnel for that subdomain.

Result of nslookup with CNAME records being present on cloudflare
![WindowsTerminal_2023-02-02_17-33-53_(Command_Prompt)_hXJb](https://user-images.githubusercontent.com/8273440/216386423-4eaeb92f-5714-42ce-8ace-bcdd46aa4c91.png)

Result of nslookup without CNAME records on cloudflare
![WindowsTerminal_2023-02-02_17-37-28_(Command_Prompt)_Oa4D](https://user-images.githubusercontent.com/8273440/216386499-cf8e8009-74cd-48b5-a0ec-4c6fc5c06573.png)

**Comment by terasolu** [comment]
Disabling AAAA queries is not a solution, it is merely a workaround. I am facing the same issue as my networks is IPv6 only. Setting a local AAAA record will only add it to the remote AAAA records instead of replacing them. In a lot of cases this is sufficient, but not for Cloudflare tunnels or reverse proxies.

**Comment by telnetdoogie** [comment]
does this still work in pihole 6?

I'm attempting to add an entry to `/etc/dnsmasq.d/09-custom-hosts.conf` with

`address=/this.domain.com/::` 

but it's still doing this same thing - I have the same situation where local records come back correctly but it's augmented with public IPv6 records from cloudflare which breaks the cert validation in the browser when using my hosted app locally.
