### ISSUE TITLE
Youtube ads are all of a sudden getting pass the blacklist?

### ISSUE THREAD

**Issue by cwissO** [pi-hole/pi-hole#516]

**Comment by Mcat12** [comment]
Video ads or website ads?

**Comment by Mcat12** [comment]
The video ads seem to be blocked, only a black screen for a few seconds, but I'm not sure if the black screen is supposed to be there or not...

**Comment by cwissO** [comment]
Video ads and site ads are now displayed again on Youtube. There is no delay anymore on videos so the ads are blocked (which I was fine with), instead it will go straight to ad > video.

**Comment by cwissO** [comment]
Weird! It fixed itself after some time. I didn't change anything, all I did was browse around for a few hours and went to youtube to check the issue again and it started blocking again.

**Comment by dschaper** [comment]
Sounds like possibly the ad serving domain got into the clients resolver cache and it just needed to time out. When the entry timed out and the client looked up the domain again it got the Pi-Hole this time and blocked like it should. If it happens again, try flushing the cache on the client...
