### ISSUE TITLE
CLI pihole query does not consider groups

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pi-hole/pi-hole#5171]
### Versions
- Pi-hole:  v5.15.5
- AdminLTE:  v5.18.4
- FTL:  v5.21

### Platform
- OS and version: Debin Bullseye
- Platform:  Raspberry Pi

### Expected behavior
`pihole query` should (have the option to)  consider user groups as well. It seems that this function was forgotten after group management was introduced.

### Actual behavior / bug
`pihole query` does not have any option to consider groups.

### Steps to reproduce

1. run `pihole query -h`
2. No option to add groups
3. Block a domain for a group only
4. Verify that domain is blocked only for that group by querying from devices in or not in the group
5. run `pihole query <that domain>`
6. Notice that it does not consider which group the domain was in

## Debug Token

- URL:  https://tricorder.pi-hole.net/RERdaKTl/

_Note that I did reverse proxy from caddy to pihole. That is not related to this issue_

### Screenshots
![Screenshot_2023-02-11-20-17-53-200_com.termux-edit.jpg](https://user-images.githubusercontent.com/64138578/218257590-2d597ba7-adaa-4940-9d60-ba106b50439f.jpg)

### Additional context
Some of us use group management to create a bypass group where nothing would be blocked for some of the devices, or customize blocklist for every devices (e.g. different for childrens and parents). `pihole query` does not care which group is being queried, so non-relevant or sometimes misleading infomation would be returned. It does really seems that this command was forgotten after group management was introduced.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by SodaWithoutSparkles** [comment]
Ok. Would you mind telling me where's the source code responsible for handling this pihole query command?

**Comment by rdwebdesign** [comment]
The option calls this function:
https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/pihole#L96-L100

The function executes the code from https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/query.sh

**Comment by SodaWithoutSparkles** [comment]
Thanks, and confirm that all groups related information is in `gravity.db` not `pihole-FTL.db`? 

If so I could try to do this in my free time, which I probably won't have in the near 3 months.

<details>
<summary>Note to self</summary>
Assuming they are in gravity.db, modifying the first link to accept one more arg for group. Maybe also add a option to rev-lookup group from client. Then modify SQL to add another LIKE, or, OR matching group. Repeat if client has 1+ groups. This may change if DB structure is not what I imagined, so check the DB structure docs as well.

Maybe time to find a software to dump DB in more human-readable way... MS excel?

Edge case: 

- group has nothing assigned
- group has 1+ assigned
- client has 1+ group assigned
- no extra args passed
- too many args passed

</summary>

**Comment by jfb-pihole** [comment]
> confirm that all groups related information is in gravity.db not pihole-FTL.db

Correct.

**Comment by yubiuser** [comment]
> Maybe time to find a software to dump DB in more human-readable way... MS excel?

https://discourse.pi-hole.net/t/export-to-excel/54260/6?u=yubiuser

**Comment by rdwebdesign** [comment]
> Maybe time to find a software to dump DB in more human-readable way... MS excel?

Only export to Excel if you need the data on Excel.

There are other tools to read a sqlite3 database, like this one: https://sqlitebrowser.org/
