### ISSUE TITLE
Latest version point to 5.15.4 version instead of 5.15.5

### ISSUE THREAD

**Issue by mariushosting** [pi-hole/pi-hole#5172]
Latest version point to 5.15.4 version instead of 5.15.5

**Comment by dschaper** [comment]
Doesn't look like that to me.

https://github.com/pi-hole/pi-hole/releases/latest

**Comment by dschaper** [comment]
![image](https://user-images.githubusercontent.com/2782850/218294671-90f9efa5-ecd4-48c1-a10b-720e8bec0232.png)

**Comment by mariushosting** [comment]
> ![image](https://user-images.githubusercontent.com/2782850/218294671-90f9efa5-ecd4-48c1-a10b-720e8bec0232.png)

Yep! But when you download the latest version fresh installation you will download version 5.15.4 instead of 5.15.5 :-/ tested on 5 different machine.

**Comment by rdwebdesign** [comment]
```console
pi@pidev:~ $ pihole -v
  Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
```
Installed a few hour ago.

**Comment by mariushosting** [comment]
> ```
> pi@pidev:~ $ pihole -v
>   Pi-hole version is v5.15.5 (Latest: v5.15.5)
>   AdminLTE version is v5.18.4 (Latest: v5.18.4)
>   FTL version is v5.21 (Latest: v5.21)
> ```
> 
> Installed a few hour ago.
> 
> Also:
> 
> ```
> pi@pidev:~ $ curl -s "https://api.github.com/repos/pi-hole/pi-hole/releases/latest" 2> /dev/null | jq --raw-output .tag_name
> v5.15.5
> ```
> 
> This is the same command `pihole` execute to get the latest version.

Not on Synology NAS devices. Already reported by 150 people in the last 24 hours. Is not working if u also recreate the image from Portainer. Just the latest version point to version 5.15.4 and not the 5.15.5

**Comment by mariushosting** [comment]
![not latest](https://user-images.githubusercontent.com/37554361/218300873-751610f7-06ce-4836-b986-8c8c0dc7063b.png)

**Comment by mariushosting** [comment]
@dschaper

**Comment by PromoFaux** [comment]
> Not on Synology NAS devices. Already reported by 150 people in the last 24 hours. Is not working if u also recreate the image from Portainer. Just the latest version point to version 5.15.4 and not the 5.15.5

It would have helped if you had said you were using docker in the first place... 

https://github.com/pi-hole/docker-pi-hole/releases/tag/2023.02.0

Note that it is supposed to include 5.15.4....

I did not push a new tag to include 5.15.5 because the bug it fixed was nothing to do with docker

>  Already reported by 150 people in the last 24 hours.

Where?
