### ISSUE TITLE
Cannot open dashboard

### ISSUE THREAD

**Issue by robdyck** [pi-hole/pi-hole#5175]
### Versions

  Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
### Platform

- OS and version:  

- Platform:  `Linux slim.mylan 6.1.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  6 23:56:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Expected behavior
When I click on "dashboard" in the GUI, the dashboard should appear.
### Actual behavior / bug
Clicking on "dashboard apparently does nothing. Lighttpd generates a log.
```
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READONLY" in /var/www/html/admin/scripts/pi-hole/php/database.php:56
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:Stack trace:
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:#0 /var/www/html/admin/scripts/pi-hole/php/gravity.php(14): SQLite3_connect()
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:#1 /var/www/html/admin/index.php(71): gravity_last_update()
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:#2 {main}
2023-02-15 09:45:39: (mod_fastcgi.c.449) FastCGI-stderr:  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 56
```
### Steps to reproduce

1. Login to host/admin
2. Click on dashboard
3. 
## Debug Token
[✓] Your debug token is: https://tricorder.pi-hole.net/uxlHygtL/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

DNS queries appear to be working.
I can access sqlite3 DB from the command line.
```
sqlite3 /etc/pihole/gravity.db
SQLite version 3.7.7.1 2011-06-28 17:39:05
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .tables
adlist               domainlist_by_group  vw_gravity         
adlist_by_group      gravity              vw_regex_blacklist 
client               group                vw_regex_whitelist 
client_by_group      info                 vw_whitelist       
domain_audit         vw_adlist          
domainlist           vw_blacklist       
sqlite> .dump info
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE info
(
        property TEXT PRIMARY KEY,
        value TEXT NOT NULL
);
INSERT INTO "info" VALUES('version','15');
INSERT INTO "info" VALUES('updated','1676408657');
INSERT INTO "info" VALUES('gravity_count','177888');
COMMIT;
sqlite>
```
This had previously been working well. Probably some update messed it up. I hadn't accessed the dashboard for months so I don't know when it stopped working.

I tried uninstalling pihole and a new install. No change.

**Comment by robdyck** [comment]
Yes
```
/usr/lib64/php/modules/pdo.so
```

**Comment by rdwebdesign** [comment]
What is the output of `php -m | grep sql` on your system?

**Comment by robdyck** [comment]
```
php -m | grep sql
pdo_sqlite
```

**Comment by rdwebdesign** [comment]
The usual output is:
```
pdo_sqlite
sqlite3
```

Look like `sqlite3` module is installed (you have the file), but is not active.

**Comment by robdyck** [comment]
![image](https://user-images.githubusercontent.com/58280584/219220404-5b1ef69f-ad15-4b37-87ce-8233d78de1ff.png)

**Comment by rdwebdesign** [comment]
To know exactly what is enabled on your PHP, please create a new file using:
```sh
echo "<?php phpinfo(); ?>" > info.php
```

Then using the browser, visit the new page at `http://pi.hole/admin/info.php`.

Do you see PDO and PDO sqlite info?
![image](https://user-images.githubusercontent.com/1385443/219226574-f2c0b499-1ac9-4c55-8d28-ddb5fb96f973.png)

Do you see `sqlite3` info?
![image](https://user-images.githubusercontent.com/1385443/219226657-c3ab3013-7619-410e-ad7d-394f5cc79560.png)

**Comment by robdyck** [comment]
sqlite3 is missing. Is it necessary with PDO. The CRUD demo works fine.

**Comment by robdyck** [comment]
According php.net
```
The SQLite3 extension is enabled by default. It's possible to disable it by using --without-sqlite3 at compile time.
```
Windows users need to enable in the ini but this isn't windows.
Beyond that I believe it requires the system library.
```
/usr/lib64/php/modules/pdo_sqlite.so
/usr/lib64/php/modules/sqlite3.so
```

**Comment by dschaper** [comment]
Any possibility that one of the config files in `/etc/lighttpd/conf.d/` is disabling it?

**Comment by robdyck** [comment]
Nothing apparent.
```
[root@slim conf.d]# find . -type f | xargs grep sqlite
./webdav.conf:  webdav.sqlite-db-name = home_dir + "/webdav.db"
./mime.conf:    ".gpkg" => "application/geopackage+sqlite3",
./mime.conf:    ".sqlite" => "application/vnd.sqlite3",
./mime.conf:    ".sqlite3" => "application/vnd.sqlite3",
```

**Comment by robdyck** [comment]
I shut down nginx and retested the dashboard. No luck.

**Comment by rdwebdesign** [comment]
> Any possibility that one of the config files in /etc/lighttpd/conf.d/ is disabling it?

Not likely. This is a PHP config and it's independent from the web server config.

**Comment by rdwebdesign** [comment]
Maybe this is turned of on the PHP `ini` files.

I'm not sure if this is the right place to enable it, but we can try to find and read the file using this command:
```
cat "$(php -i | grep 'sqlite3.ini' | sed 's/,//g')"
```

If the file exists, its contents will be printed.
As an example, mine looks like this:
```
; configuration for php sqlite3 module
; priority=20
extension=sqlite3.so
```

**Comment by robdyck** [comment]
```
cat "$(php -i | grep 'sqlite3.ini' | sed 's/,//g')"
; Enable sqlite3 extension module
;extension_dir=/usr/lib64/php/modules
;extension=sqlite3.so
;extension=pdo_sqlite.so
```
Does the semi-colon mean this is the default?

**Comment by rdwebdesign** [comment]
Semi-colon means the line is commented (disabled).

Try to enable the module with:
```
phpenmod sqlite3
```

**Comment by robdyck** [comment]
no command.

**Comment by rdwebdesign** [comment]
Looks like the problem is the module is really disabled, but I don't know how to enable PHP modules on Fedora.

This is usually enabled by default, but maybe some other software installation disabled the module.

On Debian, this is installed using `apt install php-sqlite3`.
I'm not sure if this is the correct command, but you can try `yum install php-sqlite3` (or `yum install php-sqlite`). 

You can also try to search how to enable this PHP module.

**Comment by robdyck** [comment]
As above, the the binaries are in /usr/lib64/php/modules. And the CRUD demo works - different server but same PHP installation.

**Comment by robdyck** [comment]
On a whim I removed the comments from /etc/php.d/20-sqlite3.ini. I can now open the dashboard. It would seem the CRUD demo can use PDO sqlite3 independent of the sqlite3 module. It has its own module.

**Comment by rdwebdesign** [comment]
Maybe another installation disabled the module a long time ago and you only noticed now.

`pdo_sqlite` and `sqlite3` are 2 different modules. 

Maybe `lighttpd` needs both enabled to work and `nginx` only needs PDO.
Maybe the code from the CRUD demo only use simpler functions and it's not using the functions from `sqlite3` module.
I really don't know.

Is it working now?

**Comment by robdyck** [comment]
![image](https://user-images.githubusercontent.com/58280584/219261887-8a7ff9e4-729d-4b90-bd90-b2645f981bf1.png)

**Comment by robdyck** [comment]
I am happy to close this. Thank you for prodding me to look in the right place.
