### ISSUE TITLE
foxnews fails to resolve

### ISSUE THREAD

**Issue by azleatherneck** [pi-hole/pi-hole#518]
##### Actual Behaviour:

This site can’t be reached

www.foxnews.com’s server DNS address could not be found.
Search Google for fox news
ERR_NAME_NOT_RESOLVED

##### Steps to reproduce this issue: Any device behind the pihole can not get to fox news

internet-------comcast cable modem bridged-------pfsense---pihole set as pfsense's dns forwarder in resolver. Remove Pihole and foxnews comes up fine

I changed the upstream servers to google publics and no change in behavior (dnsmasq was restarted)

**Comment by azleatherneck** [comment]
Error is from Chrome but all browsers fail
and there are no "Pi-Holed" entries in query log for anything foxnews

**Comment by dschaper** [comment]
Okay, can you SSH into the Pi-Hole and do a `sudo tail -f /var/log/pihole.log | grep foxnews` and then on a client machine try to browse the FoxNews website?

**Comment by azleatherneck** [comment]
sudo tail -f /var/log/pihole.log | grep foxnews
May 31 22:52:56 dnsmasq[26605]: query[A] www.foxnews.com from 192.168.50.1
May 31 22:52:56 dnsmasq[26605]: forwarded www.foxnews.com to 8.8.4.4
May 31 22:52:56 dnsmasq[26605]: reply www.foxnews.com is <CNAME>
May 31 22:52:56 dnsmasq[26605]: reply www.foxnews.com.edgesuite.net is <CNAME>
May 31 22:52:56 dnsmasq[26605]: query[A] www.foxnews.com.edgesuite.net from 192.168.50.1
May 31 22:52:56 dnsmasq[26605]: forwarded www.foxnews.com.edgesuite.net to 8.8.4.4
May 31 22:52:56 dnsmasq[26605]: reply www.foxnews.com.edgesuite.net is <CNAME>

**Comment by azleatherneck** [comment]
wtf is that edgesuite.net BS??

**Comment by dschaper** [comment]
Okay, so `dnsmasq` is seeing your requests for FoxNews and it's content provides, and forwarding the requests to 8.8.4.4 which is the Google DNS resolver. The EdgeSuite entries are the content delivery networks that FoxNews uses to deliver some of the page contents. It shouldn't be anything to be alarmed about, most large websites don't server from their own domains and servers, but use what are called CDN's to do the actual delivery of their content. 

I don't think there's a problem with your Pi-Hole setup, but let's go ahead and do the debug step to look at your configs and see if there is anything that comes to light.

At a terminal prompt, enter `sudo pihole -d` and when you are asked to visit the website in question, use a Pi-hole client machine and browse to FoxNews, then go back to the Pi terminal, and CTRL-C. This will leave a log file in `/var/log` called `pihole-debug.log`. If you can copy the contents of that file and post them to a site like PasteBin and then give us a link to that page we can review it and see what we there is.

**Comment by azleatherneck** [comment]
http://pastebin.com/WB2Cwf05

**Comment by azleatherneck** [comment]
Riddle me this, IF i change my firewall to use the DNS forwarder and not DNS Resolver it works fine

Pfsense 2.3.1_1

**Comment by azleatherneck** [comment]
so dnsmasq on pfsense to dnsmasq on pihole works fine
resolver on pfsense to dnsmasq on pihole fails....Thats a head scratcher

**Comment by dschaper** [comment]
That's something I'd have to research, I don't have much experience with the PFSense wall, I'm using MicroTik personally, (ex-Cisco engineer.)

**Comment by azleatherneck** [comment]
Ill dig more on my end and post, the Geek in me cant let this go, Thanks for the QUICK replies!!

**Comment by dschaper** [comment]
I'm wondering if there's an issue with rebinding? The PFSense resolver may be seeing something that it thinks is a rebind and refusing to give the DNS address, while `dnsmasq` is okay with some non-routeable addresses being used as source... Keep us up to date, and I'll keep the issue open!

**Comment by azleatherneck** [comment]
Could be but strange that I have only seen this for foxnews.com so far no other domains I have come across

**Comment by azleatherneck** [comment]
Wow you are the man...dug into the resolver logs and....drum beat



May 31 23:10:27	dnsmasq	64158	possible DNS-rebind attack detected: widgets.outbrain.com
May 31 23:10:27	dnsmasq	64158	possible DNS-rebind attack detected: dbg52463.moatads.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: foxnews.demdex.net
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: cdn.tt.omtrdc.net
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: foxnews.tt.omtrdc.net
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: cdn.optimizely.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: secure-us.imrworldwide.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: b.scorecardresearch.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: www.googletagservices.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: s.moatads.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: static.parsely.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: a.visualrevenue.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: static.chartbeat.com
May 31 23:10:28	dnsmasq	64158	possible DNS-rebind attack detected: metrics.foxnews.com
May 31 23:10:29	dnsmasq	64158	possible DNS-rebind attack detected: tapestry.tapad.com
May 31 23:10:29	dnsmasq	64158	possible DNS-rebind attack detected: widget-cdn.rpxnow.com
May 31 23:10:29	dnsmasq	64158	possible DNS-rebind attack detected: bootstrap.livefyre.com
May 31 23:10:35	dnsmasq	64158	possible DNS-rebind attack detected: ws.tapjoyads.com
May 31 23:10:35	dnsmasq	64158	possible DNS-rebind attack detected: data.flurry.com
May 31 23:10:37	dnsmasq	64158	possible DNS-rebind attack detected: connect.tapjoy.com
May 31 23:10:38	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:10:38	dnsmasq	64158	possible DNS-rebind attack detected: track.appsflyer.com
May 31 23:10:38	dnsmasq	64158	possible DNS-rebind attack detected: live.chartboost.com
May 31 23:10:38	dnsmasq	64158	possible DNS-rebind attack detected: iadsdk.apple.com
May 31 23:10:53	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:54	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:56	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:56	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:56	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:57	dnsmasq	64158	possible DNS-rebind attack detected: csi.gstatic.com
May 31 23:10:57	dnsmasq	64158	failed to send packet: Host is down
May 31 23:10:57	dnsmasq	64158	failed to send packet: Host is down
May 31 23:11:52	dnsmasq	64158	read /etc/hosts - 31 addresses
May 31 23:12:06	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:12:16	dnsmasq	64158	possible DNS-rebind attack detected: s.youtube.com
May 31 23:12:57	dnsmasq	64158	possible DNS-rebind attack detected: csi.gstatic.com
May 31 23:12:58	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:13:16	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:14:17	dnsmasq	64158	possible DNS-rebind attack detected: bs.serving-sys.com
May 31 23:14:44	dnsmasq	64158	possible DNS-rebind attack detected: s.youtube.com
May 31 23:14:57	dnsmasq	64158	possible DNS-rebind attack detected: csi.gstatic.com
May 31 23:15:06	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:15:22	dnsmasq	64158	possible DNS-rebind attack detected: bs.serving-sys.com
May 31 23:15:58	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:16:16	dnsmasq	64158	possible DNS-rebind attack detected: www.googleadservices.com
May 31 23:16:33	dnsmasq	64158	possible DNS-rebind attack detected: bs.serving-sys.com
May 31 23:16:57	dnsmasq	64158	possible DNS-rebind attack detected: csi.gstatic.com

**Comment by dschaper** [comment]
Yeah, security appliances tend to get a bit jumpy when they see internal addresses as being the source sometimes. Might have to FAQ that one up, lol...

**Comment by azleatherneck** [comment]
Yah found its a common issue with PF and will advise on work around for the thread once done....to late tonight thanks again for the talk through

**Comment by azleatherneck** [comment]
Bottom line, IF you are pointing to your Pi-Hole on your Lan as a DNS forwarder/Upstream server for your Firewall/router and it has DNS Rebind attack monitoring or mitigation this could be your issue.

Solution 1: Hand out the Pi-Hole IP as the DNS server in your DHCP scope
Solution 2: Disable the rebind attack detection, depending on what your edge device is this will need to be researched specific to your device.
