### ISSUE TITLE
lighttpd will get installed on pihole -r even if not selected during initial installation

### ISSUE THREAD

**Issue by daeks** [pi-hole/pi-hole#5182]
### Versions

Pi-hole v5.15.5
FTL v5.21
Web Interface v5.18.4

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi,

### Expected behavior

pihole -r does not install lighttpd if no webserver has been selected during installation. 

### Actual behavior / bug

If i start "pihole -r" and choose "repair" it installts lighttpd with full configuration, even if during the original installation no webserver to be installed was selected

### Steps to reproduce

1. Go to 'pihole -r'
2. Click on 'Repair'
3. lighttpd will be installed even if not selected during initial installation

**Comment by yubiuser** [comment]
This should not happen.

If `repair` is selected, `useUpdateVars` will be true

https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/automated%20install/basic-install.sh#L2078-L2082

and this is later sourcing`setupVars.conf`

https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/automated%20install/basic-install.sh#L2606-L2611

which should set `INSTALL_WEB_SERVER=false` and prevent installation. 

https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/automated%20install/basic-install.sh#L2626-L2628

___

So the question is: does your `setupVars.conf` contain `INSTALL_WEB_SERVER=false`
