### ISSUE TITLE
[Tracking] `pihole -q` does not find subdomains blocked by ABP style gravity entries

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#5184]
For tracking, in case https://github.com/pi-hole/pi-hole/pull/5179 is released without `pihole -q` support for subdomains in ABP style.
See https://github.com/pi-hole/pi-hole/pull/5179#issuecomment-1439168504

**Comment by rdwebdesign** [comment]
Fixed by https://github.com/pi-hole/pi-hole/pull/5210
