### ISSUE TITLE
Adlist Management UI Enhancement - Bulk Group Assignments

### ISSUE THREAD

**Issue by korgano** [pi-hole/pi-hole#5186]
### Versions

- Pi-hole:  v5.15.5
- AdminLTE:  v5.18.4
- FTL:  v5.21

### Platform

- OS and version:  Debian Buster, et al

- Platform: Raspberry Pi, et al

### Expected behavior

Adlists are applied to all groups and included devices.

### Actual behavior / bug

Adlists are applied to default group only. If other groups are created, user must go into Adlist page and **manually** set Group Assignments to include any/all groups beyond default.

Adlist based blocking may not function

### Steps to reproduce

1. Go to Adlists.
2. Scroll down to first Adlist.
3. By default, all Adlists will show the name of the Default group in "Group Assignment" pill.
4. If downward arrow visible on "Group Assignment" pill, user must click on pill to access menu overlay to apply Adlist to other groups.
5. User must repeat process on **all** Adlists if multiple groups exist.

### Additional context

Problem is easily solved by having a checkbox menu appear after clicking checkbox(es) to select all/some Adlists, allowing user to apply multiple groups at once the selected Adlists.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
