### ISSUE TITLE
Unsupported OS detected: Ubuntu 23.04

### ISSUE THREAD

**Issue by roma4u** [pi-hole/pi-hole#5188]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/863813/221583547-c0d6e154-f2b4-4c16-a7f6-104e10c01f14.png">

**Comment by roma4u** [comment]
curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

**Comment by jfb-pihole** [comment]
The OS you are running is in fact not supported at this time:

```
dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=36,37 CentOS=8,9"
```

**Comment by yubiuser** [comment]
... and not even officially released.

**Comment by fakhamatia** [comment]
> The OS you are running is in fact not supported at this time:
> 
> ```
> dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
> "Raspbian=10,11 Ubuntu=20,22 Debian=10,11 Fedora=36,37 CentOS=8,9"
> ```

Will support for 23.04 be added in the future? Or because it is not an LTS version, it will never be supported.

**Comment by jfb-pihole** [comment]
We cannot predict with any confidence which distros will be supported in the future.  It's case by case.
