### ISSUE TITLE
Cannot find image to download?

### ISSUE THREAD

**Issue by MarcGodard** [pi-hole/pi-hole#5191]
Hi I remember downloading an image for my rpi sd card... but now I cannot find this? Where can I find this?

**Comment by rdwebdesign** [comment]
Are you talking about docker images?
https://github.com/pi-hole/docker-pi-hole/

**Comment by rdwebdesign** [comment]
Are you talking about docker images?
- https://github.com/pi-hole/docker-pi-hole/
- https://hub.docker.com/r/pihole/pihole

**Comment by dschaper** [comment]
https://www.raspberrypi.com/software/

**Comment by dschaper** [comment]
Yes, all the information you need is at https://docs.pi-hole.net/main/prerequisites/

**Comment by MarcGodard** [comment]
Is there a headless way to install it on a pi?

**Comment by rdwebdesign** [comment]
You just need to access your headless Pi using `ssh` and follow the [One-Step Automated Install](https://github.com/pi-hole/pi-hole#one-step-automated-install).

**Comment by dschaper** [comment]
Headless way to install what? Pi-hole or Raspberry Pi OS?

You need to use the support forum that the template instructed you to use for non-bug issues. 

https://discourse.pi-hole.net.
