### ISSUE TITLE
pihole -q is case sensitive, pihole-FTL regex-test isn't

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/pi-hole#5199]
Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is new/adb_style_blocking vDev-da118e8 (Latest: v5.21)

### Platform
raspberrypi 3B
Linux raspberrypi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux

### Expected behavior

pihole -q reports the same result as pihole-FTL for regexes

### Actual behavior / bug

pihole -q is case sensitive, it shouldn't be!

### Steps to reproduce

my regex:
![image](https://user-images.githubusercontent.com/24669386/223077962-5c488566-5fcc-46a7-a811-38cf430d3ff6.png)

pihole-FTL regex-test **C**ookiebot cookiebot
```
[i] Compiling regex filter...
    Compiled regex filter in 0.117 msec

Checking domain...
    cookiebot matches
   Time: 0.076 msec
```
 pihole -q **C**ookiebot -> **NO regex match reported**
```
 Match found in file:///home/pi/blocklistproject/blocklistproject:
   consent.cookiebot.com
   cookiebot.com
 Match found in http://localhost/mylist.txt:
   consent.cookiebot.com
 Match found in https://v.firebog.net/hosts/neohostsbasic.txt:
   consent.cookiebot.com
 Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
   resources.cookiebot.com
 Match found in https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt:
   consent.cookiebot.com
   afdverify.consent.cookiebot.com
```
pihole -q cookiebot
```
 Match found in regex blacklist
   cookiebot
...
```

edit
possible fix (query.sh), **using bash 4.0**: add **,,** to "${options}" e.g. **"${options,,}"**
```
options=$(sed -E 's/ ?-(all|exact) ?//g' <<< "${options,,}")
```

possible fix (query.sh), **using tr**: replace **"${options}"** with **```$```(echo "${options}") | tr '[:upper:]' '[:lower:]')**
```
options=$(sed -E 's/ ?-(all|exact) ?//g' <<< $(echo "${options}") | tr '[:upper:]' '[:lower:]')
```
/edit

**Comment by dschaper** [comment]
It seems to be okay with the `queryads.php` page.
![image](https://user-images.githubusercontent.com/2782850/223212570-0f93a521-9a86-4f96-af9c-79213e703438.png)

But it does seem the CLI is not catching it. 
```sh
root@09184bcf19b7:/# pihole -q cookiebot
 Match found in regex blacklist
   .
   cookiebot
root@09184bcf19b7:/# pihole -q Cookiebot
 Match found in regex blacklist
   .
```

(I have a `.` regex entry for some devices from TP-Link that don't need to ever resolve any DNS names.)

**Comment by rdwebdesign** [comment]
> It seems to be okay with the `queryads.php` page.

The web interface converts to lower case:
https://github.com/pi-hole/AdminLTE/blob/b29a423b9553654f113bcdc8a82296eb6e4613d7/scripts/pi-hole/js/queryads.js#L14

**Comment by jpgpi250** [comment]
@rdwebdesign 

would it be possible to implement my fix (tr solution will hopefully suite all distros), or a better solution, if any, in the adb_query branch you hopefully will have the time to fix? This to avoid merge conflicts...

**Comment by rdwebdesign** [comment]
`adb_query` is still a work in progress and I will wait for the current `abp` branch to be merged before opening a PR.

I think we can add some changes to the new branch to avoid problems with uppercase/lowercase/mixedcase domains.

**Comment by dschaper** [comment]
Fix is in `development` branch. Please update and report any observations.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.16
