### ISSUE TITLE
pihole restartdns reload-lists does not reload from dnsmasq config?

### ISSUE THREAD

**Issue by charlieporth1** [pi-hole/pi-hole#5202]
It should be noted that this is not an existing feature so I'm not sure if this is a bug or a FR

### Versions

Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)

### Platform

- OS and version:  Ubuntu

- Platform:  VM & VPS

### Expected behavior
I believe it should reload hosts from /etc/dnsmasq.d/*
It should be noted that this is not an existing feature so I'm not sure if this is a bug or a FR
_A clear and concise description of what you expected to happen._
### Actual behavior / bug
Not reloaded
_A clear and concise description of what the bug is._

### Steps to reproduce
cname=doogle.com,google.com,3600 in a sample file in dnsmasq config and dig for the pihole 

The token is displayed at the end of the debug process if you allow for uploading the log file. 

[✓] Your debug token is: https://tricorder.pi-hole.net/wim5hft4rq

Debug logs are visible ONLY to developers and support staff. They are not publically accessible and all logs are automatically deleted after 48 hours.
-->

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

It should be noted that this is not an existing feature so I'm not sure if this is a bug or a FR

**Comment by jfb-pihole** [comment]
No debug log was found at this token.

Please open a topic on our discourse forum, as this does not appear to be a bug.

**Comment by dschaper** [comment]
Can you try a new `pihole -d` run and post the new URL?

And can you explain a bit more what you are seeing and what you expect to see? Can you include the `dig` outputs as well? 

What exactly are you typing at the command line and what is the output from your commands?

**Comment by js290** [comment]
There may be buggy behavior with `pihole restartdns`... [For me](https://discourse.pi-hole.net/t/refreshing-dnsmasq-from-cli/61684), w/o options, it doesn't seem to re-parse `setupVars.conf` and update `/etc/dnsmasq.d/01-pihole.conf`.

Here's my [debug token](https://tricorder.pi-hole.net/rFJykvo1/).

**Comment by dschaper** [comment]
How does that relate to `reload-lists`? I don't see how that requires a re-parsing of `setupVars.conf`.

**Comment by js290** [comment]
Is `restartdns` working as expected?

**Comment by charlieporth1** [comment]
Yes it is

**Comment by js290** [comment]
> 
Does "config file parsing" imply dnsmasq update?
```
       restartdns [options]
           Full  restart  Pi-hole  subsystems.  Without any options (see below) a full restart causes config file
       parsing and history re-reading

           (restart options):
             reload            Updates the lists (incl. HOSTS files) and flushes DNS cache. Does not reparse con‐
       fig files
             reload-lists       Updates  the  lists  (excl. HOSTS files) WITHOUT flushing the DNS cache. Does not
       reparse config files
```

**Comment by charlieporth1** [comment]
> > 
> 
> Does "config file parsing" imply dnsmasq update?
> 
> ```
>        restartdns [options]
>            Full  restart  Pi-hole  subsystems.  Without any options (see below) a full restart causes config file
>        parsing and history re-reading
> 
>            (restart options):
>              reload            Updates the lists (incl. HOSTS files) and flushes DNS cache. Does not reparse con‐
>        fig files
>              reload-lists       Updates  the  lists  (excl. HOSTS files) WITHOUT flushing the DNS cache. Does not
>        reparse config files
> ```
It should since you use dnsmasq as the backend with a custom fork

**Comment by js290** [comment]
> > > 
> > 
> > 
> > Does "config file parsing" imply dnsmasq update?
> > ```
> >        restartdns [options]
> >            Full  restart  Pi-hole  subsystems.  Without any options (see below) a full restart causes config file
> >        parsing and history re-reading
> > 
> >            (restart options):
> >              reload            Updates the lists (incl. HOSTS files) and flushes DNS cache. Does not reparse con‐
> >        fig files
> >              reload-lists       Updates  the  lists  (excl. HOSTS files) WITHOUT flushing the DNS cache. Does not
> >        reparse config files
> > ```
> 
> It should since you use dnsmasq as the backend with a custom fork

So should I open a new issue or should we keep potential buggy `restartdns` behavior here?  Because `restartdns` w/o options is **not** updating `/etc/dnsmasq.d/01-pihole.conf`.

**Comment by charlieporth1** [comment]
> 

Sorry for the late edit do you mind updating that so we can be on the same page with each other

**Comment by js290** [comment]
> I don't think it does since you use dnsmasq as the backend with a custom fork with dnsmasq and t he config is in setupVars.conf

Saving DNS Settings in the web UI saves to `setupVars.conf` and updates dnsmasq... so it must not be tied to `restartdns`... does `restartdns` parse `setupVars.conf`, i.e. is this the config file that gets parsed as implied in the `pihole` man page?

**Comment by charlieporth1** [comment]
I think the reason I'm confused is because of this in statement `admin/dns_records.php`

```
The device's host name and pi.hole
Configured in a config file in /etc/dnsmasq.d/
Read from /etc/hosts
Read from the "Local (custom) DNS" list (stored in /etc/pihole/custom.list)
```

Because A. my custom dnsmasq config files are not showing up there and I assumed they are lists

**Comment by js290** [comment]
assuming your custom dnsmasq config files have valid `dnsmasq` config syntax and are located in `/etc/dnsmasq.d`, maybe there is buggy behavior with `restartdns`...

**Comment by charlieporth1** [comment]
My dnsmasq files are valid

**Comment by yubiuser** [comment]
@js290 

Please stop hijacking threads and repeatedly stating your own issue.

**Comment by js290** [comment]
Please update docs accordingly, thanks... #5204

**Comment by dschaper** [comment]
I think we're done with the hijacking. Thanks for playing!

**Comment by dschaper** [comment]
I'm still waiting for the new debug URL, thanks!

**Comment by charlieporth1** [comment]
Just so I'm clean I have differnet files than the `pihole -a removecustomdns` and `pihole -a addcustomdns`  commands put the domains for 2 reason. A the command is not documented. B for organization. I am getting you the debug token

**Comment by droghio** [comment]
Sorry to ping an old thread but can you add more background on why the issue was no longer needed? I believe I am seeing the same behavior on the latest version of pihole:

```
pihole -v       
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
```

Namely I add a custom config under the /etc/dnsmasq.d/ directory where changes to the records only seem to take effect if I issue `pihole restartdns` vs. `pihole restartdns reload-lists`. Namely I run nslookup locally on the pihole and with the reload-lists command any changes I had made to the file are not reflected but if I do the full restartdns the query reflects the changes.

**Comment by yubiuser** [comment]
@droghio 

This is expected: `pihole restartdns reload-lists` is not enough to re-read the `dnsmasq` config. You could try if `pihole restartdns reload` is enough, otherwise you need a full `restartdns`
