### ISSUE TITLE
restartdns not updating dnsmasq configs

### ISSUE THREAD

**Issue by js290** [pi-hole/pi-hole#5203]
### Versions

- Pi-hole:  v5.15.5
- AdminLTE:  v5.18.4
- FTL:  v5.21

### Platform

- OS and version:  Debian 11 (bullseye)

- Platform:  i386

### Expected behavior

Should `pihole restartdns` w/o options reparse `setupVars.conf` and update `/etc/dnsmasq.d/01-pihole.conf`?

### Actual behavior / bug

`pihole restartdns` (w/o options) does not update `/etc/dnsmasq.d/01-pihole.conf`.

### Steps to reproduce

1. update `PIHOLE_DNS_*` in `/etc/pihole/setupVars.conf`
2. run `pihole restartdns`
3. check `/etc/dnsmasq.d/01-pihole.conf` is not updated with new server(s)

Saving in the [web UI](http://pi.hole/admin/settings.php?tab=dns) updates `setupVars.conf` and `01-pihole.conf`
## Debug Token

- URL:  https://tricorder.pi-hole.net/rFJykvo1/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

[at discourse](https://discourse.pi-hole.net/t/refreshing-dnsmasq-from-cli/61684?u=js290): What is the correct way to use the pihole CLI to reload after manually updating `setupVars.conf`?

**Comment by yubiuser** [comment]
There is no bug. `pihole restartdns` is not meant to re-read the `setupVars.conf` and set `01-pihole.conf`. The right command is `pihole -a setdns`

https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/advanced/Scripts/webpage.sh#L302
