### ISSUE TITLE
Process still running after uninstalling pihole

### ISSUE THREAD

**Issue by pietrouk** [pi-hole/pi-hole#5205]
After running "pihole uninstall", I'm still seeing this in the log files:
1678437423|127.0.0.1|127.0.0.1|GET /admin/api.php HTTP/1.1|404|341
1678437454|127.0.0.1|127.0.0.1|GET /admin/api.php HTTP/1.1|404|341

I'm running Raspbian GNU/Linux 10 (buster) and would like to keep lighttpd running.

How can I remove those requests?

**Comment by yubiuser** [comment]
This file should have been removed by the installer

https://github.com/pi-hole/pi-hole/blob/d86b325dfe4d39b7bc523672bb22f1bdbd12265f/automated%20install/uninstall.sh#L102-L106

Can you still access the web interface?

What's the output of 
```
sudo ls -lha /var/www/html/admin
```

**Comment by pietrouk** [comment]
Web interface cannot be accessed but it's possible that I had manually removed those folders before running the uninstall script.

Output is

$ sudo ls -lha /var/www/html/admin
ls: cannot access '/var/www/html/admin': No such file or directory

**Comment by yubiuser** [comment]
I just spotted `404` in your

> 1678437423|127.0.0.1|127.0.0.1|GET /admin/api.php HTTP/1.1|404|341

So something is trying to reach the API but it could not be found. Are you running any third-party app that might use Pi-hole's API?

**Comment by pietrouk** [comment]
Not that I am aware of, how would I go about finding that out?
