### ISSUE TITLE
403 error after upgrade to 5.15.5

### ISSUE THREAD

**Issue by christianhuebner** [pi-hole/pi-hole#5207]
### Versions

  Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)

### Platform

- OS and version:  raspbian 10 (buster)

- Platform:  Raspberry Pi (Pihole)

### Expected behavior

Until now when accessing http://<ip of pihole server> I got a page that has the raspberry and a link to the admin interface. 

### Actual behavior / bug

Now accessing http://<ip of pihole server> I receive 403 forbidden

### Steps to reproduce

Enter "http:://<ip of pihole server>" in browser URL box. Result: white page with "403 Forbidden"

## Debug Token

- URL:  https://tricorder.pi-hole.net/WYIQN5xC/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

While trying to find the problem I found another issue with lighttpd, but fixing that did not fix the 403 problem:

/var/log/lighttpd/error-pihole.log
2023-03-11 19:58:06: (server.c.1464) server started (lighttpd/1.4.53)
2023-03-11 19:58:06: (server.c.1493) WARNING: unknown config-key: setenv.add-response-header (ignored)
2023-03-11 19:58:06: (server.c.1493) WARNING: unknown config-key: setenv.set-response-header (ignored)
2023-03-11 20:15:25: (server.c.2059) server stopped by UID = 0 PID = 1

I can not guarantee this is new in this version, but the reason this appears is that mod_setenv is missing in the lighttpd.conf for v5.15.5

root@raspberrypi:/etc/lighttpd# diff lighttpd.conf.bug lighttpd.conf
5a6
>  	"mod_setenv",

After adding this line in the server.modules list in lighttpd.conf the error when restarting lighttpd doees not appear anymore. The 403 error described above is not fixed by adding this line.

**Comment by christianhuebner** [comment]
I tried purging and re-adding lighttpd and then running pihole -r and selecting repair.

The issue appears to be that index.html is missing. The index.html that comes with lighttpd is renamed into index.lighttpd.orig and no replacement file is created.

**Comment by jfb-pihole** [comment]
What is the exact URL you are using to access the admin GUI?

**Comment by PromoFaux** [comment]
This is expected behaviour.

To access the web interface you need to append `/admin` to the URL you use to access the web interface, or browse via `http://pi.hole`

See these release notes for more information:

https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content
