### ISSUE TITLE
Installed DNSCrypt, requests are not secured

### ISSUE THREAD

**Issue by brantje** [pi-hole/pi-hole#521]
I followed the wiki [page](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt) to install DNSCrypt.
Builded DNSCrypt from source, installed it and tested it.

Tested DNSCrypt with sudo journalctl -u dnscrypt-proxy
And the last line in the output is
`[NOTICE] Proxying from 127.0.0.1:40 to 77.66.84.233:443`

So DNSCrypt seems to be working.
When i go to dnssec-failed.org it still resolves, also other dnssec tests fails

**Comment by dschaper** [comment]
Can you post a copy of your `pihole -d` and give us a link to your PasteBin?

**Comment by brantje** [comment]
After a reinstall of raspbian, pi-hole and dnscrypt it works.

**Comment by brantje** [comment]
I spoke to soon...
After a reboot the following happens

`
Jun 02 21:33:31 piHole systemd[1]: dnscrypt-proxy.service start operation timed out. Terminating.
Jun 02 21:33:31 piHole systemd[1]: Failed to start Secure connection between your computer and DNS resolver.
Jun 02 21:33:31 piHole systemd[1]: Unit dnscrypt-proxy.service entered failed state.
Jun 02 21:33:36 piHole systemd[1]: dnscrypt-proxy.service holdoff time over, scheduling restart.
Jun 02 21:33:36 piHole systemd[1]: Stopping Secure connection between your computer and DNS resolver...
Jun 02 21:33:36 piHole systemd[1]: Starting Secure connection between your computer and DNS resolver...
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] + DNS Security Extensions are supported
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] + Provider supposedly doesn't keep logs
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [NOTICE] Starting dnscrypt-proxy 1.6.1
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] Ephemeral keys enabled - generating a new seed
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] Done
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] Server certificate #808464433 received
Jun 02 21:33:36 piHole dnscrypt-proxy[808]: [INFO] This certificate is valid
Jun 02 21:33:37 piHole dnscrypt-proxy[808]: [INFO] Chosen certificate #808464433 is valid from [2015-09-11] to [2016-09-10]
Jun 02 21:33:37 piHole dnscrypt-proxy[808]: [INFO] Server key fingerprint is E7AC:5C21:A4E6:6A90:B254:DD73:5229:3BA1:5BE9:8EB3:4E8F:E538:52DE:A2FB:DDB6:1357
Jun 02 21:33:37 piHole dnscrypt-proxy[808]: [NOTICE] Proxying from 127.0.0.1:40 to 176.56.237.171:443
`

Log: http://pastebin.com/pRyWCg5J

**Comment by dschaper** [comment]
How many instances of dnscrypt-proxy are you running? Your Pi-hole config is trying to connect to ports 40 and 41. And there seems to be an issue with your webserver. The last line shows you do have a successful dnscrypt-proxy session set up though, so could you please detail what problems you are seeing?

**Comment by brantje** [comment]
I followed the wiki, created a `dnscrypt-proxy.service` and `dnscrypt-proxy-backup.service`. Config files [here](http://pastebin.com/Rs8eSwJA).
I used the dnscrypt.eu-nl for main and the fvz-rec-gb-lon-01 as backup one.
The issue with the webserver was last night when i reinstalled it, logs where empty so that probably caused the PHP error.

**Comment by brantje** [comment]
Strange after another reboot it works again. I'll investigate and report back

**Comment by dschaper** [comment]
The PHP error is something we can take a look at later, empty logs shouldn't throw those. 

But for dnscrypt-proxy can you post up `sudo systemctl -i status dnscrypt-proxy` and `sudo systemctl -i status dnscrypt-proxy-backup`

**Comment by brantje** [comment]
I think i've found it, changed the backup server from fvz-rec-gb-lon-01 (londen) to dnscrypt.eu-dk seems to work, can you test this server?

**Comment by brantje** [comment]
As for the PHP error, i will create a separate issue in the correct repo.

**Comment by dschaper** [comment]
I don't currently have a system that I can change up the servers to test, but those two `systemctl status` commands I posted above should give you the running status and any errors if the server is down. The dnscrypt-proxy Wiki entry was done by a contributor and isn't supported by Pi-Hole. (It's a beta work in progress write up...)

**Comment by brantje** [comment]
I suspect it is that server, because when i change it back, get the errors posted above.
Also i have idea's / improvements for the webinterface, maybe better to discuss that on gitter?

**Comment by dschaper** [comment]
Or if you can code the improvements and send us a PR? But that would be better handled over on that Repo.

**Comment by brantje** [comment]
Yea np, i have some spare time this weekend =)

**Comment by ewan2395** [comment]
I had a similar issue with DNScrypt servers so I increased the number of servers being used and added "all-servers" to dnsmasq's config - setting this flag forces dnsmasq to send all queries to all available servers. The reply from the server which answers first will be returned to the original requester.

`all-servers
server=127.0.0.1#25354
server=127.0.0.1#25355
server=127.0.0.1#25356
server=127.0.0.1#25357
server=127.0.0.1#25358`

For DNScrypt-proxy I added a various servers from different providers using this: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by dschaper** [comment]
Hi @brantje, this kind of got put on the back burner while we looked at your other contributions to the project. Updates?
