### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hitensam** [pi-hole/pi-hole#5212]
### Versions
Pi-hole: v5.15.5
AdminLTE: v5.18.4
FTL: v5.21

### Platform

- OS and version:  Debian

- Platform:  Raspberry Pi Zero W

### Feature Request
Whenever pi-hole blocks any address, the user should be redirected to a page that shows (blocked by pi-hole). This feature can be very useful in finding the relevant domains which need the manual whitelisting by the admin.

Example : 
![OpenDNS-implementation](https://user-images.githubusercontent.com/30778907/225860367-2aa70de8-3dbc-4188-afa3-9320ce795fe9.png)

**Comment by yubiuser** [comment]
Pi-hole used to have this function but we removed it on purpose: it's only working with unencrypted `http` requests which is the minority these days on the internet.


https://github.com/pi-hole/pi-hole/pull/3910

**Comment by hitensam** [comment]
Okay, thanks for the info. Is there any way I can implement the same on my end?
