### ISSUE TITLE
Pi-Hole scripted domain gravity.db changes and pihole restartdns reload-lists not working.

### ISSUE THREAD

**Issue by an0wak** [pi-hole/pi-hole#5217]
### Versions

Pi-hole version is v5.15.5 (Latest: v5.15.5)
AdminLTE version is v5.18.4 (Latest: v5.18.4)
FTL version is v5.21 (Latest: v5.21)

### Platform

- OS and version:  Debian 11(.6)
- 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

- Platform:  Tired VM on top KVM and a Docker Image. But this case is for VM on KVM.

### Expected behaviour
When running a cron job script, to enable or disable ```Domains``` at specified times and using ```pihole restartdns reload-lists```, I would expect it to work, as it does when done via the GUI. 

GUI section I'm referring too.
![image](https://user-images.githubusercontent.com/74270857/226468181-45aaf94a-7513-41f4-83b3-aa6a1007f9bc.png)

**Bash Script**
_modify_pihole_domainlist.sh_
```
#!/bin/bash

enabled=$1

if [ ! -z "${enabled-}" ]
then

 echo "$(date)# ${enabled}" >> /var/log/cron.log
 echo "$(date)# assign value: ${enabled}"

 gravitydb="/etc/pihole/gravity.db"

 # Enable/Disable blacklists with script in comment.
 pihole-FTL sqlite3 ${gravitydb} "update 'domainlist' SET enabled = '${enabled}' WHERE comment like '%Script%';"

 echo "$(pihole-FTL sqlite3 -header -cmd ".mode columns" ${gravitydb} "SELECT * FROM 'domainlist' WHERE comment like '%Script%';")" >> /var/log/cron.log

 pihole restartdns reload-lists

 echo "DNS Restarted" >> /var/log/cron.log

fi
```

crontab
```
00 6 * * Mon /opt/pihole_scripts/modify_pihole_domainlist.sh 1
30 16 * * Fri /opt/pihole_scripts/modify_pihole_domainlist.sh 0
```

### Actual behavior / bug
When using the GUI to enable and disable domains - works a treat.
When using a script, it will trigger the database variable within the database correctly and show correctly under the GUI. But Pi-Hole ignores the values. If domain was previously set to enabled, and script disables it - it will keep working as though it is enabled. The only way to fix it, is to click individually in the GUI domains, enable or disable. Or run ```pihole restartdns reload-lists``` via command line.

I've tried different actions below with no success. But have read reload-list should do the trick.
```pihole updateGravity```
```pihole stop; pihole start```

### Steps to reproduce

Steps to reproduce the behaviour:

Physical Hardware: Intel NUC
Operating System: Debian 11.6
Hardware: Debian KVM - Debian VM
Kernel Architecture: amd64
Hardware architecture: x86

Install Pi-Hole as per Pi-Hole documentation for Debian using One-Step Automated install.
Set up a few regexp domains to block. Add comment and prefix or postfix the work "Script" to it.
Create script as shown above modify_pihole_domainlist.sh
Place script in a directory of choice e.g: /opt/pihole_scripts
Create cron task as sudo, shown above - modify time to suited testing times.
Allow time to pass and script trigger the database enable, disable values. 
See within GUI values have correctly changed.
See that the blocking or allowing is not adhered too. Unless manually restarted or triggered?

**Comment by dschaper** [comment]
Please include two debug token URLs. One from each condition. 

If a manual `pihole restartdns reload-lists` works then my assumption is that your script is not working as you intend.

Perhaps including the output from `bash -x /opt/pihole_scripts/modify_pihole_domainlist.sh 1` and the same with `0` will shed some light. 

What user owns and will be running that crontab entry?

**Comment by dschaper** [comment]
And you'll want to include the full path to `pihole` in that cronjob script. `cron` has a different `PATH` environment and it may not be what you expect.

**Comment by an0wak** [comment]
Hi dschaper,

The ```echo "DNS Restarted" >> /var/log/cron.log``` is more for myself so I know the command above was run.


Output for the script and checking the database values is as follows - I can see it is changing the value.
```
Tue 21 Mar 2023 08:03:34 AEDT# 1
id  type  domain                                                enabled  date_added  date_modified  comment
--  ----  ----------------------------------------------------  -------  ----------  -------------  ----------------------
1   3     (.|^)youtube.*$                                       1        1677541300  1679346214      Script Block YouTube
2   3     (.|^)googlevideo.*$                                   1        1677541300  1679346214      Script Block YouTube
3   3     .*youtu.?be.*                                         1        1677541300  1679346214      Script Block YouTube
4   3     (.|^)tiktok.*$                                        1        1677541300  1679346214      Script Block TikTok
5   3     (.|^)tiktok.com$                                      1        1677541300  1679346214      Script Block TikTok
6   3     (.|^)twitch.tv$                                       1        1677541300  1679346214      Script Block Twitch
15  3     (.|^)instagram.*$                                     1        1678699082  1679346214     Script Block Instagram
16  3     (^|.).+(snapchat|sc-cdn|snapkit|snap-dev|snapads).*$  1        1678699587  1679346214     Script Block Snapchat
DNS Restarted
Tue 21 Mar 2023 08:04:01 AEDT# 0
id  type  domain                                                enabled  date_added  date_modified  comment
--  ----  ----------------------------------------------------  -------  ----------  -------------  ----------------------
1   3     (.|^)youtube.*$                                       0        1677541300  1679346241      Script Block YouTube
2   3     (.|^)googlevideo.*$                                   0        1677541300  1679346241      Script Block YouTube
3   3     .*youtu.?be.*                                         0        1677541300  1679346241      Script Block YouTube
4   3     (.|^)tiktok.*$                                        0        1677541300  1679346241      Script Block TikTok
5   3     (.|^)tiktok.com$                                      0        1677541300  1679346241      Script Block TikTok
6   3     (.|^)twitch.tv$                                       0        1677541300  1679346241      Script Block Twitch
15  3     (.|^)instagram.*$                                     0        1678699082  1679346241     Script Block Instagram
16  3     (^|.).+(snapchat|sc-cdn|snapkit|snap-dev|snapads).*$  0        1678699587  1679346241     Script Block Snapchat
DNS Restarted
Tue 21 Mar 2023 08:05:01 AEDT# 0
id  type  domain                                                enabled  date_added  date_modified  comment
--  ----  ----------------------------------------------------  -------  ----------  -------------  ----------------------
1   3     (.|^)youtube.*$                                       0        1677541300  1679346301      Script Block YouTube
2   3     (.|^)googlevideo.*$                                   0        1677541300  1679346301      Script Block YouTube
3   3     .*youtu.?be.*                                         0        1677541300  1679346301      Script Block YouTube
4   3     (.|^)tiktok.*$                                        0        1677541300  1679346301      Script Block TikTok
5   3     (.|^)tiktok.com$                                      0        1677541300  1679346301      Script Block TikTok
6   3     (.|^)twitch.tv$                                       0        1677541300  1679346301      Script Block Twitch
15  3     (.|^)instagram.*$                                     0        1678699082  1679346301     Script Block Instagram
16  3     (^|.).+(snapchat|sc-cdn|snapkit|snap-dev|snapads).*$  0        1678699587  1679346301     Script Block Snapchat
DNS Restarted
```

cron is run by sudo ... but I see what you mean about the path
Let me change that and test it.

Thanks.

**Comment by an0wak** [comment]
Hi dschaper,

You are right on the money!
ran ```which pihole``` to get the location of the executable.
added that to my script.
```
/usr/local/bin/pihole restartdns reload-lists
```
Looks like that was the issue! It's been doing my head in for months and was not getting much traction at the community site or others.

Appreciate the extremely quick response time!

**Comment by dschaper** [comment]
> Looks like that was the issue!

Great, glad you found it. 

Just for further enlightenment on what is happening:

`/usr/local/bin/` isn't in the `cron` environment's PATH by default (typically). It's a close mirror of the `root` users PATH and uses `/usr/bin/`. So your two options are to include the full path to the binary or modify `PATH` in the crontab.

We do the second option in our cronjobs.

https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole.cron#L21
```
59 1    * * 7   root    PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updateGravity >/var/log/pihole/pihole_updateGravity.log || cat /var/log/pihole/pihole_updateGravity.log
```
