### ISSUE TITLE
"Disable Blocking" will occasionally fail due to expired session

### ISSUE THREAD

**Issue by anothermindbomb** [pi-hole/pi-hole#5228]
### Versions
 - Pi-hole version is v5.15.5 (Latest: v5.16.1)
 - AdminLTE version is v5.18.4 (Latest: v5.19)
 - FTL version is v5.21 (Latest: v5.22)

### Platform
- OS and version:  Linux raspberrypi 5.10.103-v7l+ 1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
- Platform:  Raspberry Pi

### Expected behavior
When opening the Disable Blocking side menu and selecting any of the "Block for <time>", pihole blocking will be disabled for that time.

### Actual behavior / bug

Spinner appears beside "Disable Blocking" and never vanishes. Message logged into /var/log/lighttpd/error-pihole.log stating:

`2023-03-23 20:09:49: Session expired! Please re-login on the Pi-hole dashboard.
`

Refreshing the dashboard or picking some other menu option and coming back to Disable Blocking, produces the normal behaviour.

### Steps to reproduce

- Leave the dashboard alone for a few minutes (15 or so, I've never timed it to be honest).
- Try to Disable Blocking for 30 seconds
- Watch Spinner spin.
- Refresh the page or pick another menu option.
- Try to Disable Blocking and see it succeed.

## Debug Token

- URL:  
 https://tricorder.pi-hole.net/DarUb3y7/

**Comment by SodaWithoutSparkles** [comment]
A possible explanation would be that "disble blocking" is the only one in the sidebar that does not require a reload of the page. On reload the session cookie might be reset of it was timed out/near time out. Most likely, a refresh would clear the problem
