### ISSUE TITLE
Pi 3B+ becoming unresponsive / running out of memory while updating gravity

### ISSUE THREAD

**Issue by Winni19** [pi-hole/pi-hole#5229]
### Versions

- Pi-hole:  v5.16.1
- AdminLTE:  v5.19
- FTL:  v5.22

### Platform

- OS and version:  Debian 11, 5.10.162-1 (2023-01-21) aarch64

- Platform:  Raspberry Pi 3B+

### Expected behavior

Running "pihole -g" should update gravity.

### Actual behavior / bug

Running "pihole -g" renders my raspberry pi 3b+ unresponsive. Update does not complete since the pi appears to run out of memory during the process. This issue did not apply to former releases.

### Steps to reproduce

Enter "pihole -g" from the command line or select "update gravity" on the dashboard.

**Comment by dschaper** [comment]
Thanks, known issue and we are working on it.

**Comment by SireSalty** [comment]
Having this same issue on a Pi 3B.  Completely crashing the pihole for up to 15 minutes per larger list.

Examples:
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
https://v.firebog.net/hosts/RPiList-Phishing.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt

**Comment by mk-au** [comment]
+1 getting this same issue.

**Comment by maartenlangeveld** [comment]
Tested gravity-test and choking has disappeared.

My one big blocklist (Hagezi Ultimate, ABP-style) is now being processed very very quickly, whereas v5.15.5 choked my system (NanoPi NEO2 1 GB ram, 1GB swap-file, DietPi OS) completely.

Thanks and a big ran of applause for the devs involved fixing this issue!

**Comment by yubiuser** [comment]
Should be fixed by https://github.com/pi-hole/pi-hole/releases/tag/v5.16.2
