### ISSUE TITLE
Unable to remove whitelisted domain beginning with *

### ISSUE THREAD

**Issue by rj45jack** [pi-hole/pi-hole#523]
I white listed a domain using, what I now know is incorrect formatting. I white listed a domain using the following usage `*domainiwhitelisted.com`. Doing this did not white list the domain. So I tried it again using `*.domainwhitelisted.com` and this time it worked. I then tried to remove the `*domainwhitelisted.com` from the white list and it fails to find/remove it.

**Comment by PromoFaux** [comment]
Pi-hole doesn't have the ability to whitelist wildcard domains. Technically this can be achieved with `dnsmasq` but that's something we're still working on...

if you want to add a wildcard domain try adding a new config file (Example: `/etc/dnsmasq.d/02-wildcards.conf` and set up your wildcard domains like so `address=/.domain.tld/YOUR_PI_IP_HERE`

We used to use the `address=` format for ALL domains that Pi-Hole blocks, however [we were seeing huge performance hits using this method](http://jacobsalmela.com/huge-update-to-ad-list-that-the-pi-hole-uses/).

That said, to have a smaller, user controlled list using this method is probably OK. Provided you don't start getting into the thousands. Though even then, you'd need to go through `gravity.list` and remove entries matching the  `*.domainwhitelisted.com` pattern manually. We'll get there!

In the mean time, if you want to tidy it up a bit, just edit `/etc/pihole/whitelist.txt` and remove your wildcard entries from there, before running `pihole -g` to update everything. 

Hope this helps!

**Comment by rj45jack** [comment]
Perfect, thank you :)
