### ISSUE TITLE
Disabling Pihole still blocks domains in ad lists

### ISSUE THREAD

**Issue by random3456345** [pi-hole/pi-hole#5230]
### Versions

Pi-hole version is v5.11.4 (Latest: v5.16.1)
  AdminLTE version is v5.13 (Latest: v5.19)
  FTL version is v5.16.1 (Latest: v5.22):  

### Platform
Raspbian bullseye

- Platform:   Raspberry Pi

### Expected behavior

Domains in ad lists should not blocked when Pihole is disabled

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

### Actual behavior / bug

The domains are not blocked

### Steps to reproduce

1. Disable Pihole
2. Go to a domain that normally blocked 
3. The domain is still blocked after disabling Pihole

## Debug Token

- URL:  https://s.amazon-adsystem.com/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
I just tested and the domains is blocked only when Pi-hole is enabled.

Can you please provide a debug token?

**Comment by random3456345** [comment]
Sorry. It was my mistake.

**Comment by jfb-pihole** [comment]
What was your mistake.  Not posting a debug token, or is the problem now resolved?  If the problem is resolved, what did you do to resolve it?

**Comment by random3456345** [comment]
> What was your mistake. Not posting a debug token, or is the problem now resolved? If the problem is resolved, what did you do to resolve it?

The upstream server was still blocking the domain and I made the mistake of incorectly applying the new non-blocking upstream server.
