### ISSUE TITLE
Upstream DNS Server not resolving

### ISSUE THREAD

**Issue by elhennig** [pi-hole/pi-hole#5233]
### Versions
  Pi-hole version is v5.16.1 (Latest: v5.16.1)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- Platform:  Raspberry Pi

### Expected behavior

Domains should be resolved if I only enable an upstream dns server like my local router

### Actual behavior / bug

At least some domains are not resolved like github.com if I use the pihole service. After switching directly to use the local router as DNS server it works.

### Steps to reproduce

- Set pihole as nameserver in /etc/resolv.conf
- run nslookup github.com

## Debug Token
[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, contact Pi-hole support for assistance.
    * Error message: curl: (6) Could not resolve host: tricorder.pi-hole.net

[✗] There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole/pihole_debug.log

### Additional context
See 
[debug.txt](https://github.com/pi-hole/pi-hole/files/11069113/debug.txt)

**Comment by SodaWithoutSparkles** [comment]
What is your upstream DNS? I was having issues with `cloudflared` DoH and have to use dnscrypt-proxy these few days.

**Comment by elhennig** [comment]
My Upstream DNS server is my Fritzbox router that uses the internet provider's DNS. In my case that is M-net.
the 2 IP v4 servers are 212.18.3.5 und 212.18.0.5

**Comment by SodaWithoutSparkles** [comment]
ISP's DNS servers are known to be problematic. Try switching to public ones such as cloudflare (`1.1.1.1`, `1.0.0.1`), quad9 (`9.9.9.9`, `149.112.112.112`), or google (`8.8.8.8`, `8.4.4.8`)

**Comment by elhennig** [comment]
Just tried that to use openDNS and DNS.Watch servers on the router. 
But as soon as I disable those directly in pihole and only forward alls DNS requests to the fritzbox the behavior is as before. Maybe there is also a problem with the fritzbox OS. I asked the AVM support for help, too
