### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Scrat80** [pi-hole/pi-hole#5237]
### Versions

- Pi-hole:  v5.16.2
- AdminLTE:  v5.19
- FTL:  v5.22

### Platform

- OS and version:  Ubuntu 22.04.1

- Platform:  Proxmox LXC

### Expected behavior

_A clear and concise description of what you expected to happen._
I don't expect to see the following:

There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected '|' in /etc/pihole/pihole-FTL.conf on line 5 in /var/www/html/admin/scripts/pi-hole/php/FTL.php:23 

### Actual behavior / bug
Syntax error

## Debug Token

- URL:  

### Screenshots

See image

I'm not sure how to reproduce the error. I don't know if it came after an OS or Pi-Hole update. Wish I could be of more use there.
<img width="836" alt="Screen Shot 2023-03-27 at 5 08 44 PM" src="https://user-images.githubusercontent.com/43921769/228078918-ab7fa49b-4c5a-4326-8b38-aadeec575170.png">

**Comment by rdwebdesign** [comment]
Please, provide a debug token.

**Comment by Scrat80** [comment]
How?

**Comment by rdwebdesign** [comment]
**Using the command line:**
use `pihole -d` command. When asked to upload the log, answer <kbd>Y</kbd>.
Copy only the token and paste here.

**Using the web interface:**
menu option _Tools > Generate Debug Log_.
Then mark the second checkbox to upload the log and click on the big button.
When finished, copy only the token and paste here.

**Comment by Scrat80** [comment]
Token: 5bFlUfpp

**Comment by rdwebdesign** [comment]
What is the output of `cat /etc/pihole/pihole-FTL.conf`?

**Comment by Scrat80** [comment]
`#; Pi-hole FTL config file
#; Comments should start with #; to avoid issues with PHP and bash reading this file

#  Something to think about in the future. If it affects the viewing of addresses in Pi-Hole, leave it alone.
#  BLOCK_ENSI=true|false - Used to disable deep CNAME inspection

PRIVACYLEVEL=0

#  Set to 10 queries every 12 hours
RATE_LIMIT=1000/60

api2.branch.io
getpocket.cdn.mozilla.net
incoming.telemetry.mozilla.org
spocs.getpocket.com
userlocation.googleapis.com
d.joinhoney.com`

**Comment by rdwebdesign** [comment]
Replace line 5 with:
```diff
- #  BLOCK_ENSI=true|false - Used to disable deep CNAME inspection
+ #;  BLOCK_ENSI=true|false - Used to disable deep CNAME inspection
```

If you read the second line of this same file, it states you need to use `#;` to avoid PHP issues.

**Comment by Scrat80** [comment]
Cheers! *facepalm* Good to know!
