### ISSUE TITLE
Adblock Plus style adlist domain entries with CSS element selector should be ignored

### ISSUE THREAD

**Issue by RoHapp** [pi-hole/pi-hole#5246]
### Versions
- Pi-hole:  v5.16.2
- AdminLTE:  v5.19
- FTL:  v5.22

### Expected behavior

Entries with a CSS element selector should not be blocked.

### Actual behavior / bug

Example line from easylist:
```
coin360.com##.b5BiRm
```
The site `coin360.com` gets blocked because it has entries in the `easylist.txt` following a CSS element selector.  
The CSS selector `##.b5BiRm` is an [element selector](https://adblockplus.org/filter-cheatsheet#elementselection).
Lines containing this selector should be ignored.
The [Extended CSS selectors (Adblock Plus specific)](https://adblockplus.org/filter-cheatsheet#elementhideemulation) should probably also be ignored.

In the lower part of the easylist are a lot of domains affected by this bug.

**Comment by yubiuser** [comment]
Please post the output of `pihole -q coin360.com`

**Comment by RoHapp** [comment]
Output of `pihole -q coin360.com`
```
$ pihole -q coin360.com
 Match found in exact whitelist
   coin360.com
 Match found in https://easylist.to/easylist/easylist.txt:
   coin360.com
   coin360.com
   coin360.com
   coin360.com
   coin360.com
   coin360.com
   coin360.com
```

**Comment by yubiuser** [comment]
Thanks.

This is a tricky task. The reason we see this behaviour is because we remove trailing comments from lists. We do this, because it allows users to annotate (comment) on list entries. This was not an issue so far, because we did not supported any ABP style at all.

https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/gravity.sh#L769

How do you want do discriminate between a user comment (could also have two ## in a row) and a ABP CSS selector?

**Comment by RoHapp** [comment]
Oh, yeah this is tricky. Do you have a example list with such a comment?. I would suspect a comment to have a space or tab before the double pound sign (##).  
Example:
```
example.com ##Great Website
```
Is it a good idea to discriminate with the space or tab before the comment?

**Comment by yubiuser** [comment]
After some internal discussion we're likely going to remove all lines from the input file which contain a patter like `#[?@$](0,1)#.*$`. That should strip out all lines with extended CSS selectors. We're going to do this before removing trailing comment so users can keep existing comments. Only limitation is that comments can't include `##, `#$#`,... anymore.

**Comment by yubiuser** [comment]
```
  [i] Target: https://easylist.to/easylist/easylist.txt
  [✓] Status: Retrieval successful
  [i] List contained AdBlock Plus style domains
  [i] Imported 21534 patterns, ignoring 6178 non-domain entries
      Sample of non-domain entries:
        - -ad-300x600-
        - -ad-336x280-
        - -ad-458x80.
        - -ad-banner-
        - -ad-bottom-

pi@s740:~$ pihole -q coin360.com
  [i] No results found for coin360.com within the adlists


```

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/pi-hole/releases/tag/v5.17
