### ISSUE TITLE
`pgl.yoyo.org` list cannot be used in Adblock Plus format

### ISSUE THREAD

**Issue by xofe** [pi-hole/pi-hole#5248]
### Versions
- Pi-hole:  v5.16.2
- AdminLTE:  v5.19
- FTL:  v5.22

### Platform
- OS and version:  Debian 11 amd64
- Platform:  clean test install running in virtual machine

### Expected behavior
Adding Peter Lowe's list in ABP format as an ad list should download and parse the list as an ABP-format list.

### Actual behavior / bug

Adding Peter Lowe's list in ABP format as an ad list will download and parse the list as a hosts-format list, due to the hard-coded parameters in `gravity.sh` overriding the provided URL:
https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/gravity.sh#L466-L470

### Steps to reproduce

1. Install Pi-hole per instructions in `README.md`, deselecting the default hosts list (for an easier-to-test install).
2. Visit the web interface and add [Peter Lowe's list in ABP format](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext) as an ad list.
3. Run `pihole -q not-a-real-subdomain.doubleclick.net`:
```
  [i] No results found for not-a-real-subdomain.doubleclick.net within the adlists
```
4. Remove `pgl.yoyo.org` case from `gravity.sh` code snippet above, and update Pi-hole lists.
5. Run `pihole -q not-a-real-subdomain.doubleclick.net`:
```
 Match found in https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext:
   ||doubleclick.net^
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/2Jny2ieO/

### Additional context

This list [doesn't include subdomains](https://pgl.yoyo.org/adservers/#I-only-add-highest-level-hostnames), so it's not as effective in hosts format as opposed to ABP format, where the latest versions of Pi-hole will block subdomains (many thanks for this support too!).

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/pi-hole/releases/tag/v5.17
