### ISSUE TITLE
Windows 10 telemetry list Link saying "Not Found"

### ISSUE THREAD

**Issue by Neogx** [pi-hole/pi-hole#525]
##### Expected Behaviour:
To see the list from the url 
##### Actual Behaviour:
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/hosts/windows10_spy.txt
saying "Not Found"

**Comment by Fenisu** [comment]
It appears that the owner of the list changed the path to the hosts file, https://github.com/crazy-max/WindowsSpyBlocker#projects-using-windowsspyblocker

Apparently, this is the correct one.
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt

**Comment by PromoFaux** [comment]
Ah yeah, the owner submitted a pull request to fix that. It will be in the next release!

**Comment by PromoFaux** [comment]
Fixed in 2.7
