### ISSUE TITLE
No flavored Cloudflare DNS options? 

### ISSUE THREAD

**Issue by ecdeveloper** [pi-hole/pi-hole#5262]
It looks like there was an attempt to add the two flavors of Cloudflare DNS -1.1.1.2 (No Malware) & 1.1.1.3 (No Malware or Adult Content) at some point, but then this was reverted by the following commit - https://github.com/pi-hole/pi-hole/commit/e6dcccc7bd0c7c9ce6ad1d1ccaf3184d7edc147c. 

Is there a reason it was reverted? I'm currently using this DNS as a custom DNS record but it would be nice to have it pre-defined in PiHole.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/pi-hole/pull/3276#issuecomment-615928826

**Comment by ecdeveloper** [comment]
Oh, that's a bummer :( 

Thanks, though!

**Comment by yubiuser** [comment]
P.S. You can manually set any pre-filtered upstream as you want in the custom upstream DNS field.

**Comment by ecdeveloper** [comment]
You mean in the custom DNS section on the right hand-side? I'm already doing that, but I thought it's nice to have the commonly known options defined along with Google DNS, Cloudflare, etc on the left side.
