### ISSUE TITLE
Curl not returning correct HTTP code for modified list

### ISSUE THREAD

**Issue by WaLLy3K** [pi-hole/pi-hole#5263]
### Versions
  Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform
Debian GNU/Linux 11 (bullseye) via LXC

### Issue
Previously, https://v.firebog.net/hosts/Prigent-Ads.txt used to have IP addresses found within its list:
![alt](https://media.infosec.exchange/infosecmediaeu/media_attachments/files/110/274/889/130/767/670/original/901d7ad15669b594.png)

I updated my parser today to fix this issue, and flushed the CF cache - so it doesn't have any IP's in it now. When I run a gravity update however, it is incorrectly returning "No changes detected".

Digging into this a bit further, [line 646 of gravity.sh](https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/gravity.sh#L676) runs the following command (more or less):

```
curl --connect-timeout 10 -s -L --compressed  -z /etc/pihole/list.149.v.firebog.net.domains -w %{http_code} -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" https://v.firebog.net/hosts/Prigent-Ads.txt
```

For the sake of reproduction, I've uploaded `list.149.v.firebog.net.domains` here, in order to preserve file modification dates:  https://v.firebog.net/list.149.v.firebog.net.tar.gz

I'm presently finding that the above `curl` command returns `304` instead of `200`.

Thanks ☺️

**Comment by PromoFaux** [comment]
That said - looks like the issue could be server side:

```
root@docker-pihole-pi4:/etc/pihole# ls -lah list.19.*
-rwxrwx--- 1 1001 1001 60K Apr 28 04:35 list.19.v.firebog.net.domains
-rwxrwx--- 1 1001 1001  85 Apr 14 17:10 list.19.v.firebog.net.domains.sha1
root@docker-pihole-pi4:/etc/pihole# curl -s -v -X HEAD https://v.firebog.net/hosts/Prigent-Ads.txt 2>&1 | grep last-modified
< last-modified: Thu, 27 Apr 2023 19:21:29 GMT
```

**Comment by WaLLy3K** [comment]
Unless `list.19.v.firebog.net.domains` is `touch`'d somewhere after being checked and confirmed as "no changes detected", then timezone twattery is about the only thing that makes sense.

I re-ran an update on `Prigent-Ads.txt` which was correctly picked up and updated this time.

`curl -z` is an interesting option to use though. It'll account for the `last-modified` header, but what about if a server just returns `etag`? I've come across that a couple of times, which is why I'll store the `last-modified` or `etag` and if neither exist, compare a hash against a generated hash of the upstream copy that's been temporarily cached locally.
