### ISSUE TITLE
Windows wont cache Local DNS record

### ISSUE THREAD

**Issue by SeimusS** [pi-hole/pi-hole#5265]
Hello all,

Sorry for this topic but I have a question.

I have created several Local DNS Records so I can access them from browsers instead of typing the IP.

However I observed that for example Windows based PC wont cache such entry which results in flooding the PiHole. It floods in such a way it even hits the default Rate-Limit.

Is this a normal behaviour?

**Comment by jfb-pihole** [comment]
The TTL (time to live) for these entries is zero, by default, so what you are seeing is normal. 

From the dnsmasq manual (https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html):

-T, --local-ttl=<time>
When replying with information from /etc/hosts or configuration or the DHCP leases file dnsmasq by default sets the time-to-live field to zero, meaning that the requester should not itself cache the information. This is the correct thing to do in almost all situations. This option allows a time-to-live (in seconds) to be given for these replies. This will reduce the load on the server at the expense of clients using stale data under some circumstances.

You can change this with a new dnsmasq configuration file in directory -***/etc/dnsmasq.d***.

**Comment by SeimusS** [comment]
@jfb-pihole Many thanks!

I totaly forgot to look into this within the dnsmasq manual!

Many thanks again and sorry for opening such silly ticket.

**Comment by SeimusS** [comment]
Issue fixed / Tunned by implementing "local-ttl=" into /etc/dnsmasq.d

```
#-T, --local-ttl=<time>
#When replying with information from /etc/hosts or configuration or the DHCP leases file dnsmasq by default sets the time-to-live field to zero, meaning that the requester should not itself cache the information.
#This is the correct thing to do in almost all situations.
#This option allows a time-to-live (in seconds) to be given for these replies.
#This will reduce the load on the server at the expense of clients using stale data under some circumstances.
# You can change this with a new dnsmasq configuration file in directory -/etc/dnsmasq.d.

local-ttl=300
```

**Comment by SeimusS** [comment]
Once again thank you for help!

Regards,
S.
