### ISSUE TITLE
Adding Local DNS Records does not add to /etc/pihole/custom.list

### ISSUE THREAD

**Issue by MrDuck2742** [pi-hole/pi-hole#5268]
### Versions

  Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform

- OS and version:  Manjaro

- Platform:  Raspberry Pi4

### Expected behavior

Adding DNS record adds entry to /etc/pihole/custom.list

### Actual behavior / bug

Record not added to /etc/pihole/custom.list

### Steps to reproduce

1. Go to "admin/dns_records.php" i.e. "Local DNS Records [A/AAAA]" i.e. Local DNS -> DNS Records page
2. Enter "Domain" and "IP Address"
3. Click "Add"
4. Note entry not added to "List of local DNS domains"

## Debug Token 

- URL:  

"Pi-hole debug options are disabled.

ArchLinux distribution of Pi-hole is not supported by official project and this debug report CAN NOT be uploaded to their debug team."

### Additional context

```
# /usr/bin/pihole -a addcustomdns 172.16.0.1 test.telegram.org false
  [✓] Adding custom DNS entry...
  [✗] Invalid Domain passed!
```

Issue may be related to:

[Code](https://github.com/pi-hole/pi-hole/blob/3c86af0e5938e5b03bc12abe9563b8d1efa113d8/advanced/Scripts/webpage.sh#L620)

```
checkDomain()
{
    local domain validDomain
    # Convert to lowercase
    domain="${1,,}"
    validDomain=$(grep -P "^((-|_)*[a-z\\d]((-|_)*[a-z\\d])*(-|_)*)(\\.(-|_)*([a-z\\d]((-|_)*[a-z\\d])*))*$" <<< "${domain}") # Valid chars check
    validDomain=$(grep -P "^[^\\.]{1,63}(\\.[^\\.]{1,63})*$" <<< "${validDomain}") # Length of each label
    echo "${validDomain}"
}
```

**Comment by MrDuck2742** [comment]
After some debugging:

grep 3.10 seems to break Perl regexp used by checkDomain function in webpage.sh

Downgrading to grep 3.9 resolves issue.

pacman -U grep-3.9-1-aarch64.pkg.tar.xz

`/usr/bin/pihole -a addcustomdns 172.16.0.1 test.telegram.org false
  [✓] Adding custom DNS entry...`

Note sure if this incorrect behaviour by grep 3.10 or incorrect checkDomain regexp code (fixed by grep 3.10)

**Comment by MrDuck2742** [comment]
This works:

`checkDomain()
{
    local domain validDomain
    # Convert to lowercase
    domain="${1,,}"
    validDomain=$(grep -P '^(?=.{1,253}\.)[a-zA-Z0-9](?:(?!-)[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9](?:(?!-)[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$' <<< "${domain}")
    echo "${validDomain}"
}
`

**Comment by MrDuck2742** [comment]
Finally some improvements to work with both grep 3.9 and 3.10 and RFC 1034 definitions:

```
checkDomain()
{
    local domain validDomain
    # Convert to lowercase
    domain="${1,,}"
    validDomain=$(grep -Pi '^(?=.{1,255}$)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$' <<< "${domain}")
    echo "${validDomain}"
}
```

GPT Chat description:

^ is the start-of-string anchor that ensures that the regular expression starts matching from the beginning of the string.
(?=.{1,255}$) is a positive lookahead that ensures that the length of the string is between 1 and 255 characters. It does not consume any characters in the string.

(?: ... )+ is a non-capturing group that contains the pattern for a domain name. The group is repeated one or more times using the + quantifier. This ensures that the string contains at least one domain name.

[a-z\d] matches any lowercase letter or digit. This ensures that the first character of a label is a letter or a digit.

(?:[a-z\d-]*[a-z\d])? is an optional non-capturing group that matches additional characters in a label. It can contain any number of letters, digits, or hyphens, as long as it ends with a letter or a digit. The ? quantifier makes the group optional.
\.? matches an optional dot at the end of a label. This allows the domain name to end with a trailing dot, although this is optional according to the RFC 1034 standard.

[a-z]{2,} matches at least two lowercase letters at the end of the domain name. This ensures that the domain name ends with a valid top-level domain (TLD).

$ is the end-of-string anchor that ensures that the regular expression matches up to the end of the string.
Overall, this regular expression is designed to match valid domain names according to the RFC 1034 standard. It ensures that the domain name contains at least one label, that each label starts with a letter or a digit, and that each label can contain letters, digits, or hyphens. It also ensures that the domain name ends with at least two letters to represent a valid TLD.

**Comment by yubiuser** [comment]
Thanks for digging. So we basically could just replace `\d` with `0-9` to fix the issue on grep 3.10?

**Comment by MrDuck2742** [comment]
I recon that should do it ... yep

**Comment by yubiuser** [comment]
Do you want to open a PR to fix the issue?

**Comment by MrDuck2742** [comment]
I'll give it a go!

This does work with grep 3.10:

```
checkDomain()
{
    local domain validDomain
    # Convert to lowercase
    domain="${1,,}"
    validDomain=$(grep -P "^((-|_)*[a-z0-9]((-|_)*[a-z0-9])*(-|_)*)(\\.(-|_)*([a-z0-9]((-|_)*[a-z0-9])*))*$" <<< "${domain}") # Valid chars check
    validDomain=$(grep -P "^[^\\.]{1,63}(\\.[^\\.]{1,63})*$" <<< "${validDomain}") # Length of each label
    echo "${validDomain}"
}
```

**Comment by jfb-pihole** [comment]
Please vote that you are running an unsupported OS.

**Comment by PromoFaux** [comment]
That as may be... this is useful information - should any of our officially supported distros update to using grep 3.10. It makes sense that we would look to incorporate a fix in the main repo rather than just punting it towards the arch distribution

|OS|grep version|
|:--|:---|
|Debian 10|3.3|
|Debian 11|3.6|
|Fedora 36| 3.7|
|Fedora 37| 3.7|
|Ubuntu 20.04|3.4|
|Ubuntu 22.04|3.7|
|Centos 8 stream|3.1|
|Centos 9 stream|3.1|

@MrDuck2742 above is a list of the supported distros (from [here](https://docs.pi-hole.net/main/prerequisites/)) and the version of grep that currently is supported on those distros (from [here](https://pkgs.org/search/?q=grep))

As long as your solution remains compatible with all those versions of grep, then we should be OK

**Comment by MrDuck2742** [comment]
FYI:

[GNU bug report logs - #62605 `[\d]` does not work with PCRE](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62605)

**Comment by MrDuck2742** [comment]
> Please vote that you are running an unsupported OS.
> 
> "ArchLinux distribution of Pi-hole is not supported by official project..."

How do i vote ... ?

**Comment by yubiuser** [comment]
It's likely a typo vote> note.

**Comment by MrDuck2742** [comment]
Great! Nice to be able to help out ...

**Comment by PromoFaux** [comment]
@MrDuck2742 - See this issue here: https://github.com/pi-hole/pi-hole/issues/5290

Something is not quite right with the new pattern, and regrettably I missed it in my testing
