### ISSUE TITLE
Upstream DNS Servers Active or Standby

### ISSUE THREAD

**Issue by luweijun1992** [pi-hole/pi-hole#5276]
### Versions

- Pi-hole:  v5.16.2
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  Docker

---

Is it possible to set up the active and standby upstream DNS servers?
When the primary upstream dns fails and cannot return, the backup upstream dns server will be used.

**Comment by rdwebdesign** [comment]
This is not how devices use DNS servers.

Usually, when you advertise 2 (or more) DNS servers each device (actually the OS) will choose which one will be used. 
Some will use the first one, if available. Some will choose one at random. Others will alternate between the servers.

Of course, if one server is down the other(s) will be used, but when all are available, all will be used.

**Comment by luweijun1992** [comment]
> This is not how devices use DNS servers.
> 
> Usually, when you advertise 2 (or more) DNS servers each device (actually the OS) will choose which one will be used. Some will use the first one, if available. Some will choose one at random. Others will alternate between the servers.
> 
> Of course, if one server is down the other(s) will be used, but when all are available, all will be used.

Because the upstream server is an internal dns server.
It is hoped that when the upstream dns server fails, it can be switched to the backup dns (Internet public dns).

**Comment by rdwebdesign** [comment]
> It is hoped that when the upstream dns server fails, it can be switched to the backup dns

This is not how it works.
