### ISSUE TITLE
Block Command & Control servers from various Ransomware

### ISSUE THREAD

**Issue by brantje** [pi-hole/pi-hole#528]
Hi,
This list: https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
Lists all known domains of C&C servers that control the following virusses:
- TeslaCrypt
- CryptoWall
- TorrentLocker
- PadCrypt
- Locky
- CTBLocker
- FAKBEN
- PayCrypt
- DMALocker

Would it be possible to include this list in pihole?

**Comment by PromoFaux** [comment]
I don't see why not. Perhaps not as a default, but it can be added (commented out) to `adlists.default` to give users the option of adding it!

**Comment by PromoFaux** [comment]
That said, after a quick glance through the list (with only 174 domains) There doesn't look to be any legitimate domains on there, So it could also be included as a default list

**Comment by PromoFaux** [comment]
Added in next release, thanks!
