### ISSUE TITLE
Unable to resolve local domain without point.

### ISSUE THREAD

**Issue by DenuxPlays** [pi-hole/pi-hole#5280]
### Versions

- Pi-hole:  5.16.2
- AdminLTE:  5.19
- FTL:  5.22

### Platform

- OS and version:  Rasbian 10

- Platform:  Raspberry Pi 3b+

### Expected behavior

Pi hole should be able to resolve the domain correctly.

### Actual behavior / bug

If you lookup the domain (in my case its `pc`) it returns an error that pi hole cannot resolve it:
![image](https://github.com/pi-hole/pi-hole/assets/83671398/3a96c792-388e-43f9-8c86-0c3d417970d0)

### Steps to reproduce

1. Go to local dns
2. Add the following line: 
![image](https://github.com/pi-hole/pi-hole/assets/83671398/91ecfc81-da69-46d0-941c-f93d52f035f1)
3. nslookup the domain or try to access it.

## Debug Token

- URL:  https://tricorder.pi-hole.net/oXycNPFr/

### Screenshots

My local dns setup:
![image](https://github.com/pi-hole/pi-hole/assets/83671398/7df2a3a1-8cf1-424c-a36b-1d318d8ac53e)

Nslookup:
![image](https://github.com/pi-hole/pi-hole/assets/83671398/2bb3cf46-5b88-49d5-bbd7-0fddc2e0b526)

### Additional context

[DoH](https://docs.pi-hole.net/guides/dns/cloudflared/) is activated if this has something to do with that.

**Comment by jfb-pihole** [comment]
Why are you trying to assign the PC the loopback IP?  That IP is already in use by the OS on the Pi.

**Comment by DenuxPlays** [comment]
> Why are you trying to assign the PC the loopback IP? That IP is already in use by the OS on the Pi.

Just as an example.
A friend of mine tried something like this (idk what their usecase was exactly) so this is just an "example".
Replace localhost with `192.168.178.120` and you'll get the same result.

**Comment by rdwebdesign** [comment]
I'm not sure if this is a limitation of Windows `nslookup` (I'm guessing here).

I tested using my Pi-hole install.
I created a new entry in "Local DNS Record" page, called `pc` pointing to `192.168.0.6`.

Running `nslookup pc` from 2 different Linux clients I got:
```console
root@pi4:~ # nslookup pc
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   pc
Address: 192.168.0.6
```

But running the same command from Windows command line I got:
```yaml
C:\Windows\System32>nslookup pc
Servidor:  pi.hole
Address:  192.168.0.201

*** pi.hole can't find pc: Non-existent domain
```

**Comment by rdwebdesign** [comment]
**NOTE:**

Actually, every domain ends with an implicit dot, but we never use it.

If you add the dot, the Windows `nslookup` will show the expected answer:

```yaml
C:\Windows\System32>nslookup pc.
Servidor:  pi.hole
Address:  192.168.0.201

Name:    pc
Address:  192.168.0.6
```

**Comment by DenuxPlays** [comment]
Yeah its windows. Can confirm this.
Ran fedora in wsl and tried nslookup and got the expected answer.
![image](https://github.com/pi-hole/pi-hole/assets/83671398/0386b618-51d7-4249-94ee-6917f52e1dbb)

Thank you for your help :)
