### ISSUE TITLE
Teleporter Backup function succeeds on connected Windows GUI client but fails on RaspberryPi server CLI

### ISSUE THREAD

**Issue by veaseym** [pi-hole/pi-hole#5285]
### Versions

- Pi-hole:  5.16.2
- AdminLTE:  N/A
- FTL:  5.2.2

### Platform

- OS and version:  Raspberry Pi OS bullseye

- Platform:  Raspberry Pi 4

### Expected behavior

Running `pihole -a -t` on the CLI as root should produce a viable backup .tar.gz file.

### Actual behavior / bug

`pihole -a -t` on the CLI as root produces a corrupted .tar.gz file - it is only 82 bytes in size and cannot be unpacked. Running the equivalent Teleport / Backup command on a connected Windows client produces a viable .tar.gz file which can be moved to the RPi and unpacked safely.

### Steps to reproduce

1. sudo as root
2. `cd /tmp`
3. `pihole -a -t`

## Debug Token

- URL:  https://tricorder.pi-hole.net/DSsgt7L4/

### Screenshots

RPi native CLI:

```
root@raspberrypi:/tmp# pihole -a -t
root@raspberrypi:/tmp# ls -al

-rw-r--r--  1 root root   82 May 25 13:30 pi-hole-raspberrypi-teleporter_2023-05-25_13-30-08.tar.gz

root@raspberrypi:/tmp# tar xvfz pi-hole-raspberrypi-teleporter_2023-05-25_13-30-08.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Windows GUI extracts when moved to RPi box:

```
root@raspberrypi:/tmp# tar xvfz pi-hole-raspberrypi-teleporter_2023-05-25_12-09-08.tar.gz
root@raspberrypi:/tmp# ls -al

whitelist.exact.json
whitelist.regex.json
blacklist.exact.json
blacklist.regex.json
adlist.json
domain_audit.json
group.json
client.json
domainlist_by_group.json
adlist_by_group.json
client_by_group.json
setupVars.conf
dhcp.leases
custom.list
pihole-FTL.conf
etc/hosts
dnsmasq.d/01-pihole.conf
dnsmasq.d/06-rfc6761.conf
```

**Comment by veaseym** [comment]
Thanks for looking at this.

When running `pihole -a -t` as the regular user, I get the same behaviour as reported with root: an 82 byte .tar.gz file. Curiously, the file produced is owned by root, even if run as the regular user.

As to why - I'm looking to integrate the CLI `pihole -a -t` command into my regular backup regime for the RPi - whilst the pihole backup might not need superuser privileges, other aspects of the broader scripting will.

> Why are you doing this as root? Did it not work when you are logged in as your regular user?

**Comment by yubiuser** [comment]
I can't reproduce this on my installation.

What is the output of `file pi-hole......tar.gz`

**Comment by veaseym** [comment]
Thanks yubiuser - I think you have it.

`file pi-hole......tar.gz` output indicates an ASCII file, so using `cat`:

`Could not open input file: /var/www/html/admin/scripts/pi-hole/php/teleporter.php`

On installation, I moved the pihole `/var/www/html` directory away from the default `admin` sideways to another directory. The (Apache) .conf file was easy to change, but the CLI had no way to follow the change as the path to `teleporter.php` is hardcoded into `/opt/pihole/webpage.sh`

A bit of rearranging, putting the pihole `/var/www/html` directory back to the default fixed the problem for me.
