### ISSUE TITLE
Integration with YunoHost

### ISSUE THREAD

**Issue by anmol26s** [pi-hole/pi-hole#529]
Hi

I run a yunohost server which uses nginx. I installed Pi-hole on it, but it broke my nginx. Can you please integrate it with YunoHost so that it is easier to run Pi-hole on the nginx from just a command.
Thanks.
Useful links-
https://forum.yunohost.org/t/pihole-dns-adware-filter-not-on-yunohost/1618
https://forum.yunohost.org/t/news-about-app-management-and-packaging-in-yunohost-2-4/1379
https://yunohost.org/apps
##

**Comment by dschaper** [comment]
Thanks, we'll take a look at the configuration, but one of the requirements for the Pi-Hole is that we are running a webserver on port 80. If you have an existing web server, then you either need to change the existing server to listen on another port, or set up another IP address for your Pi and run the two servers on differing IP addresses. 

The reason we need port 80 is that we are masquerading as the ad serving hosts, so we need to appear to your web browser as the actual webserver from the ad server. This means that we respond to your browsers http requests to port 80 of the ad server. This is dictated by the http standards. 

As for your question on the yunohost forum, to uninstall the Pi-Hole, there is a `pihole uninstall` command that should reverse out the changes.

**Comment by jacobsalmela** [comment]
Closing.  Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/integrate-with-yunohost/559) so this feature is votable.
