### ISSUE TITLE
"pihole -v" shows that there is a new version, but "pihole -up" says that it is up to date

### ISSUE THREAD

**Issue by darkmanlv** [pi-hole/pi-hole#5297]
### Versions
  Pi-hole version is v5.16.2 (Latest: v5.17.1)
  AdminLTE version is v5.19 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform
- OS and version:  
Debian GNU/Linux 11 (Raspberry Pi OS)
- Platform:  
Raspberry Pi

### Expected behavior

update must be downloaded and installed

### Actual behavior / bug

pihole -up shows that no need to update

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

### Steps to reproduce

pihole -v
pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/Ku1Mcpxz/

**Comment by rdwebdesign** [comment]
The new release was created around an hour ago.

`pihole -v` information is updated once a day, but apparently it was not yet updated on your system.

Options:
1. wait for pi-hole update the information.
2. run `pihole updatechecker` to update the versions file.
3. run `pihole -up`, even if the version information is outdated. The command itself will verify if there is a new version.

**Comment by darkmanlv** [comment]
> The new release was created around an hour ago.

but adminlte updated already 2 days ago

> 2. run `pihole updatechecker` to update the versions file.

did many times

> 3. run `pihole -up` again, even if the version information is outdated. The command itself will verify if there is a new version.

nothing changing, will try tomorrow, but AdminLTE not updating already 2 days

`pi@raspberrypi:~ $ sudo pihole updatechecker
pi@raspberrypi:~ $ sudo pihole -v
  Pi-hole version is v5.16.2 (Latest: v5.17.1)
  AdminLTE version is v5.19 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
pi@raspberrypi:~ $ sudo pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
`

**Comment by rdwebdesign** [comment]
> but adminlte updated already 2 days ago

It was updated again.

---

Your `versions` file is missing a few values (`_HASH` variables):
```
-rw-r--r-- 1 root root 299 May 30 22:30 /etc/pihole/versions
   CORE_VERSION=v5.16.2
   CORE_BRANCH=master
   CORE_HASH=d885e926
   GITHUB_CORE_VERSION=v5.17.1
   GITHUB_CORE_HASH=
   WEB_VERSION=v5.19
   WEB_BRANCH=master
   WEB_HASH=d7f18428
   GITHUB_WEB_VERSION=v5.20.1
   GITHUB_WEB_HASH=
   FTL_VERSION=v5.23
   FTL_BRANCH=master
   FTL_HASH=d201776e
   GITHUB_FTL_VERSION=v5.23
   GITHUB_FTL_HASH=
```

**Comment by darkmanlv** [comment]
What about this variables? How to fix them?

Still the same today, tried now. 

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

**Comment by yubiuser** [comment]
My guess is: You're up-to-date (as indicated by `pihole -up`) but your versions file is out-of-date here (supported by the missing `HASH`) .

Please switch into `/etc/.pihole` and run `git rev-parse "@{0}"` (This should give us the current `core` version you're actually running).

__

Please also run `sudo bash -x /opt/pihole/updatecheck.sh` and post the output.

**Comment by rdwebdesign** [comment]
Please, run these 3 command and post the output:

```
git ls-remote https://github.com/pi-hole/pi-hole --tags master
git ls-remote https://github.com/pi-hole/AdminLTE --tags master
git ls-remote https://github.com/pi-hole/FTL --tags master
```

**Comment by yubiuser** [comment]
Ok, so the local repo is really on `16.2`. So the issue must be in the updater. Let's see what the above commands yield.

**Comment by yubiuser** [comment]
@darkmanlv 

Please also run `pihole -q github.com`

**Comment by darkmanlv** [comment]
> git ls-remote https://github.com/pi-hole/FTL --tags master

nothing after running this commands

pi@raspberrypi:/etc/.pihole $ git ls-remote https://github.com/pi-hole/pi-hole --tags master
pi@raspberrypi:/etc/.pihole $ sudo git ls-remote https://github.com/pi-hole/pi-hole --tags master
pi@raspberrypi:/etc/.pihole $ sudo git ls-remote https://github.com/pi-hole/AdminLTE --tags master
pi@raspberrypi:/etc/.pihole $ git ls-remote https://github.com/pi-hole/FTL --tags master
pi@raspberrypi:/etc/.pihole $ sudo git ls-remote https://github.com/pi-hole/FTL --tags master

**Comment by yubiuser** [comment]
It's strange that the `ls-remote` commands did not produce any output, not even an error. Can you please check their exit codes?

```
git ls-remote https://github.com/pi-hole/pi-hole --tags master
echo $?
```

**Comment by darkmanlv** [comment]
> git ls-remote https://github.com/pi-hole/pi-hole --tags master
> echo $?

pi@raspberrypi:~ $ git ls-remote https://github.com/pi-hole/pi-hole --tags master
echo $?
128

**Comment by rdwebdesign** [comment]
I think this is an authentication issue. 

Are you able to access any other public Github repo?
`git ls-remote <other_Github_repo_of_your_choice>`

**Comment by darkmanlv** [comment]
> I think this is an authentication issue.
> 
> Are you able to access any other public Github repo? `git ls-remote <other_Github_repo_of_your_choice>`

same, 128

pi@raspberrypi:~ $ git ls-remote https://github.com/YouROK/TorrServer --tags master
pi@raspberrypi:~ $ echo $?
128

**Comment by rdwebdesign** [comment]
I'm not sure what is wrong with your `git` configuration, but this is not a Pi-hole bug.

My suggestion is to search for `git ls-remote 128` or `"git ls-remote" 128` on the Internet.

**Comment by darkmanlv** [comment]
thanks, problem fixed, problem with git.... 

fixed by 'sudo apt-get purge git; sudo apt-get autoremove; sudo apt-get install git'
