### ISSUE TITLE
Updating Available Packages Fails in Mint 21

### ISSUE THREAD

**Issue by Soumil32** [pi-hole/pi-hole#5298]
### Versions

- Pi-hole:  5.17
- AdminLTE:  5.20.1
- FTL:  5.23

### Platform

- OS and version:  Linux Mint 21

- Platform:  Personal Desktop

### Expected behavior

Both the install script and update script first check for package updates using `apt update`. This should receive update information and proceed with the rest of the script.

### Actual behavior / bug

Both scripts fail with the error 
```bash
   Error: Unable to update package cache. Please try "sudo apt update"
```
This happens even when I run the scripts with sudo.
### Steps to reproduce

- Run the automated install script either using curl directly or downloading it first (fails)
- Or try updating an existing install using `pihole -up` (fails)

## Debug Token

- URL:  https://tricorder.pi-hole.net/VsKackan/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

To install pihole in the first place I had to download the install script and remove the code which updates packages.

**Comment by yubiuser** [comment]
Linux Mint is not a supported Distro.

```
** [ DIAGNOSING ]: Operating system
[✗] Distro:  Linuxmint
[✓] dig return code: 0
[i] dig response: "Raspbian=10,11 Ubuntu=20,22,23 Debian=10,11 Fedora=36,37,38 CentOS=8,9"
[✗] Error: Linuxmint is not a supported distro (https://docs.pi-hole.net/main/prerequisites/)
```

**Comment by PromoFaux** [comment]
>    Error: Unable to update package cache. Please try "sudo apt update"

There is a problem updating the package cache. Running the suggested command will point you in the right direction
