### ISSUE TITLE
Find Blocked Domain In Lists doesn't allow "-all" in search string

### ISSUE THREAD

**Issue by BornToBeRoot** [pi-hole/pi-hole#5299]
### Versions

- Pi-hole:  5.16.2
- AdminLTE:  5.19
- FTL:  5.22

### Platform
Docker

### Expected behavior

A domain like `test-alltest.com` will search for `testtest.com` (The `-all` is removed 😄): 

![image](https://github.com/pi-hole/pi-hole/assets/16019165/5da27cfb-720e-4f5b-8162-bf6a1db0eb71)

**Comment by yubiuser** [comment]
The fix is pretty simple, but I'll target it to the v6 branch.
