### ISSUE TITLE
TrackerControl messes with Pi-Hole (dnsmasq to be exact)

### ISSUE THREAD

**Issue by DevelopingEntitiesWithFuntations** [pi-hole/pi-hole#5301]
In the web GUI I keep getting this error:
```
DNSMASQ_WARN	Warning in dnsmasq core:

ignoring query from non-local network 10.1.10.1 (logged only once)

Check out our documentation for further information.
```

I managed to debug why this strange behaviour is happening - namely the Android application TrackerControl uses a VPN internally and sets the IP to 10.1.10.1.

How do I setup this correctly to handle this error properly?

**Comment by yubiuser** [comment]
Please vitis our forum at https://discourse.pi-hole.net/ for help regading configuration issues.
