### ISSUE TITLE
homepage uses third-party scripts and google static

### ISSUE THREAD

**Issue by LoveIsGrief** [pi-hole/pi-hole#5302]
When the scripts are blocked (I blackhole google static + have µblock + firefox block third party domains), then it looks like below.

![image](https://github.com/pi-hole/pi-hole/assets/2829538/9ae1b8e7-8197-422b-8b15-cee97cb0d53d)

It'd be great if the website used first-party scripts and didn't use google services for the fonts (which should be small, right?)

**Comment by dschaper** [comment]
Thanks for the comment. We use a CDN for the site so your restrictions are what is causing the breakage.
