### ISSUE TITLE
Unsupported OS detected: Ubuntu 22.04

### ISSUE THREAD

**Issue by origamiofficial** [pi-hole/pi-hole#5303]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.22 (Latest: v5.23)

### Platform

- OS and version:  Ubuntu 22.04 LTS

- Platform:  x86_64

### Expected behavior

`pihole -up` should just update Pi-hole.

### Actual behavior / bug

It shows `[✗] Unsupported OS detected: Ubuntu 22.04` but Ubuntu 22.04 is on the supported list.
Terminal Log:
```bash
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] SELinux not detected
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 8.1.2-1ubuntu2.11

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✗] Unsupported OS detected: Ubuntu 22.04
      If you are seeing this message and you do have a supported OS, please contact support.

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


  Unable to complete update, please contact Pi-hole Support
  ```

### Steps to reproduce

1. Run `pihole -up`
2. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/ChIntnGS/

### Screenshots

N/A

### Additional context

N/A

**Comment by rdwebdesign** [comment]
There is a very similar issue on our Discourse forum.

Please try the solution suggested here:
https://discourse.pi-hole.net/t/unsupported-os-detected-upon-pi-hole-update-w-ubuntu-22-04/63161/8

**Comment by vgdh** [comment]
have the same issue
`
 [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     update available
  [i] Web Interface:    update available
  [i] FTL:              update available

  [i] Pi-hole core files out of date, updating local repo.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...HEAD is now at 6a45c6a v5.17.1 (#5295)
  [✓] Update repo in /etc/.pihole

  [i] If you had made any changes in '/etc/.pihole/', they have been stashed using 'git stash'

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...HEAD is now at 3a11976 5.20.1 (#2598)
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] SELinux not detected
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✗] Retrieval of supported OS list failed. dig succeeded, but response was blank. Please contact support. 
      Unable to determine if the detected OS (Debian 11) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


  Unable to complete update, please contact Pi-hole Support
`

**Comment by rdwebdesign** [comment]
@vgdh 

Your error message is completely different:
```log
[✗] Retrieval of supported OS list failed. dig succeeded, but response was blank. Please contact support.
Unable to determine if the detected OS (Debian 11) is supported
Possible causes for this include:
- Firewall blocking certain DNS lookups from Pi-hole device
- ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
- Other internet connectivity issues
```

You have a different issue.
Apparently there is something blocking `ns1.pi-hole.net` (firewall, Pi-hole list, etc.) or even a temporary connection issue.

**Comment by origamiofficial** [comment]
After disabling the IPV6 it fixed the issue!!

> There is a very similar issue on our Discourse forum.
> 
> Please try the solution suggested here: https://discourse.pi-hole.net/t/unsupported-os-detected-upon-pi-hole-update-w-ubuntu-22-04/63161/8
