### ISSUE TITLE
FATAL ERROR in dnsmasq core: failed to create listening socket for port 53: Address already in use

### ISSUE THREAD

**Issue by sgreadly** [pi-hole/pi-hole#5315]
### Versions
  Pi-hole version is v5.17.1 (Latest: N/A)
  AdminLTE version is v5.20.1 (Latest: N/A)
  FTL version is v5.23 (Latest: N/A)

### Platform
RaspberryOS (Debian 11 Bullseye)
Linux hop4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Raspberry Pi 4.

### Expected behavior

Pihole-FTL to start successfully and listen to :53.

### Actual behavior / bug

Pihole fails to start, as another daemon (connmand) is already listening.

`FATAL ERROR in dnsmasq core: failed to create listening socket for port 53: Address already in use`

```console
● pihole-FTL.service - Pi-hole FTL
     Loaded: loaded (/etc/systemd/system/pihole-FTL.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-06-14 14:48:04 NZST; 1s ago
    Process: 3299 ExecStartPre=/opt/pihole/pihole-FTL-prestart.sh (code=exited, status=0/SUCCESS)
    Process: 3312 ExecStart=/usr/bin/pihole-FTL -f (code=exited, status=2)
    Process: 3316 ExecStopPost=/opt/pihole/pihole-FTL-poststop.sh (code=exited, status=0/SUCCESS)
   Main PID: 3312 (code=exited, status=2)
        CPU: 786ms
```

```console
$ sudo netstat -nltup | grep 'Proto\|:53 \|:67 \|:80 \|:471'
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      513/connmand
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      901/nginx: master p
tcp6       0      0 ::1:53                  :::*                    LISTEN      513/connmand
tcp6       0      0 :::80                   :::*                    LISTEN      901/nginx: master p
udp        0      0 127.0.0.1:53            0.0.0.0:*                           513/connmand
udp6       0      0 ::1:53                  :::*                                513/connmand
```

### Steps to reproduce

I'm not sure how to reproduce this, I think this issue is there by default? I notice after I do the workaround, few times a year it happens again especially after daemon updates. 

The workaround is to add "**--nodnsproxy**" to connmand when it starts.

$ cat /etc/systemd/system/multi-user.target.wants/connman.service
<snip>
[Service]
Type=dbus
BusName=net.connman
Restart=on-failure
**ExecStart=/usr/sbin/connmand -n --nodnsproxy**
StandardOutput=null
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SYS_TIME CAP_SYS_MODULE
ProtectHome=true
ProtectSystem=full
<snip>

## Debug Token

- URL:  https://tricorder.pi-hole.net/rW2f88Vv/

### Screenshots

N/A

### Additional context

What I'm asking for or about is a more 'proper' or correct / permanent way of having this fixed. As it seems on RaspberryOS it frequently happens. I've seen a few other threads where other users seem to trigger this on a new install too.

**Comment by DL6ER** [comment]
> I think this issue is there by default?

It's not. `connmand` should not be installed by default but is something you have to install manually (please correct me if I'm wrong). I' afraid your workaround is the most appropriate solution if you want to have both installed - *unless* there is another way of telling this (in a more permanent way) to `connmand` in a config file. Since I'm not familiar with this software, I cannot really tell, however, when looking at the `man` page, it doesn't appear to be supported and you'd have to do exactly what you did.

**Comment by sgreadly** [comment]
Thanks @DL6ER ,

You're right. dhcpcd is the default that comes with. I forgot that I replaced it with Connman a while back. 

I recall asking and was told Connman will be replacing NetworkManager in due time, but I can't find anything that backs this up. 

Yes googling more, it does seem like Connman irritatingly overtakes port 53, like it or not :/ 

I guess we'll have to live with the workaround for the time being.
