### ISSUE TITLE
Pi-Hole DNS filtering periodically fails without generating readable diagnosis

### ISSUE THREAD

**Issue by korgano** [pi-hole/pi-hole#5316]
### Versions
- Pi-hole:  v5.17.1
- AdminLTE:  v5.20.1
- FTL:  v5.23

### Platform
- OS and version: Debian 11
- Platform: Raspberry Pi

### Expected behavior

-Pi-Hole functions 24 hours a day, blocking DNS queries to domains on block list.
-In case of failures, notifications are generated.
-Data entries of errors appear in Pi-Hole Diagnosis

### Actual behavior / bug

-Pi-Hole DNS filtering ceases at some time (variable)
-An error notification may or may not be generated
-Data entries do not appear in Pi-Hole Diagnosis
-WiFi connections function, allowing internet access
-DNS filtering resumes when Pi-Hole/Raspberry Pi restarted

### Steps to reproduce

Unknown, uncertain what is causing the behavior

## Debug Token

- URL:  https://tricorder.pi-hole.net/SEmbmEPy/

### Screenshots

![pi-hole-utilization](https://github.com/pi-hole/pi-hole/assets/1180905/af277b92-ca82-427d-8382-d15548d072ac)

### Additional context

Pi-Hole is connected to TP-Link Deco WiFi Mesh router, and has cooling fan. However, I cannot rule out potential router issues or thermal throttling, as it is summer in my location.

**Comment by rdwebdesign** [comment]
Your router is advertising 2 different DNS servers: Pi-hole and `1.1.1.2`.

This will cause Pi-hole to be bypassed (even if Pi-hole is working).
I can't tell for sure if this is the issue here, but it's a possibility.
