### ISSUE TITLE
[Suggestion] Add snap package support

### ISSUE THREAD

**Issue by tbds** [pi-hole/pi-hole#532]
A good way to pi-hole be distro agnostic is to setup pi-hole using a snap package.

More about snap packages at [Universal “snap” packages launch on multiple Linux distros](https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/)

Website: [snapcraft.io](http://snapcraft.io/)
##

**Comment by dschaper** [comment]
Thanks for the link, it looks like `snapd` isn't really available on any of the distributions that we target right now, (It's only available in Sid for Debian, and will be a very long time before it's supported by Raspbian.) Once it has time to mature and be adopted by more than just Ubuntu it may be more viable. For now our focus is on Apt, Yum and Docker.

**Comment by Nadrajkowski** [comment]
Hi, 

since snaps have become very popular and available on (I think) all of the distros You support it would be a good idea to revisit this issue. It would make the install of pihole on especially Snappy Ubuntu Core much easier.

**Comment by N-G-X** [comment]
Agreed ^, I've chosen to configure all of my rPis with Ubuntu Core and having a snap to easily install and configure pi-hole would be awesome.

**Comment by dschaper** [comment]
We ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by NatoBoram** [comment]
There's one [here](https://discourse.pi-hole.net/t/snap-for-ubuntu-core-users/11061), if anyone happens to stumble upon this issue from Google.

**Comment by N-G-X** [comment]
Thanks @NatoBoram, I forgot to link that after creating it. Everyone please vote for this!

**Comment by jacobsalmela** [comment]
https://github.com/pi-hole/pihole-snap is now made public.  It's not quite fully functional yet, but we're hoping with some help from the community it may go somewhere.  Special thanks to @popey for helping develop it during the Snapcraft summit

**Comment by N-G-X** [comment]
Awesome! I can't wait to test it, thanks @jacobsalmela  and @popey!

**Comment by remov** [comment]
Where there any new developments about supporting snaps?

It looks like https://github.com/pi-hole/pihole-snap is a 404 now and I could not find a pi-hole snap anywhere.

**Comment by rajannpatel** [comment]
I know it has been quite a while since this thread was active, but I wanted to share an update for anyone still looking to run Pi-hole on Ubuntu Core.

I’ve been working on a snap for Pi-hole that addresses this exact use case. I'd love to hear any feedback, so feel free to use it and let me know if you run into any issues or have feature suggestions!

Repository: https://github.com/rajannpatel/snap-pi-hole

Documentation: https://github.com/rajannpatel/snap-pi-hole/wiki

Pi-hole snap on Snapcraft: https://snapcraft.io/pihole-by-rajannpatel
