### ISSUE TITLE
Allow `gravity.sh` to ingest simple AdBlock Plus lists

### ISSUE THREAD

**Issue by tkil** [pi-hole/pi-hole#5322]
### Versions

```console
$ pihole -v
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
```

### Platform

```console
$ uname -a
Linux raspberrypi 5.10.11+ #1399 Thu Jan 28 12:02:28 GMT 2021 armv6l GNU/Linux

$ cat /proc/device-tree/model  ; echo
Raspberry Pi Model B Plus Rev 1.2

$ free
              total        used        free      shared  buff/cache   available
Mem:         440448      120128       72112       11936      248208      255724
Swap:        102396        4096       98300
```

### Expected behavior

I was hoping to use some of the lists from [The Big Blocklist Collection](https://firebog.net/), which is the first link on the [Community Projects](https://docs.pi-hole.net/main/projects/) page.

It looks like these are in "adblock plus" format? E.g., https://v.firebog.net/hosts/Admiral.txt has lines that look like:

```
||2znp09oa.com^
||2znp09oa.com^
||35.186.219.42^
||35.186.249.84^
||35.190.48.184^
||35.190.58.50^
||35.190.62.199^
```

It should be possible for a novice user to use lists that are linked from the pi-hole documentation.

### Actual behavior / bug

I tried simply using the list URL through the Pi-hole UI, but the update said "0 domains" (or something along those lines).

I found https://github.com/pi-hole/FTL/issues/1573 that seemed related, but handling the actual entries was deferred because they require regex matching in the most general case.

### Steps to reproduce

1. Go to "Admin Panel" --> "Adlists"
2. Add a new adlist:
    a. Address: https://v.firebog.net/hosts/Admiral.txt
    b. Comment: Whatever
4. Click on "Add"
5. Click on "... update your gravity list **online** ..."
6. Click "Update"

Actual result: 0 new domains from the new list
Expected result: some number greater than 0.

### Possible fix

I was able to get the domains recognized by adding:

```bash
    -e 's/^\|\|(.*)\^$/\1/' \
```

To this `sed` command (currently around line 658 in /opt/pihole/gravity.sh):

```bash
  # 2) Remove carriage returns
  # 3) Remove lines starting with ! (ABP Comments)
  # 4) Remove lines starting with [ (ABP Header)
  # 5) Remove lines containing ABP extended CSS selectors ("##", "#!#", "#@#", "#?#") preceded by a letter
  # 6) Remove comments (text starting with "#", include possible spaces before the hash sign)
  # 7) Remove leading tabs, spaces, etc. (Also removes leading IP addresses)
  # 8) Convert from ABP format: ||some.domain.here^ --> some.domain.here
  # 9) Remove empty lines

    sed -i -r \
    -e 's/\r$//' \
    -e 's/\s*!.*//g' \
    -e 's/\s*\[.*//g' \
    -e '/[a-z]\#[$?@]{0,1}\#/d' \
    -e 's/\s*#.*//g' \
    -e 's/^.*\s+//g' \
    -e 's/^\|\|(.*)\^$/\1/' \
    -e '/^$/d' "${destination}"
```

(Note the above snippet has the new expression and a matching comment.)

This doesn't solve the full problem of handling fancy ABP patterns, but it might be worth adding to take advantage of the many hosts- / domains-only lists out there.

Happy to open a PR for this, but honestly, it took me a long time to even find your Github org, and I still haven't figured out exactly where `gravity.sh` lives in your various repos...

p.s. "Took me a long time to find your Github org" == you have great docs about contributing, but I didn't see any obvious links to which org / repo you lived in! E.g., https://docs.pi-hole.net/guides/github/contributing/ doesn't have a pointer to this repo. Even filing this issue took a [human redirect](https://github.com/yubiuser/pihole_adlist_tool/issues/77#issuecomment-1598233554), h/t to @yubiuser

**Comment by yubiuser** [comment]
This ABP style is supported already. For me adding this list results in

```
  [i] Target: https://v.firebog.net/hosts/Admiral.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 1026 ABP-style domains (ignored 0 non-domain entries)
  ```
  
  Note ` 1026 ABP-style domains`

**Comment by tkil** [comment]
Interesting. I wonder what I was doing wrong? Maybe I did the import before I did the update to the most recent version.

I'll see if I can recreate it "from scratch".

**Comment by tkil** [comment]
> Maybe I did the import before I did the update to the most recent version.

Looks like that was the problem; it's working fine now.

Apologies for the noise, and thanks again for the great tool!
