### ISSUE TITLE
Queries Over Time Graph on Admin Interface Never Loads

### ISSUE THREAD

**Issue by slamanna212** [pi-hole/pi-hole#533]
##### Expected Behaviour:

Graph loads on IP_ADDRESS/admin
##### Actual Behaviour:

The queries over time graph just has the spinning loading circle for ever

Even if i flush the logs and only have a couple entries in the log file, the queries over time graph still does not load, all other graphs do. I JUST reinstalled raspbian jessie lite and pihole on my raspberry pi 2 about 3 days ago. 
##

**Comment by PromoFaux** [comment]
Hey, could you provide us with two things, please..

The contents of `/etc/pihole/install.log` , and the output of running `pihole -d` (debug function) Cheers!

**Comment by Manwe73** [comment]
Hi @all,

i have same problem here.
- Pi3+, Raspbian
- permanently updated and upgraded with "sudo apt-get update" and "sudo apt-get upgrade"
- started pihole with last 2.6.x ... works fine
- upgraded to 2.7.0 with "curl -L https://install.pi-hole.net | bash" again ... no graphs & values displayed
- upgraded to 2.7.1 with "curl -L https://install.pi-hole.net | bash" again ... no graphs & values displayed

If i call "pi.hole/admin" browser console logs some HTTP500 issues.

What I see in pihole_debug.log:
- raspberry host name: 127.0.1.1 (??? should this not be 127.0.0.1 ???)
- massiv "mod_fastcgi.c.2695" Errors

[browser_console.zip](https://github.com/pi-hole/pi-hole/files/333646/browser_console.zip)
[install.zip](https://github.com/pi-hole/pi-hole/files/333639/install.zip)
[pihole_debug.zip](https://github.com/pi-hole/pi-hole/files/333647/pihole_debug.zip)

**Comment by ryanknapper** [comment]
I've just resolved this problem for myself, but I'm working with a non-standard installation.  admin/api.php was complaining about there being no default timezone set.  Once I added date_default_timezone_set('Country/City'); to the top of api.php and it became happy.

**Comment by dschaper** [comment]
@ryanknapper Thanks for the tip!
@Manwe73 Can you post the log files to PasteBin and then give us the links to the Bins please? For security purposes we'd rather have the code on a remote site rather than downloading zip files. Thanks!

**Comment by idgers** [comment]
Not sure if this issue is withering on the vine or not...but it says 'open' so I will add a comment.  I currently have this issue.  `pihole -d` shows a number of things like this with various php line numbers (a dozen or so):

> 2016-09-29 21:05:12: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 215

Not sure if time of day makes a difference or not...

Everything works great pi-hole wise.  Just the admin page is wonky.  Usually the other stat numbers show up on the page eventually but it takes a while.  I haven't yet tried the timezone thing mentioned above.

**Comment by PromoFaux** [comment]
Hi, thanks for your report!

It is indeed an ongoing issue, and has to do with a couple of factors... Mainly the sheer size of the log after a certain time, but also available memory on the device you have pi-hole installed on.

That said, we've been hard at work to come up with a faster alternative, and I think we are very close... Watch this space, next release should improve things vastly!

**Comment by PavelPr** [comment]
Hi!

Today I started experiencing this ("0 Ads Blocked Today", "0.0% Of Today's Traffic Is Ads", an ever loading "Queries over time" graph and an empty "Top Advertisers" list). Strangely enough, this would not be resolved by reinstalling pi-hole, nor by inserting a freshly-imaged Raspbian micro SD card and then installing Pi hole on it, afresh. This last part is rather strange. Perhaps anyone has any idea?

**Comment by ajp2k13** [comment]
Same thing happened to me today, was working fine a couple of days ago and I haven't changed a thing?

**Comment by PavelPr** [comment]
It seems like we're not alone:

https://www.reddit.com/r/pihole/comments/55bfz9/ads_blocked_today0_admin_counter_issues/

**Comment by PromoFaux** [comment]
This one is slightly different, but I am looking into that one! It's confusing me to say the least....!

**Comment by Erikih** [comment]
There is an update available. The file data.php is updated. After updating using the command "pihole -ud" the counter, and the Queries over time graph works!

**Comment by PromoFaux** [comment]
Yeah, that was also falling over due to pi-hole/AdminLTE/#150 but that update should fix it!

We still have an issue where the dashboard falls over if the log file is too big! [But that is soon to be fixed](https://github.com/pi-hole/pi-hole/pull/731)

**Comment by gauravsharma013** [comment]
Yes flushing the log seems to fix the problem, btw I'm using 
Pi-hole version is v2.9.5 & Web-Admin version is v1.4.4.2

**Comment by DL6ER** [comment]
The issue has been resolved. Feel free to reopen if the error persists!

**Comment by PromoFaux** [comment]
I'd like to keep this one open for now. It's still an ongoing issue for users with large logs. 

While not something we can directly control at the moment, it's a good reminder that we need to optimise the process of parsing the logs!

**Comment by DL6ER** [comment]
@PromoFaux Ah, I thought that [this issue](https://github.com/pi-hole/AdminLTE/issues/130) (on the web page repo) actually describes a very similar problem (still open).

**Comment by PromoFaux** [comment]
Yeah, pretty much the same thing. Keeping it open is more for issue visibility than anything.

**Comment by SteveW25561** [comment]
I'm noticing that on Webinterface v2.2, the Queries over time, Query Types and Forward Destinations don't load at all on Chrome (OSX, Chrome Version 55.0.2883.95 (64-bit)) -- but on the same computer, at the same time, Safari loads it properly, as do iOS devices.

**Comment by DL6ER** [comment]
Can you debug what is happening? On Chrome you may use the Developer Tools (press F12) to see if there are any errors shown (should be the case if nothing is displayed).

![screenshot at 2016-12-26 12-29-16](https://cloud.githubusercontent.com/assets/16748619/21481355/fbda1e1e-cb66-11e6-8eff-b11e271e1a4b.png)

**Comment by SteveW25561** [comment]
Here's what I get using the Developer's tools console:
![screenshot_885](https://cloud.githubusercontent.com/assets/13310409/21491681/6181842c-cbb3-11e6-99a0-ae59104e3eae.jpg)

**Comment by DL6ER** [comment]
Okay, that totally makes sense as your `index.js` is in a very old state. Since it is working on your other devices it must be a Cache issue on your Chrome browser (clear the Cache!).

In your Dev console in line 53 of `index.js` there is the complaint that `(intermediate value).Line` is not a function. However, this command was only there quite some time ago.

**Comment by SteveW25561** [comment]
Thanks for this.  Clearing the cache worked!

**Comment by PartisanEntity** [comment]
Same issue. Pi-hole Version v2.11 Web Interface Version v2.3. Installed on a Raspberry Pi 3. The main page displayed nicely the first 1-2 days and now never display any graphs.

**Comment by DL6ER** [comment]
> Same issue 

means you have solved it by clearing the Cache?

If not, please open a separate issue so we can assist everyone individually.

**Comment by jacobsalmela** [comment]
Looks like clearing the cache fixed the issue then.  Others can open a new issue if needed (make sure you run `pihole -up` to get on the version we released today).

**Comment by bwanaaa** [comment]
I updated to 3.2.1 and started having this problem. Flushed the logs and it made no difference.
<img width="973" alt="screen shot 2018-01-02 at 8 43 18 pm" src="https://user-images.githubusercontent.com/4876720/34506774-cf9ecf54-effd-11e7-99e4-f57e2485c61d.png">

Now it doesn't even show the version info at the bottom
