### ISSUE TITLE
No redirection of "/admin" when using lighttpd

### ISSUE THREAD

**Issue by magistermundisum** [pi-hole/pi-hole#5346]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  
- NAME="Ubuntu"
VERSION="22.04.2 LTS (Jammy Jellyfish)"

Raspberry Pi

### Expected behavior
The web interface should redirect to /admin when accessing it via IP

### Actual behavior / bug
The web interface does not redirect to /admin when accessing it via IP.

The issue seems to be in the lighttpd config "15-pihole-admin.conf"
replace line 71 
from
```
else $HTTP["url"] == "/admin" {
     url.redirect = ("" => "/admin/")
```
to
```
 else $HTTP["url"] != "/admin" {
     url.redirect = ("" => "/admin/")
```
and it seems to redirects correct.

### Steps to reproduce

Just install and visit the web via IP without /admin

**Comment by PromoFaux** [comment]
This is actually by design. See: https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

The conditional that you've tweaked is to add a trailing `/` to the url when it is missing
