### ISSUE TITLE
private-user-images.githubusercontent.com is blocked

### ISSUE THREAD

**Issue by Soviut** [pi-hole/pi-hole#5347]
### Versions

- Pi-hole:  v5.17.1
- AdminLTE:  v5.20.1
- FTL:  v5.23

### Platform

- OS and version:  Raspbian GNU/Linux 11 (bullseye)

- Platform:  Raspberry Pi

### Expected behavior

Images pasted to github PRs and issues should not be blocked.

The URL these pasted images generate start with `https://private-user-images.githubusercontent.com/`.

### Actual behavior / bug

Pasted images in github PRs and issues are visible on github itself, but are blocked when you click them to view the image directly.

### Steps to reproduce

1. Go to github
2. Create a PR, issue or comment and drag/paste an image into the text area
3. Post the PR/issue/comment
4. Note that the image previews and displays correctly
5. Click the image to open the original
6. Observe the direct link is blocked
7. Disable PiHole
8. Observe the direct link now works

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
Running `pihole -q private-user-images.githubusercontent.com` will tell you the list that domain is on, and then you will need to contact the maintainer of that list to find out why it is on their blocklist.

Alternatively, you can whitelist the domain to ensure it does not get blocked by any blocklist.

**Comment by Soviut** [comment]
@PromoFaux Thanks. I tried `pihole -q private-user-images.githubusercontent.com` and `pihole -q githubusercontent.com` and no results came up.

Additionally, I'm not able to reproduce the issue anymore, so perhaps it was a temporary problem with github itself.
