### ISSUE TITLE
v6 `pihole -q -all domain` is failing when `-all` is before the domain

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/pi-hole#5348]
The command `pihole -q google -all` (using the `-all` option **AFTER** the domain) works and retrieves all domains and ABP entries.
The command `pihole -q -all google` (using the arguments in the most common order) fails and returns an error: `Unknown query option specified`.

Probably related to : https://github.com/pi-hole/pi-hole/pull/5300
This currently happens only in `v6` (`v5 master` is working).

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/pi-hole/pull/5361
