### ISSUE TITLE
pihole dhcp conflicts with WiFi hotspot isc-dhcp-server

### ISSUE THREAD

**Issue by magnificu** [pi-hole/pi-hole#5350]
### Versions

- Pi-hole:  5.17.1
- AdminLTE:  5.20.1
- FTL:  5.23

### Platform

- OS and version:  

### Expected behavior
Use the r-pi as a pihole DNS server connected to the LAN and WiFi as a Hotspot accessing the LAN.

### Actual behavior / bug
pihole dhcp conflicts with WiFi hotspot isc-dhcp-server

### Steps to reproduce

here you can find a more detailed description and a workaround
https://github.com/MichaIng/DietPi/issues/6485

### Proposal
add (specify) the chosen interface in the pihole configuration files: 
in this case "eth0" e.g. 
/etc/dnsmasq.d/02-pihole-dhcp.conf

dhcp-range=eth0,192.168.1.2,192.168.1.254,255.255.255.0,24h
dhcp-option=eth0,option:router,192.168.1.1

**Comment by Bucking-Horn** [comment]
It should be possible to use Pi-hole as DNS server along with any DHCP server out of the box:
Pi-hole's DHCP server is disabled by default.  
It would ony be activated if you explicitly configure Pi-hole to enable it,.

Furthermore, why would you want to run two DHCP servers on the same machine anyway?

There is no need to do so if it's already running Pi-hole for DNS, as Pi-hole is capable of handling DHCP also.
Using Pi-hole for both DNS and DHCP offers the additional benefit of registering local hostnames as presented by clients during DHCP negotiation with DNS straight away.  
I recall BIND's isc-dhcp-server to not register hostnames with DNS at all by default.

If you would be determined to use two (or more) separate DHCP servers on the same machine, configuration would depend on how excactly you'd want them to coexist.
As I see it, this is guaranteed to require manual configuration.

One way to have a separate DHCP server coexist with Pi-hole's DHCP server would be to have each of them serve a specific interface only.
To that end, you could add a custom configuration file under `/etc/dnsmasq.d/` with the following content to Pi-hole's configuration:
```
no-dhcp-interface=<interface name>
```
This would stop Pi-hole's DHCP server to manage DHPC requests that arrrive via an interface that you want to be handled by another DHCP server.

You could also try to limit Pi-hole's interface settings to one of the interface specific settings via its Settings | DNS UI, either by itself or in addition to above custom configuration.
In case that UI would not show the correct interface name, you also may have to run `pihole -r` with *Reconfigure* to pick your desired interface.

In any case, I do not see how Pi-hole could arrive at a set of defaults safe to be used with any arbitrary additional DHCP server software.

If Dietpi is offering installation of isc-dhcp-server alongside Pi-hole, their installaton script would possibly be the best place to predefine a custom configuration that would allow that very combination of specific DHCP servers to coexist on the same machine.

**Comment by magnificu** [comment]
Thank you for your extensive feedback.
I am using pi-hole as the main DNS server.
The issue is that I am using for the WiFi interface as a host spot with a different IP range and pihole DNS will try to allocate IP's to the wlan0 interface as defined in this file /etc/dnsmasq.d/02-pihole-dhcp.conf

if pihole will specify the interface (user selection during pihole -r) in the config file there will be no issue anymore

todays config file
dhcp-range=192.168.1.2,192.168.1.254,24h
dhcp-option=option:router,192.168.1.1

proposed change
dhcp-range=eth0,192.168.1.2,192.168.1.254,24h
dhcp-option=eth0,option:router,192.168.1.1

do you see any issue with this proposal?

**Comment by magnificu** [comment]
I would like to avoid using isc-dhcp-server alongside Pi-hole.
In my view it does not make any sense to run two DNS servers in the same time.

in my setup I created a new config file in /etc/dnsmasq.d/  (e.g. 99-dietpi-hotspot.conf) that looks like this

dhcp-range=wlan0,192.168.42.2,192.168.42.100,255.255.255.0,12h
dhcp-option=wlan0,option:router,192.168.42.1

main issue is every update in pihole interface will overwrite /etc/dnsmasq.d/02-pihole-dhcp.conf
deleting the specified interfaces (eth0) and after the pihole DNS will crash
