### ISSUE TITLE
copy paste domain name from query log

### ISSUE THREAD

**Issue by primski** [pi-hole/pi-hole#5362]
on-click event opens up details page and you cannot copy the domain name

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
From the text below the query log

`On a computer: Hold down Ctrl, Alt, or ⌘ to allow highlighting for copying to clipboard`

**Comment by primski** [comment]
this doesn't work 

> From the text below the query log
> 
> `On a computer: Hold down Ctrl, Alt, or ⌘ to allow highlighting for copying to clipboard`
