### ISSUE TITLE
DNS service and FTL are not running after an update

### ISSUE THREAD

**Issue by sky7d** [pi-hole/pi-hole#5377]
After last update DNS service and FTL are not running, Can you help me? I don't want to reinstall everything on my raspberry :(
Thanks in advance...

Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
/opt/pihole/version.sh: line 19: pihole-FTL: command not found
/opt/pihole/version.sh: line 122: pihole-FTL: command not found
  Latest FTL version is v5.23

**Comment by rdwebdesign** [comment]
Please, generate a debug log and post here only the TOKEN:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.
