### ISSUE TITLE
Adding an url to white or black list using admin website

### ISSUE THREAD

**Issue by kaasszje** [pi-hole/pi-hole#538]
##### Expected Behaviour:
Added url's

##### Actual Behaviour:
![image](https://cloud.githubusercontent.com/assets/11602234/16269934/acb5be5c-3894-11e6-8024-c52130d4d965.png)

Looking into the lighthttpd error log I see:
2016-06-22 16:16:18: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/admin/php/add.php on line 16

##### Steps to reproduce this issue:
Just click add in the whitelist or blacklist page

**Comment by PromoFaux** [comment]
Hi @kaasszje , could you please pastebin the output (file) of the command `pihole -d` so we can take a look.

Also, what hardware/OS are you running on? Thanks

**Comment by kaasszje** [comment]
Here it is http://pastebin.com/kPDjjvUJ
Running on raspberry pi 1 with raspian installed:
Raspbian GNU/Linux 7 (wheezy)

**Comment by PromoFaux** [comment]
Got it...

Unfortunately the latest version of PHP on Debian Wheezy is 5.4, and the `get_hash()` function needs PHP 5.6..... How attached are you to this install? Is there anything stopping you from updating to Raspbian Jessie?

**Comment by kaasszje** [comment]
Ah that would explain it, not extremely attached. would have to do some extra installs to get all working.
Tnx for the feedback :)

**Comment by dschaper** [comment]
@PromoFaux got it. Looked at Jessie Backports and I don't see the updated package there, it does look like dotdeb has a package but the best bet is Jessie if you can.

**Comment by kaasszje** [comment]
I'll try to do the upgrade tonight and see what happens.
Will report back

**Comment by kaasszje** [comment]
Well updated my Raspberry to Jessie
And it works like a charm :)

**Comment by PromoFaux** [comment]
Excellent! Glad its working for you!

Enjoy :)

**Comment by gerard33** [comment]
Had this issue as well with Pihole running on Ubuntu Server 14.04.
Fixed it by installing PHP7.
