### ISSUE TITLE
Pi-hole login credentials not updated after password change via SSH

### ISSUE THREAD

**Issue by adalbertobrant** [pi-hole/pi-hole#5380]
Description:

After installing Pi-hole using the system-generated password, I logged in using the Mozilla Firefox browser. While still logged in to Firefox, I accessed Pi-hole via SSH and changed the password. Afterwards, I logged back in to Firefox, which was still logged in and continued to use Pi-hole, even with the old password.

Version:

Pi-hole: 5.17.1
AdminLTE: 5.17.1
FTL: 5.17.1
Platform:

OS and version: RaspiOs Lite
Platform: Raspberry Pi
Steps to reproduce:

Install Pi-hole using the system-generated password.
Log in to Pi-hole using the Mozilla Firefox browser.
While still logged in to Firefox, access Pi-hole via SSH and change the password.
Log back in to Firefox.
Verify that you are still logged in to Pi-hole and that the old password still works.
Expected behavior:

After changing the password via SSH, the new password should be required to log in to Pi-hole.

Actual behavior:

The old password is still accepted to log in to Pi-hole.

Additional context:

This issue is a security risk, as it allows an attacker to access Pi-hole without knowing the new password.

**Comment by adalbertobrant** [comment]
I've made a video showing the problem.
[https://emalm.com/?v=WAi8M](https://emalm.com/?v=WAi8M)

**Comment by yubiuser** [comment]
This is kind of expected, as you still have a valid session and credentials are not re-checked unless the session expires or you log out.

**Comment by adalbertobrant** [comment]
I am closing because it is not an issue anymore, thanks for the explanation @yubiuser
