### ISSUE TITLE
Err message

### ISSUE THREAD

**Issue by Mark-spec8** [pi-hole/pi-hole#5392]
PiHole Browser Extension: 3.0.2
Operating System: Win32
Browser: Chrome/Chromium 117.0.0.0

Error message showing, and stating that connection is not succesfully, can't seem to de-bug. have deleted and re-installed the chrome app to no avail.

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
There is no official browser extension from Pi-hole. This must be a third-party app, please connect the relevant developers

**Comment by Mark-spec8** [comment]
> There is no official browser extension from Pi-hole. This must be a third-party app, please connect the relevant developers

i'm such a noob. I don't know how to connect the relevant developers, or what that means.

![image](https://github.com/pi-hole/pi-hole/assets/145025960/22729ec3-a37d-4ec3-8721-4865f3a54c2e)

**Comment by yubiuser** [comment]
File an issue here https://github.com/badsgahhl/pihole-browser-extension
