### ISSUE TITLE
 wl.spotify.com being blocked

### ISSUE THREAD

**Issue by benniblot** [pi-hole/pi-hole#5393]
### Versions

- Pi-hole version is v5.17.1 (Latest: v5.17.1)
- AdminLTE version is v5.20.1 (Latest: v5.20.1)
- FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  Debian GNU/Linux 11 (bullseye)

- Platform:  Docker

### Expected behavior

wl.spotify.com shouldn't be blocked since its being used to confirm new email addresses

### Actual behavior / bug

wl.spotify.com gets block by the adlist (didn't add any additional adlists)

### Steps to reproduce

1. Go to wl.spotify.com
2. Notice how the domain gets blocked

or 

1. Try to change your mail of your spotify account
2. Click on the link you get via mail
3. Notice how the domain gets blocked

**Comment by yubiuser** [comment]
Pi-hole does not maintain any adlist itself. If you did not add any additional adlist, you're using the default from https://github.com/StevenBlack/hosts. However, this list does not contain `wl.spotify.com` (see https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts).

Please visit our user forum at https://discourse.pi-hole.net/ for additional configuration help.

**Comment by benniblot** [comment]
![image](https://github.com/pi-hole/pi-hole/assets/47495914/2ba7d734-e617-451e-a64f-97fad3aed58a)
these are my adlists

these are the results when searching for wl
![image](https://github.com/pi-hole/pi-hole/assets/47495914/430316ec-87ae-4caf-9f46-e1e92195da1e)

**Comment by jfb-pihole** [comment]
The domain is contained in your whitelist, but only there.  It does not appear that Pi-hole was ever able to block that domain.

**Comment by benniblot** [comment]
oh sorry about that, thats true didn't read the whole message still don't understand why it was blocked before I set it on the whitelist
![image](https://github.com/pi-hole/pi-hole/assets/47495914/493a1af9-d2e9-4670-b82a-948478906216)

**Comment by jfb-pihole** [comment]
Where are you seeing that Pi-hole was blocking this domain?  Was this showing in the query log or in the dnsmasq log at ***/var/log/pihole/pihole.log***

**Comment by benniblot** [comment]
the query log
