### ISSUE TITLE
Update Gravity DNS resolution failure

### ISSUE THREAD

**Issue by dnbarclay** [pi-hole/pi-hole#5395]
### Versions
- Pi-hole:  5.17.1
- AdminLTE:  5.20.1
- FTL:  5.23

### Platform
- OS and version:  Ubuntu 20.04
- Platform:  Docker

### Expected behavior

I press update gravity in the webUI and my block lists update. 

### Actual behavior / bug

I get a message "DNS resolution is currently unavailable" in the output terminal. 

### Steps to reproduce

1. Go to WebUI
2. Click on Tools
3. Scroll down to update gravity and click

## Debug Token

- URL:  

"There was an error uploading your debug log"

I have a local copy of the log saved.

**Comment by yubiuser** [comment]
Please head over to our forum at discourse.pi-hole.net for help regarding individual configuration issues.
