### ISSUE TITLE
Group based RegEx does not work properly

### ISSUE THREAD

**Issue by leonbrag** [pi-hole/pi-hole#5407]
### Versions

Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
### Platform

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Ubuntu

### Expected behavior

1. I have created a RegEx rules that is applicable to specific group only
2. I expect rule to only apply to Default group and NOT different group.

### Actual behavior / bug

3. however RegEx rule is incorrectly applies to devices in the group where it should not apply to

### Steps to reproduce

1. create rule that does not apply to Work group:

![image](https://github.com/pi-hole/pi-hole/assets/5290089/d8bcdf13-73d8-4191-8585-758af1b6e804)

2. create Work group and add device to this group:
![image](https://github.com/pi-hole/pi-hole/assets/5290089/0c7ca163-c4ab-4368-a52b-99233806020a)

3. observe how RegEx blocking rules is applied to device that is in the Work group
![image](https://github.com/pi-hole/pi-hole/assets/5290089/dcf826a5-bce4-495a-8b04-e1ccc4df85cb)

Because device is in the Work group, RegEx block should not apply, yet it's incorrectly applied

![image](https://github.com/pi-hole/pi-hole/assets/5290089/c4bfe9c1-b781-4ccd-9507-8b90d4ab279f)

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
> ## Debug Token
>     * URL:


Please, generate a Debug Token:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by leonbrag** [comment]
I am sorry. Numerous devices connected to pinhole are used for work. I won’t be able to provide logs. 

But this should be very easy repro to setup.

**Comment by jfb-pihole** [comment]
If you are unwilling to provide a debug log (visible only to the Pi-hole team and for only 48 hours), then review your debug log and dnsmasq log to verify that the client and group assignments are as you expect. For example, is the work client showing at its actual IP, or the Ip of the router.

**Comment by leonbrag** [comment]
I have re-added client and now it works.
