### ISSUE TITLE
Thoughts about the 10 secs youtube delay.

### ISSUE THREAD

**Issue by alexpsfti** [pi-hole/pi-hole#541]
With firefox, using the Private Browsing feature (CTRL + SHIFT + P), removes the delay and ads are still blocked. 

I also noticed that only HTLM5 is affected. If you switch to flash, with this addon: https://addons.mozilla.org/fr/firefox/addon/youtube-flash-video-player/ then, the delay will go away as well.
##

**Comment by PromoFaux** [comment]
Hmm.. that begs the question.. what other addons do you have running, that aren't loaded in private browsing mode?

**Comment by alexpsfti** [comment]
All my modules are still loaded in the private browsing mode. These are: 

- Greasemonkey
- Stylish
- Check4Change
- Adblock Plus

**Comment by PromoFaux** [comment]
>I also noticed that only HTLM5 is affected. If you switch to flash, with this addon:

Youtube requires an opt-in to use HTML5, right? At least it used to. I may be remembering things wrong, but does it default to Flash? (I.E not signed in with a private-browsing mode)

**Comment by dschaper** [comment]
They reversed that a bit ago, I think you have to opt-out of HTML5 / WebM (or whatever they are using now.) Flash doesn't work on the Pi's...

**Comment by PromoFaux** [comment]
Sure, but flash works on the client machines that are actually loading the content... Just spitballing seeing that there is no delay on flash player/private-browsing mode.

**Comment by jradwan** [comment]
I've noticed the YouTube delay as well (Chrome). I'll have to see if Firefox exhibits the same behavior.

**Comment by bitterypaul** [comment]
HTML 5 is enabled by default in youtube. I experience delays like 4-5 seconds.

**Comment by alexanderkent** [comment]
4-5 second delays in youtube using (Chrome)

**Comment by jacobsalmela** [comment]
Discussion continues [here](https://discourse.pi-hole.net/t/youtube-10-second-black-screen/495/20)...
