### ISSUE TITLE
Install Script fails on Raspbian 12

### ISSUE THREAD

**Issue by JohnnyMoonlight** [pi-hole/pi-hole#5425]
### Versions

  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.20.2 (Latest: v5.20.2)
  FTL version is v5.23 (Latest: v5.23)

### Platform
OS:
Raspbian 12 Lite

PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian

Platform:  Raspberry Pi 3b+

### Expected behavior

If someone calls the auto install script from Raspiban 12 Lite, the script should recognize Raspbian 12 Lite as supported OS and execute the installation.

### Actual behavior / bug

The installation script throws an error message, stating Raspbian 12 not supported.
`
Unsupported OS detected: Raspbian 12`

A workaround is suggested, but the OS should be added to the list of supported systems to facilitate the installation on the new Raspbian OS.

### Steps to reproduce

1. Flash the device with Raspbian 12 Lite.
2. Call the install script via `[curl -sSL https://install.pi-hole.net | bash](https://github.com/pi-hole/pi-hole/#curl--ssl-httpsinstallpi-holenet--bash)`
3. Error is thrown.

### Additional context

I have updated my Raspberry Pi running pihole to the newest Raspbian OS and received this error.

**Comment by jfb-pihole** [comment]
This OS was just released on 10 October 2023.  We have not yet added support for this OS, but will likely do so after we accumulate some run time on it and ensure that there are no problems.

See this discussion:  https://team.pi-hole.net/landing#/pi-hole/pl/117pueoec7rjtno78jj3ctguxe

**Comment by derfasthirnlosenick** [comment]
> This OS was just released on 10 October 2023. We have not yet added support for this OS, but will likely do so after we accumulate some run time on it and ensure that there are no problems.

Would it make sense to enable it for version 6 in the development branch? That one is anyhow considered unstable, so might just as well accumulate the run time on that version.

**Comment by yubiuser** [comment]
There is no way to enable it only for one branch without hard coding the exception in the installer script - something I'd like to avoid giving that you can override the check easily.

**Comment by Dylan96** [comment]
Any updates on this issue?

**Comment by yubiuser** [comment]
Support for Rpi 12 has been added a few days ago. Installation should be working now without issues.

**Comment by JohnnyMoonlight** [comment]
Thanks a bunch for adressing this issue.

I have a question, I would be glad if anyone could answer: I tried to understand the corresponding passage in the code that compares the OS the script runs on and the supported OS list. If I understand correctly, the supported OS-list is retrieved from a DNS-server: `dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net`. Why DNS? Could the script not simply call a web resource? I guess there is a reason for this?

**Comment by yubiuser** [comment]
Your assumption is right. It's a DNS record we control which delivers a TXT record with the supported OS.
I'm not sure why we chose this approach back than and no other but I guess it boils down to: it was easy and already there.
But maybe @dschaper or @PromoFaux remember better.

**Comment by Dylan96** [comment]
> Support for Rpi 12 has been added a few days ago. Installation should be working now without issues.

Thank you, it installed just fine.

The only problem i’m having is that i can’t access the web gui at my raspberry ip (http://192.168.1.5), it’s showing lighttpd’s placeholder page…

Works fine if i enter 192.168.1.5/admin

**Comment by yubiuser** [comment]
This is expected. There is only a automatic redirect to `´/admin` if the hostname is `pi.hole`. For all others you need to specifically request `/admin`

**Comment by yubiuser** [comment]
Closing Raspbian 12 is now supported.
