### ISSUE TITLE
Incorrect name resolution in Pihole V6

### ISSUE THREAD

**Issue by Mister-XY** [pi-hole/pi-hole#5446]
### Versions

  - Pi-hole version is development-v6 v5.17.1-170-g6cf39d9b (Latest: v5.17.2)
  - web version is development-v6 v5.19-321-g111c7286 (Latest: v5.20.2)
  - FTL version is development-v6 vDev-4c6dadd (Latest: v5.23)

### Platform

- OS and version:  DietPi v8.22.3

- Platform:  Raspberry Pi

### Expected behavior

Incorrect name resolution in Pihole V6

### Actual behavior / bug

Hello, after an update from Pihole v5 to v6 I have a completely different name resolution. I don't use Pihole as a DHCP server, my Fritzbox 7530 AX does that.
While in Pihole v5 I have the names as they are entered in the Fritzbox, in Pihole v6 I have a different resolution.
I've uploaded the screenshots. I didn't change anything in Pihole after the update.

## Debug Token

- URL:  

### Screenshots

Pihole V5

![pihole v5](https://github.com/pi-hole/pi-hole/assets/10309056/a36b5558-7a34-480c-ba6e-0063d65db969)

Pihole V6

![pihole v6](https://github.com/pi-hole/pi-hole/assets/10309056/760a4d0e-884a-4949-949d-b14322c34154)

### Additional context

_Add any other context about the problem here._

**Comment by Ollipop030** [comment]
I'm having the same issue, with the same configuration, but on v5. I think, pihole uses the device name of the very first connection.

![grafik](https://github.com/pi-hole/pi-hole/assets/121013633/94ac1c80-6550-4fd1-9d78-c3701f299c13)

Sometimes the name is none-2.fritz.box, sometimes strange names like avs-ffreg-1975522331.fritz.box, and sometimes the correct name.
