### ISSUE TITLE
Client group management list not visible in docker

### ISSUE THREAD

**Issue by raf181** [pi-hole/pi-hole#5454]
### Versions

- Pi-hole:   v5.17.2
- AdminLTE:  v5.20.2
- FTL:  v5.23

### Platform

- OS and version:  Debian 12

- Platform:  Docker

### Expected behavior

the list where you manage the clients and the groups they belong to should be visible

### Actual behavior/bug

the list where you manage the clients and the groups they belong is not loading

### Steps to reproduce

1. flowing the install process for the docker
2. go to groups and create a group
3. go to clients set one of your clients
4. scroll down and they are not visible on the list, even after reloading.

### Screenshots

![image](https://github.com/pi-hole/pi-hole/assets/93051606/569400bf-daef-4ee2-a138-659c9b37a8db)

**Comment by rdwebdesign** [comment]
Do you see any error message?

Can you please open the browser's Developer Tools (usually you need to press key <kbd>F12</kbd>) and select the tab "**_Console_**".
Do you see errors there?

**Comment by raf181** [comment]
> Do you see any error message?
> 
> Can you please open the browser's Developer Tools (usually you need to press key F12) and select the tab "**_Console_**". Do you see errors there?

![image](https://github.com/pi-hole/pi-hole/assets/93051606/5e1ad83c-de31-4d59-b70a-54c8b34704b1)

**Comment by iTim314** [comment]
I am seeing the same datatables issue across any page that relies on datatables. But in my case, I don't believe it's docker-related, rather that I have the admin console behind an Nginx proxy. Everything works fine when bypassing the proxy.

**Comment by rdwebdesign** [comment]
@iTim314 

Apparently your issue was related to reverse proxy config. I think you already fixed it ([Reddit post](https://www.reddit.com/r/pihole/comments/17fdm0b/datatables_warning_on_most_pages_when_behind/)).

@raf181

Can you please generate a Debug Log:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

Also, are you using a reverse proxy?

**Comment by raf181** [comment]
@rdwebdesign 
Debug Log: https://tricorder.pi-hole.net/kyu0ElK7/
I am not using a reverse proxy. I am running Pi-hole by installing it with CasaOS, but to my knowledge, it should not mater

**Comment by rdwebdesign** [comment]
One more question:

The initial screenshot shows docker tag `2023.10.0` on the footer, but your debug log is showing `2023.05.2`.
Did you start a new container or this is a different Pi-hole install?

**Comment by rdwebdesign** [comment]
The debug log shows a few issues with your database.

```
   [2023-10-24 21:58:00.097 259/T289] SQLite3 message: no such column: name in "UPDATE network_addresses SET name = NULL WHERE nameUpdated < 1666641480;" (1)
   ...
   [2023-10-24 22:00:41.516 259M] SQLite3 message: no such column: aliasclient_id in "SELECT aliasclient_id FROM network WHERE id = (SELECT ...
```

If you are using a volume to store `/etc/pihole`, you need to stop Pi-hole container, move the database to a new file and restart the container. A new database will be created.

**Comment by raf181** [comment]
yes, it initially was **2023.10.0** but when I restart the system that docker is running on it reverts the update to **2023.05.2** , even if it was updated successfully. I have reviewed the system and docker logs and can't find anything that causes the update to revert.
I'll try recreating the database, and see if it solves the issue

**Comment by raf181** [comment]
removing everything in **/etc/pihole** and running the container again solved the issue
