### ISSUE TITLE
Pihole is up to date?

### ISSUE THREAD

**Issue by Manaplayer** [pi-hole/pi-hole#5456]
### Versions

- Pi-hole:  5.17.2
- AdminLTE:  5.20.2
- FTL:  5.23

### Platform
 DietPi 8.23.3
- OS and version:  

- Platform:  RPi 2 Model B

### Expected behavior

PiHole Web Page shows, that a Update of core is available, but there is nothing. It shows it even after rebooting the complete RPi

### Actual behavior / bug

Explained as above

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context
![Zwischenablage01](https://github.com/pi-hole/pi-hole/assets/58844825/06c98cb1-0bf2-4b33-9cbb-5a1a106cc219)

_Add any other context about the problem here._
![Zwischenablage02](https://github.com/pi-hole/pi-hole/assets/58844825/de6c7441-3f1b-4b9d-a283-67923ac876db)

**Comment by yubiuser** [comment]
Please generate a debug log and post the token.

**Comment by Manaplayer** [comment]
*** [ INITIALIZING ]
[i] 2023-10-23:10:59:54 debug log has been initialized.
[i] System has been running for 0 days, 0 hours, 0 minutes

*** [ INITIALIZING ] Sourcing setup variables
[i] Sourcing /etc/pihole/setupVars.conf...

*** [ DIAGNOSING ]: Core version
[✓] Version: v5.17.2
[i] Remotes: origin	https://github.com/pi-hole/pi-hole.git (fetch)
             origin	https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.17.2-0-g60b6a10

*** [ DIAGNOSING ]: Web version
[✓] Version: v5.20.2
[i] Remotes: origin	https://github.com/pi-hole/AdminLTE.git (fetch)
             origin	https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.20.2-0-g3dd5752

*** [ DIAGNOSING ]: FTL version
[✓] Version: v5.23
[i] Branch: master
[i] Commit: d201776e

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.59

*** [ DIAGNOSING ]: php version
[i] 7.4.33

*** [ DIAGNOSING ]: Operating system
[✓] Distro:  Debian
[✓] Version: 11
[✓] dig return code: 0
[i] dig response: "Raspbian=10,11 Ubuntu=20,22,23 Debian=10,11,12 Fedora=36,37,38 CentOS=8,9"
[✓] Distro and version supported

*** [ DIAGNOSING ]: SELinux
[i] SELinux not detected

*** [ DIAGNOSING ]: FirewallD
[i] Firewalld service inactive

*** [ DIAGNOSING ]: Processor
[✓] armv7l

*** [ DIAGNOSING ]: Disk usage
   Filesystem      Size  Used Avail Use% Mounted on
   /dev/root       7.0G  1.4G  5.4G  20% /
   devtmpfs        454M     0  454M   0% /dev
   tmpfs           486M  1.3M  485M   1% /dev/shm
   tmpfs           195M  2.9M  192M   2% /run
   tmpfs           5.0M     0  5.0M   0% /run/lock
   tmpfs           486M  4.0K  486M   1% /tmp
   tmpfs            50M   36K   50M   1% /var/log
   /dev/mmcblk0p1  127M   52M   75M  42% /boot

*** [ DIAGNOSING ]: Network interfaces and addresses
   1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
       link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
       inet 127.0.0.1/8 scope host lo
          valid_lft forever preferred_lft forever
       inet6 ::1/128 scope host 
          valid_lft forever preferred_lft forever
   2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
       link/ether b8:27:eb:9f:32:90 brd ff:ff:ff:ff:ff:ff
       inet 192.168.178.22/24 brd 192.168.178.255 scope global eth0
          valid_lft forever preferred_lft forever
       inet6 fe80::ba27:ebff:fe9f:3290/64 scope link 
          valid_lft forever preferred_lft forever

*** [ DIAGNOSING ]: Network routing table
   default via 192.168.178.1 dev eth0 onlink 
   192.168.178.0/24 dev eth0 proto kernel scope link src 192.168.178.22 

*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
    192.168.178.22/24

[✓] IPv6 address(es) bound to the eth0 interface:
    fe80::ba27:ebff:fe9f:3290/64

[i] Default IPv4 gateway(s):
     192.168.178.1
   * Pinging first gateway 192.168.178.1...
[✓] Gateway responded.
[i] Default IPv6 gateway(s):

*** [ DIAGNOSING ]: Ports in use
[✓] udp:0.0.0.0:53 is in use by pihole-FTL
    udp:127.0.0.1:5335 is in use by unbound
[✓] udp:*:53 is in use by pihole-FTL
[✓] tcp:0.0.0.0:53 is in use by pihole-FTL
[✓] tcp:127.0.0.1:4711 is in use by pihole-FTL
    tcp:0.0.0.0:22 is in use by dropbear
[✓] tcp:0.0.0.0:80 is in use by lighttpd
    tcp:127.0.0.1:5335 is in use by unbound
    tcp:127.0.0.1:8953 is in use by unbound
[✓] tcp:[::]:53 is in use by pihole-FTL
    tcp:[::]:22 is in use by dropbear
[✓] tcp:[::1]:4711 is in use by pihole-FTL
[✓] tcp:[::]:80 is in use by lighttpd

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] yjjdz.realdatting.com is 103.224.182.239 on lo (127.0.0.1)
[✓] yjjdz.realdatting.com is 103.224.182.239 on eth0 (192.168.178.22)
[✓] doubleclick.com is 216.58.212.174 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] yapiev09.top is  on lo (::1)
[✓] yapiev09.top is  on eth0 (fe80::ba27:ebff:fe9f:3290)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (2001:4860:4860::8888)

*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   Timeout: 10 seconds
   
   * Received 548 bytes from eth0:192.168.178.1
     Offered IP address: 192.168.178.22
     Server IP address: 192.168.178.1
     Relay-agent IP address: N/A
     BOOTP server: (empty)
     BOOTP file: (empty)
     DHCP options:
      Message type: DHCPOFFER (2)
      server-identifier: 192.168.178.1
      lease-time: 864000 ( 10d )
      renewal-time: 432000 ( 5d )
      rebinding-time: 756000 ( 8d 18h )
      netmask: 255.255.255.0
      router: 192.168.178.1
      dns-server: 192.168.178.22
      domain-name: "fritz.box"
      mtu: 1500
      broadcast: 192.168.178.255
      ntp-server: 192.168.178.1
      Port Control Protocol (PCP) server: 192.168.178.1
   
   DHCP packets received on interface eth0: 1

*** [ DIAGNOSING ]: Pi-hole processes
[✓] lighttpd daemon is active
[✓] pihole-FTL daemon is active

*** [ DIAGNOSING ]: Pi-hole-FTL full status
   ● pihole-FTL.service - Pi-hole FTL
     Loaded: loaded (/etc/systemd/system/pihole-FTL.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-10-23 10:59:30 CEST; 1min 33s ago
    Process: 321 ExecStartPre=/opt/pihole/pihole-FTL-prestart.sh (code=exited, status=0/SUCCESS)
   Main PID: 341 (pihole-FTL)
      Tasks: 19 (limit: 2176)
        CPU: 1.104s
     CGroup: /system.slice/pihole-FTL.service
             └─341 /usr/bin/pihole-FTL -f

Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.388 341M]    ADDR2LINE: Enabled
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.388 341M]    REPLY_WHEN_BUSY: Drop queries when the database is busy
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.388 341M]    BLOCK_TTL: 2 seconds
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.388 341M]    BLOCK_ICLOUD_PR: Enabled
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.388 341M]    CHECK_LOAD: Enabled
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.389 341M]    CHECK_SHMEM: Warning if shared-memory usage exceeds 90%
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.389 341M]    CHECK_DISK: Warning if certain disk usage exceeds 90%
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.389 341M] Finished config file parsing
Oct 23 10:59:30 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.390 341M] Creating mutex
Oct 23 10:59:31 DietPi pihole-FTL[341]: [2023-10-23 10:59:30.390 341M] Crea

*** [ DIAGNOSING ]: Lighttpd configuration test
[✓] No error in lighttpd configuration

*** [ DIAGNOSING ]: Setup variables
    BLOCKING_ENABLED=false
    DNSSEC=false
    REV_SERVER=true
    REV_SERVER_CIDR=192.168.178.0/24
    REV_SERVER_TARGET=192.168.178.1
    REV_SERVER_DOMAIN=fritz.box
    PIHOLE_INTERFACE=eth0
    PIHOLE_DNS_1=127.0.0.1#5335
    PIHOLE_DNS_2=::1#5335
    QUERY_LOGGING=false
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    LIGHTTPD_ENABLED=true
    CACHE_SIZE=10000
    DNS_FQDN_REQUIRED=true
    DNS_BOGUS_PRIV=true
    DNSMASQ_LISTENING=local
    TEMPERATUREUNIT=C

*** [ DIAGNOSING ]: Dashboard headers

**Comment by yubiuser** [comment]
The log is truncated. We only need the token that is shown at the end of the debug log. Please don't post the full log here.

**Comment by jfb-pihole** [comment]
You are on the latest version.  The web admin GUI will update in due time.

```
*** [ DIAGNOSING ]: Core version
[✓] Version: v5.17.2
[i] Remotes: origin	https://github.com/pi-hole/pi-hole.git (fetch)
             origin	https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.17.2-0-g60b6a10

*** [ DIAGNOSING ]: Web version
[✓] Version: v5.20.2
[i] Remotes: origin	https://github.com/pi-hole/AdminLTE.git (fetch)
             origin	https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.20.2-0-g3dd5752

*** [ DIAGNOSING ]: FTL version
[✓] Version: v5.23
[i] Branch: master
[i] Commit: d201776e
```

**Comment by yubiuser** [comment]
```
   2023-10-23 17:17:37: server.c.1513) server started (lighttpd/1.4.59)
   2023-10-23 17:18:58: mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined index: CORE_VERSION in /var/www/html/admin/scripts/pi-hole/php/update_checker.php on line 40
   2023-10-23 17:18:58: mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined index: CORE_VERSION in /var/www/html/admin/scripts/pi-hole/php/update_checker.php on line 40
   2023-10-23 17:19:09: mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined index: CORE_VERSION in /var/www/html/admin/scripts/pi-hole/php/update_checker.php on line 40

```

What's the output of your `/etc/pihole/versions`

**Comment by Manaplayer** [comment]
![Zwischenablage01](https://github.com/pi-hole/pi-hole/assets/58844825/c93023cc-7367-4964-915d-07ac418cdd36)

**Comment by yubiuser** [comment]
Ok, I see the issue. Let me investigate.

Could you please also run `pihole -v`

**Comment by Manaplayer** [comment]
![Zwischenablage01](https://github.com/pi-hole/pi-hole/assets/58844825/78a452cb-2beb-4326-a839-c5322571e3a8)

**Comment by yubiuser** [comment]
Ok, this is kind of unexpected.
Your issue is that `/etc/pihole/verisons` is missing an entry for `CORE_VERSION` and the web interface will interpret this the wrong way and thinks an update is available. However, `pihole -v` sources the same file and should not be able to show the correct current version when the line is missing.

In general, this issue should not happen and if it does, it should auto-correct after 24h, when `pihole updatechecker` runs.

Could you please run `pihole updatechecker` (no output expected) and afterwards see if `versions` contains the line with `CORE_VERSION`. The web interface should now report no update.

**Comment by Manaplayer** [comment]
After "pihole updatechecker" the version file don't get updated. I deleted it and did "pihole updatechecker" again and the line with "CORE_VERSION" got be written and pihole web now don't show that there is an update again.
