### ISSUE TITLE
Cannot whitelist/blacklist from web interface

### ISSUE THREAD

**Issue by AtomicLaser** [pi-hole/pi-hole#546]
##### Expected Behaviour:
When adding a whitelist or blacklist in the web interface, Po-Hole should add the website address after refreshing the list

##### Actual Behaviour:
Does not add information

##### Steps to reproduce this issue:
Enter URL into box and press add button
Screen shows: Adding to the Whitelist...
Screen shows: Success! The list will refresh.
Screen refreshes
added URL does not show up

**Comment by dschaper** [comment]
Can you run a `pihole -d` and get us a copy of the log output from that command. Just follow the on-screen directions.

**Comment by AtomicLaser** [comment]
Log below:

Just to note this is a fresh install - the install I had wouldn't work on that either, so i tried to reinstall from a fresh jessie lite image downloaded tonight.




IP Addresses of this Pi:
192.xxx.xxx.xxx
127.0.0.1

Gateway check:
ok

#######################################
########## Versions Section ###########
#######################################
Pi-hole Version: v2.7.1
WebUI Version: v1.3

#######################################
######## Whitelist Comparison #########
#######################################

#######################################
######## Blacklist Comparison #########
#######################################

#######################################
############ NSLookup Test ############
#######################################
NSLOOKUP of doubleclick.com from PiHole:
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	doubleclick.com
Address: 192.168.1.92


NSLOOKUP of doubleclick.com from 8.8.8.8:
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	doubleclick.com
Address: 212.56.71.35
Name:	doubleclick.com
Address: 212.56.71.50
Name:	doubleclick.com
Address: 212.56.71.45
Name:	doubleclick.com
Address: 212.56.71.29
Name:	doubleclick.com
Address: 212.56.71.49
Name:	doubleclick.com
Address: 212.56.71.44
Name:	doubleclick.com
Address: 212.56.71.39
Name:	doubleclick.com
Address: 212.56.71.34
Name:	doubleclick.com
Address: 212.56.71.30
Name:	doubleclick.com
Address: 212.56.71.54
Name:	doubleclick.com
Address: 212.56.71.24
Name:	doubleclick.com
Address: 212.56.71.20
Name:	doubleclick.com
Address: 212.56.71.59
Name:	doubleclick.com
Address: 212.56.71.25
Name:	doubleclick.com
Address: 212.56.71.55
Name:	doubleclick.com
Address: 212.56.71.40


#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Sat 2016-06-25 19:40:05 UTC; 4min 13s ago
  Process: 606 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 633 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─633 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─646 /usr/bin/php-cgi
           ├─647 /usr/bin/php-cgi
           ├─648 /usr/bin/php-cgi
           ├─649 /usr/bin/php-cgi
           └─650 /usr/bin/php-cgi

Jun 25 19:40:05 raspberrypi lighttpd[606]: Syntax OK
Jun 25 19:40:05 raspberrypi systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Sat 2016-06-25 19:40:02 UTC; 4min 17s ago
  Process: 450 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 424 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 350 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 449 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─449 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

Jun 25 19:40:00 raspberrypi systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jun 25 19:40:00 raspberrypi dnsmasq[350]: dnsmasq: syntax check OK.
Jun 25 19:40:02 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
#######################################
############ lighttpd.conf ############
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
######### lighttpd error.log ##########
#######################################
2016-06-25 19:12:33: (log.c.164) server started 
2016-06-25 19:16:56: (server.c.1558) server stopped by UID = 0 PID = 1 
2016-06-25 19:18:42: (log.c.164) server started 
2016-06-25 19:39:55: (server.c.1558) server stopped by UID = 0 PID = 1 
2016-06-25 19:40:05: (log.c.164) server started 

#######################################
############### Dnsmasq ###############
#######################################

#######################################
########### 01-pihole.conf ############
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
############ gravity.list #############
#######################################
101871 /etc/pihole/gravity.list

Hostname of this pihole is: 
raspberrypi
#######################################
################ Hosts ################
#######################################
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

127.0.1.1	raspberrypi

#######################################
############## Whitelist ##############
#######################################
raw.githubusercontent.com
adblock.gjtech.net
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net

#######################################
############## Blacklist ##############
#######################################

#######################################
############ adlists.list #############
#######################################
No adlists.list file found... using adlists.default!
#######################################
############# pihole.log ##############
#######################################
[Snipped]

**Comment by jacobsalmela** [comment]
Can you check if `/etc/sudoers.d/pihole` exists and also verify the `sudo` is installed?  We haven't added that to the debug log yet.

**Comment by AtomicLaser** [comment]
pi@raspberrypi:/ $ /etc/sudoers.d/pihole                                         
-bash: /etc/sudoers.d/pihole: No such file or directory                          
pi@raspberrypi:/ $ cd /etc/sudoers.d/                                            
pi@raspberrypi:/etc/sudoers.d $ ls                                               
README  sudoers_commands                                                         
pi@raspberrypi:/etc/sudoers.d $                                                  
                                                                                 

pi@raspberrypi:/ $ sudo                                                          
usage: sudo -h | -K | -k | -V                                                    
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]                
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]      
            [command]                                                            
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p    
            prompt] [-u user] [VAR=value] [-i|-s] [<command>]                    
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p     
            prompt] [-u user] file ...                                           
pi@raspberrypi:/ $ which sudo                                                    
/usr/bin/sudo                                                                    
pi@raspberrypi

**Comment by jacobsalmela** [comment]
OK, so you have `sudo`, but not the sudoers file, which allows the Web interface to run the `pihole` commands.  You can run the installer again to get it, or run this command:
```
sudo curl -o /etc/sudoers.d/pihole https://raw.githubusercontent.com/pi-hole/pi-hole/master/advanced/pihole.sudo
```

**Comment by AtomicLaser** [comment]
Oh wait, sorry, I was looking at the wrong Pi!

The actual pi-hole DOES have sudo and the /etc/sudoers.d/pihole file 

Sorry!

**Comment by Mcat12** [comment]
So is this fixed?

**Comment by AtomicLaser** [comment]
nope :(

**Comment by Ang3er** [comment]
Same problem here, the sudors file is existing, but I did not get 100 percent what you meant with " is sudo installed" ... should pihole run as sudo?
Thanks in advance
Dominik

**Comment by jacobsalmela** [comment]
Type `which sudo` to check if it is installed.  Will you also send the output of `ls -l /etc/sudoers.d`

**Comment by Ang3er** [comment]
As suggested I checked which sudo, an its outputting me a valid path (/usr/bin/sudo
). The requested output of sudoers.d is 
-r--r----- 1 root root 490 Jun 27 20:15 pihole
-r--r----- 1 root root 958 Mar 13  2015 README

Thanks in advance

**Comment by Longshot** [comment]
Also having this problem.
sudo is installed
sudoers file does exists
running on debian jessie

**Comment by diginc** [comment]
@Longshot Chrome or Firefox? 

Some browsers maybe broken in the current version and https://github.com/pi-hole/AdminLTE/pull/110 or https://github.com/pi-hole/AdminLTE/pull/112 should address the bugs.  These fixes are not in the current deployed master branch pi-holes get by default.  You could checkout devel to get 112's quick fix.  I'm hoping my PR gets merged soon too since it'll help with debugging what is going on exactly.

Something else I learned about this problem which probably won't effect many people: while fixing my alpine nginx php-fpm docker that $PATH was missing /usr/local/* and that broke it too, if anyone is running non default lighttpd+fastcgi stacks and has this problem, check out phpinfo() to see if PHP has the location for `pihole` in the $PATH Environment / $_SERVER variables.

**Comment by Longshot** [comment]
@diginc 
On Chrome and Firefox (Ubuntu 14.04) and Edge (W10)
The only thing not default with my lighttp install is that it's running on port 81.

I've just used the command line for now to add URLs to the whitelist and will wait patiently for the fix :)

**Comment by Mcat12** [comment]
@Longshot Can you open Chrome, go to `pi.hole/admin`, and open the whitelist page? Then click F12, which will open up the dev tools. Open the "Network" tab in the dev tools, and click the filter called "XHR" below the filter text box. Reload the page and then try to whitelist a domain. Now, a few new items in the network tab should have appeared. Click on the one with the name "add.php". Another info pane will pop up, and open the "Response" tab in that new info pane. Copy the contents and share them here.

**Comment by Longshot** [comment]
@Mcat12 It just has one line which says:

Failed CORS

**Comment by Mcat12** [comment]
How are you accessing the web interface? http://pi.hole, etc. It might be that you're using port 81, which makes the origin http://pi.hole:81. We don't take into account ports. So you might have to edit a line on two specific php files.

**Comment by AtomicLaser** [comment]
@Mcat12 Well, the whitelisting just worked fine for me!  Must have been an update or something which *may* have fixed it...

::: Refresh lists in dnsmasq... done!

**Comment by Longshot** [comment]
@Mcat12  I'm using this URL:
http://192.168.2.39:81/admin/index.php

I don't think it should complicate things but Pi-Hole is running on Debian Jessie server on a VirtualBox VM on an Ubuntu host :)

**Comment by Mcat12** [comment]
@Longshot sorry for responding so late. Change [this](https://github.com/pi-hole/AdminLTE/blob/master/php/add.php#L6) line on both `/admin/php/add.php` and `/admin/php/sub.php`:
```php
if($_SERVER['HTTP_ORIGIN'] == "http://pi.hole:81" || $_SERVER['HTTP_ORIGIN'] == "http://${_SERVER['SERVER_ADDR']}:81")
```

**Comment by Ang3er** [comment]
@Mcat12 Thank you very much .... such a quite obvious mistake :P My problem ist that the pihole runs on a server which already has a web server ---> therefore i need to change manually the port to (in my case) 12345 ... is there any smart solution for running the lighthttp behind my apache? or is there even a quite convenient way to maybe host it direct on the apache?

Thanks
Dominik

**Comment by Mcat12** [comment]
I think there's an Apache config for Pi-hole floating around somewhere... It's certainly possible!

**Comment by shieldsit** [comment]
I was fighting this issue and the fix for me was to edit admin/php/auth.php and add my server name to the $AUTHORIZED_HOSTNAMES array.  Don't forget the ' around your new entry and the , after the previous entry!

**Comment by Keelan** [comment]
@shieldsit also just did this! Worked great.

Why isn't SERVER_ADDR picking this up?

http://stackoverflow.com/questions/5705082/is-serverserver-addr-safe-to-rely-on

**Comment by Mcat12** [comment]
SERVER_ADDR returns the IP address of the server. Are you unable to whitelist from the IP address? Please open a new issue if you need help.
