### ISSUE TITLE
Persistent 'old' interface name 

### ISSUE THREAD

**Issue by gitzone83** [pi-hole/pi-hole#5469]
### Versions

- Pi-hole version is v5.17.1 (Latest: v5.17.2) 
- web version is v5.20.1 (Latest: null) 
- FTL version is v5.23 (Latest: v5.23)  

### Platform

- OS and version:  Ubuntu 22.04.3 LTS

- Platform:  self-hosted VM

### Expected behavior

The original PIHole installation was hosted on KVM and used enp1s0 interface name. Once the VM was migrated into HyperV, interface name was changed to eth0. The GUI still shows enp1s0 even though underlying VM uses eth0, as shown below

ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.150.3  netmask 255.255.255.0  broadcast 192.168.150.255
        inet6 fe80::215:5dff:fe96:201  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:96:02:01  txqueuelen 1000  (Ethernet)
        RX packets 4261702  bytes 926360630 (926.3 MB)
        RX errors 0  dropped 48596  overruns 0  frame 0
        TX packets 1597063  bytes 701732640 (701.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 27683068  bytes 1736619291 (1.7 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27683068  bytes 1736619291 (1.7 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I am looking for a way to change the interface name displayed in GUI. I have not been able to locate where it is pulled from. PIHole / VM has been rebooted several times and the interface name persists. 

### Actual behavior / bug

see above, interface name shown in settings is incorrect and does not match the VM interface name

### Steps to reproduce

see above, interface name shown in settings is incorrect and does not match the VM interface name

## Debug Token

- URL:  https://tricorder.pi-hole.net/Gk5voPKO/

### Screenshots

![image](https://github.com/pi-hole/pi-hole/assets/25298905/8ee47e9b-efa5-41ec-9d22-6ad0964e23ba)

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
Your config has the old value:

```ini
*** [ DIAGNOSING ]: Setup variables
    PIHOLE_INTERFACE=enp1s0
```

You need to run `pihole -r` to reconfigure.

**Comment by gitzone83** [comment]
That did fix the issue, it is just odd that the system has to be reinstalled rather than keeping the interface name in exposed settings somewhere for the user to control.

**Comment by jfb-pihole** [comment]
> it is just odd that the system has to be reinstalled

You didn't reinstall - you just changed the configuration settings.
