### ISSUE TITLE
First character of password can not be "!"

### ISSUE THREAD

**Issue by Blubberland** [pi-hole/pi-hole#5474]
### Versions

all, i guess

### Platform
all, i guess

### Expected behavior

change password

### Actual behavior / bug

get an error:
`-bash: {ANY_STRING_WITH_A_!_IN_THE_BEGINNING}: event not found`

### Steps to reproduce

```bash
pihole -a -p {ANY_STRING_WITH_A_!_IN_THE_BEGINNING}
```

## Debug Token

- URL:  

### Screenshots

not necessary

### Additional context
Generated a random password. It happened to have a "!" as the first character.
No big issue, I just regenerated.
But it would have been nice if this was mentioned in the documentation and manpage.

**Comment by yubiuser** [comment]
Good catch.
On a fresh installation at take care this cannot happen

https://github.com/pi-hole/pi-hole/blob/60b6a1016c7f39e1db8359fc5874ae35d8c27ff9/automated%20install/basic-install.sh#L2678

However, when users change their password manually later, we do not check for this condition. I'll fix this.

**Comment by DL6ER** [comment]
Have you tried to enclose the password to be set by single quotes (see below)?

At least this is not an issue with Pi-hole v6.0:

```
$ pihole setpassword '!ABC'
  [✓] New password set
```

![Screenshot from 2023-11-05 11-25-25](https://github.com/pi-hole/pi-hole/assets/16748619/cf4bcfb6-d8ed-45bf-aa80-22c67bc37a55)

**Comment by Blubberland** [comment]
Actually not.
I tried double quotes, which didn't work.
Should've also tried single quotes.

But it's not documented. Would be a better default to catch this error.

**Comment by yubiuser** [comment]
I tried it with v5 and v6: it's working with single quotes in both cases and it works when `pihole setpassword`/`pihole -a -p` is called without a trailing password, hence in interactive mode.
The reason it's not working with leading `!`: this is a build-in bash command for [history expansion](https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html#History-Interaction). The only way around this is to quote it.

**Comment by yubiuser** [comment]
Documentation should be fixed by https://github.com/pi-hole/pi-hole/pull/5476
