### ISSUE TITLE
If you had made any changes in '...', they have been stashed using 'git stash'

### ISSUE THREAD

**Issue by petaflot** [pi-hole/pi-hole#5477]
### Versions
-  Pi-hole version is v5.17.2 (Latest: v5.17.2)
-  web version is v5.20.2 (Latest: v5.20.2)
-  FTL version is v5.23 (Latest: v5.23)

(but I just ran an upgrade after a very long time)

### Platform
pihole image on what appears to be a debian-based system

### Expected behavior

if any changes have been made, ask before stashing or request explicit stashing

### Actual behavior / bug

like "oh just so you know, I broke all the changes you made not because I didn't notice before, not because it was not possible for me to be aware there could have been important changes but because I just didn't give a damn"

AT THE VERY LEAST please give a warning in the doc at https://docs.pi-hole.net/main/update/

### Steps to reproduce

as simple as running the following command:

`pihole -up`

For the record, I didn't do any changes to `/etc/.pihole/` or `/var/www/html/admin/` so I didn't lose anything and I'm not mad, but it's typically the kind of things that would make a start for a bad day.

**Comment by PromoFaux** [comment]
> like "oh just so you know, I broke all the changes you made not because I didn't notice before, not because it was not possible for me to be aware there could have been important changes but because I just didn't give a damn"

This is hyperbole, and not accurate. `git stash` allows for changes to be reapplied (https://git-scm.com/docs/git-stash) Any changes made will need to be checked for compatibility with any updates we've made to Pi-hole on our side. As we have no idea what changes any given user may have made to those directories, it's on the user to reapply their changes (if needed) via the `git stash` command.

`/etc/.pihole` and `/var/www/html/admin` are key component directories. Making any customisations in these directories is not a good idea. If you ever find yourself needing to modify something in those directories - then something has gone wrong.
