### ISSUE TITLE
tabula.technology won't open

### ISSUE THREAD

**Issue by phelix001** [pi-hole/pi-hole#5486]
### Versions
 pihole -v
  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.20.2 (Latest: v5.20.2)
  FTL version is v5.23 (Latest: v5.23)

### Platform
Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Expected behavior

dig tabula.technology

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> tabula.technology
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 42168
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tabula.technology.		IN	A

;; Query time: 16 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Nov 09 15:00:29 EST 2023
;; MSG SIZE  rcvd: 46

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Template ignored. Please head to our user forum at discourse.pi-hole.net for help regarding configuration issues.
