### ISSUE TITLE
Installation issue with Fedora 39 with SELinux disabled

### ISSUE THREAD

**Issue by ItzMiracleOwO** [pi-hole/pi-hole#5487]
![image](https://github.com/pi-hole/pi-hole/assets/76854136/23ed844f-74c8-4f0f-92ba-6bb585742f32)

**Comment by ItzMiracleOwO** [comment]
Already tried with environment variables

![image](https://github.com/pi-hole/pi-hole/assets/76854136/324aacaf-4d90-491f-8b27-1a206627fdde)

**Comment by ItzMiracleOwO** [comment]
SELinux is disabled

![image](https://github.com/pi-hole/pi-hole/assets/76854136/9fff5461-8ed8-4666-9402-19c2330a58c7)

**Comment by bcambl** [comment]
There was recent changes to selinux with Fedora 39. Please allow me some time to investigate and provide some additional troubleshooting steps.

**Comment by bcambl** [comment]
Upon a second look at the info you have provided, your issue is due to how you are trying to call the install from a non-root user. The environment variable is not being properly with your nested bash invocations.

Try switching to root then running the installer:

```
[user@localhost ~]$ sudo su -
[root@localhost ~]# export PIHOLE_SELINUX=true
[root@localhost ~]# curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] Default SELinux: enforcing
  [✗] Current SELinux: enforcing
  [i] SELinux Enforcing detected. PIHOLE_SELINUX env variable set - installer will continue

  [i] Checking dnf for upgraded packages...
```

**Comment by bcambl** [comment]
As mentioned above, there has been changes to how selinux is disabled with Fedora 39.
Please review the instructions found within `/etc/selinux/config` on how to disable selinux via the kernel.

**Comment by ItzMiracleOwO** [comment]
Okay, thanks for your help!
