### ISSUE TITLE
Update failure when document root is customized

### ISSUE THREAD

**Issue by Yoanndp** [pi-hole/pi-hole#5495]
### Versions
- Pi-hole version is v5.3.1 (Latest: v5.17.2)
- AdminLTE version is -1 (Latest: v5.23)
- Current FTL version is v5.2.

### Platform
- OS and version:  Raspbian OS 
- Platform:  Raspberry Pi 4

### Context
- Custom configuration is in use, where the server.document-root admin folder is set to `/var/www/admin` instead of `/var/www/html/admin`
- It appears that the updater is unable to access the repository, even though it exists.

### Expected behavior
The update process should proceed without errors, and the Pi-hole server should be successfully updated.

### Actual behavior / bug
When attempting to update my Pi-hole server using the pihole -up command, I encountered the following error message:
```
Error: Web Admin repo is missing from system
```

### Steps to reproduce
Run pihole -up to update the Pi-hole server.
Observe the error message: "Error: Web Admin repo is missing from system."

**Comment by yubiuser** [comment]
This is kind of expected, as the location of the repo is hard-coded in some places in the bash scripts

https://github.com/pi-hole/pi-hole/blob/60b6a1016c7f39e1db8359fc5874ae35d8c27ff9/advanced/Scripts/update.sh#L15

**Comment by yubiuser** [comment]
As we are using the plain copy of the github repo at `/var/www/html/admin` without further modification, your suggestion should work.

**Comment by yubiuser** [comment]
This is a OS level issue, independently of Pi-hole. Pleases use our support forum at https://discourse.pi-hole.net/ for help.
