### ISSUE TITLE
Network list response truncated and not displayed

### ISSUE THREAD

**Issue by dsm1212** [pi-hole/pi-hole#5497]
### Versions
  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.23 (Latest: v5.23)

### Platform
Docker on Debian Buster

### Expected behavior
Selecting Tools->Network should show a table of devices on my network.

### Actual behavior
The Network table won't display after running a few days. Instead of getting the table I get a message about unknown error and the first few lines of the network table json are displayed.

I find that if I enter the URL for getting the network list, the response is truncated. It truncates at 65528 bytes which is suspicious. Chrome inspector shows the payload the app got was also truncated at the same byte. So is invalid json.

### Steps to reproduce
Start pihole on my network and let it run for a while.
Select Tools->Network

## Debug Token
Previously submitted here: https://github.com/pi-hole/pi-hole/issues/5403
Maybe is gone now. I can grab again if you want, but I didn't see anything useful in the log last time and I believe the 65528 message size is the key clue. I just don't understand why more people are not complaining if there is a 64K byte size limit on this table response. Either this size needs to be increased or the APi needs to be paginated.

**Comment by yubiuser** [comment]
I think you might have "too"  many clients on your network (IPv6?, MAC randomization?) which will increase the JSON response to such a size. Let's check for the number of clients at the table

```
pihole-FTL sqlite3 /etc/pihole/pihole-FTL.db "SELECT Count(ROWID) from network;"
```

**Comment by dsm1212** [comment]
Answer was 289. I think there are several reasons the overall response is large:

1. Devices have 1 ipv4 and 3 ipv6 addresses (typical)
2. iphones constantly change their mac address and show up many times. This can be turned off on the phone, but it's on by default.
3. One of the ipv6 addresses per the standard is temporary so changes frequently.
4. veth devices accumulate when docker starts/stops containers

All this adds up to a lot of entries and addresses. There are a couple of things I'd be happy to do if it were possible:

A. Don't add veth devices to the network table at all. I'm assuming this is just for reporting on this table. If they are needed for something else then this won't work.
B. Keep a limited number of ipv6 address (3), or let me provide the ipv6 prefixes and keep only one from each prefix.

Are either of these possible?

**Comment by dsm1212** [comment]
Deleting the veth interfaces from the table allowed the ui to work. There are also a bunch of br interfaces wihch show as "not using pihole".  A "clean" network table button rather than truncate would be helpfull to work around this.

**Comment by DL6ER** [comment]
I will just mention here that we are currently in the beta phase of our next big Pi-hole v6.0 release which features a completely rewritten API. Truncation due to size constraints violation will not occur here (as long as everything fits into memory... A 4 GB size network table won't work on a Raspberry Pi Zero).

**Comment by yubiuser** [comment]
> A "clean" network table button rather than truncate would be helpfull to work around this.

We have `Settings> System > Flush network table `

**Comment by dsm1212** [comment]
Ah if the new rev is coming which addresses this then close this. I have a little script to purge the veth and be entries for now.
