### ISSUE TITLE
Lighttpd won't change IPv6 port, only IPv4 port

### ISSUE THREAD

**Issue by Chillsmeit** [pi-hole/pi-hole#5503]
### Versions

- Pi-hole:  v5.17.2
- AdminLTE:  v5.21
- FTL:  v5.23

### Platform

- OS and version:  Debian GNU/Linux 12 (bookworm) aarch64 (Raspberry Pi OS Lite 64-bit)

- Platform:  Raspberry Pi 5 8Gb

### Expected behavior

By creating a file in `/etc/lighttpd/conf-enabled/external.conf` and adding `server.port := 22410` to it should change the WebInterface port

### Actual behavior / bug

This does change the interface port but for IPv4 only. 
I can access the webinterface with http://PiIP:22410/admin

But for some reason lighttpd still listens to port 80 for IPv6.
When doing `sudo lsof -i :22410` I get the following:
```
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 1522 www-data    5u  IPv4  15198      0t0  TCP *:22410 (LISTEN)
```
But when doing `sudo lsof -i :80` I get the following:
```
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 1522 www-data    4u  IPv6  15197      0t0  TCP *:http (LISTEN)
```

I wanted to use the **external.conf** instead of just commenting out in `/etc/lighttpd/lighttpd.conf` the line
```
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
```
I'm afraid PiHole will revert this change with an update if I change lighttpd.conf directly

### Steps to reproduce

`sudo nano /etc/lighttpd/conf-enabled/external.conf`
Add this and save `server.port := 22410`
Then restart lighttpd or reboot Pi
`sudo service lighttpd restart`

## Debug Token

- URL:  https://tricorder.pi-hole.net/1yBUV2Jr/

### Additional context

Externally, I don't use IPv6 btw, my router has IPv6 disabled.
I'm using Raspberry Pi OS Lite, that means that I don't have alot of packages that might interfere with this. 
I've only installed nala, neofetch, docker, docker-compose and unbound.
I also tried a clean install with PiHole only, same issue occurred.

**Comment by rdwebdesign** [comment]
> I'm afraid PiHole will revert this change with an update if I change lighttpd.conf directly

This only happens if you have an older `lighttpd.conf` _(installed by pi-hole versions **prior to v5.14.2**)_.
In other words, you shouldn't change `/etc/lighttpd/lighttpd.conf` if your file contains this comment:

https://github.com/pi-hole/pi-hole/blob/60b6a1016c7f39e1db8359fc5874ae35d8c27ff9/advanced/lighttpd.conf.debian#L10-L18

Otherwise, the file is yours and you can even change the port directly in `/etc/lighttpd/lighttpd.conf`.

**Comment by Chillsmeit** [comment]
Oh ok! Thank you for your help!
I'll just change the port directly then. But hypothetically, what if I had a Pi-Hole version prior to v5.14.2, how would I go about it?

**Comment by rdwebdesign** [comment]
Versions older than v5.14.2 use a dedicated `/etc/lighttpd/lighttpd.conf` (containing the header from previous comment), so you should change that file. Also, older versions don't use `/conf-enabled/` directory.
If I remember correctly, you will need to override the port in `/etc/lighttpd/external.conf`.

**Comment by Chillsmeit** [comment]
Thanks for the help/info!
