### ISSUE TITLE
pihole tries to access edgesuite.net - why?

### ISSUE THREAD

**Issue by Emporea** [pi-hole/pi-hole#5505]
Pihole on raspberry pi 3 bullseye
![Screenshot_20231201-221458_Fennec_1](https://github.com/pi-hole/pi-hole/assets/21969523/81fb01ed-4b8b-40e8-9009-6f9abbbee1c4)

![Screenshot_20231201-221316_Fennec_1](https://github.com/pi-hole/pi-hole/assets/21969523/e676ba43-ac2f-414f-9229-1e03cc6712f5)

What is edgesuite.net and why does pi hole tries to acves it 25000 times since yesterday??

**Comment by yubiuser** [comment]
Pi-hole does not query that domain. It's the host device running Pi-hole (or any software running next to it) that queries this domain.

**Comment by PromoFaux** [comment]
Closing, as this isn't a Pi-hole issue per se.

You'll need to identify the process on your machine that is making these requests. Maybe something in here can help:

https://serverfault.com/questions/192893/how-can-i-identify-which-processes-are-generating-udp-traffic-on-linux
