### ISSUE TITLE
Not working on my Airport Extreme.

### ISSUE THREAD

**Issue by leftynaut** [pi-hole/pi-hole#552]
I've sent my top DNS server to my RPi's IP. My second is set to 8.8.8.8

Rebooted my router and my internet is working fine on all devices, but ad blocking isn't working. I'm able to pull up the admin panel on my MacBook just fine, but it's not showing any stats.

Not sure where to go from here...

**Comment by dschaper** [comment]
Hi, it is possible that having Google's DNS server in the second place on your router is letting queries out to use that server. Some routers will go down the list, some will round robin, and some will just take the first response that comes back. What kind of router are you using?

In the configuration of the Pi-Hole, the process asks for an upstream DNS server, and that's the server that the Pi-Hole will query if it can't find the domain on it's own internal list. Are you able to just set a single IP address in the routers DNS configuration?

And just to check and make sure your Pi-Hole installation is working correctly, can you run a `pihole -d` from the terminal, and then paste the results of the logfile generated on PasteBin for us to take a look at and to start troubleshooting?

Thanks

**Comment by Mcat12** [comment]
Just from glancing at some logs, it looks like dnsmasq just throws out a request to all upstream servers and uses the first one that comes back.

**Comment by rakkesh** [comment]
I am using `pi-hole` on raspi with router - Apple Airport Extreme, and the setup works just fine.

@leftynaut to verify whether you're getting a response from your `raspberry pi`, open `Terminal.app` and run dig - 

```
$ dig

; <<>> DiG 9.8.3-P1 <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56378
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			3599656	IN	NS	l.root-servers.net.
.			3599656	IN	NS	f.root-servers.net.
.			3599656	IN	NS	d.root-servers.net.
.			3599656	IN	NS	m.root-servers.net.
.			3599656	IN	NS	c.root-servers.net.
.			3599656	IN	NS	k.root-servers.net.
.			3599656	IN	NS	j.root-servers.net.
.			3599656	IN	NS	i.root-servers.net.
.			3599656	IN	NS	h.root-servers.net.
.			3599656	IN	NS	g.root-servers.net.
.			3599656	IN	NS	b.root-servers.net.
.			3599656	IN	NS	e.root-servers.net.
.			3599656	IN	NS	a.root-servers.net.

;; Query time: 19 msec
;; SERVER: 192.168.1.100#53(192.168.1.100)
;; WHEN: Fri Jul 15 23:00:13 2016
;; MSG SIZE  rcvd: 241
```
> ;; SERVER: 192.168.1.100#53(192.168.1.100)

`192.168.1.100` is the IP address of my local DNS server on `raspberry pi`, your IP address may differ.

If `SERVER` IP address in `dig` output is `8.8.8.8` then most probably DNS traffic is not reaching `raspberry pi`.

**Comment by leftynaut** [comment]
@rakkesh got 8.8.8.8

**Comment by rakkesh** [comment]
@leftynaut that would imply, DNS traffic in your network or just your Mac is not able to reach `pi-hole`. Try pinging your `raspi` from your Mac and check whether it succeeds.

Also, make sure that the output of `cat /etc/resolv.conf` shows your `raspi` address listed as the foremost `nameserver`. As an example, my DNS configuration is as follows - 

```
$ cat /etc/resolv.conf
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
domain ahrudaya.local
nameserver 192.168.1.100
nameserver 172.16.1.100
```

If the order of `nameserver` addresses is not right, then change the setting on your Airport Extreme.

**Comment by Zambonilli** [comment]
I was able to get pi-hole working on my network with the airport extreme AC on the latest firmware.

**Comment by leftynaut** [comment]
Must be a user error then. I'm switching routers anyways, so I'll close this for now.
