### ISSUE TITLE
missing redirection to http://pihole.FQDN/admin/

### ISSUE THREAD

**Issue by t0b3** [pi-hole/pi-hole#5530]
**Observed behaviour**
For serving http://pihole.FQDN/admin/ nor http://192.168.x.y/admin/ neither http://pi.hole/admin/ etc. there is no domain restriction - but contraintuitively the forwarding to /admin/ only happens on http://pi.hole/

**Expected behaviour**
Consistent forwarding on any of the served domains

may we skip this host check?
https://github.com/pi-hole/pi-hole/blob/60b6a1016c7f39e1db8359fc5874ae35d8c27ff9/advanced/pihole-admin.conf#L75

**Comment by yubiuser** [comment]
This was a deliberate decision. Users may host other stuff at `http://192.168.x.y` so we do not enforce the redirect for hosts other than `pi.hole`

**Comment by t0b3** [comment]
hmm, can I override this permanently by adding yet another file i.e. /etc/lighttpd/conf-enabled/95-redirect-admin.conf ?

**Comment by yubiuser** [comment]
You should be able to do that. Yoi should be able to set multiple

```
 $HTTP["host"] == "XXXX"
```

configurations. See the example at https://redmine.lighttpd.net/projects/1/wiki/docs_configuration
  
  Best would be if you just go ahead and try it....
