### ISSUE TITLE
Issues with Pi-hole v6

### ISSUE THREAD

**Issue by sefinek24** [pi-hole/pi-hole#5531]
### Versions

- Pi-hole:  6e8029f6
- AdminLTE:  071beb84
- FTL:  a8d29915

### Platform

- OS and version:  Ubuntu 20.4

- Platform:  HP Terminal

From time to time, I encounter issues with the DNS resolver.
![](https://cdn.sefinek.net/static/31.12.2023/brave_1GzaPGhSU3CJ.png)
![](https://cdn.sefinek.net/static/31.12.2023/brave_YMIPAMxUiSYS.png)

The failure lasts for about 50 seconds, then after a while everything returns to normal.

Additionally, I sometimes have issues with false positives. Despite the domain not being on ANY blocklist, Pi-hole still blocks it for some reason. Recently, Pi-hole blocked api.nuget.org for some reason, even though the indicated subdomain was not on the blocked list. I had the same problem with other domains.

I suspect there might be an issue with Gravity. I've recently checked multiple times to confirm if the domain was indeed on the blocklist, and it never appeared on it. So, why does Pi-hole block something that has never been on the blocklist?

## Debug Token
https://tricorder.pi-hole.net/JG11AJjA/

**Comment by yubiuser** [comment]
The second issue is discussed here: https://discourse.pi-hole.net/t/pi-hole-blocking-domain-it-shouldnt/67111
 
A fixing PR is awaiting review.
