### ISSUE TITLE
GUI list updater shows 0 domains instead of the correct amount.

### ISSUE THREAD

**Issue by sjhgvr** [pi-hole/pi-hole#5534]
A oisd user reported the following:

### Actual behavior / bug

"I just updated the adlist in my pi-hole to https://big.oisd.nl/
However, pulling up the adlist shows 0 domains listed, compared to the old list:"
![image](https://github.com/pi-hole/pi-hole/assets/51121527/eb645d6f-afc7-4963-aa56-ff85ff11d5c2)
"I understand the format was changed recently, but is that what would cause the "0" here, ...."

### Versions
- Pi-hole:  v5.17.2  
- FTL:  v5.23
- Web: v5.21

### Expected behavior

Show correctly loaded (ABP) domains on GUI instead of 0

Note: CLI shows correct (ABP) domains:
![image](https://github.com/pi-hole/pi-hole/assets/51121527/0488f9e2-f550-4c44-b434-c993fdc13700)

**Comment by yubiuser** [comment]
Thanks for the report. This is a cosmetic issue on Pi-hole v5. It's fixed in v6 already. I'm not sure if anyone is going to back-port the fix.

![Screenshot at 2024-01-04 23-00-42](https://github.com/pi-hole/pi-hole/assets/26622301/30f72f6d-af6d-4448-b290-4b54edc6a218)
