### ISSUE TITLE
Conditional forwarding (to external DHCP server) configuration UI does not support multiple entries for i.e. adding IPv6 config

### ISSUE THREAD

**Issue by binaryanomaly** [pi-hole/pi-hole#5539]
### Versions
Core
    Version is v5.17.1-255-ge14792bc (Latest: v5.17.3)
    Branch is development-v6
    Hash is e14792bc (Latest: e14792bc)
Web
    Version is v5.19-626-g7052ff0d (Latest: v5.21)
    Branch is development-v6
    Hash is 7052ff0d (Latest: 7052ff0d)
FTL
    Version is vDev-933e6f6 (Latest: v5.24)
    Branch is development-v6
    Hash is 933e6f60 (Latest: 933e6f60)

### Platform
- OS and version:  Debian GNU/Linux 12 (bookworm)
- Platform:  VM

### Expected behavior

Conditional forwarding (to external DHCP server) does not support IPv6 addresses.

### Actual behavior / bug

It is only possible to provide a DHCPv4 server to forward requests to obtain device/hostnames.

### Steps to reproduce

1. Go to: Settings -> DNS
2. Scroll down to 'Conditional forwarding'
3. Observe configuration UI (only one possibility for IPv4)

### Screenshots

![image](https://github.com/pi-hole/pi-hole/assets/4775424/8f22133e-20dc-4993-a26c-eb3d2c313765)

### Additional context

Might be just an UI issue. Maybe the functionality is already present but not properly reflected in the UI.

**Comment by yubiuser** [comment]
Did you try to set an IPv6 there and observed an issue? Or do you just assume it does not work? On the screenshot it does not say "IPv4-only", just the examples are IPv4 only.

**Comment by binaryanomaly** [comment]
I'd need to be able to maintain an entry for both IPv4 and IPv6.
It seems only the v6 UI part is lacking, functionality in the backend is there according to here: https://github.com/pi-hole/web/pull/1208

What I observe is that only few IPv6 addresses get looked up while it works almost 100% with IPv6 with only being able to configure 1 option (the IPv4 at this time).

I have now added the IPv6 reverse lookup config manually in `/etc/dnsmasq.d/90-reverse-ipv6.conf` but ideally this would be possible from the UI.

**Comment by yubiuser** [comment]
More is likely to come ...
https://github.com/pi-hole/FTL/pull/1797

**Comment by binaryanomaly** [comment]
That would be awesome.
