### ISSUE TITLE
Hostnames not resolving on Dashboard tab for ipv6 devices

### ISSUE THREAD

**Issue by moya2162** [pi-hole/pi-hole#5544]
### Versions

- Pi-hole:  5.17.2
- AdminLTE:  5.21
- FTL:  5.23

### Platform

- OS and version:  Debian Bookworm

- Platform:  ODROID HC4 (arm64)

### Expected behavior

_On Pihole's Dashboard summary tab, under top clients, client hostname, both ipv4 and ipv6 should resolve._

### Actual behavior / bug

_On Pihole's Dashboard summary tab, under top clients, client hostname, ipv6 specifically, does not resolve. Client is identified under Network tab. There appears to be an issue where not all hostnames are applied correctly to ipv6 addresses on the Dashboard._

### Steps to reproduce

1. Go to "Dashboard" tab.
3. Scroll down to "Top Clients" and view hostnames. ipv6 not all ipv6 devices have hostnames resolved. 

## Debug Token

- URL:  n/a

### Screenshots

**Dashboard Tab**
![pihole1-edit](https://github.com/pi-hole/pi-hole/assets/120048096/7828f4b0-8d25-47d0-89ee-3ab72fbfbaac)

**Network Tab**
![pihole2-edit](https://github.com/pi-hole/pi-hole/assets/120048096/96c928ee-3f5f-4829-bbff-74bed5a881dc)

### Additional context

_Client hostnames resolved via EDNS0 method. All clients are able to resolve under network tab correctly for both ipv4 and ipv6 addresses. Dashboard appears to be bugged for some ipv6 addresses._

**Comment by Aura67** [comment]
@moya2162 First you bring your Linux up to date with: apt update && apt upgrade -y then you first do: reboot and then you log back into your SSH and enter: pihole -up a new version came the pihole out your pihole is out of date

**Comment by moya2162** [comment]
Linux is already up to date and pihole docker image was updated to latest version and issue remains. I'm not surprised the update did not fix it because the changelog did not indicate this issue would be fixed. This has been an issue for me for minimum last 3 months. There appears to be a disconnect with the dashboard tab not updating hostnames as fast as the network tab is able to identify it. The dashboard tab and query log eventually get the hostname resolved however it takes forever to do so. It should be instant like how the network tab can identify it. 

Another data point to add is that my ftl db got corrupted and i had to delete it and rebuild it, but this issue still remains.

**Comment by moya2162** [comment]
bump

**Comment by moya2162** [comment]
bump

**Comment by bkodenkt** [comment]
I can confirm this issue. I was closely watching logs the last weeks while checking out a different problem, this logging in frequently, and indeed could not see resolved IPv6 hostnames on the dashboard very often. Since I did not encounter this problem when checking the actual logs, maybe it is hust some display issue on the dashboard web-frontend?

**Comment by PromoFaux** [comment]
I'm unable to check this from an IPv6 perspective (I never did get around to setting it up on my network)

But if you're feeling adventurous - could you see if this is still an issue in our v6 beta? https://pi-hole.net/blog/2023/10/09/pi-hole-v6-beta-testing/

**Comment by bkodenkt** [comment]
I just might snapshot the current system and upgrade to v6 and restore the snapshot afterwards. Maybe I'll have some time this weekend! ✌️

**Comment by moya2162** [comment]
bump

@bkodenkt were you able to check if this issue is reoccurring in v6?

**Comment by moya2162** [comment]
Hostname resolution does not appear to be working on v6. Appears PTR requests are not being generated to be forwarded upstream. 

I made an issue about it here: https://github.com/pi-hole/FTL/issues/1975#issue-2317248546
