### ISSUE TITLE
V6/Does not block anymore

### ISSUE THREAD

**Issue by Just2Confuse** [pi-hole/pi-hole#5546]
### Versions

Core
    Version is b756262 (Latest: v5.17.3)
    Branch is development-v6
    Hash is b756262e (Latest: b756262e)
Web
    Version is 7e21b3b (Latest: v5.21)
    Branch is development-v6
    Hash is 7e21b3b0 (Latest: 7e21b3b0)
FTL
    Version is vDev-b0c2ab9 (Latest: v5.24)
    Branch is development-v6
    Hash is b0c2ab9d (Latest: b0c2ab9d)

### Platform

- Bookworm / Docker / Pi 5

- Platform:  Raspberry Pi 5

### Expected behavior

This version dosent block or count blocked queries. Also on https://d3ward.github.io/toolz/adblock.html there is not so much. Counter in Pihole (Blocked queries) ae "0"

### Actual behavior / bug

These version (Docker) dosent block anymore. At least that's how it looks. "Blocked Queries" are empty. 
Systems run in a Docker Container. Also latest V5. In V5 everythung locks as it should. 
V6 are not my permanent blocker, im running V5. That's why you see so few DNS queries. 

### Steps to reproduce

Just browse
Also on https://d3ward.github.io/toolz/adblock.html there is not so much. Counter in Pihole (Blocked queries) ae "0"

## Debug Token

- URL:  https://tricorder.pi-hole.net/H6MtzqvJ/

### Screenshots

![pi1](https://github.com/pi-hole/pi-hole/assets/140651588/b2c52693-b868-4e77-8ae8-0c17256500db)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
I don't see any obvious issue in your debug log. Did you consider, that non of the 4030 queries was one that should have been blocked?

Please run `dig flurry.com @IP_of_pihole_v6` and post the output.

**Comment by Just2Confuse** [comment]
> dig flurry.com @IP_of_pihole_v6

Dig from the pi againts V&
`
mypi@Pi5:~ $ dig flurry.com @192.168.1.3

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> flurry.com @192.168.1.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18855
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;flurry.com.                    IN      A

;; ANSWER SECTION:
flurry.com.             167     IN      A       34.225.127.72
flurry.com.             167     IN      A       13.251.69.97
flurry.com.             167     IN      A       54.161.105.65
flurry.com.             167     IN      A       34.213.101.254
flurry.com.             167     IN      A       13.50.184.192
flurry.com.             167     IN      A       44.228.206.170
flurry.com.             167     IN      A       18.136.37.69
flurry.com.             167     IN      A       13.49.212.207

;; Query time: 0 msec
;; SERVER: 192.168.1.3#53(192.168.1.3) (UDP)
;; WHEN: Fri Jan 12 21:39:28 CET 2024
;; MSG SIZE  rcvd: 167

mypi@Pi5:~ $

`



Dig againts V5 from the Pi. Stop V6 Container and start V5 Container
```
mypi@Pi5:~ $ dig flurry.com @192.168.1.3

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> flurry.com @192.168.1.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45252
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;flurry.com.                    IN      A

;; ANSWER SECTION:
flurry.com.             2       IN      A       0.0.0.0

;; Query time: 0 msec
;; SERVER: 192.168.1.3#53(192.168.1.3) (UDP)
;; WHEN: Fri Jan 12 21:42:14 CET 2024
;; MSG SIZE  rcvd: 55

mypi@Pi5:~ $

```

Screenshot from V6
![dig_v6](https://github.com/pi-hole/pi-hole/assets/140651588/c2834efd-4538-4985-aa25-00130c652731)

**Comment by yubiuser** [comment]
What are the corresponding lines in `/var/log/pihole/pihole.log` for the `flurry.com` query?

**Comment by Just2Confuse** [comment]
> `/var/log/pihole/pihole.log`

`PiHole6:/# cat /var/log/pihole/pihole.log | grep flurry
Jan 12 20:37:56 dnsmasq[151]: query[A] flurry.com from 192.168.1.3
Jan 12 20:37:56 dnsmasq[151]: forwarded flurry.com to 8.8.8.8
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 13.251.69.97
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 54.161.105.65
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 34.213.101.254
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 13.50.184.192
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 44.228.206.170
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 18.136.37.69
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 13.49.212.207
Jan 12 20:37:56 dnsmasq[151]: reply flurry.com is 34.225.127.72
Jan 12 20:38:45 dnsmasq[151]: query[A] flurry.com from 192.168.1.3
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 13.251.69.97
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 54.161.105.65
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 34.213.101.254
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 13.50.184.192
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 44.228.206.170
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 18.136.37.69
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 13.49.212.207
Jan 12 20:38:45 dnsmasq[151]: cached flurry.com is 34.225.127.72
Jan 12 20:39:28 dnsmasq[151]: query[A] flurry.com from 192.168.1.3
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 34.225.127.72
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 13.251.69.97
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 54.161.105.65
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 34.213.101.254
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 13.50.184.192
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 44.228.206.170
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 18.136.37.69
Jan 12 20:39:28 dnsmasq[151]: cached flurry.com is 13.49.212.207
PiHole6:/# `

**Comment by yubiuser** [comment]
Scratch it. It's this regex `(\.|^)|bild\.de$ ` There is an additional `|` which makes the regex catch everything.

**Comment by Just2Confuse** [comment]
> Scratch it. It's this regex `(\.|^)|bild\.de$ ` There is an additional `|` which makes the regex catch everything.

F....this is right. I would never have found that on my own. I'm not sure when the entry was added. 
High praise and "hats off" to this great analysis. My apologies !!!

```
mypi@Pi5:~ $ dig flurry.com @192.168.1.3

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> flurry.com @192.168.1.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43976
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;flurry.com.                    IN      A

;; ANSWER SECTION:
flurry.com.             2       IN      A       0.0.0.0

;; Query time: 3 msec
;; SERVER: 192.168.1.3#53(192.168.1.3) (UDP)
;; WHEN: Fri Jan 12 22:01:51 CET 2024
;; MSG SIZE  rcvd: 55

mypi@Pi5:~ $

```

**Comment by yubiuser** [comment]
Your're welcome. After a few hundred debug logs you know what to look for ;-)
