### ISSUE TITLE
Trouble Whitlisting v2.7.1

### ISSUE THREAD

**Issue by jbukfan** [pi-hole/pi-hole#555]
##### Expected Behaviour:
When adding to the Whitelist, i should see message that it succeeded.

##### Actual Behaviour:
When adding to the Whiltelist, i get an error that "something went wrong". after enabling the debug log and trying again, it generated the following log:

IP Addresses of this Pi:
192.168.2.217
127.0.0.1

Gateway check:
ok

#######################################
#######################################
Pi-hole Version: v2.7.1
WebUI Version: v1.3

#######################################
#######################################

#######################################
#######################################

#######################################
#######################################
NSLOOKUP of doubleclick.com from PiHole:
Server:		192.168.2.217
Address:	192.168.2.217#53

Name:	doubleclick.com
Address: 192.168.2.217

NSLOOKUP of doubleclick.com from 8.8.8.8:
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	doubleclick.com
Address: 76.73.145.19
Name:	doubleclick.com
Address: 76.73.145.25
Name:	doubleclick.com
Address: 76.73.145.16
Name:	doubleclick.com
Address: 76.73.145.21
Name:	doubleclick.com
Address: 76.73.145.15
Name:	doubleclick.com
Address: 76.73.145.18
Name:	doubleclick.com
Address: 76.73.145.27
Name:	doubleclick.com
Address: 76.73.145.22
Name:	doubleclick.com
Address: 76.73.145.24
Name:	doubleclick.com
Address: 76.73.145.23
Name:	doubleclick.com
Address: 76.73.145.29
Name:	doubleclick.com
Address: 76.73.145.28
Name:	doubleclick.com
Address: 76.73.145.20
Name:	doubleclick.com
Address: 76.73.145.17
Name:	doubleclick.com
Address: 76.73.145.26

#######################################
#######################################

lighttpd processes status:

dnsmasq processes status:
#######################################
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
#######################################
2016-07-03 06:25:07: (server.c.1242) logfiles cycled UID = 0 PID = 3453 
2016-07-03 07:30:58: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/admin/php/add.php on line 16
 
2016-07-03 16:55:43: (server.c.1558) server stopped by UID = 0 PID = 4163 
2016-07-03 16:56:57: (log.c.166) server started 
2016-07-03 16:58:17: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/admin/php/add.php on line 16
 
2016-07-03 16:58:24: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Notice:  Undefined index: HTTP_ORIGIN in /var/www/html/admin/php/add.php on line 6
PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/admin/php/add.php on line 16
 

#######################################
#######################################

#######################################
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
#######################################
101949 /etc/pihole/gravity.list

Hostname of this pihole is: 
buehrle-pi1
#######################################
#######################################
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
fe00::0		ip6-localnet
ff00::0		ip6-mcastprefix
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

127.0.1.1	buehrle-pi1

#######################################
#######################################
raw.githubusercontent.com
adblock.gjtech.net
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net

#######################################
#######################################

#######################################
#######################################
No adlists.list file found... using adlists.default!
#######################################
#######################################
Jul  3 17:07:48 dnsmasq[4669]: query[A] lyncdiscoverinternal.baptisthealth.net from 192.168.2.241
Jul  3 17:07:48 dnsmasq[4669]: forwarded lyncdiscoverinternal.baptisthealth.net to 8.8.4.4
Jul  3 17:07:48 dnsmasq[4669]: query[A] lyncdiscover.baptisthealth.net from 192.168.2.241
Jul  3 17:07:48 dnsmasq[4669]: forwarded lyncdiscover.baptisthealth.net to 8.8.4.4
Jul  3 17:07:48 dnsmasq[4669]: reply lyncdiscoverinternal.baptisthealth.net is NXDOMAIN-IPv4
Jul  3 17:07:48 dnsmasq[4669]: reply lsweb1-ext.baptisthealth.net is 198.160.135.30
Jul  3 17:07:48 dnsmasq[4669]: query[A] lsweb1-ext.baptisthealth.net from 192.168.2.241
Jul  3 17:07:48 dnsmasq[4669]: cached lsweb1-ext.baptisthealth.net is 198.160.135.30
Jul  3 17:07:50 dnsmasq[4669]: query[A] doubleclick.com from 192.168.2.217
Jul  3 17:07:50 dnsmasq[4669]: /etc/pihole/gravity.list doubleclick.com is 192.168.2.217
Jul  3 17:08:05 dnsmasq[4669]: query[A] safebrowsing.google.com from 192.168.2.215
Jul  3 17:08:05 dnsmasq[4669]: forwarded safebrowsing.google.com to 8.8.8.8
Jul  3 17:08:05 dnsmasq[4669]: forwarded safebrowsing.google.com to 8.8.4.4
Jul  3 17:08:05 dnsmasq[4669]: reply sb.l.google.com is 74.125.71.93
Jul  3 17:08:05 dnsmasq[4669]: reply sb.l.google.com is 74.125.71.136
Jul  3 17:08:05 dnsmasq[4669]: reply sb.l.google.com is 74.125.71.190
Jul  3 17:08:05 dnsmasq[4669]: reply sb.l.google.com is 74.125.71.91
Jul  3 17:08:06 dnsmasq[4669]: query[A] safebrowsing.google.com from 192.168.2.215
Jul  3 17:08:06 dnsmasq[4669]: cached safebrowsing.google.com is <CNAME>
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.91
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.190
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.136
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.93
Jul  3 17:08:06 dnsmasq[4669]: query[A] safebrowsing.google.com from 192.168.2.215
Jul  3 17:08:06 dnsmasq[4669]: cached safebrowsing.google.com is <CNAME>
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.93
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.91
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.190
Jul  3 17:08:06 dnsmasq[4669]: cached sb.l.google.com is 74.125.71.136
Jul  3 17:08:11 dnsmasq[4669]: query[A] rtupdate.wunderground.com from 192.168.2.217
Jul  3 17:08:11 dnsmasq[4669]: forwarded rtupdate.wunderground.com to 8.8.4.4
Jul  3 17:08:11 dnsmasq[4669]: reply rtupdate-wxu.weather-perf.akadns.net is 38.102.137.157
Jul  3 17:08:11 dnsmasq[4669]: query[AAAA] rtupdate.wunderground.com from 192.168.2.217
Jul  3 17:08:11 dnsmasq[4669]: cached rtupdate.wunderground.com is <CNAME>
Jul  3 17:08:11 dnsmasq[4669]: cached rtupdate-wxu.weather-perf.akadns.net is NODATA-IPv6

##### Steps to reproduce this issue:
Click  on Whitelist and entered address.

**Comment by Mcat12** [comment]
Looks like you might have an old version of PHP. Make a new file under `/var/www/html/` called `phpinfo.php` and put the following in it:
```
<?php
phpinfo();
?>
```
Save it and open up `http://pi.hole/phpinfo.php`. Look under the `Core` header for `PHP Version` and post it here.

**Comment by jbukfan** [comment]
Looks like i'm having issues with root user as well.. it's prompting for a pw which i don't guess i know.  I did everything as user pi ... so i can't even create the file above as requested until i resolve that..

**Comment by Mcat12** [comment]
Do you need root access to make that file?

**Comment by Mcat12** [comment]
By default there is no root password. Are you sure that it's not the Pi's password?

**Comment by jbukfan** [comment]
I get access denied when i try no PW or with pi's PW from Putty..

**Comment by Mcat12** [comment]
Can you get a screenshot/log of it?

**Comment by jbukfan** [comment]
![rasbpilogin](https://cloud.githubusercontent.com/assets/20271632/16566901/54548358-41de-11e6-944e-fa8e5091ce47.jpg)

**Comment by Mcat12** [comment]
You need to login as the `pi` user. Since root doesn't have a password you are unable to access it. You can just use `sudo` or `sudo su` to act as root if you need to, while still being the `pi` user.

**Comment by jbukfan** [comment]
I have been logging in as pi ... and my lack of unix knowledge is showing.  i couldn't do just su, as root prompted for a PW, so i did what you just said, sudo su, and it switched to root. GRrrr.. now i'll do what you asked above..

**Comment by jbukfan** [comment]
![phpinfo](https://cloud.githubusercontent.com/assets/20271632/16567123/c70e0da4-41e0-11e6-92c1-1758b5e40d58.jpg)

**Comment by Mcat12** [comment]
Are you running Raspbian Wheezy or Jessie?

**Comment by jbukfan** [comment]
I can't answer that honestly.. I just recall picking Debian when I first booted the Pi (a year or two ago) and have been using it to publish weather data before adding pi-hole.

**Comment by Mcat12** [comment]
Run `cat /etc/os-release` and check the first line.

**Comment by jbukfan** [comment]
root@buehrle-pi1:/var/www/html# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@buehrle-pi1:/var/www/html#

**Comment by Mcat12** [comment]
Ok. Wheezy is the older version of Raspbian (Debian really), and Jessie is the newer version. Wheezy doesn't support PHP 5.6 without going through something like https://www.dotdeb.org/. If you aren't too tied to this setup you can re-image your pi (or just make a new SD) with Jessie and put your stuff back on it; or you could try to use that dotdeb site to get PHP 5.6.

**Comment by Mcat12** [comment]
Looks like you just need to run these commands:
```
echo "deb http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list
echo "deb-src http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list
wget http://www.dotdeb.org/dotdeb.gpg -O- |apt-key add –
apt-get install php5-common php5-cgi php5
```

**Comment by Mcat12** [comment]
After running those, you can reboot the Pi or run:
```
sudo service lighttpd restart
```

**Comment by jbukfan** [comment]
is something missing at the end of this line?
wget http://www.dotdeb.org/dotdeb.gpg -O- |apt-key add –

**Comment by Mcat12** [comment]
I don't think so. Does it give an error?

**Comment by jbukfan** [comment]
root@buehrle-pi1:/# wget http://www.dotdeb.org/dotdeb.gpg -O- |apt-key add –
--2016-07-04 13:13:03--  http://www.dotdeb.org/dotdeb.gpg
Resolving www.dotdeb.org (www.dotdeb.org)... 195.154.242.153, 2001:bc8:21eb:100::1
Connecting to www.dotdeb.org (www.dotdeb.org)|195.154.242.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5299 (5.2K) [application/octet-stream]
Saving to: `STDOUT'

100%[====================================================================================================>] 5,299       --.-K/s   in 0s

2016-07-04 13:13:03 (34.6 MB/s) - written to stdout [5299/5299]

gpg: can't open `–': No such file or directory
root@buehrle-pi1:/#

**Comment by Mcat12** [comment]
That last dash looks like it's longer than the others... Try replacing it with a normal dash like the rest of them. (probably because I copied and pasted it)

**Comment by jbukfan** [comment]
ok.. was able to get through all of that .. installed dependencies and new php.. the phpinfo still shows the same version as it did before.  Also whitelist still failed. :(

**Comment by Mcat12** [comment]
Did you run `sudo service lighttpd restart`? If that doesn't work, reboot the pi.

**Comment by jbukfan** [comment]
i did.. even restarted the pi..

**Comment by jbukfan** [comment]
Actually it did change..  PHP Version 5.4.45-0+deb7u4 .. the u3 updated to u4 ...

**Comment by Mcat12** [comment]
Try `sudo apt-get install php5-fpm` and restart lighttpd.

**Comment by Mcat12** [comment]
Oh, did you run `apt-get update` after those first steps?

**Comment by Mcat12** [comment]
Forgot to mention that... If that wasn't run then that's why nothing really changed.

**Comment by Mcat12** [comment]
After that, run `apt-get install php5-common php5-cgi php5` again (plus restart lighttpd again).

**Comment by jbukfan** [comment]
ran apt-get update and got this.. 

Fetched 7,041 kB in 42s (167 kB/s)
W: Failed to fetch http://packages.dotdeb.org/dists/wheezy-php56/Release  Unable to find expected entry 'all/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@buehrle-pi1:/home/pi#

**Comment by jbukfan** [comment]
root@buehrle-pi1:/# apt-get install php5-common php5-cgi php5
Reading package lists... Done
Building dependency tree
Reading state information... Done
php5 is already the newest version.
php5-cgi is already the newest version.
php5-common is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.
root@buehrle-pi1:/#

**Comment by Mcat12** [comment]
Looks like that source doesn't include armhf builds (the pi is an ARM powered device, unlike x86 or 64bit devices).

**Comment by jbukfan** [comment]
Not sure what that really means to me.. So I need to re-image with Wheezy?

**Comment by Mcat12** [comment]
I'm checking for a php 5.6 armhf version, but if you re-image you'd re-image with Jessie

**Comment by Mcat12** [comment]
Run `sudo rm /etc/apt/sources.list.d/dotdeb.list` to stop that error from showing up when doing an update.

Follow these directions (taken from [here](http://stackoverflow.com/a/31342872)). This may take awhile, because we have to build PHP from source since there's no prebuilt armhf binaries provided for wheezy:
```
# Get the PHP source
# You can find the latest version number on the PHP download page: http://php.net/downloads.php
# Change `nl1` to your nearest mirror. Find the mirror list here: http://php.net/mirrors.php.
wget http://nl1.php.net/distributions/php-5.6.23.tar.bz2

# Unpack
tar -xvjf php-5.6.13.tar.bz2

cd php-5.6.13

sudo apt-get update
sudo apt-get install libxml2-dev
./configure

# If on the Raspberry Pi 2
make -j4
# Otherwise
make

sudo make install

# Reboot to make sure changes are effective
sudo reboot

# Check PHP version
php -v
```

**Comment by jbukfan** [comment]
sr/include -g -O2 -fvisibility=hidden  -c /php-5.6.23/ext/fileinfo/libmagic/fsmagic.c -o ext/fileinfo/libmagic/fsmagic.lo
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Makefile:630: recipe for target 'ext/fileinfo/libmagic/apprentice.lo' failed
make: *** [ext/fileinfo/libmagic/apprentice.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jbukfan** [comment]
ok i pulled down a new image of Jessie and setup a new SD card, reinstalled pi-hole and i can now add to whitelist .. now i just have to get my weather station back up and running.. 

Thanks for all the help..

**Comment by Mcat12** [comment]
It's too bad that wheezy doesn't have PHP 5.6. It's our pleasure to try and help you!

**Comment by jbukfan** [comment]
Well after all of that, my DirecTV app on my iPhone still won't work right, it will start to stream a show and then drop out and return to the menu.  It works fine on other wifi hotspots and over cellular data, but since i implemented pi-hole, it started failing.  I have used it for more than a year without this problem previously, and have added to the whitelist all sites that show up as pi-holed when i try to watch something.  Not sure what to do next.

**Comment by jbukfan** [comment]
OK FINALLY found the right domain to whitelist and it appears to have been resolved.. metrics.directv.com .. Grrr..  Thanks again for all the help.
