### ISSUE TITLE
Temperature keeps reverting to Celsius from Fahrenheit when updating

### ISSUE THREAD

**Issue by jedis00** [pi-hole/pi-hole#5552]
Temperature keeps reverting to Celsius from Fahrenheit when updating

**Comment by yubiuser** [comment]
You completely ignored the help template.

**Comment by jedis00** [comment]
There is nothing to fill out. Latest version, Fahrenheit is set. If you update it via ssh, it reverts back to Celsius. That's all a developer needs to fix it.

**Comment by jedis00** [comment]
@PromoFaux

**Comment by rdwebdesign** [comment]
This is not happening with other users, so if there is something really broken, we need to know exactly what is the issue, including your specific details.

Please follow the template, specially the debug log.

**Comment by PromoFaux** [comment]
As I've been tagged (I don't really know why) I'll reiterate...

"It's broken, fix it" is not nearly enough for us to go on. The template is there to help us help you, and to more easily diagnose the issue. As RD mentioned, we've not had any other reports of this, so this is likely a configuration issue. But I can only guess.

**Comment by jedis00** [comment]
It's happened across 2 different installs since 2018 and not with restoring a config. On a raspberry pi (raspbian), and in a VM (Debian 11) ... I've just become accustomed to updating it every time I login to the admin page after an update.

https://tricorder.pi-hole.net/fNRjaTMa/

**Comment by jedis00** [comment]
@PromoFaux Updated original post.

**Comment by jedis00** [comment]
@yubiuser Updated original post.

**Comment by PromoFaux** [comment]
Maybe a file permission issue - what is the output of `ls -lah /etc/pihole` please?

**Comment by PromoFaux** [comment]
Just checked against a known-working installed version, and permissions match.

Can you verify, do you currently have F set for temperatue unit in the web interface? If you do, please run a fresh debug token

**Comment by jedis00** [comment]
No, looks like it had reverted back to celsius again. Changed it back to fahrenheit and uploaded new log: https://tricorder.pi-hole.net/857sJbRh/

**Comment by jedis00** [comment]
@PromoFaux Hey, wondering if you had a chance to look at it, and if I need to refresh the debug token. Thanks!

**Comment by PromoFaux** [comment]
I've tried to reproduce this, but I cannot.  Note the value of `TEMPERATUREUNIT` in `setupVars.conf` before and after an update:

```
pi@raspberrypi:~ $ pihole -v
  Pi-hole version is v5.17.2 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.24 (Latest: v5.24)
pi@raspberrypi:~ $ cat /etc/pihole/setupVars.conf | grep TEMPERATURE
TEMPERATUREUNIT=F
pi@raspberrypi:~ $ pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     update available
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [i] Pi-hole core files out of date, updating local repo.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...HEAD is now at 19bfa08b Pi-hole core v5.17.3 (#5520)
  [✓] Update repo in /etc/.pihole

  [i] If you had made any changes in '/etc/.pihole/', they have been stashed using 'git stash'

[SNIP IRRELEVANT UPDATE OUTPUT]

  [✓] Update complete!

  Current Pi-hole version is v5.17.3
  Current web version is v5.21
  Current FTL version is v5.24
pi@raspberrypi:~ $ cat /etc/pihole/setupVars.conf | grep TEMPERATURE
TEMPERATUREUNIT=F
```

Do you have some sort of process that is restoring/overwriting the file `/etc/pihole/setupVars.conf`?

**Comment by jedis00** [comment]
@PromoFaux No. Vanilla install. Nothing special. How often does the process reread the config file for values to apply changes? Does it do it on a cadence or is it manually triggered by something?

**Comment by PromoFaux** [comment]
The only time the process is triggered is if you change the temperature in the dashboard... Maybe someone else has access to your dashboard and prefers to see Celsius. It's a global setting, not per-browser.

It can also be set with `pihole -a -c` (or `pihole -a -f`, or `pihole -a -k`), though this function only exists for the web interface to call when you set it in the web interface.

I've checked through the code, and there is no other path to setting this value. There is clearly something "other" about your install(s), but what - I cannot say. If it were a wider issue, we'd have heard _something_ by now.

V6 will change how these things are handled entirely. Maybe it's worth opting into the beta on one of your devices to see if you still have this issue. 

https://pi-hole.net/blog/2023/10/09/pi-hole-v6-beta-testing/

**Comment by jedis00** [comment]
Yeah, not sure. I don't login to look at it often. It reverted overnight, even without doing an update. I cloned the VM and had them both set as Fahrenheit. Only one reverted. Some kind of thing is triggering it, but it's a mystery. These were clean Debian 11 installs and only running the pi-hole installation. No other customizations done.

**Comment by OldGrumpyBear** [comment]
FYI, I am having the same issue.   Entering "pihole -a -f" doesn't work.   It's not a critical issue, but simply annoying.

**Comment by rdwebdesign** [comment]
@OldGrumpyBear 

In the issue reported above, the temperature unit is correctly set (and apparently all commands are working), but the temperature unit is lost **only when Pi-hole is updated** to a new version. 

> Entering "pihole -a -f" doesn't work. 

This is a completely different issue. 

Please, open a new issue **following the template**, or ask your questions at our [Discourse Forum](https://discourse.pi-hole.net/).

**Comment by OldGrumpyBear** [comment]
I checked the file /etc/pihole/setupVars.conf, and it has TEMPERATUREUNIT=F.   Yet on the GUI it keeps reverting back to Celsius.   I'm running pihole and gravity on a Ubuntu 23.10 system.

**Comment by jedis00** [comment]
> @OldGrumpyBear
> 
> In the issue reported above, the temperature unit is correctly set (and apparently all commands are working), but the temperature unit is lost **only when Pi-hole is updated** to a new version.
> 
> > Entering "pihole -a -f" doesn't work.
> 
> This is a completely different issue.
> 
> Please, open a new issue **following the template**, or ask your questions at our [Discourse Forum](https://discourse.pi-hole.net/).

It's actually doing it outside of updating now. Set to F and the next day, GUI shows C again.

**Comment by OldGrumpyBear** [comment]
> @OldGrumpyBear
> 
> In the issue reported above, the temperature unit is correctly set (and apparently all commands are working), but the temperature unit is lost **only when Pi-hole is updated** to a new version.
> 
> > Entering "pihole -a -f" doesn't work.
> 
> This is a completely different issue.
> 
> Please, open a new issue **following the template**, or ask your questions at our [Discourse Forum](https://discourse.pi-hole.net/).

If you re-read the thread, the issue continously occurs, not "only when pihole is updated."

**Comment by PromoFaux** [comment]
I'm still able to reproduce this. Were you able to test against V6? Maybe on another device if you're not ready to jump into the beta

**Comment by OldGrumpyBear** [comment]
I have three instances of pi-hole running.   One on a dedicated Raspberry Pi 4, and two as VMs.   All three instances does the same thing.  All are the latest of version 5.   I can upgrade one of the VMs to version 6 .... once I refresh my memory on how to do that.

**Comment by OldGrumpyBear** [comment]
I have three instances of pi-hole running.   One on a dedicated Raspberry Pi 4, and two as VMs.   All three instances does the same thing.  All are the latest of version 5.   I can upgrade one of the VMs to version 6 .... once I refresh my memory on how to do that.

**Comment by jedis00** [comment]
> I have three instances of pi-hole running. One on a dedicated Raspberry Pi 4, and two as VMs. All three instances does the same thing. All are the latest of version 5. I can upgrade one of the VMs to version 6 .... once I refresh my memory on how to do that.

Did updating work?
