### ISSUE TITLE
Ads Not Blocking Properly in Pi-hole Docker 

### ISSUE THREAD

**Issue by touhamii** [pi-hole/pi-hole#5553]
### Versions

  Pi-hole version is v5.17.3 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.24 (Latest: v5.24)

### Platform

- Platform:  Docker

Issue:
Ads are not consistently being blocked as expected in my Pi-hole Docker setup. After restarting Docker or my PC, the blocking functionality becomes random. Even after re-downloading Pi-hole, the problem persists.

Expected Behavior:
Consistent ad blocking, with domains and ads disappearing as intended.

Note:
No changes were made to settings; the issue started without any modifications made by me. I only restarted my PC.

**Comment by rdwebdesign** [comment]
Please, post the compose file or `docker run` command used to start the container.

Also, generate a debug log and post here **only the Token**.

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by touhamii** [comment]
1/ docker run : 


docker run --hostname=d76b0dc50f41 --mac-address=02:42:ac:11:00:02 --env=PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=phpver=php --env=PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log --env=IPv6=True --env=S6_KEEP_ENV=1 --env=S6_BEHAVIOUR_IF_STAGE2_FAILS=2 --env=S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 --env=FTLCONF_LOCAL_IPV4=0.0.0.0 --env=FTL_CMD=no-daemon --env=DNSMASQ_USER=pihole -p 53:53 -p 53:53/udp -p 67:67/udp -p 80:80 --label='org.opencontainers.image.created=2024-01-07T08:10:27.389Z' --label='org.opencontainers.image.description=Pi-hole in a docker container' --label='org.opencontainers.image.licenses=NOASSERTION' --label='org.opencontainers.image.revision=184b8bbedcbf308a1777ed653f4a7cbc5885358d' --label='org.opencontainers.image.source=https://github.com/pi-hole/docker-pi-hole' --label='org.opencontainers.image.title=docker-pi-hole' --label='org.opencontainers.image.url=https://github.com/pi-hole/docker-pi-hole' --label='org.opencontainers.image.version=2024.01.0' --runtime=runc -d pihole/pihole:latest
___________________________________________

2/  
[✓] Your debug token is: https://tricorder.pi-hole.net/n1NqmaUX/

**Comment by touhamii** [comment]
Observations:

The number of blocked queries increases when visiting sites with ads (e.g., cnn.com).
However, certain ads, such as the large one at the top (see attached picture), do not disappear.
This issue is specific to Windows 10 + Docker; on my MX Linux distro, Pi-hole functions correctly.

Picture 1: Before navigating to cnn.com
![Before navigating to cnn com on my win10 Docker Pihole](https://github.com/pi-hole/pi-hole/assets/30718879/4ce644d9-98d2-402e-be61-8745671e7787)
Picture 2 : After 
![After](https://github.com/pi-hole/pi-hole/assets/30718879/fe1bd14d-13e5-4af8-997f-65d2863b2baf)

**Comment by DarrenRainey** [comment]
Just to confirm ad's are being blocked on other devices fine (Your Linux distro) but not windows 10?

Can you check that you only have 1 DNS entry set and that it points to your pi-hole. I had a similar issue where I had the pi-hole set as my main dns server and cloudflare dns set as the alternate DNS in windows.

On your windows machine run ipconfig /all and post the output here to confirm.

**Comment by touhamii** [comment]
thank you for your answer 
i actually found the solution and forgot to close this 
the solution is that after i unistalled docker and lost hope i decided to give it one last chance and i downloaded pihole again im not sure if it's the same version here it is : 
https://i.imgur.com/QIyTjZf.png
what i rly wanted to block is the ads on some Games and i can see that if i dont unirely close the game before setting up dns on phone it will not work i think that's what happend at first i should have closed the game before setting up the dns for it to work or maybe this version of pi-hole is better it's one of the two

**Comment by rdwebdesign** [comment]
@touhamii 

Apparently you are using the `nightly` image.

Just be careful, because this uses development branches for all 3 components (Pi-hole core, web interface and FTL) and it can have recent changes still in test.
This is usually safe, but in rare cases it will brake your install.

You can use the most recent tag: `2024.02.0`.
