### ISSUE TITLE
(development-v6) cannot update FTL on amd64 device

### ISSUE THREAD

**Issue by GerdRuetten** [pi-hole/pi-hole#5562]
### Versions

Core
    Version is v5.17.1-269-gcc8f9fe0 (Latest: null)
    Branch is development-v6
    Hash is cc8f9fe0 (Latest: 9a3affd8)
Web
    Version is v5.19-653-g1dcf90bd (Latest: null)
    Branch is development-v6
    Hash is 1dcf90bd (Latest: 1dcf90bd)
FTL
    Version is vDev-ce4407b (Latest: null)
    Branch is development-v6
    Hash is ce4407b5 (Latest: ce4407b5)

### Platform
Linux ProxmoxCT-pihole 5.15.131-2-pve #1 SMP PVE 5.15.131-3 (2023-12-01T13:42Z) x86_64 GNU/Linux
Proxmox LXC-Container
### Expected behavior

Update the dev-v6 broken with:

  curl: (7) Failed to connect to ftl.pi-hole.net port 443: Verbindungsaufbau abgelehnt
...
  [✗] Downloading and Installing FTL
   Error: URL https://ftl.pi-hole.net/development-v6/pihole-FTL-amd64 not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

## Debug Token

https://tricorder.pi-hole.net/bg9cEl0n/

### Additional context

Using pi-hole with unbound

**Comment by rizlah** [comment]
I am having this issue as well

**Comment by nicoloma89** [comment]
me too

**Comment by PromoFaux** [comment]
Rebooted the binary storage server - seems to have fixed it. Thanks for the report!
