### ISSUE TITLE
Intermittent issues using custom dns_records

### ISSUE THREAD

**Issue by cruzzoe** [pi-hole/pi-hole#5564]
### Versions

  Pi-hole version is v5.17.2 (Latest: N/A)
  web version is v5.21 (Latest: N/A)
  FTL version is v5.23 (Latest: N/A)

### Platform
OS and version:  "Debian GNU/Linux 11 (bullseye)"
Platform:  Raspberry Pi

### Expected behavior

On pihole I use the feature under /dns_records.php.
 I use this to create custom domains e.g myprinter.com  to resolve to the IP of my printer and so on.

This works nicely 80% of the time i.e I can access port 80 on myprinter.com.
this is just an example but you get the idea of what I am using this for.

### Actual behavior / bug

There are times where the dns doesnt resolve as expected. It doesnt matter what browser I use. I see in my browser: 

Hmm. We’re having trouble finding that site.We can’t connect to the server at xxx"

I can't predict when this will happen. My workaround is to stop using the custom domain and instead use the static IP. This workaround is fine, but its frustrating. It will the resolve itself later on in the day, but for a short period (maybe some hours) I am forced to use the IP address to access.

### Steps to reproduce

1. Set a custom domain on the pihole under /dns_records.php e.g myprinter.com --> 192.168.1.8
 2. Go to myprinter.com

Sometimes it works and sometimes it doesnt. !

## Debug Token

- URL:  

I tried to upload the log but got the following error:

[?] Would you like to upload the log? [y/N] y
    * Using curl for transmission.
    * curl failed, contact Pi-hole support for assistance.
    * Error message: curl: (6) Could not resolve host: tricorder.pi-hole.net

**Comment by yubiuser** [comment]
If it works 80% of the time and only fails unpredictably it sounds a bit like Pi-hole is not the only upstream of you clients and they choose the other DNS server at random times.

**Comment by cruzzoe** [comment]
I see. Next time this happens, I'll double check what my dns is. Actually iirc rebooting my router may have fixed this last time which indicates it's not pihole.
