### ISSUE TITLE
Update of pi-hole not possible on Linuxmint 6 (Debian)

### ISSUE THREAD

**Issue by Jambola77** [pi-hole/pi-hole#5575]
### Versions

Pi-hole version is v5.17.3 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.24 (Latest: v5.25)

### Platform

- OS and version:  

- Platform:  Linuxmint 6 (Debian Edition) LMDE

$ uname -a
Linux vmmint 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Expected behavior

I tried to "pi-hole -up" and was expecting that the update runs flawlessly.

### Actual behavior / bug

After pi-hole -up I got the following message:
"Unsupported OS detected: Linuxmint 6"

### Steps to reproduce

pi-hole -up 

## Debug Token

- URL:  

### Screenshots
[✗] **Unsupported OS detected: Linuxmint 6**
      If you are seeing this message and you do have a supported OS, please contact support.

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

  **Unable to complete update, please contact Pi-hole Support**

### Additional context

none

**Comment by rdwebdesign** [comment]
This is the expected behavior when using an unsupported OS, but there is a simple solution:

You can try to update using the command:

```
sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
```

**Note:**
This command is in the text you posted above.

It is possible that the installation will still fail at this stage due to an unsupported configuration.
If that is the case, please ask the community on Discourse with the Community Help category:
https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

**Comment by Jambola77** [comment]
Oh yes, I see. And it works very well.
You can add this distribution to your supported OS. Everythings works fine.
