### ISSUE TITLE
pihole -v shows update available but pihole -up doesn't

### ISSUE THREAD

**Issue by jamieburchell** [pi-hole/pi-hole#5576]
### Versions

- Pi-hole:  5.17.3
- AdminLTE:  5.21
- FTL:  5.24

### Platform

- OS and version:  Rasbian 12 Bookworm

- Platform:  Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

Pihole should update if an update is available

### Actual behavior / bug

_A clear and concise description of what the bug is._

```
jamie@homebridge:~ $ sudo pihole -v
  Pi-hole version is v5.17.3 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.24 (Latest: v5.25)
jamie@homebridge:~ $ sudo pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 8.2.7
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

```

### Steps to reproduce

1. `pihole -u`

## Debug Token

- URL:  https://tricorder.pi-hole.net/IaaNDxfE/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by Jeetah** [comment]
Same here since a few weeks:

`pihole -v
  Pi-hole version is v5.14.2 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)
  `

This is the output **after** running pihole -up

**Debug Token: ** https://tricorder.pi-hole.net/fDJh2Sqd/

**Comment by jamieburchell** [comment]
I was able to "resolve" it by rebooting the Pi. Restarting the DNS service made no difference.

**Comment by rdwebdesign** [comment]
@Jeetah 

You debug log shows you are running Pi-hole core v5.17.3, but the `/etc/pihole/versions` file shows an older version:
```
   CORE_VERSION=v5.14.2
   CORE_BRANCH=master
   CORE_HASH=19bfa08b
   GITHUB_CORE_VERSION=v5.17.3
   GITHUB_CORE_HASH=19bfa08
```

Please run `pihole updatechecker` and try again.
Do you see any difference?

**Comment by Jeetah** [comment]
Tried _updatechecker_ already. Also reboot. Without any success or change in pihole -v output or update behavior.

But _/etc/pihole/versions_ contained **a lot of** `^@`s before the CORE_VERSION variable. Deleted those and corrected the version to the same as the GITHUB_CORE_VERSION. Now waiting if this works on next update.

**Comment by rdwebdesign** [comment]
> But _/etc/pihole/versions_ contained a lot of `^@`s before the CORE_VERSION variable. 

Apparently the issue was some kind of file corruption in `/etc/pihole/versions`.

The update process worked as expected (`v5.17.3` was actually installed), but when the function tried to update the versions file, it never found `CORE_VERSION` variable.

There was a different string (like `^@^@^@^@^@^@^@^@^@^@^@^@CORE_VERSION`).
The new version number was never saved to this file, causing the wrong message.
