### ISSUE TITLE
Default list author fine with breaking functionality -- suggest finding alternative

### ISSUE THREAD

**Issue by mdstricklin** [pi-hole/pi-hole#5577]
### Versions

- Pi-hole:  all

### Platform

- OS and version:  all

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

Login through Discord occurs without issue.

### Actual behavior / bug

_A clear and concise description of what the bug is._

Logging in through Discord breaks at the verification step, due to their login server being blacklisted by the default ad list.

Tracing the issue back to root cause shows that the repo owner for the default blocklist has different priorities than PiHole users:
"It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety."

StevenBlack appears to be be focused on eliminating tracking regardless of the unintended consequences, while most PiHole users choose PiHole to block ads and expect other aspects of their lives to continue normally. It sounds like it's time to choose a new default list to ship with PiHole installs.

### Additional context

_Add any other context about the problem here._
StevenBlack suggested bringing the issue here, so I am:
https://github.com/StevenBlack/hosts/issues/2574

**Comment by jfb-pihole** [comment]
This is not a bug.  The adlist has a domain blocked, and you don't agree that the domain should be blocked. 

Options:

1.  Whitelist the domain, which will make it immune from all future blocking.
2. Remove this adlist from your Pi-hole install and replace it with a list of your choosing.

**Comment by mdstricklin** [comment]
Well, yeah. Obviously I've done those steps. You're right this isn't really a bug, but after tracing down the issue and finding out the situation, I figured it was worth noting and I didn't see a "questionable design decisions" button, so here we are.

Just so it's clearly stated, my issue is not, "The adlist has a domain blocked, and [I] don't agree that the domain should be blocked." My issue is that a project that describes itself as "Network-wide Ad Blocking" has chosen to use a third-party list that is not centered around Ad Blocking. Per the owner's own description, "We serve people who don't want to be tracked. That's our mission, and those are our people."

Seems like **it would be wise to update the default adlist shipped with the software to be an adlist, not a tracker list.**

**Comment by jfb-pihole** [comment]
We have been using this list for many years (at least seven, to my recollection).

Some related discussion on the topic of provided optional lists on install:

https://github.com/pi-hole/pi-hole/pull/3236

https://github.com/pi-hole/pi-hole/pull/3937
