### ISSUE TITLE
Consider NOT rate-limiting queries from the local router 

### ISSUE THREAD

**Issue by mgogulapati** [pi-hole/pi-hole#5586]
### Versions
  Pi-hole version is v5.17.3 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)

### Platform
- OS and version:  Raspbian GNU/Linux 11 (bullseye)
- Platform:  Raspberry Pi 400 Rev 1.1

### Configuration 
_ Pi-hole's IP address is configured as the ONLY DNS server in the router/gateway_

### Expected behavior
_DNS quires to pi-hole from the local DNS server of the network need not be considered for rate limiting._

### Actual behavior / bug
_While considering rate-limiting per client basis on the local networks, the local router/gateway is also being rate-limited, when it is forwarding all received DNS queries to the pi-hole for resolution.  
Consider NOT rate-limiting the gateway's DNS queries _

### Steps to reproduce

1.  Install pi-hole with static local IP address (192.168.192.3) 
2.  Configure pi-hole as the DNS server on the router (192.168.192.1) 
3.  Allow the local clients to generate requests (There are about 40+ clients on my network)
4.  The problem happens, when there is sudden surge of the network traffic.  

## Debug Token

- URL:  https://tricorder.pi-hole.net/vOrFBiRh/

### Screenshots

_![Screenshot-1](https://github.com/pi-hole/pi-hole/assets/48071228/37a52aa8-2ea2-4bde-92ad-8b25d1c4784e)_

### Additional context

_Add any other context about the problem here._

**Comment by mgogulapati** [comment]
I have about 40 devices in my home network and i see this message almost everyday.  Please let me know, if you need any other information related to this.

**Comment by PromoFaux** [comment]
Is it not possible in your router to set the DNS server for the clients to Pi-hole via DHCP?

That way all clients would directly query the Pi-hole rather than the router, which then forwards the requests to the Pi-hole.

Rate limiting is also configurable: https://docs.pi-hole.net/ftldns/configfile/#rate_limit

**Comment by mgogulapati** [comment]
Rate-limiting is caused due to repeated forwarding loop of in-addr.arpa address requests to the requester (DHCP gateway).  

I reproduced the error and found the rate-limiting is caused due to the same in-addr.arpa address request between pihole and the requester (DHCP gateway). This configuration error will eventually cause failures for the legitimate DNS lookups from the other devices using the gateway. 

Is it possible to enhance the pihole eliminating forwarding the same DNS request back to the requester? 


——  Start of Pihole.log — 

Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: forwarded lb._dns-sd._udp.0.192.168.192.in-addr.arpa to 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: query[PTR] lb._dns-sd._udp.0.192.168.192.in-addr.arpa from 192.168.192.1
Sep 19 05:11:31 dnsmasq[2296491]: config error is REFUSED (EDE: blocked)
Sep 19 05:11:31 dnsmasq[2296491]: Rate-limiting lb._dns-sd._udp.0.192.168.192.in-addr.arpa is REFUSED (EDE: blocked)
Sep 19 05:11:31 dnsmasq[2296491]: reply error is REFUSED
Sep 19 05:11:42 dnsmasq[2296491]: query[A] logsink.devices.nest.com from 192.168.192.1
Sep 19 05:11:42 dnsmasq[2296491]: config error is REFUSED (EDE: blocked)
Sep 19 05:11:42 dnsmasq[2296491]: Rate-limiting logsink.devices.nest.com is REFUSED (EDE: blocked)
Sep 19 05:11:42 dnsmasq[2296491]: query[A] logsink.devices.nest.com from 192.168.192.1
Sep 19 05:11:42 dnsmasq[2296491]: config error is REFUSED (EDE: blocked)
Sep 19 05:11:42 dnsmasq[2296491]: Rate-limiting logsink.devices.nest.com is REFUSED (EDE: blocked)
Sep 19 05:11:42 dnsmasq[2296491]: query[A] weather.nest.com from 192.168.192.1
Sep 19 05:11:42 dnsmasq[2296491]: config error is REFUSED (EDE: blocked)
Sep 19 05:11:42 dnsmasq[2296491]: Rate-limiting weather.nest.com is REFUSED (EDE: blocked)

—— End of pihole.log —

**Comment by mgogulapati** [comment]
[✓] Your debug token is: https://tricorder.pi-hole.net/GxSeklkU/
[i] Logs are deleted 48 hours after upload.

**Comment by Bucking-Horn** [comment]
@mgogulapati 

> Rate-limiting is caused due to repeated forwarding loop of in-addr.arpa address requests to the requester (DHCP gateway).


That would demonstrate that you've configured a DNS loop, making this a configuration issue rather than a bug.

If you need assistance with that, open a topic over at https://discourse.pi-hole.net.

**Comment by S2ciOnur** [comment]
I solved it by adding more specific hostnames to my running containers and also added the hostnames.to the API URIs I'm calling.
