### ISSUE TITLE
pihole -up Banana Pi M1 not working

### ISSUE THREAD

**Issue by ApophysX** [pi-hole/pi-hole#5596]
### Versions
- Pi-hole: v5.17.2 · [Update available!]
- AdminLTE:  v5.21]
- FTL:  v5.23 · [Update available!]

### Platform
- OS and version:  Armbian 23.11.1 Jammy with bleeding edge Linux 6.4.12-edge-sunxi
- Platform:  Banana PI M1

### Expected behavior

Update available!: i type pihole -up

### Actual behavior / bug

 [✗] Update local cache of available packages
   Error: Unable to update package cache. Please try "sudo apt update"

**Comment by para-do-x** [comment]
Hello ApophysX, 

this part of Pi-hole update checks, if the apt package management from your OS (Armbian) is up to date.
What did you get, when you run "sudo apt update"? Is this working? 
You need to fix this first, before you can update Pi-hole.

Br,

Para-do-x

**Comment by ApophysX** [comment]
> Hello ApophysX,
> 
> this part of Pi-hole update checks, if the apt package management from your OS (Armbian) is up to date. What did you get, when you run "sudo apt update"? Is this working? You need to fix this first, before you can update Pi-hole.
> 
> Br,
> 
> Para-do-x

Hello para-do-x,

yes sudo apt update is working:
root@bananapi:~# sudo apt update
Hit:1 http://ports.ubuntu.com jammy InRelease
Get:2 http://ports.ubuntu.com jammy-security InRelease [110 kB]
Get:3 http://ports.ubuntu.com jammy-updates InRelease [119 kB]
Hit:4 http://ports.ubuntu.com jammy-backports InRelease
Hit:6 http://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy InRelease
Hit:7 http://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease
Get:8 http://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu jammy InRelease [23.9 kB]
Hit:9 http://deb.volian.org/volian scar InRelease
Get:11 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease [2,115 B]
Ign:12 https://download.docker.com/linux/debian jammy InRelease
Hit:13 https://download.docker.com/linux/ubuntu jammy InRelease
Err:14 https://download.docker.com/linux/debian jammy Release
  404  Not Found [IP: 18.155.145.73 443]
Get:5 http://mirrors.netix.net/armbian/apt jammy InRelease [52.5 kB]
Hit:10 https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium InRelease
Get:15 http://ports.ubuntu.com jammy-updates/main armhf Packages [984 kB]
Get:16 https://itai-nelken.github.io/weekly-box86-debs/debian  Packages [19.5 kB]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@bananapi:~# pihole -up
  [✗] Update local cache of available packages
   Error: Unable to update package cache. Please try "sudo apt update"
root@bananapi:~#
