### ISSUE TITLE
OS Detection saying supported OS is not Supported

### ISSUE THREAD

**Issue by rjhancock** [pi-hole/pi-hole#5599]
### Versions

  Pi-hole version is v5.17.3 (Latest: v5.17.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25 (Latest: v5.25.1)

### Platform
- OS and version:  Ubuntu 22.04
- Platform: Old intel desktop

### Expected behavior

That running `pihole -up will update the software`

### Actual behavior / bug

Process stop claiming the OS is supported when it is marked as being supported on the main page. Maybe the issue is the point version?

```
Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

  System information as of Sun Mar  3 12:29:37 PM UTC 2024
```

```
  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✗] Unsupported OS detected: Ubuntu 22.04
      If you are seeing this message and you do have a supported OS, please contact support.

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


  Unable to complete update, please contact Pi-hole Support
```

**Comment by PromoFaux** [comment]
What is the output of `cat /etc/os-release` on that machine, please?

**Comment by rjhancock** [comment]
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by PromoFaux** [comment]
That's really strange, I can't see any reason why it would be failing that check - unless maybe.....

Can you run `dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net` please and post the results

**Comment by rjhancock** [comment]
```
rjhancock@runner-alt:~$ dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
;; communications error to 2600:9000:5301:9700::1#53: timed out
;; communications error to 2600:9000:5301:9700::1#53: timed out
;; communications error to 2600:9000:5301:9700::1#53: timed out
"Raspbian=10,11,12 Ubuntu=20,22,23 Debian=10,11,12 Fedora=36,37,38 CentOS=8,9"
rjhancock@runner-alt:~$ 
```

**Comment by PromoFaux** [comment]
OK those first three lines will stop it. The expected result is just the `Raspbian=` etc etc.

Seems like you may have a network configuration issue somewhere along the line that is timing out/restricting lookups via ns1.pi-hole.net

**Comment by rjhancock** [comment]
Odd. Shouldn't be an issue as all other things are working fine, it is ONLY when running the `pihole -up` command that this occurs.

Will double check things when I get home. The only thing that has really changed on the network is I turned the AT&T router into IP Passthrough mode so that might be causing issues for some reason.

**Comment by PromoFaux** [comment]
You may want to check your IPv6 configuration - it looks like that is what is timing out, and then `dig` is falling back to IPv4 after three attempts.

**Comment by PromoFaux** [comment]
Something that might "fix" it is this PR: https://github.com/pi-hole/pi-hole/pull/5399

You can try it locally with `pihole checkout core cdouble_dig_v5`

**Comment by rjhancock** [comment]
Network config issue. AT&T Router in IP Passthrough mode was the issue. I disabled that, and it started working again.

**Comment by gautamsamyak** [comment]
Run: nmcli con show 'Wired Connection 1'
this should be ipv4.method same as ipv6.method

if you are sharing the internet from wifi to ethernet then it's like
ipv6.method: shared  
ipv4.method: shared
