### ISSUE TITLE
Information: Running Tor relay on a pi-hole setup

### ISSUE THREAD

**Issue by suedi** [pi-hole/pi-hole#560]
Is it possible to run a Tor relay on a pi-hole setup?

**Comment by dan019** [comment]
Which RPi version?

**Comment by suedi** [comment]
Not bought yet so I guess the latest

**Comment by dschaper** [comment]
I can't think of anything that would prevent the use of Tor on a Pi with the Pi-Hole installed. And even if there were sites blocked, I'd think we could find a solution that would whitelist any needed lookups? Is there a tutorial that you have in mind that you'd like to follow? We could take a look and see if we can get one set up and running before you make the purchase.

**Comment by suedi** [comment]
I don't know of any special tutorial but had a notion that It would be the best place to have a 
tor relay running in my local network. 

I read about a guy running Devuan + Pi-Hole on a Pi so I wanted to do that combo.

I will check if I can find a tutorial for Debian regarding tor, it should be basically the same for Devuan.

**Comment by suedi** [comment]
Bought a rpi3 now and installed devuan.

Will report how progress goes although I am in shortage of time right now.

**Comment by suedi** [comment]
Now pi-hole installed on my devuan rpi3

Will soon try to add tor

**Comment by RanaInside** [comment]
I have tor relay running on pi3 with piHole (and samba); no issues at all

**Comment by Mcat12** [comment]
Closing this, since it seems that everything's working fine. It will be reopened if any issues arise.
