### ISSUE TITLE
Query Log Ajax Error

### ISSUE THREAD

**Issue by iLlama** [pi-hole/pi-hole#561]
Expected Behavior: Show Query Log info on Admin Page

Actual Behavior: Receive error DataTables warning: table id=all-queries - Ajax error

Steps to reproduce this issue: Clicking Query Log 

All of the main page graphs seems to be working fine, though loading is quiet slow. 

Seen the /var/log/lighttpd/error.log asked for in other threads I looked at so here is that as well - http://pastebin.com/yNkxRaGA

**Comment by iLlama** [comment]
Also noticing thet

**Comment by Mcat12** [comment]
Run `pihole -d` and pastebin the log it creates as well. It looks like you might have a big log file. One of the reasons we're working on a rewrite is so that a big log file doesn't slow down the web interface.

**Comment by iLlama** [comment]
Here is the log - http://pastebin.com/N1hLfG70

Not sure if its worth mentioning that I have only been using pi-hole for a few days. #

**Comment by Mcat12** [comment]
If you run `pihole -f`, wait a min or so, and then check the web interface, what are the stats? Does everything load correctly?

**Comment by iLlama** [comment]
Well, I wanted to wait a day before I said anything, but it seems the issue went away on its own.

**Comment by Mcat12** [comment]
The issue most likely was that there were so many queries logged at that point that the pi was unable to handle so many. It fixed itself because every night the log is flushed.

**Comment by iLlama** [comment]
I guess that makes sense then. I noticed this issue on days that my family would be home and surfing all day. The last two days we have been at work and school etc. 

Is this something I should keep an eye on this weekend I guess? What should I do if it happens again? Can I increase the log size or flush the log manually?

Thanks

**Comment by Mcat12** [comment]
Having a large log will only affect the web interface, so unless that's critical for you it is not too important. Running `pihole -f` will flush the log, letting you view the web interface stats (although there won't be many queries shown since it was just flushed).

**Comment by PromoFaux** [comment]
Reopened on the AdminLTE repo on the above link.
