### ISSUE TITLE
fails to install in nobara linux(fedora 39)

### ISSUE THREAD

**Issue by kevin01523** [pi-hole/pi-hole#5614]
### Versions

- Pi-hole:  n/a
- AdminLTE:  n/a
- FTL:  n/a

### Platform

- OS and version:  
NAME="Nobara Linux"
VERSION="39 (KDE Plasma)"

- Platform:  Baremetal

### Expected behavior
pihole installs successfully

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
`curl -sSL https://install.pi-hole.net | sudo bash
[sudo] password for sette: 

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Default SELinux: disabled
  [✓] Current SELinux: disabled
  [i] Enabling EPEL package repository (https://fedoraproject.org/wiki/EPEL)
expressvpn                                                                                                                                                          614  B/s | 833  B     00:01    
[MIRROR] epel-release-latest-39.noarch.rpm: Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)                                        
[MIRROR] epel-release-latest-39.noarch.rpm: Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)                                        
[MIRROR] epel-release-latest-39.noarch.rpm: Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)                                        
[MIRROR] epel-release-latest-39.noarch.rpm: Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)                                        
[FAILED] epel-release-latest-39.noarch.rpm: Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)                                        
Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-39.noarch.rpm (IP: 38.145.60.23)
`

_A clear and concise description of what the bug is._

### Steps to reproduce

run the install script on terminal
curl -sSL https://install.pi-hole.net | sudo bash

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._
![image](https://github.com/pi-hole/pi-hole/assets/8380242/ae9e48dd-70b3-4757-8448-e39197ab0733)

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
This is an OS level issue.

The message is saying Fedora server is answering with error 404 (not found).

**Comment by bcambl** [comment]
Oops, I have a typo in that command. Update `nobora`  -> `nobara`.
My apologies, I will update it in my above comment for future users.
