### ISSUE TITLE
How Does It Work? - Watch the 60-second video below to get a quick overview

### ISSUE THREAD

**Issue by Sopor-** [pi-hole/pi-hole#562]
I only want to tell you that the video for "How Does It Work? - Watch the 60-second video below to get a quick overview" doesn't exist anymore. Maybe you should remove it or add a new one?

**Comment by PromoFaux** [comment]
Ah. We have a new one on our YouTube channel, it may just be that we need to update the link.

We had to remove the logo as it was in breach ornthe Raspberry Pi Foundation's trademark.

Thanks for pointing it out!

**Comment by PromoFaux** [comment]
fixed in 412c0a1
