### ISSUE TITLE
Using "IP/admin" page for admin interface returns a blank/clear/white page.

### ISSUE THREAD

**Issue by ILudw1g** [pi-hole/pi-hole#5628]
### Versions

  Pi-hole version is v5.17.3 (Latest: v5.18.1)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)

### Platform

- OS and version:  Debian GNU/Linux 12 (bookworm) aarch64

- Platform:  RPi5

### Expected behavior

Admin interface to open with login prompt, like normal.

### Actual behavior / bug

A white blank clear page opens instead. 

But if I use pi.hole/admin instead, all is good. 

Although using the "IP/admin" works on incognito mode on the same device, as well as normal browsing windows on other devices such as phone.

### Steps to reproduce

1. Go to "IP/admin"
3. See bug

## Debug Token

- URL:  

### Screenshots

Attached.
Normal browsing using IP:
![image](https://github.com/pi-hole/pi-hole/assets/110345581/e8634460-0a92-4e82-bf63-b7ec83d528b5)

Same browser and device, but incognito:
![image](https://github.com/pi-hole/pi-hole/assets/110345581/96f6189d-6037-43d0-99dd-6aaf544077c7)

### Additional context

I have already tried clearning all my cache. Again, works on different devices and browsers.

**Comment by rdwebdesign** [comment]
Did you try to clear cache and cookies?

If you are still unable to connect after clearing cookies and cache, please post a debug log _(run `pihole -d` on the command line, upload it and post here **only the Token**)_.
