### ISSUE TITLE
Teleporter does not restore DHCP server enabled state

### ISSUE THREAD

**Issue by PurryPlatypus** [pi-hole/pi-hole#5632]
### Versions

`pihole -v` on the backup export PiHole
```
  Pi-hole version is v5.17.3 (Latest: v5.18.2)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)
```
`pihole -v` on the restore target PiHole
```
  Pi-hole version is v5.18.2 (Latest: v5.18.2)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.1)
```

### Platform

- OS and version: Armbian/Jammy (Ubuntu)
- Platform:  BananaPi M2 Zero ARM SBC
- OS and version:  Ubuntu 23.10 (fresh install, using the server ISO)
- Platform:  Wyse 3040 / Intel Atom x5-Z8350 / x86-64

### Expected behavior

_I expected Teleporter to restore the previous state of my PiHole configuration, at the creation time of the backup file._

### Actual behavior / bug

_Teleporter did not restore the `enabled` state of the DHCP server._

### Steps to reproduce

1. have an existing PiHole, running on Armbian / BananaPi M2 Zero ARM SBC
2. install Ubuntu 23.10 Server on a Wyse 3040 x86-64 thin client, with the intent to use this box as the PiHole
3. export the PiHole backup from the BananaPi, using Teleporter
4. import/restore the backup on the Wyse into a fresh install of PiHole, using  Teleporter
5. (i might've rebooted the Wyse after restoring, i'm not quite sure)
6. notice the DHCP server remained _un-_`enabled`
7. after manually enabling the DHCP server, the enabled state remains after rebooting the Wyse

Considering that people who integrate a PiHole into a/their network, usually know what they're doing, i don't think that leaving the DHCP server disabled was a deliberate choice. Please export/backup and import/restore the DHCP server enabled state via Teleporter.

**Comment by jsolisu** [comment]
Confirmed.

**Comment by PurryPlatypus** [comment]
should i interact with an issue, when the bot announces auto-closure?

**Comment by jsolisu** [comment]
The problem persists

**Comment by yubiuser** [comment]
This is fixed in Pi-hole v6
