### ISSUE TITLE
Youtube history not updating when using pi.hole

### ISSUE THREAD

**Issue by kefir-** [pi-hole/pi-hole#5636]
### Versions
I'm not at the location running pi.hole at the moment, but I installed around 3 months ago, and updated to latest version a few days ago. I've only recently discovered this issue, but it seems to be easily reproducible.

### Platform

- OS and version:  Debian 12

- Platform:  Mac Mini 

### Expected behavior

I expect youtube to update my history when I've watched a video. 

### Actual behavior / bug

When using an updated youtube app on an updated android phone, on a network with an updated pi.hole enabled, the videos I watch do not appear in my watch history. If I switch from wifi to mobile network, the history immediately works as expected. 

This only happens in the app, watching youtube in the browser updates the history as expected. I've not tested apps on other platforms yet. 

### Steps to reproduce

1. Use youtube app on android phone to watch videos while logged on to youtube
3. Click on your profile and then your view history
4. Notice that recently viewed videos are missing from history

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
This is not a bug, rather you probably have s.youtube.com or video-stats.l.google.com on one of your blockists

https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212#youtube-history-3

Add these to your whitelist and it should start working again :)

**Comment by kefir-** [comment]
Thanks!!
