### ISSUE TITLE
No Blocked Page?

### ISSUE THREAD

**Issue by AtomicLaser** [pi-hole/pi-hole#564]
##### Expected Behaviour:
When visiting a filtered/blocked site, I.e http://www.googleadservices.com should get a page stating "Blocked by Pi-Hole!"

##### Actual Behaviour:
Shows a DNS error from browser:

Chrome:

> This site can’t be reached
> www.googleadservices.com’s server DNS address could not be found.

Safari:

> Safari Can't Find the Server
> Safari can't open the page "http://www.googleadservices.com" because Safari can't find the server "http://www.googleadservices.com".

##### Steps to reproduce this issue:
visit http://www.googleadservices.com or any blocked site

**Comment by dschaper** [comment]
That's actually the page that Google is returning. It's not really a DNS error, if you look at the Page Source you'll see that they are generating the page themselves.

**Comment by dschaper** [comment]
Checking further, getting a 404 now.

**Comment by AtomicLaser** [comment]
Any updates to this?  Would really like to have this back up instead of the "cannot find dns" errors

**Comment by dschaper** [comment]
Have you upgraded to the latest release? Can you run a `pihole -d` and post the results of the debug run so we can take a better look at the issue?

**Comment by AtomicLaser** [comment]
I thought I was on the latest update, but it would appear that a newer version had been released today!

Still the same on the new release; here's the debug log:

http://termbin.com/jw9e

**Comment by dschaper** [comment]
In a terminal on the Pi-Hole can you run the following:

`curl -I localhost`
`curl -i localhost/admin/`
`curl -i doubleclick.com`

And post up the responses that curl generates. The debug looks okay, want to check and see if our headers are being added and if the Pi-Hole can contact its own webserver.

**Comment by AtomicLaser** [comment]
Here are the results, I've snipped out the HTML coding that was spat out on localhost/adamin/

pi@pihole:~ $ curl -i doubleclick.com                                            
HTTP/1.1 200 OK                                                                  
X-Pi-hole: A black hole for Internet advertisements.                             
Content-Type: text/html                                                          
Accept-Ranges: bytes                                                             
ETag: "627042218"                                                                
Last-Modified: Sat, 09 Jul 2016 10:44:55 GMT                                     
Content-Length: 19                                                               
Date: Sat, 16 Jul 2016 19:02:20 GMT                                              
Server: lighttpd/1.4.35                                                          
                                                                                 
Blocked by Pi-Hole                                                               


i@pihole:~ $ curl -I localhost                                                  
HTTP/1.1 200 OK                                                                  
X-Pi-hole: A black hole for Internet advertisements.                             
Content-Type: text/html                                                          
Accept-Ranges: bytes                                                             
ETag: "627042218"                                                                
Last-Modified: Sat, 09 Jul 2016 10:44:55 GMT                                     
Content-Length: 19                                                               
Date: Sat, 16 Jul 2016 19:01:47 GMT                                              
Server: lighttpd/1.4.35               

pi@pihole:~ $ curl -i localhost/admin/                                           
HTTP/1.1 200 OK                                                                  
X-Pi-hole: The Pi-hole Web interface is working!                                 
X-Frame-Options: DENY                                                            
Content-type: text/html; charset=UTF-8                                           
Transfer-Encoding: chunked                                                       
Date: Sat, 16 Jul 2016 19:01:47 GMT                                              
Server: lighttpd/1.4.35

**Comment by dschaper** [comment]
All of the `X-Pi-hole` header tags come from the Pi-hole serving up the replacement images for the adverts. Can you now try to open http://doubleclick.com from a client browser and see if you get a blank page or if you get a dns error?

**Comment by AtomicLaser** [comment]
Still getting DNS issues on all my PCs

here's a curl output from my Mac if this helps:

IMAC:~ user$ curl -i doubleclick.com 
curl: (52) Empty reply from server


IMAC:~ user $ curl -i google.com
HTTP/1.1 302 Found
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Location: http://www.google.co.uk/?gfe_rd=cr&ei=PYeKV-q-I7SN8Qem7oDIDg
Content-Length: 261
Date: Sat, 16 Jul 2016 19:13:01 GMT

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.co.uk/?gfe_rd=cr&amp;ei=PYeKV-q-I7SN8Qem7oDIDg">here</A>.
</BODY></HTML>

**Comment by dschaper** [comment]
You should be getting the same response on the Mac with that curl command as you do directly on the Pi. Do you have any kind of firewall or iptables or port blocking running on the PI? 

Also, what does the `/etc/resolv.conf` file look like on the Mac?

**Comment by AtomicLaser** [comment]
That's what I thought, which is why i thought i'd give it a go!

Nothing running on the Pi other than Pi-Hol out of the box

**/etc/resolv.conf**
```
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
nameserver 192.168.1.1
```

**Comment by dschaper** [comment]
Is 192.168.1.1 your router? Does it have it's DNS set to the Pi-Hole at 192.168.1.92? (And if it is set up in that configuration, do you know if the router uses DNS Rebind Protection?)

**Comment by AtomicLaser** [comment]
Hi, 

192.168.1.1 is the router and 102.168.1.92 is the Pi.

The DNS is set in the router to got to the Pi then onwards from there to the world wide web.
Attached is the current setup
<img width="468" alt="screen shot 2016-07-16 at 21 05 54" src="https://cloud.githubusercontent.com/assets/11791329/16896890/3c133a9a-4b99-11e6-9b7c-be08ef3e1625.png">

The router is a DD-WRT firmware, so i'm not 100% sure if it uses DNS Rebind Protection, but I did make a few changes and I started seeing the custom page "Blocked by Pi-Hole" on the Windows PC, but not on the Mac, although the windows PC can be a bit glitchy and sometimes displays the DNS error

**Comment by dschaper** [comment]
Check here https://github.com/pi-hole/pi-hole/issues/292#issuecomment-186124004 it looks like this one has come up before, I use OpenWRT/Lede so my interface is different but the dhcp server should be the same. The link is to a DD-WRT solution.

**Comment by AtomicLaser** [comment]
<img width="633" alt="screen shot 2016-07-16 at 21 16 16" src="https://cloud.githubusercontent.com/assets/11791329/16896933/a30f8e1e-4b9a-11e6-86cc-b369d188621b.png">

Looks like DNS rebind is disabled.m but I'll have a read over that thread :)

**Comment by dschaper** [comment]
You may have to check via CLI, No DNS Rebind Enabled may actually mean Enable Anti-DNS Rebind mode.
