### ISSUE TITLE
v6 : WhiteList Rules not always working

### ISSUE THREAD

**Issue by Jarsky** [pi-hole/pi-hole#5643]
### Versions

Core
    Version is 448b1f4 (Latest: null)
    Branch is development-v6
    Hash is 448b1f4d (Latest: 448b1f4d)
Web
    Version is 78f59dd (Latest: null)
    Branch is development-v6
    Hash is 78f59dda (Latest: 78f59dda)
FTL
    Version is vDev-db32e4d (Latest: null)
    Branch is development-v6
    Hash is db32e4da (Latest: db32e4da)

### Platform
- OS and version:  Ubuntu 22.04
- Platform:  Raspberry Pi 4

### Expected behavior

When adding a domain to the Allow List; and reloading Gravity; the domain should be allowed to bypass the blocked domains. This happens most of the time; but sometimes it does not get allowed since upgrading to v6.

### Actual behavior / bug

The domain stays blocked and is null routed. e.g

```
2024-04-30 09:55:45.464 query[A] api.ipify.org from 192.168.30.244
2024-04-30 09:55:45.464 gravity blocked api.ipify.org is 0.0.0.0
```

Even though it is in the allow. 
Have also pulled the latest image and tried restarting Pihole and reloading Gravity again. The same issue persists. 

### Steps to reproduce

1. Click on 'Domains'
2. Add the appropriate domain (my example is api.ipify.org) and select 'Add Domain as Wildcard'. Click Add to allowed domains
3. Add the appropriate domain (my example is api.ipify.org) and leave Wildcard unticked. Click Add to allowed domains
4. Reload Gravity
5. Once reloaded try an NSLookup on the domain

## Debug Token

- URL:  https://tricorder.pi-hole.net/p0lQzI5z/

### Screenshots

![image](https://github.com/pi-hole/pi-hole/assets/839416/5f5a3740-cdf9-4db6-a3fe-879decba2f36)
![image](https://github.com/pi-hole/pi-hole/assets/839416/1805b874-0d52-4802-817d-a838e01254f4)

**Comment by rdwebdesign** [comment]
You added the regex entry to the `WhiteList-Infrastructure` group, but there are no Clients in this group, so the rule won't apply to your clients.

**Note:** 
Clients not set to any group will automatically use the rules set to Default group, but you need to manually add each client to user defined groups.

**Comment by Jarsky** [comment]
> You added the regex entry to the `WhiteList-Infrastructure` group, but there are no Clients in this group, so the rule won't apply to your clients.
> 
> **Note:** Clients not set to any group will automatically use the rules set to Default group, but you need to manually add each client to user defined groups.

Thank you so much; ahhh I feel like an idiot. I decided to create groups to categorise them when I migrated from v5 to v6 to make it easier to filter through them. Didnt consider that they dont get assigned all groups bey default!
