### ISSUE TITLE
Whitelist fails CORS when not browsing using IP address

### ISSUE THREAD

**Issue by JunaidZA** [pi-hole/pi-hole#565]
##### Expected Behaviour:

Adding a domain to whitelist 
##### Actual Behaviour:

Does not add to whitelist as the JavaScript call fails CORS
##### Steps to reproduce this issue:

Browse the pihole admin using the PM's domain name, not it's IP and add try to add a domain to the whitelist
##

**Comment by Mcat12** [comment]
I'll link to a Reddit post with a similar question (are you the same person?) http://www.reddit.com/r/pihole/comments/4sa7hh/_/ Though we should have put the hostname of the Pi-hole in the accepted origins.

**Comment by JunaidZA** [comment]
Thanks Mcat, yes that was me.

**Comment by Windyo** [comment]
To add to this issue :
For those of use who have a multi-purpose Pi, the same problem arises if we decide to use another port for the WebAdmin.
For example, I have my pi-hole webadmin set up on port 8017 ; whitelisting fails CORS because of that.
Going to pi.hole redirects to what I have hosted on port 80, which is expected but not volontary behavior.

**Comment by Mcat12** [comment]
[This](https://github.com/pi-hole/pi-hole/issues/546#issuecomment-235917230) will help for having a different port.

**Comment by Windyo** [comment]
@Mcat12 followed the steps, still fails CORS for some reason.

**Comment by Mcat12** [comment]
Did you modify the change for your custom port? And are you going to the page using `http://pi.hole:8017/admin/`?

**Comment by Windyo** [comment]
I modified `/var/www/html/admin/php/sub.php` and `/var/www/html/admin/php/sub.php`
to 
`// Check CORS
if($_SERVER['HTTP_ORIGIN'] == "http://pi.hole:8017" || $_SERVER['HTTP_ORIGIN'] == "http://${_SERVER['SERVER_ADDR']}:8017")
    header("Access-Control-Allow-Origin: ${_SERVER['HTTP_ORIGIN']}");
else if($_SERVER['HTTP_HOST'] == $_SERVER['SERVER_ADDR'] || $_SERVER['HTTP_HOST'] == "pi.hole")
    header("Access-Control-Allow-Origin: ${_SERVER['HTTP_HOST']}");
else
    die("Failed CORS");`
and tried accessing the panel via `http://my.ad.dr.es.ss:8017/admin` and `http://pi.hole:8017/admin`, no dice.

**Comment by Mcat12** [comment]
Ah, I forgot to mention one thing. Those `header(...)` lines need to also have the port on them.

**Comment by Mcat12** [comment]
Are you using Internet Explorer or Edge?

**Comment by Windyo** [comment]
Where should I put the port in the Header lines ?
I am using firefox and Chrome  interchangeably

**Comment by Mcat12** [comment]
That comment was actually wrong, since `$_SERVER['HTTP_ORIGIN']` should contain the port. Add this line right after `// Check CORS`:
```
echo $_SERVER['HTTP_ORIGIN'];
```
And then follow [these](https://github.com/pi-hole/pi-hole/issues/546#issuecomment-233498279) instructions (using your correct port of course).

**Comment by Windyo** [comment]
I failed to get it working following the instructions.
I ended up bypassing CORS for now.

**Comment by Mcat12** [comment]
What was in the response? Remember that by removing CORS, you are removing a security feature.

**Comment by Windyo** [comment]
The response was still "failed CORS" with no other information, even after adding `echo $_SERVER['HTTP_ORIGIN'];`.

I'm not psyched about removing CORS but if I don't my less technically-inclined co-users of the router can't bypass the pihole when need be, which is a much bigger problem in my book.

**Comment by Mcat12** [comment]
Did you add that `echo` line to `add.php` as well as `sub.php`?

**Comment by Windyo** [comment]
Yes.

**Comment by Mcat12** [comment]
Weird... afaik Chrome sends the Origin header along with all requests, including same-origin ones... Well, in the dev version of the web interface, we are handling CORS better, so this would not be an issue if the Origin header is missing.

**Comment by xac1d** [comment]
i had the same issue. maybe this can help you https://www.reddit.com/r/pihole/comments/52icnm/nginx_reverse_proxy_not_working_with_pihole/

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #184](https://github.com/pi-hole/AdminLTE/issues/184) via [**ZenHub**](https://www.zenhub.com/)
