### ISSUE TITLE
Pihole re-installation failed

### ISSUE THREAD

**Issue by rsauve** [pi-hole/pi-hole#5659]
### Versions
Pi-hole version is v5.18.2 (Latest: v5.18.2)
web version is v5.21 (Latest: v5.21)
FTL version is v5.25.2 (Latest: v5.25.2)

### Platform
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Expected behavior
Installed a replacement router (Synology RT6600ax). When I tried to log into the admin web interface I was presented with a very large pihole logo and a the bottom of the page was a login field with a username Pi-hole (username could not be changed). my usual password did not work.

I tried to change password (sudo pihole -a -p), that did not work either.
I uninstalled pihole using the uninstalled script (Pi-hole/automated install/uninstall.sh).
I then installed pihole using: curl -sSL https://install.pi-hole.net | bash

I excluded lighttpd as my server is running Apache2.

After the installed was complete I tried to log into the admin interface. This time it just display some text on the page (no login):

Total queries

 active clients
Queries Blocked

List blocked queries
Percentage Blocked

List all queries
Domains on Adlists

Manage adlists
Total queries over last 24 hours
Client activity over last 24 hours
Query Types

Upstream servers
Top Permitted Domains
Domain Hits Frequency
Top Blocked Domains
Domain Hits Frequency
Top Clients (total)
Client Requests Frequency
Top Clients (blocked only)
Client Requests Frequency

### Actual behavior / bug

Even though I uninstalled pihole and re-installed, its not a clean out of the box installation. Something is preventing the web interface from operating.
Before I installed the new router pihole was happy running under apache2.
Not sure why there is a problem.

### Steps to reproduce

Swap out router
Change LAN IP address range
Update all resources and devices for new IP address range
Log into pihole web interface

## Debug Token
https://tricorder.pi-hole.net/mIwsXCKM/

---

UPDATE: Web interface is now back displaying large logo and fixed user login page:

![Capture](https://github.com/pi-hole/pi-hole/assets/26235138/4b0ce592-603b-41f9-9a71-d45721093191)

---
UPDATE2: http://192.168.5.1/admin/ displays the text only page
http://192.168.5.1/admin/login.php displays logo and fixed username page

http://192.168.5.1/admin/login.php is how I normally log into pihole

**Comment by rdwebdesign** [comment]
Your debug log shows you are running Apache on port 53:

```
[✗] tcp:*:80 is in use by apache2 (https://docs.pi-hole.net/main/prerequisites/#ports)
```

You have 2 options:

- disable Apache to free up port 53 for `lighttpd` (the web server used by Pi-hole) or

- change the port used by `lighttpd` to something else (like `server.port = 8080`) in `/etc/lighttpd/lighttpd.conf`. If you choose this option, you will need to access the web interface using the port: http://192.168.5.1:8080/admin/

**Comment by rsauve** [comment]
Thank you for pointing me in the right direction, rdwebdesign.
I changed server.port = 8080 in file /etc/lighttpd/lighttpd.conf
Enabled lightpd. Now both appache2 and lightpd services can run at the same time without error.
I re-installed pihole, opened the web interface at port 8080 and logged in as normal.
All is working again.

I only have one website running under apache2, I should get it running under lightpd and uninstall apache2.

**Comment by rdwebdesign** [comment]
I missed your last comment.

> I could not find port 53 bind to apache2

This is expected. 
Port 53 is used for DNS queries and has nothing to do with apache2. It will be used by `pihole-FTL`.
