### ISSUE TITLE
Error 500 when accessing Network tab

### ISSUE THREAD

**Issue by galvesribeiro** [pi-hole/pi-hole#5663]
### Versions

- Pi-hole:  v5.18.2
- AdminLTE:  v5.21
- FTL:  v5.25.2

### Platform

- OS and version:  Ubuntu 24.04 LTS

- Platform:  Raspberry Pi 5

### Expected behavior

Access to all tabs on the WebUI without errors.

### Actual behavior / bug

When I click on Tools > Network I get a 500.

### Steps to reproduce

1. Access the web interface
2. Go to Tools > Network

## Debug Token

- URL:  https://tricorder.pi-hole.net/HgQK7z2E/

### Screenshots

<img width="486" alt="image" src="https://github.com/pi-hole/pi-hole/assets/4714040/e8098715-1af6-499c-b8f0-51244ca7940f">
<img width="1799" alt="image" src="https://github.com/pi-hole/pi-hole/assets/4714040/1d2105e7-1bf2-418a-a2b0-2f449c2a88a7">
<img width="1777" alt="image" src="https://github.com/pi-hole/pi-hole/assets/4714040/0ac831b2-5fa3-48b8-b057-15922d92721f">
<img width="1769" alt="image" src="https://github.com/pi-hole/pi-hole/assets/4714040/dec6fcd9-120f-43fd-93a0-230f71aa89ea">

### Additional context

I had it running on same OS but on a PI 4 and it worked just fine.

**Comment by rdwebdesign** [comment]
Your debug log shows your database file is incomplete.

The file is only 24Kb, but an empty database should be 80Kb:

```css
*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 24K May 19 20:18 /etc/pihole/pihole-FTL.db
```

To fix this, you need to stop Pi-hole, move (or delete) the database and restart Pi-hole (a new database will be created).
Execute the 3 commands bellow:

```
sudo service pihole-FTL stop
sudo mv /etc/pihole/pihole-FTL.db /etc/pihole/pihole-FTL-old.db
sudo service pihole-FTL start
```

**Comment by galvesribeiro** [comment]
That worked perfectly fine! Thank you for the very quick response!
