### ISSUE TITLE
Again discrepancy in versions

### ISSUE THREAD

**Issue by LutzRFrank** [pi-hole/pi-hole#5693]
### Versions

  Pi-hole version is v5.14.1 (Latest: v5.18.2)
  AdminLTE version is v5.21 (Latest: null)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- OS and version:  
- PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm

- pi@RaspberryPi-4B-2GB:/etc/pihole $ cat /etc/debian_version: 12.1

- Platform:  Raspberry Pi

### Expected behavior

PiHole version numbers don't match
  Pi-hole version is v5.14.1 (Latest: v5.18.2) versus
  pihole -up telling up to date (see below)

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

check versions on web interface and pihole
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 8.2.20
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!

## Debug Token

- URL:  https://tricorder.pi-hole.net/vwnbUTQt/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
Please follow the template and supply a debug Token:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by LutzRFrank** [comment]
[✓] Your debug token is: https://tricorder.pi-hole.net/vwnbUTQt/

**Comment by LutzRFrank** [comment]
Solved by switching on the Beta-Train

pi@RaspberryPi-4B-2GB:~ $ sudo pihole -up
  [✓] Update local cache of available packages
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL binary already installed, verifying integrity...
  [i] Local binary up-to-date. No need to download!
  [i] FTL:		up to date
  [i] Warning: You are using FTL from a custom branch (development-v6) and might be missing future releases.

No discrepancy, diving into testing ...
