### ISSUE TITLE
[web/development-v6] Top Domains and Top Clients do not adjust according to privacy mode selection

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/pi-hole#5699]
**I opened here originally then closed and opened as https://github.com/pi-hole/web/issues/3068**

**I reopened this for visibility**

### Versions

Core
    Version is v5.18.2-400-g8b324741 (Latest: null)
    Branch is development-v6
    Hash is 8b324741 (Latest: 8b324741)

Web
    Version is v5.19-818-ge852fbb2 (Latest: null)
    Branch is development-v6
    Hash is  e852fbb2  (Latest: e852fbb2 )

FTL
    Version is vDev-5c97d29 (Latest: null)
    Branch is development-v6
    Hash is 5c97d290  (Latest: 5c97d290 )

### Platform

- OS and version:  Ubuntu 24.04 LTS

- Platform:  Raspberry Pi 4 Model B Rev 1.1

### Expected behavior

when privacy mode is set to anything other than `Show Everything`  the last 4 boxes should be hidden when they contain no data.

### Actual behavior / bug

when privacy mode is set to `Anonymous mode` the last 4 boxes show a loading wheel endlessly

### Steps to reproduce

1. set privacy mode to anything other than `Show Everything`
2. go to the dashboard 
3. Scroll down to the bottom of the dashboard (http://pi.hole/admin/)
4. See boxes with loading wheels, how many depends on privacy mode selection ( as seen in screenshots )

## Debug Token

- URL:  https://tricorder.pi-hole.net/tog4t1Nu/

### Screenshots

This is when `Anonymous mode` & `Hide domains and clients` is selected 
![Screenshot from 2024-07-07 21-09-56](https://github.com/pi-hole/pi-hole/assets/5729320/3dc965fc-20fb-440c-a97f-924497e5e859) 

This is when `Hide domains` is selected 
![Screenshot from 2024-07-07 21-45-52](https://github.com/pi-hole/web/assets/5729320/f45cb8c6-ed22-415b-a129-d0f7298e79fc)

**Comment by mwoolweaver** [comment]
closed here and opened https://github.com/pi-hole/web/issues/3068

**Comment by rdwebdesign** [comment]
No need for 2 issues.
