### ISSUE TITLE
DCHP No longer responding to Client Request after Pi-Hole Update to v5.18.3

### ISSUE THREAD

**Issue by angeloluidens** [pi-hole/pi-hole#5702]
### Versions

  Pi-hole version is v5.18.3 (Latest: v5.18.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform
- OS and version:  
     Debian 11 / VM/VPS
- Platform:  
     Proxmox

### Expected behavior
     Client devices automatically get assigned an IP address from the defined pool of addresses.

### Actual behavior / bug
     Client devices DO NOT receive a response from the PiHole/DCHP Server with a designated IP address for the device from the Address Pool.

### Steps to reproduce
     Pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/zoISvWqo/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by taitaitai1777** [comment]
Here's a structured guide to help you diagnose and resolve DHCP issues with Pi-Hole after an update:

## Troubleshooting and Resolving Pi-Hole DHCP Issues

### Step 1: Check Logs
Logs provide valuable insights into potential issues. 

- **Pi-Hole Logs:**
  ```bash
  sudo tail -f /var/log/pihole.log
  ```
- **System Logs:**
  ```bash
  sudo tail -f /var/log/syslog
  ```
  or for `journalctl`:
  ```bash
  sudo journalctl -xe
  ```

### Step 2: Verify DHCP Configuration
Ensure the DHCP server settings are correctly configured.

- **Via the Web Interface:**
  1. Navigate to `http://pi.hole/admin` or your Pi-Hole's IP/admin.
  2. Go to **Settings** > **DHCP**.
  3. Verify that the DHCP server is enabled and properly configured.

- **Via Configuration File:**
  1. Open `/etc/dnsmasq.d/02-pihole-dhcp.conf`.
  2. Ensure settings are correct, e.g.:
     ```ini
     dhcp-range=192.168.1.100,192.168.1.200,24h
     ```
  3. Correct any syntax errors or misconfigurations.

### Step 3: Restart the Pi-Hole Service
Restart the service to resolve transient issues.

```bash
sudo systemctl restart pihole-FTL
```
or
```bash
sudo service pihole-FTL restart
```

### Step 4: Reset FTL Database
Resetting the database can fix corruption issues.

1. Remove the existing database:
   ```bash
   sudo rm /etc/pihole/pihole-FTL.db
   ```
2. Restart the service:
   ```bash
   sudo systemctl restart pihole-FTL
   ```

### Step 5: Re-enable DHCP Service
Disabling and then re-enabling the service can force reinitialization.

- **Via the Web Interface:**
  1. Navigate to **Settings** > **DHCP**.
  2. Disable the DHCP server and save changes.
  3. Re-enable the DHCP server and save changes again.

### Step 6: Check for Conflicting Services
Make sure no other DHCP servers (like those on a home router) are running on the same network.

- **Disable Router DHCP:**
  1. Access your router’s admin interface (`192.168.1.1` or `192.168.0.1`).
  2. Locate DHCP settings.
  3. Disable the router’s DHCP server.

### Step 7: Update Pi-Hole
Make sure you're running the latest version to fix known bugs.

```bash
pihole -up
```

### Step 8: Reconfigure Pi-Hole
Reconfigure can resolve underlying issues.

1. Initiate reconfiguration:
   ```bash
   pihole -r
   ```
2. Choose the **Reconfigure** option.

### Step 9: Check Network Settings
Ensure the device running Pi-Hole is correctly configured.

- **Verify IP Address Configuration:**
  ```bash
  ip addr show
  ```
  or
  ```bash
  ifconfig
  ```

- **Ensure Correct Settings:** 
  - Confirm the IP matches Pi-Hole’s DHCP settings.
  - Verify subnet mask (typically `255.255.255.0`).

### Step 10: Consult Community and Report Issues
If all else fails, seek help from the Pi-Hole community or report an issue.

- **Pi-Hole Community Forums:** [Pi-Hole Discourse](https://discourse.pi-hole.net/)
- **GitHub Issues:** [Pi-Hole GitHub Issues page](https://github.com/pi-hole/pi-hole/issues)

### Additional Debugging Steps

1. **Network Analysis Tools:**
   Use tools like `Wireshark` to analyze network traffic.
   
2. **Check for IP Conflicts:**
   Ensure no device is using Pi-Hole’s IP.

3. **Temporary Fix - Static Leases:**
   Set static IP leases for critical devices.

4. **Alternative DHCP Server:**
   Consider using another DHCP server and point DNS to Pi-Hole.

By following this guidance, you should be able to troubleshoot and resolve DHCP issues with your Pi-Hole setup.

**Comment by boscorelly** [comment]
hi, i confirm the same problem here.

docker version 2024.7.0 / 5.18.3.

from debug : 

-rw-r--r-- 1 1000 pihole 790 Aug  4 23:18 /etc/dnsmasq.d/04-pihole-static-dhcp.conf
   dhcp-host=04:CF:8C:41:D7:1C,192.168.1.150,Ventilateur-chambre

in pihole :

# docker exec pihole cat /etc/pihole/dhcp.leases
1723064066 04:cf:8c:41:d7:1c 192.168.1.102 dmaker-fan-p5_miapD71C *

**Comment by boscorelly** [comment]
found my issue : as i use docker and needed a way to accept connections with external ip address, i added a route causing problems. remobing the route solved the problem.
