### ISSUE TITLE
CNAME to `pi.hole` does not return an IP

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pi-hole/pi-hole#5712]
### Versions

- Pi-hole:  5.18.3
- AdminLTE:  5.21
- FTL:  5.25.2

### Platform

- OS and version:  22.04.1-Ubuntu

- Platform:  N100 computer

### Expected behavior

CNAME to a domain to `pi.hole` should also return an A record of pi.hole just like https://github.com/pi-hole/pi-hole/issues/3915#issuecomment-740183130

### Actual behavior / bug

The response of the lookup is incomplete and does not have an IP. 

### Steps to reproduce

1. confirm `not.pi.hole` is not resolvable
2. CNAME `not.pi.hole` to `pi.hole`
3. `dig not.pi.hole`
4. observe the incomplete lookup response

## Debug Token

- URL:  https://tricorder.pi-hole.net/mIhPvjCL/

### Screenshots

![image](https://github.com/user-attachments/assets/91df3d76-46c7-45a0-b66b-904107544e0b)

### Additional context

https://www.reddit.com/r/pihole/comments/1eedk3n/cname_to_pihole_not_working_as_expected/

**Comment by laplongejunior** [comment]
I'm not sure how to refer to other issues in github but I had already opened an issue about it a few years ago : https://github.com/pi-hole/pi-hole/issues/4647

**Comment by SodaWithoutSparkles** [comment]
Yeah I think my searches missed that issue. But it doesnt seem like there were any replies and updates since 2 years ago so I'll leave this up.

My usecase involves pi-hole responding to the correct IP when it was asked from a VPN interface/local lan/docker. A spilt tunnel is used to only tunnel the IPs in the VPN range. Forcing the 192.168 IP would not work as it isnt in the range.

Including the 192.168 IP in the VPN ranges would 1) cause a lot of routing issues when the wifi subnet you are on happens to be the same range, and 2) happens to crash my VPN client. The first issue is very significant as the 192.168.0.0/24 range is the default for most consumer routers.

**Comment by SodaWithoutSparkles** [comment]
anti-stale

**Comment by UberKitten** [comment]
Also running into this issue in a similar context.
