### ISSUE TITLE
 Old clients (inactive for more than 24 hours) in the “Top Clients (total)” list show incorrect data

### ISSUE THREAD

**Issue by AS98765** [pi-hole/pi-hole#5714]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.25.2
- FTL:  v5.21

### Platform

- OS and version:  Raspberry Pi OS Lite (64-bit), Bookworm
- Platform:  Raspberry Pi

### Expected behavior

Old clients should be deleted from the list. Alternatively, the number of “Requests” should be set to 0.

### Actual behavior / bug

The “Requests” in the “Top Clients (total)” list show the data from the last 24 hours.

For old clients, undefined data is displayed. Clicking on the link with the 76 requests here then displays “No data available in table”.

### Steps to reproduce

Imo not necessary

### Debug Token
...

### Screenshots

![Screenshot 2024-07-30 124612 - m 2](https://github.com/user-attachments/assets/5c4a5b51-a6bb-42f3-a10e-2754a47f0c36)
![Screenshot 2024-07-30 123552](https://github.com/user-attachments/assets/726db7ec-a702-474d-b13d-3e462318e505)

### Additional context

N/A

**Comment by yubiuser** [comment]
Please provide a debug token.
