### ISSUE TITLE
barebone pi-hole thinks

### ISSUE THREAD

**Issue by Nukiver** [pi-hole/pi-hole#5728]
### Versions

- Pi-hole:  v5.17.3
- AdminLTE: v5.21  
- FTL:  v5.24
(Only have a screenshot from the pi-hole web interface because right after commenting the docker_version in versions file I updated...)

### Platform

- OS and version:  Linux rpi5 6.6.31+rpt-rpi-2712 # 1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

- Platform:  Raspberry Pi 5
Got docker installed for other stuff, but not for pi-hole. Traefik is running docker but pi-hole is used bare-bones.

### Expected behaviour

When running `pi-hole -up` it should check and understand if it is running under docker or is a bare-bones install and accordingly then run the update if it's bare bone.

### Actual behaviour / bug

When running `pi-hole -up` and the versions file in /etc/pihole/versions has a docker_version inside, pi-hole says, “Function not supported in Docker images” even if running on bare-bones. 
Why /etc/pihole/versions included docker_version is unclear.

### Steps to reproduce

1. Have bare-bones installation of pi-hole running
2. Add “DOCKER_VERSION=2024.01.0” to /etc/pi-hole/versions 
3. run `pi-hole -up`

## Debug Token

- URL:   https://tricorder.pi-hole.net/Wdc99mFu/

### Additional context

It's unclear how the docker_version got into the pi-hole versions file, when it is not running in docker. Maybe somebody can find out and clear it up?

**Comment by rdwebdesign** [comment]
Your debug log shows Pi-hole is running bare metal, in a Ubuntu OS:

```
*** [ DIAGNOSING ]: Operating system
[✓] Distro:  Debian
[✓] Version: 12
[✓] dig return code: 0
[i] dig response: "Raspbian=10,11,12 Ubuntu=20,22,23,24 Debian=10,11,12 Fedora=39,40 CentOS=9"
[✓] Distro and version supported
```

---

> #### Steps to reproduce
> 2. Add “DOCKER_VERSION=2024.01.0” to /etc/pi-hole/versions

Why are you doing this?

---

To fix it, delete and recreate the versions file with:

```
rm /etc/pihole/versions
pihole updatechecker
```

Then try `pihole -up` again.

**Comment by yubiuser** [comment]
> Expected behaviour
When running pi-hole -up it should check and understand if it is running under docker or is a bare-bones install and accordingly then run the update if it's bare bone.

This is exactly what Pi-hole is doing. The way we do it is by checking for the `DOCKER_VERSION` key.

This should never exist on bare metal, as ist is injected on docker image creation.

https://github.com/pi-hole/docker-pi-hole/blob/d4dd6b0a41bfb06629a5544d18680d5cce43c8f2/src/Dockerfile#L5

And

https://github.com/pi-hole/pi-hole/blob/be5a8dc51a7b3e7ec3b40a9c815dee1c866ea2d4/advanced/Scripts/updatecheck.sh#L55

**Comment by Nukiver** [comment]
> > Expected behaviour
> > When running pi-hole -up it should check and understand if it is running under docker or is a bare-bones install and accordingly then run the update if it's bare bone.
> 
> This is exactly what Pi-hole is doing. The way we do it is by checking for the `DOCKER_VERSION` key.
> 
> This should never exist on bare metal, as ist is injected on docker image creation.
> 
> https://github.com/pi-hole/docker-pi-hole/blob/d4dd6b0a41bfb06629a5544d18680d5cce43c8f2/src/Dockerfile#L5
> 
> And
> 
> https://github.com/pi-hole/pi-hole/blob/be5a8dc51a7b3e7ec3b40a9c815dee1c866ea2d4/advanced/Scripts/updatecheck.sh#L55

The problem is, it did not detect correctly, that - even though I have docker installed - I have pi-hole installed bare bones and blocked the installation of updates. -> Which is not intended I would guess?!

**Comment by rdwebdesign** [comment]
Did you manually set `DOCKER_VERSION` in versions file?

If you manually change this configuration, you are effectively telling Pi-hole it is inside a container and Pi-hole will behave accordingly.

**Comment by Nukiver** [comment]
> Did you manually set `DOCKER_VERSION` in versions file?
> 
> If you manually change this configuration, you are effectively telling Pi-hole it is inside a container and Pi-hole will behave accordingly.

I did NOT manually change the versions file.

**Comment by rdwebdesign** [comment]
Did you copied the configurations file from a previous docker installation?

If you did, the variable was there because it actually was a docker installation.

Now it you just need to fix it.
Delete and recreate the versions file with:
``` 
rm /etc/pihole/versions
pihole updatechecker
```

just follow

**Comment by yubiuser** [comment]
Does the file `/pihole.docker.tag` exist?

**Comment by Nukiver** [comment]
> Did you copied the configurations file from a previous docker installation?
> 
> If you did, the variable was there because it actually was a docker installation.
> 
> Now you just need to fix it. Delete and recreate the versions file with:
> 
> ```
> rm /etc/pihole/versions
> pihole updatechecker
> ```

I actually did copy some files over from an old installation, but the old one was barebone aswell! :D 

I did 
```
rm /etc/pihole/versions
pihole updatechecker
```
and checked the versions file and it did not contain the docker_version tag anymore. 



> Does the file `/pihole.docker.tag` exist?

Where do I search for it ? I have not found it in /etc/pihole

![image](https://github.com/user-attachments/assets/d6c0a57d-7a23-4a1b-af6c-a3b4992440ae)

**Comment by Nukiver** [comment]
> > #### Steps to reproduce
> > 
> > 2. Add “DOCKER_VERSION=2024.01.0” to /etc/pi-hole/versions
> 
> Why are you doing this?

And to reiterate on the "why are you doing this" 
To recreate the bug -> If this is the only "failsafe" to check if pi-hole is docker installation, I don't think it's thought through enough. Correct me if I'm wrong.

**Comment by yubiuser** [comment]
It would be in the filesystems root folder.

**Comment by Nukiver** [comment]
> It would be in the filesystems root folder.

It's not there either. 
![image](https://github.com/user-attachments/assets/1b8b693f-9a73-4fe7-ad36-8c06198d1859)

**Comment by yubiuser** [comment]
> I don't think it's thought through enough. Correct me if I'm wrong.

Your the first encountering/reporting this issue. I think this is failsafe enough and the fix (delete the additional line) is simple. We tried different approaches how to detect running inside a container. None was really 'failsafe'. Additionally, we use the docker version tag inside the container for different things, e.g. display it on the web interface.

But I'm interested in your suggestion how to detect if a process is running inside a container.

**Comment by rdwebdesign** [comment]
> and checked the versions file and it did not contain the docker_version tag anymore.

Try `pihole -up` again.
Does the issue still happen even without the tag in versions file?

If it does, maybe you have the variable `DOCKER_VERSION` in your environment.

Check the output of `env | grep DOCKER_VERSION`. If the variable is there, unset the value with `env -u DOCKER_VERSION`.

**Comment by Nukiver** [comment]
> > and checked the versions file and it did not contain the docker_version tag anymore.
> 
> Try `pihole -up` again. Does the issue still happen even without the tag in versions file?
> 
> If it does, maybe you have the variable `DOCKER_VERSION` in your environment.
> 
> Check the output of `env | grep DOCKER_VERSION`. If the variable is there, unset the value with `env -u DOCKER_VERSION`.

After removing the tag it worked (it worked already with commenting the tag line!)

I found that workaround online -> Don't think I was the only one happening to. 

https://discourse.pi-hole.net/t/function-not-supported-in-docker-images/65700/2



> > I don't think it's thought through enough. Correct me if I'm wrong.
> 
> Your the first encountering/reporting this issue. I think this is failsafe enough and the fix (delete the additional line) is simple. We tried different approaches how to detect running inside a container. None was really 'failsafe'. Additionally, we use the docker version tag inside the container for different things, e.g. display it on the web interface.
> 
> But I'm interested in your suggestion how to detect if a process is running inside a container.

Good reality check here, I haven't thought that far, sorry about that. I don't know if there is a good way to check that.

**Comment by rdwebdesign** [comment]
> I don't know if there is a good way to check that.

It's not easy.
When Pi-hole is inside the container, it doesn't have access to your host OS, so the code inside the container don't know it is actually running in a docker container. That's why we decided to use the variable.

**Comment by Nukiver** [comment]
> > I don't know if there is a good way to check that.
> 
> It's not easy. When Pi-hole is inside the container, it doesn't have access to your host OS, so the code inside the container don't know it is actually running in a docker container. That's why we decided to use the variable.

Fair enough. Thanks for the help. Probably the easiest way to have the workaround and if needed to use that.
