### ISSUE TITLE
gravity.sh: Error: cannot open "/tmp/tmp.YE2CkYX4gG"

### ISSUE THREAD

**Issue by corbolais** [pi-hole/pi-hole#5746]
Pi-hole v5.18.2
FTL v5.25.2
Web Interface v5.21

Pi Brev2 buster and bookworm

This line: 

https://github.com/pi-hole/pi-hole/blob/be5a8dc51a7b3e7ec3b40a9c815dee1c866ea2d4/gravity.sh#L159

is causing the following issue:

```
# pihole -g -r recreate
[✓] Recreating gravity database from migration backup
[i] Creating new gravity database
[i] Migrating content of /etc/pihole/adlists.list into new database
[i] Migrating content of /etc/pihole/blacklist.txt into new database

[✗] Unable to fill table domainlist1 in database /etc/pihole/gravity.db
Error: cannot open "/tmp/tmp.YE2CkYX4gG"
[✓] Cleaning up stray matter
[✓] FTL is listening on port 53
[✓] UDP (IPv4)
[✓] TCP (IPv4)
[✓] UDP (IPv6)
[✓] TCP (IPv6)

[✓] Pi-hole blocking is enabled
```

Commenting the offending `mv` line yields a successful gravity recreate command.

EDIT: notice, this line is present in the latest git branch as well.

I might miss something. Why does this line exist in the first place? It strikes me as a strange thing to create an unpredictable tmp file to just rename it to something predictable.

thx.

**Comment by yubiuser** [comment]
> I might miss something. Why does this line exist in the first place? It strikes me as a strange thing to create an unpredictable tmp file to just rename it to something predictable.

As the comment right above the line says

>   Create a temporary file. We don't use '--suffix' here because not all
 >  implementations of mktemp support it, e.g. on Alpine

**Comment by yubiuser** [comment]
There is an issue in `master` which is fixed in `development` already

https://github.com/pi-hole/pi-hole/commit/fd8fdd3513f7d41afddfe1877d11261c7e4ac0b2

The issue was that we later try to remove the temp file but did not update the variable containing the path.
