### ISSUE TITLE
"Local DNS Records" -> "domain/IP associations": No consideration of capital letters

### ISSUE THREAD

**Issue by AS98765** [pi-hole/pi-hole#5755]
### Versions

- Pi-hole: v5.18.3
- AdminLTE: v5.25
- FTL: v5.21

### Platform

- OS and version: Raspberry Pi OS Lite (64-bit), Bookworm
- Platform: Raspberry Pi

### Expected behavior

Consideration of capital letters as with the other DNS records.
If not technically possible in this context, perhaps a comment under “Note”.

### Actual behavior / bug

Capital letters are not taken into account

### Steps to reproduce

Imo not necessary

### Debug Token

...

### Screenshots

If necessary

### Additional context

N/A

**Comment by yubiuser** [comment]
DNS Resolution, in general, is case insensitive. 
`google.com` and `Google.com` and `gOOgLe.com` are equal DNS-wise.
