### ISSUE TITLE
SSH into the pi, ran pihole -up, now cannot access WebIF (/admin)... 403 Forbidden

### ISSUE THREAD

**Issue by Majestic7979** [pi-hole/pi-hole#5756]
### Versions

  Pi-hole version is v5.18.3 (Latest: v5.18.3)
  web version is devel v5.21-930-g465bb1c9 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- OS and version:  ```Raspberry Pi OS - Linux version 6.1.28-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1649 SMP PREEMPT Fri May 12 14:25:37 BST 2023```
- 

- Platform:  Raspberry Pi 4

### Expected behavior

I was always able to access my WebUI admin interface via pihole-ip/admin and now I get 403 Forbidden.

I also use Traefik and was able to access by going to blk.mydomain.com and now I cannot... same error.
### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

Starting from the previous version I just ran sudo apt get -y full-upgrade to ensure my Pi OS was up to date, then I ran pihole -up to update PiHole itself. Now I cannot access the Web admin page. Blocking still seems to work fine. I use Unbound too.

My iptables -L:

```
sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8000
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:9000

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/kwxAU9Cj/

### Screenshots

![image](https://github.com/user-attachments/assets/55f48f2a-334a-489d-aa7c-3f9f8cd5edf3)
### Additional context

I have always done the same process to ensure my system is fine:

ssh into pi4
sudo apt update
sudo apt -y full-upgrade
pihole -up

have always been able to access the admin UI until now.

I also ran pihole -r

I also did a apt purge of lighttpd and then ran pihole -r

I do not really want to uninstall and install from zero because I'll lose my configs...

This only happened after an update, nothing else was running. I do not have apache or nginx webservers installed so they are not conflicting.

I also added module mod_fastcgi to lighttpd config but that made no difference (found this by googling).

At a loss here! I really need to keep an eye on things using the webui so it's important to regain access, please help :) Thanks!

**Comment by rdwebdesign** [comment]
You are using `devel` branch for the Web interface:

```
*** [ DIAGNOSING ]: Core version
[✓] Version: v5.18.3
[i] Branch: master
[i] Commit: v5.18.3-0-gbe5a8dc5

*** [ DIAGNOSING ]: Web version
[✓] Version: v5.21
[i] Branch: devel                     <-------- This should be master
[i] Commit: v5.21-930-g465bb1c9

*** [ DIAGNOSING ]: FTL version
[✓] Version: v5.25.2
[i] Branch: master
[i] Commit: 8943e260
```

This branch is not compatible with the other Pi-hole v5 components.

Run `pihole checkout web master` to switch to `master` web interface, then try `pihole -up` again.

**Comment by Majestic7979** [comment]
Hi rdwebdesign, you are totally right that this fix will allow me to access, it worked.

But I never installed using the devel branch, so not sure how it changed to that!? Confused here.

Anyway, thanks so much for providing a quick and easy fix! I am running the webif again :)

Have a nice day!

**Comment by rdwebdesign** [comment]
> But I never installed using the devel branch, so not sure how it changed to that!?

The only way to use this branch is executing `pihole checkout web devel`.

If you didn't intentionally changed to `devel`, someone else (or some script) did, but I think this is just a case of "memory lapse". Sometimes we try different branches and forget about them. This is not that uncommon.

You probably changed that a long time ago, forgot about it and kept updating Pi-hole using `devel` branch without issues. This branch was compatible with v5, but this changed very recently.

**Comment by Majestic7979** [comment]
I'm sorry if it's memory lapse however I've been running this since 2022 and have done the process outlined above countless times... If someone accessed my server somehow that's a possibility but I definitely didn't issue that command or by your own explanation I wouldn't have been able to access the WebUI, right? This isn't me arguing, just not really sure what happened but the last time I used the WebIF successfully was just last month, and then I ran apt update followed by pihole -up and suddenly lost access. I am just happy your provided solution worked, thanks again!

**Comment by rdwebdesign** [comment]
> This isn't me arguing, just not really sure what happened but the last time I used the WebIF successfully was just last month

I understand. I'm also not arguing. 
I'm just trying to explain what caused your issue.

> but I definitely didn't issue that command or by your own explanation I wouldn't have been able to access the WebUI, right?

Not exactly.

Until around a week go `devel` branch was working as you expected, but this branch was **recently changed**. The web interface would have been working until a week ago, even after updates.

I really don't think someone accessed your server (no need to worry). 
I'm almost sure you just tried the command a long time ago, forgot about it and never noticed. 

Now this branch will fail if mixed with `master` branches.

Anyway, it is fixed now.

**Comment by Majestic7979** [comment]
Makes total sense, thanks for your patience and respect, it's always great when people act civil online, I try my best and hope I didn't come across rudely :) Best wishes!
