### ISSUE TITLE
Pi-hole cannot block a web subdirectory

### ISSUE THREAD

**Issue by trunglehuynh** [pi-hole/pi-hole#5758]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:   v5.21
- FTL:   v5.25.2

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  AWS

### Expected behavior

I want to block a subdirectory of a website but not a whole website, for exmaples:

- Unblock: facebook.com
- Block: facebook.com/images/<image_id>

### Actual behavior / bug

Pi-hole cannot block a subdirectory

### Steps to reproduce

1. Go to http://ip-address/admin/groups-domains.php
2. Click on 'Regular Filter'
3. Enter "facebook\.com/images/"
4. Add To Blacklist
5. I was able to open facebook.com/image/1234

### Tried

- I ran this command and learned that the regex matches URLs

"pihole-FTL regex-test www.facebook.com/images/dthnyB9Rd2Y facebook\.com/images/
[i] Compiling regex filter...
    Compiled regex filter in 0.029 msec

Checking domain...
    facebook.com/images/ matches
   Time: 0.008 msec
"

- I removed DNS caches on test devices but it does not resolve the issue.
- I was able to block a whole website but not block part of a website.

## Debug Token

- URL:   https://tricorder.pi-hole.net/7eEFCWgl/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
> I want to block a subdirectory of a website but not a whole website

This is not possible with Pi-hole.

Pi-hole only blocks **domain names**, not URLs.

![image](https://github.com/user-attachments/assets/4abf380f-97a5-4f14-951a-d459c2bf6f22)

**Comment by trunglehuynh** [comment]
@rdwebdesign do you have a code pointer of filter logic that I can fork and implement for my use case? thanks

**Comment by rdwebdesign** [comment]
This is impossible using a DNS filter, like Pi-hole.

Pi-hole will never be able to filter what you want.

When you try to access `www.example.com/directory/page`, your browser will need to know the IP of this domain (`www.example.com`): 

1. The browser will ask Pi-hole: "What is the IP of `www.example.com`?" (only the domain);

2. Pi-hole will check if `www.example.com` should be blocked:
    - If it should be blocked, Pi-hole will answer with `0.0.0.0`;
    - if it is allowed, Pi-hole will forward the query to the upstream DNS, receive an IP as answer and return this IP to the browser.

3. Then, the browser will request the `/directory/page` using the IP.

Only the browser knows the full URL. The URL is never sent to Pi-hole in step 1.

This is only possible using a browser extension.

**Comment by trunglehuynh** [comment]
@rdwebdesign thank you so much for the detailed explain, that makes sense to me now. Do you think a VPN can filter URLs too? thanks
