### ISSUE TITLE
lighttpd service won't start

### ISSUE THREAD

**Issue by Just8Will** [pi-hole/pi-hole#576]
##### Expected Behaviour:
lighttpd will run in the background to support pihole

##### Actual Behaviour:
lighttpd fails when pihole starts.

I ran `service lighttpd status` to check this. Trying to load the lighttpd daemon manually with `sudo service lighttpd start` and then checking the status produces the same output.
e.g.

> ● lighttpd.service - Lighttpd Daemon
>    Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
>    Active: failed (Result: exit-code) since Sat 2016-07-16 10:23:57 BST; 10s ago
>   Process: 5244 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
>   Process: 5242 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
>  Main PID: 5244 (code=exited, status=255)

Pihole itself seems to be working. Ads do not load on my network, but I cannot access the web interface.

The results of running pihole -d can be seen at:
http://termbin.com/fhru

##### Steps to reproduce this issue:
The web interface asked me to update and after much searching on how to do it I ran the installer again.
This caused the original issue. Then in an effort to fix it I have run `pihole uninstall` and then installed from scratch.

I'd appreciate some help or pointers to run more debugging in order to fix this. Al;though pihole is working it is much better with the web interface.

**Comment by brantje** [comment]
Can you paste the contents of the lighthttpd.conf?

**Comment by PromoFaux** [comment]
@brantje they're in the debug log :)

Hi there, thanks for providing the debug script! 

Interestingly... this line sticks out:
`Jul 16 10:23:57 raspberrypi lighttpd[5244]: 2016-07-16 10:23:57: (server.c.785) can't find username lighttpd` Which suggests something has gone wrong with the `lighttpd` install...

**Comment by PromoFaux** [comment]
You could try removing and then reinstalling `lighttpd` to see if that creates the proper user. I just tried this myself and it doesn't affect the pi-hole flavoured `lighttpd.conf`

`sudo apt-get remove lighttpd`
`sudo apt-get install lighttpd`

What I don't understand though is how running the install script over the top of your existing install broke things, as it's designed to detect that you already have it installed and update as necessary (Albiet you still have to go through the install dialogs, but we're slowly working towards a script that removes that bit.)

**Comment by Just8Will** [comment]
I've now tried removing and reinstalling lighttpd but that hasn't made any difference. could it be that the issue isn't with lighttpd itself but with something it requires in order to run properly as part of pihole?

**Comment by PromoFaux** [comment]
Well, `lighttpd` seems to be refusing to start because there is no user for it....

try `adduser lighttpd`

**Comment by Just8Will** [comment]
If I do it that way it requires me to set up a password, what should it be to allow pihole to use it?

**Comment by PromoFaux** [comment]
Good question... let me look into it

**Comment by Just8Will** [comment]
By the way thank you for your help with this. I'm a relative noob on pi and i'd have been completely stuck without help.

**Comment by PromoFaux** [comment]
:) we all start somewhere... I'm still a bit of a noob myself!

**Comment by PromoFaux** [comment]
`groupadd -g 208 lighttpd`
`useradd -u 208 -g lighttpd -d /var/www lighttpd`

**Comment by PromoFaux** [comment]
Failing that, it might be easier to re-flash your SD card with Raspbian and start from scratch.. as long as you are not using any other services on your pi!

**Comment by Just8Will** [comment]
always the way isn't it! I do of course use my pi for more than just pihole!

That didn't work.
I've been investigating the install and yum wasn't a found command in the install so I've installed yum.
When I actually do the install the yum lines say e.g. 

> :::    Checking for epel-release... Not found! Installing.... [-]  There are no enabled repos.
>  Run "yum repolist all" to see the repos you have.
>  You can enable repos with yum-config-manager --enable <repo>                                                              done!
> 

Whereas the install log says:

> ::: Checking Pi-Hole dependencies:
> :::    Checking for epel-release... Not found! Installing.... done!
> :::    Checking for bind-utils... Not found! Installing.... done!
> :::    Checking for bc... Not found! Installing.... done!
> :::    Checking for dnsmasq... Not found! Installing.... done!
> :::    Checking for lighttpd... Not found! Installing.... done!
> :::    Checking for lighttpd-fastcgi... Not found! Installing.... done!
> :::    Checking for php-common... Not found! Installing.... done!
> :::    Checking for php-cli... Not found! Installing.... done!
> :::    Checking for php... Not found! Installing.... done!
> :::    Checking for git... Not found! Installing.... done!
> :::    Checking for curl... Not found! Installing.... done!
> :::    Checking for unzip... Not found! Installing.... done!
> :::    Checking for wget... Not found! Installing.... done!
> :::    Checking for findutils... Not found! Installing.... done!
> :::    Checking for cronie... Not found! Installing.... done!
> :::    Checking for sudo... Not found! Installing.... done!
> :::    Checking for netcat... Not found! Installing.... done!
> :::
> ::: Stopping services... done.
> ::: Checking if user 'pihole' exists...
> ::: User 'pihole' already exists
> :::
> ::: Checking for existing base files...
> :::    Checking /etc/.pihole is a repo... not found!!
> :::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole... done!
> :::
> ::: Checking for existing web interface...
> :::    Checking /var/www/html/admin is a repo... not found!!
> :::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin... done!
> :::
> ::: Installing scripts to /opt/pihole... done.
> :::
> ::: Installing configs...
> :::    No dnsmasq.conf found.. restoring default dnsmasq.conf... done.
> :::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
> :::
> ::: Creating log file and changing owner to dnsmasq... done!
> :::
> ::: Installing pihole custom index page...
> :::     No default index.lighttpd.html file found... not backing up done!
> ::: Installing sudoer file... done!
> :::
> ::: Installing latest Cron script... done!
> :::
> ::: Preparing to run gravity.sh to refresh hosts...
> ::: Running gravity.sh
> :::
> ::: You are root.
> ::: Neutrino emissions detected...
> :::
> ::: No custom adlist file detected, reading from default file... done!
> :::
> ::: Existing pihole directory found
> :::
> ::: Getting raw.githubusercontent.com list... List updated, transport successful!
> ::: Getting adblock.gjtech.net list... List updated, transport successful!
> ::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
> ::: Getting sysctl.org list... List updated, transport successful!
> ::: Getting zeustracker.abuse.ch list... List updated, transport successful!
> ::: Getting s3.amazonaws.com list... List updated, transport successful!
> ::: Getting s3.amazonaws.com list... List updated, transport successful!
> ::: Getting hosts-file.net list... List updated, transport successful!
> ::: Getting raw.githubusercontent.com list... List updated, transport successful!
> ::: Getting ransomwaretracker.abuse.ch list... List updated, transport successful!
> :::
> ::: Aggregating list of domains... done!
> ::: Formatting list of domains to remove comments.... done!
> ::: 128236 domains being pulled in by gravity...
> ::: Removing duplicate domains.... done!
> ::: 103921 unique domains trapped in the event horizon.
> ::: Formatting domains into a HOSTS file...
> :::
> ::: Adding 10 adlist sources to the whitelist... done!
> ::: Running whitelist script to update HOSTS file.... 8 domains whitelisted!
> ::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
> :::
> ::: Cleaning up un-needed files... done!
> :::
> ::: Refresh lists in dnsmasq... done!
> ::: Configuring iptables for httpd and dnsmasq..
> 
> 

Is any of this relevant?

**Comment by Just8Will** [comment]
Also yum-config-manager is not a found command despite what the install says to do

**Comment by Just8Will** [comment]
The other major change I have made which had some effect was installing apache2.
Now when you load /admin int the web browser instead of saying connection refused it shows the text of the what i think is the index.php file without interpreting it.
e.g it shows plaintext - 

> <?php
>     require "header.html";
> ?>
> 
> <div class="row">
>     <div class="col-lg-3 col-xs-6">
>         
>         <div class="small-box bg-aqua">
>             <div class="inner">
>                 <h3 class="statistic" id="ads_blocked_today">---</h3>
>                 <p>Ads Blocked Today</p>
>             </div>
>             <div class="icon">
>                 <i class="ion ion-android-hand"></i>
>             </div>
>         </div>
>     </div>
>     
>     <div class="col-lg-3 col-xs-6">
>         
>         <div class="small-box bg-green">
>             <div class="inner">
>                 <h3 class="statistic" id="dns_queries_today">---</h3>
>                 <p>DNS Queries Today</p>
>             </div>
>             <div class="icon">
>                 <i class="ion ion-earth"></i>
>             </div>
>         </div>
>     </div>
>     
>     <div class="col-lg-3 col-xs-6">
>         
>         <div class="small-box bg-yellow">
>             <div class="inner">
>                 <h3 class="statistic" id="ads_percentage_today">---</h3>
>                 <p>Of Today's Traffic Is Ads</p>
>             </div>
>             <div class="icon">
>                 <i class="ion ion-pie-graph"></i>
>             </div>
>         </div>
>     </div>
>     
>     <div class="col-lg-3 col-xs-6">
>         
>         <div class="small-box bg-red">
>             <div class="inner">
>                 <h3 class="statistic" id="domains_being_blocked"><sup style="font-size: 30px">---</sup></h3>
>                 <p>Domains Being Blocked</p>
>             </div>
>             <div class="icon">
>                 <i class="ion ion-ios-list"></i>
>             </div>
>         </div>
>     </div>
>     
> </div>
> 
> <div class="row">
>     <div class="col-md-12">
>     <div class="box" id="queries-over-time">
>         <div class="box-header with-border">
>           <h3 class="box-title">Queries over time</h3>
>         </div>
>         <div class="box-body">
>           <div class="chart">
>             <canvas id="queryOverTimeChart" style="height: 247px; width: 466px;" width="932" height="494"></canvas>
>           </div>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>     </div>
> </div>
> 
> <div class="row">
>     <div class="col-md-6">
>     <div class="box" id="query-types">
>         <div class="box-header with-border">
>           <h3 class="box-title">Query Types</h3>
>         </div>
>         <div class="box-body">
>           <div class="chart">
>             <canvas id="queryTypeChart" style="height: 247px; width: 466px;" width="932" height="494"></canvas>
>           </div>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>     </div>
>     <div class="col-md-6">
>     <div class="box" id="forward-destinations">
>         <div class="box-header with-border">
>           <h3 class="box-title">Forward Destinations</h3>
>         </div>
>         <div class="box-body">
>           <div class="chart">
>             <canvas id="forwardDestinationChart" style="height: 247px; width: 466px;" width="932" height="494"></canvas>
>           </div>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>     </div>
> </div>
> 
> <div class="row">
>         <div class="col-md-4">
>       <div class="box" id="domain-frequency">
>         <div class="box-header with-border">
>           <h3 class="box-title">Top Domains</h3>
>         </div>
>         
>         <div class="box-body">
>           <table class="table table-bordered">
>             <tbody><tr>
>               <th>Domain</th>
>               <th>Hits</th>
>               <th>Frequency</th>
>             </tr>
>           </tbody></table>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>       
>     </div>
>     
>     <div class="col-md-4">
>       <div class="box" id="ad-frequency">
>         <div class="box-header with-border">
>           <h3 class="box-title">Top Advertisers</h3>
>         </div>
>         
>         <div class="box-body">
>           <table class="table table-bordered">
>             <tbody>
>               <tr>
>               <th>Domain</th>
>               <th>Hits</th>
>               <th>Frequency</th>
>               </tr>
>             </tbody>
>           </table>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>       
>     </div>
>     
>     <div class="col-md-4">
>       <div class="box" id="client-frequency">
>         <div class="box-header with-border">
>           <h3 class="box-title">Top Clients</h3>
>         </div>
>         
>         <div class="box-body">
>           <table class="table table-bordered">
>             <tbody><tr>
>               <th>Client</th>
>               <th>Requests</th>
>               <th>Frequency</th>
>             </tr>
>           </tbody></table>
>         </div>
>         <div class="overlay">
>           <i class="fa fa-refresh fa-spin"></i>
>         </div>
>         
>       </div>
>       
>     </div>
>     
> </div>
> 
> 
> <?php
>     require "footer.php";
> ?>
> 
> <script src="js/pihole/index.js"></script>

**Comment by Just8Will** [comment]
Ok I can't paste the actual thing it says. the comment system here interprets the code in a way my web browser isn't!

**Comment by brantje** [comment]
Try this ```sudo a2enmod php5```

**Comment by Just8Will** [comment]
ERROR: Module php5 does not exist!

**Comment by brantje** [comment]
Sorry forgot to add this one ```sudo apt-get install libapache2-mod-php5```
So now it becomes this:
```
sudo apt-get install libapache2-mod-php5
sudo a2enmod php5
```

**Comment by Just8Will** [comment]
OK the fist line on its own was enough. The second line said the module was already enabled (or something like that).

What I don't understand is how apache and php were no longer on my system!

Also how is it now working despite the fact that lighttpd is still broken in the same way as it was?

Thank you for your help though

**Comment by brantje** [comment]
To be honest, i have no clue. 
Maybe @PromoFaux can shine some light on this.
Glad it's working now

**Comment by PromoFaux** [comment]
Silly question... what distro are you running?

**Comment by Just8Will** [comment]
raspian jessie

**Comment by PromoFaux** [comment]
Did you install `yum` before or after you tried to update with the curl command?

**Comment by Just8Will** [comment]
I installed apache2, based on some info I googled about lighttpd errors, and then did a reinstall. This brought up the index.php file in my web browser as described above.
I then saw yum not found errors in the install so I installed yum and reinstalled pihole, giving the errors detailed above. This made no difference to the performance of pihole.
Then as per your instructions I installed php5. This made the difference and the admin console now displays properly.
However if I run `service lighttpd status` then I get the same errors as at the start of this process.

**Comment by PromoFaux** [comment]
Hmmm, it shouldn't have given yum errors for raspbian.. the yum stuff is only in there for Rhel/CentOS.

Short of messing your pi up any further... would you mind removing yum, and then running the install script again but with a `-x` switch on bash.

`curl -L https://install.pi-hole.net | bash -x` And then pastebin the full output...

**Comment by Just8Will** [comment]
http://pastebin.com/m0RwMTJF

There is no change in the way it is working. Lighttpd is not working but the web interface is.

**Comment by dschaper** [comment]
Hi, it looks like your install has the RedHat Linux package manager called `yum` installed, and that is causing the install script to act incorrectly. We can try a `sudo apt-get purge yum` and try again, however having `apache2` will also cause conflicts, as we use the `lighttpd` daemon and having two webservers is not a standard supported installation. We may be able to poke things into place, but lets first try getting that `yum` off the Pi.

**Comment by Just8Will** [comment]
But the lighttpd daemon doesn't work. That's my fundamental problem. Apache has taken over for the lighttpd daemon because the lighttpd daemon fails to launch. Now that I have removed apache I'm back where I was at the start. the web interface is broken.

**Comment by dschaper** [comment]
Okay, we can see what we need to do to fix that. If you've removed `yum` and `apache2` can you provide us with a fresh `pihole -d` so we can see what the current state of the Pi is?

**Comment by Just8Will** [comment]
http://termbin.com/6pe3

**Comment by dschaper** [comment]
Okay, and the output from `sudo ls -lac /var/log/lighttpd/`

**Comment by Just8Will** [comment]
> total 2124
> drwxr-xr-x  2 www-data www-data    4096 Jul 16 12:16 .
> drwxr-xr-x 10 root     root        4096 Jul 16 17:06 ..
> -rwxr-xr-x  1 www-data www-data  626047 Jul 16 12:16 access.log
> -rwxr-xr-x  1 www-data www-data 1507968 Jul 16 12:16 access.log.1
> -rwxr-xr-x  1 www-data www-data    7531 Jul 16 12:16 access.log.2.gz
> -rwxr-xr-x  1 www-data www-data     562 Jul 16 12:16 error.log
> -rwxr-xr-x  1 www-data www-data    2498 Jul 16 12:16 error.log.1
> -rwxr-xr-x  1 www-data www-data     516 Jul 16 12:16 error.log.2.gz

**Comment by dschaper** [comment]
Thanks, let me take a look and see if I can tell why `lighttpd` is unable to open the `error.log`. It looks like the file has the correct permissions.

**Comment by Just8Will** [comment]
Thank you for helping

**Comment by dschaper** [comment]
Sure, in your `/etc/lighttpd/lighttpd.conf` you have two lines that are contributing to the problems.

```
server.username             = "lighttpd"
server.groupname            = "lighttpd"
````

Those two lines should be:

```
server.username             = "www-data"
server.groupname            = "www-data"
```

Try correcting those two lines, and then `sudo systemctl restart lighttpd` and see if the web interface works.

**Comment by Just8Will** [comment]
Thanks That fixed it and lighttpd is running as well.

**Comment by dschaper** [comment]
Great! Good to hear.

**Comment by DarthKeizer** [comment]
@dschaper last comment fixed it for me
