### ISSUE TITLE
Disabling long-term statistics should not disalbe the database at all

### ISSUE THREAD

**Issue by loeffelpan** [pi-hole/pi-hole#5765]
### Versions

- Pi-hole:  5.18.3
- AdminLTE:  5.21
- FTL:  5.25.2

### Platform

- OS and version:  Fedora CoreOS 40

- Platform:  Docker

### Expected behavior
[Docs](https://docs.pi-hole.net/ftldns/configfile/#long-term-database-settings) allow to disable long-term statistics.
This should only disable long-term statistics in the database and keep it for network/client data and anything needed for pihole.

### Actual behavior / bug
But `MAXDBDAYS=0` or `DBFILE=` disable the database at all and produces the following error in the admin interface.

Long-term Data -> Query Log
![image](https://github.com/user-attachments/assets/0b1e577c-7233-4420-939f-ed853a762811)

Clients
![image](https://github.com/user-attachments/assets/f47c61c4-37ad-4caf-8066-8d2e7793efc7)

Tools -> Network
![image](https://github.com/user-attachments/assets/1375f992-5491-4df3-b6b0-ef7254770980)

### Steps to reproduce

1. Set `MAXDBDAYS=0` or `DBFILE=`
2. Go to admin interface and see error messages like described above.

## Debug Token

- URL:  https://tricorder.pi-hole.net/HvB20mT4/

**Comment by loeffelpan** [comment]
I just noticed, that `DBINTERVAL=5.0` also doesn't work and produces the same error messages like no database is available.

**Comment by loeffelpan** [comment]
This error is still present.
Any help would be very appreciated.

**Comment by yubiuser** [comment]
This should be fixed with v6. At least the `php` errors are gone and the web interface. However, the network table is not populated. Pinging @DL6ER if this could be changed, at least with the information that don't require long-term data.

**Comment by loeffelpan** [comment]
Thanks.
Network table filled would be nice. Is there any information from long term statistics associated with network data?

I think data from clients, groups and network are saved to the sqlite database and should be available regardings long term statistics are enabled or not.

**Comment by loeffelpan** [comment]
Didn't try v6 yet.
But I will take a look and file a new issue if needed.
Ä
