### ISSUE TITLE
upgrading procedure from recent versions advice

### ISSUE THREAD

**Issue by roscom** [pi-hole/pi-hole#577]
aside from the general comment on the pi-hole page with respect to upgrading from old versions, is there a simple procedure for upgrading from, say, 2.7.1 to 2.8.1, or is it just a re-install of each new version.

**Comment by Mcat12** [comment]
You just need to run `curl -L https://install.pi-hole.net | bash`.

**Comment by roscom** [comment]
Thank you.

Upgraded as noted.

Also found post upgrade that the number of domains being blocked has 
dropped from approx 103,000 to approx 64,000.

I had made no changes to the list of domains being blocked.

Is there a reason for the change?

Regards

Ross

**Comment by Mcat12** [comment]
Run `pihole -g` and check how many domains there are. If it is still low, run `pihole -d` and post the debug link.

**Comment by roscom** [comment]
Ran pihole -g.

Domains being checked now shows as over 104,000 which would be 
consistent with the numbers prior to upgrade.

Thank you.

**Comment by Mcat12** [comment]
You're welcome!
