### ISSUE TITLE
Duplicate output when updating FTL

### ISSUE THREAD

**Issue by compulsions** [pi-hole/pi-hole#5772]
### Versions
Core
    Version is v5.18.3-490-g0cf0b2ab (Latest: null)
    Branch is development
    Hash is 0cf0b2ab (Latest: 0cf0b2ab)
Web
    Version is v5.21-947-g05c286df (Latest: null)
    Branch is development
    Hash is 05c286df (Latest: 05c286df)
FTL
    Version is vDev-72bfc98 (Latest: null)
    Branch is development
    Hash is 72bfc983 (Latest: 72bfc983)

### Platform
- OS and version:  Debian 12
- Platform:  Raspberry Pi W Zero 2

### Expected behavior
Not have repeatable output when doing pihole -up

### Actual behavior / bug
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL binary already installed, verifying integrity...
  [✗] Remote binary is different, downloading...
  [i] FTL:              update available

  [✓] Detected AArch64 (64 Bit ARM) architecture
  [i] FTL binary already installed, verifying integrity...
  [✗] Remote binary is different, downloading...
  [✓] Downloading and Installing FTL
  [✓] Installing scripts from /etc/.pihole

### Steps to reproduce
Perform a pihole -up when there is an update available.

## Debug Token
- URL:  https://tricorder.pi-hole.net/lafcwxOC/

### Screenshots
![image](https://github.com/user-attachments/assets/b0e38867-dd2a-4682-8c7a-bea1ae9bffdd)

### Additional context
Is it possible to remove the following output
  [i] FTL binary already installed, verifying integrity...
  [✗] Remote binary is different, downloading...
   at the top when checking if the components are up to date and keep the other one?

**Comment by yubiuser** [comment]
Should be fixed by https://github.com/pi-hole/pi-hole/pull/5800
