### ISSUE TITLE
Exit code on failed updates (pihole -up) is 0 but should not

### ISSUE THREAD

**Issue by dagobert** [pi-hole/pi-hole#5774]
### Versions
 - Pi-hole version is v5.18.2 (Latest: v5.18.3)
 - web version is v5.21 (Latest: v5.21)
 - FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- OS and version:  Debian 12

- Platform:  VM

### Expected behavior

`pihole -up` should exit with non zero exit code on failed updates.

### Actual behavior / bug

Exit code is `0` eg. wwhen version check fails and therefor also update fails.

### Steps to reproduce

1. Execute `pihole -up` with no dns server set.
2. On failed update attempt execute `echo $?`

## Debug Token

 - URL: https://tricorder.pi-hole.net/cgSVYF5c/

### Screenshots

none

### Additional context

none

**Comment by dagobert** [comment]
Bump

**Comment by dagobert** [comment]
It is not resolved yet.

**Comment by yubiuser** [comment]
Where did you set no host? On the host or Pihole's configuration?

**Comment by yubiuser** [comment]
Should be fixed by https://github.com/pi-hole/pi-hole/pull/5803
