### ISSUE TITLE
Certificate problem installing from https

### ISSUE THREAD

**Issue by Tom999Hall** [pi-hole/pi-hole#578]
pi@raspberrypi:~ $ curl -L https://install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate is not yet valid
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

Worked OK using plain http

**Comment by dschaper** [comment]
We have been using CloudFlare as a CDN to help with the load. But all that is changing. Thanks to some awesome providers we are in the middle of building our own server infrastructure.  So no more CA chain problems. It's going to take a few days as I don't like to use scripts to build my servers, I prefer to do everything manually just to make sure it's secure. 

We've got a ton of tricks coming up to really show off our stuff, hang in there and enjoy the ride.

**Comment by dschaper** [comment]
Since this is a known issue and the resolution is in the error message I'm going to close out this issue. Feel free to add any more comments or concerns and we'll still respond.

Thanks
