### ISSUE TITLE
When update is available only for web interface, after upgrade check for latest version

### ISSUE THREAD

**Issue by compulsions** [pi-hole/pi-hole#5784]
### Versions
Core
    Version is v5.18.3-510-gc0e39087 (Latest: null)
    Branch is development
    Hash is c0e39087 (Latest: c0e39087)
Web
    Version is v5.21-984-gae728a16 (Latest: null)
    Branch is development
    Hash is ae728a16 (Latest: ae728a16)
FTL
    Version is vDev-d749dff (Latest: null)
    Branch is development
    Hash is d749dffb (Latest: d749dffb)

### Platform
- OS and version:  Debian GNU/Linux 12 (bookworm)
- Platform:  Raspberry Pi Zero W 2

### Expected behavior
When you perform an update and there is only a web interface version change, do a pihole -v at the end to verify that it is indeed upgraded to the latest version and there is nothing newer.

### Actual behavior / bug
  Only the following output is given:  
  [✓] Update local cache of available packages
  [✓] Checking for iproute2

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    update available
  [i] FTL binary already installed, verifying integrity...
  [i] Local binary up-to-date. No need to download!
  [i] FTL:              up to date

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'
  [i] Local version file information updated.

### Steps to reproduce
Perform pihole -up when there is only web version update available.
Check the output
No pihole -v done at the end to verify if it is indeed the latest version.

## Debug Token

- URL:  https://tricorder.pi-hole.net/70HhkHGS/

### Additional context

Is it possible to check for the latest version again at the end of an web interface version update?

**Comment by yubiuser** [comment]
Why not just run `pihole -v` manually?

**Comment by compulsions** [comment]
Well, of  course it can be done manually. but it will be easier to have it done automatically, plus today I did an update and after it it showed me the hash for web interface was different and turned out there is a update released during my upgrade

**Comment by rdwebdesign** [comment]
> it showed me the hash for web interface was different and turned out there is a update released during my upgrade

> Branch is development

You are running development branches. 
In this case it is normal to see new updates all the time.

This doesn't happen too often with stable releases.

**Comment by compulsions** [comment]
I do agree with the statement above and thought about it, just for consistency sake sometimes even in stable when a bug is found there are times where multiple updates are being released for a single component.

**Comment by yubiuser** [comment]
Should be fixed in v6 with https://github.com/pi-hole/pi-hole/pull/5788
