### ISSUE TITLE
Gui and CLI behave not the same REGEX

### ISSUE THREAD

**Issue by ugurtu** [pi-hole/pi-hole#5786]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.18.3
- FTL:  v5.25.2

### Platform

- OS and version:  Ubuntu 24.04 LTS

- Platform:  Raspberry Pi 5

### Expected behavior

If REGEX is disabled, I would expect, that `pihole -q` would also behave the same.

### Actual behavior / bug

If regex is disabled, `pihole -q` blocks query, but the GUI does not block it anymore! 

### Steps to reproduce

1. Add regex
2. Disable regex
3. Open terminal and run `pihole -q`
4. `pihole -q` says it is blocked, but in GUI it is not blocked!

### Debug Token
https://tricorder.pi-hole.net/BmefEgI0/

**Comment by rdwebdesign** [comment]
Please, include a debug log:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by ugurtu** [comment]
Here you go I just uploaded it, the debug token is now present in my edited issue

**Comment by rdwebdesign** [comment]
I tested using the same regex found in your debug log:

- Terminal: executing `pihole -q amazon.eu` returns: `Match found in regex blacklist`
- Web interface, ***Tools > Search Adlists***: if I search for `amazon.eu` it returns: `Match found in regex blacklist`

Exactly the same output in both cases. Internally ***Tools > Search Adlists*** uses `pihole -q`.


**NOTE:**

I think I understand your confusion.

> 4. `pihole -q` says it is blocked, but in GUI it is not blocked!

`pihole -q` doesn't really check if a domain is blocked or allowed. It's just a search tool.

It just says if a domain or regex is found in the database, but in Pi-hole v5 `pihole -q` doesn't check if the entry is enabled or disabled.

In Pi-hole v6 (already in development), the function will return only **enabled** entries.

**Comment by ugurtu** [comment]
Many thanks for your fast reply, the workaround for this is:

to delete the regex from the gravity.db! If somebody needs!
