### ISSUE TITLE
Conditional forwarding causes blocked queries to show up in upstream query log

### ISSUE THREAD

**Issue by jogger2510** [pi-hole/pi-hole#5795]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.21
- FTL:  v5.25.2

### Platform

- OS and version:  Linux pi400 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt2 (2024-10-01) aarch64 GNU/Linux

- Platform:  Raspberry Pi400

### Expected behavior

Upstream query logs should never contain blocked queries.

### Actual behavior / bug

With conditional forwarding blocked queries that would have been forwarded to the DHCP server show up in the respective upstream query log. 

### Steps to reproduce

1. Configure Conditional forwarding as documented
2. In the Dashboard click on "blocked" in the "Upstream servers" section, until a blocked query appears that would have gone to the DHCP server configured for Conditional Forwarding.
3. In the Dashboard click on the DHCP server configured for Conditional Forwarding in the "Upstream servers" section.
4. See the same blocked queries appear as in step 2.

## Debug Token

- URL:  https://tricorder.pi-hole.net/rJ1haxLl/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by DL6ER** [comment]
Could you provide some screenshots for us?

**Comment by jogger2510** [comment]
You see, the very same queries are shown under "blocked" as well as "upstream".![Image](https://github.com/user-attachments/assets/ea396c2f-89d3-433b-80c8-0de234cb1c97)
![Image](https://github.com/user-attachments/assets/e56b343d-9932-4f73-a284-304942f0e62a)

**Comment by rdwebdesign** [comment]
> ### Expected behavior
> 
> Upstream query logs should never contain blocked queries.

I just saw your last comment and screenshots.

The status `Blocked (external, NXRA)` means these 3 PTR queries were allowed by Pi-hole (that's why they were sent to the upstream server), but they were actually blocked by the "external" upstream server itself.

In other words: 
the PTR queries were allowed, sent upstream and answered by the upstream server as `0.0.0.0`. Then Pi-hole marked them as `blocked external`.

**Note:**
The other 3 `mask.icloud.com` queries are completely unrelated. They were blocked by Pi-hole and never sent upstream.

**Comment by jogger2510** [comment]
I See. Nevertheless there is a bug. You get to the query lists by clicking on the individual segments of the pie chart. A pie chart implies that the contents of the segments is mutually exclusive. But according to my screen shots "blocked external" is listed as "blocked" as well as "upstream". In my view then any upstream query should never be listed or counted in the "blocked" segment.

**Comment by DL6ER** [comment]
I don't think this is a bug any longer in the entirely rewritten new REST API of the upcoming Pi-hole v6.0. Also in the version you are seeing this is more of a cosmetic issue. Queries are counted correctly but the Query Log is somewhat imprecise in what it shows you. If you request "Blocked/external", it will show you only exactly these queries. If you request "Blocked", however, it collects and shows all the various types where the status is *somehow* being blocked.
