### ISSUE TITLE
CHIP computer latest install IPv6 tunnel, loss of internet connectivity 

### ISSUE THREAD

**Issue by CDeeRON** [pi-hole/pi-hole#580]
##### Expected Behaviour:

Fresh install of CHIP OS, Fresh install of Pi-Hole. Internet access from CHIP is impacted as the install of Pi-Hole enables the IPv6 tunneling. 

Linux chip 4.3.0-ntc #1 SMP Wed May 11 21:57:30 UTC 2016 armv7l GNU/Linux
##### Actual Behaviour:

Before:

root@chip:/scripts# ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:296 errors:0 dropped:0 overruns:0 frame:0
          TX packets:296 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:22768 (22.2 KiB)  TX bytes:22768 (22.2 KiB)

wlan0     Link encap:Ethernet  HWaddr 7c:c7:09:e0:71:9d  
          inet addr:10.25.101.20  Bcast:10.25.101.255  Mask:255.255.255.0
          inet6 addr: fe80::7ec7:9ff:fee0:719d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:53187 errors:0 dropped:629 overruns:0 frame:0
          TX packets:21812 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:73733097 (70.3 MiB)  TX bytes:2837510 (2.7 MiB)

After:
ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.25.101.20  Mask:255.255.255.0
          inet6 addr: fe80::341f:aaff:fef9:4c83/64 Scope:Link
          UP RUNNING NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:3 dropped:3 overruns:0 carrier:3
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:34 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2270 (2.2 KiB)  TX bytes:2270 (2.2 KiB)

sit0      Link encap:IPv6-in-IPv4  
          inet addr:10.25.101.20  Mask:255.255.255.0
          inet6 addr: ::127.0.0.1/96 Scope:Unknown
          UP RUNNING NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:66 errors:6 dropped:0 overruns:0 carrier:0
          collisions:6 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:4374 (4.2 KiB)

wlan0     Link encap:Ethernet  HWaddr 7c:c7:09:e0:71:9d  
          inet addr:10.25.101.20  Bcast:10.25.101.255  Mask:255.255.255.0
          inet6 addr: fe80::7ec7:9ff:fee0:719d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:178 errors:0 dropped:3 overruns:0 frame:0
          TX packets:178 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:28759 (28.0 KiB)  TX bytes:27543 (26.8 KiB)

If I `ifconfig sit0 down` then internet connectivity from CHIP is restored. However after a reboot `sit0` returns and internet is lost from CHIP computer. 
##### Steps to reproduce this issue:
1. Fresh install of CHIP os on a CHIP
2. Fresh install of Pi-Hole on CHIP
##

**Comment by PromoFaux** [comment]
@jacobsalmela Assigning you here because you're the only one of us with a CHIP!

**Comment by CDeeRON** [comment]
I just tested fresh install os and pi-hole using the 2.7.1 install script with no issue. I will dig into the differences between 2.7.1 and 2.8 and start pulling code to determine which is the culprit.

**Comment by PromoFaux** [comment]
Can you run a `pihole -d` on both 2.7.1 and 2.8.1 and paste up the links, please? Thanks!

**Comment by jacobsalmela** [comment]
K.  I'll try the latest install on my C.H.I.P., too.

**Comment by CDeeRON** [comment]
2.7.1  install script:  http://termbin.com/2ucm
2.8  install script: http://termbin.com/ox9x

**Comment by CDeeRON** [comment]
After a bunch of testing I've determined the new installer dependency `dhcpcd5`is causing the issue on CHIP os.

**Comment by jacobsalmela** [comment]
I'm not sure.  I'll have to look.  I'll pull out my C.H.I.P. this weekend.

**Comment by jacobsalmela** [comment]
Yep, weird it failed for me, too.  

I think `dhcpcd5` is part of the Fedora support..maybe @dschaper knows?

**Comment by dschaper** [comment]
Someone want to loan their C.H.I.P for testing purposes? :wink: I'll see what I can do.

**Comment by dschaper** [comment]
https://packages.debian.org/jessie/dhcpcd5 Since we write to DHCPCD for config, it's there to make sure our static config is there. Why a `sit` or any IPv4 in 6 tunnel is created is confusing. What is the C.H.I.P os based off of?

**Comment by CDeeRON** [comment]
Debian. I can setup remote access later today on a spare CHIP if that would help?

**Comment by dschaper** [comment]
Will have to co-ordinate that. Unless you'd like to trade that spare for a new Zero or something :wink:

**Comment by CDeeRON** [comment]
I would trade however I just received this spare and my next order of CHIPs won't arrive until Sept. I have a spare network completely separate of my home network I will move this CHIP to and setup remote access. Would you prefer I flash with fresh install of CHIP OS?

**Comment by dschaper** [comment]
Yes, a fresh New OOB set up would be great. 

Here's my PubKey
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdj7GVJ270wFOvBrO3+zirMrbHcARgWLrvSe1LB3CR3c3anJitfaJUw6KgsuQcZIWZplL5FxiFc5tQNREMgwNcXVQreg5X+722Nn5pukp9Uklv2eLsPTnXD4lvtAGOSJPfifKwxg/hQJLtl5K+iU9r3INbqdd/t0v1HufKPGO2QC/aH5rWc5l7xm5yLfBhyE3m0q08pUCxRGqgdZtcYQaIohok9DyZnRiL/mHqMK6GF5qs3mOp+DkzbPA0fJpClVI0pacCdPhVAi0YjtpCa6eymlx4vewn7nkFqc7TlkDwxFAJbzrVBX8Zl8jzRvYMDeJ4qGa7poI22wdBtKV9NfCx djsch@ANDROMEDA
```

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/17093872/c74134a4-5243-11e6-808d-c5847358ca60.png)
Whoops!

**Comment by dschaper** [comment]
I was looking, what's the ship window though? I've got just about every other SBC out there, might as well add the C.H.I.P.

**Comment by CDeeRON** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/5178468/17094118/35c01f68-521b-11e6-9ba6-4e333fa3eb84.png)

What they sent me for ship windows.

**Comment by dschaper** [comment]
Hmm, I got lucky on the Pine64 KS and got fast shipping from that. I'll order one, but how my shipping is more expensive than Promofaux's I don't know?

**Comment by CDeeRON** [comment]
@dschaper give it a try 174.110.147.79

**Comment by dschaper** [comment]
I'm getting a password request. If you want, email me at dschaper@ganymeade.com and we can figure that part out.

**Comment by CDeeRON** [comment]
User was from dschaper instead of djsch as mentioned in the key. 
From log
`Invalid user dschaper `

**Comment by dschaper** [comment]
`djsch@174.110.147.79's password:`

**Comment by CDeeRON** [comment]
try one more time changed the hostname in authorized_keys to your ip

**Comment by dschaper** [comment]
Okay, still getting a pass prompt. 

Here's a new gen'd key if that other one was giving problems, RSA 4096 bits. 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdxP9f9yHdH5CDuBEF1o5tzg7wBWWIl7/L1Q07hrxobZQEJ0BzipatrWRfg1udSLtMtHPpfZPAUTBuAMQYIpntymAwuxq9vxCiF/bODlSczfQZU1llIpLbIeikxxssBAlrGhJRY2hmq33kAuzdHBTqyDhR+9mtumhwGp46263j0QCWyWP8sVeTDIBRqC4SsDK7v0jhHa0KrzysUiTcQdblJtTsW937j3u2uOWMXDrRjvlvAO8zsQu2XvmhPHYnykXEute87a+RCMA8q9ivt3fm/eVzQ65Tl6tmniTqE8Z63+Vl0i26d8IAACA+dNjoJgx4fWuHDQvlnHTB7vgyRcqc+NGI+igatIR/dHGA+y6xUXWvLD/3Ca1tJY070HbLnUQS8QkP9RvCDtwTNwk6UL482fVVzwarKdCUtc+reGTegzlKgEtfaafFt563mPhT/p9MWTq2GrbvayEfoOr+iO/IoOaotpGcDfP7r/rjeQJUVqP7D9p5VNu48NDzLRQXzayAtdTrg9FTS0DqVpp66nwWjYtkhmgVF+bg6GlE6AtTwA0xx5smLx8U8280kU4LKlghljaOiiF6QyTNbkVNxmJBI/5wgfb2RaxlOl9iihy1rowbTLPBq7e1L2WLPVA1kU/qIHVly3jndCuBUOGZFQumQcDvIlM3+pQYI+Hk9RmPTw== C.H.I.P Test Key
```

**Comment by CDeeRON** [comment]
try now

**Comment by dschaper** [comment]
Still password, removed my config in case I was requesting kex algo's that were too strict just in case, but doesn't look to be that.

**Comment by CDeeRON** [comment]
Just sent you an email.

**Comment by dschaper** [comment]
Okay, I've got a CHIP waiting for me at home courtesy of Jacob, so I'll hack away on that and do some more destructive code tests. Thanks for the usage of your CHIP @CDeeRON, you can take it offline now, I didn't want to have to keep bugging you to reflash the OS because I'm guessing we're going to be breaking a few things to get a working solution.

**Comment by CDeeRON** [comment]
@dschaper no problem at all.  If I can help in anyway please reach out. I don't mind testing or digging into to the code.

**Comment by dschaper** [comment]
@CDeeRON Thanks! I was at home for a few and got a look at the CHIP. Very nice little thing! I'll update when I find something. :)

**Comment by dschaper** [comment]
Okay, uses NetworkManager, which doesn't play nice with the other kids on the block. Looks like this is going to be an exception/edge-case issue. 

```
root@chip:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
BUILD_ID=Wed Jun  1 05:34:36 UTC 2016
VARIANT="Debian on C.H.I.P"
VARIANT_ID=SERVER
```

**Comment by CDeeRON** [comment]
My thought was to add to the distro if;then checker in the install script?

**Comment by dschaper** [comment]
If we go the CentOS route, and detect `nmcli` and Jessie then we could generate a config script and have `nmcli` load that static config. Other option is to kill NetMan. Either way I'm still trying to figure out why adding the `dhcpcd5` package would cause breakage if it's not used. NetMan should just ignore.

**Comment by dschaper** [comment]
May be something else, I have `apt install dhcpcd5` and rebooted, no tunnel yet. Just looks like `dhchcd5` took over the duties of listening for IPv6 RA's and IPv4 DHCP leases from NetManager. Do either of you have native IPv6 capabilities? (I do, wondering if my native is blocking out the tunnel.) Have it up with the serial TTL interface so I can check the boot process.

**Comment by dschaper** [comment]
@CDeeRON On your affected CHIP, can you get me the output of `nmcli dev`? That will show some of what is going on.

**Comment by CDeeRON** [comment]
I've fixed my CHIPs by removing `dhcpcd5` from the install script or `apt-get remove dhcpcd5` afterwards.

`root@chip:/scripts# nmcli dev
DEVICE   TYPE      STATE      CONNECTION 
sit0     sit       connected  sit0       
wlan0    wifi      connected  heyyou     
ip6tnl0  ip6tnl    unmanaged  --         
lo       loopback  unmanaged  --         
wlan1    wifi      unmanaged  --         
`

`root@chip:/scripts# lsmod
Module                  Size  Used by
8723bs               1428634  0 
bnep                   13579  2 
cfg80211              498231  1 8723bs
hci_uart               56774  1 
btbcm                   7251  1 hci_uart
btintel                 3772  1 hci_uart
cmac                    3111  0 
ecb                     2426  0 
bluetooth             508285  23 bnep,btbcm,hci_uart,btintel
tca8418_keypad          4546  0 
usb_f_acm               8388  1 
u_serial               13753  3 usb_f_acm
g_serial                4133  0 
libcomposite           54530  2 usb_f_acm,g_serial
configfs               31307  3 usb_f_acm,libcomposite
fuse                   91882  1 
`

**Comment by dschaper** [comment]
Thanks, and you're flashing with 4.3 or 4.4? I'm trying just a bare flash with 4.4, setting up Wlan0 with nmtui via command line and then curling to see what comes up. I'll try IPv4 w/6, w/out6 and 6 only and see what comes up.

**Comment by CDeeRON** [comment]
4.3

**Comment by CDeeRON** [comment]
@dschaper I'm testing a fix for this

```
elif [ -x "$(command -v nmtui)" ];then
        # CHIP Debian Family
        PKG_MANAGER="apt-get"
        PKG_CACHE="/var/cache/apt"
        UPDATE_PKG_CACHE="$PKG_MANAGER -qq update"
        PKG_UPDATE="$PKG_MANAGER upgrade"
        PKG_INSTALL="$PKG_MANAGER --yes --quiet install"
        PKG_COUNT="$PKG_MANAGER -s -o Debug::NoLocking=true upgrade | grep -c ^Inst"
        INSTALLER_DEPS=( apt-utils whiptail )
        PIHOLE_DEPS=( dnsutils bc dnsmasq lighttpd php5-common php5-cgi php5 git curl unzip wget sudo netcat )
        LIGHTTPD_USER="www-data"
        LIGHTTPD_GROUP="www-data"
        LIGHTTPD_CFG="lighttpd.conf.debian"
        package_check() {
                dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -c "ok installed"
        }

```

**Comment by CDeeRON** [comment]
Will also need to add to function `setStaticIPv4`


```
	elif [ -x "$(command -v nmtui)" ];then
                # CHIP Debian Family
                        $SUDO ip addr replace dev "$piholeInterface" "$IPv4addr"
                        echo ":::"
                        echo "::: Setting IP to $IPv4addr.  You may need to restart after the install is complete."
                        echo ":::"
```

Or Maybe put in a blurb about the need to use `nmtui` to set static since CHIP uses NetworkManager

**Comment by dschaper** [comment]
The only gotcha's are that CentOS/RHEL use `nmtui` as well. Still testing things, got called out so I haven't had a chance to run tests. From what I did get to do, if I install `dhcpcd5` on its own before curling, then I don't run into issues, but if it's part of the script then a few different behaviors popped up. I just haven't figured out why `dhcpcd5` causes a tunnel. I did see `dhclient` which is part of `dhcp3` hearing RA's along with `dhcpcd` which could cause a race condition.

**Comment by khromov** [comment]
Having similar problems with loss of internet connectivity. Pi Hole sets up a new static network sit0 instead of configuring the existing wlan0 network. Two networks with same IP = loss off connectivity.

I would like to decline the step to configure static IP completely but it doesn't seem possible.

**Comment by dschaper** [comment]
Just as a personal comment, as I move more and more to DHCP reservations instead of setting statics wherever possible I'm wondering about the concept of requiring statics. Part of me would like to set reservations, but then something like a DNS resolver could make a good argument for static. 

I think the user base that would know about reservations and the configurations that requires would be able to adjust the install to fit their needs, and our origins are in a project that has the ability to go from fresh Raspbian to full Adblocker without the need for extra knowledge. 

I'm interested to hear others thoughts on that.

**Comment by dschaper** [comment]
And yes, I still have the CHIP, but the flashing process is quite time consuming and I'm stepping though things while trying to find what exactly is triggering the interface confusion, which means very frequent flashing.

**Comment by CDeeRON** [comment]
@dschaper I think the question needs to be asked is Pi-Hole only supporting Raspbian and Raspberry Pi hardware? Or moving to be a universal ad-blocker supported on other distros and hardware. If the path is to be supported cross distros and hardware I would vote removing the setting of static ip functions in the install script.

**Comment by Mcat12** [comment]
Just jumping in here, but Pi-hole's definitely not limited to just Raspbian or Raspberry Pis! Theoretically, you might even be able to install it on Windows with the anniversary update... ;)

**Comment by zeroprime790** [comment]
any update on the dhcpcd5 issue? I'm having the same problem and running OS 4.4

**Comment by CDeeRON** [comment]
@zeroprime790  run `apt-get remove dhcpcd5`  this will provide a temporary fix until you upgrade to a new release of pi-hole.

**Comment by zeroprime790** [comment]
@CDeeRON than you for your answer. I have already did that and installed the latest version but it doesn't seem to fix this issue.  The installation require dhcpcd5 module for the installation. 
When the installation finished,  sit0 and wlan1 interfaces created and caused IP conflict as it used wlan0 IP.  I uninstalled once more the dhcpcd5 and now my connection is restored. Although this is not a solution. Why this module takes over and mess everything?

**Comment by CDeeRON** [comment]
Has something to do with CHIP os using network manager. I believe the pihole project owners are working on a permanent solution.

**Comment by dschaper** [comment]
Okay, I hear you all, `dhcpcd5` on a non-Raspbian install will cause abominations to befall the C.H.I.P. (That OS install process is a GGrrrr inducer though, browser based OS install???) We need to look at pulling out `dhcpcd5` from anything that isn't Raspbian, and go with the default dhcp client. (Believe that is isc-dhcp-client?) We also need to take a look at how we assign static IP's, or if we want to observe and determine if there can be a reserved lease on the DHCP server and progress that way. This will take time to resolve.

**Comment by jacobsalmela** [comment]
The C.H.I.P. is neat, but is very difficult for us to support as we try to scale Pi-hole into something bigger.  For now, we are dropping support for C.H.I.P.s.
