### ISSUE TITLE
Inconsistent Behavior with Whitelist from Admin GUI

### ISSUE THREAD

**Issue by dbec** [pi-hole/pi-hole#581]
##### Expected Behaviour:

In the admin gui, when a domain is removed from the whitelist, it is removed from /etc/pihole/whitelist.txt _and not added to gravity.list_. 
##### Actual Behaviour:

In the admin gui, when a domain is removed from the whitelist, it is removed from /etc/pihole/whitelist.txt _and also added to gravity.list_. 
##### Steps to reproduce this issue:

Add a domain to whitelist
Confirm domain is added to end of /etc/pihole/whitelist.txt on container
Remove domain from whitelist via red garbage can icon on the right
Domain is removed from list in the GUI
Domain is no longer in whitelist.txt
However, domain is added to end of gravity.list (?!), causing the domain to be "pi-holed"

Refer to here for further notes:
https://github.com/diginc/docker-pi-hole/issues/23
##

**Comment by PromoFaux** [comment]
> However, domain is added to end of gravity.list (?!), causing the domain to be "pi-holed"

Surely if you've removed a domain from the whitelist... you want it to be pi-holed?

When I did the whitelist/blacklist scripts, my thinking at the time was that you're only going to whitelist domains that are actually in `gravity.list` in the first place. Makes sense, right? The only reason you'd whitelist a site that _wasn't_ already blocked would be just in case it was to ever appear on a blocklist.

Now, let's say you no longer want that domain whitelisted... Working on the theory that the domain was removed from `gravity.list`, it needs to go back on there in order for it to no longer be whitelisted... the opposite of it being whitelisted is in-fact the domain being pi-holed.

Is there a reason why you would want a domain to be no longer whitelisted, but yet not blocked?

That all said, adding it back in is only meant as a temporary measure until the next run of `pihole -g`, either manually or when it runs automatically on a Sunday, which will reset `gravity.list` to more accurately reflect the lists pulled in.

**Comment by diginc** [comment]
> When I did the whitelist/blacklist scripts, my thinking at the time was that you're only going to whitelist domains that are actually in gravity.list

I agree un-whitelisting blocked domains should behave the way it is currently implemented, so maybe it just needs to behave differently when un-whitelisting benign domains.  

Mistakes happen, domains may get added without needing to be on the whitelist, or just to test if whitelisting 'google.com' works through the GUI...then you don't need it anymore so you remove it...uh oh now it broke :(

**Comment by PromoFaux** [comment]
I wonder...

a) Have a "master" copy of `gravity.list` to be referred to in cases like this (downside, takes up more space...)
b) Check for the un-whitelisted domain in the `list.X...` files. If it's in them, add it back to `gravity.list` else.. don't.

**Comment by Mcat12** [comment]
With the python rewrite, we could just query the `unformatted_domains` table for the domain. That table acts like a huge list of all the domains and what list they came from, including duplicates.

**Comment by jacobsalmela** [comment]
Fixed by #584
