### ISSUE TITLE
Temporarily disabling and manually re-enabling blocking does not clear the timer

### ISSUE THREAD

**Issue by Flybel** [pi-hole/pi-hole#5810]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.21
- FTL:  v5.25.2

### Platform

- OS and version:  Debian GNU/Linux 12 (bookworm)

- Platform:  Raspberry Pi (via https://github.com/pivpn/pivpn)

### Expected behavior

When I temporarily disable blocking, then manually re-enable it and disable blocking again, all before the timer runs out, blocking should be disabled for the time set when I last disabled blocking (possibly indefinitely). This can occur when I know before the set timer runs out (and blocking is re-enabled automatically) that I will require blocking to be disabled for longer than originally specified.

### Actual behavior / bug

When I temporarily disable blocking, then re-enable it and disable it again (either permanently or temporarily for longer than the time remaining on the first timer), blocking is re-enabled when the first timer runs out. It is as if manually re-enabling blocking does not clear the timer. This causes unwanted blocking.

### Steps to reproduce

Method A:

1. On the web interface, click on 'Disable Blocking' and choose a preset or custom time duration
2. Click on 'Enable Blocking' before the time runs out
3. Click on 'Disable Blocking' and choose any duration (longer, including indefinitely) before the original (now invisible) timer would have ended
4. Refresh the page after the original timer would have ended, and find the new timer to be gone, the button 'Enable Blocking' having changed to 'Disable Blocking' again; confirm that blocking has been re-enabled by trying to access blocked domains

Method B:

1. On the host command line, run 'pihole disable \<short duration\>'
2. Run 'pihole enable' before the time runs out
3. Run 'pihole disable' or 'pihole disable \<longer duration\>' before the time would have run out
4. Run 'pihole status' before the original timer would have run out and confirm Pi-hole blocking is disabled
5. Run 'pihole status' after the original timer would have run out (and before the new timer, if one has been set, runs out) and confirm Pi-hole blocking is enabled

The behavior is cascading, so this can be continued (disable for timer 1, re-enable, disable for timer 2, wait until timer 1 runs out, disable for timer 3, wait until timer 2 runs out, disable for timer 4, ...).

## Debug Token

- URL:  https://tricorder.pi-hole.net/hNcCDJ2p/

### Additional context

This essentially matches #3829 but is not limited to the web interface, or a custom timer followed by the indefinite option.

**Comment by yubiuser** [comment]
This should be fixed in v6 with https://github.com/pi-hole/FTL/pull/2011
