### ISSUE TITLE
Failure to update FTL on Raspbian 10

### ISSUE THREAD

**Issue by CarbideCarGuy** [pi-hole/pi-hole#5816]
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.21
- FTL:  v5.25.1

### Platform

- OS and version:  Raspbian 10

- Platform:  Raspberry Pi Zero W

### Expected behavior

_A clear and concise description of what you expected to happen._

Ran pihole -u to update pihole version and FTL version 

### Actual behavior / bug

pihole -up returned an error for FTL, unable to update due to unsupported OS. Pihole updated successfully

  [✗] Unsupported OS detected: Raspbian 10
      If you are seeing this message and you do have a supported OS, please contact support.

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

  Unable to complete update, please contact Pi-hole Support

### Steps to reproduce

1. Go to cmd ssh and log into ssh
2. run pihole -up, 
3. See error
4. run sudo pihole_skip_os_check=true pihole -r
5. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/pvGvP7NR/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by DL6ER** [comment]
> 4. run sudo pihole_skip_os_check=true pihole -r

Did you run the *exact* same command as suggested by the error text or what you have typed here? Note that capitalization matters!

> If you are seeing this message after having run pihole -up:
> ```
> sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
> ```
