### ISSUE TITLE
site being pi-holed when it shouldn't be

### ISSUE THREAD

**Issue by roscom** [pi-hole/pi-hole#582]
##### Expected Behaviour:

browsing to smh.com.au should show the main page of the site
##### Actual Behaviour:

Lighttpd placeholder page is displayed instead

behaviour appeared after upgrading to 2.8.1

pihole -d results: http://termbin.com/v7cy
##### Steps to reproduce this issue:

Browse to smh.com.au

url is neither whitelisted nor blacklisted yet shows in the log as being pi-holed - see screen shot.

![selection_102](https://cloud.githubusercontent.com/assets/406562/16970677/30b4a510-4e61-11e6-9d8e-edd0b7d90bbc.png)
![selection_101](https://cloud.githubusercontent.com/assets/406562/16970678/30b5b4e6-4e61-11e6-997f-236fe8478871.png)
##

**Comment by Mcat12** [comment]
If it is being blocked without being blacklisted, then it seems that it must appear on one of the ad lists. To whitelist it, run `pihole -w smh.com.au`. If parts of it or all of it is still blocked, check out [this tool](https://chrome.google.com/webstore/detail/whitelist-assistant-by-dn/fdmpekabnlekabjlimjkfmdjajnddgpc?hl=en) to whitelist the correct domains. Also, that placeholder page should have been renamed when you installed Pi-hole. Since it seems like somehow it wasn't, you can either delete the file at `/var/www/html/index.lighttpd.html` or rename it to something like `index.lighttpd.orig`.

**Comment by diginc** [comment]
#581 related?  I see you had it green right before it was pi-holed in your screenshot.  did you un-whitelist it?

**Comment by Mcat12** [comment]
Ah, good catch @diginc

**Comment by roscom** [comment]
Thanks.

whitelisted the site. Used the Whitelist Assistant to add a few other 
urls. Renamed the index page as suggested.

Restarted pi-hole just incase.

However, no change. smh.com.au (which is a big site) is still being 
pi-hole'd.

I see you have noted it as a possible bug.

Added the debug output which may be found at http://termbin.com/y9v5

Regards

**Comment by diginc** [comment]
I think the output of `grep 'smh.com.au' /etc/pihole/*` maybe valuable.

**Comment by roscom** [comment]
```
pi@cb-7:~ $ egrep -i 'smh\.com\.au' /etc/pihole/*
/etc/pihole/whitelist.txt:smh.com.au
/etc/pihole/whitelist.txt:www.smh.com.au
pi@cb-7:~ $
```

**Comment by diginc** [comment]
`PWD=/var/www/html/admin/php ; USER=root ; COMMAND=/usr/local/bin/pihole -w -q -d smh.com.au`

from your pihole debug output matches the command (the removal from whitelist CMD) I used to reproduce the #581 issue when it was brought to my attention in this issue : https://github.com/diginc/docker-pi-hole/issues/23

```
root@90dab8d5adbc:/# sudo pihole -w -q -d issue23.github
root@90dab8d5adbc:/# grep 'issue23' /etc/pihole/*
/etc/pihole/gravity.list:192.168.41.55 issue23.github
```

It is strange you do not have smh.com.au in gravity.list...I expected to see that in the the grep result.

I think a work around maybe adding the domain to your blacklist and then removing it again.

**Comment by roscom** [comment]
no chance it is a cached version in lighttpd. cleared the cache out.

removing the whitelisted pages via the gui trashcan doesn't actually remove them from whitelist.txt (deletions are not persisted). that file has to be manually edited to clear them.

adding the url to the blacklist results:
```
pi@cb-7:~ $ egrep -i 'smh\.com\.au' /etc/pihole/*
/etc/pihole/blacklist.txt:smh.com.au
/etc/pihole/blacklist.txt:www.smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 www.smh.com.au
pi@cb-7:~ $
```
I assume you mean removing the entries from the blacklist via the gui. sorry to say but that doesn't work either. appears to work but the changes are apparently not persisted.

results prior to removal from balcklist via trashcan:
```
pi@cb-7:~ $ egrep -i 'smh\.com\.au' /etc/pihole/*
/etc/pihole/blacklist.txt:smh.com.au
/etc/pihole/blacklist.txt:www.smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 www.smh.com.au
```

results following trashcan removal from black list:
```
pi@cb-7:~ $ egrep -i 'smh\.com\.au' /etc/pihole/*
/etc/pihole/blacklist.txt:smh.com.au
/etc/pihole/blacklist.txt:www.smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 smh.com.au
/etc/pihole/gravity.list:192.168.38.103 www.smh.com.au
pi@cb-7:~ $
```
Hope this helps...

**Comment by diginc** [comment]
If the trash button doesn't work you should be able to directly delete from the blacklist with the command:

```
sudo pihole -b -d smh.com.au www.smh.com.au
```

**Comment by PromoFaux** [comment]
@diginc 
>#581 related?

Just FYI, removing a domain from the whitelist is supposed to do that!

**Comment by PromoFaux** [comment]
@roscom Are you still having trouble with this? I just tried to access the site now and it's not blocked for me...

Might be worth running `pihole -g` to refresh the gravity list if it's still persisting...

**Comment by roscom** [comment]
Yes, unfortunately, the problem persists, even after pihole -g has been run.

**Comment by jacobsalmela** [comment]
@roscom can you please verify whether or not this is still an issue on the latest version?

**Comment by dschaper** [comment]
Closing no response.

**Comment by benwiggins** [comment]
This is still an issue as of v2.12.1. I see it sporadically every week or so. 

When the bug hits, all main Fairfax newspaper websites are affected (smh.com.au, brisbanetimes.com.au, theage.com.au, watoday.com.au) simultaneously so it doesn't look like anything to do with smh.com.au directly.

**Comment by dschaper** [comment]
Stale, closing. Please reopen if problem continues.
