### ISSUE TITLE
Installer fails to install prerequisites (fedora / dnf)

### ISSUE THREAD

**Issue by acavella** [pi-hole/pi-hole#5838]
### Versions

- Pi-hole:  Latest
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Fedora Server 41 (aarch64)

- Platform:  Raspberry Pi 4

### Expected behavior

Installer executes, checks for and installs missing prerequisites.

### Actual behavior / bug

Installer executes, indicates all prerequisites have been satisfied which is not valid and missing prereqs are not installed causing installation to fail. In the pasted example below, the installer indicates 'git' has been found and installation fails due to it not being installed.

### Steps to reproduce

Execute the following command: `curl -sSL https://install.pi-hole.net | bash`

## Debug Token

NA

### Screenshots

```
[root@rpi4-001 acavella]# curl -sSL https://install.pi-hole.net | bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✗] Default SELinux: enforcing
  [✗] Current SELinux: enforcing
  [i] SELinux Enforcing detected. PIHOLE_SELINUX env variable set - installer will continue

  [i] Checking dnf for upgraded packages...Updating and loading repositories:
Repositories loaded.
  [✓] Checking dnf for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for bind-utils

  [✓] Supported OS detected
  [i] Checking for / installing Required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for dialog
  [✓] Checking for iproute
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for chkconfig
  [✓] Checking for ca-certificates

  [i] Using interface: end0
  [i] IPv4 address: 10.0.3.10/24
  [i] Unable to find IPv6 ULA/GUA address
  [i] IPv6 address:
  [i] Using upstream DNS: Cloudflare (DNSSEC) (1.1.1.1, 1.0.0.1)
  [i] Installing StevenBlack's Unified Hosts List
  [i] Installing Admin Web Interface
  [i] Installing lighttpd
  [i] Query Logging on.
  [i] Using privacy level: 0
  [✗] Check for existing repository in /etc/.pihole
  [i] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole...
  Error: Could not update local repository. Contact support.
[root@rpi4-001 acavella]# git
bash: git: command not found
```

### Additional context

_Add any other context about the problem here._

**Comment by acavella** [comment]
1. Unable to pull logs, the installer seems to fail without creating any install log.
2. Installed all prerequisite software manually (lighttpd, php, etc..). Once installed I was able re-run the install script successfully.

**Comment by randomap** [comment]
Im running into a similar issue. The installer just exits after lighttpd is enabled.

![Image](https://github.com/user-attachments/assets/22d94548-15bc-4ce2-8f6a-12de91e03fc5)

I'm not really sure what is wrong.

**Comment by randomap** [comment]
> This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:
> 
> https://discourse.pi-hole.net/t/pi-hole-install-terminates-without-error-when-restarting-lighttpd-on-fedora-41/74795/4

That forum post links to here. Its like the spiderman meme. But we are all having the same problem

**Comment by yubiuser** [comment]
If you watch the log output, you'll see, that the installation aborts at a different location and for a different  reason.
@acavella has an issue with cloning the repos due to missing `git`. @randomap could not enable `lighttpd`

**Comment by PromoFaux** [comment]
> that solution posted didnt work for me.

No solution posted yet - that's just a link that gets automatically generated when a Github Issue is linked to from our forum.

**Comment by PromoFaux** [comment]
Comparing between Fedora 40 and 41, I see there is a new version of `dnf` - which is entirely changing the expected output when a package is not installed.

41 on the left, 40 on the right:

![Image](https://github.com/user-attachments/assets/f56a1422-59e7-46ad-8464-f657432ec05f)

What is happening in the case of both reports here is that the installer is seeing the `exit 0` from dnf and taking that to mean that the package is already installed - so it doesn't attempt to actually install the dependency. 

Please hold for a workaround...

**Comment by yubiuser** [comment]
The fix is easy, see https://github.com/pi-hole/pi-hole/pull/5813

**Comment by PromoFaux** [comment]
Ah yes, https://github.com/pi-hole/pi-hole/pull/5839 will fix this. We'll get a hotfix out.

In the meantime, if you want to install v5 on Fedora 41, the workaround is to install the dependencies manually _before_ running the installer:

```
dnf install -y grep bind-utils git dialog iproute newt procps-ng chkconfig ca-certificates cronie curl findutils sudo unzip libidn2 psmisc libcap nmap-ncat jq lighttpd lighttpd-fastcgi php-common php-cli php-pdo php-xml php-json php-intl
```

An alternative workaround is to install the pre-release of v6, in which this issue is already fixed. Alternative install instructions to go straight to v6 (thus skipping the need for `lighttpd` and `php`) are:

```
dnf install git
git clone https://github.com/pi-hole/pihole /etc/.pihole
git clone https://github.com/pi-hole/web /var/www/html/admin
mkdir /etc/pihole
echo "development" > /etc/pihole/ftlbranch
cd /var/www/html/admin && git checkout development
cd /etc/pihole && git checkout development
./automated\ install/basic-install.sh
```

(Depending on users etc, you may need to preface these commands with `sudo`)

**Comment by PromoFaux** [comment]
v5.18.4 is now tagged which fixes this issue for Fedora 41 https://github.com/pi-hole/pi-hole/releases/tag/v5.18.4
