### ISSUE TITLE
pihole.log to SQLite DB

### ISSUE THREAD

**Issue by LarsTi** [pi-hole/pi-hole#585]
Hey there,

it's not an issue, more a feature request i can not handle myself due to lack of github knowledge.

I created a python script which is running continously in background and reads permanent the pihole.log file and creates a database named pihole.log.db.

I hope you will find it useful.

I added the python script to the crontab of root. The Script needs rights to write to /var/log/ (cause the db is created in /var/log/pihole.log.db).

I attached the python file to this issue (its in *.txt so it can be uploaded, rename it to *.py).
Please ensure you add the correct ipv4 value and ipv6 value for your pi :)

Cheer up your day :)
[dnsToDb.txt](https://github.com/pi-hole/pi-hole/files/374443/dnsToDb.txt)
##

**Comment by dschaper** [comment]
Thanks! We'll take a look. Trying to remember if there is a Python module or library for `dnsmasq` log scraping?

**Comment by LarsTi** [comment]
I did not find any way to log dnsmasq directly to another destination than a syslog facility.
If you are deeply enough in linux, you might use a virtual file and redirect the output to a python stream.. Though i am not sure and not capable to manage this.

**Comment by dschaper** [comment]
We'd leave the log to file as is, don't want to mess with that quite yet. But you've done the heavy lifting part of creating the parser so thanks a ton for that!

**Comment by jacobsalmela** [comment]
We have a [database feature request](https://discourse.pi-hole.net/t/database-for-logs/227) that's votable.  We also have some database stuff in development for [Core](https://github.com/pi-hole/pi-hole/pull/731) and [Web](https://github.com/pi-hole/AdminLTE/pull/149).
