### ISSUE TITLE
Installing on Centos-7

### ISSUE THREAD

**Issue by BiloxiGeek** [pi-hole/pi-hole#586]
Fresh install from CentOS-Userland-7-armv7hl-Minimal-1603-RaspberryPi3.img

Did some minor tweaking on the Pi, just installed a few utilities I find useful for myself.

##### Expected Behaviour:
Run install script, end up with an operational pi-hole setup.

##### Actual Behaviour:
Downloaded the install script to a local file.  Ran it as root via a ssh login.  Received numerous errors, most of all seemed to be related to packages not found.

##### Steps to reproduce this issue:
Install to new sd card from CentOS-Userland-7-armv7hl-Minimal-1603-RaspberryPi3.img
Run "curl -L https://install.pi-hole.net | bash" (or download it first and run manually)

Full output from the shell at http://pastebin.com/VwhcFMiV

Is this expected?  I was under the impression that CentOS on the Pi was ready to go, or is it just CentOS support that's been added?

**Comment by dschaper** [comment]
Taking a look at that now, can you post a copy of your `/etc/resolv.conf` file and a copy of `ip a`?

**Comment by dschaper** [comment]
```
[root@centos-rpi3 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
# Configured via Pi-Hole installer
DEVICE=eth0
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.1.100
PREFIX=24
USERCTL=no
[root@centos-rpi3 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0.backup-2016-07-20-205053
TYPE="Ethernet"
BOOTPROTO="dhcp"
NM_CONTROLLED="yes"
DEFROUTE="yes"
NAME="eth0"
UUID="1192052d-21c2-4e6b-a831-3a972461b623"
ONBOOT="yes"
```
```
[root@centos-rpi3 ~]# cat /etc/resolv.conf
# Generated by NetworkManager


# No nameservers found; try putting DNS servers into your
# ifcfg files in /etc/sysconfig/network-scripts like so:
#
# DNS1=xxx.xxx.xxx.xxx
# DNS2=xxx.xxx.xxx.xxx
# DOMAIN=lab.foo.com bar.foo.com
```

**Comment by dschaper** [comment]
And works fine in DO droplet install of CentOS 7.11. Debugging further.

**Comment by dschaper** [comment]
@bcambl

**Comment by dschaper** [comment]
@BiloxiGeek It doesn't look like that SIG has an epel-release available for the packages we need to work. I'll check it further, but I don't think that release is going to be functional until they have some more packages available.

**Comment by BiloxiGeek** [comment]
@dschaper ... That's what I was thinking would be the issue.  How are you getting an RPi running CentOS 7 and Pi-Hole installed?

**Comment by dschaper** [comment]
It's functional on CentOS 7 for the x86 environment. The Pi (ARM) distro is the RHEL/FC release.

**Comment by BiloxiGeek** [comment]
/etc/resolv.conf
cat /etc/resolv.conf 
 # Generated by NetworkManager
 nameserver 192.168.1.2

That IP is my Rasbian Pi running pi-hole, it's being set as the DNS for all dhcp clients on my network.

ip a:

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether b8:27:eb:9e:f0:71 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.14/24 brd 192.168.1.255 scope global dynamic eth0
       valid_lft 28549sec preferred_lft 28549sec
    inet6 fe80::ba27:ebff:fe9e:f071/64 scope link 
       valid_lft forever preferred_lft forever

Guess all that is a bit useless for the moment.

**Comment by dschaper** [comment]
Unfortunately until that SIG has a working set of packages, it won't function as a Pi-Hole. I'm just getting yum locks trying to get the keys on the repos.

**Comment by bcambl** [comment]
@BiloxiGeek,
Your pastebin states that your system is out of date.
Do:
`dnf clean all`
`dnf update -y`
..then attempt the install again.

**Comment by bcambl** [comment]
PEERDNS=no will stop network manager from overwriting  `resolv.conf`
DNS can be specified in the interface file ifcfg-<interface> like so:
DNS1=x.x.x.x
DNS2=x.x.x.x

**Comment by BiloxiGeek** [comment]
Gonna have to get back on this tomorrow.  But a couple of obserations...

Looks like this CentOS7 for RPi install does not have dnf available yet.  Yum still works as expected. 

There are three repos available after install:
repo id                             repo name                             status
base/7/armhfp                       CentOS-7 - Base                       4,883
extras/7/armhfp                     CentOS-7 - Extras                        15
updates/7/armhfp                    CentOS-7 - Updates                    1,045

I looked for any available yum-conf-<repo> and any EPEL related packages.  None to be found in those repos.

I made the mistake of running the yum update before I had expanded the filesystem to fill up the sd card, it promptly choked after updating 3 packages.  Oops.  But I can always reimage and start over tomorrow.

**Comment by bcambl** [comment]
Right on, let me know how it goes.
If there is no 'epel-release` package in your default repos, you may need to add EPEL manually.
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
(or just create the repo file manually)

**Comment by BiloxiGeek** [comment]
No joy in mudville so far.  The EPEL repo file doesn't want to install and function, doesn't like the arch environment setting.  Looks like a good portion of the packages in EPEL are compiled for x86_64, lighttpd is for sure, so no way to get that package to install.  There is "httpd.arm7hl"  along with devel, manual and tools packages.  No idea at this point what dependency hell trying that would cause.  Without jumping through a bunch of hoops I think I'm gonna have to wait for EPEL to get a decent arm7 repo worked up.

I've got a Raspbian pi-hole running so I'm good to go at the moment.  My idea was to get a CentOS version setup since I work with SciLinux and Fedora both on the job and at home.  I like consistency wherever I can get it.

**Comment by BiloxiGeek** [comment]
If one of you guys can provide a list of the RPM's that come from EPEL I can try to start pulling source RPM's and see what I might come up with.  I haven't done a lot of that in the past so I'm stumbling around mostly in the dark but I'll give a whirl just to see what happens.

**Comment by bcambl** [comment]
Yea, you will definitely need EPEL (Fedora packages) for this project.
I personally run Fedora ARM (https://fedoraproject.org/wiki/Architectures/ARM) so the ARM packages are available by default. @dschaper and I did all our testing of CentOS on VM/VPS (x86_64).

I will post a list of the packages that are required from EPEL next chance I get.

**Comment by BiloxiGeek** [comment]
Well somehow I managed to get:
lighttpd-1.4.39-3.el7.centos.armv7hl
spawn-fcgi-1.6.3-5.el7.centos.armv7hl
lighttpd-fastcgi-1.4.39-3.el7.centos.armv7hl

all built from srpm and installed.  They actually seem to be running properly too. :) I'm feeling my geek cred getting a bump up today!

**Comment by BiloxiGeek** [comment]
Geek cred taking a nose dive now.  Started looking into what other packages are going to be required and hitting some serious dependency hell.  Not sure this is going to be a manageable task without the EPEL repo supporting the RPi3 hardware.

**Comment by dschaper** [comment]
If you can help us out by starting a list of packages and dependencies maybe we can attack this from multiple angles and try to figure something out. The more intel we have, the better off we all are. I appreciate the assistance! Thanks.

**Comment by bcambl** [comment]
From a CentOS 7.2 DO droplet with EPEL installed (`epel-release`):
http://termbin.com/1jly

**Comment by BiloxiGeek** [comment]
@dschaper How much detail do you want?  I'm starting from a fresh install and documenting pretty much every step right now.

@bcambl Working through that list now, everything in your fedora-packages list seems to be already installed or available except for lighttpd and lighttpd-fastcgi.  Getting those from source, building the rpm's and then installing locally caused me to get the idea that I'd need to get spawn-fcgi installed the same way.  Don't recall precisely where I ran into that the first time, but I think it was error messages from systemctl when I tried to start lighttpd after building and installing.

**Comment by BiloxiGeek** [comment]
/etc/pihole/install.log:      http://termbin.com/eyuc

All the output from the install script:  http://termbin.com/3ek7

lighttpd is running but no pages being served up.

/etc/pihole just has the install.log and piholeIP files.

**Comment by BiloxiGeek** [comment]
Think I found one thing that was causing issues with this attempt.  The network setup was coming up with no default route defined.  I've got that fixed now and am running through another install attempt.

Looks like that may have been the actual problem all along.  Well besides no lighttpd and spawn-fcgi. I set my iPad to use this test RPi as DNS and ads are being blocked.  The pihole admin web interface is functioning.  Really think I'm gonna start from scratch again, run through my steps but add a check for proper network config.  I did tweak the install script to not install epel-release and changed the netcat package name to nmap-ncat.

**Comment by BiloxiGeek** [comment]
A minor network issue now:  My most recent install attempt went well.  Had to tweak the /etc/sysconfig/network-scripts/ifcfg-eth0 file to get a default gateway setup.  Something went wrong with that; /etc/pihole and /var/www/html/admin didn't have the content that should be there.  So I ran the installer again and it all seemed okay after that.  But the ifcfg-eth0 file got overwritten with a config that I think won't work for most anyone.

Right now I have:
# Configured via Pi-Hole installer 
DEVICE=eth0
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.1.14
PREFIX=24
USERCTL=no

Pretty sure there's gotta be one additional directive in there:
GATEWAY=192.168.1.1

But the big takeaway from all this is locally building lighttpd and spawn-fcgi, plus some minor adjustments to the install script can get CentOS running pi-hole on an RPi3.  I wouldn't recommend it to a non-geek, but for those with some sysad or similar experience it can be done.

**Comment by dschaper** [comment]
Thanks a ton for all the help and the notes. I'm a bit busy in my real life job and just wanted to drop a quick note to say thanks and I'll get more time to look in a day or two. (I hope :smile: )

**Comment by BiloxiGeek** [comment]
Should I be working up a wiki page here to document the steps I went through getting CentOS to work with pi-hole on the RPi?  I won't show it all just the basic steps and a reference back to this issue.

**Comment by PromoFaux** [comment]
Yep, feel free! One area we are currently quite lax on is documentation so every little helps!

**Comment by BiloxiGeek** [comment]
https://github.com/pi-hole/pi-hole/wiki/CentOS-and-RPi3
