### ISSUE TITLE
Redirecet not working - lighttpd fails to start

### ISSUE THREAD

**Issue by shesk** [pi-hole/pi-hole#587]
##### Expected Behaviour: 

Manual install step 'Configure The Web Server To Redirect Ad Domains To A Blank Page'

sudo service lighttpd restart 
Successful

##### Actual Behaviour:

sudo service lighttpd restart
Job for lighttpd.service failed. See 'systemctl status lighttpd.service' and 'journalctl -xn' for details.

##### Steps to reproduce this issue:

It took me a long time to narrow down the fact that it was the web server causing the issue. Here are the specific troubleshooting steps once I discovered it wasn't starting

- Rebuilt raspbian Pi (Jessie light) twice
- Ran through all the manual steps - including creating dnsmasq.conf and lighttpd.conf files
- Found a generic lighttpd.conf file and replaced to see if that would help
- Re-ran the chmod and chown commands on the /var/www files

dnsmasq log-facility **/var/log/pihole.log** - shows 
query[A] adsite.com from 192.168.1.1
forwarded adsite.com to 8.8.8.8
forwarded adsite.com to 8.8.4.4

**systemctl status lighttpd.service**
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: failed (Result: exit-code) since Thu 2016-07-21 19:41:24 EDT; 11min ago
  Process: 719 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
  Process: 2003 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
 Main PID: 719 (code=exited, status=0/SUCCESS)

Jul 21 19:41:24 raspberrypi lighttpd[2003]: 2016-07-21 23:41:24: (configfile.c.589) source: /etc/lighttpd/lighttpd.conf line: 32 pos: 25 use => for assignments in arrays
Jul 21 19:41:24 raspberrypi lighttpd[2003]: 2016-07-21 23:41:24: (configfile.c.954) configfile parser failed at:
Jul 21 19:41:24 raspberrypi systemd[1]: lighttpd.service: control process exited, code=exited status=255
Jul 21 19:41:24 raspberrypi systemd[1]: Failed to start Lighttpd Daemon.
Jul 21 19:41:24 raspberrypi systemd[1]: Unit lighttpd.service entered failed state.

**sudo journalctl -xn | grep lighttpd**
-- Subject: Unit lighttpd.service has begun with start-up
-- Unit lighttpd.service has begun starting up.
Jul 21 19:54:20 raspberrypi lighttpd[2072]: 2016-07-21 23:54:20: (configfile.c.589) source: /etc lighttpd/lighttpd.conf line: 32 pos: 25 use => for assignments in arrays
Jul 21 19:54:20 raspberrypi lighttpd[2072]: 2016-07-21 23:54:20: (configfile.c.954) configfile parser failed at:
Jul 21 19:54:20 raspberrypi systemd[1]: lighttpd.service: control process exited, code=exited status=255
-- Subject: Unit lighttpd.service has failed
-- Unit lighttpd.service has failed.
Jul 21 19:54:20 raspberrypi systemd[1]: Unit lighttpd.service entered failed state.

**Comment by dschaper** [comment]
Which manual directions are you using. We have a complete automated install now, and some blogs reference an older manual method that will cause issues if you follow them.

**Comment by PromoFaux** [comment]
I _think_ there was a notice added to the top of that manual method to say it was out of date?

If you want to try and install manually, best bet is to read the [install script](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh) to see what it's doing, and the dependencies it requires/files it pulls in. Things have changed a fair bit since that blogpost!

**Comment by shesk** [comment]
I must have left that part out. I ran the automayed script, twice. Rebuilding the Raspbian pi in-between attempts. Pi-hole was not working properly both attempts. 

So, I started going the manual steps to where it failed. The manual steps came from http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/

Running service lights restart was the only fail I received through the entire manual process.

**Comment by dschaper** [comment]
Because that manual method is out of date and references some configurations that will break and also will cause problems with the upgrade features, can we get you to try the Automated Install on Raspbian Jessie, and if you run into problems, let us know here. We have a scripted debugging procedure and so far we've been able to solve over %99 of the install problems. (And that other %1 is under active research to get them up and running as well.) 

Welll work with you until you have an operational Pi-Hole, that's a promise from me personally.

**Comment by jacobsalmela** [comment]
Yes, sorry about the outdated steps.  I put a disclaimer on top of the article and I have also been redirecting old posts so that doesn't happen.

Try using the new automated install and you'll have a lot better luck.  Let us know how it goes.

**Comment by shesk** [comment]
Jacobsalmela and dschaper, thanks for the help. Really appreciate it! Disclaimer, I have pipvn running on the same box.

I've rerun the automated scripts. Unfortunately I'm out of the country for the next few weeks and won't have physical access to my pi in order to flash Jessie light.

After re-running the script. I'm now able to see that lighttpd is started. However. When I ping an ad site or anything on the blacklist, I still get a valid IP rather then an internal one. Dnsmasq is also running. I skimmed through the lighttpd.conf and it looks to be correct. 

Should I attempt the debugging now or wait until I can start over with a clean install? ( Note: my first two attempts were done with the automated script on a clean install of Jessie light. It was only after the install that I tried manual intervention to fix)

**Comment by dschaper** [comment]
We can take a look at the debug now and see if we can solve the issue without needing a reflash. Just run `pihole -d` from a shell and follow the prompts. If the Pi-Hole has internet access it will give you a URL, just paste that up here and we'll take a look. (Check the URL first just to make sure there is no information you'd prefer not get out and let us know!)

**Comment by shesk** [comment]
Wow, quick response. 

Something tells me that it didn't work. Where do I find the log file?

pi@raspberrypi:~ $ pihole -d
::: You are root... Beginning debug!
::: Writing local IPs to debug log
cat: /etc/*release/: No such file or directory
:::
::: Logging status of lighttpd and dnsmasq...
::: Writing lighttpd to debug log...
::: Writing dnsmasq.conf to debug log...
::: Writing 01-pihole.conf to debug log...
::: Writing size of gravity.list to debug log...
::: Writing hosts file to debug log...
::: Writing whitelist to debug log...
::: Writing blacklist to debug log...
::: Writing adlists.list to debug log...
:::     No adlists.list file found... using adlists.default!
::: Writing current pihole traffic to debug log...
:::     Try loading any/all sites that you are having trouble with now...
:::     (Press ctrl+C to finish)


Running out for a few hours, I'll check back in when I can. Thanks again!

**Comment by dschaper** [comment]
You just need to hit `CTRL-C` to finish up the debug and it will give you the location from there. The pause is so that you can browse a few sites on a client machine and that will show in the debug logs.

**Comment by shesk** [comment]
That is my bad. I have a slow connection and the file name didn't display immediately after I hit ctrl-c. 

IP Addresses of this Pi:
192.168.1.3
127.0.0.1
10.8.0.1

Gateway check:
ok

#######################################
########## Versions Section ###########
#######################################
Pi-hole Version: v2.8.1
WebUI Version: v1.3

#######################################
######## Distribution Section #########
#######################################
Distribution Version: Failed to find release

#######################################
######## Whitelist Comparison #########
#######################################
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com

#######################################
######## Blacklist Comparison #########
#######################################
192.168.1.3 www.googleadservices.com
192.168.1.3 www.googleadservices.com
192.168.1.3 www.googleadservices.com
192.168.1.3 https://www.googleadservices.com
192.168.1.3 https://www.googleadservices.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://adclick.g.doubleclick.net/
192.168.1.3 https://adclick.g.doubleclick.net/
192.168.1.3 247media.com
192.168.1.3 247media.com
192.168.1.3 247media.com
192.168.1.3 amazon.com/b/
192.168.1.3 amazon.com/b/
192.168.1.3 pagead.l.doubleclick.net
192.168.1.3 pagead.l.doubleclick.net

#######################################
############ NSLookup Test ############
#######################################
NSLOOKUP of raspberrypi from PiHole:
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find raspberrypi: SERVFAIL


NSLOOKUP of raspberrypi from 8.8.8.8:
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find raspberrypi: NXDOMAIN

#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Mon 2016-07-25 22:43:31 EDT; 3 days ago
  Process: 691 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 719 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─719 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─727 /usr/bin/php-cgi
           ├─728 /usr/bin/php-cgi
           ├─729 /usr/bin/php-cgi
           ├─730 /usr/bin/php-cgi
           └─731 /usr/bin/php-cgi

Jul 25 22:43:31 raspberrypi lighttpd[691]: Syntax OK
Jul 25 22:43:31 raspberrypi systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Mon 2016-07-25 22:43:28 EDT; 3 days ago
  Process: 500 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=1/FAILURE)
  Process: 406 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Jul 25 22:43:28 raspberrypi dnsmasq[406]: dnsmasq: syntax check OK.
Jul 25 22:43:28 raspberrypi dnsmasq[500]: dnsmasq: illegal repeated keyword at line 8 of /etc/dnsmasq.conf
Jul 25 22:43:28 raspberrypi systemd[1]: dnsmasq.service: control process exited, code=exited status=1
Jul 25 22:43:28 raspberrypi systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jul 25 22:43:28 raspberrypi systemd[1]: Unit dnsmasq.service entered failed state.
#######################################
############ lighttpd.conf ############
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404        = "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename                      = "/var/log/lighttpd/access.log"
accesslog.format                        = "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
######### lighttpd error.log ##########
#######################################
2016-07-26 02:31:39: (log.c.164) server started
2016-07-26 02:31:39: (server.c.1045) WARNING: unknown config-key: url.access-deny (ignored)
2016-07-26 02:43:25: (server.c.1558) server stopped by UID = 0 PID = 1
2016-07-26 02:43:32: (log.c.164) server started
2016-07-26 02:43:32: (server.c.1045) WARNING: unknown config-key: url.access-deny (ignored)
2016-07-26 02:50:23: (server.c.1558) server stopped by UID = 0 PID = 1
2016-07-26 02:55:39: (log.c.164) server started
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 230
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 231
2016-07-26 02:43:32: (log.c.164) server started
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 230

#######################################
############### Dnsmasq ###############
#######################################
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
########### 01-pihole.conf ############
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
############ gravity.list #############
#######################################
101227 /etc/pihole/gravity.list

Hostname of this pihole is:
raspberrypi
#######################################
################ Hosts ################
#######################################
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi

#######################################
############## Whitelist ##############
#######################################
https://aax-us-east.amazon-adsystem.com
raw.githubusercontent.com
adblock.gjtech.net
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net
ransomwaretracker.abuse.ch

#######################################
############## Blacklist ##############
#######################################
www.googleadservices.com
https://www.googleadservices.com
https://aax-us-east.amazon-adsystem.com
https://adclick.g.doubleclick.net/
247media.com
amazon.com/b/
pagead.l.doubleclick.net

#######################################
############ adlists.list #############
#######################################
No adlists.list file found... using adlists.default!
#######################################
############# pihole.log ##############
#######################################

**Comment by dschaper** [comment]
Okay, first thing is that you have addresses set for the 192/24 block and the 10/8 block on your Pi. Can you get an output of `ip a` for us? And then the real show stopper, your `/etc/dnsmasq.conf` and `/etc/dnsmasq.d/01-pihole.conf` contain duplicate information. This will cause `dnsmasq` to fail, as seen in the `dnsmasq processes status:` stanza. So we need to clear out the duplicate entries from `/etc/dnsmasq.conf`. (Anything that is in `01-pihole.conf` cannot be in `dnsmasq.conf` so delete those lines. 

Once you get that cleaned up, run another debug and post up the output.

**Comment by shesk** [comment]
Here is the first part. Working on the second now.

pi@raspberrypi:~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:1f:d3:31 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::dce6:591c:af31:cdc3/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:4a:86:64 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::acf2:9bc4:f57a:ed27/64 scope link tentative
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.8.0.1 peer 10.8.0.2/32 scope global tun0
       valid_lft forever preferred_lft forever

**Comment by shesk** [comment]
Hmm. If I'm reading this correctly, literally every line is a duplicate. Can I have an empty Dnsmasq.conf file or delete the file entirely?

**Comment by dschaper** [comment]
I wouldn't delete the file entirely, but go ahead and clean it out if there are just duplicated lines in there.

**Comment by shesk** [comment]
Alright. Debug #2. 

IP Addresses of this Pi:
192.168.1.3
127.0.0.1
10.8.0.1

Gateway check:
ok

#######################################
########## Versions Section ###########
#######################################
Pi-hole Version: v2.8.1
WebUI Version: v1.3

#######################################
######## Distribution Section #########
#######################################
Distribution Version: Failed to find release
#######################################
######## Whitelist Comparison #########
#######################################
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com

#######################################
######## Blacklist Comparison #########
#######################################
192.168.1.3 www.googleadservices.com
192.168.1.3 www.googleadservices.com
192.168.1.3 www.googleadservices.com
192.168.1.3 https://www.googleadservices.com
192.168.1.3 https://www.googleadservices.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://aax-us-east.amazon-adsystem.com
192.168.1.3 https://adclick.g.doubleclick.net/
192.168.1.3 https://adclick.g.doubleclick.net/
192.168.1.3 247media.com
192.168.1.3 247media.com
192.168.1.3 247media.com
192.168.1.3 amazon.com/b/
192.168.1.3 amazon.com/b/
192.168.1.3 pagead.l.doubleclick.net
192.168.1.3 pagead.l.doubleclick.net

#######################################
############ NSLookup Test ############
#######################################
NSLOOKUP of raspberrypi from PiHole:
;; connection timed out; no servers could be reached


NSLOOKUP of raspberrypi from 8.8.8.8:
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find raspberrypi: NXDOMAIN


#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Mon 2016-07-25 22:43:31 EDT; 4 days ago
  Process: 691 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 719 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─719 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─727 /usr/bin/php-cgi
           ├─728 /usr/bin/php-cgi
           ├─729 /usr/bin/php-cgi
           ├─730 /usr/bin/php-cgi
           └─731 /usr/bin/php-cgi

Jul 25 22:43:31 raspberrypi lighttpd[691]: Syntax OK
Jul 25 22:43:31 raspberrypi systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Mon 2016-07-25 22:43:28 EDT; 4 days ago
  Process: 500 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=1/FAILURE)
  Process: 406 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Jul 25 22:43:28 raspberrypi dnsmasq[406]: dnsmasq: syntax check OK.
Jul 25 22:43:28 raspberrypi dnsmasq[500]: dnsmasq: illegal repeated keyword at line 8 of /etc/dnsmasq.conf
Jul 25 22:43:28 raspberrypi systemd[1]: dnsmasq.service: control process exited, code=exited status=1
Jul 25 22:43:28 raspberrypi systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jul 25 22:43:28 raspberrypi systemd[1]: Unit dnsmasq.service entered failed state.
#######################################
############ lighttpd.conf ############
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404        = "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename                      = "/var/log/lighttpd/access.log"
accesslog.format                        = "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
######### lighttpd error.log ##########
#######################################
2016-07-26 02:31:39: (log.c.164) server started
2016-07-26 02:31:39: (server.c.1045) WARNING: unknown config-key: url.access-deny (ignored)
2016-07-26 02:43:25: (server.c.1558) server stopped by UID = 0 PID = 1
2016-07-26 02:43:32: (log.c.164) server started
2016-07-26 02:43:32: (server.c.1045) WARNING: unknown config-key: url.access-deny (ignored)
2016-07-26 02:50:23: (server.c.1558) server stopped by UID = 0 PID = 1
2016-07-26 02:50:46: (log.c.164) server started
2016-07-26 02:51:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 02:51:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 02:51:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 234
2016-07-26 02:52:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 02:52:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 02:52:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 234
2016-07-26 02:55:38: (server.c.1558) server stopped by UID = 0 PID = 1
2016-07-26 02:55:39: (log.c.164) server started
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 03:00:36: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 230
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-26 03:02:34: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 231
2016-07-26 02:43:32: (log.c.164) server started
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-27 12:55:52: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 230
2016-07-30 00:10:09: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-30 00:10:09: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  max(): Array must contain at least one element in /var/www/html/admin/data.php on line 227
2016-07-30 00:10:09: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-30 00:10:09: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  min(): Array must contain at least one element in /var/www/html/admin/data.php on line 228
2016-07-30 00:10:09: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/data.php on line 231

#######################################
############### Dnsmasq ###############
#######################################

#######################################
########### 01-pihole.conf ############
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
############ gravity.list #############
#######################################
101227 /etc/pihole/gravity.list

Hostname of this pihole is:
raspberrypi
#######################################
################ Hosts ################
#######################################
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi

#######################################
############## Whitelist ##############
#######################################
https://aax-us-east.amazon-adsystem.com
raw.githubusercontent.com
adblock.gjtech.net
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net
ransomwaretracker.abuse.ch

#######################################
############## Blacklist ##############
#######################################
www.googleadservices.com
https://www.googleadservices.com
https://aax-us-east.amazon-adsystem.com
https://adclick.g.doubleclick.net/
247media.com
amazon.com/b/
pagead.l.doubleclick.net

#######################################
############ adlists.list #############
#######################################
No adlists.list file found... using adlists.default!
#######################################
############# pihole.log ##############
#######################################

**Comment by dschaper** [comment]
Okay, try `sudo systemctl restart dnsmasq` and one last debug and I think we'll be good and working.

**Comment by shesk** [comment]
URL is probably a good sign

http://termbin.com/quwy

**Comment by dschaper** [comment]
Everything looks good, should be able to set your clients to the Pi-Hole as the DNS and see some blocking. The Admin Page should be functional as well!

**Comment by shesk** [comment]
I have my router setting the DNS to the pihole IP.

Admin page is up and running.

Still seeing external IPs when I ping a site on the blacklist. Maybe I have the router setup wrong. Iloilo go back and check.

Thanks!

**Comment by dschaper** [comment]
No problem, let me know if that solves it and I'll close out the issue.

**Comment by shesk** [comment]
Settings appear correct.

I have it routing to the 192/24 block. Should I be routing to the 10/8 block instead?

**Comment by dschaper** [comment]
The 10/8 is a TUN adapter, so I figured you had a reason for that setup. If your clients are all on the 192/24 then they should forward to the 192 address.

```
Jul 30 08:57:43 dnsmasq[13057]: query[A] v.canaryis.com from 192.168.1.1
Jul 30 08:57:43 dnsmasq[13057]: forwarded v.canaryis.com to 8.8.4.4
```
That shows that 192.168.1.1 is forwarding reqeusts to the Pi-Hole correctly. Your `ip a` shows that you don't have IPv6 on your network, which takes a lot of the troubleshooting out. (A good thing in this case.) What OS are your clients running? It's possible they have the addresses in cache and they either need to time out or be flushed. On windows you could run `ipconfig /flushdns` at a command prompt to flush the DNS cache.

**Comment by shesk** [comment]
The 10/8 must be from pipvn. 

The only client I can test from at the moment is my cell phone tunneled in via the pipvn. 

So, stupid question. If I ping from the raspberry pi, what should I see?

If I ping from my cell phone after tunneled in (10/8 IP), Im guessing I should see the redirect.

**Comment by dschaper** [comment]
Pinging a blocked domain from the Pi-Hole itself should return the 192.168.1.3 address. (It may return 127.0.0.1 but if it does then there may be other issues.) Does the Admin page show any activity?

**Comment by shesk** [comment]
Pinging a blocked domain returns a public IP. From the Pi-Hole or phone.

Admin page is up and active. ~200 DNS requests, but only 1 blocked ad. Domain = raspberrypi

This isn't all that different from the last few days.

**Comment by dschaper** [comment]
What does the `/etc/resolv.conf` file look like?

**Comment by shesk** [comment]
pi@raspberrypi:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 127.0.0.1

**Comment by dschaper** [comment]
Okay, last thing to check out, lets delete your `/etc/pihole/gravity.list` and clear the blacklist and whitelist. When that's done run `pihole -g` to rebuild. That should clear out the last of any remnants...

**Comment by jacobsalmela** [comment]
So your whitelist and blacklist appear to have the full URL.  The whitelist and blacklist need to be just a list of fully qualified domain names.  So only  `www.googleadservices.com`, not `https://www.googleadservices.com`.

**Comment by shesk** [comment]
@jacobsalmela I was wondering about that, thanks!

@dschaper It works! Thank you so much for helping!!! You are awesome

**Comment by dschaper** [comment]
Great! Thanks for using the Pi-Hole!
