### ISSUE TITLE
Adchoices

### ISSUE THREAD

**Issue by dkdhanda8** [pi-hole/pi-hole#596]
How to remove adchoices from apps ?

![screenshot_20160729-170308](https://cloud.githubusercontent.com/assets/20723805/17247232/791219d2-55af-11e6-86a2-82cb44f1df4c.png)
##

**Comment by dschaper** [comment]
Those ad sources are very hard to eliminate. They use their own internal cache of ads that are supplied along with the .apk files. So even when we do block them from pulling new advertisements, they go to their internal cache of ads and display those. We're always under development to try and find new ways to block if we can, so we will continue to try to find a solution to this type of advertisement.

And sometimes they just disappear after a period of time...
