### ISSUE TITLE
Cannot add or remove from Whitelist/Blacklist through Web Admin Panel

### ISSUE THREAD

**Issue by Woodamsc** [pi-hole/pi-hole#604]
##### Expected Behaviour:
Type in a (sub)domain to be blocked/whitelisted, then click "Add" to have that domain added to the appropriate list.
Clicking delete on any existing domains in the list are removed.

##### Actual Behaviour:
When trying to add a domain to either list a blue banner appears saying "Adding to White/Blacklist..."
Immediately followed by a red one "Something went wrong...", and no change to the list.
When deleting, a small pop-up appears that says "Failed to remove domain"

Contents of `pihole -d`
```
Clark@Hemlock ~ $ pihole -d
[sudo] password for Clark:
::: You are root... Beginning debug!
::: Writing local IPs to debug log
cat: /etc/*release/: No such file or directory
:::
::: Logging status of lighttpd and dnsmasq...
/opt/pihole/piholeDebug.sh: line 154: systemctl: command not found
/opt/pihole/piholeDebug.sh: line 154: systemctl: command not found
::: Writing lighttpd to debug log...
::: Writing dnsmasq.conf to debug log...
::: Writing 01-pihole.conf to debug log...
::: Writing size of gravity.list to debug log...
::: Writing hosts file to debug log...
::: Writing whitelist to debug log...
::: Writing blacklist to debug log...
::: Writing adlists.list to debug log...
:::	No adlists.list file found... using adlists.default!
::: Writing current pihole traffic to debug log...
:::	Try loading any/all sites that you are having trouble with now...
:::	(Press ctrl+C to finish)
^C
::: Finishing debug write from interrupt... Quitting!
::: Finshed debugging!
::: Debug log can be found at : http://termbin.com/opjn
```

Running Raspbian Wheezy, using Safari 9.1.2 for Admin Panel
Sudo is installed. I've done a complete uninstall of pi-hole and re-install several times. I can't help but think it's a permission issue. I'm not sure if the debugger trying to use systemctl on a debian system indicates a problem detecting my OS?
And what I would assume is related:
```cat /etc/*release/ ```
should be
```cat /etc/*release```
The former returns "No such file or directory", latter returns actual release info.

**Comment by Mcat12** [comment]
Ya, that's a bug in the debug script. Looking at your log, you have php 5.4, while the scripts for adding and removing domains requires 5.6 or greater. We are looking into fixing this, but in the mean time you should either update php (through a third-party repo, as 5.6 is not available on wheezy) or update to Raspbian Jessie, which would have php 5.6.

**Comment by Zegnat** [comment]
> <i>[T]</i>he scripts for adding and removing domains requires 5.6 or greater.

Is this only because of the use of `hash_equals`? Would it not be a good idea to ship your own [safe compare function](https://gist.github.com/Zegnat/5936767) and just support 5.4? Asking because it seems people write in with older versions of PHP quiet regularly. (And who can blame them, when most repos haven’t even added PHP 7 yet!)

**Comment by Mcat12** [comment]
Yep. Right now I'm actually looking replacing it with something more compatible. If you would like, you can make a pull request!

**Comment by Woodamsc** [comment]
I updated to Raspbian Jessie which gave me 5.6 and the issue is no longer present - just as you suspected. Thanks for help

**Comment by Mcat12** [comment]
You're welcome!
