### ISSUE TITLE
Can't access the Pi-hole webinterface

### ISSUE THREAD

**Issue by josvliet** [pi-hole/pi-hole#605]
##### Actual Behaviour: I Installes Pi-hole on my RaspberyPi 3. It seems to work fine. But I get the message: Problem connecting to website. Website dies not exitst or is down when I want to view the webinterface for performers etc.
Pi-hole is working because I don't see ads anymore. Al my systems are set to use the RaspberyPi for DNS. All other sites are connecting ok.
I'm a newbee for linux systems so I don't know how to troubleshoot. Sorry for that.

**Comment by dschaper** [comment]
Hi, can you run `pihole -d` and post the link to the debug file generated from that command? Just follow the on-screen prompts.

**Comment by josvliet** [comment]
Hi Dan,

Thanks for your quick response.

I’ve run the debug and the results are on  http://termbin.com/k10h

Jos

 

Van: Dan Schaper [mailto:notifications@github.com] 


Verzonden: maandag 1 augustus 2016 15:21
Aan: pi-hole/pi-hole <pi-hole@noreply.github.com>
CC: josvliet <josvandervliet@casema.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pi-hole/pi-hole] Can't access the Pi-hole webinterface (#605)

 

Hi, can you run pihole -d and post the link to the debug file generated from that command? Just follow the on-screen prompts.

**Comment by dschaper** [comment]
Which OS are you running on your Pi-hole install?

**Comment by josvliet** [comment]
I used Noobs to install  Raspbian Jessie.

 

Van: Dan Schaper [mailto:notifications@github.com] 
Verzonden: maandag 1 augustus 2016 16:08
Aan: pi-hole/pi-hole <pi-hole@noreply.github.com>
CC: josvliet <josvandervliet@casema.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pi-hole/pi-hole] Can't access the Pi-hole webinterface (#605)

 

Which OS are you running on your Pi-hole install?

**Comment by dschaper** [comment]
Thanks, looks like `lighttpd` isn't fully configured. Can you post the output from `php-cgi -v`?

**Comment by josvliet** [comment]
If I run that I get the message: -bash: php-cgi: opdracht niet gevonden. Moet ik dat vanuit een bepaalde folder runnen?

 

Van: Dan Schaper [mailto:notifications@github.com] 
Verzonden: maandag 1 augustus 2016 16:48
Aan: pi-hole/pi-hole <pi-hole@noreply.github.com>
CC: josvliet <josvandervliet@casema.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pi-hole/pi-hole] Can't access the Pi-hole webinterface (#605)

 

Thanks, looks like lighttpd isn't fully configured. Can you post the output from php-cgi -v?

**Comment by josvliet** [comment]
Hello Dan,

I’ve runed the commands below, and now it’s working. Super!

I’dd like to thank very much.

Regards,

Jos

 

 

Van: Dan Schaper [mailto:notifications@github.com] 
Verzonden: maandag 1 augustus 2016 17:16
Aan: pi-hole/pi-hole <pi-hole@noreply.github.com>
CC: josvliet <josvandervliet@casema.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pi-hole/pi-hole] Can't access the Pi-hole webinterface (#605)

 

It appears that somehow PHP wasn't installed when you ran the install script. Can you run sudo apt update && sudo apt install php5-common php5-cgi php5 and then if that is successful, run sudo systemctl start lighttpd?

**Comment by dschaper** [comment]
Great! Thanks for using the Pi-hole!
