### ISSUE TITLE
Give the user the option of uploading their logs to the Internet.

### ISSUE THREAD

**Issue by escapologyBB** [pi-hole/pi-hole#606]
##### Expected Behaviour:
That when I run `pihole -d` I will see a debugging log for Pi-Hole.
##### Actual Behaviour:
The debugging log is generated but then is uploaded to the Internet without my express permission, it is uploaded to a service called Termbin.
##### Steps to reproduce this issue:
Run `pihole -d`, wait a few seconds and then the user is presented with A link to the logs which have been uploaded to Termbin.

---

Hi Guys,

As suggested on the Reddit thread I've opened in issue here detailing my problem/issue.  This is an awesome project and after using it for a couple of weeks I made sure to donate and install it on family computers, it really is great.  However I have one problem which I wondered if you could address.

When I run the command `pihole -d` in the event of a problem, I was expecting to see a printout of my debugging log so I could go about fixing my problem.  However, I was presented with a link to a service on the Internet to which my logs had been uploaded.  This uploading was done without my permission, was uploaded to a server that doesn't use SSL and could possibly contain personally identifiable information.  I'm not sure about that last one, it depends on whether it shows where I've been on the Internet, but you can see why I might take issue with the log being uploaded straight to the Internet without a prompt asking me if I was okay with it.

So I was wondering if you could add in an interstitial step after I run the command   `pihole -d` to get a log, something as simple as: `Would you like to upload this to Termbin to make it easier to share with the developers [Y/n]` would be great.  Or a small menu even, something simple so as not to over face non-technical users that might look something like this after you run the command:

1. Upload logs to Termbin for easier sharing
2. Print logs to the terminal to look at them locally without uploading them to the Internet
3. Both of the above!

Let me repeat, this is an awesome project and you have created something brilliant.  This is more of an ethical issue for me than a technical one, and I assumed that because you were building something that helps people avoid the perils of online tracking you might feel the same way.  Just today, 10% of my traffic was advertising related, now I'm lucky enough to be on unmetered Internet access but were I not non-metered Internet access that means that 10% of every Internet bill goes to paying for adverts I don't want, track me, and potentially serve up malware without my knowing.  They do all this and they make it cost people money!

Okay, I'm going to stop rambling now but it was suggested I raise an issue here so that the whole team could see it.

All the best and let me know if I can help in anyway.

**Comment by PromoFaux** [comment]
Totally understand this, whilst there _shouldn't_ be any personally identifying information in the debug log, it pays to be cautious!

Prompt added.

**Comment by escapologyBB** [comment]
Wow, that was fast!

What can I say, addressing and fixing my problem in under six hours, very awesome my friend, very awesome indeed.  So I can close this now and go about my day.  :-)

Keep up the good work guys!

**Comment by PromoFaux** [comment]
;) What can I say? I'm a speed demon. :smile: 

Actually in all honestly it would have been quicker.. but I've just got intelliJ Idea installed, and I was grappling with how to work it!

**Comment by PromoFaux** [comment]
(also, providing the rest of the guys approve it, it'll be in the next release)
