### ISSUE TITLE
Request for a couple of options on command line

### ISSUE THREAD

**Issue by BiloxiGeek** [pi-hole/pi-hole#608]
Could you add in a couple options on the pihole command?

This one should be pretty easy.
-v:   Display pihole version and web version

-(letter of your choice):  Query for any available updates to pihole.  Could possibly combine this check into the -v check above.  Show what's running and show what's available.

Edit (Mcat12): Looks like the `<` and `>` from `letter of your choice` made the whole thing invisible. Changed to parenthesis.

**Comment by PromoFaux** [comment]
Both should be more than possible, if nobody has already done it, I'll take a look into adding them tonight when I get home.

They are both available on the dashboard in any case :)

**Comment by Mcat12** [comment]
The python rewrite currently has the version flag.

**Comment by PromoFaux** [comment]
In which case, I wont bother.

Actually I might, in case we don't release the python version for a million years!

**Comment by Mcat12** [comment]
You can certainly try to get it in the bash version. The Python rewrite is still in development; we haven't even gotten the API or web interface fully functional!

**Comment by BiloxiGeek** [comment]
It should probably be a function of the API as well.

**Comment by Mcat12** [comment]
Sounds good
