### ISSUE TITLE
There is an update available overlays home page

### ISSUE THREAD

**Issue by vinceskahan** [pi-hole/pi-hole#610]
With 2.8.0 installed, I'm nagged mercilessly to update by an overlay on your home screen which pops annoyingly over far too much of the screen.

Please change where your update available info appears, a small 'update available' thing to the left of the pihole logo would be plenty sufficient for notifying us, the massive rectangular popup is a bit much.

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #121](https://github.com/pi-hole/AdminLTE/issues/121) via [**ZenHub**](https://www.zenhub.com/)
