### ISSUE TITLE
youtube.com in browser stopped working after last gravity pull

### ISSUE THREAD

**Issue by lukas947** [pi-hole/pi-hole#611]
##### Expected Behaviour:

youtube.com in browser should show page but not ads
##### Actual Behaviour:

Before gravity pull youtube was showing ads as if it was without pihole. After gravity pull shows just ERR_QUIC_PROTOCOL_ERROR in chrome, or nothing in edge / IE. 
![image](https://cloud.githubusercontent.com/assets/13629192/17445995/91955698-5b47-11e6-8e33-2530c8f5a255.png)

Tested on two different installations on debian 8.5 and ubuntu 16.04
##### Steps to reproduce this issue:
1. before update check functionality of youtube.com
2. login to pihole and run "pihole -g"
3. check youtube again when script is done 
##

**Comment by PromoFaux** [comment]
Could you please paste in the results of running `pihole -d`, thanks.

**Comment by lukas947** [comment]
Of course, [here](http://termbin.com/0ew5) you go

**Comment by jacobsalmela** [comment]
YouTube is a moving target.  The log looks OK.  I'll check it out this weekend on my Pi-hole

**Comment by lukas947** [comment]
Perfect, thank you!

**Comment by shopro** [comment]
I'm pretty sure that the problem is with pihole, since bypassing it fixes the problem.

**Comment by lukas947** [comment]
I would not say it's a problem... This is simply a new situation we have to deal with, since something apparently changed on youtube side, so when ads are not shown / dowloaded / do not have hits no other content is shown.

While discussing this matter, it's quite interesting to see how they made it this way. It does not really seem youtube/google solution, but rather quick and dirty workaround. So instead of showing nice HTML5 error message, they blocked it on application layer hence the unusual error. 

You actually triggered my curiosity further more (because this is not problem of pihole), so i started to dig around and found some interesting evidence:

I ran network packet capture to see what's going on in particular, and found that my client(s) and youtube talk correctly, but at certain point youtube replies with HTTP/1.1 301 Moved permanently. This is a new behavior not experienced before. So there **is** somebody working on it as we speak.

I also noticed that when I probed youtube serveral times and several ways - HTTP, HTTPS, Edge, IE, Chrome, Chrome Incognito; it has finally loaded correctly like before this thread. It's important to say this does not affect Android and iOS devices, but this situation is strictly limited to x86 / x64 platforms.

Without saying it's conspiration we should probably acknowledge that blocking ads on youtube makes google loose a lot of money, and this is for sure not last counter action to get every penny back. For me personally ads in general are fine, and sometimes (well rather rarely) amuse me enough to even click them, but it's obnoxious advertising practices which led me to the critical measure of blocking ads on network level. 

To put a lid on this... i still want to use pihole for all sites with 10KB of content and couple of megs of ads. And it's also making a great job as wall against advertisers spreading malware / spyware via ads. So in conclusion I will whitelist youtube ads. 

Nevertheless i would like to keep this thread open, since whitelisting is a workaround and not a root cause with solution...

**Comment by ShoGinn** [comment]
I'll chime in and say this, I noticed the same thing; here **WAS** the culprit.

`./list.7.hosts-file.net.domains:127.0.0.1	youtube-ui.l.google.com`

But a nice `pihole -g` updated the hosts-file.net blocks.

**Comment by jacobsalmela** [comment]
@lukas947 do you have any additional information in the months since your last post?

**Comment by lukas947** [comment]
Hi, I did not have time to perform proper testing lately... But as it seems from preliminary tests google made changes in chrome, so it is not dependent on client dns anymore. I have to do more tests in other browsers. 

Isn't there anybody else suffering the same problem?

**Comment by lukas947** [comment]
I tested functionality in various browsers this weekend, and this particular problem with youtube seems to be solved in latest version. Thank you!
