### ISSUE TITLE
Any plans for opensuse support? Or: how could the community help for that??

### ISSUE THREAD

**Issue by jpluimers** [pi-hole/pi-hole#614]
Since my system is opensuse based: any plans for that?

If so: how could the community help? Where to start?

My particular system is apache on opensuse (I think apache is the default there).

It might be possible to use some of the ideas of https://github.com/certbot/certbot to support opensuse.

--jeroen
##

**Comment by dschaper** [comment]
Hi, we'll certainly take a look. I haven't used the OpenSUSE platform before, but it looks like Kiwi can create VM's so it's definitely worth spinning up to see if we can support it. With Certbot, are there any code examples that highlight SUSE integrations?

**Comment by jpluimers** [comment]
opensuse has some differences in apache vhost handling. I've opened/responded to some issues there to get it resolved. Most of their code is in Python and I think most of your code is bash. I could fire up a new fresh opensuse Tumbleweed VM. Tumbleweed is the leading (sometimes but not often bleeding) rolling build and help you test.

Here are the steps (I need to update them, I know) of how I installed Tumbleweed: https://github.com/jpluimers/OpenSuSE.Tumbleweed.Server-Install

**Comment by dschaper** [comment]
IRC is one of the few channels that we don't have an active presence. We do have gitter, however. We are in a total rewrite of the code to Python and moving away from bash as we need some other features that will just end up bloating out bash and causing some ugly code. We'll flag this to take a deeper look into it.

**Comment by jpluimers** [comment]
Which of the gitter communities should I check? I found these:

- https://gitter.im/diginc/docker-pi-hole
- https://gitter.im/pi-hole/AdminLTE
- https://gitter.im/pi-hole/pi-hole

**Comment by PromoFaux** [comment]
`/pi-hole/pi-hole` is for the base pi-hole project.
`/pi-hole/AdminLTE` is for the web admin.
`/diginc/docker-pi-hole` is for the docker image that @diginc has developed.

pi-hole dev's can be found in any one of the first two, and if you have specific docker-based chat.. then digincs channel! :)

**Comment by jpluimers** [comment]
@PromoFaux this should go in the readme as this query won't find it: https://www.google.com/search?q=gitter+site%3Agithub.com%2Fpi-hole%2Fpi-hole

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/17669576/14f3b8ca-6306-11e6-90f4-f9c5bb242e18.png)

;)

**Comment by jpluimers** [comment]
Maybe add text `gitter` there as well. I could not find searching `gitter` and overlooked it because the high number of colourful areas on that page distracted me too much.
