### ISSUE TITLE
(mod_fastcgi.c.2520) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '[' in /var/www/html/admin/data.php on line 68

### ISSUE THREAD

**Issue by changchichung** [pi-hole/pi-hole#617]
install on new CentOS 6.6 x64 
shows no data in graph and there`s log repeat as title in lighttpd error.log
##

**Comment by Mcat12** [comment]
Run `pihole -d` and post the link. Most likely, your PHP version is too old. I think CentOS has PHP 5.3 or something, while currently the web interface requires 5.6 (we're looking to lower this).

**Comment by changchichung** [comment]
yes , php 5.3
rpm -qa |grep php
php-common-5.3.3-47.el6.x86_64
php-cli-5.3.3-47.el6.x86_64

I manually comment out data.php line 68-75 , then everything works ...
