### ISSUE TITLE
Should rollbar.com be blocked?

### ISSUE THREAD

**Issue by mikescott** [pi-hole/pi-hole#618]
Rollbar is a tool used by developers to catch bugs in their applications. It doesn't serve ads and it doesn't collect any more data than what the developer of the non-blocked site that uses Rollbar would have had access to anyway.

As a user of Pi-hole, I wouldn't expect something like this to be blocked as getting bugs fixed in the sites I use benefits me.

Similar services, such as bugsnag.com and getsentry.com are not blocked.

**Comment by dschaper** [comment]
We actually don't have a say in what is blocked or not blocked, that is all dependent upon the blocklists that you use. What we do add is the ability to customize the blocklists via a whitelist or blacklist. So the quickest and easiest solution to this problem would be to whitelist the domain. 

If you'd like to go further and contact the author of the adlist that is causing the domain to be blocked then that would also solve the problem.

**Comment by mikescott** [comment]
Thanks @dschaper - is there a way I can find out which list caused the domain to be pi-holed?

**Comment by dschaper** [comment]
I think we're working on a web interface feature to pull up the list name but for now try running `egrep -lir --include=*.domains "(rollbar)" /etc/pihole` and see if that lists out the name of the file. That should let you know who has the domain on their blocklist.

**Comment by dschaper** [comment]
@mikescott Were you able to resolve this issue and track down the list that was blocking the domain?

**Comment by dschaper** [comment]
Closing outside issue, please reopen if problem persists.

**Comment by the-simian** [comment]
@mikescott I noticed today that bugsnag is being blocked currently
