### ISSUE TITLE
Pi Hole is not working. Admin page is not loading, and Lighttpd is failing. Noob alert

### ISSUE THREAD

**Issue by cdb8457** [pi-hole/pi-hole#620]
##### Expected Behavior:
Pi Worked at the start, After about a week it has stopped working. Admins page should be loading and Pi hole should be blocking ads.

##### Actual Behaviour:

Nothing is working

##### Steps to reproduce this issue:

I have tried to reinstall pi hole numerous times and it goes well. I try to log into my admin page, but no dice. I checked dnsmasq and it was working, but lighttpd is actively failing.

![capture](https://cloud.githubusercontent.com/assets/21016001/17646798/22be3ada-618e-11e6-8972-5b270383058d.PNG)

**Comment by dschaper** [comment]
It's showing as unable to bind to Port 80, do you have another webserver installed on the hardware?

**Comment by cdb8457** [comment]
maybe a dns server can I take that off?

**Comment by cdb8457** [comment]
![capture2](https://cloud.githubusercontent.com/assets/21016001/17646873/d4df8392-6191-11e6-93f8-3ac6ac6cd83c.PNG)

How do I get rid of apache?

**Comment by dschaper** [comment]
Did you install another package that depends on Apache? You can do a `sudo apt remove apache2` but if that's required by another package you have installed then you risk breaking something else. Are you able to start with a fresh Raspbian image and then install the Pi-hole?

**Comment by cdb8457** [comment]
Thanks! You helped out a lot. New to this and really liking pi hole so far. I just purged apache2 found a command and i will look to see what was using it later! Your the best!

**Comment by dschaper** [comment]
Let us know if you run into any other problems! And thanks!
