### ISSUE TITLE
Pi Hole keeps blocking Domotz from scanning even though it's white listed

### ISSUE THREAD

**Issue by itmightbekyle** [pi-hole/pi-hole#621]
Orginal Reddit Thread: https://www.reddit.com/r/pihole/comments/4xk79l/how_to_make_pi_hole_not_block_ads_on_localhost/

As stated in the Reddit thread, I use Domotz on the same Pi that I run Pi Hole on. 
Domotz scans my network, but I keep seeing 212.0.0.10.in-addr.arpa being Pi holed. So I added it to the whitelist, but it is still being Pi Holed. Domotz doesn't show my Pi in it's list of attached devices.

dschaper wanted me to run `dig 212.0.0.10.in-addr.arpa` below is the result.
````
; <<>> DiG 9.9.5-9+deb8u6-Raspbian <<>> 212.0.0.10.in-addr.arpa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3388
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;212.0.0.10.in-addr.arpa.       IN      A

;; Query time: 87 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Aug 13 23:48:25 MDT 2016
;; MSG SIZE  rcvd: 52
````

**Comment by dschaper** [comment]
It doesn't appear to be blocking that query. The status of NXDOMAIN in the response just means that there is no A record for the requested domain. Here's a little primer on that aspect https://www.dnsknowledge.com/whatis/nxdomain-non-existent-domain-2/

If the request was being Pi-hole'd then there would be a response consisting of the address of the Pi-hole. I'm not sure how to exactly proceed on the troubleshooting. Basically what is happening is that the Pi is trying to figure out if 10.0.0.212 has a FQDN to address the Pi as. I don't think whitelisting would do anything as there is no response to be generated, hence the NXDOMAIN.

What is the response from `dig` if you take the Pi-hole out of the operation. Does Domotz add the 10.0.0.212 records to a host file for resolution?

**Comment by dschaper** [comment]
https://www.reddit.com/r/pihole/comments/4xqi70/any_incompatibility/

@itmightbekyle Does this post help, mentions moving Domotz to a different port?

**Comment by dschaper** [comment]
Closing for outside issue, please reopen if problem persists.
