### ISSUE TITLE
Pi Hole Not block ads. Admin page states 0 - 1 Ads Blocked

### ISSUE THREAD

**Issue by cdb8457** [pi-hole/pi-hole#622]
##### Expected Behaviour:
Pi Hole blocking ads

##### Actual Behaviour:
Pi hole not blocking ads - Shows around 0 to 1

##### Steps to reproduce this issue:

Reinstalled Pi hole several times

![no blocking](https://cloud.githubusercontent.com/assets/21016001/17720736/269447c4-63d9-11e6-8fe9-ea80c407e685.PNG)

**Comment by cdb8457** [comment]
![gravity](https://cloud.githubusercontent.com/assets/21016001/17720797/acf59b56-63d9-11e6-9621-605d694b69a8.PNG)
 after running pihole -g

**Comment by cdb8457** [comment]
www.termbin.com/58lp

pihole -d

**Comment by dschaper** [comment]
How have you configured your client machines to point to the Pi-hole as their DNS server?

**Comment by cdb8457** [comment]
![dns 2](https://cloud.githubusercontent.com/assets/21016001/17721036/bf4e2e88-63db-11e6-96b7-45f627adad46.PNG)

![dns 1](https://cloud.githubusercontent.com/assets/21016001/17721037/c29548a6-63db-11e6-810b-7023efd0cb34.PNG)
 

Is there more than this? If so I haven't done it yet.

**Comment by dschaper** [comment]
And on the Pi-hole, what is the contents of `/etc/resolv.conf`?

**Comment by cdb8457** [comment]
![resolv](https://cloud.githubusercontent.com/assets/21016001/17721142/d6b7bb2e-63dc-11e6-9877-afe017056fd4.PNG)

**Comment by dschaper** [comment]
Try a `sudo cat /etc/resolv.conf` and that should list the file contents. It should be set to `127.0.0.1` but it looks like it may be set to a different server.

**Comment by cdb8457** [comment]
No such file? Weird

**Comment by dschaper** [comment]
Is this a fresh install of Raspbian Jessie, or are you running another OS on the Raspberry Pi?

**Comment by cdb8457** [comment]
127.0.0.1

**Comment by cdb8457** [comment]
gawd typo, sorry

**Comment by cdb8457** [comment]
so is that my dns?

**Comment by cdb8457** [comment]
![capture09](https://cloud.githubusercontent.com/assets/21016001/17721299/16e6dada-63de-11e6-9796-2f379950681c.PNG)

**Comment by dschaper** [comment]
That looks good, but just checked the debug again and `dnsmasq` which is the DNS server, is set to some non-standard settings. It's showing that it's running with `/usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
`

So it's actually looking at `/var/run/dnsmasq/resolv.conf` instead of `/etc/resolv.conf`. I'm not sure how that was changed, we don't touch the files that configure that section?

**Comment by dschaper** [comment]
What does `apt-cache policy dnsmasq` report as the installed version?

**Comment by cdb8457** [comment]
![apt](https://cloud.githubusercontent.com/assets/21016001/17721447/144e807e-63df-11e6-91e3-aa41b64b7baa.PNG)

**Comment by cdb8457** [comment]
![dns33](https://cloud.githubusercontent.com/assets/21016001/17721490/690a57e6-63df-11e6-8094-68542e1c2420.PNG)

**Comment by dschaper** [comment]
Have you made any other configuration changes, or added any other packages besides running the Pi-hole install script? Something has corrupted the `dnsmasq` configuration.

**Comment by cdb8457** [comment]
well i tried to use bind9 at one point, I think that was one.

**Comment by dschaper** [comment]
Okay, how about a look at `/etc/default/dnsmasq` file contents to see if there are any overrides in there.

**Comment by cdb8457** [comment]
![default](https://cloud.githubusercontent.com/assets/21016001/17721609/689be1d4-63e0-11e6-850c-cea137f39708.PNG)

**Comment by cdb8457** [comment]
I am new to this, feel like I am typing wrong commands

**Comment by dschaper** [comment]
No, you're doing fine, we just need to find where the flags are being set. Let's try 'apt-cache policy resolvconf` and see if bind removed that package when it installed.

**Comment by cdb8457** [comment]
![resolvconf](https://cloud.githubusercontent.com/assets/21016001/17721737/6b2330f0-63e1-11e6-8cbc-499ac557bf62.PNG)

**Comment by dschaper** [comment]
Okay, `sudo apt install resolvconf` and the reboot the Raspberry Pi. Then one more look at `/etc/resolv.conf` once it's rebooted to make sure everything is still configured correctly and you should be okay.

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/17721838/2488730c-63e2-11e6-872d-f646e3646b51.png)

**Comment by dschaper** [comment]
Good, you should be able to see it working now. Try a few sites and then check the admin page again.

**Comment by cdb8457** [comment]
Well also I am viewing my pi from remote connection... Would that mes  anything up?

**Comment by dschaper** [comment]
No, shouldn't cause any problems.

**Comment by cdb8457** [comment]
Thank you again! You strictly a pi hole dev? Its working!

**Comment by dschaper** [comment]
We're all volunteers that work on the project in our time off from our regular jobs...

**Comment by cdb8457** [comment]
WOW, well thank you. Its definlty hard to look for the answers myself. Thanks again!

**Comment by dschaper** [comment]
Sure! Thanks for using the Pi-hole!

**Comment by WitnessMee** [comment]
The command `sudo apt install resolvconf` also fixed it for me. 

It didn't work for me when I installed Raspbian Jessie Light on Raspberry Pi 2 and then did `curl -L https://install.pi-hole.net | bash`
Perhaps Jessie Light is missing resolvconf?

Also a note: One of the test sites I used was http://ads-blocker.com/testing/
Which was not a good idea, because it seem pi-hole did not black list it. Also the site is actually selling ad blocking itself.
Fortunately all ads on "real" sites like facebook, yahoo, ... where blocked fine.

It's working really fast, I love it. Keep up the good work!

**Comment by SimplyCorey** [comment]
I also had to run `sudo apt install resolvconf` to get mine to work correctly.

**Comment by kunalspathak** [comment]
I tried above suggestion `sudo apt install resolvconf` but for me I don't think it is working. My system showed exact same things that @cdb8457 shared in this issue.

I have also verified that ads are being shown on web sites.

![image](https://cloud.githubusercontent.com/assets/12488060/21563116/5421231e-ce33-11e6-949f-6216a920409a.png)

**Comment by dschaper** [comment]
Please open a new issue and fill out the issue template so that we can track the issue if the previous solutions did not work for you. Thanks.
