### ISSUE TITLE
Total number of "Domains Being Blocked" is lower than other Pihole users

### ISSUE THREAD

**Issue by kuerious** [pi-hole/pi-hole#627]
##### Expected Behaviour:
Total number of "Domains being blocked" should increase. There is no reason I can determine why another Pihole user's total count is higher than my instance.

##### Actual Behaviour:
Even after a re-install and all manual updates I can try, the total number has not change from 99,073. The only step I have not yet done is to blow away the entire VM and start over.

##### Steps to reproduce this issue:
Install instance of Ubuntu Server 15.10
Update & upgrade.
Run pi-hole script
Allow to run
View the Admin console

**Comment by kuerious** [comment]
See screenshot. This is after a re-do of the CURL script for Pi-hole itself. The original instance had run for 24 hours and was working fine, BEYOND the actual "total domains blocked" number never growing.

https://i.imgur.com/LJTZoH2.png

**Comment by PromoFaux** [comment]
Can you please run `pihole -d` and paste the link?

Also the output of `ls -l /etc/pihole` 

Thanks!

**Comment by kuerious** [comment]
First:
http://termbin.com/vmr5

Second:
https://i.imgur.com/WVUI86K.png

**Comment by PromoFaux** [comment]
It doesn't look like there is anything wrong with your install, though I'm noticing mine only has 99,073 domains now. My guess is one of the default lists has changed in some way...

**Comment by PromoFaux** [comment]
Found it.. Malwaredomains (one of the default lists) have removed ~6000 domains, and added ~2000

[Source](http://www.malwaredomains.com/?p=4061)

**Comment by kuerious** [comment]
So what does this mean, then?

**Comment by PromoFaux** [comment]
From the link:

>Added 2265 domains to our list and removed 5938 since our last update. New ransomware variants 
have been spotted and the domains we found distributing the malware have been blocked. Thank you for using Malware Domains.

**Comment by kuerious** [comment]
So ... 99,074 is normal (for now), then?

**Comment by PromoFaux** [comment]
Looks that way, they updated the list on the 19th august, so most peoples will still be showing 101,000 (or however many it used to be) until tomorrow night when gravity runs automatically, unless they've recently reinstalled/ran gravity manually.

**Comment by kuerious** [comment]
Thanks. I recognize that it still works, I just wanted to be sure that the total # was accurate.
