### ISSUE TITLE
Feature request: admin web interface over HTTPS

### ISSUE THREAD

**Issue by jpluimers** [pi-hole/pi-hole#630]
It would be nice if the admin web interface could be reachable over HTTPS with a (self-signed) certificate out of the box.

HTTPS makes it a lot harder to tamper with data and given the movement to HTTPS would make it a logical step for the future.
##

**Comment by dschaper** [comment]
We have debated the scripting and auto install of a self-signed certificate, and my personal feeling is that for something of a certificate, the user really needs to be the driving force. There are too many questions that need to be answered, the CN for the certs, the level of encryption (do we go EC or non-EC). And then there is the location of the keys public and private. Lastly is the configuration of the webserver and the myriad of choices as to ciphers (see https://mozilla.github.io/server-side-tls/ssl-config-generator). It's just a situation that I feel we can't do an adequate job of via an install script. 

What are your feelings, do we use a less secure setup and then let the user increase the level of security so they can pass from a D to an A, or do we just let the users do the whole thing and tailor it to their needs? With the proliferation of Let's Encrypt and the guides available for that solution, I think the users should be in charge.

**Comment by jpluimers** [comment]
In my experience, despite letsencrypt and startssl, lots of users are still afraid of enabling TLS/SSL. So any system that helps them getting some baseline having TLS/SSL would be favourable to me.

Thanks for the ssl-config-generator tip: its a great tool I didn't know about yet.

**Comment by dschaper** [comment]
I'm very open to a wiki that walks through the steps, I've been running Acmetool from hlandau in the Github repo, on phone so I will update with link, but it's very useful. I've set up close to a dozen certs with it.

**Comment by dschaper** [comment]
https://github.com/hlandau/acme is the tool I use to gen most of my certs. I use the DNS hooks to create the TXT records for validation instead to doing it via webserver and it's really clean.

**Comment by jpluimers** [comment]
Though a pi-hole system is providing DNS it usually isn't authoritative for a particular domain, so I think another mean of validation would work better.

For me to get started: where is the lighthttpd config generated?

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/tree/master/advanced is the location that stores all the prebuilt configs, then they are sourced/copied into their directories via the basic install script.

**Comment by jpluimers** [comment]
OK. I'm a bit pressed for time as always, but will see what I can do before conference season starts.

On a related thing: I also posted an issue on https://github.com/pi-hole/AdminLTE but later found out that is quite a bit behind on https://github.com/almasaeed2010/AdminLTE

- Who is monitoring AdminLTE issues?
- What version of AdminLTE is installed by pi-hole?

**Comment by dschaper** [comment]
Our fork for AdminLTE had diverged from the parent so much that a pull from the almasaseed2010 would most likely cause severe breakage. We're actually going to be leaving the AdminLTE code in a little bit to use our own code for the admin interface. And the issues are monitored by the same team that handles this repo. 

We all are volunteers on the project and work on it in our free time away from our full time jobs, so we get to things as quickly as possible.

**Comment by jpluimers** [comment]
Thanks for the update. I bear with you. Same for my contributions to the OS world: all spare time work.

**Comment by IMcPwn** [comment]
If you are using LetsEncrypt you could possibly use free_tls_certificates (https://github.com/mail-in-a-box/free_tls_certificates).
It's a python library for Let's Encrypt.

**Comment by dschaper** [comment]
Thanks @IMcPwn, always on the lookout for new libraries to help get things done!

**Comment by jacobsalmela** [comment]
[Making this feature votable in orbit](https://discourse.pi-hole.net/t/admin-web-interface-over-https/562).

**Comment by maxbla** [comment]
To sum up the discussion on discourse, Pi-hole does not plan automatically activate SSL/TLS, but there is an official guide for doing so (manually). See https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/admin-web-interface-over-https/562/1
