### ISSUE TITLE
Pi-hole Admin console GUI not updating after last web interface update.

### ISSUE THREAD

**Issue by odinb** [pi-hole/pi-hole#631]
##### Expected Behaviour:
GUI to show information in all fields.

##### Actual Behaviour:
GUI not showing information in all fields.

##### Steps to reproduce this issue:
Load Web GUI.

Hi!

After I initially installed pi-hole on my pogoplug with debian Jessie (Linux version 4.4.0-kirkwood-tld-1 (root@tldDebian) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 PREEMPT Mon Jan 25 20:35:24 PST 2016), the GUI was populating correctly.

However, there was an update to the web interface a couple of days ago, and after that, the web-GUI no longer updates all fields. Sometimes some fields will be populated, but it is random.
Now installed: Pi-hole Version v2.8.1 Web Interface Version v1.4.

Have tried to:
Reboot the server.
Made sure "/var/log/pihole.log" has the correct permissions (chmod 644, chown dnsmasq:root).
Reinstalled Pi-hole (curl -L https://install.pi-hole.net | bash) and rebooted.

It just won't work anymore.
Image: http://i.imgur.com/D3sv8tG.png

Is it a timing issue? I see the load being high if I refresh the GUI, monitoring with "top". I also see a bunch of "php-cgi" processes being the reason behind the high load. Once they settle, load goes down to under 1% CPU. every now and then, the "php-cgi" processes will come back for a bit, causing high load momentarily again. Thinking maybe the timers for these processes are too short, and they do not finish before timing out?

**Comment by Mcat12** [comment]
I think it might just be timing, since the code controlling this stuff wasn't really changed in the update. One thing to watch out for, if the pi has a large load, is to not keep refreshing the admin site. Each time you refresh, it queues up new PHP processes to compile the stats again. So it might work quickly the first time, but if you refresh a lot, it will slow down. This is mainly a result of it running on a Pi, and how we generate stats (no database; have to read in the whole log file every time).

Also, since we have to load in the whole log file, having a lot of DNS requests in the log can cause the processes to slow down far enough that it takes more than 30 seconds to return the stats or use too much memory; things PHP doesn't like. So if it takes longer than 30 seconds or uses too much memory, it kills the process and you're left with no data for that widget.

With the Python rewrite, we're partly focusing on performance. We're going to use a database for logs, which should greatly speed things up.

**Comment by odinb** [comment]
So how can I extend the timeout to beyond 30 seconds for php?

**Comment by dschaper** [comment]
That's a general PHP configuration, and not one that is specific to Pi-hole, but if you post the output from `php -v` I can see if I can track down the config flags and point you in the right direction to expanding the timeout period.

**Comment by odinb** [comment]
root@pi-hole:/etc/lighttpd# php -v
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 14:48:25)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
root@pi-hole:/etc/lighttpd#

**Comment by Mcat12** [comment]
Try `php --ini`

**Comment by Mcat12** [comment]
Most likely, it will show that the configuration file is at `/etc/php5/cli/php.ini`, but it's good to check anyways.

**Comment by odinb** [comment]
root@pi-hole:/etc/lighttpd# php --ini
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /etc/php5/cli/conf.d
Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-json.ini

root@pi-hole:/etc/lighttpd#

**Comment by odinb** [comment]
Think this is the one that needs changing:
`;;;;;;;;;;;;;;;;;;;
; Resource Limits ;
;;;;;;;;;;;;;;;;;;;

; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 30`

Should I go to 60, and take it from there?

**Comment by odinb** [comment]
What does this one do? Leave it at current I assume?

; Maximum amount of time each script may spend parsing request data. It's a good
; idea to limit this time on productions servers in order to eliminate unexpectedly
; long running scripts.
; Note: This directive is hardcoded to -1 for the CLI SAPI
; Default Value: -1 (Unlimited)
; Development Value: 60 (60 seconds)
; Production Value: 60 (60 seconds)
; http://php.net/max-input-time
max_input_time = 60

**Comment by odinb** [comment]
There is this one also, I assume I should leave this one also:
; Default timeout for socket based streams (seconds)
; http://php.net/default-socket-timeout
default_socket_timeout = 60

**Comment by Mcat12** [comment]
`max_execution_time` should be the only one you need to change. You can also set it to 0, for no time limit.

**Comment by odinb** [comment]
Have it set at 600, and still only see the spinning arrows...nothing seems to take up any large amount of CPU using "top".

**Comment by Mcat12** [comment]
Run `pihole -d` and post the log link.

**Comment by odinb** [comment]
http://termbin.com/gms7

**Comment by odinb** [comment]
Ok, gave up on this, and just left it! everything except the GUI seemed to work! Now after the latest update (Pi-hole Version V2.9.1 Web Interface Version v1.4) it started working again! Did not do anything aside from updating/reinstalling!

**Comment by dschaper** [comment]
Great, not sure what may have changed to fix it, but glad to know it's working again for you. Closing out the issue for now, re-open it if you run into issues again.
