### ISSUE TITLE
possibility to add some sources

### ISSUE THREAD

**Issue by positroni** [pi-hole/pi-hole#634]
Hi,
first I would like to thank you for the magnificent piece of software. It's amazing and super useful.
Before Pihole I always used the [adblock](https://github.com/openwrt/packages/tree/master/net/adblock/files) script on Openwrt.

The amount of URLs that Pihole blocks is bigger than Adblock, but Adblock blocked more ads from the site that I usually visit.
That is why I would like to ask if it is possible to add some of its sources, in particular:
-[shalla](http://www.shallalist.de/Downloads/shallalist.tar.gz) (categories 'adv', 'costtraps', 'spyware', 'tracker', 'warez')
-[whocares](http://someonewhocares.org/hosts/hosts)
-[disconnect](https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt) (i.e. simple_melvertising.txt)
-[adaway](https://adaway.org/hosts.txt)
-[yoyo](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0&mimetype=plaintext)

I tried to add these URLs on the list source but the number of domains blocked in the WebGUI of Pihole remained the same.
Thank you!

**Comment by PromoFaux** [comment]
Hi there, ok so three of those lists (yoyo, adaway, and whocares), are already included in the default list via @StevenBlack 's [host list](https://github.com/StevenBlack/hosts).

To add a list to your `adlists.list` file, you need to make sure that it is in a hosts file format (not zipped up like the shalla list you linked to!)

**Comment by PromoFaux** [comment]
ping!

**Comment by positroni** [comment]
Sorry, I forgot to say that everything's fine.
I wrote a script that downloads and updates some of the categories in shalla and then I added the domain files in the source list.
Thanks for the support!
