### ISSUE TITLE
admin panel ajax error

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#638]
am getting this error while looking on my query logs. some of the graphs dont appear they just keep spinning.

DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![capture1](https://cloud.githubusercontent.com/assets/15007183/18050262/81fc4710-6dbb-11e6-8d3e-a69f5d2c2cf4.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/18050264/85fdeb2a-6dbb-11e6-9876-4a1dc7bd9319.PNG)

**Comment by PromoFaux** [comment]
Hi there, that's quite a lot of queries (I think... I've not actually looked at my admin page for a while....) How many devices do you have connected?

Does it run fine at the start of the day? It may just be that there are so many queries that it is struggling under the load. What device do you have pi-hole installed on? Can you please post the results of a `pihole -d`? Also try doing a `pihole -f` (flush the logs) to see if that fixes it.

**Comment by xxcriticxx** [comment]
i have about 10 devices running on this network 

pi-hole is installed on Ubuntu 16.04.1 LTS (3.07ghz cpu, 8 gb ram, 1tb hd)

runs correct for about day pihole -f helps is but tomorrow we have same scenario

Debug log can be found at : http://termbin.com/08xt

**Comment by PromoFaux** [comment]
`2016-08-28 19:20:20: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/admin/data.php on line 176`

There may be something in this... @Mcat12 is the PHP guy... any ideas?

**Comment by Zegnat** [comment]
> `2016-08-28 19:20:20: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/admin/data.php on line 176`
>
> There may be something in this...

That is where the entire pihole.log file is read into memory at once. It might be worth switching over to `fopen`/`fgets` and go through the log file line-by-line to save memory.

(At some point I should really get a Pi-Hole dev environment up and running instead of just commenting with ideas.)

**Comment by xxcriticxx** [comment]
i guess we wait for @Mcat12 to show up

**Comment by stonedbovines** [comment]
You could always flush the log daily. Do you ever want to actually do anything with the contents of the log?

For example, I have a daily process a few minutes before midnight that makes a dated copy of the log file and then flushes it ready for the new day. I can then tinker with the log file to my hearts content (to produce a more detailed breakdown than the smoothed graph shows) and eventually delete the dated files.

**Comment by PromoFaux** [comment]
>you could always flush the log daily

No need, this is already done at 11:55 pm on a preinstalled cron job, though minus the backup. :)

@xxcriticxx as a temporary measure, you could try increasing the amount of [memory PHP is allowed](http://stackoverflow.com/a/22283701) however it's likely that this is a due to how we've coded the log parser.

**Comment by CDeeRON** [comment]
This issue is reported every so often see #465

**Comment by PromoFaux** [comment]
Similar, no doubt, but slightly different. Wasn't that to do with how many domains were in `gravity.list`? This appears to be down to the sheer size of the log.

**Comment by CDeeRON** [comment]
Agree, wondering if the `memory_limit` for php could be checked/increased during pi-hole install? Default is what 128mb?

**Comment by PromoFaux** [comment]
I think it's best we try to find a way to make the log read more memory efficient, rather than chuck more ram at the problem!

Perhaps we could `curl http://downloadmoreram.com/download.html` :)

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #130](https://github.com/pi-hole/AdminLTE/issues/130) via [**ZenHub**](https://www.zenhub.com/)
