### ISSUE TITLE
[Feature Request] Password Protect Admin Page

### ISSUE THREAD

**Issue by Addicted5** [pi-hole/pi-hole#641]
Hi, without password protection ,anyone can access pihole admin page.
That means everyone in my local network can know browsing history.
So how to password protect it?
##

**Comment by PromoFaux** [comment]
Unfortunately we don't have password protection enabled by default at the moment (probably should get around to adding that!) but you could take a look at @jacobsalmela 's guide on [his blog](http://jacobsalmela.com/password-protect-a-lighttpd-web-server-on-a-raspberry-pi-using-mod-auth/) on how to password protect lighttpd (which Pi-hole uses)

**Comment by stonedbovines** [comment]
The link provided works well but the pihole upgrade process (at least from v2.7 to v2.9) overwrites /etc/lighttpd/lighttpd.conf disabling the password protection.

**Comment by DonLexos** [comment]
If lighttpd supports .htaccess that could also provide a solution, since the admin page is in a seperate folder (although I am not sure if it woul be purged on an update).

**Comment by stonedbovines** [comment]
Unfortunately, lighttpd doesn't support .htaccess

I ended up just knocking up a script to replace the missing lines after an upgrade. There are a number of things I want done differently to the standard package, so that all gets done as a post-upgrade process.

**Comment by brantje** [comment]
Just curious, what does that script do?

**Comment by stonedbovines** [comment]
Gets rid of the cronjobs, as I need it to do some of those things at different times, and do some of it differently. I have my own set of jobs already set up on my username. It's just easier to kill everything and use my own, rather than checking for any new additions. They all get commented out, rather than just deleting the new file, so I can always check for any new stuff that gets introduced.

Reinstates the password protection. The main part of that lives in a separate file, so the conf file that the upgrade overwrites needs to have the ability to use auth plus the link to the separate auth file added back in to it.

**Comment by stonedbovines** [comment]
I thought there was a third thing it did, but that is just a commented 'keep an eye on' at the moment. I am watching to see what happens with 'log rotation' and 'log to database' as I will want to do something with those. They would definitely be things that I regain control over. :)

One of the additional jobs I have it do prior to the daily flush, is to break down the requests into a finer time period than hourly. It gets broken down into activity (# of requests) per 10-minute segment and that gets saved to a dated CSV (TSV actually) file. So, a mis-timed log rotation would mess with that. Similarly, logging to database would require me to grab that data differently.

**Comment by p1r473** [comment]
I attempted to follow Jacob's blog post about password protecting a web server. I followed the blog basically to the letter. However, my admin page does not prompt me for my username/password.
You can find my attempt at http://termbin.com/l0c2 under section lighttpd.conf

**Comment by stonedbovines** [comment]
`auth.require = ( "/admin/" =>`
you need the url fragment, not the filesystem location

`"realm"   => "<whatever name you used in the hashing phase>",`
unless you actually used `myrealm` (you can choose whatever word you want to use, but they have to match)

**Comment by p1r473** [comment]
Thanks, I will try this!

**Comment by p1r473** [comment]
Thanks, it works!

**Comment by jacobsalmela** [comment]
This is [a votable request](https://discourse.pi-hole.net/t/password-protect-the-dashboard/223) on Discourse.
