### ISSUE TITLE
Feature Request: Send e-mail or notification when pihole -up updates Pi-Hole

### ISSUE THREAD

**Issue by silentwolf15** [pi-hole/pi-hole#642]
Send e-mail or notification when pihole -up updates Pi-Hole
##

**Comment by PromoFaux** [comment]
Hi there, that command isn't set to update automatically, it has to be run by the user, so you would know if it was updated or not!

You could cover up with a script that does auto update though, by taking the output of `pihole -v` you can determine if there is an update available, and the run `pihole -up`

**Comment by silentwolf15** [comment]
Correct I have it set as a cronjob.. so it would be a nice option to have the ability to email

**Comment by PromoFaux** [comment]
Ah ok, it's a bit out of scope at the moment. All we've done by providing the version and update scripts is to give users the tools they need to set up their own auto-update scripts.

If you want some pointers on writing a script that will send you an email when it's finished running... take a look over [this solution on askUbuntu](http://askubuntu.com/a/522434)

**Comment by PromoFaux** [comment]
Also take a look at [this guide](https://www.nixtutor.com/linux/sending-email-alerts-through-cron/). Don't forget you'll need to set up an email server, too.

**Comment by jacobsalmela** [comment]
This is [votable on Discourse](https://discourse.pi-hole.net/t/send-e-mail-or-notification-when-pihole-up-updates-pi-hole/563).  But it _is_ out of scope at the moment.
