### ISSUE TITLE
Custom Config /etc/dnsmasq.d/01-pihole.conf

### ISSUE THREAD

**Issue by jodumont** [pi-hole/pi-hole#646]
##### Expected Behaviour:

- Not replacing my addn-host in the 01-pihole.conf and how adding a addns-hosts=/etc/pihole/custom.list

info : gravity.sh at line 32[7-9]
```
#Now replace the line in dnsmasq file
${SUDO} sed -i "s/^addn-hosts.*/addn-hosts=$adList/" /etc/dnsmasq.d/01-pihole.conf
dnsmasqPid=$(pidof dnsmasq)
```

##### Actual Behaviour:
If I had a dnsmasq this line change all my addn so 
The result will be a multiple addn line with the same gravity.list

##### Steps to reproduce this issue:

- Add another addn-host into 01-pihole.conf
- Reboot!

**Comment by PromoFaux** [comment]
I THINK i have my head around what you're asking... you want to have an additional list alongside gravity.list, right? It's best to leave any custom configurations out of the base pihole configs ads they are likely to get overwritten. Instead, you can create an additional file for your custom configs.

Create the following file:
`/etc/dnsmasq.d/02-custom.conf`

and in there add the line:
`addn-hosts=/etc/pihole/custom.list`

Restart dnsmasq to load in changes:
`sudo service dnsmasq restart`

**Comment by jodumont** [comment]
I knew it wasn't a real issue and thank for your clear instruction :)
because actually I tried something similar but it didn't work without your help!
