### ISSUE TITLE
Check for directory and file locations prior to utilization

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#647]
@dschaper commented on [Thu Sep 01 2016](https://github.com/pi-hole/AdminLTE/issues/132)

##### Steps to reproduce this issue: See https://www.reddit.com/r/pihole/comments/50kqmx/fyi_you_need_opt_before_running_the_installer/

---

@dschaper commented on [Thu Sep 01 2016](https://github.com/pi-hole/AdminLTE/issues/132#issuecomment-243959628)

Wrong repo...

**Comment by dschaper** [comment]
See #645
