### ISSUE TITLE
Feature Request: PiHole High Availability

### ISSUE THREAD

**Issue by ryanborstelmann** [pi-hole/pi-hole#648]
I'd love to see the option of running multiple PiHoles in your network and a means to keep all of them in sync (whitelists, etc). Ideally, only one would serve the Web Interface, and it would show stats for multiple PiHoles. (the other PiHoles could be "satellite" PiHoles or something)

The use case is the following: I have PiHole running flawlessly in an Ubuntu Server 16.04 VM in Hyper-V. But this is a single point of failure - when I reboot my Hyper-V host for updates, for example, the PiHole goes down. I want to implement a Raspberry Pi as well, so clients have a "backup" DNS that's also a PiHole. As it stands now, the backup DNS servers are just Google's 8.8.8.8 and 8.8.4.4, but I'd love the opportunity to make more PiHoles and minimize management overhead.
##

**Comment by diginc** [comment]
> a means to keep all of them in sync (whitelists, etc).

A NAS mount point for /etc/pihole would accomplish this, reloading dnsmasq on your secondary PH when the first PH modifies the nas whitelist would be tricky but it is do-able.  Something like a cron watching the modified date vs the last reload of dnsmasq or a PHP modification that SSH's to the 2nd pi-hole and runs the pihole reload for you should do the trick.

NAS becomes your single point of failure although...are you using a NAS for your Hyper-V VMs?  If so you've got bigger problems if it goes down.  Maybe something like GlusterFS would be better if you don't have a NAS with near 100% uptime.

**Comment by ryanborstelmann** [comment]
I've got two NAS devices, each running UnRAID. One is an offsite replica of the other (nightly rsync), and neither of them act as Hyper-V storage.

I'm not *too* worried about the PiHole being truly highly available, as I currently have Google's DNS servers as backups. It's more of a "It'd be a nice feature" sort of thing. For now, I can just use both PiHoles and sync up the whitelists manually - they honestly don't change much at all for me.

**Comment by diginc** [comment]
I'm just spit-balling some semi easy ideas for the current version becoming HA.  The next version written in python with a real back end database will probably be more ideal for this type of feature.

**Comment by jacobsalmela** [comment]
Migrating this to discourse.pi-hole.net since conversation has gone stale.  This request will now be votable: https://discourse.pi-hole.net/t/high-availability-ha-for-pi-hole/3138
