### ISSUE TITLE
pi.hole doesn't resolve

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#652]
##### Expected Behaviour:

http://pi.hole should resolve
##### Actual Behaviour:

http://ipaddress/admin works fine.
##### Steps to reproduce this issue:

Unknown.  Port from here: https://pi-hole.net/suggestions/bug-pi-hole-doesnt-work/
##

**Comment by jacobsalmela** [comment]
Closing due to no response.

**Comment by phelma** [comment]
This is not working for me either
Ubuntu 16.04.1
Raspberry Pi 2

from a machine on the network using the pi-hole dns

```bash
$ nslookup pi.hole

Server:		192.168.1.1
Address:       	192.168.1.1#53

** server can't find pi.hole: NXDOMAIN
```


```bash
$ dig pi.hole

; <<>> DiG 9.8.3-P1 <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51743
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pi.hole.      			IN     	A

;; Query time: 12 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sun Sep  4 20:14:44 2016
;; MSG SIZE  rcvd: 25
```

Also from the query logs  I notice that pi.hole is being Pi-holed sometimes. 
![pi-hole_admin_console](https://cloud.githubusercontent.com/assets/4057948/18233379/e2649888-72dd-11e6-9c80-a5a23070701d.jpg)
I have tried adding pi.hole to the whitelist but still no joy.

Can I help with any more diagnostic information?

**Comment by Mcat12** [comment]
Currently, any domain that resolves to the Pi-hole's IP should show up as "blocked", so that shouldn't be an issue (though I wonder why it's sometimes not "blocked"). Please generate a debug log with `pihole -d`. Also, how did you set your network to use Pi-hole?

**Comment by nomoreads** [comment]
Hi @jacobsalmela that was actually my bug report.

pi.hole gives a blank page while pi.hole/admin gives the admin panel (also piholeIP/admin gives admin panel) but i assumed that pi.hole would redirect automatically to the pihole admin panel.

**Comment by PromoFaux** [comment]
Hi @nomoreads `pi.hole `is just a hostname translation to `<whateveryourPiholeIPis>`, so you still need to type in the `/admin` to access the admin page :)

**Comment by PromoFaux** [comment]
@Mcat12 the `devel` branch of AdminLTE has code in to not count `pi.hole` or `<hostname>` as an ad, and therefore won't show up as pi-holed

**Comment by DL6ER** [comment]
This issue has been resolved.
