### ISSUE TITLE
iproute missing in OSMC

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#653]
##### Expected Behaviour:
iproute should be available

##### Actual Behaviour:
While installing pihole on an OSMC raspberry pi system I've noticed that currently the package "iproute" is missing in the apt-get install tool line. Suggesting to add that accordingly. (It might be included already in Rasbian so this is the reason this gap hasn't been detected yet)

##### Steps to reproduce this issue:
Unkown.  Ported from https://pi-hole.net/suggestions/iproute-package-is-missing/

**Comment by dschaper** [comment]
OSMC is going to cause other issues as well, looks like it uses Network Manager for interface address control. https://osmc.tv/wiki/general/setting-up-your-network-connection/

**Comment by jacobsalmela** [comment]
Like C.H.I.P., too.

**Comment by dschaper** [comment]
Exactly, would be interesting to see if `dhcpcd5` causes the same behavior, crashing the neighborhood...

**Comment by dschaper** [comment]
But that does make them not so much a corner case anymore. Checked to see if they run read-only and I don't see anything about that yet, so hopefully any changes made will stick and not be lost on reboot.

**Comment by Taijian** [comment]
I have pi-hole running on my pi with OSMC. iproute can be manually installed from the repo and once that is done, pi-hole does work. So from my use-case it seems like simply modifying the script to check for the presence of iproute and pulling it in if it is missing, should be enough.

**Comment by inconsx** [comment]
@Taijian 

did that but it doesn't work.
Did you any settings?

Cheers

**Comment by Taijian** [comment]
I simply did: _sudo apt install iproute2_

`osmc@osmc:~$ apt show iproute2
Package: iproute2
Version: 3.16.0-2
Installed-Size: 906 kB
Maintainer: Debian iproute2 Maintainers <ah-iproute@debian.org>
Replaces: iproute
Provides: arpd
Depends: libc6 (>= 2.14), libdb5.3, libselinux1 (>= 2.0.15)
Recommends: libatm1 (>= 2.4.1-17~), libxtables10
Suggests: iproute2-doc
Conflicts: arpd, iproute (<< 20130000-1)
Homepage: http://www.linux-foundation.org/en/Net:Iproute2
Section: net
Priority: important
Download-Size: 386 kB
APT-Manual-Installed: yes
APT-Sources: http://ftp.debian.org/debian/ jessie/main armhf Packages
Description: networking and traffic control tools
 The iproute2 suite is a collection of utilities for networking and
 traffic control.
 .
 These tools communicate with the Linux kernel via the (rt)netlink
 interface, providing advanced features not available through the
 legacy net-tools commands 'ifconfig' and 'route'.
`

**Comment by Taijian** [comment]
You do have to re-run the pihole install script afterwards, because without iproute2 some config options cannot be executed and you end up with a faulty config. Simply installing iproute2 after the fact does not fix this.

**Comment by inconsx** [comment]
@Taijian 

It works now, thanks!
Had to reinstall pi-hole completely.

Yeah a dependency check during the install script would resolve this issue for OSMC easily.

Cheers,
Michael

**Comment by jeroenvdw** [comment]
Came here to see if this issue was already known. Maybe I can confirm that "apt-get install iproute" did the trick.
One more concern though; my Kodi installation was already using port 80, for the web controller. Changed this, and now pihole works perfectly. However, would it be possible to change the port for the webserver pihole is running?

**Comment by mcblum** [comment]
Question about this. I just tried to install and on the `Checking for iproute2` line it just stopped. No error message or anything, just stopped installing. With the updates you made to the script, is that expected behavior?

**Comment by dschaper** [comment]
There's changes in the testing phase to solve that issue. If it just dropped you back to the command prompt, give it a second try and see if it will go through. Sometimes the `apt` cache is outdated and the way we were installing didn't know how to handle the case where `apt-get` throws an error. Should be fixed in the next release.

**Comment by mcblum** [comment]
@dschaper Awesome, thank you Dan!

**Comment by RIKWEBB** [comment]
Getting the same problem myself, drops me back to the command prompt at checking for iproute2.
I have run the install many times.
Is there any way of getting around this problem?

Rik

**Comment by DL6ER** [comment]
There will be a release soon which includes the proposed fix.

**Comment by RIKWEBB** [comment]
Solved :) eventually found this

(line 85)
PIHOLE_DEPS=( dnsutils bc dnsmasq lighttpd ${phpVer}-common ${phpVer}-cgi curl unzip wget sudo netcat cron iproute2 )
to
(line 85) PIHOLE_DEPS=( dnsutils bc dnsmasq lighttpd ${phpVer}-common ${phpVer}-cgi curl unzip wget sudo netcat cron iproute )
Changing iproute2 -> iproute as a final attempt, the whole thing continued with the installer and now it seems to be working. :)

from here https://www.reddit.com/r/pihole/comments/57xon6/pihole_293_released_install_script_overhaul_and_a/d8w93mu/?st=iwrtzpr0&sh=fd43dcb0
Rik

**Comment by DL6ER** [comment]
Yes, that is what is happening [here](https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L90)

**Comment by RIKWEBB** [comment]
Excellent :)
