### ISSUE TITLE
[Feature Request] Rotate log via logrotate control

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#656]
##### Expected Behaviour:

`/var/log/pihole.log` should be treated as other system logs since it is analogous to `dnsmasq` log. Should be handled by `logrotate` snippet, which would allow rotation based on time, file size or other means instead of a monotonic daily dump. Would also allow for history of logs to be kept if so requested.
##### Actual Behaviour:

Log is handled by cronjob and no log history is kept
##### Steps to reproduce this issue:

Default install
##

**Comment by dschaper** [comment]
https://support.rackspace.com/how-to/understanding-logrotate-utility/

**Comment by dschaper** [comment]
This should probably not be an issue in the sometime near future.

**Comment by DL6ER** [comment]
Implemented in #1130
