### ISSUE TITLE
Tidy up var storage

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#658]
With the introduction of `/etc/pihole/setupVars.conf`, we can probably make better use of it and source it in scripts that need it. i.e gravity

Currently gravity relies on another file to get the IPV4 address, but this is now redundant.
##

**Comment by dschaper** [comment]
Last time I say anything on this, promise. But can we look at LFHS and see about locating the file in a standardized location? We could set up a templated file and pull it over with git, and then sed out the parts as needed.

**Comment by PromoFaux** [comment]
Addressed in next release
