### ISSUE TITLE
Docs: Recommeded Upgrade Process

### ISSUE THREAD

**Issue by gtzilla** [pi-hole/pi-hole#659]
I already 'installed' pi.hole and want to upgrade to the latest (2.9). What's the recommended way of doing this? Is merely re-running the basic install best? Will it preserve my existing white/black list? There is a `automated\ install/basic_install.sh` is that the best route? 
##

**Comment by Mcat12** [comment]
The best way would be to run the install command again. `curl -L https://install.pi-hole.net | bash`
However, with v2.9 this changes a bit! After you update, you should be able to just run `pihole -up` to update to any newer version.

**Comment by Bisaloo** [comment]
You should also update [your FAQ](https://pi-hole.net/help/) now that there is a proper way to upgrade.

**Comment by dschaper** [comment]
Thank you for the comment, we are getting ready to move to a new platform for our website that will allow us to be more responsive and to help make finding answers to questions easier and faster.

**Comment by dschaper** [comment]
Should be on discourse now.
