### ISSUE TITLE
Web interface disabled after 2.9 update (RPI)

### ISSUE THREAD

**Issue by Berrygoodly** [pi-hole/pi-hole#660]
##### Expected Behaviour
Admin web page should appear as usual

##### Actual Behaviour:
Lighttpd fails to start due to running as "lighttpd" user instead of "www-data". Error is solved by manual configuration change but is apparently introduced (and reintroduced) by the Pi hole installer pulling from the RedHat / Centos branch instead of Debian. 

##### Steps to reproduce this issue:
Install PiHole 2.9 on a Raspian Raspberry Pi 3 that is already running 2.8

After upgrade, web admin page will not load as the lighttpd server will fail to run. 

Installing again, or installing as upgrade/new install makes no difference.

**Comment by dschaper** [comment]
Hi, I'm not sure if you've come over from reddit, but just to get a baseline for the troubleshooting, can you link us to a `pihole -d` output. I think this is the issue where the Debian install for some reason is following the RHEL/CentOS install path on the script and using trying to use the config files for that OS platform.

**Comment by Berrygoodly** [comment]
Debug with error: http://termbin.com/k9lm

**Comment by dschaper** [comment]
Okay, can you run the install command and copy the output from the display? (Or run the install again and post a copy of the install log that should be located in `/etc/pihole/`

**Comment by Berrygoodly** [comment]
Install log: http://pastebin.com/bkGiRTmq

**Comment by dschaper** [comment]
Thanks, and the output from the following:

`command -v rpm`
`command -v apt-get`
`command -v dnf`

**Comment by Berrygoodly** [comment]
/usr/bin/rpm
/usr/bin/apt-get
(Nothing)

**Comment by dschaper** [comment]
Okay, somehow you got `rpm` installed on your system. This is the RedHat Package Manager and that's what is causing the confusion for the install script. Can you run `apt-cache policy rpm` and see if it gives the package information for `rpm`. And do you know how that may have been installed on your Pi-hole?

**Comment by dschaper** [comment]
@bcambl Does CentOS/RHEL have an `lsb` descriptor file or an `os-release` that we could try to parse to detect the actual running OS and sanity check the `rpm`/`dnf` detection?

**Comment by Berrygoodly** [comment]
rpm:
  Installed: 4.11.3-1.1
  Candidate: 4.11.3-1.1
  Version table:
 *** 4.11.3-1.1 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status

I honestly have no clue how that got installed. The only thing I installed recently was CUPS and piaware (flight tracking software)

**Comment by Berrygoodly** [comment]
When I try to purge "rpm" with apt-get it also wants to remove dtrx, a file decompression tool I installed a couple of months ago. Maybe that's how it got on my system?

**Comment by dschaper** [comment]
I've run PiAware for a long time, used to handle the Arch packaging for a lot of it, so good to see another users out there! I'm pretty sure it wouldn't have come from that, Mutability has his Debian packaging down rather solid. Not sure on CUPS though, I've never run a print environment off the Pi... 

As for `dtrx`, there does appear to be a package for that in the Jessie repository and it does list `rpm` as one of it's dependencies. Possibly it uses that to attempt to expand/extract rpm sources?

**Comment by Berrygoodly** [comment]
I just purged and autoremoved "dtrx" and re ran the pihole install script. Now it works perfectly! No errors, web admin page is fine. I guess that was it. Previous install script didn't have any problems with the presence of dtrx though.

**Comment by dschaper** [comment]
We've added in support for other OSes besides ones that are typically run in Rapsberry Pi's and this case just happened to trigger the alternate OS support to install. We'll see if we can clean up the detection process, but I'll defer to my more knowledgeable friend on that part! Glad to see it working though!

**Comment by bcambl** [comment]
I was going to do a PR to flip the apt/rpm checks in the OS compatability section. I would bet the majority of users will be on apt based distros. If we flipped the check then we wouldn't need to worry about the 'rpm installed on debian' edge case. I doubt any actual rpm based distros would have apt installed. 
Simple PR if anyone wants to beat me to it!

**Comment by PromoFaux** [comment]
> I doubt any actual rpm based distros would have apt installed. 

Careful what you wish for...

**Comment by dschaper** [comment]
Fixed #663

**Comment by bcambl** [comment]
> Careful what you wish for...

I would **not** wish anyone to use a package manager other than their distribution default.
That is when you should be using `<your favorite container solution>`.

Sometimes sending a PR to the project works as well.. haha

**Comment by dschaper** [comment]
It's big, it's floats on water and it carries cargo... (Or Jenkins.)
