### ISSUE TITLE
Resolve.conf having issues parsing ports when with DNSCrypt

### ISSUE THREAD

**Issue by 99ytrewq911** [pi-hole/pi-hole#661]
Used DNSCrypt guide in wiki

##### Expected Behaviour:
As according to `01-pihole.conf`, Pihole should be using `127.0.0.1:40` as it's resolver. 
`Resolve.conf` lists `nameserver 127.0.0.1#40` as it's resolver.

##### Actual Behaviour:
As according to logs, it instead uses `127.0.0.1:53` for it's resolver which creates a loop(since we are using nslookup, it points the blame at the OS level resolver and resolve.conf)? It resolves domains but it doesn't seem to send them through the DNScrypt proxy.

##### Steps to reproduce this issue:
Follow DNSCrypt guide in wiki,
Reboot, and test via log file.
PiHole and raspbian are fully updated, have rebooted

##### Other notes: 

DNSMasq crashes with odd configurations...
This results in a successful startup:
```
server=127.0.0.1#40
#server=8.8.8.8.8#53
```
This results in a failed startup with an error on the second line
```
server=127.0.0.1#40
server=8.8.8.8.8#53
```

Logs and mirror:
http://termbin.com/j3bz
http://pastebin.com/4KY7ypH8

Not exactly sure if the OS resolver is handling the port number too well.
Do need some confirmation on where the issue could be.

**Comment by dschaper** [comment]
`resolv.conf` with the standard `glibc` and `libresolv` libraries can not use port numbers in the configuration. This has been a longstanding issue, as I believe the BSD's are able to use port numbers. That's why you end up having to use a wrapper script or program to get non-standard ports working with DNSCrypt. It would be very nice to get port number support in that file, but checking the usual mailing lists and bug reports don't look all that promising.

**Comment by ajp2k13** [comment]
Hmm... why does my setup seem to work then? Clients work and they get the DNSCrypt servers if I check with dnsleaktest.com or something.

**Comment by dschaper** [comment]
It's possible that your `dnsmasq` is listening on port 53 and forwarding those queries to the dnscrypt process on 40/41. What does `sudo netstat -tulpn` show as owning 40, 41 and 53?

**Comment by ajp2k13** [comment]
Port 40/41 is owned by DNSCrypt-Proxy and port 53 by DNSMasq.

**Comment by ajp2k13** [comment]
Yes, looks like it.

A nslookup looks like this...

pi@raspberrypi:~ $ nslookup pi-hole.net
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   pi-hole.net
Address: 104.24.108.83
Name:   pi-hole.net
Address: 104.24.109.83

I have set a static IP on my Pi with 127.0.0.1 as DNS (used to bet set to my router)

**Comment by dschaper** [comment]
Okay, you could probably pull out the `resolve.conf` and reset the immutable bit and then make sure all the connections are functioning. If that's all good, then the Wiki can be updated and things should be good. :+1:

**Comment by ajp2k13** [comment]
Thanks for the feedback! I will test it for a bit and then if all is well I'll update the wiki.

**Comment by 99ytrewq911** [comment]
Confirming at upon further testing, DNSleaktest shows my Dnscrypt server rather than secondary DNS.

**Comment by ajp2k13** [comment]
Updated the wiki: removed the bit about resolv.conf and added a couple more troubleshooting tips.

**Comment by dschaper** [comment]
Thanks @ajp2k13 for the update, really glad it works now without needing to `chattr` any files, should make it easier to implement, and hopefully more people will.

Closing.
