### ISSUE TITLE
access to TeamViewer being blocked

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#664]
how can i distinguish what list is blocking login.teamviewer.com. i cant open that website on 1 of my computers i only see white page.

**Comment by dschaper** [comment]
On version 2.9 `pihole -q login.teamview.com` will show you the lists it is on.

**Comment by xxcriticxx** [comment]
`critic@critic:~$ pihole -q login.teamview.com
/etc/pihole/list.0.raw.githubusercontent.com.domains
/etc/pihole/list.1.adblock.gjtech.net.domains
/etc/pihole/list.2.mirror1.malwaredomains.com.domains
/etc/pihole/list.3.sysctl.org.domains
/etc/pihole/list.4.zeustracker.abuse.ch.domains
/etc/pihole/list.5.s3.amazonaws.com.domains
/etc/pihole/list.6.s3.amazonaws.com.domains
/etc/pihole/list.7.hosts-file.net.domains
/etc/pihole/list.8.raw.githubusercontent.com.domains
/etc/pihole/list.9.ransomwaretracker.abuse.ch.domains
`
does this make sense its on 9 different lists?

**Comment by Mcat12** [comment]
That output could use some clarifying. It's listing the lists it looked at, and it didn't find the domain in any of them. You'd see something different with `doubleclick.com`, for example. Also, it seems we've mixed up `login.teamviewer.com` with `login.teamview.com`. I've been guilty of the same mistake. ;)

**Comment by xxcriticxx** [comment]
same result list 0-9 so why do i see white page?

i got login with the software but not with the website

**Comment by PromoFaux** [comment]
If you open up a command box on the machine you're having trouble with and type `ping login.teamviewer.com`, what result do you get?

**Comment by xxcriticxx** [comment]
request timed out. 100% loss

**Comment by PromoFaux** [comment]
`nslookup login.teamviewer.com`

**Comment by xxcriticxx** [comment]
Server: DD-WRT
Address: 192.168.1.1

Non-authoritative answer:
Name: teamviewercolnsole-westeurope.cloudapp.net
Address: 65.52.140.72
Aliases: login.teamviewer.com
tvc-westeurope.trafficmanger.net

**Comment by dschaper** [comment]
I'm timing out on a Windows box to that IP address, looks like it's a TeamViewer issue?

**Comment by jacobsalmela** [comment]
Also unable to ping from my Mac.

**Comment by dschaper** [comment]
Route crashes at the MSN ingress router for them, it's a TV problem.

**Comment by dschaper** [comment]
And just to check what the white page is coming from `curl -v login.teamviewer.com` and check the headers, if it's been Pi-hole'd then you'll see an X-Header from us.

**Comment by xxcriticxx** [comment]
critic@critic:~$ curl -v login.teamviewer.com
* Rebuilt URL to: login.teamviewer.com/
*   Trying 65.52.140.72...
* Connected to login.teamviewer.com (65.52.140.72) port 80 (#0)
> GET / HTTP/1.1
> Host: login.teamviewer.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=utf-8
< Location: https://login.teamviewer.com/
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Date: Tue, 06 Sep 2016 19:18:14 GMT
< Content-Length: 146
< 
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://login.teamviewer.com/">here</a>.</h2>
</body></html>
* Connection #0 to host login.teamviewer.com left intact

**Comment by xxcriticxx** [comment]
if am in usa why am i connecting through Europe?

**Comment by dschaper** [comment]
What upstream DNS server are you using? Are you using a VPN? If you appear to be located in Europe, then you will be routed to the closest node from your exit point. And if your DNS server is in another country that can affect your connection based on the load balancers.

**Comment by xxcriticxx** [comment]
all the stuff went through my isp before i installed pi-hole. remember that i had that DNSKEY auth from different post https://github.com/pi-hole/AdminLTE/issues/130

**Comment by dschaper** [comment]
The Pi-hole doesn't do anything to re-route your traffic, it's just a local repeater/interceptor. If you have the upstream DNS set to your ISP then you would need to find out why they are locating you in Europe. I'll have a better understanding of your configuration after you let me know the DNS upstream and if you are using a VPN or not.

**Comment by xxcriticxx** [comment]
no vpn and how to i check my dns upstream?

**Comment by dschaper** [comment]
It was an option when you ran the setup script. It should be in `/etc/dnsmasq.d/01-pihole.conf`

**Comment by xxcriticxx** [comment]
http://pastebin.com/fX8R5A5C

**Comment by dschaper** [comment]
That shows Google as your DNS upstream (8.8.8.8 and 8.8.4.4). So no clue as to why your ISP is routing you through Europe...

**Comment by dschaper** [comment]
That shows Google as your DNS upstream (8.8.8.8 and 8.8.4.4). So no clue as to why your ISP is routing you through Europe... Just a quick check here on the West Coast of the US and I'm showing `login.teamviewer.com` to be on cloudapp.net in westeurope, so you're seeing what I'm seeing as far as name resolution. I am able to open that site however, and from the `curl` you posted, there is no Pi-hole headers so it's not blocking you.

You can try a `curl -v https://login.teamviewer.com` but the results are likely to show the same.

**Comment by xxcriticxx** [comment]
critic@critic:~$ curl -v https://login.teamviewer.com
* Rebuilt URL to: https://login.teamviewer.com/
*   Trying 65.52.140.72...
* Connected to login.teamviewer.com (65.52.140.72) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_CBC_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.teamviewer.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: OU=GT09290475,OU=See www.rapidssl.com/resources/cps (c)12,OU=Domain Control Validated - RapidSSL(R),CN=*.teamviewer.com
* 	 start date: Mon, 19 Jan 2015 19:50:37 GMT
* 	 expire date: Mon, 26 Dec 2016 23:00:36 GMT
* 	 issuer: C=US,O=GeoTrust Inc.,CN=RapidSSL SHA256 CA - G3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: login.teamviewer.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=utf-8
< Location: /LogOn
< Set-Cookie: lang=en; expires=Tue, 13-Sep-2016 21:44:07 GMT; path=/; secure
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Date: Tue, 06 Sep 2016 21:44:07 GMT
< Content-Length: 123
< 
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/LogOn">here</a>.</h2>
</body></html>
* Connection #0 to host login.teamviewer.com left intact

**Comment by dschaper** [comment]
You should be redirected to https://login.teamviewer.com/LogOn but in any case, this is not related to Pi-hole, as you are correctly connected to teamviewer and attempting to negotiate a secure connection.

**Comment by xxcriticxx** [comment]
yes you right lets close this issue
