### ISSUE TITLE
pi-hole relies on cron for maintenance, does not provide fail-safe

### ISSUE THREAD

**Issue by Taijian** [pi-hole/pi-hole#669]
##### Expected Behaviour:

The install script should check ALL dependencies during install and try to pull in any missing package. Failing that, the user should be notified.

##### Actual Behaviour:

Pi-hole installs on systems without cron without any error messages / pulling in cron.
Therefore the maintenance stubs in /etc/cron.* do nothing.

##### Steps to reproduce this issue:

Run the install script on a pi with a base OSMC installation (or any other distro that foregoes cron in favor of systemd timers).

**Comment by dschaper** [comment]
Solution: Add the systemD timers.

**Comment by Taijian** [comment]
Well, either add systemd timers, or pull in cron as a dependency - that's what I ended up doing, because I couldn't be bothered to go through the cron stubs and translate them to timers...

**Comment by PromoFaux** [comment]
Though, does OSMC use `apt-get` as a package manager?

**Comment by Taijian** [comment]
It most certainly does, good sir!

**Comment by PromoFaux** [comment]
Fixed in [2.9.1] (https://github.com/pi-hole/pi-hole/wiki/Changelog#291---2016-09-12)

**Comment by dschaper** [comment]
I'll keep this self assigned because I think systemD timers is probably the way to go in the long run, especially on Arch...

**Comment by PromoFaux** [comment]
Sure thing!
