### ISSUE TITLE
Blocking https-sites - this needs some attention

### ISSUE THREAD

**Issue by awestvik** [pi-hole/pi-hole#670]
Many ad sites are starting to use https on their ad platform. And I want to block this as well. And so fare I cannot do it like with other domains (or at all) Or am I doing something wrong?

**Comment by brantje** [comment]
For HTTPS it doesn't matter, as the domain name will be the same, and therefore it will still block the domains.

**Comment by awestvik** [comment]
Yeah that does not work here. Then again - adding any domains to the blacklist via the webpage does not work. This is on a fresh install of pi-hole. Great.

**Comment by brantje** [comment]
You can run `pihole -b domain.com` to block a domain via CLI.

When on the blacklist page can you press F12, then go to the console tab.
After that, fill in a domain to block, and submit.
Do you see any errors appear in the console?

**Comment by awestvik** [comment]
Okay I get it now. There is a major lag from when I enter the domain to block and it blocks the domain and when I whitelist the domain/remove the domain. So excuse me while I show my way out. 

(Sorry did not try the F12 as that key does something else on this mac, even with the fn-key.)

**Comment by brantje** [comment]
I think on mac it's `⌘ + Shift + C.`
