### ISSUE TITLE
request: temperature in Chart

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#677]
Hi,
I guess it would be intersting a Chart for the showing CPU Temperature. It has just to be added to the existing "Queries over time" chart.

Like this:
![image](https://cloud.githubusercontent.com/assets/18073299/18435638/bdd1a6a6-78f4-11e6-8df7-286acef259e2.png)

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #138](https://github.com/pi-hole/AdminLTE/issues/138) via [**ZenHub**](https://www.zenhub.com/)
