### ISSUE TITLE
time/date stamps on install / upgrade logs.  /usr/local/bin# ./pihole -up

### ISSUE THREAD

**Issue by hykgoml** [pi-hole/pi-hole#678]
##### Expected Behaviour:
Time date stamps on when and what was updated in the install/upgrade log

##### Actual Behaviour:
Good data but if you upgrade more than once you don't know what changed when.

##### Steps to reproduce this issue:
run pihole -up
```
/usr/local/bin# ./pihole -up

Unpacking objects: 100% (1/1), done.
From https://github.com/pi-hole/pi-hole
   ec6ecf0..6eedfb5  master     -> origin/master
 * [new tag]         V2.9.1     -> V2.9.1
Updating ec6ecf0..6eedfb5
Fast-forward
 adlists.default                    |  1 -
 advanced/Scripts/piholeLogFlush.sh |  2 +-
 advanced/bash-completion/pihole    |  2 +-
 advanced/pihole.cron               |  4 ++--
 automated install/basic-install.sh | 35 ++++++++++++++++++-----------------
 pihole                             | 10 +++++++++-
 6 files changed, 31 insertions(+), 23 deletions(-)
:::
```

Thanks and LOVE the kit.

**Comment by PromoFaux** [comment]
Watch this space... making some tweaks to the update script based on feedback!

**Comment by PromoFaux** [comment]
This should be fixed in https://github.com/pi-hole/pi-hole/pull/679, which will be in the next release
