### ISSUE TITLE
reconfig DNS settings and firewall

### ISSUE THREAD

**Issue by ookangzheng** [pi-hole/pi-hole#684]
Server : CentOS6 
Question:
1. Failed to start lighttpd and php service
2. Does not auto add port 53 udp to iptables
3. How can i reconfig the dns? I tried to change in setupVars.conf. change from google dns to opendns, and i type pihole -g , but it does not change
##

**Comment by PromoFaux** [comment]
1. @bcambl Any ideas on CentOS6? 

2. Is this so that you can have it as a public-facing DNS server? [See this thread for an explanation as to why that is a bad idea!](https://github.com/pi-hole/pi-hole/issues/683#issuecomment-246776571)

3. If you change the values in `setupVars.conf`, you'll need to run `pihole -up` in order to pull the new values into your setup.

**Comment by bcambl** [comment]
Hey, I was able to reproduce some CentOS 6.x issues on a DO Droplet.
CentOS 6.8 is currently at php v5.3.3 and there is some php code here that requires a newer version.

@ookangzheng please try the following:
```
yum install -y http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
yum --enablerepo=remi-php56 install -y php
service lighttpd restart
``` 
Now try to load the admin page.. profit?

As for your `iptables` issue.. do you mind running the following commands:
```
getenforce
service iptables status
```
Let me know how this goes. I may need to submit a PR to address some CentOS 6.x issues.

-cheers

**Comment by ookangzheng** [comment]
1. when i running pihole -up to use my new DNS settings, not working ,still use the old dns.
2. when i tried to run pihole -g , it appear this error http://imgur.com/a/XIPjJ

**Comment by bcambl** [comment]
The line 267 error is addressed by commit 640af30 in PR #668.

**Comment by PromoFaux** [comment]
@ookangzheng Can you run another `pihole -d` and paste up the link here for us? Thanks

**Comment by ookangzheng** [comment]
I already change my server to Centos6, uninstall lighttpd, php
I install myself nginx,php. and dnsmasq does not auto boot up , I manual add it.
The tcp/udp port 53 not auto-insert to iptables when first-time install... I add the rule manually. 

Heres is the log file
http://termbin.com/wxab

**Comment by dschaper** [comment]
Please update to the latest release and check to see if the problem still exists.
Thank you.
