### ISSUE TITLE
Initial install script requires GUI environment

### ISSUE THREAD

**Issue by Dot-Dash** [pi-hole/pi-hole#686]
##### Expected Behaviour:
Installer runs correctly from an SSH session with no GUI, or if this isn't possible, gives a warning to that effect. Since a shell command is publicized as the install method, the need for the graphical environment is _not_ obvious. 

##### Actual Behaviour:
Installer runs, but user isn't given a chance to make any local configurations. No warning(s) are given. Especially noticeable if the local pi-hole interface needs to be something other than the default eth0. 

##### Steps to reproduce this issue:
Install on a headless Pi using only ssh to connect.

**Comment by dschaper** [comment]
The only graphical element involved is Whiptail / Dialog and that runs just fine over an SSH session. Are you not seeing any dialog screens? Do you have your install to run whiptail/dialog in non-interactive mode?

**Comment by diginc** [comment]
related to #681  ?

**Comment by dschaper** [comment]
Not sure, the automated install should not progress unless the user hits the enter key at each of the dialog windows that are displayed. If the install progresses without any user input then I would hazard a guess that non-interactive mode has been enabled and default options are being used. 

It would be good to get a copy of `/etc/pihole/install.log` to take a look at the install, and possibly a `pihole -d` just to see what the baseline install has been configured as.

**Comment by Dot-Dash** [comment]
I did not see any dialogs. I  didn't do any customization  to the pi-hole install. 

#681 happened at a different time, during an upgrade. 

This one was during the first install. I ended up re-running through VNC, with a GUI, and then saw dialog boxes.

**Comment by dschaper** [comment]
When you ran via VNC, did you just open an terminal window and run the install script? What OS?

**Comment by Dot-Dash** [comment]
OS: Linux pi-alarm 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l
(Raspbian) on model B+ 

For VNC, yes, just opened a terminal window and ran the script. 

The original install.log file is long gone, sorry.

**Comment by PromoFaux** [comment]
When you say you ran the script.. are you running the full `curl -L https://install.pi-hole.net | bash`, or are you running `pihole -up` on an existing installation?

The former will give dialogs, even over SSH, so it's confusing to me that it it would not!

The latter has no dialogs by design. This is because the options would already have been selected in the original install and as of 2.9, those settings are saved out to `/etc/pihole/setupVars.conf`.

If you run the former over an existing install, you should get a dialog saying something to the effect of ”existing install detected, would you like to update it reinstall?"

**Comment by PromoFaux** [comment]
bump

**Comment by Dot-Dash** [comment]
I really don't have any log files or additional info. The logs have been overwritten several times now. On the install that prompted this issue report, I did not use `pihole -up`, since that didn't exist yet, and it was my first install.  I know I didn't see any dialogs, since I didn't even know the installer had dialogs until I re-ran it in the GUI.

**Comment by Dot-Dash** [comment]
I'll volunteer to try to reproduce this in the next few days.

**Comment by PromoFaux** [comment]
If there is anyway you can record your screen whilst you try and reproduce the lack of dialogs, that would be an immense help! Thanks.

**Comment by Dot-Dash** [comment]
I could not reproduce this as stated, except for the part about the interface. There does appear to be a bug here. I was never, after several tries, able to get the installer to actually configure wlan0 as the interface. No matter what I selected in the GUI, the interface always became eth0. 

I ran the install script from scratch several times. (Scratch meaning, at least removing the /etc/pihole and /opt/pihole directories first). 

In the dialog, I would see the option to select an interface. eth0 and wlan0 were offered, with the selection being defaulted to eth0.  I would press tab to move the cursor, and then return. The setupVar.conf file always ended up with the interface as eth0. If I go in and manually edit that to wlan0, then reboot, it works fine.

**Comment by dschaper** [comment]
When you tab to move the cursor to WLAN0 are you pressing the SPACE key to make sure WLAN0's button is lit up before you move to the next screen?

**Comment by Dot-Dash** [comment]
No. I just realized that, and updated my comment. D'oh!

**Comment by dschaper** [comment]
Try running through an install and check to see if the WLAN0 is starred when you go through that section, if you still get ETH0 then we need to really scour through a few things. I'm still not exactly sure how the whiptail failed to display at all the first go around with the install, that's an issue.

**Comment by Dot-Dash** [comment]
The user is kind of conditioned to press return through all those `<OK>` dialogs, and the Interface dialog lacks the `(press space to select)` instruction that some of the others have.

**Comment by Dot-Dash** [comment]
If wlan0 is well and truly selected with space key, then the interface is set up accordingly.
