### ISSUE TITLE
I am using Nginx for a website and PiHole appears to be taking over a bit.

### ISSUE THREAD

**Issue by camdenorrb** [pi-hole/pi-hole#687]
Tends to install Apache by force and website isn't optional.

**Comment by bukka1** [comment]
How? What are the issues that you are experiencing as I am using Nginx as my web server with pi-hole and the interaction is seamless.

**Comment by camdenorrb** [comment]
Port 80 is already taken.

**Comment by Sh4kE** [comment]
Why did you close this? Is this problem resolved? I'm facing the same issue. Is there a tutorial how to switch from lighthttpd to nginx/apache?

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration
