### ISSUE TITLE
How important is the physical location?

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#690]
##### Expected Behaviour:
Fast loading of web pages and fast DNS lookup

##### Actual Behaviour:
Long loading time for web pages

My Pi with that hole is actually behind an second router upstairs. Would it be better to connect it direct to the main router (in the cellar)?
How can I figure out the time to DNS lookup? Maybe a DNS benchmark or trace?

My family is flaming...

**Comment by diginc** [comment]
does your `ipconfig /all` (windows) show pihole as your primary DNS server?

Could you post the debug command output by running `pihole -d` ?

**Comment by TylonHH** [comment]
Yeah the DNS is set to the PiHole
Here is [the Log](http://termbin.com/msd8)
I tried to open https://bitly.com/ and http://www.fritz.de/ from 192.168.178.66

But as I see in the Log there is something wrong? Do you suggest a wipe / install?

**Comment by diginc** [comment]
The log doesn't look abnormal for bitly.com or fritz.de lookups, they occur in under a second.  That would indicate something outside the pihole is causing the slow down.

try this: `tail -f /var/log/pihole.log`
then hit some websites again and see if there is a delay before they show up in your log.  That would indicate the request isn't hitting the pi immediately and your computer / network is not immediately sending the request to the pi.  

> Yeah the DNS is set to the PiHole

Is it set as the first DNS server though?  a timeout on a non-functioning DNS as the primary and failing over to the 2nd/3rd dns server could introduce delay like you are seeing.

**Comment by PromoFaux** [comment]
Just looking at your debug log, and I'm not sure if it's related.. but..

The `lighttpd` error log is showing a LOT of PHP issues... I'm wondering if something is messed up with the log? Is there an easy way to check the health of your SD card?

**Comment by TylonHH** [comment]
Please no. I recently got two defect SD card (intenso trash). I can check the SD card but I'll buy some new cards also.

That's what I wonder about the log too. I recommend to set it up new.

**Comment by Mcat12** [comment]
I don't think those php errors necessarily indicate sd failure, although there are a lot of them. It could be just that the web interface is being opened a lot, and every time an error or two is generated (could be a few reasons).

**Comment by diginc** [comment]
lighttpd seems beside the issue since response time of page / dns loads sound like the issue.  The php errors are concerning yes, but not critical / fatal if he has no complaints about the web interface.

try this, it'll be simpler than my previous suggestion, it'll tell you how long your pihole takes to lookup compared to google's DNS.  My previous suggestion for debugging lookup times still stands too.

```
time nslookup doubleclick.com
time nslookup doubleclick.com 8.8.8.8
```

**Comment by TylonHH** [comment]
Here is what I got from my Linux Laptop
```
HP-625-Linux ~ # time nslookup doubleclick.com
Server:		127.0.1.1
Address:	127.0.1.1#53

Name:	doubleclick.com
Address: 192.168.178.22

real	0m0.060s
user	0m0.052s
sys	0m0.008s
HP-625-Linux ~ # time nslookup doubleclick.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	doubleclick.com
Address: 216.58.210.14

real	0m0.100s
user	0m0.060s
sys	0m0.004s
```

And here from an other Pi (Kodi)
```
OpenELEC:~ # time nslookup doubleclick.com
Server:    192.168.178.22
Address 1: 192.168.178.22 raspberrypi

Name:      doubleclick.com
Address 1: 192.168.178.22 raspberrypi
real	0m 0.02s
user	0m 0.00s
sys	0m 0.00s
OpenELEC:~ # time nslookup doubleclick.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      doubleclick.com
Address 1: 216.58.210.14 fra16s07-in-f14.1e100.net
real	0m 0.14s
user	0m 0.00s
sys	0m 0.00s
```
So nothing to worry about.
But as I told installed PiHole complete new. Its getting better.

**Comment by TylonHH** [comment]
I disabled IPv6 on my router. That boosted my loading time on my smartphone extremely.

Can I still leave IPv6 enabled on the PiHole?

**Comment by Mcat12** [comment]
It won't hurt anything.

**Comment by PromoFaux** [comment]
I always select IPv6 out of habit when installing, and I've never had IPv6 as an option on my router!
