### ISSUE TITLE
No status and temperature in Firefox

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#697]
##### Expected Behaviour:
Showing status and temperature of Pi

##### Actual Behaviour:
Doesn't show in Firefox latest version (even with adblocker plugins disabled)

##### Steps to reproduce this issue:

Visit Pihole IP/admin and see in left corner on top

Screenshot from mobile (Chrome): http://i.imgur.com/xzWUeVz.png

Screenshot from desktop (Firefox latest):  http://i.imgur.com/f6D8qRr.png

**Comment by TylonHH** [comment]
Already mentioned in https://github.com/pi-hole/pi-hole/issues/693

**Comment by nomoreads** [comment]
Oops... sorry :\

**Comment by TylonHH** [comment]
No problem.
So please close this issue here and go on the other thread.
