### ISSUE TITLE
Web interface b0rked after upgrade to most recent version. 

### ISSUE THREAD

**Issue by escapologyBB** [pi-hole/pi-hole#698]
Hi,

This has been working beautifully for me for a while now, so I thought upgrading wouldn't cause any problems however it really has.  I ran through the update process and where before I could see the admin interface when I visited 192.168.0.55/admin, now I can only see the following:

https://gist.github.com/escapologyBB/3c16d9140105217d6599465c6445de38

I tried running the following two commands as suggested in one of the comments but to no avail:

`sudo lighttpd-enable-mod fastcgi-php` 
`sudo service lighttpd force-reload`

Here is the output from Termbin (thanks fall giving me the option to choose whether to upload my logs or not by the way!):  http://termbin.com/dgmh

I'm running Pi-Hole on the Raspberry Pi 2B.

TIA

Edited To Add: Just discovered that it still working as a DNS server, I just can't access the web interface.

**Comment by escapologyBB** [comment]
I have rolled back to version 2.9.8 and everything is working again.  Just FYI.

**Comment by PromoFaux** [comment]
Strange... so you're saying it's just displaying the web page as pure HTML, rather than the rendered page?

**Comment by escapologyBB** [comment]
That's exactly what I'm saying, somebody over at Reddit said that it might be because something was already using port 80.  I'm going to run a check and make sure nothing else is using port 80 and get back to you, although it's a clean install  of the OS so there shouldn't have been a web server installed.

**Comment by PromoFaux** [comment]
Curious! 

There was nothing changed in the latest update that would have touched the web interface...

**Comment by escapologyBB** [comment]
nope, just updated to the most recent version and all it's doing is showing me the raw HTML of the page.  There is no other service running on port 80 according to netstat:

```
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      803/tor
tcp        0      0 192.168.0.55:50046      158.58.170.27:443       ESTABLISHED 803/tor
tcp6       0      0 :::80                   :::*                    LISTEN      821/apache2
tcp6       0      0 192.168.0.55:80         192.168.0.5:64422       TIME_WAIT   -
tcp6       0      0 192.168.0.55:80         192.168.0.6:51098       TIME_WAIT   -
udp6       0      0 fe80::ba27:ebff:fe1:123 :::*                                707/ntpd
unix  2      [ ACC ]     STREAM     LISTENING     9737     803/tor             /var/run/tor/control
unix  3      [ ]         STREAM     CONNECTED     9733     803/tor
unix  3      [ ]         STREAM     CONNECTED     8063     533/cron
unix  3      [ ]         DGRAM                    12380    1/systemd
unix  3      [ ]         STREAM     CONNECTED     9732     803/tor
```

**Comment by PromoFaux** [comment]
Does it show the same in all browsers? What about private browsing mode? I'm wondering if there is an extension that is interfering...

Also, could you run a `pihole -d` and paste the results, please?

**Comment by PromoFaux** [comment]
Oh wait... I notice that you have `apache2` listening on port 80....not `lighttpd`

**Comment by escapologyBB** [comment]
Problem solved, for some reason apache2 was installed, I have no idea how that happened but everything is okay now.  Thanks guys!

**Comment by PromoFaux** [comment]
👍 Do you have any other packages installed that have a web interface? You may find something stops working....

**Comment by escapologyBB** [comment]
As far as I'm aware there should be nothing else running except Pi-Hole and Tor, other than that there should be nothing else running.  I'm sure somebody will start shouting if they try to access something and can't!  :-)

**Comment by PromoFaux** [comment]
>I'm sure somebody will start shouting 

That's usually my solution. If you don't know why something is in place, remove it and see if anyone complains :D

**Comment by escapologyBB** [comment]
Definitely, not noticed any fires just yet so I'm going to assume everything is fine.  :-)

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/18617408/87cfa842-7dc6-11e6-8a1a-cd44733aa252.png)

**Comment by escapologyBB** [comment]
*ded*
