### ISSUE TITLE
MINOR : Question about chmod and sudo

### ISSUE THREAD

**Issue by Fedora-Core** [pi-hole/pi-hole#699]
MINOR : Question about chmod and sudo

Branch = master

Latest commit = 6eedfb5

Directory = pi-hole/automated install/

script = basic-install.sh

Observation:

1) some linux distros do NOT install the sudo package.

2) example: Debian Jessie 8.5 for PC, Netinstall, minimal, no X.

3) the script basic-install.sh checks this - starting at line 44. Very Good.

4) the script basic-install.sh informs the non-root user at line 54. Very Good.

"sudo is needed for the Web interface to run pihole commands.  Please run this script as root and it will be automatically installed."

5) the non-root user must log-off, and log-in with the root account, and rerun the installation. Very Good.

6) now all works - sudo is installed - and the whole installation process completes. Very Good.

So it seems...

Question:
- if the basic-install.sh is executed by the user root,
- then what is the effect of the chown at line 576 ?

" ${SUDO} chown "$USER":root /opt/pihole "
- the environment variable $USER in that case is "root"
- if the package sudo should exist,
- and if the installation was performed by a non-root user,
- then the enviroment variable $USER would be something else.
  ( For Raspbian Jessie it would be "pi" )
- So, what was the developer's aim when writing this chown that way ?
- Will this - non-hypothetical - case ruin the Pi-hole appliance ?

Greetings, Fedora Core
##

**Comment by Fedora-Core** [comment]
Great ! issue number 100 ;-)

**Comment by PromoFaux** [comment]
Hi FC, long time no speak!

>Will this - non-hypothetical - case ruin the Pi-hole appliance ?

Very good question... and in fact, you may already have the answer, unless you've ran through the code in your head instead of installing :) Have you noticed any issues?

I wonder if it is perhaps best that instead of suggesting the user runs as root, that we suggest they install sudo, and then re-run.

**Comment by dschaper** [comment]
The developers aim in adding the $USER environment call to the script is to eventually drop as many privs as possible and move to an install with less than `root` requirements. The idea was to use the `pihole` user and only elevate when needed. We kind of had to go with a full `sudo` approach for now as we are writing to paths that are protected, but with the LFH guidelines you posted (and I did read them, I was attempting to package this beast at some point) we may be able to do a dropped priv approach.

The script now runs as root, so the $USER is always going to be root, as the script now refires if not run by user 0.

**Comment by Fedora-Core** [comment]
Thank you.
