### ISSUE TITLE
Queries counter on main page and quiere log aren't equal

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#700]
On the web interface there are nearly 2k queries (flushed 20 minutes ago).
In the quiere log I see on l at the bottom only a total number of 150.
Shouldn't the numbers be equal? Are your numbers at those places equal?

~~If yes, I would suggest it's because of an different timezones I set, which is not set everywhere?!?!~~

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #143](https://github.com/pi-hole/AdminLTE/issues/143) via [**ZenHub**](https://www.zenhub.com/)
