### ISSUE TITLE
How to disable temporally disable PiHole on a client

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#707]
Hi,
How can I temporally disable the PiHole DNS one one specific client? Now the DNS server is set into the router.
I thought I could set a "different" DNS server on the client (to the default one)...
Is there a possibility to exclude a specific client IP on the PiHole? Or other solution?

**Comment by PromoFaux** [comment]
On one specific client, you'd need to manually change the DNS settings on that client to point somewhere else, i.e google.

To temporarily disable Pi-hole completely you'd need to comment out the line `addn-hosts` in `/etc/dnsmasq.d/01-pihole.conf` and then reload `dnsmasq`

We did start [on a script for pausing pi-hole](https://github.com/pi-hole/pi-hole/blob/d40b841b2ab4fec58f2417eeddc7793290cc0365/advanced/Scripts/pauseResume.sh), which should give you and idea

**Comment by TylonHH** [comment]
your pause/resume idea 💡 is pretty cool.
It would be nice if i can pause it on the web interface.

**Comment by dschaper** [comment]
Just keep in mind, if you pause for a client and they have the pi-hole'd IP address, then they need to either flush their DNS cache, or wait for the 300 second record TTL to time out and for the new address to be resolved.

**Comment by TylonHH** [comment]
@jacobsalmela @PromoFaux 
Where do I have to put [this script](https://github.com/pi-hole/pi-hole/blob/d40b841b2ab4fec58f2417eeddc7793290cc0365/advanced/Scripts/pauseResume.sh)?
Am I right that I start it with `sudo sh pauseResume.sh`?

**Comment by PromoFaux** [comment]
You should be able to run it from anywhere. Once we get around to integrating it properly it will be on the `pihole` command. Untill then, that's right, `sudo sh pauseResume.sh`

**Comment by TylonHH** [comment]
````
root@raspberrypi:/home/pi# sudo sh /share/pauseResume.sh
/share/pauseResume.sh: 14: /share/pauseResume.sh: [[: not found
::: sudo will be used.
/share/pauseResume.sh: 20: /share/pauseResume.sh: [[: not found
::: Please install sudo or run this script as root.
````

**Comment by PromoFaux** [comment]
Hmmm. Try `sudo ./share/pauseResume.sh`

Or `sudo bash /suare/pauseResume.sh`

**Comment by TylonHH** [comment]
Last one works `sudo bash /share/pauseResume.sh`
