### ISSUE TITLE
Undefined offset: -2 in /var/www/html/admin/data.php

### ISSUE THREAD

**Issue by ipv89** [pi-hole/pi-hole#709]
When viewing the apache error log it contains the following errors. 

Undefined offset: -2 in /var/www/html/admin/data.php on line 268
Undefined offset: -3 in /var/www/html/admin/data.php on line 269

Not sure if it is related but my graphs on the admin page are no longer loading but the stats are available through /api.php

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #145](https://github.com/pi-hole/AdminLTE/issues/145) via [**ZenHub**](https://www.zenhub.com/)
