### ISSUE TITLE
can anyone help me out on blocking add sites on CNN

### ISSUE THREAD

**Issue by Fins2rit** [pi-hole/pi-hole#710]
I pop onto CNN.com in the morning just to catch up on some news. I am always getting trivago hotel sites adds before every video article I play. Now I understand nothing is free but every time you click a video is a bit crazy.

So i tried to inspect the add and i think i got this website for the add "http://z.cdn.turner.com".
I added it to blacklist in pihole "z.cdn.turner.com"and still the video still plays through.

i restarted the browser and re-ran pihole -g and still the video plays.

am i doing something wrong can anyone help me.

Thanks in advance and thank you Jacob for Pihole.

**Comment by PromoFaux** [comment]
Hi @Fins2rit , you might have better luck with this kind of question on [our subreddit](https://reddit.com/r/pihole), the community there are very helpful!
