### ISSUE TITLE
Help, Error install pi-hole

### ISSUE THREAD

**Issue by mcdohl007** [pi-hole/pi-hole#712]
First scenario i'm install curl 
`apt-get install curl`
and when i run 
`curl -L https://install.pi-hole.net | bash`

i got error message:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                    Dload  Upload   Total   Spent    Left  Speed
100  5719    0  5719    0     0  11419      0 --:--:-- --:--
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
:-- --:--:-- 11415
(23) Failed writing body
```

--------------------------------------------------------------------------------------------------------------
second scenario i'm install curl 
`apt-get install curl`
and run command 
`curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh | bash`

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0:::
::: You are root.
100 34785  100 34785    0     0  77461      0 --:--:-- --:--:-- --:--:-- 77472
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking installer dependencies...
:::    Checking for apt-utils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for dhcpcd5... Not found! Installing.... done!
::: Using interface: eth0
::: Warning: Unable to locate configuration file to set static IPv4 address!
```

FYI: i'm using debian 8 jessie amd64 with gui (download from debian website)

-----------------------------------------------------------------------------------------------------------------
yesterday i already test install on my raspberry without any error

FYI: RASPBIAN JESSIE from raspberry website

**Comment by PromoFaux** [comment]
Hi there, 

Looks like the code is falling over at [this function](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L332), which suggests that the file `/etc/dhcpcd.conf` does not exist. 

That said, `dchpcd5` wasn't installed until you ran the install script, so I wonder if it just hadn't created the file yet. Try restarting the box and running the install script again.

**Comment by mcdohl007** [comment]
i got the problem,
default sourcelist unable to get dhcpcd5
so, i change sourcelist.

thank you @PromoFaux  for 

> /etc/dhcpcd.conf

Problem solve
