### ISSUE TITLE
9/10 times I visit the admin page - the pi3 reboots

### ISSUE THREAD

**Issue by awestvik** [pi-hole/pi-hole#714]
Hi

So almost everytime I visit the admin page to for example blacklist a site, the raspberry pi 3 reboots. That is really all I have to say. I'm running the latest software with a 64Gb fast sd card. And there is nothing else running other than pihole.

**Comment by PromoFaux** [comment]
It's most likely that the power supply you're using doesn't have enough oomph...

Had a user on [reddit with a similar issue](https://www.reddit.com/r/pihole/comments/51e4e7/each_time_i_go_to_my_httpipadmin_page_on_rasbian/)

**Comment by awestvik** [comment]
So maybe adding a powerbank with a nice amp output would act as a UPS and then I can see if that's the case. I have tried several chargers and stuff.

**Comment by PromoFaux** [comment]
Take a look at [the power requirements page](https://www.raspberrypi.org/help/faqs/#power) of the Rpi FAQs. Pi 3 is recommended at 2.5 amps! Your average phone charger probably won't meet those requirements.

**Comment by awestvik** [comment]
Thank you!
