### ISSUE TITLE
How to prevent DNS misuse (open recursive DNS server)

### ISSUE THREAD

**Issue by vincentcox** [pi-hole/pi-hole#715]
The pi hole is based on dnsmasq, and it is open to recursive DNS requests. So it can be used in a DNS amplification attack. How do we prevent this?

**Comment by PromoFaux** [comment]
Only if you have forwarded port 53 on your router to your pi-hole. Simplest way to prevent it is to make sure it's only in use on your home network!

[We recently made a blog post about this](https://pi-hole.net/tips-for-accessing-your-pi-hole-remotely/)

**Comment by PromoFaux** [comment]
Feel free to continue discussing in this thread, But I've closed it as it's not really an issue with the software.

**Comment by vincentcox** [comment]
Thank you for explaining. The blogpost says it all. I am using pi-hole for the wrong purposes I guess. However, it's a great project! Thanks!
