### ISSUE TITLE
Tabs that are opened in background are randomly closing upon loading completes

### ISSUE THREAD

**Issue by matrixagent** [pi-hole/pi-hole#716]
I suppose this is the new popup-closing feature having unintended consequences. When I open an URL in the background (for example from Tweetbot), i.e. having the app that opens the URL configured not to give focus to the browser, that tab will close as soon as it has finished loading. It only happens to some URLs, I suppose it is all URLs that contain anything Pi-Hole blocks.

##### Expected Behaviour:

Tabs opened in background not closing.

##### Actual Behaviour:

Tabs are closing.

##### Steps to reproduce this issue:

Configure Tweetbot like this:
![image](https://cloud.githubusercontent.com/assets/309726/18786185/dc4a5974-819c-11e6-92b0-a50bfe419c52.png)

Open e.g. https://www.dropbox.com/release_notes from a tweet inside Tweetbot.

**Comment by PromoFaux** [comment]
Hi, thanks for the report, I'll try and play with this later on!

**Comment by PromoFaux** [comment]
In the meantime.. could you try clearing out the content of `/var/www/html/pihole/index.html` and seeing if you still get this issue?

**Comment by matrixagent** [comment]
I tried, but the issue persists. Any services I should restart after emptying the file?

**Comment by PromoFaux** [comment]
Might want to clear the browser cache on your client machine (You can see what is coming back by navigating to a blocked domain i.e `doubleclick.net` and then right click, view source to check)

**Comment by matrixagent** [comment]
After some more investigating it looks like a different extension (https://mypermissions.com) was causing that behaviour. Sorry for not looking deeply enough into it before troubling you, the timing coincidence was just too convenient as an explanation.

**Comment by PromoFaux** [comment]
:) No worries at all! We like to know if anything we're doing is causing issues, so that we can try and fix it! But glad it wasn't us 😄
