### ISSUE TITLE
Chronometer printing the words "is" and "to" [$5]

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#717]
##### Expected Behaviour:

Chronometer should print the name of the server that was blocked
##### Actual Behaviour:

Chronometer prints the words "to" and "is"
##### Steps to reproduce this issue:

In Chronometer.sh, I had to change the number 7's to be 6's. Now, instead of seeing the word "is" all the time, I see the actual domain.
**However, some times, the word "to" is displayed instead of the domain.**

Original line:
# tail -f /var/log/pihole.log | awk '/\/etc\/pihole\/gravity.list/ {if ($7 != "address" && $7 != "name" && $7 != "/etc/pihole/gravity.list") print $7; else;}'

My line:

tail -f /var/log/pihole.log | awk '/\/etc\/pihole\/gravity.list/ {if ($6 != "address" && $6 != "name" && $6 != "/etc/pihole/gravity.list") print $6; else;}'
##

**Comment by PromoFaux** [comment]
Hi there,

That line is commented out by default because it doesn't really work very well! (As you've discovered) It probably should have been removed when we last updated `chronometer.sh`. That said, I'll take a look at it later on and see if I can come up with the solution, unless you already have one??

**Comment by p1r473** [comment]
Other than changing the 7s to 6s, I don't know how to get it to not display
the occasional word "to". At least it doesn't keep spamming the word "is"
anymore

I am using this line due to hooking up the pihole to the LCD display and
wanting to see what it's blocking

**Comment by PromoFaux** [comment]
Sure thing! I will take a look at it later if I get time, hopefully you can put up with the occasional "to" for a bit! :)

**Comment by p1r473** [comment]
Thanks!

**Comment by p1r473** [comment]
Hi @promofaux just hoping you'll get to this issue eventually!

**Comment by PromoFaux** [comment]
Hi @p1r473 sorry, things have been hectic and this got pushed to the back of the pile! @DL6ER has said in another channel that he will take a look, I think he has a solution...

**Comment by DL6ER** [comment]
Once `FTL` is in we will have a reliable solution. But it should come soon (:tm:) !

**Comment by andylh** [comment]
I changed the line to just : 
tail --lines=1  /var/log/pihole.log | awk '{print$6}'

At least it prints the latest line and the daily stats.

**Comment by p1r473** [comment]
Hi, it looks like in the latest release, chronometer doesn't print out this list like this anymore. It only prints out the most recent blocked domain.

I put the old code back in, but it still has the issue where it printed the is and to instead of the blocked domain. Can anyone whip up a way to get the old list style of chronometer working but not replacing those words incorrectly?

**Comment by Mcat12** [comment]
This code is obsolete now with FTL, so what you are looking for is probably better achieved with `pihole -t` or a feature request on Discourse.
