### ISSUE TITLE
When a period is in a comment in a source, the comment is used as the URL, instead of intended URL [$5]

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#718]
##### Expected Behaviour:
Comments in a source should be ignored

##### Actual Behaviour:
Periods in the comments are treated like URLs to be blocked, and actual URl is not blocked

##### Steps to reproduce this issue:
Try putting these lines in your source:

**rcsmetrics.it #Corriere.it
esm1.net #Dealer.com**

It seems when the comment looks like a URL, PiHole is taking the comment as the domain, rather than the domain itself!

Because this is what I see in my actual gravity.list:
**192.168.1.186 #Corriere.it
192.168.1.186 #Dealer.com**

It is blocking the comment instead of the intended URL. **And it keeps the # in there too.**

**Comment by stonedbovines** [comment]
http://termbin.com/yn01 contains code (sed) for an external script I built to work on the contents of gravity.list for my own system, essentially against the default lists. The only addition to the default set is a link that is currently already included within one of the defaults, just to ensure that it always gets used, even if it gets removed from that default set. It returns a sorted and deduplicated list of the domains. It needs the pi-hole IP address added to each line, which I've left off as it will almost certainly be different to mine.

It is possible that some of the lines duplicate work done previously in the script but it was knocked up against increasingly larger subsets of the original `list.*` files to remove new 'errors' after adding in additional files. As it only takes ~9s to run on a raspi3, I didn't bother trying to micro-optimise it any further.

It may _appear_ to be more aggressive with how many it returns but there is a LOT of cruft in the original files that currently leaves several 'visually indistinguishable' duplicates in the gravity file.

If someone wants to use the code to earn the bounty, feel free.

**Comment by PromoFaux** [comment]
Done! It was actually a super simple fix. I'm not too worried about the bounty @p1r473, donate $5 to charity instead, if you like!

**Comment by p1r473** [comment]
I think the bounty needs to be claimed as I've already paid it
Enjoy!
