### ISSUE TITLE
Question on blacklist

### ISSUE THREAD

**Issue by joeyanez97** [pi-hole/pi-hole#719]
Is there a way to blacklist every URL with the subdomain googlevideo.com?

I started blacklisting some google ad URLs like r6---sn-q4fl6ne6.googlevideo.com and r8---sn-q4f7snsz.googlevideo.com but there are way to many to block.

I have tried to blacklist *.googlevideo.com and .googlevideo.com but they error out with "Failure! Something went wrong."

**Comment by TylonHH** [comment]
Yes it's possible, see https://github.com/pi-hole/pi-hole/issues/672

**Comment by PromoFaux** [comment]
Added to FAQ s
