### ISSUE TITLE
Update seems to have gone fine - no more web UI

### ISSUE THREAD

**Issue by 40da63260** [pi-hole/pi-hole#720]
##### Expected Behaviour:

pihole -up 
in a dedicated container on a pine64 - debian 64

##### Actual Behaviour:

update seemed to work - but on reboot of container the web UI failed to show up.

http://termbin.com/gx6d

**Comment by brantje** [comment]
Looks like php-fpm is having struggles:
```
unexpected end-of-file (perhaps the fastcgi process died): 18 Permission denied 
2016-08-12 04:50:03: (mod_fastcgi.c.3353) response not received, request sent: 824 on socket: unix:/var/run/lighttpd/php.socket-0 for /admin/api.php?getForwardDestinations, closing connection
```

Does this also happen if you re-create the container?

**Comment by dschaper** [comment]
@40da63260 Ping for update
