### ISSUE TITLE
admin console

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#723]
any way to turn off admin console completely off?

**Comment by PromoFaux** [comment]
`sudo rm -rf /var/www/html/admin` should do it.

**Comment by PromoFaux** [comment]
Though it will come back on an update as it's part of the install script!

**Comment by xxcriticxx** [comment]
if i turn off admin console any other way to know whats domain was pi-hole?

**Comment by PromoFaux** [comment]
You would need to parse `/var/log/pihole.log`

running `cat /var/log/pihole.log | grep gravity` will show you all domains that have been blocked, but you'd need to expand on it a bit to get the client that sent the request etc.

Is there any particular reason you want to disable the admin page?

**Comment by xxcriticxx** [comment]
is there any debug mode that will show you whats blocked? that you can turn on and turn off 

my keeps crashing every 2 hours

**Comment by PromoFaux** [comment]
Ah yes, I remember now, you were having issues with the PHP load times (https://github.com/pi-hole/AdminLTE/issues/130)

I'm going to close this issue as you already have an issue open for this.
