### ISSUE TITLE
Pihole -up wipes custom configuration by replacing /etc/dnsmasq.d/01-pihole.conf

### ISSUE THREAD

**Issue by jannylund** [pi-hole/pi-hole#724]
I have a setup where I have pihole's ip served as my primary DNS, with firewall's ip as secondary. Pihole is using firewall for lookups, to allow using internal DNS names as set in the firewall.
##### Expected Behaviour:

Custom configuration in `/etc/dnsmasq.d/01-pihole.conf` would be stored or a warning seen that file has been modified.
##### Actual Behaviour:

Pihole simply replaces the file.
##### Steps to reproduce this issue:
1. Set custom server in `/etc/dnsmasq.d/01-pihole.conf`. For example. `server 10.0.1.1`. 
2. Run `pihole -up`
3. Verify that `/etc/dnsmasq.d/01-pihole.conf` now uses configuration as `server 8.8.8.8` + `server 8.8.4.4`.
##

**Comment by stonedbovines** [comment]
Put your custom setup in a separate file, eg `/etc/dnsmasq.d/02-custom.conf` and it will overwrite the corresponding entries from `01-pihole.conf`

**Comment by jannylund** [comment]
As dnsmasqd supports multiple configurations of server, your suggestion actually works as if I added all three servers. I guess I can live with it as failover, but I would prefer a solution using only my firewall as next-hop.

**Comment by dschaper** [comment]
Does this happen when you choose a custom upstream server in the automated installation routine? Or are you manually editing the 01-pihole.conf file after installation?

**Comment by jannylund** [comment]
This was after a manual modification to `01-pihole.conf`. I can try testing the custom installation.

**Comment by dschaper** [comment]
If you could please, just to be sure as that file isn't intended to be edited manually, but it probably will be edited in general use.

**Comment by jannylund** [comment]
I found the `/etc/pihole/setupVars.conf`, modified it to contain `piholeDNS1=10.0.1.1` and re-ran the command `pihole -up`. This works correctly, so I guess this is a *false positive* and can be closed (or maybe changed to a feature request).

**Comment by dschaper** [comment]
Okay, I'll leave this open for now so the other members can comment on it if they'd like. Will leave as FR for now.

**Comment by PromoFaux** [comment]
This was the exact reason we implemented setupVars.conf :)

**Comment by PromoFaux** [comment]
Just as a note, @jannylund, you could also have run the install script again. This would have given you the option to change the values used. The upgrade script is the same as the install script, it just skips all the dialogs and then uses whatever values you used in the last install (which as you've learned are stored in `setupVars.conf`)

Closing the issue for now unless anyone thinks it needs to stay open.

**Comment by jannylund** [comment]
@PromoFaux yeah, I understand that. This is most likely *never* an issue for anyone running a standalone pi-hole and without any experience of dnsmasqd, so I'm guess I'm a minority.

However. Since it would be fairly simple to take a hash of `01-pihole.conf`, store it in `setupVars.conf` and confirm there is no differences and throw a warning when updater is run or make a copy of the configuration file before overwriting it.

**Comment by PromoFaux** [comment]
Had not thought about checking for changes with a hash, to be honest! 

But really, the whole reason we moved away from using `/etc/dnsmasq.conf` to using `/etc/dnsmasq.d/01-pihole.conf` was so that we wouldn't _have_ to worry about overwriting changes, as any user changes should be made in either the former file, or an additional conf in the `dnsmasq.d` directory.

I've not tried this...  if you were to set `piholeDNS1` and `piholeDNS2`  in `setupVars.conf` to be blank, then `01-pihole.conf` will not contain any lines for `SERVER=`. you can then create something like `/etc/dnsmasq.d/02-custom.conf` and add your own `SERVER=` lines to there. Though kind of beside the point now, since you've changed them in `setupVars.conf` :)

We can look into storing conf file hashes, though, and at least make a backup on update.

**Comment by jannylund** [comment]
Here's a simple way of doing validation and hashing.
```
root@pi-hole:~# md5sum /etc/dnsmasq.d/01-pihole.conf > /etc/pihole/hash
root@pi-hole:~# md5sum -c /etc/pihole/hash
/etc/dnsmasq.d/01-pihole.conf: OK
root@pi-hole:~# echo "# test" >> /etc/dnsmasq.d/01-pihole.conf
root@pi-hole:~# md5sum -c /etc/pihole/hash
/etc/dnsmasq.d/01-pihole.conf: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
root@pi-hole:~#
```

**Comment by diginc** [comment]
Most configuration management solutions suggest adding a banner saying "DO NOT MODIFY - MANGED BY XYZ, CHANGES WILL BE LOST" at the top & bottom as a warning to users.  Just a thought.

Not that people can't modify it (I do in my docker) but they need to know they have to re-apply/verify changes after every update.  I automate this in my update script so when I pull in changes, any modifications are re-ran through `sed` or other tools.

**Comment by diginc** [comment]
> Here's a simple way of doing validation and hashing.

They wouldn't support updating that file in the future for anyone that customizes.  There is already a dnsmasq.d folder for customizations which is a best practice to use.  Important modifications that need to be made to a managed file are best done through environment variables like they're doing with setupVars.txt.  I don't think adding complexity is needed when what you want is already supported with variables or a second file.

**Comment by jannylund** [comment]
@diginc I kind of agree. Adding the warning would be good to share the information that the file will be wiped. The hash could also be useful to trigger a warning during upgrade, and for simplicity it could just rename the custom config to `01-pihole.conf.backup` or similar, to avoid wiping the custom configuration but also not support it.

**Comment by dschaper** [comment]
Warnings have been added to volatile configurations files.
