### ISSUE TITLE
[Feature Request] Download or copy able list of not piholed Domains [$5]

### ISSUE THREAD

**Issue by gforke97** [pi-hole/pi-hole#732]
I would like to have a file where i have just the Domain Names of the Domains that werent piholed to make it easier to add them to the blacklist (im missing alot, I already have nearly 100k Domains blocked but am still seeing tons of ads).

Bounty of 1$ when added
##

**Comment by jacobsalmela** [comment]
I have some ideas already.

**Comment by TylonHH** [comment]
Are you sure that PiHole is running?
Can you open www.a-ads.com ? If yes your PiHole is not running correctly.

**Comment by gforke97** [comment]
Yes Pihole is running (its logging like crazy too)
And i can open a-ads.com (it opens via https pihole only blocks http i think)

**Comment by PromoFaux** [comment]
This will be super simple once (if) we get #731 merged. I've already worked out the command...!

**Comment by Bisaloo** [comment]
FWIW, a-ads.com is pi-holed over here (and no, it's not in my personal blacklist).

![screenshot from 2016-09-29 20-12-12](https://cloud.githubusercontent.com/assets/10783929/18966339/1ea75996-8681-11e6-8e62-c32e3dfbbf06.png)

**Comment by TylonHH** [comment]
Same here. Although it's https it should be blocked.
Are you trying to block subdomains too?

**Comment by gforke97** [comment]
Im using the installation over the script i set it up yesterday and have set the py as the dns server on my fritzbox

**Comment by gforke97** [comment]
And its logged as piholed but tge site still opens

**Comment by PromoFaux** [comment]
Would you guys mind chatting about this over in [gitter](https://gitter.im/pi-hole/pi-hole)? Just to keep the issue on topic with the original request...? Thanks!

**Comment by PromoFaux** [comment]
Leaving this here for future reference. It doesn't do anything now:

`sqlite3 /etc/pihole/pihole.db "select a.name from queries as a left join gravity as b on a.name = b.domain where b.domain is null and a.name not in ('<hostname>','pi.hole')" | sort -u > temp.txt`

**Comment by shadiakiki1986** [comment]
bountysource.com seems to be down ATM. I'll post on it for the bounty when it's back up

**Comment by DL6ER** [comment]
@gforke97 We already have the "Query List". I suggest the following: Go to this list and sort the results by "Status". Is this what you want (I added a "Show All" function in the current devel version). You can directly select everything and do some copy-and-paste magic. There even is a "Blacklist"-Button next to each of the shown links which will immediately send it to the blacklist (also in the devel branch).

Is this roughly what you are looking for or do you still want to have a "pretty" text file containing each of the not pi-holed domain per line, etc.?
I'm willing to work on that if you tell me more and if you are still interested.

**Comment by gforke97** [comment]
That sounds nice, could you add a Whitelist button too?
Can't check it out because I don't have the Dev Version.

**Comment by PromoFaux** [comment]
>could you add a Whitelist button too?

This is also included :)

**Comment by DL6ER** [comment]
See my comment [here](https://github.com/pi-hole/AdminLTE/pull/194#issuecomment-260209938) for a screenshot of what it will look like once released.

**Comment by PromoFaux** [comment]
@gforke97 The whitelist/blacklist functionality from the queries page is now in the master release... does this solve your issue, or would you still like a script to pass out a list?

If you still want a script, @shadiakiki1986's solution in #733 is still valid, however I'm unsure how likely it is to get into the main release yet. However, once this issue is closed, either him or @DL6ER will be able to claim the bounty, depending on which solution best fits your needs.

**Comment by PromoFaux** [comment]
Closing due to lack of response
