### ISSUE TITLE
Pi-hole Admin Console bit buggy

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#737]
##### Expected Behaviour:
0 Ads Blocked Today

Can see ads been  blocked in Recent Queries.

##### Actual Behaviour:
See http://imgur.com/APIffB8 and http://imgur.com/kCy3SLR

##### Steps to reproduce this issue:
go to http://myip/admin

**Comment by PromoFaux** [comment]
Hi there, thanks for the report! This has already been reported here:

https://github.com/pi-hole/AdminLTE/issues/150
