### ISSUE TITLE
Pihole Webinterface not writing to Black/Whitelist

### ISSUE THREAD

**Issue by gforke97** [pi-hole/pi-hole#739]
##### Expected Behaviour:
Domains added over the Webinterface should be added to the Black/Whitelist

##### Actual Behaviour:
Domains dont get added to /etc/pihole/whitelist.txt or /etc/pihole/blacklistlist.txt

##### Steps to reproduce this issue:
Adding a domain over the Webinterface
![image](https://cloud.githubusercontent.com/assets/19305191/19015396/f21890aa-8803-11e6-93cc-2cd3e26e3fb1.png)

**Comment by Mcat12** [comment]
Run `pihole -d` and share the log.

**Comment by PromoFaux** [comment]
What URL are you using to access the dashboard?

`http://pi.hole/admin` or `http://<pi's IP>/admin` should work with the whitelist scripts.

Anything else will not work for security purposes.

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #153](https://github.com/pi-hole/AdminLTE/issues/153) via [**ZenHub**](https://www.zenhub.com/)
