### ISSUE TITLE
Basic installer has two entries for installing the config

### ISSUE THREAD

**Issue by shadiakiki1986** [pi-hole/pi-hole#741]
##### Expected Behaviour:

One installation of configs only
##### Actual Behaviour:

Two installations of config
Can  be seen in [this log](http://paste.debian.net/851373/) on lines 35 and 39
Not sure if this was intentional
##### Steps to reproduce this issue:

Just run `automated\ install/basic-install.sh`
The duplicated line is on [line829](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L829) and 830 in `installPihole`. Also in `updatePihole`
##

**Comment by PromoFaux** [comment]
I don't see it doing any harm, but good catch! There is another duplicate in the function below, too!

I'll take a look.

**Comment by Fedora-Core** [comment]
That's not the only duplicate !

Lines 814 and 945 both make directory /etc/pihole

No harm done, but sloppy ;-)

Furthermore, the available diskspace is detected AFTER installing the installer dependencies .... 

Also sloppy ;-)

Greetings, F.C.

**Comment by PromoFaux** [comment]
I just went into the blame section of the file. It was me :embarrassed-face: I will fix it!

**Comment by Fedora-Core** [comment]
Warning:

The directory /etc/pihole should be created in the main dialog.
The proposed modification removed it, and left the double in the function installPihole.
That is too late.
The directory /etc/pihole is needed by the functions that are executed BEFORE installPihole.

Sorry to not have mentioned this in my intervention :(

Will do better next time ;-)

Greetings, F.C.

**Comment by PromoFaux** [comment]
I've just changed it back,

But reading through the code, it wouldn't have mattered! Unless I'm missing something, there is nothing that depends on the directory existing between `welcomeDialgs` and `installPihole` Pleas correct me if I'm wrong!

**Comment by Fedora-Core** [comment]
You are 100% right - I think.

Since the introduction of /etc/pihole/setupVars
and the complete clean-up of the individual installation response files that used to go to /etc/pihole
there is no longer a need for the /etc/pihole directory that early.

I must print-out and - use my yellow markers on - a more recent version of the script ;-)

Greetings, F.C.

**Comment by PromoFaux** [comment]
Fixed in previous release
