### ISSUE TITLE
Very high traffic to dns.msftncsi.com

### ISSUE THREAD

**Issue by aleph-1** [pi-hole/pi-hole#744]
Ok,

I’m not sure this is a bug – but its definitely odd…

Pi-hole has been running flawlessly for the last 6+ months on a pi. The last month or so Pi-Hole is reporting an insane amount of traffic as follows:

ct  2 15:04:40 dnsmasq[27283]: query[A] dns.msftncsi.com from 192.168.0.1
Oct  2 15:04:40 dnsmasq[27283]: cached dns.msftncsi.com is 131.107.255.255
Oct  2 15:04:45 dnsmasq[27283]: query[A] dns.msftncsi.com from 192.168.0.1
Oct  2 15:04:45 dnsmasq[27283]: forwarded dns.msftncsi.com to 8.8.4.4
Oct  2 15:04:45 dnsmasq[27283]: reply dns.msftncsi.com is 131.107.255.255
Oct  2 15:04:50 dnsmasq[27283]: query[A] dns.msftncsi.com from 192.168.0.1
Oct  2 15:04:50 dnsmasq[27283]: forwarded dns.msftncsi.com to 8.8.4.4
Oct  2 15:04:50 dnsmasq[27283]: reply dns.msftncsi.com is 131.107.255.255

non stop, day and night.  192.168.0.1 is my router. 

Googling  dns.msftncsi.com – is some kind of  “Microsoft alive check” 

BUT, I have no windows s/w  in my network

To really narrow it down,  I have  switched off all 25 devices on my network,  to end up with the  router (RT-AC66U), pi hole & a  ubuntu laptop.  Still 4  queries per minute !! 

So it’s either the router, the Pi-hole, or the Ubuntu laptop … with Pi-hole pointing the finger at the router. I have checked the Asus forums and can’t find anything...

One other thing, I have fired up wireshark  and I see no packets containing    the string “dns.msftncsi.com” or “ 131.107.255.255” in any traffic – which makes no sense , unless Pi-hole is ‘making stuff up’

any thoughts, anything to try?

**Comment by jacobsalmela** [comment]
What about other Mircosoft devices like an Xbox?

**Comment by PromoFaux** [comment]
I have a total of 8 queries on that domain myself.

Some from my windows 10 PC, and the rest from my Xbox

![image](https://cloud.githubusercontent.com/assets/1998970/19021827/c9482866-88c1-11e6-83bc-fa7b6ef56bb1.png)

How about a windows phone?

**Comment by AKJT** [comment]
It's your Router

Found this [here](http://www.snbforums.com/threads/beta-asuswrt-merlin-380-61-beta-is-now-available.33914/page-4#post-273932)

> New WAN state detection code from Asus. Make sure you aren't blocking dns.msftncsi.com. 

 [Github file](https://github.com/RMerl/asuswrt-merlin/blob/dd3bfa147cec6c3f74efab863b31269ef97d0a55/release/src/router/shared/defaults.c#L1106) where you can find it.

And [Github commit](https://github.com/RMerl/asuswrt-merlin/commit/bcde2858bf296d645409a3c7d9014b210c7e9199#diff-bfa6420c19ccc27ccfcc70113cbc0590R1106) where it got added (warning slow)

**Comment by aleph-1** [comment]
@ all there is nothing MSFT on the network (not phones, xboxen, etc). I'm seeing 6 requests  & replies per minute at least... 24x7...  really annoying 

@AKJT  Its my router.... Thanks for finding this!!  I'm surprised stumble across it. but I'm not running Merlin on it, just the Asus code line.   

I don't think it's blocked, as it's not getting pi-holed. 

Thanks for the help - I'm off to the Asus forum to see whats going on.

**Comment by PromoFaux** [comment]
I had a similar annoyance recently trying to track down something that was looking up `www.google.com` about 50 times a minute! Turned out to be Plex's  DLNA server...

Glad you (sort of) got to the bottom of it!
