### ISSUE TITLE
OpenVPN Running on Router.

### ISSUE THREAD

**Issue by escapologyBB** [pi-hole/pi-hole#747]
I have a question I really can't seem to get my tiny little mind round, I really love PI-Hole and as I've mentioned elsewhere I've already contributed financially because this is such a great service.  That out of the way, here comes my possibly potentially stupid question:

I have just installed [DD-WRT](http://dd-wrt.com/) on my router primarily so that I can run an OpenVPN client configuration to increase my privacy up to at least 11, however all of my internal devices have their DNS set to `192.168.0.55` which is the address of the Pi-Hole.  The upstream providers are OpenDNS.

So my question is, do I now make my upstream DNS provider my router running the OpenVPN client so that all traffic is tunnelled through the VPN tunnel or should I just leave well alone?  Does that make sense?  I'm wondering if the pie Pi-Hole is bypassing the VPN by using the OpenDNS IP addresses, which it still may be doing but because every connection on my network has to go through the router  it could just be connecting to the OpenDNS servers whilst inside the VPN tunnel already.  See, I've confused myself and it's only been three paragraphs!

Any help would be greatly appreciated.  :-)

**Comment by PromoFaux** [comment]
Before it gets too confusing... If I understand correctly, you don't need to change anything. The openDNS lookups still have to go through your router, which is connected to the wider world over a VPN. 

If you really like, and want to use whatever DNS servers the VPN provider has, er, provided... just change `piholeDNS1` to your router IP in `/etc/pihole/setupVars.conf` and leave `piholeDNS2` blank. Then run `bash /etc/.pihole/automated\ install/basic-install.sh` to reconfigure your current settings.

I might be wrong about the first paragraph, but the second paragraph is correct!

**Comment by Mcat12** [comment]
Pinging for update @escapologyBB

**Comment by escapologyBB** [comment]
Sorry about the radio silence, medical things are stupid and incredibly inconvenient.  Who knew?!

Thank you for the response @PromoFaux, and you are entirely correct I didn't need to change a thing because everything is going straight through the VPN tunnel.  Because my Pi-Hole is on my local network it necessarily has to go through the router to get out onto the wider Internet, I just wasn't thinking the problem all the way through to the end.

Anyway, I checked with WireShark and nothing is leaking, so problem solved.  I'm going to close this comment and mark it as "user not paying full attention to the problem"

Thanks guys 👍

**Comment by dschaper** [comment]
Feel free to reopen if you run into problems when you get a chance to explore some more. Good Luck!

**Comment by escapologyBB** [comment]
@dschaper Will do, although I'm having problems describing the whole thing to people without them/me laughing because I keep explaining where my Pi-Hole is!  Unintended consequences or what?!  :-)
