### ISSUE TITLE
Suggestion: Don't clobber existing lighttpd configuration(s) on install

### ISSUE THREAD

**Issue by stonedbovines** [pi-hole/pi-hole#751]
##### Expected Behaviour:

Existing sites continue to work as normal.
##### Actual Behaviour:

Main configuration file, /var/lighttpd/lighttpd.conf, gets overwritten; content of /var/www/html gets overwritten. Existing sites disappear.
##### Steps to reproduce this issue:

Install pi-hole.
The issue being that pi-hole assumes it is the only thing that will be using certain features of that box.
##### Resolution for my system:

I have tinkered with a post-install system to get it to serve multiple sites. My current live system isn't under source control, and is also using a slightly older version of pi-hole than the current one.

The basic changes were:
- don't use /var/www/html as destination folder, because we don't know what is already in there
- set up /var/www/pihole
- don't overwrite /etc/lighttpd/lighttpd.conf, because we don't know what is already in there
- set up /etc/lighttpd/pihole.d
- add one final line (checking that it isn't already there) to /etc/lighttpd/lighttpd.conf to read all contents of /etc/lighttpd/pihole.d `include_shell "cat /etc/lighttpd/pihole.d/*.conf 2>/dev/null"`
- note that anyone already using _other_ directories to hold other site details will be (mostly) unaffected
- they might need to add host constructs to their details, if they have not already done so
- transfer the pi-hole specific options, currently in lighttpd.conf where they shouldn't be, to /etc/lighttpd/pihole.d/01-pihole.conf, changed to use `server.modules +=`
- a lot of the current detail is actually part of the basic install of lighttpd which, at worst, has just been installed, but I didn't have a fresh install of lighttpd to compare against
- in 01-pihole.conf, wrap specific moved options in a `$HTTP["host"] == "pi-hole" {...}` construct

You only need to ensure that each website uses a different name (eg in /etc/hosts), and you might need to whitelist those names (but you would be doing that anyway, because why would you setup your own site and then risk blacklisting it?)

Restarted lighttpd and all was well with the world. As far as I remember, any other changes were just to stop `pihole -up` from overwriting these changes, by making certain files (eg lighttpd.conf) immutable.
##

**Comment by sectioneight** [comment]
Definitely interested in this as well.

For my use case, I overwrite the `server.port` to not be 80 because I already have another web server doing other things there. Whenever I update pi-hole I have to remember to change it back.

**Comment by dschaper** [comment]
How do your clients handle being served whatever web page they are served when they need a response from port 80?

**Comment by sectioneight** [comment]
I'm using caddy to proxy all traffic on port 80 for the given vhost names to a different backend. Here's the relevant block from my Caddyfile:

```
blackhole:80 pi.hole:80 {
  root /var/www/html/pihole
  log /var/log/caddy/blackhole.log

  proxy / localhost:1080 {
   transparent
  }
}
```

Obviously I've changed `lighttpd.conf` to have a server port of 1080.

I haven't had any problems yet, or maybe I just don't know what else is supposed to be server from :80? I thought it was just the admin portal.

**Comment by dschaper** [comment]
The way it was designed was that a webbrowser would query for the IP address to send it's request for html elements. If they were ad elements, they would get the IP of the Pi-hole and send the request there. The `lighttpd` server would get the request, and 404 it, sending back a blank image to place in the page as it renders. This happens quickly so that rendering time is decreased without all the ad elements. If the browser doesn't get a 404 or 200, then it has to time out waiting for the element. If it gets actual html, then it will try to render that as the ad element.

**Comment by sectioneight** [comment]
Ah yes, I see that now :)

I think this works for me because caddy doesn't have a "default" vhost so when it gets a request with a `Host:` header that it doesn't recognize, it just sends a 404 back.

```
curl --verbose -H "Host: zzha.net" blackhole
* Rebuilt URL to: blackhole/
*   Trying 10.10.0.10...
* Connected to blackhole (10.10.0.10) port 80 (#0)
> GET / HTTP/1.1
> Host: zzha.net
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Server: Caddy
< X-Content-Type-Options: nosniff
< Date: Sun, 09 Oct 2016 03:00:26 GMT
< Content-Length: 19
<
* Connection #0 to host blackhole left intact
No such site at :80%
```

**Comment by dschaper** [comment]
Yeah, your setup basically eliminates the need for port 80 if it automatically sends out a 404, just short circuits the process. We do have the x-headers that we use to debug, but you most likely would be able to debug that portion of the setup without needing extra assistance.

**Comment by p1r473** [comment]
When I upgraded, not only did it nuke my lighttpd file containing my
password protected Admin page, but also my modified chronometer script
(which is fine and easily fixed) but worse of all, nuked my dnsmasq file
containing my dnscrypt ports

However I understand the need to replace files so I just backed up my files
and re added my changes after every upgrade

**Comment by dschaper** [comment]
We have an installer function that specifically does a check on `dnsmasq` files, unless you modified `01-pihole.conf` which is subject to change. If you need further customization for `dnsmasq` use a new snippet file, don't modify `01-pihole.conf`.

**Comment by dschaper** [comment]
The Pi-hole was designed to be a stand-alone solitary installation, it just happens to be serendipity that it can operate with other servers and daemons at the same time. We do try to avoid stepping on other configurations when possible, but not at the cost of performance or function of the Pi-hole.

**Comment by sectioneight** [comment]
In case anybody else stumbles upon this issue and is using Caddy, here is a fully-functional definition that will rewrite JS requests and properly serve unknown hosts to the lighttpd backend (key being the `0.0.0.0.:80` host accept):

```java
blackhole:80, pi.hole:80, 0.0.0.0:80 {
  root /var/www/html/pihole
  log /var/log/caddy/blackhole.log

  rewrite {
    ext js
    to index.js
  }

  proxy / localhost:1080 {
    transparent
  }
}
```

**Comment by sectioneight** [comment]
But yea, I totally get what you guys are going for, just wanted to bring up the use case in case it helped inform future decisions. Obviously open source software is tough (I maintain a few myself) and this isn't on the top of your list.

That said, if you have a proposal you like for how to support this I'd be happy to take a swing at implementing it.

**Comment by dschaper** [comment]
If you could add a section in to the WiKi (we're working on a real wiki as soon as I get to setting it up) so that the information is available to users beyond the lifetime of this thread, that would be great. I'm interested in Caddy though, if that is something that can help us move toward a modular setup where the actual webserver doesn't matter, then that would be awesome.

**Comment by sectioneight** [comment]
Sure thing, I left a page here: https://github.com/pi-hole/pi-hole/wiki/Caddy-webserver-frontend

**Comment by p1r473** [comment]
So for the dnsmasq changes, how do I add my changes into a new file? Do I
just make a new file with my changes only in it, or do I copy the whole of
my modified 01-pihole.conf?
All I am changing is my dnscrypt stuff like the IPs of my local
dnscrypt service and the all-server function

**Comment by stonedbovines** [comment]
Yes, just your changes. Create named files, where each holds a particular set of details.
For example, I have 
01-pihole.conf
02-wildcards.conf
03-local.conf

where 02 holds config details for blocking wildcarded domains and 03 holds my lan details. I _could_ have put them in a single separate file, but I preferred to split the tasks into different files.

My 01 _is_ a slightly modified version, to disable logging (I don't need it, so no need to write anything to the SD card), but I have also disabled upgrading, so that won't get overwritten.

**Comment by p1r473** [comment]
So does the 02 file overwrite the 01 file?
If I have my 01 file with 8.8.8.8 and 8.8.4.4 and my 02 file with my
dnscrypt 127.10.10.2 and 127.10.10.3?

Or do I remove the 8.8.8.8 and 8.8.4.4 out of the 01 file, and only have
the 127.10.10.2 and 127.10.10.3 ip set in the 02 file?

Additionally do I need to set the file as active anywhere ?

**Comment by stonedbovines** [comment]
It would _add_ your server lines. What _I_ would do is comment out the server lines in 01 and make that 01 file immutable, and then add your own server lines to an 02 file. That would allow you to tinker with your changes in the 02 file without having to reopen the 01 for further edits.

No need to specifically set the 02 as active. The way dnsmasq has been setup is to read any conf files it finds in that directory - which is how the 01 gets read in the first place.

**Comment by dschaper** [comment]
@p1r473 Run the install again, and select Custom DNS for the upstream and enter in your custom IP addresses for the upstreams. No need to mess with setting immutable bits and breaking the configuration. If the only changes you have are to use the two `127` addresses for your DNS servers, then we have a configuration setting for things like that.

**Comment by stonedbovines** [comment]
Sure, for simple server changes, you could reinstall, but that can have its own problems (hence this issue!)

It is, however, what I have to do to permanently disable logging. I also use an immutable pihole cron file, and an immutable lighttpd.conf to prevent the unwanted 'de-customisation' that an update brings. I _could_ have a process run after an update to 'correct' matters, but it is better to disallow unwanted changes in the first place.

**Comment by dschaper** [comment]
Well, we're dealing with 3 separate issues in this one thread, the solution for one of the issues already exists. Your issue is a separate thing. If a user overwrites Pi-hole specific config files then bad things happen. As you are requesting a config snippet for `lighttpd` we'd expect that the Pi-hole specific config snippet wouldn't be modified by the end user.

**Comment by sectioneight** [comment]
@dschaper agreed, let's break this down into sub-issues. Sorry for derailing the conversation :|

**Comment by jacobsalmela** [comment]
`lighttpd.conf` customizations are now possible via a [secondary config file](https://github.com/pi-hole/pi-hole/pull/704):

**Comment by justinglock40** [comment]
@sectioneight Do you have an update for this with the new changes to Caddy? I can't get this to work for anything?

**Comment by sectioneight** [comment]
@justinglock40 I haven't upgraded to "the new changes to Caddy" -- can you elaborate on the error, what old/new versions of Caddy you're on? I'll try upgrading my personal box to the latest Caddy but want to make sure I'm repro-ing the same issues as you are.

FWIW I'm on Caddy 0.10.4 on Fedora 26.

**Comment by sectioneight** [comment]
Also "I can't get this to work for anything" -- can you clarify? Are you getting error messages, unable to launch caddy, any extra information you provide can be helpful in identifying the issue.
