### ISSUE TITLE
bad adress in /etc/pihole/gravity.list line 1

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#758]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [X] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[BUG | ISSUE] Actual Behaviour:**
my pihole.log has after reboot 9063k lines.
for eg.
``bad adress in /etc/pihole/gravity.list line 1``
and so on unti line 103149
So I checked the `gravity.list`
````
 005.free-counter.co.uk
 006.free-adult-counters.x-xtra.com
 006.free-counter.co.uk
 006.freecounters.co.uk
 007.free-counter.co.uk
 007.go2cloud.org
 0075-7112-e7eb-f9b9.reporo.net
 008.free-counter.co.uk
 008.free-counters.co.uk
 00czda00-system.esy.es
 00fun.com
 00game.net
 00hq.com
 00inkjets.com
````
Please note the Space at the beginning of each line.

**(Optional) Debug Log generated by `pihole -d`:**
[pihole -d](http://termbin.com/85ln)

**Comment by dschaper** [comment]
Can you delete `/etc/pihole/gravity.list` and run `pihole -g` to rebuild that list?

**Comment by TylonHH** [comment]
Thank you

**Comment by TylonHH** [comment]
Could please check https://www.reddit.com/r/pihole/comments/55a540/moving_web_interface/ my last two comments?

**Comment by dschaper** [comment]
Either your other project uses port 80 or Pi-hole uses port 80, you can't have both. Pi-hole can't run on any port other than 80 due to how the web works, so if you want to run both projects you will need to get the other project on to another port.

**Comment by TylonHH** [comment]
the other project runs already on Port 81. I can open it via ``http://192.168.178.22:81`` but there is also running an apache 2 and the curl cant resolve the localhost.

**Comment by dschaper** [comment]
What's the output from `sudo netstat -tulpn`?

**Comment by TylonHH** [comment]
````
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1095/mysqld     
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      538/Xtightvnc   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      715/lighttpd    
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      538/Xtightvnc   
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      424/dnsmasq     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      636/sshd        
tcp6       0      0 :::80                   :::*                    LISTEN      715/lighttpd    
tcp6       0      0 :::81                   :::*                    LISTEN      1096/apache2    
tcp6       0      0 :::53                   :::*                    LISTEN      424/dnsmasq     
tcp6       0      0 :::22                   :::*                    LISTEN      636/sshd        
udp        0      0 0.0.0.0:53              0.0.0.0:*                           424/dnsmasq     
udp        0      0 0.0.0.0:68              0.0.0.0:*                           635/dhcpcd      
udp        0      0 192.168.178.22:123      0.0.0.0:*                           704/ntpd        
udp        0      0 127.0.0.1:123           0.0.0.0:*                           704/ntpd        
udp        0      0 0.0.0.0:123             0.0.0.0:*                           704/ntpd        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           331/avahi-daemon: r
udp        0      0 0.0.0.0:44575           0.0.0.0:*                           331/avahi-daemon: r
udp6       0      0 :::53                   :::*                                424/dnsmasq     
udp6       0      0 ::1:123                 :::*                                704/ntpd        
udp6       0      0 fe80::6d0b:f555:24f:123 :::*                                704/ntpd        
udp6       0      0 :::123                  :::*                                704/ntpd        
udp6       0      0 :::5353                 :::*                                331/avahi-daemon: r
udp6       0      0 :::39267                :::*                                331/avahi-daemon: r
````

**Comment by dschaper** [comment]
`curl -I http://localhost`
`curl -I http://localhost:81`

**Comment by TylonHH** [comment]
````
root@raspberrypi:~# curl -I http://localhost
HTTP/1.1 200 OK
X-Pi-hole: A black hole for Internet advertisements.
Content-Type: text/html
Accept-Ranges: bytes
ETag: "2713168023"
Last-Modified: Sun, 25 Sep 2016 14:25:14 GMT
Content-Length: 10701
Date: Fri, 07 Oct 2016 21:58:19 GMT
Server: lighttpd/1.4.35
````
and
root@raspberrypi:~# curl -I http://localhost:81
HTTP/1.1 200 OK
Date: Fri, 07 Oct 2016 21:58:54 GMT
Server: Apache/2.4.10 (Raspbian)
Content-Type: text/html; charset=UTF-8
````

**Comment by dschaper** [comment]
Okay, I'm not sure I understand what the issue is? Pi-hole is listening on 80 and Apache2 is listening on 81 and both are responding to traffic requests?

**Comment by TylonHH** [comment]
so its not PiHole related. I'll ask the other guys how to change the port.
Because in there log, I still see Port 80
````
[Oct 08 00:02:43][chn0] CURL: Connection 12 seems to be dead!
[Oct 08 00:02:43][chn0] CURL: Closing connection 12
[Oct 08 00:02:43][chn0] CURL: Hostname was found in DNS cache
[Oct 08 00:02:43][chn0] CURL:   Trying ::1...
[Oct 08 00:02:43][chn0] CURL: Connected to localhost (::1) port 80 (#13)
[Oct 08 00:02:43][chn0] CURL: Sent 41 bytes..
[Oct 08 00:02:43][chn0] CURL: Sent '[ [ 1475877763755, 179.71000000000001 ] ]' bytes
[Oct 08 00:02:43][chn0] CURL: upload completely sent off: 41 out of 41 bytes
[Oct 08 00:02:43][chn0] CURL: Server lighttpd/1.4.35 is not blacklisted
[Oct 08 00:02:43][chn0] CURL: Received 61 bytes
[Oct 08 00:02:43][chn0] CURL: Received 'var x = "Pi-hole: A black hole for Internet advertisements."
````

**Comment by dschaper** [comment]
Yeah, their daemon is hardcoded to query port 80, which `lighttpd` for Pi-hole is running on, as seen on the last line of that codeblock. If they are trying to call home, then they need to call port 81 instead.

**Comment by TylonHH** [comment]
last (offtopic) issue: please check http://termbin.com/sh1e
my interface show nothing

**Comment by dschaper** [comment]
Please open a new issue for this. Thank you

**Comment by Mcat12** [comment]
The reason for the incorrectly formatted list is because on a new install the variables for IP address, interfaces, etc is not saved before gravity is run. So gravity doesn't know the IP address, and leaves that part of the list blank.

**Comment by dschaper** [comment]
Fixed in https://github.com/pi-hole/pi-hole/pull/770/commits/10e1a03c7667488a658e0b2380a442cf711ccfc5
