### ISSUE TITLE
PHP Warning Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#759]
**[BUG | ISSUE] Actual Behaviour:**
The admin page just shows the total number of domains being blocked. The other figures are 0. Also the query log is empty.
But Ads are still blocked on my devices.

I run `piholeLogFlush.sh` with no success.
My `/var/log/pihole.log` is now 4193 big.
I have an RPi 3
With nearly the same setup it works like a charm. What have I done? I completely installed the new update 2.9.2 on top on an other [project](https://github.com/volkszaehler).

Here is my [pihole -d](http://termbin.com/30sk)

**Comment by dschaper** [comment]
Quick check: 
```
cd /etc/.pihole
sudo git status
```
Just to make sure you are on the master branch.

```
cd /var/www/html/admin
sudo git status
```

**Comment by TylonHH** [comment]
yes I'm. Both response with nothing to change.

**Comment by dschaper** [comment]
`ls -lahc /var/log/pihole.log`

**Comment by TylonHH** [comment]
`-rw-r----- 1 dnsmasq root 50K Okt  8 00:37 /var/log/pihole.log`

**Comment by dschaper** [comment]
Okay, this looks like it may be an Admin interface issue. Moving this issue over to that GitHub repository.

**Comment by dschaper** [comment]
Issue moved to [pi-hole/AdminLTE #155](https://github.com/pi-hole/AdminLTE/issues/155) via [**ZenHub**](https://www.zenhub.com/)
