### ISSUE TITLE
Moving Log to external storage

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#763]
I have an general question, with using PiHole on an RPi
Does it make sense to move the log(s) to an external storage (e.g. NAS)? I'm asking that because there is an limitation to read/write the SD card. But I guess PiHole doesn't do that intensive?!
I already destroyed three SD cards because I wrote to often an image on them or formated them.

Cheers

**Comment by Mcat12** [comment]
I haven't had any trouble with SD cards getting too many reads/writes, but the others might have more experience with this question. If you want to move the logs to a different storage device, you can do that.

**Comment by dschaper** [comment]
Follow up on discourse for general questions.
