### ISSUE TITLE
line 929: [: =: unary operator expected

### ISSUE THREAD

**Issue by emansih** [pi-hole/pi-hole#767]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ x] The issue I am reporting can be *replicated*
- [ x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**
Warning should not appear

**[BUG | ISSUE] Actual Behaviour:**
Warning appears

**[BUG | ISSUE] Steps to reproduce:**
Run the script and watch the output
-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

**Comment by emansih** [comment]
A fix will be at line 929 

change _if [ $1 = "--i_do_not_follow_recommendations" ]; then_
to 
_if [ "$1" = "--i_do_not_follow_recommendations" ]; then_

**Comment by emansih** [comment]
shall i send a pull request?

**Comment by Mcat12** [comment]
https://github.com/pi-hole/pi-hole/pull/761#issuecomment-252414914

**Comment by Mcat12** [comment]
Sorry, but this is a duplicate
