### ISSUE TITLE
Package cache check is not functioning as expected.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#768]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [x] 10 (very familiar)

---
**OTHER:**

Automated install is not correctly detecting package cache status. 

```
oot@raspberrypi:/home/pi/idea/automated install# bash basic-install.sh
:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking installer dependencies...
:::    Checking for apt-utils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for dhcpcd5... already installed!
::: Using interface: eth0
:::
::: Setting IP to 192.168.1.182/24.  You may need to restart after the install is complete.
:::
::: Using IPv4 on 192.168.1.182/24
::: Using IPv6 on 2605:e000:3c8e:ca00:581:78bb:174a:8d8d
::: Using Google DNS servers.
::: Checking Pi-Hole dependencies:
:::    Checking for dnsutils... Not found! Installing.... [|]  E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/b/bind9/dnsutils_9.9.5.dfsg-9+deb8u6_armhf.deb  404  Not Found [IP: 2001:41c9:1:3ce::11 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                 done!
:::    Checking for bc... Not found! Installing.... done!
:::    Checking for dnsmasq... Not found! Installing.... done!
:::    Checking for lighttpd... Not found! Installing.... done!
```

The `dnsutils` install error is because `apt-get update` has not actually been run. The function to check if the Package Count actually changes the date of the files we stat so that it appears as if an `update` has been run when it hasn't. `upgrade` still shows 0 packages available, if an `apt update` is run manually then the `upgrade` shows the correct value with packages to be upgraded.

**Comment by dschaper** [comment]
Thinking this could be solved by running a check for the presence of the package after install, and if the package didn't actually install, either exit out of the script with the instructions to run a package cache update, or actually run the package cache update and re-install the package.

**Comment by dschaper** [comment]
`apt-get upgrade` does not update the package index...

**Comment by stonedbovines** [comment]
Why not use `command -v ${progname}` in `package_check()` and then check for `$?` being zero on success?

**Comment by dschaper** [comment]
I think I've found another way around, check for the date of `/var/lib/apt/lists/` and use that as the sentinel. It has the latest indexes and the date they were updated. Fixes the missing count as well.

**Comment by dschaper** [comment]
Resolved.
