### ISSUE TITLE
Debianize the script for easier installation

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#77]
Create a .deb of the pi-hole package to let facilitate an easier end-user experience. Create a repository for distribution of the .deb via apt-get on Debian-like environments.
##

**Comment by dschaper** [comment]
Working on this, just need to know what contact information you'd like to use. (Name and email address?)

**Comment by jacobsalmela** [comment]
Where is this information stored?  Is it so someone can contact me for any issues or what?  I'm not familiar with all the `apt-get` packing world.

**Comment by dschaper** [comment]
It's stored in the copyright file section.

**Comment by dschaper** [comment]
Upstream-Name

Single-line: the name upstream uses for the software

Upstream-Contact

Line-based list: the preferred address(es) to reach the upstream project. May be free-form text, but by convention will usually be written as a list of RFC5322 addresses or URIs.

**Comment by jacobsalmela** [comment]
Do you have a link with some more information?  I will probably just make an @pi-hole.net email or something.

**Comment by dschaper** [comment]
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#format-field

An @pi-hole.net email would work just fine.

**Comment by jacobsalmela** [comment]
OK thanks.  I'll get back to you on that.

**Comment by jacobsalmela** [comment]
adblock@pi-hole.net

**Comment by dschaper** [comment]
Thanks!

**Comment by dschaper** [comment]
What are your thoughts on splitting this into two packages. One package for the pi-hole (gravity) itself, and a separate package for the web-interface? Functionally gravity can run without the web-interface, and this would follow the repository setup since the web interface is in another repository.

**Comment by jacobsalmela** [comment]
I concur.

**Comment by dschaper** [comment]
Still working this, the bureaucracy of a .deb is a lot more complex than I thought. There's a ton of guides on doing it the wrong way, but not too many on doing it the Debian way while integrating git into the mix. Trying to coordinate git commits with quilt patchsets is odd. (Why can't it just be like Arch!)

**Comment by jacobsalmela** [comment]
I have been re-thinking this...  Just thinking it may make supporting the software too complex for the time I have to work on it.  I have been more of a weekend warrior on this project.

I think if we can fix #67, we could easily make a `case` statement to determine what OS the user is running when they run `curl -L install.pi-hole.net | bash`.  We could then have different variables for each type of system.

Then we could have other scripts like:

`curl -L update.pi-hole.net | bash`

`curl -L diagnose.pi-hole.net | bash`, etc...

It would be a lot easier for me to support since I could do everything through Github.  

How much work have you put into it so far?

**Comment by dschaper** [comment]
Fixing #67 would be ideal, and actually we could fork off the apt packaging to a separate repo that you wouldn't need to maintain. (Sort of similar to the DietPi set-up, but the debian repo would track your releases closely and when you do an update you'd just need to tag them with the new release info. The tag and the tarball that is generated with the tag are all that's needed for packaging.) That way you could continue to develop the way you are now, no changes needed and you wouldn't need to deal with the details of the packaging. Everything would be hosted on GitHub and the source code would be fully open and available for audit.

**Comment by jacobsalmela** [comment]
That's right.  I forgot that it just needs the version tagging, which I did earlier.

Cool; that will work good then.  Then users could still use the `basic-install.sh` if they want to.

Thanks for your knowledge on this!

**Comment by dschaper** [comment]
Not a problem, that's kind of why I added all the copyright info to all the files... Your attribution would be there no matter which way the PiHole was installed.

**Comment by PePaPossum** [comment]
Wasn't sure where to put this, but wanted to give you some feedback (sorry if I'm hijacking your issue)

I just installed Pi-Hole on a fresh install (virtual machine) of Debian Jessie. Works fine (Thank you!) apart from a few things I had to change:

-Debian Jessie doesn't have unzip install by default so it didn't unpack the web interface but works fine after manually installing unzip and re-running the script
-I don't have a Pi user so had to download the shell script first and change the usermod (in installpihole) command to my user before running

**Comment by jacobsalmela** [comment]
@PePaPossum, yeah, the project is focused on the RPi, but many people have been using it else where.  It will eventually be Debianized, but it's a ways off I think.

**Comment by jacobsalmela** [comment]
Closing for now as we pursue other packaging and/or distribution methods.  Re-open if it's still something you are working on, but I think from our discussions, it's not on the radar right now.
