### ISSUE TITLE
Bogus/unusable /etc/dnsmasq.d/01-pihole.conf written out by installer

### ISSUE THREAD

**Issue by wolftrouble** [pi-hole/pi-hole#776]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [x] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

I was running an existing installation of Pihole (I do not know the version now) that was working fine. I attempted to do an upgrade when advised by the UI by running the installer, which appeared to work, save for somehow gravity.list was invalid (missing IP for every line). For that I had to rerun gravity.sh, which fixed that problem without further issue.

However, my installation still wouldn't work. DNS queries were failing. After some troubleshooting I found the following in /etc/dnsmasq.d/01-pihole.conf:

```
# If you want dnsmasq to listen for DHCP and DNS requests only on
# specified interfaces (and the loopback) give the name of the
# interface (eg eth0) here.
interface=eth0
# Or which to listen on by address (remember to include 127.0.0.1 if
# you use this.)
listen-address=127.0.0.1
```

That's clearly not going to work - first off, by only listening on localhost it won't respond to external DNS queries. Second I have no active eth0 on my system (and never have); I use wlan0. And again, this was working pre-upgrade/re-install (not sure which to call it), and the installer didn't throw any errors that I recall.

It was easy enough to fix:

```
# If you want dnsmasq to listen for DHCP and DNS requests only on
# specified interfaces (and the loopback) give the name of the
# interface (eg eth0) here.
interface=wlan0
# Or which to listen on by address (remember to include 127.0.0.1 if
# you use this.)
listen-address=0.0.0.0
```

But it's just a lucky coincidence that I happen to be well-versed in dnsmasq - I would have been stuck for hours otherwise. Any idea what might have gone wrong here?

**Comment by dschaper** [comment]
It should be set to listen address as 127.0.0.1, it's an OR address. Either the interface, or 127.0.0.1, since you've declared an interface, the listen address doesn't matter. Setting it to 0.0.0.0 doesn't matter either, since you've set interface to wlan0. I'm going to say that either the upgrade pulled the wrong interface, or there was a confusion on the interface selection during the update. We are modernizing the intstall/update mechanism and catching a few bugs to keep things like this from happening, and when the next release is due out it should guard against selecting the incorrect interface. 

But again,
```
# Or which to listen on by address (remember to include 127.0.0.1 if
# you use this.)
listen-address=127.0.0.1
```
Is an OR clause, and won't be used since interfaces have been declared.

**Comment by wolftrouble** [comment]
Got it, thanks (and verified with testing). Thanks for all the hard work!
