### ISSUE TITLE
basic_install.sh | bad address at /etc/pihole/gravity.list

### ISSUE THREAD

**Issue by Fourdee** [pi-hole/pi-hole#777]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [404 with link. File does not exist] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [X] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[BUG | ISSUE] Expected Behaviour:**

Installing PiHole through ```curl -L https://install.pi-hole.net | bash``` should correctly set the  ```/etc/pihole/gravity.list``` file after ```gravity.sh``` is run by the install script.

**[BUG | ISSUE] Actual Behaviour:**

System IP address is missing from the generated list in ```/etc/pihole/gravity.list```, causing dnsmasq to fail.

in  ```/etc/pihole/gravity.list```:
```
 DietPi
 pi.hole
 0000mps.webpreview.dsl.net
 0001.2waky.com
 000dom.revenuedirect.com
 00119922.com
 001wen.com
```

In ```/var/log/pihole.log```: 
```
.......
Oct 12 16:49:43 dnsmasq[9576]: bad address at /etc/pihole/gravity.list line 33917
.......
```

**[BUG | ISSUE] Steps to reproduce:**

- ```curl -L https://install.pi-hole.net | bash``` 
- ```cat /var/log/pihole.log```

**[OTHER]**

- This issue was found by John from the DietPi forums and reported it to me.
- Running ```pihole -g``` manually, after the installation, seems to resolve the issue.
- My notes and testing: https://github.com/Fourdee/DietPi/issues/551

**Comment by jacobsalmela** [comment]
Thanks.  Running `pihole -g` again will fix the issue.  We discovered this already.  We'll have a fix in the next release.  Please see [#758](https://github.com/pi-hole/pi-hole/issues/758)

**Comment by Fourdee** [comment]
@jacobsalmela 
Sorry long day, didn't see the dupe. 👍

**Comment by jacobsalmela** [comment]
No problem.  Sorry for the bug.  =(
