### ISSUE TITLE
Debug process is missing IPv6 gateway, error is being thrown.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#778]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [x] 10 (very familiar)
---

**[BUG | ISSUE] Expected Behaviour:**
IPv6 Gateway should be determined correctly and ping should use the IPv6.

**[BUG | ISSUE] Actual Behaviour:**
Often IPv6 gateway is incorrectly determined, and even in cases where it is correctly identified, the ping process uses the IPv4 `ping` instead of `ping6` giving no useful debug information

**[BUG | ISSUE] Steps to reproduce:**

Run `pihole -d` with an active IPv6 stack

**Comment by dschaper** [comment]
Dropped a `6` off the ping...

**Comment by PromoFaux** [comment]
Fixed in current version.
