### ISSUE TITLE
blank page in app fast demdex call

### ISSUE THREAD

**Issue by iannao** [pi-hole/pi-hole#780]
Hi @dschaper , i'm not able to make question in the other thread, can you please tell me how did you fix the issue (blank page in iOS App)? we are having the same problem in our app.

Thank you
Best Regards
Riccardo

**Comment by dschaper** [comment]
Hi, can you run a `pihole -d` and when instructed by the debugging script, browse to the site that is showing up blank in iOS so that we can look at starting to debug the process? Thanks.

**Comment by iannao** [comment]
Hi Dschaper I'm not part of this project, I'm talkin about another App, but we are having the same issue

thank you
Best Regards
Riccardo

**Comment by dschaper** [comment]
We are only able to support Pi-hole. If this is not in regards to Pi-hole, then I invite you to look over our source code and see if there are any hints there to help you in your endeavors.

Thanks.
