### ISSUE TITLE
Spotify app (iOS) Home, Browse and Search don't work when using PiHole

### ISSUE THREAD

**Issue by SteveW25561** [pi-hole/pi-hole#781]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x ] The issue I am reporting can be *replicated*
- [x ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ x] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[BUG | ISSUE] Expected Behaviour:**
Spotify iOS apps should work to search music, browse or see the Home panel.
**[BUG | ISSUE] Actual Behaviour:**
Spotify on iOS apps shows an "An Error Occurred" screen if you open the Home or Browse menus, and any search doesn't work at all (also shows the same "Error" screen).

**[BUG | ISSUE] Steps to reproduce:**

- Log iOS device onto WiFi with PiHole as the DNS server
-Try to do any search on Spotify iOS app, or open the Home or Browse panels -- error will show
-On iOS device, shut off WiFi and switch to LTE: all functions work
-On IOS device, manually specify DNS (eg OpenDNS 208.67.222.222) - all functions work
-On iOS device, switch back to PiHole DNS - errors occur again

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/w7ph`
=== Here is what the log looks like if I'm banging on Spotify at around 9:20-9:21 pm:

#######################################
#######################################
Oct 13 21:20:32 dnsmasq[12644]: query[TXT] evictions.bind from 127.0.0.1
Oct 13 21:20:32 dnsmasq[12644]: config evictions.bind is <TXT>
Oct 13 21:20:32 dnsmasq[12644]: query[TXT] misses.bind from 127.0.0.1
Oct 13 21:20:32 dnsmasq[12644]: config misses.bind is <TXT>
Oct 13 21:20:32 dnsmasq[12644]: query[TXT] hits.bind from 127.0.0.1
Oct 13 21:20:32 dnsmasq[12644]: config hits.bind is <TXT>
Oct 13 21:20:32 dnsmasq[12644]: query[TXT] auth.bind from 127.0.0.1
Oct 13 21:20:32 dnsmasq[12644]: config auth.bind is <TXT>
Oct 13 21:20:32 dnsmasq[12644]: query[TXT] servers.bind from 127.0.0.1
Oct 13 21:20:32 dnsmasq[12644]: config servers.bind is <TXT>
Oct 13 21:20:33 dnsmasq[12644]: query[A] p23-keyvalueservice-current.edge.icloud.apple-dns.net from 192.168.1.1
Oct 13 21:20:33 dnsmasq[12644]: forwarded p23-keyvalueservice-current.edge.icloud.apple-dns.net to 212.71.249.225
Oct 13 21:20:33 dnsmasq[12644]: reply p23-keyvalueservice-current.edge.icloud.apple-dns.net is 17.248.144.182
Oct 13 21:20:39 dnsmasq[12644]: query[A] e6.whatsapp.net from 192.168.1.1
Oct 13 21:20:39 dnsmasq[12644]: forwarded e6.whatsapp.net to 212.71.249.225
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 158.85.58.36
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 173.192.222.163
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 173.193.205.11
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 169.47.5.213
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 169.45.219.242
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 169.45.214.242
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 158.85.58.9
Oct 13 21:20:39 dnsmasq[12644]: reply e6.whatsapp.net is 169.54.55.205
Oct 13 21:20:45 dnsmasq[12644]: query[AAAA] apresolve.spotify.com from 192.168.1.1
Oct 13 21:20:45 dnsmasq[12644]: forwarded apresolve.spotify.com to 212.71.249.225
Oct 13 21:20:45 dnsmasq[12644]: query[A] spclient.wg.spotify.com from 192.168.1.1
Oct 13 21:20:45 dnsmasq[12644]: /etc/pihole/gravity.list spclient.wg.spotify.com is 192.168.1.2
Oct 13 21:20:45 dnsmasq[12644]: reply apresolve.spotify.com is <CNAME>
Oct 13 21:20:45 dnsmasq[12644]: reply weblb-wg.gslb.spotify.com is NODATA-IPv6
Oct 13 21:20:45 dnsmasq[12644]: query[A] weblb-wg.gslb.spotify.com from 192.168.1.1
Oct 13 21:20:45 dnsmasq[12644]: forwarded weblb-wg.gslb.spotify.com to 212.71.249.225
Oct 13 21:20:45 dnsmasq[12644]: query[A] p15-buy.itunes-apple.com.akadns.net from 192.168.1.1
Oct 13 21:20:45 dnsmasq[12644]: forwarded p15-buy.itunes-apple.com.akadns.net to 212.71.249.225
Oct 13 21:20:46 dnsmasq[12644]: reply p15-buy.itunes-apple.com.akadns.net is 17.154.66.73
Oct 13 21:20:46 dnsmasq[12644]: reply weblb-wg.gslb.spotify.com is 194.132.198.198
Oct 13 21:20:46 dnsmasq[12644]: reply weblb-wg.gslb.spotify.com is 194.132.196.228
Oct 13 21:20:46 dnsmasq[12644]: reply weblb-wg.gslb.spotify.com is 194.132.197.198
Oct 13 21:20:46 dnsmasq[12644]: query[AAAA] sjc1-accesspoint-a93.ap.spotify.com from 192.168.1.1
Oct 13 21:20:46 dnsmasq[12644]: forwarded sjc1-accesspoint-a93.ap.spotify.com to 212.71.249.225
Oct 13 21:20:46 dnsmasq[12644]: reply sjc1-accesspoint-a93.ap.spotify.com is NODATA-IPv6
Oct 13 21:20:46 dnsmasq[12644]: query[A] sjc1-accesspoint-a93.ap.spotify.com from 192.168.1.1
Oct 13 21:20:46 dnsmasq[12644]: forwarded sjc1-accesspoint-a93.ap.spotify.com to 212.71.249.225
Oct 13 21:20:46 dnsmasq[12644]: reply sjc1-accesspoint-a93.ap.spotify.com is 194.68.29.196
Oct 13 21:20:48 dnsmasq[12644]: query[A] time-ios.g.aaplimg.com from 192.168.1.1
Oct 13 21:20:48 dnsmasq[12644]: forwarded time-ios.g.aaplimg.com to 212.71.249.225
Oct 13 21:20:48 dnsmasq[12644]: forwarded time-ios.g.aaplimg.com to 54.72.70.84
Oct 13 21:20:48 dnsmasq[12644]: reply time-ios.g.aaplimg.com is 17.253.34.125
Oct 13 21:20:48 dnsmasq[12644]: reply time-ios.g.aaplimg.com is 17.253.34.253
Oct 13 21:20:48 dnsmasq[12644]: reply time-ios.g.aaplimg.com is 17.253.52.253
Oct 13 21:21:09 dnsmasq[12644]: query[A] i.scdn.co from 192.168.1.1
Oct 13 21:21:09 dnsmasq[12644]: forwarded i.scdn.co to 212.71.249.225
Oct 13 21:21:09 dnsmasq[12644]: forwarded i.scdn.co to 54.72.70.84
Oct 13 21:21:09 dnsmasq[12644]: reply i.scdn.co is <CNAME>
Oct 13 21:21:09 dnsmasq[12644]: reply beta.spotify.map.fastly.net is <CNAME>
Oct 13 21:21:09 dnsmasq[12644]: reply prod.spotify.map.fastlylb.net is 151.101.16.246
Oct 13 21:21:11 dnsmasq[12644]: query[A] dws.connecteddata.com from 192.168.1.1
Oct 13 21:21:11 dnsmasq[12644]: cached dws.connecteddata.com is <CNAME>
Oct 13 21:21:11 dnsmasq[12644]: forwarded dws.connecteddata.com to 212.71.249.225
Oct 13 21:21:11 dnsmasq[12644]: reply dws.connecteddata.com is <CNAME>
Oct 13 21:21:11 dnsmasq[12644]: reply devicelb-1476719160.us-east-1.elb.amazonaws.com is 52.73.137.208
Oct 13 21:21:11 dnsmasq[12644]: reply devicelb-1476719160.us-east-1.elb.amazonaws.com is 52.6.137.101
Oct 13 21:21:14 dnsmasq[12644]: query[A] vod.ring.com from 192.168.1.1
Oct 13 21:21:14 dnsmasq[12644]: forwarded vod.ring.com to 212.71.249.225
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 52.20.175.167
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 54.87.89.218
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 54.236.131.106
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 52.202.14.79
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 54.173.235.83
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 52.204.28.188
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 54.236.85.59
Oct 13 21:21:14 dnsmasq[12644]: reply vod.ring.com is 52.200.124.145

**Comment by PromoFaux** [comment]
`pihole -w spclient.wg.spotify.com` should solve your problem....

As noted [here in the wiki](https://github.com/pi-hole/pi-hole/wiki/Whitelisting-tips#spotify) ;)

**Comment by SteveW25561** [comment]
Ah! Thanks so much. I didn't see the wiki but I appreciate the reply!

**Comment by PromoFaux** [comment]
You're welcome! Please feel free to reopen this issue if you continue to have problems!
