### ISSUE TITLE
Some QoL requests and minor UI changes

### ISSUE THREAD

**Issue by tomose** [pi-hole/pi-hole#782]
1. "Ads Blocked Today" -> "Queries Blocked Today"
Not everything blocked is an ad. Trackers, other malicious domains, etc.
2. "Of Today's Traffic Is Ads" -> "Of Today's Queries Denied"
Just better wording.
3. QoL request - Be able to set default number of entries in log via web interface (am aware that it can be done manually through editing a file).
4. QoL request - Filter log to show only blocked, unblocked, or all domains.
5. QoL request - Nav page links on top of query log as well (so you don't have to scroll down to move to the next page)

That's it really. Appreciate how great this works. Looking forward to being able to wildcard domains for easier blocking in the future. :)

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #161](https://github.com/pi-hole/AdminLTE/issues/161) via [**ZenHub**](https://www.zenhub.com/)
