### ISSUE TITLE
Changed piholeIP data not working

### ISSUE THREAD

**Issue by ookangzheng** [pi-hole/pi-hole#783]
I tried to change piholeIP to 0.0.0.0
and pihole -g
but gravity.list still list my own server ip

**Comment by dschaper** [comment]
What is it that you are trying to do?

**Comment by ookangzheng** [comment]
I need to redirect them to localhost, I dont want it point to my server IP

**Comment by dschaper** [comment]
So you want your clients to point back to themselves? You want 127.0.0.1 as the IP address that the Pi-hole sends the clients to?

**Comment by ookangzheng** [comment]
yap like this in gravity.list

127.0.0.1 xxx.com

**Comment by PromoFaux** [comment]
@ookangzheng If memory serves... you should be able to change the following settings in `/etc/pihole/setupVars.conf`

Set `IPv4addr=0.0.0.0/0` and `piholeIPv6=::/0` then run `bash /etc/.pihole/automated\ install/basic-install.sh` and choose "update" to refresh the values.

Let me know how you get on.

**Comment by tuplink** [comment]
as a note if you set the host to localhost (127.0.0.1) clients like chrome will keep "loading the page till its timeout is reached if the client dosnt have a webserver on it

**Comment by jacobsalmela** [comment]
@ookangzheng did @PromoFaux's solution work for you?
