### ISSUE TITLE
PiHole is blocking JavaScript from same host?!?!

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#784]
Hi,
I use PiHole on my raspberry without problems so far. I installed another project called [PiControl](https://pi-control.de/). This project use apache2 webserver, wich works fine except small issues.
I saw in the developer view under network (in FF) that they get an answer _"var x = "Pi-hole: A black hole for Internet advertisements."_
I URL for that interface is http://192.168.178.22/pic/
I tried to add the local IP adress to whitelist but I can't add,  _"Failure! Something went wrong."_
While refreshing that local page I checked `tail -f /var/log/pihole.log` but there is no querie(?)
What did I missed?

**Comment by TylonHH** [comment]
OK I investigatet a lil bit.
As far as I see PiHole is blocking **JavaScript**. I cant set the local IP to the whitelist.
So how can I use webservices on the same device (Raspberry Pi 3) where PiHole is runnung?

**Comment by Mcat12** [comment]
That project says it can use Apache, Nginx, or Lighttpd, so are you sure that it's not using Lighttpd? Either way, it looks like Lighttpd is still working, because it's still redirecting Javascript and running PHP. Comment out [this](https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L60) line in `/etc/lighttpd/lighttpd.conf` then run `sudo service lighttpd restart`.

**Comment by TylonHH** [comment]
Ok I'll try to double check which webserver is enabled. On startup of the installation I can choose which web server I would like to use. What server should I use on first choice?

I commented out the highlighted line and now it's working. But I'm afraid to loose some blocking actions.

**Comment by Mcat12** [comment]
You should be fine now, and it won't hurt you that that one line was commented out. We use Lighttpd, and our config seems to work with that project, so no more configuring is necessary. Re-open this if something isn't working.

**Comment by p1r473** [comment]
So what will happen if I now have an ad domain hs query? It just won't be
blocked ?

**Comment by TylonHH** [comment]
@Mcat12 you're right.
````
HTTP-Server 	lighttpd/1.4.35
PHP-Version 	5.6.24-0+deb8u
Benutzer 	www-data
````
Can't I whitelist the PiHole itself?

**Comment by Mcat12** [comment]
For one, you can't whitelist/blacklist an IP address. Second, the Pi-hole is always allowed through. That JS block is a little too restrictive, and we plan to change that in a future version.

**Comment by p1r473** [comment]
Great- soon as its changed, hopefully PiControl will work?

**Comment by Mcat12** [comment]
If you follow the instructions above (commenting out the JS blocking line) it will work.
