### ISSUE TITLE
can't make 'a new version is available' overlay close

### ISSUE THREAD

**Issue by vinceskahan** [pi-hole/pi-hole#785]
Is there a way to close the blasted overlay that nags heck out of us ?   Why aren't you just putting up a small red 'update available' or something ?

**Comment by PromoFaux** [comment]
Yeah, we hear you on that! It's a bit annoying.. with any luck we'll get it into the next update. (You could always update.. that will get rid of it!)

If you don't want to update, just click anywhere else on the page to make it disappear ...

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #163](https://github.com/pi-hole/AdminLTE/issues/163) via [**ZenHub**](https://www.zenhub.com/)
