### ISSUE TITLE
Admin page keeps loading and ads not blocked

### ISSUE THREAD

**Issue by Hoaxr** [pi-hole/pi-hole#791]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [x] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

I have a pi running osmc with pi-hole now

I enterd the ip of my pi in my router on the DHCP page in the DNS field
My devices get the DNS server, i can connect to the internet but ads are not blocked.

As far as i can see everything is correct.

The admin page keeps loading: https://s12.postimg.org/4p40hworh/screen.png

The pihole -d log: http://termbin.com/erdh

**Comment by PromoFaux** [comment]
I've added the template back into your issue. Please update the relevant sections. :)

**Comment by dschaper** [comment]
Try running a `pihole -g` and the post a new debug `pihole -d`

**Comment by Hoaxr** [comment]
Here it is: http://termbin.com/6sih

**Comment by dschaper** [comment]
Okay, you at least are blocking ads now. The problem with the web interface is being rectified in the many GitHub issues and PR's that have been opened for that problem. (May want to check the AdminLTE repo issue tracker to see if there are any clues there to help you out.)

**Comment by Hoaxr** [comment]
yeah i can see the ads are blocked now, will i always see this gray screen? (with adblocker plugin in chrome the just disappear?

https://s22.postimg.org/fpt3hdun5/screen3.png

**Comment by dschaper** [comment]
No, you should be getting a blank image back from `lighttpd` daemon, unless the ad is from an https source. Are all the ad replacements giving the broken page icon or just some of the ad replacements?

**Comment by dschaper** [comment]
What does `curl -I http://localhost` and `curl -I http://localhost/admin/` show on the Pi-hole install? We are looking for X-headers that indicate the Pi-hole is serving the ad replacement assets correctly.

**Comment by Hoaxr** [comment]
Nevermind is was a browser cache everything works perfect now thanks :) i will check the adminLTE repo for the admin panel problem.
