### ISSUE TITLE
Clean install, being told to reference /etc/pihole/setupVars.conf, when it does not exist

### ISSUE THREAD

**Issue by cybrnook** [pi-hole/pi-hole#793]
Details in forum:
https://pi-hole.net/forums/topic/another-error-during-vanilla-install/

**Comment by PromoFaux** [comment]
Also fixed in the next release ;)

Please follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) next time !
