### ISSUE TITLE
Manage multiple blacklists

### ISSUE THREAD

**Issue by Bisaloo** [pi-hole/pi-hole#795]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [x] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**FEATURE REQUEST:**

It would be really useful to have the ability to create and manage multiple blacklists. It would be a major step in the process of allowing users to share their custom blacklists.

For example, the default blocklists seem to miss a lot of mobile game ads. So I started to put the offending domains in my blacklist. But I also added other domains because of privacy issues.

Now, if I had the ability to split my blacklist in multiple parts:
- mobile game ads
- privacy threats

I could then put those lists on github to help users in a similar situation.

**Comment by TylonHH** [comment]
I guess you can add a list (domain) to `/etc/pihole/adlists.default`

**Comment by dschaper** [comment]
@TylonHH Raises a good point, we already handle multiple blacklists. If you create a repository for your custom domain lists and store it as a HOSTS formatted list, then you can add that URL to the custom `adlists`. If you want to publicize the repository you created for your blacklist, you can do that as well.

**Comment by Bisaloo** [comment]
Hum, right, that's a neat way to do it. I hadn't thought about it.

I still think it would be useful to add something like I described in the web GUI, in the blacklist tab but I get it if you prefer to focus on other bugs/features.

**Comment by xxcriticxx** [comment]
@Bisaloo i could use your list where can i find it?

**Comment by DL6ER** [comment]
@Bisaloo I'm currently working on improvements for the web UI. What would be the benefit of selecting to *which* blacklist an entry should go? How should this look like?

**Comment by PromoFaux** [comment]
Maybe a page to manipulate `/etc/pihole/adlists.list` with checkboxes, with the ability to add other lists

**Comment by Bisaloo** [comment]
@DL6ER I was thinking like subsections in the blacklist section in the toolbar where you could navigate to `blacklist_1`, `blacklist_2`, etc.

The attached screenshot shows what I had in mind:
![proposal](https://cloud.githubusercontent.com/assets/10783929/20564417/82c0dfce-b18d-11e6-8e3a-cb2a5ddb9faf.png)

@xxcriticxx , I don't have many domains and it is all mixed up at the moment but I will remember to ping you when I release it.

**Comment by xxcriticxx** [comment]
@Bisaloo i can test what you have right now. Can you start new repository and upload your list?

**Comment by jacobsalmela** [comment]
As of 3.0, you can now [manage blocklists in the dashboard](https://github.com/pi-hole/AdminLTE/pull/252). @Bisaloo, does this solution satisfy your request?
