### ISSUE TITLE
Admin ui error

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#796]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [ ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [x] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

Hello,

Did a clean install of pi hole, when i got to 10.10.1.4/admin i get this popup

http://i.imgur.com/tFCiP3Q.png

remove /admin and reinstall does not fix it :(

**Comment by PromoFaux** [comment]
Hi there, I've added the issue reporting template back into your OP. Please follow it! :)

**Comment by Tntdruid** [comment]
did a clean os install and it works now. did that too before :)

**Comment by PromoFaux** [comment]
It may be down to the size of your logs... What hardware are you running on?

**Comment by Tntdruid** [comment]
Raspberry Pi 3 Model B

**Comment by TylonHH** [comment]
Please post the result of `df -h`

**Comment by Tntdruid** [comment]
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G 1009M   14G   8% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M  6.3M  457M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1   63M   21M   43M  33% /boot

**Comment by TylonHH** [comment]
Where is the tmp?
Try also `df -h /tmp`
