### ISSUE TITLE
0 ads blocked

### ISSUE THREAD

**Issue by MLWALK3R** [pi-hole/pi-hole#801]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [ ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [x] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**
Ads get blocked

**[BUG | ISSUE] Actual Behaviour:**
No ads are blocked

**[BUG | ISSUE] Steps to reproduce:**

visit any site with ads, 0 get blocked
Do dig or nslookup up non are blocked
Do curl to blocked sites no header from pi-hole.
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

No ads seem to be getting blocked.

http://termbin.com/0bvi

/etc/resolv.conf is set to 127.0.0.1

**Comment by PromoFaux** [comment]
Please don't remove the issue template. It is there for a reason! I've added it back in for you to fill out.

**Comment by PromoFaux** [comment]
Also, I notice you debug log is missing 7 sections from the end... did you edit it?

**Comment by MLWALK3R** [comment]
Nope i left it running, I'll run it again.

**Comment by MLWALK3R** [comment]
I've also noticed now no stats are loading after running the debug https://lel.ovh/1476708927 and seems the debug is taking forever on 

> `::: Writing current Pi-hole traffic to debug log...
:::     Try loading any/all sites that you are having trouble with now...
:::     (Press ctrl+C to finish)
`

**Comment by PromoFaux** [comment]
>::: (Press ctrl+C to finish)

**Comment by PromoFaux** [comment]
After that you should see something like:
```
:::     Try loading any/all sites that you are having trouble with now...
:::     (Press ctrl+C to finish)
♥
::: Finishing debug write from interrupt... Quitting!
::: Finshed debugging!
::: The debug log can be uploaded to Termbin.com for easier sharing.
::: Would you like to upload the log? [y/N] y
::: Debug log can be found at : <redacted>
```

**Comment by MLWALK3R** [comment]
http://termbin.com/0sno

**Comment by MLWALK3R** [comment]
here is /var/log/pihole_debug.log | https://copyd.ovh/1476709677

**Comment by PromoFaux** [comment]
Thanks, odd that termbin is cutting half of it off... I'll take a look at the copyd one (thanks for that!)

**Comment by PromoFaux** [comment]
What are the outputs of:
`head /etc/pihole/gravity.list`
and
`nslookup doublclick.com`

**Comment by MLWALK3R** [comment]
`172.16.0.10 raspberrypi
2a02:c7f:a406:ce01:c511:bc27:1cc8:7ebd raspberrypi
172.16.0.10 pi.hole
2a02:c7f:a406:ce01:c511:bc27:1cc8:7ebd pi.hole
172.16.0.10 0000mps.webpreview.dsl.net
2a02:c7f:a406:ce01:c511:bc27:1cc8:7ebd 0000mps.webpreview.dsl.net
172.16.0.10 0001.2waky.com
2a02:c7f:a406:ce01:c511:bc27:1cc8:7ebd 0001.2waky.com
172.16.0.10 000dom.revenuedirect.com
2a02:c7f:a406:ce01:c511:bc27:1cc8:7ebd 000dom.revenuedirect.com
`

`Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   doublclick.com
Address: 199.59.243.120
`

**Comment by er0l** [comment]
Issue confirmed also in the lighttpd error log:

`(mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/admin/data.php on line 178`

**Comment by PromoFaux** [comment]
Sorry, @MLWALK3R I made a spelling mistake! try `nslookup doubleclick.com` instead

**Comment by MLWALK3R** [comment]
Its kind of weird its started working again **randomly** and I fixed the memory limit thing so we're all good now

https://lel.ovh/1476713133.png

**Comment by PromoFaux** [comment]
Huh. Odd. Did you, by chance, run `pihole -g` between now and then? We had a bit of a bug in the last release that was resolved by running `pihole -g`, which will be fixed in the next update.

We should be pushing out a new update later today that fixes a couple of minor bugs/stability issues

**Comment by MLWALK3R** [comment]
All I did was run the the debug command a few times and fix the mem issue and it started working, really F-ing random xD

**Comment by PromoFaux** [comment]
What did you do to fix the memory issue?

**Comment by MLWALK3R** [comment]
adjusted the php.ini mem size to 1G; after I did that the UI loaded almost instantly.

**Comment by PromoFaux** [comment]
Ah yeah, that'll do it. Big update to how the logs are parsed in the coming weeks, which should improve that no end! Glad its sorted.. reopen this thread if it happens again
