### ISSUE TITLE
Failed install whole new pihole on centos 6

### ISSUE THREAD

**Issue by ookangzheng** [pi-hole/pi-hole#807]
My os is Centos 6 32bit, I tried to install newest 2.9.4 in my system but it lag 

http://i.imgur.com/Wsbht93.png

**Comment by dschaper** [comment]
Try the install a second time.

**Comment by ookangzheng** [comment]
tried again, same prb

**Comment by dschaper** [comment]
What does `yum install procps-ng` show?

**Comment by ookangzheng** [comment]
it show no packages available

**Comment by dschaper** [comment]
Okay, your version of CentOS may not be new enough for support. Will check with the team and see if there are any options.

**Comment by ookangzheng** [comment]
But I used 2.4.12 is ok for me

**Comment by dschaper** [comment]
There was a dependency change, the `procps-ng` package was added and it appears to not be available to CentOS 6. We'll check and let you know.

**Comment by ookangzheng** [comment]
okok

**Comment by Mcat12** [comment]
Looks like it's a name change: http://www.linuxquestions.org/questions/linux-security-4/w-command-not-working-in-my-redhat-6-server-4175552826/#post5419322

**Comment by brontide** [comment]
This should fix the install.

```
    yum list procps-ng &> /dev/null && PROCPS_PKG="procps-ng" || PROCPS_PKG="procps"
    yum list nmap-ncat &> /dev/null && NCAT_PKG="nmap-ncat" || NCAT_PKG="nmap"
    INSTALLER_DEPS=( iproute net-tools $PROCPS_PKG newt git )
    PIHOLE_DEPS=( epel-release bind-utils bc dnsmasq lighttpd lighttpd-fastcgi php-common php-cli php curl unzip wget findutils cronie sudo $NCAT_PKG )
```

But php 5.3 is too old to work with the web interface.  You either need the remi repo which will be a drop in replacement for the stock php or the webtastic repo and change the dependant packages to php70w*

**Comment by brontide** [comment]
#846 has been submitted to development, if included it should allow centos 6 to install pi-hole but the web-ui will not work yet.
