### ISSUE TITLE
Query log broken in 2.9.4

### ISSUE THREAD

**Issue by bobpullen** [pi-hole/pi-hole#808]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)

---

**[BUG | ISSUE] Expected Behaviour:**

Able to view the query log in the admin GUI without error.

**[BUG | ISSUE] Actual Behaviour:**

When attempting to view the query log in the admin GUI and error is displayed:

`DataTables warning: table id=all-queries - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**[BUG | ISSUE] Steps to reproduce:**

Log into the pi.hole admin GUI and click the 'Query log' hyperlink in the left-hand navigation pane.

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/1msh`

**Comment by PromoFaux** [comment]
Interesting.. mine is not! (Classic dev excuse... "Works on my machine!")

Can you tell me if you get an output from navigating to `http://pi.hole/admin/api.php?getAllQueries`

**Comment by bobpullen** [comment]
Nope, white screens. I've just flushed my logs and it's working again so probably related to the PHP memory usage issue that seems to slow displaying of the admin panel in general. Want me to close the issue?

**Comment by PromoFaux** [comment]
Ah yeah, OK That's an ongoing issue... Though the latest web update should have mitigated it somewhat...

What kind of sizes are you logs getting up to?

**Comment by jeepmullet** [comment]
Hey @PromoFaux is there any reason it would be made worse than the 1.4.2 web interface? I'm testing this on a debian based server with 6GB RAM, i7 and SSDon bare metal.  Before, even with 60,000 queries I could open the query log in a few seconds.  Now the front page doesnt show queries over time until leaving it open for a minute or so with only 2000 queries and the query log page takes a couple minutes to log.

What all php memory settings can we play with to try to speed up the loading?

Thank you

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/AdminLTE #169](https://github.com/pi-hole/AdminLTE/issues/169) via [**ZenHub**](https://www.zenhub.com/)
