### ISSUE TITLE
Pi-Hole not blocking ads, Admin Console working

### ISSUE THREAD

**Issue by rubinkazan** [pi-hole/pi-hole#810]
The admin console works fine but ads are not being blocked.
http://termbin.com/ma2s

`############################################################
############################################################
Pi-hole Version: v2.9.4
WebUI Version: v1.4.3.1
lighttpd/1.4.35 (ssl) - a light and fast webserver
PHP 5.6.26-0+deb8u1 (cli) (built: Oct 13 2016 03:03:57) 
############################################################
############################################################
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

############################################################
############################################################
127.0.0.1/8
192.168.2.20/24
::1/128
fe80::65b5:49d0:1fb9:d795/64

IPv4 Gateway check:
192.168.2.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.681/0.730/0.785/0.052 ms

IPv4 Internet check:
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 43.299/44.116/45.403/0.952 ms

No IPv6 Gateway Detected

############################################################
############################################################
This Pi-hole is: PiyoteQueen
###              Hosts              ###
127.0.0.1 localhost.localdomain PiyoteQueen
127.0.1.1 PiyoteQueen

############################################################
############################################################
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 639 www-data    4u  IPv4   9220      0t0  TCP *:http (LISTEN)
lighttpd 639 www-data    5u  IPv6   9221      0t0  TCP *:http (LISTEN)
lighttpd 639 www-data    8u  IPv4  11263      0t0  TCP Piyote:http->192.168.2.21:51809 (FIN_WAIT2)
COMMAND PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 429 dnsmasq    4u  IPv4   8365      0t0  UDP *:domain 
dnsmasq 429 dnsmasq    5u  IPv4   8366      0t0  TCP *:domain (LISTEN)
dnsmasq 429 dnsmasq    6u  IPv6   8367      0t0  UDP *:domain 
dnsmasq 429 dnsmasq    7u  IPv6   8368      0t0  TCP *:domain (LISTEN)

#######################################
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Tue 2016-10-18 21:10:02 UTC; 7min ago
  Process: 492 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 639 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─639 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─805 /usr/bin/php-cgi
           ├─864 /usr/bin/php-cgi
           ├─865 /usr/bin/php-cgi
           ├─866 /usr/bin/php-cgi
           └─867 /usr/bin/php-cgi

Oct 18 21:10:02 PiyoteQueen lighttpd[492]: Syntax OK
Oct 18 21:10:02 PiyoteQueen systemd[1]: Started Lighttpd Daemon.
Oct 18 21:10:55 PiyoteQueen systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Tue 2016-10-18 21:10:00 UTC; 7min ago
  Process: 431 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 411 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 377 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 429 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─429 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

Oct 18 21:09:55 PiyoteQueen systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Oct 18 21:09:56 PiyoteQueen dnsmasq[377]: dnsmasq: syntax check OK.
Oct 18 21:10:00 PiyoteQueen systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
Oct 18 21:10:55 PiyoteQueen systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

############################################################
############################################################
Resolution of doubleclick.com from Pi-hole:

; <<>> DiG 9.9.5-9+deb8u7-Raspbian <<>> doubleclick.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7650
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	299	IN	A	216.58.223.14

;; Query time: 219 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 18 21:17:26 UTC 2016
;; MSG SIZE  rcvd: 60

Resolution of doubleclick.com from 8.8.8.8:

; <<>> DiG 9.9.5-9+deb8u7-Raspbian <<>> doubleclick.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9507
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	299	IN	A	216.58.223.14

;; Query time: 213 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Oct 18 21:17:26 UTC 2016
;; MSG SIZE  rcvd: 60

Pi-hole dnsmasq specific records lookups
Cache Size:
"10000"
Insertions count:
"358"
Evictions count:
"0"
Misses count:
"153"
Hits count:
"16"
Auth count:
"0"
Upstream Servers:
"8.8.4.4#53 95 3" "8.8.8.8#53 77 0"

#######################################
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
#######################################

#######################################
#######################################
conf-dir=/etc/dnsmasq.d

#######################################
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
#######################################
2 /etc/pihole/gravity.list

#######################################
#######################################
raw.githubusercontent.com
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net
ransomwaretracker.abuse.ch

#######################################
#######################################

#######################################
#######################################
No adlists.list file found... using adlists.default!
#######################################
#######################################
Oct 18 21:17:27 dnsmasq[429]: query[TXT] evictions.bind from 127.0.0.1
Oct 18 21:17:27 dnsmasq[429]: config evictions.bind is <TXT>
Oct 18 21:17:27 dnsmasq[429]: query[TXT] misses.bind from 127.0.0.1
Oct 18 21:17:27 dnsmasq[429]: config misses.bind is <TXT>
Oct 18 21:17:27 dnsmasq[429]: query[TXT] hits.bind from 127.0.0.1
Oct 18 21:17:27 dnsmasq[429]: config hits.bind is <TXT>
Oct 18 21:17:27 dnsmasq[429]: query[TXT] auth.bind from 127.0.0.1
Oct 18 21:17:27 dnsmasq[429]: config auth.bind is <TXT>
Oct 18 21:17:27 dnsmasq[429]: query[TXT] servers.bind from 127.0.0.1
Oct 18 21:17:27 dnsmasq[429]: config servers.bind is <TXT>`

**Comment by dschaper** [comment]
Try running `pihole -g` and then do a new `pihole -d` and run a few client checks when prompted in `pihole -d`.

**Comment by rubinkazan** [comment]
http://termbin.com/qias
############################################################
##########           Installed Versions           ##########
############################################################
Pi-hole Version: v2.9.4
WebUI Version: v1.4.3.1
lighttpd/1.4.35 (ssl) - a light and fast webserver
PHP 5.6.26-0+deb8u1 (cli) (built: Oct 13 2016 03:03:57) 
############################################################
########          Installed OS Distribution        #########
############################################################
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

############################################################
########           IP Address Information          #########
############################################################
127.0.0.1/8
192.168.2.20/24
::1/128
fe80::65b5:49d0:1fb9:d795/64

IPv4 Gateway check:
192.168.2.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.703/3.432/8.848/3.829 ms

IPv4 Internet check:
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 44.077/44.150/44.252/0.186 ms

No IPv6 Gateway Detected

############################################################
########            Hostname Information           #########
############################################################
This Pi-hole is: PiyoteQueen
###              Hosts              ###
127.0.0.1 localhost.localdomain PiyoteQueen
127.0.1.1 PiyoteQueen

############################################################
########           Open Port Information           #########
############################################################
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 639 www-data    4u  IPv4   9220      0t0  TCP *:http (LISTEN)
lighttpd 639 www-data    5u  IPv6   9221      0t0  TCP *:http (LISTEN)
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 2586 dnsmasq    4u  IPv4  13638      0t0  UDP *:domain 
dnsmasq 2586 dnsmasq    5u  IPv4  13639      0t0  TCP *:domain (LISTEN)
dnsmasq 2586 dnsmasq    6u  IPv6  13640      0t0  UDP *:domain 
dnsmasq 2586 dnsmasq    7u  IPv6  13641      0t0  TCP *:domain (LISTEN)

#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Tue 2016-10-18 21:10:02 UTC; 19min ago
 Main PID: 639 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─639 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─805 /usr/bin/php-cgi
           ├─864 /usr/bin/php-cgi
           ├─865 /usr/bin/php-cgi
           ├─866 /usr/bin/php-cgi
           └─867 /usr/bin/php-cgi

Oct 18 21:10:02 PiyoteQueen lighttpd[492]: Syntax OK
Oct 18 21:10:02 PiyoteQueen systemd[1]: Started Lighttpd Daemon.
Oct 18 21:10:55 PiyoteQueen systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Tue 2016-10-18 21:29:15 UTC; 13s ago
  Process: 2541 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 2587 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 2579 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 2576 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 2586 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─2586 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

Oct 18 21:29:14 PiyoteQueen dnsmasq[2576]: dnsmasq: syntax check OK.
Oct 18 21:29:15 PiyoteQueen systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

############################################################
############      Resolver Functions Check      ############
############################################################
Resolution of doubleclick.com from Pi-hole:

; <<>> DiG 9.9.5-9+deb8u7-Raspbian <<>> doubleclick.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14514
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	300	IN	A	192.168.2.20

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 18 21:29:28 UTC 2016
;; MSG SIZE  rcvd: 60

Resolution of doubleclick.com from 8.8.8.8:

; <<>> DiG 9.9.5-9+deb8u7-Raspbian <<>> doubleclick.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18043
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	299	IN	A	216.58.223.14

;; Query time: 211 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Oct 18 21:29:28 UTC 2016
;; MSG SIZE  rcvd: 60

Pi-hole dnsmasq specific records lookups
Cache Size:
"10000"
Insertions count:
"0"
Evictions count:
"0"
Misses count:
"0"
Hits count:
"5"
Auth count:
"0"
Upstream Servers:
"8.8.4.4#53 0 0" "8.8.8.8#53 0 0"

#######################################
############ lighttpd.conf ############
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
######### lighttpd error.log ##########
#######################################


#######################################
############### Dnsmasq ###############
#######################################
conf-dir=/etc/dnsmasq.d

#######################################
########### 01-pihole.conf ############
#######################################
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async

#######################################
############ gravity.list #############
#######################################
101003 /etc/pihole/gravity.list

#######################################
############## Whitelist ##############
#######################################
raw.githubusercontent.com
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net
ransomwaretracker.abuse.ch

#######################################
############## Blacklist ##############
#######################################

#######################################
############ adlists.list #############
#######################################
No adlists.list file found... using adlists.default!
#######################################
############# pihole.log ##############
#######################################
Oct 18 21:29:29 dnsmasq[2586]: query[TXT] evictions.bind from 127.0.0.1
Oct 18 21:29:29 dnsmasq[2586]: config evictions.bind is <TXT>
Oct 18 21:29:29 dnsmasq[2586]: query[TXT] misses.bind from 127.0.0.1
Oct 18 21:29:29 dnsmasq[2586]: config misses.bind is <TXT>
Oct 18 21:29:29 dnsmasq[2586]: query[TXT] hits.bind from 127.0.0.1
Oct 18 21:29:29 dnsmasq[2586]: config hits.bind is <TXT>
Oct 18 21:29:29 dnsmasq[2586]: query[TXT] auth.bind from 127.0.0.1
Oct 18 21:29:29 dnsmasq[2586]: config auth.bind is <TXT>
Oct 18 21:29:29 dnsmasq[2586]: query[TXT] servers.bind from 127.0.0.1
Oct 18 21:29:29 dnsmasq[2586]: config servers.bind is <TXT>
Oct 18 21:29:40 dnsmasq[2586]: query[A] www.belkin.com from 192.168.2.1
Oct 18 21:29:40 dnsmasq[2586]: forwarded www.belkin.com to 8.8.4.4
Oct 18 21:29:40 dnsmasq[2586]: forwarded www.belkin.com to 8.8.8.8
Oct 18 21:29:41 dnsmasq[2586]: reply www.belkin.com is <CNAME>
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.227
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.200
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.86
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.21
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.64
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.68
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.226
Oct 18 21:29:41 dnsmasq[2586]: reply d3gjecg2uu2eaq.cloudfront.net is 52.85.47.85
Oct 18 21:29:55 dnsmasq[2586]: query[A] star-mini.c10r.facebook.com from 192.168.2.1
Oct 18 21:29:55 dnsmasq[2586]: forwarded star-mini.c10r.facebook.com to 8.8.4.4
Oct 18 21:29:55 dnsmasq[2586]: reply star-mini.c10r.facebook.com is 31.13.92.36

**Comment by dschaper** [comment]
Okay, that looks like it's blocking now. You may need to wait a few minutes for your clients cache to timeout, but if it's not working in about 15 minutes or so we'll take another look.

**Comment by rubinkazan** [comment]
Alright thanks, tested on my laptop using http://ads-blocker.com/testing/ and it has blocked all the advertisements, same applies to my mobile phone and tablet. Problem solved! appreciate the help
