### ISSUE TITLE
Request: Add option to create DNS record in GUI

### ISSUE THREAD

**Issue by wioxjk** [pi-hole/pi-hole#812]
Because the Pi is now the DNS-server for the local network, it should be possible to add my own records.

For example, I want to add one of my homeservers so it would resolve to a local IP address. Or I want to override the google.com record to resolve to another IP address.

I hope that I was clear enough

**Comment by mrjack711** [comment]
I would also love to see this as a feature

**Comment by PromoFaux** [comment]
A good starting point for this would be to add them into `/etc/hosts`
e.g on my test pi I have the following:
```
pi@raspberrypi:~ $ cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi
192.168.1.1    device1 device1.local
192.1681.2     device2 device2.local
pi@raspberrypi:~ $
```

**Comment by wioxjk** [comment]
@PromoFaux 
Would also be awesome if the option to add my own SRV records also. Not just a A record :)
The hosts file is not suitable for it thou, but it works great with just A records.

**Comment by jacobsalmela** [comment]
Votable feature request added [here](https://discourse.pi-hole.net/t/add-option-to-create-dns-records-in-gui/564).
