### ISSUE TITLE
Update Web Interface manually...

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#815]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be _replicated_
- [ ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
## 

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

Reading this https://pi-hole.net/faq/is-there-a-easy-way-to-update-the-web-interface/ and tried to execute the script, doesn't work.

Connected via VNC and tried to locate the file "updateDashboard.sh" which doesn't exist at all (at least not in the mentioned folder).

Currently there is a bug for the Web Interface only which can be seen here https://github.com/pi-hole/AdminLTE/wiki/Changelog#1431---2016-10-18:
[FIX] Revert pull #154 , as it is causing loading issues #171

Problem is, when i tried via SSH to update Pihole (pihole -up) it says it is already updated but there is an update for the Web Interface, there is no command to update Web Interface only.

So currently it refuses to update the Pihole Web Interface with command "pihole -up".

**Comment by Mcat12** [comment]
Please post a log of the update command (`pihole -up`).

**Comment by Mcat12** [comment]
I have also updated your issue with the handy issue template, which we request you fill in.

**Comment by nomoreads** [comment]
Here you go, pihole -up log:

::: Elevating to root with sudo
::: Checking for updates...
::: Pi-hole version is v2.9.4 (Latest version is v2.9.4)
::: Web Admin version is v1.4.3 (Latest version is v1.4.3.1)
:::
::: Pi-hole Base files are already up to date! Version: v2.9.4
::: No need to update!
:::
::: An Update is available for the Web Admin!
:::
::: Fetching latest changes from GitHub...
From https://github.com/pi-hole/AdminLTE
 * branch            master     -> FETCH_HEAD
Already up-to-date.
:::
::: Pi-hole Web Admin has been updated to v1.4.3
::: See https://changes.pi-hole.net for details


pihole -v log:

::: Elevating to root with sudo
::: Pi-hole version is v2.9.4 (Latest version is v2.9.4)
::: Web-Admin version is v1.4.3 (Latest version is v1.4.3.1)

Weird that it does not automatically update the Web Interface, even while it knows there is an update.
A bug if you ask me...

**Comment by nomoreads** [comment]
And this post is obsolete and/or contains wrong information https://pi-hole.net/faq/is-there-a-easy-way-to-update-the-web-interface/
The file does not exist (in that folder).

**Comment by Mcat12** [comment]
I think #809 fixes this, but it is yet to be released.

**Comment by PromoFaux** [comment]
Yeah, #809 has a fix for this!

in the mean time
```
cd /var/www/html/admin
sudo git reset --hard
sudo git checkout master
sudo git pull
```

will update it!

**Comment by Mcat12** [comment]
Update has been released
