### ISSUE TITLE
Pihole updates overwrites cron settings

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#820]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be _replicated_
- [ ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [x] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[FEATURE REQUEST | QUESTION | OTHER]:**

BUG:

As described in a post here (how to) https://pi-hole.net/suggestions/nightly-pihole-command-initiated-by-cron/

Editing this file: /etc/cron.d/pihole

For example this line:

59 1 \* \* 7 root /usr/local/bin/pihole updateGravity

I changed it to:

45 6 \* \* \* root /usr/local/bin/pihole updateGravity // runs the update daily instead of once a week

With a new update (pihole -up) the file (probably all files) /etc/cron.d/pihole will be overwritten and loses custom edits.

**[BUG | ISSUE] Expected Behaviour:**

BUG: Expected behaviour is that it respects the edited file and not overwrite it

**[BUG | ISSUE] Actual Behaviour:**

Actual behaviour is that it does overwrite custom edits

**[BUG | ISSUE] Steps to reproduce:**

Editing this file: /etc/cron.d/pihole

For example this line:

59 1 \* \* 7 root /usr/local/bin/pihole updateGravity

I changed it to:

45 6 \* \* \* root /usr/local/bin/pihole updateGravity

Check the file when a new pi-hole update has been released and downloaded, it has been changed (overwritten).

**Comment by wioxjk** [comment]
I dont consider this a bug.
But if you really want to run that script on a hourly basis, just put this file into /etc/cron.hourly/

```
#!/bin/bash
/usr/local/bin/pihole updateGravity
```

**Comment by dschaper** [comment]
We don't want it to run hourly. I should run daily at the very most frequently. (And should be a systemD timer, but that's lower on the priority list.)

**Comment by PromoFaux** [comment]
@nomoreads Please do not delete the issue template. It is there for a reason! Read it carefully and fill it out! Please update your OP to follow the templace. Thanks!!

**Comment by nomoreads** [comment]
So you don't consider it a bug when a user edits and file and it gets overwritten by every single pihole update?
And please read carefully.... where did i said i want to run it hourly???

I said daily... instead of once a week...

**Comment by dschaper** [comment]
> But if you really want to run that script on a hourly basis, just put this file into /etc/cron.hourly/

Abuse the dev's and get closed out. Thanks!

**Comment by nomoreads** [comment]
Please read carefully... i said DAILY... not HOURLY

**Comment by nomoreads** [comment]
All i want to achieve is that it updates from lists (adblocking sources) every single day, so it checks daily sites like http://mirror1.malwaredomains.com/files/justdomains

Not want to hammer the pi-hole server at all...

**Comment by PromoFaux** [comment]
@nomoreads chill please. @dschaper was replying to @wioxjk .

ANYWAY. If we could all get along please, no need for capital letters and general asshattery. 

As asked before, please update your OP and follow the issue template!

In answer to your question, create another file in `/etc/cron.d/custom` (or something like that) and add the daily update line into that. We wont touch that on update, because we don't know it exists. Don't forget to reload `cron`! 

Generally custom edits to base pi-hole files are not supported, which is why we put our files in `.d` folders, so that they can be separated from user customisations if needs be.

**Comment by nomoreads** [comment]
@PromoFaux 

Ok you can read here (i'm user "pipi") https://pi-hole.net/suggestions/nightly-pihole-command-initiated-by-cron/ that i was told by Dan Schaper to do it that way.

Change 59 1 * * 7 root /usr/local/bin/pihole updateGravity

to

45 6 * * * root /usr/local/bin/pihole updateGravity

**Comment by nomoreads** [comment]
@PromoFaux what do you ask me to edit by the way?

**Comment by PromoFaux** [comment]
OP = Original Post.

**Comment by nomoreads** [comment]
@PromoFaux i understand OP, but what exactly do you want me to edit?

**Comment by PromoFaux** [comment]
For all the accusations of telling people they can't read.... you sure as hell seem to be struggling.

**Comment by nomoreads** [comment]
@PromoFaux That's why i'm using CAPITAL letters to mark things for attention ;) Please note that i am not an native English speaker. Sorry.

**Comment by PromoFaux** [comment]
Right. Here's what we're going to do. I'm going to delete most of the comments in this thread. 

You're going to look at the OP and follow the instructions in the template carefully. Then we're going to get back to problem solving and being nice to each other!!

I will unlock this topic again once the issue template has been filled out correctly.

**Comment by nomoreads** [comment]
Ok OP has been edited as requested.

**Comment by PromoFaux** [comment]
Hooray, we got there!

So, to continue the discussion....

Solution by @wioxjk would work well for you (although, in `cron.daily` not `cron.hourly`!)

Or you could try adding it to your `crontab` (Lots of examples in [this guide](http://kvz.io/blog/2007/07/29/schedule-tasks-on-linux-using-crontab/))

As for issue of whether or not this is a bug, it's a difficult one. Ideally we don't want users editing any of the existing files, so that we can continue to overwrite the default files if we need to change anything. This is possibly a change of position from when we originally replied on the other thread back in April, and we have been putting things into place recently that allow users to make customisations (e.g setupVars.conf, adlists.default/adlists.list etc)

**Comment by nomoreads** [comment]
I'll check that out, thanks.
And no i don't want to use it hourly and hammer the pihole server, all i want is to run a daily update from the source lists.

So in this case Dan Schaper teached me a wrong thing https://pi-hole.net/suggestions/nightly-pihole-command-initiated-by-cron/

**Comment by dschaper** [comment]
Please point out exactly what I taught you that was wrong, I'd really like to know where I mislead you. I believe all I pointed out was how to use gksu leafpad? Perhaps you have me confused with someone else in that thread?

**Comment by nomoreads** [comment]
@dschaper  No that thread is about changing weekly update to daily update and my point was that i did not get that working and my issue was solved with "gksudo leafpad", and your explain how to do it (edit the /usr/local/bin/pihole updateGravity file).

I guess you are one of the admins/creators of pihole, what's the point of explaining how to edit a file that gets overwritten by every pihole update?

**Comment by PromoFaux** [comment]
@nomoreads Because of this:

>his is possibly a change of position from when we originally replied on the other thread back in April,

**Comment by dschaper** [comment]
I apologize if you feel I lead you astray. We now will have warnings on files that are subject to change. https://github.com/pi-hole/pi-hole/pull/822/files Anything with the name pihole or pihole.conf is subject to change or upgrade at any time.

**Comment by dschaper** [comment]
My intent was to explain how to use a desktop tool to edit a file that was under root control. That's all. There was no thought given to which file you were editing or why you were editing it. I will make sure not to do that in the future.

**Comment by nomoreads** [comment]
@dschaper Well you helped me out how to unlock a file, thanks for that.
But the whole explain was in context of changing weekly update to daily update and editing that particular file, which i now understand makes no sense as it will be overwritten anyway.

**Comment by nomoreads** [comment]
So now the question is... or remains... how do i properly change a file to daily update gravity.list to get automatic daily updates for blocked domains????

**Comment by PromoFaux** [comment]
I refer you to my comment from 40 mins ago! :) 

https://github.com/pi-hole/pi-hole/issues/820#issuecomment-255074044

**Comment by nomoreads** [comment]
@PromoFaux Oh sorry man, i get lost in this thread lol

**Comment by dschaper** [comment]
Fixed
