### ISSUE TITLE
Ubuntu 16.04 dosnt load /etc/sudoers.d/* by default

### ISSUE THREAD

**Issue by tuplink** [pi-hole/pi-hole#824]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ x] The issue I am reporting can be *replicated*
- [ x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ x] 5
---
**[FEATURE REQUEST | QUESTION | OTHER]:**
ISSUE
solution edit /etc/sudoers and uncomment 
includedir /etc/sudoers.d

**Comment by dschaper** [comment]
Can you post this on our Discourse as a FAQ so that others will have the info for them?

**Comment by tuplink** [comment]
this didnt fix it
