### ISSUE TITLE
calling home hosts

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#825]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [X] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[FEATURE REQUEST | QUESTION | OTHER]:**

any way to exclude hosts that call home from log files?

**Comment by Mcat12** [comment]
Is the reason you want to remove these queries from the log for performance reasons, not to see them in the web interface, or something else?

**Comment by xxcriticxx** [comment]
not to see them in web interface

all i have in my top domains is (microsoft, amazon, apple, samsung, office365, and nest in my case) all about 7000 connection each

**Comment by Mcat12** [comment]
I would setup a cronjob to remove all lines matching the domains you don't want in there.

**Comment by xxcriticxx** [comment]
can i please get example?

**Comment by Mcat12** [comment]
http://stackoverflow.com/a/5413132/3267834

**Comment by dschaper** [comment]
Not a bug to fix.
