### ISSUE TITLE
configureFirewall issue on lxd container install

### ISSUE THREAD

**Issue by brontide** [pi-hole/pi-hole#827]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [X] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

[LXD is a system for running operating systems as containers.](https://linuxcontainers.org/lxd/introduction/)  Similar to VMs but a lot less friction for linux-on-linux.

**[ ISSUE] Expected Behaviour:**

On a fresh Ubuntu 16.04 in LXD.
- `apt update`
- `apt upgrade`
- `curl -L https://install.pi-hole.net | bash` ( taking all defaults )

I would expect that the service would be running and functional

**[ ISSUE] Actual Behaviour:**

Script appears to complete with a warning but setupVars.conf was never created so most of the other steps failed.

**cropped output from curl|bash**

````
::: Installing latest Cron script... done!
::: Configuring iptables for httpd and dnsmasq..
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-38-generic/modules.dep.bin'
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.4.0-38-generic
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
::: Restarting services...
:::
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
::: done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:
:::     192.168.111.138
:::     
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log
::: View the web interface at http://pi.hole/admin or http://192.168.111.138/admin
````

***end of install.log***

````
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
::: Configuring iptables for httpd and dnsmasq..
````

**[ ISSUE] Steps to reproduce:**

- install lxd on ubuntu
- `lxc launch ubuntu:16.04 pihole`
- `lxc exec pihole -- bash`
- Install pihole

**fix**

Based on the errors I'm presuming there is an error with the logic of iptables setup that is causing the basic-install.sh to bomb so I commented it out.

````
--- basic-install.sh.bak	2016-10-20 18:28:23.962835975 +0000
+++ basic-install.sh	2016-10-20 18:29:34.754837316 +0000
@@ -820,7 +820,7 @@
     configureSelinux
     installPiholeWeb
     installCron
-    configureFirewall
+    #configureFirewall
     finalExports
     runGravity
 }
@@ -838,7 +838,7 @@
     configureSelinux
     installPiholeWeb
     installCron
-    configureFirewall
+    #configureFirewall
     runGravity
 }
````

and it runs to completion ( see install.log )

````
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Existing pihole directory found
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting ransomwaretracker.abuse.ch list... List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 125440 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 101352 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 9 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 7 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...
````

I will dig into the code later to see if I can rework the function to either not take out the whole script or provide some useful debugging.

**Comment by brontide** [comment]
Due to LXD containers not having permission for some kernel operations the iptables functions fail and the `set -e` causes the whole script to stop.

But more than that this logic is fundamentally broken since running this script multiple times will result in a growing output list.  It doesn't check if the firewall is up and if it were this script does not guarantee that packets will be received since `-A` dumps the rule at the end  rather than a `-C` existence check then `-I 1` insert at first position if it doesn't already exist.

**Comment by dschaper** [comment]
`set -e` is intentional for reasons like this, otherwise the script would progress without the user knowing that there was a failure in a major function of the script. I'm not sure how we can progress with the install script detecting that it's being installed inside a virtualized environment, with no access to necessary kernel operations. Would you be open to creating a fork of this project for LXC/D containers as we have a fork that is for Docker installations?

**Comment by dschaper** [comment]
There is a bug in `set -e`'s implementation in the fact that it should drop out of the entire script (and I need to write that trap) instead of just dropping out of that function and continuing the installer. It should just die with an INT function that states the install is incompatible with the current state of the system.

**Comment by brontide** [comment]
I don't think a specific LXD branch would be necessary since if the iptables was smarter it would work.  Let me check with my oracle linux/centos 6 boxes for error codes on iptables -C and the like.  

WIth `set -e` can I capture non-zero return codes or will it bomb the script?

Psuedocode

```
if `iptables -L OUTPUT` returns non-zero {  # iptables is not working
    echo "::: iptables setup failed, make sure ports 53/udp, 53/tcp, and 80/tcp are open
} else {
    for rule in "-p udp --dport 53", "-p tcp --dport 53", "-p tcp --dport 80" do {
        # if rule not in chain insert it at the beginning
        if `iptables -C output $rule -j ACCEPT` is non-zero then iptables -I output 1 $rule -j ACCEPT
    }
}
```

for the time being what about a `--nofirewalls` flag that skips that step?  Should be rather trivial to create and could be useful in debugging issues on new systems in general.

**Comment by dschaper** [comment]
`--nofirewalls` flag could work, and `set -e` is kind of a odd set up at the moment, we use named pipes in some of our functions and that will cause the script to not fully crash out, but to instead just break out of that particular function. In theory you could write a trap that would monitor for something like `exit 24` and when a function exits with that retVal then you write your trap to catch it and do what ever process you'd like it to. It should also allow for INT to be trapped separately for a cleanup function that I have yet to write. But putting that into practice is an exercise that's a bit more difficult than the manual says it should be.

**Comment by dschaper** [comment]
By default most OSes come without IPTables enabled. It's the RHEL/CentOS security oriented releases that have things like AppArmour or SELinux that muck up the waters. We have a great contributor that is helping with the RHEL / CentOS that we can ping if need be...

**Comment by brontide** [comment]
SElinux is the devil.  You can always check for it with a `getenforce`.  If it return `enforcing` then SElinux might muck things up, maybe do a test at the top and throw a warning?

I've got hundreds of centos boxen and I believe with the right flags I can test it in LXD as well.  Even under RHEL/CentOS the logic will be wied when run multiple times since it will just keep `-A` appending rules to the chain, but for the moment I will implement a `--nofirewalls` patch.

**Comment by hvanderlaan** [comment]
Sorry, but i can't reproduce this issue.

host: ubuntu 16.04 LTS
lxd: 2.0.5

```
$ lxc launch images:ubuntu/xenial c1
$ lxc exec c1 -- bash
root@c1:~# apt-get install curl
root@c1:~# curl -skL https://install.pi-hole.net | bash
  default all

curl -skL https://install.pi-hole.net | bash
:::
::: You are root.
::: Verifying free disk space...
:::
::: apt-get update has not been run today. Running now... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 13 updates available for your system!
::: We recommend you run 'apt-get upgrade' after installing Pi-Hole! 
:::
:::    Checking for apt-utils... installed!
:::    Checking for whiptail... installed!
:::    Checking for git... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for dnsutils... installed!
:::    Checking for bc... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for lighttpd... installed!
:::    Checking for php-common... installed!
:::    Checking for php-cgi... installed!
:::    Checking for curl... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::    Checking for sudo... installed!
:::    Checking for netcat... installed!
:::    Checking for cron... installed!
:::    Checking for iproute2... installed!
:::
::: Checking for existing repository...
:::    Checking /etc/.pihole is a repo...:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole... done!
:::
::: Checking for existing repository...
:::    Checking /var/www/html/admin is a repo...:::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin... done!
:::
::: Stopping dnsmasq service... [/]  
 done.
:::
::: Stopping lighttpd service... done.
::: Using interface: eth0
:::
::: Setting IP to 172.16.129.195/16.  You may need to restart after the install is complete.
:::
::: IPv4 address: 172.16.129.195/16
::: IPv6 address: 
::: Using Google DNS servers.
::: Checking if user 'pihole' exists...
::: User 'pihole' doesn't exist. Creating...
:::
::: Installing scripts to /opt/pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page... done!
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
::: No firewall detected.. skipping firewall configuration.
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Existing pihole directory found
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting ransomwaretracker.abuse.ch list... List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 124843 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 100766 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 9 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 7 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...::: Restarting services...
:::
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
::: done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:
:::     172.16.129.195
:::     
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log
::: View the web interface at http://pi.hole/admin or http://172.16.129.195/admin
root@c1:~#
```

**Comment by dschaper** [comment]
@hvanderlaan Can you confirm the status of your firewall in the container so we can check if it applied or if the script just passed that section without properly warning you?

**Comment by hvanderlaan** [comment]
@dschaper by default the official ubuntu lxd image does not have iptables installed. The host will handle the firewall rules. These rules are set by lxd-bridge.

This is the reason I conclude that @brontide is not using the official ubuntu lxd image.

please try:
```
lxc image copu remote:ubuntu/xenial local: --alias=ubuntu-lts
lxc launch ubuntu-lts pihole
lxc exec pihole -- bash
# apt-get install curl
# curl -skL https://install.pi-hole.net | bash
```

**Comment by brontide** [comment]
> ::: No firewall detected.. skipping firewall configuration.

I am using the ubuntu:16.04 image and not the images:ubuntu/xenial.  It looks like that version does not come with iptables binaries installed and therefore skips the attempted configuration.

Checking the [documentation I will quote](https://help.ubuntu.com/lts/serverguide/lxd.html)

> images: this is a default-installed alias for images.linuxcontainers.org. This is serves classical lxc images built using the same images which the LXC 'download' template uses. This includes various distributions and minimal custom-made Ubuntu images. This is not the recommended server for Ubuntu images.

So it's a different minimal ubuntu image you are using and not the officials which come from the ubuntu: repository.  Either way it still does not address the underlying issue that function should fail more gracefully in cases where iptables is not

**Comment by brontide** [comment]
Confirmed.  The unofficial images:ubuntu/xenial rootfs does not ship with iptables which bypases the issue.

```
ewarnke@eric-cb:~/worklog$ lxc launch images:ubuntu/xenial
Creating loving-coyote
Retrieving image: 100%
Starting loving-coyote
ewarnke@eric-cb:~/worklog$ lxc exec loving-coyote -- bash
root@loving-coyote:~# ls -al /sbin/iptables
ls: cannot access '/sbin/iptables': No such file or directory
root@loving-coyote:~# exit
exit
ewarnke@eric-cb:~/worklog$ lxc launch ubuntu:lts
Creating deciding-caiman
Retrieving image: 100%
Starting deciding-caiman
ewarnke@eric-cb:~/worklog$ lxc exec deciding-caiman -- bash
root@deciding-caiman:~# ls -al /sbin/iptables
lrwxrwxrwx 1 root root 13 Feb 19  2016 /sbin/iptables -> xtables-multi

```

**Comment by brontide** [comment]
Before anyone tries to reproduce it, I can not get it to fail under 2 other LXD hosts with NAT networking.  Investigating if it's NAT or bridged networking that triggers the permission issue.

**Comment by brontide** [comment]
I have completed a first pass iptables cleanup in #828 after replicating the host scenario.

You can end up in this situation when you attempt to run iptables on the guests BEFORE iptables modules are autoloaded on the host.  This also fixes the problem of duplicate rules when pihole is run in update or reconfigure mode.

**Comment by brontide** [comment]
I'm closing this since I will be looking to remove ( or improve ) iptables support with a new pull at some point.
