### ISSUE TITLE
Migrate away from DHCPCD5 on non-Berry platforms.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#830]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [x] 10 (very familiar)

---

**[FEATURE REQUEST]:**

Setting static IP's via DHCPCD5 on non-Rasbperry platforms is problematic. We should be stetting static addresses via `/etc/network/interfaces.d` or `/etc/network/interfaces`.

Also should take into consideration the situation where static reservations are set for Pi-hole installs and not touch the networking at all, let the users own DHCP server handle the static lease/reserved IP assignment.

**Comment by dschaper** [comment]
Platform and default manual static configuration software
- Raspbian Jessie: DHCPCD configuration controlled static IP.
- Raspbian Wheezy: EOL - Suggested removal from supported platforms

**Comment by Fedora-Core** [comment]
This works for me,
on a stock Raspian Jessie,
and on a stock Debian Jessie,
(no reservations in DHCP server required)
 =>

[on GitHub : /etc/network/interfaces](https://github.com/Fedora-Core/Pi-hole-adblock-multiple-IP-addresses)

Greetings, F.C.

**Comment by dschaper** [comment]
Thanks F.C., trying to compile a list of OSes and what they use for stock addressing, either DHCP acquired or through static addressing.

**Comment by dschaper** [comment]
High Priority. Affects just about any Debian install that isn't Raspbian, and kills other installs dead pretty quickly. Thanks to the RPF for this abomination of a system, it's appreciated.

**Comment by brontide** [comment]
Why not make user responsible for static IP on non-Pi platforms?

**Comment by dschaper** [comment]
Part of what we do is to handle everything in the background for the less experienced user. Just buy a Pi, burn Raspbian and run one command to `curl` and they have an ad-blocker. We could look at a more advanced install option with a flag for experienced users that bypasses some holding of hands.

**Comment by dschaper** [comment]
Roll into #629

**Comment by HarvsG** [comment]
So this issue [moved onto the forums](https://discourse.pi-hole.net/t/work-with-dhcp-address-instead-of-static-ip-address-configuration/561) and is marked as solved. However I cannot get it to work. I am trying to create a PiHole on a digital ocean server which can be dropped around the globe. The solution to the broken networking is to use `pihole -r` to reset the static IP to the new DHCP configuration. However since networking is broken by this `pihole -r` hangs, and even if it didn't I think it would just retrieve the incorrect, old, configuration. 

Also, since the networking is broken, you can't do any of this over SSH
