### ISSUE TITLE
Failed update Pi-hole from version 2.9.2 to version 2.9.4 and Web-Admin from version 1.4.2 to version 1.4.3.1

### ISSUE THREAD

**Issue by M1chael** [pi-hole/pi-hole#833]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [X] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:**
`pihole -up` should update Pi-hole and Web Admin to the latest versions.

**[BUG | ISSUE] Actual Behaviour:**
`pihole -up` not update Pi-hole and Web Admin:

```
::: Pi-hole has been updated to version v2.9.4
::: Web Admin has been updated to version v1.4.3.1
:::
::: See https://changes.pi-hole.net for details
pi@raspberrypi ~ $ pihole -v
::: Pi-hole version is V2.9.2 (Latest version is v2.9.4)
::: Web-Admin version is v1.4.2 (Latest version is v1.4.3.1)
```

**[BUG | ISSUE] Steps to reproduce:**
- `pihole -up`
- select any suggested option
- `pihole -v`

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/nq08`

**Comment by PromoFaux** [comment]
Hi there, there is a known bug in `pihole -up` which will be fixed in the next release. (Fixed in pull #814)

In the mean time, you can manually update the Web-Admin by:

```
cd /var/www/html/admin
sudo git checkout master
sudo git pull
```

**Comment by M1chael** [comment]
@PromoFaux, thanks for that! What about Pi-hole itself? Is there any way to update it?

**Comment by PromoFaux** [comment]
The update command should would for the pi-hole files, I think the bug just affects the web...

**Comment by M1chael** [comment]
Unfortunately it doesn't:
```
pi@raspberrypi ~ $ pihole -up
::: Checking for updates...
::: Pi-hole version is V2.9.2 (Latest version is v2.9.4a)
::: Web Admin version is v1.4.3.1a (Latest version is v1.4.3.1a)
:::
::: An update is available for  Pi-Hole!
::: Fetching latest changes from GitHub...
[sudo] password for pi: 
From https://github.com/pi-hole/pi-hole
 * branch            master     -> FETCH_HEAD
Already up-to-date.
:::
::: You are root.
::: Update option selected.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for apt-utils... installed!
:::    Checking for whiptail... installed!
:::    Checking for git... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for dnsutils... installed!
:::    Checking for bc... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for lighttpd... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
:::    Checking for curl... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::    Checking for sudo... installed!
:::    Checking for netcat... installed!
:::    Checking for cron... installed!
:::    Checking for iproute2...:::
::: Pi-hole has been updated to version v2.9.4a
:::
::: See https://changes.pi-hole.net for details
pi@raspberrypi ~ $ pihole -v
::: Pi-hole version is V2.9.2 (Latest version is v2.9.4a)
::: Web-Admin version is v1.4.3.1a (Latest version is v1.4.3.1a)
```

**Comment by PromoFaux** [comment]
Hmm. OK. I'll take a look into it. In the mean time:
```
cd /etc/.pihole
sudo git checkout master
sudo git pull
```

**Comment by M1chael** [comment]
@PromoFaux, thx again!

**Comment by M1chael** [comment]
Problem still here:
```
::: Pi-hole has been updated to version v2.9.5
::: Web Admin has been updated to version v1.4.4.2
:::
::: See https://changes.pi-hole.net for details
pi@raspberrypi ~ $ pihole -v
::: Pi-hole version is v2.9.4a (Latest version is v2.9.5)
::: Web-Admin version is v1.4.3.1a (Latest version is v1.4.4.2)
```

**Comment by PromoFaux** [comment]
Yeah it will because the update script you currently have is still the old one!

One last manual pull, and you should be golden!

**Comment by PromoFaux** [comment]
This should be fixed now, however the real test is going to come on the next release.

**Comment by Mcat12** [comment]
@M1chael Did the updater work?

**Comment by M1chael** [comment]
Yes. It works now for me.

**Comment by f1vefour** [comment]
For some reason it wouldn't work for me, I couldn't pull the web admin due to overwriting conflict. I had to do this:

```git fetch --all
```git reset --hard origin/master
