### ISSUE TITLE
Whitelist and ipv6

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#834]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x ] The issue I am reporting can be _replicated_
- [ x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ x] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

Added s.youtube.com to whitelist, still get blocked whit ipv6

2016-10-23T17:15:57 A   s.youtube.com   10.10.1.35  OK
2016-10-23T17:15:57 AAAA    s.youtube.com   10.10.1.35  Pi-holed

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
## 
## 
## 

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

**Comment by PromoFaux** [comment]
@Tntdruid To clarify... do you have IPv6 and IPv4 enabled in pi-hole?

please run `pihole -d` 

and also provide the output of `cat /etc/pihole/setupVars.conf`

**Comment by Tntdruid** [comment]
piholeInterface=eth0
IPv4_address=10.10.1.4/24
IPv6_address=2a00:7660:d07:0:b60d:51d9:8329:a9d4
piholeDNS1=8.8.8.8
piholeDNS2=8.8.4.4

**Comment by PromoFaux** [comment]
Yeah, think there may be an issue with the current script.

New scripts incoming in the next release.

**Comment by dschaper** [comment]
Fixed in v2.9.5

**Comment by cybrnook** [comment]
Also seeing similar issues in 2.9.5. Trying to whitelist googleadservices with ipv4 and ipv6 enabled, behaves as though it's still blocked. I also tried a pihole -g to guarantee that the list was processed.

**Comment by Mcat12** [comment]
@cybrnook create a new issue and we'll take a look at it
