### ISSUE TITLE
Search domains Pi.hole or lan?

### ISSUE THREAD

**Issue by psybintea** [pi-hole/pi-hole#839]
Does it matter which is used ? they both have the same  or what appears to be the same effect -- they both work.  but I'm just wondering if one is less desirable, such as what they are doingbehind the scenes that is an obvious to someone like myself.  I have zero technical skills. just wondering sorry for the mundane question you don't have to answer probably wouldn't understand even if you did.i'm just concerned because I'm getting a lot of messages and strange traffic and something about my IP Has been indicated in something like 14,000 attempts withsome kind of loginto some domain in the past hour or something like that to do something I was wondering what what's wrong and Google is telling me that there's strange request coming from my computer and they want to make sure I am a human . should I unplug my pihole

**Comment by PromoFaux** [comment]
Please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when submitting a new issue. It's there to help us to help you!
