### ISSUE TITLE
Stop PI-hole without stoping dnsmasqd service

### ISSUE THREAD

**Issue by develmts** [pi-hole/pi-hole#840]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [X] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST]:**

  Add the option of deactivating pi-Hole without stopping dnsmasqd
  
**[DETAILS]**

The whole idea is to support "deactivating" pi-hole functionality without stopping dnsmasq, maybe because you also use it as a caching nameserver or for any other reason

The best way I can think of is to having two alternative dnsmasqd config files one referencing gravity.list, one not, and restart the service with the required one

If that is implemented we need a way to check, preffererably without checking the dnsmasqd configuration file. It could be implemented by adding one fake server name to gravity.list and doing a dns request for it. We will know before hand that it will be pihole'd, so we can check the dns answer against our own ip adrdress. It doesn't shots any real dns request to the outside, so it doesn't hurt. We only need to exclude it from statistics calculations.

Once that is done. It would be nice that the api servers a status endpoint that differentiates the two possible "running" states, ie running and "pi holing" and "running only"

**Comment by PromoFaux** [comment]
Already in the pipe-line! :)

https://github.com/pi-hole/pi-hole/blob/promoTweaksTheSecond/pihole#L117-L156

**Comment by PromoFaux** [comment]
Including:
![image](https://cloud.githubusercontent.com/assets/1998970/19640933/de374a92-99d6-11e6-81bd-f2e35fd80720.png)

**Comment by develmts** [comment]
Sorry. Searched and didn't found it any issue specifically related. I will be more careful next time

**Comment by PromoFaux** [comment]
:) not a problem at all! It's always a good idea to check the Pull Requests tab too!

**Comment by develmts** [comment]
By the way , is there some kind of provision for the API endpoint  that takes this into account?

Mainly interested cause I'm writing a Port ( very, very alpha stage by now) of Web Interface to NodeJs 
I'm trying to include as much functionality  of pi-hole command line tool options into the interface, so I'm reworking API calls in a backwards compatible mode as much as possible.

**Comment by Mcat12** [comment]
It should be possible, and perhaps in the future it will be moved out (mostly for performance reasons). However, the PR was implemented with the feature built into the page. https://github.com/pi-hole/AdminLTE/pull/173/files
