### ISSUE TITLE
gravity host name to update non-routeable address ( 0.0.0.0)

### ISSUE THREAD

**Issue by mkaliyannan** [pi-hole/pi-hole#841]
This template was created based on the work of udemy-dl.

In raising this issue, I confirm the following (please check boxes, eg [X]):

[x] I have read and understood the contributors guide.
[x] The issue I am reporting can be replicated
[x] The issue I'm reporting isn't a duplicate (see FAQs, closed issues, and open issues).
How familiar are you with the codebase?:

[x] 1 (very unfamiliar)
 2
 3
 4
 5
 6
 7
 8
 9
 10 (very familiar)

I noticed hostip makes delay on youtube ads , why not upgraded to 0.0.0.0. so this won't make delay. Noticed few of youtube ads are not blocking.

**Comment by jacobsalmela** [comment]
Please fill out the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).  I can re-open the issue once you do.

**Comment by dschaper** [comment]
We redirect to the web daemon on the Pi-hole so we can either replace the image (work in progress) or replace the JS with a 404 and immediately return that resultant html code. If well null route the packets we lose that ability, and I believe the browser then waits to timetout instead of getting an immediate server repsonse?

**Comment by mkaliyannan** [comment]
Make sense. Good Job. I haven't went deeper on this code. Is that possible to add regex based filter ? so this way we can block such embedded ads like youtube and others.

**Comment by dschaper** [comment]
We purely handle the DNS calls, we don't proxy, just return the equivalent of a null route. I don't know if the team wants to get involved with selective content or if we just stay with one response for everyone. I'm not up to date with the webserver code and that side of things, others are better to respond to that part of the question.

**Comment by dschaper** [comment]
Check the last few comments of https://github.com/pi-hole/pi-hole/issues/349 and see if that is possibly related to the topic.

**Comment by dschaper** [comment]
Knew this topic sounded familiar, here's a better place: https://github.com/pi-hole/pi-hole/pull/444

**Comment by mkaliyannan** [comment]
cool. I am so much happy with this team. sure. I will take a look and we will see the possibility

**Comment by dschaper** [comment]
Thanks! We can open #444 again if there's any activity on that front.
