### ISSUE TITLE
localhost.localdomain (and others?) being incorrectly blacklisted

### ISSUE THREAD

**Issue by austinheap** [pi-hole/pi-hole#843]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [X] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**BUG Expected Behaviour:** `nslookup localhost.localdomain <pihold address>` shouldn't return anything or should return `127.0.0.1`/`::1`

**BUG Actual Behaviour:** `nslookup localhost.localdomain <pihold address>` returns the address of the Pihole device

**BUG Steps to reproduce:** Install Pihole.

---

Thanks for the awesome project! I think I stumbled into a small bug. (

The list `/etc/pihole/list.0.raw.githubusercontent.com.domains` ([link](http://termbin.com/zxxd)) contains a few entries meant to point to people's local machines (i.e.: `127.0.0.1`/`::1`). Pihole is interpreting the `localhost.localdomain` entry (and others?) to mean that they should be blacklisted, when they shouldn't. The lines in question are:

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

To get around this I've added `localhost.localdomain` to the whitelist which works.

Versions are as follows:

```
::: Pi-hole version is v2.9.4 (Latest version is v2.9.4)
::: Web-Admin version is v1.4.3.1 (Latest version is v1.4.3.1)
```

**Comment by dschaper** [comment]
Thanks for the submission, I do have to ask that you fill out the template for Issues (We all do it, including the developers.) Thank you.

**Comment by PromoFaux** [comment]
So it appears it's only adding `localhost.localdomain` to the list, and not the others. One has to question why they're in the list in the first place?? Should be a simple hardcoded fix to ignore `localhost.localdomain`

```
adam@adam-debian:~$ cat /etc/pihole/gravity.list | grep localhost
192.168.216.236 localhost.localdomain
fe80::6432:41ff:fe5f:999c localhost.localdomain
```

**Comment by tuplink** [comment]
if the client has a properly configured /etc/hosts (\Windows\System32\drivers\etc\hosts) file this query should never leave the client.  my guess as to why they are in there is because most people would put these lists in there hosts file

**Comment by PromoFaux** [comment]
> my guess as to why they are in there is because most people would put these lists in there hosts file

That makes sense. Still, easy to filter it out.

**Comment by brontide** [comment]
While returning 127.0.0.1 is fairly harmless the pihole script does not allow you to whitelist locahost.

```
ewarnke@eric-cb:~$ lxc exec pihole-debian8 -- pihole -w localhost
::: localhost is not a valid argument or domain name
:::
::: No changes need to be made
ewarnke@eric-cb:~$ lxc exec pihole-debian8 -- pihole -w localhost.
::: localhost. is not a valid argument or domain name
:::
::: No changes need to be made
```

You can and should whitelist localhost.localdomain as it should always be NXDOMAIN.

**Comment by tuplink** [comment]
so along this same localhost.localdomain issue       
# tail -f /var/log/pihole.log |  grep query
load the webui > repeate a few times 
and take note of the query

still havent found out where this is coming from but someting is calling localhost.localdomain

**Comment by PromoFaux** [comment]
`localhost` will not be pulled into `gravity.list` as as far as i remember `gravity.sh` will only add a FQDN to the list...

**Comment by brontide** [comment]
I have confirmed that localhost is not in the dnsmasq. configs... so it must be a default that comes from upstream.

**Comment by brontide** [comment]
To turn off localhost you need to add

```
no-hosts
```

To one of the dnsmasq config files.

**Comment by PromoFaux** [comment]
`cron` looksup `localhost` when it fires, and we've no idea why. Discovered that when working on the `db` branch that has a cronjob firing every minute.

**Comment by austinheap** [comment]
@dschaper Sorry, updated the ticket. When I saw that I figured it was spam or a mistake so I just deleted it!

**Comment by dschaper** [comment]
How does this issue manifest itself. If a client machine tries to lookup localhost or localhost.localdomain it's going to see itself and never hit the Pi-hole?

**Comment by Mcat12** [comment]
I found this bug also when working on the Python rewrite. It happens when a client tries to use one of those other localhost type domains, but since they're in some ad lists they redirect to the Pi-hole instead of the actual local machine.

**Comment by dschaper** [comment]
That's odd, the `localhost` query should never leave the local machine, have to check and see if the `no-hosts` idea works. Back into the `dnsmasq` docs again...

**Comment by PromoFaux** [comment]
`localhost` on it's own does not make it into `gravity.list`. The issue here is that one of the block lists contains:
```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

`localhost.localdomain` being an FQDN (apparently) means it's added to `gravity.list`

**Comment by dschaper** [comment]
Oh, well that's different then. It still may be covered under the `no-hosts` directive, just depends on if `dnsmasq` filters before or after sourcing the added hosts files, and if `no-hosts` kills the added hosts files completely.

**Comment by austinheap** [comment]
What @Mcat12 and @PromoFaux said is the behaviour I'm experiencing too.

**Comment by PromoFaux** [comment]
As a workaround for now @austinheap , adding `localhost.localdomain` to the whitelist should do the trick...

**Comment by dschaper** [comment]
Implemented in recent versions.
