### ISSUE TITLE
[BUG] Older version of lighttpd not rewriting js ad queries because of known bug in lighttpd

### ISSUE THREAD

**Issue by brontide** [pi-hole/pi-hole#850]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [X] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[BUG] Expected Behaviour:**

javascript payload

```
ewarnke@eric-cb:~/github/pihole-test$ curl http://10.195.42.87/1.js
var x = "Pi-hole: A black hole for Internet advertisements."
```

**[BUG] Actual Behaviour:**

404 payload

```
ewarnke@eric-cb:~/github/pihole-test$ curl http://10.195.42.87/1.js
<html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>
```

**[BUG] Steps to reproduce:**

Platforms with older lighttpd ( ubuntu 14.04 and debian wheezy that I know of ) have a known bug in [lighttd](https://redmine.lighttpd.net/issues/2526).

**FIX**

Move the url.rewite out of the offending block.   This is has been tested and I will issue a pull once my current pull is closed.

```
# Rewite js requests, must be out of $HTTP block due to bug #2526
url.rewrite = ( "^(?!/admin/).*\.js$"  => "pihole/index.js"   )

# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
    # Create a response header for debugging using curl -I
    setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
}
```

**Comment by dschaper** [comment]
That's one heck of a find, Thanks!

**Comment by brontide** [comment]
It should be in the #846 pull at this point, check the lighttpd.conf files.
