### ISSUE TITLE
[BUG] Pihole ignores HTTPS and Pihole ignores redirects

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#851]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [ x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [? ] The issue I am reporting can be _replicated_
- [x ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [x ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

**[FEATURE REQUEST | QUESTION | OTHER]:**

BUGS

**[BUG | ISSUE] Expected Behaviour:**

Pi-hole should block banned domains

**[BUG | ISSUE] Actual Behaviour:**

Pi-hole still pass banned domains when if they use a redirect

**[BUG | ISSUE] Steps to reproduce:**
- As described in this post how to ban domains and complete domain extensions by wildcard https://github.com/pi-hole/pi-hole/issues/672#issuecomment-247960864
- I have banned the complete .XYZ domain extension with address=/.xyz/192.168.1.200
## \- It use to work but 2 problems..... (**1**) HTTPS sites are still passed trough... example https://blog.heckel.xyz/  (**2**) blocked domains with redirects are passed trough i.e. www.generalassembly.xyz redirects to www.generalassembly.ly. As the first domain ends with .xyz Pihole should stop there and not allow the redirect.

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

**Comment by dschaper** [comment]
In order for a domain to redirect, it has to get a 301 or 302 from the webserver. If you are being redirected, then you are not blocking the `.xyz` domain at all. (Or you have yet to clear your cache and the TTL hasn't expired yet.) We also don't do anything with HTTP(S) traffic, all we do is DNS resolution. 

As asked by the template, can you post the output from `pihole -d` and when directed by the script, visit the sites in question so the log can capture the name resolution. Just post the link to the termbin dump, please don't copy and paste the log in a post here in Issues.

**Comment by dschaper** [comment]
Closing for non-activity.

**Comment by harrypnyce** [comment]
I'm having same/similar difficulties, should i create a new issue?  Will work on submitting output from pihole -d

**Comment by WaLLy3K** [comment]
Please do create a new issue, thanks! 😄

**Comment by harrypnyce** [comment]
Done, thanks!  https://github.com/pi-hole/pi-hole/issues/1725
