### ISSUE TITLE
Pihole unable to ban IP ADDRESS

### ISSUE THREAD

**Issue by nomoreads** [pi-hole/pi-hole#852]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*
- [ ] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

BUG

**[BUG | ISSUE] Expected Behaviour:**

Pihole should ban the IP

**[BUG | ISSUE] Actual Behaviour:**

Pihole doesn;t ban the IP

**[BUG | ISSUE] Steps to reproduce:**

- Both, trying to add a IP to Pihole Admin blacklist and in dnsmasq, as described in this post https://github.com/pi-hole/pi-hole/issues/672#issuecomment-247960864 by adding the folowing address=/213.206.98.70/192.168.1.200
- Want to ban an IP address that is called via a Javascript include and serving OpenX ads selfhosted 
- Script is called on a site with:

<\\\\script type="text/javascript" src="http://213.206.98.70/etc/etc/etc"><\\\\/script>
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

**Comment by PromoFaux** [comment]
This is out of scope for [DNS](https://en.wikipedia.org/wiki/Name_server), which is for translating alphabetical domain names into IP addresses. e.g http://pi.hole to 192.168.1.200

What you are trying to achieve is impossible with pi-hole!

**Comment by nomoreads** [comment]
Thanks, so basically you're saying when adservers, tracking scripts and malware spreaders using a simple JS include that calls a script with an IP address instead of a domain name (letters) it just tricks pihole and and is easily able to serve ads, track analytics and spread malware?

**Comment by dschaper** [comment]
And malware/tracker that uses an IP is going to be BGP blackholed by most ISP's before you can sneeze. That being said, we are an advertisement blocker, not a security product, and make no claims that we do anything related to the security of your network. There are options out there if you'd like to block traffic from an IP.

**Comment by nomoreads** [comment]
@dschaper  How to block an IP?

"We are an advertisement blocker..." well if an advertising network simply orders their publishers to call a script hosted on an IP address instead of a domain (as described above) it simply and easily bypasses Pihole's blocking options and shows ads.

Didn't knew it is that easy to trick Pihole.

**Comment by brontide** [comment]
If you want to block IP addresses then your best bet is to address it with a firewall.  I have my firewall automatically blackhole ip's in various threat blacklists.  Agree 100% with @dschaper, unfortunately, this is far out of scope for the pi-hole project at this time.  It's just not possible to do via DNS.

**Comment by dschaper** [comment]
No, a firewall with DNS rebind protection can.
