### ISSUE TITLE
Development code installer drops to shell on `apt-get` failure.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#864]
**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [x] 10 (very familiar)

---

**[OTHER]:**

Hey @dschaper it would be cool if the development branch code installer had a trap function that told users why exactly (or at least approximately) the installer is kicking out to shell. Let them know that `apt-get` is not updating the indexes correctly, and they just need to run the installer again.

**Comment by brontide** [comment]
I was kicking that around myself the other day and this is what I came up with

```
root@pihole-debian-sid:/var/www/html/admin# output=$(apt-get install foobar 2>&1 ) && echo Success || ( echo "ERROR" &&  echo $output )
ERROR
Reading package lists... Building dependency tree... Reading state information... E: Unable to locate package foobar
root@pihole-debian-sid:/var/www/html/admin# output=$(apt-get install nano 2>&1 ) && echo Success || ( echo "ERROR" &&  echo $output )
Success
root@pihole-debian-sid:/var/www/html/admin# output=$(apt-get install nansdfsdfo 2>&1 ) && echo Success || ( echo "ERROR" &&  echo $output )
ERROR
Reading package lists... Building dependency tree... Reading state information... E: Unable to locate package nansdfsdfo
root@pihole-debian-sid:/var/www/html/admin# 
```

Totally untested code

```bash
install_dependent_packages() {
    # Install packages passed in via argument array
    # No spinner - conflicts with set -e
    declare -a argArray1=("${!1}")

    for i in "${argArray1[@]}"; do
        echo -n ":::    Checking for $i..."
        PKG_MGR_OUT=$(package_check_install "${i}" 2>&1) && echo "Installed!" || ( 
             echo "PACKAGE INSTALL ERROR, SEE BELOW" && echo $output )
    done
}
```

**Comment by brontide** [comment]
No reason we can't also echo ALL the output to the install.log as well.

**Comment by dschaper** [comment]
> # No spinner - conflicts with set -e
That's the key right there... I'll take a look at the logic, I was also looking at seeing if I could wedge in a custom return value and trap on that as well. Basically now since there is no trap, INT and EXIT just drop you on the floor, no cushion. 

Apt does error out with helpful information, but right now we swallow that information, and don't pass it along. (Error with installing package <> try apt update and install again or try --fix-missing) or something along those lines...

As for the log, again subshells and shadows, we spawn a ton of environments and that was part of what I was trying to fix with the `set -e` enforcement, require us to code with convention instead of by committee, or find a happy medium. I don't know if a full dump is helpful to anyone but us. I really like the idea of creating an array to store the installed packages, and not the ones previously installed, for uninstall purposes and dropping that out to log.

**Comment by brontide** [comment]
The way it runs, it only outputs anything if package_check_install returns non 0.  Shunting the output to the log might be useful for debugging which is where it belongs.

**Comment by dschaper** [comment]
So you're suggesting the actual package list and progress should be logged instead of displayed, and only let the user know that packages are being installed, but not what the individual packages are? Interesting idea actually...

**Comment by brontide** [comment]
I think this is better done in code.  Let me spin a feature branch to demonstrate some ideas.  Honestly it might be a lot more stable if we show each package "download only" and then install them all in one big push with the output being logged for any download error and for the actual install.  The only concern I had was blowing the 50mb space check.

**Comment by dschaper** [comment]
Wow, we can adjust the space check, that's not an issue, 8GB is pretty much min anyways for install locations including the Pi, maybe 2GB if using a massive cutdown. Still may have issues with the latest packages, not sure, so a feature would be great to check out. Thanks!

**Comment by brontide** [comment]
```
root@pihole-debian7:~# ./basic-install.sh 
:::
::: You are root.
::: Verifying free disk space...
df: `/sys/kernel/debug/tracing': Permission denied
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Installing apt-utils...Installed!
:::    Installing whiptail...Installed!
:::    Installing git...Installed!
:::    Installing dhcpcd5...Installed!
:::    Installing dnsutils...Installed!
:::    Installing bc...Installed!
:::    Installing dnsmasq...Installed!
:::    Installing lighttpd...Installed!
:::    Installing php5-common...Installed!
:::    Installing php5-cgi...Installed!
:::    Installing curl...Installed!
:::    Installing unzip...Installed!
:::    Installing wget...Installed!
:::    Installing sudo...Installed!
:::    Installing netcat...Installed!
:::    Installing cron...Installed!
:::    Installing iproute2...PACKAGE INSTALL ERROR, SEE BELOW
0
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package iproute2
```

I didn't do the pre-download because it's not universal so I didn't want to hack it without a plan.  I tested on wheezy since that fix wasn't applied yet and I knew I would fail on iproute2.  I'll clean up these few lines and do a PR.

**Comment by brontide** [comment]
Debian 7 again

```
:::    Installing wget...Installed!
:::    Installing sudo...Installed!
:::    Installing netcat...Installed!
:::    Installing cron...Installed!
:::    Installing iproute2...PACKAGE INSTALL ERROR
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package iproute2
::: Sometimes this can be a transitory error, check connectivity and retry
```

and centos 6 

```
[root@pihole-centos6 ~]# ./basic-install.sh 
:::
::: You are root.
::: Verifying free disk space...
df: `/sys/kernel/debug/tracing': Permission denied
:::
::: yum update has not been run today. Running now... done!
:::
::: Checking yum for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Installing iproute...Installed!
:::    Installing net-tools...Installed!
:::    Installing procps-ng...PACKAGE INSTALL ERROR
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.us.leaseweb.net
 * extras: mirror.cc.columbia.edu
 * updates: mirror.teklinks.com
No package procps-ng available.
Error: Nothing to do
::: Sometimes this can be a transitory error, check connectivity and retry
```

At least it gives people an idea where to start.

**Comment by dschaper** [comment]
Should be resolved, using OS based installer now.
