### ISSUE TITLE
Blacklisted domains not being blocked over IPv6

### ISSUE THREAD

**Issue by sootstone** [pi-hole/pi-hole#865]
**In raising this issue, I confirm the following:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [X] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)
---

**[OTHER]:**

Domains that are blacklisted are not being blocked over IPv6 when IPv6 blocking is otherwise working (for the standard Pi-hole domains and adlists) as described here: 
[https://discourse.pi-hole.net/t/domains-added-to-blacklist-only-blocked-over-ipv4/379/27](https://discourse.pi-hole.net/t/domains-added-to-blacklist-only-blocked-over-ipv4/379/27)
## 
## 
## 
##

**Comment by sootstone** [comment]
P.S. Sorry for not replying Dan, I just reached my reply limit! Thanks for your time though :)

**Comment by dschaper** [comment]
Thanks for the catch! Should be fixed in #859 and I'll pull the development branch just to double check.

**Comment by sootstone** [comment]
No problem!

**Comment by dschaper** [comment]
Are you using the development branch or the master released code?

**Comment by Tntdruid** [comment]
You should fix Whitelist ipv6 bug too :)

**Comment by dschaper** [comment]
Thanks, we plan to...

**Comment by Tntdruid** [comment]
ty :)

**Comment by PromoFaux** [comment]
Both off these issues will be fixed in the next release.

**Comment by sootstone** [comment]
Nice! Good work.

**Comment by PromoFaux** [comment]
Fixed in 2.9.5
