### ISSUE TITLE
[DISCUSSION] Uninstall script

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#868]
The uninstall script could really use some love.

At the moment we've kind of neglected it (The last release where we switched to the `install` command even neglects to install `uninstall.sh` into `/opt/pihole`!)

At the moment, it's a rather heavy handed/laborious script that loops through each of the dependencies on the list, and asks the user if they wish to uninstall them. 

[It's been suggested](https://discourse.pi-hole.net/t/bugs-in-pihole-scripts/385/3?u=promofaux) that perhaps we keep track of the packages actually installed by `basic-install.sh` and then just flip that in `uninstall.sh` so that we're not removing anything the user already had installed...

Is there a command we can use on each package to see if other applications are depending on them?

Ideas welcome...

**Comment by tuplink** [comment]
Ubuntu   run "apt-get autoremove -y"     after all packages removed

**Comment by tuplink** [comment]
but apt-get --s install XXXX spits out a list of required

**Comment by PromoFaux** [comment]
The other route we go down, of course, is that we just remove the core pi-hole files and leave all packages we installed in place. Or we could use setupVars to build an array of applications installed by the installer (as in, not already installed when we run through the dependency check)

**Comment by tuplink** [comment]
thats my thought      just remove pihole files.    whos to say i want to remove DNSMASQ and lighttpd    maybe  im using them for something else too

**Comment by PromoFaux** [comment]
If we have a list of applications installed, we can say "Do you wish to remove additonal applications installed by Pi-hole" or something like that.

**Comment by dschaper** [comment]
Or just echo a list of packages we installed with the command that would be needed to remove the packaged. "Run `apt-get remove dhcpcd5 lighttpd ......` to remove installed packages." And remove the pihole user, but that also needs to be added to the install as a trap so that a borked install removes the user as well. (Had that last night, a user got half way through, the install termed but left the user and some files.)

**Comment by PromoFaux** [comment]
This should be sorted in https://github.com/pi-hole/pi-hole/pull/1663
