### ISSUE TITLE
NX Hijacking

### ISSUE THREAD

**Issue by brontide** [pi-hole/pi-hole#872]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [X] 7

---

Only 2 of the presented upstream DNS servers does not NX hijack connections to mistyped domains.  I recommend we either stop using them or put into place the config changes for dnsmasq to block the replies.  I discovered this the other day during the DDoS when I tried swapping out my usual google DNS for comodo.

I suggest we take advantage of the `bogus-nxdomain` dnsmasq option to properly filter these answers.

Google
- 8.8.8.8, 8.8.4.4
- No NX redirection

OpenDNS
- 208.67.222.222, 208.67.220.220
- No NX redirection

Level3
- 4.2.2.1, 4.2.2.2
- NX Hijacking

Norton
- 199.85.126.10, 199.85.127.10
- NX Hijacking

Comodo
- 8.26.56.26, 8.20.247.20
- NX Hijacking

```
echo Google
dig @8.8.8.8 www.bogus.nxdomain +short
dig @8.8.4.4 www.bogus.nxdomain +short
echo OpenDNS
dig @208.67.222.222 www.bogus.nxdomain +short
dig @208.67.220.220 www.bogus.nxdomain +short
echo Level3
dig @4.2.2.1 www.bogus.nxdomain +short
dig @4.2.2.2 www.bogus.nxdomain +short
echo Norton
dig @199.85.126.10 www.bogus.nxdomain +short
dig @199.85.127.10 www.bogus.nxdomain +short
echo Comodo
dig @8.26.56.26 www.bogus.nxdomain +short
dig @8.20.247.20 www.bogus.nxdomain +short
```

```
Google
OpenDNS
Level3
198.105.254.11
104.239.213.7
198.105.254.11
104.239.213.7
Norton
54.200.75.96
54.200.75.96
Comodo
92.242.144.50
92.242.144.50
```

**Comment by dschaper** [comment]
I agree that from a security standpoint the are bad resolvers. But our users have asked for these options in their configuration, and they do have the option for a custom resolver. (Although I suspect most just hit enter at that screen and choose Google, without knowing Google's kind of pervasive data gathering policies...)

**Comment by dschaper** [comment]
I think this is going to be under the wont-fix category. Unless anyone else has any comments.

**Comment by PromoFaux** [comment]
I did wonder about maybe changing the order, so that Google isn't the default.. BUT I would imagine that Google is the most reliable upstream on the list, certainly the biggest. Would we just open up more issues if we chose one of the lesser known ones for the people that hit enter enter enter enter enter

**Comment by dschaper** [comment]
The only thing I would change is swapping OpenDNS for Google on the order. (But same parent company...) Just as stable as Google, same redirection issues.

**Comment by dschaper** [comment]
Security side says Yes! but the practicality of it is that we present the choices to the users, and it's up to them to use the tools as they may. (Damage from pointy objects used incorrectly is covered by the GPL...)
