### ISSUE TITLE
Query time is run off local time not universal time.

### ISSUE THREAD

**Issue by JamesBK** [pi-hole/pi-hole#878]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [X] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)
## Query time is run off local time not universal time.

**[BUG | ISSUE] Expected Behaviour:**
I would expect the logged events to be saved in UTC then shown in the admin console as local time.

**[BUG | ISSUE] Actual Behaviour:**
I had the time set incorrectly on my server and when I updated the timezone to the correct timezone for my location the log showed no requests over the past several hours instead keeping the logged events at what was previously the correct local time, the actual (UTC) time did not change at all, only the local time set on my device

**[BUG | ISSUE] Steps to reproduce:**
Change the time zone to one in the future using `dpkg-reconfigure tzdata.`

Please note I have not tested what would happen when the time zone is one set in the "past", although my immediate assumption would be that it would be problematic.

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/rh71`

**Comment by DL6ER** [comment]
The log time is obtained from the system clock via a `C` call

```
time_t time_now;
time(&time_now);
ctime(&time_now); <--- Generating the string for writing to the log
```

From the `man` page:
> The call ctime(t) is equivalent to asctime(localtime(t)).  It  converts the calendar time t into a null-terminated string of the form

>              "Wed Jun 30 21:49:08 1993\n"

>    The function also sets the external variables tzname,  timezone,  and  daylight (see tzset(3)) with information about the current timezone.

We cannot change this.
