### ISSUE TITLE
Time parameter for enable/disable command [Feature Request]

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#880]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [X] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---

**[FEATURE REQUEST]:**
**One feature I really enjoy about the enable/disable script found on this script: https://www.reddit.com/r/pihole/comments/49aoqv/temporarily_stop_pihole/
Is the ability to set a time parameter, that Pihole will automatically re-enable after
For example, instead of saying "pihole disable", I would like the option of doing "pihole disable 5m" which will disable pihole for 5 minutes, after which point it will automatically be re-enabled**

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment]
Not a terrible idea!, will think about how to best implement it

**Comment by DL6ER** [comment]
This has been implemented.

**Comment by p1r473** [comment]
Hi, what is the command to make this work? 
Thanks

**Comment by DL6ER** [comment]
See [here](https://github.com/pi-hole/pi-hole/pull/933) in the PR I referenced.

> `pihole disable 5s` will disable blocking for 5 seconds
> `pihole disable 7m` will disable blocking for 7 minutes
> etc.

**Comment by p1r473** [comment]
Thanks!
