### ISSUE TITLE
Gerald Ping

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#883]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
```
192.30.252.34 - - [30/Oct/2016 15:03:21] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xf9\x01\x00\x00\xf5\x03\x03X\x16')
192.30.252.34 - - [30/Oct/2016 15:03:21] "▒▒X
                                             ▒l9▒▒T▒,▒9 400 -
192.30.252.45 - - [30/Oct/2016 15:03:31] code 400, message Bad request version ('\xc0\x13\xc0$\xc0(\xc0')
192.30.252.45 - - [30/Oct/2016 15:03:31] "▒▒X
                                             +4▒9Tz▒6▒▒▒3▒▒vD▒+▒/▒,▒0▒▒▒▒▒#▒'▒  ▒▒$▒(▒" 400 -
```
??

**Comment by dschaper** [comment]
Reboot and try again...

**Comment by dschaper** [comment]
Ping?

**Comment by PromoFaux** [comment]
PING

**Comment by PromoFaux** [comment]
seems to be working

**Comment by PromoFaux** [comment]
Hi Dan
