### ISSUE TITLE
Calculation of blocked domains wrong

### ISSUE THREAD

**Issue by Haringstad** [pi-hole/pi-hole#888]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [x] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:** The Webinterface should show double the amount of domains blocked when both IPv4 and IPv6 are enabled/used.

**[BUG | ISSUE] Actual Behaviour:** The webinterface shows only HALF the amount of domains blocked when both IPv4 and IPv6 are enabled/used

**[BUG | ISSUE] Steps to reproduce:** Turning off IPv6 shows double the amount of domains. (setupVars.conf IPv6_address= empty) removed /etc/pihole/.useIPv6. 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Within the php code, the calculation is off.

**Comment by PromoFaux** [comment]
Hi There,

The calculation should be correct, with IPv6 enabled, there are double the amount of entries in `/etc/pihole/gravity.list` so we divide it by 2 to discount the duplicates.

With IPv6 disabled, then the number should stay (roughly) the same as there should be no duplicates in `gravity.list`.

Did you reload gravity after making the change to `/etc/pihole/setupVars.conf`?

Without IPv6:
![image](https://cloud.githubusercontent.com/assets/1998970/19884767/2fd1d16e-a013-11e6-9d2f-2b2ecf70b689.png)

With IPv6:
![image](https://cloud.githubusercontent.com/assets/1998970/19884872/b08b9808-a013-11e6-9f2f-0b2c2e0a9595.png)

**Comment by PromoFaux** [comment]
(side note, the file `/etc/pihole/.useIPv6` is now redundant since we introduced setupVars.conf

**Comment by Haringstad** [comment]
Yes, I forgot to reload....

**Comment by PromoFaux** [comment]
:)
