### ISSUE TITLE
Parsing out URLs from one IP address.

### ISSUE THREAD

**Issue by escapologyBB** [pi-hole/pi-hole#889]
Hi guys,

I'm a really happy user of Pi-Hole and have been for months now, but something just occurred to me and I was wondering if you guys could help me.

I run a Wi-Fi access point for all of the PAs, carers, nurses and other sundry medical people that spend extended periods of time in my house (I'm quadriplegic).  It is completely separated from the private network that my wife and I use which I've done for a couple of reasons, first being so that they don't have access to our private file shares etc and second being that should they do something illegal then I would have some defence and be able to say that I only use our private Wi-Fi access point and not the one that the carers use.

However, it's just occurred to me that I have no proof of that.  So my question is, would it be possible to log every URL that comes from just one IP address and parse it out to a log file as this is what happens in the query log in Pi-Hole interface. Everybody who connects to the Internet through the Wi-Fi access point I set up using a Raspberry Pi shows up as using the same IP address `192.168.0.49`.

Now obviously, IP addresses can be spoofed but it would be one more tick in my column should one of the carers do something they shouldn't on my connection, so if I could capture MAC addresses and anything else as well that would also be great. I'm working on a captive portal at the moment so whoever connects to the access point is informed that it is being monitored, as I don't want to do this in secret.

And yes, I could just not provide free Wi-Fi for people working for me whilst doing nightshifts, but I would rather they be awake when I call for them in the middle of the night because I'm being sick rather than asleep because they  had nothing to do.

I'm largely thinking about illegal filesharing here case anybody's wondering.

Can anybody help,  either in the manner suggested or with a completely new suggestion, I am open to any ideas!  Thanks in advance.  :-)

**Comment by PromoFaux** [comment]
Hi @escapologyBB I noticed you've opened up a reddit thread too, so I'll close this one for now. Probably a better place for discussion (an even better place for discussion would be our shiny new [disourse](https://discourse.pi-hole.net) forums!

**Comment by escapologyBB** [comment]
No problem, I did wonder.  I will get rid of the Reddit post and head over to the new shiny shiny.  :-)


![shining](http://i.giphy.com/4kmCVXOTFBddu.gif)

**Comment by PromoFaux** [comment]
Might as well keep the reddit post up, too! Double the discussion potential !

**Comment by escapologyBB** [comment]
I've posted on discuss and it said it needed a moderator to okay my first post and to be patient, I think I've been patient enough, I mean I have been waiting like 37.6 seconds now and it's still not been approved!

WTF?!   =P

**Comment by brantje** [comment]
Visible here in a incognito screen, so seems it worked :P

**Comment by escapologyBB** [comment]
@brantje Say you can, that was quick!  :-)
