### ISSUE TITLE
custom dns entry's

### ISSUE THREAD

**Issue by stage-newfish** [pi-hole/pi-hole#901]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST/QUESTION]:**

Hey,

i am a web developer and i want to add custom domain names to my dns server. (like http://pi.hole does) To redirect to my project (http://myProject.dev > 192.168.10.x etc.) Is this possible with pi-hole?

**Comment by ntimo** [comment]
That would be a very nice feature. I would like this too.

**Comment by Mcat12** [comment]
Try adding it to the Pi-hole's host file at `/etc/hosts`

**Comment by wioxjk** [comment]
As requested in
https://github.com/pi-hole/pi-hole/issues/812

👍

**Comment by jacobsalmela** [comment]
Votable feature request added [here](https://discourse.pi-hole.net/t/add-option-to-create-dns-records-in-gui/564).
