### ISSUE TITLE
Custom DNS blocking entries by ip range or single ip

### ISSUE THREAD

**Issue by Daiben** [pi-hole/pi-hole#912]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

---
**[FEATURE REQUEST]:**

is it possible to implement custom DNS blocking entries by ip range or single ip.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by diginc** [comment]
If you have a router with a feature rich firewall it could handle IP blocks network wide.  Plugging in a range or single IP into your router's firewall as a block seems like a more logical fit for this type of block.

Firewalls on individual computers wouldn't have the network-wide block effect I think you're looking for, including IPTables (linux's firewall) on the pi-hole.

Even if we did somehow catch that a DNS lookup matched one of our forbidden IPs, the lookup would have already been performed and returned to the client.  Preventing that is most likely not possible using just plain DNSMasq like we do.

If I've misunderstood what you're proposing then please provide a concrete example of how you'd see this working.
