### ISSUE TITLE
Videoplayer Ad: Request for OnceUX vmap failed 

### ISSUE THREAD

**Issue by bakman2** [pi-hole/pi-hole#914]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 2
---
**[QUESTION**
Videos on the Verge displaying ads using the [brightcove](http://docs.brightcove.com/en/perform/brightcove-player/guides/onceux-plugin.html) player. 

These end up in an error:

```Request for OnceUX vmap failed```

To allow them, one would need to use a specific url: http://onceux.unicornmedia.com/now/*
How can this be done in pihole ?

**Comment by jacobsalmela** [comment]
I was able to get rid of this error by whitelisting:
```
pihole -w onceux.unicornmedia.com
```
The ads return, but it stops the player from failing out.  Video ads have always been a challenge and a moving target.
