### ISSUE TITLE
Uninstall script doesn't print next dependency to remove on a new line

### ISSUE THREAD

**Issue by haydenknowles** [pi-hole/pi-hole#916]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [X] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:**
In the uninstall script, after selecting 'n' to skip the removal of a dependency, the next prompt should show on a new line

**[BUG | ISSUE] Actual Behaviour:**
Next prompt does not show on a new line

**[BUG | ISSUE] Steps to reproduce:**

-Run uninstall script
-Skip the removal of a dependency

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Thanks, all PR's need to be based off of our development branch, instead of the master branch, so if you'd like, you can change the base and reopen the PR.

**Comment by haydenknowles** [comment]
Thanks, will do. My first contribution to a GitHub project so please excuse me.

Regards

On 15/11/2016, at 10:32, Dan Schaper <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, all PR's need to be based off of our development branch, instead of the master branch, so if you'd like, you can change the base and reopen the PR.

-

**Comment by dschaper** [comment]
Sure, we have a lot documented in the Contributor Guide to help out or let us know if you get stuck.
