### ISSUE TITLE
Ads leaking through the hole

### ISSUE THREAD

**Issue by lynch3001** [pi-hole/pi-hole#922]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [X] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG] Expected Behaviour:**
Ads should be blocked on ps4 after pointing manually setting dns to pihole. 

**[BUG] Actual Behaviour:**
Ads were fully blocked previously.  In the last few weeks have started getting through. 

**[BUG] Steps to reproduce:**
Watching videos on YouTube on ps4 after about 5-10 videos ads leak through.  Some show after 1-2 videos 
-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**
pi@PiHole:~ $ pihole -up
::: Checking for updates...
:::
::: Pi-hole version is v2.9.5 (Latest version is v2.9.5)
::: Web Admin version is v1.4.4.2 (Latest version is v1.4.4.2)
:::
::: Everything is up to date!

pi@PiHole:~ $ upit
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Ign http://giteduberger.fr rpimonitor/ InRelease
Hit http://giteduberger.fr rpimonitor/ Release.gpg
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://giteduberger.fr rpimonitor/ Release
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://giteduberger.fr rpimonitor/ Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://giteduberger.fr rpimonitor/ Translation-en_GB
Ign http://giteduberger.fr rpimonitor/ Translation-en
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@PiHole:~ $

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
Have you looked over [this thread](https://discourse.pi-hole.net/t/youtube-10-second-black-screen/495)?

**Comment by lynch3001** [comment]
Hi @jacobsalmela thanks for that, looked through that thread, very good and did what it said, but still getting ads.

**Comment by PromoFaux** [comment]
@lynch3001 Could you please run `pihole -d` so we  can better see what's going on? 

Before you end the script (by pressing `ctrl+c`) try to navigate to pages where you have been seeing ads, so that it populates the log file for us. Once it's run, say yes to the prompt for uploading the log and give us the token that it spits out... thanks!

**Comment by dschaper** [comment]
I don't think this is a bug that we can fix right now, YT is putting in advertisements ads in playlists and not pre-roll ads like they used to use. Cat and mouse. But if these are coming in a playlist, it would be rather difficult to select good YT videos versus an ad video.

**Comment by dschaper** [comment]
Closed, no OP follow-up
