### ISSUE TITLE
Addition to uninstall.sh

### ISSUE THREAD

**Issue by zbholman** [pi-hole/pi-hole#923]
Hey guys,

I was having errors trying to reinstall after uninstalling. Turns out the solution was to remove the pihole user using the command
'sudo userdel -r pihole'
figured this should be included in the uninstall since it's being created during the install.

Great work though! Glad to have a working pi hole!

**Comment by PromoFaux** [comment]
Yeah the uninstall script needs a lot more love (I mean, nobody should ever have to use it anyway, right? 😜)

At some point we need to sit down and go over it properly with a fine tooth comb to make sure it does what we need it to... Feel free to submit any Pull Requests that you feel may help!

**Comment by dschaper** [comment]
See #868 for a full discussion thread on the Uninstaller Issue. Closing out this one so we can keep the problems in one thread along with the discussion.
