### ISSUE TITLE
Pi-Hole not blocking any ads

### ISSUE THREAD

**Issue by II12yanII** [pi-hole/pi-hole#943]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open [](issues](https://github.com/pi-hole/pi-hole/issues)).)

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**
i have a raspberry pi 3 with a fresh install of raspbian. i updated rasbian fully just before i installed pi-hole. after i set it up i changed the ip address of my dns to the static ip address i assigned to my pi. i set up pi hole to use opendns. on my desktop when i use the ipconfig /all command it shows the dns servers as the opendns server ip address. so the DNS portion of the pi is working fine with over 600 DNS queries. but i have 0 ad blocks. every single ad from youtube to random news sites show ads everywhere. i followed the steps that were talked about here to no prevail. https://github.com/pi-hole/pi-hole/issues/622
i have kept the default settings. the blacklist and whitelist are default. 

i uploaded my debug log. my debug token is: d3tufs6ysq
-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Can you get us the output from `cat /etc/pihole/setupVars.conf` please?

**Comment by DL6ER** [comment]
Just curious: How do you access the web interface - using the IP address of your Pi? Does `http://pi.hole/admin/` also work for you?

**Comment by dschaper** [comment]
It looks like your list of domains to block on is empty. Can you try running `pihole -g` and see if that helps the situation?

**Comment by II12yanII** [comment]
pi@raspberrypi:~ $ cat /etc/pihole/setupVars.conf
piholeInterface=wlan0
IPv4_address=192.168.0.13/24
IPv6_address=2605:a000:e541:d400:f7d0:30ff:ec0b:fd5c
piholeDNS1=208.67.222.222
piholeDNS2=208.67.220.220

**Comment by II12yanII** [comment]
even after typing in the pihole -g it still doesnt block ads. i went to cnn and there ads all over the screen for me.
[Pi-hole Admin Console.pdf](https://github.com/pi-hole/pi-hole/files/607739/Pi-hole.Admin.Console.pdf)

**Comment by dschaper** [comment]
After the pihole -g it will take a little while for your client to expire their cache of the ad serving domains. You can speed the process along with a `ipconfig /flushdns` on a Windows client or if you are using another operating system then use their process for flushing the DNS cache. Then try visiting the sites again. You do show that the block list is populated now, so things should resolve themselves in a few minutes.

**Comment by II12yanII** [comment]
well its says that its working now. it block 3 ads so it says. but on CNN, fox, reddit and youtube there were ads on each website. so i guess i have some blacklisting to do. do the default blacklist not block very much?

**Comment by Mcat12** [comment]
The default ad lists should block most ads. Try rebooting or reconnecting to your network if you can't flush the dns cache. Also create another debug log so we can check that it is working: `pihole -d`.

**Comment by II12yanII** [comment]
so i rebooted my router and Pi. it works on my laptop but still not on my desktop. for DNS its showing 8.8.8.8 as the dns server. thats googles dns server not openDNS that i have my pi configured to use. the ipconfig /flushdns didnt update it i guess it will just change to the right ip address eventually.  but thanks as of now it blocks ads. ill just have to work on blacklisting youtube. video ads seem to get through on that sometimes. but all other ads are gone.

**Comment by Tntdruid** [comment]
Did you setup IPv6 dns on the clients?

**Comment by dschaper** [comment]
Appears to have been resolved.
