### ISSUE TITLE
Feature request: Add option to update to development version

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/pi-hole#948]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).

**How familiar are you with the codebase?:**

- [X] 9

---
**[FEATURE REQUEST]:**

There are often quite some changes in the `development` branch which mostly fix a lot of open issues for several users. However, many of the users who are rather inexperienced with `git` are not able to benefit immediately. Also, they cannot test themselves if the change we merge into `development` actually suits their needs.

I propose to add an option to be able to easily update pi-hole and the dashboard to the latest `development` / `devel` version for those who are willing to test this.

Example:
`pihole -development`

I'm working on this additional feature right now.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Released code in the master branch. `pihole checkout dev` will pull the latest development branches.
