### ISSUE TITLE
pihole has non-zero exit code

### ISSUE THREAD

**Issue by maweki** [pi-hole/pi-hole#950]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[BUG | ISSUE] Expected Behaviour:**

If I run `pihole -g` or `pihole --help`, it works as expected (and without errors) and therefore returns 0 as an exit code.

**[BUG | ISSUE] Actual Behaviour:**

pihole almost always returns 1 as an exit code. This happens with `pihole --help` as well as (and that's more problematic) with `pihole -g`, even if the update has no errors. This makes it "impossible" to use, for example, `ansible` to update pihole or anything script-like that stops when the first executed command fails.

**[BUG | ISSUE] Steps to reproduce:**

`pihole --help; echo $?`

**Comment by dschaper** [comment]
This is an ongoing thing that we are fixing as we find it. There is some legacy issues that were caused by a coding convention that used 1 as a retval for everything. We're trying to remove that and change to a proper retval for the scripts.

**Comment by Mcat12** [comment]
Update has been released
