### ISSUE TITLE
Pi Hole keeps cutting out

### ISSUE THREAD

**Issue by Burdalfis** [pi-hole/pi-hole#953]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [X] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[BUG | ISSUE] Expected Behaviour:**

Pi Hole redirects URLs associated with ads, therefore blocking them

**[BUG | ISSUE] Actual Behaviour:**

Pi Hole does work, on and off. At time of writing, it isn't blocking ads, I have provided a screenshot below. However Pi Hole is reporting ads being blocked. I can access Pi Hole through http://pi.hole/admin/index.php and through SSH while it is both working and not working.

**[BUG | ISSUE] Steps to reproduce:**

I'm not entirely sure how anyone would replicate this, I cannot find this issue anywhere else. The steps I took to this point are installing the latest version of Raspbian, installing Pi Hole, and I started experiencing the issue. I did some googling, and I found one common issue is not having resolvconf installed, so I installed that, and that fixed everything for a little while, but the problem persists.

**(Optional) Debug Log generated by `pihole -d`:**

http://pastebin.com/0Mjg9ZMB
http://imgur.com/a/wi5CK

**Comment by dschaper** [comment]
Can you re-run `pihole -d` and when the instructions say to browse with a client, try viewing a few sites and then hit CTRL-C to stop the log collection. This will give you the option to upload the logs to us and give you a token to let us know which log is yours.

**Comment by dschaper** [comment]
Also, how do you have the clients set up to receive the DNS address of the Pi-hole? Are you using DHCP, and do you have a secondary DNS set up to go to the clients?

**Comment by Burdalfis** [comment]
Here is my token, Pi Hole is actually working now, I refreshed http://ads-blocker/testing/ three times and all three times I saw no ads. I will give pihole -d another go when it stops working again.

I have set up my router's primary DNS server to the router-set raspberry pi static IP of 192.168.100.2, and I have updated my imgur link above to contain a screenshot of my router's settings.

**Comment by dschaper** [comment]
The debug looks good, let us know if it starts to let ad's through again and well take a look.

**Comment by Burdalfis** [comment]
Alrighty, Will do. Thanks for the excellent response!

**Comment by Burdalfis** [comment]
Aha! It's cut out! I also cannot access it via http://pi.hole/admin/index.php but I can via <pi's IP>/admin.

Here is my debug token for three reloads on http://ads-blocker.com/testing/
270q7tic81

**Comment by DL6ER** [comment]
> I also cannot access it via http://pi.hole/admin/index.php but I can via <pi's IP>/admin

That sound like the Pi-Hole is not your (primary) DNS server as the Pi-Hole would be able to resolve pi.hole to <pi's IP>. Besides that. accessing it via its IP directly will always work, even if the computer doesn't use any of its ad-blocking capabilities.

**Comment by Burdalfis** [comment]
Yeah that makes sense. However in my image above my Pi is clearly set to my main DNS server, I wonder if my router is switching off it for some reason

**Comment by Mcat12** [comment]
Your settings show that you have set a secondary DNS server. Some routers/devices will do a round-robin on DNS servers, sometimes using the first and sometimes the second. This might be happening to you. Try removing the second DNS server.

**Comment by Burdalfis** [comment]
Unfortunately the second DNS server field is empty in the settings, I guess it just chose the best one to put there and did so. What should I put there? I have another Raspberry Pi, but it's one of the original B models when Raspberry Pi was new, and my current Pi-Hole Pi is a Pi3

**Comment by Mcat12** [comment]
One of your images showed a second. If the Pi-hole is the only server, then all devices should be using the Pi-hole.

**Comment by Burdalfis** [comment]
Yeah it's strange, on the left on the second image is my homescreen for my router, and the middle are the DHCP settings, some of them, at least. If I don't define a second IP, it'll round robin between my first IP and a random working DNS pre-programmed into the router, I believe. I have tried pointing the router back to itself or my PC which has a static IP, making it create an error and switch back to the first DNS server, but that failed too.

**Comment by Mcat12** [comment]
Odd. Can you set both primary and secondary to the same Pi-hole?

**Comment by Burdalfis** [comment]
Unfortunately not, it won't let me input an invalid IP or the same IP

**Comment by DL6ER** [comment]
What do you mean by invalid? Does it check if the IP corresponds to a real DNS server? If not, you could try setting your other Pi as secondary DNS server. This will not solve the issue but may help with debugging.

**Comment by Burdalfis** [comment]
Invalid such as 0.0.0.0 and whatnot, IPs that point nowhere. I'm probably going to hook up my second Pi tomorrow and point my router there, see if that fixes my problems. I think my router switches between the two IPs regularly, and if I don't input an IP it chooses one from a list and uses it, as seen from my image of the homescreen. So if both IPs it uses are both pi-holes then it should just switch between the two and block ads no matter what.

**Comment by DL6ER** [comment]
My question was just: What if the second server you supply is no DNS server at all? Might happen that you just cannot load pages sometimes. However, in the cases where pages actually load there should be no ads there.

**Comment by Burdalfis** [comment]
Hmm. I tried pointing the router to itself, I put 192.168.100.1 into the secondary DNS server settings, and the same behavior was observed. I didn't see ads for a while, they came back, and then they stopped showing up again, and it repeated. I do have the router all the devices are connected to plugged into another router, the chain goes: Internet -> Router #1 -> Router #2 -> All devices. The first router had super spotty wifi, so I got another, and so I could still connect to all my devices on ethernet via wifi and vice versa I used just router #2, could that be potentially be causing issues?

**Comment by dschaper** [comment]
Will close this unless there are further issues to discuss.

**Comment by Burdalfis** [comment]
Yeah I've got it all figured out, I didn't configure my devices correctly. Thanks!

**Comment by dschaper** [comment]
Thanks! Let us know if you run into any other issues!
