### ISSUE TITLE
Running Pie Hole along side openvpn Access server

### ISSUE THREAD

**Issue by dwlyles** [pi-hole/pi-hole#954]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- X1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**
So i've got openvpn access server running on ubuntu and it does not require the use of port 80. Port 80 is already set to forward on my router to my machine hosting both openvpn & pie hole.I've gotten pie hole installed and lighttpd will not run, as I get the following error. 
(network.c.405) can't bind to port:  80 Address already in use

If i use the url http://pie.hole/admin I will get a webpage but not statistics. This also confirms that I am not blocking any ads either.

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token. Since it says that port 80 is taken, you have to find out what is blocking use of that port.

**Comment by dwlyles** [comment]
I actually came back to it the next morning after a reboot and its working, thanks for the help!
