### ISSUE TITLE
Installation error----can't resolve domain

### ISSUE THREAD

**Issue by la0wei** [pi-hole/pi-hole#958]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

hostus openvz vps. ubuntu 16.04 kernel 2.6.32-042stab116.1.
After  run curl -L https://install.pi-hole.net | bash
::: We recommend you run 'apt-get upgrade' after installing Pi-Hole! 
:::
:::    Checking for apt-utils... installed!
:::    Checking for whiptail... installed!
:::    Checking for git... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for dnsutils... installed!
:::    Checking for bc... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for lighttpd...

stopped to terminal.
And now can't resolve any domain.
Any one can help?

**Comment by Mcat12** [comment]
I've added the template back to your issue. Please fill it out, as we explicitly say "Failure to fill the template will close your issue". I won't close it this time, but please fill out the information, as it is very useful when when solving issues.

**Comment by la0wei** [comment]
@Mcat12 I'am very sorry,just new here and rush to solve the problem.
I add server = 8.8.8.8 to /etc/dnsmasq.conf
then re run the script,problem solved.
