### ISSUE TITLE
PiHole fail to replace ad page

### ISSUE THREAD

**Issue by paulkramme** [pi-hole/pi-hole#963]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**
Pi Hole should replace ad with empty page

**[BUG | ISSUE] Actual Behaviour:**
DNS lookup fails, which takes time.

**[BUG | ISSUE] Steps to reproduce:**

-Open doubleclick.net
-Wait
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Template not filled.

**Comment by paulkramme** [comment]
Please reopen, GitHub cleared it :/

**Comment by paulkramme** [comment]
Thank you.

**Comment by dschaper** [comment]
It sounds like either your clients have the wrong DNS servers listed or the upstream for you Pi-hole is not correctly set. Can you please run a `pihole -d` and follow the onscreen instructions to browse to a site that is causing problems resolving, and then provide us with the token generated so that we can check your debug logs? Thank you.

**Comment by paulkramme** [comment]
Log: fg9o93pm1f

**Comment by paulkramme** [comment]
PiHole is routers dns, pihole upstream is google dns.

**Comment by Mcat12** [comment]
Your queries are completing in under a second, so the problem doesn't seem to be your Pi-hole. I can't see anything out of order in your log. Are you always having these issues?

**Comment by paulkramme** [comment]
Yes, ive set pi hole as primary and secondary dns in network, so this happens on any device any time. My problem is that these dns timeouts take time when any page with ads load.

**Comment by dschaper** [comment]
How many client machines do you have? The logs just show the device at .1 as being the client to query the Pi-hole, (and if you take a look at the last section of the log, any entery with `/etc/pihole/gravity.list` is a domain that is blocked, it looks like the answers from the Pi-hole are coming in the same second or two as the queries from .1. Is .1 the router for your network? There may be a misconfiguration with the router if it's not handing out the DNS address of the Pi-hole with the DHCP leases to the clients and is instead behaving as an intermediate step and trying to be the DNS resolver itself.

There is a timeout with the PHP which would indicate large log files, can you try a `pihole -f` to flush the logs followed by a `pihole -g` to regenerate the block lists just to see if there is something stuck in one of the processes that is causing the timeout situation?

**Comment by paulkramme** [comment]
I have about 13 devices. The .1 adress is the router and a fritzbox, if that helps, and is properly configured afaik. I will try the flush and respond.

**Comment by paulkramme** [comment]
Well... Now i can access doubleclick.net whivh redirects me to doubleclickbygoogle.com. And then it cant find their dns.

**Comment by Mcat12** [comment]
When it's not blocking ads, are you able to reach pi.hole/admin ?

**Comment by paulkramme** [comment]
I cannot reach it at all... strange. Normaly, i use the ipv4 adress.

**Comment by Mcat12** [comment]
That means that something is causing you to not use the Pi-hole as your DNS server.

**Comment by paulkramme** [comment]
But why does ad block work then?

**Comment by paulkramme** [comment]
Linked to #83?

**Comment by Mcat12** [comment]
Some ads are probably still being blocked because your device's DNS cache still has the domains pointing to the Pi-hole. However, since you hadn't used pi.hole recently, it had to make a new entry in the cache. Since it wasn't using Pi-hole, it couldn't find the address. Just like how you have to wait or flush DNS caches when you first install Pi-hole, the caches can say the domains are blocked when Pi-hole isn't working anymore.

**Comment by paulkramme** [comment]
I fixed the DNS issue, however the problem of DNS not found remains. Now i
have these funny little ad boxes with dns not found pages in it. pi.hole is
now accessible.

**Comment by Mcat12** [comment]
Make another debug log

**Comment by paulkramme** [comment]
Will do, need 3 hours.

**Comment by paulkramme** [comment]
Debuglog: f5ju4rj2wh

**Comment by Mcat12** [comment]
It looks like you're getting ipv6 queries on your network, but have not enabled ipv6 on Pi-hole. Run `pihole -r` and choose Reconfigure to enable ipv6 and ipv4. Try making a debug log where you query one of the domains that your client can't reach.

**Comment by jacobsalmela** [comment]
@paulkramme did enabling IPv6 work?

**Comment by paulkramme** [comment]
Yes. Thank you all very much.
