### ISSUE TITLE
quits blocking ads after a few days

### ISSUE THREAD

**Issue by dgiffen** [pi-hole/pi-hole#967]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

--after a few days it quits blocking ads. I have tried running the gravity script and all appears well. If I reinstall the installation script all starts working again. I am running this on a Ubuntu 16.04 machine, with all updates current.

**Comment by dschaper** [comment]
Can you run the debug process for us? `pihole -d` and if you can do the same when it looks like it's stopped working so we can see if there are any differences in the configurations when it seems to be not working.

**Comment by dgiffen** [comment]
I thought it was stalling out today, seemed stuck on 199
I ran the debug log. Token is lh7oim6eku

I'll keep watching it. I had to do a reboot on the computer earlier for an
update

Thanks
Doug

**Comment by dgiffen** [comment]
Dan,
All day it only got to 200, its usually much higher
I reinstalled
Ran pihole -d here is the token nxh7z6dkk1

Thanks
Doug

**Comment by Mcat12** [comment]
Are you saying you only have 200 DNS queries? That log shows that ad domains are being blocked and other clients are getting their DNS requests fulfilled.
