### ISSUE TITLE
Query log: option to show blocked only

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#968]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST]:**

It would be nice if there was a query log option to only showed blocked entries, not allowed entries. This is quicker than SSHing into my Pi to check the tail of the Pi logs to see what was blocked.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
You can search for `Pi-holed` in the query log, but I agree it would be nice to have a button to do it.

**Comment by Mcat12** [comment]
BTW, soon we're going to be directing feature requests to [our forums](https://discourse.pi-hole.net/) where other users can vote on them.

**Comment by DL6ER** [comment]
I will implement this Feature Request as soon as we know how it should look like.

- Two buttons?
- "Show only blocked" + "Show only permitted"?
- Other wording?
- Other suggestions?

**Comment by p1r473** [comment]
Maybe just a check box saying "Show only blocked"?
A checkbox can take the place instead of 2 buttons (uncluttered UI)

**Comment by p1r473** [comment]
I placed a bounty on this ($5)
I think the Bountysource integration is doing something funny, as it hasn't added the tag automatically here, and there are no "Add a bounty" buttons
So here is the link manually
https://www.bountysource.com/issues/39825622-query-log-option-to-show-blocked-only

**Comment by DL6ER** [comment]
Looking again at this issue I'm actually not sure if we really need it. Got to "Query Log" and click on Status to sort (the date/time will always be the second sort column). You will get what you want.

![screenshot at 2016-12-11 00-05-43](https://cloud.githubusercontent.com/assets/16748619/21076816/c9b2f218-bf35-11e6-97eb-6f38c04583b6.png)

If you really want this, open a Feature Request on Discourse, so other users who would like to see this can vote for it

**Comment by DL6ER** [comment]
Having said that I might simply implement this in the future on the new settings page I am working on. There we might simply add some check boxes like `show allowed queries`, and `show blocked queries`. You could uncheck the allowed ones to get what you want. What do you think?

I'm not a big fan of having even more controls on the Query Log page since it is already quite full (I already added additional pagination control only recently).

**Comment by p1r473** [comment]
I think its a great idea, just to have that one check box.

**Comment by p1r473** [comment]
@DL6ER After using only the sorting column as a method of seeing blocked queries only, I feel this method is actually a little clunky, and do hope you implement this checkbox in your new UI

**Comment by PromoFaux** [comment]
Hi @p1r473 Hope you're well!

Watch this space...

![image](https://cloud.githubusercontent.com/assets/1998970/21306638/f239011a-c5c9-11e6-8dbf-fbe14f8fcbfb.png)

**Comment by p1r473** [comment]
Hi @PromoFaux , thanks!
Is this a dev branch?

Thanks!!

**Comment by PromoFaux** [comment]
Currently on the `devel` branch of AdminLTE and the `development` branch of this repo. 

If you can wait a couple of days though, we're planning on a release for weds...
