### ISSUE TITLE
Pi-hole status is 'Starting' in GUI but is blocking ads & is enabled according to command-line

### ISSUE THREAD

**Issue by Freekers** [pi-hole/pi-hole#969]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)

---
**[BUG | ISSUE] Expected Behaviour:**

Pi-hole's status should be Nominal after being started and the 'Disabled' button should be visible in the web interface.

**[BUG | ISSUE] Actual Behaviour:**

Currently Pi-hole's status is Starting, even though it's blocking ads. Additionally, the 'Enable' button is shown in the web interface implying that Pi-hole is Disabled. However, entering 'pihole status' in the command-line shows that Pi-hole indeed is running.

**[BUG | ISSUE] Steps to reproduce:**
- Install Pi-hole on (a fresh) Diet Pi (v138) image 
- Start Pi-hole

**Debug Log generated by `pihole -d`:**

http://pastebin.com/BdeDcic3

**Screenshot:**
![pihole_starting](https://cloud.githubusercontent.com/assets/1370857/20986227/01995b2e-bcc8-11e6-873e-7ee860851e0f.PNG)

**Comment by Mcat12** [comment]
Did you install Pi-hole via DietPi's installer, or ours?

**Comment by Freekers** [comment]
@Mcat12 I used DietPi's installer, although DietPi claims that it uses the official PiHole installer to install PiHole. See: http://dietpi.com/phpbb/viewtopic.php?f=11&t=816&p=3691&sid=d76c4eb9dbcc57539979ad47350eb5e5#p3691

**Comment by Mcat12** [comment]
What does `pihole status web` return?

**Comment by Freekers** [comment]
@Mcat12 `pihole status web` returns `1`

**Comment by Mcat12** [comment]
Does the web interface still say "Starting" when that command equals 1?

**Comment by Freekers** [comment]
@Mcat12 Yes
![pihole starting2](https://cloud.githubusercontent.com/assets/1370857/20989783/4325e9d2-bcd6-11e6-82b9-96de734fe034.png)

**Comment by Mcat12** [comment]
After refreshing the page (just making sure)? `sudo pihole status web` would probably show the same value, but please check. [This](https://github.com/pi-hole/AdminLTE/blob/master/header.php#L141) is the line that controls what status is shown, so the only think I can think of to make this happen is if the output includes a newline or something...

**Comment by Freekers** [comment]
Yes, even after refreshing the page and indeed, `sudo pihole status web` shows the same value.
Hmm, yes I see. But if the output included a newline, I should be able to see it from the command line right?
Also worth noting; It was working properly in the past, it stopped working since a few days...

**Comment by Mcat12** [comment]
Is there a `pihole` file under `/etc/sudoers.d`?

**Comment by DL6ER** [comment]
What happens if you type `sudo -u www-data sudo pihole status web` as root?
That should also return `1`

**Comment by Freekers** [comment]
@Mcat12 No, there is no `pihole` file under `/etc/sudoers.d`. There only is a `010_pi-nopasswd` file. Should there a `pihole` file as well?

@DL6ER I'm having some issues executing this command. I don't know the password for the www-data user account; it isn't the root password I set and it isn't the default DietPi image password. I'll ask in the DietPi forums and get back to you.

Thank you

**Comment by DL6ER** [comment]
It shouldn't ask you for a password if you are running this command as root.

There should be the following file in `/etc/sudoers.d`:
https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.sudo

**Comment by Mcat12** [comment]
@Freekers Run `pihole -r` and choose Repair. It should try adding that file. Send the output also.

**Comment by Freekers** [comment]
@DL6ER That makes sense, thanks for the explanation :)

@Mcat12 Sadly I read your edit too late. I already ran the `pihole -r` command and now my webinterface is broken; it doesn't load at all any more (just shows a blank page). According to the developer of Diet Pi, they are now using the official installer to install PiHole, so the lighttpd config should be the same, right? See: http://dietpi.com/phpbb/viewtopic.php?f=11&t=816&p=3691&sid=d76c4eb9dbcc57539979ad47350eb5e5#p3691
Any idea how I can fix this without having to start from scratch again?

`pihole -r` output: http://pastebin.com/JpKAKmX9
new `pihole -d` output: http://pastebin.com/MThh0c9n

Many thanks!

**Comment by trinapicot** [comment]
Looks like the php cgi module is not loading in lighttpd. Did you uninstall pi-hole and then reinstall? If so, it could be related to #970 and #971.

You can try `pihole uninstall` and say yes to remove dependencies and yes to remove lighttpd.  Then reinstall pi-hole. This should give you a new lighttpd configuration.

**Comment by Mcat12** [comment]
@Freekers follow @trinapicot's instructions on uninstalling (or if there's a way in dietpi for uninstalling, do it that way). Then reinstall normally like you originally did.

**Comment by Freekers** [comment]
@trinapicot No, I did not uninstall pi-hole and then reinstall, I only executed `pihole -r`

@Mcat12 I uninstalled Pi-hole using DietPi's own installation manager, said y yes to remove dependencies and yes to remove lighttpd. as instructed by @trinapicot, and then reinstalled it the same way (using DietPi's own isntallation manager). Sadly it's still broken; the webinterface still shows a blank page.

installation log: http://pastebin.com/m7Qdwx7c
new pihole -d output: http://pastebin.com/Q2KnUgbd

**Comment by trinapicot** [comment]
@Freekers You should now have a standard pi-hole lighttpd configuration in place which puts the webinterface at http://server/admin/. The dietpi pi-hole configuration puts the webinterface at http://server/pihole/. Is that why you are seeing a blank page?

**Comment by Freekers** [comment]
@trinapicot Indeed, you are correct, the webinterface is now at http://server/admin (d'oh!) and it works!! Good job! I donated a few bucks to keep the project alive. Thanks again for all the help 👍!!
