### ISSUE TITLE
Feature Request - Add tail argument to automatically "tail -f" pihole.log

### ISSUE THREAD

**Issue by skeletorfw** [pi-hole/pi-hole#972]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 6

---
**[FEATURE REQUEST]:**

It would be useful to add an argument `-t` to allow quick tailing of the logs. This would simply call the command `tail -f /var/log/pihole.log`

In order to complete this, the following would need to be added to pihole
_line 43:_
`tailFunc() {
	tail -f /var/log/pihole.log
	exit 0
}`

and

_line 199_
`	"-t" | "tail"				) tailFunc;;`

---

I would add this myself to development, but I'm not very experienced with git, and I'd rather not risk breaking things.

**Comment by jacobsalmela** [comment]
I actually like this idea.  I would change it slightly to be `-F` based on some stuff we are testing in development.  Functionally, it's the same, just a bit more resilient.
