### ISSUE TITLE
Add custom DNS entrees

### ISSUE THREAD

**Issue by paulkramme** [pi-hole/pi-hole#975]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [X] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**FEATURE REQUEST:**
I'd like to add easy DNS entrees, so i can reach my local devices over them. Since hostnames are not working after switching DNS from router to pihole, this would be nice. I'm very sorry if i reposted this, i did not find it under open issues.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Are you asking to use a custom upstream provider for your DNS server (in place of Google or OpenDNS for example) or are you asking about entering data into the Pi-hole's HOSTS file so that you can reach local machines by their short names?

**Comment by paulkramme** [comment]
Latter.

**Comment by Mcat12** [comment]
Add your hosts to your Pi-hole's `/etc/hosts` file.

**Comment by dschaper** [comment]
Okay, I will pass that along as a feature request, it's possible to do now, if you use the Pi-hole's `dnsmasq` process as your DHCP server, but we need to work out a way to safely edit the `/etc/hosts` file and determine a process to present those options to the users. If the Pi-hole also acts as the DHCP server, then `dnsmasq` will automatically add the short name to the resolver's lookups but this would require disabling the DHCP server on the router and passing that function over to the Pi. It's a feature we are talking about, but we want to do it in a sane way that will hopefully avert the possibility of a user locking themselves out, :) If you'd like to open a Feature Request over on Discourse.Pi-hole.net then other users will be able to vote and comment on the idea.

**Comment by jannylund** [comment]
@paulkramme an easy workaround for this is to set pihole to use your routers dns instead of google, then your local host config works as before.

**Comment by paulkramme** [comment]
Yes, im aware of that, but id loose the performance improvement, and this
is not an option for me.

**Comment by woftor** [comment]
Edit the file `/etc/dnsmasq.d/03-pihole-wildcard.conf`

Add entries like this:

> address=/printer.mydomain.com/192.168.2.9
> address=/babycam.mydomain.com/192.168.2.10

This working very well. Don't forget to flush DNS on Windows machine when testing.
You cannot enter these values in the webinterface, there only default values are possible (it's the wildcard option).

**Comment by ldrrp** [comment]
https://www.bountysource.com/issues/39915327-add-custom-dns-entrees

**Comment by paulkramme** [comment]
@ldrrp Wow! Thats great, hopefully it will boost this feature.

**Comment by woftor** [comment]
You can also make a **new file** in `/etc/dnsmasq.d/` with `.conf` extentsion. All files in this directory are read by dnsmasq. You can add DNS entries just like I said in my previous post like this:

```
address=/printer.mydomain.com/192.168.2.9
address=/babycam.mydomain.com/192.168.2.10
```

Again: it would be very nice if this were added to the web-gui.

**Comment by paulkramme** [comment]
I think i will write a program for this, i will link this here when im finished. Can i name the file whatever i want, like `mom.conf`?

**Comment by dschaper** [comment]
Conf files are sourced lexicographically, so 01 first, but typically they are named with a number leading, so 99 would be sourced last, so a 50-mom.conf would be in the middle and can still be overridden. (`dnsmasq` will throw errors if commands are duplicated, but should be okay if they are appending.)

**Comment by paulkramme** [comment]
If i write this, would it be possible to include this into the project as a
repository, so others could use this? Maybe it could be used from pihole
itself..?

>

**Comment by DL6ER** [comment]
Unfortunately, I don't have much time this week, but I will look into this issue. I don't need this as I'm using the Pi-hole DHCP server, which already adds this functionality.

**Comment by paulkramme** [comment]
I created a [repository](https://github.com/paulkramme/dns-add)

**Comment by ldrrp** [comment]
@paulkramme its probably better to add it to the web interface since it is protected by a login.

**Comment by paulkramme** [comment]
Yes, i agree.

**Comment by tobiastom** [comment]
Just as a small addition, this might also be a nice feature to configure specific addresses to a given localised IP, this would solve some problems with geo location based IPs.

**Comment by Mcat12** [comment]
It looks like this feature has been implemented: #1266

**Comment by tobiastom** [comment]
This is awesome. Somehow it looks all documentation is only available inside the pull request. 

Thank you @Mcat12 for the update!

**Comment by mikegleasonjr** [comment]
For those wondering how to add multiple entries, add your entries to `/etc/hosts` then `$ pihole restartdns`

**Comment by elBradford** [comment]
The 'solutions' here don't really do anything that editing the hosts file doesn't do already, correct? I'd love a DNS entry page in the WebUI for this purpose. I can take a crack at adding the feature if there's a chance my pull request would be approved.

**Comment by Comodore125** [comment]
Very unfortunate to see this closed.

**Comment by dschaper** [comment]
It's been implemented in https://github.com/pi-hole/pi-hole/pull/1266 hence it was closed.

**Comment by elBradford** [comment]
@dschaper That merge requests allows for a _single_ DNS entry, whereas this feature request is for _multiple_ entries and in my opinion, from the WebUI.

**Comment by dschaper** [comment]
We can only do so much with the volunteer time we have, if you have a PR that you'd like to submit or code suggestions then we can look at implementing it. There are a lot of feature requests and none of the developers work on this full time. I appreciate the thumbs down votes, they help prioritize what we should work on next.

**Comment by dschaper** [comment]
There's a bounty on it, if a user codes a solution they can claim the bounty and make some money off of it.

**Comment by hopeseekr** [comment]
So it's safe to say that 15 months later nothing has been accomplished?

**Comment by DL6ER** [comment]
> So it's safe to say that 15 months later nothing has been accomplished?

As there hasn't been a pull request referencing this issue ticket, I assume the answer is Yes.

**Comment by Zixim** [comment]
If you have the possibility to set pihole as your DHCP server, then you can assign hostnames to devices from the DHCP config page.

**Comment by hopeseekr** [comment]
I'm much more interested in setting a custom DNS entry for https://archive.is/, as seeing how they actively block CloudFlare DNS from querying them (they point to 127.0.0.4).

**Comment by dschaper** [comment]
Is there anything currently stopping you from doing so?

**Comment by Ilshidur** [comment]
There s CLI command for this :

`pihole -a hostrecord subdomain.example.com 1.2.3.4`

**Comment by makeworld-the-better-one** [comment]
@Ilshidur Are there commands to list or remove records? I can't find them.

**Comment by Zixim** [comment]
add : `pihole -a hostrecord home.mydomain.de 192.168.1.10`

list :  `grep 'host-record' /etc/dnsmasq.d/01-pihole.conf`
But listing seems of little use, since you can add just the 1 hostrecord.

remove : `pihole -a hostrecord`

**Comment by makeworld-the-better-one** [comment]
Oh you can only add one? I didn't realize. Thanks!

**Comment by Zixim** [comment]
at present, the cleanest way to add your own dns records would be : 

- make sure that `/etc/dnsmasq.conf` contains the line : `conf-dir=/etc/dnsmasq.d`
- create a file in `/etc/dnsmasq.d` to store your custom dns records : 
```
$ ls -lha /etc/dnsmasq.d
total 57K
drwxr-xr-x  2 root root    7 Oct 31 10:52 .
drwxr-xr-x 95 root root  187 Oct 29 10:27 ..
-rw-r--r--  1 root root 1.6K Oct 31 10:52 01-pihole.conf
-rw-r--r--  1 root root  488 Oct 27 11:45 02-pihole-dhcp.conf
-rw-r--r--  1 root root 1.9K Aug 13 15:57 04-pihole-static-dhcp.conf
-rw-r--r--  1 root root   47 Jun 22 11:54 98-hostrecords-dns.conf
-rw-r--r--  1 root root  175 Aug 13 15:59 99-reservations-dhcp.conf
$ cat 98-hostrecords-dns.conf
host-record=mydomain.duckdns.org,192.168.1.10
``` 
Add as many host-record lines as you like.

- Don't forget to `pihole restartdns` if you add/remove domains.

**Comment by eitch** [comment]
I tried this on my pihole, and somehow the DNS system didn't want to start anymore. I have no added the records to 

    /etc/pihole/local.list

and now it works as expected

**Comment by Zixim** [comment]
@eitch Don't use local.list , it is a system generated file and will get overwritten sooner or later by updates & such.

**Comment by eitch** [comment]
@Zixim then there is a bug, when using the host-records directive the pi-hole manager says the DNS service does not start, which i can see as i can't lookup any addresses anymore?

**Comment by Zixim** [comment]
did you perhaps edit the .conf file with a windows text editor ?
``dnsmasq --test`` will do basic syntax checks on the config files

**Comment by eitch** [comment]
Weird... i just tried again and now it works. I prepared to check all logs, FTL, pihole, daemon.log etc. but no error and it works as expected. I only move back the file which i had given the ending .bck to 98-hostrecords-dns.conf and performed a restart. Thanks anyhow!
