### ISSUE TITLE
pi's ip at no 1 Top advertisers

### ISSUE THREAD

**Issue by Binog** [pi-hole/pi-hole#980]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [x] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:**
No appearance of pi's Ip in Top advertisers. At least it shouldn't advertise..

**[BUG | ISSUE] Actual Behaviour:**
No 1 advertiser as stated in the GUI is the IP-Adress of the Raspi, on which pi-hole is running. I guess, that shouldn't be like this...

**[BUG | ISSUE] Steps to reproduce:**
Since last upgrade, I found this circumstance. Had a look at https://github.com/pi-hole/pi-hole/issues/843, but that seems to bee a different.
-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

` Detecting Installed Package Versions:
:::       Pi-hole: v2.9.5
:::       WebUI: v1.4.4.2
:::       lighttpd/1.4.35
:::       PHP 5.6.27-0+deb8u1 (cli) (built: Oct 24 2016 18:22:27) 

everything seems to be fine, except: 
:::  Detecting existence of /etc/pihole/adlists.list:
:::  /etc/pihole/adlists.list not found!`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Binog** [comment]
Can anyone help?

**Comment by DL6ER** [comment]
Sorry for not responding earlier. We are in the middle of preparing a huge release that needs intense testing and have been quite busy.

One question to you: Did you upload a debug log?


`/etc/pihole/adlists.list not found!` is no error, it just means that you don't have a customized list but are using the default ad lists.

Could you also provide a screenshot of your Top Ads table? It should not include IPs, but only host names, like you see here (screenshot from my Pi-hole at home):
![screenshot at 2016-12-18 21-48-24](https://cloud.githubusercontent.com/assets/16748619/21296433/de026f1e-c56b-11e6-9318-88cd0d26edd1.png)

**Comment by Binog** [comment]
Thanks for replying ! Well my pi's IP adress is the only one. 
Well, I did not upload a debug log. Is there a difference between the output I can see via -d and the one You can see in the uploaded log?

![topadv](https://cloud.githubusercontent.com/assets/11355616/21305148/1c45718c-c5ca-11e6-9308-07f436e3055a.jpg)

**Comment by DL6ER** [comment]
Well, Yes and No. There is a difference to what you quoted here. The debug script will have given you some output at the very end like:
> A local copy of the Debug log can be found at :  `/var/log/pihole_debug.log`

We assure you that your details will be treated with the strictest confidence.
The log will contain e.g. some data that is collected within the 60 seconds where you are asked do some test browsing. We can use this data to investigate what is happening in your case.

You can also provide us with more detail about your local setup: Are you using VPN? Are you in a standard home network (one router that is also DHCP server)? Etc. The better we understand your local networking environment, the better we can help in solving your problem.

**Comment by Binog** [comment]
OK, here is the token: 7wr51g83zo  
I am using a standard router (DHCP), that has the DNS-IP of my raspi on which pihole is running. That works very well. In this configuration the raspi has the x.x.x.20 IP, which appears in the top ads, as we can see in the picture. In this configuration I don't use a VPN.
Hope that helps.
Thx for Your support so far

**Comment by PromoFaux** [comment]
Hi @Binog,

I think I've found the culprit. What device do you have on `10.0.1.2`?

It appears to be doing reverse lookups, something which I only have a vague understanding of myself!

```
Dec 19 08:37:39 dnsmasq[18783]: query[PTR] 20.1.0.10.in-addr.arpa from 10.0.1.2
Dec 19 08:37:39 dnsmasq[18783]: /etc/pihole/gravity.list 10.0.1.20 is 0000mps.webpreview.dsl.net
```

**Comment by Binog** [comment]
Hey .2 is a NAS device. Oh yeah, it  has network Scanner in Board. Shouldnt run permanently but obviously it does. Either way, that Could be the reason?

**Comment by DL6ER** [comment]
Yes, I looked at your log for other possible explanations. Your log seems perfectly fine despite those many `[PTR]` requests from your NAS device contaminate the log with false-positives in a way that I haven't seen before.

I have an idea how we can fix that, but have to discuss this code change with the others of our team after we have the current release out.

**Comment by DL6ER** [comment]
I think the problem you are seeing should be fixed with the upcoming release. However, please test it once it is out over several days and tell us what you see (close the issue if solved, tell us if it is still there).
