### ISSUE TITLE
Command Not Found Errors in Cron'd updateGravity

### ISSUE THREAD

**Issue by ghalfacree** [pi-hole/pi-hole#982]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [X] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:**
The Pi-Hole updateGravity cron job automatically created during installation should run, update everything, restart stuff, and exit cleanly with no errors, even though I'm running on an Ubuntu 14.04 server rather than a Raspberry Pi.

**[BUG | ISSUE] Actual Behaviour:**
What actually happens is the following:

```
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
::: Getting sysctl.org list... No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting hosts-file.net list... No changes detected, transport skipped!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 129108 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 104980 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
/opt/pihole/gravity.sh: line 216: pihole: command not found
::: Whitelisting 9 domains... done!
::: Nothing to blacklist!
::: Formatting domains into a HOSTS file...
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...
/opt/pihole/gravity.sh: line 317: pihole: command not found
/opt/pihole/gravity.sh: line 353: pihole: command not found
```

Note the errors from script lines 216, 317, and 353 which claim the ``pihole`` command can't be found. These correspond to the whitelisting, restarting DNS forwarder, and DHCP server steps of the update process.

Oddly, these errors do *not* appear if ``pihole -g`` is run directly from an interactive shell. Instead, everything works absolutely fine. ``pihole`` itself is in ``/usr/local/bin/`` and is owned by root with read, write, and execute permissions.

**[BUG | ISSUE] Steps to reproduce:**
Install Pi-Hole on an Ubuntu 14.04 server. Let the updateGravity cron job execute. Take a shufti at the log.

**Comment by DL6ER** [comment]
This has been reported [here](https://discourse.pi-hole.net/t/errors-during-weekly-gravity-sh-update-cron/805/4).

The problem is that the the `PATH`s of `root` and `root` (as executed from `cron`) is different:
- `root`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
- `root` (as executed from `cron`): `/usr/bin:/bin`

**Comment by DL6ER** [comment]
@ghalfacree Please test if #983 solves your problem. This is completely untested right now.

**Comment by ghalfacree** [comment]
@DL6ER: It looks like it should, but just where should I apply the changes - in other words, where does Pi-Hole keep its crontab? The only entries I have in ``/var/spool/cron/crontabs`` are for my main user and root, and the Pi-Hole rules don't appear in either of 'em.

(Sorry if I'm missing something obvious or being particularly dense!)

**Comment by DL6ER** [comment]
Look here: `/etc/cron.d/pihole`

**Comment by ghalfacree** [comment]
@DL6ER: I can confirm that #983 works absolutely perfectly. Thanks!

```
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
::: Getting sysctl.org list... No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting hosts-file.net list... No changes detected, transport skipped!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 129934 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 105888 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 9 domains... done!
::: Nothing to blacklist!
::: Formatting domains into a HOSTS file...
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...
 * Restarting DNS forwarder and DHCP server dnsmasq
   ...done.
::: Pi-hole blocking is Enabled
```
